### ISSUE TITLE
Problem with translation of the new "Output" tab

### ISSUE THREAD

**Issue by benrom** [Microsoft/vscode#19796]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-simpler-icons|davidbabel|1.3.0|
|vscode-elixir|mjmcloug|0.1.1|

---

Steps to Reproduce:

1. Using the French version of Visual studio, the "Output" console tab title shows correctly "Sortie" 
![image](https://cloud.githubusercontent.com/assets/22596367/22583844/62692020-e9ef-11e6-880b-c22313ae23fb.png)

2. Now click on this tab. The tab title changes to "Output". Click on other tabs, it stays like this.
![image](https://cloud.githubusercontent.com/assets/22596367/22583851/68d662a6-e9ef-11e6-86ab-6e268128eed9.png)
![image](https://cloud.githubusercontent.com/assets/22596367/22583858/6d42797e-e9ef-11e6-8158-34fe9e95d0a9.png)

**Comment by bpasero** [comment]
Yes, this is an issue with our translation input. This is because 1.9 is not fully translated yet.

fyi @dbaeumer

**Comment by johnliu2016** [comment]
All "output" instances are localized to FRA in current loc resources pool, @dbaeumer, is the mentioned 1.9 release build input to loc process?

**Comment by dbaeumer** [comment]
Verified. Is translated in the latest build.

![capture](https://cloud.githubusercontent.com/assets/1931590/22641560/87eb91d8-ec57-11e6-8660-72af0bcd6310.png)

**Comment by johnliu2016** [comment]
Thank you @dbaeumer
