### ISSUE TITLE
The "Move to a new file" action should allow to specify the new file's name and location

### ISSUE THREAD

**Issue by TheKoTech** [microsoft/vscode#197909]
Currently on the "Move to a new file" action, the selected code is moved to a new file is created in the same folder and named after the entity that was selected. 

It would be nice if the user was able to specify the new file's name and location, saving them a few actions

**Comment by lramos15** [comment]
I'm not sure what move to new file action you're mentioning. Can you provide a screenshot just so I can know what feature you're referring to

**Comment by lramos15** [comment]
Closing due to lack of info
