### ISSUE TITLE
Terminal Font are screwed in new version of vs code

### ISSUE THREAD

**Issue by fssrepository** [microsoft/vscode#197940]
![font_messed_up](https://github.com/microsoft/vscode/assets/45578746/eef54872-36d8-424b-bcaa-c4e57a3bd281)
Type: <b>Bug</b>

Terminal Font in Docker container has been messed up.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 5.4.0-166-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2773)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.55GB (10.36GB free)|
|Process Argv|--unity-launch --crash-reporter-id b52cb55a-2296-4f0e-8dc5-b3ec4f0c4487|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.16.1
gitlens|eam|14.4.0
go|gol|0.39.1
mongodb-vscode|mon|1.3.1
vscode-docker|ms-|1.27.0
remote-containers|ms-|0.315.1
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
gradle-language|nac|0.2.3
java|red|1.23.0
vscode-yaml|red|1.14.0
vscode-gradle-extension-pack|ric|0.0.4
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.49.0
vscode-gradle|vsc|3.13.0
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.14
vscode-java-test|vsc|0.40.0
vscode-maven|vsc|0.42.0
vscode-spring-boot-dashboard|vsc|0.13.1
vscode-spring-initializr|vsc|0.11.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss2:30886141
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30886110
dsvsc017cf:30886113
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by fssrepository** [comment]
I had to "terminal.integrated.fontFamily": "monospace", which solved the problem in the settings.

**Comment by meganrogge** [comment]
We only support monospace fonts in the terminal. If you want to use one that's not monospace, you have to configure `fontFamily`.

**Comment by fssrepository** [comment]
> We only support monospace fonts in the terminal. If you want to use one that's not monospace, you have to configure `fontFamily`.

then the plugin should do it as default, instead of digging to the settings.json, i just wanted to work, i didn't even know that there is no defaulf fontfamiliy for that plugin.

**Comment by fssrepository** [comment]
> We only support monospace fonts in the terminal. If you want to use one that's not monospace, you have to configure `fontFamily`.

then the plugin should do it as default, instead of digging to the settings.json, i just wanted to work, i didn't even know that there is no defaulf fontfamiliy for that plugin.
