### ISSUE TITLE
Option to auto-close readonly code tab upon ending debug session

### ISSUE THREAD

**Issue by dkfdkdodkms** [microsoft/vscode#197949]
After ending a debug session the readonly code tab that was opened does not auto-close. This is frustrating, because I often start trying to edit this file without thinking, and of course I cannot.

**Comment by mohammadamin16** [comment]
If this issue is still valid, I'd love to work on it.

**Comment by cremick** [comment]
I would like to work on this bug as well

**Comment by connor4312** [comment]
THis is still valid, feel free to give it a shot!

**Comment by mohammadamin16** [comment]
Great! I'll try then:)

**Comment by mohammadamin16** [comment]
@dkfdkdodkms, I tried to start a debugging session, but it doesn't seem to create a read-only tab for me.
What language you are using and what are the steps to reproduce this issue?

**Comment by mohammadamin16** [comment]
@connor4312 I would really appreciate it, if you could take the time and review this PR.

**Comment by connor4312** [comment]
Completed in #199898

**Comment by rzhao271** [comment]
Confirmed that enabling the setting `debug.closeReadonlyTabsOnEnd` doesn't resolve the issue on Windows.
