### ISSUE TITLE
Trouble with check50 cs50/problems/2022/python/outdated

### ISSUE THREAD

**Issue by RonGarza** [microsoft/vscode#197975]
I found Help somewhere on GitHub before,  when check50 was complaining about something. At that time, I was prompting the user when I was not supposed to. That Hint got me passed the problem. BUT, I don't remember how I got there. 

At this time, the check 50 of outdated.py is complaining about October/9/1971 and September 8 1636 re-prompting when these inputs should have been rejected. My tests show that they are rejected, not re-prompted. 

How to I get to the Github feature that shows where previous students have solved problems like this one? 

-- RonGarza@hotmail.com

ADD ISSUE DESCRIPTION HERE

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
Please use the course support channel.
