### ISSUE TITLE
Context view sometimes appear in top left corner

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#197987]
![image](https://github.com/microsoft/vscode/assets/900690/468c7737-6611-42fc-9ae6-63bbd25a5e9e)

If anyone has steps how to reliably reproduce, please speak up. It seems to happen when invoking quick fix command in editor or in the explorer:
* rename a file
* remove its name so that the input box is empty

**Comment by Deepakvrma14** [comment]
maybe it's about the toolbar settings you have used, have a look around it in file>preferences>workspace>toolbar settings

**Comment by bpasero** [comment]
Hopefully https://github.com/microsoft/vscode/commit/af63c41918a0608c2385d79efc8b1b5b3a033339 fixes it.
