### ISSUE TITLE
[URGENT]Update broke my vs code in Linux

### ISSUE THREAD

**Issue by Deepakvrma14** [microsoft/vscode#197981]
idk how but my vs code got automatically updated to v1.84.1 (am on Fedora Linux) and when i opened vs code, it's showing this screen
![image](https://github.com/microsoft/vscode/assets/86903293/2a6731e6-0b38-4be5-9208-ad7a9ba958a5)

thogh all the buttons are working i tried hovering on buttons i know the positions but gui got broken
![image](https://github.com/microsoft/vscode/assets/86903293/e7a01551-9523-4469-b008-e849d72e1f45)

i tried updating to latest v1.84.2 via cmd but that too didnt worked ,tried installing insiders version that too isnt working as well , kindly fix this it's a big issue

**Comment by Deepakvrma14** [comment]
> idk how but my vs code got automatically updated to v1.84.1 (am on Fedora Linux) and when i opened vs code, it's showing this screen ![image](https://user-images.githubusercontent.com/86903293/282215618-2a6731e6-0b38-4be5-9208-ad7a9ba958a5.png)
> 
> thogh all the buttons are working i tried hovering on buttons i know the positions but gui got broken ![image](https://user-images.githubusercontent.com/86903293/282215703-e7a01551-9523-4469-b008-e849d72e1f45.png)
> 
> i tried updating to latest v1.84.2 via cmd but that too didnt worked ,tried installing insiders version that too isnt working as well , kindly fix this it's a big issue

**Comment by Deepakvrma14** [comment]
my issues havent been addressed

**Comment by Akay7** [comment]
I got the same issue, version 1.84.2 at OpenSUSE Tumbleweed.

![image](https://github.com/microsoft/vscode/assets/7696441/5bb990fa-bb47-4d8d-a0a5-d3d7152bd98f)

**Comment by Deepakvrma14** [comment]
> I got the same issue, version 1.84.2 at OpenSUSE Tumbleweed.
> 
> ![image](https://user-images.githubusercontent.com/7696441/282230615-5bb990fa-bb47-4d8d-a0a5-d3d7152bd98f.png)

i searched for it a while and finally got a fix, it was nothing but our gpu which was causing the problem., the fix is quiet simple, just to disable the gpu while oepning the code, incase you open it via cmd, you can use 
`code --disable-gpu`

If this happened after an update, deleting the GPUCache directory can resolve the issue(this worked for me

`rm -r ~/.config/Code/GPUCache`

**Comment by Akay7** [comment]
Thanks @Deepakvrma14 I deleted cache with `rm -r ~/.config/Code/GPUCache` and it helps.
