### ISSUE TITLE
Node debugging does not work after update

### ISSUE THREAD

**Issue by AntonBozhinov** [Microsoft/vscode#19798]
Node debugging stopped working after the latest update to version 1.9
Debugger starts listening on port XXX then freezes on the warning message that it is experimental feature. Any help?

- VSCode Version: January 2017 (version 1.9)
- OS Version: Windows 10 Pro version 1607

launch.json

``` json{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node2",
            "request": "launch",
            "program": "${workspaceRoot}/index.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy",
                "--preserve-symlinks"
            ],
            "env": {
                "NODE_ENV": "development",
                "NODE_PATH":"dev"
            },
            "sourceMaps": false,
            "outFiles": []
        },
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": false,
            "outFiles": [],
            "localRoot": "${workspaceRoot}",
            "remoteRoot": null
        },
        {
            "name": "Attach to Process",
            "type": "node",
            "request": "attach",
            "processId": "${command.PickProcess}",
            "port": 5858,
            "sourceMaps": false,
            "outFiles": []
        }
    ]
}
```

**Comment by Robban1980** [comment]
+1

Same problem here.

**Comment by isidorn** [comment]
This looks like the `"node2"` debugger. For now you can change the type to be `"node"`
Assigning to @roblourens

**Comment by weinand** [comment]
Does it help if you change the debug type from `node2` to `node`?

**Comment by Robban1980** [comment]
I was using "node" same problem there. 
But just downgraded to 1.8.1 and everything is working again.

**Comment by AntonBozhinov** [comment]
Changing the type from `node2` to `node` worked for me. Thank you!

**Comment by weinand** [comment]
@AntonBozhinov probably because node v7.5.0 doesn't support the v8 debugging protocol any more (I think).

**Comment by roblourens** [comment]
That shouldn't be the case yet...

Can someone set `"diagnosticLogging": true` in their launch config, and upload the log from the path that it prints at the top of the debug console?

**Comment by roblourens** [comment]
Or if the app you're debugging can be shared, I'd like to try it out.

**Comment by renanborgez** [comment]
Same problem +1

**Comment by weinand** [comment]
@renanborgez your problem seems to be unrelated this issue because you needed the opposite workaround to make it work again.

**Comment by fearthecowboy** [comment]
I this this is what I'm seeing too.

attached log with `"diagnosticLogging": true`
[vscode-node-debug2.txt](https://github.com/Microsoft/vscode/files/790850/vscode-node-debug2.txt)

`launch.json ` : 
``` json
{
  "version": "0.2.0",
  "configurations": [{
    "diagnosticLogging": true,
    "type": "node2",
    "request": "launch",
    "name": "bootstrapper",
    "program": "${workspaceRoot}/src/bootstrapper/app.js",
    "cwd": "${workspaceRoot}/src/bootstrapper",
    "sourceMaps": true,
    "outFiles": [ "${workspaceRoot}/src/bootstrapper/**/*.js"
      ,"!${workspaceRoot}/src/bootstrapper/node_modules/**"
     ]    
  }],
  "compounds": []
}
```


other try with simpler `launch.json`
``` json
{
  "version": "0.2.0",
  "configurations": [{
    "diagnosticLogging": true,
    "type": "node2",
    "request": "launch",
    "name": "bootstrapper",
    "program": "${workspaceRoot}/src/bootstrapper/app.js",
    "cwd": "${workspaceRoot}"
  }],
  "compounds": []
}
```
[vscode-node-debug3.txt](https://github.com/Microsoft/vscode/files/790864/vscode-node-debug3.txt)

**Comment by roblourens** [comment]
@fearthecowboy Your problem doesn't sound like the others, they said it freezes when starting. In your case, the log says you set a breakpoint in `gulpfile.iced`, but it can't find a file with that name. See if you can use [the .scripts command](https://github.com/Microsoft/vscode-node-debug2#the-scripts-command) to debug your issue and open a new issue if there's a bug.

**Comment by roblourens** [comment]
Stale issue. If anyone still reproes this using `"protocol": "inspector"`, please share the log file (`"trace": true` in launch config).
