### ISSUE TITLE
New diff view headers look very out of place

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#197935]
The light background and dark text on top doesn't fix the UI for dark themes

![image](https://github.com/microsoft/vscode/assets/2193314/cad7cf89-f02e-493f-b909-ab963c86c6b2)

![image](https://github.com/microsoft/vscode/assets/2193314/cd5e5178-9c69-4846-9055-7eb79f2d15aa)

Maybe something more like the peek view would look better?

![image](https://github.com/microsoft/vscode/assets/2193314/4ea41d2e-e766-4efb-8eca-360994a65d33)

**Comment by bpasero** [comment]
Related https://github.com/microsoft/vscode/issues/197929
