### ISSUE TITLE
Problems with Extensions

### ISSUE THREAD

**Issue by adelahozredhat** [microsoft/vscode#197903]
If it installs extensions when restart workspace impossible installation another extension. List of another didn't install is empty.

Version: 1.83.0
Commit: unknown
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Embedder: server-distro

**Comment by gjsjohnmurray** [comment]
Please update to the current release, 1.84.2, then retest.
