### ISSUE TITLE
warning of "typeScript language service abort 5 times in last 5 minutes" show repeatedly

### ISSUE THREAD

**Issue by AIluffy** [Microsoft/vscode#19795]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|project-manager|alefragnani|0.13.2|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|jshint|dbaeumer|0.10.15|
|githistory|donjayamanne|0.1.5|
|jquerysnippets|donjayamanne|0.0.1|
|theme-dracula|dracula-theme|1.2.5|
|beautify|HookyQR|0.7.3|
|vue|liuji-jim|0.1.5|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|HTMLHint|mkaufman|0.3.3|
|prettify-json|mohsen1|0.0.3|
|debugger-for-chrome|msjsdiag|2.5.1|
|vscode-icons|robertohuertasm|7.1.2|
|stylelint|shinnn|0.22.0|
|guides|spywhere|0.6.1|
|vscode-gulp|tanato|0.0.4|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. "npm init"
2. "npm install --save hapi"
3. create "server.js" file, then the bug appears.

**Comment by mjbvz** [comment]
To help us investigate, please:

* Add `"typescript.tsserver.trace": "verbose"` to your settings.
* Restart VSCode and reproduce the problem.
* Open the output panel in VSCode and paste up the output from `TypeScript`

Thanks

**Comment by AIluffy** [comment]
[Error - a.m8:56:55] TSServer exited with code: 1
[Info  - a.m8:56:55] Using tsserver from location: d:\Tools\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js

It's the output.

**Comment by AIluffy** [comment]
I just find the reason why this happens in my company computer, because the antivirus software recognize some js files under the path "node_modules\typescript\lib" as dangerous, so it deletes some files such as typescript.js, typingsinstaller.js, tsserver.js, tsc.js. when I trust these files, then the warning doesn't show. 

But I dont think the infinite warning is good.

**Comment by AIluffy** [comment]
I just find in my company computer,  the antivirus software recognizes some js files under the path "node_modules\typescript\lib" as dangerous, so it deletes some files such as typescript.js, typingsinstaller.js, tsserver.js, tsc.js. But when I trust these files, the infinite warning bar still there.

**Comment by AIluffy** [comment]
I just find in my company computer, the antivirus software recognizes some js files under the path "node_modules\typescript\lib" as dangerous, so it deletes some files such as typescript.js, typingsinstaller.js, tsserver.js, tsc.js. And then I restore these files, the code works, the warning disappear.
