### ISSUE TITLE
Can't install the newest version (v18.4.2) in Chromebook

### ISSUE THREAD

**Issue by chendaolong1119** [microsoft/vscode#197982]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 18.4.2
- OS Version: Chromebook Debian 11.8

Steps to Reproduce:

1. The old version 18.4.1 can be installed, but when I upgrade to 18.4.2 by code_1.84.2-1699528352_amd64.deb, it showed the following errors:
The following packages have unmet dependencies:
  code: Depends: libasound2 (>= 1.0.17) but it is not installable
        Depends: libatk-bridge2.0-0 (>= 2.5.3) but it is not installable
        Depends: libatk1.0-0 (>= 2.2.0) but it is not installable
        Depends: libatspi2.0-0 (>= 2.9.90) but it is not installable
        Depends: libc6 (>= 2.14) but it is not installable
        Depends: libc6 (>= 2.16) but it is not installable
        Depends: libc6 (>= 2.17) but it is not installable
        Depends: libc6 (>= 2.2.5) but it is not installable
        Depends: libcairo2 (>= 1.6.0) but it is not installable
        Depends: libcurl3-gnutls but it is not installable or
                 libcurl3-nss but it is not installable or
                 libcurl4 but it is not installable or
                 libcurl3 but it is not installable
        Depends: libdbus-1-3 (>= 1.5.12) but it is not installable
        Depends: libdrm2 (>= 2.4.75) but it is not installable
        Depends: libexpat1 (>= 2.0.1) but it is not installable
        Depends: libgbm1 (>= 17.1.0~rc2) but it is not installable
        Depends: libglib2.0-0 (>= 2.37.3) but it is not installable
        Depends: libgssapi-krb5-2 but it is not installable
        Depends: libgtk-3-0 (>= 3.9.10) but it is not installable
        Depends: libgtk-3-0 (>= 3.9.10) but it is not installable or
                 libgtk-4-1 but it is not installable
        Depends: libkrb5-3 but it is not installable
        Depends: libnspr4 (>= 2:4.9-2~) but it is not installable
        Depends: libnss3 (>= 2:3.30) but it is not installable
        Depends: libnss3 (>= 3.26) but it is not installable
        Depends: libpango-1.0-0 (>= 1.14.0) but it is not installable
        Depends: libx11-6 but it is not installable
        Depends: libx11-6 (>= 2:1.4.99.1) but it is not installable
        Depends: libxcb1 (>= 1.9.2) but it is not installable
        Depends: libxcomposite1 (>= 1:0.4.4-1) but it is not installable
        Depends: libxdamage1 (>= 1:1.1) but it is not installable
        Depends: libxext6 but it is not installable
        Depends: libxfixes3 but it is not installable
        Depends: libxkbcommon0 (>= 0.4.1) but it is not installable
        Depends: libxkbfile1 but it is not installable
        Depends: libxrandr2 but it is not installable
        Recommends: libvulkan1 but it is not installable
Do I need to upgrade something else?
Thanks.

**Comment by joaomoreno** [comment]
Chromebooks are not a supported OS.
