### ISSUE TITLE
Sparkle icon on editor gutter feels off in notebook

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#197953]
Does this issue occur when all extensions are disabled?: Yes/No

<img width="519" alt="image" src="https://github.com/microsoft/vscode/assets/876920/b251958e-e8d0-4a26-bcab-b35c8f6c28eb">

**Comment by rebornix** [comment]
<img width="724" alt="image" src="https://github.com/microsoft/vscode/assets/876920/360821b2-d7e0-49d1-81f7-e9478d4a5b58">

Also I think we may want to show the icon only when the cell editor has focus, but it seems right not it displays always for the cursor "selection"

**Comment by aiday-mar** [comment]
The sparkle in the gutter has been entirely removed from the code base. Hence this issue can be closed.
