### ISSUE TITLE
Configure Recommended Extensions (Workspace)

### ISSUE THREAD

**Issue by ozluy** [Microsoft/vscode#19792]
- VSCode Version: 1.9.0
- OS Version: macOS Sierra 10.12.2

What happened to `Configure Recommended Extensions (Workspace)` in menu with the update?
I had this before like below but with update its gone....
<img src="https://cdn-images-1.medium.com/max/800/1*wf8ry089aLB2t_VqRk-8vg.png" />

**Comment by sandy081** [comment]
@ozluy This option was moved into Command pallette (F1)

**Comment by ozluy** [comment]
Hi @sandy081 thanks a lot for the quick response.
