### ISSUE TITLE
Possibility to open debugger in new window

### ISSUE THREAD

**Issue by huttarichard** [Microsoft/vscode#19793]
Would it be possible / hard to open debugger in new window? I guess lot of us has just more than one monitor. I think would be just awesome to have code in one window and debugger in second to see all output logs / content of debug console (like chrome dev tools).

What do you think guys?

**Comment by isidorn** [comment]
I think it is a valid feature request, however this would make debugging quite a heavy task and at the moment we are trying to keep vscode very light.
In the future this might be covered if we enable multiple windows to be opened on the same project.
For now leaving this open as a feature request

**Comment by weinand** [comment]
VS Code (based on Electron) does not yet support 'cheap' secondary windows for a project.
Here is the fundamental feature request: https://github.com/Microsoft/vscode/issues/2686

**Comment by weinand** [comment]
With the introduction of workspaces it is now possible to open the debugger in a new window.
Here is how to do this:
- launch VS Code
- create a new Window and use the "Add Folder to Workspace" action to open your project
- create another Window and use the "Add Folder to Workspace" action to open your project a second time
- move this window to the second monitor
- switch to the debug viewlet and start debugging.

Voilà, debugger runs on second monitor!



Please see this trick for how to use https://github.com/Microsoft/vscode/issues/2686#issuecomment-315342616

**Comment by huttarichard** [comment]
@weinand beautiful
