### ISSUE TITLE
git: broken tag 1.84.2

### ISSUE THREAD

**Issue by daiyam** [microsoft/vscode#197976]
Hi, the tag `1.84.2` is referencing the same commit as `1.84.1` (2b35e1e6d88f1ce073683991d1eff5284a32690f) when it should be 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e.

**Comment by inigohidalgo** [comment]
We depend on the tag for ensuring our remote vscode instances are up to date. This has broken the workflow. Is it possible to fix ex-post or do we need to patch it and wait for the next release?

Thanks

**Comment by daiyam** [comment]
What's really weird is that the tag points correctly to https://github.com/microsoft/vscode/commit/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e on some systems

**Comment by lszomoru** [comment]
@joaomoreno, could you please take a look at this? Thanks!

**Comment by inigohidalgo** [comment]
This can probably be closed since `1.85.0` released some days ago, but it would be nice to understand what happened so it won't happen again.

**Comment by justschen** [comment]
this happened accidentally in 1.85.1 release vs. 1.85 as well, but it was fixed with a force push. @bhavyaus maybe didn't `git pull` before tagging from release?

**Comment by bhavyaus** [comment]
Apologies for breaking this. I have fixed the tag for [1.84.2](https://github.com/microsoft/vscode/releases/tag/1.84.2)
