### ISSUE TITLE
No tasks.json https://code.visualstudio.com/docs/typescript/typescript-compiling#_step-3-make-the-typescript-build-the-default

### ISSUE THREAD

**Issue by kaihendry** [microsoft/vscode#197904]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:57.054Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

Steps to Reproduce:

1. Do the tutorial upon https://code.visualstudio.com/docs/typescript/typescript-compiling#_step-3-make-the-typescript-build-the-default
2. ⇧⌘B select tsc build
3. Expect to see tasks.json created, it's not

https://github.com/microsoft/vscode/assets/765871/e66a1cb0-1fd5-4914-924c-28a2cb49eb69

**Comment by meganrogge** [comment]
You need to run `Configure default build task`
