### ISSUE TITLE
The activity bar top position holds an error when it is closed 

### ISSUE THREAD

**Issue by MohammadHarish52** [microsoft/vscode#197925]
The activity bar when open 
![Screenshot 2023-11-10 210152](https://github.com/microsoft/vscode/assets/109061798/6bba1ea4-db12-4c88-9494-c3e784877840)

but after closing there is no option to go back and it becomes troublesome to find it
![Screenshot 2023-11-10 210203](https://github.com/microsoft/vscode/assets/109061798/b5e628e9-bdfa-432f-90cf-89987ed9cfa1)

**Comment by MohammadHarish52** [comment]
![Screenshot 2023-11-10 210203](https://github.com/microsoft/vscode/assets/109061798/1bfe516e-9763-4ca7-a4dc-613197ab6f92)
It would be better if there is a small option like this to open the activity bar, When the activity bar has top position.

**Comment by sandy081** [comment]
There are layout controls on the title bar to the right to toggle this

![image](https://github.com/microsoft/vscode/assets/10746682/baaf0523-88ab-4543-b392-2ee76da52e8e)
