### ISSUE TITLE
Running c++ generate task keeps building

### ISSUE THREAD

**Issue by Dorian-CodeVerse** [microsoft/vscode#197920]
Type: <b>Bug</b>

1. setting.json add 

"terminal.integrated.defaultLocation": "editor",
![image](https://github.com/microsoft/vscode/assets/81910915/15f2f537-c52d-4df9-9973-c0f9daeb52dd)

2. Terminal Run Build Task

![image](https://github.com/microsoft/vscode/assets/81910915/fb708c07-aca6-4d22-ae37-985be98ea1b5)

4. c++ generate task execution unsuccessful

![image](https://github.com/microsoft/vscode/assets/81910915/23236664-cb0a-4a5b-aecb-81ba944bd2b4)

5. When I change the default location of the terminal to "view"
![image](https://github.com/microsoft/vscode/assets/81910915/8fa8e18e-488e-4b5d-8048-30046aef4658)

6.  Everything works fine!Please tell me why this is happening.
![image](https://github.com/microsoft/vscode/assets/81910915/bb9e8b9a-0942-4093-bced-c74bada4850f)

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (0.89GB free)|
|Process Argv|--crash-reporter-id c04e0e34-8e01-410e-a640-fc9116162161 --crash-reporter-id c04e0e34-8e01-410e-a640-fc9116162161|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
TabOut|alb|0.2.2
project-manager|ale|12.7.0
path-intellisense|chr|2.8.5
vscode-mysql-client2|cwe|6.8.2
todo-tree|Gru|0.0.226
vscode-language-pack-zh-hans|MS-|1.84.2023110809
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
indent-rainbow|ode|8.3.1
cmake|twx|0.0.17
errorlens|use|3.15.0
vscode-icons|vsc|12.6.0
vim|vsc|1.26.2
material-theme|zhu|3.16.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30880073
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss2:30886141
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30886110
dsvsc017:30886112
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by meganrogge** [comment]
works just fine for me with that default location and the build task. pls create an issue for the C++ team, as maybe there's something wrong with the task. 

![Screenshot 2023-11-10 at 10 20 16 AM](https://github.com/microsoft/vscode/assets/29464607/d57072cc-9a94-4461-ac3f-07042e0f7735)
