### ISSUE TITLE
Selection highlighting matches regex if activated in local search.

### ISSUE THREAD

**Issue by SrTobi** [Microsoft/vscode#1980]
Unless it is a feature:

Correct:
![bug1](https://cloud.githubusercontent.com/assets/4148534/12291018/14c3c19e-b9e5-11e5-8816-407ea50c3527.PNG)

Bug:
![bug2](https://cloud.githubusercontent.com/assets/4148534/12291087/7c22e568-b9e5-11e5-9f79-580937ae9a50.PNG)

**Comment by alexandrudima** [comment]
@SrTobi Yeah, the <kbd>Ctrl</kbd>+<kbd>D</kbd> respects the modifiers of the find widget. Match case makes sense, whole words makes sense, I wasn't sure what to do about the regex, so I left it to honor that as well.

I'm not sure how useful it is though... I personally never use it like that. Maybe I'll just take it out.

**Comment by SrTobi** [comment]
ok, your right. for Case Matching and whole words it does make sense.

Hmmm... I think it is a little strange for regex, though. It is a little bit distracting to select a dot and the hole text gets highlighted...

On the other side it is some kind of feature.

**Comment by alexandrudima** [comment]
@SrTobi Thank you for your thoughts. Just pushed the change that the regex toggle is not taken into account in these cases :+1:
