### ISSUE TITLE
Commit hash for VS Code app version 1.84.2 (MacOS) doesn't match the Release page

### ISSUE THREAD

**Issue by pati-dev** [microsoft/vscode#198091]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Install VS Code app for MacOS
2. Click on _About Visual Studio Code_
3. Check the Commit hash (snapshot below)
4. Confirm if it matches with the one on the Release page ([link](https://github.com/microsoft/vscode/commit/2b35e1e6d88f1ce073683991d1eff5284a32690f#:~:text=commit-,2b35e1e,-Showing%201%20changed))

<img width="264" alt="image" src="https://github.com/microsoft/vscode/assets/29841730/cf671153-c6e1-46b0-a40c-2b63b3613275">

I believe both the commit hashes should match each other, but that doesn't seem to be the case for this version of VS Code. This is breaking some automations that we have at our end and I would like to confirm if this is going to be the case for all future releases? Can something be done to fix this so that things don't break at our end?

**Comment by gjsjohnmurray** [comment]
See also #197976
