### ISSUE TITLE
improve error information about "debug adapter process has terminated"

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/vscode#198069]
js debugger works after disabled all extension, so it might crashed by some extension, but there's no error stack at log
![image](https://github.com/microsoft/vscode/assets/49113249/bd73d70f-0ced-4399-8a4a-638e93e38f50)

I don't want to try one by one since I have dozens of them installed, so can vscode team improve the error information about this issue?

**Comment by gjsjohnmurray** [comment]
Are you aware of the Start Extension Bisect command?

**Comment by HomyeeKing** [comment]
wow! It's a very useful feature, thanks for your information
