### ISSUE TITLE
Generate Commit Message Icon Overlaps Commit message

### ISSUE THREAD

**Issue by shazzad** [microsoft/vscode#198019]
Type: <b>Bug</b>

On the `Source Control` tab, `Generate Commit Message` icon overlaps the last character of commit message. 

To reproduce, write a commit message till the end of the line (one line). And it wouldn't show the last character as the `Generate Commit Message` icon is above the text.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (3.80GB free)|
|Process Argv|--crash-reporter-id a8c9ab7a-d92e-4c61-829f-3e2026f98989|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (2 x 2495)|
|Memory (System)|4.81GB (0.60GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (2 x 2495)|
|Memory (System)|4.81GB (0.60GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
remote-containers|ms-|0.321.0
remote-wsl|ms-|0.81.8
twig|wha|1.0.2
composer-php-vscode|DEV|1.40.14103
phptools-vscode|DEV|1.40.14103
profiler-php-vscode|DEV|1.40.14103
redis|Dun|1.4.0
prettier-vscode|esb|10.1.0
copilot|Git|1.135.0
copilot-chat|Git|0.10.1
vscode-github-actions|git|0.26.2
vscode-docker|ms-|1.27.0
black-formatter|ms-|2023.6.0
python|ms-|2023.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30887143
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016cf:30886111
dsvsc017:30886112
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by shazzad** [comment]
Here's a Screenshot:

![vs-code-text-overlaps](https://github.com/microsoft/vscode/assets/2789126/ec9de655-d9ff-4ee0-b66a-a0435c900da3)

**Comment by lszomoru** [comment]
@shazzad, thanks for filling this issue. This has already been fixed in the latest Insiders release, and the fix will be included in the next Stable release.
