### ISSUE TITLE
Hafl of the window is uclickable

### ISSUE THREAD

**Issue by wuszej** [microsoft/vscode#198033]
Type: <b>Bug</b>

Hello,
When I resize the window right side of it is unclickable 

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.2.0-36-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|7.18GB (3.77GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id f082f6fb-8ed4-4f5b-955a-915db11c65a1|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.14.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
vsc-python-indent|Kev|1.18.0
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
vsliveshare|ms-|1.0.5892
autodocstring|njp|0.6.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8
scrapy-command-runner|ybe|1.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2cf:30871583
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30886110
dsvsc017cf:30886113
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by wuszej** [comment]
[Screencast from 2023-11-12 10-14-36.webm](https://github.com/microsoft/vscode/assets/96411155/2ac7f89d-f5f3-43ea-a79e-082f9ff4d1f9)

**Comment by bpasero** [comment]
What is that browser window showing up when you click?

**Comment by wuszej** [comment]
It`s showing content that I have opened.

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by wuszej** [comment]
Still didn't help.

**Comment by bpasero** [comment]
I have my doubts this is an issue with VS Code, it looks more like a config issue with the OS and maybe window manager?

**Comment by wuszej** [comment]
But it only happens with vs code

**Comment by deepak1556** [comment]
Can you clarify if you are in a multi monitor setup ? Does the issue repro when you use the deb package https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions ?
