### ISSUE TITLE
Copied `B` but pasted `A`

### ISSUE THREAD

**Issue by bilogic** [microsoft/vscode#198024]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: vscode.dev 1.84.2
- OS Version: Windows 10

Steps to Reproduce:

## Video to reproduce the problem
https://github.com/microsoft/vscode/assets/946010/8823e3d6-b971-4db9-8036-dea0797cf095

1. Copy and paste a file, e.g. `bug.md`
2. `bug copy.md` will be created
3. `F2` to trying and rename any file, e.g. `issue.md`
4. Instead of rename, press `Ctrl + C` to copy the filename
5. Come back to the editor and `Ctrl + V`
6. Expected to paste `issue`, but instead gets `bug.md`
7. This issue will not happen if we did not copy and paste a file in step 1

**Comment by bilogic** [comment]
![image](https://github.com/microsoft/vscode/assets/946010/4912fa17-4a2e-49f8-ab36-06b2bfd3008b)

I believe this is the culprit and add `!editorTextFocus` is a possible solution

**Comment by bilogic** [comment]
fixable?

**Comment by lramos15** [comment]
I think this was fixed by https://github.com/microsoft/vscode/issues/200641

Try the latest insiders and let me know
