### ISSUE TITLE
The complete popup is abnormal

### ISSUE THREAD

**Issue by Auchunk** [microsoft/vscode#198079]
![1699861689663](https://github.com/microsoft/vscode/assets/55735114/a5229ac6-cdd6-4dbe-b8a1-87e535c1e04a)
Type: <b>Bug</b>

When python imports the tracback package, a pop-up message is displayed indicating that the popup persists after tracback is selected

VS Code version: Code - Insiders 1.85.0-insider (345c8d0927402d41f42402411d856eeec4013e5e, 2023-11-13T05:39:23.476Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (6.33GB free)|
|Process Argv|--crash-reporter-id cc42c93f-ec66-4779-83b2-4c6956e4f53c|
|Screen Reader|no|
|VM|86%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.14
vscode-language-pack-zh-hans|MS-|1.84.2023110809
black-formatter|ms-|2023.7.13121006
python|ms-|2023.21.13141007
vscode-pylance|ms-|2023.11.12
remote-wsl|ms-|0.81.8
tabnine-vscode|Tab|3.30.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
a247i228:30880122
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30869155
dsvsc013:30777762
dsvsc014:30777825
pythonmpsinfo:30859869
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by jrieken** [comment]
This issue lack

* copy-paste friendly sample
* precise steps, esp how did you trigger completions

**Comment by Auchunk** [comment]
1.
