### ISSUE TITLE
Bad escaping of path for `command.revealFileInOS`

### ISSUE THREAD

**Issue by simonmicro** [microsoft/vscode#198045]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: Linux Mint 21.2 Cinnamon

Steps to Reproduce:

1. Open a new, empty folder in VSCode (let's call it `project-folder`)
2. Create a subfolder named `# abc`
3. Create a file within it (let's call it `a`)
4. Right-Click the file **within the subfolder,** select "Open Containing Folder"
5. The file-manager opens - displaying the `project-folder`
6. Create a subfolder named `%3B%20%24%28touch%20file%29`
7. Create a file within it (let's call it `a`)
8. Right-Click the file **within the subfolder,** select "Open Containing Folder"
9. An error is being shown by the os-filemanager (`nemo`): `Could not find ".../project-folder/; $(touch file)/a".` (`...` = masked by me)

This smells like a way to perform a shell-injection, but I was unable to reproduce this. This bug also occurs if _any_ folder inside the path to the file to be revealed has a `#` in its name (very annoying for me).

I would like to perform a deeper analysis to discover how the underlying OS command is being executed (potentially discovering a way to perform the aforementioned shell-injection), but I was unable to locate the respective source code files.

**Comment by bpasero** [comment]
I think we are now on an Electron version that includes https://github.com/electron/electron/pull/40527, curious if that closes this issue?

**Comment by simonmicro** [comment]
@bpasero Which electron version are you referring to? I was just able to reproduce this issue again with VSCode `v1.85.1` / Electron `v25.9.7`.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by simonmicro** [comment]
Oh, thank you very much! This indeed fixed the issue. Thanks!

**Comment by hsfzxjy** [comment]
congrats to fixing this!
