### ISSUE TITLE
vs code randomly opens settings panel.

### ISSUE THREAD

**Issue by vusal5555** [microsoft/vscode#198035]
Type: <b>Bug</b>

Vs code randomly opens settings panel when I save the file using ctrl + s shortcut. I looked for the shortcut that prompts this in the keyboard shortcats panel but could not find anything. I just wanted to disable it. your help would be gladly appreciated,

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.18GB free)|
|Process Argv|--crash-reporter-id 794ebb75-3150-45d2-ba79-244d0342617a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.10.3
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
go|gol|0.39.1
dotenv|mik|1.0.1
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.31.0
LiveServer|rit|5.7.9
vscode-styled-components|sty|1.7.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30880073
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30887144
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2cf:30871583
pyreplss2:30886141
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016cf:30886111
dsvsc017:30886112
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by rzhao271** [comment]
Hi, have you figured out a solution?

There could be multiple things causing the problem, so I've attached some guides:
- [Troubleshooting VS Code keybindings](https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings)
- [Running extension bisect to identify bad extensions](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect)

**Comment by vusal5555** [comment]
Yes Raymond, I did. it was due to a keyboard shortcut that opened settings.
I accidentally pressed on it while trying to putting commas between items.
