### ISSUE TITLE
Feature Request: Configuration Setting to Open Secondary Side Bar by Default

### ISSUE THREAD

**Issue by Wladefant** [microsoft/vscode#198032]
**Body:**
I would like to suggest a feature for Visual Studio Code that allows users to configure the Secondary Side Bar (Auxiliary Bar) to open by default when the editor starts.

**Current Behavior:**
VS Code does not offer a `settings.json` configuration to set the default state of the Secondary Side Bar. It relies on the last session's state, which means the Secondary Side Bar only opens on startup if it was open when VS Code was last closed.

**Desired Behavior:**
Introduce a new setting, such as `"workbench.secondarySideBar.visibleOnStartup": true`, that can be added to `settings.json`. This would allow users who frequently use the Secondary Side Bar to have it open automatically each time they start VS Code.

**Use Case:**
Many developers use the Secondary Side Bar for quick access to extensions like **Github Copilot Chat**, Outline, Timeline, or custom views from other extensions. Having to open it manually on each startup can disrupt the flow, especially for those who prefer a consistent starting layout for their development environment.

**Benefit:**
This feature would enhance user efficiency by reducing repetitive manual actions and providing a more personalized and streamlined workspace setup.

Thank you for considering this feature request.

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/191202
