### ISSUE TITLE
Markdown preview scrolling not working in v1.9.0

### ISSUE THREAD

**Issue by punker76** [Microsoft/vscode#19802]
- VSCode Version: 1.9.0
- Commit: 27240e71ef390bf2d66307e677c2a333cebf75af
- Shell: 1.4.6
- Renderer: 53.0.2785.143
- Node: 6.5.0
- OS Version: Windows 10 1607 14393.222

Steps to Reproduce:

1. update code via updater
2. open markdown *.md or *.markdown
3. open preview and try scrolling
4. editor is not scrolling and vice versa

![hamburger_caliburn](https://cloud.githubusercontent.com/assets/658431/22584213/6eb6c3c6-e9f1-11e6-9d03-1c2b84c639d7.gif)

**Comment by mjbvz** [comment]
I'm having trouble reproducing this issue. To help investigate:

* How are you opening the preview?
* Does this happen for all markdown files or just some of them?
* Can you share a markdown file that does not work
* Also Go to `Help -> Toggle Developer tools` and see if any errors are being printed out there.

Thanks

**Comment by punker76** [comment]
Here are some more infos, hope it helps

> How are you opening the preview?

CTRL+SHIFT+V or via menu icon on top right

> Does this happen for all markdown files or just some of them?

until yet for all markdown files *.md and *.markdown

> Can you share a markdown file that does not work

https://github.com/MahApps/MahApps.Metro/tree/develop/docs/release-notes

or

https://github.com/punker76/jekyll.jkarger.de/tree/gh-pages/_posts

> Also Go to Help -> Toggle Developer tools and see if any errors are being printed out there.

there are no errors, sorry

and both parameters set to true

```
"markdown.preview.scrollPreviewWithEditorSelection": true,
"markdown.preview.scrollEditorWithPreview": true
```
