### ISSUE TITLE
Suggested commands have a weird sort order

### ISSUE THREAD

**Issue by asabla** [Microsoft/vscode#19806]
- VSCode Version: 1.9.0
- OS Version: Windows 10 Enterprise 2015 LTSB (were unable to locate build number)

Steps to Reproduce:

1. Start searching for commands (e.g Ctrl+Shift+P)
2. Type: install extensions
3. The sort order should now not prioritize exact match, but rather keep it at the bottom (see attached image)

![visual studio code - sort order](https://cloud.githubusercontent.com/assets/1063362/22584021/6e065942-e9f0-11e6-800d-46e29002c54d.png)

This is just something small and a bit edge case, due to there ain't that many commands which match with others (if there even is any more then this case).

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14727
