### ISSUE TITLE
Terminal quick fixes in fish shell

### ISSUE THREAD

**Issue by LarsRefsgaard** [microsoft/vscode#198092]
In the October 2023 release the terminal quick fixes were released, but it seems that it only works in `zsh`, or at least not in the `fish` shell.

**Comment by meganrogge** [comment]
it works in `bash` and `fish` for me. If automatic shell integration isn't working for you, you can read about how to manually install them here. 

<img width="724" alt="Screenshot 2023-11-13 at 11 15 08 AM" src="https://github.com/microsoft/vscode/assets/29464607/6421af21-39a6-49da-aa4a-2f9f420b3b5a">

https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation

**Comment by LarsRefsgaard** [comment]
Okay, thank you. It seems that [Starship](https://starship.rs/) disables this somehow, for some reason.

**Comment by alanxmay** [comment]
> Okay, thank you. It seems that [Starship](https://starship.rs/) disables this somehow, for some reason.

Hi, I come with same issue, shell integration not work with starship. How did you fix this?

**Comment by LarsRefsgaard** [comment]
> > Okay, thank you. It seems that [Starship](https://starship.rs/) disables this somehow, for some reason.
> 
> Hi, I come with same issue, shell integration not work with starship. How did you fix this?

I didn't fix it. You can disable starfix and it will work, though.

**Comment by alanxmay** [comment]
Thanks! I haven't found a solution either, looks like I should stop and live with it for now 🤷‍♂️
