### ISSUE TITLE
[json] Allow extensions to enable the builtin `json-language-features` extension on their own personal json `languageId`

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode#198025]
Currently the builtin `json` extension supports the language ids `json` and `jsonc`
It would be nice if other extensions could add their own `languageId` to the list

from my testing, simply allowing the possibility to add languages to the `documentSelector` will work
https://github.com/microsoft/vscode/blob/55c1e8473c1e156a2d8e59cd5ea65205b1cfec5f/extensions/json-language-features/client/src/jsonClient.ts#L150

and also modifying the `"activationEvents"`
https://github.com/microsoft/vscode/blob/bdc113ffe148a92d0e1a8ec34b12c44ea0b73f29/extensions/json-language-features/package.json#L14-L17  

also very closely related @jeff-hykin
the language `Code Snippets` does not have the `json language server` enabled

**Comment by aeschli** [comment]
For html we support something called language participants:
A language can declare a set of features they want to use from html:
https://github.com/microsoft/vscode/issues/156200

If that's useful, I'm happy to take a PR for JSON.

But maybe first. may I ask what kind of language that is?

**Comment by RedCMD** [comment]
> But maybe first. may I ask what kind of language that is?

Syntax highlighter for VSCodes json TextMate files
https://marketplace.visualstudio.com/items?itemName=RedCMD.tmlanguage-syntax-highlighter

also the new `code-snippets` edition would benefit from having the json lanuage features

**Comment by aeschli** [comment]
Ok I see. No your proposals would go on top. But you might get conflicting proposals unless you can tune the schema the way you want it.

An alternative is to not define a new language but keep it as JSON.
Use additional providers for diagnostics and semantic highlighting instead of your own grammar.

**Comment by RedCMD** [comment]
yeah, I'll make the schem handle the basics and let my language server handle the rest

switching to solely using semantic highlighting instead of textmate isn't an option for me
as semantic's cant handle bracket pair matching
and I think the `string` scope from textmate disables `"autoClosingPairs"`
and I like the idea of textmate grammars highlighting textmate grammars

I'll look into making a pr soon

**Comment by andreamah** [comment]
@aeschli Do you have some minimal steps to verify this?

**Comment by RedCMD** [comment]
place this in an extensions `package.json` file
update `languageId` with a language to target
open a file with that language set
notice how all the json language features are available 
Intellisense, formatting, diagnostics etc
```json
"main": "",
"extensionDependencies": [
	"vscode.json-language-features"
],
"contributes": {
	"jsonLanguageParticipants": [
		{
			"languageId": "foobar"
		}
	]
} 
```

`extensionDependencies` activates the `json language features` extension
`main` is required for `extensionDependencies` to work
