### ISSUE TITLE
Cannot refactor - File not found

### ISSUE THREAD

**Issue by tSte** [Microsoft/vscode#19809]
I have a refactor issue after last update.

- VSCode Version:
1.9.0
- OS Version:
Windows 8.1 Pro x64

Steps to Reproduce:

1. Select and press F2
2. Rename and hit enter
3. Warning message: "File not found (\path\to\current\file.js)"

Note: This does not happen in every file. I tried to create blank folder with new .js file and refactoring worked correctly. I'm not sure what causes this behavior...

**Comment by tSte** [comment]
I have not experienced this issue since I solved #19753

**Comment by sandy081** [comment]
Closed this as this is due to #19753
