### ISSUE TITLE
Not letting me input text in console

### ISSUE THREAD

**Issue by eriontroni** [microsoft/vscode#198059]
Type: <b>Performance Issue</b>

Hi, i was trying to execute a simple program using c++, and it wont work.
The program in question was the following:

int main(){
    int a;
    cout<< "HEY\n";
    cin >> a;
    
    return 0;

}

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.80GB (0.29GB free)|
|Process Argv|--crash-reporter-id a3a5afe3-38e4-4a4a-9712-0f7397c0fc17|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    61	 19308	code main
    0	    22	  1168	fileWatcher [1]
    0	    82	  1260	   gpu-process
    0	     6	  2044	   crashpad-handler
    2	    62	  4488	window [2] (Issue Reporter)
    0	    39	  5296	shared-process
    0	   119	  8768	window [1] (erii.cpp - erii - Visual Studio Code)
    0	    17	  9972	   utility-network-service
    0	    15	 18100	ptyHost
    0	    23	   308	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     3	 18872	     conpty-agent
    0	    35	 19228	extensionHost [1]
    0	    18	 10076	     electron-nodejs ("C:\Users\Erion\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Erion\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=19228)
    0	    32	 14008	     c:\Users\Erion\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64\bin\cpptools.exe
    0	     1	 12932	       "c:\Users\Erion\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64\bin\cpptools.exe"
    0	    26	  6256	         c:\Users\Erion\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64/bin/cpptools-srv.exe 14008 {FB27E3A1-C53B-49B5-9F5F-8F58A6A10203}
    0	    10	 13268	           C:\WINDOWS\system32\conhost.exe 0x4
    0	    28	  7820	         c:\Users\Erion\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64/bin/cpptools-srv.exe 14008 {0022905E-76D0-482D-838F-D7A474AAE487}
    0	     9	  5760	           C:\WINDOWS\system32\conhost.exe 0x4
    0	     8	 15220	       C:\WINDOWS\system32\conhost.exe 0x4
    0	     3	 17412	     C:\WINDOWS\system32\cmd.exe /d /s /c "cd "c:\Users\Erion\erii\" && g++ erii.cpp -o erii && "c:\Users\Erion\erii\"erii"
    0	     4	 13344	       "c:\Users\Erion\erii\"erii
    0	    10	 15564	       C:\WINDOWS\system32\conhost.exe 0x4
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (erii.cpp - erii - Visual Studio Code)
|    Folder (erii): 8 files
|      File types: json(4) cpp(2) exe(1)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: cppdbg(3);
```

</details>
<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.14.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
code-runner|for|0.12.1
c-cpp-runner|fra|9.2.1
better-cpp-syntax|jef|1.17.2
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
autodocstring|njp|0.6.1
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8
livecode|xir|1.3.10

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30887144
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30886110
dsvsc017cf:30886113
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by roblourens** [comment]
You can open an issue on the C++ extension or check the docs
