### ISSUE TITLE
Add an option "never" for showing inline suggestion toolbar

### ISSUE THREAD

**Issue by gugeonmo** [microsoft/vscode#198070]
### Inline Suggestion Toolbar
<img src="https://code.visualstudio.com/assets/updates/1_75/inline-completions-hover.gif" alt="drawing" width="600"/>

### Current Feature
Currently, we can control when to show the inline suggestion toolbar by setting `editor.inlineSuggest.showToolbar` to "always" or "onHover", which are defined as follows:
- "always": show the inline suggestion toolbar whenever an inline suggestion is shown, and
- "onHover":  show the inline suggestion toolbar when hovering over an inline suggestion.

### New Feature
For the new feature, I suggest to add an option "never" as follows
- "never": do not show the inline suggestion toolbar.

**Comment by hediet** [comment]
I think this should be very easy to implement. Up for a PR?

**Comment by hsfzxjy** [comment]
I would like to take this.

**Comment by cyfyifanchen** [comment]
Any ideas why this setting isn't in the Settings JSON file? `"editor.inlineSuggest.showToolbar": "onHover"`.

**Comment by gugeonmo** [comment]
Thank you so much for accepting the request and for the contribution!
