### ISSUE TITLE
memory leak in menubar

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#198051]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: Ubuntu 23.04

Steps to Reproduce:

1. Open a VSCode Window
2. In the menu at the top, click on "File" which opens the menu
3. In the menu at the top, click on "File" again which closes the menu
4. A Menu instance has been added, but not been removed

### Test Script

```sh
git clone git@github.com:SimonSiefke/vscode-memory-leak-finder.git &&
cd vscode-memory-leak-finder &&
git checkout v5.22.2 &&
npm ci &&
node packages/cli/bin/test.js --cwd packages/e2e  --check-leaks --measure instance-counts-with-source-map --only title-bar &&
cat .vscode-memory-leak-finder-results/instance-counts-with-source-map/title-bar-menu-toggle.json
```

### Output

```json
{
  "instanceCounts": {
    "before": [
      {
        "name": "Menu",
        "count": 1
      }
    ],
    "after": [
      {
        "name": "Menu",
        "count": 2
      }
    ]
  },
  "isLeak": true
}
```

**Comment by jrieken** [comment]
verified in code review


@SimonSiefke Thank you for these great issues and fixes ❤️
