### ISSUE TITLE
When a file is modified by extensions , it loses the undo history.

### ISSUE THREAD

**Issue by v3ss0n** [Microsoft/vscode#19800]
- VSCode Version: 1.9
- OS Version: Linux

Steps to Reproduce:

1. install vscode-prettydiff from extension market place.
2. made some changes to a file.
3. run it to beautify the file. `Ctrl + Shift + P` : `Prettify using Prettydiff`

Source :

https://github.com/HexcodeTechnologies/vscode-prettydiff/blob/master/extension.js
I do believe extensions should not discard undo history.

**Comment by bpasero** [comment]
This is not how we recommend extensions to modify a text buffer. There is proper API to modify text documents and those should be used.

Please file this as bug to the extension you are using.

**Comment by v3ss0n** [comment]
I am extension developer of it.

**Comment by v3ss0n** [comment]
Thats means external applications modifying the document are supposed to discard Undo History?
That is not right. That is a bug.

**Comment by v3ss0n** [comment]
I had confirmed:

Modify same file in different editor.
VSCode's Undo History is lost.

**Comment by bpasero** [comment]
@v3ss0n why can you not express your edit via the text document API? what happens if the file is dirty in the editor, you just write to disk? that is a bad behaving extension 👎

**Comment by v3ss0n** [comment]
I just started my first extension and reported a Bug , still it is a bug since Undo History should not be lost. Why Microsoft developers so toxic , this is not once such `noob blaming/shaming behavior` is spotted.  you can just `Kindly` point to the correct API or Example.

**Comment by bpasero** [comment]
@v3ss0n see http://code.visualstudio.com/docs/extensionAPI/vscode-api#TextEditor and specifically the `edit` method. Anything you do in there will support undo/redo.
