### ISSUE TITLE
`code --wait <file>` with pre-existing editor no longer exits when `<file>` is closed

### ISSUE THREAD

**Issue by torokati44** [microsoft/vscode#198002]
Type: <b>Bug</b>

This used to work fine, regressed a couple weeks ago.

The reason this is a problem is that I usually have a project open in VS Code, and also use `code --wait` as a git editor (for rebase TODOs and squashed commit messages and such).
And now I have to close the entire project for git to proceed with the operation it started the editor for.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.5.8-200.fc38.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 4266)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|31.23GB (9.14GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.1.4
meson|asa|1.3.0
vscode-django|bat|1.14.0
QML|bbe|1.0.0
vscode-as3mxml|bow|1.19.0
vscode-nextgenas|bow|2.0.0
vscode-swf-debug|bow|1.8.2
ccls|ccl|0.1.29
opt-info|dam|0.7.0
vscode-eslint|dba|2.4.2
vscode-lark|dir|0.1.0
vscode-wasm|dts|1.4.1
gitlens|eam|14.4.1
vscode-firefox-debug|fir|2.9.10
code-runner|for|0.12.1
vscode-opencl|gal|0.8.2
copilot|Git|1.135.0
copilot-chat|Git|0.10.1
vscode-github-actions|git|0.26.2
git-tree-compare|let|1.16.0
MagicPython|mag|1.1.0
git-graph|mhu|1.30.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.27.0
isort|ms-|2023.10.1
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
jupyter|ms-|2023.10.1003070148
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.321.0
hexeditor|ms-|1.9.12
makefile-tools|ms-|0.7.0
vsliveshare|ms-|1.0.5892
vshaxe|nad|2.30.0
color-highlight|nau|2.5.0
wgsl|Pol|0.1.16
show-offset|ram|0.0.4
vscode-xml|red|0.26.1
llvm|RRe|0.1.1
rust-analyzer|rus|0.3.1722
vscode-header-source|ryz|1.3.0
omnetpp-ned|sch|0.0.4
crates|ser|0.6.3
shader|sle|1.1.5
even-better-toml|tam|0.19.2
simple-rst|tro|1.5.4
vscode-lldb|vad|1.10.0
debug|web|0.26.1
jinja|who|0.0.8
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.5.1

</details>

**Comment by bpasero** [comment]
If this is a confirmed regression, it would help to know which change caused it. We maintain a node.js based CLI tool  [`vscode-bisect`](https://github.com/microsoft/vscode-bisect) that automatically downloads and runs previous VS Code insiders and asks for each build if the issue reproduces. It takes up to 8 steps to find exactly the build that caused the regression.

**Steps:**
* install [node.js](https://nodejs.org/en/download) (if not yet done)
* `npx --yes @vscode/vscode-bisect@latest`
* follow the instructions until you found the offending build (its fine to leave the commit empty)
* report back the commit range in this issue

Thanks!

**Comment by bpasero** [comment]
Can you provide clear step by step instruction show to reproduce this?

**Comment by torokati44** [comment]
Never mind, closing all files/editors in the instance of VS Code with my usual project folder open solved this.
