### ISSUE TITLE
workbench.editor.showTabs incorrect resource scope error

### ISSUE THREAD

**Issue by mj-spencer** [microsoft/vscode#198056]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.0-insider (Universal)
- OS Version: Sonoma 14.0

Description: The setting 'workbench.editor.showTabs' is either listed incorrectly as available under the Folder settings, or is incorrectly showing an error when set under the folder settings. I'm not sure of the expected behavior (personally, I'd prefer it to be settable at the folder level rather than having to create a new profile just to change this setting, but regardless, the setting is confusing)

Steps to Reproduce:

1. Leave the setting "workbench.editor.showTabs" as default (multiple)
2. Open a folder and include the setting "workbench.editor.showTabs": "none" (setting can be adjusted in the json file without error, or found in the Settings UI.
3. Close and reopen VS Code.
4. Error notification appears: "Unable to write to Folder Settings because workbench.editor.showTabs does not support the folder resource scope."

Note: The change that I made to settings and subsequent changes to the folder do function and are saved correctly, but the error notification continues to appear. As far as I can tell, it's simply a bad error message, but obviously is concerning, since it (incorrectly) indicates I can't save folder settings.

<img width="1512" alt="image" src="https://github.com/microsoft/vscode/assets/64339311/68d060ab-d486-4816-a595-6524ee477469">

**Comment by benibenj** [comment]
Thank you for reporting this @mj-spencer.  There was an error in the migration of this setting which I've fixed now.

**Comment by sandy081** [comment]
I can still repro this with following steps:

- Open a folder with `.vscode/settings.json` file
- Set the setting `"workbench.editor.showTabs":false` in the file
- Reload window

<img width="483" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/181c4c6a-a750-457d-897f-4528f073e781">
