### ISSUE TITLE
Support more than one running tasks

### ISSUE THREAD

**Issue by NCC1701M** [Microsoft/vscode#19817]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
---
Steps to Reproduce:

1. Create a asp.net core app
2. Setup launch to start app
3. Use preLaunchTask to build dotnet app
4. Setup tasks
5. Create task to build dotnet (preLaunchTask)
6. Create second task to start tsc in watch mode
7. Run tsc - Task
8. Press F5 to launch dotnet app.

As you can see, you get an error that a task is already running and the preLaunchTask cannot be started.

It should be possible to run more than one tasks at a time. For every running task show a seperated terminal.

A example programm  you can find [here](https://github.com/Microsoft/vscode/files/750027/Test.zip)

**Comment by dbaeumer** [comment]
This is on its way and as prelimary support in 1.9. See the release notes. I will close this issue since we are working on this.

**Comment by dbaeumer** [comment]
See http://code.visualstudio.com/updates/v1_9#_task-execution-in-terminal
