### ISSUE TITLE
"Visual Studio" icon is showing instead of VS Code icon

### ISSUE THREAD

**Issue by hkchakladar** [microsoft/vscode#198121]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.84.2
- OS Version: 20.04

Steps to Reproduce:

1. Install latest version via `apt`.
2. Check icon.

Here is my `cat /usr/share/applications/code.desktop`
```
[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --unity-launch %F
Icon=vscode
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-code-workspace;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/share/code/code --new-window %F
Icon=vscode
```
Icon in launcher:
![image](https://github.com/microsoft/vscode/assets/7250906/5cac8678-2d1c-4555-96a9-e3c2ba011d03)

**Comment by joaomoreno** [comment]
This seems a bug within the DM you're using. Please give them an issue.
