### ISSUE TITLE
"focus" not working anymore

### ISSUE THREAD

**Issue by RoyalXXX** [microsoft/vscode#198148]
- VS Code Version: 1.84.2
- OS Version: Windows 10 64-bit v. 10.0.19045
- C++/ C extension: v1.17.5

Steps to Reproduce:

In ```tasks.json``` in C++ folder in ```presentation```, ```focus``` is ```true```
It used to work, but now it doesn't work.
For example, it was very convenient when, after compilation, the output window was focused, and this made it possible to close the window by pressing Enter.
Now, regardless of whether true or false is selected for ```focus```, the window is not focused. You have to click on the window after compilation and only then press Enter to close it.

![Screenshot 2023-11-13 200216](https://github.com/microsoft/vscode/assets/125651292/745fe0e5-eac3-4cdc-a5d6-88965adf905a)
![Screenshot 2023-11-13 200529](https://github.com/microsoft/vscode/assets/125651292/1790f52e-163e-4433-a424-f82951441a8f)

**Comment by ehoogeveen-medweb** [comment]
I'm having this problem too, but it seems like it's working again in the pre-release version of 1.85 (`1.85-insider`). I don't know what changeset might have fixed it though.
