### ISSUE TITLE
After VSCode upgrade source control repository list does not show number of changes per repository

### ISSUE THREAD

**Issue by RaimisJ** [microsoft/vscode#198101]
Type: <b>Bug</b>

1. Add two folders to workspace with git tracked changes
2. Number of pending changes is shown next to the Source Control icon, but changes per folders is not shown in "Source Control Repositories" list, which was the case in the previous version.

<img width="134" alt="image" src="https://github.com/microsoft/vscode/assets/28889883/72ec8c02-77ea-43bf-8947-8bc1b0ad7eb4">

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.91GB (5.46GB free)|
|Process Argv|--crash-reporter-id db8fe700-2e24-4369-b577-2d6d0fbb44a2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.2
prettier-vscode|esb|10.1.0
volar|Vue|1.8.22
vscode-typescript-vue-plugin|Vue|1.8.22

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
a247i228:30880122
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30887143
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016cf:30886111
dsvsc017:30886112
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by gjsjohnmurray** [comment]
What value is your `scm.providerCountBadge` setting set to?

**Comment by RaimisJ** [comment]
> What value is your `scm.providerCountBadge` setting set to?

It was not set at all, so default - hidden. Setting it to visible fixes the problem.

**Comment by gjsjohnmurray** [comment]
:+1: Please close your issue

**Comment by RaimisJ** [comment]
Closing this as it seems to be a configuration issue - setting scm.providerCountBadge to visible fixes the proble,
