### ISSUE TITLE
jsconfig.json not working

### ISSUE THREAD

**Issue by murrellr** [microsoft/vscode#198157]
[test.zip](https://github.com/microsoft/vscode/files/13342548/test.zip)
Type: <b>Bug</b>

Unzip the workspace.
Open test.code-workspace

Explorer shows test1, test2, and test3 folders even though test2 has been excluded in jsconfig.json.  I don't know when this broke.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12850HX (24 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.67GB (5.63GB free)|
|Process Argv|--crash-reporter-id 9627556d-631e-4542-bfc5-c239f85d7509|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|14.4.1
shortcut-menu-bar|jer|3.0.4
hexeditor|ms-|1.9.12
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss2:30886141
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016cf:30886111
dsvsc017:30886112
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by mjbvz** [comment]
VS Code's explorer shows the file system. The `jsconfig.json` does not control what shows in the explorer

**Comment by murrellr** [comment]
Here is a further refinement.  

- Unzip testb.zip.
- Open test.code-workspace.
- From code explorer. open test.js
- Right-click on test_a() and go to definition.  The editor will report that the definition is not found.  test_a() is defined in both test1/test1.js and test2/test2.js.
- Open test2/test2.js.
- Go back to test.js.  Right-click on test_a() and go to definition.  The cursor will jump to test2/test2.js.  test2 is excluded in jsconfig.json.

[testb.zip](https://github.com/microsoft/vscode/files/13392693/testb.zip)

**Comment by murrellr** [comment]
When I exclude the unwanted directory in workspace settings, code explorer and intellisense work OK.  So what does jsconfig.json do?
