### ISSUE TITLE
No emoji shown neither editor or terminal

### ISSUE THREAD

**Issue by miguelfito** [microsoft/vscode#198124]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: Fedora Silverblue 39 (`Linux fedora 6.5.11-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov  8 22:37:57 UTC 2023 x86_64 GNU/Linux`)

Steps to Reproduce:

1. Open VS Code
2. Type or paste any text with emoji on editor tab or terminal

What to expect:
![image](https://github.com/microsoft/vscode/assets/879123/d908b2b6-4c04-48d4-8dd3-805b71409c83)

What is shown:
![image](https://github.com/microsoft/vscode/assets/879123/8741bf93-5609-49a3-a122-c478f3ada350)
![image](https://github.com/microsoft/vscode/assets/879123/35f751a1-b155-4e59-aa59-bdb9f3a14ad9)

Seems to be related with issue https://github.com/microsoft/vscode/issues/194172.

**Comment by miguelfito** [comment]
Just checked that in `v1.84.1` works as expected, so it seems to be a bug introduced in latest patch.

**Comment by Tyriar** [comment]
@deepak1556 anything change around electron in 1.84.2? I would expect this to be something related to system fonts, but could possibly be an electron issue?

**Comment by deepak1556** [comment]
We didn't have any runtime updates between 1.84.1 and 1.84.2. @miguelfito can you run our bisect tool https://github.com/microsoft/vscode-bisect to help narrow down the regression range.

**Comment by miguelfito** [comment]
Mmmmm... Sorry, but seems that 6 latests builds reports the same behavior:

```bash
15:34:44 in  ~/tmp/vscode-bisect 
⬢ [fedora-toolbox:39] ✗ npx @vscode/vscode-bisect --reset                                                                                                                   
✔ Commit of released insiders build that reproduces the issue (leave empty to pick the latest build) … 
✔ Commit of released insiders build that does not reproduce the issue (leave empty to pick the oldest build) … 
[build] total 175 builds with roughly 7 steps
[build] downloading build from https://az764295.vo.msecnd.net/insider/333c4e687d97007e07dc8ec4e5532cb615496163/code-insider-x64-1695203539.tar.gz...
[build] unzipping build to /tmp/vscode-bisect/.builds/333c4e687d97007e07dc8ec4e5532cb615496163...
[build] starting desktop build 333c4e687d97007e07dc8ec4e5532cb615496163...
✔ Is 333c4e687d97007e07dc8ec4e5532cb615496163 good or bad? › Bad
[build] downloading build from https://az764295.vo.msecnd.net/insider/86c61d26765f8329078bb6d13b4584bd47f24ffa/code-insider-x64-1692682416.tar.gz...
[build] unzipping build to /tmp/vscode-bisect/.builds/86c61d26765f8329078bb6d13b4584bd47f24ffa...
[build] starting desktop build 86c61d26765f8329078bb6d13b4584bd47f24ffa...
✔ Is 86c61d26765f8329078bb6d13b4584bd47f24ffa good or bad? › Bad
[build] downloading build from https://az764295.vo.msecnd.net/insider/58abf70a4573fe6392ce9945d06c127d4c56e3ee/code-insider-x64-1690954415.tar.gz...
[build] unzipping build to /tmp/vscode-bisect/.builds/58abf70a4573fe6392ce9945d06c127d4c56e3ee...
[build] starting desktop build 58abf70a4573fe6392ce9945d06c127d4c56e3ee...
✔ Is 58abf70a4573fe6392ce9945d06c127d4c56e3ee good or bad? › Bad
[build] downloading build from https://az764295.vo.msecnd.net/insider/2509b7f50472eac94b4f23671544571ba91a786e/code-insider-x64-1689923739.tar.gz...
[build] unzipping build to /tmp/vscode-bisect/.builds/2509b7f50472eac94b4f23671544571ba91a786e...
[build] starting desktop build 2509b7f50472eac94b4f23671544571ba91a786e...
✔ Is 2509b7f50472eac94b4f23671544571ba91a786e good or bad? › Bad
[build] downloading build from https://az764295.vo.msecnd.net/insider/02d3b49d8035a9b30db3b0ae706796af9b1a4260/code-insider-x64-1689572059.tar.gz...
[build] unzipping build to /tmp/vscode-bisect/.builds/02d3b49d8035a9b30db3b0ae706796af9b1a4260...
[build] starting desktop build 02d3b49d8035a9b30db3b0ae706796af9b1a4260...
✔ Is 02d3b49d8035a9b30db3b0ae706796af9b1a4260 good or bad? › Bad
[build] downloading build from https://az764295.vo.msecnd.net/insider/d568855b2a4ef75716cdaa9a52da5315f5100a5d/code-insider-x64-1689162423.tar.gz...
[build] unzipping build to /tmp/vscode-bisect/.builds/d568855b2a4ef75716cdaa9a52da5315f5100a5d...
[build] starting desktop build d568855b2a4ef75716cdaa9a52da5315f5100a5d...
✔ Is d568855b2a4ef75716cdaa9a52da5315f5100a5d good or bad? › Bad
[build] All builds are bad!
```

A screenshot where you can check that window title bar reflects emojis (as usual) but editor tab doesn't render them correctly:

![image](https://github.com/microsoft/vscode/assets/879123/154469d2-37bc-46bc-b0de-2ba66d88ed93)

**Comment by miguelfito** [comment]
Sorry guys, seems to be a font cache problem on my host.

I deleted `$HOME/.cache/fontconfig` folder and then force a new cache generation with `fc-cache --force --verbose` and the problem is gone.

I will inform reporter on issue https://github.com/microsoft/vscode/issues/194172 too.

Thanks for your suggestions!
