### ISSUE TITLE
Crash in integration tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#198131]
[b20278bf-b60d-4d21-8085-d5b2083cc72d.dmp.zip](https://github.com/microsoft/vscode/files/13336731/b20278bf-b60d-4d21-8085-d5b2083cc72d.dmp.zip)

https://dev.azure.com/vscode/VSCode/_build/results?buildId=108312&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/192119
