### ISSUE TITLE
在过去五分钟内，TypeScript语言服务以外终止了5次

### ISSUE THREAD

**Issue by FanTaSyLin** [Microsoft/vscode#19814]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-eslint|dbaeumer|1.2.2|
|tortoise-svn|fantasytyx|0.1.1|
|vscode-auto-open-markdown-preview|hnw|0.0.3|
|beautify|HookyQR|0.7.3|
|JSDocTagComplete|HookyQR|0.0.2|
|docthis|joelday|0.3.10|
|debugger-for-chrome|msjsdiag|2.5.1|
|vscode-icons|robertohuertasm|7.1.2|
|vim|vscodevim|0.5.2|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.2.0|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by fishdong1107** [comment]
我是tsserverlibrary.js 被杀毒软件误删了，设置了白名单后好了。
tsserverlibrary.js Killed by antivirus software

**Comment by bpasero** [comment]
Please refile this issue in english. Thanks.

**Comment by maicss** [comment]
你们能不能又点素质啊，一个国际的项目用中文提issue也就算了，但是有外国人为你们说的啥你们都不理一下的？你有问题了就来这上面问，有人帮你了，你还不理别人？丢不丢人？机器翻译一下会死？

**Comment by maicss** [comment]
@bpasero They using a China an so called "anti-virus" software, and run typescript script, the software gives a warning, said the Vue application is a virus.

The software is very convenience， but it collect user all (yes, all) information without user agree or notice. Most chinese programmer spit it. So it seems very ridiculous. 

And those men cannot(or no will) post an issue with English, it's ridiculous. But what's shocked me is they don't reply someone want to help them, what a shame. 

Sorry for that.

My English is very bad yet, I post this with some help of online translator, but I think this a basic manner to reply someone want help you. At least, you should give your thanks.

**Comment by FanTaSyLin** [comment]
this issue is vscode auto submit. I didn't notice it. 
i am so sorry
