### ISSUE TITLE
How to find all references / peek definition / go to definition work across whole project ?

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [Microsoft/vscode#19811]
- VSCode Version: 1.9.0
- OS Version: 10.12.2

Steps to Reproduce:

1. Open a project by dragging its outermost folder on the visual studio code icon
2. Try to "Find all references" or "Go to definition" or just using a function defined in another file.

Expectation: 
it would search across all files. Or give intellisense from that function defined in that other file.

Current Behaviour: 
only references in currently opened file are shown.
definition is not found if it’s not in the same folder.
no intellisense is provided if the function is not in the same file.

My code is pure javascript (es6), html & scss
Folder structure:
```
.git/
.vscode/
build/
api/
debian/
doc/
node_modules/
scripts/
src/ <--- main folder I’m working with
target/
.gitignore
package.json
README.md
```

Thanks for your help

**Comment by mjbvz** [comment]
Try creating a`jsconfig.json` file at the root of your project that looks something like this:

```json
{
 "include": [
        "src/**/*"
    ],
}
```

This will clue VSCode into treating all files under src as part of a project. Here's some additional information about project configuration: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

Please let me know if this resolves the issue

**Comment by mjbvz** [comment]
Closing as we've not heard anything back on this. @ThibaultJanBeyer please let me know if you are still running into problems here

**Comment by ThibaultJanBeyer** [comment]
thanks @mjbvz since the new Version it seems to work out of the box. However, it has some troubles with some frameworks. Dojo for example. But I guess that’s normal because they have different writing styles than regular JavaScript…

Sorry I completely forgot to notify you here. Thanks for the help!

**Comment by jag-s-gill** [comment]
I can't get this to work. I setup a project with two files and jsconfig.json:

File1.js:
`export class File1 {
  hello = function () {
    console.log('hello');
  }
}`

File2.js:
`import File1 from './file1'
export class File2 {
  sayHello = function () {
    File1.hello();
  }
}`

jsconfig.json:
`{
  "include": [
    "file1.js",
    "file2.js"
  ]
}`

I try to find all references for 'hello' in File1 and it only finds itself. Is my setup correct? Should this work for ES6 files?
