### ISSUE TITLE
VS Code JTAG - No option to avoid a monitor reset after download 

### ISSUE THREAD

**Issue by vasanth15** [microsoft/vscode#198156]
Type: <b>Bug</b>

I would like to use JTAG to write the application binary directly to SRAM rather than the flash. And launch.json file doesn't have option to perform monitor RESET only when needed, and in my case, I want it before download only.

In the excerpts below, there is a monitor reset before and after downloading the application binary and I want to avoid the reset which happens after downloading the file. CLion has an option to avoid that as it provides a combo box to perform monitor reset command "Before download" option.

Without this option, I can't use VS Code for development purpose.

**Below is the excerpts:**

Connecting to J-Link...
J-Link is connected.
Firmware: J-Link V11 compiled Aug  2 2023 10:34:01
Hardware: V11.00
S/N: 851001477
Feature(s): RDI, FlashBP, FlashDL, JFlash, GDB
Checking target voltage...
Target voltage: 3.32 V
Listening on TCP/IP port 50000
Connecting to target...
Halting core...
Connected to target
Waiting for GDB connection...Connected to 0000:0000:0000:0000:0000:0000:0000:0001
GDB client (conn. 824) requested target.xml from GDB Server
Reading common registers: Read register 'r0' (4 bytes) from hardware: 0x00000000
Read register 'r1' (4 bytes) from hardware: 0xC4AA0624
Read register 'r2' (4 bytes) from hardware: 0x00000000
Read register 'r3' (4 bytes) from hardware: 0x00000000
Read register 'r4' (4 bytes) from hardware: 0xC9120008
Read register 'r5' (4 bytes) from hardware: 0x00000000
Read register 'r6' (4 bytes) from hardware: 0x55555555
Read register 'r7' (4 bytes) from hardware: 0xC8B40624
Read register 'r8' (4 bytes) from hardware: 0x55555555
Read register 'r9' (4 bytes) from hardware: 0x55555555
Read register 'r10' (4 bytes) from hardware: 0x55555555
Read register 'r11' (4 bytes) from hardware: 0x55555555
Read register 'r12' (4 bytes) from hardware: 0x000000E1
Read register 'sp' (4 bytes) from hardware: 0xC8B40624
Read register 'lr' (4 bytes) from hardware: 0x13040008
Read register 'pc' (4 bytes) from hardware: 0xD0120008
Read register 'xpsr' (4 bytes) from hardware: 0x00000041
Read 4 bytes @ address 0x080012D0 (Data = 0xE7FDBF00)
Read 2 bytes @ address 0x080012D0 (Data = 0xBF00)
Received monitor command: halt
Halting target CPU...
...Target halted (PC = 0x080012D0)
**Received monitor command: reset
Resetting target**
Downloading 672 bytes @ address 0x24000000
Downloading 15856 bytes @ address 0x240002A0
Downloading 15744 bytes @ address 0x24004090
Downloading 15728 bytes @ address 0x24007E10
Downloading 15648 bytes @ address 0x2400BB80
Downloading 15888 bytes @ address 0x2400F8A0
Downloading 15856 bytes @ address 0x240136B0
Downloading 15808 bytes @ address 0x240174A0
Downloading 16160 bytes @ address 0x2401B260
Downloading 15872 bytes @ address 0x2401F180
Downloading 15632 bytes @ address 0x24022F80
Downloading 16048 bytes @ address 0x24026C90
Downloading 15888 bytes @ address 0x2402AB40
Downloading 16048 bytes @ address 0x2402E950
Downloading 15968 bytes @ address 0x24032800
Downloading 15952 bytes @ address 0x24036660
Downloading 15568 bytes @ address 0x2403A4B0
Downloading 15872 bytes @ address 0x2403E180
Downloading 16000 bytes @ address 0x24041F80
Downloading 15920 bytes @ address 0x24045E00
Downloading 15968 bytes @ address 0x24049C30
Downloading 11940 bytes @ address 0x2404DA90
Downloading 36 bytes @ address 0x24050934
Downloading 16344 bytes @ address 0x24050958
Downloading 16288 bytes @ address 0x24054930
Downloading 16176 bytes @ address 0x240588D0
Downloading 15544 bytes @ address 0x2405C800
Downloading 8 bytes @ address 0x240604B8
Downloading 5188 bytes @ address 0x240604C0
Downloading 13096 bytes @ address 0x24061904
Writing register 'pc' = 0x240003E4
**Received monitor command: reset
Resetting target**
Read 4 bytes @ address 0x240003E4 (Data = 0xF000E75C)
Read 2 bytes @ address 0x240003E4 (Data = 0xE75C)
Read 4 bytes @ address 0x240003E4 (Data = 0xF000E75C)
Read 2 bytes @ address 0x240003E4 (Data = 0xE75C)
Starting target CPU...
Debugger requested to halt target...
...Target halted (PC = 0x24018318)
Reading common registers: Read register 'r0' (4 bytes) from hardware: 0x00000000

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-11955M CPU @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (15.86GB free)|
|Process Argv|--crash-reporter-id 1657622f-230e-4d97-b570-4b96d8ace50f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
git-easy|bib|1.11.0
c-cpp-compile-run|dan|1.0.50
empty-indent|Dmi|0.2.0
prettier-vscode|esb|10.1.0
code-runner|for|0.12.1
cortex-debug|mar|1.12.1
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.25
peripheral-viewer|mcu|1.4.6
rtos-views|mcu|0.0.7
git-graph|mhu|1.30.0
python|ms-|2023.20.0
remote-wsl|ms-|0.81.8
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
indent-rainbow|ode|8.3.1
gitpatch|par|0.2.1
ActiveFileInStatusBar|Ros|1.0.3
vscode-paste-and-indent|Rub|0.0.8
git-merger|sha|0.4.1
cmake|twx|0.0.17
gitblame|wad|10.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016cf:30886111
dsvsc017cf:30886113
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by vasanthmurari** [comment]
Are there any plans to address this bug in December 2023 release?

**Comment by joaomoreno** [comment]
This doens't seem to be a VS Code issue at all. Please file an issue to the respective extension.
