### ISSUE TITLE
SCM incoming/outgoing changes UX feedback

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#198189]
Having now selfhosted a bit on incoming/outgoing changes I felt that the view "With changes" feels a bit off: `Incoming/Outgoing` shows in smaller font making it look inbalanced

I wonder if we should simply try to have a node like `Changes` so that the tree is balanced again.

With changes:

![image](https://github.com/microsoft/vscode/assets/900690/42ffd886-89de-4329-9a16-34957624b375)

Without changes:

![image](https://github.com/microsoft/vscode/assets/900690/e1bd1726-88f1-49f0-b598-66fab199a129)

**Comment by lszomoru** [comment]
Thanks for the feedback. //cc @hbons

**Comment by lszomoru** [comment]
Closing as the "Incoming/Outgoing" section has been removed.
