### ISSUE TITLE
Progress bar is not below editor title anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#198176]
See:
![Recording 2023-11-14 at 05 43 21](https://github.com/microsoft/vscode/assets/900690/85f059d3-02a6-42f3-86c6-0d490351e397)

**Comment by rzhao271** [comment]
LGTM, though my tabs look a bit different than yours.

![Screenshot showing pink stripe below file, as expected](https://github.com/microsoft/vscode/assets/7199958/7f4dd414-9ea6-440e-99c0-331e3b7b53d4)
