### ISSUE TITLE
VS Code inconsistent in detecting git changes

### ISSUE THREAD

**Issue by 0xCLARITY** [microsoft/vscode#198138]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.84.2 (Universal)
- OS Version: macOS Ventura 13.5

Steps to Reproduce:

1. Open repo
2. Initially see my uncommitted changes
3. Watch them disappear before my eyes

It's amusing to me that the badge counter remains correct (shows 2 changes) - but then it doesn't actually list them?

![Kapture 2023-11-13 at 08 43 15](https://github.com/microsoft/vscode/assets/11398766/9f1a087e-d970-4245-9945-9568e826d8aa)

**Comment by 0xCLARITY** [comment]
Yes - the behavior is reproducible with all extensions disabled.

I am _not_ able to reproduce this issue with VS Code Insiders. I have been using that for the past week or so for this repo.

I should also point out that this is only happening in a single repository. All other repos have working Source Control, it is only a single repo where I am experiencing this odd behavior.

I can't think of why that would be the case - but it is a Solidity-Foundry repo that uses git submodules fairly extensively, if that makes a difference.

**Comment by 0xCLARITY** [comment]
@lszomoru - still happening with 1.85 (even with extensions disabled).

Should I open a new issue?

**Comment by lszomoru** [comment]
@0xCLARITY, yes please! Thank you!
