### ISSUE TITLE
SCM: incoming/outgoing changes node should have primary actions

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#198190]
I was expecting to have actions to pull, push, sync on the node:

![image](https://github.com/microsoft/vscode/assets/900690/79144063-4f2f-4eea-8b6d-c231d1f9c649)

**Comment by lszomoru** [comment]
Thanks for the feedback. This is something that is currently under discussion. The main concern is that by default the actions are only visible on hover, yet if they are invoked by accident, they result in an operation that cannot be undone. Having said that, I would love to add them there.

**Comment by lszomoru** [comment]
Closing as the "Incoming/Outgoing" changes section has been removed.
