### ISSUE TITLE
Release Notes tab always reload its content on tab focus

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#19818]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.5|
|code-runner|formulahendry|0.6.7|
|beautify|HookyQR|0.7.3|
|vscode-hexdump|slevesque|1.1.4|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1. Help / Release Notes
2. Scroll in middle of the document
3. File / Preferences / Settings
4. switch back to opened Release Notes

Expected: previous opened document with our scroll position.

Actual: reloaded document with zero scroll positions.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/15214
