### ISSUE TITLE
preLoadTask for a task

### ISSUE THREAD

**Issue by hhucqian** [Microsoft/vscode#19821]
- VSCode Version: 1.9.0
- OS Version: windows 10

Steps to Reproduce:

1.
2.

I expect that one task can have a preloadtask.

```
{
    "version": "0.1.0",
    "tasks": [
        {
            "taskName": "A",
            "command": "A"
        },
        {
            "taskName": "B",
            "command": "B",
            "preLoadTask":"A"
        }
    ]
}
```

when I run task B, the task A  run before task B.

**Comment by dbaeumer** [comment]
This got implemented for the new task runner (version 2.0.0). The property in named dependsOn.
