### ISSUE TITLE
VS Code Speech - control start of search

### ISSUE THREAD

**Issue by ilearner777** [microsoft/vscode#198252]
## Current Behaviour
Note: by default we will start to search after a moment when you pause talking.

## Issue
Use Case 1: If I pause, while thinking, the extension starts a search before I am finished stating my question. 
Use Case 2: At times I want to say something, then paste some sample code, and then continue my question.

In both instances above, Copilot will not receive the intended answer with its current auto-start behaviour.

## Recommendations
1. Allow user to determine the length of delay,
2. Allow user to hot-key start of listening and then hot-key start of search.

**Comment by meganrogge** [comment]
You can configure that with `accessibility.voice.speechTimeout`
