### ISSUE TITLE
Copy-Paste not working in file explorer

### ISSUE THREAD

**Issue by pdanpdan** [microsoft/vscode#198235]
Type: <b>Bug</b>

In the latest versions of VSCode Insiders (not sure for how long) copy and paste of files in file explorer is not working anymore. It was working before.
Ubuntu 22.4 / Wayland

VS Code version: Code - Insiders 1.85.0-insider (54821ee1f14beca4866abd7de86175b4794b030d, 2023-11-14T12:46:44.247Z)
OS version: Linux x64 6.5.6-76060506-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 3635)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.06GB (19.75GB free)|
|Process Argv|--unity-launch --crash-reporter-id 609a073c-e838-44e0-83cd-756d613399cf|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|pop-wayland|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop-wayland|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
project-manager|ale|12.7.0
color-info|bie|0.7.2
vscode-fish|bma|1.0.37
postcss|css|1.0.9
transformer|dak|1.12.1
vscode-eslint|dba|2.4.2
xml|Dot|2.5.1
gitlens|eam|2023.11.1404
vscode-html-css|ecm|1.13.1
l13-diff|L13|1.3.4
i18n-ally|lok|2.12.0
rainbow-csv|mec|3.8.0
typescript-javascript-grammar|ms-|0.0.55
vscode-typescript-next|ms-|5.4.20231113
vscode-versionlens|pfl|1.9.2
material-icon-theme|PKi|4.31.0
vscode-sort-json|ric|1.20.0
vscode-gtm|s3r|0.2.0
sass-indented|syl|1.8.28
language-stylus|sys|1.16.0
volar|Vue|1.8.23
markdown-all-in-one|yzh|3.5.1
cursorCharCode|zei|0.2.4
vitest-explorer|Zix|0.2.43

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
synctok:30869157
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30859870
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by bpasero** [comment]
Maybe a regression from our support to paste files?

**Comment by pdanpdan** [comment]
It looks like it was fixed in

Version: 1.85.0-insider
Commit: 444e73750b99b11c3597a5f5d210d2b52257e377
Date: 2023-11-16T05:35:40.528Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.85.0-insider Chrome/114.0.5735.289 Electron/25.9.4 Safari/537.36

**Comment by pdanpdan** [comment]
I think it was fixed by this https://github.com/microsoft/vscode/commit/eca3d313b290097ca75834cac377fd5c0763739b
