### ISSUE TITLE
[MacOS] Do custom title bar possible with native tabs

### ISSUE THREAD

**Issue by viktor-berezin** [microsoft/vscode#198244]
When I set the setting window.nativeTabs to 'true', it's not possible to use window.titleBarStyle = 'custom'.
I know it works as designed. It says:

> Enables macOS Sierra window tabs. Note that changes require a full restart to apply and that native tabs will disable a custom title bar style if configured.

But why it's designed like that? I think it's a loss in user experience. Other editors can have both: custom window title bar and native macOS tabs. Example:

<img width="1727" alt="image" src="https://github.com/microsoft/vscode/assets/3610010/093c19b0-f29f-4525-9d2c-e4771e053f08">

**Comment by flying-sheep** [comment]
why was this closed?
