### ISSUE TITLE
Window scrolls while selecting text, causing selection to jump

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#19827]
I've never seen this before so I suspect this is regression in 1.9.0.

- VSCode Version: 1.9.0
- OS Version: Windows 10 Pro

I'm editing a markdown file that contains both text and code blocks. I have the preview open on the right (split screen). When I drag my mouse to highlight text in the editor on the left, it randomly scrolls, causing my selection to go the opposite way to where I was dragging from the start point.

It's really random; it took me 10-15 drags to repro for this GIF, however it seemed to be happening more frequently when I wasn't trying to repro.

I don't know how well this GIF will illustrate the issue, but I start dragging from line 217 (`items.sort();`) and drag upwards. After my selection gest to line 211, the editor suddenly scrolls down, (across a few frames of this GIF) resulting in my selection running from line 217 to 227 (the opposite direction).

![Selection scrolling](https://cloud.githubusercontent.com/assets/1078012/22588681/cafe464c-e9fe-11e6-9ead-5e57e4a70a1b.gif)

**Comment by DanTup** [comment]
I don't seem to be able to repro without the preview open; so wonder if it may be related to the new feature that tries to sync the windows (though I don't think it's expected that the left window ever scrolls for this?).

**Comment by DanTup** [comment]
I just realised that it is intended that the left pane can be scrolled - scrolling the left pane causes the right to scroll.

So I suspect what's happening is cursor is being moved around on left pane, which is causing the right pane to scroll, which for some reason is then causing the left pane to scroll.

**Comment by bpasero** [comment]
Looks like markdown scrolling is causing this?
