### ISSUE TITLE
Undo history is gone if currently opened file is edited by external application or extensions.

### ISSUE THREAD

**Issue by v3ss0n** [Microsoft/vscode#19826]
Related  #19800 
Recreating the issue since this is not caused by extension at all. 

- VSCode Version: 1.9
- OS Version: Linux

Steps to Reproduce:

1. Edit the currently opened files .
2. Edit it on external editor and save it.
3. Changes reloads instaly but Undo History is gone.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/2908
