### ISSUE TITLE
[BASH] Wrong syntax highlight for declare and local when specifying a variable with an attribute

### ISSUE THREAD

**Issue by GrabbenD** [microsoft/vscode#198284]
**Setup:**
- Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: 1.84.2
- OS Version: Arch Linux

**Steps to Reproduce:**
* `File > Preferences > Theme > Color Theme > Dark`
  ![dark](https://github.com/microsoft/vscode/assets/45666572/f3705c55-c8c7-47e5-8697-a66a018f9e72)
* `File > Preferences > Theme > Color Theme > Dark Modern`
  ![dark_modern](https://github.com/microsoft/vscode/assets/45666572/1e277a3e-8331-4bbd-bdb3-4de3c3554f01)
* `File > Preferences > Theme > Color Theme > Dark+`
  ![darkplus](https://github.com/microsoft/vscode/assets/45666572/b48b25d9-6995-42ea-9f0f-9fba5391ea19)

**Problems:**

When specifying a variable attribute (like `-r`) with `declare` and `local`, the syntax highlight breaks (see screenshot above):
* Variable names get the same color as values.
* Array elements get the same color as function names.

_(for clarification, any option in `declare` & `local` breaks the syntax highlight, not just `-g` and `-r`)_

Reference (full list of options):
* https://www.gnu.org/software/bash/manual/bash.html#index-declare
* https://www.gnu.org/software/bash/manual/bash.html#index-local (has same options as `declare`)

Related:
* https://github.com/microsoft/vscode/issues/176190

**Example:**

```bash
# REFERENCE

FUNCTION_CALL

correct="ok"
export correct="ok"

declare correct="ok"
declare correct=(
    "all"
    "good"
)

local correct="ok"
local correct=(
    "ok"
    "works"
)


# PROBLEM

declare -g wrong="bad"
declare -g wrong=(
    "even"
    "worse"
)

local -r wrong="bad"
local -r wrong=(
    "bad"
)
```

**Comment by RedCMD** [comment]
should move report to https://github.com/jeff-hykin/better-shell-syntax
and a code snippet would be nice

**Comment by RedCMD** [comment]
That extension is the grammar that vscode ships with by default

thanks for the snippet

@jeff-hykin

**Comment by GrabbenD** [comment]
> That extension is the grammar that vscode ships with by default

Huh, I don't see it under my extensions list, is it hidden/compiled into VSCode at build time?
I'm confused because the README suggests it can be installed `Just install the VS Code extension and the changes will automatically be applied to all relevent files.`?

> -g isn't supported atm?

For clarification, _any_ option passed to `local` or `declare` breaks the syntax highlight, not just `-r` and `-g`

**Comment by aeschli** [comment]
I created https://github.com/jeff-hykin/better-shell-syntax/issues/69

@GrabbenD The built-in extesnion for shellscript copied the grammar from that repo. The fix needs to be made there.

https://github.com/microsoft/vscode/blob/ab413e8ec67b8c6a87fd51f93978fa3db734abc6/extensions/shellscript/syntaxes/shell-unix-bash.tmLanguage.json#L3
