### ISSUE TITLE
Autofix doesn't handle cursor/selection correctly

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19828]
_From @rebornix on October 25, 2016 17:22_

Testing https://github.com/Microsoft/vscode/issues/14319 .

Repro steps:
1. Turn on eslint rule `curly` as `warn`.
2. Insert following code into the editor, put cursor just after the semicolon.
   
   ```
   if (foo) foo++;
   ```
3. Save
### Expected

The content is changed to `if (foo) {foo++;}` and the cursor is after `}`
### Actual

The content is fixed correctly while both `;` and `}` are selected.

![screen shot 2016-10-25 at 10 21 38 am](https://cloud.githubusercontent.com/assets/876920/19696635/d9175f0e-9a9c-11e6-83fe-aa82837136d8.png)
### Note

This issue won't happen if you already put cursor elsewhere.

_Copied from original issue: Microsoft/vscode-eslint#161_

**Comment by dbaeumer** [comment]
I checked this and the edit actually looks ok to me:

```
[Trace - 12:12:32 PM] Received response 'textDocument/willSaveWaitUntil - (14)' in 1ms.
Result: [
    {
        "range": {
            "start": {
                "line": 2,
                "character": 10
            },
            "end": {
                "line": 2,
                "character": 16
            }
        },
        "newText": "{foo++;}"
    }
]
```

Moving to VS Code since this is nothing ESLint can fix.

**Comment by alexandrudima** [comment]
When editing the model directly (which is what autofix on save does I think), the edit goes directly to the model, and the cursor is left to "recover" its position from markers.

This edit causes one of the two markers used by the cursor to move as it is making edits exactly at the cursor position.

In the core, the edits can give a hint as to their semantics https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/core/editOperation.ts#L11 via the `forceMoveMarkers` flag.

Additionally, we could send this edit through to the web worker to compute a more minimal edit.

**Comment by jrieken** [comment]
Today we use the [bulk edit](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/bulkEdit.ts#L154) here. That's the same we use for rename and find/replace across files. It should be aware of the current editor...

**Comment by roblourens** [comment]
@rebornix and I can't get eslint autofix to work at all, whether by `eslint.autoFixOnSave` or the command palette. Same in 1.9 and 1.10. Am I missing something?

**Comment by roblourens** [comment]
Actually, it's fine. We just messed it up a couple times (eslint out of date, syntax error in js file)
