### ISSUE TITLE
html auto-formatting: preserve my line breaks between attributes

### ISSUE THREAD

**Issue by Andikki** [Microsoft/vscode#19829]
- VSCode Version: 1.9.0

The new `html.format.wrapAttributes` settings is nice, but can it be extended with an option to keep "manual" wrapping? 
`"html.format.wrapAttributes": "auto"` condenses all attributes into one line (or multiple lines if max length is reached).
`"html.format.wrapAttributes": "force|force-align|force-expand-multiline"` inserts a line break between each attribute.
It would be nice to have an option of making your own line breaks between attributes where you feel it's best (but so that auto-formatter still indents, removes empty lines and extra spaces, inserts missing spaces, etc.).

**Comment by aeschli** [comment]
We use [jsbeautify](https://github.com/beautify-web/js-beautify) as formatter. Please file the request there.

**Comment by Andikki** [comment]
https://github.com/beautify-web/js-beautify/issues/1125
