### ISSUE TITLE
dotnet restore not working with generated Blazor project.

### ISSUE THREAD

**Issue by shindighost** [microsoft/vscode#198254]
Type: <b>Bug</b>

dotnet restore
  Determining projects to restore...
C:\git\Personal\TravelBlog8\TravelBlog8.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.Components.WebAssembly (>= 8.0.0)' for 'net8.0'. [C:\git\Personal\TravelBlog8\
TravelBlog8.sln]
C:\git\Personal\TravelBlog8\TravelBlog8.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.Components.WebAssembly.DevServer (>= 8.0.0)' for 'net8.0'. [C:\git\Personal\Tr 
avelBlog8\TravelBlog8.sln]

I have DevKit (pre-release), SDK .Net 8.0, 

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (18.66GB free)|
|Process Argv|--crash-reporter-id 1b1a67ae-ef1c-49da-a403-932def47efb0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.136.0
copilot-chat|Git|0.10.1
vscode-azureresourcegroups|ms-|0.7.5
vscode-cosmosdb|ms-|0.20.0
csdevkit|ms-|1.1.9
csharp|ms-|2.10.28
dotnet-maui|ms-|0.5.50
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26
azure-account|ms-|0.11.6
live-server|ms-|0.4.11
powershell|ms-|2023.8.0
material-icon-theme|PKi|4.31.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
vscrpc:30673769
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30887143
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2cf:30871583
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016cf:30886111
dsvsc017cf:30886113
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by sandy081** [comment]
Please file the issue against the dotnet extension.
