### ISSUE TITLE
"View staged changes" icon should not be a magnifying glass?

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#198200]
I found it confusing that the icon for opening multi-diff editor is a magnifying glass. Should it maybe match GHPR's icon or have some other icon? 

![Image](https://github.com/microsoft/vscode/assets/16353531/4184d70c-a96b-44cc-9cf2-bcfdd68e6e85)

**Comment by hediet** [comment]
Fixed in #198768. FYI @jrieken 

Maybe we should create a new icon for this though @hbons?
