### ISSUE TITLE
ERROR: Failed building wheel

### ISSUE THREAD

**Issue by suchitrakumari** [microsoft/vscode#198258]
Type: <b>Bug</b>

Hi,

Getting error while installing dbt-sqlserver in VS terminal.
Below last few lines of error:

  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects

I have all updated versions of python /pip/ pyodbc, stc.
Anything is missing? Clearly as mentioned in note, that it is not problem with pip.

Thanks
Suchitra

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (4.56GB free)|
|Process Argv|--crash-reporter-id 892b6946-1e59-433a-9f5a-28b8d997dba7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
gitignore|cod|0.9.0
compareit|in4|0.0.2
vscode-dbt-power-user|inn|0.24.2
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
notepadplusplus-keybindings|ms-|1.0.7
jinjahtml|sam|0.20.0
snowflake-vsc|sno|1.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30886110
dsvsc017:30886112
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by suchitrakumari** [comment]
Using cached PyJWT-2.8.0-py3-none-any.whl (22 kB)
Building wheels for collected packages: pyodbc
  Building wheel for pyodbc (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyodbc (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      WARNING: '' not a valid package name; please use only .-separated package names in setup.py
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      copying src\pyodbc.pyi -> build\lib.win-amd64-cpython-312
      running build_ext
      building 'pyodbc' extension
      creating build\temp.win-amd64-cpython-312
      creating build\temp.win-amd64-cpython-312\Release
      creating build\temp.win-amd64-cpython-312\Release\src
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DPYODBC_VERSION=4.0.39 -IC:\Suchi\dbt_workspace\demo_dbt_proj\dbt_venv\include -IC:\Users\Suchi\AppData\Local\Programs\Python\Python312\include -IC:\Users\Suchi\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpsrc\buffer.cpp /Fobuild\temp.win-amd64-cpython-312\Release\src\buffer.obj /Wall /wd4514 /wd4820 /wd4668 /wd4711 /wd4100 /wd4127 /wd4191 /d2FH4-
      buffer.cpp
      C:\Users\Suchi\AppData\Local\Programs\Python\Python312\include\cpython/unicodeobject.h(343): warning C4365: '=': conversion from 'unsigned int' to 'int', signed/unsigned mismatch
      C:\Users\Suchi\AppData\Local\Programs\Python\Python312\include\cpython/unicodeobject.h(367): warning C4365: '=': conversion from 'unsigned int' to 'int', signed/unsigned mismatch
      C:\Users\Suchi\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(121): warning C4365: 'initializing': conversion from 'uintptr_t' to 'Py_ssize_t', signed/unsigned mismatch
      C:\Users\Suchi\AppData\Local\Programs\Python\Python312\include\cpython/ceval.h(31): warning C5039: 'PyUnstable_Eval_RequestCodeExtraIndex': pointer or reference to potentially throwing function passed to 'extern "C"' function under -EHc. Undefined behavior may occur if this function throws an exception.
      C:\Users\Suchi\AppData\Local\Programs\Python\Python312\include\cpython/abstract.h(60): warning C4365: 'return': conversion from 'size_t' to 'Py_ssize_t', signed/unsigned mismatch
      C:\Users\Suchi\AppData\Local\Temp\pip-install-elxrl73c\pyodbc_e6dbcae02c22454dbea91f5c45d992f0\src\pyodbccompat.h(75): error C3861: 'PyUnicode_FromUnicode': identifier not found
      C:\Users\Suchi\AppData\Local\Temp\pip-install-elxrl73c\pyodbc_e6dbcae02c22454dbea91f5c45d992f0\src\pyodbccompat.h(86): error C3861: 'PyUnicode_AS_UNICODE': identifier not found
      C:\Users\Suchi\AppData\Local\Temp\pip-install-elxrl73c\pyodbc_e6dbcae02c22454dbea91f5c45d992f0\src\pyodbccompat.h(126): error C3861: 'PyUnicode_GET_SIZE': identifier not found
      C:\Users\Suchi\AppData\Local\Temp\pip-install-elxrl73c\pyodbc_e6dbcae02c22454dbea91f5c45d992f0\src\pyodbccompat.h(146): error C3861: 'PyUnicode_GET_SIZE': identifier not found
      C:\Users\Suchi\AppData\Local\Temp\pip-install-elxrl73c\pyodbc_e6dbcae02c22454dbea91f5c45d992f0\src\pyodbccompat.h(147): error C3861: 'PyUnicode_AS_UNICODE': identifier not found
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyodbc
Failed to build pyodbc
ERROR: Could not build wheels for pyodbc, which is required to install pyproject.toml-based projects

**Comment by aeschli** [comment]
Can you explain how this is related to VS Code?
Is it a command that you run in the terminal?

**Comment by suchitrakumari** [comment]
Yes, Getting error while installing dbt-sqlserver in VS terminal.

**Comment by aeschli** [comment]
If you use an external terminal, that error doesn't show?
I'm trying to find out how VS Code is involved here. This issue tracker is for issues of VS Code.

**Comment by suchitrakumari** [comment]
I tried both, getting same error.

**Comment by suchitrakumari** [comment]
![image](https://github.com/microsoft/vscode/assets/17451750/69d85797-a422-43d8-a12c-1760b8330160)

**Comment by suchitrakumari** [comment]
![image](https://github.com/microsoft/vscode/assets/17451750/302f6cd0-5761-43ac-be02-e0efb486f261)
