### ISSUE TITLE
memory leak in commentsController

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#198234]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: Ubuntu 23.04

Steps to Reproduce:

1. Open an editor
2. Close the editor
3. Notice that a `CodeEditorWidget` was created but not removed

```json
{
  "instanceCountsWithSourceMap": {
    "before": [
      {
        "name": "CodeEditorWidget",
        "count": 1
      }
    ],
    "after": [
      {
        "name": "CodeEditorWidget",
        "count": 2
      }
    ]
  },
  "isLeak": true
}
```

In Chrome devtools, the retainer chain points to `commentsController.ts`:

![comments-controller](https://github.com/microsoft/vscode/assets/23744935/4c6534b5-88e4-45fd-ae18-fd0d2411304d)

**Comment by alexr00** [comment]
I discussed with @bpasero, and when an editor is closed it is not disposed unless it is the last editor in the group and the group isn't the default group, so in the scenario described in this issue, the `CodeEditorWidget` is still expected to exist. Here's how to check if the `CodeEditorWidget` is being leaked:

1. Open an editor. Check how many `CodeEditorWidget`s you have.
2. Open a second editor in a new editor group.
3. Close the editor in the second group. Check how many `CodeEditorWidget`s you have. If there is no leak, there should be the same number as in step 1.

I have tested, and I don't see a memory leak from `CommentsController`.

**Comment by SimonSiefke** [comment]
@alexr00 Thanks a lot for the info, it's really helpful!

And apologies, you're absolutely right! I was so focused looking for something that would explain the two `CodeEditorWidgets` and didn't really think about anything else.

Your steps make much more sense and with that I don't see a memory leak from `CommentsController`.

No wonder it took me so long to find the apparent source, when there is none... xD

Thanks again!
