### ISSUE TITLE
`Views and more actions` button uses aria role of `presentation` but shouldn't

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#198233]
Elements marked as presentational should not have global ARIA or tabindex to ensure all screen readers ignore them (presentation-role-conflict - https://dequeuniversity.com/rules/axe/4.7/presentation-role-conflict?application=msftAI)

In this case, we want screen readers to be aware of them, so we need to change the role to `button`.

**Comment by Samhitha66** [comment]
#Visual Studio Code; #CAITestPass_May2020;

**Comment by ShaileshChudawkar** [comment]
#Regressed:12-05-23; 
@meganrogge Issue is repro in the web (Chrome). could you please implement the changes in web version.

**Comment by aniketr99** [comment]
#Visual Studio Code Client; #BM-VisualStudioCodeClient-Win32-Aug2023;
