### ISSUE TITLE
Please create an official VSCode Mastodon account

### ISSUE THREAD

**Issue by mlcohen** [microsoft/vscode#198231]
This isn't a "feature" request but, rather, a very humble request for someone on the VS Code team to please setup an official VS Code [Mastodon](https://joinmastodon.org) account. Currently the VS Code team only has a [Twitter/X account](https://twitter.com/code). There are many developers who use VS Code who would prefer to follow updates on Mastodon. This would be very easy to do. Just setup an account on [mastodon.social](https://mastodon.social/explore) (e.g. `vscode@mastodon.social`). Get the account [verified](https://joinmastodon.org/verification) and add prominent links to the account on the [VS Code website](https://code.visualstudio.com).

<img width="1161" alt="Screenshot 2023-11-14 at 10 35 06 AM" src="https://github.com/microsoft/vscode/assets/100445/ab27eb24-4742-4120-b8ce-043c0ad50786">

**Comment by czfadmin** [comment]
What does Mastodon do? Is it a competitor to Twitter?

**Comment by mlcohen** [comment]
Should note that Microsoft's TypeScript engineer team has an official and verified Mastodon account https://fosstodon.org/@TypeScript. Perhaps that gives some precedent for the VS Code engineering team to setup an official Mastodon account.

**Comment by TylerLeonhardt** [comment]
When we consider taking on a new social media account, we want to make sure we are able to take on the overhead of:

* A new feedback channel
* Another place where we need to post updates
* Another place where we should engage (ex. boost others posts aka retweeting)

and that the usage is worth that overhead.

At this time, we are not looking to create a Mastodon account.

**Comment by mlcohen** [comment]
@TylerLeonhardt Appreciate the response. 

I do hope the VS Code team will take another look at Mastodon at some point and consider establishing an official presence on Mastodon. There is a thriving, active developer community on Mastodon who I'm sure would love to follow you there rather than on Twitter/X (especially given everything that has been happening with Twitter over the past year, and, even more so, the past month).

Just for reference, here are some other official developer-related Mastodon accounts that have some intersection with VS Code:

- Python - https://fosstodon.org/@ThePSF
- Rust - https://social.rust-lang.org/@rust
- PHP - https://fosstodon.org/@php & https://phpc.social/@thephpf
