### ISSUE TITLE
Dependency cycle between browserHostService.ts and web.api.ts

### ISSUE THREAD

**Issue by rehmsen** [microsoft/vscode#198220]
This is not a user visible bug, but a code health issue in the main branch - I was not sure how to best report this.

I am from Google and we have some patches to avoid dependency cycles in the TypeScript source (which our build system does not allow). As I think this cycle also makes the code harder to understand, and is relatively easy to fix, I will send a PR to see if you would be willing to have it resolved.

**Comment by bpasero** [comment]
Thanks. If you have more patches that you think should be upstreamed, feel free to discuss.
