### ISSUE TITLE
Add support for `.yaml-tmlanguage`, `.yaml-tmpreferences` and `.yaml-tmtheme` file extensions

### ISSUE THREAD

**Issue by scripthunter7** [microsoft/vscode#198290]
`.yaml-tmlanguage` extension is used to specify the syntax highlighting for popular languages, such as TypeScript:
https://github.com/microsoft/TypeScript-TmLanguage/blob/master/TypeScript.YAML-tmLanguage

Currently, the workaround is to push the settings file to Git:
https://github.com/microsoft/TypeScript-TmLanguage/blob/master/.vscode/settings.json

In addition, `.yaml-tmlanguage` extension is also [supported by GitHub Linguist](https://github.com/github-linguist/linguist/blob/c1c34e5260797b4d598f5ec76f19723bfc5a1894/tools/grammars/compiler/loader_fs.go#L18-L24).

It would be nice if VSCode could support these aliases to YAML natively.

**Comment by aeschli** [comment]
If you want to make a PR, that would be great!

**Comment by scripthunter7** [comment]
@aeschli I made a PR, I hope it's good: https://github.com/microsoft/vscode/pull/198300
