### ISSUE TITLE
Settings UI enum dropdown can show itself in the top left of the window

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#198251]
1. Click the dropdown caret
2. Hover over an enum value
3. :bug: dropdown appears in top left 

<img width="574" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/3eb97c23-27ac-4c41-a2a4-f6404421ec88">

**Comment by gjsjohnmurray** [comment]
I have seen this occasionally too, but haven't discovered a repro.

Perhaps #197987 is related.

**Comment by gjsjohnmurray** [comment]
See also #197755

**Comment by joyceerhl** [comment]
For me this reproduces 100% of the time precisely when I hover over the dropdown list values, and I even repro it when the settings UI is the only active editor (no splitview or gridview)

**Comment by rzhao271** [comment]
I'm able to repro https://github.com/microsoft/vscode/issues/197755, but I'm unable to repro this issue where the context menu already goes to the top-left while still in the Settings editor.

**Comment by bpasero** [comment]
@joyceerhl if you repro, then please `vscode-bisect` it to the change!

**Comment by joyceerhl** [comment]
🤔 `vscode-bisect` claims there is no released insiders for 657bb89984f37b810b250955570593cde0cd62eb even though I got that from the insiders builds page after checking `Show released only` based on https://github.com/microsoft/vscode/issues/197755#issuecomment-1811538701

![image](https://github.com/microsoft/vscode/assets/30305945/ab0ae54e-d095-415a-902b-a287cc587c72)

**Comment by joyceerhl** [comment]
I cannot repro in Code-OSS :(

**Comment by bpasero** [comment]
@joyceerhl `vscode-bisect` goes over unreleased builds as well. What is the commits range?

**Comment by joyceerhl** [comment]
@rzhao271 found that he could repro https://github.com/microsoft/vscode/issues/197755 between 1.78.2 and 1.79.2

**Comment by bpasero** [comment]
@joyceerhl thats a different bug

**Comment by joyceerhl** [comment]
FWIW, I tried debugging in dev tools
* We relayout the context view on hover here https://github.com/microsoft/vscode/blob/e1c8870cd21051aaf9b2582d7b4dcea5d874bf08/src/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L776
* On a good layout, `DOM.getDomNodePagePosition(this.view).top` and `DOM.getDomNodePagePosition(this.view).left` are 0 here https://github.com/microsoft/vscode/blob/e1c8870cd21051aaf9b2582d7b4dcea5d874bf08/src/vs/base/browser/ui/contextview/contextview.ts#L351-L352
* On a bad layout, `top` === `DOM.getDomNodePagePosition(this.view).top` and `left` === `DOM.getDomNodePagePosition(this.view).left`, so `this.view.style.top` and `this.view.style.left` get zeroed

**Comment by bpasero** [comment]
@joyceerhl interesting, I wonder if maybe we cannot find the `window` for the element in `getDomNodePagePosition`, there were recent changes. Having a change in https://github.com/microsoft/vscode/pull/198269 to always ensure we fallback to the main window.

**Comment by atom0s** [comment]
Also seeing this issue as of tonight on latest `1.85.0-insider` build. 

When attempting to hover a dropdown list, it will jump to (0,0). Then when trying to hover it while it's at (0,0) will cause it to jump back to the list it came from.
It will continue to do this over and over, basically playing _"catch me if you can!"_ with the mouse.

Personal environment information:

```
Version: 1.85.0-insider (system setup)
Commit: b3a649fe52c0fb8692c9b28dfe25227c97521884
Date: 2023-11-15T09:43:13.091Z (1 hr ago)
Electron: 25.9.4
ElectronBuildId: 25127168
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
```

  - VSCode Insiders `1.85.0-insider`
  - Windows 11 Pro 23H2

I did not personally see this issue until tonight. It started on a previous version of Insiders, but I allowed it to update before coming to file a bug report to see if it was a known issue that was already fixed. It is still happening on latest. But seems to be happening less frequently now.

**Comment by joyceerhl** [comment]
@bpasero I cannot repro anymore in latest Insiders :+1:
