### ISSUE TITLE
[Feature Request] Make it easy to create file or folder in the root directory

### ISSUE THREAD

**Issue by andreynering** [Microsoft/vscode#19824]
- VSCode Version:

```
Version 1.9.0
Commit 27240e71ef390bf2d66307e677c2a333cebf75af
Date 2017-02-02T08:31:00.827Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

- OS Version: Windows 10 Pro x64

It's easy to create a file or folder in a folder with a right-click:

![vs1](https://cloud.githubusercontent.com/assets/7011819/22587680/d572815c-e9e9-11e6-95ba-1a1b6ca97ff9.png)

Unfortunately, that don't work for the root directory: there's no right-click menu. There are buttons to create a file or folder, which I'd expect to create in the root, but actually create in the selected directory:

![vs2](https://cloud.githubusercontent.com/assets/7011819/22587757/2b65a576-e9ea-11e6-925c-67521f4867d6.png)

I think allowing the right-click menu in the root would be the best option.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1043

**Comment by bpasero** [comment]
@andreynering you can right click on empty space below the explorer to create a file/folder at root, but I agree this does not work when you have many elements:

![image](https://cloud.githubusercontent.com/assets/900690/22601815/f5944248-ea40-11e6-8f59-7e8e006d1947.png)
