### ISSUE TITLE
Questionable use of QuickPick as a confirmation dialog or alert

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#19822]
When opening old projects with the VS Code 1.9.0 I now get this QuickOpen menu:

![2017-02-03_10-32-15](https://cloud.githubusercontent.com/assets/1898161/22586552/b041a52a-e9fd-11e6-9949-e0b2576850cb.png)

I fully understand why we do this, but I think the use of QuickPick in this situation is confusing (and I even have proof for this from user studies done by @stevencl in debug land).

The problem with QuickPick is that it is normally used when the user explicitly triggered an action with multiple choices: the QuickPick menu does not come as a surprise in these cases.

But in the situation at hand the user has requested VS Code to open a specific workspace and does not expect a QuickPick to appear. And from past experience he has learned, that there is no QuickPick when opening a workspace.

Even I am still surprised by the QuickPick in this case and quickly press Esc to make it go away because I suspect that I've accidentally triggered some action. 

We have seen the same in the debug user studies: when users started debugging for the first time by pressing F5 they have no launch.json and a QuickPick menu appears offering different debug environment choices. Since users are not expecting this, they dismiss the menu quickly and debugging will fail. They are not realising that an important decision needs to be made here.

Could we try to introduce a different UI for situations like this? Something like an modal "alert/confirmation style" QuickPick?

/cc @stevencl @bpasero

**Comment by bpasero** [comment]
Yes, my first feedback was (via mail?) that we still need to show a message to the user and then show quick pick as a user interaction. I fully agree that quick pick right after startup makes no sense.

**Comment by jrieken** [comment]
We are about to add modal dialogs that allow for arbitrary buttons etc

**Comment by weinand** [comment]
I'm not really suggesting to introduce buttons and such.
But could we try to make the instruction "Select the TypeScript version..." in the QuickPick from above visually stronger so that the user understands that he needs to make a decision before dismissing the menu.

**Comment by bpasero** [comment]
-1, a quick pick opens with some options and I as a user have no idea why we opened this picker. Unless we want to change the UI of the picker to be more like a dialog with message and explanation I suggest to use the message service first and then the picker.

**Comment by joaomoreno** [comment]
We could somehow show some alerting affordance in the TypeScript version status bar widget that would catch the user's eye. Once clicked, the quick open would appear.

**Comment by weinand** [comment]
I'd prefer a general solution that we can use everywhere.
E.g. for the "Select debug environment" QuickPick or the "process picker" QuickPick that surprises some users.

 problem that we can ecause we would like

**Comment by weinand** [comment]
The 'javascript' and 'typescript' labels are misleading: I've created the issue to discuss the use of QuickPick in general. The typescript QuickPicker is just an example.

**Comment by isidorn** [comment]
I share concers @weinand pointed out. And yes we do similar bad usages of quick open in debug land.

Now the question is when we really need input from the user to continue do we:
1. Always use dialogs - so the user can not dismiss them withouth choosing
2. Continue using quick open as we do now but we let the user easily get back into the state of getting that quick open if he dismissis it (as Joao suggests via status bar in this case)
3. Add some quick open options such that the quick open clients can make it more stable (such that the user can not easily dismiss it via ESC)

I think that whatever we decide we should just be consistent across our UX so the users get familiar with this approach.

**Comment by weinand** [comment]
@stevencl could we talk about this while you are in ZRH?

**Comment by kieferrm** [comment]
@weinand @stevencl  I'd expect these questions to be covered by the notification system discussion. Correct?

**Comment by stevencl** [comment]
Yes, that's correct.

**Comment by mjbvz** [comment]
Closing since autoshowing the version selector was mainly done for workspace migration. We removed this a few iterations back
