### ISSUE TITLE
"IntelliSense inside string values for tasks.json and launch.json to get a full list of predefined variables" not supported

### ISSUE THREAD

**Issue by phommy** [microsoft/vscode#198203]
Type: <b>Bug</b>
related documentation: https://code.visualstudio.com/docs/editor/variables-reference

![3](https://github.com/microsoft/vscode/assets/24478780/f835b8fe-7190-4af8-8144-a5c2fbf83c8e)
![2](https://github.com/microsoft/vscode/assets/24478780/094b0140-803a-4f56-abc1-48fd9bcd697f)
![1](https://github.com/microsoft/vscode/assets/24478780/46fd4d7c-599e-484e-b585-e020ed0478e2)

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (3.27GB free)|
|Process Argv|--crash-reporter-id 4fcbbd0d-1853-4bf6-91a1-1f7263893c52|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by phommy** [comment]
![3](https://github.com/microsoft/vscode/assets/24478780/5d53c810-2319-4b2e-aece-b1e2321f0c9b)
![2](https://github.com/microsoft/vscode/assets/24478780/ed59c128-d459-4953-9c44-3e0e6f286e97)
![1](https://github.com/microsoft/vscode/assets/24478780/a43fd481-393f-4a90-a36d-64ffc85b3a7e)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/182700
