### ISSUE TITLE
staged changes are always collapsed 

### ISSUE THREAD

**Issue by FernandoMiguel** [microsoft/vscode#198206]
Type: <b>Bug</b>

`  "git.alwaysShowStagedChangesResourceGroup": true`

anytime i stage changes, the staged changes block of the SCM is collapsed and requires me to manually expand it.
previously it would be expanded.

VS Code version: Code - Insiders 1.85.0-insider (94959e85502687ec77e23eb0d4d4b1a827b919af, 2023-11-14T05:45:03.848Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|12, 16, 24|
|Memory (System)|32.00GB (3.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
inline-hasher|ale|1.1.0
spellright|ban|3.0.118
iam-policy|bin|0.0.1
copilot|Git|1.136.0
copilot-chat|Git|0.10.1
terraform|has|2.29.2023110810
vscode-kubernetes-tools|ms-|1.3.15
indent-rainbow|ode|8.3.1
ytt-lint|phi|0.3.1
vscode-yaml|red|1.14.0
vscode-gitweblinks|red|2.9.3
iam-legend|Seb|1.1.48
kubernator-vscode|smp|1.0.0
code-spell-checker|str|3.0.1
shellcheck|tim|0.34.0
sort-lines|Tyr|1.11.0
errorlens|use|3.15.0
vscode-icons|vsc|12.6.0
json|Zai|2.0.2

(1 theme extensions excluded)

</details>

**Comment by Maxim-Mazurok** [comment]
I'm having the opposite problem... No matter the `alwaysShowStagedChangesResourceGroup` value, whenever I stage a file - it automatically expands "Staged Changes". So I have to collapse it again or scroll a lot to see unstaged changes. I think something got broken there...

```
Version: 1.85.0-insider (user setup)
Commit: 055458feab40fc308fc6d70b185068138c8cf8eb
Date: 2023-11-27T05:35:23.734Z
Electron: 25.9.4
ElectronBuildId: 25127168
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by lszomoru** [comment]
@FernandoMiguel, @Maxim-Mazurok, sorry for not getting back to you on this until now. 

Could you please check the value of the `scm.autoReveal` setting? Is this setting enabled? If so, this might explain when the "Staged Changes" resource group is automatically expanded when you stage a file. If you disable the setting, than the "Staged Changes" resource group should maintain its state as you stage files - if it's closed, it should stay closed, if it's open it should stay open.

**Comment by amunger** [comment]
This still doesn't seem to be working correctly, and I don't see any difference when changing the value of `git.alwaysShowStagedChangesResourceGroup`.

1. set `git.alwaysShowStagedChangesResourceGroup` to false
2. stage a change, collapse that group in the SCM view
3. switch tabs to a file that has a staged change
result: Staged Changes group expands

Also, staging a change doesn't expand that group if it was collapsed and `git.alwaysShowStagedChangesResourceGroup`: true. I wouldn't necessarily expect that, but it sounds like that was the original issue?

**Comment by Maxim-Mazurok** [comment]
Setting `scm.autoReveal` to `false` is a workaround

Also on fix PR page it says "This PR’s merge commit doesn’t appear in any tags" so maybe it wasn't released yet?

**Comment by Maxim-Mazurok** [comment]
Not sure if related, but also started seeing this:
![image](https://github.com/microsoft/vscode/assets/7756211/662aa6f9-e8be-494f-ab40-ecc546f9b687)

And overall weirdness navigating. For example when I click on file in explorer view - nothing happens, it doesn't open. Window reload fixes.

And when renaming file, it looses the name in the UI shows up as blank. Again window reload fixes.

**Comment by lszomoru** [comment]
@Maxim-Mazurok, that is unrelated to this issue. We are spinning a new Insiders build to get that fixed.

**Comment by lszomoru** [comment]
@amunger, thank you very much for verifying this issue. The `git.alwaysShowStagedChangesResourceGroup` setting is not in scope for the issue that was reported here. That setting only controls whether the "Staged Changes" group is being shown when empty or not. 

Here are the verification steps:
* Open a folder/workspace that contains a git repository 
* Ensure that `scm.autoReveal` is set to `true`
* Make changes to 2/3 files, and save the changes
  * Confirm that the files appear in the "Changes" resource group 
* Stage the first file
  * Confirm that the file is moved to the "Staged Changes" resource group
  * Confirm that the "Staged Changes" resource group is expanded
* Collapse the "Staged Changes" resource group
* Stage another file
  * Confirm that the "Staged Changes" resource group stays collapsed
