### ISSUE TITLE
Setting a color for whitespace symbols doesn't work anymore

### ISSUE THREAD

**Issue by Instagit** [Microsoft/vscode#19830]
**VSCode Version:**

Version 1.9.0
Commit 27240e71ef390bf2d66307e677c2a333cebf75af
Date 2017-02-02T08:21:13.228Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**OS Version:**

Ubuntu 16.04

**Steps to Reproduce:**

I'm using [this](https://github.com/Instagit/vscode-theme-monokai-dark-soda-whitespace/blob/master/themes/monokai-dark-soda-whitespace.tmTheme) theme to make whitespace visible only when it's selected, by giving whitespace symbols the same color as the background.

````
<key>invisibles</key>
<string>#242424</string>
````

This has stopped working in version 1.9.0.

**Comment by alexandrudima** [comment]
Interestingly, this works for me on master:

![invisibles](https://cloud.githubusercontent.com/assets/5047891/22603023/f6b44894-ea45-11e6-8c1c-6ec2ebc0629e.gif)

**Comment by alexandrudima** [comment]
Seems to be fixed 2 days ago at #19647
