### ISSUE TITLE
"Add include path to settings"

### ISSUE THREAD

**Issue by neilyoung** [Microsoft/vscode#19834]
- VSCode Version:Version 1.10.0-insider (1.10.0-insider), 723b20093d2f525e84cdf94a52f7695d1d539273
- OS Version: Mac OSX Sierra

Steps to Reproduce:

1. Open a C++ project
2. See the box "Add include path to settings" popping up every now and then

PS: Happens whenever I change to another file using the tabs

**Comment by neilyoung** [comment]
PPS: Due to this bug the navigation between source and header is broken as well. The header is opened, but the cursor is not positioned correctly.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by neilyoung** [comment]
Uhmm. What I can tell you, that I didn't have had this problem before today's update of VSCode. So even if an extension has to be blamed, it is VSCode which did break something initially.

Anyway. I switched back to the official VSCode version, which doesn't have this issue

**Comment by maxtruxa** [comment]
@neilyoung This is a bug with the C/C++ extension (v0.10.0). It's already been fixed in the v0.10.1 release, but not published yet. See [this issue](https://github.com/Microsoft/vscode-cpptools/issues/472).

**Comment by neilyoung** [comment]
@maxtruxa Thanks for the pointer. I will check later once the new version is out

**Comment by neilyoung** [comment]
@maxtruxa : Confirmed
