### ISSUE TITLE
Extensions update button missing

### ISSUE THREAD

**Issue by norbertfuhs** [Microsoft/vscode#19838]
- VSCode Version: 1.9.0
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Click on Extensions
2. Show Extensions 

If there is an update for an extension I have to click through each extension to see which I can update. In the past versions of Visual Studio Code there was an update button right inside the list view of the installed extensions to update them.

I attached a picture to show you what I mean I hope this makes the issue clearer:

![bildschirmfoto 2017-02-03 um 13 59 05](https://cloud.githubusercontent.com/assets/17197786/22592238/fd831baa-ea18-11e6-8164-f1ad2c80ada3.png)

**Comment by mrmlnc** [comment]
Wow, it's magic 🔮 

![screencast 2017-02-03 16-10-01](https://cloud.githubusercontent.com/assets/7034281/22592687/0506d408-ea2c-11e6-9f05-22bb108f2b99.gif)

**Comment by norbertfuhs** [comment]
Okay ...-.- sorry...
