### ISSUE TITLE
How to set Integrated Terminal default encoding to UTF-8?

### ISSUE THREAD

**Issue by frocelu** [Microsoft/vscode#19837]
- VSCode Version: 1.9.0
- OS Version: Windows 10 x64

Steps to Reproduce:
As title，I want to set the default encoding of Integrated Terminal to UTF-8.But I don't know how to do this.
Please teach me how to do this,thanks.

**Comment by yuriy-06** [comment]
"tsc" �� ����� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� �������� 䠩���.

here is what the compiler is writting

    VSCode Version: 1.9.0
    OS Version: Windows 7 x64 / language = russian

**Comment by frocelu** [comment]
You can use "chcp" command to set the encoding of Terminal.
Ex: chcp 65001 to UTF-8.
But, you need do this when vs code open everytime.

**Comment by frocelu** [comment]
If Integrated Terminal can execute some script automatically,it will help.

**Comment by Tyriar** [comment]
I don't know much about setting shell encoding on Windows so any help would be appreciated. If this can be set via an environment variable then that is doable. By default VS Code sets the `$LANG` environment variable on macOS to fix this there.

**Comment by yuriy-06** [comment]
"chch 65001" not helped in output window, I just set locale to "en", as explained here - https://code.visualstudio.com/docs/customization/locales. 
It may be working some in preferences 
"terminal.integrated.shell.windows": "C:\\Windows\\system32\\cmd.exe \K chcp 65001",
or
  "terminal.integrated.shellArgs.windows": [chcp 65001],

**Comment by frocelu** [comment]
Thank yuriy-06，but it not works.
Error happens.

**Comment by yuriy-06** [comment]
I'm run in cmd.exe "REG ADD HKCU\Console /v CodePage /t REG_DWORD /d 65001 /f"
when i'm run vscode, in output window:
"Parameter format not correct - 65001"
but when i'm typed
"D:\...\projekt\fund_ts-master>chcp" => 
Active code page: 65001.
Maybe it's the solution?

**Comment by yuryleb** [comment]
`"terminal.integrated.shellArgs.windows": ["/K", "chcp 65001"],` works better :wink:

**Comment by Tyriar** [comment]
@daviwil should this arg be rolled into the vscode-powershell extension? Is there any reason this isn't the default?

**Comment by gpassero** [comment]
@yuryleb I set PYTHONIOENCODING to UTF-8 and your solution didn't work for me. This one seems to have worked:

`"terminal.integrated.shellArgs.windows": ["-NoExit", "/c", "chcp.com 65001"],`

**Comment by Tyriar** [comment]
Ping @daviwil

**Comment by daviwil** [comment]
Apologies, I've been buried in e-mail for the past week!  This seems like a general issue with the terminal right?  Seems that some here are having to configure cmd.exe with the same chcp call.  I'll make sure the PS extension's Integrated Console also sets the mode correctly.

**Comment by Tyriar** [comment]
@daviwil setting it as the default could cause issues as then users have to change the `shellArgs` when they change the `shell`. Otherwise the terminal will exit immediately with an ambiguous error message due to unrecognized args.

**Comment by artem-leonov** [comment]
But when use tasks with this workaround error happens. "Parameter format not correct - /d" for cmd and "Parameter format not correct - -Command" for powershell. I think you'll need to reopen this issue.

**Comment by Tyriar** [comment]
@artem-leonov if this is specific to tasks please create a new issue

**Comment by AbdellatifHousni** [comment]
In Windows,
I set "LC_ALL=fr_BE.UTF-8" as an environement variable (restart Visual Studio Code to apply)
