### ISSUE TITLE
Test explorer input uses wrong background color

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#198301]
* open test explorer
* notice that the input has the wrong background color, e.g it has two background colors

<img width="455" alt="Screenshot 2023-11-15 at 14 29 05" src="https://github.com/microsoft/vscode/assets/1794099/7549a3be-fdec-43a6-ba17-ea94efe9e716">

**Comment by connor4312** [comment]
What theme are you using? I'm not seeing any backgrounds being applied to that menu / menu bar 🤔

**Comment by jrieken** [comment]
Like, any light theme?

https://github.com/microsoft/vscode/assets/1794099/7afd478a-74e4-4691-8aca-bc6198748acb

**Comment by connor4312** [comment]
Still confused 😕  on the latest Insiders for me:

<img width="725" alt="image" src="https://github.com/microsoft/vscode/assets/2230985/96cc1efc-151d-4beb-bf31-0ee55728672d">

Does it reproduce on a fresh user-data-dir for you?

**Comment by jrieken** [comment]
I see. It doesn't show with an empty profile but I also don't have any setting that screams test explorer background color

**Comment by connor4312** [comment]
Could you bisect your user settings or share them so I can play around? 🙂

**Comment by jrieken** [comment]
This seems to be because I have the test explorer in the secondary sidebar. There is some settings that controls this but I have no clue which one it is

<img width="2188" alt="Screenshot 2023-12-12 at 18 02 53" src="https://github.com/microsoft/vscode/assets/1794099/917c24c0-2bb9-4a72-a2b5-07b67853251b">

**Comment by connor4312** [comment]
CSS is fun 🙃
