### ISSUE TITLE
Consolidate similar settings shared across components

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#198333]
As the product has grown, the number of settings has exploded and the product has become more complex as a result. Something that I've been passively thinking about for a while is the idea to consolidate similar features into a single one. This idea has come up just now again with @justschen's proposal for [allowing toggling of editor problem decorations](https://github.com/microsoft/vscode/issues/166797).

For example, take settings containing "font size" now:

![image](https://github.com/microsoft/vscode/assets/2193314/921db3d2-0100-40f0-b0a2-214e1f0abfa5)

That's 10 different font sizes for various different parts, some of which has slightly different key names (eg. `.fontSize` vs `...FontSize`) and all of which have slightly different descriptions. In the settings editor these take up 1 and a half pages on my monitor.

My proposal is essentially to deprecate these in favor of a setting like:

```ts
// I'm not sure whjat the right prefix would be for a "meta" setting
// like this that expands across the whole workbench
"workbench.fontSize": number | {
  "base": number, // base, *, etc?
  [componentId: string]: number;
}
```

So using it could look something like this:

```ts
// Set all font sizes to 12
"workbench.fontSize": 12;

// Set all font sizes to 12, but override terminal and editor
"workbench.fontSize": {
  "base": 12,
  "terminal": 13,
  "editor": 14
}
```

We could present this in the settings UI as a single setting with a list of components as checkboxes/textboxes, just with some way of setting everything. Similar to the show action button setting:

![image](https://github.com/microsoft/vscode/assets/2193314/97e94d68-617e-4521-8cab-498054585296)

An extra benefit of this is they would share the same base text but allow for an optional per-component description if needed.

cc @hbons @rzhao271 @sandy081 @aeschli 

---

## Technical details

As for how this could be implemented, the "base" feature could be declared somewhere in platform or workbench, driven by where the lowest level it's needed is. Components could then "register into" that declaration to add component ids to the setting schema.

We have a similar mechanism for this in a related problem of shared keybindings across different components where we have the solution of the `MultiCommand`:

https://github.com/microsoft/vscode/blob/e2670a457fbba846c8adebc70bcaec674c949866/src/vs/editor/browser/editorExtensions.ts#L188-L197

This allows registering different behavior for a command based on a `when` clause. This is actually something that the terminal should adopt but I was kind of late to discover it so it's just debt work that we may get to eventually.

**Comment by aeschli** [comment]
There are always many ways of grouping functionality. By component (e.g. terminal), by property (e.g. fontSize).

We've decided in the beginning, our settings are grouped by component (`editor`, `terminal`). Also we've decided in the beginning that we want a flat key/value structure. `"editor.x.a" "editor.x.b", not editor.x: { a: 1; b: 2 }`. There has been exceptions over time, but that's still the general rule.

Starting a different way of grouping or structuring on the JSON property level will just complicate things and not solve the problem that there are always many ways of looking at settings. Beside, migrating existing settings is challenging and a source of many errors and UX problems.
Instead, the settings UI should investigate offering different views. An idea is to annotate font size related settings so we can show them in a separate view.

**Comment by starball5** [comment]
I agree with @aeschli. On top of the complication of executing automation of format change (and how long would the code that does the update have to live in VS Code?), the amount of documentation- both official and unofficial- that would need to be updated would be a nightmare. I'd bet implementing the change and updates to the extension API would also be difficult (and the impact it would have on the extension ecosystem). I say this as someone who initially thought the flat structure was weird.

Why not just use/augment the `@...` mechanism in the settings UI for this? Like the existing `@feature:notebook`. There's already `tags` in the configuration contribution point, which I assume corresponds to searching with `@tag:`.
