### ISSUE TITLE
Ruby's `in` and `when` keywords decrease indentation incorrectly because of language configuration

### ISSUE THREAD

**Issue by vinistock** [microsoft/vscode#198350]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.2
- OS Version: MacOS latest

Steps to Reproduce:

1. Create a Ruby file
2. Create any class
```ruby
class Foo
end
```
3. Try to add include Bar
```ruby
class Foo
  include Bar
end
```
4. The include statement has its indentation decreased because it's incorrectly matched to an `in` keyword by the language configuration

The fix is in #198349.

**Comment by aiday-mar** [comment]
Should be fixed now
