### ISSUE TITLE
[Bug] The KeyboardEvent.getModifierState function can be undefined.

### ISSUE THREAD

**Issue by samirzubi-db** [microsoft/vscode#198308]
We have been encountering a type error `TypeError: t.getModifierState is not a function`

Steps to Reproduce:
Do not have a way to reproduce the issue but my hunch lies with a autofill event that does not have the `getModifierState` gets triggered. Noticed in `monaco-editor` library but the file associated with the issue is in [this library](https://github.com/microsoft/vscode/blob/43b0558cc1eec2528a9a1b9ee1c7a559823bda31/src/vs/base/browser/keyboardEvent.ts#L145).

**Comment by jrieken** [comment]
@samirzubi-db What browser do you use? According to https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState#browser_compatibility this should be supported since a couple of years everywhere

**Comment by alexdima** [comment]
Closing since we could not reproduce.

**Comment by justin-mellor** [comment]
@alexdima I have a reproduction for this issue in the monaco-editor
See https://github.com/microsoft/monaco-editor/issues/4325
It occurs in Edge and Chrome.

**Comment by Lindahot** [comment]
Send your details for help

**Comment by mivanyna** [comment]
This can be reproduces easily
