### ISSUE TITLE
“An external application wants to open [file] in Code” dialog does not remember “Allow opening local paths without asking” decision

### ISSUE THREAD

**Issue by martinbean** [microsoft/vscode#198336]
Type: <b>Bug</b>

Every time I try and open a file from say, a command line program, I get a prompt in Code saying:

> An external application wants to open [file] in Code. Do you want to open this file or folder?

Each time, I check the "Allow opening local paths without asking" and then click the "Yes" button, but I still get this prompt multiple times a day.

Is it possible to get this dialog to actually remember my decision to open local files without asking? Instead of constantly asking.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (0.01GB free)|
|Process Argv|. --crash-reporter-id d0190847-56db-4203-8f95-8148c095a0ae|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.10.1
vscode-eslint|dba|2.4.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
copilot|Git|1.137.0
copilot-chat|Git|0.10.1
vscode-github-actions|git|0.26.2
todo-tree|Gru|0.0.226
php-namespace-resolver|Meh|1.1.9
dotenv|mik|1.0.1
php-docblocker|nei|2.7.0
volar|Vue|1.8.23
vscode-typescript-vue-plugin|Vue|1.8.22
vscode-import-cost|wix|3.3.0
php-debug|xde|1.34.0

</details>

**Comment by martinbean** [comment]
Screenshot of dialog:

![Screenshot 2023-11-15 at 16 47 27](https://github.com/microsoft/vscode/assets/167312/8b901a0e-757a-4aa9-9e09-0fb434109b67)

**Comment by bpasero** [comment]
If you open the settings editor, change the `security.promptForLocalFileProtocolHandling` setting accordingly.

**Comment by martinbean** [comment]
It’s un-checked, which given the description sounds like the dialog shouldn’t be appearing at all?

![Screenshot 2023-11-15 at 19 19 37](https://github.com/microsoft/vscode/assets/167312/2cc1165d-d6f8-403b-83b0-45793340eaa6)

**Comment by bpasero** [comment]
Yeah strange, whats the full protocol link?

**Comment by sebj54** [comment]
Hi @bpasero, same problem here when opening files from WSL:

![image](https://github.com/microsoft/vscode/assets/5880435/4a2074ba-b285-42e8-8c9a-380c45c69564)

URL: 

```
vscode://vscode-remote/wsl+Ubuntu-22.04/home/myuser/myproject/myfile.php:305
```

`security.promptForLocalFileProtocolHandling` is also unchecked.

**Comment by bpasero** [comment]
@sebj54 Try: `security.promptForRemoteFileProtocolHandling`

**Comment by sebj54** [comment]
It is also unchecked. 

I also tried the following:

1. set `security.promptForRemoteFileProtocolHandling` to true 
2. tick the checkbox on the popup
3. `security.promptForRemoteFileProtocolHandling` is now unchecked

So it seems that these settings are not taken in account and the warning is shown everytime

**Comment by bpasero** [comment]
@sebj54 the setting is inverse, it needs to be `false` for the checkbox to be checked. Please read the settings description carefully.

**Comment by sebj54** [comment]
Yes I know that. I checked it only to see if the checkbox **on the confirm prompt** is working. The only thing that's working here is this checkbox on the confirm prompt.

The setting itself (`security.promptForRemoteFileProtocolHandling`) is not taken in account. The confirm prompt is shown whether it is `true` or `false`.

**Comment by bpasero** [comment]
Is this a normal install with local settings or anything special about it? Workspace settings?

**Comment by sebj54** [comment]
Yes it's a normal install. The setting only exists in remote (no user nor workspace setting)

**Comment by bpasero** [comment]
It needs to be configured locally, not remote.

**Comment by sebj54** [comment]
Then the confirm prompt does not set the correct setting I guess. Ticking the box updates the setting in remote and this setting does not appear anywhere than in remote. See screenshots below:

![Remote settings](https://github.com/microsoft/vscode/assets/5880435/ace2bbc3-8530-4db9-8db6-045f568f4835)

![User settings](https://github.com/microsoft/vscode/assets/5880435/8fcf9ae8-8aa8-4ed9-9b60-43b2f19841de)

![Workspace settings](https://github.com/microsoft/vscode/assets/5880435/ff46679b-95a1-4254-ac96-f93068ba7bde)

When I manually set it to `false` in my JSON user settings, it works as expected (the prompt is disabled), but the line I added is greyed out:

![JSON user settings](https://github.com/microsoft/vscode/assets/5880435/cc20063e-feca-43d8-a4b2-04719bd35382)

**Comment by bpasero** [comment]
Ah nice catch!

**Comment by sebj54** [comment]
It was hard to find out! Thanks for your help on this :)

**Comment by amunger** [comment]
is there an easy way to trigger this prompt?

**Comment by justschen** [comment]
@sebj54 @martinbean @bpasero bumping to see if the issue is fixed!

**Comment by sebj54** [comment]
@justschen @bpasero Sorry for the delay. I've tried to check if the issue is fixed with insiders version but could not figure out how to make it work from WSL (the URL scheme keeps launching stable version)

**Comment by bpasero** [comment]
This fix has meanwhile landed in stable!

**Comment by feliperaul** [comment]
Still having the same issue, Warp editor + VsCode

Version: 1.87.0 (Universal)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:56.944Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 21.5.0

![image](https://github.com/microsoft/vscode/assets/743879/0ceb5a0c-69cf-4bb1-b4f0-33a60b1c5a45)

![image](https://github.com/microsoft/vscode/assets/743879/1b11ad33-cce3-4fe0-b64f-47df3b7c6209)

**Comment by LightcastMouse** [comment]
I am also having the same issue and it is also with the warp application. Fur sure a correlation with warp. Causation is not confirmed.

**Comment by svallory** [comment]
Having this issue too and I'm using WezTerm. I'm opening files using `vscode://...`

**Comment by dgattey** [comment]
Still having this issue on macOS, just using Arc browser with Locator.js and VSCode stable, opening files using links like `vscode://file/Users/dgattey/checkouts/ghg/workspaces/app-dashboard/components/measure/footprint/CalculationMethodTiles.tsx:35:9`, where `ghg` is repo folder name. When I open it in VSCode I see this popup, which makes me think maybe the file is being treated as not remote OR local? Is there something about the resolution to `~` for the home folder that's messing with this setting still?
<img width="335" alt="image" src="https://github.com/microsoft/vscode/assets/982182/aae44be4-8147-496a-bb74-56015653856b">

I have this in my user settings and no overrides in my workspace settings:
```json
  "security.promptForRemoteFileProtocolHandling": false,
  "security.promptForLocalFileProtocolHandling": false,
```
