### ISSUE TITLE
Enable workspace-recommended extensions only for current workspace when installing them

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#198335]
Picking up this request from a comment on a now-closed-and-locked issue:

> It would be great for [workspace recommended extensions](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions) to install to the current workspace by default. This can allow developers to confidently install recommended extensions knowing that the extensions won't clutter up their editing experience working on other projects.
_Originally posted by @szhu in https://github.com/microsoft/vscode/issues/85735#issuecomment-584993761_

I was motivated to do this by #197136 from @bpasero, since as a contributor I recently updated my fork, accepted the new `jrieken.vscode-pr-pinger` recommendation, then had to to the following dance to turn off @jrieken's extension for all my other workspaces:

- Disable Extension
- Enable Extension for This Workspace Only

**Comment by sandy081** [comment]
@gjsjohnmurray I have unlocked the other issue and removed the duplicate label. Lets continue discussion there.
