### ISSUE TITLE
css style colspan

### ISSUE THREAD

**Issue by RailMapper** [microsoft/vscode#198311]
Type: <b>Bug</b>

VSCode message: Unknown property: 'colspan'. But it works.
see also https://html.spec.whatwg.org/multipage/tables.html#attr-tdth-colspan

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700G with Radeon Graphics          (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.37GB (25.06GB free)|
|Process Argv|--crash-reporter-id fdbc129c-e907-469e-bfc1-48dfcf7e2cf3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
gitlens|eam|14.5.0
prettier-vscode|esb|10.1.0
vscode-firefox-debug|fir|2.9.10
todo-tree|Gru|0.0.226
js-debug-nightly|ms-|2023.11.1317
LiveServer|rit|5.7.9
php-debug|xde|1.34.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30887144
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss2:30886141
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016cf:30886111
dsvsc017:30886112
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by aeschli** [comment]
Can you give me a small code sample? Is this CSS or HTML?

**Comment by RailMapper** [comment]
It referes to CSS: colspan: 2;. Target is a <table> to span the innerHTML in two columns in the same row. Intellisens says "Unknown property: 'colspan' css(unknownProperties)".
In the visible table the cells are correctly spanned with the innerHTML.

**Comment by aeschli** [comment]
Can you give me a small code sample?

**Comment by RailMapper** [comment]
Sorry, diving in the docs I found the reason of my misunderstanding. The "colspan" is an attribute of html elements td and th and not a style. But it did work - why? One failure did hide a second one in my project. Thanks for directing.
