### ISSUE TITLE
[Feature Request] Implement popping out the chat window for Github Copilot.

### ISSUE THREAD

**Issue by kynexis** [microsoft/vscode#198382]
I would like to be able to pop out the Github Copilot chat into a separate window that I can put on another monitor so I don't have to have the sidebar open in VSCode.

**Comment by bpasero** [comment]
This is already implemented in insiders. You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by aiday-mar** [comment]
Yes thank you for filing the issue. Indeed the feature is already implemented in Insiders and should come out in the next stable release. To do this, you can click on the three dots in the chat view and select the option `Open Session in New Window`.

<img width="477" alt="Screenshot 2023-11-16 at 09 01 51" src="https://github.com/microsoft/vscode/assets/61460952/21b7d01b-9831-4ac9-a8f9-689b3bd84a02">

This issue will be closed
