### ISSUE TITLE
window.menuBarVisibility bug

### ISSUE THREAD

**Issue by NiggyWizzyWoz** [Microsoft/vscode#19831]
- VSCode Version:
Version 1.9.0
Commit 27240e71ef390bf2d66307e677c2a333cebf75af
Date 2017-02-02T08:21:13.228Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:
Linux 4.8.17-1-MANJARO

Steps to Reproduce:

1. Set "window.menuBarVisibility": "hidden " in the user settings json file.
2. Restart the vscode.
3. The menu bar is still visible.

**Comment by bpasero** [comment]
This was fixed via https://github.com/Microsoft/vscode/issues/19777

You should consider to switch to the insiders channel where this fix will be in monday morning 👍 

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
