### ISSUE TITLE
fail to display the total counts of search results in jupyter

### ISSUE THREAD

**Issue by Shi-YuZhang** [microsoft/vscode#198359]
## Environment data

-   VS Code version:  1.85.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2023.11.1003202024
-   Python Extension version (available under the Extensions sidebar): v2023.21.13181010
-   OS (Windows | Mac | Linux distro) and version:  Linux
-   Python and/or Anaconda version: Anaconda
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | Remote

## Expected behaviour

search some content, and display the total counts of search results and the current index

## Actual behaviour

fail to display the total counts of search results in jupyter

in jupyter, it fails
<img width="492" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/74309824/e457a2ed-3c7a-4af0-81b2-e404b5147eec">

while in .R or .py, it works well
<img width="423" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/74309824/8c7eafa1-22c5-4a97-afb4-0a98494f34ab">

**Comment by starball5** [comment]
Is the issue just display width? Does it appear if you expand the find widget by dragging the sash to the left to make the widget longer?

If it's not a sizing issue, and a count value issue, then see also #194823 and [Find widget in Jupyter Notebook in VS Code gives inconsistent, high number of results](https://stackoverflow.com/q/77160190/11107541).

**Comment by Shi-YuZhang** [comment]
<img width="736" alt="image" src="https://github.com/microsoft/vscode/assets/74309824/fb8db33f-e35d-497a-b485-772f0d25725d">
<img width="720" alt="image" src="https://github.com/microsoft/vscode/assets/74309824/6bedc8ec-9ecc-444f-8e86-8a4e36034111">
I though it was not the issue of display

**Comment by Yoyokrazy** [comment]
cannot repro -- please attach a current version screenshot if this is still an issue on your setup.

**Comment by Shi-YuZhang** [comment]
版本: 1.97.0-insider
提交: 21a129e8d0fbdfabcae2444b04a0e4c3912c6fe1
日期: 2024-12-13T12:38:52.505Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

<img width="427" alt="Image" src="https://github.com/user-attachments/assets/ca489c62-ecf7-460f-a96b-cd6d3651e28d" />
<img width="692" alt="Image" src="https://github.com/user-attachments/assets/c0f3a528-5853-4992-832f-57620597c174" />
