### ISSUE TITLE
Live Share Chat webview image/css/js load issues (ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep)

### ISSUE THREAD

**Issue by jramsay** [microsoft/vscode#198365]
Version: 1.85.0-insider
Commit: b3a649fe52c0fb8692c9b28dfe25227c97521884
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Embedder: vscode.dev

**Issues:** 

1. Images are no longer loading in Live Share Chat's webview in vscode.dev (stable & insiders) (ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep)

    We use gravatar images from a separate npm package (gravatar-api "^1.5.0") 
    
    ex:      gravatar.imageUrl({email: email, parameters: { size: '200', d: 'retro' }, secure: true });
    
    GET https://secure.gravatar.com/avatar/cc0e5d4db395cc26979293047d3df3be?size=200&d=retro net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200 (OK)

(Please see full callstack and images below)

**Is there something new we have to do to use cross-origin images?  I've seen some issues that suggest adding the following to the img  tag might work `crossorigin="anonymous"`. I've been unable to test this out though due to the second issue below.** 

2. In vscode.dev we are no longer able to test out Live Share webview changes from our private developer extension (localhost) that is loaded via: View > Command Palette > `Developer: Install Extension from Location...`
 
Webview assets (.js/.css) fail to load due to a vscode-coi error:

![image](https://github.com/microsoft/vscode/assets/8161247/32b57854-8b6d-4f5c-9562-3b2507ae3182)

Further info for issue#1:

**Web:**

![image](https://github.com/microsoft/vscode/assets/8161247/baab27bf-85cf-43c7-b0bc-bdae2acd0bc3)

**Desktop:** Still works as expected

![image](https://github.com/microsoft/vscode/assets/8161247/44aaa0fc-0ded-4c52-b7b6-459411387b5b)

**Console:**
![image](https://github.com/microsoft/vscode/assets/8161247/46ce3189-b69c-46ad-b942-317753e2b7af)

        GET https://secure.gravatar.com/avatar/cc0e5d4db395cc26979293047d3df3be?size=200&d=retro net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200 (OK)
Image (async)
_o @ chunk-vendors.js:15
mo @ chunk-vendors.js:15
go @ chunk-vendors.js:15
k @ chunk-vendors.js:15
d @ chunk-vendors.js:15
b @ chunk-vendors.js:15
d @ chunk-vendors.js:15
b @ chunk-vendors.js:15
d @ chunk-vendors.js:15
(anonymous) @ chunk-vendors.js:15
Qt.e._update @ chunk-vendors.js:15
r @ chunk-vendors.js:15
e.get @ chunk-vendors.js:15
e @ chunk-vendors.js:15
en @ chunk-vendors.js:15
Jr.$mount @ chunk-vendors.js:15
Jr.$mount @ chunk-vendors.js:15
init @ chunk-vendors.js:15
v @ chunk-vendors.js:15
d @ chunk-vendors.js:15
b @ chunk-vendors.js:15
d @ chunk-vendors.js:15
(anonymous) @ chunk-vendors.js:15
Qt.e._update @ chunk-vendors.js:15
r @ chunk-vendors.js:15
e.get @ chunk-vendors.js:15
e @ chunk-vendors.js:15
en @ chunk-vendors.js:15
Jr.$mount @ chunk-vendors.js:15
Jr.$mount @ chunk-vendors.js:15
init @ chunk-vendors.js:15
v @ chunk-vendors.js:15
d @ chunk-vendors.js:15
C @ chunk-vendors.js:15
D @ chunk-vendors.js:15
O @ chunk-vendors.js:15
(anonymous) @ chunk-vendors.js:15
Qt.e._update @ chunk-vendors.js:15
r @ chunk-vendors.js:15
e.get @ chunk-vendors.js:15
e.run @ chunk-vendors.js:15
_n @ chunk-vendors.js:15
(anonymous) @ chunk-vendors.js:15
Rn @ chunk-vendors.js:15
Promise.then (async)
Ln @ chunk-vendors.js:15
Pn @ chunk-vendors.js:15
kn @ chunk-vendors.js:15
e.update @ chunk-vendors.js:15
e.notify @ chunk-vendors.js:15
set @ chunk-vendors.js:15
Yn.Jn.set @ chunk-vendors.js:15
(anonymous) @ app.js:1
postMessage (async)
(anonymous) @ index.html?id=773eb9f7-4c02-4542-bc4f-6aef28f1d951&origin=40824c4c-d6c0-45b5-9b97-cab06ac778ed&swVersion=4&extensionId=ms-vsliveshare.vsliveshare&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=https%3A%2F%2Fvscode.dev&vscode-coi=3:1168
HostMessaging.channel.port1.onmessage @ index.html?id=773eb9f7-4c02-4542-bc4f-6aef28f1d951&origin=40824c4c-d6c0-45b5-9b97-cab06ac778ed&swVersion=4&extensionId=ms-vsliveshare.vsliveshare&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=https%3A%2F%2Fvscode.dev&vscode-coi=3:308
secure.gravatar.com/avatar/87403bdb909cecb6d1d229c4d0a10076?size=200&d=retro:1

**Comment by mjbvz** [comment]
Sounds like fallout from us enabling CORP somewhat recently on vscode.dev


This comment has info on how you can continue testing locally: https://github.com/microsoft/vscode-dev/issues/987#issuecomment-1779724725. You should just need to make sure dev server sets CORP headers. The exact process depends on the dev server you are using


Then if you get local development working again, let me know if `crossorigin="anonymous"` works too

**Comment by jramsay** [comment]
thanks @mjbvz! that did the trick for local testing and the `crossorigin="anonymous"` does resolve the issue.

**Comment by jramsay** [comment]
@mjbvz: I was able to get my local (localhost) dev server to set the CORPS header as I was using Live Server. Our test team installs the Live Share extension that we copy to an Azure > Storage Account > Container (Blob)

Do you know how to add the "Cross-Origin-Resource-Policy": "cross-origin" header for this?

**Comment by mjbvz** [comment]
Azure blobs have a cors option that you can enable. Try turning that on and seeing if it also sets `Cross-Origin-Resource-Policy`
