### ISSUE TITLE
`Focus Sticky Scroll` command for the terminal

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#198369]
We have `editor.action.focusStickyScroll`, which allows keyboard only / screen reader users to focus the sticky scroll element. It would be cool to have this in the terminal too.

**Comment by Tyriar** [comment]
I'm not sure we need it focusable for the terminal? Right now it's unfocusable and supports clicking/hover only, but its functionality can be accessed with the keyboard via ctrl/cmd+up/down.

**Comment by meganrogge** [comment]
Yeah, maybe not 🤔 .
