### ISSUE TITLE
Unable to execute Python Scripts from VS Code via Powershell

### ISSUE THREAD

**Issue by sambrainerd** [Microsoft/vscode#19839]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.6|
|sublime-keybindings|ms-vscode|1.8.2|
|vscode-sql-beautify|sensourceinc|0.0.4|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. Open a python script
2. Execute it on the integrated terminal

![untitled](https://cloud.githubusercontent.com/assets/22213964/22593029/ab3f2ea4-ea42-11e6-88fe-f68145ba9eea.png)

The script is executed as `"python" c:/path/scriptname.py` when it should be `python c:/path/scriptname.py` (without the double quotes around the word python).

I don't know if there is a system setting to change how VS Code passes commands to powershell in this case, hence the bug report.

**Comment by Tyriar** [comment]
@sambrainerd the screenshot shows you entered `"python" c:/...` and it didn't work, does `python c:/...` work?

/cc @daviwil

**Comment by Tyriar** [comment]
@sambrainerd are you using the Python extension? How are you executing the script exactly?

**Comment by jefftham** [comment]
actually, i face the same problem. it happens when i do right-click and trigger "Run Python File in Terminal".
the powershell run with the command "python" c:/path/scriptname.py .
i think the word python should not be wrapped.

Manually triggering this command without wrapping python with double quotation mark is running flawlessly.

python c:/path/scriptname.py   instead of  "python" c:/path/scriptname.py

**Comment by daviwil** [comment]
I'm guessing that quotation marks are being used in case the full Python path is being specified.  PowerShell just treats it as a string unless you use the ampersand character before the string:

```
& "python" c:/path/scriptname.py when it should be python c:/path/scriptname.py
```

**Comment by jefftham** [comment]
FYI, i just updated my python extension in vscode to version 0.5.8 , it solved the problem that i have. Thank you.

**Comment by sambrainerd** [comment]
Updated the Python extension and it nows runs the command as ` & python c;/.../script.py`. I guess the problem is solved now.

**Comment by Tyriar** [comment]
Great to hear!

**Comment by Musaab** [comment]
I'm fully updated and having this problem today.

**Comment by Tyriar** [comment]
@Musaab I believe this is just how powershell works, you might want to switch to cmd.exe
