### ISSUE TITLE
Avoid blocking main thread when a folder is opened

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#198384]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.85.0-insider (user setup)
OS: Windows_NT x64 10.0.22518

These things block main thread significantly when starting up, following observations correspond to [this CPU profile](https://github.com/microsoft/vscode/files/13372609/git.cpuprofile), but can be reproduced almost consistently:

- [ ] Git extension uses `spawn` to "get the repository root" which can block over 3 seconds:

![image](https://github.com/microsoft/vscode/assets/13199757/298d264f-7bb8-4bfa-b809-894bd4fd8d69)

Note `spawn` in NodeJS is known to be synchronous and blocking: https://github.com/microsoft/vscode-python/issues/22146#issuecomment-1813773184. We can use worker threads here to spawn in a different thread, we've been doing the same in Python extension when spawning other binaries: https://github.com/microsoft/vscode-python/issues/22146

- [x] WSL recommender extension "gets telemetry" using "readFileSync" in the process, probably not necessary.

![image](https://github.com/microsoft/vscode/assets/13199757/5515caa6-f712-4f57-8954-3a14628e9288)

- [ ] This is probably required but extension host seems to use `readFileSync` which blocks some time:

![image](https://github.com/microsoft/vscode/assets/13199757/ed032573-8dd5-4079-9603-e2113d280bb8)
![image](https://github.com/microsoft/vscode/assets/13199757/55f9defd-fa10-4ac8-87a7-2bc0f9ca476b)

**Comment by lszomoru** [comment]
The Git extension uses `spawn` for **every git** operation. If there is a better way of doing things (ex: use workers) then we should explore doing that as it would have significant impact. I will look into this in December.

**Comment by aeschli** [comment]
I removed the WSL recommender extension: We no longer use it: https://github.com/microsoft/vscode/pull/198502

**Comment by lszomoru** [comment]
Spoke with @deepak1556 and the issue seems to be specific to @karrtikr's environment with more details here - https://github.com/microsoft/vscode-python/issues/22146. There is no need to any changes in VS Code so I am closing this issue.
