### ISSUE TITLE
Menu bar cannot be toggled off in v1.9.0

### ISSUE THREAD

**Issue by gilboa23** [Microsoft/vscode#19833]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-svgviewer|cssho|1.3.0|
|debugger-for-chrome|msjsdiag|2.5.1|
|sort-imports|peterjuras|2.2.3|
|tsimporter|pmneo|1.2.13|
|theme-mellow|yuvalg|0.0.2|

---

Steps to Reproduce:

1. Click on View menu -> Toggle Menu Bar
2. Menu bar remains visible

Also,

1. Settings -> "window.menuBarVisibility" = "toggle" or "hidden"
2. Menu bar remains visible

**Comment by bpasero** [comment]
This was fixed via https://github.com/Microsoft/vscode/issues/19777

You should consider to switch to the insiders channel where this fix will be in monday morning 👍 

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment]
@gilboa23 btw if you set it to `toggle` it should work, are you saying it does not even work with `toggle`?

**Comment by gilboa23** [comment]
Yes, i'm normally having this set to `toggle`. The setting is consistently ignored and the menu bar is always displayed. See attached screenshot:


![image1](https://cloud.githubusercontent.com/assets/18614824/22612318/88ab3528-ea78-11e6-88bf-3a5357a1b6c1.png)

**Comment by bpasero** [comment]
@gilboa23 can you try something for me: from that window, run File > New Window, are you then seeing the menu hidden or not?

**Comment by gilboa23** [comment]
The menu bar is visible also in the new window

**Comment by bpasero** [comment]
Ok, weird. I am out of ideas what this could be. Did you try our insiders build?
