### ISSUE TITLE
Settings UI is completely blank

### ISSUE THREAD

**Issue by arvid-norlander** [microsoft/vscode#198420]
Type: <b>Bug</b>

1. Open VS Code (with or without extensions disabled, makes no difference)
2. Open File -> Preferences -> Settings
3. Observe blank UI with no actual settings in it.

![image](https://github.com/microsoft/vscode/assets/132438847/1dda7c03-ac17-4318-9ed3-41357ef0eb6b)

If you leave the settings tab open and restart vs code (such that it reopens the settings tab automatically on restart) the settings GUI will be there, but *all the extension settings will be missing* (observe that it is missing from the menu here):

![image](https://github.com/microsoft/vscode/assets/132438847/fcc60996-919d-4886-9297-967184ea76b9)

*If I then close and reopen settings they will again be empty.*

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.2.0-36-generic (Ubuntu 22.04 LTS)
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12950HX (24 x 4156)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|62.29GB (54.92GB free)|
|Process Argv|--disable-extensions --crash-reporter-id f5e0695e-011b-4a71-ba0b-b0beb8be9ddf|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|plasma|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled

**Comment by arvid-norlander** [comment]
I also tried with `prime-run` to run this on the nVidia GPU instead of the built in Intel GPU. Makes no difference.

**Comment by rzhao271** [comment]
After running the command "Developer: Toggle Developer Tools", do any errors show up under the Console tab?

**Comment by arvid-norlander** [comment]
> After running the command "Developer: Toggle Developer Tools", do any errors show up under the Console tab?

Yes I got 3 errors, they all seem related to that I'm behind a corporate proxy though. Note that I ran this with `--disable-extensions`, but I still get errors related to extensions. I find this very strange

![image](https://github.com/microsoft/vscode/assets/132438847/4d8a0efb-90fa-4aa0-98bd-1d30d24560a5)
![image](https://github.com/microsoft/vscode/assets/132438847/d3003720-c191-4793-98ff-ed8677c757c7)
![image](https://github.com/microsoft/vscode/assets/132438847/a42c6cfc-92d3-47f3-8f8f-ac3134824a94)

**Comment by arvid-norlander** [comment]
@rzhao271 

When I'm not behind the proxy, settings work as expected. I find it *very odd* that VSCode would need to call out to the internet just to open settings. Opening the marketplace for extensions I understand, but not settings.

Especially since I can *also* open settings just fine if I'm completely disconnected. It is just if I'm connected via the corporate network that it falls flat on it's face.

For some further debug information: We use Zscaler at my workplace, which acts as a HTTPS MITM proxy. The proper certificate is installed in the system certificate store (`/etc/ca-certificates`) and that works as expected with other programs.

**Comment by rzhao271** [comment]
The Settings editor currently recommends the Copilot extension when it's not installed, which lines up with the error messages you're seeing.

I'll put up a PR that skips over showing that feature in case of networking errors.

**Comment by rzhao271** [comment]
Tomorrow's [VS Code Insiders](https://code.visualstudio.com/insiders/) should contain the fix.

**Comment by arvid-norlander** [comment]
@rzhao271 what about the bit where it seems to ignore the root system certificates though?

It seems there were actually (at least) two bugs here:
1. The one you fixed, where settings can't open when there are network errors
2. The fact that a corporate proxy with correctly installed CA certificates in the system store doesn't work. Presumably it isn't picking up the system CA certificates correctly.

**Comment by ShubhamCodeMaster** [comment]
thank you very much my problem is solved after follow this step  (Open VS Code disable  all extensions disabled, and enable once again all extension then i am successfully able to see my settings))

**Comment by chrmarti** [comment]
@arvid-norlander Please see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/cert_management.md#add-a-certificate on how to add a root certificate for Chromium, that also applies for Electron-based applications like VS Code.

The root certificate example is:
```
certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n <certificate nickname> -i <certificate filename>
```

**Comment by HongLinLiao** [comment]
I got the same issue in open setting.
And when I open setting, I got regular expression in developer tool

<img width="818" alt="截圖 2023-12-11 上午12 07 11" src="https://github.com/microsoft/vscode/assets/22143800/e59d3463-1127-4884-96ca-5532db134862">
