### ISSUE TITLE
Intellisense freezes at random instances

### ISSUE THREAD

**Issue by sqnkov** [Microsoft/vscode#19840]
- VSCode Version: 1.9.0 / 1.9.1
- OS Version: Windows

---
> **Tested on 4 different machines running Windows 10/Windows 10/Linux/macOS**

---

Steps to Reproduce:

1. Write code in * language
2. Observe lack of intellisense 

![prob2](https://cloud.githubusercontent.com/assets/9406520/22594060/26c60016-ea2a-11e6-935b-dbe44ff8b441.gif)

![3so4u0voqo](https://cloud.githubusercontent.com/assets/9406520/22594011/ed5249f2-ea29-11e6-9738-a890030363a8.gif)

This happened in =< 1.8,1 at random points of time, but it was okay for a bit after closing VS Code and starting it again. Now the situation is different. Intellisense stops every 2-3 lines of input.

No matter the language used.

As you can see, even code-hinting / linting does not work. So does auto-beautify or whatever plugin that has some kind of dynamic function. Every functionality except input is not present.

![classch](https://cloud.githubusercontent.com/assets/9406520/22597089/d9378fec-ea36-11e6-9db8-22211a4590f7.gif)

![rlsts](https://cloud.githubusercontent.com/assets/9406520/22597199/50f62cdc-ea37-11e6-9fb2-7b2a2a79f725.gif)

Git is on, Gulp is running in the Terminal (integrated)

Plugin list:

```
auto-close-tag - Version :0.3.9
auto-rename-tag - Version :0.0.11
beautify - Version :0.7.3
Bookmarks - Version :0.10.2
bracket-pair-colorizer - Version :0.2.1
code-settings-sync - Version :2.4.3
color-highlight - Version :1.3.1
gitignore - Version :0.5.0
guides - Version :0.6.1
html-snippets - Version :0.0.18
HTMLHint - Version :0.3.3
htmltagwrap - Version :0.0.3
lorem-ipsum - Version :1.0.0
path-intellisense - Version :1.2.0
php-intellisense - Version :1.1.1
stylelint - Version :0.22.0
theme-material-theme - Version :1.0.1
vscode-autoprefixer - Version :2.0.0
vscode-color - Version :0.2.3
vscode-eslint - Version :1.2.5
vscode-great-icons - Version :1.1.44
vscode-html-css - Version :0.0.33
vscode-scss - Version :0.6.1
vscode-todo-highlight - Version :0.3.3

```

**Comment by v3ss0n** [comment]
Experienced in javascript and python too.

**Comment by aeschli** [comment]
It looks like the extension host is no longer responding.
- Open the developer tools (Help > Toggle Developer Tools' and check the console.
- Open the output view and check for output in the 'Extensions' channel.
- Disable extension `html-css-class-completion` and see it this makes a difference.
- If that doesn't solve the issue, run without any extension (run code with `code --disable-extensions`) and see it that makes a difference.

@jrieken Any tips how to get more information what the extension host is busy doing?

**Comment by sqnkov** [comment]
Tried all the things you suggested, still no intellisense after initial try.

Here is my console log:

```
Overwriting extension <<.scss>> to now point to mime <<text/x-sass>>
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2601  for  bookmarks.toggle
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2602  for  bookmarks.jumpToNext
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2600  for  bookmarks.jumpToPrevious
[Extension Host] Windows_NT
[Extension Host] Looking for parseable documents...
[Extension Host] Found all parseable documents.
[Extension Host] Parsing documents and looking for CSS class definitions...
[Extension Host] Sumary:
[Extension Host] 8 parseable documents found
[Extension Host] 12407 CSS class definitions found
[Extension Host] 1724 unique CSS class definitions found
[Extension Host] 0 failed attempts to parse. List of the documents:
[Extension Host] 
[Extension Host] [Guides] Sending usage statistics...
[Extension Host] [Guides] Error while sending usage statistics: Error: getaddrinfo ENOTFOUND api.digitalparticle.com api.digitalparticle.com:80
[Extension Host] [Guides] Usage statistics will retry in the next 5 minutes

```

**Comment by jrieken** [comment]
This is most likely an issue with an extension consuming too much CPU time and therefore taking away the chances of other extensions doing something useful - all extension run in a single threaded process.

@sqnkov Are you saying this happens when you have started with `--disable-extensions`?

**Comment by sqnkov** [comment]
@jrieken  , indeed, I stopped the extensions like @aeschli said. 

I will do a full day of coding and will report back later in the day.

**Comment by sqnkov** [comment]
@aeschli , @bpasero , @jrieken 

1.9.1 Update - still being able to reproduce without failing. Any time. 

Disabled all extensions one by one.

I still think that Git markers that appear on the left cause this drop. The moment I go on a new line, start typing and get a green bar on the left, which means there is a new change that can be staged and pushed, is when intellisense stops.

![gt](https://cloud.githubusercontent.com/assets/9406520/22777851/55a6c3ba-eebd-11e6-838e-31f26c767c4d.gif)

**Comment by aeschli** [comment]
@joaomoreno FYI

**Comment by joaomoreno** [comment]
Can you reproduce in a workspace that is not a git repository?

**Comment by sqnkov** [comment]
@joaomoreno this also works at random. I am really frustrated.

Here is a CPU profile at the time of the issue. 
[CPU-20170209T121404.zip](https://github.com/Microsoft/vscode/files/763297/CPU-20170209T121404.zip)

**Comment by joaomoreno** [comment]
@sqnkov Can you reproduce in a workspace that is not a git repository?

**Comment by sqnkov** [comment]
The CPU profile that I've just uploaded is recorded in a non-Git environment.

**Comment by joaomoreno** [comment]
So, I assume it still happens even with Git disabled.

It's definitely very strange that it still reproduces with `code --disable-extensions`... so can I ask you to show us a CPU profile in that situation instead?

**Comment by sqnkov** [comment]
All extensions disabled:

[CPU-20170209T131311.zip](https://github.com/Microsoft/vscode/files/763465/CPU-20170209T131311.zip)

**Comment by aeschli** [comment]
Thanks a lot @sqnkov for your help, it is very much appreciated. It would be awesome if you can stick with us, as we're trying to nail this freezes (a.k.a intellisense stops to work).
The profile unfortunately doesn't tell me much as it only shows what's happening in the renderer process. What is busy is the extension host process or the CSS language server process and we only have limited capability to see what's going on there.

Experiment 1:
- launch code with `code --logExtensionHostCommunication`. Open the dev tools and observe the console. There are going to be a lot of messages. What's interesting is, what is the communication when you see the 'freeze'. Is the Extension host talking back to the Window? What's the last request that the Window sent to the Extension hist.

Experiment 2:
- set user setting `"css.trace.server": "messages"`. Open the output view on the 'CSS Language Server' tab. This logs the communication between the extension host and the css language server (again a separate process). My theory is that while the 'freeze' there will not be any communication as the extension host is frozen. 

Experiment 3:
- Check out the OS processes view. In windows, look at the 'Details' tab, sort by process 'Code' and observe the 'CPU', 'Memory' and 'Command Line' column while you see the freeze.

**Comment by aeschli** [comment]
![image](https://cloud.githubusercontent.com/assets/6461412/22781339/5bc36dfc-eec2-11e6-8c3d-fb857b1848c7.png)

**Comment by sqnkov** [comment]
@aeschli , where are the logs from the console stored? I have the option checked.

**Comment by aeschli** [comment]
You can access and save t from the Dev Tools Console:
 - Help > Toggle Developer Tools
- in the dev tool, open the 'Console' tab
- right click in the console: Save As...
![image](https://cloud.githubusercontent.com/assets/6461412/22781725/1c1b16d0-eec4-11e6-8688-b5a90db33571.png)

**Comment by sqnkov** [comment]
Took a bit longer this time, but still managed to freeze it. You will see it near the end, along with a lot of Ctrl+z

[-1486640401448.zip](https://github.com/Microsoft/vscode/files/763511/-1486640401448.zip)

**Comment by aeschli** [comment]
What are the steps you are doing? Typing, Ctrl+Space, Typing, Undo, Ctrl+Space ?

**Comment by sqnkov** [comment]
@aeschli I am basically clicking on a row, hitting enter, start typing a property, if intellisense appears, I hit `Ctrl+Backspace` to delete the property that I've just created, select a new row, repeat.

I am not using `Ctrl+Space` at all. 

But as I use it just now, it seems to be loading some type of intellisense stuff, or something like that.

**Comment by aeschli** [comment]
From the log it seems that extensions are still active, e.g. the SirTori/indenticator extension still writes to the status bar. 
- Can you start code with
`code --disableExtensions --logExtensionHostCommunication`

- Once code hast started, can you open the console and paste to the dev tools command line 
`var oldLog = console.log; console.log = function() { oldLog(JSON.stringify(arguments)); };`

![image](https://cloud.githubusercontent.com/assets/6461412/22788428/16f2fca6-eee0-11e6-825a-31e7bba7a1be.png)

That will give us some nicer rendering

- Then reproduce the error as before, and save the log.

**Comment by aeschli** [comment]
Also if you have any insights from Experiment 2. I'd love to see what the last messages were to the language server.

![image](https://cloud.githubusercontent.com/assets/6461412/22788673/defe20ea-eee0-11e6-8192-d3c7e605d48f.png)

BTW, thanks again for your time. I truly appreciate it.

**Comment by sqnkov** [comment]
@aeschli 

Experiment 2 Output:

```
[Trace - 17:06:38] Sending request 'initialize - (0)'.
[Trace - 17:06:38] Received response 'initialize - (0)' in 188ms.
[Trace - 17:06:38] Sending notification 'initialized'.
[Trace - 17:06:38] Sending notification '$/setTraceNotification'.
[Trace - 17:06:38] Sending notification 'workspace/didChangeConfiguration'.
[Trace - 17:06:38] Sending notification 'textDocument/didOpen'.
[Trace - 17:06:39] Sending request 'css/colorSymbols - (1)'.
[Trace - 17:06:39] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:39] Received response 'css/colorSymbols - (1)' in 242ms.
[Trace - 17:06:41] Sending notification 'textDocument/didChange'.
[Trace - 17:06:41] Sending notification 'textDocument/didChange'.
[Trace - 17:06:41] Sending request 'textDocument/codeAction - (2)'.
[Trace - 17:06:41] Sending request 'textDocument/completion - (3)'.
[Trace - 17:06:41] Received response 'textDocument/codeAction - (2)' in 285ms.
[Trace - 17:06:41] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:41] Received response 'textDocument/completion - (3)' in 433ms.
[Trace - 17:06:41] Sending request 'css/colorSymbols - (4)'.
[Trace - 17:06:41] Received response 'css/colorSymbols - (4)' in 10ms.
[Trace - 17:06:42] Sending notification 'textDocument/didChange'.
[Trace - 17:06:42] Sending request 'textDocument/codeAction - (5)'.
[Trace - 17:06:42] Received response 'textDocument/codeAction - (5)' in 206ms.
[Trace - 17:06:42] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:42] Sending notification 'textDocument/didChange'.
[Trace - 17:06:42] Sending request 'textDocument/codeAction - (6)'.
[Trace - 17:06:42] Received response 'textDocument/codeAction - (6)' in 199ms.
[Trace - 17:06:42] Sending notification 'textDocument/didChange'.
[Trace - 17:06:42] Sending request 'textDocument/codeAction - (7)'.
[Trace - 17:06:42] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:42] Sending notification 'textDocument/didChange'.
[Trace - 17:06:42] Sending request 'textDocument/codeAction - (8)'.
[Trace - 17:06:42] Received response 'textDocument/codeAction - (7)' in 250ms.
[Trace - 17:06:43] Received response 'textDocument/codeAction - (8)' in 340ms.
[Trace - 17:06:43] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:43] Sending request 'css/colorSymbols - (9)'.
[Trace - 17:06:43] Received response 'css/colorSymbols - (9)' in 10ms.
[Trace - 17:06:43] Sending notification 'textDocument/didChange'.
[Trace - 17:06:44] Sending request 'css/colorSymbols - (10)'.
[Trace - 17:06:44] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:44] Received response 'css/colorSymbols - (10)' in 165ms.
[Trace - 17:06:44] Sending notification 'textDocument/didChange'.
[Trace - 17:06:44] Sending request 'css/colorSymbols - (11)'.
[Trace - 17:06:44] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:44] Received response 'css/colorSymbols - (11)' in 153ms.
[Trace - 17:06:46] Sending notification 'textDocument/didChange'.
[Trace - 17:06:46] Sending request 'textDocument/codeAction - (12)'.
[Trace - 17:06:46] Sending request 'textDocument/completion - (13)'.
[Trace - 17:06:46] Received response 'textDocument/codeAction - (12)' in 216ms.
[Trace - 17:06:47] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:47] Received response 'textDocument/completion - (13)' in 314ms.
[Trace - 17:06:47] Sending notification 'textDocument/didChange'.
[Trace - 17:06:47] Sending request 'textDocument/codeAction - (14)'.
[Trace - 17:06:47] Received response 'textDocument/codeAction - (14)' in 186ms.
[Trace - 17:06:47] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:47] Sending notification 'textDocument/didChange'.
[Trace - 17:06:47] Sending request 'textDocument/codeAction - (15)'.
[Trace - 17:06:47] Sending notification 'textDocument/didChange'.
[Trace - 17:06:47] Sending request 'textDocument/codeAction - (16)'.
[Trace - 17:06:47] Received response 'textDocument/codeAction - (15)' in 308ms.
[Trace - 17:06:47] Sending notification 'textDocument/didChange'.
[Trace - 17:06:47] Sending request 'textDocument/codeAction - (17)'.
[Trace - 17:06:48] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:48] Sending notification 'textDocument/didChange'.
[Trace - 17:06:48] Sending request 'textDocument/codeAction - (18)'.
[Trace - 17:06:48] Received response 'textDocument/codeAction - (16)' in 660ms.
[Trace - 17:06:48] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:48] Received response 'textDocument/codeAction - (17)' in 470ms.
[Trace - 17:06:48] Sending request 'textDocument/codeAction - (19)'.
[Trace - 17:06:48] Received response 'textDocument/codeAction - (18)' in 412ms.
[Trace - 17:06:48] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:48] Received response 'textDocument/codeAction - (19)' in 259ms.
[Trace - 17:06:48] Sending request 'css/colorSymbols - (20)'.
[Trace - 17:06:48] Received response 'css/colorSymbols - (20)' in 12ms.
[Trace - 17:06:48] Sending notification 'textDocument/didChange'.
[Trace - 17:06:48] Sending request 'textDocument/codeAction - (21)'.
[Trace - 17:06:49] Sending notification 'textDocument/didChange'.
[Trace - 17:06:49] Sending request 'textDocument/codeAction - (22)'.
[Trace - 17:06:49] Received response 'textDocument/codeAction - (21)' in 272ms.
[Trace - 17:06:49] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:49] Received response 'textDocument/codeAction - (22)' in 306ms.
[Trace - 17:06:49] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:49] Sending notification 'textDocument/didChange'.
[Trace - 17:06:49] Sending notification 'textDocument/didChange'.
[Trace - 17:06:50] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:50] Sending notification 'textDocument/didChange'.
[Trace - 17:06:50] Sending notification 'textDocument/didSave'.
[Trace - 17:06:50] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:50] Sending request 'css/colorSymbols - (23)'.
[Trace - 17:06:50] Received response 'css/colorSymbols - (23)' in 213ms.
[Trace - 17:06:50] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:52] Sending request 'textDocument/documentHighlight - (24)'.
[Trace - 17:06:52] Sending request 'textDocument/codeAction - (25)'.
[Trace - 17:06:52] Received response 'textDocument/documentHighlight - (24)' in 28ms.
[Trace - 17:06:52] Received response 'textDocument/codeAction - (25)' in 29ms.
[Trace - 17:06:53] Sending notification 'textDocument/didChange'.
[Trace - 17:06:53] Sending request 'css/colorSymbols - (26)'.
[Trace - 17:06:53] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:53] Received response 'css/colorSymbols - (26)' in 178ms.
[Trace - 17:06:54] Sending notification 'textDocument/didChange'.
[Trace - 17:06:54] Sending request 'css/colorSymbols - (27)'.
[Trace - 17:06:54] Received notification 'textDocument/publishDiagnostics'.
[Trace - 17:06:54] Received response 'css/colorSymbols - (27)' in 170ms.
[Trace - 17:06:56] Sending notification 'textDocument/didChange'.
[Trace - 17:06:56] Sending request 'textDocument/codeAction - (28)'.
[Trace - 17:06:56] Sending request 'textDocument/completion - (29)'.

```

And the log file with `--disableExtensions --logExtensionHostCommunication`

[-1486652678891.zip](https://github.com/Microsoft/vscode/files/764036/-1486652678891.zip)

**Comment by aeschli** [comment]
Amazing, thanks. So the last message for the language server is a completion request without any response. After that, you still type, but don't see no code assist windows are seen anymore, nor any requests are sent to the extension host?

**Comment by sqnkov** [comment]
**Exactly.** 

The typing and row manipulation afterwards are just repeated attempts, to see if it is just some lag, but I think this is a more serious issue. I saw a 660 ms request from something in the tracer:

`[Trace - 17:06:48] Received response 'textDocument/codeAction - (16)' in 660ms.` - is this normal?

I hope there is a fix for all this.

**Comment by sqnkov** [comment]
@aeschli , did you managed to derive some verification from all this?

**Comment by aeschli** [comment]
Sorry, haven't find the culprit yet...

**Comment by v3ss0n** [comment]
this is fixed on 
https://github.com/Microsoft/vscode/commit/cc69bea6dfd868d010d88504a4b6a69aa52ee624 ?

**Comment by aeschli** [comment]
@sqnkov I think we found the issue. Thanks a lot for your help. You can verify the fix in the latest [insiders](https://code.visualstudio.com/insiders) build.

**Comment by sqnkov** [comment]
@aeschli , everything seems to be working fine now. Thanks for that!

**Comment by v3ss0n** [comment]
@aeschli , thanks , looking forward to the next release.

**Comment by aeschli** [comment]
verified based on [@sqnkov 's comment](https://github.com/Microsoft/vscode/issues/19840#issuecomment-281023186)

**Comment by Z3roCoder** [comment]
Hello!

I didn't want to open up a new Issue for this.
I am still having this problem, mainly with .ts/TypeScript and .js/JavaScript files.

I can work 10 Minutes, up to two hours until Intellisense just freezes,. If i press CTRL+Space, it only says "Loading...", but never actually loads the typings up anymore. I need to Restart VSCode to have it working again. 

I am on VSCode 1.11.1
Installed Plugins:
```
abusaidm.html-snippets
Angular.ng-template
christian-kohler.path-intellisense
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
donjayamanne.githistory
DotJoshJohnson.xml
eg2.tslint
fantasytyx.tortoise-svn
filipw.scriptcsRunner
lonefy.vscode-JS-CSS-HTML-formatter
michelemelluso.code-beautifier
mkaufman.HTMLHint
mquandalle.graphql
mrmlnc.vscode-csscomb
ms-vscode.csharp
ms-vscode.PowerShell
msjsdiag.debugger-for-chrome
polunzh.start-git
vismalietuva.vscode-angular-support
xabikos.JavaScriptSnippets 
```
All Plugins are up-to-date.
But I have this behaviour even without any active/installed Plugins.

Maybe it's worth noting that we have a pretty huge project (several hundret .ts/.js files), maybe it has something to do with that?

**Comment by sqnkov** [comment]
@aeschli , I can confirm @Z3roCoder 's information. 

The issue is back at full power.

**Comment by aeschli** [comment]
@sqnkov @Z3roCoder Please file a new issue. Please try with no extensions and please give detailed information where exactly the freeze happens. In what language, in what size of a file. Code examples are very useful.
