### ISSUE TITLE
Share "inputs" variables across tasks.json and launch.json - Please reconsider to implement it!

### ISSUE THREAD

**Issue by mkiessling-ifx** [microsoft/vscode#198498]
This a request, to consider, to implement the previously rejected request, to avoid duplicating of input variable in tasks.json and launch.json
Please see the closed issue "Share "inputs" variables across tasks.json and launch.json. #72579", and the high number of folks that would need such feature. 

Thank you for your understanding. :-)

**Comment by are-scenic** [comment]
It would be great to have it at least in `*.code-workspace`.

**Comment by roblourens** [comment]
Sorry, these are different feature areas and I still don't think it makes sense to do this, and we need to prioritize other things
