### ISSUE TITLE
Add support for search.action.focusNextSearchResult for in-document search

### ISSUE THREAD

**Issue by DavidA2014** [Microsoft/vscode#19844]
- VSCode Version: 1.9.0
- OS Version: Windows 10

Steps to Reproduce:

1. The Search Result Navigation search.action.focusNextSearchResult, bound to key f4, is useful but appears not to work for in-document searches (initiated by CTRL-F).

**Comment by bpasero** [comment]
Try with `editor.action.nextMatchFindAction`
