### ISSUE TITLE
[ux] Change how files are staged in Git view

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#19845]
Right now, the process for staging files in the git view involve me clicking the plus button along each file's name. This creates some problems if the list is too long, as the pane's scroll position keeps jumping here and there, and user cannot keep his mouse stable in one place and keep clicking the `+` button. They have to individually seek out each file they want to stage, and then click the button, otherwise they end up staging wrong files.

Observe:
![bug1](https://cloud.githubusercontent.com/assets/760112/22594551/7c8137f4-ea49-11e6-8bdf-d06b36122c29.gif)

vs

Git GUI
![bug2](https://cloud.githubusercontent.com/assets/760112/22594610/d218939c-ea49-11e6-8eaf-7fce3110788a.gif)

**Comment by joaomoreno** [comment]
There is multi select in there.

![kapture 2017-02-03 at 17 53 48](https://cloud.githubusercontent.com/assets/22350/22600193/be96ed4c-ea39-11e6-8f07-5ad62958bf9f.gif)

**Comment by kumarharsh** [comment]
@joaomoreno the multi-select seems to be broken in the new build: b2a55b

**Comment by joaomoreno** [comment]
@kumarharsh It is not yet implemented in the new SCM viewlet, currently in Insiders.

**Comment by kumarharsh** [comment]
@joaomoreno also, sometimes <kbd>Space</kbd>, Arrow keys stop working in the SCM input area... seems to be a bug spanning multiple areas in vscode... Restarting vscode, or reloading window fixes this.
