### ISSUE TITLE
Tasks/Integrated Terminal not picking up User Path

### ISSUE THREAD

**Issue by dotnetdan** [Microsoft/vscode#19848]
- VSCode Version: 1.9
- OS Version: Windows 7

It seems like VS Code is not inheriting the user level PATH in Windows 7. System level PATH is working fine.

Steps to Reproduce:

1. Run a shell command from either a task or integrated terminal
2. If the target is defined in User Path, "* is not recognized as an internal or exsternal command, operable program or batch file."

Anyone else having this behavior? Is it intended? It's been a few weeks since I was actively using VS Code, so I'm not sure exactly when this started happening, but it wasn't an issue before...

**Comment by dbaeumer** [comment]
I can't reproduce this neither in the terminal nor as a task. I executed the following task:

```json
    {
            "taskName": "Path",
            "command": "echo",
            "args": [
                "%PATH%"
            ],
            "isShellCommand": true
     }
```
and it prints the correct environment.

@Tyriar any idea what could cause this since it seems to happen in the terminal as well.

@dotnetdan any additional information you can provide? How do you start VS Code?

**Comment by Tyriar** [comment]
@dotnetdan you will need to close all instances of VS Code and relaunch of you have only just changed the environment variable, could this be what you're experiencing?

**Comment by dotnetdan** [comment]
After rebooting my computer, everything went back to normal - I hadn't rebooted in ages and corporate controlled system updates were pending, so maybe the issue was external to VS Code. Sorry for the false alarm.
