### ISSUE TITLE
Standard Git extension needs more methods exported

### ISSUE THREAD

**Issue by awhitenose** [microsoft/vscode#198484]
Standard Git extension needs more methods exported to make easier 3rd party VS Code extensions developing based on standard VS Code Git extension. 

I'm developing a simple extension for VSCode. It's based on standard [Git extension](https://github.com/microsoft/vscode/blob/main/extensions/git/src/repository.ts) I found some useful methods are not exported and not defined in git.d.ts, yet I can find them in the source of Git extension.

For example, I'd like to use exec() from Repository but also found that even simple rm() from Repository is not exported as well. I see no harm having these and other methods exported and making them available for extension developers.

I'm especially interested in exec() which would allow to run any custom Git commands from my extension, particularly interested in running a simple rm --cached for example.

For example I'd like the below code to work (this is an extraction, not a complete code), currently it does not because it can't call exec() in the last line since it was not exported and not available in the minimized git.ts:

```
const gitExtension = vscode.extensions.getExtension<GitExtension>('vscode.git')?.exports;
const git = gitExtension?.getAPI(1);
let repo = git.repositories[0];
if (repo) {
	let args = ['rm', '--cached', '--'];
	args.push(arg.path);
	await repo.exec(args);
}

```

**Comment by lszomoru** [comment]
@awhitenose, thank you very much for filing this issue. We do not plan for making the `exec()` method available through the git extension's API. You can, and some extensions implement their own `exec()` method (ex: GitLens) to run arbitrary git commands against a repository. If you would like to have the `rm()` method exposed, that is something that we can look at.

**Comment by awhitenose** [comment]
Thank you @lszomoru for your comments. But why do you think exposing exec() from git extension's API is a bad idea? Do you think other extension developers may use it wrong and do any harm to repositories etc? But the same is possible to do any other ways including writing their own exec(). Yes, I can go for my own exec() implementation but it's just more time while your git extension does great work and already have this implemented, then why to reinvent the wheel? 

If you can expose rm(), that would help with solving one small particular issue but getting access to exec() would be more generic if possible.
