### ISSUE TITLE
Everything became so slow since 2 days

### ISSUE THREAD

**Issue by alexsoyes** [microsoft/vscode#198489]
Type: <b>Bug</b>

Disable all extension, reset settings

VS Code version: Code - Insiders 1.85.0-insider (Universal) (444e73750b99b11c3597a5f5d210d2b52257e377, 2023-11-16T05:37:00.486Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (2.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-fr|MS-|1.84.2023111509

</details>

**Comment by M3ssman** [comment]
Same on Ubuntu 20.04 LTS V1.84.2

**Comment by Tyriar** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
