### ISSUE TITLE
VSCode hangs every now and then

### ISSUE THREAD

**Issue by nisarul** [microsoft/vscode#198485]
Type: <b>Bug</b>

My VSCode keeps on hanging every some time randomly. Earlier I thought it was because of remote machine(VSCode server) but it hangs even on local machine(without connecting to remote).
I then thought it was because of copilot or c+ extension as I had large workspace and so I disabled those extensions. Even then I faced same issue.
Then I tried on simple workspace with very few small files and still same issue.
I am not able to triangulate the rot cause.
I saw same issue even on latest insider versoin.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (2.42GB free)|
|Process Argv|--folder-uri file:///c%3A/xampp/htdocs --crash-reporter-id 09300a96-753b-461f-a161-961afbc08118|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azureautomation|azu|1.2.2
go-custom-format|bon|0.1.0
indented-block-highlighting|byi|1.0.7
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.4.2
composer-php-vscode|DEV|1.41.14263
intelli-php-vscode|DEV|0.10.14222
phptools-vscode|DEV|1.41.14263
profiler-php-vscode|DEV|1.41.14263
jquerysnippets|don|0.0.1
gitlens|eam|2023.11.1604
vscode-html-css|ecm|1.13.1
shell-format|fox|7.2.5
copilot|Git|1.137.0
copilot-chat|Git|0.10.1
copilot-labs|Git|0.15.1019
remotehub|Git|0.62.0
go|gol|0.40.0
jquery-snippets|Hri|1.0.0
better-cpp-syntax|jef|1.17.2
blockman|leo|1.7.5
bash-ide-vscode|mad|1.39.0
compare-folders|mos|0.23.0
vscode-kubernetes-tools|ms-|1.3.15
vscode-kubernetes-tools-syed|ms-|1.3.10
isort|ms-|2023.10.1
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
jupyter|ms-|2023.10.1100000000
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-powertoys|ms-|0.0.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.321.0
remote-ssh|ms-|0.108.2023110315
remote-ssh-edit|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.24.0
azure-account|ms-|0.11.6
azure-repos|ms-|0.38.0
cmake-tools|ms-|1.16.31
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2023.8.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.0
back-n-forth|nic|3.1.1
sqlite-viewer|qwt|0.3.13
vscode-yaml|red|1.14.0
format-html-in-php|rif|1.7.0
bash-debug|rog|0.3.9
zsh-debug|rog|0.1.3
cscope-code|Seu|0.0.6
bash-beautify|sha|0.1.1
helm-intellisense|Tim|0.14.3
cmake|twx|0.0.17
bracket-lens|wra|1.5.3
php-debug|xde|1.34.0
php-pack|xde|1.0.3
php-intellisense|zob|1.3.3
explicit-folding|zok|0.23.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30880073
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30887144
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss2:30886141
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30886110
dsvsc017cf:30886113
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command in Command Palette to investigate whether the problem is being caused by one of your extensions.

**Comment by nisarul** [comment]
Thanks @gjsjohnmurray 
![image](https://github.com/microsoft/vscode/assets/4020266/5931ef75-b182-43ab-90c5-1a24c5b1f462)

I'll keep this extension disabled for some time and check if all is back to normal.
