### ISSUE TITLE
folders to group extensions

### ISSUE THREAD

**Issue by JadsonHudson** [microsoft/vscode#198425]
Type: <b>Feature Request</b>

Add a folder structure that groups extensions so you can enable and disable multiple extensions at the same time. The objective is to facilitate the use of extensions for different programming languages.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 5.15.138-1-MANJARO
Modes:

**Comment by gjsjohnmurray** [comment]
Have you explored [Profiles](https://code.visualstudio.com/docs/editor/profiles) for this?

**Comment by JadsonHudson** [comment]
Oh no, thanks for your answer
