### ISSUE TITLE
When I push from to Github directly from Code I get an error

### ISSUE THREAD

**Issue by rmaclean** [Microsoft/vscode#1984]
I am not able to push to GitHub from inside VS Code? The git output looks like this:

```text
git push
remote: Anonymous access to rmaclean/Website_DevConf.git denied.
fatal: Authentication failed for 'https://github.com/rmaclean/Website_DevConf.git/'
```

​The anonymous part is odd, since I am prompted for my credentials and they are correct (I can use the command line tools fine).  I am not using credential helper at the moment.

**Comment by egamma** [comment]
Closing as a duplicate of #490.

**Comment by rmaclean** [comment]
Disagree it is a duplicate, maybe related but not duplicate. 

Reason being I do not use GitHub Desktop at all (I don't have it installed). I could workaround it by doing `git config --global credential.helper wincred` and restarting VSCode, however that is not a fix. I don't want to use credential helpers - I just want to type it in.

**Comment by egamma** [comment]
The root cause is a github authentication issue, if we address #490, then this issue should be addressed as well. I've reopened the issue so that we can verify this.

**Comment by joaomoreno** [comment]
@rmaclean This should be fixed by now, since Code supports requesting for credentials. Let me know otherwise.
