### ISSUE TITLE
Workbench.editor.showTabs does not support folder resource ranges and cannot be written to folder settings.

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#198435]
I saw this error suddenly:
![image](https://github.com/microsoft/vscode/assets/2193314/2edb7f24-1d6d-4523-8867-77bf2126840e)

I see it was recently added to .vscode/settings.json in a6469cae574176b71f043d32368e70ed5b8db6e1

I also agree with it, do you mean to do what I did for self-hosting? If so you need to temporarily allow it at the resource level, but we want to change that such that a project can not override the user's preference when it's no longer experimental.

**Comment by benibenj** [comment]
This is a bug I fixed, however when testing I accidently pushed a settings change to vscode. I removed it again. You should be able to just pull main and the error won't appear anymore. (#198439)
