### ISSUE TITLE
add  language Polish 

### ISSUE THREAD

**Issue by Kociak2115** [microsoft/vscode#198472]
vs code despite so many years on the market is still quite modest linguistically, Polish is missing, for example, I can help add in Polish but other languages are also missing

**Comment by Kociak2115** [comment]
@bpasero

**Comment by isidorn** [comment]
Thanks for letting us know. We are open to language contributions and more can be found in our docs here
https://code.visualstudio.com/docs/getstarted/locales#_can-i-contribute-to-a-language-packs-translations
