### ISSUE TITLE
debug.console.collapseIdenticalLines true but console is not collapsing them

### ISSUE THREAD

**Issue by ZLKam** [microsoft/vscode#198452]
This is my settings.json file.
`{
    "workbench.colorTheme": "Default Dark Modern",
    "remote.SSH.defaultExtensions": [
        "gitpod.gitpod-remote-ssh"
    ],
    "remote.SSH.remotePlatform": {
        "wechaty-gettingstarted-p0m1umwi5h2.vss.gitpod.io": "linux"
    },
    "redhat.telemetry.enabled": false,
    "launch": {
        "configurations": [
            {
                "type": "python",
                "name": "Debug(Launch) - Current File",
                "request": "launch",
                "args": [],
                "console": "internalConsole",
                "program": "${file}"
            }
        ],
        "compounds": []
    },
    "debug.console.collapseIdenticalLines": true
}`

And a screenshot of my debug console.
![image](https://github.com/microsoft/vscode/assets/105273994/8a951a40-75d8-4aa6-90fa-77e95d43dc5c)

**Comment by roblourens** [comment]
Did some experimenting and it seems that the python debugger will sometimes send multiple lines as a single console update, and in that case the lines will not be merged. In other cases, it seems like a single log may or may not have a newline, making it not equal to the previous message. You can file this against debugpy or the Python extension.
