### ISSUE TITLE
Could you work a solution? "The language server needs at least PHP 7 installed. Version found: 5.6.23"

### ISSUE THREAD

**Issue by rbenitezpagan** [Microsoft/vscode#19854]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|code-gnu-global|austin|0.2.1|
|javadebugger|donjayamanne|0.0.2|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.0.0|
|beautify|HookyQR|0.7.3|
|crane|HvyIndustries|0.2.2|
|composer|ikappas|0.5.0|
|format-indent|Kasik96|1.3.0|
|HTMLHint|mkaufman|0.3.3|
|cpptools|ms-vscode|0.10.0|
|csharp|ms-vscode|1.6.2|
|vscode-icons|robertohuertasm|7.1.2|
|Spell|seanmcbreen|0.9.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by rbenitezpagan** [comment]
I believe VS Code should provide a way of updating the PHP more autonomous. Thanks.

**Comment by bpasero** [comment]
@rbenitezpagan I suggest to discuss this with the author of the PHP extension where this message seems to originate from and then see if VS Code needs to provide something.
