### ISSUE TITLE
Focus Next and Prev Search Result current position lost if the text is edited.

### ISSUE THREAD

**Issue by gregmarr** [Microsoft/vscode#19853]
- VSCode Version: 1.9.0
- OS Version: 10.11.6

Steps to Reproduce:
1. Search for a string using the search pane.
2. Press F4 several times to go to a particular result.
3. Edit the text so it no longer matches the search term, and is thus removed from the results in the search pane.
4. Press F4 to go to the next result.

Expected Result:
The next result is highlighted.  (This is the behavior in Visual Studio.)

Actual Result:
The first result is highlighted.  F4 must be used several times to get back to the desired result.

**Comment by roblourens** [comment]
Doesn't seem to repro anymore.

**Comment by gregmarr** [comment]
Just reproduced in Version 1.11.2 (1.11.2) 6eaebe3b9c70406d67c97779468c324a7a95db0e

**Comment by roblourens** [comment]
Ah I actually do see it. Misread the issue. Same as https://github.com/Microsoft/vscode/issues/20467
