### ISSUE TITLE
Using SnippetString in CompletionItem

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#19859]
I'm working on a language server, and have `vscode-languageserver-types@3.0.3` as dep. However, it doesn't have `SnippetString` and doesn't allow `SnippetString` as part of `CompletionItem.insertText`.

I thought LS servers wouldn't have to have `vscode` as a dev dep -- at least that's what I gathered from the node LS and html LS.

However I was looking at #15573 and it seems Go just depends directly on VSCode: https://github.com/Microsoft/vscode-go/blob/master/src/goSuggest.ts#L187

Two questions:

- Will `SnippetString` be added to `vscode-languageserver-types`?
- Overall, should LS servers import types from `vscode` or `vscode-languageserver-types`?

/cc @dbaeumer @jrieken

**Comment by eriklieben** [comment]
see https://github.com/Microsoft/vscode-languageserver-node/issues/152

**Comment by octref** [comment]
@eriklieben That's fast, thanks!

But I'm still wondering if LS servers should import types from `vscode` or `vscode-languageserver-types`. I see Go just use everything directly from `vscode` namespace -- @ramya-rao-a is there a reason you did it this way instead of using `vscode-languageserver-types`?

**Comment by ramya-rao-a** [comment]
@octref That is because the Go extension doesnt use a language server in the first place. It uses a combination of Go CLI tools to achieve most of the features

**Comment by octref** [comment]
@ramya-rao-a Oh I see it's all based on languages API. Thanks!
