### ISSUE TITLE
Keybindings sync should perform a basic cross-platform translation

### ISSUE THREAD

**Issue by yushiyangk** [microsoft/vscode#198506]
Reiterating #152567, since it was closed without being addressed as a feature request.

It would be good if VS Code could sync keybindings between Windows/Linux and Mac, **and** automatically translate keys using the conventional mapping of Ctrl to Cmd.

The only common exceptions to this that I can think of are Ctrl+Tab and Ctrl+Shift+Tab, which do not change on Mac.

I am aware that `settingsSync.keybindingsPerPlatform` exists, but neither true nor false achieves the above feature request.

**Comment by sandy081** [comment]
We do not auto convert keyboard shortcuts say, changing from CTRL to CMD or vice versa.

Please refer to this issue for OS specific keybindings - https://github.com/microsoft/vscode/issues/8962

**Comment by yushiyangk** [comment]
I know that you do not do that, that is why this is a **feature request**.

As I mentioned, I am aware that I can set OS-specific keybindings. This is a **feature request**.
