### ISSUE TITLE
In Multi diff view action menu get's hide behind the file name 

### ISSUE THREAD

**Issue by abhijit-chikane** [microsoft/vscode#198544]
Right click in the Multi diff view and see the action get's hide behind the file name line as well as the sidebar

//cc @hediet 

![image](https://github.com/microsoft/vscode/assets/50770619/0b379a35-8e96-497d-b836-8caa9d870e9f)

**Comment by hediet** [comment]
Fixed

![Image](https://github.com/microsoft/vscode/assets/2931520/470e36c7-8b7a-4841-8128-0e2b3574b8aa)

**Comment by ulugbekna** [comment]
<img width="2299" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/70f0c159-cff2-4f1e-9c54-7e1e5a61082a">
