### ISSUE TITLE
disable copilot suggestion in single file ( for solving coding problem without cheating)

### ISSUE THREAD

**Issue by jovyan-escher** [microsoft/vscode#198569]
I practice coding problems regularly. Even though many platforms support VS Code keybindings, I still prefer coding in VS Code. Especially when I'm not actually testing, the VS Code debug feature is really helpful.

However, Copilot is too smart. I guess I could disable the Copilot extension temporarily, but currently, I move the cursor frantically when the shadow font suddenly appears.

**Comment by joyceerhl** [comment]
This repo is for issues specific to the code editor. Please file this feature request on https://github.com/community/community/discussions/categories/copilot
