### ISSUE TITLE
Icons for Variables when Debugging

### ISSUE THREAD

**Issue by sabahtalateh** [microsoft/vscode#198586]
Greetings! I'm kindly suggesting adding icons in Variables View (when debugging) like it is now in Visual Studio and IntelliJ. Icon may identify variable type or just visually indicate that it is a variable and not text

VSCode (No Icons)
<img width="188" alt="image" src="https://github.com/microsoft/vscode/assets/4948885/db30cf26-59d3-4c92-86de-b905d9d61408">

Visual Studio (With Icons)
<img width="305" alt="image" src="https://github.com/microsoft/vscode/assets/4948885/e5a9a18d-ca06-44cd-a92a-9669f445a6a9">

IntelliJ (With Icons)
<img width="266" alt="image" src="https://github.com/microsoft/vscode/assets/4948885/d7fcfafb-80f7-4461-835a-a02c236fb4e0">

**Comment by roblourens** [comment]
Is that helpful? In your examples all the varialbes have the same icon. So what's the point?
