### ISSUE TITLE
Markdown cells in jupyter notebooks causing scrolling issues

### ISSUE THREAD

**Issue by luchungi** [microsoft/vscode#198577]
Type: <b>Bug</b>

Adding any markdown cells into a jupyter notebook causes the scrolling to get stuck upon reaching a markdown cell. The first scroll down still works but subsequent scrolls back up gets stuck once it hits a markdown cell.

Removing markdown cells using text editor and reloading resolves the issue completely.

Tried uninstalling jupyter extension (microsoft) but does not resolve the issue. This only happens on the insider edition. The current latest VS Code (non-insider edition) does not have this problem.

VS Code version: Code - Insiders 1.85.0-insider (54b8f6a80aaad7489b75e9293b8d7a1700bed815, 2023-11-17T10:49:40.914Z)
OS version: Windows_NT x64 10.0.22635
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600 6-Core Processor               (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (49.27GB free)|
|Process Argv|--crash-reporter-id 8c1f125c-7b85-4121-8c37-3f0f54919dfb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600 6-Core Processor (12 x 3500)|
|Memory (System)|31.30GB (28.91GB free)|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.16.2
vscode-peacock|joh|4.2.2
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.324.0
remote-wsl|ms-|0.81.8
binary-plist|dni|0.11.3
githistory|don|0.6.20
gitlens|eam|2023.11.1704
themeswitch|Foo|1.0.5
copilot|Git|1.137.556
copilot-chat|Git|0.11.2023111701
vscode-pull-request-github|Git|0.76.1
latex-workshop|Jam|9.15.0
rainbow-csv|mec|3.8.0
vscode-docker|ms-|1.28.0
vscode-dotnet-runtime|ms-|2.0.0
isort|ms-|2023.10.1
pylint|ms-|2023.11.13201006
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
datawrangler|ms-|0.21.1
jupyter|ms-|2023.11.1003211000
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
tensorboard|ms-|2023.10.1002992421
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.16.31
cpptools|ms-|1.19.0
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
cmake|twx|0.0.17
vscode-colorize-plus|YuT|0.12.13

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
2i9eh265:30646982
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30869155
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30859868
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by rebornix** [comment]
Sorry about that, should be fixed via https://github.com/microsoft/vscode/commit/74d6858c83fcd0ff47841f55fda9503f9f0c6998 and be available next week.
