### ISSUE TITLE
Focus Next and Prev Search Result don't wrap around

### ISSUE THREAD

**Issue by gregmarr** [Microsoft/vscode#19852]
- VSCode Version: 1.9.0
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Search for a string in the search pane.
2. Use F4 to go to the next result.
3. Once the last result is reached, the key stops working, instead of wrapping around as in Visual Studio.

The same applies to Shift-F4 to go backwards.  This functionality in VS is incredibly useful to go to the last match in a file.

**Comment by roblourens** [comment]
That makes sense, I can add that
