### ISSUE TITLE
`diffEditorViewModel` breaks when previous `_unchangedRegions` is non-empty

### ISSUE THREAD

**Issue by OfekShilon** [microsoft/vscode#198516]
The direct symptom is in the site `www.compiler-explorer.com`, but the investigation went through `monaco-editor` (which the site uses) and ends up here.

Steps to Reproduce:

1. Navigate to https://godbolt.org/z/dsav96z6P
This shows the "LLVM Opt Pipeline Viewer" (1)  which is a diff pane created by monaco's `createDiffEditor` (2). It's contents change based on the user selection in from the 'passes' list (3).
![image](https://github.com/microsoft/vscode/assets/73080/65c98a47-9a1b-4451-bdbd-b0d678ff6503)

2. To see normal operation in action: click in order the passes "SROAPass" (first one) and "Greedy Register Allocator". Diffs are shown properly:
![image](https://github.com/microsoft/vscode/assets/73080/446c54c6-8193-4519-be26-fdfa83218990)

3. To reproduce the bug, click in order the passes "SROAPass", then "Debug Variable Analysis" (one above Greedy) and finally "Greedy Register Allocator". First, text diffs are not being decorated despite being present:

![image](https://github.com/microsoft/vscode/assets/73080/15931c9e-bee3-44e1-b002-8d03a2c88293)

and second, a console shows the error:
```
lineRange.js:94  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'endLineNumberExclusive')
    at nl.intersectsStrict (lineRange.js:94:45)
    at a (diffEditorViewModel.js:98:50)
    at diffEditorViewModel.js:180:17
    at BV (base.js:76:9)
    at BU.<anonymous> (diffEditorViewModel.js:179:13)
    at Generator.next (<anonymous>)
    at r (diffEditorViewModel.js:17:58)
```

-----------------------

Preliminary investigation directs attention to these lines in `DiffEditorViewModel`'s [updateUnchangedRegions](https://github.com/microsoft/vscode/blob/f3dfca443d6efdf59c9b281cdb652492d8db067a/src/vs/editor/browser/widget/diffEditor/diffEditorViewModel.ts#L94):

```js
        const updateUnchangedRegions = (result, tx, reader) => {
            const newUnchangedRegions = UnchangedRegion.fromDiffs(result.changes, model.original.getLineCount(), model.modified.getLineCount(), this._options.hideUnchangedRegionsMinimumLineCount.read(reader), this._options.hideUnchangedRegionsContextLineCount.read(reader));
            // Transfer state from cur state
            const lastUnchangedRegions = this._unchangedRegions.get();
            const lastUnchangedRegionsOrigRanges = lastUnchangedRegions.originalDecorationIds
                .map(id => model.original.getDecorationRange(id))
                .filter(r => !!r)
                .map(r => LineRange.fromRange(r));

...
            for (const r of newUnchangedRegions) {   
                for (let i = 0; i < lastUnchangedRegions.regions.length; i++) {
                    if (r.originalUnchangedRange.intersectsStrict(lastUnchangedRegionsOrigRanges[i])   <--- attempt to access an empty array
...
                    }
                }
            }
```

In the (not so rare) problematic scenario, `newUnchangedRegions` and `lastUnchangedRegions.regions` are non-empty *but* `lastUnchangedRegionsOrigRanges` is, so the code enters the loop and crashes immediately.

I suspect something broke in @hediet PR #191977, but not sure.

**Comment by OfekShilon** [comment]
A monaco-playground link with a small standalone repro for the problem:
https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#XQAAAAJoAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw10ok-_1uhrp2RzO_KSoj3BnqSCFzt4AfU0xJ0CGYU1vRtgnKPmZzQcQ68ILtjJsSfOJtidapac8gxQKIxncegpZ2ULdDxvd_XPSiNVCchDoIge5jk6s1SWlJHGtnWQqr7L4r_MlNAJ2RzOsdk0zGe0j8TXj8yOvGPVTPTJTA8f3tvAZ_TMpaHmeOJ3xTggSlAUS-56fkH9W5H5tzIOm2S1a7ykHN4qD951XsRmPfdrrXpcQTePkwrf8b_5AwyLMoCEvdMdL8mF9vOFA_SC_blJZQOiu4Ou3FLGhIPmRj-zbDdoAdqYSMrjX9H30Rr_V5d4G_6RootmoxSUSxnj_-hnZM

This creates a diffView and populates both sides with an offending text (specifically, one with non-empty "unchangedRegions"). After two seconds it sets the left pane to the same text as it currently has, but this time the decorations disappear and a console error message as above appears.


Perhaps this tidbit would be helpful:

It seems that upon entering `updateUnchangedRegions`, `this._unchangedRegions._value._originalDecorationIds` contains ids that were already invalidated - i.e., do not appear in `this.model.original._decorations`:
![image](https://github.com/microsoft/vscode/assets/73080/023e942e-6076-4d29-8701-6ef26483c6d9)

And so `.map(id => model.*.getDecorationRange(id))` returns only nulls and the resulting array is empty. My current guess is these decoration-IDs invalidation is too early, and should be moved to after `updateUnchangedRegions`.

**Comment by OfekShilon** [comment]
@hediet  Thank you for the prompt fix!

**Comment by beauxq** [comment]
I saw this problem again today.
```
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.4.0-169-generic snap
```

**Comment by hediet** [comment]
> I saw this problem again today.

Can you please share the output of the dev console? Thanks!
