### ISSUE TITLE
Select HTML tag including inner HTML | FEATURE REQUEST

### ISSUE THREAD

**Issue by unexdesigns** [Microsoft/vscode#19855]
I would love to have a feature where you select a tag, enter a Keyboard Shortcut and the whole HTML element with it's children is selected. Would make for easy HTML element repositioning (especially large elements) in the document.

**Comment by kaiwood** [comment]
Already included, Emmet does this via `Emmet: Balance (inward)` and `Emmet: Balance (outward)`. 

See [this](http://stackoverflow.com/a/40971959/2906632) answer on Stackoverflow for a complete keybinding setup combined with the `Expand Select` and `Shrink Select` (those two do basically the same for selecting inside strings, braces, etc.)

**Comment by aeschli** [comment]
Wow! Thanks @kaiwood, I didn't know that!
