### ISSUE TITLE
Missing settings entries

### ISSUE THREAD

**Issue by mquandalle** [Microsoft/vscode#19857]
Hello,

In the new settings view of VSCode, it seems that I don't have access to all available settings, for instance, here I'm searching for `editor.action.` settings and there is no result matching:

![settings left panel](https://cloud.githubusercontent.com/assets/1730702/22595950/d253fa7e-ea29-11e6-8fed-0cbe69853c75.png)

Similarly on the right panel, the autocompletion tool doesn't suggest `editor.action` settings:

![settings right panel](https://cloud.githubusercontent.com/assets/1730702/22596011/0ac91f56-ea2a-11e6-99dd-8e7b2d58a376.png)

I'm on Linux Ubuntu 16.04

**Comment by chrmarti** [comment]
If you are looking for the keyboard shortcuts, these are under: File > Preferences > Keyboard Shortcuts

**Comment by mquandalle** [comment]
Oh yes... My bad
