### ISSUE TITLE
Front-trimmed search result preview should be ellipsized

### ISSUE THREAD

**Issue by jacekkopecky** [microsoft/vscode#198566]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: macOS 12.6.5

Steps to Reproduce:

1. make a file with a long line of code, e.g.
   ```
   // Test using the latest Insiders build to see if your issue has already been fixed: https://code.visualstudio.com/insiders/
   ```
2. search for something near the end of that line of code, e.g. _"fixed"_
3. observe that search results preview cuts the beginning of the line, e.g. showing only _"your issue has already been fixed: https://code.visualstudio.com/insiders/"_ 
4. make the search pane narrower so it starts ellipsizing the end of the preview, e.g. showing only _"your issue has already been fixed: https://code…"_
6. observe that if you hover over the search result preview, the hover title shows the search result shortened at the start but not at the end where it's ellipsized

This screenshot shows the current behaviour, implying the last search result is on a line starting with `12`.

<img width="1248" alt="Screen Shot 2023-11-17 at 21 25 52" src="https://github.com/microsoft/vscode/assets/807315/4b47b724-0de4-45cd-a421-80107a1b1828">

The cutting at the start can make the preview confusing in circumstances where the first parts of the code line affect the meaning of the matched part (e.g. where it's in a string or in a comment rather than in code). It's confusing because there is no indication that the line is cut at the start.

This can be solved by adding an ellipsis … at the start of the cut preview, and by showing the whole line in the hover title.

This screenshot shows what it should look like:

<img width="1249" alt="Screen Shot 2023-11-17 at 21 23 36" src="https://github.com/microsoft/vscode/assets/807315/ec2392cd-bd3f-4e6d-b0d5-76cfbf24b5db">

PR coming in a few moments.

**Comment by andreamah** [comment]
Verification steps:
1. Create a long multi-word line with a specific word at the end. (ie: `eeeeeee eeeeeee eeeeee eeeeeee eeeeeee eeeeeeee eeeeeee eeeeeee eeeeeeeeeee test`)
2. Search for that word (ie: `test`)
3. Verify that the match for it has a `...` at the beginning.
<img alt="image" src="https://github.com/microsoft/vscode/assets/31675041/8a5b95fb-7e52-4e63-8430-620dab39cc75">
