### ISSUE TITLE
Unable to open untitled:// resources from problems view

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19856]
Steps to Reproduce:

1. have an untitled file with JS mode
2. have code with errors/warnings
3. click on one

=> crash

![image](https://cloud.githubusercontent.com/assets/900690/22596109/91299f62-ea2a-11e6-8eee-8c6a4586678f.png)

Is the resource scheme file but the URI untitled? Looks like it

**Comment by sandy081** [comment]
@mjbvz Looks like `ts` is registered this as a file resource where are `json` is not having any issues.

**Comment by mjbvz** [comment]
@sandy081 Thanks for the investigation. #20073 should fix this
