### ISSUE TITLE
Scrolling in Jupyter notebook leads to crashing of all cells

### ISSUE THREAD

**Issue by Georgewxm** [microsoft/vscode#198642]
Type: <b>Bug</b>

I regularly use Jupyter Notebook for my daily tasks. Today, when I started it, everything appeared normal initially. However, as soon as I attempted to scroll in one of the cells, it became unresponsive. Repeated scrolling attempts yielded no response, and the entire cell vanished unexpectedly. I had to shut down Visual Studio Code, but restarting and even reinstalling the extension did not resolve the issue. Currently, I'm unable to find a permanent solution to this problem.

VS Code version: Code - Insiders 1.85.0-insider (54b8f6a80aaad7489b75e9293b8d7a1700bed815, 2023-11-17T10:49:40.914Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (16.97GB free)|
|Process Argv|--crash-reporter-id 5846b696-4e62-4d0b-bea7-a576080e9ff6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
python-environment-manager|don|1.2.4
copilot|Git|1.137.556
copilot-chat|Git|0.11.2023111701
gc-excelviewer|Gra|4.2.58
latex-workshop|Jam|9.15.0
language-julia|jul|1.60.2
vscode-leetcode|Lee|0.18.1
rainbow-csv|mec|3.8.0
vscode-docker|ms-|1.28.0
vscode-language-pack-zh-hans|MS-|1.84.2023111509
vscode-dotnet-runtime|ms-|2.0.0
vscode-edge-devtools|ms-|2.1.3
black-formatter|ms-|2023.6.0
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
datawrangler|ms-|0.21.1
jupyter|ms-|2023.10.1100000000
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-powertoys|ms-|0.1.0
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.324.0
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
vsliveshare|ms-|1.0.5892
subtitles-editor|pep|1.1.7
r|REd|2.8.2
markdown-preview-enhanced|shd|0.8.10
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30869155
dsvsc013:30777762
dsvsc014:30777825
pythonmpsinfo:30859869
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by rebornix** [comment]
@Georgewxm sorry about the bug, it should be fixed in main and will be available in a couple of hours in Insiders.

**Comment by rebornix** [comment]
This is now fixed in latest Insiders, please update VS Code. Sorry for the inconvenience.
