### ISSUE TITLE
Tab not tabbing any more.

### ISSUE THREAD

**Issue by andriesfc** [microsoft/vscode#198694]
Type: <b>Bug</b>

The tab key no change focus from one place of the UI to another. I removed the key binding for it, and disabled the tab chage focus value in the settings.json file. 

Is there a solution?

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin x64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.87GB free)|
|Process Argv|--crash-reporter-id 103514a8-2c7a-4748-bf43-d9aac5de66ae|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
alt-catppuccin-vsc|doo|2.7.4
kotlin|fwc|0.2.32
vscode-gradle|vsc|3.13.2023110409

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30887143
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016cf:30886111
dsvsc017cf:30886113
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by gjsjohnmurray** [comment]
Do you have a "Tab Moves Focus" panel near the right end of your status bar? If so, try clicking it. Do things start working properly again?

If so I suggest you use Command Palette to see what the keyboard shortcut for the `Toggle Tab Key Moves Focus` command is. Perhaps you accidentally pressed it.

**Comment by andriesfc** [comment]
Hi. I toggled the "Tab Key Move Focus" using the standard key binding. And regardless of whether is toggled on or off, the behaviour is the same: Just move focus. I even deleted my local config, and re-installed it, with the same results.

**Comment by gjsjohnmurray** [comment]
Does the `Start Extension Bisect` command produce a diagnosis?

**Comment by andriesfc** [comment]
It does not. It picks 2 extensions which event when disabled, does not fix the issue.

**Comment by ulugbekna** [comment]
Hi @andriesfc :-)

Thanks for filing this issue! 

1. Could you provide your keybindings.json file contents? (invoke command "Preferences: Open Keyboard Shortcuts (JSON)" to open it)

Could you please try the [following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

1. Run the command "Developer: Toggle Keyboard Shortcuts Troubleshooting" (you can, for example, run it from the Command Palette). 

   This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.

2. Press exactly the keybinding you desire
 
3. Check what VS Code detects 

If you are having trouble understanding the output, please feel free to paste here and we'll be happy to help ☺️

**Comment by andriesfc** [comment]
Hi. Fixed it by finding *all* configuration and files, and delete it completely. After that a new install it worked fine. Thnx.
