### ISSUE TITLE
.deb Linux repos changed Origin and Label fields, triggering update errors

### ISSUE THREAD

**Issue by tpacent** [microsoft/vscode#198658]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.2-1699528352
- OS Version: Ubuntu 23.10

Steps to Reproduce:

0. have `packages.microsoft.com/repos/code` [added](https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions) to a list of apt repos
1. run `sudo apt update` 
2. see warning messages (coming from contents of [InRelease](https://packages.microsoft.com/repos/code/dists/stable/InRelease) file):

```
Get:7 https://packages.microsoft.com/repos/code stable InRelease [3,533 B]
E: Repository 'https://packages.microsoft.com/repos/code stable InRelease' changed its 'Origin' value from 'code stable' to 'Pulp 3'
E: Repository 'https://packages.microsoft.com/repos/code stable InRelease' changed its 'Label' value from 'code stable' to ''
```

Are these changes intentional or the package server has been misconfigured?

**Comment by eddy-geek** [comment]
same here.
is the reference to "Pulp 3" because of some move towards https://pulpproject.org/about-pulp-3/ ?

**Comment by psylence303** [comment]
Same here, I'm reluctant to accept the changes until confirmation

**Comment by jp438-2** [comment]
This change also means users can't update using Ubuntu's inbuilt updating application which just shows an error that says "Failed to download repository information" with no explanation, and tells you to check your internet connection.

The only way to see what has happened is to use `apt update` in the terminal where you can accept the change (which is not something I am happy to do and I have avoided).

**Comment by devcomputer** [comment]
apt remove code

remove sources

go code oss!

https://appimage.github.io/Code_OSS/

**Comment by sztal** [comment]
Yes, I would also appreciate very much some clarification of this chance from the official VS Code team. For now it looks as if this could be a malicious change by someone from outside of the team.

**Comment by SteampunkIslande** [comment]
Same here. Luckily, my package manager refused to connect with the same error (E: Repository 'https://packages.microsoft.com/repos/code stable InRelease' changed its 'Origin' value from 'code stable' to 'Pulp 3')

What I did is I removed this external source repository. Hope this is not some malicious change

**Comment by philclifford** [comment]
This seems to be intermittent: so far in the last 20 mins or so two `apt update`s have succeeded without incident (and manual inspection of InRelease seemed normal) but 4 have exhibited the "Pulp 3"  problem.  For completeness, my configured repo is `../vscode` not `.../code`.

**Comment by philclifford** [comment]
InRelease is changing to and fro:

```
phil@phil-reco-spcc:~$ sudo apt update
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
[...]                                                                                                                          
Get:11 https://packages.microsoft.com/repos/vscode stable InRelease [3,533 B]                                                                                                                                     
[...]
Hit:20 https://esm.ubuntu.com/infra/ubuntu jammy-infra-updates InRelease
E: Repository 'https://packages.microsoft.com/repos/vscode stable InRelease' changed its 'Origin' value from 'vscode stable' to 'Pulp 3'
E: Repository 'https://packages.microsoft.com/repos/vscode stable InRelease' changed its 'Label' value from 'vscode stable' to ''
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N] n
Fetched 18.2 kB in 27s (672 B/s)                                                                                                                                                                                  
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/repos/vscode/dists/stable/InRelease  
E: Some index files failed to download. They have been ignored, or old ones used instead.
phil@phil-reco-spcc:~$ sudo apt update
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
[...]
Get:9 https://packages.microsoft.com/repos/vscode stable InRelease [3,573 B]                                                                                                                                    
[...]
[...]
Get:23 http://security.ubuntu.com/ubuntu jammy-security/main Translation-en [188 kB]
Fetched 1,753 kB in 2s (1,024 kB/s)                              
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
phil@phil-reco-spcc:~$ sudo apt update
Hit:1 http://gb.archive.ubuntu.com/ubuntu jammy InRelease
[...]
Get:12 https://packages.microsoft.com/repos/vscode stable InRelease [3,533 B]                                                                                                                     
[...]
E: Repository 'https://packages.microsoft.com/repos/vscode stable InRelease' changed its 'Origin' value from 'vscode stable' to 'Pulp 3'
E: Repository 'https://packages.microsoft.com/repos/vscode stable InRelease' changed its 'Label' value from 'vscode stable' to ''
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N] n 
Fetched 18.2 kB in 26s (697 B/s)                                                                                                                                                                                  
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/repos/vscode/dists/stable/InRelease  
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by lamenawuer** [comment]
I get the same error, but it seems to be intermittent and random.

**Comment by gorenstein** [comment]
the same here

**Comment by daviddavis** [comment]
Thanks for the bug report. We're working to fix this issue. Updates are being tracked here: https://github.com/microsoft/linux-package-repositories/issues/96

**Comment by daviddavis** [comment]
FYI, this should be fixed now.

**Comment by bamdadsabbagh** [comment]
Fixed on `Debian GNU/Linux 12 (bookworm) x86_64` after running `apt clean`

**Comment by romansh** [comment]
Just run into the bug.

sudo apt-get clean didn't help on Ubuntu 22.04.3 LTS
