### ISSUE TITLE
Markdown preview doesn't scroll preview window

### ISSUE THREAD

**Issue by kiranj321** [Microsoft/vscode#19867]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-svgviewer|cssho|1.3.0|
|vscode-npm-script|eg2|0.1.8|
|Angular2|johnpapa|1.0.2|
|theme-material-theme|jprestidge|1.0.1|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.9.0|
|debugger-for-chrome|msjsdiag|2.5.0|
|vscode-docker|PeterJausovec|0.0.11|
|swaggitor|qnsolutions|0.1.1|
|sass-indented|robinbentley|1.3.0|

---

Steps to Reproduce:

1. Open a markdown file.
2. Ctrl K V to open preview
3. Scroll the md source without clicking on content. 
Preview doesn't scroll. If I scroll with cursor, it scrolls fine.

**Comment by mjbvz** [comment]
Scrolling the markdown editor to scroll the markdown preview is currently being tracked by #19459, but we need some new APIs on the VSCode side to make this happen
