### ISSUE TITLE
Unable to reset Settings Sync machine identity

### ISSUE THREAD

**Issue by ches** [microsoft/vscode#198614]
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.85.0-insider
Commit: 54b8f6a80aaad7489b75e9293b8d7a1700bed815
Date: 2023-11-17T10:50:41.392Z
Electron: 25.9.4
ElectronBuildId: 25127168
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 22.6.0
```

I am using and have always used the Insiders sync service.

This is essentially an echo of #104732, but it was closed as deemed caused by the third-party Settings Sync extension. I have never used that extension, only VS Code's native Settings Sync.

The short summary is just as the subject of that earlier issue: Settings Sync "sees my two computers as one".

What _is_ key in my case is that I used Apple Migration Assistant to copy user data from old to new, but the old machine is still in use. So it's understandable that state was duplicated exactly, and some nudge may be needed to give the new machine a fresh identity.

The problem is that the evident (to me) means of doing that within a user's recourse—turning Settings Sync off and on, "Clear Data in Cloud…"—do not seem resolve this.

For Migration Assistant and other similar use cases, it would be great if there is a command or similar to reset the identity and sync state of a single machine, ideally without the need to delete all cloud data history and enable sync again on all other machines.

Steps to Reproduce:

1. Use Migration Assistant or otherwise copy the entire `~/Library/Application Support/Code` / `Code - Insiders` directory to another Mac. (Possibly other local state/cache locations?)
2. Run Code on both and observe that the "Synced Machines" view shows one entry with the original machine name. This may lead to unexpected syncing behavior (in my case I had a third machine as well, with a proper identity of its own).
3. Use the "Clear Data in Cloud…" function from either of the hosts with the same identity.
4. Re-enable Settings Sync on both
5. Find that Settings Sync remote data has started fresh, but "Synced Machines" still shows only one

I've tried the workaround from https://github.com/microsoft/vscode/issues/104732#issuecomment-703081384 without effect. I do unsurprisingly have `machineid` files with the same content, not sure if that file is vestigial now because removing it does not seem to matter and it is not regenerated at all.

**Comment by sandy081** [comment]
You can perform following steps to reset

- Turn off Settings Sync on the machine
- Shut down VS Code
- Run command `Developer: Open User Data Folder`
- Delete `machineid` file
- Open VS Code and turn on settings sync again
