### ISSUE TITLE
You don't have an extension for debugging X

### ISSUE THREAD

**Issue by Tarotis** [microsoft/vscode#198667]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.84.2
- OS Version: Fedora39

With files for which I do not have a debugger installed (esp. .log and .tex), VScode prompts an error message whether it should search for a debugger. I tried deactivating the LaTeX workshop extension, and then the problem started popping up for the -log-files as well. The error message looks as following: 

![Image](https://github.com/microsoft/vscode/assets/73231722/3add70f6-cd6d-4d0e-a6b3-12b1dd9de4ea)

When I click on "Cancel", the error message immediately reappears - which is the main problem. This makes working in VScode currently impossible for me, as the message keeps blocking any other window/menu panel.

**Comment by roblourens** [comment]
I don't follow, what are you doing when this error appears? 

If you aren't trying to start debugging, is it possible that some extension is trying to? You could try running "Start Extension Bisect"
