### ISSUE TITLE
Glyph Widgets Operate On View Positions, Not Model Positions

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#198674]
[Monaco Editor Repro](https://microsoft.github.io/monaco-editor/playground.html?source=v0.45.0-dev-20231117#XQAAAAIDBgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw9vveOAmRHEYw2pVmocjg2JTLAYRSDUpZuOkFaezs6BukOHFHluuzVCMzkZPlBGNrDEdrZWFK_vwi_52sicvusS-Tv1CK5wcEYboEZoVdvCdN9JFSgiUGHax3DQyEvYDtrqAb8-T30VeamGUqnA18wuyfa0Auy28KfjtZDNAuGJLGH-M7AyY_mTF9mi6Iib91HnxlBBYui5aULiXN8DN8ubVR7SXpxhhatnff9KHaOGrQN8spWbnkm3NYtnbC9ScoGBjXikdvliKdVzHec8gzFe6BougNaPjtJvYEdCXPz6nHGw5zTugxGCh-Ssq5u71mTs2OJ3gbDdWZE6FUzX8rt4MuqBNh2h9OH8i0eWZXChGWXnPdBk_P-DnX70a-ovRVTjRAiZmh1jDk2aRF0Apc2kNJmhwpTnKUGQPKpwN-iSAguYxlYjhF81qvaeCBPsuyTcXzEde_AghAjeEHtLhX4bfIPr-rzSQh_4xzG5a4bw3v9EY-yNybuAup-nCznpzezxjt7kuEzgq9hjCLvgI8OmMZr0J2TOODTNPMAvAVB9EbBo2NfkbMalpLUrlzAMOWIyNYoPPoYT1YNZ2_vnet2ea7Sis-kseBAXCqzYFpGqgD7D7Ssf2jUuNomy0uAK2KkgUJNNxNwwoeYEiKILkHZbv2d4aZjE0V-iSIlZtPC5e9yNuysZ3oDFkFQyEIe_geeYXHS-GECV6gl8mKMuLmCQ0dQgTiY9VWVaWubYCrX5wF59Pw3Nxe_9Hl-4w)

As you can see, the positioning does not folding into account:

![Image](https://github.com/microsoft/vscode/assets/2931520/0c18f2e0-0c46-4b01-a6a2-81998248e22f)

This breaks the revert arrows in the diff editor, as I adopted glyph widgets for them.

**Comment by joyceerhl** [comment]
We're deciding whether to render widgets based on `ctx.visibleRange.startLineNumber` and `endLineNumber` here https://github.com/microsoft/vscode/blob/620340c8637cb9a90ca3bd4a5fafa8f60ba0ae49/src/vs/editor/browser/viewParts/glyphMargin/glyphMargin.ts#L276-L281 but these are the viewport and not the model line numbers
