### ISSUE TITLE
keybinding when clause context for Developer Tools open

### ISSUE THREAD

**Issue by avertx** [microsoft/vscode#198610]
This is to disable keybindings (i.e. for editors, like CMD+\ which overlaps with Developer Tools debugger) when using Developer Tools (debugger).  A chord for developer tools isn't a viable option, since the debugger often needs to be "continued" in rapid succession.

or document it on 
[https://code.visualstudio.com/api/references/when-clause-contexts#conditional-operators]()

**Comment by roblourens** [comment]
Are you talking about opening the Developer Tools on the vscode window? Why are you using that/
