### ISSUE TITLE
Extension Managar hangs a lot

### ISSUE THREAD

**Issue by skanda890** [microsoft/vscode#198671]
Extension Manager hangs, a lot.

### System Information

Windows Build No: 10.0.22621.2715

Other Software: OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

System Information:
Physical Memory: 11.89GB (1.28GB free)
Processor Architecture: x64

Extension Info: Python - Profiling and Python - C++ Project debugging support or something like that.

### Additional Information

I tried without the extensions but it still hangs.

### An image for reference

![image](https://github.com/microsoft/vscode/assets/99239826/a38b446a-5f6f-4184-bc25-74dc76bc1d66)

**Comment by alefragnani** [comment]
Hi @skanda890 ,

Your issue is related to Visual Studio, not Visual Studio Code. I think the best location to find info and/or report issues for Visual Studio would be at https://visualstudio.microsoft.com/vs/support/?tab=support

Hope this helps

/outOfScope
