### ISSUE TITLE
Request: Shortcut to send the current line to the terminal

### ISSUE THREAD

**Issue by tomtom** [Microsoft/vscode#19863]
Some other apps handle "send to console"-like features like this:

1. if no text is selected, send the current line (and maybe move the cursor to the next line)
2. if some text is selected, send that text

VSCode currently provides a way to achieve 2 but not (easily) 1 or 1+2 depending on the current selection.

VSCode should provide at least some command to send the current line (and move to the next line).

**Comment by Tyriar** [comment]
Related https://github.com/Microsoft/vscode/issues/19375

**Comment by lbollar** [comment]
This tends to be the default behavior in IDEs like Rstudio and Pycharm and I think is generally pretty popular in the data science community. I was actually assuming this would be the default behavior of execute in terminal with no selected text, but then found out it wasn't.

I can say this tends to be a pretty great way to work with a script alongside a terminal. Personally, if I want to run an entire script's worth of code, I tend to expect that I will either need to do a select all and execute or there will be a command specifically for that task.

**Comment by Tyriar** [comment]
I've changed the behavior to send the active line, this should be available in tomorrow's Insiders build.
