### ISSUE TITLE
Tearable Tabs

### ISSUE THREAD

**Issue by jcampbell05** [Microsoft/vscode#19861]
I would love for the tabs in VSCode to work like google chrome with the ability to tear them off and also for you to move them to another window.

**Comment by SidIcarus** [comment]
You can currently tear them off and move them to another _already_ open window.  
What I believe you mean is, tear them off and on _drop_ have it create a new window. Yes?

**Comment by patrick-collins-429** [comment]
I agree with this, just like how in Visual Studio you can move an open tab to its own window, but it is still part of the project you pulled it from. If you move an open file in vscode to its own window it isn;t a part of that project anymore. This feature would be super helpful for use across multiple monitors and desktops

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8171
