### ISSUE TITLE
Unable to diff

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#1986]
Not sure who's working on this @joaomoreno @bpasero @jrieken 

In selfhost, sometimes it works, but oftentimes I hit this:

![image](https://cloud.githubusercontent.com/assets/5047891/12294471/059724ac-b9fb-11e5-9e4b-5b51a8652910.png)

**Comment by joaomoreno** [comment]
I just saw this 
![image](https://cloud.githubusercontent.com/assets/22350/12296173/4e2b0368-ba06-11e5-80ea-deb3bd5648ab.png)

**Comment by bpasero** [comment]
@jrieken any chance your changes with the "weak" module cause code editor models to get disposed? My understanding is that only models with a scheme that are registered to the content providers would get auto disposed.

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/12296396/add8dece-ba07-11e5-96d0-921a0c8e4b6b.png)

![image](https://cloud.githubusercontent.com/assets/22350/12296415/cca04b1c-ba07-11e5-85db-6b5ae625382b.png)

**Comment by bpasero** [comment]
I fired new builds for Win and Mac.

**Comment by jrieken** [comment]
thanks

**Comment by aeschli** [comment]
Verified by opening product.json  via quick open.
