### ISSUE TITLE
`ignoreIfExists` flag for `CreateFile` fails if file already exists

### ISSUE THREAD

**Issue by EhabY** [microsoft/vscode#198659]
Trying to create an already existing file using the option `ignoreIfExists` fails with the error:
> [warning] IGNORING workspace edit: Error: Unable to create file '<URI>' that already exists when overwrite flag is not set.

It seems this flag is useless as turning it on or off has no effect on `applyEdit`.

See the following reproducer:

```javascript
const uri = vscode.workspace.workspaceFolders?.[0].uri;
if(uri === undefined) {
	return;
}

const wse = new vscode.WorkspaceEdit();
const fileUri =  vscode.Uri.joinPath(uri, "my file.txt");
wse.createFile(fileUri, { overwrite: false, ignoreIfExists: true });
wse.insert(fileUri, new vscode.Position(0, 0), "Hello" + (count++));
await vscode.workspace.applyEdit(wse);
```

If you run this command twice it will fail because it cannot "create" an already existing file even though `ignoreIfExists` is `true`.

Could be related to https://github.com/Microsoft/vscode/issues/56986, and I also do not have auto-save on.

**Comment by jrieken** [comment]
I understand the confusion but this is by design because we way `overwrite` wins over `ignoreIfExists`. So, the former beats the latter and is stronger. For your case only `ignoreIfExists` should be set. A better API might have been an enum that doesn't allow for this confusing combination

**Comment by EhabY** [comment]
I was not aware setting  `overwrite` to false will render `ignoreIfExists` useless.

> When `overwrite` and `ignoreIfExists` are both set `overwrite` wins

I think I see the confusion now, "set" here means that the value is present and not "set to true" so `{overwrite: false}` ignores the flag `ignoreIfExists`. It doesn't help that TypeScripts treats them all as falsy 😩

**Comment by jrieken** [comment]
I was also confused, had already made the changes, but some failing test brought me back to reality.
