### ISSUE TITLE
TypeScript lnaguage services died unexpectedly 5 times in the last 5 minutes

### ISSUE THREAD

**Issue by aaron-nls** [Microsoft/vscode#19860]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|php-debug|felixfbecker|1.9.7|
|sass-indented|robinbentley|1.1.0|
|language-stylus|sysoev|1.6.0|

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@aaron-nls any more information about your setup and workspace?

**Comment by faraoman** [comment]
Hi! In my case it was enough create a new folder (myTestApp), create a subdirectory named app and inside this, create a new file called main.js. After I opened the file, I notice the errors in object. I had to rename the folder 'typescript' into "typescript_" located in 'C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions' to resolve temporarily this issue.
I hoper I have helped

**Comment by mjbvz** [comment]
@faraoman / @aaron-nls  Do you happen to be opening a folder stored on sharepoint or some other network share?

**Comment by faraoman** [comment]
@mjbvz Nothing of this. I only created a folder to desktop with the described message above. No SharePoint or network share, only folders stored on hdd or external hdd.  Can be the non installation of Typescript globally? In another machine (Windows) than I use to develop, I notice than this issue in not raised.

**Comment by mjbvz** [comment]
@faraoman What is the error message that you are seeing? Does it mention not being able to location some `typescript` file?

**Comment by faraoman** [comment]
@mjbvz After renaming the folder (typescript) described above, I gave this messages:
- [Warn] The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.
- [Warn] The path C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib doesn't point to a valid tsserver install. Falling back to bundled TypeScript version.
- [Error] TypeScript language server couldn't be started. Error message is: 1

**Comment by mjbvz** [comment]
@faraoman Please check the `C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib` path. There should be a `tsserver.js` file there. We've seen a few reports of over enthusiastic anti-virus softer deleting these files however.

If the file is missing, you can [use a custom typescript install with `typescript.tsdk`](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). You can also reinstall vscode to restore the files. Be sure to exclude the typescript directory from antivirus to prevent this from happening again. Our official downloads ship the standard npm typescript package
