### ISSUE TITLE
Module Typings won't get picked up.

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#19869]
- VSCode Version: 1.9.0
- OS Version: Win10x64
- npm Version: 4.1.1

Steps to Reproduce:

1. npm i [upath@0.2.0](/anodynos/upath)
2. import it ``upath = require('upath')``
3. try to use it and witness no module members present in suggestions

![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2017-02/Code_2017-02-03_20-01-50.png)

upath isn't present in DefinitelyTyped. It only has local typing: [package.json: "types": "./upath.d.ts"](/anodynos/upath/blob/master/package.json#L32). However post install this line transforms (in the local package.json) into

```
  "typescript": {
    "definition": "upath.d.ts"
  },
```
which apparently VSCode doesn't understand.

I don't know why does it happen. I have my own module, that I host on a private git server that I install via npm's git+ssh support and it doesn't change ``"types"`` into ``"typescript.definition"`` and in this case VSCode does pick up my local typings alright.

**Comment by mjbvz** [comment]
I believe an old version of `upath` is published to npm: https://github.com/anodynos/upath/commit/259198793a675866fd8c0e2a63b847e5ea53d16a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

The `typescript:definition` field is not supported. The correct way is to use `"types"`: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html


Please try following up with upath on this. I see you already opened an issue https://github.com/anodynos/upath/issues/6

Thanks

**Comment by Spown** [comment]
>>  I see you already opened an issue

yeah, I was running between the repos not knowing who to blame... Thanks for clearing this one out.
