### ISSUE TITLE
GitHub Copilot Chat

### ISSUE THREAD

**Issue by DipsFrontJim** [microsoft/vscode#198657]
Type: <b>Bug</b>

When signing in, CoPilot chat icon disappears from the activity bar. Can't get it to work. VS code upgraded to latest version. Copilot uninstalled and installed again. Also tried pre-release version of Copilot, but still the same problem.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.52GB (9.84GB free)|
|Process Argv|--crash-reporter-id 2a7f8d63-fd15-40f4-93e7-f3c7f20b59de|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|17.0.2
vscode-firefox-debug|fir|2.9.10
copilot|Git|1.137.0
copilot-chat|Git|0.10.1
todo-tree|Gru|0.0.226
vscode-drawio|hed|1.6.6
vscode-docker|ms-|1.28.0
csharp|ms-|2.10.28
vscode-dotnet-runtime|ms-|2.0.0
remote-containers|ms-|0.321.0
js-debug-nightly|ms-|2023.11.1317
docker-compose|p1c|0.5.1
preview-vscode|sea|2.2.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30880073
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30886110
dsvsc017cf:30886113
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by gjsjohnmurray** [comment]
Presumably you have an active GitHub Copilot subscription?

**Comment by DipsFrontJim** [comment]
I do 😊 Registered on Jim (DipsFrontJim), Organization DIPS Front

Vennlig hilsen
Jim Johannesson
Utvikler
DIPS Front AS
Mobil +47 995 79 982


Fra: John Murray ***@***.***>
Sendt: mandag 20. november 2023 09:58
Til: microsoft/vscode ***@***.***>
Kopi: Jim Johannesson ***@***.***>; Author ***@***.***>
Emne: Re: [microsoft/vscode] GitHub Copilot Chat (Issue #198657)


Presumably you have an active GitHub Copilot subscription?

**Comment by DipsFrontJim** [comment]
I just want to add that I can't get it to work in "Visual Studio Enterprise 2022 (64-bit) - Version 17.6.6" either. When trying to start a chat, I get a conversations error saying "[Conversations Error] [CopilotClient] unauthorized: chat not enabled for IDE token"

**Comment by DipsFrontJim** [comment]
I'm closing this issue. Our it guys didn't enable the chat at enterprise level. It's ok know.
