### ISSUE TITLE
Broken link to Slack invitation 

### ISSUE THREAD

**Issue by hickford** [microsoft/vscode#198602]
https://github.com/microsoft/vscode/wiki/Feedback-Channels#slack links to https://aka.ms/vscode-dev-community

> This link is no longer active. To join this workspace, you’ll need to ask the person who originally invited you for a new link.

**Comment by gjsjohnmurray** [comment]
The dead link also appears on @digitarald's welcome post at https://github.com/microsoft/vscode-discussions/discussions/5

**Comment by isidorn** [comment]
Thanks for letting us know. I have just updated both places.

**Comment by hickford** [comment]
@isidorn What's the new link?

**Comment by isidorn** [comment]
@hickford I think that link should just work. I think it works without an invite.
@eamodio can confirm

**Comment by eamodio** [comment]
@hickford @isidorn Thanks for the ping -- I updated the invite link. Gotta love the "Never expires" Slack invite links that silently expire.

**Comment by isidorn** [comment]
Hehe, thanks Eric!
