### ISSUE TITLE
Sixel support does not work on Windows

### ISSUE THREAD

**Issue by utybo** [microsoft/vscode#198622]
Type: <b>Bug</b>

With the following settings:

- `Terminal > Integrated: Enable Images` enabled
- `Integrated: Gpu Acceleration` set to `on`
- `Terminal > Integrated: Windows Enable Conpty` set to `on` (default)

I can't seem to get images displayed correctly in the integrated terminal. Via pwsh, trying `cat snake.six` (the one from libsixel, downloaded from GitHub) only prints a blank line. Here are commands I've tried: none of them print any image:

- In pwsh, `cat <a sixel image downloaded>`
- In WSL, `img2sixel <some PNG>` and ` curl -s https://raw.githubusercontent.com/saitoha/libsixel/master/images/snake.six && echo`

Did I do something wrong? How do I make Sixel support work? I couldn't find any information on Windows while digging in a few places.

NB: Tabby, which also uses xterm.js, claim that Sixel support straight up does not work on Windows because of ConPTY (https://github.com/Eugeny/tabby/issues/7063), while the help for the Enable Images option says that it _should_ work on Windows

![image](https://github.com/microsoft/vscode/assets/5175705/10f3fd63-a213-41b6-a888-2fb7d45758fb)

### Screenshots

![image](https://github.com/microsoft/vscode/assets/5175705/65a2ac46-65c7-41fb-b4b1-67f6a01844ae)

![image](https://github.com/microsoft/vscode/assets/5175705/35ccf2c7-661b-40dc-8175-5432ed2eedf2)

### Everything else

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor              (12 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (18.39GB free)|
|Process Argv|--disable-extensions --crash-reporter-id e9c2325f-b28a-415b-9f99-a36273b50ae8|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30887144
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss2:30886141
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016cf:30886111
dsvsc017cf:30886113
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by Tyriar** [comment]
I believe support for this is coming soon in Windows Terminal which means we will get it soon as we're finally about to start shipping a newer version of conpty https://github.com/microsoft/vscode/issues/224488

**Comment by Tyriar** [comment]
To verify check the setting description for `enableImages` and `windowsUseConptyDll`.
