### ISSUE TITLE
My code space is hanging

### ISSUE THREAD

**Issue by sylviaadoyo77** [microsoft/vscode#198661]
my codespace is hanging hence i cant comfortably use it. The outline is not appearing and i cant use and commands . Please help

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by sandy081** [comment]
Please file the issue against the github codespaces.
