### ISSUE TITLE
Integration tests crash

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#198679]
[17f69bb8-3cfb-4f77-9c68-29ddef3b70c6.dmp.zip](https://github.com/microsoft/vscode/files/13415083/17f69bb8-3cfb-4f77-9c68-29ddef3b70c6.dmp.zip)

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=244996&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by hediet** [comment]
Also: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=245116&view=logs&j=0304f796-6596-5b42-8573-3d5da85bc4a5&t=00744841-0714-5307-20a7-5948355aa3d4

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/192119
