### ISSUE TITLE
Visual Glitches

### ISSUE THREAD

**Issue by sunlighthater31** [microsoft/vscode#198613]
Type: <b>Performance Issue</b>

Not much to say, simply visual glitches in vscode. In the menu, the editor, any other window, all of them have the same glitches, as if im lagging in a video game, the code i type flashes somewhere else on the screen, or there are weird pixels all over the screen etc etc. How do i fix it please help. It almost feels like my graphics card is broken but i dont experience anything similar in any other app, just in vscode. So my card should be fine. But it does act as if it isn't when i use vscode. Its literally happening as im typing this, the text flickers. Please help.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes: Restricted

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13600KF (20 x 3494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (21.24GB free)|
|Process Argv|--crash-reporter-id d072dc5d-ca63-46cf-abcd-1a2de15c1776|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   110	 18304	code main
    0	    29	  3600	   crashpad-handler
    0	    91	  4868	window [2] (Issue Reporter)
    0	    77	  7664	fileWatcher [1]
    0	    41	  9380	   utility-network-service
    0	   103	 13064	   gpu-process
    0	   149	 13788	extensionHost [1]
    0	    87	  7576	     electron-nodejs ("C:\Users\Levan\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Levan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=13788)
    0	   225	 15244	window [1] (PersistedSettings.json - Visual Studio Code)
    0	   105	 16564	shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|10.1.0
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
remote-wsl|ms-|0.81.8

(16 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30880073
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016cf:30886111
dsvsc017:30886112
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by mikajed** [comment]
Same here on Linux.

Arch Linux Kernel Version:  6.6.1-arch1-1
GNOME 45.1
Wayland
NVIDIA GeForce GTX 1660 - Driver Version: 545.29.02
AMD Ryzen™ 5 2600 × 12

**Comment by IllusionMH** [comment]
Screenshots/recordings might be helpful.

Have you tried to launch VS Code with `--disable-gpu` flag?

**Comment by mikajed** [comment]
> Screenshots/recordings might be helpful.
> 
> Have you tried to launch VS Code with `--disable-gpu` flag?

Screnshots won't help here and i can't record right now. 

The thing is Code - OSS works perfectly fine on X11 but on Wayland it is not that good.

**Comment by ChrisLauinger77** [comment]
> > code --disable-gpu --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations seems to work though in 1.84.2 code-insiders from today does not need the --disable-gpu
> 
> I tried it with `--enable-features=UseOzonePlatform --ozone-platform=wayland`
> 
> Fixed everything for me on Arch Linux + GNOME + Wayland on Nvidia.

I have amd GFX

**Comment by deepak1556** [comment]
Closing as resolved based on the above comments
