### ISSUE TITLE
Show SCM incoming/outgoing as view?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#198697]
In the scm view, I'd expect `incoming/outgoing` to be its own view instead of a section in an existing view

The main reason for this is that I'd expect to be able to right click on the `Incoming/outgoing` title to hide this view

**Comment by lszomoru** [comment]
Thanks for the feedback. There have been multiple iterations of this, and initially we did have this information in a separate view, but there have been several downside of that approach:
1. Views come with a cost. Have to be discovered, opened, closed, resized. 
2. With a separate view, it would have made sense to move the "Sync Changes" button to this new view which resulted in some confusion as the button was not present in the main Source Control view any more.

As far as hiding this information, you can use the following settings:
* `scm.showIncomingChanges = never`
* `scm.showOutgoingChanges = never`

**Comment by mjbvz** [comment]
@lszomoru Thanks for the background. That makes sense but I think we could help users discover how to hide this section. Some ideas:

- Add a right click context menu on the `Incoming/Outgoing`
- Add a option in the SCM `...` menu that shows/hides the incoming/outgoing section

That would address the main reason I wanted a separate view

**Comment by lszomoru** [comment]
@mjbvz, thanks for the feedback. I will explore those options.
