### ISSUE TITLE
Seletores de CSS3 não funcionam no vscode.

### ISSUE THREAD

**Issue by RenanHuben** [microsoft/vscode#198621]
Quando estava configurando a página style no CSS3, seletores pararam de funcionar. Quando adiciono um novo ícone para ser editado, ele não reconhece seletores como background-color ou padding.

**Comment by aeschli** [comment]
Please provide a small sample code, and detailed steps. What do you see, what do you expect.

**Comment by RenanHuben** [comment]
![printcerto](https://github.com/microsoft/vscode/assets/149059506/473bc018-c0a2-4f6a-9b81-7ae4a797d7b4)

![printcerto02](https://github.com/microsoft/vscode/assets/149059506/c08d2d88-f401-4975-b0dd-5168c366e19e)

Consegue abrir esses prints?

**Comment by RenanHuben** [comment]
> Quando estava configurando a página style no CSS3, seletores pararam de funcionar. Quando adiciono um novo ícone para ser editado, ele não reconhece seletores como background-color ou padding.
