### ISSUE TITLE
Aux window: Unable to switch to first editor group from new window

### ISSUE THREAD

**Issue by msukkari** [microsoft/vscode#198607]
Type: <b>Bug</b>

First of all, thank you for adding floating editor windows! Super useful feature that has already improved my productivity using VS code.

I'm experiencing a weird issue where I am unable to navigate to the first editor group (located in my original window) from a newly opened window. I am able to navigate to any other editor group, but just not the first one.

Steps to repro:
- Open vs code window with two editor groups (this is the "original window")
- Open new vscode window
- From the new window, press ctrl + 1 (workbench.action.focusFirstEditorGroup) to try to go to the first editor group in the original window
- Observe that nothing happens (expected to change focus to first editor group in the original window)
- From the new window, press ctrl + 2 (workbench.action.focusSecondEditorGroup) and observe that you can change focus to the second editor group as expected

Current workaround if I want to change focus to the first editor group from the new window is I do ctrl + 2 to go to the second editor group, and then I can press ctrl + 1 to focus on the first editor group. If I'm in the original window I have no issue switching between the first and any other editor group in that window

VS Code version: Code - Insiders 1.85.0-insider (54b8f6a80aaad7489b75e9293b8d7a1700bed815, 2023-11-17T10:49:40.914Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.0-1026-aws

<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.324.0
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
vim|vsc|1.27.0
copilot|Git|1.137.556
copilot-chat|Git|0.11.2023111701
autopep8|ms-|2023.9.13201008
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
2i9eh265:30646982
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
synctok:30869157
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30859868
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by bpasero** [comment]
Thanks, good catch. Fixing this case is relatively easy, but there are other navigational commands across editor groups that will need special care for when multiple windows are opened: https://github.com/microsoft/vscode/issues/198651
