### ISSUE TITLE
[WelcomeUX] Add openRecentFolder telemetry

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19865]

**Comment by joaomoreno** [comment]
After a Standup discussion, I decided to move this out of the recovery since this is not a fix.

@chrmarti I've created a reverse commit: 3e400cc

**Comment by chrmarti** [comment]
@joaomoreno Telemetry is essential to the evaluation of the Welcome UX. Without this particular change we don't know if the Recent section is worth its cost. That is why I have put it in. I consider it a fix.
