### ISSUE TITLE
Markdown document outline view interaction logic error. . .

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#198620]
Markdown document outline view interaction logic error. . .

Please see the detailed performance process:

https://github.com/microsoft/vscode/assets/54253524/631dcf0d-d5a7-4c34-8ab2-6a050903b7e0

Windows 10 19044
VSCode 1.84.2

**Comment by zhouxinghong** [comment]
Hopefully next version will fix it, thank you very much!

**Comment by mjbvz** [comment]
This is expected as previews cannot provide document outlines. Related to #97095
