### ISSUE TITLE
Aux window: switching focus between floating window sometimes doesn't change keyboard focus

### ISSUE THREAD

**Issue by msukkari** [microsoft/vscode#198797]
Type: <b>Bug</b>

This happens randomly when I'm switching between the main window and a floating window (around ~10% repro rate). 

Repro steps:
- open main vs code window
- open a new floating window
- switch from one to another
- observe that it appears that focus has changed to the new window (the cursor becomes highlighted), but when you attempt to interact with the editor group (ex. down arrow to move down in the file) the focus is actually still in the old editor group 

Current workaround is just to press the keyboard shortcut to switch to the other window again. Seems to only happen when switching from the main window to the floating window

VS Code version: Code - Insiders 1.85.0-insider (da5ab29656a9f0bef63602fbce10968a7f4db2b5, 2023-11-20T18:53:26.158Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.0-1026-aws

<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.324.0
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
vim|vsc|1.27.0
copilot|Git|1.138.0
copilot-chat|Git|0.11.2023112102
autopep8|ms-|2023.9.13201008
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
jupyter|ms-|2023.11.1003211000
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
2i9eh265:30646982
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
synctok:30869157
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30859868
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by bpasero** [comment]
How do you switch?

**Comment by bpasero** [comment]
Does the window indicate focus? We end up calling an Electron method to focus the other window in order to bring it to the front, so it would signal this back with a different color in the title.

Without focus:

<img width="803" alt="image" src="https://github.com/microsoft/vscode/assets/900690/40d58f22-cdac-4887-83d1-ba8f297f2317">


With focus:

<img width="819" alt="image" src="https://github.com/microsoft/vscode/assets/900690/896db5ef-3953-4740-80c7-811e90c7a63c">

**Comment by CalvinWilkinson** [comment]
I personally tried to reproduce the issue but I cannot.  Everything seems to work fine for me.

**Comment by msukkari** [comment]
I've tried to repro this morning with no luck. It happened very infrequently, so will try to notice if the window indicates focus the next time it happens. The cursor would indicate that it was focused on the other window though

Another weird behavior I've hit while trying to repro this is that the terminal window sometimes gets minimized when switching between the main view and floating view. Created a new issue for this #198870

**Comment by bpasero** [comment]
Lets close and see if others can repro. There is an active issue with focus tracking of lists: https://github.com/microsoft/vscode/issues/199729
