### ISSUE TITLE
Ctrl+click on function not working (PHP)

### ISSUE THREAD

**Issue by php4fan** [microsoft/vscode#198754]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Open a PHP file
2. Click on a function name in a function call

Expected behavior:
should go to the function definition

Observed behavior:
does nothing.

As far as I understand PHP support is built in (otherwise the syntax wouldn't be highlighted, right?) so I don't think I need to install any extension for this to work.

**Comment by roblourens** [comment]
You will need an extension for language features like go-to-definition. Out of the box there is only very basic PHP support.
