### ISSUE TITLE
Add a callback function for the Accept button of inline suggestion toolbar

### ISSUE THREAD

**Issue by gugeonmo** [microsoft/vscode#198721]
### Inline Suggestion Toolbar
<img src="https://code.visualstudio.com/assets/updates/1_75/inline-completions-hover.gif" alt="drawing" width="600"/>

### Current Feature
https://github.com/microsoft/vscode/blob/620340c8637cb9a90ca3bd4a5fafa8f60ba0ae49/src/vscode-dts/vscode.proposed.inlineCompletionsAdditions.d.ts#L42-L56

When we click "Accept Word" of the inline suggestion toolbar,
the function `handleDidPartiallyAcceptCompletionItem` is called
so that we can handle the event for partially accepted suggestion.

For the "Accept" button, however, we don't have a corresponding function.

### New Feature
Can we add a function that is called when an inline completion item was fully accepted by the "Accept" button of the inline suggestion toolbar?

The function would look like as follows:
```typescript
/**
* Is called when an inline completion item was fully accepted.
* @param completionItem The completion item that was shown.
*/
handleDidFullyAcceptCompletionItem?(completionItem: InlineCompletionItem): void;
```

**Comment by hediet** [comment]
You can set a command which is then called.

**Comment by gugeonmo** [comment]
@hediet Thank you for replying!

I am not sure if I understood your answer correctly.
Does setting a command mean writing a function body as follows?
```typescript
handleDidPartiallyAcceptCompletionItem(completionItem: vscode.InlineCompletionItem, acceptedLength: number): void {
	console.log('handleDidPartiallyAcceptCompletionItem');
},
```

Then, how can I add a command for "full" accept event? (i.e., event for the Accept button was clicked)

**Comment by hediet** [comment]
there is a command propert yon the inline completion item itself

**Comment by gugeonmo** [comment]
@hediet I see. Thank you for the answer.

For those who need explanation, here is the main part of the code for handling the accept event using the property on the inline completion item.

```typescript
export function activate(context: vscode.ExtensionContext) {
  function handleAccept() {
    console.log("Accepted");
  }
  vscode.commands.registerCommand('accept.command1', handleAccept);
  const provider: vscode.InlineCompletionItemProvider = {
    async provideInlineCompletionItems(document, position, context, token) {
      const result: vscode.InlineCompletionList = {
        items: [],
        commands: [],
      };
      // TODO: make suggestion text, position_range, and completeBracketPairs
      result.items.push({
        insertText: text,
        range: position_range,
        completeBracketPairs,
        command: {command: 'accept.command1', title: 'my title'},
      });
     return result
  }
};
```

**Comment by hediet** [comment]
dont forget to unregister your temporary commands!
