### ISSUE TITLE
Project that runs in VS Mac doesn't run in VS Code on macOS

### ISSUE THREAD

**Issue by mrlife** [microsoft/vscode#198777]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:57.054Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
- OS Version: macOS 13.6 (22G120)

I develop on macOS and deploy to Windows as a Windows service. I'm using the C# Dev Kit.

Steps to Reproduce:

1. Add this to .csproj on macOS: `<DefaultAppHostRuntimeIdentifier>win-x64</DefaultAppHostRuntimeIdentifier>`
2. Debug project and notice that it doesn't start and presents this error:
> The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[29491] AlumniAdmissionsReport.exe' has exited with code 1 (0x1).

**Comment by roblourens** [comment]
Please file this against the C# dev kit
