### ISSUE TITLE
testhost-8.0.runtimeconfig.json missing from .Net 8

### ISSUE THREAD

**Issue by wgrs** [microsoft/vscode#198748]
Type: <b>Bug</b>

testhost-8.0.runtimeconfig.json is missing from .Net 8

Testhost process for source(s) '/home/greg/Dev/Projects/FSBO/src/Tests/bin/Debug/net8.0/Tests.dll' exited with error: The specified runtimeconfig.json [/usr/lib/dotnet/sdk/8.0.100/testhost-8.0.runtimeconfig.json] does not exist
. Please check the diagnostic logs for more information.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.5.0-10-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|4, 5, 3|
|Memory (System)|7.66GB (4.37GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 2e58bea4-2abd-486f-ba1a-d660f0ad9c03|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
dotnet-test-explorer|for|0.7.8
csdevkit|ms-|1.0.14
csharp|ms-|2.10.28
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
a247i228:30880122
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30887144
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30886110
dsvsc017cf:30886113
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by wgrs** [comment]
Any updates on this?

**Comment by arivoir** [comment]
Same issue here

**Comment by roblourens** [comment]
This sounds like an issue with a C# extension?

**Comment by wgrs** [comment]
The extensions team say it must be reported here. You can expect the public to manage this. If its a different team, surely you can redirect it?

**Comment by kryzalid87** [comment]
@wgrs @arivoir @dunchan, maybe this comment is not so important here, but for a temporary fix, you can add a missing file with the content below,

`{
  "runtimeOptions": {
    "tfm": "net8.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "8.0.100"
    }
  }
}`

**Comment by wgrs** [comment]
As usual with these issues, zero engagement from the team. No updates, nothing. Just completely ignore the issue. Same on vscode tools team. Zero engagement on broken tools.

**Comment by wgrs** [comment]
> I think it's an issue with linux SDK 8.0.100 ![image](https://private-user-images.githubusercontent.com/20307736/289802662-4b6bc2af-5585-4f70-95d6-aa799c178b2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTUwOTEsIm5iZiI6MTcwMjM5NDc5MSwicGF0aCI6Ii8yMDMwNzczNi8yODk4MDI2NjItNGI2YmMyYWYtNTU4NS00ZjcwLTk1ZDYtYWE3OTljMTc4YjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE1MjYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YzlmNGJlZWU2MmY4OGMzZDI1ZGEyMmViYmQzNDJmN2RjMzdlZDZkYjE3MjQ3ZDNiZGYxZTI3MDQwNTg0MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lxvv5MvS83u-efYtEyGKBGJL4OyRqV7Cjdv8aSXUf60) The file testhost-8.0.runtimeconfig.json is simply missing

I am sure it is. However, its up to MS staff to fix these things. Its their products that are not working. Instead, they just close down tickets and put zero effort into doing actual support.

**Comment by roblourens** [comment]
You reported an issue with .NET, which has nothing to do with VS Code. If you filed an issue on the extension team and they told you that it's an issue with VS Code, share the link. I don't know who said what. But I don't see how it's a generic VS Code issue without more details.

**Comment by wgrs** [comment]
How can a vscode extension that is crippling vscode have nothing to do with vscode?

**Comment by roblourens** [comment]
> crippling vscode

It sounds like it's the extension that's crippled

**Comment by wgrs** [comment]
Quite possibly the extension. But unless I am mistaken, is this extension not developed by MS?
