### ISSUE TITLE
Autocomplete removes ending " for html tag attribute value

### ISSUE THREAD

**Issue by simonferndriger** [microsoft/vscode#198793]
Type: <b>Bug</b>

When you have a `<div class="" x-text="...">` and you begin typing a classname and select a suggested class (e.g. "test"), the ending " of the class attribute will get omitted. The tag then looks like this: `<div class="test x-text="...">`. 

Misteriously, this does not always happen but sometimes. Did not figure out the trigger for this issue yet. I assume it has something to do with the non-standard html attribute.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X6 1090T Processor (6 x 3211)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (7.40GB free)|
|Process Argv|--crash-reporter-id a857cf0e-f549-4ce5-b52a-0502444e9549|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
avocode|avo|0.1.0
vscode-intelephense-client|bme|1.10.1
vscode-eslint|dba|2.4.2
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
auto-rename-tag|for|0.1.10
minifyall|jos|2.10.0
ftp-sync|luk|0.3.9
live-server|ms-|0.4.11
sftp|Nat|1.16.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30886110
dsvsc017cf:30886113
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by aeschli** [comment]
The built-in HTML extension does have completions for classes. Maybe this is added by an extension? Can you file the issue there?

**Comment by simonferndriger** [comment]
@aeschli Thanks - I will do that. Can you perhaps provide me the (github) link. Looks like it's not listed in the VS Code plugin section...

**Comment by aeschli** [comment]
From the list of your extension my guess it is the `vscode-intelephense-client` extension.
To verify this, can you disable the extension, and try your example? 
https://github.com/bmewburn/vscode-intelephense would be the repo of the intelephense extension.

**Comment by simonferndriger** [comment]
@aeschli Thanks - somehow I seem to have tomatoes in my eyes, because I don't see this etension im my list either.

This is the effect I am talking about:

![image](https://github.com/microsoft/vscode/assets/1435963/ec7d639e-ddfa-4dd6-bb71-fb98a146128b)

And these are (all) my extensions:

![image](https://github.com/microsoft/vscode/assets/1435963/04a03e68-5d4e-4f66-aebe-39abc8d6092c)

**Comment by aeschli** [comment]
From you screenshot I can see that you have only textual proposals. They come from VS Code (no extension needed).

I tested these, and they don't overwrite the quote.

**Comment by simonferndriger** [comment]
@aeschli To be frank, it took my a while (and some nerves 😅) to reproduce it while capturing it, it usually doesn't occur in the very first attempt. But I finally got it on video. Perhaps it's a timing issue. See attached video.


https://github.com/microsoft/vscode/assets/1435963/8e8311dc-7a67-4681-8eeb-4a5085384e02

**Comment by aeschli** [comment]
Yes, interesting, looks like some timing issue. Assigning to @jrieken given it's a textual proposal.
