### ISSUE TITLE
Show doubles as doubles even if the decimal part is zero.

### ISSUE THREAD

**Issue by Daviid-P** [microsoft/vscode#198745]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

Add `$double = 10.0` to watch.

Seriously I was wondering why the heck `is_int($foo)` was returning false when the watch was clearly showing that `$foo` was 13.

![image](https://github.com/microsoft/vscode/assets/7734808/69845dda-a6a5-41ff-b3a7-788707f6fb76)

If the variable is a double just show the decimal part.

**Comment by roblourens** [comment]
This is up to the debug extension, please file on whichever debug extension you're using
