### ISSUE TITLE
JS on SharePoint via WebDav

### ISSUE THREAD

**Issue by stephen-hardy** [Microsoft/vscode#19870]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.5|
|mssql|ms-mssql|0.2.0|
|PowerShell|ms-vscode|0.9.0|
|code-settings-sync|Shan|2.4.3|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1. Open JavaScript file hosted on SharePoint via WebDav

Feel free to contact v-sthard for more information or a demo

**Comment by mjbvz** [comment]
Thank you for the report.

Tracking this on the TypeScript side with https://github.com/Microsoft/TypeScript/issues/13874
