### ISSUE TITLE
When using ASM syntax, rendering failure occurs.

### ISSUE THREAD

**Issue by aboutzero** [microsoft/vscode#198738]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.2
- OS Version: Windows10

Steps to Reproduce:

1. When using ASM syntax in large C/C++ files, rendering errors occur where the rendered colors are inconsistent with the normal file. However, when I replace "asm" with the "__asm" keyword or use "{}" instead of "()" after "asm," the rendering is correct.
![_17005511931810](https://github.com/microsoft/vscode/assets/44740560/b586e5dc-c60f-4748-b03d-43bff9ae9d21)
![_17005512327822](https://github.com/microsoft/vscode/assets/44740560/c51498d9-30cf-43a5-a8f2-ccd2abee1dbd)
![_17005513075375](https://github.com/microsoft/vscode/assets/44740560/f6615ac7-4425-4b06-ae3e-70c828098b5d)

**Comment by alexr00** [comment]
@aboutzero can you share a copy/pasteable sample that I can use to reproduce the issue?

**Comment by aboutzero** [comment]
Of course, that sample is in llvm project source code.
And you can find it on directory "./openmp/libomptarget/DeviceRTL/src/Misc.cpp" in llvm source code.
[https://github.com/llvm/llvm-project/blob/main/openmp/libomptarget/DeviceRTL/src/Misc.cpp](url)

**Comment by RedCMD** [comment]
@aboutzero clicking that link takes me to https://github.com/microsoft/vscode/issues/url  

should move report to https://github.com/jeff-hykin/better-cpp-syntax

doesn't seem very broken to me
![image](https://github.com/microsoft/vscode/assets/33529441/4eb0bd1b-3c70-4b3b-ac98-5496a6eedc86)
```c
double getWTime() {
  unsigned long long nsecs;
  asm volatile("mov.u64  %0, %%globaltimer;" : "=l"(nsecs));
  return (double)nsecs * getWTick();
}

#pragma omp end declare variant


double getWTime() {
  unsigned long long nsecs;
  __asm volatile("mov.u64  %0, %%globaltimer;" : "=l"(nsecs));
  return (double)nsecs * getWTick();
}

#pragma omp end declare variant


double getWTime() {
  unsigned long long nsecs;
  asm volatile{"mov.u64  %0, %%globaltimer;" : "=l"(nsecs)};
  return (double)nsecs * getWTick();
}

#pragma omp end declare variant
```
https://github.com/llvm/llvm-project/blob/442fef6eea22ac7d26261f88bff778d78857c36a/openmp/libomptarget/DeviceRTL/src/Misc.cpp#L64-L68

**Comment by aboutzero** [comment]
Thank you for your reminder, which made me realize that it was indeed because of the plugin I had enabled. Yes, ultimately I discovered that the reason was due to the activation of an Arm Assembly plugin.
https://github.com/dan-c-underwood/vscode-arm
