### ISSUE TITLE
occurrences highlight stuck the selection word

### ISSUE THREAD

**Issue by xXN1ckWa1k3rXx** [microsoft/vscode#198773]
Type: <b>Bug</b>

I don’t know how to describe this problem. It seems that I pressed a certain key combination (unreasonable) that caused some problems with occurrences highlight.

It's a bit blurry, but if you look closely you'll notice that when I select an empty line, the highlight is still there:

[![It's a bit blurry, but if you look closely you'll notice that when I select an empty row, the highlight is still there][1]][1]

I Split the Editor. If the editor edits the same source file at the same time, the highlight will be stuck in another editor.
But if two editors are not editing the same source file at the same time, this problem will not occur.

It seem that is vscode feature but idk.

Tried:
`editor.occurrencesHighlight = false` (work, but i needed it)
`editor.selectionHighlight = false`
`Editor: Multi Document Occurrences Highlight = false and true` (both have this buggly)

and i tried to restart the vscode and restart the pc, and nothing.

  [1]: https://i.stack.imgur.com/P6pKQ.gif

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics          (12 x 3893)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.29GB (7.70GB free)|
|Process Argv|--crash-reporter-id 95d4c8d0-afc5-4da2-960b-1cd90fa6a90f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.4.2
code-runner|for|0.12.1
vscode-language-pack-zh-hans|MS-|1.84.2023111509
remote-containers|ms-|0.321.0
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
cmake-tools|ms-|1.16.31
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30886110
dsvsc017cf:30886113
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by xXN1ckWa1k3rXx** [comment]
problem still haven't fix
![GIF 12-9-2023 5-15-24 PM](https://github.com/microsoft/vscode/assets/85390877/5cc9cbae-b523-4673-9313-8491d42edf64)

**Comment by Yoyokrazy** [comment]
2 quick follow up questions, what is the value of your `editor.occurrenceHighlight` enum setting? And second, does this only repro when in a split view of the same file, or does this repro when split viewing different files as well?

**Comment by xXN1ckWa1k3rXx** [comment]
1. Default. i do not touch it.
![image](https://github.com/microsoft/vscode/assets/85390877/24d398f6-23a9-4d77-9578-cfe789c1b43c)

2. same file

**Comment by Yoyokrazy** [comment]
Thank you for the responses! Will be looking into this.

**Comment by Yoyokrazy** [comment]
Closing this as a dupe in favor of [#198866](https://github.com/microsoft/vscode/issues/198866)
