### ISSUE TITLE
Show bracket match border in sticky scroll

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#198790]
The matching bracket doesn't show in sticky scroll, it would be very useful though:

![image](https://github.com/microsoft/vscode/assets/2193314/faaa325e-697f-41a3-9ecb-2477aebfd343)

When scrolling up:

![image](https://github.com/microsoft/vscode/assets/2193314/1ff4e522-6a2a-46a5-a749-29b0547bce96)

**Comment by aiday-mar** [comment]
Hi @Tyriar, I am not sure I understood the idea. You would like for example line 8 and line 63 to somehow show together so that the matching bracket pairs are visible?

**Comment by Tyriar** [comment]
@aiday-mar 

current:

![image](https://github.com/microsoft/vscode/assets/2193314/2b9d7377-c303-43e3-b66c-612adfd87480)

proposal:

![image](https://github.com/microsoft/vscode/assets/2193314/416f2f99-f4a0-437d-bbea-88f2b12f1281)

**Comment by aiday-mar** [comment]
Ah right that makes sense. Thanks for the clarification.

**Comment by aiday-mar** [comment]
This is a duplicate of the more generic https://github.com/microsoft/vscode/issues/187834
