### ISSUE TITLE
vscode.cdn.azure.cn cannot fetch latest insider build.

### ISSUE THREAD

**Issue by WitherZuo** [microsoft/vscode#198824]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85-insider
- OS Version: Windows 11 Insider Preview (Canary Build) 25997.1010 (rs_prerelease)

**Steps to Reproduce:**

1. Get download link of VS Code Insiders by `vscode.cdn.azure.cn`. 
2. Failed, then show `BlobNotFound` error.  

## What happened:

Since Monday, the speed of downloading updates for VS Code - Insiders has become abnormally slow. Previously, in China mainland, the download of updates for VS Code was done through `vscode.cdn.azure.cn`, and after checking, it seems that the download link for updates for VS Code - Insiders has changed:

**Stable build:**  
```bash
> curl -s https://update.code.visualstudio.com/latest/win32-x64/stable
Found. Redirecting to https://vscode.cdn.azure.cn/stable/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/VSCodeSetup-x64-1.84.2.exe?1
```  

**Insider build:**
```bash
> curl -s https://update.code.visualstudio.com/latest/win32-x64/insider
Found. Redirecting to https://vscode.download.prss.microsoft.com/dbazure/download/insider/05cd2640ec8a106a4ee99cb38e6ee34fbec04f11/VSCodeSetup-x64-1.85.0-insider.exe?1
```  

Previously, both Stable and Insider builds could be downloaded at high speed via `vscode.cdn.azure.cn` in China mainland, it looks like the new download links are distributed via the PRSS CDN, not `vscode.cdn.azure.cn`, which may be interfered with by some ISP in China mainland (?). VS Code report me `net::ERR_CERT_COMMON_NAME_INVALID`.  

After further investigation, I found that it might be caused by this PR which removed references to `https://vscode.blob.core.chinacloudapi.cn` and `https://vscode.cdn.azure.cn` during the build&publish process, could you re-add `vscode.cdn.azure.cn` to solve the current problem of possible download interruptions? Thank you for your time. 

#198631

**Comment by WitherZuo** [comment]
![Screenshot_20231122112259.png](https://github.com/microsoft/vscode/assets/25317916/9aff98ed-7502-4846-b33c-92f0f3f8e888)

The certificate is wrong, Microsoft's PRSS CDN domain name will not be verified with the certificate of weixin.qq.com, this will not show up as Microsoft, but Shenzhen Tencent.

**Comment by joaomoreno** [comment]
We're currently transitioning to a new CDN, `vscode.download.prss.microsoft.com`, which should be available in China at very high speeds as well. The latest Insider builds are already in the new CDN.

Two questions:

- Is the certificate the only issue you're seeing, or did you also manage to connect and have observed slow speeds from the new CDN?
- Usually whenever there are certificate mismatches, that means the network your machine is on is overwriting the request certificate. Are you in a corporate environment?

**Comment by WitherZuo** [comment]
> We're currently transitioning to a new CDN, `vscode.download.prss.microsoft.com`, which should be available in China at very high speeds as well. The latest Insider builds are already in the new CDN.
> 
> Two questions:
> 
> - Is the certificate the only issue you're seeing, or did you also manage to connect and have observed slow speeds from the new CDN?
> - Usually whenever there are certificate mismatches, that means the network your machine is on is overwriting the request certificate. Are you in a corporate environment?
> 
> This is the expected certificate:
> 
> 
> 
> ![Image](https://github.com/microsoft/vscode/assets/22350/b14f0ebd-59bf-4c9b-8270-7bbee4047edf)
> 
> 

No, my device is on my home network, and using the new CDN to get Insider Build will see something like this:

**1. When downloading through the browser (Firefox):** Firefox will report that the certificate used by the site does not match the site, and I see here that the certificate of the site is from the weixin.qq.com, not Microsoft, you can continue to access the risk with ignorance, but during the download process, the speed will drop from 3 MB/s to 60 KB/s, and then the download fails.

**2. Update from VS Code desktop:** After clicking Check for Update, a net::ERR_CERT_COMMON_NAME_INVALID error will pop up directly, and the update cannot be checked.

**Networks used:**
ISP: China Unicom - Beijing Unicom
DNS Service Provider: Alibaba Public DNS
DNS：223.5.5.5

**Comment by WitherZuo** [comment]
![图片](https://github.com/microsoft/vscode/assets/25317916/b72549ea-7526-4a0f-b7f9-0e2a81f7d238)

**Comment by joaomoreno** [comment]
Interesting. Can you reproduce on another machine?

**Comment by WitherZuo** [comment]
> Interesting. Can you reproduce on another machine?

Yes, a user named CodeCodeStudy on V2EX is also experiencing this issue (the main language of this site is Chinese, you may need to use translation)

[https://v2ex.com/t/993964#reply3](https://v2ex.com/t/993964#reply3)

The image I uploaded after my first post was also his reply.

**Comment by WitherZuo** [comment]
![Image_1700648150395.jpg](https://github.com/microsoft/vscode/assets/25317916/4aa05d15-5ad9-4325-86f8-b7c9ee506589)

![Image_1700648159241.jpg](https://github.com/microsoft/vscode/assets/25317916/615d7f79-2791-4802-9875-183c40bef082)

@joaomoreno

**Comment by joaomoreno** [comment]
@WitherZuo Actually, the user CodeCodeStudy isn't also experiencing the same issue. They are pointing to the fact that there must be some misconfiguration in the network somewhere; potentially even an actual attack on your machine. I agree with their analysis.

**Comment by WitherZuo** [comment]
I tested the download speed for `vscode.cdn.azure.cn` and `vscode.download.prss.microsoft.com` respectively. Where `vscode.cdn.azure.cn` is used for stable build and `vscode.download.prss.microsoft.com` is used for insider build. Each test have 5 download attempts.  

## `vscode.cdn.azure.cn` + Stable build:  

```bash
~\Downloads took 10s
> curl -s https://update.code.visualstudio.com/latest/win32-x64/stable
Found. Redirecting to https://vscode.cdn.azure.cn/stable/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/VSCodeSetup-x64-1.84.2.exe?1
```  

### Test output:
<details>
<summary>Click me to show more...</summary>  

```bash  
~\Downloads
> curl -s https://update.code.visualstudio.com/latest/win32-x64/stable
Found. Redirecting to https://vscode.cdn.azure.cn/stable/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/VSCodeSetup-x64-1.84.2.exe?1

~\Downloads
> curl -O https://vscode.cdn.azure.cn/stable/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/VSCodeSetup-x64-1.84.2.exe?1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 90.2M  100 90.2M    0     0  8717k      0  0:00:10  0:00:10 --:--:-- 9139k

~\Downloads took 10s
> curl -O https://vscode.cdn.azure.cn/stable/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/VSCodeSetup-x64-1.84.2.exe?1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 90.2M  100 90.2M    0     0  8169k      0  0:00:11  0:00:11 --:--:-- 8403k

~\Downloads took 11s
> curl -O https://vscode.cdn.azure.cn/stable/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/VSCodeSetup-x64-1.84.2.exe?1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 90.2M  100 90.2M    0     0  8206k      0  0:00:11  0:00:11 --:--:-- 8236k

~\Downloads took 11s
> curl -O https://vscode.cdn.azure.cn/stable/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/VSCodeSetup-x64-1.84.2.exe?1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 90.2M  100 90.2M    0     0  8318k      0  0:00:11  0:00:11 --:--:-- 9069k

~\Downloads took 11s
> curl -O https://vscode.cdn.azure.cn/stable/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/VSCodeSetup-x64-1.84.2.exe?1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 90.2M  100 90.2M    0     0  8743k      0  0:00:10  0:00:10 --:--:-- 8624k
```  
  
</details>

### Test result: (`vscode.cdn.azure.cn`)
<details>
<summary>Click me to show more...</summary> 
 
**Attempts:** 5, 
**Download Success:** 5, 
**Download Failure:** 0, 
**User Cancel:** 0, 
**Download Time:** 10 ~ 11 seconds, 
**Download Speed:** 8.7 MB/s.    

</details>

## `vscode.download.prss.microsoft.com` + Insider build:  

```bash
~\Downloads
> curl -s https://update.code.visualstudio.com/latest/win32-x64/insider
Found. Redirecting to https://vscode.download.prss.microsoft.com/dbazure/download/insider/f3da7cb46a8ffbea21998420dc673777715e55cf/VSCodeSetup-x64-1.85.0-insider.exe
```   

### Test output: (with HTTPS)
<details>
<summary>Click me to show more...</summary>  

```bash
~\Downloads
> curl -O https://vscode.download.prss.microsoft.com/dbazure/download/insider/f3da7cb46a8ffbea21998420dc673777715e55cf/VSCodeSetup-x64-1.85.0-insider.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) schannel: SNI or certificate check failed: SEC_E_WRONG_PRINCIPAL (0x80090322) - 目标主要名称不正确。
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

</details>

### Test output (with non-HTTPS) - ROUND 1:
<details>
<summary>Click me to show more...</summary>  

```bash
~\Downloads
x curl -O http://vscode.download.prss.microsoft.com/dbazure/download/insider/f3da7cb46a8ffbea21998420dc673777715e55cf/VSCodeSetup-x64-1.85.0-insider.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 90.1M  100 90.1M    0     0  7970k      0  0:00:11  0:00:11 --:--:-- 8372k

~\Downloads took 11s
> curl -O http://vscode.download.prss.microsoft.com/dbazure/download/insider/f3da7cb46a8ffbea21998420dc673777715e55cf/VSCodeSetup-x64-1.85.0-insider.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 10 90.1M   10 9628k    0     0   232k      0  0:06:37  0:00:41  0:05:56     0
curl: (56) Recv failure: Connection was reset

~\Downloads took 41s
x curl -O http://vscode.download.prss.microsoft.com/dbazure/download/insider/f3da7cb46a8ffbea21998420dc673777715e55cf/VSCodeSetup-x64-1.85.0-insider.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 90.1M  100 90.1M    0     0  6392k      0  0:00:14  0:00:14 --:--:-- 7679k

~\Downloads took 14s
> curl -O http://vscode.download.prss.microsoft.com/dbazure/download/insider/f3da7cb46a8ffbea21998420dc673777715e55cf/VSCodeSetup-x64-1.85.0-insider.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 90.1M  100 90.1M    0     0  7247k      0  0:00:12  0:00:12 --:--:-- 8908k

~\Downloads took 12s
> curl -O http://vscode.download.prss.microsoft.com/dbazure/download/insider/f3da7cb46a8ffbea21998420dc673777715e55cf/VSCodeSetup-x64-1.85.0-insider.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 90.1M  100 90.1M    0     0  8604k      0  0:00:10  0:00:10 --:--:--  9.9M
```

</details>  

### Test result (`vscode.download.prss.microsoft.com`) - ROUND 1:
<details>
<summary>Click me to show more...</summary>  

**Attempts:** 5, 
**Download Success:** 4, 
**Download Failure:** 1 (Connection was reset), 
**User Cancel:** 0, 
**Download Time:** 11 ~ 41 seconds, 
**Download Speed:** 6.4 ~ 8.5 MB/s.    

</details>  

### Test output (with non-HTTPS) - ROUND 2:
<details>
<summary>Click me to show more...</summary>  

```bash
~\Downloads
> curl -O http://vscode.download.prss.microsoft.com/dbazure/download/insider/f3da7cb46a8ffbea21998420dc673777715e55cf/VSCodeSetup-x64-1.85.0-insider.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 13 90.1M   13 11.8M    0     0  84809      0  0:18:34  0:02:26  0:16:08     0
curl: (56) Recv failure: Connection was reset

~\Downloads took 2m26s
x curl -O http://vscode.download.prss.microsoft.com/dbazure/download/insider/f3da7cb46a8ffbea21998420dc673777715e55cf/VSCodeSetup-x64-1.85.0-insider.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 12 90.1M   12 11.0M    0     0  65888      0  0:23:53  0:02:56  0:20:57     0
curl: (56) Recv failure: Connection was reset

~\Downloads took 2m56s
x curl -O http://vscode.download.prss.microsoft.com/dbazure/download/insider/f3da7cb46a8ffbea21998420dc673777715e55cf/VSCodeSetup-x64-1.85.0-insider.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 14 90.1M   14 12.6M    0     0  71018      0  0:22:10  0:03:06  0:19:04     0
curl: (56) Recv failure: Connection was reset

~\Downloads took 3m6s
x curl -O http://vscode.download.prss.microsoft.com/dbazure/download/insider/f3da7cb46a8ffbea21998420dc673777715e55cf/VSCodeSetup-x64-1.85.0-insider.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 90.1M    0  7244    0     0    478      0 54:54:15  0:00:15 54:54:00     0
curl: (56) Recv failure: Connection was reset

~\Downloads took 15s
x curl -O http://vscode.download.prss.microsoft.com/dbazure/download/insider/f3da7cb46a8ffbea21998420dc673777715e55cf/VSCodeSetup-x64-1.85.0-insider.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 90.1M    0  322k    0     0   4177      0  6:16:58  0:01:19  6:15:39     0
curl: (56) Recv failure: Connection was reset
``` 

</details>  

### Test result (`vscode.download.prss.microsoft.com`) - ROUND 2:
<details>
<summary>Click me to show more...</summary>  

**Attempts:** 5, 
**Download Success:** 0, 
**Download Failure:** 5 (Connection was reset), 
**User Cancel:** 0, 

</details>  

## Conclusion  

Downloading from `vscode.cdn.azure.cn` are very stable and fast, and have never failed; downloading from `vscode.download.prss.microsoft.com` are sometimes less stable, and at certain moments frequently experience a decrease in download speed, and then get stuck, reporting that `Connection was reset` error. Also some situations may be complicated because of Great Firewall (GFW).

**Comment by joaomoreno** [comment]
Thank you for the detailed tests @WitherZuo. Did you find anything about the SSL certificate?

**Comment by WitherZuo** [comment]
> Thank you for the detailed tests @WitherZuo. Did you find anything about the SSL certificate?

No, I'm curious as to why this certificate is from weixin.qq.com and not Microsoft Azure. My device has not been subjected to any internet attacks.  

In addition, there are a lot of people in China who use WeChat (both on computers and mobile devices)...

**Comment by joaomoreno** [comment]
This is why I asked if you could reproduce this in another machine. Do you have a second machine you can try this out from?

**Comment by WitherZuo** [comment]
> This is why I asked if you could reproduce this in another machine. Do you have a second machine you can try this out from?

I tested it using Firefox on my phone and I was getting the certificate error too. The screenshots above, with the exception of two screenshots from Firefox, were tested by others on their own devices, and they also ran into this issue.  

![Screenshot_20231122230107.png](https://github.com/microsoft/vscode/assets/25317916/4afe6f62-704b-4409-8da6-51ac58a7442c)

**Comment by WitherZuo** [comment]
It seems that resolving of https://vscode.download.prss.microsoft.com in different regions of China mainland is very confusing, and it usually resolves to the address of the carrier, while outside of Chinese mainland, it is an anycast address.

![Image_1700666786611.png](https://github.com/microsoft/vscode/assets/25317916/ce25cd6a-0545-4f2c-a0ff-b59a7c8d75d9)

**Comment by Mundanity-fc** [comment]
![image](https://github.com/microsoft/vscode/assets/17294992/656686b5-a041-448e-8fc2-838f6020e6b7)
Same dig output.
The domain `*.cdn.dnsv1.com` belongs to Tencent Cloud CDN, which could explain why the SSL certificant is wrong.
![image](https://github.com/microsoft/vscode/assets/17294992/c8be2494-f916-4638-adb3-0d4c2ba2656b)

**Comment by joaomoreno** [comment]
Thank you for this!

**Comment by WitherZuo** [comment]
> The certificate of vscode.download.prss.microsoft.com in Tencent Cloud CDN isn't configured correctly yet.
> 
> Additional info: the domain above points to Tencent Cloud CDN in China as its front CDN service now.
> 
> ![Screenshot_2023-11-23-00-41-58-920_com.android.chrome.jpg](https://github.com/microsoft/vscode/assets/67832651/23b066a3-a9e8-4f67-85df-469fdbd28c06)
> 
> ![Screenshot_2023-11-23-00-37-57-326_bin.mt.plus.jpg](https://github.com/microsoft/vscode/assets/67832651/fdfc3570-1973-4f2d-a77d-a2383aa74bc2)
> 
> 
> 
> ~~I also tested that downloading via HTTP works well.~~ Downloading via HTTP will get slower and slower and not advance any process.
> 
> To the VSC Team: If you encounter some issues when configuring an SSL certificate in Tencent Cloud CDN, you can reach me at Teams via caozhi.li@studentambassadors.com, and I will help you.

Yes, if download via HTTP, the download speed will slower and slower, and finally failed, for me, it will report `Connection was reset`.

**Comment by LiCaoZ** [comment]
It concludes that it isn't a DNS issue; the resolving result of vscode.download.prss.microsoft.com is correct.
It is a problem with the configuration of Tencent Cloud CDN in China.

------

If the VSC team has anything wrong with configuring the Tencent Cloud CDN, please contact me at Teams anytime so I can assist you to have them done if needed.

**Comment by WitherZuo** [comment]
@LiCaoZ 😊Thank you for your analysis for helping us quickly and accurately understand what the issue is, and we hope that the VS Code team could resolve the issue as soon as possible. However, the new DNS is still slightly slow to access in parts of China mainland (as can be observed from the resolution of the figure above...). It is also unknown whether access to this DNS in China mainland will be interfered with by GFW in the future...

**Comment by WitherZuo** [comment]
![图片](https://github.com/microsoft/vscode/assets/25317916/9f730da4-0cca-4232-9df4-93e796dab4cf)
It looks like HTTPS access is back to normal, further ongoing observation and testing is required.

**Comment by joaomoreno** [comment]
> It seems that HTTPS access is back to normal, further ongoing observation and testing is required.

So is this working OK for you now? And what are the test speeds in HTTPS? And are you still having connection reset events?

It might just be that the GFW needs to get accustomed to new domains popping in.

**Comment by WitherZuo** [comment]
> > It seems that HTTPS access is back to normal, further ongoing observation and testing is required.
> 
> So is this working OK for you now? And what are the test speeds in HTTPS? And are you still having connection reset events?
> 
> It might just be that the GFW needs to get accustomed to new domains popping in.

Thanks! The HTTPS connection has been restored, VS Code desktop can check for updates normally, and it seems that the download speed is about 3 MB/s to 8 MB/s, and Connection was reset problem still exists, the speed will gradually drop to 0 and then get stuck for a while and failed, usually after the first successful download, subsequent downloads may not be stable.  

IMO, the final result of this new CDN in China mainland is not yet clear, and it may be necessary to wait until the next stable release to start using the new CDN for all VS Code downloads.  

Does this new CDN have relevant nodes deployed in China mainland? Thank you for your reply.

**Comment by joaomoreno** [comment]
Thank you for confirming and being so responsive overall!

> Connection was reset problem still exists, the speed will gradually drop to 0 and then get stuck for a while and failed

How often do you estimate this happening still?

> Does this new CDN have relevant nodes deployed in China mainland?

Correct, this new CDN does have relevant nodes deployed in China, via Tencent. This was a hard requirement for us to move to a new system. We are working on also adding a new provider in parallel.

**Comment by WitherZuo** [comment]
> Thank you for confirming and being so responsive overall!
> 
> > Connection was reset problem still exists, the speed will gradually drop to 0 and then get stuck for a while and failed
> 
> How often do you estimate this happening still?
> 
> > Does this new CDN have relevant nodes deployed in China mainland?
> 
> Correct, this new CDN does have relevant nodes deployed in China, via Tencent. This was a hard requirement for us to move to a new system. We are working on also adding a new provider in parallel.

There doesn't seem to be a specific time pattern, and basically the first time is relatively fast and successful, and then there is a certain probability that it will be unstable when trying again.

**Comment by joaomoreno** [comment]
This is great! Closing the issue for now. Let me know here if it regresses at some point.
