### ISSUE TITLE
feat: copyable text in pop-up messages

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode#198897]

**Comment by hamirmahal** [comment]
I can't currently copy text in pop-up messages like this one.

![image](https://github.com/microsoft/vscode/assets/43425812/2cd9a2e6-1fee-4113-854a-59c100c49528)

It'd be nice if I could, since then I wouldn't have to spend time typing error messages.

**Comment by lramos15** [comment]
This is just a native OS limitation. If you want you can use custom dialogs via `"window.dialogStyle": "custom"` which allows copy and pasting
