### ISSUE TITLE
Can't enable the Dynamic Debug Configurations feature without the activation event onDebugDynamicConfigurations

### ISSUE THREAD

**Issue by walter-erquinigo** [microsoft/vscode#198800]
Type: <b>Bug</b>

I'm developing an extension for VSCode and found out that I can't enable Dynamic Debug Configurations unless I include `onDebugDynamicConfigurations` in the list of activation events.

I have tried not including this activation event but having my extension activated through other means (like activated on language), but the feature doesn't work.

Only when I include `onDebugDynamicConfigurations`, this feature works.

My extension is now working properly, but I wouldn't be surprised if this prevents other extension developers from using this feature.  I have found this very old post of someone who might have had that exact same issue https://stackoverflow.com/questions/57283882/providedebugconfigurations-not-getting-called.

VS Code version: Code 1.84.2 (Universal) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.57GB free)|
|Process Argv|--crash-reporter-id 145e4c41-a207-4208-bc81-c945b5ead5dc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.52.0
gitlens|eam|14.5.0
prettier-vscode|esb|10.1.0
custom-local-formatters|jki|0.0.6
vscode-clangd|llv|0.1.24
vscode-mlir|llv|0.0.11
rainbow-csv|mec|3.8.0
vscode-mojo|mod|5.0.4-dev
csdevkit|ms-|1.0.14
csharp|ms-|2.10.28
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26
black-formatter|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
jupyter|ms-|2023.10.1100000000
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.321.0
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.24.0
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
reflow-paragraph|Tro|1.3.0
errorlens|use|3.15.0
vscode-icons|vsc|12.6.0
vim|vsc|1.27.0
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
vscrpc:30673769
2i9eh265:30646982
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016cf:30886111
dsvsc017cf:30886113
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by roblourens** [comment]
Can you explain a bit more what doesn't work?

**Comment by walter-erquinigo** [comment]
@roblourens , thanks for looking into this.

I have an extension with a working debugger feature via launch.json file. I'm trying to register a DebugConfigurationProvider with kind = `dynamic` that implements `provideDebugConfigurations`. And, unless, I add `onDebugDynamicConfigurations` as an activation event, my new provider doesn't get invoked at all and I don't see an entry for my debugger in the selector of the Debug View. I have confirmed that my extension was initialized right after VSCode is launched. It's as if this kind of provider is only enabled if the activation event is present.

**Comment by roblourens** [comment]
There's some discussion about this in https://github.com/microsoft/vscode/issues/96297. @connor4312 you've touched this too, should this be changed or just documented?

**Comment by connor4312** [comment]
I think changing it is fine. An extension _should_ register an activation for it, but this isn't something we enforce for any other API. Will take care of it.
