### ISSUE TITLE
Settings contain strange "*h*h*h*h" file associations

### ISSUE THREAD

**Issue by Bascy** [Microsoft/vscode#19880]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-file-templates|bam|1.0.2|
|githistory|donjayamanne|0.1.5|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.4.2|
|xml|DotJoshJohnson|1.7.0|
|vscode-javac|georgewfraser|0.0.23|
|CppSnippets|hars|0.0.6|
|ino|vscode|0.1.0|
|cpptools|ms-vscode|0.10.0|
|python|tht13|0.2.3|
|omnipascal|Wosi|0.12.0|

---

Steps to Reproduce:
Looking at my settings file, it shows the following entries:

    "files.associations": {
      "*.mk": "makefile",
      "*.ino": "cpp",
      "string": "cpp",
      "vector": "cpp",
      "*h*h*h*h*hdeque": "cpp",
      "deque": "cpp",
      "*h*hdeque": "cpp",
      "list": "cpp",
      "*h*h*h*harray": "cpp",
      "array": "cpp",
      "unordered_map": "cpp",
      "initializer_list": "cpp",
      "*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*h*CPP*CPP*h*h*h*h*cpp*cpp*cpp*cpp*cppdeque": "cpp",
      "associative_base": "cpp",
      "serstream": "cpp",
      "*cpp*cpp*H*H*H*H*H*H*h*h*CPP*CPP*CPP*CPP*CPP*CPP*CPP*CPP*Hvalarray": "cpp",
      "*tcc*c*cppios": "cpp",
      "*harray": "cpp",
      "*h*h*h*hdeque": "cpp",
      "random": "cpp",
      "*h*h*h*halgorithm": "cpp",
      "algorithm": "cpp",
      "*H*h*h*h*h*Hlocale": "cpp"
    },

**Comment by sandy081** [comment]
Totally unsure how could this happen unless the user or the extension add the entry. 

@Bascy May I know, do you have any extensions that could do this? Probably configure and open VS Code using a different user directory and see if this is being added again?

`code --user-data-dir=<folder>`

**Comment by sean-mcmanus** [comment]
@Bascy It's a bug with the cpptools extension. It should be fixed with the 0.10.1 update we're releasing today. After getting the updated extension version, you can just delete your entire files.associations, unless you want to keep some you manually added. The associations automatically get added for extensionless and non-standard files that are part of C/C++ #include statements when a Go to Definition is used on them.

**Comment by sandy081** [comment]
Thanks @Bascy for the update
