### ISSUE TITLE
JS/TS Service

### ISSUE THREAD

**Issue by Gebriell** [microsoft/vscode#198818]
Type: <b>Bug</b>

TS/JS service apparently crashed 5 times and did not restart. I was initially prompted to disable intellicode, but it still ended up crashing

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.1.0-1025-oem snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1360P (16 x 3474)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|30.96GB (17.81GB free)|
|Process Argv|--no-sandbox --crash-reporter-id c5076f15-344b-4f45-b9f9-55e46f89e18e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.138.0
copilot-chat|Git|0.10.2
copilot-labs|Git|0.17.1121
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
cmake-tools|ms-|1.16.31
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
java|red|1.24.0
LiveServer|rit|5.7.9
cmake|twx|0.0.17
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.2
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.43.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30887144
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30886110
dsvsc017:30886112
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Gebriell** [comment]
I'm not sure. For context, I am also getting another error from Copilot:

[ERROR] [default] [2023-11-21T23:34:02.209Z] Extension activation failed: "ENOENT: no such file or directory, uv_cwd"

Perhaps a restart might solve the issue.

**Comment by Gebriell** [comment]
Looks like that did it. Thanks for the help.
