### ISSUE TITLE
Feature request: remember the last text searches

### ISSUE THREAD

**Issue by dluc** [Microsoft/vscode#19884]
- VSCode Version: 1.9.0
- OS Version: MacOS

Steps to Reproduce:

1. Edit->Find
2. The input box where to enter the text to search should allow selecting something searched recently in the current session

**Comment by mjbvz** [comment]
I believe this is already implemented, see #13659. Use `alt` + up and down arrow to navigate through the search history

**Comment by dluc** [comment]
I see thanks for pointing to the shortcut. However I think it's more of a UI issue, a dropdown list would make it more visible.
