### ISSUE TITLE
Multi diff editor failed to open

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#198832]
Type: <b>Bug</b>

When reviewing outgoing changes for my tracking fork of microsoft/vscode after merging upstream/main into my local copy today.

![image](https://github.com/microsoft/vscode/assets/6726799/65461b1e-6cbe-4427-8509-ed42018e2979)

Also, based on #198768 I was surprised to see the magnifying glass icon still being used for "View Changes".

VS Code version: Code - Insiders 1.85.0-insider (f3da7cb46a8ffbea21998420dc673777715e55cf, 2023-11-22T05:35:23.085Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by hediet** [comment]
I'm very sure this is a duplicate of https://github.com/microsoft/vscode/issues/198325

**Comment by hediet** [comment]
> Also, based on https://github.com/microsoft/vscode/pull/198768 I was surprised to see the magnifying glass icon still being used for "View Changes".

This sounds like there was no insiders for today. Can you check you are running the build from today? The PR just got merged yesterday.

**Comment by gjsjohnmurray** [comment]
> VS Code version: Code - Insiders 1.85.0-insider ([f3da7cb](https://github.com/microsoft/vscode/commit/f3da7cb46a8ffbea21998420dc673777715e55cf), 2023-11-22T05:35:23.085Z)

Yes, this is today's. The new codicon appears in the Timeline view, just not in the incoming/outgoing party of Source Control view:

![image](https://github.com/microsoft/vscode/assets/6726799/7256ac4e-3ddd-4dcb-94c4-3dc3cef24aea)

**Comment by hediet** [comment]
It does for me:

![Image](https://github.com/microsoft/vscode/assets/2931520/1e5f2466-b2de-4d36-868b-104aa8b480f4)

**Comment by gjsjohnmurray** [comment]
Ah, we're not talking about the same thing.

My screenshot is of the feature recently added by @lszomoru and controlled by the `scm.showIncomingChanges` and `scm.showOutgoingChanges` settings. It comes from here:

https://github.com/microsoft/vscode/blob/e0ef3fcd186931240d5a6bcb63a5c9c1f5d79ea2/src/vs/workbench/contrib/scm/browser/scmViewPane.ts#L1729-L1742

**Comment by lszomoru** [comment]
@gjsjohnmurray, are you able to reproduce this consistently? 
Could you provide steps that that I should use to try to reproduce the issue? Thanks!

**Comment by gjsjohnmurray** [comment]
@lszomoru in https://github.com/microsoft/vscode/issues/198832#issuecomment-1822525064 @hediet said it was probably a known issue. Ever since Insiders got that fix I haven't had any problems opening multi-diff for outgoing changes that get listed after I merge from upstream/main into my local main prior to pushing them to origin/main (my tracking repo). So I'm closing this one.

**Comment by lszomoru** [comment]
@gjsjohnmurray, thanks for the update!

**Comment by gjsjohnmurray** [comment]
Hmm, just happened to me again with today's Insiders:

![image](https://github.com/microsoft/vscode/assets/6726799/1c622e30-2c25-4161-95d0-ab4af51b453c)

Reopening.

@lszomoru @hediet  I'll hold back from pushing the local changes that I merged in from upstream/main in case there are places you'd like me to look for clues while I can repro it.

**Comment by gjsjohnmurray** [comment]
Devtools console:
```
  ERR Error: File seems to be binary and cannot be opened as text
    at g.M (textFileService.ts:241:11)
    at async g.readStream (textFileService.ts:198:35)
    at async T.Cb (textFileEditorModel.ts:444:20)
    at async T.resolve (textFileEditorModel.ts:300:3)
    at async s.W (textFileEditorModelManager.ts:416:4)
    at async u.r (textModelResolverService.ts:70:18)
    at async y.acquire (lifecycle.ts:683:19)
    at async h.createModelReference (textModelResolverService.ts:238:10)
    at async multiDiffEditorInput.ts:87:40
    at async Promise.all (index 10)
    at async u.t (multiDiffEditorInput.ts:86:14)
    at async ne.b (multiDiffEditorInput.ts:76:17)
    at async i.setInput (multiDiffEditor.ts:68:14)
    at async g.S (editorPanes.ts:445:4)
    at async g.L (editorPanes.ts:270:34)
    at async g.openEditor (editorPanes.ts:146:12)
    at async editorGroupView.ts:1111:49
    at async editorCommands.ts:667:3
    at async E.u (actions.ts:194:3)
    at async E.run (actions.ts:185:4)
    at async L.onClick (menuEntryActionViewItem.ts:156:4)
```

**Comment by gjsjohnmurray** [comment]
It's this one:

![image](https://github.com/microsoft/vscode/assets/6726799/c647888c-876f-453b-996e-4898aa2f249f)

And specifically `codicon.ttf` which is of course binary:

![image](https://github.com/microsoft/vscode/assets/6726799/e0231021-0381-4050-9552-cd2fb44c9ec1)

I guess the multi diff editor needs to handle this case gracefully instead of failing to show the diffs for the other files.

**Comment by lszomoru** [comment]
@gjsjohnmurray, thanks! @hediet, could you please take a look? Thanks!

**Comment by hediet** [comment]
Ahh, because it is a binary file...
