### ISSUE TITLE
Problem in Visual studio code

### ISSUE THREAD

**Issue by ShubhamCodeMaster** [microsoft/vscode#198852]
Type: <b>Bug</b>

i am not able to see options in right top corner

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (3.93GB free)|
|Process Argv|--crash-reporter-id d6d47b51-e9a1-48f2-bc28-d8c632bae13f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
vscode-django|bat|1.14.0
emojisense|bie|0.10.0
tailwindshades|bou|0.0.5
vscode-tailwindcss|bra|0.10.3
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
tailwindcss-intellisense-twin|lig|3.0.0
google-fonts|lio|0.0.1
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
mongodb-vscode|mon|1.3.1
python|ms-|2023.20.0
remote-wsl|ms-|0.81.8
vscode-extension-auto-import|Nuc|1.4.3
tailwindcss-tune|omk|0.0.6
material-icon-theme|PKi|4.32.0
vscode-css-peek|pra|4.4.1
vscode-css-navigation|puc|1.14.0
html-to-jsx|ria|0.0.1
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
tailwindcss-transpiler|sud|0.0.8
tail-lighter|Teo|0.0.2
pdf|tom|1.2.2
es7-react-js-snippets|woo|2.5.1
JavaScriptSnippets|xab|1.8.0
tailwind-snippets|Zar|1.0.2
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30886110
dsvsc017:30886112
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by gjsjohnmurray** [comment]
Which options?

/gifPlease

**Comment by ShubhamCodeMaster** [comment]
![Recording 2023-11-22 at 18 58 25](https://github.com/microsoft/vscode/assets/150455657/c7d74717-08c4-4a50-8945-08d74bf75d0d)

**Comment by ShubhamCodeMaster** [comment]
No

**Comment by ShubhamCodeMaster** [comment]
How to solve this problem i am not able to see my setting

**Comment by gjsjohnmurray** [comment]
This sounds like #198420

Please use the advice at https://github.com/microsoft/vscode/issues/198420#issuecomment-1814986927 to look for error message in the devtools console.

**Comment by ShubhamCodeMaster** [comment]
Recording 2023-11-22 at 21.34.37.gif
<https://drive.google.com/file/d/1-wpLqDdm5-n3wyLq1KVVMl_-u-5nKMHj/view?usp=drive_web>
i am follow this step but my problem is not solved please tell me perfect
solution for solving this problem

**Comment by gjsjohnmurray** [comment]
Please use the GitHub web interface and drag/drop or copy/paste your GIF directly into a comment. Alternatively use the paperclip button on the comment editor toolbar.
