### ISSUE TITLE
Refactor menu's css seems missing

### ISSUE THREAD

**Issue by fourdim** [microsoft/vscode#198881]
Does this issue occur when all extensions are disabled?: Yes, but with vscode-remote enabled.

- Version: 1.85.0-insider (user setup)
- Commit: 05cd2640ec8a106a4ee99cb38e6ee34fbec04f11
- Date: 2023-11-21T05:35:09.651Z
- Electron: 25.9.4
- ElectronBuildId: 25127168
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0
- OS: Windows_NT x64 10.0.19045
- Remote-SSH: v0.107.0

Steps to Reproduce:

1. Create a typescript file.
2. Select a function and click on refactor.

![image](https://github.com/microsoft/vscode/assets/59462000/849846a6-cd36-4d88-aa8a-3239b6d59cd5)

**Comment by gjsjohnmurray** [comment]
Do you still get this after you update to the newest Insiders?

**Comment by fourdim** [comment]
Yeah, the bug is still there.
The latest insider:

- Version: 1.85.0-insider (user setup)
- Commit: 9524207999ef1159f5e973539d68c69ed1b519f2
- Date: 2023-11-22T14:33:51.941Z
- Electron: 25.9.4
- ElectronBuildId: 25127168
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0
- OS: Windows_NT x64 10.0.19045

**Comment by justschen** [comment]
I've been unable to reproduce this - do you have a reliable repro for this @fourdim ?

**Comment by fourdim** [comment]
At least it is reproducible on my side.
- Disable all the extensions.
- Create a file called `a.ts`
- Copy the following code to the file:
```typescript
export const aa = () => {
    console.log('aa');
};
```
- Move the cursor to `lo|g`
```typescript
export const aa = () => {
    console.lo|g('aa');
};
```
- Right click to open the menu and then click on the refactor.

**Comment by justschen** [comment]
repro:
- Linux
- refactor (via menu) before hitting the lightbulb, using the quick fix menu, or using ctrl + shift + r
- Observe focused, but incorrectly rendered menu

**Comment by mirao** [comment]
The same issue is in my environment when using "Refactor" on a selected text in a TypeScript file. I'm able to reproduce it reliably.
Note it happens only if the setting `window.titleBarStyle` has the value `custom`. Value `native` works well.
It could be a regression in 1.85 as I didn't the issue in 1.84.

![image](https://github.com/microsoft/vscode/assets/12584138/f6a46016-19b5-401d-b2fb-4e9834294f76)

Tested with (both environments are affected):
- Windows 11, VSCode 1.85
- Ubuntu 22.04, VSCode 1.85

**Comment by DanTup** [comment]
This is happening in stable now, the refactor menu is broken in many ways. For TypeScript it looks like this:

![image](https://github.com/microsoft/vscode/assets/1078012/f43de385-b632-4210-af7a-2c072d9f0e18)

For Dart/Flutter, the menu just doesn't appear when you click "Refactor" in the context menu, but if you use the shortcut key it appears, and then it subsequently appears when you use the menu.

**Comment by justschen** [comment]
exploring this right now - looks like it's only happening in Windows and Linux, was unable to repro on Mac.

**Comment by justschen** [comment]
wonder if it's related to @bpasero 's change in the `contextViewService` https://github.com/microsoft/vscode/commit/af63c41918a0608c2385d79efc8b1b5b3a033339

I'm seeing `shadow-root` where it's not supposed to be. 

<img width="1471" alt="Screenshot 2023-12-12 at 9 02 02 AM" src="https://github.com/microsoft/vscode/assets/54879025/74e2a2a9-5fb7-43f6-9e2c-5e57a568bf48">
