### ISSUE TITLE
C:\Program Files (x86)\Local\resources\extraResources\lightning-services\php-8.1.23+0\bin\win64\php.exe

### ISSUE THREAD

**Issue by richatwin** [microsoft/vscode#198879]
When I save this it looses many backslash, why so?

`C:\Program Files (x86)\Local\resources\extraResources\lightning-services\php-8.1.23+0\bin\win64\php.exe`
![03](https://github.com/microsoft/vscode/assets/151412101/6d0ad7b4-9f8c-4e7a-bd87-25c478f5849a)

Whats the solution to Issue?

**Comment by gjsjohnmurray** [comment]
In JSON strings you must double up ever backslash.

**Comment by richatwin** [comment]
Like This:

![image](https://github.com/microsoft/vscode/assets/151412101/7ba2ff2c-0a0a-4af1-9da6-78dcd5b9e814)

**Comment by gjsjohnmurray** [comment]
Please close your issue.
