### ISSUE TITLE
TypeScript Promises aren't typed correctly

### ISSUE THREAD

**Issue by danperkins** [Microsoft/vscode#19882]
- VSCode Version: 1.9
- OS Version: Windows 10 Enterprise version 1607

Steps to Reproduce:

1. Create a new Typescript File (.ts)
2. Paste this code in the editor:
// bar typed by VSCode (with 'es2015.promise lib configuration) -- Promise<void>
// bar typed by VSCode with 'es6-promise' module -- Promise<string>
// bar typed by Typescript Playground -- Promise<number | string>
let bar = Promise.resolve()
    .then(() => 5)
    .catch(() => {
        return 'true';
    });

// foo typed by VSCode (with 'es2015.promise lib configuration) -- Promise<{}>
// foo typed by VSCode with 'es6-promise' module -- Promise <any>
// foo typed by Typescript Playground -- Promise <string>
let foo = Promise
    .resolve(5)
    .then(() => 'test')
    .catch(() => {
        return Promise.reject(false);
    });

The typings for the Promises don't match what I would expect them to (compared to [https://www.typescriptlang.org/play/](https://www.typescriptlang.org/play/) which does the right thing.  I was using npm module 'es6-promise' instead of including a polyfill, but switched to trying the --lib declaration for 'es2015.promise' in my tsconfig file.  Both cases gave me different typings for the Promise, but both were wrong and didn't match Typescripts playground.

Is this a known issue or is there some other combination of configurations that I can use to get correctly typed Promises?

Thanks!

**Comment by mjbvz** [comment]
Using this `tsconfig.json`, I see the correct typings: 

```json
{
    "compilerOptions": {
        "target": "es6"
    }
}
```

I don't know why `"lib": [ "es2015.promise" ]` does not work the same way, but I suggest you  follow up with TypeScript on this. They would probably can better explain why these cases produce different types
