### ISSUE TITLE
Unexpected vsda not found

### ISSUE THREAD

**Issue by yiliang114** [microsoft/vscode#198827]
it can be seen from #72885  that vsda should not be revealed in the oss version, but it is loaded, although the file cannot be found.

![image](https://github.com/microsoft/vscode/assets/11473889/e71f8b9c-6dff-4efe-ad97-32a90d260473)

Reproduction steps
1. git clone https://github.com/microsoft/vscode.git 
2. use  `cmd + shift + b` to build vscode
3. use `./scripts/code-server.sh` to start vscode
4. The application can load normally, but there is an error reported above.

Version: 1.82.0-dev
Commit: a6a6971875d9a2f8de30
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Embedder: server-distro

**Comment by yiliang114** [comment]
The error reporting comes from this pr https://github.com/microsoft/vscode/pull/182815, which implements the sign Service on the web side. Or does Microsoft decide to provide the vsda package to the oss version?

**Comment by connor4312** [comment]
That error is expected in the OSS version.
