### ISSUE TITLE
 matching syntax highlight in split window  wont clear 

### ISSUE THREAD

**Issue by jesussmile** [microsoft/vscode#198866]
There is a strange issue in vs code when i split the window, and click on any code or syntax , it will highlight similar code/syntax but the highlig

ht is persistent, it wont go away, it works fine in the first window but when it gets split to the right it doesnt work if i click anywhere else in the window,

in the left side the currentCrew is highlighted now, it just wont clear.

sys info
Version: 1.84.2 (Universal)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:33.687Z (1 wk ago)
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 21.6.0

<img width="1680" alt="Screen Shot 2023-11-22 at 9 42 52 AM" src="https://github.com/microsoft/vscode/assets/11044978/342dddb1-147a-4fe4-80ba-ce45b68b4dcf">

**Comment by lszomoru** [comment]
@jrieken, could you help with triaging this issue? Thanks!
