### ISSUE TITLE
Aux window: switching to main window sometimes hides/shows terminal

### ISSUE THREAD

**Issue by msukkari** [microsoft/vscode#198870]
Type: <b>Bug</b>

Happens infrequently and seemingly randomly

Repro steps:
- Open main window with terminal and floating window
- Switch between floating window and main window
- Observe that sometimes the terminal window is hidden (if it was in view) or that the terminal appears and is in focus (if it was not in view)

https://github.com/microsoft/vscode/assets/22405198/bfc6b1cf-fc9f-4865-a360-adee91837d0a

VS Code version: Code - Insiders 1.85.0-insider (05cd2640ec8a106a4ee99cb38e6ee34fbec04f11, 2023-11-21T05:35:09.651Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.0-1026-aws

<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.324.0
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
vim|vsc|1.27.0
copilot|Git|1.138.563
copilot-chat|Git|0.11.2023112201
autopep8|ms-|2023.9.13201008
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
jupyter|ms-|2023.11.1003211000
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
vscode-github-issue-notebooks|ms-|0.0.130

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
2i9eh265:30646982
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
synctok:30869157
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30859868
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by bpasero** [comment]
@msukkari does this still happen?
