### ISSUE TITLE
Exclude some directories from workspace symbol search (Symbol in workspace)

### ISSUE THREAD

**Issue by codeAbinash** [microsoft/vscode#198991]
To exclude some directories(eg. node_modules) from Workspace symbol search (Symbol in workspace).

![Screenshot 2023-11-24 120923](https://github.com/microsoft/vscode/assets/83173549/1af83d47-60be-4dd0-85cc-1629bddd029a)

Currently it searches all the files in workspace.

**Comment by gjsjohnmurray** [comment]
Does the `typescript.workspaceSymbols.excludeLibrarySymbols` setting help you?

**Comment by codeAbinash** [comment]
I tried but it did not work.

![Screenshot 2023-11-25 130324](https://github.com/microsoft/vscode/assets/83173549/e5c2b66e-9c14-43c3-8bb2-37841d5da224)

**Comment by mjbvz** [comment]
Try the current VS Code insiders build or VS Code 1.85 once it is released
