### ISSUE TITLE
First load of the GHPRI view renders empty for ~3 seconds

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#198951]
We could make it much snappier by immediately rendering the sections:

https://github.com/microsoft/vscode-pull-request-github/assets/22350/3324ecdc-4054-4691-a5ef-70d6085ef320

**Comment by joaomoreno** [comment]
@alexr00 I suggest you do a first call from the GHPRI view in which you assume all nodes are empty. And then a second call where you go ahead and load what needs loading. Even if this was a core tree, this would be my recommendation.

**Comment by alexr00** [comment]
@joaomoreno, I'll make that change. However, there are probably other extensions out there that make a similar assumption and would benefit from changing the built-in behavior.

**Comment by joaomoreno** [comment]
It's tricky. Changing the default behavior means there's no fine-grained control any more of how things work. Right now the tree gives users the most powerful API: everything can be done, and users can tailor the API calls to the experience. If, on the other hand, the tree decides to render tree nodes as they get resolved, there's no turning back.
