### ISSUE TITLE
Vscode don't display git branches in Chinese mode

### ISSUE THREAD

**Issue by yysc622** [microsoft/vscode#198925]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.2
- OS Version: Windows 11

Steps to Reproduce:

1. F1->config display language->中文简体
2. restart vscode
3. as shown, the git branch and 'source control checkout, source control sync' are gone

![image](https://github.com/microsoft/vscode/assets/77236294/3f56d062-d936-4b7d-8218-6d7fe7506f4b)

![image](https://github.com/microsoft/vscode/assets/77236294/1e29477e-00fe-4d61-929d-a9728f3ce573)

**Comment by creeper0167** [comment]
If it's possible I would be glad to give it a try.

**Comment by Alan3344** [comment]
The latest version has solved it

Version: 1.86.0 (user setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621

ssh is a virtual machine [Multipass](https://multipass.run/install)
Tested `main` branch and `master` branch Passed

<img width="1280" alt="image_2024-02-23_20-01-29" src="https://github.com/microsoft/vscode/assets/60773912/b13f416e-0bc3-46f3-aace-ae4457e9814e">
<img width="1280" alt="image_2024-02-23_20-04-16" src="https://github.com/microsoft/vscode/assets/60773912/6b03789c-4761-47d0-bf7b-675acac5ba97">
<img width="1280" alt="image_2024-02-23_20-06-10" src="https://github.com/microsoft/vscode/assets/60773912/903fcf03-2b17-44f2-b1b7-645e3742a42f">

Windows 11
<img width="1061" alt="image_2024-02-23_20-07-08" src="https://github.com/microsoft/vscode/assets/60773912/ea28df08-08a5-4e61-b1e2-efdb2948a650">

**Comment by lszomoru** [comment]
Closing the issue based on the most recent comment.
