### ISSUE TITLE
Entering ' character when commenting code results in double ''

### ISSUE THREAD

**Issue by swigstrom** [Microsoft/vscode#19893]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 15.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|emoji|Perkovec|0.0.3|
|python|donjayamanne|0.5.6|
|Theme-monokai-best|gerane|0.0.2|
|MagicPython|magicstack|1.0.3|

---

Steps to Reproduce:

1. Comment a line of code
2. Press the ' button on the keyboard (2 will show up where it should only be 1 when commenting code > 2 should only show up when writing actual code)

**Comment by alexandrudima** [comment]
@swigstrom Since this is all language dependent can you let us know what language you're using. A code snippet would also be very helpful. Thanks!

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.
