### ISSUE TITLE
Test Coverage UX: Use a less heavy icon on "View Test Coverage" line

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#198936]
I suggest `pie-chart`

![image](https://github.com/microsoft/vscode/assets/6726799/22a6845f-adce-4e8f-ab45-0d9fe852de51)

instead of the current one:

![image](https://github.com/microsoft/vscode/assets/6726799/236119ca-ce78-4d63-9bf2-15519c75cd49)

**Comment by connor4312** [comment]
I have a request out to our design team for a dedicated icon, will duplicate into that :) https://github.com/microsoft/vscode-codicons/issues/205
