### ISSUE TITLE
Aux window: debug toolbar should be visible on the active window

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#198913]
So that you know that you are debugging.

//cc @roblourens @connor4312

**Comment by connor4312** [comment]
I'm not sure on this, personally I would find it kind of annoying to have the toolbar on all windows. Maybe it's a setting, or can be dragged between windows? (Is there reusable cross-window drag logic yet?)

**Comment by bpasero** [comment]
To clarify: not visible on all windows at the same time, but visible on the window that has focus maybe? Otherwise, it will be quite hard to step through a file using mouse in floating windows?

**Comment by connor4312** [comment]
I think having it appear in the active window (when in floating mode) is good.

**Comment by bpasero** [comment]
Thanks!!!

**Comment by connor4312** [comment]
Verification:

- Start debugging, and drag an editor out to an aux window
- Make sure the debug toolbar appears on whichever window has focus
- The debug toolbar should reappear in the same place per-window as you focus it
