### ISSUE TITLE
workbench.action.terminal.toggleTerminal does more than "Toggle Terminal"

### ISSUE THREAD

**Issue by DanKaplanSES** [microsoft/vscode#198906]
Keyword: Toggle Terminal, ctrl + `, Keyboard shortcuts

1. Close the terminal
2. Click on an editor tab to focus it
3. Press <kbd>ctrl</kbd> + <kbd>`</kbd> (i.e., run the "workbench.action.terminal.toggleTerminal" command)
4. The terminal is opened
5. Press <kbd>ctrl</kbd> + <kbd>`</kbd>
6. The terminal is closed (so far so good)
3. Press <kbd>ctrl</kbd> + <kbd>`</kbd>
4. The terminal is opened
5. Click on an editor tab to focus it
3. Press <kbd>ctrl</kbd> + <kbd>`</kbd>

Expected: The terminal is closed
Actual: The terminal is given focus and remains open

I noticed other `View: Toggle <x>` behave the same way, so this might be working as expected, but it precludes a keyboard shortcut for `View: Focus <x>` (or would clash with it if there was a desire to create a `View: Focus <x>` in the future).

---

Originally I was going to create this as a bug because I thought that the "When `terminal.active`" had something to do with this behavior, but as far as I can tell, there's no difference in behavior with or without `terminal.active`. Maybe _this_ is a legitimate bug? What should "When `terminal.active`" do?

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (23.43GB free)|
|Process Argv|--disable-extensions --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by NasifAhmed** [comment]
I think simply, the `ctrl` + `` ` ``  shortcut closes the terminal only when `terminal.active` is active which means the terminal is in focus.
If `terminal.active` is not active and the editor is not in focus(like you did in step 9), then at first the terminal gets focus and then pressing the shortcut again works and the terminal closes properly as expected.

The expected closing terminal behavior can be done with `ctrl`+`j` shortcut. Which toggles the panel visibility.

**Comment by DanKaplanSES** [comment]
> I think simply, the `ctrl` + `` ` `` shortcut closes the terminal only when `terminal.active` is active which means the terminal is in focus. 
I made the same assumption. Remove it and see if it makes a difference for you. It didn't for me.

**Comment by NasifAhmed** [comment]
> > I think simply, the `ctrl` + `` ` `` shortcut closes the terminal only when `terminal.active` is active which means the terminal is in focus.
> 
> I made the same assumption. Remove it and see if it makes a difference for you. It didn't for me.

Yes you are right. The `workbench.action.terminal.toggleTerminal` command always focuses the terminal first if it is not in focus. Doesn't matter if it has the **When** : `terminal.active` or not.

I tried without anything in **When** expression and then tried adding `editorFocus || terminal.active`, still same behavior. Nothing changed.

**Comment by meganrogge** [comment]
I believe this is working as designed. @sandy081 do you agree?

When I remove the `when` expression, the keybinding does not work.

**Comment by DanKaplanSES** [comment]
> I believe this is working as designed. @sandy081 do you agree?
@meganrogge I intended this issue to be a feature request not a bug report. Did I use the wrong template?

> When I remove the `when` expression, the keybinding does not work.
It works exactly the same way when I remove it. Can you provide the steps you are taking to test this?

**Comment by sandy081** [comment]
> I believe this is working as designed. @sandy081 do you agree?

Yes. This is general toggle behaviour for panels.

CC @sbatten

**Comment by DanKaplanSES** [comment]
@meganrogge / @sandy081 Sorry. I don't think my last reply was fleshed out well. I said:

> I intended this issue to be a feature request not a bug report. Did I use the wrong template?

Here's what I meant: even if it's by design, I'm requesting a change to this behavior. I'm under the impression this issue was closed because "it's not a bug"—at least, that's what I inferred from the comment before its closure. If that's the case, I'm hoping this can be reopened as something to consider changing. But before making up your mind, I should probably provide motivation for the feature request: 

It would improve accessibility for those that use dictation software and utter phrases to perform multiple steps. Since `workbench.action.terminal.toggleTerminal` behaves differently depending on the current focus and/or if the terminal is already open, "tricks" have to be used to make the script idempotent.

As an example, let's say you want the phrase, "Run Test" to type `npm run test\n` on the terminal. Well, the external software would need to deal with whether the terminal is already in focus. 

#### If the terminal is already focused:
  1. Type `npm run test\n`
#### If the terminal is hidden or _not_ focused:
  1.  Execute `workbench.action.terminal.toggleTerminal` to focus the terminal
  2.  Type `npm run test\n`

Here's the problem: dictation software is external to Visual Studio code, so it doesn't know if the terminal is already focused. If you follow the wrong steps, you'll be typing `npm run test\n` into the editor instead of the terminal; the script is not idempotent. 

There is a workaround, but as I mentioned above, it's more of a "trick." 

1. Execute `workbench.action.terminal.killAll`
   * If the terminal is already focused: this will "hide" the window.
   * If the terminal is hidden or _not_ focused: this will have no effect or "hide" the window, respectively.
1. Now Visual Studio code is in a predictable state: the terminal is "hidden." 
1. Execute `workbench.action.terminal.toggleTerminal` to focus the terminal
1. Type `npm run test\n`

I call this a trick because if `workbench.action.terminal.killAll` didn't exist, I'm not sure how else it could be done.

Back to what I was requesting: instead of `workbench.action.terminal.toggleTerminal` focusing _or_ toggling the terminal, make these separate commands. `workbench.action.terminal.toggleTerminal` will only toggle the terminal, and something like `workbench.action.terminal.focusTerminal` will only focus the terminal (even if it's currently "hidden"). 

If `workbench.action.terminal.focusTerminal` existed, the above trick could be written like this instead:
1. Execute `workbench.action.terminal.focusTerminal`
   * If the terminal is already focused: this will do nothing.
   * If the terminal is hidden or _not_ focused: this will focus it, regardless.
1. Type `npm run test\n`

That's less steps and a more straightforward script. Now, having said alllll that, I have a feeling there is an easier fix: make `terminal.active` have an effect on `workbench.action.terminal.toggleTerminal`. 

@meganrogge says,

> When I remove the `when` expression, the keybinding does not work.

I haven't experienced that: for me it works the same with or without that `when` expression. And when I change the `when` expression to `!terminal.active`, the keybinding doesn't do anything, regardless of what's focused. Maybe I don't know what "active" means in this context? Anyway, if this sounds like a better route, let me know and I'll create a bug report.

**Comment by meganrogge** [comment]
I am not clear on what `terminal.active` does. Maybe @sandy081 can clarify that as it's added by the views service.

There was a `window.title` property added recently of `focusedView`, which indicates whether or not the terminal is currently focused. Does that help you?

Also, we have a command, `Terminal: Focus Terminal` that will always focus the terminal regardless of whether it's already focused or hidden. I think that is preferable to the kill all and toggle sequence you're currently doing?

**Comment by DanKaplanSES** [comment]
> Thank you for the additional information.
Any time. Thank you for replying, and sorry for the brain dump.

> There was a `window.title` property added recently of `focusedView`, which indicates whether or not the terminal is currently focused. Does that help you?

Yeah, actually it could! Dictation software has the ability to read the window title. I've already modified `window.title` in the past. That's an extremely useful setting for those who use dictation software to code.

> Also, we have a command, `Terminal: Focus Terminal` that will always focus the terminal regardless of whether it's already focused or hidden. I think that is preferable to the kill all and toggle sequence you're currently doing?

Definitely. I'm not sure how I missed this. I cleared out the `when` condition and now it works exactly the way I want. (For future readers, it also creates new terminals after they are all killed.) 

I don't think there is a reason to reopen this issue anymore, but like you, I am not clear on what `terminal.active` does.

Thanks for all the help!

**Comment by DanKaplanSES** [comment]
@sandy081  Can you define what active means?

**Comment by sandy081** [comment]
Active is like enabled that implies that a view is registered but not enabled yet.
