### ISSUE TITLE
vscode window stucked in remote destoptop sometimes

### ISSUE THREAD

**Issue by 751620780** [microsoft/vscode#198993]
Does this issue occur when all extensions are disabled?: Yes/No

VS Code Version: latest
OS Version: Windows 10 10.0.19045.2604
Steps to Reproduce:

There are two Windows computers A and B, each with the latest version of VScode installed

use mstsc.exe remote to computer B on computer A, vscode window may stuck sometimes when write code. It will take approximately 2-5 seconds to recover, regardless of whether restart vscode or not.

thiss issue similar to issue #195102.

**Comment by 751620780** [comment]
network caused!

**Comment by 751620780** [comment]
The vscode window gets stuck after pressing a keyboard key, and the displayed content is refreshed only after switching applications. But the same phenomenon will occur whenever the button is pressed thereafter. Unless restarting vscode。
VS Code Version: 1.84.2(system setup)
OS Version: Windows 10 10.0.19045.2604

Refer to the gif below：
![1](https://github.com/microsoft/vscode/assets/29426293/029e9ffd-f834-4fd3-afef-029464922511)

**Comment by 751620780** [comment]
The usage scenario of the following gif image is that after remote access to this computer yesterday, I used vscode directly on this computer today. I found that vscode was also stuck at the beginning, and returned to normal after about a minute.

![2](https://github.com/microsoft/vscode/assets/29426293/465b2981-7c68-4d24-9b00-fc94bea38bcd)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/167556
