### ISSUE TITLE
Need delay setting for showing all Intellisense and popup windows

### ISSUE THREAD

**Issue by longtimedeveloper** [microsoft/vscode#198905]
Type: <b>Feature Request</b>

VSCode would have a MUCH better user experience if all Intellisense and related editing pop ups would have and honor delay setting.

It is SO distracting and frustrating to have to keep pressing the Escape key "all the time" to dismiss these popups.  95% of the time, we developers are just typing our code and do not need a popup every 5 seconds while typing.

PLEASE greatly improve the usability of the product.

Even with the below settings my editing experience is always poor because I have to keep pressing Escape just to see my code!

"editor.hover.delay": 500,
"editor.quickSuggestionsDelay": 2000,
"errorLens.delay": 3000,
"workbench.hover.delay": 1000,

This happens when I use VSCode for C#, Dart and Flutter

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by jrieken** [comment]
These settings will help you: editor.quickSuggestions and editor.suggestOnTriggerCharacters

**Comment by longtimedeveloper** [comment]
@jrieken this didn't help an did not address the request.

**Why did you close this?**

**Comment by longtimedeveloper** [comment]
this is NOT a question.  This is a feature request.

**Comment by BuiIdinger** [comment]
/open

Software Devloper
Contact if you have any questions
________________________________
