### ISSUE TITLE
Test Coverage UX: Indicate which run the coverage results are from

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#198934]
Type: <b>Feature Request</b>

1. Clone vscode-extension-samples
2. Open test-provider-sample, build it and run it.
3. Select Testing on Activity Bar.
4. Use "Run Tests" button on Test Explorer view's title bar.
5. Go to right-hand part of Test Results tab on Panel, and click "View Test Coverage"
6. Comment out failing test on line 4 of test.md
7. "Run Tests" again.

Test Results tab on Panel now correctly shows 2 runs, and Test Explorer shows the new results, but it's easy to miss that Test Coverage is still showing the results of the previous run.

Perhaps add the run timestamp to the view title, or on a row below it?

Or, only show this if the coverage results aren't from the latest run.

Related to this, should Test Coverage contents track Test Explorer, updating automatically when a new run occurs?

VS Code version: Code - Insiders 1.85.0-insider (ef71b038ad2518e32514b6cc3a4df9f94c096e65, 2023-11-23T05:36:37.890Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by connor4312** [comment]
> should Test Coverage contents track Test Explorer, updating automatically when a new run occurs?

Yea, after playing around with it I decided that this makes sense :)
