### ISSUE TITLE
Run active file

### ISSUE THREAD

**Issue by Glutey** [microsoft/vscode#198974]
Hello, 

This issue has appeared now after i have come to code on the platform after a short absence.

I used to be able to create or select an existing file and use the 'Terminal' tab at the top left to select 'Run Active File'.  This used to allow the code i had recently typed to execute fully on the terminal screen that would populate at the base of the VSCode screen.

I am no longer able to do this and unsure why. I had recently cleared a load of programs i no longer used from my computer and maybe that has affected it.  I went onto the 'Extensions'  tab and downloaded 'Python - pylance, environment and extension pack' thinking maybe this is what it was missing (i am currently coding in python and wish to continue learning).  

I repeated the 'Run Active File' but  the terminal would only display the file path and not execute the program as intended. 

I cant recall how exactly but i was then prompted by the program (i beleive i saw an orange ! mark on the bottom of the VSCode program that alerted me to the fact i had no set Inteperter in use on the Editor).

This alert stated that the python interpreter it recommends is from Microsoft Store... i clicked this and downloaded the suggestion.

With this selected as the interpreter i tried to 'Run Active File' again from the 'Terminal' tab but I would get the same responses as before.

I have since downloaded Python from the offical site, installed it on  my computer and then copied its PATH to the VSCode interpreter (to replace the Microsoft Store PATH).

Now when i click 'Run Active File' a seperate IDLE opens (the one i downloaded) and the code executes from there..

I would rather the old way of running an active file to be available again and could really use some help solving the issue.

Thanks in advance for any advice.

**Comment by ulugbekna** [comment]
This seems to be a python extension issue. Please, open an issue with them here - https://github.com/Microsoft/vscode-python/issues
