### ISSUE TITLE
Test Coverage UX: Clear All Results leaves Test Coverage view populated

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#198933]
Type: <b>Bug</b>

1. Clone vscode-extension-samples
2. Open test-provider-sample, build it and run it.
3. Select Testing on Activity Bar.
4. Use "Run Tests" button on Test Explorer view's title bar.
5. Go to right-hand part of Test Results tab on Panel, and click "View Test Coverage"

Test Coverage view appears under Test Explorer on side bar :+1:

6. On Test Results toolbar on panel click "Clear All Results".

Test Explorer view clears :+1: but Test Coverage doesn't. ? :bug:?

VS Code version: Code - Insiders 1.85.0-insider (ef71b038ad2518e32514b6cc3a4df9f94c096e65, 2023-11-23T05:36:37.890Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by connor4312** [comment]
I fixed this in my results cleanup
