### ISSUE TITLE
Language specific settings: Unable to set tab size per language

### ISSUE THREAD

**Issue by tejasjadhav** [Microsoft/vscode#19895]
Hey VSCode Team,

Firstly, thank you so much for this much awaited feature! However, it seems that the set of available settings per language is limited. I wanted to set `editor.tabSize` for `javascript` as `2`, which is `4` as the default. But, it doesn't work and my tab size is still `4` for JS files.

- VSCode Version: 1.9
- OS Version: Ubuntu 16.04 64-bit

Steps to Reproduce:

1. Open *User settings*.
2. Add the below setting,
```json
"[javascript]": {
    "editor.tabSize": 2
}
```

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/19511
