### ISSUE TITLE
node2 debugging - watches return 'not available' after stepping

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#19897]
Fixing this for 1.9.1 since the fix is relatively simple and it's very annoying.

**Comment by joaomoreno** [comment]
@roblourens Can you elaborate on the issue, impact and whether there is a workaround without the fix?

**Comment by roblourens** [comment]
Sure, the bug is
- Add a watch
- Hit a breakpoint, the watch shows the correct value
- Step
- The watch shows "not available" here and after every step, almost every time

This makes watches not very useful, and there is no workaround.

It was caused by a workaround to a chrome/node bug which I just had to take a little further so I consider it low risk.

**Comment by joaomoreno** [comment]
Makes sense, let's keep it in for January.

**Comment by joaomoreno** [comment]
I'll verify this.
