### ISSUE TITLE
TypeScript Method Autocomplete: Broken Edit

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#198958]
![Image](https://github.com/microsoft/vscode/assets/2931520/f90805f5-d30b-467d-bab7-9a7e662238c6)

I'm in this state:

![Image](https://github.com/microsoft/vscode/assets/2931520/612f738f-40ad-48cf-ba25-c3e8bfcb042a)

and press enter.

**Comment by mjbvz** [comment]
Please share example code and steps to reproduce the issue

**Comment by hediet** [comment]
I cannot reproduce anymore. Maybe the typescript language server got ouf of sync with VS Code edits?
Feel free to close.
