### ISSUE TITLE
Aux window: provide more ways of entering into aux windows

### ISSUE THREAD

**Issue by MrYuto** [microsoft/vscode#198994]
As the aux window support has reached a good point, Thanks to @ bpasero for his amazing work, I think the public release is getting closer and closer. Although users can open a new aux window with a command or from the tab context menu, more user flows can be considered. I'll list some possible places where users might want to open a new window.

### Open a new window:
![image](https://github.com/microsoft/vscode/assets/75252297/b6114898-d6a7-417b-8f43-365ea7216592)
### Open a file in a new window from quick open:
![image](https://github.com/microsoft/vscode/assets/75252297/81f703a7-1837-4a51-97de-fe0559878dc2)
### Open a file in a new window from the explorer:
![image](https://github.com/microsoft/vscode/assets/75252297/928022d4-e7a4-4b76-ad1c-42b2c4c7dd7f)
### Open a file in a new window from a link:
![image](https://github.com/microsoft/vscode/assets/75252297/49bbcb8a-05cc-4d92-b3cc-20084c706407)
#### Move into a new window from the tab context menu
This is already implanted but maybe considering changing the position?! For example, putting in keep open, pin section

**Comment by bpasero** [comment]
Thanks for sharing this analysis and suggestions. I think modifier keys are heavily overloaded already for opening things to the side or pinned, I am not sure we can find a modifier that would work for opening a new window. 

Here are the entry points today:
* drag and drop (both tabs and tab container)
* right click tab context menu to move to new window
* command palette (move / copy editor, editor group)
* top level main menu entries

We can expand to more locations where it makes sense and maybe based on more feedback.

**Comment by hbons** [comment]
how about also having a context menu on section/view headers with "Float"? (this is the verb on VS Win, would be good to match it)

**Comment by bpasero** [comment]
So far I have stayed away from using "float" or "detached" terms:

<img width="721" alt="image" src="https://github.com/microsoft/vscode/assets/900690/d749904f-3a31-43a7-adfe-45d2c0a04b83">

Since only editors can be moved to new windows currently, I am not sure to which section/view header to add this?

**Comment by stephenfrost** [comment]
I hope this is an OK place to make comment (could not find it mentioned already in aux windows issues):
Currently in insiders, the tab with focus will be the window moved or copied into new window via context menu, even when I right-click on a different tab. I can understand the user NOT wanting right-click of non-focused tab to give it focus, but intuitively, it seems you'd want the context menu to act on the tab you right-clicked, regardless if the tab is the one with focus or not.

**Comment by bpasero** [comment]
@stephenfrost great finding, could you open a new issue for this? thank for testing!
