### ISSUE TITLE
Debugger moved to awkward place cannot access the buttons.

### ISSUE THREAD

**Issue by Aswin5010** [Microsoft/vscode#19899]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-node-readme|bengreenier|1.0.7|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-sql-connect|dvdbrink|0.2.1|
|LogFileHighlighter|emilast|1.0.1|
|NodeAssertionSnippets|jaymorrow|0.1.0|
|docthis|joelday|0.3.10|
|vscode-mssql|sanagama|0.0.4|
|addDocComments|stevencl|0.0.8|

---
![image](https://cloud.githubusercontent.com/assets/11367293/22615722/fa2c1490-eac0-11e6-8ebc-7a540b5bf296.png)

Steps to Reproduce:

1. Updated to V1.9.0
2. Pressed f5 to start/run node app.

**Comment by isidorn** [comment]
Can not reproduce this behavior. Tried win10 but can not move the debug toolbar past the left border.
To get around this ugly corner case, F1 > toggle developer tools > application > local storage > file then find `debug.actionswidgetposition` entry and delete it.

**Comment by vaispiday** [comment]
This could be easily reproducible , make sure you have split monitor , basically two monitors and then now move the debugger to the left corner till it hide the grip indicator on your secondary monitor.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/20298
