### ISSUE TITLE
Can no longer copy from previous git diff

### ISSUE THREAD

**Issue by Ghost---Shadow** [microsoft/vscode#198943]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Produce any git diff
2. Try to copy the stuff in the red

![Screenshot 2023-11-23 074629](https://github.com/microsoft/vscode/assets/7743925/bc309d99-42a0-4538-8941-0900340f62c1)

**Comment by gjsjohnmurray** [comment]
Is this #8226?

Can you use the context menu on the deleted lines?

Can you switch out of inline view?

Your title says "no longer". Did something change for you?

**Comment by Ghost---Shadow** [comment]
Oh sorry. I never used the inline diff feature before. I use the side by side diff.

It seems in the new update, if I try to open diff with another window on the side, it automatically switches to inline diff.

Where do I find the settings to disable automatically switch to inline diff from side by side diff?

**Comment by gjsjohnmurray** [comment]
Is the `diffEditor.useInlineViewWhenSpaceIsLimited` setting relevant?

**Comment by gjsjohnmurray** [comment]
Or `diffEditor.renderSideBySideInlineBreakpoint`?

**Comment by Ghost---Shadow** [comment]
That fixed it, you can close the ticket
