### ISSUE TITLE
Install Extension: order on extension list

### ISSUE THREAD

**Issue by Lajt** [Microsoft/vscode#199]
When you try to install yeoman generator with:
`ext install yo`
yeoman generator is last on the list but should be first
`yo` is name of package
with hundreds of packages it will be pain to find.
I know you can install it with:
`ext install yeoman` 
but shouldn't it prioritize package name somehow?

![image](http://i.imgur.com/UAmLpOq.jpg)

**Comment by joaomoreno** [comment]
:+1:

**Comment by Tyriar** [comment]
Seems fixed now 
![image](https://cloud.githubusercontent.com/assets/2193314/15624365/14334f18-243b-11e6-8441-29331bf15baa.png)
