### ISSUE TITLE
"select hightlights" bug on delete

### ISSUE THREAD

**Issue by iqbal98** [Microsoft/vscode#19900]
- VSCode Version: latest
- OS Version: linux 4.8.0

Steps to Reproduce:

1. select a single quote or 'highlight it'
2. <kbd>ctrl</kbd>+<kbd>L</kbd>
3. <kbd>del</kbd>

I was modifying a constants file in php and then I wanted to **replace all single quotes for double quotes**.

![bug](https://cloud.githubusercontent.com/assets/21296115/22615746/c4753a0e-ea69-11e6-9797-58b1d7b56e63.gif)

**Comment by alexandrudima** [comment]
@iqbal98 I cannot reproduce. Can you reproduce when running without extensions `code --disable-extensions` ?

![19900](https://cloud.githubusercontent.com/assets/5047891/25441895/cab4efac-2aa3-11e7-8fd8-44c2d1a23cfc.gif)

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.
