### ISSUE TITLE
VSCode Continuously Crashing with Error Code 139

### ISSUE THREAD

**Issue by johnwsmithv** [microsoft/vscode#199060]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.84.2
- OS Version: RedHat 9.2

Steps to Reproduce:

![image](https://github.com/microsoft/vscode/assets/37300578/ab5f5c7a-124e-4e9b-bae6-ee8a70bfa821)

I'm not totally sure how to reproduce it, but I have been working on a pretty massive Java project for Grad School and have been working with a lot of different terminals - so I have a Window for the terminals and another Window for the Java project itself. Within the last couple of weeks, I have been continuously getting the error code 139 with my Windows crashing; even after disabling all of the extensions I still get the error.

Any ideas what might be going on?

**Comment by meganrogge** [comment]
Exit code 139 typically indicates a segmentation fault. This can occur for a variety of reasons, such as when a program tries to access memory that it doesn't have permission to access, or when it tries to execute data as if it were code.

Can you reproduce this in an external terminal?
