### ISSUE TITLE
Initial cursor location in terminal is wrong

### ISSUE THREAD

**Issue by tleunen** [Microsoft/vscode#19901]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|vscode-css-modules|clinyong|0.1.2|
|vscode-eslint|dbaeumer|1.2.2|
|docthis|joelday|0.3.10|
|debugger-for-chrome|msjsdiag|2.5.1|
|stylelint|shinnn|0.22.0|
|vscode-react-native|vsmobile|0.2.5|
|ReactSnippets|xabikos|1.2.0|

Steps to Reproduce:

1. Setup custom terminal styles (with zsh for example)
2. Have characters on the right side of the current line (eg: git status)
3. Notice the issue

![kapture 2017-02-03 at 23 36 43](https://cloud.githubusercontent.com/assets/1972567/22615742/a2039dee-ea69-11e6-87b2-f6effd54385f.gif)

The issue is not present when there's no character on the right side of the line.
![screen shot 2017-02-03 at 11 39 10 pm](https://cloud.githubusercontent.com/assets/1972567/22615769/fb9f5154-ea69-11e6-9bb4-796812162b97.jpg)

**Comment by Tyriar** [comment]
@tleunen would you be able to provide more details about your configuration (what plugins, what do they do) and report this upstream? https://github.com/sourcelair/xterm.js/issues/new
