### ISSUE TITLE
File drop should insert file paths

### ISSUE THREAD

**Issue by userFortyTwo** [microsoft/vscode#199013]
Type: <b>Feature Request</b>

When either dragging a file from the project explorer or dragging a tab, then dropping the item into an external application, a file URL starting with "file://" will be pasted into that app.

I frequently like to drop files onto the command line, but will receive an error message complaining the file wouldn't exist.

I am quite sceptical about whether this the behavior most people prefer and would very much rather it pasted regular file paths instead.

EDIT: I just noticed that this depends on the external app you're using. Notepad++, or TextEdit and Terminal on Mac will paste a file path. However, the command prompt, Git Bash, or PowerShell do not. Is there a way for VS Code to work around this?

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by meganrogge** [comment]
Can you clarify what you're dragging from and to? Dragging from the explorer or from an editor tab into the terminal pastes the file path for me.

**Comment by userFortyTwo** [comment]
![fileurl](https://github.com/microsoft/vscode/assets/85737538/2c7aba46-507f-49ee-84b5-5ef91e8a586a)

**Comment by lramos15** [comment]
This is up to the application and not something we can fix

**Comment by userFortyTwo** [comment]
@lramos15: I am really not sure if this is true. Please consider the information provided here: #200150.
