### ISSUE TITLE
why？

### ISSUE THREAD

**Issue by FE-Franck** [Microsoft/vscode#19903]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-css-formatter|aeschli|0.0.2|
|vscode-theme-onedark|akamud|0.2.14|
|project-manager|alefragnani|0.12.2|
|vscode-color|anseki|0.2.2|
|typings-installer|benjaminromano|0.2.0|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-dash|deerawan|1.3.0|
|githistory|donjayamanne|0.1.4|
|python|donjayamanne|0.4.2|
|xml|DotJoshJohnson|1.7.0|
|tslint|eg2|0.8.1|
|Angular1|johnpapa|0.1.16|
|Angular2|johnpapa|1.0.2|
|vue|liuji-jim|0.1.5|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|prettify-json|mohsen1|0.0.3|
|jscs-formatter|moose87|0.1.1|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.6.2|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|Theme-MaterialKit|ms-vscode|0.1.1|
|Theme-TomorrowKit|ms-vscode|0.1.3|
|debugger-for-chrome|msjsdiag|2.4.2|
|theme-hackershaze|Nuuf|1.3.1|
|vscode-icons|robertohuertasm|6.0.0|
|sass-indented|robinbentley|1.3.0|
|stylelint|shinnn|0.17.3|
|cordova-tools|vsmobile|1.2.5|
|JavaScriptSnippets|xabikos|1.2.0|
|ReactSnippets|xabikos|1.2.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
why not?

@FE-Franck Can you be more specific about the issue you are facing?
