### ISSUE TITLE
Support Extension Unloading

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#199026]
It would be amazing if it would be possible to unload extensions, such that a newer version could be loaded again.
Extensions would have to opt in for this.

**Comment by sandy081** [comment]
Can you please elaborate> What do you mean by unloading an extension and is it a user feature?

**Comment by hediet** [comment]
Sorry for the unclear issue description.

I have three scenarios in mind where "extension unloading" could be useful, and what the scope of it could be:
* Allowing extensions to update/uninstall without having to reload VS Code
   * Updating an extension means unloading/uninstalling the old version (if loaded) and installing/loading the new version
   * Only some extensions would support this at all (probably with some flickering when they show a webview) and even less seamless (e.g. copilot could be unloaded/loaded without any noticable flickering)
* Hot-reloading extensions during development
   * By watching the folder and unloading/reloading the extension on file change.
* This would be a first step for "workspace extensions"
   * Workspace extensions have a different distribution mechanism than marketplace extensions - their "updates" are fetched through `git pull` and some background watch task. I think for workspace extensions it is quite important that the version of the currently running workspace extension matches the currently checked out code-base.
   * Reloading VS Code after every git pull would be disrupting, so hot-reloading workspace extension would a huge game changer.

This is more a brainstorming issue and I wanted to write down my idea.
