### ISSUE TITLE
Duplicated command on <tab> in the terminal

### ISSUE THREAD

**Issue by tleunen** [Microsoft/vscode#19902]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|vscode-css-modules|clinyong|0.1.2|
|vscode-eslint|dbaeumer|1.2.2|
|docthis|joelday|0.3.10|
|debugger-for-chrome|msjsdiag|2.5.1|
|stylelint|shinnn|0.22.0|
|vscode-react-native|vsmobile|0.2.5|
|ReactSnippets|xabikos|1.2.0|

Steps to Reproduce:

1. Open terminal (using zsh in my case)
2. write `cd <tab>` or `cd sth<tab>` (where sth finds no match)
3. Notice the duplicate `cd` and the first cd cannot actually be removed, it's only visual.

_Note:_ this also occurs in non git directory

![kapture 2017-02-03 at 23 41 07](https://cloud.githubusercontent.com/assets/1972567/22615799/d0899b04-ea6a-11e6-830c-eb0294b91fd1.gif)

**Comment by kaiwood** [comment]
I've seen this effect in the past a couple of times, but couldn't come up with reproducible steps. Thought it was gone after the latest terminal overhaul. Still can't reproduce it with simple tabbing, hmm.

@tleunen What ZSH_THEME are you using, one of the built-ins?

**Comment by tleunen** [comment]
I'm using zprezto with this https://gist.github.com/Veraticus/1b30a6b6cbe8dae57e9f

**Comment by Tyriar** [comment]
@tleunen What's causing the `--local directory --` and `-- no matched found --` messages?

**Comment by tleunen** [comment]
It's the auto completion, when I hit <tab>

**Comment by Tyriar** [comment]
@tleunen whatever that is doing is causing the problem, I need to know exactly what it is and what it's doing to investigate. The zprezto thing you linked doesn't appear to have `-- local directory --` anywhere within the file.

**Comment by tleunen** [comment]
This is probably the default git plugin from zprezto then. I don't have fancy thing on my zsh.

Here's the full zprezto config that I use: https://gist.github.com/tleunen/f18eb18c3ed9249669c97ca836cc60a8

**Comment by Tyriar** [comment]
Probably related to this https://github.com/sorin-ionescu/prezto/blob/4f19700919c8ebbaf75755fc0d03716d13183f49/modules/completion/init.zsh#L58

**Comment by tleunen** [comment]
I tested again with the recent 1.10.1 and the issue is resolved. So closing this issue.
Thanks!
