### ISSUE TITLE
TypeScript 5 times in the middle

### ISSUE THREAD

**Issue by xieling999** [Microsoft/vscode#19904]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|project-manager|alefragnani|0.13.2|
|vscode-database|bajdzis|1.2.0|
|plsql|casian|0.0.2|
|npm-intellisense|christian-kohler|1.2.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.5|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.0.33|
|vscode-great-icons|emmanuelbeziat|1.1.43|
|php-debug|felixfbecker|1.10.0|
|auto-close-tag|formulahendry|0.3.9|
|auto-rename-tag|formulahendry|0.0.11|
|beautify|HookyQR|0.7.3|
|docthis|joelday|0.3.10|
|code-beautifier|michelemelluso|1.6.2|
|mssql|ms-mssql|0.2.1|
|vscode-icons|robertohuertasm|7.1.2|

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@xieling999 can you share more details of the issue you see with TypeScript?

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this. 

Please check the `C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib` path. There should be a `tsserver.js` file there. We've seen a few reports of overenthusiastic anti-virus software is deleting these files however.

If the file is missing, you can [use a custom typescript install with `typescript.tsdk`](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). You can also reinstall vscode to restore the files. Be sure to exclude the typescript directory from antivirus to prevent this from happening again. Our official downloads ship the standard npm typescript package
