### ISSUE TITLE
Not all onCancellationRequested listeners are called for a CancelablePromise

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#199068]
The CancelablePromise disposes its CancellationTokenSource inside a onCancellationRequested listener. That means that any other onCancellationRequested listeners that were added after that one won't be called, because the EventEmitter has been disposed. In practice that means that any listener that was added after an async step inside the callback function is not called.

This caused issues in chat, but the function is used in many places and I think it's likely that some of those are affected. My suggested fix is in https://github.com/microsoft/vscode/pull/199067 but I don't think this is safe to check in at the end of the iteration, so I will wait until December.

Looks like you guys have touched this code, lmk what you think: @hediet @jrieken 

Transferred from a private issue. Original issue discussion below

<details>
---

1. Ask a question such as "Explain recursion in detail to me"
2. Immediately hit cancel
3. 🐛 Watch the copilot chat log, you will see the request continues and even follow ups are computed even though no tokens are shown to the user.

---

This is a bit weird. Order of events is this:

- Call `createCancelablePromise` to get a token
- Attach some `onCancellationRequested` listeners to it, some after async steps
- Cancel the cancellable promise
- The cancellable promise disposes the token source
- The cancellation listeners that were added after an async step don't get called because the event emitter is disposed before it can call them

The last step is suspicious but I guess that's how EventEmitter works? And the cancellable promise seems like it's doing the right thing. https://github.com/microsoft/vscode/blob/5bcff70fe0889d90bddc63262e9fa1526e814278/src/vs/base/common/async.ts#L28-L32

I need to check that the same thing happens with a normal CancellationTokenSource because the logic is the same.

---

Still not sure of the right solution.

Essentially `createCancelablePromise` has a `onCancellationRequested` listener which disposes the `CancellationTokenSource`. Listeners that were added later than that first `onCancellationRequested` listener will not be called because the event emitter will be disposed in the middle of emitting, which is by design for EventEmitter. But there is no way to guarantee that all listeners have been called before disposing, besides something like

```ts
const subscription = source.token.onCancellationRequested(() => {
	reject(new CancellationError());
	timeout(0).then(() => {
		subscription.dispose();
		source.dispose();
	});
});
```

which doesn't seem nice

</details>

**Comment by hediet** [comment]
Disposables and leaks are tricky... Thanks for finding this!
Here is the PR that introduced this: https://github.com/microsoft/vscode/pull/127329
Ironic that I introduced leaks with the goal to reduce leaks...
