### ISSUE TITLE
Python test debugging falls back to default launch configuration after running custom `debug-test` configuration once

### ISSUE THREAD

**Issue by RLThomaz** [microsoft/vscode#199051]
Does this issue occur when all extensions are disabled?: Yes (keeping `Pylance`, `Python`, and `Remote-SSH` enabled)

- VS Code Version: 1.84.2
- OS Version: Mac OS X: 13.5.2 (Local) and Amazon Linux 2 (Remote)

Steps to Reproduce:

1.  Create a custom launch configuration to debug Python tests.

```
    "launch": {
        "version": "0.2.0",
        "configurations": [
			{
				"name": "Python: Debug Tests",
				"type": "python",
				"request": "launch",
				"program": "${file}",
				"purpose": [
					"debug-test"
				],
				"console": "internalConsole",
				"env": {
					"PYTEST_ADDOPTS": "--no-cov"
				},
				"justMyCode": false,
				"autoReload": {
					"enable": true
				},
			},
        ],
        "compounds": []
	},
```

2. Open any Python project that contains tests to run (or create anything simple using `pytest`).
3. Add a breakpoint inside the unit-test.
4. Debug the unit-test, either by right-clicking on the "Run button" next to the test, and selecting "Debug" or by clicking the "Debug" button on the "Tests" tab.
5. Watch as the breakpoint is reached, and continue running the test.
6. Repeat steps 3 to 5, but now watch the breakpoint being skipped.
7. Open the `DEBUG CONSOLE` and observe the windows available (see image below), there should be two: `Python: Debug Tests`, i.e., the name of our custom configuration, and `Debug Unit Test`, the default launch configuration in VSCode. 

![image](https://github.com/microsoft/vscode/assets/11475657/66b97fce-7e7d-4d84-8e13-74e9d5eb5137)

Anytime you modify anything on the custom launch configuration and debug the unit test again, it will reach the breakpoint once and only once.

I've followed https://code.visualstudio.com/docs/python/testing#_debug-tests to setup this launch configuration. I've searched the VSCode repo, and the only mention to `Debug Unit Test` is here: https://github.com/microsoft/vscode/blob/ed6dc7b6b38890e9cbca22561a71b3723902bf6b/.vscode/launch.json#L582

**Comment by roblourens** [comment]
This would be an issue for the python extension

**Comment by RLThomaz** [comment]
Thank you for pointing out I should investigate `vscode-python`. I actually debugged this and it's pointing me in the direction of this repository again (unless I'm missing something). Here are the breadcrumbs I'm following:

In the extension [vscode-python](https://github.com/microsoft/vscode-python/tree/eb96141dc8540f2b6838f7fab278a86481575ede), running (or debugging) a test will reach, at first, the following line:

https://github.com/microsoft/vscode-python/blob/eb96141dc8540f2b6838f7fab278a86481575ede/src/client/testing/testController/pytest/runner.ts#L120C20-L120C20

Then:

https://github.com/microsoft/vscode-python/blob/main/src/client/testing/common/debugLauncher.ts#L41C53-L41C53

And:

https://github.com/microsoft/vscode-python/blob/main/src/client/testing/common/debugLauncher.ts#L77C37-L77C37

Followed by:

https://github.com/microsoft/vscode-python/blob/main/src/client/testing/common/debugLauncher.ts#L117

Which finally reaches:

https://github.com/microsoft/vscode-python/blob/main/src/client/debugger/extension/configuration/launch.json/launchJsonReader.ts#L15C46-L15C46

Presumably, given the little I know about VSCode, `getConfiguration` is an API function that's found in this repo here:

https://github.com/microsoft/vscode/blob/578ad35313f41c4aeff777ab25bd3265c645ab34/src/vs/workbench/api/common/extHostConfiguration.ts#L157C18-L157C18

I couldn't debug this further, but I can explain my observations. When running the debugger for the first time, the call to `getConfiguration` will return the correct launch configuration found in my `.code-workspace` file (shown in the code-block in the original issue message). Looking at the variables panel, we can see that the first time `getConfiguration` is called, it returns everything correctly.

![image](https://github.com/microsoft/vscode/assets/11475657/ffdbc299-2b34-4d1f-9b05-7a0dd9c532d3)

However, the second time it's invoked, the field `purpose` is empty and some other fields show up:

![image](https://github.com/microsoft/vscode/assets/11475657/6dd6acd2-6e4c-4203-967c-93656e644417)

Therefore, I believe this issue belongs to this repository -- if not to another one other than `vscode-python`. I hope you find all this information useful.

**Comment by roblourens** [comment]
Thanks for trying to debug it, but this needs to be investigated by someone who understands what the python extension is trying to do here
