### ISSUE TITLE
There is no "run mode" for node debugging

### ISSUE THREAD

**Issue by zhouzhonghao** [Microsoft/vscode#19906]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.0.0
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. use vscode 1.9
2. the shortcut command+fn+f5 has no effect

**Comment by isidorn** [comment]
This works fine for me.
I believe what is happening in your case is that the default mac keybinding (turn voiceover on) is overlaping with the default keybinding to run a program. You can customise the keybinding for this action by preferences > keyboard shortucts and adding something like
You can also try running this action from the command palette by F1 > start without debugging

```json
{ "key": "cmd+f6",                "command": "workbench.action.debug.run",
                                     "when": "!inDebugMode" }
```

**Comment by zhouzhonghao** [comment]
OK, thanks. Turn off the shortcut for voiceover and restart the mac computer, then the problem solved.
