### ISSUE TITLE
feature: Save Editor tab group in Explorer and bring up those tab groups whenever needed

### ISSUE THREAD

**Issue by ashuvssut** [microsoft/vscode#199028]
I sometimes work on multiple feature branches at a time.
For each feature, I need certain editor tab to be opened up.

For details, lets take an example
- I have 2 feature branches F1, & F2
- when I am on F1, I opened 5 files in my editor.
- Now i want to work on F2. **Instead of closing all those 5 F1 editor tabs, I would like to save that editor tab group in my Explorer or somewhere.**
- Now after saving that editor group, I will close all 5 of them.
- i  can now start working on F2 with a clean editor space. I will open (say) 7 editor tabs for working on F2
- Now if I want to switch to F1, I will save my current 7 editor tabs into a group. 
- Now I will open the Explorer again to bring up my saved F1 tab group

**Comment by gjsjohnmurray** [comment]
Maybe what you need is #35307
