### ISSUE TITLE
Test: Linux client bits

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#199045]
Refs: https://github.com/microsoft/vscode/pull/192513

- [x] linux @alexr00 @rzhao271 (x86_64, test both .deb and .rpm package)
- [x] linux @justschen  (arm64, test both .deb and .rpm package)

Complexity: 3

Authors: @deepak1556 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23199045%0A%0A&assignees=deepak1556)

---

In this milestone we have explored building our linux client bits (native modules, cli binaries) using custom compiler toolchain and  sysroot. The goal of this plan item is to ensure sanity on some of the interesting bits before pushing it to insiders next milestone.

**Please note:** Use the following [unreleased build](https://builds.code.visualstudio.com/builds/insider?commit=21af479f859a2b11e3687a84d89db06db755d83b&dev=true) for testing

_Installation:_

- Ensure application is installable on any distro supporting glibc >= 2.28 (ex: Ubuntu 20.04, Debian 10, Fedora 30)
   - For deb package: `sudo dpkg -i <path-to>.deb`
   - For rpm package: `sudo dnf install <path-to>.rpm` 
   - **Note:** if this is a fresh vm you might have missing dependencies prompted with the above command in that case install those dependencies and proceed.
 

_Testing native modules:_

- Open the integrated terminal and run a long running task like `yarn watch` in the vscode repo, things to keep eyes on
    - Ensure terminal sessions can be created and killed, (i-e) no leaking processes
    - Ensure terminal title updates as expected
 
- Toggle `Developer: Set log level` and change log levels,
   - Ensure that logs are displayed as expected from the relevant processes
   - Ensure logs are persisted to the user data dir `Developer: Open Logs folder`

- Connect to any container from the remote explorer and ensure the workspace opens as expected.

**Comment by professorabhay** [comment]
Hey @deepak1556, I would like to help you in the testing process. I have multiple machines available already.
If this is open for anyone then assign it to me.

**Comment by deepak1556** [comment]
Thanks for chiming in, this issue will be assigned to out team members during [endgame](https://github.com/Microsoft/vscode/wiki/Development-Process#end-game). But feel free to test and file any issues you encounter via our issue tracker. Builds for testing are linked below,

VS Code Build: 21af479f859a2b11e3687a84d89db06db755d83b

linux-arm64: https://az764295.vo.msecnd.net/insider/21af479f859a2b11e3687a84d89db06db755d83b/code-insider-arm64-1700845460.tar.gz
linux-armhf: https://az764295.vo.msecnd.net/insider/21af479f859a2b11e3687a84d89db06db755d83b/code-insider-armhf-1700845700.tar.gz
linux-deb-arm64: https://az764295.vo.msecnd.net/insider/21af479f859a2b11e3687a84d89db06db755d83b/code-insiders_1.85.0-1700845515_arm64.deb
linux-deb-armhf: https://az764295.vo.msecnd.net/insider/21af479f859a2b11e3687a84d89db06db755d83b/code-insiders_1.85.0-1700845751_armhf.deb
linux-deb-x64: https://az764295.vo.msecnd.net/insider/21af479f859a2b11e3687a84d89db06db755d83b/code-insiders_1.85.0-1700846702_amd64.deb
linux-rpm-arm64: https://az764295.vo.msecnd.net/insider/21af479f859a2b11e3687a84d89db06db755d83b/code-insiders-1.85.0-1700845600.el7.aarch64.rpm
linux-rpm-armhf: https://az764295.vo.msecnd.net/insider/21af479f859a2b11e3687a84d89db06db755d83b/code-insiders-1.85.0-1700845825.el7.armv7hl.rpm
linux-rpm-x64: https://az764295.vo.msecnd.net/insider/21af479f859a2b11e3687a84d89db06db755d83b/code-insiders-1.85.0-1700846797.el7.x86_64.rpm
linux-snap-x64: https://az764295.vo.msecnd.net/insider/21af479f859a2b11e3687a84d89db06db755d83b/code-insider-x64-1700848273.snap
linux-x64: https://az764295.vo.msecnd.net/insider/21af479f859a2b11e3687a84d89db06db755d83b/code-insider-x64-1700845452.tar.gz

**Comment by alexr00** [comment]
@deepak1556 your "unreleased builds" link doesn't work for me, but your links to each build in the previous comment work.

**Comment by alexr00** [comment]
Tested the .deb assigned to me (had to setup up a new Ubuntu VM, my existing one was 18). I'm trying to trade for the .rpm as I don't already have a setup for that.

**Comment by justschen** [comment]
No problems on arm64 .deb, ubuntu 22.

I was unable to install rpm on Fedora 36 though - deferring to another tester

**Comment by rzhao271** [comment]
Parallels does not work well with my Fedora 39 VM because it's unable to install tools that help me share folders between the guest and host systems.
The x64 rpm cannot be installed on my CentOS 7 VM.
I'll have to try this again later in a few hours with a USB stick.
