### ISSUE TITLE
Octicon support lost from status bar?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1990]
Maybe I am in some weird intermediate state because I triggered a build this afternoon and now my status bar extension is no longer showing Octicons:

![image](https://cloud.githubusercontent.com/assets/900690/12300530/2f8b34d0-ba1c-11e5-8911-2b77165b1f36.png)

@jrieken fyi

**Comment by jrieken** [comment]
this is a bug in the extension: https://github.com/felixrieseberg/vsc-travis-ci-status/issues/5

**Comment by jrieken** [comment]
I've pushed https://github.com/Microsoft/vscode/commit/f704f917aed99222603ab041f86e05fe5f52d7ab work around this

**Comment by bpasero** [comment]
Ah ok

**Comment by jrieken** [comment]
closing. workaround might stay for another while
