### ISSUE TITLE
vscode wrongly reported that the lisences should be array in a node package

### ISSUE THREAD

**Issue by zhouzhonghao** [Microsoft/vscode#19909]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.0.0
- Extensions:

|Extension|Author|Version|
|---|---|---|

---
![image](https://cloud.githubusercontent.com/assets/5805405/22616745/2d9c566e-eaee-11e6-984e-6a4ed209c6e4.png)

Steps to Reproduce:

1. write a node package including a package.json file.
2. vscode wrongly reported that the lisences should be array.

**Comment by aeschli** [comment]
The schema from package.json come from http://schemastore.org/json/.

But from how I understand https://docs.npmjs.com/files/package.json#license it does the right thing:

`license` is of type string. `licenses` is deprecated but used to be of type array.

Do you disagree? If yes, please file the bug against https://github.com/schemastore/schemastore/

**Comment by zhouzhonghao** [comment]
Though i agree with you, I do not want to see the warning. Can I do something to bypass it?

**Comment by aeschli** [comment]
Well, you could associate a different schema for package.json in your user settings.
But if your package.json really is a Node module package description, I'd suggest you follow the spec and rather use 'license' than 'licenses'

**Comment by zhouzhonghao** [comment]
OK. Thanks for your reply. The best choice is replace licenses with license as an upgradation.
