### ISSUE TITLE
The spark icon not showing anymore in the commit message section

### ISSUE THREAD

**Issue by Tanimou** [microsoft/vscode#199020]
Type: <b>Bug</b>

Not able to generate commit message. The spark icon disappeared

VS Code version: Code - Insiders 1.85.0-insider (aed074f18b4ac2cf2830fa9b57e1441b632fdddc, 2023-11-24T05:35:41.162Z)
OS version: Windows_NT x64 10.0.23590
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (5.96GB free)|
|Process Argv|--crash-reporter-id 7f788c3c-9b80-464e-a1f6-86d200419551|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (138)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
format-selection-as-html|adr|2.3.0
project-manager|ale|12.7.0
zip-extract-all|Anc|1.2.0
smarty-template-support|asw|2.1.1
html-extentions-pack|bou|0.3.0
multi-cursor-case-preserve|Car|1.0.5
catppuccin-vsc|Cat|3.6.0
catppuccin-vsc-icons|Cat|0.30.0
path-intellisense|chr|2.8.5
codestream|Cod|14.30.1
gitignore|cod|0.9.0
vscode-office|cwe|3.1.8
quicktype-refresh|dog|1.0.2
git-extension-pack|don|0.1.3
githistory|don|0.6.20
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
css-flexbox-cheatsheet|dzh|3.3.4
git-cheatsheet|dzh|1.4.4
gitlens|eam|2023.11.2404
vscode-html-css|ecm|1.13.1
vsc-material-theme-icons|equ|3.1.4
prettier-vscode|esb|10.1.0
vscode-github-notifications-bell|fab|2.3.1
git-project-manager|fel|1.8.2
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
docker-explorer|for|0.1.7
pythonsnippets|frh|1.0.2
vscode-image-gallery|Ger|1.2.1
codespaces|Git|1.16.2
copilot|Git|1.138.566
copilot-chat|Git|0.11.2023112301
copilot-labs|Git|0.17.1121
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.77.2023112309
gc-excelviewer|Gra|4.2.58
pyscript|Har|0.1.1
vscode-test-explorer|hbe|2.21.1
vscode-test-explorer-liveshare|hbe|1.0.5
helium-icon-theme|hel|1.0.0
docker-linter|hen|0.5.0
vscode-git-tags|how|1.4.4
output-colorizer|IBM|0.1.2
mysql-syntax|jak|1.3.1
better-dockerfile-syntax|jef|1.0.2
better-js-syntax|jef|0.0.2
better-shellscript-syntax|jef|1.6.3
OdooSnippets|jig|1.5.0
python-essentials|Jil|0.0.3
sass-color-transformation|jjv|0.0.4
svg|joc|1.5.3
vscode-peacock|joh|4.2.2
vsc-python-indent|Kev|1.18.0
vscode-gutter-preview|kis|0.30.0
git-tree-compare|let|1.16.0
vscode-python-test-adapter|lit|0.8.1
vsls-whiteboard|los|0.0.12
MagicPython|mag|1.1.0
docker-extension-pack|mag|1.0.0
start-git-bash|McC|1.2.1
rainbow-csv|mec|3.8.0
template-string-converter|meg|0.6.1
python-path|mge|0.0.14
vscode-language-babel|mgm|0.0.40
gitignore|mic|1.0.1
inline-fold|moa|0.2.6
prettify-json|moh|0.0.3
vscode-docker|ms-|1.28.0
vscode-edge-devtools|ms-|2.1.3
vscode-postgresql|ms-|0.3.0
black-formatter|ms-|2023.7.13171007
isort|ms-|2023.11.13191009
python|ms-|2023.21.13261010
vscode-pylance|ms-|2023.11.13
remote-containers|ms-|0.325.0
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.38.0
js-debug-nightly|ms-|2023.11.1317
live-server|ms-|0.4.11
powershell|ms-|2023.8.0
remote-explorer|ms-|0.5.2023110609
remote-repositories|ms-|0.40.0
remote-server|ms-|1.6.2023110809
test-adapter-converter|ms-|0.1.8
vscode-typescript-next|ms-|5.4.20231123
vsliveshare|ms-|1.0.5892
vsliveshare-audio|ms-|0.1.93
odoo-scaffold|mst|0.1.4
color-highlight|nau|2.5.0
vs-html-to-css|nep|1.0.0
back-n-forth|nic|3.1.1
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
docker-compose|p1c|0.5.1
material-icon-theme|PKi|4.32.0
git-file-history|pom|1.0.1
postman-for-vscode|Pos|0.14.3
python-string-sql|ptw|1.2.0
sqlite-viewer|qwt|0.3.13
vscode-rapidapi-client|Rap|1.10.2
vscode-services|rap|1.0.2
vscode-yaml|red|1.14.0
synthwave-vscode|Rob|0.1.15
git-merger|sha|0.4.1
background|sha|1.2.13
markdown-preview-enhanced|shd|0.8.10
git-autoconfig|shy|0.0.2
vsc-quokka-statusbar|ske|1.3.6
gitignore-generator|sle|0.0.2
vscode-zipexplorer|sle|0.3.1
sourcery|sou|1.14.0
guides|spy|0.9.3
teamhub|Tea|17.0.3
docker-essentials|Tec|0.3.0
git-essentials|Tec|0.3.0
branch-warnings|tel|1.0.10
pdf|tom|1.2.2
errorlens|use|3.15.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-pack|vsc|0.25.15
quokka-vscode|Wal|1.0.593
footsteps|Wat|0.5.0
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
five-server|yan|0.2.3
material-theme|zhu|3.16.2
vscode-open-in-github|ziy|1.3.6

(12 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
synctok:30869157
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30859870
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by Tanimou** [comment]
![image](https://github.com/microsoft/vscode/assets/91100433/e3512cb5-1d93-42dd-9fc4-5621f50b327b)

**Comment by xqrdot** [comment]
Spark icon - is that the one about generating the commit message? Try setting this setting value to true:
`"gitlens.ai.experimental.generateCommitMessage.enabled"`
Make sure you have gitlens installed.

**Comment by Tanimou** [comment]
Thank you very much. It works now
