### ISSUE TITLE
UI Glitch and Display Issues in Visual Studio Code on Kali Linux 2023.3

### ISSUE THREAD

**Issue by NoMrBody** [microsoft/vscode#199093]
Type: <b>Bug</b>

I encountered a significant UI malfunction in Visual Studio Code (VSCode) on my Kali Linux 2023.3 system. When attempting to launch the application using the regular method, the UI failed to display correctly, showing only the main window with several glitching areas on the screen.

Operating System Information:
    OS: Kali Linux 2023.3

Problem Details:
    Symptoms: Upon launching VSCode, only the main window is visible, and various glitching areas appear on the screen.
    Resolution Attempted: Opening the application from the terminal using the command code --disable-gpu resolved the issue partially. However, the problem persists when launching the app in the regular way.
The problem remains even after testing with the default theme, ruling out any issues related to installed theme extensions.

VSCode
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:50:47.800Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.0-kali3-amd64
Thank you for your attention to this matter. If further information is needed, please let me know.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.5.0-kali3-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 7520U with Radeon Graphics (8 x 4135)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|7.04GB (4.61GB free)|
|Process Argv|--disable-gpu --crash-reporter-id b0fc46ab-78e7-4dd3-9bbe-1c7eab22fa61|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
mayukaithemevsc|Gul|3.2.4
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
java|red|1.24.0
LiveServer|rit|5.7.9
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.2
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.43.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
vscrp:30673768
2i9eh265:30646982
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30886110
dsvsc017cf:30886113
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by gjsjohnmurray** [comment]
I suggest you try the advice at https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium

**Comment by gjsjohnmurray** [comment]
I suggest you try the advice at https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium

**Comment by NoMrBody** [comment]
> I suggest you try the advice at https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium

The problem has been resolved, thank you for your assistance.
