### ISSUE TITLE
Test: floating windows

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#199023]
Refs: https://github.com/microsoft/vscode/issues/10121

- [x] macOS @meganrogge 
- [x] linux @chrmarti
- [x] windows @Tyriar

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23199023%0A%0A&assignees=bpasero)

---

Floating windows will be available in stable for our next release. A lot of changes went in during this milestone to polish the experience. This test plan covers the additions.

**Overal**
* watch out for errors in devtools from your testing
* watch out for screen cheese or missing CSS styles that cause rendering issues
* enable the "Open Editors" view to easily see all opened windows and ensure you can navigate to them

**Drag and Drop**
* run this test both with dragging editor tabs as well as tab groups [1]
* drag and drop outside of VS Code and verify a floating window opens with the tab(s) at the location you dropped
* verify this with multi-monitor setup and ensure the location is correct
* drag and drop into editor area of other VS Code windows (both floating or other workspace windows) and verify you can still drop tab(s) into other windows without being forced to open a floating window
* verify you never see a floating window open for when you drop over any VS Code window, including the one you start the drag operation from
* set `workbench.editor.dragToOpenWindow: false` and verify that dropping outside the window no longer opens floating windows
* press `Alt` key before dragging and verify you get the opposite drop behaviour of what `workbench.editor.dragToOpenWindow` is configured to in both cases

[1] you can drag tab group by dragging the empty space after the last tab

**Custom Title**
* configure `window.titleBarStyle: custom`
* open floating windows and verify you see the same custom title as in the main window (except for: no menu bar, no layout controls)
* verify you can configure command center visibility and the update is live
* verify you can double click on title to maximize / restore
* verify you can move the floating window by dragging the custom title bar
* verify the window title reflects the active editor of the floating window
* configure `window.titleBarStyle: native`
* open floating windows and verify you see native title bar
* verify the window title reflects the active editor of the floating window

**Status Bar**
* open floating windows and verify you see a status bar with the same colors as the main window
* verify you see entries for editor status (for example line/col selection) that are specific to the active editor of the floating window
* verify you see a per-window language status indicator with a rich hover that is functional
* verify multiple windows show different editor status that is always specific to the active editor in the window
* verify status bar background color changes when you start/stop to debug

**New Commands**
* right click on a tab and trigger the new command "Move into New Window"
* from the "Editor Layout" top level menu (under "View > Appearance"), trigger the new commands to Move/Copy into New Window
* from the command palette, trigger the new commands to Move/Copy into New Window both for active editor and active editor group
* from the command palette in a floating window trigger the new command "Restore editors into main window" and ensure the editors of the floating window all move over

**Accessibility**
* enable the `editor.accessibilitySupport` setting for enhanced accessibility
* open floating windows
* enable a screen reader
* verify you get the active elements announced while you operate in the floating window including text editor and quick open

**Comment by meganrogge** [comment]
All works well for me from an accessibility perspective. 👏🏼

**Comment by Tyriar** [comment]
I got through part of this today, will finish up testing tomorrow to make sure it's done right.
