### ISSUE TITLE
Test: Tree Sticky Scroll

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#199153]
Refs: #161207

- [x] Windows: @Tyriar 
- [x] anyOS @lszomoru
- [x] anyOS @andreamah

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23199153%0A%0A&assignees=benibenj)

---

We added sticky scroll to all trees in vscode. 

**Try out sticky scroll on at least 3 different trees, one of them being contributed by an extension.**

Examples: File Explorer, Outline View, Search View, SCM change files, Problems view, Debug panel, Testing View, Settings editor, GitHub PR extension, ...

**Settings:**
- `workbench.tree.enableStickyScroll`: Enables/Disables sticky scroll for all trees (currently enabled by default)
- `workbench.tree.stickyScrollMaxItemCount`: Maximum number of items in the sticky scroll widget

We make sure that the sticky scroll widget never fills more than 40% of the tree view. Try resizing the height of the view to test this.

**Sticky Scroll Behaviour:**
- When pressing on a sticky scroll node, the tree reveals the real node under the the mouse cursor.
- When pressing on a sticky scroll twisty, the tree collapses and reveals the real node under the the mouse cursor (It is not guaranteed that the real node can be revealed under the cursor as there might not be enough tree items after that node to scroll it in place).
- When pressing on a sticky scroll action item, the action runs and the tree does not reveal the node (except if the action itself causes this to happen)
- When right clicking a sticky scroll node, the context menu of that node appears.

**Other Behaviour:**
- When using the arrow keys to navigate the trees the focused tree item can not be hidden behind the widget. (Same as when navigating the tree without sticky scroll, the focused item is always visible when using arrow keys

https://github.com/microsoft/vscode/assets/44439583/cb9112c0-5e00-4a7b-a0da-d610d3d4c4a3

**Comment by Tyriar** [comment]
Very solid 👏

**Comment by lszomoru** [comment]
Awesome work 👏🏻👏🏻👏🏻

**Comment by andreamah** [comment]
Works well! :)
