### ISSUE TITLE
PyQt5 file dialog crash only when launched from integrated terminal AND with a .json file next to the python file

### ISSUE THREAD

**Issue by mperez-cdf** [microsoft/vscode#199190]
Type: <b>Bug</b>

I had a project which worked well, using PyQt5. Today, after several weeks without touching this project, it didn't work so well. I couldn't open any file dialog. The software freezes and begins to take more and more memory.

After investigation with a very minimal program, a python environment (tried python 3.10 and 3.11) with only PyQt5 installed and all extensions disabled:
```python
from PyQt5.QtWidgets import QApplication, QFileDialog


app = QApplication([])
w = QFileDialog()
w.show()
app.exec_()
```

it appears that this bug only happens when opening a PyQt5 File Dialog if run from the integrated terminal (tested with fish or bash and "python main.py") and if there's a json file alongside the main.py file.

The bug is still there if I try from another folder, with a valid, invalid, or empty json file, whatever its name.

It works from another terminal. It works if I remove the json extension of the file or change it to anything else like txt (which is not used by my program at all).

So, this is very particular but it seems to be linked to vscode. It took me some time to find what was the problem so I figured it was better to share it. I guess it comes from a recent version of vscode as it worked before.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.6.1-1-MANJARO snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz (16 x 4597)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.11GB (23.38GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --log trace|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-fr|MS-|1.84.2023111509

</details>

**Comment by mperez-cdf** [comment]
When it works (here, changing the extension of the empty file to "anything.NOT_json") it should look like that : an opened window where you can choose a file to open.
![file_dialog_working](https://github.com/microsoft/vscode/assets/122037372/182c679e-d722-4536-86aa-3f5de973fac6)

When the extension is json however, the window is empty (we see behind part of vscode), I have to kill the program manually, otherwise it takes more and more memory.
![file_dialog_not_working](https://github.com/microsoft/vscode/assets/122037372/5041d0e9-ab46-4a63-a9c7-b803cafaeb87)

I don't know how much it is due to Qt or vscode ; but one thing is sure : this does not happen when I use an external console. It only happens via the integrated terminal of vscode and from a recent version of vscode.

**Comment by meganrogge** [comment]
Thanks for the info. Here's info on how to provide more details about your issue https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by mperez-cdf** [comment]
Info from code --status are included in this performance report issue (all extensions are disabled)

Type: <b>Performance Issue</b>



VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.6.2-1-MANJARO snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz (16 x 4600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|31.11GB (25.77GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   127	  3309	code main
    0	    32	  3311	   zygote
    0	    32	  3312	   zygote
    0	   191	  3361	window [1] (main.py - test_qt5_file_dialog - Visual Studio Code)
    0	    96	  4890	window [2] (Rapporteur du problème)
    0	   127	  3340	   gpu-process
    0	    32	  3344	   utility-network-service
    0	    64	  3417	ptyHost
    0	     0	  3484	     /usr/bin/fish
    0	   924	  3961	       python main.py
    0	    96	  3427	shared-process
    0	     0	  4900	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    64	  3428	fileWatcher [1]
    0	    96	  3429	extensionHost [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (main.py - test_qt5_file_dialog - Visual Studio Code)
|    Folder (test_qt5_file_dialog): 4418 files
|      File types: sip(786) py(753) pyc(752) qml(695) png(219) qm(195) so(181)
|                  qmlc(170) qmltypes(53) 5(48)
|      Conf files:;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-fr|MS-|1.84.2023111509


</details>

**Comment by meganrogge** [comment]
@joaomoreno or @rzhao271 any ideas related to Linux x64 6.6.2-1-MANJARO snap?

**Comment by Tyriar** [comment]
This is very likely a snap problem
