### ISSUE TITLE
"Find in the selection" not activatable on find and replace

### ISSUE THREAD

**Issue by Mutton** [Microsoft/vscode#19914]
- VSCode Version: 1.9.0
- OS Version: Windows 10 Pro (Build: 14393.693)

Steps to Reproduce:

1. select any range of text / code in the normal editing sub-window
2. press combination ctrl + h
3. try to press greyed out button with over-mouse description "Find in selection"

**Comment by mrmlnc** [comment]
Duplicate of #19910.

**Comment by Mutton** [comment]
Next time, I would love to be taken more seriously, instead of just closing the issue without any confirmation of a successful solution. And yes, it was my fault for not listing one initial reproduction step because my brain considered it as self-evident while it should be mentioned for the sake of completion.
