### ISSUE TITLE
Screen reader not reading in terminal

### ISSUE THREAD

**Issue by rohanshardha** [microsoft/vscode#199102]
Type: <b>Bug</b>

Using JAWS 2023.2307. When pressing back space in terminal(powershell, cmd, R, radian) screen reader is not reading what character was deleted. Did not had this issue in older versions.

VS Code version: Code - Insiders 1.85.0-insider (9524207999ef1159f5e973539d68c69ed1b519f2, 2023-11-22T14:33:51.941Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1360P (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (2.84GB free)|
|Process Argv|--crash-reporter-id 29d949c7-509e-49cc-988a-655bbe4b9e28|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2023.21.13261010
vscode-pylance|ms-|2023.11.13
jupyter|ms-|2023.11.1003301000
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
r|REd|2.8.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialogc:30812479
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30859868
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by rohanshardha** [comment]
Having the same issue in v1.84. @meganrogge

**Comment by jooyoungseo** [comment]
Just FYI, this is not supported well in Python in any other repl. This is because the character-tracking in terminal relies on shell integration and regex and the sub-shells, such as repl does not provide shell integration. I agree this is an essential feature and it would be great if this could be resolved in the near future.

**Comment by meganrogge** [comment]
cc @anthonykim1 

/duplicate #195372
