### ISSUE TITLE
Test: Source Control view sanity testing

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#199172]
Refs: https://github.com/microsoft/vscode/issues/192290

- [x] anyOS @eleanorjboyd 
- [x] anyOS @hediet

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23199172%0A%0A&assignees=lszomoru)

---

This milestone we have refactored the main "Source Control" view in order to use the async data tree. Given the importance of the view, we want to ensure that this refactoring did not introduce any major regressions so we would like to sanity test the view. 

⚠️ Testing incoming/outgoing changes is not in scope for this test plan item.

### Prerequisites
* Download and install the latest VS Code Insiders release

### Basic functionality
* Open a folder/workspace that contains a git repository
* Make changes to file multiple files, save them
  * Confirm that the tree is being updated as expected 
* Stage changes, Unstage changes, discard changes
  * Confirm that the tree is being updated as expected 
* Switch between list and tree view
  * Confirm that the tree is being updated as expected
* Switch to tree view and expand/collapse some nodes
* Switch to the Explorer view, then switch back to Source Control view
  * Confirm that the tree state is being maintained

### Multi-repo functionality 
* Open a folder/workspace that contains multiple git repositories
* In the "Source Control Repositories" view select all repositories
  * Confirm that all selected repositories get rendered in the "Source Control" view
* Change the selected of repositories in the "Source Control Repositories" view
  * Confirm that all selected repositories get rendered in the "Source Control" view 
* Make changes/stage/unstage/discard changes for each repository
  * Confirm that the tree is being updated as expected

### Settings
* Open a folder/workspace that contains a git repository
* Open the settings editor and toggle the following settings and confirm they they work as expected:
  * `scm.alwaysShowActions`
  * `scm.showActionButton`
  * `scm.countBadge`
  * `git.alwaysShowStagedChangesResourceGroup`
  * `git.untrackedChanges`

**Comment by hediet** [comment]
Looks good!
