### ISSUE TITLE
"Find in the selection" not activatable on find and replace

### ISSUE THREAD

**Issue by Mutton** [Microsoft/vscode#19910]
- VSCode Version: 1.9.0
- OS Version: Windows 10 Pro (Build: 14393.693)

Steps to Reproduce:

1. select any range of text / code
2. press combination ctrl + h
3. try to press greyed out button with over-mouse description "Find in selection"

**Comment by bpasero** [comment]
@Mutton it becomes enabled once you select text 👍

**Comment by Mutton** [comment]
I selected text, sorry to not have it mentioned in the reproduction listing

**Comment by alexandrudima** [comment]
Duplicate of #15125, which has a PR #15566
