### ISSUE TITLE
[Integrated terrminal] [Feature Request] Configuration option to show integrated terminal by default

### ISSUE THREAD

**Issue by denislamela** [Microsoft/vscode#19919]
- VSCode Version: NA
- OS Version: NA

Steps to Reproduce: NA

It would be nice to have a configuration option to show integrated terminal window by default.

Kind regards

**Comment by Tyriar** [comment]
The terminal window will always be restored if it was open when VS Code was shutdown. So if you never close it it should always restore. Would rather not add a configuration value for this as that system already exists, plus a setting would conflict with it and cause bloat.
