### ISSUE TITLE
improve discoverability of accessibility info in copilot experience

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#199191]
Screen reader users learn about accessibility features related to the copilot experience via accessibility help, which is discoverable in the aria label of the input box. 

Low vision users, keyboard only users, and others might not discover this. 

We should consider adding a button/link to the Copilot welcome message so all users can learn about the accessibility features. 
```[tasklist]
### Tasks
- [x] Add acessibility to copilot documentation
- [x] Move accessibility help/ view information up in VS Code accessibilty docs
```

**Comment by isidorn** [comment]
Can we instead mention it in our Copilot docs on our website?
https://code.visualstudio.com/docs/editor/github-copilot#_chat-features
Since the Copilot welcome message already links there?

@gregvanl for thoughts?

**Comment by meganrogge** [comment]
Yes, I wondered about that. But I think we'd need to include them very close to the top, if so?

**Comment by meganrogge** [comment]
The fable study showed that magnification users aren't aware of the accessible view, which would help when keyboard shortcut labels wrap. They would also benefit from the accessibility help dialog, which provides an overview of what to expect with the chat experience.

**Comment by joyceerhl** [comment]
I'm not convinced we should put more text in the welcome message, given we invested effort to trim it down lately. Should we rather make sure that the accessible view and accessible help functionality are discoverable (maybe in our Get Started walkthrough and our documentation)?

**Comment by meganrogge** [comment]
As long as the accessibility information is placed prominently in our documentation, that sounds good to me.

**Comment by joyceerhl** [comment]
Increasingly various parts of VS Code have onboarded to the accessibility help, would we consider also moving mention of the accessibility help higher in the accessibility documentation to help with this? https://code.visualstudio.com/docs/editor/accessibility#_accessibility-help

**Comment by meganrogge** [comment]
I have moved accessibility help up in our docs. 

I don't think we necessarily need to add it to the Copilot documentation. I'll keep getting feedback on this.
