### ISSUE TITLE
Test: Multi Diff Editor

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#199155]
Refs: https://github.com/microsoft/vscode/issues/179000

- [x] any @bpasero 
- [x] any @alexdima 
- [x] any @isidorn

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23199155%0A%0A&assignees=hediet)

---

This iteration, we implemented the (still experimental) *multi diff editor*.

## Preparation
* Open a github repository (e.g. vscode)
* Install latest pre-release GHPRI extension
* Set `"multiDiffEditor.experimental.enabled": true`

### How To Open A Multi Diff Editor

Try to open the multi diff editor from various places. The icon is always the same. Test if it is intuitive how to open the view.

Notice that the multi file diff editor does not yet react to files becoming changed/unchanged while the view is open.

* SCM view (make sure you have multiple locally changed files) - test this for both staged and unstaged changes

![Image](https://github.com/microsoft/vscode/assets/2931520/22db7927-0118-4e3e-b64e-762fd702d3c0)

* SCM view: Incoming changes/Outgoing changes (outgoing optional)

* For Pull Request in the GitHub sidebar

### Multi Diff Editor Itself

* Verify that collapsing files work
* Verify that scrolling works (sufficiently smooth)
* Verify that editor options are applied, even if different file types get different settings (e.g. change a ts and a json file, and configure the font size for json files in your settings)
* Verify that reloading VS Code works while the multi diff editor is open
* Verify that the scroll position is restored when switching to a different editor in the same tab group and back

Please also try to test the UX of this feature - try reviewing PRs using the multi diff editor! What features do you miss the most? What bugs are the most annoying?

**Comment by gjsjohnmurray** [comment]
It is also openable from Timeline view when this is showing commits (which it does by default).

**Comment by bpasero** [comment]
@gjsjohnmurray does it?

**Comment by gjsjohnmurray** [comment]
> @gjsjohnmurray does it?

Sorry, I had misremembered. Updated my comment.

**Comment by bpasero** [comment]
Pretty cool 👍 . Sometimes I was not able to click into the diff editor anymore (right hand side), but not sure how to reproduce that.

**Comment by alexdima** [comment]
:clap: Very nice! And of high quality!
