### ISSUE TITLE
Add duration to the terminal command SI tooltip

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#199170]
We have a rough timestamp, but a duration would be quite easy to add here as well:

![image](https://github.com/microsoft/vscode/assets/2193314/edb80356-2eb8-4cae-a2cc-c4b644fd940c)

**Comment by hsfzxjy** [comment]
I'd like to work on this. To clarify, by "duration" do you mean "the amount of time this command being executed"?
