### ISSUE TITLE
Line numbers width does not grow when pasting large file

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#19913]
Paste checker.ts at https://microsoft.github.io/monaco-editor/index.html

![image](https://cloud.githubusercontent.com/assets/5047891/22616993/035b5faa-eaba-11e6-8dc9-9e630fe2ad72.png)

**Comment by bam** [comment]
Just downloaded vscode 1.9.0 and seems it works well with 1 000 000 lines of code...
![screenshot 2](https://cloud.githubusercontent.com/assets/2446302/22619188/2c83ad38-eb00-11e6-809c-8ac6b2d33d77.png)

**Comment by bam** [comment]
Is it a problem with vscode? or [monaco](https://github.com/Microsoft/monaco-editor)?
in vscode 1.9.0 it works fine:
![screenshot 2](https://cloud.githubusercontent.com/assets/2446302/22619216/0bac7170-eb01-11e6-8175-1f7531538dda.png)

**Comment by alexandrudima** [comment]
I've noticed it in the monaco editor. It should all follow the same code path, so I'm stumped why it happens there and not in vscode :).

**Comment by alexandrudima** [comment]
Most annoying. I can no longer reproduce.

**Comment by bam** [comment]
But I can. In monaco on the link you provided it works well until 9999. There is only 4 digits for line numbers and panel width doesn't grow. (tested in latest chrome and edge)
![image](https://cloud.githubusercontent.com/assets/2446302/22653592/f4295a72-ec9a-11e6-827a-83d04b4b08cc.png)

**Comment by bam** [comment]
Maybe is it worth to move this bug to monaco project?

**Comment by alexandrudima** [comment]
Indeed, it seems to be caused by the website CSS itself, that's why I couldn't reproduce -- https://github.com/Microsoft/monaco-editor/blob/master/website/index/index.css#L7

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#350
