### ISSUE TITLE
[Accessibility] Allow users to send codeblocks from within Copilot Chat Accessible View

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#199119]
Type: <b>Feature Request</b>

CC @meganrogge 

1. Open copilot Chat.

1. Ask "Create a simple Python dict."

1. Open Alt+F2 (Accessible View) for the returned response.

1. Move around your cursor to anywhere inside the Python codeblock.

1. Press Ctrl+/ to insert the codeblock to editor or run "Chat: Insert at Cursor" in the command palette.

* Note: This is not currently supported and users have to close the Accessible View and manually relocate to the codeblock.

VS Code version: Code - Insiders 1.85.0-insider (eb56719ae7653bff54989385818ef39e1cd73d29, 2023-11-24T15:21:39.004Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by meganrogge** [comment]
Can try to focus the location where the cursor was in the help view in the chat view.
