### ISSUE TITLE
while i use the second monitor, there is a problem about color.

### ISSUE THREAD

**Issue by rcbcerwin** [Microsoft/vscode#19911]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|insertnumbers|Asuka|0.9.1|
|calculate|acarreiro|1.1.0|
|Bookmarks|alefragnani|0.10.2|
|code-runner|formulahendry|0.6.7|
|CppSnippets|hars|0.0.6|
|cpptools|ms-vscode|0.10.0|

---

Steps to Reproduce:

1.
2.

![image](https://cloud.githubusercontent.com/assets/22849464/22616868/b6c6f856-eaf1-11e6-89c5-fef05f6c1a58.png)
Are you see the different,  all color theme have this problem when i use the second monitor in mac.

**Comment by Ziao** [comment]
Noticed this as well, initially thought it had to do with the HDMI connection, but after trying with DisplayPort, it still happens. Running OSX as well.

**Comment by bpasero** [comment]
#12473
