### ISSUE TITLE
Test: status bar/ activity bar keyboard navigable tooltips

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#199199]
Refs #196500

- [x] Windows @bhavyaus 
- [x] macOS @isidorn 
- [x] Linux @alexr00 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23199199%0A%0A&assignees=meganrogge)

---

There is a push to make icon only buttons show tooltip information when focused via keyboard.

Activity Bar/ Status Bar:

Enable `Tab Moves Focus` mode with `ctrl+shift+m`. Using tab and arrow keys, verify that the activity bar and status bar items display tooltips when focused.  

Verify that on mouse hover, the tooltips still work as expected.

**Comment by isidorn** [comment]
Cool work! Do we have plans to adopt this in all areas where we use the custom hover?

**Comment by meganrogge** [comment]
@isidorn, after #199220, this should now work in all of the places with a custom hover AFAIK. Can you think of other places that we're missing? 

It will be nice when this #154364 happens and this works everywhere. That will allow us to close #132344.
