### ISSUE TITLE
Test: copilot generate commit message in the terminal

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#199197]
Refs https://github.com/microsoft/vscode-copilot/issues/2438

- [x] Windows @gregvanl 
- [x] macOS @sandy081 
- [x] Linux @rzhao271 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23199197%0A%0A&assignees=meganrogge)

---

In a single folder and in a multi-root repo:
- Make some file changes
- In the terminal, add these changes via `git add .` or `git add filename`
- Verify the ❇️ quick fix shows up with `Copilot: Generate Commit Message`
- Run the action and ensure it works as expected

**Comment by gregvanl** [comment]
Not seeing a sparkle anywhere around `git add .` or `git add blah.md`?

**Comment by sandy081** [comment]
Same for me. I am also not seeing the code actions

<img width="792" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/38b0f6eb-c998-49c6-80ee-a19fd4018c69">

**Comment by meganrogge** [comment]
@sandy081 we check for the command line to match against `git add .+`. We don't currently support aliases, though there is an issue tracking that.

**Comment by meganrogge** [comment]
@gregvanl likely a windows bug, could you pls create an issue?

**Comment by sbatten** [comment]
I don't see this working at all on Linux (Fedora 35)

**Comment by gregvanl** [comment]
Also not working for me on Linux (Debian)

**Comment by meganrogge** [comment]
Screenshots from Linux would be helpful.

**Comment by meganrogge** [comment]
Also, does the other copilot quick fix work? Ie run a no op command in the terminal such as "blah". Any sparkle quick fix?

**Comment by meganrogge** [comment]
I think quick fixes on linux were likely not working for the same reason as https://github.com/microsoft/vscode/issues/199448. Should be fixed in the next insider's.

**Comment by meganrogge** [comment]
@gregvanl and @sbatten can you pls test on this build when it is ready?

https://builds.code.visualstudio.com/builds/insider?commit=8762127fc97b8aaae5f3a0dd6a6d853d9a1b7574

**Comment by gregvanl** [comment]
Working now on Windows

![image](https://github.com/microsoft/vscode/assets/12818376/3d80db06-a169-4b22-b611-9849871cd6c0)
