### ISSUE TITLE
Close multiple tabs quickly

### ISSUE THREAD

**Issue by HediRaz** [microsoft/vscode#199178]
Type: <b>Feature Request</b>

When closing tabs, when clicking on the cross it would be great that the cross of the next tab slides right under the pointer.
Firefox has a similar feature: when you open a lot of tabs their size decrease, then when you exit a lot of them they keep the same size so that we can exit a lot of tabs just by clicking multiple times on the same place and remaining tabs take a bigger shape only when your pointer goes somewhere else.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.2.0-37-generic
Modes:
Remote OS version: Linux x64 6.2.0-37-generic

**Comment by JOEMN96** [comment]
When you click mouse scroll wheel on tabs, you will get this requested behavior.

**Comment by bpasero** [comment]
You can get this when you configure `workbench.editor.tabSizing` to `fixed`
