### ISSUE TITLE
Notebook scroll scroll font feels inconsistent

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#199198]
Does this issue occur when all extensions are disabled?: Yes/No

<img width="833" alt="image" src="https://github.com/microsoft/vscode/assets/876920/a03a7c63-2894-471b-b572-f06158448c55">

The notebook sticky scroll is using the text editor font other than the workspace font, which made it look inconsistent with the breadcrumb and notebook toolbar.

It looks less polished compared to the list view sticky scroll.

<img width="1319" alt="image" src="https://github.com/microsoft/vscode/assets/876920/f13c96b3-f348-4107-b3e3-000c243a71ef">

**Comment by Yoyokrazy** [comment]
Fixed via #202200
