### ISSUE TITLE
Glob: server/**/**.js should not match server.js

### ISSUE THREAD

**Issue by victorschinaider** [Microsoft/vscode#19926]
- VSCode Version: 
- OS Version: Ubuntu 16.04

Steps to Reproduce:
Description: 
I'm having problems to define a pattern to exclude files of the view.
Let define that we've this folder directory project:

```
+ Project
    + server
        + folder2
            - file2.ts
            - file2.js 
        - file1.ts
        - file1.js
- server.js
```

I want to exclude ``**.js``files. So, a define the pattern ``server/**/**.js``, but vscode is interpreting that "server/" is a file, and the project folder looks like that, after the pattern.

```
+ Project
    + server
        + folder2
            - file2.ts
        - file1.ts
```

Vscode excludes ``server.js` ` too. There is a gif below showing the behavior:

**Gif below:**

![](http://im2.ezgif.com/tmp/ezgif.com-537ce5f92a.gif)

**Comment by bpasero** [comment]
@victorschinaider I see the problem, a better solution is to do this:

`"**/*.js": { "when": "$(basename).ts" }`

**Comment by victorschinaider** [comment]
But your aren't seeing a bug here? The pattern is hiding files that aren't in pattern...

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/5438
