### ISSUE TITLE
Test: Terminal command navigation improvements

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#199243]
Refs: #198041

- [x] macOS @sandy081
- [x] linux @andreamah
- [x] windows @bhavyaus

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23199243%0A%0A&assignees=Tyriar)

---

Since sticky scroll (https://github.com/microsoft/vscode/issues/199240) and the command highlight (https://github.com/microsoft/vscode/issues/199237) features are built upon the same infrastructure as command navigation, it also saw several improvements this iteration. Docs on the feature: https://code.visualstudio.com/docs/terminal/shell-integration#_command-navigation

Here are some of the changes/things to test:

- The entire prompt should now be highlighted, including a single focus rectangle around all whole prompt lines
- The feature should be more reliable now, try holding cmd/ctrl+up or down and make sure it works (it used to loop around in some circumstances)
- It should play nicely with sticky scroll
- After scrolling, it should be positioned giving a little context above unless the entire prompt was already in the viewport

**Comment by sandy081** [comment]
Works well 👏
