### ISSUE TITLE
Add _ to the default value of "editor.wordSeparators"

### ISSUE THREAD

**Issue by KalitaAlexey** [Microsoft/vscode#19923]
Hi everybody.

It seems that `_` isn't part of default value of **editor.wordSeparators**.
It seems weird to me.
I am opening this issue to collect opinions whether other people also want `_` to be part of **editor.wordSeparators**.

**Comment by alexandrudima** [comment]
Labeling as question, since we don't have a discussion label. 

I think we haven't included `_` in the default list of word separators because so many programming languages allow for `_` to be part of an identifier.

**Comment by KalitaAlexey** [comment]
@alexandrudima,
Yes, I know.
But I very often want to change only part of an identifier.

**Comment by jhasse** [comment]
I think it shouldn't be part of wordSeparators so that selecting camelCase and snake_case identifiers behaves the same.

**Comment by alexandrudima** [comment]
We have no plans to change the default value at this time.
