### ISSUE TITLE
Terminal Sticky Scroll can hide entire terminal

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#199276]
Testing #199240

I ran the following command which is a powershell command that spans 8 lines. In this case sticky scroll can fill the entire terminal. One thing we do for sticky scroll in the tree is we allow sticky scroll to take a maximum of 40% of the view height. If the widget takes more than 40% of the height, we start dropping some of the sticky lines. In that case you could possibly have a `...` at the end of the last line to indicate to the user that there is more to the command than can be shown.

powershell command: `ping 8.8.8.8; >> ping 8.8.8.8; >> ping 8.8.8.8 >> ping 8.8.8.8 >> ping 8.8.8.8 >> ping 8.8.8.8 >> ping 8.8.8.8 >> ping 8.8.8.8`

(>> is new line)

used setting `terminal.integrated.stickyScroll.maxLineCount: 10`

![Recording 2023-11-28 at 09 52 03](https://github.com/microsoft/vscode/assets/44439583/af5d2171-847d-4fac-9615-ef6736c97d09)

**Comment by aiday-mar** [comment]
Hey @Tyriar, we do not have such a logic in the editor sticky scroll although it is a very interesting idea and it may be worthwhile to look into it.
