### ISSUE TITLE
Hide all messages with actions after a certain timeout

### ISSUE THREAD

**Issue by RockyTV** [Microsoft/vscode#1992]
After you have executed a task, or have installed a new extension, a pop-up will show, but won't disappear until you manually close it.

Pop-ups should have a default kill-time, and for pop-ups that warns you that you must restart VSCode to install the new extension could not disappear by default.

The time could also be configurable.

Here's my suggestion: have `IMessageInterface.show()` include an argument for the dispose time, and not specifying it will make the popup disappear in the time specified in the Workbench Settings.

**Comment by tatmanblue** [comment]
I would like to add, global option to turn these off.   they get in the way.   better option to have these messages appear in the output console window.

**Comment by bpasero** [comment]
@RockyTV with https://github.com/Microsoft/vscode/pull/43770 landing can you check this again from our insider build to see if it still nags you? Notifications no longer appear over the editor, but bottom right. 

You can give our preview releases a try from: https://code.visualstudio.com/insiders/
