### ISSUE TITLE
Circular dependency in problems settings for toggling problems

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#199246]
debt and changes related to https://github.com/microsoft/vscode/pull/198719

~Change settings to match the following:~
> I don't believe that using `editor.renderValidationDecorations` is the right setting to control all error renderings and that this should be revisited.
> 
> I would have expected a single, new settings which is an object where each key represents an "product" area, like
> 
> ```
> problems: {
>   outline: true|false,
>   explorer: true|false,
>   editor: ...
> }
> ```

- [x] Fix circular dependency so settings aren't bled into other contribs (all in workbench, but in different contribs)
> While it's a bit weird to have a setting from `markers` contribution which can have impact on others, but it's much better than `workbench.editor.*` setting. Maybe this can be a setting contribution from the marker service, but since marker service is in `platform`, I'm not sure if that's the right to do.
> 
> Having an unified `problems.visibility` setting is better than having a "problem"/"diagnostic" setting in every component. 

- [x] Settings migrations
- [x] Move out of preview features 

(partially fixed by https://github.com/microsoft/vscode/pull/202187)

cc @jrieken @bpasero

**Comment by starball5** [comment]
Note to self: update https://stackoverflow.com/a/74934214/11107541 when this goes through.

**Comment by justschen** [comment]
after further discussion, closing this issue and will re-address unification of settings with https://github.com/microsoft/vscode/issues/198333

The shape of the setting will remain as `problems.visibility`
