### ISSUE TITLE
Extension host with pid 6264 exited with code: 0, signal: unknown.

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#199208]
https://dev.azure.com/vscode/VSCode/_build/results?buildId=109548&view=logs&j=e5ed5edc-5ec6-5bfb-d1cb-ed7e8a6cb5eb&t=47853d69-0171-5aff-95e0-ddf2bd2b235d&l=1457

I have seen this a few times recently 

https://github.com/microsoft/vscode/blob/bc8742568c4c03f91550731fc214d8e78706a147/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L509

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/192119

**Comment by deepak1556** [comment]
Thanks @alexdima , merging this to https://github.com/microsoft/vscode/issues/192119.
