### ISSUE TITLE
Terminal sticky scroll is partially visible 

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#199200]
Does this issue occur when all extensions are disabled?: Yes/No

<img width="808" alt="image" src="https://github.com/microsoft/vscode/assets/876920/a8ef2ad5-1283-40c7-a422-0a05b91bb06a">

after switching between different terminal instances, the sticky scroll becomes partially visible.

**Comment by Tyriar** [comment]
Since it looks perfectly aligned with the line above, I'm guessing it's related to the existing issue where the top line could be obscured. I know this can happen after zooming, did you do that by recently chance?

**Comment by rebornix** [comment]
@Tyriar I don't recall I did any zooming as I seldomly do so. Will keep an eye on if I get another reproduce.

**Comment by justschen** [comment]
After zooming in/out, it adds a space between the tabs and the sticky scroll (not clickable, but sticky scroll is). 

<img width="989" alt="Screenshot 2023-11-28 at 9 46 26 AM" src="https://github.com/microsoft/vscode/assets/54879025/366491eb-8c46-48bb-9bfb-d240a7a93aef">

**Comment by Tyriar** [comment]
Haven't seen this in a long time
