### ISSUE TITLE
Multi-diff editor doesn't seem to respect readonly on the right side

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#199251]
The multi-diff editor from the SCM view (or using the `vscode.changes` command directly) isn't honoring the `readonly` state of the Uri on the right side. Allowing you to still edit the in-memory document when you shouldn't be able to.

The easiest way to see this is to open the multi-diff editor for staged changes -- you can edit the currently staged changes and save, but nothing really happens. Though it is making changes to the in-memory document, because if after you make changes you open a normal diff of the file you edited you will actually still see your changes (which is completely wrong). If you then close both diffs (multi and single), and then re-open the diff everything is back as expected (without the change made).

**Comment by bpasero** [comment]
Fyi I think for normal text editors we control this via the `originalEditable` option:

protected override getConfigurationOverrides(configuration: IEditorConfiguration): IDiffEditorOptions {
		return {
			...super.getConfigurationOverrides(configuration),
			...this.getReadonlyConfiguration(this.input?.isReadonly()),
			originalEditable: this.input instanceof DiffEditorInput && !this.input.original.isReadonly(),
			lineDecorationsWidth: '2ch'
		};
	}
