### ISSUE TITLE
Test: initial test coverage experience

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#199242]
Refs: https://github.com/microsoft/vscode/issues/123713

- [x] anyOS @aiday-mar
- [x] anyOS @luabud

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23199242%0A%0A&assignees=connor4312)

---

Initial worked happened this month on the test coverage API. Please read through [the API](https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.testCoverage.d.ts), make sure it makes sense, and try out the basic experience.

Note that in-editor decorations do not exist yet, but they will in a later iteration.

1. Clone and F5 the [test-provider-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/test-provider-sample). This marks lines as "covered" when it runs lines with math on them.
2. Go to the Test Explorer view, and run all tests
3. A Test Coverage view should be shown that contains a complete view of covered files in the test run. It should display coverage bars with a hover for precise details.
4.  Go back to the Explorer view. See that the bars appear on nodes in that view. You can toggle them off with the `testing.showCoverageInExplorer` setting.
5. You can dismiss the open coverage report via the action in the Test Coverage view, under the result in the Test Results view, or by running Clear All Test Results.

**Comment by aiday-mar** [comment]
Works well

**Comment by connor4312** [comment]
Good idea!
