### ISSUE TITLE
Missing Badge In Sidebar

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#199299]
Testing #199172

I think I can only reproduce when the "problems" pane is in the SCM view.

Note that there is no badge:

![Image](https://github.com/microsoft/vscode/assets/2931520/6da41375-eadd-444f-b891-bc7ef2309faa)

I don't know what exactly triggered it to finally update:

![Image](https://github.com/microsoft/vscode/assets/2931520/8e90471b-ae11-4373-9e33-bc4fcf7e6b2d)

**Comment by lszomoru** [comment]
I can repro using the following steps:
1. Open a folder/workspace that contains a git repository
2. Make sure that you do not have any pending changes
3. Move the problems view into the Source Control view container
4. Make a change to a file, and save the file
    * No badge is being shown
5. Move the Problems view out of the Source Control view container
    * Badge appears

@sandy081, @sbatten, any idea what is going on here?
