### ISSUE TITLE
Header separation is maybe a bit too subtle

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#199285]
Testing #199155

In this case it almost looks as if I am looking at one editor:

![Image](https://github.com/microsoft/vscode/assets/2931520/f4d0c3aa-29fc-4361-9fd0-271ef2c8dbc9)

*//edit @hediet: updated screenshot*

**Comment by hediet** [comment]
Closing because the initial screenshot showed an (unreproducible) bug.
