### ISSUE TITLE
I18N Support on extensions ?

### ISSUE THREAD

**Issue by ichiriac** [Microsoft/vscode#19927]
Hi,

I'm working on an extension authoring and I've found a way to define translation keys on package.json (with package.nls.json) but I'm wondering how to do the same with my code and also start some translations (english/french).

I've didn't find anything about this in the documentation but maybe I'm missing something.

Best Regards,
Ioan

**Comment by bpasero** [comment]
Please direct questions to http://stackoverflow.com/questions/tagged/vscode
