### ISSUE TITLE
Drag for multiple cursors

### ISSUE THREAD

**Issue by CodingHobby** [Microsoft/vscode#19925]
- VSCode Version: 1.9.0
- OS Version: Manjaro Linux 16.10.3

Could you include a feature similar to what Sublime Text has, where you can hold ALT and drag your mouse with the right button clicked to create multiple cursors on different lines? I really feel like this feature is missing. Thanks a lot!

**Comment by gansai** [comment]
Multiple cursors on different lines can be added in Ver 1.9.0 . Ctrl+ Alt + up to add cursor above.. Ctrl+ Alt + down to add cursor below.. Please check these shortcuts and also check the menu - under Selection. It has sub menus for these controls. Does this satisfy your requirement?

**Comment by bpasero** [comment]
Yeah thats it 👍
