### ISSUE TITLE
Seeing a bar on the left

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#199286]
Testing #199155

I am not sure what this bar does on the far left of the editor stretching vertically:

![image](https://github.com/microsoft/vscode/assets/900690/497a18c6-8e82-473b-ad57-c551e5458279)

**Comment by bpasero** [comment]
But for what reason? I am not even seeing the UX benefit, let alone that it takes real screen estate away from the editor.

**Comment by gjsjohnmurray** [comment]
Reducing it from its current 17px to 2px gains space for code but retains the visual indent sufficiently for me.

**Comment by hbons** [comment]
This seems to have been fixed with the new "card" design.
