### ISSUE TITLE
Test: JS Heap Snapshots viewer

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#199239]
Refs: https://github.com/microsoft/vscode/issues/191920

- [x] anyOS @eleanorjboyd
- [x] anyOS @aiday-mar

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23199239%0A%0A&assignees=connor4312)

---

This month I added a custom editor to allow viewing JavaScript heap snapshots.

1. Debug any JavaScript, and run Take Performance Profile > Heap Snapshot. That will collect a .heapsnapshot file into your workspace folder. (Doing this in browsers is fairly fast, but Node is slow and can take several moments)
2. Open the file. Poke around the table view and check that things are sane and work as they should. The numbers should match the same file opened in the Memory tab in Chrome (_not_ Edge, Edge tweaks Chrome's calculation)
3. Click on the "graph" button beside a node and see that it opens a graph of its retaininers. You will be prompted to install the [flame chart visualizer](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-js-profile-flame) if not installed, as it contains the heavier-weight graphing components.
4. Check that graph navigation is sane and works well. You can change the distance of displayed retaininers, but be warned that high numbers may take increasing amounts of time to chart, especially for Node.js profiles.

**Comment by aiday-mar** [comment]
Loving the graphic functionality ^^

**Comment by connor4312** [comment]
Thank you for the thorough testing :)

**Comment by IanButterworth** [comment]
The julia language Profile stdlib provides [a way](https://docs.julialang.org/en/v1/stdlib/Profile/#Heap-Snapshots) to record `.heapsnapshot` files that can be viewed in chrome devtools, but they hang indefinitely in this viewer and print the following error

```
2023-12-30 19:27:38.621 [info] ExtensionService#_doActivateExtension ms-vscode.vscode-js-profile-table, startup: false, activationEvent: 'onCustomEditor:jsProfileVisualizer.heapsnapshot.table'
2023-12-30 19:27:38.772 [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "invalid profile JSON".
```

Is there any way to get any further debug information?

Here is a zipped example [81416_881767189633791.heapsnapshot.zip](https://github.com/microsoft/vscode/files/13799559/81416_881767189633791.heapsnapshot.zip)

I thought I wouldn't open a dedicated issue until we can rule out the issue being on the julia side
