### ISSUE TITLE
Allow updating zen mode settings when in zen mode

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#199249]
Zen Mode cannot hide editor Tab

I am still unable to hide the editor Tab after switching to Zen Mode. I would like to be able to allow the user to hide the editor Tab after switching to Zen Mode to maximize the editor space.
![image](https://github.com/microsoft/vscode/assets/54253524/554402cc-35a0-41ae-897c-f2a8f577e9d8)

Windows 10
1.85 Preview

Hopefully this will be improved when 1.85 is released, thank you very much!👍

**Comment by zhouxinghong** [comment]
Thank you very much for adding many more interesting features to 1.85!👍

**Comment by zhouxinghong** [comment]
> You can use the `zenMode.showTabs` setting to hide tabs (currently only in insiders). Like all zen mode settings, they don't directly apply when already in zen mode and changing the setting. The changed settings applies the next time you open zen mode.

I've tried it but it doesn't work. . .

**Comment by zhouxinghong** [comment]
@benibenj 
Why can't it be hidden directly here? If the "zenMode.showTabs" setting is necessary, the user experience will be terrible. . .😒

**Comment by benibenj** [comment]
This is currently limited by the zen mode and not by editor tabs. It's the case for all settings which affect zen mode. I agree this is something we should support. I'll add this to the backlog.

**Comment by zhouxinghong** [comment]
Very good! 👍😜Thank you very much for your patience in listening to users!
At the same time, I wish you all the best in your work! 😜

**Comment by benibenj** [comment]
Added support to change most settings in zen mode (except `zenMode.fullScreen`). When in zen mode we now also show the `Tab Bar` submenu in the context menu of the tab bar which when toggled, affects the `zenMode.showTabs` setting instead of the `workbench.editor.showTabs` setting.
