### ISSUE TITLE
Test: Korean aware alt character search

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#199221]
Refs: https://github.com/microsoft/vscode/issues/196203

- [x] macOS @anthonykim1 
- [x] Windows @TylerLeonhardt 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23199221%0A%0A&assignees=Tyriar)

---

With https://github.com/microsoft/vscode/pull/196204 being merged the command palette (and other places, where ever uses `matchesWords`) are now able to search Korean input as if it were typed with a standard qwerty keyboard layout. This makes it behave much like most search engines:

<img width="643" alt="Screenshot 2023-11-27 at 12 36 54" src="https://github.com/microsoft/vscode/assets/2193314/71d14961-acb7-4c84-a147-319c37e1b418">

To test, open the command palette with hangul mode of the Korean IME on and start typing in English. Note that this only works right now for matching from the start of words, for example it cannot find the "nal" in "terminal". The feature issue is remaining open for some investigation into supporting the other matches functions https://github.com/microsoft/vscode/issues/196203

**Comment by anthonykim1** [comment]
loving the feature as I personally encounter this every day switching back and forth. It also seems to pick up word after the : sign, which is great. 
<img width="516" alt="Screenshot 2023-11-28 at 3 32 06 PM" src="https://github.com/microsoft/vscode/assets/62267334/cfc7e6da-43e7-4716-b950-bef12c3a4c60">

**Comment by joonseokhu** [comment]
One of the best feature of VSCode in 2022.
