### ISSUE TITLE
Terminal Sticky Scroll renders at wrong height when resizing

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#199294]
Testing #199240

When having a splitview terminal, resizing it such that it becomes small can cause the sticky scroll to render at the wrong top position.

![Recording 2023-11-28 at 11 13 54](https://github.com/microsoft/vscode/assets/44439583/c14c9127-1577-4ab3-9006-0a713aafe537)

**Comment by justschen** [comment]
Not just in split view, but also occurs when resizing the entire window.

**Comment by Tyriar** [comment]
Cannot reproduce:

![Image](https://github.com/user-attachments/assets/8858fcfe-6caa-40da-a241-2ec38d046f15)
![Image](https://github.com/user-attachments/assets/46535e85-3d8a-470f-b5ad-576086ef46aa)

Could again have been related to conpty https://github.com/microsoft/vscode/issues/224488
