### ISSUE TITLE
Too many borders, lines and wasted space

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#199351]
Testing #199155

Much better than the original design, but I still think we are using way too many borders, lines and the area between editors is taking too much height.
Can we make this leaner, and more compact?

fyi @hbons 

![Screenshot 2023-11-28 at 14 55 46](https://github.com/microsoft/vscode/assets/1926584/91182863-b498-45c4-8c45-2e294c6ceb20)

**Comment by hediet** [comment]
FYI @bpasero @alexr00 - pinging you because you expressed concerns that the file header is not very noticable.
Also related: https://github.com/microsoft/vscode/issues/199333

**Comment by isidorn** [comment]
Also there is too much glyph margin. Why does it look like double the width, is it really needed? I might be missing something. Thanks

**Comment by hediet** [comment]
> Why does it look like double the width, is it really needed?

It is because the file has more than 1000 lines, so there has to be space for 4 digits of line numbers.

**Comment by isidorn** [comment]
But even my files that have < 100 lines have extra glyph margin space?
Is that because we take enough margin to make room for the longest file?

Also I see we lose some space on the very left to make this whole multi diff editor appear as floating.

> Arguably, we don't need the glyph margin of the left side.

I noticed that we leave the glyph margin on the left side for the diff editor. So I would try to align here.

**Comment by alexr00** [comment]
I think removing the borders and reducing the space between files would make it even more difficult to tell when a file ends.

**Comment by bpasero** [comment]
My only concern is the strange box on the far left of editors that imho we should just remove. The headers imho are OK and make it a nice separation between editors.

**Comment by gjsjohnmurray** [comment]
Per https://github.com/microsoft/vscode/issues/199286#issuecomment-1829577804 I would prefer not to lose the left edge entirely, but 2px looks sufficient IMO.

![image](https://github.com/microsoft/vscode/assets/6726799/e673b0bb-cc42-43c4-bfaa-7584b1120e0b)

**Comment by hbons** [comment]
The focus border on the first line of each editor seems to contribute a lot to the noise. Do we need this?

**Comment by hbons** [comment]
Here's an option where I've completely disconnected the separate files. I prefer this approach for scanning, but it's not a simple fix. :)

<img width="777" alt="image" src="https://github.com/microsoft/vscode/assets/103326/8558880e-18b3-45f4-8c04-7d501198e207">

**Comment by hbons** [comment]
Variant with 100% width but keeping the gaps between files:

<img width="615" alt="image" src="https://github.com/microsoft/vscode/assets/103326/c30f109e-486c-471d-8d4f-36e0dc479739">

**Comment by alexr00** [comment]
I prefer the 100% width.

**Comment by gjsjohnmurray** [comment]
I prefer the first one. For me the second one's separators look like sashes I should be able to adjust.
