### ISSUE TITLE
Should clicking a file in a commit reveal the file in the entire commit's multi-editor diff?

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#199314]
Testing #199177

Right now clicking a file in a commit from the Incoming/Outgoing section opens a diff editor with that file. Clicking the `View Changes` action in the commit itself opens the new multi-editor diff.

💡 Idea: why not always open the multi-editor diff and just scroll to the file's top position, when clicking a file in a commit? Clicking another file would just make the editor scroll to the new position.

Thoughts @hediet?

**Comment by hediet** [comment]
I like the idea, we should explore this!

**Comment by lszomoru** [comment]
I like this. Do you think that it would make sense to collapse all files, except the one that the use clicked on? Assuming that we have a UI gesture to expand/collapse all files I think that I would prefer that.

**Comment by lszomoru** [comment]
Closing this issue as the incoming/outgoing section has been removed and no files are being shown in the "Source Control Graph" view.
