### ISSUE TITLE
outline and multiline string in 

### ISSUE THREAD

**Issue by APerricone** [Microsoft/vscode#19937]
- VSCode Version: 1.9
- OS Version:Ubuntu 16.10

Steps to Reproduce:

1. inside a javascript function write a literal string with the start of a HTML file, like this example:
```javascript
function a()
{
    var b=`<DOCTYPE html>
<html>`
}
```

2. close the outline of the function

see that the part of function after the html remains visible.

**Comment by aeschli** [comment]
I assume with 'closing the outline' you mean folding.

We currently only look at the indentation of a line to determine the folding regions.
To implement your request we need to add more language knowledge to the folding regions. We have issue #3422 for this
