### ISSUE TITLE
Activity bar keyboard focus skips showing Accounts tooltip on first pass

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#199391]
Testing #199199

1. Focus on activity bar
2. Use the keyboard to navigate down to the Accounts icon
3. All tooltips shown except on Accounts icon on first pass.
4. Returning to the Accounts using the `Up` arrow displays tooltip.

![Image](https://github.com/microsoft/vscode/assets/25044782/4c43d2de-fa7e-4394-88ed-765bc4aaec3e)

**Comment by meganrogge** [comment]
@bhavyaus could you pls enable screen cast mode so I can see which keys you're pressing?

https://github.com/microsoft/vscode/assets/29464607/56cceb34-fbf1-4308-96b3-8e0ed1263b62
