### ISSUE TITLE
Closing aux window focuses wrong "main" window

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#199372]
* have two screens and two windows of vscode
* have one window on screen A and the other window on screen B
* in screen A, create a aux window, move it to screen B
* close the aux window
* the main window on screen B get focused, not the origin window on screen A

**Comment by bpasero** [comment]
@jrieken curious, did you have editors in the aux window before you closed it? Because closing an aux window moves those editors back to the "main" window and will in turn focus it.

**Comment by jrieken** [comment]
Yeah, I had an editor in there and I mean I close the last editor which closes the aux window which then focuses the wrong main window

**Comment by bpasero** [comment]
To truly focus the right window in terms of MRU, we need https://github.com/microsoft/vscode/issues/199529. But the fix I can do for now is to ensure the main window gets focus.
