### ISSUE TITLE
Wrong windows closed

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#199363]
Testing #199023

- Open window 1 with a workspace folder open. Open a few files.
- Drag one editor to a floating window of window 1.
- In window 1: File > New Window a window 2.
- Drag the editor from the floating window of window 1 to window 2.
- In window 2: File > Close Window.
- Window 1 and its floating window close. 🐛 

Testing on Linux. It doesn't always happen, can't figure out when it does vs. when it doesn't.

**Comment by bpasero** [comment]
I am not entirely sure this is floating window related. Since you have 2 full windows and pick an action from the main menu, this could also be an issue we always had.

Does it reproduce in stable? Does it reproduce with native vs custom title bar?

**Comment by chrmarti** [comment]
I have seen it with the custom title bar. Can't reproduce currently in today's Insiders (tried custom and native title bar).
