### ISSUE TITLE
Support hiding tree sticky scroll via context menu

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#199381]
Testing #199153

Editor and terminal sticky scroll can both be disabled by right clicking it.

**Comment by benibenj** [comment]
I agree we should support something similar, however, right clicking opens the context menu of the tree item and I don't think we should add it to these context menus as there is already a lot going on in them. Do you by chance have an other idea how we could support this nicely for the tree SS?

**Comment by benibenj** [comment]
Closing as there are no plans or even ways to do this at the moment
