### ISSUE TITLE
Terminal can not detect keyboard/mouse interactions correctly

### ISSUE THREAD

**Issue by Ramin-RX7** [microsoft/vscode#199370]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: Windows10

When working with some python packages such as `unicurses` I face an issue with terminal. Packages like that are used to interact with terminal with keyboard and mouse buttons. The problem in VSCode terminal is that I think the key presses are not directly sent to the shell session and something is in the middle of this route.

A simple way to demonstrate the problem is using one of the `unicurses` [examples](https://github.com/unicurses/unicurses/blob/master/demos/test_keymenu.py) which works perfectly fine in cmd, powershell, etc. But if you run it in the vscode terminal (with any shell you want) It will not work.

(This issue is filled in a bug report template, however I'm not sure what I'm asking is a bug or a feature request)

**Comment by meganrogge** [comment]
You can enable `terminal.integrated.sendKeybindingsToShell` for your use case

**Comment by Ramin-RX7** [comment]
@meganrogge The solution provided did not change the result. Can you review it again?

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You will need to upgrade Windows to use conpty. You can read more about ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423) and [here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue).

/duplicate https://github.com/Microsoft/vscode/issues/45693
