### ISSUE TITLE
Colors should be equal or more different

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#199350]
Testing #199155

Right now the gray in the margin is slightly different than the gray in the hidden lines info bar. IMHO we should either make them equal or make them more different, the shades are very close now which makes it feel like something is off.

<img width="288" alt="image" src="https://github.com/microsoft/vscode/assets/5047891/49b33f25-3621-44b1-88de-3b70c62d85a3">

**Comment by hbons** [comment]
agree. @hediet can we use the same grey background as the gutter for the hidden lines?
