### ISSUE TITLE
Plus button to add a comment doesn't disappear when leaving the editor area

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#199342]
Testing #199155

* open a multi-diff editor using GHPRI
* move your mouse in the editor and leave it
* observe that the plus disappears only when leaving the editor in a very specific way but most of the times sticks around incorrectly

https://github.com/microsoft/vscode/assets/5047891/92779f57-048a-433f-aec7-e9f706903a2f

**Comment by creeper0167** [comment]
Can i work on this issue and take a shot at it?

**Comment by alexr00** [comment]
@creeper0167 thanks for your interest in contributing to the project! I don't know where the bug is yet for this, so I can't provide any pointers. I would recommend choosing a different issue if you want to contribute!
