### ISSUE TITLE
Testing JS Heap Snapshots Viewer: bar-charts are a bit unclear and they overlap

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#199326]
Testing #199239

I noticed there were horizontal grey lines (sort of an underline) with a grey background right under some of the memory usage values. When I opened up the nodes in the graph, I understood that these correspond, presumably, to a bar chart indicating the relative usage percentage. I thought maybe it would have been more clear those were bar-charts if they were displayed in an adjacent separate column. You could also have the actual percentage value indicated at the 'top' of the bar so the user sees an associated numerical metric.

The bar-charts in the left and in the right column also overlap. In the image below you can see that for the built in module node the left and right bar-charts overlap a bit creating a more opaque white region. 

<img width="317" alt="Screenshot 2023-11-28 at 13 37 26" src="https://github.com/microsoft/vscode/assets/61460952/5a3ec39e-e64d-473c-8a84-de3f1a2c86fa">

**Comment by connor4312** [comment]
I added the % to the title displayed when hovering over a bar
