### ISSUE TITLE
Activity bar hover on focus doesn't work when using combination of tab and arrows

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#199396]
Testing #199199

1. Here's what I have in the activity bar:
![image](https://github.com/microsoft/vscode/assets/38270282/21b81cbf-d36d-4287-b89e-dbf1f48fbed2)
2. Turn on tab moves focus
3. Tab until you get to the Account icon in the activity bar. The "Accounts" hover shows correctly
4. Arrow up **once**. The Remote Explorer hover doesn't show.
![Recording 2023-11-28 at 18 19 10](https://github.com/microsoft/vscode/assets/38270282/134493bd-dfb8-4886-a957-4dbf2210cc14)

**Comment by meganrogge** [comment]
Oh, I see - what's happening is to move between the two segments of the activity bar, you have to use `Tab or Shift+Tab`. Since you don't do that, the item is not focused and the hover is closed (on blur).
