### ISSUE TITLE
[Idea] AI actions should respect Copilot Completions language disablement

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#199379]
Testing #199158

1. Open a file that you don't want Copilot Completions in such as JSONC
2. Click the Copilot status icon
3. Click "Disable Completions for 'jsonc'
4. Copilot icon now shows disabled, but I still get sparkle AI actions

It would be neat if this was all hooked up so I could turn off AI actions, completions, and other automatic UI elements that are AI related for certain language types. I believe inline chat can of course stay enabled because it's manually triggered, but the icons don't make much sense for me in something like a markdown file.

**Comment by aiday-mar** [comment]
I think this makes sense thanks for picking up on it

**Comment by aeschli** [comment]
`Disable Completions` is really about completions. But yes, it makes sense that we also add an entry to that menu to turn off AI code actions. I don't think we need this per language.

**Comment by aiday-mar** [comment]
Do you mean we should add a setting in that menu to change the value of `github.copilot.editor.enableCodeActions` or to change `editor.lightbulb.experimental.showAiIcon`? The latter one is a generic setting that applies to all AI code action contributing extensions, I suppose we don't want that.

**Comment by aeschli** [comment]
Yes, menu actions from that menua ideally only change only 'githb.copilot` settings.

We need to decide if we want to implement the idea that `editor.lightbulb.showAiAction` also would filter AI code actions. (https://github.com/microsoft/vscode/issues/199459).

**Comment by aiday-mar** [comment]
I am wondering if we want the setting to be shown in the view that appears when you click on the copilot logo in the status bar. In the view there is the action `Edit settings...` which opens up the settings editor with the `Github Copilot` search filter. In particular the following setting appears `github.copilot.editor.enableCodeActions`.

<img width="608" alt="Screenshot 2023-12-04 at 13 07 04" src="https://github.com/microsoft/vscode/assets/61460952/e689e967-5384-4ab4-98b0-311845d08ad8">

For the other point, the following merged PR (https://github.com/microsoft/vscode/pull/199642) already implemented this.

**Comment by aiday-mar** [comment]
After some more thought, I think having the `Edit Settings...` entry in the Copilot menu should be sufficient to disable AI actions. I will close this issue. Feel free to comment if you'd like to discuss this some more
