### ISSUE TITLE
Extension auto update checkbox not preserved

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#199336]
1. Install GitHub copilot pre-release
2. Click on the Copilot Chat extension. Disable Auto update
3. Reload VS Code
4. Open Copilot Chat extension. Click on Auto update checkbox to enable it
5. Open some other view, got back to Copilot chat. The checkbox is unchecked 🐛 

https://github.com/microsoft/vscode/assets/1926584/463432ad-0ec0-465f-9276-d8572a56ba1a

**Comment by sandy081** [comment]
I am not able to reproduce this. Am I missing any steps?

**Comment by isidorn** [comment]
Yes. I can also not reproduce this anymore. Sorry. But yesterday I could not check that checkbox in any way.
Though I can still reproduce https://github.com/microsoft/vscode/issues/199339 easily

**Comment by sandy081** [comment]
Ok. Please reopen it if you can repro again.

> Though I can still reproduce https://github.com/microsoft/vscode/issues/199339 easily

This is known and I made it intentionally - Please see https://github.com/microsoft/vscode/issues/199413
