### ISSUE TITLE
Tree Sticky Scroll - difference in behaviour when right clicking

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#199366]
Testing #199153

* When one right clicks on a node, the node gets the focus indicator  
    <img width="520" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/ba989212-3953-41f6-ab59-1c5dbcc154ef">
* When one right clicks on a sticky node, the node does not get the focus indicator:  
   <img width="433" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/ef1670ec-aa6c-48d4-9a69-5ac019911c31">

**Comment by benibenj** [comment]
I haven't added this because we don't properly support navigating the sticky scroll widget with the keyboard. Will add this together with general keyboard navigation on the widget: #199373
