### ISSUE TITLE
Terminal Sticky Scroll disappears when the beginning (not the end) of code block reaches the end of the scope

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#199305]
Testing #199240

So I was testing the terminal sticky scroll and I noticed that the sticky code block disappears in an abrupt manner when the beginning (not the end) of the multiline terminal command, reaches the end of the scope. To give more context about what I mean, I added the GIF below. I was sort of expecting the code block to start disappearing when the line `>  `  reached the end of the output for that command. I noticed that the code block disappeared however when the line `echo hi; \` reached the end of the output for that run.

https://github.com/microsoft/vscode/assets/61460952/8c92b925-f29a-498a-a8f0-cd438e6d6c6c

I don't think this is a problem per say, it's a different manner of animating sticky scroll. I was just wondering if this is intended? I think the potential issue with this approach is that the sticky scroll block is hiding the next terminal command and its output while you are scrolling until it disappears. In the editor, sticky scroll starts disappearing progressively when the bottom of the last block/line touches the end of the scope. Perhaps we could explore something similar?

https://github.com/microsoft/vscode/assets/61460952/e3c8fdf2-7dc1-4363-a9f7-ff403a36f533

**Comment by Tyriar** [comment]
This is actually a bug, it's meant to scroll up as in the editor and was doing that at some point. Note that it's not as smooth as the editor since there's no "partial line scrolling" in the terminal

**Comment by Tyriar** [comment]
Repro that demonstrates more clearly what's happening:

Run:

```
echo "
> 1
> 2
> 3
> 4
> 5
```

Run:

```
echo "
> 6
> 7
> 8
> 9
> 10
```

Run:

```
echo "
> 11
> 12
> 13
> 14
> 15
```

🐛 when scrolling, sticky scroll from a command should never obscure the command below it like this:

![image](https://github.com/microsoft/vscode/assets/2193314/2438d9d7-df6f-4463-aa61-085e9c7571dc)

**Comment by meganrogge** [comment]
@Tyriar I see the prompt line sort of being obscured here 🤔 

https://github.com/microsoft/vscode/assets/29464607/46b4584a-b9fe-42ae-b4e1-6d124032f644
