### ISSUE TITLE
Problem visibility setting does not reflect state in problem view

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#199300]
Testing #199247

* Set `"problems.visibility": false,`
* Open a file with some error
* See the problem view still reports the error despite explorer and outline view working as expected

<img width="1440" alt="Screenshot 2023-11-28 at 19 42 36" src="https://github.com/microsoft/vscode/assets/964386/fee73d13-a18f-4e86-a570-2210db944a4d">

**Comment by roblourens** [comment]
I think this is good. You still get a view of the errors in the workspace without them being in your face, and you can totally hide this view if you don't like it.
