### ISSUE TITLE
File headings should have a different background color than lines

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#199333]
Testing #199155

* just scrolling around
* it is difficult to tell when moving from one file to another just by focusing your eyes on the right-hand-side
* IMHO the problem is that the background color of the file heading is not easily distinguishable from the lines background
* IMHO the background color for the hidden info bar is too proeminent and attracts too much attention compared to their relative importance with the file heading.
* My suggestion would be to explore making the hidden info bar use the white background and use the gray for the files because those are much more important separators. 

https://github.com/microsoft/vscode/assets/5047891/8735e797-252c-4e9f-9d72-e5f15bb95d6f

**Comment by hediet** [comment]
@hbons what do you think?

I fear that if the hidden-lines-bar have a white background, they will have the same problem of not being easy to recognize.

**Comment by hbons** [comment]
we can play around with the base colour. also the file names seem to be missing?

**Comment by hediet** [comment]
> also the file names seem to be missing?

The screenshot is of the right side of the side-by-side view. The file name is on the left side, so not visible here.

**Comment by hediet** [comment]
I implemented @hbons design in https://github.com/microsoft/vscode/pull/202108.
Assinging this issue to @hbons to decide if the header should have a different color or not.

I still like this design, which would also solve this problem:

https://private-user-images.githubusercontent.com/103326/286603902-8558880e-18b3-45f4-8c04-7d501198e207.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MzgyMDAsIm5iZiI6MTcwNDgzNzkwMCwicGF0aCI6Ii8xMDMzMjYvMjg2NjAzOTAyLTg1NTg4ODBlLTE4YjMtNDVmNC04YzA0LTdkNTAxMTk4ZTIwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQyMjA1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGU0ZjAzZDZmNWYzZTBiNjhjYTk4NDc5Njg3M2Y1MmYwNDljYmJkZjVlNjQ4OWM5MDFiMzU1Y2QyZGNmMzU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jONu_QL6EsVxz-V54ZuCfA9gEZeFzeYCEI92l2FjXrI
