### ISSUE TITLE
Switching document tab makes 'Remove Unnecessary Usings' pops up.

### ISSUE THREAD

**Issue by antonkudin** [Microsoft/vscode#19938]
- VSCode Version: Code - Insiders 1.10.0-insider (723b20093d2f525e84cdf94a52f7695d1d539273, 2017-02-03T08:24:58.073Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharpfixformat|Leopotam|0.0.8|
|unity-tools|Tobiah|0.1.9|
|unity-snippets|YclepticStudios|0.1.2|
|csharp|ms-vscode|1.6.2|
|theme-actual-obsidian|zehfernando|1.4.2|

---

Steps to Reproduce:

1. Click other tab, cmd+alt+direction to switch or cmd+number to create new window.

**Comment by bpasero** [comment]
@antonkudin please add more details what you mean

**Comment by antonkudin** [comment]
Its manifested again, here's a gif of it in action.
Only middle tab here makes the popup appear.

I use mouse clicks couple times to switch tabs, then use keyboard shortcut and popup still appears out of nowhere.
![2017-02-07 22_21_43](https://cloud.githubusercontent.com/assets/8632082/22707463/ec630970-ed83-11e6-8c0e-857e2a32a3ba.gif)

**Comment by antonkudin** [comment]
It also seems like having top line in a document be one of the unused 'using'-s makes it appear (it appears underlined in green). Doesn't happen if top 'using' is actually important for this document's code.

**Comment by Tyriar** [comment]
This is related to the C# extension, please file this at https://github.com/OmniSharp/omnisharp-vscode/issues/new
