### ISSUE TITLE
Testing JS Heap Snapshots Viewer: Code text horizontally cut off before attaining scrollbar

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#199323]
Testing #199239

The text representing the code associated to the memory usage appears to be cut off much earlier than the full horizontal space it could span. The text could span the full width. I was wondering if this was intended?

<img width="1127" alt="Screenshot 2023-11-28 at 13 30 40" src="https://github.com/microsoft/vscode/assets/61460952/8f059b7b-86b8-4f8d-9181-2c9d57309892">

**Comment by connor4312** [comment]
We can increase the length displayed before truncation
