### ISSUE TITLE
Outgoing counter doesn't update when committing

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#199310]
Testing #199177

<img width="341" alt="image" src="https://github.com/microsoft/vscode/assets/22350/b2c1f767-7a88-437c-b12e-078ff4317228">

1. In the integrated terminal run `git commit --allow-empty -m foo`. Notice the outgoing section comes up with `1` as the counter
2. Run it again. Notice the sync button updates to show `2`, but the outgoing section still shows `1`

**Comment by joaomoreno** [comment]
This might actually be specific to empty commits only. I can't repro when commits actually have changes. Also, the whole tree breaks down, not just the counter.

Related to #199311 ?

**Comment by lszomoru** [comment]
@joaomoreno, I am unable to repro with empty commits but this seems like an issue that I have trying to track down for a long time where the Incoming/Outgoing changes information is not getting updated following an action (ex: checkout, commit, sync changes). If you have a repro I would love to take a look. My current theory at the moment is that the cache invalidation does not occur as expected. Does the counter gets fixed if you press the Refresh button?

**Comment by lszomoru** [comment]
I have tracked down an issue (checking out a tag or a detached commit) that would get the tree in a bad state. I am hoping that this also addresses the issue in which the tree is not being refreshed. Closing this issue but please let me know if you can reproduce again. If so, please check the dev tools console to see if any exception was thrown. Thanks!

**Comment by joaomoreno** [comment]
I did check at the time, and there were no devtools errors. 👌 Will try to break it again today!
