### ISSUE TITLE
"[nim]": { "editor.tabSize": 2 } Unknown identifier

### ISSUE THREAD

**Issue by yay** [Microsoft/vscode#19930]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.8|
|code-runner|formulahendry|0.6.7|
|nim|kosz78|0.5.14|
|vscode-clang|mitaki28|0.2.1|
|vscode-lldb|vadimcn|0.3.3|

---

Steps to Reproduce:

1. Install the https://marketplace.visualstudio.com/items?itemName=kosz78.nim extension
2. Try setting default tab size to 2 spaces as a language specific setting. Many editor options are available, but tabSize is not one of them.

**Comment by mgasparel** [comment]
Just noticed this myself when attempting to set a javascript-specific tabsize setting. Many editor options available, but not tabsize.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/19511
