### ISSUE TITLE
Find in all files should sort by priority

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#19939]
Find in all files should sort using the following priority by default:

1. Results in current active file
2. Results in opened files 
3. Results in recent files
4. All other files

Brackets all file search for example does a sorting similar to the above which is very useful.

There should be a button to also do an alphabetical sort.

**Comment by dakaraphi** [comment]
@bpasero Without comment, I'm not sure why the dislike.
This was a very popular feature for Brackets.  I can understand not wanting to change default behavior, but seems this would be useful as an option.

This provides the following benefits which have been requested separately:

- I can see a list of all matches in my current file.  This is often useful as a temporary right side bookmark navigation in my current file.  Similar to #14836
- It is often that I am more interested in matches for all the files in which I am currently working.  Seeing them organized together helps speed up my workflow.  Similar to #18796
- Also, when there are too many hits to show all results, showing those hits for files I am currently working as a priority seems it would be useful.

It seems it would be useful that a user could then choose sorting priority method such as:

- current vscode default
- active/open file priority
- number of hits
- alphabetical

**Comment by bpasero** [comment]
Not much to comment here other than I like our current sorting (strictly alphabetical to workspace context) and I would not benefit from any other sorting. It is the same sorting I have in the explorer and in git changes view.

**Comment by dakaraphi** [comment]
Ahh thanks.  I actually did not understand how it is currently sorted.  In a project with thousands of folders, the results don't seem to have an order, but now I do see the pattern.

For me there are 2 general search cases:

- **Completeness**:  In this case, sort order is probably not even important generally for me.  I just need to know if this term exists anywhere, how many matches, and all files containing term.
- **Current task workflow**:  In this case, I have set of tasks I'm working.  I want to know where a term exists in all files I'm currently working as the term may be a term used throughout the project, but the scope of interest is related to my current working context.  This might not seem apparently useful for smaller projects, but in my case working on something on the scale of million lines of code it is useful.

As an alternative, some type of method to more quickly apply scoping could also work for my use case.  I haven't found folder organization usually important, but that could be due to my projects folder structure which is too large and deep to be useful in the results view.

**Comment by roblourens** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
