### ISSUE TITLE
Extensions: Include and release additional (resource) files with a project

### ISSUE THREAD

**Issue by mkloubert** [Microsoft/vscode#19935]
I would like to develop an extension that runs a [NodeJS server](https://nodejs.org/api/http.html#http_http_createserver_requestlistener), written in [TypeScript](https://www.typescriptlang.org/).

I would like to include other things as my generated `.js` files, like `.css`, fonts or images, that should be released with my extension into `/out/src` folder.

The only workarround I know, is to include these files as Base64 encoded data in TypeScript files:

```typescript
// resources.ts

export RESOURCES = {
    'my-css-file.css': 'LyogVmlzdWFsIFN0dWRpbyBDb2RlIHJvY2tzISAqLw0KDQpib2R5IHsNCiAgICAvKiBhd2Vzb21lICovDQp9DQoNCmhlYWQgew0KICAgIC8qIGJyaWxsYW50ICovDQp9'
}
```

I don't think that this is a good solution. Libraries like [FontAwesome](http://fontawesome.io/) or [Bootstrap](https://getbootstrap.com/) will increase the code extremly.

Is there a way to setup things like the `package.json` file to link to external files that should also be released with the extension?

**Comment by joaomoreno** [comment]
`vsce ls` will list all the files that will be included in your extension package. By default it includes all files in the `cwd`. You can ignore some using the `.vsceignore` file.

https://code.visualstudio.com/docs/tools/vscecli
