### ISSUE TITLE
Testing JS Heap Snapshots Viewer: Have button to sort in decreasing/increasing order on clicking on `Self Size` or `Retained Size`

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#199320]
Testing #199239

So I was looking at the .heapsnapshot file in VS Code, and I noticed that when you click on the `Self Size` or `Retained Size` text, the memory usage is sorted in decreasing order relative to that metric (the other column being updated too). I was a bit expecting the memory to be sorted in increasing order on click (which would mirror the behavior in the memory tab of the dev tools). Perhaps we could have an additional button to sort in decreasing order?

https://github.com/microsoft/vscode/assets/61460952/521ceee1-cb6f-4637-b878-2d2829a758d8

**Comment by connor4312** [comment]
This is something I didn't bother doing. In my experience, if I'm looking at the overall table, it's to find the things that are retaining the most memory; I don't care about the smallest things. If we get a feature request, I can add it, but I don't think it's worth the trouble right now.
