### ISSUE TITLE
Command "start inline chat" is missing from command palette

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#199371]
<img width="2560" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/7e63e0ea-afb9-4048-bcb3-708c7ce33e8f">

**Comment by jrieken** [comment]
@ulugbekna you don't seem to have an editor open

**Comment by ulugbekna** [comment]
Doesn't seem to be the problem: 

<img width="1252" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/a83f5635-d9e7-443c-9d58-3eeb7153f4c7">

**Comment by jrieken** [comment]
Maybe because the commands wants editor focus:

https://github.com/microsoft/vscode/blob/2c13662a9ed3ed1d9125cbab63e89139ec82bb59/src/vs/workbench/contrib/inlineChat/browser/inlineChatActions.ts#L46

Tho, I assumed that the command palette evaluates before stealing focus. Need to investigate

**Comment by jrieken** [comment]
Also "Show Diff" shouldn't be there
