### ISSUE TITLE
Screen 🧀 on empty commits

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#199311]
Testing #199177

1. Run `git commit --allow-empty -m foo`
2. Reveal the commit in the outgoing section

🐛 Notice the empty square in All Changes

<img width="429" alt="image" src="https://github.com/microsoft/vscode/assets/22350/ac2fcd05-d4d3-4685-a76e-238ed1875f45">

**Comment by lszomoru** [comment]
Diff statistics badge will always contain the number of files:
<img width="474" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/abc91e25-b1cd-4914-be64-415be1fbab60">
