### ISSUE TITLE
"Show all" is bad action title

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#199348]
Testing #199155

"Show all"  is very generic. Can we have a more precise title message of the action.
For example "Show unchanged region", "Expand unchanged region"...

![Screenshot 2023-11-28 at 14 53 22](https://github.com/microsoft/vscode/assets/1926584/59b08094-951d-45e2-ac98-ac05c1d07b14)

**Comment by hediet** [comment]
That's how github does it:

![Image](https://github.com/microsoft/vscode/assets/2931520/57ce9035-8234-4f06-bda7-f73b7223fdec)

I like "Show unchanged region" though.

**Comment by isidorn** [comment]
Ok, I think we can be better than GitHub here :)
And make sure to use right capitalisation of words.
