### ISSUE TITLE
Scm generate commit message button focus outline not shown on hover

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#199340]
1. Move keyboard focus to SCM generate commit message button
2. Notice the nice blue outline being rendered
3. Mouse hover over the button. The outline is no longer visible 🐛

**Comment by lszomoru** [comment]
Is the button enabled or disabled? I am asking as from what I can tell the pattern is that for enabled buttons the focus outline is not persisted when the button is hovered over. Disabled buttons persist the focus outline as they do not have a hover.

**Comment by lszomoru** [comment]
Reopening as I implemented the wrong fix.

**Comment by isidorn** [comment]
The button is enabled.

I noticed that in the Find Widget for example the focus outline is persisted on hover. Which imho is the natural thing to do.

**Comment by lszomoru** [comment]
With the PR linked above, the behaviour will be consistent with the rest of the actions. We can start a separate conversation whether we want to update **all** actions to keep the focus border on hover.
