### ISSUE TITLE
Push and sync actions should not be options when in detached state

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#199313]
Testing #199177

1. Checkout a specific commit, not a branch, to go to a detached state

🐛  Notice the SCM button still lets you `Commit & Push` (among others). None of the "sync" actions make sense in detached state. One can only commit. And an idea for a default button when there are no changes: `Create Branch`.

<img width="506" alt="image" src="https://github.com/microsoft/vscode/assets/22350/88c8120e-a6d3-4a1c-b37d-6d2f02dfa17e">

**Comment by lszomoru** [comment]
Created https://github.com/microsoft/vscode/issues/199322 to track the `Create Branch` action button.
