### ISSUE TITLE
[proposal] Ability to export all installed extensions & share that with other PCs to install

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/vscode#19933]
- VSCode Version: **1.9**
- OS Version: **Any**

> The idea is simple but I was digging around to see if it was available anywhere without any luck.

It'd be great to be able to select some **"Export All Installed Extensions"**, maybe somewhere here in the menu options for extensions.

This would be great, so that you could easily **share** those 20+ favorite extensions you have with friends, or even all the laptops/PCs you might have with VSCode installed, *and get up to speed in seconds*. 

Maybe even an IT solution that is pre-installing VSCode on new machines and wants them all to have the same baseline extensions.

![image](https://cloud.githubusercontent.com/assets/2574412/22619267/2967c12a-eabf-11e6-8749-acfc59f96ae7.png)

^ Maybe somewhere here in this menu?

---

Anyway just an idea, ❤️  VSCode, just thought I'd get the idea out there, see if others would be interested in it as well!

**Comment by mlewand** [comment]
@MarkPieszak There's a great extension for that purpose called [Settings Sync ](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync). Make sure to check it out.

I'm using it across my different machines to keep the settings synced.

**Comment by sandy081** [comment]
@MarkPieszak Closing this in favour of Settings Sync extension.

**Comment by MarkPieszak** [comment]
Not a problem, thanks @sandy081 !
