### ISSUE TITLE
Module import and decorator error messages

### ISSUE THREAD

**Issue by btroncone** [Microsoft/vscode#1993]
VSCode sporadically gives errors for valid modules/imports as well as classes regardless of settings in tsconfig. The below error messages will appear in one file in a project while an adjacent file with the same imports has no error message. These modules are valid and are passed through TSC with no problems. Local module imports seem to work without issue.

![image](https://cloud.githubusercontent.com/assets/5085101/12306172/6e58f88e-ba06-11e5-8535-89731a2695f2.png)

![image](https://cloud.githubusercontent.com/assets/5085101/12306256/d4cfe898-ba06-11e5-9085-53e333f08206.png)

**Comment by dbaeumer** [comment]
@btroncone: how does the tsconfig.json file look like. Could it be that the other file is not covered by the tsconfig.json file since you use a files section

**Comment by btroncone** [comment]
This is an example tsconfig.json file being used in a project. In this circumstance VSCode is throwing an error on all external modules. 

```json
{
  "compilerOptions": {
    "allowNonTsExtensions": true,
    "isolatedModules": true,
    "noLib": true,
    "target": "ES5",
    "module": "commonjs",
    "noEmitOnError": false,
    "rootDir": ".",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": false,
    "inlineSourceMap": false,
    "inlineSources": false,
    "moduleResolution": "node"
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false
}
```

![image](https://cloud.githubusercontent.com/assets/5085101/12354425/def02abe-bb63-11e5-9f83-8f1affc3978e.png)

**Comment by dbaeumer** [comment]
@btroncone you set the moduleResolution to 'node'. Where do ionic-framework/ionic live. With moduleResolution: 'node' the tsserver which VSCode uses looks in the node_modules folder for these files. Same for angular. You might want to read up about node module resolution of d.ts file here: http://blogs.msdn.com/b/typescript/archive/2015/09/16/announcing-typescript-1-6.aspx

**Comment by btroncone** [comment]
That's correct, these modules live in the root of the project under the node_modules folder. The example I am referencing above is the base Ionic v2 project in case you need to reproduce.

**Comment by dbaeumer** [comment]
@btroncone I am not a Ionic expert. Is there a git repository I can clone to get a starter project.

**Comment by btroncone** [comment]
Sorry, yes, the easiest way to get started would be:

1.) npm install -g ionic@beta
2.) ionic start exampleApp tabs --v2 --ts

This will give you a starter project which will allow you to reproduce the issue.

Additional documentation: http://ionicframework.com/docs/v2/cli/

Thanks for your help!

**Comment by dbaeumer** [comment]
@btroncone thanks for the steps.

The default setup works for me out of the box using your steps. See screen shot

![capture](https://cloud.githubusercontent.com/assets/1931590/12505794/3603c316-c0ea-11e5-9bb1-7ce2b8cc85e8.png)

**Comment by dbaeumer** [comment]
Importing testing works as well:
![capture](https://cloud.githubusercontent.com/assets/1931590/12505834/7bb3d64e-c0ea-11e5-8537-c88e992d1e8b.png)
 @btroncone do you have any additional steps.

**Comment by btroncone** [comment]
Interesting, I'm working with a team of developers building Ionic v2 apps all experiencing the same errors. I will post a sample repo to GitHub shortly. Thanks for the quick feedback.

**Comment by btroncone** [comment]
@dbaeumer Thanks for your help, it appears I had one of my config options wrong as it seems to work as intended with the below config. I believe this issue can be closed.

```json
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "noEmitOnError": false,
    "rootDir": ".",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": false,
    "sourceRoot": "",
    "inlineSourceMap": false,
    "inlineSources": false
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false
}
```

**Comment by dbaeumer** [comment]
Closing then.

**Comment by dbaeumer** [comment]
Sorry, was closed :-). Wrong button
