### ISSUE TITLE
Terminal Sticky Scroll slightly jumps when multiline command appears

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#199304]
Testing #199240

I am not sure if this is intended, I noticed that while I was dragging the top of the terminal down, when the sticky scroll block appeared, it jumped down a bit. It's as though a new div was added at the top which caused the lines to be shifted down.

https://github.com/microsoft/vscode/assets/61460952/d86de42c-a5b9-45a8-a71c-549b8d70ea38

**Comment by Tyriar** [comment]
I think this is by design, is your issue the fact that the terminal cannot scroll partial lines like this so it's more jarring?

![image](https://github.com/microsoft/vscode/assets/2193314/e34e92d4-c449-43ed-9b65-6d5147f4e087)
