### ISSUE TITLE
Tree sticky scroll doesn't work as expected in searxch view

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#199383]
Testing #199153

The file name isn't covered, probably due to how the search tree is implemented.

![image](https://github.com/microsoft/vscode/assets/2193314/dc810bec-7944-4ef8-8aea-b49265021165)
![image](https://github.com/microsoft/vscode/assets/2193314/dd9d4773-4f84-4111-82ae-95e0fb9eaadb)

**Comment by benibenj** [comment]
Do you mean it's not detecting the tree node with the file name as sticky? Not able to reproduce that. Did you maybe set the `workbench.tree.stickyScrollMaxItemCount` value to 1?

**Comment by andreamah** [comment]
I also couldn't repro this in the tree view for search.

**Comment by Tyriar** [comment]
Oh, I guess it was due to the tiny height of the tree then. This is actually working fine then 👌
