### ISSUE TITLE
Highlight occurences on multiple files stopped working

### ISSUE THREAD

**Issue by omermizr** [microsoft/vscode#199315]
Type: <b>Bug</b>

This worked well in the first iteration, but looks like it stopped working. I saw the setting was changed to the `occurrencesHighlight` enum, but even after changing it it only highlights within the same file.

VS Code version: Code - Insiders 1.85.0-insider (Universal) (dcb066e3ae59baa89654ebca3b12aae7c35477a3, 2023-11-28T07:30:22.020Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|41, 28, 18|
|Memory (System)|32.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 70a87a82-3a18-4efd-a579-683643eba8e8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
TabOut|alb|0.2.2
Bookmarks|ale|13.4.2
scratchpads|bue|1.0.0
path-intellisense|chr|2.8.5
regex|chr|0.4.0
vscode-eslint|dba|2.4.2
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|2023.11.2804
prettier-vscode|esb|10.1.0
vscode-expo-tools|exp|1.0.7
vscode-jest-runner|fir|0.4.69
code-runner|for|0.12.1
shell-format|fox|7.2.5
copilot|Git|1.138.570
copilot-chat|Git|0.11.2023112803
copilot-labs|Git|0.17.1121
remotehub|Git|0.62.0
gitlab-workflow|Git|3.87.0
todo-tree|Gru|0.0.226
selected-lines-count|gur|1.4.0
debug-visualizer|hed|2.4.0
realtime-debugging|hed|0.1.0
vscode-power-mode|hoo|3.0.2
search-editor-apply-changes|jak|0.1.1
jwt-decoder|jfl|1.2.0
svg|joc|1.5.3
git-graph|mhu|1.30.0
vscode-docker|ms-|1.28.0
dotnet-interactive-vscode|ms-|1.0.4577061
vscode-edge-devtools|ms-|2.1.3
jupyter|ms-|2023.11.1003341000
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-repositories|ms-|0.40.0
vscode-js-profile-flame|ms-|1.0.8
vscode-typescript-next|ms-|5.4.20231127
vscode-react-native|msj|1.12.2
color-highlight|nau|2.5.0
vscode-twoslash-queries|Ort|1.2.2
vscode-versionlens|pfl|1.9.2
quicktype|qui|12.0.46
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
partial-diff|ryu|1.4.3
vscode-javascript-booster|sbu|14.0.1
vscode-fileutils|sle|3.10.3
code-spell-checker|str|3.0.1
even-better-toml|tam|0.19.2
luna-paint|Tyr|0.16.0
errorlens|use|3.15.0
console-ninja|Wal|1.0.266
quokka-vscode|Wal|1.0.597
vscode-import-cost|wix|3.3.0
vscode-jumpy|wma|0.3.1
pretty-ts-errors|yoa|0.5.2
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30859868
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by Yoyokrazy** [comment]
Checking back on this, has this been resolved in later releases of VS Code, or does your issue still persist?

**Comment by Yoyokrazy** [comment]
Going to close this as fixed, there have been a number of improvements to the multi-doc highlights and I belive this was fixed previously. If you are still facing this, feel free to reopen the issue with some details. Thanks!
