### ISSUE TITLE
Remote Tunnel: Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)

### ISSUE THREAD

**Issue by nassergharbi** [microsoft/vscode#199386]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.0-insider
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce: Cannot be systematically reproduced

Hello everyone,

For the past few days, I've encountered an error while attempting to connect to the VS Code server hosted on a remote Linux VM. This issue occurred a few weeks ago, and it was resolved the following day without any explanation.

Actions taken at that time:

- Reloaded VS Code
- Restarted Windows 11
- Uninstalled and reinstalled the service
- Recreated a new GitHub token

The current error message is: "Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)."

What I didn't do during the previous occurrence was take a closer look at the Output trace:

```
2023-11-28 17:35:07.988 [trace] [server] Installing and setting up Visual Studio Code Server...
2023-11-28 17:35:07.990 [error] [proxy] [connection.0] error setting up websocket: Error: WrappedError(WrappedError { message: "error creating server directory", original: "No space left on device (os error 28)" })
```

However, I want to emphasize that there is sufficient disk space, and the VS Code server has been installed and used daily for a few months now.

Could you please assist me in figuring out the root cause of this issue?

---

**Comment by connor4312** [comment]
"No space left on device" is an error from your operating system. By default, the CLI will install servers in the `~/.vscode-server` directory in your home folder. Please make sure there's sufficient space there and that the CLI has permissions to create more files in that location.
