### ISSUE TITLE
Keybinding in a hover should be in parentheses not brackets?

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#199359]
Follow up on #195994

Currently we wrap the kb in brackets: 

<img width="193" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/edccc5dd-2273-488b-9faa-a12990ab1712">

But we use parentheses in other places where the keybinding is shown, eg hover over problems or terminal pane label, or other icons.

<img width="199" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/20df1707-54bc-4a1c-bf40-b0b3698c1a3b">

**Comment by aiday-mar** [comment]
Hi @ulugbekna thank you for posting this issue. Indeed when I chose the square brackets I was not sure what type of brackets to use. In the editor toolbar menu for example, we appear to be using square brackets. I'll ask in the UX channel about this.

<img width="423" alt="Screenshot 2023-11-28 at 17 26 10" src="https://github.com/microsoft/vscode/assets/61460952/1fb5d4f1-8452-4f5e-a47c-a9b701470345">
