### ISSUE TITLE
Testing JS Heap Snapshots Viewer: On clicking of `Self Size` and `Retained Size` the chevron icon disappears then reappears repeatedly?

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#199321]
Testing #199239

When I was clicking on the `Self Size` text, I noticed that the chevron was appearing and disappearing repeatedly (while the column data itself did not change). I am not quite sure what the chevron is supposed to signify?

https://github.com/microsoft/vscode/assets/61460952/433d180a-7038-4756-8155-119c29340969

Related to this, I noticed that when you click on the text, you see a flicker as the text appears to be updating. In that case no update is needed since the data is already sorted, so perhaps we can avoid flickering.

**Comment by connor4312** [comment]
The default sorting is by self-size, so clicking on it is kind of a no-op (unless you're already sorting by something else). But I will fix the flicker.
