### ISSUE TITLE
Open editors view not reflecting new window

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#199411]
Testing #199023

Drag an editor tab into an empty space so a window opens.

Expectation: open editors in the main view shows a new window with that file open
Reality: It does not show the new window.

![Screenshot 2023-11-28 at 12 07 45 PM](https://github.com/microsoft/vscode/assets/29464607/804e1d4a-57ef-4d63-924b-7254e2abe940)

**Comment by bpasero** [comment]
This looks to me again like a window as empty workspace and not a floating window.
