### ISSUE TITLE
cannot drag and drop an editor

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#199403]
Testing #199023

https://github.com/microsoft/vscode/assets/29464607/e4634bfd-54b4-4753-8a71-f737172a5baa

**Comment by meganrogge** [comment]
Using the command `Open Active File in New Window` worked for that file though

**Comment by bpasero** [comment]
Does it help if you wait 1-2s at the location over the desktop before releasing? I have seen macOS sometimes refusing to accept the drop operation if I release the mouse very quickly after dragging.

**Comment by bpasero** [comment]
Unfortunately we are very limited in what we can do, given we rely on native drag and drop. Merging into https://github.com/microsoft/vscode/issues/198128

**Comment by bpasero** [comment]
!this.isNewWindowOperation(previousDragEvent ?? e)
