### ISSUE TITLE
Notify user to install yarn editor sdk when detected using yarn as npm package manager

### ISSUE THREAD

**Issue by FOWind** [microsoft/vscode#199481]
If using yarn as npm package manager, we should install yarn editor sdk to enable powerful features , I think vscode can notify user to install them like go extension.

https://yarnpkg.com/getting-started/editor-sdks

Below is Go notification: 
![image](https://github.com/microsoft/vscode/assets/13653453/53b3b72f-93b4-42f4-9e06-43f27d23bbe2)

**Comment by bhavyaus** [comment]
@isidorn I'm not sure if you're the correct owner for this but could you please help direct this extension recommendation issue? Thank you.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now to gather more feedback. Thanks
