### ISSUE TITLE
Quick Open should populate search field with selected text

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#19943]
When launching Quick Open, if there is text selected in the editor, populate the search field with the selected text.

**Comment by bpasero** [comment]
Not liking this idea, if I want to start searching for a file, I do not want the editor selection to start a search I do not want.

**Comment by dakaraphi** [comment]
@bpasero 
I am coming from using Brackets, and this is the default behavior of Brackets.  I've found it very useful.
Simply add this as another command id which I can bind a key mapping for this behavior

**Comment by bpasero** [comment]
@dakaraphi yeah, having a separate command for this makes more sense to me 👍

**Comment by dakaraphi** [comment]
@bpasero yes, I am thinking of just the file search quick open.
So the new command would populate with the current selected text or word under cursor.
Ideally, if there were only 1 match, then it would just open the file vs showing the quick open dialog.

**Comment by g8up** [comment]
I'm a javascript coder, and I need this featrue. 

In many situations, I need to search the related js file:
![image](https://user-images.githubusercontent.com/8005686/28425849-0d99eb9a-6da4-11e7-9d40-006519023786.png)
Under SublimeText3 I did a [plugin](http://git.oschina.net/g8up/sublimetext3-plugin/blob/master/go_to_file.py#L14) to fill selected text to the popup panel.

Does it have some config to achive this? may like this:
```javascript
    {
        "key": "ctrl+p",
        "command": "workbench.action.quickOpen",
        // "text": "${selection}"
        // args: "${selection}"
    }
```

**Comment by gkkirilov** [comment]
Coming from eclipse this is the only feature I miss.

**Comment by samir-majhi** [comment]
@dakaraphi This feature looks like it has already been done. When I select text and press Ctrl+Shift+F the selected text is populated in the search box.
Am I missing something?

**Comment by gkkirilov** [comment]
@samir-majhi This feature is asking to prepopulate the open file filed( CTRL + P ) not the search in files field(CTRL + [SHIFT] + F)

**Comment by bpasero** [comment]
I am closing this as extension candidate. You can get the selection from the active editor and you can pass a prefix to the `workbench.action.quickOpen` command.
