### ISSUE TITLE
"go to file" doesn't place cursor

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#199439]
Testing #199172

I am having trouble remembering if this was the previous behavior but I am struggling a bit with how it behaves now and thought I would submit a bug

1. use "go to file" in the scm view
2. your cursor is not located anywhere in the file
3. press enter
4. it seems like the cursor chose the spot next to the first change as its position, then when you click enter it shows the dual screen view.

I feel like it would be nice to have your cursor displayed somewhere in the file after the go to file button (I am not sure if this is a chosen decision based on the view type or not). Thanks

(my github is not letting me upload videos, I can DM it)

**Comment by lszomoru** [comment]
@eleanorjboyd, could you please DM me the recording? Thanks!

**Comment by eleanorjboyd** [comment]
able to upload it now:
https://github.com/microsoft/vscode/assets/26030610/9ed9e214-5995-47b3-aa35-c3ba7c577719

**Comment by lszomoru** [comment]
I am not aware of any recent changes related to the "Open File" action so I am adding @joaomoreno to provide any historical context on whether it was an explicit decision for the cursor not to be placed in the file after the file is opened.
