### ISSUE TITLE
should each window have access to the file system?

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#199408]
Testing #199023

I'm wondering if the window should open the folder that the file is in. A few things I encountered that made me wonder this:
- The explorer view saying there's no folder open, despite being in a folder and editing a file. I was curious about if this was a duplicate of the original file or if the changes would take effect.
- When doing `cmd+p` to search for a file and seeing no results found since there's just a single file.

**Comment by bpasero** [comment]
@meganrogge did you possibly not get a floating window in the end? Asking because there should not be any explorer in the floating window, see https://github.com/microsoft/vscode/issues/199023#issuecomment-1830493167

**Comment by meganrogge** [comment]
Yes, I was not clear on this.
