### ISSUE TITLE
Add option to customize "play" button

### ISSUE THREAD

**Issue by Bomer107** [microsoft/vscode#199463]
I am writing C++ programs in vs code, and something that frustrated me, is that even when I press the "Run C/C++ File" play button, it always builds the program and runs it through the debugger. 
first of all, if I didn't made any change to my C++ program, but just wants to run it again, there is no need to build again the exe file and it takes time.
also, why is the program runs through the debugger instead of running directly in the terminal?

Therefore, I would like you to add option of customizing the "play" buttom, and even customizing different modes of the button.
for example here are some modes:
1) run without build- play button that lets you run the exe file with a name according to your customization, without building the program.
2) run with build- play button that lets you build the program, and immediatly run it, and not through the debugger.
3) debug- which is working fine.

**Comment by roblourens** [comment]
Not sure which button is this, it might be contributed by an extension. If you're seeing the generic run button, you might be able to customize this in your launch.json. File an issue on the extension if there's something missing.
