### ISSUE TITLE
Can tab through notebook when it's in the background

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#199469]
- Open a notebook
- Switch to a text editor tab
- Enable "tab moves focus mode"
- Tab through the UI. After the status bar, the focus disappears. Check with devtools, see that focus is on notebook toolbars

**Comment by justschen** [comment]
@amunger not sure if this is the same issue, but the tabbing seems super random and does go into the notebook cell:

https://github.com/microsoft/vscode/assets/54879025/0bc49f4b-43d8-42a9-a38c-d8e8ac346188

**Comment by amunger** [comment]
It's separate, and I think that's the expected behavior: It's navigating among different toolbars, and once focused in a toolbar, you can use arrow keys to navigate. It jumps to that particular cell since that's where you were previously focused (I assume)

**Comment by meganrogge** [comment]
@amunger the focus still gets stuck in the notebook when I'm in tab moves focus mode.

**Comment by amunger** [comment]
@meganrogge - what do you mean it gets stuck? Do you have repro steps? That sounds different than what this issue was for.
