### ISSUE TITLE
Code cannot compile/run, even with main method

### ISSUE THREAD

**Issue by KWyle** [microsoft/vscode#199460]
Type: <b>Feature Request</b>

When I try to run the code, nothing happens, and when I scroll down to the main method, it does not even have a option to run like other versions of vscode.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by roblourens** [comment]
This sounds like an issue with the extension that you're trying to use to run the code, or with your code
