### ISSUE TITLE
Test coverage display when re-running single tests  

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#199426]
Testing #199242

The experience is looking great! I noticed a few things that I'm not sure if they're as designed or not:

- I expected to still be able to see the test2.md coverage when I re-ran the single test case on test.md, but it disappears.
- Once you re-run a single test case, it seems the denominator of the coverage does not change, so that causes the coverage to go down significantly, unless you re-run all tests again:

![TestCoverageDec23](https://github.com/microsoft/vscode/assets/45497113/02dff4cd-4b6b-4795-9085-af98b2b73d66)

![image](https://github.com/microsoft/vscode/assets/45497113/e368a29a-016c-4834-9262-55eeaeb9cd7e)

**Comment by connor4312** [comment]
This isn't something we can do much about as an editor. Users running coverage for a single test should be aware that the coverage report will only reflect that single test.
