### ISSUE TITLE
JQuery intellisense only works in HTML files?

### ISSUE THREAD

**Issue by DanJ210** [Microsoft/vscode#19944]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.15019
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-css-formatter|aeschli|0.0.2|
|vs-code-css-comments|ashhitch|1.0.2|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|githistory|donjayamanne|0.1.5|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.5.1|
|vscode-html-css|ecmel|0.0.33|
|javac-linter|faustinoaq|1.2.2|
|php-intellisense|felixfbecker|1.1.1|
|auto-close-tag|formulahendry|0.3.9|
|auto-rename-tag|formulahendry|0.0.11|
|code-runner|formulahendry|0.6.8|
|csharpextensions|jchannon|1.2.0|
|format-indent|Kasik96|1.3.0|
|format-php|Kasik96|1.1.2|
|ftp-sync|lukasz-wronski|0.3.2|
|cpptools|ms-vscode|0.10.0|
|csharp|ms-vscode|1.6.2|
|theme-railscasts|PaulOlteanu|2.0.0|
|material-icon-theme|PKief|1.2.0|
|vscode-icons|robertohuertasm|7.1.2|
|elise|schematrix|0.0.1|
|theme-tinaciousdesign|tinaciousdesign|0.1.1|

---

Steps to Reproduce:

1. Use jQuery for intellisense in an HTML document.
2. Use jQuery for intellisense in a JS document.

Hello. I'm trying to use JQuery in a separate JS file so that my html pages aren't too convoluted but looks like JQuery intellisense only works in HTML files and not in JS files. Am I wrong? Can I request that intellisense works in JS files as well as HTML files?

![HTML File Full Intellisense](https://cloud.githubusercontent.com/assets/16159685/22621542/19470d34-eaf4-11e6-84a9-28ae0a975da5.png)

![JS File No Intellisense](https://cloud.githubusercontent.com/assets/16159685/22621548/30cd9b44-eaf4-11e6-8267-89509b394a53.png)

**Comment by mjbvz** [comment]
I believe that in html files, we assume that `$` is jquery unless we can determine otherwise. We don't make the same assumption in JS files, which is why you don't see the correct intellisense.

To have VSCode know about Jquery in js files, either add an import `import $ from 'jquery';` to the file or install the typings for jquery `npm install --save-dev @types/jquery`

This should let VSCode know that `$` refers to jquery in JavaScript files

**Comment by DanJ210** [comment]
@mjbvz Both of those methods work, thank you so much!

**Comment by johns22** [comment]
@mjbvz `import $ from 'jquery'` did not work for me on either 1.9.0 or 1.9.1.  Do I need the jquery library in the same directory, or a jsconfig.json in there?  For example, if I create a new directory C:\Temp and put in Test.js and Test.html, the jquery intellisense works for the HTML but not for the JS file.

**Comment by DanJ210** [comment]
@johns22 @mjbvz What's weird is that `import $ from 'jquery'` did not work for me either, but installing the typings did. Only problem with that is what if I didn't want to install typings for whatever reason. I did some deeper searching and came across this...

`/// <reference path="jquery-3.1.1.js"/>`

Which I added with the three slashes to my .js file and jquery intellisense was then working. But after a couple days all of a sudden, jquery intellisense is no longer working within that same file after I've already been using it so I have no idea if that is what gave me intellisense or not. All I know is that it's not working now.

I can try installing typings on this new project but I was hoping not to have to, but I suppose it's not that big of a deal. Regardless, maybe there could be an easier and more official way to get intellisense for wwhatever you want in whatever file we want? Only one of the above suggestions worked and the one that did requires installing.

**Comment by johns22** [comment]
Thanks for the details @DanJ210 

@mjbvz Does this issue need to be reopened or should I open a new issue?  It seems like the jquery intellisense should work without having to install the typings as they clearly work when editing an HTML file.

**Comment by mjbvz** [comment]
@johns22 The html extension handles this differently, it basically tells TypeScript to always provide suggestions for jquery.

In a normal JS project, you should just be able to type `import $ from 'jquery'` and [automatic typing acquisition](https://code.visualstudio.com/Docs/languages/javascript#_automatic-type-acquisition) will download the typings for intellisense. This only happens for JS projects. If you are working with TypeScript — or even if you just have a `tsconfig.json` in your workspace — automatic typings acquisition is disabled. To be sure you are in a javascript project, try creating a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) at the root of your workspace

If you do not see this behavior, please open another bug and we can investigate.

**Comment by mabbashm110** [comment]
@mjbvz `import $ from 'jquery'` it worked for me on vscode but when I run the file it says `uncaught exception: unexpected token import`... and then i used `var $ = 'jquery'` and it says `Uncaught TypeError: $ is not a function`

**Comment by mjbvz** [comment]
These are errors with your code

The first means that your browser does not support `import` statements yet. This can be fixed using a packaer like webpack or a transpiler such as babel to transform the import statements into requires 

The second error means that `$` is assigned to something that is not actually jquery. If the example you shared is correct, then you assigned `$` to the string `'jquery'` which clearly won't work.
