### ISSUE TITLE
CMD+I has different behavior if Inline Chat is open in the file somewhere

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#199444]
Testing #199158

* in an editor, hit `cmd+i` -> inline chat opens DON'T CLOSE INLINE CHAT
* click somewhere else in the file
* hit `cmd+i`

For me, completions open. I was expecting:
* Inline chat to move down to my cursor
* A new Inline chat to start here

For a large file, I might forget that I started inline chat in an off screen portion of my file...

**Comment by aiday-mar** [comment]
Hi thanks for writing about this issue. As you mentioned, I think when the inline chat is already open we do not open it again. I guess we could change the context key here. Thoughts cc @jrieken ?
