### ISSUE TITLE
not able to restore settings editor to main window

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#199431]
Testing #199023

I had moved an editor group into a new window including a file and the settings UI. From that new window, I moved the file into a new window. I clicked on the window with the settings UI, tried to find the `Restore editors` command in the command palette, did not see it.

The `when` must be false here.

![Screenshot 2023-11-28 at 1 12 52 PM](https://github.com/microsoft/vscode/assets/29464607/8b947924-bc53-485c-b082-040e503ec65b)

**Comment by bpasero** [comment]
@meganrogge the `when` clause required here is that the active window is an aux window. Can you reproduce reliably and can provide exactly the steps?

**Comment by meganrogge** [comment]
I cannot reproduce today.
