### ISSUE TITLE
Unsure where Sync Changes button is

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#199409]
Testing #199177

I don't seem to have the sync changes button available to me, unless you're referring to the small icons in the status bars.

![Collapsed Incoming/Outgoing changes view](https://github.com/microsoft/vscode/assets/7199958/2e958bad-9f86-4eae-bdc7-a0afb8a1759f)

**Comment by rzhao271** [comment]
I was able to get the Sync Changes button with the node-spdlog repository on my mac.
It could be because my Windows machine and/or the vscode repository I tested with both have `"git.pullBeforeCheckout": true`

**Comment by lszomoru** [comment]
@rzhao271, that should not be the case. In your screenshot, I see that you have both incoming and outgoing changes, and no pending changes so the "Sync Changes" button should be shown instead of the disabled "Commit" button. Could you please share the exact steps that got you into this state? Also what is the value of the `git.showActionButton` setting?

**Comment by rzhao271** [comment]
The `git.showActionButton` has the default value.

Here are some steps:

1. In the microsoft/vscode repository, switch to a new branch off of the main branch
2. Remove a file
3. Commit and push to establish the remote version of the branch
4. On github.com, edit a separate file on that (remote) branch and commit the change directly to that branch.
5. Locally, edit yet another file and commit the change. Do not push.
6. Run the git fetch command.
7. :bug: There are both incoming and outgoing changes but the sync button does not appear.

**Comment by lszomoru** [comment]
Thanks for the steps. I will keep trying but for now I am unable to reproduce the issue:

![Image](https://github.com/microsoft/vscode/assets/3372902/04423c79-aa23-4161-9932-4124c694fea9)
