### ISSUE TITLE
No copy into new window action

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#199412]
Testing #199023

Unclear based on the description if there should also be a copy action, but for me, there is not.

![Screenshot 2023-11-28 at 12 08 52 PM](https://github.com/microsoft/vscode/assets/29464607/33417cf1-b96f-4b32-a889-1fef3cfacb4d)

**Comment by bpasero** [comment]
No, its intentionally not there because this menu is already very very long.

The entry is in the main menu:

<img width="550" alt="image" src="https://github.com/microsoft/vscode/assets/900690/6d044810-c220-467b-a5ef-f7b5b4e2a719">
