### ISSUE TITLE
AuthCodeExchangeError

### ISSUE THREAD

**Issue by Akhil-teja1** [microsoft/vscode#199487]
Type: <b>Feature Request</b>

Not able to connect with the salesforce org and unable to set up proxy settings.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by chrmarti** [comment]
Where is this AuthCodeExchangeError shown? What steps are you taking that end up not working?

**Comment by Akhil-teja1** [comment]
> Where is this AuthCodeExchangeError shown? What steps are you taking that end up not working?

When I try to connect the Salesforce Org to VS Code using private LAN then I'm not able to connect salesforce org to VS Code.

**Comment by chrmarti** [comment]
This sounds like a problem with your company's setup. When I search the web for AuthCodeExchangeError, some of the top hits are from Salesforce forums, please check these.
