### ISSUE TITLE
code space takes long time to load (or authenticate?).

### ISSUE THREAD

**Issue by kagurazburger** [microsoft/vscode#199490]
everything was working fine until I installed docker. However docker couldn't run and messed up my codespace as well. I also installed ubantu. not sure what's causing what issue. I'd be happy to provide more details, just let me know.

ADD ISSUE DESCRIPTION HERE

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Embedder: codespaces

**Comment by ulugbekna** [comment]
Please, report issues related to codespaces using "Codespaces: report issue" command in the command palette (press F1 to invoke command palette) 



![Image](https://github.com/microsoft/vscode/assets/16353531/b9d887f7-3265-4b1f-869f-f8526891612a)
