### ISSUE TITLE
I cant install extensions any way!

### ISSUE THREAD

**Issue by Alisabeghi1** [microsoft/vscode#199499]
Type: <b>Bug</b>

1.install Vs Code
2.Try to install extensions
3. give me error(Error while installing 'C# Dev Kit' extension. Please check the log for more details.)
4. try manually install and error again(end of central directory record signature not found)

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621

**Comment by gjsjohnmurray** [comment]
Have you tried installing a very simple extension, such as https://marketplace.visualstudio.com/items?itemName=georgejames.thefoldingstuff?

**Comment by sandy081** [comment]
It could be an issue with your network. I have seen users reporting same error and resolving it by fixing their network. Please check. Thanks.

**Comment by Alisabeghi1** [comment]
network is Correct !

**Comment by sandy081** [comment]
Can you please follow these steps and let us know if you still see the issue?

- F1 > Open User Data Folder
- Open `CachedExtensionVSIXs` folder
- Delete all files in the folder
- Restart VS Code and try again

**Comment by Alisabeghi1** [comment]
I was just deleted and try on Studio!

**Comment by Alisabeghi1** [comment]
i should first check installed packages on PC and installing which package i need. I solve my prblm.
TNX Git
