### ISSUE TITLE
Find in all files should allow search within results

### ISSUE THREAD

**Issue by dakaraphi** [microsoft/vscode#19940]
Find in all files should have the ability to do a search again within the files which were found from a previous search.

**Comment by schaveyt** [comment]
Agree. It seems that if the found in #22322 where implemented the it would enable this sort of experience.

**Comment by pipepupo** [comment]
I want this.

**Comment by vjeranc** [comment]
Yep, this would be very useful.

**Comment by gdbates1417** [comment]
I want this.

**Comment by anpel** [comment]
This would be really nice to have.

**Comment by oheydrew** [comment]
Agreed - Came here hoping this feature existed. It'd be handy. In the interim, does anyone have any workflow tips for searching large codebases with multiple search criteria?

**Comment by jialin-jiao** [comment]
+1 
really nice if VScode has this feature

**Comment by aglaberson** [comment]
I keep hoping this will be in the latest version, disappointed again 😭 (Though VSCode IS the best IDE ever)

**Comment by roblourens** [comment]
I think this will only be fixed by https://github.com/microsoft/vscode/issues/23931
