### ISSUE TITLE
dragging and dropping across monitors does not work

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#199405]
Testing #199023

I drag a tab from one window to another monitor and it creates the window (only sometimes, see other issues) in the current monitor's window.

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/assets/29464607/688ebc33-65a6-4aa7-97d0-6787d42ec653

**Comment by bpasero** [comment]
Similar as for the other drag issue, when you wait a bit before releasing the mouse, does it make it any better?

**Comment by meganrogge** [comment]
Yes if I wait a few seconds, it works.

**Comment by bpasero** [comment]
Merging into https://github.com/microsoft/vscode/issues/198128

**Comment by bpasero** [comment]
Same underlying reason as https://github.com/microsoft/vscode/issues/199403#issuecomment-1831268398
