### ISSUE TITLE
Terminal command navigation on a secondary window is redirected to the main window

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#199465]
Testing #199023

![Recording 2023-11-28 at 15 29 44](https://github.com/microsoft/vscode/assets/2193314/3e19b540-4f02-41d9-a929-cecdd5a9c637)

**Comment by meganrogge** [comment]
same root cause as #199432

**Comment by momvart** [comment]
Experienced a similar issue when pasting commands into terminal. It was getting pasted into the one in the main window not in the floating one.

**Comment by patrickbritz** [comment]
> Experienced a similar issue when pasting commands into terminal. It was getting pasted into the one in the main window not in the floating one.

Getting the same problem.

**Comment by Tyriar** [comment]
Seems to be working now
