### ISSUE TITLE
It needs to be clearer what will be auto-run

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#199452]
Testing #199158

For this line, presumably there is only one AI action available.

![Image](https://github.com/microsoft/vscode/assets/2644648/851c0449-6170-459b-8a84-2a03c378a7d4)

But I have no idea what that action is... and what will be executed when I open inline chat.

It opens with `/doc`:

![Image](https://github.com/microsoft/vscode/assets/2644648/60371f45-ebcd-4510-a75e-245235f16f20)

I think this should be more clear that this will happen as it's a bit jarring.

Also https://github.com/microsoft/vscode/issues/199425 will help here I think

**Comment by aiday-mar** [comment]
Yes that's a very good point, if an action is auto-ran I will put the action title in the hover message.

**Comment by aeschli** [comment]
@aiday-mar Is there a way to override the autorun from the code action?

**Comment by aiday-mar** [comment]
I am working on changing the arguments if the command ID is `inlineChat.start`. I will create a new args object but set autoSend to false

**Comment by aiday-mar** [comment]
So I have one PR to show the action title in the sparkle hover: https://github.com/microsoft/vscode/pull/199521
And one PR which disables autoSend when invoking inlineChat.start : https://github.com/microsoft/vscode/pull/199680
