### ISSUE TITLE
Go to definition should also find functions across plain JS project

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#19942]
Currently 'go to definition' seems to only work for some symbols within the same file.  I work on a very large project with custom built module system.  Navigating the code base currently best works with Brackets and WebStorm.
Both Brackets and WebStorm can find the function definition of any function for any type of JS project.
If there are multiple possible definitions for a function, they will present a list from which you can choose.

**Comment by medanny** [comment]
I also believe this would be very helpful.

**Comment by mjbvz** [comment]
@dakaraphi Can you share some additional information about your project structure. Do you have a `jsconfig.json` file? What types of modules are you using?

Thanks

**Comment by dakaraphi** [comment]
@mjbvz 
I do have a jsconfig.json.

I think what I'm actually asking for is to support finding function definitions when there are no official modules.  It is a fuzzier type of resolution where we don't know how the project is assembled.

For example, in Brackets or WebStorm, you can just create 2 plain javascript files.  Without any module declarations or imports.  If there is an object on which you call a function, if that function name exists in the other file, it can find it.

My project is a Dojo based project, but the module system is custom built.  Doesn't conform to Dojo's.  Brackets and WebStorm work because they don't try to understand the module system.  They just find all potential matches for a function throughout the entire project.

**Comment by mjbvz** [comment]
@dakaraphi Can you please share a minimial project that shows this behavior and we'll see if this is something that the TypeScript team can improve

**Comment by dakaraphi** [comment]
Here is an example as 2 plain JS files.

ModuleA.js
```javascript
function canYouFindMe() {
    function whereAmI() {
        
    }
}
var someObject = {
    someFunction: function() {},
    whereAmI: function() {}
}
```

ModuleB.js
```javascript
module.canYouFindMe();
module.whereAmI();
module.someFunction();
```

I want to be able to click on any of those 3 functions, and it take me to the source in file ModuleA.  This is useful for projects not using any conventional module system and where functions are dynamically assigned.  Using those 2 files, If I open ModuleB in Brackets, I can press cmd+E to find/edit the source.  If I click on 'whereAmI' it will show me there are 2 definitions of that function and I can choose which one to navigate.

**Comment by bfranklyn** [comment]
Wow I have had this problem since 1.0 when I started using vs code but could never word it as well as @dakaraphi. Go to definition only works like 20-30%  of the time for me and i have been complaining about this for ages. Johannes Rieken made a plugin called 'fuzzy definitions' it helps but still not as solid as go to definition in something like sublime text which is what I moved from.

**Comment by gillibrand** [comment]
I'm hitting the same problem. Works in Sublime Text.
