### ISSUE TITLE
Setting to None clears all of my previous choices

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#199413]
Testing #199180

1. Hit Auto Update & Auto Update All on a few extensions
2. Now set the setting to `None` (expectedly, the choices before are unchecked)
3. Now switch the setting back to `SelectedExtensions`
4. 🐛 my previous choices are all gone

Imagine I have set auto update on a bunch of extensions & publishers that my company trusts... but because I'm trying to troubleshoot something, or I'm working under crunch time and don't want anything about my environment to change for a bit, I switch to `None`.

Now at this point, I've lost all of my previous preferences and I have to redo everything again. This is a bit frustrating. I would expect that either:
* my previous preferences would be re-applied or,
* when setting to None, a modal pops up saying all my selected choices will get clobbered

**Comment by sandy081** [comment]
Thanks for the feedback.

> when setting to None, a modal pops up saying all my selected choices will get clobbered

I would prefer this option. I will wait for more feedback and see what users are expecting in general,

**Comment by isidorn** [comment]
Got hit by exactly this issue. From those two options, I think this one makes a strictly better user experience:
> previous preferences would be re-applied
