### ISSUE TITLE
Empty workspace: restore untitled dirty files in the order they were after restart

### ISSUE THREAD

**Issue by cosmofrit** [Microsoft/vscode#19948]
- VSCode Version: 1.9.0
- OS Version: Windows 7

Steps to Reproduce:

1. Create new files, but don't save them
2. Close VSC
<img width="948" alt="hotexittaborderaftervscodereopened" src="https://cloud.githubusercontent.com/assets/23569695/22622951/eed4439e-eb95-11e6-9ad4-5b4142738dcf.PNG">

3. Open VSC. Files saved by Hot Exit are not in the same Tab order as they were when created

**Comment by bpasero** [comment]
@cosmofrit having a hard time to reproduce this, here is a video of how it looks like for me:

![kapture 2017-02-06 at 7 12 05](https://cloud.githubusercontent.com/assets/900690/22636458/95184656-ec3b-11e6-8006-c3603172b2b1.gif)

**Comment by bpasero** [comment]
Oh I see it now, it only happens in an empty workspace without folder opened.

**Comment by bpasero** [comment]
This really is: https://github.com/Microsoft/vscode/issues/207

**Comment by cosmofrit** [comment]
The description of #207 doesn't really sound like this files in tabs ordering bug. See Notepad++ for an example of an editor that displays unsaved files in tabs in the same order as you left them when you closed down the program. That's how I think VS Code should work too.

**Comment by bpasero** [comment]
@cosmofrit you can trust me about the duplicate, but thanks for asking 👍
