### ISSUE TITLE
Is it possible to debug the VSCode execution?

### ISSUE THREAD

**Issue by scarletquasar** [microsoft/vscode#199489]
Maybe using some kind of electron chromium-based developer console or some kind of external debugger attached to it? What is the best way to discover the calls behind a common function execution inside the editor? 

For example: I never touched this codebase; I want to know if there is some way to find the function calls behind the file explorer because I want to work on some corrections/optimizations about file moving in specific situations. I can obviously dive into the codebase, just asking for practicity.

**Comment by gjsjohnmurray** [comment]
Have you reviewed https://github.com/microsoft/vscode/wiki/How-to-Contribute and other pages in the Contributing section of the wiki?
