### ISSUE TITLE
namespace Autocompletion/Intellisense

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#1994]
In C# when typing in a namespace, there is no completion hinting of namespaces that are being used.

    namespace My.Name.Space{}

When I create a new class, vscode can auto complete the `using` part, but It doesn't autocomplete the the `namespace` part.

So, when typing `namespace My.` it should suggest `Name` and anything else within the `My` space.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#377
