### ISSUE TITLE
Terminal selection doesn't stay focused to use hotkeys

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#199586]
Steps to Reproduce:

1. Create multiple terminals
2. Select one and press delete (or F2 to rename)
🐛 terminal is not removed

if I hold down the click, it can keep focus to be deleted correctly as shown in the gif

![Recording 2023-11-29 at 10 49 16](https://github.com/microsoft/vscode/assets/2019016/e4122602-fea3-4833-aa23-5a35c2655462)

**Comment by meganrogge** [comment]
What is the exact key sequence you're using when this does not work?

**Comment by amunger** [comment]
the screencast should show: click a terminal then press delete. 

It only successfully deletes if I hold the mouse click, just a plain click will put it in that grey highlight as if it's selected but not focused.

**Comment by meganrogge** [comment]
that is what is happening for me - I click and press delete. are you left, middle, or right clicking? anything interesting happen for you in the explorer as that's similarly just a list?

https://github.com/microsoft/vscode/assets/29464607/b525ae60-f9a4-4c47-8e04-cc63af01da7e

**Comment by amunger** [comment]
oh, this is expected. I have `"terminal.integrated.tabs.focusMode": "singleClick"` on, so it's giving focus to the terminal as designed.
