### ISSUE TITLE
`CTX_INLINE_CHAT_TOOLBAR_ICON_ENABLED` isn't needed

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#199525]
We have `CTX_INLINE_CHAT_TOOLBAR_ICON_ENABLED` as explicit context key which is driven with the [config service](https://github.com/microsoft/vscode/blob/8cd71f96f9f8139270e1ba5653a7ea939ec34559/src/vs/workbench/contrib/inlineChat/browser/inlineChatDecorations.ts#L113-L115). This is all fine but actually not needed. Any configuration is automatically a context key when prefixed with `config.` - [this as a sample](https://github.com/microsoft/vscode/blob/f54f1b0400df0de4282c217984373a00fa368479/src/vs/workbench/contrib/inlineChat/common/inlineChat.ts#L157), the setting is `inlineChat.mode` and you can use `config.inlineChat.mode` as context key

**Comment by aiday-mar** [comment]
That's useful, thank you I didn't know
