### ISSUE TITLE
Update file icons

### ISSUE THREAD

**Issue by mlntr** [microsoft/vscode#199531]
Can the default file icon theme be updated in VS Code (seems just need to follow the [instruction](https://github.com/microsoft/vscode/tree/main/extensions/theme-seti#updating-icons) to run the [update-icon-theme.js](https://github.com/microsoft/vscode/blob/main/extensions/theme-seti/build/update-icon-theme.js) script)

Pom.xml files should by now have the Maven (mvnw) icon but are still showing regular XML icon.

**Comment by aeschli** [comment]
Verify that the Pom.xml files now have the Maven (mvnw) icon
