### ISSUE TITLE
Wording: "Hide" and "Hidden"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#199550]
Suggest to be consistent:

![image](https://github.com/microsoft/vscode/assets/900690/50d0a08c-c6d7-43b9-bff7-d81fbbd749e7)

![image](https://github.com/microsoft/vscode/assets/900690/a12bc3eb-87ce-4d89-a82f-4450aedc6c3d)

**Comment by gjsjohnmurray** [comment]
I vote for Hidden
