### ISSUE TITLE
vscode not able to pick up node version from nvm

### ISSUE THREAD

**Issue by shrimpywu** [Microsoft/vscode#19951]
- VSCode Version: Code - Insiders 1.10.0-insider (723b20093d2f525e84cdf94a52f7695d1d539273, 2017-02-03T08:24:58.073Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. debug node version is 0.10.48, perform `nvm use 4.6`
2. `code-insider .` to open vscode for a project

expect: vscode should use node v4.6
actual: it is using v0.10.48

**Comment by weinand** [comment]
nvm uses a shell function (instead of an environment variable) to configure the path to the node.js.
This is not supported in VS Code on macOS.

The workaround is to use the `runtimeVersion` attribute:
```
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${workspaceFolder}/test.js",
			"runtimeVersion": "4.6"
		}
```
