### ISSUE TITLE
Frozen/slow input when switching between windows after inactivity

### ISSUE THREAD

**Issue by itacud95** [microsoft/vscode#199535]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
code --version
1.84.2
1fc52b725b3f76b97eadfd988cea42a739ae923f
x64
```
- OS Version: 
```
EndeavourOS Linux x86_64 
WM: Sway (Wayland)
```

Steps to Reproduce:

1. Open 2 separate vscode windows using command: `code --disable-extensions .`
2. Focus one window and wait for at least 15 seconds.
3. Change focus to the other vscode window and immediately start moving around in the editor using arrow keys.
4. Notice how the input is freezed for around 1 second. 

Other findings: 
- This happens only when vscode is focused. Focusing on firefox or a terminal does not give the same result. 
- The issue seems to happen between 10-15 seconds of inactivity. 
- Using 15 seconds as a timer to switch between vscode windows triggers the issue almost every time. I have tried longer delays with same result. 10 seconds is not as reproducible as it only happens sometimes. 
- I have a suspicion that it could be Wayland related, but I am not sure. 
- I am seeing this on both VSCodium and the 'main' VSCode

Please let me know how I can help debug this.

**Comment by deepak1556** [comment]
Just to confirm are you running with wayland backend in the application, (i-e) `--ozone-platform-hint=auto` or `--ozone-platform=wayland` ?

Can you also check if the issue repros with our [exploration build](https://az764295.vo.msecnd.net/exploration/42053f37e98a2dbaa0d108807491e716105dccd2/code-exploration-x64-1701157790.tar.gz) based on a newer version of the runtime.

**Comment by itacud95** [comment]
Thanks for the reply. 

I thought I had these flags enabled, but it turns out I did not. I think I disabled them since I had code crash on open with them. 

The crash seems to be related to
```
    "window.titleBarStyle": "custom",  <= this works
    "window.titleBarStyle": "native",  <= this crashes
```

I cannot reproduce my problem while running code with flags 
```
--enable-features=WaylandWindowDecorations
--ozone-platform-hint=auto
```

Would be nice not to have that titlebar there, but I guess that is another issue.

**Comment by deepak1556** [comment]
Thanks for confirming, the crashes are tracked in https://github.com/microsoft/vscode/issues/184124. Given the issue does not happen with wayland backend in the application I am inclined to close this issue. Thoughts ?

**Comment by itacud95** [comment]
Yes, I agree.
