### ISSUE TITLE
Add keybinding for generate commit message with copilot extension

### ISSUE THREAD

**Issue by david-macleod** [microsoft/vscode#199522]
Currently we have the ability to add a keybinding for GitLens' generate commit message

![image](https://github.com/microsoft/vscode/assets/17232877/9f56dd60-445b-46dd-9712-d2005e4d3619)

It would be really great if was also could map a keybinding to the github copilot "generate commit message" so avoid having to click the "sparkle" icon each time

![image](https://github.com/microsoft/vscode/assets/17232877/ac70367e-d98e-4c97-be80-e7c60372a904)

**Comment by Lawrencium77** [comment]
`git.generateCommitMessage` in Keyboard Shortcuts is what you want

**Comment by david-macleod** [comment]
My hero
