### ISSUE TITLE
Modify/disable built-in snippet

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#19952]
vscode: 1.9.0

From discussion: https://github.com/Microsoft/vscode/issues/18963

The copy and override way is not optimal as it creates two identical entries in the list:
![image](https://cloud.githubusercontent.com/assets/3254987/22623233/ac729890-eb07-11e6-89bf-6466f0db9e22.png)

It would be better if we can edit or remove the built-in snippet directly.

**Comment by jrieken** [comment]
We have similar discussions about other non-code extension contributions, like keybindings

**Comment by unional** [comment]
@jrieken would you consider re-open https://github.com/Microsoft/vscode/issues/18963 also?
The `editor.snippetSuggestions: 'top'` solution is not good enough.

**Comment by jrieken** [comment]
dupe of #10565
