### ISSUE TITLE
It's not possible to set `editor.semanticTokenColorCustomizations` scoped by a language

### ISSUE THREAD

**Issue by deser** [microsoft/vscode#199569]
Type: <b>Bug</b>

1. Go to workspace settings json file.
2. Start typing the next:
{
    "[typescript]": {
        "editor.semantic"
    }
}
3. You will see that autosuggestion do not show `editor.semanticTokenColorCustomizations` option. Also, confirmed that if I insert it manually, it doesn't work. 
<img width="684" alt="image" src="https://github.com/microsoft/vscode/assets/3010698/5b2c8310-3641-499c-ba89-6875b872fb5b">

VS Code version: Code 1.84.2 (Universal) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin arm64 22.6.0
Modes:

```[tasklist]
### Tasks
```

**Comment by aeschli** [comment]
You are right `editor.semanticTokenColorCustomizations` is not a language specific setting, same as all other theming settings.
But, you can do this:
```
  "editor.semanticTokenColorCustomizations": {
    "rules": {
      "parameter:typescript": {
        "foreground": "#ff0000"
      }
    }
  }
```

**Comment by deser** [comment]
Thanks, hopefully this is documented somewhere :)

**Comment by aeschli** [comment]
https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-coloring-in-color-themes

**Comment by aeschli** [comment]
@deser This works for all languages and also for custom token names. But does your language have a semantic token provider?
