### ISSUE TITLE
Snippets stopped working

### ISSUE THREAD

**Issue by ripvannwinkler** [Microsoft/vscode#19954]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-beautifier|michelemelluso|1.6.2|
|vscode-scss|mrmlnc|0.6.0|
|vscode-sql-beautify|sensourceinc|0.0.4|
|lorem-ipsum|Tyriar|1.0.0|

---

Steps to Reproduce:

1. Use VS Code <1.9.
2. Add a snippet. See example of my snippet below.
3. Upgrade to 1.9
4. Insert snippet command reports "There are no entries to pick from"
5. Intellisense does not list known snippets.

My snippet (installed in both JavaScript and JavaScript React):

    {
        "JSX Comment":{ 
            "prefix":"jc",
            "body":[
                "{/* $1 */}$0"
            ],
        "description": "Inserts a React-style comment"
    }
}

Note: I tried re-adding a snippet after the upgrade, and newly added snippets do not appear either. It seems as though VS Code fails to load snippets for the current file type.

**Comment by chris-schmitz** [comment]
VSCode version: Version 1.9.0 (1.9.0)
OS Version: 10.12.2 (16C67)

I'm running into this issue too with snippets for the `.vue` language when using the [vuter](https://github.com/octref/vetur) extension. 

A couple of additional things to note:

- These snippets were working fine before my last upgrade
- I created a new profile on my computer, only installed the vuter extension, and still ran into the same issue
- I made sure in both instances I had my file.associations setting set to: 

```
    "files.associations": {
        "*.vue": "vue"
    }
```
- And lastly but maybe most telling, some snippets actually _are_ expanding, but they are snippets from my `html.json` file. 

I'm thinking that maybe something is going wrong with the file.association linking.

**Comment by jrieken** [comment]
@ripvannwinkler @chris-schmitz Can you guys add more information such that I can reproduce this? I have taken 1.8.1, added the above snippet, updated to 1.9.0 and I still see it in the 'Insert Snippet'-list.

* what file are you in when you run the command?
* what the does the lower left corner (lang indicator) show?
* do you have some file-accociations configured?

**Comment by ripvannwinkler** [comment]
@jrieken All of our work is done in .js files which Code correctly identifies as JavaScript in the status bar.

Interestingly enough after reading yours and @chris-schmitz comments, I went to an old file this morning to test a few things and found the following:

- This is not limited to a specific file, but all of my .js files. 

Even something as simple as the content below exhibits the problem (footer.js)

    import React from "react";

    export default (props) => {
        return (
            <footer className="bg-teal text-white font-11">
                <p>
                </p>
            </footer>
        );
    }

- The snippet pops up fine anywhere except a JSX block. [Screenshot](https://i.imgur.com/GRB7EcL.png) [again](https://i.imgur.com/A2eVT7q.png) and [another](https://i.imgur.com/56AAe5s.png)
- I tried saving the file as .jsx instead of .js, and the symptoms persist.

**Comment by chris-schmitz** [comment]
Hey @jrieken, 

> what file are you in when you run the command?

I'm creating a `test.vue` file which is the file extension that I'm trying to use snippets for.

> what the does the lower left corner (lang indicator) show?

This is interesting, when I'm in my test profile using vscode with no extensions other than the vuter extension that gives vue.js language support, the language type vscode uses is HTML. 

Sadly, even after I manually changed the language type to vue vscode still expanded snippets from the HTML snippet file.

> do you have some file-accociations configured?

Yep, I have the following association set:

```
    "files.associations": {
        "*.vue": "vue"
    }
```

I also did a screen capture of the issue in action. Hopefully this will help [file associations not working as expected](https://dl.dropboxusercontent.com/u/1953984/File%20association%20for%20vue%20not%20working%20as%20expected.mov).

**Comment by jrieken** [comment]
@ripvannwinkler Thanks, so I can reproduce this:

* have a JSX file and a JavaScript react snippet as shown beloen
* open the JSX file,
* invoke "Insert Snippet" on line 4 -> see `jc` snippet
* invoke "Insert Snippet" on line 6
* 🐛 no snippets



test.jsx
```jsx
import React from "react";

export default (props) => {
    return (
        <footer className="bg-teal text-white font-11">
            <p>
            </p>
        </footer>
    );
}
```

javascriptreact.json
```json
{
	"JSX Comment": {
		"prefix": "jc",
		"body": [
			"{/* $1 */}$0"
		],
		"description": "Inserts a React-style comment"
	}
}

```

**Comment by jrieken** [comment]
@chris-schmitz I still have to drill into your steps to see if that's the same or something different but wrt the scenario @ripvannwinkler describes this is what happens: For the editor there are actually two different languages in that file: `javascriptreact` and `jsx-tags`. The latter is line 5-8 and therefore the javascript-react snippet don't match anymore. 

Picking the mode at the current cursor location was changed already 2 months ago (https://github.com/Microsoft/vscode/commit/bed2db5438d1848c4df3243ad09808a71ad31605) to fix a different issue, like html snippets in embedded JavaScript. 

First, we should understand what changed to have caused this? @aeschli Did the jsx-grammar change? @alexandrudima Can the more correct handling of TM tokens now result in a different language at a position?

Second, we should figure out what the desired behaviour is assuming the new behaviour is correct. There is definitely a use-case for picking snippets for the language the cursor is currently in (like JS/CSS in html) but this is a case speaking against it.

**Comment by alexandrudima** [comment]
@jrieken Yes, a grammar contribution can configure the embedded languages:

https://github.com/Microsoft/vscode/blob/master/extensions/javascript/package.json#L66

I think the change is that we have now more correctly expressed that JSX contains multiple languages. The Inspect TM Scopes widget will show what language the grammar detects at a position (based on this `embeddedLanguages`).

**Comment by jrieken** [comment]
I see. So, I believe the editor reflects the world correct and that we should change the selection logic a little. Today, we call `getLanguageIdAtPosition` and check with that for available snippets. My proposal would be to validate first if that language id is for a "user facing language", like one with a name and one for which you can actually define snippets. If the language id at the position isn't such a "user facing language" I would fall back to the containing language. @alexandrudima Does that sound reasonable to you?

**Comment by alexandrudima** [comment]
Yes, that sounds like a good heuristic. At this time, there's no other way to distinguish the case of "javascript inside html" to this case of "jsx-tags inside javascriptreact" than jsx-tags not having a language name.

**Comment by aeschli** [comment]
The jsx-tags were introduced in the January build (d826ad6e4fd52d9997fd144531c952af13218146) that's why thing behave differently now.
Note that we did that to have the 'comment' command use the react comments. So maybe you don't need snippets for that anymore.

jsx-tags is a bit special as we hide it from our language selection. But maybe we should show it in the user snippet configuration dialog and allow users to create snippets specifically for that region.
I'd think the more specific, the better. One can always add the same snippet also into the JavaScript scope if wanted.

**Comment by ripvannwinkler** [comment]
@aeschli I just checked and as you noted, the default comment command is now JSX-aware. That's awesome! The comment snippet I originally used is no longer necessary. It may still be desirable to use other snippets in the same context.

**Comment by alexandrudima** [comment]
verified via code review

**Comment by dedmazayukr** [comment]
vscode chooses unusual option for autocomplete
http://stackoverflow.com/q/42022456/6011421

**Comment by chris-schmitz** [comment]
Was the fix for this in the v 1.9.1 release that came out this morning? If so I'm still not able to expand my .vue specific snippets. Is there something else I need to do to make it work?

**Comment by dedmazayukr** [comment]
Thanks for the quick response, but in version 1.9.1 is the same problem.
The decision was prompted on StackOverflow http://stackoverflow.com/a/42107910/6011421

> You can add this "editor.snippetSuggestions": "top" to your configuration to ensure snippets are always sorted on top

**Comment by jrieken** [comment]
This issue was about the steps described [in the above comment](https://github.com/Microsoft/vscode/issues/19954#issuecomment-277705088) and about us using the wrong language when trying to insert snippet. @dedmazayukr You seem to talk about something else. @chris-schmitz I was never able to reproduce was you describe. Please file [separate issues](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests) for separate problems.

**Comment by dedmazayukr** [comment]
Ok, excuse me. @jrieken Good luck.

**Comment by chris-schmitz** [comment]
Gotcha. Will do.
