### ISSUE TITLE
light+ theme's "entity.other.attribute-name" should not use red as foreground

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#199564]
Props in TSX components use red color, which signals of a mistake and in general too bright color for something that's used often. I propose using same color as for function params

Now: 

<img width="586" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/1712a464-861d-4fbe-be72-c31eb1cc1cab">

Proposed:

<img width="521" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/6c230fb4-04cc-4c12-b0c6-39358e004231">

I can send a PR if we agree.

Another solution would be to assign another scope (other than "entity.other.attribute-name" -- maybe same scope as a function parameter), which would be even better?

**Comment by hbons** [comment]
Agree the red looks wrong. Do you know where this theme originally came from? It looks like the VS Win theme. Just want to make sure we don't diverge needlessly or if we fix it we do so in both places.

**Comment by ulugbekna** [comment]
`light_plus.json` inherits this color from `light_vs.json`

i don't know how safe it is to change a color in such popular themes but we can't be the only ones who think red is bad for this use case

**Comment by aeschli** [comment]
That's the color we use for attribute names in html and xml, and this originally came from how Visual Studio colors HTML.
Of course there's no rule that we need to use matching colors in JSX and HTML. Already for property values, such as strings we are different in JSX.
![image](https://github.com/microsoft/vscode/assets/6461412/3bc74a8c-67c1-4443-af39-2e7f9e32ede8)

I wouldn't rush into color changes for the default themes. From experience there will be some users that won't like the change.
We have plenty of themes to choose from and capabilities to customize themes.
