### ISSUE TITLE
Problems view: lightbulb loses color on focus

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#199565]
1. Have some errors in your typescript file
2. Click on the problems view. Notice the lightbulb. But it losses colour when the focus is on the item. Making it look bad 🐛 

![Screenshot 2023-11-29 at 17 28 50](https://github.com/microsoft/vscode/assets/1926584/a561c8e7-2cc9-430e-a531-716da63735c9)

**Comment by sandy081** [comment]
Icons take the colors from the list so that they are visible otherwise they might look weird with list colors.
