### ISSUE TITLE
Testing peek view not respecting theme settings 

### ISSUE THREAD

**Issue by Uberroot** [microsoft/vscode#199533]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.2
- OS Version: Win 10

Steps to Reproduce:

1. set peekViewResult.background to a noticeable color
2. Write a failing test and run (pytest used in my case)
3. Open peek view for the test- the editor background color is used

From src/vs/workbench/contrib/testing/browser/media/testing.css it looks like this was meant to be in place but it does not currently work.

**Comment by connor4312** [comment]
`peekViewResult.background` affects the background color of the tree view in the peek, and that works for me:

<img width="810" alt="image" src="https://github.com/microsoft/vscode/assets/2230985/be5dd30e-778d-475d-ada6-03881588c19a">

**Comment by Uberroot** [comment]
Ah I misunderstood what that was controlling. For reference here is what I was seeing:

![tmp_043bbda0-8e38-4917-97dc-110ffcf3c356](https://github.com/microsoft/vscode/assets/5520842/192b29c5-2048-4868-ba39-2e521a77f7b3)

In that case it looks like the actual issue is that peekViewEditor.background isn't being used where I would have expected given other peek styling (maybe `.test-output-peek-message-container .monaco-editor` and `.test-output-peek-message-container .margin`?)
