### ISSUE TITLE
Terminal showCommandGuide is quite slow for really large outputs

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#199593]
Repro:

Run `ls -Recurse` in a large repo with a high `terminal.integrated.scrollback` set, hover and leave the terminal. This example was with ~38k lines of output:

![image](https://github.com/microsoft/vscode/assets/2193314/64628e2c-d18c-45cb-b577-9b864c4f1a83)

**Comment by FlightControl-User** [comment]
I have the same issue, it is slowing down the compilation heavily and it sticks. I mean, a large scrollback buffer really slows down the whole system and the vscode editor itself.
