### ISSUE TITLE
Smoke: only signal `restored` phase when contributions have executed

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#199577]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=246870
Changes: https://github.com/Microsoft/vscode/compare/bc90807...9fc2a7a

**Comment by sandy081** [comment]
Checked the playwright trace and logs and it seems workbench is in the restored lifecycle phase and the `Focus on Extensions View` command is not available in the workbench.
