### ISSUE TITLE
Change all Occurrences also changes values within the comments

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#1995]
In C# when I do "Change all Occurrences" it also changes occurrences within comments. The issue here is, is that not all comments contain code but contain text that has spellings that are the same as a variable/property that is getting changed.

**Comment by isidorn** [comment]
I think this is as designed, since changing all occurrences changes **all** occurrences. Try using **rename** instead. 
Giving to @jrieken to comment more or close

**Comment by jrieken** [comment]
Yes - that the point of the feature.

**Comment by TheColorRed** [comment]
Well then is there a way to change all occurrences within the scope only?

**Comment by jrieken** [comment]
You should see rename being enabled for C# files

**Comment by TheColorRed** [comment]
Okay. I tried that on my Linux machine last night and was getting an error. Seems to work on my Windows machine though.
