### ISSUE TITLE
Disable underline below Activity Bar icons when workbench.activityBar.location is set to top

### ISSUE THREAD

**Issue by uncenter** [microsoft/vscode#199573]
I think the underline beneath the icon of the active tab doesn't look great.

![Screenshot 2023-11-29 at 11 47 58 (Code)](https://github.com/microsoft/vscode/assets/47499684/362e837e-f35b-4aae-8963-7909937107b0)

The ideal solution would be to change the icon color to the accent like it does when `workbench.activityBar.location` is "side":

![Screenshot 2023-11-29 at 11 53 31 (Code)](https://github.com/microsoft/vscode/assets/47499684/60857676-fa83-48d1-b450-2474d0c2c77e)

**Comment by T-256** [comment]
> The ideal solution would be to change the icon color to the accent

It does
![image](https://github.com/microsoft/vscode/assets/132141463/5b570e62-a427-4d6c-ba61-ef9f4c077255)

Theme: Dark modern

**Comment by uncenter** [comment]
It doesn't... I have the same screenshot. The whole icon should be that blue color, or purple with my theme above.
