### ISSUE TITLE
error con el uso de directorios virtuales... o en la red ...

### ISSUE THREAD

**Issue by patmic** [Microsoft/vscode#19953]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|debugger-for-chrome|msjsdiag|2.5.2|

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
English please 👍
