### ISSUE TITLE
When In Zen Mode the title bar doesn't get hidden due to the New "Top" mode for Activity Bar

### ISSUE THREAD

**Issue by RadhiRasho** [microsoft/vscode#199579]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: Windows 10 22H2 (Build 19045.3693)

Steps to Reproduce:

1. Open New Window of VS Code
2. Set the Activity Bar Position to "Top"
3. Enter Zen Mode (Command Pallete -> View: Toggle Zen Mode)
4. Title Bar should still be there

This was tested on the latest version of VS Code Insider and Results were the same and with all Extensions Off

Expected Behavior: 
Title Bar should be hidden (at least when in Zen Mode)

Possible Fix/Alternatives:
1. Hide it in Zen Mode
2. Add an option into the Zen Mode Settings to turn Title bar off unless the user has clicked Alt (which shows the title bar)

In Zen Mode: 
![image](https://github.com/microsoft/vscode/assets/54078496/7a1096c6-3ce2-480c-9b19-aea3e0fbeac3)

Out Of Zen Mode: 
![image](https://github.com/microsoft/vscode/assets/54078496/d614f829-1bc2-4d07-9375-5a9e565ffa65)

**Comment by bpasero** [comment]
@RadhiRasho can you try configuring `window.customTitleBarVisibility` to `window.customTitleBarVisibility`. When in Zen mode, the window goes fullscreen and the title should hide.

But maybe I am missing some context here, can you try to reproduce again.

**Comment by benibenj** [comment]
You are right We are not showing the activity bar when using default position in zen mode so we also shouldn't show the title bar in zen mode when the activity bar is at the top.

**Comment by RadhiRasho** [comment]
This might be a separate issue, but it seems that when `Activity Bar` is in `Top` mode, the alt no longer switches to the menu bar. 

Also the Menu Bar when it's hidden (hamburger menu in activity bar) has a bit of an alignment issue: 
![image](https://github.com/microsoft/vscode/assets/54078496/d488fb48-54c7-4594-8214-4d7bfe77646f)


Let me know if I should move this to another issue

**Comment by benibenj** [comment]
Please create a new issue for this. Also make sure to mention which settings/mode you are using

**Comment by RadhiRasho** [comment]
New issue as mentioned above: #211353
