### ISSUE TITLE
AI sparkle is too strong

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#199528]
I like the AI sparkle but I think its color is too strong. IMO it should be less strong and so that it blends away a little more

<img width="192" alt="Screenshot 2023-11-29 at 12 46 12" src="https://github.com/microsoft/vscode/assets/1794099/61aec696-bb23-4125-8390-27aca53fd057">

**Comment by jrieken** [comment]
@hbons for help

**Comment by aiday-mar** [comment]
Hey thanks for writing about this, this is indeed a good point. I can make the opacity lower (set it for example to 0.5). With such an opacity, the icon looks as follows:

![Screenshot 2023-11-29 at 14 41 56](https://github.com/microsoft/vscode/assets/61460952/c0a3cb96-053f-492c-86c3-ac4148117a3c)

**Comment by hbons** [comment]
Looks like an improvement @aiday-mar.
