### ISSUE TITLE
UI is hard to use on 125% DPI monitor

### ISSUE THREAD

**Issue by jnm2** [Microsoft/vscode#19956]
It's not blurry or cut off like other issues I've seen here. It's just plain hard to click the menus and buttons.

I can set `"window.zoomLevel": 1.25` (100% + 20% * 1.25 = 125% :smile:) and that takes care of some of the issue, but it would be nice if it would automatically adjust so that I could leave `window.zoomLevel` at whatever zoom level I *really* want and have VS Code compensate for whatever monitor I happen to be using. For example, I'll sometimes remote in from a computer with 100% DPI and sometimes from a computer with 200% DPI. Every application that I use adjusts except VS Code.

One other thing- the menu bar does not resize, and the menu item text is almost falling off the bottom edge of the menu bar. It's pretty thin to click on.

- VSCode Version: 1.9.0 27240e71ef390bf2d66307e677c2a333cebf75af
- OS Version: Windows 10 x64

**Comment by jnm2** [comment]
Additionally, the markdown live preview is zoomed 125% too small to fit inside the area it should occupy, so there is lots of wasted space to the right and underneath the scroll bars.

**Comment by MikeDimmickMnetics** [comment]
I've raised the Markdown preview issue separately, as I'm not sure that's an Electron issue - #23095

**Comment by bpasero** [comment]
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders

**Comment by the-ress** [comment]
@bpasero The insider build looks OK to me (using 125% DPI)

1.10.2:
![vscode125](https://cloud.githubusercontent.com/assets/1612377/24874680/d67bda06-1e25-11e7-9f04-03041ca4a1dc.PNG)

The insider build:
![vscode125i](https://cloud.githubusercontent.com/assets/1612377/24874685/d8a5ed6c-1e25-11e7-8568-5e67b69f1121.PNG)

**Comment by bpasero** [comment]
I also noticed a change when I tried. Thanks 👍

**Comment by jnm2** [comment]
It seems that all the problems have been addressed in 1.21.1!  🎉
