### ISSUE TITLE
Explorer Folder Tree Keeps Auto Collapsing Even When There Is File Open

### ISSUE THREAD

**Issue by YTKme** [microsoft/vscode#199696]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.0-insider
- Commit: c6b48c364dde70c12bf977f1da50acda0fd801e3
- OS Version: macOS 14.1.1 (23B81)

Steps to Reproduce:

1. Launch VS Code
2. Open New Window
3. Load Saved Workspace
4. Continue To Work...
5. Explorer Menu Auto Collapse If I 3 finger swipe to change workspace and swipe back.

**Comment by lramos15** [comment]
This was a regression, we're working on getting a new insiders released shortly with a fix
