### ISSUE TITLE
[Feature] Request for Filter Feature in Visual Studio Code's `TEST RESULTS` Section 

### ISSUE THREAD

**Issue by hardeep-qa** [microsoft/vscode#199628]
Hi Team,

At present, the `TEST RESULTS` section in Visual Studio Code lacks a filter option. This absence makes it challenging to search for specific text within this section. I kindly request the inclusion of a filter feature to enhance usability.

Best Regards, Harry
![image](https://github.com/microsoft/playwright/assets/43902698/1446f625-162a-4da1-9e6b-2e9a348a1b8e)

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/193589#issuecomment-1804753437
