### ISSUE TITLE
Valid settings not recognized in settings.json

### ISSUE THREAD

**Issue by SharakPL** [microsoft/vscode#199658]
It would be nice to have a proper structure in settings.json. eg. to have this:
![obraz](https://github.com/microsoft/vscode/assets/5007456/cb556578-653f-435f-b503-2aa0e9a958ee)
instead of this:
![obraz](https://github.com/microsoft/vscode/assets/5007456/c6f9983a-87cb-4ff8-8d33-89e847cf609c)

And it works both ways! The problem is these grouped settings are not recognized properly:

https://github.com/microsoft/vscode/assets/5007456/79092ef5-332e-4eac-af62-16ad98d9301b

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: WIndows 11 23H2

Steps to Reproduce:

1. Open settings.json
2. Change any setting to a json object

**Comment by goyalyashpal** [comment]
* after motivated by toots regarding "have u used profiles" all around here (most recently: this https://github.com/microsoft/vscode/issues/198611#issuecomment-1833606457), 
* as apparently it is more capable than `settings.json` as it can contain the layout information, as well as enable/disable extensions, etc which the former can't
* i thought about finally looking at the profiles feature and the generated `profiles.code-profile` file, and 
* oh my my. what a ... it was 🤦 . it had more backslashes than lisp has parenthesis; it had no directly parseable structure what-so-ever. 

it was plain collection of strings - i suppose all it does is take those strings, and output them in their own separate files - which would consume the backslashes, and produces the normal `.json` files used elsewhere in vscode.

conclusion? - i didn't find anything fruitful in this regard in that file.

here's its structure:

```json
{
    "name": "profiles",
    "settings": "",
    "keybindings": "",
    "snippets": "",
    "extensions": "",
    "globalState": ""
}

```

**Comment by goyalyashpal** [comment]
> I think this might be why https://github.com/microsoft/vscode/issues/43670#issuecomment-420841680
>
>> Now that we have the settings UI, we aren't investing much in the JSON editor

classic MS - our target audience is gooey using masses. though we love to name our tools as "power*" , but we dont like power users.

> It seems support for managing settings.json is becoming lackluster, which is concerning; declarative configurations are easier to debug than UI widgets.

exactly what i was feeilng with the `*.code-profiles` becoming face of all things config related. and that file, like i said, is super "un"-toolable and is plain-text only on face of it

**Comment by goyalyashpal** [comment]
hey all! i have created a proposal which can help in grouping settings. though, not as properly as this, but still much better than no grouping. can u take a look?

* https://github.com/microsoft/vscode/issues/200686

**Comment by zoeleu** [comment]
This is still a problem. Any possible workarounds? The cascading settings work, they just aren't properly typed.

**Comment by goyalyashpal** [comment]
> The cascading settings work, they just aren't properly typed.

wow, amazing.  thanks for sharing.  

can you show with what settings you tried?  the snippet of config or screenshot etc and how did you confirmed that it was really working.

**Comment by zoeleu** [comment]
`{
    "typescript": {
        "updateImportsOnFileMove": {
            "enabled": "always"
        },
    },
    "files.autoSave": "afterDelay",
    "editor": {
        "fontFamily": "'Cascadia Code', 'Droid Sans Mono', 'monospace', monospace",
        "fontSize": 15,
        "fontLigatures": true,
        "minimap": {
            "enabled": false
        },
        "formatOnSave": true
    },
}`

works just the same as the un-cascaded version

**Comment by goyalyashpal** [comment]
> works just the same as the un-cascaded version

the reason i was asking was that did you try changing values in this hierarchial version?  as maybe these are default-ish values or some such.  

just trying to foolproof thn things here for records.

**Comment by zoeleu** [comment]
> the reason i was asking was that did you try changing values in this hierarchial version? as maybe these are default-ish values or some such.

I did, these are not the defaults.
