### ISSUE TITLE
VSCode in golang adding the letter 'o' to the right of '0' number

### ISSUE THREAD

**Issue by rrasouli** [microsoft/vscode#199639]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:57.054Z (2 wks ago)
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0
- OS Version: Macos 14.1.1 (23B81)
Steps to Reproduce:

1. having numbers numbers in golang code that starts in 0's after saving (linter?) o added to the right of that 0 number:
{code}
os.Chmod(bastionKey, 0600)
os.Chmod(privateKey, 0600)
to
os.Chmod(bastionKey, 0o600)
os.Chmod(privateKey, 0o600)
{code}

**Comment by aeschli** [comment]
Please file this against to [`go` extension](https://github.com/golang/vscode-go).
