### ISSUE TITLE
Let code actions highlight a range of code they apply to

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#199608]
## Problem

For refactoring such as `extract method` or `move to file`, it's not always clear which code the action will apply to. This is especially true for languages like TS that try to intelligently expand the user's current selection

## Proposal
Let code actions provide one (or potentially many) ranges that they will apply to. This range can then be highlighted as the user arrows through the code action list

For refactorings, this range would be the code in the current file that will be effected by the refactoring

For quick fixes, this range could be the range of the diagnostics that will be fixed (or we could just highlight the diagnostics directly since code actions already provide this info in `CodeAction.diagnostics`)

**Comment by tjx666** [comment]
Also, please consider provide a way to highlight the added code like:

https://github.com/p42ai/js-assistant

https://github.com/microsoft/vscode/assets/41773861/df9af3f4-85e0-4572-8c5d-5ebb7416b734

**Comment by justschen** [comment]
shape of the API atm:

```typescript
declare module 'vscode' {

	export interface CodeAction {
		/**
		 * A range of text that should be highlighted from the Code Action.
		 *
		 * Ex: A refactoring action will highlight the range of text that will be changed.
		 */
		editRanges?: Range[];
	}
```

**Comment by RedCMD** [comment]
could something similar be added to `[F2] Rename`?
