### ISSUE TITLE
Bug: No Windows 11 Modern Context Menu entry in 1.18 despite checked checkboxes

### ISSUE THREAD

**Issue by drandarov-io** [microsoft/vscode#199671]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2 (including previous ones)
- OS Version: W11 23H2 22635.2776 (including all recent versions)
- Tested on 5 different devices over the course of this year with different Windows Versions and user rights

Steps to Reproduce:
1. Tried to install with any of the following install methods: MS Store, Winget, System, User, 64- and 32-bit
2. Checked both context menu checks during installation
3. No entry in the context menu even after restart

I'm actually unsure if it is implemented, since I haven't seen the entry in the W11 context menu on any machine yet, but the closed Issue https://github.com/microsoft/vscode/issues/127365 suggests it is. I have no idea what to do except post this bug report. I have waited since that issue was closed last year until now, because I wasn't sure if it had something to do with me, but now I'm feel like somthing is wrong.

![image](https://github.com/microsoft/vscode/assets/13102251/434b5916-8269-4380-bfc7-1fc081cbdc40)
![image](https://github.com/microsoft/vscode/assets/13102251/48e422ef-03fc-4abc-bc58-591bfc1cb467)

**Comment by gjsjohnmurray** [comment]
Are the options present on the Show More Options submenu? AFAIK the installation of the options on the primary context menu on Windows 11 currently only happens when installing the Insiders variant.

**Comment by drandarov-io** [comment]
Yes, the options are present when pressing "Show more options", but if the feature is still not generally available after **over a year** on the Insider Channel, I feel like https://github.com/microsoft/vscode/issues/127365 shouldn't be closed.
Or am I missing something?

![image](https://github.com/microsoft/vscode/assets/13102251/e19a29cb-6886-4baf-8560-e7061ceb4640)

**Comment by gjsjohnmurray** [comment]
> I feel like #127365 shouldn't be closed

@joaomoreno has bringing this to Stable somehow dropped off the radar?

**Comment by deepak1556** [comment]
Bringing the context menu support to stable is tracked in https://github.com/microsoft/vscode/issues/183297, merging this issue as duplicate.
