### ISSUE TITLE
Print out Program Source Listing with Line Numbers

### ISSUE THREAD

**Issue by JohnT314** [microsoft/vscode#199694]
Type: <b>Feature Request</b>

I would like the ability to print out the program source code as displayed in the editor, with Line numbers (with/without preferrably being a choice).  It seems VERY strange to me that this is NOT included.    In my opinion, the idea that VS-Code is a standalone development platform covering (a lot of ) languages cannot be supported without the ability to print out the source code.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by roblourens** [comment]
Sorry, I don't understand. Print it from where?
