### ISSUE TITLE
how to Folding code, closing tag always on one line

### ISSUE THREAD

**Issue by vaynevayne** [microsoft/vscode#199632]
vscode :
<img width="457" alt="image" src="https://github.com/microsoft/vscode/assets/124666577/1219fc57-3953-4334-9caa-c66d317dd5f7">

wanted
https://www.svelte.cn/tutorial/bind-this

<img width="748" alt="image" src="https://github.com/microsoft/vscode/assets/124666577/4a97c640-8804-4c1e-8363-248641a136c7">

**Comment by aeschli** [comment]
In VS Code each language can have it's own folding provider and can decide on how much to fold.
So please file this against the Svelte extension.

That said, we only support `...` as folding text not `<->})` as you show in the screenshot. The issue for custom folding text is https://github.com/microsoft/vscode/issues/70794
Also we only support folding full lines.
