### ISSUE TITLE
A Pane to List Todos Neatly

### ISSUE THREAD

**Issue by masterSoti** [Microsoft/vscode#19963]
- VSCode Version: 1.9
- OS Version: Linux Mint

This is an enhancement request.

I drop todos all over my projects, and there needs to be a proper way to find all of them in a list with links to the position in the file. There are two problems with code that is hindering the development of a fully featured plugin to perform this task.

1. Each language must have a documentation for what the comment syntax is so that it does not have to be done manually for the extension developers.

2. There needs to be a pane to display all of todos clearly, or html must be allowed on the output pane so that the output actually looks beautiful. I really like the look and feel of the error pane(shown below), and it would be great if there was a pane where we could list the todos in a similar manner.

![image](https://cloud.githubusercontent.com/assets/6607952/22624334/51ee250e-eb36-11e6-9568-2d4f76e2e8f5.png)

**Comment by bpasero** [comment]
+1 for being able to see TODOs in problems view.

**Comment by sandy081** [comment]
There is an extension that already list TODOs in the project
https://marketplace.visualstudio.com/items?itemName=MattiasPernhult.vscode-todo

To list them in Problems Pane, one can generate diagnostics. But there is  no TODO diagnostic type. To work around it, one can use Unknown (or Info) type.

**Comment by masterSoti** [comment]
@sandy081 ,

I am really sorry if I am not supposed to converse on a closed thread, but I would like to address a couple of the points you make.

1. With all of the extensions that do this, there is none that I can move from a todo to the next with ease. There is Todo-Parser but it suffers from the problem of not being able to use the diagnostic type

1. I would also like to address the current diagnostic type. With your suggestion, the user would have to look under the Problems tab to find all of the todos. Also, the user would have all of the todos underlined with either green or red lines (even with an unkown or an info type). What I meant was for was to have an api to create a todo tab just like the problems tab where the diagnostics would not be underlined.

1. I also realize that there exists a language configuration file for all languages in vscode. I would also like a way to be also to read in the language configuration file through an api (by giving an extension as a parameter). Currently, I have been doing it by finding what the file type would be then by searching in the extensions' list for that language configuration. I mainly want to access this so that I know how each language is commented based on its file extension.

There is a lot of features about vscode api that I do not know yet, but if the api to do all of this is built out already, please let me know =).

**Comment by masterSoti** [comment]
update... I have used external libraries for commenting, but I would still love the diagnostic pane without the green underline, and the ability to create a tab that is not named Problems.
