### ISSUE TITLE
default to global .gitignore if none is found in project

### ISSUE THREAD

**Issue by haasDev** [Microsoft/vscode#19961]
- VSCode Version: 1.8.1
- OS Version: MacOS 10.11.6

Steps to Reproduce:

1.  create .gitignore in home directory
2.  create project without .gitignore file

When there is no .gitignore file in the root of the project the git feature should look to the home directory for a .gitignore file.  Currently this doesn't happen.

**Comment by bpasero** [comment]
I think we should not do anything here, in the end we run git as command and git does its things.

**Comment by joaomoreno** [comment]
Can you show us how _this doesn't happen_?

**Comment by joaomoreno** [comment]
Are you doing [this](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore)?
