### ISSUE TITLE
Problems panel filter is broken

### ISSUE THREAD

**Issue by HofiOne** [microsoft/vscode#199695]
Type: <b>Bug</b>

Even though it is stated in the filter edit box hints it should support multiple filter expressions at once, It can filter only for a single one

- tried the separator comma, as the hints are suggesting, with multiple other characters, space, semicolon, etc. also tried regular expression style filters, but none of them worked
- tried both in table and tree view

Only a single word is supported now it seems.
Please support the style the filter box hints show e.g.

![Screenshot 2023-11-30 at 18 22 04](https://github.com/microsoft/vscode/assets/12213492/fb724598-4573-4bef-87ec-1a39b11f807d)

VS Code version: Code 1.84.2 (Universal) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 7, 6|
|Memory (System)|64.00GB (0.87GB free)|
|Process Argv|--crash-reporter-id d8253db2-ba5f-473a-a6fe-1d5a62a24ea0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-django|bat|1.14.0
vscode-astyle|chi|0.9.0
regex|chr|0.4.0
yash|dao|0.2.9
vscode-markdownlint|Dav|0.52.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
gitlens|eam|14.5.1
vscode-pull-request-github|Git|0.76.1
vscode-test-explorer|hbe|2.21.1
output-colorizer|IBM|0.1.2
cmake-language-support-vscode|jos|0.0.9
vsc-python-indent|Kev|1.18.0
vscode-python-test-adapter|lit|0.8.1
autoconf|mae|0.2.0
vscode-docker|ms-|1.28.0
vscode-dotnet-runtime|ms-|2.0.0
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
remote-containers|ms-|0.321.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.19.1
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
test-adapter-converter|ms-|0.1.8
autodocstring|njp|0.6.1
explorer-exclude|Pet|1.3.2
command-variable|rio|1.60.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by sandy081** [comment]
It does not support multiple filter expressions. Filter box help suggests what kind of expressions you can type.

**Comment by HofiOne** [comment]
I also found this, which is why I opened this ticket.
Should I open a feature request instead?

Also, please note, the placeholder and the hint text are misleading, as all the other filter, search boxes that support multiple filter expressions use the same notation style.
Please consider a different notation.

**Comment by sandy081** [comment]
> Should I open a feature request instead?

It should be there already. Please search in our issues list. If not found, feel free to create one.

> Also, please note, the placeholder and the hint text are misleading, as all the other filter, search boxes that support multiple filter expressions use the same notation style.
Please consider a different notation.

Like?

**Comment by HofiOne** [comment]
> Like?

Filter (e.g. text | **/*.ts | !**/node_modules/**)

**Comment by sandy081** [comment]
I think `|` is most commonly used as OR operator.

**Comment by HofiOne** [comment]
That is why i suggested it, as the items currently can be only one of the examples, not all or multiple ones, so

either 1st, OR 2nd, OR 3rd, etc.

using a comma most of us will associate to an AND relationship
using | most will to an OR

**Comment by sandy081** [comment]
This has been there for a while and seems like most of the users read it the way it is. Hence, unfortunately, I would not prefer to change the text. I will revisit if more users feel the same.
