### ISSUE TITLE
Feature request: choose method to override for PHP in VSCode

### ISSUE THREAD

**Issue by JeromeGDev** [microsoft/vscode#199683]
Hello,

I am a PHP developer and I use VSCode as my code editor. I work with symfony and easyadmin bundle, and I often need to override some methods from the parent classes. For example, I need to override the methods configureFields(), configureAssets(), configureMenuItems(), and many others.

In phpstorm, there is a very useful feature that allows me to do this easily. It is called "choose method to override" and it is accessible by the keyboard shortcut Ctrl + o. It opens a menu that shows me a list of methods that I can override from the parent class. When I select a method, it inserts the complete code of the method in my class, with the return type, the parameters, and the body. I only need to customize it according to my needs. It saves me a lot of time and makes my work easier.

However, in VSCode, I cannot find a similar feature. The best I can do is to use the extension Intelliphense and to place myself on the parent method, and use a keyboard shortcut that shows me a list of methods that I can override. But this method has several drawbacks:
- It is complicated to use and not intuitive.
- It only inserts the name of the method, not the complete code. I have to type the return type, the parameters, and the body myself.
- It slows down, lengthens, and complicates my work.

I really want to use VSCode, but I also really need this feature "choose method to override". I think it would be very helpful for many PHP developers who work with symfony and easyadmin, or other frameworks that require overriding methods. I wonder if you could add this feature in VSCode, or if there is an extension that provides this feature.

Thank you for your attention and your work on VSCode. I appreciate it a lot.
Jerome

**Comment by roblourens** [comment]
Our built-in PHP support is very basic. This would be best for an extension
