### ISSUE TITLE
Explorer view loses position when CMD-tabbing between apps

### ISSUE THREAD

**Issue by cannontrodder** [microsoft/vscode#199669]
Type: <b>Bug</b>

Open a file, note the explorer view highlights that file in its tree structure. CMD-tab to another window on the same screen. CMD-tab back. Explorer tree collapses the folder back to the root.

VS Code version: Code - Insiders 1.85.0-insider (Universal) (c6b48c364dde70c12bf977f1da50acda0fd801e3, 2023-11-30T05:36:38.809Z)
OS version: Darwin arm64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (3.44GB free)|
|Process Argv|. --crash-reporter-id 308ff237-769a-4b56-a42e-04af4ab54dd3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.5.2
vscode-diff-viewer|cap|1.5.0
vscode-eslint|dba|2.4.2
gitlens|eam|2023.11.3004
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
markmap-vscode|ger|0.1.1
copilot|Git|1.139.0
copilot-chat|Git|0.10.2
copilot-labs|Git|0.17.1121
vscode-github-actions|git|0.26.2
todo-tree|Gru|0.0.226
terraform|has|2.29.0
vscode-drawio|hed|1.6.6
read-time|joh|1.0.0
vscode-github-actions|me-|3.0.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.28.0
remote-containers|ms-|0.325.0
vsliveshare|ms-|1.0.5896
sqltools|mtx|0.28.1
sqltools-driver-pg|mtx|0.5.2
vscode-nvm|noj|0.0.2
docthis|oou|0.8.2
vscode-jest|Ort|5.2.3
vscode-yaml|red|1.14.0
json-to-js-object|sal|0.0.4
markdown-preview-enhanced|shd|0.8.10
code-spell-checker|str|3.0.1
vscode-conventional-commits|viv|1.25.0
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30901777
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by lramos15** [comment]
Closing as duplicate
