### ISSUE TITLE
Global search is not working

### ISSUE THREAD

**Issue by erikgassler** [microsoft/vscode#199664]
Type: <b>Bug</b>

Using the Search tab, when I type in any search value and press enter, a popup with a "spawn...ENOENT" message displays directly below the search input field. I would love to copy the full message here, but this popup is not copyable and disappears when focus moves away from the input field.

This issue started after getting the latest Insiders update.

VS Code version: Code - Insiders 1.84.0-insider (eb4f3c149f34d82b9763a08230907cf79e7fc103, 2023-10-10T07:26:46.161Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.89GB (83.71GB free)|
|Process Argv|--crash-reporter-id 9e416620-5c37-4311-a831-98877d22957f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.52.0
copilot-labs|Git|0.17.1121
vscode-github-actions|git|0.26.2
todo-tree|Gru|0.0.226
vscode-test-explorer|hbe|2.21.1
rust-test-lens|hde|1.0.0
rust-doc-viewer|JSc|4.1.0
document|min|2.2.1
vscode-azureresourcegroups|ms-|0.8.0
vscode-dotnet-runtime|ms-|2.0.0
vscode-edge-devtools|ms-|2.1.3
azure-account|ms-|0.11.6
powershell|ms-|2023.11.0
test-adapter-converter|ms-|0.1.8
cargo|pan|0.2.3
rust-targets|Pol|1.1.1
rust-analyzer|rus|0.3.1748
crates|ser|0.6.3
vscode-rust-test-adapter|Swe|0.11.0
even-better-toml|tam|0.19.2
errorlens|use|3.15.0
vscode-lldb|vad|1.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialogc:30812479
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30901777
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by andreamah** [comment]
Could you take a screenshot? What are your search parameters?

**Comment by erikgassler** [comment]
I cannot take a screenshot because my VSCode blocks my PrtScn button from triggering a screenshot and like I said before, the popup disappears as soon as the field loses focus - i.e. I click anywhere else on my screen.
The search parameters do not matter. I am usually only searching one word, like `test` or `HttpClient`. I get the same issue for every search I try.
This issue has persisted across VSCode restarts as well as full computer restarts.

**Comment by andreamah** [comment]
Do you get any relevant logs in the `Extension Host` output channel?

**Comment by andreamah** [comment]
Hmm that's weird. Is there any chance you can try re-installing?

**Comment by erikgassler** [comment]
I did a fresh install. New installation doesn't have issue.
Something of note though is that my old "installation" was in a custom folder along the lines of "D:\Programs\VSCodeInsider". I don't recall it being installed using an MSI or any other installer but was downloaded to run as a standalone executable without being installed into Windows. But I couldn't see any option for doing that in the current insider downloads page, and the install process gave me no option for setting an install directory. Maybe that was an installation method that you guys deprecated?
This is not an issue as of this past weekend, but until then not having the option to install this on a separate drive likely would have led me to not have it installed at all, since my C drive had very limited space and nice-to-have apps like insider builds did not make the cut for installing on my C drive.

**Comment by andreamah** [comment]
Are you talking about Portable Mode? https://code.visualstudio.com/docs/editor/portable

**Comment by erikgassler** [comment]
Sounds familiar. It's been a really long time since I had initially installed it - I don't recognize the instructions in that link, so it's hard to say.

**Comment by andreamah** [comment]
I'll close this for now. You can reopen if you see this again.
