### ISSUE TITLE
Debugging support for Babel transpiled ES6

### ISSUE THREAD

**Issue by sujoy18** [Microsoft/vscode#19968]
I have an express.js appication which I am converting into es6 code. But unable to debug it. Please provide debugging support for es8

**Comment by weinand** [comment]
@sujoy18 you mention ES6 and ES8. Please be specific.
VS Code debugging supports es6. What problem are you seeing?

**Comment by sujoy18** [comment]
Hi Andre,Thanks a lot for replying. My problem is as follows:My express app written in ES5 could be debugged with following launch.json file "configurations": [            {            "type": "node",            "request": "launch",            "name": "Launch Program",            "program": "${workspaceRoot}\\server.js",            "cwd": "${workspaceRoot}"        },        {            "type": "node",            "request": "attach",            "name": "Attach to Process",            "port": 5858        }    ]
As I decided to move on ES6, I setup Bable as transpiler with presets setting ES2015.  Application run successfully with ES6 syntax. However, when I launch debugger, it shows error in debug console as follows: import express from 'express';^^^^^^SyntaxError: Unexpected token import    at Object.exports.runInThisContext (vm.js:76:16)    at Module._compile (module.js:542:28)    at Object.Module._extensions..js (module.js:579:10)    at Module.load (module.js:487:32)    at tryModuleLoad (module.js:446:12)    at Function.Module._load (module.js:438:3)    at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
Hope it will give you full understanding of my problem. 
Regards,Ifthekhar Hasan  

    On Monday, February 6, 2017 8:02 AM, Andre Weinand <notifications@github.com> wrote:
 

 @sujoy18 you mention ES6 and ES8. Please be specific.
VS Code debugging supports es6. What problem are you seeing?—

**Comment by weinand** [comment]
I've reformatted @sujoy18's email because it was unreadable:

Hi Andre,Thanks a lot for replying. My problem is as follows:My express app written in ES5 could be debugged with following launch.json file
```json
"configurations": [
  {
    "type": "node",
    "request": "launch",
    "name": "Launch Program",
    "program": "${workspaceRoot}\\server.js",
    "cwd": "${workspaceRoot}"
  },
  {
    "type": "node",
    "request": "attach",
    "name": "Attach to Process",
    "port": 5858
  }
]
```
As I decided to move on ES6, I setup Bable as transpiler with presets setting ES2015.  Application run successfully with ES6 syntax. However, when I launch debugger, it shows error in debug console as follows:
```json
import express from 'express';
^^^^^^SyntaxError: Unexpected token import
at Object.exports.runInThisContext (vm.js:76:16)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
```
Hope it will give you full understanding of my problem. 
Regards,Ifthekhar Hasan

**Comment by roblourens** [comment]
It looks like you are launching with the original sources. You will need to run the babel-compiled output. Closing as this is very old...
