### ISSUE TITLE
When double-clicking with two fingers on a Mac, a strange floating displacement occurs

### ISSUE THREAD

**Issue by qqharry21** [microsoft/vscode#199626]
Type: <b>Bug</b>

Use two finger tap on the sidebar extensions you will see the floating issue, this error occur frequently 

Here is the video

https://github.com/microsoft/vscode/assets/48307775/ab1e4dc2-ff38-489f-aeb1-545685dd0124

VS Code version: Code 1.84.2 (Universal) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|22, 10, 7|
|Memory (System)|32.00GB (1.85GB free)|
|Process Argv|. --crash-reporter-id 42792c7e-bbc1-47d7-bf16-4e40b51b8132|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
vscode-django|bat|1.14.0
vscode-tailwindcss|bra|0.10.3
multi-cursor-case-preserve|Car|1.0.5
turbo-console-log|Cha|2.9.6
path-intellisense|chr|2.8.5
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
vscode-jest-runner|fir|0.4.69
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
copilot|Git|1.139.0
copilot-chat|Git|0.10.2
copilot-labs|Git|0.17.1121
todo-tree|Gru|0.0.226
vsc-python-indent|Kev|1.18.0
vscode-codemetrics|kis|1.26.1
i18n-ally|lok|2.12.0
add-to-gitignore|mac|1.0.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-filesize|mkx|3.1.0
vscode-docker|ms-|1.28.0
vscode-language-pack-zh-hant|MS-|1.84.2023111509
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
remote-containers|ms-|0.321.0
color-highlight|nau|2.5.0
NextNav|Nex|1.0.5
angular-console|nrw|18.10.1
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|4.32.0
git-file-history|pom|1.0.1
quicktype|qui|12.0.46
vscode-thunder-client|ran|2.16.2
rust-analyzer|rus|0.3.1748
vscode-fileutils|sle|3.10.3
autoimport|ste|1.5.4
code-spell-checker|str|3.0.1
vscode-styled-components|sty|1.7.8
lorem-ipsum|Tyr|1.3.1
errorlens|use|3.15.0
quokka-vscode|Wal|1.0.598
vscode-import-cost|wix|3.3.0
pretty-ts-errors|yoa|0.5.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by deepak1556** [comment]
I am unable to repro with both stable and insiders, can you create a new profile with the command `Profile: Create a Temporary Profile` and check if the issue repros ?

**Comment by qqharry21** [comment]
> I am unable to repro with both stable and insiders, can you create a new profile with the command `Profile: Create a Temporary Profile` and check if the issue repros ?

I created a temporary profile and rechecked, but the problem still happens!!

https://github.com/microsoft/vscode/assets/48307775/f2fa9f69-f463-4a45-9698-47b68ada7ed7

**Comment by deepak1556** [comment]
Can you run `npx @vscode/vscode-bisect` to identify if this was a recent regression.

**Comment by qqharry21** [comment]
I've run this command, and it pop up a vscode insiders, should I test is my problem still happen on this version?
And if it still happen, then what should I do next? 
I saw the command line pop up a message to  choose Good/Bad/Retry , like this 
`Is df7d3d054020b0775fc2445c25ada7450c508524 good or bad?`

**Comment by deepak1556** [comment]
Thanks for narrowing down the issue. Closing as resolved.
