### ISSUE TITLE
File Explorer collapses VS Code gets back into focus

### ISSUE THREAD

**Issue by sascharo** [microsoft/vscode#199687]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

Typically, when you navigate between open files in File Explorer, it centers on the current file. However, you lose your place in the hierarchy if you tab out of Visual Studio Code and then return to it.

I added `"skipRefreshExplorerOnWindowFocus": true` to the _settings.json_ but it doesn't have any effect.

It's the same behavior with all extensions disabled.

**Comment by callumok2004** [comment]
I am also seeing this when a file is deleted

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode/issues/199655

**Comment by sascharo** [comment]
I just updated to 

```
Version: 1.85.0-insider (user setup)
Commit: 92772dcc29bd74108ab61ba9da5ad1f5154639ff
Date: 2023-11-30T18:37:45.605Z
```

this morning, and it seems to be fixed. It's working for me now.
