### ISSUE TITLE
`codeActionAI` shouldn't be a proposed API

### ISSUE THREAD

**Issue by umpox** [microsoft/vscode#199647]
## Description

`codeActionAI` is [currently a proposed API](https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.codeActionAI.d.ts). I would like to suggest that this is no longer proposed.

Reasoning:
- It is incredibly simple, it is just a single `boolean` value on a configuration object
- AI code actions are here to stay
- Keeping this as a proposed API means there is a disparity between other AI extensions and Copilot. It means other AI extensions can appear more prominently than other, more targeted, quick fixes (e.g. `Change spelling`).

**Comment by mjbvz** [comment]
This guide explains how api proposals work: https://github.com/Microsoft/vscode/wiki/Extension-API-process

The size of the api isn't relevant and it's proposed because we're not sure it's "here to stay" in it's current form
