### ISSUE TITLE
Notebook sticky scroll shows up too late

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#199601]
<img width="670" alt="image" src="https://github.com/microsoft/vscode/assets/876920/daeee1c9-1e0a-45d0-950d-e6c95518d139">

<img width="818" alt="image" src="https://github.com/microsoft/vscode/assets/876920/a3305f52-e54f-4a5b-8306-19cf5040eb89">

Even though I already scroll beyond the headers, since the bottom padding/margin of the markdown cell is still in the viewport, the sticky scroll is still not visible yet.

**Comment by Yoyokrazy** [comment]
Likely the same issue as [#191558](https://github.com/microsoft/vscode/issues/191558), just with a slightly easier repro. Will keep this open for now but can likely be closed alongside the other.

**Comment by Yoyokrazy** [comment]
fixed via #201837
