### ISSUE TITLE
Tasks not running in project stored on network file share

### ISSUE THREAD

**Issue by abrakidabra** [Microsoft/vscode#19964]
- VSCode Version: 1.9.0
- OS Version: Windows 10 Pro Build 1607

I have a TypeScript project stored on a Samba file share that I access remotely from a number of computers and I am unable to run tasks in that project when using Windows 10. There's no output or error message, the task just fails to run.

This is my tasks.json:

```json
{
	"version": "0.1.0",
	"command": "echo",
	"isShellCommand": true,
	"args": ["Hello World"],
	"showOutput": "always"
}
```
When I run the task on Windows 10 there is no output produced.
When I run the task on MacOS Sierra 10.12.3 the output 'Hello World' is produced as expected.

If I then copy the project folder from the file share to the local disk on Windows I am able to run the task and it outputs 'Hello World' as expected. 

I have also tested this with the TypeScript compiler in watch mode using the following tasks.json:

```json
{
	"version": "0.1.0",
	"command": "tsc",
	"isShellCommand": true,
	"args": ["-w", "-p", "."],
	"showOutput": "silent",
	"isWatching": true,
	"problemMatcher": "$tsc-watch"
}
```

This yields similar results. It runs fine on MacOS and also runs fine when I copy the project folder to my local disk, but will not run on Windows 10 from the file share.

Surprisingly though I can execute the following from either cmd or powershell and the watcher works as it should: 

```
tsc -w -p [path to project]
```

Any idea why this might be happening?

**Comment by dbaeumer** [comment]
Do you assign a drive letter to the samba share? Shell command under windows when executed in cmd.exe can't access a UNC drive (e.g. something like `\\server\path`)

**Comment by abrakidabra** [comment]
I hadn't assigned a drive letter to the share but now that I have the tasks seem to be running fine.

From the integrated terminal, without the drive letter assigned, I am able to execute both "echo Hello World" and "tsc -w -p [path to project]" and both run as expected, despite displaying a warning regarding UNC paths.

**Comment by dbaeumer** [comment]
The integrated terminal uses PowerShell whereas the task runner currently uses cmd.exe. I am in the process of using the terminal for task running so this will get better in the future.

I will close the issue since this will work in the future when executing task in the terminal. And a workaround for now exists to use driver letters instead of UNC paths. 

@abrakidabra please ping if you disagree.
