### ISSUE TITLE
scss syntax highlighting: support @layer

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#199645]
Issue of the SCSS grammar 
(We're still on the archived https://github.com/atom/language-sass)

`@layer` in 
```scss
@layer bootstrap;
@import url('bootstrap/scss/bootstrap.scss') layer(bootstrap);
```
not being highlighted is SCSS

**Comment by alexr00** [comment]
Marking as a duplicate of the issue tracking finding a new scss grammar: https://github.com/microsoft/vscode/issues/81038
