### ISSUE TITLE
Markdown scroll synchronization doesn't work

### ISSUE THREAD

**Issue by dustinmoris** [Microsoft/vscode#19966]
Hi, basically what the title says. I updated VS Code via the auto updater, and the sync scroll doesn't work. Then I downloaded the installer (read that in some other GitHub issue) but still no luck.

VSCode Version:
![image](https://cloud.githubusercontent.com/assets/4580714/22624826/f332f1f4-eb7e-11e6-823e-c7d618640aab.png)

OS Version:
![image](https://cloud.githubusercontent.com/assets/4580714/22624832/3db1856a-eb7f-11e6-8da5-9b695f8f4c4a.png)

Steps to Reproduce:

1. Update existing VS Code to 1.9
2. Open Markdown file
3. Split view
4. Click on Preview in 2nd view
5. Scroll in either window and see that nothing happens

**Comment by ITSecMedia** [comment]
Same here, doesn't work.
