### ISSUE TITLE
Unconventional and counterintuitive filename sorting: "." comes after all other characters, should come before

### ISSUE THREAD

**Issue by php4fan** [microsoft/vscode#199676]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: Manjaro linux

Steps to Reproduce:
=

1. Open a project that has files with these names:
```
functions.php
functions_admin.php
functions_user.php
```
2. Look at the list of files in the left panel ("Explorer" I think it's called)

Expected behavior
=

They should be sorted in this order:
```
functions.php
functions_admin.php
functions_user.php
```
This is the prevailing convention everywhere, it has always been, and for good reason, because it's the only right one. If not in general, certainly for file names.
The dot is commonly conventionally used to separate file name from file extension. Therefore, `xxxxx` followed by a dot means a filename `xxxxx` followed by _nothing_. And _nothing_ intuitively comes before anything. That's why the dot usually comes before any other (normal) character **at least when sorting file names**.
Again, not only is this the way sorting filenames has always been done and is done everywhere, it is the right way of doing it because it makes sense.

Observed behavior
=
They are sorted like this:
```
functions_admin.php
functions_user.php
functions.php
```
i.e. the dot (".") comes after any other character.
This is confusing, counterintuitive, illogical, _and_ contrary to prevailing and long-standing conventions. There's no justification for such behavior.

I have seen the same issue before in other pieces of software in Linux (I think starting recently), so VSCode is not alone, but that doesn't make it any less wrong, and it's the exception, not the norm.

**Comment by lramos15** [comment]
Try changing your sort options to unicode
<img width="824" alt="image" src="https://github.com/microsoft/vscode/assets/4544166/4a22a4fe-6500-437b-aee9-62f8c027fb91">

**Comment by php4fan** [comment]
That fixes the dot but it messes up the underscore.
With "unicode", the **underscore** apparently comes after all letters; so with unicode now `foobar` will come before `foo_bar` which is also counterintuitive and contrary to prevailing conventions.

**Comment by lramos15** [comment]
That matches macOS explorer at least. I think convention varies
<img width="723" alt="image" src="https://github.com/microsoft/vscode/assets/4544166/9cb5f50f-c14b-4a1b-8bf6-f41fdc57e2df">

**Comment by php4fan** [comment]
Yes, MacOS is crap when it comes to this kind of things. Apple usually goes against conventions by design.

**Comment by php4fan** [comment]
And what if I wanted to choose Uppercase first or Lowercase first. What would the behavior of underscore and dot be in those cases? Overall the choice of sorting is utter nonsense.

**Comment by lramos15** [comment]
Hmmm this is with unicode

<img width="444" alt="image" src="https://github.com/microsoft/vscode/assets/4544166/5115e9fc-bf79-4b68-8e9e-699413f1c0ee">


And here's the way the sort works

https://github.com/microsoft/vscode/blob/168df5be82370a61296f337cbb37a760cef71275/src/vs/base/common/comparers.ts#L79-L89

**Comment by php4fan** [comment]
Ok, it seems **unicode groups uppercase first**, which renders it useless unless you are one of the few people who would want uppercase first.

**Comment by lramos15** [comment]
Maybe keep an eye on https://github.com/microsoft/vscode/issues/27286 which tracks the idea of being able to provide a custom sort order
