### ISSUE TITLE
User settings in profile get a warning

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#199691]
Version: 1.85.0
Commit: Unknown
Date: Unknown
Electron: 25.9.6
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-89-generic

- create a new, empty profile
- open the user settings and add `"jake.autoDetect": true,`
- warning: `This setting has an application scope and can be set only in the user settings file.`

But this is a user settings file
![image](https://github.com/microsoft/vscode/assets/6461412/b7ea5518-ecae-4aaf-bc93-54bcc67bfd52)

**Comment by sandy081** [comment]
This is expected because the setting is defined application scoped and such settings cannot be configured in profile settings - https://github.com/microsoft/vscode/blob/c6f507deeb99925e713271b1048f21dbaab4bd54/extensions/jake/package.json#L40
