### ISSUE TITLE
Add editable command for selection.

### ISSUE THREAD

**Issue by ngunderson** [Microsoft/vscode#1996]
Add a command that mimics selection or mark similar to ctrl+space in Emacs.

**Comment by isidorn** [comment]
Can you please explain what does this command exactly do?
I think this should be done as an extension to vscode.

**Comment by runner4444** [comment]
In emacs, in the editor, if you hit ctrl+space a mark is set. This is essentially activated selection where in the user can navigate the cursor around with either arrow keys or keyboard shortcuts and highlight will be active wherever moved. ctrl+space again will then deactivate the selection. Hence ctrl+space is basically a toggle for the selection.

**Comment by isidorn** [comment]
@alexandrudima would this be possible to be done via an extension? If yes, then close this I guess

**Comment by noxdafox** [comment]
The Emacs extension partially does that.

https://marketplace.visualstudio.com/items?itemName=hiro-sun.vscode-emacs

It works when navigating the code using arrows but not with any other keyboard shortcut though.
