### ISSUE TITLE
Configure Command Decorations should skip picker with one listed item 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#199697]
1. From a Python file, use shift+enter to run a command in the Python REPL
2. From the blue circle decoration for that command, select Configure Command Decorations
3. There is only one item in the picker, I would expect us to just skip straight to the multiselect list for which decorations to enable

<img width="806" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/1cef7916-c90a-48d6-939f-389090e7fdd6">

**Comment by Tyriar** [comment]
To verify:

1. Run a command
2. Click the blue dot, there should not be a toggle visibility entry
3. Right click the blue do, the toggle visibility entry should be there
4. Activating it should show the quick pick with checkboxes immediately
