### ISSUE TITLE
Annotations at the start of a codeblock can break codeblock rendering

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#199767]
This is when an annotation is added to the triple-backtick start of a codeblock. It should only be inside the codeblock, after the newline.

<img width="433" alt="image" src="https://github.com/microsoft/vscode/assets/323878/1f744130-8bcb-40d6-a13b-4c2fc31bd4f8">

**Comment by rzhao271** [comment]
Is this the expected output?
It looks like the extension did not parse the backticks into a code block.


![Screenshot of an ask to repeat a code block showing the backticks got printed literally in the response](https://github.com/microsoft/vscode/assets/7199958/dbd17aef-25dd-445a-bdb0-e09d0ab8cca4)

**Comment by justschen** [comment]
@rzhao271 I think has to do with https://vscodeteam.slack.com/archives/C04PKH0BDQS/p1701449237374729

seems like its working for me now?

**Comment by roblourens** [comment]
- Clear your chat session and close open editors to reduce distraction. 
- Send the "repeat this code..." request.
- You should get something like this that shows a vulnerability

<img width="241" alt="image" src="https://github.com/microsoft/vscode/assets/323878/1cd3f568-cba7-41eb-a433-d435fe26afae">

If it refuses to answer, clear the session and try again
