### ISSUE TITLE
Mouse cursor rapidly flashing when positioned in certain positions

### ISSUE THREAD

**Issue by simonborje** [microsoft/vscode#199735]
Type: <b>Bug</b>

I have been able to reproduce this issue when using any color theme other than the new default theme "Dark modern" which does not have the issue - in the example I used "Kimbie Dark".

When positioning the mouse cursor at the bottom of buttons embedded in the title bar, on a position where the explanation popup would show up, the cursor starts to flash quickly. The area which triggers this is likely only one pixel in height. I suspect that the issue is caused by the explanation popup appearing and then immediately disappearing in a loop.

https://github.com/microsoft/vscode/assets/3867784/9ed3b277-bb9c-4d17-8150-04e286c5eddf

VS Code version: Code - Insiders 1.85.0-insider (621d89f2ef4b7715f681384739820cf08dfeeecd, 2023-12-01T01:39:41.186Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30901777
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2cf:30902440
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by moritz-t-w** [comment]
I've seen this in other software, it might not be an issue with vscode but rather whatever this UI is built on
