### ISSUE TITLE
unable to debug nodejs code written in es6 + async await and transpiled  with babel.

### ISSUE THREAD

**Issue by talarari** [Microsoft/vscode#19973]
- VSCode Version:1.9.0
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. clone this repository :https://github.com/talarari/vscode-debug/tree/master
2. run ```npm run build``` to transpile code with babel
3. run ``` npm install```      
4. set breakpoints in src/async-await.js like this (the breakpoints will move when you actually try to run...):
![image](https://cloud.githubusercontent.com/assets/4973087/22625964/0392a482-ebab-11e6-82bb-90198e670c00.png)
5. launch the project from inside vscode like this:
![image](https://cloud.githubusercontent.com/assets/4973087/22625968/1832c0a2-ebab-11e6-85f3-d899839a3a5f.png)

breakpoints will break in unexpected places, stepping into and over will go to unexpected places, basically debugging will not be possible.

vscode code has an awesome debugging experience, but faced with the option of debugging vs writing async-await code, the latter wins.

would really like to have both :)    
i've tried many different setups and none worked.
any project setup that will work is fine by me (babel-node,building source before running, advanced versions of node , anything else you can think of).    

if there is one that works, just fork my repo and make the needed changes.
any help will be greatly appreciated.

**Comment by weinand** [comment]
@talarari please try our new node debugger by setting "type" to "node2" and see whether this makes a difference.

**Comment by talarari** [comment]
No, doesn't help.
This is the launch config im using:
https://github.com/talarari/vscode-debug/blob/master/.vscode/launch.json

Regular es6 works fine, the problem is debugging asyc await.

**Comment by roblourens** [comment]
I'm not sure we can do any better than this, the sourcemap output looks screwy. Is it better in any other debugger?

**Comment by roblourens** [comment]
Actually, I think this could be fixed by https://github.com/Microsoft/vscode-chrome-debug-core/issues/112. But it's only an issue because the babel sourcemappings are really weird.

Where you have ```var a = `hello${name}`;```, the `a` and `name` on the generated side are mapped correctly, but the `= 'hello'` part is mapped to the wrong line for some reason. We can probably be a little more clever about how we pick mappings.

**Comment by talarari** [comment]
any update on this?

**Comment by mengxingshike2012** [comment]
I have followed by the instruction of [this](https://medium.com/@katopz/how-to-debug-es6-nodejs-with-vscode-8d00bd6c4f94), it seems that when I try to step into next line after await in a async function, the  breakpoints will break in unexpected places.
As we are using webpack2, the unconfortable thing is that we have many .babelrc files. one in project root with simple config, and one in each for the root  category e.g.  src/frontend, src/server, src/common..Does it matter

**Comment by chemitaxis** [comment]
I'm having this issue too... if I don't use await/async functions all works fine...

**Comment by chemitaxis** [comment]
Hi guys! Any news about it? Thanks!

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode-chrome-debug-core/issues/112 was closed awhile ago and the experience should be better now. Would appreciate if someone can try it out and let me know.
