### ISSUE TITLE
Malformed link in notification to open workspace

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#199715]
1. Configure display language e.g. to French
2. Open a repo that contains a workspace file
3. Get notification which says this, :bug: the markdown link is not rendered
```
Ce dossier contient un fichier d’espace de travail 'workspace.code-workspace'. Voulez-vous l’ouvrir ? [En savoir plus] (https://go.microsoft.com/fwlink/?linkid=2025315) sur les fichiers de l’espace de travail.
```

**Comment by TylerLeonhardt** [comment]
We should use locking comments (a feature of our localization pipeline) to enforce this.
```
    comment: ['{Locked="STRING TO LOCK IN PLACE"}']
```
Using the other signature of localize:
```ts
localize(
  {
    key: 'workspaceFound',
    comment: ['{Locked="]({1})"}']
  },
  "This folder contains a workspace file '{0}'. Do you want to open it? [Learn more]({1}) about workspace files.",
  workspaceFile,
  'https://go.microsoft.com/fwlink/?linkid=2025315'
) 
```

Note the use of `](` in the beginning of the `Locked` statement... this will programmatically force no space being injected.

**Comment by bpasero** [comment]
@TylerLeonhardt I was not aware. Its a bit odd having to use this directive though, can we automate it? We have a lot more usages that seem to be using a different hint:

![image](https://github.com/microsoft/vscode/assets/900690/3ad298af-8ca5-484a-b156-7d3e4c58de87)

E.g. `Please ensure the markdown link syntax is not broken up with whitespace [text block](link block)`

**Comment by TylerLeonhardt** [comment]
I don't have any good ideas for how to fix that at the moment... but at least we have an issue: https://github.com/microsoft/vscode/issues/199829

**Comment by andreamah** [comment]
<img width="422" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/e49bb499-46fb-4309-a5fa-4cf98ae07cb6">

Not sure if this is because the translation hasn't gone through, but switching the language doesn't give me the french string here.

**Comment by TylerLeonhardt** [comment]
Looks like that string was not picked up. Unusual.

**Comment by TylerLeonhardt** [comment]
![image](https://github.com/microsoft/vscode/assets/2644648/cacb8b02-8582-493d-866c-a69a65fb9d5b)

ok I think there was maybe a lag in translations as I see it now.
