### ISSUE TITLE
Typescript Language Server Error on "Move to File" in Svelte Project

### ISSUE THREAD

**Issue by ian-viri** [microsoft/vscode#199785]
Type: <b>Bug</b>

# Observed behavior

1. Create a new SvelteKit project
2. Add a new component file, e.g. `src/lib/Component.svelte`
3. Use that component in a `+page.svelte file`
4.  Open any `.ts` file, find a function, and attempt to `Refactor > Move to File`
5. See the following error from the TS lanugage server
```
<semantic> TypeScript Server Error (5.2.2) Debug Failure. File /Users/iangillis/code/blog/prisma-sveltekit-seeding/src/lib/Component.svelte has unknown extension. Error: Debug Failure. File /Users/iangillis/code/blog/prisma-sveltekit-seeding/src/lib/Component.svelte has unknown extension. at extensionFromPath (/Users/iangillis/code/blog/prisma-sveltekit-seeding/node_modules/typescript/lib/tsserver.js:21064:39) at /Users/iangillis/code/blog/prisma-sveltekit-seeding/node_modules/typescript/lib/tsserver.js:144823:221 at mapDefined (/Users/iangillis/code/blog/prisma-sveltekit-seeding/node_modules/typescript/lib/tsserver.js:2671:22) at Proxy.getMoveToRefactoringFileSuggestions (/Users/iangillis/code/blog/prisma-sveltekit-seeding/node_modules/typescript/lib/tsserver.js:144823:19) at IpcIOSession.getMoveToRefactoringFileSuggestions (/Users/iangillis/code/blog/prisma-sveltekit-seeding/node_modules/typescript/lib/tsserver.js:184487:41) at getMoveToRefactoringFileSuggesti...
```

# Expected Behavior 

Ideally, be able to use the `Move to File` refactor to move files between `.ts` and `.svelte` files. At the very least, be able to us it to move files between `.ts` files without error.

VS Code version: Code 1.84.2 (Universal) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (0.79GB free)|
|Process Argv|--crash-reporter-id 0604b2b7-da58-49ac-9bd1-50808c63cf5b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
svelte-intellisense|ard|0.7.1
vscode-tailwindcss|bra|0.10.3
postcss|css|1.0.9
vscode-eslint|dba|2.4.2
gitlens|eam|14.5.2
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|10.1.0
vscode-svelte-snippets|fiv|0.5.0
copilot|Git|1.139.0
copilot-chat|Git|0.10.2
fontawesome-autocomplete|Jan|1.3.1
rainbow-csv|mec|3.8.0
vscode-docker|ms-|1.28.0
vscode-postgresql|ms-|0.3.0
prisma|Pri|5.6.0
caseformatter|Rob|0.26.0
svelte-vscode|sve|108.1.0
vim|vsc|1.27.1
markdown-all-in-one|yzh|3.5.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by mjbvz** [comment]
Please file this issue against the Svelt extension
