### ISSUE TITLE
Git - vscode incorrectly detects encoding of a file and cause corruption

### ISSUE THREAD

**Issue by BusyJay** [microsoft/vscode#199726]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:57.054Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

Steps to Reproduce:

1. git clone https://github.com/mysql/mysql-server.git
2. Use vscode open mysql-test/t/ctype_utf8.test
3. Delete first line
4. Save the file
5. git diff

What I'm expected is git diff only show the deleted line, but it shows many other lines are also changed. The problem is ctype_utf8.test is not a UTF-8 encoded file, but vscode use UTF-8 to process the file hence all non-UTF8 characters are also changed even they are not edited. Changing the encoding to ISO 8859-2 solves the problem.

One more thing, when change the file type to binary, I was expecting the file is not effected by encoding, but turns out vscode still use encoding to process the file.

**Comment by bebuch** [comment]
We run into the same problem with our code base. Nevertheless, silently changing lines that the user hasn't touched is really bad. :-/

**Comment by ToBoMi** [comment]
I guessed there must be an option to show encoding differences in (git) diff viewer, but I didn't found one.

**Comment by lszomoru** [comment]
Sorry for not getting back to you on this until now. Are you still able to reproduce this issue. 
Are you able to reproduce the issue if you enable the `files.autoGuessEncoding` setting?

**Comment by BusyJay** [comment]
Yes, just try the reproduce steps provided in the issue body.

**Comment by lszomoru** [comment]
@BusyJay, could you please [VS Code Insiders](https://code.visualstudio.com/insiders/) as that contains the potential fix.
