### ISSUE TITLE
Enablement annd tooltip of SCM view Commit button no longer updates after changing branch

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#199771]
Type: <b>Bug</b>

I am observing this when using today's Insiders to work on the local clone of my OSS tracking repo.

If I have main checked out when I launch VS Code the Commit button is correctly disabled because main is protected, and the tip correctly states "Commit Changes to New Branch" because of this setting in .vscode/settings.json

```json
"git.branchProtectionPrompt": "alwaysCommitToNewBranch",
```
![Screenshot 2023-12-01 141427](https://github.com/microsoft/vscode/assets/6726799/c05a766d-0a6e-4102-b589-418a5dfc6508)

But when I check out a branch I previously created for a bugfix the button remains disabled and the tip is unchanged.

![Screenshot 2023-12-01 141718](https://github.com/microsoft/vscode/assets/6726799/b32b8900-4bb6-496d-8f2b-319d1d4355a8)

I have to reload the window to get the correct state and tip.

This feels like a very recent regression, as I routinely switch between main and a bugfix branch and haven't previously needede to reload before the Commit button becomes active.

VS Code version: Code - Insiders 1.85.0-insider (621d89f2ef4b7715f681384739820cf08dfeeecd, 2023-12-01T01:39:41.186Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by gjsjohnmurray** [comment]
As I was adding the screenshots after opening this a new update showed up, and after installing that the problem seems to have gone:

```
Version: 1.85.0-insider
Commit: 7caa3f698d26f7929822064baa1f3b23e7955c7d
Date: 2023-12-01T14:17:40.644Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.85.0-insider Chrome/114.0.5735.289 Electron/25.9.6 Safari/537.36
```

Closing.

**Comment by gjsjohnmurray** [comment]
FYI @lszomoru in case these symptoms don't match anything fixed today.

**Comment by lszomoru** [comment]
Thanks @gjsjohnmurray. 
This does look like an issue with the Source Control tree that we have fixed.
