### ISSUE TITLE
Code Lens's is not vertically middle

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#19979]
- VSCode Version: 1.9.0
- OS Version: sierra

I think @joaomoreno get's me in this problem: References are aligned on top of a div when you have `line-height`. Which is a bit bad because you think it's about the upper line.

<img width="227" alt="screen shot 2017-02-05 at 6 53 11 pm" src="https://cloud.githubusercontent.com/assets/2157285/22627242/61d916d8-ebd4-11e6-813c-7062d3ede965.png">

Now if it be vertically middle like this:

<img width="227" alt="screen shot 2017-02-05 at 6 53 11 pm" src="https://cloud.githubusercontent.com/assets/2157285/22627259/c3bdf800-ebd4-11e6-8250-73345a3dfb28.png">

It can be much better. I don't know if it's possible but I think a simple `vertical-align: middle` should solve it right?

**Comment by pmkary** [comment]
@alexandrudima I somehow could have guessed :D

**Comment by alexandrudima** [comment]
@pmkary What settings are you using? I've tried with:
```
    "typescript.referencesCodeLens.enabled": true,
    "editor.lineHeight": 50
```

on master, and interestingly, it appears to be bottom-aligned:

![image](https://cloud.githubusercontent.com/assets/5047891/22646590/716c5c60-ec6d-11e6-90db-cbdb18526b93.png)

**Comment by pmkary** [comment]
{
  "editor.fontSize": 13,
  "terminal.integrated.fontSize": 14,
  "editor.lineHeight": 25,
  "editor.fontFamily": "Hasklig-Medium",
  "editor.fontLigatures": true,
  "editor.tabSize": 4,
  "editor.wrappingColumn": 0,
  "editor.wrappingIndent": "same",
  "editor.quickSuggestionsDelay": 0,
  "editor.renderWhitespace": false,
  "editor.insertSpaces": true,
  "dafny.dafnyServerPath": "~\/dafny\/DafnyServer.exe",
  "window.reopenFolders": "all",
  "window.openFilesInNewWindow": false,
  "workbench.statusBar.visible": true,
  "window.titleBarStyle": "native",
  "cSpell.enabledLanguageIds": [
    "csharp",
    "go",
    "javascript",
    "javascriptreact",
    "markdown",
    "php",
    "plaintext",
    "text",
    "typescript",
    "typescriptreact",
    "yml",
    "ruby",
    "pageman",
    "html"
  ],
  "typescript.check.tscVersion": false,
  "workbench.editor.sideBySideLayout": "horizontal",
  "window.zoomLevel": 0,
  "editor.mouseWheelZoom": false,
  "git.confirmSync": false,
  "workbench.activityBar.visible": true,
  "workbench.sideBar.location": "left",
  "workbench.welcome.enabled": true,
  "typescript.referencesCodeLens.enabled": true
}

**Comment by alexandrudima** [comment]
Thank you, I could reproduce with your settings.

Here's how it looks with the fix:
![image](https://cloud.githubusercontent.com/assets/5047891/22650941/77bf4082-ec81-11e6-8ddb-4317d911bf50.png)

**Comment by pmkary** [comment]
@alexandrudima thanks a lot for the fix 👍 

Additionally I think you should include the Hasklig font in your tests because I previously found a bug: #13503 which was also fixed when dear João Moreno used the font and found the bug. (which was the reason I mentioned him in the first place.)
