### ISSUE TITLE
@terminal selected when QuickChat was already open

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#199734]
> For me `Cmd+I` on mac works. Verified the fix with that.
> 
> A remaining issue is that in this case the `@terminal` is selected, so it is overwritten when I start typing. This is unlike when the QuickChat was not open before. Will open a new issue for that. 

 _Originally posted by @chrmarti in [#197076](https://github.com/microsoft/vscode/issues/197076#issuecomment-1835701005)_

**Comment by Tyriar** [comment]
Repro:

- Set `"github.copilot.chat.terminalChatLocation": "quickChat"`
- Hit ctrl+i in terminal, type something
- ctrl+` to focus terminal (don't close quick chat)
- ctrl+i
- type something 🐛 `@terminal ` is deleted
