### ISSUE TITLE
只要一打开js文件cpu占用很高 As long as a js file occupies a high cpu

### ISSUE THREAD

**Issue by PUGE** [Microsoft/vscode#19977]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.
2.

**Comment by PUGE** [comment]
http://myweb-10017157.cos.myqcloud.com/2016/QQ%E6%88%AA%E5%9B%BE20170205222253.png
一直会以每秒好几次的频率弹出这个错误
This error will always pop up several times per second

**Comment by bpasero** [comment]
English please.
