### ISSUE TITLE
Deleted folder in codespace

### ISSUE THREAD

**Issue by vamsi999krishna** [microsoft/vscode#199709]
I was coding in codespaces and by mistakenly I deleted my folder permanently and I lost all my code.
I think you should u get an option to bring back my code or  move the deleted code in some trash.
It would be more helpful if u guys add that feature in GitHub codespaces.
No one should face this issue I like faced today.

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by IllusionMH** [comment]
This looks like request to Codespases, not VS Code editor itself. 

Also aren't Codespases tied to Git repo. In this case you can use Git features and that will track history and allows restore tlatest commit.

**Comment by rebornix** [comment]
Please file issues/reports to Codespace, thanks!
