### ISSUE TITLE
Aux window: focused window does not change to main window when focusing sidebar

### ISSUE THREAD

**Issue by JeremyTCD** [microsoft/vscode#199729]
## Issue
@bpasero I've noticed that when I use keyboard shortcuts to focus sidebar views, the main window isn't automatically focused. 

For example, say I have two windows, the main window and an aux window:

- If, in the aux window editor, I highlight some text and `Ctrl + Shift + H` (replace in files), the search view is revealed but an `Alt + Tab` to the main window is necessary before I can use my keyboard to interact with the search view.

- Similarly, if in the aux window editor, I use the "reveal active file in explorer view" command, the explorer view is revealed with the file highlighted, but an `Alt + Tab` to the main window is required before I can use my keyboard to interact with the explorer view.

Would it make sense to automatically focus the main window when a sidebar view receives focus?

**Comment by bpasero** [comment]
There is an explicit decision made by this action to not grab focus:

https://github.com/microsoft/vscode/blob/3fb8fd72cd55179d361cefa829052b3e971fb5d2/src/vs/workbench/contrib/search/browser/searchActionsNav.ts#L526

I am deferring to component owners if this should change or not. I think the rationale is that the focus should remain in the editor while being able to search.

**Comment by bpasero** [comment]
Btw I cannot reproduce the issue with revealing in the explorer, for me the window focus changes. I suggest to follow up in a separate issue providing more steps and details about your setup.

**Comment by JeremyTCD** [comment]
Thanks for the quick response again! I've recorded clips of what I thought were focus issues, let me know if I should open new issues for each case.

## Reveal active file in explorer view
My mistake on this, the focus does shift to the main window, however, keystrokes aren't registered.

In the following clip:

1. I "reveal active file in explorer view" in the main window. The explorer view is focused and I am able to use up/down keys to select another file.
2. I move the other file to a new window.
3. I "reveal active file in explorer view" in the new window.  The explorer view is focused but up/down key inputs do not work
(box at the top right hand corner of the screen displays keystrokes).

https://github.com/microsoft/vscode/assets/11733898/738e7da8-2946-43e3-9c53-c4dcfc71925c

## Search view
I believe the following line effectively focuses the search view:

https://github.com/microsoft/vscode/blob/3fb8fd72cd55179d361cefa829052b3e971fb5d2/src/vs/workbench/contrib/search/browser/searchActionsNav.ts#L532

In the following clip:

1. I "replace in files" in the main window. The search view is focused and I replace the selected text.
2. I move the file to a new window.
3. I "replace in files" in the new window.  The search view is not focused, text in search field isn't updated.

https://github.com/microsoft/vscode/assets/11733898/eae1e29e-568f-4fb7-ae66-73c854402925

**Comment by bpasero** [comment]
@JeremyTCD what OS and window manager is this? Could be a problem with that.

**Comment by JeremyTCD** [comment]
Windows 11, [PowerToys FancyZones](https://learn.microsoft.com/en-us/windows/powertoys/fancyzones). Will check if the same issues occur without FancyZones and VSCode extensions.

**Comment by JeremyTCD** [comment]
Tested in a fresh environment on a vanilla Windows 11 machine (no windows manager, fresh VSCode insiders installation, no extensions), encountered the same behaviour.

**Comment by bpasero** [comment]
Thanks, I can reproduce now. The issue with the explorer is really bizarre: its sufficient to have 2 windows open (1 main and 1 floating) and just click into the main window explorer on a file to get into this state: you cannot arrow up/down to change focus, you need to click somewhere else and than back into the explorer.

**Comment by bpasero** [comment]
@JeremyTCD you actually found 2 different issues, both very good: the fact that the window does not get focus for the search command is just a missing call to `window.focus()` when the input box gets focus. Rather than finding all the places where call `HTMLElement.focus()`, I am thinking of patching `HTMLElement.prototype.focus` to ensure the owning window gets focus too: https://github.com/microsoft/vscode/pull/199837

As for the explorer: that is a serious one, as it means keyboard navigation is broken when a list/tree gets focus after the floating window had focus. Will see to push a fix for that for our upcoming stable release: https://github.com/microsoft/vscode/pull/199840

**Comment by JeremyTCD** [comment]
Nice, thanks for the fixes!

**Comment by bpasero** [comment]
That one is covered in https://github.com/microsoft/vscode/issues/199867
