### ISSUE TITLE
Add a way for the user to configure extension activation based on workspace language

### ISSUE THREAD

**Issue by theKnightsOfRohan** [microsoft/vscode#199782]
I work with a lot of different languages, and I have a lot of language-specific extensions installed. However, I've seen that this has started to bog down my computer, and my startup times are getting pretty long. So, I was wondering if there would be a way to configure specific extensions to only be activated if a specific language were present in the file. 

In terms of settings, I would think that a preliminary config would look something like this:

```
"editor.extensions.manualConfig": true, // If false, the editor would activate extensions as they are by default
"editor.extensions.activate": [
    // These extensions would be activated no matter the project language
    "github.copilot",
    "vscode-neovim",
    ...
],
"[java]": {
    // These extensions would activate if a java file is present in the workspace
    "editor.extensions.activate": [
        "redhat.java",
        ...
    ]
}
```

I know that extensions already have similar functionality active in their source code, but a way for the user to easily configure this as well, without having to create a separate profile for each language, would be nice.

**Comment by gjsjohnmurray** [comment]
Do you know about [VS Code Profiles](https://code.visualstudio.com/docs/editor/profiles)?

**Comment by joyceerhl** [comment]
Have you also tried out disabling extensions per-workspace?

**Comment by theKnightsOfRohan** [comment]
> Have you also tried out disabling extensions per-workspace?

Yes, but I feel that that gets tedious as you work on new repos. A more automatic solution would be better, in my eyes.

**Comment by alexdima** [comment]
@sandy081 Forwarding to you. AFAIK profiles should be able to handle everything requested in this feature request.

**Comment by sandy081** [comment]
> Yes, but using profiles requires you to manually switch when cloning new repos, which can get annoying. 

What do you mean by this? Would you like to have a custom default profile to be used for new repos/workspaces?

> but I am unsure how you would handle profiles in larger repos with multiple language types,

This is manual for now, ie., one has to create and configure a profile for a given project. Other idea would be to have a custom profile checked in to the repo.

**Comment by theKnightsOfRohan** [comment]
> > Yes, but using profiles requires you to manually switch when cloning new repos, which can get annoying. 
> 
> 
> 
> What do you mean by this? Would you like to have a custom default profile to be used for new repos/workspaces?
> 
> 
> 
> > but I am unsure how you would handle profiles in larger repos with multiple language types,
> 
> 
> 
> This is manual for now, ie., one has to create and configure a profile for a given project. Other idea would be to have a custom profile checked in to the repo and VS Code will open the repo/workspace using that profile when cloned.

I would like a way to  configure custom profiles which can be loaded automatically on startup according to various criteria (probably language). I would also like to enable multiple profiles at a time, so that I can have one profile for html and one for js, which would both be enabled when I open a project with both languages, for example.

**Comment by sandy081** [comment]
Thanks for explaining your use case, unfortunately we do not have plans to support applying multiple profiles for the same workspace.
