### ISSUE TITLE
Unsaved changes error during settings migration

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#199736]
Steps to Reproduce:

1. Have following settings in your workspace settings file
```json
 "[typescript][javascript]": {
            "editor.insertSpaces": false,
            "editor.defaultFormatter": "vscode.typescript-language-features",
            "editor.formatOnSave": true,
            "editor.codeActionsOnSave": {
                "source.organizeImports": false,
                "source.fixAll": "never"
            }
          },
        "[python]": {
            "editor.codeActionsOnSave": {
                "source.organizeImports": true
            }
        },
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
```
3. Reload window
4. Settings are migrated properly but following error is shown

![image](https://github.com/microsoft/vscode/assets/10746682/a33f3b2c-d33f-48e2-bea4-3b2d5e8a1db7)

**Comment by justschen** [comment]
@sandy081 I wasn't able to repro this exactly on latest insiders. for me, it seemed to flash the warning really fast before disappearing

https://github.com/microsoft/vscode/assets/54879025/719d4ae2-1228-4d43-baac-99b0289ddbc0
