### ISSUE TITLE
Comment on Allow for floating windows #10121

### ISSUE THREAD

**Issue by hahoyer** [microsoft/vscode#199766]
It doesn't make much sense to me to have floating editor windows.
It would be much more important for the tool windows such as Output or Terminal as well as the debug windows Watch, Stack and Variables.

**Comment by bpasero** [comment]
@hahoyer would https://github.com/microsoft/vscode/issues/193267 cover what you are looking for?

**Comment by hahoyer** [comment]
I can almost agree with that. In #193267 the debug windows are not mentioned. Having these as floating windows is very important to me.

**Comment by bpasero** [comment]
Yes, I think we would not limit which view or panel to move. Closing as duplicate then.
