### ISSUE TITLE
Rename File Makes Filename Disappear

### ISSUE THREAD

**Issue by YTKme** [microsoft/vscode#199707]
This issue also occurs when you copy and paste a file within editor.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.0-insider
- Commit: 92772dcc29bd74108ab61ba9da5ad1f5154639ff
- OS Version: macOS 14.1.1 (23B81)

Steps to Reproduce:

1. Rename a file (filename disappears)
2. Collapse and expand and the filename shows
3. Try renaming the file, nothing happens

<img width="251" alt="image" src="https://github.com/microsoft/vscode/assets/3649725/06752547-2b7d-42c6-b798-26e4f208c202">

**Comment by Ssiswent** [comment]
The same:

版本: 1.85.0-insider
提交: 621d89f2ef4b7715f681384739820cf08dfeeecd
日期: 2023-12-01T01:37:06.481Z
Electron: 25.9.6
ElectronBuildId: 25427645
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

**Comment by mohammadamin16** [comment]
I could reproduce it, Can I work on this?

**Comment by amadeogallardo** [comment]
Also able to reproduce. Trying to rename a file either causes:

- The filename to disappear.
- The filename is not highlighted and cannot be changed.

**Comment by SsiswentLi** [comment]
The same as yours
