### ISSUE TITLE
`onDidChangeInlayHints` doesn't work.

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#199722]
Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

I'm reworking how the C/C++ extension populates inlay hints and semantic tokens, to progressively populate the document as additional results are available.  Beyond the first set of results, I need to use `onDidChangeSemanticTokens` and `onDidChangeInlayHints` to trigger those providers to issue new requests.  This works properly for semantic tokens but doesn't seem to work for inlay hints.  Firing the event does not trigger a new inlay hint request.  Doing almost anything, such as scrolling the document, will trigger a new request, so it could be that the event is having the intended effect, just doesn't trigger the request immediately as it should.
 
Example extension code:

```
export class InlayHintsProvider implements vscode.InlayHintsProvider {
    public onDidChangeInlayHintsEvent = new vscode.EventEmitter<void>();
    public onDidChangeInlayHints?: vscode.Event<void> = this.onDidChangeInlayHintsEvent.event;

    public triggerUpdate(): void {
        this.onDidChangeInlayHintsEvent.fire();
    }
}
```

**Comment by jrieken** [comment]
> so it could be that the event is having the intended effect, just doesn't trigger the request immediately as it should.

It says nowhere that a request is send off immediately, it's mere a signal that something has changed. The renderer decided how to handle that. What is does is that [it schedules a normal update](https://github.com/microsoft/vscode/blob/7a135a6acd758a101edf537e6d96b2ad75e72f1f/src/vs/editor/contrib/inlayHints/browser/inlayHintsController.ts#L196) (which timings depend on the averaged durations of your provider) but it doesn't do an immediate update

**Comment by jrieken** [comment]
> potentially indefinitely, until the user performs an appropriate action to trigger the update

It's not indefinite but after a delay which is derived (within bounds) from the performance of the provider (your extension) for the file in question. We do use (and need) debouncing because we cannot allow that an extension that always fires keeps us indefinitely busy.

**Comment by jrieken** [comment]
Yes, I have tried this out but your initial steps leave much room for interpretation. What you describe sounds very much like https://github.com/microsoft/vscode/issues/186620. Please read the issue careful and confirm. Also take it as inspiration how to file good bugs.

**Comment by Colengms** [comment]
This sounds similar to https://github.com/microsoft/vscode/issues/186620  (Fixed by you on the same day you commented on this issue.) , though my experience is exactly as I posted here, and further clarification would seem to require clarifying questions, which I'd encourage you to ask if there is not sufficient information to understand what was reported.
