### ISSUE TITLE
Coloration issue

### ISSUE THREAD

**Issue by jjktc** [Microsoft/vscode#19975]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Create a file
2. Add a bunch of lines of code (or don't)

You may be able to notice that the coloration isn't quite correct across the editor. There are rectangles of a darker shade of gray around any lines of code you wrote, so if there is a long line of code, there is a long rectangle of darker gray. There is also a rectangle around the lines that you currently are typing in. However, the rest of the background behind the code is an ever so slightly lighter shade of gray. The darker shade is 1e1e1e and the lighter shade is 212121. The difference is extremely apparent to me whenever I am using the software.

![vscode-coloration](https://cloud.githubusercontent.com/assets/5074313/22626369/a7cc1132-eb79-11e6-9a29-0844dcc82955.jpg)

The top half is of 1e1e1e and the bottom half is of 212121 in this particular screenshot

**Comment by bpasero** [comment]
#12473
