### ISSUE TITLE
PHP Syntax highlight doesn't handle {$variables} in double-quoted strings

### ISSUE THREAD

**Issue by php4fan** [microsoft/vscode#199790]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.84.2
- OS Version: Manjaro Linux

Steps to Reproduce:
=
1. Write this in a PHP file:

```
<?php

$array = ['x' => 'y'];

$string = "Lorem ipsum {$array['x']}";
```

Expected behavior
=
In the above code in PHP, the chunk `{$array['x']}` is expanded into the value of what's inside the `{}`, which is an element of the array.
The **braces should be somehow highlighted**, and `$array['x']` shoould be highlighted in a way similar to how array elements are highlighted outside of a string: with the array name, brackets, and index highlighted in different colors.

Observed behavior
=
It is highlighted like this:

![image](https://github.com/microsoft/vscode/assets/13969584/f3d11b6f-4ad6-47d4-b3ba-52315b408cdd)

as if 
- the braces were just part of the string, 
- only the variable `$array` itself were expanded, and
- the portion `['x']` were again just part of the string

**Comment by alexr00** [comment]
Moved to https://github.com/KapitanOczywisty/language-php/issues/15
