### ISSUE TITLE
Unlucky default color for sparkle lightbulb

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#199748]
* Use "Github Light Theme" from `GitHub.github-vscode-theme`
* the sparkle lightbulb seems to be the same color as the editor background

<img width="212" alt="Screenshot 2023-12-01 at 10 42 28" src="https://github.com/microsoft/vscode/assets/1794099/81322602-dc00-44e8-a32c-628c8945cf18">

**Comment by aiday-mar** [comment]
I can decrease the value of the lightening factor. This will however mean that the sparkles will be darker on other light themes.
