### ISSUE TITLE
CPU consumption high

### ISSUE THREAD

**Issue by aaa132452** [Microsoft/vscode#1997]
When I open a folder in vs code then open a js file of this folder,the cpu consumption will be 40%.Closing this folder will solve this problem.
Windows 10 10586.63
VS Code Version 0.10.6

**Comment by isidorn** [comment]
Do you see this for any JS folder?
If it is only on one folder can you share it so we try to reproduce this issue on our side?

**Comment by aaa132452** [comment]
It also include HTML and CSS.
I can not upload the file as zip because GitHub tells me they don't support that file type.

**Comment by jrieken** [comment]
@aaa132452 Can you outline the structure of the project or attach a screen shot showing the explorer? Also check with process explorer what child process of VS Code takes that much CPU

**Comment by aaa132452** [comment]
I don't know why i can't upload any file and GitHub tells me "Something went really wrong......"
The structure of the project : 
css
  --xxx.css
  --xxx.css
   ....
img
  --xxx.jpg
  --xxx.png
  ....
xxx.js  *6
xxx.html  *2

The process of VS code which takes much memory takes much CPU.

**Comment by jrieken** [comment]
looks like a small workspace. are those very large files?

**Comment by aaa132452** [comment]
The largest file is a js file , 103KB

**Comment by jrieken** [comment]
can you rename those files  to see if the issue then goes away. it tell me that's our JavaScript brain

**Comment by aaa132452** [comment]
I renamed it and the issue still exsits.

 

 

发件人: Johannes Rieken [mailto:notifications@github.com] 
发送时间: 2016年1月15日 16:41
收件人: Microsoft/vscode <vscode@noreply.github.com>
抄送: aaa132452 <aaa132452@outlook.com>
主题: Re: [vscode] CPU consumption high (#1997)

 

can you rename those files to see if the issue then goes away. it tell me that's our JavaScript brain

**Comment by aaa132452** [comment]
Could you please leave me a email address then I send these files to you?

**Comment by jrieken** [comment]
I believe mail will run into the same upload issue. Do you have access to dropbox or one drive?

**Comment by aaa132452** [comment]
http://1drv.ms/1ZC3PNc

**Comment by jrieken** [comment]
Thanks for the files tho I cannot reproduce the issue with them. I see low cpu utilisation unless I open a different file where is spikes for a short moment (which is to be expected). There is no permanent CPU load. 

@aaa132452 What extension do you have installed and can you test without them (`--disable-extensions command` line argument)

**Comment by nojvek** [comment]
VSCode allows opening the F12 tools right. Why can't we profile the code to see what code is consuming such high CPU?

**Comment by jrieken** [comment]
@nojvek Sure you can. The challenge is that many things run in different child processes (like search, extensions, file watching etc)

**Comment by jrieken** [comment]
need more info - will reopen then
