### ISSUE TITLE
Expand "JSON" to "JavaScript Object Notation" in language mode selection

### ISSUE THREAD

**Issue by moritz-t-w** [microsoft/vscode#199774]
![image](https://github.com/microsoft/vscode/assets/90388353/301ffadf-e541-4c77-83be-fa852a44eb88)
Unlike other programming languages "JSON" is not expanded to "Javascript Object Notation".
- What's the point of "JSON (json)"? Why not "JavaScript Object Notation (json)"
- When I search for js, the first thing I want to find is **J**ava**S**cript, not **J**ava**S**cript Object Notation.
- When I search for "JavaScript Object Notation" I want to find JavaScript Object Notation, just like I can find JavaScript when searching for "JavaScript".
![image](https://github.com/microsoft/vscode/assets/90388353/eb6027bb-ff09-4689-9d95-4d8eed82bca2)

So I propose you replace "JSON (json)" with "JavaScript Object Notation (json)"

**Comment by moritz-t-w** [comment]
As you can see, this search isn't entirely truthful anyways, since JavaScript **JS**X is matching, not **J**ava**S**cript JSX. Therefore, if "JavaScript Object Notation with Comments (jsonc)" is just too long of a label, shortening it to "JSON with Comments (jsonc)" in the displayed text but using the full name for the actual search function would be an elegant solution

**Comment by moritz-t-w** [comment]
The actual search match not aligning with what's displayed to improve usability has precedence with `JavaScript JSX`.
> JavaScript **JS**X is matching, not **J**ava**S**cript JSX.

**Comment by moritz-t-w** [comment]
If you're still not convinced, is this something that could be achieved by an extension or would I have to make a fork? I'm not asking for a tutorial, I'm just hoping you can tell me if this is even something an extension can influence.

**Comment by aeschli** [comment]
Sorry, we won't change the name, I've never heard someone calling JSON, `JavaScript Object Notation`.
You could disable the JSON extension to not see these entries.

**Comment by moritz-t-w** [comment]
My point is just that if I'm searching for js, I should see javascript first, not json. And sure people don't refer to it like that cause it's a long name but as a user of both of these languages I want to find both of them the same way. I think it's reasonable to shorten it in the display but it should still be searchable under its full name just like every other language.

**Comment by moritz-t-w** [comment]
Shouldn't this be closed as "wontfix"?
