### ISSUE TITLE
Git revert message not localized

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#199714]
<img width="415" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/3b2f1679-fdf4-4702-b4ea-1cdb88d332c8">

Looks localized here though, and hasn't changed in 13 months https://github.com/microsoft/vscode/blob/b2380d7e31545d6d21a502db46b07b79f51032d1/extensions/git/src/commands.ts#L1718-L1723

**Comment by TylerLeonhardt** [comment]
language pack looks ok too...

https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-fr/translations/extensions/vscode.git.i18n.json#L31

Looking into this some more... it seems that the new lines aren't being handled properly.

**Comment by joyceerhl** [comment]
This still repros :/ @TylerLeonhardt is the loc pipeline maybe not running?

**Comment by TylerLeonhardt** [comment]
it is the newlines... which I thought I fixed... sigh... They are being escaped in the language pack:
https://github.com/microsoft/vscode-loc/blob/f3d703e3e7663591e1f0132068e43ac71eb04de8/i18n/vscode-language-pack-cs/translations/extensions/vscode.git.i18n.json#L31

if I manually delete these extra slashes locally, the problem goes away.

**Comment by TylerLeonhardt** [comment]
Update... the text has change:
https://github.com/microsoft/vscode-loc/blob/a56bbe30c6ad54846107425a908aae5af3c5fd96/i18n/vscode-language-pack-cs/translations/extensions/vscode.git.i18n.json#L32

Now it's using `\r\n` when it should use `\n` and I think I know why.

So exporting looks find:
```
<source xml:lang="en">Are you sure you want to discard ALL changes in {0} files?&#10;This is IRREVERSIBLE!&#10;Your current working set will be FOREVER LOST if you proceed.</source>
```
`\n` is turned in to `&#10;` (we do this manually and it's the XML way to say `\n`)

but what we get from the translators... they replace `&#10;` with actual new lines 🙄 
```
      <trans-unit id="++CODE++67d45ba7ddf30d221f72b9dde82614a6b6e5ec199cca9d63f7c34a8279fa7a31">
        <source xml:lang="en">Are you sure you want to discard ALL changes in {0} files?
This is IRREVERSIBLE!
Your current working set will be FOREVER LOST if you proceed.</source>
        <target state="translated">Opravdu chcete zahodit VŠECHNY změny v souborech (celkem {0})?
Odstranění je NEVRATNÉ!
Když budete pokračovat, vaše aktuální pracovní sada se NAVŽDY ZTRATÍ.</target>
      </trans-unit>
```

That's not what I was expecting. I would expect only backtick strings to have actual newlines in the file... Not ones where we are explicit with `\n`.

So I'm wondering what would happen if we don't escape these `\n` to `&#10;`. Maybe that will keep the `\n` throughout the process. I'll make this change.

**Comment by andreamah** [comment]
<img  alt="image" src="https://github.com/microsoft/vscode/assets/31675041/064e25f9-b723-4685-b2fd-cb3e928e7c23">

Looks like it works now
