### ISSUE TITLE
VSCODE 1.9 does not display inline help and output from Python ext

### ISSUE THREAD

**Issue by RO-mix** [Microsoft/vscode#19974]
- VSCode Version: 1.9
- OS Version: win 8.1 64

 Python extension does not display inline help and Jupyter inline output.
Tryed on Linux machine - works fine. Cannot get it working on windows machine. Don`t know where exactly the problem is and how to diagnose more. Reported it here, because inline html help file does not show either.
Steps to Reproduce:

1. Python: help
2. empty output window with white background
![image](https://cloud.githubusercontent.com/assets/24660300/22626230/f838c256-ebb9-11e6-88c0-9a41258a5216.png)

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
