### ISSUE TITLE
I used to be able to click links on integrated terminal by holding the Alt key. Now, without any action on my part (I haven't even update it), it changes to some useless cross symbol.

### ISSUE THREAD

**Issue by KSXGitHub** [microsoft/vscode#199848]

**Comment by Tyriar** [comment]
The terminal's usage of `editor.multiCursorModifier` may have regressed?

**Comment by Tyriar** [comment]
The issue I'm seeing is `editor.multiCursorModifier` no longer seems to flip the terminal link modifiers and column select modifier. Additionally the `+` cursor isn't showing anymore when using column selection.

**Comment by Tyriar** [comment]
Actually I don't think it ever flipped the column select modifier

**Comment by Tyriar** [comment]
When `"editor.multiCursorModifier": "ctrlCmd"` is set, alt+click still opens fine. After https://github.com/xtermjs/xterm.js/pull/4921 the crosshair will be working as intended, the link pointer cursor will override it correctly.

**Comment by alexr00** [comment]
![Recording 2024-01-25 at 11 49 19](https://github.com/microsoft/vscode/assets/38270282/2f4546c5-ae3f-4657-bc63-e7943cd67aa2)

I can still repro if `"editor.multiCursorModifier": "alt"`. Is there something else I should set?

**Comment by aiday-mar** [comment]
Since verification steps are needed and @Tyriar is OOF, this issue will be moved to the February 2024 milestone.

**Comment by alexr00** [comment]
@meganrogge in case you know the verifications steps.

**Comment by meganrogge** [comment]
I verified that regardless of the value of `editor.multiCursorModifier`, I can open links in the terminal with ctrlCmd and holding alt allows me to do column selection, which I believe is by design.

**Comment by KSXGitHub** [comment]
It turns out that the bug has nothing to do with the cross cursor. The real cause was extension host keep crashing after a few minutes after opening a big TypeScript monorepo.
