### ISSUE TITLE
Unable to put the cursor on info popup

### ISSUE THREAD

**Issue by ImIvanGil** [microsoft/vscode#199819]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.84.2 (Universal)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:33.687Z (3 wks ago)
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0

- OS Version: Sonoma 14.2 

Steps to Reproduce:

1.  Open a file 
2.  Put the cursor on a component or element that displays info dialog (pop up)
3. I cannot put the cursor on the info dialog to click actions or scroll to see complete info. 

https://github.com/microsoft/vscode/assets/13439236/1a16c094-4659-4cac-943c-b01112ded935

Any thoughts? 

I used the extension bisect to see if it was replicable, and I can reproduce it with the extension bisect activated.

**Comment by aiday-mar** [comment]
Hi can you please verify the value of your setting `editor.hover.sticky`? If it is disabled, when the mouse moves away from the token the hover disappears

**Comment by ImIvanGil** [comment]
> editor.hover.sticky

Yeah, this solves the issue, im not sure why is it disabled, I set it to true on the settings.json, and works, Thanks a lot!
