### ISSUE TITLE
Aux window: Search in files input doesn't update if the sidebar is open

### ISSUE THREAD

**Issue by MrYuto** [microsoft/vscode#199867]
Repro:
1. Open an editor in an aux window
2. Select a text 
3. Run search in files (`ctrl + shift + f`)
4. Repeat step 3 with another selection
5. I expect the search input to be updated for a new search, but nothing happens

![Code_-_Insiders_Jx9t9kK2yc](https://github.com/microsoft/vscode/assets/75252297/637c2728-c216-4451-858a-b67808047fce)

Version: 1.85.0-insider (user setup)
Commit: 94a3d7bac770b43ce97e9685715bef1a60d1a759
Date: 2023-12-01T19:00:37.339Z
Electron: 25.9.6
ElectronBuildId: 25531495
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by bpasero** [comment]
@MrYuto can you provide textual steps of what you do and what you expect? Is it that focus does not move into the side bar?

**Comment by MrYuto** [comment]
@bpasero I updated the issue with steps to reproduce. I think this is related to a focus management issue because when I close the sidebar or click on an editor in the main window, I can again search for something else from the aux window.

**Comment by bpasero** [comment]
This is a good catch, here is what happens:
* the first time find in files is used from a floating window it works fine with the selection from the editor
* the second time, we wrongly assume that focus is in the search view and refuse to look at the active selection [1]
* conclusion is that we need to distinguish between `document.activeElement` and `document.hasFocus()`. we cannot assume that the active element also has focus and should additionally check on that too

[1]
https://github.com/microsoft/vscode/blob/4b9608ccceba9fee3d5ceb5f76e0b728d7a05068/src/vs/workbench/contrib/search/browser/searchView.ts#L1279-L1281
