### ISSUE TITLE
VSCode extremely slow to launch

### ISSUE THREAD

**Issue by zegheim** [microsoft/vscode#199825]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: Pop!_OS 22.04 LTS on 6.5.6-76060506-generic

Steps to Reproduce:

1. Start VSCode (extension disabled)
[Startup Performance.md](https://github.com/microsoft/vscode/files/13532468/Startup.Performance.md)

**Comment by bpasero** [comment]
```
window.loadUrl() => begin to require(workbench.desktop.main.js) | 14727
```

This means something spends 14s from when we `loadURL` to when we `require` our workbench file. This is time spend in Electron I think.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/192493

Can you check if the issue is present with our [exploration build](https://vscode.download.prss.microsoft.com/dbazure/download/exploration/42053f37e98a2dbaa0d108807491e716105dccd2/code-exploration-x64-1701157790.tar.gz)
