### ISSUE TITLE
Upload zip/tar files should not open them 

### ISSUE THREAD

**Issue by veredcon** [microsoft/vscode#199887]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.2
- OS Version: N/A - vscode-dev

Steps to Reproduce:

1. Upload/Drag & Drop zip/tar file
2. It will try to open it as well in text editor although files like that cannot be opened.

**Comment by veredcon** [comment]
I believe it comes from: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/browser/fileImportExport.ts#L195 

It always open in case of a file, no matter which file it is.

**Comment by happyme531** [comment]
Duplicate https://github.com/microsoft/vscode/issues/168809
