### ISSUE TITLE
GNOME: mouse pointer icon not changing

### ISSUE THREAD

**Issue by ciao1092** [microsoft/vscode#199860]
Type: <b>Bug</b>

Moving the mouse pointer around does not change its appearance (e.g. it does not change from normal arrow to pointer to text selector when going from empty surface to link to text editor)

Instead it will only show an arrow (the default cursor)

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.5.12-300.fc39.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|15.38GB (10.80GB free)|
|Process Argv|--unity-launch --crash-reporter-id 86c53b14-1495-40b1-ac5a-b0cf1ad5c04c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (165)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.1.4
better-comments|aar|3.0.2
alpine-js-intellisense|adr|1.2.0
vscode-caniuse|aka|0.5.4
vscode-flutter-helper|aks|0.2.5
Bookmarks|ale|13.4.2
project-manager|ale|12.7.0
flutter-snippets|ale|3.0.0
pug|ama|1.0.1
linker-script|ama|0.1.0
vscode-twig-pack|baj|1.1.0
troff|ban|1.0.24
vscode-intelephense-client|bme|1.10.1
vscode-tailwindcss|bra|0.10.3
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
laravel-blade|cjh|1.1.2
js-codeformer|cms|2.6.1
jsrefactor|cms|3.0.1
gitignore|cod|0.9.0
vscode-qrcode|Com|0.2.0
doxdocgen|csc|1.4.0
dart-code|Dar|3.78.0
flutter|Dar|3.78.0
vscode-markdownlint|Dav|0.52.0
vscode-eslint|dba|2.4.2
vscode-faker|dee|2.0.0
composer-php-vscode|DEV|1.41.14263
intelli-php-vscode|DEV|0.10.14222
phptools-vscode|DEV|1.41.14263
profiler-php-vscode|DEV|1.41.14263
nasm-language-support|doi|1.2.0
xml|Dot|2.5.1
gitlens|eam|14.5.2
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
apacheconf-snippets|eim|1.3.0
htmlentity-replacer|enr|2.1.0
vsc-material-theme|Equ|34.3.0
vsc-material-theme-icons|equ|3.2.0
prettier-vscode|esb|10.1.0
vscode-solution-explorer|fer|0.8.4
vscode-firefox-debug|fir|2.9.10
auto-close-tag|for|0.5.14
shell-format|fox|7.2.5
x8664assembly|fre|0.1.0
language-forth|ftt|0.0.5
sort-json-array|fvc|3.1.0
codespaces|Git|1.16.2
vscode-pull-request-github|Git|0.76.1
go|gol|0.40.0
gc-excelviewer|Gra|4.2.58
todo-tree|Gru|0.0.226
vscode-htmlhint|HTM|1.0.5
rest-client|hum|0.25.1
output-colorizer|IBM|0.1.2
vscode-mustache-snippets|img|2.0.2
ionic|Ion|1.61.0
vscode-edit-csv|jan|0.8.3
better-cpp-syntax|jef|1.17.2
vscode-insertdatestring|jsy|2.3.1
vscode-colorize|kam|0.11.1
batch-rename|kar|0.0.5
batch-snippits|kdo|0.0.1
vscode-codemetrics|kis|1.26.1
csharpextensions|kre|1.7.3
vscord|Leo|5.1.18
nasm|Luc|1.2.1
nasmcustom|Luc|1.1.0
flutter-tree|mar|1.0.0
web-accessibility|Max|0.2.83
twig-language-2|mbl|0.9.4
lang-freebasic|me0|2.0.0
rainbow-csv|mec|3.9.0
code-beautifier|mic|2.3.3
import-sorter|mik|3.3.1
sort-selection-concentrically|min|1.0.4
vscode-apache|mrm|1.2.0
vscode-attrs-sorter|mrm|2.1.0
vscode-pugbeautify|mrm|1.0.2
vscode-docker|ms-|1.28.0
csdevkit|ms-|1.0.14
csharp|ms-|2.12.19
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26
vscode-edge-devtools|ms-|2.1.3
isort|ms-|2023.10.1
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
jupyter|ms-|2023.10.1100000000
jupyter-keymap|ms-|1.1.2
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.321.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
atom-keybindings|ms-|3.3.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.19.1
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.11
makefile-tools|ms-|0.7.0
notepadplusplus-keybindings|ms-|1.0.7
powershell|ms-|2023.8.0
remote-explorer|ms-|0.4.1
vsliveshare|ms-|1.0.5896
color-highlight|nau|2.5.0
laravel-blade|one|1.34.0
dart-syntax-highlighting-only|osc|1.0.1
basic|pac|1.0.0
web|pac|1.0.0
x8664assemblys|pen|0.1.0
explorer-exclude|Pet|1.3.2
vscode-versionlens|pfl|1.9.2
adwaita-theme|pio|1.1.0
material-icon-theme|PKi|4.32.0
polacode|pnp|0.3.4
vscode-css-peek|pra|4.4.1
inline-html|pus|0.3.9
quicktype|qui|12.0.46
vscode-data-preview|Ran|2.3.0
fabric8-analytics|red|0.7.3
java|red|1.25.0
vscode-xml|red|0.26.1
frosted-glass-theme|Ric|0.6.13
vscode-sort-json|ric|1.20.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1748
vscode-javascript-booster|sbu|14.0.1
crates|ser|0.6.3
vscode-blade-formatter|shu|0.23.5
alpinejs-syntax-highlight|spe|1.0.1
autoimport|ste|1.5.4
move-ts|str|1.12.0
ignore-gitignore|stu|1.0.1
lua|sum|3.7.3
even-better-toml|tam|0.19.2
shellcheck|tim|0.35.0
gnu-mapfiles|tro|1.1.0
cmake|twx|0.0.17
sort-lines|Tyr|1.11.0
errorlens|use|3.15.0
non-breaking-space-highlighter|vik|0.0.3
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22
vscodeintellicode-insiders|Vis|1.1.10
properties-validator|viv|0.0.6
vscode-gradle|vsc|3.13.5
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.25.15
vscode-maven|vsc|0.43.0
volar|Vue|1.8.24
quokka-vscode|Wal|1.0.598
twig|wha|1.0.2
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.34.0
php-pack|xde|1.0.3
five-server|yan|0.2.3
markdown-all-in-one|yzh|3.5.1
linkerscript|Zix|1.0.3
vue|znc|0.12.0
php-intellisense|zob|1.3.3

(29 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by ciao1092** [comment]
Update: it seems it isn't working in Chrome either.
It works in Firefox and other apps.

**Comment by ciao1092** [comment]
Reopening: also happening in Debian 11 (Parrot OS)

**Comment by ciao1092** [comment]
I tried to disable hardware acceleration, but that didn't seem to do anything...

**Comment by ciao1092** [comment]
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 6.5.0-13parrot1-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 3978)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.39GB (12.13GB free)|
|Process Argv|--unity-launch --crash-reporter-id ecde3380-e55c-477e-9deb-f9d41ef86ab9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (166)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.1.4
better-comments|aar|3.0.2
alpine-js-intellisense|adr|1.2.0
vscode-caniuse|aka|0.5.4
vscode-flutter-helper|aks|0.2.5
Bookmarks|ale|13.4.2
project-manager|ale|12.7.0
flutter-snippets|ale|3.0.0
pug|ama|1.0.1
linker-script|ama|0.1.0
vscode-twig-pack|baj|1.1.0
troff|ban|1.0.24
vscode-intelephense-client|bme|1.10.2
vscode-tailwindcss|bra|0.10.4
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
laravel-blade|cjh|1.1.2
js-codeformer|cms|2.6.1
jsrefactor|cms|3.0.1
gitignore|cod|0.9.0
vscode-qrcode|Com|0.2.0
doxdocgen|csc|1.4.0
dart-code|Dar|3.80.0
flutter|Dar|3.80.0
vscode-markdownlint|Dav|0.53.0
vscode-eslint|dba|2.4.2
vscode-faker|dee|2.0.0
composer-php-vscode|DEV|1.42.14434
intelli-php-vscode|DEV|0.10.14222
phptools-vscode|DEV|1.42.14434
profiler-php-vscode|DEV|1.42.14434
nasm-language-support|doi|1.2.0
xml|Dot|2.5.1
gitlens|eam|14.6.1
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
apacheconf-snippets|eim|1.3.0
htmlentity-replacer|enr|2.1.0
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.3.1
vscode-solution-explorer|fer|0.8.5
vscode-firefox-debug|fir|2.9.10
auto-close-tag|for|0.5.15
shell-format|fox|7.2.5
x8664assembly|fre|0.1.0
language-forth|ftt|0.0.5
sort-json-array|fvc|3.1.0
codespaces|Git|1.16.5
vscode-pull-request-github|Git|0.78.1
go|gol|0.40.1
gc-excelviewer|Gra|4.2.58
todo-tree|Gru|0.0.226
vscode-htmlhint|HTM|1.0.5
rest-client|hum|0.25.1
output-colorizer|IBM|0.1.2
vscode-mustache-snippets|img|2.3.1
ionic|Ion|1.64.0
vscode-edit-csv|jan|0.8.3
better-cpp-syntax|jef|1.17.2
vscode-insertdatestring|jsy|2.3.1
vscode-colorize|kam|0.11.1
batch-rename|kar|0.0.5
batch-snippits|kdo|0.0.1
vscode-codemetrics|kis|1.26.1
csharpextensions|kre|1.7.3
vscord|Leo|5.1.18
nasm|Luc|1.2.1
nasmcustom|Luc|1.1.0
flutter-tree|mar|1.0.0
web-accessibility|Max|0.2.83
twig-language-2|mbl|0.9.4
lang-freebasic|me0|2.0.0
rainbow-csv|mec|3.9.0
code-beautifier|mic|2.3.3
import-sorter|mik|3.3.1
sort-selection-concentrically|min|1.0.4
djlint|mon|2023.11.0
vscode-apache|mrm|1.2.0
vscode-attrs-sorter|mrm|2.1.0
vscode-pugbeautify|mrm|1.0.2
vscode-docker|ms-|1.28.0
csdevkit|ms-|1.1.16
csharp|ms-|2.14.8
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26
vscode-edge-devtools|ms-|2.1.3
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1003402403
jupyter-keymap|ms-|1.1.2
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
atom-keybindings|ms-|3.3.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.19.1
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.13
makefile-tools|ms-|0.8.22
notepadplusplus-keybindings|ms-|1.0.7
powershell|ms-|2023.8.0
remote-explorer|ms-|0.4.1
vsliveshare|ms-|1.0.5900
color-highlight|nau|2.5.0
laravel-blade|one|1.34.0
dart-syntax-highlighting-only|osc|1.0.1
basic|pac|1.0.0
web|pac|1.0.0
x8664assemblys|pen|0.1.0
explorer-exclude|Pet|1.3.2
vscode-versionlens|pfl|1.9.2
adwaita-theme|pio|1.1.0
material-icon-theme|PKi|4.32.0
polacode|pnp|0.3.4
vscode-css-peek|pra|4.4.1
inline-html|pus|0.3.9
quicktype|qui|12.0.46
vscode-data-preview|Ran|2.3.0
fabric8-analytics|red|0.9.1
java|red|1.25.1
vscode-xml|red|0.26.1
frosted-glass-theme|Ric|0.6.16
vscode-sort-json|ric|1.20.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1782
vscode-javascript-booster|sbu|14.0.1
crates|ser|0.6.5
vscode-blade-formatter|shu|0.23.5
alpinejs-syntax-highlight|spe|1.0.1
autoimport|ste|1.5.4
move-ts|str|1.12.0
ignore-gitignore|stu|1.0.1
lua|sum|3.7.3
even-better-toml|tam|0.19.2
shellcheck|tim|0.35.0
gnu-mapfiles|tro|1.1.0
cmake|twx|0.0.17
sort-lines|Tyr|1.11.0
errorlens|use|3.16.0
non-breaking-space-highlighter|vik|0.0.3
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22
vscodeintellicode-insiders|Vis|1.1.10
properties-validator|viv|0.0.6
vscode-gradle|vsc|3.13.5
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.25.15
vscode-maven|vsc|0.43.0
vim|vsc|1.27.2
volar|Vue|1.8.27
quokka-vscode|Wal|1.0.609
twig|wha|1.0.2
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.34.0
php-pack|xde|1.0.3
five-server|yan|0.2.3
markdown-all-in-one|yzh|3.5.1
linkerscript|Zix|1.0.4
vue|znc|0.12.0
php-intellisense|zob|1.3.3

(29 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
f6dab269:30613381
showlangstatbar:30737416
962ge761:30917236
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184c:30925681

```

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/97864

**Comment by ciao1092** [comment]
Same system, seems to work on KDE

**Comment by deepak1556** [comment]
>  it seems it isn't working in Chrome either.

Did you try with vscode.dev or is it an issue with any website ?

**Comment by ciao1092** [comment]
Any website...

**Comment by deepak1556** [comment]
Can you open an issue in https://bugs.chromium.org/p/chromium/issues/list, this seems like a generic issue in the runtime based on chromium and not something we can address.
