### ISSUE TITLE
Disable hover in editor

### ISSUE THREAD

**Issue by misantronic** [Microsoft/vscode#19988]
- VSCode Version: 1.9.0
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. Write a function
2. Reference it somewhere
3. Mouse-Hover the function pops up a little box with informations

Just as described in https://code.visualstudio.com/docs/editor/editingevolved#_hover

Is there a way to disable it or at least set a delay?
I find myself in many situations where this just blocks my view.

**Comment by alexandrudima** [comment]
Unofficial (hence the squiggle you'll get), but here goes: `"editor.hover": false`

**Comment by misantronic** [comment]
Works quite well, thank you!

Its not that the hover-informations are bad, they just pop up everywhere :)
I would suggest to add a delay-option to keep the popup-rate low.

**Comment by alexandrudima** [comment]
It isn't user configurable, the delays is hard-coded to 300ms.

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/hover/browser/hoverOperation.ts#L51

**Comment by WoodyWoodsta** [comment]
Incredible. I was just looking for this. The HTML and CSS hovers are way too verbose. I've been working with CSS for a while, I know what `background` does :smile: 

What would be better is if the popups could be triggered by some other, more intentional means, such as a keyboard shortcut. I'd hazard a guess that 95% of the time, the user wants information provided by the popup after actively deciding to find it. The hover action does not convey this degree of intention.

**Comment by alexandrudima** [comment]
At least on linux it is `ctrl+k ctrl+i`. Look for `F1 > Show Hover`

**Comment by WoodyWoodsta** [comment]
Brilliant :+1: Thank you.

**Comment by misantronic** [comment]
I get an error-message when doing so:
`Cannot read property 'startShowingAt' of undefined`

**Comment by WoodyWoodsta** [comment]
@misantronic Confirmed. Reloading the window does not resolve the issue.

**Comment by alexandrudima** [comment]
@misantronic @WoodyWoodsta `ctrl+k ctrl+i` works for me:

I position the cursor at the position I'm interested in and press `ctrl+k crtl+i` on windows:

![hover-kb](https://cloud.githubusercontent.com/assets/5047891/22656787/b05c41ac-ec94-11e6-9340-4c5ec5d86adb.gif)

Perhaps there's something more to it? (to get `Cannot read property 'startShowingAt' of undefined` ?

**Comment by WoodyWoodsta** [comment]
After looking around, it appears that the keybind works after setting `editor.hover` to `false` but only up until you reload the window. After reloading the window, the error shows. Setting `editor.hover` back to `true` only reflects when reloading the window again.

**Comment by WoodyWoodsta** [comment]
In my opinion, editor hovers could benefit from having more configuration. For example, hovers on linter errors are incredibly helpful (required, in fact, unless you want to keep opening the errors pane), but html tag info: not so much. Typescript-like info in a normal Javascript file is also a question mark in my mind. It is unfortunate that it is an all-or-nothing choice (and an unofficial one too). I am unsure of the mechanism behind hovers, but if this is something worth discussing further, then should a new issue be opened?

**Comment by misantronic** [comment]
@alexandrudima I am on mac and supossed to press ctrl + J. Whenever I do set the error-message pops up. Might be a mac issue?

@WoodyWoodsta I totally agree on that.
I use flow a lot and hovering is really helpful in those cases. but most of the time - I dont need the popups.

**Comment by DarrylD** [comment]
> I use flow a lot and hovering is really helpful in those cases. but most of the time - I dont need the popups.

I'm in the same boat, any solution to this? I also get `Cannot read property 'startShowingAt' of undefined`

**Comment by romines** [comment]
See #32786

**Comment by amackintosh** [comment]
"editor.hover": false doesn't work anymore. I really wish it did. These menus flying all over the place are super annoying and always cause problems with selecting text on the line above.

![editor](https://user-images.githubusercontent.com/25964567/32036978-c9e8db10-b9d7-11e7-976f-bb5c1c9c0a01.png)

**Comment by amackintosh** [comment]
This is super annoying. `"editor.hover": false,` does work and requires a restart of VS Code, but it also disables ES Lint. I can't stand it and I can't live without it :(

**Comment by alexandrudima** [comment]
@amackintosh Problems can also be viewed in the problems panel (View > Problems) or in the editor via F8/Shift-F8

**Comment by amackintosh** [comment]
Thanks, but that is not efficient. I want every tool tip except this one:

![editor](https://user-images.githubusercontent.com/25964567/32075479-cbbbb91a-ba51-11e7-85e4-3084069cd3f2.png)

The fastest possible solution would be to increase the hover time to like 500ms, because it comes up pretty much instantly and prevents selecting text that is above the text that the mouse passes through.

**Comment by alexandrudima** [comment]
@amackintosh The last screenshot is of parameter hints. `editor.parameterHints: false`. As for the type information hover, perhaps @mjbvz can transmit or capture the feedback to the TS team that the type information becomes useless in JavaScript when the type requires more than 100 chars to convey (i.e. is very complex or "not-nameable").

**Comment by mjbvz** [comment]
Yes we have a few issues tracking improving display of complex types:

- https://github.com/Microsoft/TypeScript/issues/1510
- https://github.com/Microsoft/TypeScript/issues/13095
- https://github.com/Microsoft/TypeScript/issues/8134
