### ISSUE TITLE
Scrolling with Surface Pro 4 is terrible. Delays to start scrolling.

### ISSUE THREAD

**Issue by CarlosDanielFP** [Microsoft/vscode#19980]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Try to scroll with the touchpad in the Surface Pro 4
2. Wait one second until it starts scrolling

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13612 and https://github.com/Microsoft/vscode/issues/12637
