### ISSUE TITLE
Vscode-insiders - File renaming not working ( i.e. side-panel, right click on a file and choose rename, not working) 

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode#199891]
Vscode-insiders - File renaming not working ( i.e. side-panel, right click on a file and choose rename, not working) 

VS Code Version: 

Version: 1.85.0-insider
Commit: 621d89f2ef4b7715f681384739820cf08dfeeecd
Date: 2023-12-01T01:38:16.445Z
Electron: 25.9.6
ElectronBuildId: 25427645
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-89-generic

- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. In side-panel, right click on a file and choose rename
2.

**Comment by lramos15** [comment]
This should be fixed, let me know if you're still experiencing issues
