### ISSUE TITLE
Text selection is very slow

### ISSUE THREAD

**Issue by mosajjal** [Microsoft/vscode#19982]
- VSCode Version:
Version 1.9.0
Commit 27240e71ef390bf2d66307e677c2a333cebf75af
Date 2017-02-02T08:21:13.228Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:
Arch Linux, 4.4.42-1-lts

Steps to Reproduce:

1. Open a big file (in my case ~8.5k lines) 
2. Try to select 20 lines with mouse drag
3. See it taking 3-4 seconds with freezes.

I wonder it has something to do with the "selected word count" function being called each time a word is selected, which is shown in statusbar.

**Comment by bpasero** [comment]
To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

**Comment by mosajjal** [comment]
I did for 4-5 times. Here's the CPU profile

[CPU-20170205T220619.cpuprofile.txt](https://github.com/Microsoft/vscode/files/753193/CPU-20170205T220619.cpuprofile.txt)

**Comment by mosajjal** [comment]
looks like `internal/process/next_tick.js` is taking up some time. I'm not an expert on reading the profile but it sure looks like it

**Comment by alexandrudima** [comment]
@mosajjal Indeed, most of the time is spent in `$trySetDecorations`. This is an API call that comes in from the extension host and my guess is that you have an extension that is creating spamming us with decorations.

Does the issue still occur when you launch VS Code w/ extensions disabled? From the command line: `code --disable-extensions` ?

**Comment by mosajjal** [comment]
yes. It got fixed after disabling extensions. 
Although I haven't installed anything out of ordinary in my vscode. 

![image](https://cloud.githubusercontent.com/assets/10158936/22650645/5ed1a9c0-ec95-11e6-846d-f85ba1fc92a1.png)

I'll disable these extensions one by one to find the "rouge" one and will open issue in the extension's repository. 

thanks, you can go ahead and close this one if you want. Or I can provide more feedback about which extension caused the hiccup.

**Comment by mosajjal** [comment]
ok I found the extension. It's the "Guides" which helps with python indentation.

**Comment by alexandrudima** [comment]
Thank you for tracking it down. The best would be to let the extension author know about the perf issue in large files.
