### ISSUE TITLE
Several versions of vscode after update

### ISSUE THREAD

**Issue by saitam1** [Microsoft/vscode#19986]
After updating now the second time vscode, I can now right-click a file and open it with 3 different versions of it: 1.6.1, 1.8.1 & 1.9.0.

How can I either automatically prevent this on an update or remove the old versions after the updates? Many thanks in advance!

My OS Version is: Mac OSX 10.11.5

**Comment by joaomoreno** [comment]
Can you show us a screenshot?

Can you locate those other versions? If so, can you remove them?

**Comment by saitam1** [comment]
Strangely version 1.8.1 disappeared just after I opened a file with it and then inside of it clicked `Code`--> `About Visual Studio Code` to view the version number. The shown number was 1.9.0. But version 1.6.1 is still there and is located in: `/Users/username/Library/Application Support/com.microsoft.VSCode.ShipIt/update.OhD5XFk`. Can I just delete it? Here is a screenshot of what I mean:

<img src="https://cloud.githubusercontent.com/assets/23245678/22644902/b9f82274-ec64-11e6-9390-1d2a4a1ad9ea.png">

**Comment by joaomoreno** [comment]
You can just delete it.
