### ISSUE TITLE
Error pylint is not installed when vscode has installed it

### ISSUE THREAD

**Issue by G109B** [Microsoft/vscode#19989]
- VSCode Version: Code 1.9.0
- OS Version: Windows 10 Pro w/all updates
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.8|

---

Steps to Reproduce:

1. Save a python source file
2. Agree to install pylint by clicking the error message
3. Installation procedure says pylint already installed (I did it more than once).
4. Save a python source file - error always reported, even if select disable option.

**Comment by bpasero** [comment]
@G109B can you share a screenshot of the error?

**Comment by G109B** [comment]
The first pic is after saving the file, the second after choosing 'install' and the save again.
![image](https://cloud.githubusercontent.com/assets/17625062/22648838/441b7a18-ec70-11e6-96c4-25677976548d.png)
![image](https://cloud.githubusercontent.com/assets/17625062/22648884/84f2d7fc-ec70-11e6-8fd6-41d25f6ccb88.png)

**Comment by G109B** [comment]
Maybe the python code is so bad it is confusing ? The code runs on a Raspberry Pi, but doesn't seem to do what I hoped yet.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by G109B** [comment]
This all started by VS code advice to install the python extension, so I have uninstalled it as I can live without it. Thanks for your help.

**Comment by joaomoreno** [comment]
Moved to DonJayamanne/pythonVSCode#713
