### ISSUE TITLE
Make the new icon picker generally usable for other components and adopt in terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#199964]
Forked off from https://github.com/microsoft/vscode/issues/188972#issuecomment-1753216468 as that issue is closed.

Related: https://github.com/microsoft/vscode/issues/171076

We currently have a blaring inconsistency in the UI with 2 separate icon pickers:

![image](https://github.com/microsoft/vscode/assets/2193314/5c76b56c-8492-4301-97c8-9ae47ae26b07)

![image](https://github.com/microsoft/vscode/assets/2193314/983a4130-dba2-44de-8c39-a44a6dbd8104)

I consider this icon picker work still a work in progress and not completed because of this. To fix this, before the terminal adopts we need more icons in the picker (https://github.com/microsoft/vscode/issues/171076) such that the regression in functionality in the terminal is not so severe. For example we must have icons debian, ubuntu, etc.

Breakdown of work:

- [ ] Define the subset of codicons to be exposed to the user https://github.com/microsoft/vscode/issues/171076 @hbons 
- [ ] Define how the icons are exposed to different components, this may need some smarts around what icons are displayed when filtering vs not such that the icon picker size doesn't get too large @hbons 
- [ ] Implement the changes in the icon picker and make it usage in the terminal @sandy081 
- [ ] Adopt the new API in the terminal @Tyriar

**Comment by Tyriar** [comment]
Adopted in https://github.com/microsoft/vscode/pull/209118, I deduped the icons and selected the first in the icon registry of any given `fontCharacter`.

**Comment by gusbemacbe** [comment]
Good evening, @Tyriar!

Will we be able to choose our custom icons for user profile and terminal icon? For example, Codicons does not have brain, flower, paint roller icons, unlike Font Awesome has.

**Comment by Tyriar** [comment]
@gusbemacbe yes I believe this is possible with this change, if icons from extensions aren't pulled in could you create an issue?
