### ISSUE TITLE
On Execution of vscode.executeInlayHintProvider comamnd, hints are not getting added/shown in the document

### ISSUE THREAD

**Issue by ajaygera** [microsoft/vscode#199961]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.0
- OS Version: Windows 11

Steps to Reproduce:

On Execution of vscode.executeInlayHintProvider comamnd, hints are not getting added/shown in the document. Please note, hints are getting added/shown, when we type any character in the editor.
I need to execute vscode.executeInlayHintProvider built-in command, on some context menu in the editor. (as 
I am facing two issues on executing vscode.executeInlayHintProvider comamnd:-
1) hints are not getting added/shown in the editor even though my custom hint provider (HintsProvider, as shown below) which implements vscode.InlayHintsProvider  is getting called.
2) my custom hint provider (HintsProvider, as shown below) is getting called on typing in the document. I want this is to be invoked only on execution of command - vscode.executeInlayHintProvider. (this built in command i am executing from onGeneratEvent  as shown below)

Following is the code snippet of custom hint provider :-

export class HintsProvider implements vscode.InlayHintsProvider {
    onDidChangeInlayHints?: vscode.Event<void>;
    static counter: number = 90;
    provideInlayHints(document: vscode.TextDocument, range: vscode.Range, token: vscode.CancellationToken): vscode.ProviderResult<vscode.InlayHint[]> {
        var provider = new HintsProvider();
        return new Promise<vscode.InlayHint[]> ((resolve,reject) =>{
        let ret: Array<vscode.InlayHint> = new Array();
        HintsProvider.counter++;
        let tempList: Array<vscode.InlayHintLabelPart> = new Array();
        let temp: vscode.InlayHintLabelPart = new vscode.InlayHintLabelPart(`labelHint${HintsProvider.counter}`);
        temp.tooltip = "hint tooltip";
        tempList.push(temp);
        let start = range && range.start ? range.start : new vscode.Position(1, 0);
        let retValue: vscode.InlayHint = new vscode.InlayHint(start, tempList, vscode.InlayHintKind.Parameter);
        let textRange = (range && range.start && range.end) ? range : new vscode.Range(new vscode.Position(1, 1), new vscode.Position(5, 10));
        let edit: vscode.TextEdit = new vscode.TextEdit(textRange, "hint text to be inserted");
        retValue.textEdits = new Array();
        retValue.textEdits.push(edit);
        ret.push(retValue);        
        resolve(ret);            
        });        
    }

    resolveInlayHint?(hint: vscode.InlayHint, token: vscode.CancellationToken): vscode.ProviderResult<vscode.InlayHint> {
        return new Promise<vscode.InlayHint>((resolve, reject) => {
            resolve(hint);
        })
    }

//Following is the code snippet of some function , where i execute command - vscode.executeInlayHintProvider.

  private onGeneratEvent = async (event:GenerateNLtoSQLErrorEventParams):Promise<any> =>{
      var pos = new vscode.Position(10, 0);
      var endPos = new vscode.Position(12, 0);
      let range:vscode.Range = new vscode.Range(pos,endPos);
      vscode.window.showErrorMessage(event.message);
        return vscode.commands.executeCommand("vscode.executeInlayHintProvider",vscode.Uri.parse(event.ownerUri),range).then ( (temp1) =>{
          let ret = new Array();          
          let list = new Array();          
          let hintLabelPart = new vscode.InlayHintLabelPart(`hint1`);
          hintLabelPart.tooltip = "hint tooltip";
          list.push(hintLabelPart);
          let inlayHint = new vscode.InlayHint(new vscode.Position(1, 0), list, vscode.InlayHintKind.Parameter);
          let edit = new vscode.TextEdit(new vscode.Range(new vscode.Position(1, 1), new vscode.Position(5, 10)), "textTobeInserted");
          inlayHint.textEdits = new Array();
          inlayHint.textEdits.push(edit);
          return inlayHint;
        });
  }

**Comment by jrieken** [comment]
> On Execution of vscode.executeInlayHintProvider comamnd, hints are not getting added/shown in the document.

It's not meant to do that. These commands are to retrieve data but they aren't doing anything in the UI
