### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by bierenjiadehaizi** [Microsoft/vscode#19998]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:
安装扩展时提示 unable to verify the first certificate失败

**Comment by bpasero** [comment]
@bierenjiadehaizi this issue needs more information
