### ISSUE TITLE
Terminal Sticky Scroll: git pull wrong sticky node

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#199940]
_Starting from an empty terminal_

When using `git pull origin main`, the command is not set to be the sticky node but `main       -> origin/main` is

<img width="529" alt="image" src="https://github.com/microsoft/vscode/assets/44439583/742c60bd-817f-4e51-8214-9fd5d9cf15fc">

<img width="800" alt="image" src="https://github.com/microsoft/vscode/assets/44439583/692f43f5-ce1d-4276-a116-4fff7e92dfb4">

**Comment by Tyriar** [comment]
Can't repro unfortunately. I'll need trace `Terminal` logs to be able to diagnose without a reliable repro.
