### ISSUE TITLE
open the javascript file,have a bug about Typescript

### ISSUE THREAD

**Issue by tikeoewoew** [Microsoft/vscode#19995]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-npm-script|eg2|0.1.8|
|php-intellisense|felixfbecker|0.0.12|
|ftp-simple|humy2833|0.4.14|
|crane|HvyIndustries|0.2.2|
|launcher|ilich8086|0.0.4|
|docthis|joelday|0.3.10|
|vue|liuji-jim|0.1.5|
|ftp-sync|lukasz-wronski|0.3.2|
|PowerShell|ms-vscode|0.9.0|
|vscode-icons|robertohuertasm|7.1.2|

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@tikeoewoew this issue needs more details.
