### ISSUE TITLE
Cannot find runtime 'node' on PATH

### ISSUE THREAD

**Issue by TomKrcmar** [Microsoft/vscode#19996]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.6.2|
|vscode-icons|robertohuertasm|7.2.0|

---

**To reproduce:**
<hr />

- Use my computer to open VSCode
- Create a `console.log('Hello, World!');` JavaScript file
- Launch as node application from the VSCode Debugger view

Produces error: `Cannot find runtime 'node' on PATH`

**Given:**
<hr />

- My launch.json:

    {
    	"version": "0.2.0",
    	"configurations": [
    		{
    			"type": "node",
    			"request": "launch",
    			"name": "Build",
    			"program": "${workspaceRoot}/build.js",
    			"cwd": "${workspaceRoot}"
    		}
    	]
    }

- I have moved nodejs to within 2048 characters of my PATH variable.
- I have restarted my computer.
- I have restarted VSCode.
- `node -v` gives `v6.9.5`

*From both CMD and the Integrated Terminal (tried both sysnative/cmd and PowerShell):*

- `PATH` contains `D:/Program Files/nodejs`
- `where node` returns `D:/Program Files/nodejs/node.exe`

*From the Google Developer Console:*

- `process.env.PATH` contains `D:/Program Files/nodejs`
- Running the following code produces `D:/Program Files/nodejs/node.exe`:

    (function(){
        const cp = require('child_process');
        const env = Object.assign({}, process.env, {
            ATOM_SHELL_INTERNAL_RUN_AS_NODE: '1',
            ELECTRON_NO_ATTACH_CONSOLE: '1'
        });
        const result = cp.spawnSync('where', ['node'], {
            detached: true,
            stdio: ['ignore', 'pipe', process.stderr],
            env,
            encoding: 'utf8'
        });
        
        console.log(result.stdout);
    })();

**Additional (Maybe Related)**
<hr />

- Also .NET-Core applications behave identically - terminal and cmd works, `dotnet` is on the path, but Launch from VSCode debugger view fails to find CLI Tools on the path.

- Attaching to an existing `dotnet` process produces a different error:
`Please set up the launch configuration file for your application. command 'csharp.listProcess' not found`

**Update**

I've been doing some debugging, and it looks like the following code produces `Command Failed: echo test`:

    require('child_process')
    .execSync('echo test', {cwd: workspaceRoot, env: process.env});

Under the hood, it winds up calling

    require('child_process')
    .spawnSync('cmd', ['/s', '/c', '"echo test"'], {cwd: workspaceRoot, env: process.env});

The command it builds under the hood is `C:\Windows\System32\cmd.exe /s /c "echo test"` which I tested *outside* of VSCode, and does indeed print `test`.

Inside VSCode, the `spawnSync` call reveals that the exit code is `3221225477`.

In fact, every time I use `child_process` to execute something via cmd, the exit code is `3221225477`. I can get `spawnSync` to start other processes aside from cmd, though. This works:

    require('child_process')
    .spawnSync('node', ['build.js'], {cwd: workspaceRoot, env: process.env});

**Comment by isidorn** [comment]
This is coming from the node debugger thus forwarding to @weinand to do the initial investigation

**Comment by weinand** [comment]
@TomKrcmar as a workaround you could set `runtimeExecutable` to `D:/Program Files/nodejs/node.exe`. With this node debugging should work.

Could you please print the PATH environment variable from inside the node program and compare it to the PATH that you see in the integrated terminal. They should be identical.

**Comment by TomKrcmar** [comment]
Correct, they are identical.

**Comment by weinand** [comment]
Please try this in VS Code 1.11.0. We've fixed something in this area.
