### ISSUE TITLE
Search results tree-granularity

### ISSUE THREAD

**Issue by easyTree** [microsoft/vscode#199905]
Search results currently have the option to show as a tree:
 * file > result

 I suggest adding an additional level between file and result (probably toggle-able):
 * file > function > result

This will greatly aid familiarising oneself with a new codebase as well as being generally useful.

&lt;/suggestion&gt;

**Comment by andreamah** [comment]
As mentioned above, we perform plain-text match, so considering syntax is currently out of scope. This is generally because of the performance overhead and also the extra team effort needed to build and maintain this.
