### ISSUE TITLE
Tab key changes focus instead of adding tab to document.

### ISSUE THREAD

**Issue by andriesfc** [microsoft/vscode#199932]
Type: <b>Bug</b>

Nowhere is the tab key set to change focus, but it still steals focus. This did not happen with the previous versions.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin x64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv|--crash-reporter-id 103514a8-2c7a-4748-bf43-d9aac5de66ae|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
jsoncrack-vscode|Ayk|2.0.2
vscode-log-viewer|ber|0.14.1
vscode-jq-playground|dav|4.3.5
quicktype-refresh|dog|1.0.2
alt-catppuccin-vsc|doo|2.7.4
gitlens|eam|14.5.2
markdown-table-formatter|fcr|3.0.0
kotlin|fwc|0.2.32
vscode-jmespath|jos|0.0.6
jq-syntax-highlighting|jq-|0.0.2
vscode-docker|ms-|1.28.0
remote-containers|ms-|0.321.0
vscode-json-editor|nic|0.3.0
java|red|1.26.2023120108
dothttp-code|shi|1.0.10
jsonpathhighlighter|Shi|0.1.0
markdowntable|Tak|0.11.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.13.2023112207
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.2023120100
vscode-java-pack|vsc|0.25.2023110908
vscode-java-test|vsc|0.40.2023101002
vscode-maven|vsc|0.43.0
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by gjsjohnmurray** [comment]
Do you see this in your Status Bar?

![image](https://github.com/microsoft/vscode/assets/6726799/6f560889-c72e-40f0-affc-629c7b9a1529)

If so, you probably inadvertently entered the keyboard shortcut for the `Toggle Tab Key Moves Focus` command.

You can turn this mode off by clicking on that indicator.

**Comment by andriesfc** [comment]
I have tried. It does not work, (the indicator on the bottom bar disappears, but that is it). I've gone so far as to delete the whole installation, and it still does not work. Is there some super uber secret place vscode stores settings on my mac?

**Comment by andriesfc** [comment]
I Eventually just gave up to understand what the heck happened. And fixed it windows way: Delete the whole installation. Found a script online which forcefully remove all traces of the app, and re-installed it. It worked 😃 !
Thanx for everybody who tried to help.
