### ISSUE TITLE
BUG - Devtools rendering error when stick to main window

### ISSUE THREAD

**Issue by Ryanjiang2009** [microsoft/vscode#199941]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 
- 版本: 1.85.0-insider (system setup)
提交: 94a3d7bac770b43ce97e9685715bef1a60d1a759
日期: 2023-12-01T19:00:37.339Z
Electron: 25.9.6
ElectronBuildId: 25531495
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. click help - toggle devtools
2. change devtools to stick on the right side of window
3. the main exit button overlaps with the devtools toolbar
![image](https://github.com/microsoft/vscode/assets/67903708/f6c55cc9-baf7-4fa6-bd03-3af25fe99969)

**Comment by deepak1556** [comment]
Closing as wontfix, please refer to the above linked issue for details.
