### ISSUE TITLE
Powershell integrated terminal stopped working on macOS after upgrading to 1.9.0

### ISSUE THREAD

**Issue by giordyb** [Microsoft/vscode#19990]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.7.3|
|vscode-docker|PeterJausovec|0.0.11|
|code-settings-sync|Shan|2.4.3|
|vscode-css-formatter|aeschli|0.0.2|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.8|
|vscode-npm-script|eg2|0.1.8|
|LogFileHighlighter|emilast|1.0.1|
|vscode-npm|fknop|3.3.0|
|rest-client|humao|0.12.1|
|reg|ionutvmi|0.0.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|ftp-sync|lukasz-wronski|0.3.2|
|mssql|ms-mssql|0.2.1|
|PowerShell|ms-vscode|0.9.0|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.5.2|
|vscode-icons|robertohuertasm|7.1.2|
|JavaScriptSnippets|xabikos|1.4.0|

---
After upgrading to 1.9.0, when using powershell as the integrated terminal every character type is followed by a number of  "^Q", making it unusable. I also tried to set the terminal back to bash and it works, but when I start a powershell session the same problem occurs.

Steps to Reproduce:

1. run powershell as integrate terminal
2. type anything

![test](https://cloud.githubusercontent.com/assets/13320961/22630251/c7a0126a-ebf6-11e6-85a8-28368ddc0b31.gif)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19766
