### ISSUE TITLE
Allow for custom icons for non-file based editors (extensions, keybindings, search, settings)

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#199965]
Nice easy polish change to switch to the 4 square icon here:

![image](https://github.com/microsoft/vscode/assets/2193314/526e96e1-04bf-4c69-af4e-c4da2ee0b0ea)

![image](https://github.com/microsoft/vscode/assets/2193314/73c0cb9e-6b77-4584-9c54-353a963b0899)

**Comment by Tyriar** [comment]
Makes sense for other editors: keybindings, search, settings

**Comment by Tyriar** [comment]
I was hoping to do this myself and looked into it, but there's no clear way other than CSS with `!important` which is a hack to assign an icon for. I'm also a little worried I'll cause regressions with how this interacts with icon themes which I have minimal knowledge on, so assigning to respective owners.

For reference the terminal does it by generating CSS in JS and injecting it such that the codicon chars (which could theoretically change) are not hard coded in CSS:

https://github.com/microsoft/vscode/blob/97082b0ca528e64fb1be0adcda9b1876fb223d05/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L1246-L1252

**Comment by bpasero** [comment]
It seems that @mjbvz started the work on allowing Codicon in tab labels via https://github.com/microsoft/vscode/pull/92122 to enable https://github.com/microsoft/vscode/issues/90616. That PR had ongoing discussions and is still draft, but maybe some of the changes can be taken for consideration.

**Comment by benibenj** [comment]
Verification steps:
1. open following editors: Settings editor, Keyboard shortcut editor, multi diff editor and an extension view (the view with the info about an extension) in the editor 
2. you should be seeing a different icon (non default) for each editor in the tab bar, open editors view and quick pick
