### ISSUE TITLE
Generated tasks.json for TypeScript watch mode contains deprecated isWatching field

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#19991]
VS Code 1.9, Windows 10

Generated tasks.json contains deprecated field `isWatching`, should be `isBackground`.

![image](https://cloud.githubusercontent.com/assets/101152/22630875/fd8ceda2-ec01-11e6-970f-23384562bb35.png)

**Comment by dbaeumer** [comment]
Good catch.
