### ISSUE TITLE
Regression in search performance in 1.9.0

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#19993]
- VSCode Version: 1.9.0
- OS Version:  OSX 10.11.6

Steps to Reproduce:

1.  Searching large project in 1.8.1 for a particular term takes 2 seconds
2. Searching the same project for the same term in 1.9.0 takes 6 seconds

**Comment by roblourens** [comment]
Huh, I can't imagine what would have been responsible for this in 1.9. Do you have a lot of UTF-16 files or anything like that?

**Comment by dakaraphi** [comment]
All files are UTF-8 as far as I know.
So I tried another test using a new Angular2 project installed by npm.
I disabled the node_models exclusion so it would search everything.

- search for term 'million' v1.8.1 = 1.5 secs.
- search for term 'million' v1.9.0 = 3 secs.

So, I'm not just seeing this with my specific project only.  Was able to reproduce with a new Angular2 project.
Also, I tried running with all extensions disabled.  I still get the same results.

**Comment by dakaraphi** [comment]
I tried this again on my Windows 10 machine.  Another project, the Brackets editor source including node_modules.

- search term 'million' v1.8.1 = 1.2 secs
- search term 'million' v1.9.0 = 2.8 secs

**Comment by roblourens** [comment]
I think I actually can repro this, not at a 2x slowdown, but a little slower. There are a couple things that could possibly have regressed this.

**Comment by roblourens** [comment]
I think this is from https://github.com/Microsoft/vscode/commit/b4bbb5655d83df8939a118d8295307aba85e97ea#diff-8d34cbc5c6e742345fd2dc2dccf9c167 - it's a lot faster when I revert this, just because it adds extra function calls in very perf-sensitive code. It's going to be annoying to inline all that... Hopefully we can just switch to silver searcher or ripgrep this month anyway.

**Comment by dakaraphi** [comment]
I wonder if the JIT can't inline those functions because of the partial application of peekLF and peekCR.  It might be worth trying to just call direct functions to see if the JIT will inline.

**Comment by roblourens** [comment]
This will be in tomorrow's Insider build. Would appreciate it if you try it out and let me know!

**Comment by dakaraphi** [comment]
@roblourens Current timings for my project wide search.
VSCode Insiders = **2.9**
VSCode 1.9.1 = 7.7
VSCode 1.8.1 = **2.9**

Awesome! looks like that fully restored the performance.  Thanks!
Just curious, any idea why V8 wouldn't inline the functions?

**Comment by roblourens** [comment]
Perfect! I really don't know. There are a lot of nested functions in closures, and I think that impacts what optimizations it can do. I might be able to push it further by simplifying that file further.
