### ISSUE TITLE
Iteration Plan for December 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#199907]
This plan captures our housekeeping work in **December**. We will **not** ship a December release. Our next release will be the January release, that we will ship in **early February**. We will have a separate January plan.

You'll see a large number of GitHub issue notifications over the course of this iteration.

If you are interested in why we have issue housekeeping iterations and in our general philosophy around issue management, then we have this [write-up](https://github.com/microsoft/vscode/wiki/Issue-Grooming) for you. As part of housekeeping we will also fix bugs and implement minor improvements as we see fit.

## Endgame
There is **no** endgame in December as the next release will only be shipped in early February.

## End-of-year Schedule
The last Insiders build of 2023 will ship on December 20nd. We will suspend our builds until January 3nd. You will see delayed or no responses from us on issues and PRs across all of our repositories.

## Plan Items
Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

</details>

### Housekeeping
- [x] Issue/PR Grooming - review, categorization, assignment [vscode#199906](https://github.com/microsoft/vscode/issues/199906) **team**

-----
### Deferred Items
- All work that was in-flight end of November. We'll resume work in early January.

**Comment by lygstate** [comment]
any chance to getting https://github.com/microsoft/vscode/pull/177434 merged?

**Comment by linkmiau** [comment]
xd
