### ISSUE TITLE
Color picker is bugged, adding additional ) when choosing color

### ISSUE THREAD

**Issue by KostaD02** [microsoft/vscode#199900]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 
1.84.2
- OS Version: 
Windows_NT x64 10.0.19045
Steps to Reproduce:

1.  Create any css file (or any file where you could open built in color picker)
2.  Write simple css similar to this:
```css
* {
   color: red;
}
```
3. When red box appear (color picker), choose any color desired color

Actual bug:
In some cases it does append additional `)` which is unnecessary.

**Comment by aiday-mar** [comment]
Hi I am currently trying to reproduce this error and am not able to. If you find a more concrete example of this error, could you post here a screen recording and the exact example that caused the error?

**Comment by KostaD02** [comment]
https://github.com/microsoft/vscode/assets/68782786/6c529ffb-ae00-4b66-ac25-166ee1dafa7a

Now new bug appeared, not only ) is adding itself even numbers.

**Comment by r3m0t** [comment]
Can you share the values of your Auto Save-related settings? Can you try again after the command "Developer: Reload With Extensions Disabled"?

**Comment by KostaD02** [comment]
> Can you share the values of your Auto Save-related settings? Can you try again after the command "Developer: Reload With Extensions Disabled"? Also, the values of these settings: "Format on Save", "Code Actions On Save"

https://github.com/microsoft/vscode/assets/68782786/e01fcef7-5846-43e5-b5fb-0299081c1eae

Issue is still happening
