### ISSUE TITLE
SCM: When multiple `scm/inputBox` been registered, the button shifted

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode#199921]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: `1.85.0-insider (user setup)`
- OS Version: `Windows_NT x64 10.0.19045`

Steps to Reproduce:

1. Here is the only one `scm/inputBox` registered. It's okay.

    ![image](https://github.com/microsoft/vscode/assets/88981/df302358-9b35-449b-9d18-b114d881b2a2)

2. Here is two extensions registered the same `scm/inputBox`.

    ![image](https://github.com/microsoft/vscode/assets/88981/07616860-b446-49e7-ba5d-f4c08e971927)

    ![image](https://github.com/microsoft/vscode/assets/88981/f7146419-f11c-4a25-8506-4afd9bcd03ad)

**Comment by lszomoru** [comment]
This issue is fixed in the latest VS Code Insiders release.

**Comment by TylerLeonhardt** [comment]
@doggy8088 can you confirm that this is fixed, please?
