### ISSUE TITLE
The color and clarity (pixels) of image resources, videos, text and other content are seriously distorted. . .

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#199928]
# The color and clarity (pixels) of image resources, videos, text and other content are seriously distorted. . .

## System environment:
Windows10 x64 19044
Chrome
Version 119.0.6045.200 (Official Build) (64-bit)
VSCode 1.85

## To reproduce the example:

1. Open the same picture and the same video in Chrome and VSCode 1.85 respectively. However, it is surprising to find that the color and clarity (pixels) of image resources, videos, text and other content rendered by VSCode 1.85 are seriously distorted. . . The original image, video quality and colors look very distorted and terrible. . . Don't know what causes this?

## Video 1 is rendered in the Chrome browser
![Chrome视频颜色](https://github.com/microsoft/vscode/assets/54253524/b049241d-152a-42ce-a7be-a6307e14a550)
## Image 1 was rendered in the Chrome browser
![Chrome视频颜色2](https://github.com/microsoft/vscode/assets/54253524/ee3a1075-f500-4d8e-aa3d-9089ba64e148)

---

## Video 2 is rendered in VSCode 1.85 Markdown
![VSCode视频颜色](https://github.com/microsoft/vscode/assets/54253524/be5ec59a-4dc8-4824-b789-5b5cb37ff39e)
## Image 2 was rendered in VSCode 1.85 Markdown
![VSCode视频颜色2](https://github.com/microsoft/vscode/assets/54253524/46987e28-95e6-4fd3-b031-a0695b3d6e69)

You should be able to clearly see that the image quality, video quality and color rendered in VSCode 1.85 Markdown are very distorted. . . It is really difficult to understand that such color differences and color distortions will occur when using the same video, image, text and other content on the same computer. . .

Hopefully the VSCode team will fix and improve it in the next version. Thank you so much!

**Comment by zhouxinghong** [comment]
When images and videos are opened from the resource manager, the opened images and videos also have the above-mentioned color distortion and color difference problems. . .

**Comment by zhouxinghong** [comment]
Compare videos and images respectively:
**Video 1 is rendered in the Chrome browser**
![](https://private-user-images.githubusercontent.com/54253524/287631297-b049241d-152a-42ce-a7be-a6307e14a550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDE5NzEsIm5iZiI6MTcwMjAwMTY3MSwicGF0aCI6Ii81NDI1MzUyNC8yODc2MzEyOTctYjA0OTI0MWQtMTUyYS00MmNlLWE3YmUtYTYzMDdlMTRhNTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAyMTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZTU3YjkzMDQxNDNjNjg3N2YzNjc2ZDU3ZDZlNDljZWU0MWQyZmU2ZmYwYTFiNjJkMTMwMDExZDZiMDk5NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j2fCwBEdyzV7nRR8W36pv4V4faAilNU1YyKk_JreSn0)
**Video 2 is rendered in VSCode 1.85 Markdown**
![](https://private-user-images.githubusercontent.com/54253524/287631563-be5ec59a-4dc8-4824-b789-5b5cb37ff39e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDE5NzEsIm5iZiI6MTcwMjAwMTY3MSwicGF0aCI6Ii81NDI1MzUyNC8yODc2MzE1NjMtYmU1ZWM1OWEtNGRjOC00ODI0LWI3ODktNWI1Y2IzN2ZmMzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAyMTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMjcwMjc4ZTU0YWUxYTNiNDkxOTliZTBhOWE3NGFhNjY5YWY0M2UyNGUxNTJjODk5Njc4NThjZDBlNzc0M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.snuTESGxEPBfpN8OjXJEQt5e6lX28c-OLspGHOEqPaA)
**Image 1 was rendered in the Chrome browser**
![](https://private-user-images.githubusercontent.com/54253524/287631448-ee3a1075-f500-4d8e-aa3d-9089ba64e148.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDE5NzEsIm5iZiI6MTcwMjAwMTY3MSwicGF0aCI6Ii81NDI1MzUyNC8yODc2MzE0NDgtZWUzYTEwNzUtZjUwMC00ZDhlLWFhM2QtOTA4OWJhNjRlMTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAyMTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMDVhMjZlYWZjN2M2Yzk1MTI2YzE0ODU0MjhhMDM5ZDI3MmQxYzVkZTA4NzU1MTI4N2VlNzMzMzQxMWExODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.knHKdxgwv-5bRgmiYWIy4u37ykgHBoaH27Dw9UNExYQ)
**Image 2 was rendered in VSCode 1.85 Markdown**
![](https://private-user-images.githubusercontent.com/54253524/287631734-46987e28-95e6-4fd3-b031-a0695b3d6e69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDE5NzEsIm5iZiI6MTcwMjAwMTY3MSwicGF0aCI6Ii81NDI1MzUyNC8yODc2MzE3MzQtNDY5ODdlMjgtOTVlNi00ZmQzLWIwMzEtYTA2OTViM2Q2ZTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAyMTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZmY2ZTYwMzU1NzIxNWJkNDhkMjNmMjM2N2ExZjhjM2ZlNTcxNzcyOGJiNTQ2YmQ2MmRlZjhhZTUyN2I3YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B40yWgqSJngg7-PcyJB_PyQMEJgjO3_RhRRmDjuMcCk)

**Comment by zhouxinghong** [comment]
When images and videos are opened from the resource manager, the opened images and videos also have the above-mentioned color distortion and color difference problems. . .

**Comment by deepak1556** [comment]
VSCode does not control the rendering of images and video, the support comes from the chromium runtime. If issue does not appear in Chrome then very likely issue is addressed in newer runtime versions. Closing as not actionable.
