### ISSUE TITLE
aria-live updates related to the accessible view overlap with the announcement of the focused control when navigating the VS Code UI with NVDA

### ISSUE THREAD

**Issue by rperez030** [microsoft/vscode#199959]
Type: <b>Bug</b>

When navigating the UI using the keyboard, NVDA reads the announcement related to the accessible view before the controls that receives focus. I'm finding this to be quite a bad experience, and potentially a big issue for more beginner users of the editor. An easy way to reproduce the problem is by pressing F6 from the editor to focus the status bar and use the arrow keys to move between elements. The issue only seems to affect NVDA at the moment. It may be good to give some time to fire these updates after the control receives focus, especially if the user is navigating quickly through nearby controls like in the status bar. In fact, I wonder what is the benefit of showing just the name of controls and potentially some descriptive text in the accessible view.

@isidorn @meganrogge 

VS Code version: Code - Insiders 1.85.0-insider (94a3d7bac770b43ce97e9685715bef1a60d1a759, 2023-12-01T19:00:32.802Z)
OS version: Windows_NT arm64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple Silicon (6 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.99GB (9.79GB free)|
|Process Argv|--crash-reporter-id 286be978-64ae-4658-8bf9-a3235a9d2cd2|
|Screen Reader|yes|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
a247i228:30880122
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialogc:30812479
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30901775
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by meganrogge** [comment]
Thanks for the report. It shouldn't be reading info about the accessible view in this case.

**Comment by meganrogge** [comment]
@rperez030 last iteration, for keyboard only users, we added support for showing the tooltip on keyboard focus of status bar items. I had only tested this with a screen reader on macOS. I'll be curious to see why this is causing an issue on windows.

**Comment by rperez030** [comment]
I'm debugging with NVDA. Each time an element in the status bar gains focus, NVDA reports a liveRegionChange associated with the announcement "Inspect this in the accessible view with Alt+F2". If I press alt +F2, the name of that control appears in the accessible view.The live region update is taking precedence over the focus changed event.

**Comment by meganrogge** [comment]
To verify, on windows, enable NVDA. Focus the status bar / activity bar. Use arrow keys. Verify that there's no message about opening the accessible view. Focus a hover in the editor using only the keyboard. Verify that you do hear a message about opening the accessible view.

**Comment by meganrogge** [comment]
Verified by @rperez030

**Comment by meganrogge** [comment]
This was verified in insider's by @rperez030. Will leave it without the label to also verify in the stable build.
