### ISSUE TITLE
find widget should show x of y find results

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#1999]
Find in Chrome shows "x of y" results that help you understand how far through the document you are:

![image](https://cloud.githubusercontent.com/assets/1487073/12315818/4c22181c-ba34-11e5-8f54-4f937540afb9.png)

**Comment by alexandrudima** [comment]
@chrisdias I already felt bad in taking 30px from the search input to add the matches count. Perhaps we can do it if we make the widget more wide?

![image](https://cloud.githubusercontent.com/assets/5047891/12320325/4f5eb796-baa8-11e5-8d73-d81fa2b96a4a.png)

@bgashler1 @stevencl what do you think?

**Comment by alexandrudima** [comment]
@chrisdias @bgashler1 @stevencl Let's discuss this in #1476 , as that was there before
