### ISSUE TITLE
Allow unfolding at a specific level with hotkey

### ISSUE THREAD

**Issue by makingglitches** [microsoft/vscode#199904]
I would like to be able to unfold an entire level of json or code with a keystroke.

Example:

I have a json object that is extension and has many subfeatures.

Lets say I fold the whole json structure with ctrl+k ctrl+0

Resulting in the following, after I unfold the top level:

![Screenshot from 2023-12-03 16-10-37](https://github.com/microsoft/vscode/assets/53788764/7a202da4-14a4-4b2d-9031-80f6b9a1380d)

I would like to be able to press a key to unfold successive levels, so if I press a key chord including ctrl+1,  I would like to see the next top level object unfolded producing something like the following:

![Screenshot from 2023-12-03 16-12-24](https://github.com/microsoft/vscode/assets/53788764/d47ff303-4418-4106-9bb3-253566c88509)

As it is the current keystrokes I can find info on only unfold a region you have selected, I just want to be able to drop down the whole file the way you can fold everything.

**Comment by makingglitches** [comment]
Course you could always hire me and I'd learn how to do it. I'm not big on node js but I have used it.

**Comment by aeschli** [comment]
I think you can 'unfold all' (Ctrl + K CtrL + J), followed by 'fold level 2' (Ctrl + K Ctrl + 2).
Then it's 'unfold all' (Ctrl + K CtrL + J), followed by 'fold level 3' (Ctrl + K Ctrl + 2).

You can create a shortcut for that:
```
  {
    "key": "h",
    "command": "runCommands",
    "args": {
      "commands": [
        "editor.unfoldAll",
        "editor.foldLevel2"
      ]
    }
  }
```
