### ISSUE TITLE
Stepping through Jupyter Notebook Diffs does not respect Metadata / Output view settings

### ISSUE THREAD

**Issue by simonbohnen** [microsoft/vscode#199958]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: macOS 14.1.1

Steps to Reproduce:

1. Create a Jupyter Notebook and modify it such that a cell has a diff in the output or metadata, but not in the code.
2. Disable 'Show Metadata Changes' and 'Show Output Changes'.
3. Step through the changes with the arrows in the top right of the diff viewer.

Cycling through the changes will include the changes to the metadata / output, although the checkmarks for showing these changes are unset.

This can be fixed by modifying [this file](https://github.com/microsoft/vscode/blob/d5fe76749aeaa4df109911668ef5e87e3b262c02/src/vs/workbench/contrib/notebook/browser/diff/notebookDiffActions.ts).

**Comment by DonJayamanne** [comment]
This should now be fixed with the latest changes.
