### ISSUE TITLE
Warn: The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by michal-husak** [Microsoft/vscode#20009]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. I just open a .js file
2. then the error is appearing every 3 seconds, I am not using any TypeScript

**Comment by bpasero** [comment]
@michal-husak are you working against a network share?

**Comment by michal-husak** [comment]
Hi @bpasero,
I am not exactly sure what you mean by "network share" but my files are located on SharePoint (not on my HDD). After I restarted the VSC the error stopped appearing. This happens usually when I start VSC for the first time after Windows starts.

**Comment by bpasero** [comment]
@michal-husak yeah, this seems to be sharepoint related all in all. We received many duplicates.

**Comment by mjbvz** [comment]
Thanks. This does look like a duplicate of https://github.com/Microsoft/TypeScript/issues/13874

We're trying to coordinate a fix with the TypeScript team. Closing as upsteam
