### ISSUE TITLE
Is there support remove spaces after opening and before closing curly braces?

### ISSUE THREAD

**Issue by leaves4j** [Microsoft/vscode#20004]
- VSCode Version: 1.9.0
- OS Version: macOS 10.12.2 

Steps to Reproduce:

1. code
```js
const a = {a: 'b'};
```
2. then format it
```js
const a = { a: 'b' };
```
VSCode insert spaces after opening and before closing curly braces in javascript, Is there support remove those spaces?

**Comment by bpasero** [comment]
Questions are best being asked here: http://stackoverflow.com/questions/tagged/vscode
