### ISSUE TITLE
Merge Editor doesn't launch

### ISSUE THREAD

**Issue by akijankaPRMW** [microsoft/vscode#200053]
Type: <b>Bug</b>

when on your branch you'll have merge conflicts after running command "git merge main": 
- click on 'open file' on the change that has a merge conflict
-click on 'resolve in merge editor'
-three-way merge editor doesn't launch

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (16.11GB free)|
|Process Argv|--crash-reporter-id 04d94e28-7a40-4357-9c49-fa49e2fe125a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.2
gitlens|eam|14.5.2
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|59.7.0
salesforcedx-vscode-apex|sal|59.7.0
salesforcedx-vscode-apex-debugger|sal|59.7.0
salesforcedx-vscode-apex-replay-debugger|sal|59.7.0
salesforcedx-vscode-core|sal|59.7.0
salesforcedx-vscode-lightning|sal|59.7.0
salesforcedx-vscode-lwc|sal|59.7.0
salesforcedx-vscode-soql|sal|59.7.0
salesforcedx-vscode-visualforce|sal|59.7.0
sfdx-package-xml-generator|Vig|2.0.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by hediet** [comment]
Can you please share a screenrecording and the dev console logs? Thanks!

**Comment by akijankaPRMW** [comment]
It magically repaired itself
