### ISSUE TITLE
Auto report

### ISSUE THREAD

**Issue by EthanOrange** [Microsoft/vscode#20007]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.5|
|jquerysnippets|donjayamanne|0.0.1|
|vue-snippets|hollowtree|0.1.0|
|docthis|joelday|0.3.10|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|ejs-language-support|QassimFarid|0.0.1|
|vue|seanwash|0.4.2|

---

Steps to Reproduce:

1.
2.

**Comment by mrmlnc** [comment]
Please, provide more detailed description 👍
