### ISSUE TITLE
With an unsaved file exists, the blue color at the edge of the current tab disappears when the tab is moved.

### ISSUE THREAD

**Issue by StaringInfinity** [microsoft/vscode#200054]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.2
- OS Version: win10

Steps to Reproduce:

1.  Theme: Dark Modern

2. Open two cpp files in the workspace, move the tabs upwards and downwards respectively.

https://github.com/microsoft/vscode/assets/49320365/54b91e29-6f0d-4b23-9279-b3b93014ea92

3. Ctrl+N, Open a new Tab, and copy some content into it.
    Move the tabs upwards and downwards respectively.
    When I move tabs downwards,  the edge color disappears.

https://github.com/microsoft/vscode/assets/49320365/aed397c3-924f-430f-bc10-bf0d55f3216b

4.  Another sample

https://github.com/microsoft/vscode/assets/49320365/c38848ab-c50b-4ace-90d4-a0da4229dd31

This issue can be reproduced in vscode-insider

**Comment by benibenj** [comment]
I'm not able to reproduce this. Can you check if you see an error in the dev console? Run the `workbench.action.toggleDevTools` command and check the console for errors.

**Comment by StaringInfinity** [comment]
https://github.com/microsoft/vscode/assets/49320365/a6fcad04-8f64-4b2a-bf1d-96d68fa1b2da


You can try with a larger cpp file, simply copy code to many lines. Drag the tab down to change the tab's position

**Comment by StaringInfinity** [comment]
It seems the tab scrolls down, so the color bar is blocked

https://github.com/microsoft/vscode/assets/49320365/79e05e79-54a2-4b21-b2e8-cd1a1aed3f85

**Comment by benibenj** [comment]
I was able to reproduce it now. The reason I was not seeing it was because it only appears at specific zoom levels. Looking into it...

**Comment by benibenj** [comment]
Thanks for the help @StaringInfinity, we were able to fix it

**Comment by StaringInfinity** [comment]
This problem seems to still exist in the latest vscode-insider. ("window.zoomLevel" : 0 )

1.86.0-insider
37fe2d06d65db4b50303c5f5e8ca589a50f2287a
x64

With untitled tabs, the tab can be scrolled down and up,

https://github.com/microsoft/vscode/assets/49320365/5c9e99c5-045b-44fc-8f4e-8bfaed17e3c3

Besides, It seems that the .json file is an exception

https://github.com/microsoft/vscode/assets/49320365/01e2a5d4-bf96-4063-b05d-c105f7f1b987
