### ISSUE TITLE
how to support object rest spread

### ISSUE THREAD

**Issue by zzzgit** [Microsoft/vscode#20006]
- VSCode Version: the latest
- OS Version: win10

```javascript
{
  a: 3,
  b: 4,
  ...{c: 5}
}
```

it is call [object rest spreading](https://babeljs.io/docs/plugins/transform-object-rest-spread/).
how could i make vscode to support this syntax?

**Comment by bpasero** [comment]
Please direct questions here: http://stackoverflow.com/questions/tagged/vscode
