### ISSUE TITLE
SCM "Incoming/Outgoing" label doesn't reflect settings

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#200046]
I have incoming changes disabled in SCM. When I have outgoing changes, the label still says "Incoming/Outgoing", which is a little confusing.

![image](https://github.com/microsoft/vscode/assets/38270282/57eb3a3a-0077-4f79-b824-692ca84c19c8)

**Comment by susiwen8** [comment]
Looks like an easy issue, can I take this one?

**Comment by alexr00** [comment]
This looks much cleaner now, thank you!
