### ISSUE TITLE
Github copilot extension does not automatically reconnect to the internet

### ISSUE THREAD

**Issue by brayo-pip** [microsoft/vscode#200024]
Whenever the github copilot extension loses an internet connection I have to restart VS code to get it to reconnect. I wish for the  github copilot extension to automatically reconnect. I guess this the only place I could request the feature since copilot doesn't have a repo.

**Comment by ulugbekna** [comment]
Please, report it [here](https://github.com/orgs/community/discussions) if not already reported by someone else. Thank you!
