### ISSUE TITLE
Debug Console does not scroll when text selection reaches top of view

### ISSUE THREAD

**Issue by award999** [microsoft/vscode#200048]
Does this issue occur when all extensions are disabled?: n/a, need some debug extension to reproduce

- VS Code Version: 1.84.0
- OS Version: macOS 13.5

Steps to Reproduce:
1. Launch any type of debug session (reproduced with python and c debugging)
2. Make sure the source has a bunch of print statements to make sure the Debug Console has a scroll bar
3. Try to select text towards the top of the debug console
4. I would expect that when I reach the top that the console scrolls up and continues to select, but it does not scroll, stops selecting, and as your cursor moves into the editor you can actually select editor text or cause the editor to scroll depending on your movement. I do see the "Copy All" context menu option for the debug console but in cases that the debugee is producing a lot of text, you probably want to be able to select just a small range
<img width="670" alt="Screenshot 2023-12-05 at 9 24 46 AM" src="https://github.com/microsoft/vscode/assets/78549403/005a1aca-cbf2-403c-83be-6a10d8c8b54f">

**Comment by roblourens** [comment]
I will roll this into https://github.com/microsoft/vscode/issues/186561
