### ISSUE TITLE
Not able to Debug the code

### ISSUE THREAD

**Issue by D-Dharani** [microsoft/vscode#200057]
In Vscode not able to start debugging the code , code is building but when giving dotnet run command or start debugging/F5 debugger is not starting it shows activating extensions and stop there are no debugger points appearing. No errors are popping up.

This performance issue is from last week ,previously i am able to debug code with no issues.

tried re-installing didnt work.Confirmed launch.json  also it is correct.

**Comment by D-Dharani** [comment]
Hi @roblourens  , can i have update on this , i am not able to debug my code

**Comment by roblourens** [comment]
Please file this on the C# extension
