### ISSUE TITLE
Make globally file and content search more intuitive

### ISSUE THREAD

**Issue by Tsimopak** [microsoft/vscode#200095]
I would suggest an option to refactor the globally file/content search to look more like the one in jetbrains:

![image](https://github.com/microsoft/vscode/assets/70956665/87e3b5c0-338b-4390-bd90-d8670c916832)

As you can see, a new pop up is raised when searching, and you can see in a list wise all the results and a preview beneath it, I think that it's more intuitive in terms of UX file and the preview are close to each other and also the file name is marked better.

I wish to be able to switch to such UI, as an optional choice.

**Comment by Tsimopak** [comment]
Hi @andreamah thanks for your fast response.
I am familiar with that UI window, but it seems less intuitive, it just look like a tests results inside a textarea element, which is not rich in UI elements, but just a text.

If you would watch again the image I just sent, you could see that instead of a full page, only a pop up of the search field is raised up and it composed of two main sections: the search field in which you see a preview of 1 liner of the search result and besides that the file and below u can see a preview of the full file content and it's also a scrollable window.

I am using intensively both VSCode products and Jetbrains and I think that this approach is better I really hope you could discuss internally about that and see if it has some advantages.

There's an option in that popup to stick the results to one of the panes, in that sense, it looks really close to the default and only search window in VSCode.

**Comment by andreamah** [comment]
https://code.visualstudio.com/updates/v1_82#_quick-access-text-search Does something like this look a bit closer to what you want to see? We have an issue here to track the ability to see context in files live https://github.com/microsoft/vscode/issues/191259

**Comment by andreamah** [comment]
When this https://github.com/microsoft/vscode/issues/191259 issue is implemented, you should be able to see the context (sort of like like what you see when you `ctrl`+`shift`+`o` on a file with symbols that you can navigate).

**Comment by Tsimopak** [comment]
@andreamah Looking forward for that feature to be implemented! :D thank you for your answer.
But as far as I understand, this new context window wouldn't include a mini preview of that file, right? instead, every search result selection would navigate to that file on that specific place, wouldn't it be better to have the ability now to move to the entire file but instead see a snapshot in a small window? in that way you wouldn't lose track of your current file

**Comment by Tsimopak** [comment]
Closing this issue, as it related to #203885
