### ISSUE TITLE
Debug toolbar not offset in aux windows

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#200005]
Seems to be very much to the top of the window:

<img width="912" alt="image" src="https://github.com/microsoft/vscode/assets/900690/ee927e77-eb97-485f-9ef0-f5a8404db3cf">

Are we missing some offset here that we only apply in the main window?

**Comment by sandy081** [comment]
Reopened the issue as it broke moving debug toolbar onto titlebar.

**Comment by connor4312** [comment]
So the ability to move the toolbar into the title bar is intended -- do you think we should have it default to being below the titlebar in new windows rather than being at y=0?

**Comment by sandy081** [comment]
do you think we should have it default to being below the titlebar in new windows rather than being at y=0?

Yeah, agreed. Is not how it is right now?

**Comment by connor4312** [comment]
Right now it defaulted to y=0 if unspecified, so I changed that to instead default to the main container's top.

**Comment by bpasero** [comment]
Getting the debug toolbar to appear in the floating window is a hit or miss for me, in most cases it will open in the main window. Did something break?

![image](https://github.com/microsoft/vscode/assets/900690/97f54cba-da33-4c2a-81cd-669f0b69236b)

**Comment by connor4312** [comment]
I'm having some trouble repro'ing this, are there specific steps you take that get you into this state?

**Comment by bpasero** [comment]
Strange, here it come I cannot reproduce what I saw...
