### ISSUE TITLE
File Explorer Loses Ability to Open Folder

### ISSUE THREAD

**Issue by tmarquard1** [microsoft/vscode#200071]
Type: <b>Bug</b>

After opening a directory in the Explorer, and then hitting refresh the folder will lose the ">" and is clickable, but doesn't open the folder contents. It seems to be also related to any files open in the given folders. 

It seems more reproducable if you open a folder, close it, and then refresh the explorer. 

VS Code version: Code - Insiders 1.85.0-insider (Universal) (92772dcc29bd74108ab61ba9da5ad1f5154639ff, 2023-11-30T18:38:36.579Z)
OS version: Darwin arm64 23.1.0
Modes:
Connection to 'ssh-remote+tmarquarddev' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|64.00GB (26.40GB free)|
|Process Argv|--crash-reporter-id ba1dc637-3612-4921-abc8-17de76bb5ce2|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+tmarquarddev' could not be established
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
gitlens|eam|2023.12.504
prettier-vscode|esb|10.1.0
copilot|Git|1.140.583
copilot-chat|Git|0.12.2023120501
vscode-docker|ms-|1.28.0
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.321.0
remote-ssh|ms-|0.108.2023112915
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.5.2023110609

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
2i9eh265:30646982
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialogc:30812479
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30901777
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by lramos15** [comment]
You're on a very old VS Code insiders. Please update, this has been fixed
