### ISSUE TITLE
The function of displaying all opened files in the tab bar without scroll bar

### ISSUE THREAD

**Issue by hbwqing1017** [microsoft/vscode#200035]
![1701780835719](https://github.com/microsoft/vscode/assets/17635050/0c7cc9bc-a625-47fa-b762-a9cac17b5b97)
The function of displaying all opened files in the tab bar without scroll bar。
Just like an image, this image is a multi row display setting for the Rider Editor

**Comment by benibenj** [comment]
Have you tried the `workbench.editor.wrapTabs` option which wraps tabs across multiple tab bars?

**Comment by hbwqing1017** [comment]
> Have you tried the `workbench.editor.wrapTabs` option which wraps tabs across multiple tab bars?

Thank you very much for meeting my needs
