### ISSUE TITLE
Add color contrast between requests/responses

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#200084]
Magnification users often zoom out to decide what they will zoom in to read. 

For HC themes, we should make sure there's a difference in color between requests and responses.

**Comment by hbons** [comment]
good idea!

**Comment by alexr00** [comment]
There's a slight difference on high contrast dark, but there appears to be no difference with high contrast light:

![image](https://github.com/microsoft/vscode/assets/38270282/24916298-98a3-48a6-8487-5d335095d978)

![image](https://github.com/microsoft/vscode/assets/38270282/26e44d89-4abb-4d95-ba83-4622adcd55fd)
