### ISSUE TITLE
Plugin suggestion should allow suppressing suggesting the plugin

### ISSUE THREAD

**Issue by pvginkel** [microsoft/vscode#200010]
Type: <b>Feature Request</b>

The notification suggesting a plugin has a cog with an option "Don't show again". It's however not clear whether this suppresses suggesting the specific plugin, or any plugin. Either this message should be clarified ("Don't show this plugin again") or a second option should be added.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by sandy081** [comment]
<img width="485" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/793c7e28-f60a-4fc3-b697-8bfa315bd29b">

<img width="478" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/2f4f078e-44ef-493a-b8c8-3c9c101e3673">

**Comment by pvginkel** [comment]
Thank you.
