### ISSUE TITLE
"vscode.executeDocumentHighlights" API has stopped returning DocumentHighlight[]

### ISSUE THREAD

**Issue by mcoumbe** [microsoft/vscode#200056]
Type: <b>Bug</b>

I have an extension that has been making use of the executeCommand API for "vscode.executeDocumentHighlights" to get the `DocumentHighlight[]` for different positions in a file. Essentially calling something like below:
```ts
const highlights = await vscode.commands.executeCommand<DocumentHighlight[]>("vscode.executeDocumentHighlights", uri, pos);
```

After a recent VsCode update, the API is no longer returning any values and simply returns `undefined`.

I'm not sure the best way to provide a reproduce for this. I originally encountered the problem with a custom extension/language server. However the problem also appears to occur when calling the same command on a simple typescript file so I believe it's a general issue rather than any thing specific to my environment.

I've had a quick search in the VsCode sources and I have a feeling this commit might be responsible: https://github.com/microsoft/vscode/commit/7dff07893ac160244db210e574eccc05f1cba2cb

I think the problem is due to `getOccurrencesAtPosition` now returning `ResourceMap<DocumentHighlight[]>` instead of `DocumentHighlight[]`.
https://github.com/microsoft/vscode/blob/85b1ab9a53c5ce93ecee90d8c43a70fcb60ce6ce/src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts#L256-L259

When it gets to the ApiCommand layer I think the `tryMapWith` function fails and returns `undefined` as the function has been given a `ResourceMap<DocumentHighlight[]>` instead of `DocumentHighlight[]`
https://github.com/microsoft/vscode/blob/85b1ab9a53c5ce93ecee90d8c43a70fcb60ce6ce/src/vs/workbench/api/common/extHostApiCommands.ts#L29-L33

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.75GB (42.48GB free)|
|Process Argv|. --crash-reporter-id 438e9a7d-b840-41a0-a731-2833797fc3d5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.53.0
vscode-eslint|dba|2.4.2
mfcobol|Mic|1.0.53
mfenterprise|Mic|1.0.53
vscode-language-pack-ja|MS-|1.84.2023111509
csdevkit|ms-|1.0.14
csharp|ms-|2.12.19
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
jupyter|ms-|2023.10.1100000000
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
powershell|ms-|2023.8.0
remote-explorer|ms-|0.4.1
test-adapter-converter|ms-|0.1.8
java|red|1.25.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.43.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
vscrp:30673768
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by jrieken** [comment]
Thanks @mcoumbe. This is a good find!

**Comment by jrieken** [comment]
To verify:

* make sure this test has passed: https://github.com/microsoft/vscode/blob/7cd710eefe7a0a20f3f191a972ba5cc41b5a9e02/src/vs/workbench/api/test/browser/extHostApiCommands.test.ts#L686
