### ISSUE TITLE
Make it clearer what the suggested question is/does

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#200083]
Users in the fable study weren't sure if the question was asking them something (given it's a chat experience) or if it was actionable. 

Could we use a better icon to indicate this?

Should we add static text: `Suggested question:`?

We should also add `Suggested question:` to the aria label.

**Comment by roblourens** [comment]
Is this just something where you might not be sure what it is, then you click it, and you instantly find out, and then it's no longer a question? That's how UX has to work sometimes. Not opposed to an aria label. Sounds like it's about screenreader and also sighted users though (since you mentioned an icon)

**Comment by meganrogge** [comment]
The copilot sparkle icon is redundant IMO, since this question exists within the copilot chat panel. 

Yes, a submit / run icon would be better I think to indicate what will happen.

**Comment by meganrogge** [comment]
![Screenshot 2023-12-19 at 1 11 06 PM](https://github.com/microsoft/vscode/assets/29464607/56bc350d-4169-4024-88a6-2c333d68cc99)

**Comment by roblourens** [comment]
I don't really like that one, sorry, I don't think "run" is the right meaning

**Comment by meganrogge** [comment]
I don't love it either. Other ideas?

**Comment by roblourens** [comment]
Maybe submit? But otherwise I think "sparkle" makes sense for "send this to the magic AI"

**Comment by meganrogge** [comment]
We're within the copilot chat panel already - so not sure the sparkle is necessary.

**Comment by roblourens** [comment]
It's just blue text that does something very different than all the other blue text, so I think it needs something to differentiate it, and I think the sparkle works as well as anything

**Comment by meganrogge** [comment]
It differentiates it but doesn't give any indication of what will happen. That's what users have reported.

**Comment by roblourens** [comment]
Well I don't have any other ideas

**Comment by meganrogge** [comment]
@hbons any ideas for a better icon here?

**Comment by meganrogge** [comment]
I think we can mention follow ups in the accessibility help dialog.

**Comment by meganrogge** [comment]
To verify:

- in the chat input box, `alt+f1` and make sure you it contains "In the input box, navigate to the suggested follow up question (Shift+Tab) and press Enter to run it."
- with a screen reader on, focus the input box. `shift+tab` to the suggested question and verify that the aria label indicates it's a suggested question.
