### ISSUE TITLE
Colored labels / layers in the tree view

### ISSUE THREAD

**Issue by mattkenefick** [microsoft/vscode#200047]
To be able to right click and select a color background for different tree depths like you might find on Mac, Photoshop, Illustrator, etc. Not just a file-type icon, but something you can arbitrarily set and unset.

<img width="936" alt="image" src="https://github.com/microsoft/vscode/assets/149809/c93f3633-8719-4d2d-a970-ee06bf9689bc">

<img width="363" alt="image" src="https://github.com/microsoft/vscode/assets/149809/fe7ad81a-8a85-4ce4-bd3f-a04c28acfef0">

I'm less a fan of the Finder's implementation where it's just a circle.

The value to me comes in organization on larger projects where there are folders / files you want to remember todo, things you want to forget, etc. Like "I don't need to look at this folder anymore, so I'll mark it red for now to remind me it's done."

And if the marks were saved somewhere in `.vscode` or something, they could be shared across the team perhaps which allows you to highlight things for other coworkers.

I'm not sure about a universal implementation, but I've been wanting to see this show up in the VSCode extension API so I could implement it how I'd need it.

**Comment by alexr00** [comment]
Is this something you want in the File Explorer tree, or in all trees?

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode/issues/62104
