### ISSUE TITLE
Debug Toolbar should be aligned to the right when placed in command center

### ISSUE THREAD

**Issue by icnahom** [microsoft/vscode#200021]
![image](https://github.com/microsoft/vscode/assets/60504285/2a74818c-2157-4ea1-aae8-aeb6e2da19d5)

Since the debug toolbar was mostly on the right side, I would prefer to have it on the right, next to the search icon. Most IDE's have these buttons on the right, so it would be against our muscle memory to go all the way to the left.

**Comment by gjsjohnmurray** [comment]
Please add the word "Debug" to the start of this issue title.

**Comment by roblourens** [comment]
What do you mean by 

> was mostly on the right side

**Comment by icnahom** [comment]
> What do you mean by
> 
> > was mostly on the right side

Poor wording maybe, I meant personally for me I had it floating on the right side.

Some screenshots from the web:

![](https://miro.medium.com/v2/resize:fit:1400/1*3JK8YlyF6HfLeXrSm-_D4A.png)
![](https://uploads.sitepoint.com/wp-content/uploads/2018/04/152442833804-places-hover.png)

**Comment by roblourens** [comment]
Sure, you can drag it anywhere. I don't really see why the right side of the command center would be really any different than the left side. If we try to add more stuff into the command center later, maybe then it would make sense for it to be even more customizable. For now I think left is fine.

**Comment by icnahom** [comment]
> Sure, you can drag it anywhere. 
Yes but I kind of liked the new location, since it's not covering anything below - unlike the floating option.

> I don't really see why the right side of the command center would be really any different than the left side.
It's not a big deal to be honest, but UX wise it feels wrong. In fact I believe it shouldn't even be place inside the command center box. Right side outside the box would improve the Visual Hierarchy.
