### ISSUE TITLE
UI glitches with test view widget and sticky scroll

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#200192]
Does this issue occur when all extensions are disabled?: Yes/No

<img width="906" alt="image" src="https://github.com/microsoft/vscode/assets/876920/04e97ce4-a5f7-4ace-8ed4-05bd9eaa1231">

When scrolling upwards the title bar of the test view can overlap with the sticky scroll and its half transparant background looks weird with sticky scroll.

**Comment by eleanorjboyd** [comment]
I think I am still seeing this I just have a non-transparent background for my problems view. It looks better but the problem view should probably scroll under the sticky scroll like the rest of the file.

https://github.com/microsoft/vscode/assets/26030610/48f0f61d-5552-40d3-bff9-546565eea33b

**Comment by connor4312** [comment]
Peeks in general go over sticky scroll right now, e.g. Peek References. This fix was just fixing test's behavior of not having an opaque background.
