### ISSUE TITLE
警告，在过去的5分钟TypeScript语言服务终止了5次，一直闪跳，无法打字使用。

### ISSUE THREAD

**Issue by dan938** [Microsoft/vscode#20017]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

- [](url)

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|javadebugger|donjayamanne|0.0.2|
|vscode-javac|georgewfraser|0.0.23|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|Go|lukehoban|0.6.53|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.5.2|
|vscode-sort-json|richie5um2|1.7.0|
|vscode-icons|robertohuertasm|7.2.0|

---

Steps to Reproduce:

1.
2.

**Comment by innerlee** [comment]
https://github.com/Microsoft/vscode/issues/20003
