### ISSUE TITLE
Panel grab bar is too small and should be expanded by 2px

### ISSUE THREAD

**Issue by thadguidry** [microsoft/vscode#200103]
Type: <b>Bug</b>

The Panel grab bar active area is too small currently and requires the most precise mouse movements in order to highlight and grab its top bar to expand it vertically.  I would appreciate if the active area was increased about 2px above and below it's current active grab range.

### Video of the problem

https://github.com/microsoft/vscode/assets/986438/b206008a-3edf-40a0-a7c2-197af7d3712f

VS Code version: Code - Insiders 1.85.0-insider (6d33f515e8cbe8c134c75f81a6764c9a2bdde620, 2023-12-05T22:06:57.246Z)
OS version: Windows_NT x64 10.0.23595
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (54.65GB free)|
|Process Argv|--crash-reporter-id ec828980-5f99-4b3a-9589-b598d2900347|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|3.1.10
vscode-eslint|dba|2.4.2
gitlens|eam|2023.12.504
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
vscode-firefox-debug|fir|2.9.10
copilot|Git|1.140.0
copilot-chat|Git|0.11.0
vscode-pull-request-github|Git|0.77.2023120509
vscode-graphql|Gra|0.8.20
vscode-graphql-syntax|Gra|1.2.2
todo-tree|Gru|0.0.226
vscode-docker|ms-|1.28.0
vscode-edge-devtools|ms-|2.1.3
vscode-kubernetes-tools|ms-|1.3.15
playwright|ms-|1.0.19
isort|ms-|2023.11.13191009
python|ms-|2023.23.13391009
vscode-pylance|ms-|2023.11.102
remote-containers|ms-|0.326.0
remote-wsl|ms-|0.81.8
cmake-tools|ms-|1.17.5
cpptools|ms-|1.19.1
cpptools-extension-pack|ms-|1.3.0
test-adapter-converter|ms-|0.1.8
vsliveshare|ms-|1.0.5896
htmx-tags|oto|0.0.8
java|red|1.25.0
vscode-xml|red|0.26.2023120208
vscode-yaml|red|1.14.0
rust-analyzer|rus|0.4.1759
sonarlint-vscode|Son|4.1.0
code-spell-checker|str|3.0.1
vscode-stylelint|sty|1.3.0
svelte-vscode|sve|108.1.0
even-better-toml|tam|0.19.2
cmake|twx|0.0.17
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.51.2023120505
vscode-gradle|vsc|3.13.2023112207
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.2023120100
vscode-java-pack|vsc|0.25.2023110908
vscode-java-test|vsc|0.40.2023101002
vscode-maven|vsc|0.43.0
vscode-spring-initializr|vsc|0.11.2023070103
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30901777
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the `workbench.sash.size` setting help you?

**Comment by sbatten** [comment]
closing as setitngs resolve issue
