### ISSUE TITLE
Insiders and stable URL's reversed when instantiating UserDataSyncStoreClient

### ISSUE THREAD

**Issue by colin-grant-work** [microsoft/vscode#200196]
Does this issue occur when all extensions are disabled?: Probably not, as there would be no one to supply auth.

- VS Code Version: b141c5a (1.85)
- OS Version: CentOS 8

## Steps to Reproduce:

1. Attempt to use a `product.json` that would default to `insiders` URL.
2. Log in, and observe that it attempts to use the `stableUrl` anyway.

It looks wrong that if the `type` is `'insiders'`, the `stableUrl` is used, otherwise `insidersUrl`. Seems the branches of the ternary should be reversed.

https://github.com/microsoft/vscode/blob/b141c5accd99034811099fb30ae856e997db14dc/src/vs/workbench/services/userDataSync/browser/userDataSyncWorkbenchService.ts#L349

**Comment by sandy081** [comment]
It was intentional so that during initialisation in web we can get the other end point - 

https://github.com/microsoft/vscode/blob/1350b6eca0c46484fd489e9cdad83ec146c15ef2/src/vs/workbench/services/userDataSync/browser/userDataSyncInit.ts#L148-L151
