### ISSUE TITLE
Tailwind css options do not get auto suggested after adding className=""

### ISSUE THREAD

**Issue by ramanand-rv** [microsoft/vscode#200105]
Tailwind css options do not get auto suggested after adding className=""
![image](https://github.com/microsoft/vscode/assets/80584888/69b84b6a-f0c2-4df2-8e9e-669561d246e6)

User is required to click ctrl+space to see the options or add an extra space to list down the options
![image](https://github.com/microsoft/vscode/assets/80584888/21826fd2-f2b2-4256-8d1f-0d2bc4177635)

![image](https://github.com/microsoft/vscode/assets/80584888/6058729d-8112-4605-943f-5d76ccc6d9a2)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.84.2
- OS Version: Windows 10

Steps to Reproduce:

1. Start any project having Tailwind configured
2. Create a file (xyz.jsx / abc.tsx) 
3. add an element, try adding tailwind styling by adding className=""

Expected: Styling options should get auto suggested
Actual: No options are auto suggested, user has to click ctrl+space or add an extra space in order to list down the options

**Comment by aeschli** [comment]
The built-in HTML language service is designed for standard HTML and CSS.
Tailwind support has to come from a Tailwind extension
