### ISSUE TITLE
Let tab content provide custom icon name

### ISSUE THREAD

**Issue by hbons** [microsoft/vscode#200147]
Right now tabs with non-file content like Settings/Extensions/PRs use the generic text file icon in the tab bar. It would improve ease of navigation if content that's not a file could provide their own icon name.

In this mockup the `extensions`, `settings` and `git-pull-request` are used:

<img width="813" alt="image" src="https://github.com/microsoft/vscode/assets/103326/9680fcb3-55dc-46b0-b62c-d1b4b49ebb0a">

**Comment by bpasero** [comment]
👍 , the implementation issue is https://github.com/microsoft/vscode/issues/199965 from @benibenj
