### ISSUE TITLE
Add room in titlebar to click and drag window around when restored

### ISSUE THREAD

**Issue by bordrboy** [microsoft/vscode#200146]
SUMMARY: In VSCode for Windows, users are not able to easily drag a window around by clicking and dragging the title-bar when _Men Bar_, _Command Center_, and _Layout Controls_ are all on. With the VSCode window not maximized (Restored) it can make it to where the entire title-bar is filled with clickable items and you basically can't click and drag the window around.

Visual:
![image](https://github.com/microsoft/vscode/assets/7196249/9961c440-85d3-4aa5-ad8d-253dd0262abd)

Feature Suggestion: 
Leave some acceptable size padding somewhere on the toolbar that's always easily clickable.

Chrome addresses this by always leaving some blank space to the left of the minimize/restore/close buttons:

![image](https://github.com/microsoft/vscode/assets/7196249/a1d0b8d6-821c-4c1e-9b1c-a745f8a271fa)

**Comment by gjsjohnmurray** [comment]
For me the window is draggable with a small area between the `...` menubar entry and the `Go Back` button, and also with a thin strip below the command centre.

**Comment by LWChris** [comment]
Well "recent" update isn't quite true. That input field is the "Command center" and was introduced in the June 22 update. I'm currently on my phone so I don't know what customization options there are or have been added in those 18 months, but probably you can find something with that information.

If nothing is available I'd appreciate an option for the bar to stay compact unless focused.

**Comment by bordrboy** [comment]
@LWChris thanks for the input. I updated the issue request to be more accurate.

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/169380
