### ISSUE TITLE
Refresh explorer doesn't work when explorer is moved

### ISSUE THREAD

**Issue by dacapoday** [microsoft/vscode#200109]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:
![explorer_dis](https://github.com/microsoft/vscode/assets/9378047/72621d3c-e513-486c-b71d-9ec7e4e7361a)

also causes `Refresh Explorer` to fail.

Related issues:
https://github.com/microsoft/vscode/issues/197301

Workarround:
* call `View: Reset View Locations`

**Comment by lramos15** [comment]
I cannot reproduce, so you just move views around a bunch until the explorer disappears?  Do you have any extension?

**Comment by lramos15** [comment]
Okay so I can see that refresh explorer doesn't work in this case, that's for sure. I cannot get folders to completely disappear

**Comment by lramos15** [comment]
To verify:
1. Move the folder view (the file tree structure) somewhere else separate from the explorer view container
2. Hit refresh explorer

You should stay on the folder view and not be moved to a different view container. You should also see the refresh properly occur.
