### ISSUE TITLE
My vs code appear blank after opening and gets stuck in a lag. I have tried various methods online and also deleted and downloaded it again for well over a year now but it just doesn't work. To make sure it works, I've also download all the extra packs on the official website for running it but it is just the same.

### ISSUE THREAD

**Issue by theonesupreme** [microsoft/vscode#200155]
Does this issue occur when all extensions are disabled?: Yes/No (Yes)

- VS Code Version:  Code 1.84.2 
- OS Version: 10.0.14393 N/A Build 14393

Steps to Reproduce:

1. I just downloaded it from the main site.
2. Opened it.
3. it got stuck in a blank like lag showing nothing.

My situation is something like this:
![Sketch](https://github.com/microsoft/vscode/assets/69294542/0d5a4370-3733-42aa-9c00-6dca42eaec4f)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by theonesupreme** [comment]
I searched a few way and stumbled upon deleted the 'Code' folder from the C:\Users\a(username)\AppData\Roaming and when I re-installed the app, it started working. Thanks for the suggestion anyway, @bpasero .
