### ISSUE TITLE
git.exe high cpu and memory

### ISSUE THREAD

**Issue by graysongs** [Microsoft/vscode#20019]
- VSCode Version: **1.8.0**
- OS Version: **windows 7 sp1 x64 Ultimate**
- Git Version :  **Git_2.11.1**

Steps to Reproduce:  check images I upload
![qq 20170206164523](https://cloud.githubusercontent.com/assets/20311450/22640597/5b5dbd94-ec8e-11e6-8c69-deb47f2b1997.png)

![qq 20170206165328](https://cloud.githubusercontent.com/assets/20311450/22640525/fc2c57ea-ec8d-11e6-840a-6e038f5e91db.png)
![qq 20170206164716](https://cloud.githubusercontent.com/assets/20311450/22640540/0aef4418-ec8e-11e6-969c-459b86450511.png)
![qq 20170206165357](https://cloud.githubusercontent.com/assets/20311450/22640550/1757dcb0-ec8e-11e6-83eb-906125f45004.png)

**Comment by graysongs** [comment]
I found this problem on version 1.9.0 , then I try to change to lower version to avoid that ,  It does not work.  So , probably some version are have this problem.

**Comment by joaomoreno** [comment]
When you click the Git icon, do any changes appear in the window? Can you show a screenshot of that?

What do you get when you run `git status` from the command line, when in that folder?

**Comment by graysongs** [comment]
@joaomoreno 
![qq 20170207092411](https://cloud.githubusercontent.com/assets/20311450/22673816/628ab0a2-ed17-11e6-93f2-4a6e7371c8c5.png)

**Comment by joaomoreno** [comment]
You repository appears to be enormous. Try running `git status -u`. How long does that take?

**Comment by graysongs** [comment]
@joaomoreno 
When running `git status -u` , it seems endless code flush into cmd window , and git.exe still consumes cpu and memory.
![qq 20170208093442](https://cloud.githubusercontent.com/assets/20311450/22719740/ec55e5b6-ede1-11e6-83d0-13d2d0f4bcca.png)

**Comment by graysongs** [comment]
@joaomoreno I try to run `git init` in current folders(e:\demo\tree)  , then vscode works fine.
![qq 20170208094451](https://cloud.githubusercontent.com/assets/20311450/22720040/7b62db3c-ede3-11e6-83f9-75ed82fbe9a2.png)

**Comment by graysongs** [comment]
@joaomoreno 
There are few question : 
1.When I run `git status -u` , code in cmd window shows it looks up in e:\demo\build\node_modules . Why I opened e:\demo\tree , but vscode try to find .git folder in e:\demo ?
2.Is this a bug , or just because I don't know how to use git ?

**Comment by joaomoreno** [comment]
You possibly have initiated a git repository somewhere where you didn't intend to. In `E:\demo`, run `git rev-parse --show-toplevel`. It will tell you where the root of that git repository is. There will be a `.git` folder inside. Just delete it. 👍

**Comment by Jazman1** [comment]
I also have this issue. Git for Windows is running in the background constantly using 15% CPU when I'm idle. And git root level is correct. git status -u is also clean.
