### ISSUE TITLE
add predefined variables to the tasks.json as comment

### ISSUE THREAD

**Issue by roycarser** [Microsoft/vscode#20015]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.6|
|xml|DotJoshJohnson|1.6.1|
|cpptools|ms-vscode|0.9.3|
|vscode-icons|robertohuertasm|5.0.0|

---

Steps to Reproduce:

1.write predefined variables to the default tasks.json as comment
like this: you can fold this comment by default if you think this is occupy too much space
![default](https://cloud.githubusercontent.com/assets/24681803/22639737/768bc25e-ec8a-11e6-8198-5e67bac79af9.png)

**Comment by dbaeumer** [comment]
We had that in the past and then decided to replace it with a link to the documentation. The complain was that if we start to list variables why not the index fields for problem matchers. It is very hard to make the cut here.
