### ISSUE TITLE
Ctrl + Space in a FILE within the integrated terminal doesn't work if the path contains spaces...

### ISSUE THREAD

**Issue by kenzaflow** [microsoft/vscode#200166]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.2 (user setup)
- OS Version: Windows_NT x64 10.0.22631

Copied from VSCode:

Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Have at least one space in the FILE path, in my case, in the username I created... "fuck microsoft."
2. Ctrl + Click doesn't function due to the space. If I remove the space in terminal.integrated.wordSeparators, the beginning of the line, the "FILE " gets copied as well, ruining the entire Ctrl + Click functionality.

I've been searching online to change the Windows username, but all the required steps are extremely frustrating (me hincha mucho las pelotas). In the end, the only solution seems to be creating a new user or formatting, which is even more frustrating because I need to work! I can't believe this, all because they didn't implement a Regex in terminal.integrated.wordSeparators instead of "1 character in that configuration string = 1 space". Goodness!

https://github.com/microsoft/vscode/assets/74398451/6b999f17-bc80-415f-9915-abb7bbe32eb2

**Comment by Tyriar** [comment]
I think you're saying removing space from word separators would fix this but that would not work because then ` FILE ` would be part of the ["word link"](https://code.visualstudio.com/docs/terminal/basics#_links).

**Comment by Tyriar** [comment]
To verify make sure links in the format above (` FILE ...`) work correctly
