### ISSUE TITLE
Title bar: show git branch information

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#20016]
Related to https://github.com/Microsoft/vscode/issues/1723, make it possible to show the current branch name in the window title.

**Comment by tommck** [comment]
I know TFS isn't a first-class citizen in the VS Code world, but it would be nice to have similar functionality for TFS as well

**Comment by bpasero** [comment]
I think this is similar to being able to show some SCM status in the explorer: We need a generic enough `ISCMService` that we can use everywhere to make these calls. 

/cc @joaomoreno

**Comment by SailorMax** [comment]
Also it would be nice to see current branch name in title of "Source Control" panel, before "Commit" button.
Sometimes when work with few branches at the same time can make changes in wrong branch. This information has to be before eyes on commit. Looks at bottom of window or any other place not always work.

**Comment by Deathhush** [comment]
Is there any update on this item? Showing the current branch name in the title of source control panel will be very helpful. In Git, people typically work with multiple branches. @bpasero

**Comment by SailorMax** [comment]
@Deathhush Not great, but solution - new setting "scm.alwaysShowProviders": true

**Comment by joaomoreno** [comment]
Going for `"scm.alwaysShowProviders": true` instead, in this way you always have that information at a glance as well as a few useful context actions. 👍

**Comment by rafareino** [comment]
I am a free lancer, and sometimes I do multiple projects to the same company (in different efforts) and need to be able to properly track the amount of time I spent in each project.

RescueTime/ActivityWatch/ProcrastriTracker among others track my time usage true capturing my active window name regularly.

Would be great if we could have some free form terminal command to be run regularly (once a few minutes) and updating a variable to be included in the customized tittle bar. I recognize that I have a very edge use case, but would be great if we could embrace it.

Thoughtfully
