### ISSUE TITLE
Git diff populated in the commit message on `--amend`

### ISSUE THREAD

**Issue by sshishov** [microsoft/vscode#200189]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `1.84.2 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e arm64`
- OS Version: `macOS Sonoma 14.1.1 (23B81)

Steps to Reproduce:

1. It happens not every time, but probably I have a file which will cause the issue
2. In config we have:
```
[core]
    editor = code --wait
```
3. `git commit --amend`

This issue have the same root cause as:
- https://github.com/microsoft/vscode/issues/92581
- https://github.com/microsoft/vscode/issues/51121

Mentioned issues have been closed but never fixed. Please note that if I change `editor` to `vim` then the same operation working as expected.

**Comment by sshishov** [comment]
I am going to provide the repo where we can reproduce the issue in few days, will keep you updated.

**Comment by sshishov** [comment]
Okay, I have figured out the reproducible example, create any `txt` file and add the following:
```text
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
```
Just 21 lines in the file.
If we are using ordinary `git commit` it is working because the diff is not populated into the editor
But if we are using `gc` which stands for `git commit -v` then we are getting the commit message populated with all the diff.

```
alias gc                  
gc='git commit -v'
```

This alias is from the standard [`git` plugin for `zsh`](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git), in `.zshrc`:
```zsh
plugins=(
  git
  ...
)
```

And this is the commit message I receive:
```
commit 0a5eef89f0ba30e9da9fa21f227c11cc003b665a (HEAD -> main)
Author: <AUTHOR>
Date:   Thu Dec 7 02:08:38 2023 +0400

    test commit message
    diff --git a/testfile.txt b/testfile.txt
    new file mode 100644
    index 0000000..2bd26db
    --- /dev/null
    +++ b/testfile.txt
    @@ -0,0 +1,21 @@
    +1
    +2
    +3
    +4
    +5
    +6
    +7
    +8
    +9
    +10
    +11
    +12
    +13
    +14
    +15
    +16
    +17
    +18
    +19
    +20
    +21

 testfile.txt | 21 +++++++++++++++++++++
 1 file changed, 21 insertions(+)
```

**Comment by lszomoru** [comment]
Sorry for not getting back to you on this until now. I am reading through the issue and I am having hard time understanding how is this an issue with VS Code since the repro steps that you have included involves only git and the git alias that you are using. Could you please elaborate? Thanks!
