### ISSUE TITLE
TypeScript 语言服务意外终止

### ISSUE THREAD

**Issue by jcindex** [Microsoft/vscode#20012]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|tslint|eg2|0.8.1|
|TypeScriptImport|kevinmcgowan|1.7.0|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|tsimporter|pmneo|1.2.13|

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
Please file issues in english language.
