### ISSUE TITLE
Build failed: smoke test failure, extensions

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#200170]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=248012
Changes: https://github.com/Microsoft/vscode/compare/ec2c8e1...f713a29

```
 VSCode Smoke Tests (Web)
       Extensions
         install and enable vscode-smoketest-check extension:
```

**Comment by meganrogge** [comment]
again https://dev.azure.com/monacotools/Monaco/_build/results?buildId=248021&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=d37b6de0-ee32-5542-d5b1-fb041953e05d&l=105

**Comment by bpasero** [comment]
I think the install never completed, maybe a network issue?

<img width="312" alt="image" src="https://github.com/microsoft/vscode/assets/900690/3f6019ff-f64f-417c-81d1-b7a42babda53">

**Comment by sandy081** [comment]
Network related.
