### ISSUE TITLE
CSS auto complete not work

### ISSUE THREAD

**Issue by valeri879** [Microsoft/vscode#20018]
- VSCode Version: 1.9
- OS Version: Windows 10 Home

Steps to Reproduce:

1.  sometimes css auto complete not work for me

**Comment by bpasero** [comment]
@valeri879 can you provide more details about your setup and extensions?

**Comment by valeri879** [comment]
@bpasero I deleted all extensions and reinstall  `code` but after 1 day still not working auto complete

**Comment by aeschli** [comment]
Can you paste the code example?
Can you open the developer tools (Help > Toggle Developer Tools) and see if there is anything in the console?

**Comment by valeri879** [comment]
here is screenshot

![capture](https://cloud.githubusercontent.com/assets/6426966/22687809/f6de3172-ed42-11e6-80ea-541e12c5e310.PNG)

**Comment by valeri879** [comment]
@aeschli @bpasero Guys help me please, I really like this editor, but without suggestion it's very useless

**Comment by aeschli** [comment]
duplicate of #19840
