### ISSUE TITLE
Style suggestions are not available in HTML page.

### ISSUE THREAD

**Issue by anishmvcd** [Microsoft/vscode#20020]
Style suggestions are not available in HTML page

**Comment by mrmlnc** [comment]
Please, provide more detailed description of your problem. This is works fine for me.

<details>
![screencast 2017-02-06 12-12-38](https://cloud.githubusercontent.com/assets/7034281/22640899/a32e7970-ec65-11e6-87fe-674c803bfd07.gif)
</details>

**Comment by anishmvcd** [comment]
@mrmlnc I'm sorry, I forgot to mention that suggestions are not getting while adding in-line styles to a tag.

**Comment by mrmlnc** [comment]
@anishmvcd, 

Maybe you attach your file, version of VS Code and list of installed extensions?

<details>

![screencast 2017-02-06 13-07-03](https://cloud.githubusercontent.com/assets/7034281/22642828/46595fb4-ec6d-11e6-8ef6-3b84be9a0be3.gif)

</details>

**Comment by aeschli** [comment]
Closing due to lack of additional information
