### ISSUE TITLE
regression: optimize-vscode now fails with EMFILE on linux

### ISSUE THREAD

**Issue by brjsp** [microsoft/vscode#200276]
Since the last release 1.85.0 i am unable to build the [Code package in openSUSE](https://build.opensuse.org/package/show/devel:tools:ide:vscode/code). It always fails at this step:
```
[  758s] [22:13:10] Finished [36mcompile-extension-media-build[39m after [35m242 ms[39m
[  758s] [22:13:10] Starting [36mclean-out-vscode[39m ...
[  758s] [22:13:10] Finished [36mclean-out-vscode[39m after [35m2 ms[39m
[  758s] [22:13:10] Starting [36moptimize-vscode[39m ...
[  759s] ✘ [ERROR] Cannot start service: Host version "0.17.14" does not match binary version "0.19.1"
[  759s] 
[  759s] 1 error
[  765s] [22:13:16] 'vscode-linux-x64-min' errored after 7.83 min
[  765s] [22:13:16] Error: EMFILE: too many open files, open '/home/abuild/rpmbuild/BUILD/vscode-1.85.0/out-build/vs/base/browser/ui/iconLabel/iconLabelHover.js.map'
[  765s] error Command failed with exit code 1.
[  765s] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[  765s] error: Bad exit status from /var/tmp/rpm-tmp.vbMfjN (%build)
```
(ignore the esbuild “cannot start service” message, this is expected output due to our downstream patches)

I suspect the culprit to be commit 87e7f8b5 but am unable to revert it easily due to it removing dependencies from `node_modules` which is not reflected in the git diff.

**Comment by brjsp** [comment]
@deepak1556 The rpmbuild runs fine on my local computer, it only fails on OBS where i do not have interactive access (the FD limit there seems to be 4096)

Do you know a way to run the node process under a harness that shows the max number of open descriptors?

**Comment by deepak1556** [comment]
There is no builtin way, you can use `lsof` or `strace` to determine the open file descriptors.

**Comment by brjsp** [comment]
I managed to reproduce the issue in a git checkout, bisecting gave inconsistent results in the vicinity of commit 90d1e81c.

This seems to be therefore a case of software bloat, not a leak or other bug.
