### ISSUE TITLE
Prettier grey sparkle?

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#200240]
This is subjective (and others might not feel this way) but the grey sparkle looks a bit off-putting to me, especially in dark mode. I guess there was feedback that non-filled grey sparkle was not too visible, but the current solution seems less pleasant. 

<img width="643" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/413c5e5b-d32b-4f90-88e9-c3ff76b7f983">

<img width="455" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/79c2b109-d215-43a1-9f61-ac3c9ac3e7c5">

**Comment by aeschli** [comment]
I agree. What about using the same yellow as the lightbulb? In the end it is just a different lightbulb. And we don't need to make up a new color.

![image](https://github.com/microsoft/vscode/assets/6461412/db172b69-354d-4fb7-85a9-4df9c5861388)

**Comment by aiday-mar** [comment]
I will change the color of the sparkle to make it yellow

**Comment by hbons** [comment]
I thought @aiday-mar changed this before from yellow to grey based of previous feedback. :)
Maybe we should just increase the contrast?

**Comment by aeschli** [comment]
I think the yellow looks good and has some advantages:
- we that we don't introduce a new color. It's difficult to pick a new color that works for existing themes
- the sparkle is just a variant of the lightbulb and the hope is using the same color will convey that
