### ISSUE TITLE
Provide a command to toggle menu bar visibility without settings change

### ISSUE THREAD

**Issue by m3l7** [Microsoft/vscode#20024]
by default, I set the menu bar to hidden.

Sometimes I need to show the menu bar, so I run the command "toggle menu bar", but when I want to return to the default hidden behaviour I'm forced to open my user settings.

It should be nice to have a command "hide menu bar" or having a unique command which respects toggle/hide behaviour

**Comment by Swiiip** [comment]
Why don't you just run "toggle menu bar" again ? ^^

**Comment by m3l7** [comment]
if I run "toggle menu bar" again the "menubarVisibility" settings is automatically changed to toggle, instead of hidden

**Comment by bpasero** [comment]
This is a tough one. Maybe we should have another command to make the menu bar visible but this does not write to settings but instead just does it for the current window?

**Comment by hoovercj** [comment]
@m3l7 I have published an extension that allows you to change any setting using keyboard commands. It is called [Settings Cycler](https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler) and it allows you to cycle through different values for a setting -- either to enable or disable a setting or to cycle between values.

For your case, if you use this setting:
```json
    "settings.cycle": [
        {
            "setting": "window.menuBarVisibility",
            "values": [
                "hidden",
                "default"
            ]
        }
    ]
```
And this keybinding (you can change the keys):
```json
{
    "key": "ctrl+shift+t",
    "command": "settings.cycle.window.menuBarVisibility",
    "when": ""
}
```

You should get the behavior that you want.


I hope it helps!

**Comment by rebornix** [comment]
It's a good extension candidate and you can use [Settings Cycler](https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler) or follow https://medium.com/hack-visual-studio-code/toggle-any-setting-in-vs-code-using-keyboard-shortcut-arguments-cdb5ddc56955 to get your preferred extension to archive that.

**Comment by hoovercj** [comment]
Thanks for the shout-out, @rebornix!

Neat optimization adding the settings as arguments to the command directly, I hadn't thought of that.

Quick question though...Any reason that toggle and Settings Cycler shouldn't be the same extension?I n the end the main purpose is the same, and I can see both being useful for different situations.

I could patch it in myself, but it would feel less like stealing if you submitted a PR or gave explicit blessing. If you'd rather they remain separate, that's fine too.

Cheers!

**Comment by rebornix** [comment]
@hoovercj sure, it sounds good to me. My whole point of writing that extension is showing users/extension authors about how to leverage keyboard shortcut `arguments` and you are totally correct, we should make them a single one.

It would be awesome if you can do the patching as I don't know what kind of tweaks to your existing functionality you would like. Once you do the patching, I'll update my blog post and just talk about Settings Cycler.

**Comment by hoovercj** [comment]
Mission accomplished, I didn't realize the power of `args` in keyboard commands, but now I do :-)

I just updated Settings Cycler. It basically uses your schema now, but allows users to specify them either directly on the command or in settings. There are a couple other settings as well related to logging, allowing workspace overrides, etc. Thanks again for the ideas for improvement!

**Comment by rebornix** [comment]
@hoovercj impressive! I'll update the blog post this weekend.

**Comment by hoovercj** [comment]
@rebornix fyi, I'll be traveling for a week starting on Saturday, so hopefully there aren't any issues with the extension :-)

**Comment by bpasero** [comment]
Closing in favour of extension.
