### ISSUE TITLE
Regression: Mangled path in user tasks shell when executed in a workspace

### ISSUE THREAD

**Issue by mthierman** [microsoft/vscode#200279]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.0
- OS Version: Windows 11, 23H2 build 22631.2792

Steps to Reproduce:

1. Create a shell task in user level tasks.json. Minimal example with PowerShell:
```json
{
    "label": "Test",
    "type": "shell",
    "command": "Get-ChildItem",
    "problemMatcher": []
},
```
3. Execute the task in a non-workspace folder and it's fine (no path is printed in this case). Execute it in a saved workspace and the shell will print a mangled path:
`*  Executing task in folder d%3A%5CTest: Get-ChildItem`

I believe this path was printing correctly before the 1.85.0 update.

![Screenshot 2023-12-07 161931](https://github.com/microsoft/vscode/assets/68129072/fc7c6b17-b769-4088-8c79-dd39c907a9bc)

**Comment by meganrogge** [comment]
do you set a `cwd` for the task?

here's where we do this https://github.com/microsoft/vscode/blob/ce1f3a7579bcfe3854e7f2f58d30b1dc4893a5bf/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1180

**Comment by mthierman** [comment]
I did not have a cwd set, so I tried `"cwd": "${workspaceFolder}"`, which had the same result.

So I tried absolute paths and it seems to be a problem with the seperators in a Windows path, which I am guessing ${workspaceFolder} is also using on Windows.

`"cwd": "D:/GitHub/"` =  `*  Executing task in folder GitHub: Get-ChildItem`

`"cwd": "D:\\GitHub\\"` = `*  Executing task in folder d%3A%5CGitHub%5C: Get-ChildItem`
