### ISSUE TITLE
Can't resolve merge conflict in vscode-insiders

### ISSUE THREAD

**Issue by Yuhi-Aoki** [microsoft/vscode#200289]
## Environment data

-   VS Code version: 1.78.0-insider (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2023.4.1011172344
-   Python Extension version (available under the Extensions sidebar): v2023.7.11111009
-   OS (Windows | Mac | Linux distro) and version: Darwin x64 22.3.0
-   Python and/or Anaconda version: 3.10.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

open merge conflict editer, when click right-bottom green button

## Actual behaviour

I can't open merge conflict editer

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by TomashA1980** [comment]
same problem with 1.85 version VSC on Ubuntu

**Comment by conradwt** [comment]
I'm also seeing the same issue with VSCode - Insiders 1.88.0-insider (Universal) on macOS 14.3.1.

**Comment by DonJayamanne** [comment]
This should now be fixed,
Please feel free to ping here or create a new issue if this problem persists.
