### ISSUE TITLE
Undo (Ctrl+Z) when doing search-replace from the search window GUI does not work

### ISSUE THREAD

**Issue by sveinse** [microsoft/vscode#20026]
- VSCode Version: 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af)
- OS Version: Ubuntu 16.04, Gnome Shell

When searching and replacing text from the search window, doing undo (Ctrl+Z) does not undo the text in the editor.

Steps to Reproduce:

1. Search for a text using Ctrl+F, enter a search text and a replacement text
2. Find the next occurrence with the "Next match" button, press the "Replace" button.
3. Press Ctrl+Z and see that the undo function did not undo the last replace in the text editor, but rather changed the typed text in the replacement field.

As a workaround, change the focus to the text buffer window, and then press undo.

**Comment by bpasero** [comment]
@sveinse undo works in whatever control has focus. If the input box has focus, undo should undo what you typed there imho.

**Comment by sandy081** [comment]
Agreed with @bpasero, but how about switching the focus to the editor when pressed on replace button? This might break the current good user experience while navigating and replacing using keyboard

**Comment by sveinse** [comment]
As a user I'd expect the undo function in a editor window applies to the window in which the edit is made. A user does not (want to) care if a small helper search-replace window has focus or not. Particularly when there is no obvious GUI indication that the editor has lost focus to the the search window.

You could argue that you can see in the editor that the caret is gone when the search window gets focus, but the tab header of the editor windows seems to indicate that the editor still has focus. If you do edit the text in the replace field and press "Next match" and then "Replace" buttons, you'll also see that the replace field caret is gone. Hence, at this point, the user cannot know what the undo function actually will undo, since there is no indication of such. My argument is that the user will expect this to be the text editor.

I've checked with other editor, and the ones I tested all maps undo to undo the replaced text in the editor, _unless_ a text field in the search window is active with a caret. Then the undo function operates on the selected text field, and not the text editor.

**Comment by bpasero** [comment]
My understanding is that the replace input field has focus when undo is triggered? If not, then yes it should go to the editor. The rule is quite simple: go to the editor if the currently active element is not a textarea or input field.

**Comment by sveinse** [comment]
No, the input field does not have focus when undo is triggered. The input field loses focus when you press the search buttons. It is the last focused input field thou.

**Comment by bpasero** [comment]
@sveinse just for me to understand, is it like in the video what you do? And you expect after you click the replace button that undo undos the replacement in the editor to the right?

![kapture 2017-02-06 at 14 37 20](https://cloud.githubusercontent.com/assets/900690/22649090/c76ac60e-ec79-11e6-87b1-83dce9c942f4.gif)

**Comment by sveinse** [comment]
Yes. Both the search bar to the left and the built-in/pop-up search. My procedure is as shown below -- Unfortunately I could not get to show the keypress on the screen-cast, but in both cases I press Ctrl+Z after pressing the replace button. The result is that it undo the type into the replace input text field, not the replace done in the text editor, despite the replace input field has lost focus.

![vscode-search-undo](https://cloud.githubusercontent.com/assets/13770135/22649988/982190c2-ec7d-11e6-893c-8085e22e1d0e.gif)

![vscode-search-undo2](https://cloud.githubusercontent.com/assets/13770135/22650247/9d5d2406-ec7e-11e6-909d-5f7323e901f1.gif)

**Comment by bpasero** [comment]
Thanks for the video. It seems to me the tree has focus in the end (without showing any elements) and pressing undo goes to the replace input field for some weird reason. This should not happen, the undo action is implemented in a way that it will go to the active editor in that case in https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/config/config.ts#L715

Not sure if the search viewlet has its own keybinding handling for this case though.

**Comment by sandy081** [comment]
I do not think there are not any keybindings for ctrl+z in Search viewlet. Looks like Editor undo is happening only when editor text has focus. That's why ctrl+z is undo-ing the replace input in find widget also.

**Comment by Nimzozo** [comment]
Not sure if I should open a new issue, but when I undo with the focus on the search field, it doesn't work properly. I mean it undoes letter by letter (and never replace with the previous search term). I think it should undo the entire field, although it could be another problem for regexp...

**Comment by sandy081** [comment]
@Nimzozo To replace with previous search term you can use Alt + Up or Alt + Down keys. You can also customise to ctrl+z.

**Comment by sandy081** [comment]
@alexandrudima Can you please confirm that undo (Ctrl+z) action needs editor to be in focus?

**Comment by sandy081** [comment]
I checked that Editor undo, by default, needs editor in focus. I also checked that **Search view** is undo-ing the text after replace action. @sveinse Can you please confirm.

**Comment by sveinse** [comment]
I tested this on the 1.11.2 release, and it still behaves the same way as the two videos above indicate. The undo function of the text works if you manually focus the editor after pressing the replace button (in either search view) and then press Ctrl+Z.

**Comment by roblourens** [comment]
This now works for me as it should, pressing cmd+z with the search viewlet focused undoes the replace. Someone comment if it's still an issue.

**Comment by sveinse** [comment]
On which version is it fixed? It does still not work for me on 1.15.1 neither Ubuntu nor windows

**Comment by roblourens** [comment]
Oh, I see that it works on MacOS but doesn't on Windows

**Comment by roblourens** [comment]
Debugging on Mac, I see `vscode:runAction` called with 'undo': https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/window.ts#L116

Is this from Electron sending the 'undo' command when the cmd+z is not handled by the editor? I guess this is supposed to happen when a menu item is pressed, but is it also supposed to happen on keypress? @Tyriar? This doesn't happen on Windows. You get the same thing when focus is in the File Explorer or another viewlet.

On Windows, it sends the undo to the replace input box, and I can't figure out how that's happening.

**Comment by roblourens** [comment]
Ah this does come from electron's `menu.js`, which actually generates a 'click' event, even though it comes from a keypress.


![image](https://user-images.githubusercontent.com/323878/30138181-ba233f14-931b-11e7-9a7a-5919a7db802a.png)

**Comment by CherkashinSergey** [comment]
Can I clarify whether this feature will work on Ubuntu? Because I ran into the same problem in version 1.31.0 on Ubuntu.

**Comment by Nowaker** [comment]
Doesn't work on Linux either.

**Comment by zhyiyu** [comment]
> Agreed with @bpasero, but how about switching the focus to the editor when pressed on replace button? This might break the current good user experience while navigating and replacing using keyboard

Plus, if user has to click into the editor to undo the replacement, then he or she might lose the current cursor position in the script. I know after undoing, the cursor would return to that position anyway, but it is just a little scary to think of losing current position.

**Comment by Kiyos** [comment]
I am experiencing this behavior using version 1.44.2 on Windows when doing replacements using keyboard-mouse combo, i.e.:
1. Pressing Ctrl+H to bring up the Search/Replace popup window,
2. Pasting a search term into the search field, then clicking the Replace field and pasting the replacement string there,
3. Clicking on the “Replace” mini button to test the replacement before applying it to the whole document.
If the result is not what I needed (which happens too often with regular expressions 😉), I press Ctrl+Z hoping that my _last action would be undone_. But that doesn’t happen. Instead, nothing happens. For Ctrl+Z to work properly, the main window must be in focus, not the popup window or its controls, and an extra action is needed for that (a single mouse click into the main window, or going into the Edit menu and calling Undo from there, or a couple of Shift+Tab presses). It unreasonably complicates the workflow, IMO.

**Comment by jonas-frey** [comment]
From this thread I get the impression that there's a solution on macos that everybody's happy with? Why doesn't it work on linux? Isn't it the same codebase? Is it that hard to port over?

**Comment by andreamah** [comment]
I've tried undo/redo in the search input for windows/linux and it seems to work, so I believe that the original issue is resolved.
