### ISSUE TITLE
version1.9.0 " autowrap "  can't use

### ISSUE THREAD

**Issue by zhiqiang21** [Microsoft/vscode#20023]
- VSCode Version:1.9.0
- OS Version:10.12.3

Steps to Reproduce:

when i update vscode 1.9.0  i  try to  when i use autowrap ,it does't work. try shortcut it doen't work also;

**Comment by bpasero** [comment]
@zhiqiang21 can you share what command you are trying to execute?

**Comment by zhiqiang21** [comment]
i set keybindings.json  

![image](https://cloud.githubusercontent.com/assets/3990411/22647878/b90fe8a2-ecae-11e6-9b4c-67584444a349.png)

**Comment by zhiqiang21** [comment]
i set keybindings.json  

![image](https://cloud.githubusercontent.com/assets/3990411/22647878/b90fe8a2-ecae-11e6-9b4c-67584444a349.png)

**Comment by alexandrudima** [comment]
@zhiqiang21 That action writes `editor.wordWrap: true` or `editor.wordWrap: false` to the user settings. 

Please review the usage of `editor.wordWrap` and `editor.wrappingColumn` in your user and/or workspace settings (workspace settings overwrite user settings, it is recommended to not use a presentation option such as `editor.wordWrap` or `editor.wrappingColumn` in a workspace setting).

### Mastering line wrapping

There are two important settings in VS Code that control line wrapping.

* `editor.wrappingColumn` (300 by default)
* and `editor.wordWrap` (false by default)

It is important to understand the need for two distinct settings and how to tweak them to suit your use-case:

Examples (with explanations):

| `wordWrap` | `wrappingColumn` | Explanation |
|---|---|---|
| false | 300 | Lines will wrap at <code>300</code> |
| false | 0 | Lines will wrap at <code>viewport_column</code> |
| false | -1 | Lines will never wrap. |
| true | 300 | Lines will wrap at <code>min(viewport_column, 300)</code> |
| true | 0 | Lines will wrap at <code>viewport_column</code> |
| true | -1 | Lines will never wrap. |

**Comment by Bill-Stewart** [comment]
I think it is counter intuitive that any wrapping occurs when `wordWrap` is set to `false`. My opinion is that the behavior should be as follows:

**`wordWrap`** | **`wrappingColumn`** | **Explanation**
----------------|-------------------------|---------------
`false`               | any value                      | Lines will never wrap
`true`               | -1                                  | Lines will wrap at min(viewport_column, wrappingColumn)
`true`               | 0                                   | Lines will wrap at viewport_column
`true`               | >= 1                             | Lines will wrap at specified column

**Comment by zhiqiang21** [comment]
@alexandrudima @Bill-Stewart  yes  ,i set keybindings.json  


i want  line autowrap when wrappingColumn=80  

![image](https://cloud.githubusercontent.com/assets/3990411/22674836/381c98fc-ed1d-11e6-9126-bcdf3be182c5.png)


when i trigger "alt+shift+z" (the command of toggle word wrap) it will not autowrap .

but it not effective. when i use 1.8.1 this config is effective. please help me why?


![image](https://cloud.githubusercontent.com/assets/3990411/22674860/3f8b1014-ed1d-11e6-8089-9f94aebea975.png)

**Comment by alexandrudima** [comment]
@zhiqiang21 The command does nothing more than writing to your `settings.json` file. You can do what the command does by yourself by editing the `settings.json` file.

### Remove `editor.wrappingColumn` and `editor.wordWrap` from your workspace settings:
* `File` > `Preferences` > `Settings`
* Click on the `Workspace Settings`
* Ensure the `Workspace Settings` do not contain `editor.wrappingColumn`, nor `editor.wordWrap`:
![image](https://cloud.githubusercontent.com/assets/5047891/22689875/35ce96a2-ed33-11e6-90d2-cc3d07c05359.png)

### Open user settings and observe what the action does
* `File` > `Preferences` > `Settings`
* Click on the `User Settings`
* Execute the action and observe that all the action does is change `editor.wordWrap` in the user settings. You can edit that value by yourself, but the action does it for you, even when the settings are not visible.
![word-wrap](https://cloud.githubusercontent.com/assets/5047891/22689993/c46048a2-ed33-11e6-97ad-514ba9a5725e.gif)
