### ISSUE TITLE
Error when trying to open release notes

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#20029]
- VSCode Version: Code - Insiders 1.10.0-insider (ad605ea39a832e4be2cbf77670781654056ef027, 2017-02-06T07:10:53.676Z)
- OS Version: Windows_NT ia32 10.0.15025
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|theme-dracula|dracula-theme|1.2.5|
|vscode-great-icons|emmanuelbeziat|1.1.38|
|Theme-azure|gerane|0.0.2|
|theme-material-theme|jprestidge|1.0.1|
|vs-color-picker|lihui|0.3.2|
|Theme-MaterialKit|ms-vscode|0.1.1|
|view-in-browser|qinjia|0.0.4|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|eval|Stormspirit|0.0.5|
|omnipascal|Wosi|0.12.0|

---

Steps to Reproduce:

1. Open "Release Notes" from the Help menu

An error shows up: `"unable to open 'Release Notes: 1.10.0-insider': Cannot read property 'replace' of null`

**Comment by stefan-kern** [comment]
i'm having the same issue on ubuntu 16.04 (vscode version 1.10.0-1486365175_amd64).

**Comment by joaomoreno** [comment]
Great catch!
