### ISSUE TITLE
Allow to contribute IntelliSense for string only JSON settings

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#20028]
My scenario is that I have a setting (`window.title`) which I want to provide IntelliSense for because the value of this setting can have variables (e.g. `$(activeFile)`).

I tried two different strategies:

1. from the main side, add a `JSONWorkerContribution` to our JSON server and implement `collectValueCompletions`, e.g. like this:

```typescript
public collectValueCompletions(resource: string, location: JSONPath, currentKey: string, result: CompletionsCollector): Thenable<any> {
    if (this.isSettingsFile(resource) && location.length === 1 && location[0] === 'window.title') {
        result.add({ kind: CompletionItemKind.Value, label: localize('trueLabel', "$(activeFile)"), filterText: 'true', insertText: 'true', documentation: localize('activeFileDescription', "Enable activeFile.") });
    }

    return null;
} 
```

=> I am not getting a completion when I do so

![image](https://cloud.githubusercontent.com/assets/900690/22643073/54686c04-ec5d-11e6-9db2-36161089cb7e.png)

2. do it proper and from the `config-editing` extension: this is https://github.com/Microsoft/vscode/issues/20030

**Comment by bpasero** [comment]
We should probably ignore this issue and fix https://github.com/Microsoft/vscode/issues/20030 in favour because that is the right story.

**Comment by aeschli** [comment]
Closing, as we don't want any setting specific code in the JSON language server.
