### ISSUE TITLE
Quick fix keybinding style don't align with established pattern

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#200258]
![image](https://github.com/microsoft/vscode/assets/2193314/3a0363e0-085d-47b7-ba33-efacb516592c)

command palette:

![image](https://github.com/microsoft/vscode/assets/2193314/55def7b8-b7a8-44fb-ac67-622b18b58b3d)

keybinding editor:

![image](https://github.com/microsoft/vscode/assets/2193314/dd060b01-508c-4717-bbe3-be3f958b5dc1)

**Comment by justschen** [comment]
@Tyriar I'm on Mac, so there are no `+` in the examples below:

<img width="493" alt="Screenshot 2023-12-07 at 2 29 34 PM" src="https://github.com/microsoft/vscode/assets/54879025/8cfab08e-884f-4e08-bde9-b5e56c000a30">
<img width="355" alt="Screenshot 2023-12-07 at 2 29 18 PM" src="https://github.com/microsoft/vscode/assets/54879025/c2e14333-556d-45f2-9ce9-a4bc2c8944ff">

Thoughts on if we need to have a `disabled` version of keybindings, leave as is, or just not show if disabled? I don't think there are example of menu options that are disabled that have this kind of keybinding.
