### ISSUE TITLE
Restriction of injection grammars for specific filename

### ISSUE THREAD

**Issue by anticultist** [microsoft/vscode#200248]
I can not find a way to restrict injected syntax highlighting to specific files like `foo.json`.

In my use case I want extend syntax highlighting in dictionary string values of specific JSON files with a fixed file name. The syntax highlighting works fine but it is also enabled in other JSON files I do not want them to be enabled. Is there a way to restrict injected syntax highlighting to a specific file name or do I have to create a language server?

**Comment by RedCMD** [comment]
Currently there is no easy way
Either create a language server and use semantic highlighting (which won't have bracket highlighting support)
or
create a new `languageId`; allowing you to define `"filenamePatterns"`
Include `source.json` and then you can inject into your `languageId`

**Comment by anticultist** [comment]
Thanks for the quick response!

I try to stick with the json languageId because I want to keep other nice features like json schema support. I suppose it is only enabled for the json languageId.
So it sounds like I have to go the language server route, which I thought I could try to avoid.
Is there any chance that restriction of injected grammars for specific filename could be considered as a new feature?

**Comment by RedCMD** [comment]
I am trying to get this through https://github.com/microsoft/vscode/pull/198583 to enable schema support etc for other json `languageId`'s

**Comment by aeschli** [comment]
Using semantic highlighting sounds like the best approach to me.

**Comment by aeschli** [comment]
Closing the issue. No plans to make injections per file name.
