### ISSUE TITLE
Endless loop when discard changes inside a notebook

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#200223]
* open notebook
* make inline chat changes
* select "Discard"
* 🧊 the editor will freeze, stuck in an endless loop in `_undoModelUntil`

**Comment by jrieken** [comment]
This doesn't reproduce but I had this with insiders and I could see that `canUndo` would return `true` and `undo` wouldn't do anything, e.g it would _not_ change the alternative version id. 

@rebornix This is notebook specific and the debugger did show me that parts of undo seems to be async. I wonder if this should be exposed in the undo-method that I am calling and that's the cause for this

**Comment by alexdima** [comment]
I did a quick look at the source code in `UndoRedoService.canUndo` and that looks OK to me. @jrieken `TextModel.undo()` returns `void | Promise<void>`. I notice the loop doesn't await the result in case a promise is returned. Could that be the right fix here?

**Comment by jrieken** [comment]
I missed it returning a promise. Might be the right fix here but I also wasn't able reproduce and only debugged this from insiders once.
