### ISSUE TITLE
Jupyter Notebook progress bar is broken with Julia (not Python)

### ISSUE THREAD

**Issue by nunofachada** [microsoft/vscode#200261]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Progress bars on Julia Jupyter notebooks are broken, as they were previously in [Python](https://github.com/microsoft/vscode/issues/146397). This is what happens:

![image](https://user-images.githubusercontent.com/3018963/198680524-fffd63dd-babc-4def-9acb-6b6f8b77763f.png)
![image](https://user-images.githubusercontent.com/3018963/198680031-a3780621-c098-43c7-ac02-ddbf52102bf2.png)

This is what should happen:

![image](https://user-images.githubusercontent.com/3018963/198680660-fe01bdf0-7a7a-494d-938b-2a3d291d90c6.png)

This also happens with Julia's [ProgressBars.jl](https://juliapackages.com/p/progressbars) package.

This **does not** happen in Python, with [tdqm](https://pypi.org/project/tqdm/) for example. I.e., it works as expected in Python.

Here's the example code for demonstrating this behavior:

```julia
import Pkg; Pkg.add("ProgressMeter")
```

```julia
using ProgressMeter

@showprogress for i in 1:10
    sleep(0.8)
end
```

### VS Code Version

Version: 1.72.2 Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075 Date: 2022-10-12T22:16:26.920Z Electron: 19.0.17 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Linux x64 5.15.0-52-generic snap Sandboxed: No

### Jupyter Extension Version

v2022.9.1202862440

### Jupyter logs

```shell
No logs are generated when running the notebook.
```

### Coding Language and Runtime Version

Julia 1.6.7

### Language Extension Version (if applicable)

Julia extension v1.38.2

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
it sounds like was fixed externally, but let me know if that's not the case
