### ISSUE TITLE
Double-byte file names are not displayed correctly in Markdown editor

### ISSUE THREAD

**Issue by ayatokura** [microsoft/vscode#200213]
Type: <b>Bug</b>

# What's the problem
File names do not load properly when calling double-byte filenames in Markdown

# What's the expected result
It would be great if Markdown could show double-byte file names when we load them up, just like in VS Code Explorer

# How to reproduce
1. Create Markdown file
2. Drag-and-drop to embed double-byte files
3. File names do not load properly when calling double-byte filenames in Markdown

# Screenshot
![image](https://github.com/microsoft/vscode/assets/12283147/558cde5a-3af3-4e04-bc18-3d5ad4ff8da6)

VS Code version: Code 1.84.2 (Universal) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 9da1c14d-d8a1-4f0e-a8f6-556418b9b65d --crash-reporter-id 9da1c14d-d8a1-4f0e-a8f6-556418b9b65d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.14.0
markdown-preview-github-styles|bie|2.0.3
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
codespaces|Git|1.16.2
copilot|Git|1.139.0
copilot-chat|Git|0.10.2
vscode-pull-request-github|Git|0.76.1
vscode-power-mode|hoo|3.0.2
vsc-python-indent|Kev|1.18.0
node-module-intellisense|lei|1.5.0
vscode-language-pack-ja|MS-|1.84.2023111509
vscode-kubernetes-tools|ms-|1.3.15
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
jupyter|ms-|2023.10.1100000000
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.321.0
atom-keybindings|ms-|3.3.0
vsliveshare|ms-|1.0.5896
autodocstring|njp|0.6.1
vscode-yaml|red|1.14.0
code-spell-checker|str|3.0.1
vscode-pets|ton|1.25.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
ch094911:30880123
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss2:30886141
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016cf:30886111
dsvsc017:30886112
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by mjbvz** [comment]
Can you share an example file name as text so I can try to easily reproduce this

Also is the issue that the file doesn't load in the preview or that the wrong path is inserted when you drop the file into the markdown editor

**Comment by mjbvz** [comment]
Thanks @ayatokura! Will check in a fix for the next insiders build
