### ISSUE TITLE
Unable to open file at a line number from the terminal if filename ends with a period

### ISSUE THREAD

**Issue by sparxooo** [microsoft/vscode#200257]
Type: <b>Bug</b>

When opening a file:line number link (ctrl-click) from the terminal that ends with a period, in the format "File.tsx:25", VSCode does not find any results as the period is included with the line number. Removing the period finds the result successfully.

![Screenshot 2023-12-07 174701](https://github.com/microsoft/vscode/assets/25756001/ff80b739-047e-4fb5-a58e-6b3061d9071d)

If you remove the period, then the search functions successfully, as expected.

![Screenshot 2023-12-07 174714](https://github.com/microsoft/vscode/assets/25756001/f0f93686-8a80-483e-bd38-33ab33cdef33)

The trailing period should be ignored, as it is not part of the line number.

VS Code version: Code - Insiders 1.85.0-insider (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T11:15:22.766Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.27GB free)|
|Process Argv|--crash-reporter-id e7ee9cdf-761c-4795-a9fd-a3471e3f552b|
|Screen Reader|no|
|VM|36%|

|Item|Value|
|---|---|
|Remote|Dev Container: App|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 3600)|
|Memory (System)|15.59GB (11.25GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|4.4.3
codespaces|Git|1.16.4
remotehub|Git|0.62.0
remote-containers|ms-|0.328.0
remote-wsl|ms-|0.81.8
azure-repos|ms-|0.38.0
remote-repositories|ms-|0.40.0
vscode-eslint|dba|2.4.2
prettier-vscode|esb|10.1.0
copilot|Git|1.140.0
copilot-chat|Git|0.11.0
vscode-docker|ms-|1.28.0
prisma|Pri|5.7.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
2i9eh265:30646982
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30901775
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by joyceerhl** [comment]
I can't reproduce the described behavior: 
<img width="476" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/9395ec71-0232-43d5-ae24-fda9c5ce37ef">
Do you have a project that this consistently occurs in, e.g. if you are using custom tasks?

**Comment by sparxooo** [comment]
> I can't reproduce the described behavior: <img alt="image" width="476" src="https://private-user-images.githubusercontent.com/30305945/290672372-9395ec71-0232-43d5-ae24-fda9c5ce37ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1OTc2MzQsIm5iZiI6MTcwMjU5NzMzNCwicGF0aCI6Ii8zMDMwNTk0NS8yOTA2NzIzNzItOTM5NWVjNzEtMDIzMi00M2Q1LWFlMjQtZmRhOWM1Y2UzN2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDIzNDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNTAxZDU5NjZmOTI1MTMwMjE5NTY3ZTYyZWUyNjY4NzAxYThmMTc3MzA5Mzg2M2Q3Y2E3Nzk4ZjFhZTY1NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7jJQeZSi0GRL3C7c8OJxiTdLOSO1maM-Dy0T_USHHy4"> Do you have a project that this consistently occurs in, e.g. if you are using custom tasks?

Hi joyceerhl,

The links are present, and highlighted correctly (with the underline), and can be clicked, but they don't seem to function properly.

- Line numbers not trailed by a period all seem to function properly.
- Single digit line numbers trailed by a period will open the correct file, however will not place the caret on the correct line.
- Double+ digit line numbers trailed by a period will not open the file, showing the "No matching results" text.

I've tested this on a clean 1.85.1 install on my Windows machine and Github Codespaces (also 1.85.1), and it does appear to be misbehaving. There is a repro repo here: https://github.com/sparxooo/PoCvscodebug

Thanks :)

sparxooo

**Comment by joyceerhl** [comment]
I do repro this in a codespace, thanks for the detailed steps! 

<img width="780" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/d54277d9-405c-4222-86bd-e1b012f3b6c8">

**Comment by sparxooo** [comment]
Interestingly, I think I found why single digit lines still open the correct file, and that's because the replace regex 
`text = text.replace(/:[^\\/][^\d]+$/, '');` in terminalLinkOpeners.ts:111 strips off the line/column number if it is a single digit, and then has a trailing period, but not if it's double+ digits.

![Screenshot 2023-12-15 033526](https://github.com/microsoft/vscode/assets/25756001/65b7aa0c-5b9b-44c9-b2e1-4468c79a5417) ![Screenshot 2023-12-15 033411](https://github.com/microsoft/vscode/assets/25756001/a0281249-4997-4e8a-9d17-9b207de10603) ![Screenshot 2023-12-15 033458](https://github.com/microsoft/vscode/assets/25756001/a0222ac1-bb7c-432b-b357-27301f1364e4) ![Screenshot 2023-12-15 033506](https://github.com/microsoft/vscode/assets/25756001/4f401406-efca-45f6-a86d-44807ea6d419)

Not a fix, but might be useful info.
