### ISSUE TITLE
Rejecting in Promise.race will trigger debug pause

### ISSUE THREAD

**Issue by t123yh** [Microsoft/vscode#20025]
- VSCode Version: 1.8.1 (commit ee428b0)
- OS Version: Ubuntu 16.04.1

The code:
```js
let p1 = new Promise(function(resolve, reject) {
    setTimeout(resolve, 100, 'OK!!!');
});
let p2 = new Promise(function(resolve, reject) {
    setTimeout(reject, 300, new Error('Operation timed out'));
});

Promise.race([p3, p2]).then(function(result) {
    console.log('Got result: %s', result);
}, function (error) {
    console.log('Got error: %s', error.message);
});
```

(It's almost the same as the example in Mozilla Develpoer Network)

This code is expected to give output `Got result: OK!!!`, and it works fine in Node.js from command line. Node.js will not give any warnings.

However, when debugging this snippet in VS Code, execution will be interrupted for the timed-out error. It's already catched by the `race` sentence, so I wonder if this should not happen.

**Comment by weinand** [comment]
dup of #5213
