### ISSUE TITLE
Ctrl+W closes tab with terminal

### ISSUE THREAD

**Issue by jhasse** [microsoft/vscode#200380]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.0
af28b32d7e553898b2a91af498b1fb666fdebe0c
x64
- OS Version: GNOME, Fedora Linux 6.6.4-200.fc39.x86_64

Steps to Reproduce:

1. Open a terminal as a tab.
2. Press Ctrl+W to delete word in shell.
3. Terminal tab closes.

This didn't happen before 1.85.0.

**Comment by meganrogge** [comment]
This is by design. You can alter the keybinding for `workbench.action.terminal.killEditor` if you want to.
