### ISSUE TITLE
In .NET Core projects, VScode should check if the referenced project has been updated

### ISSUE THREAD

**Issue by SWY1985** [Microsoft/vscode#20036]
- VSCode Version: 1.9
- OS Version: Xubuntu 16.04

Steps to Reproduce:

1. Create two .NET core projects (ie. Console app and .NET Standard library) in separate workspaces
2. Reference the library project from the console app project
3. Make change to library (ie. make new class)
4. The Console app project remembers the previously compiled version and reports errors if I try to reference the new class, until I close and open te workspace

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
