### ISSUE TITLE
Intelisense not available in Java projects.. Taking forever "Starting Java Language Server"

### ISSUE THREAD

**Issue by majiccode** [Microsoft/vscode#20034]
- 1.9.0
- Windows 10

Steps to Reproduce:

I'm using the extension "Language Support for Java by RedHat".

1. Open a folder housing several reasonably large java projects.
      c:\git-repos\
                         \repo1
                         \repo2
                         \repo3
                         ....
    Not all repositories are java but the the majority are.
2. Open a java source file from one of the projects (c:\git-repos\repo1\src\main\java\com\...\SomeJavaFile.Java) and look at the intelisense for anything.

"Loading..." will appear in the tooltip and the status bar you will see "Starting Java Language Server..." I've waited over 30 minutes and still see this with no intelisense available. The projects are not insanely huge. This has worked on a tiny test project outside the folder containing lots of java project repositories,

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
