### ISSUE TITLE
The debug console content is cleared when debug console font size is changed

### ISSUE THREAD

**Issue by StaringInfinity** [microsoft/vscode#200369]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.0
- OS Version: win10

Steps to Reproduce:

1. Debug a C/C++ program. 
2. Press "Ctrl +j" to Toggle Panel invisible. Change the debug console font size, then toggle panel visible. It can be seen the debug console content is cleared
3. Here is a video demonstration

https://github.com/microsoft/vscode/assets/49320365/558089b9-cedd-4fe0-a1a6-6d29fde3a7a6

**Comment by roblourens** [comment]
Weird bug. I can repro it

**Comment by lramos15** [comment]
Still repros

**Comment by roblourens** [comment]
I see that this works sometimes, but sometimes it still clears the debug console content.

**Comment by manav014** [comment]
I would like to work on this. @roblourens Can you please assign this to me?

**Comment by roblourens** [comment]
Feel free to send a PR if you'd like

**Comment by manav014** [comment]
Tried to reproduce this on the latest stable release and it seems like this is already fixed.
https://github.com/user-attachments/assets/9a5343fa-a3c3-450f-9259-77e16e0b1a03

**Comment by roblourens** [comment]
The original steps:

> Press "Ctrl +j" to Toggle Panel invisible. Change the debug console font size, then toggle panel visible. It can be seen the debug console content is cleared

**Comment by BABA983** [comment]
> The original steps:
> 
> > Press "Ctrl +j" to Toggle Panel invisible. Change the debug console font size, then toggle panel visible. It can be seen the debug console content is cleared

I fire a [PR](https://github.com/microsoft/vscode/pull/224694) to fix this problem. But I'm not sure if it is an ideal approach. Any feedback would be helpful 😄.
