### ISSUE TITLE
git refresh with big latency

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#20035]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.5|
|code-runner|formulahendry|0.6.8|
|beautify|HookyQR|0.7.3|
|vscode-hexdump|slevesque|1.1.4|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1. setup "git.autorefresh": false, "git.autofetch": false, 
2. open git panel
3. press "Refresh" button

Expected: immediately refresh process with progress line animation.

Actual: refresh process with progress line animation only after 5 seconds. But in task manager some service in services group take 100% immediately.

**Comment by joaomoreno** [comment]
How big is your repository? Does running `git status` in the command line also take a bit long?

**Comment by SailorMax** [comment]
Repository is not big.
`git status` take 1 second.

**Comment by joaomoreno** [comment]
What about `git status -u`?

**Comment by SailorMax** [comment]
`git status -u` take 1 second.

**Comment by joaomoreno** [comment]
So... In the task manager, or maybe [Process Hacker](http://processhacker.sourceforge.net/) (which gives you a bit more detail), what process seems to take 100% CPU and longer than 5 seconds?

**Comment by SailorMax** [comment]
svchost.exe :) I don't know hot to detect its name in Windows 10 < Creative update.

Only clue gives Process Explorer:
Autostart location of service: HKLM\System\CurrentControlSet\Services\WpnUserService_3596b
WpnUserService = Windows Push Notifications User Service
Later will dig more if you have some tools.

**Comment by joaomoreno** [comment]
That doesn't seem to be a Code issue at all. What animation only shows up after 5 seconds?

**Comment by SailorMax** [comment]
Running horizontal line before "Message" input field.
And "Commit all" button disable only after 5 seconds.
And clock icon showing on Git tab only after 5 seconds.

**Comment by joaomoreno** [comment]
What are your machine specs?

**Comment by SailorMax** [comment]
https://www.cnet.com/products/dell-optiplex-3010-core-i5-3470-3-2-ghz-4-gb-250-gb/specs/

**Comment by joaomoreno** [comment]
Can you somehow record what you see? Maybe using http://www.cockos.com/licecap/?

**Comment by SailorMax** [comment]
record: https://dropfile.to/DGjA3mr

**Comment by joaomoreno** [comment]
Can you give this a read? https://github.com/msysgit/msysgit/wiki/Diagnosing-why-Git-is-so-slow

**Comment by SailorMax** [comment]
intermediate data:
Process Monitor result:
time -- process -- new subprocess
**[press "refresh" button]**
13:23:11:6326517 -- code.exe -- "C:\Program Files\Git\cmd\git.exe" status -z -u
13:23:13:7957393 -- code.exe -- "C:\Program Files\Git\cmd\git.exe" symbolic-ref --short HEAD
13:23:14:2325946 -- code.exe -- "C:\Program Files\Git\cmd\git.exe" rev-parse dev
13:23:14:7305046 -- code.exe -- "C:\Program Files\Git\cmd\git.exe" rev-parse --symbolic-full-name --abbrev-ref dev@{u}
13:23:15:2234722 -- code.exe -- "C:\Program Files\Git\cmd\git.exe" rev-list --left-right dev...origin/dev
13:23:15:7957300 -- code.exe -- "C:\Program Files\Git\cmd\git.exe" for-each-ref --format "%(refname) %(objectname)"
13:23:15:8320369 -- code.exe -- "C:\Program Files\Git\cmd\git.exe" remote --verbose
**[and only here VSCode start to display animation, disable "commit all" button and setup clock icon on git-tab]**
13:23:16:3782145 -- code.exe -- "C:\Program Files\Git\cmd\git.exe" status -z -u
...

Why setup command animation and status icon so late?
