### ISSUE TITLE
angular debugging in chrome stopped working

### ISSUE THREAD

**Issue by DipsFrontJim** [microsoft/vscode#200318]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85
- OS Version: Windows 10 Enterprise 10.0.19045 Build 19045

Steps to Reproduce:
1. Use Javascript Debugger (Nightly) from 2023.12.717 extension
2. upgrade to version Visual studio code to 1.85
3. start debugging
4. chrome opens, and closes within a couple of seconds. No errors

**Comment by DipsFrontJim** [comment]
If I downgrade Javascript Debugger (Nightly) from 2023.12.717 to 2023.12.117, chrome doesn't close anymore.  If I disable the debugger and also disable the firefox debugger, I get  a message in Run and debug saying "All debug extensions are disabled. Enable a debug extension or install a new one from the markedplace"

Why is this necessary. My colleague here can run in chrome without any extensions installed. I don't get this :(

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1900, fixed in the next nightly out in ~30m
