### ISSUE TITLE
Mark mode in the terminal similar to Windows terminal

### ISSUE THREAD

**Issue by erikgrahn13** [microsoft/vscode#200338]
Being able to to use similar features as "mark mode" in Windows terminal to be able to navigate the terminal and select text without the need of using the mouse. For example, "mark mode" uses ctrl+shift+m in Windows Terminal to enter the mode where you will be able to navigate the terminal with keyboard.

**Comment by meganrogge** [comment]
You can do this in terminals with shell integration already via `ctrl/cmd+shift+up/down arrow`
