### ISSUE TITLE
Code collapse

### ISSUE THREAD

**Issue by jaswantmandloi** [Microsoft/vscode#20037]
Feature Request 

Please introduce the code collapse functionality in editor. It is very useful with the big file codes.

**Comment by bpasero** [comment]
@jaswantmandloi we do support code folding. Maybe you disabled it in settings?

**Comment by jaswantmandloi** [comment]
Hello there,

Thanks for your quick reply.
There is option for code collapse.
But is there any way to collapse whole code simultaneously with sort cut
keys?

Please let me know if there is option?

Thanks,
Jaswant

**Comment by bpasero** [comment]
@jaswantmandloi so you are asking for keybindings? You find them in the command palette when you search for "fold..."
