### ISSUE TITLE
why can't found c# language type when i run the instance of vscode that build with vscode source?

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#2003]
When i build vscode source code and use ".\scripts\code.bat" to start the instance of vscode, i found i have found c# type when i open language mode selector ,anyone can help me?

![unablefoundc](https://cloud.githubusercontent.com/assets/15098626/12319657/b49db662-bade-11e5-9029-14e0e30f4b8f.png)

**Comment by isidorn** [comment]
C# comes in as an extension. 
@jrieken how to get it in code.bat?

**Comment by jrieken** [comment]
@BleyChen The source is currently in transit and will move to the OmniSharp org. What you need to do is this:

* find the extension folder for ./script/code in your _home_ dir, like `~/.code-oss-build-dev/extension`
* add a sym link that point to the omnisharp extension (for now from your installation, soon from the github project)

**Comment by BleyChen** [comment]
@jrieken  could you please use the screenshot to  tell me the detail steps how to do it ,thank you!!!
