### ISSUE TITLE
"Go to symbol" looks like only take care of upper cases

### ISSUE THREAD

**Issue by hansanghoon** [Microsoft/vscode#20039]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.7.3|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-dash|deerawan|1.3.0|
|bower|donjayamanne|0.0.3|
|vscode-babel-coloring|dzannotti|0.0.4|
|debugger-for-chrome|msjsdiag|2.5.1|
|polymer-ide|polymer|0.3.0|
|java|redhat|0.0.9|
|elm|sbrink|0.8.3|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. create js file with content as below
```javascript
function helloWorld1() {}
function hElloWorld2() {}
function helloWOrld3() {}
function hElloWOrld4() {}
```
2. type `eo` in `cmd+shift+o` and `cmd+t` with case combinations

|typed char|`@`|`#`|
|---|---|---|
|eo|![image](https://cloud.githubusercontent.com/assets/3644666/22648530/7249af46-ecba-11e6-96cc-b1e2ceac13ee.png)|![image](https://cloud.githubusercontent.com/assets/3644666/22648435/0512f8c4-ecba-11e6-8d0a-b9bc5156ee05.png)|
|eO|![image](https://cloud.githubusercontent.com/assets/3644666/22648444/10b838ec-ecba-11e6-9c1b-340197bfe052.png)|![image](https://cloud.githubusercontent.com/assets/3644666/22648452/1e77641c-ecba-11e6-92bc-f09c88028097.png)|
|Eo|![image](https://cloud.githubusercontent.com/assets/3644666/22648462/2dccf7a6-ecba-11e6-8fc6-d9cc8e64f0b0.png)|![image](https://cloud.githubusercontent.com/assets/3644666/22648470/3701f416-ecba-11e6-85d9-7c3d2fcc6848.png)|
|EO|![image](https://cloud.githubusercontent.com/assets/3644666/22648479/40272264-ecba-11e6-99b1-189671954600.png)|![image](https://cloud.githubusercontent.com/assets/3644666/22648490/4af00422-ecba-11e6-8162-2a629fb3fe8e.png)|

I only ran tests for a single file case, but something isn't right... only `hElloWOrld4` got attention and even worse, `Go to symbol in workspace` sometimes shows no result.

**Comment by bpasero** [comment]
@aeschli for if we do something bad in the open symbol filtering and @waderyan to see if this is a bug in TypeScript actually. I suspect the latter.

**Comment by aeschli** [comment]
@bpasero That's a long time ago since I touched that code. I suggest @mjbvz and @waderyan have a look.

**Comment by mjbvz** [comment]
The root cause is that workspace and document symbol search use different filtering logic.

For symbol search in a document, we take all symbols in the document and filter the results down on the VSCode side. For workspace symbol search, we send a search term to TypeScript who returns an already filtered list of results

I've opened https://github.com/Microsoft/TypeScript/issues/13909 to track fuzzier matches on the TypeScript side
