### ISSUE TITLE
GitHub is the ONLY login option

### ISSUE THREAD

**Issue by paturikaustubh** [microsoft/vscode#200385]
Type: <b>Bug</b>

I am trying to login using my Microsoft account as I have a profile synced to that account. But unintentionally I first logged in to my GitHub account and now I am unable to log in through my Microsoft account. Every time I try to log in from the Profile section, it always redirects me to the GitHub login page. It doesn't show the options to login in the VS Code.

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12450H (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (10.34GB free)|
|Process Argv|--crash-reporter-id 3ad7f61c-7882-49c7-af69-abb07301bea7|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

</details>

**Comment by sandy081** [comment]
Check this to switch accounts - https://code.visualstudio.com/docs/editor/settings-sync#_switching-accounts
