### ISSUE TITLE
Keyboard shortcut for Next / Previous Change in diff view

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#20038]
In the diff (compare) view, e.g., after clicking on a changed file in the Git sidebar, it would be useful to have keyboard shortcuts for Next Change / Previous Change actions. Those are currently just clickable arrow in the top right.

**Comment by bpasero** [comment]
You can assign `workbench.action.compareEditor.nextChange` and `workbench.action.compareEditor.previousChange`

**Comment by borekb** [comment]
🤦‍♂️ how could I overlook those.. Thanks!

**Comment by borekb** [comment]
@bpasero Is there a suitable ["when" context](https://code.visualstudio.com/docs/customization/keybindings#_when-clause-contexts) for this?

**Comment by bpasero** [comment]
@borekb yes, it is called `textCompareEditorVisible`
