### ISSUE TITLE
SCM Incoming/Outgoing: stick to bottom

### ISSUE THREAD

**Issue by EcksDy** [microsoft/vscode#200345]
Heya!
I'd like to have the ability to set the new `Incoming/Outgoing` section in the SCM, to be sticky near the bottom. I find it very useful but somewhat cluttered right now, as changes that aren't related to the current change are visually close to the actual current changes.

Most of the time there's more than enough vertical real estate, so it could be a nice addition that helps with visual separation of the two sections.

**Comment by nicolaerario** [comment]
Hi, I agree with @EcksDy 
We could have behavior like in the file explorer, where `timeline` and `outline` are down and usable on need. It would also be more consistent with the rest of the sections.

**Comment by kaleidawave** [comment]
I agree. It's a useful view but because it sits in the same place as where *change files* are it trips me up as I think there are still uncommitted files.

**Comment by lszomoru** [comment]
Closing this as the "Incoming/Outgoing" section has been removed.
