### ISSUE TITLE
The 'Generate commit message' button is not displaying.

### ISSUE THREAD

**Issue by BorovlevAS** [microsoft/vscode#200375]
- VS Code Version: 1.85.0
- OS Version: Ubuntu 20.04 x64

1. Make some changes in the project
2. Stage changes
3. There should have been a "sparkle" button, but it's not there.
![2023-12-08_02-39](https://github.com/microsoft/vscode-copilot-release/assets/101502943/960b1243-c9a8-4807-8b21-ebcc162c89ee)

Copilot is working, copilot chat is also working

**Comment by lszomoru** [comment]
@BorovlevAS, @SkyDev125, could you please share the version of the Copilot extension?

**Comment by SkyDev125** [comment]
Github Copilot: v1.141.0
Github Copilot Chat: v0.11.0
GitHub Copilot Labs: v0.17.1121
<img width="248" alt="image" src="https://github.com/microsoft/vscode/assets/41944315/2fbc0f47-3144-455d-9b61-6a1a5feaa158">
<img width="250" alt="image" src="https://github.com/microsoft/vscode/assets/41944315/a3fed64f-204d-4772-8057-68e2dc4e1c85">

**Comment by BorovlevAS** [comment]
> @BorovlevAS, @SkyDev125, could you please share the version of the Copilot extension?

Copilot: v1.141.0
Copilot Chat: v0.11.0

**Comment by lszomoru** [comment]
Thank you! I have found the regression, and will be working on a fix.

**Comment by drementer** [comment]
Same issiue :'(

GitHub Copilot Chat v0.11.0
GitHub Copilot v1.141.0
GitLens — Git supercharged v14.5.2
GitHub Copilot Labs v0.17.1121
GitHub Pull Requests and Issues v0.76.1

<img width="1214" alt="image" src="https://github.com/microsoft/vscode/assets/48869708/743c385c-349b-46e8-ae5a-d4af805edcb7">
<img width="414" alt="image" src="https://github.com/microsoft/vscode/assets/48869708/ff4a9909-2678-4d88-88bc-e2a92caeecc9">

**Comment by lszomoru** [comment]
@BorovlevAS, @SkyDev125, @drementer, could you please download the latest VS Code Insiders release as it contains a fix for this issue. It would be great if any of you could confirm that the fix is working as expected. Thank you!

**Comment by mooch443** [comment]
It did for me. Thank you!
