### ISSUE TITLE
Starting a program to attach to a node process is not showing any progress

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#20031]
In VS code development workspace
- Go to debug view in VS Code with VS code dev workspace
- Start launching the program `Attach to Shared Process`

You do not see any progress and after 10s it shows an error

**Comment by weinand** [comment]
if there is no server listening on a port, it is difficult to provide progress.
But we could inform the user that we trying to connect to a port.
But this would require modifications to the DAP.
