### ISSUE TITLE
November 2023 Recovery 1

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#200399]
- [x] Create a milestone `<Month> <Year> Recovery <1|2|3>` **endgame champion**
- [x] Bump the version number **endgame champion**
- [x] [🔖candidate issues](https://github.com/issues?q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fmonaco-editor+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-anycode+repo%3Amicrosoft%2Fvscode-copilot+repo%3Amicrosoft%2Fvscode-copilot-release+repo%3Amicrosoft%2Fvscode-dev+repo%3Amicrosoft%2Fvscode-dev-chrome-launcher+repo%3Amicrosoft%2Fvscode-emmet-helper+repo%3Amicrosoft%2Fvscode-extension-telemetry+repo%3Amicrosoft%2Fvscode-github-issue-notebooks+repo%3Amicrosoft%2Fvscode-hexeditor+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-js-debug+repo%3Amicrosoft%2Fvscode-jupyter+repo%3Amicrosoft%2Fvscode-jupyter-internal+repo%3Amicrosoft%2Fvscode-l10n+repo%3Amicrosoft%2Fvscode-livepreview+repo%3Amicrosoft%2Fvscode-pull-request-github+repo%3Amicrosoft%2Fvscode-python+repo%3Amicrosoft%2Fvscode-python-debugger+repo%3Amicrosoft%2Fvscode-references-view+repo%3Amicrosoft%2Fvscode-remote-release+repo%3Amicrosoft%2Fvscode-remote-repositories-github+repo%3Amicrosoft%2Fvscode-remote-tunnels+repo%3Amicrosoft%2Fvscode-remotehub+repo%3Amicrosoft%2Fvscode-settings-sync-server+repo%3Amicrosoft%2Fvscode-unpkg+repo%3Amicrosoft%2Fvscode-vsce+milestone%3A%22November+2023+Recovery+1%22+)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `main`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **endgame champion**
- [x] Issues are verified on `stable` build and the `verified` label is added **endgame champion**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **endgame champion**
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [x] [Sanity Testing](https://github.com/microsoft/vscode/wiki/Sanity-Check)
  - [x] Windows 64 bit @dbaeumer 
    - [x] System Installer
    - [x] User Installer
    - [x] Archive
    - [x] Server
    - [x] CLI
  - [x] Windows ARM64 @joaomoreno 
    - [x] System Installer
    - [x] User Installer
    - [x] Archive
    - [x] CLI
  - [x] macOS Intel @bpasero 
    - [x] Archive
    - [x] Universal Archive
    - [x] Server
    - [x] CLI
  - [x] macOS ARM64 @jrieken 
    - [x] Archive
    - [x] Universal Archive
    - [x] Server
    - [x] CLI
  - [x] Linux x64 @chrmarti 
    - [x] Archive
    - [x] DEB
    - [x] RPM
    - [x] Snap
  - [x] Linux Server @alex00 _(can be tested from any OS with Docker)_
    - [x] x64
    - [x] ARM32
    - [x] ARM64
    - [x] x64 Alpine
    - [x] ARM64 Alpine
  - [x] Linux CLI @aiday-mar  _(can be tested from any OS with Docker)_
    - [x] x64
    - [x] ARM32
    - [x] ARM64
    - [x] x64 Alpine
    - [x] ARM64 Alpine
- [x] Publish website **@gregvanl**
- [x] Publish stable build **endgame champion**
- [x] Create an official release **endgame champion**
  - [x] Create a tag (make sure you pull the release branch first): `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)
- [x] Close the milestone on [GitHub](https://github.com/microsoft/vscode/milestones) **endgame champion**

**Comment by gjsjohnmurray** [comment]
Please add the year to the issue title.

**Comment by Nevro** [comment]
What is point of release if there is no any changes?

comparison: https://github.com/microsoft/vscode/compare/1.85.0...1.85.1

Not even version number in `package.json`
