### ISSUE TITLE
Text from PsReadline PredictionViewStyle InlineView is now bold and roman in all color theme

### ISSUE THREAD

**Issue by RoadToDream** [microsoft/vscode#200398]
Type: <b>Bug</b>

If enable PsReadline' PredictionViewStyle and set to InlineView, the predicted text style will be bold and roman, which is normal and italic in Microsoft terminal.  

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900HX (24 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.73GB (46.34GB free)|
|Process Argv|--crash-reporter-id f3ab23e7-5bce-414c-b33d-d7165becbcfe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
cpp-helper|ami|0.3.3
doxdocgen|csc|1.4.0
autoit|Dam|1.0.12
gitlens|eam|14.5.2
stql|Ear|0.0.2
matlab|Gim|3.0.2
copilot|Git|1.141.0
copilot-chat|Git|0.11.0
vscode-ptx-syntax|gka|1.0.0
latex-workshop|Jam|9.15.0
better-cpp-syntax|jef|1.17.2
fastmag-helper|Jia|0.0.1
vscode-cudacpp|kri|0.1.1
vscode-docker|ms-|1.28.0
isort|ms-|2023.10.1
python|ms-|2023.22.0
vscode-pylance|ms-|2023.11.10
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.12
js-debug-nightly|ms-|2023.12.717
powershell|ms-|2023.8.0
remote-explorer|ms-|0.4.1
vscode-typescript-next|ms-|5.4.20231207
memory-viewer|Nat|0.0.1
nsight-vscode-edition|nvi|2023.2.32964508
svg-preview|Sim|2.8.3
code-spell-checker|str|3.0.1
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30917236
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260

```

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You will need to upgrade Windows to use conpty. You can read more about ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423) and [here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by RoadToDream** [comment]
Thanks for the quick reply. Confirmed the issue is related to the choice of backend render.
