### ISSUE TITLE
When opening a folder in VS Code that contains multiple Git repositories, it may not be able to locate the subdirectory repositories.

### ISSUE THREAD

**Issue by lobmoo** [microsoft/vscode#200324]
In my project folder, there are multiple projects named A, B, C, and D. Projects A, B, and C are all managed with Git version control. Under project D, there are three sub-projects named a, b, and c. The root directory of the projects is called ROOT. When I open ROOT, the source code manager only shows projects A, B, and C, and it doesn't display projects a, b, and c. I believe this has a significant impact on developers because when I make changes to projects a, b, and c, the version control manager cannot see those changes. How can I have all six repositories (ABC and abc) visible in the version control manager when I open ROOT?

**Comment by gjsjohnmurray** [comment]
Glad I could help. Please close the issue.
