### ISSUE TITLE
Implement scm.inputMinLines

### ISSUE THREAD

**Issue by Hermholtz** [microsoft/vscode#200341]
The commit message textbox is still not friendly for people with mild hand motion impairment. I'd like to be able to set commit message bigger by default. You recently implemented scm.inputMaxLines, thus adding scm.inputMinLines which would make it bigger by default should not be a big deal. See also #171359.

**Comment by MaxBR97** [comment]
@lszomoru I'd like to take this issue upon me please.

**Comment by lszomoru** [comment]
Related https://github.com/microsoft/vscode/pull/200551

**Comment by lszomoru** [comment]
Marking as duplicate of https://github.com/microsoft/vscode/issues/121452.

**Comment by Hermholtz** [comment]
@MaxBR97 @lszomoru thank you for implementing this feature. I was able to try it and it's just wonderful, makes VSCode so much better to use for me.

**Comment by MaxBR97** [comment]
@Hermholtz Thank you too for the opportunity! I would be grateful for having an endorsment or just a good feed back anywhere on my LinkedIn https://www.linkedin.com/in/max-brener/    Feel free to contact me for any further requests and/or feedbacks!
