### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by Nikita-schetko** [Microsoft/vscode#20032]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|htmltagwrap|bradgashler|0.0.3|
|path-intellisense|christian-kohler|1.2.0|
|vscode-stylesheet-formatter|dbalage|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|auto-close-tag|formulahendry|0.3.9|
|auto-rename-tag|formulahendry|0.0.11|
|beautify|HookyQR|0.7.3|
|expand-region|letrieu|0.0.3|
|code-beautifier|michelemelluso|1.6.2|
|HTMLHint|mkaufman|0.3.3|
|vscode-csscomb|mrmlnc|4.0.0|
|vscode-less|mrmlnc|0.6.0|
|debugger-for-chrome|msjsdiag|2.4.2|
|vscode-paste-and-indent|Rubymaniac|0.0.8|
|html5-boilerplate|sidthesloth|1.0.1|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
More info please.
