### ISSUE TITLE
Allow relative values for editor.lineHeight

### ISSUE THREAD

**Issue by huygn** [microsoft/vscode#20033]
- VSCode Version: 1.9
- OS Version: MacOS Sierra

`editor.lineHeight` should be allowed to use relative values to `fontSize` like css, ie. `1.5`, currently only `0` value scales to `fontSize`, but I need a higher scale value.

One thing I notice - `terminal.integrated.lineHeight` allows relative values, but not `editor.lineHeight`.

**Comment by zackkrida** [comment]
Please! 👍

**Comment by jm-mwi** [comment]
Also, the Markdown Preview line height is relative. It would be nice if these were all the same value instead of two of them functioning one way and a single option functioning another way.

**Comment by albertorestifo** [comment]
Would a PR for this be accepted?

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=usernamehw.relative-line-height 

```js
"relativeLineHeight.value": 1.5,
```
