### ISSUE TITLE
Terminal line error

### ISSUE THREAD

**Issue by its-19818942118** [microsoft/vscode#200427]
Type: <b>Bug</b>

Does this issue occur when all extensions are disabled?: Yes/No
**`YES`**
**System Issue**

so um on windows i used **`starship prompt`**. I configured my own prompt, And with the help of the **`pwsh community i managed to make a prompt that updates after 300 milsec to update the time`** it is a two line prompt standard two prompt works fine but the problem is with when i use starship `$fill` module it causes to create more lines like below 

![image](https://github.com/microsoft/vscode/assets/87006850/29e6e9b7-c32d-42cd-ad7f-f8932125a097)

PS: It also creates problems with the **`fill module`** disabling it keeps it fine but um i would like to know if there are any soulutions to this. **_Works fine on WIndows Terminal _**

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU 3867U @ 1.80GHz (2 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.30GB free)|
|Process Argv|--crash-reporter-id c0a55baa-dcd7-4303-958c-0ff80c879e75|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (87)</summary>

Extension|Author (truncated)|Version
---|---|---
node-essentials|afr|1.1.0
indent-jump|aPi|1.0.1
shell|bbe|0.3.0
color-info|bie|0.7.2
docs-view|bie|0.0.11
markdown-mermaid|bie|1.21.0
markdown-preview-github-styles|bie|2.0.3
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
iconsgallery|Cod|1.0.6
vscode-markdownlint|Dav|0.53.0
githistory|don|0.6.20
bracket-pair-toggler|dzh|0.0.3
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
sweet-vscode-icons|Eli|0.0.1
open-lnk|Enk|0.0.1
indent-switcher|eph|1.2.1
prettier-vscode|esb|10.1.0
indent-rainbow-palettes|evo|0.0.18
file-icons|fil|1.1.0
vscode-firefox-debug|fir|2.9.10
frame-indent-rainbow|fir|0.1.3
bravato-icons|flo|1.1.0
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
codespaces|Git|1.16.4
remotehub|Git|0.62.0
html-essentials|Gyd|0.1.0
web-design-essentials|Gyd|0.6.0
helium-icon-theme|hel|1.0.0
codepet|hiw|0.5.0
vscode-htmlhint|HTM|1.0.5
vscode-peacock|joh|4.2.2
bracket-peek|jom|1.4.4
code-background|Kat|2.9.0
vscode-gutter-preview|kis|0.30.0
l13-diff|L13|1.3.4
google-fonts|lio|0.0.1
materialdesignicons-intellisense|luk|4.1.0
manpages|mer|0.1.4
vscode-language-pack-zh-hans|MS-|1.85.2023120618
vscode-edge-devtools|ms-|2.1.3
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
brackets-keybindings|ms-|0.1.1
live-server|ms-|0.4.12
powershell|ms-|2023.11.1
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.0
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5900
color-highlight|nau|2.5.0
indent-rainbow|ode|8.3.1
vscode-css-peek|pra|4.4.1
vscode-rapidapi-client|Rap|1.10.2
vscode-services|rap|1.0.2
fabric8-analytics|red|0.7.3
vscode-yaml|red|1.14.0
folder-alias|rik|0.0.9
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
indenticator|Sir|0.7.0
vscode-fileutils|sle|3.10.3
code-spell-checker|str|3.0.1
indent-colorizer|tal|1.0.0
even-better-toml|tam|0.19.2
open-in-browser|tec|2.0.0
vscode-h2o|tet|0.2.15
vs-gradient-maker|The|1.2.0
vscode-pets|ton|1.25.1
loco-developer-preview|tre|0.0.2
windows-terminal|Tyr|0.7.0
mini-gradient-preview|Vic|1.0.0
highlight-matching-tag|vin|0.11.0
folder-path-color|Vis|0.0.13
quokka-vscode|Wal|1.0.601
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0
shell-script-ide|woo|0.0.3
vscode-folder-size|xia|0.1.0
txt-syntax|xsh|0.2.2
html-css-class-completion|Zig|1.20.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260

```

</details>

**Comment by Tyriar** [comment]
This sort of prompt might be a little too out there to support properly with shell integration. I recommend remove the 300ms update thing, trying to put it on the same line, or [disabling shell integration](https://code.visualstudio.com/docs/terminal/shell-integration).
