### ISSUE TITLE
Refactor options not available

### ISSUE THREAD

**Issue by ramanraja** [microsoft/vscode#200466]
Type: <b>Bug</b>

Open any working Flutter project that has no compiler errors. Choose any widget and right click. Select 'Refactor' option. Normally you should get a menu with items like 'wrap with widget', 'remove this widget' etc. But since the lastest update to VSCode these options are missing. Clicking 'Refactor' does not produce any menu.
Seems to be a repeat of an old bug:
https://github.com/Dart-Code/Dart-Code/issues/4104

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.69GB free)|
|Process Argv|--crash-reporter-id dd31163f-1ff9-48bc-bfb6-1ae9a90715c1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|3.0.0
ng-template|Ang|17.0.3
dart-code|Dar|3.78.0
flutter|Dar|3.78.0
vscode-eslint|dba|2.4.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|10.1.0
ionic|Ion|1.62.0
angular-essentials|joh|16.0.4
Angular2|joh|16.0.1
vscode-peacock|joh|4.2.2
vscode-docker|ms-|1.28.0
remote-wsl|ms-|0.81.8
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
material-icon-theme|PKi|4.32.0
platformio-ide|pla|3.3.1
cmake|twx|0.0.17
vscode-gradle|vsc|3.13.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259

```

</details>

**Comment by milindgoel15** [comment]
Same as https://github.com/microsoft/vscode/issues/200436

Can reproduce the bug with 0 extensions enabled.

**Comment by justschen** [comment]
/duplicate: tracking here https://github.com/microsoft/vscode/issues/198881
