### ISSUE TITLE
Editor isn't inserting asterisks automatically in JavaScript comment block

### ISSUE THREAD

**Issue by ahlechandre** [Microsoft/vscode#20044]
VSCode Version: 1.9.0
OS Version: Microsoft Windows 10

Steps to Reproduce:
1. Type `/**`
2. Press Enter key

![video_1486381527](https://cloud.githubusercontent.com/assets/7119058/22649604/d39ee778-ec62-11e6-9e14-775617b97b7c.gif)

**Comment by mjbvz** [comment]
I'm unable to reproduce this in 1.9.

Do you have any extensions installed? Does this also happen when you run code with `--disable-extensions`? Also, can you please share your user settings.

Thanks

**Comment by ahlechandre** [comment]
Yes, I have extensions installed and I do not running with `--disable-extensions`. Strangely this started happening after 1.9 update.

my User Settings:
```js
// Place your settings in this file to overwrite the default settings
{
  // Controls the font family.
  "editor.fontFamily": "Inconsolata",
  // Controls the font size.
  "editor.fontSize": 18,
  // Controls the rendering size of tabs in characters. Accepted values: "auto", 2, 4, 6, etc. If set to "auto", the value will be guessed when a file is opened.
  "editor.tabSize": 2,
  // Insert spaces when pressing Tab.
  "editor.insertSpaces": true,
  // Controls after how many characters the editor will wrap to the next line. Setting this to 0 turns on viewport width wrapping
  "editor.wrappingColumn": 0,
  // Whether the linter is run on save or on type.
  "php.validate.run": "onType",
  // Whether auto fetching is enabled.
  "git.autofetch": false,
  // Controls whether snippets are shown with other suggestions and how they are sorted.
  "editor.snippetSuggestions": "inline",
  // Controls auto save of dirty files. Accepted values:  "off", "afterDelay", "onFocusChange" (editor loses focus), "onWindowChange" (window loses focus). If set to "afterDelay", you can configure the delay in "files.autoSaveDelay".
  "files.autoSave": "off",
  // Controls the delay in ms after which a dirty file is saved automatically. Only applies when "files.autoSave" is set to "afterDelay"
  "files.autoSaveDelay": 1000,
  "editor.formatOnType": true,
  // The path of the shell that the terminal uses on Windows. When using shells shipped with Windows (cmd, PowerShell or Bash on Ubuntu), prefer C:\Windows\sysnative over C:\Windows\System32 to use the 64-bit versions.
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "window.zoomLevel": 0,
  "files.associations": {
    "*.htm": "twig"
  },
  "workbench.statusBar.visible": true,
  "workbench.activityBar.visible": false,
  "window.menuBarVisibility": "toggle"
}
```

**Comment by ahlechandre** [comment]
Things like `Tyriar.lorem-ipsum` extension and `Markdown preview` also just stopped working after 1.9 here.

![ezgif com-e78997768a](https://cloud.githubusercontent.com/assets/7119058/22690815/ab471eaa-ed1e-11e6-879b-a1fb6c9531b1.gif)

![mark](https://cloud.githubusercontent.com/assets/7119058/22690870/ded64bd8-ed1e-11e6-88a9-981f6f88c46d.gif)

**Comment by mjbvz** [comment]
@ahlechandre Please try running code with all extensions disabled: https://code.visualstudio.com/docs/editor/extension-gallery#_disable-an-extension

Since multiple features are broken, my best guess is that either you have a bad extension installed or your installation is corrupt. If the same issues are present with all extensions disabled, try reinstalling vscode to see if that fixes things

**Comment by ahlechandre** [comment]
@mjbvz By the reason I don't know why, these things now started working since the 1.9 release without needing reinstall or run with `--disable-extensions`. 

I expect that this features stay working from now.

Thank you.
