### ISSUE TITLE
Broken setting link in localized description

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#200421]
The setting name shouldn't be part of a localized string, otherwise this tends to happen

<img width="504" alt="image" src="https://github.com/microsoft/vscode/assets/323878/5c2b03da-e3d3-4623-ac1c-bcff97a1ac53">

**Comment by benibenj** [comment]
This is a mistake by the person translating. Having setting names in localized strings seems to be common. We add a comment to the localized string to indicate to the person translating that this needs to be taken into account. For example like this:

`'markdownDescription': localize({ comment: ['This is the description for a setting. Values surrounded by single quotes are not to be translated.'], key: 'tabSizing' }, "Controls the size of editor tabs. This value is ignored when `#workbench.editor.showTabs#` is not set to `multiple`.")`

@TylerLeonhardt is this still the recommended way to have setting names in localized markdown strings?

**Comment by TylerLeonhardt** [comment]
I would just do this:
```typescript
'markdownDescription': localize(
    {
        comment: ['{0} will be a setting name rendered as a link'],
        key: 'tabSizing'
    },
    "Controls the size of editor tabs. This value is ignored when {0} is not set to `multiple`.",
    '`#workbench.editor.showTabs#`'
)
```

**Comment by benibenj** [comment]
Good point. Will adapt this for all `workbench` settings

// @bpasero
