### ISSUE TITLE
Suggestion: do not stop search (& other actions) when VSCode's window loses focus

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#20043]
- VSCode Version: 1.9.0
- OS Version: Windows 10

When running operations that can take a long time, like searching into files, if the user clicks outside the VSCode window to do something else, the search is interrupted.

Suggestion: have an option to not interrupt actions if the VSCode's window loses focus.

**Comment by warpdesign** [comment]
Seems like the "workbench.quickOpen.closeOnFocusLost" not only affects quickOpen but search in files as well.

May I suggest renaming it since it's quite confusing?

**Comment by bpasero** [comment]
Yeah, that is the option 👍
