### ISSUE TITLE
TerminalInstance memory leak

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#200400]
Repro:

1. Open Code - OSS
2. Close all terminals
3. Reload
4. Open devtools
5. Go to memory and take a heap snapshot
6. Open a terminal
7. Close the terminal
8. Go to memory and take a heap snapshot
9. Compare the two heap snapshots, you should not see `TerminalInstance`

**Comment by mjbvz** [comment]
On Mac, I'm still seeing a terminal instances after running `kill all terminals`

![Image](https://github.com/microsoft/vscode/assets/12821956/a69e4e87-0879-4db7-bd54-729700ba4a26)


Repeating the process I then see two `TerminalInstance`
