### ISSUE TITLE
Auto updating devcontainer.json when installing extensions in the dev container

### ISSUE THREAD

**Issue by WolfEYc** [microsoft/vscode#200449]
It would be cool to either have installing an extension in the dev container result in the devcontainer.json auto updating with the extensionid, or to at least have a button next to the install / uninstall buttons of the extension that would add it to the json for me.

**Comment by sandy081** [comment]
There is an action in the context menu to add extension to devContainer.json

<img width="433" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/e5409ca6-24ca-4b02-a2de-1647cac0d9a6">
