### ISSUE TITLE
[win] Mocha test runner doesn't work when there is a space in the path

### ISSUE THREAD

**Issue by RaniSharim** [Microsoft/vscode#20046]
- VSCode Version: 1.9.0
- OS Version: Windows 10/8/7

Steps to Reproduce:

1. Create a project with path that contains spaces
2. Add "mocha test" debug configuration

My path is c:\Users\aharon\Documents\Visual Studio 2013\Projects\mrs\mrs

I get 'c:\Users\aharon\Documents\Visual' is not recognized as an internal or external command,
operable program or batch file.'

The path to exec need to be surrounded by " ", 
but when I try to do that it complains about something else.

**Comment by weinand** [comment]
@RaniSharim I cannot reproduce this problem with VS Code 1.12.2 on Windows 10.
With a project folder "foo bar" the path is properly surrounded by quotes:

```
Debugging with legacy protocol because Node.js v6.5.0 was detected.
node --debug-brk=13980 --nolazy node_modules\mocha\bin\_mocha -u tdd --timeout 999999 --colors 'c:\Users\weinand\Projects\TestData\foo bar/test' 
Debugger listening on [::]:13980
No test files found
```
