### ISSUE TITLE
Notebook cell editor -- selection highlighting doesn't work

### ISSUE THREAD

**Issue by zpincus** [microsoft/vscode#200406]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When `"editor.selectionHighlight"` is set, in non-notebook windows, selecting a block of text will highlight matching blocks elsewhere in the document.

I seem to recall this used to be true in jupyter notebook cells as well, but it is no longer the case (for me at least). Here's an SO post from a couple years back demonstrating that selection highlighting was indeed once working in notebook cells:
https://stackoverflow.com/questions/68527700/ipynb-highlight-other-occurrences-of-selected-variable-in-vscode-ipython-notebo).

This is independent of whether the kernel is local or remote, or any other settings that I have tried. I observe it on two different machines (one a Mac connected via the remote extension to a linux box; another a Mac editing locally -- and there is no settings sync between them or anything so these are ~independent configs...)

Unsure of whether this is a core vscode issue, or a vscode-jupyter one.

### VS Code Version

Version: 1.84.2 (Universal) Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e Date: 2023-11-09T10:52:33.687Z Electron: 25.9.2 ElectronBuildId: 24603566 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Darwin arm64 23.1.0

### Jupyter Extension Version

v2023.10.1100000000

### Running Jupyter locally or remotely?

None

**Comment by Yoyokrazy** [comment]
Could you investigate this within the new stable release (1.85)? There have been a number of improvements to the multi document highlighting api, including a number of bugfixes, a change of the `editor.occurrenceHighlight` setting to an enum, and out of the box semantic highlighting for typescript.

**Comment by zpincus** [comment]
Unfortunately this is not fixed in the new release, I'm afraid.

Repro is easy ofc: run the command "Create: New Jupyter Notebook" (I haven't tested with other notebook languages/extensions), type in e.g. "foo bar foo" and select one of the "foo"s. Observe that the other is not highlighted.

**Comment by Yoyokrazy** [comment]
Hm, could you go ahead and create a fully empty profile on the latest release, and attempt it there? I followed that repro, and was able to get proper highlighting without any snags. See attached:

<img width="735" alt="image" src="https://github.com/microsoft/vscode/assets/12552271/fa7c21f6-da1b-43e5-b1cf-d4c4faf64967">

**Comment by Yoyokrazy** [comment]
Ah yep, sorry bout the confusion there, you're spot on. Just did a little digging and it looks like this hasn't worked in a couple releases. This will make it onto the backlog of things for me to address within the cell editors, but can't promise any certain timing. 

Looking at that SO post you sent earlier, I do tend to think that all screenshots in that post (OP's and the reply) are showing stationary cursors on a single character of the variable and would therefore be utilizing occurrence highlighting. The first image just appears to be using a block style cursor rather than the default line style we are used to these days. Nonetheless, I agree that the feature should work across editor types, and will look into this.

**Comment by zpincus** [comment]
Thanks! Appreciate your attention on this one! :)

**Comment by Wmuntean** [comment]
Any updates on this? Would be nice to have similar highlighting behavior between notebooks and editors.

**Comment by Yoyokrazy** [comment]
Thank you for pointing this out! Could you please file an issue citing this comment? I have a handful of polish fixes that will be coming as I find time to work on them, and that would help make sure that this is addressed as well. Thanks!
