### ISSUE TITLE
codespaces dont work

### ISSUE THREAD

**Issue by EdsinZxx** [microsoft/vscode#200490]
ADD ISSUE DESCRIPTION HERE
codespaces dont loading
Version: 1.85.0
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by meganrogge** [comment]
To make this actionable, pls provide more info next time.
