### ISSUE TITLE
icoming/outgoing source control doesn't show contents

### ISSUE THREAD

**Issue by robaho** [microsoft/vscode#200488]
Type: <b>Bug</b>

The new incoming/outgoing does not not work propery.

The sections cannot be expanded to show the contents. The count icon matches.

VS Code version: Code 1.85.0 (Universal) (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T18:18:04.614Z)
OS version: Darwin x64 22.6.0
Modes:
Remote OS version: Linux x64 5.15.0-91-generic
Remote OS version: Linux x64 5.15.0-91-generic
Remote OS version: Linux x64 5.15.0-91-generic
Remote OS version: Linux x64 5.15.0-91-generic
Remote OS version: Linux x64 5.15.0-91-generic
Remote OS version: Linux x64 5.15.0-91-generic
Remote OS version: Linux x64 5.15.0-91-generic
Remote OS version: Linux x64 5.15.0-91-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (2.36GB free)|
|Process Argv|--crash-reporter-id 54620fd3-09a5-4761-bc78-a085e93eaf2b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: work|
|OS|Linux x64 5.15.0-91-generic|
|CPUs|Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz (12 x 3800)|
|Memory (System)|31.08GB (11.11GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: chwld-rengels1|
|OS|Linux x64 5.15.0-91-generic|
|CPUs|Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz (12 x 3800)|
|Memory (System)|31.08GB (11.11GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: work|
|OS|Linux x64 5.15.0-91-generic|
|CPUs|Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz (12 x 2179)|
|Memory (System)|31.08GB (11.11GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: work|
|OS|Linux x64 5.15.0-91-generic|
|CPUs|Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz (12 x 3800)|
|Memory (System)|31.08GB (11.11GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: chwld-rengels1|
|OS|Linux x64 5.15.0-91-generic|
|CPUs|Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz (12 x 3800)|
|Memory (System)|31.08GB (11.11GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: chwld-rengels1|
|OS|Linux x64 5.15.0-91-generic|
|CPUs|Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz (12 x 3800)|
|Memory (System)|31.08GB (11.11GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: chwld-rengels1|
|OS|Linux x64 5.15.0-91-generic|
|CPUs|Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz (12 x 3800)|
|Memory (System)|31.08GB (11.11GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: work|
|OS|Linux x64 5.15.0-91-generic|
|CPUs|Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz (12 x 3800)|
|Memory (System)|31.08GB (11.11GB free)|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
remotehub|Git|0.62.0
better-cpp-syntax|jef|1.17.2
better-objc-syntax|jef|0.2.0
better-objcpp-syntax|jef|0.2.0
autoconf|mae|0.2.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.0
lit-html|bie|1.11.1
githistory|don|0.6.20
vscode-pull-request-github|Git|0.76.1
vscode-embedded-css-template-strings|hec|0.5.1
githd|hui|2.3.3
rest-client|hum|0.25.1
gitsweep|jel|1.0.0
git-tree-compare|let|1.16.0
vscode-antlr4|mik|2.4.4
hexeditor|ms-|1.9.12
sqltools|mtx|0.28.1
sqltools-driver-pg|mtx|0.5.2
gradle-language|nac|0.2.3
inline-html|pus|0.3.9
java|red|1.26.2023120908
code-spell-checker|str|3.0.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.13.2023120800
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.43.0
gitblame|wad|10.5.1
jar-viewer|wma|1.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by robaho** [comment]
Here is a screenshot:

<img width="460" alt="image" src="https://github.com/microsoft/vscode/assets/4958833/787b4cf9-fd8f-4b4f-9edd-a7447ca8b98c">

**Comment by inigohidalgo** [comment]
I have the same issue, but it works locally, it is only broken on my remote development sessions through ssh.

**Comment by inigohidalgo** [comment]
When I try to toggle the incoming/outgoing dropdown I see the following in the Git log output:

```
2023-12-11 11:45:28.429 [info] > git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z --shortstat --diff-merges=first-parent --author-date-order [commit-hashes] [58ms]
2023-12-11 11:45:28.429 [info] fatal: unrecognized argument: --diff-merges=first-parent
```

It seems that argument was added in git v2.31.0 [link to git release notes](https://github.com/git/git/blob/a5828ae6b52137b913b978e16cd2334482eb4c1f/Documentation/RelNotes/2.31.0.txt#L55C5-L55C5)

On my remote dev machine I have `2.25.1` so that tracks.
