### ISSUE TITLE
Exported theme looks different

### ISSUE THREAD

**Issue by yuyang9119** [microsoft/vscode#200448]
Type: <b>Bug</b>

I add color-customizations in settings.json, then export and publish the theme, but if install this theme the displaying colors are different from settings.json.

![colors](https://github.com/microsoft/vscode/assets/18855621/55a7ac2e-9770-410c-8149-a69cde05f8b0)

This is my settings.json:
[settings.json](https://github.com/microsoft/vscode/files/13625153/settings.json)

This is the exported theme: 
https://marketplace.visualstudio.com/items?itemName=YY-GamePlayer.dark-modern-plus

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
netcore-editorconfiggenerator|dog|0.2.0
EditorConfig|Edi|0.16.4
vscode-language-pack-zh-hans|MS-|1.85.2023120618
csdevkit|ms-|1.1.16
csharp|ms-|2.13.10
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26
hexeditor|ms-|1.9.12
vstuc|vis|0.9.3
vscode-icons|vsc|12.6.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by aeschli** [comment]
Can you use the `Inspect Editor Tokens and Scopes` command to find out what could be different.
Is it semantic token that are missing in the export?

**Comment by aeschli** [comment]
Themes can decide if they want semantic highlighting or not. Our built-in themes do.

To enable this in your theme add `"semanticHighlighting": true` in the theme file

**Comment by yuyang9119** [comment]
> Themes can decide if they want semantic highlighting or not. Our built-in themes do.
> 
> To enable this in your theme add `"semanticHighlighting": true` in the theme file

After adding `"semanticHighlighting": true`, most of the colors are correct, but the color of namespaces are still incorrect.

This is the current settings.json:
[settings.json](https://github.com/microsoft/vscode/files/13684578/settings.json)

This is the updated theme:
https://marketplace.visualstudio.com/items?itemName=YY-GamePlayer.dark-modern-plus

**Comment by aeschli** [comment]
Sorry, please use the `Inspect Editor Scopes and Tokens` command to figure out the changes.

Maybe you have to add some semantic colors to your theme

There is the known issue that the generate command does not add the semantic colors https://github.com/microsoft/vscode/issues/101556
