### ISSUE TITLE
Debugger should show unescaped strings

### ISSUE THREAD

**Issue by KallDrexx** [Microsoft/vscode#20048]
- VSCode Version: 1.9.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Create a new .net core project with `dotnet new`
2. Specify the following main function:
```
        public static void Main(string[] args)
        {
            var test = @"{""Test"": 123}";
            Console.WriteLine(test);
        }
```
3) Put a break point on the last ending brace of the function
4) Debug

----> Observe the variables and watch window shows the value of the string as `"{\"Test\": 123}"` when it should show the unescaped value of `{"Test": 123}`.

This is important because I"m in the process of writing an application to read and write structured (json) logs and trying to verify some things with the debugger, and it's adding extra steps to verifying the json being output (since I have to manually unescape it in order to pretty print it for verification)

I have no idea if this is C# or VSCode specific.

**Comment by isidorn** [comment]
This is coming from the C# extension, so please file the issue here https://github.com/OmniSharp/omnisharp-vscode

**Comment by KallDrexx** [comment]
Will do thanks!
