### ISSUE TITLE
"Run Python file in terminal" fails with error

### ISSUE THREAD

**Issue by pfmoore** [Microsoft/vscode#20047]
- VSCode Version: 1.9.0
- OS Version: Windows 7 Professional SP1

Steps to Reproduce:

1. Open a Python file with the single line ```print("Hello, world")```
2. Right click on the file and select "Run Python file in terminal"

The following output appears in the terminal window:

```
Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

PS 13:57 C:\Work\Scratch\test
>"C:/Windows/py.exe" c:/Work/Scratch/test/__main__.py
At line:1 char:21
+ "C:/Windows/py.exe" c:/Work/Scratch/test/__main__.py
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'c:/Work/Scratch/test/__main__.py' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

PS 13:57 {00:00.007} C:\Work\Scratch\test
>
```

It's not clear to me whether this action comes from VS Code itself or from an extension (I have the "Python" and "Powershell" extensions installed). But it does seem that the action is failing to format the shell command in a way that Powershell can execute (an initial ```&``` is needed as the executable name is quoted).

My settings file includes the following:

```json
// Place your settings in this file to overwrite the default settings
{
  // Customizes which terminal to run on Windows.
  "terminal.integrated.shell.windows": "C:\\WINDOWS\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
  //"python.pythonPath": "C:\\Users\\UK03306\\AppData\\Local\\Programs\\Python\\Python36\\python.exe"
  "python.pythonPath": "C:\\Windows\\py.exe"
}
```

I'm guessing that the "Run Python file in terminal" command isn't taking into account the possibility that the default shell is not ```cmd.exe```. Removing my custom ```terminal.integrated.shell.windows``` allows "Run Python file..." to work, but I do *not* consider that to be an acceptable solution here, as it would affect the behaviour of ```Ctrl-Shift-'``` (Create New Integrated Terminal).

**Comment by pfmoore** [comment]
With a bit more digging I discovered that this is a feature of the Python extension. I'll raise an issue over there. However, in cases like this is there a way I can easily tell which extension is causing some behaviour? (Short of disabling all extensions, then re-enabling them one by one...) Having a way would save a lot of wasted time (both mine and yours) caused by reporting issues in the wrong place.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by pfmoore** [comment]
OK, understood. But regarding my other question, how would I be able to tell this was an issue with an extension (and more specifically which extension I should report it to)?
