### ISSUE TITLE
editor.showTabs 'single' prevents drag and drop

### ISSUE THREAD

**Issue by GTonehour** [microsoft/vscode#200441]
When `workbench.editor.showTabs` is `single`, then I can't drag and drop a tab to split the screen.

![2023-12-08_18h07_20](https://github.com/microsoft/vscode/assets/86954612/21870434-b432-47c7-9073-9ad7fff2aeae)

- VS Code Version: 1.85.0
- OS Version: Windows 11 10.0.22621
- Occurs with --disable-extensions

Steps to Reproduce:
1. Set  `workbench.editor.showTabs` to `single`
2. Open two tabs
3. Click on the name of the opened tab, try to drag it to the right or bottom

**Comment by benibenj** [comment]
This is as designed. You don't see the tabs underneath in single tabs mode, so a drag and drop would create potentially unexpected behaviour. However, we have commands and the action item in the top right to split an editor into two or support drag and drop on the editors listed in the open editors view in the explorer.
