### ISSUE TITLE
Long delay after tasks finish before they can be run again

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#200434]
Type: <b>Performance Issue</b>

There's a very long delay after after a task finishes before vscode recognizes it has finished and allows it to be run again. 

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "build",
			"type": "shell",
			"command": "dir",
			"problemMatcher": [],
			"group": {
				"kind": "build",
				"isDefault": true
			}
		},
	]
}
```

For a very simple task like the above it takes ~90 ms to run. Then it takes another 1340 ms for vscode to notice. This is problematic for longer tasks as well if you're paying attention to them and waiting for them to finish. It's easy to try to run another task in the game between the first task finishing and vscode allowing another to be run.

Changing the shell to `cmd /D` doesn't make a difference and neither does disabling shell integration (which I assume isn't enabled for tasks).

![Bug](https://github.com/microsoft/vscode/assets/484784/c2260238-b3ce-42d1-bf8b-4fd80cfa48b7)

VS Code version: Code - Insiders 1.86.0-insider (02b90714767f05c734ac29a64d0e5b4768f532d8, 2023-12-08T11:53:10.286Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (18.97GB free)|
|Process Argv|--crash-reporter-id 22cf4e37-a96e-4ad9-82f0-8715f8e2bf6e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   113	 35120	code-insiders main
    0	   101	 14448	shared-process
    0	    40	 14896	   utility-network-service
    0	    97	 21380	window [2] (Issue Reporter)
    0	   133	 23292	extensionHost [1]
    0	   107	 31232	     electron-nodejs ("C:\Users\akbyrd\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" --ms-enable-electron-run-as-node "c:\Users\akbyrd\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=23292)
    0	    83	 32544	fileWatcher [1]
    0	   144	 32956	   gpu-process
    0	   100	 33484	ptyHost
    0	   112	   412	     "C:\Program Files\PowerShell\7\pwsh.exe"
    0	     9	  7684	     conpty-agent
    0	    30	 35996	   crashpad-handler
    0	   289	 36056	window [1] (tasks.json - bug - Visual Studio Code - Insiders)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (tasks.json - bug - Visual Studio Code - Insiders)
|    Folder (bug): 1 files
|      File types:
|      Conf files:;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
2i9eh265:30646982
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpsinfo:30901776
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by meganrogge** [comment]
This is by design to prevent a race condition in which a task would run multiple times.

**Comment by akbyrd** [comment]
Can you expand on that?

I assume an arbitrary 1250 ms delay doesn't prevent a race condition, though it may hide one.

There is a command that runs and returns. Once it returns it is safe to run it again. It's not obvious to me where the delay comes into play.

**Comment by meganrogge** [comment]
I am not sure I understand what is going on in your gif. I do not see a delay there.

**Comment by akbyrd** [comment]
When Ctrl+Shift+B is pressed the output of the `dir` command shows up almost immediately. At this point the terminal command has executed, returned, and it is safe to run the command again.

More than a second later the line "Terminal will be reused by tasks, press any key to close it" shows up.

In the space between those two messages vscode will not allow the task to be run, even though it should. It will say the task is still in progress, but it is not in progress. The command has returned a value and exited. This makes commands sluggish and can be frustrating it highly iterative workflows that rely on quick feedback.
