### ISSUE TITLE
Remote connection

### ISSUE THREAD

**Issue by hamtagg** [microsoft/vscode#200455]
Hello computer experts!
I've got the below problem once I was trying to connect through WSL tunnel and received the below messages which I don't know how I can resolve them!
Could you please guide me! Any comments would be so much appreciated!
[VSC.txt](https://github.com/microsoft/vscode/files/13625529/VSC.txt)
![Screenshot (2264)](https://github.com/microsoft/vscode/assets/153090943/1c173290-5437-42bf-9762-10ad0542a399)

**Comment by aeschli** [comment]
From the log I can see that tunnels are not involved, it's just regular remote WSL window.
Regardless, this should work. Unfortunately the log doesn't give any information the the connection stopped.

Can you close all windows and try the following
- in a WSL terminal, run `rm -r ~/.vscode-server/bin`. Remove the VS Code server installation in case the binary is corrupt
- in a Windows command prompt run `wsl --shutdown`. Restarts the WSL VM.

**Comment by hamtagg** [comment]
Hi aeschli,
Thanks for the comment. Of course, I’ll let you know in case I manage.
