### ISSUE TITLE
Unable to disable "Sync this Extension"

### ISSUE THREAD

**Issue by Moulick** [microsoft/vscode#200470]
Type: <b>Bug</b>

1. Go to any extension
2. Click the gear icon and try to untick the "Sync this Extension"
3. Error pops up "k.toLowerCase is not a function"

![image](https://github.com/microsoft/vscode/assets/15780903/5d64aaed-31e8-4fee-9cce-81bd9da4dc96)
![image](https://github.com/microsoft/vscode/assets/15780903/f8f7dabc-3f47-4721-a906-7690e3f4c89f)

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T18:17:50.719Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (1.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (67)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
better-comments|aar|3.0.2
vscode-base64|ada|0.1.0
base64utils|adr|1.2.4
asciidoctor-vscode|asc|3.1.10
atlascode|atl|3.0.9
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.21.0
markdown-preview-github-styles|bie|2.0.3
markdown-yaml-preamble|bie|0.1.0
tpl|cdp|1.0.1
path-intellisense|chr|2.8.5
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|14.5.2
RunOnSave|eme|0.2.0
opensslutils|ffa|1.1.1
shell-format|fox|7.2.5
copilot|Git|1.141.0
copilot-chat|Git|0.12.2023120701
copilot-labs|Git|0.17.1121
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.76.1
go|gol|0.40.0
raythis|Goo|1.1.1
gc-excelviewer|Gra|4.2.58
hcl|has|0.3.2
terraform|has|2.29.0
jsonnetplus|hui|1.1.4
jbockle-format-files|jbo|3.4.0
plantuml|jeb|2.17.5
better-shellscript-syntax|jef|1.6.3
minifyall|jos|2.10.0
vscode-github-actions|me-|3.0.1
rainbow-csv|mec|3.9.0
fluent-icons|mig|0.0.18
vscode-docker|ms-|1.28.0
black-formatter|ms-|2023.6.0
python|ms-|2023.22.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
live-server|ms-|0.4.12
makefile-tools|ms-|0.7.0
remote-repositories|ms-|0.40.0
vsliveshare|ms-|1.0.5900
json-parse-stringify|nex|1.0.2
json-to-yaml-and-more|pet|0.0.3
material-icon-theme|PKi|4.32.0
excalidraw-editor|pom|3.7.1
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
partial-diff|ryu|1.4.3
semanticdiff|sem|0.8.8
swapdiff|sha|0.2.2
even-better-toml|tam|0.19.2
shellcheck|tim|0.35.0
vscode-gradle|vsc|3.13.5
vscode-icons|vsc|12.6.0
footsteps|Wat|0.5.0
vscode-todo-highlight|way|1.0.5
markdown-all-in-one|yzh|3.5.1
material-theme|zhu|3.16.2

</details>

**Comment by sandy081** [comment]
I am not able to reproduce it. Does this happen on every extension or specific extension?

**Comment by Moulick** [comment]
@sandy081 on all extensions

**Comment by sandy081** [comment]
Can you please check following and let me know if you see any error logs?

- F1 > Open View... > Window
- F1 > Open View... > Shared
- F1 > Developer: Toggle Developer Tools > Console

**Comment by Moulick** [comment]
No new log in Window
No new log in Shared

Console
```
TypeError: k.toLowerCase is not a function
    at ignoredExtensions.ts:44:119
    at Array.map (<anonymous>)
    at D.updateIgnoredExtensions (ignoredExtensions.ts:44:106)
    at ne.toggleExtensionIgnoredToSync (extensionsWorkbenchService.ts:1779:41)
    at Object.run (extensions.contribution.ts:1519:45)
    at d.run (extensions.contribution.ts:1679:35)
    at handler (actions.ts:580:42)
    at g.invokeFunction (instantiationService.ts:68:11)
    at k.n (commandService.ts:95:46)
    at k.executeCommand (commandService.ts:60:17)
    at v.run (actions.ts:506:31)
    at mt.run (extensionsActions.ts:1242:22)
    at E.u (actions.ts:194:16)
    at E.run (actions.ts:185:15)
    at m.r (contextmenuService.ts:257:33)
    at Object.click (contextmenuService.ts:229:11)
    at Function.h (contextmenu.ts:18:8)
c @ notificationsAlerts.ts:40
```

Would you rather I give a screenshot of all three?

**Comment by Moulick** [comment]
Error on Settings Sync Plugin
```
2024-01-08 10:59:07.447 [error] TypeError: $.toLowerCase is not a function
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:20750
    at Array.map (<anonymous>)
    at j.getIgnoredExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:20741)
    at I.getLocalExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:29376)
    at async p.qb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:24674)
    at async p.eb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:16015)
 ```

**Comment by sandy081** [comment]
Can you please open your settings.json and see if there is value configured for `settingsSync.ignoredExtensions` ?

**Comment by Moulick** [comment]
```json
"settingsSync.ignoredExtensions": [
    {
      "security.workspace.trust.untrustedFiles": "open"
    }
  ]
```

**Comment by sandy081** [comment]
Please delete this setting and try again

**Comment by Moulick** [comment]
Yep, that fixes the problem. But still, It looks like somewhere code calls `k.toLowerCase` function which is not available? While cleaning up the settings did fix it, maybe there is a bug lurking?

**Comment by sandy081** [comment]
You have an invalid setting and this caused it. VS Code expects value in a particular format and you have it in different format. Since it is user error, I would like not to fix it.
