### ISSUE TITLE
Feature request: different settings for split-view windows

### ISSUE THREAD

**Issue by thesunlover** [Microsoft/vscode#20040]
I would like to able to change the settings of one of the views when using split-view.
I wanted to toggle the word-wrap option for one of the views, but the option changes all the views.
It would be comfortable to have the option for both views, but as well as on the currently focused view.
And it would be good if more features are integrated the same way.

- VSCode Version: 1.9.0
- OS Version: Windows 10

Steps to Reproduce: 

1. Open some code file
2. Split the editor and open the documentation or specification for that source code
3. Toggle the view for the Documentation to be "WordWrap:ON"
and for the source code to be "WordWrap:OFF"

Expected: the option should be in different state for the views

Current result: We have all the views in the same state for the WordWrap option.

**Comment by bpasero** [comment]
Well, this is a consequence of making this setting move into `settings.json`. It no longer is a editor only view setting.

**Comment by alexandrudima** [comment]
@thesunlover The word wrapping now behaves similar to all other presentation options: font family, font size, zoom level, etc. All editors get the same value. The only way at this point to customize settings from an editor to another is to use per-language settings.

**Comment by thesunlover** [comment]
@bpasero
Do you say that it was a feature that was disabled sometime ago?

**Comment by thesunlover** [comment]
@alexandrudima
I have some kind of documentation that has a TypeScript code in it and I want to read the document as a .TS., but still keep my real TS code as the not word-wrapped
