### ISSUE TITLE
Refactor Dropdown is not readable.

### ISSUE THREAD

**Issue by thesamim** [microsoft/vscode#200410]
Type: <b>Bug</b>

Select code,
Right Click,
Select Refactor.

Refactor dropdown is not readable.

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7900X 12-Core Processor             (24 x 4691)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.15GB (40.89GB free)|
|Process Argv|E:\\Dev\\TickTickSync\\master --crash-reporter-id b365d7f7-630d-48bf-8839-acd7e698fa76|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-wysiwyg|ada|0.7.8
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.21.0
markdown-preview-github-styles|bie|2.0.3
markdown-yaml-preamble|bie|0.1.0
vscode-github-actions|git|0.26.2
python|ms-|2023.22.0
vscode-pylance|ms-|2023.11.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
962ge761:30917236
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260

```

</details>

**Comment by thesamim** [comment]
Screen shots.
![Refactor Disspears -- Dark](https://github.com/microsoft/vscode/assets/5315625/6f4307f9-9379-4dc1-8a20-6f268724437f)
![Refactor Disspears -- Light](https://github.com/microsoft/vscode/assets/5315625/addcd8a6-7483-4769-881e-a78819f94b23)

**Comment by roblourens** [comment]
Is that one of the default themes?

Got any `workbench.colorCustomizations` setting configured?

**Comment by thesamim** [comment]
> Is that one of the default themes?
> 
Tried with several themes. All same result.

> Got any `workbench.colorCustomizations` setting configured?
None.

Be happy to try any dark theme you suggest.

**Comment by justschen** [comment]
/duplicate: tracking it here: https://github.com/microsoft/vscode/issues/198881
