### ISSUE TITLE
Aux Window: Full screen Terminal Window Input Lag

### ISSUE THREAD

**Issue by maharshivpatel** [microsoft/vscode#200469]
Does this issue occur when all extensions are disabled?: Yes/No

VS Code Version: Version: 1.85.0 (Universal)
OS Version: Darwin arm64 22.5.0

Terminal input doesn't work ( is too slow almost feels like not working ) when using `Full Screen` in Aux Window.

Steps to Reproduce:

Open Aux Terminal Window In Full Screen Mode or make it Full screen afterwords.

https://github.com/microsoft/vscode/assets/39730881/ed5c03cf-bcc2-4bca-859e-74c23bdba515

**Comment by maharshivpatel** [comment]
This seems to be working in OSS Dev container.

**Comment by bpasero** [comment]
This looks to me like a case of scheduling something on the main window which gets throttled once hidden. 

@Tyriar is the terminal using scheduler for rendering such as RAF or `runWhenIdle`?

**Comment by bpasero** [comment]
I can reproduce and its pretty bad.

**Comment by maharshivpatel** [comment]
off-topic: is there a way to move panel to separate window. e.g. bottom drawer or individually like terminal, debug console ?

**Comment by jeanp413** [comment]
PR fixing it https://github.com/xtermjs/xterm.js/pull/4912
