### ISSUE TITLE
Array

### ISSUE THREAD

**Issue by pingorhart** [microsoft/vscode#200460]
Type: <b>Performance Issue</b>

When I'm using array in c++ the code have an error or it paused then the tab showed xstring I don't know what's the problem.

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.31GB free)|
|Process Argv|--crash-reporter-id 77cc4a8b-7a0d-403e-bfd3-ffb620f8211a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    99	 19452	code main
    0	    57	  2840	ptyHost
    0	    55	  2376	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\Jordan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     6	 24268	     conpty-agent
    0	    94	 13952	window [3] (Issue Reporter)
    0	   186	 17220	extensionHost [1]
    0	    50	 20112	     electron-nodejs ("C:\Users\Jordan\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Jordan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=17220)
    0	    51	 29196	     c:\Users\Jordan\.vscode\extensions\ms-vscode.cpptools-1.18.5-win32-x64\bin\cpptools.exe
    0	     7	  5700	       "c:\Users\Jordan\.vscode\extensions\ms-vscode.cpptools-1.18.5-win32-x64\bin\cpptools.exe"
    0	   105	 27680	         c:\Users\Jordan\.vscode\extensions\ms-vscode.cpptools-1.18.5-win32-x64/bin/cpptools-srv.exe 29196 {2A968440-C3DC-4502-AD3C-7443622A4D22}
    0	    10	 25792	           C:\WINDOWS\system32\conhost.exe 0x4
    0	    10	 22728	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    81	 18808	shared-process
    0	   303	 21768	window [1] (xstring - vs code - Visual Studio Code)
    0	    53	 22168	fileWatcher [1]
    0	   174	 25972	   gpu-process
    0	    41	 28320	   utility-network-service
    0	    28	 28600	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (xstring - vs code - Visual Studio Code)
|    Folder (vs code): 135 files
|      File types: pdb(28) exe(25) ilk(25) obj(25) cpp(23) json(4) 1(1) CPP(1)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1);
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
blackbox|Bla|1.2.34
copilot|Git|1.141.0
copilot-chat|Git|0.11.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259

```

</details>

```[tasklist]
### Tasks
```

**Comment by pingorhart** [comment]
<img width="960" alt="image" src="https://github.com/microsoft/vscode/assets/145249681/4541ea7c-b312-4945-99ac-ae2b9bf6dbf3">

**Comment by pingorhart** [comment]
<img width="960" alt="image" src="https://github.com/microsoft/vscode/assets/145249681/65473d24-8e0a-4e27-a92d-65e07f101b4a">

**Comment by hediet** [comment]
This does not seem to be a VS Code issue.
