### ISSUE TITLE
Ability to commit only staged changes is  no longer possible in source control tab

### ISSUE THREAD

**Issue by gopipalamalai** [microsoft/vscode#200423]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.85.0
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T18:17:50.719Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

Steps to Reproduce:

1.  Make  some code changes and  stage only some files, not all changes.
2. Go to source control tab and try to commit only the staged changes. No option exists. This was an option before.

![image](https://github.com/microsoft/vscode/assets/55415440/f3ce4672-44b6-4ff8-bfd9-ec3b32bcd6a2)

**Comment by gopipalamalai** [comment]
Seems like the commit option will only commit the staged changes. If this is by design close this issue.

**Comment by lszomoru** [comment]
There was never an option to commit staged changes as that is the default behaviour when changes are staged and the "Commit" button is pressed.
