### ISSUE TITLE
Debug go progream, but it does not work.

### ISSUE THREAD

**Issue by tuningMaster** [microsoft/vscode#200461]
`func TestTemplate1(t *testing.T) {
	var me string = "hello world"
	fmt.Println(me)
}`

when debug this test demo, but it does not work. like this:
![image](https://github.com/microsoft/vscode/assets/153407390/9c8ef9ba-4f63-4391-91de-dc00b5f30881)
how can I resolve this?

**Comment by roblourens** [comment]
Please file an issue on the debug extension you're using
