### ISSUE TITLE
TS: Refactor menu is transparent

### ISSUE THREAD

**Issue by psnet** [microsoft/vscode#200442]
Type: <b>Bug</b>

TypeScript:

STR:

1. select const var to move to new file
2. context menu - Refactor
3. opens menu without background (transparent), menu items text will be put on code editor`s text

![зображення](https://github.com/microsoft/vscode/assets/1023918/8a6c8567-2679-4218-a836-b9fb0f6c7ec6)

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64

### UPD

After pressing `Show disabled` menu item menu background became visible, but after a while working with it it again becames transparent and w/o icons.

**Also** this affects menu `source action` - it doesnt shows at all 

![зображення](https://github.com/microsoft/vscode/assets/1023918/aa42c8db-df1b-443b-a96b-027c9976963c)

### UPD2

Clicking `Show disabled` / `Hide Disabled` in `Refactor` menu shows background in `Refactor` menu and also became working `source action` menu, but after a while both these menus became not working again: `Refactor` again became transparent and `source action` doesnt shows at all

**Comment by DanTup** [comment]
Opening from the context menu is broken (in many languages). Pressing the shortcut key Ctrl+Shift+R seems to "fix" it (even for then opening it from the menu).

**Comment by justschen** [comment]
/duplicate : tracking here https://github.com/microsoft/vscode/issues/198881
