### ISSUE TITLE
Sticky tree scroll doesn't activate when file is revealed

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#200420]
Type: <b>Bug</b>

1. In VS code codebase, open `codeAction.ts`

**bug**
I don't see the sticky  tree elements in the explorer

![Image](https://github.com/microsoft/vscode/assets/12821956/1664baf7-e99f-404b-8f2e-c94d2630dbfc)

These only show up for me if I scroll up and then back down

VS Code version: Code - Insiders 1.86.0-insider (Universal) (02b90714767f05c734ac29a64d0e5b4768f532d8, 2023-12-08T11:53:26.555Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (0.42GB free)|
|Process Argv|--crash-reporter-id 0fffb5da-9cd7-46fd-9e7f-a1564e8c5fda|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by benibenj** [comment]
This is the expected behaviour. We don't show the sticky element based on the active or focused file but based on the first visible file in the tree.
