### ISSUE TITLE
Sticky scroll node removal is too slow

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#200533]
Simple scroll on a PC with a fast CPU:

![image](https://github.com/microsoft/vscode/assets/2193314/b89a5571-bfc7-477c-9bd2-e12f1a7581e4)
![image](https://github.com/microsoft/vscode/assets/2193314/d2defb9b-9ba9-4f38-a473-a2f8e1960196)

Consider doing one of the following:

- Not clear the node at all, just hide it
- Prevent larger layout impact, removing an item on a separate layer should not be taking 2ms
- Defer clean up to an idle frame
- Do the render in the animation frame

**Comment by Tyriar** [comment]
The same applies to showing it:

![image](https://github.com/microsoft/vscode/assets/2193314/9db86657-c3b1-494a-9911-6c43f4f0f4d1)

**Comment by italojs** [comment]
how can we reproduce it?

**Comment by aiday-mar** [comment]
Some work has been done with the following PR: https://github.com/microsoft/vscode/pull/200656. The code no longer clears the full dom node, it clears only the sticky lines that need to be rerendered.
