### ISSUE TITLE
Sync is not working

### ISSUE THREAD

**Issue by gopibabus** [microsoft/vscode#200596]
Type: <b>Bug</b>

Sync is not working

VS Code version: Code 1.85.0 (Universal) (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T18:18:04.614Z)
OS version: Darwin x64 20.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 7, 8|
|Memory (System)|16.00GB (0.50GB free)|
|Process Argv|--crash-reporter-id b10e9b4f-e258-48a0-9bf5-57b2b7caa5ce|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
-extra-intellisense|ami|0.6.4
-goto-view|cod|1.3.11
EditorConfig|Edi|0.16.4
copilot|Git|1.141.0
copilot-chat|Git|0.11.0
-create-view|gli|0.0.6
-blade-wrapper|IHu|1.0.1
vscode-peacock|joh|4.2.2
-goto-components|nao|1.2.0
-blade|one|1.34.0
-extension-pack|one|1.2.0
5-snippets|one|1.17.0
-jump-controller|pgl|0.0.33
-artisan|rya|0.0.31
vscode-blade-formatter|shu|0.23.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
0bi6i642:30917235
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by gjsjohnmurray** [comment]
Does your `Log (Settings Sync)` output channel contain any clues?

**Comment by sandy081** [comment]
Closing this because the the requested information is not provided.
