### ISSUE TITLE
Add a separate button for clean Terminal

### ISSUE THREAD

**Issue by yisibl** [microsoft/vscode#200510]
VS Code has always been able to clear Terminal only by binding shortcuts or shortcut menus. When debugging server logs, we will often need to clear the logs, and Chrome DevTools provides a separate button for that as well.

I can submit a PR for this.

![image](https://github.com/microsoft/vscode/assets/2784308/f86caf3d-40db-4ca2-a084-b05ddd24910e)

![image](https://github.com/microsoft/vscode/assets/2784308/3b061f15-6efa-44dc-95ad-b0436880b6ab)

**Comment by Tyriar** [comment]
This is actually already a feature but recently regressed. Clear Terminal is in the overflow `...` menu, and in the next release you'll be able to right click to show it in the panel again:

![image](https://github.com/microsoft/vscode/assets/2193314/115a76e8-1319-4a83-be40-211dc3ff29ae)
