### ISSUE TITLE
Terminal should advertise "Simple Browser"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#200579]
With a link such as:

<img width="422" alt="image" src="https://github.com/microsoft/vscode/assets/900690/149ec945-7e2c-4280-adb4-ec898ff7df1f">

Would be great to offer to open it in our "Simple Browser" editor:

<img width="696" alt="image" src="https://github.com/microsoft/vscode/assets/900690/0b2cfe35-3353-4a9f-bd2c-3d2fe4995dec">

**Comment by Tyriar** [comment]
Doing this would be a matter of registering a terminal link provider in the simple-browser extension:

https://github.com/microsoft/vscode/blob/83180a3d094d988162620cdee1ce32c997b90bc8/src/vscode-dts/vscode.d.ts#L11049

**Comment by bpasero** [comment]
Oh nice! I might take a look.

**Comment by bpasero** [comment]
Having played with this API for 5 minutes, here is some feedback: for one, there does not seem to be a related extension activation mechanism for detecting links, forcing me to `*`-activate the simple browser extensions.

But more importantly: it seems that I am taking over the entire handling of the link, even in presence of our default handler to open in the external web browser. I am not sure what I would expect, but my goal was just to give a hint that the link can optionally be opened in the simple browser as well, just as a way to make it discoverable in this case.

**Comment by Tyriar** [comment]
Yes I don't think there's an activation event, I don't think it's come up yet as GitLens and GHPRI are the main use cases.

For the default handler, this is currently handled within the extension itself. The hope was to eventually support multiple link handlers but was closed last year: https://github.com/microsoft/vscode/issues/97070

**Comment by hediet** [comment]
This feature would also be very interesting for the [edge dev tools extension](https://github.com/microsoft/vscode-edge-devtools) ([marketplace link](https://marketplace.visualstudio.com/items?itemName=ms-edgedevtools.vscode-edge-devtools)).
