### ISSUE TITLE
Group the Chat history by date

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#200574]
It is really helpful to have access to the chat history. When the history gets long it would be even more helpful when the chat history is grouped by date in the same way as the Timeline view. 

The current rendering is a flat list:
![Image](https://github.com/microsoft/vscode/assets/172399/d7f0c7e6-48f8-4345-9860-155040a8d93c)

**Comment by roblourens** [comment]
Reference

<img width="393" alt="image" src="https://github.com/microsoft/vscode/assets/323878/5afb530c-58e3-419d-8ce7-dc464264f1fd">

**Comment by isidorn** [comment]
This is done now.

![Image](https://github.com/user-attachments/assets/819368f2-f4e0-40ba-b4cd-07b8bf929975)
