### ISSUE TITLE
Rendering glitch when using the 'ChatAgentTask' progress report

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#200575]
Pls see the screenshot below

![Image](https://github.com/microsoft/vscode/assets/172399/c8e33554-580a-4a6c-86e7-e3a018466671)

The code is here https://github.com/egamma/codetour-agent/blob/6c6a8a82752a9f236e73a39799c513dc8466209f/src/extension.ts#L156

**Comment by roblourens** [comment]
You might actually want to send a `ChatAgentProgressMessage`. This will show the progress message with spinner and will automatically disappear when some content is loaded.

**Comment by egamma** [comment]
@roblourens 
>You might actually want to send a ChatAgentProgressMessage. This will show the progress message with spinner and will automatically disappear when some content is loaded.

Thanks, I've looked into this, but I haven't found the type `ChatAgentProgressMessage` in the `ChatAgentProgress` type in the `chatAgent2.d.ts`, pls see https://github.com/egamma/codetour-agent/blob/10dd6e92a700c04a0850072ebda52304ad45126f/src/vscode.proposed.chatAgents2.d.ts#L253

**Comment by roblourens** [comment]
I think you will get the latest version when you set your vscode engine version in `1.84` to `1.85`. I also might merge these two types: https://github.com/microsoft/vscode/issues/200598
