### ISSUE TITLE
Cannot copy/paste files anymore between folders

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#200581]
I am trying to `Cmd+C` a file in the one root folder and `Cmd+V` into another root folder and nothing happens anymore. Is this known?

I am using multi-root folder setup.

![Recording 2023-12-11 at 20 04 26](https://github.com/microsoft/vscode/assets/900690/fa0de413-715c-4f88-ae15-a1feb7872ff8)

**Comment by aliphys** [comment]
I can replicate this issue in VS Code 1.85.1.

Cannot copy-paste with both remote folders over SSH as well as local folders. Tried both drag-drop as well as `Ctrl+c` and `Ctrl+v`.

```
Version: 1.85.1 (system setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
```
