### ISSUE TITLE
Selecting text in debug console only selects text that is visible... 

### ISSUE THREAD

**Issue by jjmartin** [Microsoft/vscode#20052]
- VSCode Version: 1.9.0  (would be nice if you made the about selectable... ) 
- OS Version: Win 10

Steps to Reproduce:

1.  run something with a long output in the debug window (unit test output)
2. try to select text and scroll to select a large range of text extending beyond visible screen
3.  copy 
4 . paste somewhere -  only the visible text was copied....  scrolling up the window reveals that the text wasn't selected beyond the visible window.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/2163
