### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mmelvin23** [Microsoft/vscode#20053]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-angular2-files|alexiv|1.3.7|
|angular2-snippets|danwahlin|1.0.12|
|vscode-eslint|dbaeumer|1.2.2|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|Angular2|johnpapa|1.0.2|
|ng-bootstrap-snippets|ktriek|0.1.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|mssql|ms-mssql|0.2.0|
|PowerShell|ms-vscode|0.8.0|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.0.1|
|Spell|seanmcbreen|0.9.1|
|autoimport|steoates|1.2.2|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
More details please 👍
