### ISSUE TITLE
Cannot read properties of null (reading 'finishedPaste')

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#200597]
- Paste any text into the SCM commit message input
- Get this notification popup: `Cannot read properties of null (reading 'finishedPaste')`
- I can't find a stack trace in any log but it happens in every window so hopefully it's easy to repro. The paste text doesn't seem to matter

**Comment by roblourens** [comment]
Looks like this is from https://github.com/microsoft/vscode/issues/199908, will fail for simple editors that don't have a CopyPasteController.

**Comment by mjbvz** [comment]
Seems like it was introduced in #196516

**Comment by roblourens** [comment]
ha I was looking at that issue and guess I failed to copy the url
