### ISSUE TITLE
Merge ChatAgentTask and ChatAgentProgressMessage

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#200598]
https://github.com/microsoft/vscode/issues/200575 inspired me to consider whether we need two different message types here.

Currently the ProgressMessage is rendered at the top of the response and disappears when some content shows up.

The Task shows a placeholder with a spinner, which is then replaced by whatever its Promise resolves to. In theory, the Task could show a placeholder while more content is streaming in after it, and we have implemented it this way, but I don't think we use that ability and I question whether we actually need it? @joyceerhl what do you think?

If not, then these two messages could probably be merged. The new logic of ChatAgentProgressMessage could be to show the progress message with a spinner inline after any other content that has been received, and when more content is received after the progress message, the progress message disappears. That would keep the same behavior for `@workspace` progress messages and also could implement what `@workspace /new` gets from ChatAgentTask right now, with simpler implementation in vscode.

cc https://github.com/microsoft/vscode/issues/199908

**Comment by joyceerhl** [comment]
Yeah, I don't think we need that ability, and I was planning to adopt the new progress API anyway :)
