### ISSUE TITLE
Breadcrumbs widget does not get resized properly

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#200590]
- VS Code Version: stable
- OS Version: 

Steps to Reproduce:

1. Enable breadcrumbs
3. Create two editor groups
4. Resize one editor group to be as narrow as possible
5. Move editors between editor groups
6. :bug: breadcrumbs widget does not get resized properly sometimes

![image](https://github.com/microsoft/vscode/assets/25115070/58eb470d-3865-4d9f-8100-213cb5ec298b)

**Comment by jeanp413** [comment]
PR fixing it https://github.com/microsoft/vscode/pull/200591

**Comment by jrieken** [comment]
Do you have consistent steps to reproduce?

**Comment by jeanp413** [comment]
Updated the repro steps, added **Resize one editor group to be as narrow as possible**, using above repro steps is possible to repro, not on first try but maybe at the third one or so
