### ISSUE TITLE
MD content renderer is off

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2005]
We [have](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/htmlContentRenderer.ts#L283) a little markdown renderer that support bold, italic, and link but I think it wrong wrt to bold and italic. It uses `*` and `_` instead of `**` or `__` (bold) and `*` or `_` (italic). I might be wrong but at least it isn't consistent with markdown here on github.

**Comment by jrieken** [comment]
Unsure if this is you @bpasero

**Comment by bpasero** [comment]
@jrieken I am not sure who introduced that though, might be very old and I do not think the intent was to duplicate markdown but just have some way to provide more rich formatting in some UI places. We can change it to markdown but we have to adopt it everywhere then.

**Comment by bpasero** [comment]
@jrieken looks like Jeff (https://monacotools.visualstudio.com/DefaultCollection/_git/Monaco/commit/b345e4742e33197d24c817abf804d52f2e451400#path=%2Fclient%2Fvs%2Fbase%2Fdom%2FhtmlContent.ts&_a=compare).

**Comment by jrieken** [comment]
wow, long time ago. I wonder if we should leave it like that and add way to feed in markdown and a markdown lib (marked, markit) or just allowing some sort of plain html we are sure of doesn't harm

**Comment by bpasero** [comment]
@jrieken in what area would we allow markdown/html? is this for preview?

**Comment by jrieken** [comment]
nah, it's for hover over jsdoc comment that use markdown, like in our `vscode.d.ts` file

**Comment by bpasero** [comment]
@jrieken I see. I think it would be relatively straight forward to just pipe whatever is in the hover through our marked library which is already bundled with the markdown language (vs/src/vs/languages/markdown/common/marked.js). Maybe we keep it separate from our simple markup method so that we are not causing issues for existing clients.

**Comment by weinand** [comment]
@jrieken assigning to you since @bpasero removed his assignment.

**Comment by jrieken** [comment]
I'll add `{ markdown:string }` to the html content element

**Comment by jrieken** [comment]
closing this of duplicate of #1856
