### ISSUE TITLE
Sorting issue in the test coverage report view

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#200529]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.86.0-insider
Commit: 46a233646602c378c2168fa2a104dff8e8551558
Date: 2023-12-11T05:36:45.890Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.86.0-insider Chrome/118.0.5993.159 Electron/27.1.3 Safari/537.36

![image](https://github.com/microsoft/vscode/assets/6193897/e6436b24-e6e0-43ec-b1bb-87d954034ce6)

- `vet` should below `system`
- files(`xxx.java`) should below folders.

**Comment by connor4312** [comment]
Yes, currently we don't apply any sorting there

**Comment by connor4312** [comment]
Verification:

- Run some tests with coverage (e.g. VS Code's unit tests)
- In the Testing view container, see the Test Coverage view. Use the action in the view's navigation to change sorting and make sure it behaves as expected
    - (Note that Istanbul doesn't give us very nice names for functions in coverage data in most cases; a bunch of `anonymous` functions are expected)
