### ISSUE TITLE
Cannot rename or move files through VS Code

### ISSUE THREAD

**Issue by klaugust** [microsoft/vscode#200568]
Type: <b>Bug</b>

Create new folder in project, 
try to move files / folders around in directory.
throws error

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|10.1.0
copilot|Git|1.141.0
copilot-chat|Git|0.11.0
code-spell-checker|str|3.0.1

</details>

**Comment by gjsjohnmurray** [comment]
> throws error

Please give details.

**Comment by timint** [comment]
+1
Like in Notepad++. Right click tab, choose Rename to save to a new location or give a new filename.
