### ISSUE TITLE
"You are about to connect to a developer tunnel" warning prevents debugging on devices without peripherals

### ISSUE THREAD

**Issue by OysteinAmundsen** [microsoft/vscode#200541]
Trying to fix a bug only visible on an apple tv device when running my project. I'm using the port forwarding feature of VSCode, but the first panel displayed is a warning which can only be skipped by clicking the "Continue" button - which is impossible because the apple tv does not have any peripherals connected to it. I'm not sure if it is possible to connect any either. It does have a remote, but the remote cannot be focused on the button and the dialog can therefore not be skipped.

I would like to be able to turn off this warning message in the port forwarding setup. It could be default on, but should also be skippable when the tunnel is created, so that projects running on devices without mouse or keyboard can display the app through the tunnel.

**Comment by connor4312** [comment]
It sounds like the only solution would be removing the warning entirely as either keyboard or mouse input is needed. I don't think there's a way to do that, nor would we want that (cc @derekbekoe)

However, it seems like you are able to pair a bluetooth keyboard to the TV which may work... https://discussions.apple.com/thread/250298712?sortBy=best

**Comment by OysteinAmundsen** [comment]
It's ok. I can try to use ngrok instead. :-)

**Comment by connor4312** [comment]
Glad you found a solution that works for you!

@derekbekoe I think you could probably also accept input on that screen using the [gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API) for controller input.

I will close this issue though since it's upstream of VS Code.
