### ISSUE TITLE
On shell task run, terminal is not displayed if there's another open terminal in editor area

### ISSUE THREAD

**Issue by undeletable** [microsoft/vscode#200552]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.0
- OS Version: Linux x64 5.4.0-150-generic

Steps to Reproduce:

1. Open terminal (from top menu: Terminal -> New Terminal)
2. Move terminal to editor area (using menu displayed on click on terminal name). 
![moveterminal](https://github.com/microsoft/vscode/assets/6094468/5384f587-3278-4600-aa8d-ff569f15d530)
3. Launch a predefined task with `"type": "shell"` defined in `tasks.json` (from top menu: Terminal -> Run Task)

Expected Result:
New terminal with task output is opened in editor area. This was the behavior in earlier versions.

Actual Results:

- New terminal is not opened
- In order to see it, I had to open new terminal. It's displayed in bottom panel, which contains navigation to task terminal on the right. See it hovered:
![terminalnavigation](https://github.com/microsoft/vscode/assets/6094468/65ed169d-829c-491f-8c27-20440a5cc066)

**Comment by meganrogge** [comment]
This is working as designed. The panel closes when you move the terminal to the editor area. Tasks will run by default in the panel unless you change the `terminal.integrated.defaultLocation` to be `editor`. I am guessing that your task has `isBackground` true and thus, the panel does not show when you run it.

**Comment by undeletable** [comment]
Thank you for the response. `isBackground` is not set for my tasks. I've just set `terminal.integrated.defaultLocation` to `editor` and am happy with that, though the design behavior looks confusing to me.
