### ISSUE TITLE
Pinning a tab bug

### ISSUE THREAD

**Issue by VerfiyNull** [microsoft/vscode#200592]
Version: 1.85.0
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows x64 10.0.22621

( I am using a Python interpter )
Steps to Reproduce:

1.  Have at least 1 tab/file open
2. Pin the tab ( at the top )
3. Issue: The run button disappears 

It's a very very minor bug and simply you just open another file to have it reappear.

![Screenshot 2023-12-11 160737](https://github.com/microsoft/vscode/assets/62515427/d33d143d-b5bd-4f63-ad75-cd5f464a40c6)

**Comment by benibenj** [comment]
Thanks for reporting this! It lead to fixing this and other bugs we had :)

**Comment by VerfiyNull** [comment]
> Thanks for reporting this! It lead to fixing this and other bugs we had :)

I am glad to hear!
