### ISSUE TITLE
Inline chat shows "Accept" / "Discard" button for explainers

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#200580]
Steps to Reproduce:

1.  open inline chat
2.  ask it a question that does not result in code changes (e.g. anything with `/explain ...`)
3. the answer shows Accept/Discard buttons

![image](https://github.com/microsoft/vscode/assets/900690/22bea577-0e7d-42e1-b9db-c6784c6d651a)

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode-copilot/pull/3305
