### ISSUE TITLE
Windows 11 context menu still not presented after installing VSCodeUserSetup-x64-1.85.0.exe

### ISSUE THREAD

**Issue by swchung-at-ncsoft** [microsoft/vscode#200525]
Type: <b>Bug</b>

https://github.com/microsoft/vscode/issues/127365#issuecomment-1288556108 says that "a reinstall is required" and "it should be available in the December / January VS Code stable" in Oct, 2022 (=version `1.74.0`).

However, I can't get a context menu in the recent stable version. How can I fix this? I tried removal & reinstallation but nothing changed.

Fig 1: Installer for stable version(`VSCodeUserSetup-x64-1.85.0.exe`) shows options for files and *directory* context menu, which differs from installer for insiders(`VSCodeUserSetup-x64-1.86.0-insider.exe`) that only shows file context menu. It seems that the stable installer still recognizes my system as Windows 10 or lower.
![image](https://github.com/microsoft/vscode/assets/150996223/7171d38c-557b-4c0c-b40e-a75443894be3)

Fig 2: The context menu of my system after removing & reinstallation. Only the insider version shows the menu.
![image](https://github.com/microsoft/vscode/assets/150996223/57531227-c70f-4492-bff6-7cb204c47f70)

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (37.24GB free)|
|Process Argv|--crash-reporter-id bab445d8-3d13-4b32-a324-8e9457268c55|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260

```

</details>

**Comment by globi84** [comment]
Yes, I would be very interested in this feature. I also think that after a year of testing, such a feature should be included in the stable version.
