### ISSUE TITLE
Emmet multicursor snippets don't work as I remember them working

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#20056]
From our Interactive Playground

ul>li.item$*5

I remember this snippet resulting in 5 cursors at the right spot (i.e. 5 multiple cursors). It now creates 5 different tab stops each consisting of one cursor. I'm not sure if this change is intentional or not.

**Comment by ramya-rao-a** [comment]
This is now fixed with the new emmet model. Set `emmet.useNewEmmet` to `true`
