### ISSUE TITLE
Command highlight shows incorrect height when the original command is wrapped

### ISSUE THREAD

**Issue by amio** [microsoft/vscode#200602]
Does this issue occur when all extensions are disabled?: Yes

## Versions
Version: 1.85.0
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T18:17:50.719Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

## Steps to Reproduce

1. execute a long command that wraps
2. hover to the command ![image](https://github.com/microsoft/vscode/assets/215282/52f753b8-8918-4508-b5b3-983ee245da3a)

**Comment by joyceerhl** [comment]
On Windows I can repro for certain shells, e.g. this repros for Git Bash and not for pwsh
