### ISSUE TITLE
Ability to disable extensions by default

### ISSUE THREAD

**Issue by amirm3hdi** [Microsoft/vscode#20060]
When adding a new project folder, it takes a bit of time to disable extensions for workspace,
it would be good if there was a way to disable an extension by default.

Also, when installing a new extension, it gets enabled for all other projects too which takes time to disable for every project that doesn't need that ext.

**Comment by joaomoreno** [comment]
cc @sandy081

**Comment by sandy081** [comment]
@amirm3hdi This request looks similar to #15611. So making to a dup of that. Please vote for the feature in that issue if it is same. Otherwise please reopen this.

Duplicates #15611
