### ISSUE TITLE
Editor text zoom/change while the autocomplete menu is visible doesn't update line height

### ISSUE THREAD

**Issue by NDacevic** [microsoft/vscode#200631]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
var editor = monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});

function zoomIn()
  {
const action = this.editor.getAction(
      "editor.action.fontZoomIn"
    );
    if (action.isSupported())
    {
      action.run();
    }
 }
 

this.editor.addCommand(
      83, // keycode for the dash key (-)
      zoomIn.bind(this)
    );
```

### Reproduction Steps

1. Type something to make the autocompletion menu appear.
2. Hit the dash key (-) multiple times to zoom in a lot.

### Actual (Problematic) Behavior

Only the text in the menu gets larger while the html elements stay the same size.

![image](https://user-images.githubusercontent.com/54848417/207800254-7453bf1d-4b68-4f86-918d-968fef954f5d.png)

### Expected Behavior

The html should resize with the text appropriately.

### Additional Context

Zooming in first and then revealing the menu produces the correct sizes on everything.

It's possible that "editor.action.fontZoomIn" is the incorrect command to call in this case. Perhaps a list of commands could be provided?

**Comment by jrieken** [comment]
To verify

* bind a keybinding to Editor Zoom In/out
* trigger suggest
* while it shows, use the editor zoom keybindings
