### ISSUE TITLE
Python interpreter reads inputs slowly after plotting with matplotlib

### ISSUE THREAD

**Issue by aradley** [microsoft/vscode#200652]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.0 (Universal)
- OS Version: macOS 14.1.2 (23B2091)

Steps to Reproduce:
I use Visual Studio Code as an interpreter for Python and I am experiencing an issue on multiple Mac machines where after plotting and viewing a plot with the matplotlib package, the Python interpreter becomes much slower at reading inputs. This is very annoying for working on workflows and debugging code.

I have provided a video below to show how the issue can be reproduced. This video was recorded on a new M3 Mac with a fresh install of Python and Visual Studio Code.

https://github.com/microsoft/vscode/assets/17301771/eaaa4b38-5f56-4508-b68e-5a8383a8f201

**Comment by roblourens** [comment]
Not sure what's going on, I'm not sure where to send this. Any ideas @Tyriar @meganrogge?

**Comment by roblourens** [comment]
I wasn't able to repro it.

**Comment by aradley** [comment]
Yea, I'm just using, shift+enter, to run selection.

It's the evening here in the UK. Tomorrow I'll get the version information for Python and the installed packages to see if that helps you reproduce it.

**Comment by aradley** [comment]
Hi again.

Python version: 3.9.6
Installed packages:
anndata             0.10.3
array-api-compat    1.4
cESFW               0.0.1
contourpy           1.2.0
cycler              0.12.1
dill                0.3.7
exceptiongroup      1.2.0
fonttools           4.46.0
h5py                3.10.0
importlib-resources 6.1.1
joblib              1.3.2
kiwisolver          1.4.5
llvmlite            0.41.1
matplotlib          3.8.2
multiprocess        0.70.14
natsort             8.4.0
numba               0.58.1
numpy               1.26.2
p-tqdm              1.4.0
packaging           23.2
pandas              2.1.4
pathos              0.3.1
Pillow              10.1.0
pip                 23.3.1
plotly              5.18.0
ppft                1.7.6.7
pynndescent         0.5.11
pyparsing           3.1.1
python-dateutil     2.8.2
pytz                2023.3.post1
scikit-learn        1.3.2
scipy               1.11.4
seaborn             0.13.0
setuptools          69.0.2
six                 1.16.0
tenacity            8.2.3
threadpoolctl       3.2.0
tqdm                4.66.1
tzdata              2023.3
umap-learn          0.5.5
wheel               0.42.0
zipp                3.17.0

Note that cESFW is one of my packages, which you can install from https://github.com/aradley/cESFW, but I would be very surprised if this was the issue as it uses basic Python packages.

**Comment by roblourens** [comment]
I wonder whether this happens in an external terminal outside of vscode, with just pasting the text into the terminal with cmd+v?

**Comment by anthonykim1** [comment]
@aradley can you try running this in Python REPL launched from terminal like Rob mentioned? Totally outside of VS Code? Trying to figure out if this is problem for REPL in VS Code Python or some other.

**Comment by aradley** [comment]
Just did, and not only is it still a problem, but it was worse. 1187 times slower when just running Python through the terminal compared to 97 times slower in Visual Studio Code. 

Guess this isn't your problem then? Any idea where I should submit the problem? Either way, thank you for your engagement and help.

**Comment by brettcannon** [comment]
> Guess this isn't your problem then?

Probably not.



> Any idea where I should submit the problem?

If it only happens when displaying a figure, I would ask matplotlib.

**Comment by brettcannon** [comment]
https://matplotlib.org/devdocs/devel/contribute.html#submitting-a-bug-report is how to report a bug for matplotlib.

**Comment by aradley** [comment]
Cool, thanks for your help. I'll close the issue.

**Comment by aradley** [comment]
Issue appears to be outside of Visual Studio Code.
