### ISSUE TITLE
Pty Host disconnects when close any terminal

### ISSUE THREAD

**Issue by comedinha** [microsoft/vscode#200681]
Type: <b>Bug</b>

When close some window in vscode all another window terminals are crashed
I have disabled extensions and the error continues

Open some vscode window
Kill terminal (or use kill all terminals)
Try open terminal

Reproduction video: https://gyazo.com/f45365e8cb2c1b5e7815e5d30d852677

VS Code version: Code - Insiders 1.86.0-insider (72cb92fdc5d08101d65d59e4b1c046d397896dd2, 2023-12-12T05:36:41.973Z)
OS version: Windows_NT x64 10.0.26010
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (14.04GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 49af183a-8041-4fa8-ba25-9ac7d095d0af|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30901777
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2cf:30902440
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by comedinha** [comment]
Reproduction video: https://gyazo.com/f45365e8cb2c1b5e7815e5d30d852677

When I close some window in vscode all another window terminals are crashed

I think this is related to:
https://github.com/microsoft/vscode/issues/199227
https://github.com/microsoft/vscode/issues/200496

**Comment by decahedron1** [comment]
Also experiencing this. It appears it's caused by a ConPTY change in Windows 11 insider builds after 26002, as disabling `terminal.integrated.windowsEnableConpty` fixes it.

**Comment by kilotone** [comment]
So I hate to reopen this, but I have some insight on reproduction.

When using the conpty format, the Id's for specific instances of a rendered terminal seem to be mismatched on lookup and assignment.


Main -> [warning] No ptyHost heartbeat after 6 seconds

Pty Host -> [warning] Shell integration cannot be enabled for executable "C:\WINDOWS\System32\cmd.exe"

Shared -> [error] [uncaught exception in sharedProcess]: Event not found: onDidChange: CodeExpectedError: Event not found: onDidChange
at Object.listen (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:45:4959)

I can't reproduce consistently, but there seems to be differences in how the error logs through the different output available.

In one case it looks like there was an identifier lookup mismatch for what tracks the multiplexing between the virtual shells, and the actual instances. with one prefering a UUID to store the instance, vs the reassignment or killing looking for an integer.
