### ISSUE TITLE
Closing notebook diff editor tab also closes notebook

### ISSUE THREAD

**Issue by MarinMlinarevic** [microsoft/vscode#200683]
Type: <b>Bug</b>

1. Make some changes in a Jupyter notebook in a Git repository
2. Click on Source Control
3. Click on the notebook name to open diff editor
4. Close the diff editor tab

Result: The notebook tab is also closed.

Expected result: The notebook should stay open, just like text files do.

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (10.25GB free)|
|Process Argv|--crash-reporter-id e8a96201-29ce-407a-9506-937a3be04ace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
root-file-viewer|alb|1.2.2
project-manager|ale|12.7.0
gitstash|art|5.2.0
svg-gallery|dev|2.1.0
gitlens|eam|14.5.2
copilot|Git|1.142.0
copilot-chat|Git|0.11.0
gc-excelviewer|Gra|4.2.58
latex-workshop|Jam|9.15.3
rainbow-csv|mec|3.9.0
git-graph|mhu|1.30.0
vscode-dotnet-runtime|ms-|2.0.0
flake8|ms-|2023.10.0
isort|ms-|2023.10.1
python|ms-|2023.22.0
vscode-pylance|ms-|2023.11.10
datawrangler|ms-|0.22.2
jupyter|ms-|2023.11.1003402403
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.25.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.5.2023110609
remote-server|ms-|1.5.0
vscode-sanddance|msr|4.1.0
light-dark-toggle|pan|0.2.0
cython|tcw|0.1.0
pdf|tom|1.2.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyonecf:30548226
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by luchungi** [comment]
Same happens for the insider version

Version: 1.86.0-insider (user setup)
Commit: a017b12b9caa3475675cfe6fda014fcf5af388c9
Date: 2023-12-19T05:37:59.567Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22635

**Comment by jmigual** [comment]
I can confirm this issue. This is a recording of what's happening:


https://github.com/microsoft/vscode/assets/6493651/a48e342d-c45e-4d5c-9c79-4827e591ccef

**Comment by grapland0** [comment]
I think this issue get resolved with the latest update of vscode and all related extensions.

**Comment by grapland0** [comment]
bumping this as it causes data loss on some very common senerios.

**Comment by DonJayamanne** [comment]
This should now be fixed in VS Code insiders
