### ISSUE TITLE
The JSON Language Server server crashed 5 times in the last 3 minutes viewing any json file

### ISSUE THREAD

**Issue by davidsielertpge** [microsoft/vscode#200695]
Type: <b>Bug</b>

 I keep getting `The JSON Language Server server crashed 5 times in the last 3 minutes` when viewing a simple AWS IAM policy. I don't see any additional information provided even when enabling verbose logging. The only messages I see repeated in the developer console are an error about settings and a grammar file (See  screenshot)
![image](https://github.com/microsoft/vscode/assets/152447255/3668bf8e-3d7d-4f7e-a030-afc374b2af12)

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.99GB free)|
|Process Argv|--crash-reporter-id c1a8b369-c105-4210-8925-0b517152dd95|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
vscode-jq-playground|dav|4.3.5
gitlens|eam|14.5.2
terraform|has|2.29.0
jq-syntax-highlighting|jq-|0.0.2
black-formatter|ms-|2023.6.0
python|ms-|2023.22.0
vscode-pylance|ms-|2023.11.10
powershell|ms-|2023.8.0
vscode-yaml|red|1.14.0
even-better-toml|tam|0.19.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by aeschli** [comment]
Any chance you can share the JSON file that causes that?

**Comment by davidsielertpge** [comment]
It was all json files. But just to update it appears this was related to an organizational group policy to run VSCode as administrator. Since reinstalling as non-admin the lang server crashes are gone
