### ISSUE TITLE
Copy-paste causes editor to become unresponsive

### ISSUE THREAD

**Issue by onizhongxu** [microsoft/vscode#200611]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. vscode 1.85.0, operating system: windows 10
2. Just copy a file with ctrl+c in vscode,Then click New File in the folder where you copied the file, vscode will let you output the file name. At this time, you can paste the file you just copied with ctrl+v. At this time, vscode will become unresponsive and stuck.

**Comment by onizhongxu** [comment]
版本: 1.85.0 (user setup)
提交: af28b32d7e553898b2a91af498b1fb666fdebe0c
日期: 2023-12-06T20:48:09.019Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode/issues/200312
