### ISSUE TITLE
Add telemetry to when the code action lightbulb is shown

### ISSUE THREAD

**Issue by abner-math** [microsoft/vscode#200629]
If we could log events for when the lightbulb widget is shown to users and which kind of code actions it contains, we could get valuable insight on its usage. This is especially important now with AI code actions. With this kind of telemetry, we could monitor if displaying the lightbulb with a different icon for AI code actions increase or decrease click rate.

**Comment by mjbvz** [comment]
I suspect you meant to open this on Google's editor repo. We don't take telemetry additions from outside the team (if you do add this internally keep in mind that it's going to generate a huge amount of data as the light bulb is updated everytime the cursor moves)
