### ISSUE TITLE
Clear terminal blocks renderer for 1+ second

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#200660]
* open terminal
* run `./scripts/tests.sh`
* wait a little
* press `cmd+k` to clear
* 🧊 the renderer freezes for 1+ second doing `clearBuffer`

<img width="410" alt="image" src="https://github.com/microsoft/vscode/assets/1794099/85534df6-c3a3-46da-873b-70cc779418eb">

**Comment by jrieken** [comment]
Sorry, I cannot get electron/code-oss to save the profile file. Tho, this repos easy and zooming in show very many dispose calls, seemingly without yield

<img width="514" alt="Screenshot 2023-12-12 at 16 55 42" src="https://github.com/microsoft/vscode/assets/1794099/fa6790ae-a96e-4032-8eb2-d549702e170e">

**Comment by Tyriar** [comment]
Already planned 👌 https://github.com/microsoft/vscode/issues/199593 /duplicate
