### ISSUE TITLE
"Compare New Untitled Text Files" does not work properly with "Inline View"

### ISSUE THREAD

**Issue by Marcono1234** [microsoft/vscode#200693]
### Version

Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.85.0 (user setup)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T20:48:09.019Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

### Description
The "File: Compare New Untitled Text Files" command added for #165123 does not work properly when "Inline View" is enabled for the window (e.g. from before when you were viewing a Git diff).

For the "Inline View" you don't see two text editors but only one and therefore cannot properly compare two temporary text inputs, which is the functionality the "File: Compare New Untitled Text Files" command was added for.

### Expected behavior
For the diff window opened with the "File: Compare New Untitled Text Files" command, "Inline View" should always be disabled temporarily (without remembering this setting for regular diff windows opened afterwards) regardless of whether it was enabled before.

### Steps to Reproduce

Preparation (to make sure "Inline View" is already enabled):
1. "Run File: Compare New Untitled Text Files", or alternatively open a Git diff
2. Click on the three dots at the top right and select "Inline View" (in case it wasn't selected yet)
3. Close the editor tab

Bug steps:
1. Run "File: Compare New Untitled Text Files"
  :x: Bug: Only a single editor window is shown which is not usable for comparing two texts

**Comment by hediet** [comment]
You can use `"diffEditor.useInlineViewWhenSpaceIsLimited": false,` to disable automatic inline mode.
Or even
```
"[plaintext]": {
        "diffEditor.useInlineViewWhenSpaceIsLimited": false,
},
```
-> when language detection kicks in, it switches to the other mode.

We do not plan to address this issue otherwise, though I understand your problem.
