### ISSUE TITLE
Incoming/Outgoing section fails for long branch name

### ISSUE THREAD

**Issue by Zerthim** [microsoft/vscode#200636]
Type: <b>Bug</b>

1. Open Source Control with Incoming/Outgoing section enabled with branch that has long name - in my case 91 characters
2. Git output shows message `[info] fatal: failed to stat 'refs/heads/feature/` followed by local and remote branch names and finished with `: Filename too long`
3. Incoming/Outgoing section does not show in Source Control

For branch with 74 character name, Incoming/Outgoing section is correctly displayed.

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|14.5.2
zopeneditor|IBM|1.0.3
vscode-language-pack-pl|MS-|1.85.2023120618
vscode-extension-for-zowe|Zow|2.12.2

</details>

**Comment by IDrumsey** [comment]
Same issue here. My branch name is only 56 characters. It does use one level of nesting though (ie - `mysprint/myfeature...`)
Same git log.
Doesn't show changes under the Source Control tab and sometimes doesn't show all the buttons like the refresh button and commit check mark button.

Version: 1.85.1 (user setup)
Windows

**Comment by lszomoru** [comment]
This issue has been fixed in the latest VS Code [Insiders release](https://code.visualstudio.com/insiders/).

**Comment by TylerLeonhardt** [comment]
<img width="320" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/c34ce998-d9ae-473c-88c6-a5bc3bf5b9ac">
Looks verified 👍
