### ISSUE TITLE
Ubuntu 23.04 Random crashes

### ISSUE THREAD

**Issue by aaaaaaaalex** [microsoft/vscode#200644]
Type: Bug

>lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.04
Release:	23.04
Codename: lunar

Code keeps crashing with a generic crash dialogue.

Captured debug logs of crash attached.
[code.debug.log](https://github.com/microsoft/vscode/files/13648870/code.debug.log)

**Comment by aaaaaaaalex** [comment]
![image](https://github.com/microsoft/vscode/assets/35259825/cb451054-4524-483e-b9a0-ca5f06a79215)

Error dialogue I get

**Comment by aaaaaaaalex** [comment]
Oh - BTW:

```
> code -v
1.85.0
af28b32d7e553898b2a91af498b1fb666fdebe0c
x64
```

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/wiki/Native-Crash-Issues

**Comment by aaaaaaaalex** [comment]
[vscode_crash.zip](https://github.com/microsoft/vscode/files/13659911/vscode_crash.zip)

**Comment by deepak1556** [comment]
Crash due to OOM when parsing JSON in the workbench, however the crash reports are from older stable version `1.84`. @aaaaaaaalex can you repro the issue in latest stable `1.85` ? If so, can you run `Profiles: Create a Temporary Profile` and isolate steps to repro the crash.

**Comment by aaaaaaaalex** [comment]
Ah sorry forgot to mention I rolled back after posting the issue in an attempt to fix, but was getting the same error code and type of behaviour in 1.85. Will upgrade again and send on details, thanks.

**Comment by aaaaaaaalex** [comment]
1.85 crash attached.
[vscode.1.85.0-1701902998.crash.zip](https://github.com/microsoft/vscode/files/13663633/vscode.1.85.0-1701902998.crash.zip)

From a temp profile - the steps I can say to repro are: added the repo directories listed above to the workspace, then install Go extension, C/C++ extension, and GitLens. I have a hunch it is the Go extension in particular that may be causing this, but hard to be certain.

**Comment by aaaaaaaalex** [comment]
Update on this - I created a fresh profile and things were stable before adding extensions.
I added the recommended Go extension (the official google one), the recommended C/C++ extension pack, and GitLens.
This, in a workspace with the repo's I listed above is enough to trigger the crash for me.

**Comment by hwm1** [comment]
versions after 1.81.1 crash for me on ubuntu 16.04.  specifically i know 1.83 and 1.85 don't work for me.  i don't remember how 1.83 crashes, but 1.85 simply ends and disappears with no message when main menu items are selected.   the workaround is install 1.81.1 over the update :)
