### ISSUE TITLE
Codespace is not opening in the browser.

### ISSUE THREAD

**Issue by hyberson** [microsoft/vscode#200669]
ADD ISSUE DESCRIPTION HERE

That's pretty much it: the codespace is not opening in the browser.

Version: 1.85.0
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by hyberson** [comment]
Hello.
Thanks for asking. 
At the time, it meant that the Codespaces environment was "Opening Remote..." and nothing was happening. The editor wouldn't open.
Please see the image bellow.

![codespaces opening remote](https://github.com/microsoft/vscode/assets/26346753/2abb3739-5b36-45d4-a2ba-97c79f54f88c)

**Comment by joyceerhl** [comment]
Please provide details to the codespaces team at https://github.com/orgs/community/discussions/categories/codespaces

**Comment by hyberson** [comment]
Thank you for your help.
