### ISSUE TITLE
Autocomplete of <![CDATA[]]> is stupid

### ISSUE THREAD

**Issue by php4fan** [microsoft/vscode#200671]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.0
- OS Version: Manjaro Linux

Steps to Reproduce:

1. In an HTML file, try to type `<![CDATA[`

Expected behavior:
The IDE should either help me, or do nothing, but never get in my way.
A very convenient way to help me which is what most IDEs do is: when I type `<![CDATA[`, autocomplete it to: `<![CDATA[]]>`, with the cursor between the `[]`.

Observed behavior:
That, but with a stupid extra `]` at the end that I never typed, that was auto-added when I typed the first `[`, and now is after the entire tag.
So now I have to go to the end and delete it 

Watch it:

https://github.com/microsoft/vscode/assets/13969584/8c6c672e-65b7-4f0f-a69c-510e007dc564

**Comment by aeschli** [comment]
You can control completion of brackets with the setting: `editor.autoClosingBrackets`.
You can also do that per language, e.g. just for HTML:
```
	"[html]" : {
		"editor.autoClosingBrackets": "never",
	},
```

**Comment by php4fan** [comment]
Why are you closing this??
I don't want to disable autoclosing brackets, I want it to work as expected and not interfere with other autoclosings.

**Comment by aeschli** [comment]
Here's what I see with a plain VS Code, in HTML mode
![cdata](https://github.com/microsoft/vscode/assets/6461412/13c2f346-565d-494e-a820-a3e756d4b180)

I assumed that you don't like the auto completion of the `]`.

 Now I see that there's a completion of `>]`. Are you using an extension? Are you in HTML mode ? (see language named in the status bar)

**Comment by php4fan** [comment]
Sorry, it's XML, not HTML (my bad there).

I do have the PHP extension, but I did extension bisect and reproduced with no extension.

The behavior you show doesn't seem very useful either. What's the point in autoclosing the `]]` without the final `>`?

**Comment by aeschli** [comment]
Ok, I see. There's in fact a extra autoClosing rule for `CDATA`. It doesn't work together with the autoClosing rule for `[`
I'll remove the rule. That way HTML and XML are the same.

**Comment by php4fan** [comment]
> There's in fact a extra autoClosing rule for CDATA. It doesn't work together with the autoClosing rule for [
> I'll remove the rule.

Well that's an improvement over the current situation, but what about fixing the autoClosing of `<![CDATA[]]>` so that it _is_ compatible with the one for `[]`, instead of removing it entirely? Is it your standard approach for fixing features that are broken, to just remove the feature?

BTW if I'm not mistaken `<![CDATA[]]>` exists both in XML and HTML.

**Comment by php4fan** [comment]
This issue is not fixed. It should be reopened. See my previous comment

**Comment by aeschli** [comment]
The fix made sure that HTML and XML behave the same.

There are currently no plans to improve the completion the `<![CDATA[]]>`. Please file an feature request and I can put it up for a vote.
Or if you want to work on a PR, that would be great.

**Comment by php4fan** [comment]
You need a feature request for that? Pathetic.

**Comment by php4fan** [comment]
It seems that you have finally understood how this was supposed to work. NOW it behaves as expected.
