### ISSUE TITLE
Aux window: `increase current view size` doesn't consider floating windows

### ISSUE THREAD

**Issue by losnappas** [microsoft/vscode#200613]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.85.0
af28b32d7e553898b2a91af498b1fb666fdebe0c
x64

- OS Version: `Linux System-Product-Name 5.15.0-89-generic #99~20.04.1-Ubuntu SMP Thu Nov 2 15:16:47 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

Steps to Reproduce:

1. Open a new floating window with `View: New Empty Editor Window` (or any of the other ones)
2. Open a few split editors in the main view and the floating view
3. Focus a split in floating window
4. In the floating view, execute `Increase Current View Size`
5. The floating window editor size doesn't change, it happens in the main one

**Comment by bpasero** [comment]
Good catch, these commands should not be available in floating windows.
