### ISSUE TITLE
`Terminal Gpu Acceleration` setting `auto` should pick up the  `--disable-gpu` command line option

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#200696]
When disabling the GPU on Raspberry PI by running VS Code with the `--disable-gpu` command line option, I still see rendering issues in VS Code's integrated Terminal. These issues are fixed by turning off VS Code's `Terminal Gpu Acceleration` setting.

I would expect that the default `Terminal Gpu Acceleration` setting `auto` automatically picks up the `--disable-gpu` command line option in this case.

**Comment by Tyriar** [comment]
To action this we need to get the GPU status and check that when applying the GPU renderers here:

https://github.com/microsoft/vscode/blob/6fb7d0ae591d1076e1049c89d2187ab33558dab4/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts#L426-L432

GPU status is currently used in the issue reporter:

![image](https://github.com/microsoft/vscode/assets/2193314/aaa1c460-a25a-4870-ab2b-8e49b3e3d87b)

Which is hooked up here:

https://github.com/microsoft/vscode/blob/6fb7d0ae591d1076e1049c89d2187ab33558dab4/src/vs/code/electron-sandbox/issue/issueReporterService.ts#L1024-L1027

**Comment by Tyriar** [comment]
Don't need this anymore: https://github.com/microsoft/vscode/pull/223929#issuecomment-2253168780
