### ISSUE TITLE
Refactoring menu miss Move to file

### ISSUE THREAD

**Issue by codingwesley** [microsoft/vscode#200603]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 
- OS Version: 

Version: 1.86.0-insider (Universal)
Commit: 46a233646602c378c2168fa2a104dff8e8551558
Date: 2023-12-11T05:37:31.663Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin x64 19.6.0

typescript project ts file, Open refactoring menu, and miss move to file, other, I found support scenarios more less than before used vscode version.

![image](https://github.com/microsoft/vscode/assets/8223607/65833403-badd-4bbc-a4e6-eb2bc5334778)

**Comment by mjbvz** [comment]
This refactoring option is now only shown when the cursor is on the function name. Previously it also showed anywhere in the function body but this resulted in the lightbulb showing too often

**Comment by codingwesley** [comment]
"Move to file" is very useful function in my mind, Refactoring process use often, you can do it  any where if you want in ts project,  I must switch latest vscode version from "insider (Universal)" 


![image](https://github.com/microsoft/vscode/assets/8223607/ac8e9080-3ebe-4c28-9a69-a1b1aa8248c4)
