### ISSUE TITLE
Refractor method using mouse is not working as expected and is extremely slow after VS Code update to version 1.85.0.

### ISSUE THREAD

**Issue by suhail600** [microsoft/vscode#200607]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: **1.85.0 user**
- OS Version: **Windows 11 home 22H2**

**Steps to Reproduce:**

1. Open VS Code.
2. Navigate to a file with code that needs refactoring.
3. Use mouse option to bring up refactoring.(see the option is no triggered as expected)
4. Use the Ctrl + . shortcut to trigger the refactor options.
5. Then choose a refactor option using the mouse.(will see the option is now working)
6. Observe the behavior of the refactor operation.(very slow and not works some time)

**Description:**

After updating to version 1.85.0, the refactor method feature in VS Code is exhibiting issues when using the mouse. When attempting to refactor using the mouse, the options appear, but the actual refactoring does not occur. Additionally, the process is excessively slow, impacting the efficiency of the refactoring operation.

**Expected Results:**

Refactoring using the mouse should smoothly execute the chosen option without any delays.

**Actual Results:**

Refactoring using the mouse is not functioning as expected, and the process is unusually slow, affecting the overall user experience.

**Additional Information:**

VS Code Version: **1.85.0**
This issue started occurring after the latest update.
The problem is consistent across multiple systems running Windows.
Here is the video clip showing the bug explained.

https://github.com/microsoft/vscode/assets/62710125/e1389244-8c3d-4853-925f-0b8a033eb5f0

**Comment by justschen** [comment]
@suhail600 does this happen with `ctrl + shift + r` (the refactor keyboard shortcut), and what extensions do you have installed?

**Comment by suhail600** [comment]
> @suhail600 does this happen with `ctrl + shift + r` (the refactor keyboard shortcut) and what extensions do you have installed (the refactor options look like they are contributed by the Dart extension perhaps?)

the shortcut works the mouse refractor was not working , now somehow its working , so i am closing this issue. checked 2 to 3 systems with vs code faced this error all of them were working.
