### ISSUE TITLE
Tab Moves Focus should not re-enabled when restarting vsc

### ISSUE THREAD

**Issue by Esger** [microsoft/vscode#200720]
I understand this is a very important accessibility feature, but it is very annoying that pressing Tab doesn't do what it's meant to do in the editor for people without the need for this feature: indent a line or a block.

Therefore I suggest when someone disables the feature bij pressing the button in the footer or otherwise, it shouldn't be re-enabled after restarting vsc.

**Comment by gjsjohnmurray** [comment]
What is your `editor.tabFocusMode` setting?

**Comment by Esger** [comment]
In 'User' it was checked, in 'Workspace' unchecked. Unchecking it fixes my issue; thanks a lot.
I couldn't find that setting myself, searching for 'Tab moves focus' as the button in the footer states... I should have searched for 'tab focus' instead.
