### ISSUE TITLE
 Cannot read property 'getChildren' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#20078]
Issue Id: <b>2ea4075c-d1fa-4ea4-ebfe-bab442c4d84d</b><br /><br />*Versions* <br />- 1.9.0<br />*Stack* <br />TypeError: Cannot read property 'getChildren' of undefined<br />[/vs/workbench/parts/debug/electron-browser/debugHover.ts#L189:19 (getChildren)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/debug/electron-browser/debugHover.ts#L189:19 (getChildren))<br />[/vs/workbench/parts/debug/electron-browser/debugHover.ts#L207:58 (doFindExpression)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/debug/electron-browser/debugHover.ts#L207:58 (doFindExpression))<br />    at Array.map (native)<br />[/vs/workbench/parts/debug/electron-browser/debugHover.ts#L207:40 (map)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/debug/electron-browser/debugHover.ts#L207:40 (map))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/workbench/parts/debug/electron-browser/debugHover.ts#L207:4 (then)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/debug/electron-browser/debugHover.ts#L207:4 (then))<br />[/vs/workbench/parts/debug/electron-browser/debugHover.ts#L168:18 (findExpressionInStackFrame)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/debug/electron-browser/debugHover.ts#L168:18 (findExpressionInStackFrame))<br />[/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L195:27 (showAt)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L195:27 (showAt))<br />[/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L77:60 (showHover)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L77:60 (showHover))<br />[/vs/base/common/async.ts#L629:8 (runner)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/base/common/async.ts#L629:8 (runner))<br />

**Comment by kieferrm** [comment]
Over 4500 occurrences since 1.9.

**Comment by isidorn** [comment]
The worst is that the hover crashes and does not show a value in some cases (due to that not a candidate imho). Are those on 4500 different machines?

**Comment by kieferrm** [comment]
The ratio between machines and occurrences is approximately 1:9.
