### ISSUE TITLE
Strange split scrolling with vscode terminal

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode#200706]
Type: <b>Bug</b>

This is hard to explain so I created a video showing the problem. This has occured to a few times and not sure what is causing this, but it's messing up the terminal output.

https://youtu.be/-pJQXTltkyw

VS Code version: Code - Insiders 1.86.0-insider (46a233646602c378c2168fa2a104dff8e8551558, 2023-12-11T05:36:14.686Z)
OS version: Linux x64 6.6.3-1-default
Modes:

## System info

Operating System: openSUSE Tumbleweed 20231209
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.112.0
Qt Version: 5.15.11
Kernel Version: 6.6.3-1-default (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 5900X 12-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3080/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7A38
System Version: 8.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 3999)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 2|
|Memory (System)|62.71GB (45.46GB free)|
|Process Argv|. --crash-reporter-id 210d9130-10f4-4cf9-ad76-187d60112fd6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma5|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
ng-template|Ang|17.0.3
vscode-apollo|apo|1.20.0
markdown-preview-github-styles|bie|2.0.3
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
vscode-markdownlint|Dav|0.53.0
vscode-eslint|dba|2.4.2
java-decompiler|dgi|0.0.3
java-debug|DSn|0.0.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
rest-client|hum|0.25.1
java-properties|ith|0.0.2
plantuml|jeb|2.17.5
angular-file-changer|joh|0.0.4
vscode-peacock|joh|4.2.2
sort-typescript-imports|mic|1.4.1
vscode-docker|ms-|1.28.0
playwright|ms-|1.0.19
isort|ms-|2023.10.1
python|ms-|2023.22.0
cpptools|ms-|1.18.5
js-debug-nightly|ms-|2023.12.1117
live-server|ms-|0.4.13
angular2-inline|nat|0.0.17
platformio-ide|pla|3.3.1
java-ide-pack|pve|1.2.1
fabric8-analytics|red|0.7.3
java|red|1.25.1
vscode-commons|red|0.0.6
vscode-community-server-connector|red|0.26.14
vscode-rsp-ui|red|0.24.9
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
markdown-preview-enhanced|shd|0.8.11
vscode-checkstyle|she|1.4.2
java-generate-setters-getters|soh|8.0.0
sonarlint-vscode|Son|4.1.0
sass-indented|syl|1.8.28
find-then-jump|tra|2.0.5
sort-lines|Tyr|1.11.0
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.51.0
vscode-gradle|vsc|3.13.2023120800
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-lombok|vsc|1.1.0
vscode-maven|vsc|0.43.0
vscode-spring-boot-dashboard|vsc|0.13.1
vscode-spring-initializr|vsc|0.11.2
markdown-pdf|yza|1.5.0
vscode-aspell|zap|0.1.4

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
2i9eh265:30646982
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30901775
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by rajinder-yadav** [comment]
This is also happening with the main editor window. It is supper annoying and I would treat this as a critical bug.

The following image shows the same black split line appearing as in the video.

![snap-20231213-01](https://github.com/microsoft/vscode/assets/439226/883da593-bb83-49b4-9558-231220d376b8)

**Comment by Adam-Antios** [comment]
This is not a bug. It is the [sticky scroll](https://code.visualstudio.com/updates/v1_70#_editor-sticky-scroll) feature. You can disable it through Settings if you want.

![Screenshot 2023-12-13 125547](https://github.com/microsoft/vscode/assets/17729838/b5bcfc73-fc43-4662-a212-a40415fc46a4)

**Comment by rajinder-yadav** [comment]
> This is not a bug. It is the [sticky scroll](https://code.visualstudio.com/updates/v1_70#_editor-sticky-scroll) feature. You can disable it through Settings if you want.
> 
> ![Screenshot 2023-12-13 125547](https://private-user-images.githubusercontent.com/17729838/290165584-b5bcfc73-fc43-4662-a212-a40415fc46a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjkzMTYsIm5iZiI6MTcwMjUyOTAxNiwicGF0aCI6Ii8xNzcyOTgzOC8yOTAxNjU1ODQtYjViY2ZjNzMtZmM0My00NjYyLWEyMTItYTQwNDE1ZmM0NmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA0NDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZDljMjBiNDcyZTRmYmVjMGVhMmE2YmJiYmZiOTRjMjg0MGJjODkyYzhiYTFiOGY1MTg2NDRjNmUyNTg2MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DLrUsEzU-JxEJYQfrM-I6XKh-xgmbWZt-acxPCfmoMM)

wow when a bug is a feature, for real! 😂 ... thanks  I have disabled everywhere. How long has this feature been there?
