### ISSUE TITLE
Diff never resolves

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#200747]
Notice the error in the dev tools.

[Monaco editor playground repro](https://microsoft.github.io/monaco-editor/playground.html?source=v0.46.0-dev-20231212#XQAAAALFUwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscz7ore9k3Y3lj4dcH2Tvg7CoQ-F2f1REWC7PBN90IlpLvcflp2pp5-9Ef9ly7AC2fyF0LqLrPU1LlfRxN4mzDoPOtmoAZBIMwUApXP9vWg5rv8cBSZvD_CtH1OEKbGdQ7bG9FHjxeWcmMQA8XNqhoPLt9QlCLrhd88dsa2K7l65H6SpYEDeq1vdEZOz0M4LoD14Cmj8Fez_TH2LN85PoS3OPh-NwmOY6RNQ3lbc-I2x6DTwbJV8CrHrAnmBBnCreNliI27Jso9ikYm9vj3btsrb7v25yr4V-k69VxaI8fl7dYXPSRUl_8dQIPz1cTgBueVWPz1OFERTMuCSAYcnqvDjzAA-MAGvIcH8_dTbmSKBsEq3tAGoLbrOQNii-dqKIUHtd13qeDDmke2ei-REq1YfoV6nu0zOkrCgJyMtJkTxYKAvKxla7GCF3Uro2uF3xcaNdYxqTZItg5192-q5wRkqnIUIVW_GYdnV_JdFjYcLqvcjf05LCb0Qdbg0M0rTseaPrSS2PEDS2WcGSun3CndrVS1MTAmjwrc8Q0cdqZxu0PICzgoqlJP_q-_y0_3U2TUT-Z4WUok_M7usWpbxoCtigvyM_wPR5m0Gt0hzXgZwfw8EVPjK_G6d8PTkE4NeqWLc9xoZouieC0qgWnnogNrOlOKqzcoxzmNu-MQNfQCIttQMWURDIPxAQXt3YTXsNmA7tdVulS04r-_z7nsRAMHSkdFDZRdKytndapeb-Y51P6o8uPs8p_CUbW5DZ-wWOtCOGjtBbQJwd31uj2R7Wj6MmWPAU3_bb7v2yBpv890aKAaPdwQIRNTGbHVUofOwcTQG851kf2A9WaNlCGLd_pUC91up7BQ9Tw6T42KRd9DMswr6acdeCqp4CkKLn-b8xd1Nv0trijTglxPLaOqvl_Zikm_aYZfWiwyYIEc-N-2Q-S3aXM7K-dIM1Qe8tIzMJ1RUb7TaAkd9wmT_voIzXdeUz3OfRTdhPJTWpYEJmcCL4jYSXQ_2mP83HppP-suT5Fa8pm9Rh3m1wQlP2rP0qivIqFum_zRUpmAMV-BskBE28zvbTfANlF37OibRLOffB6FzwQz0jOuk8ziSp1ukCWAtj1PofuFWcv1l9iF5VquZZ1GkhjZo5_oNolDoekVHeIqbr1p5Da-wEyBG6BzyTY1bQPtnarXAbcaJCMN3q_jtmsHc-I0-XvW5lfLKWumTAwk_d4Qvdc_ZdTrl4sZ9rWhb6Z0dKP6ym4aLrCL5wHaoTKeQxfh9vg-xKpZ4Gqf17j0dgDH912j8Q_23P8sgole_9Y9RfHf4-jW1e5mw8HAt37wZLV6smsklubGbtdRssTvAjX79zaozfbgwR6gi22kMjIBRovc4VQz9uExBCMSQenDFLdQmuhguLLe_dHW5BXyHstf1gBrjMKMLlNN5AfEq-W1XTIbeKPZJcdYkW12f3u0idRSAeUlJvDWF7JucuKjHtOn7pLbCQLXDP0MkxlW9zlMreHpBW2Ava8sJkrGwOKGKL3dWV7eReBzn3A6Xyju5xKybSNVGaUrjn55u2wG3onjhRo2QWEf-0iiHSIsylvnQ9bkjiD0SzKuUVBK5X94pKQq_u-WNlDHM8pFNXkQO6zwIUYqqr8c60q_u2eNn2aQJ3hlS1i_hP-MX1p2N5GyP5r4roX1pd9A5UK8ca5_OUxJtJR9gyFXuIFhbW4vUJhrc-Oxz_sutFekL67w8Gx896m4_ekZfcRffHTdopOyVnjoWjrZQzDegI7_Sxqk96_O5LKc5ope3PRjUGt9mKOtz_f32EF_r-RDNBLPbKyB-9BLo0cWLuJXW4AFAQa6vlkd-ylAu2lpv5s3c1lz8PYudNY6WRSl2Rywq6eKBggYLCyM-hRLtpvpgYC1kjXOrkhnrkg0kqkNVTyHiQzpUWk7IjUfGNF4jajRUz-FQeoRVkfMMil2ROobcL7NLWiBL-IVt6wGoRCY17gqC4rxI-YQc582TOjbBv_SLXhkQvAsUODJI-ElbG42wmtrmWkToHrsjdiFBiibzHtsK09yXZFyxy16mrypkkd57GrDzP21XOIv7cxrHC06zs_XPxuBr49ELmDjSbOoHlDVqS1pmsc7RaM8ncNc8wlScCJA1KoFqAA-87CfVML4slYuz_zVjCRrG2qVf30w3LgFjr01hGEP9PZfxHF2hhO8D8CN2Y5PiXhVrRIfDPWCIYF3ZBdDvgrDfSYw2nBZYSRe9M3KjJy4bmS5t7Zp_szLDMxMYeV22NoeBq2rysPoILQSGNnboPRjvJQg1dUJ6Mqi7GaIAhJP8AefBzC5GuJYGK5bXVIaO-RoBoIyfmg9XW_JF0O_fNqvrvNWHnYH4iVxk5r-McUUkm5gWdmmUfD48WRhrTFHNKbQGEAvtG_E8GICndZaJxUUz5AUty56VgmN3kKVduqnU2OxWi2jm284HpNUB86GIfFYD_GLuI6EGohmISJO8Yr7j0HWNBZxvJcHYlKJuPNPJfLmeYBsPA7DfmNyNhS9-DWAo8oRc-hYRrebGJIgHXOt97W_62PGCebON5rGiX_x3zWWDKyfWMzUe1R54MU-rWW1ePudbfM78sWomQHO4JjxNx2ah7hzagZ3fPACmoyeR8NTnLgmfN2nm9PHyoKLvdBJPUYE52veY9sXaoqs6AYIVYRmgxaQE3NWumB5QAP2RJQsF09xqat2cckldqDtsphnV6-Qks3_b7HUdMDJFwzVhXfVIl8adDTpBBCqmbhyGWLSpy4tljqYpYoikFxnBBXsPbFY7L2FFn1L2jSP9QhoD8mKqohDLddTg841jHg_7YEZxSRoyiaxOy2DrsVI9jx4nevFfrHj4eIkc0SUB_9tunK3n8ryM2HH1bwwptnkiUVKo_9cCvW1h0YondhWKx39ZjnnEmixZPC8TPperly00iyP3Ekj5Vpl21JN60LjBdt1WCDfZvuBlyLlW4LXV0_QD5znVtfiA7J9VFt_Zgz7HtM86OmLDV9SSRXn24ix-Nc3c0g7Xh_hTZaJQkQuZiSJ9Qjz0H2bbNnUzWmpWwqqd41Fq0PdPsBIORhlVLbF6T2kcRumqyCZUh-S87Kqo8pyVlXcpPBCBDyfwXctI9JROos9unifBuK-3JsB7lpktYej1rguYtEoUDppG62-1hBp82w_Ywq1Wz-UVzy0jjcvJur3qLOSf707UMGRcb6ni95wE3DWTspMr6ht2ETNhhaqat7WZgi9WzOy4tgYs7sseP-Ll5d2HLTpLohdk4uCAAw9RQYPgbkhJaOSSB6bHBtq3eEboMc1NGaaXjc84T-Lx6XqUNGxenyuAw557awvVFWAnbSsn7Ihnr7lTr45Iv3jq3o5nmbs4dtKbCgj066gR5BdsoKXLy-VG4McFxAWSoEL4ryP8ddfAsx5mqKQIsIGAwavap05aRAhdCditabRi3GNnXtE3SEIL38Z8-6rXKZJ_M2_Ei-_zBsAo7RSNpcZdGPNl5XObr6i9b9_INxDCi-LdX_rwKtZc_T8SNjCsxM64Qbnme2-ShRoijvq0NeX2mn03ihPwbdfU4wm59XxS-k-FQg2AK5LjrGHVTzC-UTx6q3P_lWCplgxTlbQIl_HACz6g3NrJWsAotUSTzm9V9rxCI95ipmwOUDbzTek12plA1Wu4tZSz8cUQ5eUKtCBAnS2zwWKm75QrDmZY884o5Bze6hqM21vRxphXJ_rD_7l5k1zOFlDilGLCHaKXAvfZ3dFCbLxefBhB_4xUozm50HAY7Mx1lExfoXmxt_4AKLJLURDb9GP_P8xUxen8B2UPRUNDsZ-6q21VYRJBIOR5Apb321b4o-jkFKJOQhxpNumBKtPFdGyFVAW2ojk5D2fPOALvb2tQYhT5WIcowtDCMhuAHIgvU3AdOMMYoLgC5BY6t5nryf4XnUlEJmLbuy7-xKUGGca6Um0I24Ogg82c_e4l2kIkwuxk7s6yFh4utKKPIcINhZGJyYxreDPWFh9Mkw8oKccRqz1UJuVLYotMKgtmeQTjWDtp-P8P_lf-loHUiVPCjbhEUGlH7Gytareqt3rVDt6QmEy2HwsvSnr1JfR5X3PEdOF87uT1A6KTL3OPti3NqBTY0UeppTyKBP5FfXl7L4SMOfFuLRraCm2UxD0BrlxPa15BLmi2gAMa4eI3eqchifOnR5TT-DUBT7g4_ce79TGyqosPCumNA7Z_Mt-Oki5PtYmAi1-s8aJL7TlGepRe_lcru1XMHfGIcBZzn54rQDsalIEeoF5v3B8SUFrfPXbpjD4eehefXws1FyLbQBHGsPj9qZeNUeqmHcL3T0teQm_vt89wpyys6I_yM7BsBs6r5EvphDWM6-Qj_Hx_QD1orFAJoofv-4ftrGGOy80FHBGSyt0VGNfSxHX7B5BiYXPwrwAMRHBhxgrSlv3spG1R_ogMNWmJPqSn0EY9tMRJkk1sQkfcCmUC0ylwAMn-zXR2hMT23oTX78ZlSEXJK89y40oRsJBil8IrPlNW4JVbDrv0vIiSYFviuKusVuH_6Aptn_soEV015-Ko7_X7c8OAlbz7GIU2rtuL4zV38CcUXKgsCtn0LU-OiR3j57S0_EaJpiuWdCRveTkcW95efzk7epwxoBegB6lMhQkW6wKUsled4yGzmVN6NY5S1d13RindHpLAZKIzGlHKT-RRbTY-9HXztpKwDIUe6FHfnGsFZHbMpd8Dm2Zi1yWBksXhdG5nO1x8zGY0EeshA1TV7YL7znwWH_vpX0eSveHkmlRNHtzA62XDDRNFqQiNeWQ02YvEiPsJth5yLtATMQtUWIl2I-yejRnrT50yXkljz1eC5pGxv3Ugita48e1zmFCh2mz-6d-F5TOcLCtd8p1OQfadr8j8QLpQ9vFViqWUpgVhRq7YCOWpSzvy24-6iCSj7bZ5s4qDIlqPcUrahtdPFbhzbeejHCvPd22p8Jq7xG9o2NIP4h8go_iVkib1XfgitskES29g2aeq1gNRzG_M0o8nUWOc9Sm_R5azgdqXiOxVEDH_t19H0OZnzCpn13SL4VXQLJjsOcP4Zb8wG8fLO7BAb2WJB8apXGlhAovbS54XV9sqIGs767yaaVTUP1bf94iW6uWUXSOS8hMAhec5W50M_j4HlyWupfMEyOTh-O4EAzTBfYfa8-w06jDpDzY_sNpeGTbr6uuzUWNGUE4HQ2vS9T8lEWniGWgBz8VHG3bi55Un3lMwblhk6UK9ghwKoWbEYjbIojl9r8XCI8C5NO35ThRGln954b5wrpxeWIpiZ9nvUuEHjLVdWayX7LGuUBRkjWwQAGbeNZdC7Hfwd4V-qT9oAYSdd246KpECAswUTaEpQY282aXAUUg9h06TUGhyuD2ZB90ehGsgQ_ESKy4ceMAXysq8VwAAmWB0l-bx_npx6SjtYi7R3PvAtn-nozLreVMiyVxDoAez7CzvWr1TenpTLqGw4plDOeSP2i8FkBj_TXalpdPgJq0QdB1QWX2F1TxrcaBiW_smQWli1hpxf8Mu0ZAFEn_gKIbsWXTi4kjQ4fAvRBIRD-ZnlTHZTcEjE0MuFIDpi9WvoQal9FFonwitzZ4rbDxMV4TAV5hDXTXiNpnaJtwUaOQKP7hy0RHpdYH_SfvtYZyGyYZ2t6QYNbU1djswUm2JYvDUciY1G8dnQ0yJwdooL4zBrvhnslEWKgbjT9ayS_oRx_8Ojxs86RPi8OfkMcLTs-goo4xbUmX5GhygGzUoIn3fUnZgoOrhu4tebXCJgzeYFuwhHFKvFHt8ew1cEbRYY554eNFK_ghSYVNlriLNJNX_dhPuN6qro5LevRH5WWAoeEZJ50IZTFirFQr5IsPFjt3xXXY0dAZbLNBj1gdgUs2aDI0dB4PmoXuKUMSxp1JLAua69G7a7O1mOjn9949haRLjVgKdKUXaLwwmjnmhSQZo1cidGPWC2G4PwkyrYSKZKDFyTKm7QVM3r6eqf0ONLXJSfoT64qRhuEDflZ5bL0Iio8ttHWQkS943KBXaZFW6naFqKDSDZZd9W0YedsOdHVF7c3TpGh-ZVtht3tKs7_4R4lbx4wJbGThMMylTipLCWh4Qaq8_eqWoumZFIeovxN2G4CxwW5O8zadolW9U4dcmeJB11nYQl5hfn22GVI66_cw4ITHFQdsV-KZrEp2GiaZREdWVO_Kq8GTPS5lTXTWzz6jtyPs1NqAOVNo3qBWRhdldLPyZfg8PCmK7_QYLVuCtiBz9Th9s_KnIFRGvfmUwOE6IFHXmDNOJ7V76YHSSBABtuFqohuOWh3WUIVm3Jot6yIuVFzWXK4csaZ6o8Cqw28Ryj26CxBXkx1cNxDQ0vLkcIrIuK1xZ29JblXpivLB0_NGb0NWS1xp2ya57x7ygMB9tCj9poiFrKVttj3jtQ6sWGf-O2PSc0XT6_uIEntUV1xE7Qe4byqFXPWGK1B2VrCGiy_gOgy3SE3rJigkv7GZ2k-HcFB50GCQKwtQafrtDgcpJowxMkbfqNLNOD5HbJL5X6DhN3Yl_dipkbLvJyQFzeXjqj0QdVqf8iEP-ZuicXmvYW3IoP0_LOtDE7Qr6dXfIoHWMZ3gb-KIaNZ3R_-f7xW97Il9gQ8TVCGcLI4U7Xio6iHlkuynP1A7tZgHYJp8GfdBRxCPz7WpJx7sP2nq_xbGQ845Lwk9mdFuyeuiHyLWxYmo8AFtvN1nq8Khpo43c5h7sj_etqWSu9AG5iIUA8n7LKLiBFTBnCtqXF_z-debxNFZamnezXMulM0FnIA-JcZImkLjFZNTyTDx32lIalmZ0l0iNqCWXui0Xn05ALSUkmOILRzLOGG57eheEXmnzPJ3R3MJjEJ8d2U8MEDD9736_Pu_9y8Zic5JJNHmDmXDhjxtU5szniN1umKRstemqRkmWKqYEnUM7Dq42tuA_82pRfk)

**Comment by hediet** [comment]
Thanks for finding this! One of the very few bugs in the diff algorithm.
