### ISSUE TITLE
Allow to rename a folder that is opened in VS Code

### ISSUE THREAD

**Issue by mnquintana** [Microsoft/vscode#20071]
- VSCode Version: 1.9.0
- OS Version: macOS Sierra 10.12.3

### Steps to Reproduce:

1. Open a project folder
2. Rename it outside of VS Code (e.g. `mv project-folder-name new-name`)
3. Click on any file in the explorer – VS Code will throw an error: `Unable to open 'file-name': File not found`

I've been able to repro this consistently with all extensions disabled.

**Comment by bpasero** [comment]
@mnquintana to be clear, you open VS Code on a folder X and outside you rename that folder X?

**Comment by mnquintana** [comment]
@bpasero Yup, that's right! Ideally I'd love to see VS Code gracefully update to reflect the new name, but it'd also be good if there were a manual escape hatch to supply VS Code with the new path.

**Comment by bpasero** [comment]
I think this will be supported once we support multiple workspaces inside a workspace 👍

**Comment by bpasero** [comment]
This should be relatively easy to implement with the new [`WorkspaceService.updateFolders()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configuration/node/configurationService.ts#L120) API

**Comment by sandipb** [comment]
I am using this workaround to rename a workspaceFolder:

1. Open workspace settings
2. Rename folder from command line: `mv old new`
3. Rename the path in the folders settings of workspace, and save

VSCode immediately updates the workspaceFolder in the UI.

**Comment by bpasero** [comment]
Unfortunately I will close this "as designed". We have a ton of state that is associated with the workspace folder path that would need to be migrated to the new path.
