### ISSUE TITLE
light bulb not showing up for the first line properly.

### ISSUE THREAD

**Issue by heejaechang** [microsoft/vscode#200792]
Does this issue occur when all extensions are disabled?: it repro with `pylance`, but I can repro with `typescript` as well.

- VS Code Version: 
![image](https://github.com/microsoft/vscode/assets/1333179/6aa1411a-3597-4666-a13d-7732cd0b3b62)

- OS Version: windows 11 build 22621

Steps to Reproduce:

1. create python file
2. and save the file
3. write `sys`
![image](https://github.com/microsoft/vscode/assets/1333179/168ef0c6-4dd2-44d4-a649-0661b4ab66bf)
4. put caret at `sy|s`
5. make sure `EOF` is at the end of the `sys`

expected behavior: lightbulb shows up
actual behavior: lightbulb doesn't show up

if I move `sys` to next line, it works
![image](https://github.com/microsoft/vscode/assets/1333179/c961073b-6cb9-4148-8a4e-058f031ab6c0)

if I set `"python.trace.server": "verbose",` in `settings.json`, I can see `code action LSP message` is sent as expected.

``` json
2023-12-13 16:35:35.460 [info] Result: [
    {
        "title": "Add \"import sys\"",
        "command": {
            "title": "Add \"import sys\"",
            "command": "python.addImport",
            "arguments": [
                "... test file path ....py",
                {
                    "start": {
                        "line": 0,
                        "character": 0
                    },
                    "end": {
                        "line": 0,
                        "character": 3
                    }
                },
                "sys",
                null
            ]
        },
        "kind": "quickfix"
    }
]
```

it also repro with typescript

Steps to Reproduce:

1. create test.ts file
2. write `export class Test {  }`
3. create test1.ts file
4. write `Te|st` and put caret at `|`
5. make sure `EOF` is at the end of `Test`

expected behavior: lightbulb shows up.
actual behavior: it doesn't show up

if you move `Test` to next line, lighbulb shows up as expected.

if you use `vscode-insider`,
![image](https://github.com/microsoft/vscode/assets/1333179/144bbc34-3252-4dad-83c3-a98a4e4f1234)

behavior is slightly different, with same set up, lightbulb doesn't show up until 2nd char of the first line, but work after 2nd char.

**Comment by justschen** [comment]
I believe this is related to @aiday-mar with the new lightbulb setting?

**Comment by aiday-mar** [comment]
Hi I am looking into the issue. For the TypeScript example you gave on Insiders I see the following behavior:

https://github.com/microsoft/vscode/assets/61460952/408c52b2-32bd-44db-a9f4-ab8c667575aa

For the Python example you gave I see the following behavior:

https://github.com/microsoft/vscode/assets/61460952/781735f4-c5de-474f-846d-c07b9edf2be2

The lightbulb shows up for me. I am on the latest Insiders. 

Could you include a screen shot of what you are seeing and add details about what you would expect the behavior to be?
