### ISSUE TITLE
Unused import in `extensions/git/src/api/git.d.ts`

### ISSUE THREAD

**Issue by Malix-off** [microsoft/vscode#200796]
Unused import `ThemeIcon` from `vscode` from https://github.com/microsoft/vscode/commit/c05b49710b0fff24aa4380751e02b53c54e784ce?diff=split#diff-839abdd5d0c5ed04bbf6e6103392ae0ce12bfd1c97ad2d223d32a5e30f5a49edR6 in https://github.com/microsoft/vscode/commit/1466cbfcdf232a4fd145769a1831b184bde3981d#diff-839abdd5d0c5ed04bbf6e6103392ae0ce12bfd1c97ad2d223d32a5e30f5a49edL6

**Comment by osbyrne** [comment]
bruh
