### ISSUE TITLE
Terminal character display error, when there are lots of prints in the program

### ISSUE THREAD

**Issue by StaringInfinity** [microsoft/vscode#200752]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.0
- OS Version: win10

Steps to Reproduce:

1. Setting >> Terminal.integrated.**GpuAcceleration: off.**
2. Ctrl+Shift+P, >**Preferences: Configure Runtime Arguments**, **"disable-hardware-acceleration": true**. (I encountered this issue on a computer without a GPU. On a PC with GPU, this setting is required to repro). 
3. Restart vscode. (Not just reload window ).
4. Open a folder, Debug a C/C++ program that prints a lot. (For example, loop printing "hello world").The C/C++ extension I use is ms-vscode.cpptools 1.19.1.
5. Terminal characters display extra spaces, and there is also something wrong with selection rendering.
Here is a video demonstration:

https://github.com/microsoft/vscode/assets/49320365/1dc15f8a-be9c-4da1-a2c5-e0d46d347fd0

If change Terminal Font Size, the terminal display will work normally

https://github.com/microsoft/vscode/assets/49320365/f3d4c795-1f5c-478f-a817-a6f4a3ea4ac8

**This issue can be reproduced from version 1.83.**

**Comment by StaringInfinity** [comment]
There is another related problem. It's about  terminal selection background color. 

setting
Ctrl+Shift+P, >Preferences: Configure Runtime Arguments, **"disable-hardware-acceleration": true**. (On a PC without a GPU)
Terminal.integrated.**GpuAcceleration : auto**.

The terminal selection background color become very light.
![image](https://github.com/microsoft/vscode/assets/49320365/05207c66-2785-4c5e-960f-70bd5775916b)
This phenomenon occurs in versions after v1.82

The original  terminal selection background color
![image](https://github.com/microsoft/vscode/assets/49320365/e5f744cc-b4df-42ce-8ac9-2a2e9d98a30c)

**Comment by Tyriar** [comment]
The selection issue is this which happens if you're using the canvas renderer: https://github.com/xtermjs/xterm.js/issues/3937, since you disabled GPU acceleration in VS Code and had gpuAcceleration to auto, the webgl renderer was not used and it fell back to the CPU-based canvas renderer which has some limitations.

**Comment by StaringInfinity** [comment]
Oh, I get it.  The canvas renderer's color is light. I haven't tried to choose canvas before.
But in the version before 1.82 (version<=1.81.1), when I disabled GPU acceleration in VS Code and had gpuAcceleration to auto,
It should not have fallen back to the CPU-based canvas renderer.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/194156

The selection color should be consistent now. The canvas renderer has also been removed completely.
