### ISSUE TITLE
Please restore the configuration "window.experimental.windowControlsOverlay.enabled" to support placing developer tools on the right.

### ISSUE THREAD

**Issue by cweijan** [microsoft/vscode#200794]
@deepak1556 @bpasero @sbatten I am an extension author developing using webview api, I used "window.experimental.windowControlsOverlay.enabled" to put the developer tools on the right side, but in the new version it was deprecated #188793, please restore it.

In order for the developer tools to be positioned on the right side, I now have to go back to VS Code version 1.81 and disable updates.

Version 1.81:
![11](https://github.com/microsoft/vscode/assets/27798227/deae5de0-bed3-4d98-b46a-f1089cd232be)

Newest Version:
![222](https://github.com/microsoft/vscode/assets/27798227/447c1214-e3ca-4de3-a889-94d9ef1abba0)

**Comment by cweijan** [comment]
My extension is https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2, which uses many webview views, so I need to use the developer tools frequently.

**Comment by sbatten** [comment]
@deepak1556 I don't really like bringing back that setting unless we have to, is it something that can be fixed upstream?

**Comment by deepak1556** [comment]
The devtools behavior with WCO was inherited from chromium PWA and there are no plans in upstream in fix this currently, https://github.com/microsoft/vscode/issues/168454#issuecomment-1697135264 for context.

**Comment by sbatten** [comment]
Okay, so we must bring this setting back to support other configurations in the near term?

**Comment by deepak1556** [comment]
The user can still position the developer tools to the right side using snap layout on the undocked devtools. Given bringing back the setting is not trivial and the issue can be worked around I am not in favor of bringing back the setting.

**Comment by cweijan** [comment]
I avoided this issue by switching the operating system to Mac OS😁.
