### ISSUE TITLE
`testRun.appendOutput` formatting is the same as test failure formatting.

### ISSUE THREAD

**Issue by ioquatix** [microsoft/vscode#200716]
When adding output to a specific location using `testRun.appendOutput`, the UI element is coloured red as if to indicate a test failure or problem.

<img width="941" alt="image" src="https://github.com/microsoft/vscode/assets/30030/ab4ac09d-3575-4a0d-86ba-a3c6349daab3">

However, this is not desirable. I believe we should be able to control this formatting, as it may relate to one of the following:

- Informational feedback about the test (performance, throughput, etc).
- Non-fatal test status, e.g. skipped tests.
- Debugging output.

Perhaps in the first iteration, if output is specified by a failing test, a red coloured UI is appropriate, but in every other case it could be a neutral colour (grey, blue, etc).

cc @connor4312

**Comment by ioquatix** [comment]
Awesome, thanks for the quick turn around. Do you mind explaining the conclusion? Any new public interface for selecting formatting? etc.

**Comment by connor4312** [comment]
Normal `appendOutput` is shown as (in default themes) blue, and the peek is only red if a failure/error message is being displayed
