### ISSUE TITLE
Shell integration failed to activate

### ISSUE THREAD

**Issue by oblason** [microsoft/vscode#200757]
JavaScript Debug Terminal
这Java.. C
Kill (D
Process ID (PID): 16368
Command line: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
no exit` '-command* "try (. "c:\Users\User\AppData\Local\Programs\Microsoft VS
Code\resources\app\out\lvs\workbench\contrib\terminal\browser\media\shelllntegrati
on.ps1") catch f
Shell integration failed to activate
n Reader Optimized
Ln 11, Col 56 (51 selected)
Spaces: 4 We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by garveyhu** [comment]
I have the same problem

When entering the terminal for the first time, you can open the terminal. Occasionally, it shows that the terminal is disconnected. At this time, the terminal icon turns red. Delete all terminal shortcuts ctrl+ ` to open the terminal. Terminal blank.
![Uploading image.png…]()

**Comment by garveyhu** [comment]
只有重启vscode才能正常生效终端，而且这个终端一定时间后也会中断，一旦手动把所有的终端删除，新建的终端都是空白的，我在另一台win11电脑试过也是一样的，有趣的是另一台win10是可以的（所有的vscode都升级到了最新版）

**Comment by joyceerhl** [comment]
Can you please share terminal logs: https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by garveyhu** [comment]
@joyceerhl 
This is my log terminal.log file:
2023-12-15 15:56:32.316 [trace] [1422fbe] Reconnected to local terminals []
2023-12-15 15:56:32.317 [trace] [1422fbe] Pty host ready []
2023-12-15 15:56:33.889 [trace] [1422fbe] terminalInstance#ctor (instanceId: 1) [{"executable":"C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe","icon":{"id":"terminal-powershell"}}]
2023-12-15 15:56:34.659 [debug] [1422fbe] The terminal's pty host process is starting []
2023-12-15 15:56:34.912 [debug] [1422fbe] Unbinding from mouse events. []
2023-12-15 15:56:34.964 [debug] [1422fbe] Starting pty host []
2023-12-15 15:56:34.964 [trace] [1422fbe] Renderer->PtyHost#connect: before acquirePort []
2023-12-15 15:56:35.079 [trace] [1422fbe] Renderer->PtyHost#connect: connection established []
2023-12-15 15:56:35.222 [trace] [1422fbe] Webgl was loaded []
2023-12-15 15:56:36.361 [debug] [1422fbe] Terminal process ready (shellProcessId: 21368) []
2023-12-15 15:56:36.509 [debug] [1422fbe] terminalInstance added capability [3]
2023-12-15 15:56:36.758 [debug] [1422fbe] parsing data "[?9001h[?1004h" [[27,91,63,57,48,48,49,104,27,91,63,49,48,48,52,104]]
2023-12-15 15:56:36.760 [debug] [1422fbe] sending data "[O" [[27,91,79]]
2023-12-15 15:56:36.761 [debug] [1422fbe] parsing data "[?25l[2J[m[H

**Comment by Tyriar** [comment]
What version and build of Windows are you on? You can run `ver` in cmd.exe to get this

**Comment by oblason** [comment]
Edition	Windows 10 Home
Version	22H2
Installed on	‎10/‎18/‎2021
OS build	19045.3803
Experience	Windows Feature Experience Pack 1000.19053.1000.0
but I restarted it three times and it didn't work yet what other things I can do? this restart doesn't fix the problem.

**Comment by garveyhu** [comment]
Microsoft Windows [version 10.0.26002.1000]

**Comment by garveyhu** [comment]
Now the terminal link problem has seriously affected my use of vscode, you know the editor without terminal, and another colleague of mine also has the same problem as me

**Comment by garveyhu** [comment]
![image](https://github.com/microsoft/vscode/assets/63913508/2a43071b-9004-44bc-ab60-60bc932cc041)
@TyriarWhen I first opened the terminal background under vscode the terminal process worked fine
![image](https://github.com/microsoft/vscode/assets/63913508/f5bf6fc1-450e-48b0-9636-f95c909d3930)
When I kill the terminal, the process still exists, and the next time I open the terminal, it will not connect to the blank display
![image](https://github.com/microsoft/vscode/assets/63913508/199c4aec-0411-4ee7-b626-eb42d9b53e78)
It seems like the terminal won't kill, powershell shut down but there is still a console window that the host doesn't kill so the next time I open the terminal it seems to get stuck, it seems vscode had a problem closing the terminal last time
![image](https://github.com/microsoft/vscode/assets/63913508/60dc5cd0-4de1-4bd7-9dff-08771b6fe1d7)
This is my last operation, the resource manager manually aborted the console window host, my blank terminal disappeared, and the last initial open terminal came out normally, which also confirmed that the last closed terminal did not really kill clean

**Comment by Tyriar** [comment]
> Shell integration failed to activate

There's not enough information to action this so closing. Generally seeing this means your shell isn't compatible with VS Code's shell integration. You can try setting `terminal.integrated.experimental.windowsUseConptyDll` to bring you on the new backend, but other than that you would need to investigate where the failure is happening on your end.

> I have the same problem
> 
> When entering the terminal for the first time, you can open the terminal. Occasionally, it shows that the terminal is disconnected.

This problem is unrelated to the original report
