### ISSUE TITLE
Merge editor should automatically resolve conflicts that are identical

### ISSUE THREAD

**Issue by queglay** [microsoft/vscode#200704]
If a conflict is generated where a current section of code is identical with the incoming this can show up as a conflict (when the change exists in both current and incoming branches ).  
Currently it shows up as a conflict, but its not necesary.  It would be fine to automatically resolve it.

**Comment by hediet** [comment]
We do this already:

![Image](https://github.com/microsoft/vscode/assets/2931520/3a1f44f0-7502-4518-a056-75be45f0fbab)

[merge-conflict-demo.zip](https://github.com/microsoft/vscode/files/13659984/merge-conflict-demo.zip)
