### ISSUE TITLE
Test Result Panel has some strange styling

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#200703]
Version: 1.86.0-insider
Commit: 72cb92fdc5d08101d65d59e4b1c046d397896dd2
Date: 2023-12-12T05:36:41.973Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.86.0-insider Chrome/118.0.5993.159 Electron/27.1.3 Safari/537.36

It's the same issue as https://github.com/microsoft/vscode/issues/196521. Since that issue is locked and the related issue is closed, but I still can see this strange style in the test results panel. So, I have to create a new one.

Steps to Reproduce:

I haven't found a way to reproduce it using the extension sample. It's reproducible in the Java test runner extension. What the extension does is just simply append plain text to the output via `appendOutput()` api: https://github.com/microsoft/vscode-java-test/blob/22a11be0c6074c536e40b7b2e4c8fdb05c8803dd/src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts#L55

And I found a pattern that if I click the `Clear All Result` button, then the text rendering will become normal afterward.

Here is a video:

https://github.com/microsoft/vscode/assets/6193897/e04ff2fd-a64f-4f49-9ea1-e5c9a40fa60f

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/194156, reopened that issue
