### ISSUE TITLE
GitHub Copilot error

### ISSUE THREAD

**Issue by Miaotilo** [microsoft/vscode#200724]
GitHub Copilot could not connect to server. Extension activation failed: "Cannot read properties of undefined (reading 'onDidPerformUserAction')"
```[tasklist]
### Tasks
```

**Comment by Miaotilo** [comment]
Today, suddenly the Copilot plug-in cannot be used. I have tried the following methods: closing the client, logging out and logging in again, switching to an old version of Copilot, but none of them work. Can anyone help me solve the problem?

**Comment by smurtym** [comment]
I am also facing the same issue. First I am getting this error
 GitHub Copilot could not connect to server. Extension activation failed: "Cannot read properties of undefined (reading 'onDidPerformUserAction')"

After retry I am getting this error
 GitHub Copilot could not connect to server. Extension activation failed: "Cannot read properties of undefined (reading 'onDidPerformUserAction')"

**Comment by ulugbekna** [comment]
Hi, could you please show logs where you're seeing this error to get more context? 

Also, please mention the versions of vscode, "copilot" and "copilot chat" extensions

**Comment by drelbert** [comment]
Getting the same message as above.  Thanks for taking a look @ulugbekna.   
vscode version = 1.69.2
copilot version = 1.84.51

from output  = 
[INFO] [copilotIgnore] [2023-12-13T15:45:54.125Z] inactive
[INFO] [codequote] [2023-12-13T15:45:54.125Z] CodeQuote enabled
[INFO] [copilotIgnore] [2023-12-13T15:45:54.128Z] inactive
[INFO] [codequote] [2023-12-13T15:45:54.128Z] CodeQuote enabled
[ERROR] [default] [2023-12-13T15:45:54.129Z] GitHub Copilot could not connect to server. Extension activation failed: "command 'codequote.openMatchPanel' already exists"

**Comment by Franky1** [comment]
Same for me:

```log
[ERROR] [default] [2023-12-13T21:11:43.613Z] GitHub Copilot could not connect to server. Extension activation failed: "Cannot read properties of undefined (reading 'onDidPerformUserAction')"
```

- Copilot Version `v1.84.51`
- VSCode Version:

```log
Version: 1.72.0 (user setup)
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Datum: 2022-10-04T23:20:39.912Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
Betriebssystem: Windows_NT x64 10.0.19045
Sandkasten: No
```

**Comment by Franky1** [comment]
Probably the reason was, that vscode automatically **disabled** updates, without me knowing, because i had installed it previously with administrator rights on windows. After i downloaded the system-wide installer for vscode, i got the latest vscode version `1.85.1` and the copilot plugin worked again.

**Comment by tauseedzaman** [comment]
getting the same issue guys

**Comment by tauseedzaman** [comment]
![image](https://github.com/microsoft/vscode/assets/64689921/f658ace0-ab5e-4e01-bac8-ccd553a412ff)

**Comment by tauseedzaman** [comment]
i downloaded vscode v1.85.1 but now getting this error 
![Uploading image.png…]()

**Comment by Miaotilo** [comment]
I rolled back the Copilot version to v1.77.9225 and it can be used normally.

**Comment by QAQQL** [comment]
So how can I solve this problem?

**Comment by LeNotFound** [comment]
> 我将 Copilot 版本回滚到 v1.77.9225，可以正常使用。

非常好解决方案，使我的copilot正常工作，爱来自vscode 1.70.2❤
