### ISSUE TITLE
Extension tests are broken on Mac OS (Both CI and local)

### ISSUE THREAD

**Issue by ecmel** [microsoft/vscode#200708]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.85.0
- OS Version: Mac OS Sonoma 14.1.2

Steps to Reproduce:

1. If exists remove `.vscode-test`
2. run `npm test`

The following error occurs:
```
Downloaded VS Code into .vscode-test/vscode-darwin-arm64-1.85.0
Test error: Error: spawn .vscode-test/vscode-darwin-arm64-1.85.0/Visual Studio Code.app/Contents/MacOS/Electron ENOENT
Exit code:   -2
Failed to run tests.
```

The problem is the file is located here:
```
.vscode-test/vscode-darwin-arm64-1.85.0/Contents/MacOS/Electron
```

This was working yesterday, the new downloaded archive has a different directory structure. CI tests are broken as well, check https://github.com/KxSystems/kx-vscode/actions/runs/7191001314

**Comment by ecmel** [comment]
1.84.2 works fine https://github.com/KxSystems/kx-vscode/actions/runs/7220687511

**Comment by connor4312** [comment]
What version of @vscode/test-electron are you using?

**Comment by connor4312** [comment]
Please update to the latest version of @vscode/test-electron (2.3.8) where this is fixed. [You're on 2.3.6](https://github.com/KxSystems/kx-vscode/blob/25727dcd06e9fa4ef8c0a5ac9b6b4f92a8ade6d3/package-lock.json#L967).
