### ISSUE TITLE
Support drag and drag between items in the list

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#200745]
@connor4312 suggested in https://github.com/microsoft/vscode/issues/151284#issuecomment-1151313117:

> I way I've seen to do this is to have "edges" so that dragging a tab in a small area between two tabs would have a horizontal highlight bar between them, and rearrange. While dragging tab more directly atop another tab highlights the tab itself and will split them.

The problem we're trying to solve here is how to split the terminal groups where the group is presented "inline":

![image](https://github.com/microsoft/vscode/assets/2193314/8b8e38b7-7753-4f9d-ae96-77d0fdab4548)

We decided at one point that it's confusing when drag and drop splits or unsplits depending on where it's dropped, but some other feature like this could help with this ambiguity. If we do this we should have a chat and decide together about the exact behavior we're planning on.

**Comment by benibenj** [comment]
Lists/Trees now support drag and drop between items. This can be tested in the Open Editors View (Supports multi select drag and drop) and in the Debug Watch Expressions View.
