### ISSUE TITLE
`testRun.appendOutput(message, uri, test)` appends output to Test Results incorrectly.

### ISSUE THREAD

**Issue by ioquatix** [microsoft/vscode#200715]
- VS Code Version: 1.85.0
- OS Version: macOS 14.1.1

I'm using the following to output informational messages captured during the test run:

```javascript
	inform(data: any) {
		const test = this.tests[data.inform];
		
		this.messagesFor(data).forEach(message => {
			this.testRun.appendOutput(message.message.toString(), message.location, test);
		});
	}
```

It seems to come out in the correct place:

<img width="944" alt="image" src="https://github.com/microsoft/vscode/assets/30030/125fd258-9200-4592-972d-6382b5fa25ef">

However, it also comes out in the test output buffer, messing up output formatting:

<img width="720" alt="image" src="https://github.com/microsoft/vscode/assets/30030/23ea1664-afdb-43a2-afc7-a71874deedda">

A message that is attached to a location should not also be printed in the Test Results.

This may be also related to / solved by the ideas proposed in <https://github.com/microsoft/vscode/issues/174802>.

cc @connor4312

**Comment by connor4312** [comment]
This is as the API is designed (and changing it would be a breaking change at this point.) `appendOutput` is used for messages that appear in the console output of the test run.

Note that you can make it a little prettier by surrounding it with other data, like

```js
run.appendOutput(`Output from ${testName}:`);
lines.forEach(line => {
  run.appendOutput('\t')
  run.appendOutput(line, location, test);
})
```

**Comment by ioquatix** [comment]
Okay, should I open a feature request then, for a mechanism to add output to specific lines, without outputting it in the test results window?
