### ISSUE TITLE
Currently there is no provision to scroll down the page 

### ISSUE THREAD

**Issue by Mayanks0307** [microsoft/vscode#200733]
Currently, there is no provision to scroll down the page to bring inline suggestions into view if it is outside the visible area.
If the suggestion is big for suggestion is half outside the visible area then there is no provision to bring the inline suggestion into the visible area.

**Comment by hediet** [comment]
Can you share a screenshot?

**Comment by Mayanks0307** [comment]
<img width="1049" alt="Screenshot 2023-12-13 at 8 28 33 PM" src="https://github.com/microsoft/vscode/assets/98150135/bece68bc-2d83-4665-bd9a-5e363e10327f">
if we show inline suggestions at the bottom. The suggestion is visible half on the screen so wanted if it could be scrolled so that whole suggestion is visible like in image
<img width="1046" alt="Screenshot 2023-12-13 at 8 28 36 PM" src="https://github.com/microsoft/vscode/assets/98150135/48b25081-7a02-43cb-8e75-22402c36c7eb">
 below.

**Comment by hediet** [comment]
Cannot reproduce



![Image](https://github.com/microsoft/vscode/assets/2931520/4116d770-71ed-4825-a568-a0b0c59e1334)
