### ISSUE TITLE
Application opening without file opening

### ISSUE THREAD

**Issue by CodeJunkieMonkey** [Microsoft/vscode#20088]
- VSCode Version: 1.9.0
- OS Version: Windows 10

Steps to Reproduce:

1. Set VS Code as Windows default app for .cs files
2. Double click a .cs file in Windows Explorer

VS Code will open, but the .cs file you double clicked on will not be one the open tabs. You see Untitled-1 instead.
See animated gif. Note that the animated gif is looped.

Further notes- I repro'ed this without any VS Code extensions. I also reset settings to default before repro'ing.

![vs code bug](https://cloud.githubusercontent.com/assets/2722806/22671851/5166feee-ec85-11e6-8468-91197002cb64.gif)

Note: Updating from 1.8 to 1.9 did not solve the issue. Uninstalling and reinstalling solved the issue.

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/15654

**Comment by chrmarti** [comment]
Cannot be #15654, since that goes into tomorrow's 1.10-insider and the bug is reported against 1.9.

**Comment by bpasero** [comment]
I cannot reproduce this on my Windows, I suspect an issue with the windows registry for this file type. 

@CodeJunkieMonkey can you reproduce after completely uninstall and reinstall of VS Code?

**Comment by CodeJunkieMonkey** [comment]
@bpasero  Uninstalling and reinstalling solved the issue. Thank you.
