### ISSUE TITLE
Right Click Open in new terminal

### ISSUE THREAD

**Issue by fabiokounang** [microsoft/vscode#200841]
Type: <b>Bug</b>

i want to right click open in new terminal, but my location is opened in the root folder

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.4.0-162-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (4.49GB free)|
|Process Argv|--crash-reporter-id 63946bb6-56c2-45ce-992f-bcf3710598aa|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: VIP-Auto|
|OS|Linux x64 5.4.0-162-generic|
|CPUs|AMD EPYC 7T83 64-Core Processor (8 x 3096)|
|Memory (System)|15.11GB (12.56GB free)|
|VM|11%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-rename-tag|for|0.1.10
vue-snippets|hol|1.0.4
vue|jcb|0.1.5
Angular2|joh|16.0.1
vscode-peacock|joh|4.2.2
sequelize-snippets|kvc|1.0.0
vue|liu|0.1.5
Angular-BeastCode|Mik|10.0.3
dotenv|mik|1.0.1
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
awesome-flutter-snippets|Nas|3.0.3
material-icon-theme|PKi|4.32.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
vscrpc:30673769
2i9eh265:30646982
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by meganrogge** [comment]
Not sure what you mean, a screenshot would help.
