### ISSUE TITLE
Broken Square Select (Multiple Cursor Select)

### ISSUE THREAD

**Issue by maxime4000** [Microsoft/vscode#20087]
- VSCode Version: 1.9.0
- OS Version: Windows 7

Steps to Reproduce:

1. Key Down Shift + Alt
2. Click to the right of X in the last line
3. Select to the S of SoMEKEy
At the moment nothing is selected
4. Go to the E of valuE

This is what it select :
SomeKey" valuE
SomeKey" value
SomeKey" value

What it should be selected: 
E="000
e="000
e="00X

Example of file :
```
<property id="SomeThing" key="SomeKey" value="000"/>
<property id="SomeThing" key="SomeKey" value="000"/>
<property id="SomeThing" Key="SomeKey" value="000"/>
<property id="SomeThing" key="SomeKey" value="000"/>
<property id="SomeThing" key="SoMEKEy" value="000"/>
<property id="SomeThing" key="SomeKey" value="000"/>
<property id="SomeThing" key="SomeKey" value="000"/>
<property id="SomeThing" key="SomeKey" valuE="000"/>
<property id="SomeThing" key="SomeKey" value="000"/>
<property id="SomeThing" key="SomeKey" value="00X"/>
```

**Comment by kieferrm** [comment]
@maxime4000 in step 3 you drag the mouse? When using left mouse click instead the selection is as expected.

**Comment by maxime4000** [comment]
@kieferrm yeah. When you select at the right and you drag to the left, it not selecting anything, but it should. And when you go to right, it selecting from your most left position and not a the place you start selecting with your mouse. After 3 it should have selected from SoMEKEy to 00X but it doesn't select anything and on 1.8.1 it was selecting like that.

**Comment by alexandrudima** [comment]
Indeed, dragging from right to left is not working properly, meanwhile dragging from left to right is working OK.
