### ISSUE TITLE
Test quick pick enhancements

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2008]
* [x] any os @bpasero

We have improved the quick pick API to allow for a second row with details and to be pinged when an item is selected/focused. Ensure that

* the API is easy to understand
* you can have octicons in the label, description, and detail ($(check) this)
* you can provide a `onDidSelectItem` function which is called when selecting items in the list
* give feedback if `onDidSelectItem` is the proper name to use

**Comment by egamma** [comment]
Suggest to test this by adding a sample to the vscode-samples project.
