### ISSUE TITLE
c/c++ error squigger is not enabling 

### ISSUE THREAD

**Issue by yatharth-1907** [microsoft/vscode#200831]
Type: <b>Feature Request</b>

my c/c++ error squiggle is not enabling and showing error. And shoeing 'C_Cpp.EnableErrorSquiggles' not found.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by deepak1556** [comment]
Please open the issue at https://github.com/microsoft/vscode-cpptools
