### ISSUE TITLE
Settings changing on it's own and syncing new value on it's own

### ISSUE THREAD

**Issue by webdevnerdstuff** [microsoft/vscode#200802]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1 
- OS Version: Apple M1 Max Mac 13.6.2

Steps to Reproduce:

1. Add this snippet to VSCode settings
```json
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
```
2. Restart VSCode
3. VSCode keeps changing the setting to:
```json
 "editor.codeActionsOnSave": {
    "source.fixAll.eslint": "explicit"
  },
```

If I change the value back to true (a valid value), then force the settings to sync (confirming the sync happened with the new setting), then reopen VSCode again.. the value has reverted it back to "explicit" and a new sync entry (from opening VSCode) happens saying it synced that new value. If I change the value to "always" it does not change back to "explicit".

**Comment by blakeNaccarato** [comment]
While `true` is still allowed, I think they're trying to deprecate that and encourage usage of `explicit`/`always`/`never`. It's changing to `explicit` which is equivalent to `true` had been prior to the September 2023 release aka v1.83, see discussion in release notes [here](https://code.visualstudio.com/updates/v1_83#_code-actions-on-save-and-auto-save) and [here](https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto).

**Comment by webdevnerdstuff** [comment]
Probably the best fix would be actually remove true/false values as valid inputs. Keeping them as valid can/will cause confusion. While it is mentioned in those release notes, not everybody reads every release notes in detail and it still conflicts with VSCode suggesting those values as valid.

**Comment by apieceofbart** [comment]
This is a breaking change, how this even got merged?
