### ISSUE TITLE
Can't upgrade on Ubuntu 18.04 (again)

### ISSUE THREAD

**Issue by cobalt2727** [microsoft/vscode#200863]
https://github.com/microsoft/vscode/issues/181720 is back with a vengeance.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest insider build as of December 14th
- OS Version: Ubuntu 18.04.6

Steps to Reproduce:

1. `sudo apt install code-insiders` on an 18.04 terminal
```bash
ubuntu@oracle-vm:~$ sudo apt install code-insiders                          Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 code-insiders : Depends: libc6 (>= 2.28) but 2.27-3ubuntu1.6 is to be installed
                 Depends: libgssapi-krb5-2 (>= 1.17) but 1.16-2ubuntu0.4 is to be installed
                 Depends: libxkbfile1 (>= 1:1.1.0) but 1:1.0.9-2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by deepak1556** [comment]
Hi, this is not a regression but is the expected dependencies moving forward. You can read more about it at https://code.visualstudio.com/docs/supporting/faq#_can-i-run-vs-code-on-older-linux-distributions

**Comment by stephkoch** [comment]
Hey, i had the same issue with installation on Ubuntu 18.04 on Nvidia Jetson Nano Jet pack 4.6.4

Installation is no longer possible. However, i could connect via VS Code SSH to my Jetson Nano from a Windows 11 Host Machine.
Greetings

**Comment by cobalt2727** [comment]
@stephkoch Yeah, see above - they're just killing support for it. Best solution I can think of at the moment would be to (shameless self-promo) run the [L4T Megascript](https://github.com/cobalt2727/L4T-Megascript), install literally anything from it, and Flatpak support will get set up in the background with an unofficial Flatpak packaging of the L4T GPU drivers a friend of mine set up. You can just install the [unofficial Flatpak packaging of VS Code](https://flathub.org/apps/com.visualstudio.code) using the software store app (or the CLI) afterwards.

I'll probably switch the VS Code installer in that repo to use this method if the user is on 18.04, although I'm really not a fan of it. Building from source on 18.04 just looks to be more trouble than it's worth, and VS Codium will probably have the same updated requirements soon.
