### ISSUE TITLE
Deleting a folder previously used in VSC without restarting the OS

### ISSUE THREAD

**Issue by 1C0D** [microsoft/vscode#200885]
Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: latest
- OS Version: Win 11/10

Steps to Reproduce:

1. open a project. 
2. close VSC and all applis linked to what is in the folder.
3. try to delete the folder. You can't. 
4. It's only possible after an OS restart

**Comment by 1C0D** [comment]
Well I tried through the console and it's telling about git
`rm: remove write-protected regular file './obsidian-tools/.git/objects/02/5ad1d92c19a4847d5f9a17ba3e1993dbeea9c3'?
`
I don't know if it's only linked to git or git in VSC. I ran a npm install & run dev on this folder before. And the console was closed of course

**Comment by lramos15** [comment]
This is just file locking, there's not anything VS Code can do. Whatever process is using the files must stop and in this case it looks like git has locked your files.
