### ISSUE TITLE
Electron won't init on macOS sierra

### ISSUE THREAD

**Issue by rstormsf** [Microsoft/vscode#20086]
- VSCode Version: 1.9.0
- OS Version: darwin (OSX)

Steps to Reproduce:

1. Download https://code.visualstudio.com/docs/?dv=osx
2. Unzip, Drag and Drop into Application's folder
3. Open VS

![screen shot 2017-02-06 at 2 16 42 pm](https://cloud.githubusercontent.com/assets/9360827/22668835/0f157312-ec77-11e6-8a9d-b6f7589aaad3.png)

**Comment by mjbvz** [comment]
Quick question: how are you unzipping VSCode? We've see a few issues (#17985) when not using the standard osx unarchiver

**Comment by rstormsf** [comment]
@mjbvz Yes, I'm using the standard osx's archiver. 
I just installed:
https://vscode-update.azurewebsites.net/1.8.1/darwin/stable
works fine as expected.
It seems the issue is with 1.9.0

**Comment by rstormsf** [comment]
So, I just installed 1.8.1 and clicked Update now - the same issue.
So I will downgrade and use 1.8.1 for now

**Comment by rstormsf** [comment]
The same issue with VSCOde-insider. if there are any useful logs, please tell me where to grab them

**Comment by rstormsf** [comment]
@mjbvz per your request I tried unzipping via terminal:
`unzip VSCODE` 
the same issue

**Comment by rstormsf** [comment]
Ok, I'm not sure why it happened, but here is the fix that worked for me:
I disconnected all external monitors and ethernet cable.
Installed VSCode and it works fine 1.9.0

**Comment by rstormsf** [comment]
@mjbvz @bpasero  I think I figured it out why this issue happens:
When you open VSCode, it tries to open a web browser with Getting Started link. It also does a background task that is checking whether it has a latest version or not.
If there is a flag that could say please don't do it, I'll check it manually, that will help a lot since I'm behind some firewall rules and security settings

**Comment by bpasero** [comment]
What kind of "security tool" prevents an application from starting when it does any network request without telling the user?????

**Comment by rstormsf** [comment]
I have no idea.
@bpasero 
Is there any way to inspect which requests are blocking? I want to find out. The weirdest thing is that other people on the same network us vscode without any problem

**Comment by rstormsf** [comment]
I noticed that it works fine if I run it from CLI: .....app/bin/code
