### ISSUE TITLE
Saving files deletes all file contents.

### ISSUE THREAD

**Issue by james-berkheimer** [microsoft/vscode#200805]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.1
- OS Version: Darwin arm64 23.1.0 & Windows 10

Steps to Reproduce:

1. Open a file, write some text into it.
2. Try saving the file.  When I save all the text contents of the file is deleted and I'm left with an empty file.

**Comment by james-berkheimer** [comment]
BTW, this is a show stopper for me.  I am unable to do any work right now.  Can someone at the very least point me to a link for version 1.85.0?

**Comment by james-berkheimer** [comment]
Found this issue from a few years back that is the exact same issue I'm having now.

https://github.com/microsoft/vscode/issues/61310

**Comment by james-berkheimer** [comment]
And now all of a sudden the issue went away.  I have zero idea what changed.

**Comment by lramos15** [comment]
So is this fixed?

**Comment by james-berkheimer** [comment]
> So is this fixed?

It appears so.  Although I have no idea how it got fixed.  I'll close the issue.
