### ISSUE TITLE
A repository of problemMatchers for common (or less common tools)

### ISSUE THREAD

**Issue by dannystaple** [Microsoft/vscode#20085]
There are any number of common tools, language outputs, compilers, linters, test outputs etc.

A developer will probably need selection of flavours of problemMatchers for use in tasks.json to cover these.

The proposal is to create repo or list of problem matchers, where people can contribute and enhance them.

This could be as simple as a set of searchable pages people can make PR's to and add ones that they didn't find. It could later be expanding into something suggested in VSCode.

**Comment by dbaeumer** [comment]
The idea here is to allow extensions to contribute problem matchers. So there could then be extension in the marketplace added these for other tools.

**Comment by dbaeumer** [comment]
Extensions can now contribute problem matchers and do so. Closing.
