### ISSUE TITLE
Hitting enter to insert a new line at the end of a comment triggers autocomplete

### ISSUE THREAD

**Issue by AndrewRayCode** [Microsoft/vscode#20089]
Not sure if this is a dupe of https://github.com/Microsoft/vscode/issues/10819 or not?

- VSCode Version: Version 1.9.0 (1.9.0)
- OS Version: OSX

Steps to Reproduce:

1. Type a comment and type to the end of a line
2. Type a word that has an autocompletion you don't want
3. Hit enter to start a new line
![vscode-autocomplete](https://cloud.githubusercontent.com/assets/79215/22671641/32095070-ec84-11e6-9df3-3d387d6e4d50.gif)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/1657
