### ISSUE TITLE
Inline values in vscode only look at local scope

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#20084]
Seems like this is broken with node2.

The inline values are only shown for local scope. For es6, every `{` and `}` creates a block scope.

![image](https://cloud.githubusercontent.com/assets/1018196/22668350/4bc283e2-ec75-11e6-9c01-370fd592864b.png)

It seems like the stackFrame line numbers could be too restrictive or incorrect. The inline value debugging experience seems broken as only the current line values are shown. 

**Expected:** In this case, I expect function parameters and probabibiltySegments to have their values shown as decorators besides it.

```
		stackFrame.getMostSpecificScopes(new Range(stackFrame.lineNumber, stackFrame.column, stackFrame.lineNumber, stackFrame.column))
			// Get all top level children in the scope chain
			.then(scopes => TPromise.join(scopes.map(scope => scope.getChildren()
				.then(children => {
					let range = new Range(0, 0, stackFrame.lineNumber, stackFrame.column);
					if (scope.range) {
						range = range.setStartPosition(scope.range.startLineNumber, scope.range.startColumn);
					}

					return this.createInlineValueDecorationsInsideRange(children, range);
				}))).then(decorationsPerScope => {
					const allDecorations = decorationsPerScope.reduce((previous, current) => previous.concat(current), []);
					this.editor.setDecorations(INLINE_VALUE_DECORATION_KEY, allDecorations);
				}));
```

**Comment by roblourens** [comment]
It looks like vscode only shows children for the most specific scope, but maybe it should show them for all the scopes up to the most specific 'Local' scope?

**Comment by nojvek** [comment]
According to code it should traverse the scope chain up to a limit. It seems code later was added to limit line numbers between the scope ranges. I don't understand how that's computed. 

I'll get back to confirm whether this is also happening for python code as well. 

@isidor what was the ideal experience intention?

**Comment by nojvek** [comment]
I would expect everything inside the current function to be inlined
including the function parameters.

If it's a class/module, I would expect the class/module properties to be
inlined as well.

When debugging that would be the most useful info to quickly discover bugs
and the flow of apps.

**Comment by roblourens** [comment]
Would it be better if we show every scope except the global scope, which is marked with "expensive" @isidorn? Or close?

**Comment by nojvek** [comment]
For someone who uses inlineValues debugging everyday I find it weird that
issues are closed based on whether it can fit in 6 months or not.

Some of this issues can significantly improve the user experience. What is
the harm in leaving the issue open but assigning a label that it’s not in
the current roadmap.

**Comment by roblourens** [comment]
Hey @nojvek, we have many 100s of issues which are valid but which we may not realistically get to in the near future. In the past we've left them open forever but now we're trying to be a little more strict.

**Comment by nojvek** [comment]
I understand. As a small team you have to choose your battles very wisely
otherwise it ends up in endless scope creep.

I'm happy to send a PR regarding this issue if someone can point me to the
code. I do like Rob's approach where we show all scopes other than global
for js.
