### ISSUE TITLE
Code.exe not found when downloading / decompressing vscode 1.85.1 in vscode integration tests

### ISSUE THREAD

**Issue by matts85** [microsoft/vscode#200895]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: 1.85.1
- OS Version: Windows 11 Enterprise (10.0.22621)

Steps to Reproduce:

1. Invoke the runTests function from @vscode/test-electron/out/runTest
2. Observe an error like the one below:

Downloading VS Code 1.85.1 from https://update.code.visualstudio.com/1.85.1/win32-x64-archive/stable
Downloading VS Code (131526249B)
Downloading VS Code [------------------------------] 0%Downloading VS Code [===---------------------------] 11%Downloading VS Code [=======-----------------------] 25%Downloading VS Code [===========-------------------] 39%Downloading VS Code [================--------------] 53%Downloading VS Code [===================-----------] 66%Downloading VS Code [====================----------] 69%Downloading VS Code [=====================---------] 71%Downloading VS Code [=====================---------] 72%Downloading VS Code [=====================---------] 73%Downloading VS Code [======================--------] 75%Downloading VS Code [=======================-------] 78%Downloading VS Code [=======================-------] 79%Downloading VS Code [========================------] 82%Downloading VS Code [=========================-----] 86%Downloading VS Code [==========================----] 90%Downloading VS Code [===========================---] 91%Downloading VS Code [============================--] 94%Downloading VS Code [==============================] 100%Downloaded VS Code into C:\__w\1\s\.vscode-test\vscode-win32-x64-archive-1.85.1
Downloaded VS Code into C:\__w\1\s\.vscode-test\vscode-win32-x64-archive-1.85.1
Test error: Error: spawn C:\__w\1\s\.vscode-test\vscode-win32-x64-archive-1.85.1\Code.exe ENOENT
Exit code:   -4058
Failed to run tests
Failed
##[error]Cmd.exe exited with code '1'.

_**Note: Even though manually downloading & decompressing from https://update.code.visualstudio.com/1.85.1/win32-x64-archive/stable yields Code.exe in the decompressed folder, the folder decompressed by the test framework doesn't include Code.exe.**_

**Comment by khawkins** [comment]
I can confirm in our GitHub Actions CI, as well as confirming that reverting back to explicitly downloading `1.84.2` instead of `stable` resolved the problem. Looks like an issue with the Windows bundle of the latest VSCode version.

**Comment by xiyaowong** [comment]
Upgrade @vscode/test-electron

**Comment by khawkins** [comment]
> Upgrade @vscode/test-electron

Confirmed, @xiyaowong . Thank you!

**Comment by ryanluker** [comment]
> Upgrade @vscode/test-electron

Yep this fixed it for me as well thanks!
https://github.com/ryanluker/vscode-coverage-gutters/actions/runs/7241789051/job/19726300052
https://github.com/ryanluker/vscode-coverage-gutters/commit/a4fe7621d3ad4c48a40f03cb2bc3fc304513b632

**Comment by matts85** [comment]
Confirmed this fix works on my end too. Thanks!
