### ISSUE TITLE
Remote Host Access via `code` CLI

### ISSUE THREAD

**Issue by willsawyerrrr** [microsoft/vscode#200828]
The `code` command conveniently allows opening a new VS Code window; however, there does not appear to be a way to specify the remote host to use for the the new window.

Suppose I have an SSH host called `server` and a WSL instance called `distro` configured. It would be great to have a way to specify which of these hosts to use for the new window.

Consider the following usage options:
  1. Automatically resolve the type of host.
    - For example, `code --host server` and `code --host distro`.
  2. Specify the type of host with a protocol-like prefix.
    - For example, `code --host ssh:server` and `code --host wsl:distro`.
  3. Specify the type of host with separate flags.
    - For example, `code --ssh server` and `code --wsl distro`.

**Comment by connor4312** [comment]
duplicates https://github.com/microsoft/vscode-remote-release/issues/3738
