### ISSUE TITLE
FileSearchQueryProvider: search pattern is not passed to `provideFileSearchResults` 

### ISSUE THREAD

**Issue by wkillerud** [microsoft/vscode#200892]
Type: <b>Bug</b>

In `FileSearchManager` when calling registered search providers' `provideSearchResults`, `this.config.filePattern` is the only thing passed as `pattern`.

https://github.com/microsoft/vscode/blob/4866333b0a56b6295bbd9ce6d45bda3bbe21d97b/src/vs/workbench/services/search/common/fileSearchManager.ts#L121-L125

However, when the [file query is created](https://github.com/microsoft/vscode/blob/4866333b0a56b6295bbd9ce6d45bda3bbe21d97b/src/vs/workbench/api/browser/mainThreadWorkspace.ts#L147), [`filePattern` isn't included](https://github.com/microsoft/vscode/blob/4866333b0a56b6295bbd9ce6d45bda3bbe21d97b/src/vs/workbench/services/search/common/queryBuilder.ts#L180-L192).

`includePattern` is part of the config, but since it's not passed on to the provider I can't get to it. I've stepped through with the debugger and can see the search pattern I've sent to `workspace.findFiles` on `includePattern`.

I've tried to dig in the commit history to find some answers.

- Should `fileSearchManager` send `includePattern` if `filePattern` is not set?
  ```js
  {
    pattern: this.config.filePattern || this.config.includePattern || ''
  }
  ```
- Should `filePattern` be calculated somehow and passed as an option to the query builder in [`$startFileSearch`](https://github.com/microsoft/vscode/blob/4866333b0a56b6295bbd9ce6d45bda3bbe21d97b/src/vs/workbench/api/browser/mainThreadWorkspace.ts#L143C2-L143C18)?

VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.37GB free)|
|Process Argv|--crash-reporter-id 94df6333-f6b2-40cb-b105-74bbd6ea2448|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
astro-vscode|ast|2.5.3
comment-tagged-templates|bie|0.3.2
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-preview-github-styles|bie|2.0.3
markdown-yaml-preamble|bie|0.1.0
nodejs-testing|con|1.3.2
vscode-eslint|dba|2.4.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
sublime-keybindings|ms-|4.0.10
test-adapter-converter|ms-|0.1.8
vsliveshare|ms-|1.0.5900
lit-plugin|run|1.4.1
some-sass|Som|2.14.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by andreamah** [comment]
Do you have example code that I can use to debug this? I'm a bit unsure of the bug that lead to this investigation.

**Comment by wkillerud** [comment]
I have a draft PR in https://github.com/microsoft/vscode-test-web/pull/114 from https://github.com/wkillerud/vscode-test-web/tree/search-provider

It adds a search provider for the virtual file system `vscode-test-web`.

Whenever I call `workspace.findFiles` with a pattern, for instance in [this test](https://github.com/microsoft/vscode-test-web/pull/114/files#diff-63719845aa79343d33efd71fda91eae38eecbda80756725b4966c0e40d42ecc8R39) or [this command](https://github.com/microsoft/vscode-test-web/pull/114/files#diff-d636b40cf70524f74154fed232ebc17678d1badf469c79296bdbdf58f356b5bbR31), the search pattern is not passed to [the search provider](https://github.com/microsoft/vscode-test-web/pull/114/files#diff-0aa1f335599458062baaf0bbc9ac5d95db489f47937e1832308fbb12cb30a7beR144).

```
git clone git@github.com:wkillerud/vscode-test-web.git
git switch search-provider
npm install
npm run compile
npm run sample-tests
```

Here's the output from running the test:

![](https://github.com/microsoft/vscode/assets/1223410/a73cfe59-964e-4bda-bbe1-7ebdd9f78197)

I would expect the line `vscode-test-web search query: {"pattern":""}` to log `vscode-test-web search query: {"pattern":"**/*.txt"}`

You can also `npm run sample`, then run the command `Find files`

![](https://github.com/microsoft/vscode/assets/1223410/b38df2cb-4f04-4e3f-bcde-aae76a2ba898)

Search for `**/*.txt`.

I set breakpoints in the following locations:

![mainthreadworkspace line 147](https://github.com/microsoft/vscode/assets/1223410/4a1ffca4-f9de-4759-bc8f-80a365755e55)
![filesearchmanager line 121](https://github.com/microsoft/vscode/assets/1223410/9339d50a-08df-4737-a565-ce6843b30685)
![fsProvider line 143](https://github.com/microsoft/vscode/assets/1223410/30c7f70c-0284-4f1e-a7f2-eabc6d17fe38)

**Comment by wkillerud** [comment]
It looks like the filtering is done correctly on the client-side / in VS Code, so the provider can return all files as "matches" and still _kind of_ work. It's unexpected behavior, though.

**Comment by andreamah** [comment]
Hey! Sorry for the late response here. To address this, I'm trying out a new overload for `findFiles` that is currently proposed as `findFiles2` https://github.com/microsoft/vscode/pull/203844. 

Since the old `findFiles` had some overall limitations, I tried to revamp it a bit.

**Comment by wkillerud** [comment]
Cool, thank you! I gave `findFiles2` a test run on https://github.com/wkillerud/vscode-test-web/commit/fb2b8887c2a08307d7bfdfa1ae6f4994a1846ad7, and the file search provider gets the pattern as expected 🙌
