### ISSUE TITLE
[OSX] Command-A is recently frequently not causing the editor to Select All

### ISSUE THREAD

**Issue by eob** [Microsoft/vscode#20082]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.0.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|mavensmate|DavidHelmer|0.6.4|
|word-count|hypnoes|0.1.1|
|softwrap|jsturtevant|1.0.2|
|Go|lukehoban|0.6.53|
|debugger-for-chrome|msjsdiag|2.5.1|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

This is a Heisenbug--I can't find a reliable way to reproduce it.

1. Bring focus to the text window.
2. Press Command-A
3. Observe nothing happens.

**Comment by equinusocio** [comment]
I'm on macOS and i don't have this issue.

**Comment by alexandrudima** [comment]
Please keep an eye out and if you find any reproducible steps, reopen the issue. Sorry about it, but there's no action I can take unless we can somehow reproduce.
