### ISSUE TITLE
VSCode infinite loading

### ISSUE THREAD

**Issue by sedouard** [Microsoft/vscode#20083]
This is a bit of an odd bug I found only by accidentally creating a file called "\\" in my project directory.

- VSCode Version: 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281)
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. Create a folder with a new git repo initialized
2. `touch "\\"`
3. Open the directory with VS Code
4. VSCode continues loading forever

**Comment by Tyriar** [comment]
Might be related to folder loading and/or git integration.

**Comment by sedouard** [comment]
Yeah likely. Most people wouldn't hit this and it probably isn't that important to fix. I just thought I'd report it in case its something easy or uncovers a larger problem.

**Comment by bpasero** [comment]
@sedouard does it reproduce if you disable git (`git.enabled: false`)

**Comment by sedouard** [comment]
Yup. 
<img width="684" alt="captura de pantalla 2017-02-07 a las 10 17 40 pm" src="https://cloud.githubusercontent.com/assets/3053263/22725596/47346886-ed83-11e6-80ff-39ae0c41ed85.png">

**Comment by sedouard** [comment]
Actually I suppose this might be a product of environment. Every so often my ember project (in another vscode window) will cause too many file handles to open on my system, causing a 'file table overflow'. As a result other applications have a hard time opening files. So this probably has something to do with it as after I close the ember project, this issue does not reproduce.
