### ISSUE TITLE
Collapsed folders reappearing automatically

### ISSUE THREAD

**Issue by Tapesh-1308** [microsoft/vscode#200856]
Type: <b>Bug</b>

Steps to Reproduce:

1. Open multiple folders in the Explorer tab
2. Collapse all the subfolders
3. Collapse the main folder
4. Reopen that folder and all the collapsed subfolders will also get opened in their previous state before step 2.

Here is the demo:
![vs_code_bug](https://github.com/microsoft/vscode/assets/71540051/841d796a-b121-4193-ad11-d9fccd238f68)

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.53GB free)|
|Process Argv|--crash-reporter-id cd0a98e7-36c7-425a-8dc5-c60895c18a56|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-tailwindcss|bra|0.10.3
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|10.1.0
code-runner|for|0.12.1
cpptools|ms-|1.18.5
live-server|ms-|0.4.13
material-icon-theme|PKi|4.32.0
vscode-rapidapi-client|Rap|1.10.2
vscode-services|rap|1.0.2
LiveServer|rit|5.7.9

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30917236
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by lramos15** [comment]
Did you happen to have HomeBanner.jsx open in this case?
