### ISSUE TITLE
Rename Terminal (and/or F2 key) only works when multiple terminals running

### ISSUE THREAD

**Issue by JeremyTBradshaw** [microsoft/vscode#200960]
Type: <b>Bug</b>

I typical run 3 PowerShell's and so rename them and give them different colored icons for easy selection throughout my day (e.g., various M365* administration, various on-premises Exchange orgs).  I've noticed for a while now (ever since I tried, never succeeded) - if there's just 1 PowerShell running, Rename... and F2 key just do nothing.

Is this expected?  Low urgency.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (5.96GB free)|
|Process Argv|--crash-reporter-id adefba71-b7ac-4e94-9af1-1427a7e4d304|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
html-preview-vscode|geo|0.2.5
rainbow-csv|mec|3.9.0
live-server|ms-|0.4.13
powershell|ms-|2023.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by JeremyTBradshaw** [comment]
@meganrogge can you please provide any reference? I am uninterested in Insiders build and do not find my issue when searching opened/closed issues.

**Comment by JeremyTBradshaw** [comment]
![image](https://github.com/microsoft/vscode/assets/18154705/defd6a90-be32-4ae6-b845-dcb4751e325a)
It's those 3 options that don't work, until there are multiple shells running.

Once you have two or more shells, those options start working, as below I'm showing me renaming successfully the 2nd shell:
![image](https://github.com/microsoft/vscode/assets/18154705/01352605-2187-4dc0-b8bf-4ca5bf072a56)

**Comment by meganrogge** [comment]
Yeah, that seems like a bug with the single tab, which is a separate issue

**Comment by JeremyTBradshaw** [comment]
Thank you for acknowledging and opening the new issue.
