### ISSUE TITLE
Web shows many internet disconnected errors for extension galary

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#200986]
1. Open insiders.vscode.dev
2. Open dev tools
3. Click the automatically install "Fugio" extension
4. Click around and see many internet disconnected errors.

I made sure my adblockers were off just in case

<img width="689" alt="image" src="https://github.com/microsoft/vscode/assets/4544166/4beb450f-386f-43f4-a12c-e7d17440b65b">

**Comment by sandy081** [comment]
> Click the automatically install "Fugio" extension

What do you mean by automatically install here?

**Comment by lramos15** [comment]
Turns out my machine was acting up, half of github.dev and vscode.dev would not work. Still not sure why but this is working fine on other machines so closing.
