### ISSUE TITLE
markdown code block word wrap didnt work

### ISSUE THREAD

**Issue by protasov1904** [microsoft/vscode#200996]
Type: <b>Bug</b>

markdown code block word wrap didnt work after update with GitHub Markdown Preview extension

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440S CPU @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (0.97GB free)|
|Process Argv|e:\\Users\\protasov_ss\\Desktop\\markdown\\SP_OFFLINE.code-workspace --crash-reporter-id 2139dcd2-5d12-42bc-986c-3d252437deac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.21.0
markdown-preview-github-styles|bie|2.0.3
markdown-yaml-preamble|bie|0.1.0
remotehub|Git|0.62.0
azure-repos|ms-|0.38.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by mjbvz** [comment]
In the markdown preview? If so, please file an issue against that extension

**Comment by protasov1904** [comment]
Created incorrectly, sorry
The problem only appears in a certain extension  `GitHub Markdown Preview` after version 1.85.1

in version 1.84.2 and earlier there were no line breaks here

```sh
echo "long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text "
```

lines were wrapped only if the language was not specified,
```
long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text 
```
 which significantly accelerated the compilation of a local knowledge base without the need to change the CSS

but its not a big problem
It’s safer to write MD files so that they minimally depend on the extensions used
