### ISSUE TITLE
Debugging List Comprehension 02

### ISSUE THREAD

**Issue by avgmdus** [microsoft/vscode#200970]
![LCP_02](https://github.com/microsoft/vscode/assets/79008640/0090a1c3-4cd5-4b6a-876e-033df69e469e)
Type: <b>Bug</b>

1. Enter the following Python code into VS Code:

result = []
for n in [20, 40, 60]:
    for m in [2, 4, 6]:
        result.append(n*m)
print(result)

result = [i*j for i in [20, 40, 60] for j in [2, 4, 6]]
print(result)

2. Set breakpoint at line 5 (at print(result))

3. Execute code under debugger by pressing F5 twice. Terminal window will show the expected results:
[40, 80, 120, 80, 160, 240, 120, 240, 360]
[40, 80, 120, 80, 160, 240, 120, 240, 360]

4. Now execute the same code in a slightly different way:
4.1. Press F5 once. Code execution will stop at line 5 (print(result))

4.2. Press F10. Observe result printed in the Terminal window:
[40, 80, 120, 80, 160, 240, 120, 240, 360]

4.3. Continue pressing F10. At some point the Runtime Warnings will appear in the Terminal window:
C:\Users\Admin\Documents\Learn\MultiMatch\ListComprehensionProblem01.py:7: RuntimeWarning: assigning None to unbound local 'i'
  result = [i*j for i in [20, 40, 60] for j in [2, 4, 6]]
C:\Users\Admin\Documents\Learn\MultiMatch\ListComprehensionProblem01.py:7: RuntimeWarning: assigning None to unbound local 'j'
  result = [i*j for i in [20, 40, 60] for j in [2, 4, 6]]

4.4. Continue pressing F10. At some point TypeError Exception will appear in the code window:
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
(see screenshot above)

5. Because of the exception above, the second result is never printed in Terminal window

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (20.30GB free)|
|Process Argv|--crash-reporter-id 1b53df1e-8a96-4bda-8bb4-c809f418f731|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30917236
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259

```

</details>

**Comment by roblourens** [comment]
Please file this on the debugpy repo
