### ISSUE TITLE
Workspace edit metadata `needsConfirmation` results in all checkboxes unchecked

### ISSUE THREAD

**Issue by BoykoAlex** [microsoft/vscode#200991]
The `WorkspaceEdit` that has metadata with `needsConfirmation` set to `true` shows the **Refactor Preview** which is great but all checkboxes are unchecked. I'd rather have all checkboxes checked.

I went through various git issues where showing **Refactor View** was first implemented. All screenshots show all changes check-marked. I also saw this one #144893 which also shows all changes check-marked and the request to check/uncheck a group of changes which would be useful.

However, I always have all changes unchecked and wonder how they could be all checked by default?
I'd appreciate a code snippet

For example i have this:
```typescript
            const edit: VSCode.WorkspaceEdit = new VSCode.WorkspaceEdit();
    
            const folders = VSCode.workspace.workspaceFolders;
            if (!folders || folders.length === 0) {
                VSCode.window.showInformationMessage('Open a folder first');
                return;
            }
            const newFile = VSCode.Uri.joinPath(folders[0].uri, 'foo.txt');
            edit.createFile(newFile, 
                { overwrite: true }, 
                { label: 'New text', needsConfirmation: true }
            );
    
            const initialContent = new TextEdit(new Range(new Position(0,0), new Position(0, 0)), "Hello World\nOne more line");
            edit.set(newFile, [initialContent]);
    
            VSCode.workspace.applyEdit(edit, { isRefactoring: true });

```
How can i make checkboxes checked for the above?

**Comment by Raf-A2F** [comment]
is:open label:ux

**Comment by DanTup** [comment]
Maybe same as https://github.com/microsoft/vscode/issues/207578?

**Comment by jrieken** [comment]
This is actually designed. Needs confirmation means the extension is unsure about this change and the user must explicitly accept it
