### ISSUE TITLE
pow function in math.h library

### ISSUE THREAD

**Issue by TruptiCoder** [microsoft/vscode#200918]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.1
- OS Version: 21H2

Steps to Reproduce:

1. write a basic program in cpp 
2. add math.h library
3. use pow function
4. for pow(10 , 2) it is giving wrong answer.
5.
![binary cpp - coding - Visual Studio Code 15-12-2023 09_44_53](https://github.com/microsoft/vscode/assets/113124070/8b46bb24-4cf0-4a78-9529-c9ee58e447e5)

**Comment by TruptiCoder** [comment]
It is giving such wrong answers for multiple of 10 , 100 , ... raise to power of even numbers like 2 , 4 , .... .

**Comment by xiyaowong** [comment]
Dude, VSCode is just an editor, please learn to use search engines.

https://cplusplus.com/forum/beginner/252848/
