### ISSUE TITLE
Tyscript Failing when editing files on SharePoint 365 mapped drive

### ISSUE THREAD

**Issue by jdtoth** [Microsoft/vscode#20090]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: None installed

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Open folder on a mapped drive (in this case the mapped drive is to a SharePoint 365 site)
2. Receiving a recurring message about Typescript failing

**Comment by mjbvz** [comment]
Thanks. We're working with TypeScript to fix this: https://github.com/Microsoft/TypeScript/issues/13874

Closing as a duplicate
