### ISSUE TITLE
Debug hangs immediately on powershell script

### ISSUE THREAD

**Issue by ssaari** [Microsoft/vscode#20091]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|mssql|ms-mssql|0.2.0|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.7.10|

---
After updating to v1.9.0, no scripts run, either in single file or normal debug sessions.  The progress bar runs until I cancel it (requires two clicks on the cancel button), but no output occurs to the debug console.  Tried it on two computers.
Steps to Reproduce:

1. Create a new powershell script.  Folder can be open or not.  Debug clicked or not.
2. Type Write-Host 'Test'
3. Press F5 or click the Run icon.  No output displays.  Script never completes.

**Comment by weinand** [comment]
This issue was moved to PowerShell/vscode-powershell#494

**Comment by weinand** [comment]
This issue has been moved to the PowerShell repository.
