### ISSUE TITLE
Code occupies all available memory - possibly ripgrep related

### ISSUE THREAD

**Issue by lrzpellegrini** [microsoft/vscode#200979]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.85.1 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2 x64
- OS Version: kUbuntu 22.04.3 LTS
Installed using apt.

Code has sudden spikes of memory occupation which can fill the entire available RAM and swap memory. The issue seems to be related to ripgrep.

The issue occurred a couple of times in the same session. The problem is "auto-solved" the moment the swap memory is occupied (as it crashes the ripgrep processes due to OOM) but in the meantime the entire system is frozen.

The issue started to appear after a few seconds I started working with a multi-line code search. At that point, the VSCode session was already opened for a couple of hours.

The problem seems to occur even when not actively using the search tab. The problem occurs even if no matches are found.

Exact search string:

```
    hydra/launcher=submitit_local \
    hydra.launcher.tasks_per_node=2 \
    hydra.launcher.gpus_per_node=2 \
    hydra.launcher.timeout_min=1000000 \
```

Updated info: the problem appears even when starting a fresh VSCode session the moment that string is pasted. No regex or other search options were added, just a plain search. No replacement string was provided.

Updated info 2: the problem is also immediately solved if the search string is deleted from the search text box.

Attaching screen photo of htop output. Sorry for the poor quality, but the system was frozen at the time.
![code_memory_overflow](https://github.com/microsoft/vscode/assets/43009885/926c0db7-feaf-4d1a-8d24-d2bc20443a15)

**Comment by andreamah** [comment]
Questions:
1. Have you tried with all extensions disabled?
2. Are you using a remote machine?
3. Is is a particularly large repo?

**Comment by lrzpellegrini** [comment]
Hi @andreamah,

1. Yes, it also happens when extensions are disabled
2. I tried this on a local machine
3. It's not *that* big. It includes a git submodule which is not large. I can safely search for other simpler strings, even regexes. The problem seems to be related to the peculiar format of the search string I provided for reference (which is part of a bash multiline command)

**Comment by andreamah** [comment]
Please try this out:

1. Run `Developer: Set Log Level`  in the command palette and set `Trace`.
2. Do a search with the query that you listed above.
3. In the bottom panel, check logs in the `Extension Host` channel in the `Outputs` tab.

Is there a line that starts sort of like this?
```
RipgrepSearchEH#search c:\Users\andreamah\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\@vscode\ripgrep\bin\rg.exe 
```

Then, if you invoke rg.exe directly from the command line, what type of performance do you get?

**Comment by lrzpellegrini** [comment]
Ok, I tried this by connecting remotely (I had to use the "Extension Host (Remote)" tab to get the full command). (Obvious) side note: the problem persists even when I use the system remotely.

The output I got is:

```
2024-01-04 16:34:30.308 [debug] RipgrepSearchEH#search provideTextSearchResults     hydra/launcher=submitit_local \
    hydra.launcher.tasks_per_node=2 \
    hydra.launcher.gpus_per_node=2 \
    hydra.launcher.timeout_min=1000000 \, {"folder":"file:///home/lorenzo/Desktop/VCS/TPC-dev","excludes":[],"includes":[],"useIgnoreFiles":false,"useGlobalIgnoreFiles":false,"useParentIgnoreFiles":false,"followSymlinks":true,"encoding":"utf8","maxResults":20000,"previewOptions":{"matchLines":1,"charsPerLine":1000},"usePCRE2":false}
2024-01-04 16:34:30.310 [debug] RipgrepSearchEH#search /home/lorenzo/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node_modules/@vscode/ripgrep/bin/rg --hidden --no-require-git --ignore-case --no-ignore --follow --crlf --engine 'auto' --regexp '    hydra/launcher=submitit_local \\\r?\n    hydra\.launcher\.tasks_per_node=2 \\\r?\n    hydra\.launcher\.gpus_per_node=2 \\\r?\n    hydra\.launcher\.timeout_min=1000000 \\' --no-config --no-ignore-global --json --multiline -- '.'
 - cwd: /home/lorenzo/Desktop/VCS/TPC-dev
```

I can confirm that, by running that command in a separate terminal (outside VSCode), I still get the same problem.

Side note 2: I tried this on a different system (Manjaro) and the problem does not persist. The "working" VSCode version on Manjaro is:

1.85.1
0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
x64

... the same as the one in the kUbuntu system where I get this issue. This probably means it's vscode version-unrelated.

**Comment by davidmerwin** [comment]
#201785 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andreamah** [comment]
I think that this would be a performance limitation with ripgrep itself. Unfortunately, I would advise to add more files to exclude to your configuration if possible. Otherwise, you can try filing an issue in the ripgrep repo itself.
