### ISSUE TITLE
Additional formats for directory/file links with spaces

### ISSUE THREAD

**Issue by hybridherbst** [microsoft/vscode#200978]
Related:
- https://github.com/microsoft/vscode/issues/97941

Some path formats for paths with spaces are already available.

It would be great to also have the following - not sure what's feasible here:
- [some-tag] <path>: <anything>
- anything "path" anything

**Comment by karthiknadig** [comment]
Thank you for taking the time to share your suggestion with us. We sincerely apologize for not responding to your request sooner. We greatly value the feedback and ideas our users share, as they help shape the future of our product.

Unfortunately, this particular feature request hasn’t received the level of support (votes) required for us to prioritize its implementation. As a result, we’ll be closing this request for now.

Please don’t hesitate to share any additional suggestions or insights in the future. We’re always open to hearing from our community and appreciate your contributions.

Thank you for your understanding!
