### ISSUE TITLE
Fuzzy search sorting seems broken

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2009]
Step 1 all is good
![screen shot 2016-01-14 at 11 36 06](https://cloud.githubusercontent.com/assets/1926584/12322221/0e3658ae-bab3-11e5-8e8d-3bb03e98933a.png)

Step 2 all is broken

![screen shot 2016-01-14 at 11 35 25](https://cloud.githubusercontent.com/assets/1926584/12322204/f2d3c326-bab2-11e5-947d-8fcd867375b6.png)

**Comment by bpasero** [comment]
@isidorn I do not see an issue here, you typed "partsService" which does not exist?

**Comment by isidorn** [comment]
Stupid me
