### ISSUE TITLE
Hover occasionally stops working 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#200949]
Since 1.86-insider I see that occasionally the hover stops working. Looking at the EH logs shows that no more requests are made, hover in another (to the side) editor is still working which makes me believe something is wrong with the hover editor contribution. 

I will update this issue once I have step to reproduce or more actionable information

**Comment by aiday-mar** [comment]
Hi @jrieken thank you for writing about this. I will try to reproduce this issue and look into what may be causing this.

**Comment by aiday-mar** [comment]
Do you still see this issue @jrieken ? I tried to reproduce the issue but wasn't able to so far.

**Comment by jrieken** [comment]
No, I havn't seen this anymore. Might have been a fluke, esp since no one else spoke about this. Sorry for the false alarm, I am OK to close this

**Comment by aiday-mar** [comment]
Ah I am glad to hear. Then I'll close this issue. If you ever see this happening again, feel free to open it again.
