### ISSUE TITLE
ptyError,  can't launch any terminal after connecting to remote server by ssh

### ISSUE THREAD

**Issue by KevinfromTJ** [microsoft/vscode#200985]
Type: <b>Bug</b>

1. connect to remote server by ssh 
2. in previous version, once connection is established, a terminal will be activated, also it can be manually created at the bottom bar of vscode's interface
3. however , it didn't response and output warning message such as “The connection to the terminal pty host process does not respond and the terminal may stop working”

VS Code version: Code - Insiders 1.86.0-insider (37fe2d06d65db4b50303c5f5e8ca589a50f2287a, 2023-12-15T05:36:59.071Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 4.15.0-213-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12500H (16 x 3110)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (2.26GB free)|
|Process Argv|--crash-reporter-id fa2e69f7-4882-4d74-bb79-e534b481e4f9|
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: WzhLab_b101_80and90|
|OS|Linux x64 4.15.0-213-generic|
|CPUs|Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz (64 x 891)|
|Memory (System)|251.57GB (188.44GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
better-cpp-syntax|jef|1.17.2
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.328.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
vue-vscode-snippets|sdr|3.1.1
open-in-browser|tec|1.1.0
vscode-language-pack-zh-hans|MS-|1.85.2023121309
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpsinfo:30901776
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by KevinfromTJ** [comment]
![PixPin_2023-12-16_00-49-49](https://github.com/microsoft/vscode/assets/90135463/da17dd64-6b61-4c37-b2bb-2b2defcb7ca0)

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal
