### ISSUE TITLE
Mac touchBar in vscode doesn't have a toggle breakpoint key

### ISSUE THREAD

**Issue by oulaoba** [microsoft/vscode#200969]
First thanks  for the best project vscode .

I use the vscode on Mac,and my computer is enable the touchBar App contral option in keyboards seething. 
When I code or debug,the touchBar doesn't have a toggle breakpoint key. 

Now it's like this 
![befor](https://github.com/microsoft/vscode/assets/34548001/328786d6-76b0-454a-a3c2-91dd7d0059fe)

I tried to find an option to config this, but I can't find. So I hope it's can be option to configure or provide it in default,it will be like this : 
![after](https://github.com/microsoft/vscode/assets/34548001/a6ba3fbc-7691-4e44-8fef-92bf287a7c53)

Computer info :MacBook Pro a1990

OS: macOs 14.2 (23C64)

vscode info:

Version: 1.85.1 (Universal)

Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2

Date: 2023-12-13T09:48:06.308Z (21 hrs ago)

Electron: 25.9.7

ElectronBuildId: 25551756

Chromium: 114.0.5735.289

Node.js: 18.15.0

V8: 11.4.183.29-electron.0

OS: Darwin x64 23.2.0

**Comment by roblourens** [comment]
Since Apple isn't making new macbooks with a touchbar, and you can toggle breakpoints with F9, I don't think we should invest more in the touch bar.

**Comment by oulaoba** [comment]
> Since Apple isn't making new macbooks with a touchbar, and you can toggle breakpoints with F9, I don't think we should invest more in the touch bar.

But he is really  useful among programmers.
At now when i enable app control,it doesn’t have breakpoint key on keyboard. if i want add a new breakpoint i need press 'fn' + 'F9' ,or i can't use the 'app control'. for me i think the 'app control' can help me to use to app easily. but now it make me more complex.
So i hope you consider this issues,plz
