### ISSUE TITLE
Cannot read properties of null (reading 'finishedPaste')

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#200931]
Got this error when pasting into a comment widget input:

![image](https://github.com/microsoft/vscode/assets/38270282/f4442f57-3e67-4eed-9e03-00c4ca973715)

I can't find a stack trace in the console or in any of the logs. 

My exact steps:
- Copy a permalink using the GHPRI "Copy permalink" command
- Open a comment widget and paste the permalink there

**Comment by mjbvz** [comment]
Duplicate of #200694
