### ISSUE TITLE
Comments and badges missing after reloading window

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#200972]
Testing microsoft/vscode#167397

on Windows 11

In the vscode-docs repo, open draft PR microsoft/vscode#5677 and add a couple of comments to docs/sourcecontrol/intro-to-git.md.

The Comments view shows that there are comments and the badge reflects the resolved or unresolved state.

Reload the window and the Comments view doesn't show that there are comments.

![image](https://user-images.githubusercontent.com/12818376/204667713-9a67d7b7-99cb-4cb8-ba67-b00b9c0b0f65.png)

**Comment by alexr00** [comment]
Actually, there's a bug here.
