### ISSUE TITLE
node.js debug issue

### ISSUE THREAD

**Issue by hellopao** [Microsoft/vscode#20097]
debug the node.js projects via nodemon failed

- VSCode Version: 1.1.0-insider
- OS Version: windows7

Steps to Reproduce:

1. change the default integrated terminal to git bash
2. debug node.js projects via nodemon
![image](https://cloud.githubusercontent.com/assets/5064875/22675305/e3b7dddc-ed1f-11e6-881a-021ec426c63a.png)

![image](https://cloud.githubusercontent.com/assets/5064875/22675158/f8fab760-ed1e-11e6-9a6a-dd591646e969.png)

3. it works when i change the default integrated terminal back to cmd
![image](https://cloud.githubusercontent.com/assets/5064875/22675295/da9c11e6-ed1f-11e6-94f8-e4234edec074.png)

4. it doesn't work when i change the console option to `internalConsole` either
![image](https://cloud.githubusercontent.com/assets/5064875/22675351/21c92892-ed20-11e6-89d0-d6a77207346b.png)

**Comment by Tyriar** [comment]
You will probably want to refer to nodemon from within the node_module folder, something like this:

```js
"runtimeExecutable": "${workspaceRoot}/node_modules/.bin/nodemon"
```

**Comment by weinand** [comment]
In Insider we are working on merging the two node debuggers into one (and switching automatically between 'node' and 'node2' behind the scene). Currently Insider has a problem detecting the correct debugger to use. It picks 'node2' which doesn't really work with you nodemon setup.

Workaround: add `'protocol': 'legacy'` to your launch config. That forces VS Code to use the old debugger 'node'.
