### ISSUE TITLE
The shortcuts to Add Cursor Above(CTRL + ALT + UpArrow) and Add Cursor Below(CTRL + ALT + DownArrow) doesn't works and in fact changes the orientation the windows system.

### ISSUE THREAD

**Issue by zaid-khan** [Microsoft/vscode#20098]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|

---

Steps to Reproduce:

1.Press CTRL + ALT + UpArrow
2.Press CTRL + ALT + DownArrow

**Comment by Tyriar** [comment]
This is due to your graphics drivers, you will need to disable the hotkey in your driver's settings or rebind the VS Code commands with custom keybindings https://code.visualstudio.com/docs/customization/keybindings#_customizing-shortcuts
