### ISSUE TITLE
Change click behavior in NPM Scripts panel in VS Code

### ISSUE THREAD

**Issue by charnou** [microsoft/vscode#200901]
Hello VS Code Team,

I am a regular user of Visual Studio Code and I really enjoy using it. Currently, I've noticed that when clicking a script name in the NPM Scripts pane, we are taken to the script's definition in the package.json file. While this can be sometimes beneficial, we already  have implementation for the right-click context option with the same logic.

For an improved and efficient workflow, **my suggestion is that clicking the script name should directly run the script instead of navigating to its location.** The reasoning behind my suggestion is that running a script is the most frequently performed action, hence, it should be the easiest to perform. Hovering over to click 'Run' can be somewhat inconvenient as it requires accurate pointer placement.

The Debug button can remain accessible on hover, but I would also like to have a possibility to hide it thought the settings.

I am open to discussions on how to realize this functionality and I am ready to assist in any way possible to see this improvement in VS Code. This change, I believe, will significantly enhance the experience and productivity of many other developers like me.

Thank you for considering this feature request.

Best Regards, 
Stanislau Charnou

**Comment by Igorgro** [comment]
There is already a setting for that: `"npm.scriptExplorerAction": "run"`.

**Comment by connor4312** [comment]
`npm.scriptExplorerAction` is the way to go.
