### ISSUE TITLE
Quick Fix not working on floating windows

### ISSUE THREAD

**Issue by Crucialjun** [microsoft/vscode#200922]
Type: <b>Bug</b>

Tapping on quick fix opens the list of choices to fix the error but quickly closes before selecting any option

VS Code version: Code - Insiders 1.86.0-insider (789c802e75813bfb38ff2e13e4b322bd7e90124b, 2023-12-14T05:36:50.991Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.44GB free)|
|Process Argv|--crash-reporter-id ef0ebe3d-bbce-475a-8558-0a4155e388bb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
better-tests|and|0.3.1
ccs-flutter-color|cir|1.2.1
dart-code|Dar|3.78.2
flutter|Dar|3.78.0
gitlens|eam|14.6.1
prettier-vscode|esb|10.1.0
bloc|Fel|6.6.5
copilot|Git|1.143.601
copilot-chat|Git|0.11.1
copilot-labs|Git|0.17.1121
vscode-pull-request-github|Git|0.78.1
json-to-dart|hir|3.5.8
dart-data-class-generator|hzg|0.5.4
svg|joc|1.5.3
dart-import|lua|0.3.1
awesome-flutter-snippets|Nas|4.0.1
color-highlight|nau|2.5.0
vscode-versionlens|pfl|1.9.2
material-icon-theme|PKi|4.32.0
flutter-riverpod-snippets|rob|1.2.2
code-spell-checker|str|3.0.1
ayu|tea|1.0.5
errorlens|use|3.15.0
vscode-icons|vsc|12.6.0
vscode-surround|yat|1.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
2i9eh265:30646982
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30901775
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by zouyaoji** [comment]
me too

**Comment by justschen** [comment]
Looks like the entire window closes for a split second before reopening with the quick fix menu, then closes the quick fix menu. May be related to the context view changes

https://github.com/microsoft/vscode/assets/54879025/bed1570e-4499-475d-b20c-5a46e5a32d76
