### ISSUE TITLE
decorators in object literals not working

### ISSUE THREAD

**Issue by pascalopitz** [Microsoft/vscode#201]
I am getting a parsing error for decorators on object literal properties. My jsconfig.json looks like this:

    {
        "compilerOptions": {
            "target": "ES6",
            "module": "commonjs",
            "experimentalDecorators": true
        }
    }

This code compiles okay in babel 5.8.12 using the "es7.decorators" extension.
Can I somehow make this work?

![image](https://cloud.githubusercontent.com/assets/271740/11269888/3f0a1f3a-8f0a-11e5-86e8-578b7a24d60d.png)

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#5770
