### ISSUE TITLE
Source control bug

### ISSUE THREAD

**Issue by w3ichen** [microsoft/vscode#201042]
Type: <b>Bug</b>

1. Edit a file
2. In source control sidebar, stage the files
3. Without entering a commit message, click the commit & sync button
4. It wil infinitely load and do nothing

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:16.874Z)
OS version: Darwin arm64 23.2.0

**Comment by lszomoru** [comment]
Pressing the commit button without entering a commit message triggers the flow described here - https://code.visualstudio.com/updates/v1_69#_author-commit-message-using-an-editor. If that is not what you are seeing please feel free to reopen this issue. Thanks!
