### ISSUE TITLE
Status bar hit target is off

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/vscode#201033]
Type: <b>Bug</b>

When hovering over buttons in the status bar, I cannot select them unless I am on the border.

VS Code version: Code - Insiders 1.86.0-insider (37fe2d06d65db4b50303c5f5e8ca589a50f2287a, 2023-12-15T05:36:59.071Z)
OS version: Windows_NT x64 10.0.22621
Modes:

![hit-target-status-bar](https://github.com/microsoft/vscode/assets/972891/1bb21c4c-6f65-4a51-9873-d0a6f6f2113f)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.22GB free)|
|Process Argv|--log vscode.typescript-language-features=trace --crash-reporter-id b3069aa6-29c0-4a9a-9f21-122aa0ea5c48|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ruff|cha|2023.56.0
nunjucks-template|ese|0.5.1
codespaces|Git|1.16.5
theme-monokai-pro-vscode|mon|1.2.1
black-formatter|ms-|2023.7.13471009
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.100
jupyter|ms-|2024.1.2023121501
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
vscode-typescript-next|ms-|5.4.20231215
show-offset|ram|0.0.4
even-better-toml|tam|0.19.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
showlangstatbar:30737417
9b8hh234:30694863
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30901777
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by DanielRosenwasser** [comment]
Possibly related to #200225.

**Comment by bpasero** [comment]
Does this apply to all status bar entries?

**Comment by DanielRosenwasser** [comment]
Yup, on every button

![hit-target-status-bar-2](https://github.com/microsoft/vscode/assets/972891/b6810fb2-b6c4-4713-88e6-b9258663d27d)

**Comment by bpasero** [comment]
If this is a confirmed regression, it would help to know which change caused it. We maintain a node.js based CLI tool  [`vscode-bisect`](https://github.com/microsoft/vscode-bisect) that automatically downloads and runs previous VS Code insiders and asks for each build if the issue reproduces. It takes up to 8 steps to find exactly the build that caused the regression.

**Steps:**
* install [node.js](https://nodejs.org/en/download) (if not yet done)
* `npx --yes @vscode/vscode-bisect@latest`
* follow the instructions until you found the offending build (its fine to leave the commit empty)
* report back the commit range in this issue

Thanks!

**Comment by DanielRosenwasser** [comment]
I apologize - I'm actually now pretty sure this is not related to VS Code. It only happens when my status bar is sufficiently close to the Windows task bar, and it happens in other programs like Chrome too. I have no idea what's causing this.

**Comment by DanielRosenwasser** [comment]
Killed explorer.exe and that fixed it. I'll try to file something on Windows when it happens again.
