### ISSUE TITLE
Escaping closing brackets in snippet choices results in backslashes being inserted

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#201059]
In [the docs here](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar) it says:

> Below is the EBNF ([extended Backus-Naur form](https://en.wikipedia.org/wiki/Extended_Backus-Naur_form)) for snippets. With `\` (backslash), you can escape `$`, `}`, and `\`. Within choice elements, the backslash also escapes comma and pipe characters.

My understanding of this is that `}` can be escaped with a `\` for all kinds of snippets.

However, if I create a snippet that uses choices and escapes a bracket, the backslash appears as-is in the choice:

```ts
const doc = await vscode.workspace.openTextDocument({ content: '' });
const editor = await vscode.window.showTextDocument(doc);
const snippet = new vscode.SnippetString("a(${1|{optionA\\})>,optionB|}");
await editor.insertSnippet(snippet, new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 0)));
```

![image](https://github.com/microsoft/vscode/assets/1078012/ae79cec5-5a17-467d-87e2-7bb609e70737)

If it is not allowed to escape `}` for choices, then I think it should be clearer from the docs (and [the same docs in LSP](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#grammar)).

Note: I can't use the `appendChoice()` API because these snippets are being returned over LSP from a language server (and such, it's important the docs are accurate and specific, to ensure servers and clients have the same understandings).

**Comment by DanTup** [comment]
This actually repros without the backslashes when using appendChoice:

```
const doc = await vscode.workspace.openTextDocument({ content: '' });
const editor = await vscode.window.showTextDocument(doc);
const snippet = new vscode.SnippetString("a(");
snippet.appendChoice(["{optionA})>", "optionB"]);
await editor.insertSnippet(snippet, new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 0)));
```

Although it's possible that bit will be fixed by https://github.com/microsoft/vscode/issues/180132

**Comment by RedCMD** [comment]
related: https://github.com/microsoft/vscode/issues/200424

**Comment by jrieken** [comment]
> My understanding of this is that } can be escaped with a \ for all kinds of snippets.

I see how the docs make you believe so but it is a misunderstanding. Generally, only things that have a "syntax-meaning" need to be escaped.

**Comment by RedCMD** [comment]
> only things that have a "syntax-meaning" need to be escaped

@jrieken then how come when I escape snippet syntax in https://github.com/microsoft/vscode/issues/200424 the escape char goes through
but if I don't escape it, the snippet syntax goes through

**Comment by jrieken** [comment]
@RedCMD I don't see how #200424 is related to this issue

**Comment by DanTup** [comment]
@jrieken 

> I see how the docs make you believe so but it is a misunderstanding. Generally, only things that have a "syntax-meaning" need to be escaped.

Gotcha - so the only thing to escape in a choice is the pipe `|` and comma `,`? It would be good if the docs could list _exactly_ which characters _can_ be escaped (it sounds like there's no difference between _need_ and _can_ here) for each of the contexts to avoid any ambiguity?

I'm happy to send a PR with my guess at what that is if you'd review it - I'd like to ensure our server (and the LSP spec) are correct 
and explicit for the actual behaviour here. Thanks!

**Comment by DanTup** [comment]
https://github.com/microsoft/vscode-docs/pull/6928 was merged with doc updates for VS Code. The same change in LSP is open at https://github.com/microsoft/language-server-protocol/pull/1868.

**Comment by DanTup** [comment]
Both the PRs above have been merged.
