### ISSUE TITLE
Vue intellisense does not work with PNPM & VSCODE 1.85.1

### ISSUE THREAD

**Issue by aspheresedge** [microsoft/vscode#201049]
Does this issue occur when all extensions are disabled?: Not tested because we need extensions for expected behavior to work

- VS Code Version: 1.85.1
- OS Version: Both Windows 10 & Macos Ventrua 13.4 - however doesnt seem to be OS dependent.

Steps to Reproduce: Available in: [https://github.com/vuejs/language-tools/issues/3802](https://github.com/vuejs/language-tools/issues/3802)

PNPM uses symlink for packages, could that be the issue? https://pnpm.io/motivation#creating-a-non-flat-node_modules-directory

**Comment by mjbvz** [comment]
> d because we need extensions for expected behavior to work

What extensions are needed?

**Comment by aspheresedge** [comment]
Hi @mjbvz , standard vue language tools extension. https://marketplace.visualstudio.com/items?itemName=Vue.volar

**Comment by pietdevries94** [comment]
I also have this problem in 1.84.2 on Nixos (Linux)

**Comment by aspheresedge** [comment]
https://github.com/volarjs/typescript-auto-import-cache/pull/3
