### ISSUE TITLE
Terminal is too slow while running specially az cli commands 

### ISSUE THREAD

**Issue by rajmaragoni** [microsoft/vscode#201041]
Type: <b>Bug</b>

Go to the Powershell or any Terminal on window VS code application, and Run az cli commands.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.71GB (51.46GB free)|
|Process Argv|--crash-reporter-id 60e50c9c-4ca8-4c38-9d1e-4808da70c67f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|14.6.1
copilot|Git|1.143.0
copilot-chat|Git|0.11.1
vscode-github-actions|git|0.26.2
terraform|has|2.29.1
git-graph|mhu|1.30.0
azure-dev|ms-|0.8.0
vscode-azureresourcegroups|ms-|0.8.3
vscode-docker|ms-|1.28.0
vscode-dotnet-runtime|ms-|2.0.0
vscode-kubernetes-tools|ms-|1.3.15
azure-account|ms-|0.11.6
azurecli|ms-|0.5.0
powershell|ms-|2023.8.0
vscode-node-azure-pack|ms-|1.2.0
azurerm-vscode-tools|msa|0.15.11
vscode-yaml|red|1.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t:30925682

```

</details>

**Comment by meganrogge** [comment]
Does this reproduce in an external terminal?
