### ISSUE TITLE
When folded text is moved by drag and drop, the text will be unfolded and lost folding status

### ISSUE THREAD

**Issue by Takakiriy** [microsoft/vscode#201031]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
1.85.1

- OS Version: 
Any

Steps to Reproduce:

1. Fold a text
2. Select the folded text
3. Drag and drop the selected text moving to other line

Result:

Moved text is unfolded.
Folding status will be lost.
Folding status is fold state and unfold state at each line.

I must respond to:

I have to scroll to the beginning of a large selection of text and fold it again.

Expected Result:

The text that I moved remains collapsed and folding status.

**Comment by aeschli** [comment]
duplicate of https://github.com/microsoft/vscode/issues/78004
