### ISSUE TITLE
Single terminal tab `rename` action does not work

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#201025]
1. Right click on a single terminal tab
2. Select `rename`
3. 🐛 The quickpick doesn't open

Reproduces in stable

**Comment by jeanp413** [comment]
The same [context menu](https://github.com/microsoft/vscode/blob/6248d9bc358871fa51bc70de35538dbc8350c9dc/src/vs/workbench/contrib/terminal/browser/terminalMenus.ts#L579-L588) is used for both the terminal tabs and single terminal tab action view, the [rename action](https://github.com/microsoft/vscode/blob/6248d9bc358871fa51bc70de35538dbc8350c9dc/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L843-L886) used expects the tabs always present. Cannot create a different one as it's exposed as a contribution point `terminal/title/context`.
A possible fix would be to add a new context key to check whether terminal tabs is present or not and then handle that special case to do the rename with quick pick.
Thoughts @meganrogge.

**Comment by meganrogge** [comment]
Thanks for investigating and a new context key sounds like a good approach.

**Comment by jeanp413** [comment]
PR fixing it https://github.com/microsoft/vscode/pull/201128
