### ISSUE TITLE
Information tooltip on types / errors / warnings not displaying

### ISSUE THREAD

**Issue by Llacoste2000** [microsoft/vscode#201063]
Type: <b>Bug</b>

After some time of use, when an error appears or if I want to see the type of a variable (by hovering it), nothing gets displayed.
Only tested on Typescript projects.

VS Code version: Code - Insiders 1.86.0-insider (Universal) (789c802e75813bfb38ff2e13e4b322bd7e90124b, 2023-12-14T05:38:12.712Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|. --crash-reporter-id 86ae2c4f-d809-4062-81b2-87484b92d6ae|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (96)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.19.2
codesnap|adp|1.3.4
alpine-js-intellisense|adr|1.2.0
vscode-mslint|aes|1.0.0
markdown-mermaid|bie|1.21.0
git-exclude|bou|0.3.1
glsl-literal|boy|1.0.6
vscode-tailwindcss|bra|0.10.3
bruno|bru|3.1.0
multi-cursor-case-preserve|Car|1.0.5
turbo-console-log|Cha|2.9.10
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
regex|chr|0.4.0
glsl-canvas|cir|0.2.15
vscode-css-modules|cli|0.5.1
gitignore|cod|0.9.0
vscode-eslint|dba|2.4.2
FreeMarker|dco|0.0.9
composer-php-vscode|DEV|1.42.14455
intelli-php-vscode|DEV|0.11.14308
phptools-vscode|DEV|1.42.14455
profiler-php-vscode|DEV|1.42.14455
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.6.1
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|10.1.0
vscode-ionic-snippets|fiv|2.2.2
auto-rename-tag|for|0.1.10
copilot|Git|1.143.601
copilot-chat|Git|0.12.2023121501
copilot-labs|Git|0.17.1121
live-sass|gle|6.1.2
go|gol|0.40.0
go-nightly|gol|2023.12.800
todo-tree|Gru|0.0.226
vscode-drawio|hed|1.6.6
ionic|Ion|1.64.0
vscode-edit-csv|jan|0.8.3
batch-rename-extension|Jan|0.0.6
vscode-go-template|jin|0.2.1
svg|joc|1.5.3
node-module-intellisense|lei|1.5.0
vscode-language-babel|mgm|0.0.40
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-maniascript|mmc|1.2.3
vscode-scss|mrm|0.10.0
vscode-azureresourcegroups|ms-|0.8.3
vscode-docker|ms-|1.28.0
python|ms-|2023.22.1
jupyter|ms-|2023.11.1003402403
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.328.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
azure-account|ms-|0.11.6
hexeditor|ms-|1.9.12
remote-explorer|ms-|0.4.1
vsliveshare|ms-|1.0.5900
sqltools|mtx|0.28.1
sqltools-driver-mysql|mtx|0.6.0
sqltools-driver-pg|mtx|0.5.2
angular-console|nrw|18.10.1
bun-vscode|ove|0.0.12
material-icon-theme|PKi|4.32.0
vscode-react-refactor|pla|1.1.3
postman-for-vscode|Pos|0.16.0
prisma|Pri|5.7.0
webgl-glsl-editor|rac|1.3.7
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
vue-vscode-snippets|sdr|3.1.1
shader|sle|1.1.5
vscode-styled-components|sty|1.7.8
svelte-vscode|sve|108.1.0
sass-indented|syl|1.8.28
vsfire|tob|1.4.1
vscode-mdx|uni|1.6.0
vscode-gradle|vsc|3.13.5
vscode-java-debug|vsc|0.55.0
vscode-java-pack|vsc|0.25.15
gistfs|vsl|0.6.0
volar|Vue|1.8.25
vscode-typescript-vue-plugin|Vue|1.8.25
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
vscode-mdx-preview|xyc|0.3.3
local-history|xyz|1.8.1
pretty-ts-errors|yoa|0.5.2
markdown-all-in-one|yzh|3.5.1
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
vscrp:30624060
2i9eh265:30646982
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30901775
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Llacoste2000** [comment]
It's quite random, I didn't manage to reproduce it lately. It's way less frequent than the day I submited this issue (I think it has been stopping since the date I updated Copilot Chat). I think this issue can be paused / closed for the moment, I'll try to get clear informations when that happens, if it happens again. Thanks !

**Comment by mjbvz** [comment]
Closing as we can't investigate this without more information or a way to reproduce the problem
