### ISSUE TITLE
Support focusing the app when continuing debugging

### ISSUE THREAD

**Issue by tristanlabelle** [microsoft/vscode#201018]
When debugging a desktop app and hitting a breakpoint, the focus is given to Visual Studio code. When continuing execution, however, the focus is not given back to the executing app, and one must manually switch back to it. Big VS and Xcode have this feature and it's quite nifty.

This is most likely a per-debug adapter feature since it might not apply to some targets like the web. From a quick look at the VS Code, the debug API does not look rich enough to enable a debugger adapter-providing extension to be notified when debugging resumes, so  it might have to be implemented as a (custom?) DAP request, or as a flag to the DAP that it's okay to do presentation-related things in response to continue events.

Originally filed for the Swift extension here: https://github.com/swift-server/vscode-swift/issues/657

**Comment by roblourens** [comment]
Yeah, the DA will have to implement this because vscode doesn't know what the debuggee's window is, or what should happen. The extension could use a DebugAdapterTracker, or communicate with the DA via custom messages.
