### ISSUE TITLE
single tab context menu actions sometimes don't work

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#201008]
![image](https://github.com/microsoft/vscode/assets/18154705/defd6a90-be32-4ae6-b845-dcb4751e325a)
It's those 3 options that don't work, until there are multiple shells running.

Once you have two or more shells, those options start working, as below I'm showing me renaming successfully the 2nd shell:
![image](https://github.com/microsoft/vscode/assets/18154705/01352605-2187-4dc0-b8bf-4ca5bf072a56)

_Originally posted by @JeremyTBradshaw in https://github.com/microsoft/vscode/issues/200960#issuecomment-1858379484_

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/assets/29464607/6277bacb-e80f-4a4c-8397-bda2d371a7aa

**Comment by meganrogge** [comment]
I think related to this https://github.com/microsoft/vscode/issues/199228

**Comment by jeanp413** [comment]
PR fixing it https://github.com/microsoft/vscode/pull/201021

**Comment by meganrogge** [comment]
moving the issue with `rename` to this issue as it's not a recent regression https://github.com/microsoft/vscode/issues/201025
