### ISSUE TITLE
Terminal is not works

### ISSUE THREAD

**Issue by aliuq** [microsoft/vscode#201084]
Type: <b>Bug</b>

`Ctrl + J` opened terminal, But is empty

VS Code version: Code - Insiders 1.86.0-insider (37fe2d06d65db4b50303c5f5e8ca589a50f2287a, 2023-12-15T05:36:59.071Z)
OS version: Windows_NT x64 10.0.26002
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|39.70GB (20.51GB free)|
|Process Argv|--crash-reporter-id 3a9f3277-1326-4342-ad8a-5375edf7c9b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (73)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
project-manager|ale|12.7.0
tongyi-lingma|Ali|1.0.9
browse-lite|ant|0.3.6
file-nesting|ant|1.1.2
goto-alias|ant|0.1.2
iconify|ant|0.7.1
slidev|ant|0.4.2
unocss|ant|0.58.0
vite|ant|0.2.5
astro-vscode|ast|2.5.4
postcss|css|1.0.9
vscode-markdownlint|Dav|0.53.0
vscode-eslint|dba|2.4.2
gitlens|eam|14.6.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
docker-explorer|for|0.1.7
shell-format|fox|7.2.5
codespaces|Git|1.16.5
copilot|Git|1.143.601
copilot-chat|Git|0.12.2023121501
copilot-labs|Git|0.17.1121
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.78.1
gc-excelviewer|Gra|4.2.58
todo-tree|Gru|0.0.226
vscode-drawio|hed|1.6.6
rest-client|hum|0.25.1
vscode-env|Iro|0.1.0
svg|joc|1.5.3
vscode-home-assistant|kee|1.39.0
vscode-gutter-preview|kis|0.30.0
vscode-format-context-menu|lac|1.0.4
vscode-leetcode|Lee|0.18.1
i18n-ally|lok|2.12.0
rainbow-csv|mec|3.9.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.28.0
vscode-language-pack-zh-hans|MS-|1.85.2023121309
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.25.0
azure-repos|ms-|0.38.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.0
vsliveshare|ms-|1.0.5900
vscode-paste-image|mus|1.0.4
color-highlight|nau|2.5.0
postman-for-vscode|Pos|0.16.0
vscode-yaml|red|1.14.0
markdown-preview-enhanced|shd|0.8.11
code-spell-checker|str|3.0.1
vscode-stylelint|sty|1.3.0
svelte-vscode|sve|108.1.0
even-better-toml|tam|0.19.2
open-in-browser|tec|2.0.0
errorlens|use|3.16.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.6.0
volar|Vue|1.8.25
vscode-typescript-vue-plugin|Vue|1.8.25
vscode-wakatime|Wak|24.4.0
JavaScriptSnippets|xab|1.8.0
local-history|xyz|1.8.1
markdown-all-in-one|yzh|3.5.1
material-theme|zhu|3.16.2
vitest-explorer|Zix|0.2.43

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
vscrp:30624060
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpsinfo:30901776
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal

**Comment by meganrogge** [comment]
maybe related #200754
