### ISSUE TITLE
Internal view container ID surfaced when view moved to alternate side bar

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#201085]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Latest Insiders
- OS Version: macOS

Steps to Reproduce:

1. Move timeline view to secondary side bar
2. Find "Focus on Timeline View" command's display title (command palette, keybindings editor)
3. See `workbench.views.service.sidebar.07a48ef9-6c29-48cd-983f-56cf6ff46298: Focus on Timeline View`
4. Move timeline view back to explorer
5. See `Explorer: Focus on Timeline View`

<img width="1440" alt="image" src="https://github.com/microsoft/vscode/assets/8586769/4076e549-c21b-4376-9f2a-fa56cb989b03">

<img width="1440" alt="image" src="https://github.com/microsoft/vscode/assets/8586769/af3cd8f7-7ef3-4f7e-a29f-f09fd2978c0a">

<img width="1440" alt="image" src="https://github.com/microsoft/vscode/assets/8586769/5a155704-9786-4acc-9d25-61ad00ec2546">

Been like this for a few months now. Still see it in Insiders.

**Comment by JacksonKearl** [comment]
Not just Timeline

<img width="1440" alt="image" src="https://github.com/microsoft/vscode/assets/8586769/802f9e7d-4eb1-42c1-afef-200abe53a947">

**Comment by JacksonKearl** [comment]
cc @sbatten

**Comment by bpasero** [comment]
I miss the background, but wondering if https://github.com/microsoft/vscode/pull/207670 is the right fix. When I look at the code, there is a `doNotRegisterOpenCommand: true` directive:

https://github.com/microsoft/vscode/blob/9784f876f9d9f3c443d6313c533e342c89fb8a79/src/vs/workbench/services/views/browser/viewDescriptorService.ts#L511

Which is being respected here:

https://github.com/microsoft/vscode/blob/9784f876f9d9f3c443d6313c533e342c89fb8a79/src/vs/workbench/services/views/browser/viewsService.ts#L437-L439

There is no associated option to prevent registering a focus action though:

https://github.com/microsoft/vscode/blob/9784f876f9d9f3c443d6313c533e342c89fb8a79/src/vs/workbench/services/views/browser/viewsService.ts#L506-L507

But maybe there should be to stay in sync?

**Comment by sandy081** [comment]
Agreed. https://github.com/microsoft/vscode/pull/207670 does not seem to be the right fix.

`doNotRegisterOpenCommand` option allows view containers to register open command by themselves. This is allowed for legacy reasons, ie, before view containers were introduced, viewlets used to have the open commands registered by themselves. `focusViewAction` was introduced with View Containers feature and there was no need to surface similar option as it was new then.

**Comment by JacksonKearl** [comment]
I disagree that *removing* the focus command by introducing something like `doNotRegisterFocusCommand` would be the right fix. Currently, the only way to access the timeline using the Command Palette is via this focus command, and I do not think that removing it is a good idea. 
<img width="859" alt="image" src="https://github.com/microsoft/vscode/assets/8586769/71419538-79ed-4870-84ef-21cfeaebc299">

If we are to desire synchronization between the Open and Focus paths, I think it would make more sense to surface both but ensure proper labeling for both.

**Comment by bpasero** [comment]
Yeah, to clarify: I am not saying your fix is entirely wrong, but it seems inconsistent with the fact that we hide the commands to open views. I am fine having focus and open views for all, which sounds like a good accessibility feature too.

**Comment by JacksonKearl** [comment]
Could the patch to #207670 be simply removing the `doNotRegisterOpenCommand ` from: https://github.com/microsoft/vscode/blob/9784f876f9d9f3c443d6313c533e342c89fb8a79/src/vs/workbench/services/views/browser/viewDescriptorService.ts#L511

**Comment by bpasero** [comment]
I still find it very fishy that we do this:

https://github.com/microsoft/vscode/blob/bc278dfe7c8b0b050ae57f88bfdc4073dff30364/src/vs/workbench/services/views/browser/viewDescriptorService.ts#L507

**Comment by JacksonKearl** [comment]
Yes I agree, that's why I swapped it to use a real localized location title in the PR: https://github.com/microsoft/vscode/pull/207670/files#diff-898d043cbc55a0fe40e345f991ca5352218600ab8b4f121a67d88ca3adf0d5e2R507

**Comment by bpasero** [comment]
In your change, I would have expected the name of the view to appear as the title, not just the container name?

**Comment by JacksonKearl** [comment]
That's not what I observe, the titles used by the "chrome" UI (i.e. everything besides the command titles) do not take into account that title property. One bug I did notice with that implementation is that if you create a compound view container in the secondary side bar, then drag the entire container to the panel or the primary side bar, the label remains as "Secondary Side Bar: ...". Perhaps an option instead to not place the title in command labels at all?

**Comment by bpasero** [comment]
I am arguing that the `category` is actually not very helpful to find these focus commands. Views can be very much unrelated to the container they are in, so I suggest to not have it and just show the focus command without category.
