### ISSUE TITLE
Move Layout Controls position to the center of status bar

### ISSUE THREAD

**Issue by T-256** [microsoft/vscode#201040]
With top activity bar, title bar is crowded:
![image](https://github.com/microsoft/vscode/assets/132141463/f0aec298-ed6f-4173-b26d-9cf34543bf73)

Lapce example:
![image](https://github.com/lapce/lapce/blob/master/extra/images/screenshot.png?raw=true)

**Comment by sbatten** [comment]
I don't think we will add a center alignment for the status bar, but an extension can add these controls to the status bar.
