### ISSUE TITLE
Terminal top-right icons (➕,🗑, etc.) right-click context menu: "Clear Terminal" option to pin as button has gone missing

### ISSUE THREAD

**Issue by Keavon** [microsoft/vscode#201114]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Windows 10 22H2

Steps to Reproduce:
1. Right click one of the shortcut buttons in the top right of the integrated terminal to open the context menu which lets you customize which shortcut buttons show up:
  ![image](https://github.com/microsoft/vscode/assets/4388688/c54c56fc-49ef-487a-ad2d-466b474fd540)
2. "Clear Terminal" is missing from this list of button pinning options, however it used to be available in the previous month's version (once I updated, its icon disappeared and so did its listing in the menu shown above)

**Comment by meganrogge** [comment]
Maybe try insider's, it's showing up for me

![Screenshot 2023-12-18 at 10 58 07 AM](https://github.com/microsoft/vscode/assets/29464607/d5c6ab24-005e-45d3-a81b-ae3947747b9c)
