### ISSUE TITLE
Be able to download Microsoft built electron (Microsoft/vscode-electron-prebuilt)

### ISSUE THREAD

**Issue by ericzhucode** [microsoft/vscode#201176]
If I built a vscode by my own and it seems some features are lost. Like searching in webview because `findInFrame` function is not an original electron method. 
I found that when Microsoft vscode team builds vscode, you use a special electron tag and the download url should be
https://api.github.com/repos/Microsoft/vscode-electron-prebuilt/releases/tags/v22.3.18-22689846
but when I open this url, it shows `Not Found`

I take a look at the @vscode/gulp-electron repo in github which helps downloading electron in vscode and there's a test suite showing we need to use a token to download
https://github.com/microsoft/vscode-gulp-electron/commit/a39ee5bfd99ba44549f892ce5284d4ff2da8a8c4 Can we download that build version?

**Is it possible to give developers in community the access to this electron version?**

Or is it **possible to add this feature to original electron repo**? I noticed your team has already been processing on this but it seems the commit has not been merged yet.
https://github.com/microsoft/vscode/issues/96307
https://github.com/electron/electron/pull/28274

**Comment by deepak1556** [comment]
We are in the process of upstreaming the features and in the near future we are targeting feature parity but there are no plans to open up https://github.com/Microsoft/vscode-electron-prebuilt.
