### ISSUE TITLE
VS code server - remote tunnel: grant only some specific client addresses

### ISSUE THREAD

**Issue by badien** [microsoft/vscode#201179]
- allow vscode server (tunnel CLI / interface) to restrict or grant some specific public addresses from client access via vscode.dev 
- this will be useful for some organizations / small team to control and manage developers from their dev environments

**Comment by connor4312** [comment]
Are you referring to forwarded ports or the tunnel connection on vscode.dev itself?

**Comment by badien** [comment]
I am mentioning to tunnel connection, it should be setup when run vscode server using remote tunnel. However if possible, it should also be included local port forwarding because using same dev tunnel.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-remote-release/issues/7714

**Comment by badien** [comment]
@connor4312 you have confused my mean, my suggestion is that restrict or grant some specific public IP addresses from client, not mention to account / user. Example: i enable vscode server and allow only IP address as 123.456.789.222 from internet, when if client connect from this network, they can access to vscode server, if not ignore connection. Thanks.

**Comment by connor4312** [comment]
The request is part of a broader work to support multiple users in the tunnel, which I'm tracking in that issue ^
