### ISSUE TITLE
Support debug console output from extensions

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#20113]
Since debug extensions start to have more code running in the extension, we need a way that this code can send information messages to the same channel ('debug console') as debug adapters.

One example: https://github.com/Microsoft/vscode-node-debug/issues/126

**Comment by isidorn** [comment]
@weinand do we want to support different severity? I think yes as this can increase clarity if there are multiple messages

**Comment by weinand** [comment]
@isidorn IIRC the debug console maps the 'console', 'stdout', 'stderr' categories of the DAP `OutputEvent` to some 'severity' styles. So an extension cannot freely use 'severity' because they are already used for something else.

On the other hand I do not see a need for an extension to send messages to a different category other than 'console'.

Bottom line: neither a 'severity' nor a 'category' is needed for this API.

**Comment by isidorn** [comment]
Now you can do the following from your extension
`vscode.commands.executeCommand('debug.logToDebugConsole', 'hello Rob and Andre')`

Try it out and let me know how ti works for you

**Comment by weinand** [comment]
If I use this API before the debug session has been started by means of `vscode.commands.executeCommand('vscode.startDebug', config);` the output does not show up because it is immediately cleared by the `vscode.startDebug`command.
