### ISSUE TITLE
"vscode.FileSystemWatcher" creates incorrect event on network mount locations [NFS/SMB mounted to a location]

### ISSUE THREAD

**Issue by jlmanohar** [microsoft/vscode#201103]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.85.1
- OS Version: Fedora 39 (Linux fedora 6.6.6-200.fc39.x86_64 )

Steps to Reproduce:

1. Install VSCode 1.85.1
2. Create a new extension following the guide from [Your First Extension](https://code.visualstudio.com/api/get-started/your-first-extension) 
3. Create a new FileSystemwatcher (I created for only java files)
```vscode.window.showInformationMessage('Hello World from fsWatcher!');
		var watcher = vscode.workspace.createFileSystemWatcher("**/*.java");
		watcher.onDidCreate(() => {
			console.log("Create event");
		});
		watcher.onDidChange(()=>{
			console.log("Change event");
		});
```
4. Run the extension by pressing f5
5. Add two or more folders to the workspace, one folder from the filesystem (btrfs in my case), another from any mounted network location (smb in my case)
6. Create file and save file in both of the folders.

Expected:
Created event should be generated when file is created

Actual:
Changed event is generated when file in created in smb location

Sample extension that i used:
[fswatcher.zip](https://github.com/microsoft/vscode/files/13701181/fswatcher.zip)

Screen capture:
[filesystemwatcher issue.webm](https://github.com/microsoft/vscode/assets/66161434/626597cd-0871-49d9-b6ce-3df48ca83d08)

**Comment by jlmanohar** [comment]
This issue is not new to 1.85.1, this happened from atleast 1.82.1 when i observed it.
My initial assumption was its was an extension issue for the extension "Java project Manager" so i reported it there
https://github.com/microsoft/vscode-java-dependency/issues/787

**Comment by bpasero** [comment]
This issue could originate from a problem with file watching. Let me explain how file watching works in VSCode first and then provide some details how to get more logging data from how file watching behaves in your case.

**Synopsis**
VSCode has different strategies for file watching depending on your workspace and setup:
* no folder opened: files in opened editors are watched via node.js `fs.watch`
* folder opened: folder is watched recursively for all changes via [parcel](https://github.com/parcel-bundler/watcher), opened editors with files not within the folder are watched via node.js `fs.watch`

If you are connected to a remote (SSH, WSL, Docker), the file watcher will run within the target file system. As such, even though you maybe on Windows where VSCode runs, if the remote is Linux, the file watcher will run in the Linux environment.

**Platforms**
Depending on the platform you are on, file watching is differently implemented:
* macOS: using `fsevents` services
* Windows: using `ReadDirectoryChangesW` method
* Linux: using `inotify`

Specifically on Linux, watching a large folder recursively can result in VSCode consuming too many file handles. If that is the case, you will see a warning notification with instructions how to solve that.

**Limitations**
File watching comes with a set of limitations:
* symbolic links are not followed automatically but you can explicitly add symbolic links to be watched via the `files.watcherInclude` setting
* mapped network drives or third party file system drivers are not guaranteed to produce file events
* in general, the operating system may decide to drop file events at any time, there is no 100% guarantee

**Settings**
Please review your settings to see if maybe a folder is excluded by accident. Specifically, the `files.watcherExclude` setting is relevant.

**Logging (local)**
!!! This is ONLY when you open a local workspace, for remote see below !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the local workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `Help | Toggle Developer Tools`
* select `Console`
* filter the output by typing `File Watcher` into the filter box
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323290-f3ba6470-dfed-4066-a19c-951395611738.png)

**Logging (remote)**
!!! This is ONLY when you open a remote workspace (WSL, Docker, SSH), for local see above !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the remote workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `View | Output`
* select `Log (Remote Server)` from the dropdown
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323886-6b7dfa25-d6ac-4316-9150-80e5c8104d04.png)

**Comment by bpasero** [comment]
Fyi besides what I posted, file events over network shares work on a "may work, may not work" basis. They are generally quite unreliable.

**Comment by jlmanohar** [comment]
Yes, can confirm that the event is created as changed instead of created from parcel watcher. Let me test it on a windows machine as well.

Is there a way to improve the event detection ? My use case requires me to use only network drives to store my project files.

```
DEBUG _performFileEdits [{"newResource":{"$mid":1,"path":"/home/jlmanohar/smb4k/192.168.29.254/share/testsmb/test.java","scheme":"file"},"options":{"folder":false}}]
log.ts:401 TRACE KeybindingService#dispatch Enter [ No matching keybinding ]
log.ts:401 TRACE [File Watcher (parcel)] [CHANGED] /home/jlmanohar/smb4k/192.168.29.254/share/testsmb/test.java
log.ts:411 DEBUG [DEBOUNCE: Folding] is disabled in developed mode
log.ts:401 TRACE [IE] (editor:vs.editor.ICodeEditor:1)NEW controller
log.ts:401 TRACE [text file model] resolve() - enter file:///home/jlmanohar/smb4k/192.168.29.254/share/testsmb/test.java
log.ts:401 TRACE [text file model] resolveFromFile() file:///home/jlmanohar/smb4k/192.168.29.254/share/testsmb/test.java
```

**Comment by bpasero** [comment]
You can try to report as issue on https://github.com/parcel-bundler/watcher.
