### ISSUE TITLE
"TODO" highlight is off by one character if there are syntax errors

### ISSUE THREAD

**Issue by php4fan** [microsoft/vscode#201142]
Does this issue occur when all extensions are disabled?: Extension bisect doen't work, so I don't know

- VS Code Version:  1.85.1
- OS Version: Manjaro Linux

Steps to Reproduce:

Look at the screenshot:

![image](https://github.com/microsoft/vscode/assets/13969584/84be4075-61ca-4c83-8c21-de0b32c768bb)

The "TODO" highlight is off by one character.

I know, there is a syntax error and therefore I cannot expect perfect syntax highlight of code after the syntax error. But either you completely stop highlighting everything that comes after the syntax error and grey it out (which would arguably be more useful than having randomly broken highlight), or if you do keep highlighting code even after an error, you do it sensibly. To highlight 4 characters at some random position somewhat near the substring "TODO" makes no sense and it's not justified by the presence of a syntax error before.

**Comment by ulugbekna** [comment]
VS Code does not highlight TODO's automatically, as far as I know. You must be using an extension that's highlighting with an off-by-one error. Please, check your installed extensions.
