### ISSUE TITLE
Typo in Open/Save-DialogOptions filters property

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#201136]
The examples in the [OpenDialogOptions.filters](https://code.visualstudio.com/api/references/vscode-api#OpenDialogOptions.filters) and [SaveDialogOptions.filters](https://code.visualstudio.com/api/references/vscode-api#SaveDialogOptions.filters) have a typo.

The `,` is missing as object property separator:

```js
{
    'Images': ['png', 'jpg']
    'TypeScript': ['ts', 'tsx']
}
```

should be
```js
{
    'Images': ['png', 'jpg'],
    'TypeScript': ['ts', 'tsx']
}
```

**Comment by gregvanl** [comment]
@rioj7 Thanks for pointing out the typos! As mentioned above, the API reference will be updated when the 1.86 release goes out early February
