### ISSUE TITLE
Not possible to add options to string properties 

### ISSUE THREAD

**Issue by tilor** [Microsoft/vscode#20115]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

I'm
Steps to Reproduce:

1. Create a file like this but with only 2 PathTypes (without PATHTYPE_WORKSPACE):
export const PATHTYPE_WORKSPACE = "W";  // This line comes later
export const PATHTYPE_FOLDER = "F";   
export const PATHTYPE_PROCESS = "P"; 
export type PathType = "F" | "W" | "P";

export interface PathDetails {
  workspaceId: string,
  pathId: string,
  parentPathId?: string,
  pathType: PathType 
}

2. Add the additional option "PATHTYPE_WORKSPACE"

3. Now PATHTYPE_WORKSPACE cannot be assigned to pathType, only "F" and "P" are allowed:
error TS2365: Operator '==' cannot be applied to types '"F" | "P"' and '"W"'.

-> Somehow VS Code and/or TypeScript are caching the old property settings?
Reload, restart etc. don't help.

Is there an option to refresh properties?

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this
