### ISSUE TITLE
Incorrect "window.menuBarVisibility" behaviour between restarts

### ISSUE THREAD

**Issue by CrumpyOldLord** [Microsoft/vscode#20119]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|alignment|annsk|0.3.0|
|latex|ms-vscode|0.1.3|

---

Expected behavior: menu bar remains hidden
Actual behavior: menu bar becomes visisble after restart

Steps to Reproduce:

1. Set ` window.menuBarVisibility` to `hidden`
2. Close VS Code and open it again

The menu bar is now permanently visible, as if set to `default`. Setting the option to `toggle` and then back to `hidden` hides the menu bar, but this solution does not persist to the next session.

**Comment by bpasero** [comment]
Fixed in our insiders release (via https://github.com/Microsoft/vscode/issues/19777).

Time to join insiders! You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
