### ISSUE TITLE
Application won't launch

### ISSUE THREAD

**Issue by axman6** [Microsoft/vscode#20116]
- VSCode Version: 1.9.0
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. Try to open the application - Application icon appears briefly in the dock and then exits. There is nothing in any log that I can find (dmesg, system log in console.app, crash logs), no errors, nothing at all to go on. The only thing that I can think of that might have broken things is the macOS window server crashing and having to log in again probably leaving something in an inconsistent state, but I have no idea where to start looking.

Good thing I don't need a text editor for my job as a software engineer.

**Comment by bpasero** [comment]
@axman6 I wonder if there is a leftover code process running in the background? can you either check in Activity manager or do a restart and try again?

**Comment by axman6** [comment]
@bpasero Looks like you nailed it, that's exactly what was going on, I'm disappointed I didn't think of it! And apologies for the snarky comment, this was the last straw at the end of a very frustrating day.

**Comment by bpasero** [comment]
@axman6 no worries, glad you can run it again 👍
