### ISSUE TITLE
vsix file is not self-sufficient

### ISSUE THREAD

**Issue by fredpouyet** [microsoft/vscode#201127]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. prepare a vsix file for python extension compatible with visualstudio code 1.82.2 or above under x86_64/RHEL7 
2. use visualstudio code with no internet access 
3. code & 
4. select extension menu -> ... -> "install from VSIX"

You will see that installation does not complete and our IT observed some traffic queries, that we are not in position to grant due to export control reasons

**Comment by fredpouyet** [comment]
Does this issue occur when all extensions are disabled?: Yes
VS Code Version: > 1.82.2
OS Version linux/RHEL7

**Comment by fredpouyet** [comment]
Hello VSC support, any update on this? please thanks Fred

**Comment by sandy081** [comment]
> You will see that installation does not complete and our IT observed some traffic queries, that we are not in position to grant due to export control reasons

Thats true, but it does not prevent installing the extension from VSIX. Can you please check if extension installation succeeded or not?

**Comment by fredpouyet** [comment]
Hi Sandy08,
how can I check this? I bet it did not as there was no python extension installed.

**Comment by sandy081** [comment]
If succeeded, you can see extension in the installed section of extensions view.

**Comment by fredpouyet** [comment]
Yes, I do not have that.

**Comment by sandy081** [comment]
Can you please share the following log while you install the extension

- F1 > Open View... > Shared

**Comment by fredpouyet** [comment]
Hello here it is. 
[shared.log](https://github.com/microsoft/vscode/files/13857742/shared.log)

**Comment by sandy081** [comment]
Seems there is an error while installing the extension, can you please enable log level to trace (`F1 > Developer: Set Log Level > Trace`) and share the log again?

**Comment by fredpouyet** [comment]
Log with trace 
[log_with_trace.log](https://github.com/microsoft/vscode/files/13858053/log_with_trace.log)

**Comment by sandy081** [comment]
I do not see the error information in the log, can you please share the window log

> F1 > Open View... > Window

**Comment by fredpouyet** [comment]
Here is the new log 
[log_3.log](https://github.com/microsoft/vscode/files/13859271/log_3.log)

**Comment by sandy081** [comment]
This does not seems to be the one I requested. Please share the window log

- F1 > Open View... > Window

**Comment by fredpouyet** [comment]
sorry here it is 
[trace_4.log](https://github.com/microsoft/vscode/files/13860607/trace_4.log)

**Comment by sandy081** [comment]
Following error is shown when an extension is being installed (unzipping the VSIX)

```
ENOENT: no such file or directory, mkdir '/arm/tools/visualstudio/vscode/1.82.2/VSCode-linux-x64/resources/app/extensions/.90678910-2e5a-466d-83f9-8f13af54e290': Extract: ENOENT: no such file or directory, mkdir '/arm/tools/visualstudio/vscode/1.82.2/VSCode-linux-x64/resources/app/extensions/.90678910-2e5a-466d-83f9-8f13af54e290'
```

Does your system has issues with extracting zips?

**Comment by fredpouyet** [comment]
Indeed, as users we cannot create directory under /arm/tools. Only our CAD department can

**Comment by sandy081** [comment]
Extension can be installed only by extracting the VSIX. Unfortunately nothing can be done here.

**Comment by fredpouyet** [comment]
Hello @sandy081 , 

I do not understand the closure. The issue is not resolved. I forsee a next action : enhance the tool so that vsix does not have a dependency on installation root to be writable. This is quite common to restrict access installation root by CAD team, still users should be able to install vsix (extensions) without involving CAD team.
Please reopen the ticket, I can also recreate a new ticket

thanks
Fred
