### ISSUE TITLE
[Certificate] https://*.visualstudio.com/  NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by ultravires** [microsoft/vscode#201101]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest
- OS Version: macos 14.2 (23C64)

Steps to Reproduce:

<img width="898" alt="image" src="https://github.com/microsoft/vscode/assets/26894991/0b36cd14-8fec-476c-ae88-5639233aa153">

**Comment by chrmarti** [comment]
Searching the web for djfidicjmwos.com suggests that this is an issue on your ISP's side and not with any of the visualstudio.com websites.
