### ISSUE TITLE
'Open in vs code' not showing in Windows 11 Context Menu

### ISSUE THREAD

**Issue by hassancoder1** [microsoft/vscode#201112]
Type: <b>Bug</b>

Hi Visual Studio Code Support Team, As we all know Windows 11 introduced new Menu when we right click on screen. I noticed it in start but didn't took it serious and expecting that you will solve soon. but now it's december 2023 now. The issue is that when we right click mouse button either on desktop, in File Explorer in and Folder or on right clicking any file/Folder. I can see Windows 11 new menu but I everytime needs to click on show more options to see old windows Menu and then click on "Open with Code" option. it's not compatible or not supporting windows 11 new menu.  

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz (4 x 2095)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (1.91GB free)|
|Process Argv|E:\\Hassan Ali\\Learnings\\Reactjs\\100 days\\todo-mongo --crash-reporter-id 67bb8b08-037c-401b-af60-90aaf1a9d5fd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.1.4
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
remotehub|Git|0.62.0
live-sass|gle|6.1.2
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.13
remote-repositories|ms-|0.40.0
vs-html-to-css|nep|1.0.0
material-icon-theme|PKi|4.32.0
vscode-thunder-client|ran|2.16.2
es7-react-js-snippets|rod|1.9.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by sbatten** [comment]
How did you install VS Code?

**Comment by hassancoder1** [comment]
@sbatten I remember, I checked the (add to the context menu) box

**Comment by hassancoder1** [comment]
Check it
https://github.com/microsoft/vscode/assets/128244826/38b4671d-f262-4773-bddb-a1b8f9dc6fea

**Comment by Zastai** [comment]
Same issue for me; uninstalled and reinstalled VS Code to be sure (using the system installer) and checked both explorer integration options during the install. The entries appear only in the "more options" context.
