### ISSUE TITLE
activeEditor and other context keys are incorrect when vscode is launched

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#201181]
Type: <b>Bug</b>

When first opening vscode or reloading the window several context keys are set to incorrect values. These values may eventually be corrected when focusing another editor and returning to the original one.

The keys I have noticed with this issue are:
* `activeEditorIsFirstInGroup`
* `activeEditorIsLastInGroup`
* `activeEditorIsNotPreview`
* `activeEditorIsPinned`
* `canNavigateBack`
* `hasWordHighlights`
* `languageSupportsDisassembleRequest`
* `scmActiveResourceHasChanges`
* `scmActiveResourceRepository`
* `typescript.isManagedFile`
* `workbench.accounts.experimental.showEntitlements`

It can be a little tricky to catch some of them misbehaving. It depends on which editors you have open and how they are arranged.

![image](https://github.com/microsoft/vscode/assets/484784/a2566798-88bf-4e4d-87ca-d79b661f205e)

Steps to repro:
* Open 2 editors
* Focus the first editor
* Pin it
* Record context keys
* Reload window
* Record context keys
* Diff the two sets of context keys and notice they are not the same

VS Code version: Code - Insiders 1.86.0-insider (279872bd965e4030c81129a9bf1ce1710ff7cd55, 2023-12-18T05:36:59.983Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.25GB free)|
|Process Argv|--crash-reporter-id 22cf4e37-a96e-4ad9-82f0-8715f8e2bf6e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
2i9eh265:30646982
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpsinfo:30901776
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232
cp7184t:30925682

```

</details>

**Comment by bpasero** [comment]
Ben, maybe you could check for the ones in editor area since you recently fixed some issues there. Maybe its a regression?

**Comment by benibenj** [comment]
The following context keys were not being updated on reload:
`activeEditorIsFirstInGroup`
`activeEditorIsLastInGroup`
`activeEditorIsNotPreview`
`activeEditorIsPinned`
`activeEditorGroupLocked`

Updating them now on reload

**Comment by akbyrd** [comment]
This seems to apply to a few additional context keys outside of `activeEditor*`. Just a heads up in case closing the issue was accidental.
