### ISSUE TITLE
Gulp tasks not detected automatically since upgrading to 1.9

### ISSUE THREAD

**Issue by fparadise** [Microsoft/vscode#20111]
- VSCode Version: 1.9
- OS Version: Windows 7

Steps to Reproduce:

1. Open a folder with a gulpfile.js
2. Type `task default` in the command panel 
3. No tasks detected

Since upgrading to last version (1.9), VS Code doesn't detect Gulp tasks automatically from the gulpfile.js. I tested this on 2 computers and on different projects that were working fine on 1.8 and before.

I found a workaround : use the `Configure Task Runner` command, let it create a tasks.json and then use the `task` command.
Is it now the desired behavior? I didn't see any mentions about this in the changelog.

Thanks.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/19743.
