### ISSUE TITLE
The TreeDataProvider of reference view gets called twice.

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#201182]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.86.0-insider (Universal)
Commit: 279872bd965e4030c81129a9bf1ce1710ff7cd55
Date: 2023-12-18T05:37:34.083Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0

Background:

The Java extension leverage reference view extension to show type hierarchy (via its extension api). The implementation has not been changed for a long time. But recently it stops working. When I debug the code, I found that the [TreeDataProvider](https://github.com/microsoft/vscode/blob/a017b12b9caa3475675cfe6fda014fcf5af388c9/extensions/references-view/src/references-view.d.ts#L91) (provider used by the api model) of the reference view will be called twice for the first time.

See the below video:

https://github.com/microsoft/vscode/assets/6193897/98b78ee4-89bb-4c47-9694-d81a8f71f46d

The `getChildren()` get called twice, but the input element is always `undefined` (when getting the root node).

This causes a problem, because in our extension, [a node is assigned a random id](https://github.com/redhat-developer/vscode-java/blob/1cb8d0c77fb2a0da1381520bac65e36826a40c84/src/typeHierarchy/model.ts#L136) because of [this issue](https://github.com/microsoft/vscode/issues/114614#issuecomment-763428052).

Since the TreeDataProvider called twice, I guess some state of the reference view tree become out-of-sync. If a new request sent to the reference view, a error like below will be thrown:

```
rejected promise not handled within 1 second: Error: TreeError [references-view.tree] Data tree node not found: [object Object]
```

Not sure if I declare the problem clear enough. Please let me know if having any question :)

**Comment by jrieken** [comment]
This might be due to tree sticky scroll? @jdneo do you have the enabled by any chance?

> This causes a problem, because in our extension, [a node is assigned a random id](https://github.com/redhat-developer/vscode-java/blob/1cb8d0c77fb2a0da1381520bac65e36826a40c84/src/typeHierarchy/model.ts#L136) because of https://github.com/microsoft/vscode/issues/114614#issuecomment-763428052.

@alexr00 to comment on that but that sounds fishy to me

**Comment by alexr00** [comment]
I was thinking that this change maybe caused a problem, but it doesn't appear to be `getChildren` to be caused twice: 95147456e499613748ceb03a3e82e7b31c3323f6

**Comment by alexr00** [comment]
> This causes a problem, because in our extension, [a node is assigned a random id](https://github.com/redhat-developer/vscode-java/blob/1cb8d0c77fb2a0da1381520bac65e36826a40c84/src/typeHierarchy/model.ts#L136) because of https://github.com/microsoft/vscode/issues/114614#issuecomment-763428052.

This is fishy. Instead of setting a random ID I would suggest you make an ID that looks something like `symbolThatWasSearchedFor-file-symbolPosition`. Then, when the user re-searches for the same symbol their expand/collapse state will be preserved.

**Comment by alexr00** [comment]
I am not able to reproduce `getChildren` being called twice. My steps:

1. 
```java
class Test
{
    public static void main(String[] args)
    {
        System.out.println("hello world");
        System.out.println(args[0]);
    }
};
```
2. Cursor in `println`, run Java: Show Type Hierarchy

Is there something else I need to do?

**Comment by jdneo** [comment]
> This is fishy. Instead of setting a random ID I would suggest you make an ID that looks something like symbolThatWasSearchedFor-file-symbolPosition

Thank you for the suggestion. I'll try it.

> Is there something else I need to do?

Usually it will happen for the first time requesting for type hierarchy. You can try request the Type Hierarchy on the symbol `System`.

Meanwhile, if you keep request type hierarchy on `System` for 2~3 times. You will see the error `Data tree node not found: [object Object]`

**Comment by jdneo** [comment]
> I would suggest you make an ID that looks something like symbolThatWasSearchedFor-file-symbolPosition

Ok, after asking the owner of the original issue, his original request is to not reserve the collapse state. He wants to have a 'refresh' tree for each request.

Since this is related with the UX, I've no idea from users' perspective, which one is preferred.

But I can confirm that after applying a stable id for the nodes, The feature will be working again. I can use this as a quick fix for the issue from the java extension side.

**Comment by alexr00** [comment]
@jdneo can you try your scenario again with the latest VS Code insiders? I'm thinking that `getChildren` being called twice was a red herring. I fixed https://github.com/microsoft/vscode/issues/201196 yesterday and I suspect that this may solve your issue.

**Comment by jdneo** [comment]
I tried:

Version: 1.86.0-insider (Universal)
Commit: 9621add46007f7a1ab37d1fce9bcdcecca62aeb0
Date: 2023-12-20T05:38:07.020Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0 

For the first time, the `getChildren` is still called twice with `undefined` as input, see below video:

https://github.com/microsoft/vscode/assets/6193897/91fb8a84-88e3-4d7a-899f-7875f7924351

But, the good news is that the type hierarchy feature in java works again without any change in the latest insiders. I kept triggering it for different symbols and it worked for all of them!

**Comment by alexr00** [comment]
Great. I don't know that `getChildren` being called twice with `undefined` is new or even a problem. As far as I can see, there's a way it could have always gotten called twice. The calls to `this._provider.update` and `this.clearInput` both will cause this:

https://github.com/microsoft/vscode/blob/d32043d8b8d54b96abe7fe28ac48f02e3419b8ef/extensions/references-view/src/tree.ts#L70-L82

**Comment by jdneo** [comment]
Hi @alexr00,

Will VS Code team make a recovery release in January containing this fix? I found that once the tree view goes into the 'wrong' state, all other features like `call hierarchy, find references` stops working as well.

**Comment by testforstephen** [comment]
See https://github.com/microsoft/vscode-maven/issues/1013, multiple users of vscode-maven extension have reported that the tree nodes of maven explorer are overlapping when using vscode@1.85.0 version. This issue doesn't exist in 1.84, it seems same reason as https://github.com/microsoft/vscode/issues/201196.

> Will VS Code team make a recovery release in January containing this fix?

+1 for this. @alexr00

**Comment by alexr00** [comment]
I would like to make a recovery release for this, but at present this is the only bug fix that would be included in the recovery. If that changes then we might make a recovery release.
