### ISSUE TITLE
collect2.exe: falat error

### ISSUE THREAD

**Issue by AnuzzKhatri** [microsoft/vscode#201150]
Type: <b>Performance Issue</b>

Always getting this issue since 2 days don't know why, and got very irrtative about this i can't able to code plz help me
collect2.exe: fatal error: CreateProcess: No such file or directory
compilation terminated.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|5.85GB (1.70GB free)|
|Process Argv|--crash-reporter-id d917ce65-a397-4831-83d1-03746f6b038c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   103	  9620	code main
    0	    31	  1264	ptyHost
    0	    63	 11740	   gpu-process
    0	     8	 14008	   crashpad-handler
    0	    52	 15124	shared-process
    0	    95	 18796	extensionHost [1]
    0	    30	 10888	     electron-nodejs ("C:\Users\anuvansh\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\anuvansh\.vscode\extensions\mtxr.sqltools-0.28.1\dist\languageserver.js --node-ipc --clientProcessId=18796)
    0	    28	 24864	     electron-nodejs ("C:\Users\anuvansh\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\anuvansh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=18796)
    0	    74	 27248	     c:\Users\anuvansh\.vscode\extensions\ms-vscode.cpptools-1.18.5-win32-x64\bin\cpptools.exe
    0	     2	 25180	       "c:\Users\anuvansh\.vscode\extensions\ms-vscode.cpptools-1.18.5-win32-x64\bin\cpptools.exe"
    0	    14	 23200	         c:\Users\anuvansh\.vscode\extensions\ms-vscode.cpptools-1.18.5-win32-x64/bin/cpptools-srv.exe 27248 {6811B867-9C82-447A-92CC-6211A1481893}
    0	     7	 20956	           C:\Windows\system32\conhost.exe 0x4
    0	    36	 24668	         c:\Users\anuvansh\.vscode\extensions\ms-vscode.cpptools-1.18.5-win32-x64/bin/cpptools-srv.exe 27248 {49A63C9F-2A9B-4570-B4EF-6DAEB2EC85D8}
    0	     7	 26816	           C:\Windows\system32\conhost.exe 0x4
    0	     6	 27696	       C:\Windows\system32\conhost.exe 0x4
    0	    38	 20444	fileWatcher [1]
    0	    14	 22856	   utility-network-service
    0	   191	 23868	window [1] (conversions.cpp - Untitled (Workspace) - Visual Studio Code [Administrator])
    0	    97	 28492	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (conversions.cpp - Untitled (Workspace) - Visual Studio Code [Administrator])
|    Folder (.vscode): 9 files
|      File types: json(8)
|      Conf files: launch.json(2) settings.json(2) tasks.json(1)
|      Launch Configs: cppdbg(4) extensionHost(3) cmake
|    Folder (C++ Course): 38 files
|      File types: cpp(13) exe(11) json(8) md(1) ini(1)
|      Conf files: launch.json(2) settings.json(2) tasks.json(1)
|      Launch Configs: cppdbg(2) cppvsdbg
|    Folder (C course): 0 files
|      File types:
|      Conf files:;
```

</details>
<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.53.0
gitlens|eam|14.6.1
EditorConfig|Edi|0.16.4
code-runner|for|0.12.1
c-cpp-runner|fra|9.3.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
sqltools|mtx|0.28.1
java|red|1.25.1
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.13.5
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.43.0
vscode-spring-initializr|vsc|0.11.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t:30925682

```

</details>

**Comment by bpasero** [comment]
From the description the issue sounds like a setup / configuration problem outside of VSCode and nothing VSCode itself could fix.

VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

We also have a large community over at https://stackoverflow.com/questions/tagged/visual-studio-code to ask for advice.

Happy Coding!
