### ISSUE TITLE
Copilot chat: pressing arrow down on last line in prompt box clears content.

### ISSUE THREAD

**Issue by kaigr** [microsoft/vscode#201269]
When typing in the Copilot chat box, if you press arrow down on the last line, the entire contents of the prompt are lost and a new prompt is started.  Pressing arrow up doesn't return the lost (unsubmitted) text, but instead returns to the last-submitted prompt.  It's happened to me many times today, when I'm arrowing up to check earlier text within the prompt, then arrow down to return to the last line to keep typing, but if I overdo it with arrowing down... all my typing goes away & I have to start over.

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Embedder: codespaces

**Comment by rogiervandenberg** [comment]
Yes, I have exactly the same thing. To type a good prompt I sometimes move my cursor up and down the "ask copilot" form.

- When hitting the end, the form containing my new prompt is cleared before sending
- When hitting the top, I get my earlier prompt that already has been sent

Annoying behaviour. I'd rather stay in the current text without removing or loading the previous one, OR have a way to get my just typed text back.

**Comment by leo-diehl** [comment]
Just seconding this request. I had a situation where I lost a big prompt I was developing because of this feature.

**Comment by roblourens** [comment]
Tracking this in https://github.com/microsoft/vscode-copilot-release/issues/661

**Comment by MarciusP** [comment]
Was this solved? My VSCode is up to date, but I am still having this issue.

https://github.com/microsoft/vscode/assets/49277079/076f856a-45a0-44eb-aa14-4dc8f32512c2

**Comment by danielbalcells** [comment]
Seconding as an annoying issue, thanks! 

I'm temporarily disabling the keybindings that result in this behavior:
- `inlineChat.nextFromHistory` (arrow down)
- `inlineChat.previousFromHistory` (arrow up)

**Comment by roblourens** [comment]
It's fixed in Insiders which will be released to stable at the end of the month
