### ISSUE TITLE
When the debug debugging, the node cannot be started

### ISSUE THREAD

**Issue by katoongzhe** [Microsoft/vscode#20123]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.1.0|

---

Steps to Reproduce:

1.So much about the debug debugging, the node cannot be started
2.I have to restart the vscode to save it.

**Comment by weinand** [comment]
@katoongzhe please provide reproducible steps. 
What do you mean by "debug debugging"?
