### ISSUE TITLE
Open a file from another repo do not open repo under 'EXPLORER' or  'SOURCE CONTROL' - `GIT: Open Repository` not working

### ISSUE THREAD

**Issue by fenchu** [microsoft/vscode#201272]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.85.1
- OS Version: windows 11 (Windows-NT x64: 10.0.22631

Steps to Reproduce:

1.  start vscode for one repo - all is fine
2.  open the terminal and use the code to open a file from a different repo, the file show up, but nothing happens under source control.
3. I've used this for years to move files between repo and check their diffs before checking in.
4. using the cmmand `shift+ctrl+p` `>Git: Open Repository` do not do anything. Do not see anything in the develper console

Current workaround is to open separate vscode instances for each repo. (it become lots of windows)

Enclosed is a screenshot from vscode in trk report, where I open up a file in hemit-repo, and nothing happens in source control:

![vscode-open-repo-do-not-work](https://github.com/microsoft/vscode/assets/11349883/1927eb48-8c3e-42a7-b2d7-fb4608e0376d)

**Comment by fenchu** [comment]
I tried rebooting and then vscode come up with explorer showing the original repo, but the file loaded is in different repo:
![Skjermbilde 2023-12-20 101831](https://github.com/microsoft/vscode/assets/11349883/f41187ef-8ce4-4542-817e-cccb6b7a6742)
And nothing in sourcecontrol, even I know the file has changed.

**Comment by lszomoru** [comment]
@fenchu, could you please check the value of the `git.autoRepositoryDetection`. Could you please make sure that the value of set to `true`? Also could you invoke the "Source Control: Focus on Source Control Repositories View" command from the command palette? Do you see both repositories there? Thanks!

**Comment by fenchu** [comment]
Thanks for the feedback,
git.autoRepositoryDetection was set to true.
I set it to subfolders, and restarted then I set to true again and started `code ..\<another-repo>\file
Then it asked if I wanted to open this repo, and it then opened up.

Thansk so much, I close this.
