### ISSUE TITLE
Debug: [nodejs] some logs by logging libs are not shown in console

### ISSUE THREAD

**Issue by wkrueger** [Microsoft/vscode#20127]
- VSCode Version: 1.9.0
- OS Version: OSX Sierra

When I upgraded to 1.9.0, some logs stopped appearing on the debug console. I've noticed it seems to only happen with logs sent by logging libs (ex: morgan, winston). `console.log` and node errors are still shown.

Debugging as general seems ok.

**Context** nodejs debugging
 - my nodejs version: 7.2.1
 - launch.json has `node2` mode.

**Workarounds**
 - changing debug type to "node" instead of "node2" fixes it
 - sending the output to the integrated terminal, instead of the debug console (`console : "integratedTerminal"`) fixes it

**Comment by roblourens** [comment]
This is #19750. I don't have any other workarounds to add - trying to decide how to handle this.
