### ISSUE TITLE
Dropdown button style regressed

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#201232]
Terminal dropdown:

![image](https://github.com/microsoft/vscode/assets/2193314/02f03d34-8191-45d8-a36c-52502ed3d7a4)

This part is not meant to be there:

![image](https://github.com/microsoft/vscode/assets/2193314/d84e87ec-be3d-48d7-8b59-9cf6cd4d560e)

**Comment by hbons** [comment]
what theme is this?

**Comment by hbons** [comment]
Looks like a `padding-right: 4px` that should be a `margin-left: 4px`. Fixed it in the CSS dev tool but can't find the right file.

**Comment by Tyriar** [comment]
Happens in dark modern

**Comment by Tyriar** [comment]
I can see in insiders but not code - oss? I think this button is `DropdownWithPrimaryActionViewItem`

**Comment by hbons** [comment]
@Tyriar this doesn't seem to happen anymore. did you fix it?
<img width="166" alt="image" src="https://github.com/microsoft/vscode/assets/103326/f9f7a634-b20d-40f0-ba4b-a30f7b732371">

**Comment by Tyriar** [comment]
Seems fixed, at least on macOS where I verified just now 👌
