### ISSUE TITLE
Please allow users to decide whether to add the above setting code...

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#201286]
Hello! Starting from VSCode version 1.85, why is it mandatory to append the following code to settings.json? What is the purpose of doing this?
```
    "[csharp][css][go][go.mod][html][java][javascript][json][jsonc][markdown][python][rust][toml][typescript][xml][yaml]": {
        "editor.codeActionsOnSave": {
            "source.fixAll": "always",
            "source.organizeImports": "always",
            "source.sortImports": "explicit"
        }
    },
```
Moreover, different languages have different settings. . . Please allow users to decide whether to add the above setting code, rather than forcing users to add the above setting code. . . Thanks!

**Comment by justschen** [comment]
@zhouxinghong I'm not sure I understand what you mean by mandatory. In what scenario does this get appended (ie, what were your settings prior to this getting "appended" into the `settings.json` file`)?

**Comment by f1nn3g4n** [comment]
Hey @justschen I think my workplace is having the same issue. Since updating vscode each of our vscode's appends .vscode/settings.json with the following lines upon boot. Doesn't seem to be any of our extensions that are causing the problem.

`"[html][typescript]": {
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": "never"
    }
  }`

**Comment by justschen** [comment]
@f1nn3g4n I see - same question as above though! what are the existing settings prior to it being appended? Migration should only happen when `editor.codeActionsOnSave` already exists, so I'd like to identify if it's an issue with migration, the default setting, or something else.

**Comment by f1nn3g4n** [comment]
@justschen right, you mentioned that haha. Sorry I misread! We have these rules that seem to be combined kind of with this appended lines.

`"[typescript]": {
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": false
    }
  },
  "[html]": {
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": false
    }
  },`

**Comment by zhouxinghong** [comment]
> I'm not sure I understand what you mean by mandatory. In what scenario does this get appended (ie, what were your settings prior to this getting "appended" into the `settings.json` file`)?

When VSCode starts, it will force the above code to be appended to the end of settings.json.

**Comment by sandy081** [comment]
```
 "[typescript]": {
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": false
    }
  },

  "[html]": {
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": false
    }
  }
```

@justschen Can you please check why you are triggering migration in the above case?

**Comment by justschen** [comment]
`false` should be migrated to `never` in this case, since we shifted to supporting `always`, `explicit`, `never` instead of the booleans.

**Comment by sandy081** [comment]
@justschen Do you mean, following 

```
"[typescript]": {
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": false
    }
  },

  "[html]": {
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": false
    }
  },
```

is being migrated to 

```
"[typescript]": {
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": false
    }
  },

  "[html]": {
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": false
    }
  },

"[html][typescript]": {
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": 'never'
    }
  },
```

**Comment by justschen** [comment]
@sandy081 yes exactly!
