### ISSUE TITLE
VS Code 1.85.1 jumps into wrong file line from Search menu

### ISSUE THREAD

**Issue by MikrMikr** [microsoft/vscode#201275]
Type: <b>Bug</b>

Working with Cisco .cfg configuration export files.
The linux "file" command reports the file as: ASCII text, with CRLF, CR line terminators. 
VSCode reports the file as UTF-8 CRLF.
Notepad++ shows every line in a file ends with CRCRLF.
The issue goes away if I change the line endings with a command.

Steps to reproduce:

1. Get a file with CRCRLF line endings.
2. Search for string in Search menu
3. Click on Search results in any file
4. Code will jump into wrong line most of the time
5. After closing and opening that file in editor and cliking again will solve the problem for that file only

Looks the same as https://github.com/Microsoft/vscode/issues/32547

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19042

**Comment by MikrMikr** [comment]
relevant? -> https://github.com/microsoft/vscode/issues/127#issuecomment-159306903

**Comment by andreamah** [comment]
> relevant? -> https://github.com/microsoft/vscode/issues/127#issuecomment-159306903

Yes, it seems that, according to that comment, we don't support mixed line endings, at least for find/search. I would prefer that the find functionality support this before search does.
