### ISSUE TITLE
Code is misreporting activeEditorIsPinned

### ISSUE THREAD

**Issue by Acumane** [microsoft/vscode#201268]
Does this issue occur when all extensions are disabled? **YES**

- VS Code Version: `1.85.1` and `1.86.0-insiders`
- OS Version: Linux (`6.6.6-200.fc39.x86_64`)

Code regularly appears to misreport `activeEditorIsPinned`, the condition used to bind a key that toggles editor pinned state.

Steps to Reproduce:

1. Use `Developer: Inspect Context Keys` on a misbehaving pinned editor
2. `Developer Tools` > observe that `activeEditorIsPinned` disagrees with the state it's visibly in

**Comment by hitzhangjie** [comment]
This problem has been fixed recently. I am waiting the next update.

please see here: https://github.com/microsoft/vscode/issues/200305#issuecomment-1851846295
