### ISSUE TITLE
Cursor becomes invisible when clicking end of line

### ISSUE THREAD

**Issue by PolarPayne** [Microsoft/vscode#20120]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:21:13.228Z)
- OS Version: Linux x64 4.4.0-59-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|gc-excelviewer|GrapeCity|1.1.10|
|vscode-docker|PeterJausovec|0.0.11|
|elm-format|abadi199|0.1.0|
|clojure|avli|0.5.2|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.3|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.8|
|escaping-characters|drphrozen|1.0.0|
|text-transform|florianloch|0.1.0|
|code-sync|golf1052|2.1.1|
|rest-client|humao|0.12.1|
|vscode-clang|mitaki28|0.2.1|
|java|redhat|0.0.9|
|vscode-flow|rtorr|276.3.0|
|todotasks|sandy081|0.4.0|
|elm|sbrink|0.8.3|
|vscode-hexdump|slevesque|1.1.4|
|vim|vscodevim|0.5.2|
|jinja|wholroyd|0.0.7|

---

Conf:
block cursor

Steps to Reproduce:

1. Go to a tab where there is no active cursor
2. Click outside of text to the right (where there is no characters)
3. Cursor goes to the end of the line (as expected) but is not visible

Moving cursor to not end of line makes it visible again..

**Comment by shan-du** [comment]
I'm able to reproduce this
This starts to happen after latest update to **v1.9.0**

Extensions I have:

- Active File In Status Bar
- beautify
- ESLint
- Git History
- GitLens
- ReactJS code snippet

**Comment by PolarPayne** [comment]
1.9.1 fixed this for me (probably was duplicate of #20094).
