### ISSUE TITLE
Switching tabs when generating code with Copilot messes up file contents

### ISSUE THREAD

**Issue by Daniil0891** [microsoft/vscode#201249]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.85.1
- OS Version: Windows 10

Steps to Reproduce:

1. Press ctrl + i to open prompt window
2. Start generating code
3. Switch tabs while generating code

Generated code will end up in the file you opened, it will be mixed with the existing file content

**Comment by jrieken** [comment]
Optimistically closing this because we have revised how changes are cancelled and tracked
