### ISSUE TITLE
Feature Request: Option to Use Manual Path Input Bar for Opening Folders in Local Environment

### ISSUE THREAD

**Issue by tadteo** [microsoft/vscode#201279]
## Description:
In VSCode, when working remotely over SSH and opening a folder, there is a convenient and straightforward input bar at the top where the user can manually type the path to the desired directory. However, in a local environment, opening a folder defaults to using the native file dialog of the operating system. While this integration is appreciated for its OS-native experience, there are scenarios where a manual input bar, similar to the one used in remote sessions, could be more efficient and consistent, especially for users who frequently switch between local and remote development.

## Request:
I would like to request the addition of an option in VSCode that allows users to choose between the native file dialog and a manual path input bar for opening folders in a local development environment. This feature would be particularly useful for users who prefer the simplicity and keyboard-centric approach of typing the path directly, mirroring the experience in a remote SSH session.

## Use Case:
This feature would benefit users who:

- Prefer keyboard-centric navigation.
- Work in both local and remote environments and desire a consistent experience.
- Frequently access directories with long or complex paths that are easier to type or paste than navigate to via a GUI.

## Proposed Solution:
Introduce a setting in VSCode's preferences that allows users to select their preferred method of opening folders. This setting could offer two options:
- Use OS-native file dialog (current default behavior).
- Use manual path input bar (similar to the remote SSH session experience).

## Additional Context:
Having a consistent experience in both local and remote environments can streamline the workflow for developers who regularly switch contexts. The addition of this feature would enhance VSCode's flexibility and user-friendliness, especially for those who favor a more keyboard-driven approach.

**Comment by bpasero** [comment]
This can be enabled via `files.simpleDialog.enable` setting.
