### ISSUE TITLE
test files ending with mts don't change icon color

### ISSUE THREAD

**Issue by satanshiro** [microsoft/vscode#201245]
Does this issue occur when all extensions are disabled?: Yes/No
yes

- VS Code Version: 1.85.1 
- OS Version: macos catalina

Steps to Reproduce:

1. create a file named test.spec.ts notice the file color now change the file extension to mts (file type representing ems)
2. the color is not showing the file as a test file anymore

**Comment by aeschli** [comment]
What file icon theme are you using?

**Comment by satanshiro** [comment]
<img width="205" alt="image" src="https://github.com/microsoft/vscode/assets/38865738/8e7b9c89-0611-499d-894f-6bc04eab5083">
vs 
<img width="175" alt="image" src="https://github.com/microsoft/vscode/assets/38865738/f2ada7f9-395d-41e5-9157-9c4ec3a05b47">

**Comment by aeschli** [comment]
The Seti file icon theme is derived from https://github.com/jesseweed/seti-ui.

Please file an issue there, or, even better, create a PR.

Here is how the color was defined for spec.mjs: /blob/88bcd4a8fca14aa33dd9d50781ad8af3b03c6b90/styles/components/icons/mapping.less#L211
