### ISSUE TITLE
Add button to limit search to changed files

### ISSUE THREAD

**Issue by fanantoxa** [microsoft/vscode#201293]
Hey! I quite often when I have quite big code change (30+ files) I find myself missing some button so I can search only in files that have a change in it (the one I can see on source control panel).
So I remember name of the function/method or variable name, but can't remember where it exactly in which file. I can use regular search by all files, but then I find to many non related files because search term may be to vague. 

Currently we already have a button to limit search to opened editors 
![image](https://github.com/microsoft/vscode/assets/7717033/51d1b9a1-7906-4012-9d89-dfe112a44915)

Would be really awesome to have additional button here to limit search only to files that where changed (files mentioned in source control panel/tab both staged or not). 

Thank you! 🙂

**Comment by andreamah** [comment]
Targeting only a set of files is covered in this feature req: https://github.com/microsoft/vscode/issues/20530

/duplicate https://github.com/microsoft/vscode/issues/20530
