### ISSUE TITLE
Crtl+C, Ctrl+V on file doens't work anymore

### ISSUE THREAD

**Issue by allevo** [microsoft/vscode#201208]
Type: <b>Bug</b>

1. select a file in tree file view
2. press Ctrl+C
3. press Ctrl+V
The expected behaviour is the file is duplicated, but nothing happen

VS Code version: Code - Insiders 1.86.0-insider (Universal) (46a233646602c378c2168fa2a104dff8e8551558, 2023-12-11T05:37:31.663Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.77GB free)|
|Process Argv|--crash-reporter-id e3c16393-4fa9-4705-96e9-1affab8a4b1c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.2
vscode-wasm|dts|1.4.1
prettier-vscode|esb|10.1.0
copilot|Git|1.143.601
copilot-chat|Git|0.12.2023121801
vscode-github-actions|git|0.26.2
playwright|ms-|1.0.20
indent-rainbow|ode|8.3.1
prisma-insider|Pri|31.0.3145
rust-analyzer|rus|0.4.1773
crates|ser|0.6.5
vscode-standard|sta|2.1.3
vscode-mdx|uni|1.6.0
volar|Vue|1.8.25
grammarly|znc|0.25.0

</details>

**Comment by bpasero** [comment]
I think this was fixed in more recent insider versions.

**Comment by allevo** [comment]
Hi @bpasero. Yes it is. I'm closing this.
Thanks for your help.
