### ISSUE TITLE
generate file 'logback.log' automatically

### ISSUE THREAD

**Issue by yangjuexi-ones** [microsoft/vscode#201278]
Type: <b>Bug</b>

1. just open any git repo
2. a file named 'logback.log' will be created automatically

I do not change any config of vscode or extension, except upgrade vscode and some extensions.I firstlt thought it may be some java extensions did that, but it continue after i uninstall all java extensions

VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 66ed805b-18ab-405c-9152-8c330a1ab0ae|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-base64|ada|0.1.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.21.0
markdown-preview-github-styles|bie|2.0.3
markdown-yaml-preamble|bie|0.1.0
vscode-markdownlint|Dav|0.53.0
githistory|don|0.6.20
gitlens|eam|14.6.1
shell-format|fox|7.2.5
html-preview-vscode|geo|0.2.5
copilot|Git|1.143.601
copilot-chat|Git|0.11.1
go|gol|0.40.0
vscode-graphql|Gra|0.8.20
vscode-graphql-execution|Gra|0.2.4
vscode-graphql-syntax|Gra|1.2.2
todo-tree|Gru|0.0.226
rest-client|hum|0.25.1
output-colorizer|IBM|0.1.2
vscode-gutter-preview|kis|0.30.0
fluent-icons|mig|0.0.18
vscode-docker|ms-|1.28.0
vscode-postgresql|ms-|0.3.0
black-formatter|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
cpptools|ms-|1.18.5
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
sqltools|mtx|0.28.1
sqltools-driver-mysql|mtx|0.6.0
sqltools-driver-pg|mtx|0.5.2
gradle-language|nac|0.2.3
vscode-groovy-lint|Nic|3.1.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.32.0
vscode-commons|red|0.0.6
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
shellman|Rem|5.7.0
jenkinsfile-support|sec|0.1.0
sonarlint-vscode|Son|4.1.0
lua|sum|3.7.3
pdf|tom|1.2.2
errorlens|use|3.16.0
vscode-concourse|vmw|1.51.0
vscode-manifest-yaml|vmw|1.51.0
vscode-icons|vsc|12.6.0
vscode-nginx|wil|0.7.2
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.5.1

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by lszomoru** [comment]
@yangjuexi-ones, there is no reference of such file in the VS Code codebase so this must be created either by an extension, or a git hook that is specific to your git repository that you have opened.  

Please use the "Help: Troubleshoot Issue..." command from the command palette to try to narrow down the root cause of the issue. Thanks!

**Comment by thackervishal** [comment]
@yangjuexi-ones I had the same issue, it looks like for me its the extension `Groovy Lint, Format and Fix` thats doing this .... I have it disabled for now and the issue is resolved for me. I'm hoping the extension gets patched soon (dont wanna have to gitignore the `logback.log` file in all my repos)

**Comment by yangjuexi-ones** [comment]
> @yangjuexi-ones I had the same issue, it looks like for me its the extension `Groovy Lint, Format and Fix` thats doing this .... I have it disabled for now and the issue is resolved for me. I'm hoping the extension gets patched soon (dont wanna have to gitignore the `logback.log` file in all my repos)

Thanks !!! It works.
After uninstall `Groovy Lint, Format and Fix` ,  the file no longer been created any more.

**Comment by yangjuexi-ones** [comment]
> @yangjuexi-ones, there is no reference of such file in the VS Code codebase so this must be created either by an extension, or a git hook that is specific to your git repository that you have opened.
> 
> Please use the "Help: Troubleshoot Issue..." command from the command palette to try to narrow down the root cause of the issue. Thanks!

Thanks . I have identified that  the problem was caused by extension `Groovy Lint, Format and Fix` according the command you tell me. And , the process tell me the problem was caused by extension `Groovy Lint, Format and Fix`. After that, I tried to disable/ uninstall the extension, and no more `logback.log` created.

**Comment by yangjuexi-ones** [comment]
I have created a issue at https://github.com/nvuillam/vscode-groovy-lint/issues/200, anyone wants more process can view this issue.
