### ISSUE TITLE
TS Server crashes when trying to use my own node installation.

### ISSUE THREAD

**Issue by slayn777** [microsoft/vscode#201211]
Type: <b>Bug</b>

I set this in my workspace settings:
  "typescript.tsserver.maxTsServerMemory": 8192,
  "typescript.tsserver.nodePath": "node",

On one of my machines, this works fine. And another, I get a message saying the ts server has crashed 5 times immediately and won't be started.

In output I see this 5 times:
[error] TSServer exited. Code: 1. Signal: null

No logs are generated. I enabled verbose logging but all the log folders are empty. Seems like it crashes before any logs other than the above error can be written.

If I revert my settings back to the included node of vs code, it is fine, but then I can't increase maxTsServerMemory above 4GB so I'm unable to work effectively. Our repo is too large and needs more than 4GB which is why I'm trying to use my own node installation. But VS code is giving me no clue what is wrong with my node installation.

I can confirm that my installation of node is otherwise fine, as I use it to run our app locally. And I did try uninstalling/re-installing node locally to see if that would fix my problem. I am using node v14.21.3 on both machines (the working one and the broken one)

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.80GB (51.13GB free)|
|Process Argv|--crash-reporter-id d7d0dbc2-4cac-4d5e-9372-7c21a115a97e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.2
prettier-vscode|esb|10.1.0
vscode-yarn|gam|2.1.0
copilot|Git|1.143.0
copilot-chat|Git|0.11.1
vscode-scss|mrm|0.10.0
vscode-bicep|ms-|0.24.24
vscode-dotnet-runtime|ms-|2.0.0
vscode-typescript-next|ms-|5.4.20231218
vscode-jest|Ort|5.2.3
code-spell-checker|str|3.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
962ge761:30917236
f8hc8238:30694864
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t:30925682

```

</details>

**Comment by mjbvz** [comment]
What's the output of running `node -e "console.log(process.execPath)"` on the effected machine? Does it point to the correct directory?

**Comment by slayn777** [comment]
@mjbvz 
PS C:\Users\erjohn> node -e "console.log(process.execPath)"
C:\Program Files\nodejs\node.exe
PS C:\Users\erjohn> & "C:\Program Files\nodejs\node.exe" -v
v14.21.3

Above looks healthy to me

**Comment by mjbvz** [comment]
Have you tried using a newer node version? Also does it work if you give it the exact path to instal instead of using `node`?

**Comment by slayn777** [comment]
I just tested node v16.20.2
I tested this setting: `"typescript.tsserver.nodePath": "C:\\Program Files\\nodejs\\node.exe"`

both gave me the same crash

Is there any way to get vs code to tell me more than this?
> The JS/TS language service immediately crashed 5 times. The service will not be restarted.

This is the complete output I see. If I try to open any of the log files in the output, they do not exist

2023-12-19 16:19:31.187 [info] Starting TS Server undefined
2023-12-19 16:19:31.187 [info] Using tsserver from: c:\Users\erjohn\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js undefined
2023-12-19 16:19:31.187 [info] Using Node installation from C:\Program Files\nodejs\node.exe to run TS Server undefined
2023-12-19 16:19:31.187 [info] <syntax> Log file: c:\Users\erjohn\AppData\Roaming\Code\logs\20231219T092830\window1\exthost\vscode.typescript-language-features\tsserver-log-4RhZex\tsserver.log
2023-12-19 16:19:31.187 [info] <syntax> Forking...
2023-12-19 16:19:31.187 [info] <syntax> Starting...
2023-12-19 16:19:31.187 [info] <semantic> Log file: c:\Users\erjohn\AppData\Roaming\Code\logs\20231219T092830\window1\exthost\vscode.typescript-language-features\tsserver-log-yCm44C\tsserver.log
2023-12-19 16:19:31.188 [info] <semantic> Forking...
2023-12-19 16:19:31.188 [info] <semantic> Starting...
2023-12-19 16:19:31.219 [error] TSServer exited. Code: 1. Signal: null
2023-12-19 16:19:31.219 [info] TSServer log file: c:\Users\erjohn\AppData\Roaming\Code\logs\20231219T092830\window1\exthost\vscode.typescript-language-features\tsserver-log-yCm44C\tsserver.log undefined

**Comment by slayn777** [comment]
@mjbvz  more I've now tried many permutations of different versions of vs code, different versions of node, using nvm-windows, using standalone node, installing into different locations, nothing has worked.

I also noticed for my machine that is 'working' this line is missing from the log:
[info] Using Node installation from ...
So I don't actually feel confident that the machine that is 'working' is actually using the setting. It's on vs code 1.85.1 and the setting looks valid (the setting is bright, not faded like other unrecognized settings) but nothing in the logs confirms that my installation of node is actually being used on this machine. So I'm more inclined to believe that the setting is broken on both machines but in different ways.

**Comment by lvanhala** [comment]
I have the same problem. Using nvm.

**Comment by ronakj** [comment]
The problem is due to spawn being used here https://github.com/microsoft/vscode/blob/f88bce8fe6a6d2ccd27cbd64bb26853cd8779afa/extensions/typescript-language-features/src/tsServer/serverProcess.electron.ts#L281C4-L286C8

This is a simple repro using same arguments as what's used by VSCode -
```js
const { spawn } = require('child_process');

const nodeExe = 'C:\\Program Files\\nodejs\\node.exe';
const args = [
	'--max-old-space-size=8916',
	'd:\\vscode\\extensions\\node_modules\\typescript\\lib\\tsserver.js',
	'--serverMode',
	'partialSemantic',
	'--useInferredProjectPerProjectRoot',
	'--disableAutomaticTypingAcquisition',
	'--cancellationPipeName',
	'C:\\Users\\RONAKJ~1\\AppData\\Local\\Temp\\vscode-typescript\\9b7e3c03610bfac6c256\\tscancellation-35109630df997a093dd3.tmp*',
	'--locale',
	'en',
	'--noGetErrOnBackgroundUpdate',
	'--validateDefaultNpmLocation'
];

const child = spawn(nodeExe, args, {
	shell: true,
	windowsHide: true,
	cwd: undefined,
});

child.stdout.on('data', (data) => {
	console.log(`stdout: ${data}`);
});

child.stderr.on('data', (data) => {
	console.error(`stderr: ${data}`);
});

child.on('close', (code) => {
	console.log(`child process exited with code ${code}`);
});

```

Executing this on my local machine I get 
```
PS E:\> node tsserver.js
stderr: 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

child process exited with code 1
```

The way to solve this would be to put node executable path in quotes for windows.

**Comment by ronakj** [comment]
@mjbvz Please check the PR #201966

**Comment by mjbvz** [comment]
Thanks @ronakj!

**Comment by mjbvz** [comment]
To verify:

- Create an instance of a node install at a location that includes spaces in the path: `/users/spacey space/node`. (you can copy the file/link from `which node` to this location)
- Try using this path in the `typescript.tsserver.nodePath` setting
- Restart VS code
- Open a JS/TS file and confirm it does not crash

**Comment by Anoninz** [comment]
I met this problem on my m1 max mac too
actually containing the path in quotes is the way to solve the problem
like: 
TypeScript > Tsserver: Node Path:  `"/Users/anoninz/.nvm/versions/node/v20.11.0/bin/node"`

finally I can use more memory to run my project happily

**Comment by digitalmaster** [comment]
> I met this problem on my m1 max mac too actually containing the path in quotes is the way to solve the problem like: TypeScript > Tsserver: Node Path: `"/Users/anoninz/.nvm/versions/node/v20.11.0/bin/node"`
> 
> finally I can use more memory to run my project happily

This did the trick for me. Less then ideal tho since mean's i'll have to change this anything i change node versions (or change machines/folders).

**Comment by nagyen** [comment]
@digitalmaster I think you can just use `"node"` to let vscode use the node version from your workspace. I didn't get any errors after doing this. 

ref: https://github.com/microsoft/vscode/blob/dc9701399307b9e4919116c82dd30eda86deccc2/extensions/typescript-language-features/src/configuration/configuration.electron.ts#L80-L88
