### ISSUE TITLE
Terminal: Better highlighting support when using line cursor

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#20126]
When using `"terminal.integrated.cursorStyle": "line"` the last letter doesn't get highlighted.

Here are some comparisons of what it looks like in code and conemu

Code
![blinking2](https://cloud.githubusercontent.com/assets/6662208/22696878/4a289d1e-ed15-11e6-9ab6-5d73d42542ab.gif)

Conemu
![blinking1](https://cloud.githubusercontent.com/assets/6662208/22696884/504ad43c-ed15-11e6-93dd-9c049ebec71d.gif)

- VSCode Version: 1.10.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Set `"terminal.integrated.cursorStyle": "line"` 
2. Open terminal
3. Type some text and then highlight it.

cc: @Tyriar

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/529

**Comment by Tyriar** [comment]
I'm not sure there's a way to fix this, closing
