### ISSUE TITLE
Disable ctrl + w from closing a terminal

### ISSUE THREAD

**Issue by Wizzzo** [microsoft/vscode#201207]
After adding the feature for moving the terminal window to the code editor tab ( a great improvement!).
there is a problem now that when I try to use ctrl + w to delete a word in the terminal as always, I accidentaly close the terminal window.
because the ctrl + w should close tabs in the editor.
need an option to disable it the terminal tabs.

**Comment by Tyriar** [comment]
You can disable the keybinding with this:

```
{ "key": "ctrl+w",                "command": "-workbench.action.terminal.killEditor",
                                     "when": "terminalEditorFocus && terminalFocus && terminalHasBeenCreated || terminalEditorFocus && terminalFocus && terminalProcessSupported" },
```
