### ISSUE TITLE
VSCode 1.9.0 Not Responding on the Windows 10

### ISSUE THREAD

**Issue by sdey0081** [Microsoft/vscode#20125]
- VSCode Version: 1.9.0
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Once upgraded to 1.9.0, it it is not responding when I am using its own terminal.
2.

**Comment by Tyriar** [comment]
What did you do before it became unresponsive? You mentioned the terminal?

**Comment by sdey0081** [comment]
yes

**Comment by digitalcoyote** [comment]
I believe I am also experiencing this issue. Specifically, When using the terminal to run Gulp scripts that may need to run in excess of 30s, I get a notification that the window is not responding and asking me to reopen or wait. Wait never resolves the issue after this, reopening leaves me with a blank screen. Let me know what else I can provide.

**Comment by Tyriar** [comment]
Closing off since there isn't enough information to repro
