### ISSUE TITLE
Voice: support prompts, like `@workSpace` or `/explain`

### ISSUE THREAD

**Issue by dbsxdbsx** [microsoft/vscode#201220]
Currently, with the latest Vscode v 1.85.0, it is glad to see using voice only(Vscode Speech extension) is ok to collaborate with Copilot chat within the chat View Ui. But the speech extension can't handle well with the tag like `@workspace`. For example, if said with speech "what is the whole project for", it would answer  something like "I am just an AI aasistant, I can't get access ....", but It does feed back proper answer if with prompt `@workSpace` or just with "ctrl+enter" which is a feature added within v.1.85.0.

I know this feature is a little complicated, since within just raw speech, how to handle target prompt is complex with raw NLP.  But still I think it a killer feature for any AI programming tool.  For this, what I come up is that Copilot can ask  an anti-question before answering if Copilot is at a loss --- let it ask user first, like "what context you refer to",  follwing several valid choices like `#file`,`@workspace`, `auto`... to choose.

**Comment by bpasero** [comment]
In places where voice is used for Copilot chat, phrases such as "at workspace", "slash fix" will now get replaced to `@workspace` and `/fix`.
