### ISSUE TITLE
[decorators] Unicode characters are no longer rendered properly

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#20137]
- VSCode Version: `1.10.0-insider` 87fd1dde6d2d2b0d84c3fe56fabc174e888b0024
- OS Version: macOS Sierra `10.12.3 (16D32)`

This just started in this nightly, here is what I see now:

![image](https://cloud.githubusercontent.com/assets/641685/22702819/fa57b520-ed2f-11e6-90eb-f49f41e30299.png)

This is what I saw prior to today's nightly:

![image](https://cloud.githubusercontent.com/assets/641685/22702862/261e342c-ed30-11e6-9bf4-1f42ccf0cf62.png)

**Comment by eamodio** [comment]
Here is the offending commit: https://github.com/Microsoft/vscode/commit/c07bf9de7abda95a7da6e93f350e1f81d8954f33

It is because unicode in the contentText is in the form of `\000000` and this causes it to become `\\000000`. See http://stackoverflow.com/a/10393517/98284

**Comment by aeschli** [comment]
This works for me
```javascript
        before: {
            contentText: "\u2661",
            color: "rgba(255,255,255,0.5)",
        }
```

![image](https://cloud.githubusercontent.com/assets/6461412/23130837/3ab91a70-f788-11e6-9244-1594050d874b.png)
