### ISSUE TITLE
When debugging Python code, you can display the shape or size of tensors, matrices, lists, etc

### ISSUE THREAD

**Issue by Hainuo-Wang** [microsoft/vscode#201358]
Deep learning debugging is more concerned with shape or size. It would be more useful if the shape or size of tensors or matrices could be displayed first during debugging, as is the case with pycharm.

In vscode: 
![image](https://github.com/microsoft/vscode/assets/88794833/87d3d9b0-101b-4992-b42d-8b3a6d0f68c9)

In pycharm:
![image](https://github.com/microsoft/vscode/assets/88794833/c7dd24d7-962a-49bc-9bea-d6c508123a97)

**Comment by roblourens** [comment]
This is an issue for debugpy or the Python extension
