### ISSUE TITLE
Refresh the vscode UI/UX & icons

### ISSUE THREAD

**Issue by FlissKarim** [microsoft/vscode#201399]
Hello, i'm using vscode for personal and professional purposes, what make vscode a bit old is its old UI, please take inspiration from Fleet IDE its awsome, XCode of Apple too.
i think its the moment to refresh vscode if you won't people leave it and use Fleet IDE for exemple.
Thanks for your work :)

**Comment by hbons** [comment]
Thanks for your feedback. We're continuously updating the default themes and considering what it is to look "modern". Closing this for now though as it's not an actionable issue.
