### ISSUE TITLE
`typescript.experimental.aiCodeActions` actions are not marked with `isAI`

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#201313]
Code actions provided by Copilot are marked with a sparkle because they are marked as `isAI` code actions using the `codeActionAI` API proposal. We could also mark the TypeScript experimental AI code actions as `isAI`. 

![Screenshot 2023-12-20 at 16 31 18](https://github.com/microsoft/vscode/assets/61460952/13da03e6-cf24-42f5-9727-82683a399b81)

**Comment by mjbvz** [comment]
I believe this was addressed in #201140
