### ISSUE TITLE
Change focus to terminal panes via number keyboard shortcut

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode#20133]
- VSCode Version: 1.9.0
- OS Version: OSX 10.11

Steps to Reproduce:

1. Open the terminal, create a few panes
2. Try to focus a particular one with a keyboard shortcut.  I see there is `workbench.action.terminal.focusNext` but nothing to directly access a pane by number even though the dropdown contains numbers.

**Comment by bpasero** [comment]
@Tyriar should we maybe align the command ids with the already existing ones for opening an editor at a specific index? Their command ids look like this: `workbench.action.openEditorAtIndex6`

**Comment by Tyriar** [comment]
@bpasero :+1: I'll change it tomorrow
