### ISSUE TITLE
Show Symbols on the right side

### ISSUE THREAD

**Issue by bowencool** [microsoft/vscode#201398]
Currently: 
![breadcrumb-symbol-dropdown](https://code.visualstudio.com/assets/docs/editor/editingevolved/breadcrumb-symbol-dropdown.png)

Expect to be like GitHub:
<img width="1692" alt="图片" src="https://github.com/microsoft/vscode/assets/20217146/e6ccdbe8-82e3-4459-af15-ab3e9531897c">

**Comment by gjsjohnmurray** [comment]
Have you seen the Outline view? One way to find it is to run `Explorer: Focus on Outline View` in the Command Palette. The default location of this view is in the Explorer container in the Primary Side Bar, but as with most views you can drag it to the Secondary Side Bar, whose default position is on the right-hand side of the window.

**Comment by bowencool** [comment]
> Have you seen the Outline view? One way to find it is to run `Explorer: Focus on Outline View` in the Command Palette. The default location of this view is in the Explorer container in the Primary Side Bar, but as with most views you can drag it to the Secondary Side Bar, whose default position is on the right-hand side of the window.

Thanks
