### ISSUE TITLE
The drive or unc share you selected doesn`t exist or not accessible

### ISSUE THREAD

**Issue by Yousefms1** [microsoft/vscode#201377]
When I deleted visual studio code then I wanted to reinstall it this message appeared "The drive or unc share you selected doesn`t exist or not accessible " 

I don`t know what to do now >>.
please help..

and know that I tried to uninstall the the programme from windows but I didn`t find it
```[tasklist]
### Tasks
```

**Comment by joaomoreno** [comment]
Workaround: https://github.com/microsoft/vscode/issues/147041#issue-1196621444
