### ISSUE TITLE
[Feature Request] Format option to not insert space between non-empty curly braces in TS/JS

### ISSUE THREAD

**Issue by abgivant** [Microsoft/vscode#20130]
- VSCode Version: 1.9
- OS Version: Windows 8.1

Would it be possible to add a formatting option to not automatically insert a space between non-empty curly braces in JS and TS?

**Example:**
```javascript
var prop = 1;
var obj = {prop};
```
Will get formatted as:
```javascript
var prop = 1;
var obj = { prop };  
```

It does appear that the space will not be inserted for empty braces (`var obj = {};`). That's what I expect, but that should probably be an option too.

Thanks!

**Comment by mjbvz** [comment]
I agree this is option is worth adding. TypeScript already supports for this formatting option, but it is currently not exposed to us. We're tracking that work here: https://github.com/Microsoft/TypeScript/issues/13275

Closing as upstream
