### ISSUE TITLE
Default Open/Save Location doesn't work for clone repository destinations

### ISSUE THREAD

**Issue by leighmcculloch** [microsoft/vscode#201341]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
   ```
   Version: 1.85.1 (Universal)
   Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
   Date: 2023-12-13T09:48:06.308Z
   Electron: 25.9.7
   ElectronBuildId: 25551756
   Chromium: 114.0.5735.289
   Node.js: 18.15.0
   V8: 11.4.183.29-electron.0
   OS: Darwin arm64 23.1.0
   ```
- OS Version:
   ```
   macOS 14.1.1 (23B81)
   ```

Steps to Reproduce:

1. Install VSCode and Git.
2. Configure `files.dialog.defaultPath` with a path like `/Users/leighmcculloch/Code`.
3. Use the `Git: Clone` command to clone a repo from GitHub.
4. A box will open to the users home directory (`/Users/leighmcculloch`), not the configured default path (`/Users/leighmcculloch/Code`):
   <img width="1149" alt="Screenshot 2023-12-21 at 11 12 28 AM" src="https://github.com/microsoft/vscode/assets/351529/0cafef91-7107-42ff-9221-c10873edf81f">

The `files.dialog.defaultPath` config was added in https://github.com/microsoft/vscode/pull/182908, in response to https://github.com/microsoft/vscode/issues/115730, but doesn't appear to affect the location dialog for where to clone new repositories.

**Comment by lszomoru** [comment]
The git extension maintains its own setting for the default clone location - `git.defaultCloneDirectory`.
