### ISSUE TITLE
Command center window title with newline

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#201340]
- Open the multi-diff editor from the Timeline view
- See a messed up window title, I think due to the editor title having a newline in it

<img width="700" alt="image" src="https://github.com/microsoft/vscode/assets/323878/a27da2c5-d1af-4ac7-a065-718d97d1298a">

**Comment by hediet** [comment]
For me, it justs contains the workspace name:

![Image](https://github.com/microsoft/vscode/assets/2931520/30b24805-dace-4706-ba28-48779ac97c84)

However, I do think this title has multiple lines (commit.message):
https://github.com/microsoft/vscode/blob/93a6a2a12574e98ecaf5a47e991a8c0db660462a/extensions/git/src/commands.ts#L3636

**Comment by roblourens** [comment]
I have `"window.title": "${dirty} ${activeEditorShort}${separator}${rootName}"` if that matters

**Comment by jrieken** [comment]
repro steps

* have a commit which message uses new lines
* configure `"window.title": "${dirty} ${activeEditorShort}${separator}${rootName}"` and `"multiDiffEditor.experimental.enabled": true`
* open the multi diff editor for a file in said commit
* the command center looks bad
