### ISSUE TITLE
[Feature Request] To support IntelliSense when implementing interface or abstract class

### ISSUE THREAD

**Issue by BirdLeeSCUT** [Microsoft/vscode#20134]
- VSCode Version: 1.9.0
- OS Version: Windows 10
- Languege: TypeScript 2.1.5

At present vsCode do not provide IntelliSense when implementing interface or abstract class, as below:

![image](https://cloud.githubusercontent.com/assets/10753131/22701038/7a105a1c-ed97-11e6-8a13-26855ff3a7f1.png)

![image](https://cloud.githubusercontent.com/assets/10753131/22700707/7dc94656-ed96-11e6-8203-e79a606e7427.png)

If vsCode can provide IntelliSense in these cases, it will be so convinient.

**Comment by mjbvz** [comment]
Thanks. We're tracking this on the TypeScript side https://github.com/Microsoft/TypeScript/issues/7158 . Once they implement this, VSCode should pick up the functionality automatically
