### ISSUE TITLE
Source control not working properly

### ISSUE THREAD

**Issue by eeshitashri** [microsoft/vscode#201360]
Type: <b>Bug</b>

1. I click on + icon to stage changes on a file, I think the file gets staged but the source control left menu doesn't show it. It updates when I close and open the application.
2. I cannot find the commit option
3. If I git commit through console, the source control left menu doesn't update.
4. source control dropdown menu from which we stash and commit is also not there.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (8.07GB free)|
|Process Argv|--crash-reporter-id 3a22e858-57e3-4a64-a323-30c674c416de|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.2
gitlens|eam|14.6.1
prettier-vscode|esb|10.1.0
java|red|1.25.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.43.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30917236
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pythonregdiag2cf:30926736
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184t:30925682

```

</details>

**Comment by TrevorDMartin** [comment]
Currently running into the same issue.

Running on Apple M1 Pro.

Reverting 1.84.2 fixes the issue.

**Comment by lszomoru** [comment]
@eeshitashri, @TrevorDMartin, could you please try the latest VS Code Insiders release? Thanks!

**Comment by eeshitashri** [comment]
All the issues I had listed above seem to be working okay.

**Comment by lszomoru** [comment]
Thanks for the update. Closing the issue.

**Comment by eleanorjboyd** [comment]
verified working by user @eeshitashri
