### ISSUE TITLE
Command palette search relevance

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode#20138]
(vscode 1.9.0) 

 "Disable All Extensions" should not be the first that's shown when I am trying to install extensions. And the result I want probably shouldn't be 5 items far as well.

![image](https://cloud.githubusercontent.com/assets/159209/22703627/b1202c04-ed19-11e6-9a71-12817035f4da.png)

Please close if duplicate but I think this particular case highlights the issue very well.

**Comment by Tyriar** [comment]
While it may not feel ideal, changing the ordering would probably make things work so this is as designed imo.

**Comment by bpasero** [comment]
I recently changed the relevance scoring via https://github.com/Microsoft/vscode/issues/14727:

![image](https://cloud.githubusercontent.com/assets/900690/22730279/a68a003a-ede6-11e6-8211-07e815999a1a.png)
