### ISSUE TITLE
[Feature Request] Preview images saved in a GitHub private repo in a JSDoc comment

### ISSUE THREAD

**Issue by Fullchee** [microsoft/vscode#201375]
The preview of the image works for publically available images
- https://github.com/microsoft/vscode/issues/55484

So if I had a JSDoc comment,
```
/**
 * `![image](https://user-images.githubusercontent.com/12345678/123456789-12345678-1234-1234-1234-123456789012.png)`
 */
const myFn = () => {}
```

and I hovered over `myFn`, I would see the image in the preview

However, now when you upload an image into a GitHub private repo's PR, issue or comment, it can only be accessed if you have permission.

I would be nice to be able to view private images in a JSDoc comment.

---

I'd love to know if anyone has workarounds!

One workaround I can think of is to paste the image on a public repo

**Comment by joyceerhl** [comment]
> it can only be accessed if you have permission

This is due to how GitHub hosts images--they "belong to" that private repository rather than just being globally accessible user data. I don't think this is something that we would address in VS Code, thus closing as out of scope.
