### ISSUE TITLE
Support to update breakpoint status asynchronously

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2013]
With the current breakpoint API it is only possible to return errors as part of the SetBreakpointsRequest, and there is no way to update that error message or clear it later on. Other debug adapters allow to set breakpoints before they know if they are valid and then want to update the UI as modules load and it can be determined if they have really bound or not.

The current thinking is that we will introduce a breakpoint ID and a `BreakpointsUpdatedEvent`.

CC @gregg-miskelly @isidorn

**Comment by vadimcn** [comment]
Please consider also supporting "unsolicited" breakpoint notifications.  It would be nice if breakpoints created via debugger's REPL interface could be displayed in the UI and be preserved across debugging sessions.  (Note that this might require round-tripping a custom data chunk to account for advanced breakpoint attributes which VSCode does not know about.)

**Comment by weinand** [comment]
I've added the following protocol support: a new `BreakpointEvent` and an attribute `id` for the `Breakpoint` type. A debug adapter that wants to send out `BreakpointEvent` is expected to set the `id` of the `Breakpoint` returned from the `setBreakpoints` or `setFunctionBreakpoints` requests so that subsequent events with the same id can be mapped to the corresponding breakpoints.

@isidorn please implement this in the front end.

**Comment by weinand** [comment]
@gregg-miskelly VS Code now listens on breakpoint events with reason `update` and updates the verification state and location.
