### ISSUE TITLE
error FS0010: Unexpected character '' in interaction

### ISSUE THREAD

**Issue by aliozgur** [Microsoft/vscode#20139]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Ionide-FAKE|Ionide|1.2.3|
|Ionide-Paket|Ionide|1.6.1|
|Ionide-fsharp|Ionide|2.22.1|
|swift|Kasik96|0.0.2|
|bower|donjayamanne|0.0.3|
|mssql|ms-mssql|0.2.1|
|cpptools|ms-vscode|0.10.0|
|csharp|ms-vscode|1.6.2|

---

Steps to Reproduce:
1. Create a new fsx file
2. type ```let test = 42``` and hit Alt+. (Send Line)

**Comment by aliozgur** [comment]
<img width="954" alt="capturfiles-20170207_084205" src="https://cloud.githubusercontent.com/assets/799194/22703785/690dfa56-ed76-11e6-80c3-75b51f336a88.png">

**Comment by aliozgur** [comment]
This is what happens when I open new bash in integrated terminal and then type ```fsharpi```. Please note the *mono-sgen32* terminals dropdown

<img width="960" alt="capturfiles-20170207_084236" src="https://cloud.githubusercontent.com/assets/799194/22703792/720e8904-ed76-11e6-8dfb-38b85e841ab1.png">

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19766
