### ISSUE TITLE
Editor border theme keys are complaining about requiring transparency

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#201304]
This might be my design, but I would think that a border color would never set transparency required as it would be too difficult to differentiate colors when stacked upon each other on a 1px wide line

![image](https://github.com/microsoft/vscode/assets/2193314/f4a36256-256f-4f28-85e3-f57636eb01db)

The `, true` at the end causes this:

https://github.com/microsoft/vscode/blob/b21537c2ef9307850c21bef5eb10e037b8d06424/src/vs/editor/common/core/editorColorRegistry.ts#L17-L19

**Comment by hediet** [comment]
I'm open for a PR here. Unfortunately, I don't have any context on why there `true` argument is there.
Are the values in our themes for this color transparent?

**Comment by Tyriar** [comment]
It seems reasonable to assume borders are find to be opaque as they're so narrow. Alex might have context but I'm guessing it was a copy paste issue.
