### ISSUE TITLE
Allow to copy/paste file between windows

### ISSUE THREAD

**Issue by ajmas** [Microsoft/vscode#20135]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.3.0

I just tried copy/pasting and dragging a file between two vscode trees and found it would not copy. On the other hand, revealing that file in the Finder and then dragging it into the other window allowed me to achieve the copy. 

It would be nice if was possible to do all of this without needing to go through the Finder.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/164
