### ISSUE TITLE
CSP on Web breaks "Install Extension from Location..." Command

### ISSUE THREAD

**Issue by AdamRaichu** [microsoft/vscode#201317]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: web (insiders.vscode.dev)
- OS Version: Google Chrome

Steps to Reproduce:

1. Open a repository in vscode web insiders. (I was using https://insiders.vscode.dev/github/AdamRaichu/vscode-docx-viewer)
2. Open the command palette (Ctrl+Shift+P).
3. Type "Install Extension from Location", and run that command.
4. Paste in a URL that is the root of an extension hosted online. (I was using https://raw.githubusercontent.com/AdamRaichu/vscode-zip-viewer/main/)
5. No error or failure message is visible to the user, but the console has the following messages.

```log
Refused to connect to 'https://raw.githubusercontent.com/AdamRaichu/vscode-zip-viewer/main/package.json' because it violates the following Content Security Policy directive: "connect-src 'self' https://main.vscode-cdn.net https://vscodeweb.azureedge.net http://localhost:* https://localhost:* https://api.github.com/ https://update.code.visualstudio.com/api/ https://*.vscode-unpkg.net/ https://default.exp-tas.com/vscode/ab https://vscode-sync.trafficmanager.net/ https://vscode-sync-insiders.trafficmanager.net/ https://*.gallerycdn.vsassets.io https://vortex.data.microsoft.com/collect/v1 https://marketplace.visualstudio.com/_apis/public/gallery/ https://vslsdev.blob.core.windows.net/webextension/ https://vslsppe.blob.core.windows.net/webextension/ https://vscodedotdev.blob.core.windows.net/web-builds/ https://az764295.vo.msecnd.net/experiments/vscode-experiments.json https://vscodeexperiments.azureedge.net/experiments/vscode-experiments.json https://code.visualstudio.com/raw/ https://vscode-auth.github.com https://*.gallery.vsassets.io/_apis/public/gallery/ https://marketplace.visualstudio.com/items/ https://az764295.vo.msecnd.net/extensions/marketplace.json https://az764295.vo.msecnd.net/extensions/workspaceRecommendations.json.gz https://az764295.vo.msecnd.net/profile-templates/ https://mobile.events.data.microsoft.com/ https://auth.vscode.dev https://auth.insiders.vscode.dev https://*.rel.tunnels.api.visualstudio.com wss://*.rel.tunnels.api.visualstudio.com https://vscodeedu.com https://ppe.vscodeedu.com https://management.azure.com https://*.instances.azureml.ms:* wss://*.instances.azureml.ms:* https://api-dogfood.resources.windows-int.net/ https://login.windows-ppe.net/".

Refused to connect to 'https://raw.githubusercontent.com/AdamRaichu/vscode-zip-viewer/main/package.json' because it violates the document's Content Security Policy.

Error while fetching manifest from https://raw.githubusercontent.com/AdamRaichu/vscode-zip-viewer/main/ Failed to fetch

Uncaught (in promise) Error: Cannot find packageJSON from the location https://raw.githubusercontent.com/AdamRaichu/vscode-zip-viewer/main/
    at n.install (workbench.web.main.js:2693:3248)
install @ workbench.web.main.js:2693
```

I'm opening this issue because the idea of having a CSP and installing an extension from the web are contradictory. Consider these two questions: Why have a command that allows for installing from the web if no user-controlled urls are allowed? And if you want such a command to work, why have a CSP in the first place?

Either the CSP should be changed in order to allow this command to function, or it should be removed from the web version. I personally would advocate for keeping this command as it is useful for testing web extensions, but I can understand why the CSP is in place.

**Comment by sandy081** [comment]
@AdamRaichu You cannot add any location to install an extension from location. Purpose of this command to side load your extension in web to test before publishing. Please check this doc - https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-vscode.dev

**Comment by AdamRaichu** [comment]
Ah, thank you. I had never found that page before.
