### ISSUE TITLE
Codespace not loading

### ISSUE THREAD

**Issue by rivers07-maker** [microsoft/vscode#201369]
The Codespace is not loading properly. I'm trying to practice the Week 2 exercises and is imposible. Can I have an opportunity to work in the Codespace? Thanks in advance!

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by justschen** [comment]
@rivers07-maker can you provide some additional details? what part is not loading properly?

**Comment by rivers07-maker** [comment]
I already solve the problem, it has to do with my internet connection.
Thanks!
