### ISSUE TITLE
my vs code studio is automatically unistalled last night iam sure i did not uninstalled and only i have the  access to my computer

### ISSUE THREAD

**Issue by rajeshpekala** [microsoft/vscode#201428]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by roblourens** [comment]
VS Code wouldn't uninstall itself. I would check whether antivirus or corporate policy is present on your machine and did something.
