### ISSUE TITLE
Option to move debug toolbar to the right side of the command center

### ISSUE THREAD

**Issue by rasitayaz** [microsoft/vscode#201438]
We can move the floating debug toolbar to the left side of the command center by setting this in `settings.json`:
```json
"debug.toolBarLocation": "commandCenter"
```
It looks like this:
![original](https://github.com/microsoft/vscode/assets/45076094/33070177-fb6c-4865-8b40-da41616e4478)

And this one is a prototype I made to show what I have in mind:
![example](https://github.com/microsoft/vscode/assets/45076094/d6c889de-0520-491d-a8bd-568e5f89c20f)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/200021
