### ISSUE TITLE
Formatter still format the whole python file with `modificationsIfAvailable` or `modifications`

### ISSUE THREAD

**Issue by XuShenLZ** [microsoft/vscode#201494]
Type: <b>Bug</b>

1. Commit and Push a file to source control with unformatted code such as
```python
a = 10/36
b = 145.038
c = 2.0/ 60.0
d = 'variable_name'
```
2. Enable the Editor: Format On Save
3. Choose "modificationsIfAvailable" or "modifications" from Editor: Format On Save Mode
4. Open the file we just had and add something, for example
```python
e = 13.5
```
5. Save the file with `ctrl+s`
6. You will see the whole file still gets formatted such that some spaces are added, and single quotes are converted to double quotes
```python
a = 10 / 36
b = 145.038
c = 2.0 / 60.0
d = "variable_name"
e = 13.5
```

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.2.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1360P (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (2.07GB free)|
|Process Argv|--crash-reporter-id 602cdfb3-807c-43f7-bab0-69d52a85f4d8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container wsm (compute) @ xps-ws-desktop|
|OS|Linux x64 6.2.0-39-generic|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900KF (32 x 1957)|
|Memory (System)|62.51GB (53.00GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.17.2
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
remote-explorer|ms-|0.4.1
sublime-keybindings|ms-|4.0.10
pdf|tom|1.2.2
material-theme|zhu|3.16.2
dbclient-jdbc|cwe|1.3.4
vscode-database-client2|cwe|6.9.6
gc-excelviewer|Gra|4.2.58
black-formatter|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1003402403
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30917235
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pythonregdiag2cf:30926736
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by brettcannon** [comment]
Based on the description I'm assuming you're using Black as your formatter. If that's correct then this is by design as Black itself doesn't support partial formatting, only the whole file.

If you're using another formatter, please open an issue in the repo for that extension.
