### ISSUE TITLE
vs code doesn't responding while open big size file

### ISSUE THREAD

**Issue by rj-eww** [microsoft/vscode#201477]
Type: <b>Bug</b>

When I try to open a Laravel log file, a popup appears saying it is not responding. I have to reopen VS Code. The log file is around 78MB. and this is many time happen when i try to open big file.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19043
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.27GB free)|
|Process Argv|--crash-reporter-id 2e83b74f-ae22-49d5-b922-03b73073c2ff|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
laravel-extra-intellisense|ami|0.6.4
bootstrap5-vscode|Anb|0.4.4
laravel-blade-spacer|aus|2.2.0
blackbox|Bla|1.2.40
vscode-intelephense-client|bme|1.10.2
better-toml|bun|0.3.2
simple-react-snippets|bur|1.2.7
better-phpunit|cal|1.6.2
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.11
vscode-eslint|dba|2.4.2
vscode-notes|dio|1.1.0
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.6.1
vscode-html-css|ecm|1.13.1
vscode-npm-script|eg2|0.3.29
vscode-great-icons|emm|2.1.102
prettier-vscode|esb|10.1.0
vscode-ionic-snippets|fiv|2.2.2
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
vscode-google-translate|fun|1.4.13
html-snippets|gey|0.2.3
vscode-pull-request-github|Git|0.79.2023122012
laravel-create-view|gli|0.0.6
go|gol|0.40.1
beautify|Hoo|1.5.0
laravel-blade-wrapper|IHu|1.0.1
php-namespace-resolver|Meh|1.1.9
vscode-html-format|moh|0.1.5
mongodb-vscode|mon|1.3.1
vsliveshare|ms-|1.0.5900
laravel-goto-components|nao|1.2.0
color-highlight|nau|2.5.0
laravel-blade|one|1.34.0
laravel-extension-pack|one|1.2.0
laravel5-snippets|one|1.17.0
phpunit-snippets|one|1.1.0
laravel-jump-controller|pgl|0.0.33
tsimporter|pmn|2.0.1
postman-for-vscode|Pos|0.16.0
prisma|Pri|5.7.1
prisma-insider|Pri|31.0.3153
LiveServer|rit|5.7.9
laravel-artisan|rya|0.0.31
vscode-blade-formatter|shu|0.23.5
vscode-fileutils|sle|3.10.3
html-to-css-autocompletion|sol|1.1.2
code-spell-checker|str|3.0.1
bootstrap-5-snippets-extension|swu|1.4.0
tabnine-vscode|Tab|3.53.0
even-better-toml|tam|0.19.2
open-in-browser|tec|2.0.0
java-fill|tre|1.0.5
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.6.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.34.0
material-theme|zhu|3.16.2
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
f6dab269:30613381
showlangstatbar:30737416
962ge761:30917236
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by SuffixAutomata** [comment]
![image](https://github.com/microsoft/vscode/assets/121671093/ac8223ac-5111-42f6-aca5-51e6dadd4c3f)

confirm - only opening the default editor crashes - the hex editor doesn't

Version: 1.85.0
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T22:27:05.695Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.0-28-generic
