### ISSUE TITLE
Default Configuration Change: Integrated Terminal Defaults OSX/Linux

### ISSUE THREAD

**Issue by tracker1** [Microsoft/vscode#20145]
I would suggest adjusting the following default configuration options, as the current linux/osx terminal (`/bin/bash`) are acceptable, however, the user environment isn't setup as the profile script isn't run.  If the default shellArgs were set, it would be a better default.

    // The path of the shell that the terminal uses on Linux.
    "terminal.integrated.shell.linux": "/bin/bash",

    // The command line arguments to use when on the Linux terminal.
    "terminal.integrated.shellArgs.linux": ["-l"],

    // The path of the shell that the terminal uses on OS X.
    "terminal.integrated.shell.osx": "/bin/bash",

    // The command line arguments to use when on the OS X terminal.
    "terminal.integrated.shellArgs.osx": ["-l"],

**Comment by Tyriar** [comment]
I've considered this in the past but I'm against it for the following reasons:

- Giving `*.shellArgs.*` a default on Linux/OSX would make it more difficult to customize the default
- AFAIK it's more of a hack to run a login interactive shell (see: http://unix.stackexchange.com/a/46856/115410 http://askubuntu.com/a/156038/409516). You would be better off putting your setup in `~/.bashrc` and/or ensuring `~/.bash-profile` is idempotent then sourcing that from your `~/.bashrc`.
