### ISSUE TITLE
We read `/etc/ssl/certs/ca-certificates.crt` and `/etc/ssl/certs/ca-bundle.crt` and add these to all requests made with Node.js' `https` module from the remote extension host.

### ISSUE THREAD

**Issue by ryrodriguez25** [microsoft/vscode#201427]
We read `/etc/ssl/certs/ca-certificates.crt` and `/etc/ssl/certs/ca-bundle.crt` and add these to all requests made with Node.js' `https` module from the remote extension host.

Maybe the failing request is made somewhere else. Could you attach a screenshot from when the error occurs?

_Originally posted by @chrmarti in https://github.com/microsoft/vscode/issues/131836#issuecomment-909983815_

**Comment by chrmarti** [comment]
This is a copy of my comment without additional information. I assume this was opened by accident. Closing.
