### ISSUE TITLE
Unable switch to HTTPS for Local Port Forwarding

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode#201465]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: `1.85.1`
- OS Version: `Windows_NT x64 10.0.19045`

```txt
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

Steps to Reproduce:

1. Create a sample Angular project (for testing tls connection)

    ```sh
    npm i -g @angular/cli

    ng new demo1 --ssr=false --style=css
    cd demo1
    ng serve --ssl
    ```

    At this moment, it will listen <https://localhost:4200/>

    ![image](https://github.com/microsoft/vscode/assets/88981/2e8d7627-6b8e-408e-8137-116ddcc82e3d)

2. Open with VSCode and create a new Local Port Forwarding

    ```sh
    code .
    ```

    I tried to switch to HTTPS.

    ![image](https://github.com/microsoft/vscode/assets/88981/9926537f-ce17-4e21-87d1-e02f9173435e)

    It never switch to HTTPS.

    ![image](https://github.com/microsoft/vscode/assets/88981/93441fc0-7f14-4e9a-b253-9c7ae73dd103)

    Preview in Editor

    ![image](https://github.com/microsoft/vscode/assets/88981/3bf4fc3e-4211-406f-b62a-827476fbcfb0)

    It never response.

    ![image](https://github.com/microsoft/vscode/assets/88981/aca27d33-e544-407f-b5e4-dc230c92013a)

**Comment by icleolion** [comment]
Glad to see it's not just me struggling with this issue!

https://github.com/microsoft/vscode/issues/201371

**Comment by connor4312** [comment]
This isn't something dev tunnels supports at the moment. Is there a way in the ports API to hide the "change port protocol" option?

**Comment by icleolion** [comment]
Sorry if I’ve misunderstood something here about the “dev tunnel” feature VS Code is using, but there are multiple references to dev tunnels supporting the https protocol in the microsoft docs.

https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/cli-commands

**Comment by alexr00** [comment]
@connor4312 I've added an opt out for tunnel factories with https://github.com/microsoft/vscode/pull/202067. I haven't tested it yet, but it should be pretty easy for dev tunnels to adopt!

**Comment by doggy8088** [comment]
I have no need to switch dev tunnels between HTTP and HTTPS. How can I add a port with HTTPS at the beginning for this new change?

**Comment by icleolion** [comment]
> I have no need to switch dev tunnels between HTTP and HTTPS. How can I add a port with HTTPS at the beginning for this new change?

Same here.  Looking at the dev tunnel CLI reference, I'd be inclined to say that instead of hiding the "change port protocol" feature, it should be fixed and expanded to also include "auto" as an option.  Unless someone can substantiate dev tunnels in VS code not supporting https.

![image](https://github.com/microsoft/vscode/assets/47498402/db5e2c37-58fd-422d-bc3b-95886c144fd2)

**Comment by alexr00** [comment]
Per @connor4312 in https://github.com/microsoft/vscode/issues/201465#issuecomment-1881501118, switching the protocol is not supported in Dev Tunnels. I've added a way for the Dev Tunnels extension to simply remove this functionality for ports forwarded by Dev Tunnels. Once @connor4312 adopts this in the Dev Tunnels extension you should be all set with `https` as the default, as I assume, Dev Tunnels will also just use `https` as the default.

**Comment by icleolion** [comment]
Ahh so https is supported, it's just switching protocol for a port already forwarded that isn't supported.  Which would explain why `auto` exists as a protocol option.  Thank you, that's where the misunderstanding was for me.  Not sure why that didn't click at first!

**Comment by doggy8088** [comment]
@alexr00 Can I switch from HTTPS to HTTP by configure the extension settings?

**Comment by alexr00** [comment]
Dev tunnels doesn't support http, so no.

**Comment by icleolion** [comment]
@alexr00 Please tell me I’ve misunderstood things again, because dev tunnels in vs code works just fine with http protocol as I mentioned in my original issue.

**Comment by connor4312** [comment]
Actually, it looks like their `auto` does not work, but if I manually request that dev tunnels connect via HTTPS, they seem to do the TLS negotiation through the tunnel. So this should work if I wire that up.

**Comment by icleolion** [comment]
@connor4312 ok, so is the plan now to keep the protocol switching menu (not bother with adding `auto` due to it's seeming uselessness) and when a user switches protocol, instead of updating the existing dev tunnel, it will be restarted instead using the new protocol?

**Comment by ionorb** [comment]
For anyone wanting to get this working while they fix the issue, you can download the devtunnel cli and follow the guide [here](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started).

For linux machines:

- Download ```devtunnel``` using:
```
curl -sL https://aka.ms/DevTunnelCliInstall | bash
```
- Then login and register with your microsoft account:
```
devtunnel user login
```
- Finally run the command mentioned by @doggy8088 above with your desired port:
```
devtunnel host -p 8080 --protocol https
```
Solved all my problems... In the meanwhile thanks for your great work on vscode @connor4312. I hope it'll be fixed soon! :)

**Comment by LePhenix47** [comment]
I'm facing the same issue. When attempting to port forward a development server using HTTPS protocol in VS Code, I'm unable to change the protocol on the Port Forwarding tab to HTTPS, it remains HTTP. 

Thus, I'm unable to provide access to my local web app.

**Comment by ionorb** [comment]
Exactly! Sad it is still not fixed... I just started manually using the devtunnel app, but it would be way more useful if it was fully integrated into vscode. @connor4312 I know you probably have a lot to do but is there any update on the progress of this issue?
