### ISSUE TITLE
Solarized coloration does not work on a diff file

### ISSUE THREAD

**Issue by mrvkino** [Microsoft/vscode#20144]
The default Solarized Dark or Light does not color the text in a diff file (actual diff or patch file).

- VSCode Version: 1.9.0
- OS Version: Macos 10.12.3

Steps to Reproduce:

1. Use the default VSCode Solarized theme and the text is grey
2. Open a diff or patch file
3. Change for another theme like Red to see the diff file text be in color

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19735

**Comment by mrvkino** [comment]
I am talking about an actual diff or patch file used to patch C code. Not the diff view generated by VSCode for the git integration.

#19735 seems more about the diff view from the git sidebar.

I have updated the issue explanation to clarify that I am talking about the actual file and not the git view from VSCode.

**Comment by Tyriar** [comment]
@mrvkino thanks for the clarification can you post a screenshot of the issue?

**Comment by mrvkino** [comment]
Here is the Solarized theme version:
![diff_patch](https://cloud.githubusercontent.com/assets/279511/22712250/2720c642-ed52-11e6-8135-fd0b9bf3d719.jpeg)

Here is the red theme version:
![diff_patch_red](https://cloud.githubusercontent.com/assets/279511/22712330/62a5f142-ed52-11e6-98ce-1ae89bfa3975.jpeg)
