### ISSUE TITLE
Highlight colors should be on the background for light themes.

### ISSUE THREAD

**Issue by Tnze** [microsoft/vscode#201439]
The code highlighting will color words. Under dark themes, the color of the code text will be more prominent than under light themes.

This is because the human eye is more sensitive to the colors of objects with higher brightness. Under the dark themes, the foreground is light, the color of text is evident. Under the light themes, the background is light, the color of text is illegible.

In my opinion, it's worth to try add colorful shadows to the code when light themes are used, instead color the text itself.

**Comment by Hphu2004** [comment]
Make yours things to best cost for best buy...

**Comment by aeschli** [comment]
What do you mean by `colorful shadows` ?

In general, all colors are defined by color themes and there many theme available on the marketplace. It's also easy to customise themes using the settings.I hope that way you can find a light theme that works for you.
