### ISSUE TITLE
Lock Workspace

### ISSUE THREAD

**Issue by ibrahimxcool** [microsoft/vscode#201458]
An option to lock a Window workspace (cant make chages to any file, unless uncloked) , so i dont accidently disturb the code when copying a code from one window to another

**Comment by bpasero** [comment]
I think you can get that done via the readonly settings we provide since a few months:

![image](https://github.com/microsoft/vscode/assets/900690/9b6b6871-bcc8-462c-a4b1-2d2b9d759b61)
