### ISSUE TITLE
Helo me please

### ISSUE THREAD

**Issue by XuananLe** [microsoft/vscode#201455]
Type: <b>Bug</b>

I just turn on the vscode and this bug appear

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 6.2.0-39-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1240P (16 x 1024)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|15.30GB (7.18GB free)|
|Process Argv|--no-sandbox . --crash-reporter-id 039a981d-4c56-4802-8db0-badff8ba3b13|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
tailwind-docs|aus|2.1.0
tailwindshades|bou|0.0.5
vscode-tailwindcss|bra|0.10.4
vscode-eslint|dba|2.4.2
gitlens|eam|14.6.1
codespaces|Git|1.16.5
copilot|Git|1.143.0
copilot-chat|Git|0.11.1
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.2
vscode-react-typescript|inf|1.3.1
rainbow-csv|mec|3.9.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.28.0
autopep8|ms-|2023.8.0
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.101
jupyter|ms-|2023.11.1003402403
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.0
vscode-typescript-next|ms-|5.4.20231223
sqltools|mtx|0.28.1
sqltools-driver-mysql|mtx|0.6.0
sqltools-driver-pg|mtx|0.5.2
vscode-python-typehint|njq|1.5.1
material-icon-theme|PKi|4.32.0
tsimporter|pmn|2.0.1
nextjs-snippets|Pul|1.0.1
vscode-thunder-client|ran|2.16.3
LiveServer|rit|5.7.9
pytorch-snippets|SBS|1.0.2
tailwind-fold|sti|0.1.0
pdf|tom|1.2.2
vscode-pets|ton|1.25.1
errorlens|use|3.16.0
vscode-icons|vsc|12.6.0
tailwind-snippets|Zar|1.0.2
previewjs|zen|1.27.3
material-theme|zhu|3.16.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30917235
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184c:30925681

```

</details>

**Comment by Iheuzio** [comment]
What exactly is the issue?
