### ISSUE TITLE
Problema ao instalar Entity Framework

### ISSUE THREAD

**Issue by PMagoga** [microsoft/vscode#201414]
Type: <b>Bug</b>

Já tentei diversar versões mas não consigo instalar o Entity Framework
![Captura de tela 2023-12-22 184650](https://github.com/microsoft/vscode/assets/94563183/6730b670-4d5d-4a71-98bd-5c44c37d33d9)

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.74GB (0.77GB free)|
|Process Argv|--crash-reporter-id 2436fe20-1242-459d-a501-799a896bbe01|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
vscode-django|bat|1.14.0
htmlplay|bia|0.0.10
django|big|1.0.2
bracket-pair-color-dlw|Bra|0.0.6
vscode-tailwindcss|bra|0.10.4
flask-snippets|cst|0.1.3
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
gitlens|eam|14.6.1
vscode-html-css|ecm|1.13.1
vsc-python-indent|Kev|1.18.0
csharpextensions|kre|1.7.3
vscode-docker|ms-|1.28.0
vscode-language-pack-pt-BR|MS-|1.85.2023121309
csdevkit|ms-|1.1.16
csharp|ms-|2.14.8
dotnet-maui|ms-|0.6.54
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.22.0
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.1
autopep8|ms-|2023.8.0
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1003402403
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
powershell|ms-|2023.8.0
sqltools|mtx|0.28.1
autodocstring|njp|0.6.1
inline-html|pus|0.3.9
sqlite-viewer|qwt|0.3.13
vscode-qt-for-python|sea|7.6.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.6.0
jinja|who|0.0.8
emmet-live|yse|1.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
89544117:30613380
vscrpc:30673769
a9j8j154:30646983
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t:30925682

```

</details>

**Comment by lszomoru** [comment]
This does not seem to be related to VS Code. Please post this issue in the dotnet repository.
