### ISSUE TITLE
Changing a theme on a second window also changes the first.

### ISSUE THREAD

**Issue by darrenparkinson** [Microsoft/vscode#20147]
Having multiple separate windows open, one for Markdown and one for code is quite common.  Having appropriate themes for each of those at the same time would be useful.  Thanks.

- VSCode Version: 1.9.0
- OS Version: macOS 10.12.1

Steps to Reproduce:

1. Open first window.  Set theme to "Light" for a Markdown file
2. Open second window. Set theme to "Dark" for code editing.
3. First window theme also changes.

**Comment by darrenparkinson** [comment]
I just noticed 1.9.0 got language specific settings.  Will it be possible to set the theme that way?

**Comment by Tyriar** [comment]
This is by design, however this will probably be flexible when https://github.com/Microsoft/vscode/issues/7358 is resolved.

/cc @aeschli
