### ISSUE TITLE
Toggle Line Comment does not work correctly

### ISSUE THREAD

**Issue by Mirodil** [Microsoft/vscode#20148]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|vscode-eslint|dbaeumer|1.2.4|
|githistory|donjayamanne|0.1.5|
|prettier-vscode|esbenp|0.8.0|
|flow-for-vscode|flowtype|0.4.0|
|docthis|joelday|0.3.10|
|Angular2|johnpapa|1.0.2|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.5.2|
|Spell|seanmcbreen|0.9.1|
|vscode-react-native|vsmobile|0.2.5|
|change-case|wmaurer|1.0.0|
|JavaScriptSnippets|xabikos|1.4.0|

---

Steps to Reproduce:

1. Open javascript file
2. Try comment some code with Toggle Line Comment by selecting multiple lines
it uses block comment `/* ... */` instead of line comment `//`

**Comment by rebornix** [comment]
@Mirodil can you help confirm if you are running into the same issue in https://github.com/Microsoft/vscode/issues/19868 ? Especially the info I put in https://github.com/Microsoft/vscode/issues/19868#issuecomment-277745476 .

**Comment by Mirodil** [comment]
it exactly like #19868, in my case it is constantly happening in new version. I did not have any problem with previous version. `shift+alt+a` is block comment in my case.

**Comment by rebornix** [comment]
@Mirodil do you mind sharing part of snippets that you have trouble with?

**Comment by Mirodil** [comment]
here is it `layout.js`:
```
import React from 'react';
import classes from './Layout.scss';

export const Layout = (props) => {
    const { children } = props;

    return (
        <div className={classes.container}>
            {children}
        </div>
    );
};

Layout.propTypes = {
    children: React.PropTypes.element.isRequired
};

export default Layout;
```
select all then try comment with `line comment`

**Comment by rebornix** [comment]
That's actually a real dup of #19868. Thanks for your help!
