### ISSUE TITLE
Autoindent doesn't trigger on closing parenthesis

### ISSUE THREAD

**Issue by russelldavis** [microsoft/vscode#201424]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Darwin arm64 22.6.0

Steps to Reproduce:
1. Ensure the **Editor: Auto Indent** setting is set to "full" 
2. Add the following to a `.js` file:

```js
console.log(
    "bar");
```
3. Place the caret after between the closing quote and the closing parenthesis.
4. Press enter

Expected: Autoindent should decrease the indentation of the new line, resulting in this:
```js
console.log(
    "bar"
);
```

Actual: Autoindent doesn't do anything, resulting in this:
```js
console.log(
    "bar"
    );
```

I tracked this down to a missing closing paren in the `decreaseIndentPattern` in the javascript and typescript [language configurations](https://github.com/microsoft/vscode/blob/860d67064a9c1ef8ce0c8de35a78bea01033f76c/extensions/typescript-basics/language-configuration.json#L131C4-L133). You can see there's an opening paren in `increaseIndentPattern` but no closing paren in `decreaseIndentPattern`.

**Comment by aiday-mar** [comment]
Hi @russelldavis, thank you for the analysis, you are totally correct. We will have a look at the linked PR.

**Comment by aiday-mar** [comment]
Hi @russelldavis, thank you for the analysis, you are totally correct. We will have a look at the linked PR.
