### ISSUE TITLE
Regression: VSCode ignores `unwantedRecommendations` from `.vscode/extensions.json`

### ISSUE THREAD

**Issue by ivankravets** [microsoft/vscode#201441]
Type: <b>Bug</b>

Microsoft tries to force every C/C++ developer to install unnecessary pack https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-extension-pack

This extension pack is typically useless and its extensions provide conflicts for PlatformIO developers ( https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide ). The extensions listed in the pack add new buttons and commands to the UI, confusing the end firmware developer. PlatformIO DOES NOT depend on these "recommended" extensions.

So, to fix this issue and provide superior developer experiences, we added Microsoft's pack (spam) to the `unwantedRecommendations` to avoid further conflicts. Now, VSCode ignores this configuration. See attached screenshot:

<img width="791" alt="Screenshot 2023-12-23 at 19 56 46" src="https://github.com/microsoft/vscode/assets/1760209/22849df3-9388-466a-a1f2-06bfab13eb5a">

------

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (4 x 2311)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (4.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.18.5
platformio-ide|pla|3.3.1

</details>

**Comment by sandy081** [comment]
Can you please provide the steps to reproduce?
