### ISSUE TITLE
Copying from the terminal does not copy across scrolls

### ISSUE THREAD

**Issue by tanmaybinaykiya** [Microsoft/vscode#20143]
Copying from the terminal does not copy across scrolls

- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.11|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.5|
|tslint|eg2|0.8.1|
|vscode-npm|fknop|3.3.0|
|docthis|joelday|0.3.10|
|prettify-json|mohsen1|0.0.3|
|Spell|seanmcbreen|0.9.1|
|java-imports-snippets|tushortz|0.0.1|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1. Have a multipage output in the console
2. Copy using Cmd+C
3. Paste it - Notice that only a part of the selected output is copied

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/6755
