### ISSUE TITLE
c++ compiler works extremely slow

### ISSUE THREAD

**Issue by Sahil-Vanani** [microsoft/vscode#201497]
Type: <b>Performance Issue</b>

hello sir/mam,

I have an issue regarding to c++ compliletion in visual studio. Whenever I complie c++ program, it takes a quite amount of time to run the program. Eventhough it takes 15 seconds to run a program of "hello world". 

Please, give me a viable solution for this!

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.34GB (1.66GB free)|
|Process Argv|--crash-reporter-id af9b7018-7ab4-40da-bb64-ed1a6b8a4df9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   101	  7996	code main
    0	   236	  3352	window [1] (Extension: CMake Tools - New folder - Visual Studio Code)
    0	   150	  6080	   gpu-process
    0	    83	  6884	ptyHost
    0	    41	  9508	   utility-network-service
    0	    90	 10288	shared-process
    0	    93	 10532	window [2] (Issue Reporter)
    0	    76	 13372	fileWatcher [1]
    0	   137	 17256	extensionHost [1]
    0	    89	 12432	     electron-nodejs ("C:\Users\SNEHA VANANI\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\SNEHA VANANI\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=17256)
    0	    85	 20084	     "c:\Users\SNEHA VANANI\.vscode\extensions\ms-vscode.cpptools-1.18.5-win32-x64\bin\cpptools.exe"
    0	    10	  2776	       C:\windows\system32\conhost.exe 0x4
    0	     4	  2972	       "c:\Users\SNEHA VANANI\.vscode\extensions\ms-vscode.cpptools-1.18.5-win32-x64\bin\cpptools.exe"
    0	    46	  3704	         "c:\Users\SNEHA VANANI\.vscode\extensions\ms-vscode.cpptools-1.18.5-win32-x64/bin/cpptools-srv.exe" 20084 {07A3C94B-19AF-41C2-94AB-D3BA08BC7222}
    0	    10	  2136	           C:\windows\system32\conhost.exe 0x4
    0	    28	 19232	   crashpad-handler
    0	    88	 19980	   window
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: CMake Tools - New folder - Visual Studio Code)
|    Folder (New folder): 5 files
|      File types: json(2) cpp(1) exe(1)
|      Conf files: settings.json(1) tasks.json(1);
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.1
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30917235
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t:30925682

```

</details>

**Comment by roblourens** [comment]
This sounds like an issue with your code or configuration. If you think it's an issue with VS Code, please open an issue with much more detail on the C++ extension repo.
