### ISSUE TITLE
Terminal Window Not opening Visual Studio Code  its hidden inside tools always Mac m2 OS Sonama 

### ISSUE THREAD

**Issue by pavan1289** [microsoft/vscode#201407]
Type: <b>Bug</b>

Hi Team,

Always terminal window hidden on Sonama Mac OS M2 Pro ,Please check why it is like that .

VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin arm64 23.2.0
Modes:

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed
