### ISSUE TITLE
Visual Studio Code installer failing

### ISSUE THREAD

**Issue by c-sattler** [microsoft/vscode#201445]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Go to https://code.visualstudio.com/download
2. Click on any version's download link
 Download times out waiting for response.
Alternatively, go to https://update.code.visualstudio.com/v1_85/win32-x64/stable response is "Cannot GET /v1_85/win32-x64/stable"
I have also tried getting it from the Microsoft store

**Comment by joaomoreno** [comment]
https://update.code.visualstudio.com/1.85.1/win32-x64/stable
