### ISSUE TITLE
In "Find in files" add a small X similar to other input fields, it's the only field you need to backspace to erase

### ISSUE THREAD

**Issue by yaronelh** [microsoft/vscode#201503]
Very simple, add to the "Find in files" input field a small X similar to other input fields, 
it's the only field you need to backspace to erase, That way we can clear the input field with one click instead of a long backspace press.

**Comment by ADTC** [comment]
This one? You can click the "Clear Search Results" button:

<img width="464" alt="image" src="https://github.com/microsoft/vscode/assets/6047296/56a1025e-5b33-4d34-92fb-23c7051816b9">

**Comment by yaronelh** [comment]
I don't know from which part of the application this is, for me clicking Ctrl+Shift+F Looks like this.
![image](https://github.com/microsoft/vscode/assets/7690499/f51c44a9-0059-4285-ab87-cef59c9ad207)

In your screenshots there seems to be buttons underneath "Clear Search Results", and it's not located properly (part of the input box border is hidden).

Are you sure it's not an extension that is adding it for you?

**Comment by ADTC** [comment]
@yaronelh it's the same thing. I just moved it to the secondary side bar. But it's exactly the same as what you're looking at.

> In your screenshots there seems to be buttons underneath "Clear Search Results", and it's not located properly (part of the input box border is hidden).

Those are the same buttons you see... the `Aa`, `ab` and `.*` buttons. They are just under the tooltip of the "Clear Search Results" button (which is what I'm trying to show you).

This is part of VS Code, not an extension. Have you located the button for "Clear Search Results"? It's the one with lines and a small cross at the corner, in BOTH screenshots (yours and mine).

**Comment by ADTC** [comment]
This one: 
<img width="59" alt="image" src="https://github.com/microsoft/vscode/assets/6047296/b8027e1d-e501-4e88-8306-01305b8bc4b3">

**Comment by yaronelh** [comment]
I see it,, 
![image](https://github.com/microsoft/vscode/assets/7690499/32f6cee7-8706-4d68-b6f3-e7b72c73371e)

They implemented it outside of the input box 👍

**Comment by ADTC** [comment]
Makes sense to me because it clears the search results as well as the input box. 🤷
