### ISSUE TITLE
Clean Current File, Clean All Files in Command Palette

### ISSUE THREAD

**Issue by mherodev** [Microsoft/vscode#20154]
It'd be lovely if the `Clean` operation (i.e. checkout current file, checkout all files) could be done from the command palette instead of the GUI.

Bonus request: Convert `Clean` from a destructive action into an action that uses the `undo` stack. This removes the warning and makes it more user friendly.

**Comment by xavadu** [comment]
+1

Just migrating to VSCode and looking for it, I installed the extension 'Git Easy' which add more git commands to the palette but still this is not available

**Comment by bartlewis** [comment]
And/or keybinding support for `clean` and `clean all`.

**Comment by eamodio** [comment]
Related, it would be great to have commands for `stage selected lines` and `unstage selected lines`

**Comment by joaomoreno** [comment]
This is now fixed in the upcoming SCM work.

**Comment by eamodio** [comment]
@joaomoreno `stage/unstage selected lines` too?

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/23176092/f24b7fd2-f861-11e6-9c14-f0ef50b95b7f.png)
