### ISSUE TITLE
The VS Code Speech extension should have a manual mode (disable end-of-speech detection)

### ISSUE THREAD

**Issue by emchristiansen** [microsoft/vscode#201595]
The VS Code Speech end-of-speech detection is really frustrating for me, because it often assumes I'm done talking when I'm not.

Instead of being super fancy, can I just have the option to press a button when I'm done?
E.g. `Command-u` to start and `Command-u` again to stop?

**Comment by meganrogge** [comment]
you can set `accessibility.voice.speechTimeout` to `0` to disable that.
