### ISSUE TITLE
[php] heredocs not colored

### ISSUE THREAD

**Issue by hbunjes** [Microsoft/vscode#2015]
I just ran into an error in parsing PHP in VS Code.

This is an example:
```php
$myVar=<<<EOT
    test content
EOT;
```

This is parsed fine but as soon as I insert a space or a tab after "EOT;" it breaks as it still sees this line as the end of the Heredoc string. However, only the "end word" (in this case EOT) and an optional semicolon is allowed, to other characters.

So the parsing in this case must only except the end word and the optional semicolon.

**Comment by TheColorRed** [comment]
+1

I am seeing the same thing.

**Comment by aeschli** [comment]
Sorry, I don't seem to bae able to reproduce this. Is this the complete code snippet?
This is about syntax highlighting, right?

**Comment by TheColorRed** [comment]
For me it was about syntax highlighting.

**Comment by hbunjes** [comment]
I just tried it again and it seems that HEREDOC isn't parsed at all. 

    <?php
    $myVar=<<<EOT
    echo "test content";
    EOT;
    ?>

In this case the text between the two "EOT" is a string that gets assigned to $myVar

However, the syntax highlighting indicates that `echo "test content"; ` is a function call to "echo".

**Comment by aeschli** [comment]
Ok, I see, that seems to be no support for HERE docs

**Comment by PimCoumans** [comment]
It appears to be working now. Ran into the same problem but carefully read the php.net description [http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc](url) which says
> It is very important to note that the line with the closing identifier must contain no other characters, except a semicolon (;). 

Placing the `EOT;` without any indenting fixes any issues I had

**Comment by hbunjes** [comment]
We are getting close :-)

The following code is currently not parsed correctly. After the first "EOT;" there are some spaces which means this lines belongs to the string. However, it's not colored as part of the string but like the end of the Heredoc.

```php
$test=<<<EOT
Hello	
EOT;     
EOT;
```

**Comment by markgukov** [comment]
Is it possible to highlight HTML tags inside heredocs? This can be made a user setting.

**Comment by aeschli** [comment]
I tried the given examples in 1.10-insiders and they seem to work now after switching to https://github.com/atom/language-php as TextMate grammar.

**Comment by aeschli** [comment]
@markgukov Please file this request separately
