### ISSUE TITLE
shebang fails to trigger (g)awk language syntax highlighting

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#201572]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.1
- OS Version: macOS Ventura

Steps to Reproduce:

1. Write an executable text file `bb` (*no file extension*) with a GNU awk shebang: `#!/usr/bin/env gawk -f`
2. View the file in VSCode.

# Expected

The file renders with (g)awk syntax highlighting.

# Observed

The file opens as a plain text document, rather than a (g)awk script. No syntax highlighting is applied.

VSCode gives up quite early in this case, as the script has no file extension. In my case, I am writing a general purpose CLI script, where the user is not required to know that the script is written in a specific programming language.

There appears to be a bug in VSCode when shebangs use `/usr/bin/env`. Unfortunately, certain programming languages, commonly Python and gawk, require the `/usr/bin/env` prefix, because the final interpreter binary is not located in /bin or any other universal, standard location. It's extremely varied across environments.

What's more, VSCode fails to persist the preferred language syntax for the file. Every time the file is opened, it loads as a plain text file with no highlighting. I have to manually correct the language every time I reopen the file.

**Comment by RedCMD** [comment]
What extension do you have installed for gawk?
as I'm pretty sure VSCode doesn't support gawk by default
for me VSCode detects `#!/usr/bin/env gawk -f` as `shellscript`

**Comment by alexr00** [comment]
@RedCMD is correct, we don't have any built in syntax highlighting for gawk. You'd need to install an extension for gawk syntax highlighting.
