### ISSUE TITLE
Right click to open specific folder opens multiple instances

### ISSUE THREAD

**Issue by goleary** [Microsoft/vscode#20153]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1. right click on vs code on the taskbar (no instance running) and select a recent or pinned folder
2. 3 instances of vs code open 3 different 

I get that vs code is trying to reopen my previous state, but if I specifically tell it I want to open a folder then why is it trying to return me to a previous state?

**Comment by Tyriar** [comment]
Did you have any unsaved changes open in the last session? These will restore in an individual session due to hot exit.

**Comment by goleary** [comment]
Not to my knowledge, but I can no longer repro the same behavior.  Will update if I see it again.

**Comment by bpasero** [comment]
Ok, closing until we have more info.
