### ISSUE TITLE
Can not make a change on settings or keybindings when open view PROFILES

### ISSUE THREAD

**Issue by XiLaiTL** [microsoft/vscode#201548]
Type: <b>Bug</b>

I want to change settings.
When I click Manage Profile -> Profiles -> Show Profile Contents, and then I get a PROFILES view.
I open settings.json by the view. However I can not change anything through it. And when I refresh the file, all the changes were cleaned.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800U with Radeon Graphics          (16 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (6.95GB free)|
|Process Argv|--crash-reporter-id f320210d-d8c6-4bcc-aa08-7bf78c837451 --crash-reporter-id f320210d-d8c6-4bcc-aa08-7bf78c837451|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
EnglishChineseDictionary|Cod|1.1.0
macros|ctf|1.0.0
vscode-markdownlint|Dav|0.53.0
markdown-all-in-one-for-web|fan|3.5.2
vscode-wordcount-cjk|hol|1.3.1
vscode-markdown-notebook|ms-|0.0.26
markdown-preview-enhanced|shd|0.8.11
vscode-toolbar|XiL|1.0.2
grammarly|znc|0.24.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30917235
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184t:30925682

```

</details>

![image](https://github.com/microsoft/vscode/assets/20791912/36fd777c-47b9-446e-8598-cb4398e969d5)

**Comment by sandy081** [comment]
You can change the settings from there, but these changes are not applied to the current profile. They are included only when you export the profile. Are you expecting the changes applied to the current profile?

**Comment by XiLaiTL** [comment]
I see, but **logically** the changes should apply to the current profile.
Because this view named "PROFILES" and it was opened by the menu "Show Profile Contents".
If just exporting, its name should be like this: "EXPORTING PROFILES".

**Comment by sandy081** [comment]
I understand your perspective. I would wait for more feedback before doing this change.
