### ISSUE TITLE
Other Extensions will be activated while debugging a C# project.

### ISSUE THREAD

**Issue by tn-072** [microsoft/vscode#201533]
Type: <b>Bug</b>

## Steps to Reproduce ##
1. Open a C# .NET project
2. Click the "Debug project associated with this file" button
3. After the debugging finished, click it again

## Expected Behavior ##

Extensions not for C# will not be activated.

## Actual Behavior ##

rust-analyzer and CMake Tools will be activated.

## Environment information ##

**VSCode version**: 1.85.1
**C# Extension**: 2.14.8
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.71b9f198

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.2
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.71b9f198
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  6.0.417 [/usr/local/share/dotnet/sdk]
  7.0.306 [/usr/local/share/dotnet/sdk]
  8.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|cmake|twxs|0.0.17|twxs.cmake-0.0.17|
|cmake-tools|ms-vscode|1.16.32|ms-vscode.cmake-tools-1.16.32|
|cpptools|ms-vscode|1.18.5|ms-vscode.cpptools-1.18.5-darwin-x64|
|csdevkit|ms-dotnettools|1.1.16|ms-dotnettools.csdevkit-1.1.16-darwin-x64|
|csharp|ms-dotnettools|2.14.8|ms-dotnettools.csharp-2.14.8-darwin-x64|
|markdown-all-in-one|yzhang|3.5.1|yzhang.markdown-all-in-one-3.5.1|
|markdown-footnotes|bierner|0.1.1|bierner.markdown-footnotes-0.1.1|
|markdown-yaml-preamble|bierner|0.1.0|bierner.markdown-yaml-preamble-0.1.0|
|material-icon-theme|PKief|4.32.0|pkief.material-icon-theme-4.32.0|
|python|ms-python|2023.22.1|ms-python.python-2023.22.1|
|remote-containers|ms-vscode-remote|0.327.0|ms-vscode-remote.remote-containers-0.327.0|
|remote-explorer|ms-vscode|0.4.1|ms-vscode.remote-explorer-0.4.1|
|remote-server|ms-vscode|1.5.0|ms-vscode.remote-server-1.5.0|
|remote-ssh|ms-vscode-remote|0.107.1|ms-vscode-remote.remote-ssh-0.107.1|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|remote-wsl|ms-vscode-remote|0.81.8|ms-vscode-remote.remote-wsl-0.81.8|
|rust-analyzer|rust-lang|0.3.1782|rust-lang.rust-analyzer-0.3.1782-darwin-x64|
|vscode-clangd|llvm-vs-code-extensions|0.1.26|llvm-vs-code-extensions.vscode-clangd-0.1.26|
|vscode-dotnet-runtime|ms-dotnettools|2.0.0|ms-dotnettools.vscode-dotnet-runtime-2.0.0|
|vscode-pylance|ms-python|2023.12.1|ms-python.vscode-pylance-2023.12.1|
|vscode-remote-extensionpack|ms-vscode-remote|0.25.0|ms-vscode-remote.vscode-remote-extensionpack-0.25.0|
|vscode-xml|redhat|0.26.1|redhat.vscode-xml-0.26.1-darwin-x64|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-darwin-x64|;

</details>

VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin x64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 x 1100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 62cfa310-8df8-4e0e-a145-dbcaa17c8040|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by tn-072** [comment]
<img width="1792" alt="截屏2023-12-27 13 33 15" src="https://github.com/microsoft/vscode/assets/97588735/59c4058f-1fc1-4cef-b388-60cd5a1961f3">

**Comment by roblourens** [comment]
Please file this issue on those extensions, they determine when they activate
