### ISSUE TITLE
Run build task fails

### ISSUE THREAD

**Issue by Leon99** [Microsoft/vscode#20152]
- VSCode Version: 1.9.0
- OS Version: Win10.0.14393
- PS Version: 5.1.14393.693

Steps to Reproduce:

1. _Tasks: Run build task_.

tasks.json:
```
{
    "version": "0.1.0",
    "command": "powershell",
    "args": [   
        "-ExecutionPolicy",
        "Unrestricted",
        "-NoProfile",
        "-File",
        "${cwd}/Invoke-PostBuildActivities.ps1"       
    ],
    "taskSelector": "-task ",
    "showOutput": "always",
    "tasks": [
        {
            "taskName": "build",
            "showOutput": "always",
            "isBuildCommand": true
        }
    ]
}
```

![image](https://cloud.githubusercontent.com/assets/6840381/22715617/d86eb376-ede5-11e6-9ea2-c6c0f3190134.png)

The script works OK when run directly with _Debug: Continue_.

Any ideas?

Not sure if it should be here or in the PowerShell extension's repo, sorry in advance if this is a wrong place.

Many thanks

**Comment by dbaeumer** [comment]
@Leon99, I assume your problem is the not correctly displayed output. In this case it is a dup of which will be addressed by running tasks in the terminal. 

Dups https://github.com/Microsoft/vscode/issues/3550.

Please ping if it was not about the encoding.

**Comment by Leon99** [comment]
Output is wrong indeed, but my main problem is that the script is not starting.
Thanks for letting me know about the plans to migrate to the terminal though.

**Comment by Leon99** [comment]
Hey @dbaeumer, just a reminder that this one shouldn't be closed. This is pretty critical since I can't use VSCode to run any powershell script. Just checked the very basic one, still the same:
![image](https://cloud.githubusercontent.com/assets/6840381/23005369/3840e0ba-f450-11e6-85f1-e86d47329559.png)
> Internal Windows Powershell error. Loading managed Windows PowerShell failed with error 80070002.

The same happens with the Insiders build.

**Comment by dbaeumer** [comment]
As said we migrate this to running in the terminal where PowerShell works for me as expected. You even have full control over the shell you want to use. See the release notes for 1.9 on how you can already test this. I have no plans to add this support back to the output panel runner.

If you want to directly control the shell you can have the following:
```
isShellCommand: {
    "executable": "powershell"
}
```

**Comment by Leon99** [comment]
Adding `"_runner": "terminal",` helped, thanks.
