### ISSUE TITLE
typescript.tsserver.experimental.enableProjectDiagnostics causes bug in eslint-define-config v2

### ISSUE THREAD

**Issue by U-4-E-A** [microsoft/vscode#201507]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Windows 10

Steps to Reproduce:

Upgrading the from the last version of [eslint-define-config](https://github.com/eslint-types/eslint-define-config) `v1` (`v1.24.1`) to the latest version (`v2.0.0`) stops package from properly displaying type errors when `typescript.tsserver.experimental.enableProjectDiagnostics` is set to `true`. 

`eslint-define-plugin` creator believes this to be a problem with vscode or TS. Please see discussion [this discussion](https://github.com/eslint-types/eslint-define-config/discussions/266) on package repo for more information.

**Comment by mjbvz** [comment]
This is an experiential setting that will not be finalized in its current form. Happy to take an PRs fixing this but we're not going to look into this on our side
