### ISSUE TITLE
[regression] Commit hotkey (ctrl+enter) no longer works

### ISSUE THREAD

**Issue by adalisk-emikhaylov** [microsoft/vscode#201506]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1 (user setup)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Open a repository.
2. Enter a commit message:
![image](https://github.com/microsoft/vscode/assets/69473580/d66292bb-5c8a-42d7-9c1e-4fa8fb5c7a6c)
3. Press Ctrl+Enter to commit.
4. Observe that nothing happens. Instead, a commit should've been created.

This used to work in older versions. Clicking the checkmark button works, so it's only the hotkey that's broken.

**Comment by lszomoru** [comment]
Could you please open the command palette and invoke the "Developer: Toggle Keyboard Shortcuts Troubleshooting" command. Then write the commit message and press Ctrl+Enter. Please send me the contents of the output window to better understand why the `scm.acceptInput` command is not matched. Thanks!
