### ISSUE TITLE
Voice: Linux arm64 build

### ISSUE THREAD

**Issue by brad** [microsoft/vscode#201573]
Can you make a Linux arm64 build for the [VS Code Speech extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-speech&ssr=false#overview)? A growing number of us Linux users are using computers with aarch64 architecture.

**Comment by gperdomor** [comment]
@brad is available...

<img width="351" alt="Screenshot 2023-12-28 at 00 07 35" src="https://github.com/microsoft/vscode/assets/371939/fa912b26-eb48-4f94-a820-7cda8a90d8ac">

**Comment by brad** [comment]
🤦🏼‍♂️ I'm sorry, I came here from [here](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-speech&ssr=false#overview) and I didn't realize I was in the vscode bug tracker. I'll adjust the title and label

**Comment by brad** [comment]
It seems that I cannot add the `workbench-voice` label. Can someone with permissions please do that?
