### ISSUE TITLE
Conda environment variables cached

### ISSUE THREAD

**Issue by Sayaka91** [microsoft/vscode#201529]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.1
- OS Version: Ubuntu 20.04.6 LTS
- Conda Version: 23.9.0

Steps to Reproduce:

1. Open VSC and activate a conda environment
2. Check os environment variables in a terminal on VSC

Detail: I tried using terminal of linux, os.getenv('some_env') not return anything, but when using terminal of VSC, it returns a value that cached from the previous running. The problem is if I want to change env values in .env file, this new values cannot be updated when I run on terminal of VSC

**Comment by meganrogge** [comment]
This type of issue is typically related to environment differences between VS Code's terminal and the external terminal. You can try diffing the two environments by printing them (eg. `env`, `Get-ChildItem env:`) and investigating any differences.

Closing this off as it doesn't look actionable on our end, you can read more about our [issue process here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label *question
