### ISSUE TITLE
 Prefer Go To Source Definition Should Be Enabled By Default

### ISSUE THREAD

**Issue by jwalkerinterpres** [microsoft/vscode#201520]
I'm a Typescript developer, and I think it's safe to say that no developer I've ever met has ever wanted to go to a Typescript definition when we `CTRL/Command + Click` a bit of code :)  We all want to see the code for what we clicked, not its type (although, obviously, "Goto Type" still makes sense when you click _on a type_).

It turns out, VS Code already has the correct behavior built-in, but for some reason you force people to enable it manually.  This is the reverse 80/20 rule: you're making 80%+ devs (who don't want to go to types) go to types, when less than 20% of them want to.  It should be the other way around: VS Code should support most devs out of the box, with a weird setting you have to enable if you're a freak (no judgment) who prefers looking at types to looking at code.
 
Please make "Prefer Go To Source Definition" enabled by default.   Not for me (I've already fixed it), but for every other Javascript AND Typescript dev.

**Comment by mjbvz** [comment]
There are good reasons why it's not enabled by default: it's far slower and less reliable

**Comment by jwalkerinterpres** [comment]
But who cares if it's slow? Go to Type Definition is useless, whatever it's speed.

  Trading performance for usefulness is a bad trade :(
