### ISSUE TITLE
extention host

### ISSUE THREAD

**Issue by Aka9877** [microsoft/vscode#201536]
Type: <b>Bug</b>

hello
i have a problem
when open th vscode, i see this error:
Extension host terminated unexpectedly 3 times within the last 5 minutes.
what's wrong?

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (2.02GB free)|
|Process Argv|--crash-reporter-id b81684b6-7c28-48fa-b66e-cdcb64ecfc2b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
laravel-extra-intellisense|ami|0.6.4
vscode-intelephense-client|bme|1.10.2
laravel-goto-view|cod|1.3.11
dart-code|Dar|3.78.2
flutter|Dar|3.78.0
xml|Dot|2.5.1
gitlens|eam|14.6.1
EditorConfig|Edi|0.16.4
php-intellisense|fel|2.3.14
code-runner|for|0.12.1
vscode-pull-request-github|Git|0.78.1
laravel-create-view|gli|0.0.6
laravel-blade-wrapper|IHu|1.0.1
code-groovy|mar|0.1.2
dotenv|mik|1.0.1
vscode-dotnet-runtime|ms-|2.0.0
python|ms-|2023.22.1
jupyter|ms-|2023.11.1003402403
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
gradle-language|nac|0.2.3
laravel-goto-components|nao|1.2.0
laravel-blade|one|1.34.0
laravel-extension-pack|one|1.2.0
laravel5-snippets|one|1.17.0
laravel-jump-controller|pgl|0.0.33
material-icon-theme|PKi|4.32.0
java|red|1.25.1
vscode-yaml|red|1.14.0
laravel-artisan|rya|0.0.31
vscode-blade-formatter|shu|0.23.5
laravel-goto-controller|ste|0.0.12
vscode-status-bar-format-toggle|tom|3.2.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.13.5
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.3
vscode-maven|vsc|0.43.0
php-debug|xde|1.34.0
php-pack|xde|1.0.3
material-theme|zhu|3.16.2
php-intellisense|zob|1.3.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
89544117:30613380
vscrpc:30673769
showlangstatbar:30737416
962ge761:30917236
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184c:30925681

```

</details>

**Comment by ulugbekna** [comment]
This is very likely caused by an extension. Please, use [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to identify which extension is causing the crashes.

**Comment by Aka9877** [comment]
I used it but the problem was not solved.
