### ISSUE TITLE
Creating user tasks in multiple configuration files, unable to open the correct tasks.json

### ISSUE THREAD

**Issue by ProudRabbit** [microsoft/vscode#201528]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
- OS Version: 
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:
1. switch to another configuration file
2. run the `Tasks: Open User Tasks` command or click `Setting` -> `User Tasks`

![image](https://github.com/microsoft/vscode/assets/56437960/04b2bdb0-de63-459e-90f2-78686b690ce2)

after running the `Tasks: Open User Tasks` command, will open the default `tasks.json` file, not under the current configuration.
![image](https://github.com/microsoft/vscode/assets/56437960/bfa4ac4c-002a-46e1-8cce-d382d54cad6a)

**Comment by meganrogge** [comment]
how did you create tasks in multiple configuration files? opening user tasks is working fine for me

**Comment by ProudRabbit** [comment]
@meganrogge 
No matter what configuration I am in, when I click the `Setting -> User Tasks` it always open `"C:\Users\yuhang_feng1\AppData\Roaming\Code\User\tasks.json"`. But what I want to configure is another `task.json` file, such as `"C:\Users\User_Name\AppData\Roaming\Code\User\profiles\-53d6f972\tasks.json"`. When I manually edit the content of this file, I can see the defined tasks in Vscode, but I cannot open them in Vscode.

![Image](https://github.com/user-attachments/assets/896f2699-e8c7-4277-9415-19757c0d0a78)
![Image](https://github.com/user-attachments/assets/2a90b38d-34de-43b1-a154-a5143b66f167)
![Image](https://github.com/user-attachments/assets/502b125e-bf77-463b-bef2-31033e4fa2f9)
