### ISSUE TITLE
Markdown Preview is cut off

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#20151]
- VSCode Version: 1.0
- OS Version: macOS

Steps to Reproduce:

1. Open a markdown file in preview mode 

![screen shot 2017-02-07 at 3 03 10 pm](https://cloud.githubusercontent.com/assets/543633/22715655/d24bef12-ed46-11e6-9dce-fafa733f7a3a.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/5745
