### ISSUE TITLE
Lagging while running loop question.

### ISSUE THREAD

**Issue by Brijanshu07** [microsoft/vscode#201565]
Type: <b>Performance Issue</b>

When i run any loop question  in vs code it take more than 30 second to show the output in  terminal even my first line of program that input taken from user is not show in terminal . 
Any other program run eaisly but in Loop question  it take more time to show output.
So please help me to resolved my problem as soon as possible 

Thank you 

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12450H (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (8.48GB free)|
|Process Argv|--crash-reporter-id 5277b7a4-2fe9-469d-8176-c6b2db07f031|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   123	 17604	code main
    1	    65	  1948	fileWatcher [1]
    0	   209	  2136	   gpu-process
    0	    96	  2704	window [2] (Issue Reporter)
    0	    91	  2740	shared-process
    0	    26	  6284	   crashpad-handler
    0	    81	  7088	ptyHost
    0	    38	 10968	   utility-network-service
    1	   223	 16912	window [1] (loop.c - c tutorial - Visual Studio Code)
    1	   149	 18068	extensionHost [1]
    0	    77	  8672	     electron-nodejs ("C:\Users\Abhishek Singh\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Abhishek Singh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=18068)
    0	    40	 17860	     "c:\Users\Abhishek Singh\.vscode\extensions\ms-vscode.cpptools-1.18.5-win32-x64\bin\cpptools.exe"
    0	     4	  3948	       "c:\Users\Abhishek Singh\.vscode\extensions\ms-vscode.cpptools-1.18.5-win32-x64\bin\cpptools.exe"
    0	    16	 10448	         "c:\Users\Abhishek Singh\.vscode\extensions\ms-vscode.cpptools-1.18.5-win32-x64/bin/cpptools-srv.exe" 17860 {9C50794F-F4FE-4040-85D2-2B43818E215C}
    0	    10	  7524	           C:\Windows\system32\conhost.exe 0x4
    0	    12	 17456	         "c:\Users\Abhishek Singh\.vscode\extensions\ms-vscode.cpptools-1.18.5-win32-x64/bin/cpptools-srv.exe" 17860 {63B8EF14-05A7-49D4-94B2-351BC50FAAF3}
    0	     5	 11396	           C:\Windows\system32\conhost.exe 0x4
    0	     5	 17856	       C:\Windows\system32\conhost.exe 0x4
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (loop.c - c tutorial - Visual Studio Code)
|    Folder (c tutorial): 51 files
|      File types: c(24) exe(21) json(4)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: cppdbg;
```

</details>
<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
android-emulator-launcher|343|0.9.0
vscode-django|bat|1.14.0
dart-code|Dar|3.80.0
flutter|Dar|3.80.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
code-runner|for|0.12.1
c-cpp-runner|fra|9.4.0
vsc-python-indent|Kev|1.18.0
vscode-edge-devtools|ms-|2.1.3
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.13
autodocstring|njp|0.6.1
LiveServer|rit|5.7.9
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
89544117:30613380
showlangstatbar:30737416
0bi6i642:30917235
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259
cp7184t:30925682

```

</details>

**Comment by roblourens** [comment]
What is a "loop question"? This wouldn't be an issue with vscode, this would be an issue either with an extension that you're using, or your code or configuration.
