### ISSUE TITLE
"Scroll lock" in Output doesn't work

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#20150]
Whether I have scroll lock toggled on or off, the output pane doesn't scroll with new build output. Seeing this in all of my projects in Insiders. 

- Open the vscode repo
- Open the output pane
- Enable scroll lock
- Build vscode
- New output goes below the output pane viewport, and it doesn't automatically scroll to keep the bottom in view.

**Comment by isidorn** [comment]
Great find. No clue how did this slip through the test plan!
