### ISSUE TITLE
vs code 1.85, Magnifier search icon disappeared but remaining search tool does not give results

### ISSUE THREAD

**Issue by pmorrsn99** [microsoft/vscode#201590]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Open VS code
2. No magnifying glass icon, other icons there.. But by clicking open editors,there is a search section.. But when I try a search, it does not show me results.

**Comment by gjsjohnmurray** [comment]
I suggest you run the Reset View Locations command from the Command Palette.

**Comment by pmorrsn99** [comment]
Wow, thanks

**Comment by romanPolansky78** [comment]
Wow it's works :-)
