### ISSUE TITLE
Incoming/Outgoing doesn't expand

### ISSUE THREAD

**Issue by kjorand** [microsoft/vscode#201570]
Type: <b>Bug</b>

Not sure if it's related directly to code or remote-ssh (I already ran the bisect command without success : it stops after the first iteration saying it might be a problem with vs code)

Am willing to provide any additionnal information ... 

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux arm64 5.10.104-tegra
Remote OS version: Linux arm64 5.10.104-tegra
Remote OS version: Linux arm64 5.10.104-tegra

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz (16 x 3792)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.68GB (7.05GB free)|
|Process Argv|--crash-reporter-id 841dbb85-6c2c-4a54-bf67-13ce05dd21ea|
|Screen Reader|no|
|VM|33%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.1.10|
|OS|Linux arm64 5.10.104-tegra|
|CPUs|ARMv8 Processor rev 1 (v8l) (6 x 729)|
|Memory (System)|7.16GB (4.34GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.1.10|
|OS|Linux arm64 5.10.104-tegra|
|CPUs|ARMv8 Processor rev 1 (v8l) (6 x 729)|
|Memory (System)|7.16GB (4.34GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.1.10|
|OS|Linux arm64 5.10.104-tegra|
|CPUs|ARMv8 Processor rev 1 (v8l) (6 x 729)|
|Memory (System)|7.16GB (4.34GB free)|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.4.2
emojisense|bie|0.10.0
mermaid-markdown-syntax-highlighting|bpr|1.6.0
vscode-firefox-debug|fir|2.9.10
auto-rename-tag|for|0.1.10
vscode-drawio|hed|1.6.6
better-cpp-syntax|jef|1.17.2
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
remote-explorer|ms-|0.4.1
php-docblocker|nei|2.7.0
pdf|tom|1.2.2
errorlens|use|3.16.0
gitlens|eam|14.6.1
nicksays|eng|1.4.1
todo-tree|Gru|0.0.226
omp-pragma|idm|1.1.0
rainbow-csv|mec|3.9.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.8.22
nsight-vscode-edition|nvi|2023.2.32964508
indent-rainbow|ode|8.3.1
cmantic|tde|0.9.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by kjorand** [comment]
![image](https://github.com/microsoft/vscode/assets/25977492/339822af-0109-4b51-a5e6-f0634a032c73)

If that might help ... 
(I tried clicking on the branch name as well as the ">" with same result : the ">" transforms to "v" and a "loading bar" appears quickly under the second "source control" for a split second and then it promptly comes back to the state as in the picture. As a precision : during that split second, nothing appears under the branch name ["labo04"] )

**Comment by lszomoru** [comment]
@kjorand, are you able to reproduce this with the latest VS Code Insiders release? Thanks!

**Comment by ddahlman** [comment]
@lszomoru I had the same problem and after trying it in version 1.86.0 insider release I could see that everything worked as expected

**Comment by lszomoru** [comment]
Thanks @ddahlman for the update. I will close this issue.
