### ISSUE TITLE
allow calculated replacements using match number

### ISSUE THREAD

**Issue by schahli** [microsoft/vscode#201556]
In Search and Replace operations make the number of the match available in the Replacement-Pattern including mathematical operations-

**Comment by andreamah** [comment]
Can you provide an example of this?

**Comment by schahli** [comment]
Yes, I can, dear Andrea Mah.
Given a text listing poems and songs in alternating sequence with poem-author and -title and Interpret and source where IT was taken from and interpret, title, CD-title for the songs.

Every poem-description contains a last line beginning with "Aus: ".
Every song-desription contains a last line beginning with "CD: ".

I want to generate a subrib title (SRT-File), which is used by mediaplayers to display just the  short text describing the poem or song.

May the average duration of the poems be p seconds and the average duration of a son be s seconds. In a first approximation , i can insert constant timeintervalls in the srt-File.

The first song starts at 00:00:00,000 and ends at the time in hh:mm:ss,ddd calculated from s; call ths Time(s).
The first poem starts at Time(1*s) and ends at Time (1*s+1*p).
The second song starts at Time(1*s+1*p) and ends at Time(2*s+1*p).
The second poem starts at Time(2*s+1*p) and ends at Time(2*s+2*p).
The rest follows by induction.

Calculated values of the count of a match of "Aus: " and "CD: " in replacement-expressions would solve the issue.

Thanks a lot.
Cheers from good old Germany
Karl Gutheil

Am Di., Jan. 2, 2024 at 18:37 schrieb Andrea Mah
***@***.***>:

Can you provide an example of this?
