### ISSUE TITLE
Problem starting program

### ISSUE THREAD

**Issue by YuanPeixi** [microsoft/vscode#201635]
Type: <b>Bug</b>

VSCode failed to start program. with message box from WindowsTerminal written Error: The following argument was not expected: /c Run with --help for more infomation

VS Code version: Code - Insiders 1.86.0-insider (9621add46007f7a1ab37d1fce9bcdcecca62aeb0, 2023-12-20T05:36:57.756Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (3.12GB free)|
|Process Argv|--crash-reporter-id e3602382-7d36-4ddb-ac73-7fa9d2694e7e|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.1.4
html-snippets|abu|0.2.1
language-mcfunction|arc|0.18.0
markdown-preview-github-styles|bie|2.0.3
masm|bli|0.0.5
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.3.1
syntax-mcfunction|Min|0.6.0
vscode-language-pack-zh-hans|MS-|1.85.2023121309
vscode-edge-devtools|ms-|2.1.3
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
cmake-tools|ms-|1.16.32
cpptools|ms-|1.19.1
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.12
js-debug-nightly|ms-|2023.12.1817
makefile-tools|ms-|0.8.22
vscode-typescript-next|ms-|5.4.20231229
shader|sle|1.1.5
datapack-language-server|SPG|3.4.19
markdown|sta|2.0.1
hlsltools|Tim|1.1.303
cmake|twx|0.0.17
JavaScriptSnippets|xab|1.8.0
masm-tasm|xsr|1.1.1
vscode-dosbox|xsr|0.1.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
a9j8j154:30646983
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30901775
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232
cp7184t:30925682

```

</details>

**Comment by aeschli** [comment]
When do you get this? When you start VS Code? Or when you run a task out of VS Code?

**Comment by YuanPeixi** [comment]
when I run a task out of VS Code?
