### ISSUE TITLE
Disabled paste option after copying a file from file explorer

### ISSUE THREAD

**Issue by shivankar-p** [microsoft/vscode#201639]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85
- OS Version: mac

Steps to Reproduce:

1. Once I copy a file from my file explorer and If I want to paste it in vscode's file explorer the paste option is disabled on right click. Although the paste works with cmd + v

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode/issues/199421
