### ISSUE TITLE
Impossible to View All Terminal Session Info

### ISSUE THREAD

**Issue by brettbialer** [microsoft/vscode#201691]
![Screenshot (3104)](https://github.com/microsoft/vscode/assets/7341121/1564d702-6dc9-4cde-b33f-0cc3ea53e4ea)
Type: <b>Bug</b>

VS Code's terminal session information window (that appears upon mouseover of the terminal session name) is is too small to render all text appearing within it.

It's fixed proportions cause the text to be cut off. Expanding it or vertically scrolling down is not possible. Even highlighting, copying, and pasting the text elsewhere to view it is not possible. This makes determining why a yellow "exclamation mark within triangle" icon appears immediately to the right of the terminal session name frustratingly difficult.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by meganrogge** [comment]
I believe this will fix itself automatically as you update Windows as we will move onto a newer version of conpty like what Windows Terminal ships to. We recently added a FAQ to workaround this but looks like you already figured that out: https://code.visualstudio.com/docs/editor/integrated-terminal#_i-see-1-or-201-when-i-paste-something

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed
