### ISSUE TITLE
Latest monaco editor build likely broken

### ISSUE THREAD

**Issue by basarat** [Microsoft/vscode#20166]
Built yesterday fine. Broken just today. 

- All builds https://travis-ci.org/basarat/monaco/builds
- Today's build https://travis-ci.org/basarat/monaco/builds/199465864#L960 Suspect a test definition has gone wonky (or missing) 

```
[02:12:47] Error: /home/travis/build/basarat/monaco/vscode/src/vs/workbench/parts/welcome/gettingStarted/test/common/gettingStarted.test.ts(13,1): Cannot find name 'suite'.
```

As always, just felt it would be helpful to report early. Love your work / monaco :rose: :heart:

**Comment by mjbvz** [comment]
Can you try updating and rebuilding. I've been trying to move us to use `@types` to manage our `d.ts` files and this may have broken that build

**Comment by basarat** [comment]
> Can you try updating and rebuilding.

Still failing https://travis-ci.org/basarat/monaco/builds/200739766#L961 

Thanks for looking into it :rose:

**Comment by mjbvz** [comment]
It looks like your build is synced to https://github.com/Microsoft/vscode/tree/8ac90919c0c23ede2d64a9281f09e40830de01de

You need to sync to at least 17ed384683d6712fca1ba96f8f729ab347d84359 to see if the fix worked

**Comment by basarat** [comment]
> It looks like your build is synced to

No. Its synced to whatever is latest on master at the time when the build is run. Relevant code https://github.com/basarat/monaco/blob/d01f946a7815112eeed7702431844a964ca212da/prepare.sh#L12-L13

In the log you can see `HEAD is now at f65c156 Merge pull request #18980 from chirag64/master`  https://travis-ci.org/basarat/monaco/builds/200739766#L190 which corresponds to commit https://github.com/Microsoft/vscode/commit/f65c156 which contains 
https://github.com/Microsoft/vscode/blob/f65c156e71612da878432672b487c6969b5dda2c/build/monaco/package.json#L16-L19 

----- 

That said I just realize that `npm install` is run in the vscode root. Had to do this in the past https://github.com/basarat/monaco/blob/d01f946a7815112eeed7702431844a964ca212da/extensions/preBuild.ts#L111 as the `npm install` changed for monaco vs. vscode (but still relied on the one in vscode). Seems like its been cleaned up so I shouldn't need to run the `npm install` for vscode. Will investigate and report back :rose:

**Comment by basarat** [comment]
:heart: Got it working https://travis-ci.org/basarat/monaco/builds/201329773


I did identify `winreg` types missing from the api `package.json` but present in the vscode  root `package.json` : https://github.com/basarat/monaco/blob/d0c41417b6fb79c2e305a5d77b29f39aef819dbc/extensions/preBuild.ts#L56-L58

I am sure there are others but merging vscode dev deps with api dev deps unblocks me now. Thanks for your help! :rose:
