### ISSUE TITLE
Cannot clear history of terminal in new window when both integrated terminal and terminal in text area exists

### ISSUE THREAD

**Issue by MikeWang000000** [microsoft/vscode#201636]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1 (commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2)
- OS Version: Darwin arm64 21.6.0

Steps to Reproduce:

1. `>Terminal: Create New Terminal in Text Area`
2. `>View: Move Editor into New Window`
3. `>Terminal: Create New Terminal`
4. Type some command in integrated terminal and press enter
5. Type some command in new windows' terminal and press enter
6. Right click new windows' terminal then click `Clear`

History of new windows' terminal is not cleared.
Instead, history of integrated terminal is cleared.

**Comment by meganrogge** [comment]
does this reproduce in insider's?

**Comment by MikeWang000000** [comment]
Using the latest insider, everything works fine...
Closing this issue...

---

Version: 1.86.0-insider (Universal)
Commit: d8a75eacf7c70e7327a460a8224dec14a65e1e27
Date: 2024-01-04T05:37:49.499Z (2 hrs ago)
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 21.6.0
