### ISSUE TITLE
how can i go to the last edit position

### ISSUE THREAD

**Issue by halleystar** [Microsoft/vscode#20165]
- VSCode Version: 1.9
- OS Version:  ubuntu 14.04

what's the keyboard shortcut that go to the last edit position

**Comment by Tyriar** [comment]
I use undo followed by redo to do this personally.

**Comment by halleystar** [comment]
that is a good idea, but there is a  better method to do that.

**Comment by alexandrudima** [comment]
The action is called "Go Back". Under Windows it is bound to `alt+left arrow`. For Ubuntu, you can find its binding in the F1 list.

**Comment by alexandrudima** [comment]
An alternative to that action is `ctrl+u` which undoes the last cursor move
