### ISSUE TITLE
Wrong position of Manage and Accounts model when primary side bar is in the right

### ISSUE THREAD

**Issue by cl3m3c7** [microsoft/vscode#201688]
Type: <b>Bug</b>

in Plasma desktop (KDE), and when the Primary Side Bar is in the right, the model shown from clicking on Manage and Accounts overlaps with the bar itself.

![Screenshot_20240102_183421](https://github.com/microsoft/vscode/assets/61097104/9a9f3060-42c2-4a02-a608-e2f1f4f34f18)
![Screenshot_20240102_183453](https://github.com/microsoft/vscode/assets/61097104/cfd8991a-9ce5-41df-9c52-d8693525add1)

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 6.6.8-zen1-1-zen
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3402)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|15.58GB (12.87GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by cl3m3c7** [comment]
Version: 1.86.0-insider
Commit: fb769554405bee9be16e21ceb0a496bd29126941
Date: 2024-01-09T09:57:05.633Z
Electron: 27.2.1
ElectronBuildId: 26149897
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.6.10-zen1-1-zen

and the problem still exists!

**Comment by sandy081** [comment]
Have you tried toggling the position?

**Comment by cl3m3c7** [comment]
[demo.webm](https://github.com/microsoft/vscode/assets/61097104/2356862e-38d3-4cf6-9ec7-d8ce14840248)

**Comment by sandy081** [comment]
Does it gets fixed when you reload the window?

**Comment by cl3m3c7** [comment]
no, it does not.

**Comment by sandy081** [comment]
@sbatten Can you please check this? Looks like user is always seeing the context menu not in the right location.

**Comment by sbatten** [comment]
These are native context menus and aren't designed to avoid the activity bar. This does not seem like a bug IMO.

**Comment by cl3m3c7** [comment]
@sbatten but that is not the case on windows OS, moreover when I click the settings button for example, if I don't hold the click, it clicks whatever under the cursor!

**Comment by sbatten** [comment]
@cl3m3c7 the menus on Windows are not native. You can enable this on Linux with `window.titleBarStyle`. However, the custom title bar on linux is styled like Windows because we cannot maintain custom implementations of every popular linux WM

**Comment by cl3m3c7** [comment]
@sbatten I see, thank you for the clarification.
