### ISSUE TITLE
Explore improved language support inside JSDoc comments, provide Intellisense for markup and symbols 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#20161]

**Comment by joelharkes** [comment]
Please add the following: native Jsdoc support for nodejs types & classes.

You can see vscode shows documentation for classes from nodejs:

![image](https://cloud.githubusercontent.com/assets/2960938/22980800/d5eb5130-f39a-11e6-9240-a7cb2f122ad5.png)

But it is not shown in jsdoc:
![image](https://cloud.githubusercontent.com/assets/2960938/22980851/026c5c72-f39b-11e6-85d2-0ebfdc3931e2.png)

When added manualy it is also need seen as any type:

![image](https://cloud.githubusercontent.com/assets/2960938/22980907/290bb030-f39b-11e6-9446-9caf72a46fcb.png)

**Comment by mjbvz** [comment]
Closing out exploration. Please open new issues for feature requests or bugs related to jsdocs
