### ISSUE TITLE
Reset Zoom on Macbook Pro (Cmd+NumPad0) doesn't exist 

### ISSUE THREAD

**Issue by tommyt99** [microsoft/vscode#201629]
Type: <b>Bug</b>

How come I can't just do Cmd + 0 for it to reset my zoom in vs code? I don't have a NumPad on Macbook Pro or my Windows laptops. Could you please fix this feature? Thanks.

VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin arm64 22.6.0
Modes:

**Comment by bpasero** [comment]
The command is reserved for `workbench.action.focusSideBar`. You can change keybindings.
