### ISSUE TITLE
Support to drag the debug hover inspector

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#2016]
After hovering over a variable while in debug mode, I would like to be able to drag the tooltip around so that I could easily refer to both it and my code. For example, in the shot below I have hovered over the params variable
![hoverpic1](https://cloud.githubusercontent.com/assets/1704059/12326895/5b09d148-bacb-11e5-933d-ee056aaa7f79.png)

But after I expand the elements in the array I see this:
![hoverpic2](https://cloud.githubusercontent.com/assets/1704059/12326906/6e71c86c-bacb-11e5-9357-2f23e1377bc3.png)

Ideally I would still like to be able to read the code following the line I am paused on and refer to the data in the inspector. I was imagining that I could click and hold on a blank area in the tooltip and then move the mouse to drag the tooltip to a convenient location.

**Comment by isidorn** [comment]
@stevencl I think this is a valid feature request and would be useful for some users. But what you then expect this behavior across all our hovers or just for the debug hover? If it is only the debug hover would it make it inconsitent?
