### ISSUE TITLE
regression: remote development disconnection prompt no longer associated with individual windows

### ISSUE THREAD

**Issue by arxanas** [microsoft/vscode#201686]
Type: <b>Bug</b>

Steps to reproduce:

1. Open a remote development connection via SSH to a remote host.
2. Open one in another window as well.
3. Open a third local-only window.
4. Focus the local-only window (not critical but helpful to demonstrate why particularly annoying).
5. Terminate the remote connection out-of-band (usually I put my laptop to sleep or cut VPN, but it should work to cut wi-fi?)

Expected behavior:

The two remote development windows show this dialog associated with each of them individually:

<img width="271" alt="Screenshot 2023-12-10 at 01 58 17" src="https://github.com/microsoft/vscode/assets/454057/879723d3-ec5f-4e9d-8195-9459c312d480">

The local-only development does not show this dialog at all. (In particular, this dialog blocks using the editor entirely, so you have to resolve *all* of them for *every* window when just trying to do local development.)

Actual behavior:

The first window to be used after the connection is dropped shows *all* of the dialogs, in sequence. You have to resolve 1 dialog per window with remote connection that was dropped, even if the remote connection was not associated with that window. This is particularly annoying because I would prefer to do local work when appropriate and not have to resolve remote connections at that time.

This used to be the behavior as of 2-ish (?) versions ago.

VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin arm64 23.2.0
Modes:
Connection to 'SSH: shainfra17' could not be established  Canceled
Connection to 'SSH: shainfra17' could not be established  Canceled
Connection to 'SSH: shainfra17' could not be established  Canceled
Remote OS version: Linux x64 5.4.117.hrtdev
Connection to 'SSH: shainfra17' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 6, 4|
|Memory (System)|32.00GB (0.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: shainfra17' could not be established  Canceled

Connection to 'SSH: shainfra17' could not be established  Canceled

Connection to 'SSH: shainfra17' could not be established  Canceled

|Item|Value|
|---|---|
|Remote|SSH: shainfra17|
|OS|Linux x64 5.4.117.hrtdev|
|CPUs|AMD EPYC 7502 32-Core Processor (64 x 3337)|
|Memory (System)|251.15GB (122.62GB free)|
|VM|0%|

Connection to 'SSH: shainfra17' could not be established  Canceled
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
errorlens|use|3.16.0
vim|vsc|1.27.2
hrtaddins|HRT|1.0.5
better-toml|bun|0.3.2
ccls|ccl|10.1.29
ruff|cha|2023.60.0
gitlens|eam|14.6.1
prettier-vscode|esb|10.1.0
black-formatter|ms-|2023.6.0
isort|ms-|2023.10.1
mypy-type-checker|ms-|2023.6.0
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1003402403
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
rust-analyzer|rus|0.3.1791
vscode-header-source|ryz|11.1.0
shellcheck|tim|0.35.0
clang-format|xav|11.9.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
vsjup518:30340749
vshan820:30294714
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184c:30925681

```

</details>

**Comment by justschen** [comment]
cc @roblourens

**Comment by roblourens** [comment]
Does this sound like it could be related to any Electron changes, @deepak1556? A native dialog is showing up on the wrong window.

**Comment by joshheinrichs-shopify** [comment]
I can reproduce this issue on 1.84.2. 1.83.1 shows the message in the correct window.

**Comment by arxanas** [comment]
I'm not sure if it's related, but I've also noticed that forwarded ports sometimes get associated with the wrong windows. Occasionally (not sure what triggers it), I'm doing remote web development, and then loading `localhost:1234` in my web browser (where `1234` is the forwarded port) starts hanging. In those circumstances, it persists after reloading the current window, and I think even after restarting VS Code. The fix is actually to find *another* window that appears to be forwarding the same ports, and then unset them there/close the window. I'm not sure if this issue was present before 1.84.

**Comment by joshheinrichs-shopify** [comment]
I bisected this and it appears to be due to 66d70da881fe56153a98c75f42df225dd0cfd5f0

**Comment by bpasero** [comment]
Sorry for the late triage, this should have been on my radar much earlier on. Will look into a fix.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/6ac03b980dab16b94cbebe1fd8442cc65cb078f5

**Comment by bpasero** [comment]
Fix has landed in insiders and can be verified.

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
