### ISSUE TITLE
TaskList in Markdown Preview

### ISSUE THREAD

**Issue by kylebutts** [microsoft/vscode#201669]
I know there is an extension for previewing checklists: https://github.com/mjbvz/vscode-markdown-checkboxes, but when checking a box in the preview, it leaves the `.md` file unchecked. It seems like this integration would go in the `markdown-language-features` extension folder. 

After adding the `markdown-it-task-lists` extension to the renderer, I think adding the checkbox feature would go in here:

https://github.com/microsoft/vscode/blob/df8db3a75a49b85c9636530a3557cdbc639f7bdc/extensions/markdown-language-features/preview-src/index.ts#L321-L354

Adding a check for `<input type="checkbox">`, getting the line number from `getEditorLineNumberForPageOffset`, then 
```ts
if (event.target.tagName === "INPUT" && event.target.type === "checkbox") {
	const offset = event.pageY;
	const line = getEditorLineNumberForPageOffset(offset, documentVersion);
	if (typeof line === 'number' && !isNaN(line)) {
                // Toggle - [ ] <-> - [x]
                // ...
	}
}
```

**Comment by mjbvz** [comment]
Please file this feature request against that extension. VS Code itself targets standard markdown which does not include task lists

**Comment by kylebutts** [comment]
@mjbvz is there a way to watch for click events in the VSCode preview window from another extension? Could you point me towards that API and I can try and submit a PR
