### ISSUE TITLE
Generate Commit Message with Copilot gives incorrect commit message

### ISSUE THREAD

**Issue by jsolly** [microsoft/vscode#201617]
Type: <b>Bug</b>

1 - Make some changes in a GitHub project. 
2 - Hit the 'Generate Commit Message with Copilot' button
The commit message has nothing to do with the changes I made.
![CleanShot 2023-12-29 at 15 43 24](https://github.com/microsoft/vscode/assets/9572232/e926475c-7ad7-4886-8db3-3cd24d1f5b13)

For example, I just made some basic changes to my app and this is the generated commit message:
"Update user authentication logic to use bcrypt hashing algorithm"

I've tried restarting the app to no avail. Every commit message is like this.

VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin x64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.01GB free)|
|Process Argv|--crash-reporter-id 15fadd92-ba66-41c4-9c50-8e66c634b1df|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-sql-formatter|adp|1.4.4
vscode-sievehighlight|adz|1.0.6
file-nesting|ant|1.1.2
vite|ant|0.2.5
vscode-tailwindcss|bra|0.10.4
ruff|cha|2023.60.0
vscode-eslint|dba|2.4.2
gitlens|eam|14.6.1
copilot|Git|1.143.0
copilot-chat|Git|0.11.1
vscode-github-actions|git|0.26.2
vscode-map-preview|jum|0.6.0
vscode-docker|ms-|1.28.0
black-formatter|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1003402403
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.327.0
live-server|ms-|0.4.13
vsliveshare|ms-|1.0.5900
vsliveshare-pack|ms-|0.4.0
material-icon-theme|PKi|4.32.0
sqlite-viewer|qwt|0.3.13
geo-data-viewer|Ran|2.6.0
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
vscode-coverage-gutters|rya|2.11.1
svg-preview|Sim|2.8.3
svelte-vscode|sve|108.1.0
even-better-toml|tam|0.19.2
sml-environment|vrj|0.0.3
vim|vsc|1.27.2
volar|Vue|1.8.27
vitest-explorer|Zix|0.2.43

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
vsjup518:30340749
vshan820:30294714
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
89544117:30613380
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by jsolly** [comment]
I should also mention this is currently only happening with one of my projects. I opened a new window and the other project is getting normal commit messages.

**Comment by albinhubsch** [comment]
This just started to happen to me as well in a few projects.

**Comment by jsolly** [comment]
@albinhubsch yes, I get that message a lot as well. Something to do with 'login' or cryptography.

**Comment by paycove-ben** [comment]
I'm experiencing a similar issue. It frequently says some update was made regarding "login" or "authentication". I'm using the Insider version. I also have many repos in a workspace, not sure if that's related. The issue persists even after committing all changes in other repos.

**Comment by MakingSpiderSense** [comment]
I'm experiencing a similar issue. It frequently says some update was made regarding "login" or "authentication". I'm using the Insider version. I also have many repos in a workspace, not sure if that's related. The issue persists even after committing all changes in other repos.

**Comment by expl0r3rgu1** [comment]
I've seen this so many times on my own. It might be something worth working on

**Comment by NonymousMorlock** [comment]
One eternity later

**Comment by lszomoru** [comment]
Since this issue has been filed we have updated both the model as well as the context users to generate the commit message. With the latest release of Copilot Chat we have also added support for specifying custom instructions when generating the commit message - https://code.visualstudio.com/updates/v1_96#_custom-instructions-for-commit-message-generation. I will go ahead and close this issue but please feel free to reopen it in case you are still hitting this issue. Thanks!
