### ISSUE TITLE
Mouse back and forward buttons do not work on Mac OS

### ISSUE THREAD

**Issue by Vladimir7i** [microsoft/vscode#201620]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1 (Universal)
- OS Version: MacOS Sonoma 14.2.1

Steps to Reproduce:

1. press F12 "go to definition" 
2. "ctrl-" for [go Back] is work, but "Mouse 4" is Not

**Comment by syradar** [comment]
@Vladimir7i What type of mouse do you use? I have the same issue with a Logitech M705 and the Logi Options+ app. You can add a keyboard override for VS Code until it is fixed.

## Add Logi Options+ override for VS Code

![image](https://github.com/microsoft/vscode/assets/10453338/2b05d54a-bb33-4d4f-89dc-ce29b630ada2)

Add a VS Code as a special application

![image](https://github.com/microsoft/vscode/assets/10453338/2207b48f-8ebb-440f-9e8c-44ebd4eaddd9)

Change the Back and Forward buttons to <kbd>Ctrl</kbd> + <kbd>-</kbd> and <kbd>Ctrl<kbd> + <kbd>Shift</kbd> + <kbd>-</kbd>
![image](https://github.com/microsoft/vscode/assets/10453338/78289ad1-e738-43d9-b900-2e27b680f5a2)

**Comment by miridius** [comment]
Just to be clear, the above is a workaround and not an actual solution. This issue has existed for years and is still broken. I found a number of copies of this issue, all closed without being fixed. No other app has any issues with the back and forward buttons, only VS Code.

**Comment by hexxone** [comment]
+1
Sad to see this is still an issue and has to be worked around instead of getting a fix.

And this is after Microsoft deprecating normal Visual Studio for Mac, only leaving you with VSCode as a free alternative.

**Comment by deepak1556** [comment]
Per https://github.com/microsoft/vscode/issues/88029#issuecomment-1000010739 and https://issues.chromium.org/issues/41490678 we don't have a way to intercept the events from these mouse buttons. Closing as not actionable.
