### ISSUE TITLE
The "Show raw keys" option (showKeys) is disabling everything

### ISSUE THREAD

**Issue by webarthur** [microsoft/vscode#201689]
When I disable the "Show raw keys" option (showKeys) in the VS Code settings, the editor no longer shows the shortcuts either. If the "showKeybingings" option is enabled it should show the shortcuts. This is not behaving the way expected.

![image](https://github.com/microsoft/vscode/assets/100484/2ff4e691-e694-4e7e-87e2-5d50666afab3)

**Comment by joaomoreno** [comment]
When I set these settings:

<img width="652" alt="image" src="https://github.com/microsoft/vscode/assets/22350/b7153515-740c-4d6e-8b70-7d1a9a4fbb33">

I still see command if I hit `Ctrl Shift P`.

**Comment by webarthur** [comment]
Unfortunately it doesn't work for me in this same configuration.

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.0-14-generic

**Comment by joaomoreno** [comment]
Sadly this is this: https://github.com/microsoft/vscode/issues/188938#issuecomment-1731334171

A big chunk of our internal commands simply do not have good descriptions. It requires a large change over the code base. Feel free to send a PR my way which adds descriptions to the few that you are dependent on, if this is important.

**Comment by webarthur** [comment]
Ok, but I would like it to show commands such as "Ctrl + C" even without a description and that is not happening. If I set it to show only the commands it continues to behave the same way, without showing the commands in the editor part. I remember that when I sent the commit that fixed some problems in the screencast, it was working perfectly, but now it no longer works.

![image](https://github.com/microsoft/vscode/assets/100484/af49b4dc-cd71-437b-8d02-873b83a49569)

It still doesn't work in this configuration.

**Comment by joaomoreno** [comment]
You're right, sorry for jumping the gun there, and thanks for the additional explanation. Fix coming. 👍
