### ISSUE TITLE
VSCode not working with wsl

### ISSUE THREAD

**Issue by Aidivni** [microsoft/vscode#201677]
Does this issue occur when all extensions are disabled?: Well I can't disable all extensions because I need wsl.

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

I tried reinstalling the wsl extension, updating wsl, and vscode, reinstalled vscode, still get the same error.

1. Navigate to desired folder in wsl
2. Type "code ."
3. Receive the following error:

+ COMMIT=0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ SERVERDATAFOLDER=.vscode-server
+ realpath /mnt/c/Users/Invidia/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/Invidia/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/Invidia/AppData/Local/Programs/Microsoft VS Code/bin
+ VSCODE_PATH=/mnt/c/Users/Invidia/AppData/Local/Programs/Microsoft VS Code
+ ELECTRON=/mnt/c/Users/Invidia/AppData/Local/Programs/Microsoft VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu-18.04 ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:
+ wslpath -m /mnt/c/Users/Invidia/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ CLI=C:/Users/Invidia/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/Invidia/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/Invidia/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --ms-enable-electron-run-as-node --locate-extension ms-vscode-remote.remote-wsl
+ cat /tmp/remote-wsl-loc.txt
+ WSL_EXT_WLOC=c:\Users\Invidia\.vscode\extensions\ms-vscode-remote.remote-wsl-0.81.8
+ [ -n c:\Users\Invidia\.vscode\extensions\ms-vscode-remote.remote-wsl-0.81.8 ]
+ wslpath -u c:\Users\Invidia\.vscode\extensions\ms-vscode-remote.remote-wsl-0.81.8
+ WSL_CODE=/mnt/c/Users/Invidia/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.8/scripts/wslCode.sh
+ /mnt/c/Users/Invidia/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.8/scripts/wslCode.sh 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2 stable /mnt/c/Users/Invidia/AppData/Local/Programs/Microsoft VS Code/Code.exe code .vscode-server .
+ [ -z .vscode-server ]
+ [ .vscode-server = .vscode-insiders ]
+ [ ! -t 0 ]
+ VSCODE_REMOTE_BIN=/home/invidia/.vscode-server/bin
+ AUTHORITY=wsl+default
+ [ Ubuntu-18.04 ]
+ AUTHORITY=wsl+Ubuntu-18.04
+ dirname /mnt/c/Users/Invidia/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.8/scripts/wslCode.sh
+ /mnt/c/Users/Invidia/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.8/scripts/wslDownload.sh 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2 stable /home/invidia/.vscode-server/bin
+ [ ! -d /home/invidia/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2 ]
+ RC=0
+ [ 0 -ne 0 ]
+ mktemp /tmp/vscode-distro-env.XXXXXX
+ STORED_ENV=/tmp/vscode-distro-env.uopGkE
+ env
+ dirname /mnt/c/Users/Invidia/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.8/scripts/wslCode.sh
+ VSCODE_CLIENT_COMMAND=/mnt/c/Users/Invidia/AppData/Local/Programs/Microsoft VS Code/Code.exe VSCODE_CLIENT_COMMAND_CWD=/mnt/c/Users/Invidia/.vscode/extensions/ms-vscode-remote.remote-wsl-0.81.8/scripts VSCODE_CLI_AUTHORITY=wsl+Ubuntu-18.04 VSCODE_CLI_REMOTE_ENV=/tmp/vscode-distro-env.uopGkE VSCODE_STDIN_FILE_PATH= WSLENV=VSCODE_CLI_REMOTE_ENV/w:ELECTRON_RUN_AS_NODE/w: /home/invidia/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/bin/remote-cli/code .

#
# Fatal error in , line 0
# Check failed: VerifyChecksum(blob).
#
#
#
#FailureMessage Object: 0x7ffff0213fb0
 1: 0xbe8881  [/home/invidia/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 2: 0x1e6acf4 V8_Fatal(char const*, ...) [/home/invidia/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 3: 0x134b4d9  [/home/invidia/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 4: 0xd9abfa v8::Isolate::Initialize(v8::Isolate*, v8::Isolate::CreateParams const&) [/home/invidia/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 5: 0xabc9e1 node::NewIsolate(v8::Isolate::CreateParams*, uv_loop_s*, node::MultiIsolatePlatform*, bool) [/home/invidia/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 6: 0xbc2f1e node::NodeMainInstance::NodeMainInstance(node::SnapshotData const*, uv_loop_s*, node::MultiIsolatePlatform*, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&) [/home/invidia/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 7: 0xb362cc node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResult const*) [/home/invidia/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 8: 0xb3a766 node::Start(int, char**) [/home/invidia/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
 9: 0x7f12bd114c87 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
10: 0xab681c  [/home/invidia/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node]
Trace/breakpoint trap
+ exit 133

**Comment by okineadev** [comment]
This is a checksum validation error.

Try updating VS Code
> `Settings > Check for Updates`

![image](https://github.com/microsoft/vscode/assets/81070564/3bbb1004-98af-446f-9847-a01da1e54389)

If this does not help - try to uninstall VS Code and install

**Comment by aeschli** [comment]
Yes. To force a reinstall of the server, close all VS Code windows, open a WSL terminal and run `rm -r ~/.vscode-server/bin`
