### ISSUE TITLE
"Run Selection/Line in Interactive Window" ignores empty lines in Python multi-line strings

### ISSUE THREAD

**Issue by moritzkoerber** [microsoft/vscode#201630]
Type: **Bug**

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: macOS 14.2.1 (23C71)

Steps to Reproduce:
1. Select the following code in VS Code, click on "Run in Interactive Window" -> "Run Selection/Line in Interactive Window" in the context menu.
```
"""\
foo


bar"""
```
Expected output: `'foo\n\n\nbar'`, actual output: `'foo\nbar'`

Note that this does not happen when you run the complete file in the interactive window or copy&paste the code into the interactive window and run it from there.

**Comment by amunger** [comment]
You can get your expected behavior with the setting `"jupyter.interactiveWindow.textEditor.normalizeSelection": false`, which we plan on making the default.
