### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by muratcan23** [microsoft/vscode#201673]
Type: <b>Bug</b>

can't see my installed extensions or cant reinstall any, pleese fix it or help me , I dont want to start the new year with such a bad vs code issue.
I had bunch of extensions but now I see as 0
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (9.03GB free)|
|Process Argv|--crash-reporter-id fbccbcb1-be9f-448d-ac29-ab007ad28add|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242:30382549
vsjup518:30340749
vshan820:30294714
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
f6dab269:30613381
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t:30925682

```

</details>

![Screenshot 2024-01-02 040007](https://github.com/microsoft/vscode/assets/61114943/1311e5a2-5ef2-4f72-92aa-3c83e779eaaa)

**Comment by muratcan23** [comment]
Can not install again the same extentions before I intalled . Here  one of the errors I took when I tried , 
![Screenshot 2024-01-02 115257](https://github.com/microsoft/vscode/assets/61114943/0aed6e4b-59fe-4215-a031-79c983d7b8f7)
![Screenshot 2024-01-02 115032](https://github.com/microsoft/vscode/assets/61114943/6659b954-f6a5-478e-9bc6-1ddd7f04a79c)
any suggestions?

**Comment by okineadev** [comment]
Show the **full** error log

**Comment by okineadev** [comment]
#201663

**Comment by muratcan23** [comment]
dont know how it occurred but it happened to me first day of 2024, find a solution that is pretty old school, in GitHub, =>. I cleared the folder "c:/Users/{user}/.vscode/extensions/" and reinstalled everything you want and everything works fine now... I am not gonna to lie, I was expecting a different solution, and it didn't come from mcirosft.
