### ISSUE TITLE
Markdown unchecked boxes are not highlighted correctly

### ISSUE THREAD

**Issue by taquangtrung** [microsoft/vscode#201638]
Hi,

The unchecked boxes of a Markdown document are somehow not correctly highlighted like the checked box:

Here is a sample screenshot, where the checked box at line 59, 60, 61 are highlighted, but other unchecked boxes are not:

![markdown list unchecked](https://github.com/microsoft/vscode/assets/193967/5d7cae9e-efd6-41b7-b2ca-e2f53cd16dbe)

Does this issue occur when all extensions are disabled?: YesNo

- VS Code Version: 1.85.1
- OS Version: Linux Mint 21.2

Steps to Reproduce:

1. Create a new Markdown document
2. Insert the following content and see the highlighting.

    ```
    - [x] Test 1
    - [x] Test 2
    - [ ] Test 3
    - [ ] Test 4
      + [ ] Test 4.1
      + [x] Test 4.2
      + [ ] Test 4.3
    ```

**Comment by mjbvz** [comment]
Markdown checkboxes are not part the common markdown spec. Support for them can be added by extensions
