### ISSUE TITLE
Markdown preview with JS allowed does fails to send console logs or errors to the "output" window

### ISSUE THREAD

**Issue by Pomax** [microsoft/vscode#201645]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.1
- OS Version: not relevant

Steps to Reproduce:

1. create a new dir containing a `test.js` and `test.md` file.
2. put `<script src="test.js" async defer></script>` in the `test.md` file
3. put ``console.log(`test`); throw new Error(`this should go somewhere`);`` in the `test.js` file
4. load `test.md` in VS code, and open its preview
5. in response to the insecure content warning, click the prompt and select the option that allows all content.

The JS will now be allowed to run (just like it would be on a github page based off of markdown content), but its logs and error data apparently go nowhere, they just disappear into the void rather than being written to the "output" window, as they should be.

**Comment by Pomax** [comment]
(This includes failures outside the user's own code, too, which means it's impossible to debug why something that JS should do, isn't happening)

**Comment by mjbvz** [comment]
You can use the normal chrome developer tools to see console logs and inspect the preview: `Developer: Toggle developer tools`

**Comment by Pomax** [comment]
That's... really weird: I shouldn't need dev tools just to see log/error text, that should just end up in the same place that everything else puts logs and errors. And then VS Code can pop up a little "if you want more details, use dev tools. Click here to learn more" that it pops up for everything else the first time when some of that output comes from JS in a preview. Dev tools should be an option, but not a requirement.

**Comment by mjbvz** [comment]
`console.log` is a dev thing. Plus the chrome dev tools are something web developers are used to and much more feature rich than anything we're going to build

**Comment by Pomax** [comment]
_The entirety of VS Code_ is a dev thing. What makes it great is that it puts information you need in places you first want it, with the ability to "get much more elaborate" if you need to, but not by default.

This is an excellent example of where that would make sense, too.
