### ISSUE TITLE
VSCode Extension Development: Send Command to Terminal without entering text

### ISSUE THREAD

**Issue by zqstack** [microsoft/vscode#201680]
At this moment I can run a command in the terminal by sending text (`terminal.sendText()`) to it. Now I would like to run a command without displaying the command, but only its output, like I can do with NPM scripts.

For example when `echo`ing in color or basically any command. I'd rather output custom logs, such as:
- Starting script..
- Completed step 1
- Completed step 2
- Done (In green color)

Instead of:
`echo -e '\x1b[32mOpen terminal\x1b[0m'`
`Open terminal` (in green color)

I would propose:
`terminal.sendCommand( command: string, showInput?: boolean )`
`terminal.sendOutput( text: string, color?: Color )`

**Comment by zqstack** [comment]
@Tyriar We have reached 20 upvotes, will it be added to the backlog please?

**Comment by Tyriar** [comment]
There isn't a way to do this without a bunch of hacks so this is out of scope. I recommend launching a one of terminal if you much hide the command and passing the command in as args to the shell (eg. `bash`, `['-c', 'echo blah']`)
