### ISSUE TITLE
Eclipse like C/C++ search feature for C/C++ projects

### ISSUE THREAD

**Issue by harish753** [microsoft/vscode#201611]
Hi,
In VScode, the existing search options are Ctrl+F and Ctrl+Shift+F only but the Eclipse IDE is offering one more beautiful search which is missing in VScode. And the search is a C/C++ search. By default, the search dialogue that opens in Eclipse IDE is a Ctrl+H keyboard shortcut.

![C_C++_search_Eclipse](https://github.com/microsoft/vscode/assets/46315611/467873f5-399d-429d-8eae-7278b3043268)

The differences between the traditional search of VScode and the C/C++ search can be understood from the above image. 

This has many uses for C/C++ programmers while searching and it improves the productivity who use VScode. And one more, C/C++ search doesn't search in comments too, how beautiful it is.

The Eclipse IDE also has a pinned feature for the search tabs. When one search tab is pinned then the new search results will open in the new search tab. This will be useful for people who need previous search results. This feature also can understand from above figure.

**Comment by gjsjohnmurray** [comment]
Re pinning, have you tried the "Open in editor" link that appears at the top of search results? Each search editor gets its own tab.

**Comment by harish753** [comment]
Yeah, I tried it but this feature is not exactly the same as what I proposed. Here, some manual intervention required to do this. But whatever the feature I told that will enhance the experience.

**Comment by IllusionMH** [comment]
FYI VS Code has Search editors feature to keep previous results and have different searches in parallel. 

As for comments - this is text only search (AFAIK for performance reasons and complexity), so it doesn't differentiate between comments and usages.
Not sure about C++ but other languages have "Find all references" which would cover this case a bit (but won't find all variables with same name)

**Comment by harish753** [comment]
> FYI VS Code has Search editors feature to keep previous results and have different searches in parallel.
> 
> As for comments - this is text only search (AFAIK for performance reasons and complexity), so it doesn't differentiate between comments and usages. Not sure about C++ but other languages have "Find all references" which would cover this case a bit (but won't find all variables with same name)

Hi,
Yes, I know the things that you shared. But I am requesting the VScode team to have the C/C++ search that I mentioned in the image. In the search editor tabs can't be kept in align with the search tab and able to keep up with existing source tabs.

**Comment by andreamah** [comment]
I prefer this to be handled on the extension API level, especially considering that this is language-specific. This is blocked on the extension APIs being finalized. https://github.com/microsoft/vscode/issues/59921
