### ISSUE TITLE
In split screen between code editor and interactive window, new tabs are randomly opened under heavy loading

### ISSUE THREAD

**Issue by Jakoviz** [microsoft/vscode#201726]
- VS Code Version: Version: 1.86.0-insider
Commit: df8db3a75a49b85c9636530a3557cdbc639f7bdc
Date: 2024-01-01T05:35:59.858Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
Jupyter extension v2023.11.1003402403
Python extension v2023.22.1
- OS Version: OS: Linux x64 6.2.0-39-generic

Steps to Reproduce:
1. Split the screen between code editor and interactive window
2. Add cells into execution queue
3. Cause extra loading by scrolling etc.
=> a tab will open
![vscode bug with split screen](https://github.com/microsoft/vscode/assets/7263106/984ff257-b8b1-408d-918a-efec7cb82a9a)

If my focus was in the interactive window, the new tab is another interactive window. If my focus was in the code editor, the new tab is another code window containing a line of code from around where my cursor was located at the time when this happens. The occurrence of the latter is more arbitrary, so it would not be so easy to catch it on a screen recording.

The tab does not just open, but also steals the focus. And it does not only steal the focus within VS Code, but from everything in my desktop, as seen in the gif. As maybe can be seen from the gif, my whole system goes quite unusable until it has processed the execution queue. I cannot even switch to another application to wait for it to finish, as it keeps hijacking the focus back. Also, it seems to me like the "extra" interactive window goes into some kind of a loop, at least the scroll bar keeps jerking back and forth in a nonsensical manner. And if I close the extra interactive window, it will also close the primary one.

I think this has something to do with heavy loading on the system, as this usually does not happen if I wait for all cell execution to finish before starting to scroll around. Also, it seems that it is more likely to happen if my VSCode window is maximized, as against having it tiled half-screen or smaller.

Maybe the same issue as: https://github.com/microsoft/vscode/issues/193084

**Comment by amunger** [comment]
Not sure what's going on there. I can't manage to repro, and from debugging that workflow, it only seems to call `openEditor` when the IW is initially opened.

Can you try creating a temporary profile (`Profile: Create Temporary Profile`) and just install the python and Jupyter extensions to see if it still reproduces without any other extensions or settings?

**Comment by Jakoviz** [comment]
Ok, I believe it was caused by the extension VSCode Neovim.
