### ISSUE TITLE
Editor Sticky Scroll highlighting does not kick in after reload

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#201728]
Reproduce:
1. Open a file and scroll to a location where sticky scroll appears in the editor
2. Reload Window
3. See that sticky scroll highlighting does not kick in until the user scrolls

<img width="908" alt="image" src="https://github.com/microsoft/vscode/assets/44439583/15ce8cc9-fe07-4b83-9e8d-853ba5eb6439">

**Comment by benibenj** [comment]
I've also seen it happen without reloading. I think this is an important bug to fix before it's released as on default.

**Comment by aiday-mar** [comment]
This issue appears to be a duplicate of https://github.com/microsoft/vscode/issues/201728. This issue will be closed in favor of the other issue.
