### ISSUE TITLE
Infinite app pop-ups while opening code

### ISSUE THREAD

**Issue by LaysonShen** [microsoft/vscode#201775]
Type: <b>Bug</b>

After I've finished compiling a tex file , I opened Onedrive and then closed my laptop. About half an hour later, I returned to my laptop and double-clicked on the VS Code icon on my desktop. A pop-up of warning "A vs code has already been running" and then infinite windows of vs code kept showing up and my laptop's CPU and ROM have been fully used.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7735H  with Radeon Graphics         (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.19GB (0.11GB free)|
|Process Argv|--crash-reporter-id 981d38b8-a826-4622-a353-c24a637dedda|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
matlab-formatter|Aff|2.11.0
matlab-interactive-terminal|apo|0.4.0
python-environment-manager|don|1.2.4
latex-workshop|Jam|9.17.0
vscode-fix-checksums|leh|1.1.0
language-matlab|Mat|1.1.5
vscode-language-pack-zh-hans|MS-|1.85.2023121309
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1003402403
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
indent-rainbow|ode|8.3.1
background|sha|1.2.13
markdown-preview-enhanced|shd|0.8.11
vscode-zipexplorer|sle|0.3.1
cpp-compile|tch|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
f6dab269:30613381
2i9eh265:30646982
962ge761:30917236
pythongtdpath:30769146
i26e3531:30792625
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30928863
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184t3:30927821

```

</details>

**Comment by LaysonShen** [comment]
![屏幕截图 2024-01-04 182947](https://github.com/microsoft/vscode/assets/69374332/a1a791e9-0e2e-4859-a6eb-f1416c6a21bb)
![屏幕截图 2024-01-04 183244](https://github.com/microsoft/vscode/assets/69374332/052463d0-b77e-4e50-a0dc-3f966cfe446a)

**Comment by LaysonShen** [comment]
After my manually shutting down these sessions through Task Manager, my vscode surprisingly works normally as it should have to be.

**Comment by joaomoreno** [comment]
Do you still have the issue?

**Comment by LaysonShen** [comment]
So far I haven't met it again











 申宇阳
Shen Yu-yang
  ***@***.***
  







Original:
From：João ***@***.***>Date：2024-01-11 16:27:28(中国 (GMT+08:00))To：microsoft/vscode ***@***.***>Cc：LaysonShen ***@***.***> , Author ***@***.***>Subject：Re: [microsoft/vscode] Infinite app pop-ups while opening code (Issue #201775)
Do you still have the issue?
