### ISSUE TITLE
For Copilot chat using VSCode chat api, keyboard up and down is easy to trigger to the boundary of the sentence I am writing so that it will be cleaned.

### ISSUE THREAD

**Issue by jasonwang82** [microsoft/vscode#201755]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. write a long sentence (better to be more than two lines)
2. then keyboard up and down up to the bounary
3. press again up/down, then current sentence is replaced to previous history or cleaned, so that I can not restore current sentence any more.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/661
