### ISSUE TITLE
Add option to ignore color-related errors in color-theme definitions

### ISSUE THREAD

**Issue by surfinzap** [microsoft/vscode#201763]
For my color theme, I have defined colors as mustache variables. For each of them, I get an error that they have an invalid color format. Can this particular check for color themes be turned off?
![image](https://github.com/microsoft/vscode/assets/1387798/c9991afe-5915-4fb4-85f1-12ba7cddad27)

**Comment by aeschli** [comment]
We only support JSON as format of the color-theme files, and color values have to be hex colors.
We have no plans to support other color formats than hex colors and also don't want to turn off errors for invalid values.

But you can define your own color theme file format with a different file name (not ending with `-color-theme.json`). Your tool will then convert that file to a `-color-theme.json` file.

**Comment by surfinzap** [comment]
Thanks for sharing the decision.

I'm not sure if this checking for problems is file-name-dependent, but one option to turn it on/off is to include `"$schema": "vscode://schemas/color-theme"` in the JSON file. With the schema on, I will get:
- tooltips on variables definition
![image](https://github.com/microsoft/vscode/assets/1387798/93e89a96-4c3c-475c-ac99-3afed811aa85)
- check on errors, e.g., checking null definitions, duplicate definitions, and invalid color format errors,
- and probably much more

All of the above is super useful to see; apart from checks on invalid color format. When I remove the $schema, I lose the invaluable tooltips on var definitions and other useful error checks just to get rid of the invalid color format errors. At the same time, color checks are irrelevant to me as I'm using variables to maintain multiple theme variations efficiently.
