### ISSUE TITLE
Usage of input from `launch.json` inside `tasks.json` when used as `preLaunchTask`

### ISSUE THREAD

**Issue by ThaDaVos** [microsoft/vscode#201785]
It's seems to be a re-open of this one: https://github.com/microsoft/vscode/issues/95158

But I expected that if one uses the same input (same ID) in both the `launch.json` and `tasks.json` that I would only get asked once for the input and it gets used in both files, but I am getting asked twice, which may lead to a misconfiguration if choosing a different option - the used inputs is below:

```json
............
  "inputs": [
    {
      "id": "BuildConfiguration",
      "description": "The used Build Configuration: Debug or Release",
      "default": "Debug",
      "options": ["Debug", "Release"],
      "type": "pickString"
    }
  ],
............
```

So the feature I would like, is that the input, as long as the ID is the same, gets re-used - or a way to pass it through manually, like a `preLaunchTaskInputs` - to define each input one wants to supply, maybe as follows:
```json
............
"preLaunchTaskInputs": {
  "BuildConfiguration": "${input:BuildConfiguration}"
}
............
```

Above would allow fixed set values or re-using inputs, even with different names, to be passed to the task - it's also the most flexible solution

**Comment by ThaDaVos** [comment]
Seems I haven't searched good enough, or with the correct arguments - but this old issue seems to be almost the same:
https://github.com/microsoft/vscode/issues/27157

**Comment by roblourens** [comment]
I think https://github.com/microsoft/vscode/issues/27157 would be the right approach
