### ISSUE TITLE
Automatically adjust lightness of indistinguishable text. [apperance][feature-request]

### ISSUE THREAD

**Issue by wfnian** [microsoft/vscode#201766]
In the Appearance settings of the Windows terminal, there is a setting:
### Automatically adjust lightness of indistinguishable text
> Automatically brightens or darkens text to make it more visible. Even when enabled, this adjustment will only occur when a combination of foreground and background colors would result in poor contrast. 

This setting is particularly user-friendly for individuals with mild visual impairments. It is hoped that this feature can be implemented in Visual Studio Code in the near future.

![setting of Windwos terminal](https://github.com/microsoft/vscode/assets/18214955/3903e7a5-d5db-4440-96e4-f312154535bf)

**Comment by Tyriar** [comment]
This feature actually existed in VS Code before that one did in WT AFAIK 😉 

https://code.visualstudio.com/docs/terminal/appearance#_minimum-contrast-ratio
