### ISSUE TITLE
Chat editor contents fail to load on VS Code reload

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#201745]
Type: <b>Bug</b>

1. Open the chat panel and move the chat to editor.
2. Reload VS Code
3. Chat Editor fails with below error:

![Image](https://github.com/microsoft/vscode/assets/25044782/ef8c4722-de9c-4155-8c56-43caddd0916c)

VS Code version: Code - Insiders 1.86.0-insider (df8db3a75a49b85c9636530a3557cdbc639f7bdc, 2024-01-01T05:36:24.423Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 6.2.0-1018-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (20.74GB free)|
|Process Argv|--crash-reporter-id 8e212a87-3023-4cf9-a7ca-f2a280d2f266|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: friendly invention|
|OS|Linux x64 6.2.0-1018-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (4 x 3023)|
|Memory (System)|15.61GB (11.26GB free)|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
vscode-eslint|dba|2.4.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
codespaces|Git|1.16.5
copilot|Git|1.144.0
copilot-chat|Git|0.12.2023122001
remotehub|Git|0.62.0
vscode-pull-request-github|Git|0.79.2023122012
csdevkit|ms-|1.2.5
csharp|ms-|2.14.8
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2024.1.2023122501
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.327.0
remote-wsl|ms-|0.81.8
azure-repos|ms-|0.38.0
cpptools|ms-|1.19.1
live-server|ms-|0.5.2023121201
remote-repositories|ms-|0.41.2023121801
remote-server|ms-|1.5.0
vscode-github-issue-notebooks|ms-|0.0.130
vscode-selfhost-test-provider|ms-|0.3.22
vscode-typescript-next|ms-|5.4.20240102
vscode-json-validate|rio|1.4.3
luna-paint|Tyr|0.16.0
helloworld-sample|und|0.0.1

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/187764
