### ISSUE TITLE
Editor sticky scroll missing code highlighting until scroll happens

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#201727]
Repro: 

1. Have some typescript file with >= 1 levels of sticky scroll visible in the editor
2. Reload window -> :bug:

https://github.com/microsoft/vscode/assets/16353531/4bef5360-709c-4b1b-b1da-625c963d9fcb

Version: 1.86.0-insider
Commit: 9621add46007f7a1ab37d1fce9bcdcecca62aeb0
Date: 2023-12-20T05:47:39.317Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0

cc @hediet since you mentioned sticky scroll during planning call

**Comment by hediet** [comment]
@aiday-mar you should listen on the tokenization changed/finished event.
