### ISSUE TITLE
vscode.dev popup shadow bug

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#201747]
shadow looks off on this popup/notice thing. Maybe a z-index bug?

![image](https://github.com/microsoft/vscode/assets/2644648/ec186ba1-184d-4847-8063-cd94c4379b68)

**Comment by nikhilkarve** [comment]
Can I take a look at this? @TylerLeonhardt or has anyone already started working?

**Comment by bhavyaus** [comment]
Feature no longer active.
