### ISSUE TITLE
It gets a bit glitchy (visually)

### ISSUE THREAD

**Issue by alenjohn0571** [microsoft/vscode#201774]
Type: <b>Bug</b>

i dont kno what is happing but the vscode screen gets weird when i change tabs

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|9.88GB (3.34GB free)|
|Process Argv|--crash-reporter-id b8fa7f72-fa6a-476c-a545-1d10858282c4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|3.0.0
dbclient-jdbc|cwe|1.3.4
vscode-mysql-client2|cwe|6.9.8
dart-code|Dar|3.80.0
flutter|Dar|3.80.0
emulate|Die|1.6.0
vscode-language-babel|mgm|0.0.40
vscode-docker|ms-|1.28.0
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1003402403
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.81.8
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
vscode-react-native|msj|1.12.2
sqltools|mtx|0.28.1
sqltools-driver-mysql|mtx|0.6.0
r|REd|2.8.2
LiveServer|rit|5.7.9
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vshan820:30294714
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
89544117:30613380
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30928863
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by alenjohn0571** [comment]
![Screenshot 2024-01-04 154425](https://github.com/microsoft/vscode/assets/72413454/49dda324-a2e6-4f38-bd2b-00bdeea6d91d)

**Comment by alenjohn0571** [comment]
![image](https://github.com/microsoft/vscode/assets/72413454/24166964-667a-433c-b3b6-3b60880f0986)

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by alenjohn0571** [comment]
Thank you for your response
Its working perfectly now

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/124226
