### ISSUE TITLE
在过去5分钟内内，TypeScript语言服五意外终止了5次

### ISSUE THREAD

**Issue by EvaSong1990** [Microsoft/vscode#20173]
- VSCode Version: Code 1.9.0 **[Unsupported]** (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|background|shalldie|1.1.9|
|theme-tinaciousdesign|tinaciousdesign|0.1.1|

---

Steps to Reproduce:

1.
2.

**Comment by nguymin4** [comment]
Similar to #20110

**Comment by mjbvz** [comment]
Two questions:

* Do you see a message about a missing `typingscript/...` file?
* Are you opening a folder on sharepoint?

**Comment by DennisGuo** [comment]
I have the same issue ,when I open my react project ,!

The package.json  :

```json
{
  "name": "geobeans-gropramming-rule",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-scripts": "0.8.4",
    "redux-logger": "^2.7.4"
  },
  "dependencies": {
    "axios": "^0.15.3",
    "fetch": "^1.1.0",
    "github-markdown-css": "^2.4.1",
    "markdown": "^0.5.0",
    "material-design-lite": "^1.2.1",
    "promise-polyfill": "^6.0.2",
    "react": "^15.4.1",
    "react-dom": "^15.4.1",
    "react-redux": "^5.0.1",
    "react-router": "^3.0.0",
    "redux": "^3.6.0",
    "whatwg-fetch": "^2.0.1",
    "zenscroll": "^3.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

```

**Comment by mjbvz** [comment]
Please check the `C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib` path. There should be a `tsserver.js` file there. We've seen a few reports of overenthusiastic anti-virus software is deleting these files however.

If the file is missing, you can [use a custom typescript install with `typescript.tsdk`](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). You can also reinstall vscode to restore the files. Be sure to exclude the typescript directory from antivirus to prevent this from happening again. Our official downloads ship the standard npm typescript package
