### ISSUE TITLE
Cannot do Copy Paste

### ISSUE THREAD

**Issue by exmadesu** [microsoft/vscode#201744]
Type: <b>Bug</b>

I have no idea, why i can't do `Copy -> Paste` data that already stored on **Clipboard**.. I just tested to Paste on another place like _Notepad_, _Sticky Notes_, _Sublime_, also _Console tab on Chrome_.

The Clipboard data is exists, and the data is written there. But VSCode not working, both `Ctrl+V`, and `Right Click Context Menu -> Paste`.

The copy problem is just same, both `Ctrl+C` and `Right Click Context Menu -> Copy` from VSCode not stored on my **Clipboard**.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (20.10GB free)|
|Process Argv|--crash-reporter-id 9cd7d090-217c-47d3-9f1e-bca2d91d3f09|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
chrome-extension-developer-tools|aar|2.0.4
swagger-snippets|adi|0.0.1
codesnap|adp|1.3.4
vscode-nginx-conf|ahm|0.3.2
numbered-bookmarks|ale|8.4.0
project-manager|ale|12.7.0
vscode-sqlite|ale|0.14.1
laravel-extra-intellisense|ami|0.6.4
toml|be5|0.6.0
vscode-tailwindcss|bra|0.10.4
server-feed|Cik|0.0.1
laravel-goto-view|cod|1.3.11
doxdocgen|csc|1.4.0
dart-code|Dar|3.80.0
flutter|Dar|3.80.0
vscode-eslint|dba|2.4.2
javascript-ejs-support|Dig|1.3.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
laravel-create-view|gli|0.0.6
go|gol|0.40.1
rest-client|hum|0.25.1
laravel-blade-wrapper|IHu|1.0.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.28.0
remote-wsl|ms-|0.81.8
sqltools|mtx|0.28.1
sqltools-driver-mysql|mtx|0.6.0
sqltools-driver-pg|mtx|0.5.2
sqltools-driver-sqlite|mtx|0.5.0
laravel-goto-components|nao|1.2.0
laravel-blade|one|1.34.0
laravel-extension-pack|one|1.2.0
laravel5-snippets|one|1.17.0
laravel-jump-controller|pgl|0.0.33
prisma|Pri|5.7.1
java|red|1.25.1
LiveServer|rit|5.7.9
laravel-artisan|rya|0.0.31
vscode-blade-formatter|shu|0.24.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.13.5
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.43.0
volar|Vue|1.8.27
scss-to-css|yut|3.2.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vsjup518:30340749
vshan820:30294714
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
f6dab269:30613381
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259
cp7184t3:30927821

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by exmadesu** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Wow i can't believe that, just installed [latest VS Code insiders build](https://code.visualstudio.com/insiders/) and everything just working now, Both `Copy` + `Paste` functionality on my old VSCode.

Yeah you are right, maybe today i should take a fresh install one. Thank you for the link, now i know how to dealing with extension.

Happy New Year,
