### ISSUE TITLE
copilot still 3.5

### ISSUE THREAD

**Issue by emicovi** [microsoft/vscode#201793]
Type: <b>Bug</b>

I thought copilot would use latest 4 turbo model? it still uses 3.5 turbo

VS Code version: Code - Insiders 1.86.0-insider (df8db3a75a49b85c9636530a3557cdbc639f7bdc, 2024-01-01T05:37:30.691Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id 4605076d-0625-412b-ae69-ef3edf2ee709|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.2
gitlens|eam|2024.1.404
copilot|Git|1.144.631
copilot-chat|Git|0.12.2023122001
java|red|1.26.2024010208
vs-code-prettier-eslint|rve|5.1.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.55.2023121302
vscode-java-dependency|vsc|0.23.2023120100
vscode-java-pack|vsc|0.25.2023121402
vscode-java-test|vsc|0.40.2023122104
vscode-maven|vsc|0.43.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vsc_aa:30263845
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
a9j8j154:30646983
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by roblourens** [comment]
Copilot or Copilot Chat? Chat is using GPT-4

**Comment by roblourens** [comment]
Nothing changed in the past few days
