### ISSUE TITLE
triple backticks with language specifiers rendering 

### ISSUE THREAD

**Issue by hros** [microsoft/vscode#201731]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Using triple backticks with language specifiers (e.g., "\`\`\`python" or "\`\`\`bash") displays two additional lines (before and after the code block) starting with a vertical bar (sort of opening and closing parentheses)

For example, the following markdown:

> \#\# Preparation
> Install the tensorflow datasets package (tfds) to load the *MNIST* dataset
> \`\`\`bash
> pip install tensorflow_datasets
> pip install tensorflow
> \`\`\`
> 
> Download the *Radon* dataset
> \`\`\`python
> import tensorflow_datasets as tfds
> ds, info = tfds.load('mnist', split='train', shuffle_files=True)
> \`\`\`

It is displayed with the additional markers; see screenshot:
<img width="494" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/2613469/657d7937-2b82-4df0-9b08-18977cea4212">

In Jupyter (or Jupyter-Lab) these markers are not displayed

### VS Code Version

Version: 1.85.1 (user setup) Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2 Date: 2023-12-13T09:49:37.021Z Electron: 25.9.7 ElectronBuildId: 25551756 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Windows_NT x64 10.0.22635

### Jupyter Extension Version

v2023.11.1003402403

### Coding Language and Runtime Version

Python 3.11

### Language Extension Version (if applicable)

python: v2023.22.1

### Running Jupyter locally or remotely?

Remote

**Comment by mjbvz** [comment]
I believe this has already been fixed in VS Code insiders:

![Image](https://github.com/microsoft/vscode/assets/12821956/f7247126-8316-4f4e-817f-91617f3d588a)

**Comment by mjbvz** [comment]
Oh actually still broken for notebooks but fixed for normal markdown. Will also port fix to notebooks

**Comment by TylerLeonhardt** [comment]
<img width="733" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/95768b06-c283-467d-a42b-edee5d1c29f7">

looks good!
