### ISSUE TITLE
Don't show non-actionable Install buttons when extension has no release version

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/vscode#201730]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1 (Universal)
- OS Version: macOS Ventura 13.2 (22D49)

Steps to Reproduce:

1. Search for an extension that has no release version, such as [Panda CSS](https://marketplace.visualstudio.com/items?itemName=chakra-ui.panda-css-vscode)
2. Click its _Install_ button
3. Get the non-actionable popup saying _"Can't install release version of 'chakra-ui.panda-css-vscode' extension because it has no release version."_

This is a poor user experience. There's no indication anywhere that the user is supposed to click the little down arrow next to _Install_ and select _Install Pre-Release Version_. Plus, once that's installed, a similarly non-actionable _Switch to Release Version_ button shows.

Suggestion: either...
* If it's knowable ahead of time that there isn't a release version, only show an _Install Pre-Release Version_ button
* If it's not, add an offer to install the pre-release version to the dialog/modal

![Screenshot of a VS Code window open to the Panda CSS entry in the marketplace. It's marked as Pre-Release and Preview, and there's an Install button.](https://github.com/microsoft/vscode/assets/3335181/49663f35-28c6-4852-a8c1-fd4c9a77073e)

Video recording: https://github.com/microsoft/vscode/assets/3335181/59bc1d85-2b94-4cca-835c-de1705c7c960 [^1]

[^1]: Video description: A VS Code window open to the Panda CSS entry in the marketplace. The user first tries to click 'Install', but gets a popup saying "Can't install release version of 'chakra-ui.panda-css-vscode' extension because it has no release version.". The user then clicks the down arrow next to 'Install' and 'Install Release Version' to the same result. The user then clicks the down arrow next to 'Install' and 'Install Pre-Release Version' which does install the extension correctly. The page now shows a 'Switch to Release Version' button, which when clicked, gives the same failure modal.

**Comment by sandy081** [comment]
<img width="246" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/6a3c0a1a-dbcb-4058-be8d-c18b94a64279">
