### ISSUE TITLE
emmet is not working

### ISSUE THREAD

**Issue by ciwyaitd** [Microsoft/vscode#20177]
Tab is not working in html file after update just now.

- VSCode Version: 1.10.0-insider eff9148502fd3edf42573beb16006bee533c3cf9
- OS Version: 10.11.6

**Comment by ciwyaitd** [comment]
![image](https://cloud.githubusercontent.com/assets/9427862/22728905/42826f66-ee1b-11e6-8238-2fb6f6e2cce7.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/20209
