### ISSUE TITLE
Custom theme dosen't work after 1.9 update

### ISSUE THREAD

**Issue by thonymg** [Microsoft/vscode#20175]
Hello, after the last update i have some strange bug in my theme. 

i create a custom theme for elixir & Js ... and after the update

![image](https://cloud.githubusercontent.com/assets/8509486/22726751/2423e840-ede6-11e6-8975-fa3ef911bfac.png)

- VSCode Version:
1.9
- OS Version:
Windows 10

Link to the [theme package](https://marketplace.visualstudio.com/items?itemName=thonymg.Darkplusix)

**Comment by Tyriar** [comment]
This happened because we weren't following textmate parsing rules properly before, you'll need to redo parts of you theme. More information is in this [blog post](https://code.visualstudio.com/blogs/2017/02/08/syntax-highlighting-optimizations).
