### ISSUE TITLE
Markdown Formatter Breaks Code

### ISSUE THREAD

**Issue by tdkbzh** [microsoft/vscode#201725]
I use the "format code on save" feature of vscode.

The vscode markdown formatter has a breaking behavior when markdown files are used with mustache templating inside.

### Current behavior

The markdown formatter takes the initiative to remove some backticks when deemed unnecessary.

`file.md` (before code formatting):

    ````
    hello
    ````

`file.md` (after code formatting):

    ```
    hello
    ```

### Problem

This behavior becomes problematic when you insert mustache variables that contains markdown code blocks (which the formatter is not aware of):

`file.md` (before code formatting):

    ````
    {{ markdownCodeBlockSayingHello }}
    ````

`file.md` (after code formatting):

    ```
    {{ markdownCodeBlockSayingHello }}
    ```

Output after mustache rendering, resulting in a broken markdown code:

    ```
    ```
    hello
    ```
    ```

### Proposed fix

Extra-backticks should always be preserved when formatting markdown:

    ````
    hello
    ````

**Comment by mjbvz** [comment]
VS Code doesn't include a built-in markdown formatter. Please file this against your markdown formatting extension
