### ISSUE TITLE
Debugging QOL improvement ideas

### ISSUE THREAD

**Issue by sparecycles** [microsoft/vscode#201753]
## Run controls widget
Currently: located "somewhere in the top section of the window", but nowhere feel ideal.  (on OSX, it can even be moved "under" the close/expand/minimize traffic lights buttons on the top left of the window.)

<img width="226" alt="image" src="https://github.com/microsoft/vscode/assets/719818/9b7c4591-2f1e-4fab-b6a4-bf572d104763">

I would like the option to dock it into the variables/watch/callstack section.

## Breakpoints

Would be awesome if I could drag them (maybe hold down alt and drag to clone them).   Sounds silly but consider conditional breakpoints, which require a `click`-`right-click`-`select "edit breakpoint"`-`enter the conditional` to add, and once added, removing it requires confirmation (by default, anyway).
![image](https://github.com/microsoft/vscode/assets/719818/1eb8b78e-a51d-4997-859f-1984cded0dfc)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/88227
