### ISSUE TITLE
keyboard shortcut for opening menus stopped working

### ISSUE THREAD

**Issue by mkimberling** [microsoft/vscode#201751]
Type: <b>Bug</b>

I'm not longer able to open menus using any ALT+ keyboard shortcut.  When I press the Alt key, an underscore appears beneath the F in the File menu but pressing Alt+F does not actually open the menu.  Nothing happens.  I'm no longer able to open any of the menus with a keyboard shortcut:
alt+f doesn't open the File menu
alt+e doesn't open the Edit menu
etc

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz (24 x 2993)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.71GB (77.27GB free)|
|Process Argv|--crash-reporter-id 52669eef-de6a-4997-b0ac-5dc96cd5b01b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
cruncher-debugger|cod|0.0.1-cod-main.0+000000000
vscode-eslint|dba|2.4.2
copilot-chat|Git|0.11.1
vscode-peacock|joh|4.2.2
cmake-language-support-vscode|jos|0.0.9
vscode-rust|kal|0.4.2
perforce|mjc|4.15.7
csharp|ms-|2.14.8
vscode-dotnet-runtime|ms-|2.0.0
isort|ms-|2023.10.1
mypy-type-checker|ms-|2023.6.0
pylint|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1003402403
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.81.8
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2023.8.0
jenkins|p1c|0.1.0
vscode-commons|red|0.0.6
vscode-xml|red|0.26.1
fastbuild|Ros|1.0.0
jinjahtml|sam|0.20.0
even-better-toml|tam|0.19.2
debug|web|0.26.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
f6dab269:30613381
0bi6i642:30917235
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by sbatten** [comment]
Can you share a screen recording of your experience? Does this happen with all extensions disabled?

**Comment by mkimberling** [comment]
I had to reboot my computer yesterday.  Now the issue is no longer happening.  I'll update this issue if it comes back and I have any more information I can share.
