### ISSUE TITLE
add command to toggle line numbers

### ISSUE THREAD

**Issue by aliva** [Microsoft/vscode#20176]
- VSCode Version:
```
Version 1.9.0
Commit 27240e71ef390bf2d66307e677c2a333cebf75af
Date 2017-02-02T08:21:13.228Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```
- OS Version: ubuntu 16.10

I really like to have a command to toggle line number, normally I like to disable line numbers, they are a waste of monitor size
but when debugging or using linter I want to enable line numbers temporary

**Comment by rebornix** [comment]
It's a good extension candidate and you can follow https://medium.com/hack-visual-studio-code/toggle-any-setting-in-vs-code-using-keyboard-shortcut-arguments-cdb5ddc56955 to get your preferred extension to archive that.

**Comment by aliva** [comment]
good enough for me :+1:

**Comment by mjbvz** [comment]
Closing as this can be implemented by an extension. Please try the extension that @rebornix linked to
