### ISSUE TITLE
Allow an action with a specific group to be `isHiddenByDefault: true`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#201782]
I think `isHiddenByDefault` is pretty cool for actions because this allows us to give the user full control which actions show primary and which actions show in the "..." menu. I would like to adopt this for some of my actions in the editor area, however there seems to be a limitation: I cannot pick a custom `group` that is not `navigation` to get this to work.

Could we allow an action with a custom `group` to still get promoted to the `navigation` group if the user picks as such?

Code example which I would like to see working:

```ts
MenuRegistry.appendMenuItem(MenuId.EditorTitle, {
	command: {
		id: CLOSE_EDITORS_IN_GROUP_COMMAND_ID,
		title: localize('closeAll', "Close All")
	},
	group: '5_close',
	order: 10,
	isHiddenByDefault: true
});
```

//cc @sandy081

**Comment by jrieken** [comment]
> Could we allow an action with a custom group to still get promoted to the navigation group if the user picks as such?

That's not really how this works. Hiding means that the hidden command goes into the overflow menu but stays in its group, e.g the navigation or primary group now overflows irrespective of its size. You would need to have all these groups be rendered as primary to get this to work.

**Comment by jrieken** [comment]
> So you cannot have multiple groups appear as primary and others overflowing.

That's not right. Any group and also many groups can be primary. Check the [raw](https://github.com/microsoft/vscode/blob/358f15fb9bbcd59d83984d9ffca6fdbd82ea5866/src/vs/platform/actions/browser/menuEntryActionViewItem.ts#L46 ) implementation and how this is exposed via `IToolbarRenderOptions#primaryGroup`

**Comment by bpasero** [comment]
Nice, that I did not know!
