### ISSUE TITLE
Source Control Tree stay collapsed

### ISSUE THREAD

**Issue by Cedric-LE** [microsoft/vscode#201797]
Type: <b>Bug</b>

I simply switched to a branch, perhaps with a rather long name. On this branch, the source control tree doesn't open and remains in a collapsed state.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (12.08GB free)|
|Process Argv|--crash-reporter-id 92b4f21c-334b-48e0-b831-c3fb9f922356|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nginx-conf|ahm|0.3.2
path-intellisense|chr|2.8.5
vscode-markdownlint|Dav|0.53.0
vscode-eslint|dba|2.4.2
gitlens|eam|14.6.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
vscode-nginx-conf-hint|han|0.3.0
react-component|jer|1.1.0
svg|joc|1.5.3
vscode-styled-components|jpo|1.7.0
vscode-docker|ms-|1.28.0
csdevkit|ms-|1.1.16
csharp|ms-|2.14.8
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26
vscode-kubernetes-tools|ms-|1.3.15
remote-containers|ms-|0.327.0
remote-wsl|ms-|0.81.8
powershell|ms-|2023.8.0
nginx-formatter|ray|0.0.13
vscode-yaml|red|1.14.0
vscode-nginx|sha|0.6.0
vscode-asciidoc|sta|0.0.3
vscode-styled-components|sty|1.7.8
vscode-nginx|wil|0.7.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
vsjup518:30340749
vshan820:30294714
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
f6dab269:30613381
2i9eh265:30646982
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by lszomoru** [comment]
@Cedric-LE, are you able to reproduce the issue with the latest VS Code Insiders release?

**Comment by Cedric-LE** [comment]
> @Cedric-LE, are you able to reproduce the issue with the latest VS Code Insiders release?

It can still be reproduced withe latest VS Code Insiders Release. I attach a film. My branch name:
bugfix-CAR-5045-loading-compositions-component-order-messed-up-when-selecting-lumped-from
![sc-tree-issue](https://github.com/microsoft/vscode/assets/81676601/e6e7284d-823f-44a9-8e6c-835d8722bd51)

**Comment by lszomoru** [comment]
@Cedric-LE, thanks for the recording. Could you also please share the contents of the git output window which you can access by invoking the "Git: Show Git Output" command from the command palette. Thanks!

**Comment by Cedric-LE** [comment]
> @Cedric-LE, thanks for the recording. Could you also please share the contents of the git output window which you can access by invoking the "Git: Show Git Output" command from the command palette. Thanks!
> 
> Also, can you still reproduce the issue if you set the following settings to `never`:
> 
> * scm.showIncomingChanges
> * scm.showOutgoingChanges

2024-01-08 11:34:18.008 [info] fatal: failed to stat 'refs/heads/bugfix-CAR-5045-loading-compositions-component-order-messed-up-when-selecting-lumped-from...refs/remotes/origin/bugfix-CAR-5045-loading-compositions-component-order-messed-up-when-selecting-lumped-from': Filename too long

**Comment by lszomoru** [comment]
@Cedric-LE, what version of VS Code are you using? 
Are you using the latest VS Code Insiders release?  
```
Version: 1.86.0-insider (Universal)
Commit: 4caba0473af34a2b128cedc46f6b13316aae9226
Date: 2024-01-08T05:37:49.269Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0
```

**Comment by Cedric-LE** [comment]
Version: 1.86.0-insider (user setup)
Commit: 4caba0473af34a2b128cedc46f6b13316aae9226
Date: 2024-01-08T05:36:56.355Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by lszomoru** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/200636
