### ISSUE TITLE
Since I Played the launching game my computer isn't back to normal

### ISSUE THREAD

**Issue by Distractmeplz** [microsoft/vscode#201746]
Type: <b>Bug</b>

Please do something it(s pissing me off that there still is some issues based on what the game made to my computer

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (7.89GB free)|
|Process Argv|--crash-reporter-id 4e4d6e13-cd17-492a-9211-cb2782f1ea2c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
dadroit-json-generator|Dad|1.1.7
vscode-eslint|dba|2.4.2
xml|Dot|2.5.1
gitlens|eam|2023.12.2104
vscode-test-explorer|hbe|2.21.1
rwxml-lang-serv|mad|0.42.0
vscode-kubernetes-tools|ms-|1.3.15
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
hexeditor|ms-|1.9.12
test-adapter-converter|ms-|0.1.8
vscode-yaml|red|1.14.0
vscode-php-test-explorer-docker|sat|1.0.5
c-cpp-flag-debugging|uts|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyonecf:30548226
89544117:30613380
a9j8j154:30646983
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30928863
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184t3:30927821

```

</details>

**Comment by roblourens** [comment]
I'm not sure this is related to VS Code, if it is, please more detail and describe exactly what is happening and steps for us to reproduce it.
