### ISSUE TITLE
Floating Terminal

### ISSUE THREAD

**Issue by hoangsep** [microsoft/vscode#201768]
Is it possible to have floating terminal? The built-in terminal is convenient that I can just Ctrl-click to jump to a file/line, but it takes some screen space.
I have multiple monitor and would like to float the terminal to a side monitor to be able to see more output.

**Comment by hoangvunguyenbk** [comment]
+1, I really need this feature as well.

**Comment by meganrogge** [comment]
You can already do this. Run this command :
![Screenshot 2024-01-04 at 11 10 09 AM](https://github.com/microsoft/vscode/assets/29464607/03d4599d-16e9-43df-903c-0cd47ffee738)

**Comment by hoangsep** [comment]
@meganrogge Which version are you running? I am 1.85.1 on Linux and I don't have this command, only moving to the editor area. After that I can move from the editor to a new window but the new window would blink/flash sometimes. I am not sure why.

**Comment by DavidHJong** [comment]
i'm using 1.85.2 on windows 10. no blink/flash problem. maybe you can try on that.

**Comment by DavidHJong** [comment]
i'm using 1.85.2 on windows 10. no blink/flash problem. maybe you can try the new version. @hoangsep

**Comment by hoangsep** [comment]
@DavidHJong still flashing on 1.85.2 on Linux :(
