### ISSUE TITLE
Multi-repository style also for single repository

### ISSUE THREAD

**Issue by aureliusm** [microsoft/vscode#201721]
I really like the way source control shows repositories when I have multiple open repositores in a single project like so:
<img width="595" alt="image" src="https://github.com/microsoft/vscode/assets/4232702/8ba6bbba-708c-46ba-a0ea-1e8db4b831e7">

You immediately see the repository name, current branch with all options on the right side.

I would love to have the same "view" or "style" of viewing a repository even if there is only a single one - so the name is still visible along with current branch etc. Currently it all disappears into the top line and it is harder for me to parse which branch is active - I have to look at the bottom to the status bar:
<img width="600" alt="image" src="https://github.com/microsoft/vscode/assets/4232702/47c2fd30-a9c0-43ed-adf7-1f68ef1ea510">

Maybe already possible, but can't find it :)

**Comment by lszomoru** [comment]
Please use the `scm.alwaysShowRepositories` setting. Thanks!
