### ISSUE TITLE
 Cannot set property 'value' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#20180]
Issue Id: <b>02b666c8-2094-a8ef-d410-903af558fb1a</b><br /><br />*Versions* <br />- 1.9.0<br />*Stack* <br />TypeError: Cannot set property 'value' of undefined<br />[/vs/workbench/parts/preferences/common/preferencesModels.ts#L258:20 (value)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/preferences/common/preferencesModels.ts#L258:20 (value))<br />[/vs/base/common/json.ts#L995:37 (visitFunction)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/base/common/json.ts#L995:37 (visitFunction))<br />[/vs/base/common/json.ts#L1049:3 (onLiteralValue)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/base/common/json.ts#L1049:3 (onLiteralValue))<br />[/vs/base/common/json.ts#L1172:11 (parseString)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/base/common/json.ts#L1172:11 (parseString))<br />[/vs/base/common/json.ts#L1098:8 (parseValue)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/base/common/json.ts#L1098:8 (parseValue))<br />[/vs/base/common/json.ts#L1122:8 (parseProperty)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/base/common/json.ts#L1122:8 (parseProperty))<br />[/vs/base/common/json.ts#L1170:11 (parseObject)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/base/common/json.ts#L1170:11 (parseObject))<br />[/vs/base/common/json.ts#L1182:6 (parseValue)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/base/common/json.ts#L1182:6 (parseValue))<br />[/vs/workbench/parts/preferences/common/preferencesModels.ts#L378:2 (visit)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/preferences/common/preferencesModels.ts#L378:2 (visit))<br />[/vs/workbench/parts/preferences/common/preferencesModels.ts#L219:8 (parse)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/preferences/common/preferencesModels.ts#L219:8 (parse))<br />

**Comment by sandy081** [comment]
Duplicates #20105
