### ISSUE TITLE
Unable to write file... Error: ENOENT: no such file or directory.

### ISSUE THREAD

**Issue by kyleacuna** [microsoft/vscode#201887]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.1 
- OS Version: Windows_NT x64 10.0.22631

Can someone help me with this? This error happens to every file inside the folder on my github repositories.

![image](https://github.com/microsoft/vscode/assets/134776227/16362094-d6d3-4d3a-a777-3c3740e700c0)

**Comment by lramos15** [comment]
Starting with @joyceerhl as the error in the modal says something about remotehub global storage

**Comment by joyceerhl** [comment]
I can reproduce this. You can temporarily work around this by not using `|` in the filename.

**Comment by joyceerhl** [comment]
Actually, it looks like the reason for this is that the `|` character (U+007C) is [not permitted](https://en.wikipedia.org/wiki/Filename#In_Windows) on Windows. You can use the `∣` (U+2223) character instead.

**Comment by kyleacuna** [comment]
Thanks! I can confirm that this error is now fixed by using your suggestion (use the ∣ (U+2223) character instead.) Thank you!
