### ISSUE TITLE
The glob pattern given to createFileSystemWatcher is matched against the full fs path

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#20184]
Like most tools that ask for user input in the form of the glob, it should be matched against the relative path to a reference, in this case the workspace.

Example:

- I have a `log` file in my `/Users/joao/what` workspace .
- `workspace.createFileSystemWatcher('log')` doesn't give me any events
- `workspace.createFileSystemWatcher('**/log')` does, because the glob is matched against `/Users/joao/what/log`.

I find that very confusing especially given that `createFileSystemWatcher` is called upon a `workspace` object.

**Comment by joaomoreno** [comment]
It might be too late to fix this... so I recommend writing up a better documentation around that method so users know what to provide in that parameter.

**Comment by jrieken** [comment]
yeah, we can think about an option...

**Comment by jrieken** [comment]
Actually won't fix considering that we will soon support multi root workspaces
