### ISSUE TITLE
Problem Text is Cropped (it Doesn't Scroll or Wrap)

### ISSUE THREAD

**Issue by jwalkerinterpres** [microsoft/vscode#201807]
**Does this issue occur when all extensions are disabled?:** Yes

- **VS Code Version:**  1.85.1 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2 arm64
- **OS Version:** MacOS

**Steps to Reproduce:**

1.  Split your editor (or just have a small monitor)
2. Get  "problem" (eg. TypeScript error) in your code with long text
3. Hit the `F8` key to go to that problem
4. Try to read the problem's text: you can't (because it exceeds the screen width)

**Proposed Solution:** This is a pretty standard UI problem, and the standard solution (eg. on similar long web text) is either to wrap the text (and extend it on to further lines of UI), or to add a scroll bar to let the user scroll to the hidden parts of the text.

Currently the UI allows neither, and it doesn't even allow for "hack scrolling" (one typical workaround to this problem is to highlight the text starting on the left, and drag the cursor past the right-border ... but again, even that doesn't work in VS Code).

**Comment by jwalkerinterpres** [comment]
Here's an example:
![cropped](https://github.com/microsoft/vscode/assets/152227747/d8e33973-6bd2-4448-8d22-13cddacb41dc)

**Comment by bhavyaus** [comment]
@sandy081 could you please help redirect this if you're not the correct audience? Thank you.

**Comment by jrieken** [comment]
There should be a scrollbar once you move over the contents, like so:

https://github.com/microsoft/vscode/assets/1794099/6d1a7542-ca6f-4fb0-8583-a3d657ab9bc2

**Comment by jwalkerinterpres** [comment]
That's great ... but as you can see from my screenshot, there was no scroll bar.  If there had been, I never would have filed this ticket.

**Comment by jwalkerinterpres** [comment]
Testing it now (with a different error), I _do_ see a scrollbar when I mouseover the error pane.  I suspect that something must have gone wrong previously with the "show slider when you mouseover" logic.

Since I can no longer reproduce the problem, I'm not sure what to do with the ticket: maybe close it, but remember it so that you believe the reporter if they report something similar?

**Comment by jrieken** [comment]
It's not a matter of believing but reproducing, without steps I cannot trust my fixing

**Comment by jwalkerinterpres** [comment]
Understood, but at _some_ point, when X number of users report an unreproducible bug, you stop saying "we can't reproduce, so we'll do nothing", and you starting looking into potential causes ... right?

I don't know what X is, but I'm just saying ... X is now X - 1 with this bug report :)

**Comment by jrieken** [comment]
not actionable
