### ISSUE TITLE
Where's the Debug Actions?

### ISSUE THREAD

**Issue by mirusky** [microsoft/vscode#201836]
I'm not able to find the vscode debugger actions on top anymore, it just disapeared: 
![image](https://github.com/microsoft/vscode/assets/54698990/adeb2c3b-79f6-4821-87ff-8158545da63e)

What I'm looking for:
![image](https://github.com/microsoft/vscode/assets/54698990/4cd3041f-fb67-4fc8-9413-680015ac4c2f)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.85.1 (system setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
- OS Version: Windows 10

Steps to Reproduce:

1. Write any code (JS, Go, Ruby)
2. Press F5 to start debug
3. See the Debug action not showing up

**Comment by roblourens** [comment]
Maybe you've set the `"debug.toolBarLocation"` setting to move it?

**Comment by mirusky** [comment]
I've oppened settings.json and It's not setted. I've also tried to use debug.toolBarLocation with `commandCenter`, `docked` and `floating` but it didn't change anything. 

Look's like it's disabled / hidden, in every case.

**Comment by mirusky** [comment]
Correction:

`Docked` is showing, but directly in the debug panel, other options is not showing up in anywhere.

![image](https://github.com/microsoft/vscode/assets/54698990/9e13894a-9e38-47c2-ba68-56e3ef495be6)

**Comment by ArturoDent** [comment]
Are you by chance using two+ monitors?

**Comment by mirusky** [comment]
No, just one on Laptop.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/204265#issuecomment-1931236889
