### ISSUE TITLE
Hot exit doesn't retain custom language selections between sessions

### ISSUE THREAD

**Issue by zaid-khan** [Microsoft/vscode#20189]
- VSCode Version:1.9.0
- OS Version:6.3 (Windows 8.1 x64)

Steps to Reproduce:

1. Select the Language for a new document but don't save the document and close Code.
2. Open Code, now the language previously selected is lost and Plain Text is selected again.

**Comment by bpasero** [comment]
@zaid-khan @Tyriar I cannot reproduce and I fixed this for the 1.9 release, so I am confused. Can you maybe share a video or screenshots what you do and how it behaves?

**Comment by zaid-khan** [comment]
https://youtu.be/-CcsJDnx3_Q

YouTube<https://youtu.be/-CcsJDnx3_Q>
youtu.be
and share it all with friends, family, and the world on YouTube.




________________________________

**Comment by bpasero** [comment]
@zaid-khan thanks, this only happens because the window is an "empty" window without associated workspace. In that case we do not preserve any view state.

I would say we can close this as duplicate of https://github.com/Microsoft/vscode/issues/207

**Comment by Tyriar** [comment]
@bpasero :+1:
