### ISSUE TITLE
Ctrl+Space support for the integrated terminal

### ISSUE THREAD

**Issue by Leon99** [Microsoft/vscode#20188]
- VSCode Version: 1.9.0
- OS Version: Win10.0.14393

Steps to Reproduce:

1. Type part of a PS command, i.e. `Test-`, in the integrated terminal and press Ctrl+space.
2. Nothing happens, though a standalone powershell.exe would show a list of possible commands.

**Comment by Tyriar** [comment]
@daviwil any ideas of whether this would be possible in vscode?

**Comment by daviwil** [comment]
If the user has PSReadLine loaded in PowerShell, Ctrl+Space will print out a list of all matching commands.  I'll make sure this also works for my integrated PS console which is coming soon.

However, I wonder if Leon is actually asking for a completion list like what you get in PowerShell ISE's terminal:

![image](https://cloud.githubusercontent.com/assets/79405/22785392/f59ca40a-ee88-11e6-966e-aadb976eb19e.png)

It'd be pretty sweet if we could invoke the completion UI from the terminal, but I'm not sure how much effort that would take :)

**Comment by Tyriar** [comment]
Yeah I don't see this happening if it's a popup like that, going to close this off. Thanks @daviwil

**Comment by Leon99** [comment]
Hmm no I've specifically pointed that I'm looking for the behaviour that I see in powershell.exe:
![image](https://cloud.githubusercontent.com/assets/6840381/22805495/ef754318-ef71-11e6-990c-41d65ef70603.png)
That won't appear in the integrated terminal for me. So I'm not sure what's the reason why it's closed - is it because it's not going to happen before @daviwil releases the 'integrated PS console' (whatever that means) or I'm doing something wrong? BTW I thought that PSReadLine is integrated in Win10, no?

**Comment by daviwil** [comment]
That completion display is coming from PSReadline, so there must be something preventing PSReadline from handling that keybinding.

**Comment by Tyriar** [comment]
It looks like ctrl+space is being passed to xterm.js as the NUL key, not sure what we're meant to pass to winpty to make PowerShell behave as it's not xterm.

**Comment by Leon99** [comment]
1. I'm still wondering why it's closed?
2. Not sure if it helps/relevant, but anyway - I've noticed that Ctrl+Backspace doesn't work either.

**Comment by Tyriar** [comment]
This is definitely an upstream issue so it probably belongs here https://github.com/sourcelair/xterm.js, I'm not sure it's possible to implement this though since powershell doesn't implement xterm? We would need to know what powershell expects to trigger this.
