### ISSUE TITLE
Menubar always visible on startup, regardless of setting

### ISSUE THREAD

**Issue by electricduck** [Microsoft/vscode#20186]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-color|anseki|0.2.2|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.6|
|vscode-npm-script|eg2|0.1.8|
|code-runner|formulahendry|0.6.6|
|rest-client|humao|0.12.1|
|word-count|hypnoes|0.1.1|
|vscode-doiuse|mrmlnc|1.3.0|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.9.0|
|vscode-docker|PeterJausovec|0.0.11|
|qub-msbuild|qub|0.5.0|
|Ruby|rebornix|0.10.4|
|markdown-all-in-one|yzhang|0.2.0|

---

Steps to Reproduce:

1. Include `"window.menuBarVisibility": "hidden"` in `settings.json`
2. Observe menubar hides after saving settings
3. Close application
4. Re-open
5. **Observe menubar shows again after startup, even with the setting in-tact**

Additional Notes:
- Menubar toggle stops working
- To make the menubar invisible again, I have to go to settings, yank the setting, save `settings.json`, re-add the setting, and then save again

**Comment by electricduck** [comment]
Hm, this may be an invalid ticket; is `hidden` still a valid option? `toggle` works as expected.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/19777
