### ISSUE TITLE
Consider distinguishing between conditional breakpoints and regular breakpoints in the breakpoints pane

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#2018]
We might need a way to identify conditional breakpoints in the breakpoint panel as without hovering over the breakpoints, there is no way to tell which have conditions attached to them. A few thoughts off the top of my head
- We group the list of breakpoints into two groups, regular and conditional.
- We draw a label ‘conditional’ next to the breakpoint
- We draw as much of the expression as can fit in next to the breakpoint (this has problems due to the lack of available screen real estate)

**Comment by isidorn** [comment]
Option 3 will not work for breakpoints that have long paths inside a workspace – we show the path in the breakpoint widget and there will be no place in the breakpoint pane
We experiment with first two ideas. More ideas are welcome
