### ISSUE TITLE
 Cannot read property 'done' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#20181]
Issue Id: <b>5e664130-e668-3ea9-7422-a3cbaa901748</b><br /><br />*Versions* <br />- 1.9.0<br />*Stack* <br />TypeError: Cannot read property 'done' of undefined<br />[/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L302:92 (done)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L302:92 (done))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L118:26 (call)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/base/common/event.ts#L118:26 (call))<br />[/vs/workbench/parts/preferences/browser/preferencesWidgets.ts#L338:49 (fire)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/preferences/browser/preferencesWidgets.ts#L338:49 (fire))<br />[/vs/base/browser/ui/widget.ts#L16:102 (listener)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/base/browser/ui/widget.ts#L16:102 (listener))<br />

**Comment by isidorn** [comment]
Fixed in latest
