### ISSUE TITLE
Infinite "Initializing JS/TS language features"

### ISSUE THREAD

**Issue by c0nf1gur4t0r** [microsoft/vscode#201858]
Type: <b>Bug</b>

I'm not using Typescript in my solution, but anyway the Code is blocking my IntelliCode/IntelliSense/IntelliWhatever because the "language features" is initializing infinitely.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 6.6.8-200.fc39.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 4065)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 2|
|Memory (System)|31.08GB (21.79GB free)|
|Process Argv|--unity-launch --crash-reporter-id 0c76bf12-1fb0-4316-8dac-972d2fb64d7b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
node-essentials|afr|1.1.0
vscode-eslint|dba|2.4.2
docs-preview|doc|1.0.3
gitlens|eam|14.6.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.2.2
vscode-docker|ms-|1.28.0
vscode-edge-devtools|ms-|2.1.3
vscode-kubernetes-tools|ms-|1.3.15
remote-containers|ms-|0.327.0
remote-wsl|ms-|0.81.8
azure-account|ms-|0.11.6
vsliveshare|ms-|1.0.5900
vscode-jest|Ort|5.2.3
vscode-yaml|red|1.14.0
bash-beautify|sha|0.1.1
prettier-plus|Shu|3.0.0
vscode-icons|vsc|12.6.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30899288
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
f6dab269:30613381
vscrp:30673768
a9j8j154:30646983
0bi6i642:30917235
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If it does, please provide steps to reproduce the issue
