### ISSUE TITLE
Angular 7 code spaming false positive errors

### ISSUE THREAD

**Issue by EduardoKSibata** [microsoft/vscode#201877]
Type: <b>Bug</b>

I have an Angular 7 project and recently, visual code start to spaming some errors like "'CommonModule' does not appear to be an NgModule class".
The project build and run as spected, though the errors are very anoyng, I just don't know wich error is really an error or not.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (1.45GB free)|
|Process Argv|--crash-reporter-id e529d18c-72bb-4d4f-8312-1c2676a67977|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|17.0.3
path-intellisense|chr|2.8.5
prettier-vscode|esb|10.1.0
Angular-BeastCode|Mik|10.0.3
nested-comments|phi|4.0.1
csharp2ts|raf|0.0.26
sass-indented|syl|1.8.28

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vshan820:30294714
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
f6dab269:30613381
a9j8j154:30646983
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184t3:30927821

```

</details>

**Comment by mjbvz** [comment]
Please file this against your angular extensions

**Comment by EduardoKSibata** [comment]
Right, if someone find this in the future, was the "Angular Language Services" extension. Run fine for angular 9 projects, but spam nosense errors for angular 7 projects. Btw, I disabled the extension and now everything is running as expected.
