### ISSUE TITLE
Attempting to launch code OSS from Windows throws terminal process error

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/vscode#201861]
Attempted to follow steps on https://github.com/microsoft/vscode/wiki/How-to-Contribute in order to run code OSS on windows. Tried windows dev boxes, Windows 11 via parallels on Mac ARM, Windows 11, but still getting the error: 
<img width="879" alt="Screenshot 2024-01-04 at 11 59 24 PM" src="https://github.com/microsoft/vscode/assets/62267334/8a080629-1f04-47a9-9467-d7f0bf3f1264">
after following all steps in prerequisites

Steps to Reproduce:

1. Install git
2. Install node 18.18.1 from https://nodejs.org/en/blog/release/v18.18.1 (Checked box to install Tools for Native Modules)
3. Install Yarn
4. Install Python
5.  Installed Visual Studio Build Tools and checked Desktop Development with C++
6. cloned VS Code repo and run 'yarn'
7. Went to run and debug tab and tried to launch Code OSS
8. 
<img width="879" alt="Screenshot 2024-01-04 at 11 59 24 PM" src="https://github.com/microsoft/vscode/assets/62267334/3123e38a-6234-4ba6-81e8-318adbdbc863">
Nothing is launched

I followed the steps for Mac OS, and worked fine, not sure what Im doing wrong here.

**Comment by roblourens** [comment]
It looks like there was an error from yarn, is that right? Also can you run the command manually in a terminal?

**Comment by anthonykim1** [comment]
Yeah, I think that's right. When I ran re-installed all dependencies also some additional ones related to VS C++ stuff and ran yarn watch afterwards, it worked. Not sure what happened but glad it worked out :) Thank youu
