### ISSUE TITLE
copy line disapeared

### ISSUE THREAD

**Issue by savelkouls** [microsoft/vscode#201954]
Type: <b>Bug</b>

put the cursor on the line you want to copy
ctrl+c

go to the line where you want to insert the line you copied
ctrl+v

VS Code version: Code - Insiders 1.86.0-insider (1cfc62d46e6b9dd217cd485d7d4591136f421d70, 2024-01-05T16:21:29.391Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (48.03GB free)|
|Process Argv|--folder-uri file:///d%3A/harvel.xxx/x3-backend --crash-reporter-id fec4aa4f-71c2-45a6-aa22-946d06a020a9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-intelephense-client|bme|1.10.2
vscode-dashboard-window-colors|Dan|2.7.3
vscode-eslint|dba|2.4.2
gitlens|eam|2024.1.604
copilot|Git|1.145.0
copilot-chat|Git|0.12.2023122001
compare-folders|mos|0.24.1
azure-dev|ms-|0.8.0
vscode-azureappservice|ms-|0.25.1
vscode-azurecontainerapps|ms-|0.6.1
vscode-azurefunctions|ms-|1.13.1
vscode-azureresourcegroups|ms-|0.8.3
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.15.3
vscode-azurevirtualmachines|ms-|0.6.5
vscode-cosmosdb|ms-|0.20.0
autopep8|ms-|2023.9.13201008
python|ms-|2023.23.13541005
vscode-pylance|ms-|2023.12.102
jupyter|ms-|2024.1.2024010501
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.329.0
remote-wsl|ms-|0.81.8
azure-account|ms-|0.11.6
powershell|ms-|2024.1.0
vscode-node-azure-pack|ms-|1.2.0
heroku-command|pko|0.0.8
sqlite-viewer|qwt|0.3.13
vscode-xml|red|0.26.2023120208
robocorp-code|rob|1.14.0
robotframework-lsp|rob|1.11.0
pypi-assistant|twi|1.2.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30784851
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by savelkouls** [comment]
I did not look correctly, it actually pasts the line after the line selected instead of inserting it above.

**Comment by alexdima** [comment]
If you don't want for whole lines to be put in the clipboard when having no selection, you can configure `"editor.emptySelectionClipboard": false`
