### ISSUE TITLE
Split terminals don't align their first lines

### ISSUE THREAD

**Issue by FlyingWing12138** [microsoft/vscode#201946]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Windows 10 version 19045

Steps to Reproduce:

1. Launch VS code
2. Split terminal by clicking the button or by shortcuts

![image](https://github.com/microsoft/vscode/assets/43272496/d50c3d3d-7dfe-4837-9937-1aa1f4585a79)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
