### ISSUE TITLE
[json] Improve combining schemas not working with 'additionalProperties: false'

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#20193]
When combining schemas such as when multiple extensions have schemas for package.json we use 'allOf' to combine.
This works well as long as none of the schemas uses additionalProperties: false.

```json
{ 
    "allOf": [
        {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "bar": {
                    "description": "bar"
                },
                "foo": {
                    "description": "foo"                }
            }
        },
        {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "xoo": {
                    "description": "xoo"
                }
            }
        }

    ]
}

**Comment by HIAB-vesteel** [comment]
I believe this is the correct functionality of JSON Schema. 
When adding "additionalProperties": false, in combination of "allOf" it will not validate. When the first schema is validated in allOf it will fail as there are additionalProperties. After this the allOf validation is done.

This issue should probably be closed. If you need help and support could be found at json-schema github page. :)

**Comment by bpasero** [comment]
<img width="614" alt="image" src="https://user-images.githubusercontent.com/900690/182294667-c70b71e3-97c6-4562-aeb8-0d58c6a50ab3.png">

🤔

**Comment by aeschli** [comment]
It's working in May 2022, thus the milestone
