### ISSUE TITLE
open terminal but is empty

### ISSUE THREAD

**Issue by Handsomer** [microsoft/vscode#201972]
Type: <b>Bug</b>

in the bottom of vscode, cant show termianl cursor and key anything

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 6.2.9200
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.91GB free)|
|Process Argv|--crash-reporter-id ead44571-6eef-486e-b27f-fdc854287111|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-nginx-conf|ahm|0.3.2
arepl|alm|2.0.5
vscode-django|bat|1.15.0
htmlplay|bia|0.0.10
python-snippets|cst|0.1.2
vscode-markdownlint|Dav|0.53.0
pep8-asm|dea|0.0.1
python-preview|don|0.0.4
githistory|don|0.6.20
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
vscode-go-syntax|dun|0.0.18
gitlens|eam|14.2.1
vscode-html-css|ecm|2.0.6
copy-relative-path-and-line-numbers|ezf|0.3.1
vscode-pydev|fab|0.4.0
git-project-manager|fel|1.8.2
vscode-postfix-python|fil|0.1.3
vscode-test-explorer|hbe|2.21.1
Python-autopep8|him|1.0.2
rails-snippets|Hri|1.0.8
pep9-asm|ico|1.1.1
python-coding-conventions|igr|0.0.4
python-essentials|Jil|0.0.3
vsc-python-indent|Kev|1.18.0
kite|kit|0.147.0
vscode-python-test-adapter|lit|0.8.1
MagicPython|mag|1.1.0
background-cover|man|2.3.6
python-path|mge|0.0.14
vscode-docker|ms-|1.28.0
vscode-language-pack-zh-hans|MS-|1.85.2023121309
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
remote-explorer|ms-|0.4.1
test-adapter-converter|ms-|0.1.8
python-docs|Muk|0.8.3
python-coding-tools|nil|1.0.4
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
vetur|oct|0.37.3
nginx-formatter|ray|0.0.13
LiveServer|rit|5.7.9
vscode-qt-for-python|sea|7.6.0
tabnine-vscode|Tab|3.56.0
python-editing-terminal|ted|1.0.6
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8
vscode-nginx|wil|0.7.2
clang-format|xav|1.9.0
vscode-proto3|zxh|0.5.5

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vshan820:30294714
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30917236
pythongtdpath:30769146
i26e3531:30792625
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by Handsomer** [comment]
![image](https://github.com/microsoft/vscode/assets/10918610/8c1e1df4-4a12-4276-be5d-d7924bf87aa4)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by Handsomer** [comment]
> I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
yes , this version's(code VS insiders) terminal works well
![image](https://github.com/microsoft/vscode/assets/10918610/5d68fae1-6e3c-493e-9fab-a99d1d266173)
