### ISSUE TITLE
Add ability to reveal and set chat message in copilot window

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode#201911]
**Scenario**: we have webviews with code editor and error output, and we would like the LLM to generate code to fix it by clicking a contextual button. In other words, we would like to create functionality similar to this button in Jupyter notebooks:

<img width="212" alt="image" src="https://github.com/microsoft/vscode/assets/8560030/fa75b1e4-81ef-40a4-8021-0cfbd98a78d4">

It is very hard for a user to discover this functionality from the chat window directly otherwise, as there might not always be an error, or it might be difficult for the chat window to refer to a specific piece of UI.

In an ideal world, it would be great if we could directly call on the GitHub LLM to allow for this functionality. However, I understand that there might be more concerns with adding LLM access to the general API.

As a workaround, I am wondering if it would be possible to at least have an API to reveal the chat panel and pre-populate the text so that the user can submit it by simply pressing `Enter`? If the text field is not empty, perhaps to display a warning message that allows the user to keep or override the value?

This could also help with the discoverability portion as it teaches the user what to type in the chat window to achieve certain results.

Thanks!

**Comment by roblourens** [comment]
For now, you can call `workbench.action.chat.open` with these arguments: https://github.com/microsoft/vscode/blob/df8db3a75a49b85c9636530a3557cdbc639f7bdc/src/vs/workbench/contrib/chat/browser/actions/chatActions.ts#L41-L50

This is a bit experimental, might change, but this general scenario is important to us.

Out of curiosity, can you tell me more about your scenario? What type of webview editor?

**Comment by pwang347** [comment]
The above works well, thank you!

For our scenario, we are using Monaco editor within a webview. Here's an image of how it works:
<img width="1027" alt="image" src="https://github.com/microsoft/vscode/assets/8560030/9231c60a-ab25-462f-94ae-358ea459942c">

Do you know if there are also any considerations to execute slash commands, but not having to reveal the panel (to avoid disrupting the control flow)?

**Comment by roblourens** [comment]
Cool, any reason you aren't using a notebook for this?

And no, we are only focused on interactive scenarios in the panel where the user can look at the result.

**Comment by pwang347** [comment]
Hi @roblourens, apologies for the late response.

The extension we're building leverages code authoring / execution in a way similar to a notebook, however the user scenarios differ quite a bit and we need to control more of the state (e.g. when code is editable, can be executed, what content is displayed etc.) Feel free to reach out to me on Teams and I can definitely share more.

Re: the focus. Got it, thanks for confirming!

**Comment by roblourens** [comment]
Sounds like the command works for now, closing this. Also see the chatRequestAccess proposed API- this is only supported for chat agents in the panel for now but in the future may be able to drive arbitrary requests to the LLM as well, which might help you.
