### ISSUE TITLE
File nesting in explorer not working properly

### ISSUE THREAD

**Issue by PraneshBalasubramaniam** [microsoft/vscode#201919]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Windows 10 Enterprise 22H2

Enabled `explorer.fileNesting.enabled` setting to `true` and given the pattern for nesting `.css` under `.js` but didn't work.
Tried removing all extensions, removing all settings , but still got the issue.
Only previous added patterns are working, new ones are not working.
Also tried in GitHub Codespaces got same issue.

![image](https://github.com/microsoft/vscode/assets/44346322/f4bc9157-eaef-42ac-ac84-10e5f5133534)
Here I wanted the `.css` file to nest under corresponding `.jsx` files and `.js`, `.min.js` under `.ts` files but didn't happen

My setting
![image](https://github.com/microsoft/vscode/assets/44346322/1e43f980-a570-4e8d-a316-27f84f51f3d7)

**Comment by lramos15** [comment]
```
    "*.ts": "${capture}*.js",
    "*.tsx": "${capture}.css",
```
<img width="365" alt="image" src="https://github.com/microsoft/vscode/assets/4544166/5592f6ec-8973-4e3f-afcf-154d8245c57d">
