### ISSUE TITLE
Proposal: More flexible task definition

### ISSUE THREAD

**Issue by FancyBanana** [Microsoft/vscode#20194]
Version 1.9 brought long-awaited (at least by me) multiple commands for task definition, but the way tasks are defined is still rigid, there are a lot of attributes that can only be defined in the root of task.json.

I propose a simple system with inheritance and overriding:  
```
rootTaskgroup
      |-->task0
      |-->task1
      |-->taskgroup0
             |-->task00
             |-->task01
             |-->taskgroup00
                    |-->task000
```

`rootTaskgroup`  has every attribute defined by default or by specification.  
`taskgroup` inherits all attributes of the  parent and can override any attribute.
`task` inherits all attributes of the parent and can override any.  
___Only exception to the rule is task's name, which must be defined for each task separately.___

In the end, when parsing configuration file you obtain a list of tasks.
_update: made the model more uniform_

**Comment by dbaeumer** [comment]
Actually we have request that want exactly the opposite. They ask to remove inheritance and make the file simpler. I lean towards that as well.

**Comment by FancyBanana** [comment]
What i propose does not necessary introduce complexity, the simplest `task.json` may look like:
```json
{
    "tasks": [{
        "name":"foobar",
        "showOutput":"silent",
        "command":"foo",
        "args":["bar"]
    }]
}
```
As you can see, there is no _visible_ inheritance.  
I personally would like to have inheritance to avoid setting redundant attributes, for example when i have 5 build configurations for c++ project when the only difference is a couple of arguments. With inheritance the only thing i would need to define for each configuration is name and additional arguments.

**Comment by dbaeumer** [comment]
The complexity comes with explaining what is legal in a tasks.json. The simpler the easier to explain.

**Comment by FancyBanana** [comment]
What is complex here? You have a list of attributes, which is the same for all. Child inherits parents attributes and can override them.

**Comment by alexr00** [comment]
We support defining properties globally for a tasks.json file, then overriding those in individual tasks. Does that satisfy what you're looking for?
