### ISSUE TITLE
Cannot Search Across Files in Virtual Filesystem

### ISSUE THREAD

**Issue by iamhyc** [microsoft/vscode#201964]
Type: <b>Bug</b>

Hi, I am the author of the Overleaf Workshop extension, and recently our user find it is impossible to search in the virtual filesystem, which is registered with the scheme `overleaf-workshop`.

### Steps to Reproduce
1. Login to Overleaf server in [Overleaf Workshop](https://marketplace.visualstudio.com/items?itemName=iamhyc.overleaf-workshop) extension, and open any project in virtual filesystem.
2. **With no open files in the editor**, search for anything in the Search panel. The search will load indefinitely.

![](https://github.com/microsoft/vscode/assets/9068301/29ef6ee5-34b5-4039-9b23-fe81d8787d9e)

A similar issue I found on the issue list is #116303 ("**Search all files (ctrl+shift+f) doesn't find results in files with very long filepaths unless opened in the editor**"), which shares the same phenomenon we encountered in the virtual filesystem. For example, the root workspace folder of project `example-project` would have the long URI as below
```
overleaf-workshop://overleaf.com/example-project?user%3D64b8918eeeb0f60140fbdccd%26project%3D6595289580d7f9009dab4f74
```

Cause all the files will have long URIs with user ID and project ID, I am not sure if long URI is the only cause to blame. Please help confirm if we encountered the same issue as in #116303. Thank you!

----

VS Code version: Code - Insiders 1.86.0-insider (1cfc62d46e6b9dd217cd485d7d4591136f421d70, 2024-01-05T16:21:29.391Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7840HS w/ Radeon 780M Graphics      (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.73GB (5.57GB free)|
|Process Argv|--crash-reporter-id 5b4a88ff-b4a0-4382-9e95-565dec77f30a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
overleaf-workshop|iam|0.7.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
a9j8j154:30646983
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by andreamah** [comment]
Some questions:
1. Do you have a text search provider for that scheme?
2. Are there any helpful logs in the `Extension Host (Remote)` or `Extension Host` Output panel if you set your debug level to `Debug`?
3. If you turn off `search.experimental.closedNotebookRichContentResults`, dose anything change?

**Comment by iamhyc** [comment]
> Some questions:
> 
>   1. Do you have a text search provider for that scheme?
> 
>   2. Are there any helpful logs in the `Extension Host (Remote)` or `Extension Host` Output panel if you set your debug level to `Debug`?
> 
>   3. If you turn off `search.experimental.closedNotebookRichContentResults`, dose anything change?
> 
>   4. Did this work on a previous version of VSCode?

Thanks for your question! I just found a warning information shown when I apply the search. It appears that there is no search provider registered for my scheme.

![](https://github.com/microsoft/vscode/assets/9068301/647cd0f2-cd6f-4b29-938e-61530c9d0a27)

I see the `TextSearchProvider` API is still under discussion in #59921 and there is no public documentation yet. Can you give me some guidance? Thank you!

**Comment by iamhyc** [comment]
Hi @andreamah , I find the related API is still in proposal status here, https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.textSearchProvider.d.ts

If we can only expect search to work with a `TextSearchProvider` (in stabilized API), please help close this issue and I will keep track of #59921 instead. Thank you :)

**Comment by andreamah** [comment]
Yes, you will need a `TextSearchProvider` if you want to search using a specific scheme. Please track there. Thanks!
