### ISSUE TITLE
CurrentCulture=en-US if "console": "integratedTerminal" in debugger

### ISSUE THREAD

**Issue by shin-ng** [microsoft/vscode#201956]
Does this issue occur when all extensions are disabled?: Yes/No

I couldn't run debugger if all extensions are disabled. 

- VS Code Version: 1.85.1
- OS Version: MacOS BigSur 11.7.10

Steps to Reproduce:
I added a line to print out the CurrentCulture in Program.cs in the attached test project (created with "dotnet new webapi").

When debugging the project (Press F5):
If I commented out the line "console": "integratedTerminal" in the launch.json, the CurrentCulture=en-GB.
If I uncommented out the line, the CurrentCulture=en-US.

If I run "dotnet run" in the macOS terminal the CurrentCulture is always en-GB regardless of whether "console": "integratedTerminal" is added or not.
en-GB is what I expected as the Region in the system pref of my laptop is configured as UK.
[testwebapi.zip](https://github.com/microsoft/vscode/files/13854032/testwebapi.zip)

**Comment by roblourens** [comment]
I'm guessing this is related to your terminal/shell confguration in vscode, not vscode's terminal, but I don't know how this is determined on mac

**Comment by meganrogge** [comment]
This type of issue is typically related to environment differences between VS Code's terminal and the external terminal. 

Closing this off as it doesn't look actionable on our end, you can read more about our [issue process here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label *question
