### ISSUE TITLE
ENOSPC though no workspace

### ISSUE THREAD

**Issue by oliviercailloux** [microsoft/vscode#201923]
Type: <b>Bug</b>

- Have (almost?) all your inotify watches eaten by some (non VS Code related) process.
- Start VS Code without a workspace

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 6.1.0-16-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 7600 6-Core Processor (12 x 4108)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|14.77GB (11.28GB free)|
|Process Argv|--unity-launch --crash-reporter-id 20e93107-cdd5-4bd0-8ae0-0cf9727f02a2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|3.1.10
copilot|Git|1.145.0
copilot-chat|Git|0.11.1
vscode-htmlhint|HTM|1.0.5
latex-workshop|Jam|9.17.0
vscode-graphviz|joa|0.0.9
svg|joc|1.5.3
rainbow-csv|mec|3.11.0
black-formatter|ms-|2023.6.0
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1003402403
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
live-server|ms-|0.4.13
java|red|1.25.1
vscode-xml|red|0.26.1
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.43.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vshan820:30294714
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
89544117:30613380
2i9eh265:30646982
962ge761:30917236
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184t3:30927821

```

</details>

**Comment by gjsjohnmurray** [comment]
Does it also happen if you launch with all extensions disabled by adding the `--disable-extensions` argument?

**Comment by oliviercailloux** [comment]
Ouch, I did not expect that the VS Code issue reporter would post the comment without confirmation. Here is a complementary explanation.

When starting VS Code [without a workspace](https://code.visualstudio.com/docs/editor/workspaces), I see the infamous “Visual Studio Code is unable to watch for file changes in this large workspace” [ENOSPC](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc) error.

The message is incorrect: there is no VS Code workspace so there is also no large workspace.

I believe that The System is trying to tell me that it is running out of file watches, and this has nothing to do with my current VS Code workspace (if any). 

This may look like a detail but the current message is misleading and might lead the user to search for a problem in their workspace.

**Comment by oliviercailloux** [comment]
> Does it also happen if you launch with all extensions disabled by adding the `--disable-extensions` argument?

Yes, it does.

**Comment by bpasero** [comment]
I agree, we should probably rename the error and the docs because this issue may rise even from very small workspaces.

**Comment by bpasero** [comment]
The new wording is: `Unable to watch for file changes in this workspace. Please follow the instructions link to resolve this issue.`

**Comment by oliviercailloux** [comment]
Perhaps I am nitpicking, but this is still incorrect in case it appears when the user opens an instance with no workspace.

**Comment by bpasero** [comment]
Yeah, maybe we just drop the term altogether and make it:

```
Unable to watch for file changes. Please follow the instructions link to resolve this issue.
```

?

**Comment by oliviercailloux** [comment]
That seems most adequate to me.
