### ISSUE TITLE
Selected text cannot be copied and pasted immediately with "Show Paste Selector"-Option

### ISSUE THREAD

**Issue by MarkStraub** [microsoft/vscode#201951]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.86.0-insider (system setup)
- Commit: 1cfc62d46e6b9dd217cd485d7d4591136f421d70
- Date: 2024-01-05T16:21:29.391Z
- Electron: 27.1.3
- ElectronBuildId: 25612240
- Chromium: 118.0.5993.159
- Node.js: 18.17.1
- V8: 11.8.172.18-electron.0
- OS: Windows_NT x64 10.0.22635

Steps to Reproduce:
1. Mark a text to be copied
2. Press Ctrl + C
3. Press Ctrl + V
4. Nothing happens
5. Even when changing "Paste As: Show Paste Selector" to never

Description:
It happens if the "Show Paste Selector"-Option appears, or it is set to never
It still works as it should with plain text

Example:
![example-vs-code-issue](https://github.com/microsoft/vscode/assets/37868502/4cf22429-39dd-4b43-adab-07b48a460d6a)

**Comment by OlivierBelan** [comment]
Seem to fix the problem If you unselect this option in the settings:

![image](https://github.com/microsoft/vscode/assets/46423181/2651dd90-5d3c-47fd-802f-9714d0838dc2)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

I don't think the paste widget should show up in this case at all

**Comment by OlivierBelan** [comment]
Yes - I got this behaviour in version 1.86.0-insider with all extensions disabled (from what i remember).

**Comment by mjbvz** [comment]
Closing as the paste selection will no longer show in this case
