### ISSUE TITLE
Quotes with headings on markdown not rendering properly

### ISSUE THREAD

**Issue by Naxuh** [microsoft/vscode#201922]
Type: Bug

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
- OS version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1.  Open VS Code and make a .md file
2. Type "> #### Text"

The background box does not adjust to the font size of the headings

**Comment by RedCMD** [comment]
Can confirm
```md
# h1
> # h1
## h2
> ## h2
### h3
> ### h3
#### h4
> #### h4
normal
> normal
```
![image](https://github.com/microsoft/vscode/assets/33529441/2880c846-2f59-451d-a58a-8db44be6832c)

**Comment by Naxuh** [comment]
Even in the markdown preview of the comments here the quotes with headings works good. The bug is in VS Code

> #### Test

**Comment by eleanorjboyd** [comment]
still seeing a problem here but instead it looks a little different from the previous result
<img width="1587" alt="Screenshot 2024-06-25 at 11 34 32 AM" src="https://github.com/microsoft/vscode/assets/26030610/02148f8b-fb1a-41a5-96c1-0221ef33dabc">

**Comment by mjbvz** [comment]
@eleanorjboyd I think the issue was about the markdown preview. Take a look at the header size in the preview now [compared to before](https://github.com/microsoft/vscode/issues/201922#issuecomment-1879603660)

![Image](https://github.com/user-attachments/assets/5c0c6dcd-8972-490c-81d7-aec8f16186ba)
