### ISSUE TITLE
Inefficient transfer of `ArrayBuffer` from WebView to extension

### ISSUE THREAD

**Issue by juancampa** [microsoft/vscode#201933]
Type: <b>Bug</b>

1. Send an `ArrayBuffer` from a WebView using `acquireVsCodeApi.postMessage`
2. Print the received message in the `WebView`'s `onDidReceiveMessage` handler

Result: `{0: 123, 1: 34, 2: 72, 3: 105, 4: 103, ...`
Expected: `ArrayBuffer`

Also tested with `Uint8Array` but no luck.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:16.874Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|14, 9, 7|
|Memory (System)|32.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id c5db302d-a456-4380-8e2f-7d11ad0a619e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ron|a5h|0.11.0
vscode-eslint|dba|2.4.2
prettier-vscode|esb|10.1.0
kotlin|fwc|0.2.32
copilot|Git|1.145.0
copilot-chat|Git|0.11.1
vscode-github-actions|git|0.26.2
better-cpp-syntax|jef|1.17.2
vscode-peacock|joh|4.2.2
vscode-clangd|llv|0.1.26
vscode-dotnet-runtime|ms-|2.0.0
vscode-postgresql|ms-|0.3.0
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.12
makefile-tools|ms-|0.8.22
remote-explorer|ms-|0.4.1
proto|pet|0.0.4
vscode-yaml|red|1.14.0
vscode-gitweblinks|red|2.9.3
rust-analyzer|rus|0.3.1791
even-better-toml|tam|0.19.2
shellcheck|tim|0.35.0
es6-string-html|Tob|2.14.1
vscode-lldb|vad|1.10.0
vim|vsc|1.27.2
clang-format|xav|1.9.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
f6dab269:30613381
vscrp:30673768
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30928863
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by juancampa** [comment]
cc @mjbvz who originally implemented this 🙏 

I believe the root cause is that the `transfer` parameter was left unused: https://github.com/microsoft/vscode/pull/115664/files#diff-fe1b8b36665808bb8248cedd64619dcb6addd92be517c4cb6938776d16ec0af5R711

**Comment by mjbvz** [comment]
Works fine for me. I suspect your extension is targeting an old version of VS Code. For back compat, we only enable array buffer transfers if the extension targets vscode 1.57 or newer: https://github.com/microsoft/vscode/blob/996b733b2ccf6969fb99f6599a7a0f0540b9807a/src/vs/workbench/api/common/extHostWebview.ts#L175

**Comment by juancampa** [comment]
Weird, I reran it today and I'm not getting the issue anymore (I see ArrayBuffers arriving both ways). I've been using engine `^1.70.0` this whole time so I don't think it was that. Maybe my test was wrong somehow, I'm not sure anymore. Anyway thanks a lot for quickly looking into it 🙏
