### ISSUE TITLE
inabilty to input

### ISSUE THREAD

**Issue by stanley2344** [microsoft/vscode#201984]
Type: <b>Bug</b>

my terminal is supposed to allow me to input values according to the instructions ,but the input field isnt at the right position   PS C:\Users\stanl\0neDrive\Desktop\c— programming) & 'c:\Users\stanl\.vscode-insiders\extensions\ms-vscode.cpptools-1.18.5-win32-x64\debu
gAdapters\bin\windowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-OjialBoy.flj' '--stdout=Microsoft-MIEngine-0ut-4oik4omw.jst' '--std
PS C:\Users\stanl\0neDrive\Desktop\c- programming) & 'c:\Users\stanl\.vscode—insiders\extensions\ms—vscode.cpptools—1.18.5—win32—x64\debu
gAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-godmzw33.eqt' '--stdout=Microsoft-MIEngine-0ut-s4kumr4o.jgk' '--std
err=Microsoft~MIEngine~Error—vabvzka.Gwy' '——pid=Microsoft—MIEngine—Pid—swuzdvxc.clc' '——dngxe=C:\msys64\ucrt64\bin\gdb.exe' '——interpre
ter=mi'

Enter side A:

PS E:\Users\stanl\0neDrive\Desktop\c- programming) PS C:\Users\stanl\0neDrive\Desktop\c- programming)

>>

VS Code version: Code - Insiders 1.86.0-insider (1cfc62d46e6b9dd217cd485d7d4591136f421d70, 2024-01-05T16:21:29.391Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.95GB (6.28GB free)|
|Process Argv|--crash-reporter-id 5a05417a-f2a3-4db9-80df-fe09a92117d4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|10.1.0
code-runner|for|0.12.1
copilot|Git|1.145.636
copilot-chat|Git|0.12.2023122001
output-colorizer|IBM|0.1.2
vscode-gutter-preview|kis|0.30.0
vscode-edge-devtools|ms-|2.1.3
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
color-highlight|nau|2.5.0
LiveServer|rit|5.7.9
cmake|twx|0.0.17
chat-gpt|zha|1.6.63

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
