### ISSUE TITLE
Support underscore templates in "html.format.enable"

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode#20197]
**Versions**

- VSCode Version: Version 1.10.0-insider (1.10.0-insider)
- OS Version: Mac OS X 10.12.3 

**Steps to Reproduce**

1. Set `"html.format.enable"` to `true`.
2. Open the following `index.html` and format the file:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <% console.log('hello') %>
  <title>Login</title>
</head>
<body>
  <%
    // copy configs
    require('copy-loader!./foo.js');
  %>
  <script src="foo.js"></script>
</body>
</html>
```

**What did I expect?**

No changes.

**What was the actual result?**

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <% console.log('hello') %>
    <title>Login</title>
</head>
<body>
  <%
    // copy configs
    require('copy-loader!./foo.js');
  %>
    <script src="foo.js"></script>
</body>
</html>
```

It looks like every tag after `<% %>` is indented by two spaces.

**Why should this be changed?**

Underscore templates within HTML are a common feature in solutions like [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin).

**Comment by aeschli** [comment]
We're using http://jsbeautifier.org/ to format. You could file the issue there or look out for extensions that are giving full support to your template language.

**Comment by donaldpipowitch** [comment]
Thank you so far. I've created https://github.com/beautify-web/js-beautify/issues/1130.
