### ISSUE TITLE
the mixed language highlighting display.

### ISSUE THREAD

**Issue by phitrowkelvin** [microsoft/vscode#201906]
Type: <b>Feature Request</b>

hello! 
I like this program. I often write web pages. 
And I miss the mixed language highlighting display. 
I can have HTML, CSS, JS & PHP on my page at once.  
It would be nice to add just such a mode with a new future update. 
Thanks! With best wishes!

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by andreamah** [comment]
Do those not already highlight in an html file when you surround the text with the appropriate tags?

**Comment by phitrowkelvin** [comment]
In HTML mode, which I usually use, everything is highlighted except PHP, PHP all code is white.

**Comment by aeschli** [comment]
PHP might look like HTML, but it is its own language, with syntax not compatible to HTML.
So for PHP the language mode must be set to `PHP` and you need a PHP extension for richer language support.
