### ISSUE TITLE
Cors policy breaking remote tunnels on vscode.dev and insiders.vscode.dev

### ISSUE THREAD

**Issue by fred21O4** [microsoft/vscode#201967]
Does this issue occur when all extensions are disabled?: Yes (client), client never connects to host so host extension shouldn't effect result

- VS Code Version: client: vscode.dev (1.85.1 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2) server (shouldn't effect issue): 1.85.1 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2 x64
- OS Version (host): NixOS
- OS Version (client): all of: Chrome (version 120.0.6099.199) on windows, Edge (version 120.0.2210.121) on Windows, Firefox Nightly (version 123.0a1) on Android

Steps to Reproduce:

1. setup a vscode tunnel on a host computer
2. sign in (tested with github) on vscode.dev
3. no tunnels show up
4. manually connect to tunnel with vscode.dev/tunnel/hostname
5. observe network error
6. check browser console and find CORS policy violation

The exact error is:

> Access to XMLHttpRequest at 'https://global.rel.tunnels.api.visualstudio.com/api/v1/tunnels?tags=hostname,vscode-server-launcher&allTags=true&limit=1&global=true' from origin 'https://v--19o6jif34c0mpeit1a8veou0n92b64oqhb27cp6a35c7mh7slql1.vscode-cdn.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by fred21O4** [comment]
connecting to the same tunnel work via vscode app (version 1.84.2 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e)

**Comment by GingerIndustries** [comment]
This error just started occuring for me; the tunnels were working fine when the issue was opened.

**Comment by taiyosogawa** [comment]
We are investigating and working on resolving this issue. We are hoping to have a fix out in about an hour.

**Comment by grisaitis** [comment]
Working for me now!

**Comment by taiyosogawa** [comment]
Fantastic! The fix should be available in all regions soon. Thanks for the feedback everyone!

**Comment by grisaitis** [comment]
is this an issue with `code serve-web` or only vscode.dev?

**Comment by fred21O4** [comment]
can confirm working for me as well.
