### ISSUE TITLE
Why is Mac terminal complaining “-bash: export: `PATH;': not a valid identifier”

### ISSUE THREAD

**Issue by dumbledad** [Microsoft/vscode#20196]
- VSCode Version: 1.9.0
- OS Version: 10.12.3

This may not be VS Code, that's just a hunch. On my Mac when I start a terminal it first reports the error

`-bash: export: 'PATH;': not a valid identifier`

This appears to stem from the last line of my `~/.bash_profile` file:

`export VISUAL=vscodeeval $(/usr/libexec/path_helper -s)`

since commenting out the line fixes the issue. Is that line something added by VS Code when it installs?

(Stack Exchange question [here](http://apple.stackexchange.com/q/272194/142445).)

**Comment by joaomoreno** [comment]
No, Code didn't add that to your `~/.bash_profile`. I wouldn't know where that comes from or what it appears to be doing. 😕

**Comment by dumbledad** [comment]
Thanks João - all's fine if I just remove it so that's what I've done.
