### ISSUE TITLE
Unable to Run in Visual Studio Code

### ISSUE THREAD

**Issue by ejrabenda** [microsoft/vscode#201963]
Type: <b>Bug</b>

Project running in windows correct. will not build in Visual Studio Code for Android, does run correctly in Visual Studio 2022 for windows android 

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.95GB (50.73GB free)|
|Process Argv|--crash-reporter-id 044a1515-688b-47b9-94ee-0861ea6f954d|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
VSCode-MAUI-Archive|ban|0.1.3
gitlens|eam|14.6.1
remotehub|Git|0.62.0
vscode-docker|ms-|1.28.0
csdevkit|ms-|1.1.16
csharp|ms-|2.14.8
dotnet-maui|ms-|0.7.8
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.0.0
vscode-dotnet-sdk|ms-|0.8.0
vscodeintellicode-csharp|ms-|0.1.26
azure-repos|ms-|0.38.0
cpptools|ms-|1.19.1
notepadplusplus-keybindings|ms-|1.0.7
remote-repositories|ms-|0.40.0
vstuc|vis|0.9.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vshan820:30294714
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
89544117:30613380
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30928863
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by chrmarti** [comment]
Please provide steps to reproduce and maybe screenshots. What is "Visual Studio Code for Android"?

**Comment by ejrabenda** [comment]
android SDK Locations 
C:\Users\ejrab\AppData\Local\Android\Sdk

Installed 
c:\program files\Microsoft\jdk=21.0.1.12-hotspot\
c:\program files\Microsoft\jdk=11.02.21
microsoft-jdk-11.0.21-windows=x64.msi
microsoft-jdk-21.0.1-windows=x64.msi

Selected product file ThemeManagerMaui.sln
Run and Debug 
1) Picked Windows device local > Launched and WAD 
2) Picked Android Device a emulator that works on VS 2022 
   Preload task maui build exit code 1
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET MAUI",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build"
        }
    ]
}
[{
	"resource": "/c:/Program Files/dotnet/packs/Microsoft.Android.Sdk.Windows/33.0.95/targets/Microsoft.Android.Sdk.Tooling.targets",
	"owner": "msCompile",
	"code": "XA0031",
	"severity": 8,
	"message": "Java SDK 11.0 or above is required when using .NET 6 or",
	"source": "cpp",
	"startLineNumber": 20,
	"startColumn": 5,
	"endLineNumber": 20,
	"endColumn": 5
}]

**Comment by chrmarti** [comment]
This is not an issue with VS Code itself, but either with an extension or one of the tools used. Maybe file an issue with https://github.com/banditoth/maui-archiver-vscode/issues. Thanks.
