### ISSUE TITLE
Html tag pair <input> and </input> is not highlighted when clicked.

### ISSUE THREAD

**Issue by jetnag** [Microsoft/vscode#20191]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.3.9|
|PowerShell|ms-vscode|0.9.0|

---

Steps to Reproduce:

1. Create a html document. Tag pairs i.e. <div> and </div> are highlighted on cursor-over. 
2. The <input> </input> tag pairs are NOT highlighted correctly, only the <input> tag
3. Using these tags also destroys tag pair highlighting for parent tags as well, as these are subject to the same behaviour as in step 2 when surrounding the <input></input> tags.

Thanks!
![screenshot_input-error1](https://cloud.githubusercontent.com/assets/25635901/22734960/ed770e3c-edf7-11e6-93b6-e9c278895bf0.PNG)
![screenshot_input-error2](https://cloud.githubusercontent.com/assets/25635901/22734961/ed77f48c-edf7-11e6-83f6-b095dfca75b3.PNG)
![screenshot_input-error3](https://cloud.githubusercontent.com/assets/25635901/22734959/ed74fa7a-edf7-11e6-9160-36e18406fe2c.PNG)
![screenshot_normalbehaviour1](https://cloud.githubusercontent.com/assets/25635901/22734958/ed74fac0-edf7-11e6-86fd-7e342ebbc299.PNG)
![screenshot_normalbehaviour2](https://cloud.githubusercontent.com/assets/25635901/22734962/ed7941c0-edf7-11e6-9641-399a71a58fae.PNG)

**Comment by aeschli** [comment]
Thanks for the issue. Can you paste the example here?

**Comment by jetnag** [comment]
<form id="newinstanceform" role="form">
                        <div class="form-group">
                          <label for="instancename">Enter InstanceName:</label>
                          <input type="text" id="instancename" placeholder="InstanceName" class="form-control" maxlength="15">
                          </input>
                        </div>
                        <div class="form-group">
                          <input id="newinstancesubmit" type="submit" value="Add" class="btn btn-primary">
                          </input>
                        </div>
                      </form>

**Comment by jetnag** [comment]
I am so sorry. User error. There seems to be no  < / i n p u t >  tag, and Visual Studio Code works perfectly.
Closing this issue. :)
