### ISSUE TITLE
When typing Korean, a red box suddenly appears(same with #163106).

### ISSUE THREAD

**Issue by steadily-worked** [microsoft/vscode#201952]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `1.85.1 (Universal)`
- OS Version: `macOS Sonoma 14.2.1`

Hi, when i type with Korean, sometimes a red box with some letters suddenly appears. below is the step to reproduce with video. this issue is same with #163106 but it is already closed due to no actions.

+) i already disabled macOS VoiceOver

Steps to Reproduce:

1. create `README.md`
2. type `CMD + /` to add comment, 
3. delete them by dragging and adding any Korean 1 letter(in my case, 'ㅇ')
4. after deleting 'ㅇ', red box with "BS" appears.

https://github.com/microsoft/vscode/assets/61453718/32073856-b37a-490a-8b8c-2a8d55326965

Thanks.

**Comment by aiday-mar** [comment]
From the other issue it looks like the IME is inserting the unicode character group separator which is the reason we are seeing this. I am wondering if we should remove the group separator unicode characters and replace them for example with something else (like a space character) in order not to have it appear as a red box.

**Comment by aiday-mar** [comment]
After testing with the experimental edit context setting, this seems to be fixed. The setting is _editor.experimentalEditContextEnabled_ requires reload after enablement. This issue will be closed.
