### ISSUE TITLE
Auto-open Readme on project open

### ISSUE THREAD

**Issue by valhuber** [microsoft/vscode#202020]
Type: <b>Feature Request</b>

I am aware of the user setting to Auto-open Readme on project open.

However, my project (ApiLogicServer) creates projects, often for 1st-time VSCode users.  New users would not have set this option.  Perhaps the default should be to use this?

I am also aware of the tasks option to run commands on startup.  In particular, `code -r readme.md` works well, *except* for macs where new users might not have enable the command line option.

So, despite days of research, I have not found a way to force VSCode to open the readme.md (or Welcome.md) on startup.  

I really believe it would be valuable to provide a way to open one of these on startup, if they exist.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:16.874Z)
OS version: Darwin arm64 23.2.0
Modes:

**Comment by mjbvz** [comment]
You can set `"workbench.startupEditor": "readme"` for this

**Comment by valhuber** [comment]
@mjbvz Thanks for your reply.

This works for me *only* as a user setting.  It is not available as a project setting, and is accepted but ignored as a workspace setting, perhaps overwritten by the user setting.

In my case - new users - they generally don't know about settings, so will have the default user setting.  So overriding from this effectively disables the workspace option.

I most want this as a project setting, workspace would be ok.  Currently, I am not able to make either work.
