### ISSUE TITLE
Tab completion (e.g. Emmet) stopped working

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#20206]
- VSCode Version: Code - Insiders 1.10.0-insider (eff9148502fd3edf42573beb16006bee533c3cf9, 2017-02-08T07:05:20.062Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.4.3|
|sort-lines|Tyriar|1.2.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.10.2|
|project-manager|alefragnani|0.13.2|
|vscode-angular-files|alexiv|1.3.7|
|vscode-eslint|dbaeumer|1.2.5|
|tslint|eg2|0.8.1|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|auto-rename-tag|formulahendry|0.0.11|
|Angular2|johnpapa|1.0.2|
|vscode-icon-theme|jtlowe|1.4.0|
|theme-karyfoundation-themes|karyfoundation|11.0.0|
|ftp-sync|lukasz-wronski|0.3.2|
|HTMLHint|mkaufman|0.3.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-csscomb|mrmlnc|4.0.0|
|vscode-postcss-sorting|mrmlnc|2.2.1|
|vscode-stylefmt|mrmlnc|2.2.2|
|Theme-1337|ms-vscode|0.1.2|
|angular2-inline|natewallace|0.0.17|
|vscode-icons|robertohuertasm|7.2.0|
|stylelint|shinnn|0.22.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|1.0.3|
|theme-espresso|smlombardi|1.0.1|
|theme-tesla|smlombardi|6.0.0|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. in SCSS or CSS file, type something like `h40` and hit tab.  Nothing happens.  Should expand to `height: 40px`

2. in HTML file type `div` and tab.  Nothing happens, should expand to `<div></div>`

This is a recent regression, worked fine yesterday.

**Comment by admmasters** [comment]
Same here - might be related to:
239b199f6dcdbfb1fb3105c0954ef21e61fd326e

**Comment by admmasters** [comment]
Saying that - there seem to be some reports of tab key not working full stop...

**Comment by smlombardi** [comment]
@admmasters  Yes, I have subsequently noticed the tab key doesn't work at all. Thanks.

**Comment by smlombardi** [comment]
Likely related to https://github.com/Microsoft/vscode/issues/20209
