### ISSUE TITLE
Netwok: Folder appears empty when using a network drive

### ISSUE THREAD

**Issue by irimiab** [Microsoft/vscode#20207]
When using VS Code with a Samba network drive mounted on Z:, some folders appear as empty, even if though they have content. Opening one of the files in that folder from Windows Explorer into VS Code sometimes fixes the issue. 

- VSCode Version: 1.9.0
- OS Version: Windows 10

Steps to Reproduce:

1. Mount a Samba folder on Z:
2. Open the Z: folder in VS Code
3. Sometimes, some folders appear empty in VS Code Explorer; opening in VS Code, from Win Explorer, a file in that folder sometimes makes the correct folder structure to appear

**Comment by irimiab** [comment]
Updates regarding this issue:
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|lualinter|dcr30|1.0.3|
|line-counter|dollyn|0.2.0|
|githistory|donjayamanne|0.1.5|
|Theme-FlatlandMonokai|gerane|0.0.4|
|Lua|keyring|0.0.9|
|Theme-PredawnKit|ms-vscode|0.1.1|

So this manifests on version 1.9.1 too.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by irimiab** [comment]
Sure, I will. Let's hope it happens again, because it is an intermittent phenomenon.

**Comment by irimiab** [comment]
I keep getting these errors, but I don't think they are related to this issue, because it didn't manifest yet.
Anyway, I will add the error here, for reference:
```
Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at C:\Users\bogdan\.vscode\extensions\dcr30.lualinter-1.0.3\out\src\extension.js:93:93
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:1748)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:5235)
    at t.$acceptActiveEditorAndVisibleEditors (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:13:8151)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:2729)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:8:15667)
    at d (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:8:16344)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by bpasero** [comment]
@irimiab yeah this seems to come from an extension (lualinter) and should maybe be reported to them. Seems unrelated to this issue here.

**Comment by irimiab** [comment]
Now I could see the phenomenon again.
There is no significant output in the error console. All I get is the lua linter error above and some entries related to Git:
```
[File Watcher] [ADDED] z:\.git\index.lock
[File Watcher]  >> normalized [ADDED] z:\.git\index.lock
[File Watcher] [DELETED] z:\.git\index.lock
[File Watcher]  >> normalized [DELETED] z:\.git\index.lock
```

**Comment by irimiab** [comment]
I also disabled the `lualinter` extension, just to make sure it doesn't interfere with the app. The same phenomenon happens:
![image](https://cloud.githubusercontent.com/assets/2221542/23017445/f57c4bc8-f442-11e6-9c0f-660cbd5c79fe.png)

The folder `kernel` actually contains folders and files, which appeared until just now.
Of course, clicking on the `kernel` entry just toggles the small triangle icon on the left, but no content is shown whatsoever.
Restarting VS Code doesn't help, either.
I think it's something related with the file listing method, because **the project folder is actually on a network mounted drive** (`Z:\`):
![image](https://cloud.githubusercontent.com/assets/2221542/23017573/7e602842-f443-11e6-9804-43f365057f8b.png)

Clicking on the refresh icon doesn't help, either.

This started to happen in 1.9.0. The versions before didn't have this problem.

Let me know if I can give you more debugging information.

Thanks

**Comment by irimiab** [comment]
One more details about this:
I have these files opened:
![image](https://cloud.githubusercontent.com/assets/2221542/23017680/f89046b0-f443-11e6-8202-e2caf19229e1.png)
With the current selection, the folder `kernel` appears with no content (the issue in discussion).
If I select another file:
![image](https://cloud.githubusercontent.com/assets/2221542/23017707/13893e68-f444-11e6-8472-1b35351185b7.png)
then then folder appears correctly.

Both opened files are in sub-folders of the `kernel` folder.

Closing and reopening the file `tab-ds-status.html` fixes for the moment the problem.

**Comment by bpasero** [comment]
@irimiab would you be able to run VS Code from its sources for some debugging? See https://github.com/Microsoft/vscode/wiki/How-to-Contribute

**Comment by irimiab** [comment]
I'm sorry, this is my workstation at work, so I can't install NodeJS.
Sorry

Maybe if this bug will become really annoying I will prepare an environment for this.

**Comment by bpasero** [comment]
Ok understood 👍

**Comment by irimiab** [comment]
I have an update about this one: it seems that, when the issue manifests, the Git tab also fails to refresh. The blue line keeps rotating and nothing else appears below it. I just noticed that yesterday in the latest version of Visual Code (1.10.2).

It's definitely something  related with file access.

**Comment by bpasero** [comment]
@irimiab do you still see this with VS Code 1.12?

**Comment by irimiab** [comment]
I have an update for this issue for VS Code 1.12.1:
- as I mentioned, my project folder is on a mounted hard-drive, over Samba (the host is a FreeBSD OS) which shares the "home" server of a web app
- previously, from time to time, some folders disappeared from VS Code, inexplicably
- since version 1.11, [this](https://code.visualstudio.com/updates/v1_11#_new-setting-to-keep-editor-open-even-when-file-is-deleted) new feature eliminated the situation when the folders disappeared, but still some files became "deleted"; when I closed them and re-opened, they appeared correctly
- this issue is still present in 1.12 and 1.12.1 and it manifests especially when I commit the work on Git. I could say this is consistent (happens every time): when I commit all in Git, all opened files are being shown as "deleted". When I click on the tabs (I change between file tabs), they become fixed again (so the text "deleted from disk" disappears)

Because this wasn't as bothering as before (before 1.11), I considered it manageable and didn't proceed further with investigating it.

Thank you for your interest.

**Comment by bpasero** [comment]
It seems to me for some reason we receive a delete event on folders from time to time and that will cause the folder to disappear from the explorer. As a workaround, file watching can be disabled by setting:

```json
"files.watcherExclude": {
    "**/**": true
  }
```

**Comment by irimiab** [comment]
Thanks, I will use that.

**Comment by bpasero** [comment]
Closing due to long inactivity.

**Comment by irimiab** [comment]
Yes, it is fixed in more recent releases. Thanks.
