### ISSUE TITLE
Update Python grammar 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#202037]
We have a few bugs reported related to problems with syntax highlighting that have been addressed upstream in MagicPython but haven't made it to VS Code yet. For example: 
https://github.com/MagicStack/MagicPython/commit/5b5f388fc46e45dff7e48edc90242c7f578d8705 (from  https://github.com/microsoft/pylance-release/issues/5089#issuecomment-1804659504_)

**Comment by alexr00** [comment]
Just tried to update the python grammar, but it's actually already up to date, and has been for many months.
