### ISSUE TITLE
'git.checkout' command hangs after cancelled

### ISSUE THREAD

**Issue by tomimelo** [microsoft/vscode#202059]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Ubuntu 20.04.6 LTS

Steps to Reproduce:

1. Execute `git.checkout` command
2. Press `<Esc>` or click away the quick open window

After executing `git.checkout `(or `git.checkoutDetached`) command if you click away or press `Esc` to cancel the action the command hangs.
Seeing the code source it seems the [choice promise](https://github.com/microsoft/vscode/blob/main/extensions/git/src/commands.ts#L2415C9-L2415C9) doesn't resolve so is like the command never ends. 

![image](https://github.com/microsoft/vscode/assets/60193559/ade0bfb9-44ce-4945-9822-c77b0de5c018)

This causes that other extensions (e.g. [vscodevim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim)) after configuring a keyboard shortcut that executes a command hangs because is waiting for the command to be terminated. Related [Issue](https://github.com/VSCodeVim/Vim/issues/3718) 

I'm not very familiar with the codebase so maybe someone has a better solution, but this is what comes to my mind

![image](https://github.com/microsoft/vscode/assets/60193559/e26a1010-7d73-4c08-a431-619945730f26)

So after that it will resolve and fall into the no choice case

If you think it's worth it I can try to make a PR

**Comment by lszomoru** [comment]
Fixed with https://github.com/microsoft/vscode/pull/202495.

**Comment by alexr00** [comment]
@lszomoru I tried running "Git: Checkout to..." and cancelling in stable, but I didn't notice any hang. What is the best way to reproduce and verify this?

**Comment by lszomoru** [comment]
Verification steps:
1. Clone https://github.com/microsoft/vscode-extension-samples
2. Open `hello world-sample` folder in VS Code Insiders, run `npm i`
3. Add the following to the `package.json`
```json
	"extensionDependencies": [
		"vscode.git"
	],
```
4. Update the code of the `helloWorld` command
```ts
const disposable = vscode.commands.registerCommand('extension.helloWorld', async () => {
		await vscode.commands.executeCommand('git.checkout');

		// Display a message box to the user
		vscode.window.showInformationMessage('Hello World!');
	});
```
5. Run the sample using `F5`
6. Invoke the `Hello World` command
    * Confirm that the checkout quick pick is being shown
7. Press ESC
    * Confirm that the checkout quick pick is hidden
    * Confirm that the "Hello World" notification is shown
