### ISSUE TITLE
Jump to file in multi-diff editor

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#202019]
Not sure if this is a request for the PR extension, or the multi-diff editor. I love the new multi-diff editor. One thing I'd like to have is the ability to stay in the multi-diff editor but jump to a certain file. One way it could work would be to have the multi-diff editor icon on each file in the files list, and when I click it, it opens the editor scrolled to that file (or reveals that file in a currently-open multi-diff editor).

<img width="425" alt="image" src="https://github.com/microsoft/vscode/assets/323878/43589bd1-c1b5-46ab-83b6-11757f4a9445">

Or maybe it could work inside the editor itself with something like breadcrumbs?

**Comment by hediet** [comment]
Related #199314

**Comment by hediet** [comment]
Verification steps:
Click on a changed file in the SCM view with the middle button of your mouse.
