### ISSUE TITLE
text document a long length of render text having a max lines length causing scaling problem for leading to text to cut out after around 50,000 lines.

### ISSUE THREAD

**Issue by sirivus** [microsoft/vscode#202050]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest vscode insider version
- OS Version: macosx sonoma 14.0

Steps to Reproduce:

1. create a 50,000+ lines with full text lengths, cut off is around 49,000 depending on window size, used to display full 60,000+ word document length, is this for performance reasons, i could not find or increase the limit anywhere.

**Comment by balbertho** [comment]
Same issue

Type: <b>Bug</b>

1. Create a long file with about 52700 lines or 1000000px total height
2. All lines after this will be invisible and will be visible only after modifying the height directly in developer tool.

VS Code version: Code - Insiders 1.86.0-insider (4caba0473af34a2b128cedc46f6b13316aae9226, 2024-01-08T05:36:56.355Z)
OS version: Windows_NT x64 10.0.22621
Modes: Restricted




![image](https://github.com/microsoft/vscode/assets/12370920/a85325f6-b86b-4867-ac48-e455dad2b91a)

The bug **does not exist** in 2014-01-05's build:
Version: 1.86.0-insider (user setup)
Commit: 1cfc62d46e6b9dd217cd485d7d4591136f421d70
Date: 2024-01-05T16:21:29.391Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.26020

**Comment by RedCMD** [comment]
@sirivus 
there is a hidden setting to change it
I think you can see it when hovering over the end?

**Comment by RedCMD** [comment]
![image](https://github.com/microsoft/vscode/assets/33529441/aeb28bc5-a94c-48aa-a008-2da2adc0d97c)
`"editor.stopRenderingLineAfter": 50000`

**Comment by antlaij** [comment]
Looks like the css setting limited the height of the view.
![image](https://github.com/microsoft/vscode/assets/15242427/52422b50-850f-45b6-885d-675d9a4f454a)

If I set the height to 1e+08px, then I can see all the lines

height: 1e+08px;
