### ISSUE TITLE
Command in command palette is being run with arguments from keybinding

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#202076]
I have this keybinding for the Run Task command with a specific argument

```
	{
		"key": "ctrl+shift+alt+b",
		"command": "workbench.action.tasks.runTask",
		"args": "Restart VS Code - Build"
	},
```

Not sure when this started, but when I try to run the Run Task command (no arguments) from the command palette, it seems to be running the command with the arguments from the keybinding, which means that I can't just run the Run Task command.

**Comment by bpasero** [comment]
I see that in some cases we seem to forward arguments, not sure if that applies here:

https://github.com/microsoft/vscode/blob/572198c07d3021fad00be382c1042ab652b0be36/src/vs/platform/quickinput/browser/commandsQuickAccess.ts#L274-L276

**Comment by alexr00** [comment]
Today I can't repo. It happened 100% of the time for me yesterday. I did update VS Code, so maybe something changed. I'll reopen if I see it again.
