### ISSUE TITLE
Moved files from Userinstall directory to secondary drive with write and read permissions

### ISSUE THREAD

**Issue by JDJGInc** [microsoft/vscode#202054]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code version: Code - Insiders 1.85.0-insider (54821ee1f14beca4866abd7de86175b4794b030d, 2023-11-14T12:57:11.748Z)
- OS version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Go to the user install directory
2. move the stuff over to a different drive and folder.
3. change the path to properly use the new folder and then the update function breaks.

**Comment by JDJGInc** [comment]
![Untitled](https://github.com/microsoft/vscode/assets/22802640/9ec16223-3e6f-468b-ae9c-cb42a6f3cb83)
The error.

**Comment by JDJGInc** [comment]
ie the updater complains about a file missing in C:\Users\%username%\AppData\Local\Programs
changing user path for it does not help
![image](https://github.com/microsoft/vscode/assets/22802640/04240128-16ae-4a75-8411-d16bc76becf9)
Missing the insider .exe from there.

**Comment by joaomoreno** [comment]
> move the stuff over to a different drive and folder.

This is not supported. Maybe [Portable Mode](https://code.visualstudio.com/docs/editor/portable) is something for you?

**Comment by JDJGInc** [comment]
so the user installs only allow the C:\Users%username%\AppData\Local\Programs?

it doesn't explain what I need to backup if I do uninstall it though.

**Comment by JDJGInc** [comment]
to keep extenstions, configs, and other important settings

**Comment by joaomoreno** [comment]
You don't need to backup anything if you uninstall. All your settings and extensions will be preserved.

**Comment by JDJGInc** [comment]
I have insider and regular aren't they stored in the main folder.
Should I just move the files back to the local directory ?
