### ISSUE TITLE
Focus on Output View Command has a broken name

### ISSUE THREAD

**Issue by gabrielBusuioc** [microsoft/vscode#202086]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Ubuntu 22.04.2 LTS

![unnamed](https://github.com/microsoft/vscode/assets/100689379/2735dcd9-b97c-4063-8a62-f7fec945d72d)

I am also seeing this behavior for the panels contributed by an extension: If I define 2 or more panels in package.json, one of the associated "Focus on ..." commands will have this strange prefix. Moreover, the view that is placed inside the panel will not have its name displayed at all.

Has anything happened to the way panels are contributed? On version 1.83 everything seems to be working fine.

**Comment by sandy081** [comment]
I suspect you might have moved the output view into another location/view container. Can you please try using a temporary profile and let us know if you still see the same? - F1 > Create a Temporary Profile

**Comment by gabrielBusuioc** [comment]
@sandy081 That is true, I did play around with the views before seeing this.
After creating a temporary profile, the issue was gone. Thanks!

One more question: 
Can I control the order of the panels that I provide for the Panels Area? 
For example, my extension provides 2 panels ( each one of them containing a specific view ) and these are displayed randomly across the panels' list ( Problems - Output - Terminal - Debug Console - MyPanel1 - Ports - MyPanel2 ). 
Is there a way to instruct VS Code to group them ( Problems - Output - Terminal - Debug Console - Ports - MyPanel1 - MyPanel2 )?
