### ISSUE TITLE
Document/clarify whether TextDocumentContentProviders can send onDidChange only for open files

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#202017]
It's not clear to me from the API docs whether a `TextDocumentContentProviders` can selectively send `onDidChange` only if the document is open. Eg. after `didCloseTextDocument` or if a document is not in `workspace.textDocuments`, can an extension/server stop sending these messages?

My feeling is that the answer is yes (because otherwise there could be a lot of unnecessary spam), but it relies on VS Code not caching the contents of any documents that are "closed" and I'd like to be certain of this (and that it is the intention, and not only the current behaviour) before relying on that.

The docs for this field are here:

https://github.com/microsoft/vscode/blob/545eb1dabec2ccca84500f47ebb740c4c7170d95/src/vscode-dts/vscode.d.ts#L1805

**Comment by jrieken** [comment]
You don't need to care. You can send events any time and we should be doing the right thing

**Comment by DanTup** [comment]
@jrieken I was trying to minimize the number of events being sent if they don't do anything. Eg., if a user opens then closes a generated file and it is changed, can I skip sending the event and know that if VS Code tries to re-open the document later, it will first fetch the latest content?

Otherwise it seems like we might end up sending a lot of unnecessary change events as the user is modifying files if their changes affect generated files.

**Comment by DanTup** [comment]
@jrieken are you able to answer the above? I'm can send events on every change, but if they're unnecessary it's just more traffic and processing VS Code is doing as the user is typing. I also hope to add support for `TextDocumentContentProvider`s to LSP, so being explicit on the rules would be better.
