### ISSUE TITLE
vscode 1.85.1 with devcontainer and alpine 3.15 not working properly

### ISSUE THREAD

**Issue by Roemer** [microsoft/vscode#202014]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Windows 10, Debian WSL2

Steps to Reproduce:
1. Create a dev-container based on alpine-3.15
2. Use the search function in vscode -> doesn't show any results and spins indefinitely

More details:
I found a similar issue from April 2023 (https://github.com/microsoft/vscode/issues/179490) which is closed. I now wonder if it is the same issue or a different one or if alpine 3.15 is just unsupported now? If I leave everything as is and just use alpine-3.17 everything is back to normal.

**Comment by chrmarti** [comment]
I cannot even connect to an Alpine 3.15 container, the log shows:
```
Error relocating /vscode/vscode-server-insiders/bin/alpine-arm64/7452aaa51d440d39c4e6ab61970b290b8600f52f-insider/node: _ZSt28__throw_bad_array_new_lengthv: symbol not found
```

Alpine 3.16 works. 3.15 is past its "end of support" time: https://www.alpinelinux.org/releases/.

@deepak1556 Do you have any background on this?

**Comment by deepak1556** [comment]
Yes we only support alpine >= 3.16 since https://github.com/microsoft/vscode-linux-build-agent/pull/34, closing as expected.

**Comment by chrmarti** [comment]
It would make sense to mention changes to the supported OS/library versions in the VS Code release notes. Can't find that right now for this case.

**Comment by deepak1556** [comment]
Yeah seems like it was missed, reopening to update documentation.
