### ISSUE TITLE
IntelliSense requires ATA definitions instead of local module

### ISSUE THREAD

**Issue by bpaczkowski** [Microsoft/vscode#20205]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows 10

Steps to Reproduce:

1. Have automatic type acquisition enabled.
2. Write a file with the same name as any npm package (eg. `config`).
3. Require it in another module: `const config = require('./config')`, notice the `./` which should indicate I meant to require a local module.
4. IntelliSense will use the npm package typings instead of the local file.

![code_2017-02-08_15-28-23](https://cloud.githubusercontent.com/assets/1371800/22741467/a2587320-ee13-11e6-939d-11f6ea203e08.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13964
