### ISSUE TITLE
Markdown problems and flaws.

### ISSUE THREAD

**Issue by Rajsharma9593** [Microsoft/vscode#20203]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|vscode-eslint|dbaeumer|1.2.2|
|javadebugger|donjayamanne|0.0.2|
|java-debug|DSnake|0.0.2|
|vscode-great-icons|emmanuelbeziat|1.1.43|
|php-debug|felixfbecker|1.10.0|
|Theme-tonic|gerane|0.0.2|
|CppSnippets|hars|0.0.6|
|phpcs|ikappas|0.7.0|
|java-properties|ithildir|0.0.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|cpp-symbols|mirkoh|0.0.1|
|vscode-clang|mitaki28|0.2.1|
|cpptools|ms-vscode|0.10.0|
|theme-quietlight-vsc|onecrayon|1.0.1|

---

Steps to Reproduce:

I love your new update very much which introduced a feature of Markdown but it has few problems. the problems which I have faced while writing CSS and HTML codes are:

1. While I was writing the tags like `<div>` it suddenly takes the tag (`<div>`) down, but the cursor is not taken along with it. Not only that, it even  deletes lines and I have to re -write it. 
 
~I want the cursor also to move along with the tags.

~~ I actually love this update and it adds it to my Best code editors list. hope you will add more Surprises in FUTURE.

-Thank You.

Please correct me wherever I am wrong Please.... :)

**Comment by mjbvz** [comment]
It is unclear what the bug is. Can you please add more detailed instructions or record a gif of the problem

**Comment by mjbvz** [comment]
Closing as not actionable without more information
