### ISSUE TITLE
[grammars] nesting `embedded.meta.*` tokens doesn't work

### ISSUE THREAD

**Issue by acao** [microsoft/vscode#202046]
When I use nested `meta.embedded.*` tokens in my grammar, the tokenizer doesn't seem to have a problem with it, but the nested highlighting doesn't appear in vscode. the build-in ```js ``` block highlights the js but not the graphql. is there something I'm missing?

```
\`\`\`                                                                        | 
js                                                                            | 
const var = 1;                                                                | meta.embedded.block.javascript
                                                                              | meta.embedded.block.javascript
graphql                                                                       | meta.embedded.block.javascript entity.name.function.tagged-template.js
\`                                                                            | meta.embedded.block.javascript punctuation.definition.string.template.begin.js
                                                                              | meta.embedded.block.javascript meta.embedded.block.graphql
query                                                                         | meta.embedded.block.javascript meta.embedded.block.graphql keyword.operation.graphql
                                                                              | meta.embedded.block.javascript meta.embedded.block.graphql meta.selectionset.graphql
{                                                                             | meta.embedded.block.javascript meta.embedded.block.graphql meta.selectionset.graphql punctuation.operation.graphql
                                                                              | meta.embedded.block.javascript meta.embedded.block.graphql meta.selectionset.graphql
something                                                                     | meta.embedded.block.javascript meta.embedded.block.graphql meta.selectionset.graphql variable.graphql
                                                                              | meta.embedded.block.javascript meta.embedded.block.graphql meta.selectionset.graphql
}                                                                             | meta.embedded.block.javascript meta.embedded.block.graphql meta.selectionset.graphql punctuation.operation.graphql
\`                                                                            | meta.embedded.block.javascript punctuation.definition.string.template.end.js
\`\`\`                                                                        | 
```
Here is the relevant PR, in case there are other changes I'm missing:
https://github.com/graphql/graphiql/pull/3490

**Comment by RedCMD** [comment]
can you send some screenshots please

**Comment by acao** [comment]
sure, i just need to roll back where I made progress. i tried another strategy and it turns out that the nested embedded.meta.* scopes aren't the problem but something else.

```
                                                    | 
\`\`\`                                                  | markup.fenced_code.block.javascript punctuation.definition.markdown
javascript                                           | markup.fenced_code.block.javascript fenced_code.block.language.markdown
const var = 1;                                       | markup.fenced_code.block.javascript meta.embedded.block.javascript
                                                     | markup.fenced_code.block.javascript meta.embedded.block.javascript
graphql                                              | markup.fenced_code.block.javascript meta.embedded.block.javascript entity.name.function.tagged-template.js
\`                                                    | markup.fenced_code.block.javascript meta.embedded.block.javascript punctuation.definition.string.template.begin.js
                                                     | markup.fenced_code.block.javascript meta.embedded.block.javascript meta.embedded.block.graphql
query                                                | markup.fenced_code.block.javascript meta.embedded.block.javascript meta.embedded.block.graphql keyword.operation.graphql
                                                     | markup.fenced_code.block.javascript meta.embedded.block.javascript meta.embedded.block.graphql meta.selectionset.graphql
{                                                    | markup.fenced_code.block.javascript meta.embedded.block.javascript meta.embedded.block.graphql meta.selectionset.graphql punctuation.operation.graphql
                                                     | markup.fenced_code.block.javascript meta.embedded.block.javascript meta.embedded.block.graphql meta.selectionset.graphql
something                                            | markup.fenced_code.block.javascript meta.embedded.block.javascript meta.embedded.block.graphql meta.selectionset.graphql variable.graphql
                                                     | markup.fenced_code.block.javascript meta.embedded.block.javascript meta.embedded.block.graphql meta.selectionset.graphql
}                                                    | markup.fenced_code.block.javascript meta.embedded.block.javascript meta.embedded.block.graphql meta.selectionset.graphql punctuation.operation.graphql
\`                                                    | markup.fenced_code.block.javascript meta.embedded.block.javascript punctuation.definition.string.template.end.js
\`\`\`                                                  | markup.fenced_code.block.javascript punctuation.definition.markdown
                    
 ```
 
 ```json
 {
 "scopeName": "inline.graphql.markdown.codeblock",
  "injectionSelector": "L:text.html.markdown",
  "patterns": [
    {
      "begin": "(^|\\G)(\\s*)(\\`{3,}|~{3,})\\s*(?i:(javascript|typescript|js|ts)(\\s+[^`~]*)?$)",
      "name": "markup.fenced_code.block.javascript",
      "end": "(^|\\G)(\\2|\\s{0,3})(\\3)\\s*$",
      "beginCaptures": {
        "3": {
          "name": "punctuation.definition.markdown"
        },
        "4": {
          "name": "fenced_code.block.language.markdown"
        },
        "5": {
          "name": "fenced_code.block.language.attributes.markdown"
        }
      },
      "endCaptures": {
        "3": {
          "name": "punctuation.definition.markdown"
        }
      },
      "patterns": [
        {
          "begin": "(^|\\G)(\\s*)(.*)",
          "while": "(^|\\G)(?!\\s*([`~]{3,})\\s*$)",
          "contentName": "meta.embedded.block.javascript",
          "patterns": [
            {
              "include": "inline.graphql"
            }
          ]
        }
      ]
    },
   ```
   gives me this, which is progress:
   
![image](https://github.com/microsoft/vscode/assets/1368727/8a073b7b-cf88-49f2-a516-65f905869ba4)

now, I will roll back to what I had when i created the issue, and update the description to show you

**Comment by acao** [comment]
Ok I got it working, but it seems to be a slow and inefficient approach, by using the generic markdown `injectionSelector` `L:text.html.markdown` instead of the more specific `L:markup.fenced_code.block.markdown`.

![image](https://github.com/microsoft/vscode/assets/1368727/df0f2ca6-e7d9-4116-8048-a6c171712f09)


the trick was to use this pattern, where we put the graphql js include before the source.js one specifically

```json
  {
          "begin": "(^|\\G)(\\s*)(.*)",
          "while": "(^|\\G)(?!\\s*([`~]{3,})\\s*$)",
          "contentName": "meta.embedded.block.javascript",
          "patterns": [
            {
              "include": "inline.graphql"
            },
            {
              "include": "source.js"
            }
          ]
        }
 ```

**Comment by acao** [comment]
thanks! i will try that

one thing to note - languages such as php, vue or svelte that provide `text.html.*`  do not work with the approach I found to work. either way, the PR has been updated with a working solution. i will come back to this tomorrow as well!

**Comment by RedCMD** [comment]
not sure if you are trying to use it
but VSCode TextMate currently doesn't support the any scope selector `*` inside `"injectionSelector"`
https://github.com/microsoft/vscode-textmate/issues/160

> Is there a way I can achieve this result with `L:markup.fenced_code.block.markdown`

`markup.fenced_code.block.markdown` is a generic scopename for all markdown code blocks
you would have no easy way of knowing which language it corresponded to (without using lookbehinds)
VSCode Markdown has a slightly different regex to yours
![image](https://github.com/microsoft/vscode/assets/33529441/43315747-b2eb-47eb-83b3-69db2c28966e)


you could potentially inject directly into `meta.embedded.block.javascript`
tho you'll need a seperate file for each language
`"injectionSelector": "L:meta.embedded.block.javascript -inline.graphql -source.js"`
maybe something like this might work?
![image](https://github.com/microsoft/vscode/assets/33529441/56e2ebc5-3c2b-4797-9ed0-be1d7f614c29)

This problem would need to be fixed by `inline.graphql` injecting/handling `source.js` better
![image](https://github.com/microsoft/vscode/assets/33529441/ce79c564-f14c-4642-8deb-9ae2c6e985bc)

**Comment by aeschli** [comment]
Thanks @RedCMD for helping. I now know who to ask when I have a problem with grammar injection :-)

@acao Is your problem solved? If you believe there's a bug on how we apply injections, then the issue would have to go against https://github.com/Microsoft/vscode-textmate

**Comment by acao** [comment]
@aeschli the bug is not solved really, but I don't think its a problem with how the injections are applied

**Comment by RedCMD** [comment]
always glad to help 😊 

@acao I've just realized. `package.json` already injects `inline-graphql` into `source.js` etc
I guess `"injectTo"` only applies to the top level scopename
maybe simply just adding `text.html.markdown` to that list will fix everything (revert all your previous changes)

**Comment by RedCMD** [comment]
`"injectionSelector": "L:(meta.embedded.block.javascript | meta.embedded.block.typescript | source.js | source.ts | source.tsx | source.vue | source.svelte) -source.graphql -inline.graphql -string -comment"`
![image](https://github.com/microsoft/vscode/assets/33529441/f84f89f3-44d3-4d93-baf2-f8f2b036d790)
![image](https://github.com/microsoft/vscode/assets/33529441/0b515504-537b-475e-9e8c-137e43d41785)
![image](https://github.com/microsoft/vscode/assets/33529441/e71c4f0d-816c-48a8-b72a-4c754a7ae336)

and the `markdown.graphql.codeblock.json` grammar injects itself in too eagerly
should add `-meta.embedded.block` to the `"injectionSelector"`
![image](https://github.com/microsoft/vscode/assets/33529441/3cb00f23-8e0b-4b98-8c89-f5378ae9b7f2)
