### ISSUE TITLE
Tab is broken in the latest insider release

### ISSUE THREAD

**Issue by rwatts3** [Microsoft/vscode#20209]
- VSCode Version: Code - Insiders 1.10.0-insider (eff9148502fd3edf42573beb16006bee533c3cf9, 2017-02-08T07:05:20.062Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-class-suggestions|AndersEAndersen|1.0.3|
|EditorConfig|EditorConfig|0.3.4|
|JSDocTagComplete|HookyQR|0.0.2|
|vscode-cheatsheet|MattiasPernhult|0.1.1|
|vscode-docker|PeterJausovec|0.0.11|
|code-settings-sync|Shan|2.4.3|
|vscode-wakatime|WakaTime|1.0.6|
|Bookmarks|alefragnani|0.10.2|
|project-manager|alefragnani|0.13.2|
|Handlebars|andrejunges|0.2.0|
|vscode-database|bajdzis|1.2.0|
|typings-installer|benjaminromano|0.2.0|
|npm-intellisense|christian-kohler|1.2.1|
|path-intellisense|christian-kohler|1.2.0|
|bower|donjayamanne|0.0.3|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.6|
|tslint|eg2|0.8.1|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|vscode-npm|fknop|3.3.0|
|auto-close-tag|formulahendry|0.3.9|
|code-runner|formulahendry|0.6.9|
|Theme-dimmed-monokai|gerane|0.0.2|
|vscode-auto-open-markdown-preview|hnw|0.0.3|
|ColdFusion|ilich8086|0.0.5|
|graphql-for-vscode|kumar-harsh|1.1.1|
|ftp-sync|lukasz-wronski|0.3.2|
|sublime-keybindings|ms-vscode|1.9.2|
|vuehelper|oysun|0.0.7|
|vscode-icons|robertohuertasm|7.2.0|
|todotasks|sandy081|0.4.0|
|vue|seanwash|0.4.2|
|slack|sozercan|0.0.8|
|vscode-meteor|vuhrmeister|0.1.1|
|change-case|wmaurer|1.0.0|
|swig|zhutian|0.0.5|

---

Steps to Reproduce:

1. Enter a document to edit.
2. Try to press the tab key, nothing happens.

**Comment by hrgui** [comment]
I thought my keyboard wasn't working when I couldn't tab today in VSCode...

**Comment by rwatts3** [comment]
It was definitely this latest release, because I was writing code at 3 AM and did not have this problem until after I updated.

**Comment by SethCopeland** [comment]
I found a workaround for now by adding this setting.

`"emmet.triggerExpansionOnTab": false`

I figured that out based on @admmasters comment [here](https://github.com/Microsoft/vscode/issues/20206#issuecomment-278391990) about commit 239b199

**Comment by bobmagicii** [comment]
amen @SethCopeland you beautiful person. i had tried toggling so many random settings, except that one. and that was the one.

**Comment by ramya-rao-a** [comment]
The fix is in the latest insiders.

**Comment by ogrotten** [comment]
Is there a keystroke or something that changes `"emmet.triggerExpansionOnTab": false` on the fly to `true`? I was happily running along, for several hours, then all of a sudden tab was only moving between UI elements of the program, not inserting indentation. 

Even tho that setting was already set to false, I put that line my user settings, restarted VSC, and now eveyrthing is back to normal.

**Comment by jackpot1136** [comment]
Thank the Lord and all of you people that helped me bring the truth out.
I would like to file a case against Brian Moore for herrasment and falsification

**Comment by alexjamesbrown** [comment]
This fixed it for me:
https://stackoverflow.com/a/42458207/131809

Ctrl+M Toggle Use of Tab Key for Setting Focus 

I'd pressed ctrl+m+o trying to collapse code blocks!

**Comment by ogrotten** [comment]
Yes! ctrl-m is it!
