### ISSUE TITLE
GLIBC version requirement is incorrectly hardcoded in error message

### ISSUE THREAD

**Issue by standamo** [microsoft/vscode#202082]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  
Version: 1.86.0-insider (user setup)
Commit: fb769554405bee9be16e21ceb0a496bd29126941
Date: 2024-01-09T09:57:14.563Z
Electron: 27.2.1
ElectronBuildId: 26149897
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

- OS Version: RHEL7.9 or CentOS 7

Steps to Reproduce:

Remote-SSH to RHEL/CentOS 7 fails to setup.
Running the remote manually shows a reason:

```
$ ./.vscode-server-insiders/code-insiders-fb769554405bee9be16e21ceb0a496bd29126941
[2024-01-09 09:20:19] error This machine not meet Visual Studio Code Server's prerequisites, expected either...:   - find GLIBC >= 2.17 (but found v2.17.0 instead) for GNU environments
  - find /lib/ld-musl-x86_64.so.1, which is required to run the Visual Studio Code Server in musl environments
```

The message is misleading however.
The system has GLIBC2.17 so it should not fail based on the message:
```
$ ldd --version|head -1
ldd (GNU libc) 2.17
```

The problem is that the check is really for `MIN_LDD_VERSION` which is now 2.28, It's only that '2.17' is incorrectly hardcoded in `check_glibc_version()` which is misleading,
See:
https://github.com/microsoft/vscode/blob/66bf39bd4e2e1822da2964f4b03bc364ce067c68/cli/src/util/prereqs.rs#L144

**Comment by M0Cube** [comment]
[root@xxxx ~]# cat /root/.vscode-server-insiders/.cli.fb769554405bee9be16e21ceb0a496bd29126941.log
[2024-01-10 09:16:45] error This machine not meet Visual Studio Code Server's prerequisites, expected either...:   - find GLIBC >= 2.17 (but found v2.17.0 instead) for GNU environments
  - find /lib/ld-musl-x86_64.so.1, which is required to run the Visual Studio Code Server in musl environments
  
  遇到了同样的问题

**Comment by b4sjoo** [comment]
Same issue here. 
```
[2024-01-10 22:10:53] error This machine not meet Visual Studio Code Server's prerequisites, expected either...:   - find GLIBC >= 2.17 (but found v2.26.0 instead) for GNU environments
```

**Comment by Jianxff** [comment]
Same issue.
```
error This machine not meet Visual Studio Code Server's prerequisites, expected either...:   - find GLIBC >= 2.17 (but found v2.27.0 instead) for GNU environments
```

**Comment by ixomaxip** [comment]
the same issue, but with additional lib:
```
error This machine not meet Visual Studio Code Server's prerequisites, expected either...: 
  - find GLIBC >= 2.17 (but found v2.27.0 instead) for GNU environments
  - find /lib/ld-musl-x86_64.so.1, which is required to run the Visual Studio Code Server in musl environments
/root/.vscode-server-insiders/.cli.29bef5673ebb1fc3a59b90c9d8bfd2bc61c3f011.log
```

**Comment by justschen** [comment]
cc @roblourens or @connor4312 ? looks like a linux/c version issue?

**Comment by mherkazandjian** [comment]
same here, remote host is centos 7

```
└─╼ ~/.vscode-server-insiders $ ./code-insiders-81725794264e4c0fddbc1b3b728013744ae90840
[2024-01-15 17:56:40] error This machine not meet Visual Studio Code Server's prerequisites, expected either...:   - find GLIBC >= 2.17 (but found v2.17.0 instead) for GNU environments
  - find /lib/ld-musl-x86_64.so.1, which is required to run the Visual Studio Code Server in musl environments
┌─[17:56:40 mherk@faros]->(1) conda311
└─╼ ~/.vscode-server-insiders $ rpm -qa | grep glibc
glibc-headers-2.17-326.el7_9.x86_64
glibc-common-2.17-326.el7_9.x86_64
glibc-2.17-326.el7_9.x86_64
glibc-devel-2.17-326.el7_9.x86_64
```

**Comment by menzer2015** [comment]
I get this error also am on centos 7, I am trying to use an older version which I have but now joy is there a fix for this?

error This machine does not meet Visual Studio Code Server's prerequisites, expected either...:   - find GLIBC >= v2.28.0 (but found v2.17.0 instead) for GNU environments
  - find /lib/ld-musl-x86_64.so.1, which is required to run the Visual Studio Code Server in musl environments
Any help or advice or patch appreciated thanks

**Comment by rkkris75** [comment]
Same here. Having the same issue since this morning. I am on Amazon linux 2

**Comment by djnighti** [comment]
same issue happening today, heres my computer info:
Version: 1.86.0
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:27:46.147Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.5.0-15-generic snap

**Comment by Jhin3433** [comment]
Same here.

**Comment by minyinhho** [comment]
same issue happening here
 error This machine does not meet Visual Studio Code Server
 This machine does not meet Visual Studio Code Server's prerequisites, expected either...: - find GLIBC >= v2.28.0 (but found v2.17.0 instead) for GNU environments.

**Comment by HadXu** [comment]
> [2024-02-02 09:20:05] error This machine does not meet Visual Studio Code Server
> 's prerequisites, expected either...:   - find GLIBC >= v2.28.0 (but found v2.27
> .0 instead) for GNU environments
>   - find /lib/ld-musl-x86_64.so.1, which is required to run the Visual Studio Co
> de Server in musl environments

**Comment by mherkazandjian** [comment]
same issue here.

**Comment by rkkris75** [comment]
> Same here. Having the same issue since this morning. I am on Amazon linux 2

I have downgraded the VS code version from 1.86 back to 1.85, with that change now able to connect to my remote EC2 host.

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/203967#issuecomment-1923440629
