### ISSUE TITLE
HTML formatting broken when tag is too long

### ISSUE THREAD

**Issue by RaananW** [Microsoft/vscode#20204]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|angular-material-snippets|4tron|0.3.1|
|bracket-pair-colorizer|CoenraadS|0.2.1|
|vscode-svgviewer|cssho|1.3.1|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.8|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|autofilename|JerryHong|0.1.3|
|docthis|joelday|0.3.10|
|Angular2|johnpapa|1.0.2|
|code-beautifier|michelemelluso|1.6.2|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.5.2|
|java|redhat|0.0.9|
|vscode-icons|robertohuertasm|7.2.0|
|partial-diff|ryu1kn|0.2.0|
|vscode-sql-beautify|sensourceinc|0.0.4|
|autoimport|steoates|1.2.2|
|code-spell-checker|streetsidesoftware|0.17.2|
|local-history|xyz|1.1.0|
|html-css-class-completion|Zignd|1.0.3|

---

When trying to format an html file with html tags that spread accross two or more lines, the closing html tag stays at the same level of the content and doesn't go back. 
Example:

Expected:

```html
<md-autocomplete ng-if="$ctrl.parentSelect" flex md-selected-item="$ctrl.parent" md-selected-item-change="$ctrl.selectParent(item)"
    md-search-text="$ctrl.searchText" md-items="item in $ctrl.getResources($ctrl.searchText)" md-item-text="item.title" md-min-length="2"
    md-floating-label="Parent">
.......
</md-autocomplete>
```

After formatting with vscode:

```html
<md-autocomplete ng-if="$ctrl.parentSelect" flex md-selected-item="$ctrl.parent" md-selected-item-change="$ctrl.selectParent(item)"
    md-search-text="$ctrl.searchText" md-items="item in $ctrl.getResources($ctrl.searchText)" md-item-text="item.title" md-min-length="2"
    md-floating-label="Parent">
    .......
    </md-autocomplete>
```

**Comment by chimon2000** [comment]
Also seeing this as of latest release.

**Comment by aeschli** [comment]
Reproduced on http://jsbeautifier.org/

**Comment by aeschli** [comment]
This issue was moved to beautify-web/js-beautify#1129

**Comment by HookyQR** [comment]
This is fixed in the [beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) extension.
