### ISSUE TITLE
use checkboxes for help: list alerts/audio cues

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#202025]
When using the `Help: List Audio Cues` command, Roberto did not know there was a configure action available. He said:

              It works, but in all my time using the editor, it never occurred to me to try using the tab key in that list. I always assumed it was read only.

_Originally posted by @rperez030 in https://github.com/microsoft/vscode/issues/201910#issuecomment-1879295647_

**Comment by meganrogge** [comment]
@jooyoungseo also faced this discoverability issue. Additionally, he found that `tab` has to be pressed twice to reach the settings gear when running `Help: List Audio Cues`.

**Comment by meganrogge** [comment]
He suggested we use checkboxes instead and combine `alert` with `audio cues`.

**Comment by meganrogge** [comment]
Need to assess which other actions we need to fix

**Comment by isidorn** [comment]
I think it is possible using the quick pick api to render checkboxes for this.
Let me un-assign Tyler and in case you need help with the API feel free to reach out to me and we can find the right usage.
