### ISSUE TITLE
Files navigatio vanishing after clicking on any other option such as extension tabs: Kali Linux

### ISSUE THREAD

**Issue by scienmanas** [microsoft/vscode#202117]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1.  Click on extension tab or any other tab
2.  The file navigation menu disappears

Photos: 

![image](https://github.com/microsoft/vscode/assets/99756067/32780c81-ff6a-4ca1-a674-bad9cbe7fc91)

**Comment by gjsjohnmurray** [comment]
I suggest you use the `Reset View Locations` command from the Command Palette (F1).

Then if you are able to give exact steps to reproduce the issue again please add them here.

**Comment by scienmanas** [comment]
I did it, still it didn't solve.

[Screencast from 2024-01-10 13-48-16.webm](https://github.com/microsoft/vscode/assets/99756067/9f813beb-f4d4-410f-8a6c-28e9b73647ea)

**Comment by scienmanas** [comment]
Ok, it worked, thanks.
