### ISSUE TITLE
Tab key does nothing on html file

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#20210]
- VSCode Version: Code - Insiders 1.10.0-insider (eff9148502fd3edf42573beb16006bee533c3cf9, 2017-02-08T07:10:29.700Z)
- OS Version: Windows_NT ia32 10.0.15025
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|theme-dracula|dracula-theme|1.2.5|
|vscode-great-icons|emmanuelbeziat|1.1.43|
|Theme-azure|gerane|0.0.2|
|theme-material-theme|jprestidge|1.0.1|
|vs-color-picker|lihui|0.4.0|
|Theme-MaterialKit|ms-vscode|0.1.1|
|view-in-browser|qinjia|0.0.5|
|java|redhat|0.0.9|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|eval|Stormspirit|0.0.5|
|omnipascal|Wosi|0.12.0|

---

Steps to Reproduce:

1. open an html file
2. press tab

Nothing happens. Tab only seem to work if some text has been selected.

**Comment by SethCopeland** [comment]
It is not just HTML files. See #20209.
