### ISSUE TITLE
Allow disabling the "save workspace" dialog

### ISSUE THREAD

**Issue by ChristopherJTrent** [microsoft/vscode#202173]
I'd like to have a toggle that will make vscode skip asking me to save my workspace every time I close a window that was duplicated.

I cannot imagine a single situation where I would want to save the configuration of a transient duplicate window to disk, so the popup only serves to add an extraneous click to an already click-heavy application in my use-case.

**Comment by gjsjohnmurray** [comment]
Insiders already has a `window.confirmSaveUntitledWorkspace` setting, but this seems to be new enough that it's not yet in Stable.

**Comment by ChristopherJTrent** [comment]
closing as already implemented per John's comment. 
I will await seeing this in stable as insider builds are unavailable for Code - OSS.
