### ISSUE TITLE
Trouble with scripts\npm.bat: it calls itself

### ISSUE THREAD

**Issue by dubeg** [Microsoft/vscode#2021]
I don't know if it's supposed to be different, but the call to `npm %*` in the file `scripts\npm.bat` seems to call itself. I had to rename the bat file to something like `pre-npm.bat` for it to work properly.

Is it supposed to work without renaming it?

**Comment by joaomoreno** [comment]
@dubeg Don't call it from the `scripts` directory, but from the root of the repository.

**Comment by dubeg** [comment]
Oh, yeah. Sorry
