### ISSUE TITLE
shared `terminal.integrated.env` for all platforms

### ISSUE THREAD

**Issue by farfromrefug** [microsoft/vscode#202144]
Right now when you need integrated terminal env you have to define either `terminal.integrated.env.osx`, `terminal.integrated.env.linux`, `terminal.integrated.env.windows`.
It works nicely but when you work on all platforms you need to duplicate settings for all platforms which is quite a pain. Maintenance is not fun.

Would be really awesome if we could have `terminal.integrated.env.shared` or something like that to have shared env variables (which would get overriden by `terminal.integrated.env.osx` ... ).

It is kind of the same thing with `terminal.integrated.profiles.osx`. Would be also awesome to be able to share profiles for all platforms

**Comment by meganrogge** [comment]
thanks for the issue. `env` on each platform can be quite different, so it's not worth adding this IMO. 

Similarly, the `profiles` are quite different per platform. 

@Tyriar can reopen if he disagrees.
