### ISSUE TITLE
Hi! friend! Duplicate search results

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#202122]
Hi! friend! Duplicate search results
Windows 10 19044
VSCode 1.84~1.85.1

![Wrong search results](https://github.com/microsoft/vscode/assets/54253524/e8d27182-1a5c-411c-8cb3-5a24e4153f83)

**Comment by zhouxinghong** [comment]
If there are multiple search results, it will definitely cause trouble to users.

**Comment by gjsjohnmurray** [comment]
Do you have the `Toggle Context Lines` button selected?

![image](https://github.com/microsoft/vscode/assets/6726799/4ccda5a4-3695-4d1b-9938-f446956c5e4f)

Is the workspace you ar searching in a local folder? Or is it something different (e.g. remote WSL)?

Can you reproduce the issue with a folder cloned from a public repo, e.g. https://github.com/microsoft/vscode-extension-samples ?

**Comment by zhouxinghong** [comment]
I searched the vscode local workspace folder

**Comment by gjsjohnmurray** [comment]
> I searched the vscode local workspace folder

Here's what I get when I search a local folder into which I have cloned https://github.com/microsoft/vscode

![image](https://github.com/microsoft/vscode/assets/6726799/c6f18e7a-ffb6-4767-a083-c2eb1c7feb0d)

Which repo are you seeing this happen with?

Does it also happen after you run the `Profiles: Create a Temporary Profile` command?

**Comment by zhouxinghong** [comment]
1. I used what I saw in the vscode extension project I created;
2. I am currently using vscode 1.84.2;
3. Operating system: Windows 10 19044;

**Comment by gjsjohnmurray** [comment]
When not using the temporary profile please use the `Start Extension Bisect` command to investigate.

**Comment by zhouxinghong** [comment]
`When not using the temporary profile please use the Start Extension Bisect command to investigate.`
OK! Thank you for your help! 👍 Also, I will try in vscode 1.86 to see if the same problem occurs.

**Comment by zhouxinghong** [comment]
`You're seeing this on 1.85? This might be a duplicate of `
I am currently using vscode 1.84.2;

**Comment by andreamah** [comment]
Can you try on the latest version?

**Comment by zhouxinghong** [comment]
What is the latest version?

**Comment by andreamah** [comment]
https://code.visualstudio.com/updates/v1_85

**Comment by zhouxinghong** [comment]
No! 1.85 has too many bugs, let’s wait until 1.86 is released before testing it! Thank you very much!

**Comment by andreamah** [comment]
Ok, please let me know once you test it.

**Comment by zhouxinghong** [comment]
ok

**Comment by zhouxinghong** [comment]
@andreamah Thank you very much! This issue has been fixed!
