### ISSUE TITLE
Site not responding

### ISSUE THREAD

**Issue by jtgood07** [microsoft/vscode#202104]
![github errors](https://github.com/microsoft/vscode/assets/156017807/3bd35570-7656-40e0-bdd4-8c5812c7c732)
When I run code through the port it says site not responding contact site owner.

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by alexr00** [comment]
@jtgood07 how did you open that editor tab with the `https://congenial-space...` url in it?

**Comment by jtgood07** [comment]
________________________________

**Comment by jtgood07** [comment]
________________________________
