### ISSUE TITLE
Paused inline chat resumes with wrong "diff"

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#202164]
* open the same file in two editor columns
* start inline chat
* get AI changes
* in column A switch to another file
* in column B makes changes to the original file (w/o overlap of the AI chnages)
* in column A switch back
* the UI suggests that all edits (yours and AIs) are AI edits

**Comment by eleanorjboyd** [comment]
really appreciate that after this step "in column B makes changes to the original file (w/o overlap of the AI chnages)" I accidentally saved the file and it jumped me to the other editor with the AI suggestion and required them to be resolved before I could finish saving. Great flow for that complicated edge case!!
