### ISSUE TITLE
API Request: Support for "faded" code

### ISSUE THREAD

**Issue by DustinCampbell** [Microsoft/vscode#20219]
This a request from the C# for VS Code extension to provide a way for a diagnostic to present itself as "faded" code. Note that this is orthogonal to the squiggle that appears. It's completely expected that a diagnostic could be "faded" while still appearing with a red, green, or no squiggle.

This is needed to support core editing experiences that we have in Visual Studio for code fixes like "Remove Unnecessary Usings", or "Remove Redundant Cast".

![fadedusingdirectives](https://cloud.githubusercontent.com/assets/116161/22749089/02c5964e-ede1-11e6-868e-8fe3c0134ff9.png)

cc @Eilon

**Comment by jrieken** [comment]
@alexandrudima This might be fitting into semantic highlighting?

**Comment by DustinCampbell** [comment]
Potentially, that's how it's ultimately implemented under the hood in VS as presentation. Logically, we included in the Roslyn diagnostics API. I'll leave it up to you all to figure out how you'd best expose this to VS Code extensions.

**Comment by 0xdeafcafe** [comment]
Any progress on this?

**Comment by jrieken** [comment]
no progress on this

**Comment by rchande** [comment]
@jrieken TypeScript in VS Code now fades unused members--what API do they use to do that? It sounds like that's the same as what's requested here?

**Comment by mjbvz** [comment]
Addressed by #51104

https://github.com/Microsoft/language-server-protocol/issues/500 tracks this for the LSP
