### ISSUE TITLE
Multifile diff editor is all grey on start/load

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#202137]
* use light theme
* open a multifile diff editor for the first time
* while it loads its background is grey, much darker than the default editor background color

https://github.com/microsoft/vscode/assets/1794099/b1f314a8-64f9-4ce5-bafd-408daf4b31d2

**Comment by joaomoreno** [comment]
💡 Why not simply reusing the sidebar background color as the multi-file diff editor background color?

<img width="2029" alt="image" src="https://github.com/microsoft/vscode/assets/22350/b3b8899f-1b39-4480-b22e-233ca248d583">

<img width="2029" alt="image" src="https://github.com/microsoft/vscode/assets/22350/0085b434-60df-45ff-ae49-fc1f68fec44f">

**Comment by hediet** [comment]
Hylkes ideas:

![image](https://github.com/microsoft/vscode/assets/2931520/ce6f4442-3093-4aea-ae10-24154030eb10)


![image](https://github.com/microsoft/vscode/assets/2931520/940523cb-ec70-4d2e-b0d6-a7577872ea99)

**Comment by jrieken** [comment]
> 💡 Why not simply reusing the sidebar background color as the multi-file diff editor background color?

I think that's confusing, your screen shot makes it not clear where the editor ends and where the panel starts. For text editors we fill up remaining space with the editor default background color and IMO we should do the same for this editor. 

<img width="657" alt="Screenshot 2024-01-24 at 11 22 28" src="https://github.com/microsoft/vscode/assets/1794099/3b9b6b85-77fb-4386-90d5-914b0c0ff74c">

**Comment by jrieken** [comment]
> Hylkes ideas:

I like the coloring but not the extra indent but I also don't believe that is needed to solve this issue

**Comment by hbons** [comment]
@jrieken I didn't add the extra indent. looks like a bug.

**Comment by bpasero** [comment]
Maybe I am missing something, but why can the multi-diff editor not have the same background color as text editors and notebooks? I see no unexpected color when I open a notebook while it is loading.

**Comment by hediet** [comment]
Fixed in #203499
