### ISSUE TITLE
I can't open any thing use vs code after M1 update to Sonoma 14.2.1.

### ISSUE THREAD

**Issue by yesterdaytime** [microsoft/vscode#202134]
### Issue:
After the Mac M1 update to 14.2.1, sometimes, I restart my Mac, and the vs code can't open any finder. 

### Code status 
```
Version:          Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS Version:       Darwin arm64 23.2.0
CPUs:             Apple M1 Pro (10 x 24)
Memory (System):  32.00GB (2.40GB free)
Load (avg):       9, 10, 9
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id 068cbb19-5bc9-4648-a1ed-4e6a1353cb4b
GPU Status:       2d_canvas:                              enabled
                  canvas_oop_rasterization:               enabled_on
                  direct_rendering_display_compositor:    disabled_off_ok
                  gpu_compositing:                        enabled
                  multiple_raster_threads:                enabled_on
                  opengl:                                 enabled_on
                  rasterization:                          enabled
                  raw_draw:                               disabled_off_ok
                  video_decode:                           enabled
                  video_encode:                           enabled
                  vulkan:                                 disabled_off
                  webgl:                                  enabled
                  webgl2:                                 enabled
                  webgpu:                                 enabled

CPU %	Mem MB	   PID	Process
    2	   197	  8605	code main
    0	    66	  8608	   gpu-process
    0	    66	 34585	window [2] (Visual Studio Code)
    7	    33	 80138	   utility-network-service

```

#### Some trying but not work
- Restart  mac
- Code --disable-gpu
- Kill all the processes and restart vs code.

This is the screenshot, I can't open any items, and even though I want to see the **About Visual Studio Code**, I can't open it. Run `code ./` shows this screenshot too. 
![image](https://github.com/microsoft/vscode/assets/14917134/c13e7a6a-bc17-4e6e-98e1-9e82d5c2227d)

Who knows how to fix this?

**Comment by deepak1556** [comment]
Can you provide the output of `code --verbose`

**Comment by yesterdaytime** [comment]
Hi @deepak1556 This is the verbose

```
[0110/182750.352323:ERROR:crash_report_database_mac.mm(753)] open lock /Users/xxx/Library/Application Support/Code/Crashpad/pending/f43a2901-627c-4a45-a87a-365facb436d7.dmp: Resource temporarily unavailable (35)
[0110/182750.353960:ERROR:crash_report_database_mac.mm(753)] open lock /Users/xxx/Library/Application Support/Code/Crashpad/pending/18c951e4-775a-4b3b-9875-1df10a2558bc.dmp: Resource temporarily unavailable (35)
2024-01-10 18:27:50.364 Electron[52521:3055987] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
[52533:0110/182750.400364:ERROR:validation_errors.cc(117)] Invalid message: VALIDATION_ERROR_DESERIALIZATION_FAILED
[52533:0110/182750.401247:WARNING:network_service.cc(217)] Mojo error in NetworkService: Received bad user message: Validation failed for network.mojom.NetworkService.4  [VALIDATION_ERROR_DESERIALIZATION_FAILED]
[main 2024-01-10T10:27:50.432Z] [File Watcher (node.js)] Request to start watching: /Users/xxx/Library/Application Support/Code/User (excludes: <none>, includes: <all>, correlationId: <none>),/Users/xxx/Library/Application Support/Code/User/settings.json (excludes: <none>, includes: <all>, correlationId: <none>)
[main 2024-01-10T10:27:50.437Z] Sending env to running instance...
[main 2024-01-10T10:27:50.445Z] [File Watcher (node.js)] Started watching: '/Users/xxx/Library/Application Support/Code/User'
[main 2024-01-10T10:27:50.446Z] [File Watcher (node.js)] Started watching: '/Users/xxx/Library/Application Support/Code/User/settings.json'
[main 2024-01-10T10:27:50.452Z] Sent env to running instance. Terminating...
[main 2024-01-10T10:27:50.452Z] Lifecycle#kill()
[main 2024-01-10T10:27:50.453Z] Lifecycle#onWillShutdown.fire()
[52533:0110/182750.598759:ERROR:interface_endpoint_client.cc(697)] Message 647314295 rejected by interface network.mojom.NetworkService
```

**Comment by basicsmods** [comment]
A flavour of this has been happening to me since I updated my vscode a week or two ago. I'm also on macos Sonoma. I pretty much exclusively use vscode with remote workspaces and when I close my laptop for a while and then re-open it, my vscode windows have lost their connection and need to be reloaded (and I'm conveniently presented with a prompt asking me if I want to reload / reopen). Occasionally, reloading from this situation results in just a completely blank window that I cannot interact with. (I can't press cmd+shift+p to issue another reload and using the menu bar at the top of my screen to click File > Open Recent > and selecting the remote workspace I want to reload does nothing; so my only option is to close that window and re-open it manually. This can be very annoying because I often have multiple different remote workspaces open in different vscode windows for all the different work tasks I'm jumping between and it's easy to forget which one is the one that bricked and needs to be reloaded.)

Here is my output for `code --verbose` while a bricked window is currently open
```
> code --verbose
2024-01-10 10:23:21.840 Electron[27094:29160723] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
[main 2024-01-10T18:23:21.933Z] [File Watcher (node.js)] Request to start watching: /Users/patrick/Library/Application Support/Code/User (excludes: <none>, includes: <all>, correlationId: <none>),/Users/patrick/Library/Application Support/Code/User/settings.json (excludes: <none>, includes: <all>, correlationId: <none>)
[main 2024-01-10T18:23:21.940Z] Sending env to running instance...
[main 2024-01-10T18:23:21.941Z] [File Watcher (node.js)] Started watching: '/Users/patrick/Library/Application Support/Code/User'
[main 2024-01-10T18:23:21.942Z] [File Watcher (node.js)] Started watching: '/Users/patrick/Library/Application Support/Code/User/settings.json'
[main 2024-01-10T18:23:22.044Z] Sent env to running instance. Terminating...
[main 2024-01-10T18:23:22.044Z] Lifecycle#kill()
[main 2024-01-10T18:23:22.044Z] Lifecycle#onWillShutdown.fire()
```

Here is my version (same for both my local machine and my remote machine):
```
> code --version
1.85.1
0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
arm64
```



<img width="1524" alt="Screenshot 2024-01-10 at 10 20 13 am" src="https://github.com/microsoft/vscode/assets/108436227/a4138784-f364-49d0-bcab-acec30e4d95e">

**Comment by deepak1556** [comment]
@yesterdaytime thanks for the logs, there seems to be a crash in the network process, can you follow the steps here https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report and attach the crash reports.

**Comment by deepak1556** [comment]
@basicsmods `code --verbose` should be called before opening any vscode instance. Can you recreate the logs for your scenario and attach them here.

**Comment by basicsmods** [comment]
> @basicsmods `code --verbose` should be called before opening any vscode instance. Can you recreate the logs for your scenario and attach them here.

Unfortunately I'm not able to reproduce the issue consistently. It just happens from time to time when I open my laptop and have to reopen / reload my remote workspaces. And I generally have multiple of these remote workspaces active so all of them will need to be reloaded (at least the ones that I want to work on), but if one of them fails and results in the blank screen, that doesn't mean any of the others will fail as well.

If I figure out a way to reproduce it consistently, I'll be sure to report it with the relevant logs.

**Comment by yesterdaytime** [comment]
@deepak1556 I generate the reports. In the report folder, only the pending folder has some dmp files, other folder is empty. This is one dmp output:

```
Symbolicating...
Operating system: Mac OS X
                  14.2.1 23C71
CPU: arm64
     10 CPUs

GPU: UNKNOWN

Crash reason:  Simulated Exception
Crash address: 0x1193f853c
Process uptime: 0 seconds

Thread 6 (crashed)
.....
```

**Comment by deepak1556** [comment]
@yesterdaytime can you zip up the contents of pending folder and attach them here, thanks

**Comment by yesterdaytime** [comment]
@deepak1556  [1330d7a8-6559-4651-8d3e-91cfbc754eba.dmp](https://github.com/microsoft/vscode/files/13899536/1330d7a8-6559-4651-8d3e-91cfbc754eba.dmp)
This is the dmp file.

**Comment by yesterdaytime** [comment]
Hi @deepak1556 This is the report
[logs.zip](https://github.com/microsoft/vscode/files/13899562/logs.zip)

**Comment by deepak1556** [comment]
@yesterdaytime do you have any proxy configured in the system, crash can happen from malformed proxy values.

**Comment by yesterdaytime** [comment]
Hi @deepak1556 
After I close the proxy from the system and iterm 2, I can open vs code. Thanks very much.

**Comment by deepak1556** [comment]
Thanks for confirming, merging to https://github.com/microsoft/vscode/issues/138364
