### ISSUE TITLE
Queue and ResourceQueue issues

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#202136]
I have been adding a `clear` function to `Queue` and with that also looked at its dispose method. Today, it only disposes the drain-emitter but it doesn't clear the work queue nor does it prevent new enqueuing of tasks. When doing so (on dispose nuke pending tasks and prevent further enqueuing) the tests for `ResourceQueue` start failing. This is because the resource queue disposes queues on drain. This means consumers that hold on to such a queue (as [this test](https://github.com/microsoft/vscode/blob/0a08e6fdcd514741ceb679fb38c746550b5aabf3/src/vs/base/test/common/async.test.ts#L734)) will now have a doomed queue (which today never fires). 

Because this is used in save-land I have commented my changes (except for the new clear) method but it seems that even today there is issues with dead queues that have been acquired from the resource queue data structure

**Comment by jrieken** [comment]
It's now in `main`. Enable [this test](https://github.com/microsoft/vscode/blob/8ffbf09e3114b624cdd77b568a1a406ad3e0ab28/src/vs/base/test/common/async.test.ts#L514) after uncommenting things from `Limiter#dispose`

**Comment by bpasero** [comment]
This is a good catch and I think the flaw is that `ResourceQueue.queueFor` returns the actual `Queue` object which gets disposed when drained. I think all clients of this method actually call the `queue` method, so its probably safe the way it works now even with your change, but I would probably change the utility in a way that you can `queue` something for a resource and that is handled internally without ever passing out the actual `Queue` instance.
