### ISSUE TITLE
Markdown doesn't sync when folder isn't open

### ISSUE THREAD

**Issue by vladamx** [Microsoft/vscode#20214]
- VSCode Version: 1.9
- OS Version: Windows 10

Steps to Reproduce:

1. Open standalone markdown file 
2. Preview it
3. On selection or scroll nothing happens

**Comment by mjbvz** [comment]
I believe this may be fixed by #20064.

Please try out the latest insiders build or 1.9.1 when it comes out and let me know if you are still running into this problem

Thanks
