### ISSUE TITLE
Key Tab is not working

### ISSUE THREAD

**Issue by InKiev** [Microsoft/vscode#20218]
- VSCode Version: Code - Insiders 1.10.0-insider (eff9148502fd3edf42573beb16006bee533c3cf9, 2017-02-08T07:10:29.700Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|one-monokai|azemoh|0.2.4|
|path-intellisense|christian-kohler|1.2.0|
|Theme-monokai-best|gerane|0.0.2|
|tsimporter|pmneo|1.2.13|
|vscode-icons|robertohuertasm|7.2.0|
|todotasks|sandy081|0.4.0|

---

Steps to Reproduce:

1. Open a file
2. Point the cursor at the beginning of a line of code
3. Press Tab Key

It should indent my code, it's doing nothing and in some situations it navigates the different editor sections, for example, Explorer, Search, Git, etc

**Comment by smlombardi** [comment]
This is also broken on Mac 10.12.3.

**Comment by WillAnd31** [comment]
I am able to use it for intellisense, but nothing else seems to work with the tab key. I'm on Mac 10.12.3, with the latest build of VSCode insiders from this morning.

**Comment by bobmagicii** [comment]
THANK GOD I AM NOT GOING CRAZY :D

![image](https://cloud.githubusercontent.com/assets/881944/22755325/4afba22e-ee08-11e6-843a-5010df1375c8.png)

no matter what i do. tab tab tab tab TAB TAB TAB TABATABATRBATABABHAFDKDJGDSALFJDABATABATBABADFFFF

**Comment by bobmagicii** [comment]
this guy's work around worked for me. https://github.com/Microsoft/vscode/issues/20209#issuecomment-278428711

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/20209
