### ISSUE TITLE
TS language server crashes

### ISSUE THREAD

**Issue by Varun-Dhruv** [microsoft/vscode#202143]
Type: <b>Bug</b>

Open VS code

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 6.1.0-17-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4500U with Radeon Graphics (6 x 2487)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 1|
|Memory (System)|7.15GB (1.25GB free)|
|Process Argv|. --crash-reporter-id 3372fa1f-30d9-4030-b758-46a3f340d128|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|GNOME|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (84)</summary>

Extension|Author (truncated)|Version
---|---|---
nestjs|ash|1.4.2
vscode-django|bat|1.15.0
vscode-tailwindcss|bra|0.11.39
simple-react-snippets|bur|1.2.7
doxdocgen|csc|1.4.0
gitlab-ci-validator|cst|1.0.0
c-cpp-compile-run|dan|1.0.50
python-environment-manager|don|1.2.4
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.6.1
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.3.1
prettier-vscode|esb|10.1.0
code-runner|for|0.12.1
kotlin|fwc|0.2.32
copilot|Git|1.147.0
copilot-chat|Git|0.11.1
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.78.1
go|gol|0.40.1
vscode-env|Iro|0.1.0
better-cpp-syntax|jef|1.17.2
vscode-peacock|joh|4.2.2
cmake-language-support-vscode|jos|0.0.9
solidity|Jua|0.0.165
vscode-colorize|kam|0.11.1
vsc-python-indent|Kev|1.18.0
rainbow-csv|mec|3.11.0
graphql|mqu|0.1.2
vscode-docker|ms-|1.28.0
vscode-dotnet-runtime|ms-|2.0.0
vscode-kubernetes-tools|ms-|1.3.15
black-formatter|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
azure-repos|ms-|0.38.0
brackets-keybindings|ms-|0.1.1
brackets-pack|ms-|0.1.1
cmake-tools|ms-|1.16.32
cpptools|ms-|1.19.1
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.8.22
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
vscode-typescript-next|ms-|5.4.20240109
vsliveshare|ms-|1.0.5900
vsliveshare-audio|ms-|0.1.93
hardhat-solidity|Nom|0.7.3
vscode-css-peek|pra|4.4.1
prisma|Pri|5.8.0
java|red|1.25.1
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1799
markdown-preview-enhanced|shd|0.8.11
sass-indented|syl|1.8.28
icons|tal|3.8.0
ayu|tea|1.0.5
tailwind-raw-reorder|Tra|3.1.0
cmake|twx|0.0.17
vscode-gradle|vsc|3.13.5
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.43.0
vscode-icons|vsc|12.6.0
vim|vsc|1.27.2
codetour|vsl|0.0.59
nextjs|Wil|0.0.8
vscode-nextjs-snippets|wil|0.3.0
typescript-snippets|zha|0.0.8
html-css-class-completion|Zig|1.20.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30933248
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019a:30933241

```

</details>

**Comment by potapov-ev** [comment]
Hi. 
It looks like I have the same problem.
When vscode starts, ts crashes. The error message suggests disabling the IntelliCode plugin. https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode
After restarting, when trying to send an error message, the editor suggests updating the typescrypt version
<img width="313" alt="image" src="https://github.com/microsoft/vscode/assets/48162503/14733521-eff6-4fa1-8eba-f9e1c5ef5aa8">

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Varun-Dhruv** [comment]
Nope the bug got fixed with a PC restart was not able to reproduce it
