### ISSUE TITLE
Cannot register two commands with the same id: workbench.action.terminal.scrollToTop

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#202107]
PS C:\dev\microsoft\vscode> ./scripts/test-documentation.bat   
Runs tests against the current documentation in https://github.com/microsoft/vscode-docs/tree/vnext

Found --crash-reporter-directory argument. Setting crashDumps directory to be 'C:\dev\microsoft\vscode\.build\crashes'
[24744:0109/225758.346:INFO:CONSOLE(207)] "Cannot register two commands with the same id: workbench.action.terminal.scrollToBottom", source: C:\dev\microsoft\vscode\test\unit\electron\renderer.js (207)
[24744:0109/225758.347:INFO:CONSOLE(207)] "Cannot register two commands with the same id: workbench.action.terminal.scrollToTop", source: C:\dev\microsoft\vscode\test\unit\electron\renderer.js (207)

  Tests are using suiteSetup and setup correctly
    + assertCleanState - check that registries are clean at the start of test running
    1) "after each" hook for "assertCleanState - check that registries are clean at the start of test running"

  1 passing (5ms)
  1 failing

  1) "after each" hook for "assertCleanState - check that registries are clean at the start of test running":

      + expected - actual

      -false
      +true

  AssertionError [ERR_ASSERTION]: Error: Unexpected console output in test run. Please ensure no console.[log|error|info|warn] usage in tests or runtime errors.
      at Context.<anonymous> (C:\dev\microsoft\vscode\test\unit\electron\renderer.js:282:12)

---

This blocks updating colors

**Comment by felixhaeberle** [comment]
I also have this issue.

My env:
Version: 1.86.0-insider (Universal)
Commit: 2c8f29174a63b3ace3d00ad0028cdc7ed9853b8b
Datum: 2024-01-16T05:36:24.731Z (Vor 1 Tag)
Electron: 27.2.1
ElectronBuildId: 26149897
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
Betriebssystem: Darwin arm64 22.6.0

**Comment by Tyriar** [comment]
Cannot reproduce
