### ISSUE TITLE
[folding] Fold All at same level as cursor

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#20217]
When in a large file deeply nested, it is often unclear which fold level will match what you actually wish to fold.
Often, I want to collapse everything at the same level as my cursor.
In effect, this would select the fold level automatically based on current cursor position.

**Comment by aeschli** [comment]
Something like 'Fold Children'?

**Comment by dakaraphi** [comment]
@aeschli 
It is not a request to fold children, more like fold all siblings but not exactly.  In effect, it is precisely picking the level you are at based on the cursor location, then executing fold (level # determined by cursor location)

**Comment by dakaraphi** [comment]
@aeschli FYI, I have now implemented this as an extension.
https://marketplace.visualstudio.com/items?itemName=dakara.dakara-foldplus

**Comment by aeschli** [comment]
@dakaraphi Very cool!

**Comment by aeschli** [comment]
Closing as there hasn't been more requests for this feature and as you have it as an extension this should be good enough.
