### ISSUE TITLE
Accepting suggestion/completion with `tab` is removing completion suffix

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#202153]
# Description

Accepting suggestion/completion with `tab` is removing completion suffix. 

# Example

Given 

`|` is cursor 

```ts
const obj = {
	foo: 1, 
	bar: 2,
	jar: 3,
};

for (const { foo, |bar } of obj) {
	console.log(foo, bar);
}
```

Typing in `j` and accepting completion `jar` results in `jarbar` in 1.85.1, now it results in `jar` (`bar` is removed).

# Behavior in 1.85.1

https://github.com/microsoft/vscode/assets/16353531/2d6be151-fcaa-4381-be75-d28078424d92

# New behavior

https://github.com/microsoft/vscode/assets/16353531/212a1696-9785-428b-bdae-54e2fdab9309

# Info

Version: 1.86.0-insider
Commit: fb769554405bee9be16e21ceb0a496bd29126941
Date: 2024-01-09T10:06:54.001Z
Electron: 27.2.1
ElectronBuildId: 26149897
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0

TS 5.3.2

**Comment by jrieken** [comment]
Unsure if this is a bug and changed (the 2nd video has a different code sample) but debugging shows that insert and replace ranges are about replacing the current word. 

<img width="1352" alt="Screenshot 2024-01-10 at 15 43 24" src="https://github.com/microsoft/vscode/assets/1794099/d0f429e1-995e-4d7c-b192-4f9d5bc2c629">

**Comment by ulugbekna** [comment]
Reproed with the same code: 

https://github.com/microsoft/vscode/assets/16353531/0e9dbe8e-07ac-4446-a9fc-f8daf7b585dc

```
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation and GitHub. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

const example = {
	foo: 1,
	bar: 2,
	jar: 3,
};

for (const { foo, |bar } of [example]) {
	console.log(foo, bar);
}

```

**Comment by RedCMD** [comment]
isn't this just a editor setting?
completion.replace vs insert or something

**Comment by ulugbekna** [comment]
> isn't this just a editor setting?
completion.replace vs insert or something

I copied my current settings in insiders to stable and still behavior was different between them.

**Comment by connor4312** [comment]
This happens on an empty profile, and does not require actually accepting the suggestion (see my linked issue)
