### ISSUE TITLE
Terminal wordwrap with Alt+Z stretch font horizontally

### ISSUE THREAD

**Issue by QuentinDstl** [microsoft/vscode#202167]
Type: <b>Bug</b>

When I do Alt+Z in terminal to toggle wordwrap it will stretch my terminal font hoizontally when wordwarp is turn off

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (18.39GB free)|
|Process Argv|--crash-reporter-id 1acd0450-ddd8-4182-9f10-bebc59481c5e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (82)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
ng-template|Ang|17.0.3
browse-lite|ant|0.3.7
vite|ant|0.2.5
vscode-intelephense-client|bme|1.10.2
npm-intellisense|chr|1.4.5
doxdocgen|csc|1.4.0
dbclient-jdbc|cwe|1.3.4
vscode-database-client2|cwe|6.9.9
dart-code|Dar|3.80.0
flutter|Dar|3.80.0
vscode-markdownlint|Dav|0.53.0
vscode-eslint|dba|2.4.2
vscode-deno|den|3.31.0
gitlens|eam|14.6.1
vscode-html-css|ecm|2.0.6
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
json-tools|eri|1.0.2
prettier-vscode|esb|10.1.0
figma-vscode-extension|fig|0.3.1
copilot|Git|1.147.0
copilot-labs|Git|0.17.1121
vscode-github-actions|git|0.26.2
vscode-graphql|Gra|0.8.21
vscode-graphql-syntax|Gra|1.2.2
language-cython|guy|0.0.8
terraform|has|2.29.1
db2connect|IBM|2.3.1
plantuml|jeb|2.17.5
better-cpp-syntax|jef|1.17.2
vscode-peacock|joh|4.2.2
cmake-language-support-vscode|jos|0.0.9
solidity|Jua|0.0.165
calculator|lix|0.1.1
start-git-bash|McC|1.2.1
rainbow-csv|mec|3.11.0
vscode-language-babel|mgm|0.0.40
git-graph|mhu|1.30.0
vscode-mojo|mod|0.6.1
vscode-docker|ms-|1.28.0
vscode-language-pack-fr|MS-|1.85.2024011009
vscode-dotnet-runtime|ms-|2.0.0
vscode-edge-devtools|ms-|2.1.3
vscode-kubernetes-tools|ms-|1.3.15
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.8.22
remote-explorer|ms-|0.4.1
sublime-keybindings|ms-|4.0.10
vscode-typescript-next|ms-|5.4.20240109
vsliveshare|ms-|1.0.5900
react-proptypes-intellisense|OfH|1.0.3
vscode-versionlens|pfl|1.9.2
material-icon-theme|PKi|4.33.0
vscode-css-peek|pra|4.4.1
prisma|Pri|5.8.0
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
svelte-vscode|sve|108.1.0
pdf|tom|1.2.2
cmake|twx|0.0.17
volar|Vue|1.8.27
console-ninja|Wal|1.0.271
vscode-import-cost|wix|3.3.0
xata|xat|0.5.0
php-debug|xde|1.34.0
markdown-all-in-one|yzh|3.6.1
vscode-python-poetry|zes|0.17.9

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30933248
pythongtdpath:30769146
i26e3531:30792625
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30928863
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by meganrogge** [comment]
works for me, maybe try changing `terminal.integrated.gpuAcceleration`

https://github.com/microsoft/vscode/assets/29464607/27cc7437-de4b-4351-b6a0-d690ae0a08b8
