### ISSUE TITLE
VSCODE insiders cannot render more than 55k lines in big files

### ISSUE THREAD

**Issue by uselessscat** [microsoft/vscode#202168]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
  Version: 1.86.0-insider (Universal)
  Commit: c973ec767338f7846710cc2ee46e38b4504a044c
  Date: 2024-01-10T05:37:20.920Z (9 hrs ago)
  Electron: 27.2.1
  ElectronBuildId: 26149897
  Chromium: 118.0.5993.159
  Node.js: 18.17.1
  V8: 11.8.172.18-electron.0
- OS Version: Darwin x64 23.2.0

Steps to Reproduce:

1. Create a large file with almost 1_000_000 lines
2. Open it using vscode
3. Vscode only renders 55555 lines

Example:
<img width="1155" alt="image" src="https://github.com/microsoft/vscode/assets/15332878/b5125981-7c63-4663-85da-45bad7e85bc3">

Is there a way to show the whole file?

**Comment by gjsjohnmurray** [comment]
Is #202138 related?

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode/issues/202138

**Comment by uselessscat** [comment]
Thanks a lot ✨
