### ISSUE TITLE
Jupyter markdown cells fail with a `cases` environment nested in an `equation`

### ISSUE THREAD

**Issue by jlelong** [microsoft/vscode#202149]
Write the following latex code inside a markdown cell in a Jupyter notebook

```latex
Consider
\begin{equation}
f(x) = \begin{cases}
1 & \text{if ...} \\
1 & \text{otherwise}
\end{cases}
\end{equation}
```

Rendering the cell fails with `ParseError: Katex parse error: Expected & or \ or \cr or \end at end of input: ...se} \end{cases}`

Adding a blank line before `\begin{equation}` or indenting `end{cases}` seems to fix the issue.

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 23.2.0

**Comment by CodeWithMe04** [comment]
Its helps in Jupyter markdown cells
