### ISSUE TITLE
`bazel-*` symlink directories are not added to `files.watcherExclude` by default

### ISSUE THREAD

**Issue by AdwaitChavan** [microsoft/vscode#202264]
For Bazel based projects, `bazel-*` symlink directories are output directories, and their size is proportional to the size of the project. Adding these by default to `files.watcherExclude` would help improve development experience in Bazel based projects.

For more details:
https://bazel.build/remote/output-directories#layout-diagram
https://bazel.build/docs/user-manual#configuration-specific-data

**Comment by AdwaitChavan** [comment]
Tried to investigate more and found some logs in the "Server" output channel after setting log level to `trace`:

<img width="1422" alt="bazel-out" src="https://github.com/microsoft/vscode/assets/57969397/a92fc3aa-8b45-48a1-9f3a-0fee7a2991a1">

Looks like it tries to add watchers to the linked path for symlinks?

**Comment by bpasero** [comment]
@AdwaitChavan its still possible that these symlinks are watched, but not as a result of our default workspace watcher which will start at the root of the opened folder and then recursively descend down.

Is it possible that `files.watcherInclude` is configured in settings which was added specifically to explicitly allow to include certain folders in the workspace that are symlinks?

The other alternative is that an extension explicitly uses the `createFileSystemWatcher` API to watch these folders, can you check?

**Comment by bpasero** [comment]
In fact, the log message really suggests that `.../bazel-out` is explicitly watched and its unlikely that this folder is opened as workspace, or is it?

**Comment by guw** [comment]
@bpasero Can this be the Git extension? Although we have these folders in `.gitignore`.

**Comment by bpasero** [comment]
I do not think this is the git extension, but I am not 100% sure. Unfortunately the log does not tell which extension initiated the watching. 

To proof the point can you try with a folder that does not have `.git` and by selectively disabling extensions?

**Comment by AdwaitChavan** [comment]
Thanks you for the details. Actually, I did some further troubleshooting and found that `.../bazel-out` folder was opened during testing which is why file watchers for that folder were observed. Retesting in a clean environment indicated that file watchers for `bazel-*` directories are indeed not added by default even if the parent folder is opened. Also, this is with the Git extension enabled.

**Comment by AdwaitChavan** [comment]
Yes, that seems to be the case. Closing this issue based on the discussion above.
