### ISSUE TITLE
Pasting after copying an entire line inserts it at cursor instead of new line

### ISSUE THREAD

**Issue by julianlam** [microsoft/vscode#202203]
Type: <b>Bug</b>

1. Write a line of text (e.g. `kajnjsdncsdlkfsdkf`)
2. Place cursor in the middle of text, ensuring no characters are selected
3. `Ctrl-C` to copy the line
4. `Ctrl-V` to paste the line

The previous and expected behaviour inserts the copied line above the current line.

The new behaviour inserts the clipboard contents in the middle of the current line.

VS Code version: Code - Insiders 1.86.0-insider (d2028ff9c7678834f810cad53f10a35718f3fcba, 2024-01-05T05:35:23.597Z)
OS version: Linux x64 6.6.9-200.fc39.x86_64
Modes:

**Comment by mjbvz** [comment]
Doesn't happen for me in  2024-01-10T05:37:20.920Z

What about in the latest insiders build? Also does it still happen if you disable extensions?

**Comment by julianlam** [comment]
Thanks @mjbvz, latest insiders resolved. Must've been a one-off regression.
