### ISSUE TITLE
improve visual contrast/ animation of speech microphone

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#202253]
<img width="946" alt="Screenshot 2024-01-11 at 7 25 59 AM" src="https://github.com/microsoft/vscode/assets/29464607/0e194bbb-ae62-4e72-a3f5-46f6e83bd489">
<img width="950" alt="Screenshot 2024-01-11 at 7 25 49 AM" src="https://github.com/microsoft/vscode/assets/29464607/ef6b191f-4edb-4091-afa3-60adc7262f3b">

**Comment by hbons** [comment]
cc @bpasero

**Comment by bpasero** [comment]
Just fyi, I attempted to model how other related UIs looks like, mainly Bing Copilot Chat:

![Recording 2024-02-07 at 16 10 23](https://github.com/microsoft/vscode/assets/900690/aa2513d2-e9cb-47a4-9c0b-f616b57496be)

I think one challenge is that our buttons are generally smaller so the effect is smaller.

The implementation is here:

https://github.com/microsoft/vscode/blob/5460e21847948d5432a24d5a8ba5d6ceaca804bf/src/vs/workbench/contrib/chat/electron-sandbox/actions/voiceChatActions.ts#L680-L724

**Comment by hbons** [comment]
We have a bit of leeway on the icon canvas to make this look visually bigger. I can have a look at that.

**Comment by bpasero** [comment]
Cool thanks!

**Comment by hbons** [comment]
Larger `mic-*` icons in https://github.com/microsoft/vscode-codicons/pull/225
