### ISSUE TITLE
Issue with style50

### ISSUE THREAD

**Issue by AnanyaKAjay** [microsoft/vscode#202259]
I have been trying to use style50 for a while , but I am repeatedly getting the following error : Failed to connect extension server on port 1337. Could someone please help with this? Thank you.

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0
Embedder: codespaces

**Comment by chrmarti** [comment]
`style50` is not part of VS Code, please check with them for help.
