### ISSUE TITLE
Linux: Make the title & menu bar color match the current vscode theme

### ISSUE THREAD

**Issue by Crestanzio** [microsoft/vscode#202275]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Linux x64 6.5.9-2-cachyos-bmq
- DE: Gnome 45

The title & menu bar is not matching the color theme, i want to make it blue like my theme is but i can't find any way.
https://i.imgur.com/9k7Iv2z.png

**Comment by bpasero** [comment]
It will be fine if you configure `window.titleBarStyle` setting to `custom`

**Comment by Crestanzio** [comment]
But that give me a "Windows" style title bar and i don't like it. I want to keep the Linux style title bar.

**Comment by deepak1556** [comment]
This is a limitation of native title bar support from the runtime, if we get window controls overlay support for linux then we can improve the situation for custom titlebar controls which is tracked in https://github.com/microsoft/vscode/issues/176467.
