### ISSUE TITLE
call ConfigurationDoneRequest only if debug adapter supports this

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2022]
Only call `ConfigurationDoneRequest` if  `InitializeRequest` returns a value of true for the `supportsConfigurationDoneRequest`.

**Comment by isidorn** [comment]
I now repsect capabilites returned from the initilaze response.
For the latest node adapter I do not get any capabilites returned, is this change pushed?

**Comment by weinand** [comment]
@isidorn yes, capabilities are returned for quite some time. The debug adapter tests would fail if the node adapter would not return the 'supportsConfigurationDoneRequest'.

**Comment by isidorn** [comment]
@weinand in the debugProtocl it is specified that these are topLevel, while in the node-debug code you return them as part of the `body`

**Comment by weinand** [comment]
@isidorn oops, oversight.

**Comment by weinand** [comment]
@isidorn for backward compatibility you have to deal with the issue that old debugAdapters (e.g. mono-debug) don't return a 'body' in their InitializeResponse:

![2016-01-22 18-58-03](https://cloud.githubusercontent.com/assets/1898161/12518667/2267020a-c13a-11e5-904b-c878f2cd92e4.png)
