### ISSUE TITLE
Linux: join title bar & menu bar in one line like windows does

### ISSUE THREAD

**Issue by Crestanzio** [microsoft/vscode#202273]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Linux x64 6.5.9-2-cachyos-bmq
- DE: Gnome 45

The menu bar  is separate from title bar as a result bad user experience is there any way i can join title & menu bar?

Linux:
https://i.imgur.com/yaTY0Mu.png

Windows:
https://i.imgur.com/BopugSm.png

**Comment by sbatten** [comment]
You can get the "Windows" experience on linux with this setting: `window.titleBarStyle`

Note that we currently don't have a good way to support linux native window management controls so this is one reason why this is not the default. If you are fine with the windows styling on linux, this setting will suffice.

**Comment by Crestanzio** [comment]
Yes, i know about "Windows" style but i'm not happy with that. There is no one workaround at least that can help to get Linux style title bar in the same color with my theme?
