### ISSUE TITLE
OS specific tasks / task filtering

### ISSUE THREAD

**Issue by MarcelRobitaille** [microsoft/vscode#202278]
My organization has a lot of tasks.json that do all kinds of different things. We have tasks that only make sense on Windows and others that only make sense on Linux. They are inherently completely different.

I would like to have a list of tasks for Windows and a different list for Linux inside of tasks.json.

Reading [the schema](https://code.visualstudio.com/docs/editor/tasks-appendix), it looks like I should be able to do something like this:

```json
{
    "linux": {
        "tasks": [
            
        ]
    },
    "windows": {
        "tasks": [
            
        ]
    },
}
```

But when I do this, I get: `Task version 2.0.0 doesn't support global OS specific tasks. Convert them to a task with a OS specific command. Affected tasks are:`

Why not?

`TaskConfiguration` has a field `windows` of type `BaseTaskConfiguration` which includes `tasks?: TaskDescription[]`. I am following the schema. It's not really even a feature request. I'm just asking that you support something that is valid according to your schema.

As far as I know, there is no other way to have an os specific task. It would also be cool to solve this in a more general way and add some kind of filter property to each task to granularly control when it shows up.

**Comment by meganrogge** [comment]
This has not gotten any upvotes, so closing as I don't think we'll do this anytime soon.
