### ISSUE TITLE
Run ts server using ubuntu bash (WSL)

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#20220]
It would be nice if ts server in VSCode could run using Ubuntu Bash (Windows Subsystem for Linux). It is needed if in general dev workflow assumes working with bash shell and WSL file system. For example, WSL symlinks are not compatible with windows NTFS symlinks - this makes running VSCode (tsserver) and other node_modules related operations in bash shell incompatible when linked modules are involved.

This issue is one of the cases of https://github.com/Microsoft/vscode/issues/10129

**Comment by Tyriar** [comment]
@mjbvz might know more about what tsserver is.

**Comment by mjbvz** [comment]
It is unclear to me what the issue with TSServer is here or how it relates to the command line. Can you please explain your usecase and the problems you are seeing in more detail. If TSSerever is not handling some file paths / symlinks properly, please [open an issue against TypeScript](https://github.com/Microsoft/TypeScript/issues/new)

**Comment by whitecolor** [comment]
Correct me if I'm wrong: in VSCode Typescript Server  (tsserver) is running as background process, and it gets requests and sends responses that is how TS autocompletion, error reporting etc works. 

But this background process is run natively in windows shell (uses nodejs that is installed in windows) and using windows file system. And I say that there is a need that this background process would be run as WSL process using nodejs that installed in linux and using its file system.

(The same case for running GIT, either windows version is used or linux installed)

**Comment by mjbvz** [comment]
@whitecolor Thanks for the additional detail. Yes, we just fork the current node process to spawn the tsserver. The request here would be to allow using a different instance of node than the one running vscode, probably by passing a `execPath` argument to `fork`

**Comment by whitecolor** [comment]
I think yes, but this should probably work, but need to check how it will run with WSL bash.

**Comment by whitecolor** [comment]
But the problem here is that tsc compiler seem to not support WSL https://github.com/Microsoft/TypeScript/issues/15328

**Comment by entrptaher** [comment]
Got same issue on ubuntu :(

**Comment by rfgamaral** [comment]
Also having the same issue...

I'm trying to move completely to WSL but this doesn't allow me to specify a different TypeScript tsserver - installed on WSL - to be used by Code. I'm forced to have Node.js/NPM installed on Windows and use that to install TypeScript globally and only then I can set that version in Code's `typescript.tsdk` setting.

@Tyriar @mjbvz Is this planned to be looked at?

**Comment by RMacfarlane** [comment]
`We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development`
