### ISSUE TITLE
No semantic token assigned to import names, but available for export

### ISSUE THREAD

**Issue by OzelotVanilla** [microsoft/vscode#202224]
Type: <b>Bug</b>

This is an issue originally from: https://github.com/typescript-language-server/typescript-language-server/issues/842
The issue is confirmed not to be an issue from TypeScript Language Server by its' developer/maintainer.

When export a name, there is semantic token assigned. Such as the Compiler is assigned with class.

![](https://private-user-images.githubusercontent.com/59910575/293825916-4a3c69c2-02e9-4dfb-8664-94fb69e8535b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTkyNDYsIm5iZiI6MTcwNDk1ODk0NiwicGF0aCI6Ii81OTkxMDU3NS8yOTM4MjU5MTYtNGEzYzY5YzItMDJlOS00ZGZiLTg2NjQtOTRmYjY5ZTg1MzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA3NDIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZDdjN2U5ZTI2ZGNkYzkxODI2M2RjNDZmMWQzMTRlNGRiZjNhOGQ4YmVkOGZhZGJmMmZlMzYyM2U1MTQyNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qvn3N_Ma4bsHi5FKoM4Io6G3NV_Gt9eQocqe6C3TWEM)

For import, there seems to be no semantic token available.

![](https://private-user-images.githubusercontent.com/59910575/293825941-f3c8211d-52cf-4b0e-9849-a1ff0d532873.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTkyNDYsIm5iZiI6MTcwNDk1ODk0NiwicGF0aCI6Ii81OTkxMDU3NS8yOTM4MjU5NDEtZjNjODIxMWQtNTJjZi00YjBlLTk4NDktYTFmZjBkNTMyODczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA3NDIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MjI1ZGIzNjliZDZjZTFiZjUxYjlhMzRjNzNjYjFkNjM3MzRjN2UwODQ5NjI0NWViOWEzYzhlNDMyZDhkNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vsAzilF0jwLHy0v2QF10QgB3gDEc-KJecT7_yXbOj3k)

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (20.58GB free)|
|Process Argv|--crash-reporter-id a37d0f1f-77dd-4a89-91bb-2352dc8a97c1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.2
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
gitlens|eam|14.6.1
html-preview-vscode|geo|0.2.5
git-graph|mhu|1.30.0
vscode-language-pack-ja|MS-|1.85.2024011009
csdevkit|ms-|1.2.7
csharp|ms-|2.14.8
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26
autopep8|ms-|2023.8.0
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
remote-wsl|ms-|0.81.8
cmake-tools|ms-|1.16.32
cpptools-extension-pack|ms-|1.3.0
vscode-typescript-next|ms-|5.4.20240110
vsliveshare|ms-|1.0.5900
veriloghdl|msh|1.13.0
vscode-react-native|msj|1.12.2
rust-analyzer|rus|0.3.1799
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.6.0
volar|Vue|1.8.27
vscode-typescript-vue-plugin|Vue|1.8.27
markdown-all-in-one|yzh|3.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30928863
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019acf:30933242

```

</details>

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
