### ISSUE TITLE
Android version of winulate windows emulation web based

### ISSUE THREAD

**Issue by taibud007** [Microsoft/vscode#20228]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by taibud007** [comment]
Web page to nettable windows terminal

**Comment by Tyriar** [comment]
I'm sorry but I'm not sure what you mean. Using your native language might be easier to understand after running it through a translator.

**Comment by taibud007** [comment]
I dunno goto project m. milkdrop ported to android and open arena quake 3d ported to android. How can I port DirectX and opengl like a desktop guy. There are alto of software that android won't run. 
Steps locate then app that ported them and lets start porting everything from Mac and windows and UNIX to run on a android

**Comment by Tyriar** [comment]
VS Code has very integration with Android and game development, you should go investigate porting applications to Android if that's what you need to do.
