### ISSUE TITLE
consider providing action to go to extension settings from extension page

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#202252]
One of the fable findings was that beginner users expected to be able to configure extension settings from the extension page/ view. Could we consider this?

<img width="1144" alt="Screenshot 2024-01-11 at 7 22 33 AM" src="https://github.com/microsoft/vscode/assets/29464607/8231492b-7c4d-4b6b-ac05-c36a5086dcfc">

**Comment by sandy081** [comment]
<img width="610" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/2cddc1c6-b5cc-4167-9817-500f29c19126">
