### ISSUE TITLE
Fish shell history completion gets munged

### ISSUE THREAD

**Issue by dreki** [Microsoft/vscode#20225]
- VSCode Version:
- OS Version: Mac OSX 10.11.6

Steps to Reproduce:

1. Make `fish` your default shell before opening VS Code
2. Ensure you have a sizable fish command history
3. Open the Integrated Terminal
4. Trigger fish's history search (e.g. by `^r`)
5. Start typing to narrow the results (minimum of 4 chars)
6. Notice how the input area for fish is munged.

example image: 
![image](https://cloud.githubusercontent.com/assets/563345/22752037/9a28fa74-edfc-11e6-9067-91b7dfc11516.png)

**Comment by rmunn** [comment]
What happens if you turn off the `terminal.integrated.flowControl` setting (which defaults to `true`)? That fixed a similar (but not identical) problem in the F# Interactive window (from the Ionide-fsharp plugin) for me.

**Comment by Tyriar** [comment]
Thanks @rmunn, yes that's likely the case and that should work around the issue. This should be fixed in 1.9.1 :smiley:
