### ISSUE TITLE
Terminal should propagate not handled shortcut key combo

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#20223]
vscode: 1.9.0

When terminal is in focus, other shortcut keys such as `[Alt+p]` which invokes `project-manager` is not working.

It should propagate those so the extension can be triggered.

**Comment by Tyriar** [comment]
This is because the terminal uses that key sequence. You will need to override `terminal.integrated.commandsToSkipShell` and add the project manager keybinding to that list to work around.

**Comment by unional** [comment]
> add the project manager keybinding to that list to work around.

Thanks. It works. For the record, it means adding "projectManager.listProjects" in this case.

To get the key binding, go to Extensions > look up "Project Manager" > Contributions and get the  Command Name with that Keyboard Shortcuts.
