### ISSUE TITLE
issue with terminal on windows

### ISSUE THREAD

**Issue by piyushh36** [microsoft/vscode#202398]
Type: <b>Bug</b>

i have opened vs code terminal. whenever i am click right click it treating as ctrl + V   asking me if i want to paste the code there

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700HX (24 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (7.03GB free)|
|Process Argv|. --crash-reporter-id 847f2f22-bc04-4af4-80bb-17bc379768d4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.20
vscode-docker-syntax|dun|0.1.5
gitlens|eam|14.6.1
go|gol|0.40.1
rest-client|hum|0.25.1
vscode-chat-gpt|ika|1.2.0
kubernetes-snippets|ipe|0.1.9
kubernetes-yaml-formatter|ken|1.1.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.28.0
vscode-kubernetes-tools|ms-|1.3.15
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.327.0
remote-wsl|ms-|0.81.8
hardhat-solidity|Nom|0.7.3
vscode-yaml|red|1.14.0
solidity-debugger-pro|rob|2023.5.8
pdf|tom|1.2.2
gitblame|wad|10.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30933248
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019acf:30933242

```

</details>

**Comment by gjsjohnmurray** [comment]
What is your `terminal.integrated.rightClickBehavior` setting value?
