### ISSUE TITLE
Allow MarkedStrings in Diagnostics

### ISSUE THREAD

**Issue by daschult** [Microsoft/vscode#20232]
It would be nice to be able to include markdown (such as url links) inside of Diagnostics. That way you could provide a url where a user could go to see more information about a particular error or warning. This functionality currently exists in Hover, so I would think it wouldn't be a big deal to do it for Diagnostics too.

**Comment by sandy081** [comment]
Duplicates #11847

**Comment by gerrywastaken** [comment]
@sandy081 I believe the issue you linked as a dupe is specific to vscode-eslint, so it's possible that this could end up getting fixed without @daschult's request being addressed. Is it possible to rename the other issue so that a fix for it would allow all linters to add clickable links?

**Comment by sandy081** [comment]
@gerrywastaken Agreed the issue @11847 is eslint specific. But solution would be generic for all extensions contributing problems. Will change the issue summary to be generic

**Comment by gerrywastaken** [comment]
@sandy081 Thanks for that :)
