### ISSUE TITLE
"Open with" makes profile set to "default"

### ISSUE THREAD

**Issue by OTsector** [microsoft/vscode#202301]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Windows 11 pro x64

Steps to Reproduce:

When I click script file to open with VScode. The "Profiles" is applied to "Default".
But if I set my "Profile" and exit from VScode and relaunch VScode shortcut on desktop it will save it and open as my regular Profile.

**Comment by OTsector** [comment]
I have found solution myself for me.

fix for .sh
```Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\VSCode.sh\shell\open\command]
@="\"C:\\Users\\root\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe\" --profile 0x07 \"%1\""

```

This one is worked for me, now I need to write script in PowerShell to get all file extension in this regitry path and set profile like this example.

But this solution will work just for me and who will see and who is capable to do same thing him/herself.

**Comment by OTsector** [comment]
I've wrote script in PowerShell for fix this issue:

PS C:\Users\root> ```$pathArray = @(); $valueArray = @(); (Get-Item -LiteralPath 'Registry::HKEY_CLASSES_ROOT').GetSubKeyNames() | ForEach-Object { "Registry::HKEY_CLASSES_ROOT\"+$_+"\shell\open\command" } | Select-String -Pattern 'VScode' -Raw | ForEach-Object { if (((Get-ItemProperty -LiteralPath "$_" -ErrorAction SilentlyContinue).'(default)' -ne $null)) { $valueArray += (Get-ItemProperty -LiteralPath $_).'(default)'; $pathArray += $_ } }; foreach ($i in 0..($valueArray.Length -1 )) { if ($valueArray[$i].Substring($valueArray[$i].LastIndexOf('\') + 1) -eq 'Code.exe" "%1"') { $value=($valueArray[$i]).ToString().Substring(0, ($valueArray[$i]).ToString().LastIndexOf('\')+1) + 'Code.exe"'+ ' --profile 0x07 ' +'"%1"'; $path=$pathArray[$i]; $valueName='(Default)'; Set-ItemProperty -Path "$path" -Name '(Default)' -Value "$value"; if($?) { Write-Output "=====START`nregistry value is changed`npath: $path;`nvalueName: $valueName;`nvalue: $value`npathArray: $($pathArray[$i])`n=======END`n" } } }```
=====START
registry value is changed
path: Registry::HKEY_CLASSES_ROOT\VSCode.vue\shell\open\command;
valueName: (Default);
value: "C:\Users\root\AppData\Local\Programs\Microsoft VS Code\Code.exe" --profile 0x07 "%1"
pathArray: Registry::HKEY_CLASSES_ROOT\VSCode.vue\shell\open\command
=======END
...

**Comment by OTsector** [comment]
I've wrote script in PowerShell for fix this issue:

PS C:\Users\root> ```$profile="0x07"; $pathArray = @(); $valueArray = @(); (Get-Item -LiteralPath 'Registry::HKEY_CLASSES_ROOT').GetSubKeyNames() | ForEach-Object { "Registry::HKEY_CLASSES_ROOT\"+$_+"\shell\open\command" } | Select-String -Pattern 'VScode' -Raw | ForEach-Object { if (((Get-ItemProperty -LiteralPath "$_" -ErrorAction SilentlyContinue).'(default)' -ne $null)) { $valueArray += (Get-ItemProperty -LiteralPath $_).'(default)'; $pathArray += $_ } }; foreach ($i in 0..($valueArray.Length -1 )) { if ($valueArray[$i].Substring($valueArray[$i].LastIndexOf('\') + 1) -eq 'Code.exe" "%1"') { $value = ($valueArray[$i]).ToString().Substring(0, ($valueArray[$i]).ToString().LastIndexOf('\')+1) + 'Code.exe --profile ' + $profile + ' "%1"'; $path=$pathArray[$i]; $valueName='(Default)'; Set-ItemProperty -Path "$path" -Name '(Default)' -Value "$value"; if($?) { Write-Output "=====START`nregistry value is changed`npath: $path;`nvalueName: $valueName;`nvalue: $value`npathArray: $($pathArray[$i])`n=======END`n" } } }```
=====START
registry value is changed
path: Registry::HKEY_CLASSES_ROOT\VSCode.vue\shell\open\command;
valueName: (Default);
value: "C:\Users\root\AppData\Local\Programs\Microsoft VS Code\Code.exe" --profile 0x07 "%1"
pathArray: Registry::HKEY_CLASSES_ROOT\VSCode.vue\shell\open\command
=======END
...

**Comment by OTsector** [comment]
.ps1 script file code (An administrator account is required):
```
$jsonFile = "$home\AppData\Roaming\Code\User\globalStorage\storage.json"
if (-Not (Test-Path -Path $jsonFile -PathType Leaf)) {
	$profile = Read-Host "error: profile name is not fount (may VScode is not installed at default location).`nenter your profile name"
} else {
	$profile = (Get-Content -Raw -Path $jsonFile | ConvertFrom-Json).userDataProfiles.name
}
if (-Not $profile) {
	$profile = Read-Host "error: profile name is not fount (it seems you are not using profile).`nenter your profile name"
}
$pathArray = @()
$valueArray = @()
(Get-Item -LiteralPath 'Registry::HKEY_CLASSES_ROOT').GetSubKeyNames()
	| ForEach-Object { "Registry::HKEY_CLASSES_ROOT\"+$_+"\shell\open\command" }
	| Select-String -Pattern 'VScode' -Raw 
	| ForEach-Object {
			if(((Get-ItemProperty -LiteralPath "$_" -ErrorAction SilentlyContinue).'(default)' -ne $null)) {
				$valueArray += (Get-ItemProperty -LiteralPath $_).'(default)'
				$pathArray += $_
			}
		}
foreach ($i in 0..($valueArray.Length -1 )) {
	if ($valueArray[$i].Substring($valueArray[$i].LastIndexOf('\') + 1) -eq 'Code.exe" "%1"') {
		$value = ($valueArray[$i]).ToString().Substring(0, ($valueArray[$i]).ToString().LastIndexOf('\')+1) + 'Code.exe --profile ' + $profile + ' "%1"'
		$path=$pathArray[$i]; $valueName='(Default)'
		Set-ItemProperty -Path "$path" -Name '(Default)' -Value "$value"
		if($?) {
			Write-Output "=====START`nregistry value is changed`npath: $path;`nvalueName: $valueName;`nvalue: $value`npathArray: $($pathArray[$i])`n=======END`n"
		}
	}
}
$pathArray = @()
$valueArray = @()
(Get-Item -LiteralPath 'Registry::HKEY_USERS').GetSubKeyNames()
	| ForEach-Object { "Registry::HKEY_USERS\"+$_ }
	| ForEach-Object { $path=$_; ((Get-Item -LiteralPath ($_)).GetSubKeyNames())
	| ForEach-Object { $path+"\"+$_+"\shell\open\command" } }
	| Select-String -Pattern 'VScode' -Raw
	| ForEach-Object {
			if(((Get-ItemProperty -LiteralPath "$_" -ErrorAction SilentlyContinue).'(default)' -ne $null)) {
				$valueArray += (Get-ItemProperty -LiteralPath $_).'(default)'
				$pathArray += $_
			}
		}
foreach ($i in 0..($valueArray.Length -1 )) {
	if ($valueArray[$i].Substring($valueArray[$i].LastIndexOf('\') + 1) -eq 'Code.exe" "%1"') {
		$value = ($valueArray[$i]).ToString().Substring(0, ($valueArray[$i]).ToString().LastIndexOf('\')+1) + 'Code.exe --profile ' + $profile + ' "%1"'
		$path=$pathArray[$i]; $valueName='(Default)'
		Set-ItemProperty -Path "$path" -Name '(Default)' -Value "$value"
		if($?) {
			Write-Output "=====START`nregistry value is changed`npath: $path;`nvalueName: $valueName;`nvalue: $value`npathArray: $($pathArray[$i])`n=======END`n"
		}
	}
}
```

**Comment by sandy081** [comment]
Thanks for sharing your solution. I do not think there is an action to be taken here. Hence closing.
