### ISSUE TITLE
Javascript outline / symbol search (Ctrl-Shift-O) stops working

### ISSUE THREAD

**Issue by markus-brt** [Microsoft/vscode#20235]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.5|
|xml|DotJoshJohnson|1.7.0|
|docthis|joelday|0.3.10|
|PowerShell|ms-vscode|0.9.0|
|debugger-for-ios-web|msjsdiag|0.1.2|
|java|redhat|0.0.9|
|perforce|slevesque|1.0.0|
|ur|SAP|0.0.2|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

The Ctrl-Shift-O outline works immediately after starting the editor but after a few minutes it only shows the loading animation but no results.

**Comment by markus-brt** [comment]
Still an issue in 1.9.1
It seems ESLint also stops working at the same time when symbol search fails. Also our own extensions stops processing commands.... strange. Can we enable some kind of debug logging for VSCode?

**Comment by markus-brt** [comment]
I deactivated several extension. The issue still exists: After editing a few line and saving a few times, symbol search and ESLint extension stop working.

**Comment by markus-brt** [comment]
Does no longer occur in latest 2 releases.

**Comment by mjbvz** [comment]
Thanks. Sorry for the lack of follow up on this issue but glad everything now seems to be working
