### ISSUE TITLE
Intellisense derived from JSDoc does not function correctly when imported

### ISSUE THREAD

**Issue by just-nick** [Microsoft/vscode#20238]
- VSCode Version: 1.9.0
- OS Version: Windows 10

When using an ES2015 class as a type in JSDoc it does not appear to work correctly in files that import that class via a require statement.

While working within the same file that the class was defined in, everything works as expected. (shown below).

![An example of JSDoc typing working correctly in the same file](https://cloud.githubusercontent.com/assets/4516547/22762823/62edaf00-eeb5-11e6-8dd9-363acae1b28c.jpg)

While working within a different file the class appears to import correctly and show its constructor typing (shown below).

![An example of an imported class working correctly](https://cloud.githubusercontent.com/assets/4516547/22762822/62ed0028-eeb5-11e6-858c-c0f7a52054e8.jpg)

But when I try to use the class for typing (As done in the first image) it no longer considers my class as a valid type.

![An example of an imported class not being accepted as a type](https://cloud.githubusercontent.com/assets/4516547/22762824/62eeb706-eeb5-11e6-88ec-de5d2dedb1bd.png)

Here is the jsconfig I was using for this example

```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "allowSyntheticDefaultImports": true
    }
}
```

Apologies if this has been submitted before. I couldn't seem to find it in the issue search.

**Comment by mjbvz** [comment]
Thanks for the report. Opened this bug against TypeScript: https://github.com/Microsoft/TypeScript/issues/14056

One possible workaround is using `import`: 

```js
import {ExampleType} from './class'
```

Closing as upstream
