### ISSUE TITLE
MAUI debuggin: Unable to stop to all exceptions

### ISSUE THREAD

**Issue by jeanpierrep1972** [microsoft/vscode#202349]
Type: <b>Bug</b>

When I start a debugging session with .net MAUI. I'm unable to set exceptions to stop on All Exceptions. The option is simply invisible in the debug panel inside the Breakpoint panel

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin x64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 5, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id d0e57bca-3396-4a46-8c93-288669fce67e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
nugetpackagemanagergui|ali|2.0.6
shell|bbe|0.3.0
cmake-format|che|0.6.11
gitignore|cod|0.9.0
vscode-mac-color-picker|dae|1.1.0
githistory|don|0.6.20
gitlens|eam|14.6.1
remotehub|Git|0.62.0
cmake-integration-vscode|go2|0.7.1
vscode-nuget-package-manager|jmr|1.1.6
cmake-language-support-vscode|jos|0.0.9
cpptask|kay|0.0.1
compare-folders|mos|0.24.1
azure-pipelines|ms-|1.228.0
vscode-docker|ms-|1.28.0
csdevkit|ms-|1.2.7
csharp|ms-|2.15.30
dotnet-interactive-vscode|ms-|1.0.5061050
dotnet-maui|ms-|0.8.3
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.0.0
vscode-dotnet-sdk|ms-|0.8.0
vscodeintellicode-csharp|ms-|0.1.26
sarif-viewer|MS-|3.4.2
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-deploy|ms-|1.2.4
remote-containers|ms-|0.327.0
azure-account|ms-|0.11.6
azurecli|ms-|0.5.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
powershell|ms-|2024.0.0
remote-repositories|ms-|0.40.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-concourse|vmw|1.51.0
vscode-icons|vsc|12.6.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019a:30933241

```

</details>

**Comment by roblourens** [comment]
Please file on the .NET debug extension repo, thanks

**Comment by jeanpierrep1972** [comment]
Where is this repo? Thanks

**Comment by jeanpierrep1972** [comment]
Frankly, I find Microsoft's decision to abandon VS Studio Mac worrying... Especially since VS Code with C# Extension doesn't seem to be up to the task of basic debugging. I've lost 2 days on a basic concept that should work... No documentation anywhere on this bug.

Please tell me where VS code debugging rests... I can't find it. Thank you
