### ISSUE TITLE
Support "toSide" with commands in the markdown file of a walkthrough/getting started

### ISSUE THREAD

**Issue by chankeith** [microsoft/vscode#202350]
#132087 added `toSide` ```(e.g [mycommand](command:toSide:mycommandtorun))``` that runs a command in new view beside the walkthrough from the description of a step.  Commands are also supported in the markdown files that a walkthrough step can point to via `media`, however, including `toSide` with a command in the markdown file doesn't work; I get an error in the developer console:

```ERR command 'toSide:mycommand' not found: Error: command 'toSide:mycommand' not found```

If a command using `toSide` works in a step's description, the same command with `toSide` should work in a markdown file too.

**Comment by bhavyaus** [comment]
@chankeith could you please include a use case for running a walkthrough command to the side in a new view? 
Would opening the walkthrough using `toSide` and then running your command not work in your case?

**Comment by chankeith** [comment]
> @chankeith could you please include a use case for running a walkthrough command to the side in a new view? Would opening the walkthrough using `toSide` and then running your command not work in your case?

Please expand on what you mean by opening the walkthrough using `toSide`?

The use case is when the walkthrough content in the markdown file contains a step to make a setting change, if `toSide` is working, the user could see the setting, change it, and then move on to the next step in the markdown file rather than just finding an error in the console.

**Comment by chankeith** [comment]
Thanks.

**Comment by eleanorjboyd** [comment]
@chankeith are you able to verify if this works now?

**Comment by chankeith** [comment]
> @chankeith are you able to verify if this works now?

Can I verify this when the Feb 2024 release is out or is there a faster way of verifying it?

**Comment by andreamah** [comment]
If you could install the insiders build and test it there, that'd be amazing! https://code.visualstudio.com/insiders/

**Comment by chankeith** [comment]
Verified!  Thank you.
