### ISSUE TITLE
Terminal Not working

### ISSUE THREAD

**Issue by TLP1872K** [microsoft/vscode#202315]
Type: <b>Bug</b>

Issue : Terminal is blank and crashes 

Steps to reporduce : 
1.Go to Terminal
2.Click New Terminal
3.Terminal opens 

Issue Observed : Terminal crashes when followed above steps and terminal is blank incase it opens

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (1.28GB free)|
|Process Argv|--crash-reporter-id b2e3f037-3e5f-40ef-85b0-d12c7db273a2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.2
lwc-salesforce|Nik|2.3.0
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|59.13.0
salesforcedx-vscode-apex|sal|59.13.0
salesforcedx-vscode-apex-debugger|sal|59.13.0
salesforcedx-vscode-apex-replay-debugger|sal|59.13.0
salesforcedx-vscode-core|sal|59.13.0
salesforcedx-vscode-lightning|sal|59.13.0
salesforcedx-vscode-lwc|sal|59.13.0
salesforcedx-vscode-soql|sal|59.13.0
salesforcedx-vscode-visualforce|sal|59.13.0
windows-terminal|Tyr|0.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
