### ISSUE TITLE
By default, don't auto-complete the first Intellisense suggestion after typing '.'

### ISSUE THREAD

**Issue by matthew-dean** [microsoft/vscode#202368]
[This](https://github.com/microsoft/vscode/issues/70176) was opened as a bug report and closed. 
This was opened as a second bug report as this was still and issue, and closed because it's a duplicate of #70176, even though #70176 is closed. So, as far as I can tell, this still isn't resolved.

Since some of the feedback seemed to be: "This is by design" despite being contrary to developer expectations. I just wanted to share this maddening experience trying to type an `.eslintrc.js` file:

https://github.com/microsoft/vscode/assets/414752/ee826b0a-bf58-446c-8843-43b4917a72d1

Trying to quickly type `module.exports` results in dumping in `useCssModule`, despite how counter-intuitive that is. This happens frequently. Another example is I'll type something as a typo, and then later find some weird, obscure import, like I'll accidentally type `d.` and later will find, at the top of my file:
```ts
import { d } from 'node_modules/some-obscure/random/dist/folder/with/a-build-variable/that-happens-to-be/d'
```
IMO the original bug report still applies - TAB and ENTER are both documented to finish auto-complete. A period character usually should not, auto-complete and certainly should NOT completely _transform_ something like the word `module` to `useCssModule` which is not an auto-completion and is, in fact, a complete substitution. So I'm confused how that follows developer intent at all.

Can we, by default, just have a period not dump in something un-related, and follow the docs to ask users to press tab to auto-insert the completion?

**Comment by jrieken** [comment]
The setting you are looking for is `editor.acceptSuggestionOnCommitCharacter`. This prevents automatic insertion of completions while typing. I do agree that `.` for the given prefix is a poor choice but that's one made by the vue extension so please also report this issue to them
