### ISSUE TITLE
Missing dash separating filename from Code application title

### ISSUE THREAD

**Issue by lediur** [Microsoft/vscode#20236]
- VSCode Version: 1.10.0-insider eff9148502
- OS Version: Windows 10 Pro Insider Preview 15025

In the Visual Studio Code title bar, when no project folder is open, the filename is not separated from the text "Visual Studio Code - Insiders". This issue persists if the file is saved.

Steps to Reproduce:

1. Open a new window with no project folder open.
2. Notice that Untitled-1 in the title bar shows `Untitled-1Visual Studio Code - Insiders`

**Screenshots:**
![image](https://cloud.githubusercontent.com/assets/1077648/22761810/41b767e4-ee11-11e6-977c-39e1d8cf230c.png)
![image](https://cloud.githubusercontent.com/assets/1077648/22761814/463dc48e-ee11-11e6-95ab-36428d85de76.png)

**Comment by Tyriar** [comment]
Default `window.title` and `"window.title": "${activeEditorName}${separator}${appName}"` works.
