### ISSUE TITLE
The Show Preview button located on top most right side 

### ISSUE THREAD

**Issue by paryagbansal131** [microsoft/vscode#202370]
![Screenshot 2024-01-13 003035](https://github.com/microsoft/vscode/assets/142718792/f86406b3-c2ae-4151-b615-f380d893a34b)
Type: <b>Feature Issue (Request) </b>

By mistake i have clicked on some option, after that the show preview button which is located at the right side of the bar had be disappeared. And now i am tired off to finding any kind of setting related to this and after a lot of  messing up i am writting this report to you.
Kindly help me in this issue to getting back that button back on the bar aggain like the previous ones. As that button was very helpful for me now i am having problem to it . Kindy help he by providing a step-by-step list fo actions to be performed any actions to see that " show preview " button back.
Thank You

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.46GB free)|
|Process Argv|--crash-reporter-id e863e75c-9b48-4fbe-8cc4-08b377125c83|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Workspace Info</summary>

```
|  Window (LEARNING CSS - Visual Studio Code)
|    Folder (LEARNING CSS): 31 files
|      File types: html(10) png(4) css(4) jpg(4) svg(3) json(2) jpeg(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
blackbox|Bla|1.2.50
composer-php-vscode|DEV|1.42.14626
intelli-php-vscode|DEV|0.12.14619
phptools-vscode|DEV|1.42.14626
profiler-php-vscode|DEV|1.42.14626
prettier-vscode|esb|10.1.0
live-server|ms-|0.4.13
material-icon-theme|PKi|4.33.0
LiveServer|rit|5.7.9
material-theme|zhu|3.16.2

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
You can right click > "Reset menu", that will probably do it
