### ISSUE TITLE
VS Code complains about lack of internet

### ISSUE THREAD

**Issue by Zarel** [Microsoft/vscode#20231]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|sublime-commands|Zarel|0.1.0|

---

Steps to Reproduce:

1. Open VS Code
2. Wait a day or so, while switching between various low-quality internet connections 

![image](https://cloud.githubusercontent.com/assets/551184/22759733/2628fdbe-ee19-11e6-8553-9330e0828e54.png)

Now, I'm aware that VS Code uses the internet for various features, including checking for updates and running `git fetch` on startup (or intermittently? not exactly sure when exactly it runs `git fetch`).

But VS Code should not require an internet connection unless I'm doing something like browsing the extension store, and it should not complain about lacking an internet connection while I'm doing literally nothing except leaving it open.

These errors are also kind of frustrating since they're not even telling me what VS is doing that needs an internet connection. A good error message tells me what failed and ideally how to fix it. The first two don't even tell me why I'm supposed to care that I don't have an internet connection, and the third doesn't tell me anything about what request it was or why it's initiating requests.

Like, I don't mind tracking; I opt-into all tracking so it might have been something like that. Just don't show me error messages when your tracking fails; that's your problem, not mine.

**Comment by Tyriar** [comment]
Not sure where the errors are coming from, but it looks like they're exceptions thrown from libraries that aren't handled as I couldn't find the strings in Microsoft/vscode.

**Comment by joaomoreno** [comment]
Yup, I have a feeling this comes from an extension. Could it be the type acquisition?

**Comment by bpasero** [comment]
I actually also got this yesterday.

**Comment by mjbvz** [comment]
I don't think this is TypeScript as it's running in a different process and we handle their errors differently. I also tried to trigger these alerts using ATA but was unable to

**Comment by Zarel** [comment]
Whatever extension it is, it's a built-in extension.

It seems kind of undesirable for VS Code to forward an error message directly from something external, without even noting in some way where the error message is coming from. That leads to cryptic error messages like these that are really hard to debug (if user error, it makes it hard for the user to know what they did wrong; if a bug in VS Code, it makes it hard to track down and fix).

**Comment by mjbvz** [comment]
@Zarel Try going to `Help -> Toggle Developer Tools`. The error messages there should have the complete callstack which may provide some clues as to where this error is coming from

**Comment by Zarel** [comment]
I'm unfortunately on a stable internet connection now, and unable to reproduce this. :(

**Comment by Zarel** [comment]
@mjbvz 

> The Internet connection appears to be offline.
> e.doShow @ workbench.main.js:formatted:103139

That is the entire callstack

![image](https://cloud.githubusercontent.com/assets/551184/23732406/893ba17e-0438-11e7-9506-fc731125a024.png)

![image](https://cloud.githubusercontent.com/assets/551184/23732395/76b076c4-0438-11e7-8299-f14e94323288.png)

**Comment by joaomoreno** [comment]
#21601
