### ISSUE TITLE
This content is blocked. Contact the site owner to fix the issue.

### ISSUE THREAD

**Issue by AnnaIsrael** [microsoft/vscode#202337]
Whenever I click the "Run" button to run my code, the message in the window states that "This content is blocked. Contact the site owner to fix the issue.". I'm not sure how to fix this issue. 

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by AnnaIsrael** [comment]
Thank you for your help! I managed to resolve the issue on my own. Have a great day!

**Comment by SaMyaW02** [comment]
Hi @AnnaIsrael is it possible to share how you resolved this issue?

**Comment by AnnaIsrael** [comment]
Good morning,

I resolved the issue by clicking on the "Open in Browser" button when opening up a new tab within GitHub codespace.
________________________________
