### ISSUE TITLE
Key binding to quick open in new split

### ISSUE THREAD

**Issue by CrashyBang** [Microsoft/vscode#20230]
- VSCode Version: 1.9.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

When using `ctrl`+`p` I can search for a file and hit enter to open it *OR* use the little icon to open the new file in a split.

Ideally I would be able to use the `ctrl`+`\` binding to open in a new split from the quick find, or is this already possible with another key binding I was unable to find?

Cheers.

**Comment by Tyriar** [comment]
You can already do this; ctrl+p to open quick find and then ctrl+enter to open it in a new tab (similar to ctrl+click in the file explorer).
