### ISSUE TITLE
Bug: git initialize repository ignores init.defaultBranch setting and creates main branch

### ISSUE THREAD

**Issue by kgtkr** [microsoft/vscode#202322]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.1
- OS Version: MacOS 14.1.1

Steps to Reproduce:

1. ```
    > git config --global init.defaultBranch
    master
   ```
2.  click `git initialize repository`
3. main branch will be created

Output git log:
```
2024-01-10 10:11:10.641 [info] > git init -b main [13ms]
```

**Comment by lszomoru** [comment]
When creating a new repository using VS Code, it uses the value of the `git.defaultBranchName` setting for the name of the default branch. If you would like it to use the git config, you have to set the value of the setting to the empty string. If that is not the behaviour that you are seeing please feel free to reopen this issue. Thanks!
