### ISSUE TITLE
SCM: Incoming/Outgoing showing for a different branch

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#202335]
Type: <b>Bug</b>

I don't have repro steps, but yesterday my Incoming/Outgoing tree got into a state where it was showing commits belonging to a different branch from the one I had checked out.

Perhaps there is a pathway by which the cache it uses isn't getting cleared correctly.

VS Code version: Code - Insiders 1.86.0-insider (29bef5673ebb1fc3a59b90c9d8bfd2bc61c3f011, 2024-01-12T05:37:28.770Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by gjsjohnmurray** [comment]
More evidence today of a cache problem.

Using today's Insiders I followed my usual procedure for updating my local main of the OSS repo, which is:

1. Make sure main is checked out
2. Fetch From All Remotes
3. Merge upstream/main

Normally at this point I see the blue Sync button with a non-zero count, and below it the outgoing commits. But on this occasion there was no Incoming/Outgoing section. So I set `"scm.showOutgoingChanges": "always"` and got this:

![image](https://github.com/microsoft/vscode/assets/6726799/50693e56-e41b-4007-a706-d77e4fbdfc06)

Exiting VS Code and reopening it I got the correct display, and reset that setting to its default:

![image](https://github.com/microsoft/vscode/assets/6726799/38e8e8eb-eea0-4e67-8a2e-c4f9e5d2b73e)

Shortly before this incident I had checked out main and used `Git: Delete...` to delete my local copy of a branch I had used for a bugfix PR that had just been approved and merged. Don't know if that sequence could have left the incoming/outgoing cache in a bad state.

**Comment by lszomoru** [comment]
@gjsjohnmurray, thank you very much for filing the issue. Yes, I have seen this in the past but I was not able to come up with a consistent set of steps to reproduce the problem. Any additional information that you can provide would be of great help in the effort to get to the bottom of this issue. 

One way to confirm that indeed it is a caching issue is to click the "Refresh" action in the Source Control view title as the "Refresh" action clears the incoming/outgoing cache. I will continue to look the code but please feel free to share any additional findings. Thank you!

**Comment by lszomoru** [comment]
I have refactored some of the state management code and I have fixed an issue that might have caused this behaviour. The fix is included in the VS Code release listed below. I will optimistically close this issue but please feel free to reopen it in case you are still able to reproduce the issue. Thanks!

```
Version: 1.86.0-insider (Universal)
Commit: e244acbb172c428cb219717a07bf55d2737492ca
Date: 2024-01-22T05:37:04.772Z
Electron: 27.2.1
ElectronBuildId: 26149897
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0
```
