### ISSUE TITLE
`TitleBarPart` does not emit `onDidChange` events when zooming is prevented

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#202377]
It seems that the `TitleBarPart` changes its `minimumHeight` in cases where it wants to prevent zoom. This can happen when:
* there are no controls in the custom title that require zooming
* the user zooms out below `0`

https://github.com/microsoft/vscode/blob/c1496443c09fc9de289ff0ac97db0e350902641f/src/vs/workbench/browser/parts/titlebar/titlebarPart.ts#L190-L196

This works fine today, but as it turns out, does not adhere to the rules of a component that is part of the grid: a component must emit a `onDidChange` event when its size constraints change:

https://github.com/microsoft/vscode/blob/c1496443c09fc9de289ff0ac97db0e350902641f/src/vs/base/browser/ui/grid/gridview.ts#L100-L114

I only noticed this because of a bug in floating windows related to this when zooming, but I am actually surprised this does not cause issues in the main window today. I am pushing https://github.com/microsoft/vscode/pull/202378 for the floating window issue because I am not sure of the consequences of addressing this issue here.

**Comment by sbatten** [comment]
So we should just add a listener for zoom level change in titlebarpart and emit the event?

**Comment by bpasero** [comment]
@sbatten yeah I can do a PR for that because I had the change prepped, however the reason I did not just push it is because I then noticed flicker when zooming in or out where the title bar would jump up and down a bit. That is actually why I filed this issue first to see if we need to do this or if it actually works fine even without.

**Comment by bpasero** [comment]
Opened https://github.com/microsoft/vscode/pull/202400

The flicker is visible (when title prevents zooming):
![Recording 2024-01-13 at 07 47 46](https://github.com/microsoft/vscode/assets/900690/4f5e6154-cd1d-4459-8881-f6d7744c47b9)

**Comment by bpasero** [comment]
I am not convinced to change this because I see regressions in floating windows and flicker.
