### ISSUE TITLE
Can't enable settings sync UI State option - "too large payload"

### ISSUE THREAD

**Issue by vaindil** [microsoft/vscode#202359]
I had to clear settings sync for an unrelated issue and start fresh, but enabling the "UI State" option causes the error below to be continually thrown. If I disable the "UI State" option in settings sync, it starts working again.

```
[error] TooLarge (UserDataSyncError) syncResource:globalState operationId:unknown: POST request 'https://vscode-sync.trafficmanager.net/v1/resource/globalState' failed because of too large payload (413).
    at a.mb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:19807)
    at async a.tb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:38857)
    at async a.ab (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:15032)
    at async a.Z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:13321)
    at async a.Y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:12350)
    at async a.U (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:10889)
    at async a.sync (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:10186)
    at async a.sync (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:111668)
    at async r.S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:103974)
    at async r.P (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:102847)
```

Type: <b>Bug</b>

1. Enable settings sync, check all boxes _except_ "UI State"
1. Watch settings sync log, see that it succeeds
1. Update settings sync config to include UI State

VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|--crash-reporter-id a9d46dd4-9a53-4438-a4a8-1f63f7b38ae4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
vscode-eslint|dba|2.4.2
prettier-vscode|esb|10.1.0
codespaces|Git|1.16.6
copilot|Git|1.148.0
copilot-chat|Git|0.11.1
vscode-graphql-syntax|Gra|1.2.3
endwise|kai|1.5.1
remote-containers|ms-|0.327.0
proto|pet|0.0.4
rewrap|stk|1.16.3
gitblame|wad|10.6.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30933248
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019acf:30933242

```

</details>

**Comment by sandy081** [comment]
Can you please share the UI state using following steps

- F1 > Export Profile...
- Select only UI state
- Export the profile and share it

**Comment by vaindil** [comment]
The exported file is 2.3 MB, and it has some things inside that might be considered sensitive, I'm not sure. Is there a way I can share it privately?

**Comment by sandy081** [comment]
You can share it to me by email - sasomava@microsoft.com

@Tyriar 2.3 MB is way under the limits right?

**Comment by vaindil** [comment]
Just emailed the file, thank you!

**Comment by sandy081** [comment]
Thanks for sharing. I figured out that port forwarding state is taking majority of the size. Hence assigning to @alexr00

**Comment by alexr00** [comment]
Discussed with @sandy081 and there are 3 easy things I can do to quickly reduce the size:
- Don't save empty `remote.tunnels.toRestore` values
- Add an expiry time to `remote.tunnels.toRestore` values so they don't live forever
- Save fewer fields per port in `remote.tunnels.toRestore`. For example, only `closable` tunnels should be stored + restored, so `closable` should be removed. So should `privacy`, `runningProcess`, `hasRunningProcess`, and `pid`.

**Comment by Tyriar** [comment]
@sandy081 the limit per resource is 2mb atm

**Comment by connor4312** [comment]
Are there steps to verify this?

**Comment by alexr00** [comment]
To verify:
1. Connect to a Codespace and forward a port
2. Close the remote connection
3. Follow the steps in https://github.com/microsoft/vscode/issues/202359#issuecomment-1892200637 to collect a profile
4. Open the file created in step 3. Check that the port that you just forwarded in step 1 is listed there under a `remote.tunnels.toRestore` key and that it doesn't have a `closable` value.

**Comment by TylerLeonhardt** [comment]
This is verified. The new port forwarded doesn't have `closable`, but @alexr00 I did notice some old ports of mine from old codespaces still having `closable`. Not sure if that was expected to be covered.

**Comment by alexr00** [comment]
The behavior you see is expected. I didn't add any cleanup of the old state.
