### ISSUE TITLE
Folder/Workspace not being saved upon opening

### ISSUE THREAD

**Issue by heriga** [microsoft/vscode#202442]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.85.1
- OS Version:  macos 14

Steps to Reproduce:

1.  Download vscode
2.  Open a folder/add to workspace
3. Close vscode
4. Folder is not opened when opening vscode again

Whenever i open a folder and close vscode my winodws are not restored. the Restore Windows is set to all and i already tried uninstalling/installing vscode again but still does not work. Everytime i open vscode i need to manually open my folder/workspace. Help

**Comment by bpasero** [comment]
You are closing the individual window but not the app via quitting.

**Comment by heriga** [comment]
Even when i quit the app and open it again the folder is not opened and i have to manually open it.
