### ISSUE TITLE
Could not open a folder.

### ISSUE THREAD

**Issue by heheboy1603** [microsoft/vscode#202434]
Type: <b>Bug</b>

I pressed Ctrl + K + Ctrl + O (hotkey to open a folder), the program works very good until I press Seclet folder and it did not open the chosen folder. Please help me as soon as possible because I don't like wasting my time pressing Ctrl + O to open each file in the chosen folder. Thanks for reading my report.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.75GB (0.34GB free)|
|Process Argv|--crash-reporter-id e013c8b7-d934-45d2-a1ee-cc285af44be4|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-color-dlw|Bra|0.0.6
bracket-pair-toggler|dzh|0.0.3
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.103
cpptools|ms-|1.19.1
cpptools-extension-pack|ms-|1.3.0
code-spell-checker|str|3.0.1
tabnine-vscode|Tab|3.57.0
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30933248
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by heheboy1603** [comment]
Thanks for your help!!
