### ISSUE TITLE
Window maximize disabled

### ISSUE THREAD

**Issue by Nikhilnv1209** [microsoft/vscode#202425]
Type: <b>Bug</b>

The window maximize button is disabled on the vscode and i am not able to maximize or toggle the maximize the screen. Only minimize and close is working

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.74GB (1.40GB free)|
|Process Argv|--crash-reporter-id ac2ec26c-0153-401c-bd03-e404d146a42a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
tailwind-documentation|alf|0.1.15
vscode-tailwindcss|bra|0.10.5
vscode-animations|Bra|2.0.1
apc-extension|drc|0.3.6
es7-react-js-snippets|dsz|4.4.3
bracket-pair-toggler|dzh|0.0.3
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
copilot|Git|1.148.648
copilot-chat|Git|0.12.2023120701
go|gol|0.40.1
headwind|hey|1.7.0
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.25
isort|ms-|2023.10.1
python|ms-|2023.22.1
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.16.32
cpptools|ms-|1.19.1
powershell|ms-|2024.0.0
vsliveshare|ms-|1.0.5905
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.33.0
prisma|Pri|5.8.0
vscode-thunder-client|ran|2.17.0
reactree|Rea|1.0.8
java|red|1.26.0
LiveServer|rit|5.7.9
code-snapshot|rob|0.2.1
autoimport|ste|1.5.4
vscode-styled-components|sty|1.7.8
cmake|twx|0.0.17
vscode-java-dependency|vsc|0.23.3
vscode-maven|vsc|0.43.0
vscode-import-cost|wix|3.3.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019acf:30933242

```

</details>

**Comment by antpowell** [comment]
@Nikhilnv1209 Could you add your solution. I'm having the same issue but I can't seem to find a fix.

**Comment by hie-senberg** [comment]
Same here

**Comment by Nikhilnv1209** [comment]
Hello,
Actually that was the case because of an extension used for animation called vscode-animations, apc-extension.

I had to change some configuration but then i was using linux so there was some permission issues so i just uninstalled the extension and it worked fine again.

**Comment by hie-senberg** [comment]
Okay, thanks for the reply.
