### ISSUE TITLE
Bad bash syntax highlighting with multi line strings and single quotes

### ISSUE THREAD

**Issue by NicolasGoeddel** [microsoft/vscode#202493]
Does this issue occur when all extensions are disabled?: Yes

# Metadata
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-91-generic snap

# Bug
## Initial variant
![image](https://github.com/microsoft/vscode/assets/1520064/f1482a58-db82-4db3-8e3c-47bb08a085f9)
**Code:**
```bash
#!/bin/bash

cat << \
────────────────────────────────────────────────────────────────────────────────
oh no's
/* this comment and everything
 * after has wrong colors
 */
────────────────────────────────────────────────────────────────────────────────

function foo() {
    echo "Function foo"
}

foo

```
As you can see, even here in Github everything after the `oh no's` has wrong colors.
## Other variant
![image](https://github.com/microsoft/vscode/assets/1520064/45da2688-3ee1-4078-b5a5-6ef45d793724)
**Code:**
```bash
#!/bin/bash

cat << \
EOL
oh no's
/* this comment and everything
 * after has wrong colors
 */
EOL

function foo() {
    echo "Function foo"
}

foo
```
# Working example
## Without single quote
This works in VSCode but not on Github.
![image](https://github.com/microsoft/vscode/assets/1520064/e160384e-999c-40f4-9e2d-e6f15598a91a)
**Code:**
```bash
#!/bin/bash

cat << \
EOL
oh nos
/* this comment and everything
 * after has wrong colors
 */
EOL

function foo() {
    echo "Function foo"
}

foo
```
## Without line break after <<
This works in VSCode and on Github.
![image](https://github.com/microsoft/vscode/assets/1520064/8e8cfc8d-e8ae-459e-a811-178a3f6501a2)
**Code:**
```bash
#!/bin/bash

cat <<EOL
oh no's
/* this comment and everything
 * after has wrong colors
 */
EOL

function foo() {
    echo "Function foo"
}

foo
```

**Comment by NicolasGoeddel** [comment]
## Another workaround
Just escape the single quote.
![image](https://github.com/microsoft/vscode/assets/1520064/3bb78c28-8536-4520-a84c-acbba8c3a86c)
**Code:**
```bash
#!/bin/bash

cat << \
────────────────────────────────────────────────────────────────────────────────
oh no\'s
/* this comment and everything
 * after has wrong colors
 */
────────────────────────────────────────────────────────────────────────────────

function foo() {
    echo "Function foo"
}

foo
```

**Comment by alexr00** [comment]
Thank you for all the details! I've copied the issue to the repo that we pull our shell script syntax highlighting grammar from: https://github.com/jeff-hykin/better-shell-syntax/issues/73
