### ISSUE TITLE
Cannot drag and drop a file with no extension to the explorer on Linux

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#20240]
- VSCode Version: 1.9.0
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Create a file with no extension
2. Drag it to the explorer, fails

If you drag and drop it to the editor, it can be opened correctly and it's shown in the OPEN EDITORS but you just can't drop it to the explorer.

**Comment by chrmarti** [comment]
Confirmed on Ubuntu 32-bit while sanity-checking the bits. (Haven't tried others.)

**Comment by Tyriar** [comment]
Doesn't repro on 64-bit so not high priority.

**Comment by chrmarti** [comment]
@rebornix was using 64-bit.

**Comment by Tyriar** [comment]
What was the file name exactly? I tried "jquery" (no ext) and it worked file?

**Comment by Tyriar** [comment]
This works now.
