### ISSUE TITLE
Aux window: do not render URL bar below title

### ISSUE THREAD

**Issue by futurist** [microsoft/vscode#202430]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: MacOS 13.4 (22F66)

Steps to Reproduce:

1. Chrome Browser, open vscode.dev
2. Install PWA
3. Open a file, right click in Tab Title Menu: Move into new Window
4. The Opened floating window shown extra blank title area.

![image](https://github.com/microsoft/vscode/assets/159167/35523562-4135-4391-83a8-31c07b88a315)

**Comment by bpasero** [comment]
This is something Chrome seems to be adding, when not using PWA you can see its this:

<img width="568" alt="image" src="https://github.com/microsoft/vscode/assets/900690/39253dd2-301e-426f-b286-2d3f5f55ffb3">

And it seems to be the same in PWA, even though not rendering the same:

<img width="253" alt="image" src="https://github.com/microsoft/vscode/assets/900690/c84299b4-0aef-44ee-a09a-b653fd410948">

If someone knows how to disable this, please chime in.

**Comment by jzyrobert** [comment]
@bpasero I can't find the exact source for this, but for security reasons the url bar will always be shown unless the site has a valid SSL certificate. I can see that the popup window is opened with `about:blank` here: https://github.com/microsoft/vscode/blob/6d6bb5889a1eed4afb4d9bfec9cbda6720a189d9/src/vs/workbench/services/auxiliaryWindow/browser/auxiliaryWindowService.ts#L264

But I don't know how you would change that to be e.g. https://vscode.dev instead. `auxiliaryWindow.history.replaceState` may or may not work.
