### ISSUE TITLE
VSCode UI becomes blurry.

### ISSUE THREAD

**Issue by ahamedsuhails** [microsoft/vscode#202439]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

- OS Version:  Windows 11

![image](https://github.com/microsoft/vscode/assets/75640953/8aaf64cf-e008-4c38-817c-2448597dc154)
When the window is active, the issue is less likely to happen. If this was some issue with my laptop display, wouldn't all the applications have the same issue?

Steps to Reproduce:

1.  Open VSCode,

**Comment by ahamedsuhails** [comment]
![Screenshot 2024-01-14 122814](https://github.com/microsoft/vscode/assets/75640953/245b17ed-a4d0-4539-8cac-6e04110d0579)

Even when the application is in full window and active, the issue still exist

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/201774#issuecomment-1887807355 help?

**Comment by ahamedsuhails** [comment]
> Does [#201774 (comment)](https://github.com/microsoft/vscode/issues/201774#issuecomment-1887807355) help?


Disabling hardware acceleration did work for me. I am not facing the issue now. Thanks for your help.
