### ISSUE TITLE
Unable to read from console

### ISSUE THREAD

**Issue by samzuercher** [microsoft/vscode#202488]
Steps to Reproduce:

1. dotnet new console
2. Try to read something from the Console e.g. with `Console.ReadKey()`
3. Gives Exception
>Exception has occurred: CLR/System.InvalidOperationException
Exception thrown: 'System.InvalidOperationException' in System.Console.dll: 'Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.'

⚠️ This Issue has already been raised several times:
- https://github.com/microsoft/vscode/issues/179057
- https://github.com/microsoft/vscode/issues/179378

Nothing of these options has worked for me so far
>"console": "externalConsole",
"console": "externalTerminal",
"terminal": "external",
"externalConsole": true,

in `launch.json`
> {
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C#: console",
            "type": "dotnet",
            "request": "launch",
            "projectPath": "${workspaceFolder}\\console\\console.csproj",
            "launchConfigurationId": "TargetFramework=;console",
            "console": "externalConsole",
        }
    ],
}

💡Also: it would be nice to be able to upvote closed issues as well. If an issue does not get enough upvotes within some time it may get them later. I think vscode is not fully usable if it is not able to read from the Console, therefore this feature really needs to be implemented.
💡This documentation seems to be outdated, it also mentions the `"console"` - setting: https://code.visualstudio.com/docs/csharp/debugger-settings

**Comment by roblourens** [comment]
Please file this on the C# extension repo, thanks!

**Comment by samzuercher** [comment]
@roblourens why do you think it has anything to do with an extension? It is not the extension, it is `dotnet launch`
