### ISSUE TITLE
data viewer doesn't work

### ISSUE THREAD

**Issue by LayneWu50** [microsoft/vscode#202477]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.1
- OS Version: win10

Steps to Reproduce:

I got the lastest vscode (version 1.85.1) and the latest juytper (v2023.11.1100101639), after that, I found the data viewer doesn't work anymore

**Comment by tahendry** [comment]
The data viewer while debugging is also gone for me. Any ideas why or what the issue could be?

Version: 1.86.0-insider (user setup)
Commit: 0b571a26e213bf1ec6266e37152ced80c006bd1e
Date: 2024-01-18T05:36:10.559Z
Electron: 27.2.1
ElectronBuildId: 26149897
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by amunger** [comment]
using the dataviewer while debugging has been fixed in the latest insiders.

@LayneWu50 - I'm not able repro in 1.85, what specific behavior are you seeing when it doesn't work? any error messages?

**Comment by tahendry** [comment]
I don't know if my information helps, but in my case, if I right click on a pandas dataframe, it only shows the following:
![image](https://github.com/microsoft/vscode/assets/77280556/13e20e21-b73a-49b1-b5f4-12b38b1e3906)

The above picture is a screenshot with the following version of vscode insiders:
Version: 1.86.0-insider (user setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T03:29:50.526Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

----------------------
If I do exactly the same with vscode, it works ("View Value in Data Viewer" is shown when right clicking). I am also using the same code and same environment as above with vscode insiders.
Here is my version of the vscode:
Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by tahendry** [comment]
In both cases, I am debugging a .py script, with the same conda environment. 
When executing "pip list" these are the versions of the jupyter packages:
![image](https://github.com/microsoft/vscode/assets/77280556/8fdd2a66-8469-4dab-9d54-06ac184541af)

**Comment by amunger** [comment]
By Jupyter Extension, I meant the vs code jupyter extension. That extension contributes the data viewer.

![image](https://github.com/microsoft/vscode/assets/2019016/a62af9e9-1788-4f68-b9fd-82fbd3dac874)

**Comment by amunger** [comment]
likely this issue: https://github.com/microsoft/vscode-jupyter/issues/15121

**Comment by tahendry** [comment]
Thanks for the help. Since the new update of VSCode Insiders and after reloading all extentions (automatically after starting VSCode), it is working again.
