### ISSUE TITLE
create hotkey for test and debug_test in npm debug script

### ISSUE THREAD

**Issue by dmitryk1** [microsoft/vscode#202407]
I make node project in VSCode and build config for it:
```
{
  "name": "testproject",
  "version": "1.0.0",
  "description": "desc",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "mocha test.js",
    "test_unit": "mocha test_unit.js"
  },
}
```

In interface it view like:
![Screenshot_4](https://github.com/microsoft/vscode/assets/1874995/0061db0b-8bc1-45b1-95f7-47c35344e87f)

and I try add hotkey to debug(bag) button which show when mouse move over npm test zone. 

[stackoverflow question](https://stackoverflow.com/questions/77801815/how-can-i-bind-a-keyboard-shortcut-for-npm-script-debug-in-vs-code/77808814)

**Comment by starball5** [comment]
You would do well to have the courtesy not to make the VS Code maintainers have to read an external Q&A to understand what exactly you're asking for...

**Comment by roblourens** [comment]
You can set a keyboard shortcut to run a task like this https://stackoverflow.com/a/43239574/129895
