### ISSUE TITLE
No display scaling for Release Notes

### ISSUE THREAD

**Issue by thebend** [Microsoft/vscode#20245]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|python|donjayamanne|0.5.8|
|beautify|HookyQR|0.7.3|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.9.0|

---

On Windows 10, using DPI scaling (at 175%), opening VSCode after updating it to the latest version for the first time, the Release Notes tab appears automatically, but the content inside the tab is not scaled to fit the window.  It appears to be sized as if DPI scaling was at 100%.

**Comment by joaomoreno** [comment]
#5745
