### ISSUE TITLE
Preview Xcode Build Progress

### ISSUE THREAD

**Issue by Number-3434** [microsoft/vscode#202409]
Currently, you are only told when an application has finished building. It would be much more useful to see the current build progress (like in Xcode).
![IMG_4598](https://github.com/microsoft/vscode/assets/115815794/1c7838a8-eddd-469d-8a62-6015c866a850)

**Comment by Number-3434** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/202412
```

**Comment by gjsjohnmurray** [comment]
Did you install an extension to handle Xcode projects? If so please raise your issue with the extension author.

**Comment by Number-3434** [comment]
Closing as not-planned, out-of-scope.
