### ISSUE TITLE
Disable JSONC trailing comma warning by default

### ISSUE THREAD

**Issue by theoludwig** [microsoft/vscode#202422]
## Environment Context

- VS Code Version: 1.85.1
- OS Version: 
   ```sh
   $ uname -a                                                        
   Linux theoludwig-pc 6.6.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 05 Jan 2024 16:20:41 +0000 x86_64 GNU/Linux
   ```

## Bug description

Step to Reproduce: Editing a `.jsonc` file, display warnings related to trailing commas.

Does this issue occur when all extensions are disabled?: Yes.

A duplicated issue has been closed recently, too quickly without even trying to investigate the real reason to disable it (and IMO for the wrong reasons): https://github.com/microsoft/vscode/issues/194550.
Would like to open this new issue, to highlight the issue more.

## Reasons

1. [node-jsonc-parser](https://github.com/microsoft/node-jsonc-parser) supports trailing comma.
2. Prettier (a massively used extension in VSCode) now automatically formats the `.jsonc` file with trailing comma by default since v3.2.0, [Changelog Reference](https://prettier.io/blog/2024/01/12/3.2.0#new-jsonc-parser-added-15831httpsgithubcomprettierprettierpull15831-by-fiskerhttpsgithubcomfisker).

If even with all those reasons, the default behavior should still be to display a warning, please make it a config setting to disable it at least. 

But would be best to not have any config settings, as the behavior of Prettier by default (without config) is to format with trailing comma (Ref: https://prettier.io/docs/en/options#trailing-commas, "Default value changed from `es5` to `all` in v3.0.0").

**Comment by theoludwig** [comment]
Pinging @aeschli, as he is the one closing #194550 issue. :smile:

**Comment by theoludwig** [comment]
About https://github.com/microsoft/vscode/issues/194550#issuecomment-1881157719 comment:

> We don't plan to add a user setting to turn off the errors for trailing commas. In plain JSON it is an error to have a trailing comma, and JSONC is not a standard and we only want to promote it for our own setting files and for some selected configuration files.

I agree that this warning should still be enabled in simple plain `.json` file.
But even if JSONC is not a standard, it is commonly used with trailling comma.

**Comment by RedCMD** [comment]
why not comments? aeschli
![image](https://github.com/microsoft/vscode/assets/33529441/177b2f70-4a65-40d5-b663-44f930371d4d)

**Comment by jmjoy** [comment]
I think `jsonc` should be standardized so that it can benefit software other than vscode.

**Comment by vorburger** [comment]
https://github.com/microsoft/vscode/issues/102061 mentioned `allowTrailingCommas`, but this doesn't seem to work anymore? Perhaps at the very least that issue could be updated?

**Comment by RedCMD** [comment]
@vorburger `allowTrailingCommas` works for me
it is only supported at the top/root level of the schema file tho

**Comment by aeschli** [comment]
See https://github.com/microsoft/vscode/pull/203387#issuecomment-1909686444 for more background.

By showing a warning we stay on the safe side, but an extension can configure that behaviour by associating a schema that controls that.

**Comment by theoludwig** [comment]
Thank you for your detailled explanation. @aeschli 

From my understanding, the issue should be fixed by JSON schema authors, if they successfuly parse JSON files with trailing commas, and they have a schema, they should put `"allowTrailingCommas": true` in their schema to allow it.
And I agree, with this, so any config, can tell if it allows trailling commas or not. :+1:

While we could argue, that, `"allowComments": true` should have the same treatment , it is probably fine like that.

Will now open PRs to related JSON Schema authors, to allow trailing commas, if they allow to parse it that way. :+1:
Starting by opening a PR for https://github.com/DavidAnson/markdownlint-cli2/pull/270
