### ISSUE TITLE
The "Format Selection" right-click menu item doesn't work anymore after update

### ISSUE THREAD

**Issue by CapitalGrid** [Microsoft/vscode#20248]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.6|
|debugger-for-chrome|msjsdiag|2.4.2|

---

Steps to Reproduce:

1. Select a few line of code
2. Right-click mouse and choose "Format Selection"
3. You will see that the function actually mess up the code format instead of tidy it up.

**Comment by DonJayamanne** [comment]
@CapitalGrid 
Are you trying to format a block of Python code?

**Comment by CapitalGrid** [comment]
I use it to format Python, JavaScript, and HTML code.

On 23 Feb 2017 8:11 PM, Don Jayamanne <notifications@github.com> wrote:

@CapitalGrid<https://github.com/CapitalGrid>
Are you trying to format a block of Python code?

**Comment by alexandrudima** [comment]
@CapitalGrid Can you please provide a specific file + a selection, where you trigger format selection and the result is incorrect.

This will help us dispatch this issue to the right person: Python, Javascript and HTML all have different owners.

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.
