### ISSUE TITLE
An option to pin / favorize recently opened projects 

### ISSUE THREAD

**Issue by khashabri** [microsoft/vscode#202445]
I usually have to open many different projects in vscode. And some of them less frequent than the others. Whenever I go `File -> Recently Opened` (on Windows) to find the project that I need, it looks very messy and it is difficult to find my main one, because it goes down in the list or sometimes even gets lost completely. I would appreciate having an option right in `Recently Opened` near the project paths to prioritize some of them so they are always staying at the top.

![2024-01-14 13_05_00-Visual Studio Code](https://github.com/microsoft/vscode/assets/50481847/ad180b0a-ffea-4bb9-b774-021c33e4635c)

**Comment by gjsjohnmurray** [comment]
Did you try pinning VS Code to your Task Bar, then pinning selected recent entries to that icon's popup menu?

**Comment by khashabri** [comment]
That's a good workaround, thanks. At least for windows. Not sure about the other OSs.
