### ISSUE TITLE
Had a problem using the search and replace: my search results tab didnt scroll, so once i went across some files I was stuck there. Is this known?

### ISSUE THREAD

**Issue by ashishmansukhani** [Microsoft/vscode#20243]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|easy-icons|jamesmaj|0.3.1|
|FlatUI|lkytal|1.1.0|
|material-icon-theme|PKief|1.3.2|

---

Steps to Reproduce:

1. Search for something with a large number of results in a large number of files
2. Expand all results
3. try to scroll up and down

**Comment by roblourens** [comment]
Haven't seen this before. Do you see a scrollbar?

**Comment by ashishmansukhani** [comment]
I upgraded my client, and I see a scrollbar now. Not sure what was causing this.
