### ISSUE TITLE
Window jumps when moving cursor downwards if previewing markdown side by side

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#20241]
- VSCode Version: 1.9.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open https://github.com/Microsoft/vscode-smoketest-express/blob/master/readme.md
2. Preview Markdown side by side
3. Press Arrow Down and you can see the window jumps when the cursor comes across the boundaries.

I don't see this issue on macOS.

**Comment by mjbvz** [comment]
I'm having trouble reproducing this, although I was testing on Ubuntu 14.04. Let's take a look tomorrow whenever you have a chance

**Comment by mjbvz** [comment]
I think this may have been fixed by 3da42e56591a55c445e97cead52d24cefc4b8d07. Let me know if you still see this in the latest builds and I'll take another look
