### ISSUE TITLE
Git Syncronise icon wobbles

### ISSUE THREAD

**Issue by wopian** [Microsoft/vscode#20247]
- VSCode Version: 1.9.0
- OS Version: Windows 10

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.5|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.8.1|
|sass-lint|glen-84|0.0.3|
|markdown-shortcuts|mdickin|0.5.0|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.9.0|
|material-icon-theme|PKief|1.3.2|
|vue|seanwash|0.4.2|
|theme-tinaciousdesign|tinaciousdesign|0.1.1|
|vscode-wakatime|WakaTime|1.0.6|
|agc-assembly|wopian|0.2.2|

---

The 'syncronise changes' icon in the status bar wobbles while it's rotating. [Gfycat](https://gfycat.com/CelebratedKindheartedGull)

Steps to Reproduce:

1. Ctrl + Shift + G
2. Open dropdown
3. Click 'Sync'

**Comment by joaomoreno** [comment]
This is going away soon. #18615

**Comment by wopian** [comment]
@joaomoreno this is still an issue after 1.10, although not nearly as bad.

https://gfycat.com/MarvelousEverlastingFlamingo
