### ISSUE TITLE
Crash when maximizing window under kde wayland, Latest Arch Linux

### ISSUE THREAD

**Issue by EVANGELION-Air** [microsoft/vscode#202416]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Arch Linux
- KDE Plasma: 5.27.10
- 

Steps to Reproduce:

1. edit ~/.config/code-flags.conf and add  `--ozone-platform=wayland` or `--ozone-platform-hint=auto` to ensure run VSCode natively under Wayland
2. VSCode crash if you maximizing it, everything is fine if you dont maximizing.

**Comment by gjsjohnmurray** [comment]
Probably #184124 which it sounds like is fixed in upcoming 1.86 (current Insiders version).

**Comment by wmertens** [comment]
BTW this only happens when custom window title bar is enabled.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/184124
