### ISSUE TITLE
code cli serve-web user-data-dir arg cannot work

### ISSUE THREAD

**Issue by ttttmr** [microsoft/vscode#202404]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: code 1.85.1 (commit 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2)
- OS Version: Debian 12

Steps to Reproduce:

1. install code cli
2. run `code serve-web --host xxxx--port xx --connection-token xxxxxx --accept-server-license-terms --user-data-dir /tmp/userdata`
3. use Chrome privacy mode to open
4. edit user settings, fill in something
5. view /tmp/userdata in the terminal, which is empty inside

**Comment by connor4312** [comment]
The web version of VS Code does not store user settings locally, it only stores in-browser, as that is the "user".

Settings can be stored on the server by editing your remote settings via **Preferences: Open Remote Settings**.
