### ISSUE TITLE
JavaScript use string template variable raise error when run in Debug mode

### ISSUE THREAD

**Issue by jkryanchou** [microsoft/vscode#202555]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.85.1
- OS Version: Ventruen 13.4.1

Steps to Reproduce:

1. Using string template in our javascript file. like below in `console.log(...)` statements.

```javascript
...

  const { supplyAmount, borrowAmount, payAmount } = await calculateAmounts(args['--plan']);
  const { approveTx, supplyTx } = await supplyUSDCToAAVE(usdcContract, aavePoolContract, supplyAmount, userAddr);
  const borrowTx = await borrowGHOFromAAVE(aavePoolContract, borrowAmount, userAddr);
  const payTx = await payToService(ghoContract, serviceAddr, payAmount);

  console.log(`Supply ${supplyAmount / USDC.decimals} USDC to AAVE Pool TX: ${supplyTx.hash}`);
  console.log(`Borrow ${borrowAmount / GHO.decimals} GHO from AAVE Pool TX: ${borrowTx.hash}`);  
  console.log(`Pay ${payAmount / GHO.decimals} GHO to service wallet TX: ${payTx.hash}`);
...
```

2. Run in Debug mode. it will raise the exception as below
![image](https://github.com/microsoft/vscode/assets/1206342/4dcdc0a2-3f01-4632-8852-b665e30d597f)

    I have no idea what's wrong with my code snippets. I just use the `ether.js` one library.

3. When I remove the `console.log()` statements which within the single quote ``. It debug like charming.

**Comment by IllusionMH** [comment]
Is it reproducible with those `console.log`s and template literals if you run it directly?
Looks like exception originates for executed code, not from debugger/VS Code when function is passed instead of JSON string.
