### ISSUE TITLE
Markdown Tables don't render - when markdown table has an empty cell 

### ISSUE THREAD

**Issue by jchliao** [microsoft/vscode#202597]
```markdown
| Header 1 | Header 2 |
|----------|----------|
| Cell 1   | Cell 2   |
| Cell 3   | Cell 4   |
```
| Header 1 | Header 2 |
|----------|----------|
| Cell 1   | Cell 2   |
| Cell 3   | Cell 4   |

Can render properly
```markdown
|               | Header 2 |
|----------|----------|
| Cell 1   | Cell 2   |
| Cell 3   | Cell 4   |
```
Cannot render properly
```markdown
| Header 1 | Header 2 |
|----------|----------|
| Cell 1   |             |
| Cell 3   | Cell 4   |
```
Cannot render properly

**Comment by SilasRodrigues19** [comment]
Hey @jchliao 

It seems to work correctly here, however I use the [Markdown Preview Enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) extension to preview markdown files in VSCode.

The shortcut to open the markdown preview with this extension is `CTRL + K` `V`

![image](https://github.com/microsoft/vscode/assets/47532703/8fae162b-664d-497a-b78f-09030fe3545b)

**Comment by jchliao** [comment]
![table1](https://github.com/microsoft/vscode/assets/57680590/25bab5df-adfb-47d2-932a-a601b5896e05)
It works fine in md files, but the Markdown cell does not render in ipynb

**Comment by jchliao** [comment]
版本: 1.85.2 (system setup)
提交: 8b3775030ed1a69b13e4f4c628c612102e30a681
日期: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by amunger** [comment]
Can you try [disabling all extensions](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by jchliao** [comment]
Name: Quarto
Id: quarto.quarto
Description: Extension for the Quarto scientific and technical publishing system.
Version: 1.110.1
Publisher: Quarto
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=quarto.quarto
quarto caused the problem

**Comment by mjbvz** [comment]
Thanks for checking. Please file an issue against that extension
