### ISSUE TITLE
On editor window launch, .vscode/settings.json is modified 

### ISSUE THREAD

**Issue by lucasyvas** [microsoft/vscode#202527]
Type: <b>Bug</b>

VSCode is editing the `.vscode/settings.json` file on launch for a reason I cannot explain. I've disabled all extensions, yet the behavior persists. I'm not signed in for any kind of settings sync and it seems to also be happening for another team member.

It seems as if one option is deprecated - it coincidentally changes it to a non-deprecated value. The other setting is not deprecated and it just changes it for seemingly no reason.

This results in there being a new change detected on every editor window (re)launch because we check it into git so it's pretty annoying.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:16.874Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by rzhao271** [comment]
What does the file get edited to? Or, which setting key is affected?

**Comment by lucasyvas** [comment]
Sorry about that. The file goes from this:

```json
{
    "[elixir]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 2,
        "editor.wordBasedSuggestions": false,
        "editor.formatOnType": true,
        "editor.formatOnSave": true,
        "editor.trimAutoWhitespace": false,
        "files.trimTrailingWhitespace": true,
        "files.insertFinalNewline": true,
        "files.trimFinalNewlines": true,
        "editor.defaultFormatter": "JakeBecker.elixir-ls",
        "editor.formatOnSaveMode": "file",
    },
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true,
    },
    "phpcs.standard": "./core/phpcs.ruleset.xml",
    "phpcs.executablePath": "./core/bin/dev/phpcs_exec",
    "typescript.tsdk": "./node_modules/typescript/lib",
    "ansible.python.interpreterPath": "/bin/python3",
    "gitlens.ai.experimental.generateCommitMessage.enabled": false,
}
```

to this:

```json
{
    "[elixir]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 2,
        "editor.wordBasedSuggestions": "off",
        "editor.formatOnType": true,
        "editor.formatOnSave": true,
        "editor.trimAutoWhitespace": false,
        "files.trimTrailingWhitespace": true,
        "files.insertFinalNewline": true,
        "files.trimFinalNewlines": true,
        "editor.defaultFormatter": "JakeBecker.elixir-ls",
        "editor.formatOnSaveMode": "file",
    },
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": "explicit"
    },
    "phpcs.standard": "./core/phpcs.ruleset.xml",
    "phpcs.executablePath": "./core/bin/dev/phpcs_exec",
    "typescript.tsdk": "./node_modules/typescript/lib",
    "ansible.python.interpreterPath": "/bin/python3",
    "gitlens.ai.experimental.generateCommitMessage.enabled": false,
}
```

`[elixir].editorBasedWordSuggestions` - from `false` to `'off'`
`editor.codeActionsOnSave.source.fixAll.eslint` - from `true` to `'explicit'`

**Comment by rzhao271** [comment]
These are setting migrations done as part of in-product setting value formats changing over time. I can understand that having to check in workspace setting file updates across multiple repositories is tedious, but the behaviour is intentional.

**Comment by lucasyvas** [comment]
That's a fine explanation at least - I'm curious why the `editor.codeActionsOnSave.source.fixAll.eslint` setting was changed because `true` is not deprecated. The other setting made more sense since it was deprecated. I'm not sure if that's intentional, but changing a non-deprecated value doesn't make a ton of sense to me.

**Comment by justschen** [comment]
@lucasyvas it's not deprecated because we specify that we want to give users time to adjust (there are some dev setups that would suffer if they were immediately deprecated, see https://github.com/microsoft/vscode/issues/200802).

**Comment by lucasyvas** [comment]
Thanks for the explanation @justschen. Now that I know it makes sense - for what it's worth, the behavior is a bit obtuse without the explanation.

**Comment by justschen** [comment]
@lucasyvas Understandable! I don't recall when I added in the warnings, but it should specify that they will get deprecated. Can definitely see where that can get missed tho 👍 

![Screenshot 2024-01-17 at 12 04 44 PM](https://github.com/microsoft/vscode/assets/54879025/2b2062c7-4960-439e-a1fe-736077911631)
![Screenshot 2024-01-17 at 12 03 54 PM](https://github.com/microsoft/vscode/assets/54879025/31b42401-11dd-4994-b92d-168ba302816e)
