### ISSUE TITLE
VSCode Render Crashes with Code 132 on boot with no settings  or extensions

### ISSUE THREAD

**Issue by addisonj** [microsoft/vscode#202548]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1 / code-1.85.1-1702462241.el7.x86_64
- OS Version: Linux 6.6.9 / bluefin 39 (https://projectbluefin.io/, a fedora silverblue based distro with code installed into the base system using the )

Steps to Reproduce:

1. No known initial cause, restarted vscode and started getting the error
2. Delete `~/.config/Code` and `~/.vscode` and have issue persist, first start has error 133, second crash is error 132

Attached is the `Crashpad` folder with crash dumps after a clean 
[Crashpad.zip](https://github.com/microsoft/vscode/files/13943680/Crashpad.zip)

A bit more context:

* Creating a new user on my computer and using the same system-level install of vscode *does* work
* The *only* think I can guess is that something I was doing with a chromium install? I am not sure how that would happen, but the issue does seem to have happened after I installed chromium inside a container (but sharing a system namespace)

**Comment by addisonj** [comment]
Also, just more of a meta comment... it is somewhat unfortunate to not be able to debug this further into electron due the use of private symbols. I am *guessing* the issue would be somewhat obvious if I could see the stack trace in electron, even if obfuscated, but I really don't see a way of doing that currently

**Comment by addisonj** [comment]
Additionally, I just installed the latest code-insiders as well and had the same issue

**Comment by addisonj** [comment]
One more data point... running `sudo code --no-sandbox --user-data-dir ~/code_root` *does* resolve the issue, but running `code --no-sandbox --user-data-dir ~/code_test` *does not* work and has the same error.

**Comment by deepak1556** [comment]
Can you provide the output of `code --verbose --user-data-dir ~/code_test`
