### ISSUE TITLE
Keep popping warnings

### ISSUE THREAD

**Issue by Pehfan** [Microsoft/vscode#20250]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|material-icon-theme|PKief|1.1.5|

---

Steps to Reproduce:

1.
2.

**Comment by Tyriar** [comment]
Please provide more information; what do the warnings say for example?

**Comment by Pehfan** [comment]
I have re-installed, and I've solved it, thank you .
