### ISSUE TITLE
Git checkout command order issue on search

### ISSUE THREAD

**Issue by eldair** [microsoft/vscode#202579]
Type: <b>Bug</b>

When using git checkout command via commands menu and type branch name it is no longer highlighted or first item. Instead, first item is always create new branch which is not how it was before, and it makes it impossible to quickly change branches without using arrows to select found branch.

This issue was not present yesterday, so I guess it is in the latest insiders version only.

![image](https://github.com/microsoft/vscode/assets/470003/0b5f3c77-4a9e-459e-8765-cec302e4a815)

VS Code version: Code - Insiders 1.86.0-insider (2c8f29174a63b3ace3d00ad0028cdc7ed9853b8b, 2024-01-16T05:35:26.709Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.4.2
color-info|bie|0.7.2
catppuccin-vsc|Cat|3.11.0
file-icons|fil|1.1.0
auto-close-tag|for|0.5.15
dotenv|mik|1.0.1
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
remote-explorer|ms-|0.4.1
ayu|tea|1.0.5
vscode-icons|vsc|12.7.0
JavaScriptSnippets|xab|1.8.0
vscode-sql-formatter|adp|1.4.4
Bookmarks|ale|13.4.2
laravel-extra-intellisense|ami|0.6.4
vscode-intelephense-client|bme|1.10.2
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
vscode-eslint|dba|2.4.2
gitlens|eam|14.6.1
json-tools|eri|1.0.2
prettier-vscode|esb|10.1.0
vscode-github-actions|git|0.26.2
todo-tree|Gru|0.0.226
autofilename|Jer|0.1.3
svg|joc|1.5.3
rainbow-csv|mec|3.11.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.28.0
laravel-blade|one|1.34.0
open-html-in-browser|pea|2.1.10
synthwave-vscode|Rob|0.1.15
theme-check-vscode|Sho|1.15.1
vscode-fileutils|sle|3.10.3
vscode-stylelint|sty|1.3.0
sort-lines|Tyr|1.11.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
volar|Vue|1.8.27
vscode-typescript-vue-plugin|Vue|1.8.27
change-case|wma|1.0.0

(4 theme extensions excluded)

</details>

**Comment by lszomoru** [comment]
@eldair, thanks for reporting this issue. 
This has already been fixed and the fix will be included in tomorrow's Insiders release.

**Comment by eldair** [comment]
> @eldair, thanks for reporting this issue. This has already been fixed and the fix will be included in tomorrow's Insiders release.

Great to hear! Thanks a lot
