### ISSUE TITLE
The auto update feature doesn't work on mac OS

### ISSUE THREAD

**Issue by jtourlamain** [Microsoft/vscode#20259]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-gist|dbankier|0.5.2|
|vscode-auto-open-markdown-preview|hnw|0.0.3|
|prettify-json|mohsen1|0.0.3|
|PowerShell|ms-vscode|0.7.2|
|csharp|ms-vscode|1.5.3|

---

Steps to Reproduce:

1. Download a verion of VSCode
2. Install it in /Applications/Tools
3. Open/use VSCode as non root
4. If an update comes out, click update.
5. VSCode restarts but the program wasn't updated.

**Comment by joaomoreno** [comment]
Can you check out my [comment in here](https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150)?
