### ISSUE TITLE
npm extension: package manager incorrectly detected as "yarn" in workspace with central package-lock.json

### ISSUE THREAD

**Issue by Thristhart** [microsoft/vscode#202551]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Windows 11

## Steps to Reproduce:

1. Open a workspace containing folders that are part of an npm workspace, where there is a package-lock.json in the root and not in the individual package folders
  This repo contains a workspace of this sort: https://github.com/Thristhart/vscode-package-manager-detection-repro
2. Open the "NPM Scripts" sidebar view and right-click on a package
3. Invoke "Run Install"

## Expected behavior:
`npm install` is run

## Observed behavior:
`yarn install` is run

## Notes:
This is because of the logic in [findPreferredPM](https://github.com/microsoft/vscode/blob/c7ea84b4f5e779a98e93bd1f48502d83403f16c3/extensions/npm/src/preferred-pm.ts#L67) where a package-lock.json in the project directory is taken as a sign of preferring npm, but the workspace root is not considered. The yarn detection however does check the workspace root, and that wins out.

**Comment by meganrogge** [comment]
I believe changing `npm.packageManager` will fix this.

**Comment by Thristhart** [comment]
@meganrogge It is true that setting `npm.packageManager` works around the bug, but I think incorrect autodetection in a relatively common setup is still worth fixing.
