### ISSUE TITLE
Can not saving edited file using remote-ssh connection

### ISSUE THREAD

**Issue by peiliu0408** [microsoft/vscode#202576]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:  1.85.1
- OS Version: win10

Environment: VSCode version: 1.85.1, Remote-SSH version: v0.108.2023112915, connected via LAN, login as root.
Issue Description: The edited text on the remote side cannot be saved. When closing the VSCode program, a window pops up:
"Closing the window is taking a bit longer. The following operations are still running:
saving text files"

supplements:
1). If the window is force closed, the connection cannot be established through Remote-SSH next time. 
2). After deleting the ./vscode/.0***.log file, normal login can be resumed.
3). an extension called  [save as root](https://marketplace.visualstudio.com/items?itemName=yy0931.save-as-root). Using this plugin, the edited remote file can be saved using the following these steps: i) Press F1,  ii) enter save-as-root, iii) then press the Enter key (you can also set a shortcut for save-as-root). This is inconvenient, and the plugin cannot save multiple modified files at the same time; you need to perform the above steps for each text file.
4). Pycharm can edit and save the edited files normally.
5). except remote-ssh, all other extensions are uninstalled.

Initial Analysis: 
1). File permission issue. Changing the text permissions to 777 did not resolve the problem.   -- failed
2). change the setting of remote-ssh extension . -- failed

![tempImagegOLS1e](https://github.com/microsoft/vscode/assets/18061950/046755c5-b6bf-406f-b4eb-1a381c007f22)

if "close anyway", the log file: 
![tempImageWNBTji](https://github.com/microsoft/vscode/assets/18061950/583b2aa8-1615-4a02-8af2-fb4481b9d47f)

**Comment by bpasero** [comment]
Is the scenario here to save a file that you have insufficient permissions to save via Remote-SSH? In other words, you need sudo permissions to save said file? 

We do not today support this scenario, at least not as we do locally where we can elevate VS Code after showing UAC prompt.
