### ISSUE TITLE
losing new breakpoints and current launch-configs on auto updating VS Code

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2025]
Whenever I auto update VS Code, newly selected launch config or newly created breakpoints are lost.

**Comment by isidorn** [comment]
This is a workbench bug that on shutdown is not being called when we update. We do not persist anything not just breakpoint

**Comment by bpasero** [comment]
Dupe

**Comment by weinand** [comment]
duplicate of https://github.com/Microsoft/vscode/issues/172
