### ISSUE TITLE
Deprecate the `--unity-launch` flag

### ISSUE THREAD

**Issue by ThatOneCalculator** [microsoft/vscode#202545]
Reup of #40986

`--unity-launch` appears in the Linux desktop file and is currently undocumented. The flags acts as an alias to `--new-window`, forcing a new window to be spawned when opening files.

refs:
https://github.com/microsoft/vscode/blob/c7ea84b4f5e779a98e93bd1f48502d83403f16c3/src/vs/platform/launch/electron-main/launchMainService.ts#L150-L152
https://github.com/microsoft/vscode/blob/c7ea84b4f5e779a98e93bd1f48502d83403f16c3/src/vs/code/electron-main/app.ts#L1352

https://www.reddit.com/r/linuxquestions/comments/s4hvdv/comment/hsruzir/

**Comment by Tyriar** [comment]
It was added to make things work a little nicer under unity, I think specifically shift+click opening a new window (but it was a long time ago I added it). It's slightly different to `--new-window` and I suspect we don't probably don't need it anymore so I don't think we should document it. When we remove it'll need some verification to make sure there aren't any bad regressions.

**Comment by ThatOneCalculator** [comment]
Awesome, thanks for the clarification! Guessing the `.desktop` file will use `--new-window` then from now on.

**Comment by Firestar-Reimu** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/code.desktop?h=visual-studio-code-bin

the --unity-launch leads to tiny cursors on HiDPI settings.

See https://github.com/microsoft/vscode/issues/136390#issuecomment-2020292160

The fastest fix is to delete the `--unity-launch` option, just `/usr/bin/code` is fine.
