### ISSUE TITLE
SCM view shows a shadow

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#202529]
* todays insiders (81725794264e4c0fddbc1b3b728013744ae90840)
* the SCM view shows a shadow above the input box

<img width="404" alt="Screenshot 2024-01-15 at 17 46 21" src="https://github.com/microsoft/vscode/assets/1794099/9f327115-f182-4909-b74a-f8bffb367ffa">

**Comment by jrieken** [comment]
DOM hints towards tree sticky scroll

<img width="1293" alt="Screenshot 2024-01-15 at 17 51 34" src="https://github.com/microsoft/vscode/assets/1794099/c43dd575-be3b-4990-9d5b-c83fdbc922f8">

**Comment by lszomoru** [comment]
@benibenj, could you please take a look? Thanks!

**Comment by benibenj** [comment]
The sticky scroll shadow was not being removed anymore since my latest changes, fixed it here: https://github.com/microsoft/vscode/pull/202490
