### ISSUE TITLE
vscode stops letting me insert new text

### ISSUE THREAD

**Issue by ChrisJefferson** [microsoft/vscode#202570]
Type: <b>Bug</b>

Once every 2 or 3 days, vscode will stop letting me type new text -- I can still move around the editor, open other files, press the 'delete' key to delete text, but I cannot insert any new characters. Closing and reopening vscode fixes the problem.

I can believe an extension is causing this problem, but as it takes so long to appear it would take a long time to bisect. Is there any way to find out what is "eating" my keyboard input?

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (7.42GB free)|
|Process Argv|--file-uri=vscode-remote://wsl+Ubuntu/home/caj/temp/test.essence --remote=wsl+Ubuntu --crash-reporter-id f8ccd3fb-6372-4e69-b184-ce8d81cb5c86|
|Screen Reader|no|
|VM|25%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900HX (32 x 2419)|
|Memory (System)|15.49GB (10.33GB free)|
|VM|0%|
</details><details><summary>Extensions (108)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
essence|bil|0.9.1
minizinc|Dek|0.1.1
essence-language|ess|0.0.4
vscode-firefox-debug|fir|2.9.10
gap|gap|0.0.3
vsc-python-indent|Kev|1.18.0
autoconf|mae|0.2.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
windows-ai-studio|ms-|0.2.3
errorlens|use|3.16.0
jinja|who|0.0.8
pascal|ale|9.6.0
pascal-formatter|ale|2.8.1
project-manager|ale|12.7.0
vscode-django|bat|1.15.0
essence|bil|0.9.1
vscode-innosetup|cho|1.9.2
gitignore|cod|0.9.0
minizinc|Dek|0.1.1
vscode-deno|den|3.31.0
git-extension-pack|don|0.1.3
githistory|don|0.6.20
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
overtype|DrM|0.5.0
vscode-wasm|dts|1.4.1
gitlens|eam|14.6.1
vscode-html-css|ecm|2.0.6
prettier-vscode|esb|10.1.0
essence-language|ess|0.0.4
foam-vscode|foa|0.25.6
gap|gap|0.0.3
copilot|Git|1.149.0
copilot-chat|Git|0.11.1
vscode-pull-request-github|Git|0.78.1
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.25.1
innosetup|idl|1.6.1
vscode-ansi|ili|1.1.6
latex-workshop|Jam|9.18.0
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
vsc-python-indent|Kev|1.18.0
vscode-markdown-notes|kor|0.0.27
restructuredtext|lex|189.3.0
vscode-python-test-adapter|lit|0.8.1
autoconf|mae|0.2.0
rainbow-csv|mec|3.11.0
vscode-docker|ms-|1.28.0
csharp|ms-|2.15.30
vscode-dotnet-runtime|ms-|2.0.0
black-formatter|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.8.22
test-adapter-converter|ms-|0.1.9
vsliveshare|ms-|1.0.5905
vscode-paste-image|mus|1.0.4
gradle-language|nac|0.2.3
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
quarto|qua|1.110.1
java|red|1.26.0
vscode-commons|red|0.0.6
vscode-xml|red|0.26.1
r|REd|2.8.2
vscode-gradle-extension-pack|ric|0.0.4
rust-analyzer|rus|0.3.1807
partial-diff|ryu|1.4.3
crates|ser|0.6.5
code-spell-checker|str|3.0.1
lua|sum|3.7.4
markdown-links|tch|0.8.0
html-preview-vscode|tht|0.2.5
simple-rst|tro|1.5.4
cmake|twx|0.0.17
errorlens|use|3.16.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.13.5
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.43.0
volar|Vue|1.8.27
jinja|who|0.0.8
FilterText|yhi|0.0.15
markdown-all-in-one|yzh|3.6.2
vscode-open-in-github|ziy|1.3.6

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30933248
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019acf:30933242

```

</details>

**Comment by IllusionMH** [comment]
You can check https://github.com/microsoft/vscode/wiki/Keybinding-Issues for steps related to keyboard issues troubleshooting.

Does it happen only with working on remote hosts or for local-only development as well?

**Comment by ChrisJefferson** [comment]
This bug disappeared and I can't reproduce it any more
