### ISSUE TITLE
Mouse wheel scrolling does not scroll the notebook while mouse is over Markdown or Output cell

### ISSUE THREAD

**Issue by Daniel-Wedemeyer** [microsoft/vscode#202598]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

As of the newest VSCode Insiders Update (Version: 1.86.0-insider Commit: 81725794264e4c0fddbc1b3b728013744ae90840), scrolling the mouse wheel while the mouse is over a Markdown or Output cell does not scroll the notebook. You have to mouse over code cells to be able to scroll. Scrolling by hovering at the left side next to the cells or over the scroll bar works fine.

### VS Code Version

Version: 1.86.0-insider Commit: 81725794264e4c0fddbc1b3b728013744ae90840

### Jupyter Extension Version

v2024.1.2024011501

### Jupyter logs

```shell
no relevant output.
```

### Running Jupyter locally or remotely?

Local

**Comment by rebornix** [comment]
Thanks for reporting this. It's a recent regression from https://github.com/microsoft/vscode/commit/4f338c87ab68833847df18ddcb8a5f5d7ee667fc#diff-c782cacbe379d1a57c8e6490a813998561065c89f9c39662ef7a8b544a69e8fcL485, I pushed a fix now.
