### ISSUE TITLE
addSelectionToNextFindMatch doesn't work with multiple cursors

### ISSUE THREAD

**Issue by wildeyes** [Microsoft/vscode#20256]
- VSCode Version: 1.9.0
- OS Version: Windows 10

Steps to Reproduce:

1. Have three rows with a string in them.
2. hold alt, click before the first character of every word.
3. activate addSelectionToNextFindMatch, I have sublime-keymap, so that's ctrl+d for me.
4. only the last word will be selected.

**Comment by alexandrudima** [comment]
Since a few releases, this works as expected.
