### ISSUE TITLE
Copy Selection Not Saved

### ISSUE THREAD

**Issue by GeorgSteyn** [Microsoft/vscode#20269]
- VSCode Version: 1.9.1
- OS Version: Ubuntu 16.04

I am trying to copy the folder name and paste it into my code.

Steps to Reproduce:

1. In your Project File browser, Right-Click folder.
2. On Popup Menu, Left-Click "Rename"
3. Copy folder name with shortcut key, Ctrl + C
4. On your code editor side, SELECT any piece of code with mouse drag. (Do not click with mouse in code editor first. MUST do SELECTION from beggining.)
5. Then Paste Ctrl + V.

Nothing happens. I expect VSCode to paste/replace the selected code.

**Comment by Tyriar** [comment]
The issue appears to be that the editor doesn't correctly get focus when going from renaming in the explorer to clicking on the editor. The focus appears to change but the cursor doesn't appear.

**Comment by rebornix** [comment]
Looked into the code and played with it for a while. Rename->Enter will set input to the editor again then the editor is focused. However if you Rename, do nothing on the tree (no keystrokes as well) and then select text in the editor, the focus goes to editor correctly, but when the Rename Input box gets cancelled, it re-focuses the file tree item and the editor loses focus.

You can verify this by adding `console.log('editor focus')` at https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorPart.ts#L499 and `console.log('editor blur')` at https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L462, then you can see `editor focus` -> `editor blur` in sequence. You can also reproduce this with Integrated Terminal: rename -> select text in terminal -> type/paste does nothing.

A proper fix is stop re-focusing the tree item if users already focus on other UI components, now it needs your insights of treeview/file explorer @bpasero @Tyriar
