### ISSUE TITLE
Build/Debug on server

### ISSUE THREAD

**Issue by Jackie-Yang** [Microsoft/vscode#20264]
How to Build/Debug C/C++ program on server using vscode

**Comment by Daylien** [comment]
VSCode has an offical C++ extension from Microsoft. You can find it [here](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools).
This extension supports debugging for Windows (PDB, Mingw/Cygwin), OS X and Linux applications.
You can build applications with an task runner in VSCode. See the documentation [here](https://code.visualstudio.com/Docs/editor/tasks) and [here](https://code.visualstudio.com/docs/languages/cpp) for C++.
