### ISSUE TITLE
Ubuntu 22.04: You're running in a GNOME environment but the OS keyring is not available for encryption. Ensure you have gnome-keyring or another libsecret compatible implementation installed and running.

### ISSUE THREAD

**Issue by xela-95** [microsoft/vscode#202652]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.1
- OS Version: Ubuntu 22.04.3 LTS

Every time I log in into VS CODE it prompts me to sign in to Github (both for extensions and for sync cloud changes). Once I signed in, vs code reports the error:

```
You're running in a GNOME environment but the OS keyring is not available for encryption. Ensure you have gnome-keyring or another libsecret compatible implementation installed and running.
```
I've already followed the troubleshooting guide [here](https://code.visualstudio.com/docs/editor/settings-sync#_linux) and tried to launch vscode with the `"password-store"` argument set either to `gnome` or `gnome-libsecret` without success.

One strange behavior is that once done the sign in and closed the error pop up, vs code says that settings sinc is on and does not complain anymore. But every time I reopen a new vscode instance it asks again for the sign in with the same errors.

**Comment by TylerLeonhardt** [comment]
How did you install vscode on this machine?

**Comment by xela-95** [comment]
I installed it through the Ubuntu Software application. 

I then tried to uninstall from it and install using the .deb file from Microsoft and it started working again.

I think that maybe it could be an issue with seahorse...

**Comment by TylerLeonhardt** [comment]
Does Ubuntu Software install it using flatpak perhaps? I have been seeing issues with that. I would have thought it would install as a snap, which AFAIK should work fine with Secret Storage... but anyway also glad you're unblocked.

**Comment by xela-95** [comment]
> Does Ubuntu Software install it using flatpak perhaps? I have been seeing issues with that. I would have thought it would install as a snap, which AFAIK should work fine with Secret Storage... but anyway also glad you're unblocked.

I installed it through a snap, don't know if maybe the issue arises from the secret storage and not vs code per se... I will close this issue for now and re open it if the error happens again. Thank you for the support :)
