### ISSUE TITLE
the editor freezes while running "npm install" in terminal panel

### ISSUE THREAD

**Issue by ivanstefanov** [Microsoft/vscode#20262]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|Bookmarks|alefragnani|0.10.2|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|githistory|donjayamanne|0.1.5|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|gitlens|eamodio|2.0.2|
|vscode-html-css|ecmel|0.0.33|
|EditorConfig|EditorConfig|0.3.4|
|json-tools|eriklynd|1.0.2|
|auto-close-tag|formulahendry|0.3.9|
|auto-rename-tag|formulahendry|0.0.11|
|code-sync|golf1052|2.1.2|
|output-colorizer|IBM|0.0.10|
|vscode-tfs|ivangabriele|0.5.2|
|docthis|joelday|0.3.10|
|Angular2|johnpapa|1.0.2|
|typelens|kisstkondoros|1.4.1|
|Angular-BeastCode|Mikael|0.3.2|
|csharp|ms-vscode|1.6.2|
|typescript-javascript-grammar|ms-vscode|0.0.18|
|autotrim|NathanRidley|1.0.6|
|typescript-hero|rbbit|0.12.0|
|Spell|seanmcbreen|0.9.1|
|code-settings-sync|Shan|2.4.3|
|autoimport|steoates|1.2.2|
|code-spell-checker|streetsidesoftware|0.16.0|
|gitflow|vector-of-bool|1.0.0|
|gitblame|waderyan|1.3.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|vsc-angular-cli|web-dave|0.1.1|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1. Open terminal panel
2. The terminal should point to powershell.exe
3. run npm install
4. the editor goes into no responding state
5. after reopening again it loses the state of the previos opened windows

**Comment by Tyriar** [comment]
@ivanstefanov does this happen if you run it within cmd?

@daviwil have you experienced anything like this?

**Comment by daviwil** [comment]
Nah, I just ran `npm install` from PowerShell inside of VS Code's terminal UI and it completed successfully:

```
[daviwil/dsc-breakpoints +0 ~2 -0 !] C:\dev\vscode-powershell
> npm install

> PowerShell@0.9.6 postinstall C:\dev\vscode-powershell
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.7.0
Found minimal version that qualifies engine range: 1.7.1
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/1.7.1/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\vscode-powershell\node_modules\tar\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\vscode-powershell\node_modules\sshpk\package.json'

[daviwil/dsc-breakpoints +0 ~2 -0 !] C:\dev\vscode-powershell
>

```

**Comment by Tyriar** [comment]
There was a recent report of long running processes freezing VS Code after 30 seconds on Windows as well, might be related?

**Comment by ivanstefanov** [comment]
I couldn't reproduce the issue on my other PC, which was with SSD. and way more faster. It may be because of the issues @Tyriar  talked about before. Thank you for the fast response
