### ISSUE TITLE
tsserver.js is eating CPU (100%)

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#20260]
- VSCode Version: 1.9.1
- OS Version: macOS Sierra

Steps to Reproduce:

1. Open VS Code
2. Run `top -u`
3. Notice Code Helper is spiking to 80-100%

I ran the command `ps -eo pcpu,user,pid,command | grep Code` and this is the process spiking to 100%.

```
100.0 sam              37109 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry
```

// @bpasero @jrieken

**Comment by bpasero** [comment]
@SamVerschueren as usual we need a lot more details to understand why this happens.

**Comment by SamVerschueren** [comment]
It happened after the upgrade. I restarted my mac and it looks like it's ok now. If it happens again, what information can I provide to make this debuggable? I disabled all my extensions so it was a clean VS Code.

**Comment by jrieken** [comment]
Any chance you can share that project with us?

**Comment by fatty1380** [comment]
I've been tracking the same issue (also `tsserver`, same `ps aux | grep PROC_ID` results) for a few days now. I have a few interesting data points to share: 

* After quitting VSCode, and also when installing an upgrade, the high CPU process remains running, while another identical one spawns
* After a while (~5 minutes?), the process returns to a normal CPU rate (0-1%)
* I observed this behavior with VSCode in the background, after launching, then relaunching for update.

Additionally, I have observed a "Code Helper has quit unexpectedly" system modal after an hour or so of use - I'll keep track of my current process IDs to see if it is the `tsserver` processes that are quitting

```
cream:~ fatty$ ps aux | grep tsserver
fatty            18370  98.5  5.3  4043036 448640   ??  R    11:11AM   0:46.21 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry
fatty            17662  93.3  4.4  6466928 370412   ??  R    11:04AM   4:07.14 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry
fatty            18416   0.0  0.0  2459428   2044 s003  S+   11:12AM   0:00.01 grep tsserver
fatty            18371   0.0  0.4  3360196  32024   ??  S    11:11AM   0:04.15 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry
```

**Comment by maxcan** [comment]
I'm seeing this too. 

vs code 1.9.1
typescript 2.1.6
osx 10.12.2.

will try a restart

**Comment by mjbvz** [comment]
@SamVerschueren To helpplease try collecting a trace of the TypeScript Server when this occurs. Here's information on to do this using the TSS_LOG environment variable: https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29#logging

From a command line, run:

```
set TSS_LOG=-level verbose -file c:\tmp\tsserver.log
code 
```

Reproduce the problem in VSCode and then share the `c:\tmp\tsserver.log` file

Let me know if you have any questions about this.

Thanks

**Comment by mjbvz** [comment]
Closing as we need the logs investigate this. Log collection should be simplified by #22914 for VSCode 1.11 but please provide logs using the environment variable approach mentioned until then

**Comment by teterovic** [comment]
me and my coworker have the same issue. As soon as we type a single space in a .ts file the Code Helper goes crazy

`8664 100.0  9.3  4769000 1559904   ??  R    10:36PM   0:58.20 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry --cancellationPipeName /var/folders/3c/czwwfy150ns0kb3tcw5kcntm0000gn/T/vscode-tscancellation-abc31803ac049e820ccd.sock*`

`97.9        18584 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/teterovic/.vscode/extensions/Angular.ng-template-0.1.4/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/teterovic/.vscode/extensions/Angular.ng-template-0.1.4/server/server.js --node-ipc
`
i will get some debug info tomorrow

**Comment by mjbvz** [comment]
@teterovic Please open an new issue for this. Also please try collecting the TypeScript server logs. These logs contain detailed information about the time required to compute for each response:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VSCode
1. Reproduce the issue
1. Run the `Open TSServer log File` command and view the `tsserver.log` file

If you can share the ts log file I can take a look through them to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
