### ISSUE TITLE
Allow to mark unreachable code as excluded from code coverage

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#202656]
I have this code:

![Code_-_Insiders_1yuyeVji1B](https://github.com/microsoft/vscode/assets/2931520/139f70e3-8e22-490b-b9ae-3673639a5a2e)

```ts
// Make sure all ranges are valid
assertFn(() => {
	function validatePosition(pos: Position, lines: string[]): boolean {
		if (pos.lineNumber < 1 || pos.lineNumber > lines.length) { return false; }
		const line = lines[pos.lineNumber - 1];
		if (pos.column < 1 || pos.column > line.length + 1) { return false; }
		return true;
	}

	function validateRange(range: LineRange, lines: string[]): boolean {
		if (range.startLineNumber < 1 || range.startLineNumber > lines.length + 1) { return false; }
		if (range.endLineNumberExclusive < 1 || range.endLineNumberExclusive > lines.length + 1) { return false; }
		return true;
	}

	for (const c of changes) {
		if (!c.innerChanges) { return false; }
		for (const ic of c.innerChanges) {
			const valid = validatePosition(ic.modifiedRange.getStartPosition(), modifiedLines) && validatePosition(ic.modifiedRange.getEndPosition(), modifiedLines) &&
				validatePosition(ic.originalRange.getStartPosition(), originalLines) && validatePosition(ic.originalRange.getEndPosition(), originalLines);
			if (!valid) { return false; }
		}
		if (!validateRange(c.modified, modifiedLines) || !validateRange(c.original, originalLines)) {
			return false;
		}
	}
	return true;
});
```

`range.startLineNumber < 1 || range.startLineNumber > lines.length + 1` should never happen, thus code coverage marks it as red.
However, when using code coverage as signal of how well the code is tested, this is causing a false positive.

Is there a way to tell the code coverage system that this is okay? Basically to exclude it from coverage?

I like how sqlite solved this in [7.2. Coverage testing of defensive code](https://www.sqlite.org/testing.html), by introducing `ALWAYS`.
[This is also an interesting read](https://www.sqlite.org/assert.html).

**Comment by connor4312** [comment]
We use istanbul for coverage, and they have comments you can use for this: https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md

I think this should be left up to coverage tools / extensions to do rather than something in VS Code, since we don't know how to interpret the grammar of arbitrary languages (what would 'ignore the next statement' mean?)
