### ISSUE TITLE
Tab Key stop working with last update

### ISSUE THREAD

**Issue by daniel-lahoz** [Microsoft/vscode#20268]
- VSCode Version: Code - Insiders 1.10.0-insider (d86968a1c5a6c15464cfe279fde1573514e70f15, 2017-02-09T07:04:56.461Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-css-class-completion|Zignd|1.0.3|
|html-snippets|abusaidm|0.0.18|
|vscode-caniuse|agauniyal|0.4.0|
|vscode-color|anseki|0.2.3|
|path-intellisense|christian-kohler|1.2.0|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.1|
|vscode-gutter-preview|kisstkondoros|0.8.2|
|prettify-json|mohsen1|0.0.3|
|debugger-for-chrome|msjsdiag|2.5.2|
|vscode-icons|robertohuertasm|7.2.0|

---

Steps to Reproduce:

1. Update VSCode
2. Press Tab Key, nothing happens :(

**Comment by dwperrin** [comment]
Perhaps might be emmet related I have had this issue on last two insiders builds

Very temporary workaround I found as I am not using emmet is adding to my workplace settings 
"emmet.triggerExpansionOnTab": false  and forward tab started working again

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/20209
