### ISSUE TITLE
Code assist function when press enter key does't work well

### ISSUE THREAD

**Issue by coderfoobar** [Microsoft/vscode#20261]
- VSCode Version: 1.9.1
- OS Version: win10 

Steps to Reproduce:

1.  new a file
2.  input:  `asdf`    in the first line 
3.  input: `a`  in the second line , and `Press Enter key` to start a new line.

I only want to input `a` in the second line , but `asdf` would be input to the second line when `press enter key`  .

**Comment by jhasse** [comment]
Set
```
	"editor.acceptSuggestionOnEnter": false,
```
in your user settings.
