### ISSUE TITLE
Python debugger changes __file__

### ISSUE THREAD

**Issue by adusamr** [microsoft/vscode#202648]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.1
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Make launch.json be like
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "script.py",
            "cwd": "<the parent directory of srcipt.py>"
            "console": "integratedTerminal",
            "justMyCode": true,
        }
    ]
}
```
and script.py be
```
print(__file__)
```
2. When I run the script.py with debugger (by F5) the `__file__` is "script.py".
When I run the script.py without debugger (by ctrl-F5) the `__file__` is the absolute path of script.py.

According to https://stackoverflow.com/questions/7116889/is-module-file-attribute-absolute-or-relative, `__file__` should be absolute path, because my python version is 3.10.

Edit:
This happens when "program" of launch.json is relative path.
When "program" is absolute path, the launched script.py's `__file__` is absolute path, but if I call `subprocess.run(["python", "script2.py"])` in script.py, called script2.py's `__file__` becomes "script2.py"

**Comment by roblourens** [comment]
Please file this on the Python extension repo.
