### ISSUE TITLE
VSCode on Linux breaks help on other applications...

### ISSUE THREAD

**Issue by death2gods** [microsoft/vscode#202674]
Type: <b>Bug</b>

I installed VSCode because I joined a FIRST team; I use Linux for all my personal computing needs, and VSCode has a Linux version, so I put it in.  Now help for Beyond Compare loads VSCode, not help.  Because M$ seems to install inappropriately global URL handlers for every freaking little thing, I suspect it's done the same on Linux - installed a global URL handler that conflicts with other applications' URL use.  Don't really know, just know VSCode utterly destroyed all help functionally in a completely unrelated application.  That is squarely a M$ bug.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 5.4.0-166-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (8 x 2306)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.62GB (4.97GB free)|
|Process Argv|--open-url /usr/lib/beyondcompare/help/welcome.html --log trace --crash-reporter-id a748c385-18fa-4ecd-8f88-74ddfc97fd98|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
black-formatter|ms-|2023.7.13471009
isort|ms-|2023.11.13191009
python|ms-|2023.23.13481009
vscode-pylance|ms-|2023.12.100
cpptools|ms-|1.19.1
java|red|1.26.2023121408
vscode-java-debug|vsc|0.55.2023121302
vscode-java-dependency|vsc|0.23.2023120100
vscode-wpilib|wpi|2024.1.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30933247
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by IllusionMH** [comment]
How exactly did you install VS Code on that Linux machine and what scheme handler you think was affected?
