### ISSUE TITLE
Please provide a way to run `formatOnSave` before `codeActionsOnSave` or provide a code action that runs the default formatter.

### ISSUE THREAD

**Issue by virtuallyunknown** [microsoft/vscode#202699]
Consider the following configuration in `.vscode/settings.json`.

```json
{
    "[typescript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": [
        "source.fixAll.eslint",
    ]
}
```

With this configuration, I am using two different formatters:

1. eslint to apply certain stylistic formatting.
2. `vscode.typescript-language-features` (the built-in VSCode formatter).

The problem is that `editor.codeActionsOnSave` runs first, then `editor.formatOnSave` practically erases/undoes the formatting applied by the code actions (eslint in this case).

https://github.com/microsoft/vscode/assets/24871108/d559553e-125b-4a06-94ff-03ff9a251c6e

You can of course disable `editor.formatOnSave` completely, but then eslint would have to handle all the basic formatting for you, and that would introduce a whole other set of problems, not to mention that it's not a linter's job to do the heavy formatting work.

This issue has been going on for ages now, so my humble request is to provide the same functionality that `editor.formatOnSave` does, but as a code action. The good thing about code actions is that you can put them into an array, and they will execute in the specified order from first to last. I've seen people put the `editor.formatOnSave` as an item inside `editor.codeActionsOnSave`, while simultaneously disabling `editor.formatOnSave` on a root level, but I've tried that and the default formatter doesn't work that way.

```json
// default formatter doesn't run anymore
{
    "editor.formatOnSave": false,
    "editor.codeActionsOnSave": [
        "editor.formatOnSave",
        "source.fixAll.eslint",
    ]
}
```

If adding a code action to run the default formatter isn't possible, please provide another option to tweak their order of execution. It doesn't matter how, as long as it gets the job done.

Also, if someone know of any current workarounds for this problem, I would really appreciate it if you let me know, thanks!

---

- #105301 issue from 4 years ago with the exact same problem. Dead end.
- #67147 another recent issue on it, another dead end.
- #194861 yet another recent issue, but still no workarounds.

**Comment by GueganVictor** [comment]
up! having the same issue.
default formatter isn't triggered anymore when specifying codeActionsOnSave

**Comment by haoadoreorange** [comment]
FYI as a workaround, there's a plugin that does this...
https://marketplace.visualstudio.com/items?itemName=rohit-gohri.format-code-action

**Comment by Vector341** [comment]
Actually there are some similar issue: 
https://github.com/microsoft/vscode/issues/105301
https://github.com/microsoft/vscode/issues/88131

And the official plans to unify it: [Unifying "do X on save" functionality](https://github.com/microsoft/vscode/issues/67147)

**Comment by MARCROCK22** [comment]
any workaround?
