### ISSUE TITLE
Auto Detect Color Scheme. Failure under certain conditions

### ISSUE THREAD

**Issue by Gavoid123** [microsoft/vscode#202667]
Type: <b>Bug</b>

When I closed Visual Studio Code in light mode, switched the Windows system to dark mode and opened Visual Studio Code, I found that Visual Studio Code was still in light mode. While closing Visual Studio Code in dark mode, doing the opposite will not.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.11GB free)|
|Process Argv|--crash-reporter-id cf4d6e4b-e1df-4e34-ba7d-ea53995012fb --crash-reporter-id cf4d6e4b-e1df-4e34-ba7d-ea53995012fb --crash-reporter-id cf4d6e4b-e1df-4e34-ba7d-ea53995012fb|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30933248
9b8hh234:30694863
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019a:30933241

```

</details>

**Comment by Gavoider** [comment]
I have upgraded to the latest version and the problem still exists. I found that using the system theme worked fine, however when I used the extended theme I had problems

https://github.com/microsoft/vscode/assets/64102271/cdfecb90-6094-441c-a120-10c7bde8346b

**Comment by aeschli** [comment]
This got fixed in the meantime. If you have `window.autoDetectColorScheme` on, we will check the OS color scheme on startup and switch to whatever theme you have configured under `workbench.preferredDarkColorTheme` resp `workbench.preferredLightColorTheme`
