### ISSUE TITLE
Random exit (crush)

### ISSUE THREAD

**Issue by alexandis** [microsoft/vscode#202619]
I have encountered a random issue with Visual Studio Code that I cannot reproduce consistently.

I use multiple instances of Visual Studio Code to run Angular apps using webpack dev server. Sometimes, after working for several days, all the instances close unexpectedly without any user action. I have not noticed the exact moment when this happens (I just reveal they are not running anymore), but it is probably after unlocking the computer.

I want to find out the cause of this crash. Can I see some hint in a log file or use other diagnostic information?

P.S. Nothing found in Windows Event Viewer.

**Comment by rzhao271** [comment]
@alexandis I apologize for not getting back to you sooner.

Could you close all instances of VS Code and re-run them with crash logging enabled, following the instructions at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues?

Afterwards, if VS Code crashes again, you'll have a dump file that you can then send to us to symbolicate. With the symbolicated file, we'll be able to see the cause of the crash assuming it is on the Electron runtime level.

**Comment by alexandis** [comment]
@rzhao271  thank you for the recommendation, I will. But now it happens much more rarely, so the result won't be soon.
