### ISSUE TITLE
Git features not working well

### ISSUE THREAD

**Issue by mayank1513** [microsoft/vscode#202657]
Type: <b>Bug</b>

Initially Git used to show files staged and not staged, etc.

Now the UI is too complex. It shows number of commits, commit details, etc. but does not show the files. Its useless.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (4.37GB free)|
|Process Argv|--crash-reporter-id 58af0897-d6e5-4c03-81b0-522c1edb97fd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|2.5.0
vscode-bit|bit|1.0.18
css-theme-completions|con|0.0.5
vscode-eslint|dba|2.4.2
vitest-snippets|dei|1.7.1
gitlens|eam|14.6.1
prettier-vscode|esb|10.1.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.78.1
rest-client|hum|0.25.1
vscode-edit-csv|jan|0.8.3
svg|joc|1.5.3
kanban|lba|1.7.4
trello-kanban-task-board|may|0.5.0
vscode-kanban|mkl|1.33.2
csharp|ms-|2.15.30
dotnet-interactive-vscode|ms-|1.0.5063010
vscode-dotnet-runtime|ms-|2.0.0
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.81.8
vscode-js-profile-flame|ms-|1.0.8
prisma|Pri|5.8.1
java|red|1.26.0
vscode-xml|red|0.26.1
LiveServer|rit|5.7.9
svg-preview|Sim|2.8.3
vscode-mdx|uni|1.6.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.43.0
volar|Vue|1.8.27
vscode-typescript-vue-plugin|Vue|1.8.27
vscode-import-cost|wix|3.3.0
vitest-explorer|Zix|0.2.43

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30933248
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by lszomoru** [comment]
@mayank1513, thanks for the feedback. You might be hitting a known issue when it comes to files not being shown correctly in the Source Control view. Could you please try the latest VS Code Insiders release to see if you are still able to reproduce the problem?

As far as the information about incoming/outgoing changes, you can hide thee nodes using the following two settings: `scm.showIncomingChanges`, `scm.showOutgoingChanges`.

**Comment by gjsjohnmurray** [comment]
@mayank1513 please see this section of the 1.85 release notes for information about the new UI feature:

**Comment by mayank1513** [comment]
This feature may be good. But if it is replacing the old staging area view, it's very bad.

**Comment by gjsjohnmurray** [comment]
It isn't replacing the staging elements.

![image](https://github.com/microsoft/vscode/assets/6726799/7c1bba35-8f3c-48b7-8a8b-0f5a99672701)

**Comment by mayank1513** [comment]
The Staged Changes and Changes are no longer appearing in the treeview on my VSCode as well as on GitHub codespace

**Comment by lszomoru** [comment]
@mayank1513, could you please try the latest VS Code Insiders [release](https://code.visualstudio.com/insiders/)? Multiple issues have been fixed in this area and it would be great if you could confirm that the issue that you are running into is resolved. Thanks!

**Comment by mayank1513** [comment]
Ok this works good in the insider

**Comment by mayank1513** [comment]
Works in insider release. Awaiting general availibility.
