### ISSUE TITLE
the warning is not stop

### ISSUE THREAD

**Issue by screamsyk** [Microsoft/vscode#20273]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please provide some information about the problem you are seeing and some repo steps.

Thanks

**Comment by mjbvz** [comment]
Closing as not actionable without more info
