### ISSUE TITLE
VS Code Server stuck in download loop

### ISSUE THREAD

**Issue by kirwinrMK** [microsoft/vscode#202734]
Type: <b>Bug</b>

1. Connect over ssh to server that was working with vs code ssh remote development
2. Enter password
3. VS Code attempts to find active server and fails
4. VS Code installs server
5. VS Code attemtpts to find active server
6. Go back to step 2 

VS Code version: Code - Insiders 1.86.0-insider (0b571a26e213bf1ec6266e37152ced80c006bd1e, 2024-01-18T05:36:10.559Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux arm64 6.1.21-v8+
Connection to 'SSH: 10.0.125.51' could not be established  Connecting was canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (10.45GB free)|
|Process Argv|--crash-reporter-id 3532bc7e-f286-4c85-a792-bf6e4342bc07|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|mkm-telem-1|
|OS|Linux arm64 6.1.21-v8+|
|CPUs|Cortex-A72 (4 x 1500)|
|Memory (System)|7.63GB (5.11GB free)|
|VM|0%|

Connection to 'SSH: 10.0.125.51' could not be established  Connecting was canceled
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
vscrpc:30624061
pythongtdpath:30726887
welcomedialogc:30812479
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772

```

</details>

**Comment by kirwinrMK** [comment]
[1-Remote - SSH.log](https://github.com/microsoft/vscode/files/13978044/1-Remote.-.SSH.log)

**Comment by rainje** [comment]
I have the same issue, been like this for two or three days. Went back to stable. 

Also have this notification in vscode following the failure:

`Impossible d’ouvrir l’éditeur en raison d’une erreur inattendue : WrappedError(WrappedError { message: "error checking server integrity", original: "failed to run command \"/home/rain/.vscode-server-insiders/cli/servers/Insiders-0b571a26e213bf1ec6266e37152ced80c006bd1e.staging/server/bin/code-server-insiders --version\" (code 1): /home/rain/.vscode-server-insiders/cli/servers/Insiders-0b571a26e213bf1ec6266e37152ced80c006bd1e.staging/server/bin/helpers/check-requirements.sh: 35: ldconfig: not found\n" })`

**Comment by brentkearney** [comment]
Same here,  using VSCode-insiders for MacOS. The pop-up message is:
```
Failed to connect to the remote extension host server (Error: WrappedError(WrappedError { message: "error checking server integrity", original: "failed to run command \"/home/coder/.vscode-server-insiders/cli/servers/Insiders-0b571a26e213bf1ec6266e37152ced80c006bd1e.staging/server/bin/code-server-insiders --version\" (code 1): /home/coder/.vscode-server-insiders/cli/servers/Insiders-0b571a26e213bf1ec6266e37152ced80c006bd1e.staging/server/bin/helpers/check-requirements.sh: 35: ldconfig: not found\n" }))
```
The last message in the developer console is:
```
  ERR WrappedError(WrappedError { message: "error checking server integrity", original: "failed to run command \"/home/coder/.vscode-server-insiders/cli/servers/Insiders-0b571a26e213bf1ec6266e37152ced80c006bd1e.staging/server/bin/code-server-insiders --version\" (code 1): /home/coder/.vscode-server-insiders/cli/servers/Insiders-0b571a26e213bf1ec6266e37152ced80c006bd1e.staging/server/bin/helpers/check-requirements.sh: 35: ldconfig: not found\n" }): Error: WrappedError(WrappedError { message: "error checking server integrity", original: "failed to run command \"/home/coder/.vscode-server-insiders/cli/servers/Insiders-0b571a26e213bf1ec6266e37152ced80c006bd1e.staging/server/bin/code-server-insiders --version\" (code 1): /home/coder/.vscode-server-insiders/cli/servers/Insiders-0b571a26e213bf1ec6266e37152ced80c006bd1e.staging/server/bin/helpers/check-requirements.sh: 35: ldconfig: not found\n" })
	at Object.resolve (/Users/brent/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.108.2024011815/out/extension.js:2:294986)
	at /Users/brent/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.108.2024011815/out/extension.js:2:293691
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The remote server is:
```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

It's a strange error because from line 35 of that script (/home/coder/.vscode-server-insiders/cli/servers/Insiders-0b571a26e213bf1ec6266e37152ced80c006bd1e.staging/server/bin/helpers/check-requirements.sh) is:
```
elif [ -f /sbin/ldconfig ]; then
    # Look up path
    libstdcpp_paths=$(ldconfig -p | grep 'libstdc++.so.6')
```

And I can run that fine from the command line on that remote host:
```
$ ls -l /sbin/ldconfig
-rwxr-xr-x 1 root root 978784 Sep 30 08:31 /sbin/ldconfig

$ ldconfig -p | grep 'libstdc++.so.6'
	libstdc++.so.6 (libc6,x86-64) => /lib/x86_64-linux-gnu/libstdc++.so.6
```

I can also run the command from the logs that fails:
```
$ /home/coder/.vscode-server-insiders/cli/servers/Insiders-0b571a26e213bf1ec6266e37152ced80c006bd1e.staging/server/bin/code-server-insiders --version
1.86.0-insider
0b571a26e213bf1ec6266e37152ced80c006bd1e
x64
```

So I wonder if it is actually making the SSH connection on the remote server.

I tried uninstalling and reinstalling the Remote-SSH extension, pre-release version, and got the same results. I tried switching  from the pre-release version, same results.

Scrolling up in the developer console, I see a deprecation warning/error:
<img width="555" alt="vscode-deprecation" src="https://github.com/microsoft/vscode/assets/1550934/a8212fc5-c038-4716-abb4-e5840f1891a6">

**Comment by connor4312** [comment]
Addressed in https://github.com/microsoft/vscode/pull/202645
