### ISSUE TITLE
API: Contributable icons

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#20271]
Currently icons from extensions seem to come in via:

- `ThemableDecorationAttachmentRenderOptions.contentIconPath: Uri`
- `ThemableDecorationRenderOptions.gutterIconPath: Uri`
- `DecorationRenderOptions.gutterIconPath: Uri`
- Status bar `$(octicon)` style icons.

The first three are extensible at will. The status bar icons are currently restricted to Octicons.

It would be awesome to have a contribution story here. This could even solve #4201, if we move the completion item icons to this mechanism, by having the default icons be contributed in the same way.

**Proposal**

Introduce a `contributes.icons` section:

```json
"icons": [
  {
    "name": "foo",
    "path": "path/to/svg/or/png",
    "dark": {
      "path": "optional/path/to/dark/svg/or/png"
    }
  }
]
```

**Comment by jrieken** [comment]
close this as a dupe https://github.com/Microsoft/vscode/issues/10455. We should explore to use icon themes for this. They already define a symbolic-name for icons, like octicons, which then can reference is strings etc
