### ISSUE TITLE
Intellisense gives me autocomplete every time, and I can't disable or ignore it.

### ISSUE THREAD

**Issue by AAABingBing** [microsoft/vscode#202793]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.2 (user setup)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

I made a simple gif example.

![PixPin_2024-01-19_10-16-21](https://github.com/microsoft/vscode/assets/53040248/7edd198e-6bae-48bf-a577-62c03126b0e9)

When I wanted to type `co.` or `co()` intellisense automatically completes me as `const.` or `const()`, but I just want to type `co.` or `co()`

**Comment by jrieken** [comment]
The setting is `editor.acceptSuggestionOnCommitCharacter` but it looks like something is off with JS/TS that it has this enabled even for keywords

**Comment by AAABingBing** [comment]
> The setting is `editor.acceptSuggestionOnCommitCharacter` but it looks like something is off with JS/TS that it has this enabled even for keywords

Thank you for your reply.
Problem solved perfectly!
