### ISSUE TITLE
add `Suggest Terminal Command` hint 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#202764]
To improve discoverability of this feature, we should have a hint like the one in the editor:

![Screenshot 2024-01-18 at 11 49 11 AM](https://github.com/microsoft/vscode/assets/29464607/ad2cb22d-d951-4779-9310-dbbe487183b6)

This will allow us to get feedback before we consider using an inline widget in the future.

cc @tyriar, @bpasero

**Comment by meganrogge** [comment]
with this added, we should include this hint in the terminal accessibility help dialog so SR users know about it

**Comment by isidorn** [comment]
My suggestion is to not yet look into this, until we finalise the design of the terminal suggest hint.
I am not sure how to visually represent it without it being too noisy

**Comment by meganrogge** [comment]
Closing due to feedback that this is too noisy
