### ISSUE TITLE
Pass a chat session ID to chat agents

### ISSUE THREAD

**Issue by stepro** [microsoft/vscode#202779]
VS Code allows users to maintain multiple chat sessions. We have an agent that wants to track some internal session state. Currently when the agent is called, we don't know which session it was for. Aside from parsing/hashing the chat history, we don't have any way to identify which session it is and map to our internal session state.

The specific suggestion might be to add some kind of opaque session ID value to the ChatAgentContext interface.

@isidorn

**Comment by roblourens** [comment]
We need to do this, but VS Code should be in charge of the actual data so that it can be cleaned up properly when you delete a session, exported with the rest of the session data, etc.

**Comment by roblourens** [comment]
This should now be possible for extensions to implement- you can attach your own session ID to the Result object (and search your Results in history to check whether a session ID has already been assigned, or initialize it)

**Comment by roblourens** [comment]
This is probably covered by the TPI and I have implemented it as well
