### ISSUE TITLE
Add ability to unsplit editors of 2 editor groups

### ISSUE THREAD

**Issue by wildeyes** [Microsoft/vscode#20279]
Please add the ability to close a split.

**Comment by Tyriar** [comment]
There is a "Close all editors in group" command (`workbench.action.closeEditorsInGroup`) which does this. Default keybinding is ctrl+k, w on Ubuntu.

**Comment by wildeyes** [comment]
I was going for something else, a command that joins the current group's
editors with the previous group, like is done in other editors.

**Comment by bpasero** [comment]
Happy for a PR if someone wants to provide such a command.

**Comment by bpasero** [comment]
Verify: 
* with this new command "Join Editors" you can bring all editors from one group into the group to the left
* test with different editors, not just files (e.g. markdown preview, diff editors)

**Comment by etiennejcharles** [comment]
@jrieken : Is it only me or my intuition was to look for "Unsplit Editor" (been looking for this feature for a month at least now)!
