### ISSUE TITLE
`terminal.integrated.shell.windows` in project .vscode/settings is not respected

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#20276]
- VSCode Version: 1.10.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Add `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"` in `.vcode/settings.json`
2. Terminal still powershell.

**Comment by Tyriar** [comment]
Hmm, haven't had any reports like this, are you sure your settings file was saved and there weren't any workspace settings or something overriding it?

**Comment by whitecolor** [comment]
This is a screen, of course it is saved.
![image](https://cloud.githubusercontent.com/assets/736697/22815442/6eb066fc-ef7d-11e6-9b46-ab11d2386bec.png)

**Comment by Tyriar** [comment]
Oh, this was intentional due to a possible security problem. See post-release discussion here https://github.com/Microsoft/vscode/issues/19758
