### ISSUE TITLE
Unable to start debugging. unable to establish a connection to GDB debug output may contain more information. 

### ISSUE THREAD

**Issue by nullcoder153** [microsoft/vscode#202770]
Unable to start debugging. unable to establish a connection to GDB debug output may contain more information. Anyone help me? 
![Screenshot 2024-01-19 022011](https://github.com/microsoft/vscode/assets/157065440/51b68ec1-4300-40fc-98bc-8ebd23c0884d)

**Comment by roblourens** [comment]
Please file on the extension that you're using to debug
