### ISSUE TITLE
Dark Modern theme -> functions are not colored in .rb files

### ISSUE THREAD

**Issue by rfiedorowicz** [microsoft/vscode#202716]
Type: <b>Bug</b>

Yesterday it was fine, but today I lost my colors for ruby code.

in the example.rb
For example word 'round' was colored in the line:
     value = value.round(6)
and today it is full white (without number)

Could I ask to back to previous Dark Modern theme (or give new theme with old settings)

![image](https://github.com/microsoft/vscode/assets/16592902/caaa0c8e-0d14-468f-ad58-1e6a55980fe1)

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700X 8-Core Processor              (16 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|47.90GB (36.46GB free)|
|Process Argv|--crash-reporter-id fe2b1d57-4822-4243-a441-0127bbc9ef45|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
copy-path|Eti|0.0.2
rainbow-csv|mec|3.11.0
language-gettext|mro|0.2.2
autopep8|ms-|2023.8.0
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
vscode-thunder-client|ran|2.17.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
0bi6i642:30933247
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by aeschli** [comment]
There hasn't been any updates on the Dark Modern nor the ruby theme in the last 3 month

Can it be that you had a ruby extension installed that added semantic highlighting?

I tested with the code
```
def dohash()
    value = value.round(6)
```

and also in 1.84 there's no color on `round`


Can you also provide a full example? In which version do you see the color?

**Comment by rfiedorowicz** [comment]
oh!
Sorry very much for this issue ;/

I always though that it colors were from standard visual studio code.

It was probably because of my 'Ruby LSP' plugin. They had 2 new version on this week.
![image](https://github.com/microsoft/vscode/assets/16592902/9cfde391-8fa0-41b7-a9be-d44c89b5839a)

Now it is working correctly, so they fixed it.

![image](https://github.com/microsoft/vscode/assets/16592902/f905fdd3-dfb0-4552-9093-608bf519aa84)

Closing
