### ISSUE TITLE
Terminal powershell shows an error after opening the terminal

### ISSUE THREAD

**Issue by abhijit-chikane** [microsoft/vscode#202704]
- VS Code Version: 1.86 insider
- OS Version: Windows 11

Steps to Reproduce:

1. Open the powershell terminal in vscode insdider and it shows below error

![image](https://github.com/microsoft/vscode/assets/50770619/912a1c47-1442-473d-a5f5-6240b3cc46da)

script look like this
```if ($env:TERM_PROGRAM -eq "vscode") { . "$(code --locate-shell-integration-path pwsh)" }```

**Comment by meganrogge** [comment]
it looks like you've manually installed shell integration? you can read about that here and removing that will fix your issue. https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation
