### ISSUE TITLE
L and H need to respect Cursor Surrounding Lines

### ISSUE THREAD

**Issue by mrthebob** [microsoft/vscode#202752]
For the purposes of scrolling (via j/k), Cursor Surrounding Lines seems to be respected. But when jumping to the top or bottom via L / H, the scrolloff (Cursor Surrounding Lines) is not respected, and the cursor goes all the way to the top or bottom.

It would be great if this were addressed, so that by pressing L, the cursor is placed X lines above the bottom of the window, based on the scrolloff/Cursor Surrounding Lines.

**Comment by IllusionMH** [comment]
Is this related to Vim extension?

**Comment by mrthebob** [comment]
Yeesh - it totally is. I was looking at a vim extension but ended up here. Sorry - feel free to close.
