### ISSUE TITLE
Arguments not used when in debug mode and press restart from the debug task bar

### ISSUE THREAD

**Issue by Zumbala** [Microsoft/vscode#20278]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|jslint|ajhyndman|1.2.1|
|vscode-npm|fknop|3.3.0|
|beautify|HookyQR|0.7.3|
|prettify-json|mohsen1|0.0.3|
|pegjs|none|0.0.1|
|pegjs-language|SirTobi|0.1.0|
|addDocComments|stevencl|0.0.8|

---

Steps to Reproduce:

1. run program in debug mode (Launch Program mode)
2. goto launch.json and change arguments "args" to something else
3. press restart from debug mode
4. check arguments, still the same as before change.
5. press stop debug mode
6. run programm again in debug mode, arguments changed

sample launch.json configuration: [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "args" : [
                 "order.json.csv",
                 "order.eid"
            ]
        }, .....
]

**Comment by rob5408** [comment]
+1 on this one. Restart doesn't take into account any changes you've made in `launch.json`. This is possibly by design, but definitely different behavior than before 1.9.

**Comment by weinand** [comment]
Yes, this is a known issue.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/19366
