### ISSUE TITLE
Open terminal link in Incognito window

### ISSUE THREAD

**Issue by johnlewisdt** [microsoft/vscode#202717]
When cmd-click or ctrl-clicking a link from the terminal window, this opens in a standard window. A significant amount of times I need this to open an incognito window, for instance, when testing a password protected page. Example: I am editing a Shopify password page and it's quite painful as it logs me in instantly. A second link that allows incognito, with say option-click/alt-click, would be ideal.

The tooltip link doesn't allow you to copy - it disappears before you get a chance. Highlighting it and copying does not add it to the clipboard if you are quick enough. The text-based link goes over 2 lines in most cases, particularly when splitting terminals (see screenshot), so is broken up with || in the middle, forcing you to edit the link before you can use it. 

I have seen this come and go in 2020 on issue [#65136](https://github.com/microsoft/vscode/issues/65136), but it's a big productivity issue for me right now. So I thought I should resurrect it.

<img width="576" alt="Screenshot 2024-01-18 at 11 21 53" src="https://github.com/microsoft/vscode/assets/74916430/0e9b3365-8568-4a9c-bef2-9676fa899322">

**Comment by Tyriar** [comment]
This sort of thing would only be possible after https://github.com/microsoft/vscode/issues/216853 is done. So closing this out of scope but you might want to sub to that one.

In the meantime note you should be able to double click (or double click and drag) to quickly copy a link
