### ISSUE TITLE
Suggest widget stalls typing

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2027]
* open viewLine.ts
* after the first interface in the file type as fast as you can
* `class HorizontalRange implements EditorBrowser.IHorizontalRange `

Please observe the 153ms stall due to `onDidSuggest` > `refresh`

![image](https://cloud.githubusercontent.com/assets/5047891/12331073/46dddcce-bae8-11e5-8ad5-d174b972478f.png)

**Comment by joaomoreno** [comment]
Duplicate of #1923. For some reason, something changed here.
