### ISSUE TITLE
Terminal speech: mic icon does not appear when no line above prompt

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#202707]
It seems that the mic icon requires at least one line above the prompt to show:

![image](https://github.com/microsoft/vscode/assets/900690/6d52eaff-aa47-4eff-997e-b5c47838e3be)

It does not appear for me in the above case.

**Comment by meganrogge** [comment]
Thanks for the issue. Should be an easy fix and in this case the mic will have to go on the cursor line
