### ISSUE TITLE
Cut (cmd+x) put new incorrect selection

### ISSUE THREAD

**Issue by iKBAHT** [Microsoft/vscode#20277]
VSCode Version: 1.9.1
OS Version: macOS 10.12.3

Steps to Reproduce:

- Select some text (https://habrastorage.org/files/74f/8b3/922/74f8b3922df145e9a389a0464ca30b7d.png)
- cmd+x
- Text is copied and cutted, but after formed some strange selection (https://habrastorage.org/files/857/7af/deb/8577afdeb72144aabfaff2c82be721a2.png)

Expected: selection became just cursor and stay on selection start position.
This bug didn't appears all time (about 1 of 10-15 attempts). It is old bug, I noticed it at september 2016.

**Comment by alexandrudima** [comment]
@iKBAHT I cannot reproduce this no matter how hard I try and I have never run into it. Do you perhaps have some more precise steps ?

**Comment by iKBAHT** [comment]
@alexandrudima I didn't catch this long time ago. I think you may close issue.
