### ISSUE TITLE
Handlebars Formatting

### ISSUE THREAD

**Issue by m-nagy** [Microsoft/vscode#20274]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vsc-ember-frost|ciena-blueplanet|0.0.2|
|gitlens|eamodio|2.0.2|
|vsc-ember-cli|felixrieseberg|0.3.2|
|EmberES6Snippets|phanitejakomaravolu|2.1.2|
|sass-indented|robinbentley|1.3.0|

---

Steps to Reproduce:
When writing many handlebars tags inline like the following
`{{title "abc"}}{{log "abc"}}`
VSCode formatter (Alt+Shift+F) adds all inline tags in the same line and no way to configure the editor to add each tag on a single line which is very annoying

**Comment by aeschli** [comment]
We use http://jsbeautifier.org/ as underlying formatter.
Please make requests for additional features directly at https://github.com/beautify-web/js-beautify
