### ISSUE TITLE
While renaming a file in explorer, arrow keys are navigating in the text box

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#20270]
See the following video. During rename, I am using the arrow keys and they are navigating behind in the treeexplorer

![kapture 2017-02-09 at 10 43 35](https://cloud.githubusercontent.com/assets/10746682/22777828/ca58d602-eeb4-11e6-9038-c15b060dd952.gif)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/20195
