### ISSUE TITLE
Mac Visual Studio Stays In Download Folder Unless Otherwise Moved

### ISSUE THREAD

**Issue by soup6** [microsoft/vscode#202751]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Download visual studio code for mac, on mac (issue on sonoma 14.2.1)
2. Run installation
3. Visual Studio is found in the Downloads folder, not Applications.

**Comment by joaomoreno** [comment]
This is how applications on macOS work. They can be anywhere. Please move it to the Applications folder if you'd like it there.
