### ISSUE TITLE
Hide errors in status bar from unsaved (dirty) files

### ISSUE THREAD

**Issue by GorvGoyl** [microsoft/vscode#202799]
As shown in the screenshot, status bar shows errors from unsaved (dirty) files, i.e. files I created using `cmd+T` to jot down some snippets but didn't save anywhere on my machine.  I'd like VSCode to filter out errors from such unsaved files.
![image](https://github.com/microsoft/vscode/assets/7106086/1daab426-7d99-45c9-8ab2-c986bcd44658)

**Comment by starball5** [comment]
I prompted you to think about how you would like this to work when there are multiple editor groups https://stackoverflow.com/a/77842891/11107541. Did you forget? Ex. should only problems from the active editor group's active editor be omitted from the count? Or also problems from active editors in inactive editor groups? Or are you suggesting that both of those options be available?

**Comment by sandy081** [comment]
Please file an issue against the extension generating these errors.

**Comment by starball5** [comment]
@sandy081 so is this an "out-of-scope"? The tags still indicate "triage"...

**Comment by sandy081** [comment]
I do not think this is tagged as out of scope. This is related to the extension generating these errors. Action is to file issue against that extension.
