### ISSUE TITLE
Show all unsaved files

### ISSUE THREAD

**Issue by shaedrich** [microsoft/vscode#202709]
When there's only one unsaved file, VSCode will show it in the dialogue:
![grafik](https://github.com/microsoft/vscode/assets/11225821/ff1b4244-be46-415d-8a52-9a0f8fbbe855)

But if there are more, there's just their amount:
![grafik](https://github.com/microsoft/vscode/assets/11225821/049cf8df-a834-40b7-ad1c-d95773e3423e)

I agree, that the available space in the dialogue is indeed limited and we would run into problems after a certain threshold is exceeded.

However, there could be a separate view that could be opened via the left-hand file explorer or a command.

Alternatively, these files could be pinned to the top of the explorer, similar to what is suggested in #27286

**Comment by gjsjohnmurray** [comment]
Does the extension https://marketplace.visualstudio.com/items?itemName=wraith13.unsaved-files-vscode help you?

**Comment by shaedrich** [comment]
Looks awesome! Thanks
