### ISSUE TITLE
Terminal Remame is not working

### ISSUE THREAD

**Issue by soninishank** [microsoft/vscode#202774]
In the previous versions of VS Code I was able to rename the terminal. But in the newer versions , the changes are not working. 

Steps to produce the issue: 
1. Open terminal 
2. [CMD+SHIFT+P] Move terminal into editor area
3. The terminal is a bash. Right Click on the terminal name[bash], rename it. Provide the new name
4. The changes will not get reflected.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by soninishank** [comment]
yes its working in the insider version
