### ISSUE TITLE
Test: Tree Sticky Scroll Support Focus & Keyboard Navigation

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#202835]
Refs: #199373

- [x] anyOS @eleanorjboyd
- [x] anyOS @lszomoru

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23202835%0A%0A&assignees=benibenj)

---

As part of this update we allow users to focus the items in tree sticky scroll and use the arrow keys to navigate the widget.

### What to test:
1. Test that all keys listed below behave in the expected way
2. When a sticky scroll element has focus and the users scrolls the list with the mouse wheel, focus stays in the sticky scroll widget until there is no item left. In that case the focus jumps to the list.

### How to focus tree sticky scroll items:
- Click on an element in the list (not sticky scroll element) causing the focus to be in the list. By pressing TAB key, the focus jumps to a sticky scroll element.
- Right click with the mouse on a sticky scroll element. This will cause the element to get focus and the context menu to open. If you press ESC, focus will stay on the sticky scroll element.

### Keys to test:
- **Arrow Up:** moves focus to element above. If there is no element above, focus stays on the top most element
- **Arrow Down & Arrow Right:** moves focus to element below. If there is no sticky scroll element below, focus the first child of the stick scroll element. This will cause the sticky scroll element to be revealed at the same location as it was (not sticky anymore).
- **Arrow Left:** Collapses the node and focus moves up to the last sticky element available
- **Space & Enter:** Same as left mouse click. Reveals the node under the mouse. The revealed node has focus.
- **Shift + F10:** Open Context Menu for sticky element.

**Comment by lszomoru** [comment]
Tested on macOS. Nice work 👏🏻

**Comment by eleanorjboyd** [comment]
Worked for me! My one comment is that after pressing "space" it was hard to notice that I had moved from having my highlight on the sticky scroll element to then being on a tree view element. I would press "space" again and then get an error message saying "sticky scroll has no focus"
