### ISSUE TITLE
Diff editor does not jump to 1st diff

### ISSUE THREAD

**Issue by gmccullo** [microsoft/vscode#202837]
Type: <b>Bug</b>

When I open a diff window by clicking on a file in the "source control" sidebar, the editor does not jump to the 1st diff. Didn't it use to do this?

I found old reports of this (https://github.com/microsoft/vscode/issues/197019), but I don't find an open issue on it now.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|61.95GB (39.58GB free)|
|Process Argv|--crash-reporter-id f4d11365-b8df-4076-a7d2-5647e124f85c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
html-end-tag-labels|ant|1.0.0
openmatchingfiles|bca|0.5.4
markdown-footnotes|bie|0.1.1
markdown-toc|Cha|1.5.6
vscode-markdownlint|Dav|0.53.0
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
xml|Dot|2.5.1
overtype|DrM|0.5.0
vsc-material-theme-icons|equ|3.3.1
url-encode|fle|1.1.0
html-preview-vscode|geo|0.2.5
live-sass|gle|6.1.2
todo-tree|Gru|0.0.226
vscode-html-validate|htm|2.8.1
docomment|k--|1.0.0
wordcounter|kir|2.4.4
csharpextensions|kre|1.7.3
vscode-autohotkey-plus-plus|mar|5.0.3
markdown-shortcuts|mdi|0.12.0
rainbow-csv|mec|3.11.0
render-crlf|med|1.7.1
csdevkit|ms-|1.2.7
csharp|ms-|2.15.30
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26
powershell|ms-|2024.0.0
csv-to-md-table|pho|0.3.1
material-icon-theme|PKi|4.33.0
word-counter|plu|0.0.1
toggle|reb|0.0.2
vscode-sort-json|ric|1.20.0
block-travel|sas|0.0.2
vscode-table-formatter|shu|1.2.1
code-spell-checker|str|3.0.1
code-spell-checker-british-english|str|1.4.4
code-spell-checker-french|str|0.4.1
code-spell-checker-german|str|2.3.1
code-spell-checker-greek|str|1.2.1
code-spell-checker-italian|str|1.1.1
code-spell-checker-medical-terms|str|3.0.2
code-spell-checker-scientific-terms|str|0.2.2
code-spell-checker-spanish|str|2.3.2
vscode-icons|vsc|12.7.0
whichkey|VSp|0.11.4
copyrawvalue|wer|1.0.0
deletehere|xin|0.0.1
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30933247
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by hediet** [comment]
Verification steps:
* Open a repo
* Do a change at the end of a longer file
* Open the diff from the SCM View and pin the diff editor (double click on the title)
* Scroll to the top in the diff editor
* Open a new editor (so that you don't see the diff editor anymore)
* Open the diff from the SCM view again
* Verify that the diff editor now scrolled back to the first diff (at the end of the file)
