### ISSUE TITLE
Test: Support native title and custom title together

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#202857]
Refs: #172464

- [x] macOS @paulacamargo25
- [x] windows @hediet
- [x] linux @andreamah

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23202857%0A%0A&assignees=benibenj)

---

With the newest update it's possible to have a native and a custom title bar at the same time. The `window.customTitleBarVisibility` setting can be used to control when to show the custom title bar.

- `auto`: When using native title bar we show the custom title bar when it is not empty
- `windowed`: We don't show custom title bar in full screen (applies to both `titleBarStyles` values)
- `never`: We never show the custom title bar when using native title bar

There are small differences depending on what operating system you are on, which is why I created individual testing steps. Please reach out to me if something is unclear. 

### MacOS Tester:
1. Enable Command Center (`window.commandCenter`)
3. Enable Layout Controls (`workbench.layoutControl.enabled`)
4. Turn on native tabs (`window.nativeTabs`) => Restart 
6. You should be seeing two titlebars (native and custom)
7. Create a new window (Command "New Window", cmd+Shift+N)
8. Merge windows all windows (Open Window menu and press "Merge All Windows")
9. You should be seeing native tabs
10. There should not be a menu in the custom title bar
12. Right click on custom title bar opens its context menu. Hide the command center
14. Right click on custom title bar opens its context menu. Hide the layout controls
15. This will cause the custom title bar to disappear because it's now empty
16. Move editor actions to the title bar (`workbench.editor.editorActionsLocation`)
17. Custom title bar reappears as it is no longer empty
19. Toggle full screen (enter full screen)
20. Custom title bar is still visible
21. Set the visibility of the custom title bar to 'windowed' (`window.customTitleBarVisibility`)
22. Custom title bar disappears as you are currently in full screen
23. Toggle full screen (exit full screen)
24. Custom Title Bar is visible again
25. Set the visibility of the custom title bar to 'never' (`window.customTitleBarVisibility`)
26. Custom Title Bar is hidden again
27. Move activity bar actions to the top (`workbench.activityBar.location`)
28. Custom Title Bar is visible again

### Windows Tester:
1. Enable Command Center (`window.commandCenter`)
3. Enable Layout Controls (`workbench.layoutControl.enabled`)
4. Set title bar style to native (`window.titleBarStyle`) => Restart
5. You should be able to see the custom and native title bar
10. There should not be a menu in the custom title bar
12. Right click on custom title bar opens its context menu. Hide the command center
14. Right click on custom title bar opens its context menu. Hide the layout controls
15. This will cause the custom title bar to disappear because it's now empty
16. Move editor actions to the title bar (`workbench.editor.editorActionsLocation`)
17. Custom title bar reappears as it is no longer empty
19. Toggle full screen (enter full screen)
20. Custom title bar is still visible
21. Set the visibility of the custom title bar to 'windowed' (`window.customTitleBarVisibility`)
22. Custom title bar disappears as you are currently in full screen
23. Toggle full screen (exit full screen)
24. Custom Title Bar is visible again
25. Set the visibility of the custom title bar to 'never' (`window.customTitleBarVisibility`)
26. Custom Title Bar is hidden again
27. Move activity bar actions to the top (`workbench.activityBar.location`)
28. Custom Title Bar is visible again

### Linux Tester:
1. Enable Command Center (`window.commandCenter`)
3. Enable Layout Controls (`workbench.layoutControl.enabled`)
4. Set title bar style to native (`window.titleBarStyle`) => Restart
5. You should only see the native title bar. By default we will not show the custom title bar on linux when using native title bar (maybe in a future update)
6. Set the visibility of the custom title bar to 'auto' (`window.customTitleBarVisibility`)
7. You should be seeing two titlebars (native and custom)
10. There should not be a menu in the custom title bar
12. Right click on custom title bar opens its context menu. Hide the command center
14. Right click on custom title bar opens its context menu. Hide the layout controls
15. This will cause the custom title bar to disappear because it's now empty
16. Move editor actions to the title bar (`workbench.editor.editorActionsLocation`)
17. Custom title bar reappears as it is no longer empty
19. Toggle full screen (enter full screen)
20. Custom title bar is still visible
21. Set the visibility of the custom title bar to 'windowed' (`window.customTitleBarVisibility`)
22. Custom title bar disappears as you are currently in full screen
23. Toggle full screen (exit full screen)
24. Custom Title Bar is visible again
25. Set the visibility of the custom title bar to 'never' (`window.customTitleBarVisibility`)
26. Custom Title Bar is hidden again
27. Move activity bar actions to the top (`workbench.activityBar.location`)
28. Custom Title Bar is visible again

**Comment by andreamah** [comment]
Great job! 💪🙂
