### ISSUE TITLE
Upgrade to 1.9.1 crashed 

### ISSUE THREAD

**Issue by DavidA2014** [Microsoft/vscode#20280]
- VSCode Version: 1.9.1
- OS Version: Windows 10

Automated update from 1.9.0 to 1.9.1 gave an exception when I restarted VS Code to complete the update:

![image](https://cloud.githubusercontent.com/assets/7724321/22781397/40c391e2-eeba-11e6-94fc-2fa1828b1efe.png)

Required reinstallation of 1.9.0.  Had to manually close 4 processes running Code (even after Windows restart).  After reinstallation the update to 1.9.1 succeeded.

**Comment by joaomoreno** [comment]
Thanks for the screenshot, sorry for this situation! I'm glad everything is working fine after a reinstallation.
