### ISSUE TITLE
Requires installing Python + Jupyter plugin each time after restart to select virtual environments

### ISSUE THREAD

**Issue by AbhiPawar5** [microsoft/vscode#202802]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.2 (Universal)
- OS Version: Darwin arm64 21.6.0

Steps to Reproduce:

1. Open any Jupyter notebook
2. Click on 'Install Python + Jupyter plugin' to select virtual environments
3. Wait till installation is complete.
4. Restart VS Code and repeat

**Comment by amunger** [comment]
It sounds like the Jupyter extension isn't starting up successfully - can you check in the extensions tab if it is actually enabled?

The console in `Developer: Toggle developer tools` should have an error message about what went wrong.

**Comment by AbhiPawar5** [comment]
I moved the application outside of download folder. It seems to be working
now. Thanks.
