### ISSUE TITLE
Editor scroll position jumps up when returning to editor

### ISSUE THREAD

**Issue by tristan-morrison** [microsoft/vscode#202811]
Type: <b>Bug</b>

When navigating away from and back to an editor containing expanded PR comments, the scroll position of the editor is not preserved when focus returns to it. Instead, the editor's scroll position jumps higher up in the file.

**Expected behavior**
An editor is open in an editor group and the user navigates to a different editor in that group. When the user navigates back to the first editor, it opens at the same scroll position it was in when the user navigated away from it.

**Actual behavior**
An editor (containing one or more expanded PR comments) is open in an editor group and the user navigates to a different editor in that group. When the user navigates back to the first editor, it momentarily appears in the same scroll position it was in when the user navigated away from it. A moment later, however, the scroll position jumps higher up in the file.

Steps to reproduce:
1. Open two or more editors in an editor group. At least one of the editors must contain PR comments.
2. Navigate to one of the files containing PR comments, and expand at least one of the comments. Note the scroll position of the editor, for example, the line number of the first line visible at the top of the editor.
3. Navigate to another editor in the group.
4. Navigate back to the first editor. Note the scroll position immediately upon returning to the file; it should be the same as when you left.
5. Wait a moment (seems to be no more than one second). You should now have seen the scroll position of the editor jump up. Now, the line number of the first visible line should be less than that of the first visible line previously.

Other notes:
* The magnitude of the jump in scroll position seems to vary proportionally to the amount of vertical space occupied by PR comments. For example, in one test I did, I collapsed all but one of the comments, scrolled elsewhere in the file, then navigated away from the editor. When I returned, the scroll position jumped up by about 25 lines. Then, I expanded a few more of the PR comments and repeated the same sequence of actions. This time, the jump was equivalent to 75 lines.
* As a corollary to the first point, this issue does not present when all PR comments in a file are collapsed. Of course, this makes sense in terms of the first point because, when the vertical space occupied by PR comments is zero, the magnitude of the scroll position jump is zero.
* I first noticed this issue immediately after updating to the latest VS Code version (1.85). I did not notice whether or not the version of the extension also changed at that time.

Extension version: 0.79.2023121409
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin x64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 7, 15|
|Memory (System)|32.00GB (2.44GB free)|
|Process Argv|--crash-reporter-id 3622bda1-f8a6-4c12-b164-9fe14b832e0f|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by alexr00** [comment]
To verify:
1. Open a file with a comment and make sure the comment is expanded. Scroll to the bottom.
2. Switch to another file in the same editor group.
3. Switch back to the first file.
4. Verify that the scroll position only ever jumps by 2 lines and not by an amount proportional to the size of the comment thread widget.
