### ISSUE TITLE
File structure not updating after changing git branch from terminal unless manually refreshed.

### ISSUE THREAD

**Issue by shreyas-a** [Microsoft/vscode#20286]
- VSCode Version: 1.9.1
- OS Version: OSX 10.12.2

Steps to Reproduce:

1. Open a project (with a git branch) in VS Code
2. Change the branch from terminal.
3. Notice the file structure not updating w.r.t the new branch.

**Comment by Tyriar** [comment]
Do you mean the explorer on the left side?

**Comment by bpasero** [comment]
@shreyas-a 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by shreyas-a** [comment]
@Tyriar Yes!

**Comment by shreyas-a** [comment]
Tried it once again in the stable version. It's working fine now. Not sure what happened that time. Not able to reproduce it now.

**Comment by bpasero** [comment]
File events sometimes are flaky, hard to understand what was going on. If it reproduces again, let me know.
