### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#202855]
ADD ISSUE DESCRIPTION HERE

Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Embedder: codespaces

It takes a significant amount of time for the Code Editor to check the tasks as well as update the grade.

**Comment by gjsjohnmurray** [comment]
> check the tasks as well as update the grade

It sounds like you are using an online course, in which case please close this issue and contact course support.
