### ISSUE TITLE
`ICodeEditorService.getFocusedCodeEditor()` returns inline chat code editors

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#202845]
We use `ICodeEditorService` in some places to get at the currently focused code editor. To my surprise, this method seems to be returning `EmbeddedCodeEditor` that are used for example as Copilot chat input. I would argue that in most if not all our usages, we only care about text editors that contain contents of a document, but not input fields like that.

https://github.com/microsoft/vscode/blob/945bbd01aa9c90c3dcc6ae51595e834fde5adbad/src/vs/editor/browser/services/codeEditorService.ts#L44

Can we add some kind of filter logic or a way for the caller to know if the returned editor is used as input field?

**Comment by alexdima** [comment]
@bpasero I don't know exactly what @jrieken uses, but `ICodeEditor.isSimpleWidget` can be used to find out if this editor instance is an "input field".

**Comment by bpasero** [comment]
Got it, I am not sure how big of an issue this is today for everyone using the API, but I will check for my usages.

**Comment by jrieken** [comment]
> but ICodeEditor.isSimpleWidget can be used to find out if this editor instance is an "input field".

Yeah, that's what I use too
