### ISSUE TITLE
Test: triggered breakpoints

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#202882]
Refs: #152428

- [x] anyOS @isidorn
- [ ] anyOS @karrtikr

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23202882%0A%0A&assignees=connor4312)

---

This iteration, we've added the notion of "triggered breakpoints", which are breakpoints that are only activated when another breakpoint is hit. The basic flow is:

1. Have a program you can debug, in any language. Set one or more breakpoints in the program.
1. Right click in the glyph margin and "Add Triggered Breakpoint"
1. Select the breakpoint you want to wait for.
1. Debug and see that the triggered breakpoint can only be hit once the "wait for" breakpoint gets hit.

Do some explorations with this, such as...

- Play with breakpoint widget opened with "Add Triggered Breakpoint" and make sure it works
- Verify that removing the _triggering_ breakpoint converts any triggered breakpoints into ordinary breakpoints
- Verify that disabling the _triggering_ breakpoint disable any triggered breakpoints, and enabling enables the triggered breakpoints
- Try resuming very quickly after hitting the _triggering_ breakpoint and make sure there are no races
- Check that hovers are sensible and that the **Breakpoints** view works as you would expect

**Comment by isidorn** [comment]
This is pretty polished and works well - nice job 👏

**Comment by karrtikr** [comment]
Great job - works seamlessly.
