### ISSUE TITLE
Find All References does not work until the referencing file has been opened

### ISSUE THREAD

**Issue by b-steel** [microsoft/vscode#202888]
Type: <b>Bug</b>

I tested this on a blank create-react-app (`npx create-react-app my-app`)
Here is a repro I made [github](https://github.com/b-steel/cursor-go-to-def) 

The created app has `src/index.js` which clearly imports the App function from `src/App.js`
```
import App from './App';
``` 

If I open the project in vscode, open `src/App.js` and right click on the `export default App` line at the bottom then Find All References reports no matches outside the file.  If I then open the above mentioned `index.js` file and then repeat the process in the `App.js` file suddenly if finds the reference in `index.js`.  

I have used the extension bisector and this happens with all extensions disabled.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:32.531Z)
OS version: Darwin x64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 4, 5|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 24367a0e-519c-4f42-8bf7-93be94ebc73c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-tailwindcss|bra|0.10.5
path-intellisense|chr|2.8.5
vscode-eslint|dba|2.4.2
vscode-great-icons|emm|2.1.102
prettier-vscode|esb|10.1.0
vscode-expo-tools|exp|1.0.7
vscode-github-actions|git|0.26.2
vscode-leetcode|Lee|0.18.1
vscode-docker|ms-|1.28.0
color-highlight|nau|2.5.0
prisma|Pri|5.8.1
vscode-mdx|uni|1.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
0bi6i642:30933247
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019acf:30933242

```

</details>

**Comment by IllusionMH** [comment]
Do you have `jsconfig.json` or `tsconfig.json` with corresponding `inckudes` confirmation in your workspace?

Without it TS Server does not load other files, unless imported directly into open files.

See https://code.visualstudio.com/docs/languages/jsconfig

**Comment by b-steel** [comment]
Thank you very much!  Turns out I don't even need the `include` keyword since if you exclude that from the `jsconfig.json` it includes everything in the current directory.
