### ISSUE TITLE
Test: updating default test profiles

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#202884]
Refs: #193160

- [x] anyOS @justschen 
- [x] anyOS @rzhao271 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23202884%0A%0A&assignees=connor4312)

---

This iteration adjusts and finalizes the API for dealing default test profiles. The default test profile(s) are those which are used when clicking on run buttons (▶️) in the UI. Previously these weren't visible in the API.

1. Start with a test extension that exposes multiple profiles, such as the selfhost test provider https://github.com/microsoft/vscode-selfhost-test-provider
2. Modify some of the code that creates run profiles https://github.com/microsoft/vscode-selfhost-test-provider/blob/1d09ecc63752e305339fe7c99777bd6526800aeb/src/extension.ts#L156-L186 such that:
    - You have a way to asynchronously set `profile.isDefault` (a setTimeout is easy and works)
    - Listen to and log changes to `profile.onDidChangeDefault`
3. Now verify that:
    - The user changing the default profiles as a results in the correct changes to `profile.isDefault` and a change event firing (Use the dropdown button on top of the Test Explorer view, and Select Default Profiles)
    - The extension changing the `isDefault` property results in the appropriate update in the editor UI
4. Note that profiles created via `createRunProfile` have an initial value for their default property, which are used if the user hasn't otherwise configured their desired set of profiles. With a changed set of default profiles (profiles other than Electron selected) reload the window. Verify that the extension then sees immediate `onDidChangeDefault` events as its profiles are updated to reflect the user's selected defaults.

**Comment by rzhao271** [comment]
I'm confused by what it means to have multiple default run test profiles. Apart from that, LGTM.

![Checkboxes allowing users to specify multiple default run test profiles in the sample extension](https://github.com/microsoft/vscode/assets/7199958/c7396013-1218-4866-a7b5-34996853f7c0)
