### ISSUE TITLE
No close, minimize button on the workspace opened in full-screen mode prior to latest update.

### ISSUE THREAD

**Issue by abhi3700** [microsoft/vscode#202851]
Type: <b>Bug</b>

I am not able to see the 3 buttons for the VSCode workspace that was opened in full-screen mode on macOS. Please see the attached pic:
<img width="696" alt="image" src="https://github.com/microsoft/vscode/assets/16472948/e0f07f20-8644-4e02-8bcc-03c904780c30">

And the 3 buttons that I am referring to:
<img width="224" alt="image" src="https://github.com/microsoft/vscode/assets/16472948/abcf86c7-11f0-46f1-8af6-0851664e7e20">

Some observations:
- Able to minimize using shortcut key <kbd>cmd+m</kbd> ✅ 
- Not able to close ❌ the window by shortcut key <kbd>cmd+shift+w</kbd> either, given that the button is not shown.
- Not able to quit VSCode ❌ by either shortcut key <kbd>cmd+q</kbd> or "Quit" option at the top left menu when clicked on VSCode.

> These issues are found post the latest update.

Please fix.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:11.430Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 6, 8|
|Memory (System)|32.00GB (7.42GB free)|
|Process Argv|--crash-reporter-id d289c50a-1fce-452f-a2b2-a1ad33494947|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (223)</summary>

Extension|Author (truncated)|Version
---|---|---
ethcode|7fi|0.4.9
starkode|7fi|0.0.2
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-css-formatter|aes|1.0.2
include-autocomplete|ajs|0.0.4
Bookmarks|ale|13.4.2
iconify|ant|0.7.4
atlascode|atl|3.0.9
jsoncrack-vscode|Ayk|2.0.2
vscode-django|bat|1.15.0
emojisense|bie|0.10.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.21.0
markdown-preview-github-styles|bie|2.0.3
markdown-yaml-preamble|bie|0.1.0
mermaid-markdown-syntax-highlighting|bpr|1.6.0
vscode-tailwindcss|bra|0.10.5
simple-react-snippets|bur|1.2.7
ruff|cha|2024.2.0
vscode-opennewinstance|chr|0.0.12
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
vs-code-semicolon-insertion|chr|0.0.6
gitignore|cod|0.9.0
solidity-lang|Con|1.6.0
doxdocgen|csc|1.4.0
vscode-svgviewer|css|2.0.0
dbclient-jdbc|cwe|1.3.4
vscode-database-client2|cwe|7.0.1
hex-to-rgba|dak|1.0.0
move-syntax|dam|0.4.15
c-cpp-project-generator|dan|1.2.13
vscode-markdownlint|Dav|0.53.0
vscode-eslint|dba|2.4.2
go-coverage-viewer|def|1.0.3
dendron-paste-image|den|1.1.1
docs-linting|doc|0.0.13
githistory|don|0.6.20
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
vscode-wasm|dts|1.4.1
rust-syntax|dus|0.6.1
gitlens|eam|14.7.0
vscode-create-jupyter|eng|0.0.5
carbon-now-sh|eri|1.2.0
pythonsnippets3|Eri|3.3.20
prettier-vscode|esb|10.1.0
json-pretty-printer|eus|1.1.0
vscode-github-notifications-bell|fab|2.3.1
vscode-markdown-todo|fab|1.1.1
vscode-open-in-github|fab|1.3.0
vscode-todo-plus|fab|4.19.1
cpp-class-creator|Fle|1.1.0
terminal-in-status-bar|fly|0.2.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
freecodecamp-courses|fre|2.1.0
meet|gee|0.1.6
youtube-search|gee|0.0.1
chatgpt-vscode|gen|0.0.10
markmap-vscode|ger|0.1.2
github-linker|gim|0.2.5
codespaces|Git|1.16.6
copilot|Git|1.152.0
copilot-chat|Git|0.11.1
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.78.1
gitpod-desktop|git|0.0.163
go|gol|0.40.1
go-nightly|gol|2024.1.1813
vscode-kanbn|gor|0.11.0
gc-excelviewer|Gra|4.2.58
json2ts|Gre|0.0.6
mermaid-export|Gru|0.0.8
vsc-essentials|Gyd|0.6.0
timing|Haa|2.7.2
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.6
screeny|Hou|0.2.0
c-math-viewer|Hye|1.0.4
output-colorizer|IBM|0.1.2
circom|ide|0.0.2
vscode-react-typescript|inf|1.3.1
todo|iza|0.1.0
search-node-modules|jas|1.3.0
c-cpp-flylint|jbe|1.13.1
plantuml|jeb|2.17.5
better-cpp-syntax|jef|1.17.2
prettier-rust|jin|0.1.9
nbpreviewer|jit|1.2.2
rust-formatter|jms|0.0.1
vscode-graphviz|joa|0.0.9
cmake-language-support-vscode|jos|0.0.9
rust-doc-viewer|JSc|4.2.0
solidity|Jua|0.0.165
react-native-snippet|jun|0.5.6
google-search|kam|0.0.1
vscode-sshfs|Kel|1.26.1
vsc-python-indent|Kev|1.18.0
ts-extension-pack|loi|0.3.0
vscode-swissknife|lui|1.8.1
code-coverage|mar|1.11.0
vscode-catch2-test-adapter|mat|4.8.0
identical-sublime-monokai-csharp-theme-colorizer|max|1.2.3
rainbow-csv|mec|3.11.0
git-graph|mhu|1.30.0
sql-snippet|Mil|0.0.4
document|min|2.2.1
vscode-clang|mit|0.2.4
vscode-kanban|mkl|1.33.2
mongodb-vscode|mon|1.4.0
move-msl-syx|Mov|0.0.2
sui-move-analyzer|Mov|1.1.4
vscode-docker|ms-|1.28.0
vscode-dotnet-runtime|ms-|2.0.0
vscode-kubernetes-tools|ms-|1.3.15
vscode-postgresql|ms-|0.3.0
playwright|ms-|1.0.21
black-formatter|ms-|2023.6.0
debugpy|ms-|2023.3.13341006
isort|ms-|2023.10.1
python|ms-|2023.25.10191009
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-powertoys|ms-|0.1.0
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.9
azure-repos|ms-|0.38.0
cmake-tools|ms-|1.16.32
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.12
live-server|ms-|0.4.13
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
sublime-keybindings|ms-|4.0.10
test-adapter-converter|ms-|0.1.9
vsliveshare|ms-|1.0.5905
mythxvsc|Myt|0.7.21
color-highlight|nau|2.5.0
python-ext-pack|nda|0.0.6
autodocstring|njp|0.6.1
vscode-noir|noi|0.0.9
indent-rainbow|ode|8.3.1
cosmwasm-ide|ora|0.13.64
vscode-graphql|ors|0.3.18
cargo|pan|0.2.3
open-html-in-browser|pea|2.1.10
betterfountain|pie|1.12.0
material-icon-theme|PKi|4.33.0
heroku-command|pko|0.0.8
tsimporter|pmn|2.0.1
excalidraw-editor|pom|3.7.1
cpp-format|psy|1.2.0
inline-sql-syntax|quf|2.16.0
vscode-thunder-client|ran|2.17.1
vscode-yaml|red|1.14.0
bookmarksng|RK|0.0.24
keep-a-changelog|RLN|1.3.0
color-manager|roy|0.7.5
rust-analyzer|rus|0.3.1807
partial-diff|ryu|1.4.3
vscode-open|san|0.1.0
react-component-preview|Seo|1.0.5
crates|ser|0.6.5
bootstrap-5-snippets|sha|1.0.1
html5-boilerplate|sid|1.1.1
eosio|SMH|0.0.1
snappify|sna|1.0.2
dotenv-vscode-stripped|soc|0.24.0
vscode-open-in-gitfork|spa|1.0.3
cairo1|Sta|2.3.0
code-spell-checker|str|3.0.1
move-ts|str|1.12.0
pretty-json|sup|0.0.4
vscode-rust-test-adapter|Swe|0.11.0
sldb-vscode|sym|1.7.0
even-better-toml|tam|0.19.2
ethereum-security-bundle|tin|0.0.7
graphviz-interactive-preview|tin|0.3.5
solidity-metrics|tin|0.0.23
solidity-visual-auditor|tin|0.2.0
vscode-ethover|tin|0.0.7
vscode-inline-bookmarks|tin|0.1.0
vscode-LLL|tin|0.0.7
vscode-solidity-language|tin|0.0.7
vscode-vyper|tin|0.0.15
pdf|tom|1.2.2
cmake|twx|0.0.17
luna-paint|Tyr|0.16.0
vscode-terminal-here|Tyr|0.2.4
ultra-cpp|ult|1.3.9
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-svg-previewer|vit|0.7.0
soliditypp|Vit|0.7.11
solppdebugger|Vit|0.2.6
vscode-mermaid-preview|vst|1.6.3
felang|vuv|0.0.3
vscode-wakatime|Wak|24.4.0
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
vscode-go-autotest|win|1.6.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.6.2
json|Zai|2.0.2
previewjs|zen|1.27.3
rust-extension-pack|Zer|1.1.1
material-theme|zhu|3.16.2
zokrates|zok|0.1.0

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30933248
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019a:30933241

```

</details>

**Comment by bpasero** [comment]
Do you have steps to reproduce? Does it reproduce with our insiders version? 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by abhi3700** [comment]
I had to quit from the activity monitor. And now it's fixed.
Restarted VSCode after quitting all the related running tasks. And now it's running fine.

**Comment by bpasero** [comment]
Ok if you find a pattern how to reproduce this, please comment again.

**Comment by abhi3700** [comment]
sure
