### ISSUE TITLE
URL vscode:extension/extension.id does not open extension from the marketplace unless Code is already launched

### ISSUE THREAD

**Issue by StanislawStempin** [Microsoft/vscode#20289]
- VSCode Version: 1.9.1
- OS Version: Windows 10 Enterprise 14393.693

Steps to Reproduce:

1. Install VS Code
2. Open the following URL from any browser or Win+R:  vscode://extension/ms-vscode.csharp

Expected result:
According to #4883 that URL should launch VS Code and open the Microsoft C# (Omnisharp) extension

Actual result:
VS Code launches but nothing happens afterwards

**Comment by joaomoreno** [comment]
I'm pretty sure this was working. I can reproduce that the extension doesn't show up when Code isn't running. It does show up when Code is running, though. Can you confirm?

**Comment by StanislawStempin** [comment]
It doesn't seem to work regardless of Code running or not on my machine. I tried Chrome, IE, Edge and Win + R as well as VS Code with and without an open folder.

**Comment by joaomoreno** [comment]
Oh, you gotta adjust the url. The right format is `vscode:extension/ms-vscode.csharp`

**Comment by StanislawStempin** [comment]
Ok, that works but only if Code is already launched.

**Comment by jordanmkasla2009** [comment]
it appears this issue is due to the `ExtensionWorkbenchService` not being the first subscriber to the `urlService.onOpenUrl` event. `WindowsService` subscribes to the event first on launch and so `vscode:extension/id` urls get filtered out before `ExtensionWorkbenchService` can subscribe to the event.

**Comment by joaomoreno** [comment]
@jordanmkasla2009 Absolutely right!

**Comment by dbaeumer** [comment]
Can't be verified with insider since the URL handler for vscode opens VS Code stable.

**Comment by chrmarti** [comment]
@joaomoreno Shouldn't `vscode-insiders:extension/extension.id` work? That only opens VSCode, but doesn't open the extension for me on todays insiders on Windows 10 - also when VSCode is already open. (Although: It also doesn't work with 1.11.2 when already open, so maybe there is an additional problem.)

**Comment by mjbvz** [comment]
I've tried using both code-oss://extension/ms-vscode.csharp  (After updating the product.json) and vscode-insiders://extension/ms-vscode.csharp but could not get this feature to work on a Mac. It launches vscode but does not open the extension page

**Comment by mjbvz** [comment]
verified in just release insiders
