### ISSUE TITLE
Add support for showing an indicator of lint errors beside file names in the sidebar

### ISSUE THREAD

**Issue by antonsekatski** [Microsoft/vscode#20281]
I think it would be great if vscode could show some sort of an indicator of lint errors (ESLint, TSLint, etc.) near file names in the sidebar.

Here is an example of how it might look like:

![lint-error-vscode](https://cloud.githubusercontent.com/assets/8408671/22781347/283ed24e-eed3-11e6-9048-81b90332bd12.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/782
