### ISSUE TITLE
Test: Tree sticky scroll support compact sticky nodes

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#202840]
Refs: #199539

- [x] anyOS @meganrogge
- [x] anyOS @hediet

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23202840%0A%0A&assignees=benibenj)

---

In this update we will support compressing sticky nodes when the maximum number of elements in the tree sticky scroll widget is reached. This only works for trees that support compression like most file system trees in core (file explorer, search view rendered as tree, SCM view rendered as tree, ...). Trees contributed by extensions do not support compression.

### When do we compress items together in tree sticky scroll:
- When sticky scroll needs to render more than `workbench.tree.stickyScrollMaxItemCount` elements
- When the max allowed hight for sticky scroll is reached. Sticky scroll is allowed to only take up 40% of the tree view. If it needs to render one more item in sticky scroll which would cause the widget to take more than 40% it will compress the node with the previous one.
- Not all items support compression, for example in the search results tree a file can not be compressed together with a folder

### How to test:
1. Open a project with many nested folders (like VSCode)
2. Change  `workbench.tree.stickyScrollMaxItemCount` to 5 (makes it easier to test)
3. Go to explorer view
4. Make sure to expand many nested folders
5. Slowly scroll through the tree. Make sure it never renders more than  `workbench.tree.stickyScrollMaxItemCount` elements. 
6. When sticky scroll renders the max amount of elements and you scroll over another expanded nested folder, then it will render that folder together with the last sticky scroll element.
7. Make the size of the explorer view smaller by resizing it (will require to have another expanded view in the sidebar). See how it compresses more sticky scroll items together to make sure the widget does not take more than 40% of the view.
8. Change the `workbench.tree.stickyScrollMaxItemCount` value and repeat steps 4 - 6
9. Test this in another tree, for example in the search view you can search for the word 'toolbar', this will lead to many nested results. Make sure to display the results as a tree structure.

### BEFORE: WITHOUT COMPRESSION
![Code_-_Insiders_GrRqTHA0XJ](https://github.com/microsoft/vscode/assets/44439583/04411333-fdf8-4556-8e80-82d20a08e5ad)

### AFTER: WITH COMPRESSION
![Code_-_Insiders_10pWNnb4Mh](https://github.com/microsoft/vscode/assets/44439583/f951f1f9-b630-4b41-a2eb-f0e21ede5000)

**Comment by hediet** [comment]
Nice job!

**Comment by dinofx** [comment]
Excellent.  This should have been highlighted in the video/animation in the release notes.  I hope others find this issue before they open duplicate feature requests.
