### ISSUE TITLE
Show editor tabs within title area of the window

### ISSUE THREAD

**Issue by sgtoj** [Microsoft/vscode#20287]
#### Feature Request
Is it possible to switch to Edge-like title bar for VS Code on Windows. Similar to the VS Code UI for Ubuntu (and Mac?) -- except with the file bar menu hidden behind a MS hamburger button in the left corner. 

![Edge's Title Bar](http://i.imgur.com/gr07gb6.png)

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
