### ISSUE TITLE
Failed to access `code serve-web` with token on browser

### ISSUE THREAD

**Issue by Qinka** [microsoft/vscode#202812]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  
版本: 1.85.2
提交: 8b3775030ed1a69b13e4f4c628c612102e30a681
- OS Version:  Fedora 39 Sway 
- Browser: Firefox and Edge

Steps to Reproduce:

1.  execute: `code serve-web --host 172.22.60.100 --port 3333 --accept-server-license-terms`
2. Access `http://172.22.60.100:3333?tkn=b6f06646-38dc-4cdb-a39b-44bbd791d350` in browser
3. Error: 
![图片](https://github.com/microsoft/vscode/assets/9249996/f1914c41-5652-4922-b3e8-486ec5f2a526)

If I launch code with `--without-connection-token`, vscode was launch normally on the browser.

**Comment by connor4312** [comment]
Please see the notes https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_82.md#serve-web-cli-command

> Note that in order to access the server on non-localhost origins, you will need to serve the UI over TLS using a reverse proxy server such as [Caddy](https://caddyserver.com/).
