### ISSUE TITLE
Quick Open too slow

### ISSUE THREAD

**Issue by Jackie-Yang** [Microsoft/vscode#20296]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.0|

---

Steps to Reproduce:

It's too slow to search file when I using Ctrl+p (Quick Open) to search file in a big folder (almost 20G)

**Comment by Jackie-Yang** [comment]
Slower than Linux.

**Comment by chrmarti** [comment]
We are using `find` on Linux vs. our own traversal on Windows.

**Comment by Jackie-Yang** [comment]
@chrmarti VSCode is very useful, but searching files is too slow too work, and the sublime's performance on Windows is better than VSCode, so we hope it will be improved in the future

**Comment by aristotaly** [comment]
It is working slow on a 915 MBfolder as well

**Comment by chrmarti** [comment]
Related: #24074
