### ISSUE TITLE
January 2024 Endgame Recovery 1

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#202950]
- [x] Create a milestone `<Month> <Year> Recovery <1|2|3>` **@aiday-mar**
- [x] Bump the version number **@aiday-mar**
- [x] [🔖candidate issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Acandidate+repo:microsoft/monaco-editor%20repo:microsoft/vscode%20repo:microsoft/vscode-anycode%20repo:microsoft/vscode-copilot%20repo:microsoft/vscode-copilot-release%20repo:microsoft/vscode-dev%20repo:microsoft/vscode-dev-chrome-launcher%20repo:microsoft/vscode-emmet-helper%20repo:microsoft/vscode-extension-telemetry%20repo:microsoft/vscode-github-issue-notebooks%20repo:microsoft/vscode-hexeditor%20repo:microsoft/vscode-internalbacklog%20repo:microsoft/vscode-js-debug%20repo:microsoft/vscode-jupyter%20repo:microsoft/vscode-jupyter-internal%20repo:microsoft/vscode-l10n%20repo:microsoft/vscode-livepreview%20repo:microsoft/vscode-pull-request-github%20repo:microsoft/vscode-python%20repo:microsoft/vscode-python-debugger%20repo:microsoft/vscode-references-view%20repo:microsoft/vscode-remote-release%20repo:microsoft/vscode-remote-repositories-github%20repo:microsoft/vscode-remote-tunnels%20repo:microsoft/vscode-remotehub%20repo:microsoft/vscode-settings-sync-server%20repo:microsoft/vscode-unpkg%20repo:microsoft/vscode-vsce%20repo:microsoft/vscode-pylint%20repo:microsoft/vscode-black-formatter%20repo:microsoft/vscode-isort%20repo:microsoft/lsprotocol%20repo:microsoft/vscode-flake8%20repo:microsoft/vscode-autopep8%20repo:microsoft/vscode-python-tools-extension-template%20repo:microsoft/vscode-mypy%20repo:microsoft/vscode-python-debugger)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `main`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **@aiday-mar**
- [x] Issues are verified on `stable` build and the `verified` label is added **@aiday-mar**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **@aiday-mar**
- [x] The `insiders` build with all candidate fixes needs to be in the wild for 24 hours before recovery release, unless explicitly approved by @kieferrm
- [x] Update the release notes and include a link to a query for the fixed issues **@ntrogh**
- [x] [Sanity Testing](https://github.com/microsoft/vscode/wiki/Sanity-Check)
  - [x] Windows 64 bit **@benibenj**
    - [x] System Installer
    - [x] User Installer
    - [x] Archive
    - [x] Server
    - [x] CLI
  - [x] Windows ARM64 **@lszomoru**
    - [x] System Installer
    - [x] User Installer
    - [x] Archive
    - [x] CLI
  - [x] macOS Intel **@isidorn**
    - [x] Archive
    - [x] Universal Archive
    - [x] Server
    - [x] CLI
  - [x] macOS ARM64 **@sandy081**
    - [x] Archive
    - [x] Universal Archive
    - [x] Server
    - [x] CLI
  - [x] Linux x64 **@aeschli**
    - [x] Archive
    - [x] DEB
    - [x] RPM
    - [x] Snap
  - [x] Linux Server **@chrmarti** _(can be tested from any OS with Docker)_
    - [x] x64
    - [x] ARM32
    - [x] ARM64
    - [x] x64 Alpine
    - [x] ARM64 Alpine
  - [x] Linux CLI **@ulugbekna** _(can be tested from any OS with Docker)_
    - [x] x64
    - [x] ARM32
    - [x] ARM64
    - [x] x64 Alpine
    - [x] ARM64 Alpine
- [x] Publish website **@ntrogh**
- [x] Publish stable build **@aiday-mar**
- [x] Create an official release **@aiday-mar**
  - [x] Create a tag (make sure you pull the release branch first): `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)
- [x] Close the milestone on [GitHub](https://github.com/microsoft/vscode/milestones) **@aiday-mar**

**Comment by corford** [comment]
Is this recovery release planned to land today? Asking as it resolves: https://github.com/microsoft/vscode/issues/203375 (last comment there mentioned recovery release date of 8th Feb - if this is delayed, then we'll roll back to a previous VSCode release in the interim)

**Comment by aiday-mar** [comment]
Hi @corford yes this recovery release will be made very soon
