### ISSUE TITLE
Terminal encoding

### ISSUE THREAD

**Issue by matheusrocha89** [Microsoft/vscode#20297]
When I try to right some special chars on terminal it shows a code and not the special char. A list of characters examples are: `ç, é, ã, õ, í`

- VSCode Version: 1.9.1
- OS Version: Mac OS X Sierra

Steps to Reproduce:

1. Open the vscode internal terminal
2. Try to write any special characters

![vscode](https://cloud.githubusercontent.com/assets/3718366/22786590/e197df04-eeb7-11e6-9aa8-cd4db72bcf27.gif)

**UPDATE**: This happen not only when you try to write the characters but when try to render too when they appear on a `git diff` or `cat`

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/14586
