### ISSUE TITLE
Test: voice keyword activation ("Hey Code")

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#202926]
Refs: https://github.com/microsoft/vscode/issues/197050

- [x] macOS @jrieken
- [x] linux @lramos15
- [x] windows @bhavyaus

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23202926%0A%0A&assignees=bpasero)

---

**Setup:** install the pre-release version of `ms-vscode.vscode-speech`. At least be on `v0.3.x`

**Testing:**
* review the new setting `accessibility.voice.keywordActivation` makes sense
* flip through the values and verify the related action is triggered when you say "Hey Code"
* verify you see a status bar entry 🎤  informing you about active listening
* verify that after the voice chat session is done, "Hey Code" works again
* verify the status bar entry hides when you turn this back off again

**Comment by starball5** [comment]
loosely related, some users are seeing "waiting for voice chat to end" in relation to this feature: https://stackoverflow.com/q/77853020/11107541. Is something set up wrong? Are they supposed to have to manually install the speech extension?

**Comment by jrieken** [comment]
@lramos15 @bhavyaus Can I trade the linux with windows or macos here? My VM setup is linux-arm which isn't supported by the speech extension
