### ISSUE TITLE
Find text in files tree doesn't work properly 

### ISSUE THREAD

**Issue by rcorsari** [microsoft/vscode#202959]
Type: <b>Issue</b>

Tried to find the occurrence of a string in a PHP Codeigniter tree project

The string is there for sure and with the aid of a windows utility program named UltraFileSearch I have found the occurrence of that string in 5 (five) files

![UltraFileSearch-result](https://github.com/microsoft/vscode/assets/10007559/4e85afcb-6010-4ebf-af54-a9ee1abff4e5)

the string is "password_confirm"

I collapsed the whole Explorer tree in Visual Studio Code 1.85.2 , clicked the lens icon and tried to find all the occurrences of that string 

it finds the occurrence in two files only despite using the "files to include" option with these settings

![visual-studio-code-result](https://github.com/microsoft/vscode/assets/10007559/c1d0427e-cccd-40ea-acdb-d81247bc64a7)

Please  note that there are 9000 files and 875 subdirs (because of the  vendors subtrees from Composer)

Either after the time it took to write this Issue Report, there are still only 2 files out of 5 in the search result panel

Here you find the three for testing purpose
https://mega.nz/file/hW02QA7R#1kg6oxFBC8nyncmRxb0kV7YBOm_EMGgyX4bmb5Yqkw4

This tree is on a Ubuntu server 22.04LTS and shared with Samba
Visual Studio Code is running on windows
Windows is 10 22H2 fully updated

Kind regards
Roberto

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.02GB free)|
|Process Argv|Z:\\ticket --crash-reporter-id 3b04773e-b13e-4a06-9308-b80b4e58f7aa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
codeigniter4-snippets|ade|0.1.1
surround-with-tag|Bal|1.0.0
vscode-intelephense-client|bme|1.10.2
dbclient-jdbc|cwe|1.3.4
vscode-eslint|dba|2.4.2
code-runner|for|0.12.1
theme-monokai-pro-vscode|mon|1.2.2
vscode-duplicate|mrm|1.2.1
material-icon-theme|PKi|4.33.0
format-html-in-php|rif|1.7.0
code-spell-checker|str|3.0.1
code-spell-checker-italian|str|1.1.1
es6-string-html|Tob|2.14.1
html-css-class-completion|Zig|1.20.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
0bi6i642:30933247
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019a:30933241

```

</details>

**Comment by IllusionMH** [comment]
Do you have `vendor` mentioned in excluded or ignored (e.g. `.gitignire`) files?

"files to exclude" field has toggle enabled on your screenshot, so these files won't be in results

**Comment by rcorsari** [comment]
You are right but that is an unwanted behavior IMPO because I haven't enabled that filter

So you say that it is enabled by default, but I believe that should not be like that and instead it should be a user choice

I had to open this issue to discover "the issue" that should not be such. If seeking for a string would result in too many ghost results

**Comment by andreamah** [comment]
I see where you're coming from there, but we've seen that users usually want to ignore the files in their gitignore and ignore settings. Also, the tooltip on the exclude button does say "Use Exclude Settings and Ignore Files", and we hope that users can notice that it's enabled when it is.

<img  alt="image" src="https://github.com/microsoft/vscode/assets/31675041/a3babd9b-7a79-4989-899c-b3ec39678154">
