### ISSUE TITLE
Frequently crash using Remote with "Code: '5'"

### ISSUE THREAD

**Issue by Cloudac7** [microsoft/vscode#202910]
Type: <b>Bug</b>

1. Open a new Remote window.
2. Just edit the file and wait for a few minutes. 
3. Crashed with "Code: '5'" raised. 😭

<img width="273" alt="image" src="https://github.com/microsoft/vscode/assets/13016685/57dc3660-c993-4163-a353-061ca52a2d3e">

VS Code version: Code 1.85.2 (Universal) (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:32.531Z)
OS version: Darwin arm64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 5, 5|
|Memory (System)|16.00GB (1.10GB free)|
|Process Argv|--crash-reporter-directory /Users/cloudac7/Playground/tempdir/|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
github-actions-locally|alp|0.0.7
markdown-mermaid|bie|1.21.0
mermaid-markdown-syntax-highlighting|bpr|1.6.0
gitignore|cod|0.9.0
gitlens|eam|14.7.0
linter-gfortran|for|3.2.0
copilot|Git|1.152.662
copilot-chat|Git|0.11.1
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.2
markdown-image|han|1.1.36
vscode-drawio|hed|1.6.6
latex-workshop|Jam|9.18.0
vscode-docker|ms-|1.28.0
vscode-language-pack-zh-hans|MS-|1.85.2024011709
vscode-edge-devtools|ms-|2.1.3
autopep8|ms-|2023.8.0
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.9
azure-repos|ms-|0.38.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
wordcount|ms-|0.1.0
cp2k|nil|1.0.1
autodocstring|njp|0.6.1
material-icon-theme|PKi|4.33.0
java|red|1.26.0
vscode-yaml|red|1.14.0
code-spell-checker|str|3.0.1
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.43.0
vscode-icons|vsc|12.7.0
volar|Vue|1.8.27
zotero-cite|XIN|0.5.3
markdown-all-in-one|yzh|3.6.2
material-theme|zhu|3.16.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
0bi6i642:30933247
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

[dump_file.zip](https://github.com/microsoft/vscode/files/13996475/dump_file.zip)

**Comment by deepak1556** [comment]
Can you disable all extensions except the remote extensions and confirm if the crash happens ? Do you have a minimal repro which we can try ? Thanks!

**Comment by Cloudac7** [comment]
> Can you disable all extensions except the remote extensions and confirm if the crash happens ? Do you have a minimal repro which we can try ? Thanks!

Thanks. After disabled all the extensions, the crash not happened again. And I just disable the dracula theme and miracally no crash any more. Seems a issue related to dracula.
