### ISSUE TITLE
terminal issue in vsc

### ISSUE THREAD

**Issue by Parsaotk** [microsoft/vscode#202937]
ADD ISSUE DESCRIPTION HERE
terminal dont load and it works so slow
i have to wait more than 5 mins before i can type
Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed
