### ISSUE TITLE
installing vscode insiders on win 11, selecting option for context menu actions does not install the actions in context menus

### ISSUE THREAD

**Issue by derekriemer** [microsoft/vscode#202977]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: insiders, has been a specific insiders issues for as long as I have owned this machine.
- OS Version: ^Version 23H2 (OS Build 22635.3066)

Steps to Reproduce:

1. install vscode insiders from https://vscode.download.prss.microsoft.com/dbazure/download/insider/271fb7fbd599b49a1482ea7284a50b3229317f96/VSCodeUserSetup-x64-1.86.0-insider.exe
2. select options to get context menu right clicks.
3. right click a file once installed.
4. right click folder once installed.
Seems that the context menus don't get installed. I'm about to try reinstalling from the system installer not the user installer.

**Comment by derekriemer** [comment]
still happens after installing with the system insntaller. No idea why it just happens with installers for insiders.

**Comment by rzhao271** [comment]
@derekriemer does this issue still occur for you using an installer for VS Code 1.96 or later?
