### ISSUE TITLE
URL vscode://file/path/to/project/ is only able to open folders from the C: drive on Windows

### ISSUE THREAD

**Issue by StanislawStempin** [Microsoft/vscode#20290]
- VSCode Version: 1.9.1
- OS Version: Windows 10 Enterprise 14393.693

Steps to Reproduce:
1. Install VS Code
2. Create a folder D:/Temp
2. Run the following URL:  vscode://file/d/temp/

Expected result:
VS Code launches and opens folder D:/Temp

Actual result:
VS Code launches and says that folder /d/temp does not exist

**Comment by Tyriar** [comment]
I guess this is related to the windows CLI?

**Comment by joaomoreno** [comment]
Want to [attempt a PR](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/windows/electron-main/windowsService.ts#L267)?

**Comment by joaomoreno** [comment]
Thanks for the fix @jordanmkasla2009!

But actually went ahead with a simpler solution on top of yours. Instead of manipulating the strings we should just explicitly require the colon `C:` to be in the URI. So here's how URIs would work for Code:

```
vscode://file/c:/temp/
```

```
vscode://file/d:/temp/
```
