### ISSUE TITLE
Change icon for move to search panel in Quick Search

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#202906]
<img alt="image" src="https://github.com/microsoft/vscode/assets/31675041/54a5c499-c847-4f9b-9862-2d08ba5626fe">

From demoing, I got the feedback that the right arrow wasn't the best icon to use. I opted to use this icon throughout. However, I don't think it's necessarily the most descriptive icon for this case.

@hbons do you think that we could create a new icon that is like what is below, but with an arrow instead of a squiggle?
<img width="61" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/5df19e28-cfa2-427f-a032-b6af87f3bcc3">

I think that something like that would be good in this case. By the way, if you want to try out this feature to see whether the icon would actually fit, you can see how to do so here: https://code.visualstudio.com/updates/v1_82#_quick-access-text-search

_Originally posted by @andreamah in https://github.com/microsoft/vscode/issues/201735#issuecomment-1892894383_

**Comment by joanjeremiah** [comment]
Kindly assign this to me. I will work on it.

**Comment by andreamah** [comment]
Yes, that works! Thanks!
