### ISSUE TITLE
error calculating grade

### ISSUE THREAD

**Issue by brooklynsonge** [microsoft/vscode#202903]
We keep getting a "error calculating grade" message despite completing the task. 

Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Embedder: codespaces

**Comment by meganrogge** [comment]
Pls provide more information IE a screenshot next time. This is likely an extension issue.
