### ISSUE TITLE
Test: window specific zoom settings

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#202922]
Refs: https://github.com/microsoft/vscode/issues/185836

- [x] anyOS @bhavyaus
- [x] anyOS @alexr00

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23202922%0A%0A&assignees=bpasero)

---

A new setting `window.zoomPerWindow` is enabled by default that controls how the commands "Zoom In", "Zoom Out" and "Zoom Reset" apply to the active window or all windows:
* enabled: the commands only change the zoom level of the active window without writing to settings
* disabled: the commands write to the `window.zoomLevel` setting impacting all windows

**Testing:**
* verify the setting can be understood and enable if it not yet (should be enabled by default)
* open multiple windows with workspaces and some floating windows with editors
* zoom in/out/reset in each window and ensure zooming applies only to the active window
* verify the per-window zoom level restores as it was when you restart the application or reload the window
* when the window zoom differs from the `window.zoomLevel` setting, a status bar entry appears
* use the zoom status bar entry and make it sure it feels natural to you
* verify the window zoom status entry disappears when the window matches the configured zoom level
* with multiple windows having different per-window zoom, change the `window.zoomLevel` setting and verify all windows change to that level
* disable `window.zoomPerWindow`  and verify zooming applies to all windows as before

**Comment by alexr00** [comment]
> - disabled: the commands write to the `window.zoomPerWindow` setting impacting all windows

I think this is actually writing the `window.zoomLevel`, right?

**Comment by bpasero** [comment]
@alexr00 yes1
