### ISSUE TITLE
SSH connections with VS Code put my IP address on a blacklist (too many failed logins)

### ISSUE THREAD

**Issue by owenders** [Microsoft/vscode#20294]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. I open the built-in terminal.
2. I type my ssh command. I type the passphrase and type enter. The ssh connexion fails.
3. My website is not more accessible and my host informs me that my IP was blocked due to too many login attempts with ssh (IP blacklisted). On my request, my host unblocks my IP.
4. I try to connect via ssh with the standard terminal (MacOSX) and from there all is OK, the ssh connexion works.
5. When I try again from VS Code, the same problem appears: too many failed login attempts appears and IP blocked.

There is even a more bizarre behaviour: today, my IP was blocked after I launched VS Code, without any ssh connexion trial ! After having unblocked my IP, my host gave me the error message in its logs:

_csf.deny: 91.179.xxx.xxx # lfd: (sshd) Failed SSH login from 91.179.xxx.xxx (BE/Belgium/xxx.xxx-xxx-xx.adsl-dyn.isp.belgacom.be): 5 in the last 3600 secs - Thu Feb 9 11:15:12 2017_

And I din't try to connect via ssh. It is as if VS Code made attempts to connect via ssh autonomously and repeatedly when it is opened or when I type the ssh command. Here is the message that I see on my standard terminal after having succeeded to connect via ssh:

_Last failed login: Thu Feb  9 13:44:48 CET 2017 from 91.xxx.xxx.xxx on ssh:notty
There were 24 failed login attempts since the last successful login.
[user@world ~]$_

So there are 24 failed logins and I never made 24 attempts -> these attemps are automatic attempts.

Thank you in advance for your help.

**Comment by owenders** [comment]
I don't know if this is relevant but in order not to miss any information, I can add that I work in a project with a git repository and the connection to the remote repository is done by ssh (git remote add origin ssh://...). Maybe it's a problem with the git settings in VS Code (like a repeated automatic connection)...

**Comment by Tyriar** [comment]
What's in your settings.json file?

**Comment by owenders** [comment]
Since my last comment I tried to change some settings and it seems that the solution is to put git.autofetch to false (it is on true by default). The strange behaviour described above didn't repeat since then and my IP is not blocked anymore when I open VS Code. If this is the solution I would suggest to put this setting to false by default in the future release. Have you already heard about that behaviour (autonomous login attempts due to git.autofetch: true) ?

**Comment by joaomoreno** [comment]
`git.autofetch` to `false` is definitely the fix for you. I would not have that as the default as it benefits many more users than it causes issues to.

**Comment by owenders** [comment]
All right, thank you for your feedback :)
