### ISSUE TITLE
VS Code freezes

### ISSUE THREAD

**Issue by igordonxiao** [Microsoft/vscode#20299]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-swift-language|rlovelett|0.1.0|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please provide some information about the issue you are seeing and some repo steps.

Thanks

**Comment by igordonxiao** [comment]
1. open VSC, do some work in the editor
2. then switch to other programs
3. wait for sometime, about 20 mins
4. want to back to VSC and continue previous work, but VSC is not response, have to restart VSC

**Comment by joaomoreno** [comment]
Can you show us a screenshot of the state of VS Code when it does not respond?

**Comment by igordonxiao** [comment]
![2017-02-18 11 53 26](https://cloud.githubusercontent.com/assets/2564493/23109720/7a1ac88a-f756-11e6-8a53-30c8f822d569.png)

**Comment by bpasero** [comment]
@igordonxiao 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by igordonxiao** [comment]
@bpasero Ok, i'll try to remove extensions and feedback this issue.

**Comment by igordonxiao** [comment]
<img width="1023" alt="2017-02-21 9 25 46" src="https://cloud.githubusercontent.com/assets/2564493/23147446/eb391576-f819-11e6-8f17-4e1f90361bee.png">
I have removed all extensions, VSC was still not response for waiting sometimes.

**Comment by bpasero** [comment]
@igordonxiao does this even reproduce when you just have a simple file open with little content? Trying to understand if this is maybe related to the content of the editor you are seeing.

**Comment by igordonxiao** [comment]
@bpasero I keep some content in editor and didn't save it as a file, i did this behavior in older VCS versions, but worked well.

**Comment by csuwildcat** [comment]
I am seeing intermittent freezes while editing JS files on Windows 10, seemingly random without linkage to any user action. I have tried running without any plugins, and it still persists. Please advise.

**Comment by bpasero** [comment]
@igordonxiao is the contents you keep in the editor very large? does it reproduce with any content?

**Comment by igordonxiao** [comment]
@bpasero it's no relationship with the content is, just a few lines text. Now it did not occur again in new VSC version on my PC, maybe it has been fixed.
