### ISSUE TITLE
feature request: use ctrl-n and ctrl-p to move in the explorer window

### ISSUE THREAD

**Issue by louislarry** [Microsoft/vscode#20293]
Currently to select or move to next or previous items in the Explorer windows I have to use the mouse or arrow keys.

It would be great if I don't have to move my hand from keyboard move around the explorer window.  Ctrl-n for to move down and ctrl-p to move up would be great.

**Comment by bpasero** [comment]
This is already available from our insiders release. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

Duplicate of https://github.com/Microsoft/vscode/issues/11517
