### ISSUE TITLE
Add option to disable Tab switching picker

### ISSUE THREAD

**Issue by montogeek** [Microsoft/vscode#20295]
- VSCode Version: 1.9.1
- OS Version: OSX Sierra 10.12.4 Beta

At this moment when you hit Ctrl + Tab to switch to another tab a dialog appears:
![image](https://cloud.githubusercontent.com/assets/1002461/22784929/0d0ca1aa-eea0-11e6-91b6-eebfbdd76ff2.png)

I couldn't find an option to disable it.

It is possible to implement a configuration option to activate/disable it?

I am using Sublime Text Keymap

Thanks!

Steps to Reproduce:

1. Have 2 or more tabs open
2. Press Ctrl + Tab
3. See Tab switching dialog

**Comment by Tyriar** [comment]
@montogeek what do you expect to happen when ctrl+tab is pressed?

**Comment by montogeek** [comment]
Just show the other tab like Sublime or Atom

**Comment by chriswatt** [comment]
This tab switcher is a recent addition to vscode, to get the old behavour back where ctrl+tab/ctrl+shift+tab immediately switches to the next/previous tab without showing the popup, add the following to your keybindings.json

    // Place your key bindings in this file to overwrite the defaults
    [
        { "key": "ctrl+tab",         "command": "workbench.action.nextEditor" },
        { "key": "ctrl+shift+tab",   "command": "workbench.action.previousEditor"}
    ]

**Comment by Tyriar** [comment]
Thanks @chriswatt, closing since it's currently possible.
