### ISSUE TITLE
Jupyter notebook display error when maximizing panel size

### ISSUE THREAD

**Issue by szchixy** [microsoft/vscode#202974]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.2
- OS Version: MacOS Sonoma 14.2.1

Steps to Reproduce:

1. Open a jupyter notebook and a terminal panel

![WX20240122-124316@2x](https://github.com/microsoft/vscode/assets/56240054/4a86484d-1dea-4637-927e-486db432ff4c)

2. Maximize the panel size, and a line in jupyter will still display half of it in terminal panel

![WX20240122-124853@2x](https://github.com/microsoft/vscode/assets/56240054/5f53c9c3-0266-42db-ab39-39e61d9c3d05)

**Comment by rebornix** [comment]
Fixed in insiders and will be available in next Stable.
