### ISSUE TITLE
profiles get deleted when opening vscode from other machine

### ISSUE THREAD

**Issue by scarf005** [microsoft/vscode#202968]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.2 (Universal)
- OS Version: Darwin arm64 22.6.0

Steps to Reproduce:

1. create a new profile (linux).
2. ensure its settings are synced.
3. open vscode from work machine (mac).
4. new profile on work machine is not showing.
5. return back to original machine (linux).
6. new profile on original machine is also gone.

currently using `export profile > gist` to manually re-load profiles, but having to do this every day is a lot of work.

**Comment by sandy081** [comment]
Can you please share the settings sync log from both machines while this is happening. You can find the log here

- F1 > Open View... > Settings Sync

**Comment by scarf005** [comment]
wasn't able to get settings sync log from original machine, but this is the log from work machine (`Daangn` is the deleted profile in question)
[userDataSync.log](https://github.com/microsoft/vscode/files/14031157/userDataSync.log)

**Comment by sandy081** [comment]
From the machine where the profile is deleted, can you please share following

- F1 > Developer: Download Settings Sync Activity

**Comment by scarf005** [comment]
[Linux (Code) #2 - Settings Sync Activity.zip](https://github.com/microsoft/vscode/files/14045087/Linux.Code.2.-.Settings.Sync.Activity.zip)

this log is from my home machine.

additional context:
1. re-created profile `Daangn` on work machine
2. went back home, woke my home machine (from suspended state)
3. in my home machine, the profile `Daangn` was deleted.

**Comment by scarf005** [comment]
hi, this issue is persisting after i've upgraded vscode to 1.86.0, would there be anything i could help, e.g post more logs?

**Comment by m-thalmann** [comment]
Hi guys, I have the same exact issue. For me this issue does not happen each day, but still pretty often. I am switching between 3 different Windows machines.

![grafik](https://github.com/microsoft/vscode/assets/30590624/4aee839b-6b20-43bd-a5ce-25983e5a6e4d)

Also reverting the change does nothing.

**Comment by fischerjd** [comment]
My synced profiles are being deleted, also.  I work in higher ed and use vscode on multiple computers throughout the day. Each time I launch vscode, some of my profiles are *ALWAYS* deleted. It happens every time I launch vscode.

**Comment by usersina** [comment]
> this log is from my home machine.
> 
> additional context:
> 
> 1. re-created profile `Daangn` on work machine
> 2. went back home, woke my home machine (from suspended state)
> 3. in my home machine, the profile `Daangn` was deleted. settings sync activity: [Linux (Code) #2 - Settings Sync Activity.zip](https://github.com/microsoft/vscode/files/14045087/Linux.Code.2.-.Settings.Sync.Activity.zip)
> 4. went back to work, the profile `Daangn` was deleted in work machine as well. settings sync activity: [Mac (Code) #2 - Settings Sync Activity 1.zip](https://github.com/microsoft/vscode/files/14045860/Mac.Code.2.-.Settings.Sync.Activity.1.zip)

Same

**Comment by fischerjd** [comment]
I should also mention that when I have settings sync turned on, if I manually import a previously exported profile file (*.code-profile), the imported profile (within vscode) is automatically deleted almost immediately after it is imported.  For example: With settings sync turned on,

- I notice a previously created profile 'x' is missing / deleted.
- I manually recreate the missing 'x' profile by importing that profile's settings from a previously-exported profile file (x.code-profile).
- The imported profile 'x' briefly appears within vscode, but within a few seconds it disappears again.

**Comment by m3koenig** [comment]
Happend to me again. A really heavy used Profile...gone....
Thats is realy bad...now I have to reinstall all my extensions that I had.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/208710

**Comment by way-zer** [comment]
Are there any ideas how to get the profiles back?

**Comment by sandy081** [comment]
Unfortunately profiles cannot be restored.
