### ISSUE TITLE
Support referencing context key values in `window.title` template

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#202991]
Currently, `window.title` allows several variables.
It would be awesome for extensibility, if `${context.myContextVar}` would be supported, with `myContextVar` being an arbitrary context variable.

Then extensions could contribute to the window title (candidates would be `${context.debuggerStateEmoji}` or `${context.workspaceEmoji}`).

I'd be up to create a PR!

Related: #2809

**Comment by bpasero** [comment]
Sounds interesting, feel free to give it a try. The variables are substituted here:

https://github.com/microsoft/vscode/blob/8baf105cbd35e538d8133a857d4b4fede89f902c/src/vs/workbench/browser/parts/titlebar/windowTitle.ts#L287-L288

**Comment by weartist** [comment]
I'll try to submit a PR to fix this

**Comment by LEKPHET-KUNSUE** [comment]
anyone assign me pls

**Comment by benibenj** [comment]
Verification steps:
1. From an extension, create a contxt key and register a title variable
```
export function activate(context: vscode.ExtensionContext) {
    setInterval(() => 
        vscode.commands.executeCommand('setContext', 'timeNowContextKey', new Date().toLocaleTimeString()),
        1000
    );
    vscode.commands.executeCommand('registerWindowTitleVariable', 'timeNow', 'timeNowContextKey');
}
```
2. go to `window.title` in settings and add the newly created title variable (for example `window.title: "${timeNow}"`)
3. Make sure the window title correctly renders the value of the variable in the command center / window title area
