### ISSUE TITLE
Multiple processes were found matching the process name. attach by process id instead

### ISSUE THREAD

**Issue by abdou31** [microsoft/vscode#202933]
Type: <b>Bug</b>

I'm trying to attach a process to debug my application , but I got always the same error [ Razor application ( .NET 8 ) ] , this is my configuration ( Launch.json ).

![image](https://github.com/microsoft/vscode/assets/19480228/ff0a1e0d-9ba0-4e5b-ab74-c672a516b717)

```
// Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processName": "dotnet",

        }

    ]
}

```

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.17763
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|5.90GB (1.57GB free)|
|Process Argv|--crash-reporter-id 2e29cb29-ffc2-4d40-9f50-fe0a00611b42|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|17.1.0
code-gnu-global|aus|0.2.2
dart-code|Dar|3.80.0
vscode-chatgpt|gen|4.0.2
chatgpt-vscode|gen|0.0.10
Ionide-fsharp|Ion|7.17.0
csharpextensions|kre|1.7.3
dart-import|lua|0.3.1
vscode-clang|mit|0.2.4
csdevkit|ms-|1.2.7
csharp|ms-|2.15.30
dotnet-interactive-vscode|ms-|1.0.5069030
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
dart-syntax-highlighting-only|osc|1.0.1
LiveServer|rit|5.7.9
bootstrap4-vscode|the|6.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30933248
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019acf:30933242

```

</details>

**Comment by roblourens** [comment]
Please file this on the extension you're using to debug
