### ISSUE TITLE
wired grey area

### ISSUE THREAD

**Issue by suyuTech** [Microsoft/vscode#20292]
I try to move the cursor to different lines, but there is always some wired grey area. 

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.1.0

<img width="1152" alt="screen shot 2017-02-09 at 9 07 09 pm" src="https://cloud.githubusercontent.com/assets/13642123/22784563/74a989a2-ef0b-11e6-9cfd-763465db3887.png">
<img width="1148" alt="screen shot 2017-02-09 at 9 08 41 pm" src="https://cloud.githubusercontent.com/assets/13642123/22784606/a9d0747e-ef0b-11e6-8a24-d838ec234500.png">

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/12473
