### ISSUE TITLE
[xml] Closing XML element with namespace prefix generates element without local-name

### ISSUE THREAD

**Issue by filipetoscano** [microsoft/vscode#203]
The auto-generation of closing XML elements is incorrect if the open XML element has a namespace prefix such as `<xsl:text>`.

Observed behaviour:

``` xml
<xsl:text></xsl>
```

Expected behavior:

``` xml
<xsl:text></xsl:text>
```

**Comment by aeschli** [comment]
Autoclosing of xml tags is currently disabled. I'd like to bring it back at some point

**Comment by kanlukasz** [comment]
> 
> @aeschli 
> Autoclosing of xml tags is currently disabled. I'd like to bring it back at some point

Are there any new news about this? I ask because it's old case (2015)

**Comment by aeschli** [comment]
No plans to add more XML smartness to the built-in XML extension which just provides basic editing features. There are XML extensions that are better suited as they based on a proper parser.

Please have a look at what XML extension are out there and file an issue there if they are missing the feature.

**Comment by kanlukasz** [comment]
Ok.

If someone is looking for an extension to automatically close an xml element, i can recommend this one:
- https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag

If someone is looking for an extension to highlight matching xml tag, i can recommend this one:
- https://marketplace.visualstudio.com/items?itemName=vincaslt.highlight-matching-tag

If anyone have a better alternative, please let us know. Sharing is caring ❤️
