### ISSUE TITLE
Test: SCM - input field min/max lines setting

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#203034]
Refs: https://github.com/microsoft/vscode/issues/121452

- [x] anyOS @aiday-mar
- [x] anyOS @bhavyaus
- [x] anyOS @brettcannon (Optional)

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23203034%0A%0A&assignees=lszomoru)

---

This milestone we have added two new settings (`scm.inputMinLineCount` , `scm.inputMaxLineCount`) that allows users to control the number of min/max lines for the SCM input field. 

### Test plan
1. Launch the latest version of VS Code Insiders
2. Open a folder/workspace that contains a git repository
3. Open the "Source Control" view
4. Open the Settings editor
5. Update the value of the `scm.inputMinLineCount` setting
    * Confirm that the SCM input editor initial size updates accordingly
6. Update the value of the `scm.inputMaxLineCount` setting
7. Add multiple lines of text to the SCM input
    * Confirm that the SCM input grows accord to the setting value
8. Try other values for the settings and confirm that the SCM input updates accordingly

**Comment by brettcannon** [comment]
Shou
