### ISSUE TITLE
Connection to terminal's pty host process is becoming unresponsive

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/vscode#203002]
Type: <b>Bug</b>

The #130320 is still very much an issue.

I'm using integrated terminal to setup required tunnels and they stop working shortly after the view containing terminal is hidden. I have to go back to terminal and do something (like, press a space bar) to release the lock.

Using the same command in an external terminal works and tunnels stay alive for as long as connection to the remote host is stable.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (0.34GB free)|
|Process Argv|--folder-uri file:///d%3A/Profiles/anrdaemon/Documents/hk/invapi-php|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.5.2
vscode-intelephense-client|bme|1.10.2
vscode-eslint|dba|2.4.2
gitlens|eam|14.7.0
vscode-html-css|ecm|2.0.6
EditorConfig|Edi|0.16.4
vscode-firefox-debug|fir|2.9.10
todo-tree|Gru|0.0.226
composer|ika|0.8.0
better-shellscript-syntax|jef|1.6.3
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
hexeditor|ms-|1.9.12
powershell|ms-|2024.0.0
remote-explorer|ms-|0.4.1
sqltools|mtx|0.28.1
sqltools-driver-mysql|mtx|0.6.0
php-docblocker|nei|2.7.0
postman-for-vscode|Pos|0.18.0
tcl|ras|0.1.0
LiveServer|rit|5.7.9
html-to-css-autocompletion|sol|1.1.2
branch-in-window-title|wis|0.1.4
php-debug|xde|1.34.0
gitconfig-lsp|yy0|0.10.1

</details>

**Comment by meganrogge** [comment]
does this reproduce in insider's?

**Comment by AnrDaemon** [comment]
Also, please reopen https://github.com/microsoft/vscode/issues/198793
It's very annoying.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by AnrDaemon** [comment]
Yes, I can reproduce it with insiders build, even with fresh one.
This is somewhat tricky to reproduce, but a more or less reliable way of doing it is to spawn and close consoles.
Like, start the terminal with SSH session to establish tunnels.
Run a search task across the project (SilverSearcher, see #169381 btw), don't close the results window. Run build task (rsync to the dev. vm), run more build tasks over and over again.
Hide the view with terminals in between runs. At some point, the programs running in initial terminal get stuck and cease to pass the tunnel traffic around (rsync, mysql, xdebug - all gets hung trying to send data), the solution is to open the terminal with tunnels and do something in it. Press space bar for example.
Then it gets unstuck and everything works again until the next lock.

```
Version: 1.88.0-insider (system setup)
Commit: 61187a0b6547df5911a0ee259f7afda46bac7ec3
Date: 2024-03-04T05:46:35.204Z
Electron: 28.2.2
ElectronBuildId: 26836304
Chromium: 120.0.6099.276
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045
```
