### ISSUE TITLE
"open folder" dialog opens BEHIND the current window

### ISSUE THREAD

**Issue by php4fan** [microsoft/vscode#203001]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.86.0-insiders
- OS Version: Manjaro Linux (KDE)

I just installed VSCode Insiders with Snap, and this happens.

Steps to Reproduce:

1. launch Code
2. Go to file -> Open Folder

Expected:
The dialog for browsing and selecting a folder should open in the foreground

Observed:
the window opens behind the current window. If the current VSCode window is maximized or big enough, you won't even see the file browser window, and everything will look like VSCode simply froze.

I had been using VSCode on another machine with Manjaro linux previously and hadn't observed this issue, or at least it wouldn't normally happen. There I was using the version isntalled via Pamac (Manjaro's package manager) and it wasn't Insiders.
Either this is a difference between a snap installation and a traditional package installation, or somehow specific to Insiders, or a recent regression.

**Comment by php4fan** [comment]
I tried the package `visual-studio-code-insiders-bin`  from the AUR (currently version 1705642614-1) and it has the same issue.

Then I tried `visual-studio-code-bin` also from the AUR (version 1.85.2-1) and it works as expected.

In the version that works, the folder browsing window is grouped in the Task Manager together with the Visual Studio window. That is, when I'm browsing for folders, the Visual Studio Code icon in the task manager gets a "+" sign below it to indicate that it's a group that now  has more than one window. That's expected.

In the versions that have the issue, the popup window gets its own icon in the task manager. That's wrong. I suspect this might be related with the main issue.

**Comment by gjsjohnmurray** [comment]
@deepak1556 does this provide an additional datapoint for #146422?

**Comment by deepak1556** [comment]
The root issue is related to https://github.com/microsoft/vscode/issues/146422, merging to it. Please follow the issue for updates.

**Comment by php4fan** [comment]
>  Please follow the issue for updates.

If you marked this as duplicate of that one, instead of "not planned", people subscribed to this one would be automatically subscribed to that one.

BTW don't you think it's about time to unlock that one from comments? There's been no progress in almost two years.
