### ISSUE TITLE
Don't show the notebook variable view when not applicable

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#203068]
We should at least keep the view collapsed if a notebook controller isn't able to provide variables.
Also hide/disable the view if the setting is disabled at any point.

**Comment by DonJayamanne** [comment]
Unfortunately I cannot get the variables view to show up.

**Comment by DonJayamanne** [comment]
Install the github issues notebook extension
* OPen ipynb file and `Notebook Variables` view is displayed
* Open a gibuthubissues notebook and ensure the other ipynb is not visible
I would expect the `Notebook Variablers` view to be hidden.

**Comment by amunger** [comment]
I think we'll end up needing to show the variable more often for any open notebook and just showing the notebook variable source instead.
