### ISSUE TITLE
Test: `alert` in places with formerly just audio cues

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#203089]
Refs #195282

- [x] Windows @karthiknadig 
- [x] macOS @aiday-mar 
- [x] Linux @rzhao271 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23203089%0A%0A&assignees=meganrogge)

---

Braille users may or may not listen to audio cues. As such, we have added an `alert` in most places where there was formerly just an audio cue. Exceptions are made only for features which already do a dynamic alert (like chat response received). 

Enable a screen reader (because you do not have a braille device) in order to verify. Run the command `Help: List Alerts` or search for `accessibility.alert` in the settings UI. Test each to ensure that it works. 

Alerts and audio cues are not mutually exclusive. Make sure they work simultaneously.

**Comment by rzhao271** [comment]
I don't know how to set up a file to test the No Inlay Hints accessibility alert.
Apart from that and the filed issue, everything else LGTM.

**Comment by karthiknadig** [comment]
`alerts` work, but I ran into a bunch of unrelated issues with using Narrator.

**Comment by meganrogge** [comment]
@karthiknadig NVDA or Jaws are the ones we have the best support for
