### ISSUE TITLE
Test: Git - sign commit using SSH key with a passphrase

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#203070]
Refs: https://github.com/microsoft/vscode/issues/179517

- [x] macOS @justschen
- [x] linux @rzhao271
- [x] windows @hediet

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23203070%0A%0A&assignees=lszomoru)

---

This milestone we have added the capability to sign commits using an SSH key with a passphrase. In order to validate this test plan item I would like to suggest that you use a DevBox (Windows), or a VM (macOS, Linux) so that you do not make changes to your dev machine.

### Setup
GitHub has platform specific [documentation](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-signature-verification) that should help with your setup.
1. Create a new SSH key with a passphrase  - https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key. ⚠️ Please do not add the newly created SSH key to the ssh-agent as that would defeat the purpose of the feature.
2. Configure git to use the SSH key for signing - https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-ssh-key
3. In needed configure git and specify a name, and email address
4. Ensure that you are running Git 2.34 or later

### Sign Commit
1. Open Terminal and create a new folder
2. Run `git init` in the newly created folder
3. Launch the latest version of VS Code Insiders
3. Open the folder with the newly created git repository
4. Add a file to the folder, and make some changes to it
5. Click on the Commit button
    * Confirm that VS Code displays a quick input widget to enter the passphrase
6. Enter the passphrase and hit ENTER
    * Confirm that the changes were committed

**Comment by rzhao271** [comment]
I had to run the following command to get the password prompt to pop up:
`git config --global commit.gpgsign true`

Other than that, LGTM.
