### ISSUE TITLE
Quick fix menu pops up automatically when opening a file

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#20306]
- VSCode Version: Code - Insiders 1.10.0-insider (1c1f82e9722d2fafdbebb7524ac2cc465aafdfb4, 2017-02-09T11:45:48.163Z)
- OS Version: Windows_NT ia32 10.0.14986

Assuming you have an extension like this that provides a code action for every range in the document (same code as in #19562):

```ts
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    vscode.languages.registerCodeActionsProvider('haxe', {
        provideCodeActions(doc, range, message) {
            return [{
                title: doc.getText(range),
                command: ""
            }];
        }
    });
}
```

The quick fix menu pops up automatically whenever I open a file (in seemingly random places, but always with the first word in the document):

![](http://i.imgur.com/9DFiguL.gif)

Note that this already happened in the previous Insider's build before @jrieken's fix for #19562 (definitely a regression compared to 1.9.x however).

**Comment by Gama11** [comment]
I just realized that the Insider's build does not contain the for #19562 yet actually.

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/20306#issuecomment-278671630 - yeah, fixed that just before lunch

**Comment by jrieken** [comment]
ok - this is a regression from #19371

**Comment by jrieken** [comment]
I pushed a fix to properly trigger the light bulb on start/reload not the menu... Sorry for the hassle.

**Comment by Gama11** [comment]
Wow, that was quick! 👍
