### ISSUE TITLE
node protocol probing confuses electron

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#20301]
- Use this program test.js:
  ```js
  let i = 0;
  setInterval(() => {
	console.log('hello: ' + i++);
  }, 1000);
  ```
- download current Electron, e.g. on macOS https://github.com/electron/electron/releases/download/v1.4.15/electron-v1.4.15-darwin-x64.zip 
- run from command line with `./Electron.app/Contents/MacOS/Electron --debug=6009 test.js`
- attach VS Code with this config:
  ```json
  {
	"type": "node",
	"request": "attach",
	"name": "Attach to Process",
	"address": "localhost",
	"port": 6009,
	"protocol": "legacy"
  }
  ```

Observe: a debug session starts and if you set a breakpoint the program will stop and hit the breakpoint. 

- stop session
- change `protocol` to `auto`
- attach VS Code again

Observe: a message "Debugging with legacy protocol because Node version could not be determined." shows up in the debug console but no debug session starts.

Turning on tracing sends this to the debug console:
```json
Debugging with legacy protocol because Node version could not be determined.
62796: _attach: address: 127.0.0.1 port: 6009
62796: _attach: connected
62796: _terminated: socket end
62796: _terminated: node v8protocol close
62796: _terminated: socket error
62796: _terminated: node v8protocol error
62796: _terminated: node v8protocol error
62796: disconnectRequest: send response
```

So it looks like that the probing leaves the debug port in a strange state which prevents node-debug from connecting to that port successfully. 

When using 'node' instead of 'Electron', VS Code attaches successfully.

Trace output in this case:
```json
Debugging with legacy protocol because Node version could not be determined.
62843: _attach: address: 127.0.0.1 port: 6009
62843: _attach: connected
62843: _initialize: got process id 62839 from node
62843: _injectDebuggerExtensions: frame based code injection failed with error 'No frames'
62843: _injectDebuggerExtensions: global code injection successful
62843: _startInitialize: stopped: false
62843: _startInitialize: no entry event after 10 retries; giving up
62843: _startInitialize2: fire initialized event
62843: _startInitialize2: in attach mode we guess stopOnEntry flag to be 'false''
62843: _startInitialize2: remember to do a 'Continue' later
62843: setFunctionBreakPointsRequest: result []
62843: setExceptionBreakPointsRequest: ["uncaught"]
62843: configurationDoneRequest: do a 'Continue'
```

**Comment by roblourens** [comment]
This is interesting, I can repro it just by using a web browser too.

- `"protocol": "legacy"`
- Start electron
- Navigate to `http://localhost:6009`
- It responds with the following:
```
Type: connect
V8-Version: 5.3.332.47
Protocol-Version: 1
Embedding-Host: Electron
Content-Length: 0
```
- Start the debug session - see the same thing as when using 'auto'

**Comment by roblourens** [comment]
Oh, it just thinks the request is from a debugger. Then it probably thinks it's already attached and doesn't want to talk to a second debugger.

**Comment by roblourens** [comment]
I see that message is still sent again when the debugger connects. It just closes the socket after sending that message. And looking at the code - https://github.com/electron/electron/blob/22b21d04bdbb43be52a90a3b05fdbd9b4278feea/atom/browser/node_debugger.cc#L148 - it looks like it wouldn't send the message again if it thought it was already attached to a debugger. I don't see anything here that explains why it's closing the socket.

**Comment by roblourens** [comment]
I can't figure it out. I'd have to build Chromium to investigate deeper. A couple options:

- Flip it around and test for the legacy protocol first by opening a socket to the address/port. We should be able to disconnect cleanly before attaching for real from the debug adapter. And I've tested that it doesn't screw up an inspector protocol instance. The socket gets this message: 
```
"HTTP/1.0 400 Bad Request
Content-Type: text/html; charset=UTF-8

WebSockets request was expected
```
and is closed. And I can then attach with node2.

Do you think this is safe?

- Or, we'll have to not do version probing for attach. In this case, I would actually consider looking at port numbers and assuming that 5858 is legacy, and 9229 is inspector, as you proposed before.

**Comment by roblourens** [comment]
My PR implements the first option. It actually doesn't work for Electron right now - it gives the same problem as above when the debug adapter attaches. But I can't figure out why, because it's doing exactly the same thing to disconnect as the debug adapter, which has no problem connecting and disconnecting to electron multiple times. I must be missing a step.

**Comment by weinand** [comment]
@roblourens since the PR doesn't help with Electron, I suggest that we do not "rush" this and investigate more in the next milestone.

**Comment by roblourens** [comment]
Fixed: https://github.com/Microsoft/vscode-node-debug/commit/921b313d192feecf27f53fe5bd6b7cff2543db01

**Comment by michelkaporin** [comment]
Trying to verify it, steps described by @weinand still result in "Debugging with legacy protocol because Node version could not be determined" message without no subsequent debugger attaching. In fact, it does not attach simply in `auto` setting for `protocol` at all.

**Comment by weinand** [comment]
Not critical since our Electron launch configuration snippet sets the protocol to 'legacy' explicitly.

**Comment by roblourens** [comment]
I did find a mistake in my code, but even fixing that, I get the same result. But it does work with Electron 1.5-1.6 regardless, so I'm tempted to leave it.

**Comment by roblourens** [comment]
Not concerned about this anymore
