### ISSUE TITLE
Smooth scroll not working with mouse wheel in latest `1.86.0-insider` on `MacOS`

### ISSUE THREAD

**Issue by Cow258** [microsoft/vscode#203099]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.0-insider
- OS Version: Darwin arm64 23.1.0

Visual Studio Code - Insiders version
```
Version: 1.86.0-insider
Commit: e244acbb172c428cb219717a07bf55d2737492ca
Date: 2024-01-22T05:36:53.351Z (21 hrs ago)
Electron: 27.2.1
ElectronBuildId: 26149897
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.1.0
```

## Steps to Reproduce:
1. Open a long file
2. Start scroll with mouse wheel

## Expected
> This is VSCode 1.85.2

https://github.com/microsoft/vscode/assets/14261588/36ab7c35-abb5-42c1-8e16-8e80b458bc55

## Currently
> This is VSCode Insiders 1.86

https://github.com/microsoft/vscode/assets/14261588/2fa63ca1-0817-4d4b-b310-ed7fa4941171

**Comment by alexdima** [comment]
We have a `MouseWheelClassifier` [here](https://github.com/microsoft/vscode/blob/feff7c8a7e1c82320380f42d898a1e03051fefb7/src/vs/base/browser/ui/scrollbar/scrollableElement.ts#L45) which looks at the `StandardWheelEvent.deltaX` and `StandardWheelEvent.deltaY` and divides those values by the device pixel ratio to guess if the event came from a physical mouse wheel. 

This milestone we have changed `StandardWheelEvent.deltaX` and `StandardWheelEvent.deltaY` via https://github.com/microsoft/vscode/pull/200776 to already be divided by the device pixel ratio so we need to adjust the logic in `MouseWheelClassifier` to account for that.

**Comment by aiday-mar** [comment]
Since the PRs to fix this issue have been merged, I will close this issue.

**Comment by Cow258** [comment]
I just updated to latest Insiders release this morning and verified this issue has been fixed successfully. Thanks a lot. 👍🏻
