### ISSUE TITLE
Syntax Highlighting in ES template strings inconsistent

### ISSUE THREAD

**Issue by luchsamapparat** [Microsoft/vscode#20307]
- VSCode Version: 1.9.1
- OS Version: Windows 10 Version 1607

Steps to Reproduce:

1. Create a new JavaScript file
2. Paste the following code:

```js
const func1 = (path) => someFunc(`log some ${path}.`);
const func2 = (error) => someFunc(`log some ${error}.`);
```

For some reason the `path` variable is not blue whereas the `error` variable is. When I rename `path` to something else, it becomes blue. If I change it back, it is red again.

![image](https://cloud.githubusercontent.com/assets/875017/22789082/4acda07e-eee2-11e6-99fa-6816766acce9.png)

(In the screenshot I added a third line to check if the position within the file makes any difference)

Not really a big issue, but irritating :)

EDIT: I tested it without any extensions using `code --disable-extensions`. So I'm sure it's not an extension-related issue.

**Comment by mjbvz** [comment]
I believe this is fixed in the current insiders builds:

<img width="453" alt="screen shot 2017-02-09 at 12 34 56 pm" src="https://cloud.githubusercontent.com/assets/12821956/22802056/3525882c-eec4-11e6-9816-d10a6e534ec1.png">
