### ISSUE TITLE
Settings "search.include"

### ISSUE THREAD

**Issue by evanlemke** [microsoft/vscode#203063]
There is a setting "search.exclude", but not "search.include".  

My problem is that `search.exclude` inherits from `files.exclude`.  I would like to be able hide linter configuration files like `.prettierrc`, while still being able to quick open or search in them.
```
{
  "files.exclude": {
    ".node-version": true,
    ".prettierrc": true,
  },
  "search.exclude": {
    "**/node_modules": true
  },
  "search.include": {
    ".prettierrc": true,
  }
}
```

This is very similar #55271 but it was closed in favor of #869.  #869 does not address this use case because the files.exclude inheritance can not be pattern matched against.

I would like to see either
- the ability to disable search.excludes inheritance of files.exclude
- a stand alone search.include setting

**Comment by andreamah** [comment]
Please contribute to this discussion in https://github.com/microsoft/vscode/issues/869. Although your use case is different, the implications and implementation of a `search.include` should also consider the use cases that others have for creating more advanced file/search globbing. Thanks!

/duplicate https://github.com/microsoft/vscode/issues/869
