### ISSUE TITLE
[loc][Query][VSCode] Please clarify placeholders

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20308]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
{0} Group {1}.

File Name:
src\vs\workbench\browser\parts\editor\textEditor.nls.resx

Resource ID:
".resx", 0; "editorLabelWithGroup"

Query:
Please clarify placeholders. What do tehy stand for?

**Comment by bpasero** [comment]
I will probably change this to be: `{0}, Group {1}`

The first variable is the name of the editor and the second is in which group the editor is shown. This is used for screen readers so that people can hear in which group an editor is opened.
