### ISSUE TITLE
Feature request: Make wrappingColumn setting available in showCommands list

### ISSUE THREAD

**Issue by Bill-Stewart** [Microsoft/vscode#20305]
- VSCode Version: 1.9.1

It would be nice to be able to quickly and dynamically change the `wrappingColumn` setting during editing by selecting it from the `showCommands` list (<kbd>F1</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) and entering a new wrapping value.

**Comment by Tyriar** [comment]
You could write an extension that does this quite easily now.

**Comment by Bill-Stewart** [comment]
I had some time to do this...

https://marketplace.visualstudio.com/items?itemName=BillStewart.set-wrapping-column
