### ISSUE TITLE
Test markdown url pasting

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#203095]
Test for #188871

- [x] Mac @aiday-mar
- [x] Linux @roblourens
- [x] Windows @bamurtaugh

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23203095%0A%0A&assignees=mjbvz)

---

## Summary
This iteration we re-enabled the markdown paste url as link feature. When you copy text that looks like a url and paste it into a markdown file, this feature will automatically transform it into a markdown link: `[link text](http://example.com)`

## Testing
Test out this feature in some markdown files . I've detailed the expected behavior below but please also let me know if something feels wrong when using this feature

**Default Behavior**
- This feature should only be enabled if you are pasting a uri
- If you have text selected when pasting, a markdown link should be created
- If you do not have text selected, the url should be pasted but you should also see an option to paste as a markdown link in the editor
- Pasting as a markdown link should also be disabled inside of markdown code blocks and html blocks

**Advanced**
- The `markdown.editor.pasteUrlAsFormattedLink.enabled` setting controls this behavior
- If you set `"markdown.editor.pasteUrlAsFormattedLink.enabled": "smart"`, then you should no longer need a selection to paste a markdown link (however markdown links should still be disabled in code blocks and other elements)
- Regardless of `markdown.editor.pasteUrlAsFormattedLink.enabled`, the `paste as...` command should always work
- All of this should also work in markdown cells in notebooks

**Comment by roblourens** [comment]
Should the "Paste as" command have a "markdown link" option? I only see plain text and HTML.

**Comment by roblourens** [comment]
Also, it might be nice to have a mode where it never inserts markdown links by default, but does show the paste widget which gives me the option. With `"never"`, I don't see that widget.

**Comment by mjbvz** [comment]
@roblourens `Paste as` currently only shows this open if you have a valid url in the clipboard. If you have copied a url and still aren't seeing the option, please open an issue. I also considered always showing it but that kind of overlaps with our existing markdown link snippet
