### ISSUE TITLE
Test: start/stop terminal voice commands

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#203087]
Refs #199128

- [x] Windows @amunger 
- [x] macOS @hbons 
- [x] Linux @rzhao271 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23203087%0A%0A&assignees=meganrogge)

---

There are two new commands, `Terminal: Start Terminal Voice` and `Terminal: Stop Terminal Voice`. They have no default keybindings. For testing purposes, I suggest configuring some. 

Once a voice session has been started, it should respect the value of `accessibility.voice.speechTimeout`. 

Create terminals, focus them, and start / stop voice sessions. Verify the visual indicators make sense and work correctly on start/stop. Enable a screen reader. Verify that the text is announced via an aria alert upon completion. 

Disclaimer: due to the disconnect between natural language and that of the terminal, this is not super useful ATM.

**Comment by hbons** [comment]
Seems to all work correctly. I can verify that changing accessibility.voice.speechTimeout works, and the VoiceOver also announces the text that was inserted after the timeout.
