### ISSUE TITLE
Debugging node breakpoints not working

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode#20300]
- VSCode Version: 1.10.0-insider #1c1f82
- OS Version: Windows 10

Steps to Reproduce:

1. Launch node app with --debug or --debug-brk
2. Attach debugger

Debug console says **Debugging with legacy protocol because Node version could not be determined.** Break points not working. Has been doing this for a few days.

`debugger` statement works reliably. Breakpoints added through UI work inconsistently. I'm not able to determine what scenarios make them work or not work, but I just noticed the "legacy protocol" error today and assumed it was related.

Tried with node 5.5.0 and 6.9.5

**Comment by weinand** [comment]
@jamietre Please add `'protocol': 'legacy'`or `'protocol': 'v8-inspector'` to your launch config and see whether this makes a difference.

**Comment by ianwesterfield** [comment]
Same here, however `debugger;` not working either. Unable to attach specifying either `protocol` `legacy` or `v8-inspector`, only `auto` attaches with breakpoints seeming to be registered.

macOS: 10.12.3
node:     6.9.1 (also tried 6.9.5)
vscode: 2.2.1-insiders.20170209

**Comment by jamietre** [comment]
@weinand this removes the error message, but break points still are not working. They show up as "verified" but the only way I can get the debugger to stop is with `debugger`.

**Comment by cmrigney** [comment]
I'm having the same issue with 1.9.1

**Comment by cmrigney** [comment]
Here's our launch config.  Notice we are using nodemon so maybe that has something to do with my problem.

```
{
      "name": "Debug All With Reload",
      "type": "node",
      "request": "launch",
      "stopOnEntry": false,
      "cwd": "${workspaceRoot}/",
      "preLaunchTask": null,
      "runtimeExecutable": null,
      "runtimeArgs": [
        "--nolazy",
        "${workspaceRoot}/lib/node_modules/nodemon/bin/nodemon.js",
        "${workspaceRoot}/debugall.js",
        "--config",
        "${workspaceRoot}/nodemon.json"
      ],
      "env": {
        "NODE_ENV": "development"
      },
      "sourceMaps": false,
      "outDir": null,
      "console": "integratedTerminal",
      "skipFiles": [
        "<node_internals>/**",
        "**/node_modules/**"
      ]
    },
```

**Comment by jamietre** [comment]
I've tried with and without nodemon, makes no difference.

**Comment by weinand** [comment]
@jamietre please don't make your problem bigger by using "nodemon". Ignore @cmrigney's launch config as his problem is most likely unrelated.

**Comment by jamietre** [comment]
Don't worry, I'm not ;) I try to simplify as much as possible before reporting a bug  - i was just trying to respond to his comment that he **was** using nodemon.

**Comment by weinand** [comment]
@jamietre could you share your launch config?

**Comment by jamietre** [comment]
Note - I am *not* using compounds for the purposes of this problem - just plain "attach"

```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}\\dist\\dev\\server.js",
            "restart": true
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach To Node",
            "address": "localhost",
            "restart": true,
            "protocol": "legacy"
        },
        {
            "name": "Launch Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:5000/",
            "webRoot": "${workspaceRoot}/dist"
        }
    ],
    "compounds": [
        {
            "name": "Debug Full App",
            "configurations": ["Attach To Node", "Launch Chrome"]
        }
    ]
}
```

**Comment by weinand** [comment]
I cannot reproduce this problem on Windows 10 with the Insiders release of VS Code.
Are you using some form of transpilation and forgot to add an `outFiles` attributes?
The fact that server.js lives in a dist folder seems to indicate this.

**Comment by jamietre** [comment]
You are absolutely right - I can't believe I didn't notice that. So sorry to have taken your time on this - apparently someone, possibly me, accidentally broke the config.
