### ISSUE TITLE
YAML

### ISSUE THREAD

**Issue by jgreeneclarity** [microsoft/vscode#203064]
Type: <b>Bug</b>

1.85.2 shows incorrect YAML errors, specifically seeing column spacing errors that are incorrect

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1365U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.38GB (4.87GB free)|
|Process Argv|. --crash-reporter-id 6c5b89a9-5bce-4a83-9a0f-e9975521f11c --crash-reporter-id 6c5b89a9-5bce-4a83-9a0f-e9975521f11c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
pip-packages|etm|0.4.3
node-module-intellisense|lei|1.5.0
Angular-BeastCode|Mik|10.0.3
vscode-docker|ms-|1.28.0
csharp|ms-|2.15.30
vscode-dotnet-runtime|ms-|2.0.0
vscode-kubernetes-tools|ms-|1.3.15
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.9
vscode-remote-extensionpack|ms-|0.25.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.8.22
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
vscode-yaml|red|1.14.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
pretty-ts-errors|Yoa|0.5.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30933247
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019acf:30933242

```

</details>

**Comment by aeschli** [comment]
VS Code has no built-in YAML extension that does diagnostic reporting.

The errors are likely coming from the `vscode-yaml` extension. Please file the issue there.
