### ISSUE TITLE
[css] show error for CSS `@import` in invalid location

### ISSUE THREAD

**Issue by GrantGryczan** [microsoft/vscode#203098]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.2
- OS Version: N/A

[As explained on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@import#description), `@import` at-rules MUST be at the start of the file (with some exceptions).

VS Code does not show an error when this requirement is not followed. On the other hand, Chrome's source editor, for example, does show an error for this:

![image](https://github.com/microsoft/vscode/assets/14056899/c2b300dd-9b48-4e69-a03e-0e48c11743ba)

Steps to Reproduce:

1. Open a CSS file.
2. Paste the following into the file.

```css
body {
    background-color: darkblue;
}

@import url("https://example.com/style.scss");
```

3. Observe that there is no error.

(Note that, in SCSS, this should _not_ produce an error, because SCSS moves `@import` rules to the top when compiling to CSS.)

This matters to me because I want to use Monaco Editor on my website to allow for custom CSS. My website already allows custom CSS via a plain `textarea`, and users often make the mistake of using `@import`s not at the start of the stylesheet, with no indication that it won't work. I expected this to be warned against by Monaco Editor, but it isn't.

**Comment by GauravB159** [comment]
I can work on this if no one else is currently working on it

**Comment by aeschli** [comment]
The CSS language validation is quite limited and only reports syntax errors. IMO for more its best to run a linter.

Closing as out-of-scope
