### ISSUE TITLE
Test hold gesture for speech

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#203012]
Refs: https://github.com/microsoft/vscode/issues/201330

- [x] anyOS @eleanorjboyd
- [x] anyOS @lszomoru
- [x] anyOS @TylerLeonhardt

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23203012%0A%0A&assignees=jrieken)

---

As a _requirement_ you need to have the speech extension (`ms-vscode.vscode-speech`) installed. Make sure you see microphone buttons in inline chat or panel chat input boxes

For inline chat we have added gestures that allow you to hold down keys for "listening mode". This complements the microphone button that you can already use today. Make sure that

* when you press and hold `cmd+i` inline chat starts and goes into listening mode. When releasing the keys, listening stops and the request is made
* start inline chat normally (press and release `cmd+i` or via the context menu) and now hold `cmd+i` and make sure listening mode works
* make sure the microphone buttons reflects the current state of the microphone, e.g its shines blue'ish once it records
* check that the delay after which listening mode starts feels right, not too short, not too long

In addition to the inline chat enhancement there is also a new quick chat mode with a lighter UI. This more experimental but ready for feedback. 

* press `cmd+k` and hold `i` (this is a "holding chord") and make sure a microphone is rendered with the text.
* make sure the microphone goes from grey to blue pulsing which indicates it's listening
* speak and ensure the spoken words are printed 
* release the key and make sure the request is made
* make sure no request is made when you focus out while recording 
* make sure no request is made when hitting ESC while recording
* press (without hold) `cmd+k i`, talk, and select `cmd+k i` again for stop recording and make request

**Comment by lszomoru** [comment]
Great work. I love the new quick chat mode 👏🏻
