### ISSUE TITLE
Visual Studio Code is closed but code.exe processes are still running and consuming CPU

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#20302]
- VSCode Version: 1.9.0
- OS Version: Windows 8.1 x64

Not sure how to reproduce stably. Here's [an archive with dumps](https://cloud.mail.ru/public/FhZ5/t97nexEnp).

![untitled](https://cloud.githubusercontent.com/assets/4777512/22787906/f46f3b7c-eeee-11e6-9738-f148d0473337.png)

**Comment by DavidA2014** [comment]
I have also seen this. I mentioned it in https://github.com/Microsoft/vscode/issues/20280.

**Comment by mikyladewitt** [comment]
I have the same problem, but much greater. I have 42 instances still running. VS Code is shut down. 

VS Code Version: 1.9.0-insider
OS Version: Windows 7

I don't know if it's related at all, but I've run into the following issues within the last 24 hours:

*  Tried to update a couple times yesterday and each time had to abort the upgrade because I had other files that was locking the files needed by the update. 
* Very frequently getting the message, from vs code I believe, saying the window is unresponsive and asking if I'd like to reload the window. I've had to reload pretty much everytime I leave the vscode for a longer period while not actually opening/using vscode. 

Could either of these situations possibly have leaked the running processes?

![vscodeprocesses](https://cloud.githubusercontent.com/assets/1285448/22798284/34d44182-eeb6-11e6-8492-05b4746c25e2.png)

**Comment by Tyriar** [comment]
This may be the terminal (https://github.com/Microsoft/vscode/issues/18990), do you two use it? It may also be search?

**Comment by mikyladewitt** [comment]
@Tyriar I definitely use search. Frequently. 

I sometimes use terminal, but I don't _think_ I did at all in the last couple of days so I don't think that would have affected this. Unless running build tasks counts as using terminal. I know it shows the terminal output from the task, normally typescript compilation in my case, but sometimes grunt tasks.

**Comment by Tyriar** [comment]
Build tasks only count as the integrated terminal if you set "_runner": "terminal" in your `tasks.json`. @roblourens could this be recent search changes?

**Comment by mikyladewitt** [comment]
@Tyriar Okay I do not have that set so that should rule terminal out for my root cause.

**Comment by roblourens** [comment]
Can you both do the following to help us figure out which process it is?

- In Task Manager, right click the column headers and click "Select columns"
- Scroll down and check "Command line"
- Expand the column so we can see the full command line, and show us or copy it in to github?

Thanks

**Comment by Deilan** [comment]
Here you are! And yep, the count of hanging processes increased since the last time. :) I may additionaly collect dumps if you tell me how to do it correctly.

![untitled](https://cloud.githubusercontent.com/assets/4777512/22831284/d85012fa-efba-11e6-8ac0-6928b8d0d14f.png)

**Comment by roblourens** [comment]
That's like, one of everything. So it kind of looks like it just didn't shut down or something?

Since the extensionHost is using CPU, is there some way that could be keeping it open? I doubt it, but does anything else close if you just kill the extensionHost process?

**Comment by mikyladewitt** [comment]
Sorry for the delay, here's my processes with the Command Line column if you still need it. VS Code was shut down before getting this.

![vscodeprocessescmdline](https://cloud.githubusercontent.com/assets/1285448/23030075/80bd7f12-f421-11e6-8d26-dcf47333e8b5.png)

**Comment by Deilan** [comment]
One more. v.1.9.1.

![image](https://cloud.githubusercontent.com/assets/4777512/23444929/15f2cdf4-fe49-11e6-8886-3cede7b20c2d.png)

@roblourens After killing extensionHost process, the other processes shut down as well. No idea what keeping it open so far. But here's my list of extensions:

![image](https://cloud.githubusercontent.com/assets/4777512/23445030/ab8c2eb4-fe49-11e6-96a6-474cbf331dd3.png)

**Comment by Deilan** [comment]
Keeps reproducing in v.1.10.0.

**Comment by Aides359** [comment]
Having the same problem on Windows 10 with 1.11.1.
More than 10 instances were still open, 3 of them using around 30% CPU load each, rendering me completely unable to work before realizing and killing the processes.

**Comment by Tyriar** [comment]
Does this reproduce for people when you run using `code --disable-extensions`?

**Comment by Aides359** [comment]
Any idea on how to systematically test for it? 
A lot of my extensions help me with my productivity and I don't like the thought of disabling them for an unspecified time.

**Comment by Tyriar** [comment]
@Aides359 not sure if there's a better way to rule out extensions as the culprit other than by disabling them temporarily (or a subset of suspected ones).

**Comment by jludvice** [comment]
Hello, it looks like the same think happens also on Fedora 25.
I close `code` but there are still some processes running, consuming lot of CPU.

```bash
$ ps aux | grep '/usr/share/code'
jludvice 25469 60.0 13.8 2621664 1662052 ?     Rl   08:26  98:48 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=searchService
```

does `--type=searchService` provide any userful hint?

**Comment by Tyriar** [comment]
@roblourens looks like it's the searchService?

**Comment by roblourens** [comment]
Which command produced the second output? What does it mean that there are a bunch of searchService procs nested under the first searchService proc? @chrmarti Looks like there is a long-running `find` process.

**Comment by boldwade** [comment]
I'm noticing this lately... I don't have 42 instances running after close, but I'll see at least 1 to two instances of vscode running that take approximately 30% of my cpu... AFTER I close vscode for up to 30 minutes afterwards... WTF.

**Comment by roblourens** [comment]
@boldwade Can you open a new issue with the details of those processes? I can give some tips if you tell me which OS you're on.
