### ISSUE TITLE
[loc][query][VSCode] Please clarify "typings"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20309]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Acquiring typings definitions for IntelliSense.
Acquiring typings...

File Name:
extensions\typescript\out\features\completionItemProvider.nls.resx

Resource ID:
".resx", 0; "acquiringTypingsDetail"
".resx", 0; "acquiringTypingsLabel"

Query:
Can you please clarify what is referred to by "typings" and whether it is translatable?

**Comment by mjbvz** [comment]
`typings` refers to the `*.d.ts` typings files that power our IntelliSense. I don't think it should be localized
