### ISSUE TITLE
launch.json not used when debugging Python unit tests

### ISSUE THREAD

**Issue by jordanca42** [microsoft/vscode#203081]
Type: <b>Bug</b>

Since upgrading the 1.85.2, it appears that the launch.json file is not used when debugging Python unit tests using the unittest framework. Below is my launch.json
```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Current File",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "purpose": ["debug-in-terminal"],
      "console": "integratedTerminal",
      "justMyCode": true,
      "env": {
        "PYTHONPATH": "${workspaceFolder}"
      }
    },
    {
      "name": "Python: Debug Tests",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "purpose": ["debug-test"],
      "console": "integratedTerminal",
      "justMyCode": false,
      "env": {
        "PYTHONPATH": "${workspaceFolder}"
      }
    }
  ]
}
```
When debugging, I need to add my workspace folder to the Python path. This is working as expected when debugging in the terminal. However, when debugging unit tests, I can add the following code to my test
```python
import sys
print(sys.path)
```
and see that the workspace path is not being added.

This was working previously. I don't know what version I had before 1.85.2 was auto-installed.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7542 32-Core Processor                 (4 x 2895)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (4.51GB free)|
|Process Argv|--folder-uri file:///c%3A/repos/python-framework --crash-reporter-id 5d80ae5c-1369-41ef-ad5f-42c215c9dfe5|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.4
gitlens|eam|14.7.0
prettier-vscode|esb|10.1.0
ReactCodeSnippets|haz|1.2.1
mypy|mat|0.3.0
black-formatter|ms-|2023.6.0
pylint|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
powershell|ms-|2024.0.0
autodocstring|njp|0.6.1
sas-lsp|SAS|1.6.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30933247
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by roblourens** [comment]
Please file this on the Python extension repo, thanks
