### ISSUE TITLE
Test: let Code Actions contribute highlight range

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#203092]
Refs: https://github.com/microsoft/vscode/issues/199608

- [x] anyOS @paulacamargo25 
- [x] anyOS @bamurtaugh 
- [x] anyOS @alexr00 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23180757%0A%0A&assignees=justschen)

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23203092%0A%0A&assignees=justschen)

---

## Overview
A proposed API that allows Code Actions to contribute a `Range` for affected lines in the editor, which will highlight those affectd lines.

The following is the structure of the proposed API: 
```ts
	export interface CodeAction {
		/**
		 *
		 * The range to which this Code Action applies to, which will be highlighted.
		 *
		 * Ex: A refactoring action will highlight the range of text that will be affected.
		 */
		ranges?: Range[];
	}
}
```

> dts can be found at https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.codeActionRanges.d.ts

You can use this in your extension by adding this to your extension manifest (package.json):
```json
"enabledApiProposals": [
    "codeActionRanges"
  ],
```
and then run: `npx vscode-dts dev` which will fetch the proposed API and allow you to see types.

## To test
1. Must have an external extension with this API adopted, contributing a Code Action. If you have a personal extension to test on, fantastic. If not, check out [this extension's implementation](https://github.com/Yoyokrazy/clean-nb-imports-ext/blob/74f23aabe58925270d81906d3d1ddfcd40b84452/src/extension.ts#L47C8-L47C9)
2. Once the extension is installed/adopted the API, double check that when highlighting with cursor, the selected lines are highlighted. Note: if there is no code in that line, it will not be highlighted.

## Some things to make sure:
* Due to how `Range` is implemented, the contributed `Range` is 0-based, while `IRange` (which it is converted to) starts at 1.
 

Let me know what you think overall!

Note: you must adopt this in an external extension (not a built-in to VS Code one)

**Helpful links**
* [Your First Extension](https://code.visualstudio.com/api/get-started/your-first-extension)
* [Using Proposed API](https://code.visualstudio.com/api/advanced-topics/using-proposed-api)

**Comment by alexr00** [comment]
This is a nice API addition. It makes it much clearer for the todo code action provider that the reason we're suggesting the action is because there's a "todo" comment.

**Comment by paulacamargo25** [comment]
Agree with Alex, this way the code actions are easier to understand and the user has a way to see what has been modified. Great job 👍
