### ISSUE TITLE
Test application label in port notification

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#203023]
Refs: https://github.com/microsoft/vscode/issues/192684

- [x] dev container @chrmarti
- [x] dev container @chrisdias

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23203023%0A%0A&assignees=alexr00)

---

0. Make sure you have `"remote.autoForwardPorts": true`
1. Make a devcontainer.json that includes some `portsAttributes` with a label. For example, https://github.com/microsoft/vscode-remote-try-node/blob/main/.devcontainer/devcontainer.json does this.
2. Connect to your container and start your application
3. Verify that the notification that tells you your port was auto forwarded also includes the label from the `portsAttributes`.

**Comment by chrisdias** [comment]
lgtm
