### ISSUE TITLE
[WelcomeUX] Option to not open Welcome when opening a folder

### ISSUE THREAD

**Issue by mtebele** [Microsoft/vscode#20303]
When you open a recent project from the welcome screen, the last one remains opened in a tab.

- VSCode Version: 1.9.1
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. Open a new VSCode window.
2. Open a recent project from the welcome screen.
3. The project is opened and the welcome screen remains opened.

**Comment by chrmarti** [comment]
The current behavior was chosen in the hope that this would help new users by staying in the same context.

**Comment by kh0m** [comment]
I agree that the welcome screen should be closed after taking an action from it. Especially in my case, where I prefer to use the `"window.openFoldersInNewWindow": "on"` setting, having to close the otherwise empty welcome window after opening from the 'Recents' list or via File>Open feels like a bug.

**Comment by chrmarti** [comment]
You can just not show it at all. Or do you need any of the actions on it? (I'm trying to preserve the new user experience here which relies much more on guidance.)

**Comment by mtebele** [comment]
It's ok showing the welcome screen, but it should be closed after opening a project from there.

**Comment by chrmarti** [comment]
With #32416 we change the Welcome editor to open in preview mode, this way it will close when the next editor opens. (If preview mode is not disabled in settings.)

**Comment by chrmarti** [comment]
This could be an additional value for the `"workbench.startupEditor"` setting.

**Comment by uppe-r** [comment]
Hey, I could look into this. Got any tips on where I should start?

**Comment by chrmarti** [comment]
@uppe-r Great:
- Add an additional enum literal here: https://github.com/Microsoft/vscode/blob/a8b2950a12378abe6eadaa526c014bc8f257cb8f/src/vs/workbench/parts/welcome/page/electron-browser/welcomePage.contribution.ts#L23
- Check for that literal and the 'open folder' condition here: https://github.com/Microsoft/vscode/blob/a8b2950a12378abe6eadaa526c014bc8f257cb8f/src/vs/workbench/parts/welcome/page/electron-browser/welcomePage.ts#L81

**Comment by chrmarti** [comment]
You could use `welcomePageInEmptyWorkbench`. Check for no folder being open: `contextService.getWorkbenchState() === WorkbenchState.EMPTY`. You can get at the context service by adding it to the constructor of the calling class, similar to: https://github.com/Microsoft/vscode/blob/315299eddf233816ee36fe183b30f27fd841afab/src/vs/workbench/parts/extensions/electron-browser/extensionsViewlet.ts#L293

**Comment by uppe-r** [comment]
Hey @chrmarti everything seems to be working now, just one last question which is confusing me: isn't the objective of this issue to NOT show the Welcome Page when opening a new project? So why is your enum suggestion welcomePageInEmptyWorkbench?

**Comment by chrmarti** [comment]
@uppe-r Show it *only* in the empty workbench. :)

**Comment by uppe-r** [comment]
Now I'm getting `Unable to open 'Welcome': Cannot read property 'getWorkbenchState' of undefined.` upon opening a new window (empty workbench). Any ideas?

I did the comparison as you said for no folder being open.

**Comment by chrmarti** [comment]
Is the `contextService` `undefined`? You can debug it either in VS Code or in the Developer Tools (Help > Toggle Developer Tools in the window running from source).

**Comment by uppe-r** [comment]
Upon opening a new window, it isn't undefined (verified by a console log) but then it turns undefined (verified by the same console log).
