### ISSUE TITLE
Multi-Cursor Editing Collides with Windows 10 Screen Rotation

### ISSUE THREAD

**Issue by gigocabrera** [Microsoft/vscode#20304]
- VSCode Version: 1.9.1
- OS Version: Windows 10

Multi-Cursor Editing states that you can press Ctrl+Alt+UpArrow or Ctrl+Alt+DownArrow to add a new cursor above or below. HOWEVER, Windows Windows 10 Screen Rotation hotkey is also Ctrl+Alt+Up so when I try to follow the instructions in VS CODE, my whole windows screen flips

Steps to Reproduce:

1. Press Ctrl+Alt+Up or Ctrl+Alt+Down in Windows 10. The screen will flip. 

There may be ways to prevent this in Windows 10, but it sure is confusing if you have never seen this behavior before.

**Comment by Tyriar** [comment]
I believe this is to do with graphics drivers which you can disable. You can also rebind the keys https://code.visualstudio.com/docs/customization/keybindings#_customizing-shortcuts

**Comment by bakshi629** [comment]
problem is that you use keyboard shortcuts in your graphics card(intel,amd)
turn off screen rotation

**Comment by michael-hawker** [comment]
@Tyriar why is it different than the VS default of Shift+Alt?  Then there'd be no conflict on these systems.

**Comment by Tyriar** [comment]
@michael-hawker maybe VS intercepts it at a lower level? We get key events from Chromium so there are probably differences in how the key events are fetched.
