### ISSUE TITLE
Hiding activity bar actions from custom title, hides the activity bar

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#203159]
Testing #202857

Somehow when I explicitly want to hide activity bar icons from custom title, I am forced to hide the activity bar.

![Recording 2024-01-23 at 16 06 38](https://github.com/microsoft/vscode/assets/900690/726de71f-4b04-4c16-8547-62c39b9d93c4)

**Comment by benibenj** [comment]
We don't allow hiding from title bar context menu anymore. https://github.com/microsoft/vscode/pull/203142
