### ISSUE TITLE
[loc][query][VSCode]  Please clarify "Welcome experience"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20318]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
When enabled, will show the Welcome experience on startup.

File Name:
src\vs\workbench\parts\welcomePage\electron-browser\welcomePage.contribution.nls.resx

Resource ID:
".resx", 0; "welcomePage.enabled"

Query:
In this contect, "experience" seems to be the page that have "welcome" page function. Please confirm.

**Comment by chrmarti** [comment]
Yes, that is correct. When enabled the Welcome page will be shown in an editor tab right after startup.

**Comment by chrmarti** [comment]
I will replace "experience" with "page" here. Thanks.
