### ISSUE TITLE
Changes made to file are not showing in Git

### ISSUE THREAD

**Issue by lingeshnafeax** [microsoft/vscode#203135]
Type: <b>Bug</b>

I am currently working on a Data Science project . Till today morning any changes i make to a file will be showed on the Git extension.But now even if i make changes it is not showing in the git extension

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz (4 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.74GB (0.86GB free)|
|Process Argv|C:\\Users\\wling\\OneDrive\\Desktop\\Lingesh\\DataScience --crash-reporter-id 4e9fac89-7400-46f0-a8a0-3947dad655df|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-django|bat|1.15.0
path-intellisense|chr|2.8.5
doxdocgen|csc|1.4.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
prettier-vscode|esb|10.1.0
code-runner|for|0.12.1
vscode-pull-request-github|Git|0.78.1
gc-excelviewer|Gra|4.2.58
vsc-python-indent|Kev|1.18.0
black-formatter|ms-|2023.6.0
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.9
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
autodocstring|njp|0.6.1
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|4.33.0
autoimport|ste|1.5.4
tex-preview|tia|0.0.4
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.3
vscode-maven|vsc|0.43.0
jinja|who|0.0.8

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30933248
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019acf:30933242

```

</details>

**Comment by lszomoru** [comment]
@lingeshnafeax, thanks for filing this issue. There are couple of known issues related to the Source Control view that have already been fixed in VS Code Insiders. Would you be able to try that out? You can download it from https://code.visualstudio.com/insiders/.
