### ISSUE TITLE
Use metadata from browser when copying

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#203177]
Testing #203095

If I copy a URL from Edge and paste into Obsidian, it pastes this text: `[Test markdown url pasting · Issue #203095 · microsoft/vscode (github.com)](https://github.com/microsoft/vscode/issues/203095)`. I was expecting something like that, but in vscode I am just prompted to enter text myself.

**Comment by mjbvz** [comment]
Unfortunately this data doesn't seem to make it up into the browser paste event's `clipboardData`. We only get the `text/plain` content

Possibly falls under https://bugs.chromium.org/p/chromium/issues/detail?id=1029857
