### ISSUE TITLE
[loc][query][VSCode] Please clarify the strings

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20314]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Commit Staged
Commit Staged (Signed Off)

File Name:
extensions\git\package.nls.resx

Resource ID:
".resx", 0; "command.commitStaged"
".resx", 0; "command.commitStagedSigned"

Query:

Does this string means "commit has been staged?" or "commit the staged information/data". Thanks.

**Comment by joaomoreno** [comment]
It means "Commit the staged files", in which "Commit" is a verb.
