### ISSUE TITLE
Revisit name "Custom Title Bar"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#203161]
Testing #202857

![image](https://github.com/microsoft/vscode/assets/900690/0d174168-5b80-47b2-9d7b-6dfbe0667ec9)

I wonder if "Custom Title Bar" really hits it when native title is enabled. I wonder if in that case we should rather name it "Commands Bar" (not "Tool Bar"). But I think its not a custom title bar, since it actually does not contain the title, only command center and actions.

//cc @sandy081 @hbons

**Comment by benibenj** [comment]
Personally I prefer keeping the name "Custom Title Bar" as I think it might be easier for users to discover and understand instead of changing the name depending on the titleBarStyle setting.

**Comment by sandy081** [comment]
I do not like calling it differently in different platforms or with different configurations. In Mac and Windows we are already calling this custom titlebar. We should have same name everywhere.

**Comment by bpasero** [comment]
I can be convinced if others feel strong about it, so feel free to leave it for now.
