### ISSUE TITLE
[loc][query][VSCode] Please clarify "mocha"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20317]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Debug mocha tests

File Name:
package.nls.resx

Resource ID:
".resx", 0; "node.snippet.mocha.description"

Query:

Could you please confirm "mocha" should remain untranslated?

**Comment by Tyriar** [comment]
Yes, mocha is a testing framework https://mochajs.org/
