### ISSUE TITLE
Why not an API for openIssueReporter?

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#203150]
Testing https://github.com/microsoft/vscode/issues/203094

What is the benefit of doing the Issue Reporter via a command, compared to introducing an API?
Using the current command looks complex, and does not offer intelli-sense to extension authors.

fyi @TylerLeonhardt @jrieken

**Comment by karthiknadig** [comment]
I agree with this. It is difficult to make sense of what should be passed in.

**Comment by justschen** [comment]
We had a lot of discussion about the value of the API vs potentially just making a better version of the command. Wanted to get some eyes/implementations of this to see how the command would do vs. the API so we could get some more discussion on it for sure! 

appreciate the feedback as always, and will keep iterating on this

**Comment by rootsmusic** [comment]
I suggest integrating [Github Issue Notebooks](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks), without needing to install an extension.

**Comment by justschen** [comment]
closing, tracking the rest in https://github.com/microsoft/vscode/issues/196863
