### ISSUE TITLE
Show the repository name when only one repository is shown in a mulit-repository workspace

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#203147]
Testing #203035

- Open mulit-repository workspace
- Close all repositories except one
- Hide Source Control Repositories view
- Displayed Source Control view does not inform about the repository it belongs to

<img width="516" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/d20188bf-99be-43a7-87e1-56180e323783">

**Comment by lszomoru** [comment]
This behaviour is "by-design". When the folder/workspace contains only one opened repository, we do not show the repository elements in the Source Control view by default. This can be controlled using the `scm.alwaysShowRepositories` setting.
