### ISSUE TITLE
View screen cheese: no icons, titles with UUIDs

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#203131]
Checkout the screen capture below which shows totally broken views. Notice the view title in the bottom panel and the missing icon the secondary sidebar (in my setup the secondary sidebar is left, the primary is right). I suspect this is due to setting/view sync because I have connected a windows VM

<img width="1494" alt="Screenshot 2024-01-23 at 12 10 56" src="https://github.com/microsoft/vscode/assets/1794099/194bbbfc-3e6c-4767-89c3-72fb19aff39a">

**Comment by sandy081** [comment]
Have you tried clicking on those broken views and found out what those views are?

**Comment by sandy081** [comment]
Analysed the data provided by @jrieken and this is what happened

- Windows machine has some obsolete custom view containers state (in pane composite bar) which we are not cleaning up . When sync started, this machine has pushed this state, for eg:

```
"workbench.views.service.panel.c1326001-ecc5-4d53-a89f-1f5ff03f1197.state.hidden": {
			"version": 1,
			"value": "[{\"id\":\"timeline\",\"isHidden\":false}]"
		},
{\"id\":\"workbench.views.service.panel.c1326001-ecc5-4d53-a89f-1f5ff03f1197\",\"pinned\":true,\"visible\":true}
```
- Mac machine has accepted this state and started rendering this obsolete view container even though this does not exist.

This seems to be a bug in pane composite bar that render view containers - it is rendering obsolete view containers placeholders even though they do not exists in the model.

**Comment by benibenj** [comment]
verified by code review
