### ISSUE TITLE
Should enabling command center or actions bring back custom title?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#203163]
Testing #202857

I am on macOS and have custom title explicitly hidden, and use native tabs. When I go to settings and enable command center, I would have expected the custom title to appear.

**Comment by benibenj** [comment]
There are a couple of weird behaviours if we do so. My preferred approach would be to remove the setting for command center and layout actions and make them UI State.

**Comment by bpasero** [comment]
I am not sure, you would have to talk to stake holders of these features.

**Comment by bpasero** [comment]
@benibenj what exactly did you push for?

**Comment by bpasero** [comment]
@benibenj following those steps, chat command center does not seem to come back for me

**Comment by rzhao271** [comment]
It works for me. I have Title Bar Style set to custom and Native Tabs set to true. When I re-enable Command Center, I see the command center in the top-center of the window.
