### ISSUE TITLE
Vscode crashs

### ISSUE THREAD

**Issue by Tanimou** [microsoft/vscode#203195]
Type: <b>Performance Issue</b>

Since this morning, I can't properly work in vscode without interruption. Vscode keeps crashing and reloading

VS Code version: Code - Insiders 1.86.0-insider (800e60abdfb1675a59520bac6a9473bc380d49ea, 2024-01-23T06:12:41.150Z)
OS version: Windows_NT x64 10.0.23619
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.11GB free)|
|Process Argv|--crash-reporter-id 7f788c3c-9b80-464e-a1f6-86d200419551 --crash-reporter-id 7f788c3c-9b80-464e-a1f6-86d200419551|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   100	 20408	code-insiders main
    0	    40	  5576	ptyHost
    0	     5	  4104	     C:\WINDOWS\System32\cmd.exe
    0	     6	  5400	     C:\WINDOWS\System32\cmd.exe
    0	     6	  8452	     C:\WINDOWS\System32\cmd.exe
    0	     8	 10024	     conpty-agent
    0	     8	 15168	     conpty-agent
    0	     8	 15980	     conpty-agent
    0	     5	  7492	   crashpad-handler
    0	   124	  7728	   gpu-process
    0	    60	 12292	shared-process
    0	    15	 17852	   utility-network-service
    1	   445	 20560	window [9] (planning_order.py - Odoo16 - Odoo Development - Visual Studio Code - Insiders [Administrator])
    0	    85	 21948	fileWatcher [9]
   14	   897	 23772	extensionHost [9]
   19	     8	  2800	     electron-nodejs (devcontainer.js devcontainer.js devcontainer.js )
    0	    11	 11568	       C:\WINDOWS\system32\conhost.exe 0x4
    0	   225	 10156	     c:\Users\HP\.vscode-insiders\extensions\sourcery.sourcery-1.15.0\sourcery_binaries\active\sourcery.exe lsp
    0	    11	 12044	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    87	 11920	     electron-nodejs (server.js )
   13	    39	 12096	     "c:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules.asar.unpacked\@vscode\ripgrep\bin\rg.exe" --hidden --no-require-git --ignore-case -g **/* -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/Thumbs.db -g !**/.classpath -g !**/.project -g !**/.settings -g !**/.factorypath -g !**/node_modules -g !**/bower_components -g !**/*.code-search --no-ignore-parent --follow --crlf --engine auto --regexp (?:[\S\s]|\r?\n)+ --no-config --no-ignore-global --json --multiline -- .
    0	    11	 24396	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    86	 12736	     electron-nodejs (server.js )
    0	   115	 14024	     electron-nodejs (server.js )
    0	   157	 19228	     electron-nodejs (agent.js )
    0	    87	 20060	     electron-nodejs (serverMain.js )
   15	     8	 21336	     electron-nodejs (devcontainer.js devcontainer.js devcontainer.js )
    0	    11	 21732	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    99	 25256	window [10] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (planning_order.py - Odoo16 - Odoo Development - Visual Studio Code - Insiders [Administrator])
|    Folder (Odoo16): more than 25035 files
|      File types: po(10653) py(2603) xml(1431) js(527) png(505) pyc(451)
|                  pot(197) svg(124) csv(120) scss(112)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: python;
```

</details>
<details><summary>Extensions (141)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
format-selection-as-html|adr|2.3.0
project-manager|ale|12.7.0
zip-extract-all|Anc|1.2.0
smarty-template-support|asw|2.1.1
html-extentions-pack|bou|0.3.0
vscode-animations|Bra|2.0.1
multi-cursor-case-preserve|Car|1.0.5
catppuccin-vsc|Cat|3.11.0
catppuccin-vsc-icons|Cat|0.33.0
path-intellisense|chr|2.8.5
codestream|Cod|15.0.1
gitignore|cod|0.9.0
vscode-office|cwe|3.1.8
quicktype-refresh|dog|1.0.2
git-extension-pack|don|0.1.3
githistory|don|0.6.20
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
apc-extension|drc|0.3.6
css-flexbox-cheatsheet|dzh|3.3.4
git-cheatsheet|dzh|1.4.4
gitlens|eam|2024.1.1904
vscode-html-css|ecm|2.0.7
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.4.0
prettier-vscode|esb|10.1.0
vscode-github-notifications-bell|fab|2.3.1
git-project-manager|fel|1.8.2
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
docker-explorer|for|0.1.7
pythonsnippets|frh|1.0.2
vscode-image-gallery|Ger|1.2.1
codespaces|Git|1.16.7
copilot|Git|1.153.668
copilot-chat|Git|0.12.2024012301
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.79.2024012309
gc-excelviewer|Gra|4.2.58
pyscript|Har|0.1.1
vscode-test-explorer|hbe|2.21.1
vscode-test-explorer-liveshare|hbe|1.0.5
helium-icon-theme|hel|1.0.0
docker-linter|hen|0.5.0
vscode-git-tags|how|1.4.4
output-colorizer|IBM|0.1.2
mysql-syntax|jak|1.3.1
better-dockerfile-syntax|jef|1.0.2
better-js-syntax|jef|0.0.2
better-shellscript-syntax|jef|1.6.3
OdooSnippets|jig|1.5.0
python-essentials|Jil|0.0.3
sass-color-transformation|jjv|0.0.4
svg|joc|1.5.3
vscode-peacock|joh|4.2.2
vsc-python-indent|Kev|1.18.0
vscode-gutter-preview|kis|0.30.0
git-tree-compare|let|1.16.0
vscode-python-test-adapter|lit|0.8.1
vsls-whiteboard|los|0.0.12
MagicPython|mag|1.1.0
docker-extension-pack|mag|1.0.0
start-git-bash|McC|1.2.1
rainbow-csv|mec|3.11.0
template-string-converter|meg|0.6.1
python-path|mge|0.0.14
vscode-language-babel|mgm|0.0.40
gitignore|mic|1.0.1
inline-fold|moa|0.2.6
prettify-json|moh|0.0.3
vscode-docker|ms-|1.28.0
vscode-edge-devtools|ms-|2.1.3
vscode-postgresql|ms-|0.3.0
black-formatter|ms-|2023.9.10231018
debugpy|ms-|2023.3.13341008
isort|ms-|2023.13.10231012
python|ms-|2023.25.10221012
vscode-pylance|ms-|2023.12.104
remote-containers|ms-|0.335.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.9
vscode-remote-extensionpack|ms-|0.25.0
azure-repos|ms-|0.39.2023121101
js-debug-nightly|ms-|2024.1.2217
live-server|ms-|0.4.13
powershell|ms-|2024.0.0
remote-explorer|ms-|0.5.2024011009
remote-repositories|ms-|0.41.2023121801
remote-server|ms-|1.6.2024012309
test-adapter-converter|ms-|0.1.9
vscode-typescript-next|ms-|5.4.20240122
vsliveshare|ms-|1.0.5905
vsliveshare-audio|ms-|0.1.93
odoo-scaffold|mst|0.1.4
color-highlight|nau|2.5.0
vs-html-to-css|nep|1.0.0
back-n-forth|nic|3.1.1
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
docker-compose|p1c|0.5.1
material-icon-theme|PKi|4.33.0
git-file-history|pom|1.0.1
python-string-sql|ptw|1.2.0
sqlite-viewer|qwt|0.3.13
vscode-rapidapi-client|Rap|1.10.2
vscode-services|rap|1.0.2
vscode-yaml|red|1.14.0
synthwave-vscode|Rob|0.1.15
git-merger|sha|0.4.1
background|sha|1.2.13
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.8.11
git-autoconfig|shy|0.0.2
vsc-quokka-statusbar|ske|1.3.6
gitignore-generator|sle|0.0.2
vscode-zipexplorer|sle|0.3.1
sourcery|sou|1.15.0
guides|spy|0.9.3
teamhub|Tea|17.0.4
docker-essentials|Tec|0.3.0
git-essentials|Tec|0.3.0
branch-warnings|tel|1.0.10
pdf|tom|1.2.2
errorlens|use|3.16.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-pack|vsc|0.25.15
quokka-vscode|Wal|1.0.616
footsteps|Wat|0.5.0
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
five-server|yan|0.3.1
material-theme|zhu|3.16.2
vscode-open-in-github|ziy|1.3.6

(11 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vsc_aa:30263845
vscod805:30301674
vsaa593cf:30376535
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
b5d27386:30943795
fegfb526:30945144

```

</details>

**Comment by Tanimou** [comment]
![image](https://github.com/microsoft/vscode/assets/91100433/a18b8434-658a-46d5-a08e-25a5454eb21c)
Here is a screenshot that may help

**Comment by deepak1556** [comment]
Does the issue repro when you run with extensions disabled, you can run the command `Profile: Create a Temporary Profile` ?

If the issue does not repro with extensions disabled, please try to narrow down the problematic extension by running the following command `Help: Start Extension Bisect`

**Comment by Tanimou** [comment]
I tried the extension bisect command and looks like the extension Open in Github, Bitbucket, Gitlab (ziyasal) causes the issue
