### ISSUE TITLE
Improve Turning on Settings Sync experience when a setting change triggers restart

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#203141]
I'm usually a Windows user, but I set up a Linux VM for testing. While setting up setting sync on this VM I was interrupted by a restart prompt:

- Opened VS Code for the first time on Linux
- Saw the ugly native title bar and changed the setting to custom title bar.
- This required a restart of VS Code, so I restarted
- Then, I enabled settings sync.
- Setting sync said there were conflicts, so I replaced local
- This changed the title bar setting back to native, which required a restart again
- I said, yes, restart. Then another modal dialog showed asking if I wanted to cancel turning on setting sync.

**Comment by sandy081** [comment]
Restart dialog related to settings change is postponed until turning on settings sync is finished.
