### ISSUE TITLE
speech recording stops after log pause in audio

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#203189]
Testing #203012

1. Use cmd+i to speak into microphone and generate text
2. release cmd+i and have a request fulfilled
3. re-press cmd+i, this now adds text to the end of your request
4. continue to hold cmd+i but pause speaking for a few seconds
5. 🐛 although I am holding cmd+i, the microphone stops listening and triggers a request with the speech I have said, prematurely fulfilling my request

https://github.com/microsoft/vscode/assets/26030610/fe191805-a7f6-4de4-83a2-1682f79c9194

**Comment by jrieken** [comment]
This comes from here: [acceptTranscriptionScheduler](https://github.com/microsoft/vscode/blob/3aa161859aca5bcca03fddd6f1e18c19b5071e2f/src/vs/workbench/contrib/chat/electron-sandbox/actions/voiceChatActions.ts#L317) and can be configured via `accessibility.voice.speechTimeout`. Maybe for the hold gesture tho this should be disabled?

**Comment by bpasero** [comment]
Yes I think it should be disabled in this case, I can see to add some kind of option maybe.

**Comment by bpasero** [comment]
My understanding is that the command is executed from here:

https://github.com/microsoft/vscode/blob/905ed4ffd5f5ac218de334cfd330e567968a241e/src/vs/workbench/contrib/inlineChat/electron-sandbox/inlineChatActions.ts#L98

We could say that an argument can be passed that controls this. There already is a notion of `IChatExecuteActionContext`:
https://github.com/microsoft/vscode/blob/905ed4ffd5f5ac218de334cfd330e567968a241e/src/vs/workbench/contrib/chat/browser/actions/chatExecuteActions.ts#L15-L18

I wonder if we should enrich and use that context or introduce something else?

**Comment by jrieken** [comment]
Yeah, that what I was thinking. Pass some toggle to disable the timeout behaviour

**Comment by bpasero** [comment]
💪 for tomorrow
