### ISSUE TITLE
Markdown url pasting doesn't work with file URI

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#203180]
Testing #203095

Pasting this URI: `file:///Users/rob/code.txt` it is underlined as a link but I don't get the new behavior.

**Comment by mjbvz** [comment]
Currently only enabled for `http(s)` and `mailto`. We use an allow list to prevent any text with a colon from getting treated as a uri

`file` is kind discouraged for markdown but it's easy enough to add it to the list for consistency

**Comment by roblourens** [comment]
This is released? I don't see a change in the latest insiders 1091f68d834974d78cd4f9769034b4ae4581ff2a

**Comment by mjbvz** [comment]
Release but just realized this is till broken for a some common cases of uris. Proper fix ended up being a little more risky than anticipated so pushing to next iteration
