### ISSUE TITLE
Git stash view doesn't show added or moved files

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#203190]
Testing #203040

- Create a git stash that includes a new file, or a renamed file
- "View stash"
- The editor only shows modified files, and there is no indication that some content is missing

<img width="442" alt="image" src="https://github.com/microsoft/vscode/assets/323878/4b81e8b1-a69e-4ccc-939e-5b94e454280f">
<img width="305" alt="image" src="https://github.com/microsoft/vscode/assets/323878/7806a062-282e-4755-bb5f-4ba30511d8ec">
<img width="887" alt="image" src="https://github.com/microsoft/vscode/assets/323878/cf61dbfd-d136-4052-b211-abc76899d041">

**Comment by roblourens** [comment]
Maybe the pattern is that it only shows files that currently exist in the workspace. If I delete `test.js`, then "View stash", I don't see that file either.

**Comment by lszomoru** [comment]
@hediet, could you please take a look at this. I have checked and the git extensions is passing all files but it does look like the multi-file diff editor does not display all of them. Let me know if I need to change anything in the git extension. Thanks!

**Comment by eleanorjboyd** [comment]
still seeing this,
<img width="1725" alt="Screenshot 2024-01-25 at 8 31 59 AM" src="https://github.com/microsoft/vscode/assets/26030610/d2a71206-82ac-4da9-9c1a-6a9b3150584a">
<img width="1728" alt="Screenshot 2024-01-25 at 8 31 44 AM" src="https://github.com/microsoft/vscode/assets/26030610/b2e43037-9510-4e78-a54b-6a7fe5fbc378">
<img width="650" alt="Screenshot 2024-01-25 at 8 32 13 AM" src="https://github.com/microsoft/vscode/assets/26030610/379ccdfc-a304-4e73-b7a4-ac3b81fe1c0e">

**Comment by lszomoru** [comment]
@eleanorjboyd, when you have untracked filed you have to use the "Git: Stash (Include Untracked)" command otherwise the untracked files are not being included in the stash.
