### ISSUE TITLE
[loc][query][VSCode] Please clarify "executable"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20313]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Cannot determine executable for debug adapter '{0}'.

File Name:
Cannot determine executable for debug adapter '{0}'.

Resource ID:
".resx", 0; "debugAdapterCannotDetermineExecutable"

Query:
Does "executable" in this string mean a executable file or other? Thanks.

**Comment by isidorn** [comment]
I have pushed a clarification. Yes executable as an executable file.
