### ISSUE TITLE
microphone stays on during mac popup

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#203187]
Testing #203012

The first time I attempted to use voice, I held down the key and the inline chat popped up with the microphone icon but due to it being my first time, I also got a pop up from my mac to enable use of microphone by VS Code. The one minor issue is as I clicked "allow" on that prompt and returned to VS Code the microphone was still on and listening. I then had to go and click to turn it off. A small issue but could lead to confusion around if cmd+i needs to be held or not since holding did not impact the microphone being on during this loop

**Comment by jrieken** [comment]
There is an issue with keybindings not seeing the keyup-event when having lost focus but I am also surprised that the icon changes to listening before granting OS-level access

**Comment by jrieken** [comment]
To reproduce run this `tccutil reset Microphone com.microsoft.VSCodeInsiders` which reset the "answer" state

**Comment by jrieken** [comment]
The interesting bit is that we get the `Started` event despite the modal being pending. @bpasero I guess this also affects your UI elements

<img width="1000" alt="Screenshot 2024-01-24 at 19 30 53" src="https://github.com/microsoft/vscode/assets/1794099/39db64d9-bd8e-42e6-ad9b-e507e1297809">

**Comment by bpasero** [comment]
Good finding, but the SDK gives me no hint (or I miss something). Reported as https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2238
