### ISSUE TITLE
Stuck with "unsaved changes" in multi-diff editor

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#203186]
Testing #203040

- Disable autosave
- Open a file, make some change, don't save
- Open a stash in multi-file diff editor
- The diff editor is marked as unsaved and I can't close it at all
- If I close the original editor, the multi file diff can be closed

![Recording 2024-01-23 at 13 47 41](https://github.com/microsoft/vscode/assets/323878/f6112d3b-8f98-4b05-b45f-9953cc333402)

**Comment by lszomoru** [comment]
@hediet, could you please take a look at this one. Thanks!
