### ISSUE TITLE
Hide Activity Bar actions in the custom tool bar is hiding the activity bar

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#203120]
Hiding the activity bar actions in the custom tool bar should not hide the activity bar. Instead it should just hide the activity bar actions in the custom tool bar

<img width="402" alt="image" src="https://github.com/microsoft/vscode/assets/10746682/f7a73a12-20d5-4329-b046-1aac3e5e57cc">

**Comment by benibenj** [comment]
#203142
