### ISSUE TITLE
[loc][query][VSCode] Please clarify the placeholder

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20312]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Are you sure you want to open '{0}' folders?

File Name:
src\vs\workbench\electron-browser\window.nls.resx

Resource ID:
".resx", 0; "confirmOpen"

Query:
Does the placeholder replace a number?

**Comment by bpasero** [comment]
Yes, I have changed it to `Are you sure you want to open {0} folders?`
