### ISSUE TITLE
"No Speech provider is registered." is too vague of an error

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#203191]
Testing #203087

I got this error on WSL after configuring my keybindings and thought the issue was WSL couldn't process audio properly.
I then got it on my personal device after configuring my keybindings and only then realized that I could fix the problem by installing an extension like VS Code Speech.

**Comment by meganrogge** [comment]
@bpasero, what do you think of saying something about the extension here instead?

**Comment by bpasero** [comment]
We currently do not have a good story for guiding users to install the extension. For now I would hide commands, settings etc. behind the `HasSpeechProvider` context:

https://github.com/microsoft/vscode/blob/1091f68d834974d78cd4f9769034b4ae4581ff2a/src/vs/workbench/contrib/speech/common/speechService.ts#L18

**Comment by isidorn** [comment]
Agreed with Ben.

**Comment by meganrogge** [comment]
I have `HasSpeechProvider` as a `precondition` for the terminal commands, so believe that's all I can do here. 

https://github.com/microsoft/vscode/blob/b96127eea4f71b47daca57e3e4f8b9271833866b/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L1647-L1673
