### ISSUE TITLE
Triggered breakpoint when program is running could have better icon + hover

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#203153]
Testing #202882

1. Run a program
2. Have a triggered breakpoint that depends on a breakpoint that has not yet been hit
3. Hover over the triggered breakpoint and notice:
* There is a new breakpoint icon. I am not convinced we need a new icon in the UI to show this state. Could we use one of the existing breakpoint icons that we have? 
* On hover in the editor glyph it does not show on what breakpoint it depends

![Screenshot 2024-01-23 at 15 46 47](https://github.com/microsoft/vscode/assets/1926584/b1393bd0-8756-4d22-93e5-b6adeea15a09)

**Comment by connor4312** [comment]
> I am not convinced we need a new icon in the UI to show this state. Could we use one of the existing breakpoint icons that we have?

The obvious alternative here is the "unverified" icon, but I wasn't a fan of that since then one could not distinguish between a breakpoint that was waiting to be set versus one that was set but failed to bind for whatever reason. And other icons are already associated with different breakpoint type 😕

**Comment by isidorn** [comment]
Ok. If we want a new icon then I think we could get a better one. This one looks out of style compared to the others and looks like badly rendered due to low-res.

If I remember correctly - unverified is a hollow grey circle. Are we using a hollow red circle for anything?

**Comment by connor4312** [comment]
cc @hbons
