### ISSUE TITLE
[loc][query][VSCode] please provide more context

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20319]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
skipped due to 'skipFiles'
skipped due to 'smartStep'

File Name:
out\node\nodeDebug.nls.resx

Resource ID:
".resx", 0; "source.skipFiles"
".resx", 0; "source.smartstep"

Query:
Can you please clarify what is skipped here?

**Comment by roblourens** [comment]
These messages show up on stack frames that are grayed out while debugging. Usually when you 'step in' while debugging, the debugger will pause in the file that you are stepping into. But if you are using the skipFIles or smartStep attributes in your launch config, it may not pause in that file. So these messages explain why the file was skipped.
