### ISSUE TITLE
Close All (Working Tree) menu item

### ISSUE THREAD

**Issue by ManUtopiK** [microsoft/vscode#203104]
It could be useful to have a menu item to close all working tree diff editors.
I often review my diffs before committing, and open a lot of tabs for that.
When I've committed, I want to close all this diff editors, but not the "plain" editors.
I know there is a shortcut for that, but this menu item could take a good place in this menu :

![image](https://github.com/microsoft/vscode/assets/188172/6a381d38-e3ab-4fc7-8ee1-ff2542e68293)

**Comment by lszomoru** [comment]
@ManUtopiK, you can enable the automatic closure of diff editors when committing using the `git.closeDiffOnOperation` setting. You can also close all diff editors by invoking the "Git: Close All Diff Editors" command from the command palette.
