### ISSUE TITLE
Drag n Dropping multiple items is not working in Watch view

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#203183]
Testing #202849

- Open Debug watch expression view
- Create at least 4 random watch expressions
- Select more than one watch expressions and drag and drop them at a different location
🐛 Only one item is reordered

**Comment by benibenj** [comment]
Multiselect drag and drop was not supported before. Is there a reason why this wasn't supported @connor4312 ? I could add the support for it if you would like.

**Comment by connor4312** [comment]
I think this is just something that no one has asked for. If you want to support it in lists it makes sense to me. But it seems quite niche.
