### ISSUE TITLE
Option to make the "Start Debugging" button always visible in the Command Center

### ISSUE THREAD

**Issue by MurzNN** [microsoft/vscode#203105]
Now we can integrate the Debug Toolbar into the Command Center, which is very cool and convenient!

But when we stop the debugger, it disappears completely! So we have to go to the "Run and Debug" tab in the left panel and run it via the "Start Debugging" button there. I know that we can use F5 to run it, but sometimes I prefer mouse.

To resolve this issue, would be good to add an option to make the "Start Debugging" button always visible in the Command Center, and it will be replaced to the "Pause" button when started.

**Comment by roblourens** [comment]
Thanks for the suggestion, but I disagree. We would have to add the debug session picker as well, and then we would just have two places to do the same thing, and I don't think that's the direction we should go with the command center. It's nice to have this contextual place that shows some relevant actions but the home of debugging is the run and debug sidebar view.
