### ISSUE TITLE
Add copy command from terminal 

### ISSUE THREAD

**Issue by AnshuPathak-88825** [microsoft/vscode#203118]
Description:
I would like to propose the addition of a feature in Visual Studio Code that allows users to easily copy commands directly from the integrated terminal using mouse right click 

Use Case:
Often, while working in the terminal integrated into VS Code, I find myself needing to reuse or share commands with others. Currently, the process of copying commands involves manual selection, right-clicking, and selecting "Copy," which can be time-consuming. This feature aims to streamline this process for improved efficiency.

**Comment by AnshuPathak-88825** [comment]
@meganrogge pls assign this issue to me

**Comment by LEKPHET-KUNSUE** [comment]
why don't you press "assign yourself"

**Comment by meganrogge** [comment]
This already exists. Click the command decorations and select copy command.
