### ISSUE TITLE
Quick Search: Open in search button is very prominent

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#203182]
Testing #203078

![image](https://github.com/microsoft/vscode/assets/6461412/fcbc327d-8388-4c63-bff9-8d6d4c8712ed)

The open in search button is IMO too prominent. I don't think that's an command that I would use that regularly.

**Comment by andreamah** [comment]
I think that it's a valid argument. I heard feedback that the inline buttons to go to search view was not prominent enough, so I will leave this open in case there is extra discussion for this.

**Comment by osortega** [comment]
The buttons in the menu have changed, I will be closing this issue but feel free to re-open if you think otherwise.
