### ISSUE TITLE
[loc][query][VSCode] Please clarify placeholder and translatability

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20324]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Problem parsing theme file: {0}. 'settings' is not array.

File Name:
src\vs\workbench\services\themes\electron-browser\themeService.nls.resx

Resource ID:
".resx", 0; "error.plist.invalidformat"

Query:
Is this placeholder replaced by the name of the file? Is "settings" translatable?

**Comment by aeschli** [comment]
{0} will be replaced by a path. 'settings' must not be translated.
