### ISSUE TITLE
Can't exit full screen on MacOS

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode#203246]
Testing #202857

Not sure if this bug is related to this issue, but i can't exit full screen on MacOs. The button seems to be disabled. This error only happens on Insiders.

<img width="1019" alt="Screenshot 2024-01-23 at 3 14 00 PM" src="https://github.com/microsoft/vscode/assets/17892325/59d6b431-408d-4fa0-9227-4804f03d0f8c">

**Comment by deepak1556** [comment]
Tracked in https://github.com/microsoft/vscode/issues/203116
