### ISSUE TITLE
Allow resize for "outgoing/incoming" section

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#203251]
Testing #203075

Not sure if it's just me, I often find the "outgoing"/"incoming" section positioned pretty low in the sidebar (when there are quite some pending changes), I always attempt to click on the sash above the "outgoing/incoming" section to resize it. But then later on realize that it's not a traditional tree view we have so I can't resize, or drag it to move to other places.

**Comment by lszomoru** [comment]
Closing as the "Incoming/Outgoing" section has been removed.
