### ISSUE TITLE
Show preview for unexpanded value

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#203227]
Testing #203058

<img width="175" alt="image" src="https://github.com/microsoft/vscode/assets/323878/53fbae68-7c84-453c-90e3-c164aa5ff866">

Maybe you have this in mind but it would be nice to be able to see a preview for these values without expanding them. That can just be a string that is returned by the provider when it tells you about `aDict`

**Comment by amunger** [comment]
should be covered by https://github.com/microsoft/vscode-jupyter/issues/15056. That's all the provider is returning for the value at this point.
