### ISSUE TITLE
TextMate is not being updated anymre

### ISSUE THREAD

**Issue by aghArdeshir** [microsoft/vscode#203212]
Hi :wave: 

I was recently following up an issue on a bug for an HTML syntax highlighting issue, and found out it was closed as waiting for upstream (TextMate bundle) to fix the issue.

There is this information for contributors above some language grammars that depend on TextMate bundles:

![image](https://github.com/microsoft/vscode/assets/5755214/8477710a-7cf0-458d-9cbb-84ea1c8a26dc)

I wanted to inform that TextMate (and all of its grammar bundles are not being maintained anymore.

This is also copied from [the WikiPedia of TextMate](https://en.wikipedia.org/wiki/TextMate):
> In October 2021, the latest/last commit was made to GitHub, though no announcement has been made to the effect that the project has been officially abandoned and its source code is still publicly available.

Here is a list of TextMate bundles Visual Studio Code depends upon and their latest update:
- YAML: https://github.com/textmate/yaml.tmbundle (6 years ago)
- XML: https://github.com/textmate/xml.tmbundle (6 years ago)
- ASP.VB: https://github.com/textmate/asp.vb.net.tmbundle (6 years ago)
- Ruby: https://github.com/textmate/ruby.tmbundle (3 years ago)
- Perl: https://github.com/textmate/perl.tmbundle (3 years ago)
- ini: https://github.com/textmate/ini.tmbundle (11 years ago)
- Groovy: https://github.com/textmate/groovy.tmbundle (10 years ago)
- Git: https://github.com/textmate/git.tmbundle (5 years ago)
- Diff: https://github.com/textmate/diff.tmbundle (8 years ago)
- c/cpp: https://github.com/textmate/c.tmbundle (4 years ago)
- HTML: https://github.com/textmate/html.tmbundle (3 years ago)

I don't necessarily mean they need active maintaining, but Visual Studio Code will miss language improvements and required bug fixes, and there will be lots of unnecessary housekeeping work required to clean up issues and PRs for those.

So with all that given, I believe it could be beneficial to developers using Visual Studio Code if we had an actively maintained language grammar.

I looked up to see if the same discussion is already open somewhere, but did not find any public discussion. The most similar, but still unrelated discussion was this:

- https://github.com/microsoft/vscode/issues/216

which is looking for alternatives to TextMate; but for reasons other than the fact that TextMate is dead. (?)

# Example Case

I was following up on this issue recently:
- https://github.com/microsoft/vscode/issues/202915

which later was closed as a duplicate of this issue in the upstream TextMate language grammar for HTML:
- https://github.com/textmate/html.tmbundle/issues/113

Which later I followed on more issues being closed as duplicate of the same issue:

- https://github.com/microsoft/vscode/issues/105779
- https://github.com/microsoft/vscode/issues/105790
- https://github.com/microsoft/vscode/issues/111394
- https://github.com/microsoft/vscode/issues/112189

The issue is simply about a bug in HTML language grammar for event handler attributes. (which is not the topic here)

And there is a fix PR for it in the upstream repo:
- https://github.com/textmate/html.tmbundle/pull/114

and a closed PR (the same PR) in vscode repo:

- https://github.com/microsoft/vscode/pull/113434

All these issues/PRs all refer to the same bug and I used this bug only as an example. There are probably other issues with other grammar bugs here and there, which are probably open/closed without resolution because of the same reason.

**Comment by alexr00** [comment]
For many of these we are trying to find a new grammar. Others, we don't actually depend on:
- YAML: Trying to find a new grammar.
- XML: Trying to find a new grammar.
- ASP.VB: We're not trying to find a new grammar here, but there aren't many complaints about it.
- Ruby: We're not trying to find a new grammar here, but there aren't many complaints about it.
- Perl: We're not trying to find a new grammar here, but there aren't many complaints about it.
- ini: Trying to find a new grammar.
- Groovy: Trying to find a new grammar.
- Git: We have moved to a new grammar 1 year ago. The textmate repo grammar is only used for rebase now.
- Diff: We're not trying to find a new grammar here, but there aren't many complaints about it.
- c/cpp: We moved to new C and C++ grammars years ago. The textmate repo grammar is only included for source.c.platform, which is included by other languages.
- HTML: Trying to find a new grammar.

Full list of issues where we're trying to find a new grammar is here: https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3Agrammar+label%3Afeature-request+assignee%3Aalexr00

**Comment by aghArdeshir** [comment]
Thanks for your time and the clear answer :smiley:
