### ISSUE TITLE
Single Variable in variable view does not show size

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/vscode#203284]
Testing #203058

I'm not sure if this is intentional, but size for single variable does not show size 1.
(For example, for boolean and integer does not show size at all)
Do we want to have size 1 instead of blank space?

<img width="598" alt="Screenshot 2024-01-23 at 9 20 26 PM" src="https://github.com/microsoft/vscode/assets/62267334/dc524262-dd45-4a3c-8624-8cdaec6bbada">

**Comment by amunger** [comment]
that is the extension's view, no plans to update that one.
