### ISSUE TITLE
Web: What happened to report extension issue?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#203247]
Testing #203094

![image](https://github.com/microsoft/vscode/assets/2644648/2b568613-f5c5-4f35-8310-84c9c6bceed6)

It's possible that it was never there... but since on the web we don't have the issue reporter (and open GitHub.com directly) we should have an option that takes the user through a flow to open an issue on an extension in the web.

**Comment by rootsmusic** [comment]
If vscode.dev has Issue Reporter, then it'd also be able to submit a "feature request".  #203014
