### ISSUE TITLE
SCM input field doesn't show a vertical scrollbar

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#203261]
Type: <b>Bug</b>

If a put in enough lines to go beyond the viewport, no scrollbar appears (this is not a problem horizontally when word wrapping is turned off).

VS Code version: Code - Insiders 1.86.0-insider (800e60abdfb1675a59520bac6a9473bc380d49ea, 2024-01-23T06:12:41.150Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (4.23GB free)|
|Process Argv|--crash-reporter-id 2f8216b4-0af9-4bf4-a156-6cdcff01b0ab|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|7.63GB (6.15GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-todo-highlight|jgc|2.0.8
remote-wsl|ms-|0.81.9
copilot|Git|1.153.0
copilot-chat|Git|0.11.1
vscode-pull-request-github|Git|0.79.2024012309
debugpy|ms-|2023.3.13341006
python|ms-|2023.25.10221012
vscode-pylance|ms-|2023.12.104

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vscod805cf:30301675
vsaa593:30376534
py29gd2263:30784851
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
b5d27386:30943795
fegfb526:30945144

```

</details>

**Comment by lszomoru** [comment]
This behaviour is a side-effect that occurred when we added the "sparkle" action to generate a commit message into the input field. At the moment we are only showing a shadow at the top of the input field to indicate that there is content outside of the viewport. This is consistent with other input field in the workbench that grow to a fixed size.

**Comment by MartinBonner** [comment]
I see this has been closed as "as designed".  I think you should change the design - it's incredibly annoying, _particularly_ as scrolling up and down too far, suddenly causes the input window to jump to some other commit.  (I have just created a 33 line commit message, and I don't think that is particularly long).
