### ISSUE TITLE
Variables tree not updated by background code

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#203239]
Testing #203058

```
import threading
import time

# This is the variable you want to edit
my_var = 0

# This is the function that will run in the background
def background_task():
    global my_var
    while True:
        time.sleep(1)  # Wait for 1 second
        my_var += 1   # Increment the variable

# Start the background thread
thread = threading.Thread(target=background_task)
thread.start()
```

I don't know how you want to handle this or even whether this is common but I remembered that this is possible. 

If there was a Refresh button that might unstick a user who wants to do this kind of thing. But if this is really unusual you could ignore it.

**Comment by amunger** [comment]
the refresh button would also have to alter the provider's behavior to not use the cache for that execution count. So I think the workaround of executing any cell to increment the count is good enough unless people really push for it.
