### ISSUE TITLE
For `uri` consider type  `Uri | string`

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#203229]
Testing #203094

It seems weird to pass in string when you could just pass in a Uri. Better yet, consider `Uri | string`

**Comment by justschen** [comment]
I think when I was testing, URI wasn't serializable so it wouldn't be passed thru the command properly - will double check this soon though 👍

**Comment by TylerLeonhardt** [comment]
@justschen you may need to turn it into a `UriComponents` and then `revive` that on the other end. It's possible. We do it with other processes.
