### ISSUE TITLE
Vs code speech should require Copilot Chat

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#203210]
Testing #202926

1. Install VS Code speech
2. Get confused why you cannot figure out how to use it
3. Install Copilot Chat
4. 🎉 It works

**Comment by bpasero** [comment]
We are building experiences outside of chat, see for example https://github.com/microsoft/vscode/issues/199128, https://github.com/microsoft/vscode/issues/202763, https://github.com/microsoft/vscode/issues/40976
