### ISSUE TITLE
repositories still exist in explorer view after closing them in SCM

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#203243]
Testing #203035

1. open a folder with 30 gh repositories
2. right click on one, close other repositories
3. with just one remaining, close that repository
4. click reopen repository and select `vscode`
5. go to file explorer
6. I expect to only see VS Code folders, but I instead see the folders for a bunch of repositories

https://github.com/microsoft/vscode/assets/29464607/c98f21c8-1837-4315-806e-6e912da14194

**Comment by lszomoru** [comment]
This behaviour is by design. Closing a repository removes the repository from the "Source Control" view but has not effect on the Explorer view which operates on the file system.
