### ISSUE TITLE
[loc][query][VSCode] please clarify the unclear strings

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20320]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Toggle Output Scroll Lock
Toggle Tab Key Moves Focus

File Name:
src\vs\workbench\parts\output\browser\outputActions.nls.resx
src\vs\editor\contrib\toggleTabFocusMode\common\toggleTabFocusMode.nls.resx

Resource ID:
".resx", 0; "toggleOutputScrollLock"
".resx", 0; "toggle.tabMovesFocus"

Query:
These strings do not make a lot of sense without context. Can you please clarify them and provide more context?

**Comment by isidorn** [comment]
I have pushed a clarification of those strings, namely
*Turn on / off automatic output scrolling
*Turn on/off use of tab key for moving focus around VS Code
