### ISSUE TITLE
Intellisense for in launch.json is wrong

### ISSUE THREAD

**Issue by haferburg** [microsoft/vscode#203228]
Typing `"en` suggests `"env"` which then completes to `"env": {}`.
![image](https://github.com/microsoft/vscode/assets/4941909/3b58cb26-ae13-4670-aa87-c652cefb0e94)

My understanding is that the new and correct syntax is `"environment": [{"name": "", "value": ""}]"`.
https://code.visualstudio.com/docs/cpp/launch-json-reference#_environment

But when I use `"environment"`, Code even says that this is not allowed.
![image](https://github.com/microsoft/vscode/assets/4941909/ee7b0ea0-784e-480f-bd38-a352341860a9)

---

Does this issue occur when all extensions are disabled?: Yes

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.0-14-generic

**Comment by roblourens** [comment]
Intellisense just uses a json schema that comes from the extension, so you'll have to report this on the repo for that extension.
