### ISSUE TITLE
[loc][query][VSCode] Please clarify placeholder

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20323]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Problems parsing theme file: {0}

File Name:
src\vs\workbench\services\themes\electron-browser\themeService.nls.resx

Resource ID:
".resx", 0; "error.cannotparse"

Query:
Does this placeholder mean the name of the file? Thanks.

**Comment by aeschli** [comment]
Yes, the placeholder is a path to the file.
