### ISSUE TITLE
Do we need to show the `#n:` stash number in `Git: View Stash...` list?

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#203200]
Testing #203040

Curious as to why we show `#0:` `#1:` `#2:` etc. prefix in the `Git: View Stash` list.  There is always a name, even if you don't give the stash a name, which makes for easy keyboard access.  

![image](https://github.com/microsoft/vscode/assets/1487073/81ebc994-4c8f-4826-a503-dd1d8a2966ed)

**Comment by lszomoru** [comment]
The stash index (ex: `#0`) has been there historically in all the stash pickers for other commands (ex: Pop Stash..., Apply Stash...). I think that it helps users understand which stash is at the top of the stack (latest), as well as all `git stash` commands operate using an index so they can also get that information from the picker. Happy to keep the issue opened to gather more feedback.
