### ISSUE TITLE
[loc][query][VSCode] please clarify "PHP Path"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20321]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
This setting must be a User Setting. To configure PHP for the workspace, open a PHP file and click on 'PHP Path' in the status bar.

File Name:
src\vs\workbench\parts\preferences\browser\preferencesEditor.nls.resx

Resource ID:
".resx", 0; "unsupportedPHPExecutablePathSetting"

Query:
Is "PHP Path" a Visual Studio option? Not found.	Cristina Carrasco	2/2/2017 12:32:57 PM

**Comment by dbaeumer** [comment]
`PHP Path` is like a button in the status bar. So the translation should translate Path but not PHP.

**Comment by sandy081** [comment]
@dbaeumer Is this warning shown still? I thought php executable path is no longer tagged as only user setting?
