### ISSUE TITLE
[loc][query][VSCode] Please clarify "language"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20322]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Select Language

File Name:
src\vs\workbench\parts\preferences\browser\preferencesActions.nls.resx

Resource ID:
".resx", 0; "pickLanguage"

Query:
Does it refer to a programming language? Please, confirm.

**Comment by sandy081** [comment]
Yes it refers to the programming language
