### ISSUE TITLE
Quick chat - icon positioning

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#203299]
Testing #203012

I really like this new mode. One thing that I noticed at least while I was testing was that the "listening indicator" appeared below the code selection, but when the recording completed, inline chat appeared above the code selection. I think that it would be nice if both UI elements would use the same anchor location.

**Comment by jrieken** [comment]
> One thing that I noticed at least while I was testing was that the "listening indicator" appeared below the code selection

Today the indicator appears at the active end of the selection (where the cursor is) and it positions itself so that it doesn't cover the selection. This might be too much and we can simply use the selection start and always show above that.
