### ISSUE TITLE
Custom title bar style setting is confusing if I have title bar style set to custom

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#203290]
![image](https://github.com/microsoft/vscode/assets/10746682/1bb41c14-8f6b-4573-9954-e750ff9039d5)

For those who are on Mac with already custom title bar, this might be confusing. Please note that changing this setting has no impact in Mac.

Probably we should write in the description that this has a relation with title bar style

**Comment by benibenj** [comment]
Actually it does have an impact on mac even with title style custom. Setting to windowed will cause the custom title bar to hide in full screen.

**Comment by sandy081** [comment]
Thats right, but never option does not do anything. It would be helpful if we can update that in the description.
