### ISSUE TITLE
SCM - input field min lines error text  reads `Value must be less than or equal to 50` despite Max lines value being 40

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#203232]
Testing #203034

The error message should display the max lines value.

![Image](https://github.com/microsoft/vscode/assets/25044782/7b6621dc-2030-44d0-8c68-b26f6ae1b872)

**Comment by lszomoru** [comment]
This behaviour is by design. The value that is displayed in the validation message is based on the values that are statically declared when a confirmation is defined. I do not believe that there is a way to dynamically set the value. 

@rzhao271, @sandy081 please correct me if I am wrong. Thanks!
