### ISSUE TITLE
floating notebook windows not restored 

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#203214]
Testing #202923

https://github.com/microsoft/vscode/assets/54879025/074d5379-abce-48a0-842f-cafc6f755ef0

windows aren't restored on reload. when closing the floating window, the window is not restored in the main window.

if necessary, for context, the third floating window is a floating terminal window.

works super well on non-notebook files from my testing though 👍

**Comment by bpasero** [comment]
@rebornix could you check? I can reproduce this but only when the floating window with the notebook is not the active focused window. In other words, this reproduces the issue for me:
* open floating window with notebook
* focus an editor in main window
* reload from main window

What does not reproduce is when I reload from the floating window with the notebook having focus 🤯

**Comment by rebornix** [comment]
My gut feeling is it might be related to checking "active" document/container. Will dig into this.

**Comment by rebornix** [comment]
From the screenshot the notebook toolbar is already rendered, so it's very likely waiting for webview to be rendered.

**Comment by rebornix** [comment]
It's the same issue as https://github.com/microsoft/vscode/issues/201832. Not sure why in my initial PR `getActiveWindow` worked just fine on window reload, but now it's always giving me the main window. My fix for now is passing the `codeWindow` revived from your change https://github.com/microsoft/vscode/commit/b6d977789e3697ba2bcb1afedfc57949bb8704af .

**Comment by bpasero** [comment]
@rebornix thanks, can you give me some hints as to where you were expecting the floating window and get the main window, I am curious if something is broken in my area from changes I did.

**Comment by bpasero** [comment]
Oh, looking at your change, I see the issue: using `getActiveWindow` is never a good idea because that can be a random window at random times depending on focus. Passing down the window to use is 👍
