### ISSUE TITLE
Variable view spacing UI can be improved 

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/vscode#203283]
Testing #203058

First of all, great feature! 
Very happy to see this feature in notebook.

This may be little knit picking, but it would be nice if we can center/spread out the spacing of the columns as we shrink, expand variable view UI.

<img width="1587" alt="Screenshot 2024-01-23 at 9 15 56 PM" src="https://github.com/microsoft/vscode/assets/62267334/e01140b5-681e-4877-9e26-fb9a26c07dcb">
<img width="598" alt="Screenshot 2024-01-23 at 9 20 26 PM" src="https://github.com/microsoft/vscode/assets/62267334/18106432-8f93-4797-b7e0-d7f079d4a02e">

**Comment by amunger** [comment]
that is the extension's view, no plans to update that one.
