### ISSUE TITLE
VS Code Speech does not warn when no chat providers are found.

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#203241]
Testing #202926

I do not have `copilot-chat`  installed. Should we notify the user that the `Hey Code` command needs a chat provider to work?

**Comment by bpasero** [comment]
Good point, I wonder how we deal with this in other contexts. @roblourens is there an example of commands or settings that impact chat that would tell the user to install an extension for a chat provider?

One thing we could do is to not show the setting when no chat provider is registered.

**Comment by roblourens** [comment]
There isn't any API for you to probe whether chat providers are registered, but any UX would be owned by vscode and just not show up, right? I think the extension shouldn't have to know whether there are chat providers.

**Comment by bpasero** [comment]
@roblourens but I can call `IChatService.getProviderInfos()` to see if any provider is registered, no?

**Comment by roblourens** [comment]
Yeah, internally you can do that.

**Comment by bpasero** [comment]
Yeah this is all internal, the extension knows nothing about the UI.

**Comment by bpasero** [comment]
Verification: install `ms-vscode.vscode-speech` speech extension but not copilot chat and verify you do not see `accessibility.voice.keywordActivation` setting. Once you install copilot chat, you see `accessibility.voice.keywordActivation` setting.
