### ISSUE TITLE
While typing in setting.json unable to use down arrow to select from suggested settings

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#203264]
Testing #203089

While trying to select this is what happens, the completion list vanishes.
![image](https://github.com/microsoft/vscode/assets/3840081/a202d48a-e7b6-402c-a1c3-d19934bf750e)

https://github.com/microsoft/vscode/assets/3840081/a08c316b-40a6-4190-a808-2680b7c26450

**Comment by meganrogge** [comment]
It's unclear what's happening here - could you pls provide the logs when you toggle keyboard shortcuts troubleshooting?

**Comment by karthiknadig** [comment]
@meganrogge I can share my screen if you want to see. I am not sure what I need to provide to help debug this.

**Comment by meganrogge** [comment]
I don't know why that would happen and don't have experience with narrator. I'd suggest using NVDA or JAWS
