### ISSUE TITLE
Show longer variable preview on hover

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#203237]
Testing #203058

<img width="430" alt="image" src="https://github.com/microsoft/vscode/assets/323878/6f85eed4-eeed-4f9e-aa0d-ddfc56ab87e2">

The debug variable tree will show 1000 or more characters, but much fewer are shown here

Also, a "copy value" context menu action to get the full value would be helpful, as in debug

**Comment by amunger** [comment]
completed with https://github.com/microsoft/vscode-jupyter/issues/15056
