### ISSUE TITLE
Zooming out in a floating window glitch occasionally

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#203216]
Testing #202922

Tested on a Mac. This happens on floating windows only with the setting `window.zoomPerWindow` enabled.
![Image](https://github.com/microsoft/vscode/assets/25044782/4944ee31-42db-4278-b90b-1ea780446842)

**Comment by bpasero** [comment]
@bhavyaus whats the glitch?

**Comment by bhavyaus** [comment]
The contents jump back and forth before "settling" in the screen cap.

**Comment by bpasero** [comment]
And that does not reproduce in the main window?

**Comment by bhavyaus** [comment]
No. It does not reproduce in the main window.
