### ISSUE TITLE
Notebook Search eagerly activates extensions 

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#203389]
1. Enable notebook search (search.experimental.closedNotebookRichContentResults)
2. search in a dir with only a few files (no notebooks) and make a search.
3. Notice that multiple notebook serializers get enabled `onNotebookSerializer`, even if their serializer path does not match anything in the repo. :bug:

I think this was overlooked because I tried to reduce the number of `findSearch` from the renderer side and rather try to do all of the file searching form the extension side, but we perform all extension host logic from within the serializer (which needs activation).

Ideally, we can add a new call that can reply with whether or not there are files present that match a glob - otherwise, we have the problem again where potentially lots of file match data goes between ext host and render (which isn't great in the remote case) 

cc: @roblourens

**Comment by andreamah** [comment]
> Since this is I think this was overlooked because I tried to reduce the number of findSearch from the renderer side and rather try to do all of the file searching form the extension side, but we perform all extension host logic from within the serializer (which needs activation).

Looking at this a little more, there doesn't seem to currently be an efficient way to ask 'does x glob have any results'? Any call to `fileSearch` will return all results, which would be troublesome in the remote case where someone has a lot of providers installed, since it would be transferring a lot of useless info (all the matching file info) between the EH and render. 

Ideally, I can make a modified version of `fileSearch` that tries to check for existing files and will return as soon as it finds at least one file.

**Comment by eleanorjboyd** [comment]
Not sure how to do this part:

Notice that multiple notebook serializers get enabled onNotebookSerializer, even if their serializer path does not match anything in the repo. 🐛

**Comment by andreamah** [comment]
try searching for `a` in a repo with no notebooks and jupyter notebooks. When you go to the extension host logs, it should not show the jupyer extension activating.

**Comment by eleanorjboyd** [comment]
I see this in my logs:
`2024-02-21 13:59:57.017 [trace] [ms-toolsai.jupyter] INVOKE provider 'X=>X.provideCodeLenses(w.URI.revive(q),Y)'` is that what I am checking for?

**Comment by andreamah** [comment]
Oh, perhaps you should reload first. so the steps are

1. Go to directory without ipynb files.
2. Reload.
3. Search for something.
4. Make sure that you DON'T see a line that starts like `[info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false` in your ext host channel.

**Comment by eleanorjboyd** [comment]
Followed those steps and am seeing this, should I not have a python file either?

`2024-02-21 14:29:34.196 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onLanguage:python'`

**Comment by andreamah** [comment]
hmm yeah maybe stick to text files, sorry about that!

**Comment by DonJayamanne** [comment]
Yeah, I'm also a little lost on how this needs to be verified.

**Comment by andreamah** [comment]
The key is that an arbitrary search in a directory without ipynb files doesn't activate the jupyter extension on search.

https://github.com/microsoft/vscode/assets/31675041/0331cce2-9d76-4db8-b478-74cfa03b213b

Notice that in my case, there is no log that appears at the end that shows jupyter activating.
