### ISSUE TITLE
Luminosity ratio of the placeholder text of inputbox in command center is 3.339:1 which is less than minimum required ratio 4.5:1

### ISSUE THREAD

**Issue by miniwangdali** [microsoft/vscode#203398]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.2
- OS Version: Windows 11 Enterprise (Windows_NT x64 10.0.22631.3007)

```
Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
```

**Description**
During an accessibility test, we found the contrast ratio between the placeholder text and the background is not high enough under "Default Dark Modern" theme.

Placeholder Text Color: `#818181`
Background Color: `#313131`
Contrast Ratio: 3.339:1
Required Contrast Ratio: 4.5:1

![image](https://github.com/microsoft/vscode/assets/5415452/348270b9-a778-4c59-8f45-3da01ad1d13b)

**Comment by shindepra** [comment]
#A11yMAS; #A11yTCS; #A11ySev2; #DesktopApp; #Win32; #Visual Studio Code Client; #BM-VisualStudioCodeClient-Win32-Aug2023; #WCAG1.4.3; #Contrast(Minimum); #AILimited;

**Primary Bug ID**: https://microsoft.visualstudio.com/Xbox/_workitems/edit/48288067

**Comment by shindepra** [comment]
#A11yMAS; #A11yTCS; #DesktopApp; #Win32; #Visual Studio Code Client; #BM-VisualStudioCodeClient-Win32-Aug2023; #WCAG1.4.3; #Contrast (Minimum);

**Primary Bug ID:** https://microsoft.visualstudio.com/Xbox/_workitems/edit/48288067
