### ISSUE TITLE
This cloud changes view could take advantage of the multi-diff editor

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#203350]
![image](https://github.com/microsoft/vscode/assets/2644648/2d8fbdf3-2be1-4d32-9075-90ad24d6fa8d)

It might be easier to use for Cloud Changes that have many files changed, but small changes in each.

**Comment by joyceerhl** [comment]
This view is meant mainly for debugging, so it's unlikely to be worth the effort to implement multi diff editor support.
