### ISSUE TITLE
Different behavior for "Select Language Mode" in Linux and Windows

### ISSUE THREAD

**Issue by abist** [Microsoft/vscode#20339]
- VSCode Version: 1.9.0
- OS Version: Ubuntu 16.04 LTS/ Windows 10 Enterprise

Steps to Reproduce:

1. Try to change the language of the file

In Windows, you get tiny icons to the left of every language, however this is not the case for Ubuntu.

![Windows](https://cloud.githubusercontent.com/assets/6411451/22796615/e21cbed4-eeaf-11e6-89bb-f776fd47c3d6.png)

![Ubuntu](https://cloud.githubusercontent.com/assets/6411451/22796625/ea0af516-eeaf-11e6-8296-d57ac0b3a710.png)

Not sure if this is a bug, but just pointing it out.

**Comment by Tyriar** [comment]
You have different settings for the icon theme (F1 > Icon theme). Either that or the versions differ.
