### ISSUE TITLE
When vscode is out of date, some extensions keep showing "update" button even after updating

### ISSUE THREAD

**Issue by nholthaus** [Microsoft/vscode#20334]
- VSCode Version: previous versions
- OS Version: all

Steps to Reproduce:

1. Update an extension whose latest release requires a newer version of code than what you have installed. (e.g code < 1.8.0 and cmake tools < v7.2)
2. The green "update" button will remain even after performing an update (of the extension only), but the extension version doesn't increment

This behavior actually kind of makes sense, but the problem is it since the user at this point is just trying to update extensions, it makes it seem like the updater is broken. There's no feedback loop that says "hey, you can't update to the latest version of the extension _because_ your vscode version is too old". 

OR, maybe vscode shouldn't show extensions as update-able if they can't be updated with your current version of code. It would be more intuitive certainly.

**Comment by sean-mcmanus** [comment]
Yeah, I get the same behavior with VS Code 1.5.3 with the C/C++ 0.9.3 extension (0.10.0 requires 1.6.0 of VS Code). I don't know why anyone would use an older version of VS code though, so maybe this issue is just too low priority to worry about?

**Comment by nholthaus** [comment]
It's not so much that you would use an old version on purpose, it's that the following flow is _required_, but nothing tells the user that:

**works**
1. update vs code
2. update extensions

**doesn't work**
1. update extensions
2. update vscode

In fact, you'd probably _only_ hit this issue while you are in the process of updating.

Additionally, there are a lot of reasons folks might be on an old version, at least to start. Think corporate PC image...

**Comment by joaomoreno** [comment]
This has been fixed in the current Code versions. We can't really fix old versions can we?

In the current version of VSCode this should not happen. Users don't get updates for an extension version which is incompatible with their Code version.
