### ISSUE TITLE
"issues" link in Release Notes does not work as intended

### ISSUE THREAD

**Issue by smarts** [Microsoft/vscode#20333]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.7.0|
|vscode-docker|PeterJausovec|0.0.11|

---

Steps to Reproduce:

1. Upgrade from 1.9.0 to 1.9.1
2. Look at release notes for 1.9.1 Recovery build and click the "issues" link.
3. Because the GitHub "milestone" has spaces (i.e., January Recovery 2017) and is not surrounded by quotes, the desired issues are not shown

**Comment by smarts** [comment]
@joaomoreno No... it's not fixed. I just clicked on the link again by going to `Help -> Release Notes` and it is still broken. Do you mean it will be fixed in a future release?

**Comment by joaomoreno** [comment]
What version are you on?

**Comment by smarts** [comment]
https://github.com/Microsoft/vscode/issues/20333#issue-206568784

**Comment by joaomoreno** [comment]
This is working for me, you still see the issue?

**Comment by smarts** [comment]
@joaomoreno yes, I do. Maybe we need another person to verify since we seem to be split down the middle =)

**Comment by gregvanl** [comment]
The repro seems to be on Windows having Chrome be your default browser. The necessary quotes are removed when the link is launched from the in-product release notes.
I'll change to use the milestone number directly.

**Comment by gregvanl** [comment]
Fixed with vscode-docs https://github.com/Microsoft/vscode-docs/commit/a633cd2cf86300c195bf562ce208bb76dd6bc003
