### ISSUE TITLE
Windows Narrator reads "space" in empty inputbox of a command parameter in command center.

### ISSUE THREAD

**Issue by miniwangdali** [microsoft/vscode#203394]
Does this issue occur when all extensions are disabled?: **Partially Yes** (if you can find a string parameter input in command center, disabling all extensions eliminates the place it happens.)

- VS Code Version: 1.85.2
- OS Version: Windows 11 Enterprise (Windows_NT x64 10.0.22631.3007)

```
Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
```

**Description**

I am building a VS Code extension. When we go through our accessibility test, the tester reports that windows narrator reports redundant "space" on an empty inputbox. I don't have "space" at the end of the text we provided as placeholder.
Similar problem can be observed in "Create Tag" command in `Git` extension as well.

I would like to know whether this is a windows narrator problem or something that VS Code has specially for the input. 
Thanks.

Steps to Reproduce:

1. Find a command that requests a string parameter in command center.
2. Let Windows Narrator read out the empty inputbox.
3. You can hear "space" read out after the placeholder if exists. Changing the verbosity level does not resolve the problem.

**Screencapture**

https://github.com/microsoft/vscode/assets/5415452/c18232cf-00ae-49f7-b4db-2de4e0900660

**Comment by miniwangdali** [comment]
We asked our tester to try NVDA. The result is that, NVDA says "Blank" for empty inputbox. I checked their issues and it seems that is an intentional decision.
Given the narrator still have the problem, we are not allowed to resolve the issue on our end so we have to report to external parties.
Could you confirm that VS Code is doing everything correctly here? If so, I will contact Narrator team and report bugs on their end.
Thanks.

**Comment by meganrogge** [comment]
Yes, I can confirm VS Code is behaving correctly here. Thanks

**Comment by kupatkar99** [comment]
### GitHub tags:
#A11yMAS; #A11yTCS; #A11ySev2; #DesktopApp; #Win32; #Visual Studio Code Client; #BM-VisualStudioCodeClient-Win32-Jan2024; #WCAG4.1.2; #Name Role Value; #AILimited;

**Primary bug ID**: https://microsoft.visualstudio.com/Xbox/_workitems/edit/48286411
