### ISSUE TITLE
Background color is blocky when displayed on an external monitor on macOS

### ISSUE THREAD

**Issue by peteallen** [Microsoft/vscode#20331]
- VSCode Version: 1.9.1
- OS Version: macOS 10.12.3 on MacBook Pro Retina 15-inch Mid 2014

Steps to Reproduce:

1. Connect an external monitor to the Macbook (HDMI or DisplayPort)
2. Open VSCode
3. Drag VSCode to the external monitor

See the attached screenshot showing the problem. It's worth noting that the problem doesn't happen if I disable GPU acceleration with the --disable-gpu flag.

![vscode-bug](https://cloud.githubusercontent.com/assets/3686835/22793638/a5886a42-eead-11e6-992c-fe080d63a180.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/12473
