### ISSUE TITLE
codelens shouldn’t be fully updated

### ISSUE THREAD

**Issue by Simon-He95** [microsoft/vscode#203323]
Every time I press Enter at the bottom, the codeLens above will be re-rendered, and the page will shake a lot. I think there should be a diff comparison to batch update.

![屏幕录制2024-01-24 19 18 55](https://github.com/microsoft/vscode/assets/57086651/f2518ca7-1860-4a60-b91d-03eda7430029)

**Comment by jrieken** [comment]
> I think there should be a diff comparison to batch update.

There is something like this but you might be returning an empty array of code lenses inbetween. Please share a minimal repro that allows us to reproduce this

**Comment by Simon-He95** [comment]
Hi @jrieken, thank you for such a quick recovery.
I used the code repository in the official vscode-sample as a demonstration.

https://github.com/microsoft/vscode-extension-samples/tree/main/codelens-sample

**Comment by Simon-He95** [comment]
I found a problem. Because I did not register registerCodeLensProvider during initialization, but at a certain moment, I had this problem after dynamically using registerCodeLensProvider. But I think I can change my writing method to avoid this problem.
