### ISSUE TITLE
incoming/outgoing feature in source control is not working

### ISSUE THREAD

**Issue by pWoLiAn** [microsoft/vscode#203311]
Type: <b>Bug</b>

clicking on it is not doing anything. i just see the loading animation for a second and thats it.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.4.0-150-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (0.86GB free)|
|Process Argv|--crash-reporter-id 99c4487a-7581-42c4-9cec-375a1b084a92|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vm|
|OS|Linux x64 5.4.0-150-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz (16 x 2397)|
|Memory (System)|31.33GB (6.30GB free)|
|VM|2%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
file-icons|fil|1.1.0
vscode-graphql-syntax|Gra|1.2.3
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
gitlens|eam|14.7.0
go|gol|0.40.3
vscode-docker|ms-|1.28.0
vscode-kubernetes-tools|ms-|1.3.13
vscode-yaml|red|1.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
0bi6i642:30933247
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by lszomoru** [comment]
@pWoLiAn, there are couple of known issues that have already been fixed in VS Code Insiders. Could you [download](https://code.visualstudio.com/insiders/) the latest version of Insiders and see if you are still able to reproduce the problem?

**Comment by pWoLiAn** [comment]
confirmed working on insiders build
