### ISSUE TITLE
Enhancement: auto-closing brackets to include backticks?

### ISSUE THREAD

**Issue by jrnail23** [Microsoft/vscode#20338]
In working with ES6(+),  I find myself using backticks quite a lot, generally for string template literals (i.e., `` `item count is ${items.length}` ``)  I'd like to have Code auto-close backticks in javascript, like it currently does with brackets and single/double quotes.  BTW, this is the default behavior in Atom.

**Comment by mjbvz** [comment]
Autoclosing of backticks is enabled in JavaScript and TypeScript. Can you please explain what expected behavior you are not seeing? 

Note that autoclosing backticks is disabled for javascript inside of html files currently.

**Comment by jrnail23** [comment]
@mjbvz, when I type a backtick, I only get one, not two.  That's pretty much it.

**Comment by mjbvz** [comment]
@jrnail23 What type of files are you working in? Do you have any extensions installed?

**Comment by jrnail23** [comment]
@mjbvz, I'm exclusively working with `.js` files, using flow annotations, and yeah, I've got lots of extensions.

**Comment by mjbvz** [comment]
Please disable all extensions by starting code `--disable-extensions` or by using the `Disable all installed extensions command` and see if the problems still repos. If it still does with extensions disabled, please provide an example file so that we can investigate

**Comment by jrnail23** [comment]
@mjbvz, you nailed it.  disabling all extensions worked, so now I've just gotta go through and re-enable them one-by-one to find the culprit.  Thanks!

**Comment by jrnail23** [comment]
In case anyone else has this issue, mine was apparently caused by a JS Standard Linter extension (`shinnn.standard`)

**Comment by mjbvz** [comment]
@jrnail23 Thank you for the followup here.

Closing as external
