### ISSUE TITLE
SCM Graph - Outgoing commit should have `Undo Commit`

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#203313]
Testing #203075

It would be great to have an `Undo Commit` and have it appear in the context menu of outgoing commits.

- If the commit is the last one, it just does what `Undo Last Commit` does, we have this today.
- Otherwise, it rebases the commits such that the commit that was selected gets moved to the top, thus becoming the last. (see https://github.com/microsoft/vscode/issues/203315) Then, `Undo Last Commit` can run.

Furthermore, `Git: Undo Commit...` could be an F1 action which would first show all outgoing commits in a quick pick. Once the user picks a commit, the steps above would run.

**Comment by lszomoru** [comment]
Closing as we already track the feature request to add "Revert Commit" to the SCM Graph.
