### ISSUE TITLE
move find widget's match counter to a better spot

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2033]
I like the match counter but I think it is placed in an unfortunate location:

![2016-01-14 20-32-28](https://cloud.githubusercontent.com/assets/1898161/12335346/08c6047c-baff-11e5-97a5-676d65fca800.png)

It lives in the white text box but in contrast to all other elements in that box it takes no user input. In addition it makes the editable area even smaller and clutters the UI.

Could we find a better spot?

In addition the matcher counter is clipped on OS X:

![2016-01-14 20-46-34](https://cloud.githubusercontent.com/assets/1898161/12335531/ff31d6a6-baff-11e5-8484-e06b9e850f6d.png)

CC @stevencl

**Comment by stevencl** [comment]
See this issue for a discussion about this: #1476

**Comment by weinand** [comment]
@stevencl great, that discussion covers my issues. I'm closing this one.
