### ISSUE TITLE
Markdown preview not expand to fit text editor area after zoomed in

### ISSUE THREAD

**Issue by yc2986** [Microsoft/vscode#20336]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.8|
|cpptools|ms-vscode|0.10.0|
|jsx|TwentyChung|0.0.1|
|vscode-react-native|vsmobile|0.2.5|
|ReactSnippets|xabikos|1.2.1|

---

Steps to Reproduce:
Just to use the release note 1.9.1 as example

1. Open VSCode with default setting, release note is occupying the whole text editor area now.
2. Use Ctrl+= shortcut to zoom in. The bigger the zoom in level, the smaller the markdown preview area.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/5745
