### ISSUE TITLE
The extension host terminated unexpectedly

### ISSUE THREAD

**Issue by alexeychikk** [microsoft/vscode#203385]
Type: <b>Bug</b>

Every 15-20 minutes my VS Code kind of reloads its extensions (I don't know how to better describe it), it also reloads Source Control tab and stops all debug sessions. The VS Code itself seems to not be reloading completely because unsaved file editors remain open. I've tried reloading with extensions disabled - and the same thing. VS Code still reloads Source Control and stops debug sessions.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900KF (32 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (20.54GB free)|
|Process Argv|--crash-reporter-id 5712a873-9014-496e-b431-149992b20b93|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
classdiagram-ts|Ale|0.1.67
vscode-color-picker|Ant|0.0.4
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
gitignore|cod|0.9.0
vscode-eslint|dba|2.4.4
gitlens|eam|14.7.0
vscode-html-css|ecm|2.0.7
prettier-vscode|esb|10.1.0
vscode-jest-runner|fir|0.4.72
copilot|Git|1.154.0
copilot-chat|Git|0.11.1
todo-tree|Gru|0.0.226
multi-replace|jus|0.7.1
intellij-idea-keybindings|k--|1.5.12
git-graph|mhu|1.30.0
vscode-edits-history|mis|0.1.6
vscode-scss|mrm|0.10.0
vsliveshare|ms-|1.0.5905
open-html-in-browser|pea|2.1.10
material-icon-theme|PKi|4.33.0
postman-for-vscode|Pos|0.18.0
vscode-yaml|red|1.14.0
code-spell-checker|str|3.0.1
jest-snapshot-language-support|tle|1.1.1
change-case|wma|1.0.0
unsaved-files-vscode|wra|2.1.3
markdown-all-in-one|yzh|3.6.2
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30933248
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by roblourens** [comment]
It sounds like something is crashing the extension host process- probably an extension. 

Some things to try
- See if you can get a crash dump by following these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report
- Disable some extensions to see if you can figure out which one causes the issue
- Run the command "Start Extension Bisect" which will automatically take you through a bisect process to see which extension caused the issue. Of course this can be a little difficult if it takes a long time to reproduce the crash.

**Comment by alexeychikk** [comment]
@roblourens As I mentioned earlier, I already tried with all the extensions disabled. Anyway, the issue is gone, I don't know what fixed it, but I didn't change anything and everything works as before with all of my extensions enabled.
