### ISSUE TITLE
Launch configuration for installed extension is missing

### ISSUE THREAD

**Issue by willi1s** [Microsoft/vscode#20332]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|duk-debug|HaroldBrenes|0.2.13|

---

Steps to Reproduce:

1. Open debug (Ctrl+Shit+D)
2. Click 'Add Configuration...'
3. No longer able to choose default configuration for installed duktape debugger. This was working with version 1.8.1.

**Comment by isidorn** [comment]
Please file this against the duktape debugger here https://github.com/harold-b/vscode-duktape-debug

And let them know they need to implement configuration snippets as node is doing [here](https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L98)
