### ISSUE TITLE
Change test run decorations when alt is pressed

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#203372]
Love it, would be cool if the icon could change when I hold alt and hover, but I'm not sure we can do that with gutter decorations. I would never find this though, maybe the hover text could say something about alt+click?

_Originally posted by @roblourens in https://github.com/microsoft/vscode/issues/133007#issuecomment-1907039526_

**Comment by roblourens** [comment]
To me, ideally it would only change when I am hovering the icon, because I kind of hate how all menu buttons with alt actions change whenever I press alt anywhere else in the app

**Comment by connor4312** [comment]
Good point. We can do that now that we have better glyph margin hover events 😁

**Comment by connor4312** [comment]
Added this a bit ago
