### ISSUE TITLE
macOS: set acceptFirstMouse for windows

### ISSUE THREAD

**Issue by iramiller** [Microsoft/vscode#20335]
- VSCode Version: 1.9.1
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Open VSCode, open a new document and have an active terminal visible.
2. Verify the cursor can actively type in terminal, switch focus to document... type some text.  Verify cursor is still in the document.
3. Switch focus to another program via mouse click.
4. Switch focus back to VSCode via mouse click within the terminal window area.  Note that the focus in the active document is maintained and focus does not switch to the terminal.
5. A second click in the terminal area switches focus to the terminal.

Expected Behavior:

When clicking in the terminal window (or the editor) to switch focus to VSCode the focus is expected to be in the area of the program clicked.  Focus should not be retained in the previously active area it should switch to the selected component.  The is especially frustrating when multiple editor panes are displayed along with a terminal.  Essentially a 'double click to focus' is required at all times to ensure focus is actually in the portion of the program expected.

**Comment by Tyriar** [comment]
It looks like this is just how Chromium works on macOS, I can repro the same on Chrome when focusing the omnibox, switching windows and then clicking the comment box (a `<textarea>`), focus is retained in the omnibox.

**Comment by bpasero** [comment]
Could be changed via `acceptFirstMouse` option for windows (https://github.com/electron/electron/blob/master/docs/api/browser-window.md) but I think what we have currently is standard expected behaviour on macOS.

**Comment by iramiller** [comment]
The behavior displayed does appear to be standard for _single_ document interfaces, examples abound in most macOS applications.  However for multiple document interfaces a focus switch between child documents is standard behavior during click to focus.

Examples:

- Safari: 
   1. Open a browser window and open at least two tabs. 
   1. Switch focus to another program.
   1. Focus Safari by clicking any part of the chrome or within the current active document. Note window becomes focused and active document is currently focused.
   1. Switch focus to another program.
   1. Focus Safari by clicking one of the other non-selected child documents in the view by clicking on one of the inactive tabs.
   1. Note that the inactive child document becomes the focused, active document, and the Safari window becomes focused.


- Messages.app -- Within the messages window (Command+0) when multiple conversations are displayed selecting any part of the window chrome _except_ other inactive conversations will focus the current conversation.  Focusing the window by clicking an inactive child document will focus the window and switch to that document.

**Comment by bpasero** [comment]
@iramiller unfortunately this flag seems to be too strong such as it would also focus if clicked from another application. I think we need more support from Electron to make such behaviour possible.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
