### ISSUE TITLE
Sticky scroll stealing `space` to toggle check mark

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#203339]
1. Expand an extension proved tree that has some checkboxes
2. Use keyboard to navigate to a tree item with a checkbox
3. Type `space` to toggle the checkbox
![image](https://github.com/microsoft/vscode/assets/38270282/a33fd5d8-e7df-4f56-9b48-16f41678d5de)

**Comment by alexr00** [comment]
Now I can't repro it 🤷‍♀️

**Comment by benibenj** [comment]
This is fixed with #203314
