### ISSUE TITLE
SCM: Show context menu in Incoming/Outgoing node

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#203317]
Testing #203075

We should have context menu actions when the user right clicks the Incoming/Outgoing node, allowing them to control the settings:

    * `scm.showIncomingChanges`
    * `scm.showOutgoingChanges`
    * `scm.showChangesSummary`

**Comment by lszomoru** [comment]
Added an action on the "Incoming/Outgoing" node that should help with discoverability:

<img width="699" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/0a26102f-bfc7-4804-aaba-c9ac3c6695b1">

Menu is also available in the title bar menu:
<img width="460" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/eaa96f9a-ff81-4677-ae3c-e8b1a99fc10c">

**Comment by lszomoru** [comment]
Verification steps:
* Use the "gear" menu on the "Incoming/Outgoing" header, and confirm that clicking the various actions toggles the following settings: `scm.showIncomingChanges`, `scm.showOutgoingChanges`, `scm.showChangesSummary`
    <img width="699" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/0a26102f-bfc7-4804-aaba-c9ac3c6695b1">

* Use the "Incoming/Outgoing" menu that is available in the `...` menu in the title bar menu and confirm that clicking the various actions toggles the following settings: `scm.showIncomingChanges`, `scm.showOutgoingChanges`, `scm.showChangesSummary`
    <img width="460" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/eaa96f9a-ff81-4677-ae3c-e8b1a99fc10c">
