### ISSUE TITLE
[Discussion] Enforce workbench contributions before their lifecycle phase

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#203445]
During verification I saw https://github.com/microsoft/vscode/issues/193623 and it raises an interesting challenge. 

Workbench contributions are registered for a [lifecycle phase](https://github.com/microsoft/vscode/blob/e8eb39bac26ddc87f27ed69fa06c54cd230d18f9/src/vs/workbench/services/lifecycle/common/lifecycle.ts#L152) at which they are instantiated. For the sake of performance we are interested in having very few contributions during early phases (so that they don't compete with editor opening). The recommendation is to use `Restored` or `Eventually` and we are very good at sticking to this rule. 

However, workbench contributions are rarely self-contained. For instance, we often have commands to the side (`registerAction2`).  Those are typically registered statically but depend on what the contribution contributes. This means an action can be invoked _before_ its "partner-contribution" is ready. To tackle this you can

* only register actions when the contribution is registered (which can lead to UI flashes and non-working commands)
* register contribution for a very early phase (which is correct but not great for perf)

Another alternative is to let actions wait for the lifecycle phase of their "partner-contribution" (via `ILifecycleService#when(phase)`). Tho, that can be frustrating for users (extra waiting) and seems like code smell (spread the phase knowledge). A better alternative might be to ask the workbench to ensure the contribution is now ready. That would force-instantiate it and remove it from lifecycle-phase based instantiation. 

The code editor does something similar (it took inspiration from lifecycle phases but took this much further, see [EditorContributionInstantiation](https://github.com/microsoft/vscode/blob/b0d1f894c38a163ac23e400d41c800decede6117/src/vs/editor/browser/editorExtensions.ts#L33)) and it might be time to bring those learnings into the workbench. One difference tho is that workbench contributions often only cause side effects, e.g the presence of an editor type which isn't the contribution itself. 

It might be enough to begin with `IWorkbenchContributionsRegistry#get(contribution: IConstructorSignature<IWorkbenchContribution>`). That function would simply ensure a contribution is loaded (instantiate it unless already done). With that we can add an equivalent to [EditorContributionInstantiation#Lazy](https://github.com/microsoft/vscode/blob/b0d1f894c38a163ac23e400d41c800decede6117/src/vs/editor/browser/editorExtensions.ts#L63) - meaning some workbench contributions are _never_ initialised unless used. Many contributions from the `Eventually`-phase are likely candidates for this

**Comment by jrieken** [comment]
> one worry I have is that the new Lazy is unpredictable because it may actually result in very eager instantiation when the component that requires it is early on

I share that concern but I think it depends how/why `IWorkbenchContributionsRegistry#get` is called, in my mental model that's only from a user-actions (like some action or opening an editor) and not deterministically programatically.

**Comment by bpasero** [comment]
Yeah I am all up for having that new capability and I think it allows us to move early contributions to later phases 👍 

One thing I would like to explore is if we can make early contributions more visible (phases `Starting`, `Ready`). For example, we could have a ESLint rule that requires people to register their intent in some file (similar to NLS) if they really must block the restore phase. This would require an identifier and a description. When we see perf regressions we can diff that file to see how contributions changed, if at all. We can also monitor our success in making more contributions instantiate lazy or late.

On the perf dashboard I would log the identifier when creating the contribution and visualise the timings so that we can see trends.

**Comment by bpasero** [comment]
When PR https://github.com/microsoft/vscode/pull/203802 lands, we have:
* new `registerWorkbenchContribution2` with `id: string`
* new `getWorkbenchContribution(id: string)`
* a new `WorkbenchContributionInstantiation.Lazy`

I have adopted the new method for all contributions of `LifecyclePhase.Starting` and `LifecyclePhase.Ready` but we need an adoption issue for people to look into their contributions.

**Comment by bpasero** [comment]
Continues in https://github.com/microsoft/vscode/issues/203947
