### ISSUE TITLE
Cannot compile all ADPL projects - TOTVS

### ISSUE THREAD

**Issue by pablosnascimento** [microsoft/vscode#203471]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.2
- OS Version: Windows 11 Professional

Steps to Reproduce:

1. Rigth click on any folder of ADVPL project, click on "Recompile All Workspace"
2. 
![Fail compile](https://github.com/microsoft/vscode/assets/15107506/a2adab30-0a84-48e7-a750-ca443534700e)

**Comment by lszomoru** [comment]
Please file an issue in [the extension's repository](https://github.com/totvs/advpl-vscode/issues).
