### ISSUE TITLE
Notebook renders partially over other editors

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#203434]
I had multiple editors open, one of them was a notebook. At some point when I saved the file I was in the notebook suddenly appeared over the typescript file. This happened twice, once when in the typescript file and once in the multi diff editor.

<img width="1921" alt="Code_-_Insiders_G5CU0Db9YP" src="https://github.com/microsoft/vscode/assets/44439583/b98e9f8e-03be-4de6-bce8-c2e2404b2dce">

**Comment by bpasero** [comment]
Maybe a regression from the work to support notebooks in floating windows?
