### ISSUE TITLE
Inconsistent comments in comments view

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#203484]
While verifying https://github.com/microsoft/vscode/issues/200972, I made some a few comments in https://github.com/microsoft/vscode-jupyter/pull/15063 in the github page, insiders-vscode.dev and desktop vscode.
Both .dev and desktop are missing 1 of the 4 comments, but not the same one. Running `Refresh Pull Request Comments` doesn't fix it.

Inconsistent comment list
![image](https://github.com/microsoft/vscode/assets/2019016/0deaa94a-af68-498e-b880-9c0b1334a5a9)

**Comment by alexr00** [comment]
@amunger were changes pushed to the PR while you were leaving these comments? I'm wondering if one of your instances was on an earlier commit and couldn't find the right location for the comment.

**Comment by amunger** [comment]
No commits were made while I was testing this out.
I tried again today, pulled in the latest main with similar results again at first, and but .dev pulled in a comment from a different PR, and after clicking around, it's _only_ showing that unrelated comment.
<img width="1430" alt="image" src="https://github.com/microsoft/vscode/assets/2019016/b61ec143-b960-4ce6-abb2-7f57f40efb76">

**Comment by alexr00** [comment]
What branch do you have checked out in each of those instances?

**Comment by amunger** [comment]
I'm pretty sure I was just on main in the desktop, though trying again today, I don't see any comments until I check out the PR. I was just viewing the changes from the github sidebar as shown there. So, no longer repro'ing on desktop if that's expected.

For .dev, I can still see just three comments when I start viewing the PR while on the main branch, and then after opening the file with the fourth comment, that one shows up too.

**Comment by amunger** [comment]
Feel free to close as won't fix and wait for more feedback - pretty small issue at this point

**Comment by alexr00** [comment]
> For .dev, I can still see just three comments when I start viewing the PR while on the main branch, and then after opening the file with the fourth comment, that one shows up too.

This sounds like it's by design. The initial 3 comments are coming from the PR you have checked out. The additional 4th comment is coming from a different PR: the PR you have expanded in the "Pull Requests" tree and where you clicked on the file.
