### ISSUE TITLE
Test watches for children are not cancelled when their parent is cancelled

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#203496]
From playwright:

"It looks like if I watch single test item, then watch file (parent item) and then unwatch the file, cancellation token is not triggered for the test entry.... When [the parent watch] is canceled, child is canceled in the UI. But child is not cancelled programmatically."

**Comment by andreamah** [comment]
Are there verification steps for this?

**Comment by connor4312** [comment]
- Watch a single test item
- Watch file (parent item) and then unwatch the child
- The cancellation token is not triggered for the child item

Requires debugging an extension that provides tests, such as the selfhost test provider, watching [here](https://github.com/microsoft/vscode-selfhost-test-provider/blob/c318bd91f3644f8a23053c5f9105a8c6c4a1e35e/src/extension.ts#L108) for new requests and [here](https://github.com/microsoft/vscode-selfhost-test-provider/blob/c318bd91f3644f8a23053c5f9105a8c6c4a1e35e/src/extension.ts#L140) for cancellations.

**Comment by eleanorjboyd** [comment]
I get an error trying to build the [vscode-selfhost-test-provider](https://github.com/microsoft/vscode-selfhost-test-provider/tree/c318bd91f3644f8a23053c5f9105a8c6c4a1e35e), does this require using another library? I saw you made a change recently to break this out but not sure what that means for installation. I could also try on the python extension if that would work, I can successfully debug a test and given the test parent is canceled the child gets canceled so I am not sure if that is the same as the required steps here.


npm ERR! enoent ENOENT: no such file or directory, open '/Users/eleanorboyd/testingFiles/istanbul-to-vscode/istanbul-to-vscode-1.0.0.tgz'
npm ERR! enoent This is related to npm not being able to find a file.
