### ISSUE TITLE
Debug session doesn't stop when I reload the Extension Development window

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#203472]
- Start debugging extension
- Reload the Extension Development Host window
- Close the window
- The original vscode window stays in debug mode, and clicking stop doesn't do anything, until I reload it

[vscode-debugadapter-63b8e595.json.gz](https://github.com/microsoft/vscode/files/14056208/vscode-debugadapter-63b8e595.json.gz)

**Comment by connor4312** [comment]
I don't hit this very consistently even with the instructions. However, each time I close the window I see the "Invalid debug adapter" error pop up. Wonder if that's related...
