### ISSUE TITLE
Narrator is announcing incorrect information as 'selected' for options of items in the dropdown of command center

### ISSUE THREAD

**Issue by miniwangdali** [microsoft/vscode#203477]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.2
- OS Version: Windows 11 Enterprise (Windows_NT x64 10.0.22631.3007)

```
Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
```

**Description**

We are making a VS Code extension. During our accessibility test, the tester reports that the Narrator is announcing incorrect information as 'selected' for options which appears in the dropdown of items of command center. For example, if I search for git command, Narrator is announcing as "<command name>, 1 of n, selected on (off)". When I tried to reproduce the problem, it only happens in "[Extension Development Host]" with some command but does not happen on a normal VS Code instance.

Steps to Reproduce:

1.  Turn on an extension development host vscode instance.
2. Turn on Narrator.
3. Go to command center and search for some command. (Optional, this happens even if you don't search for anything)
4. Listen what Narrator says on the provided options.

https://github.com/microsoft/vscode/assets/5415452/ff26f244-0097-4abc-86e6-970ac323ab11

**Comment by meganrogge** [comment]
This is a narrator issue. Pls lmk if it reproduces when using JAWS or NVDA

**Comment by miniwangdali** [comment]
on NVDA, it says "checked" or "not checked" on the selected item, which is also a problem, I think.

**Comment by meganrogge** [comment]
> to reproduce the problem, it only happens in "[Extension Development Host]" with some command but does not happen on a normal VS Code instance.

we will only address issues found within the product.

**Comment by shindepra** [comment]
#A11yMAS; #A11yTCS; #DesktopApp; #Win32; #Visual Studio Code Client; #BM-VisualStudioCodeClient-Win32-Aug2023; #Consistent Identification; #WCAG3.2.4

**Primary Bug ID** : https://microsoft.visualstudio.com/Xbox/_workitems/edit/48288599
