### ISSUE TITLE
No colors on .html files

### ISSUE THREAD

**Issue by daniell0gda** [Microsoft/vscode#20347]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.13.2|
|vscode-twig-pack|bajdzis|1.0.0|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|typings-installer|benjaminromano|0.2.0|
|path-intellisense|christian-kohler|1.2.0|
|theme-dracula|dracula-theme|1.2.5|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|tslint|eg2|0.8.1|
|LogFileHighlighter|emilast|1.0.1|
|output-colorizer|IBM|0.0.10|
|RelativePath|jakob101|0.12.0|
|docthis|joelday|0.3.11|
|tsd-recommender|jrieken|0.0.2|
|cobalt2-Theme|kamranmackey|0.0.3|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|csharp|ms-vscode|1.7.0|
|Theme-PredawnKit|ms-vscode|0.1.1|
|debugger-for-chrome|msjsdiag|2.5.3|
|material-icon-theme|PKief|1.3.2|
|ClassyNaming|reflectiondm|1.0.0|
|theme-obsidian|rprouse|0.2.0|
|code-settings-sync|Shan|2.4.3|
|perforce|slevesque|1.0.0|
|vscode-multiclip|slevesque|0.1.2|
|cucumber|stevejpurves|0.9.6|
|wymseeangular1snippets|wymsee|0.1.17|
|JasmineSnippets|xabikos|0.2.1|

---

Steps to Reproduce:
Don't know, just installed 1.9.1.
![2017-02-09 20_29_04-new issue microsoft_vscode](https://cloud.githubusercontent.com/assets/8320732/22799549/78c02c44-ef06-11e6-85e6-77e395bb4246.png)

**Comment by Tyriar** [comment]
The update likely broke your theme due to the change detailed [here](https://code.visualstudio.com/blogs/2017/02/08/syntax-highlighting-optimizations), in the meantime try using a different one.

**Comment by daniell0gda** [comment]
My theme didn't broke - all themes on *.html are like that :/

**Comment by Tyriar** [comment]
@daniell0gda do you have any errors in the dev tools console? (Help > Toggle Developer Tools)

**Comment by daniell0gda** [comment]
@Tyriar, yup

> Overwriting extension <<.html>> to now point to mime <<text/x-html>>
> Overwriting extension <<.log>> to now point to mime <<text/x-log>>
> Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  170002978  for  docthis.documentThis
> Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  170068514  for  docthis.documentEverything
> Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  171182626  for  docthis.documentEverythingVisible
> Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2612  for  multiclip.list
> Conflict detected, command `editor.action.clipboardCopyAction` cannot be triggered by ctrl+c due to multiclip.copy
> Conflict detected, command `editor.action.clipboardCutAction` cannot be triggered by ctrl+x due to multiclip.cut
> Conflict detected, command `editor.action.clipboardPasteAction` cannot be triggered by ctrl+v due to multiclip.regularPaste
> Unknown injections for grammar <text.html.twig>: Error: Unknown injections for grammar <text.html.twig>
>     at Registry._loadGrammar (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\vscode-textmate\release\main.js:2929:30)
>     at Registry.loadGrammarWithEmbeddedLanguages (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\vscode-textmate\release\main.js:2878:14)
>     at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:137:7819
>     at new n.Class.derive._oncancel (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:19517)
>     at e._createGrammar (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:137:7769)
>     at e.registerDefinition (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:137:8011)
>     at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:137:5415
>     at e.invoke (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:26950)
>     at e.fire (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:30440)
>     at t.e._getOrCreateMode (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:69:26914)
> [Extension Host] Windows_NT

**Comment by Tyriar** [comment]
```
Unknown injections for grammar <text.html.twig>: Error: Unknown injections for grammar <text.html.twig>
at Registry._loadGrammar (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\vscode-textmate\release\main.js:2929:30)
```

I'd blame the vscode-twig-pack extension for this.

**Comment by daniell0gda** [comment]
That is right. After removing and restarting it works like before. Thank you @Tyriar .
