### ISSUE TITLE
Backticks (double) move marker in between

### ISSUE THREAD

**Issue by Thunderiuz** [microsoft/vscode#203475]
Type: <b>Feature Request</b>

Hey,
A great feature that you have is when typing a single quotation mark, parenthesis or other braces, it automatically adds another and places the marker between so that you are ready to type within this field.

I would love the same for backticks ( `` )  as they are used in template literals. I guess however that it would mess up their intended purpose of emphasizing vocals, so maybe the user needs to insert both the backticks, but then at least the marker can safely move automatically in between of them!

Thanks, gg

Ps: marking text and typing double backticks will put the text in between, but with double backticks on each side. Maybe one will do the trick?

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by lramos15** [comment]
I think you want this extension 
<img width="615" alt="image" src="https://github.com/microsoft/vscode/assets/4544166/850a9e82-8a93-4a42-9902-ba595ada9ac0">
