### ISSUE TITLE
Support reordering editor tabs in-between tabs and make consistent across the workbench

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#203441]
When you currently reorder editor tabs we change the background color of the tab you are hovering over, this does not make it very easy to understand where the tab will be placed when the user drops it.

![Code_-_Insiders_AFQpdbKTwl](https://github.com/microsoft/vscode/assets/44439583/64094a5c-05bc-44bb-8133-0edcf715644c)

In future we would like to indicate where the tab will be placed by rendering an indicator between the tabs where it will be placed.

![Code_-_OSS_WIa6jFJOZx](https://github.com/microsoft/vscode/assets/44439583/dac927cb-2d3a-49d8-b0be-717a9896f6eb)

Further improvements could include changing the position of the dragged item in relation to the mouse pointer (top left of the editor tab is placed on the mouse) or changing the rendering of the dragged item. The reason for this is that the rendering of the dragged tab can make it harder to see the drop indicator.

**Comment by bpasero** [comment]
One thing I just realise when playing around with https://github.com/microsoft/vscode/pull/203681 is that we do make it harder now for a tab to be dragged to the location of another tab. 

Previously you could just move it to the far left or right edge:

![Recording 2024-01-30 at 06 48 16](https://github.com/microsoft/vscode/assets/900690/87cd57db-88c8-4c98-9a0c-3fd374b2e2c1)

Now you need to move it all the way:

![Recording 2024-01-30 at 06 49 22](https://github.com/microsoft/vscode/assets/900690/0f59e450-f943-4d04-97a3-64b36a90567e)

This probably deserves a UX discussion with more people involved.

Tagging some more people for thoughts: @hbons @joaomoreno ?

**Comment by benibenj** [comment]
Completed with https://github.com/microsoft/vscode/pull/203681. Still open to feedback
