### ISSUE TITLE
Editor not scrolling to breakpoint if smooth scrolling enabled

### ISSUE THREAD

**Issue by stan-servaenergy** [microsoft/vscode#203490]
Type: <b>Bug</b>

Expected result:
When code execution stops on a breakpoint the editor should scroll so that the line with breakpoint is in view(port).

Actual result:
If 'Editor: Smooth Scrolling' is enabled, the editor will not scroll breakpoint into view when that breakpoint is reached.
If that setting is disabled, it works as expected.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:19.222Z)
OS version: Linux x64 6.6.1-060601-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 2239)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|62.72GB (55.25GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
pythoncpp-debug|ben|0.3.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
vscode-github-actions|git|0.26.2
vscode-peacock|joh|4.2.2
intellij-idea-keybindings|k--|1.5.12
vscode-cython|ktn|0.3.10
rainbow-csv|mec|3.11.0
git-graph|mhu|1.30.0
autopep8|ms-|2023.8.0
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.8.22
autodocstring|njp|0.6.1
sqlite-viewer|qwt|0.3.13
markdown-preview-enhanced|shd|0.8.11
simple-rst|tro|1.5.4
cmake|twx|0.0.17
gitblame|wad|10.7.1

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
I always have `editor.smoothScrolling` enabled, and I have never seen this. Can you include a screen recording or a more specific example?

**Comment by stan-servaenergy** [comment]
Here is an example of what happens on my machine:
[Screencast from 2024-01-25 21-12-19.webm](https://github.com/microsoft/vscode/assets/94936884/007d2107-8b49-4cc3-a6d9-36130f13c6bd)

**Comment by roblourens** [comment]
Strange, thanks for the recording.

**Comment by stan-servaenergy** [comment]
As of:
```
Version: 1.86.2
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:41:37.860Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.6.1-060601-generic
```

smooth scrolling seems to be working as intended for me.
