### ISSUE TITLE
PAC proxy with `--proxy-pac-url` fallbacks to direct when downloading extensions on Linux

### ISSUE THREAD

**Issue by KiruyaMomochi** [microsoft/vscode#203438]
Does this issue occur when all extensions are disabled?: Yes

On Ubuntu 22.04, after provided PAC file with `--proxy-pac-url=<pac_file>` to VS code, it still connects to marketplace.visualstudio.com directly. In netlog I have found `ERR_PAC_SCRIPT_TERMINATED`. This issue is also reproducible on version `1.86.0-insider`. However, it is not reproducible on Windows.

- VS Code Version: 1.85.2
- OS Version: Ubuntu 22.04 Linux x64 6.5.0-15-generic
- Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
- Date: 2024-01-18T06:40:19.222Z
- Electron: 25.9.7
- ElectronBuildId: 26354273
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0

Steps to Reproduce:

Preform the following steps on a fresh Ubuntu 22.04 desktop with only VS Code installed:

1. Install curl, python3 and openssh server
    ```bash
    sudo apt install -y curl python3 openssh-server
    ```
2. Use `ssh` to create a simple SOCKS5 proxy
    ```bash
    ssh -D 1080 localhost
    ```
    Leave this terminal open and start a new one.
3. Ensure that the proxy works
    ```bash
	kyaru@kyaru-virtual-machine:~/Downloads$ curl --proxy socks5://127.0.0.1:1080 -v http://microsoft.com
	*   Trying 127.0.0.1:1080...
	* SOCKS5 connect to IPv4 xxx.xxx.xxx.xxx:80 (locally resolved)
	* SOCKS5 request granted.
	* Connected to (nil) (127.0.0.1) port 1080 (#0)
	> GET / HTTP/1.1
	> Host: microsoft.com
	> User-Agent: curl/7.81.0
	> Accept: */*
	> 
	* Mark bundle as not supporting multiuse
	< HTTP/1.1 301 Moved Permanently
	< Content-Length: 0
	< Date: Thu, 25 Jan 2024 11:25:59 GMT
	< Server: Kestrel
	< Location: https://www.microsoft.com/
	< Strict-Transport-Security: max-age=31536000
	< 
	* Connection #0 to host (nil) left intact
    ```
4. Create a simple proxy PAC file
	```bash
	echo 'function FindProxyForURL(url, host) { return "SOCKS5 127.0.0.1:1080"; }' > proxy.pac
	```
5. Start a simple web server with Python
    ```bash
	python3 -m http.server
	```
   Leave this terminal open and start a new one.
6. Run vscode with the above PAC file and enable network logging
	```bash
	code --proxy-pac-url=http://127.0.0.1:8000/proxy.pac --log-net-log=netlog.json
	```
7. Try to open the extension sidebar and search some extensions
8. Close vscode
9. Open https://netlog-viewer.appspot.com and import the `netlog.json` file
10. Go to `Events` sidebar, check `PROXY_CONFIG_CHANGED` and ensure that the correct PAC file is loaded
11. Searching for `PROXY_RESOLUTION_SERVICE_RESOLVED_PROXY_LIST`, and you will see results with `ERR_PAC_SCRIPT_TERMINATED`. If the searching function does not work, manually check events of `HTTP_STREAM_JOB_CONTROLLER`, you will see some urls like `https://update.code.visualstudio.com/*` getr the correct `pac_string`, but other urls like `https://marketplace.visualstudio.com/*` fails with the following content:
	```log
	63: HTTP_STREAM_JOB_CONTROLLER
	https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
	Start Time: 2024-01-25 19:18:00.323
	
	t=4881 [st=  0] +HTTP_STREAM_JOB_CONTROLLER  [dt=139]
	                 --> is_preconnect = false
	                 --> privacy_mode = "enabled"
	                 --> url = "https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery"
	t=4881 [st=  0]    HTTP_STREAM_JOB_CONTROLLER_BOUND
	                   --> source_dependency = 61 (URL_REQUEST)
	t=4881 [st=  0]   +PROXY_RESOLUTION_SERVICE  [dt=1]
	t=4882 [st=  1]      PROXY_RESOLUTION_SERVICE_RESOLVED_PROXY_LIST
	                     --> net_error = -367 (ERR_PAC_SCRIPT_TERMINATED)
	t=4882 [st=  1]   -PROXY_RESOLUTION_SERVICE
	t=4882 [st=  1]    HTTP_STREAM_JOB_CONTROLLER_PROXY_SERVER_RESOLVED
	                   --> proxy_server = "DIRECT"
	t=4882 [st=  1]    HTTP_STREAM_REQUEST_STARTED_JOB
	                   --> source_dependency = 64 (HTTP_STREAM_JOB)
	t=5020 [st=139] -HTTP_STREAM_JOB_CONTROLLER
	```

Here is the full log file: [netlog.json](https://github.com/microsoft/vscode/files/14051132/netlog.json)

**Comment by chrmarti** [comment]
@KiruyaMomochi Is this still an issue?

**Comment by deepak1556** [comment]
It seems like a crash in the proxy resolver service, can you attach the crash dumps from latest stable following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

Also in the failing case we are running the request with [Privacy_mode_enabled](https://source.chromium.org/chromium/chromium/src/+/main:net/base/privacy_mode.h;l=14) which could have impacted with the type of proxy being used.
