### ISSUE TITLE
Certain widely used file link formats do not detect the line number in the debug console

### ISSUE THREAD

**Issue by DanteMarshal** [microsoft/vscode#203413]
- Does this issue occur when all extensions are disabled ? : Yes

- VS Code Version: 
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
- OS Version: Windows 11

- Description :
Some file address formats (for example in exceptions generated in C#, which is `<filepath>:line <line-num>`) only detect the `<filepath>` part as a link. Therefore when clicked on, it will open the file on line 1, instead of line `<line-num>`.
Note that the line number is detected correctly when displayed using the integrated terminal.

- Steps to Reproduce :
  1. On any C# console project (or anything else that might use the same format) log an exception - Or simply manually print a file link with the format specified above - in the debug console.
  2. Hover the mouse on the file link, it only detects the <filepath> part as a link, not the whole thing.
  3. Click on the link, It will open the file on line 1, while it should've opened it on whatever line number is printed out.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/34026
