### ISSUE TITLE
File: Revert File should work in multi diff editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#203470]
When you edit multiple files in a diff editor, the editor appears dirty and the files open in the background. Picking "Revert File" from the file menu should clear dirty indication.

**Comment by rzhao271** [comment]
Looks like this one will need to be verified next Insiders

**Comment by aiday-mar** [comment]
I will move this issue to February 2024

**Comment by bpasero** [comment]
It should be verified in latest insiders.
