### ISSUE TITLE
Visual label is not defined for the select all checkbox in command parameter.

### ISSUE THREAD

**Issue by miniwangdali** [microsoft/vscode#203402]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.2
- OS Version: Windows 11 Enterprise (Windows_NT x64 10.0.22631.3007)

```
Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
```

**Description**
We are making a vscode extension. The extension has a command to collect some options. the command parameter is a multi select parameter. There is a select all checkbox provided by VS Code for that parameter during the command in command center. In accessibility test, the tester reports that the checkbox does not have a visual label to indicate the title.

![image](https://github.com/microsoft/vscode/assets/5415452/05eff5c6-d81e-4320-b594-ac17d07295fb)

**Comment by meganrogge** [comment]
It is labeled for me. It might be that the user is not using a well supported screen reader. Try JAWS, NVDA, or VoiceOver
<img width="1312" alt="Screenshot 2024-01-25 at 10 46 01 AM" src="https://github.com/microsoft/vscode/assets/29464607/29ca6626-0335-4ec3-b999-1b2eadcd7bc8">

**Comment by miniwangdali** [comment]
It is labeled, but how do you bring up a visual label on that checkbox? I think this does not involve a screen reader yet.

**Comment by shindepra** [comment]
#A11yMAS; #A11yTCS; #DesktopApp; #Win32; #Visual Studio Code Client; #BM-VisualStudioCodeClient-Win32-Aug2023; #Labels or Instructions; #WCAG3.2.2

**Primary Bug ID**: https://microsoft.visualstudio.com/Xbox/_workitems/edit/48287152

**Comment by shindepra** [comment]
#A11yMAS; #A11yTCS; #DesktopApp; #Win32; #Visual Studio Code Client; #BM-VisualStudioCodeClient-Win32-Aug2023; #WCAG3.3.2; #Labels or Instructions;
