### ISSUE TITLE
Link detection defunct in terminal instance

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#203435]
I wasn't success in verifying https://github.com/microsoft/vscode/issues/193384 until I started a new terminal.

I have ` echo "/Users/jrieken/Code/vscode/src/vscode-dts/vscode.d.ts:3:5-19"` and the "old" terminal is doesn't work, in the new it does. Nothing in any of the known logs

https://github.com/microsoft/vscode/assets/1794099/52729047-6258-439d-abfb-b43cccd444a8

**Comment by Tyriar** [comment]
This is a known issue, I'll link that DisposableStore issue to it /duplicate https://github.com/microsoft/vscode/issues/184046
