### ISSUE TITLE
A serous error for the file show. Can not show the error file. 

### ISSUE THREAD

**Issue by Hoper-Q** [microsoft/vscode#203465]
### The child won`t make error tip on vscode when I change parent.
![image](https://github.com/microsoft/vscode/assets/52480108/ce0085bd-0384-4166-a6e2-5ff65f6c27e4)
![image](https://github.com/microsoft/vscode/assets/52480108/8043b9ad-e70c-44d1-8663-e4ce1a9126ac)
![image](https://github.com/microsoft/vscode/assets/52480108/4e1c07bf-4a13-4fd9-828c-edc288ae68d5)
![image](https://github.com/microsoft/vscode/assets/52480108/902dc084-9474-47d1-989c-be7f596dd090)

### But when I Choose the file, it will show the error.
![image](https://github.com/microsoft/vscode/assets/52480108/6946bd43-9a63-43d4-8192-eb3b723ed8e7)
![image](https://github.com/microsoft/vscode/assets/52480108/cddcd5ca-dc7a-480e-ab31-1d6f78009625)

**I want to know how to fix it. Make it show the error at the first time!**

**Comment by roblourens** [comment]
Please file this against the C# extension
