### ISSUE TITLE
Notebook variables view polish

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#203480]
following up on https://github.com/microsoft/vscode/issues/203058

- [x] https://github.com/microsoft/vscode/issues/203060
- [x] https://github.com/microsoft/vscode-jupyter/issues/15056
- [ ]  https://github.com/microsoft/vscode/issues/203067
- [x] https://github.com/microsoft/vscode/issues/203068
- [x] https://github.com/microsoft/vscode/issues/203231
- [x] https://github.com/microsoft/vscode/issues/203237

**Comment by davidanthoff** [comment]
Could https://github.com/microsoft/vscode/issues/204031 be added to this list?

**Comment by brad-griffin** [comment]
Dictionaries appear to be limited to showing only the first 100 keys. Are there any plans to expand this similar to long lists or allow more keys to be shown?

**Comment by amunger** [comment]
it looks like pydebug has a configurable limit of 500, we could follow that same convention here. Would that work for your use case?

**Comment by brad-griffin** [comment]
Yes, that should cover it!
