### ISSUE TITLE
`// @ts-check` on HTML inline script does not respect tsconfig.json

### ISSUE THREAD

**Issue by rance7** [microsoft/vscode#203474]
### 🔎 Search Terms

ts-check inline script tsconfig.json

### 🕗 Version & Regression Information

Typescript version 5.3.3

### 💻 Code

* This is index.html
![image](https://github.com/microsoft/TypeScript/assets/101499419/616f4725-cbe1-4abc-8c3a-8e785449f538)
* This is index.js
![image](https://github.com/microsoft/TypeScript/assets/101499419/58c13412-4a2c-4a79-b7d2-9a640f556bb5)
* This is project structure
![image](https://github.com/microsoft/TypeScript/assets/101499419/92541ab3-8fdd-42b0-841d-6df9e2fc5d3a)
* This is tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "esnext"
    ],
    "module": "esnext",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  },
  "files": [
    "index.js",
    "index.html"
  ]
}
```

### 🙁 Actual behavior

I use `@ts-check` in index.html's html inline script, but it seems that `@ts-check`  fails to read my tsconfig.json. There is an error in index.html's inline script but not int index.js. Their code is exactly the same.

### 🙂 Expected behavior

The script in html inline script should have same behavior as index.js.

### Additional information about the issue

microsoft/TypeScript#25809

**Comment by mjbvz** [comment]
Yes html files cannot belong to a jsconfig project. This falls under #26338
