### ISSUE TITLE
Create multiple folders at once in explorer

### ISSUE THREAD

**Issue by Xemiru** [Microsoft/vscode#20340]
QOL things that make VSCode more convenient and closer to being basically a replacement for most IDEs for me. The editor gives you some control over what you can do within the project folder using the view panel on the left, e.g. new file, new folder. Languages like Java, its derivatives, and a lot of others organize code through a series of folders containing nothing but yet another folder, eventually leading to actual content. It would be convenient if the editor let one create multiple at once in one action, with each folder separated by a slash character (/, \\, \\\\) like in path definitions.

![Example input](http://i.imgur.com/Ak1L5mA.png)

To add onto this functionality, the view bar can be excessively wide just to display subfolders with their correct indentation. Folders containing nothing but a single other folder can be displayed in short-hand to instead display a path leading to the next folder containing more than one directory.

```
src/main
|-- java
    |-- me/scarlet/dbot
        |-- DiscordBot.java
|-- scala
    |-- me/scarlet/dbot
        |-- DiscordBot.scala
```

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12893
