### ISSUE TITLE
Support hypterlinks from terminal to code

### ISSUE THREAD

**Issue by dickreuter** [microsoft/vscode#203455]
When running code like pylint from the terminal, vscode should be smart enough to recognize links to the code

**Comment by meganrogge** [comment]
a screenshot would help to understand what you mean

**Comment by dickreuter** [comment]
This is how it looks like on vscode when I type pylint in the terminal:
![image](https://github.com/microsoft/vscode/assets/1256318/fb1aeca8-30aa-4d24-9602-17e2dfbe1bc8)

and this is how the same looks like in pycharm, with nice hyperlinks to all the errors, directly from the terminal:
![image](https://github.com/microsoft/vscode/assets/1256318/5f1ad0ab-4e1e-4c13-8b0c-4a2313515f85)

**Comment by Tyriar** [comment]
@dickreuter we have pretty advanced link detection in the terminal, you do need to hover it to reveal the link though as we do not want to mess with the terminal text's styles (it could be rendered non-white or have an underline that could be useful). You can read more about how links work here: https://code.visualstudio.com/docs/terminal/basics#_links

If it does not show an underline when you hover _without_ holding ctrl, it means we cannot validate the link is a file on the system. If this happens you should verify that the path is either absolute or relative to the terminal's current working directory. If everything seems correct and it still doesn't work, could you share the exact text, a screenshot (with left side intact) and a screenshot of the file structure in the explorer?

**Comment by dickreuter** [comment]
All I can say is, the current system in vscode is highly inferior to what is available in pycharm, which recognizes all those links very easily. Vscode does not recognize them.

**Comment by Tyriar** [comment]
@dickreuter meaning you hover the link and it does not show an underline? It is by design that we do not change the color or show an underline until it's hovered.

**Comment by dickreuter** [comment]
Hover over it, ctrl-click on it, click on it, whatever I do, nothing happens. It’s as if it’s not even trying to parse the links. Basically whenever I run tests, I have to switch back to pycharm, otherwise it’s impossible to see where it fails without spending a lot of time manually trying to find the links.

From: Daniel Imms ***@***.***>
Date: Monday, 29 January 2024 at 20:43
To: microsoft/vscode ***@***.***>
Cc: Nicolas Dickreuter ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/vscode] Support hypterlinks from terminal to code (Issue #203455)

@dickreuter<https://github.com/dickreuter> meaning you hover the link and it does not show an underline? It is by design that we do not change the color or show an underline until it's hovered.

**Comment by Tyriar** [comment]
You should be able to ctrl+click anything in the terminal, so I suspect you're hitting this annoying issue where sometimes the links system just breaks down which is tracked in https://github.com/microsoft/vscode/issues/184046. Thanks for the info!

**Comment by dickreuter** [comment]
I think it would help a lot if the hyperlinks were highlighted in blue.
