### ISSUE TITLE
#file variable is rendered wrong in multi-root workspaces

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#203574]
<img width="377" alt="image" src="https://github.com/microsoft/vscode/assets/323878/2ca0482c-8368-44f8-9a30-91d05847fc9d">

**Comment by roblourens** [comment]
Verification step- just use a `#file` variable in a multiroot workspace, and check that you have the right blue background when it's rendered in the request.

**Comment by isidorn** [comment]
Works great.
Slightly related - why do we just render the blue background while I am typing the request, but do not render it blue when the request is sent. This was always the behaviour and is unrelated to MR workspace. I am just curious

![Screenshot 2024-01-29 at 15 31 17](https://github.com/microsoft/vscode/assets/1926584/728cecc7-f71b-49a7-9b32-f5a7ce455180)

**Comment by roblourens** [comment]
If it was used correctly, it will have the blue background. Did you pick the file from the picker, or just type the text?

**Comment by isidorn** [comment]
Picked from file picker.


https://github.com/microsoft/vscode/assets/1926584/bdc69641-4d64-4b78-8632-698e56341f1f

**Comment by roblourens** [comment]
Oh no!

**Comment by roblourens** [comment]
Apparently I didn't test this as thoroughly as I should have. Some files now break the markdown link. Need to rework this in main for debt week but there is an easy fix for now.

**Comment by roblourens** [comment]
For verification, we should test with

- Files in a multiroot workspace
- In single folder window
- Files at the top level of the workspace
- And under a folder

**Comment by aiday-mar** [comment]
Since the PR has been merged yesterday, this issue will be closed, for verification.
