### ISSUE TITLE
Python runs extremely slow when run from virtualenvironment

### ISSUE THREAD

**Issue by m4k3rz** [microsoft/vscode#203505]
Type: <b>Bug</b>

Hello,
When i run a simple "Hello World" program, it takes a lot more time when run from a virtual environment as opposed to running the same program from a global workspace (so no virtual environment). The simple Hello World program is just to illustrate what happens in a bigger scale when i try to compile a more complex program with a lot of imports and lines of code. Essentially, no matter what program i run, when ran from the virtual environment is extremely slow in comparisson when run with no virtual environment

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400F (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.62GB free)|
|Process Argv|--crash-reporter-id ffd1e91b-55a8-46ce-ba09-8779879a464c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
0bi6i642:30933247
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by roblourens** [comment]
This sounds like an issue with python itself, not with vscode. If it's an issue with the python integration in vscode, you can file this on the python extension.
