### ISSUE TITLE
Access an extension's page from the Running Extensions list tab

### ISSUE THREAD

**Issue by JimSaiya** [microsoft/vscode#203588]
There should be a way to get to an extension's page from an entry in the Running Extensions tab.  The mouse pointer becomes a pointing hand when you roll over an entry, but clicking doesn't seem to do anything.  (Right-clicking does bring up a menu, as expected.)

**Comment by sandy081** [comment]
Probably we should integrate Running Extensions editor with Extension Editor which is showing already most of the information that is available in the former.

CC @isidorn @alexdima @jrieken @joaomoreno Opinions?

**Comment by jrieken** [comment]
The running extensions editor gives a nice overview which we would loose when move it into the extension editor. Tho, duplicating some of the info isn't a concern to me

**Comment by isidorn** [comment]
I just checked and in the previous 28 days 56K folk opened the runtime extensions editor. That is like 0.2% of our user base.
So I am fine if we get more creative/aggressive about the changes for the runtime editor in general.
