### ISSUE TITLE
Unable to debug the Extension Debugger code in Python Extension

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#20358]
- VSCode Version: 1.9.1
- OS Version: Windows 8 and OS X

Steps to Reproduce:

1. Download Python repo into the Extension directory:  
```C:\Users\xxx\.vscode\extensions\pythonVSCode```  
```https://github.com/DonJayamanne/pythonVSCode.git```
2. Open the ```pythonVSCode``` directory in VS Code  
```npm install```
```Tasks: Run Build Task```
3. From debug Panel select ```Launch Extension as debug server```  
Output in debug console is as follows:  
```
node --debug-brk=35378 --harmony out\client\debugger\Main.js --server=4712 
Debugger listening on [::]:35378
waiting for debug protocol on port 4712
```
4. Add a breakpoint into the debugger code  
```src\client\debugger\Main.ts```  

5. Open another instance of VS Code   
- Open a folder with a Python file  
- Go into launch.json and add the following:  
```json
{
    "version": "0.2.0",
    "debugServer": 4711,
    "configurations": [{
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": null,
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
```
- Start debugging a simple python file with a simple print statement.

6. Expected: Debugger in VS Code should break into the extension debugger code, it doesn't.

***NOTE*** 
- This used to work last year. Not sure when it stopped working.
- No errors displayed in ```Console``` window of ```Developer Tools```

**Comment by DonJayamanne** [comment]
Possibly related issue: https://github.com/Microsoft/vscode-mock-debug/issues/10

**Comment by weinand** [comment]
@DonJayamanne the `"debugServer": 4711,` setting has to go inside the "Python" launch config. We've deprecated the global location some milestones ago.

**Comment by DonJayamanne** [comment]
Thanks, works perfectly
