### ISSUE TITLE
Cannot use arrow keys to switch between menus.

### ISSUE THREAD

**Issue by DeBTech** [Microsoft/vscode#20352]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.15031
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|cpptools|ms-vscode|0.10.0|

---

Steps to Reproduce:

1. Alt-F to drop down the File menu.
2. Pressing left or right arrow should switch to neighboring menus, but it doesn't.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1569
