### ISSUE TITLE
Too many changes pending

### ISSUE THREAD

**Issue by TraceyP89** [microsoft/vscode#203579]
Type: <b>Performance Issue</b>

I am showing that I have over 10k changes in source control. How do I fix this?

VS Code version: Code 1.85.2 (Universal) (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:32.531Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   30	   287	  8825	code main
    0	    66	  8826	   gpu-process
    0	    33	  8827	   utility-network-service
    0	   303	  8829	window [1] (OOP_Practice)
    0	    90	  8849	shared-process
    0	     0	  8970	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    49	  8877	fileWatcher [1]
    0	    49	  8878	ptyHost
    0	     0	  8889	     /bin/zsh -il
    0	   131	  8879	extensionHost [1]
    1	   205	  8925	     /usr/local/share/dotnet/dotnet /Users/trace_code89/.vscode/extensions/ms-dotnettools.csharp-2.16.24-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.LanguageServer.dll --logLevel Information --telemetryLevel all --extensionLogDirectory /Users/trace_code89/Library/Application Support/Code/logs/20240126T180114/window1/exthost/ms-dotnettools.csharp
    0	    90	  8965	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (OOP_Practice)
|    Folder (OOP_Practice): 2 files
|      File types: DS_Store(1) cs(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|2.16.24
vscode-dotnet-runtime|ms-|2.0.1
vscodeintellicode-csharp|ms-|0.1.26
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
live-server|ms-|0.4.13
powershell|ms-|2024.0.0
material-icon-theme|PKi|4.33.0
LiveServer|rit|5.7.9
vscode|uno|0.12.0
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
0bi6i642:30933247
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019acf:30933242
7j2b6412:30949929

```

</details>

**Comment by IllusionMH** [comment]
What does `git status` say? Does it match VS Code?

If yes - make sure you have proper .gitignire
