### ISSUE TITLE
Vscode LLDB Debugger Gets Stuck When Trying to Debug Rust Inside a Dev Container

### ISSUE THREAD

**Issue by mcmah309** [microsoft/vscode#203565]
Vscode lldb debugger gets stuck when trying to debug rust container inside a dev container. Here's an example, it stays like this forever

https://github.com/microsoft/vscode/assets/56412856/0c1393d3-c752-44d4-b4a3-256dd6bcc19e

.devcontainer
```
{
	"name": "rust_dev",
	"image": "rust_dev",
	"customizations": {
		"vscode": {
			"extensions": [
				"rust-lang.rust-analyzer",
				"serayuzgur.crates",
				"vadimcn.vscode-lldb"
			]
		}
	},
	"mounts": [
		// rust
		"source=/home/henry/.local/share/containers/storage/volumes/rust_dev/_data/root/.cargo,target=/root/.cargo,type=bind",
		"source=/home/henry/.local/share/containers/storage/volumes/rust_dev/_data/root/.rustup,target=/root/.rustup,type=bind"
	],
	"runArgs": [
		"--net=host",
	],
	"remoteUser": "root"
}
```

Compiling with cargo and running with vscode works fine.

The output that is notable is this
```
Warning: codelldb.cargo tasks are unavailable in the current environment.

Warning: codelldb.cargo tasks are unavailable in the current environment.
```

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.13

**Comment by roblourens** [comment]
Please file this against the debug extension, and be sure to share the launch config, thanks

**Comment by mcmah309** [comment]
@roblourens I don't know if this is entirely on the lldb extension side. I say that because canceling the debugger does not work. Vscode will not cancel the debugger no matter what I try - disconnect, restart, stop, etc. My only option is to shutdown the Vscode instance. Vscode should be able to handle this.

**Comment by roblourens** [comment]
I'm guessing that killing the task in the terminal would get it unstuck.
