### ISSUE TITLE
vscode not clickable when on fullscreen in a dual-monitor setup

### ISSUE THREAD

**Issue by lastikas** [Microsoft/vscode#20353]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 3.16.0-4-amd64
- Extensions:

|Extension|Author|Version|
|---|---|---|
|erb|CraigMaslowski|0.0.1|
|ejs-language-support|QassimFarid|0.0.1|
|vscode-html-to-elm|Rubymaniac|0.0.2|
|haskelly|UCL|0.4.10|
|elm-format|abadi199|0.1.0|
|vscode-caniuse|agauniyal|0.4.0|
|vscode-color|anseki|0.2.3|
|one-monokai|azemoh|0.2.4|
|vscode-eslint|dbaeumer|1.2.5|
|python|donjayamanne|0.5.8|
|an-old-hope-theme-vscode|dustinsanders|1.1.0|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|Theme-TwoStones|gerane|0.0.2|
|Theme-monokai-best|gerane|0.0.2|
|hopscotch|idleberg|0.1.4|
|Angular2|johnpapa|1.0.2|
|language-polymer|jonwolfe|0.7.10|
|theme-onedark-sublime|joshpeng|0.3.6|
|Theme-MaterialKit|ms-vscode|0.1.1|
|theme-oceanicnext|naumovs|0.0.4|
|java|redhat|0.0.10|
|vscode-icons|robertohuertasm|7.2.0|
|elm|sbrink|0.8.3|
|theme-tinaciousdesign|tinaciousdesign|0.1.1|
|theme-dop|Tysian|0.1.0|

Steps to Reproduce:

1. Have a dual-monitor system in place
2. In one monitor launch vscode
2. In the other monitor lauch some other application
3. In vscode toggle fullscreen
4. Interact with the other application, in the other monitor, with the mouse, click on it
5. Try to interact with vscode. It should 'disapear' revealing whatever application is running below it

------

This problem happens with
*   fullscreen
*   zen mode
*   even when launching vscode with --disable-extensions

------

It's easier to see what happens when there's another application running on the same monitor as vscode. (It's not necessary to reproduce though)

------

I've recorded the session to a gif which I'll atach to this issue

In it, at first, I launch an Electron app and then toggle fullscreen, just to see if the problem appears (it doesn't)

Then I toggle fullscreen on vscode and the problem is reproduced

If the application on the other screen is also in fullscreen mode, then the problem doesn't occur - this can be seen in the gif

------

I have experimented with other Electron based apps and this behaviour was not reproduced

![vscode_fullscreen](https://cloud.githubusercontent.com/assets/1664234/22803004/35aa6b88-eefa-11e6-9d13-632a1bd5d722.gif)

**Comment by Tyriar** [comment]
@lastikas what distro/version are you using?

**Comment by lastikas** [comment]
Debian 8 with Gnome 3

**Comment by bpasero** [comment]
Does it reproduce if you run `code --disable-gpu`?

**Comment by lastikas** [comment]
@bpasero it does not reproduce with --disable-gpu

**Comment by bpasero** [comment]
Ok, so that is a workaround then 👍

**Comment by bpasero** [comment]
Still happening?

**Comment by lastikas** [comment]
I can't reproduce this any longer.

At the moment I'm using a different machine and the problem never appeared with this setup.
