### ISSUE TITLE
Maximize/Minimize and Menubar Buttons are missing sometimes

### ISSUE THREAD

**Issue by murshidameenpv** [microsoft/vscode#203596]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.85.2 (user setup)
- OS Version: Windows 11 Home ( 10.0.22631 Build 22631 )
![Screenshot 2024-01-27 151342](https://github.com/microsoft/vscode/assets/82975683/d9669e28-7a41-41c0-bfac-df5a336435a8)

I’ve been experiencing an issue with my Visual Studio Code where the menu bar and the maximize/minimize buttons (top section) disappear intermittently. This doesn’t happen all the time, but when it does, it’s quite disruptive as I have to restart the application and all the servers. I want to clarify that I haven’t manually hidden it. The issue is only with the menu bar and the maximize/minimize buttons, not the entire top section. Has anyone else encountered this issue? If so, could you please provide any solutions or workarounds?

**Comment by bpasero** [comment]
Sorry for spam, I had wrongly assumed this is on macOS for where I do have a known issue that I plan to fix, but this is Windows and not impacted by my change.

**Comment by murshidameenpv** [comment]
Still facing this annoying issue............

**Comment by sbatten** [comment]
This appears like you are in full screen mode, have you pressed F11? Pressing again would bring those controls back

**Comment by murshidameenpv** [comment]
Fixed, thank you

**Comment by Jishan-Molla** [comment]
> Fixed, thank you

kivabe fix hoilo?
