### ISSUE TITLE
When SSH connection fails, the pop-up message blocks another window

### ISSUE THREAD

**Issue by kirilllzaitsev** [microsoft/vscode#203592]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: Ubuntu 22.04

Steps to Reproduce:

0. Open two windows
1. Being connected to a VPN, open an SSH connection in one of the windows
2. Disable VPN
3. Observe the SSH error "Connection timed out" in another (local) window

Pressing the "More Actions" button in the pop-up redirects back to the SSH window to pick an action.

```
Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:19.222Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.19.0-1028-lowlatency
```

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/201686
