### ISSUE TITLE
Performance issues in my VSCODE development IDE

### ISSUE THREAD

**Issue by pmorellg** [microsoft/vscode#203566]
My vscode keeps closing unexpectedly and it's significantly slowing down my PC. I have Debian 12 installed, and I have the latest version of vscode installed at the time of making this report. My PC is a Lenovo laptop with a 500 GB solid-state drive and 16 GB of RAM. The unexpected closure usually occurs when I try to compile my Flutter project or when I proceed to debug it.

**Comment by roblourens** [comment]
You can try to capture crash logs by following the steps here

https://github.com/microsoft/vscode/wiki/Native-Crash-Issues

It sounds like it may be related to the flutter compiler, or extension, though.
