### ISSUE TITLE
Letter spacing in inactive terminals becomes incorrect when `terminal.integrated.gpuAcceleration` is turned off

### ISSUE THREAD

**Issue by mouse2-1** [microsoft/vscode#203598]
Type: <b>Bug</b>

Does this issue occur when all extensions are disabled?: Yes

Steps:

1. Set `terminal.integrated.gpuAcceleration` to any one of `on`, `canvas`, `auto`.
2. Open multiple terminals.
3. Set `terminal.integrated.gpuAcceleration` to `off`.
4. Now the active terminal automatically refreshes and becomes normal, but the inactive terminals have extremely large letter spacing.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.27GB free)|
|Process Argv|--crash-reporter-id acab1aa0-6d2d-496c-8415-9ac98a47aea8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|7.70GB (6.80GB free)|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.1.4
better-comments|aar|3.0.2
Bookmarks|ale|13.4.2
language-gas-x86|bas|0.0.2
Doxygen|bbe|1.0.0
codespaces|Git|1.14.15
remotehub|Git|0.60.0
better-cpp-syntax|jef|1.17.2
better-dockerfile-syntax|jef|1.0.2
lex|lun|0.1.0
Kotlin|mat|1.7.1
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.106.4
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.9
remote-explorer|ms-|0.4.1
material-icon-theme|PKi|4.29.0
nas-vscode|rig|0.0.1
vscode-native-svg-preview|snd|1.72.0
ninja|sur|0.0.1
octave|toa|0.0.3
pdf|tom|1.2.2
linkerscript|Zix|1.0.3
latex-workshop|Jam|9.18.0
cmake-language-support-vscode|jos|0.0.9
vscode-clangd|llv|0.1.26
vscode-dotnet-runtime|ms-|2.0.0
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.16.32
hexeditor|ms-|1.9.12
vscode-sort-json|ric|1.20.0
latex-utilities|tec|0.4.10
cmake|twx|0.0.17
vscode-ltex|val|13.1.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
0bi6i642:30933247
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019a:30933241
3ef8e399:30949928

```

</details>

**Comment by meganrogge** [comment]
I cannot reproduce this. I'm guessing it's related to your GPU on the remote. Don't think this is actionable on our end, @tyriar pls correct me if i'm wrong
