### ISSUE TITLE
Keyboard settings lock up and change bindings

### ISSUE THREAD

**Issue by nergmada** [Microsoft/vscode#20354]
- VSCode Version: 1.9.1
- OS Version: Windows 10 (Surfacebook)

Just installed the latest updates for VS Code on my Surfacebook. I typical use the UK layout because when I touch type I don't look at keys and naturally go for the layout I grew up with. On VS Code I switch into the US layout (because I can't use backslash without switching to US).

Whilst using the new version of VS Code if I change pages, the keyboard settings lock up, the keybindings change and when I press certain keys they correspond with neither US nor UK layouts nor Romanian (The only other keyboard I have active).

Steps to Reproduce:

1. Open VSCode, switch to US Keyboard layout from default UK Layout
2. Type in a file
3. Switch to another file
4. Attempt to type (try using stuff like quote marks - alphanumerical characters seems unaffected)
5. Also note that with VS Code still in focus (important, don't switch to another program), the keyboard switcher (in the bottom right corner) freezes and doesn't work.

The keyboard doesn't switch in any other programs (including other text editors and IDEs), it just seems to have started in VS Code.

**Comment by alexandrudima** [comment]
In 1.11, on Windows, we now detect keyboard layout changes and refresh our keybindings tables appropriately
