### ISSUE TITLE
Format selection with ...

### ISSUE THREAD

**Issue by Alphapage** [microsoft/vscode#203595]
Hello,

I am building documentation using a simple txt.
When I write some javascript example, I want to select this code, then format the selection using js formatter.
I should be able to do the same with any other languages.

So, it would be very useful to add a "Format selection with ..." menu when right clicking and being able to select the desired language or formatting tool from the dropdownlist to apply the requested formatting.

I can't find a way to do this right now, but maybe someone can teach me.

Thank you in advance for your answers.

**Comment by RedCMD** [comment]
the way VSCode is setup currently 
each language would have to adapt to it individually
