### ISSUE TITLE
Inline chat holds on to untitled documents (part 2)

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#203510]
this is a long-ish demo of a potential 🐛  that is still of happening:
- when the file becomes dirty (ie, copilot writes some code), closing out and dismissing the save will not increment the `untitled` names (what was mentioned in this issue).
- But when copilot doesn't write code, closing it out and using `ctrl+n` again for a new file opens a file with the name `Untitled-2` (increments the untitled name)

https://github.com/microsoft/vscode/assets/54879025/26235c46-3fe9-47fa-a5bc-70bbec12e554

_Originally posted by @justschen in https://github.com/microsoft/vscode/issues/203448#issuecomment-1911515007_

**Comment by jrieken** [comment]
@bpasero I need you input here. Today, I listen to untitled document [becoming non-dirty](https://github.com/microsoft/vscode/blob/5cbd1a836b1186b96bb945e6b4240dec5787db03/src/vs/workbench/contrib/inlineChat/browser/inlineChatSessionServiceImpl.ts#L128-L138) but in this case it never was dirty. It feels like I am missing an event. Do I need use the events of editor tabs to see if no tab exists anymore?

**Comment by bpasero** [comment]
Lets talk when we are both in the office, there is something in the untitled land that I was planning to change in debt land that could be related.

The rule for incrementing the counter for untitled files is based on whether an untitled model still exists:

https://github.com/microsoft/vscode/blob/feff7c8a7e1c82320380f42d898a1e03051fefb7/src/vs/workbench/services/untitled/common/untitledTextEditorService.ts#L241-L245

So maybe someone still holds a reference to the untitled file and thus it does not get disposed. Remember that last milestone I had changed untitled models to be strictly disposable only when the last reference is disposed, even on revert.

**Comment by jrieken** [comment]
> So maybe someone still holds a reference to the untitled file and thus it does not get disposed.

🙋 that's me and the culprit of this issue. Inline chat creates references to the models it uses. That's because when changing between editor tabs I need to hold on to things. This is also true for closing but when closing non-dirty untitled editor I want to release sessions (e.g stop preventing to dispose them)
