### ISSUE TITLE
Native-style title bar breaks on windows with latest dev build

### ISSUE THREAD

**Issue by fallenwood** [microsoft/vscode#203514]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

Version: 1.86.0-insider
Commit: feff7c8a7e1c82320380f42d898a1e03051fefb7
Date: 2024-01-26T03:26:40.730Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

Latest dev
![image](https://github.com/microsoft/vscode/assets/11188646/04c42c20-0e8c-4d5e-8f3b-39314cd53b75)

Expected (with codium)
![image](https://github.com/microsoft/vscode/assets/11188646/28f88ae2-26a9-473e-b2db-aca1e08edefa)

Is it a bug or new feature?

**Comment by benibenj** [comment]
This is a new feature. It's now possible to have the native and custom title bar at the same time. If you don't wish to see it you can hide it by either right clicking it and pressing `hide custom title bar` or by modifying the `window.customTitleBarVisibility` setting.
