### ISSUE TITLE
Running the task generated an ugly exe program

### ISSUE THREAD

**Issue by goshut** [microsoft/vscode#203617]
Type: <b>Bug</b>

I used running tasks to build a program for a source file of "中文. c", but only generated one "ÖÐÎÄ.exe" ugly program . (it can run normally)

This is my tasks.json
```json
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe 生成活动文件",
            "command": "D:\\tool\\gcc_huanjing\\msys64\\ucrt64\\bin\\g++.exe",
            "args": [
                // "-std=c++20",
                // "-fexec-charset=GBK",
                // "-finput-charset=UTF-8",
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
                // "${fileDirname}\\AAA.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "调试器生成的任务。"
        }
    ],
    "version": "2.0.0"
}
```

I copied the command on the right and ran it in cmd
```
"D:\tool\gcc_huanjing\msys64\ucrt64\bin\g++.exe" -fdiagnostics-color=always -g "D:\test\c++test\VC_c++_test\中文.c" -o "D:\test\c++test\VC_c++_test\中文.exe"
```
It generated a "中文. exe" normally

So what is the reason why run tasks cannot generate normal file names?

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500X 6-Core Processor              (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.83GB free)|
|Process Argv|--crash-reporter-id 0a5f526b-9295-4cff-a79f-c32d193f325e|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.3.0
viztracer-vscode|gao|0.2.2
intellij-idea-keybindings|k--|1.5.12
vscode-language-pack-zh-hans|MS-|1.85.2024012409
black-formatter|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.17.7
cpptools|ms-|1.19.2
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30933247
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019a:30933241
3ef8e399:30949928

```

</details>

**Comment by goshut** [comment]
<img width="1024" alt="屏幕截图 2024-01-28 033605" src="https://github.com/microsoft/vscode/assets/45934628/795a991f-2ee9-4b2a-a59c-ce3f9d4cbe47">
<img width="1024" alt="屏幕截图 2024-01-28 033751" src="https://github.com/microsoft/vscode/assets/45934628/2dd09c7e-229f-4d2d-9ecd-3328295265b7">

**Comment by goshut** [comment]
I conducted a small experiment and created an empty file called "中文. exe" in my folder, then ran the task

An interesting thing happened, my empty file became a runnable exe program with incorrect names

So I figured out the whole process :
 run tasks first created the exe program correctly, so it overwritten my empty file with the same name, **and then a program gave it an ugly name**😅😅

**Comment by goshut** [comment]
So how do I close this renaming program or make it work properly?

**Comment by meganrogge** [comment]
I am not sure what renaming program you have.

**Comment by goshut** [comment]
This program to change the name comes from mingw64 packaged by msys2.
The problem disappeared when I changed to another compiler.
