### ISSUE TITLE
my explorer tab is gone

### ISSUE THREAD

**Issue by RichmondLim** [microsoft/vscode#203610]
ADD ISSUE DESCRIPTION HERE

Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
Please use the Reset View Locations command from the Command Palette (F1)

**Comment by lramos15** [comment]
Let me know if what John Murray said doesn't help, then I will reopen the issue
