### ISSUE TITLE
Add telemetry when inline chat is opened by sparkle

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#203678]
When the sparkle icon is clicked, we don't go through the normal code path and no code action telemetry is sent.

The fix changes that and adds a new ApplyCodeActionReason to track these events.

**Comment by gdamiaN538** [comment]
@

**Comment by aiday-mar** [comment]
Since the corresponding PRs have been merged, this issue will be closed.

**Comment by aeschli** [comment]
Verified in Version: 1.86.0
Commit: 8c08612b658a37f96892f8ed5a9c6e7a6667847d
Date: 2024-01-30T23:42:45.728Z
