### ISSUE TITLE
Timeline history not working with Jupyter notebooks

### ISSUE THREAD

**Issue by rodders99** [microsoft/vscode#203685]
Type: <b>Bug</b>

I can't seem to get timeline working with some Jupyter notebooks.

Some Notebooks in the same project folder will show their timeline, some will not.

I tend to hit the sleep button on my machine at the end of the day, could it be something to do with that? 

The notebooks that have no timeline history are the ones generally unsaved (yeah I know) at the time of hitting the sleep button. However other open saved notebbok still seem to work.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:19.222Z)
OS version: Linux x64 6.1.0-11-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-4350 Quad-Core Processor (4 x 4219)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|31.37GB (17.19GB free)|
|Process Argv|--unity-launch --crash-reporter-id a66c7410-8ef6-4b63-affa-d7e39ecddda2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color-picker|Ant|0.0.4
vs-notes|Arm|1.2.0
markdown-emoji|bie|0.3.0
markdown-mermaid|bie|1.21.0
markdown-preview-github-styles|bie|2.0.3
markdown-yaml-preamble|bie|0.1.0
gitignore|cod|0.9.0
vscode-markdownlint|Dav|0.54.0
githistory|don|0.6.20
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
vscode-html-css|ecm|2.0.7
vscode-front-matter|eli|9.4.0
copy-markdown-as-html|jer|1.1.0
nbpreviewer|jit|1.2.2
start-git-bash|McC|1.2.1
rainbow-csv|mec|3.11.0
csharp|ms-|2.15.30
vscode-dotnet-runtime|ms-|2.0.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
autodocstring|njp|0.6.1
r|REd|2.8.2
table-editor|ssw|0.3.14
code-spell-checker|str|3.0.1
even-better-toml|tam|0.19.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8
python-auto-venv|Wol|1.3.2
jupyter-toc|xel|0.2.1
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
0bi6i642:30933247
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019acf:30933242
3ef8e399:30949928

```

</details>

**Comment by rebornix** [comment]
@bpasero any suggestion for how to troubleshoot?

**Comment by bpasero** [comment]
Is there anything in the logs?

Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line
* reproduce the issue
* attach the log files you find from running the command "Open Logs Folder"

Thanks!

/duplicate https://github.com/microsoft/vscode/issues/197496

**Comment by rodders99** [comment]
Thanks for responding, 

The only thing that stands out is the size of the file, it's an 8.2Mb notebook and all other smaller files seem to be showing their history correctly. 

I seem to recall reading that file size has something to do with file history?

**Comment by bpasero** [comment]
@rodders99 yes the max file size is `256kb` and can be configured via `workbench.localHistory.maxFileSize`
