### ISSUE TITLE
Terminal Issue 

### ISSUE THREAD

**Issue by IslamAtif** [microsoft/vscode#203633]
ADD ISSUE DESCRIPTION HERE

Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Embedder: codespaces

![2024-01-28](https://github.com/microsoft/vscode/assets/42310482/06ec6835-6326-4f37-a23d-706a87bca600)
As Screen Can't Play Any Code

**Comment by IslamAtif** [comment]
Problem Not Solved Yet

**Comment by onurravli** [comment]
Can you describe your problem more detailed?
