### ISSUE TITLE
Mistakenly Deleted file permanently

### ISSUE THREAD

**Issue by Jubrilake** [microsoft/vscode#203624]
Type: <b>Bug</b>

How can i recover permanently deleted file.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (2.12GB free)|
|Process Argv|--crash-reporter-id b11ba0b1-a658-4728-9f2c-5fcba167e9da|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.10.5
npm-intellisense|chr|1.4.5
vscode-eslint|dba|2.4.4
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|10.1.0
figma-vscode-extension|fig|0.3.2
copilot|Git|1.154.0
copilot-chat|Git|0.11.1
rest-client|hum|0.25.1
dotenv|mik|1.0.1
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.28.0
remote-containers|ms-|0.327.0
remote-wsl|ms-|0.81.9
color-highlight|nau|2.5.0
LiveServer|rit|5.7.9
console-ninja|Wal|1.0.274
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
0bi6i642:30933247
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by bpasero** [comment]
Maybe from the timeline:

<img width="723" alt="image" src="https://github.com/microsoft/vscode/assets/900690/5644682f-6b9d-47e3-a48d-5f346970f8c3">

**Comment by onurravli** [comment]
I don't think neither this is a bug nor related with Visual Studio Code. Which operating system do you use?

**Comment by Jubrilake** [comment]
Windows. I also checked timeline and trash not there .

**Comment by UkiTenzai** [comment]
> Maybe from the timeline:
> 
> <img alt="image" width="723" src="https://private-user-images.githubusercontent.com/900690/300247839-5644682f-6b9d-47e3-a48d-5f346970f8c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTU5MjksIm5iZiI6MTcwOTcxNTYyOSwicGF0aCI6Ii85MDA2OTAvMzAwMjQ3ODM5LTU2NDQ2ODJmLTZiOWQtNDdlMy1hNDhkLTVmMzQ2OTcwZjhjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQwOTAwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWZkMjIzMDZjZjBjMDA3NzlmNzgyZDY4NzhlOWFjOTQ0MDQ4ZjE4Y2RmOGQyN2UwZjA1ZmVmYzE4NmE2OTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._SI7vwRfUoyZLcknl50VHPeGdSMV_5XyWjj-IXt4wII">

I work on ubuntu20.04 using vscode ssh. By this way I can recover files but not folders. If you can provide any solutions, I would greatly appreciate it.
