### ISSUE TITLE
why display problems of other projects in current project?

### ISSUE THREAD

**Issue by axolo** [microsoft/vscode#203660]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.2
- OS Version: windows 11

Steps to Reproduce:

- 1. open project A have problems and colse project.
- 2. open project B, problems of project A display in project B ???

**Comment by sandy081** [comment]
These problems are generated by the extension and therefore extension is responsible to clean up or manage them. Please file the issue against the extension.
