### ISSUE TITLE
editor.formatOnPaste: Is there a way to control the formatting used when pasting?

### ISSUE THREAD

**Issue by jrnail23** [Microsoft/vscode#20369]
My team uses "JS Standard Style" formatting, which we have configured via .eslintrc, but it seems that the formatting used when pasting code doesn't necessarily conform to the Standard rules.

For example, copying the following code (which complies with Standard's `"space-before-function-paren": ["error", "always"]` rule
```js
function doSomething (val) {}
```
ends up getting formatted like this upon pasting:
```js
function doSomething(val) {}
```
(notice the space after the function name is gone)

Is there a way to modify this behavior, preferably in a way that "just works" with my eslint configs?

**Comment by ferng** [comment]
following eslint when present would help, in my current project we use google's style for eslint which does the opposite of the above: 'space-before-function-paren': [2, 'never'],

**Comment by mjbvz** [comment]
For that specific formatting, try setting:

```json
"javascript.format.insertSpaceBeforeFunctionParenthesis": true
```

For better eslint integration, you may also want to try:

```json
"eslint.autoFixOnSave": true
```

or using the `eslint: Fix all auto-fixable problems` command

**Comment by shijunti19** [comment]
1.11.2
Does not work
`{
    "workbench.iconTheme": "material-icon-theme",
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "vue"
    ],
    "emmet.syntaxProfiles": {
        "vue-html": "html",
        "vue": "html"
    },
    "files.associations": {
        "*.vue": "html"
    },
    "beautify.language": {
        "js": {
            "type": ["javascript", "json"],
            "filename": [".jshintrc", ".jsbeautifyrc"]
            // "ext": ["js", "json"]
            // ^^ to set extensions to be beautified using the javascript beautifier
        },
        "css": ["css", "scss"],
        "html": ["htm", "html"]
        // ^^ providing just an array sets the VS Code file type
    },
    "html.format.enable": true,
    "typescript.format.insertSpaceBeforeFunctionParenthesis": true,
    "vetur.format.js.InsertSpaceBeforeFunctionParenthesis": true,
    "javascript.format.insertSpaceBeforeFunctionParenthesis": true,
    "eslint.autoFixOnSave": true
}`


![image](https://cloud.githubusercontent.com/assets/5392211/25327254/1694b7da-2906-11e7-9f83-154e03e1b124.png)
 I want to have spaces
