### ISSUE TITLE
Command Palette Needs Work

### ISSUE THREAD

**Issue by david-29** [microsoft/vscode#203644]
1. When I search existing issues for "command palette" I get hundreds of unrelated issues & very few matching Command Palette. A huge waste of my time to try to look up issues. What am I missing?
2. I'm in the Palette (I'm on a MacBook Pro, M1) and I select 'Refactor ...'. A tiny window appears saying that there currently are no refactors (what???, that's another issue; I'm programming mostly in C++ with a smattering of Python). OK, so time to go back to the Palette. But it disappeared!  What?? OK, no problem, let's click on the back button to get back to where I was in the Palette. Oops! No back button (What ???, No back button?  Really ???????). So I get to re-open the Palette and scroll down through 472 lines of crap to get back to 'Refactor ...' and explore further down.  You're kidding, right??    I ask Chat, er Copilot.  Chat says "that's right, boss, maybe you'd like to submit a feature request."    So here it is!!

**Comment by david-29** [comment]
OK, I now see that I need to select a block of code for 'Refactor ...' to offer something useful.

**Comment by david-29** [comment]
I don't want the Command Palette to be Modal, i.e. blocking. But I also don't want it to disappear as soon as I click anywhere outside of it. It should have a close button & maybe an iconify button. And the menu option I selected should be highlighted marking my place in the list of commands.

**Comment by gjsjohnmurray** [comment]
Re your first point, try adding ` in:title` to your search. The issue templates include the phrase 'command palette' in a comment block at the seeded description text.

Re your other points, if you reinvoke Command Palette by using keyboard (I like F1 but there's also Ctrl+Shift+P) it should put your most recent command at the top provided it is valid in the current context.

**Comment by david-29** [comment]
1. I tried in:title 'Command Palette' this evening. It doesn't seem to
filter anything; I still get a long list of unrelated posts.

2. I guess I wasn't clear enough on the other point. I wanted to go back to
'Refactor ...' not to run that menu item again but to continue to scroll
though the rest of the entries in the Command Palette, the ones below
'Refactor'. You have so many lines in this menu that it is tiresome to
scroll through them all. Maybe a tree widget would be a better way to
organize the various selections. But you probably can't do that in a menu.



David Beckedorff
314 Chicago Blvd
Sea Girt, NJ  08750

Mobile:  (732) 245-9865
Home:  (732) 449-3473

**Comment by gjsjohnmurray** [comment]
Re your first point, for me this search finds 35 open issues

is:issue is:open in:title 'Command Palette'

And this one finds 1402

is:issue is:open 'Command Palette'

**Comment by david-29** [comment]
Aha ...  I was doing 'is:title',  not 'in:title'.   Thanks for the
correction!


David Beckedorff
314 Chicago Blvd
Sea Girt, NJ  08750

Mobile:  (732) 245-9865
Home:  (732) 449-3473

**Comment by TylerLeonhardt** [comment]
Couple things:
1. If you want to search for command palette issues, you can do what @gjsjohnmurray suggested and/or add a filter for the `label:quick-open` [like so](https://github.com/microsoft/vscode/issues?q=is%3Aissue%20state%3Aopen%20label%3Aquick-open%20) which covers more than _just_ the command palette, but the list is a little easier to read
2. There are a couple options to play with the behavior of the Command Palette. (search for `Command Palette` or `Quick Open` in the Settings). Here are some that may help you:
  * `workbench.commandPalette.preserveInput`: controls whether the last typed input to the command palette should be restored when opening it the next time
  * `workbench.quickOpen.closeOnFocusLost`: controls whether Quick Open (which includes the Command Palette) should close automatically once it loses focus

I think I've addressed all the things you've called out, but let me know if there's something I'm missing.

**Comment by david-29** [comment]
Thanks Tyler.  This option looks interesting:
workbench.quickOpen.closeOnFocusLost
      I'll try setting it to 'false'.



Meanwhile, I have moved on to a bigger problem. I'll start searching issues
on Github tomorrow.  I had no trouble running the debugger (I use 'lldb')
under Code & the C++ extension back in January. But I haven't been able to
start it up successfully in February. I can build my app no problem with
meson / ninja. I can debug it using lldb from the command line. But when I
try to launch the debugger within Code, it just hangs at the first line of
my program. There's a spinning wheel in the VARIABLES area and that's all.
The only thing I can do at that point is to stop/kill the debugger. So "if
you know something, say something"!  Meanwhile, I'll poke around for a
while before typing up an issue to make sure I don't just have a launch
configuration issue.  Got so annoyed at it last night that I started
yelling at Copilot!!  AI abuse, right!

-David




David Beckedorff
314 Chicago Blvd
Sea Girt, NJ  08750

Mobile:  (732) 245-9865
Home:  (732) 449-3473

**Comment by TylerLeonhardt** [comment]
Glad to hear that the settings seem to do what you're looking for. For C++ issues, I'm gonna refer you to the repo for that team:

https://github.com/microsoft/vscode-cpptools

Open an issue there and they'll be better equipped to help you with C++ debug issues than us here in the editor land.

I'll close this since the setting solves your issue. Feel free to reach out if you have more issues 👍
