### ISSUE TITLE
Debugger moved to awkward place cannot access the grip indicator

### ISSUE THREAD

**Issue by vaispiday** [Microsoft/vscode#20366]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.5|
|tslint|eg2|0.8.1|
|beautify|HookyQR|0.7.3|
|Go|lukehoban|0.6.53|
|debugger-for-chrome|msjsdiag|2.5.3|
|vscode-icons|robertohuertasm|7.2.0|
|Spell|seanmcbreen|0.9.1|
|JavaScriptSnippets|xabikos|1.4.0|

---
#19899 
Steps to Reproduce:

1.   Make sure you have split monitor , basically two monitors and then use the Visual code on secondary monitor
2.  Now move the debugger to the left  corner till it hide the grip indicator on your secondary monitor and then leave the grip indicator.
3. Now try to again hold the grip indicator , you cannot access it . The solution in the #19899 is a temporary fix , but still the issue is there

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/20298
