### ISSUE TITLE
VSCode background color glitch

### ISSUE THREAD

**Issue by tedmcdo** [Microsoft/vscode#20360]
- VSCode Version: 1.9.1
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. Have external monitor plugged in via hdmi
2. Open VSCode

My VSCode background has a color inconsistency — it looks as though I have highlighlighted content when I have not. This only happens when I am connected to an external monitor, not on my mac screen.

![screen shot 2017-02-09 at 3 11 57 pm](https://cloud.githubusercontent.com/assets/8085589/22807851/fe5cdee8-eedd-11e6-8da4-d786d8aef2ca.png)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/12473
