### ISSUE TITLE
i am unable to access my codespace

### ISSUE THREAD

**Issue by satish24kumar** [microsoft/vscode#203613]
![codespace error](https://github.com/microsoft/vscode/assets/61512566/6d71f5c5-9815-4519-b906-fef98052019b)

Does this issue occur when all extensions are disabled?: unable to do so

- VS Code Version: https://cs50.dev
- OS Version: Edition	Windows 11 Home Single Language
Version	22H2
Installed on	‎11-‎12-‎2022
OS build	22621.3007
Experience	Windows Feature Experience Pack 1000.22681.1000.0

- Browser : Chrome Version 121.0.6167.86 (Official Build) (64-bit)

Steps to Reproduce:

1. 
2.

**Comment by chrmarti** [comment]
Thanks for your feedback. Since it concerns GitHub Codespaces, could you please start a discussion about it here: https://github.com/orgs/community/discussions/categories/codespaces
