### ISSUE TITLE
Command prompt not showing up in terminal profile when connecting through Remote Tunnels

### ISSUE THREAD

**Issue by kon72** [microsoft/vscode#203616]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.2
- OS Version: Windows 11 Home 23H2

Steps to Reproduce:

1. Run `code tunnel` on Windows machine
2. Open the URL and connect to the remote tunnel
3. Open the command palette and run `Terminal: Create New Terminal (With Profile)`

VS Code launched on local:
<img width="456" alt="スクリーンショット 2024-01-28 4 06 44" src="https://github.com/microsoft/vscode/assets/55415600/5f2e911a-a7e1-4bc2-a33b-61e33673b336">

connecting through remote tunnel:
<img width="599" alt="スクリーンショット 2024-01-28 4 07 49" src="https://github.com/microsoft/vscode/assets/55415600/1e24d81f-775b-4ad8-a7d6-3f9f3330689a">

#### My terminal settings:
(I tried resetting to default but that didn't help)

```
"terminal.integrated.profiles.windows": {
  "PowerShell": {
    "source": "PowerShell",
    "icon": "terminal-powershell"
  },
  "Command Prompt": {
    "path": [
      "${env:windir}\\Sysnative\\cmd.exe",
      "${env:windir}\\System32\\cmd.exe"
    ],
    "args": [],
    "icon": "terminal-cmd"
  },
  "Git Bash": {
    "source": "Git Bash"
  },
  "Developer Command Prompt for VS 2022": {
    "path": [
      "${env:windir}\\Sysnative\\cmd.exe",
      "${env:windir}\\System32\\cmd.exe"
    ],
    "args": [
      "/k",
      "${env:ProgramFiles}\\Microsoft Visual Studio\\2022\\Community\\Common7\\Tools\\VsDevCmd.bat"
    ]
  },
  "Developer PowerShell for VS 2022": {
    "source": "PowerShell",
    // C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe -noe -c "&{Import-Module """C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"""; Enter-VsDevShell 51a5e2e6}"
    "args": [
      "-NoExit",
      "-Command",
      "&{Import-Module \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\Tools\\Microsoft.VisualStudio.DevShell.dll\"; Enter-VsDevShell 51a5e2e6}"
    ]
  }
}
```

**Comment by meganrogge** [comment]
Guessing this path doesn't exist in your remote environment? `"${env:windir}\\Sysnative\\cmd.exe",`,

**Comment by kon72** [comment]
> Guessing this path doesn't exist in your remote environment? `"${env:windir}\\Sysnative\\cmd.exe",`,

Yes, cmd.exe doesn't exist in `Sysnative` but it does in `System32`.
I tried deleting the line `"${env:windir}\\Sysnative\\cmd.exe",` in config file but the issue still persists.

**Comment by meganrogge** [comment]
You can simply set the path for your profile in config. Seems like we're not getting your path by default correct.

**Comment by meganrogge** [comment]
here's where that happens https://github.com/microsoft/vscode/blob/a780b235dde376ff32118386f32e6b2e9128fae1/src/vs/platform/terminal/node/terminalProfiles.ts#L113

**Comment by kon72** [comment]
Thanks, setting to `["C:\\Windows\\System32\\cmd.exe"]` resolved the issue.
