### ISSUE TITLE
Open editors: Drag and drop sometimes ends up selecting the element

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#203696]
If I manage to drag slightly above the editor, the editor gets fully selected:

![Kapture 2024-01-29 at 14 30 40](https://github.com/microsoft/vscode/assets/900690/d30fd72c-8619-4f52-8b1a-2e50f56b6528)

**Comment by benibenj** [comment]
Candidate PR: #203702

**Comment by benibenj** [comment]
Verification step:
1. open multiple editors
2. open the "open editors view"
3. drag an editor which is further at the bottom up between two other editors
4. Move mouse slowly up and down very close to the border, make sure you don't see a flicker as can be seen in the gif above
