### ISSUE TITLE
Customisable double click-select behaviour

### ISSUE THREAD

**Issue by d0x2f** [Microsoft/vscode#2036]
Upon double-clicking, people have different expectations across various languages.
The ability to define custom highlighting rules based on the selected text would simultaneously solve a lot of highlighting issues and increase the flexibility of the editor.

My motivation for bringing this up comes from my frustration with variable selection in PHP.
When double-clicking 'foo' in '$foo->bar()' you will end up selecting '$foo-', my preference  would be 'foo'.
I also noticed another issue regarding double clicking white-space where the user would like it to select all connected white-space.
These kinds of rules would be perfectly suited for on the fly user customisation.

**Comment by vlad-saling** [comment]
I would love to see that as well. Sometimes I need to replace just part of the string. For example a part of class name in CSS ```.block--modifier``` but the default double click selects whole class. Making the behavior customizable would solve this.

**Comment by luebken** [comment]
May I add a simple use case: The first time I select a string via douple-click I would like the selection to _exclude_ the double quotes.

**Comment by jtarbox** [comment]
I noticed a change with the recent update with how this behaved.  For PHP, could we have this as an editable option or something?   As I would personally prefer it grab the preceding '$' character when double-click selecting.

**Comment by alexandrudima** [comment]
@jtarbox Yes, please try changing the following setting that now customizes word definitions when doing word operations:

```
// default:
, "editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"
// without $:
, "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"
```

**Comment by alexandrudima** [comment]
Actually, I think the new option `editor.wordSeparators` that just shipped with 0.10.11 resolves this issue

**Comment by jtarbox** [comment]
thx, worked perfectly!  (still getting used to the text based settings)

**Comment by vlad-saling** [comment]
Thank you! Works great!

**Comment by ctrulove** [comment]
This just made my day.Works like a charm.

**Comment by RonanC** [comment]
This is great, I removed the dollar for angular coding.
Is there a way to specify this for different languages?
Or do I need to edit my settings file each time I change language?

**Comment by Ben-Conrad** [comment]
This is great, I removed '$' from editor.wordSeparators and now I can double click on PowerShell variables and get the entire variable '$var' in my clipboard.

**Comment by dmagician** [comment]
Fantastic configuration feature. I have immediatelly removed $ from that ;-) I'm used to $variable being selected ;-)

**Comment by gustavaum** [comment]
These days I came across this issue of double click behavior. I noticed that most of the time I would like to "select the whole string", but it was annoying me. So, what if I double click on a "-" and the behavior would be something like "select an entire string". If I clicked on a word (as we usually do) would I still have the default behavior?
