### ISSUE TITLE
Typescript crashed

### ISSUE THREAD

**Issue by MicroJes** [Microsoft/vscode#20368]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-caniuse|akamud|0.5.3|
|beautify|HookyQR|0.4.0|
|debugger-for-chrome|msjsdiag|0.2.2|
|node-modules-resolve|naumovs|1.0.2|
|html2jade|wmaurer|0.2.0|

---

Steps to Reproduce:

1. open vscode 
2. warning  crash

**Comment by mjbvz** [comment]
Two questions:

* Does the warning or crash message mention a missing `typescript/...` file? 
* Are you opening a file stored on sharepoint?

**Comment by MicroJes** [comment]
@mjbvz  Tips: c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib doesn't point to a valid tsserver install.
I have reinstall typescript  it doesn't work. I just open file in my project.

**Comment by MicroJes** [comment]
@mjbvz   just delete "Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript" module it work well. thanks

**Comment by mjbvz** [comment]
@MicroJes Deleting that folder is not correct.

To fix this, either:

* Point VSCode to a custom typescript install using the `typescript.tsdk` setting: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions
* Uninstall whatever antivirus program is deleting these files in the first place or at least add ` `Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\...`to an exception list. Then reinstall VSCode to restore the `node_modules\typescript\...` files 

Closing as external
