### ISSUE TITLE
typescript error

### ISSUE THREAD

**Issue by pursonchen** [Microsoft/vscode#20365]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7600
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.
2.

**Comment by Tyriar** [comment]
You will need to provide more information
