### ISSUE TITLE
VSCode editor is freezed But Others is Ok

### ISSUE THREAD

**Issue by fgc346** [microsoft/vscode#203645]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: VSCode 1.85.2
- OS Version: Ubuntu 18.04

## Issue Description:
I'm experiencing a problem where, at some point, when typing in the VSCode editor, the computer suddenly freezes, and I'm unable to input characters. After a while, the characters I typed appear in the editor.

### Disabled all plugins:
Initially, I disabled all plugins, but the issue persisted, ruling out plugin-related problems.

### Uninstalled and reinstalled:
I uninstalled and reinstalled VSCode twice, including removing all configuration files, but the problem persists.

Commands used for uninstallation:
```
sudo apt remove --purge code
sudo apt autoremove
rm -rf ~/.config/Code
rm -rf ~/.vscode
```
## Seeking Help:
I'm seeking assistance on how to troubleshoot and resolve this issue.

**Comment by travisbikkle** [comment]
What I'm experiencing is :
When press <kbd>Del</kbd> in vscode, the whole system freeze, not always but pretty much often.
I've re-install kubuntu many times, this still happens.

#### OS
Kubuntu 22.04 in vmware 17, with 6 cpu cores and 16GB memory (total 32GB on host).
vscode is the only software I opened.

#### vscode version:
```txt
版本: 1.85.2
提交: 8b3775030ed1a69b13e4f4c628c612102e30a681
日期: 2024-01-18T06:40:19.222Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.0-15-generic
```

**Comment by fgc346** [comment]
The problem I'm encountering is exactly the same as shown in the animated gif in this issue （https://github.com/microsoft/vscode/issues/203538).
but it occurs specifically in the editor interface.

**Comment by deepak1556** [comment]
@fgc346 can you confirm if the issue is present with latest stable `1.96`. If it does please capture a perf trace following the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

**Comment by fgc346** [comment]
> [@fgc346](https://github.com/fgc346) can you confirm if the issue is present with latest stable `1.96`. If it does please capture a perf trace following the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

Now that the frozen issue has not recurred, I no longer need to concern myself with it.
