### ISSUE TITLE
Allow pasting media files to Markdown without holding down the shift

### ISSUE THREAD

**Issue by onnimonni** [microsoft/vscode#203615]
Dragging media files has been well documented here:
https://code.visualstudio.com/updates/v1_79#_copy-external-media-files-into-workspace-on-drop-or-paste-for-markdown

**What I currently see:**
If I drag media file into markdown file without holding down shift VSCode will just open it into new tab.

**What I would want to see:**
It would be great if I could always paste the images into the markdown even without holding down the shift.

This would make this a lot easier for new users who are not familiar with the VSCode.

It could be opt-in new option into the settings.json

This would make editing markdown content for static site generators much much more easier.

**Comment by mjbvz** [comment]
You can use copy/paste for this. It has pretty much the same behavior as drag and drop
