### ISSUE TITLE
The maximized terminal window is not displayed correctly

### ISSUE THREAD

**Issue by SunboTax** [microsoft/vscode#203631]
Type: <b>Bug</b>

All my three windows devices have the same problem where the maximized terminal window is not displayed correctly as shown in the figure below:
<img width="922" alt="屏幕截图 2024-01-28 195221" src="https://github.com/microsoft/vscode/assets/53291054/4d086575-e0c8-4515-bc41-69cedd055f1a">

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1340P (16 x 2189)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (7.31GB free)|
|Process Argv|--crash-reporter-id 76a944cf-3435-4866-9784-b32435fd18de|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.20
gitlens|eam|14.7.0
codespaces|Git|1.16.9
copilot|Git|1.155.0
copilot-chat|Git|0.11.1
gc-excelviewer|Gra|4.2.58
latex-workshop|Jam|9.18.0
vscode-edit-csv|jan|0.8.3
better-cpp-syntax|jef|1.17.2
vsc-python-indent|Kev|1.18.0
vscode-language-pack-zh-hans|MS-|1.85.2024012409
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.16.32
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.12
sqltools|mtx|0.28.1
sqltools-driver-pg|mtx|0.5.2
markdown-preview-enhanced|shd|0.8.11
graphviz-interactive-preview|tin|0.3.5
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30933248
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
7j2b6412:30949929

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by SunboTax** [comment]
Yes, it work fine in the insiders build.  :clap:
Thx for your quick reply and have a nice day :blush:
