### ISSUE TITLE
Open the GUI settings interface of vscode and wait for more than ten seconds to display the content.

### ISSUE THREAD

**Issue by you-hengh** [microsoft/vscode#203796]
Open the GUI settings interface of vscode and wait for more than ten seconds to display the content.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.2
- OS Version: win11 23H2

Steps to Reproduce:

1. Use the shortcut key ctrl+, to open the set GUI interface
2. Then the interface has no content, and you have to wait for more than ten seconds to display.

![2024-01-30_22-01-16](https://github.com/microsoft/vscode/assets/34816426/48ba382c-f5f8-4cd2-929d-3fba20812eb7)

System information:

CPU:	13th Gen Intel(R) CoreT i7-13800H   1.90 GHz

RAM:	32.0 GB (31.7 GB can use)

System type 64-bit operating system, x64-based processor

I want to be able to display the content immediately when I open the set GUI interface instead of waiting for more than ten seconds.

**Comment by rzhao271** [comment]
That looks like a bug, but I'd like some more info to figure out the root cause.

1. Could you run the command `workbench.action.toggleDevTools` and see if any errors show up in the Console view?
1. Does the issue occur with extensions disabled? You can test by running `code --disable-extensions` in a terminal.

**Comment by you-hengh** [comment]
I have disabled all the extensions, and the chinese extension will be enabled automatically, but I believe it is not the reason for this plug-in

The picture below is the page that runs according to the prompt

![2024-01-31_09-10-59](https://github.com/microsoft/vscode/assets/34816426/d7332b66-c89c-41c8-bb97-75b9af7838e8)

I don't know if that helps.

**Comment by you-hengh** [comment]
This is all my vscode configuration

```json
{
  "editor.fontFamily": "FiraCode Nerd Font Mono,'仓耳舒圆体'",
  "editor.fontSize": 16,
  "editor.formatOnSave": true,
  "editor.formatOnSaveMode": "file",
  "editor.fontLigatures": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.lineNumbers": "interval",
  "editor.smoothScrolling": true,
  "editor.cursorSmoothCaretAnimation": "on",
  "editor.cursorBlinking": "expand",
  "editor.formatOnPaste": true,
  "editor.formatOnType": true,
  "editor.acceptSuggestionOnEnter": "smart",
  "editor.suggestSelection": "recentlyUsed",
  "editor.stickyScroll.enabled": true,
  "editor.minimap.enabled": true,
  "editor.minimap.renderCharacters": false,
  "editor.minimap.autohide": true,
  "editor.scrollbar.horizontal": "hidden",
  "editor.tokenColorCustomizations": {
    "comments": "#2ec907"
  },
  "workbench.iconTheme": "material-icon-theme",
  "workbench.preferredDarkColorTheme": "Eva Dark",
  "workbench.preferredLightColorTheme": "Eva Light",
  "workbench.colorTheme": "Eva Light",
  "workbench.settings.editor": "json",
  "workbench.startupEditor": "none",
  "workbench.sideBar.location": "right",
  "workbench.tree.enableStickyScroll": true,
  "workbench.list.smoothScrolling": true,
  "workbench.colorCustomizations": {
    "tab.activeBorderTop": "#ff00f7"
  },
  "material-icon-theme.activeIconPack": "vue",
  "files.autoSave": "onFocusChange",
  "update.mode": "manual",
  "prettier.configPath": "C:\\Users\\admin\\.vscode\\.prettier\\.prettier.json",
  "vue.autoInsert.dotValue": true,
  "remote.SSH.remotePlatform": {
    "腾讯云": "linux"
  },
  "window.dialogStyle": "custom",
  "window.autoDetectColorScheme": true,
  "debug.showBreakpointsInOverviewRuler": true,
  "liveServer.settings.donotShowInfoMsg": true,
  "explorer.confirmDragAndDrop": false,
  "explorer.confirmDelete": false,
  "explorer.fileNesting.enabled": true,
  "explorer.fileNesting.patterns": {
    "package.json": "package-lock.json, yarn.lock, pnpm-lock.yaml,.eslintrc.*,.prettierrc.*,.gitignore,env.d.ts,README.md,vite.config.*"
  },
  "terminal.integrated.persistentSessionReviveProcess": "never"
}
```

![2024-01-31_09-10-48](https://github.com/microsoft/vscode/assets/34816426/4343ce9e-aa93-490c-b372-d0cf01a01b8b)

**Comment by you-hengh** [comment]
I observed that there were some problems with my access to `github.gallerycdn.azure.cn`, and I fixed this web link problem. 

Now the GUI interface of vsocde loading settings is much faster, from more than ten seconds to about 2 seconds, which is very surprising to me, 

and thank you for your help, @rzhao271
