### ISSUE TITLE
Open files are not reopened when closing/opening the app

### ISSUE THREAD

**Issue by cvet-jendries** [microsoft/vscode#203710]
Type: <b>Bug</b>

1. Close VS Code with various saved/non-saved files open.
2. Reopen VS Code
3. Not everything is reopened

I had over a dozen files open, closed the app and reopened it (no update occurred that I saw), and only five non-saved files are open. I would expect it to restore to the state it was in when it closed. Additionally, and I guess I'll create a separate bug for this, but I can't open any new files.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2024.0.0
vscode-yaml|red|1.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
0bi6i642:30933247
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
3ef8e399:30949928

```

</details>

**Comment by bpasero** [comment]
Configure: `window.restoreWindows` to `preserve`. Then it should be fine.

**Comment by cvet-jendries** [comment]
Hmmm I may have had a workspace opened originally, I don't remember. If I did, I definitely had files from other folders open also. It was set to the default "all" so this might have been the issue. What a bizarre default behavior (and poorly named IMHO).
