### ISSUE TITLE
HTML autocomplete and intellisense not working in template files.

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#20375]
![c](https://cloud.githubusercontent.com/assets/17777237/22814206/3a384eda-ef5a-11e6-9d66-1a3ef1d030d0.gif)

it not working in .blade.php file type.

![ff](https://cloud.githubusercontent.com/assets/17777237/22814876/c900e5e6-ef5f-11e6-87f1-0e5c1631af56.gif)

intellisense not working but Emmet working great

**Comment by Tyriar** [comment]
We defer support for lesser known languages like this (and PHP) to extensions https://marketplace.visualstudio.com/vscode
