### ISSUE TITLE
Can't open this git resource: Merge Added conflicts

### ISSUE THREAD

**Issue by nvcnvn** [Microsoft/vscode#20378]
I cannot open the conflict files when clicking on the git side bar
- VSCode Version: 1.9.1
- OS Version: #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
 - git version 2.7.4
 - plugins: lukehoban.Go
Steps to Reproduce:

1. some how make a merge conflict
2. click on the file name

![conflict](https://cloud.githubusercontent.com/assets/1708320/22817115/0b02e0c4-ef98-11e6-9ab2-4f9db078e212.png)

**Comment by joaomoreno** [comment]
#24919
