### ISSUE TITLE
Rerun VSCode build tasks often only restarts one task

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#203776]
I am seeing this since months but more frequently lately. I often rerun build tasks via this keybinding:

```json
{
    "key": "cmd+shift+alt+b",
    "command": "workbench.action.tasks.runTask",
    "args": "Restart VS Code - Build"
}
```

In 1 out of 2 cases only one task restarts:

<img width="1287" alt="image" src="https://github.com/microsoft/vscode/assets/900690/fbab25a3-ec2d-4db6-a67a-529427ba590f">

Is there a place I can check for logs to diagnose further or can we add some logging?

**Comment by meganrogge** [comment]
Yes. If you set log level to trace, there will be tons of task logs.

**Comment by meganrogge** [comment]
I am confused because we don't support an `arg` of `Restart VS Code - Build`.

**Comment by meganrogge** [comment]
We have this command, which takes an `arg` 

https://github.com/microsoft/vscode/blob/284a605d612bb8765d414c8cb4f17b07c2b2b820/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L496-L500

https://github.com/microsoft/vscode/blob/284a605d612bb8765d414c8cb4f17b07c2b2b820/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L3246

**Comment by meganrogge** [comment]
trying:

```
 {
    "key": "cmd+shift+alt+b",
    "command": "workbench.action.tasks.restartTask",
    "args": "VS Code - Build"
 },
```

**Comment by meganrogge** [comment]
If you are invoking this from not within the terminal, then I see exactly why that would be the case:

https://github.com/microsoft/vscode/blob/284a605d612bb8765d414c8cb4f17b07c2b2b820/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L3240-L3242

**Comment by meganrogge** [comment]
logs when it works:

![Image](https://github.com/user-attachments/assets/d90dd16b-6078-47a9-b1f6-44ee8b8d72f7)

logs when it fails to restart both:

![Image](https://github.com/user-attachments/assets/36dd7476-bc2f-4a14-9966-e70f2a61e4b6)

**Comment by meganrogge** [comment]
When this reproduces, `taskResult` is unexpectedly defined. I believe this would happen if there's already a task in flight that hasn't completed yet. 

![Image](https://github.com/user-attachments/assets/a91690ad-8d99-4ebf-b727-6d5f796b1a3d)

![Image](https://github.com/user-attachments/assets/038dbc0d-fbd5-4a0a-8612-8ef647aeb7f3)

**Comment by meganrogge** [comment]
Yes, this reproduces for me when one, but not both, of the dependency tasks has completed. 

So, run 

```
{
    "key": "cmd+shift+alt+b",
    "command": "workbench.action.tasks.runTask",
    "args": "Restart VS Code - Build"
}
```

wait a little bit until the tasks have been killed but the second dependency task hasn't started 
https://github.com/microsoft/vscode/blob/284a605d612bb8765d414c8cb4f17b07c2b2b820/.vscode/tasks.json#L109

**Comment by bpasero** [comment]
Oh nice, thanks for finding a repro!

**Comment by meganrogge** [comment]
Happens when one of the two tasks has become inactive

![Image](https://github.com/user-attachments/assets/9606def0-2d75-41ea-8b98-bb8b0705567f)

**Comment by meganrogge** [comment]
definitely a timing issue bc always reproduces without breakpoints and doesn't reproduce when I walk through the code with them

**Comment by meganrogge** [comment]
this could happen when `taskResult` is defined already.

![Image](https://github.com/user-attachments/assets/8e563259-d59e-4c25-a9ff-81a7707b4395)

**Comment by meganrogge** [comment]
which begs the question, does the overarching VS Code - Build task get removed from `activeTasks` after each of its dependencies are started or only after one of them is?

**Comment by meganrogge** [comment]
Nope, always results in this bug 

![Image](https://github.com/user-attachments/assets/3e07985d-de4f-4000-bcac-d039bbae23f4)

**Comment by meganrogge** [comment]
@bpasero the repro here is extremely specific. you'd have to be lucky with your timing to get this right, so I imagine you rarely see this. would it make sense to remove `papercut`?

I have spent many hours trying to figure out a fix and believe that the fix could cause issues like the one I mentioned above.

**Comment by bpasero** [comment]
I am still seeing this and would love a fix. Just happened now again.



![Image](https://github.com/user-attachments/assets/67cfcaa1-827e-4a53-98ec-568f27f57a22)

**Comment by bpasero** [comment]
Thanks!

**Comment by meganrogge** [comment]
Would be great if you can verify it's fixed for you @bpasero

**Comment by bpasero** [comment]
Will do!

**Comment by bpasero** [comment]
I have not seen this since, great!

**Comment by bpasero** [comment]
@meganrogge somehow this issue has come back for me, I often only see 1 task running when I trigger the default build task or restart it. Any chance this could have regressed again?

**Comment by meganrogge** [comment]
Nothing has changed in tasks in months

**Comment by bpasero** [comment]
Ok will keep an eye out for what the task tells me in the terminal when it happens.
