### ISSUE TITLE
SCM: make git commit box look like other input boxes (font, color)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#20379]
I think we should use the same font we e.g. also use for the search input box. Also the same background color:

![image](https://cloud.githubusercontent.com/assets/900690/22823542/67ba6be8-ef84-11e6-99b1-dc92324381e3.png)

![image](https://cloud.githubusercontent.com/assets/900690/22823559/778fb5e6-ef84-11e6-8f99-d9f4853833d1.png)

**Comment by joaomoreno** [comment]
Well, now it's an editor, it looks like a regular editor, not like an input box. It inherits the editor's background colour and font #20285

**Comment by bpasero** [comment]
I don't think a user would think that way.

**Comment by joaomoreno** [comment]
Let's run with it for a while.

**Comment by bpasero** [comment]
Also given the other measures we took to make the box look like the other boxes (blue focus color, same padding). But yeah, I am sure you will get this bug from someone else.
