### ISSUE TITLE
prefix error

### ISSUE THREAD

**Issue by 928PJY** [Microsoft/vscode#20374]
- VSCode Version: 1.8.1
- OS Version: win10

Hi, I am writing a VSCode extension, some problem came up when I want to use js files to render the Html page, problem like this

![image](https://cloud.githubusercontent.com/assets/17958546/22813221/0767e102-ef85-11e6-907b-1ee4863a361d.png)

you can see, the Url of variable a is "../toc.html", and the base path is "e:/SeedProject/docfx-seed/toc.html", but a get an error like this. 

![image](https://cloud.githubusercontent.com/assets/17958546/22813088/d44ad794-ef83-11e6-9c0a-c91e6c9a5a89.png)

why there is a prefix "markdown:/"?

**Comment by Tyriar** [comment]
@mjbvz might know about this from working on the markdown extension?

**Comment by mjbvz** [comment]
Are you using `Markdown: Open Preview`? The `markdown:/` scheme is how we identify markdown preview documents. 

Could you please provide a more complete example of what your code is trying to do and what is going wrong currently

**Comment by 928PJY** [comment]
Thank you for your response, I made a mistake, But there is still a problem in [Issue#20901](https://github.com/Microsoft/vscode/issues/20901)

**Comment by mjbvz** [comment]
Thanks, closing as it looks like part of your question has been resolved
