### ISSUE TITLE
Allow disabling server requirements check from external process

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#203728]
Check for the presence of a file and skip it. Option to disable at user's risk.

**Comment by deepak1556** [comment]
Steps for verification:

* With docker installed on host, run `docker pull ubuntu:bionic`
* Get image id with `docker images ubuntu:bionic`
* `docker run --rm -it --entrypoint bash <image-id-from-previous-step>`
* In bash shell, `touch /tmp/vscode-skip-server-requirements-check`
* Now from latest insiders, run `Attach to running container` and chose the above container
* Server setup will fail but make sure the logs contain the following statements

```
!!! WARNING: Skipping server pre-requisite check !!!
!!! Server stability is not guaranteed. Proceed at your own risk. !!!
```

**Comment by isidorn** [comment]
![Screenshot 2024-01-31 at 10 19 51](https://github.com/microsoft/vscode/assets/1926584/2541de65-1bfc-489b-b499-013f7c144a8c)
