### ISSUE TITLE
wrong spaces for tab key

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#20373]
![a](https://cloud.githubusercontent.com/assets/17777237/22813744/bd12c276-ef56-11e6-9dbb-bb529d92b31e.gif)
the number of spaces change from the file type or when it inside {{HERE}} or "HERE" or when the file type for example ".blade.php" in vscode 1.9.1

which is very annoying we can add setting to set the number of spaces when hit tab key for all files types and inside any thing like {{}} or ""

**Comment by Tyriar** [comment]
I believe this is because space is "simulating" a tab; the number of spaces added depends on the cursor position.
