### ISSUE TITLE
API - Docs: contributions points - schema property: lacking a lot of properties and documentation.

### ISSUE THREAD

**Issue by Malix-off** [microsoft/vscode#203721]
[the api documentation about contributions points schema property](https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema:~:text=Other%20JSON%20Schema%20properties) is lacking **a lot** of properties and documentation.

For instance, this is a list of all the properties the LSP is showing containing the letter `"a"` in it.
![image](https://github.com/biomejs/biome-vscode/assets/76160668/dd86564d-937f-4614-a87f-40f26983c7ca)
A lot of them are not listed anywhere in [the api documentation about contributions points schema property](https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema:~:text=Other%20JSON%20Schema%20properties)

Does this issue occur when all extensions are disabled?: No (Because that LSP feature it comes from a built-in extension (I didn't find which))

- VS Code Version: 1.85.2 - 8b3775030ed1a69b13e4f4c628c612102e30a681 - x64

**Comment by aeschli** [comment]
As explained in the documentation, this configuration keys are defined using a superset of [JSON Schema](https://json-schema.org/overview/what-is-jsonschema).
In the VS Code documentation, we only list the properties we added on top.

https://json-schema.org/understanding-json-schema is a good documentation of JSON Schema.

**Comment by Malix-off** [comment]
Wdym @aeschli?
Are there not supposed to be any documentation for them?

**Comment by aeschli** [comment]
It would take up a lot of space in the documentation and we would be repeating what's much better explained in the JSON schema documentation. We also don't go into the details of the JSON format. The target audience are extension developers, so I think it's ok to assume that they can look up the necessary information.

**Comment by ematipico** [comment]
@aeschli, where's the schema, though? You haven't linked it yet and we need it understand how we should define our configurations

**Comment by aeschli** [comment]
You can use everything from JSON schema (draft-07)

https://json-schema.org/understanding-json-schema describes the properties of JSON schemas and also has a line to the meta schema, if you need that? https://json-schema.org/draft-07/schema
