### ISSUE TITLE
vs code the window terminated unexpectedly (reason: 'launch-failed', code: '18') 

### ISSUE THREAD

**Issue by Muaadeeb** [microsoft/vscode#203719]
Type: <b>Bug</b>

Trying to open in admin mode.  I am up to date on version.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.27GB free)|
|Process Argv|-n --crash-reporter-id 4ae29c74-944d-481b-9bb6-921569a303c9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
docs-yaml|doc|1.0.1
copilot|Git|1.155.0
copilot-chat|Git|0.11.1
vscode-bicep|ms-|0.24.24
csdevkit|ms-|1.2.7
csharp|ms-|2.15.30
vscode-dotnet-runtime|ms-|2.0.1
vscodeintellicode-csharp|ms-|0.1.26
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
powershell|ms-|2024.0.0
azurerm-vscode-tools|msa|0.15.11
vscode-yaml|red|1.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
0bi6i642:30933247
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
3ef8e399:30949928

```

</details>

**Comment by deepak1556** [comment]
Are you able to open the application with the following command line flag `code --disable-chromium-sandbox`
