### ISSUE TITLE
The file link in terminal output can not be recognized when running make in tasks

### ISSUE THREAD

**Issue by sunhaox** [microsoft/vscode#203768]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.2 (user setup)
- OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Project struct like this:
![image](https://github.com/microsoft/vscode/assets/24861288/a49f3ee8-57a7-4462-b77e-7bca06c7dfd1)

./Makefile:
```
.PHONY: all

all:
	@echo './tt/tt.uc(3)'
	make -C test -f Makefile
```
./test/Makefile:
```
test: 
	@echo '../tt/tt.uc(3) : Error : No service'
	gcc -o test test.c
```
./.vscode/tasks.json:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "test",
            "type": "shell",
            "command": "make",
            "options": {
                "cwd": "${workspaceRoot}"
            }
        }
    ]
}
```
2. Run "test" task.
```
./tt/tt.uc(3)
make -C test -f Makefile
make[1]: Entering directory `<workspaceRoot>/test'
../tt/tt.uc(3) : Error : No service
gcc -o test test.c
```
![image](https://github.com/microsoft/vscode/assets/24861288/a867cfbc-0567-4172-9fd2-2b7c3b8a8e1b)

Only the first file can be recognized. The second file can not be recognized as the cwd changed.  

![image](https://github.com/microsoft/vscode/assets/24861288/93e2f364-c276-41f0-a5df-c0dcda350d13)

But in my test, I run make in terminal directly, these two file all can be recognized. 

I also try it on Linux based on Remote - SSH extension. Neither the task and run make in terminal can not recognize the second file path.

**Comment by Tyriar** [comment]
This is actually by design since we use the current working directory as reported by shell integration and don't have insight into the `"Entering directory `...`"` part. It should however have reasonable fallback logic when ctrl+clicked, reverting to a workspace search and opening the file if it's the only result.
