### ISSUE TITLE
Too bad save all files, it made another each file incorrect content

### ISSUE THREAD

**Issue by bunditng** [Microsoft/vscode#20372]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|angular-material-snippets|4tron|0.3.1|
|html-snippets|abusaidm|0.0.18|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|angular1-code-snippets|alexandersage|0.0.3|
|html-class-suggestions|AndersEAndersen|1.0.3|
|jsrefactor|cmstead|0.5.3|
|Angular1|johnpapa|0.1.16|
|goto-last-edit-location|krizzdewizz|0.2.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|vscode-duplicate|mrmlnc|1.0.2|
|js-atom-grammar|ms-vscode|0.1.12|
|joinlines|webdokkeren|1.1.1|
|change-case|wmaurer|1.0.0|

---
too bad save all files,it made another each file incorrect content
___

Steps to Reproduce:

1.open file more than one file, make some content has change each file
2. Click File > Save All ..

**Comment by bpasero** [comment]
@bunditng I would appreciate if you could answer my comment in https://github.com/Microsoft/vscode/issues/19356
