### ISSUE TITLE
Update rpm release tag to signify breaking update

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#203771]
Upcoming release 1.86 has [updated glibc requirements](https://code.visualstudio.com/docs/supporting/faq#_can-i-run-vs-code-on-older-linux-distributions) which will break package install on el7 systems, updating the tag to signify that.

**Comment by aiday-mar** [comment]
Since the PR into release has been merged, I will close this issue.

**Comment by deepak1556** [comment]
Issue can be verified after `1.86` is released.

Steps for verification:

* Install current stable `1.85` rpm package on CentOS 7
* Check for updates using dnf or yum, refs https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions
* Ensure that no new updates are available from `1.86` version

**Comment by rzhao271** [comment]
I used a CentOS 7 container.

When I run `yum check-update`, the following entry shows up.
```
code.x86_64                                            1.86.0-1706698221.el8                                     code
```

If I actually try to update after, I get:
```
# yum install code
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: linux-mirrors.fnal.gov
 * extras: mirrors.tripadvisor.com
 * updates: mirror.ette.biz
Resolving Dependencies
--> Running transaction check
---> Package code.x86_64 0:1.85.2-1705561377.el7 will be updated
---> Package code.x86_64 0:1.86.0-1706698221.el8 will be an update
--> Processing Dependency: libc.so.6(GLIBC_2.28)(64bit) for package: code-1.86.0-1706698221.el8.x86_64
--> Finished Dependency Resolution
Error: Package: code-1.86.0-1706698221.el8.x86_64 (code)
           Requires: libc.so.6(GLIBC_2.28)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by deepak1556** [comment]
Thanks for testing, not sure how to resolve this. The change is based on what community proposed https://github.com/microsoft/vscode/pull/117994 and given we haven't seen any reports so far I will leave this as such.

**Comment by rzhao271** [comment]
Marking as verified for now.
