### ISSUE TITLE
in .blade file comment shortcut  ( ctrl + / ) is " // " not " <!--  --> "

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#20371]
![b](https://cloud.githubusercontent.com/assets/17777237/22844649/ffb15cb4-efe7-11e6-9405-18f99cd7a9f9.gif)

![k](https://cloud.githubusercontent.com/assets/17777237/22844626/e5a16f8a-efe7-11e6-8022-085f082affa7.gif)

inside .blade.php type.

**Comment by Tyriar** [comment]
We defer support for lesser known languages like this to extensions https://marketplace.visualstudio.com/search?term=blade&target=VSCode&sortBy=Relevance
