### ISSUE TITLE
Multi Diff Editor menus: Submenu icon not rendered

### ISSUE THREAD

**Issue by alexandruavadanii** [microsoft/vscode#203792]
Type: <b>Bug</b>

An extension that contributes a submenu with a valid icon to `multiDiffEditor/resource/title` is rendered without the icon (screenshot made on mouse hover, without hovering it's not even visible):
![image](https://github.com/microsoft/vscode/assets/11544783/22a01212-124b-4ece-97d0-eef45cb7c6cf)

For comparison, the same submenu icon shows fine as a contribution to `view/title`:
![image](https://github.com/microsoft/vscode/assets/11544783/86b912c8-0b54-4242-b355-116450f22ca1)

To reproduce this, I created an empty extension with a simple set of menu contributions.

[1] https://github.com/alexandruavadanii/vscode-submenu-icon
[2] https://github.com/alexandruavadanii/vscode-submenu-icon/commit/098d2bb44bd288038761a91ca1c73db4fc9cd9ea

VS Code version: Code - Insiders 1.86.0-insider (9c5eabb378c9d18a0f712d1f22fe63df3f933ade, 2024-01-30T03:56:13.017Z)
OS version: Windows_NT x64 10.0.18362
Modes:
Remote OS version: Linux x64 4.18.0-372.19.1.el8_6.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (6.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sestolabccv8|
|OS|Linux x64 4.18.0-372.19.1.el8_6.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (8 x 2095)|
|Memory (System)|31.21GB (16.98GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: sestolabccv8|
|OS|Linux x64 4.18.0-372.19.1.el8_6.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (8 x 2095)|
|Memory (System)|31.21GB (16.98GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: sestolabccv8|
|OS|Linux x64 4.18.0-372.19.1.el8_6.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (8 x 2095)|
|Memory (System)|31.21GB (16.98GB free)|
|VM|100%|
</details>

**Comment by hediet** [comment]
Can you look into why this happens?

**Comment by alexandruavadanii** [comment]
I will give it a try.

**Comment by hediet** [comment]
Thank you, that is a very detailed analysis! Will look into it
