### ISSUE TITLE
Vscode shell tasks

### ISSUE THREAD

**Issue by windmillcode0** [microsoft/vscode#203705]
Type: <b>Feature Request</b>

I know from regular terminal processes when you reload the window the terminal does not get killed can this be an option feature for vscode tasks as well

In addition I would like an os-agnostic solution where you have the option to open running tasks in external terminal windows and even so if the OS terminal supports tabs have all the task run in each respective tab in the same terminal window

In addition just like you can dock text editors you should add a feature to dock terminals as well, so you dont have to create an os-agnostic solution

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by Tyriar** [comment]
> I know from regular terminal processes when you reload the window the terminal does not get killed can this be an option feature for vscode tasks as well

Tasks do support reconnection, I believe this was implemented before you reported this. Please create a new issue with more information if you have problems with this.

> In addition I would like an os-agnostic solution where you have the option to open running tasks in external terminal windows and even so if the OS terminal supports tabs have all the task run in each respective tab in the same terminal window

We have minimal integration with external terminals to reduce bloat in VS Code. This is a good candidate for an extension to implement.

> In addition just like you can dock text editors you should add a feature to dock terminals as well, so you dont have to create an os-agnostic solution

Not sure what you mean exactly, but it sounds a little like https://github.com/microsoft/vscode/issues/34442

**Comment by windmillcode0** [comment]
We have minimal integration with external terminals to reduce bloat in VS Code. This is a good candidate for an extension to implement.

- I am not sure what is meant by this. Essentially what we are coming to find is that when a task is run in vscode and it has to run a command in an external terminal for progress reporting the external terminal is opened. But an error is thrown when attempting to run the command in an external terminal and it has to be done via different methods. This is needed to show user progress of the task they are running
