### ISSUE TITLE
Support nested in CSS syntax

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#203727]
Our CSS grammar/LS does not appear to properly colorize [nested CSS rules](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting):

<img width="220" alt="image" src="https://github.com/microsoft/vscode/assets/2230985/0a4ce46b-2f9a-4fec-8bdf-3008e1ca114c">

**Comment by aeschli** [comment]
Waiting for https://github.com/microsoft/vscode-css/issues/9.
