### ISSUE TITLE
Codespaces times out and doesn't save/restore Terminal output

### ISSUE THREAD

**Issue by petewu100** [microsoft/vscode#203864]
After I run a build command in the Terminal pane, I work on something else since it takes a while to run. Then I come back and find that Codespaces has shutdown. So, I sign in again and find that a new Terminal session, and there doesn't seem to be a way to access my old Terminal session. So, I don't know if my build succeeded (unless I dig through logs; I'm not sure where they are).

Since Codespaces shuts down so often (which is super annoying for coding, which requires long running tasks), it's super important for it to save/restore state. Losing the Terminal output every time makes it really painful to use.

**Comment by meganrogge** [comment]
tweaking this might help you `terminal.integrated.persistentSessionReviveProcess`.
