### ISSUE TITLE
Check /var/lib/ca-certificates/ca-bundle.pem for system certificates

### ISSUE THREAD

**Issue by fortenforge** [microsoft/vscode#203847]
OpenSUSE stores system certificates here and they are not correctly picked up by vscode server as mentioned in this issue: https://github.com/microsoft/vscode/issues/189696

**Comment by chrmarti** [comment]
`/etc/ssl/ca-bundle.pem` seems slightly more generic (noted in https://github.com/microsoft/vscode/issues/189696#issuecomment-1898673792). I will go with that, thanks!
