### ISSUE TITLE
Go Back and auxiliary windows

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#203889]
I'd like "Go Back" to be per-window. Each window feels like a separate entity, so I find myself expecting "Go Back" to only go back in the window that my focus is in.

**Comment by bpasero** [comment]
One way there is to configure `workbench.editor.navigationScope` to `editorGroup` so that navigation is limited to editors of one group. Can you try?

**Comment by alexr00** [comment]
I don't usually use more than 1 editor group in a window, so this perfectly satisfies the behavior I want. Thanks!

**Comment by bpasero** [comment]
Thanks for selfhosting 👍
