### ISSUE TITLE
My CS50 Visual Studio won't load

### ISSUE THREAD

**Issue by Capver** [microsoft/vscode#203803]
My CS50 Visual Studio won't load. It keeps loading forever with me not being able to type or code anything.

Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by aeschli** [comment]
Can you reach out to the CS 50 support / help desk?
