### ISSUE TITLE
Restore option is getting displayed for both project.json file and csproj file.

### ISSUE THREAD

**Issue by anuraj** [Microsoft/vscode#20383]
- VSCode Version: Version 1.9.1
- OS Version: Windows 10 - version 1607 (OS Build 14393.693)

Steps to Reproduce:

1. Migrated my existing dotnet core project using dotnet migrate command, which created backup folder and moved project.json file inside it.
2. Then open the project folder in VSCode.
3. Here is the screenshot.

![image](https://cloud.githubusercontent.com/assets/276411/22820394/8ee0394c-ef9c-11e6-9e2a-e85b9b0e6582.png)

**Comment by Tyriar** [comment]
Please file this to the C# extension repository https://github.com/OmniSharp/omnisharp-vscode
