### ISSUE TITLE
Impossible to show/hide source control buttons when multiple repositories are open

### ISSUE THREAD

**Issue by HolyBlackCat** [microsoft/vscode#203887]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.2
- OS Version: Linux x64 6.5.13-7-MANJARO

Steps to Reproduce:

1. Open folder with a repostory, without submodules.
2. Open the version control tab, observe following buttons:
![one](https://github.com/microsoft/vscode/assets/20289055/d7f24445-6b49-4074-9f02-fef3e31e903c)
3. You can right-click them, and there are checkbox to disable them:
![two](https://github.com/microsoft/vscode/assets/20289055/47244988-ba46-47e0-81f6-46220fbbf595)
4. Now create a submodule in your repo: `git submodule add SOME_URL`. (You might need to reload VSC to load it.)
5. The original buttons disappear from the header, and now there are multiple sets of buttons:
![three](https://github.com/microsoft/vscode/assets/20289055/108e0993-2282-402a-bdcf-47f4006577db)
6. But those **can't** be right-clicked to disable them.

**Comment by lszomoru** [comment]
Great timing. The capability to hide these actions is always available in VS Code Insiders and will be available in the next VS Code Stable release scheduled for later this week.
