### ISSUE TITLE
[loc][Query][VSCode] Please conform translatability

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20388]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Controls the dimensions of opening a new window. By default, a new window will open in the center of the screen with small dimensions. When set to  'inherit', the window will get the same dimensions as the last active one. When set to 'maximized', the window will open maximized and fullscreen if configured to 'fullscreen'.

File Name:
src\vs\workbench\electron-browser\main.contribution.nls.resx

Resource ID:
".resx", 0; "newWindowDimensions"

Query:
Please confirm "inherit", "maximized" and "fullscreen" are to be translated.

**Comment by bpasero** [comment]
@mkyjakova they are NOT to be translated because they are the setting values. I will push a change to extract them as variables 👍
