### ISSUE TITLE
[loc][Query][VSCode] Please clarify "language"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20386]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Configure language specific settings...

File Name:
src\vs\workbench\parts\preferences\browser\preferencesActions.nls.resx

Resource ID:
".resx", 0; "configureLanguageBasedSettings"

Query:
Does it refer to a programming language? Please, confirm.	Cristina Carrasco	2/2/2017 11:20:42 AM

**Comment by Tyriar** [comment]
Yes, programming language or more generically the "language" that the file is written in. Note that this is not necessarily a programming language, "Markdown" for example is a format for prose.
