### ISSUE TITLE
"Merge conflict marker encountered" problems after resolving merge conflict

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#203813]
<img width="387" alt="image" src="https://github.com/microsoft/vscode/assets/323878/93cb8df0-8c62-4c3d-9431-bfb2e956fdd2">

I see this sometimes after using the merge editor. They don't go away until the window is reloaded. Do you know anything about this, or do you know which extension they would be coming from?

**Comment by chrmarti** [comment]
A web search suggests this might be a stale ESLint error (stale from the CLI, not the extension). 🤷‍♂

**Comment by hediet** [comment]
The extension host could be frozen. In any case, this is unrelated to the merge editor.
