### ISSUE TITLE
Shifting from a long running query --> Explain without running doesn't stop the long running query

### ISSUE THREAD

**Issue by forstie** [microsoft/vscode#203855]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

ctcdb31a - db2data iasp
SELECT * FROM kraken77.ITEM_FACT order by shipmode, receiptdate; -- run and explain
SELECT * FROM kraken77.ITEM_FACT order by shipmode, receiptdate; -- Explain without running

I ran 'Run and Explain against a long running query, and then regretted the choice.
Then, I ran 'Explain without running'. ... VS makes it look like Explain without running is happening, when in fact it isn't.
You could use SQL_Cancel to whack the previous query when the user asks for sumpin different.
image.png
 
image.png
<img width="605" alt="image" src="https://github.com/microsoft/vscode/assets/22151636/27252d75-76e1-497a-806c-63e7e776ec0b">

**Comment by worksofliam** [comment]
This can be closed. Please recreate at codefori/vscode-db2i.

**Comment by forstie** [comment]
Done. Sorry.
