### ISSUE TITLE
apt repository is configured to use legacy HTTP protocol

### ISSUE THREAD

**Issue by fmarier** [microsoft/vscode#203832]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.2-1705561292
- OS Version: Debian GNU/Linux trixie/sid

Steps to Reproduce:

1. Install VSCode `.deb` package.
2. Look in `/etc/apt/sources.list.d/vscode.list`

Expected:
```
$ cat /etc/apt/sources.list.d/vscode.list 
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main
```

Actual:
```
$ cat /etc/apt/sources.list.d/vscode.list 
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code stable main
```

HTTPS repositories have been supported in Debian and Ubuntu for a very long time and `packages.microsoft.com` is already available on HTTPS so this is a simple configuration change.

**Comment by Tyriar** [comment]
Fixed in https://github.com/microsoft/vscode/pull/203833
