### ISSUE TITLE
a warning dialog cannot be closed blured

### ISSUE THREAD

**Issue by gfafei** [Microsoft/vscode#20384]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.5|

---

Steps to Reproduce:

random appears.
a warning dialog that cannot be closed and blurs...
the warning is 'typescript service ends in last 10 minutes'

**Comment by mjbvz** [comment]
Can you please provide a screenshot of the warning and some repo steps for the problem.

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this. Please also try out the latest VSCode insiders releases which contain a number of important fixes
