### ISSUE TITLE
[BUG] Autocomplete with Default Colour in Workspace Colour Customisations

### ISSUE THREAD

**Issue by Number-3434** [microsoft/vscode#203828]
Does this issue occur when all extensions are disabled?: Yes

Provide autocompletions for properties in `workbench.colorCustomizations` with the default colours, instead of `#ff0000`.

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/issues/25633 is similar. Ok to mark as duplicate?

**Comment by Number-3434** [comment]
> #25633 is similar. Ok to mark as duplicate?

Yes, sorry I didn't realize. Could you change the title of that to be a bit more concise?

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/issues/25633 is about the current value (based on the currently selected theme) while your suggestion is about the default value (which is the color of the Default Modern theme).
I think the current color is more useful as you normally want to tune the currently visible colors.

**Comment by Number-3434** [comment]
> #25633 is about the current value (based on the currently selected theme) while your suggestion is about the default value (which is the color of the Default Modern theme).
> I think the current color is more useful as you normally want to tune the currently visible colors.

Yeah, sorry I meant the default _for_ current colour.
