### ISSUE TITLE
VSCode crashes every night

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#2038]
I'm working daily with VSCode and usually left it opened during night.

Most of the time, when unlocking my computer, I find out VSCode has crashed:

![codecrash](https://cloud.githubusercontent.com/assets/199648/12349350/4ea097bc-bb6f-11e5-8860-ed2225413720.jpg)

What can I do to help track down the problem ?

I'm using VSCode 0.10.6 (but I had the problem with previous versions as well) on Windows 10 x64.

**Comment by bpasero** [comment]
#508
