### ISSUE TITLE
Build: CLI jobs can't be retried sometimes

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#203871]
There are cases in which CLI jobs will fail after having published certain artifacts, for misc reasons. In this specific case, the entire pipeline was cancelled after the `CLILinuxGnuARM` job [had published](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=254400&view=logs&j=c73ef358-0dd7-5529-c2fa-4ddc54fac97c&t=4c9ebf24-921a-5eca-132c-363c39f2fc11&s=a2720dec-461a-5b3d-f007-6e0de7b924c4) the `vscode_cli_linux_arm64_cli` artifact. Upon re-running failing jobs, the same job started to [fail on that publish step](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=254400&view=logs&j=d50e285b-caa7-5e64-8bdc-6b751441dcc1&t=20c86de6-3178-57d0-3ea1-7f7d4d418623) since it can't republish the same artifact.

I recognize the issue since we hit the same before in all other jobs, where we made the decision to keep all _statically named_ artifact publishing [close together](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=254386&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=81c4857c-1565-5f10-675a-78a0149bee49) towards the end of each job. I propose we do the same for the CLI jobs. It doesn't entirely solve the problem, but certainly mitigates it to the point of irrelevancy.

**Comment by alexr00** [comment]
Verified by looking through our builds and determining that none of them failed for this reason since this fix went in.
