### ISSUE TITLE
RSS Feed for the VS Code Blog Has an Invalid Content-Type Charset

### ISSUE THREAD

**Issue by richardcox13** [microsoft/vscode#203974]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  latest
- OS Version: Win 10

Note: this is an issue with https://code.visualstudio.com, rather than VS Code itself; the report problem link points here. If there is a better place to report issues with the website please make that clear.

Steps to Reproduce:

1. Use .NET 6's System,.Net.Http.HttpClient to get the contennt of  https://code.visualstudio.com/feed.xml as a string

```
// http is an instance of HttpClient
using var resp = await http.GetAsync(curUrl);
using var content = resp.Content;
contentText = await content.ReadAsStringAsync(); // ****
```

2. At the line marked `****` get

```
System.InvalidOperationException: The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set.
 ---> System.ArgumentException: 'utf8' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
```

Examining the header one sees:

```
Content-Type: application/xml; charset=utf8
```

**Problem:** [RFC 2616 section 3.4](https://www.rfc-editor.org/rfc/rfc2616#section-3.4) defines that the `charset` parameter has a case insensitive value from the [IANA Character Sets registry](https://www.iana.org/assignments/character-sets/character-sets.xhtml). The registry lists "UTF-8", not "utf8".

**Comment by rzhao271** [comment]
Fixed
