### ISSUE TITLE
`Markdown › Preview: Scroll Preview With Editor` can not work on other language mode (e.g., rmarkdown or quarto)

### ISSUE THREAD

**Issue by ChoCho66** [microsoft/vscode#203907]
I use `markdown.showPreviewToSide` in the language mode `quarto`.
`Markdown › Preview: Scroll Editor With Preview` works in language mode of `quarto` (or `rmarkdown`).
But `Scroll Preview With Editor` doesn't work, as shown in the video below

https://github.com/microsoft/vscode/assets/72805700/316ac8e2-9047-4164-95c4-57d13e463abf

Is there any way to support the `Scroll Preview With Editor` function in the language mode of `quarto` (or `rmarkdown`)?

**Comment by mjbvz** [comment]
The built-in markdown preview only works for markdown files. Please file this issue against the extensions of those other languages
