### ISSUE TITLE
C/C++: in-function #define makes stickyscroll disappear

### ISSUE THREAD

**Issue by bjornrd** [microsoft/vscode#203921]
Does this issue occur when all extensions are disabled?: Yes

Type: <b>Bug</b>

void someFunc() {
    #define A

}

<< This will cause stickyscroll to disappear in the editor window >>

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22631
Modes:

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|14.7.0
language-matlab|Mat|1.1.6
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.9
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019bcf:30953938
3ef8e399:30949928

```

</details>

**Comment by wolfjazz** [comment]
Macros are quite common in embedded C/C++. I would appreciate if this could be fixed.

**Comment by aiday-mar** [comment]
this would be fixed by https://github.com/microsoft/vscode/issues/168428, closing this issue
