### ISSUE TITLE
Terminal doesn't look good on Windows VScode 👀

### ISSUE THREAD

**Issue by ashishworkspace** [microsoft/vscode#203914]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.2
- OS Version: Windows

Steps to Reproduce:

1. When i open the vscode inside a particular directory using command `code .`
2. The teminal prompt look very messy.
3. Here i was just doing `npm i`. 
<br>
<strong>As you can see here "npm i" command got messed up with the directory path.</strong>

![image](https://github.com/microsoft/vscode/assets/70542481/947832f8-3bbb-4a2c-81f5-5fa300c2f04f)

**Comment by meganrogge** [comment]
I cannot reproduce. A Gif would help

**Comment by ashishworkspace** [comment]
I guess this is happening due to resizing of the  window.
Please watch the full video. 

https://github.com/microsoft/vscode/assets/70542481/63ffde2f-617b-41bd-8206-35559444189a

**Comment by ashishworkspace** [comment]
@meganrogge 

![image](https://github.com/microsoft/vscode/assets/70542481/def566af-453b-44cf-b81f-5fbbccfcf8e5)

**Comment by Tyriar** [comment]
![image](https://github.com/microsoft/vscode/assets/2193314/6948baa9-30cb-4205-be14-d2b408b53331)

This is conpty not liking the small size of the new window and rendering incorrectly when the prompt is "unwrapped".

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You will need to upgrade Windows to use conpty. You can read more about ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423) and [here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by ashishworkspace** [comment]
Thanks @Tyriar  for your help 👍
