### ISSUE TITLE
Git's Fetch and Pull buttons on SCM Incoming section are hard to differentiate

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#203990]
On the left is Fetch and on the right is Pull. The broken line on the arrow shaft is all I'm seeing different on the first compared to the second.

![image](https://github.com/microsoft/vscode/assets/6726799/511da214-4005-4901-85eb-937e3b60eebb)

VS Code version: Code - Insiders 1.87.0-insider (442c133fe92b5e2606c8242caae4e68938faccc7, 2024-02-01T09:49:33.086Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by lszomoru** [comment]
Adding @hbons.

**Comment by lszomoru** [comment]
Closing this issue as the incoming/outgoing changes section has been removed.

**Comment by gjsjohnmurray** [comment]
They're now on the Source Control Graph view and just as hard to tell the difference between, visually:

![Image](https://github.com/user-attachments/assets/a6842478-6190-43c3-92d3-67d5fb5a3f9e)
