### ISSUE TITLE
[loc][Query][VSCode] Please clarfify the single word string

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20390]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Developer

File Name:
src\vs\workbench\electron-browser\window.nls.resx

Resource ID:
".resx", 0; "developer"

Query:

Is it referred to a real developer or to a product version?

**Comment by Tyriar** [comment]
Developer here is referring to a the developer command category, 'toggleDevTools' in actions.nls.resx whose text is "Toggle Developer Tools" is a command that belongs to the "Developer" category.
