### ISSUE TITLE
allow rendering objects in the settings UI

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#203916]
I'm refactoring the `audioCue` and `alert` settings to be in a new object together. A downside is that now users have to edit the settings in the settings.json file, which can be a challenge for blind people. It would be great if these could be rendered in the settings UI. 
![Screenshot 2024-01-31 at 11 39 02 AM](https://github.com/microsoft/vscode/assets/29464607/2cdf3be9-d303-41ae-8a8c-a501d066faea)

**Comment by rzhao271** [comment]
If those are the only allowed keys, does adding `"additionalProperties": false` work?

**Comment by meganrogge** [comment]
that worked, thanks!
