### ISSUE TITLE
Allow duplicating multiple preferences into the clipboard as JSON.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/vscode#203923]
I'm able to duplicate 1 preference into the clipboard as JSON, but to be able to (for instance) provide the state of an extension for diagnosis purposes, being able to select and duplicate the state of multiple as JSON would be incredibly useful.

**Comment by mjbvz** [comment]
You can open the settings files as json  if you want to copy multiple values

![Image](https://github.com/microsoft/vscode/assets/12821956/8fd4ff85-aa4e-4405-a2b2-9344f32100b5)

**Comment by RedCMD** [comment]
there's also a small button in the top right of the settings page to open it in json

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/vscode/issues/203923#issuecomment-1933166737

It's not literally as quick to use, but that's certainly adequate for my use case. Thanks, @mjbvz and @RedCMD.
