### ISSUE TITLE
Use codelens to run/debug tests

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#203913]
When I do right or left click on the test indicator in the gutter, this menu shows up:

![image](https://github.com/microsoft/vscode/assets/2931520/889b95c4-272b-4280-a1ac-82c4485135af)

(I think this used to be different, the test would just run)

I think it would make sense to explore to use code-lenses to run/debug/run-with-coverage the test instead.
That would also solve the problem with breakpoints and the revert arrow.

**Comment by connor4312** [comment]
Let's revive https://github.com/microsoft/vscode/issues/133338
