### ISSUE TITLE
[loc][Query][VSCode] Please clarify the abreviation

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20391]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Developer: Inspect TM Scopes

 File Name:
src\vs\editor\contrib\inspectTMScopes\electron-browser\inspectTMScopes.nls.resx

Resource ID:
".resx", 0; "inspectTMScopes"

Query:
Please clarify TM. What does it stand for?

**Comment by josefhosek** [comment]
TM Scopes = TextMate Scopes
