### ISSUE TITLE
Version 1.86 cannot open my development container

### ISSUE THREAD

**Issue by mcartoixa** [microsoft/vscode#203979]
Type: <b>Bug</b>

I just upgraded to version 1.86.0 and I cannot open my development container anymore. It seems that the _Reopen container_ menu executes the _Add Dev Container Configuration Files..._ menu instead...

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.81GB (23.25GB free)|
|Process Argv|--crash-reporter-id ff2baee8-ea87-433e-9dc1-d75ff8719e13|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.16.4
vscode-peacock|joh|4.2.2
vscode-docker|ms-|1.28.0
vscode-language-pack-fr|MS-|1.85.2024013109
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
vsliveshare|ms-|1.0.5905
vsliveshare-pack|ms-|0.4.0
LiveServer|rit|5.7.9
ruby-lsp|Sho|0.5.9
code-spell-checker|str|3.0.1
code-spell-checker-french|str|0.4.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
0bi6i642:30951795
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019bcf:30953938
3ef8e399:30949928

```

</details>

**Comment by ferreteleco** [comment]
It happened the same to me after update. Downgraded to 1.85.2 for the moment

**Comment by pepisg** [comment]
same here

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode/issues/203964.
