### ISSUE TITLE
File: Reveal Active File in Explorer View does NOT work if window is reloaded and Explorer panel is NOT focused

### ISSUE THREAD

**Issue by tnrich** [microsoft/vscode#203927]
Does this issue occur when all extensions are disabled?: Yes/No
YES

Version: 1.85.2 (Universal)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:32.531Z (1 wk ago)
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 21.6.0

https://github.com/microsoft/vscode/assets/2730609/cf7bfcb3-1daa-41f3-98c3-42a142e7085e

Steps to Reproduce:

1. Open a project in VSCode, open a random file, focus the debugger panel (any panel besides the File Explorer will work)
2. Cmd-P > Developer: Reload With Extensions Disabled
3. Cmd-P > Reveal Active File in Explorer View 
4. Nothing happens.. The explorer view is NOT focused and the active file does NOT show up

Maybe a dupe of https://github.com/microsoft/vscode/issues/197268 however I believe I am up to date with the latest version of vscode and I am still seeing this happen. 

@mjbvz has your issue been fixed on the latest version? If so then I think mine is a unique and still active issue. Cheers!

**Comment by lramos15** [comment]
I cannot repro doing exactly that. There will be a new 1.86 build out in a few days so maybe we wait and you can try that.

**Comment by lramos15** [comment]
Can you try again after updating @tnrich

**Comment by tnrich** [comment]
@lramos15 looks like this got fixed! Mazeltov! 💐
