### ISSUE TITLE
Visual code window does not seem to be active window

### ISSUE THREAD

**Issue by anand-xoriant** [Microsoft/vscode#20395]
Hi,
When we open Visual code, its title bar should be shown in blue color because it is an active window. However, the title bar shows gray color even though it is made active window.
-Anand Kulkarni

**Comment by bpasero** [comment]
@anand-xoriant are you on a stable Windows release? Or what OS?

**Comment by anand-xoriant** [comment]
I am on windows 7

-Anand Kulkarni

**Comment by bpasero** [comment]
@anand-xoriant can you share a screenshot how this looks like for you?

**Comment by anand-xoriant** [comment]
Actually after getting this bug, I updated Visual code to latest version
(1.9.1) & now I am not facing this problem. I will keep watch & if I come
across it once again then will forward you the screenshot.

-Anand Kulkarni

**Comment by anand-xoriant** [comment]
Please find the attached images where you can clearly see that Visual code
window is active but the title bar is not showing in BLUE color.

-Anand Kulkarni

**Comment by Tyriar** [comment]
@anand-xoriant images attached via email don't come through in GitHub.

**Comment by anand-xoriant** [comment]
![visual_code_image](https://cloud.githubusercontent.com/assets/16187119/22926777/1e43a238-f2d4-11e6-8fb8-c9e8c5f4bb1a.png)
