### ISSUE TITLE
Markdown preview line sync is reset when writing

### ISSUE THREAD

**Issue by StephD** [Microsoft/vscode#20399]
- VSCode Version: 1.9.1 (1.10.2 too)
- OS Version: Win7
- Extension for markdown : 
auto-open markdown / markdown shortcut / markdown pdf / markdownlint

Steps to Reproduce:

1. Create a markdown file and write enought text to activate the scroll
2. Click somewhere and see the preview be syncronize on the same line
3. Write something
=> The preview will go to the beginning of the file

Each letter I write, the preview go to the correct line then back to the begin of the preview

**Comment by SamuelYvon** [comment]
Same issue, on windows 10, default install of VSCode

**Comment by mjbvz** [comment]
I'm unable to repo this. Can you please share a markdown file that you see this in? A gif showing the behavior may also be helpful

Thanks

**Comment by StephD** [comment]
Here is the gif and part of the md file. I tried with this part too in an unique md file and still have the issue.


![output_0tov5m](https://cloud.githubusercontent.com/assets/1171858/22979331/4b74af6e-f396-11e6-96b3-c3d4bde7bc17.gif)


# Memcached

## Installation

Installer les extension pour zend-server.

* Ubuntu :

```
apt-get install memcached php-5.6-memcache-zend-server php-5.6-memcached-zend-server
```

* Lamp :

```
php-memcache
```

* CentOs :

```
yum install -y libevent libevent-devel memached php-pecl-memcache
yum -y install php-5.3-memcache-zend-server.x86_64
yum -y install php-5.3-memcached-zend-server.x86_64
```

* Windows :

**Comment by mjbvz** [comment]
Please try out VSCode 1.10. There were a few issues around preserving the scroll position that I believe  1.10 fixed

**Comment by SamuelYvon** [comment]
Sorry, still doesn't work on 1.10.1 @mjbvz

**Comment by mjbvz** [comment]
@SamuelYvon Are you also on windows 7? Can you please share a document that has this problem

**Comment by SamuelYvon** [comment]
I am on windows 10, here is a snippet of the document (I made it to test the issue)

```
a
a
a
a
a
a
a


a


a



a



a



a



a



a



a
```

Every time an 'a' is copy-pasted, the previous reset to the top and then comes back to the bottom

**Comment by VeryLazyBoy** [comment]
I have the same problem:
![gif](https://cloud.githubusercontent.com/assets/18899212/23758138/b6825ef2-0523-11e7-8812-b11ea43a8a26.gif)

**Comment by SamuelYvon** [comment]
Doesn't happen to me anymore on 1.10.2!

**Comment by StephD** [comment]
No change for me into the version 1.10.2

**Comment by VeryLazyBoy** [comment]
No change for me either.

**Comment by Zicore** [comment]
This bug is still there.

Windows 10.
VSCode 1.10.2

**Comment by Koasing** [comment]
Windows 10, VSCode 1.10.2

Please check [this line](https://github.com/Microsoft/vscode/blob/93ec9ddbd5cf47955569a8da5b0cacf992f0e232/extensions/markdown/src/previewContentProvider.ts#L141).
In windows system, it seems that two **fsPath** variables points to same path but drive letter is case-inverted. In my case `editor.document.uri.fsPath` was `/D:/data/BlahBlah/markdown.md`, but `sourceUri.fsPath` was `/d:/data/BlahBlah/markdown.md`. Only single character caused the problem.
Removing comparison in if-condition solved the problem, but it is very rough solution. Doing case-insensitive comparison on windows system would be more smart way.

**Comment by mjbvz** [comment]
Please let me know if you are still seeing this issue in VS Code 1.19
