### ISSUE TITLE
Compare of large JSON files stuck indefinitely

### ISSUE THREAD

**Issue by d07RiV** [microsoft/vscode#203918]
Type: <b>Performance Issue</b>

Comparing large (300k lines) JSON files never completes (even after waiting for several minutes). Using alternative tools such as WinMerge loads these files in just a few seconds.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3893)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.95GB (39.45GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 8b9e57bc-ac2b-45e6-9844-08b08d97b131|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    99	 24924	code main
    0	   121	  1796	shared-process
    0	    82	  6292	fileWatcher [1]
    1	    90	  8904	window [2] (Issue Reporter)
    0	    40	 11456	   utility-network-service
    0	    29	 17192	   crashpad-handler
    1	    96	 17404	   gpu-process
    6	   294	 19048	window [1] (data.old.json ↔ data.new.json - compare - Visual Studio Code)
    0	   254	 26788	extensionHost [1]
    0	   159	 29476	     electron-nodejs ("C:\Users\d07ri\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\d07ri\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=26788)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (data.old.json ↔ data.new.json - compare - Visual Studio Code)
|    Folder (compare): 4 files
|      File types: json(4)
|      Conf files:;
```

</details>
Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019bcf:30953938
3ef8e399:30949928

```

</details>

**Comment by hediet** [comment]
There is already an issue that requests better peformance for the diff algorithm.
Closing, because this issue does not add anything new.
