### ISSUE TITLE
[loc][Query][VSCode] Plese clarify the string

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20398]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Open Folder

File Name:
src\vs\workbench\parts\git\browser\views\noworkspace\noworkspaceView.nls.resx
src\vs\workbench\parts\search\browser\searchViewlet.nls.resx

Resource ID:
".resx", 0; "openFolder"
".resx", 0; "openFolder"

Query:
Can you please clarify whether open here is a verb (as in "I want to open the folder", or an adjective ("This folder is open")? Thanks!

**Comment by Tyriar** [comment]
A verb; I want to open the folder.
