### ISSUE TITLE
remote SSH development stopped working

### ISSUE THREAD

**Issue by HennethAnnun** [microsoft/vscode#203977]
Type: <b>Bug</b>

You fu*ks, just in the middle of my work you push some update to VSCode that breaks my remote SSH. I can not work now! Stupid.

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.80GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bgrafana-plugin-dev/home/administrator/dev/sd-grafana-dvms-ordermanager|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|4.4.3
vscode-language-pack-pl|MS-|1.85.2024013109
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2024.1.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0

</details>

**Comment by giovannipollo** [comment]
Already discussing here #203967

**Comment by HennethAnnun** [comment]
Pardon my language. But let me send you a [face_palm].

**Comment by thekendog** [comment]
Same.  Can't get into anything now.  On a Mac.

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode/issues/203967
