### ISSUE TITLE
Code block collapse doesn't like powershell string

### ISSUE THREAD

**Issue by CrunchyFerrett** [microsoft/vscode#203934]
Type: <b>Bug</b>

I created a function in powershell, which also creates a string.
```
Function Hello
{
$thing = @"
mystring
"@
...
more statements
...
}
```
When trying to visually collapse the function in editor, it's collapsing to the close of the string, not the function. 

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (0.62GB free)|
|Process Argv|--crash-reporter-id 6fc5defc-afc6-4fec-ac9e-bb8e0cc6cc5e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.327.0
volar|Vue|1.8.27
vscode-typescript-vue-plugin|Vue|1.8.27

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019bcf:30953938
3ef8e399:30949928

```

</details>

**Comment by aeschli** [comment]
Out-of the box, VS Code's folding strategy for Powershell is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To understand the Powershell string syntax, a language extension is needed that contains a parser for Powershell.

If I'm not mistaken, the [Microsoft Powershell extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell) provides folding. I suggest to give it a try.
