### ISSUE TITLE
Launch a Maven favorite as "debug" 

### ISSUE THREAD

**Issue by Artur-** [microsoft/vscode#203963]
When trying to get around #[203962](https://github.com/microsoft/vscode/issues/203962) I created a "Favorite" `jetty:run` which would have solved my immediate problem if it would have been possible to right click -> debug. But when right clicking on a favorite, there is only "run"

**Comment by Artur-** [comment]
Also it seems I cannot delete favorites...

**Comment by gjsjohnmurray** [comment]
I think the 'favorites' feature you are referring to is being contributed by an extension, in which case please report the issue to the extension author.

**Comment by Artur-** [comment]
Oh, how can I know if it is or not.. and where it comes from?
