### ISSUE TITLE
Cannot add folder to root if only folders exist

### ISSUE THREAD

**Issue by hardija** [Microsoft/vscode#20394]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.7.3|
|npm-intellisense|christian-kohler|1.2.1|
|sublime-babel-vscode|joshpeng|0.2.4|
|vs-keybindings|ms-vscode|0.1.3|
|vscode-open|sandcastle|0.1.0|
|preview-vscode|searKing|1.1.1|

---

Steps to Reproduce:

1. Open an empty folder 
2. Create a new folder from the explorer new folder button
3. Attempt to create a new sibling folder at the root using the new folder button
4. Folder is created as a child of the first new folder
5. There is no way to select the root as the parent and add a folder from the explorer new folder button

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/1043
