### ISSUE TITLE
Unable to open file 

### ISSUE THREAD

**Issue by mjangid** [Microsoft/vscode#20403]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-eslint|dbaeumer|1.2.2|
|javadebugger|donjayamanne|0.0.2|
|vs-code-xml-format|fabianlauer|0.1.4|
|prettify-json|mohsen1|0.0.3|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.8.0|
|diff|rafaelmaiolla|0.0.1|
|java|redhat|0.0.8|
|partial-diff|ryu1kn|0.2.0|
|Spell|seanmcbreen|0.9.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.  Double click any file 
2.  Visual Studio code will launch with new file instead opening selected file

**Comment by bpasero** [comment]
@mjangid a complete uninstall and reinstall should help you.

**Comment by mjangid** [comment]
Thanks @bpasero
