### ISSUE TITLE
By default 6 instances of VS code opens

### ISSUE THREAD

**Issue by ayu15** [Microsoft/vscode#20405]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.7.3|

---

Steps to Reproduce:

1. Open vs code from shortcut or start menu or anywhere else.

Expected - only 1 instance should open.

Actual- 6 instances opens automatically.

**Comment by bpasero** [comment]
@ayu15 can you share a screenshot of these 6 instances? Can you share your settings?

**Comment by ayu15** [comment]
![vs code](https://cloud.githubusercontent.com/assets/7520476/22865654/a538009c-f160-11e6-8fba-e77850a1dfb4.JPG)
[settings.txt](https://github.com/Microsoft/vscode/files/769598/settings.txt)

Sharing the screenshot and settings

**Comment by Tyriar** [comment]
What is in the other windows?

**Comment by ayu15** [comment]
![vsprob](https://cloud.githubusercontent.com/assets/7520476/24335500/56fc96d6-1276-11e7-85c4-d77ea79fe42a.JPG)
other windows is having different files which were opened previously.
I think it is accumulating file history and opens all of them.
for e.g. once I open file A, then close it, then when I open file B it opens file A and B both.
I tried reinstalling but issue still persist.

**Comment by ayu15** [comment]
after modifying below setting, it resolved.
    "files.hotExit": "onExitAndWindowClose"

**Comment by Tyriar** [comment]
You probably have changes in all the windows, that's why they're being restored. `onExitAndWindowClose` makes it so opened folders with changes *will not* be restored. They are still backed up, just not restored whenever you launch VS Code, you need to explicitly open the folder to get your unsaved changes back.
