### ISSUE TITLE
broken devcontainer functionality on VSCode 1.86.0

### ISSUE THREAD

**Issue by mokshasoul** [microsoft/vscode#204092]
Type: <b>Bug</b>

1. Open VSCode in a repository with a devcontainer
2. Click on button or CMD+SHIFT+P --> Reopen in Container
3. Getting this error message: 
<img width="442" alt="image" src="https://github.com/microsoft/vscode/assets/9151046/429954f4-71aa-4b09-ad57-d192abe0b11c">
4. VSCode tries to create new devcontainer from template

VS Code version: Code 1.86.0 (Universal) (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:15.765Z)
OS version: Darwin x64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 6, 5|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv|--profile work . --crash-reporter-id 186eed90-9651-4493-a1d7-cf6d0f6adb2e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
vscode-neovim|asv|1.5.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.21.0
markdown-preview-github-styles|bie|2.0.3
markdown-yaml-preamble|bie|0.1.0
catppuccin-vsc|Cat|3.11.0
catppuccin-vsc-icons|Cat|1.8.0
ruff|cha|2024.8.0
path-intellisense|chr|2.8.5
gitignore|cod|0.9.0
python-snippets|cst|0.1.2
vscode-markdownlint|Dav|0.54.0
githistory|don|0.6.20
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
shell-format|fox|7.2.5
copilot|Git|1.156.0
copilot-chat|Git|0.12.0
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.80.0
cloudcode|goo|2.3.0
terraform|has|2.29.3
kdl|kdl|1.3.1
dotenv|mik|1.0.1
direnv|mkh|0.16.0
vscode-docker|ms-|1.28.0
black-formatter|ms-|2024.0.0
debugpy|ms-|2024.0.0
flake8|ms-|2023.10.0
isort|ms-|2023.10.1
pylint|ms-|2023.10.1
python|ms-|2024.0.0
vscode-pylance|ms-|2024.1.104
remote-containers|ms-|0.338.1
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
makefile-tools|ms-|0.8.22
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
autodocstring|njp|0.6.1
keyboard-quickfix|pas|0.0.6
vscode-yaml|red|1.14.0
jinjahtml|sam|0.20.0
sql-bigquery|shi|1.9.0
lua|sum|3.7.4
even-better-toml|tam|0.19.2
shellcheck|tim|0.35.0
vscode-conventional-commits|viv|1.25.0
jinja|who|0.0.8
markdown-all-in-one|yzh|3.6.2
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019bcf:30953938
3ef8e399:30949928

```

</details>

**Comment by mokshasoul** [comment]
Downgrading to previous VSCode version resolves the issue

**Comment by mokshasoul** [comment]
I've since restarted VSCode and it seems to work, this seems to have been an issue when first launching VSCode after the update.

I will do some test in soem other repositories we have

**Comment by rubensa** [comment]
Look very similar to [this](https://github.com/microsoft/vscode/issues/204069#issuecomment-1923017168).

**Comment by chrmarti** [comment]
A timing issue because the new Dev Containers version that adopts a change in VS Code 1.86 only installs when VS Code 1.86 is already running.

@deepak1556 I didn't realize at the time, but it might have been smoother to ignore `--ms-enable-electron-run-as-node` instead of failing in our Electron builds as we are transitioning away from it.

**Comment by mokshasoul** [comment]
@chrmarti thx I'll advise our teams to restart VSCode then

**Comment by deepak1556** [comment]
> I didn't realize at the time, but it might have been smoother to ignore --ms-enable-electron-run-as-node instead of failing in our Electron builds as we are transitioning away from it.

Agreed, will ensure this for similar changes in future.
