### ISSUE TITLE
1.86.0 devctainer stuck

### ISSUE THREAD

**Issue by apache2046** [microsoft/vscode#204059]
after upgraded to 1.86.0 macos client,  remote ssh to a linux server , start devcontainer, stuck at here.
21345 ms] Installing VS Code Server for commit 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
[21345 ms] Start: Run in container: /bin/sh
[21456 ms] Start: Downloading VS Code Server
[21456 ms] 05047486b6df5eb8d44b2ecd70ea3bdf775fd937 linux-x64 stable

**Comment by apache2046** [comment]
by downgrad to 1.85.0, the previous stuck dispear

**Comment by gjsjohnmurray** [comment]
What exact OS version is your Linux host?

**Comment by apache2046** [comment]
> S version is your Linux host?

th server is Ubuntu 22.04.3 LTS, the client is macos 14.3

**Comment by apache2046** [comment]
may be it's a CDN delay, today this stuck problem dispear with 1.86.0
