### ISSUE TITLE
I'm new to vscode and getting this error while installing python extension.Command 'Extensions: Disable All Installed Extensions' is not enabled in the current context.

### ISSUE THREAD

**Issue by upendar3** [Microsoft/vscode#20404]
- VSCode Version:1.9
- OS Version:windows 10

Steps to Reproduce:

1.
2.

**Comment by sandy081** [comment]
@upendar3 This happens when you invoke the command `Extensions: Disable All Installed Extensions` and no extensions are installed

![image](https://cloud.githubusercontent.com/assets/10746682/23363781/a122fb9a-fcfc-11e6-8bb5-21358078d20c.png)
