### ISSUE TITLE
Jupyter notebooks. Panel to navigate between titles of the notebook.

### ISSUE THREAD

**Issue by solisgb** [microsoft/vscode#204097]
Adding an option to display a panel with the notebook's Markdown titles would improve the notebook's navigation.

**Comment by gjsjohnmurray** [comment]
Did you try the Outline view?

**Comment by solisgb** [comment]
This option is not in the View of my current installation. In Help, it says
that no updates are available.

```
Version: 1.86.0 (user setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by gjsjohnmurray** [comment]
Do you not have the OUTLINE section of Explore view?

https://code.visualstudio.com/docs/getstarted/userinterface#_outline-view

**Comment by solisgb** [comment]
Sorry, I'm beginning to use VS Code. View | Explorer | Outline, YES, it's
there. I prompted Copilot from Edge and its answer was a complete mistake.

Thanks for your clarifications.

**Comment by gjsjohnmurray** [comment]
![image](https://github.com/microsoft/vscode/assets/6726799/05a90f6a-479a-4b50-8be7-32bc6d97f972)
