### ISSUE TITLE
[loc][query][VSCode] Please confirm translatability

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#20408]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
List of tags, comma separated, where the content shouldn't be reformatted. 'null' defaults to the 'pre' tag.

File Name:
extensions\html\package.nls.resx

Resource ID:
".resx", 0; "html.format.contentUnformatted.desc"

Query:
Please confirm "null" and "pre" are not to be translated.

**Comment by aeschli** [comment]
Correct: "null" and "pre" are not to be translated.
