### ISSUE TITLE
VSCode.cmd not propogating exit code 1 from vscode.exe if --install-extensions fails

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#204067]
CC @connor4312 

Currently vscode will exit 0 if there was a problem using the --install-extension command switch, this makes tools that rely on it forced to parse stderr to verify the result. It should exit 1.

**Comment by sandy081** [comment]
I just tried this and it exits with exit code 1 when there is an error installing extension. Can you please give us more information where it is not happening for you?

**Comment by JustinGrote** [comment]
@sandy081 https://github.com/microsoft/vscode-test-cli/pull/17#discussion_r1475439011
![image](https://github.com/microsoft/vscode/assets/15258962/0b49085f-df9c-4829-8ffc-b2e5858111a0)

**Comment by sandy081** [comment]
I clearly see the exit code 1 and installation feature is throwing an error in this case. Hence assigning to @connor4312 to check if he is propagating this error correctly or not

**Comment by connor4312** [comment]
This is running through VS Code's shell scripts, I don't own anything in the pipeline that touches the code here 🙂 

Maybe `code.bat` doesn't propagate Electron's exit code

**Comment by JustinGrote** [comment]
I should have clarified this is on Windows and it is in fact using code.cmd so the problem is likely there.
![image](https://github.com/microsoft/vscode/assets/15258962/bbab22a6-5fec-4dd3-a7e2-11cac2084bc7)

**Comment by JustinGrote** [comment]
@connor4312 thank you! :)
