### ISSUE TITLE
VS Code do not connect to any SSH Remote server

### ISSUE THREAD

**Issue by michalpolic** [microsoft/vscode#204025]
Type: <b>Bug</b>

Other applications can connect via SSH to remote servers (tried multiple devices) while the VS Code always fails to establish connection. In past, it helped to shut down VS Code and load it. Reload of Window did not helped. Now this tweek do not work neither the restart of PC.

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.26040
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (18.07GB free)|
|Process Argv|--crash-reporter-id 2b924b56-cc2e-488b-959c-74dd190fb7ee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
azurite|Azu|3.29.0
armview|ben|0.4.6
vscode-pytest|Cam|0.1.1
doxdocgen|csc|1.4.0
dscodegpt|Dan|3.1.7
vscode-eslint|dba|2.4.4
vscode-html-css|ecm|2.0.9
copilot|Git|1.156.0
copilot-chat|Git|0.12.0
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
git-graph|mhu|1.30.0
azure-pipelines|ms-|1.228.0
azure-dev|ms-|0.8.0
vscode-azureappservice|ms-|0.25.1
vscode-azurecontainerapps|ms-|0.6.1
vscode-azurefunctions|ms-|1.13.2
vscode-azureresourcegroups|ms-|0.8.3
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.15.3
vscode-azurevirtualmachines|ms-|0.6.5
vscode-bicep|ms-|0.24.24
vscode-cosmosdb|ms-|0.20.1
vscode-docker|ms-|1.28.0
vscode-dotnet-runtime|ms-|2.0.1
autopep8|ms-|2023.8.0
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2024.1.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
tensorboard|ms-|2023.10.1002992421
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.338.1
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
azure-account|ms-|0.11.6
azurecli|ms-|0.6.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.19.2
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
vscode-node-azure-pack|ms-|1.2.0
azurerm-vscode-tools|msa|0.15.11
vscode-singularity|onn|0.7.0
vscode-yaml|red|1.14.0
vscode-qt-for-python|sea|7.6.0
remote-x11|spa|1.5.0
remote-x11-ssh|spa|1.5.0
cmake|twx|0.0.17
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019bcf:30953938
3ef8e399:30949928

```

</details>

**Comment by qinnamon** [comment]
I can't connect either this morning and it turns out that I am using Amazon Linux 2 which carries an older version of Glibc so VS Code 1.86.0 no longer supports it https://code.visualstudio.com/docs/remote/faq#_can-i-run-vs-code-server-on-older-linux-distributions

**Comment by gfub** [comment]
Have also run into this issue. Downgrading to 1.85.2 and everything works. Kind of sucks if we can't upgrade from `1.85.2`. Another alternative is to switch to mutagen.

**Comment by geoffrey4444** [comment]
I have the same issue on macOS

**Comment by WinCPP** [comment]
@qinnamon @gfub @geoffrey4444 looks like this is same as https://github.com/microsoft/vscode/issues/203967?

**Comment by ZhanZiyuan** [comment]
I have the same issue trying to connect to CentOS 7.7.1908 wth glibc version 2.17.

**Comment by gfub** [comment]
@WinCPP yes that looks like the same. Thanks for surfacing that one, I came across this one first, but should have know it's more widespread.

**Comment by michalpolic** [comment]
@gfub thank you for the solution. Downgrading to 1.85.2 helped and everything works fine.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/203967#issuecomment-1923440629
