### ISSUE TITLE
couldnt run ssh

### ISSUE THREAD

**Issue by yaswanth872** [microsoft/vscode#204091]
Type: <b>Performance Issue</b>

since morning couldnt connect to my remote host 
[14:40:10.537] > 
[14:40:10.561] > Server did not start successfully. Full server log at /home/ydadi/.vscode-server
> r/.05047486b6df5eb8d44b2ecd70ea3bdf775fd937.log >>>
> Warning: Missing GLIBCXX >= 3.4.25! from /usr/lib64/libstdc++.so.6.0.19
> Warning: Missing GLIBC >= 2.28! from /usr/lib64/libc-2.17.so
> Error: Missing required dependencies. Please refer to our FAQ https://aka.ms/vsc
these are some of the errors and it is even saying couldnt start ssh

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Connection to 'SSH: 192.168.3.30' could not be established  The VS Code Server failed to start

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.74GB (0.65GB free)|
|Process Argv|--crash-reporter-id 9f95b768-ff3b-4797-aa4f-f268b962824c|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: 192.168.3.30' could not be established  The VS Code Server failed to start
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   217	 23548	code main
    0	    27	  2220	   crashpad-handler
    0	   115	  3392	extensionHost [1]
    0	    39	  7256	   utility-network-service
    0	    97	  9996	ptyHost
    0	   180	 19392	   gpu-process
    0	    98	 19776	shared-process
    0	   289	 19960	window [1] (Welcome - encryption_check [SSH: 192.168.3.30] - Visual Studio Code)
    0	    66	 22384	window [3] (Issue Reporter)
    0	    64	 23444	fileWatcher [1]
Connection to 'SSH: 192.168.3.30' could not be established  The VS Code Server failed to start
```

</details>
<details>
<summary>Workspace Info</summary>

```

Connection to 'SSH: 192.168.3.30' could not be established  The VS Code Server failed to start;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019bcf:30953938
3ef8e399:30949928

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/203967#issuecomment-1923440629
