### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by Matilio** [microsoft/vscode#204016]
I updated to version: 1.86.0 (Universal) MAC and now I can't connect to ssh

**Comment by sagarbhatt0904** [comment]
I have the same issue. Downgraded to previous version and its working now

**Comment by git-nico** [comment]
Same issue here.  Normally use ssh to Synology NAS. This was working fine in version 1.85.2. I can no longer connect with version1.86.0

**Comment by WinCPP** [comment]
@Matilio @sagarbhatt0904 @git-nico Looks like this is same as https://github.com/microsoft/vscode/issues/203967?

**Comment by git-nico** [comment]
@Matilio @sagarbhatt0904 @lszomoru @WinCPP 
touch /tmp/vscode-skip-server-requirements-check on the remote server did the trick. I could use version 1.86 to ssh into remote machine.

**Comment by lszomoru** [comment]
closing as duplicate of https://github.com/microsoft/vscode/issues/203967#issuecomment-1923440629
