### ISSUE TITLE
Gitignored symlinks break the grey out feature of the file explorer

### ISSUE THREAD

**Issue by foreignmeloman** [microsoft/vscode#204080]
Does this issue occur when all extensions are disabled?: Yes

Environment:

> Version: 1.87.0-insider
> Commit: 2af613979f646fc4dcebfeaedc7d14f138c7b072
> Date: 2024-02-01T23:52:47.063Z
> Electron: 27.2.3
> ElectronBuildId: 26495564
> Chromium: 118.0.5993.159
> Node.js: 18.17.1
> V8: 11.8.172.18-electron.0
> OS: Linux x64 6.5.0-15-generic snap (Ubuntu 22.04)

Steps to Reproduce:

1. Create a symlink to a file
2. Add the symlink to .gitignore
3. Restart the IDE

Screenshots illustrating the issue:
Here the grey out feature is broken when `thycotic.py` and `jiraScript.py` files are symlinks:
![image](https://github.com/microsoft/vscode/assets/11769352/e42e1eaf-de05-4c08-b3ef-58d6614d6055)
When replaced with actual files the grey out works fine:
![image](https://github.com/microsoft/vscode/assets/11769352/c1780b8c-0b75-4288-8f76-cef07e4f4b64)

**Comment by gioboa** [comment]
I followed the steps in my environment and it's working fine for me.

> Version: 1.88.0-insider
> Commit: 8cfe998a17786ace2a19079feab8b24f42ecc896
> Date: 2024-03-27T17:29:47.315Z
> Electron: 28.2.8
> ElectronBuildId: 27744544
> Chromium: 120.0.6099.291
> Node.js: 18.18.2
> V8: 12.0.267.19-electron.0
> OS: Linux x64 6.5.0-26-generic snap

I think this can be closed.

**Comment by foreignmeloman** [comment]
@gioboa what was your environment?

**Comment by gioboa** [comment]
Linux Ubuntu

Version: 1.88.0-insider
Commit: 8cfe998
Date: 2024-03-27T17:29:47.315Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-26-generic snap

**Comment by foreignmeloman** [comment]
@gioboa indeed in v1.88 the issue is gone, probably was fixed indirectly.
