### ISSUE TITLE
Zoom level indicator always reset to level 1

### ISSUE THREAD

**Issue by chemacortes** [microsoft/vscode#204019]
Type: <b>Bug</b>

I use a window.zoomLevel of 1.2. When I zoom the window, the zoom level indicator is shown at the status bar. The reset control does not reset to the custom window.zoomlevel, always reset to level1. The indicator doesn't disappear and must to reconfig window.zoomLevel to change zoom to 1.2 again.

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:27:46.147Z)
OS version: Linux x64 6.5.0-15-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 1|
|Memory (System)|15.48GB (10.53GB free)|
|Process Argv|--unity-launch --crash-reporter-id bc0905be-d7ae-47a1-afa7-60625736e383|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
scaladex-search|bac|0.3.4
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.21.0
markdown-preview-github-styles|bie|2.0.3
markdown-yaml-preamble|bie|0.1.0
vscode-clock|Com|0.0.1
vscode-markdownlint|Dav|0.54.0
markdown-extended|jeb|1.1.3
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.18
debugpy|ms-|2024.0.0
jupyter|ms-|2024.1.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-powertoys|ms-|0.1.0
vscode-jupyter-slideshow|ms-|0.1.5
hexeditor|ms-|1.9.12
vscode-versionlens|pfl|1.9.2
profile-status|rob|0.8.1
scala|sca|0.5.7
scala-snippets|sca|0.1.0
metals|sca|1.27.0
justfile|scl|2.1.0
even-better-toml|tam|0.19.2
vscode-icons|vsc|12.7.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>

**Comment by bpasero** [comment]
Great catch 👍
