### ISSUE TITLE
error using remote - SSH after update to 1.86.0

### ISSUE THREAD

**Issue by GeofferyGeng** [microsoft/vscode#204054]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.86.0
- OS Version: win10 & centos6.9

Steps to Reproduce:

1. error using remote - SSH after update to  1.86.0
2. it noted that :https://aka.ms/vscode-remote/linux-prerequisites

**Comment by liuhuoz** [comment]
see here
https://github.com/microsoft/vscode/issues/203967
And the current method is downgrading local vscode into 1.52.2

**Comment by Hua-jiu** [comment]
https://github.com/microsoft/vscode/issues/203967#issuecomment-1921540242
let's go back to 1.85.2 and continue your work

**Comment by blues911** [comment]
Return
- VSCode to 1.85.2
- Remote SSH to 0.105.0

and disable updates

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/203375
