### ISSUE TITLE
Markdown preview disappeared

### ISSUE THREAD

**Issue by beccalee123** [microsoft/vscode#204001]
Type: <b>Bug</b>

Upon latest update the markdown preview disappeared from VSCode. Have confirmed that some (but not all) of my colleagues are having the same issue. In addition to the button no longer being visible, the commands to open the markdown preview no longer work.

VS Code version: Code 1.86.0 (Universal) (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:15.765Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|64.00GB (21.44GB free)|
|Process Argv|. --crash-reporter-id 6e119a64-c455-49ce-9869-8d6a97da5efd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipfs|arc|3.0.0
vscode-markdownlint|Dav|0.54.0
vscode-eslint|dba|2.4.4
gitlens|eam|14.7.0
prettier-vscode|esb|10.1.0
vscode-pull-request-github|Git|0.80.0
vscode-graphql|Gra|0.9.1
vscode-graphql-syntax|Gra|1.3.1
vscode-styled-components|jpo|1.7.0
remote-containers|ms-|0.338.1
vsliveshare|ms-|1.0.5905
vsliveshare-pack|ms-|0.4.0
indent-rainbow|ode|8.3.1
vscode-graphql|ors|0.3.18
indenticator|Sir|0.7.0
code-spell-checker|str|3.0.1
vscode-pets|ton|1.25.1
vscode-mdx|uni|1.7.0
vscode-icons|vsc|12.7.0
vscode-mdx-preview|xyc|0.3.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by beccalee123** [comment]
It does- just disabled all of them and reloaded the workspace. Still not seeing the markdown preview or able to open it via keyboard commands

**Comment by mjbvz** [comment]
What is the language mode of the file? This is shown in the status bar

![Image](https://github.com/microsoft/vscode/assets/12821956/e11e025a-1f4a-4dba-8636-cfb8242dc346)


Also did you perhaps disable the built-in markdown extension? You can search `@builtin markdown` in the extensions view to check

**Comment by beccalee123** [comment]
Oooh it's Markdown React. When I changed it to Markdown I was able to get the preview again, but I used to be able to get a preview for both. Doesn't look like the built-in extensions were disabled.

**Comment by mjbvz** [comment]
Thanks for checking. I don't think anything has changed on our side. Instead I suggest you check with the Markdown MDX extensions you have installed since I believe they were adding these buttons

**Comment by beccalee123** [comment]
Ok gotcha- thanks for your help looking into this!

**Comment by AllenYCLau** [comment]
The issue still there for me...
The language was selected markdown and the built-in markdown extensions were all disable then re-enabled
![Screenshot 2024-02-01 221149](https://github.com/microsoft/vscode/assets/126450472/2fd13c89-5ea5-4e35-b5d5-cb454c061c4c)

But all the markdown cells simply won't show 
![Screenshot 2024-02-01 220913](https://github.com/microsoft/vscode/assets/126450472/b1be22e1-c921-4807-8d41-1a0b91aa9422)
