### ISSUE TITLE
[VSC-Web] "window.zoomPerWindow" not applying?

### ISSUE THREAD

**Issue by MasterInQuestion** [microsoft/vscode#204026]
https://code.visualstudio.com/updates/v1_86#_configure-zoom-levels-per-window

    [https://github<i>.</i>com/microsoft/vscode/issues/185836#issuecomment-1875104406](https://github.com/microsoft/vscode/issues/185836#issuecomment-1875104406)
<.>    No "Zoom" related entries.

&#x2D;---

Version: 1.86.0
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
User Agent: Mozilla/5.0 (Linux; rv:999) Gecko/20100101 Firefox/999
Embedder: vscode.dev

**Comment by bpasero** [comment]
Yes, we cannot overtake the browser zoom in web.

**Comment by MasterInQuestion** [comment]
Well... I noted there are similar commands:
    |&#x2A;| "Increase Editor Font Size" ("editor.action.fontZoomIn")
    |&#x2A;| "Decrease Editor Font Size" ("editor.action.fontZoomOut")
    |&#x2A;| "Reset Editor Font Size" ("editor.action.fontZoomReset")

    Sure they are supposed to exist independently?
