### ISSUE TITLE
Markdown cells missing

### ISSUE THREAD

**Issue by luchungi** [microsoft/vscode#204057]
Type: <b>Bug</b>

All markdown cells of Jupyter notebooks are not displayed after latest update.
The presence of the markdown cells are still detected under OUTLINE tab.

VS Code version: Code - Insiders 1.87.0-insider (442c133fe92b5e2606c8242caae4e68938faccc7, 2024-02-01T09:49:33.086Z)
OS version: Windows_NT x64 10.0.22635
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600 6-Core Processor               (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (48.67GB free)|
|Process Argv|--crash-reporter-id 8c1f125c-7b85-4121-8c37-3f0f54919dfb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600 6-Core Processor (12 x 3500)|
|Memory (System)|54.93GB (52.30GB free)|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.16.9
vscode-peacock|joh|4.2.2
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.339.0
remote-ssh|ms-|0.108.2024012417
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
remote-explorer|ms-|0.5.2024011009
binary-plist|dni|0.11.3
githistory|don|0.6.20
gitlens|eam|2024.2.104
themeswitch|Foo|1.0.5
copilot|Git|1.156.686
copilot-chat|Git|0.13.2024020102
vscode-pull-request-github|Git|0.80.0
latex-workshop|Jam|9.18.0
rainbow-csv|mec|3.11.0
vscode-docker|ms-|1.28.0
vscode-dotnet-runtime|ms-|2.0.1
debugpy|ms-|2024.0.0
isort|ms-|2023.10.1
pylint|ms-|2023.11.13481007
python|ms-|2024.0.0
vscode-pylance|ms-|2023.12.1
datawrangler|ms-|0.25.2
jupyter|ms-|2024.1.2024012502
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
tensorboard|ms-|2023.10.1002992421
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.16.32
cpptools|ms-|1.19.2
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.8.22
cmake|twx|0.0.17
vscode-colorize-plus|YuT|0.12.13

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vscod805:30301674
vsaa593cf:30376535
py29gd2263:30784851
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
d34g3935:30953408
b1063948:30943794
fegfb526:30952798
7j2b6412:30951517
e3gdj431:30946825
ccp2r3:30950906

```

</details>

**Comment by rebornix** [comment]
Thanks for the report, it should be fixed now in latest Insiders.
