### ISSUE TITLE
python run and debug not working

### ISSUE THREAD

**Issue by Defcon404** [microsoft/vscode#204176]
Type: <b>Bug</b>

after the recent update  2 feb 2024, python run and debud is not working.
my python interpreter, ide, modules, packages are all up to date. but after the recent update, i am unable to preform run and debug. when i click the "run and debug" button, nothing is happening. even after computer restart.
please fix

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (11.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.1
autopep8|ms-|2023.8.0
debugpy|ms-|2024.0.0
python|ms-|2024.0.0
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2024.1.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
pdf|tom|1.2.2
material-theme|zhu|3.16.2

</details>

**Comment by Merculous** [comment]
Same here. My project was working just fine last night. Now debugging doesn't work. When I try to view variables in the debugger, when I click on them, they just loop indefinitely.

**Comment by lbriones-horizon-next** [comment]
Same here

**Comment by Merculous** [comment]
Update: I finally let my debugger just sit. It took 255 seconds just to wait for the debugger to finally give me variables, when it should be less than 5 seconds.

**Comment by roblourens** [comment]
Please file this on the Python extension repo, thanks
