### ISSUE TITLE
Intellisense for javascript file has too many .ts suggestions.

### ISSUE THREAD

**Issue by heeefei** [Microsoft/vscode#20414]
- VSCode Version: 1.9.1
- OS Version: macOS

Steps to Reproduce:

1.   open a javascript file
2.  input something

example
![image](https://cloud.githubusercontent.com/assets/3992113/22826476/908aaaee-efcd-11e6-897c-02a8a84ebe16.png)

when I input 'if', there is other .ts suggestion. what I want is only .js snipets. Is there any way to close the .ts suggestions when I edit a .js file?

**Comment by mjbvz** [comment]
Can you please explain what the `.ts` suggestions here are? It may help if you explain the expected behavior and how that differs from the actual behavior

Thanks

**Comment by heeefei** [comment]
sorry for that I did't explain my question clearly. what I say .ts suggestions means that when I edit a .js file. like this:
![image](https://cloud.githubusercontent.com/assets/3992113/22853240/f6006576-f08b-11e6-9981-c8044f497511.png)
When I input `if`, there are many suggestions.  The first two items are interface, and the third one is actually the keyword `if`. there are too many suggestions that I did't want. Is there any way to close the interface suggestions and just retain the .javascript keyword and snippet. @mjbvz

**Comment by mjbvz** [comment]
Those are all DOM types. To get rid of those suggestions, create a `jsconfig.json` with the contents:

```json
{
    "compilerOptions": {
        "lib": [
            "es2015"
        ]
    }
}
```

This means that only suggestions for core es2015 types will be shown. You can disable even these by changing it to `"lib": []`

**Comment by heeefei** [comment]
It works, thank you! @mjbvz
