### ISSUE TITLE
Always show "Open changes with previous revision" button

### ISSUE THREAD

**Issue by ilyakonrad** [microsoft/vscode#204115]
Some time ago I discovered this beautiful button "Open changes with previous revision" which immensely improved my process of understanding how code has changed over time.

<img width="319" alt="image" src="https://github.com/microsoft/vscode/assets/25200186/c3a926e6-e2f0-4d76-8df6-8c0024e038d3">

Later this button became hidden once you go back in history two steps.
So e. g. if you want to see what was done in your file 5 commits ago, you'll have to click on the button, then click on it again, then go to "More Actions..." menu to find "Open changes with previous revision" and repeat the last bit three times.
And the keyboard shortcut to do that doesn't work. Kinda sucks.

<img width="267" alt="image" src="https://github.com/microsoft/vscode/assets/25200186/876b4467-e1ae-4c09-afec-1e849f9ec2af">
<img width="328" alt="image" src="https://github.com/microsoft/vscode/assets/25200186/3c9080b8-3ca6-43b4-9adb-b4e432803a2c">

<br/>
<br/>

While writing this, I found out that the reason of the button being hidden is because there are too many other "quick actions" buttons there. If you uncheck some of them in the right click menu, the hidden buttons will appear again.

<img width="343" alt="image" src="https://github.com/microsoft/vscode/assets/25200186/29e5fba7-ee71-4f07-a847-6d43bc1d42f1">

So, essentially, I've fixed my issue, but I still think it's not intuitive that an action can be "checked" **and** not visible because VS Code decides that there's not enough space for it.
Also I believe "Open changes with previous/next revision" buttons are more usable than some of the others, I'd really expect them to be visible at all times by default.

**Comment by lszomoru** [comment]
@ilyakonrad, this action is being contributed by the GitLens extension so I would recommend that you file an issue in the extensions repository - https://github.com/gitkraken/vscode-gitlens/issues. Thank you!

**Comment by ilyakonrad** [comment]
They say it's VS Code behavior though.
https://github.com/gitkraken/vscode-gitlens/issues/2956

**Comment by lszomoru** [comment]
Adding @jrieken, to chime in on whether there is any way for users/extension authors to control when a menu action is being hidden.

**Comment by dennemark** [comment]
I am also running into this issue. One great improvement would be already, if the icon that is moved into the dropdown would not only be shown as text, but also with the icon. Otherwise it is hard to make the connection between icon in the bar and text in dropdown.
