### ISSUE TITLE
Search: Convert hardcoded tree actions to configurable commands

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#20418]
When you take a look at the controller in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/searchResultsView.ts#L222 there are a bunch of hardcoded keybindings associated for certain actions. We should avoid this and rather introduce commands that the user can associate keybindings with.

As part of https://github.com/Microsoft/vscode/issues/11517 I introduced a new service `IListService` that every tree is registering to. This service tracks focus of the tree and enables a `listFocus` context key whenever the tree has focus. As part of the `register` method you can pass over additional context keys that you want to have set for your domain (e.g. `searchFocus`). E.g. the "Open Editors View" is doing that [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/openEditorsView.ts#L125). 

I suggest to write new commands that are enabled in the context for the domain (e.g. `searchFocus`) and remove the hardcoded keybinding handling in the tree controller. When doing so I would pick short and descriptive command Ids (e.g. `search.something` over `workbench.action.search.something`).

If you need to overwrite a certain keybinding that already exists from the list service (e.g. <kbd>Space</kbd> should do something else than toggling), you can give your command a higher weight (see for example how the explorer is [overriding](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileActions.contribution.ts#L242) <kbd>Enter</kbd> to do something else on macOS).

**Comment by sandy081** [comment]
@roblourens FYI, Hope I am not duplicating the effort here :)
