### ISSUE TITLE
Allow better control over Windows font antialising

### ISSUE THREAD

**Issue by Frangible** [Microsoft/vscode#20417]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none

---

Normally, text rendering on Windows in VSCode uses subpixel antialiasing, where the display is assumed to be a TN LCD panel with a horizontal R-G-B subpixel arrangement.

Unfortunately, on an IPS or VA panel, this appears to produce chroma bleed and does not give the same benefit as with a TN panel (eg, the text does not appear sharper), as the subpixel structure is fundamentally different.  In my experience, for IPS and VA panels, grayscale antialiasing produces better results when rendering text.

I don't see a setting in VSCode to configure this, and while the Windows 10 Control Panel -> Display -> Cleartype setting can be changed to grayscale antialiasing, this was ignored for me in VSCode.  (Cleartype setting is GDI only?)
  
* In Sublime Text (Win10), the setting `font_options` can be set to `no_antialias`, `gray_antialias`, and `subpixel_antialias`.  
* In Chrome (Win10), the flag `chrome://flags/#lcd-text-aa` can be set to `disabled` to enable grayscale font antialiasing.  
* [This page](http://peter.sh/experiments/chromium-command-line-switches/) suggests `--disable-lcd-text` as a command-line argument in Chromium, perhaps similar to the Chrome flag.  Unfortunately, it had no effect with VSCode.  

Please consider adding a similar preference to VSCode if possible.  Thanks!

**Comment by Frangible** [comment]
More info:

* I found that disabling ClearType entirely did remove subpixel antialiasing.  However, the grayscale antialiasing provided by this mode did not appear to be as good as Cleartype being on and tuned to grayscale antialiasing.
* I looked at Electron and Atom's support for Chromium command-line arguments affecting this, but couldn't make any determinations.
* I found [PR 17401](https://github.com/Microsoft/vscode/pull/17041) discussing adding "-webkit-font-smoothing: antialiased;" to the editor CSS for HDPI displays, with some preliminary support for exposing the antialiasing mode as a preference.  I edited the minified production CSS to include this, but it had no effect.

[Composite image of the above](http://i.imgur.com/Z3aZe0J.png)

**Comment by Ciantic** [comment]
I also would like to have --disable-lcd-text flag or setting. It's available in the Chrome.

I use it in Chrome because I have 4K screens and the fonts are much better without the color fringes.

**Comment by Ciantic** [comment]
@Frangible can you try this:

I suspect this enabled the grayscale antialising on VS Code for me:
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Avalon.Graphics]

[HKEY_CURRENT_USER\Software\Microsoft\Avalon.Graphics\DISPLAY1]
"ClearTypeLevel"=dword:00000000
"EnhancedContrastLevel"=dword:00000032
"GrayscaleEnhancedContrastLevel"=dword:00000064
"TextContrastLevel"=dword:00000000
"PixelStructure"=dword:00000000

[HKEY_CURRENT_USER\Software\Microsoft\Avalon.Graphics\DISPLAY2]
"ClearTypeLevel"=dword:00000000
"EnhancedContrastLevel"=dword:00000032
"GrayscaleEnhancedContrastLevel"=dword:00000064
"TextContrastLevel"=dword:00000000
"PixelStructure"=dword:00000000
```

Even though these settings set the cleartype settings to grayscale, they won't affect Windows Explorer or Context Menus, they are rendered in clear type regardless of what you set in clear type settings.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.

**Comment by kurtextrem** [comment]
@alexandrudima If you refer to issues outside of a project, it would be a great idea to either link to such issues so we can follow, or to create an issue there.

**Comment by alexandrudima** [comment]
@kurtextrem I agree. Please create an issue at https://bugs.chromium.org/p/chromium/issues/list and add the link to it here.

**Comment by kurtextrem** [comment]
@alexandrudima I'd do, but I don't really know what the upstream issue is. If you explain me what you suspect to be the problem and the expected fix I can create one.

**Comment by alexandrudima** [comment]
From what I know, when working with a DirectText surface in Windows, unless explicitly overwritten via flags, the text will be rendered to respect the [ClearType settings](https://www.howtogeek.com/howto/28790/tweak-cleartype-in-windows-7/). Chrome uses a lot of abstraction on top of or complimentary to DirectText. 

A Chromium engineer that works on this Chromium subsystem will probably know a lot more than me.

Also, please note that I do not have any superpowers or direct hot-line to the Chromium project. I use the very same public search tools that everybody can use.
