### ISSUE TITLE
Sometimes code color did not render properly, especially on HTML with .php extension file

### ISSUE THREAD

**Issue by gensart-ai** [microsoft/vscode#204140]
Type: <b>Bug</b>

After I create some HTML tags.
But if I do scroll, it disappear.

Some color is flickering if I have any changes on that line.

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.22GB free)|
|Process Argv|--crash-reporter-id 79e7dc04-30d1-43c8-9f1d-96b0d3eed6cc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
bootstrap5-vscode|Anb|0.4.4
vscode-custom-css|be5|7.2.1
vscode-intelephense-client|bme|1.10.2
vscode-animations|Bra|2.0.1
node-snippets|chr|1.3.3
npm-intellisense|chr|1.4.5
codeium|Cod|1.7.13
vscode-eslint|dba|2.4.4
javascript-ejs-support|Dig|1.3.3
jquerysnippets|don|0.0.1
el-vsc-product-icon-theme|ElA|0.1.8
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
vscode-env|Iro|0.1.0
vs-color-picker|lih|1.0.0
font-awesome-5-codes-html|mrd|1.0.1
autopep8|ms-|2023.8.0
debugpy|ms-|2024.0.0
python|ms-|2024.0.0
vscode-pylance|ms-|2024.1.104
jupyter|ms-|2024.1.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
remote-explorer|ms-|0.4.1
vscode-typescript-next|ms-|5.4.20240201
phpstorm-snippets|phi|1.1.2
material-icon-theme|PKi|4.33.0
format-html-in-php|rif|1.7.0
vscode-autohide|sir|1.0.8
prettier-plus|svi|4.2.2
bootstrap4-vscode|the|6.1.0
vscode-icons|vsc|12.7.0
php-pack|xde|1.0.3
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>

**Comment by aeschli** [comment]
Does this reproduce if you run with Extensions disabled? 
Run command: `Developer: Reload with Extensions Disabled` 

If it still reproduces, can you add a screen capture that shows the flickering?

**Comment by gensart-ai** [comment]
It may seems weird, but after I do restart my OS yesterday, the blink never appear again.

Sorry for it.
