### ISSUE TITLE
uv_os_get_passwd returned ENOENT

### ISSUE THREAD

**Issue by helman44** [microsoft/vscode#204178]
Does this issue occur when all extensions are disabled?: Yes/No
N/A

- VS Code Version: 1.86.0
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Open VSCode 
2. Attempt to connect to an existing or new ssh config using Remote Development Extension
3. Pop up below happens:
4. 'A system error occurred (A system error ocurred: uv_os_get_passwd returned ENOENT (no such file or directory))

SOLUTION:
Drop back to VS Code Version: 1.85.2

![Screenshot from 2024-02-02 12-38-57](https://github.com/microsoft/vscode/assets/54872834/cb983e1f-a4e5-4a39-8cd1-b2e2185bad94)

**Comment by polybius-gh** [comment]
Same issue for me running on Windows 11 and remoting into Ubuntu SSH servers.  Uninstalled 1.86 and installed 1.85, issue resolved.

**Comment by kotorkovsciy** [comment]
Also on Windows 10, rolling back to 1.85.2 helped

**Comment by polybius-gh** [comment]
Also recommend disabling auto-updates until 1.86 is fixed.

**Comment by wasserman** [comment]
Same here.  Windows VSCode remote connecting via ssh to CentOS 7.9.2009.
After upgrading automatically to v1.86.0 my remote ssh VSCode attempts return tons of messages in the output tab like this:
```
> 
[22:04:05.380] > Waiting for server log...
> 
[22:04:05.414] > Waiting for server log...
> 
[22:04:05.457] > Waiting for server log...
> 
[22:04:05.467] > Waiting for server log...
> 
[22:04:05.510] > Waiting for server log...
```

This notification dialog also appears:
![image](https://github.com/microsoft/vscode/assets/6733448/1c0a452e-b677-4201-b7fa-49e8d2b02784)

The link takes me here: https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites
I was surprised to see that CentOS 7 isn't on the list. I'm on kernel is 3.10, glibc 2.17, and libstdc++ 4.8.5.  I'm working with Python on this particular host.

It took some time of me trying to determine if I needed to update some package on my Linux server due to some new requirement, but I ultimately rolled back and disabled auto-updates.  Of course it updated again while I was disabling auto-updates so I ended up having to rollback a second time.

I've been happily using VSCode for years, often via remote SSH, and have had few issues.  Keep up the great work!

**Comment by xzhai12** [comment]
Same here and all my colleagues in the team updated 1.86 got this issue. Local Mac + server CentOS.
Rolling back to 1.85 solved it. 
I don't want to be mean but it would be really great if more testing can be done before major releasing...

**Comment by hozdenoren** [comment]
Same here, the whole team had to roll back to 1.85 and disable auto updates.

**Comment by hoho51** [comment]
same issue, want the problem solved soon

**Comment by Bronek** [comment]
Same here, running snap in Debian

**Comment by npurson** [comment]
> Same here. Windows VSCode remote connecting via ssh to CentOS 7.9.2009. After upgrading automatically to v1.86.0 my remote ssh VSCode attempts return tons of messages in the output tab like this:
> 
> ```
> > 
> [22:04:05.380] > Waiting for server log...
> > 
> [22:04:05.414] > Waiting for server log...
> > 
> [22:04:05.457] > Waiting for server log...
> > 
> [22:04:05.467] > Waiting for server log...
> > 
> [22:04:05.510] > Waiting for server log...
> ```
> 
> This notification dialog also appears: ![image](https://private-user-images.githubusercontent.com/6733448/301983846-1c0a452e-b677-4201-b7fa-49e8d2b02784.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzk3NTAsIm5iZiI6MTcwNzAzOTQ1MCwicGF0aCI6Ii82NzMzNDQ4LzMwMTk4Mzg0Ni0xYzBhNDUyZS1iNjc3LTQyMDEtYjdmYS00OWU4ZDJiMDI3ODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDRUMDkzNzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjNmZjRhYzhlZTMzNmYxZjZlYWEzYjdlM2ViNzc0NzZhYzhlOTkyM2ViM2ZkODU3OWVkNjY2NWI5MDY1YmIyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7vUtnUaPwMfx_hyGitL93SFR6YRNZ1yi_LyJZET8P58)
> 
> The link takes me here: https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites I was surprised to see that CentOS 7 isn't on the list. I'm on kernel is 3.10, glibc 2.17, and libstdc++ 4.8.5. I'm working with Python on this particular host.
> 
> It took some time of me trying to determine if I needed to update some package on my Linux server due to some new requirement, but I ultimately rolled back and disabled auto-updates. Of course it updated again while I was disabling auto-updates so I ended up having to rollback a second time.
> 
> I've been happily using VSCode for years, often via remote SSH, and have had few issues. Keep up the great work!

Check the workaround here: https://github.com/npurson/vscode-server-toolchain-workaround.

**Comment by Bronek** [comment]
I think it's not only version checks; the error I'm seeing is `uv_os_get_passwd returned ENOENT` (not the prerequisites one). My remote host is running Debian 12, on aarch64

```
% lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
% uname -r
6.1.0-17-arm64
% dpkg -s libglib2.0-0 | grep Version
Version: 2.74.6-2
% dpkg -s libstdc++6 | grep Version  
Version: 12.2.0-14
```

**Comment by wasserman** [comment]
I'm currently okay since the rollback and disabling automatic updates.  But I'm now in a situation where I will not know if or when it is safe to upgrade.  In 6 months I may want some shiny new feature and forget that this happened and risk running into this problem again.  Or maybe the remote hosts will be patched and I would like an easy way re-validate if it is safe to upgrade.

Could you have some dependency version checking in the next version that would recognize the problem and tell the user that they will need to downgrade to 1.85.2?  Maybe even release a 1.85.3 to allow a user to verify if a host is compatible for 1.86+ based on a quick survey it can run when next connecting?

Please note that RHEL 7 is still supported by the vendor through [June 2024](https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/rhel-7-end-of-maintenance).

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/203375

**Comment by xzhai12** [comment]
so how home this is closed as **completed**? 
VSCode does not check when connecting to a server and throws unclear error message, yet now the team thinks this is fixed by an unofficial workaround?

**Comment by Bronek** [comment]
Looking at the workaround, I do not see how this could help fix errors like the one I am seeing, or indeed the one which started the issue. I do not have an old glibc (running Debian 12) and I guess neither does @helman44 (running Ubuntu 22.04). It is regrettable that the issue we are experiencing (ssh error `uv_os_get_passwd returned ENOENT`) got entangled with the glibc incompatibility error.

**Comment by roblourens** [comment]
Ah. Can someone share the Remote-SSH output channel log for the `uv_os_get_passwd` issue?

**Comment by juandavid212** [comment]
Same issue here, running Ubuntu 22.04.
The output channel of the Remote-SSH only shows:
[16:30:23.370] Picking SSH host
[16:55:13.019] Picking SSH host
[16:57:11.345] Picking SSH host
[16:57:18.067] Picking SSH host
[16:57:31.113] Picking SSH host
[17:01:28.266] Picking SSH host

When the error happens

**Comment by helman44** [comment]
Just to add my input as well, as @juandavid212 mentioned there is no visible log in my output channel either.

**Comment by deepak1556** [comment]
`uv_os_get_passwd` is only used by [os.userinfo](https://github.com/nodejs/node/blob/8a41d9b636be86350cd32847c3f89d327c4f6ff7/src/node_os.cc#L290) API in Node.js and I don't see any new usages of it in the SSH extension as well as server. Not sure where the call is being triggered from. @roblourens is it possible to get callstack for the error from logs ?

@helman44 @juandavid212 can you please share the remote extension version information.

**Comment by Bronek** [comment]
Not sure if this is relevant or not - I noticed that sometimes a new terminal appears within vscode which did not appear before, asking for a password to unlock my ssh keys. I have ssh-agent and correctly set `SSH_AUTH_SOCK` , so such prompt should not appear.

**Comment by juandavid212** [comment]
The problem was solved by removing VScode and installing it again from Debian files from the https://code.visualstudio.com/Download (before I installed it using 'sudo apt install code')
Remote - SSH extension and "Extension Pack" were installed using the "release" version.

**Comment by helman44** [comment]
I can confirm that @juandavid212's advice works.  I was installing via snap previously...

Just did:
sudo snap remove code
sudo dpkg -i code_deb_filename.deb
uninstalled and then reinstalled the prerelease version of the Remote Development extension

**Comment by Vraiment** [comment]
Can we reopen this issue? Switch to the deb version and installing a prerelease extension is not an ideal solution

**Comment by Roman2dot0** [comment]
This error  is related to use AD (or another domain system) with non exists user in /etc/passwd.
If add username in /etc/passwd (for test purposes) then ssh remote works as expected. 
OS - Ubuntu 23.10
VScode - snapd, 1.87.1

**Comment by mcallaghan-geotab** [comment]
Issue should be re-opened if a regression occurred here. Is the software assuming LOCAL user exists? What about systems that use LDAP or active directory? (pamd)

**Comment by Roman2dot0** [comment]
https://github.com/microsoft/vscode-remote-release/issues/9649

**Comment by MatteoFusconi** [comment]
I had this issue with vs code 1.88.1, installed with snap.
I resolved uninstalling it and reinstalling with debian

**Comment by rob-williams-mf** [comment]
Had the same error with vs code 1.89.1 with Amazon EC2 Ubuntu instance. Originally installed with Snap. Removed it and installed using dpkg and now it works. This was inside AWS WorkSpaces where users are authenticated using their managed Active Directory system.
