### ISSUE TITLE
Use CHERE_INVOKING for msys2 profile

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#204167]
See https://github.com/microsoft/vscode-docs/pull/7013

**Comment by Tyriar** [comment]
To verify install [msys2](https://www.msys2.org/), restart VS Code and verify the terminal profile is picked up. When it's launched, verify the current working directory is set to the workspace's folder.

**Comment by andreamah** [comment]
I installed msys2, then verified that it was a safe path in the "Select Default Profile" picker so that it would show up as a valid profile. However, it is not opening in the current workspace directory.

<img width="375" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/5867740c-7a44-45fe-9d54-e3842882c767">

**Comment by andreamah** [comment]
This also added a setting for `terminal.integrated.profiles.windows`, not sure if that's expected or whether things weren't added correctly.

<img width="421" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/c0d5df38-7d49-41af-aa62-f6722cd883f4">

**Comment by aiday-mar** [comment]
Hi @Tyriar we have branched off from main today, so I am pinging about the milestone on this issue. Would you like to make this issue a candidate or move it out to the `March 2024` milestone?

**Comment by amunger** [comment]
It is still setting up the home dir as the working directory 

```
REDMOND+aamunger@DESKTOP-DLTF0LJ MSYS ~
$ pwd
/home/aamunger
```

also setting the default looks the same as your screenshot

**Comment by amunger** [comment]
also, the terminal changes to this when python activates an env. (I think I remember you not wanting that to happen)
![image](https://github.com/microsoft/vscode/assets/2019016/33d2b48e-fc8e-4ab6-9dc9-f37decf998cc)

**Comment by Tyriar** [comment]
@amunger did you delete any old msys2 profile you had before verifying?

**Comment by Tyriar** [comment]
> also, the terminal changes to this when python activates an env. (I think I remember you not wanting that to happen)

This isn't up to us but the python extension. I think it's desirable if you have environment activation set up.

**Comment by amunger** [comment]
just by clearing it out from the `Terminal.integrated.profiles.windows` setting? yes - did that, restarted vscode, then checked again

**Comment by amunger** [comment]
It doesn't show up in this list until I set it as the default profile
![image](https://github.com/microsoft/vscode/assets/2019016/a8a09f60-f146-49c7-8627-4b4163709b1b)

**Comment by Tyriar** [comment]
@amunger that's expected as it's in an unsafe path, so we won't even present it as an option until the user OKs the path in default shell dialog.

**Comment by Tyriar** [comment]
@amunger so you do not see this when you say Yes to save the profile in the notification?

![image](https://github.com/microsoft/vscode/assets/2193314/95b083c3-77d5-40e4-861e-31ea9f08ac2c)

The warning is a bug which I'll fix but the `env` is there for me

**Comment by amunger** [comment]
I removed the profile from the setting, closed all vs code instances, reopened then:

![Recording 2024-03-26 at 13 37 41](https://github.com/microsoft/vscode/assets/2019016/0a9a3afc-b5a9-42eb-9de8-c993f52bf1eb)

**Comment by Tyriar** [comment]
Super weird 🤔

**Comment by Tyriar** [comment]
Figured it out! I was clicking the gear out of habit, @amunger you were clicking the item
