### ISSUE TITLE
Debug: Convert hardcoded tree actions to configurable commands

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#20419]
When you take a look at the controller in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L187 and the related subclasses, there are a bunch of hardcoded keybindings associated for certain actions. We should avoid this and rather introduce commands that the user can associate keybindings with.

As part of https://github.com/Microsoft/vscode/issues/11517 I introduced a new service `IListService` that every tree is registering to. This service tracks focus of the tree and enables a `listFocus` context key whenever the tree has focus. As part of the `register` method you can pass over additional context keys that you want to have set for your domain (e.g. `breakpointsFocus`). E.g. the "Open Editors View" is doing that [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/openEditorsView.ts#L125). 

I suggest to write new commands that are enabled in the context for the domain (e.g. `breakpointsFocus`) and remove the hardcoded keybinding handling in the tree controller. When doing so I would pick short and descriptive command Ids (e.g. `debug.something` over `workbench.action.debug.something`).

If you need to overwrite a certain keybinding that already exists from the list service (e.g. <kbd>Space</kbd> should do something else than toggling), you can give your command a higher weight (see for example how the explorer is [overriding](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileActions.contribution.ts#L242) <kbd>Enter</kbd> to do something else on macOS).

**Comment by isidorn** [comment]
I think this should have a test plan item. Thoughts?
I would create one specially for debug and you can create it for others or?

**Comment by bpasero** [comment]
@isidorn awesome! yes, I do agree this needs testing. I am about to write my test plan items, and I agree we can have one small test item specifically for debug.

**Comment by isidorn** [comment]
@bpasero ok I will write now one for debug

**Comment by isidorn** [comment]
@bpasero created https://github.com/Microsoft/vscode/issues/20434

**Comment by bpasero** [comment]
@isidorn cool, my monster test plan item for this is https://github.com/Microsoft/vscode/issues/20440

**Comment by isidorn** [comment]
😱
