### ISSUE TITLE
Search: clicking into result moves the entire result up by some pixels

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#20410]
Seems related to the change of showing the result count in the search viewlet:

![kapture 2017-02-10 at 12 42 29](https://cloud.githubusercontent.com/assets/900690/22825589/671765ce-ef8e-11e6-85cd-4fe565016dbb.gif)

**Comment by roblourens** [comment]
I fixed this exact issue originally - layout is tricky here. I can't repro it now... investigating

**Comment by roblourens** [comment]
I got it to repro, but only sometimes. CSS is weird. Pushed a change that hopefully will fix it, let me know if you see it again.
