### ISSUE TITLE
Possible QOL improvement when writing HTML

### ISSUE THREAD

**Issue by NijsTom** [Microsoft/vscode#20415]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-eslint|dbaeumer|1.2.2|
|terminal|formulahendry|0.0.5|
|beautify|HookyQR|0.7.3|
|vscode-icons|robertohuertasm|6.0.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. In an open HTML file, type any html tag without the outer brackets: e.g. table
2. Using the arrow keys, select the HTML snippet and press RETURN to insert it
3. Right now, "table" changed into `<table></table> `and the cursor is in between the two tags, this is a desired result
4. When pressing RETURN again to split the tag up over multiple rules, the cursor just goes to the current line's end instead without splitting the tag over multiple rules.

**Comment by jrieken** [comment]
That's controlled by the snippet

**Comment by aeschli** [comment]
The snippet is provided by [html-snippets](https://github.com/abusaidm/html-snippets) and is defined as:
```json
    "body": [
        "<table>",
        "\t$1",
        "</table>"
        ],
```

As $0 is not set (the final cursor position), the end of the snippet is assumed.
That's where you are navigating when pressing enter.

You need to file this issue against the extension that provides the snippet.
I'd suggest you to use emmet instead:
Press 'tab' after 'table'
