### ISSUE TITLE
Build error: `Uncaught TypeError: (0 , t.$c) is not a function`

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#204105]
Pipeline: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=254913&view=results
PR: https://github.com/microsoft/vscode/pull/204030
Revert: https://github.com/microsoft/vscode/pull/204087

The error is cryptic, but the signature reminds me of the transformation we apply at build time to localization functions  (first argument is a number). Thanks @rzhao271 for distilling it first:

```
Uncaught TypeError: (0 , t.$c) is not a function
```

With that suspicion, I reverted @mjbvz's change and the build is green again. Maybe this needs closer look from @TylerLeonhardt.

**Comment by TylerLeonhardt** [comment]
Closing this since the change was reverted.
