### ISSUE TITLE
dependsOn task just gets ignored if it does not exist

### ISSUE THREAD

**Issue by mortinger91** [microsoft/vscode#204147]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.0
- OS Version: Darwin arm64 23.3.0

Steps to Reproduce:

1. Create a task such as this one:
```
{
  "label":"my_task",
  "type":"shell",
  "dependsOrder": "sequence",
  "dependsOn": [
      "bogus_task"
  ],
  "command":"echo 123"
}
```
2. Save tasks.json file
3. Run my_task task

Even if bogus_task does not exist, no error will be thrown when running "my_task".

This is in contrast with `preLaunchTask` in a launch.json configuration. 
In that case a popup will appear saying that the task cannot be found: _Could not find the task 'bogus_task'._

This can be annoying, since renaming a task can break the depends list without any message or error

**Comment by meganrogge** [comment]
I have not seen other reports of this, so closing as I don't imagine getting to this soon
