### ISSUE TITLE
VSCode1.75.1 can not use Remote SSH extension

### ISSUE THREAD

**Issue by 18392152392** [microsoft/vscode#204228]
Does this issue occur when all extensions are disabled?: Yes/No

- OS Version: 

Steps to Reproduce:

1.  I download the VSCode packages，the version is 1.75.1
2.  I download the remote ssh extension then to connect, it failed
3. I use VSCode1.85.1, it is OK，can you help to resolve it?

![企业微信截图_17069492932670](https://github.com/microsoft/vscode/assets/52459655/3f928404-56aa-423a-b7f7-944b052c6883)

**Comment by gjsjohnmurray** [comment]
> 1. I download the VSCode packages，the version is 1.75.1

Which packages? Where did you download them fry om? That version number is about a year old. 

What OS are you using?

**Comment by 18392152392** [comment]
> > 1. I download the VSCode packages，the version is 1.75.1
> 
> Which packages? Where did you download them fry om? That version number is about a year old.
> 
> What OS are you using?

I use 1.75.1 on win10， I know 1.75.1 is old，but this question is serious, can you help to fix?

**Comment by roblourens** [comment]
Please try the latest version and let me know whether it's still an issue with that version
