### ISSUE TITLE
The TrueScript language service dieed unexpectedly 5 times in the last 5 minutes repeatedly shows

### ISSUE THREAD

**Issue by kmcknight1973** [Microsoft/vscode#20426]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions:

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|html-snippets|abusaidm|0.0.18|
|blueprintcss|coryrylan|0.0.4|
|jquerysnippets|donjayamanne|0.0.1|
|xml|DotJoshJohnson|1.7.0|
|beautify|HookyQR|0.7.3|
|rest-client|humao|0.10.2|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.9.0|
|debugger-for-chrome|msjsdiag|2.5.2|
|vscode-icons|robertohuertasm|7.2.0|
|Spell|seanmcbreen|0.9.1|
|language-stylus|sysoev|1.6.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1. Open Visual Studio Code from a mapped drive to SharePoint
2. As soon as the IDE opens I repeatedly get the above issue stated in the title.

**Comment by mjbvz** [comment]
The TypeScript network drive issue is being tracked by https://github.com/Microsoft/TypeScript/issues/13997

You can work around this issue by opening the network drive directly (not using a mapped drive). This should work in VSCode 1.9.1 using TypeScript 2.1.6
