### ISSUE TITLE
Show how to exit Zen mode when no editor is open

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#20428]
From Twitter:

> Shortcut to getting out of zend mode displayed when in zen mode an no files are open :-) Amazing Work --Tyler Canton

**Comment by datendenker** [comment]
+1 Please add a shortcut to get in / out of zen mode

**Comment by isidorn** [comment]
Shorcut istr `cltr + k  z`
Now we display chords in the menu so this should be more discoverable

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
