### ISSUE TITLE
Horizontal black line appears in sidebar

### ISSUE THREAD

**Issue by g0dzcsgo** [microsoft/vscode#204210]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.86.0 (user setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Have more than 100 folders, and a folder with alot of files inside it

What happens is it produces a black line separating it

Gif of the "black horizontal line"

![mcUhya4I0p](https://github.com/microsoft/vscode/assets/45868344/cec39f90-e923-49e9-b9a0-f20e14776a85)

**Comment by IllusionMH** [comment]
This is shadow from sticky folders
See https://code.visualstudio.com/updates/v1_86#_sticky-scroll-in-tree-views

**Comment by AxTrusov** [comment]
JFYI, even if it is disabled - the black line will remain on top of the explorer. Would be nice to hide it completely.

**Comment by benibenj** [comment]
@AxTrusov The shadow has always been there, it just moves further down when sticky scroll is active. If you turn off sticky scroll in the tree, you will have the same experience as there used to be.
