### ISSUE TITLE
Debug toolbar overlaps vscode window options on top left corner

### ISSUE THREAD

**Issue by shaunaksinha** [microsoft/vscode#204265]
Type: <b>Bug</b>

Hi,
After the recent update on vscode on macOS, I am seeing the debug toolbar stuck to the top left corner of the window when I debug a .java file. And I cannot move it.
The options overlap the window maximize, minimize and cancel buttons at the top left corner and are preventing me from clicking the options on the debug toolbar.

Please fix this.
Thank you.

VS Code version: Code 1.86.0 (Universal) (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:15.765Z)
OS version: Darwin x64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (14.91GB free)|
|Process Argv|--crash-reporter-id 2f34618c-bde3-495b-8330-b71b7bb7d99c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
live-sass|gle|6.1.2
intellij-idea-keybindings|k--|1.5.13
java|red|1.27.0
LiveServer|rit|5.7.9
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.56.0
vscode-java-dependency|vsc|0.23.4
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019bcf:30953938
3ef8e399:30949928
bg6jg535:30956215

```

</details>

**Comment by roblourens** [comment]
Could you share a screenshot? Maybe related to https://github.com/microsoft/vscode/issues/200506 but I wouldn't expect this on mac

**Comment by shaunaksinha** [comment]
It was working correctly (toolbar at the centre of the screen) just before the latest update.
Here is what it looks like now:

<img width="434" alt="vscode1" src="https://github.com/microsoft/vscode/assets/6349079/8cc17264-691a-4d02-9386-880cb6fcaac1">

**Comment by valerybugakov** [comment]
Same problem after the latest update.

**Comment by drpudding** [comment]
same

**Comment by anish-sana** [comment]
Same here. Using 1.86. This is incredible annoying to work with.

**Comment by bcking1** [comment]
I've run into the same thing on 1.86 although I was able to grab/move the debug toolbar to the center of my screen (_ever so gingerly_ trying to grab the dots without touching the close window, it felt like playing the game Operation). It has stayed there since, but it may not work for you and clearly was something that changed with the update
