### ISSUE TITLE
No operating system proof on update install

### ISSUE THREAD

**Issue by janstieler** [microsoft/vscode#204244]
I install the latest update and this is the result:
![Bildschirmfoto 2024-02-03 um 18 28 07](https://github.com/microsoft/vscode/assets/754880/98daa231-534c-45c0-919f-d882728c2a6d)
In my opinion its a serious bug if a software is not proof the OS version before it will install.

Mac OS High Sierra 10.13.6
Latest VSC Version

**Comment by rzhao271** [comment]
I believe this is out of scope and that we documented supported versions instead: https://code.visualstudio.com/Docs/supporting/requirements
