### ISSUE TITLE
createTerminal API help is outdated

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#20425]
vscode.windows.createTerminal has outdated API help, refers to v1.6 which is 3+mo old.

![image](https://cloud.githubusercontent.com/assets/1487073/22829605/a8d48356-efa3-11e6-8cb3-3e56e384dd0f.png)

**Comment by Tyriar** [comment]
You need to update your vscodeEngine in package.json and `npm run postinstall` (or install).
