### ISSUE TITLE
Debug should skip arguments assignment for step into action by default

### ISSUE THREAD

**Issue by scruel** [microsoft/vscode#204282]
![2024-02-04_18-27-24](https://github.com/microsoft/vscode/assets/16933298/371bbc58-405d-40ba-8489-40e9067b64a7)
I just want to step into the function or class, however for doing so, I will have to perform "step into" action by several times! Can you provide at least an option or set this as default, which can just let user jump into the function/class if there were no breakpoints by only one "step into" action? It's really a time-wasting behavior for users.

And do the same for array assignment.
Thanks.

**Comment by roblourens** [comment]
What language?
