### ISSUE TITLE
"can't resolve inmemory resource" error from problems pane

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#20423]
- VSCode Version: 

Version 1.10.0-insider (1.10.0-insider)  
ef3a8c9e2b642613635c1c53f70bcc86e123ad9a
2017-02-10T07:02:31.325Z

- OS Version:
MacOS

Steps to Reproduce:

1. install the docker extension: https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker
2. clone https://github.com/microsoft/vscode-docker
3. make a change to dockerfile.json
4. open git viewlet, click on dockerfile.json
5. open problems pane

Result:

![image](https://cloud.githubusercontent.com/assets/1487073/22828750/51b0304c-ef9f-11e6-8b6f-9933eb255923.png)

The docker extension think the file is a dockerfile because of the file name, that is why you get a bunch of errors. There are two issues that this then demonstrates:

* it says "23 inmemory://model/23" in the problems view, not sure what this means
* if i click on an error it throws on line 2036 of winjs.base.raw.js with the value "can't resolve inmemory resource"

![image](https://cloud.githubusercontent.com/assets/1487073/22828847/c25c25da-ef9f-11e6-8c81-36547e40acc5.png)

and in VS Code you get this error:

![image](https://cloud.githubusercontent.com/assets/1487073/22828862/cecfc998-ef9f-11e6-9104-2daea5282bd7.png)

**Comment by sandy081** [comment]
@chrisdias Is this happening with new or old Git viewlet?

**Comment by chrisdias** [comment]
@sandy081 this was with the old git viewlet

**Comment by sandy081** [comment]
@chrisdias May I know what kind of changes in the file produced errors? I am not seeing errors for changes I am doing. 

Can you also try with new Git viewlet (You can enable it from Command Pallette)?

**Comment by sandy081** [comment]
I think this is also related to #19627. @joaomoreno Correct?

**Comment by joaomoreno** [comment]
Well it's related, but it shouldn't blow up.

**Comment by sandy081** [comment]
Okay, then not sure who is creating this `inmemory:` resource? 
@chrisdias Probably can you help in reproducing this, as I said in my previous comments that , I cannot see errors with the changes I did. It would be helpful to know what changes in the file can cause errors?

**Comment by chrisdias** [comment]
I'm using the latest insiders on MacOS and I don't see a way to enable the new git viewlet from the command palette.  Regardless, I don't see the "inmemory://model" text anymore nor does it throw, but I am seeing #21526 which is fixed but not in Insiders yet.  So, I think this particular issue is closed.
