### ISSUE TITLE
LaTeX on vscode not working (error code 3221225781)

### ISSUE THREAD

**Issue by dstewtes** [microsoft/vscode#204298]
Hi all!

I set up vscode to edit LaTeX files for school work on my laptop last semester, and it works fine with zero issues, but I wanted to also edit LaTeX files on my new PC so I tried setting up vscode to do so on here but it isn't seeming to work and I don't know why. 

This is my first time asking for help on here so if I am missing any information, my apologies, but here we go with the information that I can think of that will be helpful.

First, I am using MikTeX, I am not exactly sure what version, but I downloaded it straight off of the MikTeX website in mid-january (sorry), and I have the LaTeX workshop and LaTeX utilities extensions on vscode.

I made a basic test document to see if it would work:
![code](https://github.com/microsoft/vscode/assets/158848029/efd51a60-9606-446e-b818-dbe86b75331e)

and I got a couple of pop-up errors:
![popup erros](https://github.com/microsoft/vscode/assets/158848029/181368f7-a6e3-4708-bf3f-a24d93ea3a8e)

and when I checked the output in the built in terminal thing at the bottom of vscode, I got these messages:
![console output](https://github.com/microsoft/vscode/assets/158848029/9858b3ce-f015-4aea-b1e5-fd27471c794e)

I also loaded up a couple of files that I wrote and compiled already on my laptop that I knew worked and they also gave me the same issues and everything.

I know I don't have a ton of information on what is wrong, but honestly I am quite new to a lot of this kind of stuff so I am truly at a loss as to what to do. Of course, if anyone needs more information, I will do the best I can to get the information, though I may also need help finding that information. If anyone has any help it would be greatly appreciated! 

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13600KF (20 x 3494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (17.90GB free)|
|Process Argv|--crash-reporter-id 65708dc1-8285-4d3e-9b3d-d827858a82ea|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|2.0.3
vscode-markdownlint|Dav|0.54.0
xml|Dot|2.5.1
code-runner|for|0.12.1
html-preview-vscode|geo|0.2.5
latex-workshop|Jam|9.18.0
vscode-latex|mat|1.3.0
debugpy|ms-|2024.0.0
isort|ms-|2023.10.1
python|ms-|2024.0.0
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2024.1.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.8.22
latex-formatter|nic|1.0.5
unicode-latex|oij|1.2.0
vscode-xml|red|0.26.1
docxreader|Sha|1.1.3
latex-utilities|tec|0.4.10
cmake|twx|0.0.17
better-mips|vas|0.2.1
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.6.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>

**Comment by mjbvz** [comment]
Please file this issue against your Latex extension
