### ISSUE TITLE
Crash with Error Code 5 after latest MacOS and VS Code update

### ISSUE THREAD

**Issue by guw** [microsoft/vscode#204267]
It's unclear yet what it produces. It does not seem to be tight to a specific action. Just idling or without focus and it crashed. 

Version: 1.86.0 (Universal)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:29:15.765Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0

I started to collect a dump as per the doc.
[vscode.zip](https://github.com/microsoft/vscode/files/14155315/vscode.zip)

<img width="279" alt="image" src="https://github.com/microsoft/vscode/assets/191472/8907e5c6-6921-4d68-bf33-9bb24794aa41">

**Comment by deepak1556** [comment]
Crash when workbench is running out of memory. Can you see if an extension is triggering the crash, from command palette run `Help: Start Extension Bisect`

**Comment by guw** [comment]
I am not seeing this anymore after executing the following command:
```
rm -rf ~/Library/Application\ Support/Code/Backups/*
```

I found this tip in one of the other open issues with similar reports.

**Comment by deepak1556** [comment]
I see, thanks for narrowing it down. If you see this issue again please report back without deleting backups folder, it would help us capture relevant traces.

/cc @bpasero seems there is a memory leak in backups code path.
