### ISSUE TITLE
 Ubuntu 18.04

### ISSUE THREAD

**Issue by avskr06** [microsoft/vscode#204241]
@Virtuald Can you please let me know the steps you to solve on Ubuntu 18.04. I am facing issue, kindly help out in this concern

**Comment by IllusionMH** [comment]
Please see https://code.visualstudio.com/updates/v1_86#_linux-minimum-requirements-update

**Comment by virtuald** [comment]
I rolled back to 1.85 for now. I'm sure they'll have a workaround soon.

**Comment by karthiknadig** [comment]
See https://code.visualstudio.com/updates/v1_86#_linux-minimum-requirements-update to find compatible version for Ubuntu 18.04.
