### ISSUE TITLE
IDE 代码块显示问题

### ISSUE THREAD

**Issue by lookwi** [Microsoft/vscode#20422]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|autofilename|JerryHong|0.1.3|
|vscode-theme-onedark|akamud|1.2.0|
|vscode-eslint|dbaeumer|1.2.5|
|code-file-nav|jakelucas|0.7.2|
|vscode-icons|robertohuertasm|7.2.0|
|react-redux-es6-snippets|timothymclane|2.0.2|
|vscode-react-native|vsmobile|0.2.5|

---

Steps to Reproduce:

1.
![image](https://cloud.githubusercontent.com/assets/18027182/22827685/17eb5622-efd4-11e6-92a2-19b634e5e768.png)

2.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/12473
