### ISSUE TITLE
Settings tree jitters after modifying a setting

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#204207]
Regression from https://github.com/microsoft/vscode/issues/68385

I haven't identified when the issue started happening again.

Repro steps:

1. Navigate to the Settings editor
2. Scroll down
3. Click on a checkbox or edit an inputbox on an unmodified setting, and wait for the setting to become modified, or click another nearby setting.
4. :bug: The Settings editor settings tree jumps.

**Comment by rzhao271** [comment]
I noticed the following:

- Not rendering the Settings indicator labels does not fix the issue
- After a setting value changes, `SettingsTree#setChildren` is called. Then, when `ListView#insertItemInDOM` is called during `ListView#_splice`, the setting tree elements are all smushed together. That behaviour is even more dramatic when a setting has a multi-line description.
- `ListView#insertItemInDOM` calls `ListView#updateItemInDOM`, which sets the top of the DOM node to an incorrect value. It looks like the value that is used is an estimate. I believe this estimation process is what causes the settings tree elements to shift upwards and smush together.

**Comment by chrisdias** [comment]
Note, the jittering is on the right side, not the tree on the left.

Regardless, this looks good to me. I could only repro in Stable on checkboxes, other types of settings didn't show the "jump".
