### ISSUE TITLE
Compile errors in sources

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#204328]
Steps to Reproduce:

1.  do a fresh check out of `vscode` repo
2. open it with a fresh VS Code insiders from a fresh user data dir
3. open a recently changed file such as `src/vs/base/browser/formattedTextRenderer.ts`

=> 🐛 there is a compile error in line `121`

We do seem to be setting the SDK to be the one from `node_modules`:

https://github.com/microsoft/vscode/blob/ec291c126878742ad640055ce604a58129cd088c/.vscode/settings.json#L75

But it is not being picked up it seems:

![image](https://github.com/microsoft/vscode/assets/900690/1d7b9e57-7134-4dd6-a2eb-36e8306c0d7b)

//cc @jrieken

**Comment by mjbvz** [comment]
Try switching to the workspace version of TS (5.4). There's a memento for which TS version is used in the workspace so just having the setting will not force VS Code to use the workspace version
