### ISSUE TITLE
Provide legacy server when remote requirements fail

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#204344]
* We will make legacy server the default server for this recovery release. Thus, each remote extension will download the legacy server. Remote extensions will NOT try to download the new server.
* The legacy server will check on what OS it is running. And if the OS does not support new GLIBC, it will tell the client this via a flag in the result of the `getEnvironment` call. The `getEnvironment` call is something that we already have, and we will just be adding one flag here.
* The VS Code client will respect the result of the `getEnvironment` call and based on that decide to show the Dialog and a Banner about "connecting to an OS that is unsupported by VS Code".

This is the approach we aim to take for the recovery release. It does not require any changes in the remote extensions and we believe is the lowest risk solution.
For the next stable release we plan to go away from the `getEnvironment` approach, and each remote extension will first download the new server, try to run it and if it fails fallback to the legacy. In this process the remote extension will signal to the client, so the client can show the banner and the dialog. Thus the user experience will be exactly the same in our recovery and next stable.

Work items:

- [x] make the legacy server the default server @deepak1556 
- [x] from legacy server return a flag in the `getEnvironment` based if the OS supports new GLIBC @deepak1556 
- [x] add an option to the banner, so that the `x` close button does not get shown @deepak1556 
- [x] based on the flag show a banner (that can not be closed) on the client side when connected to unsupported @deepak1556 
    - "You are connected to an OS that is unsupported by VS Code. [Learn More](https://code.visualstudio.com/docs/supporting/FAQ#_can-i-run-vs-code-on-older-linux-distributions)"
- [x] based on the flag show a dialog on the client side when about to connect to remote @deepak1556 
    - "You are about to connect to an OS that is unsupported by VS Code. [Allow] [Cancel] [Learn More] [checkbox Remember my Choice]" 
- [x] update docs https://code.visualstudio.com/docs/supporting/FAQ#_can-i-run-vs-code-on-older-linux-distributions @isidorn 
- [x] comment on GH issue on Monday 9pm CET @isidorn 
- [x] Include the changes as part of the recovery release
- [ ] Verify the issue is indeed fixed. Connect to an old OS and verify you get dialog + banner. Connect to a new OS and verify no dialog and no banner and all works well.
    - [ ] WSL @aeschli 
    - [ ] SSH @aeschli 
    - [ ] Codespaces @chrmarti 
    - [ ] Containers @chrmarti

**Comment by deepak1556** [comment]
Closing for verification.

**Comment by aiday-mar** [comment]
adding bug label so it appears in the list of issues to verify

**Comment by nikoshatzivag** [comment]
Why make the panel so that it can not be closed? We know that the OS is unsupported, what purpose does it serve having it permanently up there??

**Comment by mmazeika** [comment]
I agree. Could you please allow closing the banner on the client side?

**Comment by isidorn** [comment]
For the last two comments - dup of https://github.com/microsoft/vscode/issues/204728

**Comment by serialmetrics** [comment]
Help! this is super annoying if you are very type A, like me :)

**Comment by fulldecent** [comment]
This issue is related to a prior issue that seems to be redacted. https://github.com/microsoft/vscode/issues/203967

I believe that is the link (it may be another issue, this is now hidden from search) where Amazon engineers reported how this was a problem on EC2 and then VS Code product manager invited them on a phone call, and he put his email address in the comment.

I'm now writing a story on the virtues of "build in public" and citing this as a prime example of how things should work. But those comments all appear to be redacted, which is the extreme irony.

@isidorn Could you please advocate for that issue to be unredacted, for posterity sake?

**Comment by zyeric** [comment]
Still throws /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found.

My vscode version info is

Version: 1.88.0 (user setup)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:26:18.741Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by gjsjohnmurray** [comment]
@zyeric what remote OS version are you trying to connect with?

**Comment by pkazi** [comment]
Recently started facing this issue again - 
VS Code version - 
```
Version: 1.88.0 (Universal)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:28:18.899Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

Remote OS - 
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by deepak1556** [comment]
@pkazi @zyeric which remote extension are you using to connect ? Can you share the version information of the extension as well.

**Comment by pkazi** [comment]
> @pkazi @zyeric which remote extension are you using to connect ? Can you share the version information of the extension as well.

While checking remote ssh extension, found that I was using `v0.107.1`, and a new update was available (my auto update was disabled.)
I updated it to `v0.110.1` and now its working, able to connect to legacy linux.

**Comment by zyeric** [comment]
> @pkazi @zyeric which remote extension are you using to connect ? Can you share the version information of the extension as well.

thanks @pkazi  @deepak1556 , my case is similar to pkazi. I disable update when previous glibc error throws and forget to update the extensions.

I think it would be better you can inform user to update extensions automatically when this problem occurs.

many thanks
