### ISSUE TITLE
Code action sparkle shouldn't appear on an empty line in a search editor

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#204348]
Repro: 
1. Search for something using cmd+shift+f (ctrl+shift+f) 
2. Click on "open in editor" below the search-exclude input box
3. Put cursor on an empty line -> see sparkle (which when invoked - does nothing)

<img width="2560" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/6c2e7db2-52f7-4fd7-a5e5-31d31c2b7728">

**Comment by aeschli** [comment]
It's an editor that can be modified. So also code actions are applicable, including Copilot. Maybe you want to reformat the content using Copilot.

No changes planed
