### ISSUE TITLE
Search 'collapse' button no longer works

### ISSUE THREAD

**Issue by Dustin-Digitar** [microsoft/vscode#204316]
Type: <b>Bug</b>

1. Open the search side panel
2. Enter a search term
3. The search returns results
4. Try and click the 'collapse all' button at the top right of the search panel
5. Observe: nothing happens.  Also, the icon shows a '+'. It should show a '-' because the list is already expanded.

Before the latest update, this worked as expected.

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5825U with Radeon Graphics          (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|38.83GB (19.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
path-intellisense|chr|2.8.5
vscode-markdownlint|Dav|0.54.0
vscode-eslint|dba|2.4.4
githistory|don|0.6.20
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.15
copilot|Git|1.156.0
copilot-chat|Git|0.12.0
remotehub|Git|0.62.0
vscode-pull-request-github|Git|0.80.0
vscode-graphql-syntax|Gra|1.3.1
path-autocomplete|ion|1.25.0
vscode-env|Iro|0.1.0
rainbow-csv|mec|3.11.0
debugpy|ms-|2024.0.0
remote-wsl|ms-|0.86.0
remote-repositories|ms-|0.40.0
vsliveshare|ms-|1.0.5905
peggy-language|Peg|2.4.1
language-plan|und|0.0.1
excalidraw-editor|pom|3.7.1
quicktype|qui|12.0.46
vscode-yaml|red|1.14.0
vscode-paste-and-indent|Rub|0.0.8
partial-diff|ryu|1.4.3
multi-command|ryu|1.6.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.7.0
gitblame|wad|10.7.1
copy-hover-type|You|0.0.7

</details>

**Comment by Dustin-Digitar** [comment]
![image](https://github.com/microsoft/vscode/assets/113573618/b9370144-db8c-48e0-bf4e-ce57ba4ccf4d)

**Comment by Dustin-Digitar** [comment]
This is a pretty significant bug, because it makes the search near useless when there are a large number of files containing hits, or when there are many hits in a single file. It makes the list very tall to scroll through, and file names are harder to pick out.

**Comment by andreamah** [comment]
Hmm, I can't seem to repro this issue. What value do you have for `search.collapseResults`? Do you have any other search-related settings?

**Comment by ejohnso49** [comment]
I am able to reproduce:

Version: 1.86.0 (Universal)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:29:15.765Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0

Looking at the option that was mentioned:
`search.collapseResults: "alwaysExpand"`

When I search, after results are populated I am not able to collapse them using the button shown in the screenshot.

**Workaround**
I seem to have restored functionality by modifying the `search.collapse ` to a different value than `alwaysExpand`. I unfortunately don't know which specific value fix things, so would recommend trying them each, redo the search, and then attempt to click the collapse button. I am now able to toggle the button regardless of what option `search.collapseResults` is set to

**Comment by andreamah** [comment]
Hmm. Does your `settings.json` explicitly say `search.collapseResults: "alwaysExpand"` now? and if you remove it, can you reproduce the bug?

**Comment by ejohnso49** [comment]
It does not have that explicitly defined in my case and I don't believe I had it explicitly set previously. I also have since updated to 1.86.1. I'm having a hard time reliably reproducing the bug unfortunately. I will make sure to report back if I reproduce. I do wonder if some of the behavior was less due to the button and maybe the search still loading?

**Comment by gjsjohnmurray** [comment]
I have submitted a PR that I think fixes the issue.

**Comment by Anutrix** [comment]
Waiting for this since a few days. I assume the fix is isn't in 1.86.2.

**Comment by gjsjohnmurray** [comment]
@Anutrix no, it's in 1.87 which should be published this week.
