### ISSUE TITLE
Resize terminal shortcut broken in latest 1.86.0 on Ubuntu 22.04

### ISSUE THREAD

**Issue by Davidsastresas** [microsoft/vscode#204389]
Selecting a shortcut to:

- Terminal: Resize Terminal Right
- Terminal: Resize Terminal Left

Has the same effect, which is resizing left. This bug happened right after I updated to 1.86.0.

**Comment by meganrogge** [comment]
cannot repro, maybe use `Developer: Toggle Keyboard Shortcuts Troubleshooting` to ensure the right commands are happening?

**Comment by jsbrain** [comment]
I'm experiencing the same issue. Double checked my keyboard settings, both commands result in resize left.

**Comment by jsbrain** [comment]
@meganrogge just tested it on insider.

To reproduce:
Download vscode, set terminal panel to `right` and use the shortcut for resizing left and you should see it.

Not sure why this got closed immediately but please reopen.
