### ISSUE TITLE
Adopt the multi-file diff editor for rendering refactor previews

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#204370]
This feature request is about using the multi-diff editor in order to render the preview from the refactor preview view. Currently each change is shown in its own diff editor. We have decided to adopt the following approach to implement this:

- [x] On click of the refactor preview, open a multi-diff editor showing all the changes
- [ ] Place the refactor preview view directly into the multi-diff editor. Currently it is in an output view, on the same level as the terminal.
- [ ] Explore combining the tree of changes with the multi-diff editor

**Comment by tjx666** [comment]
cool

**Comment by aiday-mar** [comment]
One idea that was proposed by @lszomoru is to show the refactor preview in the side panel instead of within the editor (just like the results of `find references`). This would free some vertical space for the multi diff editor, and would allow us to reuse an existing component.

**Comment by aiday-mar** [comment]
Ah yes that's right
