### ISSUE TITLE
Consider to remove `RegisterSearchViewContribution`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#204347]
I came across this:

https://github.com/microsoft/vscode/blob/981343c94fe0c4098a864a97983ffbc4ce62366d/src/vs/workbench/contrib/search/browser/search.contribution.ts#L87-L104

Can we by now remove it? Seems quite old: https://github.com/microsoft/vscode/pull/89190

**Comment by sandy081** [comment]
Yes, this can be removed!
