### ISSUE TITLE
Disconnect icon doesn't appear when PowerShell debugger attaches to process

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#20432]
- VSCode Version: 1.9.1
- OS Version: Windows 10 AU (1607)
- PowerShell extension version: 0.9.0

Steps to Reproduce:

1. Open VSCode
2. Open command palette and type "PowerShell: Open Examples" and press Enter
3. Open file DebugTest.ps1
4. Open a PowerShell console
5. Execute $pid in the Powershell terminal to see process id
6. In Debug view, select the Attach to config and press F5.
7. Select the pid for the terminal and press Enter

Once the debugger is connected, notice the debug actions pane shows the stop button instead of the disconnect button.

Related - https://github.com/PowerShell/vscode-powershell/issues/486

cc @isidorn

**Comment by rkeithhill** [comment]
@isidorn  Verified fixed in the PowerShell extension w/ today's Insider build.  Thanks!

**Comment by isidorn** [comment]
@rkeithhill thanks, thus adding a verified label.
