### ISSUE TITLE
"Check for Updates" menu item missing?

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#204332]
Type: <b>Bug</b>

Or it moved?

![Image](https://github.com/microsoft/vscode/assets/9205389/7178688e-f79d-490f-86a2-9de68e33d408)

VS Code version: Code - Insiders 1.87.0-insider (ec291c126878742ad640055ce604a58129cd088c, 2024-02-05T05:57:56.185Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|8, 13, 11|
|Memory (System)|64.00GB (8.45GB free)|
|Process Argv|--log trace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
openmatchingfiles|bca|0.5.4
unique-lines|bib|1.0.0
devcontainer-image-convert|Bri|0.0.1
network-proxy-test|chr|0.0.10
regex|chr|0.4.0
esbuild-problem-matchers|con|0.0.3
vscode-eslint|dba|2.4.4
codespaces|Git|1.16.9
copilot|Git|1.156.689
copilot-chat|Git|0.13.2024020201
remotehub|Git|0.62.0
vscode-pull-request-github|Git|0.81.2024020111
vscode-drawio|hed|1.6.6
rest-client|hum|0.25.1
template-string-converter|meg|0.6.1
regexsnippets|Mon|1.0.2
vscode-docker|ms-|1.28.0
vscode-language-pack-de|MS-|1.85.2024013109
vscode-language-pack-qps-ploc|MS-|1.85.2024013109
black-formatter|ms-|2024.1.10331006
debugpy|ms-|2024.0.0
python|ms-|2024.0.0
vscode-pylance|ms-|2024.1.104
jupyter|ms-|2024.2.2024020201
jupyter-hub|ms-|2023.10.1003492320
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.339.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
extension-test-runner|ms-|0.0.5
hexeditor|ms-|1.9.13
live-server|ms-|0.5.2024010901
remote-explorer|ms-|0.5.2024011009
remote-repositories|ms-|0.40.0
remote-server|ms-|1.6.2024012309
test-adapter-converter|ms-|0.1.9
vscode-github-issue-notebooks|ms-|0.0.130
vscode-selfhost-test-provider|ms-|0.3.25
vscode-speech|ms-|0.5.2024020116
vscode-yaml|red|1.14.0
vscode-dall-toys|rob|0.0.7
rust-analyzer|rus|0.4.1830
crates|ser|0.6.6
eval|Sto|0.0.6
vscode-open-in-github|sys|1.18.0
even-better-toml|tam|0.19.2
shellcheck|tim|0.35.0
non-github-remote-source-provider|und|0.0.1
vscode-lldb|vad|1.10.0

</details>

**Comment by gjsjohnmurray** [comment]
Are there any update-related messages in you Main output channel?

**Comment by chrmarti** [comment]
My bad, I had set Update Mode to None for testing and forgot to change it back. 🤦 

Closing, thanks.
