### ISSUE TITLE
`--vscode-multiDiffEditor-headerBackground` exists but not applied to elements

### ISSUE THREAD

**Issue by EmrecanKaracayir** [microsoft/vscode#204352]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.86.0
- OS Version: Fedora Linux 39

Steps to Reproduce:

1. Assign a color to `multiDiffEditor.headerBackground` theme token.
2. Observe that diff editor headers don't even use that token.

The theme color token `multiDiffEditor.headerBackground` doesn't seem to be used at all in the current VS Code version.

Current behaviour
![Screenshot-from-2024-02-05-14-41-24](https://github.com/microsoft/vscode/assets/84916904/90b2f4f1-1dc0-4c27-a3ef-425079578f35)

Expected behaviour, after modifying background-color attribute
![Screenshot-from-2024-02-05-14-41-24 (1)](https://github.com/microsoft/vscode/assets/84916904/92c916db-2f5a-43bd-bdf1-62e565e84a30)

**Comment by Suenaga-Ryuya** [comment]
When I implement my custom vscode theme, I found that the `diffEditor.unchangedRegionBackground` color attach the property of  `multiDiffEditor.headerBackground`!

![image](https://github.com/microsoft/vscode/assets/58873641/f8228b43-4072-40ae-a2f1-735434a645ae)

I hope it is helpful to fix the bug :)
I'm sorry if you already knew it.

**Comment by EmrecanKaracayir** [comment]
It's fixed in the recent releases.
