### ISSUE TITLE
Menu Button: Go > Forward is always grayed out

### ISSUE THREAD

**Issue by griffin-warrior** [microsoft/vscode#204357]
Type: <b>Bug</b>

**Menu Button: Go > Forward** is not working after update. It's always grayed out. 
This is a very important feature when browsing the code. Hope to fix it soon. Thanks!

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (28 x 2394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|191.88GB (122.92GB free)|
|Process Argv|--crash-reporter-id fe5b6cd4-469e-4b02-836d-ba5bf86fd035|
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
todo-tree|Gru|0.0.226
better-cpp-syntax|jef|1.17.2
regionfolder|map|1.0.22
debugpy|ms-|2024.0.0
python|ms-|2024.0.0
vscode-pylance|ms-|2023.12.1
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
gem5-slicc|Tsi|1.6.0
cmake|twx|0.0.17
vim|vsc|1.27.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>

**Comment by gjsjohnmurray** [comment]
It is working for me, becoming enabled after I have used the Back button.

Please use the `Start Extension Bisect` command to investigate.

**Comment by griffin-warrior** [comment]
> It is working for me, becoming enabled after I have used the Back button.
> 
> Please use the `Start Extension Bisect` command to investigate.

Thanks for your advice. 
After a lot of effort trying to record the bug in gif, finally it's working well again after restarting vscode.
