### ISSUE TITLE
Should `onNotebook` activation events be implicit.

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#204384]
As of https://code.visualstudio.com/updates/v1_74#_implicit-activation-events-for-declared-extension-contributions several activation events are implicit, such as onCommand, onLanguage, onView etc.

Should onNotebook be implicitly added for all extensions specify a notebook under contributions?

**Comment by joyceerhl** [comment]
We do have this for notebook `onRenderer`: https://github.com/microsoft/vscode/commit/42f41d4f2526c059176d0406dfa34f22b96790a0

**Comment by rebornix** [comment]
`onNotebook` is an event for notebook document open, for notebook serializer contribution, it's `onNotebookSerializer` and it's already implicit.
