### ISSUE TITLE
In VS code 1.86, Progress information was shown in status bar instead of right-corner as before versions, which is not a good idea I think

### ISSUE THREAD

**Issue by yunknown** [microsoft/vscode#204334]
I am writing a debugger adapter. I use ProgressStartEvent/ProgressUpdateEvent/ProgressEndEvent to report some debug opertions' progress information. In previous versions, the progress information was shown in right-bottom corner, however, in 1.86.0, the progress information is shown in status bar instead.

I think this is not a good idea, as user might not be able to notice the progress information. 

If there is a workaround if I still want to show progress information in right-bottom corner of VS code?

Thanks!
Bill Zhang

**Comment by gjsjohnmurray** [comment]
I haven't yet found a 1.86 commit that specifically changes this behaviour. Have you perhaps been trying out this new 1.86 feature?

https://code.visualstudio.com/updates/v1_86#_allow-disabling-notifications-per-extension

**Comment by bpasero** [comment]
If this is a confirmed regression, it would help to know which change caused it. We maintain a node.js based CLI tool  [`vscode-bisect`](https://github.com/microsoft/vscode-bisect) that automatically downloads and runs previous VS Code insiders and asks for each build if the issue reproduces. It takes up to 8 steps to find exactly the build that caused the regression.

**Steps:**
* install [node.js](https://nodejs.org/en/download) (if not yet done)
* `npx --yes @vscode/vscode-bisect@latest`
* follow the instructions until you found the offending build (its fine to leave the commit empty)
* report back the commit range in this issue

Thanks!

**Comment by yunknown** [comment]
> I haven't yet found a 1.86 commit that specifically changes this behaviour. Have you perhaps been trying out this new 1.86 feature?
> 
> https://code.visualstudio.com/updates/v1_86#_allow-disabling-notifications-per-extension

The progress information was shown in status bar, not a pop-up window as before versions, so I have no way to enable/disable notification. In addition, notification was shown as before in right-bottom corner.

**Comment by yunknown** [comment]
> If this is a confirmed regression, it would help to know which change caused it. We maintain a node.js based CLI tool [`vscode-bisect`](https://github.com/microsoft/vscode-bisect) that automatically downloads and runs previous VS Code insiders and asks for each build if the issue reproduces. It takes up to 8 steps to find exactly the build that caused the regression.
> 
> **Steps:**
> 
> * install [node.js](https://nodejs.org/en/download) (if not yet done)
> * `npx --yes @vscode/vscode-bisect@latest`
> * follow the instructions until you found the offending build (its fine to leave the commit empty)
> * report back the commit range in this issue
> 
> Thanks!

1.85 does not have this issue.

**Comment by bpasero** [comment]
If you cannot find the actual commit causing this using `vscode-bisect`, then you need to provide a minimal repro for us to try out.

**Comment by yunknown** [comment]
> If you cannot find the actual commit causing this using `vscode-bisect`, then you need to provide a minimal repro for us to try out.

I have tried the vscode-bisect, but it failed:

PS C:\git\BIOSDBGV4\src\extension> npx --yes @vscode/vscode-bisect@latest  --reset
[build] deleting cache directory C:\Users\zhiqzhan\AppData\Local\Temp\vscode-bisect
√ Commit of released insiders build that reproduces the issue (leave empty to pick the latest build) ...
√ Commit of released insiders build that does not reproduce the issue (leave empty to pick the oldest build) ...
[build] fetching all builds from https://update.code.visualstudio.com/api/commits/insider/win32-x64?released=false...
[build] total 171 builds with roughly 7 steps
[build] downloading build from https://update.code.visualstudio.com/commit:44567a1304ea91ce041fde76e07937bb47fd77ba/win32-x64-archive/insider...
[build] unzipping build to C:\Users\zhiqzhan\AppData\Local\Temp\vscode-bisect\.builds\44567a\VSCode-win32-x64-1.85.0-insider...
[build] starting desktop build 44567a1304ea91ce041fde76e07937bb47fd77ba...
√ Is 44567a1304ea91ce041fde76e07937bb47fd77ba good or bad? » Good
[build] downloading build from https://update.code.visualstudio.com/commit:a0b228b51c9c7f8224dd8873927016cfb6797a80/win32-x64-archive/insider...
[build] unzipping build to C:\Users\zhiqzhan\AppData\Local\Temp\vscode-bisect\.builds\a0b228\VSCode-win32-x64-1.86.0-insider...
[build] starting desktop build a0b228b51c9c7f8224dd8873927016cfb6797a80...
√ Is a0b228b51c9c7f8224dd8873927016cfb6797a80 good or bad? » Bad
[build] downloading build from https://update.code.visualstudio.com/commit:ab0520decb7284b2b2a9bbe3ababea57ac83c86b/win32-x64-archive/insider...
[error] Error: read ECONNRESET
You can run vscode-bisect --verbose for more detailed output and vscode-bisect --reset for a fresh start without caches.

**Comment by yunknown** [comment]
> > If you cannot find the actual commit causing this using `vscode-bisect`, then you need to provide a minimal repro for us to try out.
> 
> I have tried the vscode-bisect, but it failed:
> 
> PS C:\git\BIOSDBGV4\src\extension> npx --yes @vscode/vscode-bisect@latest --reset [build] deleting cache directory C:\Users\zhiqzhan\AppData\Local\Temp\vscode-bisect √ Commit of released insiders build that reproduces the issue (leave empty to pick the latest build) ... √ Commit of released insiders build that does not reproduce the issue (leave empty to pick the oldest build) ... [build] fetching all builds from https://update.code.visualstudio.com/api/commits/insider/win32-x64?released=false... [build] total 171 builds with roughly 7 steps [build] downloading build from https://update.code.visualstudio.com/commit:44567a1304ea91ce041fde76e07937bb47fd77ba/win32-x64-archive/insider... [build] unzipping build to C:\Users\zhiqzhan\AppData\Local\Temp\vscode-bisect.builds\44567a\VSCode-win32-x64-1.85.0-insider... [build] starting desktop build [44567a1](https://github.com/microsoft/vscode/commit/44567a1304ea91ce041fde76e07937bb47fd77ba)... √ Is [44567a1](https://github.com/microsoft/vscode/commit/44567a1304ea91ce041fde76e07937bb47fd77ba) good or bad? » Good [build] downloading build from https://update.code.visualstudio.com/commit:a0b228b51c9c7f8224dd8873927016cfb6797a80/win32-x64-archive/insider... [build] unzipping build to C:\Users\zhiqzhan\AppData\Local\Temp\vscode-bisect.builds\a0b228\VSCode-win32-x64-1.86.0-insider... [build] starting desktop build [a0b228b](https://github.com/microsoft/vscode/commit/a0b228b51c9c7f8224dd8873927016cfb6797a80)... √ Is [a0b228b](https://github.com/microsoft/vscode/commit/a0b228b51c9c7f8224dd8873927016cfb6797a80) good or bad? » Bad [build] downloading build from https://update.code.visualstudio.com/commit:ab0520decb7284b2b2a9bbe3ababea57ac83c86b/win32-x64-archive/insider... [error] Error: read ECONNRESET You can run vscode-bisect --verbose for more detailed output and vscode-bisect --reset for a fresh start without caches.

At first, it is quick in downloading vscode-insiders, but later it takes a long time to download it. I am not sure why.

![image](https://github.com/microsoft/vscode/assets/4264592/f0320066-ce98-4964-a5dc-181ea117d088)

**Comment by yunknown** [comment]
> @yunknown thanks a lot for trying it though, maybe some connection trouble. I can try it if you tell me how to reproduce.

I create a simple debugger for testing.
code: [code.zip](https://github.com/microsoft/vscode/files/14175879/code.zip)
vsix: [test-debugger-1.0.0.vsix.zip](https://github.com/microsoft/vscode/files/14175886/test-debugger-1.0.0.vsix.zip)

I am not sure whether you know how to start a debugger or not:
1) install test-debugger-1.0.0.vsix 
2) open a empty folder and then create a luanch.json:
![create_launch](https://github.com/microsoft/vscode/assets/4264592/cb25bb37-06e9-4bc9-9dec-864f068ff02e)
3) select Debugger For Test
![add_configuration](https://github.com/microsoft/vscode/assets/4264592/3fb419c2-e42e-44c0-abf9-f4f66b751af2)
4) Start Testing debugger
![start_testing_debugger](https://github.com/microsoft/vscode/assets/4264592/858fc7d3-ad95-4cd0-87ff-09f1fea5b996)
5) You will see progress information in status bar
![1 86_progress_info](https://github.com/microsoft/vscode/assets/4264592/768ce489-6a0a-4d26-8fe3-28ea90772bba)

**Comment by yunknown** [comment]
If run in 1.85.2, it is as below:
![1 85 2_progress_info](https://github.com/microsoft/vscode/assets/4264592/1101706d-26eb-4b29-8780-367e5a95b01b)

**Comment by bpasero** [comment]
@yunknown thanks! Is it possible that you have snoozed notifications either globally or for the extension? You effectively see the same notification but when it appears in the status bar, it means the notification is hiding because of the "Do not disturb mode". When you click the status bar entry you can see how it changes to the notification toast.

**Comment by yunknown** [comment]
> @yunknown thanks! Is it possible that you have snoozed notifications either globally or for the extension? You effectively see the same notification but when it appears in the status bar, it means the notification is hiding because of the "Do not disturb mode". When you click the status bar entry you can see how it changes to the notification toast.

Yes, you are right. But event in below setting (BIOSDBG V4 is my extension):
![image](https://github.com/microsoft/vscode/assets/4264592/2de71192-4dc1-4aa9-95e3-47c705723b39)

The notification is hidden unless you click the right-bottom icon.
![image](https://github.com/microsoft/vscode/assets/4264592/d7adf4f1-4943-4bac-87bb-d05359c8e726)

I think it make me confused and it is not easy for user to notice this. Thanks!

**Comment by bpasero** [comment]
There is indeed a change that happened as part of our latest release, but I think for the better: debug decided to show notifications for debug progress in the status bar via this directive:

https://github.com/microsoft/vscode/blob/8839e62ada712a958e76e9c5cd62a41176c51501/src/vs/workbench/contrib/debug/browser/debugProgress.ts#L48

A change I did last milestone actually made to support it now:

https://github.com/microsoft/vscode/blob/8839e62ada712a958e76e9c5cd62a41176c51501/src/vs/workbench/services/progress/browser/progressService.ts#L73-L80

So I am deferring to debug component to further triage, but I think this is actually expected behaviour.

**Comment by connor4312** [comment]
I think we should revert to the old behavior for consistency as that's what users have historically seen
