### ISSUE TITLE
CodeActionProvider triggered on moving the cursor

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#20431]
- VSCode Version: 1.9.1
- OS Version: Windows 7

I noticed a performance slowdown with my language server recently. I found out it's under a kind of a *denial of service* attack coming from the latest version of VSCode. It's asking for code actions every time the cursor is placed inside a word. When I scroll through a file using the arrow keys the lanuguage server is being asked many times to provide code actions. 

The following GIF shows the requests sent by VSCode while moving the cursor:

![codeactionfoo](https://cloud.githubusercontent.com/assets/3448684/22832517/9dcd266a-efae-11e6-9ce0-8c4f8eb4d46e.gif)

I was wondering if this behaviour is intended. So I looked up the [language server protocol documentation](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md). It says:

> The code action request is sent from the client to the server to compute commands for a given text document and range. The request is triggered when the user moves the cursor into **a problem marker** in the editor or presses the lightbulb associated with a marker.

As you can see the requests are sent without moving the cursor into a problem marker.
Is the documentation outdated? If yes is there a way to get the currently documented behaviour back?

**Comment by Wosi** [comment]
It's the same for the built in TypeScript extension. `provideCodeActions` is triggered whenever the cursor is placed in any word.

**Comment by Wosi** [comment]
This question is becoming a huge issue for me. 
When my language server is asked for code actions on a selection without a problem marker it diagnoses the entire file again. This is done to recover from a dismissed diagnostics cache. That has worked good for a long time. 
But now I see code action requests whenever the cursor moves into a word. The same is happening after any letter I type.  The server is flooded with expensive code action requests. From a user's point of view it looks like the server doesn't respond anymore or is becoming really slow when he's typing or scrolling through the code. 

In case the current behaviour is intended I need to change my language server in that point. It's not a big deal. But I'd like to know the root of that problem first: Is the error recovery in my language server bad? Is the language server protocol documentation outdated? Or doesn't VSCode work as intended?

**Comment by dbaeumer** [comment]
@Wosi sorry to hear that this is causing trouble for you. The change was actually intended (I let @jrieken) fill in the details. Reason being is that extension wanted to provide code actions not bound to error. For example things like converting Boolean expressions, ....

@jrieken would it make sense to provide a diagnostic in the provide request so that clients could get a little smarter ?

**Comment by jrieken** [comment]
> @jrieken would it make sense to provide a diagnostic in the provide request so that clients could get a little smarter ?

Glad you are asking ;-) When calling `provideCodeAction` we pass in a [`context`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1542) with the markers in questions. 

As @dbaeumer correctly explained we now ask for code action more often, e.g. to support offering refactorings in addition to quick fixes. Sorry, for not having communicated this more clearly...

**Comment by Wosi** [comment]
Thanks @dbaeumer and @jrieken for pointing this out. I will change my language server.

**Comment by dbaeumer** [comment]
I should read my code as well. We are actually passing the diagnostics along to the server. So a server should be able to see if a diagnostic is reported at the cursor position.
