### ISSUE TITLE
My codespace is completely broken, how can I fix it ???

### ISSUE THREAD

**Issue by BenjaminV711** [microsoft/vscode#204339]
I constantly get messages stating "permission denied" when trying to execute a file;
and when trying to execute it it puts me incredible syntax errors, although I know there are no errors in the code !

For instance, in this one, the compiler states a syntax error with the main, although there is clearly nothing wrong there.

#include <cs50.h>
#include <stdio.h>

int main(void)
{
    int height;

    do
    {
        height = get_int("Height of the pyramid? ");
    } while (height < 1 || height > 8 );

    for (int i = 0; i < height; i ++)
    {
        printf("#");
    }

    return 0;
}

**Comment by gjsjohnmurray** [comment]
Please raise this with your CS50 support channel.
