### ISSUE TITLE
FileNotFoundError - Python debugger in VSCode not working 

### ISSUE THREAD

**Issue by StudioWEngineers** [microsoft/vscode#204407]
I am not longer able to run any Python file in VSCode and I have no clue about what I am doing wrong.

When running a simple `print("hello world")` I get the following error:

```
Exception has occurred: FileNotFoundError
[WinError 2] The system cannot find the file specified: 'c:\\Users\\XXX\\AppData\\Local\\Programs\\Python\\Python312\\python312.zip'
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\importlib\metadata\__init__.py", line 698, in mtime
    return os.stat(self.root).st_mtime
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\importlib\metadata\__init__.py", line 693, in search
    return self.lookup(self.mtime).search(name)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\importlib\metadata\__init__.py", line 795, in <genexpr>
    path.search(prepared) for path in map(FastPath, paths)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'c:\\Users\\XXX\\AppData\\Local\\Programs\\Python\\Python312\\python312.zip'
```
my `workspace.json` is:

```
{
	"folders": [
		{
			"path": "C:/studio_w"
		}
	],
	"launch": {
		"version": "0.2.0",
		"configurations": [{
			"name": "Python Debugger: Current File (Integrated Terminal)",
			"type": "debugpy",
			"request": "launch",
			"program": "${file}",
			"console": "integratedTerminal",
			"stopOnEntry": true,
			"justMyCode": false
		  }
		]
	}
}
```
I have only one Python version installed and VSCode is able to find it.
I tried to reinstall both VSCode and Python, but it did not help. 
I tried to `Python debugger: clear cache and reload windows`, but it did not help either. 

Does this issue occur when all extensions are disabled?: Yes/No
I have python extensions installed.

- VS Code Version: 
Version: 1.86.0 (system setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

- OS Version: 
Edition	Windows 10 Pro
Version	22H2
Installed on	‎15/‎08/‎2020
OS build	19045.3996
Experience	Windows Feature Experience Pack 1000.19053.1000.0

Steps to Reproduce:

1.  run `print("Hello World")`

**Comment by StudioWEngineers** [comment]
Silly mistake, sorry for the noise.

**Comment by fazedordecodigo** [comment]
How did you solve it? I have the same problem...

**Comment by StudioWEngineers** [comment]
In my case it was a silly typo: `if __name__ == "__main_" :`, but it took a while find it out.
