### ISSUE TITLE
Git commit one staged file in VSCode?

### ISSUE THREAD

**Issue by yuis-ice** [microsoft/vscode#204444]
Git commit one staged file in VSCode?

Something like e.g. `git commit -m "commit message" path/to/file.extension` in your CLI git.

**Comment by lszomoru** [comment]
@yuis-ice, you can modify a file, stage it, and click the "Commit" action button.

**Comment by yuis-ice** [comment]
I think it will "commit" all the files with some changes. Is my understanding/experience incorrect?

**Comment by lszomoru** [comment]
If you have changes that are staged, VS Code will only commit the staged file.
