### ISSUE TITLE
Make Playground a generic component and expose it to extensions

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#20449]
Users have a good time with our Welcome page and Playground in this release. Especially for new users, they get a chance to know how to use our editor to enhance their producibility, the interactive experience is awesome for education.

I'm thinking if it's possible that we can expose this feature to extensions, a good use case can be

1. Peng writes a markdown file with embedded code snippets of simple Ruby code in his Ruby extension.
2. Register the markdown file as a specific Playground scheme.
3. When users install the Ruby extension, they can open the playground page, directly edit those code snippets as now they are put in real editors.
4. They can run the snippet and see the results in output or preview page (We already have such an extension called Run Code to handle this), **without** setting up a new project/workspace for them.

IMHO, every Language Extension can use this to help educate beginners.

**Comment by rogersachan** [comment]
I agree with this. It could make moving http://www.tryfsharp.org/ a breeze for me (this is something the F# community has been asking for a long time.)

**Comment by jandrieu** [comment]
Fwiw, #54416 did not need to access the playground from an extension. Just to be able to load a .md file as a playground rather than for markdown editing.
