### ISSUE TITLE
Too many onDidChangeSelectedNotebooks subscribers leads to new kernels not being able to accept notebook association

### ISSUE THREAD

**Issue by andyscho** [microsoft/vscode#204416]
This is the underlying cause for the issue in https://github.com/microsoft/vscode-jupyter/issues/15075. This issue details the problem fixed by #204417.

Currently, users can supply arbitrary numbers of kernels. Each kernel that's added gets a listener for `onDidChangeSelectedNotebooks` in order to properly associate the kernel with the notebook so it can be executed if it is switched to.
https://github.com/microsoft/vscode/blob/12904c651efbdaa1346bf38260a85320866d49d0/src/vs/workbench/api/browser/mainThreadNotebookKernels.ts#L265-L271

The `Emitter` that is used for `onDidChangeSelectedNotebooks` is constructed with default settings.
https://github.com/microsoft/vscode/blob/12904c651efbdaa1346bf38260a85320866d49d0/src/vs/workbench/contrib/notebook/browser/services/notebookKernelServiceImpl.ts#L104

If users have too many kernels, the threshold can be hit.
https://github.com/microsoft/vscode/blob/12904c651efbdaa1346bf38260a85320866d49d0/src/vs/base/common/event.ts#L1016-L1019

When this happens, the kernel will show as selected in the UI, but will fail to execute because the kernel won't be able to properly associate with the notebook. See the vscode-jupyter issue referenced above for a demonstration of this.

- VS Code Version: Multiple VS Code versions, including current insiders
- OS Version: Present on Mac and Linux at least

Steps to Reproduce:
See https://github.com/microsoft/vscode-jupyter/issues/15075 for reproducing details.

**Comment by Jacob-Stevens-Haas** [comment]
I experienced this issue, but didn't see anything in the logs along the lines of `... REFUSES to accept new listeners because it exceeded...`.  Immediate problem solved by deleting kernels, but how would I have found that message?
