### ISSUE TITLE
side-by-side workspaces no longer work

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#20443]
It seems as if I can no longer have side-by-side workspaces  I have have workspaces above/below, but not side-by-side. Was this removed or do I have to enable it?

Here is the above/below:

![top-bottom-editor](https://cloud.githubusercontent.com/assets/1571806/22837596/eeb65eac-ef86-11e6-861d-f83cb49960d1.png)

I can't get a side-by-side example, because it won't let me make anything side-by-side.

**Comment by bpasero** [comment]
@TheColorRed try from the view menu:

![image](https://cloud.githubusercontent.com/assets/900690/22852250/4e3219e6-f038-11e6-8634-953b6e17017b.png)

**Comment by TheColorRed** [comment]
I have. It does the same thing. I have also tried the keybinding and the icon on the top right. None of them open it side by side.

**Comment by bpasero** [comment]
@TheColorRed please share a video of what you are doing

**Comment by TheColorRed** [comment]
@bpasero I figured it out, In the `Open Editors` there is that toggle button to toggle between horizontal and vertical. I didn't realize that was there. I had it set to horizontal.

**Comment by TheColorRed** [comment]
It would however, be nice if you could drag a tab to any of the four sides, and then it set up the layout instead of having it pre-defined. Then when all tabs are combined, the layout gets reset until a tab is dragged back to one of the four sides again and then the layout get defined again.

**Comment by bpasero** [comment]
Yes, agreed.
