### ISSUE TITLE
I had this configuration in my `launchsettings.json`:

### ISSUE THREAD

**Issue by MonitorOlympics** [microsoft/vscode#204450]
I had this configuration in my `launchsettings.json`:

```json
// ...
    "MyProject": {
      "commandName": "Project",
      "dotnetRunMessages": "true",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
// ...
```

I've changed it to:

```json
// ...
    "MyProject": {
      "commandName": "Project",
      "dotnetRunMessages": "true",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "https://*:5001;http://*:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
// ...
```
I can't click on `https://localhost:5001` in the debug console anymore because it's now `https://[::]:5001` but clicking on the 
`Open in Browser` button on the `Ports` view does the job and it doesn't opens any additional ports.

![image](https://user-images.githubusercontent.com/70940842/152787380-5882b4f2-6db0-487e-9044-c4f6e997cc03.png)

I will test if the problem still exists and if so I will create a test project

_Originally posted by @MBAatEJOT in https://github.com/microsoft/vscode-remote-release/issues/5446#issuecomment-1031411410_

**Comment by roblourens** [comment]
Sorry, so what is the problem here?

**Comment by MonitorOlympics** [comment]
> ```
>           I had this configuration in my `launchsettings.json`:
> ```
> 
>  ```json
> // ...
>     "MyProject": {
>       "commandName": "Project",
>       "dotnetRunMessages": "true",
>       "launchBrowser": true,
>       "launchUrl": "swagger",
>       "applicationUrl": "https://localhost:5001;http://localhost:5000",
>       "environmentVariables": {
>         "ASPNETCORE_ENVIRONMENT": "Development"
>       }
>     }
> // ...
> ```
> 
> I've changed it to:
> 
> ```json
> // ...
>     "MyProject": {
>       "commandName": "Project",
>       "dotnetRunMessages": "true",
>       "launchBrowser": true,
>       "launchUrl": "swagger",
>       "applicationUrl": "https://*:5001;http://*:5000",
>       "environmentVariables": {
>         "ASPNETCORE_ENVIRONMENT": "Development"
>       }
>     }
> // ...
> ```
> 
> I can't click on `https://localhost:5001` in the debug console anymore because it's now `https://[::]:5001` but clicking on the `Open in Browser` button on the `Ports` view does the job and it doesn't opens any additional ports.
> 
> ![image](https://user-images.githubusercontent.com/70940842/152787380-5882b4f2-6db0-487e-9044-c4f6e997cc03.png)
> 
> I will test if the problem still exists and if so I will create a test project
> 
> _Originally posted by @MBAatEJOT in [microsoft/vscode-remote-release#5446 (comment)](https://github.com/microsoft/vscode-remote-release/issues/5446#issuecomment-1031411410)_
