### ISSUE TITLE
Git auto refresh stopped working

### ISSUE THREAD

**Issue by amanda-olmo** [microsoft/vscode#204466]
Type: <b>Bug</b>

Git auto refresh stopped working yesterday. When I modify a file with the repo open in Vscode, it is not shown in the Source Control Panel automatically. It appears if I click on the refresh button. The week before it worked automatically.

I disabled all extensions and put "git.autorefresh": true in the Settings, but it did not fix the issue.

It also happens in all repos I have checked. 

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:27:46.147Z)
OS version: Linux x64 4.18.0-425.3.1.el8.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 1, 0|
|Memory (System)|31.34GB (24.36GB free)|
|Process Argv|. --crash-reporter-id 2f875dd0-c818-497e-919e-845354d815bd|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-classic|
|XDG_CURRENT_DESKTOP|GNOME-Classic:GNOME|
|XDG_SESSION_DESKTOP|gnome-classic|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30951795
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928
bg6jg535:30958357

```

</details>

**Comment by amanda-olmo** [comment]
This is the error displayed in the Dev Tools Console :


INFO Started local extension host with pid 370123.
log.ts:437   ERR [File Watcher (parcel)] Unexpected error: Invalid argument (EUNKNOWN) (path: /mnt/servers/fs01/lv-2/common/inhouse/amanda.olmo/directivebundle)
log.ts:437   ERR [File Watcher (universal)] restarting watcher after error: Invalid argument
log.ts:437   ERR [UtilityProcessWorker]: terminated unexpectedly with code 15, signal: unknown
log.ts:437   ERR [File Watcher (universal)] restarting watcher after error: terminated by itself unexpectedly with code 15, signal: unknown
log.ts:437   ERR [File Watcher (parcel)] Unexpected error: Invalid argument (EUNKNOWN) (path: /mnt/servers/fs01/lv-2/common/inhouse/amanda.olmo/directivebundle)
log.ts:437   ERR [File Watcher (universal)] restarting watcher after error: Invalid argument
log.ts:437   ERR [File Watcher (parcel)] Unexpected error: Invalid argument (EUNKNOWN) (path: /mnt/servers/fs01/lv-2/common/inhouse/amanda.olmo/directivebundle)
log.ts:437   ERR [File Watcher (universal)] restarting watcher after error: Invalid argument
log.ts:437   ERR [File Watcher (parcel)] Unexpected error: Invalid argument (EUNKNOWN) (path: /mnt/servers/fs01/lv-2/common/inhouse/amanda.olmo/directivebundle)
log.ts:437   ERR [File Watcher (universal)] restarting watcher after error: Invalid argument
log.ts:437   ERR [UtilityProcessWorker]: terminated unexpectedly with code 15, signal: unknown
log.ts:437   ERR [File Watcher (universal)] gave up attempting to restart watcher after error: terminated by itself unexpectedly with code 15, signal: unknown
log.ts:417  INFO [perf] Render performance baseline is 48ms
log.ts:437   ERR [File Watcher (parcel)] Unexpected error: Invalid argument (EUNKNOWN) (path: /mnt/servers/fs01/lv-2/common/inhouse/amanda.olmo/directivebundle)
log.ts:437   ERR [File Watcher (universal)] gave up attempting to restart watcher after error: Invalid argument
﻿

**Comment by lszomoru** [comment]
@bpasero, could you please take a look at the file watcher errors? Thank you!

**Comment by bpasero** [comment]
Since we did not change anything with the Parcel file watcher or surrounded code, I assume a file system configuration problem on your system with `/mnt/servers/fs01/lv-2/common/inhouse/amanda.olmo/directivebundle`.

**Comment by amanda-olmo** [comment]
Thanks. How can I check where is the problem?
I have checked with my coworkers, one of them has the same problem as me (with the same VSCode version) and other coworkers do not have the problem at all and they are using an older version (1.80.2). We all have the same file system and work on the same repositories

**Comment by bpasero** [comment]
The path seems to be a mounted share maybe? We do not guarantee file events over network drives, so it may well not be supported.

**Comment by amanda-olmo** [comment]
I have cloned a git repo inside the Desktop folder to test it, and the git auto refresh works fine. So the problem is the mounted share folder, as you said.
We prefer to work there because it can be accessed from any computer. Is there anything that can be done?

**Comment by bpasero** [comment]
If you are willing to conduct an experiment, we are using Parcel watcher for file watching: https://github.com/parcel-bundler/watcher

Would be interesting to see what happens when you point it to that folder.

**Comment by amanda-olmo** [comment]
Can you provide an example of what I have to execute? I do not know C++

**Comment by bpasero** [comment]
You do not need any C++ knowledge, but a bit of node.js and JavaScript. There is an example at https://github.com/parcel-bundler/watcher?tab=readme-ov-file#example for how to setup the watcher to watch a path on disk. I am curious what happens when you point it to that folder.

**Comment by amanda-olmo** [comment]
I do not know neither node.js or JavaScript

**Comment by bpasero** [comment]
This issue could originate from a problem with file watching. Let me explain how file watching works in VSCode first and then provide some details how to get more logging data from how file watching behaves in your case.

**Synopsis**
VSCode has different strategies for file watching depending on your workspace and setup:
* no folder opened: files in opened editors are watched via node.js `fs.watch`
* folder opened: folder is watched recursively for all changes via [parcel](https://github.com/parcel-bundler/watcher), opened editors with files not within the folder are watched via node.js `fs.watch`

If you are connected to a remote (SSH, WSL, Docker), the file watcher will run within the target file system. As such, even though you maybe on Windows where VSCode runs, if the remote is Linux, the file watcher will run in the Linux environment.

**Platforms**
Depending on the platform you are on, file watching is differently implemented:
* macOS: using `fsevents` services
* Windows: using `ReadDirectoryChangesW` method
* Linux: using `inotify`

Specifically on Linux, watching a large folder recursively can result in VSCode consuming too many file handles. If that is the case, you will see a warning notification with instructions how to solve that.

**Limitations**
File watching comes with a set of limitations:
* symbolic links are not followed automatically but you can explicitly add symbolic links to be watched via the `files.watcherInclude` setting
* mapped network drives or third party file system drivers are not guaranteed to produce file events
* in general, the operating system may decide to drop file events at any time, there is no 100% guarantee

**Settings**
Please review your settings to see if maybe a folder is excluded by accident. Specifically, the `files.watcherExclude` setting is relevant.

**Logging (local)**
!!! This is ONLY when you open a local workspace, for remote see below !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the local workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `Help | Toggle Developer Tools`
* select `Console`
* filter the output by typing `File Watcher` into the filter box
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323290-f3ba6470-dfed-4066-a19c-951395611738.png)

**Logging (remote)**
!!! This is ONLY when you open a remote workspace (WSL, Docker, SSH), for local see above !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the remote workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `View | Output`
* select `Log (Remote Server)` from the dropdown
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323886-6b7dfa25-d6ac-4316-9150-80e5c8104d04.png)

**Comment by bpasero** [comment]
Thanks, I am unfortunately out of ideas.

**Comment by amanda-olmo** [comment]
Thanks for your time. I will ask IT to install an older version of VSCode in which the git auto refresh works

**Comment by bpasero** [comment]
According to the file watcher docs, the target file system on Linux must support `inotify`: https://man7.org/linux/man-pages/man7/inotify.7.html

So maybe something is not supported in that area that causes this error.

**Comment by chammann** [comment]
We have the same issue with the File Watcher failing with nfs mounts (Rocky 9) with Vs Code 1.87.  Vs code 1.84 works fine. @bpasero
