### ISSUE TITLE
VS code - TypeScript service

### ISSUE THREAD

**Issue by pradeepb53** [Microsoft/vscode#20444]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Open VS Code
2. Create a file, an app.js (for Node js) on a shared folder (mapped drive for IBM system i ) 
3. Warning message 'Typescript language service died unexpectedly' would pop up

**Comment by mjbvz** [comment]
The TypeScript network drive issue is being tracked by https://github.com/Microsoft/TypeScript/issues/13997

You can work around this issue by opening the network drive directly (not using a mapped drive). This should work in VSCode 1.9.1 using TypeScript 2.1.6
