### ISSUE TITLE
Screen Blur and Lines 

### ISSUE THREAD

**Issue by SoftwareHackerNick** [microsoft/vscode#204454]
Type: <b>Bug</b>

When i am using vs code while i am programming using any lanaguage...there is lining comes in act and that lines damage my screen visibility makes unvisible

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.76GB (1.07GB free)|
|Process Argv|--crash-reporter-id ab1118e9-3d35-4cf3-8154-4a576dc56032|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
bootstrap5-vscode|Anb|0.4.4
atlascode|atl|3.0.9
blackbox|Bla|1.2.61
vscode-intelephense-client|bme|1.10.2
bracket-pair-color-dlw|Bra|0.0.6
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
vscode-autosave|cod|1.2.3
flask-snippets|cst|0.1.3
vscode-eslint|dba|2.4.4
composer-php-vscode|DEV|1.44.14925
intelli-php-vscode|DEV|0.12.14619
phptools-vscode|DEV|1.44.14925
profiler-php-vscode|DEV|1.44.14925
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|10.1.0
bootstrap-4-cdn-snippet|eve|1.13.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
codespaces|Git|1.16.9
vscode-pull-request-github|Git|0.80.0
jenkins-pipeline-linter-connector|jan|1.2.0
search-node-modules|jas|1.3.0
vsc-python-indent|Kev|1.18.0
vscode-docker|ms-|1.28.0
autopep8|ms-|2023.8.0
debugpy|ms-|2024.1.10362349
isort|ms-|2023.10.1
python|ms-|2024.1.10361108
jupyter|ms-|2024.1.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
autodocstring|njp|0.6.1
vscode-thunder-client|ran|2.17.7
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
bootstrap4-vscode|the|6.1.0
python|tht|0.2.3
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-maven|vsc|0.44.0
nodejs-extension-pack|wad|0.1.9
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.34.0
php-pack|xde|1.0.3
sqlalchemy-schema|xwb|0.0.4
chat-gpt|zha|1.6.63
php-intellisense|zob|1.3.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
7j2b6412:30949929
e3gdj431:30958358

```

</details>

**Comment by chrmarti** [comment]
Please append a screenshot.

**Comment by SoftwareHackerNick** [comment]
![Screenshot (321)](https://github.com/microsoft/vscode/assets/100552645/592b0cb4-0342-4d4a-b4a2-564179f277b2)
![image](https://github.com/microsoft/vscode/assets/100552645/e5459c4c-d225-4a72-a024-d5834c4217f0)

**Comment by SoftwareHackerNick** [comment]
Please Help me

**Comment by deepak1556** [comment]
Please enable the setting following the steps at https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

/duplicate https://github.com/microsoft/vscode/issues/124226
