### ISSUE TITLE
Random colors of syntax highlight on reformatting

### ISSUE THREAD

**Issue by KonradDRAST** [microsoft/vscode#204456]
Type: <b>Bug</b>

After reformating through prettier on save, syntax sometimes gets random colors rather than correctly highlighting whole words.

![image](https://github.com/microsoft/vscode/assets/17060750/b08d1ba0-d9c0-4890-8813-13581a9949a6)

![image](https://github.com/microsoft/vscode/assets/17060750/071f9e20-51a1-42fc-ac0a-164ac72c989d)

That was `.vue` files in both cases.

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400F (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (4.99GB free)|
|Process Argv|--crash-reporter-id 34ad5e80-d7e3-4ad2-b480-338f989ad190|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
unique-lines|bib|1.0.0
vscode-tailwindcss|bra|0.10.5
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
vscode-sql-beautify|cla|0.3.23
codeium|Cod|1.6.29
language-postcss|cpy|1.1.0
dart-code|Dar|3.82.0
vscode-eslint|dba|2.4.4
xml|Dot|2.5.1
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
dotenv|mik|1.0.1
vue-volar-extention-pack|Mis|1.1.8
vscode-language-pack-pl|MS-|1.85.2024013109
material-icon-theme|PKi|4.33.0
LiveServer|rit|5.7.9
code-spell-checker|str|3.0.1
code-spell-checker-polish|str|2.1.2
vscode-stylelint|sty|1.3.0
vscode-icons|vsc|12.7.0
volar|Vue|1.8.27
vscode-typescript-vue-plugin|Vue|1.8.27
vscode-wakatime|Wak|24.4.0
vscode-import-cost|wix|3.3.0
change-case|wma|1.0.0
material-theme|zhu|3.16.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>

**Comment by mjbvz** [comment]
Please start by filing this issue against your Vue extension
