### ISSUE TITLE
Creating a new profile from vscode.dev that is connected to a WSL instance fails to load

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#204424]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
```
Version: 1.87.0-insider
Commit: ec291c126878742ad640055ce604a58129cd088c
Date: 2024-02-05T05:52:49.458Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
```
- OS Version: 
Edge Browser, insiders.vscode.dev

Steps to Reproduce:

1. On your Windows machine, install WSL, the WSL extension and open a distro in VS Code (e.g., Ubuntu-22.04)
2. Install the Remote-Tunnels extension
3. Turn on Tunnels
4. Get the URL to insiders.vscode.dev and connect to the WSL instance that is running
5. Create a new profile

Result: VS Code tries to reload for the Profile, but now there is no WSL extension installed in the browser so you get into a reload loop and if you close that prompt, you can't query the Marketplace to install the WSL extension.

To "work around" this problem i can open insiders.vscode.dev, turn on the profile, and then install the WSL extension. Then I can use the Remote Explorer to connect to WSL again with that profile.  But, if you create a new profile, you are back to the Reload Window loop.

**Comment by sandy081** [comment]
@chrisdias I am not able to reproduce this issue.

> VS Code tries to reload for the Profile, but now there is no WSL extension installed in the browser so you get into a reload loop

I do not see WSL extension installed in the browser (insiders.vscode.dev). All you need in the browser is the remote tunnels extension which I believe is available by default as built in extension for all profiles. 

Can you please give more information how you are getting into a reload loop?

**Comment by chrisdias** [comment]
No longer seems to be an issue, closing.
