### ISSUE TITLE
Allow terminal environment to be set when created via extension API

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#20446]

**Comment by daviwil** [comment]
Sweet, thanks!

**Comment by Tyriar** [comment]
Opening to PRs, the ideal change would plum through a new option in the terminal API `"env"` which includes *additions* to the environment. You can look a search on "waitOnExit" to see most of the places that need to change https://github.com/Microsoft/vscode/search?l=TypeScript&q=waitOnExit&type=&utf8=%E2%9C%93

**Comment by dbaeumer** [comment]
@Tyriar we might to think about this in the light of tasks being API now. If a extension other could execute a task programmatically then all is there. A task can already specify its env.

**Comment by Tyriar** [comment]
@dbaeumer I know that [platformio]](http://platformio.org/) needs this, going through tasks is more restrictive that the terminal so they probably wouldn't want to do that.

**Comment by ivankravets** [comment]
Hi all,

Ivan from @PlatformIO. Thanks a lot for your work!

> 1. A task can already specify its env.

That is the first with which I stuck. We can't define custom environment variables in `tasks.json` per each task or as common for all. Again, we use [some hook](https://github.com/platformio/platformio-core/blob/develop/platformio/ide/tpls/vscode/.vscode/tasks.json.tpl#L3) for that.

2. A custom environment for built-in Terminal is very important. We use [dirty hook](https://github.com/platformio/platformio-vscode-ide/blob/develop/src/extension.js#L122:L133) now. `vscode.window.createTerminal('PlatformIO', env=dict)` would be good!

**Comment by Tyriar** [comment]
@dbaeumer do you have a link to the new task contribution extension API?

**Comment by dbaeumer** [comment]
Was in vscode.proposed.d.ts in 1.12 and is now in vscode.d.ts. See https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3766

It still might change until we ship 1.1.3

**Comment by Tyriar** [comment]
I see we're deferring it. @ivankravets you might find this new API useful in an upcoming version https://github.com/Microsoft/vscode/commit/e98c09c842df5a045f52386246a860c530945d9d

**Comment by ivankravets** [comment]
Is possible to subscribe to `onDidTaskRun()`? Where would be an ability to catch up some tasks and perform some operations. We have `do` and `post` callbacks in Atom Build. 

Simple use case. User open Serial Monitor via integrated Terminal, we see it. He triggers "Upload" task, we temporary close opened Serial Port Monitors/Terminals, then uploading firmware. If a task fails with an error, we don't re-open Monitor. However, if the upload was successful, we re-open last Serial Port Monitor.

Thanks for the hints!

**Comment by dbaeumer** [comment]
@ivankravets currently not but this is definitely something we can provide. Could you open an issue please.

**Comment by ivankravets** [comment]
@dbaeumer Thanks, done! https://github.com/Microsoft/vscode/issues/29855

**Comment by Tyriar** [comment]
@dbaeumer @ivankravets @dbaeumer hi all, @ramya-rao-a put together a PR for this https://github.com/Microsoft/vscode/pull/30352. We were thinking that the new `env` option in the API should add to the current environment rather than replace it. Wanted to get some opinions here because adding to the environment would certainly be more convenient for the vast majority of cases but we're just worried that people may need to remove keys from the environment. Does adding to the current environment cover your use cases?

**Comment by dbaeumer** [comment]
I currently merge / override the environments. This doesn't let you remove an value. We could say if a value is undefined it means to remove.

**Comment by ivankravets** [comment]
My proposition:

1. `options.evs` accepts dictionary (key/value object)
2. Terminal iterates over these keys and REPLACE all occurences in the current `process.env` which later will be used by terminal instance
3. I like this @dbaeumer "We could say if a value is undefined it means to remove."

-----

P.S: We should be able not only to override some environemnt variable but also to remove it (set to `null`/`undefined`).

Thanks!

**Comment by Tyriar** [comment]
@dbaeumer @ivankravets I like it :smile: @ramya-rao-a let's go additive but if the key exists and it's falsy, remove the key from the environment (note this in the API jsdoc).

**Comment by ivankravets** [comment]
How to use it with 1.18.0? 

```
vscode.window.createTerminal('PlatformIO', constants.IS_WINDOWS ? 'cmd.exe' : null, [], { TEST: 13 });
```

Does not work.

**Comment by ramya-rao-a** [comment]
@ivankravets 

```
code.window.createTerminal({name: 'PlatformIO', shellPath: constants.IS_WINDOWS ? 'cmd.exe' : null, [], { TEST: 13 }}
```

**Comment by ivankravets** [comment]
@ramya-rao-a Thanks, it works now!
