### ISSUE TITLE
SCM: clicking on staged image opens it as text file in editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#20441]
Steps to Reproduce:

1. add a new PNG to the project
2. stage it
3. open it

=> it opens as text file even though it is binary

**Comment by joaomoreno** [comment]
We need API to provide contents for binary documents. Or possibly images, through base64.

Thoughts @jrieken ?

**Comment by jrieken** [comment]
there is a `open` command with can do that

**Comment by joaomoreno** [comment]
The image doesn't exist on disk. I have access to a stream of bytes. We need API to provide contents for binary documents.

The workaround I could do for now is to stream everything to a temp file and show that. Sad!

**Comment by jrieken** [comment]
so, you want two things: 1) binary content provider and 2) openBinary which is complicated because we generally cannot open binaries. What would you expect to happen when a dll-file is staged?

**Comment by joaomoreno** [comment]
I'd expect us to at least say _this is a binary file which we can't open_.

**Comment by jrieken** [comment]
well, that's a start

**Comment by joaomoreno** [comment]
Let's keep it in mind.

**Comment by joaomoreno** [comment]
Fixed!
