### ISSUE TITLE
Find/replace dialog is much too small

### ISSUE THREAD

**Issue by dcormier** [Microsoft/vscode#20447]
The find/replace dialog needs to be much wider (or at least able to be resized to make it much larger). It's frustratingly small when trying to work with larger search strings.
![image](https://cloud.githubusercontent.com/assets/216265/22839669/6a418e6e-ef98-11e6-9e44-b67b2d3c44f7.png)

- VSCode Version: 1.9.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Edit > Find

**Comment by rebornix** [comment]
We are going to allow users to resize the Find widget (current plan), this problem will be solved in that way. Let's track this issue in https://github.com/Microsoft/vscode/issues/2657 and work on it in May. Thanks for your input!
