### ISSUE TITLE
shortcut not working

### ISSUE THREAD

**Issue by deepak14ri** [microsoft/vscode#204446]
Type: <b>Feature Request</b>

ctrl+ A shortcut not working.

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Remote OS version: Linux x64 6.1.43

**Comment by ArturoDent** [comment]
Run the command: `Developer: Toggle Keyboard Shortcuts Troubleshooting` and report the results.  Also `Reload with Extensions Disbaled` - does the problem still exist?

**Comment by deepak14ri** [comment]
go to setting and search shortcuts and check commands and delete other command who is same as which not working just like ctrl+c are kept as copy rest all delete.

**Comment by ulugbekna** [comment]
I assume the problem is resolved.
