### ISSUE TITLE
Copilot chat error

### ISSUE THREAD

**Issue by prabhuaashishg** [microsoft/vscode#204452]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Even though I logged in with my Copilot account it is asking to start 30-day free trial 
2. Inline suggestions are working but chat is not working

**Comment by sephraim** [comment]
This just happened to me as well after I updated VS Code to v1.86. I had to rollback to v1.85 to fix it.

Here is how to rollback:

1. Quit VS Code.
2. Install VS Code v1.85. Download it [here](https://code.visualstudio.com/updates/v1_85).
3. Open VS Code. Go to _Code -> About Visual Studio Code_ to make sure your version is 1.85.x.
4. Uninstall the GitHub Copilot Chat extension.
5. Reinstall the GitHub Copilot Chat extension.
6. Reload VS Code.

**Comment by MrAlfalfaDEV** [comment]
Hello @sephraim  I tried your suggestions but I still can't get it to work. Are there any additional suggestions you can kindly furnish me with?

Many thanks in advance

**Comment by sephraim-livefront** [comment]
You could any try the following:

- First, go to Code -> About Visual Studio Code and make sure your VS Code version is 1.85.x.
- Next: **Reload VS Code by running: _Cmd+P (or Ctrl+P) -> Developer: Reload Window_**
- Still not working? Try uninstalling / reinstalling both the _GitHub Copilot_ and the _GitHub Copilot Chat_ extensions. **Make sure to _Cmd+P (or Ctrl+P) -> Developer: Reload Window_** after reinstalling the extensions.
- Still not working? Try installing a previous version of the _GitHub Copilot_ extension (see GIF below for how to do that). **Make sure to _Cmd+P (or Ctrl+P) -> Developer: Reload Window_** after reinstalling the extension.
- Still not working? Try installing a previous version of the _GitHub Copilot Chat_ extension (see GIF below for how to do that). **Make sure to _Cmd+P (or Ctrl+P) -> Developer: Reload Window_** after reinstalling the extension.

![install_ext](https://github.com/microsoft/vscode/assets/121906014/ea0fefbe-6436-4963-a37a-78ef73a2c680)
[Image source](https://stackoverflow.com/a/53755378/990637)

Hope that helps!

**Comment by MrAlfalfaDEV** [comment]
Okay, so I rolled back to v0.11.0 which is from a month or two ago and it worked (GitHub Copilot Chat). Many thanks lads

**Comment by TylerLeonhardt** [comment]
This issue is caused by VS Code not properly supporting multiple auth sessions. Not much can be done on the extension side until VS Code fixes this. It was a bug that this worked before

Ref:
microsoft/vscode#203850
microsoft/vscode#127967

**Comment by sephraim** [comment]
I can confirm that GitHub Copilot Chat v0.11.1 works fine with VS Code v1.86.2. However, GitHub Copilot Chat v0.12.0 / v0.12.1 / 0.12.2 all give the "30-day free trial" error.
