### ISSUE TITLE
TypeScript services dies on mapped WebDAV drive

### ISSUE THREAD

**Issue by stephen-hardy** [Microsoft/vscode#20445]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.2.5|
|githistory|donjayamanne|0.1.5|
|mssql|ms-mssql|0.2.1|
|PowerShell|ms-vscode|0.9.0|
|code-settings-sync|Shan|2.4.3|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1. Map SharePoint document library to a drive via WebDAV
2. Open a JavaScript file (can repro with an empty file)

This behaving similarly to https://github.com/Microsoft/TypeScript/issues/13874, which is now resolved for me on v1.9.1

**Comment by stephen-hardy** [comment]
Just in case anybody is wondering why I'm mapping a drive, when TypeScript is now working with the UNC path:

ESLint recently broke for UNC paths. Mapping a drive was mentioned on this thread (https://github.com/Microsoft/vscode-eslint/issues/202), and I hadn't thought of trying that. I did, and ESLint worked, but then TypeScript broke.

Just wanted to mention that here, in case anybody else is looking for a way to get ESLint back before a fix is complete.

**Comment by stephen-hardy** [comment]
I'm guessing this goes back to this: https://github.com/libuv/libuv/issues/1221

And the workaround put in place for https://github.com/Microsoft/TypeScript/issues/13874 is simply missing this scenario.

**Comment by mjbvz** [comment]
Just to make sure, using TypeScript 2.1.6 in VSCode 1.9.1, you no longer see the typescript extension itself crashing when opening a sharepoint drive,  correct? Only eslint now?

Closing as external. Thank you for linking to the relevant issues

**Comment by stephen-hardy** [comment]
Feel free to ping me on Skype. I can repro it for you.

**Comment by mjbvz** [comment]
I did give this a try but saw it working in all the scenarios I tested. Reopening to investigate further. I'll contact you on skype to make sure I understand the correct repo steps

**Comment by mjbvz** [comment]
Thanks. I was able to repo this using the specific steps you provided. Opened a bug against TS to track this: https://github.com/Microsoft/TypeScript/issues/13997

Closing as upstream
