### ISSUE TITLE
Auto save delay on languages

### ISSUE THREAD

**Issue by Ardianii1** [microsoft/vscode#204542]
Ability to change the delay of autosave for specific language(.jsx .js .ts etc)  when Auto Save Workspace Files Only is enabled.

**Comment by bpasero** [comment]
Can you clarify what this would mean for workspace files vs out of workspace files? How would it work?

**Comment by Ardianii1** [comment]
I mean, regarding the option 'Auto Save Workspace Files Only' in the auto-save settings, it would be helpful to be able to adjust the auto-save delay for different file types. For example, when working with .jsx or .tsx files, you may want a delay of 2 seconds, while for .ts files, a delay of 1 second would be preferable. I hope this clarifies my feature request!

**Comment by bpasero** [comment]
https://code.visualstudio.com/updates/v1_86#_more-powerful-and-flexible-auto-save-options
