### ISSUE TITLE
Terminal panel rename using keyboard shortcut does not work (VSCode on Linux)

### ISSUE THREAD

**Issue by ChrisGy** [microsoft/vscode#204594]
Does this issue occur when all extensions are disabled?: Yes

The keyboard rename shortcut F2 seems to appropriately attempt a Terminal panel rename, but it gives the following feedback:
`command 'workbench.action.terminal.renamePanel' not found`.
Manually right-clicking the panel and clicking 'Rename' however works as expected.

- VS Code Version: 1.86.0 (2024-01-31)
- OS Version: Ubuntu 20.04.6 LTS, GNOME 3.36.8, X11.

Steps to Reproduce:

1. Click on the name of a Terminal.
2. Press the F2 key on keyboard.

![image](https://github.com/microsoft/vscode/assets/43790095/931bdf30-f8e6-4e78-9d72-7c6fa2789e42)

**Comment by mpriscella** [comment]
I was unable to reproduce using either the specified VS Code version (`1.86.0`) or the current stable version. In both instances, `F2` renamed the tab as expected.

It looks like the command `workbench.action.terminal.renamePanel` was removed in the `1.85.0` release (specifically in [this commit](https://github.com/microsoft/vscode/commit/ea078c058e95c1f94114c203c387c1214742f361)) and was replaced with `workbench.action.terminal.renameActiveTab`. Is it possible that you have that mapping still defined in `keybindings.json`?

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed
