### ISSUE TITLE
Sections of editor window flickering between images of previous visual states and black rectangles

### ISSUE THREAD

**Issue by StarryBlue7** [microsoft/vscode#204525]
Type: <b>Bug</b>

- Occurs in any VSCode editor window after January 2024 update (1.86.0), regardless of directory, file types open
- Does not occur when downgraded to prior release (1.85.2), nor in other IDEs (Visual Studio)
- Issue is most noticeable when hovering cursor over toolbar elements and buttons

Attempted Fixes:
- PC reboot
- Fresh reinstall of latest release (1.86.0)
- Disabling all extensions
- Setting GPU Acceleration to enabled, disabled, or canvas

![vscode-flickering](https://github.com/microsoft/vscode/assets/81829523/58e81571-863c-412a-ac6b-fc326d9bef37)

The flickering is even more rapid than appears in the gif, due to screen capture frame rate limitations

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900KF (32 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (13.90GB free)|
|Process Argv|C:\\Users\\Vince\\git\\test --crash-reporter-id c03306be-44bf-46b9-abe2-e3964cd58802|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
0bi6i642:30951795
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
b5d27386:30958190
3ef8e399:30949928
e3gdj431:30956216

```

</details>

**Comment by deepak1556** [comment]
> Setting GPU Acceleration to enabled, disabled, or canvas

Can you clarify the setting used ?

**Comment by StarryBlue7** [comment]
> > Setting GPU Acceleration to enabled, disabled, or canvas
> 
> Can you clarify the setting used ?

I followed your suggestion [here](https://github.com/microsoft/vscode/issues/204459#issuecomment-1929131536) to use `code --disable-gpu`, as well as changing the Terminal > Integrated: Gpu Acceleration setting in case it was somehow related, none of which appeared to fix the issue.

**Comment by deepak1556** [comment]
Can you try with the setting mentioned in https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

> as well as changing the Terminal > Integrated: Gpu Acceleration setting in case it was somehow related

This would be unrelated in this case, it only impacts the rendering backend used for the terminal.

**Comment by StarryBlue7** [comment]
> Can you try with the setting mentioned in https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

This did solve the issue, thanks!
