### ISSUE TITLE
very slow with notebook with new version 1.86 compared to 1.85.2

### ISSUE THREAD

**Issue by yongnuan** [microsoft/vscode#204515]
Type: <b>Bug</b>

> Issue troubleshooting has identified that the issue is with Visual Studio Code. 

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|64.00GB (55.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>Extensions: none

**Comment by FayzulSaimun** [comment]
Facing the same issue with the new version. Also, high CPU uses in this version.

**Comment by RinseL** [comment]
Same here with 1.86.0 version. 

Version: 1.86.0 (user setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by yongnuan** [comment]
And Use High CPU as well. The windows are always not responding. Could you please fix the bug ASAP? Also at this moment, how to downgrade to version 1.85.2? Thanks

**Comment by leviska** [comment]
+1 here, got up to 80% cpu peak usage on idle, rolling back reduced that basically to 0

**Comment by yongnuan** [comment]
> +1 here, got up to 80% cpu peak usage on idle, rolling back reduced that basically to 0

Thanks how to roll back to previous version?

**Comment by leviska** [comment]
It depends on what OS you are and how you've installed it, I'm on linux, so I've used old version from AUR

**Comment by FayzulSaimun** [comment]
> > +1 here, got up to 80% cpu peak usage on idle, rolling back reduced that basically to 0
> 
> Thanks how to roll back to previous version?

Download From here: https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions

**Comment by FayzulSaimun** [comment]
I rolled back to version 1.85.2 and the previous Jupyter version; it's now working fine.

**Comment by rodders99** [comment]
Same issue here with 1.86.0, startup after sleep it's very laggy, restart code and it's ok for a few minutes but performance degrades quite quickly after that. 

I downgraded to 1.85.2 and it's back to normal.

**Comment by leviska** [comment]
Was this issue fixed, or is it still present at newer versions?

**Comment by rodders99** [comment]
Appears to have been fixed. thanks

**Comment by yongnuan** [comment]
Yes Don, it has been fixed, it is way much faster now. I am really pleased. I tried to let you know but cannot find the original ticket. I really appreciate your help. That is really awesome. Sent from my iPhoneOn Jul 11, 2024, at 7:31 AM, Iskandarov Lev ***@***.***> wrote:﻿
Was this issue fixed, or is it still present at newer versions?
