### ISSUE TITLE
Remove warning if terminal no longer needs to be relaunched based on environment change

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#204502]
When auto-activation activates an environment (using the env variables VS Code API) we get the warning on the terminal that it should be relaunched. If a user manually activates that environment in the terminal, is it possible to detect that the terminal was activated? i.e., is there a way to compare the env variables and remove the warning?

**Comment by meganrogge** [comment]
We'd have to track env changes and I don't think that's possible

**Comment by Tyriar** [comment]
Yes I don't think this is possible. On Linux only there is a way to get to a process environment but last I tried using it there were a bunch of permissions problems and it wasn't on all distros.
