### ISSUE TITLE
Monokai Dimmed theme: LESS syntax highlighting colors very different in v1.86.0

### ISSUE THREAD

**Issue by moloko** [microsoft/vscode#204509]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.0
- OS Version: macOS 14.2.1

Steps to Reproduce:

1. Select the Monokai Dimmed theme
2. Open a .less file
3. Note that the syntax higlighting colors are very different to the previous release

This is what the less syntax highlighting looked like in v1.85.2 with the Monokai Dimmed theme enabled:
![vsc-less-1-85-2](https://github.com/microsoft/vscode/assets/1249597/ae8dc59f-8842-4a49-80ba-99e1f76ff075)

And this is what it looks like in 1.86.0:
![vsc-less-1-86-0](https://github.com/microsoft/vscode/assets/1249597/fe4951cc-bcd5-4778-bbbc-cb9b4db35985)

The main problem is that property names are now the same color as property values that are keywords - e.g. `hidden`, `flex` & `auto` - but it's also a bit annoying that LESS variables are no longer a uniform color.

I've checked a few other color themes and they don't seem to have this problem.

This is a bit of a guess but maybe Monokai Dimmed needs to be updated following the changes introduced in #200043 ?

**Comment by aeschli** [comment]
Yes, agree, this needs an update here: https://github.com/microsoft/vscode/blob/7c16d665f9be688f6e7528b3c1a066a09b86e11f/extensions/theme-monokai-dimmed/themes/dimmed-monokai-color-theme.json#L377
