### ISSUE TITLE
Remote SSH v0.108.0 is not compatible with VSCode 1.85.2 (needed for temporary fix for SSH workaround)

### ISSUE THREAD

**Issue by tbody-cfs** [microsoft/vscode#204500]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.2
- OS Version: MacOS 14.3

Steps to Reproduce:

1. Due to https://github.com/microsoft/vscode/issues/#203375 and https://github.com/microsoft/vscode/issues/##203967, I have downgraded VSCode to 1.85.2 to continue using Remote - SSH on a remote development server. This workaround allowed me to continue development work while waiting for the recovery release (https://github.com/microsoft/vscode/issues/202950).
2. Today, I can no longer connect to my development machine because the Remote - SSH extension (v0.108.0) is marked as "Extension is not compatible with Code 1.85.2. Extension requires: ^1.86.0."

Is it possible to roll back or pin the Remote - SSH extension until the recovery release is ready?

Likely duplicate of: https://github.com/microsoft/vscode-remote-release/issues/9496 (unclear whether the fix is in VSCode itself or the extension).

Context: I am a physicist running scientific software locally on my Mac as well as on AWS. VSCode is vitally important to my work, for Jupyter notebooks, as an IDE, and for enabling development and running Jupyter analysis notebooks directly on a cluster. Thanks for developing such a great product: VSCode has dramatically accelerated how quickly I can develop, debug and analyse simulations 💯

**Comment by gjsjohnmurray** [comment]
The gearwheel menu for an extension in Extensions view usually offers an option for installation of other versions.
