### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 minutes infinite loop

### ISSUE THREAD

**Issue by mtburkett** [Microsoft/vscode#20450]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.Open a js file from any SharePoint document library in explorer view.

**Comment by mjbvz** [comment]
Opening a network drive directly should be fixed in VSCode 1.9.1, see https://github.com/Microsoft/TypeScript/issues/13874

If you're using a mapped network drive, you may still hit this. We're tracking that issue here: https://github.com/Microsoft/TypeScript/issues/13997
