### ISSUE TITLE
Multi-cursor find not working with regex

### ISSUE THREAD

**Issue by jpokrzyk** [Microsoft/vscode#20451]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.2|
|beautify|HookyQR|0.7.3|
|alignment|annsk|0.3.0|
|npm-intellisense|christian-kohler|1.2.1|
|path-intellisense|christian-kohler|1.2.0|
|prettier-vscode|esbenp|0.8.0|
|git-project-manager|felipecaputo|1.0.1|
|auto-close-tag|formulahendry|0.3.9|
|auto-rename-tag|formulahendry|0.0.11|
|debugger-for-chrome|msjsdiag|2.5.3|
|java|redhat|0.0.10|
|vscode-react-native|vsmobile|0.2.5|

---

Steps to Reproduce:

1. Open a document with more than one line
2. Open find dialog (COMMAND+F)
3. Turn on regex find if it isn't already (COMMAND+OPTION+R)
4. Search for ^. You should now have any many find results as lines
5. Multi-cursor select (COMMAND+SHIFT+L)

I would expect as many cursors as I have lines. I only get one cursor though. 

Works as expected without the regex. If I just have 10 lines with the word start at the beginning of each line and I follow the above steps and search for 'start' I get 10 cursors.

I would also prefer COMMAND+SHIFT+L changes focus to the editor instead of the remaining on the find dialog. But that's more of an enhancement request.

**Comment by roblourens** [comment]
You are looking for 'alt+enter', not cmd+shift+L. See #20453.

**Comment by jpokrzyk** [comment]
Thanks. That's exactly what I wanted. 

There isn't a ton of space for an extra button in that find dialog. But I think adding a button per #20453 is probably your best bet. I obviously looked for the command but still had trouble getting to the right one.
