### ISSUE TITLE
"Surround with snippet" command is gone

### ISSUE THREAD

**Issue by josephgarnier** [microsoft/vscode#204506]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: 1.86.0
- OS Version: Linux Mint 21.3 and Windows 10

Steps to Reproduce:

1. Launch VS Code without extension : `code --disable-extensions`.
2. Create a new file (with markdown extension, for example).
3. Write a word and highlights it.
4. In Command Palette, try to find `Surround With Snippet` :( (more details [in VS Code documentation](https://code.visualstudio.com/updates/v1_65#_surround-with-snippet)).

This bug **appeared with the January update** and was found on 3 different computers (2 on Windows, 1 on Linux).

**Comment by jrieken** [comment]
@josephgarnier good catch, this regressed with 29a66313930a6689b47ff1bc45f5401b7ec90db6 (fyi @justschen)

There is a workaround because the action is still there but got renamed confusingly. It's new name is "More..."

**Comment by justschen** [comment]
ah good catch. will address this in recovery 2 potentially.

with the naming, I think we discussed having it as `More...` as opposed to having the full `Surround with Snippet...` 

however, I understand it can be confusing. maybe having it be `Snippet...` instead?

**Comment by jrieken** [comment]
> with the naming, I think we discussed having it as More... as opposed to having the full Surround with Snippet...

Using "More..." in the code actions menu makes sense, but for the command palette the full name "Surround with Snippet..." should be shown

**Comment by aiday-mar** [comment]
Issue is assigned to the recovery 2 milestone, temporarily. If it is not merged during recovery because no other candidates appear, milestone should be changed to February 2024.

**Comment by jrieken** [comment]
also https://github.com/microsoft/vscode/pull/204587 fixes this for next insiders

**Comment by aiday-mar** [comment]
Issue is closed because fix has been merged into release and main
