### ISSUE TITLE
Move to next line on comment (via key-command).

### ISSUE THREAD

**Issue by G-Rath** [Microsoft/vscode#20452]
Feature Request:

When using the comment key-command (default ctrl+/), I would like to have the caret move to the next line. 

This is a feature seen in the IDEA IDE (IntelliJ and family), and is very useful for quickly commenting and uncommenting lines of code without the mouse. 

This would work well as a setting.

**Comment by Tyriar** [comment]
You should be able to make an extension that does this fairly easily.
