### ISSUE TITLE
originSelectionRange not work while targetting non-text file

### ISSUE THREAD

**Issue by neko-para** [microsoft/vscode#204577]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.0
- OS Version: MacOS 14.3 Intel

Steps to Reproduce:

1. Create a `DefinitionProvider` that returns a `LocationLink` with `targetUri` set to uri of an image and `originSelectionRange` set to range of multiple word.
2. Check the behavior of vscode -> goto definitio works, but underline not shown up.
3. Change the `targetUri` to uri of an text file.
4. Check the behavior of vscode -> underline shown properly.

**Comment by neko-para** [comment]
[repository](https://github.com/neko-para/maa-support)
[source](https://github.com/neko-para/maa-support/blob/d067c165b6de3d1283b79f976d15ef7559a896d0/src/pipeline.ts#L165)

**Comment by neko-para** [comment]
I'm not sure whats the best practice of providing a definition to non-text file. GPT4 tells me that non-text files don't have concepts of row or column and just set the target position to (0, 0), which does work properly.

**Comment by neko-para** [comment]
Sorry to bother, but then what's the best practice to allow user jumping to non-text file from text file, e.g. a path to an image?

**Comment by jrieken** [comment]
Yeah, doc link seems like a good fit
