### ISSUE TITLE
Issues with VSCode Typescript Updates

### ISSUE THREAD

**Issue by AlGantori** [Microsoft/vscode#20456]
when faced with this nagging complaint...

![index 25](https://cloud.githubusercontent.com/assets/11699920/22841888/246bf81c-ef88-11e6-8dea-a15ae35bc2a5.jpg)

## There is neither clear directions to fix the problem nor does VSCode offer to perform a fix

The user in my case wants to be notified if there is a conflict and the current project setting are not saying "ignore I have a custom path (revision) for this project".
So "Don't Check Again" does not appear to be an option for me, besides, it keeps re-surfacing after VSCode updates.

![question-man](https://cloud.githubusercontent.com/assets/11699920/22845335/feba9b6e-ef96-11e6-850e-f05f892f38da.png)

### "More Information" button points here
https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions

![index 26](https://cloud.githubusercontent.com/assets/11699920/22841952/5f49eb42-ef88-11e6-8a62-4eda45de1c13.jpg)

### "typescript.tsdk" is not working...

I  did specify "typescript.tsdk" but It does not get rid of the warning, nor do I know it is working and using my current project local copy for this project.
![question-man](https://cloud.githubusercontent.com/assets/11699920/22845335/feba9b6e-ef96-11e6-850e-f05f892f38da.png)

## It's not obvious where the "workspace settings" are

The should say File > Preferences > "WORKSPACE SETTINGS" tab.
Or simply say open your current project .vcode/settings.json file 
![index 28](https://cloud.githubusercontent.com/assets/11699920/22841984/7e4d8206-ef88-11e6-828c-99fd0c1479fb.jpg)

### Should the path point to lib or bin ?
so is it
`
    , "typescript.tsdk": "./node_modules/typescript/lib"
`
or 
`
    , "typescript.tsdk": "./node_modules/typescript/bin"
`
![question-man](https://cloud.githubusercontent.com/assets/11699920/22845335/feba9b6e-ef96-11e6-850e-f05f892f38da.png)

## Where does VSCode store it's copy of TypeScript and how to find out what version it is?

If "global" version of tsc is 2.14 where did VSCode language service 2.1.6 get installed?
From the VSCode complaints/warning above there is a typescript 2.1.6 somewhere???

![question-man](https://cloud.githubusercontent.com/assets/11699920/22845335/feba9b6e-ef96-11e6-850e-f05f892f38da.png)

## Which version(s) of TypeScript are installed NPM Globally?
You can find the TypeScript installation location globally using  
```
npm list -g typescript
```
![index 27](https://cloud.githubusercontent.com/assets/11699920/22842001/8d824eb4-ef88-11e6-878d-d23d74d344ff.jpg)

## Which version(s) of TypeScript are installed NPM locally?
```
npm list typescript
```
![index 29](https://cloud.githubusercontent.com/assets/11699920/22842086/c987a1ca-ef88-11e6-8d50-6df4cc53ee76.jpg)

Please fix these annoyances.
 Thank you.

**Comment by AlGantori** [comment]
Hello Matt, @mjbvz could you explain what am I expected to do when I get this notification?  Thank you.

**Comment by mjbvz** [comment]
Sorry for the delayed response. The questionable clipart distracted me :)

See this answer on stackoverflow: http://stackoverflow.com/questions/42407569/how-do-i-upgrade-typescript-in-visual-studio-code-version-1-9-1/42429641#42429641 

VSCode 1.10 changes when this warning will be shown. Please try it out once it is released and feel free to submit a PR against the docs if the docs are unclear: https://github.com/Microsoft/vscode-docs
