### ISSUE TITLE
Performance Report

### ISSUE THREAD

**Issue by 304NotModified** [Microsoft/vscode#20454]
- VSCode Version: <code>Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)</code>
- Memory (System): <code>15.88GB (10.58GB free)</code>
- Memory (Process): <code>147.13MB working set (148.64MB peak, 98.14MB private, 60.96MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|63|
|main|app.isReady => window.loadUrl()|359|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|1014|
|renderer|require(workbench.main.js)|1260|
|renderer|create extension host => extensions onReady()|1830|
|renderer|restore viewlet|0|
|renderer|restore editor view state|594|
|renderer|overall workbench load|1551|
|main + renderer|start => extensions ready|4768|
|main + renderer|start => workbench ready|4269|

---

Additional Steps to Reproduce (if any):

1. Start VS code from start menu

I find +4 seconds pretty slow for an empty workbench, or am I too impatient?

**Comment by 304NotModified** [comment]
related https://github.com/Microsoft/vscode/issues/15455

**Comment by bpasero** [comment]
Yes, pretty slow. Comparable to https://github.com/Microsoft/vscode/issues/19660 that is even slower (6 seconds). Thanks for reporting 👍

**Comment by bpasero** [comment]
@304NotModified does the timing change when you run without extensions? 
From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions`

**Comment by bpasero** [comment]
I am closing this and ask people that hit slow performance to run `code-insiders --prof-startup` (from our insiders build: http://code.visualstudio.com/Download#insiders) which now supports to run CPU profiles so that we can have a closer look. Running with this argument will guide you through the process of creating a performance report here.
