### ISSUE TITLE
Second VSCode window is always blank

### ISSUE THREAD

**Issue by stlaz** [microsoft/vscode#204597]
Type: <b>Bug</b>

Reproducible:
Both in the latest stable version and the latest insiders build.

Reproducer:
1. start VSCode with `code --enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform=wayland` on a Linux system running a Wayland Window Manager such as `sway`
2. attempt to open a new window either via Ctrl+Shift+N or the "File" menu

Actual results:
Blank window with a dark stripe on the left and purple stripe at the bottom (will depend on theme used, I'll attach a screenshot).

Expected results:
A second window with VS Code editor that you can use to do stuff.

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:27:46.147Z)
OS version: Linux x64 6.7.4-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|30.55GB (21.63GB free)|
|Process Argv|--enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform=wayland|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|sway|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.20
copilot|Git|1.157.0
copilot-chat|Git|0.12.0
vscode-pull-request-github|Git|0.80.0
go|gol|0.40.3
debugpy|ms-|2024.0.0
vsliveshare|ms-|1.0.5905
gitblame|wad|10.9.0
vscode-todo-highlight|way|1.0.5

(2 theme extensions excluded)

</details>

Screenshot:

![20240207_14h01m27s_grim](https://github.com/microsoft/vscode/assets/718169/33727dff-a537-4a89-b1b0-7443505a0e93)

**Comment by stlaz** [comment]
Update: looks like the broken window is unable to repaint itself. When I attempt to move it to fullscreen via system keyboard shortcut, it keeps its current form and the rest of the screen is just filled with black color.

See the attached screenshot.
![20240222_09h40m14s_grim](https://github.com/microsoft/vscode/assets/718169/6ae6418e-4c24-4222-bfe4-5f069cdb47d6)

@sbatten please let me know if you need any more information.

**Comment by miXwui** [comment]
Chiming in that I'm experiencing the same issue. IIRC I finally defaulted VSCode to Wayland a few weeks ago since I was no longer experiencing any issues, but I guess there's a regression with the latest update.

Working fine as usual without Wayland (Fedora 39/SwayWM), and I'd be happy to take a deeper look/provide more information as well.

**Comment by hashworks** [comment]
Same here, even without extensions and a fresh user data directory. Adding `--disable-gpu` fixes the problem.

Verbose log with issue: `code --ozone-platform-hint=auto --verbose --wait -n --disable-extensions --user-data-dir /tmp/code-test` https://fb.hash.works/fGyNsB/ (new window opens in line 283)

Verbose log without issue: `code --ozone-platform-hint=auto --verbose --wait -n --disable-extensions --user-data-dir /tmp/code-test --disable-gpu` https://fb.hash.works/BM7cChfE/ (new window opens in line 267)

**Comment by hashworks** [comment]
It looks like sway 1.10 (commit 07b0598) and wlroots 0.18.0 (51c1e4aed) fixes this issue.

**Comment by stlaz** [comment]
I can confirm now that the latest stable version available on Arch (1:1.9-1) has fixed the problem.
