### ISSUE TITLE
Completion does not work with instanceof operator (typescript)

### ISSUE THREAD

**Issue by ltearno** [Microsoft/vscode#2046]
With a typescript source file, when using the [type guarded type inference](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#type-guards), the auto completion does not work...

An example :

    if(myObj instanceof MyClass) {
        myObj.ab// hit Ctrl+Space, the autocompletion will not trigger but should propose members of MyClass
    }

Thanks !

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#6527
