### ISSUE TITLE
feature request: make a functional c++ extension

### ISSUE THREAD

**Issue by billgan1024** [microsoft/vscode#204649]
Please implement something that will allow people to compile simple c++ programs properly. And for the love of god, make it simple. 

Right now we have a buggy mess called https://learn.microsoft.com/en-us/visualstudio/ide/reference/command-prompt-powershell?view=vs-2022. It takes like 5 seconds to start up a terminal, it's set to x86 by default, and AFAICT there's no way to save this environment inside vscode. Furthermore, we need to follow these convoluted steps to get c++ to work properly: https://code.visualstudio.com/docs/cpp/config-msvc. 
Finally, it doesn't work on windows 10. I'm getting random include and library errors, even after installing the Windows SDK and C++ development workload from VS.

**Comment by billgan1024** [comment]
![image](https://github.com/microsoft/vscode/assets/17630457/ba49db61-e991-46d8-99e5-6f070a3e54d3)

I literally have cl.exe and mspdbcore.dll in the same directory and this task still can't find it.
Here's the tasks.json:
`{
    "tasks": [
        {
            "label": "build",
            "type": "cppbuild",
            "command": "cl.exe",
            "args": [
                "/O2",
                "/Zi",
                "/std:c++20",
                "${file}",
                "/link",
                "d3d11.lib",
                "user32.lib"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "presentation": {
                "clear": true
            }
        }
    ],
    "version": "2.0.0"
}
`

I'm not saying this is evidence of vendor lock in. But it's getting pretty suspicious.

**Comment by lszomoru** [comment]
Thank you very much for your feedback. I would suggest that you engage with the team that owns the C++ extension by filing issues in their issue tracker - https://github.com/microsoft/vscode-cpptools/issues. Thank you!
