### ISSUE TITLE
Allow to pin an editor when saving explicitly

### ISSUE THREAD

**Issue by mherodev** [Microsoft/vscode#20466]
When a new tab is opened via fuzzy-finder, it's italic and will be replaced by another fuzzy-found tab unless changes are made to the file.

Is there a natural key command other than `space` > `backspace` for keeping a tab around (making it "sticky") when it was opened by fuzzy-finder?

And if not, how about `cmd`+`s` (saving) stickies a tab? (someone help me out with language, here) I believe Atom supports this behavior.

**Comment by bpasero** [comment]
@mherodev `{ "key": "cmd+k enter",  "command": "workbench.action.keepEditor" }` works

**Comment by mherodev** [comment]
Ah, right, they're editors and we're keepin' 'em.

Are there any objections to having save trigger the keepEditor behavior?

**Comment by bpasero** [comment]
@mherodev you mean even if the file is not dirty?

**Comment by mherodev** [comment]
@bpasero Yes. It's a behavior I'm used to from Atom, it seems good.

**Comment by bpasero** [comment]
**To verify**: a preview editor turns into a pinned editor when saving (`CtrCmd+S`).

**Comment by mherodev** [comment]
Thanks for the quick fix, @bpasero!
