### ISSUE TITLE
breakpoint

### ISSUE THREAD

**Issue by 1767083130** [Microsoft/vscode#20468]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.0.7|

---

Steps to Reproduce:
 cann't set debug breakpoint.

![bug](https://cloud.githubusercontent.com/assets/13881435/22852097/51661efe-f070-11e6-8691-ba0aa46db9ef.jpg)

**Comment by joaomoreno** [comment]
Your glyph margin appears hidden. Make sure `editor.glyphMargin` is set to `true`.
