### ISSUE TITLE
Installer rollback fails

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#20463]
vscode: 1.9 (I think it applies to many more versions)

When a new version is available, I want to upgrade to it. However, my development environment is shared by multiple people thus the installation may be blocked.

If I cancel the installation, the installer tries to rollback but vscode will still fail to start:
![image](https://cloud.githubusercontent.com/assets/3254987/22850724/9b17fd9a-efc3-11e6-9256-7430145a9159.png)

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Comment by unional** [comment]
I can understand that not many people have this issue because most people install vscode on their own machine.

Hopefully https://github.com/Microsoft/vscode/pull/38008 can address this and other issues (command line, window explorer context menu)
