### ISSUE TITLE
wait for breakpoint loading ....

### ISSUE THREAD

**Issue by tekumara** [microsoft/vscode#204699]
Type: <b>Bug</b>

Wait for Breakpoint is stuck on  `Loading...`

![CleanShot 2024-02-08 at 20 27 08@2x](https://github.com/microsoft/vscode/assets/125105/56e21a80-11fd-4266-b3c0-4029c9114bf3)

VS Code version: Code 1.86.0 (Universal) (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:15.765Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 7, 8|
|Memory (System)|32.00GB (0.40GB free)|
|Process Argv|--crash-reporter-id 1420092c-d4ca-4cab-85bb-af47402199b1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
acorn|Aco|0.7.0
vscode-sql-formatter|adp|1.4.4
TabOut|alb|0.2.2
tsl-problem-matcher|amo|0.6.2
indent-jump|aPi|1.0.1
ruff|cha|2024.10.0
vscode-markdownlint|Dav|0.54.0
vscode-eslint|dba|2.4.4
gitlens|eam|14.7.0
prettier-vscode|esb|10.1.0
hadolint|exi|1.1.2
shell-format|fox|7.2.5
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.80.0
go|gol|0.40.3
terraform|has|2.29.3
vscode-test-explorer|hbe|2.21.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
autoflake-extension|mik|1.0.4
black-formatter|ms-|2024.0.0
debugpy|ms-|2024.0.0
python|ms-|2024.0.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2024.1.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.338.1
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.8.22
remote-explorer|ms-|0.4.1
test-adapter-converter|ms-|0.1.9
vscode-marketplace-extension-browser|ms-|0.0.7
vsliveshare|ms-|1.0.5905
cuelang|nic|0.0.1
autodocstring|njp|0.6.1
excalidraw-editor|pom|3.7.2
vscode-yaml|red|1.14.0
rust-analyzer|rus|0.3.1831
cody-ai|sou|1.4.0
sourcery|sou|1.15.0
code-spell-checker|str|3.0.1
vscode-rust-test-adapter|Swe|0.11.0
even-better-toml|tam|0.19.2
typos-vscode|tek|0.1.12
tiltfile|til|0.0.3
shellcheck|tim|0.35.0
vscode-mermaid-editor|tom|0.19.1
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019bcf:30953938
3ef8e399:30949928

```

</details>

**Comment by gjsjohnmurray** [comment]
Please try `Start Extension Bisect` in case one of your extensions is the cause.

**Comment by gjsjohnmurray** [comment]
This probably need to be reported on that extension.

Are you debugging Python code when you get the problem?

**Comment by tekumara** [comment]
Yep this is python code

**Comment by tekumara** [comment]
Yep this is python code.. can this issue be moved there, or do I need to recreate it?

**Comment by gjsjohnmurray** [comment]
I suggest leaving it here for one of the VS Code team to move.

**Comment by gjsjohnmurray** [comment]
Pinging @connor4312 who steered PR #166202

**Comment by connor4312** [comment]
Are any of your breakpoints set in files that are inaccessible? That "Loading..." is shown while reading files where breakpoints are set in in order to show the line preview during selection.

**Comment by tekumara** [comment]
Seems to have resolved itself now but I'm not sure how ...

**Comment by connor4312** [comment]
It'd be nice to be able to load descriptions asnychronously, that would solve the issue or at least show what single breakpoint location is being slow to load

**Comment by alexr00** [comment]
@connor4312 what's the best way to verify this?

**Comment by connor4312** [comment]
I don't know of a way to verify this since it requires a breakpoint in a file on a filesystem that is very slow to read from. Probably just have to code review it.

**Comment by amunger** [comment]
I can actually repro on stable in conjunction with a pylance perf issue. 
Does not repro on insiders
