### ISSUE TITLE
Option to persist/set the log level of a LogOutputChannel

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#204647]
I am currently migrating our custom logging mechanism to use VS Code's LogOutputChannel API.
I want to have some logging to aid debugging issues that may arise during activation.
Since they are too verbose, I want them to be debug or trace level log messages. However, I found the selection made with "Developer: Set Log Level..." doesn't persist, nor it's not possible to set log level of our channel until the extension is activated.

I tried `code --log=extension:trace -n` option, but it doesn't seem to work - when working in remote mode. And this is not an option for web-based IDE services like GH codespace. 

What do other extensions do to trace activities during activation? I am open to options other than LogOutputChannel API.

* How to repro:

  1) Choose "Developer: Set Log Level..."
  2) Select an extension's output channel and set log level to non-default. 
  3) Reload window, choose "Developer: Set Log Level..." to see whether previously selected log level is preserved

**Comment by gjsjohnmurray** [comment]
See also #194948

**Comment by hyangah** [comment]
Thanks @gjsjohnmurray I will close this in favor of #194948
