### ISSUE TITLE
Offer a service method to install or enable an extension

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#204615]
We have some use cases for a flow where an extension is not installed or disabled but a certain UI feature requires it:

https://github.com/microsoft/vscode/blob/dc8a54d0a40dc8fa5aa7850950b118f47492e6bd/src/vs/workbench/contrib/debug/browser/variablesView.ts#L644-L658

Rather than building this in each case, would be nice to have a service method that:
* takes the identifier of an extension as input
* enables it if its disabled
* installs it if its not installed
* returns a promise I can await for when the extension has activated

**Comment by joaomoreno** [comment]
The current progress reporting for installing an extension (used by VS Code Speech) uses infinite progress:

![image](https://github.com/microsoft/vscode/assets/22350/27f6780e-141c-486b-a554-601197795ece)

It would be great if this supported showing concrete progress.

**Comment by bpasero** [comment]
@sandy081 this is also becoming interesting now for me from an extension point of view: the speech extension triggers extension install in this flow:

![voice-language](https://github.com/microsoft/vscode/assets/900690/b74b26e4-dbe8-444a-aacb-46e644e4b137)


Would be nice if the command would also take care of showing discrete progress if possible.

**Comment by sandy081** [comment]
@bpasero Are you expecting a command that can be invoked by your extension here?

**Comment by sandy081** [comment]
`workbench.extensions.installExtension` - yes this installs the extension. I think you wanted to wait until the extension is activated right?

**Comment by sandy081** [comment]
Enhanced `IExtensionsWorkbenchService.install` API to support above flow. This accepts following properties

```json
justification?: string | { reason: string; action: string };
// When enabled, the extension will be enabled if it is installed but disabled and waits until the extension is enabled.
enable?: boolean; 
```

When adopting in Voice chat action

![Image](https://github.com/microsoft/vscode/assets/10746682/c7c02ac0-3180-4dd0-b6cc-e26e7e6eebe0)

![Image](https://github.com/microsoft/vscode/assets/10746682/ee94d703-bca7-4aa4-a39a-23e454e8e966)

When adopting in Url Handler

![Image](https://github.com/microsoft/vscode/assets/10746682/fe6afa61-eb9f-41d3-8c64-9ddcc8dc3425)

Note that prompt is now consistent and shows
 
- Publisher of the extension that is being installed
- Action to Open extension 
- Option to Sync extension

We never had discrete progress for installing extension. Extensions view also show infinite progress. Hence this cannot be supported (or not scoped) in this issue.

![Image](https://github.com/microsoft/vscode/assets/10746682/fe94240e-0679-449d-a39b-811e1a6428fc)

**Comment by bpasero** [comment]
@sandy081 very cool! just to clarify: how can I benefit from this from my extension where I currently call `workbench.extensions.installExtension`?

**Comment by sandy081** [comment]
You can call the command by providing the justification like below. If you do not have any post install action, you can simply set justification as string.

https://github.com/microsoft/vscode/blob/d4a6faf8e0382c6cc6aff628d2d5494910a2c31d/src/vs/workbench/services/extensions/browser/extensionUrlHandler.ts#L240-L246

**Comment by bpasero** [comment]
This is adopted by the speech extension ✅
