### ISSUE TITLE
[Bug]: Confusing completion-text displayed in the terminal

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/vscode#204677]
Type: <b>Bug</b>

1. Launch any shell in any terminal.
2. Launch VSCode without any extensions enabled by `code --disable-extensions`.
3. Launch Windows Powershell in VSCode, make sure the Powershell Module `PSReadLine` is successfully imported.
4. Try any command (no matter if it's valid) with hyphen `-`, such as `Get-`.
5. Terminal will suddenly jump out massive JSON-like contents on the screen.
6. Keep invoking hyphen, annoying contents will refresh.

![recording](https://github.com/microsoft/vscode/assets/49941141/09b23ebd-34a9-4f3e-9e85-decd8d94d8e4)
![recording](https://github.com/microsoft/vscode/assets/49941141/b8be4c27-0454-490e-acc2-4e04586ac250)

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22631
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz (12 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (5.41GB free)|
|Process Argv|--crash-reporter-id 1950d8d7-cca7-49de-90de-e35f1ae02574|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (97)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
project-manager|ale|12.7.0
read-only-indicator|ale|3.9.0
jsonl|Alp|0.0.1
iFlyCode|Anh|2.1.0
vscode-zipfs|arc|3.0.0
vscode-django|bat|1.15.0
markdown-emoji|bie|0.3.0
vscode-fish|bma|1.0.38
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
gitignore|cod|0.9.0
doxdocgen|csc|1.4.0
transformer|dak|1.12.1
githistory|don|0.6.20
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
gitlens|eam|2024.2.704
EditorConfig|Edi|0.16.4
shell-format|fox|7.2.5
vscode-yarn|gam|2.1.0
viztracer-vscode|gao|0.2.3
codespaces|Git|1.16.10
remotehub|Git|0.63.2024010901
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.81.2024020709
vhs|gri|0.0.4
vscode-edit-csv|jan|0.8.3
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
intellij-idea-keybindings|k--|1.5.13
vsc-python-indent|Kev|1.18.0
vscode-leetcode|Lee|0.18.1
vscode-fix-checksums|leh|1.1.0
rainbow-csv|mec|3.11.0
vscode-docker|ms-|1.28.0
vscode-language-pack-zh-hans|MS-|1.85.2024020709
vscode-dotnet-runtime|ms-|2.0.1
vscode-edge-devtools|ms-|2.1.4
black-formatter|ms-|2024.1.10371008
debugpy|ms-|2024.1.10371006
flake8|ms-|2023.11.13551006
isort|ms-|2023.13.10231012
mypy-type-checker|ms-|2023.9.10221010
python|ms-|2024.1.10381007
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2024.1.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.341.0
remote-ssh|ms-|0.109.2024020215
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
azure-repos|ms-|0.38.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.19.2
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.13
js-debug-nightly|ms-|2024.2.517
makefile-tools|ms-|0.8.22
powershell|ms-|2024.0.0
remote-explorer|ms-|0.5.2024011009
remote-repositories|ms-|0.40.0
remote-server|ms-|1.6.2024012309
vscode-typescript-next|ms-|5.4.20240207
vsliveshare|ms-|1.0.5905
sqltools|mtx|0.28.1
sqltools-driver-sqlite|mtx|0.5.0
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.33.0
vscode-p3c|Rec|0.1.2
java|red|1.27.0
vscode-commons|red|0.0.6
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
sharecode|Rol|0.4.1
metals|sca|1.28.0
background|sha|1.2.13
even-better-toml|tam|0.19.2
xmake-vscode|tbo|2.2.9
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.56.0
vscode-java-dependency|vsc|0.23.4
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0
jinja|who|0.0.8
markdown-all-in-one|yzh|3.6.2
json|Zai|2.0.2
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
dsvsc019b:30953937
edj9j583:30958191
3ef8e399:30949928
e3gdj431:30958358

```

</details>

**Comment by Dragon1573** [comment]
Now I can't figure out if it's a bug, or it's a designed feature.

## Additional Information

I installed `Microsoft.Powershell` version 7.4.1 via `winget.exe`, and switched the default profile of VSCode to it. This issue will not happen again, and an IntelliSense-like auto-completion panel is shown when entering `Get-` as follows:

![image](https://github.com/microsoft/vscode/assets/49941141/c145c16d-c8d9-4b9d-86cf-c9b93ec7a8f6)

It seems the Windows bundled Powershell v5 does not support this kind of auto-completions, users of VSCode v1.87.0 should upgrade their instance to the latest Powershell v7.

**Comment by meganrogge** [comment]
I cannot reproduce this issue. 

I am also not sure how you're getting autocompletion, but that's not something we can install on behalf of our users. 

@Tyriar pls lmk if I'm missing something

**Comment by Dragon1573** [comment]
Contents of my `$PROFILE` are as follows:

```powershell
# Enable auto-completion by PSReadLine
Import-Module PSReadLine
Set-PSReadLineKeyHandler -Chord Tab -Function MenuComplete

# Enable full functionality of Git in Powershell
Import-Module posh-git

# Enable functionality of Gsudo
Import-Module "gsudoModule"
# Change prompt for indicating elevated shell
Set-Alias Prompt gsudoPrompt

# Register argument completions of Powershell
$scriptblock = {
    param($wordToComplete, $commandAst, $cursorPosition)
    $Env:_NEMOGUARDRAILS_COMPLETE = "complete_powershell"
    $Env:_TYPER_COMPLETE_ARGS = $commandAst.ToString()
    $Env:_TYPER_COMPLETE_WORD_TO_COMPLETE = $wordToComplete
    nemoguardrails | ForEach-Object {
        $commandArray = $_ -Split ":::"
        $command = $commandArray[0]
        $helpString = $commandArray[1]
        [System.Management.Automation.CompletionResult]::new(
            $command, $command, 'ParameterValue', $helpString)
    }
    $Env:_NEMOGUARDRAILS_COMPLETE = ""
    $Env:_TYPER_COMPLETE_ARGS = ""
    $Env:_TYPER_COMPLETE_WORD_TO_COMPLETE = ""
}
Register-ArgumentCompleter -Native -CommandName nemoguardrails -ScriptBlock $scriptblock
```

Installed and imported modules of Windows Powershell are:

```text
PS C:\Users\Administrator> Get-Module -All | Format-Table Name,Version,Path

Name                                         Version Path
----                                         ------- ----
gsudoModule                                  2.4.2   C:\Program Files\WindowsPowerShell\Modules\gsudoModule\gsudoModule.psm1
Microsoft.PowerShell.Commands.Management.dll 3.0.0.0 C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.PowerShell.Commands.Management\v4.0_3.0.0.0__31bf3856ad364e35...
Microsoft.PowerShell.Commands.Utility.dll    3.0.0.0 C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.PowerShell.Commands.Utility\v4.0_3.0.0.0__31bf3856ad364e35\Mi...
Microsoft.PowerShell.Management              3.1.0.0 C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management...
Microsoft.PowerShell.PSReadLine2             2.3.4.0 C:\Program Files\WindowsPowerShell\Modules\PSReadLine\2.3.4\Microsoft.PowerShell.PSReadLine2.dll
Microsoft.PowerShell.Utility                 0.0     C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psm1
Microsoft.PowerShell.Utility                 3.1.0.0 C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1
posh-git                                     1.1.0   C:\Program Files\WindowsPowerShell\Modules\posh-git\1.1.0\posh-git.psm1
PSReadLine                                   2.3.4   C:\Program Files\WindowsPowerShell\Modules\PSReadLine\2.3.4\PSReadLine.psm1
```

**Comment by Dragon1573** [comment]
That auto-completions seems provided by VSCode instead of by PSReadLine 😕

**Comment by Tyriar** [comment]
You must have the `"terminal.integrated.shellIntegration.suggestEnabled"` setting enabled, this is a WIP experimental feature.

**Comment by Dragon1573** [comment]
Thank you for the tips.  I'll check later to see if I enabled these experimental features. :heart:

**Comment by Dragon1573** [comment]
Yes, I did enabled this feature. It based on `terminal.integrated.shellIntegration.enabled` setting, which only supports on the following shell.

- Linux/macOS: `bash`, `fish`, `pwsh`, `zsh`
- Windows: `pwsh`

Upgrade my shell from _Windows Powershell 5_ to _Powershell Core 7_ can solve this problem.
