### ISSUE TITLE
New Windows close on remote connection reset

### ISSUE THREAD

**Issue by JimKleck** [microsoft/vscode#204675]
If I have files open in separate windows (i.e. "Copy into New Window") while I am working on a remote SSH host, and the connection gets lost or I need to reconnect for some reason then the new windows are lost when I reconnect. Since the original window retains its status (what files are open in which editor pane in the windw, it seem slike the new windows should also be restored.

**Comment by bpasero** [comment]
What version of VS Code are you trying, is it latest? We only recently added support to restore floating windows.
