### ISSUE TITLE
Dynamic Editor Font Zoom

### ISSUE THREAD

**Issue by unjx** [Microsoft/vscode#20465]
I would like to submit a feature request to hold down the Ctrl key and use the mouse wheel to zoom text size in and out. Basically this would bind Ctrl + Mouse Wheel to dynamically set "editor.fontsize". Please refer to Sublime Text, Atom, or NotePad++ for functional demonstration.

This text-zoom feature should NOT change the size of Visual Studio Code's menu, left side menu, or other UI elements that currently do scale when performing Ctrl + , and Ctrl -
It should only scale the font size in the editor window.

**Comment by alexandrudima** [comment]
This functionality already exists. It can be enabled via `editor.mouseWheelZoom`:

```
  // Zoom the font of the editor when using mouse wheel and holding Ctrl
  "editor.mouseWheelZoom": false,
```

**Comment by thorizer** [comment]
I think it should be enabled by default though.

**Comment by unjx** [comment]
@thorizer I agree. It would be more intuitive. Thank you @alexandrudima for the training 👍
