### ISSUE TITLE
"Move to file" looses focus

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#204606]
* have a typescript file
* select some code
* from the lightbulb select the "Move to file" refactoring
* :bug: QP opens but editors stays in (or moves back to) the editor

**Comment by TylerLeonhardt** [comment]
This is caused by:
https://github.com/microsoft/vscode/commit/4e67ba102b8adf31171195d9810b7e18f8e0975d 


maybe the lightbulb hide, puts focus back in the editor ... or something getting disposed does that.
leaving assignment to @justschen
