### ISSUE TITLE
Integrated terminal doesn't scroll up when selecting text

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/vscode#20462]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.7.3|
|swift|Kasik96|0.0.2|
|python|donjayamanne|0.5.5|
|vscode-lua|gccfeli|0.1.2|
|CSSfmt|ilich8086|0.0.3|
|Go|lukehoban|0.6.53|
|HTMLHint|mkaufman|0.3.0|
|prettify-json|mohsen1|0.0.3|

---

Steps to Reproduce:

1. ls -1c
2. do it on a folder containing large number of files, and try to select the complete text, it is not possible, the terminal should scroll up as we select, but it doesn't!

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/6755
