### ISSUE TITLE
VirtualEnv Environment Variables no longer honored when starting with 'code .' from terminal

### ISSUE THREAD

**Issue by Spareo** [Microsoft/vscode#20461]
- VSCode Version: 1.9.1
- OS Version: OSX 10.12.3

Description of Issue:
Matplotlib does not inherently work with VSCode debugger and Virtual Env. A runtime error occurs that states Python is not installed as a framework. A solution to this problem is provided [here](http://matplotlib.org/2.0.0b4/faq/osx_framework.html). The solution relies on the `code .` operator loading the environment variables from that virtual env. Up until 1.9.1 this worked just fine. 

I rolled back to 1.8 to make sure I wasn't crazy and indeed it still works. In 1.8 I was able to load my folder into vs code from terminal using `code .` and modify my launch.json to include 
```           
 "osx": {
    "pythonPath": "frameworkpython"
 }
```

with this modification I could easily use  Matplotlib. Immediately after updating to 1.9.1 I have now provide the full path to the `frameworkpython` file which tells me that the environment variables from the Virtual Env that I am using are no longer being honored in VS Code

**Comment by Tyriar** [comment]
The env only reloads from the terminal it was launched from when there are no other VS Code windows opened. Could you have had another instance opened?

**Comment by Spareo** [comment]
No I closed down VS Code completely and retried several times to be sure. I then went and downgraded to 1.8 and it worked immediately.

**Comment by Spareo** [comment]
Its possible that my terminal instance was causing the issue some how but that wouldn't explain why 1.8 worked. I can try rebooting my machine and seeing if it still happens again tomorrow.

**Comment by Spareo** [comment]
Closing the issue, it worked after a reboot.
