### ISSUE TITLE
Copilot integration is broken

### ISSUE THREAD

**Issue by mikekistler** [microsoft/vscode#204735]
Type: <b>Bug</b>

The Copilot chat window displays a message "Sign in with GitHub to use Copilot, your AI pair programmer" and a "Sign In" button. But the Sign In button does nothing. Choosing "Sign in with GitHub for Copilot" from the command palate, it just puts me into the chat window. The Copilot status that shows from the status bar says "ready", but the chat window is completely non-functional.

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:57.920Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.95GB free)|
|Process Argv|. --crash-reporter-id 419d896f-7e85-4c21-8845-5a77abdaec9d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.21.1
vscode-sidebar|Acr|1.2.3
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.54.0
vscode-eslint|dba|2.4.4
docs-article-templates|doc|1.0.3
docs-authoring-pack|doc|1.0.1
docs-build|doc|0.4.2
docs-images|doc|1.0.1
docs-linting|doc|0.0.13
docs-markdown|doc|1.0.3
docs-metadata|doc|1.0.9
docs-preview|doc|1.0.3
docs-scaffolding|doc|1.0.4
docs-yaml|doc|1.0.1
gitlens|eam|14.7.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
vscode-jest-runner|fir|0.4.72
copilot|Git|1.159.0
copilot-chat|Git|0.13.2024020201
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.80.0
go|gol|0.40.3
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.25.1
Ionide-fsharp|Ion|7.18.0
jq-syntax-highlighting|jq-|0.0.2
docomment|k--|1.0.0
Learn-Training-AI-Assistant|Lea|1.0.33
cadl-vscode|Mic|0.38.0
typespec-vscode|Mic|0.47.0
vscode-azurefunctions|ms-|1.13.3
vscode-azureresourcegroups|ms-|0.8.4
csdevkit|ms-|1.3.10
csharp|ms-|2.15.30
dotnet-interactive-vscode|ms-|1.0.5101020
vscode-dotnet-runtime|ms-|2.0.1
vscodeintellicode-csharp|ms-|0.1.26
playwright|ms-|1.0.21
debugpy|ms-|2024.0.0
isort|ms-|2023.10.1
python|ms-|2024.0.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2024.1.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.6
test-adapter-converter|ms-|0.1.9
vsliveshare|ms-|1.0.5905
java|red|1.27.0
vscode-yaml|red|1.14.0
spectral|sto|1.1.2
code-spell-checker|str|3.0.1
even-better-toml|tam|0.19.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22
vscode-java-debug|vsc|0.56.0
vscode-java-dependency|vsc|0.23.4
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019bcf:30953938
3ef8e399:30949928
bg6jg535:30958357
ccp2r6:30958158

```

</details>

**Comment by mikekistler** [comment]
FYI ... this has somehow fixed itself, so I no longer have an environment where this can be recreated/debugged.

I am fine with closing this issue as an anomaly if that's the best resolution.

**Comment by TylerLeonhardt** [comment]
Closing this out but don't hesitate to open a new issue if you see the same behavior!
