### ISSUE TITLE
Insert snippet command can only perform fuzzy search on snippet names < 60 characters

### ISSUE THREAD

**Issue by stephenkraemer** [microsoft/vscode#204757]
Type: <b>Bug</b>

I am not sure if this a feature request or a bug.

When I create Python snippets with a name longer than 60 characters, fuzzy search is disabled for these snippets.

Steps to reproduce

1. Go to Python snippets JSON file
2. Create a snippet with name: "a very long name which has more than sixty chars to trigger the problem"
3. Try to "Insert snippet" in a python file
4. The snippet can only be found when the search string matches the snippet name exactly, i.e. "a very long" will narrow the search result down to the snippet, while "avelo" will exclude the snippet from the search results.

In case this is the current behavior, I would like to make the case that in fields like data science, many people have large collections of snippets for generating different plots etc. Even in the age of Copilot, these remain useful :) To distinguish between many snippets, longer and descriptive titles are often very useful.

Thank you for considering this issue!

VS Code version: Code - Insiders 1.87.0-insider (ec291c126878742ad640055ce604a58129cd088c, 2024-02-05T05:46:48.601Z)
OS version: Linux x64 6.5.0-15-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 3757)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.34GB (6.19GB free)|
|Process Argv|--crash-reporter-id 7cb2c708-35ce-40c2-a5ee-5aa59d88c1f6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-neovim|asv|1.6.0
vscode-eslint|dba|2.4.4
copilot|Git|1.159.0
copilot-chat|Git|0.12.0
fuzzy-search|jac|0.0.3
black-formatter|ms-|2024.1.10371008
debugpy|ms-|2024.1.10371006
python|ms-|2024.1.10391007
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2024.2.2024020801
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
remote-ssh|ms-|0.109.2024020215
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.5.2024011009
remote-server|ms-|1.6.2024012309
my-vscode-utils|und|0.0.2
pyexec|und|0.0.1

</details>

**Comment by jrieken** [comment]
@TylerLeonhardt this seems to be an issue with QP and its default search/filtering

**Comment by jrieken** [comment]
@stephenkraemer For the time being you could use completions for this

<img width="632" alt="Screenshot 2024-02-09 at 15 19 46" src="https://github.com/microsoft/vscode/assets/1794099/7903b4d8-e5ae-48ad-9f89-b7bfcf1e957d">

**Comment by TylerLeonhardt** [comment]
Looks intentional... though that was 7 years ago!
https://github.com/microsoft/vscode/blob/f140bf63099aa782a08f983c95065f5ae92eb0bb/src/vs/base/common/filters.ts#L283

Let's move cautiously here as this code is used in a lot of places... first step, I'll go ahead and just trim the string to 60. This shouldn't impact perf much because we already said 60 is our limit.

In the future we can consider removing that check.
