### ISSUE TITLE
January 2024 Recovery 2

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#204723]
- [x] Create a milestone `<Month> <Year> Recovery <1|2|3>` **@aiday-mar**
- [x] Bump the version number **@aiday-mar**
- [x] [🔖candidate issues](https://github.com/issues?q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fmonaco-editor+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-anycode+repo%3Amicrosoft%2Fvscode-copilot+repo%3Amicrosoft%2Fvscode-copilot-release+repo%3Amicrosoft%2Fvscode-dev+repo%3Amicrosoft%2Fvscode-dev-chrome-launcher+repo%3Amicrosoft%2Fvscode-emmet-helper+repo%3Amicrosoft%2Fvscode-extension-telemetry+repo%3Amicrosoft%2Fvscode-github-issue-notebooks+repo%3Amicrosoft%2Fvscode-hexeditor+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-js-debug+repo%3Amicrosoft%2Fvscode-jupyter+repo%3Amicrosoft%2Fvscode-jupyter-internal+repo%3Amicrosoft%2Fvscode-l10n+repo%3Amicrosoft%2Fvscode-livepreview+repo%3Amicrosoft%2Fvscode-pull-request-github+repo%3Amicrosoft%2Fvscode-python+repo%3Amicrosoft%2Fvscode-python-debugger+repo%3Amicrosoft%2Fvscode-references-view+repo%3Amicrosoft%2Fvscode-remote-release+repo%3Amicrosoft%2Fvscode-remote-repositories-github+repo%3Amicrosoft%2Fvscode-remote-tunnels+repo%3Amicrosoft%2Fvscode-remotehub+repo%3Amicrosoft%2Fvscode-settings-sync-server+repo%3Amicrosoft%2Fvscode-unpkg+repo%3Amicrosoft%2Fvscode-vsce+milestone%3A%22December+%2F+January+2024+Recovery+2%22+)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `main`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **@aiday-mar**
- [x] Issues are verified on `stable` build and the `verified` label is added **@aiday-mar**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **@aiday-mar**
- [x] The `insiders` build with all candidate fixes needs to be in the wild for 24 hours before recovery release, unless explicitly approved by @kieferrm
- [x] Update the release notes and include a link to a query for the fixed issues **@ntrogh**
- [x] [Sanity Testing](https://github.com/microsoft/vscode/wiki/Sanity-Check)
  - [x] Windows 64 bit **@alexr00**
    - [x] System Installer
    - [x] User Installer
    - [x] Archive
    - [x] Server
    - [x] CLI
  - [x] Windows ARM64 **@lszomoru**
    - [x] System Installer
    - [x] User Installer
    - [x] Archive
    - [x] CLI
  - [x] macOS Intel **@isidorn**
    - [x] Archive
    - [x] Universal Archive
    - [x] Server
    - [x] CLI
  - [x] macOS ARM64 **@sandy081**
    - [x] Archive
    - [x] Universal Archive
    - [x] Server
    - [x] CLI
  - [x] Linux x64 **@bpasero**
    - [x] Archive
    - [x] DEB
    - [x] RPM
    - [x] Snap
  - [x] Linux Server **@chrmarti** _(can be tested from any OS with Docker)_
    - [x] x64
    - [x] ARM32
    - [x] ARM64
    - [x] x64 Alpine
    - [x] ARM64 Alpine
  - [x] Linux CLI **@deepak1556** _(can be tested from any OS with Docker)_
    - [x] x64
    - [x] ARM32
    - [x] ARM64
    - [x] x64 Alpine
    - [x] ARM64 Alpine
- [x] Publish website **@aiday-mar**
- [x] Publish stable build **@aiday-mar**
- [x] Create an official release **@aiday-mar**
  - [x] Create a tag (make sure you pull the release branch first): `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)
- [x] Close the milestone on [GitHub](https://github.com/microsoft/vscode/milestones) **@aiday-mar**

**Comment by gjsjohnmurray** [comment]
Please correct the milestone that the candidate link shows.

**Comment by aiday-mar** [comment]
Ah yes thank you for the reminder

**Comment by iAroc** [comment]
any news on these:
https://github.com/microsoft/vscode/issues/204073
https://github.com/microsoft/vscode/issues/204039
https://github.com/microsoft/vscode/issues/204110

there are more with it, its broken since over 2 weeks now _with no answer_, and having to stay forever on a lower vscode version isnt a good solution

**Comment by aiday-mar** [comment]
Hi @iAroc. I am not aware of the state of these issues. They should be discussed directly with the person responsible for them.

**Comment by iAroc** [comment]
> Hi @iAroc. I am not aware of the state of these issues. They should be discussed directly with the person responsible for them.

yes, i understand that it should be discussed with the person assigned to it. But what todo when one issue got closed without fixing it, and the other issue is just on the silent treatment. 

Its not like i have any other way todo anything except posting here and hope it will get fixed soon, so that i can actually update vscode and not being stuck on a old version since its a major break on the newer ones

**Comment by aiday-mar** [comment]
I can discuss the issue with the person responsible for it to find out the state of the issue. The person responsible is currently sleeping and it is expected he does not respond just yet.

**Comment by alumni** [comment]
I no longer see the staged/unstaged changes for a file (or for all files via the new "view changes" feature).

**Comment by aiday-mar** [comment]
Hi @alumni thank you for commenting. You may file a separate issue for this in the VS Code repo. This issue is for discussing the recovery release 1.86.2.
