### ISSUE TITLE
Width of horizontal scroll in terminal is hardcoded? 

### ISSUE THREAD

**Issue by thisismygitrepo** [microsoft/vscode#204787]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.86.1
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Enable horizontal scroll in terminal
2. print a dataframe that has very large number of columns (e.g. 60)

I managed to enable horizontal scrollbar in Terminal but it seems that there is no way to control how wide can we allow it to be. In my case its faliing me with tables that have 40 columns and this leads to line wrapping.

Thanks.

**Comment by meganrogge** [comment]
Hi you can toggle wrapping of the terminal by using alt+z

**Comment by thisismygitrepo** [comment]
@meganrogge  Yes.
