### ISSUE TITLE
Add Search in the outline view

### ISSUE THREAD

**Issue by cyborgdennett** [microsoft/vscode#204716]
Hi, I would like a feature where you can search in the outline tab.

Why I want this?
I work on large 3k loc c files
In this i want to search for functions with things in its name, it would be easier for me to do this in outline, so every occurrence is only once or twice.

How would it work?
Add a search bar when you press Ctrl+F in the outline view.

Thanks

**Comment by jrieken** [comment]
> Add a search bar when you press Ctrl+F in the outline view.

That is how it works.

**Comment by cyborgdennett** [comment]
Lol, im dumb sorry
