### ISSUE TITLE
Sign in for Copilot in WSL has problems

### ISSUE THREAD

**Issue by b1ackhawk-uh60** [microsoft/vscode#204759]
Type: <b>Bug</b>

When using copilot in VSCode in WSL, I'm frequently asked to sign in to github, notifications claim that sign in was has not completed. During the time when it is asking or attempting to sign in (takes several minutes) copilot does not work, but once notified that it was not able to log in and I need to finish authorising, it works. Which runs counter to the notifications. I haven't used outside of WSL that much, but it does seem to sign in appropriately. It seems that every new window also prompts to sign into github for copilot again. This is unexpected, unnecessary, redundant and aggrivating. 

VS Code version: Code - Insiders 1.87.0-insider (9db1b0571e119289a2264971bdac75793965e063, 2024-02-07T05:47:25.686Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.67GB (2.42GB free)|
|Process Argv|--crash-reporter-id aaa5550a-6e2f-4ad7-9334-c94df3149f71|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|Memory (System)|7.60GB (4.19GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|Memory (System)|7.60GB (4.19GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|Memory (System)|7.60GB (4.19GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|Memory (System)|7.60GB (4.19GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
theme-karyfoundation-themes|kar|34.4.0
jupyter-keymap|ms-|1.1.2
remote-wsl|ms-|0.86.0
gruvbox-material|sai|6.5.2
copilot|Git|1.158.0
copilot-chat|Git|0.12.0
terraform|has|2.29.3
git-graph|mhu|1.30.0
azure-pipelines|ms-|1.228.0
vscode-docker|ms-|1.28.0
azure-account|ms-|0.11.6
code-eol|soh|0.3.3

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:30784851
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialogc:30812479
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
pydisww1:30959800
d34g3935:30958346
edj9j583:30943796
fegfb526:30952798
7j2b6412:30951517
bg6jg535:30946824
ccp2r6:30958154

```

</details>

**Comment by b1ackhawk-uh60** [comment]
seems like that vscode was trying to open github in a webpage (which wasn't working). That has been resolved. However, I don't understand why/how copilot was working if it wasn't authenticated...

**Comment by TylerLeonhardt** [comment]
Hi @b1ackhawk-uh60 sounds like you're unblocked here now. Must have been a blip on GitHub's end. 

My guess is that what you were seeing was Copilot asking to you log in with a few additional permissions which allows for some faster searches and a few other features, but if that fails we fall back to a token that can't do as much but still can function.

Let us know if you see this issue in the future!
