### ISSUE TITLE
Issue with downloading extensions

### ISSUE THREAD

**Issue by Csinetron** [Microsoft/vscode#20479]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Go to Extensions
2. Search C/C++
3. Install the first one (from Microsoft)

It will show status "Installing" infinitely.

**Comment by joaomoreno** [comment]
Can you help us in #18103 ?
