### ISSUE TITLE
Output Channel API Incomplete for Language Servers

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#20477]
- VSCode Version: 1.9.1
- OS Version: Windows

I have a language server extension and I'd like to write logs.

My understanding is this:
1. The server recieves an IConnection object which has a console and a window. The window can show info/warning/error messages and the console can log to the chrome dev console, but neither offer access to output channels
2. The server can use a "normal" console.log (not the console from the IConnection object) which will manifest in the VS Code UI as an output channel with the name that the server was initialized with. However, there is no handle to the output channel available in the language server so it cannot be shown, for example when an error is logged.
3. The client can create an output channel and the server can route all logs to it as `requests`. Then all events that would need to open/close the channel also need to be manually routed to the client through `requests` or included as parameters in the log request. This seems like an unnecessary amount of boilerplate and indirection just to do basic logging.

Since it appears that an output channel is being created for the language server anyway as described in item 2, it should be exposed as part of the API and/or additional API functions should be added to support output channels in language servers

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/language-server-protocol#184
