### ISSUE TITLE
The Typescript language service died unexpectedly 5 times in the last 5 Minutes

### ISSUE THREAD

**Issue by vzhukov** [Microsoft/vscode#20471]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.7.0|
|angular-bootstrap|herrherrmann|4.0.6|
|sp-tools|Mike|0.3.0|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.9.0|
|debugger-for-chrome|msjsdiag|2.5.2|
|vs-code-office-ui-fabric|sivarajanraju|0.1.7|
|spremoteapi|SteveCurran|1.5.1|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1. Open folder in mapped network drive

**Comment by imfly** [comment]
Me too :cry:

**Comment by mjbvz** [comment]
We're tracking this issue on the TypeScript side ( https://github.com/Microsoft/TypeScript/issues/13997 ) and hopefully will have a fix for TS 2.2

Until then, to workaround this, try accessing the network store directly instead of mounting it.
