### ISSUE TITLE
Unable to restart debugging in VS Code 

### ISSUE THREAD

**Issue by shreyabatra4** [microsoft/vscode#204776]
I'm able to start debugging a C# based Azure Functions project. But I can't restart debugging or stop/start debugging again.

VSCODE:
Version: 1.84.1 (Universal)
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date: 2023-11-06T12:37:18.666Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

Azure Functions Core Tools
Core Tools Version: 4.0.5455 Commit hash: N/A (64-bit)
Function Runtime Version: 4.27.5.21554

Transferred from - https://github.com/Azure/azure-functions-core-tools/issues/3518

**Comment by roblourens** [comment]
Please file this on the C# debug extension, thanks
