### ISSUE TITLE
Environment variables from further VSCode instances are ignored

### ISSUE THREAD

**Issue by steffesto** [microsoft/vscode#204709]
Type: <b>Bug</b>

Start first instance of vscode and check the environment variables.
Start a second VSCode instance without a loader script that sets environment variables (e.g. vsdevcmd.bat from Visual Studio) before calling vscode. The environment variables loaded in the second instances are not present.
Expected result: the environment variables in the second instance are present.

It seems that VSCode doesn't create new processes for further instances.  With version 1.85 environment variables that were loaded in further instances are present in further instances also.

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1270P (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.58GB (13.79GB free)|
|Process Argv|--crash-reporter-id af62792b-aefa-4d89-b95d-9a0d04bdc809|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
tasks|act|0.16.0
docs-view|bie|0.1.0
vscode-markdownlint|Dav|0.54.0
gtest-adapter|Dav|1.8.3
xml|Dot|2.5.1
gitlens|eam|14.7.0
prettier-vscode|esb|10.1.0
vscode-codebeamer-integration|Fes|0.0.1
cmake-test-adapter|fre|0.17.2
html-preview-vscode|geo|0.2.5
gitlab-workflow|Git|3.101.1
todo-tree|Gru|0.0.226
vscode-test-explorer|hbe|2.21.1
plantuml|jeb|2.17.5
cmake-language-support-vscode|jos|0.0.9
cortex-debug|mar|1.12.1
vscode-catch2-test-adapter|mat|4.8.2
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.25
peripheral-viewer|mcu|1.4.6
rtos-views|mcu|0.0.7
git-graph|mhu|1.30.0
vscode-docker|ms-|1.28.0
vscode-dotnet-runtime|ms-|2.0.1
black-formatter|ms-|2024.0.0
debugpy|ms-|2024.0.0
pylint|ms-|2023.10.1
python|ms-|2024.0.1
vscode-pylance|ms-|2023.12.1
remote-containers|ms-|0.338.1
remote-wsl|ms-|0.86.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
powershell|ms-|2024.0.0
test-adapter-converter|ms-|0.1.9
vscode-markdown-plantuml-preview|mym|0.0.2
autodocstring|njp|0.6.1
vscode-cpptest|Par|2023.2.0
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
markdown-preview-enhanced|shd|0.8.11
gnu-mapfiles|tro|1.1.0
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
vscode-icons|vsc|12.7.0
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.6.2
linkerscript|Zix|1.0.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928
bg6jg535:30958357

```

</details>

**Comment by bpasero** [comment]
Steps?

**Comment by bpasero** [comment]
In your batch file, try passing `--preserve-env` to VS Code. Refs:

https://github.com/microsoft/vscode/blob/7215958b3c57945b49d3b70afdba7fb47319ca85/src/vs/platform/launch/electron-main/launchMainService.ts#L122-L133

**Comment by steffesto** [comment]
The steps are the following:
1. Start first instance of VSCode
2. check the environment variables in a terminal inside first VSCode instance using set command
3. start a second instance of VSCode from a batch file that sets some env variables before calling VSCode (e.g. call vsdevcmd.bat from Visual Studio to use compiler with CMake Tools)
4. check the environment variables in a terminal inside second VSCode instance using set command

Behaviour: The environment variables set before starting the second VSCode instance are not present.

Expected behaviour: The environment variables set before starting the second VSCode instance are present.

With version 1.85 VSCode behaves as expected.

I'm using Windows. Afaik, the --preserve-env parameter exists just on Linux.

Maybe there's another possibility to use the Visual Studio compiler within VSCode with the CMake Tools extension than calling the vsdevcmd.bat in a batch before calling VSCode, but i couldn't find one.

**Comment by bpasero** [comment]
@steffesto `--preserve-env` was added recently and is available on all OS, can you try please.

**Comment by steffesto** [comment]
`--preserve-env` does the trick! Thank you very much!

**Comment by steffesto** [comment]
By the way: do you know if there's a possibility to ignore environment variables in a second instance that were set in the first VSCode instance? So that only system and user environment variables are used in the second instance?
If vsdevcmd.bat was called in the first intsance the enviroment variables of vsdevcmd.bat are present in further instances also. This behaviour exists in all VSCode versions. This may be a common windows behaviour when starting new instances of an executable.
