### ISSUE TITLE
Branch quick pick should list exact match first

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#204733]
Type: <b>Bug</b>

1. In a repo with a branch: `abc/main` and `main`, where you have recently switched to `abc/main`
2. Open the branch selector and type `main`

**expected**
The exact branch name match is listed first

**actual**
![Image](https://github.com/microsoft/vscode/assets/12821956/c8394a17-36d6-462b-aca0-34f35de14482)

VS Code version: Code - Insiders 1.87.0-insider (Universal) (9db1b0571e119289a2264971bdac75793965e063, 2024-02-07T05:48:09.043Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|4, 4, 4|
|Memory (System)|64.00GB (1.01GB free)|
|Process Argv|--crash-reporter-id 0fffb5da-9cd7-46fd-9e7f-a1564e8c5fda|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by TylerLeonhardt** [comment]
This appears to be fixed:
![Image](https://github.com/microsoft/vscode/assets/2644648/2962eda1-4f4e-4d00-b30a-f206b38d5014)

I think this is from the branch picker using `sortByLabel: false`. Gonna assign to Lad since I didn't do anything here.
