### ISSUE TITLE
Extension bisect wipes out undo history

### ISSUE THREAD

**Issue by php4fan** [microsoft/vscode#204754]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.1
- OS Version: Manjaro Linux

Steps to Reproduce:

1. You are happily coding, so: Edit some file and make changes to it
2. You find some bug, so: Start an Extension bisection. When you're done, stop the bisection
3. Now go back to your coding: Try to undo some of the latest changes you did (either during the extension bisection or before that

=> BOOM! The undo history is completely gone!! You can't undo anything!

**Comment by sandy081** [comment]
I believe enabling/disabling extensions is nothing to do with this. 

@hediet I would suggest you to start investigating from the editor perspective and let me know if it involves extensions.

**Comment by hediet** [comment]
The editor history is not persisted during window reloads, which is required for extension bisect.

**Comment by php4fan** [comment]
> The editor history is not persisted during window reloads, which is required for extension bisect.

Well  that's ridiculous. Either persist the edit history during reloads, or make a reload not required for extension bisect.

The edit history is absolutely crucial to the work of a developer, and destroying it is an unacceptable disruption.
What do you expect the user to do when they find a bug while working?? Take note and then look into it later when they're done with  the current work? (as if there even was such a thing as "done") Do you really expect that users will take the time to report bugs then??
Or accept that if they do a bisection and report the bug, they will lose their edit history?

It's unbelievable that you don't understand how disruptive losing  the edit history is.

>  we are happy to listen and to reconsider.

Please reconsider, this is insane. 

AT THE VERY LEAST you should add an explicit warning about this and prompt for confirmation when starting an extension bisect.
