### ISSUE TITLE
VScode 1.86.1 does not open on linux

### ISSUE THREAD

**Issue by amirhosseindavoody** [microsoft/vscode#204796]
- VS Code Version: 1.86.1
- OS Version: OpenSuse12

Steps to Reproduce:

1. Download the vscode release 1.86.1 linux version as tar.gz file.
2. Extract the tar file
3. Launch vscode by executing `bin/code`
4. I get the following error message:
```
VScode_1_86_1/VSCode-linux-x64/bin/../code: /lib64/libdbus-1.so.3: no version information available (required by VScode_1_86_1/VSCode-linux-x64/bin/../code)
```

I know that there was some issues about VSCode 1.86.0 due to glibc compatibility, but according to [this comment](https://github.com/microsoft/vscode/issues/203375#issuecomment-1927893504), version 1.86.1 should be able to execute. But I am still seeing the same error after upgrading to 1.86.1.

**Comment by deepak1556** [comment]
We expect `libdbus-1-3 (>= 1.9.14)`, the error indicates your OS does not provide the required version. You can try the rpm package and it should show the missing dependencies. The issue https://github.com/microsoft/vscode/issues/203375#issuecomment-1927893504 is about our [remote server](https://code.visualstudio.com/docs/remote/vscode-server).

**Comment by amirhosseindavoody** [comment]
@deepak1556 Is this a new requirement by VSCode 1.86? I have been using the 1.85 version with no issues.

**Comment by deepak1556** [comment]
Yes, the requirement comes from the runtime which would be related to the Electron 27 [update](https://code.visualstudio.com/updates/v1_86#_electron-27-update)
