### ISSUE TITLE
Menus not working

### ISSUE THREAD

**Issue by 12michel34** [Microsoft/vscode#20474]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.15031
- Extensions:

|Extension|Author|Version|
|---|---|---|
|prettify-json|mohsen1|0.0.3|
|mssql|ms-mssql|0.2.1|
|csharp|ms-vscode|1.7.0|

Menus not working (Same issue in VS Code Insider)

Steps to Reproduce:

1.Open Vs Code
2.Try Opening Menu

**Comment by mbiebusch** [comment]
I have the same problem, nearly the same setup. The menus in e.g. Opera are not working either, so I guess the cause might be 15031.

**Comment by alexgwolff** [comment]
I have the same problem and I am also using build 15031

**Comment by joaomoreno** [comment]
Seems to be a Windows issue.
