### ISSUE TITLE
GPU process exited unexpectedly: exit_code=139

### ISSUE THREAD

**Issue by sf1nks** [microsoft/vscode#204798]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.0, 1.86.1
- OS Version: Arch Linux, 09.02.2024 last updates

Steps to Reproduce:

1. Update to version 1.86.0 or 1.86.1
2. Run from shortcut, or from console.
3. With --no-sandbox and --disable-gpu --disable-software-rasterizer too

Crushed with that logs:
[226522:0209/103230.913197:ERROR:gpu_process_host.cc(995)] GPU process exited unexpectedly: exit_code=139
[226522:0209/103230.913213:WARNING:gpu_process_host.cc(1364)] The GPU process has crashed 9 time(s)
[226522:0209/103230.913222:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.

**Comment by Kulasz** [comment]
I have the same issue on Ubuntu 22.04.3 with VS Code 1.86.1 but in my case it's exit_code=5
Tried `--disable-chromium-sandbox` and `--no-sandbox` and other as @sf1nks  but without success. Tried also run as sudo with `--user-data-dir` in /tmp also without success.

**Comment by ijtejedor** [comment]
Test with: --disable-accelerated-video-decode

**Comment by martin-kuenzel** [comment]
> Test with: --disable-accelerated-video-decode

Thank you. This solved the problem for me.
 
My problem though was not only VScode, but also signal-desktop and google-chrome on ubuntu with 6.6.1-060601-generic, so my guess would be, that it might be a problem with the underlying js engine. 

The parameter works for all of the aforementioned programs as well.

**Comment by sf1nks** [comment]
Thanks a lot! This solved the problem for me too. Change my .desktop file. Need to write post install hook to pacman.

**Comment by shreekadhikari** [comment]
I also faced the same issue with Google Chrome .deb version and vs code .deb and flatpak version.

- Google chrome worked with the `--disable-accelerated-video-decode` initially and later stopped working after update. So, I tired flatpak version, works fine without any extra arguments for now.
-  For vs code, after the .deb version stopped working, I installed flatpak. It worked fine for some time and started giving me the same issue. So, I again installed the .deb one and this time tired passing the same argument which worked and am currently using.
- There were solutions such as `--no-sandbox` or `--disable-gpu` which didn't work in my case
- Currently using VS Code 1.87.0 .deb with the argument and Chrome 122.0.6261.94-1 stable flatpak

**Comment by smarkoco** [comment]
Delete snap package, then reinstall apt package. Resolved

**Comment by louisbertrand** [comment]
> Delete snap package, install apt package. Resolved `snap remove code` `apt install code`
> 
> Neither any of these launch flags NOR updating the nvidia drivers on my machine did anything

apt does not have code (Ubuntu 22.04 LTS).

**Comment by smarkoco** [comment]
> > Delete snap package, install apt package. Resolved `snap remove code` `apt install code`
> > Neither any of these launch flags NOR updating the nvidia drivers on my machine did anything
> 
> apt does not have code (Ubuntu 22.04 LTS).

Ah, you're right, my bad, it looks like I had previously followed the instructions [here](https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions) to install the .deb file, which apparently automatically installs the repository and signing key
![image](https://github.com/microsoft/vscode/assets/53878603/f888a6ff-178a-459e-9eb5-45364f77896f)
![image](https://github.com/microsoft/vscode/assets/53878603/e8df4ad6-ee07-424c-8979-5fc3832c1785)
