### ISSUE TITLE
Terminal full screen shortcut or settings

### ISSUE THREAD

**Issue by MuhammadShakkeer2030** [microsoft/vscode#204717]
![Code_6IMUmftqlQ](https://github.com/microsoft/vscode/assets/121001685/023d9126-4e26-4c92-8faa-1df548977491)

![image](https://github.com/microsoft/vscode/assets/121001685/d5cf923c-fd92-4e95-b3b6-66a7bad09b80)

**Comment by meganrogge** [comment]
Hi there's no setting for this. You can open a terminal in a new window and size it to be full screen.

**Comment by MuhammadShakkeer2030** [comment]
ThankYou
