### ISSUE TITLE
Python Debugger Starts & Then Stops

### ISSUE THREAD

**Issue by iand66** [microsoft/vscode#204711]
Type: <b>Bug</b>

Create a new VSC project print('Hello World'), set breakpoint create clean launch.json "name": "Python Debugger: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
Run -> Start Debugging

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (24.80GB free)|
|Process Argv|--crash-reporter-id aeea62a1-79b1-42cf-aa36-17a31c2ec0d6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
todo-tree|Gru|0.0.226
rest-client|hum|0.25.1
debugpy|ms-|2024.0.0
isort|ms-|2023.10.1
python|ms-|2024.0.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2024.1.0
jupyter-renderers|ms-|1.0.17
sqlite-viewer|qwt|0.3.13
vscode-xml|red|0.26.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019bcf:30953938
d34g3935:30958340
b1063948:30958189
3ef8e399:30949928
e3gdj431:30958358

```

</details>

**Comment by gjsjohnmurray** [comment]
Did you set any breakpoints in the code you are debugging?

**Comment by iand66** [comment]
Yes. As per "set breakpoint" next to print('Hello World' FYI - Other projects work OK. So, copy & paste launch.json & settings.json into .vscode folder of new project - same result. Python Debug Console does not start in terminal window. Same result if reverting to 'python' back from 'debugpy'. Property trace: true not allowed in launch.json

**Comment by iand66** [comment]
Is there any feedback about this please?

**Comment by roblourens** [comment]
Please file this on the repo for the python extension, thanks. Some more detail might help, it's not exactly clear to me what the issue is.
