### ISSUE TITLE
vscode quits while closing devtools 

### ISSUE THREAD

**Issue by Vishal-Isharani** [Microsoft/vscode#20475]
- VSCode Version: 1.10.0-insider (latest insider)
- OS Version: windows 10

Steps to Reproduce:

1. open devtools 
2. do something in console like 1 + 2 
3. now try to close devtools 

instead of closing devtools vscode quits itself

**Comment by Vishal-Isharani** [comment]
also same behaviour on mac os

**Comment by joaomoreno** [comment]
Can you show us a screen recording?

If you execute it from the command line `code --verbose`, does it get any output when it exists?

**Comment by Vishal-Isharani** [comment]
@joaomoreno  some how new update on insiders fixed this issue but in stable it still persist 

VSCode Version: 1.9.1
OS Version: windows 10

https://drive.google.com/file/d/0B1i7s3X-7VMOV3VqN0FKb194QkE/view?usp=sharing

**Comment by joaomoreno** [comment]
This is electron/electron#6359. cc @bpasero
