### ISSUE TITLE
Add an option to install an extension into a workspace only

### ISSUE THREAD

**Issue by vadi2** [microsoft/vscode#204894]
Type: <b>Feature Request</b>

As a longtime vscode user, it is getting rather common for me to have many extensions installed and many different workspaces used for various projects in various toolstacks. However, my i5 Chromebook can only handle so much - the more extensions, the slower vscode runs. Thus, I need to be really selective about which extensions I enable. So my workflow is like this: install a new extension, and then go to the N many workspaces I have and disable it individually within each one. 

It would be great if it was possible to simply this by simply installing an extension into a specific workspace and that's it.

VS Code version: Code 1.86.1 (Universal) (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:09:01.236Z)
OS version: Darwin arm64 23.2.0
Modes:

**Comment by gjsjohnmurray** [comment]
Can't you already do this?

1. Install extension.
2. Disable it globally.
3. Enable it just for the workspace(s) you want to use it in.

**Comment by vadi2** [comment]
That's a good idea.
