### ISSUE TITLE
Using the Ctrl+Shift+C shortcut to open an external terminal in the current workspace folder prevents the command prompt from receiving signals.

### ISSUE THREAD

**Issue by LilrCoding** [microsoft/vscode#204866]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.1 (user setup)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Use the Ctrl+Shift+C shortcut to open an external cmd.
2. Run a continuous ping command, for example: ping google.com -t.
3. Try to stop the ping process by using the Ctrl+C shortcut.

Expected Behavior: The ping process should stop.

Actual Behavior: The command prompt does not respond to the Ctrl+C signal.

**Comment by meganrogge** [comment]
This is an issue with the external terminal, so not actionable by VS Code AFAICT.

**Comment by LilrCoding** [comment]
I haven't encountered this issue with previous versions. This behavior came after updating to version 1.86.1. Downgrading back to version 1.85.2 resolves the issue.

**Comment by LilrCoding** [comment]
@meganrogge I'm pretty sure this is a vs code issue
