### ISSUE TITLE
When using a Japanese input method and being word wrap turned on, display of overflown text corrupts.

### ISSUE THREAD

**Issue by avtomat2023** [microsoft/vscode#204816]
Type: <b>Bug</b>

How to reproduce:
1. Turn on word wrap by "View: Toggle Word Wrap" command.
2. Input text exceeding the length of the line using a Japanese input method.

https://github.com/microsoft/vscode/assets/6287627/c964d18c-72c6-428d-ba18-9ab183500386

When I input "ち", the end of line 129 should be "（もどり" and overflown "ち" should be shown in the next line. However, "（” in line 129 disappears, and "ち" is shown in both the end of line 129 and the next line.

VS Code version: Code - Insiders 1.87.0-insider (8fa84589eef3538dbc763ff98dc7d5a8a0c56374, 2024-02-09T05:47:15.236Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3493)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.88GB (10.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:30784851
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
pydisww1:30959800
b1063948:30943794
fegfb526:30952798
7j2b6412:30951517
e3gdj431:30946825
ccp2r3:30958153

```

</details>

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. I am able to reproduce this issue on macos. This issue should be fixed by the new experimental setting `editor.experimentalEditContextEnabled` (please reload after setting).
