### ISSUE TITLE
Give more information in authentication permission request dialog

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#204809]
Type: <b>Feature Request</b>

When an extension first asks to use credentials from an authentication provider we get this:

![image](https://github.com/microsoft/vscode/assets/6726799/242e00bc-1280-4fd2-a428-ba5396d68b19)

I would like to see a bit more information. For example:
- Extension ID
- Link/button that takes me to its details in Extensions view

VS Code version: Code - Insiders 1.87.0-insider (8fa84589eef3538dbc763ff98dc7d5a8a0c56374, 2024-02-09T05:47:15.236Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by TylerLeonhardt** [comment]
Workaround: use `silent:true` and then `forceNewSession:{ ... }`
