### ISSUE TITLE
Git Commit trying to spawn ssh?

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#2048]
In the Git section, I have my file that I just updated, and now I want to commit locally, I click the little check mark, and I get the little clock icon, and now I'm waiting forever. I check the log and have lots of this: 

git fetch
error: cannot spawn ssh: No such file or directory
fatal: unable to fork
git fetch
error: cannot spawn ssh: No such file or directory
fatal: unable to fork
git fetch
error: cannot spawn ssh: No such file or directory
fatal: unable to fork
git fetch
error: cannot spawn ssh: No such file or directory
fatal: unable to fork
git fetch

Maybe I don't understand the process, but when I want to commit locally, why would it do these other things? And now I'm waiting forever for it to release...restarting the app doesn't help. But it did commit the change locally, without telling me. 

This is on Windows 7...not sure what else might be needed to address this issue.

**Comment by joaomoreno** [comment]
`git fetch` is a background task that runs independently of the commit action.

So, to recap: you click **commit** and it stays spinning forever while actually committing successfully.

**Comment by rhires** [comment]
Yes. It commits locally successfully, but VSCode is waiting on git to do to other things I didn't ask git to do (intentionally, anyway).

**Comment by grafidi** [comment]
VSC tries to access my remote git repositories without my knowledge.

When I start it in a git directory, using "code .", I am prompted for my RSA key passphrase:
Enter passphrase for key '{home}/.ssh/id_rsa':
where {home} is my home directory.

If I search for 'ssh' in the process stack, I find:
ssh {host} git-upload-pack '{repo.git}'
where {host} and {repo.git} are the host and path of my remote origin git repository.

The first few times I ran it, I had already put my key to ssh-agent, so VSC quietly accessed my remote server without needing the passphrase.

I don't feel comfortable with VSC running ssh commands on my remote server, without my permission.  It should at least have a preference to turn this off.

VSC Linux X64 stable:
Version 0.10.11
Commit f291f4ad600767626b24a4b15816b04bee9a3049
Date 2016-03-11T16:19:03.130Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

**Comment by joaomoreno** [comment]
The setting `"git.autofetch": false` will disable this.
