### ISSUE TITLE
check-requirements.sh script fails on multi libc

### ISSUE THREAD

**Issue by y1rn** [microsoft/vscode#204802]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: code 1.86.1 (commit 31c37ee8f63491495ac49e43b8544550fbae4533)
- OS Version:  Linux arm 6.5.0-0.deb12.4-cloud-arm64

Steps to Reproduce:

1.  lookup libc show two paths
```
 ~ /sbin/ldconfig -p | grep 'libc.so.6'
        libc.so.6 (libc6,AArch64) => /lib/aarch64-linux-gnu/libc.so.6
        libc.so.6 (libc6,AArch64) => /lib/x86_64-linux-gnu/libc.so.6
```
2. run check-requirements.sh with comment `set -e` show 
```
cat: '': No such file or directory
Warning: Missing GLIBC >= 2.28! from 
Error: Missing required dependencies. Please refer to our FAQ https://aka.ms/vscode-remote/faq/old-linux for additional information.
```

**Comment by deepak1556** [comment]
/fixedWith https://github.com/microsoft/vscode/commit/f6a5654dbf9811b94dd8848571a84b73a7a34813
