### ISSUE TITLE
VS Code Speech interferes with Siri

### ISSUE THREAD

**Issue by bl-nero** [microsoft/vscode#204811]
Type: <b>Bug</b>

1. Set up Siri and make sure she responds to "Hey, Siri".
2. Launch VS Code with VS Code Speech installed.
3. Set accessibility.voice.keywordActivation to "chatInContext". (Probably anything other than "off" will do the trick.)
4. Say "Hey, Siri". Siri will not respond.

Extension version: 0.5.2024020710
VS Code version: Code 1.86.1 (Universal) (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:09:01.236Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 8, 12|
|Memory (System)|32.00GB (3.42GB free)|
|Process Argv|--crash-reporter-id 53d45e7c-1978-4b3c-af52-60f067ce37d4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30960370
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
3ef8e399:30949928

```

</details>

**Comment by bpasero** [comment]
Closing as upstream: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2265

**Comment by bpasero** [comment]
To improve this a bit on the VS Code side, keyword voice recognition will suspend when VS Code has no window focus.
