### ISSUE TITLE
Add words variables counter in editor

### ISSUE THREAD

**Issue by ManPython** [Microsoft/vscode#20489]
- [x] Add words variables counter in editor after selected word as variable, eg.:

1. data
2. data
3. data
4. data
5. **data**
6. data
7.
8. data

Words 5/7
 - it's usefull in refactoring (ctr+h as replace words)
 
![words_variables_counter](https://cloud.githubusercontent.com/assets/25403861/22858603/b9a0dd72-f0c2-11e6-831e-e1ef674f8214.png)

**Comment by joaomoreno** [comment]
This is a great extension idea. Maybe it already exists? https://marketplace.visualstudio.com/?VScode=1
