### ISSUE TITLE
Clicking on references (tree elements) in find-references view focuses on the tree container

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#204826]
Repro: 

1. Move an editor to a new window 
2. Find references on a symbol with multiple references (e.g., _list in suggestWidget.ts) and try clicking on references on the tree -- only some work

Can't repro without a separate window

https://github.com/microsoft/vscode/assets/16353531/c8d96f8d-b1fc-4610-8d02-1abff3ba4292

Version: 1.87.0-insider
Commit: bcf9b4ff0ff453a72d01f4bceaea05e166f347c6
Date: 2024-02-08T22:05:48.404Z
Electron: 27.3.1
ElectronBuildId: 26731440
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0

**Comment by jrieken** [comment]
I cannot reproduce this... @ulugbekna Do you still see this?

**Comment by ulugbekna** [comment]
can't repro
