### ISSUE TITLE
Regression since 1.86.0 on #190976 / #191131

### ISSUE THREAD

**Issue by aytey** [microsoft/vscode#204805]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: vscode_1.86.1 and code-insider-x64-1707457610
- OS Version: Linux

Steps to Reproduce:

1. Run the steps outlined in https://github.com/microsoft/vscode/issues/190976
2. Observe the behaviour is broken again

## Notes

I checked a few versions of VS Code for this:

* vscode_1.80.2 works
* vscode_1.81.1 broken
* vscode_1.82.3 works
* vscode_1.83.1 works
* vscode_1.84.2 works
* vscode_1.85.2 works
* vscode_1.86.0 broken
* vscode_1.86.1 broken
* code-insider-x64-1707457610 broken

So it seems it regressed between vscode_1.85.2 and vscode_1.86.0

**Comment by aytey** [comment]
@connor4312: it seems your fix in https://github.com/microsoft/vscode/pull/191131 has regressed

**Comment by connor4312** [comment]
Ah, that's what https://github.com/microsoft/vscode/commit/a8dd7f60a6204353e8d6969c8bc39f0476d46e2a#commitcomment-133949115 was for. Will re-fix, thanks for the issue...

**Comment by aytey** [comment]
@connor4312: I just tried with `code-insider-x64-1707716823` -- all working again, thanks for your help 😺
