### ISSUE TITLE
Quickpick item tooltip shows codicon spec in raw form

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#204818]
Type: <b>Bug</b>

I have an extension that uses the triangle-down codicon to decorate one of its items. This displays correctly in the list, but the hover text shows it as `$(triangle-down)`

![image](https://github.com/microsoft/vscode/assets/6726799/77bfe090-4002-47a3-bdb7-5c76778ea686)

VS Code version: Code - Insiders 1.87.0-insider (8fa84589eef3538dbc763ff98dc7d5a8a0c56374, 2024-02-09T05:47:15.236Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by TylerLeonhardt** [comment]
Not sure, but to make one is very easy:
```ts
                vscode.window.showQuickPick([{
			label: 'arrow',
			detail: '$(arrow-down) down',
			description: '$(arrow-up) up',
		}]);
```
