### ISSUE TITLE
 Cannot read property '_runner' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#20487]
Issue Id: <b>32ab8e97-6641-9f89-c704-499cc5de8121</b><br /><br />*Versions* <br />- 1.9.1<br />*Stack* <br />TypeError: Cannot read property '_runner' of undefined<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L927:16 (_runner)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L927:16 (_runner))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L691:85 (isTerminalConfig)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L691:85 (isTerminalConfig))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L118:26 (call)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/event.ts#L118:26 (call))<br />[/vs/workbench/services/configuration/node/configurationService.ts#L114:50 (fire)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/workbench/services/configuration/node/configurationService.ts#L114:50 (fire))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/workbench/services/configuration/node/configurationService.ts#L114:4 (then)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/workbench/services/configuration/node/configurationService.ts#L114:4 (then))<br />[/vs/base/common/async.ts#L629:8 (runner)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/async.ts#L629:8 (runner))<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Cannot read property '_runner' of undefined<br />[/vs/workbench/parts/tasks/common/taskConfiguration.ts#L1030:16 (_runner)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/workbench/parts/tasks/common/taskConfiguration.ts#L1030:16 (_runner))<br />[/vs/workbench/parts/tasks/common/taskConfiguration.ts#L1018:9 (isTerminalConfig)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/workbench/parts/tasks/common/taskConfiguration.ts#L1018:9 (isTerminalConfig))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L522:44 (from)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L522:44 (from))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L118:26 (call)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/base/common/event.ts#L118:26 (call))<br />[/vs/workbench/services/configuration/node/configurationService.ts#L106:34 (fire)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/workbench/services/configuration/node/configurationService.ts#L106:34 (fire))<br />[/vs/workbench/services/configuration/node/configurationService.ts#L87:82 (onBaseConfigurationChanged)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/workbench/services/configuration/node/configurationService.ts#L87:82 (onBaseConfigurationChanged))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L118:26 (call)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/base/common/event.ts#L118:26 (call))<br />[/vs/platform/configuration/node/configurationService.ts#L58:33 (fire)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/platform/configuration/node/configurationService.ts#L58:33 (fire))<br />

**Comment by dbaeumer** [comment]
Fixed for 1.12
