### ISSUE TITLE
Enable reconnection for restarted remote host

### ISSUE THREAD

**Issue by Haegi** [microsoft/vscode#204830]
### Motivation

I am running the vscode server and I am connecting to it via the web ui (in my case using [`code-server`](https://github.com/coder/code-server)).
Unfortunately, the new connection cannot be continued if the server is terminated or stopped without the browser window being reloaded.
The logs show the following:
```
log.ts:421  INFO [remote-connection][ExtensionHost][7745d…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:421  INFO [remote-connection][ExtensionHost][7745d…][reconnect] resolving connection...
log.ts:421  INFO [remote-connection][ExtensionHost][7745d…][reconnect] connecting to localhost:8081...
log.ts:421  INFO Creating a socket (renderer-ExtensionHost-7745d818-f9fc-423d-8fb7-f37f4ed43589)...
log.ts:441   ERR [remote-connection][Management   ][171f9…][reconnect][localhost:8081] received error control message when negotiating connection. Error:
log.ts:441   ERR Error: Connection error: Unknown reconnection token (never seen)
    at G (remoteAgentConnection.ts:812:17)
    at remoteAgentConnection.ts:338:17
    at g.invoke (event.ts:723:17)
    at r.deliver (event.ts:936:22)
    at l.fire (event.ts:892:24)
    at c.fire (ipc.net.ts:671:19)
    at k.E (ipc.net.ts:1115:28)
    at ipc.net.ts:1042:72
    at g.invoke (event.ts:723:17)
    at r.deliver (event.ts:936:22)
```

I noticed that it occurs because on startup the `remoteExtensionHostAgentServer` creates a new empty list of [`_allReconnectionTokens`](https://github.com/microsoft/vscode/blob/fbb7175b4c8d0da79c74abb3bd256e7bc27c602b/src/vs/server/node/remoteExtensionHostAgentServer.ts#L88) and the `remoteAgentConnection` [generates a new uuid `reconnectionToken`](https://github.com/microsoft/vscode/blob/fbb7175b4c8d0da79c74abb3bd256e7bc27c602b/src/vs/platform/remote/common/remoteAgentConnection.ts#L442).
Since the `_allReconnectionTokens` are empty for the new server, it can not recognise the `reconnectionToken` and will reject it.

Being able to	reconnect to a backend without having to reload the browser window would enable rolling updates/zero downtime deployments and therefore would be a huge win for the user experience (especially when running against a remote host).

### Ideas

* Instead of storing the `_allReconnectionTokens` in memory we could store it in a shared storage. For example the local filesystem.
    * For sure it would have to be behind a flag.
* Instead of generating a uuid `reconnectionToken` we could add an option to set it to a constant value. For example using some environment variable value if provided.
    * We would have to add the value also to the `_allReconnectionTokens` set.

Maybe I am missing something else and there are other parts of the code that need to be changed.

NOTE: I would be open to contribute the code after some alignment.

**Comment by roblourens** [comment]
> Unfortunately, the new connection cannot be continued if the server is terminated or stopped without the browser window being reloaded.

This is by design. A window and an extension host live together, and you can't connect the same window to a new remote extension host process.
