### ISSUE TITLE
Indentation problem eg. in python and margin in editor to line numbers

### ISSUE THREAD

**Issue by ManPython** [Microsoft/vscode#20485]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:
 

Steps to Reproduce:

1. Find single space in Python code on any color template skin  ;]
- Indentation is base and important in Python
- if we can see space before save and compile we can safe time from debuger and finding spaces

Problem: short yellow is spacebar

![problem](https://cloud.githubusercontent.com/assets/25403861/22857919/1a2b4622-f0b0-11e6-94c4-7da285a9015c.png)

**Solution: just we must have always margin line next to line numbers**

![solution](https://cloud.githubusercontent.com/assets/25403861/22857920/1a2f517c-f0b0-11e6-8f76-156122ec03b7.png)

**Comment by ManPython** [comment]
Other solutions
![solution_2](https://cloud.githubusercontent.com/assets/25403861/22858092/f74be6bc-f0b3-11e6-9534-6622970a0c6f.png)
![solution_3](https://cloud.githubusercontent.com/assets/25403861/22858093/f750b8c2-f0b3-11e6-9102-4fa0c69fae82.png)
![solution_4](https://cloud.githubusercontent.com/assets/25403861/22858094/f7524d9a-f0b3-11e6-8c38-3d76351d5531.png)

**Comment by ManPython** [comment]
![solution_5](https://cloud.githubusercontent.com/assets/25403861/22858133/df58e16c-f0b4-11e6-90b8-c123e839aaf6.png)

**Comment by ManPython** [comment]
Unification of top bar, menu ehre can be in top putted **main icons**
![solution_6](https://cloud.githubusercontent.com/assets/25403861/22858234/3b46686c-f0b7-11e6-83d3-c1caf4b5e93c.png)

![solution_7](https://cloud.githubusercontent.com/assets/25403861/22858261/07e83abc-f0b8-11e6-99f5-0617d8852cf9.png)

**Comment by alexandrudima** [comment]
@ManPython possible settings that might work for you:

### "editor.renderIndentGuides": true
![image](https://cloud.githubusercontent.com/assets/5047891/25480313/921bd2c8-2b48-11e7-9406-ffa0e51944e2.png)

### "editor.renderWhitespace": "boundary"
![image](https://cloud.githubusercontent.com/assets/5047891/25480326/a3020ac6-2b48-11e7-9f2f-10dd751c2a61.png)

### "editor.renderLineHighlight": "gutter",
![image](https://cloud.githubusercontent.com/assets/5047891/25480352/bd3f810c-2b48-11e7-85b7-12e633e4099f.png)

### "editor.rulers": [ 0 ]
![image](https://cloud.githubusercontent.com/assets/5047891/25480363/ca54e800-2b48-11e7-95f1-da6efa213516.png)

Hopefully one of these settings can work for you.
