### ISSUE TITLE
Add agent persistent for Copilot agents

### ISSUE THREAD

**Issue by charris-msft** [microsoft/vscode#204858]
We're working on building a Copilot agent.
We're doing user studies and have watched 2 people so far using the agent. Both (and one was the extension dev) have expected that once they invoke the agent subsequent prompts would go to the same agent.

Perhaps this could take the form of pre-populating the chat input box with the agent name once the agent has been used until the user starts a new chat or deletes the agent name from the chat.

**Comment by Wladefant** [comment]
you have the shouldrepopulate function for that [                readonly shouldRepopulate?: boolean;](https://github.com/microsoft/vscode/blob/903b068e329392ac9f688c76ba9511bcbef7b4b2/src/vscode-dts/vscode.proposed.chatAgents2.d.ts#L150)

**Comment by roblourens** [comment]
This is in progress: https://github.com/microsoft/vscode/pull/204910

**Comment by roblourens** [comment]
We have API for this now, and chat participants can opt in
