### ISSUE TITLE
Reference Information (CodeLens)

### ISSUE THREAD

**Issue by Mark-Phillipson** [microsoft/vscode#204899]
Type: <b>Feature Request</b>

Could we please have a keyboard shortcut to select the reference information, as there does not appear to be one.

In Visual Studio pressing Alt+F2 works, but does not work in Visual Studio Code.

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by gjsjohnmurray** [comment]
#200465 looks related.

**Comment by Mark-Phillipson** [comment]
Given that this is an accessibility issue, should it be treated as a bug?

**Comment by jrieken** [comment]
Do you know about "F1 > Show Code Lens for Current Line"?

**Comment by Mark-Phillipson** [comment]
No I was not aware of that.

I will set up a voice command for this. Thank You.
