### ISSUE TITLE
Missing window header and control buttons. Can't quit VSCode

### ISSUE THREAD

**Issue by krassx** [microsoft/vscode#204895]
Type: <b>Bug</b>

Happened to me multiple times on different devices. Last time (the one this report was generated, the laptop was brought out from sleep and after switching to VSCode it was impossible to quit it. The only was to quit is to kill process either via Activity Monitor or using a terminal. Also, the window control buttons are also missing (close, maximize, minimize) Please, see the attached screenshot below.
<br />

<img width="340" alt="Screenshot 2024-02-10 at 17 27 02" src="https://github.com/microsoft/vscode/assets/8613766/c4408eb7-4824-4ee2-b2d3-b351f428cbe3">

<br /><br />
VS Code version: Code 1.86.1 (Universal) (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:09:01.236Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 5, 3|
|Memory (System)|8.00GB (1.46GB free)|
|Process Argv|--crash-reporter-id d8bc7cd0-a51b-4d8d-b2ca-35bb874c6c8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|17.1.1
dart-code|Dar|3.82.0
flutter|Dar|3.82.0
vscode-eslint|dba|2.4.4
gitlens|eam|14.7.0
prettier-vscode|esb|10.1.0
copilot|Git|1.159.0
copilot-chat|Git|0.12.0
go|gol|0.40.3
vscode-mojo|mod|0.7.0
vscode-docker|ms-|1.28.0
csdevkit|ms-|1.3.10
csharp|ms-|2.15.30
vscode-dotnet-runtime|ms-|2.0.1
vscodeintellicode-csharp|ms-|0.1.26
debugpy|ms-|2024.0.0
isort|ms-|2023.10.1
python|ms-|2024.0.1
vscode-pylance|ms-|2023.12.1
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.13
makefile-tools|ms-|0.8.22
vscode-react-native|msj|1.12.3
vscode-versionlens|pfl|1.9.2
java|red|1.27.0
rust-analyzer|rus|0.3.1831
svelte-vscode|sve|108.2.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.56.0
vscode-java-dependency|vsc|0.23.4
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0
markdown-all-in-one|yzh|3.6.2
vscode-zig|zig|0.5.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019bcf:30953938
3ef8e399:30949928
bg6jg535:30956215

```

</details>

**Comment by deepak1556** [comment]
Does the issue repro with latest stable 1.96 ?

**Comment by krassx** [comment]
I haven’t seen this issue for a long time. Not sure since which version exactly. But in the last one and the one before it, that problem did not pop out.

**Comment by deepak1556** [comment]
thanks for confirming, closing for now.
