### ISSUE TITLE
Markdown Link Highlighting (references)

### ISSUE THREAD

**Issue by erichiller** [Microsoft/vscode#20483]
- VSCode Version: 1.9.1
- OS Version: Win 10x64

When defining links such as the below, while in the editor, the links are not highlighted as they are in [test](url) style links. I think it would be better, and more uniform for the editor to highlight these links in the same manner.

```
[Promise] objects have a [then]

[Promise]: https://msdn.microsoft.com/library/windows/apps/BR211867
[then]: https://msdn.microsoft.com/library/windows/apps/BR229728
```

[Promise] objects have a [then]

[Promise]: https://msdn.microsoft.com/library/windows/apps/BR211867
[then]: https://msdn.microsoft.com/library/windows/apps/BR229728

![image](https://cloud.githubusercontent.com/assets/5379325/22856792/a389ea94-f04d-11e6-8090-156019108a57.png)

**Comment by hashhar** [comment]
Is there a better way to implement it other than looking for all unmatched and unescaped square brackets and then referencing them. Also, what code is responsible for the link generation? Does it come from the syntax file or is it generated by modifying an object that holds the viewstate of the editor.

**Comment by mjbvz** [comment]
@hashhar For the syntax highlighting, we should just update the grammar file to identify contents inside of `[...]` as links. To get started, take a look `link-ref` in the syntax file: https://github.com/Microsoft/vscode/blob/master/extensions/markdown/syntaxes/markdown.tmLanguage

**Comment by hashhar** [comment]
Wow. This got out of hand for me. I'm very confused. Somebody else can and should work on it.

**Comment by chirag64** [comment]
I'd like to give this a try.

@erichiller Can you please explain how you want these links to be highlighted? Your link to test style links gives a 404 error.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-markdown-tm-grammar#2
