### ISSUE TITLE
different colors for different files

### ISSUE THREAD

**Issue by blaubacher** [microsoft/vscode#204837]
Type: <b>Feature Request</b>

Could you allow different files within the editor to use different color schemes?  have the schemes a 'local' rather than 'global' option?

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by mirusky** [comment]
Duplicate of #203998 
Related to #204824

**Comment by aeschli** [comment]
duplicate of #20652
