### ISSUE TITLE
How to listen input onChange event in showQuickPick?

### ISSUE THREAD

**Issue by bokuweb** [Microsoft/vscode#20499]
- VSCode Version: 1.9.1
- OS Version: 10.11.6

Is there a way to listen input onChange event in `showQuickPick`?
I want to emit command when user input changed.

Has `onDidChangeInput` not implemented yet?

Thanks

**Comment by jrieken** [comment]
That's not possible yet

**Comment by jrieken** [comment]
closing as dupe of #15659
