### ISSUE TITLE
"File to read not found or unreadable" using node-sass when saving on VSCode

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#20491]
Cross posting with sass/node-sass/issues/1894

- VSCode Version: 1.10.0-insider
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Create a folder called `styles` and place a `styles.scss` inside that folder
2. Create a node-sass 4.5.0 watch command as such: `node-sass styles/styles.scss --output-style compressed --watch --linefeed lf --source-map true --output styles`
3. There's a random chance that after editing and saving the styles.scss file, the node-sass task will fail with (fails around 30% of the time, sometimes 4-5 times in a row)

```
=> changed: G:\www\styles\styles.scss
{
  "status": 3,
  "message": "File to read not found or unreadable: G:/www/styles/styles.scss",
  "formatted": "Internal Error: File to read not found or unreadable: G:/www/styles/styles.scss\n"
}
=> changed: G:\www\styles\styles.scss
Rendering Complete, saving .css file...
Wrote CSS to G:\www\styles\styles.css
Wrote Source Map to G:\www\styles\styles.css.map
```

trying to see whose fault is it

**Comment by joaomoreno** [comment]
Very likely an issue with `node-sass`.

**Comment by umkasanki** [comment]
In Sublime text helps "atomic_save": true

**Comment by umkasanki** [comment]
for vs code try https://www.npmjs.com/package/gulp-wait

**Comment by Darcy-FzR** [comment]
For VS Code you can set settings **files.autoSave** to **afterDelay** and **files.autoSaveDelay** to a samller value like "500". And then, when you change your files, you press _ctrl + s (save)_ , although there still be err log, it does compile the newest files to .css and works.
