### ISSUE TITLE
I want to fully reset the whole VS code like litrally as new with the welcome screen

### ISSUE THREAD

**Issue by zhritik007** [microsoft/vscode#204938]
Type: <b>Feature Request</b>

I want to fully reset the whole VS code like litrally as new with the welcome screen
how to do it kindly guide

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by lramos15** [comment]
1. Open VS Code
2. F1 -> Open User Data Folder
3. Close VS Code
4. Delete that folder

Please note this will erase everything inside VS Code, so be sure you want to do this. VS Code also has support for profiles via the gear icon which can allow for different configurations depending on your needs.

**Comment by zhritik007** [comment]
Thank you so much
