### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by misantronic** [Microsoft/vscode#20492]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-simple-icons|LaurentTreguier|0.10.0|
|material-icon-theme|PKief|1.3.2|
|ejs-language-support|QassimFarid|0.0.1|
|one-monokai|azemoh|0.2.4|
|vscode-es-beautifier|dai-shi|0.2.3|
|vscode-eslint|dbaeumer|1.2.5|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|flow-for-vscode|flowtype|0.5.0|
|auto-close-tag|formulahendry|0.3.9|
|intellij-idea-keybindings|k--kato|0.2.8|
|alpenglow-monokai|kaicataldo|1.0.0|
|vscode-scss|mrmlnc|0.6.1|
|vscode-icons|robertohuertasm|7.2.0|
|ayu|teabyii|0.2.1|

---

Steps to Reproduce:

1. Click "Check for updates"

Error-message says: `Could not create temporary directory: Permission denied`

**Comment by joaomoreno** [comment]
Does it reproduce after a restart?

**Comment by misantronic** [comment]
Yep, it happens all the time.

**Comment by joaomoreno** [comment]
Can you completely reinstall VS Code? Can you also check the permissions of files and folders inside `~/Library/Application Support/Code`? Have you run `code` with `sudo` at any point in time? It isn't really recommended to do so.

**Comment by misantronic** [comment]
When I reinstall vscode, how do I backup the settings?

<img width="1171" alt="screen shot 2017-02-16 at 20 35 57" src="https://cloud.githubusercontent.com/assets/6033531/23037680/97d0b2a8-f487-11e6-9d7a-e6a9e0562ec7.png">

**Comment by joaomoreno** [comment]
Settings are in `~/Library/Application Support/Code/User`.

**Comment by misantronic** [comment]
Updated all my settings and reinstalled. It worked. Thanks a lot :)

**Comment by Nicksxs** [comment]
i face the same problem,
![image](https://cloud.githubusercontent.com/assets/7351669/25370533/0013abca-29be-11e7-895d-ca4327c0f3ea.png)
here is my screenshot of the permissions inside `~/Library/Application Support/Code`,  
how could i find it ,if i don't want to reinstall the vs code

**Comment by footyapps27** [comment]
Is reinstalling the only option to fix this error?
Am facing the same issue when trying to upgrade from 1.12.2 to 1.13.0!
