### ISSUE TITLE
tasks.json surrounds argument with single quotes when including asterisk

### ISSUE THREAD

**Issue by nhampton20** [microsoft/vscode#204947]
Type: <b>Bug</b>

1. Configure tasks.json to run a command with an argument that uses an `asterisk.`
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: clang++ build active file",
            "command": "/usr/bin/clang++",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${fileDirname}/*.cpp",
                "-v",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}",
                "--include-directory=${fileDirname}/"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ]
    
}
```
2. Execute the task
Expected output: Input the argument directly as specified, evaluating variables and letting the terminal decide what to do with the asterisk.
```
Starting build...
/usr/bin/clang++ -fdiagnostics-color=always -g /path/to/file/*.cpp -v -o /path/to/file/fileBaseNameNoExtension --include-directory=/path/to/file/
```
Observed Output: Surrounds argument with single quotes, terminal treats argument as literal instead of interpreting the asterisk as needed.
```
Starting build...
/usr/bin/clang++ -fdiagnostics-color=always -g '/path/to/file/*.cpp' -v -o /path/to/file/fileBaseNameNoExtension --include-directory=/path/to/file/
```
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:57.920Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id ace3164b-49a6-4597-8745-4f2b69d1d99b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d6fi2104:30959263
edj9j583:30958191
fegfb526:30961430
3ef8e399:30949928
ccp2r6:30958158

```

</details>

**Comment by nhampton20** [comment]
I will admit I am a student, and this is my first bug post, but I believe it to be one. The official docs state to do exactly what I am doing. I am unaware of how to insert formatted code; to this issue but would be happy to if I knew.

**Comment by ooxx201** [comment]
Hi I encounter the same issue as well, when I use "${workspaceFolder}/*.cpp" as source, vscode will quote the arg.
Any idea?
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: g++-11 build active file",
			"command": "/usr/bin/g++-11",
			"args": [
				"-fdiagnostics-color=always",
				"-g",
				"-std=c++20",
				"${workspaceFolder}/*.cpp",
				"-o",
				"${fileDirname}/${fileBasenameNoExtension}"
			],
```

```
Starting build...  
/usr/bin/g++-11 -fdiagnostics-color=always -g -std=c++20 '/home/q1/sample/*.cpp' -o /home/q1/sample/main  
cc1plus: fatal error: /home/q1/sample/*.cpp: No such file or directory  
compilation terminated.  
```

**Comment by SteuxJMHelha** [comment]
I have exactly the same issue. It appears suddenly today on all computers in my school, breaking all compilation procedures. We now have to manuall specify all files in a folder.
Here is the tasks.json that is not working anymore:
```
{
    "version": "2.0.0",
    "tasks": [
         {
            "type": "cppbuild",
            "label": "Compiler les tests",
            "command": "/usr/bin/gcc",
            "args": [
                "-g",
                "${workspaceFolder}/Sources/*.c",
                "${workspaceFolder}/Unity/*.c",
                "${workspaceFolder}/Tests/*.c",
                "-I",
                "/usr/include/mariadb",
                "-I",
                "/usr/include/mariadb/mysql",
                "-o",
                "${workspaceFolder}/Tests/tests",
                "-L",
                "/usr/lib/x86_64-linux-gnu/",
                "-l",
                "mariadb",
                "-l",
                "ncurses"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}

**Comment by LauraPanizo** [comment]
I have notice the same issue today in a mac laptop with VSCode 1.86.2. However, using the same VSCode version in windows and a task.json with the same list of arguments  it is working correctly.

**Comment by jeremvv** [comment]
The same happened to me today. VSCode version 1.86.2.
I tried downgrading to 1.86.0 but the same happened.
I am on Ubuntu 20.04.

**Comment by spotter1006** [comment]
Me too. @meganrogge , any update?

**Comment by datanasio** [comment]
I have a workaround. I think it's the extension that's the problem. I downgraded it by going to the marketplace and downloading and installing the vsix file (ms-vscode.cpptools-1.19.0@linux-x64.vsix)

**Comment by spotter1006** [comment]
> I have a workaround. I think it's the extension that's the problem. I downgraded it by going to the marketplace and downloading and installing the vsix file ([ms-vscode.cpptools-1.19.0@linux-x64.vsix](mailto:ms-vscode.cpptools-1.19.0@linux-x64.vsix)) . Now I can compile with ${fileDirname}/*.cpp

This worked for me. Thanks @datanasio

**Comment by SteuxJMHelha** [comment]
Thanks to the hint @datanasio but downgrading is not practicle when you manage many computers, including VMs and private student computers...
I found a similar issue on the C/CPP extension is here: https://github.com/microsoft/vscode-cpptools/issues/12027. Each of us should better report his problem there.
@meganrogge : could you explain the bug to your MS colleagues from C/CPP tools ? We need a correction ! Thank you !

**Comment by datanasio** [comment]
Hi Jean-Marc

Thank you for your feedback.

I did report it on the github site for the cpp extension after I discovered the true cause of the problem. They were already aware of it. I, too, teach and am responsible for many computers. I have developed a login system for my classroom that is independent of our IT department's.

Because the 'student' account has a roaming profile which resets on each power cycle,  My login script pushes the extension to the PCs. I can push any extension I want and any version of any extension by using code's command line tools.

I also push user config to each PC on login. I push Linux VM images and refresh them using a tiered staging system.

Dom


[Mt. San Antonio College (Mt. SAC) Logo]
Dominick Atanasio
Professor of Computer Science
Math and Computer Science Dept.
Natural Sciences Div.
[Office]        Bldg. 61 Room 1656
[Email] ***@***.******@***.***>

Mt. San Antonio College
1100 N. Grand Ave.,
Walnut CA 91789
www.mtsac.edu</>
Fingerprint=    1DC3 0A5F 7453 0048 D662 AC4E D432 2679 D4A5 B02B
On 2/27/24 5:31 AM, Jean-Marc Steux HELHa wrote:

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

  EXTERNAL SENDER - Exercise caution with requests, links, and attachments.

Thanks to the hint @datanasio<https://github.com/datanasio> but downgrading is not practicle when you manage many computers, including VMs and private student computers...
I found a similar issue on the C/CPP extension is here: microsoft/vscode-cpptools#12027<https://github.com/microsoft/vscode-cpptools/issues/12027>. Each of us should better report his problem there.
@meganrogge<https://github.com/meganrogge> : could you explain the bug to your MS colleagues from C/CPP tools ? We need a correction ! Thank you !

**Comment by spotter1006** [comment]
After downgrading the extension my setup worked briefly. Then VScode detected a mismatch and behind the scenes reinstalled the latest. I agree that downgrading is not a long term fix.

**Comment by datanasio** [comment]
turn off auto update for now until the extension is fixed


[Mt. San Antonio College (Mt. SAC) Logo]
Dominick Atanasio
Professor of Computer Science
Math and Computer Science Dept.
Natural Sciences Div.
[Office]        Bldg. 61 Room 1656
[Email] ***@***.******@***.***>

Mt. San Antonio College
1100 N. Grand Ave.,
Walnut CA 91789
www.mtsac.edu</>
Fingerprint=    1DC3 0A5F 7453 0048 D662 AC4E D432 2679 D4A5 B02B
On 2/27/24 6:34 AM, spotter1006 wrote:

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

  EXTERNAL SENDER - Exercise caution with requests, links, and attachments.

After downgrading the extension my setup worked briefly. Then VScode detected a mismatch and behind the scenes reinstalled the latest. I agree that downgrading is not a long term fix.
