### ISSUE TITLE
cannot git commit --amend when using vscode

### ISSUE THREAD

**Issue by S-N-O-R-L-A-X** [microsoft/vscode#204934]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.86.1
- OS Version: windows 10

Steps to Reproduce:

1.  type `git commit --amend` in terminal in vscode
2.  hint: Waiting for your editor to close the file... "E:\Microsoft VS Code\Code.exe" --wait: E:\Microsoft VS Code\Code.exe: No such file or directory

![image](https://github.com/microsoft/vscode/assets/60914359/24b3cd09-623a-4b3e-a0fe-edd33d5011e2)

**Comment by S-N-O-R-L-A-X** [comment]
BTW, my  vscode is not in E but in G:\Microsoft VS Code

**Comment by burtek** [comment]
https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration

Update `core.editor` git config to point to correct location of vscode. Not a vscode issue btw.

**Comment by S-N-O-R-L-A-X** [comment]
@burtek Really helpful information. Thanks a lot.
