### ISSUE TITLE
Using workbench.action.quickOpenSelectNext/Previous moves focus out of input box?

### ISSUE THREAD

**Issue by bokuweb** [Microsoft/vscode#20497]
- VSCode Version: 1.9.1
- OS Version: 10.11.6

Is there a way to use `showQuickPick` and re focus inputbox when `quickPickItem` focused and then user keydown in showQuickPick? 

Thanks

**Comment by joaomoreno** [comment]
I'm not sure I understand what you mean. The inputbox is always focus as the user presses <kbd>Up</kbd> and <kbd>Down</kbd>. Maybe show us a screenshot?

**Comment by bokuweb** [comment]
@joaomoreno Thanks for your reply.
I was misunderstanding. The input box is always focus as the user presses Up and Down.
But when item selected  by `workbench.action.quickOpenSelectNext`, input box is blurred.


- use Up and Down. 
![screenshot](https://cloud.githubusercontent.com/assets/10220449/22932815/9a60f270-f30c-11e6-9d2b-bb91978f5210.gif)

- use `workbench.action.quickOpenSelectNext/Previous`
![screenshot2](https://cloud.githubusercontent.com/assets/10220449/22932837/a8ccc866-f30c-11e6-9393-10ad9f1ff7e8.gif)

thanks

**Comment by bpasero** [comment]
@bokuweb sorry I have no clue what this issue is about. can you please explain it to me in a way that I can comment? Thanks.

**Comment by bokuweb** [comment]
@bpasero sorry. `blurred` means `unfocused`. the input box is always focused when selecting completion item  with Up and Down key.

But, the input box is always unfocused  when selecting completion item  with quickOpenSelectPrevious/Next command.

Sorry for the poor English...

**Comment by bpasero** [comment]
@bokuweb thanks I see the issue now 👍
