### ISSUE TITLE
Request to move the OS incompatibility message to status bar

### ISSUE THREAD

**Issue by WinCPP** [microsoft/vscode#204944]
- VS Code Version: 1.86.1
- OS Version: Windows 10 with Centos 7 for remote

Further to #203967, thanks for allowing support for unsupported OSes for another year. The new 1.86.1 shows following bar just below the Menu bar. Occupies screen real estate. Cannot dismiss it. Is too jarring.

![IMG-31c7864721cf87328b0fb58866d7fceb-V.jpg](https://github.com/microsoft/vscode/assets/8945458/09e1cc87-7f81-4105-aa56-196b62007737)

Could you please consider moving it to the status bar (typically at the bottom), whose purpose is to show such and similar details? Because we know what we are doing by using old version. Also, using some non-jarring background color, when in status bar, would help.

To begin with, perhaps it can be shown in the status bar with red warning sign, short text "Incompatible OS", with full message as ALT text and no background color change. And when the one year extension nears end, make it all red (and blinking!)... in the status bar.

Thanks,
WinCPP

**Comment by gjsjohnmurray** [comment]
See also #204728

**Comment by WinCPP** [comment]
@benibenj closing this as duplicate of #204728 which @gjsjohnmurray pointed out, which was also reported earlier.
