### ISSUE TITLE
Git - decorations for incoming changes

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#204982]
File decorations.

**Comment by d13** [comment]
Noticing "Incoming Changes" still show on the editor tab even after pulling changes.

Version: 1.87.0-insider
Commit: e587755905208e47725c5196539c4ca898255fe6
Date: 2024-02-15T05:48:48.139Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.87.0-insider Chrome/118.0.5993.159 Electron/27.3.2 Safari/537.36

![Screenshot 2024-02-15 at 4 36 43 PM](https://github.com/microsoft/vscode/assets/293282/101c8712-44a4-4004-8d53-939e1d6bdde1)

**Comment by gjsjohnmurray** [comment]
@d13 I think this is #205198, for which the fix will arrive in tomorrow's Insiders.

**Comment by lszomoru** [comment]
This should be fixed in today's VS Code Insiders release
```
Version: 1.87.0-insider (Universal)
Commit: d84c946d27b649d614319c796911871320befd42
Date: 2024-02-16T06:05:20.657Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0
```

**Comment by lszomoru** [comment]
Gutter decoration will be tracked separately.

**Comment by lszomoru** [comment]
Reopening the issue as we have decided to further polish this before shipping it.

**Comment by alcpereira** [comment]
How can we disable this feature? `git.decorations.enabled` was perfect before this change. Please make an option to disable this.
