### ISSUE TITLE
Typescript type definition files not picked up from scoped npm packages. Cannot handle @ in paths

### ISSUE THREAD

**Issue by HCanber** [Microsoft/vscode#2049]
When a scoped npm package is installed, for example, `@MyCompany/utils` it's installed in `node_modules/@MyCompany/utils`.

Since the package's `package.json` contains:

```
"typescript": {
  "definition": "my-typings.d.ts"
}
```

... this means I can add a reference to `my-typings.d.ts` to the file `typings/tsd.d.ts` using the command:

```
tsd link
```

The following will be added to `typings/tsd.d.ts`:

```
/// <reference path="../node_modules/@MyCompany/utils/my-typings.d.ts" />
```

However VSCode 0.10.6 OS X shows a red squiggly line and says it cannot find the file.
If I move `@MyCompany/utils/my-typings.d.ts` to `MyCompany/utils/my-typings.d.ts` and update `typings/tsd.d.ts` to 

```
/// <reference path="../node_modules/MyCompany/utils/my-typings.d.ts" />
```

the squiggly line disappears, and the typings in that file is picked up so the problem seems to be the `@`character in the path.

**Comment by dbaeumer** [comment]
This works for me in the latest. Seem to got fixed by the TS team. Closing.
