### ISSUE TITLE
How can an extension expand configuration variables?

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#20493]
- VSCode Version: 1.9.1
 OS Version:  Windows 10 AU (1607)

Steps to Reproduce:

1.  Start with a debug extension sample like mock-debug
2.  In scripting environments, you often want to launch the current, active file. So you create a launch config with `"program":` set to `"${file}"`. 
3. However, your workspace has other file types (.md, .json, .yml, etc) which aren't script files and can't be debugged.  So you'd like to test the extension of the file to be debugged so put up a vscode error message stating that launch.json can't be debugged.  However, all I'm seeing is `"${file}"`.  How do I resolve this to the actual file path?  I see there is an IConfigurationResolverService but I can't figure out how to access it.  It doesn't appear to be available for consumption by an extension.

**Comment by weinand** [comment]
@rkeithhill please see my extension code for node-debug at 
https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension.ts#L310

`vscode.window.activeTextEditor` corresponds to ${file} and `editor.document.languageId` is used to determine whether the open file in the editor has the correct type to be debugged by the debug extension.

**Comment by rkeithhill** [comment]
@weinand Thanks!
