### ISSUE TITLE
Unable to use break points in Python code

### ISSUE THREAD

**Issue by BillHaas1** [microsoft/vscode#204932]
Type: <b>Bug</b>

Set a break point in one line Python code (bright red dot) and run Python Debugger.  
print (" I am in Python Debug mode")
Code execution does not stop at break point.

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3840QM CPU @ 2.80GHz (8 x 2791)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.36GB free)|
|Process Argv|--crash-reporter-id 48db064e-3fe6-4113-a6a7-d9897f20aef7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|14.8.0
codespaces|Git|1.16.10
copilot|Git|1.159.0
copilot-chat|Git|0.12.1
vscode-docker|ms-|1.28.0
debugpy|ms-|2024.1.10371006
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
3ef8e399:30949928
bg6jg535:30958357
ccp1r6:30958156

```

</details>

**Comment by roblourens** [comment]
Please file an issue on the Python extension, thanks
