### ISSUE TITLE
Run task without showing Terminal panel - vscode 1.86.1

### ISSUE THREAD

**Issue by RazvanModex** [microsoft/vscode#204989]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.1
- OS Version: Windows 10 Business 20H2

Steps to Reproduce:

1. Create an empty project folder
2. Create the following task in `.vscode/tasks.json`:
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "do something",
      "type": "shell",
      "command": "echo Hello!",
      "problemMatcher": [],
      "isBackground": true,
      "presentation": {
        "reveal": "never",
        "revealProblems": "never",
        "panel": "dedicated"
      },
      "runOptions": {
        "runOn": "folderOpen"
      }
    }
  ]
}
```
3. Open the project folder in VS Code.

### Actual result
![image](https://github.com/microsoft/vscode/assets/97091990/5442cb9e-1858-4c81-b6c1-d281e908996a)

### Expected result
The task to be visible only in the Output tab, after selecting Tasks.
![image](https://github.com/microsoft/vscode/assets/97091990/8bc1e65d-d2a8-4f6d-a7b1-73f4d4af9873)

### Related issues
#44564

**Comment by meganrogge** [comment]
That's not how this works. The Output tab is for logging. It will show up in the terminal panel, but will not open the panel when you have that setting.
