### ISSUE TITLE
Why is `CompositeBarActionViewItem` not setting a custom hover via `IHoverDelegate`?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#204966]
We show a custom hover for composite bar entries:

https://github.com/microsoft/vscode/blob/983a3bc0aecfc0772dd7b37919d7da36c89a6f2d/src/vs/workbench/browser/parts/compositeBarActions.ts#L419

But action view items are capable of rendering custom hovers provided you set a `IHoverDelegate` as option:

https://github.com/microsoft/vscode/blob/983a3bc0aecfc0772dd7b37919d7da36c89a6f2d/src/vs/base/browser/ui/actionbar/actionbar.ts#L54

I feel like we should be more consistent here and not implement the hover in a subclass if the super type provides this capability already?

**Comment by sandy081** [comment]
> Why is CompositeBarActionViewItem not setting a custom hover via IHoverDelegate?

Reason is simple: `CompositeBarActionViewItem` started supporting custom hovers way before action bar does.

Closing this because I do not have plans to adopt. Sorry.

**Comment by bpasero** [comment]
I often notice that the hover in over activity bar appears instantly, even when I was hovering over something else. There seems to be logic to show the hover eagerly, if the last hover was `200ms` in that area:

https://github.com/microsoft/vscode/blob/4f2ff19ecacffa0aa4874db4d63ed4e899d98431/src/vs/workbench/browser/parts/compositeBarActions.ts#L407

Shouldn't the `hoverLeaveTime` also be cleared when the hover is disposed:

https://github.com/microsoft/vscode/blob/4f2ff19ecacffa0aa4874db4d63ed4e899d98431/src/vs/workbench/browser/parts/compositeBarActions.ts#L414

These are things that `setupCustomHover` will take care of...

**Comment by sandy081** [comment]
This is indeed by design to show the hover instantly when moving the mouse across the activity bar actions which custom hover does not support.

https://github.com/microsoft/vscode/issues/122226
