### ISSUE TITLE
Editing a markdown cell using Keyboard shotcut (Enter key) scrolls markdown cell up and there's no scrolling when using `dbl click`

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#204954]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Create a new notebook
2. Add a code cell
3. Add a markdown cell with a few lines such as follows
```md
Markdown cell
# Heading
* 1
* 3
* 3
```
* Go into preview mode in markdown
* Edit first cell
* `Esc` to get into notebook mode
* Arrow down to select markdown cell and hit enter
* Watch how the mardown cell scrolls up in the notebook view
* Go back to preview mode
* Scroll the notebook to view the first cell again and edit it
* Now select the markdown cell using the mouse
* Double click the mardown cell to edit it and wathc how it does not scroll!!

I.e. using keyboard vs mouse results in different behaviour with scrolliing of the notebook.

Ideally I would expect there to be no automatic scrolling when editing using keyboard, just as with mouse
* given the md cell is already in view we should not scroll this cell

![Recording 2024-02-12 at 11 54 33](https://github.com/microsoft/vscode/assets/1948812/60634967-e829-47e3-a807-9591d9351a7f)

**Comment by rebornix** [comment]
When pressing enter, we try to reveal the cursor selection in the cell editor into view by calling https://github.com/microsoft/vscode/blob/01f46bb5357baa8f3b9da690e1e34eb78e09a72b/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L2394

which uses the `Default` reveal type

https://github.com/microsoft/vscode/blob/01f46bb5357baa8f3b9da690e1e34eb78e09a72b/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L2133-L2135

My expectation is it only scrolls the cell if it's out of the viewport but currently it always reveals the cell to the top of the viewport. Changing the reveal type to `CellRevealRangeType.CenterIfOutsideViewport` does fix the problem (as it should behave, here I'm not necessarily suggesting we change the reveal type in `revealRangeInViewAsync`).

**Comment by rebornix** [comment]
Assigning to Feb milestone as the experience is quite bad. What surprised me is we didn't get user reports for this, which made me wonder how many users edit markdown cells after they are initially created.
