### ISSUE TITLE
VSCode doesn't send textDocument & semantic highlighting requests

### ISSUE THREAD

**Issue by wakaztahir** [microsoft/vscode#204906]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.1
- OS Version: Windows

I am trying to build a Language Server, For that I used LspCpp in C++ to build the language server, so it would be really fast. I started out the basic implementation and I am not receiving the textDocument requests (didOpen, change), also not receiving the semantic highlighting request for which I am interested in. I tried looking for other issues and made similar changes to my configuration file but nothing fixed it.

This doesn't seem like server issue, The request is just not being sent !

### Notes

- Initialize request received
- Text Document requests not received didOpen, change
- Initialized notification received with semantic highlighting not supported
- Yes I'm sending true in capabilities along with token types and modifiers

### What I've tried

- Tried enabling semantic highlighting in VSCode settings !
- Changing configuration file of LSP extension
- Tried opening & closing the files
- I've checked the Uncaught exceptions and there are no uncaught exceptions, I tried checking caught exceptions and there were too many.
- The output / debug console don't contain any informative information, The developer tools also don't contain any helpful information about what's happening
- Updated to latest version of VSCode

### Projects

Here's my LSP client extension : 
https://github.com/Qinetik/chemical-vscode

Here's my LSP server implementation :
https://github.com/Qinetik/chemical

Chat with the owner of LSPCpp :
https://github.com/kuafuwang/LspCpp/issues/35#issuecomment-1934662110

**Comment by RedCMD** [comment]
the client needs to get the requests and forward them onto the server

**Comment by wakaztahir** [comment]
I pasted this code into my extension.ts file, `Cannot find name 'vscode'`, Can you tell me how exactly do I forward these requests to the server.

**Comment by RedCMD** [comment]
> `context.subscriptions.push( languages.registerDocumentSemanticTokensProvider(['ch'], provider, legend));`

putting that in `activate()` will work

> `throw new Error("Function not implemented.");`

here you will need to contact your server and then `return` the reply
I haven't setup an LSP before, I've only custom wrote the parser directly in that function
I would recommend looking at other extensions that use an LSP
like C, JS, JSON, HTML etc
or maybe some smaller 3rd extensions that'll be easier to comprehend

**Comment by wakaztahir** [comment]
I can't seem to find a implementation of an LSP that has such code. Plus they are so complicated !

**Comment by wakaztahir** [comment]
Please I require the implementation for this, I can't do this on my own....

**Comment by wakaztahir** [comment]
ok, I found this https://github.com/microsoft/vscode-extension-samples/blob/main/semantic-tokens-sample/src/extension.ts

**Comment by wakaztahir** [comment]
In the `semantic-tokens-sample` The parse text is implemented on the client side, So its still not going to send the request to server !

https://github.com/microsoft/vscode-extension-samples/blob/2eb7bad1195e4270ce93a179aa45f18efa0f953e/semantic-tokens-sample/src/extension.ts#L67

There should be a sample that provides semantic tokens through server by making request using the language server client !

**Comment by wakaztahir** [comment]
Ok, I've found the error, The error is that you need `onLanguage:semanticLanguage` in package.json in `activationEvents` field

https://github.com/microsoft/vscode-extension-samples/issues/898

**Comment by wakaztahir** [comment]
I guess I'm still not done, I'm getting the request on server, I can also `console.log` before sending the request and its also showing in the debug console

BUT -> no syntax highlighting !

Here's what my server is returning for the full semanticTokens Request :

### Server Returns:

```c++
std::vector<SemanticToken> toks;
toks.push_back(SemanticToken{
        0, 0, 4, SemanticTokenType::ls_keyword, 0
});
toks.push_back(SemanticToken{
        0, 5, 1, SemanticTokenType::ls_variable, 0
});
toks.push_back(SemanticToken{
        0, 2, 1, SemanticTokenType::ls_operator, 0
});
toks.push_back(SemanticToken{
        0, 2, 1, SemanticTokenType::ls_number, 0
});
toks.push_back(SemanticToken{
        0, 1, 1, SemanticTokenType::ls_operator, 0
});
```

### Client Console

![screenshot-vscode-lsp](https://github.com/microsoft/vscode/assets/42442700/525d4ce7-51f8-4396-8e5e-eb0c97b70266)


### Sample Code

```
#var x = 5;
```

**Comment by wakaztahir** [comment]
Fixed With :

```
    async provideDocumentSemanticTokens(document: vscode.TextDocument, token: vscode.CancellationToken): Promise<vscode.SemanticTokens> {
        console.log("[Request] textDocument/semanticTokens/full");

        const params : SemanticTokensParams = {
            textDocument : {
                uri : document.uri.toString()
            }
        }
              // @ts-ignore
        return lc.sendRequest("textDocument/semanticTokens/full", params).catch(e => {
            console.error("Error sending semantic tokens request", e)
            return Promise.reject(e)
        })
    }
```

Oooooh this looks good !
![screenshot-vscode-lsp](https://github.com/microsoft/vscode/assets/42442700/d33604a2-19de-4f6d-88bd-d9316a0602d8)

**Comment by wakaztahir** [comment]
Microsoft : Hire me please...

**Comment by wakaztahir** [comment]
VSCode is not sending didOpen , didChange & didClose requests as well, To fix this I tried these things

with semantic highlighting full request, I can provide the semantic tokens when the user opens the file for the first time, BUT making changes to source code is known to VSCode only which is not saved in the file on disk, which is read by my server providing tokens.

To provide the very fresh tokens for fresh edits user made, I must track the source code changes done by the user, user will send these changes to my server, I'll keep it in memory as `overridden source` then when vscode asks for tokens I'll provide it from overridden source instead of file on disk

#### 1 - Catch and send requests from client to the server in the extension, however this results in errors

```typescript
    context.subscriptions.push(
        workspace.onDidOpenTextDocument((document : TextDocument) => {
            const params = {
                textDocument : {
                    uri : document.uri.toString(),
                    version : document.version,
                    languageId : document.languageId,
                    text : document.getText()
                }
            } satisfies DidOpenTextDocumentParams
            console.log("[Request] textDocument/didOpen", params)
            lc.sendNotification("textDocument/didOpen", params).catch(e => {
                console.error("Error sending did open text document params")
                return Promise.reject(e)
            })
        })
    )
```

2 - VSCode has lsp user input sample, which has a `registerProposedFeatures` call and then LSP Client sends the didOpen,  didChange & didClose requests automatically, However that doesn't work as well

```
https://github.com/microsoft/vscode-extension-samples/blob/a7e7e7f3a214c0fa3da1ff8d4e60104c06713787/lsp-user-input-sample/client/src/extension.ts#L43
```

3 - This extension also has a onLanguage in package.json here
https://github.com/microsoft/vscode-extension-samples/blob/a7e7e7f3a214c0fa3da1ff8d4e60104c06713787/lsp-user-input-sample/package.json#L15C3-L15C25
Adding this also doesn't work !

**Comment by wakaztahir** [comment]
Okay I fixed it, The way you do it this : 

`onLanguage:plaintext` means when the language is `plaintext`, so I wrote `onLanguage:chemical`

I also used this as the document selector so vscode knows the language

{ pattern : "**/*.ch", scheme: 'file', language: 'chemical' }
