### ISSUE TITLE
The ability to make quick search as the default search option

### ISSUE THREAD

**Issue by danielpaz6** [microsoft/vscode#204930]
I like the default search option, and I want to suggest the ability in the Preferences to choose this method as the default way to search content in files globally.

Another enhancement would be to provide a standalone search panel that won't necessarily need to be prefixed with "%" - which is the same case as searching files globally - in that case, the search bar is meant only for that purpose.

It does make sense that Search Files, Search Content in Files, and Others will have separate search panel.

**Comment by andreamah** [comment]
> I like the default search option, and I want to suggest the ability in the Preferences to choose this method as the default way to search content in files globally.

If you want to go to quick search by default, you can add a keybinding for `CTRL+SHIFT+F` to `workbench.action.experimental.quickTextSearch` like this:

```
  {
    "key": "ctrl+shift+f",
    "command": "workbench.action.experimental.quickTextSearch"
  }
```

to your keybindings.json. 

> Another enhancement would be to provide a standalone search panel that won't necessarily need to be prefixed with "%" - which is the same case as searching files globally - in that case, the search bar is meant only for that purpose.

I'm not sure what this would look like. Why would you want quick search in a panel? It seems that the special thing about quick search is that it is a picker instead of a panel.

**Comment by danielpaz6** [comment]
Thanks for the WA :-)
As for the question, I guess I'm used to Jetbrains, in that IDE the default is a quick search, and when I want the search results to remain there's a button to put the results in a panel.

**Comment by danielpaz6** [comment]
Is there a plan to redesign the search results in the panel to have a more verbose UI? it's text-oriented right now

**Comment by danielpaz6** [comment]
Instead of having this panel design:
![image](https://github.com/microsoft/vscode/assets/42693974/8591842f-b017-4d2b-be7d-62217b6b019d)

Make it look more like the quick search design:
![image](https://github.com/microsoft/vscode/assets/42693974/0f56aafc-803d-4114-9721-e8fe070fd865)

Btw another enhancement is maybe to color the search results with the real colors that would have been applied if these lines were seen fully, i.e. variables, conditions, loops in the real colors they should appear with instead of unify one

**Comment by danielpaz6** [comment]
Yeah, I guess that using bordering and dividers just emphasizes the search results, I mean when I take a look at both quick search and the legacy search panel, the new one just looks so much better.

Two additional things I may suggest (BTW sorry for suggesting everything in this issue, if you think it's better to divide each idea into a separate issue let me know):

1. In the quick search panel, you can see only the filename in the title, but sometimes there may be identical file names across a project, so I suggest adding the same full/relative path names as currently is when choosing how much of a path to see in opened tabs (known as **label format**)

2. Since the panel can't be moved, therefore, search results beneath the panel cannot be seen, I suggest adding a mini editor as a preview instead of moving completely to a different page. This kind of preview is implemented and used by default in Jetbrain's quick find panel - so maybe this one could be taken as inspiration.

**Comment by andreamah** [comment]
> In the quick search panel, you can see only the filename in the title, but sometimes there may be identical file names across a project, so I suggest adding the same full/relative path names as currently is when choosing how much of a path to see in opened tabs (known as label format)

This feature is being tracked here https://github.com/microsoft/vscode/issues/191994

> Since the panel can't be moved, therefore, search results beneath the panel cannot be seen, I suggest adding a mini editor as a preview instead of moving completely to a different page. This kind of preview is implemented and used by default in Jetbrain's quick find panel - so maybe this one could be taken as inspiration.

Are you talking about the picker for quick pick? We try to show the match on active element change, so it *should* always be visible (via this behavior https://github.com/microsoft/vscode/pull/202306). Is it blocking it in some cases?

**Comment by TylerLeonhardt** [comment]
> I think that you mean the syntax highlighting from the code. @TylerLeonhardt is there an issue that is tracking how we could possibly have syntax colouring in the picker?

Don't think so. Feel free to get one going, though it won't be an easy thing to light up. We don't do this in the Search view either.

**Comment by andreamah** [comment]
@danielpaz6 You can create an issue for syntax highlighting in the picker if you'd like! Although, as Tyler said, it's unlikely to be prioritized soon.

**Comment by andreamah** [comment]
If you'd like to see full syntax highlighting on results, I would suggest using the Search Editor feature.

**Comment by danielpaz6** [comment]
Thanks will do :-) closing this one.
