### ISSUE TITLE
360报tsserver为木马

### ISSUE THREAD

**Issue by zhb123168** [Microsoft/vscode#20496]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|scanner-js-twain-wia-javascript-browser-scan|asprise-scan-ocr|2.0.2|
|python|donjayamanne|0.5.7|
|ctags-support|jaydenlin|1.0.7|
|MagicPython|magicstack|1.0.6|
|language-vscode-javascript-angular2|nwallace|0.0.11|
|autolinting-for-javascript|t-sauer|1.3.0|
|python-extended-snippets|tushortz|0.0.1|

---

Steps to Reproduce:

1.
2.

**Comment by shibang** [comment]
1. 不要用360，它是流氓
2. 用英文提 issue

**Comment by mjbvz** [comment]
360 has been causing problems with TypeScript. You have two options:

* Uninstall 360, or at least add the VSCode TypeScript path to its exemption list. The office VSCode downloads ship with the official npm releases of TypeScript. 360 is incorrectly marking these files as trojans for some reason. 
* Install a custom version of TypeScript and [use it with the `typescript.tsdk` setting](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)
