### ISSUE TITLE
Aux window: support interactive editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#204984]
Now that notebooks can run in floating windows, I was wondering why interactive editor would still not be supported. There is still a capability set:

https://github.com/microsoft/vscode/blob/420099cb092f0994ecb1e7af4c679dc0ffe57fa3/src/vs/workbench/contrib/interactive/browser/interactiveEditorInput.ts#L135

Maybe just forgot to remove it?

**Comment by amunger** [comment]
should be implemented in https://github.com/microsoft/vscode/pull/206398

**Comment by amunger** [comment]
verification steps:
1. with the jupyter extension installed, create a python file with some code cells e.g.
 
```
# %%
print(1)
```

3. run the cell, which should open an interactive window
4. move the interactive window out of the main window 
5. run more cells, they should go to the same IW
