### ISSUE TITLE
Vscode completely freezes for about 3 seconds every 15-20 seconds

### ISSUE THREAD

**Issue by mladen5000** [microsoft/vscode#204903]
Type: <b>Performance Issue</b>

### When does it happen?
Constantly. It is a complete freeze, (its happening as I write the bug report). The input typed during the freeze is quickly typed up after the freeze/hang up dissapears. It occurs regardless of workspace and without any specific action.

### Steps to narrow down extension.
Disabling all extensions - which still doesn't prevent it.

VS Code version: Code - Insiders 1.87.0-insider (Universal) (8fa84589eef3538dbc763ff98dc7d5a8a0c56374, 2024-02-09T05:49:05.817Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|125, 112, 116|
|Memory (System)|16.00GB (1.29GB free)|
|Process Argv|--crash-reporter-id 0c3e08e7-ea47-425a-9275-aa898d1457f4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   12	   311	 85221	code-insiders main
    1	    98	 85224	   gpu-process
    0	    33	 85225	   utility-network-service
    0	    98	 85329	shared-process
    0	     0	 86210	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    49	 85333	ptyHost
    0	     0	 35138	     /bin/zsh -il
    0	    98	 86184	window [7] (Issue Reporter)
    0	    16	 87368	   utility-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (~/Projects/rosalind_rust — bin)
|    Folder (rosalind_rust): more than 21569 files
|      File types: html(9242) o(3226) json(955) timestamp(775) d(686)
|                  rmeta(544) rlib(332) js(180) bin(91) ll(42)
|      Conf files: launch.json(2) settings.json(1)
|      Launch Configs: lldb(2);
```

</details>
Extensions: none

**Comment by deepak1556** [comment]
Please check if the issue is present with latest stable 1.96, if it does can you capture a perf trace following the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process
