### ISSUE TITLE
Debug Tool Bar Overlaps macOS Window Buttons When Location is Set to "Floating"

### ISSUE THREAD

**Issue by ingomohr** [microsoft/vscode#204937]
Does this issue occur when all extensions are disabled?: Can't Tell. Can I even debug without any extensions?

- VS Code Version: 1.86.1
- OS Version: macOS Sonoma 14.2.1 (23C71)

### Steps to Reproduce
💡 Found this while debugging my first extension as documented [here](https://code.visualstudio.com/api/get-started/your-first-extension)

1. In the Preferences have "Debug: Tool Bar Location" set to "floating" (seems to be the default value, too)
2. In the "Run and Debug" perspective click button "Start Debugging (F5)"
3. => The debug tool bar is rendered over the window buttons 🐛

![2024-02-11 13 48 14](https://github.com/microsoft/vscode/assets/2838592/cda6ef73-c9bf-4531-9781-d0d88cd75c46)

### Workaround
Use debug tool bar location "docked" instead.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/204265#issuecomment-1931236889
