### ISSUE TITLE
delete files 

### ISSUE THREAD

**Issue by Geekybhautik** [microsoft/vscode#205025]
Type: <b>Feature Request</b>

i deleted my important files by mistake from the explorer shown in stating of vs code i want recover it but it is not showing in bin please do something it is very important

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by lramos15** [comment]
`F1 -> Local History`
