### ISSUE TITLE
Top 10% of window is covered by white rectangle - no title bar, menu bar etc

### ISSUE THREAD

**Issue by datamystic** [microsoft/vscode#205043]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.1, 1.85.2
- OS Version: Windows 10 Pro 19045.3930

Steps to Reproduce:

1. Open VS code (5 existing workspaces loaded into 5 windows)
2. Top 10% of window is covered by white rectangle. Covers title bar, menu bar and some area below this
![image](https://github.com/microsoft/vscode/assets/3630976/7b239e59-5c94-4203-906e-46b4244b9e6d)

**Comment by rzhao271** [comment]
@datamystic are you still seeing this issue on the latest version of VS Code?
