### ISSUE TITLE
Code actions obscure code on small notebook cells

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#205027]
I get what the problem is here as monaco is 1 line tall, but wondering if there a way to fix it?

![image](https://github.com/microsoft/vscode/assets/2193314/dfc203e9-d7e4-4c23-8b4c-886298035384)

**Comment by amunger** [comment]
Isn't this a general monoco editor issue?
![image](https://github.com/microsoft/vscode/assets/2019016/392dac0f-bad7-4351-8a20-4ea85ea607d3)

**Comment by Tyriar** [comment]
Yes you're right when there's no indentation, I think the plan is to move it either above or below depending on surrounding content (we talked about it in slack recently). I guess let's wait and see how that turns out and reconsider if anything is needed here
