### ISSUE TITLE
未能保存“兼容.html”: 发生了系统错误(EBUSY: resource busy or locked, open 'c:\Users\Administrator\Desktop\项目\兼容.html')

### ISSUE THREAD

**Issue by lalalawututu** [Microsoft/vscode#20507]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-css-formatter|aeschli|0.0.2|
|beautify|HookyQR|0.7.4|
|docthis|joelday|0.3.11|
|debugger-for-chrome|msjsdiag|2.5.3|
|code-settings-sync|Shan|2.4.3|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by Tyriar** [comment]
By the error it sounds like another app/process was using the file. Try closing other programs and trying again.

**Comment by lalalawututu** [comment]
I try to it again,but it is valid.i like vsc very much.I hope to find a solution.Thanks you,sir.Your answer let me excited.
