### ISSUE TITLE
Go syntax highlighting breaking if map defined on single line with square brackets in string

### ISSUE THREAD

**Issue by paulslevin** [microsoft/vscode#205005]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.1 (Universal)
- OS Version: Mac OS 14.3.1 (23D60)

The issue occurs if square brackets are included in a map value, and if the map is defined on one line.

Steps to Reproduce:

1. Create the following minimal example:
```
package test

import "fmt"

func f() {
	m := map[string]string{"key": "[]"}
	fmt.Println("this is highlighted wrongly", m)
}
```
This looks like:
<img width="375" alt="Screenshot 2024-02-12 at 14 53 47" src="https://github.com/microsoft/vscode/assets/16257798/083b2e54-a0d2-47f8-9368-a177983fc722">

This issue happens if you do this too:
```
package test

import "fmt"

func f() {
	m := map[string]string{"key": `[]`}
	fmt.Println("this is also highlighted wrongly", m)
}
```
<img width="401" alt="Screenshot 2024-02-12 at 14 53 59" src="https://github.com/microsoft/vscode/assets/16257798/1c86f5cc-a82b-4ff5-872b-f1b79d63ec20">

**Comment by paulslevin** [comment]
I checked and this issue specifically occurs with a closing square bracket:
```
<img width="372" alt="Screenshot 2024-02-12 at 14 55 51" src="https://github.com/microsoft/vscode/assets/16257798/27aed306-cd89-4cc6-b56c-5ab018196a2e">
```

**Comment by paulslevin** [comment]
The issue does not occur if the map is defined multiline:
<img width="319" alt="Screenshot 2024-02-12 at 15 00 04" src="https://github.com/microsoft/vscode/assets/16257798/f0934066-e560-4598-9c49-c97c60bc2b10">

**Comment by RedCMD** [comment]
Already fixed in the latest version of the Go grammar
@alexr00 update VSCode grammar?

**Comment by alexr00** [comment]
Already done last week! https://github.com/microsoft/vscode/commit/fc771c597f7e15500921e7965f999338f2dccbd1

@paulslevin to get the fix immediately you can try out [VS Code insiders](https://code.visualstudio.com/insiders/).
