### ISSUE TITLE
Expose API whether shell integration is working or not

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#205058]
We've been trying to figure out for ourselves using various means whether shell integration is working or not:
- Using terminal data write event
- Using terminal command event

Unfortunately each of them have not been reliably working for our users, resulting in various [bug reports](https://github.com/microsoft/vscode-python/issues?q=is%3Aopen+is%3Aissue+label%3Aexperimenting).

We need this information to use `collection.prepend` functionality correctly, to make sure we prepend exactly "once". Couple of solutions we could go with:
- Change behavior of `collection.prepend` internally to make sure we prepend exactly once even when `applyAtShellIntegration` and `applyAtProcessCreation` both are `true`. 
- Expose an API to reliably tell extensions whether shell integration is working.

**Comment by Tyriar** [comment]
This is what I'm thinking here:

```ts
	export interface TerminalState {
		/**
		 * Whether the {@link Terminal} has had [shell integration](https://code.visualstudio.com/docs/terminal/shell-integration)
		 * activated. This typically happens shortly after the terminal has been created.
		 */
		readonly isShellIntegrationActivated: boolean;
	}
```

This uses the existing `TerminalState` and event to expose it. This would make sense to implement with https://github.com/microsoft/vscode/issues/145234 as it also introduces shell integration-related APIs.

**Comment by Tyriar** [comment]
Merging this request into https://github.com/microsoft/vscode/issues/145234 as they're so closely related and influence each other.
