### ISSUE TITLE
Can't parse global variable in TypeScript

### ISSUE THREAD

**Issue by TonyPythoneer** [Microsoft/vscode#20504]
- VSCode Version: 1.9.1
- OS Version:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
```

 If anyone has the same problem, please set `+1` to express you have, too.

I have a question. I had declared a global variable in Typescript. Why can't  IDE properly parse?

example:

a_module.js
```js
global.this_is_a_constant = 100;
```

a_module.d.ts
```js
declare var this_is_a_constant: number;
```

When I tried to import it and call it,
```js
import 'a_module';
console.log(this_is_a_constant)
```

it will show error message:
```
[ts] Cannot find name 'this_is_a_constant'.
any
```

But in Nodejs, it can correctly process and output on terminal.

Is it a bug?

**Comment by mjbvz** [comment]
Try creating a `jsconfig.json` or `tsconfig.json` with the contents: `{}` at the root of your project. This will ensure that VSCode understands these three files are part of the same project. After trying this, I no longer see any errors
