### ISSUE TITLE
意外终止

### ISSUE THREAD

**Issue by lnhn** [Microsoft/vscode#20506]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|typescript-react-snippets|abotteram|0.1.9|
|html-snippets|abusaidm|0.1.0|
|one-monokai|azemoh|0.2.4|
|vscode-standardjs-snippets|capaj|0.3.0|
|cocos-creator|Chukong Technologies|0.0.1|
|cocos-debug|Chukong Technology|0.0.1|
|python|donjayamanne|0.5.8|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|Theme-TwoStones|gerane|0.0.2|
|Theme-zacks|gerane|0.0.2|
|NodeAssertionSnippets|jaymorrow|0.1.0|
|vscode-simple-icons|LaurentTreguier|0.10.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|MagicPython|magicstack|1.0.6|
|csharp|ms-vscode|1.7.0|
|debugger-for-chrome|msjsdiag|2.5.2|
|typescript-hero|rbbit|0.12.0|
|html5-boilerplate|sidthesloth|1.0.1|
|python|tht13|0.2.3|
|pygame-snippets|tushortz|0.0.1|
|python-extended-snippets|tushortz|0.0.1|
|JavaScriptSnippets|xabikos|1.4.0|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Closing as not actionable. 

Please provide some information about the issue so that we can investigate
