### ISSUE TITLE
Copilot Chat UX improvements

### ISSUE THREAD

**Issue by yannxaver** [microsoft/vscode#205059]
Copilot chat defaults are currently the opposite of what I would consider an enjoyable UX

#### 1. Pressing CMD + U should leave dictation on until I confirm with enter.
- Good prompts take time and thinking and I can't think if I know that once I stop talking for two seconds the dictation will finish and send my prompt
- I also don't want to hold down any buttons while talking. Please just let me talk and then confirm once I'm finished. That is also how dictation works on iOS and macOS.
- it should also be possible to edit the recorded prompt before sending, because voice to text accuracy is not flawless, especially for people who are not native speakers

#### 2. Default context for the prompt should be all the visible code in my active workspace
- \>90% of the time I am prompting something related to the code I'm looking at right now
- if I want to run a general prompt without relation to the current code then I should define that explicitly

#### 3. Ideally copilot chat would edit the file I'm currently in based on my prompt and then ask me if I want to keep the changes or not. 
- it shouldn't just give the options to copy the generated code or insert it exactly where my cursor is. Most of the time both of these options are not really what I'm looking for.
- it would be much better if it automatically inserts the code at the right spots in the current file and then asks me to confirm the changes
- this works very well if I manually copy the file content into chatgpt 4 and then ask for a specific change. That's why I assume it should also be no problem for copilot chat to do the same while giving the convenience of staying in the editor

**Comment by jrieken** [comment]
>  Ideally copilot chat would edit the file I'm currently in based on my prompt and then ask me if I want to keep the changes or not.

Do you know about inline chat? It wants to be just that, chat and code modifications just within the editor. Trigger it with `cmd+i` or from the command palette.

**Comment by bpasero** [comment]
Please only report 1 issue per topic. You reported 3 issues, so please create 3.

I am responding to 1: you can disable this via `accessibility.voice.speechTimeout` by setting it to `0`.
