### ISSUE TITLE
Problem with hinting in javascript

### ISSUE THREAD

**Issue by gregoryyyy** [Microsoft/vscode#20509]
Please take a look at a git I pasted below. Why editor doesn't hint me method / properties in some cases.

https://thumbs.gfycat.com/ShorttermNiceCurlew-size_restricted.gif

**Comment by snaquaye** [comment]
I believe, at that point VSCode can't infer the data type for argument which was copied to arr. Using a typed language like Typescript, would give you a full scale hinting.

**Comment by Tyriar** [comment]
Yes @snaquaye is right. Whenever a type cannot be inferred it is made to be `any` which doesnt provide intillisense. That's why it works for `any[]` but not `any`
