### ISSUE TITLE
Terminal voice actions label

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#205066]
I find these labels hard to figure out:

![image](https://github.com/microsoft/vscode/assets/900690/e9c9e9dc-9334-410a-a15f-8db2a77f38fd)

I suggest:
* `Terminal: Start Voice Input`
* `Terminal: Stop Voice Input`

**Comment by meganrogge** [comment]
i'll probably remove these altogether since they're not useful

**Comment by bpasero** [comment]
Yes 👍

**Comment by meganrogge** [comment]
@Tyriar pointed out that since this is called out in the release notes, I should wait to remove it until there's a replacement IE until we have a universal `Voice: Start Dictation` command

**Comment by bpasero** [comment]
@meganrogge but at least align the labels? "Voice: Start / Stop Dictation in Terminal"

<img width="718" alt="image" src="https://github.com/microsoft/vscode/assets/900690/da9315d3-86d4-4b58-a343-a4da375539ac">

**Comment by Tyriar** [comment]
@bpasero isthe editor one going to become a generic `Voice: Start Dictation` that can be used anywhere?
