### ISSUE TITLE
the type script language is dies 5 times so what i do

### ISSUE THREAD

**Issue by kavithara** [Microsoft/vscode#20508]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.
2.

**Comment by charleslales** [comment]
Same issue.. :-o

**Comment by mjbvz** [comment]
Two probable causes:

1. You are opening a mapped network drive. This will crash TypeScript 2.1.6. We are tracking a fix here: https://github.com/Microsoft/TypeScript/issues/13997
1. If you see a message about a missing `typescript/...` file, you may be seeing #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

If neither seems to fit for what you are hitting, please let me know

**Comment by charleslales** [comment]
Hi, thx for feedback. You're right about the network shared folder.. I'll check as soon as I'm at work ;)
