### ISSUE TITLE
how can i debug configure in windows 10 using bash gcc

### ISSUE THREAD

**Issue by veerendra-nath** [Microsoft/vscode#20501]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Please provide more information.

**Comment by veerendra-nath** [comment]
i wish to debug the c programs in visual code using Linux bash(gcc), how can I configure it?

**Comment by veerendra-nath** [comment]
or can you help me with configure the visual code to debug the c programs ?

**Comment by joaomoreno** [comment]
Have you checked out the official guide? https://code.visualstudio.com/docs/languages/cpp
