### ISSUE TITLE
Interactive TextDocumentContent

### ISSUE THREAD

**Issue by leozdgao** [Microsoft/vscode#20502]
I'm trying to make a VSCode extension, which could show an interactive TextDocumentContent and there will be a list and some buttons on it, if I click a button, it will try to add some files in my workspace. Is there any chance to implement it? 🤕 

It seems the `TextDocumentContentProvider` only work for rendering but could not response to the user interaction?

**Comment by jrieken** [comment]
It is possible but not recommended. If you just want to add button you should maybe look into [`showQuickPick`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3738) or into [`showInformationMessage`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3602). Both allow you to show a choice of buttons and react to what was selected
