### ISSUE TITLE
Productise or remove explorer experimental custom hover

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#205061]
https://github.com/microsoft/vscode/blob/b2598b92d18ea1132e9cd35df776c8c22a7f9730/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L402-L420

**Comment by benibenj** [comment]
I'll make sure to adapt this when I finish the hover work for lists

**Comment by bpasero** [comment]
@lramos15 is the idea of the setting to be able to disable the hover in the explorer (https://github.com/microsoft/vscode/issues/173236)? Why did it never become a normal option then but experimental?

**Comment by lramos15** [comment]
Redmond agreed that disabling the hover completely was a bad idea since it would open the door up for people requesting settings for disabling the hover in many different places. Instead we aimed to solve the main problem I heard about the explorer hover which is that it does not include useful information and can actually obstruct the information the explorer displays. For this, we aimed to try to implement a hover similar to what windows does but it ended up causing too many regressions

**Comment by bpasero** [comment]
@lramos15 but people that are annoyed by the hover can configure a high hover delay (I actually do that) and then this should be OK no?

**Comment by benibenj** [comment]
@lramos15 do we have users using the experimental custom hover? I also gave it a try to have it similar to the windows explorer but it is not possible to do this well. So personally I think we can remove the experimental explorer hover.

**Comment by benibenj** [comment]
Regarding #173236: I agree with @lramos15. Changing the hover delay should not be the solution as it affects all hovers in the workbench. Also adding a setting for disabling the hover in the explorer might have the danger of users wanting to support it in all other places individually which would not be great, but we still need to find a better solution here so having a setting for just the explorer might have to be a solution. Another option could be to show the hover to the side of the element making sure it does not cover any other elements

**Comment by lramos15** [comment]
@benibenj I think we can just remove the explorer hover code. It is very broken and not something we support, regardless of the users. I don't know anyone who is using it as I have not heard any discussion about it for quite some time.

**Comment by bpasero** [comment]
Then lets do that.
