### ISSUE TITLE
Show line number of found search phrases in `search` menu

### ISSUE THREAD

**Issue by Ramin-RX7** [microsoft/vscode#205083]
Is it possible to have the line number of parts where our search phrase has been found?

![Screenshot (199)](https://github.com/microsoft/vscode/assets/52785580/de909621-2ec0-4906-9411-94fd766a914e)

I find this useful for myself (may not be for others)

**Comment by andreamah** [comment]
You can enable `search.showLineNumbers` in your settings for this.
