### ISSUE TITLE
Notebook Search not working in Remote Repo Search

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#205044]
Steps to Reproduce:

1. Open up a remote repo on a local install of vscode.
2. `search.experimental.closedNotebookRichContentResults: true`
3. Try searching.
4. Notice a ENOENT error

**Comment by andreamah** [comment]
With https://github.com/microsoft/vscode/pull/205045, this will fail silently (not return notebook results).

**Comment by osortega** [comment]
Search seems to be working in remote environments, verified with Codespaces.
