### ISSUE TITLE
Deleting a notebook cell, clicking the bottom of the notebook and undo does not work

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#205028]
Repro:

1. Create 3 cells
2. Delete the middle one
3. Click the empty space at the bottom of the notebook
4. Press undo 🐛 it doesn't work, clicking in between cells does work though

**Comment by Yoyokrazy** [comment]
Specifically, undo only works when focused on a cell container. Focus within a cell (code or markdown) editor and in the notebook editor both do not handle the undo.
