### ISSUE TITLE
C++ custom class names not highlighted

### ISSUE THREAD

**Issue by Leedehai** [Microsoft/vscode#20500]
- VSCode Version: 1.9.1
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. open a C++ file, type in:
```C++
class A {
private:
  int x;
public:
  A(int _x) {
	  x = _x;
  }
  A operator+(A &a) {
	  x++;
	  return *this;
  }
  A operator*(int c) {
	  x *= c;
	  return *this;
  }
  int get_value() {
	  return x;
  }
};

int main() {
	A a = A(1);
	return 0;
}
```
2. The class name "A" will not be highlighted the same way other built-in types (like "int") are, in lines like "A operator+(A &a)" and "A a = A(1)". But in Visual Studio custom class names are highlighted. 
3. Similar: #4948

**Comment by aeschli** [comment]
The cpp grammar does not break up "A operator+(A &a)" and "A a = A(1)" in separate tokens.

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#207
