### ISSUE TITLE
Debug icons can get lost below traffic lights

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#205011]
I have no idea how I got here, I didn't even more the debug toolbar around.

<img width="250" alt="image" src="https://github.com/microsoft/vscode/assets/4544166/b8b47321-40b8-40d0-afb1-6e6337fa6d0a">

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/204265#issuecomment-1931236889
