### ISSUE TITLE
lightbulb doesn't show

### ISSUE THREAD

**Issue by hamid3pnn** [microsoft/vscode#205189]
Type: <b>Bug</b>

Hi in latest vs code version, lightbulb doesn't show at all in any line or code , i reinstalled several times and even check uncheck lightbulb also but nothing changed

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (4.61GB free)|
|Process Argv|--crash-reporter-id 60358de2-0234-4e8e-ad37-27b776ba135a|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```

</details>

<!-- generated by issue reporter -->
```[tasklist]
### Tasks
```

**Comment by hamid3pnn** [comment]
no fix?

**Comment by justschen** [comment]
@hamid3pnn have you tried checking the `editor.lightbulb.enabled` setting?

**Comment by hamid3pnn** [comment]
> editor.lightbulb.enabled

yes lightbulb is enabled and i'm working with html,css,javascript

**Comment by justschen** [comment]
@hamid3pnn this is because it's likely that you don't have any extensions that contribute code actions in html and css (if you don't have extensions, lightbulb won't show in html and css because there are no code actions to show). 

In js, if `editor.lightbulb.enabled` is `on`, lightbulb should show everywhere. if it's set to `onCode`, it won't show in empty spaces.

**Comment by hamid3pnn** [comment]
yes true i don't have any extension , so will try with extension again thanks
