### ISSUE TITLE
Inspect TM Scopes is not designed for big code.

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#20511]
os: sierra
vscode: latest and greatest!

Take [this code](https://github.com/karyfoundation/karyscript/blob/master/src/compiler/grammar/grammar.pegjs#L1705-L1736). When you try to inspect the tokenizer's scopes you'll end up with this:

<img width="922" alt="screen shot 2017-02-12 at 9 09 07 pm" src="https://cloud.githubusercontent.com/assets/2157285/22864484/9f815020-f167-11e6-9a17-0d0a7dd69186.png">

I'm not sure if it's even worthy of getting investigated but well a simple box sizing can fix it I think

**Comment by Tyriar** [comment]
Verified, it might look better using the ellipsis character '…' over '...' though

![image](https://cloud.githubusercontent.com/assets/2193314/23286148/9d9eb0aa-f9ea-11e6-89c7-518978175bd2.png)

![image](https://cloud.githubusercontent.com/assets/2193314/23286159/af94206a-f9ea-11e6-8be4-5c8226cb5b33.png)

**Comment by pmkary** [comment]
@alexandrudima @Tyriar thanks a lot!
