### ISSUE TITLE
"Convert Indentation to {tabs,spaces}" only effects auxwindow

### ISSUE THREAD

**Issue by jswillard** [microsoft/vscode#205169]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.1
- OS Version: macOS Sonoma 14.2.1 (Darwin arm64 23.2.0)

Steps to Reproduce:

1. Drag a tab to open an auxwindow
2. Click spaces/tabs button in bottom right of main window
3. Convert indentation to tabs or spaces
4. See indentation updated in auxwindow but not main window

Additionally, once closing the auxwindow, clicking the tabs/spaces button on the main window will show "No active editors" and only returns to normal after running "Developer: Reload Window"

**Comment by bpasero** [comment]
Do you get the same when splitting the editor in the main window to be side by side?

**Comment by jswillard** [comment]
Splitting the editor side by side and using "convert indention to tabs" works as expected. Whichever editor in the side by side is focused is the editor that is converted to tabs.
