### ISSUE TITLE
Git push - permission denied

### ISSUE THREAD

**Issue by soyapark** [Microsoft/vscode#20517]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 14.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.6.2|
|format-php|Kasik96|1.1.2|
|python|donjayamanne|0.5.5|
|json-tools|eriklynd|1.0.2|
|php-intellisense|felixfbecker|0.0.12|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|color-highlight|naumovs|1.3.0|
|vscode-css-peek|pranaygp|1.2.4|
|text-marker|ryu1kn|0.3.0|

---

Steps to Reproduce:

1. Git push doesn't work. Permission denied
2. I set user name & emial but still

**Comment by joaomoreno** [comment]
Does it work from the command line?
