### ISSUE TITLE
debug controls are shifted to the top left corner when test execution paused

### ISSUE THREAD

**Issue by yury-s** [microsoft/vscode#205139]
Type: <b>Bug</b>

Run a test with playwright test extension and pause on a breakpoint.

The controls are shifted as on the screenshot.

<img width="264" alt="Screenshot 2024-02-13 at 11 31 36 AM" src="https://github.com/microsoft/vscode/assets/9798949/e942212b-38f9-48ee-9309-86b1599d8bce">

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:57.920Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 3, 4|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|. --crash-reporter-id 8130ff89-a81e-4322-ab26-25f737a64bd9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|14.8.0
codespaces|Git|1.16.10
copilot|Git|1.160.0
copilot-chat|Git|0.12.1
copilot-labs|Git|0.17.1121
csdevkit|ms-|1.3.10
csharp|ms-|2.15.30
vscode-dotnet-runtime|ms-|2.0.1
vscodeintellicode-csharp|ms-|0.1.26
playwright|ms-|1.0.22
remote-containers|ms-|0.338.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30962250
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
b5d27386:30958190
a89i1917:30961429
7j2b6412:30962116
e3gdj431:30958358

```

</details>

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/204265
