### ISSUE TITLE
Quick Search should omit history

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#205135]
Steps to Reproduce:

1. Use quick search and look at results from different files.  (`%<text-here>` in quick open)
2. `esc`
3. Go back in history (either using command center or 'Go Back' command).
4. Notice that all of the files navigated to during quick search are in the history :bug:

Especially if the user looks at a lot of files, they probably don't want that info in their history.

**Comment by eleanorjboyd** [comment]
how do I do this:

`Go back in history (either using command center or 'Go Back' command).`

**Comment by andreamah** [comment]
There should be a `Go back` command in the command palette. Do you see it?

**Comment by eleanorjboyd** [comment]
<img width="782" alt="image" src="https://github.com/microsoft/vscode/assets/26030610/55fc0c50-7fad-45e1-825d-810d7a4b5771">
 I have these but they don't do anything when I select them after being on the experimental search

**Comment by andreamah** [comment]
You can also use these arrows in the command center
<img width="351" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/5b02f9dd-2f2f-4e04-b1fc-e5f617e986c9">
