### ISSUE TITLE
Add a new method `appendUnstampedLine` to `LogOutputChannel`

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#205172]
Feature Request

> Maybe we want a new method `LogOutputChannel.appendUnstampedLine`.

_Originally posted by @gjsjohnmurray in https://github.com/microsoft/vscode/issues/194953#issuecomment-1749931962_

See discussion on the original issue (now locked) for justification.

**Comment by sandy081** [comment]
@gjsjohnmurray I have reopened the linked issue.
