### ISSUE TITLE
Remote explorer/tunnel is not working after update to Januari release

### ISSUE THREAD

**Issue by waardd** [microsoft/vscode#205179]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Remote tunnel / remote explorer
- OS Version: W10 and W11

Steps to Reproduce:

1. Downgraded VSCode to the Dec 2023 1.85.2 version
2. Upgraded back to Jan 1.86.x version

With the Januari update the functionality of remote tunneling changed.
When accessing a remote port via localhost:8081 the endpoint is either not reached or not handled properly.
Messages like Emptry response, Note reachable, blanc screen are then happening.

When i uninstalled VSCode and installed the 1.85.2 version it all worked fine and the endpoint(s) can be used.

If i then again update to the latest version it stops working again.

I am syncing settings in GitHub

**Comment by gjsjohnmurray** [comment]
Please confirm whether or not you retried with 1.86.1

Also, what exact OS version the remote server is running.

**Comment by waardd** [comment]
Red Hat Enterprise Linux release 8.9 (Ootpa)
4.18.0-513.11.1.el8_9.x86_64

I did retry with the latest version 1.86.1 and it still did not work.

That is untill a collegue discovered a setting:

Remote SSH: **Use Exec Server**

This was on. And when we turned it off it seems to work again.

Don't know how this makes sense, but it works.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-remote-release/issues/9548
