### ISSUE TITLE
[Javascript] Syntax highlighting breaks for specific variable name

### ISSUE THREAD

**Issue by EthanRutherford** [Microsoft/vscode#20514]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.5|
|contextualduplicate|lafe|0.2.0|
|cpptools|ms-vscode|0.10.1|
|seti-icons|qinjia|0.1.3|

---
For some reason, for a specific name, VS code stops highlighting one specific token after a certain line in the file. The file is not terribly long (303 lines), no lines are terribly long, and the name is syntax highlighted on one line (light blue), not syntax highlighted on the next (white). In this instance the variable name is `path`. Changing the name to something else highlights appropriately, but it does not fix the problem as changing it back to `path` breaks it again. I have no idea how it gets in this state, so I can't really provide steps to reproduce, it seems completely arbitrary.

![image](https://cloud.githubusercontent.com/assets/5589147/22865712/abdb83ca-f11e-11e6-807c-063f5126e0ce.png)

**Comment by EthanRutherford** [comment]
Additional information: it seems to be broken for the variable path anywhere in the file. The only reason that the two instances above (on the first line of the function) are highlighted is that one is proceeded by `let` and the other is a property of an object.

**Comment by Tyriar** [comment]
Please file an issue upstream for this one https://github.com/Microsoft/TypeScript-TmLanguage
