### ISSUE TITLE
menu align without space ident

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [microsoft/vscode#205187]
Does this issue occur when all extensions are disabled?: Yes，same behavior as plugins loaded.

- VS Code Version: 
```sh
Version: 1.86.1
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:07:19.849Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.6.10-1-MANJARO
```

- OS Version: 

```sh
$ screenfetch 

 ██████████████████  ████████     mmc@p53
 ██████████████████  ████████     OS: Manjaro 23.1.3 Vulcan
 ██████████████████  ████████     Kernel: x86_64 Linux 6.6.10-1-MANJARO
 ██████████████████  ████████     Uptime: 3h 50m
 ████████            ████████     Packages: 1408
 ████████  ████████  ████████     Shell: zsh 5.9
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: Xfce4
 ████████  ████████  ████████     WM: Xfwm4
 ████████  ████████  ████████     WM Theme: JacWin10
 ████████  ████████  ████████     GTK Theme: Windows10 [GTK2]
 ████████  ████████  ████████     Icon Theme: Faenza
 ████████  ████████  ████████     Font: 文泉驿等宽微米黑 10
 ████████  ████████  ████████     Disk: 303G / 483G (66%)
                                  CPU: Intel Core i7-9750H @ 12x 4.5GHz [46.0°C]
                                  GPU: Quadro T1000
                                  RAM: 3088MiB / 31867MiB
```

Steps to Reproduce:

1. open code
2. click menu

if i uncheck auto save, the ident space will be disappeared, but it seems too ugly, should the space ident always be turned on? just  as previous versions.
![correct](https://github.com/microsoft/vscode/assets/7458713/b163f3e0-37be-4556-902a-3ace69725f82)

![11](https://github.com/microsoft/vscode/assets/7458713/caec1f74-3569-465c-9e5e-5420b09720c7)
![333](https://github.com/microsoft/vscode/assets/7458713/842d9b87-dcca-4538-a0f7-75f26a785554)

![222](https://github.com/microsoft/vscode/assets/7458713/6b57ae6f-f757-4170-a15b-aea060a86b06)

**Comment by TylerLeonhardt** [comment]
This is the same behavior as macOS, Windows, and probably a lot of Linux distros so this was likely an intentional decision made by Electron. In any case, giving this to @deepak1556 to confirm.
