### ISSUE TITLE
notebook variable view doesn't initialize if cell is run too quickly

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#205118]
Steps to Reproduce:

1. set `"notebook.experimental.notebookVariablesView": true,`
2. open a notebook and put `x=1` in a cell and run it to establish a kernel for that notebook
3. reload vscode and run the cell before the kernel is auto-selected

:bug: notebook variable view will not initialize

**Comment by aiday-mar** [comment]
HI @amunger is this a candidate? I noticed you assigned this issue to the recovery 2 milestone,  but this issue does not have a candidate label. There appears to only be one PR to main.
