### ISSUE TITLE
Wrong handling of nested for loops #205116

### ISSUE THREAD

**Issue by MikeEitel** [microsoft/vscode#205117]
Type: <b>Bug</b>

SORRY if double as also send direct via Github. issues/205116

void loop() {
  cyd.fillScreen(ILI9341_BLACK);
  cyd.setCursor(0, 0);

  for(int j = 1; j <= 5; j++) {
    switch(j) {
      case 1: cyd.setFont(); break;
      case 2: cyd.setFont(&TomThumb); break;
      case 3: cyd.setFont(&Picopixel); break;
      case 4: cyd.setFont(&Tiny3x3a2pt7b); break;
      case 5: cyd.setFont(&Org_01); break;
      default: break;
    }
    
    for (int i = 32; i < 128; i++) { // Start from ASCII value 32 (space)
      Serial.print(i); // Print the ASCII value
      Serial.print(" "); 
      cyd.print((char)i);
      delay(10);
    }
  }
  delay(3000);
}

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.65GB (24.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-standard-format|che|0.0.12
format-json|Cle|1.0.3
doxdocgen|csc|1.4.0
compareit|in4|0.0.2
better-cpp-syntax|jef|1.17.2
xml-format|mik|1.1.3
nc-gcode|ML|0.13.0
vscode-html-format|moh|0.1.6
vscode-docker|ms-|1.28.0
vscode-language-pack-de|MS-|1.85.2024020709
debugpy|ms-|2024.0.0
isort|ms-|2023.10.1
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.1
jupyter|ms-|2024.1.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.338.1
remote-ssh|ms-|0.108.0
remote-wsl|ms-|0.86.0
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
notepadplusplus-keybindings|ms-|1.0.7
remote-explorer|ms-|0.4.1
color-highlight|nau|2.5.0
select-compare-tabs|out|1.0.3
platformio-ide|pla|3.3.3
cmake|twx|0.0.17

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
This doesn't sound like a vscode issue, but there is not enough detail to understand the issue
