### ISSUE TITLE
GitHub CodeSpaces VsCode Speech Unsupported

### ISSUE THREAD

**Issue by alwell-kevin** [microsoft/vscode#205114]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Open CodeSpace locally, install VsCode Speech. Try to invoke.
2. Terminate codespace, try again. Works! 

![Image](https://github.com/microsoft/vscode/assets/26548363/5e1ba9a3-afa9-4402-bf4a-98dfd3c7e418)

**Comment by bpasero** [comment]
Try https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-speech
