### ISSUE TITLE
Non-internal JSONC files reporting `jsonc(519)` on trailing commas

### ISSUE THREAD

**Issue by mrmckeb** [microsoft/vscode#205168]
Type: <b>Bug</b>

As of Prettier 3.2, JSONC is now fully supported, and trailing commas are applied (on by default).
https://prettier.io/blog/2024/01/12/3.2.0#json

This issue occurs when extensions are disabled, and in a fresh installation of Insiders.

1. Create a JSONC file (i.e. `test.jsonc`).
2. Add an object with some keys.
3. Add a trailing comma to the last line, or format with Prettier 3.2+.

```jsonc
{
  "property": "value",
}
```

VS Code version: Code 1.86.1 (Universal) (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:09:01.236Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 7, 7|
|Memory (System)|16.00GB (0.36GB free)|
|Process Argv|--crash-reporter-id 82f23d23-e47d-41ab-bdb3-a5becc651759|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30959800
edj9j583:30958191
a89i1917:30961429
7j2b6412:30962116
bg6jg535:30958357

```

</details>

**Comment by mrmckeb** [comment]
The only other reports I found were related to the internal/settings files:
- https://github.com/microsoft/vscode/issues/126024
- https://github.com/microsoft/vscode/issues/80419

**Comment by RedCMD** [comment]
trailing commas can only be enable via schema atm
using `"trailingCommas"` iirc

**Comment by aeschli** [comment]
If I understand right, prettier now can format files that end with `.jsonc` and automatically adds a trailing comma?

But a. `jsonc` is not a well-defined standard and it depends on the use case of the file whether trailing commas are allowed.

I don't think that's a smart decision from prettier, We have several issues files against us for not detecting training commas.
See https://github.com/microsoft/vscode/pull/203387#issuecomment-1909686444 for more background.

**Comment by mrmckeb** [comment]
Yes, that's correct. From the blog post I linked to:
> Previously, we infer the parser of `.jsonc` files to be `json`, but if we want keep the trailing comma, we'll have to use a hacky workaround config `{parser: "json5", quoteProps: "preserve", singleQuote: false}`.
>
> The new added `jsonc` parser:
> - Always quote the object keys.
> - Wrap strings with double quotes.
> - Of course, respect the [`trailingComma`](https://prettier.io/docs/en/options#trailing-commas) option.

As trailing commas are the default in Prettier, I expect that most users will now have trailing commas appended to JSONC files.

I personally don't mind this change, but do understand your concerns. If there are any quick fixes here, I'll take them :)

**Comment by aeschli** [comment]
As mentioned, we think we're on the safer side to report trailing commas by default, unless the schema associated to the file allows trailing commas. No changes planned on our side.

I will forward issues about trailing commas to Prettier.

**Comment by mrmckeb** [comment]
Raised in this thread, thank:
https://github.com/prettier/prettier/issues/15956
