### ISSUE TITLE
PowerShell command auto-complete in the editor panel not working

### ISSUE THREAD

**Issue by cybertechassociates** [microsoft/vscode#205134]
Type: <b>Bug</b>

Auto-compelte works as expected int the terminal but not working in the editor panel

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|47.89GB (31.85GB free)|
|Process Argv|--crash-reporter-id 5e7202f7-be21-4864-8a96-386d3d07df36|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (72)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
azurepolicyextension|Azu|0.2.3
markdown-extension-pack|bat|0.7.0
emojisense|bie|0.10.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-preview-github-styles|bie|2.0.3
excel-to-markdown-table|csh|1.3.0
markdown-table-prettify|dar|3.6.0
vscode-markdownlint|Dav|0.54.0
docs-markdown|doc|1.0.3
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|14.8.0
codespaces|Git|1.16.10
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.80.1
mdmath|goe|2.7.4
gc-excelviewer|Gra|4.2.58
dummytextgenerator|gur|1.0.1
path-autocomplete|ion|1.25.0
markdown-shortcuts|mdi|0.12.0
vscode-medium-to-markdown|mos|0.2.0
azure-dev|ms-|0.8.0
vscode-azureappservice|ms-|0.25.1
vscode-azurecontainerapps|ms-|0.6.1
vscode-azurefunctions|ms-|1.13.3
vscode-azureresourcegroups|ms-|0.8.4
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.15.3
vscode-azurevirtualmachines|ms-|0.6.5
vscode-bicep|ms-|0.25.53
vscode-cosmosdb|ms-|0.20.1
vscode-docker|ms-|1.29.0
csharp|ms-|2.15.30
vscode-dotnet-runtime|ms-|2.0.1
debugpy|ms-|2024.0.0
isort|ms-|2023.10.1
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.1
jupyter|ms-|2024.1.1
vscode-ai|ms-|0.46.0
vscode-ai-remote|ms-|0.46.0
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.338.1
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
azure-account|ms-|0.11.6
azurecli|ms-|0.6.0
powershell|ms-|2024.0.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
vscode-node-azure-pack|ms-|1.2.0
vsliveshare|ms-|1.0.5905
azurerm-vscode-tools|msa|0.15.11
vscode-sanddance|msr|4.1.0
vscode-yaml|red|1.14.0
kuskus-extensions-pack|ros|1.0.10
kuskus-kusto-language-server|ros|1.0.39
kuskus-kusto-syntax-highlighting|ros|1.2.0
markdown-preview-enhanced|shd|0.8.11
code-spell-checker|str|3.0.1
vscode-markdown-paste-image|tel|1.0.2
errorlens|use|3.16.0
vscode-icons|vsc|12.7.0
vscode-todo-highlight|way|1.0.5
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.6.2
material-theme|zhu|3.16.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30962250
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d6fi2104:30959263
pydisww1:30959800
e3gdj431:30958358

```

</details>

**Comment by cybertechassociates** [comment]
Hi, 
Attached is the screenshot.
[2024-02-13_18-41-52.pdf](https://github.com/microsoft/vscode/files/14271187/2024-02-13_18-41-52.pdf)

**Comment by cybertechassociates** [comment]
Screenshot is attached
![2024-02-13_18-41-52](https://github.com/microsoft/vscode/assets/126304913/675c5cae-c955-4d43-9c12-903636092934)

**Comment by meganrogge** [comment]
Looks like you're in the editor, where autocompletion  is not expected. You can drag the terminal into the editor area if that's what you're trying to do

**Comment by cybertechassociates** [comment]
Sorry, but I don't think it's correct unless I described the issue incorrectly. On a different computer, Intellisence works as expected.
