### ISSUE TITLE
Does not Select file according to key press

### ISSUE THREAD

**Issue by khaled-hossain-code** [Microsoft/vscode#20519]
- VSCode Version: 1.9
- OS Version: win 10

Steps to Reproduce:

1.open vscode and select any file, ex: if I have index.html & app.js file in my folder. I have selected app.js and I want to select index.html among other hundred of files. I pressed 'i' but the selection does not move to any file starting with i. its a common feature of windows.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10026
