### ISSUE TITLE
Disable inline red text on broken rules

### ISSUE THREAD

**Issue by olofsjo1SICKAG** [microsoft/vscode#205132]
Since updating VS Code and the plugin (don't know which changed this behavior I get a red test in the editor when breaking a rule:
![image](https://github.com/microsoft/vscode-flake8/assets/61141629/ee78d387-fc05-4fcf-925d-37c21a126901)
I would prefer to keep the old way where I only got the squiggly and the text as a hint when hovering. 

Is this possible to configure in some way? I cannot find it in the settings or documentation.

**Comment by justschen** [comment]
what settings do you have configured atm (in `settings.json`)

**Comment by olofsjo1SICKAG** [comment]
Thank you for the hints that it wasn't the flake8 plugin that was the problem. It was a totally different plugin setting, after adding this line to the settings it now works as before (it was a changed to the workspace settings that come from another developer that I had missed, it just correlated in time with an update of VS code).
`"errorLens.messageEnabled": false`
