### ISSUE TITLE
alpha channel of colors with transparency in tmTheme files are ignored

### ISSUE THREAD

**Issue by aziz** [Microsoft/vscode#20510]
in tmTheme files colors can be defined with alpha channel in #RRGGBBAA format
that last two digits are alpha channel in hexadecimal format. vscode at the moment ignores this.
It would be nice to be able to define colors with transparecy

- VSCode Version: 1.9.1
- OS Version: macOS 10.12.4

**Comment by Tyriar** [comment]
They certainly work in some cases like highlights, what specifically doesn't work for you?

**Comment by aziz** [comment]
I'm using this theme: 
https://tmtheme-editor.herokuapp.com/#!/editor/theme/PlasticCodeWrap

You can install it from the extension marketplace:
https://marketplace.visualstudio.com/items?itemName=allenbar.theme-plastic-ab

Steps to reproduce: 
1. open a document and set it in HTML mode
2. according to the theme, html tags should have this color: `#9EFFFFAB` (notice the transparency bit at the end)
3. but they're shown in this color:  `#9EFFFF`
4. When I'm using `Inspect TM Scopes` I'm actually getting the correct color, but it's not just applied correctly.

```
head(4 chars)

language	html
token type	Other
font style	---
foreground	#9EFFFFAB
background	#00161B
entity.name.tag { "foreground": "#9EFFFFAB" }
entity.name.tag.structure.any.html
meta.tag.structure.any.html
text.html.basic
```

**Comment by Tyriar** [comment]
Actually I think for foreground opacity may be prohibited to ensure text is able to use sub-pixel rendering. /cc @alexandrudima

**Comment by Tyriar** [comment]
@aeschli themes that do this will disable subpixel rendering within the editor, I think we should just disallow it because of this?

**Comment by aeschli** [comment]
@Tyriar I talked to Alex and he said that unless we use alpha for the background we're fine.
