### ISSUE TITLE
`Developer: Open Log File...` displays unsorted quickpick

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#205170]
Type: <b>Bug</b>

![image](https://github.com/microsoft/vscode/assets/6726799/a2f48dcc-e30b-4c98-b4dd-e5ed4f039737)

I think the log files are listed in the order the LogOutputChannels got created. Unless this is intentional / important I suggest we sort them alphabetically. I also propose adding the contributing extension's ID as the description element of the list item for LogOutputChannels created by extensions.

VS Code version: Code - Insiders 1.87.0-insider (b2598b92d18ea1132e9cd35df776c8c22a7f9730, 2024-02-13T05:47:27.450Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by sandy081** [comment]
Changed it to show in the same way like in the output channel dropdown

![Image](https://github.com/microsoft/vscode/assets/10746682/55a2f473-2c26-4258-a997-afe4dc3d2f13)

**Comment by alexr00** [comment]
This is a little confusing because a provider that shows in the Output view dropdown might not show in "Developer: Open Log File...". I assume this is because Output has all output channels and "Open Log File" only has log output channels.

**Comment by sandy081** [comment]
Thats right. Not all output channels are logs.
