### ISSUE TITLE
vscode extension add tab after terminal

### ISSUE THREAD

**Issue by oknoorap** [Microsoft/vscode#20521]
How to add tab after terminal, is there any documentation or extension API doesn't support it yet?

![http://image.prntscr.com/image/72f119a9b08349a79db9b641f251b441.png](http://image.prntscr.com/image/72f119a9b08349a79db9b641f251b441.png)

**Comment by Tyriar** [comment]
No you cannot add panels via the API currently.

**Comment by oknoorap** [comment]
any plans to add this experimental feature, like tree explorer panels?

!(https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-explorer-sample)[https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-explorer-sample]

**Comment by Tyriar** [comment]
Not sure what the timeline for custom tree explorers is.
