### ISSUE TITLE
 "editor.wrappingIndent":"same" has no effect. Wrapping Indent does not work.

### ISSUE THREAD

**Issue by pawelkontek** [microsoft/vscode#205212]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.86.1
- OS Version: MacOS 14.0 (23A344)
<img width="917" alt="image" src="https://github.com/microsoft/vscode/assets/7879784/d6597f41-a92b-41d1-beaf-c89c87006d2b">

Steps to Reproduce:
I understand that this might be hard to reproduce, but here is what I've done to make sure I am running "fresh" install of VS Code:

1. Remove VS Code with this command: https://stackoverflow.com/questions/42603103/how-to-completely-uninstall-vs-code-on-mac
2. Install the newest VS Code – changing the `"editor.wrappingIndent": "same",` doesn't do anything.

I am pulling my hair off, but I can't make it work. What can be the reason?

**Comment by rmnldwg** [comment]
I have the same issue: `"editor.wrappingIndent"` seems to have no effect at all, regardless of what I set it to. The wrapped lines are always indented by as many spaces as `"editor.tabSize"` is set to.

**Comment by alexdima** [comment]
Does this reproduce in a new window in a plain text file? Could you please check if this something specific to a particular programming language or to a particular folder (folder settings)?

**Comment by rmnldwg** [comment]
I just checked and the issue seems to be gone 😅

I did change a couple of extensions and there was at least one update since the last time I consciously checked whether the issue was still present, so maybe one of those things fixed it?

Anyways, thanks for getting back to us and sorry I cannot provide more info!
