### ISSUE TITLE
same extension listed two times after updating an extension

### ISSUE THREAD

**Issue by Vishal-Isharani** [Microsoft/vscode#20525]
- VSCode Version: 1.10.0-insider
- OS Version: windows 10 

Steps to Reproduce:

1.update extension 
2.new item [ same extension with update available ] will be added in installed extension list 
![vs3](https://cloud.githubusercontent.com/assets/10386581/22871595/61e7b2d8-f1d8-11e6-9aed-4d1e9b33be3b.png)

**Comment by Vishal-Isharani** [comment]
closing this latest update fix this 
thanks

**Comment by joaomoreno** [comment]
ping @sandy081

**Comment by sandy081** [comment]
Related to #19685
