### ISSUE TITLE
Request option to relocate Workbench Status bar to Top

### ISSUE THREAD

**Issue by rdhar** [microsoft/vscode#205242]
### Summary

In short, I'd like to have the option to move/reposition the Workbench Status bar location to the top of the window, above editors tabs.

### Reasoning

The ability to customize layout has been critical for improving the accessibility of various panels and bars to be in optimal positions for any given user. In particular, the `"workbench.activityBar.location": "top"` setting is ideal for relocating the core Activity Bar icons away from the very edge of the (wide)screen to be within eyeline and closer to the editor where focus tends to be.

Similarly, having the option to move the Workbench Status bar to the top aids in moving various status text/icons within eyeline focus. Though, I would imagine that hover-tooltips and the notification drawer may need to be reworked to flow below, rather than above.

### Visualization

To help better visualise this request, here's a mock-up of the requested outcome after the Workbench Status bar has been repositioned to the top.

![image](https://github.com/microsoft/vscode/assets/19497993/7a5def9b-6fbc-4383-bbfa-72ad3ee790a8)

### Aside

While tangentially related, I'd imagine it'd be preferable to customize the ordering of entries within the Workbench Status itself, though that's addressed in #35744 already.

Thank you for your time and consideration.

```[tasklist]
### Tasks
```

**Comment by gjsjohnmurray** [comment]
See also #204933 which needs upvotes to progress.

**Comment by rdhar** [comment]
Thanks for the heads-up, @gjsjohnmurray, I should've looked for similar issues first! To minimise clutter, I'll move my post to that thread to keep us on the same page together.

Since this ticket has an assignee -- hi @daviddossett! -- I've moved/merged this discussion with #204933. Thank you!
