### ISSUE TITLE
Feature request: Code hinting/Intellisense for custom angularJS modules

### ISSUE THREAD

**Issue by cozzbie** [Microsoft/vscode#2052]
Would be really lovely if VSC can support hinting and intellisense for custom angular modules created by devs in a project and not just the default angularJS support.

1: Create a new angularJS module e.g services in a separate file eg services.js
2: return to a separate file say controller.js and create a new controller.
3: reference service from controller and as one is typing code hints and intellisense popup showing related function created in service.

Thanks

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#6643
