### ISSUE TITLE
No way to search for VSCode update from VSCode

### ISSUE THREAD

**Issue by tonylucas** [microsoft/vscode#205210]
Type: <b>Feature Request</b>

In "code" menu there was a menu to search for updates, but it disappeared. Now I have to go to google to find updates... And I can't have automatic updates anymore...

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:57.920Z)
OS version: Darwin arm64 23.3.0
Modes:

**Comment by gjsjohnmurray** [comment]
Do you see any update-related messages on the Main channel of the Output view?

**Comment by tonylucas** [comment]
was this setting : extensions.autoUpdate
