### ISSUE TITLE
Freeze Other Threads in Debugger For C# (atleast)

### ISSUE THREAD

**Issue by Garwin4j** [microsoft/vscode#205230]
As we trend towards multi-thread development being able to debug code that is run in parallel becoming more important. Visual Studio can freeze other threads so that the debugger doesn't jump across threads while stepping through. Ideally, it would be good to have a "Stick To Thread" button, but even a "Freeze Thread" button would be a good compromise.

**Comment by roblourens** [comment]
Please file this on the repo for the debug extension you're using
