### ISSUE TITLE
code-server `check-requirement.sh` fails if therer are two or more `libstdc++`

### ISSUE THREAD

**Issue by lesomnus** [microsoft/vscode#205220]
- VSCode Version: 1.86.1
- Local OS Version: Windows Home
- Remote OS Version:  Ubuntu 22.04.3 LTS
- Remote Extension/Connection Type: Containers over SSH?

- Logs:

Steps to Reproduce:

1. Create devcontainer from `library/gcc:13` or `ghcr.io/lesomnus/dev-gcc:13`
2. It is failed while connecting to devcontainer since `check-requirement.sh` fails.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: N/A

The images I mentioned above contains two `libstdc++`s:
1. `/usr/local/lib64/libstdc++.so.6`
2. `/lib/x86_64-linux-gnu/libstdc++.so.6`

As a result, in the following code:

https://github.com/microsoft/vscode/blob/903b1e9d8990623e3d7da1df3d33db3e42d80eda/resources/server/bin/helpers/check-requirements-linux.sh#L48-L73

branch block at line 59 is executed and `libstdcpp_path` set as
```
/usr/local/lib64/libstdc++.so.6 /lib/x86_64-linux-gnu/libstdc++.so.6
```

So it fails at line 72 since the variable `libstdcpp_path` is single string that contains two paths.

**Comment by deepak1556** [comment]
/fixedWIth https://github.com/microsoft/vscode/commit/f6a5654dbf9811b94dd8848571a84b73a7a34813
