### ISSUE TITLE
Preview md

### ISSUE THREAD

**Issue by zeewane** [Microsoft/vscode#20527]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-icons|robertohuertasm|7.2.0|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please provide some information about the problem

**Comment by mjbvz** [comment]
Dup of #20528
