### ISSUE TITLE
[less] problem with '&-2' selector

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#20522]
- VSCode Version: 1.9.0
- OS Version: Windows 10 x64

Hi, I have ignored all less warning like this:

`"less.lint.emptyRules": "ignore",
    "less.lint.fontFaceProperties": "ignore",
    "less.lint.hexColorLength": "ignore",
    "less.lint.argumentsInColorFunction": "ignore",
    "less.lint.unknownProperties": "ignore",
    "less.lint.propertyIgnoredDueToDisplay": "ignore"`

but in .less file, I still receive error messages, like image:
http://i.imgur.com/W1cVhpJ.png
How i can ignore it?

**Comment by ttn10** [comment]
any idea?

**Comment by ttn10** [comment]
Update:
http://i.imgur.com/MaVdvqo.png

**Comment by aeschli** [comment]
Can you please attach the source here. The less parser seems to have a problem with the '&-2' selector.

**Comment by aeschli** [comment]
You can turn off the whole less validation with `'less.validate.enable': false`

**Comment by ttn10** [comment]
Yes, but still not ok
http://i.imgur.com/mIXaYMp.png
:(

**Comment by aeschli** [comment]
Oh, sorry, it's
` "less.validate": false`

**Comment by ttn10** [comment]
Yes, it worked, thank you 👍
