### ISSUE TITLE
Preview the md does not work

### ISSUE THREAD

**Issue by zeewane** [Microsoft/vscode#20528]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-icons|robertohuertasm|7.2.0|

---

Steps to Reproduce:

1. write the md file
2. Ctrl + Shift + V，can`t preview the file

**Comment by javierglozano** [comment]
I tried to reproduce. In my case, the preview does work, but some glitch exists with preview view size when the size of text has been zoomed in.  The preview windows when showed in split mode does not cover the whole available windows space.

**Comment by mjbvz** [comment]
I'm also unable to repo this.

@zeewane Please provide some additional repo steps so that we can investigate.

**Comment by zeewane** [comment]
I`m sorry……after reboot my computer,the preview  is ok 



zeewane@qq.com
 
From: Matt Bierner
Date: 2017-02-14 06:26
To: Microsoft/vscode
CC: Zhiwei Qi; Mention
Subject: Re: [Microsoft/vscode] Preview the md does not work (#20528)
I'm also unable to repo this.
@zeewane Please provide some additional repo steps so that we can investigate.
