### ISSUE TITLE
its not giving me the option to run code

### ISSUE THREAD

**Issue by Mandygracemoore** [microsoft/vscode#205232]
i have been taking notes through this codespace. by rewriting code from lectures, then presenting the different concepts in different documents within a folder. I reuse a lot of code from an original problem and change it slightly to show a different output. This has been working great until now. it won't run the code that i paste into a new document.. even if I erase the pasted code and rewrite it, it will not run the code. I am frustrated because this was an efficient way to document different Python topics. please help me fix this issue

Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by roblourens** [comment]
It's not clear what the issue is, but it sounds like you're trying to run python code. If you're using features from the python extension for that, please file an issue on their repo with more context
