### ISSUE TITLE
Toggle git changes

### ISSUE THREAD

**Issue by sbland** [microsoft/vscode#205240]
Would it be possible to toggle file changes on and off? Perhaps in the source control view or individual changes in the diff view.
This would be useful for finding which change caused an issue for example.

**Comment by alfredbirk** [comment]
An alternative solution is to use the `Git: Revert Selected Ranges` command (you can set a keybinding for this) to remove a change and cmd+z to enable it again

**Comment by lszomoru** [comment]
@sbland, I would suggest that you use the "Revert Selected Ranged" feature as suggested above.
