### ISSUE TITLE
typescript 

### ISSUE THREAD

**Issue by skimki** [Microsoft/vscode#20526]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|Bookmarks|alefragnani|0.11.0|
|vscode-color|anseki|0.2.3|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.5|
|php-debug|felixfbecker|1.10.0|
|format-indent|Kasik96|1.3.0|
|ftp-sync|lukasz-wronski|0.3.2|
|px-to-rem-with-scss|medzhidov|1.0.1|
|HTMLHint|mkaufman|0.3.3|
|Spell|seanmcbreen|0.9.1|
|Align|steve8708|0.2.0|
|jsx|TwentyChung|0.0.1|
|vscode-react-native|vsmobile|0.2.2|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please provide some information about the problem
