### ISSUE TITLE
Ports for API calls are not being forwarded correctly when using VSCode in Codespaces

### ISSUE THREAD

**Issue by ccastrotrejo** [microsoft/vscode#205228]
ADD ISSUE DESCRIPTION HERE

Version: 1.86.0-insider
Commit: 81725794264e4c0fddbc1b3b728013744ae90840
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0
Embedder: codespaces

### General issue idea:
For Logic Apps (Standard) vscode extension we run a local `func host start` process which starts the local server in port 7071. (the port doesn't automatically starts, there are a series of steps you must do to make the server run), The port is automatically forwarded, which is good. However if we make API calls to the `localhost:7071` the api calls don't go through it. It seems that isn't active. I tried making the calls manually by changing the `localhost:7071` to the `forwarded address` and then it works. Is there a way the API calls can automatically go through the forwarded address?

All this works fine in a local environment. We are trying to make it work in a codespace environment.

### Screenshots
<img width="1500" alt="Screenshot 2024-02-14 at 9 31 35 AM" src="https://github.com/microsoft/vscode/assets/102700317/cba40965-e3af-4144-b4a2-602eeff6639c">
<img width="1500" alt="Screenshot 2024-02-14 at 9 35 41 AM" src="https://github.com/microsoft/vscode/assets/102700317/e50ddd14-409a-44e1-945c-e107d3824721">

Steps to Reproduce:

1. You can take a look on how to do this in here: https://learn.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#run-test-and-debug-locally
2. This is a really specific logic apps scenario, I am more than happy to help with this issue.

**Comment by alexr00** [comment]
Are you using Codespaces in desktop VS Code for from a browser?

**Comment by alexr00** [comment]
It looks like you're doing this from a browser, which means that forwarded ports are accessible at an internet URL that's provided by the Codespace. There's no way to make them available at `localhost` instead, as we have nothing running on your local machine where we can start a server and listen on localhost for you.

This should work fine if you use desktop VS Code though. In that case, since we have a desktop application, we do start a server and listen on `localhost` for forwarded ports.

**Comment by ccastrotrejo** [comment]
@alexr00 Yes, I am using Codespaces from a browser. 
Yes, this whole thing works fine in VS Code desktop application. The local server in my local machine works fine and the API calls to it also (since everything is local), however If I want to use Codespaces the server also works fine but the API calls that are made to the `https//localhost:7071` aren't picked up automatically since it needs to go through the forwarded address instead of the localhost and the port. 
My question here is: Is there any way the codespaces or vscode can automatically pick the API calls that are made through the localhost and the port and forward them to the forwareded address?

**Comment by alexr00** [comment]
@ccastrotrejo what/who is making the API calls? If they're coming from a VS Code extension then this is possible.

**Comment by ccastrotrejo** [comment]
Hi @alexr00 , yes those API calls are coming from the VS Code extension.

**Comment by ccastrotrejo** [comment]
@alexr00 awesome, thank you so much. I will give it a try!

**Comment by ccastrotrejo** [comment]
@alexr00  it actually worked in resolving the external Uri. But I am getting 302. Do you know why this might be happening? If I paste the url in the browser I am able to get the data
<img width="1388" alt="image" src="https://github.com/microsoft/vscode/assets/102700317/85c0a504-7f7f-40d8-ae8f-8d8eeb0d3912">

**Comment by alexr00** [comment]
@ccastrotrejo I'm not sure, maybe it's auth related. You can check if it's auth related by changing the port to "public" from the Ports view before your API call. If it's works when the port is public but not when it's private then it's probably a problem with the context you're making the API call from not having the proper auth from GitHub. Are you making this API call from a webview in a VS Code extension? If so, then this is common problem. The only solution I can offer is to make the API call from the extension, not the webview, which I know is not ideal.

**Comment by ccastrotrejo** [comment]
@alexr00 Yes, we are making the api calls from a webview.

**Comment by ccastrotrejo** [comment]
@alexr00 by any chance do you know if there will be a fix on this?

**Comment by alexr00** [comment]
@ccastrotrejo based on the above discussion, everything is working as expected. It isn't a good idea for VS Code to give webviews the same context as VS Code from a security perspective. The fix is for your extension to make the API calls that use uri that you get from `asExternalUri` in the extension, not in the webview.

**Comment by ccastrotrejo** [comment]
@alexr00 Understood, that makes sense. Thanks!
