### ISSUE TITLE
Terminal not working and codespace not loading

### ISSUE THREAD

**Issue by KanishkaThakur1** [microsoft/vscode#205287]
ADD ISSUE DESCRIPTION HERE

Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
