### ISSUE TITLE
Debug with externalTerminal gives error (Windows)

### ISSUE THREAD

**Issue by raydrak64** [microsoft/vscode#205247]
Type: <b>Bug</b>

Since the upgrade to 1.86.0 if you attempt to run a debug for Python using the externalTerminal JSON config, you get the error:

error 2147942402 (0x80070002) when launching **PATH\FILE**

Upon my research, it appears it is not handling spaces in the file path correctly any longer.

Thank you.

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (23.17GB free)|
|Process Argv|--crash-reporter-id a680fa13-9be4-4295-80bf-b0d240d645c6|
|Screen Reader|no|
|VM|80%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
speech|bie|0.1.1
python-environment-manager|don|1.2.4
evil-red-theme|fra|1.2.0
vsc-python-indent|Kev|1.18.0
black-formatter|ms-|2024.0.0
debugpy|ms-|2024.0.0
flake8|ms-|2023.10.0
pylint|ms-|2023.11.13481007
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.1.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
remote-wsl|ms-|0.86.0
glassit|s-n|0.2.6
ayu|tea|1.0.5
custom-xml-formatter|tho|1.3.2
vscode-counter|uct|3.4.0
visiontech-themespack|Vin|1.0.0

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30962250
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
edj9j583:30958191
a89i1917:30961429
3ef8e399:30964150
bg6jg535:30958357
ccp1r3:30958155

```

</details>

**Comment by roblourens** [comment]
I believe this is https://github.com/microsoft/vscode/issues/204039, which should be fixed in the VS Code Insiders build. Please let me know if that's not the case.
