### ISSUE TITLE
debugger freeze everytime on specific breakpoints in typescript applications

### ISSUE THREAD

**Issue by avan2s** [microsoft/vscode#205226]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.1
- OS Version: Ubuntu 22.04

In my company projects the debugger stucks sometimes. Now this issue occured on my open source project and hopefully the vscode dev team is able to help, why the debugger is freezing since several months from time to time.

Steps to Reproduce:

1. Make sure docker and node lts is installed on your machine. On my side it is `v20.10.0`
2. checkout the specific tag from the following repository and install the dependencies with: `git clone git@github.com:avan2s/prisma-transactions.git && cd prisma-transactions && git checkout v0.1-vscode-hangup && npm i` 
3. open vscode from terminal with `code --disable-extensions .` (it will also crash with plugins, but just to be sure, we have the same state)
4. toggle auto attach Smart (F1 => Debug: Auto Attach => smart) and then open the vscode terminal
5. set a breakpoint in the following line: https://github.com/avan2s/prisma-transactions/blob/0d8b0460015b303ab9091c1c983c62d819b46bbf/src/services/prisma-tx-propagation-extension.ts#L61
6. in the vscode terminal execute `npm run test:watch` 
7. when the watcher is started press `a` for running all jest tests
8. vscode stops at the breakpoint. Sometimes it freezes directly, but you can trigger the freeze by clicking in the watch variables on the Closure
![image](https://github.com/microsoft/vscode/assets/7395531/7eb51064-89cc-4c20-8132-6b6e870c2614)
9. vs code debugger freezes. You are unable to go to the next step from now on. Only way to escape is closing the vscode terminal

I think this issue is related to several debugger freezes i experienced in the last 4 month. Maybe this helps you to reproduce the issue.

Thanks for your help!

**Comment by avan2s** [comment]
i can also confirm this issue exist for my macOs system: Apple M1 Sonoma 14.2.1 Darwin arm64 23.2.0
vscode version: 1.86.1

**Comment by conceto-NKO** [comment]
I've successfully replicated the issue on my system as well. Below are the pertinent details of my MacBook Pro setup.

**macOS Version**: Ventura 13.5 (22G74)
**Model Identifier**: MacBookPro15,1
**Processor**: 6-Core Intel Core i7, 2.6 GHz
**System Architecture**: amd64
**Kernel Version:** Darwin 22.6.0
**VSCode Version**: 1.85.1

**Comment by ripkeanny** [comment]
Can be replicated using: 

**OS Version:** Windows 10 Pro Version 22H2
**WSL Version: ** Ubuntu-20.04
**VSCode Version:** 1.86.1

**Comment by avan2s** [comment]
I added a launch.json file and configured the trace parameter and started the test with my npm package.json script `npm run test:watch2`, which allows me to attach with the `launch.json`:
`"test:watch2": "node --inspect-brk ./node_modules/.bin/jest -i --verbose --config jest-unit.json --watch"`

It started the debugger in watch mode, attached with the `launch.json`, and executed all tests with a. The breakpoint was set and the error was reproduced:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Jest Tests",
            "type": "node",
            "request": "attach",
            "trace": true,
            "port": 9229,
            "restart": true,
            "skipFiles": ["<node_internals>/**"]
        }
    ]
}
```
The trace log file:
[vscode-debugadapter-70819bfc.json](https://github.com/microsoft/vscode/files/14303223/vscode-debugadapter-70819bfc.json)

**Comment by connor4312** [comment]
Thanks for the logs and the repro.

This is because the debugger attempts to use the `nodejs.util.inspect.custom` symbol to represent variables in the Variables view. It looks like this is defined on the `_prismaClient`, but calling it blocks indefinitely. You can see this by adding this line inside of `createProxyHandlerForFunction`:

```ts
(_prismaClient as any)[Symbol.for('nodejs.util.inspect.custom')]();
```

I didn't debug further than this.

Let me know if you run into other issues.

**Comment by andreasvh-conceto** [comment]
Hi @connor4312,
thx for your investigation and conclusion. This also explained why it only hangs up in debug mode.

```
(_prismaClient as any)[Symbol.for('nodejs.util.inspect.custom')]();
```

What would be your recommendation to fix such kind of an error? Just deleting the symbol from the _prismaclient? I never assigned this symbol there manually. 

Would be grateful for any explanation, what options I can consider.

thx a lot 🙏

**Comment by connor4312** [comment]
It is defined in the prisma client,

https://github.com/prisma/prisma/blob/794b61e7474cdd7b83fd2fe0144e1dc3230a220c/packages/client/src/runtime/core/compositeProxy/createCompositeProxy.ts#L119-L126

So it is a bug for them to fix.

**Comment by avan2s** [comment]
Thanks a lot, i will raise an issue.
Thx and best regards :)
