### ISSUE TITLE
VSCode tries to use wrong shell path with no way to change it

### ISSUE THREAD

**Issue by thennothinghappened** [microsoft/vscode#205321]
Does this issue occur when all extensions are disabled?: Yes

Hello! Now - gonna preface this that I'm 99% sure this is something I've done wrong, but I honestly don't even know where to start with this one. At some point or other I set my shell explicitly to a `fish` version in homebrew (incorrectly), but despite changing that back anywhere I can possibly think of and even doing a full `grep` of my home directory looking for any mention of this string, I still can't find what's causing it.

The main deal is that VSCode is refusing to use any other shell than this mysterious fish instance that no longer exists and doesn't give me any way of changing it - there's multiple preferences that supposedly do this even mentioned in the docs, but they show up with a squiggly line on mine and don't do anything:

<img width="975" alt="image" src="https://github.com/microsoft/vscode/assets/35243139/4e71b8df-eccc-46d4-9b71-4fcb77cc82ca">
... and the quick option "Terminal: Select Default Shell", which is just entirely missing:
<img width="614" alt="image" src="https://github.com/microsoft/vscode/assets/35243139/f6a909b4-2c1e-4a8d-b04e-42a0bece18c9">

I'm not really sure where to go from here. It's probably something pretty silly I've done, but I'm also totally lost on where those options are at that are even mentioned in the docs.

- VS Code Version: Version: 1.86.2
- OS Version: Darwin arm64 22.6.0

Steps to Reproduce:

1. Launch Visual Studio Code
2. Presented with error:
<img width="465" alt="image" src="https://github.com/microsoft/vscode/assets/35243139/5fa5ff39-bf86-417f-9a09-1f717497624b">

3. Launching a terminal also fails:
<img width="462" alt="image" src="https://github.com/microsoft/vscode/assets/35243139/319056c1-fef8-4320-976d-9eb21b02b4d4">

I also tried completely wiping my `~/.vscode`, and the `Code` folder in Application Support.

**Comment by karrtikr** [comment]
@aiday-mar This doesn't seem related to the Python extension, hence re-assigning.

**Comment by Tyriar** [comment]
We pull in the default shell via `$SHELL` which is controlled via `chsh`. You need to fix this up outside of VS Code or alternatively set a default profile explicitly (creating it if necessary, see https://code.visualstudio.com/docs/terminal/profiles)

**Comment by thennothinghappened** [comment]
> We pull in the default shell via `$SHELL` which is controlled via `chsh`. You need to fix this up outside of VS Code or alternatively set a default profile explicitly (creating it if necessary, see https://code.visualstudio.com/docs/terminal/profiles)

The issue is that `$SHELL` already points to the correct shell, and I already have it set correctly via `chsh`:
<img width="440" alt="image" src="https://github.com/microsoft/vscode/assets/35243139/819d2bba-aeee-429a-92e0-e311a309fd29">
(`chsh` output without any arguments)

And `/opt/homebrew/bin/fish` points to the correct version:
<img width="713" alt="image" src="https://github.com/microsoft/vscode/assets/35243139/8395a575-7059-4a1e-8030-1f61ca74bac1">

I have no idea where `3.6.1` is coming from, nor the hardcoded string pointing to that version.

I have now been able to now manually add `fish` as a profile, but the constant errors will not stop pointing to this erroneous path, which isn't referenced _anywhere_ I can find. I understand that this is _very_ likely user error, but I have nothing left to go off, nor does vscode offer any way to at least suppress these errors - though that would not be my preferred solution.

**Comment by Tyriar** [comment]
Unable to resolve shell environment is because we launch `$SHELL` when VS Code starts up in order to source the user's development/terminal environment. Unfortunately this has to be an issue on your end as we don't cache this and we can't really debug it effectively for you. Here is the code that determines where that shell is pulled from if that's helpful:

https://github.com/microsoft/vscode/blob/5e9e54773a6924b88d64dd61c64142bf355a74fb/src/vs/base/node/shell.ts#L29-L61

It's a good thing that you can't suppress the error as some things won't work properly until you fix this problem.
