### ISSUE TITLE
quickstart has problem with VS Code

### ISSUE THREAD

**Issue by yueguanyu** [Microsoft/vscode#20534]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions:

|Extension|Author|Version|
|---|---|---|
|angular2|johnpapa|2.0.0|
|TypeScriptImport|kevinmcgowan|1.17.0|
|vim|vscodevim|0.5.3|

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
What is quickstart?

Please provide more information.
