### ISSUE TITLE
SCM input box no longer shows validation message for messages that exceed `git.inputValidationSubjectLength`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#205392]
1. Have the default `git.inputValidationSubjectLength` value at 50 chars
2. Type in a SCM message that is longer than 50 chars
3. :bug: no warning is shown at the input box

**Comment by lszomoru** [comment]
@joyceerhl, could you please make sure that you have `git.inputValidation` enabled? Thanks!

**Comment by joyceerhl** [comment]
Ah thanks, I don't remember having enabled that before but it did the trick

**Comment by lszomoru** [comment]
We have recently changed the default value of the setting.
