### ISSUE TITLE
Git repositories view crops too early

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#205361]
See here:

<img width="367" alt="image" src="https://github.com/microsoft/vscode/assets/900690/a41c9ec6-1344-4d70-a8e8-b4925a27151a">

When I make the sidebar smaller in a multi-repository view, I see that the "..." appears even when not needed.

![Recording 2024-02-16 at 13 03 54](https://github.com/microsoft/vscode/assets/900690/275b9187-68a7-41f1-a27b-23a027ead015)

**Comment by stagefright5** [comment]
https://github.com/microsoft/vscode/issues/205330#issuecomment-1948279239

**Comment by lszomoru** [comment]
🤔, the checkout and sync actions seems to be missing. Investigating...

**Comment by lszomoru** [comment]
Adding @benibenj as this might be related to the custom hover work...
