### ISSUE TITLE
Block multiple members to make changes to the same file at the time to avoid merge conflict at max.

### ISSUE THREAD

**Issue by mrinmoy32** [microsoft/vscode#205335]
We need a way/feature (like in MS excel) to show in IDE itself if multiple members has got the same file open at the same time and at which line they are working. Also block members to make changes to the same file at the same time which would definitely reduce the chances of merge conflict a lot. The IDE should be able to do this with help of the online code repository (gitlab, github etc). 

This will be a very very useful feature. Kindly do not ignore this and this would save a huge amount of time of developers. Also VS Code code be more user friendly and preferred by devs.

**Comment by mrinmoy32** [comment]
Hello @lszomoru, could you please have a look into this feature request. : )

**Comment by mrinmoy32** [comment]
@VSCodeTriageBot it seems that the issue is not being look into. Is there a possibility to get it reviewed at the earliest possible.

**Comment by lszomoru** [comment]
Thank you very much for filing this issue. What you are describing aligns with the principles of a centralised source control system where files can be locked. This feature request is out of scope for VS Code but it is something that could be explored as a potential VS Code extension.
