### ISSUE TITLE
[BUG] Local tasks.json is not used for build task

### ISSUE THREAD

**Issue by mrj001** [microsoft/vscode#205372]
Describe the Issue

My ~/.config/Code/User/tasks.json file is used for the build task instead of a local .vscode/tasks.json file.

This may be the same underlying bug as Issue @https://github.com/microsoft/vscode-dotnettools/issues/198.

Steps To Reproduce

I created a new console app with:
`$ dotnet new console --framework net7.0 --use-program-main`
Then, I opened this folder with visual studio code. I generated the assets for build and debug.

I confirmed that build and debug both worked in visual studio code.

Then, I "sabotaged" my ~/.config/Code/User/tasks.json file by changing "dotnet" to "gotnet". It now looks as follows:

```
{
   // See https://go.microsoft.com/fwlink/?LinkId=733558
   // for the documentation about the tasks.json format
   "version": "2.0.0",
   "tasks": [
      {
         "label": "build",
         "type": "shell",
         "command": "gotnet",
         "args": [
            "build",
            "/property:GenerateFullPaths=true",
            "/consoleloggerparameters:NoSummary"
         ],
         "group": {
            "kind": "build",
            "isDefault": true
         },
         "presentation": {
            "reveal": "silent"
         },
         "problemMatcher": "$msCompile"
      }
   ]
}
```
Upon going back to Visual Studio Code, and executing either build or debug, I get this error in the terminal:

> Executing task: gotnet build /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary 
> 
> /usr/bin/bash: line 1: gotnet: command not found
> 
>  *  The terminal process "/usr/bin/bash '-c', 'gotnet build /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary'" failed to launch (exit code: 127). 
>  * 

This indicates that the `~/config/Code/User/tasks.json` file is being used for the build task, and not the local tasks.json file.

Expected Behavior

I expected the local .vscode/tasks.json file to take precedence and be used instead.

Environment Information

C# Dev Kit version: 1.3.10

Hardware: Orange Pi 5, with 16GB RAM.

From VSCode Help->About

> Version: 1.86.1
> Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
> Date: 2024-02-07T09:07:19.793Z
> Electron: 27.2.3
> ElectronBuildId: 26495564
> Chromium: 118.0.5993.159
> Node.js: 18.17.1
> V8: 11.8.172.18-electron.0
> OS: Linux arm64 5.10.160-legacy-rk35xx

```
$ cat /etc/issue
Armbian 23.11.1 bookworm \l 

 $ dotnet --info
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.69afb982

Runtime Environment:
 OS Name:     debian
 OS Version:  12
 OS Platform: Linux
 RID:         linux-arm64
 Base Path:   /home/mj/dotnet/sdk/8.0.101/

.NET workloads installed:
 Workload version: 8.0.100-manifests.69afb982
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: arm64
  Commit:       bf5e279d92

.NET SDKs installed:
  6.0.418 [/home/mj/dotnet/sdk]
  7.0.401 [/home/mj/dotnet/sdk]
  7.0.405 [/home/mj/dotnet/sdk]
  8.0.101 [/home/mj/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.26 [/home/mj/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [/home/mj/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.15 [/home/mj/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [/home/mj/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.26 [/home/mj/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [/home/mj/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [/home/mj/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [/home/mj/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/mj/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

See also my original submission [here](https://github.com/microsoft/vscode-dotnettools/issues/918).

@timheuer included a video.

**Comment by meganrogge** [comment]
User tasks will take precedence over your local tasks.json file. This is working as designed.
