### ISSUE TITLE
File Explorer dose not sync with local files

### ISSUE THREAD

**Issue by Hkmu** [Microsoft/vscode#20532]
- VSCode Version: 1.9.1
- OS Version: macOS 10.12

Steps to Reproduce:

I moved some folders to another folder in Finder but content in the File Explorer didn't change.

**Comment by bpasero** [comment]
@Hkmu does this reproduce all the time you try? Can you share your settings?

**Comment by Hkmu** [comment]
@bpasero I tried again and it didn't reproduce. Thank you!

**Comment by bpasero** [comment]
OK thanks, please report back when it happens again.
