### ISSUE TITLE
Test: accessibility signals

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#205384]
Refs #202018

- [x] Windows @joyceerhl 
- [x] macOS @hbons 
- [x] anyOS @roblourens 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23205384%0A%0A&assignees=meganrogge)

---

We have moved over from the following:

```
audioCues.clear: "on | auto | off"
accessibility.alert.clear: "true | false"
```

to:

```
"accessibility.signals.clear": {
       "sound": "auto | on | off",
       "announcement" (optional): "auto | off"
}
```

For the `format` and `save` signals, the options are `never | userGesture | always`. 

Try the following using both `Screen Reader Optimized Mode` and not:
- Add deprecated settings for `audioCues.*` and `accessibility.alert.*` in your `settings.json`. Reload the window and verify that the appropriate `accessibility.signals.*` settings have been added. Note that this iteration, we are not removing the deprecated settings. We will next iteration. 
- Delete all `audioCues.*` and `accessibility.alert.*` from your settings file, save, reload the window and verify that sounds/announcements still occur. 
- Verify that you see deprecation messages for any `audioCues.*` settings
- Run the commands `Help: List Signal Sounds` and `Help: List Signal Announcements`. to enable/ disable and verify those get applied.
- In chat and the editor, run `Open Accessibility Help` and verify that the signal settings are mentioned.

Note that an `announcement` will only be read when you have a screen reader enabled. A sound should play when either it's set to `auto` | `on` in screen reader mode or `on` when not in screen reader mode.

**Comment by hbons** [comment]
Verified everything works as described on macOS using `Screen Reader Optimized Mode` and without. Sounds play in Screen Reader mode when `sounds` is on `auto` or always when `on`.

Settings added after reload:
<img width="325" alt="image" src="https://github.com/microsoft/vscode/assets/103326/2cce8bac-03fe-40f2-a311-4910b1f2fd39">

Deprecation message:
<img width="588" alt="image" src="https://github.com/microsoft/vscode/assets/103326/00045ebb-5476-4a73-a8eb-028de4cc0d17">

a11y Help on editor:
<img width="625" alt="image" src="https://github.com/microsoft/vscode/assets/103326/0e5a3806-5fb0-4135-bc43-95495152a1d3">

a11y Help on chat:
<img width="629" alt="image" src="https://github.com/microsoft/vscode/assets/103326/20def4a5-034d-48bc-99aa-b4b0728a0126">

**Comment by roblourens** [comment]
> Note that this iteration, we are not removing the deprecated settings

Works great, but why not clean up the previous settings after migrating?

**Comment by meganrogge** [comment]
@roblourens planning to do that next iteration. Just wanted to be sure it worked / went through testing before removing them.
