### ISSUE TITLE
Add Replace in Selected Text

### ISSUE THREAD

**Issue by Behzadkhosravifar** [Microsoft/vscode#20539]
Hi,
I want to **Replace** (**Ctrl** + **H**) a sentences in the `Selected Text` not at all of document, like visual studio IDE.

Thanks a lot
Behzad

**Comment by joaomoreno** [comment]
@isidorn Didn't we have this?

**Comment by isidorn** [comment]
We still have it, open find widget -> check off selection toggle

![findinselection](https://cloud.githubusercontent.com/assets/1926584/22932766/6485c61e-f2c9-11e6-90bb-ccc8ab4ea019.gif)

**Comment by isidorn** [comment]
Or just have some text selected before you open the find widget

**Comment by Behzadkhosravifar** [comment]
Thanks a lot
