### ISSUE TITLE
Colors for "problems" block

### ISSUE THREAD

**Issue by AleksStek** [Microsoft/vscode#20538]
Hello,
There are two symbols (:x: and :warning:) in the left-bottom part of VS Code.
![errors](https://cloud.githubusercontent.com/assets/16941653/22879324/1493f2fc-f210-11e6-85f0-cc671ce07dba.png)
Both symbols have white color when no errors or warnings and also when there are some issues. It's difficult to notice changing in the numbers in right time. Personally I see problems after something already happened and doesn't work.
Maybe will be better if the error symbol will have red background color, the warning - yellow (of course only when the number of errors is different from zero)

**Comment by innerlee** [comment]
I think this bar should not attract people's attention. I like the current color's being passive.

**Comment by AleksStek** [comment]
Yes, but this two symbol are exception. They need to indicate about typo errors and so on. It doesn't make sense if the error messages don't attract attention

**Comment by dbaeumer** [comment]
@stevencl any opinion.

**Comment by stevencl** [comment]
Thanks for the feedback. Our design goals for the status bar are for it to provide ambient information, not for it to grab attention. Over time, I've seen users get accustomed to looking at this area on the status bar to see if there are any new issues. So I am going to close this for now.

**Comment by Pyrolistical** [comment]
I disagree. If you are going to make the status bar bright, then it should change when there is an issue.

If you believe it should be passive ambient information, then don't make it so bright!
