### ISSUE TITLE
Incorrect syntax highlighting for Go

### ISSUE THREAD

**Issue by findleyr** [microsoft/vscode#205306]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.2
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Install VS Code 1.86.2
2. Create a file main.go, with the following contents:
```go
package main

func main() {
  var s []byte = []byte("]")
  println(s)
}
```
3. Observe that `println` is highlighted as a string -- the `"]"` highlighting is not terminated at the closing `"`. Here's a related screenshot from one of our users. (Please ignore that the Go extension is installed in this screenshot, the issue reproduces without the Go extension.)
![image](https://github.com/microsoft/vscode/assets/57144380/6aa4d230-6142-45a2-a0d1-389db4109318)

I'm one of the maintainers of the Go extension. This was reported to us in https://github.com/golang/vscode-go/issues/3158, but appears to be a recent regression in VS Code 1.86, not the Go extension. Per the 1.86 release notes, this was likely broken by the switch to https://github.com/worlpaker/go-syntax.

**Comment by RedCMD** [comment]
dup of https://github.com/microsoft/vscode/issues/205005

https://marketplace.visualstudio.com/items?itemName=golang.Go does not supply its own `go` grammar
but instead relies on VSCode's builtin `go` grammar
which changed in 1.86

**Comment by findleyr** [comment]
Thanks. I'll close as a dupe.
