### ISSUE TITLE
"cmd+q" cant't quit the code app

### ISSUE THREAD

**Issue by heeefei** [Microsoft/vscode#20543]
## Steps to Reproduce:

1.open a file, make it focused
2.press "cmd + q"

## what I expected:
quit the app

## what happened:
![image](https://cloud.githubusercontent.com/assets/3992113/22882865/2df8e6c2-f228-11e6-9521-42c807c8b725.png)

**Comment by joaomoreno** [comment]
You likely have configured a keybinding chord or installed an extension which sets a keybinding chord which starts with <kbd>Cmd Q</kbd>.
