### ISSUE TITLE
[OSX] VSCode gets stuck with "The window has crashed"

### ISSUE THREAD

**Issue by lboshuizen** [Microsoft/vscode#20542]
After upgrade to 1.9.1 VSC fails to start and keeps prompting "The window has crashed"

From #10352 I tried:

```
/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --verbose
[main 12:45:45] Sending env to running instance...
[main 12:45:45] Sent env to running instance. Terminating...

```
Removing and then a fresh install doesn't resolve it either.

- VSCode Version: 1.9.1
- OS Version: 10.12.2

Update:
Clean build from [master] and running ```scripts/code.sh``` works.

**Comment by lboshuizen** [comment]
**Solved.**

Solution:

```sudo shutdown -r now```

**Comment by bsed** [comment]
please del 
![default](https://user-images.githubusercontent.com/10845087/31932231-58da7fbe-b8d8-11e7-98df-3be32a5fe254.png)
