### ISSUE TITLE
Opening Extension help closes the existing file

### ISSUE THREAD

**Issue by luckvicky** [Microsoft/vscode#20540]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-yaml-validation|djabraham|0.0.1|
|qub-xml|qub|1.0.3|
|json-organizer|rintoj|0.0.3|
|todotasks|sandy081|0.4.0|

---

Steps to Reproduce:

1. Set VSCode as a default program to open text files
2. Double click on a text file to open it in VS code
3. Click on Extension Icon in the side 
4. Click on any of the installed extension.
5. Extension help closes the opened file, and then opens the extension help file

**Comment by joaomoreno** [comment]
This is as expected. If you close the extension help file, your file will appear.

**Comment by luckvicky** [comment]
Even on closing the help file the file doesn't reopens

**Comment by joaomoreno** [comment]
@bpasero Is the file maybe not pinned?

**Comment by luckvicky** [comment]
It's not a pinned file.

The scenario was
I double clicked and opened the file 
Since vs code was the default app it opened
Then I wanted to format the XML present

For which I opened the help file.
But on closing the help file the original file gets closed

**Comment by bpasero** [comment]
@luckvicky I cannot reproduce, what are you doing differently?

![panel-red](https://cloud.githubusercontent.com/assets/900690/23100564/ce788296-f684-11e6-8ba2-4218fea18334.gif)
