### ISSUE TITLE
Feature Request: Add show/hide button for viewing/un-viewing the whole hashmap in one click for the debugger

### ISSUE THREAD

**Issue by IamManchanda** [microsoft/vscode#205437]
I would really love if we have the ability to debug HashMap without pressing eye icon again and again.

<img width="374" alt="Screenshot 2024-02-17 at 7 49 09 PM" src="https://github.com/microsoft/vscode/assets/4970624/14ba971f-5ef7-406b-b154-7c2004106495">

----

In Intelij Idea for example, I don't have this issue while debugging. 

<img width="358" alt="Screenshot 2024-02-17 at 7 51 16 PM" src="https://github.com/microsoft/vscode/assets/4970624/68f94894-45dd-4061-9475-a739ed945f58">

-----

Please fix by adding this feature 🙏

**Comment by roblourens** [comment]
Please file this on the repo for the debug extension that you're using, it's up to the debugger.

**Comment by IamManchanda** [comment]
@roblourens - Sorry for checking late, Done ✅  here https://github.com/microsoft/vscode-java-debug/issues/1446
