### ISSUE TITLE
Test: extension test coverage

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#205479]
Refs https://github.com/microsoft/vscode/issues/203563

- [x] anyOS @aiday-mar
- [x] anyOS @karthiknadig

Complexity: 4
Roles: Developer

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23205479%0A%0A&assignees=connor4312)

---

This iteration, we have added coverage support to VS Code [test CLI](https://code.visualstudio.com/api/working-with-extensions/testing-extension#quick-setup-the-test-cli). You will either want to have an extension already using the CLI, or update one to use the CLI as a prerequisite for verifying this. See the instructions in the link on how to do this.

Once do you, verification is actually pretty simple:

- Start off at an old version of the VS Code test CLI, 0.0.5 or below. Have the extension [test runner](https://marketplace.visualstudio.com/items?itemName=ms-vscode.extension-test-runner) installed in VS Code.
- Run one or more tests with coverage. Verify you get a notification telling you that you need to update your CLI to get coverage support.
- Update to the latest version of the `@vscode/test-cli` in your project.
- Run again. Verify coverage gets reported and appears correctly in the editor.
- Manually run `vscode-test` from the command line using `--coverage`, and see that it works there. Look at the couple of coverage related options in `vscode-test --help` and verify they make sense and work as expected.

**Comment by aiday-mar** [comment]
I got the notification as expected, for test cli version 0.0.4 or lower. Version 0.0.5 shows the test coverage.

**Comment by karthiknadig** [comment]
Same issue as reported by @aiday-mar :
![image](https://github.com/microsoft/vscode/assets/3840081/c9ab9460-7604-426d-9397-8829ff97498e)
