### ISSUE TITLE
context key "atEndOfWord" is always false

### ISSUE THREAD

**Issue by md-base-t** [microsoft/vscode#205415]
Type: <b>Bug</b>

When I open a code editor in VSCode and place the text cursor at the end of any word, the context key `atEndOfWord` remains **false**, it stays false at every cursor position. I use this context key in the "when" keys of the "keybindings.json" and it has always worked without any problems. 

I think that the state of `atEndOfWord` is always false since version 1.85 or 1.85.1.

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows 10 x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.01GB free)|
|Process Argv|--log info|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
json-viewer|Dut|0.1.0
vscode-commands|fab|1.4.3
thefoldingstuff|geo|0.2.1
vscode-menu-builder|kyl|1.0.2
vscode-plugin-keyboard-shortcut-eval-custom-javascript-codes|Lia|1.0.13
vscode-language-pack-de|MS-|1.85.2024021409
csharp|ms-|2.15.30
vscode-dotnet-runtime|ms-|2.0.1
debugpy|ms-|2024.0.0
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.1.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
powershell|ms-|2024.0.0
multi-command|ryu|1.6.0
vbsvscode|Ser|1.2.1
memento-inputs|spa|1.0.0
vscode-autohotkey2-lsp|thq|2.3.2
vscode-inline-values-powershell|Tyl|0.0.7
vscode-autohotkey-debug|zer|1.11.0

</details>

**Comment by jrieken** [comment]
> It is a possible enhancement request to make atEndOfWord context key always available, independent of editor.tabCompletion setting?

This a q quite expensive context key and we have no plans to make it generally available. It comes from a time that predates ghost text and it is more likely that we will eventually onboard tab completions to that and get rid of this context key all together.
