### ISSUE TITLE
Suggest Widget Details: Maintain Constant Size

### ISSUE THREAD

**Issue by Number-3434** [microsoft/vscode#205468]
Please add an option to maintain a **constant size** for details in the suggest widget.
The details are currently jumping to fit the size, which makes it very hard to read.

Here is an example of the issue:

![GIF demonstrating Suggest Widget Details Jumping when navigating using keyboard](https://github.com/microsoft/vscode/assets/115815794/4441e128-11da-4f9a-8cca-8b45cf1741e2)

Ideally, there should be a setting to make the details maintain consistent size.

In this case, the details will **expand** to fit the space, instead of constantly jumping.

**Comment by jrieken** [comment]
What version of VS Code are you using? The alignment at the bottom should have become the exception with later versions and with that I don't believe the varying sizes are such a big issue anymore.

**Comment by Number-3434** [comment]
@jrieken I've just updated to the latest version, and it's fixed now!

However, it still doesn't maintain a constant size.

It feels weird, since to resize the details widget, you need to find a suggestion that has large enough details to fit the size.

**Comment by Number-3434** [comment]
Sorry, closing this as it is already in VSCode.
