### ISSUE TITLE
copy output in python REPL won't work

### ISSUE THREAD

**Issue by nyck33** [microsoft/vscode#205462]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: any
- OS Version: Ubuntu 23.10

Steps to Reproduce:

1. Start writing a .py file with `#%%` for the Interactive feature and execute to get some output in the right pane
2. Please see https://forum.cursor.sh/t/copy-output-from-an-ipython-right-pane-does-not-work/2952?u=nyck3333

**Comment by amunger** [comment]
repro steps: 
1. execute something with output in the Interactive window
2. from the output menu select `copy cell output`
:bug: output is not copied

**Comment by rben01** [comment]
I think this happens when the interactive window doesn't have focus. When the interactive window doesn't have focus and you click the 3-dots menu > “copy cell output”, nothing happens. If you move focus to the interactive window and do the same, then “copy cell output” works as expected.
