### ISSUE TITLE
`code --wait` no longer exits when the file is closed in VSCode

### ISSUE THREAD

**Issue by camillol** [microsoft/vscode#205416]
Type: <b>Bug</b>

- Run `code --wait foo.txt` in your terminal (not inside VSCode).
- Type something, then close the file.
- Expected result: the `code` command exits.
- Actual result: the `code` command does not exit until the VSCode app is quit.

I believe this started happening with the January 2024 release.

I like using VSCode to manipulate rebase todo lists for git (e.g. using `GIT_EDITOR="code -w" git rebase -i master --autosquash`), so I run into this daily and it's quite annoying.

I also tried starting VSCode with `--disable-extensions` and the bug still occurs, so it doesn't seem to be an extension issue.

VS Code version: Code 1.86.2 (Universal) (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:13.651Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|11, 7, 6|
|Memory (System)|32.00GB (1.06GB free)|
|Process Argv|--crash-reporter-id 774d68bb-c124-4b34-ac13-a08d9a3197de|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|14.8.2
copilot|Git|1.162.0
copilot-chat|Git|0.12.2
vscode-pull-request-github|Git|0.80.1
go|gol|0.41.0
marp-vscode|mar|2.8.0
python-path|mge|0.0.14
black-formatter|ms-|2024.0.1
debugpy|ms-|2024.0.0
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.1.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
makefile-tools|ms-|0.8.22
rust-analyzer|rus|0.3.1839
sourcegraph|sou|2.2.16

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30962249
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
b5d27386:30958190
3ef8e399:30964150

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
