### ISSUE TITLE
Please support vscode reference plaintext view on some file extensions

### ISSUE THREAD

**Issue by novemberi** [microsoft/vscode#205423]
Hello. I'm now develop vscode extension for unity.
Now this extension is support meta references code lens.
![image](https://github.com/microsoft/vscode/assets/37071240/93e63bee-a612-4689-a938-befb053b9f50)
Unity .cs file has .meta and this included guid data is synced with prefab, unity, asset.

![image](https://github.com/microsoft/vscode/assets/37071240/e22ccd6c-1f42-4cfd-a43d-5b44a1c5752e)
But reference text view is looks empty view.
I want to show this just plaintext.

[repo](https://github.com/novemberi/clover)

**Comment by novemberi** [comment]
+ I tried to test on my MacOS, the view is looks good.
Only windows has problem.
<img width="1003" alt="Screen Shot 2024-02-17 at 6 07 19 PM" src="https://github.com/microsoft/vscode/assets/37071240/d4f05cd3-4abb-4985-956f-793c11123406">

**Comment by RedCMD** [comment]
so the preview of the referenced file is not showing?

if you click on the file reference link, does it open/load?

**Comment by novemberi** [comment]
> so the preview of the referenced file is not showing?
> 
> if you click on the file reference link, does it open/load?

No, left text view is always empty space on Windows.

**Comment by novemberi** [comment]
I fixed this problem.
I used `vscode.Location` uri data parse by `vscode.Uri.parse`. Change this to `vscode.Uri.file` and solve this problem.
![image](https://github.com/microsoft/vscode/assets/37071240/d177ff34-871d-43eb-a634-2b87125a920a)
