### ISSUE TITLE
Unintuitive result scoring with Ctrl-P in recent history

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#20546]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-whitespacer|deerawan|1.0.0|
|contextualduplicate|lafe|0.2.0|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.6.2|
|duplicatetext|rivenvirus|0.0.3|
|trailing-spaces|shardulm94|0.2.11|
|vscode-fileutils|sleistner|2.3.3|
|shader|slevesque|0.2.2|
|cmake|twxs|0.0.15|

---

Steps to Reproduce:

1. See gif.

I feel like the shorter result (in this case list-view.js) is a better match than the longer one. I would prefer to have to (for example) add an "s" to specify that I want to open list-view-**spec**.js

![codebug_ctrl-p](https://cloud.githubusercontent.com/assets/1578924/22884489/76600b6c-f1f5-11e6-97da-effb4a30c6bf.gif)

**Comment by kumarharsh** [comment]
Related: https://github.com/Microsoft/vscode/issues/17796

**Comment by Srekel** [comment]
@kumarharsh Thanks for linking! The first post in that issue is about Intellisense. I'm not sure if they use the same kind of matching algorithm (I'd imagine that Intellisense is much more complicated :) ), but a few of the responses are definitely related to this issue. Might be worth either joining these two issues, or moving the File picker (Ctrl+P) related discussion here?

**Comment by bpasero** [comment]
@Srekel the "Recently Opened" list is purely sorted by last access whereas the "File Results" are sorted by our matching algorithm. I think what you are asking for is to apply the same scoring to the "Recently Opened" list.

**Comment by Srekel** [comment]
Ah, is that what it is. Yes, I'm pretty sure that would be preferable. :)

**Comment by bpasero** [comment]
Alternatively maybe the setting should actually disable the "recently opened" altogether and so any result is coming in from the general file search scoring algorithm.

**Comment by SomeKittens** [comment]
I'd love to add scoring or just disable recently opened altogether.  Coming from SublimeText here, so my muscle memory assumes it'll only hit files in the project.  Currently, I get things like this:

![screen shot 2017-04-18 at 12 29 56 pm](https://cloud.githubusercontent.com/assets/1616464/25149431/47e0a8b2-2433-11e7-92f3-04cad5ebc030.png)

Every time I type in `pack` expecting the project's `package.json` I get `ui-router`'s and it bumps back to the top of Recently Opened.  This feature's been much more of a hassle than a helper for me.

**Comment by borekb** [comment]
@bpasero 

> the "Recently Opened" list is purely sorted by last access whereas the "File Results" are sorted by our matching algorithm

One important point here is that the "Recently Opened" is only sorted by last access until one starts typing. For example, we have lots of README files and say that I just read `./user-portal/client/README.md`. Before typing anything, it is usefully at the top:

![image](https://user-images.githubusercontent.com/101152/28165039-51d8b9c6-67d2-11e7-989d-d5504238b129.png)

However, after typing "r" (my habit is to hit Ctrl+P and just start typing), the results are "random" as far as I'm concerned:

![image](https://user-images.githubusercontent.com/101152/28165009-349ae118-67d2-11e7-814f-999d2d91f4c1.png)

I think that the search ranking should only be applied to the "File Results" section, not the "Recently Opened". (This is not against the idea of an setting to hide the "Recently Opened" section entirely but if it's there, I think it should be sorted by last access.)

**Comment by borekb** [comment]
Do you think it makes sense? Should I create a new issue for it or would this better be a bullet point in _Improve ranking of elements in quick open_ #27317 ?

**Comment by borekb** [comment]
@bpasero Does the recently open list maintain the recently open order now when I start typing?

**Comment by bpasero** [comment]
@borekb no, only when our scoring algorithm ends up with the same score for 2 entries we use the recency (previously we just sorted by path length).

**Comment by borekb** [comment]
@bpasero thanks for the explanation, I still think that this list should just sort by recency so I've created a new issue for it: https://github.com/Microsoft/vscode/issues/35610

Anyway, it's awesome to see scoring improvements, thanks!
