### ISSUE TITLE
Mouse cursor disappears when I try to hover in the editor and terminal.

### ISSUE THREAD

**Issue by moinam** [microsoft/vscode#205491]
Type: <b>Bug</b>

after the new vscode update my cursor is disappearing when i enter the terminal view or the editor view. It has become now insane to work with the IDE. All of my drivers are updated and it never happens in any other application other than vscode.

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.26058
Modes:
Remote OS version: Linux x64 5.4.0-155-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|39.65GB (21.81GB free)|
|Process Argv|--crash-reporter-id 57ebbe04-e1bc-4363-a596-ab4f27812850|
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: n08-00|
|OS|Linux x64 5.4.0-155-generic|
|CPUs|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (80 x 2722)|
|Memory (System)|754.07GB (637.79GB free)|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
plsql|cas|0.0.5
r-development|Hri|1.0.0
mysql-syntax|jak|1.3.1
better-cpp-syntax|jef|1.17.2
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.338.1
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
atom-keybindings|ms-|3.3.0
remote-explorer|ms-|0.4.1
blackbox|Bla|1.2.61
githistory|don|0.6.20
gitlens|eam|14.8.2
prettier-vscode|esb|10.1.0
copilot|Git|1.162.0
copilot-chat|Git|0.12.2
vscode-pull-request-github|Git|0.80.1
rainbow-csv|mec|3.11.0
autopep8|ms-|2023.8.0
black-formatter|ms-|2024.0.1
debugpy|ms-|2024.0.0
isort|ms-|2023.10.1
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.1.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
vscode-yaml|red|1.14.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
edj9j583:30958191
a89i1917:30961429
7j2b6412:30964151
ccp1r3:30958155

```

</details>

**Comment by galchinsky** [comment]
I met the same bug in Edge.

If you need a workaround, change the default pointer in Windows settings (Start -> mouse pointer size -> enter), either make it bigger, or make it black. Or turn off GPU acceleration.

```
1. Open command pallete (Ctrl + Shift + P)
2. Enter "Preferences: Configure Runtime Arguments"
3. Add config: "disable-hardware-acceleration": true
4. Restart VS Code
```

https://github.com/microsoft/vscode/issues/204181

**Comment by moinam** [comment]
> I met the same bug in Edge. https://issues.chromium.org/issues/40239916
> 
> If you need a workaround, change the default pointer in Windows settings (Start -> mouse pointer size -> enter), either make it bigger, or make it black. Or turn off GPU acceleration.
> 
> ```
> 1. Open command pallete (Ctrl + Shift + P)
> 2. Enter "Preferences: Configure Runtime Arguments"
> 3. Add config: "disable-hardware-acceleration": true
> 4. Restart VS Code
> ```
> 
> #204181

Thank you this worked 👍
