### ISSUE TITLE
Quick Fix imports menu instantly closes

### ISSUE THREAD

**Issue by Xenfo** [microsoft/vscode#205498]
Type: <b>Bug</b>

I'm not completely sure if this is caused by VSCode or Rust-Analyzer but I think it's VSCode. Whenever I try to open the imports menu from quick fixes, it instantly closes. It should wait for me to pick an import. This feature broke sometime within the last couple weeks.

https://github.com/microsoft/vscode/assets/46873232/f36f9b2e-7151-4841-a16b-a9ed25b4a4c5

VS Code version: Code - Insiders 1.87.0-insider (Universal) (00124e9e5830e3efc897db71c781899f8a676295, 2024-02-16T16:39:24.006Z)
OS version: Darwin arm64 23.2.0
Modes:
Remote OS version: Linux x64 6.7.4-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv|--crash-reporter-id 4f0d9ffc-0936-472c-b5f3-87ed96bfb3a8|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: arch|
|OS|Linux x64 6.7.4-arch1-1|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700F (20 x 799)|
|Memory (System)|31.20GB (5.94GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-nginx-conf|ahm|0.3.2
postcss|css|1.0.9
codespaces|Git|1.16.10
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.109.2024021615
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.5.2024011009
rust-analyzer|rus|0.3.1839

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:30784851
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:30962249
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30963552
d34g3935:30961436
edj9j583:30943796
fegfb526:30952798
7j2b6412:30951517
bg6jg535:30946824
ccp2r6:30958154

```

</details>

**Comment by justschen** [comment]
https://github.com/microsoft/vscode/issues/204606. tyler did some bisecting to one of my PRs, could be related.

@Xenfo im assuming this quick fix is supposed to open a quick pick?

**Comment by Xenfo** [comment]
> @Xenfo im assuming this quick fix is supposed to open a quick pick?

Yes it is.
