### ISSUE TITLE
Where in the name of sanity is the option to change folder in explorer

### ISSUE THREAD

**Issue by TrinityCryptx** [microsoft/vscode#205484]
Type: <b>Feature Request</b>

Hello,

As a paying customer for Microsoft's services.

I decided to download and install visual studio code.

I put in the wrong folder for explorer.

I tried changing said folder.

I have spent 10 minutes looking for the option to change said folder to the one I prefer.

There is no simple option, no right click option to add folder in explorer.

I am disgusted.

Absolutely disgusted at this design decision at what I believed to be a good company.

I pay my bills, I do my service to society, I dable in some programming from time to time.

Now I have just a basic issue.

I've had to file an entire feedback feature request to help the product made by Microsoft to ensure that I don't waste my time with such minor inconsequential things.

Disgusted.

Absolutely disgusted.

What in the name of sanity was the design decision here?

20 minutes later after creating an account on github because you don't make it clear I need a github account to make a feature request.

Even more disgusted.

What's more I get the impression you are likely to remove this due to public image.

ITS SO SIMPLE, LITERALLY JUST MAKE IT EASIER TO CHANGE THE FOLDER BEING USED IN EXPLORER, ITS NOT ROCKET SCIENCE!

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:42.342Z)
OS version: Linux arm64 6.1.0-rpi8-rpi-2712
Modes:

**Comment by gjsjohnmurray** [comment]
Please use the File menu.

To open a different folder, first close the one you opened in error.

Or to open a second folder in addition, use `Add Folder to Workspace`.

**Comment by TrinityCryptx** [comment]
Yep.

Right click on folder explore > Add Folder to Workspace 

Or

File > Open Folder
