### ISSUE TITLE
Can't use ALT+up/down to switch between search file filters

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#20547]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-whitespacer|deerawan|1.0.0|
|contextualduplicate|lafe|0.2.0|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.6.2|
|duplicatetext|rivenvirus|0.0.3|
|trailing-spaces|shardulm94|0.2.11|
|vscode-fileutils|sleistner|2.3.3|
|shader|slevesque|0.2.2|
|cmake|twxs|0.0.15|

---

Steps to Reproduce:

1. Open Find in Files. 
2. Go to the "files to include" box.
3. Make sure you've searched before with different file filters.
4. Press ALT + up/down arrow.

Expected result: Switch between previous file filters.
Result: Active line is moved.

I'm not sure if this is a missing feature or a bug, but I'm pretty sure it worked pre-1.9. (It works in Sublime and is something I use quite frequently)

![codebug_search_alt](https://cloud.githubusercontent.com/assets/1578924/22884735/c43ee5f0-f1f6-11e6-9067-bda9d6614de2.gif)

**Comment by sandy081** [comment]
Navigating history is only supported on Search field.

**Comment by sandy081** [comment]
Fixed by the PR #27476 

Verify:

History navigation in include and exclude text boxes using Alt + up and Alt +down keys.
History is remembered between window reloads

**Comment by chrmarti** [comment]
Trying to verify, I've searched including once *.js and once *.txt. I'd expect both to be in the history, but only *.txt shows up.

- VSCode Version: Code - Insiders 1.15.0-insider (211ffdf184329179ddca9c1fe993f5f11f3c4dda, 2017-08-02T05:07:49.324Z)
- OS Version: Darwin x64 16.6.0
- Extensions: none

**Comment by roblourens** [comment]
It only saves the history on a navigate action, when it should save on search submit
