### ISSUE TITLE
Insert at cursor enabled, but does nothing when no editor is open

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#205401]
Don't have an editor open, run a chat request and get a result with a codeblock. 🐛 see the insert at cursor action enabled, clicking it does nothing.

![Image](https://github.com/microsoft/vscode/assets/29464607/69e9395b-1a16-43d1-a5cf-f71a1a4bdbc3)

**Comment by roblourens** [comment]
Works fine for me. Please check for errors

**Comment by meganrogge** [comment]
Hm, it's working now, but only when I have an editor open. Shouldn't the action be disabled when I have no editors open?

**Comment by roblourens** [comment]
Probably. We don't have the right context keys right now for the right set of requirements

**Comment by meganrogge** [comment]
should it open a new document in the case of no active text editor?
