### ISSUE TITLE
vsce-sign: Respect the DOTNET_CLI_HOME when downloaded extensions from the marketplace.

### ISSUE THREAD

**Issue by isFakeAccount** [microsoft/vscode#205452]
vsce-sign should respect the `$DOTNET_CLI_HOME` instead of creating a `$HOME`.dotnet/corefx/cryptography/crls` directory. 

Even the `dotnet/sdk` suports the `$DOTNET_CLI_HOME`: https://github.com/dotnet/sdk/issues/8887

If the `$DOTNET_CLI_HOME` doesn't exist, vsce-sign can fallback on the `$HOME/.dotnet`

**Comment by sandy081** [comment]
VS Code does not deal with these env variables, it should be the Dot Net extension. Please file issue against it.

**Comment by isFakeAccount** [comment]
> VS Code does not deal with these env variables, it should be the Dot Net extension. Please file issue against it.

I am confused by your comment. Yes, VSCode does not deal with these env variables. That's precisely the issue. If VSCode dealt with those env variables then it would not create the `.dotnet` directory in the `$HOME`. 

Also, I don't have dot net extension. I have tested with several extensions and all of them create this directory.  

Are you sure this has nothing to do with the marketplace.  Does VSCode generate X509 CRL certs?

**Comment by isFakeAccount** [comment]
ok I figured out what creates this. vsce-sign creates this. I don't know which repo is responsible for vsce-sign though.

At least I can disable it by setting the `"extensions.verifySignature": false`

https://github.com/microsoft/vscode/issues/184993

**Comment by kands-code** [comment]
> ok I figured out what creates this. vsce-sign creates this. I don't know which repo is responsible for vsce-sign though.

It may be this repository [Sign](https://github.com/dotnet/sign), the relevant reference is here [msdoc](https://learn.microsoft.com/en-us/visualstudio/extensibility/signing-vsix-packages?view=vs-2022).

I also encountered this problem recently, and the `extensions.verifySignature` configuration does not seem to exist.

![image](https://github.com/user-attachments/assets/a467f0b1-a45e-4636-af75-2c7b1c053a4e)

**Comment by isFakeAccount** [comment]
@kands-code  It is vsce-sign because I monitored the directory using [LoggedFS](https://rflament.github.io/loggedfs/).

I think vscode removed this config in newer releases at some point.

**Comment by kands-code** [comment]
> @kands-code It is vsce-sign because I monitored the directory using [LoggedFS](https://rflament.github.io/loggedfs/).
> 
> I think vscode removed this config in newer releases at some point.

Oh, I see. I still don't know why I can't change the directory for this part via environment variables though. Also, thanks for the tool you recommended.
