### ISSUE TITLE
Feature Request - Save All s/cut

### ISSUE THREAD

**Issue by 72gm** [Microsoft/vscode#20544]
I've been using VS Code for a couple of months now and I'm baffled as to why you have no keyboard shortcut for save all?

In VS full its ctrl+shift+s which you seem to have allocated to save as in VS code .... something that I have never even thought about using, let alone actually needed to use!?

Unless I have missed something totally obvious??

**Comment by HofmaDresu** [comment]
This appears to be available, not sure when it was added

Windows: Ctrl+K S
Linux: Ctrl+Shift+S
Mac: ⌥⌘S

**Comment by 72gm** [comment]
I didn't know there was a list of key bindings, so for anyone else... 

ctrl+k+s will open up list of key bindings and allow you to override them... so if you want ctrl+shift+s to be "save all" then you can do this easily!!

**Comment by joaomoreno** [comment]
Our [keybindings documentation](http://code.visualstudio.com/docs/customization/keybindings) is quite comprehensive.
