### ISSUE TITLE
Where did window.showFullPath go?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#20559]
Doesn't seem to be available anymore, Is there a replacement for it?

**Comment by fchiumeo** [comment]
i found this [1.10 changelog](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_10.md#configurable-window-title)

**Comment by Tyriar** [comment]
Cheers @fchiumeo, just what I was looking for! :smiley:
