### ISSUE TITLE
Syntax Highlight of SQL in php string is utterly random

### ISSUE THREAD

**Issue by php4fan** [microsoft/vscode#205571]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.86.2
- OS Version: Manjaro Linux

Steps to Reproduce:

Type the following code in a PHP file:

![image](https://github.com/microsoft/vscode/assets/13969584/60e2b61e-cd1b-453a-979d-126c06eaf9da)

Either you highlight SQL code in PHP strings or you don't. If you do, the highlight has to make sense.

This doesn't.

1) Here:
![image](https://github.com/microsoft/vscode/assets/13969584/86c37ed6-30c9-4608-85c9-3518abd60efe)

Why is the `name` field highlighted in blue but the other three arent?

2) Here:
![image](https://github.com/microsoft/vscode/assets/13969584/dedbce8e-19c2-4747-9e9e-98a6af5a28b3)

Why is the parameter `:name` highlighted in blue but `:userinfo` isn't?

3) Here:
![image](https://github.com/microsoft/vscode/assets/13969584/86ea7a85-8843-4441-b1da-43f13c383c68)

same as (1).

**Comment by lszomoru** [comment]
@alexr00, is this a grammar issue or language server issue? Thanks!

**Comment by alexr00** [comment]
@php4fan can you share a copy/pastable example that I can use to reproduce the issue?

**Comment by php4fan** [comment]
```
<?php

$query = "INSERT INTO `user`
(telegram_id, name, info)
VALUES (
    {$user['id']},
    :name,
    :userinfo
)
ON DUPLICATE KEY UPDATE
    info = JSON_MERGE_PATCH(info, VALUES(info)),
    name = VALUES(name)";
```

**Comment by alexr00** [comment]
Thank you!

It looks like the same highlight occurs even outside of PHP when it's just an SQL file. It turns out that `name` is actually a keyword in SQL: https://dev.mysql.com/doc/refman/8.0/en/keywords.html
It appears to be fine to use in some places, but not in other: https://stackoverflow.com/questions/738124/is-name-a-reserved-word-in-mysql

**Comment by php4fan** [comment]
Ok, so the error is not in not highlighting the other column names, it's in highlighting the one that happens to be called "name". And I can see there are other keywords that have the same issue, like "user".

This is still a bug. In the cases shown above the word "name" has no special meaning in that context, it's a column name like any other, and the query above works as is. That the word may have some meaning in some other context is irrelevant. If the syntax highlight for SQL is this bad, it is truly worse than no highlight at all.
