### ISSUE TITLE
VS Code should enable navigation for more file/line formats

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#20556]
- VSCode Version: 1.10.0-insiders

**Issue**: VS Code has a filter that runs over text sent to the debug console which enables navigation if the text looks like '\<filePath\>:\<line\>:\<column\>'. But I am not aware of a way (and please correct me if I am  wrong) to add in more 'file/line/column' scrappers. .NET Core internally will sometimes dump stack traces to the output stream in its format. It would be nice if they were navigable, but they are currently not.

**Trivial example to reproduce the problem**:
Run the following code which will dump two string to the debug console:
```
   at Program.SleepThread(Object obj) in d:\proj\clicon\Program.cs:line 23
   at Program.SleepThread(Object obj) in d:\proj\clicon\Program.cs:23:0
```

**Expected Result**
Both links should be navigable

**Actual Result**
Only the second (artificial) link is.

Trivial example to show the problem:
```csharp
            try
            {
                throw new Exception("My example exception");
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.StackTrace);
                Debug.WriteLine(e.StackTrace.Replace("line ", "") + ":0");
            }
```

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/34026
