### ISSUE TITLE
Move Panel to Bottom only works if the panel doesn't have the focus

### ISSUE THREAD

**Issue by MangelMaxime** [microsoft/vscode#205584]
Type: <b>Bug</b>

1. `View: Toggle terminal` (to open the terminal panel)
2. `View: Toggle maximized panel`
3. `View: Move panel to bottom`

You should see that nothing happens because you had the focus inside of the terminal.

However, if you try to execute `View: Toggle maximised panel` you will see that it works even when the focus is in the terminal.

Workaround:

1. `View: Toggle terminal` (to open the terminal panel)
2. `View: Toggle maximized panel`
3. Click on the top bar wehre `OUTPUT | DEBUG CONSOLE | PORTS | TERMINAL` is displayed to force lose the focus of the terminal
4. `View: Move panel to bottom` now the panel return at its original place at the bottom

https://github.com/microsoft/vscode/assets/4760796/48c029b8-c564-43d2-9893-34c276266286

I would expect `View: Move panel to bottom` to works independently if the panel as the focus or not like `View: Toggle maximised panel` works.

I was able to reproduce it using VSCode insiders without any extensions installed.

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:12.210Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 3, 4|
|Memory (System)|64.00GB (2.86GB free)|
|Process Argv|--crash-reporter-id 9f2ded26-d6d2-4c9c-a38e-75c64d4b88b8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-template-fsharp-highlight|alf|1.7.0
vscode-tailwindcss|bra|0.10.5
npm-intellisense|chr|1.4.5
dart-code|Dar|3.82.0
vscode-markdownlint|Dav|0.54.0
vscode-eslint|dba|2.4.4
gitlens|eam|14.8.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
shell-format|fox|7.2.5
better-nunjucks|gin|0.2.5
copilot|Git|1.162.0
copilot-chat|Git|0.12.2
go|gol|0.41.0
vscode-graphql|Gra|0.9.1
vscode-graphql-execution|Gra|0.2.6
vscode-graphql-syntax|Gra|1.3.2
rest-client|hum|0.25.1
Ionide-Paket|Ion|2.0.0
path-autocomplete|ion|1.25.0
csharp|ms-|2.15.30
vscode-dotnet-runtime|ms-|2.0.1
debugpy|ms-|2024.0.0
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
remote-containers|ms-|0.338.1
vsliveshare|ms-|1.0.5905
vscode-nunjucks-formatter|oki|0.1.3
material-icon-theme|PKi|4.34.0
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
rust-analyzer|rus|0.3.1850
bash-beautify|sha|0.1.1
vscode-scss-formatter|sib|3.0.0
sass-indented|syl|1.8.29
even-better-toml|tam|0.19.2
ayu|tea|1.0.5
msbuild-project-tools|tin|0.6.0
vscode-harpoon|tob|1.5.0
pretty-ts-errors|Yoa|0.5.3
vitest-explorer|Zix|0.2.46

</details>

**Comment by benibenj** [comment]
`View: Move panel to bottom` Is not expected to do anything when the panel is maximized. Use the `View: Toggle maximized panel` to unmaximize the panel. 

There seems to be a focus bug which I have fixed
