### ISSUE TITLE
InteractiveChatController unit test is consuming too much time

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#205510]
InteractiveChatController unit test is consuming too much time

Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=257617
Changes: https://github.com/Microsoft/vscode/compare/3fdb0fa...9aa943b

**Comment by jrieken** [comment]
seems to be fixed by now
