### ISSUE TITLE
Terminals on the right side should be treated equally ( like keyboard shortcuts ) .

### ISSUE THREAD

**Issue by knowanegg** [microsoft/vscode#205529]
When I drag one of the terminal's bash sessions to the right side, using the search shortcut Ctrl+w in nano does not get passed to nano. Instead, VSCode directly closes that bash session.
![image](https://github.com/microsoft/vscode/assets/108446106/54d5862c-aa91-4e2e-9cff-d1cac91cd721)
Hope there can be differentiated treatment for the terminal.

**Comment by meganrogge** [comment]
You can configure the keybinding for `workbench.action.terminal.killEditor` IE remove it so that your other keybinding gets applied
