### ISSUE TITLE
Strange terminal sticky scroll state

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#205578]
I somehow got into this:

![image](https://github.com/microsoft/vscode/assets/900690/c7b3897c-9b79-4624-a7c0-bb2289a48197)

I am not sure how sticky scroll in the terminal should work but I felt this was a bit misleading.

**Comment by Tyriar** [comment]
Likely related to something going wrong after a resize. There's also something going wrong with the sticky scroll xterm.js resize here:

![image](https://github.com/microsoft/vscode/assets/2193314/37aad69d-9a4d-40f3-a6c1-7e8e411d1fb4)

Guessing this was on macOS.

**Comment by bpasero** [comment]
Yeah on macOS.

**Comment by Tyriar** [comment]
Can repro:

1. Run vscode build task
2. Reduce width of the terminal 🐛 the sticky scroll gets pushed down to accommodate new content but does not seem to update the overlay dimensions

<img width="772" alt="Screenshot 2024-02-29 at 10 15 31" src="https://github.com/microsoft/vscode/assets/2193314/60d55262-07ba-43c8-90e8-ebe1b1020523">

**Comment by bpasero** [comment]
I did not see this again.
