### ISSUE TITLE
Test: SCM - incoming changes file decoration

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#205540]
Refs: https://github.com/microsoft/vscode/issues/204982

- [x] anyOS @meganrogge
- [x] anyOS @benibenj

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23205540%0A%0A&assignees=lszomoru)

---

This milestone we have added file decorations for the files that have been modified on the remote when have incoming changes.

### Prerequisites
1. Install the latest version of VS Code Insiders
2. Ensure that you have the following setting enabled - `git.decorations.enabled`

### Testplan
1. Launch VS Code Insiders
2. Open a folder/workspace that contains a git repository
3. Open the "Source Control" view and see if you have any incoming changes
4. Open the repository on GitHub.com (or clone the repository in a second directory)
5. Make changes to files:
    * Modify some files and commit the changes
    * Delete a file and commit the change
    * Rename a file and commit the change
6. Switch back to VS Code and run the "Git: Fetch" command
    * Confirm that the new commits appear as incoming changes
7. Switch to the Explorer
    * Confirm that the files have the correct decorations
9. Click on the branch name in the status bar and create a new branch
    * Confirm that the decorations are cleared
10. Click on the branch name in the status bar and switch back to the original branch
    * Confirm that the files have the correct decorations
11. Open Settings and disable the `git.decorations.enabled` setting
    * Confirm that the file decorations cleared
12. Open Settings and enable the `git.decorations.enabled` setting 
    * Confirm that the files have the correct decorations
13. Invoke the "Git: Pull" command
    * Confirm that the commits are gone from incoming changes
    * Confirm that the file decorations cleared

**Comment by lszomoru** [comment]
Closing the TPI as we have decided to delay this by a milestone.

**Comment by benibenj** [comment]
Really nice! Love this feature
