### ISSUE TITLE
Test: Issue Reporter command and menu contribution for additional data

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#205587]
Continuation of https://github.com/microsoft/vscode/issues/196324

- [x] anyOS @paulacamargo25 
- [x] anyOS @hediet
- [x] anyOS @andreamah

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23205587%0A%0A&assignees=justschen)

---

## Overview
Added improvements to the Issue Reporter Command. Instead of an API, we now are testing a version of the `openIssueReporter` command that does virtually the same thing as the API. 

Last iteration, we added `data` and `uri` to the command shape. This iteration, we allow extensions to contribute a menu and command to call `workbench.action.openIssueReporter` which can load data from the original issue reporter flow.

The following is the structure of what an example call to `openIssueReporter` could look like.
```ts
async function openIssueReporter() {
	await vscode.commands.executeCommand('workbench.action.openIssueReporter', {
		extensionId: 'ms-python.python',
		issueTitle: 'title here',
		data: dataString,
                uri: Uri.parse('https://github.com/microsoft/vscode-copilot-release'), // changed url here for demo
	});
}
```

The general idea is that from anywhere, you could run this command and give it some parameters, mainly things like a template (which will go to the body), data (which if contributed, will add a data field), or a uri (which if contributed, will replace the repo url). 

Now that we have a menu contribution, the menu will be contributed from a `package.json` and point to a command which will run the `openIssueReporter` command. We're basically using the menu service as a medium to run commands via our extension selection!

## To test
1. Implement the command, contribute it, and add a menu contribution. This can be done basically anywhere, but for simplicity, an extension may be the easiest. If you have a personal extension to test on, fantastic. If not, check out [this extension's implementation](https://github.com/Yoyokrazy/clean-nb-imports-ext/blob/f410c53bb95585f46e4ae10cafd9843660b15430/src/extension.ts#L50). 
2. The contributed command should eventually call `workbench.action.openIssueReporter`
3. Contribute a menu contribution point like this:
``` json
"contributes": {
	"commands": [
		{
			"command": "extension.myCommand",
				"title": "Report Issue"
		}
	],
		"menus": {
			"issue/reporter": [
				{
					"command": "extension.myCommand"
				}
			]
		}
	},
```
4. Also ensure that you add `"contribIssueReporter"` to `enabledApiProposals` in `package.json` of your extension.
5. Once the command and menu contribution have been added, open the issue reporter via `Help: Report Issue` from the command palette. 
6. Select the extension that has the menu contribution, observe if data is properly added (issue body, issue data, check that the URI is properly changed).
7. Try adding multiple extensions, test switching between to make sure the right data is added.
8. To simulate a long data collection task, try adding a `timeout` (see [here](https://github.com/Yoyokrazy/clean-nb-imports-ext/blob/f410c53bb95585f46e4ae10cafd9843660b15430/src/extension.ts#L52) for example)
9. Ensure that the original issue reporter workflow for exgtensions that don't contribute a menu/command is not broken.

## Some things to make sure:
* The right things are hidden or shown
* When you switch between an extension and another extension, the correct things are shown, and correct url (when submitting) is reached.
* Data is populated correctly in both template and extension data sections.
* Correct text is sent to GitHub after pressing submit
 
## Some tips:
* [Create an extension guide](https://code.visualstudio.com/api/get-started/your-first-extension)
* [Extensions samples repo](https://github.com/Microsoft/vscode-extension-samples)

Sorry this one is super long, but I'd appreciate any feedback on UI/UX, how the extension contributions are structured, etc. Thanks!

**Comment by hediet** [comment]
It works, but I find this API very weird and unconventional.

Basically, a menu entry is used as provider registration, a command as provider definition and `workbench.action.openIssueReporter` as callback.

**Comment by paulacamargo25** [comment]
Thanks @justschen , it works fine for me, nice work 👍

**Comment by andreamah** [comment]
Great work! Reflecting a bit on the structure of the API, it does seem to be a little confusing from an extension API standpoint. I would expecting something like a `Provider` that specifies the constant info needed, plus a callback for data (see `TextSearchProvider` API, which accepts a class that defines a function for acting on results).

Although, it seems that you're doing it this way so that you can encapsulate the functionality into a command. Is this because there is a demand for filing against different repos in different cases? You've probably gotten lots of feedback on the API already from the sync, but using the API did seem a bit different from the norm.
