### ISSUE TITLE
Test: Git - setting/action to always replace local tags

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#205585]
Refs: https://github.com/microsoft/vscode/issues/176799

- [x] anyOS @anthonykim1
- [x] anyOS @deepak1556

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23205585%0A%0A&assignees=lszomoru)

---

About a year ago we have added code to detect when a `git pull` operation fails due to conflicting tags. This error condition can occur if someone force pushes a tag. This milestone we added a new setting, `git.replaceTagsWhenPull`, and a user gesture to always replace local tags.

### Prerequisites
1. Install the latest VS Code Insiders
2. Ensure that the `git.replaceTagsWhenPull` setting is set to `false`
3. Clone the same git repository in two separate folders (ex: folder1, folder2)

### Test plan
1. Open folder1 in one instance, and folder2 in the second instance
2. Open a terminal window and run the following commands in folder1:
    * `git tag v1 -m v1`
    * `git push --tags`
3. Open a terminal window and run the following commands in folder2:
    * `git tag v1 -m v1 HEAD^1`
    * `git push --tags --force`
4. Launch VS Code Insiders and open folder1
5. Execute the "Git: Pull" command
    * Confirm that a dialog is shown that provides details about the conflicting tag
6. Choose "Always Replace Local Tag(s)" option
    * Confirm that the pull operation completes
    * Confirm that the `git.replaceTagsWhenPull` setting is set to `true` in your user settings
7. Switch back to the terminal window and execute the following commands in folder1: 
    * `git tag v2 -m v2`
    * `git push --tags`
8. Switch back to the terminal window and execute the following commands in folder2:  
    * `git tag v2 -m v2 HEAD^2`
    * `git push --tags --force`
9. Switch back to VS Code that has folder1 opened and execute the "Git: Pull" command
    * Confirm that no dialog is being show
    * Confirm that the pull operation completes successfully

**Comment by anthonykim1** [comment]
<img width="266" alt="Screenshot 2024-02-20 at 10 52 01 AM" src="https://github.com/microsoft/vscode/assets/62267334/eccc4e41-eb16-4f8e-873c-438ca76f7ef9">
Everything as expected until: I got an error `fatal: Failed to resolve 'HEAD^2' as a valid ref.` when trying to run `git tag v2 -m v2 HEAD^2`. I ran `git tag v2 -m v2` and followed the remaining steps, and saw no dialog is shown as expected.
