### ISSUE TITLE
A call for more extension categories

### ISSUE THREAD

**Issue by Jakobud** [Microsoft/vscode#20558]
Taking a look at the current state of extension categories:

![screen shot 2017-02-13 at 10 39 01 am](https://cloud.githubusercontent.com/assets/87356/22895161/c9cb32f8-f1d8-11e6-8645-38cd3ce4aad9.png)

Other: 1087 extensions!

This is a pretty clear sign that some more categories are needed in the extension marketplace. Has this been brought up at all? How would the team and/or community go about deciding on what an appropriate list of categories would be and how difficult is it for the team to add these into the marketplace?

**Comment by sean-mcmanus** [comment]
"Other" is a category that extensions explicitly specify in their package.json, and a quick look at the list reveals that a lot of the extensions seem misclassified as Other when they already belong in another category. What new extension classifications did you want? Build? Source Control? Metrics? I assume they'd add more categories when they feel enough popular extensions fall into it.

**Comment by Jakobud** [comment]
I understand that an extension specifies it's category in the `package.json` as I am an extension developer. I just noticed that it appears that a lot of (if not the majority of) extensions don't fit into the current list of available categories and therefore developers end up using "Other" since it's the only available "catch-all" category.

There certain does seem to be a decent amount of mis-categorized extensions when I take a glance at the list. 

I don't know what a good list of them would be. I would expect that the plethora of extension authors out there would be able to offer a lot of suggestions. Build and Source Control for example would definitely be some useful categories imho.

**Comment by nealot** [comment]
Searching through the extension ecosystem is pretty confusing for a beginner. What should you search for when trying to find an extension that adds a new activity panel? I've seen tags like "explorer", "tree", and "sidebar". Why can't these just be grouped together under something like "activity bar panel"?

**Comment by prashantvc** [comment]
Marketplace team is working on supporting more categories on the gallery.
Can anyone reopen this issue please?
