### ISSUE TITLE
Test: slash and agent commands in voice chat

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#205523]
Refs https://github.com/microsoft/vscode/issues/201220

- [x] Windows @alexr00
- [x] macOS @Tyriar
- [x] Linux @connor4312 @rzhao271 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23205523%0A%0A&assignees=bpasero)

---

**Setup:** Install the `ms-vscode.vscode-speech` and GitHub Copilot Chat extension

**Testing:**
* open the chat view and start speech-to-text via the microphone icon
* literally say phrases such as "at workspace", "at code"
* this should insert related agents into the chat (`@workspace`, `@vscode`) if recognised properly
* try with commands such as "slash fix"
* this should insert `@workspace /fix`
* when agents or slash commands are inserted, you can pause and your search will not auto trigger until you have provided more input
* try the same with inline chat: here, agents are not supported, but slash commands like "slash fix" should work

**Comment by alexr00** [comment]
One of the times it misheard me 🤣

![image](https://github.com/microsoft/vscode/assets/38270282/a9de9451-c66f-4c45-bb69-bff6461ae72d)

**Comment by bpasero** [comment]
Great one!

**Comment by rzhao271** [comment]
Closing this issue. Following up with the Linux audio input issue at https://github.com/microsoft/vscode/issues/205758
