### ISSUE TITLE
IntelliSense suggests ".git" in require path

### ISSUE THREAD

**Issue by bpaczkowski** [Microsoft/vscode#20557]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows 10

Whenever I write a path in the require statement that starts with a dot, IntelliSense suggests `.git` path, which is incredibly annoying because a dot followed by a slash always equates to `.git/`. You have to press escape after the dot to exit the suggestion and then follow it with a slash, which I forgot to do more times than I'd like to admit.

![code_2017-02-13_18-32-30](https://cloud.githubusercontent.com/assets/1371800/22894865/d215a406-f21a-11e6-81cc-46e2d44b0d9c.png)

I'm not exactly sure what is the root cause, but disabling my `jsconfig.json` fixes it. My config looks like this: 
```json
{
  "compilerOptions": {
    "target": "es6",
    "baseUrl": ".",
    "paths": {
      "src/*": ["./*"]
    },
    "module": "commonjs"
  },
  "exclude": [
    "node_modules",
    ".git"
  ]
}
```

`.git` is excluded in workspace settings, I also tried running VS Code with extension disabled and default settings, with the same result.

**Comment by mjbvz** [comment]
efe5d1c makes it so that typing `/` will no longer autocomplete paths.

I've also opened https://github.com/Microsoft/TypeScript/issues/14283 against TypeScript to track excluded files and folders being included in the path suggestions.
