### ISSUE TITLE
MacOS VSCode is broken. Move it to Bin

### ISSUE THREAD

**Issue by dellis1972** [microsoft/vscode#205516]
Type: <b>Bug</b>

I've had this happen twice in the last month. MacOS reports tht VSCode is broken and has to be moved to the bin. I have to reinstall it each time. 

I don't have any steps to reproduce since it happens at random. So I guess just install it on MacOS and wait a while. I do tend to have more than one instance of VSCode running at a time.
They also tend to be left open for a long time. With repeated closing of the Mac (but not shutting down).

The VSCode installed is from the zip file on the website. I installed by extracting the file and drag and dropping it into the Applications folder in Finder.

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:12.210Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|34, 13, 6|
|Memory (System)|32.00GB (0.21GB free)|
|Process Argv|--crash-reporter-id 921906d4-a2aa-4b9c-beb4-9fc5586f83b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
ink|bru|1.3.1
vscode-markdownlint|Dav|0.54.0
vscode-dotnet-adapter|der|1.4.3
docs-article-templates|doc|1.0.3
docs-authoring-pack|doc|1.0.1
docs-build|doc|0.4.2
docs-images|doc|1.0.1
docs-markdown|doc|1.0.3
docs-preview|doc|1.0.3
docs-scaffolding|doc|1.0.4
docs-yaml|doc|1.0.1
xml|Dot|2.5.1
vscode-test-explorer|hbe|2.21.1
OpenShadingLanguage|Jam|1.2.0
Learn-Training-AI-Assistant|Lea|1.0.33
mgcb-editor|man|0.0.6
azure-pipelines|ms-|1.228.0
csdevkit|ms-|1.3.10
csharp|ms-|2.15.30
dotnet-maui|ms-|0.9.3
vscode-dotnet-runtime|ms-|2.0.1
vscodeintellicode-csharp|ms-|0.1.26
debugpy|ms-|2024.0.0
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
remote-containers|ms-|0.338.1
azure-account|ms-|0.11.6
cpptools|ms-|1.18.5
mono-debug|ms-|0.16.3
test-adapter-converter|ms-|0.1.9
vscode-yaml|red|1.14.0
rewrap|stk|1.16.3
code-spell-checker|str|3.0.1
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vstuc|vis|0.9.4
t4-support|zbe|0.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30962250
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
a89i1917:30961429
3ef8e399:30964150
bg6jg535:30958357
ccp1r3:30958155

```

</details>

**Comment by kalebers** [comment]
Hello, I use VSCode in two different Macbooks (M1 and late 2012 Intel). Both running without problems for months.
My guess would be a problem on your side, had kind the same issue one time, after updating my computer worked fine.

- Try to update your OS first, since you said you don't shut down your mac, I presume some updates or memory reset are up to date, maybe has something to do with it.
- Install VSCode from the official page, and make sure that the support files for your installation and libs are up to date.

Based on your previous information, doesn't seem to be a VSCode problem. 

Let us know how it goes

**Comment by joaomoreno** [comment]
No other applications cause this issue?
