### ISSUE TITLE
Test: Localize Inno Updater

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#205564]
Refs: #168894

- [x] windows @lszomoru
- [ ] windows @Yoyokrazy

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23205564%0A%0A&assignees=benibenj)

---

We added support to localize our update dialog on windows (inno updater). 

![ino_french](https://github.com/microsoft/vscode/assets/44439583/cce1ae77-f9b1-4dbe-bc2c-c2935ffb2481)
![ino_traditionalChinese](https://github.com/microsoft/vscode/assets/44439583/40aeda31-ef6c-4d78-851f-ff5e90149a20)

Test the following for 3 different languages. 

**Pick one language from:**
- french
- italian
- german
- spanish
- brazilianPortuguese
- hungarian
- turkish

**And two languages from:**
- korean
- russian
- japanese
- simplifiedChinese
- traditionalChinese

**Testing Steps:**

1. Download the latest windows insiders `setup.exe` from the [builds page](https://builds.code.visualstudio.com/builds/insider) (build needs to be from 20.02.2024 or newer). This step only needs to be done once.
2. Run the setup script from the command line with the language as argument: `setup.exe /LANG=ADD_LANGUAGE_HERE`
3. Go through the entire setup and open insiders. 
4. Quickly set `update.mode: manual`. (Only has to be done the first time)
5. Run the command `Developer: Apply Update...` and pick the `setup.exe` file you previously downloaded
6. After a couple seconds there will be an update available. Before updating I recommend recording your screen. Depending on your device, the update dialog might only show for 1 second. If you record your screen you will be able to more easily verify the text in the dialog.
7. Update & Stop Screen recording when done
8. The update dialog should have shown the 'Updating Visual Studio Code...' in the language you have picked. You do not need to verify if the translation is correct, you just need to make sure that it worked and that there is no encoding problems.
9. repeat 2 more times with other languages

**Comment by lszomoru** [comment]
I picked `hungarian`, `russian`, and `japanese`.

**Comment by Yoyokrazy** [comment]
tested french, korean, and simplified ✅ all worked correctly
