### ISSUE TITLE
Variable selection starting with dollar sign

### ISSUE THREAD

**Issue by thom-ek** [Microsoft/vscode#20550]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.1|

---

Steps to Reproduce:

1. In source code editor doubleclick on variable name starting with `$` sign like `$test` (commonly used by php and javascript and jQuery).
2. Only variable name `test` without `$` is selected. Whole variable `$test` should be selected.

**Comment by billymcintosh** [comment]
Solution here: https://github.com/Microsoft/vscode/issues/2036#issuecomment-193873124

**Comment by mjbvz** [comment]
@alexandrudima and @rebornix, I see our custom wordPattern for javascript used when single clicking on a word, but not when double clicking. It looks like it is falling back to the standard word regexp in that case. Is this the expected behavior?

**Comment by thom-ek** [comment]
Setting `editor.wordSeparators` is what I exactly was looking for. I'm closing this issue.
