### ISSUE TITLE
Tooltip blocks UI during CMD+P searches

### ISSUE THREAD

**Issue by idlethumbs** [microsoft/vscode#205548]
Type: <b>Feature Request</b>

After a recent update 
(I am on VSCODE insiders)
when using the CMD+P search input, after typing into the input a tooltip appears that explains how to use the input, this blocks the top result of the search from being read, and only disappears on moving the mouse which is very frustrating as usually would select the result using keyboard alone...

![image](https://github.com/microsoft/vscode/assets/9349874/e90df45c-9f0b-4830-b8c0-6735a9a4e6a2)

VS Code version: Code - Insiders 1.87.0-insider (Universal) (d84c946d27b649d614319c796911871320befd42, 2024-02-16T06:05:20.657Z)
OS version: Darwin arm64 23.3.0
Modes:

**Comment by TylerLeonhardt** [comment]
@idlethumbs do you see this in the latest insiders? I recall that this was fixed
