### ISSUE TITLE
SCM history: tree find (Ctrl+F) doesn't highlight matches

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#205501]
Type: <b>Bug</b>

Without filter mode selected, down-arrow from widget correctly navigates between matching nodes in the tree but the matches are not highlighted.

![image](https://github.com/microsoft/vscode/assets/6726799/6fc4284e-8484-44d0-9d22-9bf3e21864e5)

VS Code version: Code - Insiders 1.87.0-insider (00124e9e5830e3efc897db71c781899f8a676295, 2024-02-16T16:33:57.085Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by lszomoru** [comment]
Fixed in the latest VS Code Insiders release.

**Comment by meganrogge** [comment]
@gjsjohnmurray how were you triggering the find in that view? `cmd+f` doesn't work for me

**Comment by lszomoru** [comment]
@meganrogge, it looks like the default keybinding was changed to `cmd + option + f`.

**Comment by gjsjohnmurray** [comment]
> @meganrogge, it looks like the default keybinding was changed to `cmd + option + f`.

https://github.com/microsoft/vscode/pull/210634#issuecomment-2063570698
