### ISSUE TITLE
Command palette should score shorter commands higher

### ISSUE THREAD

**Issue by zweck** [Microsoft/vscode#20553]
When you jump into the command pallet and type `>install` the default option is to **Disable All Extensions**. I've just done this by accident assuming that the most matched command would be to **Install Extensions** I now have the task of going through and enabling all my extensions again :(

- VSCode Version: 1.9.1
- OS Version: MacOS 10.12.3

Steps to Reproduce:

1. hit `cmd` + `p`
2. type `>install` and hit `enter`

**Comment by bpasero** [comment]
Insiders is better but still not ideal:

![image](https://cloud.githubusercontent.com/assets/900690/23100585/52c7a6da-f685-11e6-8ec4-6aea05da2a4a.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14727
