### ISSUE TITLE
NO se conecta lsp

### ISSUE THREAD

**Issue by yeyi-su** [microsoft/vscode#205573]
Type: <b>Bug</b>

Using dotnet configured on PATH
Dotnet path: /usr/share/dotnet/dotnet
Activating C# standalone...
waiting for named pipe information from server...
[stdout] crit: Program[0]
      Server started with process ID 3083
[stdout] crit: Program[0]
      Waiting 0:01:00 for a debugger to attach
[Error - 15:10:28] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Timeout. Named pipe information not received from server.
	at q.<anonymous> (/home/andrea/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/dist/extension.js:2:1290803)
	at Generator.next (<anonymous>)
	at s (/home/andrea/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/dist/extension.js:2:1280740)
[stdout] {"pipeName":"/tmp/e5dfb11e.sock"}
received named pipe information from server

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:41:37.860Z)
OS version: Linux x64 5.15.0-94-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N2808  @ 1.58GHz (2 x 2250)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|3.71GB (1.07GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch /home/andrea/Descargas/TP-Belleza-master/belleza --crash-reporter-id 67a2446f-5cf2-4ff1-afcd-fbff73305f25|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|Lubuntu|
|XDG_CURRENT_DESKTOP|LXQt|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
htmlplay|bia|0.0.10
Ionide-fsharp|Ion|7.18.1
vscode-docker|ms-|1.29.0
vscode-language-pack-es|MS-|1.85.2024021409
csharp|ms-|2.15.30
dotnet-interactive-vscode|ms-|1.0.5101020
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.0.1
vscode-edge-devtools|ms-|2.1.4
debugpy|ms-|2024.0.0
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.1.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
b1063948:30958189
fegfb526:30961430
3ef8e399:30967273
ccp1r3:30958155

```

</details>

**Comment by roblourens** [comment]
Please file this on the repo for the C# extension, with more details about the problem you are seeing
