### ISSUE TITLE
Test Set settings directly from the release notes

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#205565]
Refs: https://github.com/microsoft/vscode/issues/204338

- [x] macOS @justschen 
- [x] linux @connor4312
- [x] windows @deepak1556

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23205565%0A%0A&assignees=alexr00)

---

You can now add a button that lets users set settings directly from the release notes when the release notes are open in VS Code:
![Recording 2024-02-19 at 14 57 26](https://github.com/microsoft/vscode/assets/38270282/2b8f26b4-2ea9-43f0-8436-c7eda23f8c58)

To test this, there's also a new command "Developer: Open Current File as Release Notes". You can create a new markdown file, write release notes in that file, then run the command to see what your release notes looks like. Note that your release notes must still be in the usual format of release notes (begins with `#`, Note that this means that you'll need to modify the top of the actual release notes in the vscode-docs repo). 

The syntax for adding one of these settings buttons is 

```
<code codesetting="your.setting.name:optionalYourSettingValue">your.setting.name</code>
```

This syntax allows the code block to be displayed as usual on `github.com`, but in VS Code, we can do special rendering. 

Things to verify:
- Verify that the special rendering works with or without the optional `:optionalYourSettingValue` included.
- Verify that if you click on one of these settings in the release notes where no `:optionalYourSettingValue` is specified you see an option to open in settings.
- Verify that if you click on one of these settings in the release notes where a `:optionalYourSettingValue` is specified you see an option to open in settings and an option to set the setting. Verify using the option to set the setting works.
- Verify that if you use one of these settings buttons to change a setting that the context menu changes and offers to restore your previous setting value. Verify that this restore option works.

**Comment by connor4312** [comment]
"Open Current File as Release Notes" just showed the actual release notes for me on Fedora:


https://github.com/microsoft/vscode/assets/2230985/e42e155c-b989-4394-8338-ad985204fe75

I then reloaded and got this error instead:

<img width="555" alt="24-02-2fa6f8f1-5433-4df2-8732-d5888c27013b" src="https://github.com/microsoft/vscode/assets/2230985/b404d747-15f1-4fe4-b65e-0c7191f5f85d">

I didn't see any more detailed errors in the console.

**Comment by connor4312** [comment]
Ah, okay, so I think I figured it out:

- The release notes need to be in the 'real' format but they cannot contain the metadata section from the vscode-docs repo: the first line should be `# Month Year`
- There is aggressive caching as Deepak found in https://github.com/microsoft/vscode/issues/205675, so after making any changes or fixes you must reload the window and/or change profiles
