### ISSUE TITLE
Chat action items should vertically align to top

### ISSUE THREAD

**Issue by hbons** [microsoft/vscode#205650]
In VS Code action items inside inputs are vertically aligned to top, in the Chat features they are centered in the middle. This happens when putting in a lot of text or pressing Shift+Enter.

Panel:
<img width="425" alt="image" src="https://github.com/microsoft/vscode/assets/103326/6a32ad8b-1522-4573-ae44-4b171f90b7bb">

Inline:
<img width="608" alt="image" src="https://github.com/microsoft/vscode/assets/103326/3f122090-951a-4a08-8b91-c9ff709b5905">

Quick:
<img width="621" alt="image" src="https://github.com/microsoft/vscode/assets/103326/de3732d0-d342-4f66-8be0-a5dc248784b6">

For Inline and Quick the action items to the right of the input box should also stick to the top.

**Comment by daviddossett** [comment]
Seems like we have a mix over top-aligned and overflow w/ scroll (see below). But I agree that we should be consistent as much as possible. But it does feel like a chat send button should generally but aligned to the bottom, no? 

We may even consider rendering the toolbar on its own row once we're into multiple lines. That would ensure the text isn't forced to fill a tiny space now that we have 2+ icons. 

Here's how Teams does it as an example:

![Image](https://github.com/microsoft/vscode/assets/25163139/b0cc1f5b-4065-4c95-9753-fa8f05eda7cf)

## Prior art

![Image](https://github.com/microsoft/vscode/assets/25163139/ff75b686-b5a0-4517-8484-0717235382c2)

![Image](https://github.com/microsoft/vscode/assets/25163139/63b4adaf-ffc9-4229-af87-70f1dfceea91)

![Image](https://github.com/microsoft/vscode/assets/25163139/9719ff87-6d99-4f54-a67a-b28ebebfa1a2)

**Comment by roblourens** [comment]
Would be awesome if the text could wrap around it, especially in the narrow search widget case, I've always wanted that but I think it would be a pain to implement.

**Comment by hbons** [comment]
Don't have a strong opinion about top or bottom, I think each can be justified on a case-by-case basis. but middle looks weird. :)

For example, iInline Chat may want to do top alignment as the icons would align with those outside the input field (poppet and close)
