### ISSUE TITLE
Inno setup - automatically install language pack

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#205666]
Testing #205564

I might misunderstand the scope of the work here but I would have expected that if I go through the setup using a particular language, when the product launches it would make the language of the setup. I think that it would be nice to automatically install the language pack that matches the setup language.

**Comment by benibenj** [comment]
This is not very related to the scope of this work, however, this is still a valid feature request and I wondered the same thing after running the setup scripts in the different languages. Maybe @joaomoreno or @TylerLeonhardt can clarify why we aren't doing so yet.

**Comment by TylerLeonhardt** [comment]
Might be a cool thing to explicitly call out in the setup. Streamline things.

Today, after they install VS Code and they open it for the first time, you do get a notification that says "do you wanna get the language pack" in the language that their OS is set to (if we have a language pack for that language of course)

So we _do_ kinda have a solution for this, but it's not as nice as a checkbox in the setup.
