### ISSUE TITLE
Consider supporting files with .msil extension

### ISSUE THREAD

**Issue by hgleaves-ncuadmin** [Microsoft/vscode#20562]
Support the compilation/translation of files with a .msil extension. 

Currently there is no form of IDE support for MSIL source code, e.g.

    .assembly hello{}
    .class hello{
        .method static public void main() il managed{
        .entrypoint
        .locals( string V_0)
         ldstr "hi there"
        stloc.0
        ret
        }
    }

Only clumsy command line options exist today for this.

**Comment by joaomoreno** [comment]
Did you know we have a pretty big [extension Marketplace](https://marketplace.visualstudio.com/?VScode=1)? There's even an [IL Complete](https://marketplace.visualstudio.com/items?itemName=wk-j.vscode-cil-complete) extension.
