### ISSUE TITLE
Why does `LanguageModelAccess` have an exposed `model` property?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#205632]
Testing #205609

I know what the model is, I requested it. This seems kinda redundant and I feel like we aren't usually redundant in API. I don't think we need the `.model` property.

**Comment by jrieken** [comment]
The idea is that `model` and `id` aren't necessarily the same, e.g you can ask for `gpt-3.5` and get `gpt-3.5-turbo`

**Comment by TylerLeonhardt** [comment]
I guess my only argument to that is... we don't need this `model` property until we are going down the direction of aliasing. If we are planning on aliasing from the start then yeah  I suppose we should have this API but if not, I question if it needs to be finalized.

For example, if we instead provide extensions an easier way to query `lm.languageModels` and find what they're looking for, we don't need aliasing and thus don't need `.model`.

Just trying to push for "no API is the best API" 😄

**Comment by jrieken** [comment]
Obsolete - the lm access object is gone
