### ISSUE TITLE
How do I only activate when my chat participant is called?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#205631]
Testing #205609

I don't want my extension to activate until my chat participant is called. I load some big JSON files into my chat participant and don't want to do that every time. There should be an activationEvent like `onChatParticipant:thethingimention`

**Comment by roblourens** [comment]
We are still discussing how to do this, but we will be adding some activation event

**Comment by roblourens** [comment]
It exists now (and is autogenerated when your package.json contributes a participant)
