### ISSUE TITLE
Closing the Signals help menus insert settings into my settings file

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#205684]
Testing #205384

- Run "List Signal Announcements"
- Close the picker
- A bunch of settings are inserted

![Image](https://github.com/microsoft/vscode/assets/323878/5d142c60-35ed-4b60-a611-0a60c7c3cccf)

And `accessibility.signals.chatResponseReceived` has a warning on "announcement" that says `Property announcement is not allowed.`

This also happens with "List Signal Sounds" but only with `accessibility.signals.format`

**Comment by meganrogge** [comment]
It's expected that they're inserted as I'm updating the configuration. 

Tracking the issue you mentioned with `chatResponseReceived` here [#205736](https://github.com/microsoft/vscode/issues/205736)
