### ISSUE TITLE
Test: `@vscode/l10n-dev`'s `generate-azure` command

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#205619]
Refs: https://github.com/microsoft/vscode-l10n/issues/154

- [x] anyOS @bpasero
- [x] anyOS @karrtikr

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23205619%0A%0A&assignees=TylerLeonhardt)

---

This month we released some new tooling for extension authors to use Azure Translate to translate their extensions. The hope is that since Azure Translator comes with a free tier, that extension authors will want to support more users by localizing their extensions for free!

Here's the process:
* Have an extension that uses `vscode.l10n.t()` or `package.nls.json` (you can see how to use these [in the README](https://github.com/microsoft/vscode-l10n?tab=readme-ov-file#localization-tooling-for-visual-studio-code)
* I recommend you set the `l10n` property in your package.json to like `./l10n`. Keeps things organized (and gives you web localization support 😄 )
* Then you want to use `@vscode/l10n-dev`'s CLI to do the rest:
  * Export your strings into a bundle using the instructions here: https://github.com/microsoft/vscode-l10n/tree/main/l10n-dev#exporting-strings
  * Follow the steps to use the `generate-azure` command documented here: https://github.com/microsoft/vscode-l10n/tree/main/l10n-dev#azure-ai-translator-experimental

Quick start for creating an Azure Translator:
* See if this direct [link works](https://portal.azure.com/#view/Microsoft_Azure_ProjectOxford/CognitiveServicesHub/~/TextTranslation)
* If not, Go to the [Azure Portal](https://portal.azure.com) and Search for "Translator"
* Create a new Translator
* "Click here to manage keys" on the overview page
* The key & location on that page are the two environment variables mentioned in the `generate-azure` section of the README

**Comment by bpasero** [comment]
🆒
