### ISSUE TITLE
multi-cursor completions don't match

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#205674]
Testing #205562

When I try completions with multiple-cursors, I keep seeing that one of them is correct and the other has an extra brace or breaks balanced quotes or something else. Should they be exactly the same? Some examples...

![Image](https://github.com/microsoft/vscode/assets/323878/55ef7251-26eb-49d4-b02b-bf73f5a4b20e)

![Image](https://github.com/microsoft/vscode/assets/323878/066e439d-88dd-4292-b65b-98c8fce014af)

Cursor one

![Image](https://github.com/microsoft/vscode/assets/323878/53f3c44e-91c2-4455-8d84-241b9bbc46d0)

Cursor  two

![Image](https://github.com/microsoft/vscode/assets/323878/5d744a9c-0266-42c2-81dc-2202f5c76012)

**Comment by aiday-mar** [comment]
Hi @roblourens thank you for posting this issue. This looks indeed like a bug, I will investigate.
