### ISSUE TITLE
Settings from release notes does not show restore option

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#205676]
Testing #205565

https://github.com/microsoft/vscode/assets/964386/228a5f49-cc1a-487f-854c-3227645347b0

**Comment by alexr00** [comment]
We don't persist past reload, the "restore" state is only in memory. @deepak1556 do you think we should keep this state?

**Comment by deepak1556** [comment]
For consistency I would like it to be persisted since there are a couple more settings I know that will need a restart. But please do get more opinions on this before making the change.

**Comment by alexr00** [comment]
Leaving open and adding to the backlog to await feedback.

**Comment by alexr00** [comment]
I haven't gotten any other feedback about this. I'm going to close it, but if you feel strongly about it I'll reopen!
