### ISSUE TITLE
VSCode debug controls positioned out of editor

### ISSUE THREAD

**Issue by nikhilnxvverma1** [Microsoft/vscode#20561]
I accidentally positioned the debug controls outside the editor's bounds.Now every time I open that project, it comes like that.

![Debug controls beyond the left bounds](https://i.stack.imgur.com/AOpFt.png)
I [found the fix](http://stackoverflow.com/questions/42199245/vscode-debug-controls-positioned-out-of-editor) by deleting the "Application Support" data

- VSCode Version:1.9.1
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Go to debug mode in any program
2. Hold the handle on the left side of the debug controls and move your mouse all the way beyond the left bounds of the editor until it clips off.

**Comment by isidorn** [comment]
Sorry about that, dup of - also contains a workaround https://github.com/Microsoft/vscode/issues/20298
