### ISSUE TITLE
"{" and "}" are not detected by the screen reader.

### ISSUE THREAD

**Issue by toni0411** [microsoft/vscode#205641]
Type: <b>Bug</b>

In the editor, when righting "{" or "}", these characters are visible, but the screen reader is not detecting them, as if they are hidden. When navigating to them and getting the character code, screen reader shows code 0, as if there was nothing. This problem popped up in the recent update (or one of recent updates because I didn't code these 2 weeks).

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by meganrogge** [comment]
/duplicate [#200956](https://github.com/microsoft/vscode/issues/200956)
