### ISSUE TITLE
`Move to file` does not provide a quick fix highlight

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#205691]
Testing [#205588](https://github.com/microsoft/vscode/issues/205588)

- in a typescript file, select an identifier, invoke quick fix and use the cursor keys have the `Move to new file` selected.
- Observe that no range is highlighted

**Comment by justschen** [comment]
This is intended - since there is some additional logic needed for `Move to File` to have highlights/show relevant edits, Typescript will be handling this soon.
