### ISSUE TITLE
External terminals opened with vscode cannot be terminated by pressing ctrl+c

### ISSUE THREAD

**Issue by bestime** [microsoft/vscode#205629]
Type: <b>Bug</b>

vscode uses the shortcut keys ctrl+shift+c to open an external terminal. After a service similar to nodejs is run, the task cannot be terminated by pressing ctrl+c, and all shortcut keys become invalid. My computer is Windows 11 system.

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12500H (16 x 3110)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.26GB free)|
|Process Argv|--crash-reporter-id 1be4e1b9-e285-4206-9914-4d678f9b7426|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.7
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.15
minify|Hoo|0.4.3
vscode-language-pack-zh-hans|MS-|1.85.2024021409
vue-vscode-snippets|sdr|3.1.1
language-stylus|sys|1.16.0
volar|Vue|1.8.27
vscode-typescript-vue-plugin|Vue|1.8.27

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30962249
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
b5d27386:30958190
a89i1917:30961429
3ef8e399:30967273
bg6jg535:30958357
ccp2r3:30958157

```

</details>

**Comment by meganrogge** [comment]
once the external terminal has been opened, it's outside of VS Code's purview thus we cannot manage any `ctrl+c` that happens

**Comment by meganrogge** [comment]
/duplicate [#205417](https://github.com/microsoft/vscode/issues/205417)

**Comment by kevingjs** [comment]
+1
