### ISSUE TITLE
Update Perl6 syntax highlighting to allow for kebab-case in addition to snake_case

### ISSUE THREAD

**Issue by WildYorkies** [Microsoft/vscode#20563]
Steps to Reproduce:

1. Make a file called `test.pl6` or `test.pm6`
2. Type the following in:

```
sub print-board() # Wrong

sub thing-for-that() # Wrong
```

3. See that the words `print` and `for` are highlighted as if they are keywords.

4. Change it to snake case and notice that it is like a normal variable again:

```
sub print_board() # Correct

sub thing_for_that() # Correct
```

Solution:

Update [this file](https://github.com/Microsoft/vscode/blob/master/extensions/perl/syntaxes/Perl%206.tmLanguage) with the kebab case addition.

**Comment by aeschli** [comment]
It's a problem of https://github.com/textmate/perl.tmbundle/blob/master/Syntaxes/Perl%206.tmLanguage that we use.

**Comment by aeschli** [comment]
This issue was moved to textmate/perl.tmbundle#24
