### ISSUE TITLE
App flashing orange in task bar

### ISSUE THREAD

**Issue by 1bellb** [microsoft/vscode#205645]
Type: <b>Bug</b>

If I am running Visual Studio Code along side Visual Studio. When I build the solution in Visual Studio it triggers the jest tests in VS Code, which now causes the app to start flashing orange in the Windows taskbar.
If you focus it and unfocus it to stop the orange flashing, it starts flashing orange again once all the tests have run.

It never used to do this, it has only just started after an update.

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.4
prettier-vscode|esb|10.1.0
vscode-todo-plus|fab|4.19.1
vscode-jest-runner|fir|0.4.72
vscode-docker|ms-|1.29.0
remote-containers|ms-|0.338.1
vs-keybindings|ms-|0.2.1
vsliveshare|ms-|1.0.5905
debugger-for-chrome|msj|4.13.0
vscode-jest|Ort|6.2.1
vscode-nuget-gallery|pat|0.0.24
vscode-scss-formatter|sib|3.0.0
sass-indented|syl|1.8.29
vscode-todo-highlight|way|1.0.5

</details>

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/205766
