### ISSUE TITLE
Unable to open vs code - insiders after update

### ISSUE THREAD

**Issue by jnystrom** [Microsoft/vscode#20564]
- VSCode Version: 1.10.0-insiders
- OS Version: MAC Sierra 10.12.3

Steps to Reproduce:

1. Update to newest insiders version
2. Unable to open app.
3.  I tried to run from command line with --verbose and got this error:

<img width="1030" alt="screen shot 2017-02-13 at 3 59 29 pm" src="https://cloud.githubusercontent.com/assets/1293142/22904008/c47002e0-f208-11e6-9ecf-55e763d003f2.png">

4.  I was able to run `sudo code-insiders` and it started up fine.

**Comment by jnystrom** [comment]
`sudo` did work, now it is not, and I am getting a similar error as above:
<img width="1071" alt="screen shot 2017-02-13 at 11 14 48 pm" src="https://cloud.githubusercontent.com/assets/1293142/22915014/48c4d5fa-f242-11e6-917f-af064c7205fc.png">

**Comment by joaomoreno** [comment]
Not very good.

First, I recommend never to use `sudo code`.

Then, does it reproduce after you restart your machine?

**Comment by ayyash** [comment]
When it prompted me to update, it wouldn't update without closing all instances, I clicked Ignore, went out, it gave me access denied error for deleting a file, i clicked abort, now when I open Code I get 
![image](https://cloud.githubusercontent.com/assets/1110344/22919609/751ddbc2-f299-11e6-881a-ed1093210978.png)

Don't know what to do, should I re-install?

**Comment by joaomoreno** [comment]
@ayyash, that looks like a separate issue, it's even on Windows. Simply reinstall, in your case.

**Comment by weinand** [comment]
@joaomoreno pls see #20555 and #20587

**Comment by jnystrom** [comment]
@joaomoreno I have tried reinstalling and restarting the machine multiple times.  I understand not to use 'sudo', but I was trying to see what might be working and what was not.

**Comment by joaomoreno** [comment]
Definitely a duplicate of #20564, the same underlying issue.

**Comment by jnystrom** [comment]
YUP, works for me now!

**Comment by joaomoreno** [comment]
Thanks @jnystrom !
