### ISSUE TITLE
Inno setup - `/LANG` should also support locale codes

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#205667]
Testing #205564

I think that the `/LANG` should also support the well known locale codes (ex: `HU`, `HU_HU`) along with `hungarian`.

**Comment by benibenj** [comment]
Not actually sure many people use /lang to set the setup language. In general inno setup tries to detect the language of your PC so not sure it's worth to add the locale code, but if we would do so it would just require adding another language entry.

```
Name: "english"; MessagesFile: "compiler:Default.isl,{#RepoDir}\build\win32\i18n\messages.en.isl" {#LocalizedLanguageFile}
Name: "en"; MessagesFile: "compiler:Default.isl,{#RepoDir}\build\win32\i18n\messages.en.isl" {#LocalizedLanguageFile}
```

// cc @joaomoreno

**Comment by joaomoreno** [comment]
`/LANG` is a feature of [Inno Setup](https://jrsoftware.org/isinfo.php). We do not expose it as a VS Code feature.
