### ISSUE TITLE
Hover interrupts when typing in explorer

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#205672]
- Right click a folder in the explorer, pick "new file"
- Start typing the name of the new file
- The hover widget appears on the folder, since my cursor was left on top of it, covering what I'm typing

This shouldn't appear when I am typing/interacting with some other part of the screen

**Comment by bpasero** [comment]
Yeah I also noticed this when I had my mouse over the explorer but then opened quick open and started to type, the hover would appear over the explorer still after a while.
