### ISSUE TITLE
Git: Rename quick fix for whitespace characters

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#205686]
Testing #205559

Message:

<img width="553" alt="image" src="https://github.com/microsoft/vscode/assets/22350/f1204876-9f8a-4543-9d2d-842ecf7e9767">

Quick fix:

<img width="230" alt="image" src="https://github.com/microsoft/vscode/assets/22350/d4c21748-52d8-43f0-9dcc-fa633e7cf1b0">

Better names:

- `Clear message`
- `Clear whitespace characters`
- `Clear whitespace`

Or, maybe the diagnostic should actually warn about trailing and following whitespace and simply have a `Trim message` quick fix for that. It would also work in the case that the entire message is just whitespace characters.

**Comment by lszomoru** [comment]
The current code action has been renamed to `Clear whitespace characters`.
The work to add an input validation check for leading/trailing whitespace - https://github.com/microsoft/vscode/issues/205825

**Comment by eleanorjboyd** [comment]
any suggestion to get the code action to pop up on whitespace select? Mine just keeps saying "no code actions avaliable"
