### ISSUE TITLE
update method of WorkspaceConfiguration not working as expected

### ISSUE THREAD

**Issue by Bill-Stewart** [Microsoft/vscode#20566]
- VSCode Version: 1.9.1
- OS Version: Windows 7

I am trying to update the `editor.wrappingColumn` setting from an extension, but it does not update the `settings.json` as expected. To reproduce:

    var vscode = require("vscode");
    function activate(context) {
      context.subscriptions.push(
        vscode.commands.registerCommand("extension.testExtension", function() {
          vscode.workspace.getConfiguration().update("editor.wrappingColumn", 79);
        })
      );
    }
    exports.activate = activate;

I can use `vscode.workspace.getConfiguration().get("editor.wrappingColumn")` to retrieve the setting, but the `update` method (like above) does not update the setting in `settings.json` like I expected. The Thenable object returned from the `update` method contains no errors.

What am I missing or not understanding?

**Comment by jrieken** [comment]
It does work for me, I see `<workspace>/.vscode/settings.json` being updated. @Bill-Stewart Are you expecting to update the global value? In that case you must pass `true` as third parameter when calling update

**Comment by Bill-Stewart** [comment]
Thank you! This works:

    var config = vscode.workspace.getConfiguration("editor");
    var configName = "wrappingColumn";
    var setAsGlobal = config.inspect(configName).workspaceValue == undefined;
    config.update(configName, 79, setAsGlobal);

(i.e., set as global value when workspace value not defined, or set workspace value if defined)
