### ISSUE TITLE
Open editors DND is strange when sorting by name

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#205648]
If you configure `explorer.openEditors.sortOrder`, DND in open editors feels a bit strange, should we disable it then?

![Recording 2024-02-20 at 10 24 21](https://github.com/microsoft/vscode/assets/900690/d557bf0a-e420-44b3-b2f5-581bbc265978)

**Comment by benibenj** [comment]
Yes, reordering does not make sense in this case, will disable it then
