### ISSUE TITLE
Test: Chat Participant API

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#205609]
Refs: https://github.com/microsoft/vscode/issues/199908

- [x] anyOS @connor4312 
- [x] anyOS @joyceerhl
- [x] anyOS @TylerLeonhardt

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23205609%0A%0A&assignees=roblourens)

---

We are preparing to finalize the API that will allow extension authors to develop extensions that show as `@` participants in chat. This item is about testing the API, ensuring that you are able to understand what it does, how to use it, and that it works. The main entrypoint is here: https://github.com/microsoft/vscode/blob/b44593a612337289c079425a5b2cc7010216eef4/src/vscode-dts/vscode.proposed.chatParticipant.d.ts#L475.

You can create a simple chat extension from scratch, or clone and modify the sample extension: https://github.com/microsoft/vscode-extension-samples/tree/main/chat-agent-sample. This sample should be up to date with the latest API that will appear in tomorrow's Insiders build. If you have any issues running it, make sure Insiders is up to date, and grab the latest dts from vscode main and ensure that the sample isn't missing a last-minute change.

We have a start on an extension guide at https://github.com/microsoft/vscode-docs/pull/7041, this may be helpful as well.

You can create an LLM chat participant using the "languageModels" proposal (this proposal has its own TPI so it doesn't need in-depth testing here, of course feedback is fine if you have any) or your own LLM API, or you can create some other kind of participant that doesn't even use an LLM.

* Start by [creating an extension](https://code.visualstudio.com/api/get-started/your-first-extension) or fork an existing [extension sample](https://github.com/Microsoft/vscode-extension-samples)
 * Add the proposed API to the `package.json` (see below)
 * Then run `npx vscode-dts dev` to get the typings
```json
	"enabledApiProposals": [
		"chatParticipant",
		"languageModels"
	],
```

**Comment by hbons** [comment]
I can run `npx vscode-dts dev` on the `chat-agent-sample` project.

<img width="852" alt="image" src="https://github.com/microsoft/vscode/assets/103326/5ada89b0-8f6b-4382-af0b-51992497afa5">

But I can't seem to run it:
<img width="565" alt="image" src="https://github.com/microsoft/vscode/assets/103326/903242c1-f719-45bb-8be1-23b31b70d348">

**Comment by TylerLeonhardt** [comment]
@hbons  Try moving the dts files into the src directory

**Comment by hbons** [comment]
@TylerLeonhardt thanks, but same thing. I'm not the right person to test this. Feel free to reassign. :)

**Comment by roblourens** [comment]
The sample keeps the dts files in the src directory

**Comment by TylerLeonhardt** [comment]
I feel like I have more to test, but I'll do it incrementally throughout the week.
