### ISSUE TITLE
Settings with boolean values are not represented in the context menu

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#205679]
Testing #205565

https://github.com/microsoft/vscode/assets/964386/4c75ad48-57b9-481a-a9a4-3771c4cc7ac5

**Comment by deepak1556** [comment]
Maybe this is intended behavior, I was expecting a context menu option like `enable`, `disable` to show up depending on the values.

**Comment by alexr00** [comment]
This is intended. The value you set in your setting matches the value the user already has set, so we don't show anything besides the "view" action.

**Comment by deepak1556** [comment]
Thanks for clarifying, can confirm boolean value options are provided when current setting does not match.
