### ISSUE TITLE
Insiders 1.10.0 Marketplace returned 'ECONNREFUSED'. Please check the 'http.proxy' setting.

### ISSUE THREAD

**Issue by wulftone** [Microsoft/vscode#20567]
Getting `Marketplace returned 'ECONNREFUSED'. Please check the 'http.proxy' setting.` after most recent insiders update.  Worked on Friday when I last opened it.  Didn't change any settings.  Not using a proxy.  I'm assuming latest update broke it somehow since it started happening right after I updated this morning.

- VSCode Version: 1.10.0-insider 422d7ff1b78fcac514498921551c33a988c4ad34 2017-02-13T07:02:30.785Z
- OS Version: OSX 10.10.5 (14F2109)

Steps to Reproduce:

1. Download above vscode-insiders build
2. Restart vscode
3. Open extensions
4. See "Marketplace returned 'ECONNREFUSED'. Please check the 'http.proxy' setting."

Need any more info?

**Comment by johnpapa** [comment]
Same here.

**Comment by joaomoreno** [comment]
What the...

**Comment by joaomoreno** [comment]
Does not reproduce in Stable or Dev.

**Comment by Nexi89** [comment]
I have the same error with vscode-insiders. 

<img width="1212" alt="bildschirmfoto 2017-02-14 um 10 00 13" src="https://cloud.githubusercontent.com/assets/11149444/22922076/7d821fc8-f29c-11e6-835e-2391a7bb181f.png">

**Comment by joaomoreno** [comment]
Repros in 422d7ff1b78fcac514498921551c33a988c4ad34 and 596579866efef0d55234cf094a8cd182f7ddda99. Only insiders.

Does **not repro** in ef3a8c9e2b642613635c1c53f70bcc86e123ad9a.

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/22922636/e532c7c4-f29e-11e6-918c-ccce7717641a.png)

**Comment by joaomoreno** [comment]
cc @jrieken The socket names were cropped somehow... too long?

**Comment by johnpapa** [comment]
new insiders build today seems fine. thanks!

**Comment by joaomoreno** [comment]
Thanks for letting me know @johnpapa

**Comment by joaomoreno** [comment]
@jrieken The fix was to come up with shorter socket names 1d17b45

**Comment by jrieken** [comment]
that is crazy. thanks for fixing this

**Comment by nbara** [comment]
Anyone else having this bug on OSX with the 1.13.0 update ?
