### ISSUE TITLE
CSS overflow-wrap: anywhere (doesn't suggest "anywhere")

### ISSUE THREAD

**Issue by levelost** [microsoft/vscode#205642]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.86.2
- OS Version: Windows 10 22H2

Steps to Reproduce:

1. Create CSS-file.
2. Create class with overflow-wrap:.
3. IDE doesn't suggest anywhere value.

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode-custom-data/pull/88

**Comment by Bashara22** [comment]
> Fixed by https://github.com/microsoft/vscode-custom-data/pull/88
