### ISSUE TITLE
Aggressive caching with Open Current File as Release Notes

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#205675]
Testing #205565

* Add a codesetting block
* Run "Developer: Open Current File as Release Notes"
* Make changes to the codesetting block
* Run "Developer: Open Current File as Release Notes" and old value still shows up

*Workaround:* Switching profiles to force new user data.

**Comment by justschen** [comment]
+1 on this

Any change is not reflected when I hit `Open Current File as Relase Notes`. Reloading vs code also fixes.
