### ISSUE TITLE
The handleUri of UriHandler doesn't fired when debugging extension 

### ISSUE THREAD

**Issue by Haigui-ckh** [microsoft/vscode#205652]
Type: <b>Bug</b>

my opration:
1. debugging the project: **vscode-extension-example-main** ---> **uri-handler-sample**.
2. start a browser and visit path '**vscode://vscode-samples.uri-handler-sample**', click to open vscode.
3. latest activated vscode window was activated.
4. handleUri of UriHandler not fired.

besides，
1. I have try in vscode and vscode insider, both not works.
2. tried versions : 1.83, 1.74
3. debug scene.
4. found issue #140468 . same question.

VS Code version: Code - Insiders 1.85.0-insider (Universal) (98417b150aeb47dd81dc58893789da4b4cb0e095, 2023-11-01T18:37:54.253Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 3a16c669-d41f-447b-9e29-4a487115d0c8|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vsc_aa:30263845
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:30784851
c4g48928:30535728
vscrp:30624060
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
pydisww1:30959800
cppperfcontrol:30963551
8082a590:30961435
7j2b6412:30951517
bg6jg535:30946824
8f97e687:30959763
ccp2r6:30958154

```

</details>

**Comment by connor4312** [comment]
Please see https://github.com/microsoft/vscode/issues/140468#issuecomment-1016829565
