### ISSUE TITLE
debugger failed to run

### ISSUE THREAD

**Issue by Yvonne-Young** [microsoft/vscode#205725]
Type: <b>Bug</b>

debugger failed to run reporting an "The following argument was not expected: /c Run with -- help for more information" error. 

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.67GB (44.59GB free)|
|Process Argv|C:\\Platform\\MtDev --crash-reporter-id d39f5400-dc76-4bdf-a0d1-090f7749c3a7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
scope-bar|amo|0.2.1
blamer-vs|bea|0.5.2
gisdk|Cal|0.2.22
doxdocgen|csc|1.4.0
prettier-vscode|esb|10.1.0
tortoise-svn|fan|0.1.1
vscode-drawio|hed|1.6.6
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
vscode-dotnet-runtime|ms-|2.0.1
remote-containers|ms-|0.338.1
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
cmake-tools|ms-|1.17.15
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.13
remote-explorer|ms-|0.4.1
vsliveshare|ms-|1.0.5905
java|red|1.28.1
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.56.1
vscode-java-dependency|vsc|0.23.4
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0
volar|Vue|1.8.27
material-theme|zhu|3.16.2

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
7j2b6412:30967274
ccp2r3:30958157

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/204039
