### ISSUE TITLE
`createChatParticipant` API choices: The setting properties after creation & create instead of register

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#205730]
Testing #205609

I find it odd that after I create a Chat Participant, I have then remember to also set some very crucial properties on the object that is returned like description and whatnot.

I would rather this be done in the creation of the chat participant so I don't forget:

```ts
createChatParticipant('name', handler, options)
// or
createChatParticipant('name', options, handler)
```

It looks like we do the first in several places:
* https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.d.ts#L10986
* https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.d.ts#L11025

If we did something like this instead, then we wouldn't need this function to be called `createChatParticipant` and it could just be `registerChatParticipant` and return a disposable instead like the many `registerSomething` functions we have already.

Combining with https://github.com/microsoft/vscode/issues/205727 if we did follow the Provider model, these properties would be returned in the object that is returned from the Provider.

**Comment by roblourens** [comment]
I think in those cases, you can't change the options after registering your provider though

**Comment by TylerLeonhardt** [comment]
I guess it feels kinda fragmented. Some things I put in the creation, others I don't. `window.createQuickPick()` doesn't have any parameters so it's expected you're gonna do something to the properties after. What if the handler is added after the creation rather than passed in to the create? Thus making `name` the only required property (since it's needed for registration).

Aligning more like quick pick, could the requestHandler, the followupsHandler, the commandsHandler all be events instead?

**Comment by jrieken** [comment]
Today the `create`-call requires the absolute minimum of properties to be set (name and handler). The name isn't mutable the handler is. I understand the desire for more options but you'll usually end-up in a situation in which you do need to call a setter after creation. So, the create-function must be understood as guiding convenience and not as sugar. We aren't perfectly consistent here but this generally aligns with createNotebookController, createTestController, or createSourceControl
