### ISSUE TITLE
Chat agents say "Github copilot used..." even though my agent doesn't use copilot

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#205792]
Testing #205609

I made my custom chat extension, but in the chat view it says "Github copilot used @[name]", even though my extension doesn't touch copilot at all. I would expect it to only show my own extension.

**Comment by roblourens** [comment]
Yeah, since the "default participant" is sort of the wrapper around the chat experience, it gets described this way, even when not "technically" accurate
