### ISSUE TITLE
Chat response button flickers in/out of existence during progressive rendering

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#205757]
Testing #205609

I have an agent that streams text and adds a button at the very end of the response. I've sometimes seen the button appear and quickly disappear from the rendered response before the text is fully progressively rendered. This only seems to happen sometimes though. Code https://github.com/joyceerhl/vscode-gptheme

**Comment by roblourens** [comment]
Fixed in https://github.com/microsoft/vscode/pull/216897
