### ISSUE TITLE
Constant popups to authenticate HTTP(S) access to the remote repository

### ISSUE THREAD

**Issue by claell** [microsoft/vscode#205707]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.2
- OS Version: Windows 11

Coming from https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/issues/1083. I suspected that extension to cause the problem, but apparently, it is caused by the git extension.

Steps to Reproduce:

* Have a clean Windows installation.
* Install VS Code
* Install the GitLab extension (probably not needed, as the issue still occurs after uninstalling that extension)
* Install git for Windows (select VS Code as git's default editor; might not be relevant)
* Clone one or two private projects from `gitlab.com` with git submodules in them (not sure whether the submodules are relevant) - I just used the "Open in your IDE" option "Visual Studio Code (HTTPS)" on the GitLab project website.
* Initialize the submodules with `git submodule update --init --recursive` (not sure if relevant)
* At some point authenticate with GitLab through the Git Credentials Manager popup window (select "Sign in with your browser")
* Wait a bit, play around with revoking the application access at https://gitlab.com/-/user_settings/applications. Possibly also reauthenticate from other machines. Close and reopen the VS Code projects on the clean installation machine.

**Comment by lszomoru** [comment]
@claell, sorry for not getting back to you on this until now. Reading through the steps it seems that you have Git Credential Manager installed and configured to handle the auth requests. If that is the case, this seems to be an issue with a misconfigured Git Credential Manager as VS Code would only handle authentication requests if no credential managers are configured.

**Comment by claell** [comment]
@lszomoru thanks for your reply.

Yes, I have Git Credential Manager installed. Not sure what could be wrong with that configuration; I just used the default one. But might be a bug on their side. If you believe that this is unrelated to VS Code, I'll create a bug report for them.

**Comment by claell** [comment]
Created https://github.com/git-ecosystem/git-credential-manager/issues/1555 as follow-up there, now.

**Comment by lszomoru** [comment]
Thank you! I will go ahead and close this issue.
