### ISSUE TITLE
Should references be deduped?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#205767]
Testing #205609

![Image](https://github.com/microsoft/vscode/assets/2644648/5c62c4dc-86b5-4b7b-a3d9-95aaa71c1626)

I was lazy and added the same url multiple times thinking it didn't matter and it would ignore dupes. Turns out I was wrong. Any reason for not deduping?

**Comment by roblourens** [comment]
I'd rather the API just be sort of dumb here and show whatever comes through the stream. Can revisit if it's a big problem.
