### ISSUE TITLE
Walkthrough will not open if the marketplace is opened

### ISSUE THREAD

**Issue by caleb-at-pieces** [microsoft/vscode#205718]
Does this issue occur when all extensions are disabled?: n/a

- VS Code Version: 1.86.2
- OS Version: MacOS Ventura 13.4.1 (c) 

Steps to Reproduce:

1. open an in app listing in the vscode marketplace i.e `vscode:extension/meshintelligenttechnologiesinc.pieces-vscode`
2. open the command palette `command + shift + p` or `ctrl + shift + p`
3. type 'open walkthrough' and select `Welcome: Open Walkthrough`
4. select a walkthrough to open
5. you will get sent to the welcome page, but the walkthrough will not open

**Comment by caleb-at-pieces** [comment]
@bhavyaus any update on this? This is critical functionality for my extension's onboarding (and likely many others).

**Comment by bhavyaus** [comment]
@caleb-at-pieces I am unable to repro this issue (see recording below). Can you try on a new insiders build?

![Image](https://github.com/microsoft/vscode/assets/25044782/4f383e81-1e20-4083-a632-27482ce5f730)

**Comment by caleb-at-pieces** [comment]
> @caleb-at-pieces I am unable to repro this issue (see recording below). Can you try on a new insiders build?
> 
> ![Image](https://private-user-images.githubusercontent.com/25044782/307154993-4f383e81-1e20-4083-a632-27482ce5f730.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MDEwMzcsIm5iZiI6MTcwODcwMDczNywicGF0aCI6Ii8yNTA0NDc4Mi8zMDcxNTQ5OTMtNGYzODNlODEtMWUyMC00MDgzLWE2MzItMjc0ODJjZTVmNzMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDE1MDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MzczZGU5ZmI4NjUxMGYwZWVjMjgzMDA0NTdiNzdlMzhiZjk4Mjc1MTk4ZWJjZGQxYzA3OTc3NDU3YzdhN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TWhLN7YdXnyG0DgCGCBXRsdYA95SdiSMfA_djrP90uY) [ ![Image](https://private-user-images.githubusercontent.com/25044782/307154993-4f383e81-1e20-4083-a632-27482ce5f730.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MDEwMzcsIm5iZiI6MTcwODcwMDczNywicGF0aCI6Ii8yNTA0NDc4Mi8zMDcxNTQ5OTMtNGYzODNlODEtMWUyMC00MDgzLWE2MzItMjc0ODJjZTVmNzMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDE1MDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MzczZGU5ZmI4NjUxMGYwZWVjMjgzMDA0NTdiNzdlMzhiZjk4Mjc1MTk4ZWJjZGQxYzA3OTc3NDU3YzdhN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TWhLN7YdXnyG0DgCGCBXRsdYA95SdiSMfA_djrP90uY) ](https://private-user-images.githubusercontent.com/25044782/307154993-4f383e81-1e20-4083-a632-27482ce5f730.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MDEwMzcsIm5iZiI6MTcwODcwMDczNywicGF0aCI6Ii8yNTA0NDc4Mi8zMDcxNTQ5OTMtNGYzODNlODEtMWUyMC00MDgzLWE2MzItMjc0ODJjZTVmNzMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDE1MDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MzczZGU5ZmI4NjUxMGYwZWVjMjgzMDA0NTdiNzdlMzhiZjk4Mjc1MTk4ZWJjZGQxYzA3OTc3NDU3YzdhN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TWhLN7YdXnyG0DgCGCBXRsdYA95SdiSMfA_djrP90uY) [ ](https://private-user-images.githubusercontent.com/25044782/307154993-4f383e81-1e20-4083-a632-27482ce5f730.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MDEwMzcsIm5iZiI6MTcwODcwMDczNywicGF0aCI6Ii8yNTA0NDc4Mi8zMDcxNTQ5OTMtNGYzODNlODEtMWUyMC00MDgzLWE2MzItMjc0ODJjZTVmNzMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDE1MDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MzczZGU5ZmI4NjUxMGYwZWVjMjgzMDA0NTdiNzdlMzhiZjk4Mjc1MTk4ZWJjZGQxYzA3OTc3NDU3YzdhN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TWhLN7YdXnyG0DgCGCBXRsdYA95SdiSMfA_djrP90uY)

Just downloaded the latest insiders and it looks like this functionality is working on it.

**Comment by bhavyaus** [comment]
This should be fixed the next release of VS Code.
