### ISSUE TITLE
Dictating into editor does not recognize programming language specific keywords

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#205784]
Testing #205521

In its current state, this appears to be great for regular text editing. If the idea is that you can also write code, then it does not do a good job of recognizing language specific keywords.

![Image](https://github.com/microsoft/vscode/assets/25044782/5b2faaf0-9b61-4f5f-bb5c-3b8cb4e856d8)

**Comment by bpasero** [comment]
Thanks, yes, this is only meant to be for languages, not programming languages, at least for now.

**Comment by s-h-a-d-o-w** [comment]
@bpasero If that's the case, why does it say "We have transferred all the learning and feedback from this technical preview to [VS Code Speech](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-speech) extension , which is generally available for download today." here? https://githubnext.com/projects/copilot-voice/

This was clearly about being able to dictate code and based on that statement there, those features were merged into VS Code Speech after the technical preview was concluded?

**Comment by bpasero** [comment]
Feature requests are always welcome.

**Comment by s-h-a-d-o-w** [comment]
But I'm just looking for what's supposed to already be there. Are you saying that this feature was simply killed?

**Comment by s-h-a-d-o-w** [comment]
I mean... presumably, Microsoft already invested hundreds of thousands dollars into GitHub voice. If it has been discontinued, it doesn't bode well for a request for bringing it back.
