### ISSUE TITLE
I wish I could nicely have a Class that implements all these handlers/providers

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#205795]
Testing #205609

Creating the Chat:
```
const participant = chat.createChatParticipant(name, ( ...) => {
    // ...
});
participant.commandProvider = (...) => {
    // ...
};
participant.followupProvider = (...) => {
   // ...
};
```

I wish that this was just:
```ts
class MyChatParticipant implements vscode.ChatParticipant {
    requestHandler(...) {
        // ...
    }

    commandProvider(...) {
        // ...
    }

    followupProvider(...) {
        // ...
    }
}
```
and then I pass this into `chat.createChatParticipant(name, participant);`

(commandProvider & followupProvider being optional)

**Comment by roblourens** [comment]
Same discussion as https://github.com/microsoft/vscode/issues/205730 and https://github.com/microsoft/vscode/issues/205727 IMO, vscode owns the object that is created
