### ISSUE TITLE
[themes] Selection highlight color is too similar to the selection color on Monokai

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#20577]
- VSCode Version: 1.9.1
- OS Version: Windows 10 x64

Hi, when i focus text and doubleclick to text, all same text has background, i can't distinguish between focus and doubleclick text, anyone help to disable it, check image
![VSCode](http://i.imgur.com/4QxveiA.gif)
I want to like Sublime text, like this:
![Sublime text](http://i.imgur.com/OEiXJjY.gif)

**Comment by dysol** [comment]
+1 This UX is pretty annoying as it is difficult to distinguish between what is "suggested" and what is "selected"

**Comment by xttn** [comment]
+1

**Comment by alexandrudima** [comment]
This can all be controlled by the theme. @ghost  what theme are you using ?

**Comment by xttn** [comment]
same here, i have this problem on all themes, test with Monokai theme
![Check it](http://i.imgur.com/PIsYBSM.gif)

**Comment by alexandrudima** [comment]
@aeschli giving to you for now. Unsure who among us owns Monokai

**Comment by alexandrudima** [comment]
Sometimes the bot is too aggressive.
