### ISSUE TITLE
github.dev is inconsistent to and worse than vscode.dev

### ISSUE THREAD

**Issue by Malix-off** [microsoft/vscode#205747]
https://github.dev is inconsistent and worse than https://vscode.dev

Notably,
- Worse tested performance and integration compared to https://vscode.dev
- Authenticating with Remote - Tunnels is broken (See https://github.com/microsoft/vscode/issues/204914#issuecomment-1954931556)
- No PWA Title Bar (which is available on https://vscode.dev)
	1. Opened PWA Title Bar (on https://vscode.dev)
	  ![image](https://github.com/microsoft/vscode/assets/76160668/fc7068e9-aff7-42a8-a0f0-911cf4b8308d)
	3. Closed PWA Title Bar (on https://vscode.dev)
	  ![image](https://github.com/microsoft/vscode/assets/76160668/23053c39-0295-42c1-a94b-2c4c950440d6)

- What is https://github.dev supposed to bring compared to https://vscode.dev?
- Is there even a way to reopen the workspace from https://github.dev to https://vscode.dev (as a remote repository)?
- Wouldn't it be better that clicking on `.` (or changing `.com` to `.dev`) in a https://github.com repository simply open a remote repository in https://vscode.dev instead of having two different domain, codebases (apparently, see my first link), and PWA manifests to maintain?
	- If you won't consider it, how to make that redirect automatically from our side?

Does this issue occur when all extensions are disabled?: Yes

**Comment by lszomoru** [comment]
@joaomoreno, could you please help with routing this to the correct owner(s). Thanks!

**Comment by joaomoreno** [comment]
This is the right place for feedback: https://github.com/community/community/discussions/categories/codespaces

**Comment by Malix-off** [comment]
@joaomoreno this "feedback" contain a bug report

> - Authenticating with Remote - Tunnels is broken (See Remote Tunnel - ChromeOS's Penguin: Can't Install Extension on Remote Host #204914 (comment))

**Comment by Malix-off** [comment]
#109611
