### ISSUE TITLE
Voice: detect missing permissions for microphone use

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#205721]
Testing https://github.com/microsoft/vscode-copilot/issues/4203

Repro:

1. On macOS
2. Open chat via cmd+i, macOS mic access popup shows (this was unexpected as I just pressed cmd+i, not held)
3. Click deny access, 🐛 blue pulse animation shows and doesn't stop

<img width="367" alt="Screenshot 2024-02-20 at 09 08 58" src="https://github.com/microsoft/vscode/assets/2193314/ea00037f-5c4a-4db4-b74b-36691e672f49">

Clicking the mic continues to toggle the state but doesn't actually do any recording. Ideally we would see access is restricted and direct the user to the macOS mic permissions.

**Comment by bpasero** [comment]
Related: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2238

**Comment by bpasero** [comment]
I was really hoping that we can detect this using web APIs and I have tried the following (needs [1] for permissions):

```ts
navigator.permissions.query(
	{ name: 'microphone' } as any
).then(function(permissionStatus){
	console.log(permissionStatus.state); // granted, denied, prompt
})
```

But this always returns `denied`. I was then hoping this would do it:

```ts
navigator.mediaDevices.getUserMedia({ audio: true }).then((stream) => {
	/* permissions */
}).catch((error) => { /* no permissions */ });
```

But I always seem to be getting a stream even when permissions are not granted.

If someone has more ideas, opening for help wanted.

[1] https://github.com/microsoft/vscode/commit/707bffbdae207740940e86a11b8178978515f9d0#diff-ce90ef6ffd304cc541efa8135dc4878c7b61889d2b2d5ef69e196af6cea7647b

**Comment by Tyriar** [comment]
@bpasero I'm guessing you would need some mac native code to check the OS-level permissions for the app, the `query` API giving denied all the time seems correct here as the app is unable to use the mic completely.

**Comment by bpasero** [comment]
@Tyriar I think the `navigator.permissions` API should return `granted` when I did grant permissions, but I also see that not all permissions can be queried like that, so its possible that `microphone` is not one of them.

I would like to avoid having to write native code for this and ideally find a web solution that works on all platforms. I am sure other apps must have this issue too?

**Comment by Tyriar** [comment]
Deepak or Matt would know more about using `permissions`, my experience with it is fairly limited to mainly just clipboard access.

**Comment by bpasero** [comment]
At least https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query indicates a lot more than just clipboard.
