### ISSUE TITLE
在过去5分钟内，TypeScript语言服务意外中止了5次

### ISSUE THREAD

**Issue by sundyli** [Microsoft/vscode#20573]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cocos-creator|Chukong Technologies|0.0.1|
|cocos-debug|Chukong Technology|0.0.1|

---

Steps to Reproduce:

1.不停的提示“在过去5分钟内，TypeScript语言服务意外中止了5次”；
2.

**Comment by mjbvz** [comment]
Two probable causes:

1. You are opening a mapped network drive. This will crash TypeScript 2.1.6. We are tracking a fix here: https://github.com/Microsoft/TypeScript/issues/13997
1. If you see a message about a missing `typescript/...` file, you may be seeing #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

If neither seems to fit for what you are hitting, please let me know
