### ISSUE TITLE
Language model access notification could  be improved 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#205798]
Testing #205568

<img width="253" alt="Screenshot 2024-02-20 at 5 26 30 PM" src="https://github.com/microsoft/vscode/assets/12821956/c52cd82d-2ba7-4971-9eaa-700f60ea7925">

Some suggestions for the notification:

- The primary title should be about accessing the language model instead of signing in to github
- A quick summary of why this is relevant to the user
- Maybe make it more clear that the justification is provided by the extension and not VS Code
- Provide a link with more details about the risks of granting access and how to manage access 

Maybe something like:

---

# The extension 'My fancy ext' would like to use the language models provided by GitHub Copilot Chat

This will allow the extension to make chat requests. Justification provided by 'My fancy ext':

`<justification>`

[Learn more](http://example.com)

**Comment by TylerLeonhardt** [comment]
I believe we improved this a while back.
