### ISSUE TITLE
testing open release notes: code block cannot be changed

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#205785]
Testing #205565

1. I have the following:
```html
 <code codesetting="editor.codeActionWidget.includeNearbyQuickFixes">asdfasdfasfdasdfsa</code>
```
2. Hit `Open Current File as Release Notes...`
3. I get back
![Screenshot 2024-02-20 at 3 27 23 PM](https://github.com/microsoft/vscode/assets/54879025/600fa36c-b116-4dee-abd4-de2c05280fc9)

is the label/code block based displayed based on `codesetting`? I expected it to change.

**Comment by alexr00** [comment]
This is intentional. It forces our release notes to be consistent.
