### ISSUE TITLE
`lm.languageModels` isn't very useful

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#205797]
Testing #205609

Today, `lm.languageModels` is an array of strings. I'm currently using `lm.languageModels` as a fallback:

```
let access;
try {
    access = lm.requestLanguageModelAccess(GPT_35);
} catch (e) {
    access = lm.requestLanguageModelAccess(lm.languageModels[0]);
}
```
> I suppose I could check for the first one that starts with `copilot-`

I wish that I could look at `lm.languageModels` and get any language model that the Copilot Chat extension contributes (in other words, this `lm.languageModels` contains the contributing extension).

This aligns with the user's expectation as well of "I just granted auth for all models of Copilot Chat", an extension auth should be able to get a good fallback model by querying `lm.languageModels` for a model that is good enough in the absence of the one they know works well enough.

**Comment by jrieken** [comment]
> I wish that I could look at lm.languageModels and get any language model that the Copilot Chat extension contributes (in other words, this lm.languageModels contains the contributing extension).

I disagree that you'll be successful with that strategy because we seen varying results and prompting requirements for different models. You can still do it using id that are published by copilot but I am not a fan of backing extensions identifier into the API. From the past we know that they are not stable either. 

The expected use case for `languageModels` is that you know what you need and just check the existence of the language model with the array

**Comment by TylerLeonhardt** [comment]
I understand, but I don't want stale broken extensions in the marketplace.

Extension authors will:
* see the finalization announcement
* "oh that's cool let me make an extension that does X with AI"
* "what models are available? Ok I'll use GPT3.5-turbo"
* ship it on the marketplace

The extension authors are not warned that their extension has a shelf life or even how long that shelf life will be.

The only indication is:
* if the extension author makes a line between the JSDoc: `when the requested language model is not available` and "program defensively if the model you asked doesn't exist anymore"
* if the extension author has the future-sight to know that the model they used will disappear

I would rather have a working extension that isn't fine-tuned to a specific model, then a completely broken extension that users will be disappointed in when they install it.

If you are very against helping the extension author out in code, at the very least please call it out in JSDoc so we set the precedent that the extension should handle a future where what they're asking for doesn't exist anymore. "when the requested language model is not available" IMO is too passive.

**Comment by jrieken** [comment]
We will not go for a composite language model identifier, the docs have been updated, explicit error type have been added, and the overall flow has been simplified
