### ISSUE TITLE
select indent using spaces gives confusing menu

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#205743]
Testing #205740

1. click into tab size in status bar
2. select indent using spaces
3. 🐛 "select tab size for current file" which doesn't really make sense given I selected "spaces" and it is asking me about tabs. If this question is about the tabs to space conversion this could be a little bit more clear like "select spaces per tab"

**Comment by Yoyokrazy** [comment]
Closing this as it's mirroring the text and design from the editor indentation entry. Will defer to that design, and follow changes if any arise there
