### ISSUE TITLE
Auto inserted settings have validation warnings

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#205736]
Testing #205384

1. Enable all announcements
2. Enable all audio cues
3. :bug: auto-inserted settings get validation warnings:

    ```json
    "accessibility.signals.chatResponseReceived": {
        "sound": "on",
        "announcement": "off"
    },
    ```

**Comment by meganrogge** [comment]
![Image](https://github.com/microsoft/vscode/assets/29464607/a1865d3e-4ff7-405d-8b0f-1f8e5b0b9b84)
