### ISSUE TITLE
Code view scrolls when code lens is dismissed

### ISSUE THREAD

**Issue by nicot** [Microsoft/vscode#20578]
- VSCode Version: 1.9.1
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. Enable a code lens
2. Scroll down to a position where there is a code lens above the rendered lines
3. Disable the code lens

Result:
The code scrolls up a couple lines.

Expected:
Center line should stay centered.

I'm not sure this ever happens in VSCode proper, but embedding it on sourcegraph.com exhibits the issue. If you go here: https://sourcegraph.com/github.com/gorilla/mux/-/blob/mux.go#L52:74 and click the Show authors button a couple times it exhibited the issue before b86e32169ef2523826486cb7cf915d9cf9117cf1 was applied. That patch might be a starting point, but it probably needs additional checks.

**Comment by alexandrudima** [comment]
Reproducible when toggling `editor.codeLens` from `true` to `false`.

![20578](https://cloud.githubusercontent.com/assets/5047891/25437152/c13095c0-2a95-11e7-9882-dcc46a1802a3.gif)
