### ISSUE TITLE
Unsure how the override actually works

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#205759]
Testing #205740

I have a Jupyter notebook where for the purposes of testing, one cell is space-indented by four spaces, and another cell is space-indented by five spaces. Even with those options set, I am able to set the notebook indentation to be tab-indented with seven spaces per tab. I'm unsure what the setting does, because even after creating a new cell and writing a Python for loop, I notice the loop body is indented by five spaces instead of a single seven-space tab.

![Indicator shows tab with seven spaces per tab but cells are indented by four or five spaces](https://github.com/microsoft/vscode/assets/7199958/3a5c017e-24f2-4e1a-81c7-1b01fc0186e8)

I can also purposely throw off the convertor by changing the setting to indent by five spaces even though the block is indented by four spaces, and then selecting the option to convert the spaces to tabs. In that case, only some of the indentation is converted over. I don't see a user purposely getting into this scenario outside of testing the feature, but I'm thinking they could accidentally reach that state.

![A single line has only some of its spaces converted to tabs after misconfiguring the spacing](https://github.com/microsoft/vscode/assets/7199958/db8343ac-1fc3-4306-ae9e-37a1a0fa932f)

**Comment by Yoyokrazy** [comment]
Closing as most of this is expected (albeit slightly sub-optimal) behavior. The first point you made is a good bug on cell editor overrides not being respected. Keeping that issue as it's a bit more concise/focused.
