### ISSUE TITLE
Issue reporter doesn't do anything on invalid URI

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#205731]
Testing #205587

I had the arg
```
uri: vscode.Uri.parse('https://github.com/microsoft/sdfgsdfgsdfgsdfg')
```

For `workbench.action.openIssueReporter` and clicking "Create on GitHub" did nothing. I would expect an error to log in the console for this so that devs know what has happened.

**Comment by justschen** [comment]
Did this log anything in the console? (ie, `illegal value in URI` or something like that)

**Comment by andreamah** [comment]
I didn't see anything in the debug console.

**Comment by andreamah** [comment]
Technically, it's a valid URI, but it doesn't resolve to a correct endpoint.
