### ISSUE TITLE
Extra context menu when viewing a setting

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#205742]
Testing #205565

- Click on a setting link in the release notes
- Get a tooltip "View '<title>' in Settings" context menu

It seems strange to open a context menu on left-click and to open one with only a single menu item. Can we skip doing this if "View" is the only action?

**Comment by alexr00** [comment]
My preference would be to keep it consistent so that a context menu always opens when the button is clicked. There was some discussion of adding a "copy setting id" item in there too, which would fix the only-one-item issue.

**Comment by alexr00** [comment]
Will be fixed by https://github.com/microsoft/vscode/pull/205852, which adds a "copy" action to the menu.

**Comment by connor4312** [comment]
Another option is to open the context menu when the "gear" icon is hit, but go directly to the setting if the text is clicked (or vise versa)
