### ISSUE TITLE
Handle conflicts between agent names

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#205776]
Testing #205609

For my little experiment I'm making a Home Assistant chat agent, which I would address as `@home`, but I could imagine people who write similar assistants for Google Home, Apple Homekit, etc. would probably also use that alias. (For this practical use case, it's also common for people to use multiple smart home clouds to some extent and coordinate them with Home Assistant.) So the next obvious step was making the name configurable, but that would conflict with the obvious implementation of having a static contribution point that identifies agents by their `name`, once better activation is supported (https://github.com/microsoft/vscode/issues/205631).

Maybe VS Code should support aliases and allow them to be mapped per-extension including in activation -- so I could alias `hass`, `ghome`, `homekit` and have them all work.

**Comment by roblourens** [comment]
That's a possibility, we also would be able to support participants with the same name from multiple extensions. The API is in place to differentiate them, although it's not really implemented, and in theory we can support different invocations of the same `@` from the chat input, similar to how `#file` works, as long as you pick the participant from the suggest widget. I think it's undecided how we want to do it though

**Comment by connor4312** [comment]
> The API is in place to differentiate them, although it's not really implemented

I considered that as well, but with activation events that might get tricky

**Comment by roblourens** [comment]
This was implemented elsewhere
