### ISSUE TITLE
Test: Tabs vs Spaces in notebooks

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#205740]
Refs: #108675 

- [x] anyOS @eleanorjboyd 
- [x] anyOS @rzhao271
Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23205740%0A%0A&assignees=Yoyokrazy)

--- 
## Summary:

Notebooks now allow you to choose indentation settings that override the standard editor indentation. These settings will be stored within `"notebook.editorOptionsCustomizations"`

## Steps to Test:
- Run the command to render whitespace, it will make testing this far easier
- Open a notebook
- Check to make sure that the status bar entry in the lower left displays the notebook's indentation
- Click on the entry and experiment with the various available commands
  - **_Note_**: The commands in the `convert file` lower section of the quickpick are the only ones that will convert the visible indentation within your notebook cells
  - The top three commands in the `change view` section of the quickpick should all alter the settings within the override listed above, however only will change the visible indentation if you are using tabs and change the display size for example. Compare and contrast to the editor indentation behavior to ensure that there is nothing quirky going on.
  - The bottom two commands in the `convert file` should convert the indentation within your notebook in EACH cell, not just the current one, as well as changing the setting for insertSpaces from true to false or vice versa

--- 
## Known Issues:
- Changing the indentation will update the settings, and will let you indent correctly according to that choice, but there is a delay in updating the status bar entry. Clicking out of the cell or hitting escape should update the entry as the focus changed. Fix incoming. 
#205739

--- 
Thanks so much for testing!

**Comment by eleanorjboyd** [comment]
Given known issue I was also running into the problem where this wasn't true "Clicking out of the cell or hitting escape should update the entry as the focus changed. Fix incoming.".

For me instead I have to press escape or click out of the cell somewhere in the notebook, clicking to the terminal did not help.

**Comment by eleanorjboyd** [comment]
for the change view section, should I expect updates to my settings? Just a bit confused on when I should see settings.json changes or references to "notebook.editorOptionsCustomizations".

Thanks!
