### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by a313008430** [Microsoft/vscode#20572]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-css-formatter|aeschli|0.0.2|
|one-monokai|azemoh|0.2.4|
|theme-onedark|azemoh|0.4.3|
|theme-desertex|casualjim|0.0.5|
|npm-intellisense|christian-kohler|1.2.1|
|path-intellisense|christian-kohler|1.2.0|
|cocos-creator|Chukong Technologies|0.0.1|
|cocos-debug|Chukong Technology|0.0.1|
|jquerysnippets|donjayamanne|0.0.1|
|theme-dracula|dracula-theme|1.2.5|
|vscode-html-css|ecmel|0.0.33|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|auto-rename-tag|formulahendry|0.0.11|
|beautify|HookyQR|0.7.5|
|prettify-json|mohsen1|0.0.3|
|material-icon-theme|PKief|1.3.2|
|vscode-icons|robertohuertasm|7.2.0|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Closing as not actionable

**Comment by a313008430** [comment]
I don't know how to solve, I had deleted the original, reinstall, now there is no problem!
