### ISSUE TITLE
when settings object absent no change made on configure view for tabs/spaces

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#205754]
Testing #205740

1. create new workspace, create settings.json file
2. open notebook
3. click on the status bar where it says tabs/spaces
4. click on "indent using spaces"
5. 🐛 no changes are made to settings.json (does work when  "notebook.editorOptionsCustomizations" setting exists)

Im not sure what happens if you have no settings.json file in general, might be worth testing this scenario too

**Comment by Yoyokrazy** [comment]
Discussed this and looked like a confusion on workspace vs user settings files. Things are updating as intended 👍
