### ISSUE TITLE
bug: CompletionItem No way to search for matches

### ISSUE THREAD

**Issue by Simon-He95** [microsoft/vscode#205705]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

When I want to provide type after implementing spaces in `registerCompletionItemProvider`, `editor.action.triggerSuggest` is bound to the `CompletionItem` of type. Because `registerCompletionItemProvider` requires `triggerCharacter`, I use `SnippetString`, `${1: }` in `CompletionItem`, so there is a dummy space and then I can trigger my `registerCompletionItemProvider` again, but when I enter the match option there is no way to match

![屏幕录制2024-02-20 23 50 23](https://github.com/microsoft/vscode/assets/57086651/c26f6069-182b-45fa-8fd9-ceb0ebb45665)

**Comment by jrieken** [comment]
I am sorry but I have trouble understanding this issue. Can you please reformulate. Is this about triggering suggest after suggest?

**Comment by Simon-He95** [comment]
> I am sorry but I have trouble understanding this issue. Can you please reformulate. Is this about triggering suggest after suggest?

thank you for your reply，我找到解决的办法了，``${key}="\${1:  }"`, use tab to replace space，It is possible to search this way
![屏幕录制2024-02-21 09 54 01](https://github.com/microsoft/vscode/assets/57086651/f16260bd-6e4f-49e6-ac38-7d9fa8e16c74)
