### ISSUE TITLE
built in solarized themes: italic comments

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#20574]
- VSCode Version: Code - Insiders 1.10.0-insider (422d7ff1b78fcac514498921551c33a988c4ad34, 2017-02-13T07:10:28.312Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.2|
|githistory|donjayamanne|0.1.5|
|git-project-manager|felipecaputo|1.0.1|
|live-html-previewer|hdg|0.0.1|
|vscodeilviewer|josephwoodward|0.0.1|
|mssql|ms-mssql|0.2.1|
|csharp|ms-vscode|1.7.0|
|code-settings-sync|Shan|2.4.3|
|stylelint|shinnn|0.22.0|
|unity-debug|Unity|1.1.0|

---

Steps to Reproduce:

1. switch from solarized dark and light
2. one has italic comments (dark) and the other (light) does not?

**Comment by aeschli** [comment]
We got the themes from http://colorsublime.com/. I don't know if that difference of comment style is intentional or an oversight and I'd rather not make changes to these themes.
I'd suggest you try some of the other 'solarized' themes from the MarkedPlace or create a modified version of the theme yourself.

**Comment by rakkarage** [comment]
If you use solarized (built-in) in sublime3 they are both not italic it seems.
If you use solarized (built-in) in atom they are both italic it seems.
I am pretty sure no one would intentionally change italics between a light and dark version of same theme.
http://ethanschoonover.com/solarized
Looks like the official solarized site shows italics for both.

**Comment by aeschli** [comment]
Ok, you convinced me :-) I changed the comments to italics also for the Light theme.
