### ISSUE TITLE
`Insert into Terminal` requires 2 clicks if terminal is closed

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#205744]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.87.0-insider (user setup)
Commit: 01ce8d869e4220577e194b2dd57bfa12437dfcf5
Date: 2024-02-20T01:53:30.190Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.25987
- OS Version: Windows 11 Insiders

Testing https://github.com/microsoft/vscode-python-debugger/issues/221

Steps to Reproduce:

1. Used sparkle to resolve an import issue with Copilot
2. Select `Insert into Terminal`, without my terminal already open

![Image](https://github.com/microsoft/vscode/assets/25310137/c80b81d9-4d52-490b-8ae3-0dd243859fe9)

3. My terminal opens, but nothing is inserted
4. I need to select `Insert into Terminal` again

I would've expected `Insert into Terminal` to open the terminal and paste in the command, rather than requiring 2 interactions.

**Comment by Tyriar** [comment]
Doesn't happen on macOS for me, likely something happening on Windows.
