### ISSUE TITLE
requestLanguageModelAccess throws error on first call when copilot hasn't been activated

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#205726]
Testing #205568

Not sure if this is an issue with the api implementation or with copilot

1. Start VS Code but do not active vscode chat
2. Call `vscode.lm.requestLanguageModelAccess('copilot-gpt-4')`

**bug**
The first time this is called, after a small delay I see:

![Image](https://github.com/microsoft/vscode/assets/12821956/2cd5c51b-0d36-4809-b18d-f987e761752e)

Subsequent calls work as expected

**Comment by ulugbekna** [comment]
If we show a dialog window on such an error, I would say it's important that the API forces extension devs to handle this case IMHO

**Comment by jrieken** [comment]
> If we show a dialog window on such an error,

AFAIK know it's the extension that shows the error, the API simply throws. I guess the question is how to make throwing more obvious or can throwing be avoided in some cases?

**Comment by mjbvz** [comment]
@jrieken My main concern was  extension activation. Can we make  `requestLanguageModelAccess` activate copilot automatically, perhaps with a `onLanguageModelRequested:` activation event

**Comment by jrieken** [comment]
Yeah, that's on our list

**Comment by jrieken** [comment]
I have now added `onLanguageModelAccess:<NAME>` which should solve the major point but let's still reconsider this for polish
