### ISSUE TITLE
Dictated text goes off screen when using voice commands.

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#205783]
Testing #205521

I'm not sure what the correct fix is but if the text was generated outside of the view, I would image the editor would scroll horizontally as text gets inserted. (same as typing in the editor).

![Image](https://github.com/microsoft/vscode/assets/25044782/101d765e-b423-4eb0-8745-c212f8345663)

**Comment by bpasero** [comment]
Yes, very good catch.
