### ISSUE TITLE
 the terminal of vscode 1.9.1 didn't work until restart the computer.

### ISSUE THREAD

**Issue by Midqiu** [Microsoft/vscode#20575]
![image](https://cloud.githubusercontent.com/assets/5728399/22912182/ada6afe6-f29e-11e6-8e76-7271dfa9844e.png)

when I edit the “Path”, the terminal of vscode 1.9.1 didn't work. I need to restart the computer.

- VSCode Version:1.9.1
- OS Version:Win 7

**Comment by Tyriar** [comment]
You will need to restart all instances of VS Code in order for path changes to take affect.
