### ISSUE TITLE
How do chat participants using language access know what language model ID to request access to?

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#205760]
Testing #205609

`requestLanguageModelAccess` requires that you know the provider name and model name that you want to address. Should this be in the docstring or in a tutorial, and should we allow wildcards like document selectors to match?

**Comment by jrieken** [comment]
It is in `lm.languageModels` and `lm.onDidChangeLanguageModels`. Keeping to make sure the doc mentions this.

**Comment by jrieken** [comment]
API moved to `sendChatRequest`, docs are updated
