### ISSUE TITLE
Possible Bug: Single-Stepping in JS involving 'Get' Property Accessor

### ISSUE THREAD

**Issue by ralphtee** [microsoft/vscode#20576]
![singlestepfail](https://cloud.githubusercontent.com/assets/22031088/22912146/8114b69e-f29e-11e6-8e26-e85cb66c4718.png)

The screen capture shows a simple JS app. When single-stepping, the debugger caused property 'z' to be modified. The expected output should be '1', '2', '3', and 'bye'. However, when single-stepping in VSCode, the outputs (i.e, values of 'z') depend on how frequent you view/inspect the object 'o1' in the Variable window.

**Comment by connor4312** [comment]
This is fixed in the [new debugger](https://github.com/microsoft/vscode-js-debug/). By default we will no longer auto-expand getters, matching the behavior of Chrome.
