### ISSUE TITLE
Can't open this git resource.

### ISSUE THREAD

**Issue by parliament718** [Microsoft/vscode#2057]
Is anybody else getting this error when clicking a folder in the git sidebar?

Currently I'm observing it happening when I click on a folder under "Changes" in the git sidebar.  I get

Warn: Can't open this git resource. [Close]

I can't view the changes

**Comment by parliament718** [comment]
Oh I see... this is because the folder itself is a different git repository.

**Comment by qbikez** [comment]
It would be nice if VSCode supported git submodules..
