### ISSUE TITLE
Upgrade vscode 1.9.0/1.9.1, but it cant work! 

### ISSUE THREAD

**Issue by zysam** [Microsoft/vscode#20583]
- VSCode Version:1.9.1
- OS Version:windows 10

![image](https://cloud.githubusercontent.com/assets/1755427/22918797/f7b7d146-f2c6-11e6-83d1-53d49b4215c8.png)

The editor zone is crashed!

**Comment by joaomoreno** [comment]
You probably have a very small value set in the `editor.lineHeight` setting. Please review your `settings.json` file.

**Comment by zysam** [comment]
thanks! 
before (vscode 1.7.1 is normal): `"editor.lineHeight": 0.8`
after i commented that line

It return to normal!
