### ISSUE TITLE
Outline nested items gui performance issue

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode#205840]
Rendering more than 50 nested levels causes lag in Outline and the dropdown Breadcrumbs view

In my test cases:
The `provideDocumentSymbols()` can handle about 600,000 `DocumentedSymbols` before I start getting `OutOfMemory` errors

Takes around 30sec to load 600,000 **sibling** symbols
But once loaded, gui scrolling is smooth

`provideDocumentSymbols()` can only handle a nesting depth of around 950 levels
going further results in getting `call stack` errors
however the gui loads instantly when at the **top** of the outline view
**But** rendering more than 50 nested levels at once starts to lag when scrolling
at 500 nested levels it takes in excess of 3minutes to scroll

notice the scrolling starting out smoothly
then progressively getting laggier

https://github.com/microsoft/vscode/assets/33529441/dc5b554c-ea13-4e2b-87d6-8e99da1ddf61

Rendering horizontally should be optimized 
as only a small porition of the outline space is actually in view

```json
{
	"scopeName": "source.nesting",
	"patterns": [{ "patterns": [{ "patterns": [{  }] }] }]
}
```

**Comment by jrieken** [comment]
Please share renderer profile and the spec of your machine

 Hit F1 > Toggle Developer Tools. In the overflow menu select 'More Tools > JavaScript Profiler'. In there select start, let it profile for 30 to 60 seconds, stop it, save it to a file and attach the file here. Thanks.

https://user-images.githubusercontent.com/1794099/120606621-a97e0180-c44f-11eb-8e32-9fdafdc949ec.mov

**Comment by RedCMD** [comment]
found it
I had to enable it under `Settings` > `Experiments`
![image](https://github.com/microsoft/vscode/assets/33529441/9f3599be-a865-4cfd-9946-fc89fa00afe1)

heres the cpu profile
[CPU-20240222T101438.cpuprofile](https://github.com/microsoft/vscode/files/14365177/CPU-20240222T101438.cpuprofile)
and a much longer profile
[CPU-20240222T101927.cpuprofile](https://github.com/microsoft/vscode/files/14365204/CPU-20240222T101927.cpuprofile)

**Comment by RedCMD** [comment]
The performance drop is situated in the gui tree graph view rendering
having hundreds of thousands of sibling nodes is fine, but going above 50 nested levels tanks performance during render updates

The tree view is used in multiple places
Outline, References, Breadcrumbs, Explorer, SCM, Run & Debug etc

Call Hierarchy References:
![image](https://github.com/microsoft/vscode/assets/33529441/d5bcb5fc-cfee-4a9d-9882-81afacc1bad4)

**Comment by RedCMD** [comment]
how come my previous comment was marked as `off-topic`?

were you able to confirm the performance issue?
