### ISSUE TITLE
can't debug

### ISSUE THREAD

**Issue by JamieRuner** [microsoft/vscode#205805]
Type: <b>Bug</b>

can't debug when use javascript debug terminal for nodejs programe debug

VS Code version: Code 1.86.2 (Universal) (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:13.651Z)
OS version: Darwin arm64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|62, 36, 17|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|--crash-reporter-id 61417937-17ca-430f-a6ad-032833af39ee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
markdown-mermaid|bie|1.22.0
ruby-debug|cas|0.3.5
solargraph|cas|0.24.1
thrift|cdu|0.0.1
npm-intellisense|chr|1.4.5
vscode-eslint|dba|2.4.4
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|14.8.2
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.5.0
prettier-vscode|esb|10.1.0
go|gol|0.41.0
go-nightly|gol|2024.2.1618
cloudcode|goo|2.4.0
ruby|gro|0.1.0
rails-snippets|Hri|1.0.8
rest-client|hum|0.25.1
byesig|ita|0.0.14
better-cpp-syntax|jef|1.17.2
ts-debug|kak|0.0.6
json2csv|kha|0.0.1
vscode-rdbg|Koi|0.2.2
azure-ssml-tags|lex|0.0.1
Kotlin|mat|1.7.1
rainbow-csv|mec|3.11.0
git-graph|mhu|1.30.0
ruby-symbols|mig|0.1.8
vscode-fileheader|mik|0.0.2
vscode-docker|ms-|1.29.0
vscode-kubernetes-tools|ms-|1.3.15
vscode-postgresql|ms-|0.3.0
debugpy|ms-|2024.0.0
isort|ms-|2023.10.1
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.1.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.338.1
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.17.16
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.8.22
remote-explorer|ms-|0.4.1
vscode-js-profile-flame|ms-|1.0.8
go-doc|msy|1.0.1
sqltools|mtx|0.28.1
vscode-gn|npc|1.1.0
vscode-versionlens|pfl|1.9.2
material-icon-theme|PKi|4.34.0
vscode-protolint|ple|0.8.0
goasm|qui|0.0.5
java|red|1.28.1
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
ruby-extensions-pack|Sho|0.1.8
ruby-lsp|Sho|0.5.11
sorbet-vscode-extension|sor|0.3.33
tabnine-vscode|Tab|3.71.0
cmake|twx|0.0.17
vscode-counter|uct|3.4.0
vscode-torque|v8-|1.0.3
vscode-lldb|vad|1.10.0
haml|vay|1.0.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.13.5
vscode-java-debug|vsc|0.56.1
vscode-java-dependency|vsc|0.23.4
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0
volar|Vue|1.8.27
markdown-all-in-one|yzh|3.6.2
vscode-proto3|zxh|0.5.5

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30959800
b1063948:30958189
a89i1917:30961429
3ef8e399:30967273
bg6jg535:30958357

```

</details>

**Comment by blimmer** [comment]
For me, the issue was that I installed the [Bun VSCode extension](https://marketplace.visualstudio.com/items?itemName=oven.bun-vscode), which breaks the debug terminal (see https://github.com/oven-sh/bun/issues/5208). Leaving this comment here in case anyone else runs into the same issue.
