### ISSUE TITLE
Error handlers for the Copilot Chat API

### ISSUE THREAD

**Issue by vinistock** [microsoft/vscode#205875]
Currently, if you're using the new Copilot Chat API and end up passing more tokens than the accepted limit, the chat just prints `bad request 400`.

It would be nice if consumers of the API had access to a handler/callback to handle chat errors and decide what to do. Maybe it's reducing the amount of content or showing a friendlier message.

**Comment by jrieken** [comment]
This very likely got fixed (today) but without knowing what function/API you are using it's hard to know.
