### ISSUE TITLE
VS code crash

### ISSUE THREAD

**Issue by Marin-Tsanov** [Microsoft/vscode#20586]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|jslint|ajhyndman|1.2.1|
|jshint|dbaeumer|0.10.13|
|csharp|ms-vscode|1.1.6|

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Please provide more details.
