### ISSUE TITLE
Add typings for errors from `requestLanguageModelAccess`

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#205800]
Testing #205568

We should probably introduce specific error types for:

- The user has denied access
- The requested model could not be found

This makes it easier to handle those cases instead of checking the message string

As an alternative, we could only reject the promise on unknown errors and switch the return type of `requestLanguageModelAccess ` to something like:

```ts
type LanguageModelAccess =
    | { type: 'granted', access: LanguageModelAccess}
    | { type: 'defined' }
    | { type: 'modelNotFound' }
```

**Comment by jrieken** [comment]
Also a totally different approach that @ulugbekna and I discussed is to change the access-object into a callback-based API, e.g instead of asking for access you would have something like this

```ts
interface LanguageModel {
  makeChatRequest(messages, options, token): LanguageModelResponse;
}

function useLanguageModel<R>(model:string, handler: (lm: LanguageModel)=>R): R;
```

With that you don't ask for access and you cannot hold-on to a stale/revoked language model object 🤷

**Comment by ulugbekna** [comment]
>  switch the return type of requestLanguageModelAccess  to something like:

I would love this solution of using discriminated union but I think this deviates from how the whole API is. 

But I agree that having subclasses of `Error` thrown that a user can `instanceof` against would be nice. 


---

Orthogonal issue is presence of `isRevoked`, which needs to be checked before making a request. I think having a callback greatly discourages of keeping a handle to the model but doesn't prevent it. I think we could express the access being revoked in the return type -- most simple is `LanguageModelResponse | undefined` or, or more involved, `LanguageModelResponse | ErrorResponse` 


```ts
makeChatRequest(...): LanguageModelResponse | undefined
```

**Comment by jrieken** [comment]
Maybe even simpler (inspired by @joaomoreno) would be this ⬇️. It avoids having an access object all together. 

```ts

export interface LanguageModelResponse {

  // as today
  stream: AsyncIterable<string>
  value: Thenable<unknown>

  // similar to HTTP status code
  code: OK | ModelNotFound | AccessRequestRejected |

  // intead of code some boolean or have makeChatRequest return `undefined`
  isRefused: boolean;
}

export function makeChatRequest(
  id: string, 
  messages: LanguageModelMessage[],
  options: { [name: string]: any }, 
  token: CancellationToken
): LanguageModelResponse;
```

**Comment by jrieken** [comment]
implemented (most of) above with https://github.com/microsoft/vscode/pull/206088 - I believe this will be the better/simpler API

**Comment by jrieken** [comment]
Closing - we have now just `sendChatRequest` and there is also `LanguageModelError`

**Comment by jrieken** [comment]
To verify check that we have `LanguageModelError` which follows the same pattern as other errors defined in the API
