### ISSUE TITLE
Getting back undefined for `LanguageModelResponse.result`

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#205802]
Testing #205568

In my testing, I always get back `undefined` when accessing `LanguageModelResponse.result` with `copilot-gpt-4`. I know the type is unknown but the docs suggest I should be able to at least know if the request succeeded or failed

>  The overall result of the request which represents failure or success

**Comment by jrieken** [comment]
Yeah, we need to specify something in the "counter part" so that this works: https://github.com/microsoft/vscode/blob/1612c2d082293e25f0cd2f0703650245ca513d65/src/vscode-dts/vscode.proposed.chatProvider.d.ts#L19

**Comment by jrieken** [comment]
Obsolete because we have removed that property
