### ISSUE TITLE
Switching menubar display position failed with error

### ISSUE THREAD

**Issue by yiliang114** [microsoft/vscode#205836]
![image](https://github.com/microsoft/vscode/assets/11473889/6a2f1cb7-5287-4d54-b311-e49c161a6f61)

Reproduction steps:
1. Use vscode.dev to open a project, such as `https://insiders.vscode.dev/github/microsoft/vscode`
2. Switch the top menubar from TitleBar to the ActivityBar, or do the opposite.
3. After switching several times, it was found that the switch failed. If you open the console, you will find an error.

![bug32](https://github.com/microsoft/vscode/assets/11473889/edfb0864-0b57-4335-aac2-712b8ffa1c5c)

Version: 1.87.0-insider
Commit: ee69e2887fbe532588f74ae86560e7fdc1e59550
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by yiliang114** [comment]
ref: https://github.com/microsoft/vscode/issues/199744, because command with the same name cannot be registered now.

The process of switching menu bars is accompanied by the destruction and initialization of two custom menu bars from A and B respectively, and their destruction execution order cannot be guaranteed. When one of the instances is destroyed and executed, the initialization of the new instance will have this problem, because initialization means registering a command with the same name.

https://github.com/microsoft/vscode/blob/f7f9fb09a3200246a55da9d6882d56b82eb4fe9a/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L440

**Comment by bpasero** [comment]
I think the issue here is that the menu bar control gets disposed in the one place and then created in the other place (title bar, activity bar) but the order is not guaranteed to be dispose first and create later, as such this action gets first registered a second time and then gets disposed:

https://github.com/microsoft/vscode/blob/67f91582f588d1d37a94ce5b18e01ba535184967/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L437-L454

**Comment by yiliang114** [comment]
> id: `workbench.actions.menubar.focus`,

Yeah, I found it, too. My original idea was to ensure that it was reasonable to reinstall after the uninstall was completed through some event mechanism, such as use `this.titleService.onMenubarVisibilityChange`, but that would require listening on both sides.

**Comment by yiliang114** [comment]
> We only recently changed to throwing an error in this case which now breaks this flow, but the issue was there before already...

Yes, Previously command with the same name can be overwritten without causing a problem. The exception thrown now causes the handler to not be executed and the switch fails.

**Comment by alexr00** [comment]
> Switch the top menubar from TitleBar to the ActivityBar, or do the opposite.

How can I do this? I'm having trouble understanding how to get the top menu to show at all. I can only get the hamburger menu.

**Comment by alexr00** [comment]
Finally found it.
