### ISSUE TITLE
Misplaced warning

### ISSUE THREAD

**Issue by tSte** [Microsoft/vscode#20588]
Honestly: I don't know how to reproduce it. I don't even know ho to name this issue correctly. See attached screenshot...

- VSCode Version: 1.9.1
- OS Version: Windows 8.1 x64

![image](https://cloud.githubusercontent.com/assets/8778539/22922986/027cccb6-f2a0-11e6-80a1-ad916be8875c.png)

**Comment by joaomoreno** [comment]
This seems to be an issue with Omnisharp, can you file an issue over there? https://github.com/OmniSharp/omnisharp-vscode/issues
