### ISSUE TITLE
What is `ChatParticipant.fullName` for?

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#205811]
Testing #205609

From the API JSdoc it's clear what `name` is for, less clear where `fullName` is used or why they would be different.

```ts
	export interface ChatParticipant {

		/**
		 * The short name by which this participant is referred to in the UI, e.g `workspace`.
		 */
		readonly name: string;

		/**
		 * The full name of this participant.
		 */
		fullName: string;
	}
```

**Comment by roblourens** [comment]
@jrieken did we already talk about this? `fullName` is actually only used for the default participant. It seems like something we would use at some point. We could have participants populate it now before we need it or delete it and add it back when it's necessary, I'm thinking we just get rid of it for now.

**Comment by jrieken** [comment]
Let's leave it our for now. No API is the best API ;-)
