### ISSUE TITLE
Expose "workbench.editor.pinnedTabSizing" as context menu for pinned tabs

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#205845]
![Code_-_Insiders_XhZOtoZpKj](https://github.com/microsoft/vscode/assets/2931520/9967c229-b094-4741-96bd-ed48e1357b4e)

`workbench.editor.pinnedTabSizing` is not very discoverable.
If it would be a submenu of the context menu, it would be much easier to tweak this setting.

**Comment by bpasero** [comment]
🤔 ... 👎

**Comment by benibenj** [comment]
I'm for making these types of settings more discoverable, however, I do not want to add these types of settings to the contextmenu. We mainly use the context menu to change the visibility of elements/features but we don't really use it to configure them/change appearance. Also, the context menu is already pretty full and I don't want to overload it.

**Comment by benibenj** [comment]
I'm open to other ideas to make them more discoverable. Maybe a "configure" entry in the overflow menu of the toolbar?

**Comment by bpasero** [comment]
Yeah I like the idea of an action in the "..." menu to configure all things editor related by narrowing down a settings search in the settings editor.

**Comment by benibenj** [comment]
verification steps:
- Right click on the tab bar (not on a tab)
- At the bottom of the context menu there is an action "Configure Tabs...", press it
- Settings editor should open with tabs related settings
