### ISSUE TITLE
Discarding a refactor doesn't close the multi-diff editor

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#205855]
Testing https://github.com/microsoft/vscode/issues/205853

1. Make a refactor that shows the Refactor view
2. In the refactor view, click on a change to open the multi-diff editor
3. In the Refactor view, click "Discard"
4. I would expect the multi-diff editor to now close as it is not longer meaningful.

**Comment by aiday-mar** [comment]
Hi thank you for posting this issue. This should be fixed by a [PR made 3 hours ago.](https://github.com/microsoft/vscode/pull/205710) The fix should be in tomorrow's Insiders.

**Comment by alexr00** [comment]
Awesome, I will verify tomorrow!
