### ISSUE TITLE
`ChatRequestTurn.participant.participant` could be avoided

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#205807]
Testing #205609

Minor nit, but could we have `ChatRequestTurn.participant.name` instead?

**Comment by roblourens** [comment]
I'd prefer this or `participantName`, thoughts @jrieken?

**Comment by jrieken** [comment]
I also have a preference for `name`. The story would be that `name` is the user visible thing and the fully qualified identifier (which we generate/own) is `extensionId.name`
