### ISSUE TITLE
inconsistent js highlighting

### ISSUE THREAD

**Issue by anvish** [Microsoft/vscode#20589]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-file-peek|abierbaum|1.0.1|
|Bookmarks|alefragnani|0.11.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.6|
|tslint|eg2|0.8.1|
|auto-close-tag|formulahendry|0.3.9|
|auto-rename-tag|formulahendry|0.0.11|
|contextualduplicate|lafe|0.2.0|
|vscode-stylefmt|mrmlnc|2.2.2|
|debugger-for-chrome|msjsdiag|2.5.3|
|typescript-hero|rbbit|0.12.0|
|stylelint|shinnn|0.22.0|

---

Steps to Reproduce:

1. Start code with --disable-extensions
2. Open .ts or .js file with contents:
```ts
const a = {
    1: '1',
    '2': '2',
}
```

Properties named with numbers are not highlighted:

![bug2](https://cloud.githubusercontent.com/assets/1114090/22923488/ba14ba2a-f2b2-11e6-85ea-7e468ee5253a.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#417
