### ISSUE TITLE
Refactor Preview: Unclear which file is revealed

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#205850]
FYI @aiday-mar 

![Code_-_Insiders_INioRxdknw](https://github.com/microsoft/vscode/assets/2931520/a1c2492a-4a64-4ae6-8d76-59490f7c8004)

I think revealing should set focus of the text editor and the focused editor should have a different background color.

**Comment by justschen** [comment]
@hediet trying to verify, I'm not sure if i see anything happening other than the character being highlighted. 

![Recording 2024-02-22 at 12 12 47](https://github.com/microsoft/vscode/assets/54879025/ba193b09-4e68-4581-91ac-92714976eb7b)

**Comment by rzhao271** [comment]
I see the same thing as Justin. I don't see a focus border for the focused editor when I change editors by clicking in the Refactor Preview pane.

However, I just tried using the up/down arrow keys to navigate through the tree, and noticed that the highlights were much more noticeable in that case. I also realized that navigating through the tree by mouse or keyboard doesn't automatically focus the diff editors, which probably explains why the diff editors didn't get focus border highlights.

Marking as verified.

**Comment by hediet** [comment]
>  I also realized that navigating through the tree by mouse or keyboard doesn't automatically focus the diff editors, which probably explains why the diff editors didn't get focus border highlights.

Yes, it used to focus the multi file diff editor, but I got feedback this is an anti-pattern (and I agree).
