### ISSUE TITLE
`ChatRequestHandler` should allow returning `void`

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#205835]
Testing #205609

If there's no error case, I now need to return something like:

```
return {};
```

**Comment by rzhao271** [comment]
Moving to March for now. Feel free to move this issue back to February if it turns out to be a candidate.

**Comment by roblourens** [comment]
It's already a `ProviderResult`, which allows 'undefined' but not void. Is it weird to say `ProviderResult<ChatResult | void> | void`?

**Comment by joyceerhl** [comment]
+1 on this, I have to explicitly `return undefined` today
