### ISSUE TITLE
Order of files in refactor preview doesn't match order in multi-diff editor

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#205859]
Testing https://github.com/microsoft/vscode/issues/205853

With all the files in the multi-diff editor collapsed to make it easy to see:
![image](https://github.com/microsoft/vscode/assets/38270282/b807a3b2-8cd0-476b-900c-9c8f5fcc7b27)

To repro, try to rename this: 

https://github.com/microsoft/vscode/blob/f34821fb1b2d37f704f82f6590cf7639365167d9/src/vs/platform/configuration/common/configuration.ts#L130

**Comment by aiday-mar** [comment]
I see, that's a good point thanks!

**Comment by aiday-mar** [comment]
To verify:

- Do a rename but do not accept rename
- Click on `shift + enter`
- The refactor preview should open
- Open the multi diff editor from there by clicking on any change in the refactor preveiw
- Check that the order of the files in the refactor preview matches the order of the files in the multi diff editor
