### ISSUE TITLE
High memory usage and keeps crashing with code 9

### ISSUE THREAD

**Issue by ppazos** [microsoft/vscode#205817]
Type: <b>Bug</b>

It's impossible to reproduce, check the logs. It just starts eating memory then freezes my whole desktop then it crashes with code 9. Today it crashed four times.

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:41:37.860Z)
OS version: Linux x64 5.15.0-94-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 3|
|Memory (System)|11.57GB (1.67GB free)|
|Process Argv|. --crash-reporter-id c58b6a49-a4ed-4475-9157-e3a90d8d2a9b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.10.2
scratchpads|bue|1.0.0
aql|DIP|0.9.1
xml|Dot|2.5.1
comment-anchors|Exo|1.10.4
vscode-diff|fab|1.4.2
code-groovy|mar|0.1.2
rainbow-csv|mec|3.11.0
vscode-docker|ms-|1.29.0
openehr-adl-lsp|Ned|0.6.1
edi-x12-support|Sil|1.1.0
doki-theme|unt|88.1.16
php-debug|xde|1.34.0
php-pack|xde|1.0.3
vscode-fhir-tools|Yan|1.5.1
php-intellisense|zob|1.3.3

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30959800
edj9j583:30958191
a89i1917:30961429
3ef8e399:30967273
e3gdj431:30958358
ccp2r3:30958157

```

</details>

**Comment by ppazos** [comment]
Found the logs:

```
2024-02-20 03:57:15.792 [info] update#setState idle
2024-02-20 03:57:45.793 [info] update#setState checking for updates
2024-02-20 03:57:46.024 [info] update#setState idle
2024-02-20 04:57:45.808 [info] update#setState checking for updates
2024-02-20 04:57:46.877 [info] update#setState idle
2024-02-20 12:38:33.224 [info] update#setState checking for updates
2024-02-20 12:38:33.685 [info] update#setState idle
2024-02-20 13:38:33.227 [info] update#setState checking for updates
2024-02-20 13:38:33.587 [info] update#setState idle
2024-02-20 14:05:52.703 [info] Extension host with pid 51521 exited with code: 0, signal: unknown.
2024-02-20 14:24:20.014 [info] Extension host with pid 64997 exited with code: 0, signal: unknown.
2024-02-20 14:38:33.237 [info] update#setState checking for updates
2024-02-20 14:38:33.572 [info] update#setState idle
2024-02-20 15:38:33.243 [info] update#setState checking for updates
2024-02-20 15:38:33.575 [info] update#setState idle
**2024-02-20 16:32:56.845 [error] CodeWindow: renderer process gone (reason: killed, code: 9)**
2024-02-20 16:32:57.267 [info] Extension host with pid 49002 exited with code: 0, signal: unknown.
**2024-02-20 16:33:01.121 [error] [UtilityProcess id: 1, type: fileWatcher, pid: 49047]: crashed with code 139 and reason 'crashed'**
2024-02-20 16:38:33.246 [info] update#setState checking for updates
2024-02-20 16:38:33.549 [info] update#setState idle
2024-02-20 17:38:33.259 [info] update#setState checking for updates
2024-02-20 17:38:33.846 [info] update#setState idle
2024-02-20 20:27:08.585 [info] update#setState checking for updates
2024-02-20 20:27:08.961 [info] update#setState idle
2024-02-20 20:40:37.906 [warning] No ptyHost heartbeat after 6 seconds
2024-02-20 20:41:07.943 [warning] No ptyHost heartbeat after 6 seconds
**2024-02-20 20:41:10.733 [error] CodeWindow: renderer process gone (reason: killed, code: 9)**
2024-02-20 20:41:10.950 [info] Extension host with pid 72865 exited with code: 0, signal: unknown.
**2024-02-20 20:41:12.281 [error] [UtilityProcess id: 3, type: fileWatcher, pid: 72875]: crashed with code 139 and reason 'crashed'**
2024-02-20 21:12:48.113 [error] CodeWindow: renderer process gone (reason: killed, code: 9)
2024-02-20 21:12:48.972 [info] Extension host with pid 87606 exited with code: 0, signal: unknown.
2024-02-20 21:12:52.606 [error] [UtilityProcessWorker]: terminated unexpectedly with code 15, signal: unknown
2024-02-20 21:12:52.607 [error] [UtilityProcess id: 4, type: fileWatcher, pid: 87621]: crashed with code 15 and reason 'killed'
2024-02-20 21:14:01.036 [warning] No ptyHost heartbeat after 6 seconds
2024-02-20 21:28:25.160 [info] update#setState checking for updates
2024-02-20 21:28:25.261 [error] CodeWindow: detected unresponsive
2024-02-20 21:28:26.333 [info] update#setState idle
2024-02-20 21:28:44.060 [warning] No ptyHost heartbeat after 6 seconds
2024-02-20 21:28:57.193 [info] Extension host with pid 91040 exited with code: 0, signal: unknown.
```

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by davesahaj** [comment]
Dealing with same issue on linux 6+.

**Comment by houhuawei23** [comment]
same issue

**Comment by houhuawei23** [comment]
i follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues, and crashed again, but i cant find the *.dmp file.
![image](https://github.com/microsoft/vscode/assets/36103474/cd847d60-44ea-4299-a41d-97293a1d1d6d)

System:
  Kernel: 5.15.0-101-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
    tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: HUAWEI product: HKF-WXX v: M1010 serial: <superuser required>
  Mobo: HUAWEI model: HKF-WXX-PCB v: M1010 serial: <superuser required> UEFI: HUAWEI v: 1.12
    date: 04/27/2023
Battery:
  ID-1: BAT0 charge: 51.9 Wh (100.0%) condition: 51.9/59.4 Wh (87.3%) volts: 13.0 min: 11.6
    model: DESAY HB5781P1EEW-31T type: Li-ion serial: <filter> status: Discharging cycles: 208
CPU:
  Info: 12-core (4-mt/8-st) model: 12th Gen Intel Core i5-12500H bits: 64 type: MST AMCP
    smt: enabled arch: Alder Lake rev: 3 cache: L1: 1.1 MiB L2: 9 MiB L3: 18 MiB
  Speed (MHz): avg: 1336 high: 2285 min/max: 400/4500:3300 cores: 1: 1048 2: 861 3: 1179 4: 1263
    5: 1260 6: 2285 7: 1677 8: 1267 9: 1590 10: 1186 11: 1559 12: 976 13: 1008 14: 2219 15: 410
    16: 1601 bogomips: 99532
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel Alder Lake-P Integrated Graphics vendor: Huawei driver: i915 v: kernel ports:
    active: HDMI-A-1,eDP-1 empty: DP-1,DP-2,DP-3 bus-ID: 00:02.0 chip-ID: 8086:46a6 class-ID: 0300
  Device-2: Luxvisions Innotech USB Camera type: USB driver: uvcvideo bus-ID: 3-7:3
    chip-ID: 30c9:0041 class-ID: fe01 serial: <filter>
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting unloaded: fbdev,vesa
    gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 8480x2240 s-dpi: 120 s-size: 1795x474mm (70.7x18.7") s-diag: 1857mm (73.1")
  Monitor-1: HDMI-1 mapped: HDMI-A-1 pos: right model: HDMI3 serial: <filter> res: 5120x2160
    hz: 60 dpi: 216 size: 601x253mm (23.7x10.0") diag: 652mm (25.7") modes: max: 2560x1080
    min: 720x400
  Monitor-2: eDP-1 pos: primary,left res: 3360x2240 hz: 90 dpi: 284 size: 300x200mm (11.8x7.9")
    diag: 361mm (14.2") modes: 2520x1680
  OpenGL: renderer: Mesa Intel Graphics (ADL GT2) v: 4.6 Mesa 23.2.1-1ubuntu3.1~22.04.2
    direct render: Yes
Audio:
  Device-1: Intel Alder Lake PCH-P High Definition Audio vendor: Huawei
    driver: sof-audio-pci-intel-tgl bus-ID: 00:1f.3 chip-ID: 8086:51c8 class-ID: 0401
  Sound Server-1: ALSA v: k5.15.0-101-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Alder Lake-P PCH CNVi WiFi driver: iwlwifi v: kernel bus-ID: 00:14.3
    chip-ID: 8086:51f0 class-ID: 0280
  IF: wlp0s20f3 state: up mac: <filter>
Bluetooth:
  Device-1: Intel type: USB driver: btusb v: 0.8 bus-ID: 3-10:5 chip-ID: 8087:0033 class-ID: e001
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter>
Drives:
  Local Storage: total: 2.75 TiB used: 328.46 GiB (11.7%)
  ID-1: /dev/nvme0n1 vendor: Western Digital model: WD PC SN740 SDDPNQD-1T00-1027
    size: 953.87 GiB speed: 63.2 Gb/s lanes: 4 type: SSD serial: <filter> rev: 74113000 temp: 32.9 C
    scheme: GPT
  ID-2: /dev/sda type: USB vendor: Western Digital model: WD Elements SE 2622 size: 1.82 TiB
    type: N/A serial: <filter> rev: 1023 scheme: GPT
Partition:
  ID-1: / size: 937.33 GiB used: 88.15 GiB (9.4%) fs: ext4 dev: /dev/nvme0n1p2
  ID-2: /boot/efi size: 511 MiB used: 17.1 MiB (3.3%) fs: vfat dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 2 GiB (100.0%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 1 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Hub-2: 2-0:1 info: Super-speed hub ports: 3 rev: 3.1 speed: 20 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
  Hub-3: 2-1:2 info: Genesys Logic USB3.1 Hub ports: 4 rev: 3.2 speed: 5 Gb/s chip-ID: 05e3:0626
    class-ID: 0900
  Device-1: 2-1.1:3 info: Western Digital Elements SE 2622 type: Mass Storage
    driver: usb-storage interfaces: 1 rev: 3.2 speed: 5 Gb/s power: 896mA chip-ID: 1058:2622
    class-ID: 0806 serial: <filter>
  Hub-4: 3-0:1 info: Hi-speed hub with single TT ports: 12 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Hub-5: 3-3:2 info: Genesys Logic Hub ports: 4 rev: 2.1 speed: 480 Mb/s power: 100mA
    chip-ID: 05e3:0610 class-ID: 0900
  Device-1: 3-3.2:4 info: [Maxxter] Optical gaming mouse type: Mouse,Keyboard
    driver: hid-generic,usbhid interfaces: 2 rev: 1.1 speed: 1.5 Mb/s power: 100mA
    chip-ID: 18f8:0f99 class-ID: 0300
  Device-2: 3-3.3:7 info: Areson Corp 2.4G Wireless Device type: Keyboard
    driver: hid-generic,usbhid interfaces: 2 rev: 2.0 speed: 12 Mb/s power: 100mA chip-ID: 25a7:2420
    class-ID: 0301
  Device-3: 3-7:3 info: Luxvisions Innotech USB Camera type: Video driver: uvcvideo
    interfaces: 5 rev: 2.0 speed: 480 Mb/s power: 500mA chip-ID: 30c9:0041 class-ID: fe01
    serial: <filter>
  Device-4: 3-10:5 info: Intel type: Bluetooth driver: btusb interfaces: 2 rev: 2.0
    speed: 12 Mb/s power: 100mA chip-ID: 8087:0033 class-ID: e001
  Hub-6: 4-0:1 info: Super-speed hub ports: 4 rev: 3.1 speed: 10 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 27.8 C mobo: N/A
  Fan Speeds (RPM): N/A
Repos:
  Packages: apt: 2946
  No active apt repos in: /etc/apt/sources.list
  No active apt repos in: /etc/apt/sources.list.d/additional-repositories.list
  No active apt repos in: /etc/apt/sources.list.d/microsoft-edge.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //mirror.sjtu.edu.cn/linuxmint virginia main upstream import backport
    2: deb https: //mirror.nju.edu.cn/ubuntu jammy main restricted universe multiverse
    3: deb https: //mirror.nju.edu.cn/ubuntu jammy-updates main restricted universe multiverse
    4: deb https: //mirror.nju.edu.cn/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  No active apt repos in: /etc/apt/sources.list.d/vscode.list
Info:
  Processes: 479 Uptime: 9h 47m wakeups: 706 Memory: 15.34 GiB used: 14.59 GiB (95.1%)
  Init: systemd v: 249 runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12/4.8 clang: 14.0.0-1ubuntu1.1
  Client: Cinnamon v: 6.0.4 inxi: 3.3.13

**Comment by PetrLaskevic** [comment]
> Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

Could you please take a look at this? I'm happy to provide any debugging logs needed :)
I'm experiencing this with Linux.

**Comment by PetrLaskevic** [comment]
> Please share the memory profile from the workbench following the steps below

Should I start sampling as soon as I start VS Code, for hour(s) at a time? I don't know when it will crash in advance.

One workaround which helped me reduce the frequency of these crashes (haven't had one since two days) is configuring a swap partition in Linux. 

It seems like in situations when ~90% RAM is utilized (out of my 16 GB). In such situation it is always VS Code which has at least one of its windows crashed with this message. Other applications (like Firefox) never do this.
Firefox especially tries to unload tabs unused for a long time in low memory situations. 
VS Code never tries to release any memory this way.

**Comment by deepak1556** [comment]
@PetrLaskevic seems like the crashes you are experiencing is mostly from system forcing OOM for the VSCode process under memory pressure ? The virtual memory allocations happen from the runtime and we don't have control over it. Browsers do have optimization to unload memory from used tabs, it is not something we have available today in the runtime we use.

When you hit the crash, please the dump file from `<user-data-dir>/Crashpad` which would help confirm the cause of the crash. You can get path to <user-data-dir> by running `Developer: Open User Data Folder` from within VSCode.
