### ISSUE TITLE
Testing side bar colors: better highlight the difference between past and recently run tests

### ISSUE THREAD

**Issue by heinrich-ulbricht** [microsoft/vscode#205873]
The **Testing** side bar should show the **recently** run tests more prominently than today.

Currently the distinction between **past** run tests and **recently** run tests is veeeeery subtle. Barely noticible for my eyes:

![image](https://github.com/microsoft/vscode/assets/3469970/2c57aba3-cc34-4fea-b6cb-1f6dd12dfe9a)

Successful tests that have been run in the past are green. Tests from the last test run are a sliiiightly brighter green.

My hope was that those two colors are themable, but only the base color is, via `testing.iconPassed`:

https://github.com/microsoft/vscode/blob/44ffd1a464fb3b976bc110ec768b8ec5fbcb7752/src/vs/workbench/contrib/testing/browser/theme.ts#L26-L31

Not sure where the logic is hidden, but it should distinguish the two states better. Or expose it for configuration.

**Comment by sr5434** [comment]
Can I take this issue?

**Comment by sr5434** [comment]
Also, from looking at the code, they appear to be the same color:
```typescript
export const testingColorIconPassed = registerColor('testing.iconPassed', {
	dark: '#73c991',
	light: '#73c991',
	hcDark: '#73c991',
	hcLight: '#007100'
}, localize('testing.iconPassed', "Color for the 'passed' icon in the test explorer."));

export const testingColorRunAction = registerColor('testing.runAction', {
	dark: testingColorIconPassed,
	light: testingColorIconPassed,
	hcDark: testingColorIconPassed,
	hcLight: testingColorIconPassed
}, localize('testing.runAction', "Color for 'run' icons in the editor."));
```

**Comment by heinrich-ulbricht** [comment]
Not sure what `testing.runActions` is supposed to be, but it's not the color we need. `testing.iconPassed` seems to be the source of both "success" color shades. At least on my machine:

![image](https://github.com/microsoft/vscode/assets/3469970/f0663c06-8c5e-49c2-959a-1a86626fa7e5)

![image](https://github.com/microsoft/vscode/assets/3469970/3b6f1ad5-38c1-4f1c-85e3-3dfa8132384f)

**Comment by heinrich-ulbricht** [comment]
Here's how Visual Studio (not Code) does it. The difference is very visible, which is nice.
![image](https://github.com/microsoft/vscode/assets/3469970/fa7d446b-5fe4-416d-b5c8-549f7909b7ea)

**Comment by sr5434** [comment]
Ok. I will work on it and open a PR today or tomorrow.

**Comment by sr5434** [comment]
Also, ```testing.runAction``` appears to be the only source(that I can tell) of the color for recent tests. This would make sense, as its colors directly reference those of ```testing.iconPassed```. However, let me know if you find any other possible sources.

**Comment by connor4312** [comment]
For now, I would probably make a separate "retired" color for tests so that they're themable, as adding icons is much harder.

That would involve making a second object that looks like this

https://github.com/microsoft/vscode/blob/44ffd1a464fb3b976bc110ec768b8ec5fbcb7752/src/vs/workbench/contrib/testing/browser/theme.ts#L184-L191

And adding some styles here so they match the 'retired' class

https://github.com/microsoft/vscode/blob/44ffd1a464fb3b976bc110ec768b8ec5fbcb7752/src/vs/workbench/contrib/testing/browser/icons.ts#L52

and removing this

https://github.com/microsoft/vscode/blob/44ffd1a464fb3b976bc110ec768b8ec5fbcb7752/src/vs/workbench/contrib/testing/browser/media/testing.css#L150-L153

**Comment by sr5434** [comment]
Where would I find out if a test is retired

**Comment by connor4312** [comment]
you don't really need to mess with the logic that determines that, just use the selectors in the 3rd snippet I linked

**Comment by sr5434** [comment]
Ok, so just edit that CSS, right

**Comment by HYOSITIVE** [comment]
I was just looking around issues and it seems this issue should be closed given that the mentioning PR already has been merged. Can you confirm, @BABA983 ?

**Comment by connor4312** [comment]
Yep, thanks for the reminder

**Comment by alexr00** [comment]
Verified that the retired test icon is themable, but the default color is still verrry difficult to see.
