### ISSUE TITLE
Error not showing up when node2 is not supported

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#20585]
- VSCode Version: insiders
- OS Version: win10
- node: 7.5.0

Steps to Reproduce:

1. Have a simple javascript file, run vscode out of source and just add the node debug extensions
2. Node debug extension auto picks node2 however node2 does not seem to be bundled
3. I would expect an error message to be visible and not only shown in the console

![image](https://cloud.githubusercontent.com/assets/2239563/22921180/de6b4f16-f298-11e6-895c-834f23beeb27.png)

ping @isidorn

**Comment by weinand** [comment]
When running out of source, OOTB no debugger is available.
Previously it was sufficient to just install node-debug.
But recently node-debug started to reach out for node-debug2 if it detects that 'node2' should be used.
-> when running out of source we now need to install both node-debug and node-debug2.
