### ISSUE TITLE
lines overlapping by weird black bordered line on macos vs code latest update

### ISSUE THREAD

**Issue by asynchronousJavascriptor** [microsoft/vscode#205822]
<img width="1251" alt="Screenshot 2024-02-21 at 12 12 35 PM" src="https://github.com/microsoft/vscode/assets/59777005/e38be0bb-9fba-4b7f-82c4-725b7a1a6b66">

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. when i scroll down, there is a weird black border overlapping happening on my vs code

**Comment by gjsjohnmurray** [comment]
This is a recent feature called Sticky Scroll.

**Comment by jahaganiev** [comment]
@gjsjohnmurray is right, I could fix the same issue by disabling Sticky Scroll on my settings.json file:

"editor.stickyScroll.enabled": false, 

but at the same time with the "Version: 1.86.2" this feature auto enabled on MacOS for some reason

**Comment by roblourens** [comment]
Yes, this is enabled by default. Not sure if that was just in the last release or earlier
