### ISSUE TITLE
Make quick input wizard helpers part of the API

### ISSUE THREAD

**Issue by gee4vee** [microsoft/vscode#205870]
The quickInput-sample has some helper code for creating a wizard using QuickPicks. It would be great if this was incorporated into the extension API to make creating wizards with QuickPicks easier.

**Comment by TylerLeonhardt** [comment]
What parts of the sample do you wish were a part of API?

The createQuickPick API already has a way to set:
* title
* totalSteps
* step
* and other properties

These were specifically added for wizard-like experiences.

**Comment by gee4vee** [comment]
@TylerLeonhardt The [multiStepInput.ts](https://github.com/microsoft/vscode-extension-samples/blob/main/quickinput-sample/src/multiStepInput.ts) file has lots of useful helper code. If that could be abstracted into the API to avoid having to duplicate that code, it would simplify wizard creation.

**Comment by TylerLeonhardt** [comment]
We try to keep VS Code's API lean and not duplicate functionality. This is how we can make the promise that API will never break. The entirety of this, albeit useful, code is just not something we want to add to the API. The helper is only like 175ish lines of code anyway and isn't too bad to duplicate.
