### ISSUE TITLE
Terminal sticky scroll screen rendering issue

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#205899]
Does this issue occur when all extensions are disabled?: Yes/No

https://github.com/microsoft/vscode/assets/876920/9a136547-532d-4d2f-a264-8f5ce01507e8

Note that there are unexpected spaces between characters on the sticky scroll.

**Comment by Tyriar** [comment]
Think this will be fixed by #206537 / https://github.com/xtermjs/xterm.js/pull/4973
