### ISSUE TITLE
Should lm access say why it has been revoked?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#205816]
Testing #205568

It may be helpful to expose a general reason why a `LanguageModelAccess` was revoked. This could help extensions understand how to recover after their access is revoked

For example, this could help differentiate:

- The user revoked access
- The current LM is no longer available
- The lm provider or VS Code revoked access (not sure if this can actually happen yet)

**Comment by jrieken** [comment]
Maybe also a case for well-typed errors, similar to `vscode.FileSystemError`

**Comment by jrieken** [comment]
There are now well-typed errors but revocation doesn't exist anymore
