### ISSUE TITLE
Mac Vscode doesn't start anmyore

### ISSUE THREAD

**Issue by marvinhagemeister** [Microsoft/vscode#20587]
- VSCode Version: 1.9.1 insider from today (not sure which commit hash)
- OS Version: Mac OS Sierra

Just upgraded vscode to the latest insider build and now it crashes on startup before even showing a window. I know that this is really vague but I don't know how to capture stack traces or more debug infos for native apps (web dev here). When launching from the terminal, vscode immediately exits silently.

A reinstall of the insiders build didn't help.

Steps to Reproduce:

1. Open vscode-insiders
2. crash

**Comment by admmasters** [comment]
Same here - installed latest update and now doesn't start.

**Comment by Gori** [comment]
Same here - it never restarted when I clicked update and won't start at all after.

**Comment by marvinhagemeister** [comment]
Seems to be a duplicate of https://github.com/Microsoft/vscode/issues/20555 Deleting the files listed in the comments solved this issue for me and vscode starts without crashing.
