### ISSUE TITLE
TypeScript语言服务以外终止

### ISSUE THREAD

**Issue by bzd111** [Microsoft/vscode#20596]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|python|donjayamanne|0.5.8|
|vscode-html-css|ecmel|0.0.33|
|debugger-for-chrome|msjsdiag|2.5.2|
|vscode-icons|robertohuertasm|7.2.0|
|python|tht13|0.2.3|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Please provide more details.
