### ISSUE TITLE
Hectic hover updating after reload on "..." menu

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#205962]
![Recording 2024-02-22 at 11 21 27](https://github.com/microsoft/vscode/assets/900690/7aa1dbed-6595-4f07-9f7f-4cbc45fa0a81)

Here I hover over the "..." of the extensions viewlet.

**Comment by benibenj** [comment]
Will be fixed when adopting the new hover service API `setupDelayedHoverAtMouse` with `lifecycleOptions.groupId`
