### ISSUE TITLE
The beginning of log files is being deleted

### ISSUE THREAD

**Issue by daltairwalter** [microsoft/vscode#205910]
I am trying to use trace logs in Pylance to understand why its language server is failing and the beginning of its log files are being deleted.  This may be a "feature" where someone is trying to prevent the log files from growing too much, but this is critical information and the only way I have found to see all of it is to kill vscode periodically and hope I ended it at the correct time.

If it is intended that the logs are size limited for some reason, it should be noted that this is a very destructive operation and critical information is being lost so it should be very easy to discover how to disable this "feature".

**Comment by sandy081** [comment]
If Pylance is using Log output channels, then the log files are rotated when the file reaches 5MB. You can find old log files in the logs folder - F1 > Developer: Open Extensions Log Folder
