### ISSUE TITLE
Go to File list rendering slow on remotes

### ISSUE THREAD

**Issue by jamesmeneghello** [microsoft/vscode#205949]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.2
- OS Version: OSX Ventura 13.2.1

Steps to Reproduce:

1. Open a repo locally
2. Go to file (`command-p`)
3. Type a filename with several potential results
4. List renders as you're typing

1. Connect to a remote host (e.g. dev container)
2. Go to file (`command-p`)
3. Type a filename with several potential results
4. Each character typed triggers a file lookup
5. List renders only after all queued lookup commands have finished

Seems to be worse when the query returns many results - serialisation back from the remote host takes longer? Either way, inflight queries should probably be cancelled or ignored if the search is fired again, otherwise you potentially have to wait many seconds for all the queued searches to finish before it finally renders the most recent one.

This is perhaps best represented in video form.

### Local:

https://github.com/microsoft/vscode/assets/86297/942d9200-a5b9-41cc-85c9-d94ea6ac6c39

### Remote (search term typed, many searches fired):

https://github.com/microsoft/vscode/assets/86297/bf7731f7-24d9-43ce-8e77-709c09fb0b96

### Remote (search term pasted, single search fired):

https://github.com/microsoft/vscode/assets/86297/687d2b03-45a6-4885-9cf4-a62756c62074

**Comment by andreamah** [comment]
Please contribute to the conversation at https://github.com/microsoft/vscode/issues/183480
