### ISSUE TITLE
`workbench.action.debug.callStack{Top,Bottom}` editor focus lost

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#205922]
While [this is verified](https://github.com/microsoft/vscode/issues/203556) for `workbench.action.debug.callStack{Up,Down}` I still get the bad behavior for `workbench.action.debug.callStackTop` and `workbench.action.debug.callStackBottom` and feel like those commands should have a similar change.

When I run `workbench.action.debug.callStack{Top,Bottom}` focus is lost from the editor.

**Comment by roblourens** [comment]
Good point!
