### ISSUE TITLE
gulpfile icon

### ISSUE THREAD

**Issue by ZhangPuXi** [Microsoft/vscode#20592]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|

---

Steps to Reproduce:

1. create a file named gulpfile.js
2. set the file icon theme to Seti
3. the icon is not the gulp logo while remove the '.js' the icon would be alright

**Comment by aeschli** [comment]
We use https://github.com/jesseweed/seti-ui as input to the Seti theme.
I think https://github.com/jesseweed/seti-ui/issues/314 is a duplicate of what you report.

**Comment by tamowicz** [comment]
I still have this issue
