### ISSUE TITLE
File > Recent: Allow for larger list

### ISSUE THREAD

**Issue by luca76** [Microsoft/vscode#20598]
Hi,

In Linux we usually handle long path files names. When opening the recent list from File menu, it's almost impossible to read file name, since the path is truncated. It happens, for example, when opening a SFTP place or a Samba share from Files that has this path:

/var/run/user/1000/gvfs/smb-share:server=fsX,share=YYY,user=USER/Applications/blabla/filename.TXT

If we can't make the menu larger in width, we could "cut" the path in middle, leaving the filename part visible (that's fundamental).
If we have a recent list showing ONLY paths, it's almost useless :-(

- VSCode Version: 1.9.1
- OS Version: Fedora 25

**Comment by bpasero** [comment]
@luca76 can you share a screenshot how this looks like for you?

**Comment by luca76** [comment]
As you can see, only the last item in the list has the file name. The other have too long path names.

![vscode](https://cloud.githubusercontent.com/assets/5095918/23120356/524e1040-f75c-11e6-9582-68a6a37f578d.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10941
