### ISSUE TITLE
Download failing for v1.86?

### ISSUE THREAD

**Issue by ankur198** [microsoft/vscode#205990]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86
- OS Version: Debian 11

Steps to Reproduce:

1. Goto https://code.visualstudio.com/#alt-downloads
2. Click `.deb` or .`rpm`
3. Wait for download to start
4. Get redirected to `https://vscode.download.prss.microsoft.com/dbazure/download/stable/903b1e9d8990623e3d7da1df3d33db3e42d80eda/code_1.86.2-1707854558_amd64.deb` and get `ERR_CONNECTION_TIMED_OUT`

Additional Notes:
VSCode server for (v1.86) (#903b1e9d8990623e3d7da1df3d33db3e42d80eda) is also not found at `https://update.code.visualstudio.com/commit:903b1e9d8990623e3d7da1df3d33db3e42d80eda/server-linux-x64/stable` making ssh also not possible

## I just realized it doesn't even exist now for windows and mac also. Maybe there server is down or they are blocking updates due to huge influx of issues after release 🤔

**Comment by joaomoreno** [comment]
The `https://vscode.download.prss.microsoft.com/dbazure/download/stable/903b1e9d8990623e3d7da1df3d33db3e42d80eda/code_1.86.2-1707854558_amd64.deb` URL seems to connect just fine for me. Anything special about your network setup?

**Comment by ankur198** [comment]
My ISP is blocking it. Works fine with mobile data. Sorry to bother.
