### ISSUE TITLE
Failed to start VSCode after installation -- entry pointer SymGetSearchPathW can't be located in dbghelp.dll

### ISSUE THREAD

**Issue by yingang** [Microsoft/vscode#20591]
- VSCode Version: 1.8.1, 1.9.1
- OS Version: Windows 7 Professional with Service Pack 1

Steps to Reproduce:

1. Install the VSCode
2. Run (Repeatable on my laptop, never happened in my desktop with the same OS environment)

**Comment by joaomoreno** [comment]
Can you show us a screenshot of that error?

Does it work if you reinstall VS Code?

**Comment by yingang** [comment]
Reinstallation doesn't help, never works on my laptop. Have used dependency walker to check the depends and looks like there is an expected version of dbghelp.dll in system32.

![code](https://cloud.githubusercontent.com/assets/1246410/22957685/e623836e-f364-11e6-9048-aa0dbe7f4e4f.png)

sorry it's in Chinese.

**Comment by joaomoreno** [comment]
This is very likely an anti-virus issue. Does it work if you disable your anti virus? What if you reinstall Code while the anti virus is disabled?

**Comment by yingang** [comment]
Yes, we have a few security softwares (including anti virus software) installed but I don't have privilege to disable them since it's a company-wide policy.
The same policy applies to my desktop PC also and this issues doesn't happen there, so I suppose it's most likely not related with that?

**Comment by joaomoreno** [comment]
Can you try [downloading the ZIP release](https://code.visualstudio.com/), see whether it works?

**Comment by yingang** [comment]
just tried the zip version, still the same problem:(

// Thanks anyway!

**Comment by joaomoreno** [comment]
Something must be broken in your system with `dbghelp.dll`. 😢
