### ISSUE TITLE
Quick Fix: Keyboard shortcut CTRL+. shows a small 'e'

### ISSUE THREAD

**Issue by YordanPavlov** [microsoft/vscode#205947]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.86.2 and 1.87.0-insiders
- OS Version: `Linux 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

Steps to Reproduce:

1. Press Ctrl + .  (quick fix shortcut)
2. A small 'e' letter is inserted at the cursor position. Pressing Ctrl + . again would remove it

The problem I observe is exactly the one described here:

https://github.com/microsoft/vscode/issues/135084

I am seeing the problem with VSCode build , also with VS code insiders 1.87.0-insiders. The problem persists with all extensions disabled on both builds.

**Comment by manor1911** [comment]
Seems to be related to Ubuntu. See https://askubuntu.com/questions/1370022/ubuntu-21-10-keyboard-shortcut-ctrl-changed-how-to-disable-or-change

**Comment by justschen** [comment]
that's kind of interesting, but will close as this isn't a vs code issue anymore! thanks @manor1911
