### ISSUE TITLE
CUDA

### ISSUE THREAD

**Issue by sursu** [Microsoft/vscode#20593]
Can you please make it possible to create .cu files (with syntax highlighting, etc).
Thank you.  

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.1|

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Did you know we have a pretty big [extension Marketplace](https://marketplace.visualstudio.com/?VScode=1)? This sounds like a great [new extension](http://code.visualstudio.com/docs/extensions/overview) idea!

**Comment by sursu** [comment]
Hi, Joao
I did not know. I am very very new to VS Code. 
Do you think I can expect the extension to be available soon?

**Comment by joaomoreno** [comment]
You can actually make it yourself. 👍
