### ISSUE TITLE
Disable markdown formatting in showInformationMessage by default

### ISSUE THREAD

**Issue by hatroman** [Microsoft/vscode#20595]
I've found an open issue (https://github.com/Microsoft/vscode/issues/6087) about markdown in show*Message. And I assume that this functionality is not implemented yet. But if I try to show message with `__`(double underscore), for example `abc__def`, underscore characters will be lost and the rest of the text will be italic. I have not found how to disable this type of formatting

- VSCode Version: 1.9.1
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. just try `window.showInformationMessage('abc__def');`
2. and you'll get abcdef, but `def` in italic

**Comment by bpasero** [comment]
I was not aware we support markdown in the message API.

**Comment by jrieken** [comment]
this is the message service: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/message/browser/messageList.ts#L274

**Comment by bpasero** [comment]
@hatroman we support a subset of formatting for messages, not full markdown:
* `*` to turn into bold
* `_` to turn into italics
* `[` and `]` to mark links inside the message

You can prefix with `\\` to escape.

**Comment by hatroman** [comment]
it would be better if i could choose. Sometimes I have calculated value for message and don't now what kind of symbols it contains. Now I will have to escape every time each message. 😞

**Comment by bpasero** [comment]
That would require new API for extensions and the default cannot be that we disable this formatting, otherwise we break existing extensions.

**Comment by hatroman** [comment]
👌  thanks anyway

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/20595#issuecomment-281243478 - we should measure how often that actually happens. We never really documented this and the deal is then that we try to see how is using it, inform them, and change it.
