### ISSUE TITLE
Extensions Sidebar Empty on Opening VS Code Insiders

### ISSUE THREAD

**Issue by shawpei8** [microsoft/vscode#205967]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Insiders Version: 1.87.0-insider (user setup)
- OS Version: Windows NT x64 10.0.22635

**Description**: In the latest VS Code Insiders build, when I open the application, the Extensions sidebar fails to display any content. This issue persists across restarts of the application and occurs without any user interaction beyond opening the sidebar.

Steps to Reproduce:
1. Open VS Code Insiders.
2. Click on the Extensions icon in the Activity Bar to view installed extensions.
3. Observe that the sidebar opens but does not display any content.

**Expected Behavior**: The Extensions sidebar should display a list of installed extensions along with options to browse and install new extensions.

**Actual Behavior**: The Extensions sidebar is completely empty, showing no installed extensions or any options to browse the marketplace.

**Screenshots**
![recording](https://github.com/microsoft/vscode/assets/69071727/169be689-11a0-4ee2-8002-647e2519d77e)
```[tasklist]
### Tasks
```

**Comment by shawpei8** [comment]
![image](https://github.com/microsoft/vscode/assets/69071727/b597b40a-99d3-473f-9092-356c4c393dd0)

**Comment by sandy081** [comment]
Can you please share the following log

- F1 > Open View... > Shared

**Comment by shawpei8** [comment]
Thank you for your comment. The problem was solved after I upgraded to the latest version.
