### ISSUE TITLE
Debug adapter client sends "evaluate" request for watch variable after sending "continue" request

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#20597]
- VSCode Version: 1.8, 1.9
- OS Version: Windows 10

Steps to Reproduce:

1. Install PowerShell extension
2. Save this script into a .ps1 file

```powershell
$abcdef = 1
while ($abcdef -le 50)
{
Start-Sleep -Milliseconds 2000
$abcdef = $abcdef + 1
}
```

3. Set a breakpoint on lines 1 and 5 and run the script
4. When breakpoint on line 1 gets hit, set a watch for `$abcdef`
5. Hit continue
6. Debugger now hangs

For some reason, the debugger client is sending an `evaluate` request for the `$abcdef` watch variable after the `continue` request is sent and its response is received.  This seems like a bug to me.  Here's what I see in the PowerShell extension logs:

```

2/13/2017 5:07:31 PM [VERBOSE] - Method "ReadMessage" at line 111 of C:\Users\kborle\Source\Repos\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "command": "continue",
      "arguments": {
        "threadId": 1
      },
      "type": "request",
      "seq": 14
    }

2/13/2017 5:07:31 PM [VERBOSE] - Method "WriteMessage" at line 59 of C:\Users\kborle\Source\Repos\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "response",
      "request_seq": 14,
      "command": "continue",
      "success": true,
      "body": null
    }

2/13/2017 5:07:31 PM [VERBOSE] - Method "OnDebuggerStop" at line 1482 of C:\Users\kborle\Source\Repos\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Received debugger resume action Continue

2/13/2017 5:07:31 PM [VERBOSE] - Method "ReadMessage" at line 111 of C:\Users\kborle\Source\Repos\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "command": "evaluate",
      "arguments": {
        "expression": "$abcdef",
        "context": "watch"
      },
      "type": "request",
      "seq": 15
    }
```

The hang is ultimately our fault, but it's happening because we're getting the `evaluate` request at an unexpected moment.

/cc @kapilmb

**Comment by weinand** [comment]
Yep, the evaluate should not come after the continue.

**Comment by daviwil** [comment]
I also found this issue from last November: https://github.com/Microsoft/vscode/issues/14843.  If this ever gets added, I'd recommend allowing a language to opt out of runtime watch evaluation because some won't be able to support it.

**Comment by isidorn** [comment]
We currently always evaluate watch expression on a change of a focussed stack frame, due to that we also evaluate when a user continues - since there is no longer a focussed stack frame and all watch should update. You could argue that this case we should treat specaially and not send the evaluate call but simply null out the watch expressions - however some adapters could support runtime evaluation.
The cleanest solution from my point of view is that the adapter simply protects itself against evaluation calls while it is not being stopped. This gives to flexiility to other adapters to support runtime evaluation.

**Comment by daviwil** [comment]
I noticed in Friday's Insiders build that I'm no longer seeing `evaluate` requests for watch variables be sent after the debugger is resumed.  Has something changed in this behavior?  In my opinion this is a positive change, but I wanted to make sure that it was intended :)

**Comment by isidorn** [comment]
It was intended :)
Part of https://github.com/Microsoft/vscode/issues/21524

**Comment by daviwil** [comment]
Awesome, thanks for confirming!
