### ISSUE TITLE
Copilot Chat - Enable navigating through prompts when chatting with an agent

### ISSUE THREAD

**Issue by charris-msft** [microsoft/vscode#205904]
If I'm not chatting with an agent, (no @[agentname] in the chat box) then I can use the up and down arrows to navigate through previous prompts I've typed. I LOVE this! Please don't change it.

However, if am chatting with an agent, I lose this ability regardless of whether I type the agent's name, or if it is persisted from the previous prompt.

What I expect is 
- if I type the agent's name I should be able to navigate through previous prompts _with the agent_. 
- if the agent's name persisted, then I could see navigating through all previous prompts, or just those with the agent. I'd check to see what customers expect.

**Comment by roblourens** [comment]
Yes, I'd like to rework input history to support this, but a few aspects of it are complicated...

**Comment by roblourens** [comment]
Tracking this in https://github.com/microsoft/vscode-copilot-release/issues/1208
