### ISSUE TITLE
files.readonlyInclude impossible to set to specific path

### ISSUE THREAD

**Issue by mgzenitech** [microsoft/vscode#206048]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. create package.0.json and a/b/c/d/package.0.json files in workspace
2. set config:
```json
  "files.readonlyInclude": {
    "**/package.*.json": true
  }
```
3. observe that both of the files became readonly, not only TOP LEVEL one.

I know that you can 
```json
  "files.readonlyInclude": {
    "**/package.*.json": true
  },
  "files.readonlyExclude": {
    "**/a/b/c/d/package.*.json": true
  }
```
but that is unacceptable as it means for every new file created in every folder I'll have to add exclusion. What we need here is either **support for variable expansion**, like `${workspaceFolder}` or make it **work like .gitignore does it** with slash prefix meaning `root` of the workspace.

P.S>
I've also tried:
`"/package.*.json": true`
`"./package.*.json": true`

none of them worked

**Comment by bpasero** [comment]
Can you not use `"*/**/package.*.json": true` ?

**Comment by mgzenitech** [comment]
> Can you not use `"*/**/package.*.json": true` ?

this will set this file also to readonly?
`a/b/c/d/package.0.json`

I need only TOP LEVEL package.0.json to be set to readonly (irrelevant to other package.0.json existing in workspace).

**Comment by bpasero** [comment]
Then why not:

```json
"files.readonlyInclude": {
    "package.*.json": true
}
```

**Comment by mgzenitech** [comment]
you are right! Holly molly, I though that without any prefix wildcards `package.*.json` is the same as `**/package.*.json` in vscode. Wrong expectations, I guess. Thanks @bpasero !
