### ISSUE TITLE
inline completions hover shows in unexpected location

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#206023]
Unfortunately, not sure how I ended up in this state.

![Image](https://github.com/microsoft/vscode/assets/29464607/33350673-cd15-497f-a7a0-880d4b8ef794)

**Comment by hediet** [comment]
Did the dev tool logs show anything?

**Comment by hediet** [comment]
Did you enable "always show toolbar"?

The inline suggestion feature does not position the hover, so I'm a bit clueless what causes this

**Comment by aiday-mar** [comment]
Hi @meganrogge if you see this again, could you please post here the file or a link to the file you were working on, as well as the code you were typing when the error happened and the inline completions you saw in the editor? A GIF would also be really helpful.

**Comment by meganrogge** [comment]
Yes I have `editor.inlineSuggest.showToolbar: always`

**Comment by hediet** [comment]
> editor.inlineSuggest.showToolbar: always

Then it actually might be caused by https://github.com/microsoft/vscode/issues/206021

**Comment by rzhao271** [comment]
Moving the issue to March for now. Feel free to move the issue back to February if it turns out to be a candidate.

**Comment by rzhao271** [comment]
Marking as candidate for now assuming the regression was caused by #206021.

**Comment by aiday-mar** [comment]
Hi @meganrogge have you seen this error recently? This issue may have been fixed recently when https://github.com/microsoft/vscode/issues/206021 was fixed.

**Comment by meganrogge** [comment]
I saw this about a week and a half ago. I'll let you know if it happens again.

**Comment by aiday-mar** [comment]
Hi Megan I believe since March we have done some improvements. Do you still see this issue? If not, I will close this issue.

**Comment by meganrogge** [comment]
Good with me to close and I will reopen if I see it again 👍🏼
