### ISSUE TITLE
goto definition with JavaScript class methods

### ISSUE THREAD

**Issue by arackaf** [Microsoft/vscode#20605]
It looks like goto definition does not work with JavaScript class methods

```
let s = new SupportStaff();
s.takeSnapshot();
```

Putting the cursor on `takeSnapshot` and hitting f12 does not do anything.  Am I missing a configuration setting somewhere?

**Comment by mjbvz** [comment]
What is the type of `s` when you hover over it?

**Comment by arackaf** [comment]
@mjbvz - `any` :(

Also, this isn't TypeScript, it should be JavaScript.  The file is .es6 because of our transpilation process, but I do have

```
"files.associations": {
        "*.js": "javascriptreact",
        "*.es6": "javascriptreact"   
    },
```

**Comment by mjbvz** [comment]
If the type is `any`, we don't have any type info for it and so cannot provide proper intellisense. Can you please share a more complete example that has the definition of `SupportStaff` as well?

**Comment by arackaf** [comment]
@mjbvz I may be missing something.

```
let s = new SupportStaff();
s.takeSnapshot();
```

where `SupportStaff` is defined in the same file.  In fact, I can click on `SupportStaff` in that line, hit f12, and zip right up to that class definition.  So I'm confused why Code isn't able to see what type s is assigned to, and know where to look for takeSnaptop.

**Comment by mjbvz** [comment]
Can you please share the definition of `SupportStaff` (or a minimal repo)? We can't understand all JavaScript class patterns, and you may be running into one of these limitations

**Comment by arackaf** [comment]
@mjbvz - ah!  Very good - it looks like this _does_ work with a simpler class.  I assume the problem is one of the decorators?

The simpler class I tested keeps working even with decorators and decorated class properties, so I'm not sure where things break down exactly :( 

```
@mappable
class SupportStaff {
    @observable isAdmin = '';
    @observable.ref savedSnapshot = null;
    id = '';
    contactId = '';
    firstName = '';
    fullName = '';
    email = '';
    @observable saving = false;
    @observable expanded = false;
    @action toggleExpanded = () => this.expanded = !this.expanded;
    
    @action toggleIsAdmin = val => this.isAdmin = val === 'true' ? true : false;

    @computed get isAdminRadio(){ return this.isAdmin ? 'true' : 'false' }
    set isAdminRadio(val) { this.isAdmin = val === 'true' ? true : false }

    constructor(resp, modulesExtension, ticketTypeExtension){
        extendObservable(this, modulesExtension);
        extendObservable(this, ticketTypeExtension);
        this.mapResponse(resp);
        this.takeSnapshot();
    }

    takeSnapshot(){
        this.savedSnapshot = Object.assign({}, toJS(this));
    }
}
```

**Comment by mjbvz** [comment]
Thanks. You may be running into this issue: 

https://github.com/Microsoft/TypeScript/issues/13032

TypeScript currently does not understand `new` calls that do not match number of arguments for a class's `constructor`.  After adding fake arguments like so `new SupportStaff(1, 2, 3)`, I see the correct suggestions using your example class.

Could this be the case?

**Comment by arackaf** [comment]
@mjbvz entirely likely - thanks for looking into it!

**Comment by mjbvz** [comment]
Ok, thanks for the follow up. Closing as upstream. We're working with the TypeScript team to improve support for these cases

**Comment by arackaf** [comment]
Sounds good - thanks for the great work!
