### ISSUE TITLE
Native and custom hover on kernel button

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#206006]
Repro

1. Create notebook
2. Try run a python cell
3. Select install kernel
4. Hover button

<img width="483" alt="Screenshot 2024-02-22 at 09 57 31" src="https://github.com/microsoft/vscode/assets/2193314/2375509f-88e0-4911-8225-313bba60e89b">

**Comment by rebornix** [comment]
@benibenj any suggestion?

**Comment by rebornix** [comment]
I put it in Feb milestone as it's a regression.

**Comment by aiday-mar** [comment]
Since @benibenj mentioned this issue is fixed, I will close this issue, so it can enter the pool of `verifiable fixes`.
