### ISSUE TITLE
Word-wrap not working for git diffs?

### ISSUE THREAD

**Issue by noodlefrenzy** [Microsoft/vscode#20606]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.8|
|csharp|ms-vscode|1.7.0|
|Spell|seanmcbreen|0.9.1|

---

Steps to Reproduce:

1. Git diff a markdown file with long lines
2. Attempt to toggle word-wrap
3. Cry bitter tears, gnash teeth

**Comment by Bill-Stewart** [comment]
Already asked and answered (search issues for "wrap").

**Comment by noodlefrenzy** [comment]
I was afraid of that. Clicking the magic "submit bug" button took me to open an issue. I should have searched issues before opening a new one. My bad. Closing.
