### ISSUE TITLE
PWA title bar bugs

### ISSUE THREAD

**Issue by Malix-Labs** [microsoft/vscode#206015]
Does this issue occur when all extensions are disabled?: Yes

## Problems

**The PWA title bars have multiples bug**

- On https://vscode.dev:
	- When window is maximized: its elements disappear on collapse
	- When hiding "menu bar": "menu bar" cannot be shown until full reload (broken)
	- Here is a recording of those two behaviors:
		![Screen recording 2024-02-22 20 05 59](https://github.com/microsoft/vscode/assets/76160668/fb7e12bd-e1ed-4289-81c8-341fce2832c0)
- On https://github.dev and **codespaces**
	- Title bar toggle doesn't exist (problem in the https://github.dev PWA manifest), so the title bar is locked expanded (so it takes double the size)

## Versions

- VS Code Version: 
	- Version: 1.86.2
	- Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
	- Date: 2024-02-13T19:42:42.858Z
	- Browser: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
- OS Version: ChromeOS (Flex) Version 122.0.6261.35 (Official Build) beta (64-bit)
- Browser Version: Google Chrome Version 123.0.6312.4 (Official Build) beta-lacros (64-bit)

## Reproduce

1. Go to https://vscode.dev
2. Download and Open the PWA
3. Test the window maximized bug
	1. Ensure that Window is minimized
	2. Verify that the title bar is correctly displayed
	3. Maximize the window
	4. Verify that the title bar is broken
4. Test the hiding "menu bar" bug
	1. Window maximized / minimized doesn't make a difference
	2. Verify that the title bar is correctly displayed
	2. Hide the "menu bar" (option available after clicking on the "Customize Layout" button)
	3. Show the "menu bar" again
	2. Verify that the title bar is broken
5. Go to https://github.dev
6. Download and Open the PWA
7. Verify that the title bar toggle doesn't exist

**Comment by bpasero** [comment]
@Malix-off can you test again with https://insiders.vscode.dev/ and see if it still reproduces.

**Comment by Malix-off** [comment]
- [Comment](https://github.com/microsoft/vscode/issues/206015#issuecomment-2078852426) from @bpasero :

  > @Malix-off can you test again with [insiders.vscode.dev](https://insiders.vscode.dev/) and see if it still reproduces.

  Hello @bpasero!
  Yes, the same things happen
