### ISSUE TITLE
Debugger hangs on break points in PowerShell code

### ISSUE THREAD

**Issue by wmc777** [Microsoft/vscode#20608]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|azuretoolsforvscode|bradygaster|1.2.1|
|PowerShell|ms-vscode|0.9.0|
|azurerm-vscode-tools|msazurermtools|0.3.4|

---

Steps to Reproduce:

1. Set a break point 
2. Press F10 to step the break point
3. The debugger hangs and Code must be restarted

1. Set a break point on a different line than the one that caused the debugger to hang.
2. Press F10 to step the break point
3. The debugger hangs and Code must be restarted

The same PowerShell code runs fine if there is not break points set.

**Comment by weinand** [comment]
This issue was moved to PowerShell/vscode-powershell#506

**Comment by weinand** [comment]
This is a PowerShell extension issue. Moving to the correct repo.

**Comment by wmc777** [comment]
Thanks!
