### ISSUE TITLE
No UI to t re-open git submodule

### ISSUE THREAD

**Issue by Shaka0723** [microsoft/vscode#206034]
after I close a git repository (usually a submodule), there is not anywhere to re-open it.

**Comment by Shaka0723** [comment]
forget it. I find a git cmd to reopen submodules.
![image](https://github.com/microsoft/vscode/assets/56809930/e66431df-e3cc-462e-b742-868245d66304)

**Comment by gjsjohnmurray** [comment]
I think this can be done from Command Palette, and #197466 says the upcoming release adds UI.
