### ISSUE TITLE
Stick scroll in embedded editor rendering issue with material theme

### ISSUE THREAD

**Issue by zyd2001** [microsoft/vscode#206025]
Type: <b>Bug</b>

When using material theme, use go to reference with some value.
The sticky part in the embedded editor is transparent. I tried with several color schemes, the problem only appears with Material Theme.

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.93GB (1.89GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/home/zyd/research/MSP430/llvm-RegionFormation --crash-reporter-id 97f44205-6f73-4788-9872-652c9d47b07f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 3800)|
|Memory (System)|15.58GB (6.77GB free)|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.1.4
Bookmarks|ale|13.4.2
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.5.0
vscode-ptx-syntax|gka|1.0.0
llvm-tablegen|jak|0.0.2
better-cpp-syntax|jef|1.17.2
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.338.1
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
remote-explorer|ms-|0.4.1
multi-command|ryu|1.6.0
vim|vsc|1.27.2
material-theme|zhu|3.16.2
gitlens|eam|14.8.2
todo-tree|Gru|0.0.226
latex-workshop|Jam|9.18.2
vscode-latex|mat|1.3.0
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.85.2024021409
debugpy|ms-|2024.0.0
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.1.1
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.17.16
cpptools|ms-|1.19.4
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.14
makefile-tools|ms-|0.8.22
vsliveshare|ms-|1.0.5905
java|red|1.28.1
cmake|twx|0.0.17
vscode-ltex|val|13.1.0
learn-vim|vin|0.0.28
vscode-java-debug|vsc|0.56.1
vscode-java-dependency|vsc|0.23.4
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0
lldb-dap|llv|0.1.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30968132
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
edj9j583:30969295
fegfb526:30961430
7j2b6412:30969109
e3gdj431:30958358
ccp2r3:30958157

```

</details>

**Comment by zyd2001** [comment]
Here are the screenshots with material theme and default colorscheme.
![image](https://github.com/microsoft/vscode/assets/25120292/0897267f-5c69-4afa-aa1e-e6f8b2a237b4)
![image](https://github.com/microsoft/vscode/assets/25120292/3e0cfd5a-ef1c-4592-8ce0-6744ee57e93d)

By the way, is it possible to have an option to disable the sticky scroll only in embedded editor, since the window is rather small and multiple nested scope really takes too much space in the small window.

**Comment by gjsjohnmurray** [comment]
I suggest you report the transparency issue to the theme author.

**Comment by aiday-mar** [comment]
Hi @zyd2001, as @gjsjohnmurray mentioned, this is happening likely because the theme authors have specified the color of that div to be transparent. You may directly file the issue to them. This issue will be closed.

**Comment by zyd2001** [comment]
I think my issue is quite similar to #201784, and it seems like it is not just an extension issue.

**Comment by aiday-mar** [comment]
The color inside of the peek view is set by the following color which has been recently added to VS Code. Please add the following to your settings, to change the color of the peek view sticky scroll:

```
 "workbench.colorCustomizations": {
    "peekViewEditorStickyScroll.background": "#ba7798"
  },
```

The other issue's second part is also caused by the specific extension at hand. I will comment on that issue.
