### ISSUE TITLE
Increase minimum limit for fontSize and lineHeight

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#20602]
- VSCode Version: 1.10.0-insider
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open settings.json.
2. Enter without saving: `"editor.fontSize": 1` and wait.
3. Small font size is applied.

I would expect to have a font size lower bound when font size is applied dynamically without saving, or asking for confirmation on small font size. The user can enter number "1" and then have a think for another several seconds before deciding on second digit for the size.

UPDATE:
"files.autoSave": "afterDelay" has to be set. Thanks to @joaomoreno comment.

**Comment by joaomoreno** [comment]
It's not that you didn't save, but you have auto save enabled after a certain timeout. Hence, the _wait_ part.

**Comment by alexandrudima** [comment]
The limit is today 0 or something like that. Perhaps it should be 5 or something.

**Comment by PoiSoNz** [comment]
Hi, I believe this issue has been solved already, with the current minimum fontSize and lineHeight limit set to 8, on [fontInfo](https://github.com/Microsoft/vscode/blob/0ae072e1fa9982950825ed7bafdc83465849b104/src/vs/editor/common/config/fontInfo.ts#L77) . 
Do you mind if I set a constant for both minimum fontSize and lineHeight for better code understanding?
It would take a big part in a school assignment.
