### ISSUE TITLE
Intellisense steering of Copilot suggestions

### ISSUE THREAD

**Issue by JBG-SY** [microsoft/vscode#206067]
After reading/seeing this
https://devblogs.microsoft.com/visualstudio/github-copilot-visual-studio-intellisense/
https://www.youtube.com/watch?v=vK4gcXIJJ0s

I would kindly request that we in Visual Studio Code get the same kind of intellisense steering of Copilot suggestions as shown working in Visual Studio.

**Comment by JBG-SY** [comment]
Not sure if relevant, but i wanna add this image
![image](https://github.com/microsoft/vscode/assets/142312679/33c78ae6-e278-4efc-bfb3-cccab83a0aaf)

**Comment by JBG-SY** [comment]
Any updates? Hopefully, this request has not been forgotten. If you have any questions, please let me know.

**Comment by guldmand** [comment]
.... ?

**Comment by isidorn** [comment]
This should just work in VS Code.
If it does not work, can you provide a simple reproducible sample showing it does not work?

**Comment by JBG-SY** [comment]
@isidorn 

To my knowledge you cannnot steer the intellisence dropdown with copilot suggestion in VSCode like shown in the video
_No vscode version i have used has had it like it shows in the video_

Do this steering work in your vscode?

**Comment by JBG-SY** [comment]
@vs-code-engineering comeon bot, its the summer vaction
