### ISSUE TITLE
Breakpoint madness in wrapped line

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#20601]
![image](https://cloud.githubusercontent.com/assets/22350/22938248/84db067e-f2db-11e6-963c-3d7c2ff52d8b.png)

**Comment by isidorn** [comment]
Had to revert the fix due to #20688 
I checked the editor API and my use case is not supported - namely to have a decoration that spans the whole line (which can be wrapped in multiple lines) but that the glyph margin is only decorated on the first line.

@rebornix @alexandrudima would it be possible to add an option in the decoration API to only show the glyph margin on the first view line even if the line spans multiple view lines?

**Comment by isidorn** [comment]
This is Sparta?

**Comment by isidorn** [comment]
Friendly ping @alexandrudima would it be possible to add an option in the decoration API to only show the glyph margin on the first view line even if the line spans multiple view lines?

**Comment by joaomoreno** [comment]
Similar: https://github.com/Microsoft/vscode/issues/37249

**Comment by alexandrudima** [comment]
@isidorn I've seen breakpoints are created on the whole line today (from column 1 to infinity).

I wonder if breakpoints don't belong "on the first non-whitespace character of a line" as a closer approximation to the concept of a statement than the entire line.

---

@joaomoreno I thought you [never write code that goes over 80 chars](https://github.com/Microsoft/vscode/issues/36479#issuecomment-340301936), how could you have hit this :)
> I never hit it, cause all my code lines are under 80 characters! 🥇

**Comment by isidorn** [comment]
@alexandrudima thanks for the suggestoin, after some refactoring this actually seems to be working fine.
As you suggested I changed that the breakpoint is set on the first non whitespace character of the line. I do not treat specially the case when the line gets deleted, but I just update the decoration range as the editor tells me. Luckily I already have a de-duping mechanism in my model that takes care of the case when the whole file gets deleted and all the breakpoints get set to the first line and column

**Comment by joaomoreno** [comment]
@alexandrudima You either crafter the most powerful GitHub issue search query to find that one or you were saving it for REVENGE.

![gif](https://media.giphy.com/media/K2ShlbUvGgD2E/giphy.gif)
