### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by jorge-a-g** [microsoft/vscode#206071]
Type: <b>Bug</b>

In the Terminal menu there is a spelling error. Where you type "Rreiniciar..." you should type "Reiniciar tarea en ejecución..."

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:41:37.860Z)
OS version: Linux x64 6.5.0-18-generic
Modes:

**Comment by meganrogge** [comment]
a screenshot would help
