### ISSUE TITLE
debug.startDebugging API should return the launched session instead of a boolean

### ISSUE THREAD

**Issue by ferenj-gs** [microsoft/vscode#206081]
Hey,
I'm adding a listener to a custom debug session to execute some logic when the session ends, and I get the launched session by accessing `vscode.debug.activeDebugSession` in the continuation function of the `startDebugSession` returned promise, which feels a little bit brittle to me as what if there are multiple debug session launched in an interleaved way, I don't see how that invariant is enforced that `vscode.debug.activeDebugSession`  is the actual session that was created by a given `startDebugSession`.

The current API signature:
```typescript
export function startDebugging(folder: WorkspaceFolder | undefined, nameOrConfiguration: string | DebugConfiguration, parentSessionOrOptions?: DebugSession | DebugSessionOptions): Thenable<boolean>;
```

Proposed API:
```typescript
export function startDebugging(folder: WorkspaceFolder | undefined, nameOrConfiguration: string | DebugConfiguration, parentSessionOrOptions?: DebugSession | DebugSessionOptions): Thenable<DebugSession|undefined>;
```
And the semantics could be that in case of a launch failure the Promise resolves to undefined.

Thanks & BR,
Ferenc

**Comment by ferenj-gs** [comment]
Hey,
I'm trying add a listener to a custom debug session, and I get the launched session by accessing `vscode.debug.activeDebugSession` in the continuation function of the `startDebugSession, which feels a little bit brittle to me as what if there are multiple debug session launched in an interleaved way, I don't see how that invariant is enforced that `vscode.debug.activeDebugSession`  is the actual session that was created by a given `startDebugSession`.

The current API signature:
```typescript
export function startDebugging(folder: WorkspaceFolder | undefined, nameOrConfiguration: string | DebugConfiguration, parentSessionOrOptions?: DebugSession | DebugSessionOptions): Thenable<boolean>;
```

Proposed API:
```typescript
export function startDebugging(folder: WorkspaceFolder | undefined, nameOrConfiguration: string | DebugConfiguration, parentSessionOrOptions?: DebugSession | DebugSessionOptions): Thenable<DebugSession|undefined>;
```
And the semantics could be that in case of a launch failure the Promise resolves to undefined.

Thanks & BR,
Ferenc

**Comment by roblourens** [comment]
Discussed in https://github.com/microsoft/vscode/issues/135407, there is a workaround for you
