### ISSUE TITLE
Transparent headers in go to references

### ISSUE THREAD

**Issue by luan-xiaokun** [microsoft/vscode#206047]
Type: <b>Bug</b>

A minimal example:

```python
def f():
    pass


class A:
    def g():
        pass
        pass
        pass
        pass
        f()


def h():
    pass
    pass
    pass
    pass
    pass
    f()
```

Ctrl click on the definiton of `f`, and go for the references in `g` and `h`, the sticky headers are transparent.

Expected behavior: I assume that these headers are not supposed to be transparent.

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:41:37.860Z)
OS version: Linux x64 5.15.0-97-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7840H with Radeon 780M Graphics (16 x 3263)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|30.04GB (24.50GB free)|
|Process Argv|. --crash-reporter-id fe979417-a4cd-4478-9827-6690e13c3c88|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
vscode-lark|dir|0.1.0
gitlens|eam|14.8.2
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|34.3.1
copilot|Git|1.165.0
copilot-chat|Git|0.12.2
todo-tree|Gru|0.0.226
latex-workshop|Jam|9.18.2
rainbow-csv|mec|3.11.0
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.85.2024021409
black-formatter|ms-|2024.0.1
debugpy|ms-|2024.0.0
isort|ms-|2023.10.1
pylint|ms-|2023.10.1
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
vscode-jupyter-cell-tags|ms-|0.1.8
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
remote-explorer|ms-|0.4.1
material-icon-theme|PKi|4.34.0
code-spell-checker|str|3.0.1
even-better-toml|tam|0.19.2
vscode-wakatime|Wak|24.4.0
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
edj9j583:30969295
a89i1917:30961429
7j2b6412:30969109
ccp1r3:30958155

```

</details>

**Comment by aiday-mar** [comment]
Hi could you please provide an image or even better a GIF showing the issue you are seeing? Thank you.

**Comment by luan-xiaokun** [comment]
Thanks for the quick response, here is what I got.

![Peek 2024-02-23 18-40](https://github.com/microsoft/vscode/assets/43921595/8c977c88-b0fd-4372-9b5a-3f87aba0c1c6)

**Comment by aiday-mar** [comment]
Hi @luan-xiaokun you may file this issue to the author of the theme you are using. The reason you see this is because the author of your theme has specified a transparent color or no color for the sticky scroll within the references editor. I will close this issue as it is outside of the scope of VS Code core.
