### ISSUE TITLE
What's happened with c-sharp language service?

### ISSUE THREAD

**Issue by reflectiondm** [Microsoft/vscode#2060]
My [extension](https://marketplace.visualstudio.com/items/reflectiondm.ClassyNaming) had a dependency to 'vscode.scharp' language as it is described [here] (https://github.com/Microsoft/vscode-docs/blob/master/docs/extensionAPI/extension-points.md#contributeslanguages). The reason this dependency was introduced was that it was impossible to contribute my own completion suffusions to C# completion list back then. Recently (probably with vscode 0.10.6 update) it suddenly stopped working. A quick investigation shown that the reason is the extension cannot reference 'vscode.csharp' anymore in its extensionDependencies list. I've removed it and extension start working as usual, and still can add its suggestions to c# completion list.
Were there any changes related to csharp language and its interaction with extensions? Everything is working now, but I would really like to know what happened.

**Comment by jrieken** [comment]
@reflectiondm Good catch ;-) The omnisharp extension has moved out of the VS Code source tree and will move into the omnisharp/dotnet org. Currently it is in transit which makes your situation a little harder. Sorry for that. Currently the name of the extension is `jrieken.vscode-omnisharp` but I am afraid it will change once more.
