### ISSUE TITLE
Scroll View Problem

### ISSUE THREAD

**Issue by HP-Harshil** [microsoft/vscode#206003]
Type: <b>Bug</b>

when largefile or large data is there, scroll view problems occurs in ubuntu it was not there earlier but before 2-3 update it started

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:41:37.860Z)
OS version: Linux x64 6.5.0-17-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2585)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.46GB (10.48GB free)|
|Process Argv|--unity-launch --crash-reporter-id fc0565cf-1ef4-4464-a7c1-eb3287e34676|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
a-file-icon-vscode|ato|1.2.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.8.2
prettier-vscode|esb|10.1.0
todo-tree|Gru|0.0.226
rainbow-csv|mec|3.11.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.0
black-formatter|ms-|2024.0.1
debugpy|ms-|2024.0.0
flake8|ms-|2023.10.0
python|ms-|2024.0.1
remote-containers|ms-|0.338.1
remote-wsl|ms-|0.86.0
live-server|ms-|0.4.13
material-icon-theme|PKi|4.34.0
vscode-thunder-client|ran|2.17.8
LiveServer|rit|5.7.9
material-theme|zhu|3.16.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
pydisww2:30959801
edj9j583:30969295
a89i1917:30961429
7j2b6412:30969109
bg6jg535:30958357

```

</details>

**Comment by Sanan4li** [comment]
Facing the same issue, I thought it was my mouse having issues but turns out it's VS Code. So the issue is when I am at line 45 and the cursor is there I come back to VS code and scroll down it scrolls down to more than 20 lines. This issue was not present a week ago.

**Comment by HP-Harshil** [comment]
![image](https://github.com/microsoft/vscode/assets/46664842/4712c424-82fa-41ba-822a-58cedd920d33)

you can check the above image while scrolling some of the above portions stuck(here you can see the image folder), and the same used to happen in the code editor window also

**Comment by justschen** [comment]
This is an intended feature called `sticky-scroll` from @aiday-mar ! (not sure if there is documentation on this yet). You can choose to disabled this by checking out the following settings

- editor: "editor.stickyScroll.scrollWithEditor": false
- workbench: "workbench.tree.enableStickyScroll": false
- adjust line length:  "editor.stickyScroll.maxLineCount": [`number here`]

**Comment by HP-Harshil** [comment]
ok thanks
