### ISSUE TITLE
Tree view hover delegate leaks

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#206090]
When I changed the hover delegate for treeview I forgot to `register` it [here](https://github.com/microsoft/vscode/blob/6ed2fd67daab0440aad1bed339aa126503701e2f/src/vs/workbench/browser/parts/views/treeView.ts#L1109).

**Comment by aiday-mar** [comment]
Reopening this issue because it is a candidate

**Comment by aiday-mar** [comment]
Approved and merged into release branch
