### ISSUE TITLE
`env.clipboard` support `onDidChangeText` event?

### ISSUE THREAD

**Issue by xianghongai** [microsoft/vscode#206058]
`env.clipboard` support `onDidChangeText` event?

Open the file in VS Code, select the characters to be copied, or select in column mode, and then perform the copy operation. At this time, I want to change the content before copying the content to the pasteboard, such as appending content or changing the naming style.

In other applications, pasting content, perhaps in column mode,…

--

env.clipboard 支持 onDidChangeText 事件？

在 VS Code 中打开文件，选择要复制的字符，或通过列模式选择，然后执行复制操作，这个时候，希望在复制内容到粘贴板之前，变更内容，如：追加内容，或者变更命名风格。

在其它应用程序中，粘贴内容，可能是列模式，…

**Comment by mjbvz** [comment]
The proposed document paste api should let you change some. Specifically 

https://github.com/microsoft/vscode/blob/9aecd9794a321df396b8edc3546ce038d370782b/src/vscode-dts/vscode.proposed.documentPaste.d.ts#L63

However for now any changes to the clipboard are only visible in VS Code and not other applications
