### ISSUE TITLE
De-dupe links in the open detected link quick pick

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#206124]
Notice how links starting with " and without are both included as file links, only one of these should be shown:

![image](https://github.com/microsoft/vscode/assets/2193314/9d9250e7-7f53-49aa-9b15-dc541dd655b9)

<img width="420" alt="Screenshot 2024-02-23 at 12 10 01" src="https://github.com/microsoft/vscode/assets/2193314/8955fcfc-3f96-4497-a01d-96c50060b7c4">

**Comment by Tyriar** [comment]
Repro:

1. Open vscode repo
2. Run `echo "./yarn.lock, line 234"`
3. Ctrl+shift+o in terminal

Since the links are next to each other, the duplicate should just be skipped.

**Comment by rzhao271** [comment]
Reopening because there are still duplicates.

![Duplicates shown in the links to open quick pick](https://github.com/microsoft/vscode/assets/7199958/bcd457fe-7749-45ce-8c9a-662908e26cab)
