### ISSUE TITLE
./scripts/test.sh requires ./scripts/code.sh to be run first

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#20612]
In the course of debugging https://github.com/Microsoft/vscode/issues/20344 I discovered that `./scripts/test.sh` will immediately exit with no output if `./scripts/code.sh` has not first been run.

Reproduce:
1. Fresh checkout of vscode
2. `./scripts/npm.sh install`
3. `npm run watch`
4. `./scripts/test.sh`

`./scripts/test.sh` stops executing at this line:
```
INSTALLED_VERSION=`cat .build/electron/version 2> /dev/null`
```

If I run `cat .build/electron/version` myself, the output is this:

```
$ cat .build/electron/version
cat: .build/electron/version: No such file or directory
```

Workaround:
- Run `./scripts/code.sh` before running `./scripts/test.sh`

Ideal behavior:
- It would be nice if `./scripts/test.sh` handled installing electron itself.

**Comment by joaomoreno** [comment]
I had seen this before, just never jumped on it. Thanks for the ping!

**Comment by nicksnyder** [comment]
Verified fix, thanks!
