### ISSUE TITLE
when navigating bw cells, indicate which cells are running in aria label

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#206125]
In the meeting with @jooyoungseo, Venkatesh suggested he'd like to know which cells are actively running when navigating with arrow keys.

Could we update the aria label to include "running" so that a user knows this?

**Comment by amunger** [comment]
verification steps:
1. create a notebook with cells that take some time to execute e.g.

```
import time
time.sleep(5)
print('done')
```

2. Run single and multiple cells at a time and move through the cell containers with the arrow keys as they change states.
3. Use a screen reader to verify that when the cells are running or pending, the aria label on the cell container 
reflects that state. When they complete, the label should return to the default
