### ISSUE TITLE
VSCode slows down the local razzle build of OS repo significantly

### ISSUE THREAD

**Issue by hiepkhuuMS** [microsoft/vscode#206136]
Whenever I have VSCode running with OS code files opened after some time, the razzle build window becomes slower. The moment I kill VSCode (or simply close all opened files), build is resuming fast immediately.

I already tried disabled all installed plugins earlier so I'm pretty sure it's not because of the plugins. It's definitely VSCode issue with opened files here.

The build on razzle command is stalled at the following point for 10+ mins

%sdxroot%\onecoreuap\net\rras\ip\nathlp>bz
BUILD: TARGETS: AMD64
BUILD: MODE: Generate Headers, Compile, Link, Post
BUILD: LOG: e:\os20\src\onecoreuap\net\rras\ip\nathlp\buildfre.log
BUILD: VERSION: 8.0.240213002
BUILD: Start time: Fri Feb 23 14:04:23 2024

3001>Merging config files
.....
BUILD: Elapsed time (Build complete) **[0:11:42.156]**

It could take longer if I didn't close those files. Normal build should only take 2 mins:
BUILD: Elapsed time (Build complete) **[0:02:58.390]**

**Comment by hiepkhuuMS** [comment]
Please feel free to let me know if you need any log collection, as I get a pretty consistent repro.

**Comment by deepak1556** [comment]
Do you still experience the issue with latest stable 1.96, if it does can you also try opening the files with https://vscode.dev/ to confirm the issue.
