### ISSUE TITLE
XHTML-style closing html tag should be scoped as tag end

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#20611]
- VSCode Version: Code - Insiders 1.10.0-insider (1d17b45a11d8db22fe95c601f793a3cb9a582ba6, 2017-02-14T09:43:26.020Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.4.3|
|sort-lines|Tyriar|1.2.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.11.0|
|project-manager|alefragnani|0.13.2|
|vscode-eslint|dbaeumer|1.2.6|
|python|donjayamanne|0.5.8|
|tslint|eg2|0.8.1|
|angular2|johnpapa|2.0.1|
|vscode-icon-theme|jtlowe|1.4.0|
|theme-karyfoundation-themes|karyfoundation|11.0.0|
|restructuredtext|lextudio|0.0.21|
|HTMLHint|mkaufman|0.3.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-stylefmt|mrmlnc|2.2.2|
|stylelint|shinnn|0.22.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|1.0.5|
|theme-tesla|smlombardi|6.0.0|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

When using a tag that still requires an XHTML-style unary closing tag `/>`, the `/` should be scoped to match the closing `>`.

As you can see, it's not, so all the `/` are white while all other `punctuation.definition.tag.end.html` are a different color:

![screen shot 2017-02-14 at 2 02 16 pm](https://cloud.githubusercontent.com/assets/835148/22944414/9f703918-f2be-11e6-81c6-84ee82d48361.png)

![screen shot 2017-02-14 at 2 02 41 pm](https://cloud.githubusercontent.com/assets/835148/22944419/a3414f78-f2be-11e6-91b3-55cea3b99b49.png)

**Comment by aeschli** [comment]
We use https://github.com/textmate/html.tmbundle as grammar. Please file the issue there.
