### ISSUE TITLE
Choose Application: Where is Electron?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode#20616]
- VSCode Version: 1.9.1 f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
- OS Version: macOS 10.12.3

I don't know how to reproduce this, but I'm writing Go code in VSCode (with vscode-go) and getting this pop up. If I say "Cancel" it goes away but comes back after a while. It doesn't crash anything either, just an annoyance. 

Any ideas what might be causing this?

![image](https://cloud.githubusercontent.com/assets/159209/22949659/de5ebc96-f2b7-11e6-8815-58d5fca2755e.png)

**Comment by joaomoreno** [comment]
Have you tried to completely remove VS Code and reinstall it?

**Comment by ahmetalpbalkan** [comment]
@joaomoreno why would I do that though? It's working.

**Comment by joaomoreno** [comment]
OK. How about running a newly downloaded VS Code? No need to uninstall the current version.

**Comment by ahmetalpbalkan** [comment]
Turns out this was causing by:

1. vscode does a git-fetch periodically (every few mins)
2. my github key has a password and it is not added to the `ssh-add`, so it prompts `ssh-askpass` provided by my company setup in a new window.
3. the `ssh-askpass` program tries to find the parent process of the caller (which happens to be `/Applications/Visual Studio Code.app/Contents/MacOS/Electron`) **to find its icon** (which prompts the macOS native popup in the initial report) so that it can show it here:

![image](https://cloud.githubusercontent.com/assets/159209/23234297/7afb007e-f906-11e6-92f7-a580523d500b.png)

pstree looks like this:

```
 |   |-+- 62372 ahmetb /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap /usr/local/bin/git /Users/ahmetb/workspace/gopath-[redacted-project-name]/src/github.com/ahmetalpbalkan/[redacted-project-name] utf8 /Applications/Visual Studio Code.app/Contents/MacOS/Electron 2.11.1
 |   | \-+- 64941 ahmetb /usr/local/bin/git fetch
 |   |   \-+- 64942 ahmetb /usr/local/bin/[redacted]-ssh git@github.com git-upload-pack 'ahmetalpbalkan/[redacted-project-name].git'
 |   |     \-+- 64964 ahmetb /bin/bash /usr/local/bin/[redacted]-ssh-askpass Enter passphrase for key '/Users/ahmetb/.ssh/github_rsa':
```

So I'm guessing it's related to my setup. We can close this.
