### ISSUE TITLE
C source build task output wrapped when using the same terminal more than once

### ISSUE THREAD

**Issue by Rosto75** [Microsoft/vscode#20618]
- VSCode Version: 1.9.1
- Extensions: C/C++ 0.10.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create buggy C source to force compiler warning/error messages. 
2. Use **VS Build Tools 2017 RC** and the following tasks.json file:
```json
{
  "version": "0.1.0",
  "echoCommand": true,
  "_runner": "terminal",
    "tasks": [
      {
      "taskName": "cl",
      "command": "cl.exe ${file}",
      "isShellCommand": true,
      "isBackground": false,
      "problemMatcher": "$msCompile",
      "isBuildCommand": true,
      "showOutput": "always"
      }
    ]
}
```
3. Build the source once. Compiler warnings are displayed correctly in one long line.
4. Without closing the terminal, build the source once again. Compiler warnings are now wrapped at column 87.
5. If you close the terminal and recompile, output will be fine again.

[https://youtu.be/8-Wmb-8LyRg](https://youtu.be/8-Wmb-8LyRg)

**Comment by Tyriar** [comment]
Verified by injecting this into ITerminalInstance:

```
		setTimeout(() => {
			this.reuseTerminal({
				name: 'test'
			});
		}, 5000);
```

And then running `ls` and ensuring the wrapping looks correct.
