### ISSUE TITLE
no automatic cs50 commits to github

### ISSUE THREAD

**Issue by jleung26** [microsoft/vscode#206148]
Previously, when I made changes in my CS50 codespace, it would automatically commit to a repository. However, it hasn't done that in over a month, and I don't want to lose all my work. 

Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
Please raise your issue with the course support channel.
