### ISSUE TITLE
Error: Invalid problemMatcher description for correct problemMatcher

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#20615]
- VSCode Version: 1.9.1 and 1.10.0-insiders

Given this defined task in tasks.json:
```json
		{
			"taskName": "watch",
			"command": "bash",
			"args": ["${workspaceRoot}/watch.sh"],
			"isBackground": true,
			"problemMatcher": {
				"pattern": "^[(.+)] (.+):\\[(\\d+),(\\d+)\\] (.*)$",
				"owner": "java",
				"fileLocation": "absolute"
			}
		}
```

which is correct according to https://code.visualstudio.com/docs/editor/tasks_appendix

trying to run it yields

```
Error: Invalid problemMatcher description. A matcher must at least define a pattern, owner and a file location. The problematic matcher is:
{
    "pattern": "^[(.+)] (.+):\\[(\\d+),(\\d+)\\] (.*)$",
    "owner": "java",
    "fileLocation": "relative"
}
```

error is logged here: https://sourcegraph.com/github.com/Microsoft/vscode@c342eaa22e172e1f51ef42860948e6a010fcfb1e/-/blob/src/vs/platform/markers/common/problemMatcher.ts#L766:1-767:1

**Comment by felixfbecker** [comment]
changing `pattern` to be `{"regexp": "...pattern..."}` works.

**Comment by pr-yemibedu** [comment]
Hello,
 The following line needs to be fixed:

https://github.com/Microsoft/vscode/blob/c342eaa22e172e1f51ef42860948e6a010fcfb1e/src/vs/platform/markers/common/problemMatcher.ts#L102
Thank you. Good day.

**Comment by dbaeumer** [comment]
@felixfbecker you can pass a string however this must be the name of a predefined problem matcher. Something like `$tsc`.

I agree that the error message is incorrect and needs to be fixed.

**Comment by felixfbecker** [comment]
@dbaeumer correct me if I'm wrong, but from the suggestions in IntelliSense and the docs I understand there are three possibilities:

1. use a built-in _problem matcher_
```json
"problemMatcher": "$tsc"
```
or _extend_ it:
```json
"problemMatcher": {
  "base": "$tsc",
  ...
}
```

3. Provide a custom problem matcher with a custom _pattern_, but default capture groups:
```json
"problemMatcher": {
  "pattern": "^...$",
  ...
}
```

4. Provide a custom problem matcher with a custom pattern with custom capture groups:
```json
"problemMatcher": {
  "pattern": {
    "regexp": "^...$",
    "severity": 1,
    "file": 2,
    "line": 3,
    "column": 4,
    "message": 5
  }
}
```

Option 3 does not work.

**Comment by dbaeumer** [comment]
The idea is that pattern can refer to a predefined pattern as well. At least my code looks like this: https://github.com/Microsoft/vscode/blob/master/src/vs/platform/markers/common/problemMatcher.ts#L862

Need to find out what is going wrong here.

**Comment by pr-yemibedu** [comment]
Hello,
 @dbaeumer is correct. The comments in the code state is could be a string of [the name of a predefined problem pattern](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/markers/common/problemMatcher.ts#L708), otherwise it needs to be an object of the form ProblemPattern.

 [Default patterns are here](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/markers/common/problemMatcher.ts#L395).

 That is also clearly stated the same in the tasks_appendix you provided. This is not an error in functionality. Please close as a bug and open as a feature request if you would like. Thank you. Good day.

**Comment by felixfbecker** [comment]
But what is `base` then for?

**Comment by pr-yemibedu** [comment]
Hello,
 It is literally in the comments on the appendix page:
/**
	 * The **name of a base problem matcher** to use. If specified the
	 * base problem matcher will be used as a template and properties
	 * specified here will replace properties of the base problem
	 * matcher
	 */

So you can have a custom matcher with a base of mscompile and then start to override some of the things that are unique to your new matcher. Maybe in that case the position of filename and message are swapped and you don't want to create the whole thing again. Thank you. Good day.

**Comment by pr-yemibedu** [comment]
Hello,
 You have not shown code that starts with a base being set, but no pattern and still get any error (following schema and guidelines). You really do not need this issue ticket. General questions get better answers in gitter chat. Thank you. Good day.

**Comment by felixfbecker** [comment]
@pr-yemibedu I will leave this ticket open because the error message is still wrong ;)

**Comment by pr-yemibedu** [comment]
Hello,
 The error message should point that the pattern is defined wrong as it could not find a predefined pattern by the given name. You are more than welcomed to leave it open so that everything can be concise and consistent. Thank you. Good day.

**Comment by dbaeumer** [comment]
You now get
```
Error: the pattern property ^[(.+)] (.+):\[(\d+),(\d+)\] (.*)$ is no valid pattern variable name.
Error: the description doesn't define a valid problem pattern:
{
    "pattern": "^[(.+)] (.+):\\[(\\d+),(\\d+)\\] (.*)$",
    "owner": "java",
    "fileLocation": "absolute"
}
```

**Comment by pr-yemibedu** [comment]
Hello,
 There is a spelling error. It should say " ... is not a valid built-in pattern variable name."
Can you please correct and commit this change. it will be exactly what developers need to see. Thank you. Good day.

**Comment by dbaeumer** [comment]
@pr-yemibedu thanks. One little thing: extension can with the next release contribute problem patterns and matchers. So these are not necessarily built-in.

Fixed in master

**Comment by pr-yemibedu** [comment]
Hello,
 Your change makes sense. You also have a typo on line [1237](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/markers/common/problemMatcher.ts#L1237) where :
``  'ProblemMatcherParser.noDefinedPatter' 
``
should be (missing last 'n' character)
`` 'ProblemMatcherParser.noDefinedPattern' 
``
for readability sake. I will not hijack this anymore. Thank you. Good day.

**Comment by dbaeumer** [comment]
@pr-yemibedu if you see other things please open a issue.
