### ISSUE TITLE
Terminal types two characters when suggesting command

### ISSUE THREAD

**Issue by jmigual** [microsoft/vscode#206156]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.2
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Open integrated terminal and use powershell
2. Use module CompletionPredictor (I think it's related)
3. Start typing any command that can be suggested by VS Code, e.g, gpg-connect-agent.exe
4. VS Code suggests the command but then two characters are typed for every character pressed (see video)

https://github.com/microsoft/vscode/assets/6493651/4b0bc167-fc49-47c6-8125-d2cca091b7a9

Also, I've tried setting `terminal.integrated.shellIntegration.suggestEnabled=false` but I still got the suggestions. Is there a way to disable them?

**Comment by jmigual** [comment]
Okay, I fully reinstalled VS Code (deleting the `%appdata%/code` and the `.vscode` folders) and I cannot reproduce the issue anymore

**Comment by Tyriar** [comment]
Setting `terminal.integrated.shellIntegration.suggestEnabled` back to false and then restarting the terminal should fix this. I'm going to make it more obvious that this feature is a WIP in https://github.com/microsoft/vscode/issues/206172
