### ISSUE TITLE
github copilot doesn't highlight the tags if tags are placed at the bottom of the long text

### ISSUE THREAD

**Issue by abhijit-chikane** [microsoft/vscode#206153]
- VS Code Version: 1.86.2
- OS Version: Windows 11

Steps to Reproduce:

1. paste long text into github copilot chat input box
![image](https://github.com/microsoft/vscode/assets/50770619/fd226382-4315-4285-92a7-2abf03b9a699)

2. Add the @ then it should show the tags dropdown
3. choose any one of it and see
4. github copilot doesn't highlight the tags and also the scrollbar is missing

and I don't know but the dropdown too takes too much of width
![image](https://github.com/microsoft/vscode/assets/50770619/493f5148-5f6b-455b-a937-978602f7b46e)

**Comment by roblourens** [comment]
The `@` chat participant is only valid at the start of the request
