### ISSUE TITLE
After click "Open Folder", the dialog coming 10s later, when my last folder is Samba and not exist.

### ISSUE THREAD

**Issue by MatrixMuto** [Microsoft/vscode#2061]
After click "Open Folder", the dialog coming 10s later, when my last folder is Samba and not exist.

**Comment by isidorn** [comment]
Do you see this regularly or only for one folder? If you only see it on one folder can you share that folder so we try to reproduce this? Does your last folder no longer exist, I am not getting that part?
On what OS are you?

**Comment by weinand** [comment]
@alexandrudima I remember that you have seen something like this before. Can you comment on this?

**Comment by alexandrudima** [comment]
I was seeing something similar when having a network share mapped as a drive and switching networks (mapped drive not available -- hostname cannot be resolved). But the open dialog was showing late on every application on Windows.

**Comment by bpasero** [comment]
OS behavior.
