### ISSUE TITLE
C/C++ Debugging, macOS: First "--" in args is not forwarded to the program

### ISSUE THREAD

**Issue by afreer** [microsoft/vscode#206144]
Type: <b>Bug</b>

Sample C++ program to reproduce:

    #include <stdlib.h>
    #include <stdio.h>

    int main(int argc, const char* argv[])
    {
        printf("argc=%d\n", argc);
        for (int i = 0; i < argc; i++)
        {
            printf("argv[%d]=%s\n", i, argv[i]);
        }
        return EXIT_SUCCESS;
    }

Sample launch.json configuration to reproduce:

    {
        "name": "C/C++: clang++ build and debug active file",
        "type": "cppdbg",
        "MIMode": "lldb",
        "request": "launch",
        "logging": {
            "trace": true,
            "engineLogging": true
        },
        "program": "${fileDirname}/${fileBasenameNoExtension}",
        "args": [
            "-a1",
            "-a2",
            "--",
            "-a3",
            "--",
            "-a4",
            "--",
            "-a5"
        ],
        "stopAtEntry": false,
        "cwd": "${fileDirname}",
        "environment": [],
        "externalConsole": false,
        "preLaunchTask": "C/C++: clang++ build active file"
    }

If you run this in VS Code on macOS you will see that the first "--" is not 
forwarded to the program. I believe this is due to a bug in lldb-mi
in how it parses the -exec-arguments command. It strips the first "--".
I tested by compiling lldb-mi but with the below modification, which caused
the first "--" to be forwarded to the program as expected.

    diff --git a/src/MICmdArgValConsume.cpp b/src/MICmdArgValConsume.cpp
    index 01d0013..d77edc3 100644
    --- a/src/MICmdArgValConsume.cpp
    +++ b/src/MICmdArgValConsume.cpp
    @@ -65,8 +65,8 @@ bool CMICmdArgValConsume::Validate(CMICmdArgContext &vwArgContext) {
        if (rTxt == "--") {
        m_bFound = true;
        m_bValid = true;
    -      if (!vwArgContext.RemoveArg(rTxt))
    -        return MIstatus::failure;
    +      // if (!vwArgContext.RemoveArg(rTxt))
    +      //   return MIstatus::failure;
        return MIstatus::success;
        }
        // Next

The real fix could involve:
 - Updating lldb-mi's -exec-arguments commmand to forward the arguments exactly
 as-is to the program and not try to parse it's own args from them.
 - Updating VS Code to use some alternative command to -exec-arguments that
 likewise only forwards the arguments exactly as-is to the program.
 - Some other solution.

Thanks for looking into this! Since "--" is a relatively common command line
argument convention, my hope is that this will help a number of users.

VS Code version: Code 1.86.2 (Universal) (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:13.651Z)
OS version: Darwin x64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.63GB free)|
|Process Argv|--crash-reporter-id e4dd87ed-185e-42be-a354-ee5209f4851b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
go-to-character-position|dav|2.0.0
gitlens|eam|14.8.2
cmake-tools|ms-|1.17.16
cpptools|ms-|1.19.4
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d34g3935:30971562
edj9j583:30969295
7j2b6412:30969109
bg6jg535:30958357

```

</details>

**Comment by afreer** [comment]
The issue does not occur for me on Windows in WSL mode. VS Code Version 1.86.2. WSL is Ubuntu 22.04.3 LTS, and is WSL 2 (not WSL 1). This I believe is due to it using the default gdb instead and not needing to use the lldb-mi translation layer.

**Comment by roblourens** [comment]
Thanks for the investigation, this would be an issue with the C++ extension providing the `cppdbg` debug adapter. Please file it on the extension's repo
