### ISSUE TITLE
Add "don't ask me again" setting to suggested language switch and store this in the users account when settings sync is on.

### ISSUE THREAD

**Issue by CodingSpiderFox** [microsoft/vscode#206155]
The most annoying thing after installing vscode on a new machine and enabling the settings sync using my Github account is that with every new install of vscode, it suggests me to switch the language of vscode to German.
I never ever would want that because it makes searching on the internet for solutions to problems with vscode way less effective.

However, sometimes I accidentally click the accept button.
I want a checkbox "Never ask me again" in that popup.
When I enable this and then close the popup, whenever I install a new PC with vscode where I login with that same account to settings sync - I want to never ever in my life see that annoying popup again unless I go to the settings of vscode and disable the "don't ask me again" setting manually

**Comment by TylerLeonhardt** [comment]
@CodingSpiderFox is there a reason you have the German language pack installed?

You can uninstall it from the Extension view if you don't want it.
