### ISSUE TITLE
Easy to submit request to `/explain` without the slash command executing

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#206248]
In both these scenarios, `/explain` is taken literally, instead of being interpreted as a command:

1. Press the `/explain how the selected code works` link:

![Image](https://github.com/microsoft/vscode/assets/22350/2d5b437b-4220-44b8-bed4-4dd6d46fc47d)

2. Type `@workspace /explain` and reload the window.

Both end up like:

![Image](https://github.com/microsoft/vscode/assets/22350/f4b4a8c8-e36b-4a0d-bdcd-efbbbd37aca5)

**Comment by joaomoreno** [comment]
Adding `candidate` just to raise awareness.

**Comment by roblourens** [comment]
Same issue as https://github.com/microsoft/vscode/issues/206050 actually
