### ISSUE TITLE
terminal.integrated.hideOnStartup Does not work

### ISSUE THREAD

**Issue by jonnyhork** [microsoft/vscode#206272]
Type: <b>Bug</b>

1. Open a project in VS Code
2. Open the integrated terminal
3. Close then VS Code, the re-open the project, the terminal should be expected to also open on startup.
4. Close the terminal.
5. In settings set terminal.integrated.hideOnStartup to "always"
6. Close then VS Code, the re-open the project, integrated termianl still opens on startup.

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:12.210Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|64.00GB (1.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.24.1
lwc-creator|Ale|1.5.3
license-header-manager|ang|0.2.5
swagger-viewer|Arj|3.1.2
markdown-mermaid|bie|1.22.0
catppuccin-vsc|Cat|3.11.2
apex-pmd|chu|0.6.2
css-theme-completions|con|0.0.5
dscodegpt|Dan|3.1.7
vscode-eslint|dba|2.4.4
vscode-quick-select|dba|0.2.9
githistory|don|0.6.20
gitlens|eam|14.8.2
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.5.0
prettier-vscode|esb|10.1.0
lana|Fin|1.14.0
copilot|Git|1.166.0
copilot-chat|Git|0.12.2
vscode-github-actions|git|0.26.2
terraform|has|2.29.4
elixir-ls|Jak|0.20.0
plantuml|jeb|2.17.5
dotenv|mik|1.0.1
perforce|mjc|4.15.7
vscode-docker|ms-|1.29.0
vscode-language-pack-es|MS-|1.85.2024021409
vscode-kubernetes-tools|ms-|1.3.15
playwright|ms-|1.0.22
remote-containers|ms-|0.338.1
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
live-server|ms-|0.4.13
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
vsliveshare|ms-|1.0.5905
vsix-viewer|onl|1.0.5
phoenix|pho|0.1.2
material-icon-theme|PKi|4.34.0
java|red|1.28.1
vscode-commons|red|0.0.6
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
salesforce-vscode-slds|sal|1.4.8
salesforcedx-einstein-gpt|sal|0.39.0
salesforcedx-vscode|sal|60.1.2
salesforcedx-vscode-apex|sal|60.1.2
salesforcedx-vscode-apex-debugger|sal|60.1.2
salesforcedx-vscode-apex-replay-debugger|sal|60.1.2
salesforcedx-vscode-core|sal|60.1.2
salesforcedx-vscode-expanded|sal|60.1.2
salesforcedx-vscode-lightning|sal|60.1.2
salesforcedx-vscode-lwc|sal|60.1.2
salesforcedx-vscode-soql|sal|60.1.2
salesforcedx-vscode-visualforce|sal|60.1.2
vscode-java-test|sal|0.37.1
coredx-workspaces-getting-started|sf-|2023.3.20
vscode-core-java-dev-pack|SFD|0.0.7
sourcegraph|sou|2.2.16
es6-mocha-snippets|spo|0.2.2
rewrap|stk|1.16.3
code-spell-checker|str|3.0.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.52.0
vscode-java-debug|vsc|0.56.1
vscode-java-dependency|vsc|0.23.4
vscode-java-pack|vsc|0.25.15
vscode-maven|vsc|0.44.0
vscode-spring-boot-dashboard|vsc|0.13.1
vscode-spring-initializr|vsc|0.11.2
codetour|vsl|0.0.59
vscode-todo-highlight|way|1.0.5

(4 theme extensions excluded)

</details>

**Comment by jonnyhork** [comment]
![hideOnStartup](https://github.com/microsoft/vscode/assets/25188632/8bf98ed7-c473-4b33-a987-f34df09fdd79)

Even though I have the hideOnStartup set to `always` the integrated terminal always opens up every time I open VS Code. Even if I close the integrated terminal before closing the window, VS Code still opens the terminal. 

I'm not sure [#189204](https://github.com/microsoft/vscode/pull/189204) really works.

The [claim the VS Code always restores the UX from the previous session](https://github.com/microsoft/vscode/issues/39137#issuecomment-350992305) seems to be false as well.

**Comment by meganrogge** [comment]
what happens if you disable all extensions and comment out your settings besides the`hideOnStartup`?

**Comment by jonnyhork** [comment]
@meganrogge If I disable all the extensions and comment out everything in settings besides `hideOnStartup` it looks like it works as expected to me. So I guess this means its likely an extension that keeps opening the console on activation. 
I guess the follow up question would be should I we expect this user setting to override any extension behavior? I think settings are applied before extension activation, which would make sense why one would still be able to open the terminal.

**Comment by meganrogge** [comment]
This is an extension issue, so I am not able to investigate further. I suggest using this command to narrow down the culprit and create an issue for that extension

![Image](https://github.com/microsoft/vscode/assets/29464607/285b0d41-e4a1-4fd4-a89e-1daa39afcbad)
