### ISSUE TITLE
code-server not working 

### ISSUE THREAD

**Issue by lakshyajaat** [microsoft/vscode#206210]
- VS Code Version: 
- OS Version:  ubuntu 

Steps to Reproduce:
wget -O- https://aka.ms/install-vscode-server/setup.sh | sh
--2024-02-25 19:32:09--  https://aka.ms/install-vscode-server/setup.sh
Resolving aka.ms (aka.ms)... 104.78.177.162
Connecting to aka.ms (aka.ms)|104.78.177.162|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://vscodeserverlauncher.blob.core.windows.net/builds/setup-scripts/setup.sh [following]
--2024-02-25 19:32:10--  https://vscodeserverlauncher.blob.core.windows.net/builds/setup-scripts/setup.sh
Resolving vscodeserverlauncher.blob.core.windows.net (vscodeserverlauncher.blob.core.windows.net)... 20.150.78.68
Connecting to vscodeserverlauncher.blob.core.windows.net (vscodeserverlauncher.blob.core.windows.net)|20.150.78.68|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1758 (1.7K) [text/x-sh]
Saving to: 'STDOUT'

-                                     100%[========================================================================>]   1.72K  --.-KB/s    in 0s      

2024-02-25 19:32:11 (50.2 MB/s) - written to stdout [1758/1758]

glibc version is 2.31
is min? 1
Installing from https://aka.ms/vscode-server-launcher/x86_64-unknown-linux-gnu
root@localhost:~# code-server
/usr/local/bin/code-server: line 1: syntax error near unexpected token `newline'
/usr/local/bin/code-server: line 1: `<!DOCTYPE html>'
1. 
2.

**Comment by connor4312** [comment]
code-server has been replaced for quite a while with the VS Code CLI: https://code.visualstudio.com/docs/remote/tunnels#_using-the-code-cli
