### ISSUE TITLE
Add a command to restart tsserver syntax server

### ISSUE THREAD

**Issue by davidfirst** [microsoft/vscode#206297]
Currently you can only "Restart TS Server". 
When `typescript.tsserver.useSyntaxServer` is set to auto, which is the default, it spawns another TS Server for the syntax. This syntax server can't be reloaded.

The reason I need this command is because with pnpm projects, in some cases, vscode shows errors about missing packages, where in fact the packages are there. Meaning, `require.resolve(pkg-name)` finds the package, but the import statement in the .ts file is shown with the red line suggesting the package is missing.
(see [this](https://stackoverflow.com/questions/71686054/how-to-fix-vscode-warning-module-not-installed-when-using-pnpm) for a similar issue)

Changing  `useSyntaxServer` from `auto` to either `never` or `always` fixes the issue. However, I don't want to change this settings, I simply want to restart this lightweight syntax server without restarting the main TS Server which takes a few seconds to load in a big project.

**Comment by mjbvz** [comment]
The normal restart TS Server command restarts both servers. You can confirm this by checking the process ids

**Comment by davidfirst** [comment]
@mjbvz , Yes I know. As I mentioned, I don't want to reload the main TS Server because the step of "initializing JS/TS language features" takes a few seconds to complete.

**Comment by mjbvz** [comment]
Can you file an  file an issue against pnpm so reloads aren't needed? 

Far too specialized to add to core VS Code

**Comment by davidfirst** [comment]
I see.
Initially I was thinking to open a bug here in vscode because the facts are:
1. when reloading TS Server the issue is gone. It doesn't complain about missing modules.
2. when `useSyntaxServer` is set to either `never` or `always` the issue is gone.

It probably means that this Syntax TS Server is not in sync with the main TS Server. 
The problem is that I can't easily specify steps for you guys to reproduce. (on my local it reproduced consistently but it requires installing some external tools). 

> Far too specialized to add to core VS Code

Is there a way for an extension to do it? I see that this Syntax TS Server is created here
```
semantic: this.spawnTsServer(TsServerProcessKind.Semantic, version, configuration, pluginManager, cancellerFactory),
```
but eventually it's saved into a private member `private serverState: ServerState.State`.

**Comment by zkochan** [comment]
As far as I understand there's nothing pnpm can do about this issue. I assume the same issue will happen with npm, if you use the [install-strategy=linked](https://docs.npmjs.com/cli/v10/commands/npm-install#install-strategy) setting, or with Yarn, if you set the `nodeLinker` setting to `pnpm`.

With the "isolated" node_modules layout that pnpm uses, all dependencies are stored in a flat directory structure inside `node_modules/.pnpm`. If some dependencies depend on peer dependencies and the peer dependency changes, then during next installation the location of the dependency inside `.pnpm` will change. For instance, a card component package could change from `.pnpm/card@1.0.0+react@16.0.0` to `.pnpm/card@1.0.0+react@16.1.0`. The issue appears to be that ts server somehow is caching the old location that the symlink was pointing to, so once pnpm changes the structure of node_modules, ts server doesn't pick up the new locations.

This is how pnpm is designed to work and I don't think there's a way to change it. As I mentioned, even npm and Yarn support this layout as an opt-in.
