### ISSUE TITLE
Quick search: editor state is not cleared

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#206286]
When I get preview editor opened from quick search, and then press `ESC`, the preview editor is still there:

![Recording 2024-02-26 at 20 53 42](https://github.com/microsoft/vscode/assets/900690/fda79ed1-cd4b-47b0-9540-18055073ec60)

**Comment by bpasero** [comment]
Hm, this seems to be related to the fact that the tab I have opened is a match in quick search, it does not reproduce when I search for something else 🤔

**Comment by andreamah** [comment]
Oh, so the repro steps are:

1. open a file
2. quick search for something that appears in the open file and a closed file.
3. navigate through to the results in the closed file, then back to the results in the open file.
4. There is a preview editor still opened for the file that was previously closed.

I can confirm that this happens.
