### ISSUE TITLE
Shell integration breaks paths inside npm commands on Windows

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#206285]
1. Have a package.json like this:

  ```
  {
      "scripts": {
          "foo": "npm run bar",
          "bar": "tsc"
      },
      "devDependencies": {
          "typescript": "^4.9.4"
      }
  }
  ```

2. Enable shell integration
3. Run `npm run foo`. Get an error like "'tsc' is not recognized as an internal or external command"
4. Disable shell integration
5. Run `npm run foo` and it works

**Comment by meganrogge** [comment]
hmm, this works for me

![Image](https://github.com/microsoft/vscode/assets/29464607/1ff9453a-b0e9-48c0-b4ba-0e84d25a75f2)

**Comment by Tyriar** [comment]
Python does indeed _set_ `$PATH`, not prepend/append to it. cc @karrtikr

**Comment by connor4312** [comment]
Having looked closer at the screenshot, it seems like that syntax the terminal shows has it prepending the path (though it duplicates everything I already had in my path which is not really necessary.)

Interestingly when I manually call `env` in the npm script, it shows a PATH that looks just like the PATH outside of the script with the addition of the expected `.bin` folder. But actually calling _any_ command without specifying an absolute path now fails: `npm` isn't found, and running `echo %path%` just says "ECHO is on.". This is something that also works if I turn shell integration off.

**Comment by karrtikr** [comment]
> Python does indeed set $PATH, not prepend/append to it. cc @karrtikr

@Tyriar If you look closely, Python is still prepending to `PATH`, it just prepends a whole lot.

> (though it duplicates everything I already had in my path which is not really necessary.)

Right, unfortunately we have to prepend `PATH` twice (once at process creation and once at shell integration level) because Python extension cannot reliably predict when shell integration works: https://github.com/microsoft/vscode-python/pull/22905.

**Comment by karrtikr** [comment]
My guess is something in shell integration script is adding to `PATH` incorrectly. 

@connor4312 Can you try some other way of printing `PATH` in cmd instead of echo? For eg. try running,
```
python -c"import os;print(os.environ['PATH'])"
```

**Comment by connor4312** [comment]
Yes, the PATH actually looks correct (https://github.com/microsoft/vscode/issues/206285#issuecomment-1965178790)

**Comment by karrtikr** [comment]
Actually now that I think about it, Command prompt does not even have [shell integration script support](https://code.visualstudio.com/docs/terminal/shell-integration), does it? @Tyriar So I wouldn't expect shell integration setting to have any effect.

**Comment by connor4312** [comment]
no, I'm using powershell, but it seems like `npm run` uses cmd.exe to run its scripts.

**Comment by karrtikr** [comment]
I see gotcha. Feel free to reassign if Python extension can do anything from our end to solve this.

**Comment by connor4312** [comment]
This is still pretty painful, I have to turn off shell integration constantly 😕 

In the copilot repo for example:



![Image](https://github.com/microsoft/vscode/assets/2230985/bf4377a7-f69c-4b5e-86c6-978a07375067)

**Comment by connor4312** [comment]
fyi, something changed and I no longer get this issue 🤷
