### ISSUE TITLE
Pressing enter to select an option during auto-complete in the Debug Console does not auto complete the selection.

### ISSUE THREAD

**Issue by dzearing** [microsoft/vscode#206262]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version: 
- OS Version: 

VSCode 1.86.2
Windows 11

Steps to Reproduce:

1. Hit a breakpoint
2. In the Debug console, start typing the name of a variable so that auto-complete shows up. But don't type the full name.
3. Hit enter to select the current selection. Or even arrow up and down and press enter to select an option.

Expected:

Text from selected item is typed into the edit box

Resulted:

Same as if you pressed enter on your partially typed string. If I was trying to match `config` by typing `con`, the auto complete window would show `config` as a selectable option. In the normal editor experience, pressing enter during autocomplete would fill it in as `config`. But in the Debug Console, this is not the case , "con" is "entered", resulting in an undefined variable referenced in console, and it's pretty annoying.

**Comment by roblourens** [comment]
Please see the setting `debug.console.acceptSuggestionOnEnter`
