### ISSUE TITLE
Inline chat: Pressing `Enter` while response is pending briefly shows buttons

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#206251]
1. Open inline chat
2. Run a query
3. Press `Enter` while it runs

🐛 Buttons flicker

https://github.com/microsoft/vscode/assets/22350/1bd70f3d-2f0e-4dc6-8bcb-a36daa909022

**Comment by jrieken** [comment]
This doesn't reproduce anymore after adopting the chat widget
