### ISSUE TITLE
Debug bar is draggable outside window

### ISSUE THREAD

**Issue by zimmi88** [Microsoft/vscode#20627]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|output-colorizer|IBM|0.0.10|
|html-css-class-completion|Zignd|1.0.3|
|Handlebars|andrejunges|0.2.0|
|vscode-svgviewer|cssho|1.3.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.6|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.8|
|tslint|eg2|0.8.1|
|Scala|itryapitsin|0.1.7|
|jscs|ms-vscode|0.1.9|
|better-merge|pprice|0.5.1|

---

The debug bar appears able to fall off the left side of the screen in such a way that it can't be dragged back into the window. Unfortunately, because VSCode appears to remember where the bar was at the end of the previous debug session, stopping and restarting doesn't bring the bar back into view. As a workaround, I had to open developer tools and manually reset the CSS rules on the element to bring it back into view.

Steps to Reproduce:

1. Start a debugging session. The debug bar should appear where it last was.
2. Click and drag the debug bar off the left side of the window.

![screen shot 2017-02-14 at 4 13 39 pm](https://cloud.githubusercontent.com/assets/3336359/22955688/576b810e-f2d2-11e6-8b8f-008fbbaabc9c.png)

**Comment by isidorn** [comment]
Sorry about that! Dup of https://github.com/Microsoft/vscode/issues/20298 which contains a workaround
