### ISSUE TITLE
.env variables are not updated

### ISSUE THREAD

**Issue by julia-meshcheryakova** [microsoft/vscode#206236]
Type: <b>Bug</b>

Environment: Windows, VS Code. Conda environment created and activated.

Steps:
1) Create '.env' file and load it using 'load_dotenv(override=True)'
var1=value1
2) Change the value of env variable, create new env variable
var1=value1upd
var2=value2
3) Run the code, printing the environment using the command:
& C:/Users/<username>/.conda/envs/<conda-env-name>/python.exe c:/.../code.py --config .\configs\config.json 

Expected: env updated
Actual: env remains unchanged (var1=value1, no new variable)

What doesn't help:
1) Open new terminal
2) Restart VS Code

What helps:
1) Restart the PC

Note:
The same code, the same conda envrironment in PyCharm gets .env updates with the new code runs.

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (4.50GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/juliame/rag-novartis-starter --remote=wsl+Ubuntu --crash-reporter-id 03863a00-26c0-4f2b-9e7a-14b5aef3fc95|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: RAG Experiment Accelerator|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|Memory (System)|15.54GB (13.58GB free)|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.165.732
copilot-chat|Git|0.12.2
intellij-idea-keybindings|k--|1.6.0
azure-dev|ms-|0.8.0
vscode-azureappservice|ms-|0.25.1
vscode-azurecontainerapps|ms-|0.6.1
vscode-azurefunctions|ms-|1.13.3
vscode-azureresourcegroups|ms-|0.8.4
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.15.3
vscode-azurevirtualmachines|ms-|0.6.5
vscode-bicep|ms-|0.25.53
vscode-cosmosdb|ms-|0.20.1
vscode-docker|ms-|1.29.0
vscode-dotnet-runtime|ms-|2.0.1
debugpy|ms-|2024.0.0
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.1.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.338.1
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
azure-account|ms-|0.11.6
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
vscode-node-azure-pack|ms-|1.2.0
vsliveshare|ms-|1.0.5905

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d34g3935:30971562
edj9j583:30969295
fegfb526:30961430
7j2b6412:30969109
ccp1r3:30958155

```

</details>

**Comment by DavideCanton** [comment]
is it related to https://github.com/microsoft/vscode-python/issues/22920 ?

**Comment by thaonp2110** [comment]
I got the similar issue with VSCode + Conda environment

**Comment by julia-meshcheryakova** [comment]
> is it related to [microsoft/vscode-python#22920](https://github.com/microsoft/vscode-python/issues/22920) ?

The fix with switching Python extension to pre-release version mentioned in the issue #22920 helped.
