### ISSUE TITLE
Lack of Confirmation and Ability to Edit Issue Text When Using Built-In "Report Issue" Functionality

### ISSUE THREAD

**Issue by ZelnickB** [microsoft/vscode#206209]
Type: <b>Bug</b>

There is no confirmation before posting an Issue reported from the VS Code user interface (Help > Report Issue).

This issue, in fact, was originally opened by accident because of this lack of confirmation—I thought that I would have a chance to edit it before it was posted, but I did not have that opportunity. Instead of immediately posting the issue to GitHub using the user's account, VS Code should simply prefill the issue report field so that the user can edit it manually.

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:12.210Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|96.00GB (51.58GB free)|
|Process Argv|--crash-reporter-id e5e9ad05-302d-484f-84d9-ef073d07d19c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|3.2.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.22.0
markdown-yaml-preamble|bie|0.1.0
vscode-markdownlint|Dav|0.54.0
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.5.0
latex-workshop|Jam|9.18.2
markdown-shortcuts|mdi|0.12.0
vscode-dotnet-runtime|ms-|2.0.1
debugpy|ms-|2024.0.0
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
datawrangler|ms-|0.26.0
jupyter|ms-|2024.1.1
jupyter-hub|ms-|2023.10.1003012305
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.338.1
remote-ssh|ms-|0.108.0
hexeditor|ms-|1.9.14
remote-explorer|ms-|0.4.1
vscode-sanddance|msr|4.1.0
quarto|qua|1.110.1
code-spell-checker|str|3.0.1
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22
org-mode|vsc|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d34g3935:30971562
edj9j583:30969295
fegfb526:30961430
7j2b6412:30969109
e3gdj431:30958358

```

</details>

**Comment by ZelnickB** [comment]
Created accidentally.

**Comment by justschen** [comment]
when you are logged in, the button says `Create on GitHub` to automatically post the issue. your chance to edit should be in the description and title boxes of the built in reporter.

**Comment by ZelnickB** [comment]
The built-in dialog does not provide the option to preview markdown and use other functionality that GitHub provides. This is why I expected to be able to edit my entry further on GitHub once I pressed the submit button.

**Comment by justschen** [comment]
sounds like you are looking for something like this https://github.com/microsoft/vscode/issues/117657 currently in our backlog. 

>This is why I expected to be able to edit my entry further on GitHub once I pressed the submit button.

you are able to edit the title, description, add comments, or add additional attachments on GitHub even after submitting on github.com by clicking on the three dots to open the menu -> `Edit`.
