### ISSUE TITLE
Accidental dedent for in and when dedent in Ruby comments

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#206292]
Originally from [vinistock](https://github.com/vinistock)

> I was testing the changes from https://github.com/microsoft/vscode/pull/205397 in Insiders and I noticed that the code was incorrectly being dedented when typing in or when in comments.

**Comment by rebornix** [comment]
This was originally introduced in https://github.com/microsoft/vscode/pull/205397 and @vinistock already has a fix via https://github.com/microsoft/vscode/pull/206132. However since the fix is late, we may want to revert the indentation rules change for stable release.

**Comment by rzhao271** [comment]
\closedWith https://github.com/microsoft/vscode/commit/927ae348708a033a2597f7dbe70730be3f6dab25
