### ISSUE TITLE
Run in active terminal doesn't work for file name starting with #

### ISSUE THREAD

**Issue by dandeancook** [microsoft/vscode#206205]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.2 (latest update)
- OS Version: Windows 11 (latest update)

Steps to Reproduce:
1. Create a .sh file with prefix '#' in file name, eg. "#SSH Open Server1.sh"
2. Open a WSL terminal
3. Open the .sh file above
4. Open Command Palette
5. Find 'Terminal: Run active file in active terminal'
6. See the result, it is. eg: `-bash: /mnt/d/devops/Servers/SSH Open Server1.sh: No such file or directory`

VS Code seems already removed the # (hash) before feeding to terminal. The same issue happens even if the file name has no spaces, just a hash prefix makes it fail.

**Comment by meganrogge** [comment]
This is by design to prevent possible script injection via the file path.
