### ISSUE TITLE
v1.86 Application crashes while opening, Ubuntu 22.04.4 LTS

### ISSUE THREAD

**Issue by bijaybogati** [microsoft/vscode#206219]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: v1.86
- OS Version: Ubuntu 22.04.4 LTS

Steps to Reproduce:

1. Updated to v1.86
2. Open vs code application and it simply crashes
3. Had to go back to previous version, which run smoothly

**Comment by deepak1556** [comment]
If the issue is present with latest stable 1.96, please share the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report
