### ISSUE TITLE
Unaligned surrogate pairs are corrupted at multiples of 50 columns.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#20624]
- VSCode Version: Code - Insiders 1.10.0-insider (1d17b45a11d8db22fe95c601f793a3cb9a582ba6, 2017-02-14T09:49:25.026Z)
- OS Version: Windows_NT ia32 10.0.15025
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.8|
|cpptools|ms-vscode|0.10.1|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|rewrap|stkb|1.2.0|

---

Steps to Reproduce:

1. Enter the following text into a new editor with UTF-8 encoding (the specific encoding of the file may not be important): `𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷𠮷` (these are all the character U+20BB7 encoded in UTF-8 as 0xF0 0xA0 0xAE 0xB7 / UTF-16 as the surrogate pair 0xD842 0xDFB7) 
2. Add a character (like 'a') to the beginning of the line which has only a single UTF-16 code unit [1].
3. Observe that some of the original characters (at offsets which are multiples of 50) are now rendered as � (U+FFFD: REPLACEMENT CHARACTER, used to render unknown characters).
4. Observe that copying a the entire run of text or just a selection including the � glyphs will paste into another line or another editor in VS Code or another program correctly as 𠮷. This seems to only affect the current line.
5. Copy the text from step 1 multiple more times onto the end of the line and you will see the corruption repeat periodically, at every 50th column.

[1] Examples:

- The letter 'a' (ASCII) is encoded as a single byte (or a single UTF-16 char) causes the problem.
- U+0280 LATIN SMALL LETTER CAPITAL "ʀ" [UTF-8: 0xCA 0x80 / UTF-16: 0x0280] causes the problem.
- U+4F60 "你" [UTF-8: 0xE4 0xBD 0xA0 / UTF-16: 0x4F60] causes the problem.
- U+20BB6 "𠮶" [UTF-8: 0xF0 0xA0 0xAE 0xB6 / UTF-16: 0xD842 0xDFB6] DOES NOT cause the problem.

I'm guessing the buffer for each line is encoded as UTF-16 and there's something funny about how unaligned surrogate pairs are handled at offsets which are multiples of 50 and the two halves of the surrogate pair occupy offsets x and y (where x mod 50 = 49; y mod 50 = 0) of the buffer (49, 50; 99, 100; 149, 150; etc.).

![image](https://cloud.githubusercontent.com/assets/494055/22954819/7e5d849c-f2cd-11e6-8732-902b0b788dee.png)

**Comment by sean-mcmanus** [comment]
FYI, the bug also repros with 1.9.1 and without the cpptools extension.

**Comment by dilijev** [comment]
Looks like this is fixed for what it is but when using word wrap it looks like we still split surrogates.

![image](https://cloud.githubusercontent.com/assets/494055/23818871/61ea0d86-05b4-11e7-9c8c-273c4ae21806.png)

Should I open a new issue?
