### ISSUE TITLE
Make Code Insider executable with a shorter name like codei

### ISSUE THREAD

**Issue by vairamsvsjdo** [Microsoft/vscode#20621]
Make Code Insider executable with a shorter name like codei
- VSCode Version: 1.10.0-insider
- OS Version: windows 10 home

Steps to Reproduce:

1.
2.

Expected: codei be the shortcut for the insider code editor. This makes usage of scripting and usage from command prompt easier on windows

**Comment by joaomoreno** [comment]
You can create aliases to executables in your own system.

**Comment by vairamsvsjdo** [comment]
code-insiders is a short name already existing. Learnt from another issue.
