### ISSUE TITLE
C# Language Extension missing?!

### ISSUE THREAD

**Issue by N3r0Nu77** [Microsoft/vscode#2062]
After updating I now receive an error.

[c:/Program Files (x86)/Microsoft VS Code/resources/app/extensions/csharp-o]: Cannot read file c:/Program Files (x86)/Microsoft VS Code/resources/app/extensions/csharp-o/package.json: ENOENT: no such file or directory, open 'c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\csharp-o\package.json'

Upon checking I found that the entire c# extension is empty and have found no solutions yet to remedy this.

**Comment by jrieken** [comment]
That's an issue with the installer

**Comment by joaomoreno** [comment]
Duplicate of #1605
