### ISSUE TITLE
Language model access API 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#206265]
This issue is about allowing extensions to use language model that are contributed by other extensions. The API proposal is https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.languageModels.d.ts and its scope is to allow to use the chat feature of language models.

Remaining finalisation todos

* [x] consolidate different LanguageModelChatXYZMessage-type into one type and a role-enum
* [x] move System message/role into its own proposal
* [x] have a select-function that's the only way of getting to a chat model 
* [x] ~~consider moving token counting into its own proposal (some model don't do token counting e.g anthropic or ollama)~~
* [ ] consider to have more sturcture on `LanguageModelChatResponse`, e.g have a fake reply message with role like others (ollama, open ai, anthropic)
  * I renamed  `LanguageModelChatResponse#stream` to `text` and I will continue to explore a stream of structured objects. That would be additive to `text` and plugged in as its foundation. 
  * add something like `modelResult: Thenable<{ [name: string]: any }>`
 *  add a StopReason-enum that's also used in LanguageModelChat

**Comment by isidorn** [comment]
Docs: https://code.visualstudio.com/api/extension-guides/language-model

**Comment by jrieken** [comment]
With #206358 there will be no more language model access object. Instead all requests are made directly via `vscode.lm.sendChatRequest(model, messages, options, token)`

**Comment by worksofliam** [comment]
Hi @jrieken 

Is there any plans to add a `registerLanguageModel`, so I can implement my own calls to other models other than the Copilot provided models?

Thanks!

**Comment by jrieken** [comment]
Yeah, that exists. It is the `src/vscode-dts/vscode.proposed.chatProvider.d.ts` which is still very rough and currently not yet scheduled for finalisation. Tho, feel free to give it a spin and report what's missing/wrong. For instance, locally I have a dummy extension that uses ollama to drive this API

**Comment by jrieken** [comment]
> @jrieken I assume you are referring to the createChatParticipant API?

No, I mean the proposal that I have mentioned

**Comment by jrieken** [comment]
FYI that I made the following changes to the `languageModels` proposal

* there is no more `vscode.lm.languageModels` and generally no more referring of language model by string-identifier. 
* there is `vscode.lm.selectChatModels(selector)` that takes a selector and returns matching chat models or nothing (`undefined`)

These changes allow for a better implementation of the providing-end (`chatProvider`-proposal) and most importantly make it more obvious that models can (and will) change. The following pattern had become popular'ish `vscode.lm.sendChatRequest('hardcoded.model.id`, ....)`. This is brittle because extensions break as soon as the model id isn't known anymore. Instead models need to be selected, making it hopefully more clear that a desired model doesn't exist. The new selector-mechanism allows for new flexibility as well. A couple of samples

```ts

// select a model by vendor and family
await vscode.lm.selectChatModels({ vendor: 'copilot', family: 'gpt-3.5-turbo' })

// select all models
await vscode.lm.selectChatModels()

// hardcode an identifier (previous usage model, NOT recommended because brittle)
await vscode.lm.selectChatModels({ id: 'someHardcodedModelId' })
```

To restate, the `selectChatModels`-function can return `undefined` which means no model was found. That's because the selector is to strict (using `id`) or because no models are known (missing extensions). The shape of language model selectors is this

```ts
export interface LanguageModelChatSelector {
  vendor?: string;
  family?: string;
  version?: string;
  id?: string;
}
```

Note that

* property order represents how specific it is
* properties are matched based on equality, when present it must match
* we will likely add some comparison selector for input and/or output tokens

**Comment by amitjoshi438** [comment]
> Hi @jrieken
> 
> Is there any plans to add a `registerLanguageModel`, so I can implement my own calls to other models other than the Copilot provided models?
> 
> Thanks!

Isn't this still possible? We can call any LLM API in our @participants handler and use the stream.markdown() to display the response, right? @jrieken

**Comment by yungezz** [comment]
> FYI that I made the following changes to the `languageModels` proposal
> 
> * there is no more `vscode.lm.languageModels` and generally no more referring of language model by string-identifier.
> * there is `vscode.lm.selectChatModels(selector)` that takes a selector and returns matching chat models or nothing (`undefined`)
> 
> These changes allow for a better implementation of the providing-end (`chatProvider`-proposal) and most importantly make it more obvious that models can (and will) change. The following pattern had become popular'ish `vscode.lm.sendChatRequest('hardcoded.model.id`, ....)`. This is brittle because extensions break as soon as the model id isn't known anymore. Instead models need to be selected, making it hopefully more clear that a desired model doesn't exist. The new selector-mechanism allows for new flexibility as well. A couple of samples
> 
> ```ts
> // select a model by vendor and family
> await vscode.lm.selectChatModels({ vendor: 'copilot', family: 'gpt-3.5-turbo' })
> 
> // select all models
> await vscode.lm.selectChatModels()
> 
> // hardcode an identifier (previous usage model, NOT recommended because brittle)
> await vscode.lm.selectChatModels({ id: 'someHardcodedModelId' })
> ```
> 
> To restate, the `selectChatModels`-function can return `undefined` which means no model was found. That's because the selector is to strict (using `id`) or because no models are known (missing extensions). The shape of language model selectors is this
> 
> ```ts
> export interface LanguageModelChatSelector {
>   vendor?: string;
>   family?: string;
>   version?: string;
>   id?: string;
> }
> ```
> 
> Note that
> 
> * property order represents how specific it is
> * properties are matched based on equality, when present it must match
> * we will likely add some comparison selector for input and/or output tokens

hi @jrieken met below error after sendRequest(). Any guidance?
```
"Language model 'github.copilot-chat/2/copilot-gpt-4' errored, check cause for more details"
```
cause
```
'y.provider.provideLanguageModelResponse is not a function'
```

**Comment by bwateratmsft** [comment]
@jrieken I'm noticing a difference in behavior of the `vscode.lm.selectChatModels()` API when running in Codespaces from the browser.

When running against a Codespace with _desktop_ Insiders, everything works as expected.

When running against the same Codespace with _browser_ Insiders, `vscode.lm.selectChatModels()` always returns `undefined`, implying there are no chat models available.

**Comment by jrieken** [comment]
> hi @jrieken met below error after sendRequest(). Any guidance?

@yungezz Make sure that you are on latest pre-release of the copilot-chat extension


> When running against the same Codespace with browser Insiders, vscode.lm.selectChatModels() always returns undefined, implying there are no chat models available.

@bwateratmsft That's certainly possible when copilot-chat isn't installed in the codespace.

**Comment by bwateratmsft** [comment]
> > When running against the same Codespace with browser Insiders, vscode.lm.selectChatModels() always returns undefined, implying there are no chat models available.
> 
> @bwateratmsft That's certainly possible when copilot-chat isn't installed in the codespace.

It is installed, and regular Copilot works normally, but our extension can't get a language model.

**Comment by jrieken** [comment]
And it is latest prerelease?

**Comment by bwateratmsft** [comment]
Yep!

Version: 1.90.0-insider
Commit: 3028408922e78cc9ca15ee761372a7c0603fa375
Date: 2024-05-13T12:40:35.552Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0

![image](https://github.com/microsoft/vscode/assets/36966225/9e26f867-8eda-4c7e-9629-4e4a71deb03a)
![image](https://github.com/microsoft/vscode/assets/36966225/97b1bc11-f9bd-4ddd-ae27-3880965d12bb)

Here's regular chat working:
![image](https://github.com/microsoft/vscode/assets/36966225/f7c12bf1-7ed9-4c87-b1a4-0fa37482f35a)

And our extension emitting to its output log, via this line of code:
```typescript
ext.outputChannel.error(JSON.stringify(await vscode.lm.selectChatModels()));
```
![image](https://github.com/microsoft/vscode/assets/36966225/508b37f9-dd38-455e-826c-508e8d41e7fb)

**Comment by jrieken** [comment]
Really confusing... In my sample remote-setup (which isn't codespaces) this is working just fine and I see so smoking guns for why this wouldn't work in codespaces. For now, I have added some logging that should help us get to the bottom of this

**Comment by jrieken** [comment]
This is place of all API proposals: https://github.com/microsoft/vscode/tree/main/src/vscode-dts

> Also is this section of the guide still accurate

Likely outdated

**Comment by bwateratmsft** [comment]
> Really confusing... In my sample remote-setup (which isn't codespaces) this is working just fine and I see so smoking guns for why this wouldn't work in codespaces. For now, I have added some logging that should help us get to the bottom of this

Where should I look for the additional logs?

**Comment by jrieken** [comment]
Enable trace logging, show the window-log and check for messages starting with `[LM]`. There should be some for registering and some for selection

<img width="963" alt="Screenshot 2024-05-15 at 08 15 30" src="https://github.com/microsoft/vscode/assets/1794099/cd138901-823d-4c1a-bf4f-0c69fe5c2542">

**Comment by jrieken** [comment]
@bwateratmsft I did find something after @roblourens running into a similar issues. Can you confirm that a later/second invocation yields models and/or that the `vscode.lm.onDidChangeChatModels`-event fires and that after that chat models are selected?

**Comment by bwateratmsft** [comment]
I found some log lines for selection but nothing for registration:
> [LM] selected language models {"vendor":"copilot","extension":{"value":"ms-azuretools.vscode-azure-github-copilot","_lower":"ms-azuretools.vscode-azure-github-copilot"}} []

**Comment by jrieken** [comment]
> I even tried doing the following and still there were no log lines about registration

Thanks for the update. That would really mean the language model API doesn't register. Can you check the chat log (Output > GH Copilot Chat) for messages starting with `registerChatResponseProvider`

**Comment by bwateratmsft** [comment]
I don't see any messages like that from either browser or desktop frontend on the Codespace. However, on the browser session there was this message which did not appear on the desktop session--might be spurious but I'm not sure:

```
2024-05-15 17:47:09.424 [info] [RemoteAgents] Invalid remote agent response: bad request: unknown integration (SyntaxError: Unexpected token 'b', "bad reques"... is not valid JSON)
```

**Comment by isidorn** [comment]
We have finalized the Language Model and Chat Participant API 🚀 

Thus, you can now publish your extensions to the VS Marketplace. This API is finalized in VS Code Insiders, and will be finalized in VS Code Stable in July. Thus we suggest that you use an engines: ^1.90.0 property in your package.json, and VS Code Stable will gracefully handle your extensions and ignore your usage of Language Model and Chat API until the API gets finalized in Stable in July.

Full docs https://code.visualstudio.com/api/extension-guides/language-model

We have decided to only finalise the `User` message. And `System` message might be finalised in one of the future iterations. Main reason for this is general API consideration - as we are still learning how the `System` prompt API would fit with some of the non-GPT models. Also we believe that the `System` prompt API requires more responsible AI testing from our team. 
If your extension would like to use the `System` prompt API - please let us know if you hit issues with using the `User` prompt as a replacement.

We are excited to see what you build ✨

**Comment by worksofliam** [comment]
@isidorn I am still wondering if there will be a `lm.registerModel` API so I can use other models inside of the chat API. Is this something coming in the future?

**Comment by jrieken** [comment]
@worksofliam https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.chatProvider.d.ts

**Comment by jrieken** [comment]
Still a proposal and not yet planned for finalisation
