### ISSUE TITLE
Hot Exit does not work when the computer blue screens

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#20629]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.15025
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.8|
|indentation-level-movement|kaiwood|1.1.1|
|cpptools|ms-vscode|0.10.1|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|rewrap|stkb|1.2.0|

---

Steps to Reproduce:

1. Open a folder in VS Code and open some editors
2. Bluescreen (obviously not expecting someone to try this on their dev machine)
3. Reopen VS Code when the PC restarts to find that the last session was not saved

I imagine this would be true if the machine lost power or was hard-reset in such a way that VS Code was unable to clean up after itself or save some state.

Expected behavior:

No matter how VS Code was closed, the working state should be restored when it is started up again. Probably could be solved by saving information about which folder and files are open at the time they are opened, instead of at the time VS Code shuts down.

**Comment by Tyriar** [comment]
All backups should be restored, with possibly the more recently input text not backed up if it crashed as you're typing. The workspace state however (current window, opened windows) is stored in local storage which can sometimes be delayed when persisted to disk. Are the files themselves are restoring fine, it's just the state?

**Comment by dilijev** [comment]
Well I don't ever leave files not-saved as a matter of habit. I haven't lost any data, just the state of the workbench has not been saved for me.

**Comment by Tyriar** [comment]
Ah ok, that's as designed. I believe the reason it happens is because we use local storage (which is very fast) but it only flushes to disk periodically.

Hot exit mainly just ensures unsaved changes don't go missing.

**Comment by dilijev** [comment]
I see. Thanks.
