### ISSUE TITLE
"Unable to open 'Unknown Source'" if StackFrame.source is missing

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#20622]
As I understand, `StackFrame.source` in the debug protocol is supposed to be optional (because there might not always be a source location available). However, starting with VSCode 1.9.0, a missing `source` causes the following error (after a pause request response, might happen elsewhere too):

![](http://i.imgur.com/xelzPoE.png)

(btw: same thing with a `source` that is present, but has no `path`)

At first glance, this makes it look like pausing didn't work. However, at a second glance, pausing and resuming still works fine, so it's mostly a cosmetic issue (that still might lead the user to think it's broken).

Here's what our debug adapter ([Haxe Debug][1]) sends:

![](http://i.imgur.com/svdJxnh.png)

This works fine (no error appears) in 1.8.1, which would make this a regression. The issue is still present in the latest Insider's build (1d17b45a11d8db22f).

Other debug adapters seem to have the same issue, as suggested by [this StackOverflow question][2] regarding the same error message with ASP.NET.

Issue #4608 seems somewhat related to this.

[1]: https://github.com/vshaxe/vshaxe-debugadapter
[2]: http://stackoverflow.com/questions/42143768/vs-code-give-me-this-error-unable-to-open-unknown-source-file-not-found-un

**Comment by InfiniSuite** [comment]
I'm still having this issue using the latest build as well as Insiders (updated today).

VS Code: v.1.9.1
TypeScript: 2.1.6
OS: OSX
Browser: Chrome
Debugger: Debugger for Chrome

**Comment by isidorn** [comment]
@Gama11 does the fix work for you? Namely vscode should simply not open the source if it is missing which would prevent the error.

**Comment by Gama11** [comment]
@isidorn Yes, it works if our debug adapter sends a stackframe like the one in the screenshot of my original post (one without a `source`).

Our debug adapter _used to send_ messages like this, where `source` is present, but path is `null` - with this, I  can still reproduce the error on Insider's:

![](http://i.imgur.com/qk5Cmr3.png)

![](http://i.imgur.com/ET24cR1.png)

I just assumed that that was incorrect API usage / not supposed to work anyway - it always showed the path as `null` in the call stack rather than detecting it as `Unknown Source`:

![](http://i.imgur.com/4HucUwu.png)

Even though in 1.8.1, this didn't error, but it actually opened a `<null>` file, which doesn't seem correct either:

![](http://i.imgur.com/1YvuWDY.png)

**Comment by isidorn** [comment]
@Gama11 thanks. Yes that is how it is supposed to work now. Adding verified label
