### ISSUE TITLE
able to start from command prompt and still be able to close command prompt after

### ISSUE THREAD

**Issue by vairamsvsjdo** [Microsoft/vscode#20620]
able to close command prompt without closing code editor after opening from command prompt 
- VSCode Version: 1.10.0-insider
- OS Version: windows 10 home

Steps to Reproduce:

1. open command prompt
2. code .
3. close command prompt will close code also

Expected:
1. close only command prompt and run visual studio code gui continuously. (This is the behavior on Cent-OS)

**Comment by vairamsvsjdo** [comment]
This behavior works correctly with LTS version 1.9.0.
1. Execute code . on a command prompt window
2.returns control to command prompt new line
3.. close command prompt window after code editor v 1.9.0 opens.
4. code editor remains opened.

1. Execute "Code Insider.exe" . on a command prompt window
2. command prompt cursor does not returns to new line and instead hangs on the next blank line
3. close command prompt window after code editor v 1.10.0-insider opens.
4. code editor also closes.

**Comment by joaomoreno** [comment]
This works for me both in 1.9.1 and 1.10.0-insiders.

Something is wrong about the steps in your first comment. In order to run 1.10.0-insider you should've run `code-insiders .`. You can then close the command prompt, works for me.

If you run `Code Insider.exe` directly, that won't work.

**Comment by vairamsvsjdo** [comment]
Yes! using *code-insiders .* worked. I didn't realize that file is buried in the bin folder. I made the correlation with code.exe.

I did not find this mentioned in that. What page will be a good candidate for documentation update?
