### ISSUE TITLE
Feature Request: Option to Hide Specific VS Code Tasks

### ISSUE THREAD

**Issue by brittotprince** [microsoft/vscode#206223]
Hi there,

I frequently work with multiple tasks, often organizing them into subtasks for better organization and parallelism. However, this practice results in a cluttered task list within VS Code.

I would like to suggest implementing a feature where tasks can be marked as hidden, allowing users to streamline their task lists and focus on the most relevant ones.

Thank you!

**Comment by brittotprince** [comment]
![image](https://github.com/microsoft/vscode/assets/24750537/d7d0e60b-a7bc-482a-a370-52983163a19d)

The red-marked ones are not needed. Changed names for privacy.

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/149095#issuecomment-1195711551 work?
