### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by SuperMageHuang** [Microsoft/vscode#20639]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|angular-2-snippets|aravindfz|0.1.0|
|vscode-angular2-emmet|jakethashi|1.0.11|
|Angular-BeastCode|Mikael|0.3.2|
|Angular2|UVBrain|0.4.1|

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Please provide more details, preferably in English.
