### ISSUE TITLE
VS Code integrated terminal text overlap and no show in some cases

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#206342]
Hi VS Code team,

We are testing VS Code with the GB18030-2022 Chinese Standard Code Character Set and we have found some issues with the integrated terminal text rendering. The text does not match the Windows system terminal in some cases.

Here are the details of our environment and test steps:
- VS Code Version: 1.86.2
- OS Version: Windows 11
- System Locale and display language: Chinese (Simplified, China)
  - To set the system locale, go to `Control Panel -> Clock & Region -> Region -> Change system locale to Chinese (Simplified, China)`.
  - To set the display language, go to `Start  > Settings  > Time & language > Language & region -> Change Windows display language to Chinese (Simplified)`.
- Test the GB18030 character set `①Ⅻㄨㄩ啊阿鼾齄丂丄狚狛狜狝﨨﨩ˊˋ˙–⿻〇` in different terminals
  - Copy and paste the character set to Windows PowerShell and cmd. Here is how they are displayed:
    ![image](https://github.com/microsoft/vscode/assets/14052197/4ec1c1f1-6d5c-4949-b83c-f200a4cdd9cb)

    ![image](https://github.com/microsoft/vscode/assets/14052197/3034e0ac-00aa-44d3-8a13-6f17d714941f)

  - Copy and paste the character set to VS Code integrated terminals (Windows PowerShell/cmd). Here is how they are displayed: 
    ![image](https://github.com/microsoft/vscode/assets/14052197/20ccae41-6074-45f6-8af4-269029f977cd)

    ![image](https://github.com/microsoft/vscode/assets/14052197/5c5e114f-1d19-45b2-a8ad-2da1b1d3c68d)

- The issues we have observed are:
  - For Windows PowerShell in VS Code, the character `Ⅻ` overlaps with other characters and the characters `ˊˋ˙–`do not show up at all.
  - For cmd in VS Code, the character `Ⅻ` overlaps with other characters.

We hope you can look into these issues and fix them ASAP. Thank you for your attention and support.

// cc: @devinvalenciano

**Comment by Tyriar** [comment]
@testforstephen 

> the characters ˊˋ˙–do not show up at all.

I cannot reproduce this, can you make sure you close all terminals and reopen them after switching languages? I suspect you might have had something in the terminal environment that got restored from the older session. Tested on Windows Terminal v1.19.10302.0, VS Code Insiders v1.87.0-insider (user setup) 41e601871ac9e197b6a9245072994f6904addb60, Windows 

> the character Ⅻ overlaps with other characters

The character is the same width as Windows Terminal, just the font that we're rendering with (Chromium's `monospace` fallback) renders it as a wide character. I've created a feature request to automatically scale down glyphs which is what Windows Terminal does https://github.com/xtermjs/xterm.js/issues/4969, we may or may not get to this in the next month.

Note though that I definitely would not consider this issue as blocking certification and I believe last year we passed just fine despite this. It's special behavior to scale such a character down and it may be considered unexpected in some cases.

**Comment by lhecker** [comment]
It may be worth noting that by default Windows Terminal does not scale down glyphs anymore in the latest version. If you're on a version older than 1.19.10573.0, you can force an update in the Microsoft Store application (down-left, when clicking on the Library button). Please feel free to open an issue in our repository as well, if you'd like: https://github.com/microsoft/terminal/issues

Similar to what @Tyriar said, we also found that this behavior is generally unexpected by users, and many complained about it. (In particular when we did it for glyphs commonly used in powerline-like prompts).

**Comment by testforstephen** [comment]
@lhecker I upgraded Windows Terminal from 1.18.10301.0 to 1.19.10573.0, now the Windows Terminal renders three glyphs (`①Ⅻㄨ`) overlapping as follows. Opened an issue https://github.com/microsoft/terminal/issues/16779 for Windows Terminal.
![image](https://github.com/microsoft/vscode/assets/14052197/d3a0955d-a2cc-4a26-9737-5ca9e6b1e0a8)

> I cannot reproduce this, can you make sure you close all terminals and reopen them after switching languages? I suspect you might have had something in the terminal environment that got restored from the older session. Tested on Windows Terminal v1.19.10302.0, VS Code Insiders v1.87.0-insider (user setup) https://github.com/microsoft/vscode/commit/41e601871ac9e197b6a9245072994f6904addb60, Windows

@Tyriar Tried again on Windows Terminal v1.18.10301.0/v1.19.10573.0, VS Code 1.86.2/1.87.0-insider (user-setup) https://github.com/microsoft/vscode/commit/019f4d1419fbc8219a181fab7892ebccf7ee29a2 from Windows (v10.0.22621.3155), and none of them display these characters (`ˊˋ˙–`) in the VS Code integrated PowerShell terminal. I have tried deleting and creating new terminals using the trash button around the integrated terminal view, but it does not affect the outcome.

I also noticed that when I run PowerShell as an administrator from the Windows search box, it does not show the characters ˊˋ˙– either. This is consistent with the VS Code integrated terminal behavior. This suggests that the issue might be related to some PowerShell settings that prevent these glyphs from showing up.

![image](https://github.com/microsoft/vscode/assets/14052197/6acf8753-3b76-44db-b310-e5da2218c829)

When I run PowerShell in Windows Terminal, all the characters (ˊˋ˙–) are displayed in the terminal.
![image](https://github.com/microsoft/vscode/assets/14052197/ccfaca17-6deb-43a9-b637-b99f9d811f80)

**Comment by Tyriar** [comment]
> This suggests that the issue might be related to some PowerShell settings that prevent these glyphs from showing up.

Can we exclude this from our report then as that's owned by a different team and we don't have control/insight into it?

**Comment by testforstephen** [comment]
> Can we exclude this from our report then as that's owned by a different team and we don't have control/insight into it?

@devinvalenciano might have more context about the test report doc. I'm also communicating with the globalization cert team to see if we have other ways to work around it.

**Comment by Tyriar** [comment]
It's looking like we may not be doing the scaling based on responses in https://github.com/xtermjs/xterm.js/issues/4969 as it's technically wrong. Note that the character is of an ambiguous width (some fonts have it wide, some don't) so the presentation is somewhat expected here.

**Comment by testforstephen** [comment]
> the characters ˊˋ˙–do not show up at all.

I discovered something interesting and I wanted to share it here in case it helps anyone else. I think there is a bug with the copy/paste behavior in the terminal. When I use the right click to automatically paste the clipboard content in the integrated PowerShell terminal, these characters `ˊˋ˙–` are missing. But when I use `ctrl + v` to paste the same content in the integrated PowerShell terminal, all the characters are present.
