### ISSUE TITLE
TypeScript is wrong

### ISSUE THREAD

**Issue by AtaoCareer** [Microsoft/vscode#20635]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|one-monokai|azemoh|0.2.4|
|typings-installer|benjaminromano|0.2.0|
|python|donjayamanne|0.5.8|
|vscode-html-css|ecmel|0.0.33|
|auto-close-tag|formulahendry|0.3.9|
|icon-fonts|idleberg|1.5.0|

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Please provide more details.
