### ISSUE TITLE
typescript 

### ISSUE THREAD

**Issue by deliveph** [Microsoft/vscode#20634]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.13.2|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.6|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.0.33|
|auto-rename-tag|formulahendry|0.0.11|
|vue-snippets|hollowtree|0.1.0|
|beautify|HookyQR|0.7.5|
|weex|jaylinwang|0.4.0|
|docthis|joelday|0.3.11|
|vue|liuji-jim|0.1.5|
|js-atom-grammar|ms-vscode|0.1.12|
|debugger-for-chrome|msjsdiag|2.5.3|
|vetur|octref|0.3.2|
|vscode-icons|robertohuertasm|7.2.0|
|vue|seanwash|0.4.2|
|vscode-typings|typings|0.0.5|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Please provide more details.
