### ISSUE TITLE
alt+click not working

### ISSUE THREAD

**Issue by bedouintravels** [Microsoft/vscode#20633]
Alt+Click to insert cursor is not working. It simply won't allow me to choose multiple cursors.

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.4.0-62-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|trumpsum|jerky676|1.1.2|
|html5-boilerplate|sidthesloth|1.0.1|
|open-in-browser|techer|0.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/3091
