### ISSUE TITLE
ctrl + shift + c  , cannot open ‘cmd’

### ISSUE THREAD

**Issue by zoeDylan** [Microsoft/vscode#20632]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-html-css|ecmel|0.0.33|
|TypeScriptImport|kevinmcgowan|1.17.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|seti-icons|qinjia|0.1.3|
|preview-vscode|searKing|1.1.1|

---

Steps to Reproduce:

1.keyboard shortcuts
2. ctrl + shift + c

**Comment by Tyriar** [comment]
Can you provide a screenshot of the error you're seeing?

**Comment by zoeDylan** [comment]
without any mistake ,unable to capture ,shortcut key no response. On a version can use keyboard shortcuts
![s 4ahad7bn px z0p7mlc8](https://cloud.githubusercontent.com/assets/7030260/22959131/b98131a8-f36e-11e6-9863-9da2e788e17e.png)

**Comment by Tyriar** [comment]
Do you have anything in your settings.json file?

**Comment by zoeDylan** [comment]
no , the problem in this version . The old version can

**Comment by zoeDylan** [comment]
could be os problem,I also have another software problems.

**Comment by Tyriar** [comment]
@zoeDylan it sounds like it probably is, something in your OS may be intercepting the key events.

**Comment by zoeDylan** [comment]
Thank you, can again yesterday afternoon, don't know why.
