### ISSUE TITLE
scanning folder for git repository stucks

### ISSUE THREAD

**Issue by ARoy-NI** [microsoft/vscode#206315]
Type: <b>Bug</b>

I use an existing git repo on a linux system and used version 1.84.2. With this version everything works well. I see the git repo in the source control tab. Remote development works fine.
With version 1.86.1 or 1.86.2  source control windows shows all the time scanning folder for git repository. I opened the same folder on the same machine like when I used 1.84.2.  I did a complete installation of vs code. Before the installation I deleted the .vscode-server folder on the linux system and also all directories on the windows system. Git version on the Linux system is 2.35.7.  Git plugin in VS code is enabled. VS code version is 1.86.1 shows the same behaviour. 

1. install 1.84.2 on your system
2. connect it to linux system (remote development per ssh)
3. open folder with a git branch 
4. have a look to the output of source control windows, you can do a commit or whatever.
5. deinstall 1.84.2 and install 1.86.2 
6. connect it to linux system (remote development per ssh)
7. open folder with a git branch 
8. have a look to the output of source control windows -> Scanning folder for git repos appears

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 6.1.38-rt12-LLTng-g3494faaf50f2
Connection to 'ssh-remote+172.22.60.112' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (17.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 172.22.60.112|
|OS|Linux x64 6.1.38-rt12-LLTng-g3494faaf50f2|
|CPUs|Intel(R) Xeon(R) W-2295 CPU @ 3.00GHz (18 x 3000)|
|Memory (System)|62.52GB (60.78GB free)|
|VM|0%|

Connection to 'ssh-remote+172.22.60.112' could not be established
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
cmake-tools|ms-|1.17.16
cpptools|ms-|1.19.4
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
cppperfcontrol:30973184
d34g3935:30971562
edj9j583:30969295
fegfb526:30961430
bg6jg535:30958357
dsvsc020:30973508

```

</details>

**Comment by trry-github** [comment]
I also felt stuck when using version 1.86.2

**Comment by kitswas** [comment]
Are you using remote development (tunnels/ssh)?
Does VSCode say

> Cannot activate the 'Git' extension because it depends on the 'Git Base' extension which is disabled.

when it starts up? (Look for popups at the bottom right corner)
Does the Output panel for Window have the following entry?

> [error] Cannot activate the 'Git' extension because it depends on unknown extension 'vscode.git-base': Error: Cannot activate the 'Git' extension because it depends on unknown extension 'vscode.git-base'

I have updated to 1.87, but this issue still occurs.

**Comment by kitswas** [comment]
Possibly related to https://github.com/microsoft/vscode/issues/157817

**Comment by ARoy-NI** [comment]
For me  version 1.87.0 does not work. With this version I get the Remote Extension host terminated unexpectedly ... error again that is fixed in the january release, I deinstalled VS code completely and removed everything from linux system (.vscode-server folder) but it is still not possible to work with it. I go back to the october release at least this works.

1. Are you doing remote development (tunnels/ssh) on a Linux server from a Windows machine?
yes

2. Does VSCode say
    Cannot activate the 'Git' extension because it depends on the 'Git Base' extension which is disabled.
    when it starts up? (Look for popups at the bottom right corner)
No

Does the Output panel for Window have the following entry?
    [error] Cannot activate the 'Git' extension because it depends on unknown extension 'vscode.git-base': Error: Cannot activate 
    the 'Git' extension because it depends on unknown extension 'vscode.git-base'
No

**Comment by ARoy-NI** [comment]
It tried 1.88.1 and it still not working. The source control tab does not recognize the git repo.

**Comment by philipp-baumann** [comment]
same problem for me, using 1.85.2 VSCodium. Doing remote work via ssh session from macOS to rocky linux server. 

Version: 1.85.2
Release: 24019
Commit: c8a36a69377856369f139f39ee56dd3838130fbf
Date: 2024-01-19T18:25:52.688Z (3 mos ago)
Electron: 25.9.7
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0

**Comment by ARoy-NI** [comment]
I tried the latest version 1.90.2. Still not working
Do you need more information, logs?

**Comment by ARoy-NI** [comment]
Hi there is no git channel just a github authentification channel. See picture:
![image](https://github.com/microsoft/vscode/assets/124816815/1ce70b6a-1bef-4b75-ac4e-222e2a41dc8d)
Which channel log do you want?

**Comment by kitswas** [comment]
> Hi there is no git channel just a github authentification channel. See picture: ![image](https://private-user-images.githubusercontent.com/124816815/343741583-1ce70b6a-1bef-4b75-ac4e-222e2a41dc8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODU4NzcsIm5iZiI6MTcxOTQ4NTU3NywicGF0aCI6Ii8xMjQ4MTY4MTUvMzQzNzQxNTgzLTFjZTcwYjZhLTFiZWYtNGI3NS1hYzRlLTIyMmUyYTQxZGM4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxMDUyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGM3YjlmYzAzMTc4ZTg4MGNhZGQ4ZTIxMWY0YTEyNGEwODliYTdkZDhjMTA3YjgxNjM2ZTg3ZTQ5NjNhOTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NvWfFV51PbM5coGSXU44bl6CqMHkAuT3dYL9Mi5PxjQ) Which channel log do you want?

Scroll up. It should be above GitHub. The list items are ordered alphabetically.

**Comment by ARoy-NI** [comment]
Hi
I can't scroll up. github authentification is the top entry. Maybe this is reason why my git repo isn't shown.
![image](https://github.com/microsoft/vscode/assets/124816815/3692c947-5a9d-4a6e-b5d9-97249f9d264e)

**Comment by lszomoru** [comment]
@ARoy-NI, thanks for the screenshot. It seems that for some reason the output channel for the Git extension that runs in the remote extension host has not been created. Do you mind sharing the contents of the "Window" output channel as it might have information on why the Git output channel is missing. Thanks!

**Comment by ARoy-NI** [comment]
HI 
I created a log and added it.
[Window.log](https://github.com/user-attachments/files/16028768/Window.log)
If you need further logs just write me.

**Comment by ARoy-NI** [comment]
Hi, are there any news about the problem / how I can solve it? The problem still exists in the version 1.91.1.

**Comment by lszomoru** [comment]
@sandy081, could you please review the logs (https://github.com/microsoft/vscode/issues/206315#issuecomment-2196716958) to see why the git output channel is not present? Thank you!

**Comment by sandy081** [comment]
Can you please search for git extension `@builtin git` in the extensions view and see if the extension is activated?

**Comment by lszomoru** [comment]
Closing the issue as we never received the necessary information to further investigate it.
