### ISSUE TITLE
Got "#include errors detected" in <cstdlib>

### ISSUE THREAD

**Issue by char990** [microsoft/vscode#206394]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- Version: 1.86.2 (user setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045
- OS Version: 
Edition	Windows 10 Pro
Version	22H2
Installed on	‎21/‎04/‎2022
OS build	19045.4046
Experience	Windows Feature Experience Pack 1000.19053.1000.0

Steps to Reproduce:
My cpp program got squiggles showing "#include erros detected". I found it's from 
```
 <stdexcept> - <string> - <basic_string.h> - <string_conversion.h> - <cstdlib>.
```
But the squiggles are located in a comment.

Reset IntelliSense database not working.
Close and restart vscode not working.

![image_35](https://github.com/microsoft/vscode/assets/16507999/e7ea4d86-62b9-47a8-acb4-85e20a4681f2)

My c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/opt/fsl-imx-fb/5.15-kirkstone/sysroots/cortexa7t2hf-neon-poky-linux-gnueabi/usr/include/",
                "/opt/fsl-imx-fb/5.15-kirkstone/sysroots/cortexa7t2hf-neon-poky-linux-gnueabi/usr/include/**",
                "/opt/fsl-imx-fb/5.15-kirkstone/sysroots/cortexa7t2hf-neon-poky-linux-gnueabi/usr/include/c++/11.3.0/**",
                "/opt/fsl-imx-fb/5.15-kirkstone/sysroots/cortexa7t2hf-neon-poky-linux-gnueabi/usr/include/c++/11.3.0/arm-poky-linux-gnueabi/**",
                "/home/work/github/spdlog/include/**",
                "/home/work/github/stb/",
                "${workspaceFolder}/include/",
                "${workspaceFolder}/include/**"
            ],
            "defines": [
                "__ARM_PCS_VFP"
            ],
            "cStandard": "gnu17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-arm"
        }
    ],
    "version": 4
}
```

**Comment by aeschli** [comment]
These errors come from the C++ extension.
Please file the issue against https://github.com/Microsoft/vscode-cpptools
