### ISSUE TITLE
Copilot Chat in separate window 

### ISSUE THREAD

**Issue by CBMcKay** [microsoft/vscode#206312]
Copilot Chat in a separate window. The output of the chat, especially code lines, is much too wide for the sidebar. It would be great if i could have that chat in separate window on a different monitor. This is how I use ChatGPT and other learning sites (StackOverflow, W3 schools, official docs, etc.)

**Comment by bpasero** [comment]
![image](https://github.com/microsoft/vscode/assets/900690/596ff8d6-19a2-438e-986e-438f79003a2c)
