### ISSUE TITLE
Editor Actions design is unpredictable/poor-user-experience under real use case with insufficient editing and organization features

### ISSUE THREAD

**Issue by LucienMP** [microsoft/vscode#206314]
Type: <b>Bug</b>

After setting up some extensions, and getting working on some C code you will find the "Editor Actions" (https://code.visualstudio.com/api/ux-guidelines/editor-actions)  part of the tool bar filling up so much that the buttons you want to access are annoyingly in the "..." or moving around depending on language/tab you are editing in.

I moved this bar to the "title bar" but even then it is limited to 7-8 icons, but I would like to be able to expand this count if there is space AND control layout.

Like editors of yore, it would be mice to have the functionality like user custom button bars where you can move, lock, and edit those buttons based on thier imporance based on the tab-type or language being worked with.

I suggest:
 1. Increase from 7-8 to more depending on its location to a user settable amount
 2. lock icons based on language/tab-type (common items out front)
 3.  Allow grouping since often common actions should be visible, but less common can be in a drop down there.
 4. Allow drag-n-drop to organize this bar more simply

Others are also suffering and there are many suggestions on how to fix this.  See entires such as; 

a. https://stackoverflow.com/questions/75847454/how-to-change-the-number-of-editor-action-buttons

b. https://stackoverflow.com/questions/75847454/how-to-change-the-number-of-editor-action-buttons

c. https://www.reddit.com/r/vscode/comments/lpm6fa/now_you_can_add_userdefined_buttons_to_editor/

d. https://marketplace.visualstudio.com/items?itemName=jerrygoyal.shortcut-menu-bar

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:41:37.860Z)
OS version: Linux x64 6.7.5-100.fc38.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4500)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|31.05GB (25.02GB free)|
|Process Argv|--password-store=gnome-libsecret --crash-reporter-id 79d5f0c2-29e5-4589-979f-a67c756640f3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|14.8.2
copilot|Git|1.166.0
copilot-chat|Git|0.13.2024020201
todo-tree|Gru|0.0.226
debugpy|ms-|2024.0.0
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
cmake-tools|ms-|1.17.16
cpptools|ms-|1.19.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.8.22
back-n-forth|nic|3.1.1
cmake|twx|0.0.17
todo-list|Tza|1.6.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
d34g3935:30971562
edj9j583:30969295
7j2b6412:30969109
bg6jg535:30958357

```

</details>

**Comment by benibenj** [comment]
Closing as we have already feature requests open for the mentioned improvements, such as giving more space to editor actions in the title bar. Also, FYI in case you are not aware, you can right click on an action item to hide them if you don't tend to use them
