### ISSUE TITLE
typescript happen stop

### ISSUE THREAD

**Issue by weicracker** [Microsoft/vscode#20631]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|theme-onedark|azemoh|0.4.3|
|typings-installer|benjaminromano|0.2.0|
|npm-intellisense|christian-kohler|1.2.1|
|path-intellisense|christian-kohler|1.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|theme-dracula|dracula-theme|1.2.5|
|vscode-html-css|ecmel|0.0.33|
|tslint|eg2|0.8.1|
|mithril-emmet|FallenMax|0.6.1|
|auto-rename-tag|formulahendry|0.0.11|
|Theme-Solarized-light|gerane|0.0.2|
|beautify|HookyQR|0.7.4|
|docthis|joelday|0.3.11|
|comment|karyfoundation|4.0.2|
|es6-angular-snips|kasperkeso|0.0.3|
|vscode-fileheader|mikey|0.0.2|
|js-atom-grammar|ms-vscode|0.1.12|
|vscode-icons|robertohuertasm|7.2.0|
|addDocComments|stevencl|0.0.8|
|theme-bracketslight|ullissescastro|1.0.2|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please provide information about the issue that you are seeing.

**Comment by weicracker** [comment]
![2017-02-15_101501](https://cloud.githubusercontent.com/assets/19145072/22958111/d6d803dc-f367-11e6-8c58-73cff7e48e44.png)

**Comment by mjbvz** [comment]
Two probable causes:

1. You are opening a mapped network drive. This will crash TypeScript 2.1.6. We are tracking a fix here: https://github.com/Microsoft/TypeScript/issues/13997
1. If you see a message about a missing `typescript/...` file, you may be seeing #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

If neither seems to fit for what you are hitting, please let me know

**Comment by weicracker** [comment]
Perfect solution, thank you！
![2017-02-15_102220](https://cloud.githubusercontent.com/assets/19145072/22958251/f79c3682-f368-11e6-83a5-8061f5025654.png)
