### ISSUE TITLE
node.js debug's breakpoint wrong

### ISSUE THREAD

**Issue by flypie2** [Microsoft/vscode#20637]
![image](https://cloud.githubusercontent.com/assets/12812523/22964260/9ff82826-f392-11e6-8f77-34989b6333ea.png)
when i take a breakpoint on line 15, but vscode break on line 12 ... i'm so sad /(ㄒoㄒ)/~~

**Comment by isidorn** [comment]
That trully sounds sad, assigning to @weinand to try to save the day since this is coming from our node debug extension.
Also does changing the `type` to `node2` in your `launch.json` help in any way? Also what version of vscode do you have?

**Comment by weinand** [comment]
@flypie2 could you share your launch configuration so that I can investigate what's going wrong here.

**Comment by flypie2** [comment]
`{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "启动程序",
            "program": "${workspaceRoot}/start.js",
            "cwd": "${workspaceRoot}"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "附加到进程",
            "port": 5858
        }
    ]
}`

I use babel to convert async/await to Node.js v7.5,is this affect the debugger?

**Comment by flypie2** [comment]
@isidorn @weinand 
when I changing the type to node2 in launch.json it works,
but it console "Warning: This is an experimental feature and could change at any time."
my vscode version is 1.9.1,
thank you ^.^

**Comment by weinand** [comment]
@flypie2 Yes, babel translation affects the debugger. The new node-debugger 'node2' directly supports this whereas the old 'node' does not (and you would have to setup sourcemaps explicitly).

Closing as this works for you in 'node2'.
