### ISSUE TITLE
Variable resolution: provide support for assigning a 'priority' to an individual variable value

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#206300]
Currently I can assign vscode.ChatVariableLevel with the values `Full`, `Medium`, `Short` to a variable.

In my scenario I have list of say 10 values sorted by importance of chat variable values. I would like that co-pilot includes the important values from the list that fit into the context window. One idea would be that I can assign decreasing priorities to the values and co-pilot adds the values by priority to the prompt and cuts of the lower priority values that do not fit into the context window.

Another option is to just honor the order of the array of variable values.

(See also https://github.com/microsoft/vscode/issues/206299)

// CC @jrieken

**Comment by jrieken** [comment]
> Another option is to just honor the order of the array of variable values.

I like that best

> Currently I can assign vscode.ChatVariableLevel with the values Full, Medium, Short to a variable.

I believe we will abandon levels - we didn't see it catch on and it doesn't support "trimming" like a sorted/weighted array of values does

**Comment by isidorn** [comment]
We are not focuesed on variables -> out of scope
