### ISSUE TITLE
Cursor changes into a "plus" when ALT is typed

### ISSUE THREAD

**Issue by italomaia-bk** [microsoft/vscode#206338]
Does this issue occur when all extensions are disabled?: Yes

Using xubuntu 23.10 here. If I move my mouse cursor over the vscode embedded terminal and type ALT and nothing else, the cursor will change from the regular pointer to a large "+". Esc does not turn the cursor back to normal. Cursor goes back to normal after I move it.

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. toggle on embedded terminal
2. move cursor over the embedded terminal
3. type L-ALT (no need to hold)

**Comment by meganrogge** [comment]
this is by design . you can disable it with terminal.integrated.altClickMovesCursor

**Comment by italomaia-bk** [comment]
`"terminal.integrated.altClickMovesCursor": false`

Did not solve it.

**Comment by meganrogge** [comment]
does this also happen in external terminals?
