### ISSUE TITLE
1.87 upgrade experience before Copilot Chat has upgraded is not good

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#206378]
- Upgrade from 1.86 stable to 1.87
- Copilot Chat has not yet been upgraded, and there were breaking API changes
- The chat view is empty with no visible errors. This will confuse users

We should make sure some helpful message is visible somehow

**Comment by rzhao271** [comment]
\closedWith https://github.com/microsoft/vscode/commit/019f4d1419fbc8219a181fab7892ebccf7ee29a2
