### ISSUE TITLE
Bug: hover tooltip suddenly shrinks when adjusting width.

### ISSUE THREAD

**Issue by hidaviddong** [microsoft/vscode#206310]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.2 (Universal) Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
- OS Version: Darwin x64 23.0.0

Steps to Reproduce:

https://github.com/microsoft/vscode/assets/73568310/5b5bf4c2-555b-472b-8773-ce7d66164868

**Comment by DongHY1** [comment]
similar to #194130
