### ISSUE TITLE
Integration test failure: workspace.applyEdit drops the TextEdit if there is a RenameFile later

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#206356]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=259722&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=e6d1c856-dd40-5946-2df0-58cb7c21b113&l=404

**Comment by bpasero** [comment]
Looks like a one time fluke, given 30d statistics and pass rate.

<img width="1357" alt="image" src="https://github.com/microsoft/vscode/assets/900690/c69d30bf-d521-4a6b-8791-d89d2b8c6666">
