### ISSUE TITLE
debugServerArgs is not working 

### ISSUE THREAD

**Issue by SachinSetiya** [Microsoft/vscode#20636]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.8.0-37-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.8|
|cpptools|ms-vscode|0.10.1|

---

Steps to Reproduce:

1.debug any c/c ++  program 
2.set debugServerArgs = "anything " , it is neither setted nor any error is given.
1: (145) LaunchOptions  WaitDynamicLibLoad='false'
1: (145) LaunchOptions  DebugServerArgs='anything'
1: (145) LaunchOptions  ExternalConsole='true'

**Comment by isidorn** [comment]
@SachinSetiya this sounds like an issue with the c++ extension and should be filed there https://github.com/Microsoft/vscode-cpptools
