### ISSUE TITLE
JavaScript heap out of memory when debug

### ISSUE THREAD

**Issue by algv** [Microsoft/vscode#20638]
VSCode Version: 1.9.1
node: 6.5.0
OS Version: Windows 10 x64

Cannot debug script:
```JS
var buffer = Buffer.alloc(2*1024*1024*1024 - 1); //2GB https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html#buffer_buffer_kmaxlength
console.log(buffer.length);
```
But it work nice when run from node.

And crash for small size to (example: Buffer.alloc(1024 * 1024 * 100))

**Comment by isidorn** [comment]
I can nicely run and debug this script from inside vscode both on mac and win10.
If I set a breakpoint on line 2 and stop then node will become unresponsive but vscode will not crash -> assigning to @weinand .

@algv please provide more details if you can constantly crash vscode with this. Can you still crash if you change the `type` in your "launch.json" to `node2`?

**Comment by weinand** [comment]
@algv the unresponsiveness of node-debug is expected (and cannot be fixed).

With 'node2' i just see this:
![2017-02-15_12-43-07](https://cloud.githubusercontent.com/assets/1898161/22972984/61c71258-f37c-11e6-9f7c-5d2543439c41.png)

Is that the expected behaviour?

**Comment by algv** [comment]
My "launch.json":
```
{
    "configurations": [
        {
            "type": "node2",
            "request": "launch",
            "name": "Запустить программу",
            "program": "${workspaceRoot}\\index.js",
            "cwd": "${workspaceRoot}"
        }
    ]
}
```
I run script and brecpoint work nice, but only first 10-15s.  Then debug out with error: 

> FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory

@weinand I think you not wait variable loaded (cannot see on screenshot).

**Comment by isidorn** [comment]
@algv got it. But then VSCode does not crash, only your debug session crashes. Correct?

**Comment by algv** [comment]
Yes, only debug session.

**Comment by algv** [comment]
Problem with heap size. Maximum size, what work in debug it: Buffer.alloc(1024 * 1024 * 34)
Check heap:
`require('v8').getHeapStatistics().used_heap_size`

> 1432971232

And heap_size_limit: 1501560832

**Comment by roblourens** [comment]
I can run this with no problem, is it still an issue in node 8?

**Comment by algv** [comment]
![default](https://user-images.githubusercontent.com/16474118/30018768-d4c62a5e-9166-11e7-8e49-ca867cdc6e48.png)

VS Code 1.15.1 debug session not crash, but cannot access any local variables (test1 example)

VSCode Version: 1.15.1
OS Version: Windows 10 x64

**Comment by roblourens** [comment]
Oh I do see the issue, from getting the length of a very large buffer: 

`← From target: {"id":24,"result":{"result":{"type":"object","subtype":"error","className":"RangeError","description":"RangeError: Invalid array length\n ...`

**Comment by weinand** [comment]
Works nicely for "inspector" protocol (and crashes "nicely" for legacy).
