### ISSUE TITLE
Smoke test failure: install and enable vscode-smoketest-check extension

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#206436]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=259757&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=dc7a7a05-ae89-521b-55db-0cb2ded34668&l=88

**Comment by benibenj** [comment]
Closing as rerunning fixed it and unable to repro locally
