### ISSUE TITLE
Markdown is not recognized on VScdoe but working on Jupyter notebook 

### ISSUE THREAD

**Issue by MRidokatz** [microsoft/vscode#206453]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I am writing a markdown on VScode using the latest jupyter extension and receive an error message "Error: Expected node of symbol group type, but got node of type cr" (on ipynb)

This markdown works well on Jupyter lab/ notebook and fails only on VScode:
$$
V(S) = \left\{\begin{array}\\ f(S) + \lambda, & S \geq K_0 \\
h(S) + \lambda, & S \leq K_0 \end{array}\right.
$$

![Jupiter Notbook working correctly](https://github.com/microsoft/vscode-jupyter/assets/117187333/8d18bb24-f149-47c0-ade7-54bde496220c)
![VScode Markdown issue ](https://github.com/microsoft/vscode-jupyter/assets/117187333/903f181d-5240-42e1-a4be-1837b4a4ffbf)

code-server (1.83.1, product-team-sandbox.wsq.io, server-distro)
Jupyter Extension Version: 2023.9.100.
Python Extension Version: 2023.20.0.
Platform: linux (x64).
code-server: v4.18.0-r3
VScode: 1.83.1

### VS Code Version

1.83.1

### Jupyter Extension Version

2023.9.100

### Jupyter logs

```shell
code-server (1.83.1, product-team-sandbox.wsq.io, server-distro)
Jupyter Extension Version: 2023.9.100.
Python Extension Version: 2023.20.0.
Platform: linux (x64).
Workspace folder /mnt/home0/wst/workspaces/user_details/default, Home = /home/wstcoredev
12:27:12.380 [info] Telemetry level is off
12:27:12.380 [info] Experiments are disabled, only manually opted experiments are active.
12:27:12.912 [info] Start refreshing Kernel Picker (1708604832912)
12:27:12.920 [info] Not using Pylance
```

### Coding Language and Runtime Version

Python 3.9.5 and 

### Language Extension Version (if applicable)

Python Extension Version: 2023.20.0.

### Running Jupyter locally or remotely?

N/A or Not sure

**Comment by mjbvz** [comment]
Closing as upstream
