### ISSUE TITLE
Remember project folders & Support for opening multiple project folders in the same window

### ISSUE THREAD

**Issue by xayden** [Microsoft/vscode#20643]
Right now every time I open VS Code I've to locate the project folder every time, and opening a new project folder closes current used files and open a new window with the new project folder, which is really annoying, I hope these issues will be fixed soon.

**Comment by ozylog** [comment]
+1

**Comment by josh64x2** [comment]
I'd love support for opening multiple project folders as well, similar to the way atom allows.

**Comment by ozylog** [comment]
one reason i haven't moved on from atom

**Comment by joaomoreno** [comment]
You might want to follow #2686 and #48
