### ISSUE TITLE
Visual Studio Code insiders is now sending `textDocument/didOpen` messages for notebooks.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#206487]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.87.0-insider (user setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
- OS Version: Windows 10 WSL

Steps to Reproduce:

1. Install Pylance and Jupyter extensions
2. Open VS code in WSL
3. Set `"python.trace.server": "verbose"` in your settings.json
4. Create a notebook and save it to disk
5. Edit a cell

If you look at the trace log output for the `Python Language Server` you'll see that we're getting `textDocument/didOpen` notifications  in Pylance. 

According to this capability: 

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#notebookDocument_synchronization

And this setting here:

https://github.com/microsoft/pyrx/blob/4c00dacee634e2c1b29524f41f02065624a8534a/packages/pylance-internal/src/server/asyncServer.ts#L659

We should only be getting `notebookDocument/didOpen` and `notebookDocument/didChange` events.

On Windows and in the stable version of VS code, this is true. On the insiders versions we seem to sometimes also get `textDocument/didOpen` and `textDocument/didChange` events for notebook cells as well.

**Comment by rchiodo** [comment]
This breaks notebooks for pylance as we don't find any of the notebook cells.

**Comment by heejaechang** [comment]
it looks like with the same selector, `vscode.languages.match` such as this https://github.com/microsoft/vscode-languageserver-node/blob/main/client/src/common/notebook.ts#L493 `fails` in `insider` but `pass` in `stable` in `WSL`

2 inputs for the `match`, selector and document (uri) seems identical.

and it only happens with `WSL`, even insider, `match` works as expected with windows.

* for this particular case, we are using this `notebook selector`

```
{
        notebookSelector: [
            {
                notebook: undefined,
                cells: [{ language: 'python' }],
            },
        ],
    }
```

**Comment by heejaechang** [comment]
might be related to this? https://github.com/microsoft/vscode/pull/205351

**Comment by heejaechang** [comment]
shouldn't this issue's priority bump up since now it got into stable?

**Comment by XuShenLZ** [comment]
bump this issue again. It is really bothering now with the new version. Looking forward to some fix soon

**Comment by Khoa-NT** [comment]
Bumping this again. I reported this problem at https://github.com/microsoft/vscode-jupyter/issues/15276. It's been driving me crazy for 3 days. I thought I did something wrong while modifying Ruff.

**Comment by jrieken** [comment]
@dbaeumer This is likely related to my change but I also wonder about the inner workings here. For the VS Code API it is expected that the `didOpen` event fires for all documents - no matter if they are a notebook cell or a standalone document.

**Comment by dbaeumer** [comment]
The underlying problem is a URI comparison with an un-transformed remote URI:

![Image](https://github.com/microsoft/vscode/assets/1931590/76350384-a807-4144-970a-0d68cb0f7842)

**Comment by jrieken** [comment]
This is an interesting issue and something that might strike us in other places. The gist is that `CellUri.parse(...).notebook` cannot be safely be used in the EH. This is because uris of notebooks get transformed (when entering the EH) but cell-uris are not. This means uri-equality checks fail. However, text document identity checks will work correctly. 

I have fixed this issue with a document identity check but IMO there is some debt

* we either transform cell uris
* we stop using the property `notebook` the `CellUri.parse` util


@rebornix Have you encountered this issue before? Are workarounds in place already or is this the first case this happens on the EH?

**Comment by justschen** [comment]
@rchiodo can you verify if this has been fixed in the latest insiders!

**Comment by heejaechang** [comment]
are you guys hot fix stable as well? once fix is verified in insider?

**Comment by justschen** [comment]
@heejaechang yes, if this fix is verified in insiders, recovery 1 for stable is currently planned for Thursday morning.

**Comment by rchiodo** [comment]
Yes it has been fixed for me in insiders. /verified

**Comment by justschen** [comment]
@rchiodo fantastic, tysm!
