### ISSUE TITLE
Show range corresponding an outline entry

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#206426]
I wanted to implement a tree-sitter parsing tree explorer using outline but realized that double clicking on an outline entry only jumps the cursor and doesn't highlight the corresponding range. 

Several notes here: 

- The jump of the cursor is a bit difficult to notice. It would be great to either change selection or do what go-to-references/refactor-preview does by quickly highlighting the background.

- It would be great to have a selection set for the whole range on some gesture

**Comment by jrieken** [comment]
Let's do double click to select the whole element, not just set the selection range

**Comment by the-coder-o** [comment]
Making the cursor jump more noticeable, perhaps by changing the selection or by quickly highlighting the background in a similar manner to what is done in go-to-references or refactor-preview features.
Having the option to select the entire range corresponding to an outline entry through some gesture or action.

**Comment by the-coder-o** [comment]
Look into the settings or preferences of the IDE to see if there is an option to enable such behavior.
Check if there are any extensions available that enhance the outline view functionality.
If such options do not exist, you could propose these changes as a feature request to the development community of the IDE. Most modern IDEs have a repository or a forum (like GitHub, GitLab, etc.) where users can submit feature requests and suggestions for improvements.
If you're comfortable with extension development, you could try creating your own extension that implements these features.

**Comment by jrieken** [comment]
To verify, open outline for a file and test that

* single click reveals the symbols but focus stays in the outline pane
* double click reveals the symbols, focuses the editor, and selects the whole symbol
