### ISSUE TITLE
vs code issue

### ISSUE THREAD

**Issue by gy09535** [Microsoft/vscode#20644]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.7.0|
|mono-debug|ms-vscode|0.13.0|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please provide info about the bug
