### ISSUE TITLE
Collapsing doesn't work ok if lines are not indented the same of the opening and closing tags in a .config file

### ISSUE THREAD

**Issue by Bokac30** [Microsoft/vscode#20646]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.6|
|xml|DotJoshJohnson|1.7.0|
|tslint|eg2|0.8.1|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|Theme-TomorrowKit|ms-vscode|0.1.3|
|debugger-for-chrome|msjsdiag|2.5.3|
|yo|samverschueren|0.9.3|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Can you provide a small code example?

**Comment by aeschli** [comment]
Our folding strategy is based on indentation only. The request to be language aware is #3422
