### ISSUE TITLE
 Using the new Templates much easier to  navigate 

### ISSUE THREAD

**Issue by slaffyJoe24** [microsoft/vscode#206432]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:
1.  Security  Suggested   to get a pull request  Can  be read.
2. But cannot be edit 
3.   I don't mean the extension You can use those when you. Have to Configure  eligibility 
4. But not all can apply can cause to much traffic to your network .✌️👍👍

**Comment by the-coder-o** [comment]
The user is affirming the need to determine if the issue occurs without extensions being active in VS Code.
They are referring to some security suggestion related to a pull request.
There is mention of something that cannot be edited, though it's not clear what "it" refers to.
They discuss something regarding the eligibility configuration.
Finally, they point out a concern about network traffic, which might suggest that the issue has something to do with network activity, possibly in relation to extensions or VS Code features that sync or communicate over the network.
The steps to reproduce the issue are not clearly defined, which could make it difficult for someone trying to help to understand and replicate the issue. If this is part of a bug report or a feature request, it would be beneficial to clarify each step and provide a concise and clear description of the issue, including specific actions, expected results, and actual results.

**Comment by meganrogge** [comment]
Your issue is super unclear. Pls provide repro steps in a new issue.

**Comment by the-coder-o** [comment]
okey
