### ISSUE TITLE
Context menu in Explorer for Workspaces - Add Settings

### ISSUE THREAD

**Issue by theking2** [microsoft/vscode#206431]
I kind of expected the settings for the workspace in the context menu in the explorer. In Detail

1. Open a workspace
2. Right click the Workspace name in the Explorer
3. A context menu appears containing an item `Settings` that opens the settings for the current workspace.
![image](https://github.com/microsoft/vscode/assets/1612152/d94be842-4bd7-49a5-8517-64e344faf59a)

**Comment by sandy081** [comment]
This action is already available on the Gear action in the bottom left and also on the menu File > Settings
