### ISSUE TITLE
C++ Extensions by Microsoft not found

### ISSUE THREAD

**Issue by vpp612** [microsoft/vscode#206446]
Type: <b>Bug</b>

After installing Visual Studio Code for Endeavouros Linux and selecting extension, I cannot find C++ Extensions by Microsoft.

VS Code version: Code - OSS 1.86.2 (Commit unknown, 2024-02-18T15:08:27.877Z)
OS version: Linux x64 6.7.6-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3899)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|15.56GB (11.12GB free)|
|Process Argv|--unity-launch /home/vpp/Workspaces/Udemy Frank|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.1.4
Doxygen|bbe|1.0.0
cmake-format|che|0.6.13
doxdocgen|csc|1.4.0
dbclient-jdbc|cwe|1.3.4
vscode-mysql-client2|cwe|7.0.6
c-cpp-project-generator|dan|1.2.13
code-runner|for|0.12.1
c-cpp-runner|fra|9.4.7
vscode-c-cpp-config|fra|6.0.0
vscode-c-cpp-dev-extension-pack|fra|0.10.0
gitlab-workflow|Git|4.3.2
better-cpp-syntax|jef|1.21.1
vscode-clangd|llv|0.1.26
vscode-dotnet-runtime|ms-|2.0.1
python|ms-|2024.0.1
makefile-tools|ms-|0.8.22
csharp|muh|2.18.16
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
vscode-icons|vsc|12.7.0
debug|web|0.27.0

(1 theme extensions excluded)

</details>

**Comment by vpp612** [comment]
Thanks for your comments!
I don't know where to find which marketplace is in use. I have tried installing it from VSIX file -> no help. Can't see it.

**Comment by vpp612** [comment]
Ok, I just found that you suggested checking settings.json. Just a minute.

**Comment by vpp612** [comment]
I didn't find anything related to marketplace. Should it be found in every settings.json file in my pc?

**Comment by the-coder-o** [comment]
> Thanks for your comments! I don't know where to find which marketplace is in use. I have tried installing it from VSIX file -> no help. Can't see it.

![Screenshot 2024-02-28 210113](https://github.com/microsoft/vscode/assets/115723431/9c5fdc7e-33d2-445d-875f-3f0d8bf91482)
![Screenshot 2024-02-28 210119](https://github.com/microsoft/vscode/assets/115723431/8bca9516-e498-4e5d-acdc-daf16d1aa31b)
![Screenshot 2024-02-28 210124](https://github.com/microsoft/vscode/assets/115723431/eb2773c2-4f85-43b5-b422-b77d90b5d356)

**Comment by vpp612** [comment]
This appears pretty challenging. I have removed and installed the "code" as it is called in this linux distro, to no avail.

I have several times installed the VSIX extension, code has indicated that it is installing the extension and provided even a restart button. But the extension won't appear. It is somewhat frustrating that many computer courses explain how easy it is to get visual studio code working with proper settings, but it is not.

**Comment by vpp612** [comment]
I was thinking, if the existing extensions could prevent the installation of another extension? I might have some odd extensions installed which I cannot easily even uninstall.

**Comment by vpp612** [comment]
This morning I removed 'code' and all its settings from HOME/.vscode-oss directory. Now my vscode works with its default settings and extensions, but this basic extension cannot be found in the marketplace and cannot be installed from VSIX file. As if it had been prevented from installing itself or working in this version.

**Comment by vpp612** [comment]
I managed to resolve the missing C/C++ Extension issue by switching to another binary, proprietary MS build of visual studio, visual-studio-code-bin. But, something is still not right, naturally. When the default build task is defined, I see that the file path in the compiler command is quoted with single quote marks, preventing an expression of "*.cpp" from expanding to all cpp files I have in the folder and resulting in compiler error because there is no file by name '*.cpp'. I have no glue where the quotation marks come from.

**Comment by vpp612** [comment]
Asterisks did not print out in the previous message. You can imagine them . :)

**Comment by sandy081** [comment]
Looks like Visual Studio Code for Endeavouros Linux is not coming from the official Microsoft build.
