### ISSUE TITLE
How to delete blank lines ? remove duplicate characters ? and delete duplicate lines ? 

### ISSUE THREAD

**Issue by xianghongai** [Microsoft/vscode#20649]
- VSCode Version: 1.9.1
- OS Version: windows 10

---

### How to delete blank lines ? 

```
1


2

3
```
to
```
1

2

3
```
&
```
1


2

3
```
to
```
1
2
3
```

---

### How to remove duplicate characters ? 
```
112233445566aabbccddee??//
```
to
```
123456abcde?/
```

---

### How to delete duplicate lines ? 

```
123
123
abc
abc
```
to
```
123
abc
```

**Comment by Bill-Stewart** [comment]
You should ask how-to questions on stackoverflow.com.

**Comment by xianghongai** [comment]
the default keybinds has command api : 
```js
// - editor.action.sortLinesAscending
// - editor.action.sortLinesDescending
```
so my question should be part of the editor function, not the other way, 
I am asking the developer, with other ways and ask questions.

**Comment by joaomoreno** [comment]
Not sure I understand. There are no special actions to remove empty lines, remove duplicate characters. You can duplicate a line with <kbd>Shift Alt Down/Up</kbd>
