### ISSUE TITLE
Extension info does not match marketplace

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#206416]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.2
- OS Version: Win 11 23H2

Steps to Reproduce:

1. Open https://marketplace.visualstudio.com/items?itemName=ms-python.mypy-type-checker

![image](https://github.com/microsoft/vscode/assets/12128514/3ea8864f-9961-44a7-87d4-ad6581664712)

2. Open the same extension in VS Code

![image](https://github.com/microsoft/vscode/assets/12128514/920ac5e6-c322-4a79-85bc-ea1449fef51c)

- Web "Released on" matches "Published", okay.
- Web "Last updated" matches "Last released"
- Code "Last updated" is different

Maybe a duplicate of https://github.com/microsoft/vscode/issues/164333#issuecomment-1294867079

**Comment by sandy081** [comment]
Last updated is when user has updated this extension.
