### ISSUE TITLE
Typescript not being recompiled on changes (it was working before the update)

### ISSUE THREAD

**Issue by ignaciolarranaga** [Microsoft/vscode#20645]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|nativescript|Telerik|0.6.1|
|githistory|donjayamanne|0.1.5|
|nativescript-ng2-snippets|wwwalkerrun|1.2.0|

---

Steps to Reproduce:

1. Just make changes.
There is no visible error too, just the .js files do not change.

**Comment by mjbvz** [comment]
Compile on save is not functionality VSCode automatically provided. How were you compiling before? A task? Script?

**Comment by mjbvz** [comment]
Closing as this seems to be an external issue. @ignaciolarranaga Please provide additional details if you do not believe this is the case
