### ISSUE TITLE
in css double-clicking a word with ! or # doesn't select

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#20642]
Have a hex-color value or use the !important directly, double click them, only the portion after that gets selected..

**Comment by aeschli** [comment]
Double clicking uses the `editor.wordSeparators` setting to figure out what to select.

**Comment by suyuTech** [comment]
hah、I have encountered the same problem. 
It is awesome that we can use "editor.wordSeparators" to customize by ourselves.
Thanks a lot!
