### ISSUE TITLE
[Chat Participant API] [Regression] defaultChatParticipant should be not needed in enabledApiProposals

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode#206414]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Insider of 2024-02-27
- OS Version: Windows

Note: with Insider of 2024-02-21, it is working: defaultChatParticipant is not needed in enabledApiProposals

Steps to Reproduce:

1. https://github.com/microsoft/vscode-azureapicenter
2. npm install
3. Press `F5`

Expected:

Run the Chat feature normally. (It works in Insider of 2024-02-21)

Actual:

Meet below error:
![image](https://github.com/microsoft/vscode/assets/1050213/cb3b5ea0-2ab5-4d9d-8c9c-60459d58b238)

cc @isidorn

**Comment by isidorn** [comment]
azure-api-center does not request `defaultChatParticipant` in `package.json`. So this feels like a bug.

**Comment by jrieken** [comment]
@formulahendry This is very likely because you assign a `fullName` to your particpant. We have moved that to the default participant proposal because other names aren't shown anywhere. Please check and adopt. You should not have to be depending on the defaultChatParticipant-proposal

**Comment by formulahendry** [comment]
Thanks @isidorn and @jrieken for the quick turnaround! ❤️  After removing `fullName` in participant, our extension could run in Insider of 2/27!
