### ISSUE TITLE
debug a Python project by FastAPI mode, python process is not response.

### ISSUE THREAD

**Issue by codejie** [microsoft/vscode#206423]
Type: <b>Bug</b>

While project imports the follow libs together, this issue will occur.

''' Python
from fastapi import FastAPI
import akshare

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:13.651Z)
OS version: Darwin x64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.46GB free)|
|Process Argv|--crash-reporter-id 475692d4-6900-4a0b-b92f-6c394986293c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.0.0
isort|ms-|2023.10.1
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.1.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
hexeditor|ms-|1.9.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
cppperfnew:30973185
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
e3gdj431:30958358
dsvsc020cf:30973509
666c4381:30973075

```

</details>

**Comment by roblourens** [comment]
It's not clear what the issue is. But this doesn't sound like an issue with vscode. If you think it is, please file an issue on the Python extension repo with much more detail

**Comment by codejie** [comment]
> It's not clear what the issue is. But this doesn't sound like an issue with vscode. If you think it is, please file an issue on the Python extension repo with much more detail

I agree, it should be a Python Debuger extension issue, because it is ok while try to run fastapi project by nvicorn in terminal not in vscode.
