### ISSUE TITLE
Syntax highlighting doesn't change when commenting out class inheritence part (part starting from colon[:])

### ISSUE THREAD

**Issue by 3rdey3** [Microsoft/vscode#20658]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|vim|vscodevim|0.5.3|

---

Steps to Reproduce:

1. declare a class with inheritance. i.e. public class CustomBootstrapper : DefaultNancyBootstrapper
2. try to comment out everything after : with // or /* */

![code_2017-02-15_20-42-00](https://cloud.githubusercontent.com/assets/20192686/22979056/3f4680cc-f3bf-11e6-8f43-c6db0e8494e3.png)
 
![code_2017-02-15_20-44-49](https://cloud.githubusercontent.com/assets/20192686/22979195/b1c258a6-f3bf-11e6-905e-b0d8e0342824.png)

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1243
