### ISSUE TITLE
An unexpected error occurred that requires a reload of this page.

### ISSUE THREAD

**Issue by Llamaisthebest** [microsoft/vscode#206599]
The workbench failed to connect to the server (Error: connection record disposed by ConnectionHub: {
"errorMessage": "Failed to start VS Code Remote server.",
"originalErrorType": "<no original type>",
"errorCode": -1,
"errorType": "GenericError",
"stack": "Error: Failed to start VS Code Remote server.\n at [CODESPACE_URL]\n at [CODESPACE_URL]\n at [CODESPACE_URL]\n at [CODESPACE_URL]\n at d ([CODESPACE_URL]\n at a ([CODESPACE_URL]"
} $1 $1)

Everytime i open it says this and when i reload it just repeats the same thing.

Version: 1.86.0-insider
Commit: 81725794264e4c0fddbc1b3b728013744ae90840
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by Llamaisthebest** [comment]
![Screenshot 2024-03-01 161107](https://github.com/microsoft/vscode/assets/86656246/169ef0fe-3e0d-4fdf-8b7d-8ccaca1d9c12)

**Comment by connor4312** [comment]
Please report this on https://gh.io/ghcs-feedback

**Comment by Llamaisthebest** [comment]
ah ok thank you
