### ISSUE TITLE
Syntax highlight is broken when TypeScript in HTML

### ISSUE THREAD

**Issue by dojyorin** [microsoft/vscode#206584]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0
- OS Version: Windows 11 23H2 (Windows App) / Chrome 122.0.6261.95 (vscode.dev)

Steps to Reproduce:

1. Open editor with language mode to "HTML".
2. Write TypeScript in `<script type="text/typescript">`.

Syntax parsing and suggestion work fine, only highlight is broken.

I had this problem when transpiling and running TS to JS within HTML.
( See https://qiita.com/dojyorin/items/00c167d0b4b41872b4a2 )

![image1](https://github.com/microsoft/vscode/assets/1251857/40f57064-99ff-4ff2-abd0-9b2270c05a7f)
![image2](https://github.com/microsoft/vscode/assets/1251857/86517297-9712-433e-8f87-6e56416efd32)

**Comment by aeschli** [comment]
The grammar that we use for syntax highlighting doesn't support `<script type="text/typescript">`
You can file a feature request against https://github.com/textmate/html.tmbundle.

The focus is on HTML as supported by browsers.

@Yoyokrazy I don't think this issue and https://github.com/microsoft/vscode/issues/206486 are related
