### ISSUE TITLE
vscode.dev: query argument to use v1.85 does not work

### ISSUE THREAD

**Issue by jichan3751** [microsoft/vscode#206570]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:  1.85.1
- OS Version: Using vscode.web with remote tunneling on Ubuntu 18.04 LTS

Steps to Reproduce:

1. Setup vscode remote tunneling on the remote device (following instructions in [link](https://code.visualstudio.com/docs/remote/tunnels) )
2. To use 1.85 version of vscode, as shown in the [link](https://code.visualstudio.com/docs/remote/faq#_can-i-run-vs-code-server-on-older-linux-distributions), go to https://vscode.dev/tunnel/my_device_name?vscode-version=0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2 

The error pops up and I cannot open the project directory:
<img width="529" alt="Screenshot 2024-02-29 at 1 30 04 PM" src="https://github.com/microsoft/vscode/assets/17326172/88d150bd-7005-41fb-9ed4-8bc80ead85d5">

An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: No remote extension installed to resolve tunnel.)

The query "?vscode-version=0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2" used to work last week, but seems like it is not working now.

**Comment by connor4312** [comment]
vscode.dev always pulls the latest version of the remote tunnels extension, and the latest version of that extension is not compatible with 1.85: we're on 1.87 now.

Fixing this is complex and I don't have plans to do so at the moment

**Comment by jichan3751** [comment]
I see. thanks for the reply.
I think it would be better to update the [documentation](https://code.visualstudio.com/docs/remote/faq#_can-i-run-vs-code-server-on-older-linux-distributions) so that 1.85 is not supported on vscode.dev.
It is currently saying that:

> On web, you can add the following query argument [?vscode-version=0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2](https://vscode.dev/?vscode-version=0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2) to use VS Code release 1.85.
