### ISSUE TITLE
tasks.runOptions.runOn folderOpen in WSL causes restart prompt

### ISSUE THREAD

**Issue by limarkxx** [microsoft/vscode#206538]
Type: <b>Bug</b>

Create a project folder in WSL and add 
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Test",
      "type": "shell",
      "command": "echo 123",
      "group": "none",
      "runOptions": {
        "runOn": "folderOpen"
      },
      "problemMatcher": []
    }
  ]
}
```
as .vscode/tasks.json
Open the project folder in VSCode and it will prompt 
```
A setting has changed that requires a restart to take effect
Press the restart button to restart Visual Studio Code and enable the setting.
```
However clicking on restart does not change anything and the prompt shows up again once the editor loads again

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600K (16 x 3686)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.70GB (6.82GB free)|
|Process Argv|--crash-reporter-id bc44750e-cf61-47f7-a1ea-8efeda56cf75 --crash-reporter-id bc44750e-cf61-47f7-a1ea-8efeda56cf75|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600K (16 x 3686)|
|Memory (System)|15.47GB (13.07GB free)|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.86.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
cppperfnew:30973185
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
dsvsc020cf:30973509

```

</details>

**Comment by meganrogge** [comment]
does the task get run?

**Comment by limarkxx** [comment]
Yes, the task will run in the background

**Comment by meganrogge** [comment]
what happens if you comment out your settings.json file?

**Comment by limarkxx** [comment]
There is no file in the project directory except .vscode/tasks.json

**Comment by meganrogge** [comment]
a gif would help, this is really odd

**Comment by limarkxx** [comment]
I wiped my %APPDATA%/Code/User/settings.json file and the problem no longer occurs.
