### ISSUE TITLE
vscode run dotnet restore error

### ISSUE THREAD

**Issue by idle518** [Microsoft/vscode#20654]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.1|
|csharp|ms-vscode|1.7.0|
|vsc-angular-cli|web-dave|0.1.1|

---
when i run dotnet restore the terminal list errores as  follow:
error: Unable to resolve 'runtime.any.System.Globalization.Calendars (>= 4.3.0)' for '.NETCoreApp,Version=v1.1 (win10-x64)'.
error: Unable to resolve 'runtime.any.System.IO (>= 4.3.0)' for '.NETCoreApp,Version=v1.1 (win10-x64)'.
error: Unable to resolve 'runtime.win.System.IO.FileSystem (>= 4.3.0)' for '.NETCoreApp,Version=v1.1 (win10-x64)'.
error: Unable to resolve 'runtime.win.System.Net.Primitives (>= 4.3.0)' for '.NETCoreApp,Version=v1.1 (win10-x64)'.
error: Unable to resolve 'runtime.win.System.Net.Sockets (>= 4.3.0)' for '.NETCoreApp,Version=v1.1 (win10-x64)'.
error: Unable to resolve 'runtime.any.System.Runtime.Handles (>= 4.3.0)' for '.NETCoreApp,Version=v1.1 (win10-x64)'.
error: Unable to resolve 'runtime.any.System.Text.Encoding (>= 4.3.0)' for '.NETCoreApp,Version=v1.1 (win10-x64)'.
error: Unable to resolve 'runtime.any.System.Text.Encoding.Extensions (>= 4.3.0)' for '.NETCoreApp,Version=v1.1 (win10-x64)'.
error: Unable to resolve 'runtime.any.System.Threading.Tasks (>= 4.3.0)' for '.NETCoreApp,Version=v1.1 (win10-x64)'.
error: Unable to resolve 'runtime.any.System.Threading.Timer (>= 4.3.0)' for '.NETCoreApp,Version=v1.1 (win10-x64)'.
error: Unable to resolve 'runtime.win7-x64.Microsoft.NETCore.DotNetHost (>= 1.1.0)' for '.NETCoreApp,Version=v1.1 (win10-x64)'.
error: Unable to resolve 'runtime.win7-x64.runtime.native.System.IO.Compression (>= 4.3.0)' for '.NETCoreApp,Version=v1.1 (win10-x64)'.

**Comment by joaomoreno** [comment]
Please file this issue in https://github.com/OmniSharp/omnisharp-vscode
