### ISSUE TITLE
"editor.occurencesHighlight" : "off" does not correctly work when switching editors

### ISSUE THREAD

**Issue by adusamr** [microsoft/vscode#206504]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.87.0
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Set "editor.occurencesHighlight" : "off" in settings.json
2. Open two editors and open file like this:
```
aaa bbb aaa bbb
```
3. If the cursor is on "aaa", once switch to another editor and get back to this file by keyboard shortcut or mouse click, the occurences highlight of "aaa" appears and it does not disappear even when moving the cursor to "bbb".

**Comment by gjsjohnmurray** [comment]
See also #206486

**Comment by Yoyokrazy** [comment]
Closing in favor of #206486 with a more detailed repro + video. Marked as candidate, fix incoming.
