### ISSUE TITLE
在过去5分钟内，TypeScript语言服务意外中止了5次

### ISSUE THREAD

**Issue by semmy2010** [Microsoft/vscode#20655]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.13.2|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.6|
|vscode-html-css|ecmel|0.0.33|
|auto-rename-tag|formulahendry|0.0.11|
|vue-snippets|hollowtree|0.1.0|
|beautify|HookyQR|0.8.0|
|sky-react-create-snippet|lulinmemeda|0.0.3|
|vscode-icons|robertohuertasm|7.2.0|
|vue|seanwash|0.4.2|
|guides|spywhere|0.6.1|
|react-beautify|taichi|0.3.0|

---

Steps to Reproduce:
在过去5分钟内，TypeScript语言服务意外中止了5次
1.
2.

**Comment by mjbvz** [comment]
Two probable causes:

1. You are opening a mapped network drive. This will crash TypeScript 2.1.6. We are tracking a fix here: https://github.com/Microsoft/TypeScript/issues/13997
1. If you see a message about a missing `typescript/...` file, you may be seeing #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

If neither seems to fit for what you are hitting, please let me know
