### ISSUE TITLE
Local Variable values not displaying when debugging in VS Code

### ISSUE THREAD

**Issue by Yajur-Grover** [microsoft/vscode#206581]
When setting a breakpoint in a JavaScript source file in a React Native Windows application, with a Node.js debugger attached, there are no local variables being displayed in the Variables section in the Run and Debug menu. Additionally, when I add variables to 'Watch', they all evaluate to the following error message: 'Uncaught Error: Can't evalInFrame: Environment not found'. 

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0-insider
- OS Version: Windows 11 Enterprise

Steps to Reproduce:

1. Clone React Native Gallery and build and run the application.
2. Enable Direct Debugging for VS Code using the instructions here: https://microsoft.github.io/react-native-windows/docs/debugging-javascript#direct-debugging.
3. Set a breakpoint on any onPress function on the VirtualizedListExamplePage.js file.
4. Add some variables within that function to 'Watch'.
5. Wait until the break point is hit and look at the value of the variables in 'Watch'.

Screenshot of current errors:

Watch section:
![image](https://github.com/microsoft/vscode/assets/157416350/16c783b9-2b62-4103-aa01-9034481d3f4a)

Corresponding break point:
![image](https://github.com/microsoft/vscode/assets/157416350/dd29a7df-d7bc-4e40-b5c4-1a9229c02813)

**Comment by roblourens** [comment]
Please file an issue on the React Native debug extension, thanks

**Comment by Yajur-Grover** [comment]
> Please file an issue on the React Native debug extension, thanks

@roblourens Have opened an issue on the RN Debug extension. However, I tested the issue with all extensions disabled and the error was still reproingh - does this mean the error could be a general VS Code issue?

**Comment by roblourens** [comment]
Don't you need the react native extension to debug this app?

**Comment by gabor-seres-sap** [comment]
Hi @Yajur-Grover, Hi @roblourens,

Please look into a related and more generic issue what I created: https://github.com/microsoft/react-native-windows/issues/12654

As I detailed this **direct debugging using Hermes JS engine** issue affects

1. Edge Developer Tools
2. VS Code built-in Node.js debugger
3. VS Code React Native Tools extension
4. Facebook Flipper: https://fbflipper.com/

In RNW 0.72 https://www.nuget.org/packages/ReactNative.Hermes.Windows/ NuGet package was replaced with https://www.nuget.org/packages/Microsoft.JavaScript.Hermes
