### ISSUE TITLE
Tab key does not insert either spaces or tabs - does nothing. Tab key works in other editors

### ISSUE THREAD

**Issue by rajivsam** [microsoft/vscode#206594]
Type: <b>Bug</b>

Action: Pressing the tab key in a python or any text file
Expected Result: Insert x number of spaces
What Happens: Nothing
What Have I tried: All the suggestions in the vscode support forums

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:51.279Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|. --crash-reporter-id b565e731-2c3c-4fce-846b-93f833794f0a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pandoc|Chr|0.4.5
pythonsnippets3|Eri|3.3.20
markdown-all-in-one-for-web|fan|3.5.2
vscode-github-actions|git|0.26.2
julia-debug|Jud|0.0.32
language-julia|jul|1.73.2
rainbow-csv|mec|3.11.0
vscode-docker|ms-|1.29.0
autopep8|ms-|2023.8.0
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.348.0
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
pandocciter|not|0.10.4
pandoc-markdown|rso|0.1.2
markdown-preview-enhanced|shd|0.8.11
even-better-toml|tam|0.19.2
vscode-md|Tob|0.6.2
simple-rst|tro|1.5.4
typycopilot|TyP|1.0.1
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
cppperfnew:30973185
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
ccp2r3:30958157
dsvsc020:30976470
jchc7451:30973076

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the advice at https://github.com/microsoft/vscode/issues/206519#issuecomment-1970968225 to check whether you have added a keybinding that uses the Tab key.

If you haven't I suggest you use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by rajivsam** [comment]
@gjsjohnmurray , thanks, keybindings was the issue. Also thanks for the pointer to Start Extension Bisect.

**Comment by gjsjohnmurray** [comment]
Glad I could help. Please close your issue.

**Comment by rajivsam** [comment]
Thanks for your help @gjsjohnmurray . Closing it.
