### ISSUE TITLE
Russian locale in the editor is not support after VS17

### ISSUE THREAD

**Issue by hoine** [Microsoft/vscode#20659]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|ue4-snippets|CAPTNCAPS|0.6.0|
|python|donjayamanne|0.5.8|
|format-indent|Kasik96|1.3.0|
|cpptools|ms-vscode|0.10.1|
|csharp|ms-vscode|1.7.0|
|RustyCode|saviorisdead|0.19.1|
|unity-debug|Unity|1.1.0|
|unity-snippets|YclepticStudios|0.1.2|

---

Steps to Reproduce:
1. Create any file in VS17
2. Add a russian comments
3. Open file in VS Code
4. Example: //��������� ��������

**Comment by joaomoreno** [comment]
Very likely the file isn't open in the right encoding. You can use the encoding status bar button to reopen the file with the right encoding:

![image](https://cloud.githubusercontent.com/assets/22350/23012216/5838712e-f425-11e6-978a-e0d09db32a9e.png)

**Comment by bpasero** [comment]
@hoine please make sure to use the same encoding in VS as in VS17.

**Comment by hoine** [comment]
thank you.
