### ISSUE TITLE
Use promises in SearchEngine 

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#20650]
The following `search` method is full of callbacks:

```typescript
search(onResult: (match: ISerializedFileMatch[]) => void, onProgress: (progress: IProgress) => void, done: (error: Error, complete: ISerializedSearchComplete) => void): void
```

We've long ago decided to drop callbacks in favour of promises, which are easier to reason about, compose and maintain.

My suggestion is to combine `onResult` with `onProgress`, they are one and the same.

```typescript
interface ISearchProgress {
  results: ISerializedFileMatch[];
  progress: IProgress;
}

search(): PPromise<ISerializedSearchComplete, ISearchProgress>;
```

**Comment by kgrz** [comment]
Are the `debt` issues open to be taken up by everyone or only Microsoft employees/members of this repo?

**Comment by chrmarti** [comment]
We have no general rule for that. This issue is undisputed, we just haven't had time to look into it. Contributions are welcome!

**Comment by roblourens** [comment]
You might just want to ping me to talk about the approach before you spend a lot of time on it, since it's a refactoring issue that might impact a bunch of files.

**Comment by kgrz** [comment]
Awesome! I can take a shot at this.

**Comment by kgrz** [comment]
@roblourens search.ts has the main `Engine` interface. fileSearch, textSearch,
rawSearchService files use that interface. One idea I have in mind is to add another search function temporarily with the new interface, ensure old and new tests are green, and then remove the old function. Do you think this is okay? (Final PR will not have 2 functions, btw)


Aside: File ripgreptextsearch also has a similar looking `search` function, but the class doesn't use the `Engine` interface. Should that also be migrated to a promise-based one?

**Comment by roblourens** [comment]
Sure that sounds like a good approach. I don't know whether it still makes sense to have a common interface between file search and text search, since they've changed a lot, which is why I didn't bother to implement it for ripgrep search, so you don't have to contort it too hard to fit.

I wanted to clean this up after getting rid of non-ripgrep search, but we will probably keep both for the time being.

**Comment by kgrz** [comment]
@roblourens This took a bit longer than I wanted, but finally got some time to make some progress: https://github.com/Microsoft/vscode/pull/32609 I'm not yet happy about some of the changes, and might need some direction.

**Comment by joaomoreno** [comment]
Closing, as we're going away from PPromise and into events.
