### ISSUE TITLE
the directory gets changed from cd to d 

### ISSUE THREAD

**Issue by sankalpnayak08** [microsoft/vscode#206592]
Type: <b>Feature Request</b>

I am using visual studio code for my  c programming and in that i use code runner for my easy work . My os was installed newly 3 weeks back and frrom then i am facing an issue of directory getting changed from cd to d automatically for the second run in terminal please help me its irritating a lot

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
