### ISSUE TITLE
Need pascal case (upper camel case) with "Transform to ... case" command

### ISSUE THREAD

**Issue by wohenbushuang** [microsoft/vscode#206591]
Type: <b>Feature Request</b>

I write Golang code, and the variables needed to be exported in Golang should be in pascal case (upper camel case). Currently there is only lower camel case but no pascal case with the command "transform to ... case", so I request to add this feature for our convenience, thanks.

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

**Comment by gjsjohnmurray** [comment]
Is this a duplicate of #206257 which recently got added to Insiders?

**Comment by wohenbushuang** [comment]
oh yep
