### ISSUE TITLE
Opening this cpuprofile makes vscode stop responding

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#206541]
- Open this .cpuprofile: 

[prof-uwGrxS2H.renderer.cpuprofile.zip](https://github.com/microsoft/vscode/files/14451536/prof-uwGrxS2H.renderer.cpuprofile.zip)

- VS Code stops responding

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/201174
