### ISSUE TITLE
Display disorder

### ISSUE THREAD

**Issue by sun247587578** [microsoft/vscode#206508]
There is a floating phenomenon in the editor code area

![float](https://github.com/microsoft/vscode/assets/24712218/23e60e36-388c-47a5-b350-0edc125801bd)

**Comment by gjsjohnmurray** [comment]
Are you talking about the Sticky Scroll header section?

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, this is a feature known as `Sticky Scroll` https://code.visualstudio.com/updates/v1_70#_editor-sticky-scroll

You can turn this feature off via the following setting (search for `Stick Scroll` in your settings to toggle these features)
<img width="482" alt="Screenshot 2024-03-04 at 11 18 17" src="https://github.com/microsoft/vscode/assets/1948812/25ea7b4a-7f77-434d-ac92-9b8a44a53f7a">

**Comment by sun247587578** [comment]
Many thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Don ***@***.***&gt;; 
发送时间: 2024年3月4日(星期一) 上午8:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/vscode] Display disorder (Issue #206508)





 
Thank you for filing this issue, this is a feature known as Sticky Scroll https://code.visualstudio.com/updates/v1_70#_editor-sticky-scroll
 
You can turn this feature off via the following setting (search for Stick Scroll in your settings to toggle these features)
 Screenshot.2024-03-04.at.11.18.17.png (view on web)
