### ISSUE TITLE
Feature request for VS code speech

### ISSUE THREAD

**Issue by threej-in** [microsoft/vscode#206534]
1. Please provide a way to stop capitalizing each word
2. If possible allow to use code speech into terminal

**Comment by meganrogge** [comment]
The first letter of each word is not capitalized for me. For the terminal, in insider's, you can use these commands.

![Image](https://github.com/microsoft/vscode/assets/29464607/a9841c64-07c0-43db-8bf7-c4a68df9c5e4)
