### ISSUE TITLE
Cannot close a folder

### ISSUE THREAD

**Issue by lindapescatore** [microsoft/vscode#206586]
Type: <b>Bug</b>

I have a folder open that has five or six files and 3 subfolders. I want to close the folder to start a new project. I only have this folder open in one window. There's no option to close a folder in my File menu. Just Open File, Open Folder, Open Workspace from File ..., and Open Recent. The only Close option is Close Editor. Google told me to Ctrl-K-F and that has worked for me in the past but now it either does nothing or messes with a css file (when it was still open). I tried closing the whole program and reopening it but the folder is still open. I checked Updates and there are none. 

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3450U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|9.89GB (1.52GB free)|
|Process Argv|--crash-reporter-id cb1be013-f0af-42cf-93b8-2b0e7c8bbb75|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-toggler|dzh|0.0.3
prettier-vscode|esb|10.1.0
codespaces|Git|1.16.11
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.82.0
debugpy|ms-|2024.2.0
isort|ms-|2023.10.1
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-repos|ms-|0.38.0
remote-repositories|ms-|0.40.0
mysql-shell-for-vs-code|Ora|1.14.2
LiveServer|rit|5.7.9
pdf|tom|1.2.2
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
cppperfcontrol:30973184
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
bg6jg535:30958357
ccp2r6:30958158
dsvsc020cf:30973509
666c4381:30973075

```

</details>

**Comment by lramos15** [comment]
`F1 -> Close Workspace`
