### ISSUE TITLE
Remote SSH - Incorrect warning of VSCode Server's prerequisites for glibc and libstdc++

### ISSUE THREAD

**Issue by git-nico** [microsoft/vscode#206533]
Does this issue occur when all extensions are disabled?: Yes

The host has version 2.36 of glibc and version 6.0.31 of libstdc++ so it does fulfill those prerequisites.
Even though the prerequisites for glibc and libstdc++" are met, connecting to the host via SSH gives the following warning: 

<img src="https://i.ibb.co/rKBv0H0/warning.png" width="400" />

## Note

The SSH into the host is working fine. The issue is the appearance of the notification. 

## Client Machine:

Version: 1.87.0
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

## Host Machine:

Linux 4.4.302+ #69057 SMP Fri Jan 12 17:02:59 CST 2024 x86_64 GNU/Linux synology_apollolake_918+

## Remote SSH plugin:

version: 0.109.0

## Steps to Reproduce
1. Install vs code and ssh remote extension
1. connect to remote host running synology DSM

## Findings

- check-requirements.sh is **not** the cause of this. Required libs are found by the script.
- 1.87.0-insider using the same version of the Remote SSH plugin does not show the warning

Version: 1.87.0-insider
Commit: 1cc266cc82838981034c2baa637f357a83711d5d
Date: 2024-02-22T22:51:58.796Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by lgu-appear** [comment]
Facing an isse with Remote-SSH, linking it there: https://github.com/microsoft/vscode/issues/204611#issuecomment-1970623541

**Comment by SonGokussj4** [comment]
This is still ongoing :-( Can't connect to Synology Nas (DSM 7.2)

**Comment by git-nico** [comment]
The issue appears to be resolved in version 1.88.0. I no longer get the warning.

**Comment by deepak1556** [comment]
Great, thanks for confirming! Should have been resolved by https://github.com/microsoft/vscode/issues/206790
