### ISSUE TITLE
Compatibility Issue with Remote - SSH Extension

### ISSUE THREAD

**Issue by bad1987** [microsoft/vscode#206515]
### Description:
When attempting to activate the VS Code Speech extension while connected remotely using the host extension in VS Code, the host extension stops functioning properly.

### Steps to Reproduce:
1. Connect remotely using the host extension in VS Code.
2. Attempt to activate the VS Code Speech extension.
3. Observe that the host extension stops working as expected.

### Expected Behavior:
The VS Code Speech extension should activate without affecting the functionality of the host extension, allowing both extensions to work simultaneously while connected remotely.

### Actual Behavior:
Activating the VS Code Speech extension causes the host extension to cease functioning properly, impacting the remote connection experience.

**Environment:**
- VS Code Version: 1.87.0
- VS Code Speech Extension Version: 0.6.0
- Remote - SSH Version: 0.109.0
- OS: Ubuntu 18.04

**Comment by alwayslove2013** [comment]
+1

**Comment by chrmarti** [comment]
@bad1987 Is this still an issue?
