### ISSUE TITLE
vs code lag & keybinding  problems

### ISSUE THREAD

**Issue by codebluded** [Microsoft/vscode#20653]
- VSCode Version:
- OS Version:

Steps to Reproduce:

I recently started using vs code from sublime. Problem is the key bindings i used in sublime do not work for vs code. Any help? I tried installing a sublime extension but it doesn't seem to work

**Comment by joaomoreno** [comment]
This extension should be pretty helpful:

https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings
