### ISSUE TITLE
HTML Attribute Tab Complete Doesn't Include Equals And Quotes

### ISSUE THREAD

**Issue by preston206** [microsoft/vscode#206565]
Type: <b>Bug</b>

I've been experiencing this issue for a while. Unfortunately, I can't pin point when exactly it happened. When using tab completion for HTML attributes, it used to include the equals symbol and quotes. After pressing tab, it would look like this: <div class="">. But now I get: <div class>. Recently, I tried toggling the html.completion.attributeDefaultValue from doublequotes to singlequotes and now the issue is partially resolved. When I create a new file, I get the attribute, equals, and qoutes after pressing tab. However, on existing files the issue still happens. The company I work for uses ESLint and Prettier, and has rules set up for quotes (they prefer single quotes), which I suspect might be conflicting with VSCode's setting?

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.66GB (13.54GB free)|
|Process Argv|--crash-reporter-id d855f0e1-4738-416f-9dfe-d010425fc5a7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.10.5
vscode-eslint|dba|2.4.4
prettier-vscode|esb|10.1.0
live-sass|gle|6.1.2
vscode-liquid-snippets|kil|2.0.3
web-accessibility|Max|0.2.83
csv-to-table|php|1.4.0
LiveServer|rit|5.7.9
theme-check-vscode|Sho|2.1.0
svg-preview|Sim|2.8.3
code-spell-checker|str|3.0.1
vscode-stylelint|sty|1.3.0
gitblame|wad|10.9.0
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
dsvsc020:30973508

```

</details>

**Comment by tomorrowagency-preston** [comment]
The bot didn't do a good job at transferring my text. My example code is missing. This is what I was trying to say.

_After pressing tab, it would look like this: `<div class="">`
But now I get: `<div class>`_

**Comment by aeschli** [comment]
- make sure your editor is in `html` mode (not php or any other HTML like language)
- try disabling all extensions as some extensions take over the html language.

**Comment by tomorrowagency-preston** [comment]
hi @aeschli, thanks for the response. I tested out the Language Mode and it is indeed related to that. However, most of my development work needs to use the Liquid mode. Is it possible for me to set up a custom setting to achieve the results I want while in a non-html language mode?

![image](https://github.com/microsoft/vscode/assets/113131178/485d5a28-72ce-4163-ab2d-38ba51869d7a)

**Comment by aeschli** [comment]
You need to look out for an extension that adds rich language support for `Liquid`. If you already do, file issues against that extension.

**Comment by tomorrowagency-preston** [comment]
in case anyone else stumbles onto this issue, here is the issue I opened for the Shopify VSC extension:

https://github.com/Shopify/theme-tools/issues/321
