### ISSUE TITLE
Welcome page layout is broken again

### ISSUE THREAD

**Issue by HolyBlackCat** [microsoft/vscode#206507]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0
- OS Version: Linux x64 6.5.13-7-MANJARO

Steps to Reproduce:

1. Open the welcome page.
2. Close all the walkthough suggestions.
3. Observe a lot of empty space on the right:

![pic](https://github.com/microsoft/vscode/assets/20289055/9e9732b7-cc42-4427-843e-66d3116c881c)

Normally after closing all walkthroughs the "recent" list moves to the second column, to have a more balanced layout.

This was broken a few versions ago, then fixed, and now it's broken again.

**Comment by tomhanax** [comment]
same here

**Comment by roblourens** [comment]
Looks the same to me, is that right?

<img width="1218" alt="image" src="https://github.com/microsoft/vscode/assets/323878/df1b70a1-b762-4429-8ba8-d9b590f32671">
