### ISSUE TITLE
Hash Sum mismatch in apt

### ISSUE THREAD

**Issue by Devil-Soumitra** [microsoft/vscode#206505]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.87.0
- OS Version: kali-rolling 2024.1

Steps to Reproduce:

1. sudo apt update

Err:4 https://packages.microsoft.com/repos/code stable/main armhf Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:17061 [weak]
   - SHA512:77b070ae84b7593ae260425c80e221b8ecdf21d53b8183908c2e51d8a11f73267a0eaf3a4e6d4ff107d17e8ff2e90a544fad9943cd27b1ef02e17060cd964580
   - SHA256:3d308a4e98ce644f31add8d448ea27cb1e63ca8402ff5279688313d8d68f1d61
  Hashes of received file:
   - SHA512:bdb79952d28092b054f107788a1eb3f788a059dec70b3b6704256c6ae8482799b456a41ddc751d102dedc9ff2d5d75f0b3ad0672682bd4073eb29141bb3e1d94
   - SHA256:31393513b8fc5c5e216ba0c735fecfde7497b5d59fb650875c5ec831970eded3
   - Filesize:17061 [weak]
  Last modification reported: Wed, 28 Feb 2024 23:07:00 +0000
  Release file created at: Wed, 28 Feb 2024 22:14:55 +0000

Failed to fetch https://packages.microsoft.com/repos/code/dists/stable/main/binary-armhf/Packages.gz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:17061 [weak]
    - SHA512:77b070ae84b7593ae260425c80e221b8ecdf21d53b8183908c2e51d8a11f73267a0eaf3a4e6d4ff107d17e8ff2e90a544fad9943cd27b1ef02e17060cd964580
    - SHA256:3d308a4e98ce644f31add8d448ea27cb1e63ca8402ff5279688313d8d68f1d61
   Hashes of received file:
    - SHA512:bdb79952d28092b054f107788a1eb3f788a059dec70b3b6704256c6ae8482799b456a41ddc751d102dedc9ff2d5d75f0b3ad0672682bd4073eb29141bb3e1d94
    - SHA256:31393513b8fc5c5e216ba0c735fecfde7497b5d59fb650875c5ec831970eded3
    - Filesize:17061 [weak]
   Last modification reported: Wed, 28 Feb 2024 23:07:00 +0000
   Release file created at: Wed, 28 Feb 2024 22:14:55 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by rcharant** [comment]
I am running PopOS 22.04, same issue for me as well.

According to this issue: https://github.com/microsoft/vscode/issues/86858, it will normalize itself after some time.
