### ISSUE TITLE
Add selection to next find match (Ctrl+D) is broken

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#20651]
- VSCode Version: 1.10 (1d17b4)
- OS Version: Windows

Background:
Earlier, pressing Ctrl+D would select all occurences of a word, and it was case-insensitive *when Match Case was off*. Now, when I keep pressing Ctrl+D, it keeps selecting those words, but when it encounters first case-sensitively different word, it selects it, and then refuses to select anything at all after it.

Steps to Reproduce:

1. Type this in your editor:
```
test
testte
Test
testte
test
```
2. Select first `test` and then press Ctrl+D a bunch of times. It stops after selecting `Test`.
![bug2](https://cloud.githubusercontent.com/assets/760112/22973897/b605dea2-f3a5-11e6-8578-d39510e1e449.gif)

## What it should do:
It shouldn't break after selecting `Test` when Match Case is off.

**Comment by joaomoreno** [comment]
I just hit this. It's pretty bad.

**Comment by michelkaporin** [comment]
Selection of occurrences works fine after the commit, however the highlight stops for the next matches (line 4 and 5 are not highlighted after selecting `Test`. Removing `verified` label.

![selection](https://cloud.githubusercontent.com/assets/2239563/23306392/c037688c-faa3-11e6-8bcb-7d6632a07019.gif)
