### ISSUE TITLE
Jupyter Notebooks not opening in IDE after VScode-Update (1.87.0)

### ISSUE THREAD

**Issue by Storm-131** [microsoft/vscode#206601]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.87.0
- OS Version: macOS Sonoma 14.2.1

Steps to Reproduce:
1. Update to the latest version of VScode (1.87.0)
2. Try to open any Juypter Notebook inside the IDE

None of my .ipynb opens after the latest update, I always get the error "Cannot read properties of null (reading 'editor.indentSize')". I disabled all extensions and moved / changed / removed all definitions of "editor.indentSize" in any settings.json.
The only way to get the .ipynb opening again was to downgrade VScode to the previous version. 
I had the exact same experience after updating on a Macbook as well (they have settings sync). Thanks for any help.

<img width="317" alt="Bildschirmfoto 2024-03-01 um 10 33 04" src="https://github.com/microsoft/vscode/assets/49946728/56f134e9-79cd-4020-9bee-dc9880e2c63c">

**Comment by vladUng** [comment]
As @Storm-131 I have the same error and was forced to revert to the previous version

**Comment by lassence** [comment]
Same error here, on two different Macbook Pro. I can't open any notebook.

**Comment by ichitaka** [comment]
Same here

**Comment by mayur7garg** [comment]
I am having the same issue on Windows 11. Is there any temp fix without downgrading the version?

**Comment by lassence** [comment]
It seems that I solved the problem by removing the following line from my `settings.json`:
`"notebook.editorOptionsCustomizations": null,`
