### ISSUE TITLE
Default keybindings for macOS contains unusable keybinding for chat.action.focus

### ISSUE THREAD

**Issue by tshino** [microsoft/vscode#206666]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0
- OS Version: macOS

Steps to Reproduce:

1. Run `workbench.action.openDefaultKeybindingsFile` command
2. Search for `chat.action.focus` in the file.

The file contains following lines.
```
{ "key": "cmd+up",                "command": "chat.action.focus",
                                     "when": "inChatInput && isLinux || inChatInput && isWindows" },
```
It looks nonsense.

**Comment by roblourens** [comment]
It just looks weird because that `cmd` registration would resolve to `ctrl` on windows and linux, but this is actually right
