### ISSUE TITLE
Automatically added unwanted indentations and parentheses when paste from on-screen keyboard

### ISSUE THREAD

**Issue by 54145a** [microsoft/vscode#206673]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0

- Browser: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 EdgA/121.0.0.0-

Steps to Reproduce:

1. Copy a piece of pre-formatted code.
2. Paste them using on-screen keyboard
![IMG_20240302_175336](https://github.com/microsoft/monaco-editor/assets/133004095/52fb29a3-3fa4-4d1d-b9cb-0efc56de71f4)

The editor automatically added unwanted indentations and parentheses.
![IMG_20240302_182429](https://github.com/microsoft/vscode/assets/133004095/ea660cc3-88db-4e9d-b7d8-d7ca722a3b0a)

**Comment by alexdima** [comment]
Does this reproduce when configuring `"editor.autoIndent": "advanced"`?

**Comment by 54145a** [comment]
> Does this reproduce when configuring `"editor.autoIndent": "advanced"`?

Yes
