### ISSUE TITLE
Request for Assistance: Unable to Decrease Size of Primary Sidebar in Latest VS Code Version

### ISSUE THREAD

**Issue by pranshugupta01** [microsoft/vscode#206687]
Type: <b>Bug</b>

I'm currently facing a problem with the latest version of VS Code. I can't seem to reduce the size of my sidebar from the default position, only increase it. This is particularly annoying on small-screen devices.

https://github.com/microsoft/vscode/assets/100456318/44bb9942-73d7-4453-831d-034621e867ab

Any assistance or guidance on resolving this issue would be appreciated.

VS Code version: Code 1.87.0 (Universal) (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:56.944Z)
OS version: Darwin arm64 23.3.0
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|20, 13, 6|
|Memory (System)|8.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id 8eb213e9-bda0-4e10-b2ef-a85617f801f8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (83)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-sqlite|ale|0.14.1
arepl|alm|2.0.5
tailwind-docs|aus|2.1.0
vscode-django|bat|1.15.0
htmlplay|bia|0.0.10
django-html|bib|1.3.0
django|big|1.0.2
vscode-tailwindcss|bra|0.10.5
exe-runner|bra|0.2.1
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.5
gitignore|cod|0.9.0
postcss|css|1.0.9
c-cpp-compile-run|dan|1.0.58
githistory|don|0.6.20
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.8.2
vscode-html-css|ecm|2.0.9
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
c-cpp-runner|fra|9.4.7
vscode-pull-request-github|Git|0.82.0
gc-excelviewer|Gra|4.2.59
CppSnippets|har|0.0.15
c-math-viewer|Hye|1.0.4
vscode-vibrancy-continued|ill|1.1.27
prettier-sql-vscode|inf|1.6.0
vscode-edit-csv|jan|0.9.0
better-cpp-syntax|jef|1.17.2
solidity|Jua|0.0.172
vscode-colorize|kam|0.11.1
vsc-python-indent|Kev|1.18.0
vscode-fix-checksums|leh|1.1.0
MagicPython|mag|1.1.0
git-graph|mhu|1.30.0
gitignore|mic|1.0.1
vscode-docker|ms-|1.29.0
black-formatter|ms-|2024.0.1
debugpy|ms-|2024.2.0
isort|ms-|2023.10.1
python|ms-|2024.2.1
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
cpptools|ms-|1.19.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.8.22
remote-explorer|ms-|0.4.3
vsliveshare|ms-|1.0.5905
autodocstring|njp|0.6.1
sqlite-viewer|qwt|0.3.13
vscode-thunder-client|ran|2.18.0
vscode-yaml|red|1.14.0
ethereum-remix|Rem|0.0.12
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
django-intellisense|sha|0.0.2
svg-preview|Sim|2.8.3
indenticator|Sir|0.7.0
swdc-vscode|sof|2.7.5
code-spell-checker|str|3.0.1
tabnine-vscode|Tab|3.73.0
pdf|tom|1.2.2
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-icons|vsc|12.7.0
quokka-vscode|Wal|1.0.627
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
random-theme-switcher|zan|0.2.2
html-css-class-completion|Zig|1.20.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
78248357:30976999
dsvsc020:30976470

```

</details>

**Comment by andremmsilva** [comment]
Hello! I am new to the project. I have an Integrating Project for my Computer Science degree that involves working on and contributing to an open source code base. The first step is to fix a bug/issue and I would love to work on this one. Any guidance is appreciated.

Thank you :)

**Comment by bpasero** [comment]
Views have a minimal width that we define statically.
