### ISSUE TITLE
Unable to update via apt : File has unexpected size (17340 != 17415).

### ISSUE THREAD

**Issue by navjotjsingh** [microsoft/vscode#206655]
- OS Version: Kubuntu 23.10

Every time I run `sudo apt update`, I run into the following error.

```
.............
Err:4 http://packages.microsoft.com/repos/code stable/main armhf Packages                                                                                                                                                                  
  File has unexpected size (17340 != 17415). Mirror sync in progress? [IP: 13.107.213.68 443]
Err:4 http://packages.microsoft.com/repos/code stable/main armhf Packages                                                                                                                                                                  
  File has unexpected size (17340 != 17415). Mirror sync in progress? [IP: 13.107.213.68 443]
...................
Reading package lists... Done
E: Failed to fetch http://packages.microsoft.com/repos/code/dists/stable/main/binary-armhf/Packages  File has unexpected size (17340 != 17415). Mirror sync in progress? [IP: 13.107.213.68 443]
E: Some index files failed to download. They have been ignored, or old ones used instead. 
```

Tried to remove the armhf and arm64 from the vscode.list and got the same error for amd64 as well. Finally removed vscode.list and it worked but this needs to be looked at.

**Comment by EG-yamagami** [comment]
same in Linux Mint 21.3

**Comment by david-waterworth** [comment]
And Ubuntu 22.04

**Comment by du-xinyi** [comment]
ubuntu 20.04 also have this problem

**Comment by MehulBawadia** [comment]
I am also facing this issue. Here's what I get when I run the `apt update` command

```bash
Err:5 https://packages.microsoft.com/repos/code stable/main amd64 Packages                                                                                     
  File has unexpected size (17307 != 17386). Mirror sync in progress? [IP: 13.107.213.48 443]
  Hashes of expected file:
   - Filesize:17386 [weak]
   - SHA512:5385bfa747c45aaac648cfa2c776be59302083052f56a02415d4bf96412f610b25a705d9ef5e37ca9bfa00a4806419836626d4765d4fcdb3aad0b0d0d554522c
   - SHA256:fbfea0a16bf3557a12b2f9d483605fa90bb6ec6fbfd908b13de53bfc76c78941
  Release file created at: Fri, 01 Mar 2024 20:17:18 +0000

E: Failed to fetch https://packages.microsoft.com/repos/code/dists/stable/main/binary-amd64/Packages.gz  File has unexpected size (17307 != 17386). Mirror sync in progress? [IP: 13.107.213.48 443]
   Hashes of expected file:
    - Filesize:17386 [weak]
    - SHA512:5385bfa747c45aaac648cfa2c776be59302083052f56a02415d4bf96412f610b25a705d9ef5e37ca9bfa00a4806419836626d4765d4fcdb3aad0b0d0d554522c
    - SHA256:fbfea0a16bf3557a12b2f9d483605fa90bb6ec6fbfd908b13de53bfc76c78941
   Release file created at: Fri, 01 Mar 2024 20:17:18 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Removing the ppa from the sources list is not the right solution, according to me. Because then, you will have to download and install VS Code manually every time. Keeping it in the sources list will also check for updates whenever we run the `apt update` command.

Any help would be much appreciated.

P.S.: I am on Ubuntu 22.04

**Comment by swapnil-23** [comment]
facing the same issue on Ubuntu

**Comment by MohneeshVaidya** [comment]
I am facing the same issue, I am on Kubuntu 22.04. Perhaps it is repository problem and will go away eventually.

**Comment by mvdw73** [comment]
Same issue on Pop!_OS 22.04, but only one of my computers. The other one seems to update fine.

The difference is that the one that FAILS has the key signing in the sources.list.d/vscode.list file:

Here's the one that fails:

```
deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
```

And the one that updates file is this:

```
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code stable main
```

So the second one doesn't have the signing line, BUT, I can't just copy the sources.list file to the failing one as the signing happens elsewhere.

The one that succeeded was installed the "old way" I think, but I can't remember the details of what I did to get the pgp key into the apt ecosystem. :-(.

**Comment by navjotjsingh** [comment]
Looks like the issue is resolved. Am closing this.

**Comment by Kevinisagirl21** [comment]
If you install vscode via the package online it seems to work fine on Ubuntu 22.04.. Should work on kubuntu. [https://code.visualstudio.com/download](url)
