### ISSUE TITLE
There is a lagging in the UX while editing or typing in the terminal which is introduce in between 1.86.2 and 1.87.0

### ISSUE THREAD

**Issue by carlosrodfern** [microsoft/vscode#206620]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.87.0-1709078732
- OS Version: Fedora 39 with the latest updates

Steps to Reproduce:

1. Ensure you had already vscode in Fedora 39 using the microsoft rpm repository
2. Bring fedora 39 up to date (`sudo dnf up -y --refresh`)
3. The previous step should have brought `code` to version `1.87.0-1709078732.el8.x86_64`
4. Open vscode and use it, and notice a lagging in the terminal as you type, and in the overall interaction
5. Revert to 1.86.2-1707854644.el8.x86_64 and the problem is gone.

The problem was introduced between those two versions: `1.86.2-1707854644.el8.x86_64` and `1.87.0-1709078732.el8.x86_64`

**Comment by meganrogge** [comment]
does changing `terminal.integrated.gpuAcceleration` help?

**Comment by carlosrodfern** [comment]
@meganrogge , that actually did it. I changed it to `on` and appears to work fine now.

**Comment by meganrogge** [comment]
Yes, makes sense. Gpu acceleration  provides a better experience. Not sure why it was disabled for you to begin with.
