### ISSUE TITLE
VSC does not recognize new PHP 7.1 syntax

### ISSUE THREAD

**Issue by mertmetin** [Microsoft/vscode#20668]
- VSCode Version: 1.9.1
- OS Version: macOS Sierra (10.12.3)

VSC does not recognize the new PHP 7.1 syntax.

function myFunc: void
function myAnotherFunc: string 

Both statements above are valid PHP 7 statements but VSC shows them as syntax error.

**Comment by AeonDigital** [comment]
- VSCode Version: 1.21.1
- OS Version: MS Win 10

The nullable types on parameters and return types still show errors.

![nullable errors](https://cloud.githubusercontent.com/assets/5123165/25931601/9981682a-35e3-11e7-9962-b0b34363ac0a.png)

**Comment by morgandenning** [comment]
- VSCode Version: 1.12.1
- OS Version Windows 10 (Version 1703 Build 16184.1001)

Constants with visibility modifiers also still show as errors

![vscode_php71](https://cloud.githubusercontent.com/assets/1228686/26078306/e52bc138-3973-11e7-9793-2238999743ea.png)

**Comment by morgandenning** [comment]
Are there any updates for this issue coming?

**Comment by roblourens** [comment]
I believe this should actually work, as long as you are using PHP 7.1. Which PHP version are you using?

**Comment by morgandenning** [comment]
That worked, thanks! I had incorrectly assumed I was already running 7.1 on this machine

**Comment by roblourens** [comment]
Excellent!
