### ISSUE TITLE
Compilation error not show

### ISSUE THREAD

**Issue by BlueJK** [microsoft/vscode#206676]
Type: <b>Feature Request</b>

when I do "click to collapse the range" to a function, if this function has compilation error, it doesn't show me anywhere. 
It would be good, if there is any way to tell me that there is a compilation error, like underline the function.

Thank you
BlueJK

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by gjsjohnmurray** [comment]
Last year I submitted PR #190682 to address this previously raised issue. Now waiting for the team to accept / reject it.

**Comment by BlueJK** [comment]
Cool. Nice that you already gave a possible solution. Hope they can approval it. Thank you!
