### ISSUE TITLE
The `typescript.check.tscVersion` setting should contain specific version numbers not just true/false

### ISSUE THREAD

**Issue by Knagis** [Microsoft/vscode#20666]
Previously I remember seeing the warning about TS version mismatch when my local version was 1.8, but VSCode used already 2.0. In that case this message was useful. However today the mismatch was between 2.1.4 and 2.1.6. Due to my laziness, I decided to click the "Don't check" button.

However, I did not really expect that the check would be disabled completely - but rather for this particular version combination. If VSCode updates to 2.2, I would like to be notified again.

**Comment by mjbvz** [comment]
Closing as this warning is no longer shown
