### ISSUE TITLE
Merge editor: strange conflict

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#206640]
See:

<img width="1654" alt="image" src="https://github.com/microsoft/vscode/assets/900690/3310694a-5b1c-41be-986a-6cfce921272a">

Repro:
[untitled folder.zip](https://github.com/microsoft/vscode/files/14465121/untitled.folder.zip)

**Comment by hediet** [comment]
This is an automatically solved conflict, because both changes agree:

![Image](https://github.com/microsoft/vscode/assets/2931520/b549af20-1e6a-4d4c-a355-39bbad4fee50)

**Comment by bpasero** [comment]
Maybe that could be clarified in the boxes and wording.
