### ISSUE TITLE
Two file explorer tabs 

### ISSUE THREAD

**Issue by arafat-dexcom** [microsoft/vscode#206639]
Type: <b>Bug</b>

On load the file explorer shows up twice, and doesn't show the files.
![image](https://github.com/microsoft/vscode/assets/106617728/5b4de370-b02e-4d42-afcc-505ddba7b5bf)

VS Code version: Code 1.87.0 (Universal) (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:56.944Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 5b04914d-fb1e-4e24-9e7d-1dca74e46375|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
svelte-bundle|1Yi|1.0.0
cucumberautocomplete|ale|2.15.2
vim-cheatsheet|And|0.0.1
Handlebars|and|0.4.1
tailwind-docs|aus|2.1.0
markdown-preview-github-styles|bie|2.0.3
vscode-tailwindcss|bra|0.10.5
githistory|don|0.6.20
gitlens|eam|14.8.2
earthfile-syntax-highlighting|ear|0.0.16
vsc-material-theme-icons|equ|3.5.0
prettier-vscode|esb|10.1.0
vscode-svelte-snippets|fiv|0.5.0
rails-snippets|Hri|1.0.8
vsc-handlebars-ext|Its|1.0.1
vscode-ember-unstable|lif|3.0.53
vscode-glimmer-syntax|lif|1.0.34
rainbow-csv|mec|3.11.0
template-string-converter|meg|0.6.1
vscode-docker|ms-|1.29.0
vsliveshare|ms-|1.0.5905
material-icon-theme|PKi|4.34.0
git-file-history|pom|1.0.1
vscode-yaml|red|1.14.0
ruby-lsp|Sho|0.5.11
vscode-fileutils|sle|3.10.3
svelte-vscode|sve|108.3.1
explorer|vit|0.4.0
vim|vsc|1.27.2
pretty-ts-errors|Yoa|0.5.3
markdown-all-in-one|yzh|3.6.2
tailwind-snippets|Zar|1.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
dsvsc020:30976470

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the second instance is being contributed by an extension.

**Comment by lramos15** [comment]
This likely means you pulled the "Folders View" out of the "Explorer" view container (yes, I know the naming is confusing). Do F1 -> Reset View Locations

**Comment by arafat-dexcom** [comment]
Thanks that fixed it
