### ISSUE TITLE
Can not use 'Don't Save' as an option via keyboard commands when closing unsaved files.

### ISSUE THREAD

**Issue by DKchemistry** [microsoft/vscode#206698]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.87.0 (Universal)
- OS Version: macOS 14.3.1 23D60 arm64 

Steps to Reproduce:

1. Open a blank file like a Jupyter Notebook.
2. Close the file without saving. 
3. Use tab to select 'Don't Save'.
4. Use enter to execute 'Don't Save'. 
5. You will still be prompted to save. 

I am trying to minimize mouse use and I don't know how to fix or workaround this.

https://github.com/microsoft/vscode/assets/81147591/04840e38-1fc1-4046-ac95-167e986b97ca

**Comment by bpasero** [comment]
Try `Space` instead of `Enter`.
