### ISSUE TITLE
`SCM: Auto Reveal` does not work consistently in multi repo projects

### ISSUE THREAD

**Issue by bilogic** [microsoft/vscode#206664]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0
- OS Version: Windows 10

Steps to Reproduce:
### Image 1: SCM (Source Control)
![image](https://github.com/microsoft/vscode/assets/946010/fa73e40b-3ef7-4271-99c9-9e41bd86a9d7)
### Image 2: Explorer
![image](https://github.com/microsoft/vscode/assets/946010/b9aa9571-eb9f-4357-8873-b5f473549481)

1. In a multi repo project like above, we have 3 repos, and `repo1` is currently selected
2. We switch to `Explorer` to open `repo2-a.md`, make some changes and save
3. Switch to `SCM`, but `repo2-a.md` is not automatically selected even though the `SCM: Auto Reveal` setting is ticked
4. This is because `repo1` is still selected in `Source Control Repositories` (BUG)
5. My expectation was for `repo2` and `repo2-a.md` to be selected when I switch to `SCM` in step 3

**Comment by bilogic** [comment]
@lszomoru any idea?

**Comment by bilogic** [comment]
@lszomoru can help?

**Comment by lszomoru** [comment]
@bilogic, the "auto-reveal" functionality operates on the list of repositories that are visible (the one that are selected in the "Source Control Repositories" view). This is by design. The workaround is to explicitly select all the repositories in the "Source Control Repositories" view.

**Comment by bilogic** [comment]
@lszomoru 

If by design refers to the description of `SCM: Auto Reveal`, which reads `Controls whether the Source Control view should automatically reveal and select files when opening them`, then it sounds fine to me, especially when the word `Reveal` is also found in the name.

1. Unfortunately, the current implementation only `select` and does not `reveal`, which, based on Explorer's `reveal` behavior, I would define as "bring into view".
2. The suggested workaround performs badly (due to scanning the git of numerous roots), and does nothing additional to `reveal` the file.
3. The extension route is also not viable as the SCM API allows only toggling, with no way to determine if a repo is currently selected.

Unless there is another definition of `reveal`, it is quite clear to me there is an issue. I hope this can be fixed. Thank you.

**Comment by lszomoru** [comment]
> I would like to suggest adding a command to select the repo + select and reveal the file. This will keep things status quo and allow for locating the file in SCM, just like Explorer. Should I open a new issue for it?

Yes, please feel free to open a feature request for that. Thanks!

**Comment by lszomoru** [comment]
Verification steps:
* Open a folder/workspace that contains multiple git repositories
* Open the "Source Control Repositories" view and select all repositories
* Ensure that the `scm.autoReveal` setting is enabled
* Open a file from the first repository and modify it
* Open a file from the last repository and modify it
* Resize the window so that the first/last repositories are not in the view port
* Switch between the two editor tabs and confirm that the file is selected and scrolled into the viewport

**Comment by bilogic** [comment]
@lszomoru 

There is an open issue here https://github.com/microsoft/vscode/issues/170819, can help?
