### ISSUE TITLE
Unexpected word and occurrence highlighting despite disabled settings

### ISSUE THREAD

**Issue by xshapira** [microsoft/vscode#206671]
When I place the cursor on random lines within the editor, VS Code highlights arbitrary words under the cursor and their occurrences throughout the file. This behavior persists even though I have disabled `editor.occurrencesHighlight` and `editor.selectionHighlight` in my settings.

This issue occurs when all extensions are disabled.

- VS Code Version: 1.87.0 (Universal)
- OS Version: macOS Monterey 12.7

https://github.com/microsoft/vscode/assets/48856190/c88dea26-8df2-43f0-91b5-a73d6afc702b

Steps to Reproduce:

1. Open any file.
2. Place the cursor on any line in the editor.
3. Watch the unexpected highlighting of the word and its occurrences.

**Note**: The issue doesn't manifest immediately and consistently but varies in how often it occurs. It may require multiple tries of moving the cursor to different lines before noticing the unexpected highlighting.

**Comment by gjsjohnmurray** [comment]
Probably fixed by #206559 in upcoming recovery release.
