### ISSUE TITLE
CSS Dynamic Root Selector

### ISSUE THREAD

**Issue by aboveallmedia-basilbabaa** [microsoft/vscode#206694]
Type: <b>Bug</b>

Here is some CSS I am working with:

/* CSS for SVG */

:root {
  --aa-svg-height: 64px;
  --aa-svg-width: 64px;  
}

%root%  {border: 1px solid green;}  /* border check */

.svg-container {
  border: 1px solid red;
  background: #ccc;
}

#svg-icon-1 {
  border: 1px solid red; /* border check */
  height: var(--aa-svg-height);
  width: var(--aa-svg-width);
}

#svg-icon-2 {
  border: 1px solid red; /* border check */
  height: var(--aa-svg-height);
  width: var(--aa-svg-width);
}

%root% .aa-svg__code-block {
  fill: blue;
}

I NEED TO KNOW HOW to configure Visual Studio Code to recognize the dynamic root selector %root%, so that it will stop flagging lines with this selector as having an error. 

I have tried adding the following to my Visual Code settings.json file:

"css.customData": {
    "properties": [
        {
            "name": "%root%",
            "description": "Dynamic root selector for use in Bricks Builder"
        }
    ]
}

And also tried adding the following to my Visual Code user snippets:

{
    "Bricks Builder dynamic root selector": {
        "prefix": "%root%",
        "body": [
            "%root%"
        ],
        "description": "Dynamic root selector for use in Bricks Builder"
    }
}

However these potential solutions did not work.

Please provide me a proper method to make it so that Visua Studio Code does NOT see %root% as a syntax error when workign with CSS files.

VS Code version: Code 1.87.0 (Universal) (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:56.944Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Ultra (20 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|128.00GB (30.63GB free)|
|Process Argv|--crash-reporter-id 6271d89b-38f4-4d7e-a0e6-45ca6ab03790|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.45.15061
vscode-edge-devtools|ms-|2.1.5

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
cppperfnew:30973185
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
8f97e687:30977000
dsvsc020:30976470

```

</details>

**Comment by IllusionMH** [comment]
Where does this `%root%` come from? Doesn't look like standard CSS, so you might need extension to support this thing.

**Comment by aboveallmedia-basilbabaa** [comment]
You’re right it is not standard.  %root% is the “dynamic" root selector designation used in Bricks Builder for Wordpress.

Here is a demonstration of some CSS I wrote and applied to an SVG element in Bricks Builder in Wordpress:

/* VARIABLE SETTINGS */
:root {

  /* Button colors */
  --play-button-color: var(--white);
  /* Default button color */
  --play-button-hover-color: var(--action-hover);
  /* Button color on hover */


  /* Animation size */
  --play-button-animation-size: .5em;
  /* Default animation size */

  /* Animation speed */
  --play-button-animation-speed: 0.5s;
  /* Default animation speed */

  /* Transition speed */
  --play-button-transition-speed: 0.8s;
  /* Default transition speed */
}

/* ANIMATIONS */
@keyframes bounceLeftAndBack {

  0%,
  100% {
    transform: translateX(0);
  }

  50% {
    transform: translateX(var(--play-button-animation-size));
  }
}

/* Styling for the play button */
.aa-video-play-button {
  align-items: center;
  display: block;
  /* Display settings */
  height: var(--play-button-svg-size);
  /* Height based on custom variable */
  justify-content: center;
  position: absolute;
  /* Positioning */
  width: var(--play-button-svg-size);
  /* Width based on custom variable */
  z-index: 1;
  /* Z-index */
}

/* Styling for the circle inside play button */
.aa-video-play-button aa-video-play-button__circle,
.aa-video-play-button__circle-outline {
  opacity: 1;
  stroke-dasharray: 650;
  stroke-dashoffset: 650;
  transition: all var(--play-button-transition-speed) ease-in-out;
  /* Apply transition speed */
}

/* Styling for the filled circle inside play button */
.aa-video-play-button aa-video-play-button__circle {
  stroke: var(--play-button-color);
  /* Set button color */
  stroke-dashoffset: 0;
}

/* Styling for the outlined circle inside play button */
.aa-video-play-button__circle-outline {
  opacity: 0.3;
  stroke: var(--play-button-color);
  /* Set button color */
}

/* Styling for the triangle inside play button */
.aa-video-play-button aa-video-play-button__triangle {
  stroke: var(--play-button-color);
  /* Set button color */
  stroke-dasharray: 240;
  stroke-dashoffset: 480;
  transition: stroke-dashoffset .8s, stroke .8s;
}

/* Hover effect styles */
.aa-video-play-button:hover aa-video-play-button__circle-outline,
.aa-video-play-button:hover aa-video-play-button__triangle {
  opacity: 1;
  stroke-dashoffset: 0;
}

/* Hover effect styles for the outlined circle inside play button */
.aa-video-play-button:hover aa-video-play-button__circle-outline {
  stroke: var(--play-button-hover-color);
  /* Set button color on hover */
}

/* Hover effect styles for the triangle inside play button */
.aa-video-play-button:hover aa-video-play-button__triangle {
  animation: bounceLeftAndBack var(--play-button-animation-speed) ease-in-out;
  /* Apply bounce animation with animation speed */
  stroke: var(--play-button-hover-color);
  /* Set button color on hover */
  stroke-dashoffset: 0;
}


And here is the same CSS used with the dynamic root selector %root%, applied to the same element.

/* VARIABLE SETTINGS */
:root {

  /* Button colors */
  --play-button-color: var(--white);
  /* Default button color */
  --play-button-hover-color: var(--action-hover);
  /* Button color on hover */


  /* Animation size */
  --play-button-animation-size: .5em;
  /* Default animation size */

  /* Animation speed */
  --play-button-animation-speed: 0.5s;
  /* Default animation speed */

  /* Transition speed */
  --play-button-transition-speed: 0.8s;
  /* Default transition speed */
}

/* ANIMATIONS */
@keyframes bounceLeftAndBack {

  0%,
  100% {
    transform: translateX(0);
  }

  50% {
    transform: translateX(var(--play-button-animation-size));
  }
}

/* Styling for the play button */
%root% {
  align-items: center;
  display: block;
  /* Display settings */
  height: var(--play-button-svg-size);
  /* Height based on custom variable */
  justify-content: center;
  position: absolute;
  /* Positioning */
  width: var(--play-button-svg-size);
  /* Width based on custom variable */
  z-index: 1;
  /* Z-index */
}

/* Styling for the circle inside play button */
%root% %root%__circle,
%root%__circle-outline {
  opacity: 1;
  stroke-dasharray: 650;
  stroke-dashoffset: 650;
  transition: all var(--play-button-transition-speed) ease-in-out;
  /* Apply transition speed */
}

/* Styling for the filled circle inside play button */
%root% %root%__circle {
  stroke: var(--play-button-color);
  /* Set button color */
  stroke-dashoffset: 0;
}

/* Styling for the outlined circle inside play button */
%root%__circle-outline {
  opacity: 0.3;
  stroke: var(--play-button-color);
  /* Set button color */
}

/* Styling for the triangle inside play button */
%root% %root%__triangle {
  stroke: var(--play-button-color);
  /* Set button color */
  stroke-dasharray: 240;
  stroke-dashoffset: 480;
  transition: stroke-dashoffset .8s, stroke .8s;
}

/* Hover effect styles */
%root%:hover %root%__circle-outline,
%root%:hover %root%__triangle {
  opacity: 1;
  stroke-dashoffset: 0;
}

/* Hover effect styles for the outlined circle inside play button */
%root%:hover %root%__circle-outline {
  stroke: var(--play-button-hover-color);
  /* Set button color on hover */
}

/* Hover effect styles for the triangle inside play button */
%root%:hover %root%__triangle {
  animation: bounceLeftAndBack var(--play-button-animation-speed) ease-in-out;
  /* Apply bounce animation with animation speed */
  stroke: var(--play-button-hover-color);
  /* Set button color on hover */
  stroke-dashoffset: 0;
}


You’ll notice that %root% replaces every reference to .aa-video-play-button

So unlike the :root pseudo-class selector which selects the highest-level element in the document tree, the %root% dynamic root selector selects the highest-level when applied to the element itself.

I was hoping that there would be a way to define %root% in Visual Studio Code so that I could work with CSS in Visual Studio Code prior to copying it to elements in Brick Builder.
Similar to how you can tell a word processor to ignore spelling errors it frequently sees, by just defining words, or right-click and choose ignore?


Thanks,







Kindest and Best Regards,

Basil Babaa | VP, CFO & CIO
Above ALL Media
 980.352.9000 <tel:980.352.9000>
 x 1712 <tel:x 1712>
 980.771.0712 <tel:980.771.0712>
 704.781.5800 <tel:704.781.5800>
 basil.babaa <https://web.skype.com/>
***@***.*** ***@***.***>
 www.aboveall.media <http://www.aboveall.media/>
 <https://www.facebook.com/Above-All-PPC-112290757091790/>  <https://www.linkedin.com/in/basilbabaa/>	 <http://aboveall.media/>
  *** ABOVE ALL, YOUR SUCCESS IS OUR #1 PRIORITY. *** 
This e-mail is confidential and intended solely for the use of the individual(s) to whom it is addressed. If you are not the intended recipient, be advised that you have received this e-mail in error and that any use, dissemination, distribution, forwarding, printing, or copying of this e-mail is strictly prohibited. If you have received this e-mail in error, please immediately contact the sender and delete this e-mail message and any attachments from your system.

Any views or opinions presented are solely those of the author and do not necessarily represent those of Above All Media, hereby known as "we" or "us", nor constitute any intent to enter into any binding agreements of any kind.

E-mail transmission cannot be guaranteed secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Although this e-mail and its contents are believed by us to be free of any security-related threat or other defects which might affect any computer or Information Technology system into which they are received, no responsibility is accepted by us for any liability for any errors or omissions in the contents of this message, and/or for loss or damage arising in any way from the receipt or use thereof. 

If verification is required, please request a hard-copy version.

**Comment by aeschli** [comment]
Yes, sorry, the CSS extension supports CSS as defined in the specification.
Support for CSS variants need to be provided by extensions.

**Comment by aboveallmedia-basilbabaa** [comment]
Hi Martin,

Thanks, I was just asking because when I use other code editors I was not getting the error; however I much prefer Visual Studio Code to the others.

But here is a solution I discovered….  if I select the file type as SCSS instead of CSS it overlooks any of the %root% dynamic selectors as being a code error.  

So at least that lets me continue to work in Visual Code Studio instead of another app. 😉

Cheers.


Kindest and Best Regards,

Basil Babaa | VP, CFO & CIO
Above ALL Media
 980.352.9000 <tel:980.352.9000>
 x 1712 <tel:x 1712>
 980.771.0712 <tel:980.771.0712>
 704.781.5800 <tel:704.781.5800>
 basil.babaa <https://web.skype.com/>
***@***.*** ***@***.***>
 www.aboveall.media <http://www.aboveall.media/>
 <https://www.facebook.com/Above-All-PPC-112290757091790/>  <https://www.linkedin.com/in/basilbabaa/>	 <http://aboveall.media/>
  *** ABOVE ALL, YOUR SUCCESS IS OUR #1 PRIORITY. *** 
This e-mail is confidential and intended solely for the use of the individual(s) to whom it is addressed. If you are not the intended recipient, be advised that you have received this e-mail in error and that any use, dissemination, distribution, forwarding, printing, or copying of this e-mail is strictly prohibited. If you have received this e-mail in error, please immediately contact the sender and delete this e-mail message and any attachments from your system.

Any views or opinions presented are solely those of the author and do not necessarily represent those of Above All Media, hereby known as "we" or "us", nor constitute any intent to enter into any binding agreements of any kind.

E-mail transmission cannot be guaranteed secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Although this e-mail and its contents are believed by us to be free of any security-related threat or other defects which might affect any computer or Information Technology system into which they are received, no responsibility is accepted by us for any liability for any errors or omissions in the contents of this message, and/or for loss or damage arising in any way from the receipt or use thereof. 

If verification is required, please request a hard-copy version.
