### ISSUE TITLE
WindowsTerminal opens minimized on C/C++

### ISSUE THREAD

**Issue by iAroc** [microsoft/vscode#206604]
Type: <b>Bug</b>

Hello

This is kinda a followup from #204039, but not complete.

in the new version, pressing F5 to start the debug session works again. 
But if you have already another wt.exe open (unrelated to your project), the new one will only start once in the foreground, and after that it starts minimized.

To reproduce:
- Make a small sample helloworld.cpp project
- Open a Windows Terminal, and just leave it there (dont close it)
- Press F5 in your Project
=> The WT for your Project gets started and you can see it
- Close the WT from your project
- Press F5 again
=> You wont see the WT anymore, since this time it started minimized

It will always start minimized until you close the other wt.exe that is running.

If you dont have any other WT.exe running, then it works without any issues

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900K (32 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.77GB (32.41GB free)|
|Process Argv|--crash-reporter-id 65f729d6-aeb0-46f2-9d2a-d9b9246c4b53|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.4
prettier-vscode|esb|10.1.0
copilot|Git|1.169.0
copilot-chat|Git|0.13.0
unreal-angelscript-clang-format|Haz|0.1.4
cmake-language-support-vscode|jos|0.0.9
vscode-clangd|llv|0.1.26
vscode-dotnet-runtime|ms-|2.0.2
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.2
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.4
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1860
vs-code-prettier-eslint|rve|6.0.0
cmake|twx|0.0.17
openplanet-angelscript|Xer|0.2.28

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30968132
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30959800
cppperfcontrol:30973184
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
78248357:30976999
dsvsc020:30976470

```

</details>

**Comment by connor4312** [comment]
I think we need https://github.com/microsoft/terminal/issues/15895 to fix this

**Comment by connor4312** [comment]
Fied upstream
