### ISSUE TITLE
Open/save files and folders from prompt

### ISSUE THREAD

**Issue by dxdxdt** [microsoft/vscode#206629]
Related: #146422

The problem with using VSCode in Linux is that, most people don't need the external file explorer or WinAPI's `OpenFileDialog` modal. Linux users are not "visual learners". They don't need a GUI modal for selecting paths. The modals rather hinder UX especially when the user wants to copy and paste the path from terminal or other programs. GNOME modals(`Ctrl` + `L`) just make it worse by auto completing the pasted path.

My suggestion is making another way to open files and folders without relying on any modal. Just prompt the path, just like how you'd use bash! Tasks are already implemented this way since there's no task list GUI implemented as of yet.

1. The user opens the command prompt by using the hot key combo(`Ctrl` + `Shift` + `P`).
2. The user types "open file", "save", "save as", or "open folder"
3. Instead of doing the `OpenFileDialog` modal, VSCode displays prompt for path input 
4. As the the user inputs the path string, VSCode lists existing path list (`Ctrl` + `P` or vim style)
5. The user selects the path by pressing `Enter`.

This would greatly improve my productivity. I failed to find the plugin that does exactly this so if there is one, please let me know. I'm gonna go make this plugin or a vscode feature in the meantime.

**Comment by bpasero** [comment]
Did you try to enable `files.simpleDialog.enable` in settings?

**Comment by dxdxdt** [comment]
@bpasero Thanks. Damn. This should be the default in Linux.
