### ISSUE TITLE
Can't input correctly chars into terminal panel with the third party input method 

### ISSUE THREAD

**Issue by wuguzaliang** [Microsoft/vscode#20665]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.8.0|
|format-php|Kasik96|1.1.2|
|code-settings-sync|Shan|2.4.3|
|Angular2|UVBrain|0.4.1|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.2.0|
|project-manager|alefragnani|0.13.2|
|one-monokai|azemoh|0.2.4|
|githistory|donjayamanne|0.1.5|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.5.8|
|tslint|eg2|0.8.1|
|code-runner|formulahendry|0.6.9|
|vscode-javac|georgewfraser|0.0.23|
|rest-client|humao|0.12.2|
|vscode-angular2-emmet|jakethashi|1.0.11|
|angular2|johnpapa|2.0.1|
|sublime-babel-vscode|joshpeng|0.2.4|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|Go|lukehoban|0.6.53|
|MagicPython|magicstack|1.0.6|
|PowerShell|ms-vscode|0.9.0|
|Theme-MaterialKit|ms-vscode|0.1.1|
|Ruby|rebornix|0.10.4|
|java|redhat|0.0.10|
|startanyshell|remcoros|0.3.1|
|vscode-icons|robertohuertasm|7.2.0|
|python|tht13|0.2.3|
|JavaScriptSnippets|xabikos|1.4.0|
|commentator|zerocrunch|1.0.3|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1.  open VS code
2. switch the focus point to terminal console
3. Switch the input method to non mac-system-input.
4. Input any chars or paster any char contents
<img width="1046" alt="qq20170215-234101 2x" src="https://cloud.githubusercontent.com/assets/17598406/22981807/41529374-f3d8-11e6-974b-dcf7910c0f14.png">

**Comment by Tyriar** [comment]
I'm guessing your `$SHELL` is set to `/bin/bash` or `bash`? You will need to add the following to your settings.json:

```js
"terminal.integrated.flowControl": false
```

**Comment by wuguzaliang** [comment]
Gr8, it works now. Thx for your efforts and help
