### ISSUE TITLE
VScode via conda navigator - crash when external drive with name with spaces 

### ISSUE THREAD

**Issue by WesleyJAGdeVries** [microsoft/vscode#206697]
Type: <b>Bug</b>

Name of bitlocker encrypted SSD: "HP external ssd"
Unlock the drive using the built-in bitlocker decryptor with the password.

Using conda navigator (GUI) > launch vscode > in vscode: going to explore tab > click on "Open Folder" > "files" window opens > click on the vertical tab the name of the ssd to open it > crash (vscode closes)

When I try this on a snap vscode install or an apt vscode install (both without using conda), everything works fine. Unless I open vscode via conda.

After changing the name to "hpexternalssd" everything went alright.
Therefore, Its either the capitalized characters or (most likely) the spaces in the name of the bitlocker encrypted drive.

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:16.599Z)
OS version: Linux x64 6.5.0-21-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 4226)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|30.55GB (21.13GB free)|
|Process Argv|--user-data-dir /home/wjagdevries/.anaconda/navigator/Code --crash-reporter-id 3977e550-97ec-4994-988a-2d91de239bba|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.168.0
copilot-chat|Git|0.12.2
copilot-labs|Git|0.17.1121
nbpreviewer|jit|1.2.2
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
tensorboard|ms-|2023.10.1002992421
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-powertoys|ms-|0.1.0
vscode-jupyter-slideshow|ms-|0.1.5
jupyterlab-browser|Vik|0.0.23
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
78248357:30976999
ccp2r6:30958158
dsvsc020:30976470

```

</details>

**Comment by deepak1556** [comment]
If the issue is still present with latest stable, please share the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report
