### ISSUE TITLE
Update50

### ISSUE THREAD

**Issue by HawkLemon** [microsoft/vscode#206662]
Update50 in terminal
failed to connect extension server on port 1337
restarting codespace did not resolve issue

ADD ISSUE DESCRIPTION HERE

Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by RedCMD** [comment]
[F1] => run command `extension.bisect.start`

**Comment by gjsjohnmurray** [comment]
Assuming this relates to CS50 please close this issue and contact the course support channel.
