### ISSUE TITLE
VS Code terribly slow

### ISSUE THREAD

**Issue by kingghallab** [microsoft/vscode#206691]
Type: <b>Performance Issue</b>

i run on one of the latest intel's processor i7 13700hx, and a 32gb ddr5 ram memory, with no more than 15 extentions on my vs code, it runs terribly slow with no valid reason, one thing i noted, is that whenever i enter anything in my text editing it keeps parsing code i guess.

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700HX (24 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (20.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   104	  2760	code main
    0	   111	  3356	   gpu-process
    0	   225	  4080	window [1] (CS112_A1_T5_20230045.cpp - C++ or C - Visual Studio Code)
    0	    96	 18352	window [2] (Issue Reporter)
    0	    41	 19992	   utility-network-service
    0	   142	 27196	extensionHost [1]
    0	   133	 14196	     c:\Users\adham\.vscode\extensions\ms-vscode.cpptools-1.19.4-win32-x64\bin\cpptools.exe
    0	    10	 27600	       C:\WINDOWS\system32\conhost.exe 0x4
    0	     5	 27916	       "c:\Users\adham\.vscode\extensions\ms-vscode.cpptools-1.19.4-win32-x64\bin\cpptools.exe"
    0	    55	 27912	         c:\Users\adham\.vscode\extensions\ms-vscode.cpptools-1.19.4-win32-x64/bin/cpptools-srv.exe 14196 {F9E03158-39DC-4E33-8C6B-C84BC95100E7}
    0	    10	 28000	           C:\WINDOWS\system32\conhost.exe 0x4
    0	    82	 27792	     "C:\Users\adham\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\adham\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=27196
    0	   133	 28104	     "C:\Users\adham\AppData\Local\Programs\Microsoft VS Code\Code.exe" c:\Users\adham\.vscode\extensions\streetsidesoftware.code-spell-checker-3.0.1\packages\_server\dist\main.cjs --node-ipc --clientProcessId=27196
    0	   102	 27268	shared-process
    0	    82	 27300	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (CS112_A1_T5_20230045.cpp - C++ or C - Visual Studio Code)
|    Folder (C++ or C): 18 files
|      File types: exe(5) json(4) cpp(4) c(1) o(1)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: cppdbg(2);
```

</details>
<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
gitignore|cod|0.9.0
python-extensions-pack|dem|1.0.3
githistory|don|0.6.20
code-runner|for|0.12.1
codespaces|Git|1.16.11
vsc-python-indent|Kev|1.18.0
black-formatter|ms-|2024.0.1
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.2
cpptools|ms-|1.19.4
cpptools-extension-pack|ms-|1.3.0
indent-rainbow|ode|8.3.1
code-spell-checker|str|3.0.1
vscode-lldb|vad|1.10.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by Destroy666x** [comment]
Same issue for me. It's especially unbearable with C++. It was not great before, mostly with big files, but now it got waaaaaaay worse, even with small files it can cause few second typing lags.

**Comment by EdwinFairchild** [comment]
same issue for me on Linux , Ubuntu. It has become terribly laggy and slow. Downgraded to 1.86.2 because it was a nightmare to work with. Downgrading fixed issues for me. Ill skip this latest update and try a future one. Nothing in the new one is of importance to me.
