### ISSUE TITLE
Everything is not working in 1.87.0

### ISSUE THREAD

**Issue by huyiwen** [microsoft/vscode#206626]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.87.0
- OS Version: Mac OS Sonoma

Simply everything is not working here. All the extensions like remote-ssh, git, python...

**Comment by kitswas** [comment]
Try doing a clean reinstall.  
Some of the extensions (including Python) could not be updated till I did that.

The git extension problem could be from an older version. See #206315

**Comment by huyiwen** [comment]
Thank you. I've rolled back my  VSCode, and now everything is back to normal.
