### ISSUE TITLE
auto-complete(python plugin) has no effect

### ISSUE THREAD

**Issue by junmoxiao** [Microsoft/vscode#20669]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.8|
|Go|lukehoban|0.6.53|

---

Steps to Reproduce:

i installed the python plugin
1.create an python file 
2.input "#!/usr/bin/env python"
2.then the editor cannot auto complete

**Comment by joaomoreno** [comment]
Please file this issue in https://github.com/DonJayamanne/pythonVSCode
