### ISSUE TITLE
Using more than 58 subschema files in an JSON schema leads to an endless loop

### ISSUE THREAD

**Issue by anticultist** [microsoft/vscode#206610]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

I'm using `TextDocumentContentProvider` to provide a generated JSON schema as it was proposed [here](https://github.com/microsoft/vscode/issues/77433#issuecomment-512726599) by @aeschli.
This approach works fine.
However when I reference more than 58 subschemas with `"$ref": "./child-xy.schema.json"` I observe an endless loop.
VS Code tries to fetch the main and all the subschemas over and over again and never stops.
Besides the obvious issue it also breaks the validation of the json file.

Because of the arbitrary number of 58 and the endless loop character of this behavior I assume it is a bug.
If it were intentional restriction of any kind I would assume that it just stops fetching and does not lead to an endless loop.

If you need a sample code, I created a minimal [demo project](https://github.com/anticultist/vscode-json-ref-issue).
You can observe in the debug console that the schemas are requested endlessly.
Additionally you can see in the output channel `JSON Language Server` that `cancelled` is also printed again and again.

In this demo projects I also tried to recreate this behavior with a file based approach but couldn't reproduce this.
The validation works as intended and there are no cancellation messages it the json output channel.

**Comment by aeschli** [comment]
It looks like there's a limit of virtual documents. @jrieken can you confirm?

The sample defines a schema file in a virtual document. The schema file references 58 more virtual documents.
While requesting these documents, the the JSON extension gets a `onDidCloseTextDocument` event on the first virtual document, causing the server to request its content again.

@anticultist I'll discuss that with @jrieken whayt can be done here but maybe you should think of folding some of the schemas together. Should that be easy possible as it's all virtual?

**Comment by jrieken** [comment]
Yes, tho this is independent of virtual documents but applies to any document opened by extensions, e.g all `vscode.workspace.openTextDocument`-call. Closing of documents happens by age (3min), overall (~80MB) size, and count (50). I guess it's the size limit that's hurting you, we added that for https://github.com/microsoft/vscode/issues/133325. There is currently no way to workaround this

**Comment by anticultist** [comment]
@aeschli I have already a workaround in place which combines all documents into one.
My VS Code extension is a port of the main features of a Monaco editor application where the main json schema dynamically references other (100-200) sub-schemas. Due to the fact that the Monaco editor API and VS Code API differs in some tiny nasty ways I couldn't reuse the code and had to fork it, but in the hope hat I could try to keep them as equal as possible. In the course of this fork I stumbled upon this issue. I hoped, that this issue could be somehow resolved that I could keep the two codebases more in sync...

@jrieken I can not confirm that the size is the issue here. In my sample code the overall size of the main and all sub-schemas is about 20KB. In my production code it is of cause much bigger but I have the same limitation of max 58 sub-schemas. Also no difference with all extensions disabled (starting vs code with `--disable-extensions` flag). I'm also exceed the described limit of 50. The third (time) limitation is also not applicable here, because it happens immediately. Ok with my target 100-200 virtual files I would exceed the limit, but it doesn't seem that this is the real reason for this issue.

I'm more concern at this point, that it not just stops getting the virtual files but tries it over and over again. This limitation feature seems not quite complete. Wouldn't it make more sense to stop asking for the content if the limits are exceed?

**Comment by aeschli** [comment]
@anticultist We have no plans to increase the number of open documents (there needs to be a limit). We could not react on the close event, but that just means such documents will be stale. That would also be a bug, but just much more subtle.

**Comment by aeschli** [comment]
Closing the issue. No work planed.
