### ISSUE TITLE
tunnel requires sudo

### ISSUE THREAD

**Issue by sergiynesterenko90** [microsoft/vscode#206730]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.87.0 (commit 019f4d1419fbc8219a181fab7892ebccf7ee29a2)
- OS Version: Ubuntu 22.04.3 LTS

Steps to Reproduce:

1. run `./code tunnel` 
2. try to log in at vscode.dev/tunnel/.... (link is provided by CLI)
3. cli shows: ` warn Tunnel exited unexpectedly but gracefully, reconnecting`. Browser sees the open tunnel, tried to connect, but then `Cannot reconnect. Please reload the window.`
4. shut down tunnel
5. run `sudo ./code tunnel`
6. open link provided in browser
7. everything works (can see file structure, open terminal, open workspace etc) BUT as root user. 

The last part seems problematic - seems like a bad idea to run everything as root. In the terminal, I can switch out of root and to my normal user, but with a notebook for example, the root user doesn't see any of the python envs.

I did a reinstall of WSl2 recently, and in my last install (from years ago) this wasn't an issue. I was able to run `./code tunnel` and use the typical user, run notebooks etc. I wish I still had that distro around to see the difference in more detail :( But with a fresh install I can't seem to figure out how to get tunnels working without starting the code tunnel as a root user.

**Comment by connor4312** [comment]
Please provide a log of the console output from the CLI, both with sudo and without, when running with `--verbose`. Thanks!

**Comment by sergiynesterenko90** [comment]
Hey @connor4312 thanks for the help!

Here are the logs with `--verbose`, with and without sudo. 

[tunnel-no-sudo.log](https://github.com/microsoft/vscode/files/14540644/tunnel-no-sudo.log)
[tunnel-with-sudo.log](https://github.com/microsoft/vscode/files/14540645/tunnel-with-sudo.log)

**Comment by connor4312** [comment]
Looks like there might be some user-specific network configuration on your machine that is not present with `sudo` -- from the logs it seems like the websocket connection to the tunnel service is just being closed by 'something'.

Note that you can also run tunnels on the Windows side and still open WSL workspaces. In that case the networking will happen on the Windows side which might avoid this issue.

**Comment by sergiynesterenko90** [comment]
Indeed - I didn't realize I could get to WSL by connecting to the windows tunnel. Amazing. Solves my issue! Thank you!

**Comment by connor4312** [comment]
yep, that's new since back in the fall 🙂
