### ISSUE TITLE
Community Polling: Migrating from Electron to EdgeWebView2 for performance boost and less RAM usage

### ISSUE THREAD

**Issue by KhoaLee** [microsoft/vscode#206711]
I believed that me and many other developers around the world have been going back and forth different code edtiors and IDEs, even try to configure NeoVim to be exactly like VSCode. But in the end we come back to VSCode because of extensions and how familiar working with it. Jetbrains products are improve significantly about UI and performance for those who willing to pay for IDE. However, I believe that most of us use VSCode either for studying, side projects development and professional working. 

VSCode has so many improved features for developers over the years but the most signicantly is the speed and ram usage which do not have any plan and many updates for them. I create this poll to ask community if they want Microsoft do something about this for VSCode at least. If anyone have any suggestion or can create a poll for technology that you think can suggest for Microsoft to consider. Please upvote this issue.

**Comment by deepak1556** [comment]
Please refer to https://github.com/microsoft/vscode/issues/118308#issuecomment-1362215823

Moving to Webview2 doesn't guarantee performance win as the underlying rendering architecture will still be the same.
