### ISSUE TITLE
Feature Request: Enable workspace settings to specify required extensions

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#20674]
We spent 20 minutes with a co-worker yesterday trying to figure out why he couldn't debug an Electron app only to find out he hadn't installed the `Debugger for Chrome` extension.  It would be helpful to teams, if one team member could configure all the required extensions in either `.vscode/settings.json` (or some other file).  At the least, VSCode could then tell someone opening the workspace that they need to install extensions and provide them with the list.  Ideally, VSCode would just install the extensions perhaps with some UI giving the user a chance to cancel (maybe he wandered into the wrong repo).

**Comment by mjbvz** [comment]
I believe this is supported using `.vscode/extensions.json`: https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions

**Comment by rkeithhill** [comment]
Cool!  Thanks.
