### ISSUE TITLE
Support browser keybindings (arrow, pageup/down, shift+pageup/down, ctrl+a)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#206747]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/206017
- [ ] https://github.com/microsoft/vscode/issues/204023
- [ ] https://github.com/microsoft/vscode/issues/205028
```

**Comment by DonJayamanne** [comment]
Fixed with https://github.com/microsoft/vscode/pull/207962

**Comment by MasterInQuestion** [comment]
See also:
    Keybindings broken in VSCode web
    [ https://github.com/microsoft/vscode/issues/163432#issuecomment-1312029773](https://github.com/microsoft/vscode/issues/163432#issuecomment-1312029773)
