### ISSUE TITLE
ignore parameter name when using vscode `find match`

### ISSUE THREAD

**Issue by future-158** [microsoft/vscode#206744]
in here, 

```python
foo = 'some_value'
bar = 'some_other_value'

_ = callable( foo=foo, bar=bar)
```
when i want to change variable name foo to other name, i usually select foo use `find match`, but it always select 
foo in argument name which i don't want change. so i manually iterate them one by one.

currently vscode `find` support few flags including whole word, case sensitive, etc. i hope it would include something like `ignore paramter name`, so i can safely change all occurence of variable name without worrying about it would mess code.

(by the way, example is python but i think its not limited to it.)

**Comment by gjsjohnmurray** [comment]
Doesn't the F2 rename feature do the right thing?
