### ISSUE TITLE
Bracket matching (and coloring) broken in some cases

### ISSUE THREAD

**Issue by DarylBeattie** [microsoft/vscode#206700]
Does this issue occur when all extensions are disabled?: ~Yes~ No... turns out they weren't all disabled.

- VS Code Version: 1.87.0
- OS Version: Microsoft Windows [Version 10.0.22631.3235]

Bracket matching seems to be broken as of the 1.87 release.
Previously, it worked fine.
It works in many/most files, but under some circumstances it is broken.

I've attached a simple example file (in its entirety!) to illustrate the issue. You'll note that this file is indeed valid; just the bracket matching and coloration makes it look wrong.

Steps to Reproduce:

1. Open a file with brackets, and find that they don't always match.
![image](https://github.com/microsoft/vscode/assets/108022170/01a77726-9fd1-4d54-ae7e-362c34ca5976)

P.S. I see a lot of people saying that "matches highlighting" is broken in 1.87; that works fine for me.

**Comment by RedCMD** [comment]
could you provide a copy&pastable code snippet please?

````
```tsx
code
```
````

I believe `GraphQL` is an embedded language
might be the same as https://github.com/microsoft/vscode/issues/202938

**Comment by DarylBeattie** [comment]
Sure thing:

```tsx
import { FC, ReactNode, createContext, useCallback, useContext } from "react";
import { GraphQLQuery } from "@aws-amplify/api";
import { API, graphqlOperation } from "aws-amplify";
import { GetFeedQuery } from "../API";
import { getFeed as gqlGetFeed } from "../graphql/queries";

const Example = createContext<{}>({});
export function useFeed() {
  return useContext(Example);
}
type Props = {
  children: ReactNode;
};
export const ExampleProvider: FC<Props> = ({ children }) => {
  const getObjs = useCallback(async () => {
    const param1 = "param1";
    const param2 = "param2";
    const param3 = "param3";
    API.graphql<GraphQLQuery<GetFeedQuery>>({
      ...graphqlOperation(gqlGetFeed, { param1, param2, param3 }),
      authMode: "AMAZON_COGNITO_USER_POOLS",
    });
  }, []);
  return <Example.Provider value={{}}>{children}</Example.Provider>;
};
```

To be clear, there is **NO** embedded GraphQL here. This is all pure TypeScript.
The `gqlGetFeed` from `graphql/queries` is actually an _automatically generated TypeScript constant_; a string that is cast to a defined type.

As I said, this used to work fine -- until yesterday when I updated to 1.87.0

**Comment by hediet** [comment]
Do you have reproduction steps?



![Image](https://github.com/microsoft/vscode/assets/2931520/4191fb4f-131e-45e2-a735-1f18918927ef)

**Comment by DarylBeattie** [comment]
Okay, turns out it's an extension after all. (Boo...)
I thought I tested properly with all extensions turned off, but the GraphQL extension was still on and that breaks the bracket-matching. I'll follow up with them.

**Comment by DarylBeattie** [comment]
An update to the "GraphQL: Syntax Highlighting" has fixed this issue.
