### ISSUE TITLE
Action is not visible in the quick pick on the first item of the group

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#206768]
![Image](https://github.com/microsoft/vscode/assets/10746682/2d18d0c4-6063-416f-9ab1-733550166cb4)

**Comment by TylerLeonhardt** [comment]
@sandy081 this is because `Trace` is your default. Same thing happens if you set a different default:
<img width="605" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/433c1fba-c2c5-4f7a-8bea-db8b080fdc6f">

**Comment by sandy081** [comment]
Oops, this makes sense. Sorry for the noise.
