### ISSUE TITLE
Hovered terminal but no "Extension: ms-python.python"

### ISSUE THREAD

**Issue by lutong99** [microsoft/vscode#206798]
Thanks, we would need a couple of details to identify the issue:
- Can you send your User/Remote settings? We need shell integration to be enabled.
- Hover over the `zsh - test` terminal name and click "Show environment contributions", we would like the contents under that file.

_Originally posted by @karrtikr in https://github.com/microsoft/vscode-python/issues/22141#issuecomment-1745468995_
            
            I have hovered the vscode terminal, but I cannot find ms python activated only Git

![errorpage](https://github.com/microsoft/vscode/assets/49482308/d1f4b3dc-cd61-434a-bfa1-dcd48de9303f)

Additionally, the new terminal will not activate the new conda environment when a conda environment was selected. It will activate the base conda environment regardless of my selection. 

It should be noted that I have two Conda installations, one located in `/usr/local/miniconda/` and the other in `~/miniconda/`. I'm not sure if this will make a difference. All environments I select are located in `~/miniconda/envs/`.

**Comment by karrtikr** [comment]
Please use `Python: Report issue` to file the issue, and make sure to include the Python logs in the template.
