### ISSUE TITLE
output window not scrolling to bottom

### ISSUE THREAD

**Issue by payonel** [Microsoft/vscode#20672]
Version 1.10.0-insider
Commit b7dc5cd88bd76d368db5b7c9972c088f533e2bfd
Date 2017-02-15T15:35:32.349Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
OS: ubuntu 16.04

Steps to Reproduce:

1. Run a tasks.json command
2. watch the output window

There are other reports about "autoscroll to bottom". My output window is auto scolling, but it doesn't scroll to far enough to show the final line, the final line being very important when my command finishes (I like to `&& echo done` after my build scrips), and the final "done" is below the final visible line, behind the status bar of the window (floating window or fullscreen)

![image](https://cloud.githubusercontent.com/assets/6590223/22991237/8281596a-f370-11e6-85e3-6a0fe1a9d6f4.png)

but if i manually scroll to the end
![image](https://cloud.githubusercontent.com/assets/6590223/22991263/90f93634-f370-11e6-8af0-188ea65d884d.png)

This happens on every build, even if I put the cursor in the output window and control-home (the cursor is quickly removed from focus, and the window doesn't continue to hold to the end (enough, but partially). If I wait until the task completes and put the cursor in the window and press ^home, i DO see the full text.

Also I understand that I can view the spinning task notification: 
![image](https://cloud.githubusercontent.com/assets/6590223/22991427/09a523c2-f371-11e6-949f-504133329efe.png)

But I do prefer to see the final line of my builds
One solution is to add some empty newlines to my makefiles

**Comment by payonel** [comment]
even in zen mode i dont see the final line

**Comment by payonel** [comment]
AH, when the task complete, the window appears to bounce back up near the top
Maybe this is more like the other bug reports about not holding an autoscroll behavior

**Comment by payonel** [comment]
hmm, it might be an issue with short tasks, I just finished a very long output command that DID show the final line

**Comment by isidorn** [comment]
@payonel  Output now always autoscrolls - unless you enable the scroll lock action.
If you can constantly reproduce this can you please provide steps so we can further investigate?
For instance you could create a small repository on github for which we could reproduce this behavior and then fix the issue.

When the last line is not revelead - can you manually scroll in order to reveal it?

**Comment by payonel** [comment]
I noticed the lock icon, but my output is not locked
repro is consistent, but there seems to be a dependency on the length (# of lines) of the output to hit this.
I'll update later for fine grain details on repro

**Comment by isidorn** [comment]
Great - looking forward to repro steps

**Comment by isidorn** [comment]
Reopening once we get repro steps.

**Comment by payonel** [comment]
Sorry! got busy.

Easy repro

tasks.json
```
{
    "version": "0.1.0",
    "command": "./script.sh",
    "isShellCommand": true,
    "args": [],
    "showOutput": "always"
}
```

script.sh
```
for n in $(seq 1 20); do
    echo $n
done
```

output window:
![image](https://cloud.githubusercontent.com/assets/6590223/23273970/eca20074-f9b5-11e6-94ae-505e74607878.png)

note the position of the scroll bar, and the unlocked scroll
![image](https://cloud.githubusercontent.com/assets/6590223/23274003/fd9f7442-f9b5-11e6-9177-5bdad2ed61b7.png)

**Comment by isidorn** [comment]
Thanks, reopening and assinging to march to investigate then

**Comment by payonel** [comment]
does not repro in latest 
Version 1.10.0-insider
Commit 40fecfaa77f01672e8a147be71f6f7ccb9cf8a12
Date 2017-02-27T14:13:35.653Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**Comment by isidorn** [comment]
@payonel thanks for checking it because I tried reproing 2 days ago and was having a hard time.
