### ISSUE TITLE
Terminal loses input after python ran a sub-bash

### ISSUE THREAD

**Issue by mstv** [microsoft/vscode#206770]
Type: **Bug**

Does this issue occur when all extensions are disabled?: Yes

Version: 1.87.0 (system setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

This is a duplicate report of #183419, which has not been fixed within one year and was unjustifiably closed as duplicate.
BTW: I must not install Insiders.

**Steps to Reproduce:**

1. create `repro.sh`:

```
#!/usr/bin/bash

echo "### $0 ###"
```

2. create `repro.py`

```
#!/usr/bin/env python3

import subprocess

subprocess.call(['bash', '-c', './repro.sh'])

choice = input(" >> ")
print(choice)
```

3. open a terminal for `bash`
4. run `python repro.py`
5. press `Enter`

--> nothing happens, terminal must be killed

(`Ctrl+D` - as mentioned in https://github.com/microsoft/vscode/issues/183419#issuecomment-1562964062 - does not help either. How could it?)

**Expected behavior:**

The script receives the input and gracefully returns to the Git bash so that further commands can be entered.

**Comment by meganrogge** [comment]
does this reproduce in an external terminal?

**Comment by mstv** [comment]
> does this reproduce in an external terminal?

Of course, it works with all kinds of external shells at hand: `wt`, `conhost` and `Git bash (MinGW64)`.

![grafik](https://github.com/microsoft/vscode/assets/36601201/e18d5196-77b3-4cfb-acf8-3d0456e431b5)

In 2022, this used to work in VS Code, too.

**Comment by meganrogge** [comment]
/duplicate [#205417](https://github.com/microsoft/vscode/issues/205417)

**Comment by mstv** [comment]
This ticket is about the internal terminal, (where `Ctrl+C` perfectly works), @meganrogge.
That's why I doubt this is a duplicate of the (reproducible) bug #205417.
