### ISSUE TITLE
Support extensions from the workspace

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#206783]
A workspace can have an extension that is built only for the workspace. For such extensions, it does not makes sense to publish them to Marketplace and make them available for all workspaces. It would be nice to have an extension available in the workspace and gets loaded only for that workspace.

Examples: 

- ms-vscode.vscode-diagnostic-tools
- ms-vscode.vscode-selfhost-test-provider

**Comment by sandy081** [comment]
CC @hediet @connor4312

**Comment by gjsjohnmurray** [comment]
Maybe migrate `jrieken.vscode-pr-pinger` to this as well? Pinging @jrieken
