### ISSUE TITLE
Add concept of "dynamic" (buffer only) settings

### ISSUE THREAD

**Issue by Bill-Stewart** [microsoft/vscode#20675]
It appears that in #13328 there was a review of settings that should persist to `settings.json` when changed.

It seems to me that there are some settings should have a default setting that comes from `settings.json`, but should not persist to `settings.json` when changed during editing - a "dynamic" ("buffer only"? need a good term) setting.

For example, `editor.wordWrap` should come from global or workspace `settings.json`, but the `toggleWordWrap` command should change wrapping only for the current buffer (view? editor? session? not sure of correct term) rather than persisting to the `settings.json` file. Examples:

* `editor.wordWrap`
* `editor.wrappingColumn`
* `editor.renderWhitespace`

Reason: I want to leave my default settings as they are but change something only temporarily while editing. I believe the `wordWrap` setting used to behave in this way but this was changed for some reason.

If this is implemented, there should be an API to allow changing these "dynamic" settings also.

**Comment by Download** [comment]
Alternatively, do persist them, but persist them keyed by (relative) file path. 
The benefit of persisting such settings per file is that, when toggling stuff for a single file, we usually do so because the deviating setting is more appropriate *for that file*. So we (probably) do appreciate it if this setting is stored, as long as it's stored just for that file.

**Comment by alexandrudima** [comment]
We have decided in today's standup that for 1.10 , we make Toggle Word Wrap "in memory" again ( #21291). i.e. it will not write to user settings, and it will apply only to the current editor instance.

It also means that the wrapping is highly transient. i.e. any touch of the settings.json will lead to it being lost. This is being tracked in #21487

**Comment by jshall** [comment]
👍 Here is supporting scenario

I have a JSON log file that I prefer not be wrapped so can use the one-line-per-event and column alignment to quickly spot changes, while in the other viewing code or even JSON data that I do want wrapped so I only need to scroll along one dimension. In this scenario I would like to have settings.json configured to wrap, use Toggle Word Wrap to disable it for only that buffer.

**Comment by alexdima** [comment]
We have implemented this via `ConfigurationTarget.MEMORY` - https://github.com/microsoft/vscode/blob/222b31ea7f9dbeaae31ac91f0b33cfabeee4e56f/src/vs/platform/configuration/common/configuration.ts#L37
