### ISSUE TITLE
Word wrap doesn't fill editor window

### ISSUE THREAD

**Issue by julesjacobs** [microsoft/vscode#206707]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0
- OS Version: macOS 14.0 (23A344)

Steps to Reproduce:

1. Open a text file with long lines
2. Turn word wrap on

Expected behaviour: fill entire editor window.
Observed behaviour: large space left open on the right hand side (see attached screenshot).

<img width="864" alt="Screenshot 2024-03-02 at 20 08 14" src="https://github.com/microsoft/vscode/assets/476654/adf1fbce-99de-460d-8265-660629d42486">

**Comment by alexdima** [comment]
If you don't mind the slowness of it, you can switch to the advanced wrapping strategy via `"editor.wrappingStrategy": "advanced"`
