### ISSUE TITLE
[Chat] It will always open first registered chat view when I am attempting to open the history session.

### ISSUE THREAD

**Issue by foreverCP3** [microsoft/vscode#206752]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.87.0
- OS Version: 14.2.1 (23C71)

Steps to Reproduce:

I am working on creating a native chat view using the proposal API provided by VSCode. However, when both GitHub Copilot and my extension are activated, it always opens the first registered chat view when attempting to open the history session. I have reviewed the [PR](https://github.com/microsoft/vscode/pull/197933/files#diff-c8add7c48ae271e3ddc678485d52a4ffc02092a0733c87e4dacdb6b437bd0ec5R283) .

<img width="1024" alt="image" src="https://github.com/microsoft/vscode/assets/77433045/eaabe696-dda8-4783-a069-9ff04b46bc70">

 I am curious as to why we don't directly use the args of getHistoryAction to specify the view and provider, instead of obtaining the first registered provider?
 
 ```
                        if (selection) {
				const sessionId = selection.chat.sessionId;
				const view = await viewsService.openView(viewId) as ChatViewPane;
				view.loadSession(sessionId);
			}
```

**Comment by roblourens** [comment]
We won't be supporting multiple chat views. You should be looking at the Chat Participant API, not an "interactive session provider", which will go away https://github.com/microsoft/vscode/issues/199908
