### ISSUE TITLE
Conflicting tooltips in diff viewer

### ISSUE THREAD

**Issue by petwu** [microsoft/vscode#206784]
Type: <b>Bug</b>

1. Modify some versioned file.
2. Open the diff viewer to see the changes side-by-side.
3. Move the mouse over the little arrow in the middle.

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:16.599Z)
OS version: Linux x64 6.7.8-arch1-1
Modes:
Connection to 'ssh-remote+pearl6' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|15.05GB (2.58GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasmawayland|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|

Connection to 'ssh-remote+pearl6' could not be established
</details>Extensions: none

**Comment by petwu** [comment]
![2024-03-04_121446](https://github.com/microsoft/vscode/assets/39537032/585aedea-3241-49d1-9559-ca70e8fb6f43)

**Comment by hediet** [comment]
This is fixed with the new revert buttons.
