### ISSUE TITLE
Polish language support in vscode-speech extension

### ISSUE THREAD

**Issue by MattCCC** [microsoft/vscode#206736]
As per title. The Polish language pack seems to be missing.

**Comment by bpasero** [comment]
Created upstream: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2283

**Comment by bpasero** [comment]
This requires support from the upstream Azure Speech SDK.

**Comment by suside** [comment]
As a workaround I can recommend local [parakeet-tdt-0.6b-v3](https://huggingface.co/nvidia/parakeet-tdt-0.6b-v3) with [cjpais/Handy](https://github.com/cjpais/Handy), it works surprisingly well and can paste text outside vscode.
