### ISSUE TITLE
Is there any event called when a you Open Projects/Folders in Code?

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#2067]
There are some events that are called you open/close a file (`onDidOpenTextDocument` and `onDidCloseTextDocument`), but it appears that aren't similar for **Projects/Folders**.

I would like to detect when a Project/Folder is opened in **Code**. Via command line, like `code C:\Temp\Myfolder` or using the menu `File / Open Folder...`. Don't get confused about _opening sub-folders in the tree, this is not the case_ :smile: 

At first, it doesn't matter if a new **Code** instance is created, or if it only changes the current Folder/Project, And it should be called also when you use `Open Recent`.

Thanks in advance

**Comment by jrieken** [comment]
That's currently not possible because each window acts like a new instance. We to have a IPC pipe to check that you don't open the same folder a second time but that's more or less it. 

Valid request tho

**Comment by kantlove** [comment]
It's been several months and I notice that there is no related information. So I'd like to ask if there is an event for opening a folder now.

**Comment by jrieken** [comment]
There is now `onDidChangeWorkspaceFolders`.
