### ISSUE TITLE
Play button is not working

### ISSUE THREAD

**Issue by alinasofie** [microsoft/vscode#206773]
Type: <b>Bug</b>

Hi, English is not my main language but I'll try to explain as much as I can. I've faced a problem with my Run Code-button. When I try to run the program, I get a notification saying "Code language not supported or defined". But when I use path Terminal > Run active file, everything is working. I don't know where the problem could be except something in the latest update. I'd be very grateful if you knew how to fix it if it's something on my computer or something in VS code.
Thank you!

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12450H (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (1.09GB free)|
|Process Argv|--crash-reporter-id d1a59019-f49b-48f0-b20c-1511188d1ed3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.4
vscode-html-css|ecm|2.0.9
code-runner|for|0.12.1
node-module-intellisense|lei|1.5.0
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.22.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.1
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.4
cpptools-extension-pack|ms-|1.3.0
tkinter-snippets|Nik|2.0.2
platformio-ide|pla|3.3.3
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30968132
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30973184
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
bg6jg535:30958357
78248357:30976999
ccp1r3:30958155
dsvsc020:30976470

```

</details>

**Comment by gjsjohnmurray** [comment]
Is that button contributed by the Code Runner extension which you have installed? One way to check is to disable that extension and see if the button disappears. If it does, please report your issue on the extension repository.

**Comment by alinasofie** [comment]
Thank you, I'll move there.
