### ISSUE TITLE
VS code crash in  administrator mode

### ISSUE THREAD

**Issue by divyang4481** [microsoft/vscode#206731]
Type: <b>Bug</b>

The window terminated unexpectedly (reason: 'launch-failed', code: '18')

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (2.96GB free)|
|Process Argv|--crash-reporter-id ccf113c9-044f-4e85-b5c3-597f8cbb9a23|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|2.12.0
vscode-django|bat|1.15.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
gitlens|eam|14.8.2
mithril-emmet|Fal|0.7.7
chatgpt-copilot|fei|4.3.1
vscode-firefox-debug|fir|2.9.10
copilot|Git|1.171.0
copilot-chat|Git|0.13.0
go|gol|0.41.1
cloudcode|goo|2.4.0
vsc-python-indent|Kev|1.18.0
python-path|mge|0.0.14
vscode-docker|ms-|1.29.0
debugpy|ms-|2024.2.0
pylint|ms-|2023.10.1
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-powertoys|ms-|0.1.0
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.348.0
remote-wsl|ms-|0.86.0
cpptools|ms-|1.19.4
sqltools|mtx|0.28.1
sqltools-driver-sqlite|mtx|0.5.0
autodocstring|njp|0.6.1
sqlite-viewer|qwt|0.3.13
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8
vscode-sqlite3-editor|yy0|1.0.178

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
bg6jg535:30958357
ccp1r6:30958156
dsvsc020:30976470

```

</details>

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/122951 , if you need to run in admin mode only the following workaround is available

* Open the Command Palette
* Run the `Preferences: Configure Runtime Arguments` command.
* This command opens a argv.json file to configure runtime arguments. You might see some default arguments there already.
* Add "disable-chromium-sandbox": true.
* Restart VS Code.
