### ISSUE TITLE
Markdown Table Styling Sucks

### ISSUE THREAD

**Issue by babakfp** [microsoft/vscode#206741]
It doesn't even look like a table!

![Screenshot 2024-03-03 143956](https://github.com/microsoft/vscode/assets/44144724/3f14e36e-38ba-40d0-9cce-eee7a6b2b842)

Why do things like this have to suck? It may take a few minutes to add some gorgeous styling.

**Comment by mjbvz** [comment]
Submit a pr instead of being rude

**Comment by babakfp** [comment]
Fix the issue instead of ignoring it!

More issues (indentation):

![image](https://github.com/microsoft/vscode/assets/44144724/6d6a1894-0ddd-4da0-9c5e-357616e17b6b)

![image](https://github.com/microsoft/vscode/assets/44144724/a8c0e43e-c1de-4434-8c25-a04500c3022f)

**Comment by babakfp** [comment]
![image](https://github.com/microsoft/vscode/assets/44144724/90e3377f-a49d-49a1-9345-b3cc5cd5eb94)
