### ISSUE TITLE
Implement a restart VSCode button or menu option

### ISSUE THREAD

**Issue by mladen5000** [microsoft/vscode#206705]
There are many times where restarting vscode has been useful to fixing some hangup or freeze. It seems like the only way to restart without quitting/reopening, is when there is an update. But is it possible to restart otherwise. I think it would be a simply drop down menu option to implement. The main use-case of this for me is when jupyter hangs.

**Comment by IllusionMH** [comment]
Just in case. Are you aware of commands `> Developer: Reload Window` and `> Restart Extensions Host `?

They already exists and should solve most of the problems that you expect to fix with restart.

Are there cases when commands above don't fix the problem?

**Comment by mladen5000** [comment]
No I was not, thank you.
