### ISSUE TITLE
Open Terminal and cd to directory of current file

### ISSUE THREAD

**Issue by joetoth** [microsoft/vscode#206746]
I want to open a terminal in the same directory as the current file I have open.

The following works with a macros extension and it's pretty hacky albeit. Is there a better way to open a terminal and send a command?

  "macros": {
    "termInFolder": [
      "workbench.action.createTerminalEditorSide",
      "workbench.action.focusLeftGroup",
      {
        "command": "workbench.action.terminal.sendSequence",
        "args": {
          "text": "cd $(realpath \"${fileDirname}\")\u000D"
        }
      },
      "workbench.action.focusRightGroup",
    ]
  }

Thanks!

**Comment by meganrogge** [comment]
there's not a way to do this in core. an extension seems like the right approach

**Comment by nkn-ms** [comment]
this vscode extension is available. cd to active file directory with one click.

https://marketplace.visualstudio.com/items?itemName=nkn-ms.cd-to-active-file-directory-in-statusbar
