### ISSUE TITLE
Strange highlight appear when switch to vscode window

### ISSUE THREAD

**Issue by rintrint** [microsoft/vscode#206715]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0
- OS Version: Windows 10 22H2

Steps to Reproduce:

1. open a new file and type some words
2. ALT+TAB switch to other window and go back to vscode

<img width="244" alt="789" src="https://github.com/microsoft/vscode/assets/152774318/f162ff98-e8ec-4c7b-aa87-da12e93e32dc">

I search for highlight settings and tried all of them. Nothing works.
The problem didn't appear before. I also checked the four most recent update histories.

**Comment by HiDolen** [comment]
I encountered a similar issue after updating my VSCode. While typing, the highlighting behaves strangely. However, closing and reopening the file restores the highlighting to normal.

![image](https://github.com/microsoft/vscode/assets/87627379/1ae2236d-3257-423a-8551-f30dd0943532)

- VS Code Version: 1.87.0
- OS Version: Windows 11 23H2（wsl: Ubuntu 22.04）

**Comment by inwardmovement** [comment]
Same here since last update.

**Comment by feliperdamaceno** [comment]
I have the same issue here, not sure what is triggering this behavior:

![Code_wEbFaN6fq6](https://github.com/microsoft/vscode/assets/83041739/7ac970b8-3061-47d3-a059-c038c19175d5)

**Comment by rintrint** [comment]
Okay. I go back to 1.86.2 and turn off auto update. Hope it could be fixed in 1.87.1.

1.86.2 download:
https://code.visualstudio.com/updates/v1_86

For windows system installer, remove `-user` from download url.
eg.
https://update.code.visualstudio.com/1.86.2/win32-x64-user/stable
https://update.code.visualstudio.com/1.86.2/win32-x64/stable

**Comment by hediet** [comment]
@HiDolen this looks like the extension sends out invalid semantic highlighting (i.e. nothing that VS Code core can fix).

@rintrint can you check the dev tools output?

**Comment by rintrint** [comment]
@hediet It's seems to be a bug of Occurrences Highlight. I turned it off and the highlight behavior change instead of completely off and disappear. Unlike old version.

**Comment by echolet** [comment]
I'm seeing the same behavior on MacOS. In some open editor random text is highlighted. Doesn't happen on all editor windows. Typing in the editor makes this highlighting disappear. Switching to another editor tab and then switching back the highlighting reappears. The highlighted text seems to always be a word, possibly the word where the text cursor was in.

**Comment by LambdaZed** [comment]
same problem
```
Version: 1.87.0
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:51.279Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 21.2.0
```

**Comment by tomatic** [comment]
Also seeing this on 1.87.0 in Linux. It appears this is connected to the setting `editor.occurrencesHighlight`. If that's set to `singleFile`, the editor highlights all occurrences of the word under the cursor. But I've set that to `off`, so it shouldn't be highlighting anything. Instead, whenever the editor gets focus or I manually reload, it highlights all occurrences of the word under the cursor. 

I'm able to reproduce this with all extensions disabled and it's not tied to any particular file type. So this seems to be an issue with the core occurences highlighting feature.

https://github.com/microsoft/vscode/assets/367058/a3866d5a-12fa-4ae9-8a9c-8c6fd4508981

```
Version: 1.87.0
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:16.599Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.5.0-21-generic
```

**Comment by echolet** [comment]
This looks to be a duplicate of #206486

**Comment by rintrint** [comment]
> This looks to be a duplicate of #206486

Thanks. I tested it again in [VS Code Insiders](https://code.visualstudio.com/insiders/). It's solved. look forward to 1.87.1 release
