### ISSUE TITLE
VS Code Flashing Screen

### ISSUE THREAD

**Issue by misterxiaotan** [microsoft/vscode#206886]
Type: <b>Bug</b>

I hope this message finds you well. I am writing to report an issue I have been experiencing with VS Code recently. Whenever I switch files, the screen keeps flashing. I am wondering if this could be a bug in the software.

I have tried uninstalling and reinstalling VS Code, but unfortunately, it did not solve the issue. The flashing screen persists even after the reinstallation.

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.34GB free)|
|Process Argv|--crash-reporter-id 9e156dd1-d36e-44a3-91ca-978c61193ec4|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
cssrem|cip|3.1.1
vue-snippets|hol|1.0.4
vscode-language-pack-zh-hans|MS-|1.87.2024022809
vetur|oct|0.37.3
vue-vscode-snippets|sdr|3.1.1
volar|Vue|2.0.4
vscode-typescript-vue-plugin|Vue|1.8.27

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30968132
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
cppperfcontrol:30979541
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by Atliac** [comment]
Version **1.89.1**, this issue still exists.

Disabling GPU acceleration seems to fix this issue.

**Comment by deepak1556** [comment]
Can you confirm if the issue still persists with latest stable, if it does please try running with `--disable-gpu`
