### ISSUE TITLE
Addition of Hungarian language support to the VS Code Speech extension

### ISSUE THREAD

**Issue by DianaMToledo** [microsoft/vscode#206823]
Dear VS Code Speech Extension Development Team,

I hope this message finds you well. I am writing to kindly request the addition of Hungarian language support to the VS Code Speech extension.

Recently, GitHub announced that the Copilot Voice will not become a GitHub product, which we were eagerly anticipating. They mentioned that official development requests can be made in the repository.

The use of AI with instructions formulated and circled in one's own language is a tremendous help. Expressing these instructions verbally in one's native language can be done much faster. There are already extensions available in several languages, including Turkish, Indian, and even Russian.

Please consider us, the Hungarians, as well. There are numerous Hungarian development teams working diligently, and this addition would be a significant aid for me and my colleagues.

Thank you for your consideration and for the excellent work you do.

Best regards,
Diana

**Comment by bpasero** [comment]
This requires support from the upstream Azure Speech SDK.
