### ISSUE TITLE
In the past 5 minutes, the TypeScript language service unexpectedly suspended for the 5 time

### ISSUE THREAD

**Issue by semmy2010** [Microsoft/vscode#20685]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.13.2|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.6|
|vscode-html-css|ecmel|0.0.33|
|auto-rename-tag|formulahendry|0.0.11|
|vue-snippets|hollowtree|0.1.0|
|beautify|HookyQR|0.8.0|
|sky-react-create-snippet|lulinmemeda|0.0.3|
|vscode-icons|robertohuertasm|7.2.0|
|vue|seanwash|0.4.2|
|guides|spywhere|0.6.1|
|react-beautify|taichi|0.3.0|

---
![_20170216102606](https://cloud.githubusercontent.com/assets/4402907/23004803/aba158d6-f433-11e6-9951-190d8eb79bcb.png)

Steps to Reproduce:

1.open vsc;
2.open javascript file
3.The warning bar has been beating, unable to close,and warning's tip is In the past 5 minutes, the TypeScript language service unexpectedly suspended for the 5 time

**Comment by mjbvz** [comment]
If you see a message about a missing `typescript/...` file, you may be seeing #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

Let me know if this is not the case

**Comment by semmy2010** [comment]
@mjbvz I used the command subst X: to map a virtual disk X disk, and then work on the X disk. And how can I solve this problem?

**Comment by mjbvz** [comment]
Opening a folder from a mapped network drive will crash TypeScript 2.1.6. We are tracking a fix here: https://github.com/Microsoft/TypeScript/issues/13997

Thanks
