### ISSUE TITLE
panel chat voice recording animation bug

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#206833]
in oss off of main, in the panel chat, when I press the start recording button, I see the mic spinning 

https://github.com/microsoft/vscode/assets/29464607/4b7851b1-38ce-4ef5-bc58-c42a3d543125

**Comment by bpasero** [comment]
Fine for me:

![image](https://github.com/microsoft/vscode/assets/900690/a219d1d2-a1ad-433d-aee7-65d785801c91)

**Comment by meganrogge** [comment]
Just checked out main again and am not seeing it.

**Comment by roblourens** [comment]
If you pulled while vscode was running and reloaded the window, it could have been the issue where CSS files are not reloaded until you restart vscode... that drives me crazy
