### ISSUE TITLE
Log whenever the application detects tampering of sources

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#206874]
> Confirmed that we do track the integrity of sources today and surface a notification to users via https://github.com/microsoft/vscode/blob/d73fa8b14a6c873958d00a7d7ad13fcb540a052c/src/vs/workbench/services/integrity/electron-sandbox/integrityService.ts#L85-L120. It is also added to issues created from our builtin issue reporter. We can add this data to trace logs as well for cases were the issues are created outside the application.

_Originally posted by @deepak1556 in https://github.com/microsoft/vscode/issues/206522#issuecomment-1978225514_

**Comment by bpasero** [comment]
This is a great idea:

![image](https://github.com/microsoft/vscode/assets/900690/2c99a12b-af0b-4718-a746-1fce444c880f)

**Comment by ssalbdivad** [comment]
Previously, extensions that patched VSCode like [Background](https://marketplace.visualstudio.com/items?itemName=Katsute.code-background) would occasionally result in a notification only after VSCode was updated.

After this change, this banner appears every time VSCode is opened, even if it was previously dismissed for the same version. This feels very obtrusive.

Was that an intended part of this change?

![image](https://github.com/microsoft/vscode/assets/10645823/8f3a5113-6dea-4a48-a578-b8e86c82b553)

**Comment by bpasero** [comment]
Banner will be removed again in https://github.com/microsoft/vscode/pull/207050, I think it will cause more harm than being useful.
