### ISSUE TITLE
Git authentication dialog does not appear on the task bar

### ISSUE THREAD

**Issue by vossad01** [Microsoft/vscode#20681]
- VSCode Version: 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519)
- OS Version: Linux Mint 18.1 (Cinnamon)

**Steps to Reproduce:**

1. Through VS Code, try to push code to a repository where entering credentials are required

**Actual Behavior:**
The resulting git authentication dialog does not appear on the task bar.

As a result, it is possible to lose this window behind other windows and not easily recover or find the window again.  Additionally, if you minimize the authentication window causing it to be completely lost and making git actions in VS Code unavailable until you close the VS Code window.

**Expected Behavior:**
The resulting git authentication appears on the task bar.

**Comment by joaomoreno** [comment]
Auth is no longer a dialog
