### ISSUE TITLE
Vs Code screen blink

### ISSUE THREAD

**Issue by danmiyamura** [microsoft/vscode#206859]
Type: <b>Bug</b>

When open the VS Code and move the mouse cursor along the "file", "edit"... the VS Code window starts to blink. I try to uninstall at all and the issue continue

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.92GB free)|
|Process Argv|--crash-reporter-id 5061610a-9661-46f5-8839-77e5e1487414|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
bg6jg535:30979843
78248357:30976999
dsvsc020:30976470

```

</details>

**Comment by danmiyamura** [comment]
https://github.com/microsoft/vscode/assets/37915988/5330e7b5-c7cd-4d22-984a-c7a0b03ef318

fyi

**Comment by deepak1556** [comment]
Can you confirm if the issue is present with latest stable, if it does please try running with `--disable-gpu`
