### ISSUE TITLE
Getting a flood of `FoldingRangeProvider` requests for the same file

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#206841]
Does this issue occur when all extensions are disabled?: No - it's an extension API issue

Version: 1.87.0 (user setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

We're seeing that VS Code is invoking our `FoldingRangeProvider` redundantly, sometimes hundreds of times, while an active request is still pending for the same file.

Our (C/C++ extension) `FoldingRangeProvider` is very simple.  It's essentially just forwards requests to our native process using `LanguageClient.sendRequest`.  However, sometimes we inexplicably get redundant requests for folding ranges for a file that there is already an outstanding request for, without the prior request being cancelled.  We definitely only call `registerFoldingRangeProvider` once as the extension starts up.  To mitigate the issue, I added [code to coalesce multiple identical requests for the same file](https://github.com/microsoft/vscode-cpptools/blob/724b47922e1b7324c7ce9fcb35f47001b445d66f/Extension/src/LanguageServer/Providers/foldingRangeProvider.ts#L34C1-L41C10), and added logging to `console.log` when the redundant requests arrive. (The issue occurred without this logic, and with our provider coded to do almost nothing other than forward the call to `sendRequest`.)

Could someone take a close look at how `FoldingRangeProvider`'s are handled, and let us know if there is something we could possibly be doing that would result in these (sometimes hundreds of) redundant folding range requests?  The issue repros only occasionally, but when it does it potentially causes VS Code to lock up for several seconds to a minute.  The only repro I can offer is to use the C/C++ Extension for a while and keep an eye on the console log until it gets into this unusual state.

Perhaps [this issue reporting potential listener leaks](https://github.com/microsoft/vscode-cpptools/issues/12052) may be related, as the user mentions the `Redundant folding ranges request received` error message, and a listener being redundantly registered would seem like a possible cause of this type of issue.

**Comment by alexandruavadanii** [comment]
I thought I could help by trying a `git bisect` between `1.80.0` (I don't remember seeing this issue last fall) and current `main/HEAD`, but I with the latest `vscode-cpptools 1.19.5` and `vscode 1.80.0`, the problem(s) are still there, only the listener leak properly points to sticky scroll (while in main, the messages are a bit less helpful and provide an unrelated trace?):

```
event.ts:866 [afa] potential listener LEAK detected, having 263 listeners already. MOST frequent listener (89):
check @ event.ts:866
_event @ event.ts:1037
SyntaxRangeProvider @ syntaxRangeProvider.ts:43
createModelFromProvider @ stickyScrollModelProvider.ts:424
(anonymous) @ stickyScrollModelProvider.ts:424
_deliver @ event.ts:1127
_deliverQueue @ event.ts:1138
fire @ event.ts:1162
$emitFoldingRangeEvent @ mainThreadLanguageFeatures.ts:804
_doInvokeHandler @ rpcProtocol.ts:458
_invokeHandler @ rpcProtocol.ts:443
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
_deliver @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
port.onmessage @ localProcessExtensionHost.ts:376
event.ts:867 Error
    at Stacktrace.create (event.ts:880:25)
    at Object._event [as onDidChange] (event.ts:1036:34)
    at new SyntaxRangeProvider (syntaxRangeProvider.ts:43:35)
    at StickyModelFromCandidateSyntaxFoldingProvider.createModelFromProvider (stickyScrollModelProvider.ts:424:20)
    at UniqueContainer.value (stickyScrollModelProvider.ts:424:85)
    at Emitter._deliver (event.ts:1127:13)
    at Emitter._deliverQueue (event.ts:1138:9)
    at Emitter.fire (event.ts:1162:9)
    at MainThreadLanguageFeatures.$emitFoldingRangeEvent (mainThreadLanguageFeatures.ts:804:8)
    at RPCProtocol._doInvokeHandler (rpcProtocol.ts:458:17)
    at RPCProtocol._invokeHandler (rpcProtocol.ts:443:32)
    at RPCProtocol._receiveRequest (rpcProtocol.ts:373:19)
    at RPCProtocol._receiveOneMessage (rpcProtocol.ts:299:10)
    at UniqueContainer.value (rpcProtocol.ts:161:42)
    at Emitter._deliver (event.ts:1127:13)
    at Emitter.fire (event.ts:1158:9)
    at BufferedEmitter.fire (ipc.net.ts:650:19)
    at port.onmessage (localProcessExtensionHost.ts:376:17)

[...]
[Extension Host] Redundant folding ranges request received for: file:///c%3A/Users/alav/Desktop/cpptools-test/2.c (at console.<anonymous> (c:\Users\alav\Desktop\vscode\out\vs\workbench\api\common\extHostConsoleForwarder.js:45:26))
```

The listener leak + redundant folding ranges do seem to come together though.

**Comment by aeschli** [comment]
Verified that both folding and sticky scroll correctly cancel their requests.

**Comment by sean-mcmanus** [comment]
@aeschli Our team believes this is a VS Code bug still -- we're seeing the number of folding ranges grow exponentially every time the active document changes, so eventually our extension becomes unusable due having to process an "endless" number (thousands) of these requests.

**Comment by sean-mcmanus** [comment]
@aeschli It appears the repro of exponentially increase get folding ranges requires > 1 document to be visible at once.

**Comment by aeschli** [comment]
I tried with multiple editors visible, also some editors showing the same file, but can not see the number of requests increasing to more than 2 requests per modified editor.
- create an extension (`yo code`) with the code snippet [above](https://github.com/microsoft/vscode/issues/206841#issuecomment-1978469227).
   -   add `"activationEvents": [ "onLanguage:java" ]` to the package.json
- run VS Code with the extension and create some `java` files
-  open one or more java files in editors
-  make some changes in a Java file and observe in the dev tools console that there are 2 folding provider requests fired per document change
- disable folding with `"editor.folding": false` and `"editor.stickyScroll.enabled": false` and verify that there are no longer requests fired.

If you can come up with similar reproducible steps that would be great.

Maybe check if some other extension is installed that makes requests.

**Comment by alexandruavadanii** [comment]
@sean-mcmanus does the exponential increase in requests happen with https://github.com/microsoft/vscode-cpptools/pull/12063 applied too, or only without?

Because if it's only without, I did notice an issue with the promise resolve in:
https://github.com/microsoft/vscode-cpptools/blob/6ccc588d696d06e651de0375a6e90b39a81c4fea/Extension/src/LanguageServer/Providers/foldingRangeProvider.ts#L51-L52
which should probably looks more like this (return the promise resolution result instead of the actual promise): https://github.com/alexandruavadanii/vscode-cpptools/blob/90c21e472849ee84d69bfe838a32723276c3e518/Extension/src/LanguageServer/Providers/foldingRangeProvider.ts#L51-L52

**Comment by Colengms** [comment]
Hi @aeschli .  To clarify, we repro with the (simple) code [here](https://github.com/microsoft/vscode-cpptools/blob/042c4585cf8be38dc83694c08269f4e5659e74a1/Extension/src/LanguageServer/Providers/foldingRangeProvider.ts) 

The issue appears to be related to `onDidChangeFoldingRanges`, which your example did not exercise.

I can reproduce the issue easily with the following simple extension.  Switching back and forth between two open java files (both simultaneously visible), and running the "Hello World" command, I see that refresh triggers more and more requests each time.

```
import * as vscode from 'vscode';

let requestId: number = 0;

export class FoldingRangeProvider implements vscode.FoldingRangeProvider {
    public onDidChangeFoldingRangesEvent = new vscode.EventEmitter<void>();
    public onDidChangeFoldingRanges?: vscode.Event<void>;

    constructor() {
        this.onDidChangeFoldingRanges = this.onDidChangeFoldingRangesEvent.event;
    }

    async provideFoldingRanges(document: vscode.TextDocument, context: vscode.FoldingContext, token: vscode.CancellationToken): Promise<vscode.FoldingRange[] | undefined> {
		const id = requestId++;
		console.log(`[${id}] folding ranges requested ${document.fileName} ${document.version}`);
		token.onCancellationRequested(() => { console.log(`[${id}] folding ranges cancelled`); });
		return new Promise((resolve, reject) => {
			setTimeout(() => {
				console.log(`[${id}] folding ranges resolved ${token.isCancellationRequested ? 'cancelled' : 'ok'}`);
				resolve([ new vscode.FoldingRange(0, 10) ]);
			}, 2000);
		});
}

    public refresh(): void {
        this.onDidChangeFoldingRangesEvent.fire();
    }
}


export function activate(context: vscode.ExtensionContext) {

	console.log('Congratulations, your extension "testextension" is now active!');
	let provider = new FoldingRangeProvider();
	let disposable = vscode.commands.registerCommand('testextension.helloWorld', () => {
		vscode.window.showInformationMessage('Hello World from TestExtension!');
		provider.refresh();
	});
	context.subscriptions.push(vscode.languages.registerFoldingRangeProvider({ language: "java" }, provider));
	context.subscriptions.push(disposable);
}

// This method is called when your extension is deactivated
export function deactivate() {}
```
