### ISSUE TITLE
npm not showing files

### ISSUE THREAD

**Issue by Mabvuu** [microsoft/vscode#206821]
Type: <b>Bug</b>

i install npm it says successful  but files not showing

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.90GB free)|
|Process Argv|--crash-reporter-id 70740283-8e4c-4e80-9910-7efcdc565b68|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.10.5
dart-code|Dar|3.84.0
flutter|Dar|3.84.0
es7-react-js-snippets|dsz|4.4.3
csharp|ms-|2.18.16
vscode-dotnet-runtime|ms-|2.0.2
vscode-react-native|msj|1.12.3
gradle-language|nac|0.2.3
awesome-flutter-snippets|Nas|4.0.1
material-icon-theme|PKi|4.34.0
vscode-thunder-client|ran|2.19.2
java|red|1.28.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.13.5
vscode-java-debug|vsc|0.56.2
vscode-java-dependency|vsc|0.23.5
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0
vscode-react|zha|0.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
cppperfnew:30973185
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
8f97e687:30977000
dsvsc020:30976470
666c4381:30973075

```

</details>

**Comment by Mabvuu** [comment]
> * Open your terminal or command prompt to verify npm was successfully installed
> * Type the following command and press Enter:
>   ```shell
>   npm -v
>   ```
> * If npm was installed successfully, you should see the version number printed in the terminal.

Its still not working. If i try to install express/mongodb/ whatever.. it tells me its been successfully installed but i can't see the files in my folder

**Comment by joyceerhl** [comment]
What files are you expecting to see in your folder? What command did you run?

**Comment by Mabvuu** [comment]
> What files are you expecting to see in your folder? How did you install npm?

Ran npm install express.... was expecting package.json etc...

**Comment by IllusionMH** [comment]
You need to create package.json by yourself manually or with `npm init`. Otherwise it would install dependencies in parent folders with `package.json`
