### ISSUE TITLE
Allow regexp replacement for markdown link insert default text

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#206810]
![](https://github.com/microsoft/vscode/assets/2931520/38af6d17-e385-4d6b-8b5c-e211c490dd90)

It would be super cool if the default link text wouldn't be `text`, but `vscode#204371`.

I could imagine that there is some `markdown.defaultLinkText` property:
```
"markdown.defaultLinkText": {
   "https://github.com/([a-zA-Z0-9]+)/([a-zA-Z0-9]+)/issues/([0-9]+)": "\1#\3",
}
```

**Comment by mjbvz** [comment]
Closing since this hasn't gotten much feedback since it was opened
