### ISSUE TITLE
Violent flash of white when restoring the VSCode window

### ISSUE THREAD

**Issue by wobbier** [microsoft/vscode#206863]
Does this issue occur when all extensions are disabled?: Yes

This is particularly bad on a 32:9 monitor.

https://github.com/microsoft/vscode/assets/3254047/ff438259-a0dd-45e4-bdba-b2f49408eed3

- VS Code Version: 1.87.0
- OS Version: Windows 11 - 22631.3155

Steps to Reproduce:

1. Open VSCode and Minimize it
2. Restore VSCode

**Comment by Hyrtwol** [comment]
sadly it's not only vs-code that flashbang you when you restore when using dark mode. it just seems like vs-code do more than other apps maybe because it's not a native app?
looks like windows still today uses white as the clear color.
fyi happens in both win 10 & 11

**Comment by Sembiance** [comment]
Happens in Linux too. Switching between virtual workspaces and huge white flash whenever switching to vscode.
