### ISSUE TITLE
Go to Definition "Could Not find anything" Markers Not being Cleared

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#20686]
Open a ts file: 

```ts
'safdsa'
```

Put cursor inside the string and press F12 multiple times (triggering go to definition). Then move the cursor and repeat. Notice that the `Could not find anything` marker is incorrectly persisted

<img width="680" alt="screen shot 2017-02-15 at 6 40 23 pm" src="https://cloud.githubusercontent.com/assets/12821956/23005029/ccfe7228-f3ae-11e6-8e5c-61fd6c08540b.png">

**Comment by joaomoreno** [comment]
We should also fix the message to match the context: _No references found_, or something like that.
