### ISSUE TITLE
tsconfig.json schema validation failed

### ISSUE THREAD

**Issue by mengdu** [microsoft/vscode#206862]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0
- OS Version: Darwin x64 20.3.0
- Region: China

Steps to Reproduce:

1. Open `tsconfig.json`
2. It will got:

```txt
Problems loading reference 'https://json.schemastore.org/tsconfig': Unable to load schema from 'https://json.schemastore.org/tsconfig': socket hang up.(768)
JSON schema for the TypeScript compiler's configuration file
```

![image](https://github.com/microsoft/vscode/assets/11366654/071edd4d-6c98-4bd5-b1cb-eb3defd0f5f7)

The schemastore got `HTTP Error 503. The service is unavailable.`

<img width="731" alt="image" src="https://github.com/microsoft/vscode/assets/11366654/3b9af2c7-e375-4dce-ae4f-99ef1780847d">

I have tried VPN proxy but it still hasn't been resolved.

**Comment by socker210** [comment]
Same here

**Comment by funnisimo** [comment]
I get a similar error when opening "package.json"

Problems loading reference 'https://json.schemastore.org/package': Unable to load schema from 'https://json.schemastore.org/package': Service Unavailable. The server is currently unavailable (overloaded or down).
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Service Unavailable</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=u.(768)
CSS contributions to package.json

However, going to "https://json.schemastore.org/package" on chrome and safari and duckduckgo works fine.

Version: 1.87.0 (Universal)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:56.944Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 22.6.0

**Comment by aeschli** [comment]
Caused by json.schemastore.org being down: https://github.com/SchemaStore/schemastore/issues/3620

https://github.com/microsoft/vscode/issues/206792 is about shipping copies of some schemas with VS Code.
