### ISSUE TITLE
High CPU Usage Code Helper (Renderer)

### ISSUE THREAD

**Issue by herberthobregon** [microsoft/vscode#206852]
Type: <b>Bug</b>

Open VScode and see your CPU Usage
![image](https://github.com/microsoft/vscode/assets/6503845/08fdd483-2c41-442a-bfcf-077c7c20e078)

![image](https://github.com/microsoft/vscode/assets/6503845/6e19eed9-a80a-4027-af2d-5922b8eeb527)

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:51.279Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|32.00GB (5.80GB free)|
|Process Argv|--crash-reporter-id 6400a2ea-63e2-4f84-a4ed-22d915a4b18d|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (73)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
sort-imports|ama|6.3.1
vscode-symlink|anb|0.0.3
package-json-upgrade|cod|2.1.2
vscode-mysql-client2|cwe|6.9.5
dart-code|Dar|3.80.0
flutter|Dar|3.80.0
vscode-eslint|dba|2.4.4
xml|Dot|2.5.1
gitlens|eam|14.7.0
prettier-vscode|esb|10.1.0
opensslutils|ffa|1.1.1
vscode-jest-runner|fir|0.4.72
vscode-sql-tagged-template-literals-syntax-only|fri|0.0.19
kotlin|fwc|0.2.34
codespaces|Git|1.16.8
copilot|Git|1.155.0
copilot-chat|Git|0.11.1
vscode-pull-request-github|Git|0.79.2024011609
go|gol|0.40.3
vsc-nvm|hen|0.0.3
vscode-edit-csv|jan|0.8.3
x509-parser|jlc|0.0.6
vscode-graphviz|joa|0.0.6
svg|joc|1.5.3
solidity|Jua|0.0.165
vscode-gutter-preview|kis|0.30.0
lit-snippets|lit|1.0.2
vscode-lottie|lot|1.0.5
kubernetes-templates|lun|1.3.1
regionfolder|map|1.0.22
rainbow-csv|mec|3.11.0
vscode-language-babel|mgm|0.0.40
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.28.0
vscode-kubernetes-tools|ms-|1.3.15
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1100101639
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
vsliveshare|ms-|1.0.5905
vscode-json-editor|nic|0.3.0
indent-rainbow|ode|8.3.1
kubernetes-context|Okt|0.1.0
material-icon-theme|PKi|4.33.0
prisma|Pri|5.8.1
quicktype|qui|12.0.46
sqlite-viewer|qwt|0.3.13
vscode-thunder-client|ran|2.17.1
vscode-yaml|red|1.14.0
lit-plugin|run|1.4.3
swift-lang|ssw|1.7.2
graphviz-interactive-preview|tin|0.3.5
lorem-ipsum|Tyr|1.3.1
errorlens|use|3.16.0
vscode-lldb|vad|1.10.0
vscodeintellicode|Vis|1.2.30
vscode-swiftformat|vkn|1.6.7
fig|wit|0.0.7
pretty-ts-errors|Yoa|0.5.3
save-as-root|yy0|1.8.0
markdown-all-in-one|yzh|3.6.2
chat-gpt|zha|1.6.63

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
bg6jg535:30979843
78248357:30976999
dsvsc020:30976470

```

</details>

**Comment by herberthobregon** [comment]
App extensions is the problem

**Comment by domnantas** [comment]
Which extension was the problem? I am experiencing the same issue after VSCode update
