### ISSUE TITLE
Python input on Powershell intergrated terminal does not work 2nd time in debugging mode

### ISSUE THREAD

**Issue by yjs990427** [Microsoft/vscode#20689]
- VSCode Version: 1.9.1
- OS Version: windows 10 Latest

Steps to Reproduce:

1. run a python script and give it a input in debugging mode (powershell integrated terminal) 
2. terminate the script
3. rerun it again
4. I cannot type anything on the terminal... 

I am not sure this is powershell problem or vs code problem but whatsoever....

**Comment by Tyriar** [comment]
> run a python script and give it a input in debugging mode (powershell integrated terminal)

Can you elaborate a little more on this? What are the characteristics of the python script? What is debugging mode in this context?

/cc @daviwil

**Comment by yjs990427** [comment]
I used python extension of donjayamanne.python-0.5.8 
and used debugging mode of when I pressed F5 key

Python code like this one cause the problem:
`print(input())`
First, it works fine, but when I run it **second time**, the integrated terminal (powershell) won't let me type in any input...

Did this explain you a bit more?

**Comment by Tyriar** [comment]
Please file the issue against the extension to see if it's an issue there first.
