### ISSUE TITLE
Git authentication prompts for username when username is in URL

### ISSUE THREAD

**Issue by adamvoss** [Microsoft/vscode#20680]
- VSCode Version: 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519)
- OS Version: Linux Mint 18.1

**Steps to Reproduce:**

1. Have a remote where the url is specified in the url and have an eligible commit to push (VS Code requirement)
    ```bash
    git clone https://vossad01@github.com/Microsoft/vscode.git
    git commit  --allow-empty -am "demonstrate issue"
    ```
1. Open the affected repository in VS Code
1. Try to push the commit

**Actual Behavior:**

You are prompted for the username and password.
![image](https://cloud.githubusercontent.com/assets/965439/23002619/82cd17a6-f3b1-11e6-98d2-e00d9aaeb738.png)

**Expected Behavior:**

You are prompted only for the password.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
