### ISSUE TITLE
VSCode JSON: Problems loading reference

### ISSUE THREAD

**Issue by ExoticGamerrrYT** [microsoft/vscode#206816]
Does this issue occur when all extensions are disabled?: Yes
Error:
![image](https://github.com/microsoft/vscode/assets/111749588/edfaec30-b715-49d8-b038-8910b867c068)

```
Problems loading reference 'https://json.schemastore.org/package': Unable to load schema from 'https://json.schemastore.org/package': Service Unavailable. The server is currently unavailable (overloaded or down).
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Service Unavailable</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=u.(768)
CSS contributions to package.json
```

**Comment by aeschli** [comment]
Caused by Schemastore being down: https://github.com/SchemaStore/schemastore/issues/3620

https://github.com/microsoft/vscode/issues/206792 is about shipping copies of some schemas with VS Code.
