### ISSUE TITLE
Markdown cell using different icons in Go to Symbol and Outline

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#206829]
<img width="932" alt="image" src="https://github.com/microsoft/vscode/assets/876920/335c92be-98f0-4aef-8f49-c68e50e34953">

**Comment by amunger** [comment]
this looks intended:

the goto symbols view is listing symbols, and uses the symbol's icon.
the outline is showing cells, show just has the cell type icon.

**Comment by rebornix** [comment]
> the outline is showing cells, show just has the cell type icon.

The outline is also a presentation of symbols, I wonder if we could just use symbols' icons. cc @Yoyokrazy

**Comment by Yoyokrazy** [comment]
Currently the outline pane within notebooks is only a treeview containing outline entries. Getting header content to clean up the markdown entries wouldn't be too difficult but pulling in the symbols will require more work. Current thoughts are to maybe change code cells to have child entries which are by default collapsed, containing all of the symbols from the given cell. Don't think there's a great way to unify the icon usage unless we are bringing the markdown symbol icon from the symbol view into the outline pane @rebornix
