### ISSUE TITLE
Take charge of the `auto indentation` feature area

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#206891]
This issue is about taking responsibility of the feature area `auto indentation` and start solving the bugs in the feature area. This issue is filed for the purpose of linking it to the iteration plan.

**Comment by aiday-mar** [comment]
I have assigned auto indentation issues to myself, added tests for different languages and started fixing some bugs. This issue will be closed.

**Comment by aiday-mar** [comment]
Issue reopened since it is referenced in the iteration plan.

**Comment by russelldavis** [comment]
So great to see this area getting some love. Would be great if you could look at #182934 and #201421 as part of this.

**Comment by aiday-mar** [comment]
This issue will be closed as it was opened mainly for the purpose of being put into the iteration plan
