### ISSUE TITLE
Cannot search ("Find") in terminal

### ISSUE THREAD

**Issue by adizhol-str** [microsoft/vscode#206894]
Type: <b>Bug</b>

ctrl + F doesn't pop up the search prompt in vscode terminal.
It works in the editor

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) w5-2445 (20 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.65GB (46.36GB free)|
|Process Argv|--crash-reporter-id 5d35bacd-373f-4e38-8ee8-61615870c762|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Xeon(R) w5-2445 (20 x 3095)|
|Memory (System)|31.17GB (28.18GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Xeon(R) w5-2445 (20 x 3095)|
|Memory (System)|31.17GB (28.18GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-wsl|ms-|0.86.0
copilot|Git|1.171.0
copilot-chat|Git|0.13.0
git-graph|mhu|1.30.0
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.3
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.5
cpptools-extension-pack|ms-|1.3.0
opencv-image|Sim|0.1.2
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0

(2 theme extensions excluded)

</details>

**Comment by meganrogge** [comment]
Pls use the command toggle keyboard shortcuts troubleshooting to find out why this doesn't work for you.

**Comment by meganrogge** [comment]
it works for me, so unfortunately I cannot debug further.

**Comment by SeanOMik** [comment]
Find in terminal is also not working for me
VSCode version: 1.86.2
OS: Arch Linux
