### ISSUE TITLE
VSCode drains battery and lags when using Notebooks

### ISSUE THREAD

**Issue by ale-dg** [microsoft/vscode#206865]
Type: <b>Performance Issue</b>

Hi,

Ever since the new update, the battery on my Mac M1 drains mentally fast, even faster than previous versions when doing some heavy machine learning (and I haven't done any since the latest update). 

Also, I have noticed when navigating the extensions (i.e. when looking for new themes or even the ones I have installed), VSCode becomes slow and sometimes prompts to restart it. Also when the hints begin to appear (at least for Python), the system becomes unresponsive for a moment, then the typing begins to lag against the screen and, if lucky, it stays that way or definitely crashes. 

I have tried everything: reinstalling it, disabling all the extensions, minimal installation, etc. No matter what, the same thing happens. See below all the information regarding my system, my workspace, and so on for you to check.

Do you have any advice or any tip on the sleeve apart of keeping my laptop plugged to the wall? :)

Thanks

Best,

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:51.279Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    9	   246	  4960	code main
    0	    82	  4961	   gpu-process
    0	    49	  4962	   utility-network-service
    0	   819	  4964	window [1] (check copy.ipynb — tec_cert_gold)
    0	   115	  4978	shared-process
    0	     0	  5261	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   279	  4992	extensionHost [1]
    0	    49	  5015	     /Users/xxxxx/tec_cert_gold/cert_env/bin/python /Users/xxxxx/.vscode/extensions/ms-python.black-formatter-2024.0.1/bundled/tool/lsp_server.py --stdio
    0	  1196	  5048	     electron-nodejs (bundle.js )
    0	    66	  5134	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/server/dist/node/workerMain --node-ipc --clientProcessId=4992
    0	  1507	  5233	     /Users/xxxxx/tec_cert_gold/cert_env/bin/python -m ipykernel_launcher --f=/Users/xxxxx/Library/Jupyter/runtime/kernel-v2-4992Wu68AdAj3pj5.json
    0	     0	  5239	       electron-nodejs (min.js MathJax.js )
    0	   131	  5243	         electron-nodejs (min.js MathJax.js )
    0	    66	  5244	           gpu-process
    0	    33	  5245	           utility-network-service
    0	   147	  5246	           window
    0	   246	  4999	   window
    0	    66	  5001	fileWatcher [1]
    0	   131	  5003	   window
    0	    66	  5009	ptyHost
    0	     0	  5011	     /bin/zsh
    0	    98	  5254	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (check copy.ipynb — tec_cert_gold)
|    Folder (tec_cert_gold): more than 26077 files
|      File types: hpp(4559) h(3167) dbf(1543) prj(1543) shp(1543) shx(1543)
|                  cpg(1539) csv(853) pdf(816) txt(327)
|      Conf files: cmake(4);
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-dotnet-runtime|ms-|2.0.2
black-formatter|ms-|2024.0.1
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.3
datawrangler|ms-|0.26.0
jupyter|ms-|2024.2.2024022602
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
vscode-icons|vsc|12.7.0

(1 theme extensions excluded)

</details>

**Comment by Delagardi** [comment]
got the same problem. Is there a way to use preious version?

**Comment by na-jakobs** [comment]
Same here, high CPU usage after February 2024 update.
```
$ code --version
[0306/094234.952502:ERROR:codesign_util.cc(108)] SecCodeCheckValidity: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)" (-67062)
1.87.0
019f4d1419fbc8219a181fab7892ebccf7ee29a2
x64
```

**Comment by jocubeit** [comment]
Same here - it's insane how fast it's draining the battery. I've never had my M1 this hot. VS Code is the only app in the battery says is using significant energy. When I close VS Code the behavior stops.

code --version
1.87.1
1e790d77f81672c49be070e04474901747115651
arm64

**Comment by paul-rogers** [comment]
May be related to #206119

**Comment by rebornix** [comment]
If you are running into this issue, can you please help provide info:

* F1/Cmd+shift+P to open Command Palette
* Search for command: "Developer: Show Process Explorer"

and from the process explorer can you check if the Pylance extension is using a lot of CPU/Memory?

Also can you try disable the Pylance extension, reload VS Code and see if it mitigates the problem? Thanks in advance!

**Comment by jocubeit** [comment]
I checked and don't have pylance.

I do have Codium though, which I have disabled. The battery usage is better, and it's not quite as hot, but VS Code still shows as significant in the battery info.

**Comment by ale-dg** [comment]
Hi @rebornix,

Please see this comment in another issue, maybe it points in a direction: https://github.com/microsoft/vscode-jupyter/issues/14459#issuecomment-1986677050

Best

**Comment by punit1108** [comment]
This should not be normal.

![image](https://github.com/microsoft/vscode/assets/7887355/d38c633e-2412-41f1-8314-21529867dca0)

**Comment by DonJayamanne** [comment]
@punit1108 @jocubeit @paul-rogers @na-jakobs @Delagardi 
Most of these issues have been addressed
Please do install the latest version of VS Code insiders and the pre-release versions of the extensions like Python, Jupyter and Pylance.

If you are still running into issues, please
* Disable all extensions except for Jupyter, Python and Notebook Renderers extensions
* If you still run into an issue, please create an issue
* If you do not, then the issue lies with one of the extensions that have been disabled
    *  Please file an issue against that extension
    * Additionally please do mention that here as well

Also, there's another issue that deals specifically with perf issues and large notebooks,
See here https://github.com/microsoft/vscode-jupyter/issues/14459
