### ISSUE TITLE
vscode-eslint break down.

### ISSUE THREAD

**Issue by Chanran** [Microsoft/vscode#20687]
- VSCode Version: v1.9.1
- OS Version: window7

Steps to Reproduce:

1. ctrl+shift+p run eslint createConfig command (already install eslint plugin v1.2.6)
2.
![image](https://cloud.githubusercontent.com/assets/11496220/23005052/0ab1cca6-f435-11e6-83c6-0f2a1869f0f8.png)
3. even in some project which ever used eslint well vscode-eslint break down.
4. 
![image](https://cloud.githubusercontent.com/assets/11496220/23005150/b0ffd616-f435-11e6-80b8-a4862bb3c0f6.png)
5. it just happens without any signs.

**Comment by dbaeumer** [comment]
@Chanran I can't reproduce this. Here is what I see on an empty workspace:

![cast](https://cloud.githubusercontent.com/assets/1931590/23013454/f05bf5c0-f42a-11e6-9d27-f90b00bcd423.gif)

Running the command a second time works for me as well. Any additional information you can provide?

**Comment by Chanran** [comment]
@dbaeumer it just report command not found.strange...
![image](https://cloud.githubusercontent.com/assets/11496220/23017014/9464ea6c-f473-11e6-980f-6776c3fbeb26.png)
![image](https://cloud.githubusercontent.com/assets/11496220/23017048/bdbff33e-f473-11e6-995e-9dc869052985.png)
![image](https://cloud.githubusercontent.com/assets/11496220/23017076/d9903736-f473-11e6-986c-f801e4a12b94.png)

**Comment by Chanran** [comment]
I also found goToDeclaration breakdown too. It seens something happened...0.0

**Comment by Chanran** [comment]
@dbaeumer  I think it is a problem of the newest edition(1.9.1). Here is my proccess to check the problem.
1. uninstall vscode(1.9.1),delete all of file in .vscode(C:\Users/Administor\.vscode).
2. reinstall vscode(1.9.1) and install eslint extension. ctrl+shift+p and type eslint then enter. it just shows error like before.
3. redo step 1
4. install vscode(1.8.1) and install eslint extension.ctrl+shift+p and type eslint then enter. it shows no error.
![image](https://cloud.githubusercontent.com/assets/11496220/23048851/88c39a0c-f4f3-11e6-813c-86826fbe9fc7.png)

**Comment by dbaeumer** [comment]
@Chanran are you still affected by this. I still can't reproduce.

**Comment by Chanran** [comment]
@dbaeumer When I update my os to win10. The bug is fixed...
Now I leave ex company. I can't reproduce...
Now I use vscode on Linux. VS Code is pretty good~

**Comment by dbaeumer** [comment]
@Chanran thanks for getting back. And happy to here that you like VS Code.
