### ISSUE TITLE
[Bug] Replace with characters like 'É'

### ISSUE THREAD

**Issue by Nimzozo** [Microsoft/vscode#2068]
I was using the replacement tool (CTRL + H).
I tried to replace the string 'Ã‰' by 'É' (ALT + 0201) but it was instead replaced by another string (I guess my previous replacement string).

**Comment by alexandrudima** [comment]
@Nimzozo I cannot reproduce. Is there something more to it?

![replace-accent](https://cloud.githubusercontent.com/assets/5047891/12394878/31a955be-be07-11e5-91d2-7ec21a1c23fb.gif)

**Comment by Nimzozo** [comment]
Ok, this is very strange :

I can reproduce the bug easily, but I was curious you couldn't. So I checked and found 2 situations :
- if you copy/paste 'É' in the replacement text box, it works correctly.
- if you type ALT + 0201 in the replacement text box, there comes the bug.

**Comment by alexandrudima** [comment]
@Nimzozo Sorry about me cheating and pasting it in when trying to repro! 

Indeed the find state would not update on "input" events, only on "keydown" events, which is incorrect. 

Thank you for reporting this, it is a great find! :heart:

**Comment by Nimzozo** [comment]
You're welcome. 
I'm not sure to understand your explanation, I will look at the code. :-)
