### ISSUE TITLE
typeScript

### ISSUE THREAD

**Issue by 450611** [Microsoft/vscode#20691]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|aessoft-class-autocomplete|AESSoft|0.1.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-eslint|dbaeumer|1.2.3|
|vscode-html-css|ecmel|0.0.33|
|auto-close-tag|formulahendry|0.3.9|
|auto-rename-tag|formulahendry|0.0.11|
|beautify|HookyQR|0.7.3|
|path-autocomplete|ionutvmi|1.4.1|
|mdhelper|joshbax|0.0.9|
|md-navigate|jrieken|0.0.1|
|vscode-fileheader|mikey|0.0.2|
|vscode-autoprefixer|mrmlnc|2.0.0|
|node-modules-resolve|naumovs|1.0.2|
|vuehelper|oysun|0.0.7|

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Please provide more details.

**Comment by 450611** [comment]
能说中文么= - = ！ 我刚刚在别的地方从新复制了一份typeScript就可以了
