### ISSUE TITLE
Settings sync is not working between Linux and Windows

### ISSUE THREAD

**Issue by aswasn** [microsoft/vscode#206935]
Type: <b>Bug</b>

It seems that settings sync between Linux and macOS is OK, but on Windows the settings wasn't synchronized successfully. I'm not sure if it's an network issue or a hidden bug of vscode. Please check.

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:16.599Z)
OS version: Linux x64 6.5.0-21-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics (12 x 4032)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|13.46GB (9.97GB free)|
|Process Argv|. --crash-reporter-id 4b6504af-0140-401e-9af4-827093337aec|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.2.0
gitlens|eam|14.8.2
todo-tree|Gru|0.0.226
debugpy|ms-|2024.2.0
isort|ms-|2023.10.1
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.3
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
cpptools|ms-|1.19.5
remote-explorer|ms-|0.4.3
vscode-speech|ms-|0.6.0
highlight-words|rsb|0.1.4
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
a89i1917:30973842
bg6jg535:30979843
78248357:30976999
dsvsc020:30976470

```

</details>

**Comment by sandy081** [comment]
Can you please be clear on what data is not syncing? Also please check following log in both machines to get additional insights

- F1 > Open View.. > Settings Sync

**Comment by aswasn** [comment]
It appears to be the network issue, not a bug. Close this issue.
