### ISSUE TITLE
launch-config for console: reuseExternalTerminal

### ISSUE THREAD

**Issue by iAroc** [microsoft/vscode#206964]
Heyya. for coding with the launch.json, there are currently 4 options
"externalTerminal" (opens a new WT.exe on each launch, and it stays open after finish)
"integratedTerminal" (opens a integrated terminal that stays open, and will be "reused" on new launch)
"internalConsole" (doesnt seem todo anything for me?)
"newExternalWindow" (opens a new WT.exe on each launch, and it closes after finish)

i would like to get a option that lets the console work like it does in visual studio. 

When you start a debug session, it opens a externalterminal, as usual. when you now restart (or stop, change code and start again) it wont open a new terminal, but uses the same that there already is

Similar case: https://github.com/microsoft/vscode/issues/18377

**Comment by roblourens** [comment]
Unfortunately I don't really think it's possible for us to support this, since there's no way for us to send new commands to an external terminal
