### ISSUE TITLE
double click on .cpp or .h files open vscode but don't open the file

### ISSUE THREAD

**Issue by theultrazone** [Microsoft/vscode#20697]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.1|

---

Steps to Reproduce:

1. double click on .cpp or .h file open vscode but don't open the file
this happens since last update
if I drag and drop the file into vscode works as intended

**Comment by joaomoreno** [comment]
Can you re-associate VS Code as the default editor for those file types?

**Comment by theultrazone** [comment]
Yes, I tried but the issue persists. The editor opens but don't open the file.
I tried "open with" and the same issue happens.
Actually, doesn't matter the extension, the editor doesn't open any file by double click anymore.

**Comment by joaomoreno** [comment]
Let's move here: #20448
