### ISSUE TITLE
Support embedding images in issue reporter

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#206973]
It would be great to be able to include images when reporting issues -- I think this's the main reason it's not used more often

**Comment by justschen** [comment]
unfortunately due to Github issues API, it's something that isn't possible atm :(

one thing I'm looking into atm tho is allowing users to Preview (instead of Create issues), so it opens the page for you to drag and drop while also having all the included information.

**Comment by ulugbekna** [comment]
what do GH people say about this limitation? do they think there's some workaround or planned fix for this? 

(feel free to close the issue)

**Comment by justschen** [comment]
There hasn't been an update to that API for a while now IIRC, and workarounds are pretty wonky (ie, uploading to s3 or uploading to github first, then referencing that uploaded image, etc). 

it would be nice if this was all supported natively in the reporter, but yeah likely just the preview button could be a good compromise, especially as we roll the issue reporter out in more areas.

**Comment by ulugbekna** [comment]
> uploading to github first, then referencing that uploaded image

This would be my first guess at a workaround

cc @alexr00 since you work with GH API a lot, maybe you know how we could work around this?

**Comment by alexr00** [comment]
I asked the GH folks about this before: https://github.slack.com/archives/C0148EC5FRA/p1686756972471559
