### ISSUE TITLE
Collapse of XML nodes utterly broken

### ISSUE THREAD

**Issue by php4fan** [microsoft/vscode#206904]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.87.0
- OS Version: Manjaro Linux

Steps to Reproduce:

1. I'm editing an XML file and I collapse this node:

![image](https://github.com/microsoft/vscode/assets/13969584/71a70820-c775-4315-8205-72d3faf9b0d0)

The contents of that node go on for many many more lines below the bottom of the window. It ONLY contains `<phrase>` nodes which in turn contain only text, and the whole XML is valid.

When I collapse the node I get this complete nonsense:

![image](https://github.com/microsoft/vscode/assets/13969584/2bfde3ca-2d42-4f39-966a-7a06c9848227)

The node is not completely collapsed. Only a random small portion of it has been hidden. What can be see below the collapsed note is actually part of the contents of the node; the first portion can be seen in the previous screenshot where it was uncollapsed.

What is currently displayed on screen couldn't even possibly be valid XML.

**Additionally**, when I hover over the left side, when the collapse/expand icons show up, several collapse icons show **next to CLOSING tags** instead of opening one, allowing to collapse random nonsensical portions of the XML as opposed to entire nodes. This happens also when the parent node is uncollapsed.

**Comment by aeschli** [comment]
Out-of the box, for XML VSCode uses a folding strategy that is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To go language aware folding, you need to look out for an extension that knows how to parse the XML syntax.

Maybe try https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml ?

**Comment by php4fan** [comment]
Unbelievable.

Having indentation-based folding by default for a language that is not indentation-based is a terrible idea, it does more harm than good. It misleads the user into thinking there's actual folding, and makes them waste their time as it happened to me. 

If you're not giving actual folding out of the box, you should just disable code folding by default when real language-based folding is not available. So at least one will immediately look for an extension rather than waste their time trying to figure out what's wrong. The first thing I'm led to think when I see wrong folding is that there's a syntax error in my code (luckily I was absolutely certain it couldn't possibly be the case for my code so I didn't waste time with that).
