### ISSUE TITLE
Folding incorrect for Transact SQL

### ISSUE THREAD

**Issue by gbritton1** [microsoft/vscode#206901]
Type: <b>Bug</b>

in SQL code like this:

CREATE OR ALTER PROCEDURE Production.AddNewBike 
      @SubcategoryName NVARCHAR(50)
    , @ModelName NVARCHAR(50)
    , @ProductName NVARCHAR(50)
    , @ProductNumber NVARCHAR(25)
    , @Color NVARCHAR(15)
    , @SafetyStockLevel SMALLINT
    , @ReorderPoint SMALLINT
    , @StandardCost MONEY
    , @ListPrice MONEY
    , @DaysToManufacture INT
    , @SellStartDate DATETIME
AS
BEGIN

if I click the collapse arrow next to CREATE PROCEDURE, I expect the whole procedure definition to collapse, since that is the outermost section.  Instead, only the signature collapses.

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (0.49GB free)|
|Process Argv|--crash-reporter-id e47ba1bc-3c8f-49a6-8d37-afc95fe7ad27|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
vsc-python-indent|Kev|1.18.0
presentation-buddy|mau|0.11.0
vscode-docker|ms-|1.29.0
csharp|ms-|2.18.16
vscode-dotnet-runtime|ms-|2.0.2
debugpy|ms-|2024.2.0
isort|ms-|2023.10.1
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.3
jupyter|ms-|2024.1.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.349.0
remote-wsl|ms-|0.86.0
powershell|ms-|2024.0.0
autodocstring|njp|0.6.1
vscode-xml|red|0.26.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
cppperfnew:30979542
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by gbritton1** [comment]
![2024-03-05_11-52-02](https://github.com/microsoft/vscode/assets/12263288/e575133f-d7a6-4fd6-bfda-767a46bb6d2a)

**Comment by aeschli** [comment]
Out-of the box, for SQL VSCode uses a folding strategy  that is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To go language aware folding, you need to look out for an extension that knows how to parse the SQL syntax.
