### ISSUE TITLE
Custom hover behaves badly near the bottom of the screen

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#206999]
1. Have a project with some kind of debugging and make sure the Breakpoints view is near the bottom of the screen
2. Hover over the pencil icon on the second-to-bottom list item. It works 👍 
3. Hover over the bottom list icon. The tooltip seems to appear and disappear very quickly causing the mouse to flicker (the FPS on the gif doesn't capture it very well but you can see that it doesn't render correctly)

![Image](https://github.com/microsoft/vscode/assets/2230985/b896f3b4-74ba-4678-b116-4ce0b35beca9)

**Comment by bpasero** [comment]
cc @benibenj , this might have always been a bug but is probably now more exposed given its a custom hover now.

**Comment by benibenj** [comment]
I haven't made any changes to the computation of where the hover should be placed in relation to the target, so a bug that we have had for a while, but should definitely look into. After testing a bit it seems to me that this only happens for `showPointer: true` (`target: 'element'`).
