### ISSUE TITLE
Incorrect syntax highlighting for Java files

### ISSUE THREAD

**Issue by tzengshinfu** [microsoft/vscode#206975]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0
- OS Version: Windows 10 22H2 19045.4046

Steps to Reproduce:

1. Create a plain text file with the following content:

```Java
public class App {
  public static void main( String[] args ) {
    //                          ↓
    int val1 = new int[]{ 1, 2 }[0];
    //                           ↓
    System.out.println("val1=" + val1);

    int[] arr = new int[]{ 1, 2 };
    //         ↓        ↓
    int val2 = arr[0] + arr[1];
  }
}
```

2. Select the Language Mode to **Java (java)**.

3. You can see that there are several places where the syntax highlighting is incorrect for the down arrows(↓). You can verify this by opening the Command Center and entering the following command: `>Developer: Inspect Editor Tokens and Scopes`
(See images below.)

![1](https://github.com/microsoft/vscode/assets/2170033/ecf15574-5a0c-4570-a3b4-a4f40a7ebb58)
![2](https://github.com/microsoft/vscode/assets/2170033/878e2009-0aac-415f-8402-a8ae21a72bbf)
![3](https://github.com/microsoft/vscode/assets/2170033/6564c962-1f4c-430e-b9fc-3e3bf3d5a08f)

**Comment by alexr00** [comment]
@tzengshinfu those scopes and colors look ok to me. Can you describe how you expect them to look?

**Comment by tzengshinfu** [comment]
> @tzengshinfu those scopes and colors look ok to me. Can you describe how you expect them to look?

Hi, @alexr00:
I think it should be like the following images.
![1](https://github.com/microsoft/vscode/assets/2170033/c62475b9-a35a-4485-b0ea-b1728fc47862)
![2](https://github.com/microsoft/vscode/assets/2170033/4e08148e-0af0-4355-98fc-9e8675d665a4)
![3](https://github.com/microsoft/vscode/assets/2170033/ac4769b4-e1da-4150-afd0-50b6f76616d5)

**Comment by alexr00** [comment]
Thanks for the screen shots! For the fist one, your expectation seems reasonable. For the other 2, those aren't actually variable definitions, so I don't think your expected scope is correct. 

This also seems to be longstanding behavior. I went all the way back to version 1.78 and I see no difference there. I'll open an issue in the repo we get our Java syntax highlighting grammar from.

**Comment by alexr00** [comment]
Upstream issue: https://github.com/redhat-developer/vscode-java/issues/3528

**Comment by tzengshinfu** [comment]
> Thanks for the screen shots! For the fist one, your expectation seems reasonable. For the other 2, those aren't actually variable definitions, so I don't think your expected scope is correct.
> 
> This also seems to be longstanding behavior. I went all the way back to version 1.78 and I see no difference there. I'll open an issue in the repo we get our Java syntax highlighting grammar from.

Hi, @alexr00

Thanks for the reminder, you are right.

In addition, I found something else. I tried to edit the built-in `java.tmLanguage.json` in VSCode and changed the begin and end of `punctuation.bracket.square.java` to other symbols (like exclamation points).

Strangely enough, the scope is working again.

![2](https://github.com/microsoft/vscode/assets/2170033/f1de683f-9ac5-431a-af0c-05660979d8f4)
![3](https://github.com/microsoft/vscode/assets/2170033/a564c0f1-8467-4614-ab24-90ef38bb1480)
