### ISSUE TITLE
default extension not present in vscode severs

### ISSUE THREAD

**Issue by colombod** [microsoft/vscode#206980]
Polyglot Notebook extension uses the grammar file of extensions like `vscode.csharp`, `vscode.powershell` to assemble polyglot grammar and also load dynamically new ones if new kernel languages are added.
This all works well but when connected to vs code server those extensions are not present. This breaks the semantic colouring for users using Polyglot Notebooks in code spaces and dev containers.

Is it possible to access those grammars in other ways?
This is the code used to load additional grammars in the polyglot Notebook extension 
https://github.com/dotnet/interactive/blob/9c6d0f5a8815d9bcb6f0f3bb60f602b5903e2483/src/polyglot-notebooks-vscode-common/src/dynamicGrammarSemanticTokenProvider.ts#L74

**Comment by colombod** [comment]
@brettfo , @jonsequitur @rebornix

**Comment by colombod** [comment]
@alexdima do you have suggestions?

**Comment by alexdima** [comment]
When VS Code is executed in a remote setup (like Remote SSH, WSL, DevContainers, Remote Tunnels or Codespaces), VS Code will spawn two extension hosts, one running on the UI machine and one running on the remote machine. Please see more in our documentation -- https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-kinds. Each extension gets to decide if it will execute on the UI extension host or on the workspace extension host.

The `extensions.all` API will only list extensions that are running on the same extension host. There is an API proposal which goes towards allowing reading extensions across all extension hosts. See https://github.com/microsoft/vscode/issues/145307
