### ISSUE TITLE
Sticky scrolling

### ISSUE THREAD

**Issue by Mubatapasango** [microsoft/vscode#206915]
Type: <b>Performance Issue</b>

I don't like this sticky scroll on top. Its a bad feature because its so disturbing. Im failing to remove it. What is its purpose?

VS Code version: Code 1.87.0 (Universal) (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:56.944Z)
OS version: Darwin x64 19.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.21GB free)|
|Process Argv|--crash-reporter-id f4bdf1ea-44eb-4401-9a6d-2c17d9752f48|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   13	   147	  1036	code main
    0	    66	  1039	   gpu-process
    0	    33	  1040	   utility-network-service
    0	   590	  1044	window [1] (home.php — trafficmonitor)
    0	   106	  1048	shared-process
    0	     0	  1850	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    49	  1049	fileWatcher [1]
    0	   213	  1050	extensionHost [1]
    0	    90	  1507	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=1050
    0	   246	  1508	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/mastertila/.vscode/extensions/angular.ng-template-17.2.2/server --logToConsole --ngProbeLocations /Users/mastertila/.vscode/extensions/angular.ng-template-17.2.2,/Users/mastertila/Documents/sites/trafficmonitor --includeAutomaticOptionalChainCompletions --includeCompletionsWithSnippetText --tsProbeLocations /Users/mastertila/.vscode/extensions/angular.ng-template-17.2.2,/Users/mastertila/Documents/sites/trafficmonitor --node-ipc --clientProcessId=1050
    0	    49	  1740	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=1050
    0	    66	  1843	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (home.php — trafficmonitor)
|    Folder (trafficmonitor): 891 files
|      File types: svg(520) jpg(87) scss(65) png(52) js(40) css(13) html(13)
|                  eot(6) ttf(6) woff(6)
|      Conf files: gulp.js(1) package.json(1);
```

</details>
<details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
vscode-angular2-files|ale|1.6.4
ng-template|Ang|17.2.2
gitignore|cod|0.9.0
angular-schematics|cyr|6.9.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.8.2
prettier-vscode|esb|10.1.0
gc-excelviewer|Gra|4.2.59
rest-client|hum|0.25.1
vscode-edit-csv|jan|0.9.0
Angular2|joh|16.0.1
solidity|Jua|0.0.172
git-graph|mhu|1.30.0
debugpy|ms-|2024.2.0
isort|ms-|2023.10.1
python|ms-|2024.2.1
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
vsliveshare|ms-|1.0.5905
vsliveshare-pack|ms-|0.4.0
html-fmt-vscode|Nik|0.9.3
laravel-blade|one|1.35.1
java|red|1.28.1
laravel-artisan|rya|0.0.31
laravel-artisan|Sof|0.0.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.52.0
vscode-java-debug|vsc|0.56.2
vscode-java-dependency|vsc|0.23.5
vscode-java-pack|vsc|0.25.15
vscode-maven|vsc|0.44.0
vscode-spring-initializr|vsc|0.11.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
dsvsc020:30976470

```

</details>

**Comment by evrsen** [comment]
It helps visualising long and nested structures, if you don't like it you can disable it in ``settings.json``:
```json
"editor.stickyScroll.enabled": false
```

**Comment by gjsjohnmurray** [comment]
Did you see the release notes?

https://code.visualstudio.com/updates/v1_87#_editor-sticky-scroll

**Comment by ErkanSensei** [comment]
Even disabled I'm seeing a weird black line across the top. I'm on an M1 Mac Ventura 13.5

**Comment by evrsen** [comment]
can you share a screenshot?

**Comment by Mubatapasango** [comment]
Thanks, i noticed how i can remove it.

**Comment by aiday-mar** [comment]
Hi thanks for posting this issue. @evrsen shared the setting to disable the feature. This issue will be closed. 

@ErkanSensei could you please include a screenshot of what you are seeing?

**Comment by ErkanSensei** [comment]
Sorry for the late reply. @aiday-mar @evrsen I believe it's the shadow on the tab bar acting up. It seems to sometimes break up and doesn't look like a shadow but just a flat black line. I can't reproduce at the moment as it's intermittent, but this is the closest I could get

<img width="1177" alt="Screenshot 2024-03-11 at 12 24 15 AM" src="https://github.com/microsoft/vscode/assets/17013914/32a7553b-14ba-4675-a2f7-2c69cd6f8931">

**Comment by aiday-mar** [comment]
Ah. I see this shadow also when sticky scroll is disabled?

https://github.com/microsoft/vscode/assets/61460952/4d0569e0-58b8-41c7-bf45-c12f5e67cffb

**Comment by ErkanSensei** [comment]
Yes it is disabled for me and that is what's showing up

**Comment by evrsen** [comment]
is that not normal?

**Comment by ErkanSensei** [comment]
Yes I know the bar is, it just looked a bit like a broken CRT? (Not sure how best to explain what it looked like). If it happens again I will update here with reproducible steps
