### ISSUE TITLE
No padding between included info and create on github button

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#206981]
![Image](https://github.com/microsoft/vscode/assets/2193314/fa44c3a4-9ab6-420a-aeef-cfedf100415b)

**Comment by justschen** [comment]
is this in OSS or in insiders?

**Comment by Tyriar** [comment]
This was oss

**Comment by justschen** [comment]
yep, this is a known issue in OSS with the css bundling. it ends up fine in Insiders and stable, but unsure why this has been the case for a while now. same as https://github.com/microsoft/vscode/issues/206982 i believe

**Comment by Tyriar** [comment]
They still happen in insiders, just the button width isn't the same for some reason (you could inspect the element in devtools to diff the styles):

![image](https://github.com/microsoft/vscode/assets/2193314/f950ba0f-8646-4d0c-9cc9-c46038261bc6)
