### ISSUE TITLE
Missing Chat Participant Icons in GitHub Copilot Chat Responses

### ISSUE THREAD

**Issue by BrunoRDS** [microsoft/vscode#206919]
Does this issue occur when all extensions are disabled?: **Yes**

### VS Code Version: & OS Version: 

Version: 1.88.0-insider (user setup)
Commit: d73fa8b14a6c873958d00a7d7ad13fcb540a052c
Date: 2024-03-05T05:47:29.930Z
Electron: 28.2.5
ElectronBuildId: 27336930
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

### Steps to Reproduce:

1. Clone [Chat-Sample
](https://github.com/microsoft/vscode-extension-samples/tree/main/chat-sample)
2. Run Chat-Sample in Extension Development Host VSCode instance
3. In the GitHub Copilot Chat send a message to the @cat participant

### Summary

Recently noticed that the participant icon is no longer showing next to the GitHub Copilot icon in the response header.

It used to look like: 
![image](https://github.com/microsoft/vscode/assets/44142527/3b424508-1600-4bfc-ba9a-bf63930d9f02)

and now it looks like: 
![image](https://github.com/microsoft/vscode/assets/44142527/47b74695-be88-4455-a90a-107fab21b037)

GitHub Copilot Chat Version: v0.14.2024030501 (pre-release)

@isidorn FYI

**Comment by roblourens** [comment]
Please make sure you have the latest versions of VS Code Insiders and the Copilot Chat extension installed

**Comment by BrunoRDS** [comment]
VS Code version info: 

Version: 1.88.0-insider (user setup)
Commit: 6c19c003574b02afc604c0c1c471b1441b33a3d3
Date: 2024-03-08T08:14:03.524Z
Electron: 28.2.5
ElectronBuildId: 27336930
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

GitHub Copilot version: v1.172.0 (release)

GitHub Copilot Chat version: v0.14.2024030801 (pre-release)

Still seeing this issue on the lates pre-release: 

![image](https://github.com/microsoft/vscode/assets/44142527/4464f4e8-4ff4-4f3a-a245-dd42e8128889)

**Comment by BrunoRDS** [comment]
@roblourens Still seeing this issue on latest version. 

Version: 1.88.0-insider (user setup)
Commit: b356b209a5a41743b45f25d569a7afb733d347a9
Date: 2024-03-18T16:36:07.814Z

GitHub Copilot Chat Extension v0.14.2024031802 (pre-release)

**Comment by roblourens** [comment]
You're right, fixed in https://github.com/microsoft/vscode/pull/207652
