### ISSUE TITLE
Notebook diff editor: Notebook becomes dirty without any apparent changes

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#206966]
Just running a Python notebook will mark it as dirty. The notebook diff editor could tell me why, but it doesn't:

![Image](https://github.com/microsoft/vscode/assets/22350/d5e5f26b-e700-43e7-8399-016568d7dadb)

**Comment by DonJayamanne** [comment]
Most likely the execution count that causes notebooks to be dirty.
I too found that we do not display the execution count and the like in the diff view.

**Comment by DonJayamanne** [comment]
**Solution:**
* We can try to include execution number in metadata
