### ISSUE TITLE
Sync extension user state keys to another machine

### ISSUE THREAD

**Issue by lulunac27a** [microsoft/vscode#206923]
I want to sync extension user state keys to another machine, like other computer/device using `ExtensionContext.globalState` with my data keys and values synced to another machine in a global state, so I can use the saved extension user state keys in another machine. When I use Settings Sync, it shows the UI State, not the extension user state keys.

**Comment by sandy081** [comment]
Extension UI state is synced along with extensions. There is no special option to enable it.

**Comment by lulunac27a** [comment]
I want to save my user data like my level and XP (experience points) from the extension from the Marketplace, so I can use the saved user data like my level and XP in my other machine.
