### ISSUE TITLE
Code Floating at the Top of Visual Studio Code

### ISSUE THREAD

**Issue by flyapex** [microsoft/vscode#206903]
Type: <b>Bug</b>

When I open the code in Visual Studio Code, I encounter an issue where some of the code remains fixed at the top of the navigation bar, impeding smooth scrolling functionality.

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.42GB (13.76GB free)|
|Process Argv|--crash-reporter-id 1d277d2e-bac7-43e4-bd03-886d1859e2ed|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
run|Alb|2.0.1
stackoverflow-search|Ale|1.2.0
tsl-problem-matcher|amo|0.6.2
tailwind-docs|aus|2.1.0
emojisense|bie|0.10.0
vscode-tailwindcss|bra|0.10.5
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.5
dart-code|Dar|3.84.0
flutter|Dar|3.84.0
githistory|don|0.6.20
vsc-material-theme-icons|equ|3.5.0
kotlin-formatter|esa|0.0.6
prettier-vscode|esb|10.1.0
vscode-open-in-github|fab|2.1.1
vscode-mysql|for|0.5.0
kotlin|fwc|0.2.34
dummytextgenerator|gur|1.0.1
codesnap-plus|hui|1.4.1
npm|ide|1.7.4
vscode-git-add-and-commit|iva|2.1.1
vscode-npm-scripts|jia|0.2.4
vscode-gutter-preview|kis|0.30.0
graphql-for-vscode|kum|1.15.3
vscode-lottie|lot|1.0.5
Kotlin|mat|1.7.1
git-graph|mhu|1.30.0
xml-format|mik|1.1.3
dotenv|mik|1.0.1
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
remote-wsl|ms-|0.86.0
vscode-typescript-next|ms-|5.5.20240304
vsliveshare|ms-|1.0.5905
vscode-react-native|msj|1.12.3
material-icon-theme|PKi|4.34.0
vscode-react-refactor|pla|1.1.3
remove-comments|pli|1.2.2
itk-snippets|ram|0.2.2
vscode-thunder-client|ran|2.19.2
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
sql-snippets|sad|0.0.4
swdc-vscode|sof|2.7.6
vscode-styled-components|sty|1.7.8
vscode-open-in-github|sys|1.18.0
highlight-matching-tag|vin|0.11.0
adb-interface-vscode|vin|0.22.4
vscode-gradle|vsc|3.13.5
vscode-icons|vsc|12.7.0
quokka-vscode|Wal|1.0.628
vscode-import-cost|wix|3.3.0
eno|Wsc|2.3.53
current-file-path|yos|4.0.0
snippetmaker|zii|0.0.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
cppperfcontrol:30979541
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by gjsjohnmurray** [comment]
Probably the recent feature called Sticky Scroll. Please check the documentation, settings and menus (including right-click) for info and options for disabling it.

**Comment by aiday-mar** [comment]
Hi @flyapex, as @gjsjohnmurray mentioned, the feature can be disabled with the following setting `editor.stickyScroll.scrollWithEditor`.

Thanks @gjsjohnmurray for the continuous support on the issues. 

This issue will be closed.
