### ISSUE TITLE
External Terminal Launch Error 2147942402 (0x80070002) in Visual Studio Code 1.87.0 When Compiling C++ with MSVC

### ISSUE THREAD

**Issue by romemart** [microsoft/vscode#206925]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.87.0
- OS Version: Windows_NT x64 10.0.19045

![image](https://github.com/microsoft/vscode/assets/44727455/40229161-a292-4b90-b7f1-854c46e39bf4)

Steps to Reproduce:

1. I open my VScode and edit new CPP file to print a message
```cpp
#include <iostream>

int main(int argc, char const *argv[])
{
    std::cout << "Hello VScode\n";
    return 0;
}
```
2. I generate tasks.json and launch.json
tasks.json
```json
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: cl.exe build active file",
            "command": "cl.exe",
            "args": [
                "/Zi",
                "/EHsc",
                "/nologo",
                "/Fe${fileDirname}\\${fileBasenameNoExtension}.exe",
                "${file}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$msCompile"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```
launch.json
```json
{
    "configurations": [
        {
            "name": "C/C++: cl.exe build and debug active file",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "console": "integratedTerminal",
            "preLaunchTask": "C/C++: cl.exe build active file"
        }
    ],
    "version": "2.0.0"
}
```
I get the message according to the code on the integrated terminal
![image](https://github.com/microsoft/vscode/assets/44727455/f9a10cda-cdbb-48e2-9bf3-cf79e0c85192)

3. Changing the launch.json to output the message through the external terminal throws the following error

[error 2147942402 (0x80070002) when launching `Romero\AppData\Local\Microsoft\WindowsApps\wt.exe -d . C:\WINDOWS\System32\cmd.exe /c c:\Users\Martin "Romero\.vscode\extensions\ms-vscode.cpptools-1.19.5-win32-x64\debugAdapters\vsdbg\bin\VsDebugConsole.exe \\.\pipe\Microsoft-VisualStudio-Debug-Console-{3BB14B18-AA50-4423-9663-1249A642B177} Local\{3BB14B18-AA50-4423-9663-1249A642B177} /AutoExit & pause"']

![image](https://github.com/microsoft/vscode/assets/44727455/e33ac367-0492-46fc-a4d8-cdfb9a85f7ab)

**Comment by roblourens** [comment]
Please file this on the repo for the C++ extension, thanks
