### ISSUE TITLE
In Windows Alt key doesn't allow menu items to be activated, e.g. Alt-F+S normally saves

### ISSUE THREAD

**Issue by toddabel** [Microsoft/vscode#20696]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.2|
|json-tools|eriklynd|1.0.2|
|vscode-auto-open-markdown-preview|hnw|0.0.3|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|vs-keybindings|ms-vscode|0.1.3|
|azurerm-vscode-tools|msazurermtools|0.3.4|
|Spell|seanmcbreen|0.9.1|

---

Steps to Reproduce:

1. Press the 'Alt' Key, the 'F' is underlined, but the menu is not displayed.
2.

**Comment by Bill-Stewart** [comment]
I think you mean to say "pressing the <kbd>Alt</kbd> key does not move keyboard focus to the menu" ?

**Comment by bpasero** [comment]
Is this https://github.com/Microsoft/vscode/issues/10525 ?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5556
