### ISSUE TITLE
Visual Studio Code can not identify if i do not use @ with Component decorator

### ISSUE THREAD

**Issue by sahdev0** [Microsoft/vscode#20695]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7600
- @ issue in Comopnent decorator :

I was created a component for my application and unfortunately i forgot to mention @ with my Component decorator  

```
import {Component} from '@angular/core';

Component({
    selector:'comments',
    templateUrl:'./comments.component.html',
    styleUrls:['comments.component.css']
})
```

when i run my code error was something weird that i could not figure out what should be the solution after 1 hours of effort i had figure out that error was because of @ with Component decorator did not mentioned see above code. If this is Editor Problem please fix this in future update of visual studio code.

**Comment by kumarharsh** [comment]
the issue is very confusing... can you try clarifying what exactly the problem is? Is it `syntax highlighting`?

**Comment by sahdev0** [comment]
Yes this is syntax related issue. Editor should prompt me if i don't use @ with Component decorator like
```
@Component({
})
```

**Comment by kumarharsh** [comment]
I don't see what's wrong?

![image](https://cloud.githubusercontent.com/assets/760112/23015237/0a12d876-f458-11e6-8e02-0f50a27157a6.png)

vs 

![image](https://cloud.githubusercontent.com/assets/760112/23015245/110462b2-f458-11e6-8f39-1f0ba372630d.png)

The syntax highlight is working, and it different in both cases.
VSCode can't know if you intend to use `Component` or `@Component`

**Comment by mjbvz** [comment]
@sahdev0, in general we cannot know when you intended to use a decorator this way vs a regular function call. This is as-designed
