### ISSUE TITLE
Python Environment in anaconda not loaded Caused by Conda is not Found on Gentoo Linux

### ISSUE THREAD

**Issue by geometrylearner** [microsoft/vscode#206977]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.87.0
- OS Version: Gentoo Linux x86_64
- Conda Version : 22.9.0

Steps to Reproduce:

1.  Installed the latest version of vscode by unpack the `code-stable-x64-1709077346.tar.gz` at the path to `code` on Gentoo Linux. The anaconda3 works well all along and VScode keeps most of its functions.
2.  Uninstalled isort and python and python debugging. Reinstall the Python Extension in VScode by latest version then all the conda environment of python can not be found when I open a python script.
3.  Manually specify the conda Python Environment by `Enter interpreter path` and navigate to the specific python interpreter, when select the python path,  VScode reported "An Invalid Python interpreter is selected, please try changing it to enable features such as IntelliSense, Linting,  and debugging. See output for more details regarding why the interpreter is invalid". The output is simply as "/home/user/anaconda3/envs/gemini/bin/python identified as Conda environment even though Conda is not found" and "~/anaconda3/envs/gemini/bin/python3 -I ~/.vscode/extensions/ms-python.python-2024.2.1/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2024.2.1/pythonFiles/interpreterInfo.py".

**Comment by roblourens** [comment]
Please file this on the Python extension repo, thanks
