### ISSUE TITLE
Fish shell script syntax highlighting gets broken on function 

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#206952]
screenshot: 

<img width="675" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/21ae8b7a-5e76-4cb6-9233-c952b7f04f20">

source: 

```sh
alias gswr='git switch -r'
alias gsws='git switch -s'

function sim
    if test $argv[1] = '--help'
        npm run p -- --help
    else
        make ls; and npm run p -- $argv
    end
end

set -x PATH /Users/ulugbekna/.dotnet $PATH
```

Version: 1.88.0-insider
Commit: d73fa8b14a6c873958d00a7d7ad13fcb540a052c
Date: 2024-03-05T06:00:23.745Z
Electron: 28.2.5
ElectronBuildId: 27336930
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.3.0

**Comment by alexr00** [comment]
Opened https://github.com/jeff-hykin/better-shell-syntax/issues/78, let's see what happens there. Maybe we should remove Fish from the shellscript extension.

**Comment by alexr00** [comment]
Based on https://github.com/jeff-hykin/better-shell-syntax/issues/78, closing as upstream.
