### ISSUE TITLE
Cannot pass "-c" option followed by argument command to zsh in integrated terminal

### ISSUE THREAD

**Issue by akrueger** [Microsoft/vscode#20699]
- VSCode Version: 1.9.1
- OS Version: macOS 10.12.3 (16D32)

Steps to Reproduce:

1. Set `"terminal.integrated.shellArgs.osx": ["-c cal"]`
2. Open integrated terminal

I'm trying to open the integrated terminal shell with a command. I'd like to do this to set an environment variable that will adjust my powerline fonts. For instance normally I can start a shell like this:
<img width="666" alt="screen shot 2017-02-16 at 01 09 05" src="https://cloud.githubusercontent.com/assets/1644520/23011106/926a778e-f3e4-11e6-8128-97ca47c4ef7c.png">

When I try to use this, the integrated terminal cannot execute the shell:
<img width="1004" alt="screen shot 2017-02-16 at 01 11 31" src="https://cloud.githubusercontent.com/assets/1644520/23011149/e42f67f0-f3e4-11e6-87bb-9484d393f1bf.png">

**Comment by joaomoreno** [comment]
What I do is I create a shell script in `~/bin/shell` and in there I call `zsh` with the right arguments. Then I configure the shell to be that script.

**Comment by akrueger** [comment]
@joaomoreno Interesting, do you have a small example you could post? Thanks

**Comment by Tyriar** [comment]
@akrueger those are 2 arguments, this should work:

```js
"terminal.integrated.shellArgs.osx": ["-c", "cal"]
```

**Comment by akrueger** [comment]
@Tyriar Thanks! I'll investigate using that to get where I need to be with powerline toggling.
