### ISSUE TITLE
SmartSnippetInserter empty text timeout

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#207009]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=260949
Changes: https://github.com/Microsoft/vscode/compare/b4e63ad...cdc9903

```
  1) SmartSnippetInserter
       empty text:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (vs/workbench/contrib/preferences/test/common/smartSnippetInserter.test)
  	at process.processImmediate (node:internal/timers:476:21)
```

**Comment by alexdima** [comment]
The build machine must have been on life support. Those tests have no async component to them and it's not possible that they take 2s unless the build machine has real CPU problems.
