### ISSUE TITLE
Debugger does not start to run a program/tests after updating to 1.87 VSCode

### ISSUE THREAD

**Issue by KhyzhniakAlex** [microsoft/vscode#207081]
Type: <b>Bug</b>

- Set up launch.json file. Field "program" links to a bin file of a 3rd-party program (Mocha)
- Run program/tests as usual on "Run and Debug" window
- Debugger does not start

VS Code version: Code 1.87.0 (Universal) (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:56.944Z)
OS version: Darwin x64 21.6.0

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/206524#issuecomment-1971707581
