### ISSUE TITLE
User Experience: Avoid notifying about available extension updates when the extension is disabled

### ISSUE THREAD

**Issue by babakfp** [microsoft/vscode#207017]
If an extension is disabled and there is a new version of it available, don't move it to the top of the extensions list, and don't add the number (how many updates are available) to the extensions panel tab.
If an extension is disabled, that means I don't care about it at all, I'm not using it.

**Comment by sandy081** [comment]
When an extension is disabled, you are required to reload the window for the extension to be stopped. Hence there is an action indicating that which is important.
