### ISSUE TITLE
Unable to spawn Julia executable while debugging an extension in VS Code insiders, but works in VS Code stable

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#207059]
Does this issue occur when all extensions are disabled?: Yes/No

- Version: 1.88.0-insider
Commit: cc1f5e3acfad98ed519befc1ebfd199777d135f4
Date: 2024-03-07T05:50:38.946Z
Electron: 28.2.5
ElectronBuildId: 27336930
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.3.0

**Steps to Reproduce:**
I'm working on the Julia extension, and found that while debugging the extension in VS Code insiders I'm unable to spawn the Julia executable,
However the exact same code works when debugging the same extension in VS Code stable (i.e. spawning julia executable works).

Here's the error message in the console window
```
 ERR spawn /Users/donjayamanne/.juliaup/bin/julia ENOENT: Error: spawn /Users/donjayamanne/.juliaup/bin/julia ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
I feel this is a regression in VS Code insiders as it works in Stable.

Not sure where the problem is, i tried changing the arguments and that does not make any difference whatsoever,
Seems to be related to debugging.

**Note**
* The executable is valid, 
* Spawning executable works in Stable
* Spawning executable works in Insiders when not debugging

@connor4312 @deepak1556 /cc not sure where the problem lies.

**Comment by connor4312** [comment]
Can you share the output of `ls -l /Users/donjayamanne/.juliaup/bin/julia` as well as verifying whether any `cwd` you're using when spawning the binary exists?

**Comment by DonJayamanne** [comment]
> ifying whether any cwd you're using when spawning the binary exists?

You're right that doesn't exist, wonder why it works in stable.
Anyways, closing as the cwd is invalid.
thanks
