### ISSUE TITLE
Clicking refactor lightbulb only shows "Surround with" options in Javascript

### ISSUE THREAD

**Issue by fbazbo** [microsoft/vscode#207090]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0
- OS Version: macOS Sonoma 14.3 

Steps to Reproduce:

1. Write some js code like:
```
function testFunc(somearg) {
	if (somearg) {
		var test = 1 + somearg;
	}
	return;
}
```
2. Highlight the if block and click the lightbulb, you only see "surround with" refactor options
<img width="309" alt="Screenshot 2024-03-07 at 8 07 43 AM" src="https://github.com/microsoft/vscode/assets/221240/0ad6f3ce-29c2-42da-8b9c-1a36a2836e6b">

**Comment by mjbvz** [comment]
What refactoring do you expect?

**Comment by fbazbo** [comment]
extract to method... I only get surround with even when trying to rename a variable

**Comment by fbazbo** [comment]
I can select just the argument in the function declaration and it gives no options, it should give at least rename. If I select the same "somearg" in the body, I only get "Surround with". Doesn't matter if I click lightbulb, right-click>refactor or do the hotkey. I only have one disabled extension, so not sure what could be interfering.

**Comment by fbazbo** [comment]
I'm not getting the quick Fix either, is that a later version or is some option not enabled?

**Comment by mjbvz** [comment]
So you only select `somearg`? We don't show extract method if you only have a single identifier selected as it's quite noisy

**Comment by fbazbo** [comment]
somearg alone should show rename as a refactor... anyway the extract doesn't appear for this block:
	if (somearg) {
		var test = 1 + somearg;
	}
as seen in screenshot above. 

I wonder if the javascript handler isn't loading properly, since I get other errors I don't see in vscode when I move the code to a different IDE

**Comment by mjbvz** [comment]
You can use rename command (f2)

This sounds like a configuration issue/usage question. Try making sure the build JS/TS extension is enabled and that the file's language mode is  js or ts too

**Comment by fbazbo** [comment]
Yeah, definitely something odd...Don't see rename anywhere (note extensions and language).  Fn F2 does nothing. Rename was just another example that something that used to work (I believe, though I do use other languages and maybe it was there). Extract definitely worked before though. Here's a screenshot of full window:
![Screenshot 2024-03-11 at 3 18 15 PM](https://github.com/microsoft/vscode/assets/221240/4c36e67b-cb75-4eca-9096-aa6aa167ab97)
