### ISSUE TITLE
SecCodeCheckValidity: Error Domain=NSOSStatusErrorDomain Code=-67062

### ISSUE THREAD

**Issue by lowang-bh** [microsoft/vscode#207039]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.87.0
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:56.944Z (1 wk ago)
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin x64 19.6.0
- OS Version: 
Catalina 10.15.7 (19H2026)

Steps to Reproduce:

1.  upgrade vscode as it preempted
2. `code .` to open a workdir

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/204085
