### ISSUE TITLE
Interface Overlapping Issue

### ISSUE THREAD

**Issue by WongChuenKhoon** [microsoft/vscode#207086]
Type: <b>Bug</b>

The interface on my vs code is overlapping.

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.35GB (9.96GB free)|
|Process Argv|--crash-reporter-id 33a2f464-04cb-4845-a098-dcfbc7b5dceb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
vscode-intelephense-client|bme|1.10.2
code-runner|for|0.12.1
classroom|git|0.0.4
vscode-pull-request-github|Git|0.82.0
live-sass|gle|6.1.2
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.3
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.6
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.13
vsliveshare|ms-|1.0.5918
java|red|1.28.1
LiveServer|rit|5.7.9
pdf|tom|1.2.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.56.2
vscode-java-dependency|vsc|0.23.5
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0
php-debug|xde|1.34.0
php-pack|xde|1.0.3
php-intellisense|zob|1.3.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
8f97e687:30977000
dsvsc020:30976470

```

</details>

**Comment by WongChuenKhoon** [comment]
![image](https://github.com/microsoft/vscode/assets/149517618/14fa9261-1709-4890-a580-603865928af3)

**Comment by gjsjohnmurray** [comment]
This is the Sticky Scroll feature. Please check the Release Notes.

**Comment by WongChuenKhoon** [comment]
Thank you very much, it is fixed

**Comment by gjsjohnmurray** [comment]
Please close your issue.
