### ISSUE TITLE
Styling of language features hover is wrong in latest

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#207080]
v1.87

![image](https://github.com/microsoft/vscode/assets/2193314/532edf50-34ad-49bb-b0e6-d0f21999ac83)

Latest 1.88-insiders

![image](https://github.com/microsoft/vscode/assets/2193314/2c9e609f-2090-4538-b738-f252fc38b4cc)

**Comment by benibenj** [comment]
After discussing with @bpasero we came to the conclusion that using the `compact` version of the hover makes sense for most areas (maybe even everywhere?). So we adopted it in the status bar as well. I fixed the padding issue today in the language and zoom hovers.
