### ISSUE TITLE
The JS/TS language service immediately crashed 5 times. (Again)

### ISSUE THREAD

**Issue by Sergioramasano** [microsoft/vscode#207047]
- VS Code Version: Version: 1.87.0 (Universal)
- OS Version: macOS Sonoma 14.2.1 (23C71)

Steps to Reproduce:

1. Open VScode, start vite vue3 App.
2. See error The JS/TS language service immediately crashed 5 times. 
3. All Vue TS Vscode features don't work. (I use TypeScript Vue Plugin (Volar) extension , tried Vue official extension)
4. Also tried to change ts version (but only one option Use VScode Version)

**Comment by OdapX** [comment]
+1

**Comment by mjbvz** [comment]
If this only happens when using the Vue plugin/extension, it's caused by them. Please file an issue against them

**Comment by johnsoncodehk** [comment]
See https://github.com/microsoft/vscode/issues/206946#issuecomment-1985672004
