### ISSUE TITLE
I cant install any Extension (error:of central directory record signature not found)

### ISSUE THREAD

**Issue by nomli** [Microsoft/vscode#20708]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601

**messageService.ts:126**  of central directory record signature not found: Error: end of central directory record signature not found,    at c:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\yauzl\index.js:98:14,    at c:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\yauzl\index.js:342:5,    at c:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\fd-slicer\index.js:32:7,    at FSReqWrap.wrapper [as oncomplete] (fs.js:681:17)e.doShow @ messageService.ts:126

**Comment by joaomoreno** [comment]
You are behind a proxy, can you provide some help in #18103 ?

**Comment by Meligy** [comment]
I'm getting the same error

end of central directory record signature not found

On version:

```
Visual Studio Code - Insiders

Version 1.10.0-insider
Commit 64801727521592cf5fe64fd911b1efe41b1ea732
Date 2017-02-20T07:13:27.765Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

Even when installing from VSIX.

Extensions are upgrading normally, but if I install https://marketplace.visualstudio.com/items?itemName=AureliaEffect.aurelia from market, or download .vsix and try to install, I get the same message.

This is on Windows 8.1, with proxy set to Fiddler, which is allowing extension manager to do remote searches and download extension updates without any problem.

**Comment by Meligy** [comment]
I have the same extension on another machine (Mac), and it installs just fine, so, I'm assuming it's not extension specific.
