### ISSUE TITLE
Select for compare on file right-click menu

### ISSUE THREAD

**Issue by joshbcondie** [microsoft/vscode#207098]
Type: <b>Feature Request</b>

In the file explorer, you can right-click on a file and select for compare, and then right-click on another file to compare with selected. It would be really nice if instead of having to go to the file explorer, you could just right-click on the file name in the editor and do the same actions, or if there were a keyboard shortcut.

VS Code version: Code 1.87.0 (Universal) (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:56.944Z)
OS version: Darwin arm64 21.6.0
Modes:
Remote OS version: Linux x64 6.2.0-1015-aws

**Comment by msftrncs** [comment]
You can create your own keyboard shortcuts for this in the keyboard short-cut editor, it will even display the short-cut in the menu once you have assigned it.

The items are `selectForCompare` and `compareFiles`.   I am not sure what 'compareSelected` does.

**Comment by alexandruavadanii** [comment]
Command palette (`Ctrl`+`Shift`+`P`) + `File: Compare Active File With...`?
You can also bind that to a shortcut of your own.

**Comment by joshbcondie** [comment]
Great, thanks!
