### ISSUE TITLE
Failed to launch external program msbuild

### ISSUE THREAD

**Issue by sursu** [Microsoft/vscode#20704]
I followed the steps of Ankit Asthana from this video:
https://www.youtube.com/watch?v=B0xTgyCwsAo
with a simple "Hello World" example.

However, when I ">Run Build Task", I get an error:
"Failed to launch external program msbuild /property:GenerateFullPaths=true.
spawn msbuild ENOENT"
---
Tried to add MSBuild.exe (from VS 2017) to my PATH and the problem persists.

Any suggestions?

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.1|

---

Steps to Reproduce:

1.
2.

**Comment by dbaeumer** [comment]
@sursu can you please provide a git URL which contains your example. This helps tracking this down.

**Comment by sursu** [comment]
Hi, Dirk 
Here is my example: https://github.com/sursu/vscode_test

**Comment by sursu** [comment]
Have you managed to replicate my error?

**Comment by dbaeumer** [comment]
@sursu when trying with VS Code without any extension I get:

```
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```

with the cloned project https://github.com/sursu/vscode_test

Could this be a problem of the cpptools extension ?

**Comment by sursu** [comment]
With and without the extension, after I have added to the path the MSBuild from Visual Studio 2017, I get indeed:

`MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.`

**Comment by dbaeumer** [comment]
Closing then.

**Comment by sursu** [comment]
:) You may close it, but how do I deal with this problem?

**Comment by dbaeumer** [comment]
I am not an msbuild expert but I think you either need to create a solution file or pass some other information. If you want to compile a single file then you can always call the compiler directly

**Comment by sursu** [comment]
Is it possible to call the compiler directly from VS Code? That is what I thought I'm doing with ">Run Build Task"...

**Comment by dbaeumer** [comment]
Yes, but you need to list the compiler you want to call as a command in the tasks.json. You might want to have a look here for some examples: http://code.visualstudio.com/docs/editor/tasks

**Comment by doubleyewdee** [comment]
Hold up, does VS Code actually need MSBuild in the path? Or has it simply not been updated to find MSBuild in its new location for VS2017? If the latter this is a bug. If the former this is merely a usability bug (it should really look for MSBuild on Windows in reasonable, known locations...)

**Comment by dbaeumer** [comment]
VS Code has not knowledge about msbuild location under Windows. All commands listed in tasks.json need to either be on the path or need to be references absolute.

**Comment by sursu** [comment]
I have now reinstalled VS Code.
The problem persists. 
`MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.`
I am curious if anyone in this world is able to build C++ applications from VS Code with msbuild and, if yes, how he/she/it does that.

```
I suspect that my problem has to do with the "includePath" from the c_cpp_properties.json file:
{
            "name": "Win32",
            "includePath": [
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
```
My Visual Studio 14.0 is essentially non-existent (the folder has some files though).
When I change the path to the msbuild of Visual Studio 2017 no success is recorded.

**Comment by dunkan50** [comment]
try the following link its not flawless but it helps https://github.com/dunkan50/vscodecpp

**Comment by ghiscoding** [comment]
@sursu the last error you received was valid, you did not provide a solution file (`.sln`) nor a project file (`.csproj`). For example, I got my project (WebUI) working with the latest `2.0.0` tasks configuration:

```javascript
{
  "version": "2.0.0",
  "tasks": [
    {
      "taskName": "Build - Debug",
      "command": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\15.0\\Bin\\amd64\\MSBuild.exe",
      "args": [
        "${workspaceRoot}/WebUI.csproj",
        "/t:Rebuild",
        "/p:Configuration=Debug;AutoParameterizationWebConfigConnectionStrings=False"
      ],
      "problemMatcher": []
    }
  ]
}
```

In my case `msbuild` was not in my Windows path, so I provided it in the task.
