### ISSUE TITLE
Passing the VSCode display language to webview

### ISSUE THREAD

**Issue by amitsgaba** [microsoft/vscode#207071]
We can detect the vscode display language using vscode.env.language. When we try to load any page in vscode webview it is still displaying the page in english even though my vscode.env.language is French.

How can we have this vscode display language passed to webview so that webview browser considers the display language and renders page in french language.

Webview is opening in iframe. Basically i want to set the webview browser language to vscode display language.

**Comment by mjbvz** [comment]
You can either pass along the display language in a message or use it when generating your webview's html

**Comment by amitsgaba** [comment]
@mjbvz Can you share some example for the same both approaches?
