### ISSUE TITLE
Vscode font get messed up if i install wine

### ISSUE THREAD

**Issue by firozmi** [Microsoft/vscode#20709]
- VSCode Version:1.9.1
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1.Install vscode
2.Install wine using command sudo apt-get install wine

When wine is installed, the vscode fonts get messed up. The font size gets smaller and ugly. If i zoom(using 'ctr' + '+'), the font gets too big and still stay ugly.

When i uninstall wine, and run 'sudo apt autoremove', everything is back to normal again.

**Comment by joaomoreno** [comment]
Can you provide a screenshot?

**Comment by giyyapan** [comment]
![image](https://user-images.githubusercontent.com/3479453/29306228-1bbd3bc0-81cf-11e7-8c06-8414880fcc32.png)
I have faced the same issue. and it can be represent on three different machine in my office (all of them are using ubuntu 16.04)

**Comment by giyyapan** [comment]
And I was able to get rid of this by adding a fontFamily config in settings file
```
"editor.fontFamily": "'Mono"
```
