### ISSUE TITLE
Make url clickable inside terminal

### ISSUE THREAD

**Issue by yuyuki** [Microsoft/vscode#20706]
Is it possible to make all url clickable inside the terminal to open a browser ?

In the sample bellow, I click on "Ctrl" above the link to activate the navigation.

Here you are a link to a video : https://youtu.be/-QsOepOU6j0

**Comment by Tyriar** [comment]
This actually landed in the [Insiders build](https://code.visualstudio.com/insiders) 2 days ago :+1: 

Duplicate of https://github.com/Microsoft/vscode/issues/7321
