### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by nani6666** [Microsoft/vscode#20701]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.7.0|
|vscode-html-css|ecmel|0.0.33|
|Angular2|johnpapa|2.0.3|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|debugger-for-chrome|msjsdiag|2.5.2|
|JavaScriptSnippets|xabikos|1.4.0|

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Please provide more details.
