### ISSUE TITLE
vs code IntelliSense is messing with typing only in PowerShell (core latest)

### ISSUE THREAD

**Issue by Sayemahamed** [microsoft/vscode#207038]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0
- OS Version: windows 11 23H2

Steps to Reproduce:

1. just type pwsh command in vs code Terminal 
2. 
![image](https://github.com/microsoft/vscode/assets/95583680/71537242-93db-47cc-8c8d-9557b9c3b15e)

**Comment by Tyriar** [comment]
This is because you've set `terminal.integrated.shellIntegration.suggestEnabled`, coming in the next version will be a warning in your settings file to warn about this as it's experimental and not ready for general use yet.
