### ISSUE TITLE
Microphone and Speech recognition issues

### ISSUE THREAD

**Issue by Tech-lang** [microsoft/vscode#207022]
My visual studio code microphone is having issues with listening to user input. If I speak to the microphone for my project it doesn't respond or listen at a
![SpeechRecognition problem](https://github.com/microsoft/vscode/assets/137643088/6680c6ef-5b92-4a54-b2d4-f2598f76d5d0)

```[tasklist]
### Tasks
```

**Comment by meganrogge** [comment]
What command are you using? Not sure where that listening message is coming from

**Comment by Tech-lang** [comment]
> What command are you using? Not sure where that listening message is coming from

def take_command():
    try:
        with sr.Microphone() as source:
            print('listening...')
            voice = listner.listen(source)
            command = listner.recognize_google(voice)
            command = command.lower()
            print(command)
            return command

i am basically trying to make my code listen to my voice and interpert
