### ISSUE TITLE
Scrolling in the editor seems to be broken

### ISSUE THREAD

**Issue by dcox1776** [microsoft/vscode#207093]
Type: <b>Bug</b>

As I scroll in the editor, some lines are frozen at the top of the editor and do not scroll off the screen as expected. Happens with every html or javascript file that I tried. See the attached image and note the line numbers.

![image](https://github.com/microsoft/vscode/assets/4509830/426b7203-a9ed-4f19-a3aa-1f235a033b85)

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.0-97-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|39.75GB (28.07GB free)|
|Process Argv|--crash-reporter-id d870cefb-6af4-46d2-8b52-e3055761eb57|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: cvit-observer.dhe.duke.edu|
|OS|Linux x64 5.15.0-97-generic|
|CPUs|AMD EPYC 7443P 24-Core Processor (8 x 2849)|
|Memory (System)|23.47GB (21.83GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-edge-devtools|ms-|2.1.5
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.3
vscode-dicom|smi|1.4.0
vscode-sqlite3-editor|yy0|1.0.179

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30981707
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
78248357:30976999
dsvsc020:30976470

```

</details>

**Comment by dcox1776** [comment]
I think I figured it out - something called "sticky scroll"...

![image](https://github.com/microsoft/vscode/assets/4509830/77047062-9ea7-4938-a7ac-92a3f0f30ff1)

**Comment by gjsjohnmurray** [comment]
That is correct. Please see the current Release Notes for more information.

**Comment by dcox1776** [comment]
Thanks. Unfortunately, I didn't read the release notes. Apparently it was turned on when released? I spent the morning messing up my code and then undoing my changes because I didn't realize the top lines of my html weren't scrolling. It was by shear luck that I noticed the line numbers weren't changing.
