### ISSUE TITLE
Output channels are not fully disposed

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode#20703]
- VSCode Version: 1.9.1
- OS Version: OSX

Steps to Reproduce:

```javascript
  const outputChannel = window.createOutputChannel(`A channel`);
  outputChannel.show();
  setTimeout(() => {
    outputChannel.dispose()
  }, 1000);
```

The channel is left in the output channels list in the UI:

![screen shot 2017-02-16 at 6 04 22 pm](https://cloud.githubusercontent.com/assets/979966/23012522/63b80580-f472-11e6-9806-82e0b791f977.png)

**Comment by jrieken** [comment]
I don't have a way (anymore?) to remove an output channel

**Comment by isidorn** [comment]
@jrieken I connected it end to end with the api. Please take a look and let me know if it works for you.

**Comment by jrieken** [comment]
Looks good. Thanks 👏

**Comment by KalitaAlexey** [comment]
@isidorn,
It will be included into the release 1.10, won't it?

**Comment by isidorn** [comment]
@KalitaAlexey yes.

**Comment by KalitaAlexey** [comment]
@isidorn,
That's cool.
Thank you.

**Comment by KalitaAlexey** [comment]
Disposing an output channel switches to another channel in the tab select box, but it still shows the content of the disposed output channel.

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/20703#issuecomment-283581882 fyi @isidorn

**Comment by isidorn** [comment]
Created new issue https://github.com/Microsoft/vscode/issues/21734
