### ISSUE TITLE
With active selection, terminal does not get focus when switching to its editor group

### ISSUE THREAD

**Issue by alexasa79** [microsoft/vscode#207089]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0 
- OS Version: MacOS Sonoma, 14.3.1 (23D60).

Steps to Reproduce:
1. Start VSCode with one editor group.
2. Start a new empty document and enter some text.
3. Create a new terminal in the editor area ("Terminal: Create New Terminal in Editor Area").
4. Move the terminal to the editor group on the right ("View: Move Editor into Right Group")
5. Select some text in the editor (left group). 
6. Focus on the second editor group ("workbench.action.focusSecondEditorGroup" or CMD+2 on MacOS).

Screencast:
![focus-bug](https://github.com/microsoft/vscode/assets/417396/a947b745-bff3-40f8-ade9-64f736211b9f)

Additional notes:
1. The bug showed up a few months ago. It is not new to 1.87.
2. Editor gets focus just fine. The problem is only with the terminal.
3. The terminal in the panel (CMD+J) works fine.
4. Attaching my settings: [settings.json](https://github.com/microsoft/vscode/files/14526954/settings.json)

**Comment by bpasero** [comment]
We rely on `focus()` being implemented properly on the editor pane.

**Comment by meganrogge** [comment]
Seems we do that here 🤔 

https://github.com/microsoft/vscode/blob/3c318f2facf9a8fd28617b6a8d52b7acf5c45c4d/src/vs/workbench/contrib/terminal/browser/terminalEditor.ts#L103-L107

**Comment by alexasa79** [comment]
Thank you!
