### ISSUE TITLE
the line above wrongly selected on ubuntu 16 installed on virtual box

### ISSUE THREAD

**Issue by jonygli** [Microsoft/vscode#20702]
- VSCode Version: 1.9.1
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. open a text file, ex. a python script 
2. click to try to select a line or double click to try to select a word, sometime, it selects the line above

**Comment by joaomoreno** [comment]
A little screen recording would be helpful.

**Comment by jonygli** [comment]
when the virtualbox window is maximized, it can work correctly. however, when the vb window is not maximized, it can very easily reproduce!

**Comment by joaomoreno** [comment]
Is VS Code the only app with this issue, or can you reproduce in others, e.g. Google Chrome?

**Comment by jonygli** [comment]
good question!
I tried sublime just now. yes, it is the same with vscode. so it probably bugs of vb.

thanks.
