### ISSUE TITLE
Autosave files after search-replace

### ISSUE THREAD

**Issue by andi1984** [Microsoft/vscode#20707]
- VSCode Version: 1.9.1
- OS Version: 10.12.13

Steps to Reproduce:

1. Go to search panel, search replace something in multiple files
2. The files are not autosaved, you have to open them and save them manually that the changes have an impact

**Comment by bpasero** [comment]
@andi1984 the files should all open for you automatically, if not please file a bug on that particular issue.

**Comment by sandy081** [comment]
@andi1984 Can you please confirm the behaviour in above comment?

**Comment by andi1984** [comment]
@sandy081 I can confirm the behaviour in @bpasero comment. I don't know why it wasn't or I thought it wasn't the case when I filed the bug. _Sorry!_ Nevertheless_ thx for the hint with auto-saving. I will enable this. I close this issue then.

**Comment by rofrol** [comment]
I would be nice to have an option for `files.autoSave`: `onSearchAndReplace`

**Comment by iulo** [comment]
It would be nice if seach-replace has an option (like a checkbox) “autosave”， I don't want to autosave files except some search-replace purpose.
