### ISSUE TITLE
on danish keyboard ctrl+½ (½ === ~ on us keyboard) don't open terminal

### ISSUE THREAD

**Issue by pbwuxus** [Microsoft/vscode#20712]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.4.0-62-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.8.0|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.6|
|file-icons|file-icons|1.0.2|
|flow-for-vscode|flowtype|0.5.0|
|debugger-for-chrome|msjsdiag|2.5.3|
|seti-icons|qinjia|0.1.3|
|vscode-icons|robertohuertasm|7.2.0|
|dark-plus-material|vangware|0.2.1|

---

Steps to Reproduce:

1. on a danish keyboard(maybe others) the ~ key next to 1 is ½
2. by press ctrl+½ nothing happen
3. try to change the key in settings to any of the char on the key like § or ¾ do not help

**Comment by Tyriar** [comment]
ctrl+' seems to work for other keyboard layouts, the problem itself I believe will be fixed in https://github.com/Microsoft/vscode/issues/17521

You may also be able to hover the keybinding in keybindings.json for a hint how to trigger it on your layout.
