### ISSUE TITLE
5 second delay when running any program

### ISSUE THREAD

**Issue by Strongestsquirrel** [microsoft/vscode#207135]
Type: <b>Performance Issue</b>

Within the last two months, my VSC began having a delay of 5 - 10 seconds whenever I try to run any program. It isn't code specific, because even when trying to run just a print line it still has the same delay. The code still runs quickly, it just seems to take very long to start. At the time I didn't take much notice as I was working on a big project and so I thought it was just the actual project being slow, and as such I am unable to pin point if there was anything I changed. I have tried uninstalling VSC and all related files, resetting all settings and preferences, but even when reinstalling it still has the same issue. I haven't been able to find other people online with the same issue and am at a loss for what to do. Unfortunately I cannot give details on how to recreate as I do not know what caused it myself

VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.18GB free)|
|Process Argv|--crash-reporter-id 7407d8cb-da65-466d-ac67-60a372c119f0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   107	 13344	code main
    0	    40	  1268	   utility-network-service
    0	    88	  4204	shared-process
    0	    92	  6332	ptyHost
    0	     6	  6232	     conpty-agent
    0	    61	 10616	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    89	  6556	window [2] (Issue Reporter)
    0	    85	  8972	fileWatcher [1]
    0	    28	  9016	   crashpad-handler
    0	   124	 11208	   gpu-process
    0	   148	 15604	extensionHost [1]
    0	   156	  3680	     electron-nodejs (bundle.js )
    0	   140	 15780	window [1] (hopefulTester.py - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
78248357:30976999
dsvsc020:30976470

```

</details>

**Comment by Strongestsquirrel** [comment]
@roblourens Would you be able to help me? I see you were assigned to this problem

**Comment by roblourens** [comment]
Can you give some more details? What _exactly_ are you doing when you run a program? What lanuage?

**Comment by Strongestsquirrel** [comment]
@roblourens It is in Python, and when I mean run the program I mean clicking the little triangular "Run" button in the top right corner of the screen.

**Comment by Strongestsquirrel** [comment]
Some additional information is that if I run the python file directly through command prompt it runs instantly with no delay. This is why I believe the problem perhaps to be a setting or something related to Visual Studio Code

**Comment by Strongestsquirrel** [comment]
@roblourens good day, would you be able to help me? It has been quite some time since our last communication, and each day I still struggle with this issue

**Comment by roblourens** [comment]
Please file on the Python extension, and maybe include a screen recording or something that would help communicate what part of the process is slow

**Comment by Strongestsquirrel** [comment]
https://github.com/microsoft/vscode/assets/162666774/972e22d6-99d9-4e85-b5db-d376cf766782

@roblourens here is a video recording of what happens. I am confused as to why you close this issue as completed when it has not been?
