### ISSUE TITLE
editor.lineNumbers: interval - render last line number

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#207179]
When setting `"editor.lineNumbers": "interval",`, the last line number should always be rendered, to prevent confusion about empty last lines:

![Image](https://github.com/microsoft/vscode/assets/2931520/88fb025b-0e91-4323-a8af-cbdfb5f62c7c)

**Comment by 89netraM** [comment]
Hi! I'd like to try my hand at this, as my first issue.

**Comment by Deepakvrma14** [comment]
hii i have studied the codebase of vs code, and wanted to have it as my first open source issue, can you assign me for it
