### ISSUE TITLE
ITerminalInstance.reuseTerminal doesn't update the terminal name

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#20717]
- VSCode Version: 1.9
- OS Version: Windows

Steps to Reproduce:

1. Reuse a terminal but specify a different name in the `shellLaunchConfig`
2. Observe: the new name is not reflected in the drop down list. It still shows the first name

**Comment by Tyriar** [comment]
Verified by injecting the following into terminalInstance constructor:

```ts
		setTimeout(() => {
			this.reuseTerminal({
				name: 'test'
			});
		}, 5000);
```
