### ISSUE TITLE
See debug button hover every time I show the debug view

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#207171]
- Click the debug icon, or press cmd+shift+D
- Wait a couple seconds
- The 'Start Debugging' hover shows on the debug button, because it is focused when the view is revealed

I can't get a screenshot, but it always happens. Is there a way that we could only show the hover when tabbing to that button, but not when focusing it programmatically? Or, is the best practice for us to focus some other element besides that button? I think it's a good place to put focus when revealing the view, especially with the cmd+shift+D shortcut

**Comment by roblourens** [comment]
@benibenj were you working on this recently?

**Comment by benibenj** [comment]
duplicate #206908
