### ISSUE TITLE
Error while searching for extension

### ISSUE THREAD

**Issue by abhijit-chikane** [microsoft/vscode#207164]
From last couple of weeks I am seeing this a lot
When I search for an extension it shows this error for a sec or so and then it shows the actual results
- VS Code Version: 1.88 insider and 1.87
- OS Version: Windows 11

Steps to Reproduce:

1. Search for extension
initially showing the error while typing
![image](https://github.com/microsoft/vscode/assets/50770619/f3ca26d9-2440-4c58-a4cd-5aef1c65e436)

2. and after a sec. or so it shows the actual results
![image](https://github.com/microsoft/vscode/assets/50770619/2474aaf2-d653-40be-a752-518991fb2778)

**Comment by sandy081** [comment]
@abhijit-chikane Can you please try again with the latest VS Code and let us know if you are still able to reproduce this error?

**Comment by abhijit-chikane** [comment]
I don't see this error now
I think we can close this

Thanks!🎉
