### ISSUE TITLE
Extensions tab not working

### ISSUE THREAD

**Issue by julesjacobs** [microsoft/vscode#207136]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.1 (Universal)
- OS Version: OS X 14.0 (23A344)

Steps to Reproduce:

1. Open VS Code
2. Go to the extensions tab

The loading animation keeps moving, but the extensions list doesn't load (not even extensions that are installed).
I tried reinstalling VS Code (and deleting all files associated with VS Code), but the issue doesn't go away.
VS Code Insiders does load the extensions.

P.S. the report issue button doesn't work either.

<img width="393" alt="image" src="https://github.com/microsoft/vscode/assets/476654/e91a6ffc-922b-42a2-9cca-12dcd5b7410f">

**Comment by sandy081** [comment]
Can you please share following log?

- F1 > Open View.. > Shared

**Comment by julesjacobs** [comment]
I am not sure which log you are referring to. If I do F1 > Open view, there is no option Shared. Can you elaborate?

**Comment by sandy081** [comment]
/duplicate 


https://github.com/microsoft/vscode/issues/206522
