### ISSUE TITLE
allow getting defenitions without the need for a .d.ts file

### ISSUE THREAD

**Issue by sr229** [Microsoft/vscode#20715]
you can close this if this is already implemented/vague.

Code Lensing and Intellisense seems to be limited when there's a ``.d.ts`` present or for local files only (when there's a Decorator present in the file).

Allowing VS Code to look through definitions in NPM/Local libraries relaxes the need for a ``.d.ts`` for Intellisense.

**Comment by mjbvz** [comment]
Thanks for the suggestion.

To a bit more context, `d.ts` files allows us to provide rich intellisense for external modules without having the be in the business of analyzing JavaScript patterns or indexing these files. Having typings files solves a number of performance and design issues for our tooling, and these files are core to our current language features. 

Closing this as out of our current design scope / upstream on the TypeScript side
