### ISSUE TITLE
QP Separator Items: Improve keybinding to navigate between sections

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#207193]
I introduced a keybinding recently (#207028) which works well for inline separators but not item separators... it was focusing the last item in a section when you go up.

Revisit to focus the first item in a section.

**Comment by TylerLeonhardt** [comment]
Fixed in https://github.com/microsoft/vscode/pull/207520

**Comment by rzhao271** [comment]
I verified that Alt+DownArrow and Alt+UpArrow on Windows navigate between sections on a quick pick, always focusing the first item of a section. Let me know if that's not what this issue is about.
