### ISSUE TITLE
settings.json wiped after nightly update

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#20714]
- VSCode Version: 1.10-insider (496b80)
- OS Version: Windows 10 64 bits

My settings.json were wiped, it now only contains 

```json
{
  "workbench.iconTheme": null
}
```

how can I restore it? (keybindings.json untouched)

**Comment by joaomoreno** [comment]
cc @Microsoft/vscode for awareness

**Comment by aeschli** [comment]
I wasn't able to reproduce, also the migration code has changed.
I added some tests for setting 'null' .
