### ISSUE TITLE
Preserve EOL type

### ISSUE THREAD

**Issue by rongjiecomputer** [Microsoft/vscode#20718]
- VSCode Version: 1.9.1
- OS Version: Windows 10

We already have `{"files.eol": "\r\n" or "\n"}` to set default EOL type. I suggest splitting this setting into two parts:

- `files.eol`: (No change).
- `files.preserveEOL`: If set to `true`, EOL of old files will be preserved. If set to `false`, EOL of old files will be set according to `files.eol`. New files will still follow `files.eol`.

**Comment by alexandrudima** [comment]
@rongjiecomputer By default, vs code preserves the EOL of files and new files follow `files.eol`.

So the only proposed change is to automatically convert files to the configured `files.eol` when `files.preserveEOL` is set to `false`. We don't typically do such "surprising" things (i.e. opening a file leading to a change in the file).

The current manual action is to click on the line ending shown in the status bar and to choose a different EOL manually.

**Comment by rongjiecomputer** [comment]
> By default, vs code preserves the EOL of files and new files follow files.eol.

I vaguely remember my file's EOL got switched after viewing it with vscode, probably my mistake then.

Since the default behaviour is already what I need, I will just close this now. Thanks for your tips @alexandrudima!
