### ISSUE TITLE
Unable to Delete files on Windows

### ISSUE THREAD

**Issue by martinmcwhorter** [Microsoft/vscode#20719]
- VSCode Version: 1.9.1
- OS Version: Windows 7

Steps to Reproduce:

1. Select a file in the Explorer
2. Right mouse click and select Delete

The file does not get deleted. Instead an error message is displayed: 

    [Error] Cannot read property 'object' of undefined             [Close]

Opening the Integrated Terminal and entering in the following deletes the file without any errors. 

    del src\app\path\to\file.component.scss

**Comment by bpasero** [comment]
@martinmcwhorter 
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by martinmcwhorter** [comment]
@bpasero 

Not sure what happened, but I cannot reproduce this issue any more.
