### ISSUE TITLE
`Esc` in editor should close unfocused (editor) widgets 

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#207161]
Repro using search widget but should apply to all widgets such as inline chat, test "peek error", etc.: 

1. press `cmd+f` to open search widget 
2. move focus to the editor (e.g., using a mouse) 
3. pressing escape should close the search widget but it doesn't

**Comment by hediet** [comment]
![Image](https://github.com/microsoft/vscode/assets/2931520/02c1b950-3446-4ffa-86d4-2e62903930db)

It does for me! Maybe this is a vim problem?

**Comment by ulugbekna** [comment]
ah, yeah, it's always vim
