### ISSUE TITLE
Paste link in markdown file adds extra markdown link syntax

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#207186]
* Be in insiders.vscode.dev
* Open a markdown file
* Add `[asdf](|)` where `|` is the cursor
* copy a link from the address bar and paste it
* 🐛 `[asdf]([text](https://github.com/microsoft/vscode/issues/34563))` is what happens

I wonder if this is because the text is rich text?

**Comment by mjbvz** [comment]
@TylerLeonhardt What browser and are you coping the link? I can't repo in my testing on MacOS

**Comment by TylerLeonhardt** [comment]
Safari on macOS when I copy from the address bar

**Comment by mjbvz** [comment]
How are you copying it? Selecting the text in the address bar?

Also have you changed `markdown.editor.pasteUrlAsFormattedLink.enabled`? Maybe it's set to `always`?

**Comment by TylerLeonhardt** [comment]
> How are you copying it? Selecting the text in the address bar and using cmd+c?

Yep.


https://github.com/microsoft/vscode/assets/2644648/8860d206-d4a7-432a-9485-b2d8dc8b053f

and no, that's not changed:

<img width="784" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/847fa5bf-4da3-4366-90ff-1165bde03779">

**Comment by mjbvz** [comment]
Ah missed you're on web. Can repo there. It's likely safari is writing `text/uri-list` or similar in this case instead of just plain text
