### ISSUE TITLE
Missing Option to Submit

### ISSUE THREAD

**Issue by PSC-Keefe** [microsoft/vscode#207166]
Hello,

I'm not sure whose responsibility this is, but my professor told me to submit a ticket. This is in regards to a school assignment, "Ch. 13 Practice Exercise 01".  Even though it's a practice exercise, it is a graded assignment.  However, the GitHub Companion provides no way to "Run Test" after each task, nor the "Calculate Grade" and "Submit" buttons to complete the assignment and have the grade reflected in Cengage. So even though I went through and completed each tasks, with no way to submit, my assignment still shows as "incomplete" in Cengage and Canvas.  The other assignments I was able to use those three functions mentioned above to submit once completed and they auto-populated my grade in Cengage and Canvas.

Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by aiday-mar** [comment]
Hi @PSC-Keefe thank you for posting this issue. Could you paste here a screen recording of the issue you are seeing. I am not sure I understand what the error is. Sounds like you could be experiencing an issue in an extension.

**Comment by gjsjohnmurray** [comment]
@PSC-Keefe I think you need to use the Cengage support channels, as the features you describe are not part of the core VS Code product.

**Comment by aiday-mar** [comment]
Yes @gjsjohnmurray mentioned, you may file the issue directly to the extension authors. I will close this issue.
