### ISSUE TITLE
C++ syntax highlight error 

### ISSUE THREAD

**Issue by clysto** [microsoft/vscode#207184]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.1
- OS Version: MacOS Sonoma 14.3.1 

Steps to Reproduce:

1. input this code:
```c++
#include <vector>

std::vector<uint64_t> test(1 << 22);

int main() {
  for (int i = 0; i < (1 << 22); i++) {
    test[i] = i;
  }
  while (true) {
    switch (test[0] % 4) {
      case 0:
        test[0] = test[0] * 0x5deece66d + 0xb;
        break;
      case 1:
        test[0] = test[0] * 0x5deece66d + 0xb;
        break;
      case 2:
        test[0] = test[0] * 0x5deece66d + 0xb;
        break;
      case 3:
        test[0] = test[0] * 0x5deece66d + 0xb;
        break;
    }
  }
  return 0;
}
```
2. 
<img width="812" alt="image" src="https://github.com/microsoft/vscode/assets/38179369/1966dbdd-f1c3-4948-9286-d2e145072e91">

**Comment by alexandruavadanii** [comment]
The C++ grammar (which has been frozen in https://github.com/microsoft/vscode/commit/eb03486765b6e06f82e392fd7f7da3f5a0c0e144, so don't hold your breath waiting for a fix for this, unless https://github.com/microsoft/vscode/issues/50140 actually lands this month + an alternative grammar for C++ is found) does not like your `1 << 22` used when initializing the vector. Use a define or extra parenthesis to work around that..

``` cpp
std::vector<uint64_t> test((1<<22));
```

**Comment by alexr00** [comment]
Thanks for the analysis @alexandruavadanii, you are correct.

Nonetheless, I've opened https://github.com/jeff-hykin/better-cpp-syntax/issues/654 in the upstream repo. There's some chance that the owner of the repo there changes the license back at some point.
