### ISSUE TITLE
colapse multi-line comments even if they don't have spaces/tabs before the lines 

### ISSUE THREAD

**Issue by bruceauyeung** [Microsoft/vscode#20711]
i have already filed [an issue](https://github.com/Microsoft/vscode-go/issues/805) under Microsoft/vscode-go , but it seems vscode do  colapsing work

for a golang project:
https://golang.org/doc/effective_go.html#commentary gives an example of block comment which has no space/tab before the lines.

all of `.go` source files in Kubernetes project have package comments , and all of these package comments have no space / tab before the lines.

gogland EAP version can colapse this kind of comments even when they don't have no space / tab before the lines.
![image 2](https://cloud.githubusercontent.com/assets/1210201/23015723/dcb74daa-f46e-11e6-8eeb-02c04d232dd1.png)

so i sugguest :
even when multi-line comments have no space/tab preceding the lines, vscode  should colapse this kind of comments.

**Comment by ramya-rao-a** [comment]
cc @alexandrudima @rebornix

**Comment by aeschli** [comment]
The current folding strategy is only indentation based. You ask for language aware folding. This is #3422
