### ISSUE TITLE
Group installed extenstions 

### ISSUE THREAD

**Issue by OlegK10** [microsoft/vscode#207106]
Type: <b>Feature Request</b>

It would be nice if it were possible to separate downloaded extensions into their groups, and then, for example, when working on a PHP project, enable the extensions for PHP, or for React when working on that, and so on.

I think it's a good idea because VS Code is a multi-language IDE.

Thx. :)

VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by gjsjohnmurray** [comment]
Have you discovered the Profiles feature yet?

**Comment by sandy081** [comment]
Use Profiles - https://code.visualstudio.com/docs/editor/profiles
