### ISSUE TITLE
Whitespaces - graphic interpatation

### ISSUE THREAD

**Issue by ivo-urbanek** [Microsoft/vscode#20713]
- VSCode Version: 1.9.1
- OS Version: Win 7

Missing option for quick view of white spaces (graphic interpratation) - one icon action.

**Comment by joaomoreno** [comment]
Do you mean this?

![image](https://cloud.githubusercontent.com/assets/22350/23060570/8e658b22-f4fe-11e6-8166-55209f666b5c.png)
