### ISSUE TITLE
launch conf

### ISSUE THREAD

**Issue by cadem** [microsoft/vscode#207149]
config in launch.json
 {
          "cwd": "${workspaceFolder}/community/tests/system-test",
          "name": "Python: specific(enterprise)",
          "type": "python",
          "request": "launch",
          "program": "${workspaceFolder}/community/tests/system-test/test.py",
          "args" : ["-f", "mytest/sm4/sm4.py", "-a", "2>${workspaceFolder}/sim/asan/client_asan.log"],
          "console": "integratedTerminal",
        }

run result
cd /root/github/taosdata/TDinternal/community/tests/system-test ; /usr/bin/env /bin/python3 /root/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 58795 -- /root/github/taosdata/TDinternal/community/tests/system-test/test.py -f mytest/sm4/sm4.py -a 2\>/root/github/taosdata/TDinternal/sim/asan/client_asan.log

2> become 2\>, it doesn't work correctlly.

**Comment by roblourens** [comment]
Please file on the Python extension repo, thanks
