### ISSUE TITLE
Clicking groups on debug console crashes the debugger

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#20723]
- VSCode Version: 1.10-insider
- OS Version: Windows 10 64 bits

Steps to Reproduce:

1. Use the "Launch Chrome" task
2. Using a React app and the logger middleware for Redux, try to click the actions in the "Debug Console"
![debug console](https://cloud.githubusercontent.com/assets/461084/23022284/c3cad5d6-f42e-11e6-967e-447efa476048.jpg)
3. Debugger crashes with the errors below
![debugger](https://cloud.githubusercontent.com/assets/461084/23022285/c3d1367e-f42e-11e6-91b5-07e238115938.jpg)
![debugger2](https://cloud.githubusercontent.com/assets/461084/23022511/04435696-f430-11e6-8191-4ae17d7e0392.jpg)

A side note: placing breakpoints in VSCode won't set them in Dev Tools (not sure if it's related)

**Comment by isidorn** [comment]
Hi, can you reproduce this issue constantly?
Is it possible for you to create a small git hub repositry with the project for which this can be reproduced?
When you say 'click actions in the debug console' - what exact actions do you mean? Are you trying to expand an object in the debug console and it is not working?

**Comment by pocesar** [comment]
actions is a "group" console.log outputted from react-logger middleware, it groups prev, action and next redux states and outputs them. when you try to expand it in the debug console (clicking the little arrow), the errors happens. 

it's not reproducible every time though, it seems really random, but usually when remote debugging

**Comment by isidorn** [comment]
This sounds like an the chrome debug adapter crashes when requesting data in order to expand the output object. Moving to @roblourens as he might have more ideas on how to best tackle this.

**Comment by roblourens** [comment]
Can you try running with `"diagnosticLogging": true`, then uploading the log from the path that it prints at the top of the debug console?
