### ISSUE TITLE
File opened through command palette always opens in the same tab.

### ISSUE THREAD

**Issue by urias-bt** [Microsoft/vscode#20726]
Hi there,
When I open a file through **command palette**, it always opens in the same tab.

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Press Ctrl+P
2. Type the name of the file you want to open
3. Press enter
4. Repeat

**Comment by bpasero** [comment]
Try: `"workbench.editor.enablePreviewFromQuickOpen": false`
