### ISSUE TITLE
New filetype that's "the same as JS but with an extra types.d.ts loaded"?

### ISSUE THREAD

**Issue by Pomax** [microsoft/vscode#207202]
I went through the dev docs looking for how get a new filetype added that is "JS, but with some more globals loaded in", but all I can find is articles that explain how to write an full fledged language server extension, instead of something that just extends an existing filetype with some extra built-ins.

Are there docs for that, specifically? If not, would it be possible to get those added?

**Comment by IllusionMH** [comment]
What exactly you want to achieve?
If you just need some globals in JS files: create `jsconfig.json` and create `.d.ts` file with globals that will be in path that matches (explicit or implicit) `includes`.

**Comment by Pomax** [comment]
It's not "for me" - I maintain an open source library that gives people a custom `<graphics-element>` for putting on pages, which accepts "plain JS but with 100ish extra global vars and functions", and I'm looking for a way for people to install an extension into VS Code that gives them a new `JavaScript (graphics-element)`, so that VS code does auto-complete and type hinting for not just plain JS but also the additional globals that I have a types.d.ts for.

**Comment by IllusionMH** [comment]
If you release it as library you can release `.d.ts` with globals declaration along with the package or separately and it would benefit not only VS Code users (but any editor with TS support) , at small one time effort from user's side. Definitely depends on lib distribution format, but may be useful. 

At this note I'll see myself out.

**Comment by Pomax** [comment]
That's not "a small one-time effort" from the user's side, that's _a hassle_ from the user's side =) It would be _far_ more user friendly if they can just install an extension and then just tell VS Code what this .js file is a "JavaScript (graphics-element)" file.

**Comment by Pomax** [comment]
No, it isn't, it's a question about your developer documentation.
