### ISSUE TITLE
error left explorer view

### ISSUE THREAD

**Issue by billydev23** [microsoft/vscode#207294]
Type: <b>Bug</b>

No file showed after I update

VS Code version: Code 1.87.1 (Universal) (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:23:16.418Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 8, 8|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 5249d4ef-b783-4825-abee-47b041042467|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|3.1.2
atlascode|atl|3.0.10
vscode-intelephense-client|bme|1.10.2
gitlens|eam|14.9.0
go|gol|0.41.1
openapi-lint|mer|1.2.0
vscode-docker|ms-|1.29.0
vscode-kubernetes-tools|ms-|1.3.15
remote-containers|ms-|0.348.0
makefile-tools|ms-|0.8.22
vsliveshare|ms-|1.0.5918
docker-compose|p1c|0.5.1
vscode-thunder-client|ran|2.19.4
vscode-yaml|red|1.14.0
php-debug|xde|1.34.0
php-pack|xde|1.0.3
php-intellisense|zob|1.3.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30968132
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
8f97e687:30977000
dsvsc020:30976470

```

</details>

**Comment by lramos15** [comment]
`F1 -> Reset View Locations`
