### ISSUE TITLE
In the template tag, when you enter a tag or tag attributes, the hint appears with a delay, and this causes discomfort

### ISSUE THREAD

**Issue by peacefful** [microsoft/vscode#207286]
In the template tag, when you enter a tag or tag attributes, the hint appears with a delay, and this causes discomfort

**Comment by aeschli** [comment]
What is a template tag?

Please provide detailed steps to reproduce. Screenshot can also help. 
Here is an example:
- create a file `text.ext`
- open the editor on that file. The language mode of the editor is `plaintext`
- enter the content `....`
- move the mouse over ...
- I see: xy, I expect zx

**Comment by aeschli** [comment]
Please file this against the `vue` extension. All support for `vue` comes from extensions.

I don't see any delay when trying this in HTML.
