### ISSUE TITLE
[Feature] Multiple Editor Window Support

### ISSUE THREAD

**Issue by DWSR** [Microsoft/vscode#20721]
- VSCode Version: 1.9.1
- OS Version: 10.0.15031.0

I would love to see the ability to have multiple editor windows open to support workstations with multiple monitors. I see this working similar to Visual Studio or Chrome, where pulling a tab out of the main window and to the desktop creates a new (editor-only) window, which can then itself have multiple tabs and be redocked in the main window by dragging it back.

**Comment by joaomoreno** [comment]
#2686
