### ISSUE TITLE
Terminal Links Broken

### ISSUE THREAD

**Issue by Jde-cpp** [microsoft/vscode#207239]
Type: <b>Bug</b>

In bash terminal type:
```
echo -e '\e]8;;file:///home/duffyj/temp.sql\afile_link\e]8;;\a'
```
Clicking should bring up //home/duffyj/temp.sql, but brings up "No matching results".

It works great in Ubuntu's bash terminal.  It used to work in vscode.  I assume January's 1.86 update broke it.  I can't seem to uninstall current version to test.

VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:07.287Z)
OS version: Linux x64 6.5.0-25-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 3999)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|62.75GB (57.69GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id a362a55c-407e-43ca-843a-7e5022c9b6e3|
|Screen Reader|no|
|VM|67%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|17.2.2
vscode-mysql|for|0.5.0
copilot|Git|1.172.0
copilot-chat|Git|0.13.0
cpptools|ms-|1.19.6
hexeditor|ms-|1.9.14
vscode-multiclip|sle|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
f8hc8238:30694864
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30958156
dsvsc020:30976470

```

</details>

**Comment by Jde-cpp** [comment]
The links seem to work in 1.89.0.
You used to be able to specify a line with #5 to go to line 5, it just brings up the file now at line 1 or the current line.

Syntax `:Line 5` or `:5` will not bring up the file.

**Comment by Chealer** [comment]
Is this reporting the same issue as #211307? Or does this also affect HTTP URL-s?
