### ISSUE TITLE
Vscode recommends depricated extension TypeScript Vue Plugin( (Volar)

### ISSUE THREAD

**Issue by kingma-sbw** [microsoft/vscode#207269]
Does this issue occur when all extensions are disabled?: Yes/No
yes

- VS Code Version: 1.87.1
- OS Version: windows 10

Steps to Reproduce:

1. Open a vue project
2. Volar is recommended, click on install,
3. After Installation it shows as This extension is deprecated. Use the [Vue - Official](vscode-file://vscode-app/d:/Users/Johannes/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) extension instead.

**Comment by theking2** [comment]
The text that appears: `Do you want to install the recommended 'TypeScript Vue Plugin (Volar)' extension from Vue for this repository?`

**Comment by panthablack** [comment]
I just replicated this in a python project with no `.js`, `.ts` or `.vue`  files in it.  It also appears in an `@recommended` extension search.

**Comment by isidorn** [comment]
We actually do not recommend `Vue.vscode-typescript-vue-plugin` from vscode anywhere.
It looks like the repository you are opening is recommending a deprecated extension. I suggest to reach out to the repository owner to tell them to recommend the new extension vue.volar

@sandy081 maybe there should be a way in core to change repository extension recommendation for deprecated extensions.

**Comment by kingma-sbw** [comment]
That is interesting . Is it part of a workspace file or repo to recommend extensions?

**Comment by isidorn** [comment]
Yeah, look under the top level `.vscode` folder in the repository.

**Comment by panthablack** [comment]
Yeah, it could be added as a feature request, for vscode to offer to remove deprecated recommendations from the `extensions.json` file (the culprit here, which I think was automatically added when creating a new Vue project with TS using Vue CLI and/or Vite) where vscode is currently suggesting to install it?
