### ISSUE TITLE
Insiders Helper goes eats all CPU every time I open a SVG file

### ISSUE THREAD

**Issue by lmartins** [Microsoft/vscode#20720]
- VSCode Version: Code - Insiders 1.10.0-insider (f04798da0ee930b80ae58be6455286455bfd3964, 2017-02-15T07:04:58.587Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|compulim-vscode-closetag|Compulim|0.1.2|
|vsc-material-theme|Equinusocio|0.0.5|
|beautify|HookyQR|0.8.0|
|vscode-simple-icons|LaurentTreguier|0.10.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-theme-onedark|akamud|1.2.0|
|Bookmarks|alefragnani|0.11.0|
|theme-atom-one-light|b4456609|0.2.3|
|vscode-twig-pack|bajdzis|1.0.0|
|theme-jsfiddle-like-syntax-vscode|davidmart|0.0.6|
|vscode-dash|deerawan|1.3.0|
|githistory|donjayamanne|0.1.5|
|theme-dracula|dracula-theme|1.2.5|
|php-debug|felixfbecker|1.10.0|
|auto-rename-tag|formulahendry|0.0.11|
|vscode-flatland-icon-theme|gebilaoxiong|0.0.6|
|Theme-OceanicNext|gerane|0.0.2|
|Theme-snappy-light|gerane|0.0.2|
|vue-snippets|hollowtree|0.1.0|
|theme-material-theme|jprestidge|1.0.1|
|vscode-liquid-snippets|killalau|0.2.5|
|php-symbols|linyang95|2.1.0|
|vue|liuji-jim|0.1.5|
|Theme-MaterialKit|ms-vscode|0.1.1|
|Theme-TomorrowKit|ms-vscode|0.1.3|
|atom-keybindings|ms-vscode|1.9.0|
|debugger-for-chrome|msjsdiag|2.5.3|
|trailing-semicolon|naumovs|1.0.2|
|language-liquid|neilding|0.0.2|
|vscode-duotone-dark|sallar|0.2.1|
|Align|steve8708|0.2.0|
|theme-base16-ocean-dark|viatsko|1.0.0|
|twig|whatwedo|1.0.2|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:
For me this has been pretty consistent for a while. Every time I open an SVG file, even very basic ones, the Insiders Helper CPU consumption goes to 100% or above and stays like that until I manually kill the process (quitting VS Code won't fix it either).

**Comment by joaomoreno** [comment]
Does it reproduce with `code --disable-extensions`?

**Comment by lmartins** [comment]
Actually must be something else because I was just checking what you're asking and the CPU is already at 100% before opening any SVG file.

**Comment by joaomoreno** [comment]
And is VS Code responsible for that 100% CPU? Please check using a process monitor such as Process Hacker.

**Comment by lmartins** [comment]
The process is called "Code - Insiders Helper" so I'd say yes, just not sure how to pinpoint the root cause for it. When I first reported this, it consistently happened every time I've opened an SVG file, today isn't displaying the same behaviour. I'm trying to find which action triggers the problem.

**Comment by lmartins** [comment]
I haven't been able replicate the issue consistently, so im closing this for now until I do. Thanks.

**Comment by lmartins** [comment]
I am now able to replica this behaviour in a consistent manner. All it takes to make VSCode go bonkers in CPU consumption is to edit and save a simple SVG file. When I save the file the editor takes about a 1sec to respond, CPU goes all the way up to around 100% and after that it just stays there.

When this is going, every time I try to save a file the lag between the keyboard input and the file being saved is quite noticeable. 

The only way to recover from this is by quitting the app and manually kill the process to get it back to normal condition.

I've attached one example of such SVG files.

[search.zip](https://github.com/Microsoft/vscode/files/821672/search.zip)

**Comment by joaomoreno** [comment]
Thanks for the sample. I can't reproduce though.

So... does it reproduce when running with `code --disable-extensions`?

**Comment by kcliu** [comment]
Nope, it can't reproduce when running with `code --disable-extensions`. 
It seems caused by `vscodevim` extension.

**Comment by joaomoreno** [comment]
ping @lmartins

**Comment by lmartins** [comment]
@joaomoreno I don't have `vscodevim` as an extension installed, not sure if that is part of core or not.
I had to stop using VSCode for the time being, so I can't provide much more info, so I'll close this.
