### ISSUE TITLE
VSCode being laggy

### ISSUE THREAD

**Issue by Buddika92** [microsoft/vscode#207235]
Type: <b>Performance Issue</b>

When coding continuously. sometimes it get at once and after while the words are typed. it if very difficult to get stuck while working continuously. please fix this. 

VS Code version: Code 1.87.1 (Universal) (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:23:16.418Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.74GB free)|
|Process Argv|--crash-reporter-id 081f626e-3f57-4461-8b5f-79218965e98b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	   213	  6356	code main
    2	    82	  6359	   gpu-process
    0	    33	  6360	   utility-network-service
    0	   492	  6361	window [1] (Nobel_Prize_Analysis.ipynb — 79 - Nobel Prize Analysis)
    0	   328	  6496	extensionHost [1]
    0	    66	  6663	     /Users/buddika/Downloads/79 - Nobel Prize Analysis/.myvenv/bin/python /Users/buddika/.vscode/extensions/ms-python.black-formatter-2024.0.1/bundled/tool/lsp_server.py --stdio
    0	   475	  6833	     electron-nodejs (bundle.js )
    0	    49	  6910	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/server/dist/node/workerMain --node-ipc --clientProcessId=6496
    0	    49	  8886	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=6496
    0	   213	  9012	     /Users/buddika/Downloads/79 - Nobel Prize Analysis/.myvenv/bin/python -m ipykernel_launcher --f=/Users/buddika/Library/Jupyter/runtime/kernel-v2-6496GmPfWQHHb9s2.json
    0	   164	  6498	   window
    0	   197	  6499	   window
    2	    82	  6507	shared-process
    0	     0	  9055	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    49	  6508	fileWatcher [1]
    0	    49	  6527	ptyHost
    0	     0	  6532	     /bin/zsh
    0	     0	  6701	     /bin/zsh
    2	    98	  9050	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Nobel_Prize_Analysis.ipynb — 79 - Nobel Prize Analysis)
|    Folder (79 - Nobel Prize Analysis): more than 22989 files
|      File types: py(7266) pyc(7265) pyi(2103) so(89) txt(63) afm(60) c(57)
|                  f90(49) ttf(38) h(34)
|      Conf files: package.json(2);
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.172.0
copilot-chat|Git|0.13.0
gc-excelviewer|Gra|4.2.59
black-formatter|ms-|2024.0.1
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.3
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30981708
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30958156
dsvsc020:30976470

```

</details>

**Comment by paul-rogers** [comment]
May be related to #206119

**Comment by DonJayamanne** [comment]
@Buddika92 
Apologies for not getting back to you on this issue.
I believe this issue has been resolved in the latest version of VS Code Insiders.
Please can you install VS Code insiders along with the latest pre-release versions of the Jupyter extension.

If the problem still persists, please ping here and I'll reopen this or feel free to create a new one.
