### ISSUE TITLE
Horizontal line across the text editor

### ISSUE THREAD

**Issue by rovermask** [microsoft/vscode#207263]
![Bug](https://github.com/microsoft/vscode/assets/82136617/525bac19-1f19-4d58-bd77-52e2da47594f)
Type: <b>Bug</b>

There's a horizontal line across the editor, which appears when I scroll down the code, it's so irritating. It's either a bug or i have donw something with my settings. In either case, provide some help

VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz (4 x 2990)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (4.39GB free)|
|Process Argv|E:\\PROGRAMMING\\WebD\\Projects\\Movies --crash-reporter-id f900bb69-3fc5-476b-95fb-e8e9c9f24239|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
code-runner|for|0.12.1
calculator|lix|0.1.1
rainbow-csv|mec|3.11.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.3
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.6
cpptools-extension-pack|ms-|1.3.0
material-icon-theme|PKi|4.34.0
java|red|1.28.1
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.56.2
vscode-java-dependency|vsc|0.23.5
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
8f97e687:30977000
ccp1r6:30958156
dsvsc020:30976470

```

</details>

**Comment by widersky** [comment]
It's called `Sticky Scroll` and you can easily disable this in settings. Just search for sticky scroll for editor, e.g. `editor.stickyScroll.scrollWithEditor`.
