### ISSUE TITLE
Visual Studio Code app problem

### ISSUE THREAD

**Issue by miger1** [microsoft/vscode#207257]
Type: <b>Performance Issue</b>

Hello, I using VS code for python coding and when i make change in code, code runs but as in before changes. I have to close VS code and open and than changes are active. I have reinastaled win 10 and VS code, so my PC is fine probably. Fact is that it is old HP mini PC Intel i3, 8gb ram, SSD. Thank you for your advice. Miger

VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.60GB free)|
|Process Argv|--crash-reporter-id 84fd52d5-bd5e-4cc7-a86e-65ae47f28a41|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   104	  2840	code main
    0	   196	  2584	   "C:\Program Files\Google\Chrome\Application\chrome.exe" --single-argument http://127.0.0.1:5000/
    0	   148	  2140	     window
    0	    82	  3512	     window
    0	    85	  4276	     window
    0	    58	  4432	     window
    0	    21	  6172	     utility-process
    0	    48	  8328	     window
    0	    10	  9092	     crashpad-handler
    0	   136	  9236	     gpu-process
    0	    32	 10452	     window
    0	    47	 11200	     utility-network-service
    0	   142	 11312	     window
    0	    24	 11356	     utility-process
    0	   148	 11672	     window
    0	    74	 12580	     window
    0	    94	  2808	ptyHost
    0	     7	  3468	     conpty-agent
    0	    68	  3580	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    24	   384	       "C:\Users\MG\AppData\Local\Programs\Python\Python312\python.exe" c:\Users\MG\.vscode\extensions\ms-python.debugpy-2024.2.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher 51907 -- c:\Users\MG\Desktop\test_excel\app.py
    0	    81	  3640	         c:\Users\MG\AppData\Local\Programs\Python\Python312\python.exe c:\Users\MG\Desktop\test_excel\app.py
    0	    66	  3840	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     7	  7172	     conpty-agent
    0	    65	 10616	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     7	 11816	     conpty-agent
    2	   143	  3492	   gpu-process
    0	    28	  7776	   crashpad-handler
    0	   192	  8524	window [1] (Settings - test_excel - Visual Studio Code)
    0	    99	  8724	shared-process
    0	    79	 11920	fileWatcher [1]
    0	    40	 12048	   utility-network-service
    3	    99	 12892	window [2] (Issue Reporter)
    0	   150	 13360	extensionHost [1]
    0	    24	  6992	     C:\Users\MG\AppData\Local\Programs\Python\Python312\python.exe c:\Users\MG\.vscode\extensions\ms-python.debugpy-2024.2.0-win32-x64\bundled\libs\debugpy\adapter
    0	    11	  4476	       C:\WINDOWS\system32\conhost.exe 0x4
    0	   192	  8952	     electron-nodejs (bundle.js )
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings - test_excel - Visual Studio Code)
|    Folder (test_excel): 23 files
|      File types: xlsx(14) py(1) css(1) html(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30981708
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30958156
dsvsc020:30976470
666c4381:30973075

```

</details>

**Comment by ulugbekna** [comment]
Please, enable screencast mode in vscode (ctrl+shift+p > "Developer: Toggle Screencast Mode") and provide a screencast of what's happening
