### ISSUE TITLE
Bug: Play a annoying sound when typing or click on toggle buttons

### ISSUE THREAD

**Issue by nafasebra** [microsoft/vscode#207283]
I have a bug when click on toggle button and when sometimes typing. As long as sleep my system this problem occurs.

This is the video I took that shows this bug:

https://github.com/microsoft/vscode/assets/74317517/ca83cec6-abc7-41ea-84cf-0669272bfd47

- VS Code Version: 1.87.1
- OS Version: Windows 11 23H2

Steps to Reproduce:

1. sleep my OS and system

**Comment by mjbvz** [comment]
What is the bug? Please explain the expected behavior
