### ISSUE TITLE
VS Code Speech not detecting any voice.

### ISSUE THREAD

**Issue by nelsonalves117** [microsoft/vscode#207290]
Type: <b>Bug</b>

I've always been able to use the Voice Chat option alongside Copilot Extension in Windows, but i've recently changed to Ubuntu 22.04 and for some reason no audio gets picked up. I can safely say it has nothing to do with standart microphone configuration,  since it' working perfectly fine anywhere else.  Altought i selected VS Code Speech in the bug report, i can't really be 100% certain the problem isn't in Copilot or Copilot Chat Extensions, so it really is just a guess. I have the newest version of all of this extensions and i've also tried reinstalling them.

Extension version: 0.6.0
VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:07.287Z)
OS version: Linux x64 6.5.0-25-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 4066)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|15.55GB (12.07GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id e80ba259-a637-40cf-9280-1ab8638a5da6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
8f97e687:30977000
ccp2r3:30958157
dsvsc020:30976470

```

</details>

**Comment by bpasero** [comment]
To figure out more about this issue related to voice recognition, can you do this:
* close all instances of VS Code
* open a terminal / console
* define an `VSCODE_SPEECH_LOGS_PATH` environment variable pointing to a folder that exists
  * on Windows: `set VSCODE_SPEECH_LOGS_PATH=<path to existing folder>`
  * on macOS/Linux: `export VSCODE_SPEECH_LOGS_PATH=<path to existing folder>`
* start VS Code from that terminal / console by typing `code` (or `code-insiders`) 
* set log level to trace for the extension (see [1])
* open the output channel for the extension (see [2])
* try to reproduce the issue that you had seen with voice recognition or keyword activation

Can you then share the output from the extension output channel as well as any log files in the folder of `VSCODE_SPEECH_LOGS_PATH`. Thanks!

[1]
<img width="729" alt="image" src="https://github.com/microsoft/vscode/assets/900690/f5df37a3-9949-4742-85a4-05f9976e0f74">
<img width="730" alt="image" src="https://github.com/microsoft/vscode/assets/900690/8c160914-904f-490f-a13c-173f6ef083c4">
<img width="722" alt="image" src="https://github.com/microsoft/vscode/assets/900690/40c2c84c-a15a-4cc8-aa77-88979c9e19f8">

[2]
<img width="934" alt="image" src="https://github.com/microsoft/vscode/assets/900690/30628791-8419-4758-a29d-0175fcc14d62">

**Comment by nelsonalves117** [comment]
Curious thing, i've actually manage to fix it by clean reinstalling VS Code through a differente package manager, at first i was using snap, which was the one giving me trouble, once i got it through apt it worked, altought i have no ideia if this could somehow be related to the problem or if i was just lucky (i think it's important to notice that clean reinstalling it with snap itself still left me with the same problem, only after getting it through apt that it started to work like it should). Anyway, thanks for the response.

**Comment by nelsonalves117** [comment]
> To figure out more about this issue related to voice recognition, can you do this:
> 
> * close all instances of VS Code
> * open a terminal / console
> * define an `VSCODE_SPEECH_LOGS_PATH` environment variable pointing to a folder that exists
>   
>   * on Windows: `set VSCODE_SPEECH_LOGS_PATH=<path to existing folder>`
>   * on macOS/Linux: `export VSCODE_SPEECH_LOGS_PATH=<path to existing folder>`
> * start VS Code from that terminal / console by typing `code` (or `code-insiders`)
> * set log level to trace for the extension (see [1])
> * open the output channel for the extension (see [2])
> * try to reproduce the issue that you had seen with voice recognition or keyword activation
> 
> Can you then share the output from the extension output channel as well as any log files in the folder of `VSCODE_SPEECH_LOGS_PATH`. Thanks!
> 
> [1] <img alt="image" width="729" src="https://private-user-images.githubusercontent.com/900690/302864150-f5df37a3-9949-4742-85a4-05f9976e0f74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjI1OTAsIm5iZiI6MTcxMDE2MjI5MCwicGF0aCI6Ii85MDA2OTAvMzAyODY0MTUwLWY1ZGYzN2EzLTk5NDktNDc0Mi04NWE0LTA1Zjk5NzZlMGY3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxMzA0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDFiNjliYTc5ODg5ZjhiYjc5YjhiYjI2ZGVjMmVmZmU4ODM5Y2NhMDFlMGYxYTRhZGMzYmY0YjE0OTYwMmFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2KwDqBWRH_7aDo33rT8I0rKzE14H1BbNssTKBl3_ejw"> <img alt="image" width="730" src="https://private-user-images.githubusercontent.com/900690/302864215-8c160914-904f-490f-a13c-173f6ef083c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjI1OTAsIm5iZiI6MTcxMDE2MjI5MCwicGF0aCI6Ii85MDA2OTAvMzAyODY0MjE1LThjMTYwOTE0LTkwNGYtNDkwZi1hMTNjLTE3M2Y2ZWYwODNjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxMzA0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGJkZjRiMDhiNTdlNDRjMjA2ZTQ1ZjY0MDJkNWE5NTE4MjAxMGRiODM3NDViNDQ5NWZhZmU0ZjBhNGM4MjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QlJyhxXptLQhGvzQv_poe7x5MRqEloSwjHZYZ1fjnq4"> <img alt="image" width="722" src="https://private-user-images.githubusercontent.com/900690/302864252-40c2c84c-a15a-4cc8-aa77-88979c9e19f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjI1OTAsIm5iZiI6MTcxMDE2MjI5MCwicGF0aCI6Ii85MDA2OTAvMzAyODY0MjUyLTQwYzJjODRjLWExNWEtNGNjOC1hYTc3LTg4OTc5YzllMTlmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxMzA0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjM0ZDA5YTc5ZTM0OTY4Y2IwZGJkODdlMjAzNjAxZDU4NzhiMTAzY2I4NmM5MzY0OTdmZTFmMDg2N2EwNzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-xKB9-QQvLPjYKH2lL_bZTxw_xgaBsKwOYmGNzSr8FM">
> 
> [2] <img alt="image" width="934" src="https://private-user-images.githubusercontent.com/900690/302864303-30628791-8419-4758-a29d-0175fcc14d62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjI1OTAsIm5iZiI6MTcxMDE2MjI5MCwicGF0aCI6Ii85MDA2OTAvMzAyODY0MzAzLTMwNjI4NzkxLTg0MTktNDc1OC1hMjlkLTAxNzVmY2MxNGQ2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxMzA0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzllYjFjZWM2NzAwZWExMzdiMTNlMTJhZTNmMTI1NzhkMjU2NTliMDBhMDhlMmI0YzI5N2IyOTliODQwNGJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ebRptsN4s1qNbdHxEjVgjQGoNBfWciGMxcOQejFcdXI">

Curious thing, i've actually manage to fix it by clean reinstalling VS Code through a differente package manager, at first i was using snap, which was the one giving me trouble, once i got it through apt it worked, altought i have no ideia if this could somehow be related to the problem or if i was just lucky (i think it's important to notice that clean reinstalling it with snap itself still left me with the same problem, only after getting it through apt that it started to work like it should). Anyway, thanks for the response.

**Comment by bpasero** [comment]
Yeah, Snap seems to cause trouble, see https://github.com/microsoft/vscode/issues/205758

**Comment by jason-curtis** [comment]
FWIW, I somehow had this same symptom on Windows 11 + WSL. Everything in VS Code had been working for years except this. Uninstall/reinstall seemed to do the trick for me too.
