### ISSUE TITLE
VS Code - Info: Resolve Dependancies Fails if User Path contains a SPACE

### ISSUE THREAD

**Issue by sporens** [Microsoft/vscode#2072]
Hi,

The command executed by VS Code to install and resolve missing dependancies for an ASP.NET application fails with "Can't find path" when the path to the users' home folder includes a space. For example:
c:\users\joeblogs\ <- works
c:\users\joe blogs\ <- fails

Running procmon I see it's attempting to execute:
cmd.exe /c start /wait cmd.exe /c "C:\Users\joe blogs\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\dnu.cmd restore & pause"

Which fails.

Thanks

**Comment by jrieken** [comment]
this is either omnisharp-vscode or omnisharp itself

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#2

**Comment by sklivvz** [comment]
This should be reopened, it was closed in Omnisharp but it still happens in vs v.1.4.0

![program cs - basic - visual studio code 2016-08-28 10 34 17](https://cloud.githubusercontent.com/assets/750257/18032825/fee199da-6d0a-11e6-9ce5-db6ebec78b24.png)
