### ISSUE TITLE
Problem with VSC program path (when update) and .vscode

### ISSUE THREAD

**Issue by ManPython** [Microsoft/vscode#20724]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. I instaled VSC on d:/VSC or e:/VSC
2. When updating VSC then have new instalation is created in C:\Program Files (x86)\Microsoft VS Code, not on d:/VSC or e:/VSC
3. The idea to install VSC on d:/VSC or e:/VSC is for some case of portable think for VSC as pendrive or cases of re-instaling all OS (then all is on d:/ or e:/ and no problem). But all plugins are on VSC on C:\Users\ManPython\.vscode and when c: partition is destroyed or formated, then must install again all extensions, etc.
- change path for .vscode (and live move/relocation with all files to other path) is important and usefull eg. next to main  VSC program files
- we can imagine 2 or more instances of VSC with other extensions or settings (but .vscode can't be one an in default path as C:\Users\ManPython\.vscode but other)

**Comment by joaomoreno** [comment]
I suggest to use the zip release. Also, you can use the `--user-data-dir` and `--extensions-dir` command line arguments to control where things go.

**Comment by ManPython** [comment]
OK, this is solution 

> --user-data-dir and --extensions-dir  

But I think that updating VSC to other path than VSC is instaled is bug/problem as in point 2.
For non zip VSC, and VSC zip doesn't have an function "check for update", soo it's hard to be in current unbuged version of VSC.
