### ISSUE TITLE
Gray bar suddenly appears above visual studio code??

### ISSUE THREAD

**Issue by dawiedevilliers** [Microsoft/vscode#20722]
![rrafyty](https://cloud.githubusercontent.com/assets/4988064/23021845/ad3bec9c-f456-11e6-87f5-4aa8f1e1ef3c.jpg)
![vs](https://cloud.githubusercontent.com/assets/4988064/23021860/c5e2d044-f456-11e6-813e-20f3ccc6ac98.PNG)

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Can you find steps to reproduce?

**Comment by dawiedevilliers** [comment]
Hi After a restart to the box it disappeared.

Will definitely try and let you know if i'm successful

**Comment by bpasero** [comment]
Closing for now until we got more info.
