### ISSUE TITLE
the has been stoped so i can not type any kind of text code even the file and the folder can not be used

### ISSUE THREAD

**Issue by Soso3354** [microsoft/vscode#207246]
ADD ISSUE DESCRIPTION HERE

Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by alexr00** [comment]
Closing as the issue is unclear.
