### ISSUE TITLE
make text to be selectable in output windows (specially in disassembly view window in c++ extesion)

### ISSUE THREAD

**Issue by FeelUsM** [microsoft/vscode#207233]
**Feature Request**

This is the disassembly view window in c++ extesion. 
![image](https://private-user-images.githubusercontent.com/49320365/289141529-7096080a-77b6-4939-aff1-502f73a9803d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5OTQwMDYsIm5iZiI6MTcwOTk5MzcwNiwicGF0aCI6Ii80OTMyMDM2NS8yODkxNDE1MjktNzA5NjA4MGEtNzdiNi00OTM5LWFmZjEtNTAyZjczYTk4MDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE0MTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZWJiNzBiY2VmMTdiYzNlYWE3YmYxZGRhZjcwYTM2MDZlMTI3NzEwM2VkNGQwODVmMWU3ZWZiZjI2MzQ5ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IfV0P-43g-4Vx0eF4LAct3a5h_k0a0-UCbIBVj_mMWY)

We can't select text in the disassembly view window.
This window cannot be implemented as a readonly text buffer for the reason described [here](https://github.com/microsoft/vscode-cpptools/discussions/12077#discussioncomment-8712321)
It would be convenient if you could select text visible on the screen and copy it.

**Comment by roblourens** [comment]
I don't think we should try to make the whole thing selectable, since it is virtualized. But we could add a "copy all" context menu item, which I would do as part of this issue to support a context menu: https://github.com/microsoft/vscode/issues/171548
