### ISSUE TITLE
git commit gets stuck without message.

### ISSUE THREAD

**Issue by Vishesh-Pandey** [microsoft/vscode#207285]
Does this issue occur when all extensions are disabled?: Yes - Always

- VS Code Version: 1.87.1 
- OS Version: Windows

Steps to Reproduce:

1. Open Visual Studio Code.
2. Navigate to a Git repository.
3. Make changes to a file in the repository.
4. Click on the commit button in the GUI version of Git in VS Code without adding any message. As shown in screenshot: 
![image](https://github.com/microsoft/vscode/assets/74998585/5f82f36a-5e3c-4deb-8c89-26d7453a992f)

5. Observe that the GUI version of Git commit gets stuck and keeps loading. As shown in example:
![image](https://github.com/microsoft/vscode/assets/74998585/85e30a53-d60d-41f2-868f-976e806cfe54)

Expected Behavior:
Either the Git commit action should complete quickly, or the commit button should be disabled if no commit message has been given.

**Comment by gjsjohnmurray** [comment]
Is https://github.com/microsoft/vscode/issues/168135#issuecomment-1340590009 help?
