### ISSUE TITLE
 blinking code

### ISSUE THREAD

**Issue by MrAlex6204** [Microsoft/vscode#20725]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.4.0-62-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.6.2|
|html-snippets|abusaidm|0.0.18|
|vscode-eslint|dbaeumer|1.2.2|
|python|donjayamanne|0.5.8|
|configure-c-compiling|ivomachado|0.2.1|
|MagicPython|magicstack|1.0.3|
|cpptools|ms-vscode|0.8.1|
|csharp|ms-vscode|1.5.3|
|debugger-for-chrome|msjsdiag|2.4.1|
|vscode-icons|robertohuertasm|4.2.0|
|whitespace|sandcastle|0.0.4|
|python|tht13|0.2.3|
|python-extended-snippets|tushortz|0.0.1|

---

Steps to Reproduce:
Some times when I edit python code, then I do a save
the code starts blinking
1. Edit python code
2. I press Ctrl + S (Save changes)

**Comment by joaomoreno** [comment]
Can you provide a screen recording?

**Comment by MrAlex6204** [comment]
Yest, you can get the screencast from this shared folder
https://drive.google.com/open?id=0B8C4ZkzFGwDpd0J6Uzk2UmlZeEk

**Comment by alexandrudima** [comment]
@MrAlex6204 Wow, that looks annoying. I can tell you what the blinking is:
* whenever the file changes on disk, we reload it
* whenever we reload the file, we retokenize it
* probably your machine is so fast in tokenizing that it appears as a flash.
* in reality, the file is painted without tokens, then tokenization starts in the background
* once tokenization reaches the lines in the viewport, the viewport is repainted with colors.

My best guess is that one of the Python extensions you have installed is somehow writing your file to disk, causing it to reload in the UI, causing the flashes. Can you perhaps try to disable some of the extensions and see if the flashing still occurs?

fyi @jrieken if you know something about the error message with linting on save

**Comment by DonJayamanne** [comment]
@alexandrudima 
>if you know something about the error message with linting on save 

It looks like this message is coming from a Python extension (https://github.com/tht13/Python-vscode/blob/9caf5feda93dea96db1d580822dc82b56924a79b/src/client/src/pythonMain.ts).

**Comment by alexandrudima** [comment]
@MrAlex6204 It appears that the error stems from an extension -- https://github.com/tht13/Python-vscode/blob/9caf5feda93dea96db1d580822dc82b56924a79b/src/client/src/pythonMain.ts#L72

![image](https://cloud.githubusercontent.com/assets/5047891/23270412/043d2aae-f9f4-11e6-856b-7f84f6fa9428.png)

I suggest to open an issue straight against that extension -- https://github.com/tht13/Python-vscode
