### ISSUE TITLE
TerminalChatController mutates disposed disposable store on window reload

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#207214]
<img width="819" alt="image" src="https://github.com/microsoft/vscode/assets/876920/dd4b817f-09ec-414c-a12b-b71af41852c9">

It happoens on window reload, might not be a big deal but it means there is a potential leak with how the code is written.

**Comment by Tyriar** [comment]
Fixed up a double dispose that looks like this on Thursday: https://github.com/microsoft/vscode/pull/207078 so this is likely fixed, ping me if you see it again.
