### ISSUE TITLE
PreLaunchTask first run does not complete

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#20734]
1. Generate a new TS-Extension with `yo code`
2. Open that extension in VSCode
3. Hit `F5` - notice how the preLaunchTask never finishes - the status bar indicator is always spinning
4. If I start debugging again the prelaunchTask will finish nicely now

Assigning to you since I know you are refactoring some things in the task framework and I did not touch any code on my end lately.

**Comment by dbaeumer** [comment]
@isidorn I can't reproduce this.

![cast](https://cloud.githubusercontent.com/assets/1931590/23059771/2150b50a-f4fb-11e6-976a-d4b918dbffbb.gif)

Any additional steps. Which version of code where you using?

**Comment by dbaeumer** [comment]
Works for me with 1.9.1 as well.

**Comment by isidorn** [comment]
Can no longer reproduce - sorry for the false alarm.
I was able to repro with yesterdays out of source. Seems to work fine now.
If I get it again will collect more details and reopen
