### ISSUE TITLE
Unchecking "Show welcome page on startup" has no effect

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#20739]
- VSCode Version: 1.9.1
- OS Version: Windows 10 Enterprise version 1607

Steps to Reproduce:

1. Open VSCode (`code .` anywhere)
2. It shows the welcome screen. Uncheck "Show welcome page on startup"
3. Close VSCode.
4. GOTO 1

**Comment by chrmarti** [comment]
@andy-ms Could you check if your settings (File > Preferences > User Settings) contain any syntax errors? Any errors in the console (Help > Toggle Developer Tools)?

**Comment by andy-ms** [comment]
Ah, my settings had a trailing comma.

**Comment by chrmarti** [comment]
Showing a corresponding message now (fixed with #18923).
