### ISSUE TITLE
Mouse support for integrated terminal in Windows not working

### ISSUE THREAD

**Issue by hamidb** [microsoft/vscode#207344]
Does this issue occur when all extensions are disabled?: Yes/No

Similar issue: [96058](https://github.com/microsoft/vscode/issues/96058) for macOS
Version: 1.78.2024022201 (user setup)
OS: Windows_NT x64 10.0.19045

I tried to use mouse events in the vscode integrated terminal without success. I explained the steps to reproduce below.
However I tested the feature successfully on a LINUX remote host. Also the feature works fine when working on standalone WSL terminal. Sounds like an issue with vscode on windows.

Steps to Reproduce:

1. In any terminal (tested with pwsh, wsl, cmd) open vim.
2. in vim enable mouse by :set mouse=a
3. :split and try to navigate between panels. It won't work
4. tested with tmux and it didn't work too

**Comment by meganrogge** [comment]
did this recently stop working for you?

**Comment by meganrogge** [comment]
You are using a very old version of VS Code. Pls try updating to see if it's been fixed
