### ISSUE TITLE
Copilot: Sorry, no response was returned.

### ISSUE THREAD

**Issue by knixer** [microsoft/vscode#207321]
Type: <b>Bug</b>

If I run a question for Copilot it creates a response and half-way stops and gives me the error message "Sorry, no response was returned."

VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (1.65GB free)|
|Process Argv|--crash-reporter-id 5ff0c530-6f70-4c1b-ba25-99139f530db7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.20.0
vscode-mjml|att|1.6.0
vscode-tailwindcss|bra|0.10.5
path-intellisense|chr|2.8.5
postcss|css|1.0.9
dart-code|Dar|3.84.0
flutter|Dar|3.84.0
vscode-eslint|dba|2.4.4
vscode-babel-coloring|dza|0.0.4
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.15
code-runner|for|0.12.1
copilot|Git|1.172.0
copilot-chat|Git|0.13.0
go|gol|0.41.1
rest-client|hum|0.25.1
graphql-for-vscode|kum|1.15.3
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.29.0
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.3
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
powershell|ms-|2024.0.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
wordcount|ms-|0.1.0
material-icon-theme|PKi|4.34.0
java|red|1.28.1
shopify-liquid|sis|4.0.1
html-preview-vscode|tht|0.2.5
vscode-counter|uct|3.4.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.13.5
vscode-java-debug|vsc|0.56.2
vscode-java-dependency|vsc|0.23.5
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
78248357:30976999
ccp1r6:30958156
dsvsc020:30976470

```

</details>

**Comment by Deepakvrma14** [comment]
Had faced same issue, the issue is regarding your firewall and network, try killing vs code and switching to mobile network and try again and it'll work ... Worked for me

**Comment by digitarald** [comment]
[Related Copilot service incident](https://www.githubstatus.com/incidents/7f4bllnv3h1n).
