### ISSUE TITLE
vscode not recognizing .csproj file

### ISSUE THREAD

**Issue by AAndharia** [Microsoft/vscode#20733]
- VSCode Version: 1.9.1
- OS Version: win

Steps to Reproduce:

1. have installed web api start project using this command 
yo aspnet webapi MyFirstASPNetCoreWebAPI

I've followed these links to create web api project template
https://docs.microsoft.com/en-us/aspnet/core/client-side/yeoman?#building-projects-with-yeoman
https://github.com/OmniSharp/generator-aspnet

2. open the project in vscode

3. It shows there are unresolved dependancies from .csproj. Please execute the restore command to continue. clicking restore shows this error in "Output"

error: Invalid input 'd:\Projects\vs-code-web\WebAPI1\WebAPI1.csproj'. The file type was not recognized.
Done: 1.

**Comment by joaomoreno** [comment]
Please file an issue in https://github.com/OmniSharp/omnisharp-vscode/issues
