### ISSUE TITLE
Committing to git without a commit message hangs the commit.

### ISSUE THREAD

**Issue by sauntheninja2** [microsoft/vscode#207396]
Type: <b>Bug</b>

1) Press the source control message
2) Press the commit button without entering anything in the message field
3) You can see the commit hangs at that point all you can do is exit visual studio code and restart it again.

VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (8.37GB free)|
|Process Argv|--crash-reporter-id 3c5f134d-0c77-4209-b2a3-705a2cedaf38|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
cform|aws|0.0.24
go|gol|0.41.1
terraform|has|2.29.4
elixir-ls|Jak|0.20.0
csdevkit|ms-|1.3.10
csharp|ms-|2.18.16
vscode-dotnet-runtime|ms-|2.0.2
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.2.3
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
powershell|ms-|2024.0.0
remote-explorer|ms-|0.4.3
vscode-yaml|red|1.14.0
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by sauntheninja2** [comment]
**Without typing a message in the commit**

Uploading attempt2.mp4…

**Comment by lszomoru** [comment]
Pressing the "Commit" button when there is no commit message specified will trigger the flow to use the editor as the commit message editor as described [here](https://code.visualstudio.com/updates/v1_69#_author-commit-message-using-an-editor). If that is not what you are seeing please share the recording. Thank you!
