### ISSUE TITLE
Installation of "the 'SQL' extension" recommended, not available.

### ISSUE THREAD

**Issue by ylg** [Microsoft/vscode#20732]
- VSCode Version: 1.9.1
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Open a .sql file
2. Observe recommendation notice.
3. Click "Show Recommendations"

<img width="724" alt="screen shot 2017-02-16 at 07 22 48" src="https://cloud.githubusercontent.com/assets/76547/23024768/cad1d4da-f418-11e6-9aca-d813fad3cb84.png">

At the top of the window, the recommendation notice comes down with the message: "It is recommended to install the 'SQL' extension." Buttons presented are "Show Recommendations" "Don't Show Again" and "Close". Clicking Show Recommendations presents a list of extensions that does not include any titled "SQL", the closest would be the Microsoft SQL Server-specific "mssql" extension. Searching all extensions for the substring "SQL" shows no extension with the title of simply "SQL".

If the intent of the notice is to encourage the user to select one of the SQL-related extensions, e.g., mssql, PL/SQL, vscode-database, then the Show button should take the user to a list of extensions tagged as SQL related, and the wording of the notice should be corrected, as "the 'SQL' extension" means one specific, so named extension.

If there is/was a specific extension simply called "SQL" that is not available at this moment, the notice could be removed or linked directly to that extension. Even if the extension is not available, it would be a clearer user-experience to click Show… and be taken to a "this extension is no longer available" page.

**Comment by joaomoreno** [comment]
This is fixed in Insiders. Sorry for the hassle.

**Comment by ylg** [comment]
Duplicate of?

**Comment by joaomoreno** [comment]
#19613

**Comment by eschurma** [comment]
As of June this has not been fixed.

**Comment by joaomoreno** [comment]
It is fixed. The extension is now called `mssql`. I've updated code on our side to not show `SQL` any more but `mssql`.
