### ISSUE TITLE
Search Exclude switch button not work

### ISSUE THREAD

**Issue by lvchangye** [microsoft/vscode#207314]
Type: <b>Bug</b>

When Search some file, enable or disable exclude setting not work.I Must delete all words in input area of files to exclude every time . 

VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.46GB (14.34GB free)|
|Process Argv|--folder-uri file:///d%3A/xygame --crash-reporter-id 99f907cc-0300-4302-b497-58588e262bea|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nginx-conf|ahm|0.3.2
vscode-json|and|1.5.2
duplicate-file|axe|0.1.2
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
doxdocgen|csc|1.4.0
dbclient-jdbc|cwe|1.3.4
vscode-mysql-client2|cwe|7.0.6
vscode-eslint|dba|2.4.2
rust-syntax|dus|0.6.1
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|10.1.0
vscode-npm|fkn|3.3.0
copilot|Git|1.172.0
copilot-chat|Git|0.13.0
copilot-labs|Git|0.17.1121
go|gol|0.39.1
vue-snippets|hol|1.0.4
better-cpp-syntax|jef|1.17.2
svg|joc|1.5.3
svn-scm|joh|2.17.0
cmake-language-support-vscode|jos|0.0.9
solidity|Jua|0.0.165
ts-debug|kak|0.0.6
i18n-ally|lok|2.12.0
git-graph|mhu|1.30.0
theme-monokai-pro-vscode|mon|1.2.1
vscode-docker|ms-|1.27.0
vscode-language-pack-zh-hans|MS-|1.83.2023101109
csharp|ms-|2.8.23
vscode-dotnet-runtime|ms-|1.8.1
black-formatter|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.20.0
vscode-pylance|ms-|2023.10.50
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.315.1
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
makefile-tools|ms-|0.7.0
powershell|ms-|2023.8.0
remote-explorer|ms-|0.4.1
nginx-formatter|ray|0.0.13
java|red|1.24.0
ethereum-remix|Rem|0.0.12
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1815
lua|sum|3.7.0
even-better-toml|tam|0.19.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.0
vscode-maven|vsc|0.42.0
vscode-icons|vsc|12.6.0
volar|Vue|1.8.27
vscode-typescript-vue-plugin|Vue|1.8.27
luaide-lite|wel|0.3.1
chatgpt-china|Whe|8.6.0
vscode-nginx|wil|0.7.2
filepath|xam|0.8.1
clang-format|xav|1.9.0
vscode-archive|YuT|0.5.1
vscode-proto3|zxh|0.5.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470
jchc7451:30973076

```

</details>

**Comment by andreamah** [comment]
Can you provide a screen recording for this?

**Comment by lvchangye** [comment]
> Can you provide a screen recording for this?

Sorry, I misunderstood. The button on the right side of the exclude input frame can only control the part within the settings, not the input area.
