### ISSUE TITLE
F5 yields `Debug adapter process has terminated unexpectedly (Extension host shut down)`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#207317]
Round about once a day debugging fails like this: `Debug adapter process has terminated unexpectedly (Extension host shut down)`. I don't see anything reasonable in the logs but I am happy to provide more informations. 

Steps aren't reliable but basically

* open vscode workspace
* select F5 to run "VS Code" launch config

**Comment by deepak1556** [comment]
Can you check for any crash dumps in the application owning the debug adapter process when this happens

1) `Developer: Open User Data Folder`
2) Go to `Crashpad/completed`, there might be a bunch of unrelated crash dumps try to match the one closest based on the timestamp

**Comment by jrieken** [comment]
@deepak1556 this is from `/Users/jrieken/Library/Application Support/Code - Insiders/Crashpad/completed/7d3bf4d9-b6f6-4a29-9df5-22af0b3acf72.dmp` ⬇️ I didn't find anything inside `/Users/jrieken/.vscode-oss-dev` which is where I initially checked for this

[7d3bf4d9-b6f6-4a29-9df5-22af0b3acf72.dmp](https://github.com/microsoft/vscode/files/14571178/7d3bf4d9-b6f6-4a29-9df5-22af0b3acf72.dmp)

**Comment by deepak1556** [comment]
Crash stack matches https://github.com/microsoft/vscode/issues/206630 which is in node module loading for dynamic imports. Fix was landed for this today, not sure if this was the direct cause for the debug adapter crash but can you check again with tomorrow's insiders.

**Comment by jrieken** [comment]
This seems to be working now. I am fine with closing this.
