### ISSUE TITLE
Could not open shitificate.png after download

### ISSUE THREAD

**Issue by ChukwukaNmadu** [microsoft/vscode#207350]
ADD ISSUE DESCRIPTION HERE

"Error loading webview: Error: Could not register service worker Security Error: Failed to register a service worker. The provided scriptURL (...) violates the content security policy" message is received whenever I try to open shirtificate.png 

Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
Embedder: codespaces

**Comment by mjbvz** [comment]
Where are you running this codespace? 1.85 seems like an outdated version

**Comment by ChukwukaNmadu** [comment]
I am running it on cs50.dev Apparently, that is the issue, because when I migrated my codespace to VSC, it could be opened right there.

**Comment by mjbvz** [comment]
Thanks for checking. Closing as external. Please try filing an issue against cs50
