### ISSUE TITLE
Tests: sometimes misses decoration

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#207336]
When a test does not begin with `test`:

![image](https://github.com/microsoft/vscode/assets/900690/756cbe5f-c72e-403f-adce-a257c952431a)

**Comment by connor4312** [comment]
Yes, we figure out what tests are through [AST parsing](https://github.com/microsoft/vscode-selfhost-test-provider/blob/d9ca0c812a5ccfbfa4f76bd21dc75b297ef0617b/src/sourceUtils.ts#L16). The parser does not interpret things so they aren't found.

I don't want to build an interpreter but common usages could be added to that
