### ISSUE TITLE
Newlines in suggestions in github copilot are ignored and displayed

### ISSUE THREAD

**Issue by yamachu** [microsoft/vscode#207311]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.88.0-insider (12fc36731bd0424dfc53e9f456ac793c1eb1d6d0)
- OS Version: Darwin arm64 23.2.0

Steps to Reproduce:

1. Enable GitHub Copilot
2. Edit the code such that multi-line suggestions occur

https://github.com/microsoft/vscode/assets/1955233/ce9bc197-fa6b-4323-b97b-6f3947112f9c

This is an understandable example, but when writing a for expression in Scala code, for example, it becomes very difficult to see if a right-hand side proposal is made.

https://github.com/microsoft/vscode/assets/1955233/8d8d59cd-bf01-444a-8bd6-661378ff9ebd

---

6c19c003574b02afc604c0c1c471b1441b33a3d3 is works expected

**Comment by hediet** [comment]
Fixed, insiders build should go out in 1-2 hours.

**Comment by PerFrivik** [comment]
![image](https://github.com/microsoft/vscode/assets/94360401/257c8bab-4bbf-4069-8b79-0d52e372cf6c)
For anyone wondering, I found it :smile:
