### ISSUE TITLE
Implicit Project Config: check JS setting does not respect module resolution

### ISSUE THREAD

**Issue by paulmillr** [microsoft/vscode#207342]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.1
- OS Version: macos 14.3.1

I am library developer and found a bug in vscode resolution. Steps to Reproduce:

1. Ensure vscode setting `"js/ts.implicitProjectConfig.checkJs": true,`

2. Create 

```sh
mkdir case
cd case
npm init -y
npm install micro-eth-signer@0.8.0
```

3. Create `index.mjs` with following contents: `import { decodeTx } from 'micro-eth-signer/abi';`
4. VSCode won't read package.json `exports` of the module, where `/abi` is properly defined: [package.json#L35](https://github.com/paulmillr/micro-eth-signer/blob/b44527d4565879c36f5be1e443826f11e179657e/package.json#L35-L38)
5. The error does not happen if tsconfig / ts file is used. I'm talking about default configuration with js.

**Comment by mjbvz** [comment]
This is unrelated to checkJS. You likely want to create a `jsconfig` and either change `module` or make sure `moduleResolution` is set to something like `bundler`

**Comment by paulmillr** [comment]
@mjbvz I believe it is related.

Specifically, the **default** implicit `moduleResolution` is "nodeNext", but its behavior is very different from jsconfig with nodeNext.

So something is wrong in default implicit module resolution.
