### ISSUE TITLE
Proposal: Change order of completions of CSS properties.

### ISSUE THREAD

**Issue by katainaka0503** [Microsoft/vscode#20738]
When I write css properties, sometimes I feel annoyed at the order of completion.

For example, I type `borr` and Tab with the intentention of being converted to `border-radius:`,
but it is converted to `border-bottom-left-radius:`.
I think it's better to be converted to `border-radius` in this case.

I think this is because completions are ordered by natural order of property name.

So, I think it's better for completions to be sorted by `(numberOfChunksSeparatedByHyphen, nameOfProperty)`.

By this,
border-bottom-left-radius -> (4, "border-bottom-left-radius")
border-radius -> (2, "border-radius")
so, border-radius is given priority,
and in other cases, shorter properties are given priority.

**Comment by aeschli** [comment]
@joaomoreno Sounds like a general completion item ordering request.
