### ISSUE TITLE
Option to Retain Newline Types in Text Search Patterns

### ISSUE THREAD

**Issue by ritikramuka** [microsoft/vscode#207331]
**Overview:** 
Currently, in the implementation of text search functionality, newline characters in search patterns are standardized to a single format. While this ensures consistency, it may not always be desirable, especially when users or extensions need to preserve the original newline types for compatibility or specific requirements.

**Proposal:**
I propose adding an option to the TextSearchOptions interface to retain the original newline types in search patterns. This option will give users and extensions the flexibility to choose whether newline characters should be standardized or preserved.

**Details:**

1. Interface Enhancement: Extend the TextSearchOptions interface to include a boolean property named retainNewlines.

```
export interface TextSearchOptions extends SearchOptions {
    // Other properties...
    retainNewlines?: boolean;
}
```

2. Usage: Users or extensions can set retainNewlines: true to preserve original newline types in search patterns.

3. Implementation: Adjust the handling of newline characters in the text search logic based on the value of retainNewlines.

**Benefits:**

Flexibility: Provides users and extensions with the flexibility to control how newline characters are handled in search patterns.
Compatibility: Ensures compatibility with systems or requirements that rely on specific newline types.
User Experience: Improves the user experience by accommodating diverse text search needs and preferences.
Conclusion:
The addition of this option will enhance the text search functionality by offering more control over newline character handling. It addresses the need for preserving original newline types in search patterns, improving compatibility and user flexibility.

Thank you for considering this feature request.

**Comment by eleanorjboyd** [comment]
Since this was filed in March going to close as it has been 60 days. Thanks!
