### ISSUE TITLE
terminal chat response is `[object Object]`

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#207368]
not sure what the repro steps are yet. 

![Image](https://github.com/microsoft/vscode/assets/29464607/110747d5-f831-4986-a2c7-f97f2a3ee9c6)

**Comment by rzhao271** [comment]
I can still reproduce the issue.
Query: "blah blah blah blah baa baa bla bla blah"

**Comment by Tyriar** [comment]
@roblourens something going wrong with rendering offtopic:

<img width="622" alt="Screenshot 2024-03-26 at 2 50 18 PM" src="https://github.com/microsoft/vscode/assets/2193314/69bf5f2d-d364-4fe2-8c37-1fab4d8c284a">

**Comment by roblourens** [comment]
Looks like this is the only case where your participant returns a markdown chunk, and this isn't stringified correctly. I did a minimal fix but a better change would be to refactor this to pass markdown chunks as-is all the way down into ChatModel
