### ISSUE TITLE
Accident opening of multiple debug sessions

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#20736]
- VSCode Version: 1.10.0-insider
- OS Version: Win 10 x64

Steps to Reproduce:

1. Go to debug menu, and press 'Start debugging' at least twice (or double click F5).
2. Same debug configuration is launched multiple times.

Expectation:

No possibility to run the same configuration (accidentally) as there is an alternative feature which is called compound which lets the user do that. @isidorn

**Comment by michelkaporin** [comment]
Verified, works now. Thank you @isidorn.

**Comment by isidorn** [comment]
@michaelchiche great. Adding verified tag.
