### ISSUE TITLE
Embedder createTerminal API doesn't work for Codespaces anymore

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#207372]
https://github.com/microsoft/vscode/pull/159666 changed `TerminalMainContribution` to move to `LifecyclePhase.Restored` but this caused a feature for Codespaces to stop working where the terminal will start streaming in the init logs before the workbench has fully loaded. Ideally we would start it up on Starting only on remote, if we can't do that we need to move it back to Starting in the meantime.

cc @bpasero @osortega

**Comment by bpasero** [comment]
We know if we are connected to a remote from the environment service via probing for `remoteAuthority`.

**Comment by Tyriar** [comment]
We don't have access to services at workbench contrib registration do we?

https://github.com/microsoft/vscode/blob/f933441a9e17555bb06fa98a29c199e559b4bf9b/src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts#L83

**Comment by bpasero** [comment]
@Tyriar no, but you could have 1 eager workbench contrib that depends on the environment service to decide if a second thing should get instantiated or not.

**Comment by Tyriar** [comment]
Marked verified, only @osortega can properly verify it

**Comment by osortega** [comment]
@Tyriar this seems to still be failing, the terminal does not show up until the codespace is fully created and the workbench initialized

**Comment by Tyriar** [comment]
Verified by @osortega 🎉
