### ISSUE TITLE
hanging on NodeJS

### ISSUE THREAD

**Issue by DiscreteProgramming** [microsoft/vscode#207323]
Type: <b>Bug</b>

when pressing Ctrl+F5, nodejs won't start running just hanging.

VS Code version: Code - Insiders 1.88.0-insider (12fc36731bd0424dfc53e9f456ac793c1eb1d6d0, 2024-03-11T05:47:58.870Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by connor4312** [comment]
Please grab https://github.com/microsoft/vscode-js-debug#nightly-extension for the fix

**Comment by DiscreteProgramming** [comment]
you didn't understand the problem.

in earlier versions this bug wasn't found!

**Comment by connor4312** [comment]
Yes, I understand, however "run without debugging" is still actually handled by the debugger extension, and the nightly version of the extension has the fix you need
