### ISSUE TITLE
CPU has been drained by PHP7.0 process

### ISSUE THREAD

**Issue by siderlan** [Microsoft/vscode#20731]
The CPU usage is about 100% when the editor is started.

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.4.0-62-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|format-php|Kasik96|1.1.2|
|material-icon-theme|PKief|1.3.3|
|githistory|donjayamanne|0.1.5|
|prettier-vscode|esbenp|0.8.0|
|php-intellisense|felixfbecker|1.1.1|
|classic-asp|ilich8086|0.0.2|
|php-symbols|linyang95|2.1.0|
|wordpress-snippet|tungvn|1.1.2|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. I started the editor and I ran the linux top command
2. The usage of CPU is close to 100% and the responsible for that is the php7.0 process
3. When I close the editor the php7.0 process is terminated and the CPU usage backs to normal

I do not know whether it is an editor issue or some extension.

**Comment by roblourens** [comment]
Is this still an issue? I know php-intellisense is the most likely offender here, and it has undergone a lot of work the past few months.
