### ISSUE TITLE
Terminal chat: No accept primary button

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#207489]
![image](https://github.com/microsoft/vscode/assets/2193314/d930e6d2-114b-4a34-9cc2-5cbcf268d45a)

**Comment by Tyriar** [comment]
I think this is because they've moved inline into the code block, but we should have the big buttons to align with the editor experience.

**Comment by meganrogge** [comment]
I believe by regenerate you mean `insert`?

**Comment by Tyriar** [comment]
This one:

<img width="255" alt="Screenshot 2024-03-12 at 12 15 51 PM" src="https://github.com/microsoft/vscode/assets/2193314/00d2c8e2-2749-45ea-8d28-cff511764748">

**Comment by meganrogge** [comment]
We don't currently support that /haven't yet

**Comment by meganrogge** [comment]
AFAICT, we've not had that before, but I can add it 👍

**Comment by Tyriar** [comment]
Moved the regenerate part to https://github.com/microsoft/vscode/issues/207583
