### ISSUE TITLE
Hide languages from the language selector

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/vscode#207406]
Some language IDs are registered only to help with features related to another language ID. The user is not supposed to ever select this language ID for a file.

Examples:

- https://github.com/vuejs/language-tools/blob/0f5dfcec3365518c4edb0c0b32397597786ca0e1/extensions/vscode/package.json#L112-L123
- https://github.com/XadillaX/vscode-language-viml/blob/74cf16021fef7a627f2c753c6fea6dbfbdb19141/package.json#L133-L135
- `raw` (builtin to VSCode to support markdown and Latex if I understand correctly)

It would be nice if these languages are hidden from the language selector. For example, the language definition in `package.json` could have a property `"hidden": true`.

**Comment by RedCMD** [comment]
`languageId` isn't required for injections
only `scopeName` is required

**Comment by remcohaszing** [comment]
I didn’t know. In that case it’s not an issue with VSCode. :)

In that case do you know what the `raw` language means?

**Comment by RedCMD** [comment]
it comes from the [vscode-jupyter](https://github.com/Microsoft/vscode-jupyter) extension
https://github.com/microsoft/vscode-jupyter/blob/bc14e07839f60377bf12f144b9b4c0418dbc188c/package.json#L1978
