### ISSUE TITLE
add support for global options in tasks.json for tasks with locally defined commands

### ISSUE THREAD

**Issue by dolphy01** [Microsoft/vscode#20740]
It would be helpful to be able to define globally applied options to tasks in tasks.json, even for tasks that define their own command locally. I am told this is currently not supported; if a task defines its command locally then it will not inherit any global options.

I am proposing that global options are applied to all tasks defined in tasks.json, with the following rules. This is described from the key/value standpoint of the "env" parameter, but the same logic would apply to "cwd" as well:

1. if any key is defined globally, and no override of that key is defined locally to a task, the global value is applied
2. if any key is defined locally, and no global definition of that key exists, the local value is applied
3. if any key is defined both globally and locally, the local value of that key "overrides" the global, and is applied

**Comment by alexr00** [comment]
Not sure when it happened, but this exists. You can define cwd for a whole tasks file, then override it in individual tasks.
