### ISSUE TITLE
Timeout in "TestSynchronizer - Manual Sync remote is accepted if last sync state does not exists in server"

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#207468]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=261800
Changes: https://github.com/Microsoft/vscode/compare/13a1951...d750a76

Similar failure in TaskSynchronizer:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=261921&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=c01b9029-2b08-503e-eba8-b45cf5956c33

https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=258318

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=262087&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=c01b9029-2b08-503e-eba8-b45cf5956c33

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=262734&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=c01b9029-2b08-503e-eba8-b45cf5956c33

**Comment by connor4312** [comment]
Similar failure in TaskSynchronizer:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=261921&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=c01b9029-2b08-503e-eba8-b45cf5956c33

**Comment by connor4312** [comment]
Similar failure: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=262087&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=c01b9029-2b08-503e-eba8-b45cf5956c33

**Comment by connor4312** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=262734&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=c01b9029-2b08-503e-eba8-b45cf5956c33

**Comment by Tyriar** [comment]
@sandy081 can you please skip this test, it's not useful until it no longer flakes and is disruptive.
