### ISSUE TITLE
Can't log into microsoft account unless I run VS Code as Administrator

### ISSUE THREAD

**Issue by cosmoKenney** [microsoft/vscode#207478]
Type: <b>Bug</b>

On the bottom-left of the Activity bar there is an "Accounts" menu button. 
If I run VS Code as an adminstrator, then I am automatically logged in to Microsoft using credentials I previously entered. However when I do not run VS Code as an administrator, I get the following error when I click the "Sign In to Sync Settings" menu item: 

**Timed out waiting for authentication provider to register**

I've tried rebooting my PC and that has not helped. 

VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (14.37GB free)|
|Process Argv|. --crash-reporter-id 34121dd8-1191-4960-be01-bd88936a5214|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|17.2.2
vscode-firefox-debug|fir|2.9.10
json-to-ts|Mar|1.7.5
csharp|ms-|2.18.16
vscode-dotnet-runtime|ms-|2.0.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30986171
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30981708
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by TylerLeonhardt** [comment]
Can you follow these steps so that we can get more information on what's going on?

* Trigger the sign in
* _Wait for the issue to happen..._
* Open the Output pane (ctrl+shift+u I think on Windows)
* drop in this issue he contents of the following:
  * `Microsoft Authentication` Output channel
  * `Window` Output channel
  * `Main` Output channel

**Comment by cosmoKenney** [comment]
I'm going to close this issue. I cannot reproduce at the moment. I think the main difference is that I changed the way VS 2022 launches VS Code at startup via npm task runner explorer.
And, I will be switching to a new laptop in the next week or so, so I don't want to continue to troubleshoot this.
