### ISSUE TITLE
regression: opened file navigation with arrow key no longer works

### ISSUE THREAD

**Issue by ghiscoding** [microsoft/vscode#207496]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0-insider (2024-03-12)
- OS Version: Windows 10 - 22H2 (19045.3930)

Steps to Reproduce:

1. have a few opened files in your editor
2. do Ctrl+Tab
3. try to use ArrowUp/Down to switch file but it no longer works and does nothing (only observer with insider builds)

> **Note** the long pause in the animated gif is when I try to use arrow keys, it works with Ctrl-Tab as shown below but it's not convenient

![Code_-_Insiders_sfIXWGc1p7](https://github.com/microsoft/vscode/assets/643976/fec22d9b-0f73-42c4-b7bd-318d22edfbc7)

This problem started couple days ago in the Insider program, the stable version is currently unimpacted and I hope it won't either in the future. I use this ArrowUp/Down **a lot** when switching opened files, so I hope that this will be fixed shortly. The only alternative I know for now is to use the mouse but it's not as efficient. I did not find any similar opened issue but in my case it happens on all 3 computers that I use.

Not sure if some of these PRs could introduce the regression?
PR #207028

**Comment by bpasero** [comment]
Thanks, I think we should try to fix regressions in quick pick before releasing stable given the amount of usage.

**Comment by TylerLeonhardt** [comment]
Totally agree. I'll have a fix for this this week
