### ISSUE TITLE
 Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#20757]
Issue Id: <b>f51b01b6-2932-7b1c-50ca-3083daae476b</b><br /><br />*Versions* <br />- 1.9.1<br />*Stack* <br />Error: Overlapping ranges are not allowed!<br />[/vs/editor/common/model/editableTextModel.ts#L318:10](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/common/model/editableTextModel.ts#L318:10)<br />[/vs/editor/common/model/editableTextModel.ts#L272:15 (_applyEdits)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/common/model/editableTextModel.ts#L272:15 (_applyEdits))<br />[/vs/editor/common/model/editStack.ts#L72:26 (applyEdits)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/common/model/editStack.ts#L72:26 (applyEdits))<br />[/vs/editor/common/model/editableTextModel.ts#L174:30 (pushEditOperation)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/common/model/editableTextModel.ts#L174:30 (pushEditOperation))<br />[/vs/editor/common/model/editableTextModel.ts#L89:15 (_pushEditOperations)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/common/model/editableTextModel.ts#L89:15 (_pushEditOperations))<br />[/vs/editor/common/commonCodeEditor.ts#L675:13 (pushEditOperations)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/common/commonCodeEditor.ts#L675:13 (pushEditOperations))<br />[/vs/workbench/api/node/mainThreadEditorsTracker.ts#L389:20 (executeEdits)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/workbench/api/node/mainThreadEditorsTracker.ts#L389:20 (executeEdits))<br />[/vs/workbench/api/node/mainThreadEditors.ts#L293:46 (applyEdits)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/workbench/api/node/mainThreadEditors.ts#L293:46 (applyEdits))<br />[/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L275:39 (handle)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/platform/extensions/common/ipcRemoteCom.ts#L275:39 (handle))<br />

**Comment by alexandrudima** [comment]
An extension calls `textEditor.edit` and builds up an invalid edit. I'm not sure why the stack shows up in error telemetry

**Comment by kof3r** [comment]
I was repeatedly getting this error while trying to refactor a variable name in a python file. I noticed that my file didn't have an empty new line at the bottom, when I added one the refactoring completed successfully. Not sure if it's somehow related.

**Comment by alexandrudima** [comment]
The fix on our side should be to throw as early as possible. i.e. when the extension builds up such an invalid edit.
