### ISSUE TITLE
The pwsh terminal display incorrectlly when installed starship

### ISSUE THREAD

**Issue by SethWen** [microsoft/vscode#207549]
Does this issue occur when all extensions are disabled?: Yes

When installing [starship](https://starship.rs/)，commad in pwsh terminal always displays an extra first letter on start of the line，while the command executed is right.
![vscode-bug](https://github.com/microsoft/vscode/assets/16742990/5ed53fe8-f042-43e1-9698-da24e047d160)

After tested, when I enable the os option for starship config, the pwsh terminal display incorrectlly.
```
[os]
disabled = false
```

However I know't think it is a problem of starship. Because everything is ok in windows terminal pwsh and the historical vscode version.

- VS Code Version: 
``` 
Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631
```
- OS Version: 
```
windows11  10.0.22631.3155
```
 - starship Version:
```
starship 1.17.1
branch:master
commit_hash:
build_time:2024-01-02 18:35:11 +00:00
build_env:rustc 1.75.0 (82e1608df 2023-12-21),stable-x86_64-pc-windows-msvc
```

**Comment by Tyriar** [comment]
This is because of the windows symbol you added to the front, removing that should fix it. We're currently discussing a related issue in https://github.com/xtermjs/xterm.js/issues/4969

/duplicate
