### ISSUE TITLE
Duplicate selection action/shortcut

### ISSUE THREAD

**Issue by madcampos** [microsoft/vscode#2075]
Other editors provide a shortcut to duplicate the current selection, or if nothing is selected duplicate the whole line (actually the actions of `copyLinesDownAction` and `copyLinesUpAction`).

**Comment by alexandrudima** [comment]
@madcampos I am not sure I've seen this, can you please give a more detailed description. Would this action do exactly what a `Ctrl+C` followed by a `Ctrl+V` would do?

**Comment by madcampos** [comment]
@alexandrudima if there is text selected, yes, it behaves just like a `Ctrl+C` followed by a `Ctrl+V` at the text cursor's position, if there is no text selected it duplicates the whole line, like `copyLinesDownAction`.
For example the [Brackets](http://brackets.io/) shortcut for this is `Ctrl+D`.
Atom offers just the `copyLinesDownAction` behavior with the `Ctl+Shift+D` shortcut.

As an example:
> this line of text|

After the action has taken turns to:
> this line of text|
> this line of text

The selection (represented by bold):
> this __line__| of text

After the action becomes:
> this __line__|line of text

**Comment by PedroNorte** [comment]
Specifically useful because it lets you duplicate a line without losing the contents of your clipboard!  The alternative of Ctrl+C then Ctrl+V overwrites your clipboard.

**Comment by Lambdac0re** [comment]
+1

**Comment by ginolon** [comment]
Like sublime text `[cmd]+D`.

How to?

**Comment by schurig** [comment]
+1

**Comment by alexandrudima** [comment]
@PedroNorte specifically for line duplication, we have two: 

https://code.visualstudio.com/docs/customization/keybindings#_basic-editing

Here are the Windows keybindings:
![image](https://cloud.githubusercontent.com/assets/5047891/13863873/76bd7760-ec9d-11e5-8265-c10d03424646.png)

**Comment by farfromrefug** [comment]
+1 copyLinesDownAction and copyLinesUpAction are not the same!
what we want is ```copySelectionDownAction```  and ```copySelectionUpAction```

**Comment by SeinopSys** [comment]
Yes, please!

**Comment by iambibhas** [comment]
Yes please! I miss this dearly.

**Comment by bealdav** [comment]
yes thanks

**Comment by martinsuchan** [comment]
Just like @madcampos mentioned, this is a very useful shortcut. In VS2015 with ReSharper it's under `Ctrl+D`, see [here](https://www.jetbrains.com/help/resharper/2016.3/Coding_Assistance__Duplicate_Line_Block.html).
There are some extensions available for VSCode emulating this behavior, but they are overwriting the current clipboard when executed and they are not working if there is nothing selected. In this case the current line should be duplicated.

**Comment by vanikin** [comment]
Just found what extention which I use also overwriting clipboard.
After quick search I found extention which does not https://marketplace.visualstudio.com/items?itemName=lafe.contextualduplicate

**Comment by kivervinicius** [comment]
+1 please, on WebStorm is Ctrl+D too;

**Comment by kynatro** [comment]
+1 On this too. Being able to duplicate multiple lines without loosing clipboard is a valuable piece in my workflow. Not to mention simply being able to duplicate only _part_ of a line is very useful.

**Comment by miguelpragier** [comment]
+1 for ctrl+d, duplicating the selected text.
In Notepad++, if you select from the middle to the EOL, it duplicates to the next line.
For me it's the best behaviour.

**Comment by zo** [comment]
Yes, duplication can be really useful.
Mostly for not losing clipboard, but also for editing inline lists (arrays, function arguments...)

I also use this a lot in sublime text to add a condition in an if/else

![2017-07-15-043736_3000x2160_scrot](https://user-images.githubusercontent.com/518711/28235944-7e7f1a2c-6919-11e7-8c62-cb453c6bf567.png)
`Ctrl+Shift+D`
![2017-07-15-043746_3000x2160_scrot](https://user-images.githubusercontent.com/518711/28235945-7e820142-6919-11e7-9ee9-c21ae40c4d2f.png)

And like madcampos said, if there is no selection the same action/shortcut should duplicate the line.

**Comment by yukulele** [comment]
https://marketplace.visualstudio.com/items?itemName=ctlajoie.DuplicateSelection

**Comment by vidaaudrey** [comment]
I just found that shift+option+down actually does the job.

**Comment by abdulmanan7** [comment]
this extension help me 
https://marketplace.visualstudio.com/items?itemName=lafe.contextualduplicate
it give you sublime like behaviour

**Comment by blunket** [comment]
for anyone finding the ContextualDuplicate extension above, there are some issues even with the extension, fortunately they are fixed in a PR by https://github.com/lafe/ContextualDuplicate/pull/5

**Comment by denmasyarikin** [comment]
+1

**Comment by kkapsner** [comment]
I also missed this feature and therefore created an extension that just provides the two missing actions ( copySelectionForwardAction and copySelectionBackwardAction): https://marketplace.visualstudio.com/items?itemName=kkapsner.duplicateselection

@vscode-dev-team: please look at the code and if it's good enough include it in the core. If it's not good enough: tell me what's wrong with it.

**Comment by samdeesh** [comment]
As mentioned by many ..we can do a ctr+c & then a ctyrl+v but it changes the clipboard..

**Comment by trailstrider** [comment]
> I just found that shift+option+down actually does the job.

Definitely not doing the job.   Try the example with adding an if else branch.   Its copying the entire lines, not the selections.

**Comment by zo** [comment]
This feature implementation is quite simple, here is the one I made for the lafe/ContextualDuplicate extension:
https://github.com/lafe/ContextualDuplicate/blob/95c5fcc45405773576bd561f3ae75d564e35ea79/src/extension.ts

But this extension is unmaintained and the pull request was never merged...

Currently I'm using @kkapsner's one, that mimic SublimeText and Notepad++ behaviour very well
https://marketplace.visualstudio.com/items?itemName=kkapsner.duplicateselection

But I still feel this should be in core

**Comment by hhoweson** [comment]
5 days shy of 3 years after this was posted and still nothing. I moved to vscode from brackets and absolutely love it! The one thing I miss is the lack of this shortcut, every other code editor has it, why doesn't vscode?

**Comment by andig** [comment]
For sake of other readers, I've created https://marketplace.visualstudio.com/items?itemName=andig.sublime-cmd-shift-d to get the sublime `Cmd-Shift-D` behaviour after https://github.com/Microsoft/vscode-sublime-keybindings/issues/100 has not seen any update.

**Comment by jacksbox** [comment]
+1 for `Duplicate Selection`, the current `Copy Line Down/Up` also duplicates lines in which nothing (except the `return`) is selected, thats not practical

**Comment by alexandrudima** [comment]
There is now a new action called "Duplicate Selection". It can be bound in `keybindings.json` e.g.

```
{
  "key": "ctrl+shift+d",
  "command": "editor.action.duplicateSelection",
  "when": "editorTextFocus && !editorReadonly"
}
```

**Comment by pedzed** [comment]
@alexandrudima What does it do when no selection is made? It should duplicate the entire line the cursor is on.

**Comment by alexandrudima** [comment]
@pedzed Yes, that's what it does.

**Comment by pedzed** [comment]
Amazing! Thank you so much. I will wait until it gets into the stable release. As for now, I am using the extension [Contextual Duplicate](https://marketplace.visualstudio.com/items?itemName=lafe.contextualduplicate).

If it works the same, I can finally remove the extension.

**Comment by andig** [comment]
I feel the shortcuts should switch places as ctrl-shift-d includes ctrl-d when there is no selection.

**Comment by alexandrudima** [comment]
@andig You can easily customize shortcuts on your machine. The new command does not ship with any default shortcut, so it needs to be bound manually.

**Comment by andig** [comment]
> You can easily customize shortcuts on your machine. 

@alexandrudima I realize that but would like to suggest to replace the default `editor.action.copyLinesDownAction` with this new one lest people don't find this new gem.

**Comment by trailstrider** [comment]
I'd second that.  Much more useful.

**Comment by pedzed** [comment]
(@trailstrider Your reply by mail contains private information. Better redact it out.)

**Comment by alexandrudima** [comment]
> I realize that but would like to suggest to replace the default `editor.action.copyLinesDownAction` with this new one lest people don't find this new gem.

I appreciate that suggestion, but unfortunately I will not be tweaking any default keyboard shortcuts in the foreseeable future, unless there is a really big problem. The reason is that we will very likely end up irritating tens of thousands of users who maybe got used to the old keybinding doing the old thing. I have learned (the hard way) that annoying so many folks for not a strong reason is not wise.

So there will be no changes to the default keybindings. We can however change the sublime keymap extension to incorporate this new command, since the purpose of that extension is to have keybindings/commands as similar to sublime, etc.
