### ISSUE TITLE
typescript server restarts ever 5 minutes

### ISSUE THREAD

**Issue by c58** [microsoft/vscode#207553]
Type: <b>Bug</b>

typescript server restarts ever 5 minutes, started to happen after updating to the latest vscode version

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:57.520Z)
OS version: Darwin arm64 23.3.0
Modes:
Remote OS version: Linux x64 5.4.0-171-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 9975d517-f859-4def-9c08-a220771a0391|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev.artemevs.com|
|OS|Linux x64 5.4.0-171-generic|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (23 x 3668)|
|Memory (System)|22.91GB (2.16GB free)|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
esbuild-problem-matchers|con|0.0.3
vscode-graphql-syntax|Gra|1.3.4
vscode-drawio|hed|1.6.6
Kotlin|mat|1.7.1
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
owb-layout-editor|und|0.0.0
vscode-tailwindcss|bra|0.10.5
ruff|cha|2024.16.0
vscode-eslint|dba|2.4.4
githistory|don|0.6.20
gitlens|eam|14.9.0
EditorConfig|Edi|0.16.4
html-preview-vscode|geo|0.2.5
vscode-pull-request-github|Git|0.82.0
go|gol|0.41.1
vscode-docker|ms-|1.29.0
debugpy|ms-|2024.2.0
flake8|ms-|2023.10.0
pylint|ms-|2023.10.1
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
code-spell-checker|str|3.0.1
even-better-toml|tam|0.19.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30986171
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d6fi2104:30959263
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by c58** [comment]
Hard to say, after executing "Kill VS Code server on host" and re-connecting to the host it seemed back to normal operation even with the same version of VS Code.

**Comment by c58** [comment]
I'm closing this since the issue stopped happenning and may be relateded with the server enriroment where the vscode remote is running.
