### ISSUE TITLE
 Cannot read property 'getLinesContent' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#20754]
Issue Id: <b>0f67410f-f01e-158b-91c8-cba9128e69e6</b><br /><br />*Versions* <br />- 1.9.1<br />*Stack* <br />TypeError: Cannot read property 'getLinesContent' of undefined<br />[/vs/workbench/parts/html/browser/htmlPreviewPart.ts#L180:107 (getLinesContent)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/workbench/parts/html/browser/htmlPreviewPart.ts#L180:107 (getLinesContent))<br />[/vs/base/common/eventEmitter.ts#L314:9 (func)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/eventEmitter.ts#L314:9 (func))<br />[/vs/base/common/eventEmitter.ts#L299:3 (safeInvoke1Arg)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/eventEmitter.ts#L299:3 (safeInvoke1Arg))<br />[/vs/base/common/eventEmitter.ts#L216:8 (_emitEvents)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/eventEmitter.ts#L216:8 (_emitEvents))<br />[/vs/editor/common/model/textModel.ts#L284:8 (emit)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/common/model/textModel.ts#L284:8 (emit))<br />[/vs/editor/common/model/textModel.ts#L357:7 (_emitContentChanged2)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/common/model/textModel.ts#L357:7 (_emitContentChanged2))<br />[/vs/workbench/api/node/mainThreadDocuments.ts#L260:9 (setValueFromRawText)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/workbench/api/node/mainThreadDocuments.ts#L260:9 (setValueFromRawText))<br />[/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L275:39 (handle)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/platform/extensions/common/ipcRemoteCom.ts#L275:39 (handle))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L231:25 (invokeHandler)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/platform/extensions/common/ipcRemoteCom.ts#L231:25 (invokeHandler))<br />

**Comment by mjbvz** [comment]
Fixed by 	2481b6e
