### ISSUE TITLE
 c._currentCancelInput is not a function

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#20756]
Issue Id: <b>7994ddfc-78d7-8deb-726a-0737397eb382</b><br /><br />*Versions* <br />- 1.9.1<br />*Stack* <br />TypeError: c._currentCancelInput is not a function<br />[/vs/editor/contrib/rename/browser/renameInputField.ts#L136:10 (_currentCancelInput)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/contrib/rename/browser/renameInputField.ts#L136:10 (_currentCancelInput))<br />[/vs/base/common/event.ts#L217:12 (apply)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/event.ts#L217:12 (apply))<br />[/vs/base/common/eventEmitter.ts#L314:9 (func)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/eventEmitter.ts#L314:9 (func))<br />[/vs/base/common/eventEmitter.ts#L182:4 (safeInvoke1Arg)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/eventEmitter.ts#L182:4 (safeInvoke1Arg))<br />[/vs/base/common/eventEmitter.ts#L201:8 (_emitToSpecificTypeListeners)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/eventEmitter.ts#L201:8 (_emitToSpecificTypeListeners))<br />[/vs/base/common/eventEmitter.ts#L216:8 (_emitEvents)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/eventEmitter.ts#L216:8 (_emitEvents))<br />[/vs/editor/common/commonCodeEditor.ts#L962:12 (emit)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/common/commonCodeEditor.ts#L962:12 (emit))<br />[/vs/base/common/eventEmitter.ts#L314:9 (func)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/eventEmitter.ts#L314:9 (func))<br />[/vs/base/common/eventEmitter.ts#L190:3 (safeInvoke1Arg)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/eventEmitter.ts#L190:3 (safeInvoke1Arg))<br />[/vs/base/common/eventEmitter.ts#L196:8 (_emitToBulkListeners)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/eventEmitter.ts#L196:8 (_emitToBulkListeners))<br />

**Comment by jrieken** [comment]
stack trace indicates that `this` in undefined here

```
let onCursorChanged = () => {
	if (!Range.containsPosition(where, this._editor.getPosition())) {
		this._currentCancelInput();
	}
};
```
