### ISSUE TITLE
 Uncaught Error

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#20755]
Issue Id: <b>c3b42d06-5420-1a64-b48b-35d2d8dabb9f</b><br /><br />*Versions* <br />- 1.9.1<br />*Stack* <br />Error<br />[/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L176:30](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L176:30)<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1209:0 (onError)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1209:0 (onError))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L901:0 (_notify)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L901:0 (_notify))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1041:0 (_run)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1041:0 (_run))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L53:5 (errorDispatch)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/workbench/parts/debug/node/v8Protocol.ts#L53:5 (errorDispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L136:6 (clb)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/workbench/parts/debug/node/v8Protocol.ts#L136:6 (clb))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L104:11 (dispatch)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/workbench/parts/debug/node/v8Protocol.ts#L104:11 (dispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L41:8 (handleData)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/workbench/parts/debug/node/v8Protocol.ts#L41:8 (handleData))<br />    at emitOne (events.js:96:13)<br />

**Comment by isidorn** [comment]
Dup of #20758
