### ISSUE TITLE
Debugger Stop button has to be clicked a few times when reload features are enabled

### ISSUE THREAD

**Issue by zmarffy** [microsoft/vscode#207532]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0-insider (Universal)
- OS Version: macOS Sonoma 14.3.1

Steps to Reproduce:

1. Clone [this repo](https://github.com/zmarffy/vscode-bugreport-1)
2. Run `docker-compose up --build`
3. Attach the debugger
4. Try to detach the debugger

This is also occurring in a project of mine that utilizes Docker Compose's `watch` functionality, but I was not able to reproduce it on my barebones example app provided here. Directly related to https://github.com/microsoft/vscode/issues/96730.

**Comment by NickSpaghetti** [comment]
I am having the same issue having to tripple click to stop debugging.

**Comment by roblourens** [comment]
Please file this on the debugpy extension repo, thanks
