### ISSUE TITLE
Text to speech support for the visually impaired

### ISSUE THREAD

**Issue by mikulobams** [microsoft/vscode#207625]
Type: <b>Feature Request</b>

I will like there to be a better integration for text to speech functionality

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by meganrogge** [comment]
this exists already. you can install the VS Code speech extension and the copilot chat extension to experiment with this. You can use commands such as `start dictation in the editor` to test it out.

**Comment by mikulobams** [comment]
Thank you for your response. I will do just that.
