### ISSUE TITLE
Sticky scroll sets `line-height` for the sticky row even though I set `setRowLineHeight: false` in the ListOptions

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#207649]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. See how this is set: 
https://github.com/microsoft/vscode/blob/ca19ca605b3a2f4e2a87f4d787905861be6ffd19/src/vs/platform/quickinput/browser/quickInputTree.ts#L541
2. See this:
`<div class="monaco-tree-sticky-row monaco-list-row focused" data-index="0" data-parity="even" id="list_id_3_0" role="option" aria-label="extensions.json, extensions.json" aria-selected="false" aria-expanded="true" style="top: 0px; height: 24px; line-height: 24px;">`
Notice the line height is set to 24px.

This causes my item to jiggle when I start scrolling:

https://github.com/microsoft/vscode/assets/2644648/331503fc-13ff-4472-bac5-bbc87d7faffa

if I get rid of that `line-height` setting, the behavior works as expected. No jittering

https://github.com/microsoft/vscode/blob/ca19ca605b3a2f4e2a87f4d787905861be6ffd19/src/vs/base/browser/ui/tree/abstractTree.ts#L1667

**Comment by benibenj** [comment]
Thanks for reporting, was unaware this existed. I now consider the `setRowHeight` and `setRowLineHeight` options
