### ISSUE TITLE
Custom code snippet not working in react

### ISSUE THREAD

**Issue by harrington101** [Microsoft/vscode#20764]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|0.10.18|

---

Steps to Reproduce:

1. Create a .js file
2. Create a custom code snippet inside of javascript.json such as the one below:
```
"Target Blank": {
	"prefix": "_b",
	"body": [
		"_blank\" rel=\"noopener noreferrer\" "
	],
	"description": "Prevent new tab from having access to original window."
}
```
3. In a react javascript file with the .js extension, inside of the
```
render() { 
     return ( 
          <THIS AREA> 
     ) 
}
```
try to type a custom made code snippet (_b). It won't work. 
3. Outside of  return area type _b. It will work. (inserts _blank" rel="noopener noreferrer").

**Comment by jrieken** [comment]
Interesting... I see the snippet when I hit F1 > Insert Snippet but not when I press Ctrl+Space
