### ISSUE TITLE
Icon and background of search bar is wrong color

### ISSUE THREAD

**Issue by xuduogui** [microsoft/vscode#207674]
Type: <b>Bug</b>

① use a theme with Office black. (this is ok)
② change my theme to Office Light. (this is not ok, some areas are light, but some are black too.)

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|39.79GB (16.37GB free)|
|Process Argv|--crash-reporter-id f9456273-091b-48bd-b3a9-1374d8b9f031|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (110)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.4.2
project-manager|ale|12.7.0
vscode-django|bat|1.15.0
gltf-vscode|ces|2.4.0
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
vscode-sql-beautify|cla|0.3.23
EnglishChineseDictionary|Cod|1.1.0
dbclient-jdbc|cwe|1.3.4
vscode-redis-client|cwe|7.1.0
vscode-code-review|d-k|1.33.1
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.54.0
vscode-eslint|dba|2.4.4
vscode-notes|dio|1.2.1
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
redis|Dun|1.4.0
gitlens|eam|14.9.0
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.102
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
todo-tree|Gru|0.0.226
markdown-image|han|1.1.40
vscode-drawio|hed|1.6.6
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
svg|joc|1.5.3
vscode-peacock|joh|4.2.2
vscode-map-preview|jum|0.6.0
ts-debug|kak|0.0.6
vscode-sshfs|Kel|1.26.1
vsc-python-indent|Kev|1.18.0
vscode-gutter-preview|kis|0.30.0
MetaJump|met|1.4.4
dotenv|mik|1.0.1
file-downloader|min|1.0.13
vue-volar-extention-pack|Mis|2.0.7
huile8|mqy|1.0.0
vscode-docker|ms-|1.29.0
vscode-language-pack-zh-hans|MS-|1.87.2024031309
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
onedrive-browser|ms-|0.0.1
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
vscode-typescript-next|ms-|5.5.20240313
vsliveshare|ms-|1.0.5918
cordova-tools|msj|2.6.7
color-highlight|nau|2.5.0
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.34.0
material-product-icons|PKi|1.7.0
excalidraw-editor|pom|3.7.3
vscode-css-peek|pra|4.4.1
quicktype|qui|12.0.46
java|red|1.28.1
vscode-commons|red|0.0.6
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
git-commit-plugin|red|1.2.1
LiveServer|rit|5.7.9
any-rule|rus|0.3.18
trailing-spaces|sha|0.4.1
markdown-preview-enhanced|shd|0.8.12
vscode-scss-formatter|sib|3.0.0
guides|spy|0.9.3
autoimport|ste|1.5.4
code-spell-checker|str|3.0.1
sass-indented|syl|1.8.29
pdf|tom|1.2.2
errorlens|use|3.16.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.0
explorer|vit|0.4.1
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.53.0
vscode-java-debug|vsc|0.56.2
vscode-java-dependency|vsc|0.23.5
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0
vscode-spring-boot-dashboard|vsc|0.13.1
vscode-spring-initializr|vsc|0.11.2
vscode-icons|vsc|12.7.0
volar|Vue|2.0.6
jinja|who|0.0.8
change-case|wma|1.0.0
vue|Wsc|1.0.26
txt-syntax|xsh|0.2.2
pretty-ts-errors|Yoa|0.5.3
dictionary-completion|yzh|1.3.1
markdown-all-in-one|yzh|3.6.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
8082a590:30971561
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470
jchc7451:30973076

```

</details>

**Comment by aeschli** [comment]
`Office Light` comes from an extension. You have to file this here: https://github.com/powertech-center/vscode-themes/issues
