### ISSUE TITLE
Terminal chat widget in task terminals

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#207646]
I keep seeing this show up in my build terminal after awhile, but no consistent repro steps

<img width="332" alt="image" src="https://github.com/microsoft/vscode/assets/323878/7b012360-8098-42ce-b7a6-50ef0331d7a9">

**Comment by Tyriar** [comment]
@meganrogge could this not be fixed yet or just not in insiders?

**Comment by meganrogge** [comment]
it's probably fixed in tomorrow's insider's
