### ISSUE TITLE
Inconsistent syntax highlighting for shell case statements

### ISSUE THREAD

**Issue by slycordinator** [microsoft/vscode#207666]
Type: <b>Bug</b>

In a shell script case statement:
1) when the case pattern and command are placed on separate lines, the highlighter correctly recognizes the commands/arguments and colors them appropriately; they get placed into appropriate scopes.

2) When the case pattern and command are placed on the same line, the command and arguments are not recognized as such and are simply placed in a scope for a case clause body, which has no special highlighting.

Example:
```
#!/bin/sh
case "$1" in
case1)
cmd1 cmd1_arg1 cmd1_arg2 cmd1_arg3;;
case2) cmd2 cmd2_arg1 cmd2_arg2 cmd2_arg3;;
esac
```

On line 4:
* cmd1 is placed in the "entity.name.command.shell" textmate scope, with its own foreground color (for me '#DCDCAA')
* cmd1_arg1, cmd1_arg2, and cmd1_arg3 are each placed into "string.unquoted.argument.shell" scope with a foreground color set (for me '#CE9178')

On line 5:
* Everything on this line displays with the default foreground color (for me '#D4D4D4')
This is because " cmd2 cmd2_arg1 cmd2_arg2 cmd2_arg3"  is placed into the "meta.scope.case-clause-body.shell" scope, which has no foreground color set.

Results:
command highlighting happens only when command placed on its own line

Expected results:
Commands/arguments to be highlighted regardless of where they occur in a case statement

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz (12 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.23GB free)|
|Process Argv|--crash-reporter-id 55116356-9d3a-4bbf-a90e-d385b50ead6b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
powershell|ms-|2024.0.0
shellcheck|tim|0.37.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30986171
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30981707
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470
gee8j676:30988843

```

</details>

**Comment by slycordinator** [comment]
Same thing happens for keyword highlighting.

```
#!/bin/sh
#shellcheck disable=SC2034
case "$1" in
	i) id="$OPTARG";;
	*)
esac

case "$1" in
	i)
		id="$OPTARG";;
	*)
esac
```

On line 4:
" id" is placed into the meta.scope.case-clause-body.shell texmate scope, which has no foreground color set (so it displays with the default ('#D4D4D4')

On line 10, "id" is placed into the variable.other.assignment.shell scope and is highlighted as a variable (for me set to '#9CDCFE')

**Comment by RedCMD** [comment]
should move the report to the upstream repo https://github.com/jeff-hykin/better-shell-syntax

![image](https://github.com/microsoft/vscode/assets/33529441/76026152-22c1-4e1e-bdeb-d43436f0550c)
![image](https://github.com/microsoft/vscode/assets/33529441/48da4988-1a20-433c-8456-b00c87c4f6dc)

**Comment by alexr00** [comment]
👍 moved to https://github.com/jeff-hykin/better-shell-syntax/issues/80

**Comment by slycordinator** [comment]
How is this an "upstream issue"? vscode has support for syntax highlighting for shell scripts and has this inconsistency.

The fact that an extension (that the user doesn't have installed) covers it better is a nonsequitur.

**Comment by RedCMD** [comment]
VSCode uses that extension as the built-in Shell script grammar

**Comment by slycordinator** [comment]
> VSCode uses that extension as the built-in Shell script grammar

Ah. And the installable extension is a newer version of it. I see.

**Comment by alexr00** [comment]
Just updated VS Code to use the latest from https://github.com/jeff-hykin/better-shell-syntax
