### ISSUE TITLE
Unable to setup Maui Android Workflow

### ISSUE THREAD

**Issue by mctainsh** [microsoft/vscode#207656]
Type: <b>Bug</b>

When executing the followiong command

dotnet build -t:InstallAndroidDependencies -f:net8.0-android -p:AndroidSdkDirectory="$HOME/Library/Android/sdk" -p:JavaSdkDirectory="/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home" -p:AcceptAndroidSDKLicenses=True 

 I get te following warning
 
 
MSBuild version 17.9.6+a4ecab324 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.85/tools/Xamarin.Installer.Common.targets(12,3): warning : Android component "tools" is obsolete, please install "cmdline-tools" [/Users/bvm437/Maui/T1/T1.csproj::TargetFramework=net8.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.85/tools/Xamarin.Installer.Common.targets(12,3): warning : Trying to fallback to "tools"... [/Users/bvm437/Maui/T1/T1.csproj::TargetFramework=net8.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.85/tools/Xamarin.Installer.Common.targets(12,3): warning : Dependency `platforms;android-34` should have been installed but could not be resolved. You can attempt to install it with: `/Users/bvm437/Library/Android/sdk/cmdline-tools/11.0/bin/sdkmanager --install "platforms;android-34"` [/Users/bvm437/Maui/T1/T1.csproj::TargetFramework=net8.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.85/tools/Xamarin.Installer.Common.targets(12,3): warning : Dependency `build-tools;34.0.0` should have been installed but could not be resolved. You can attempt to install it with: `/Users/bvm437/Library/Android/sdk/cmdline-tools/11.0/bin/sdkmanager --install "build-tools;34.0.0"` [/Users/bvm437/Maui/T1/T1.csproj::TargetFramework=net8.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.85/tools/Xamarin.Installer.Common.targets(12,3): warning : Dependency `platform-tools` should have been installed but could not be resolved. You can attempt to install it with: `/Users/bvm437/Library/Android/sdk/cmdline-tools/11.0/bin/sdkmanager --install "platform-tools"` [/Users/bvm437/Maui/T1/T1.csproj::TargetFramework=net8.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.85/tools/Xamarin.Installer.Common.targets(12,3): warning : Dependency `cmdline-tools;11.0` should have been installed but could not be resolved. You can attempt to install it with: `/Users/bvm437/Library/Android/sdk/cmdline-tools/11.0/bin/sdkmanager --install "cmdline-tools;11.0"` [/Users/bvm437/Maui/T1/T1.csproj::TargetFramework=net8.0-android]

Build succeeded.

/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.85/tools/Xamarin.Installer.Common.targets(12,3): warning : Android component "tools" is obsolete, please install "cmdline-tools" [/Users/bvm437/Maui/T1/T1.csproj::TargetFramework=net8.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.85/tools/Xamarin.Installer.Common.targets(12,3): warning : Trying to fallback to "tools"... [/Users/bvm437/Maui/T1/T1.csproj::TargetFramework=net8.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.85/tools/Xamarin.Installer.Common.targets(12,3): warning : Dependency `platforms;android-34` should have been installed but could not be resolved. You can attempt to install it with: `/Users/bvm437/Library/Android/sdk/cmdline-tools/11.0/bin/sdkmanager --install "platforms;android-34"` [/Users/bvm437/Maui/T1/T1.csproj::TargetFramework=net8.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.85/tools/Xamarin.Installer.Common.targets(12,3): warning : Dependency `build-tools;34.0.0` should have been installed but could not be resolved. You can attempt to install it with: `/Users/bvm437/Library/Android/sdk/cmdline-tools/11.0/bin/sdkmanager --install "build-tools;34.0.0"` [/Users/bvm437/Maui/T1/T1.csproj::TargetFramework=net8.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.85/tools/Xamarin.Installer.Common.targets(12,3): warning : Dependency `platform-tools` should have been installed but could not be resolved. You can attempt to install it with: `/Users/bvm437/Library/Android/sdk/cmdline-tools/11.0/bin/sdkmanager --install "platform-tools"` [/Users/bvm437/Maui/T1/T1.csproj::TargetFramework=net8.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.85/tools/Xamarin.Installer.Common.targets(12,3): warning : Dependency `cmdline-tools;11.0` should have been installed but could not be resolved. You can attempt to install it with: `/Users/bvm437/Library/Android/sdk/cmdline-tools/11.0/bin/sdkmanager --install "cmdline-tools;11.0"` [/Users/bvm437/Maui/T1/T1.csproj::TargetFramework=net8.0-android]
    6 Warning(s)
    0 Error(s)

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:57.520Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|36.00GB (1.29GB free)|
|Process Argv|--crash-reporter-id fa081640-0e81-4da3-9f82-c95627839e4e --crash-reporter-id fa081640-0e81-4da3-9f82-c95627839e4e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.29.0
csdevkit|ms-|1.4.29
csharp|ms-|2.22.3
dotnet-maui|ms-|0.9.5
vscode-dotnet-runtime|ms-|2.0.2
vscodeintellicode-csharp|ms-|0.1.26
code-spell-checker|str|3.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30986170
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30981708
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by yevgeny-sotnikov** [comment]
I have same error

**Comment by rzhao271** [comment]
Hi all, could you file this issue to [dotnet/maui](https://github.com/dotnet/maui)? I do not believe this issue is specific to VS Code.
