### ISSUE TITLE
large gap in terminal between tab and text

### ISSUE THREAD

**Issue by Xen192** [microsoft/vscode#207659]
I can't seem to remove the large gap between the tab and terminal text which i was able to do in 1.86 and previous versions
![image](https://github.com/microsoft/vscode/assets/35037446/abce23ee-f07c-4d37-a859-499682a5636a)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2
- OS Version: Manjaro KDE 23.1.3

Steps to Reproduce:
1. Simply open the terminal in vscode

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed
