### ISSUE TITLE
Build failed: Timeout finding the uninstall button

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#207698]
Error: Timeout: get element '.extension-editor .monaco-action-bar .action-item:not(.disabled) .extension-action.uninstall' after 20 seconds.

Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=262449
Changes: https://github.com/Microsoft/vscode/compare/37c50e0...49968b3

**Comment by sandy081** [comment]
Seems like extension installation has failed because of invalid vsix. I will add a retrial in this case - try to install extension again.
