### ISSUE TITLE
Syntax theme color control for comments / documentation conventions

### ISSUE THREAD

**Issue by gmattie** [Microsoft/vscode#20767]
For every built-in color theme with Visual Studio Code, the assigned color for comments ... 

```
//Default Dark+ Theme
{
	"scope": "comment",
	"settings": {
		"foreground": "#608b4e"
	}
}
```
... is being overridden by keywords associated with documentation conventions (JSDoc, etc), such as...

```
//Default Dark+ Theme
{
	"scope": "storage.type",
	"settings": {
		"foreground": "#569cd6"
	}
}
```

Example:

![capture](https://cloud.githubusercontent.com/assets/933921/23041637/8b69b93e-f463-11e6-8b55-a3c05f63da54.PNG)

What key/value can be added to the theme files, either .json defaults or TextMate theme files, so that the color of comments remains intact.

**Comment by aeschli** [comment]
You might want to check out the section 'Descendant selectors' from https://manual.macromates.com/en/scope_selectors.
With that you can say that 'comment storage.type' with be the comment color.

We don't plan to do that for the default themes. IMO having coloring inside comments is the wanted behaviour.

**Comment by Neutrino-Sunset** [comment]
"IMO having coloring inside comments is the wanted behaviour"

Sounds daft to me. What's the point of defining a color for comments at all if it is going to be overridden by everything else?

**Comment by gmattie** [comment]
Since the new version of VSCode has editor customization overrides in the User Settings, adding the following code will color comments gray when the Visual Studio color theme is Default Dark or Dark+, but it also works for most of the other built in themes as well. 

```
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "scope": [
                "comment",
                "comment storage.type",
                "comment variable",
                "comment support.variable", 
                "comment support.class",
                "comment support.type",
                "comment entity.name.type",
                "comment entity.name.class",
                "comment keyword.operator"
            ],
            "settings": {
                "foreground": "#666666"
            }
        }
    ]
}
```
