### ISSUE TITLE
Vscode can only log in to Microsoft accounts and cannot switch to GitHub accounts

### ISSUE THREAD

**Issue by star9710** [microsoft/vscode#207672]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
![image](https://github.com/microsoft/vscode/assets/108052715/0c9223b6-2769-40b7-9fdc-58fc66d2400b)

![7e2845401f0b3179b725b720939ffc2](https://github.com/microsoft/vscode/assets/108052715/7997b62a-eb04-44d4-bc8b-91eef29cfd14)

2. 
![c0f6cfedcad3e9fb5cebe5d940a1e13](https://github.com/microsoft/vscode/assets/108052715/0e81db54-6b35-4439-b30d-f8bea91737e0)

**Comment by star9710** [comment]
Click “使用GitHub登录”button，figure 3 will appear

**Comment by sandy081** [comment]
To switch account for settings sync you should turn off and turn on settings sync again - https://code.visualstudio.com/docs/editor/settings-sync#_switching-accounts
