### ISSUE TITLE
Test: accessible view chat codeblock actions

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#207637]
Refs #199119

- [x] Windows @joyceerhl 
- [x] macOS @joaomoreno 
- [x] anyOS @justschen 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23207637%0A%0A&assignees=meganrogge)

---

Screen reader users can inspect panel chat responses in the accessible view by focusing the chat response and using `alt+f2`. 

Now, users can apply code block actions from within the accessible view when their cursor is within a code block. These actions and keybindings are discoverable in the accessibility help dialog via `alt+f1`. 

To verify:
- Run a chat request in the panel chat that yields one or more code blocks
- Use `alt+f2` to open the accessible view
- Use `alt+f1` to see the commands that can be taken, the highlighted ones below are new (note https://github.com/microsoft/vscode/issues/207638)
- Configure keybindings for these and try the default ones, if any, and verify they work as expected.

![Image](https://github.com/microsoft/vscode/assets/29464607/f12b452d-9844-4b0e-9a0f-e7725db1d581)

**Comment by justschen** [comment]
@meganrogge after `alt+f2` and `alt+f1` (on mac `fn + alt + f2/f1`), I see the two accessibility help windows, and the commands to apply code block actions. but when trying  to insert, I get these errors:

for ctrl + enter:
![Screenshot 2024-03-24 at 11 01 02 PM](https://github.com/microsoft/vscode/assets/54879025/f2d318f5-273a-4426-b008-bb476bf2a030)

for ctrl + option + enter, no notification in vs code, but in Voiceover same error:
![Screenshot 2024-03-24 at 11 00 51 PM](https://github.com/microsoft/vscode/assets/54879025/a78b0260-7f05-4396-9565-2d8f457372fc)

wondering if there's an issue with my setup?

**Comment by meganrogge** [comment]
@justschen a gif would help

**Comment by justschen** [comment]
screen recording here!
https://github.com/microsoft/vscode/assets/54879025/97f70efb-9115-4871-a935-f6cdc3c0a53a

**Comment by meganrogge** [comment]
Oh I see, thanks for the gif. You need to be in the accessible view, not the accessibility help dialog, when using those keybindings. The help dialog simply describes the actions which can be taken when in the accessible view. @justschen

**Comment by justschen** [comment]
@meganrogge ah makes sense. running into the same thing in the accessible view popup:

https://github.com/microsoft/vscode/assets/54879025/7e9160b2-07a9-471a-8264-f6d809f27af2

**Comment by meganrogge** [comment]
I can reproduce, thanks. related https://github.com/microsoft/vscode/issues/205401

**Comment by justschen** [comment]
didn't realize it was a competing keybinding, but works nicely besides that 👍
