### ISSUE TITLE
"Blotchy" Theme Background

### ISSUE THREAD

**Issue by dahjelle** [Microsoft/vscode#20766]
- VSCode Version: 1.9.1
- OS Version: macOS Sierra, 10.12.3 (16D32)

Steps to Reproduce:

1. Use the built-in Solarized Light theme.
2. Open a new window.
3. Observe that the background color is not consistent. (See screenshot. EDIT: Note that I added the dashed lines to make the distinction slightly more clear.) This isn't a theme issue, as the [theme clearly claims the color should be #FDF6E3](https://github.com/Microsoft/vscode/blob/master/extensions/theme-solarized-light/themes/Solarized-light.tmTheme#L13).

![vscode-theme](https://cloud.githubusercontent.com/assets/156557/23039585/992743e4-f453-11e6-9b12-81380d89163c.png)

Even more oddly, I get different results on each of my 3 monitors: on my Retina screen, no problems. On my largest external screen, my main screen, I get the attached. On my 3rd monitor, I see the issue, but the incorrect color is #FDF6E4. Note that the 2 external screens are not retina.

I didn't look in detail through all themes, but a quick glance seemed to indicate at least the Red theme was also affected.

**Comment by dahjelle** [comment]
This also happens when rendering code in the window, where there might be several rectangles on screen of the "different" color. It appears to never appear behind code, but I'm not 100% sure of that.

**Comment by joaomoreno** [comment]
@bpasero I know we have a duplicate, I just couldn't find it...

**Comment by bpasero** [comment]
#12473
