### ISSUE TITLE
Go to File..., but keep the dialog open to quickly open multiple files

### ISSUE THREAD

**Issue by ackvf** [microsoft/vscode#207631]
Hello, working with files with certain level of code duplication, it is often needed to open several of those at once, to apply or compare changes between multiple files. This is especially common in a monorepo.

In this case, I need to open all `tsconfig.json` files to add new `include` item.

![image](https://github.com/microsoft/vscode/assets/2313018/5b016e49-6891-4bd2-8d5b-6fea2dd5acd4)

What I imagine happening is that with this dialog open, I will press a certain key combination, say <kbd>Shift</kbd>+<kbd>Enter</kbd> and the file will open in the previously focused editor without taking focus, allowing me to navigate down within the Go to File... dialog, choosing another file and repeating the steps.

**Comment by TylerLeonhardt** [comment]
@ackvf you can do this by hitting `right arrow`

https://github.com/microsoft/vscode/assets/2644648/b519c2b8-be04-4f40-a206-1654822df4de

**Comment by ackvf** [comment]
Oh my goodness, thanks!
