### ISSUE TITLE
I cannot open any files from Windows Explorer by double click or Open With > VS Code

### ISSUE THREAD

**Issue by anthony-brien** [Microsoft/vscode#20765]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|EditorConfig|EditorConfig|0.3.4|
|LogFileHighlighter|emilast|1.1.1|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|output-colorizer|IBM|0.0.10|
|vscode-icon-theme|jtlowe|1.4.0|
|cpptools|ms-vscode|0.10.1|
|csharp|ms-vscode|1.7.0|
|material-icon-theme|PKief|1.3.3|
|trailing-spaces|shardulm94|0.2.11|
|perforce|slevesque|1.0.0|
|markdown-pdf|yzane|0.1.6|

---

Steps to Reproduce:

1. Right click a json file, Open with > VS Code
2. Nothing happens. If VS Code is not running, it will start, but not open the json file.

**Comment by joaomoreno** [comment]
Check #20448. Please reinstall VS Code and reset it to open the file extensions.
