### ISSUE TITLE
Access is denied error when installing vs code

### ISSUE THREAD

**Issue by hasnatfahim12** [microsoft/vscode#207675]
Does this issue occur when all extensions are disabled?: Yes/No

![image](https://github.com/microsoft/vscode/assets/56993151/e17b31f7-3db1-46fe-8ae9-0b5b21be74af)

Facing this exact same issue - https://github.com/microsoft/vscode/issues/140244

I tried to install it again by renaming my .vscode folder in my User folder. But still not fixed. Gives no other info as well.

**Comment by blair683** [comment]
have you found a solution

**Comment by rzhao271** [comment]
Hi @hasnatfahim12, are you trying to install VS Code while running as an administrator?
If so, could you try using the System Installer from the [Downloads](https://code.visualstudio.com/Download) page instead?
