### ISSUE TITLE
[Bug] VSCode doesn't remember "Run Code" for running program with run button. Always showing output in Powershell Terminal.

### ISSUE THREAD

**Issue by fahim9778** [microsoft/vscode#207683]
Does this issue occur when all extensions are disabled?I didn't check. But since this is extension related, I can't reproduce while extensions are disabled.

-     Version: 1.87.2 (system setup)
-     Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
-     Date: 2024-03-08T15:20:17.278Z
-     Electron: 27.3.2
-     ElectronBuildId: 26836302
-     Chromium: 118.0.5993.159
-     Node.js: 18.17.1
-     V8: 11.8.172.18-electron.0
-     OS: Windows_NT x64 10.0.19045

**Describe the bug**
VS Code Code running dropdown doesn't remember the last preferred option, the "Run Code" option (by Code Runner), to output for any programming files. It is always defaulting to the "Powershell" terminal instead of the "Output" tab. 

**To Reproduce**

1. Select "Run Code" for running Python Files
2. Click the "Run" button, now it runs in Powershell terminal, not in "Output" tab.

**Actual behavior**
If I select "Run Code" button from the drop-down, VSCode doesn't seem to remember "Run Code" with code runner. Rather it's shows "Run Python file" or "Run Java" as the last selection. And the output goes in "Terminal" tab.

**Expected behavior**
VScode should remember (it was fine even yesterday), which option I chose last to run code.

Screenshots
Video demo:
https://github.com/formulahendry/vscode-code-runner/assets/26436023/880ddc9a-ecc7-4498-9249-3417982dbbf7

**Comment by roblourens** [comment]
Please file thsi on the Code Runner extension

**Comment by GazzaliBRACU** [comment]
@formulahendry please see this. I have been bouncing back and forth to create issues here and  there. Once the extension author tells me it's VSCode problem and then VSCode says it's extension problems. 🙃
