### ISSUE TITLE
Wrong type is accepted

### ISSUE THREAD

**Issue by luisbirchenz** [Microsoft/vscode#20763]
- VSCode Version: 1.9.1
- OS Version: Windows 7 Enterprise

Steps to Reproduce:

1.  By creating a service, then try to send a post method i.e. :
     http.post('/the_url', parameters, **options**)
2.  I set wrong **options** parameter like this: 
    const headers = new Headers();
    headers.append('Content-Type', 'application/x-www-form-urlencoded');
    http.post('the_url', parameters, **headers**) instead of sending new RequestOptions({ headers: headers }) there.

The post method when uses just headers as option does not work and it does not complain about wrong type and this is really hard to detect because there is no errors or warning at compilation time or runtime. I guess the IDE must show a warning otherwise the goal of why it was created (script typed) stop making sense I guess. It is really helpful to have that kind of support at compilation time.

When I replaced headers by RequestOptions({ headers: headers }) it worked properly. 

It would be great if could consider it.

Thanks in advance,

Luis.

**Comment by mjbvz** [comment]
Are you working in JavaScript or TypeScript? Also, can you please provide a complete code example that demonstrates the problem

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this.

@luisbirchenz Please provide a complete code example that shows this problem so that we can investigate this
