### ISSUE TITLE
TypeScript coloring off in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2076]
- open src/vs/workbench/services/files/node/watcher/unix/watcherService.ts
- go to line 34
- use light theme +

![image](https://cloud.githubusercontent.com/assets/900690/12384617/5767acae-bdb4-11e5-858c-54bd1dc5aa66.png)

**Comment by aeschli** [comment]
@bpasero Can you add the code snippet? Thanks!

**Comment by bpasero** [comment]
@aeschli https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/watcher/unix/watcherService.ts#L34-L69

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#60
