### ISSUE TITLE
Option for seeding find string from editor on ctrl + f

### ISSUE THREAD

**Issue by Tekbr** [microsoft/vscode#20768]
- VSCode Version: 1.10.0 - insider
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

If I put the cursor on the word (start, middle or end of word) and press `ctrl + f`, that word is automatically placed in the search.

Is not that wrong?

The correct would be if I selected the word and then pressing `ctrl + f` it should appear in the search field.

**Comment by joaomoreno** [comment]
It's not really wrong. If you don't like it, we can make a setting for it.

**Comment by Tekbr** [comment]
Thank you @joaomoreno 

@alexandrudima @joaomoreno I compared it to other editors (Atom and Sublime). If there is person they like, maybe an option to turn it on and off.

**Comment by coreyfarrell** [comment]
To expand on the reporters description, the current behavior makes it oddly difficult to "find again".  For example I just searched a Javascript file for the start of arrow functions `) =>`, and removed the parenthesis from functions with a single parameter.  After each edit I had to make sure I moved the editor cursor to empty whitespace before pressing Ctrl-F again, otherwise I had to retype my search value.

**Comment by joenoon** [comment]
I'm having the same issue that @coreyfarrell explained.  Here is my usual/desired workflow:

1. cmd+f, enter search term hit enter
2. esc to exit Find dialog on the current found
3. change text in editor
4. cmd+f again to try and find the next occurrence, except Find opens with whatever the cursor happens to be on

If anyone knows a way to work around this or just stop the editor from changing the Find that would be great.

**Comment by mfrost66** [comment]
Continued from #17562 as requested.  That said, this is really about usablity of ```replace```

If a multi-line selection is made and ```replace``` is invoked (ctrl-h):
* Default to ```find in selection```
* Set find input value to last find|replace value
* Set focus to find input control (not replace)

Reasons:
* reduces keystrokes/clicks necessary to do a replace
* attempting to search for a multi-line string is a very rare use case (currently can't even see most of a multi-line find string)
* consistent with mainstream editors (MS office, visual studio, intellij, etc)

**Comment by tbfleming** [comment]
@mfrost66 I wish. At one point ctrl+f behaved something like that, but it confused OSX users.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@rebornix I found these new functions: 

`"editor.find.autoFindInSelection" and "editor.find.seedSearchStringFromSelection":`

I did not understand their operation. Besides that, what I have reported is not happening.

My problem is:
1- Place your cursor over a word.
2- Press Ctrl + f.
3- The word goes to the field of research and I do not want to search it.


Now if I had selected the word and pressed Ctrl + f, then yes it should go to the search field.

**Comment by Tekbr** [comment]
@rebornix Can you check and answer me, please?

**Comment by Tekbr** [comment]
Can @rebornix or anyone check (@joaomoreno @alexandrudima ) and reopen this issue?

At least it is being open to there is the possibility of someone looking at it.

**Comment by rebornix** [comment]
@Tekbr I see what you mean, you are actually asking for populating from selected range but you don't want to auto populate the word under cursor, right?

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@rebornix See this gif. This can not happen, in my opinion. Place in the search field the word where the cursor is stopped (beginning - middle and end of word). By pressing Ctrl + F or Ctrl + Shift + F or clicking on the magnifying glass (search) in the sidebar.

![search](https://user-images.githubusercontent.com/19866231/26901137-0f0ad626-4bab-11e7-9156-12183eb6ccef.gif)


Now, if I had selected the word, fine, that's correct, like showing the gif below.

![search2](https://user-images.githubusercontent.com/19866231/26900858-029d39e8-4baa-11e7-9049-1e6bde988e37.gif)

**Note:** Can you explain to me what new functions are? - if possible with a gif. Thank you.

> @rebornix I found these new functions:
> 
> `"editor.find.autoFindInSelection" and "editor.find.seedSearchStringFromSelection"`:

**Comment by Tekbr** [comment]
@rebornix Can you check and answer me, please?

**Comment by rebornix** [comment]
`editor.find.seedSearchStringFromSelection` is used to populate the search string by the word under cursor of selection when you search. It means if you put your cursor around a word, the word will be populated; if you select a few characters, these selected characters will be populated.

`editor.find.autoFindInSelection ` is about whether to toggle Find In Selection when you select a few characters in the editor and run search.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@rebornix Which does not solve the problem of the question made in the first post. Can you please reopen the question? I showed and I mentioned in the [above comment](https://github.com/Microsoft/vscode/issues/20768#issuecomment-306923374) the problem.

**Comment by brunnerh** [comment]
My suggestion for dealing with this issue would be to extend `seedSearchStringFromSelection`, e.g. to an enum of: "off", "cursor", "selection"

"off" = `false`.
"cursor" would behave like the current `true`, where either selection or the word under the cursor are used.
"selection" would only replace the search if the selection is non-empty.

(For total control and consistency it would have be an array of options, so that "cursor" would not imply "selection". Disabling it would then be the empty array.)

Personally, i usually search by selection or modifying the previous search, so either having my previous search be replaced by whatever is under the cursor or not having the option of searching by selection at all is not very helpful.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

A week went by, and no answer was given by @rebornix . Even though he had previously reported that the problem had not been corrected. It can not even reopen the case, even showing the problem's gif and what the problem is.

I know the same could be busy with other problems, but take 1 minute to be able to respond or less reopen the question he can not. I know you can claim, "Why do not you offer a PR?" If I had known I would have done it or at least helped. But I do not have conditions right now.

With a closed question it will not be possible for anyone to look at it. So if @rebornix  can not solve the question, who can someone ( @joaomoreno @alexandrudima  ) reopen for it? Because it is a resource request and said nothing because of not implementing the resource.

Thank you.

**Comment by rebornix** [comment]
@Tekbr sorry for the late response, I was working on endgame and testing so didn't catch up with github notifications. Your suggestion of a enum value for `seedSearchStringFromSelection` is an option for this issue.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@rebornix Thanks for the answer.

The idea of being an `emun type` was not mine, but @brunnerh . I think @brunnerh  idea can solve (if Google Translator translated correctly. 🤔 ). What I really find annoying is: regardless of where the cursor is, by pressing `Ctrl + F` or `Ctrl + Shift + F` or `clicking on the search (magnifying glass - sidebar)` fill in the field automatically for the search. The correct one for me is only when we select the word and press `Ctrl + F` or `Ctrl + Shift + F` or `click on the search (magnifying glass - sidebar)` it fills the field.

**Comment by 3x1010** [comment]
I completely agree with Tekbr, this feature is a must.
Please include it asap.
Thanks in advance

**Comment by skateinmars** [comment]
Hello, are there any plans to work on this?

I believe using an enum as suggested earlier would help people that are getting confused by the "cursor position erases my current search" behavior.

**Comment by Springrbua** [comment]
I often do a manual search and replace inside a file (for example, if not all matches have to be replaced).  
In Eclipse I used to select the text I want to search and pressed "ctrl+k", which jumped to the next match.  
Then I replaced the match (if needed) using ctrl+v and continued my search with ctrl+k.  
In vscode, however, every hit of ctrl+k (I am using Eclipse keybindings) replaces my search-string with the one under the cursor, hitting F3 has the same effect.  
It would be cool, if this could be changed using a setting.

**Comment by redbar0n** [comment]
@Tekbr here's a how-to:

`Preferences -> Settings -> User settings window` then add:
```
{
    // ...
    "editor.find.autoFindInSelection": false,
    "editor.find.seedSearchStringFromSelection": false
}
```

Then `CMD+P` and type: `>Reload Window`
Now the behavior should be disabled.

**Comment by Skura23** [comment]
Still no solution? This is a very annoying feature. This issue has been raised for 2 years. Means it has annoyed thousands of users for 2 years. Gosh.

**Comment by Skura23** [comment]
A workaround here is to use `up arrow` in find input box. 
Say you choose `foo` and use `ctrl f` to find, then you want to change that search string to `fob`, you press `ctrl f` again, but it changes to a string your cursor is hovering on, which we don't like. Then you could press `up arrow` to track search string history. In this case, we press `up arrow` and we get string `foo` back again.

**Comment by bdoms** [comment]
This is a super annoying bug, and it's going to drive many users away from VS Code. If you think about it like this:

1. User does some manual work (by typing a search term into the find field)
2. Leaves the field/feature in question to go do other things
3. Hits `ctrl f` again
4. The program automatically undoes the manual work from step 1

Any time that a program eliminates manual work the end user did and forces them to do it again is a huge problem. This is exacerbating by nobody expecting this "cursor" behavior by default - no other editor works that way by default. Keep the highlighting for sure - that's a deliberate action on the user's part, so the behavior is expected. But the default behavior right now is a bug, and it's one that thousands of developers are encountering multiple times every day.

How can we escalate this? Is it possible to place a bounty on it? IMO "backlog" is an awful milestone for something this annoying and this impactful to the core user experience.

**Comment by wkornewald** [comment]
I've opened a pull request to completely replace the current behavior: #80477 
I don't think having multiple configuration options is worth the technical debt since the current behavior is bad UX and inconsistent with practically all other software, anyway.

Can someone with merge permission please have a look? It's a really small change.

**Comment by mbomb007** [comment]
@wkornewald The pull request has a single conflicting file that must be resolved.

**Comment by justingolden21** [comment]
@wkornewald did you look into the conflicting file?

**Comment by wkornewald** [comment]
@rebornix if I update the PR, will it be merged? I don’t want to waste time on this because for a long time nobody was interested in my PR.

**Comment by rebornix** [comment]
@wkornewald the challenge here is we support ctrl/cmd+f to search the word under cursor from day 1 and there are enormous users enjoy using this feature, including myself. I'm not convinced that this feature should be removed.

**Comment by 3x1010** [comment]
> @wkornewald the challenge here is we support ctrl/cmd+f to search the word under cursor from day 1 and there are enormous users enjoy using this feature, including myself. I'm not convinced that this feature should be removed.

They should give the option to change the behaviour.
Before day 1 there were a lot of other editors that behaved in the way we want

**Comment by wkornewald** [comment]
@rebornix So should it stay configurable and the default could switch to the more consistent behavior that all other software is using? Especially when working with multiple IDEs/editors, you feel the switching cost every time. And my PR is currently the number 3 highest-voted PR, so the current behavior really can’t be that popular.

**Comment by ktnyt** [comment]
I'm fine with this feature __so long as it doesn't interfere with what is already in the Find Widget buffer__.
When I close the Find Widget and reopen it via shortcut, __I expect its contents to be unaltered__.
If the Find Widget didn't contain any previous search query then I'd be completely fine with it being populated by the word under the cursor.
However, it isn't uncommon to search for a single query multiple times and edit each occurrence individually, which is where this feature interferes with the UX.

**Comment by danielsnider** [comment]
I found pressing `F3` or disabling `editor.find.seedSearchStringFromSelection` does what I want but only within one panel of tabs. I was hoping Ctrl+F would always have the same search string for all my tabs.

**Comment by cozuya** [comment]
`editor.find.seedSearchStringFromSelection` does not seem to be working for me.

Version 1.57.1

With a word selected and the above setting enabled, I hit `cmd + f` and that word is not seeded into the search box.  Obviously this irritates me enough to come here and complain.

**Comment by jzyrobert** [comment]
Hasn't this been fixed by https://github.com/microsoft/vscode/pull/128659 ?
That PR just quoted a different issue which is the same problem people have here.

`seedSearchStringFromSelection?: 'never' | 'always' | 'selection';`

@rebornix think this can be closed

**Comment by cspipaon** [comment]
This now works for me in 1.67.0 after restarting VScode. However, this only works in the editor. Is it possible to get it working in Jupyter notebooks as well?

**Comment by ashegoulding** [comment]
`editor.find.seedSearchStringFromSelection` has no effect on 1.66.2

This feature has been really annoying for me because I want to change the contents of the search string WHEN and ONLY WHEN I want to change it, regardless of the selection. The search string changing whenever I select something with Ctrl+D doesn't just make sense to me - from my intuition, they're separate tools and there's no reason they should be related in any way.

**Comment by mdoliner-st** [comment]
@jzyrobert Yes, I agree, this does appear to be fixed now and it seems like this should be closed. Yay. Here's a screenshot of the options I see in version 1.67.2 on macOS:
<img width="595" alt="Screen Shot 2022-06-03 at 10 15 37 AM" src="https://user-images.githubusercontent.com/53571977/171872050-41161ca5-f31f-4f29-8b95-4de13693d071.png">

@ashegoulding I'm curious what you mean by "editor.find.seedSearchStringFromSelection has no effect." If you search for that option in settings, do you see the three options from my screenshot? Does changing between the options have any effect on whether the text in the "Find" box changes when CTRL+f (or CMD+f) is pressed? I think what should happen is:
- never: The text in the Find box never changes, even if a word in the edited or selected.
- always: The text in the Find box changes to match the text under the cursor, even if that text isn't selected.
- selection: The text in the Find box is changed only if text in the editor is selected (but if nothing is selected then the text is not changed).

**Comment by amunger** [comment]
closing as completed since `editor.find.seedSearchStringFromSelection` accomplishes the original ask and seems to be working fine in the latest release
