### ISSUE TITLE
Ctrl-C kills VSCode if started from command prompt

### ISSUE THREAD

**Issue by wm1** [Microsoft/vscode#20769]
- VSCode Version: 1.9.1
- OS Version: Windows 10 Anniversary Update

Steps to Reproduce:

1. From the command prompt, run "C:\Program Files (x86)\Microsoft VS Code\Code.exe". 
2. Press Ctrl-C from command prompt, VSCode exits immediately

**Comment by joaomoreno** [comment]
This is as expected.

**Comment by wm1** [comment]
Why such a behavior is expected? A child process (at least on Windows) started from cmd.exe is not supposed to be killed when the parent process receives a Ctrl-C.

I work from command line all the time, and start Code there. Ctrl-C killing the editor is not a great experience for me.

**Comment by joaomoreno** [comment]
What should Ctrl C do, then?

**Comment by wm1** [comment]
Depends on whether the child process shares the console with the parent cmd process or not.
- For child console process that shares console, Ctrl-C would likely kill the running child process;
- For child GUI process that does not have a console at all, Ctrl-C on the parent cmd process should have no impact on it.

**Comment by joaomoreno** [comment]
Code.exe **is** a child console process. That's just how Chromium works.

If you don't want that, I suggest to use what we put in the `PATH`: simply type `code`. It should point to `...\Microsoft VS Code\bin\code.cmd`. This will get you a detached Code.

**Comment by wm1** [comment]
Before replying last time I did check that code.exe is a gui process:

`link.exe /dump /headers "C:\Program Files (x86)\Microsoft VS Code\Code.exe" | findstr subsystem
               2 subsystem (Windows `**GUI**`)`

Anyhow, code.cmd solves my problem. And I guess that is why nobody complains about this issue. I was not aware of this script as I never allow programs to update PATH.

In the meantime, I figure out that "start **/b** <path-to-code.exe>" also works, which basically sets CREATE_NEW_PROCESS_GROUP and thus the new process won't receive Ctrl-C targeting the original group.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
