### ISSUE TITLE
Resizing terminal will not resize the terminal chat widget

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#207601]
Repro:

1. Open terminal chat
2. Ask "list files in various ways"
3. Reduce height of terminal

![image](https://github.com/microsoft/vscode/assets/2193314/6a5998f4-1905-4027-b35b-430546b228c3)

**Comment by meganrogge** [comment]
@jrieken , we'd need a way to set max height for the chat widget, which there isn't currently AFAICT

**Comment by jrieken** [comment]
@meganrogge You need to call layout with the sizes you want

**Comment by meganrogge** [comment]
@jrieken i tried that and didn't see the height taking effect, only the width.
