### ISSUE TITLE
Major delay when running any program 

### ISSUE THREAD

**Issue by Strongestsquirrel** [microsoft/vscode#207632]
Type: <b>Bug</b>

Within the last two months, my VSC began having a delay of 5 - 10 seconds whenever I try to run any program. It isn't code specific, because even when trying to run just a print line it still has the same delay. The code still runs quickly, it just seems to take very long to start. At the time I didn't take much notice as I was working on a big project and so I thought it was just the actual project being slow, and as such I am unable to pin point if there was anything I changed. I have tried uninstalling VSC and all related files, resetting all settings and preferences, but even when reinstalling it still has the same issue. I haven't been able to find other people online with the same issue and am at a loss for what to do. Unfortunately I cannot give details on how to recreate as I do not know what caused it myself. 

(I have previously opened this issue, but it has been a week with no reply from the assigned member, even after an email sent to them)

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.46GB free)|
|Process Argv|--crash-reporter-id 7407d8cb-da65-466d-ac67-60a372c119f0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30986171
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by roblourens** [comment]
Sorry for the delay but please don't just open dupe issues
