### ISSUE TITLE
Inline chat does not render intents correctly if there's an intent that prefixes that intent

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#207619]
It runs the correct intent, but renders `/fix` rather than `/fixTestFailure`

![image](https://github.com/microsoft/vscode/assets/2230985/557b823e-e638-4189-89df-9a8190672e82)
 
![image](https://github.com/microsoft/vscode/assets/2230985/abd91e51-468b-48b4-bd09-3b97591b5f4a)

This does not happen in panel chat

**Comment by jrieken** [comment]
@joyceerhl You implemented this, right?
