### ISSUE TITLE
Can't step into methods when debugging unit tests

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#20776]
- VSCode Version: 1.9.1 and Insiders 1.10.0 (496b804f8ae5a95e899406fcc67f6c1896894c91)
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Set a breakpoint in a test (e.g. extHostLanguageFeatures.test.ts line 637).
2. Run the "Unit Tests" launch configuration.
3. Wait for breakpoint to catch
4. Attempt to step into a function.

Expected: Step into a function
Actual: Behaved as if I pressed "Continue".

**Comment by weinand** [comment]
dup of #19936
