### ISSUE TITLE
magnifying markdown preview decreases the size of the preview pane

### ISSUE THREAD

**Issue by jdanyow** [Microsoft/vscode#20772]
- VSCode Version:
```
Version 1.9.1
Commit f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
Date 2017-02-09T00:26:45.394Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

- OS Version:
Windows 10

Steps to Reproduce:

1. open a markdown file (*.md)
2. press <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>v</kbd> to open the markdown preview
3. press <kbd>ctrl</kbd>+<kbd>+</kbd> to magnify the markdown preview

div displaying the markdown preview becomes smaller as preview is magnified

**Comment by mjbvz** [comment]
Duplicate of #5745
