### ISSUE TITLE
Windows update interrupted the remote connection at night, causing the program on the server to be terminated

### ISSUE THREAD

**Issue by jax11235** [microsoft/vscode#207787]
Is there any way to prevent this from happening?

**Comment by connor4312** [comment]
What remote connection were you using? Did the compute go to sleep? Can you share the logs of the relevant connection type you were using from the Output window?

**Comment by connor4312** [comment]
If VS Code closes, the connection will likely close as well. You can use tools such as `screen` or `tmux` to keep programs running even if the SSH client disconnects.
