### ISSUE TITLE
Support createMenuItem API

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#207786]
There's a `createStatusBarItem` API for contributing statusbar items dynamically, a similar API for contributing menu items dynamically would be super useful for some extensions.

For example I have an [extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-commands) that allows users to define statusbar items with a few lines of configuration, I'd love to have the same capability but for menus as well, but currently this seems unimplementable (unless the installed extension rewrites itself or other crazy stuff like that).

**Comment by gjsjohnmurray** [comment]
Related to #110218?

**Comment by fabiospampinato** [comment]
Ah yeah, I couldn't find that. Closing as a duplicate of #110218
