### ISSUE TITLE
Test node2 transition work

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#20779]
Testing #19650

Complexity: 2

- [ ] Any OS @Tyriar 
- [x] Any OS @egamma 

Previously, users would set the 'type' in their launch config to 'node' or 'node2'. Now we will tell users to use the 'node' type, but pick a debug adapter by setting the 'protocol' field. It can be 'legacy', 'inspector', or 'auto'. 'auto' will detect the version of node on the path, and use 'inspector' if it's Node 6.9 or above. If protocol isn't set, it will default to 'legacy' for this milestone.

Verify that
- If you set `"protocol": "legacy"` in your launch config, it picks the legacy adapter (In the debug console, it will show that it's using the `--debug` flag)
- If you set `"protocol": "inspector"` in your launch config, it uses the inspect protocol (you will see the `--inspect` flag)
- If you set `"protocol": "auto"`, it will detect the version of node on your path, and use inspect if it's 6.9 or above.
- If you start node running with the `--debug` flag, and start an attach config that has `"protocol": "auto"`, it will successfully attach
- If you start node running with the `--inspect` flag, and start an attach config that has `"protocol": "auto"`, it will successfully attach
- There are no snippets for node2

**Comment by bpasero** [comment]
@roblourens should this be set to milestone February?

**Comment by roblourens** [comment]
Yes thanks

**Comment by weinand** [comment]
BTW, we had to test items for the "node2 transition" work. Here is the other: https://github.com/Microsoft/vscode/issues/20991

**Comment by roblourens** [comment]
I forgot to mark it "on-testplan", sorry. At least it's very well tested!
