### ISSUE TITLE
javascript.suggest.autoImports is buggy

### ISSUE THREAD

**Issue by yuis-ice** [microsoft/vscode#207710]
It ruined my day. 

I strongly suggest it to be false by default. Thanks.

**Comment by mjbvz** [comment]
What went wrong?

**Comment by yuis-ice** [comment]
Well then I can show a quick code.

I had a very normal .js file. I'm writing on it: 

```js
const Mus = require('./mus.js');
window.mus = new Must()

(async () => {
  // .. more code
  await waitUntil(() => mus
```

typing "."

```js
import mus from './mus.js'
const Mus = require('./mus.js');
window.mus = new Must()

(async () => {
  // .. more code
  await waitUntil(() => mus.
```

Well. continues.


```js
import mus from './mus.js'
const Mus = require('./mus.js');

(async () => {
  // .. more code
  await waitUntil(() => mus.playing == false);
  // continue writing..
```

Okay! Let's see how the page works... Huh? I'm getting "No such method "playing" in Object mus" (or something like that) error. Ummmmmmmmmmmm, I have no clue? That error is very weird, because literally I haven't put any code that would cause such type of error. 

(After a few hours)

**WHERE IN THE WORLD THIS LINE IS COMING FROM？？？**

```js
import mus from './mus.js' // <--------- THIS
const Mus = require('./mus.js');

(async () => {
  // .. more code
  await waitUntil(() => mus.playing == false);
  // continue writing..
```

**Comment by mjbvz** [comment]
If you don't find auto imports useful, you can turn them off by setting `javascript.suggest.autoImports: false`

Additionally you can setup a jsconfig with `module: "commonjs"` to make VS Code use `require` instead of `import` for auto imports

> I strongly suggest it to be false by default. 

Lots and lots of people rely on these working by default so we're not going to disable them

**Comment by yuis-ice** [comment]
Hey, you should try improving the feature. **I** don't use the feature as I already disabled it, since **lots and lots of people still use it** any bugs should be fixed. I think that's why the issue field on Github exists after all?

**Comment by mjbvz** [comment]
What you showed isn't really bug though, it's what's expected to happen if you accept an auto import completion
