### ISSUE TITLE
Last active window is not always restored when reopening

### ISSUE THREAD

**Issue by mherodev** [Microsoft/vscode#20770]
Instead, the last VS Code window to be closed (typically the most-background window) is opened.

This behavior does not mimic the "Reload" behavior that newly installed extensions offer, which works as expected.

Apologies if this is a duplicate.

**Comment by bpasero** [comment]
Try: `"window.reopenFolders": "all"`

**Comment by mherodev** [comment]
@bpasero I see the problem! There's a bug in the default behavior.

```
// Controls how folders are being reopened after a restart. 
// Select 'none' to never reopen a folder, 'one' to reopen the last folder you worked on or 'all' to reopen all folders of your last session.
```

The "last folder you worked on" is not always accurate as VS Code sometimes closes the folders out of order from when they were last worked on. 

I assume closing "front to back" is intended, but sometimes background tasks/terminals/editors/etc. cause the front-most, last-worked-on window to close later than another window.

To reproduce:
1) Clone react-slingshot
2) Clone redux-auth
3) Open both projects in their own windows
4) Install and Start **react-slingshot** via VS Code Terminal
5) Open up numerous editors in the **react-slingshot** window
6) `cmd + q` VS Code
7) Relaunch VS Code

These repro steps are intermittent, but they can provide the behavior, e.g.

![](http://g.recordit.co/H2AIq7FfAe.gif)

I can open up another issue if that is more appropriate.

**Comment by bpasero** [comment]
@mherodev trying to distill your issue here, is it that the "last active window" is not properly restored when you have this setting on and you restart after a quit?

**Comment by mherodev** [comment]
Correct.

The "last active window" will often be erroneously set to another window that manages to close before the true "last active window", so the wrong window is restored.

**Comment by bpasero** [comment]
There are two bugs actually:
* when `window.reopenFolders` is set to `one` (default) and you open many windows and quit, the next session will open a random window from the previous session, not necessarely the last active
* when `window.reopenFolders` is set to `all`, the same bug shows up, but less annoying, its just the last active window is not focussed

**Comment by mherodev** [comment]
Awesome, thanks @bpasero!
