### ISSUE TITLE
Inplace Update of VSCode

### ISSUE THREAD

**Issue by DoganM95** [microsoft/vscode#207779]
Inplace Updates of VSCode itself.  

There are mainly 2 options of vscode, an installer and a portable version. I use the portable one, it wroks just as the installed one, but needs the functionality to update itself, from within the folder it runs in. There are various apps, that already have this functionality. like DS4Windows. Although portable, it can easily update itself and restart automatically. This would make the portable version of vscode a lot more convenient.

**Comment by joaomoreno** [comment]
#190123
