### ISSUE TITLE
Support ANSI escape codes in TestOutputChannel

### ISSUE THREAD

**Issue by JamyDev** [microsoft/vscode#207750]
Currently the extent of the "support" for ANSI escape codes in the TestOutputChannel (so `TestRun.appendOutput`) is limited to [stripping them before appending](https://github.com/microsoft/vscode/blob/6269ab41b4ca49759bc46f473ec2172b5c7f7a14/src/vs/workbench/contrib/testing/common/testResult.ts#L368). 

Unfortunately, the test output channel is not available from `vscode.window.activeTextEditor` like a normal OutputChannel would be, so it's impossible to add decorators from the extension itself. Meaning there's no way to add color to this output. 

Could we have either:
- Full ANSI color support for the TestOutputChannel (like the terminal)
- Access to the "text editor" that contains the test result output when visible, so decorators can be added

Followup from #571

**Comment by Tyriar** [comment]
@connor4312 The text `TestOutputChannel` doesn't seem to exist in the repo? Is this about some other API?

**Comment by Tyriar** [comment]
Works (tested colors and cursor left):

<img width="243" alt="Screenshot 2024-03-25 at 12 20 03 PM" src="https://github.com/microsoft/vscode/assets/2193314/14ebe94f-39ed-4356-93b6-19b2904bda57">
