### ISSUE TITLE
Adjust URL detection within terminal to include url parameters

### ISSUE THREAD

**Issue by PowerSchill** [Microsoft/vscode#20777]
- VSCode Version: 1.10.0-insider
- OS Version: Windows 10

The URL detection in the terminal does not capture URL parameters . For example PowerShell helpfiles  have a link of the type `http://go.microsoft.com/fwlink/?linkid=821590`. However the terminal only detects and makes `http://go.microsoft.com/fwlink` a URL.

**Comment by Tyriar** [comment]
Good find :smiley:

**Comment by levrik** [comment]
@Tyriar Also in 1.10.0-insider 50f8848e44029ffabf0727de49cd18ae4069b4fe (current insider version) `http://www.google.de` `http:/` gets not underlined on hover (the second slash seems to get underlined)

**Comment by Tyriar** [comment]
@levrik that one should be fixed in the next build.
