### ISSUE TITLE
"Check for Updates" popup theme needs to match

### ISSUE THREAD

**Issue by freshsqueezedorangejuice** [microsoft/vscode#207752]
1. Change Visual Studio Code theme to Dark Theme
2. Click Manage icon > Check for Updates...
3. Observe the "There are currently no updates available." popup theme is light theme instead of dark theme.

![image](https://github.com/microsoft/vscode/assets/140188552/0ab15534-b31e-4f38-a77f-965dba42eb34)

**Comment by bpasero** [comment]
See https://code.visualstudio.com/updates/v1_86#_new-setting-to-enforce-system-color-theme

**Comment by freshsqueezedorangejuice** [comment]
@bpasero @mjbvz The link provided does not resolve the issue. Please reopen issue and first follow the three steps provided to replicate the problem.

**Comment by bpasero** [comment]
Alternatively, configure `window.dialogStyle` setting to `custom`

**Comment by freshsqueezedorangejuice** [comment]
Awesome!  Why isn't this the default dialogStyle?

**Comment by bpasero** [comment]
There is nothing in the native OS dialog that we cannot do that forces us to use a custom dialog, so we typically prefer to keep native UI integrations where possible. To give another example: macOS has a well working context menu and main menu, so we use that over our custom menu.
