### ISSUE TITLE
Unable to hide the chat widget in terminal

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#207751]
Does this issue occur when all extensions are disabled?: Yes/No

- Version: 1.88.0-insider
- Commit: 7107b38665e428a974c06b2c6e8f67a9a078aefd
- Date: 2024-03-13T06:02:12.129Z (1 day ago)
- Electron: 28.2.6
- ElectronBuildId: 27476517
- Chromium: 120.0.6099.291
- Node.js: 18.18.2
- V8: 12.0.267.19-electron.0
- OS: Darwin arm64 23.3.0

Steps to Reproduce:

Absolutely no idea how i ended up in this state, , howver I can no longer close this chat widget

<img width="546" alt="Screenshot 2024-03-15 at 05 55 43" src="https://github.com/microsoft/vscode/assets/1948812/e8019f21-e6f3-42dc-b685-3e119904c4a2">

**Comment by Tyriar** [comment]
Yep this is an annoying bug I'll try fix up today. To hide it you need to show it (ctrl/cmd+i) and hide it (esc).

There's a duplicate issue but I don't think the title is good, so I'll keep this as the main one.
