### ISSUE TITLE
Move vscode-selfhost-test-provider into VS Code workspace

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#207756]
With the introduction of [workspace extensions](https://github.com/microsoft/vscode/issues/206783), we can now move [vscode-selfhost-test-provider](https://github.com/microsoft/vscode-selfhost-test-provider) extension into VS Code repository under `.vscode/extensions` folder.

- Move the extension to `.vscode/extensions` folder.
- Use `tsconfig.json` similar to the one in builtin extensions - [example](https://github.com/microsoft/vscode/blob/98968c0b0af82b45e0b047ae67ea747ace2c204c/extensions/git/tsconfig.json#L26)
- Add `'.vscode/extensions/vscode-selfhost-test-provider'` to `dirs` in `dirs.js` file
- Add `'.vscode/extensions/vscode-selfhost-test-provider/tsconfig.json'`  to `compilations` in `gulpfile.extensions.js` file
- Remove redundant files and update code to work in this environment.
- Remove `"ms-vscode.vscode-selfhost-test-provider"` entry in `extensions.json` file

To check

- Run Build Task - cmd+shift+b - make sure extension sources are built
- Uninstall the `vscode-selfhost-test-provider` extension - Reload window.
- Open workspace recommendations - Extensions View - `@recommended` and install `vscode-selfhost-test-provider` workspace extension
- Make sure the extension is running

**Comment by connor4312** [comment]
PR is staged but there's no rush so I'll merge in debt week
