### ISSUE TITLE
enable/disable Sticky Scroll by language

### ISSUE THREAD

**Issue by hgf777-br** [microsoft/vscode#207783]
I really liked the sticky scrool feature when working with Python, Javascript and C++.  
But, for me, it gets confuse in a HTML code.
Now iis only possoble to enable or disable it globally and I think it will be a good idea to make this feature language dependent.

Thanks for your attention,
Henrique

**Comment by RedCMD** [comment]
```json
"[html]": {
	"editor.stickyScroll.enabled": false
}
```

**Comment by aiday-mar** [comment]
Thanks @RedCMD

**Comment by hgf777-br** [comment]
Thank you!!!

**Comment by aiday-mar** [comment]
Hi @hgf777-br if you are using the django extension, then you must be working in a python file. In that case you can change the `html` tag above to `python`
