### ISSUE TITLE
Do not prompt me to save files when opening a new folder, just keep them open.

### ISSUE THREAD

**Issue by MMulthaupt** [microsoft/vscode#207853]
When choosing File -> Open Folder... and choosing a different folder to open, VsCode will prompt to save any unsaved files open in the present workspace.

It would be way less intrusive to just leave unsaved files open when changing the workspace. Often they are checklists of things or part of ongoing work that is somehow related to the newly opened workspace, but the user deviates from opening an additional window to save time and resources.

**Comment by bpasero** [comment]
Try with `files.hotExit` configured to `onExitAndWindowClose`

**Comment by ahmed0saber** [comment]
Hello @MMulthaupt ,
You can open the folder first, then drag and drop the required files.

**Comment by MMulthaupt** [comment]
@bpasero Good suggestion, but the file is not transferred to the newly opened workspace.

@ahmed0saber The file may exist only in memory, i.e. created with Ctrl+N with no associated file name or path.
