### ISSUE TITLE
Proxy settings not working with extension gallery: net::ERR_TUNNEL_CONNECTION_FAILED

### ISSUE THREAD

**Issue by FloMaetschke** [Microsoft/vscode#20786]
- VSCode Version: Code - Insiders 1.10.0-insider (496b804f8ae5a95e899406fcc67f6c1896894c91, 2017-02-16T07:10:22.864Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-opennewinstance|chrisdias|0.0.4|
|npm-intellisense|christian-kohler|0.1.4|
|vscode-npm-source|dkundel|0.0.3|
|githistory|donjayamanne|0.1.2|
|KillTasksButton|dtrajano|0.0.4|
|CreateModule|HookyQR|0.0.5|
|task-master|ianhoney|0.1.37|
|output-colorizer|IBM|0.0.8|
|debugger-for-phantomjs|iradul|0.1.1|
|csharpextensions|jchannon|1.1.0|
|csharp|ms-vscode|1.5.3|
|debugger-for-chrome|msjsdiag|2.3.2|
|color-highlight|naumovs|1.2.1|
|material-icon-theme|PKief|1.1.4|
|qub-msbuild|qub|0.5.0|
|Material-theme|zhuangtongfa|1.0.3|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1. Open Extension Gallery
2. Search for 'test'

The extension gallery is no longer working.

For a longer amount of days the version gallery seems to be broken at my office pc, which is behind a corporate proxy.

I always get a net::ERR_TUNNEL_CONNECTION_FAILED when the gallery tries to fetch 
https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery

My vscode was set up with proxy credentials in config before. This did work for a long time very well. i was actually able to download extensions, after @joaomoreno fixed an early version in beginning of 2016 and uploaded it here for testing (sorry i dont fint the thread right now). This bugfix got merged in the official version later and worked fine. But as of 3 Months or so its no longer working.

When using google i found this page: http://code.visualstudio.com/docs/setup/setup-overview

I tried switching to env variables. But this does not work either, so i guess its a problem with vscode itself

I switched to HTTP_PROXY and HTTPS_PROXY env variables now, which seems to be the recommended option. But this doesn't work either.

**Comment by FloMaetschke** [comment]
I try to analyze / debug the errors on my own now, too. maybe i can help.

**Comment by joaomoreno** [comment]
Can you provide some input in #18103 ?

**Comment by FloMaetschke** [comment]
You can find the results here: https://github.com/Microsoft/vscode/issues/18103#issuecomment-280728376

Thx so much for your efforts, great idea with this http proxy unit test ;)

**Comment by FloMaetschke** [comment]
any chance to get a solution soon?

**Comment by joaomoreno** [comment]
This happens due to the use of XHR in the renderer. cc @jrieken 

Soon, but not this month yet, very busy with other stuff. I'll make it a priority for March.

**Comment by FloMaetschke** [comment]
Thx joao.

**Comment by hh9527** [comment]
How is this issue going on?

**Comment by FloMaetschke** [comment]
https://github.com/Microsoft/vscode/pull/21879

**Comment by joaomoreno** [comment]
Please check out #22214
