### ISSUE TITLE
When I insert #encoding in my python files,The code prompts invalid

### ISSUE THREAD

**Issue by Gilbertat** [Microsoft/vscode#20781]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|format-indent|Kasik96|1.3.0|
|swift|Kasik96|0.0.2|
|python|donjayamanne|0.5.8|
|php-debug|felixfbecker|1.10.0|
|vscode-icon-theme|jtlowe|1.4.0|
|MagicPython|magicstack|1.0.6|
|cpptools|ms-vscode|0.10.1|
|java|redhat|0.0.10|
|python|tht13|0.2.3|
|vim|vscodevim|0.5.3|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. insert #encoding in python files
2. edit code
3. The code prompts invalid

**Comment by joaomoreno** [comment]
What does "_The code prompts invalid_" mean?

Should you maybe file an issue to https://github.com/DonJayamanne/pythonVSCode/issues?
