### ISSUE TITLE
Code Review Mode

### ISSUE THREAD

**Issue by ICardosoRamos** [microsoft/vscode#207881]
It would be nice if the vscode had a code review mode, like in gitlab or github, this would be nice because the code review mode inside the vscode would catch all the personal configs from the user machine, like, extensions to use along the review, to help the reviwer to catch some things like, variables and other things declared but not used, and a lot of other things.

**Comment by IllusionMH** [comment]
Can you please describe how what it should exactly do?
There's already https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github which allows to check changes in PRs or pull locally to use all editor features.

**Comment by IllusionMH** [comment]
Working with different platforms and their APIs is complex work and each platform has it's own expectations.
I doubt that it can be built in into the editor itself, therefore there are separate extensions.

GitLab needs it's own extension that would rely on provided VS Code APIs that power similar functionality used by GH extension.

Check https://marketplace.visualstudio.com/items?itemName=GitLab.gitlab-workflow

From description it looks like it has Mr review functionality.
