### ISSUE TITLE
Untracked Items added to Source Control on Commit All

### ISSUE THREAD

**Issue by AlexBogoni** [Microsoft/vscode#20789]
- VSCode Version: 1.9.1
- OS Version: Windows 7 SP1

Steps to Reproduce:
1. Add new files to working directory 
2. New files with show up in GIT with a status of untracked
3. Do not add any staged items 
4. Add a comment and select commit all
5. All unstaged are added to source control

This would appear to be an issue since I would not expect untracked items to be added to source control when I press commit all. Only untacked items that I add to the index should be added and the rest should be ignored and left with a status of untacked.

**Comment by joaomoreno** [comment]
#19876
