### ISSUE TITLE
Rename widget isn't focused when out of view

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2078]
1. Put cursor on a *renameable* token.
2. Scroll until the token is out of view.
3. <kbd>F2</kbd>

Nothing happens. Scroll back to the token, the rename widget is there but without focus, which is owned by the editor itself. Maybe the line should be revealed on <kbd>F2</kbd>?

**Comment by jrieken** [comment]
Yeah, lets reveal on F2
