### ISSUE TITLE
Scroll lock does not indicate in floating windows

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#207817]
I think the indicator should show in all opened windows and for that you need to add it to all windows. I would monkey-see, monkey-do what we do for the accessibility status indicator:

https://github.com/microsoft/vscode/blob/b22f435d4848fa8f5ef3f1c89cf56f68d7ce6049/src/vs/workbench/contrib/accessibility/browser/accessibilityStatus.ts#L45

Specifically:

https://github.com/microsoft/vscode/blob/b22f435d4848fa8f5ef3f1c89cf56f68d7ce6049/src/vs/workbench/contrib/accessibility/browser/accessibilityStatus.ts#L94-L97

**Comment by benibenj** [comment]
I now show it on all windows. Used the same approach as `ScreenReaderModeStatusEntry`. However, it would be great to not have to do it this way. In principle the main Status Bar Service could provide an option to add an entry across all windows. I think this could be possible as the main service creates the aux ones and hence can track them...
