### ISSUE TITLE
Match whole word when search by regex. Post keyword will be excluded by previous keyword when previous keyword is a sub-string of the post one

### ISSUE THREAD

**Issue by StephanXu** [microsoft/vscode#207810]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.87.2 (Universal)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:21:31.043Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.4.0
- OS Version: macOS Sonoma 14.4 (23E214)

Steps to Reproduce:

1. Example file to search:
```c++
#include <iostream>

void FooBar() { std::cout << "Hello there :)" << std::endl; }

int main() {
  FooBar();
  return 0;
}
```
2. Search by regex `Foo|FooBar` and select **Match Whole Word** and **Use Regular Expression**

<img width="1027" alt="image" src="https://github.com/microsoft/vscode/assets/11131623/d5000b7e-34a9-4186-ae01-2ffa2f0ce996">

3. Compare this result with `grep`

<img width="529" alt="image" src="https://github.com/microsoft/vscode/assets/11131623/95d2d3c0-ae66-4bb4-806d-5125d0acbb9a">

**Comment by andreamah** [comment]
The 'match whole word' functionality is meant to match the whole input in the search bar as a single word in the text, therefore I wouldn't expect it to match "FooBar" to match in this case (although grep supports this this way). Internally, we simply surround the text by `\b` regex characters, so it ends up matching differently than you might expect.
