### ISSUE TITLE
Ability to modify PORTS Panel.

### ISSUE THREAD

**Issue by agatho-daemon** [microsoft/vscode#207857]
The ability to modify ports panel appearance and parameters.
![Screenshot 2024-03-14 174726](https://github.com/microsoft/vscode/assets/31913284/92815aaf-f83a-4351-a4a1-ef8c05385f8b)

As seen the yellow highlight, which has no reference anywhere, causes an eye strain.

**Comment by alexr00** [comment]
That yellow isn't built in to VS Code. Your theme, or your settings, must modify `tree.tableOddRowsBackground`.
