### ISSUE TITLE
Unable to format in new file (C#)

### ISSUE THREAD

**Issue by jburman** [Microsoft/vscode#20780]
- VSCode Version: 1.9.1
- OS Version: Win 10 Pro x64

Steps to Reproduce:

Working with dotnet core 1.1, C# extension (1.7.0)...

1. Ctrl-N, Ctrl-S (enter name of file e.g. Blah.cs)
2. Start typing code and I cannot format it until I close the file and re-open it.

I have Format On Save turned on, which doesn't work on the new file, and I also cannot format manually with Ctrl-K, Ctrl-F - have to close and re-open the file before formatting starts to work within it.

**Comment by jrieken** [comment]
please file this issue here: https://github.com/OmniSharp/omnisharp-vscode
