### ISSUE TITLE
Issue reporter prevents from sending issues that have very short title / body

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#207831]
To prevent issues like this: https://github.com/microsoft/vscode/issues/207830 and like this https://github.com/microsoft/vscode/issues/207820 and many more

**Comment by justschen** [comment]
this is a good idea, I've been getting tagged in a lot of these recently. it's difficult to say what exactly the limit/requirements should be though. atm we require title and description (the rest of the info is fluff that is auto included). Maybe force description to be longer than 10 characters?

**Comment by ulugbekna** [comment]
We can start with >10characters enforced on both title & body and see how issues keep coming. We could also maybe crowd-source ideas from the team
