### ISSUE TITLE
 VS Code 1.9.1 cannot launch on Ubuntu due to missing libXss.so.1

### ISSUE THREAD

**Issue by astatine** [Microsoft/vscode#20783]
- VSCode Version: 1.9.1
- OS Version: Ubuntu 16.10 x86_64 (fully updated)

**Steps to Reproduce:**

1. Install vscode 1.9.1 from the official deb
2. Run code

**Expected behavior:**
1. Code opens/runs

**Observed behavior:**
1. The following error: `/usr/share/code/bin/../code: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory`

**Comment by joaomoreno** [comment]
```
sudo apt-get install libxss1
```

#13089
