### ISSUE TITLE
Cannot "Open Folder" anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#207832]
Steps to Reproduce:

1. run `scripts/code-server.sh`
2. open the web UI
3. pick "Open Folder"
4. fill in a path that exists on disk and enter

<img width="791" alt="image" src="https://github.com/microsoft/vscode/assets/900690/91db50e9-00cc-4590-8869-d970af99ed52">

**Comment by alexr00** [comment]
This is weird. The `selectedItems` in the quick pick don't appear to be getting updated.

**Comment by alexr00** [comment]
Also, not just in web.

**Comment by alexr00** [comment]
Git bisect points to https://github.com/microsoft/vscode/commit/c349c44f08b6c30f4f48736d4ffeafcfa6f54cda

**Comment by alexr00** [comment]
Clearing `this._activeItems` here fixes things, but I don't think that's the right fix:

https://github.com/microsoft/vscode/blob/dd8829353c0785deb31265e10455277ac85cca3d/src/vs/platform/quickinput/browser/quickInput.ts#L1070-L1076
