### ISSUE TITLE
Extension README code blocks incorrectly wrapped in gray parentheses

### ISSUE THREAD

**Issue by singularitti** [microsoft/vscode#207895]
I believe I have found a display bug with how code blocks are rendered in the README files for extensions in the VSCode extension marketplace.

When viewing an extension's page in VSCode itself (for example by running `ext install fabiospampinato.vscode-open-in-github`), any code fences in the extension's README are incorrectly wrapped in pairs of gray-colored parentheses, which looks quite ugly (see figure 1). 

![t42tt23](https://github.com/microsoft/vscode/assets/25192197/08b3b6b3-3d0d-4c24-85bf-392092e063a1)

From inspecting the HTML, it appears the code fences are being wrapped like this:

```
<pre><code class="language-js"><code></code>
</code></pre>
```

Where the gray brackets correspond to the inner `<code></code>` tags.

However, when viewing that same extension page on the [actual Visual Studio Marketplace website](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-open-in-github) (see figure 2), the code blocks are instead rendered as expected - with a solid gray background and no parentheses.

![2t4h23](https://github.com/microsoft/vscode/assets/25192197/2fffb755-f917-4b63-9b15-2ea4036feb91)

This issue occurs consistently across all the built-in VSCode color themes, so I don't believe it is theme-specific. It seems to be a problem with how VSCode itself is parsing and rendering the Markdown from the extension README files.

Could this display issue please be looked into and fixed so that code blocks in extension READMEs display consistently between the VSCode extension panel and the web Marketplace? The current rendering in VSCode itself is confusing and unappealing.

Let me know if any other details would be helpful. Thanks for your consideration!

**Comment by RedCMD** [comment]
duplicate of https://github.com/microsoft/vscode/issues/205129

**Comment by singularitti** [comment]
Ah, thanks. I saw this is resolved in https://github.com/microsoft/vscode/pull/206304, shall we see the fixed one in the next release?

**Comment by RedCMD** [comment]
I think so

**Comment by singularitti** [comment]
Thanks!
