### ISSUE TITLE
Enable generation of language translations

### ISSUE THREAD

**Issue by Xivolkar** [Microsoft/vscode#20787]
It would be awesome if there is a feature to auto-generate translations for files. For example, generating translation for a `.properties` file

**Comment by joaomoreno** [comment]
Can you elaborate on this? How does this relate to VS Code?

**Comment by Xivolkar** [comment]
It helps while developing web apps using VS Code. In the sense, if you want to provide localisation of strings for your web apps it would be very useful to have this feature

**Comment by joaomoreno** [comment]
Shouldn't this be coming from any tooling related to the frameworks you develop against?
