### ISSUE TITLE
Blinking block cursor shifts letter down

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#207834]
Repro: 

0. set your cursor to be a block -- setting `  "editor.cursorStyle": "block",` 
1. open an editor 
2. :bug: see blinking block cursor shifting the letter down

https://github.com/microsoft/vscode/assets/16353531/d226b61d-e2bd-4f8c-ba3c-b9a939d2f1d7

Version: 1.88.0-insider
Commit: be210b3a60c7d60030c1d3d92da00d008edf6ab9
Date: 2024-03-15T06:00:06.808Z
Electron: 28.2.6
ElectronBuildId: 27476517
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.3.0

**Comment by hediet** [comment]
Introduced with https://github.com/microsoft/vscode/pull/207326

**Comment by nbarnwell** [comment]
I've been seeing this for years, and only just now bothered to check if it really was moving, or it's a red/green eye-test optical illusion thing. Sure enough, it really does move the character down a pixel or two. I Googled, and just found this issue that's only been open for 3 days! It'll probably never get fixed, but at least I know I'm not imagining it after all.
