### ISSUE TITLE
Scroll lock should not prevent scrolling in active editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#207818]
It seems today that when scroll locking is enabled, the active editor cannot scroll further down if the side editor is scrolled down. I would have expected that the active editor is always free to scroll anyway:

![Recording 2024-03-15 at 10 52 36](https://github.com/microsoft/vscode/assets/900690/1c00b5dd-c4cc-4704-ac41-5e69deee71bd)

**Comment by benibenj** [comment]
It seems like the notebook editor is blocking this. It works correctly with text editors. Looking...
