### ISSUE TITLE
Code Structure Panel

### ISSUE THREAD

**Issue by devDurgeshK** [microsoft/vscode#207996]
I request a feature of showing a Code structure panel which is also present in Pycharm which shows the classes and the functions inside it, or the `Symbols Panel` of github

![Screenshot (383)](https://github.com/microsoft/vscode/assets/149607456/c6331235-6640-4d25-b19f-abd08b23084d)

this feature i so helpful, because when the code is big consisting of 900-1000 lines of code. It would help to navigate in a code easily.

I hope this feature get added to VS Code Soon. or if it is not possible please atleast make a official extension for this. PLS.

**Comment by gjsjohnmurray** [comment]
Have you discovered the [Outline view](https://code.visualstudio.com/docs/getstarted/userinterface#_outline-view)?

**Comment by jrieken** [comment]
Yeah, outline it is.
