### ISSUE TITLE
Pty host unresponsive, shows every time when i run the code, and terminals stop working.

### ISSUE THREAD

**Issue by 7415-abhishek** [microsoft/vscode#207924]
Type: <b>Bug</b>

When i try to run my code pty host signal is broke down and shows the pty host is unresponsive please reload manually everytime and terminals stop working.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.26020
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.44GB free)|
|Process Argv|--crash-reporter-id 3b075fc4-3ac3-46c5-b069-ef8aef0ba5cd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
blackbox|Bla|1.2.71
vscode-eslint|dba|2.4.4
denigma|den|0.0.15
vscode-html-css|ecm|2.0.9
code-runner|for|0.12.1
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
remote-containers|ms-|0.348.0
cpptools|ms-|1.19.8
cpptools-extension-pack|ms-|1.3.0
java|red|1.28.1
LiveServer|rit|5.7.9
firacode|Sey|2.2.1
tabnine-vscode|Tab|3.77.0
vscode-pets|ton|1.25.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.56.2
vscode-java-dependency|vsc|0.23.5
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30991134
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470
7ghi1836:30988842

```

</details>

**Comment by 7415-abhishek** [comment]
please help me with this issue.

**Comment by meganrogge** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. 

/label upstream terminal-conpty windows
