### ISSUE TITLE
Starting vscode from windows `cmd` terminal prints odd blank line (empty newline)

### ISSUE THREAD

**Issue by Challanger524** [microsoft/vscode#207912]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2 (user setup)
- OS Version: Microsoft Windows [Version 10.0.19045.4046]

Steps to Reproduce:

1. open windows **cmd**
2. type: `code --disable-extensions`
3. see odd blank line in **cmd** window output (in **powershell** no blank lines)
```
Microsoft Windows [Version 10.0.19045.4046]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Daniil>code --disable-extensions

C:\Users\Daniil>
```

#### Problem context
It is preventing cmd window from closing automatically when launching **VS Code** from `Developer Command Prompt for VS 2022` via modified shortcut to load VS variables and launch code with one desktop shortcut:
```
%comspec% /C "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" && code
```
#### Workaround: redirect `code` output to `NUL`
```
%comspec% /C "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" && code > NUL
```

**Comment by meganrogge** [comment]
this is an issue external to vscode, thus closing as I cannot action it.

**Comment by Challanger524** [comment]
@Tyriar, may I ask to confirm/sanity_check @meganrogge's answer in which is assumed that:
- **odd blank line** printed in `cmd` **is** an **external issue** of the:
  - `windows terminal`, but not
  - `vscode`, despite
#### `cmd` is a time-proofed legacy windows interaction tool that is still being relied on, while..
#### `vscode` is yet another application that has `CLI`, that is maybe.. might.. likely working not correctly with lower-level environment
As for me - sound very "sane" and "logical"🙃

**Comment by Challanger524** [comment]
False alarm, it is literally what microsoft engineers back in the days set up `cmd` to do - to [print odd empty line after each command](https://stackoverflow.com/questions/71370820/avoid-line-break-at-end-of-cmd-output). No wonder they started to design new terminal - `powershell` without this weird _feature_.

Thank You, @meganrogge for _clearly stating_ that:
-  **This is by `cmd` Design** that obviously has no relation to `vscode` or any other console-application

> this is an issue external to...

Was interesting and baiting of yours to say:
- "this is an **issue**"
- because it is a `cmd` **feature** 🙂, you got me 😶
