### ISSUE TITLE
Show installed extensions before networked search complete when searching extensions

### ISSUE THREAD

**Issue by Legend-Master** [microsoft/vscode#207978]
You currently need to wait for the networked search to complete for the locally installed extension to show up, what about searching and showing the installed ones on top before the networked search complete?

I know that you can use `@installed` in the search box to only search for installed extensions, but that's just not as easy and intuitive as to just type the name you want to search for

https://github.com/microsoft/vscode/assets/68118705/c602715e-385d-4e04-9284-e726e53f7c7a

**Comment by sandy081** [comment]
You can always type `@installed rust` to search only installed extensions

**Comment by Legend-Master** [comment]
Yes I know, but it's not as easy and intuitive to just type the name

> I know that you can use `@installed` in the search box to only search for installed extensions, but that's just not as easy and intuitive as to just type the name you want to search for

I know it's a bit different, but the Windows (and also Android's) built-in search searches locally installed programs/files first and display them before the networked search, and I think it's pretty good and intuitive

**Comment by sandy081** [comment]
I think this is already requested. Can you please check our issues list - labeled `extensions` and find.

**Comment by Legend-Master** [comment]
I have searched before, and searched again with https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Aextensions+search but I can't find anything like this

I searched closed issues as well but there're way too many of them and I didn't find one like this

**Comment by sandy081** [comment]
This is supported now - we show the installed extensions on the top while searching.
