### ISSUE TITLE
Ctrl+C not working in "Open in Command Prompt" window

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#20798]
- VSCode Version: 1.9.1
- OS Version: Windows 10

Steps to Reproduce:

1. Right-click on a file and click "Open in Command Prompt"
2. Run some longer-running command and try to Ctrl+C to exit. No reaction.

When I do the same with a cmd window opened from outside VS Code then everything works as expected.

Related to #9347?

**Comment by Tyriar** [comment]
To clarify, you're launching an external `cmd.exe` terminal and ctrl+c isn't working?

**Comment by letmaik** [comment]
Exactly

**Comment by Tyriar** [comment]
Strange, I can't repro on Windows 10. Is there anything special about your setup? Are you on Windows Insiders or do you have vscode settings that might affect this?

**Comment by letmaik** [comment]
It's working on my Laptop currently (also standard Win 10), I have to 
try it again on my other machine tomorrow. Will report back.

**Comment by letmaik** [comment]
I just tested it on my other machine and can reproduce it. I don't have any relevant settings in vs code. I'm on the Anniversary Update version of Win 10.

Another difference is that the vscode launched prompt is 32 bits, which for example means I can't run  "bash" for some reason ( "'bash' is not recognized as an internal or external command, operable program or batch file.") When I set `"terminal.external.windowsExec": "C:\\Windows\\sysnative\\cmd.exe"` then bash works.

Another fact: When I use the integrated terminal in vs code (the powershell one) then I can ctrl+c without problems.

I tried changing `"terminal.external.windowsExec": "%COMSPEC%"` to `"terminal.external.windowsExec": "C:\\Windows\\sysnative\\cmd.exe"` to get a 64 bit prompt but same problem with ctrl+c. Equally when changing to  `"C:\\Windows\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"`.

**Comment by drumttocs8** [comment]
Having the same problem. Only seems to be an issue when using "Open in Command Prompt" from VSCode- and only sporadically. Sometimes Ctrl-C kills the process, sometimes it doesn't. 

In my case it's firebase serve that will still run even after Ctrl-C. But sometimes Ctrl-C does kill it as it should.

**Comment by Tyriar** [comment]
Cannot repro on Windows 10, if you have a ny more details to help reproduce please share. Please make sure you're on the latest version of Windows 10.

**Comment by The-Smallest** [comment]
I have same problem only if I open VSCode from console using `code .` command.
Pressing `Ctrl+Shift+C` opens command prompt that doesn't react to `Ctrl+C`.
Hope this helps.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/25195
