### ISSUE TITLE
package.json - contributes.configuration - JSON Schema

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#20791]
Can I use a `JSON Schema` in `contributes.configuration` to describe the settings of my extension?

Exaple:
```js
	"configuration": {
		"type": "object",
		"title": "My config",
		"properties": {
			"my.config": {
				"type": [
						"string",
						"object",
						"null"
					],
				"$schema": "./schema/my.config.json",
				"default": null
			}
		}
	}
```
---
http://json-schema.org/example2.html

**Comment by aeschli** [comment]
That's not really supported. It's expected that at least the properties and the default values are in the configuration. Also we encourage simple key value pairs for the configuration. 
But yes, you can do a $ref to an full URL. Relative URLs are not supported inside the configuration.
