### ISSUE TITLE
Extensition Can Not Be Selected After Move Extensition Panel To Secondary Side Bar

### ISSUE THREAD

**Issue by zengfan1992** [microsoft/vscode#207901]
Type: <b>Bug</b>

After Move Extensition Panel To Secondary Side Bar, Hovering the UI blocks operation of the extension. 

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:14:59.643Z)
OS version: Linux x64 6.5.0-25-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 6800H with Radeon Graphics (16 x 2971)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|14.80GB (11.22GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id ebf69402-dd5f-4b36-a786-e883e0ad019d --crash-reporter-id ebf69402-dd5f-4b36-a786-e883e0ad019d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
codeium|Cod|1.8.11
gc-excelviewer|Gra|4.2.59
auto-markdown-toc|hun|2.0.0
auto-day-night-theme-switcher|jak|0.2.1
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.87.2024031309
remote-ssh|ms-|0.109.0
shellman|Rem|5.7.0
file-git-history|sab|0.0.25
shell-runner-notebooks|tyl|0.0.2
vscode-icons|vsc|12.7.0
markdown-pdf|yza|1.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30986170
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30991133
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470
jchc7451:30973076

```

</details>

**Comment by roblourens** [comment]
Not sure what you're referring to, can you explain more or share a screenshot?

**Comment by zengfan1992** [comment]
![图片](https://github.com/microsoft/vscode/assets/115183414/a1ba2582-1b8e-4ec5-9d48-f21e0407151d)

**Comment by roblourens** [comment]
I think this was fixed in the latest release this week, can you confirm?
