### ISSUE TITLE
Prevent same file from being open in more than one editor (toggle)

### ISSUE THREAD

**Issue by ddotlic** [Microsoft/vscode#20792]
There is a [question about this on StackOverflow](http://stackoverflow.com/questions/39890926/visual-studio-code-prevent-same-file-opening-twice), but no answer given.

- VSCode Version: 1.10.0-insider
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Use any means to open a file, say Ctrl/Cmd+P, while the focus is in one of the editor groups
1. The file opens in that editor group
1. Move to any other editor group
1. Open same file, it is opened again, this time in the current editor group

While this behavior _is not incorrect in any sense_, it leads to proliferation of (same) files open which wastes memory, if not other resources. Honestly, I don't care about memory consumption, but mentally I am arranging files open (sometimes) to the left/right and would like the "stability" of the same file always being open in the same editor-group (I make sure that I open the file in question in the "appropriate" editor-group, I don't expect any kind of automatic placement).

It would be **really** nice if we'd have a toggle (boolean setting) which would toggle from current behavior (would be the default) and the one where however I open the file, if it's already open in an editor-group, it's simply focused there.

It might be naive, but I assume that this is a rather simple thing to implement.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7049

**Comment by ddotlic** [comment]
@bpasero Sorry for the duplicate but the language in the previous issue did not match what I looked for at all 😄
