### ISSUE TITLE
Mouse support in terminal is broken

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#20797]
Mouse support in the integrated terminal seems to be gone this morning. I can't use the mouse to switch between tmux panes any more. Did something change?

It works in stable.

**Comment by joaomoreno** [comment]
Strange... the issue's gone now...

**Comment by joaomoreno** [comment]
Oh it's back!

**Comment by Tyriar** [comment]
Haven't used mouse support in tmux, what are the repro steps?

**Comment by joaomoreno** [comment]
Set this in your `~/.tmux.conf`:

```
set -g mouse on
```

Then, in tmux: <kbd>Ctrl B</kbd><kbd>%</kbd> will open a new pane.

Clicking on each pane focuses it. This has worked flawlessly until today.

**Comment by Tyriar** [comment]
Seems to work for me, it's just that the click is flaky and sometimes doesn't switch the pane.

**Comment by Tyriar** [comment]
It actually appears to be sending the wrong coordinates. If you click further to the right for the second pane it works.

**Comment by Tyriar** [comment]
Upstream PR is out https://github.com/sourcelair/xterm.js/pull/556
