### ISSUE TITLE
Apt/yum repository should contain 32-bit packages

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#20790]
https://github.com/Microsoft/vscode/issues/2973

Currently we're blocked on the internal tool we're using to support 32-bit package submissions.

**Comment by richyarD** [comment]
Has anything changed since then?
Do you plan to maintain 32-bit repositories again?

**Comment by Tyriar** [comment]
We never supported 32-bit repos but we hope to eventually, as soon as our tooling is setup to do so.

**Comment by richyarD** [comment]
And what is ETA for setup tooling for this, if I may ask?

**Comment by Tyriar** [comment]
No ETA currently

**Comment by alvfig** [comment]
So, the only way to upgrade by now is manually download the latest 32-bit package and install it, right?

**Comment by Tyriar** [comment]
We will be following Electron's lead and dropping 32-bit support when we upgrade to Electron 4 https://github.com/Microsoft/vscode/issues/66271
