### ISSUE TITLE
About emmet

### ISSUE THREAD

**Issue by sherry-1775** [microsoft/vscode#207976]
I can't use emmet in vscode. I saw the page that said emmet is built right into Visual Studio Code, no extension required. But I can't  use it. There is no emmet setting, not even in the settings screen.
Does this issue occur when all extensions are disabled?: Yes
<img width="1646" alt="Screenshot 2024-03-18 at 14 58 36" src="https://github.com/microsoft/vscode/assets/163815664/8d0b146f-3299-44a7-aa25-89aac24a130f">

- VS Code Version:  1.87.2 (Universal)
- OS Version: macOS Sonoma Version14.4

Steps to Reproduce:

1. 

2.

**Comment by rzhao271** [comment]
If you search `@disabled` in the Extensions viewlet on the left, does Emmet show up?
