### ISSUE TITLE
downloading files in remote ssh directory causes crash

### ISSUE THREAD

**Issue by yangjinheng** [microsoft/vscode#207991]
Type: <b>Bug</b>

1. open a directory in a remote ssh
2. download a remote file

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.0-91-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12500H (16 x 3110)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.44GB free)|
|Process Argv|--folder-uri=vscode-remote://ssh-remote+quick03v.mm.bjat.qianxin-inc.cn/home/yangjinheng/project/quick-dba --crash-reporter-id 850b5e66-da6b-4b4b-b021-17b0c2593bb5|
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|SSH: quick03v.mm.bjat.qianxin-inc.cn|
|OS|Linux x64 5.15.0-91-generic|
|CPUs|Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz (16 x 2194)|
|Memory (System)|31.39GB (17.90GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
remote-explorer|ms-|0.4.3
vscode-sql-formatter|adp|1.4.4
shell-format|fox|7.2.5
go|gol|0.41.2
fracturedjsonvsc|j-b|3.1.2
clang-format|mjo|1.10.0
vscode-language-pack-zh-hans|MS-|1.87.2024031309
vscode-yaml|red|1.14.0
vscode-proto|san|0.0.6
cmake|twx|0.0.17
goctl|xia|0.1.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30986170
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30991133
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30958158
dsvsc020:30976470
jchc7451:30973076
7ghi1836:30988842

```

</details>

**Comment by rzhao271** [comment]
Hi @yangjinheng, does the issue still occur with VS Code 1.96 or later?
If so, could you attach a crash report following the steps at [Creating a Crash Report](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report)?
