### ISSUE TITLE
My  visual studio code will look like a sharpened texture on the screen

### ISSUE THREAD

**Issue by Vinny022305** [microsoft/vscode#207941]
Type: <b>Performance Issue</b>

It happen on March 4 2024 12:13 am 
it glitches my visual studio code after i installed a couple of extension to make my code colorful so i added some of extension like this "Prettier extension" "Them for java" like that extension and i have a picture of my screen rn how the glitch like virus happen on my laptop, if only i can send a picture of it

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.59GB free)|
|Process Argv|--crash-reporter-id 9542c1d1-8170-4ff1-bc7b-8e2b075d1eb2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   111	  6340	code main
    0	   160	  3416	extensionHost [1]
    0	    94	  8968	     electron-nodejs (server.js )
    0	   103	  9496	     "D:\Microsoft VS Code\Code.exe" "d:\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=3416
    0	   126	  4520	   gpu-process
    0	    98	  5800	window [2] (Issue Reporter)
    0	    85	 10260	fileWatcher [1]
    0	   193	 12460	window [1] (Web.html - WebDevelopment - Visual Studio Code)
    0	    98	 12984	shared-process
    0	    41	 13024	   utility-network-service
    0	    27	 18348	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Web.html - WebDevelopment - Visual Studio Code)
|    Folder (WebDevelopment): 8 files
|      File types: jpg(4) css(1) html(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-javascript-snippet-pack|aka|0.1.6
vscode-tailwindcss|bra|0.10.5
java-run|cao|1.1.4
javadebugger|don|0.1.5
java-debug|DSn|0.0.2
bracket-pair-toggler|dzh|0.0.3
vscode-html-css|ecm|2.0.9
html-preview-vscode|geo|0.2.5
vscode-language-babel|mgm|0.0.40
code-beautifier|mic|2.3.3
vscode-html-format|moh|0.1.6
vscode-dotnet-runtime|ms-|2.0.2
js-debug-nightly|ms-|2024.3.1117
vscode-typescript-next|ms-|5.5.20240314
vscode-css-peek|pra|4.4.1
java|red|1.29.2024031608
LiveServer|rit|5.7.9
vscode-javascript-booster|sbu|14.0.1
html5-boilerplate|sid|1.1.1
java-generate-setters-getters|soh|8.0.0
vscode-java-debug|vsc|0.56.2
vscode-java-dependency|vsc|0.23.5
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30986171
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30991134
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470

```

</details>

![image](https://github.com/microsoft/vscode/assets/159499668/5d911fa1-4828-4cbe-bd9c-47b506929c65)

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by Vinny022305** [comment]
> Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

Uhmm sir i dont know what that is sir i am new into this :(

**Comment by Vinny022305** [comment]
![image](https://github.com/microsoft/vscode/assets/159499668/81aeb34c-a0d2-45a9-8b71-06ee7948a96f)
still the same after i use an extension called Bisect

**Comment by pankajk280** [comment]
I tried installing all the extensions and some of them are deprecated but  not able to replicate the issue.
I guess its because of some extension.

**Comment by deepak1556** [comment]
Please enable the setting following the steps at https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

/duplicate https://github.com/microsoft/vscode/issues/124226
