### ISSUE TITLE
scrolling

### ISSUE THREAD

**Issue by Binhod07** [microsoft/vscode#207935]
Type: <b>Bug</b>

i'm using prettier formatter and when i save i come to the last line of code . how to fix it?

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.42GB (7.69GB free)|
|Process Argv|. --crash-reporter-id f4e1c716-ce72-45ac-b4f0-1578f609e36d|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
bootstrap5-vscode|Anb|0.4.4
blackbox|Bla|1.2.71
vscode-intelephense-client|bme|1.10.2
vscode-tailwindcss|bra|0.10.5
path-intellisense|chr|2.8.5
vscode-eslint|dba|2.4.4
es7-react-js-snippets|dsz|4.4.3
css-flexbox-cheatsheet|dzh|3.3.4
gitlens|eam|14.9.0
vscode-html-css|ecm|2.0.9
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
live-sass|gle|6.1.2
live-server|ms-|0.4.13
vsliveshare|ms-|1.0.5918
material-icon-theme|PKi|4.34.0
vscode-css-peek|pra|4.4.1
LiveServer|rit|5.7.9
autoimport|ste|1.5.4
tabnine-vscode|Tab|3.77.0
vs-gradient-maker|The|1.2.0
vscode-fontawesome-gallery|tom|0.0.7
errorlens|use|3.16.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.34.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30986171
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470
pythonait:30991152
gee8j676:30988843

```

</details>

**Comment by grgar** [comment]
prettier/prettier-vscode#3228
