### ISSUE TITLE
Terminal "Error 740"

### ISSUE THREAD

**Issue by michaelleepow90** [microsoft/vscode#207936]
Type: <b>Bug</b>

Whenever I try to start a new terminal, I keep getting this "error 740" error.. It reads as follows;

The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 740).
![Terminal Broken In Code](https://github.com/microsoft/vscode/assets/25166581/9011dfc7-6a7c-4e93-8f3a-2b51abf569ab)

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.12GB free)|
|Process Argv|--crash-reporter-id bd3c4491-c4f9-4b28-81a9-1cdc9bfe4fbe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
script-runner|eas|0.9.0
json-tools|eri|1.0.2
c-cpp-runner|fra|9.4.7
autofix|Lwl|1.0.0
run-cmd-extension|Mal|1.1.0
prettify-json|moh|0.0.3
csharp|ms-|2.22.3
vscode-dotnet-runtime|ms-|2.0.2
vscode-edge-devtools|ms-|2.1.5
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.8
live-server|ms-|0.4.13
powershell|ms-|2024.3.1
vscode-react-native|msj|1.12.3
bash-debug|rog|0.3.9
cmake|twx|0.0.17
windows-terminal|Tyr|0.7.0
vscode-lldb|vad|1.10.0
vscode-java-debug|vsc|0.56.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30986171
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30991133
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30958157
dsvsc020:30976470
gee8j676:30988843

```

</details>

**Comment by michaelleepow90** [comment]
Cool thanks 😊

**Comment by meganrogge** [comment]
The error code 740 means a requested operation requires elevation. It usually happens when you try to run a command that requires administrative privileges.
