### ISSUE TITLE
Two instances of VS Code running - If file is not saved and opening the same file again

### ISSUE THREAD

**Issue by anuraj** [Microsoft/vscode#20795]
- VSCode Version: 1.91
- OS Version: Windows 10 Version 1607 (OS Build 14393.693)

Steps to Reproduce:

1. Open a File using code <filename>
2. Modify the file, don't save it. And close VSCode.
3. Now open the same file again - It will display two VS Code instances.

Here is the screenshot

![image](https://cloud.githubusercontent.com/assets/276411/23061059/5feb1f6e-f526-11e6-8ea4-f9337da2648d.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16820
