### ISSUE TITLE
CTRL + C doesn't interrupt in terminal

### ISSUE THREAD

**Issue by haezera** [microsoft/vscode#207915]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.75.1 (But I have tried the newest release, and 1.77.3 as well)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:01.965Z (1 yr ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 23.2.0
Sandboxed: No

OS: MacOS Sonoma 14.2.1
Steps to Reproduce:

1. Install VS Code
2. Open terminal
3. CTRL + C works at the start - continues to work until opening a new project
4. Once opening a project, no longer works - and continues to not work even when restarting

Steps taken to debug:
- Cleared .zshrc
- Tried some alternative fixes suggested in similar bug report; but using ZSH compared to bash in the original report, as well, do not receive error message on terminal start as seen in the main bug report
- Tried installing older version of VS Code, as mentioned in main bug report
- Uninstalling all extensions

**Comment by meganrogge** [comment]
/duplicate [#205417](https://github.com/microsoft/vscode/issues/205417)
