### ISSUE TITLE
Git diff view having a nervous breakdown

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#20794]
Hard to repro, but here's what I did
1. Have changes in one .css file and on .ts file
2. Open git viewlet commit only the changes in the .ts file
3. Open the diff view on the remaining .css file - git view is computed the diff from the already commited .ts file and the current .css file
4. While doing that it seems to have some sort of an nervous breakdown. Apart from that code-helper goes to 100% cpu

![gidiffepilepsy](https://cloud.githubusercontent.com/assets/1926584/23060490/3a42c5d2-f4fe-11e6-831b-0f5c7efab73e.gif)

**Comment by joaomoreno** [comment]
Please try to repro once again!

**Comment by isidorn** [comment]
1. Open debug.contribution.css , remove lines 246 - 249
2. Open workbench.ts change line 853 to be StorageScope.GLOBAL
3. Open git view - commit only the workbench.ts
4. Click on debug.contribution.css

**Comment by chrmarti** [comment]
There is still something going on with https://github.com/Microsoft/vscode/commit/d196389f53892f053a877fda30a84c04d6c3ed01. I just had the diff on the only file changed open and the left side was showing a different file that I had worked on just before. Trying to reproduce.

**Comment by chrmarti** [comment]
No steps to reproduce yet, seems to happen randomly when switching editors:
![wrong_left_side](https://cloud.githubusercontent.com/assets/9205389/23072299/1629c690-f4e6-11e6-9c60-b1ea307efeff.png)

**Comment by joaomoreno** [comment]
@chrmarti That was fixed by 50f8848e44029ffabf0727de49cd18ae4069b4fe

Already built and released a new version with that fix, make sure you get that update.
