### ISSUE TITLE
cannot open a txt file that use gb2312 encoding correctly on windows

### ISSUE THREAD

**Issue by kissstudio** [Microsoft/vscode#208]
so need click the file encoding tips on status bar and choose reopen with encoding then select gb2312 encoding.

windows version 10.

**Comment by takumif** [comment]
Please use English in this repository. 在這個repository請你用英文。

He's saying that when he tries to open a document that uses GB 2312 the encoding gets messed up, and to get it to display properly he must first reopen the file then choose GB 2312.

**Comment by kissstudio** [comment]
TKS takumif

**Comment by bpasero** [comment]
@kissstudio so it works after you changed the encoding from the status bar?

**Comment by kissstudio** [comment]
yes it is.

**Comment by bpasero** [comment]
You can change the workspace encoding for all files in settings. We currently dont support this on a per file base.

**Comment by kissstudio** [comment]
the notepad.exe can do but vscode can not?
I think add a file encoding detect from file header bytes(file BOM ) can solve this issue. wish it works some day.

**Comment by bpasero** [comment]
@kissstudio yeah we do BOM detection but from my knowledge there are only BOMs for UTF 8, 16 LE and 16 BE. If you can tell me the BOM for your encoding I am happy to add it!

**Comment by kissstudio** [comment]
@bpasero 
I checked, when txt file saved as ANSI using notepad, its no BOM!
I don't know how notepad can open it correctly even its gbk encoding(gb2312 or gb10830 and more) .

if I found how it works I will be here again.

**Comment by bpasero** [comment]
:+1:
