### ISSUE TITLE
[VSCode insider] Warning: Missing GLIBCXX >= 3.4.25! from /usr/lib64/libstdc++.so.6.0.19

### ISSUE THREAD

**Issue by perrog** [microsoft/vscode#208097]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.88.0-insider
- OS Version: CentOS7/RHEL7

It looks like latest build of 1.88.0-insider (commit 7c51753f7ce936a7aeb84ac881818c35c5a9ab8d) have some C/C++ runtime gotchas on older systems. 

Steps to Reproduce:

1. Open VSCode insider
2. Remote ssh connect to CentOS7 server
3. New code server insider is downloaded, but the upgrade failed. A message is showed:

```
Failed to connect to the remote extension host server (Error: WrappedError(WrappedError {
message: "error checking server integrity", original: "failed to run command \"/home/myuser/.vscode-server-insiders/cli/servers/Insiders-7c51753f7ce936a7aeb84ac881818c35c5a9ab8d.staging/server/bin/code-server-insiders --version\" (code 100): Warning: Missing GLIBCXX >= 3.4.25! from /usr/lib64/libstdc++.so.6.0.19\n
Warning: Missing GLIBC >= 2.28! from /usr/lib64/libc-2.17.so\n
Warning: Missing required dependencies.
Please refer to our FAQ https://aka.ms/vscode-remote/faq/old-linux for additional information.\n" }))
```

**Comment by perrog** [comment]
Is there any easy way to switch back to previous build from 18th march? (commit 9ccb0fa738a2f7a1c5328800c9fe18f4dd5b4f8a)

**Comment by plwalsh** [comment]
Sounds to be the same as https://github.com/microsoft/vscode/issues/206790#issuecomment-2007163821. They recommend rolling back like you did, and disabling updates.

**Comment by plwalsh** [comment]
The last insiders version that works is `9ccb0fa738a2f7a1c5328800c9fe18f4dd5b4f8a`.

You can download the installer by clicking the `"url"` link from:  
https://update.code.visualstudio.com/api/versions/commit:9ccb0fa738a2f7a1c5328800c9fe18f4dd5b4f8a/win32-x64/insider

If you need the User installer instead, just copy/paste the `"url"` into the address bar and change the executable name to `.../VSCodeUserSetup-<version>.exe`.

And then don't forget to also set the `update.mode` setting to either `none` or `manual`.
