### ISSUE TITLE
Cannot see inline test coverage in editor

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#208055]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.88.0-insider
Commit: b356b209a5a41743b45f25d569a7afb733d347a9
Date: 2024-03-18T16:36:07.814Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.88.0-insider Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36

The editor inline coverage decoration is missing in the latest Insiders. @connor4312

**Comment by connor4312** [comment]
Looks like a gap in our backwards-compatibility shim, I'll fix it

**Comment by connor4312** [comment]
Looks like a gap in our backwards-compatibility shim. It'll be fixed once you update to the new API

**Comment by jdneo** [comment]
I still cannot see the inline decoration after update to the new API.

Below is how I add coverage to the TestRun:

```ts
for (const sourceFileCoverage of sourceFileCoverages) {
    const uri: Uri = Uri.parse(sourceFileCoverage.uriString);
    const detailedCoverage: FileCoverageDetail[] = [];
    for (const lineCoverage of sourceFileCoverage.lineCoverages) {
        const branchCoverages: BranchCoverage[] = [];
        for (const branchCoverage of lineCoverage.branchCoverages) {
            branchCoverages.push(new BranchCoverage(branchCoverage.hit, new Position(lineCoverage.lineNumber - 1, 0)));
        }
        const statementCoverage: StatementCoverage = new StatementCoverage(lineCoverage.hit,
            new Position(lineCoverage.lineNumber - 1, 0), branchCoverages);
        detailedCoverage.push(statementCoverage);
    }
    for (const methodCoverage of sourceFileCoverage.methodCoverages) {
        const functionCoverage: DeclarationCoverage = new DeclarationCoverage(methodCoverage.name, methodCoverage.hit,
            new Position(methodCoverage.lineNumber - 1, 0));
        detailedCoverage.push(functionCoverage);
    }
    run.addCoverage(FileCoverage.fromDetails(uri, detailedCoverage));
}

```

**Comment by jdneo** [comment]
And I cannot see the method coverage when I expand the file node in the coverage explorer:

https://github.com/microsoft/vscode/assets/6193897/8b789918-0610-4666-8e90-69d4f37911df

**Comment by connor4312** [comment]
Please note that FileCoverage doesn't contain `detailedCoverage` and you _must_ implement `TestRunProfile.loadCoverageDetails` to provide that data

**Comment by jdneo** [comment]
Thank you for the answer. I have a feeling that the current API is a little bit confusing between `TestRunProfile.loadCoverageDetails()` and `FileCoverage.fromDetails()`.

I feel like the current API is encouraging to first provide a rough coverage and then resolve details by calling `TestRunProfile.loadCoverageDetails()`. Then what's the purpose of `FileCoverage.fromDetails()`. If I already have the details, why I need to resolve it again?

**Comment by connor4312** [comment]
Yea, we were having some discussion about `fromDetails` potentially being misleading. But it is pretty useful for extensions that go straight to having details (potentially common if loading simple coverage from a file without extra processing) to avoid having to have them calculate things manually.

**Comment by jdneo** [comment]
> But it is pretty useful for extensions that go straight to having details

Yes, that's the case in Java. I can now cache the details and provide them when `TestRunProfile.loadCoverageDetails()` gets called.

**Comment by ioquatix** [comment]
@connor4312 it's not really obvious how we are supposed to use `loadCoverageDetails`.

Currently, we use this to create a TestRunProfile:

```
this.controller.createRunProfile('Coverage', vscode.TestRunProfileKind.Coverage, this.runHandler.bind(this), true, undefined, true);
```

Are we just supposed to monkey patch `loadCoverageDetails` into the returned object?

**Comment by connor4312** [comment]
The docs might be helpful in answering your question: https://code.visualstudio.com/api/extension-guides/testing#test-coverage

Let me know if not

**Comment by ioquatix** [comment]
Shouldn't the signature of `loadDetailedCoverage?: (testRun: TestRun, fileCoverage: FileCoverage, token: CancellationToken) => Thenable<FileCoverageDetail[]>` actually be `Thenable<readonly FileCoverageDetail[]>`?

**Comment by ioquatix** [comment]
Here is what I had to to do to add support for coverage:

https://github.com/ioquatix/sus-vscode/commit/0e7928c1ac090087a568096873fa779db67ff27c#diff-338884a8f8daeba218cad1bcbc49ed303b6343686ad9f0d2303bfbd11c102ce3R187-R195

I'm not really convinced that is a great interface... but it works.

Any thoughts on how to load coverage from disk without running any tests? Coverage data is persisted in my case.

**Comment by connor4312** [comment]
You can call `profile.createTestRun` at any time and report coverage data there without reporting any test results.
