### ISSUE TITLE
Folders getting added from other directories

### ISSUE THREAD

**Issue by SmarTi01** [Microsoft/vscode#20803]
I believe this occurs while i have multiple instances of VSC open at the same time, folders seem to get added from other directories with the currently opened tree.

- VSCode Version: 1.9.1
- OS Version: Windows & Enterprise

Steps to Reproduce:

RANDOM

**Comment by bpasero** [comment]
@SmarTi01 can you share a screenshot or video what you mean?

**Comment by SmarTi01** [comment]
Hey bpasero.  I cant give you screen shots as i use this at work so its confidential.  However, it looks like this happens when i have two or more VSCode IDE's open at the same time.  What i think is going on is that if i save on one, then those files seem get saved into the other
