### ISSUE TITLE
Debug launch command should not append to input buffer in debug console

### ISSUE THREAD

**Issue by psychedelicious** [microsoft/vscode#208051]
### Current Behaviour

When launching a debugger with the integrated terminal, VSCode does a few things:
1. Create and/or focus a dedicated terminal - the "debug console"
2. Paste the launch command into the terminal's input buffer _without clearing the existing input buffer_
3. Execute the terminal input buffer

Any text left in the input buffer is concatenated with the launch command and executed.

### Use Case

Because the debug console is otherwise a normal interactive terminal, I often run some commands in it. Sometimes, I start typing a command but never execute or clear the input buffer, then launch a debugger. Usually, the command just fails because the resulting concatenated input buffer is gobbledygook. 

But today, I made a whoopsie. I had typed `rm -rf` in the input buffer an hour or so ago - can't remember why - then changed gears. Having forgotten that I left those particular 6 characters in the input buffer, I pressed F5 to start debugging.

`rm -rf` was concatenated with the debug command, which starts with `cd /path/to/repo;`. That resulted in `rm -rf cd /path/to/repo;` which VSCode cheerfully executed. `./cd` didn't exist, but `/path/to/repo` sure did - if only for a few more milliseconds.

### Desired Behaviour

Clear the terminal's input buffer before pasting and running the debugger's launch command.

**Comment by psychedelicious** [comment]
Note: When I ran into the issue earlier, my terminal was in a different directory than the repo root. 

If I'm in the repo root with a python venv set up for the workspace, the launch command starts with something much scarier: `/usr/bin/env` -> `rm -rf /usr/bin/env`. Yikes!

**Comment by roblourens** [comment]
This should be fixed now in Insiders https://github.com/microsoft/vscode/issues/106743

**Comment by psychedelicious** [comment]
Thanks @roblourens. Sorry I missed the existing bug report and PR.
