### ISSUE TITLE
Output window does not focus on the last output line

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#20806]
- VSCode Version: 1.10.0-insider
- OS Version: Win 10

Steps to Reproduce:

0. Initialise git repository in the project folder, work with some files (to produces git output in Output window).
1. Try to commit something that produces the following git operation error:
![image](https://cloud.githubusercontent.com/assets/2239563/23067049/ce41bf76-f51d-11e6-853b-8b061df9569b.png)
2. Press 'Show Output' button.
3. Output window does not scroll to the most bottom, where the error is most likely present.

Expectation:
Focus on the last line.

ping @isidorn

**Comment by isidorn** [comment]
Can not reproduce. I always get the last line revealed which can be seen in the attached gif
Please let me know if you can constantly reproduce this and I will reopen and we can investigate together.

![gitcommit](https://cloud.githubusercontent.com/assets/1926584/23132432/dc0c4bfe-f78d-11e6-904a-15fb55741312.gif)

**Comment by michelkaporin** [comment]
I can reproduce it, please speak to me when you have time.

**Comment by isidorn** [comment]
Not important, assining to march to investigate then

**Comment by isidorn** [comment]
Please check  this again since there were users saying this is no longer happening.
If you still see it we will look together on Monday on your machine

**Comment by michelkaporin** [comment]
No longer happening.
