### ISSUE TITLE
Scrolldown issue

### ISSUE THREAD

**Issue by goktugerol-dev** [microsoft/vscode#208032]
![Captura de pantalla 2024-03-18 124526](https://github.com/microsoft/vscode/assets/92269361/6bad68f8-b096-4329-90a3-c9ed569f7445)

![Captura de pantalla 2024-03-18 131335](https://github.com/microsoft/vscode/assets/92269361/b94658a9-3e10-4872-925b-0a75e4310bc4)

(Look at the line numbers)

This bug has been present for a month, and I haven't reported it because I thought it would be fixed soon. However, it's starting to become annoying, distracting and affecting me to see the part I'm working on... 
I've tried it on three different computers (Mac, Linux, and Windows 11), and I encountered the same issue on all of them.

I've also tried different themes and even with the default ones, but the issue persists, so I don't think it's a theme-related problem.

When scrolling down, a portion of the code remains fixed on the upper part, as shown in the image.

VS Code Version: 

Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621

Does this issue occur when all extensions are disabled?: Yes, tried with a clean vs code with no extensions and see the same result.

Steps to Reproduce:

1.  Open a code file
2. Scroll down, you will see the issue.

**Comment by Lightfire228** [comment]
This is a new feature called "Sticky Scrolling"

To disable it, open the command pallet, and type "View: Toggle Editor Sticky Scroll"

**Comment by goktugerol-dev** [comment]
> This is a new feature called "Sticky Scrolling"
> 
> To disable it, open the command pallet, and type "View: Toggle Editor Sticky Scroll"

Thanks for letting me know that, it's not a bug, its a feature. I disabled and now everything is perfect.
