### ISSUE TITLE
Models getting disposed randomly

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2080]
I am still from time to time seeing errors where the code editor model seems to be disposed while the workbench model thinks the model is still alive:

![image](https://cloud.githubusercontent.com/assets/900690/12387033/01a90fd6-bdca-11e5-9b06-3334a08491b0.png)

This one happened after unstaging a change in sash.ts and then trying to open it.

@jrieken @alexandrudima fyi, any ideas who would still dispose models without going through the workbench?

**Comment by jrieken** [comment]
Hard to tell, after my change of only disposing documents from [contributed](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostDocuments.ts#L176) schemes I haven't seen this...

**Comment by alexandrudima** [comment]
I haven't seen this either.

**Comment by jrieken** [comment]
@bpasero please reopen if this remains
