### ISSUE TITLE
Grey code with no reasons

### ISSUE THREAD

**Issue by thistlillo** [microsoft/vscode#208020]
All of a sudden, I have my code greyed out in Python notebook cells.

<img width="379" alt="Screenshot 2024-03-18 at 16 12 33" src="https://github.com/microsoft/vscode/assets/6717655/ef85bb6f-9de3-4311-8635-714b75e7617d">

after line 28 the code is grey, but it is clearly reachable (actually, run).

Why?

Using VSC:
```
Version: 1.86.2
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:42:12.210Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.4.0
```

on MacOS Sonoma 14.4.

The interpreter is Python 3.8.18 in a conda environment.

**Comment by thistlillo** [comment]
Ok, understood.

See these examples:

This is fine:
<img width="570" alt="Screenshot 2024-03-18 at 16 28 41" src="https://github.com/microsoft/vscode/assets/6717655/84e21b2f-f585-45fe-936c-ce5a3a05a588">

This is also fine. Line 7 generates an error and line 8 is never executed.
<img width="653" alt="Screenshot 2024-03-18 at 16 29 31" src="https://github.com/microsoft/vscode/assets/6717655/a667cfdc-d4ce-433a-9b5d-837838132e87">

This is not fine at all:
<img width="520" alt="Screenshot 2024-03-18 at 16 30 40" src="https://github.com/microsoft/vscode/assets/6717655/40457428-dd7d-4575-88bf-ff6ca540457f">

I think I need to move this bug report somewhere else.

**Comment by racng** [comment]
I also have similar problem where the entire second half of a python file has dimmed text for no reason.

Using MacOS Sonoma 14.3.1
Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:57.520Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0

**Comment by lszomoru** [comment]
@rebornix, could you please help triage this issue? Thanks!

**Comment by stefanverbeeck** [comment]
I can confirm that this is also happening on normal .py files, not just in notebook cells.
Error is coming from Pylance, message is "Code is unreachable"
![image](https://github.com/microsoft/vscode/assets/5901500/c9881d10-55dc-48b0-8525-be2e9f6b5414)

Pylance version v2024.3.1

Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by thistlillo** [comment]
After some searching I found this:

https://github.com/microsoft/pylance-release/issues/5630

Downgrading pylance fixed the issue in my case.

**Comment by rebornix** [comment]
Yep this is a regression in the Pylance extension.
