### ISSUE TITLE
intellisence not working in cshtml files

### ISSUE THREAD

**Issue by vicana8635** [microsoft/vscode#208010]
Type: <b>Bug</b>

C# code is recognized, but html tags are not being auto closed.  If you click a div tag, for example, it no longer shows you the corresponding closing div tag.

VS Code version: Code 1.87.2 (Universal) (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin x64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|32.00GB (0.99GB free)|
|Process Argv|--crash-reporter-id 5810f138-bf4e-4fcd-b883-3372e440e6d4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
nugetpackagemanagergui|ali|2.0.6
todo-tree|Gru|0.0.226
azure-dev|ms-|0.8.1
vscode-azureappservice|ms-|0.25.2
vscode-azurefunctions|ms-|1.13.4
vscode-azureresourcegroups|ms-|0.8.4
vscode-cosmosdb|ms-|0.20.1
csdevkit|ms-|1.4.29
csharp|ms-|2.22.3
vscode-dotnet-runtime|ms-|2.0.2
azure-account|ms-|0.11.6
vscode-node-azure-pack|ms-|1.2.0
vsliveshare|ms-|1.0.5918

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by aeschli** [comment]
The Razor support comes form an extension like https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp

Please file the issue there: https://github.com/dotnet/vscode-csharp
