### ISSUE TITLE
Branch picker shows one icon in colors

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#208089]
![image](https://github.com/microsoft/vscode/assets/900690/8faed382-e8a0-4019-88d4-53e206b914c8)

Notice the red icon, I find that somewhat unexpected.

//cc @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
I bisected this to https://github.com/microsoft/vscode/commit/7674d5634504300a295f0b177c3dd54053680181

@roblourens gonna add you to assignees.

**Comment by lszomoru** [comment]
Thanks @TylerLeonhardt for tracking this down.
