### ISSUE TITLE
Save and load editor layout

### ISSUE THREAD

**Issue by ivanlaerhoven** [microsoft/vscode#208039]
Currently it's not possible to save my preferred layout of the editor (positions and sizes of panes, sidebars etc.) It would be nice if we can save multiple custom layout configurations and load them.

**Comment by ArturoDent** [comment]
See this extension: [Restore Editors](https://marketplace.visualstudio.com/items?itemName=amodio.restore-editors).  It may do what you want.

Also see [Allow extensions to get the current editor layout](https://github.com/microsoft/vscode/issues/94817#top)](https://github.com/microsoft/vscode/issues/94817)

It is not possible to do what you want currently without an extension.

**Comment by sandy081** [comment]
Please try profiles - https://code.visualstudio.com/docs/editor/profiles - that supports saving your global customisations.
