### ISSUE TITLE
Restart to update does not update VSCode

### ISSUE THREAD

**Issue by madkrupt** [microsoft/vscode#208011]
Type: <b>Bug</b>

Sometimes it will restart the application, but it still wants to update, the notification is on the settings icon, and the restart to update options does not go away.  Not sure if this could be a plugin conflict of some sort or has anything to do with my config specifically.  I am going to try to manually updated.

VS Code version: Code - Insiders 1.88.0-insider (Universal) (99a19815253d91900be5ec1016e0ecc7cc9a6950, 2024-03-14T05:50:25.208Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 9, 11|
|Memory (System)|64.00GB (1.47GB free)|
|Process Argv|--crash-reporter-id a83c3ccd-0a3b-4fe6-932d-712ed8e7cfe4|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
python-environment-manager|don|1.2.4
applescript|idl|0.25.1
vscode-circuitpython|joe|0.2.0
har-analyzer|Mat|0.0.11
vsc-webshark|mbe|2.1.0
vscode-docker|ms-|1.29.0
vscode-edge-devtools|ms-|2.1.5
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.110.2024030815
remote-ssh-edit|ms-|0.86.0
azure-account|ms-|0.11.6
azurecli|ms-|0.6.0
cpptools|ms-|1.19.8
js-debug-nightly|ms-|2024.3.1117
powershell|ms-|2024.3.1
remote-explorer|ms-|0.5.2024031109
vscode-serial-monitor|ms-|0.11.240217001
pico-w-go|pau|3.7.5
java|red|1.29.2024031808
code-spell-checker|str|3.0.1
open-in-browser|tec|2.0.0
shellcheck|tim|0.37.0
har-viewer|unc|0.0.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-arduino|vsc|0.6.230727001
vscode-java-debug|vsc|0.56.2024022605
vscode-java-dependency|vsc|0.23.2024022305
vscode-java-pack|vsc|0.25.2023121402
vscode-java-test|vsc|0.40.2024030709
vscode-maven|vsc|0.44.2024013105
vscode-icons|vsc|12.7.0
cors-browser|Wsc|1.0.11

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:30784851
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:30986170
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
d6fi2104:30968146
cppperfnew:30980852
d34g3935:30961436
fegfb526:30952798
bg6jg535:30979844
ccp2r3:30958153
pythonait:30973460
666c4381:30973073
gee8j676:30988845

```

</details>

**Comment by IllusionMH** [comment]
Is it sometimes? Please check what commit value is in About modal.

With insiders there might be few releases in one day so if new version is released after update was initially downloaded but before you restart to update - new version will be pulled after initial restart/update.

**Comment by madkrupt** [comment]
Hey, Sorry I didn't get back to you on this.  I believe it was an issue with APFS metadata that was causing the application to run in Translocation Mode.  Since I have fixed the metadata values (not sure how they got into a bad state, but MacOS metadata and the Built-in Security Systems can be confusing).
