### ISSUE TITLE
Insider: Extensions that require "Restart" can't be Restarted..

### ISSUE THREAD

**Issue by Raydir** [microsoft/vscode#208076]
Type: <b>Bug</b>

With the latest Insider-build it seems to be impossible to install new extensions when they need to reload the client.
It always shows the "Restart Extension" button which is not "clickable".

![image](https://github.com/microsoft/vscode/assets/17499573/35bef5f2-bd13-4e33-b2f2-2a480044e47f)

I did not have that Problem this morning or yesterday, so it should be a issue with the latest release!

Regards
Raydir

VS Code version: Code - Insiders 1.88.0-insider (7c51753f7ce936a7aeb84ac881818c35c5a9ab8d, 2024-03-19T05:48:31.453Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (17.70GB free)|
|Process Argv|--crash-reporter-id 5f16a62a-f4df-431c-89e3-93b380c89093|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
depot|aft|1.6.1
Bookmarks|ale|13.4.2
cucumberautocomplete|ale|2.15.2
tsl-problem-matcher|amo|0.6.2
ng-template|Ang|17.3.0
jsoncrack-vscode|Ayk|2.0.2
Bito|Bit|1.3.0
npm-intellisense|chr|1.4.5
regex|chr|0.4.0
codium|Cod|0.7.52
vscode-eslint|dba|2.4.4
githistory|don|0.6.20
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.9.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
windows-explorer-context-menu|ele|3.2.1
vscode-great-icons|emm|2.1.102
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.5.0
vscode-github-actions|git|0.26.2
gc-excelviewer|Gra|4.2.59
todo-tree|Gru|0.0.226
vscode-test-explorer|hbe|2.21.1
ilspy-vscode|ics|0.18.0
easy-icons|jam|0.3.1
vscode-edit-csv|jan|0.9.1
vscode-codemetrics|kis|1.26.1
json-to-ts|Mar|1.7.5
vscode-language-pack-de|MS-|1.87.2024031309
csharp|ms-|2.22.5
vscode-dotnet-runtime|ms-|2.0.2
hexeditor|ms-|1.9.14
powershell|ms-|2024.0.0
test-adapter-converter|ms-|0.1.9
vscode-typescript-next|ms-|5.5.20240318
typescript-docs|Nat|0.2.0
copy-json-path|nid|0.4.0
docthis|oou|0.8.2
f-script|Opa|23.2.1
opacc-fscript-debug|Opa|16.20.1
webapplicationservices-language-server|Opa|23.2.1
vscode-versionlens|pfl|1.9.2
tsimporter|pmn|2.0.1
vscode-thunder-client|ran|2.19.5
testcafe-test-runner|rom|2.1.1
serenade|ser|1.5.3
trailing-spaces|sha|0.4.1
addDocComments|ste|0.0.8
xml2jsoneditor|vyu|0.2.2
vscode-json-path|wei|2.4.0
cors-browser|Wsc|1.0.11
cursorCharCode|zei|0.2.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aa:30263845
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:30784851
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
9b8hh234:30694863
pythongtdpath:30726887
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
bf62j303:30968145
pydisww1:30991133
cppperfnew:30980852
8082a590:30961435
fegfb526:30952798
bg6jg535:30979844
ccp1r6:30958151
pythonait:30973460
7ghi1836:30988844

```

</details>

**Comment by Raydir** [comment]
even after restart of VSCode Insider i can't "load" the Extension:
![image](https://github.com/microsoft/vscode/assets/17499573/048349bb-ddf9-4771-a7ab-b3422a37b0eb)

When clicking on "Restart Extension" nothing happens.

**Comment by Raydir** [comment]
I also tried if this happens only when i install from vsix (thus this is a preview for next version of the extension).
This seems not to be the case. even when i completly remove the extension and install it new from marketplace (official release) the same problem occurs.

**Comment by sandy081** [comment]
What message do you see when you hover on **Restart Extensions** button??

**Comment by Raydir** [comment]
@sandy081  it says "Reload  VS Studio Code to activate this Extension" (translated from german...)

As I see  you fixed this already - gonna retry it when insider build is available.

Thank you!

**Comment by Raydir** [comment]
Works fine again - THANX.
