### ISSUE TITLE
VSC cutting off code in Ubuntu 16.04

### ISSUE THREAD

**Issue by cadetiii** [Microsoft/vscode#20808]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.8.0-36-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Open Visual Studio Code
2. Open file from WebDav site.
3. Note the number of lines is reduced.  In my case, from 128 to 63.  Verified code was still intact in original file, tried copying/pasting code from text editor, to get it to appear in visual studio code, only lasted as long as I had not saved the file.
4. I have _not_ uninstalled and reinstalled yet.  

Will do so next.  Will update if this resolves.

**Comment by bpasero** [comment]
@cadetiii to clarify you are opening a file with 128 lines and it only shows 63? can you attach the file?
