### ISSUE TITLE
Can't download extensions behind a proxy.

### ISSUE THREAD

**Issue by NicoCroce** [Microsoft/vscode#20809]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|angular1-code-snippets|alexandersage|0.0.3|
|copy-relative-path|alexdima|0.0.1|
|path-intellisense|christian-kohler|1.2.0|
|githistory|donjayamanne|0.1.5|
|Theme-Monokai-Soft-MD|gerane|0.0.2|
|spacegray-vscode|ionutvmi|1.1.4|
|vscode-multiclip|slevesque|0.1.2|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1.
2.

**Comment by dresoy** [comment]
Same problem over here!

**Comment by FloMaetschke** [comment]
Can you provide some input in #18103 ?
