### ISSUE TITLE
Paste with syntax highlighting is not pasting empty lines

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#20811]
- VSCode Version: VS Code Insiders from 2/17/17
- OS Version: Windows 10

Steps to Reproduce:

1. Write some code in a syntax highlighted language like PowerShell which has empty lines between real lines:

```powershell
Set-StrictMode -Version Latest
$ErrorActionPreference='stop'

Import-Module "$PSScriptRoot\DSCEngineering\helpers\LogUtility.psm1"
Import-Module "$PSScriptRoot\DSCEngineering\helpers\ToolUtility.psm1"

# In case of DevWorkflow, this script will be bin placed to <DscRepoRoot>\build\x64fre\bin\Tools
# Workflow for generating package to be handed over to OMS
```

2. Copy the snippet of code and paste it into a new email in Outlook.  The result looks like this:

![image](https://cloud.githubusercontent.com/assets/79405/23068850/1356b2e0-f4da-11e6-9ff6-b0f28a81cd1f.png)

Notice that the two blank lines are not retained.

/cc @rebornix

**Comment by rebornix** [comment]
This is when HTML eats you plain text line break or whitespaces :(

**Comment by daviwil** [comment]
Awesome, thanks!
