### ISSUE TITLE
Review diff algorithm API

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#20818]
cc @alexandrudima 

In order to implement range staging/unstaging, I had to expose the diff algorithm in the API.

```typescript
	export interface LineChange {
		readonly originalStartLineNumber: number;
		readonly originalEndLineNumber: number;
		readonly modifiedStartLineNumber: number;
		readonly modifiedEndLineNumber: number;
	}

	export function computeDiff(oneDocument: TextDocument, otherDocument: TextDocument): Thenable<LineChange[]>;
```

https://github.com/Microsoft/vscode/blob/9703537e62075a6c9edd85133c22f601c5f25182/src/vs/vscode.proposed.d.ts#L158-L165

I'm not entirely happy as to how that looks like.

@jrieken Do you have any ideas how we can improve this? Maybe we could add it to the `workspace` namespace, since it computes diffs on TextDocuments.

**Comment by jrieken** [comment]
I don't see `LineChange` being referenced anywhere in the API? Is this just a util?

**Comment by joaomoreno** [comment]
It's the result of the `computeDiff` function.

**Comment by jrieken** [comment]
I understand that but I don't see the contract? The API doesn't expect the result to passed in to some operation, right? Nor does the API call the compute-function, right? Is this just a util-function?

**Comment by jrieken** [comment]
Apart from finding it hard to justify such a utility API there are major performance concerns. Diff'ing is inherently slow, 5yrs back it was one of the first web worker consumers, and *should therefore not* be executed in the extension host.

**Comment by alexandrudima** [comment]
I'm also not really sure. 

Running `computeDiff` on [the same two inputs might yield different results](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/diff/diffComputer.ts#L317).

Perhaps we need a special purpose command that retrieves the actual displayed diff in the UI... Or perhaps it can be on the new SCM specific API that it is possible to register a diff command that will always be called with certain arguments, that also include the diff.

**Comment by joaomoreno** [comment]
> Running `computeDiff` on [the same two inputs might yield different results](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/diff/diffComputer.ts#L317).

That's not very good news.

> Perhaps we need a special purpose command that retrieves the actual displayed diff in the UI

Feels like a hack, but it could work for my specific use case.

**Comment by alexandrudima** [comment]
There's always the third option:

> Or perhaps it can be on the new SCM specific API that it is possible to register a diff command that will always be called with certain arguments, that also include the diff.

e.g.
```js
vscode.scm.registerDiffEditorCommand('bla', function(diff) {
   // diff is the current diff info displayed in the editor.
});
```

The main side would then make sure to invoke such commands always with the diff information.

**Comment by jrieken** [comment]
Yeah, there are asks for us exposing the diff editor. It sounds like that could solve this issue by exposing the currently showing diff. It would also align with `registerDiffEditorCommand`

**Comment by alexandrudima** [comment]
@jrieken We should expose think of ways to expose this information in a "non-eager" way.

Pushing the diff changes every time it is computed on the UI thread to the extension host (only to have nobody use it 99% of the time) is too much IMHO.

**Comment by jrieken** [comment]
Yeah, that's an API design thing of having it sync there or not. In general diff editors are open too often I would say and having a lone 'diffEditorCommand' might be unexpected

**Comment by joaomoreno** [comment]
Reviewed!
