### ISSUE TITLE
Inline Completions ghost text flashes on VSCode 1.87 for word-by-word accepts (ghost text did not disappear on 1.86)

### ISSUE THREAD

**Issue by dandua98** [microsoft/vscode#208152]
Does this issue occur when all extensions are disabled?: Not relevant

- VS Code Version: 1.87.2
- OS Version: MacOS Sonoma 14.3 (23D56)

Steps to Reproduce: Use word-by-word/line-by-line accepts for an `InlineCompletionItemProvider`. I re-serve the same completion from cache after word-by-word accepts (with already accepted text filtered out). The completion suggestion flashes even though the ghost text did not change. This did not use to happen on VSCode 1.86 (downgraded and tested with the same VSIX).

Example of text flashing on VSCode 1.87
gif:
![ScreenRecording](https://github.com/microsoft/vscode/assets/24802378/ec3cc71f-3a36-4e58-8eb7-508c4ca5a70d)

mov:
https://github.com/microsoft/vscode/assets/24802378/4fd26d4b-e4be-4259-bbc8-22ee98e8555a

**Comment by dandua98** [comment]
> Would be awesome if it reproduces [here](https://microsoft.github.io/monaco-editor/playground.html?source=v0.48.0-dev-20240320#XQAAAAIqHAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxyx-6HVciAKctgAboa7AaZZDHLgrLqPRv_fRv2RyIokydlTdTYccsu6v6jDrc8jQ8utukPwKUQ2RhhDEWkiejwvhCv6mI9f-mMWJ901Y9mnfbO1g9WbURsQKLj7If1bEqyfxshEfYmMsEBsZWDcvtviGwczYH-bGaY1q1RTksWprUaeb-7D9qk8sSZzNt4rv4OI9tPsXri4WDjMgCqcbDuFokXJzKy2gqmGmSPqpHgQIM0u8P3kyl2iDyOLRX7pffC0wtHHJbtk5Wp_jyMrpJQhlh4zrZoEKisNLyVy6r7velG7BULVOfeVyuQwec9LaEKXOW7WsrPRvPUXd6Mc-6NCjumphLE7e7qlpuD4U8a3tyNqUafePM05t3TUd5jHLGWAyJNlKsFrchjXEoUumGQ_461dRDaztbiGlpCzR3VJTXFCmH8oScjafsl5jj5eIzfi2-915tKakSFDv27UiLkjCItKT-Behj3gK9SSTNPzqj3unV95iGA4PZXZOJNQGsRDRZ1b5Nln9zL4YZ6TUSLpBxoj-eFljivVriY81Vm9c9VCNrpzx0_t9np7-g4X1rdNmxxz3sEGZhRg6DE31OlRMuU4nNu-arXPjKs0K56snZteJ29YKdWq3FI3ETCVzZ_TwZoTOhOEhkr7mI1LNtezFmBIDTjgucW_w_uPk3czeE-k65Ul-k-3GcSMG9Y03EPMKdoaPPAet1ikRlMobg0nPnFn5XqlzZcnKiqimCQs86lrbOOeQNMBnfVD41RVH6p_mZs-8THqT7j6gPzIfTAJ7jZ3SC7bTRxBAuHNkXJK6lb8AO0gcJcjyilwM7_tYTWwVg-D0YbPG4HvzaC9-egJJ3CbHm50VUKSTJCoQptXhBbrnVEa6Q7F8MOnVrWyKusAP-eX8NNss24XQQhdz2GB5j6ELJ66eekSIHt7cCN2-FUEmx1tf-VR8t3cmW5FgBznDeQAAojFzZ4jgSPW_bvVwIbg0Mk1SyEh7MEeOuegjfBj6FEUI9yKfuNMR7jF5PA87fx7-xB6ydHB-OWm14uH_9sXFn6P0n5dGDZEVoGBMZWb-sF9Jn9hdhrASGcmTcHSz9fzv9vgAaAF9u5Ubn4XJSp_bgfDGUTOSATxIDgRj9DHkvF8tIRugFPJPGxhd7vZj0lcm0ZemuP751sgqmj8FLicEcFHn43q-MMFP1urjATCDS_VMwLR_L4YvAx-GEVWxLqxRmb6bR00fdVr9D88t0Xb20bejJe7SBvM_vMEzqqInPlIC5JWJshR3OtmnNrE9boka4xJpnUy0YyD1yEi63j1TeYzSjL2WInktcJj7_M5L6jCyYg0fIH6_hmVZRaPH9PkMowCOEoFW-ftqpMXNpW7MFVRiZ4PLXAEDAFvgSfpJKu16sO-p2iVaDPCHM5R3Sq-Lu_kdXooT8qcAagpMyNL5ZdLF-q-8fRgWadzoklGONplwoU3J0ngeG5JQNTX3G4IWblQHnR3xAmw_ZZp9qg640zarmwbdbBfP9erXzv31t3Mo6TS6CpjCC2NNGpBEoYYuU-SXPPrpoaQ27etcZOl4lONdpp8y2j7OXF24RCjsk8B5LRjERL2t4dZ5wK0RDZvuTG9FL4G6loWAXX6yc3bCUaMYnh-Kb6DMKFgbOwo52NWadVksCNtG4pjIZBEBIhU41JPXcwf9Z55FdT6IUOgcUK_K1EXEzDKL5Zn9hu_lOeE7HtD5geYKcYn3e0eNZMC6r0bwHsP4T57DruS0kwbr2jy2EqVsg_GGfB1AHmIdrsSFTJz4wanEynUBmaVD4U4pihuQfvVpfCMkT2OKlH41ejHCzPyItLZGoYBVOA2pYBfUjdDd2bTbhGsJmYvCw8M4OPJ60ifu3emYNWQZTlDcEUTXB2q-1_kD86m-424P77lzmtdswcorbKu4SEKaunXRXdwSXieCiguZTacHbgZ8CqeWRI9b0vJYx9CQX7Al8lXAoLd3Hwr_2kb2HHIRW6qFDHnyGnX7CojYBtnQRM1-pxMz5vzPlz96AQcxdFS_2FKIVfzftLjmR3eraFQQtynlWFhgOEyL7mc-ptHvBLe748Rw__zX1Ca3Po5o2kYUli-dwpZBRocw-It0hp-joU62EKgQri1Q6ZyL5E_NHDuanyhr-_hZNB4XlLHRZdegtyFWwmcmBgbgh1kL5ZPx9IleapAVnE0fIMoaK2thH7mz51VcsSKbvmVbMu9QBcWDkbfGmWeAB_dqqC02YJLzzBCmTxcSu4T9MH7qlwsYKhumektALWnlInzMc_R427vBnYSvXhBpX0w2KkdzqCdAc7-WvOkQ2Ci8V1eEPkgdLnvci0qGqxE6dXJ1N-zuq5FlBmQTjpdy0nVKDkE1141me54IRy-t1_I4KR7rW1AUStUKvnIzKwWJ1wMppJ3lqh_vjwvVN5Fhsb3WHLRHhvLSafTLkgwpW2DQH_XSu2nBKkvHREbiyKiJAaeG86XPZMn-ek1k3MPsuaJkdYimQcctD6kRaPI6LBKkxK_4bHpU4mzPvXfva8rntn_MEhOheUi4WgtA8Db_QZAagvWozQIpJ9Y8NBlGPWJjFeEdJlBsvTu-_Thek_oXprxFSFP1Z6XYJcdPR1W90Fm-GKT2zDANNRGVRMMDJGwaXQg-GWuDuxdBzFbEXBHokVC_JUvYwSmEDLB7mSjFSJIvATVgZAwuWCY0LjPtqh3tqXqBKFEfQNzqfhf0fUrlOVdC1O8xqVAB-w_J_7LGwQGKWt2wFMvVtCbi0_3iphAA).

Yeah let me try to figure this out and see if I can reproduce it with this!

Unfortunately I wasn't able to reproduce it for CoPilot too, but with my organization's extension the behaviour changed after 1.87.

The expected implementation for word-by-word/line-by-line completion is to re-serve the text from the old completion (with matching prefix removed) as a new `vscode.InlineCompletionItem` right?

Thanks for your help!

**Comment by hediet** [comment]
> The expected implementation for word-by-word/line-by-line completion is to re-serve the text from the old completion (with matching prefix removed) as a new vscode.InlineCompletionItem right?

Yes

**Comment by dandua98** [comment]
@hediet I create a mock example where I can still reproduce this on 1.87, and confirm that the text does not flash on 1.86. Still trying to investigate further if there's any link with other extensions or anything that could conflict, but a bit perplexed since it's very much reproducible with 1.87

```typescript
async provideInlineCompletionItems(
  document: vscode.TextDocument,
  position: vscode.Position,
  context: vscode.InlineCompletionContext,
  token: vscode.CancellationToken,
): Promise<vscode.InlineCompletionList | null | undefined> {
  const trimmedLineTextBefore = document
    .lineAt(position)
    .text.slice(0, position.character)
    .trimStart();
  const phrase = "// Hello world! How can I help you today?";
  if (phrase.startsWith(trimmedLineTextBefore)) {
    return new vscode.InlineCompletionList([
      new vscode.InlineCompletionItem(
        phrase.substring(trimmedLineTextBefore.length),
        new vscode.Range(position, position),
        undefined,
      ),
    ]);
  }
}
```

**Comment by dandua98** [comment]
On another interesting note, if I replace the full line (i.e including the prefix in the suggestion), it does not flash. Maybe it's not reproducible with CoPilot if that's the approach they're taking? 

```typescript
async provideInlineCompletionItems(
  document: vscode.TextDocument,
  position: vscode.Position,
  context: vscode.InlineCompletionContext,
  token: vscode.CancellationToken,
): Promise<vscode.InlineCompletionList | null | undefined> {
  const trimmedLineTextBefore = document
    .lineAt(position)
    .text.slice(0, position.character)
    .trimStart();
  const phrase = "// Hello world! How can I help you today?";
  if (phrase.startsWith(trimmedLineTextBefore)) {
    const matching = trimmedLineTextBefore.length;
    return new vscode.InlineCompletionList([
      new vscode.InlineCompletionItem(
        phrase,
        new vscode.Range(position.translate(0, -matching), position),
        undefined,
      ),
    ]);
  }
}
```

**Comment by hediet** [comment]
> @hediet I create a mock example where I can still reproduce this on 1.87, and confirm that the text does not flash on 1.86. Still trying to investigate further if there's any link with other extensions or anything that could conflict, but a bit perplexed since it's very much reproducible with 1.87
> 
> ```ts
> async provideInlineCompletionItems(
>   document: vscode.TextDocument,
>   position: vscode.Position,
>   context: vscode.InlineCompletionContext,
>   token: vscode.CancellationToken,
> ): Promise<vscode.InlineCompletionList | null | undefined> {
>   const trimmedLineTextBefore = document
>     .lineAt(position)
>     .text.slice(0, position.character)
>     .trimStart();
>   const phrase = "// Hello world! How can I help you today?";
>   if (phrase.startsWith(trimmedLineTextBefore)) {
>     return new vscode.InlineCompletionList([
>       new vscode.InlineCompletionItem(
>         phrase.substring(trimmedLineTextBefore.length),
>         new vscode.Range(position, position),
>         undefined,
>       ),
>     ]);
>   }
> }
> ```

Can you translate this example into a [monaco editor example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.48.0-dev-20240320#XQAAAAIqHAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxyx-6HVciAKctgAboa7AaZZDHLgrLqPRv_fRv2RyIokydlTdTYccsu6v6jDrc8jQ8utukPwKUQ2RhhDEWkiejwvhCv6mI9f-mMWJ901Y9mnfbO1g9WbURsQKLj7If1bEqyfxshEfYmMsEBsZWDcvtviGwczYH-bGaY1q1RTksWprUaeb-7D9qk8sSZzNt4rv4OI9tPsXri4WDjMgCqcbDuFokXJzKy2gqmGmSPqpHgQIM0u8P3kyl2iDyOLRX7pffC0wtHHJbtk5Wp_jyMrpJQhlh4zrZoEKisNLyVy6r7velG7BULVOfeVyuQwec9LaEKXOW7WsrPRvPUXd6Mc-6NCjumphLE7e7qlpuD4U8a3tyNqUafePM05t3TUd5jHLGWAyJNlKsFrchjXEoUumGQ_461dRDaztbiGlpCzR3VJTXFCmH8oScjafsl5jj5eIzfi2-915tKakSFDv27UiLkjCItKT-Behj3gK9SSTNPzqj3unV95iGA4PZXZOJNQGsRDRZ1b5Nln9zL4YZ6TUSLpBxoj-eFljivVriY81Vm9c9VCNrpzx0_t9np7-g4X1rdNmxxz3sEGZhRg6DE31OlRMuU4nNu-arXPjKs0K56snZteJ29YKdWq3FI3ETCVzZ_TwZoTOhOEhkr7mI1LNtezFmBIDTjgucW_w_uPk3czeE-k65Ul-k-3GcSMG9Y03EPMKdoaPPAet1ikRlMobg0nPnFn5XqlzZcnKiqimCQs86lrbOOeQNMBnfVD41RVH6p_mZs-8THqT7j6gPzIfTAJ7jZ3SC7bTRxBAuHNkXJK6lb8AO0gcJcjyilwM7_tYTWwVg-D0YbPG4HvzaC9-egJJ3CbHm50VUKSTJCoQptXhBbrnVEa6Q7F8MOnVrWyKusAP-eX8NNss24XQQhdz2GB5j6ELJ66eekSIHt7cCN2-FUEmx1tf-VR8t3cmW5FgBznDeQAAojFzZ4jgSPW_bvVwIbg0Mk1SyEh7MEeOuegjfBj6FEUI9yKfuNMR7jF5PA87fx7-xB6ydHB-OWm14uH_9sXFn6P0n5dGDZEVoGBMZWb-sF9Jn9hdhrASGcmTcHSz9fzv9vgAaAF9u5Ubn4XJSp_bgfDGUTOSATxIDgRj9DHkvF8tIRugFPJPGxhd7vZj0lcm0ZemuP751sgqmj8FLicEcFHn43q-MMFP1urjATCDS_VMwLR_L4YvAx-GEVWxLqxRmb6bR00fdVr9D88t0Xb20bejJe7SBvM_vMEzqqInPlIC5JWJshR3OtmnNrE9boka4xJpnUy0YyD1yEi63j1TeYzSjL2WInktcJj7_M5L6jCyYg0fIH6_hmVZRaPH9PkMowCOEoFW-ftqpMXNpW7MFVRiZ4PLXAEDAFvgSfpJKu16sO-p2iVaDPCHM5R3Sq-Lu_kdXooT8qcAagpMyNL5ZdLF-q-8fRgWadzoklGONplwoU3J0ngeG5JQNTX3G4IWblQHnR3xAmw_ZZp9qg640zarmwbdbBfP9erXzv31t3Mo6TS6CpjCC2NNGpBEoYYuU-SXPPrpoaQ27etcZOl4lONdpp8y2j7OXF24RCjsk8B5LRjERL2t4dZ5wK0RDZvuTG9FL4G6loWAXX6yc3bCUaMYnh-Kb6DMKFgbOwo52NWadVksCNtG4pjIZBEBIhU41JPXcwf9Z55FdT6IUOgcUK_K1EXEzDKL5Zn9hu_lOeE7HtD5geYKcYn3e0eNZMC6r0bwHsP4T57DruS0kwbr2jy2EqVsg_GGfB1AHmIdrsSFTJz4wanEynUBmaVD4U4pihuQfvVpfCMkT2OKlH41ejHCzPyItLZGoYBVOA2pYBfUjdDd2bTbhGsJmYvCw8M4OPJ60ifu3emYNWQZTlDcEUTXB2q-1_kD86m-424P77lzmtdswcorbKu4SEKaunXRXdwSXieCiguZTacHbgZ8CqeWRI9b0vJYx9CQX7Al8lXAoLd3Hwr_2kb2HHIRW6qFDHnyGnX7CojYBtnQRM1-pxMz5vzPlz96AQcxdFS_2FKIVfzftLjmR3eraFQQtynlWFhgOEyL7mc-ptHvBLe748Rw__zX1Ca3Po5o2kYUli-dwpZBRocw-It0hp-joU62EKgQri1Q6ZyL5E_NHDuanyhr-_hZNB4XlLHRZdegtyFWwmcmBgbgh1kL5ZPx9IleapAVnE0fIMoaK2thH7mz51VcsSKbvmVbMu9QBcWDkbfGmWeAB_dqqC02YJLzzBCmTxcSu4T9MH7qlwsYKhumektALWnlInzMc_R427vBnYSvXhBpX0w2KkdzqCdAc7-WvOkQ2Ci8V1eEPkgdLnvci0qGqxE6dXJ1N-zuq5FlBmQTjpdy0nVKDkE1141me54IRy-t1_I4KR7rW1AUStUKvnIzKwWJ1wMppJ3lqh_vjwvVN5Fhsb3WHLRHhvLSafTLkgwpW2DQH_XSu2nBKkvHREbiyKiJAaeG86XPZMn-ek1k3MPsuaJkdYimQcctD6kRaPI6LBKkxK_4bHpU4mzPvXfva8rntn_MEhOheUi4WgtA8Db_QZAagvWozQIpJ9Y8NBlGPWJjFeEdJlBsvTu-_Thek_oXprxFSFP1Z6XYJcdPR1W90Fm-GKT2zDANNRGVRMMDJGwaXQg-GWuDuxdBzFbEXBHokVC_JUvYwSmEDLB7mSjFSJIvATVgZAwuWCY0LjPtqh3tqXqBKFEfQNzqfhf0fUrlOVdC1O8xqVAB-w_J_7LGwQGKWt2wFMvVtCbi0_3iphAA)?
That way, if it is really a bug, it will significantly reduce the time I need to fix this (and for other team members to verify a bug-fix).

**Comment by dandua98** [comment]
@hediet here's a repro on [0.48.0-dev-20240320](https://microsoft.github.io/monaco-editor/playground.html?source=v0.48.0-dev-20240320#XQAAAAK1BQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw9bbfvJuetoAwO1Vu6dpWDMWSrZltvzuPi5DhEUaPEwx0ARYIaev6KhpVl3cGzVJY-BIRYXNHPWLjq89SBK4jq_GyBxTGKvI87eU7VRKVYV2A3G66K888aG5QNIPWzka1udk498YfWOt8E51GZe5eo8IwbVUuUH_z8lxIt-GToi3uW1LTtvQT3cH3YjaeNJSi23Di1yIPUQlUCGghZctSYPnsTF4hPZsAqe9f7H-oqSzExECFoY2P9utWnm5sIrxPyBrv1mRWZezr0ScWG1_ZPyl3Gbr34Mz7BGlhufDq9bYzZXJOO-7OCx5N4xR1d_kQHUQ3McZPMYiAcG1kvYmTwkF8Awn7SL3BLIfe0rqYH-AxjN3cVYmQzB3FDIiwNKkbn65BMpR3lX1-xXxcjDcOZDK0xPpDs5U3yGkyulrY0CfchuezfTig7ciK1-eWEJ5aOtVk42lzuUnmGQFKi7RZa_MAbPgDi94NltQd1PGIWDrRkXT4PvU3_a7gt7I8mgR3AzCCusrmNJHGvnIw6zNfrXg8Th9f42EVPR0YvZ0XBl5qWupCAfeZK9AYHdsDtwdsaw2G1O5xxHL5cPecg6Rz2gXIgVMTF1wXDvYtjKsGlMk9UBZ-TgsVXoKw-yKVkrb769rSZNcCMkmtarB6BB2HpI_QTNHZ-nPiXYvSjaYXV1GHZI2ttaAH8_kbX36kb3u2zRP-uzm2rl2NIrsFfMXVqs5trGV9OIZ5ffwUaNMSi_iLxFWlPd9Y1J4t_kzL9x5fkOihdUBVIcujWCw3wF2pfvwvtUI) reproduces it. If you type `// Hello` and then select code word-by-word, the text flashes.

On [0.46.0](https://microsoft.github.io/monaco-editor/playground.html?source=v0.46.0#XQAAAAK1BQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw9bbfvJuetoAwO1Vu6dpWDMWSrZltvzuPi5DhEUaPEwx0ARYIaev6KhpVl3cGzVJY-BIRYXNHPWLjq89SBK4jq_GyBxTGKvI87eU7VRKVYV2A3G66K888aG5QNIPWzka1udk498YfWOt8E51GZe5eo8IwbVUuUH_z8lxIt-GToi3uW1LTtvQT3cH3YjaeNJSi23Di1yIPUQlUCGghZctSYPnsTF4hPZsAqe9f7H-oqSzExECFoY2P9utWnm5sIrxPyBrv1mRWZezr0ScWG1_ZPyl3Gbr34Mz7BGlhufDq9bYzZXJOO-7OCx5N4xR1d_kQHUQ3McZPMYiAcG1kvYmTwkF8Awn7SL3BLIfe0rqYH-AxjN3cVYmQzB3FDIiwNKkbn65BMpR3lX1-xXxcjDcOZDK0xPpDs5U3yGkyulrY0CfchuezfTig7ciK1-eWEJ5aOtVk42lzuUnmGQFKi7RZa_MAbPgDi94NltQd1PGIWDrRkXT4PvU3_a7gt7I8mgR3AzCCusrmNJHGvnIw6zNfrXg8Th9f42EVPR0YvZ0XBl5qWupCAfeZK9AYHdsDtwdsaw2G1O5xxHL5cPecg6Rz2gXIgVMTF1wXDvYtjKsGlMk9UBZ-TgsVXoKw-yKVkrb769rSZNcCMkmtarB6BB2HpI_QTNHZ-nPiXYvSjaYXV1GHZI2ttaAH8_kbX36kb3u2zRP-uzm2rl2NIrsFfMXVqs5trGV9OIZ5ffwUaNMSi_iLxFWlPd9Y1J4t_kzL9x5fkOihdUBVIcujWCw3wF2pfvwvtUI) this doesn't occur. 

I can repro the bug on 0.47.0 too. Hope this helps!
