### ISSUE TITLE
Notebooks are really slow.

### ISSUE THREAD

**Issue by hylkedonker** [microsoft/vscode#208192]
Type: <b>Performance Issue</b>

Not only is the execution of cells very slow. Even typing text and scrolling through the notebook shows delays in response.
When I scroll through the notebook, `htop` shows that the process `code --type=renderer ...` easily takes upto 80% of the CPU load.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:14:59.643Z)
OS version: Linux x64 6.5.0-26-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 1799)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 2|
|Memory (System)|7.41GB (1.85GB free)|
|Process Argv|--unity-launch --crash-reporter-id a044d4c7-f89c-4e7c-8187-2f3fa3d60049|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   121	  3627	code main
    0	     0	  3633	   zygote
    0	    46	  3720	     gpu-process
    0	     0	  3634	   zygote
    0	     0	  3636	     zygote
    0	   349	  3793	window [1] (3a_omninet _exposure.ipynb - lifelines-cardio-renal-metabolic - Visual Studio Code)
    0	    91	 11683	       window
    1	    83	 13687	window [2] (Issue Reporter)
    0	    15	  3736	   utility-network-service
    0	    38	  3863	shared-process
    0	     0	 13699	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    23	  4259	ptyHost
    0	     0	 11764	     /usr/bin/zsh
    0	   129	 11647	extensionHost [1]
    0	    23	 11747	     /bin/python3 /home/hylke/.vscode/extensions/ms-python.black-formatter-2024.0.1/bundled/tool/lsp_server.py --stdio
    0	    23	 11748	     /bin/python3 /home/hylke/.vscode/extensions/ms-python.flake8-2023.10.0/bundled/tool/lsp_server.py
    0	   250	 11762	     electron-nodejs (bundle.js )
    0	  1374	 12155	     electron-nodejs (fWDX.js )
    0	   304	 13644	     electron-nodejs (D.js )
    0	    30	 11696	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (3a_omninet _exposure.ipynb - lifelines-cardio-renal-metabolic - Visual Studio Code)
|    Folder (lifelines-cardio-renal-metabolic): 280 files
|      File types: log(52) json(30) yaml(16) txt(16) wandb(16) png(11) py(10)
|                  csv(9) pyc(9) ipynb(8)
|      Conf files:;
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.175.0
copilot-chat|Git|0.13.1
black-formatter|ms-|2024.0.1
debugpy|ms-|2024.2.0
flake8|ms-|2023.10.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
rewrap|stk|1.16.3
gitblame|wad|10.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30992800
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30991134
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
gee8j676:30988843

```

</details>

**Comment by rebornix** [comment]
I wonder if this happens to all your notebooks or some of them in particular? It would be great if more details can be provided. Thanks!
