### ISSUE TITLE
Test Local Workspace Extensions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#208184]
Ref: https://github.com/microsoft/vscode/issues/206783

- [x] macOS @jrieken 
- [x] linux @connor4312 
- [x] windows @hediet 

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208184%0A%0A&assignees=sandy081)

---

You can now have an extension inside a workspace under `.vscode/extensions` folder and install and enable that extension when you open that workspace.

### Set up

- Enable `extensions.experimental.supportWorkspaceExtensions` flag and reload window

### Testing

- Open a folder and have an extension under  `.vscode/extensions` folder in the workspace
- Make sure you see that extension in the workspace recommendations view in extensions viewlet (use `@recommended` filter)
- Make sure you can install that extension and is enabled only in that workspace. 
- Make sure you need to trust the workspace to install that extension
- Test uninstalling that extension works as expected.
- You can make changes to the extension and they will be picked up on window reload / restarting extensions
- Test that installing the workspace extension which is not built will not be activated until the extension is built. Extension gets activated automatically when extension is built.
- Test workspace extensions in a Multi-root workspace. Extensions under `.vscode/extensions` folder of each root should work as above.
- Feel free to do any exploratory testing

**Comment by gjsjohnmurray** [comment]
Does this feature require the workspace to have been Trusted?

**Comment by sandy081** [comment]
Good point. Yes. workspace needs to be trusted. I will add that in the testing description.

**Comment by jrieken** [comment]
This works great!

**Comment by NoReasonKen** [comment]
Is there a workaround to fix this issue by myself ? I cannot access server with remote-ssh now
