### ISSUE TITLE
Terminal: V can be wrongly rescaled

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#208102]
Found by @amunger 

![image](https://github.com/microsoft/vscode/assets/2193314/d5018860-1e98-42e7-8298-930da71d5af6)

![image](https://github.com/microsoft/vscode/assets/2193314/f4e91b92-ed29-41ad-b978-716d1f6630f3)

dpr = 1

```json
"editor.fontFamily": "Consolas, 'Courier New', monospace",
"terminal.integrated.fontSize": 14,
```

**Comment by Tyriar** [comment]
Upstream fix: https://github.com/xtermjs/xterm.js/pull/5012

**Comment by amunger** [comment]
the auto-complete font has issues with more characters as well.
![image](https://github.com/microsoft/vscode/assets/2019016/80760c82-327e-420e-814f-2eeb1424ea01)

**Comment by amunger** [comment]
normal text looks better but that completion font still has issues. I think that just comes from pwsh 7

**Comment by Tyriar** [comment]
I didn't end up pulling in the updated dep. Today I'll change it to never rescale ascii and then update so this problem will definitely go away even for italics.
