### ISSUE TITLE
API feature request - Add a Profile change event

### ISSUE THREAD

**Issue by robole** [microsoft/vscode#208195]
It would be useful to have an activation event or `onProfileChange` event to signify that the [Profile](https://code.visualstudio.com/docs/editor/profiles) has changed. 

![screenshot-statusbar](https://github.com/microsoft/vscode/assets/3703647/8aad76e2-0a26-4a30-90f9-d20dc66472f5)

My particular use case is that I want to display the profile name on the status bar.  I wrote an the extension for this: https://marketplace.visualstudio.com/items?itemName=robole.profile-status

The limitation is that the status bar item is only updated if the VS Code instance is reloaded. There are some scenarios when you switch to a new profile and when the VS Code instance does not reload such as: creating an empty profile (keep default settings when running the command `Profiles: Create Profile`), or if you have the same workspace open in 2 instances and switch profile in one.

If there is some way to detect a profile change in the API that I missed, please me let me know!

Thanks

**Comment by sandy081** [comment]
We do not support any profile related APIs so any extension feature trying to access profile could be a hack. Hence, I am closing this as wont fix.

**Comment by robole** [comment]
If you support nothing, everything is a hack! Thats a circuitous statement! Is there a rationale behind not supporting anything related to profiles?

**Comment by sandy081** [comment]
One can find the profile name in the title bar.

![Image](https://github.com/microsoft/vscode/assets/10746682/315cc03d-8015-462f-ba3e-75728afccdb6)

> If you support nothing, everything is a hack! Is there a rationale behind not supporting anything related to profiles?

1. A valid and prominent use case 
2. Aligns with our road map.
