### ISSUE TITLE
Add feature to open folder in new window via right-click in Vocode File Explorer 右键新窗口打开文件/文件夹

### ISSUE THREAD

**Issue by Lonely-lie** [microsoft/vscode#208179]
Issue Title:
Add feature to open folder in new window via right-click in Vocode File Explorer

Issue Description:
Currently, when using Vocode, it would be very useful to have the option to open a folder in a new window directly from the file explorer located on the left side. This feature would enhance user experience and productivity by providing a quicker way to navigate through files and folders without losing the current context in the main window.

Proposed Solution:
Add a right-click context menu option in the Vocode file explorer that allows users to open a folder in a new window when selected.

中文：
Issue 标题：
在 Vocode 文件资源管理器中添加右键打开文件夹至新窗口的功能

Issue 描述：
目前，在使用 Vocode 时，通过左侧的文件资源管理器直接右键打开文件夹至新窗口将会非常有用。这个功能将会提升用户体验和工作效率，让用户更快地浏览文件和文件夹，同时不会丢失主窗口中的当前内容。

建议解决方案：
在 Vocode 文件资源管理器中添加右键菜单选项，允许用户在所选文件夹中打开一个新窗口。

您可以将以上内容复制到GitHub中创建一个新的Issue，提出这个功能请求。希望对您有帮助！如果您有其他问题，也请随时告诉我。

**Comment by gjsjohnmurray** [comment]
Extensions are available for this, including https://marketplace.visualstudio.com/items?itemName=chrisdias.vscode-opennewinstance
