### ISSUE TITLE
Erro ao Debugar

### ISSUE THREAD

**Issue by Lavirle** [microsoft/vscode#208157]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 
No Java executable found, please consider to configure your 'java.jdt.ls.java.home' setting or set JAVA_HOME in your path or put a Java executable in your path.
Launching lib\main.dart on Edge in debug mode...
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:20:1: Error: Expected ';' after this.
xport 'package:flutter/foundation.dart'
^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:20:7: Error: Expected a declaration, but got ''package:flutter/foundation.dart''.
xport 'package:flutter/foundation.dart'
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:29:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
export 'package:flutter/foundation.dart'
^^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:37:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
export 'package:flutter/foundation.dart'
^^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:39:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
export 'package:flutter/foundation.dart' show DiagnosticLevel, DiagnosticsNode;
^^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:40:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
export 'package:flutter/foundation.dart' show Key, LocalKey, ValueKey;
^^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:41:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
export 'package:flutter/rendering.dart'
^^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:1518:10: Error: A named parameter can't start with an underscore ('_').
    this._widget,
         ^^^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:1519:19: Error: A named parameter can't start with an underscore ('_').
    required this._debugLifecycleState,
                  ^^^^^^^^^^^^^^^^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:928:16: Error: 'State' is already declared in this scope.
abstract class State<T extends StatefulWidget> with Diagnosticable {
               ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:916:16: Context: Previous declaration of 'State'.
abstract class State<T extends StatefulWidget> with Diagnosticable {}
               ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:21:5: Error: Type 'show' not found.
    show
    ^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:160:36: Error: 'State' isn't a type.
abstract class GlobalKey<T extends State<StatefulWidget>> extends Key {
                                   ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:160:36: Context: This isn't a type.
abstract class GlobalKey<T extends State<StatefulWidget>> extends Key {
                                   ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:212:34: Error: 'State' isn't a type.
class LabeledGlobalKey<T extends State<StatefulWidget>> extends GlobalKey<T> {
                                 ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:212:34: Context: This isn't a type.
class LabeledGlobalKey<T extends State<StatefulWidget>> extends GlobalKey<T> {
                                 ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:254:33: Error: 'State' isn't a type.
class GlobalObjectKey<T extends State<StatefulWidget>> extends GlobalKey<T> {
                                ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:254:33: Context: This isn't a type.
class GlobalObjectKey<T extends State<StatefulWidget>> extends GlobalKey<T> {
                                ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:810:3: Error: 'State' isn't a type.
  State createState();
  ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:810:3: Context: This isn't a type.
  State createState();
  ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:916:16: Error: 'Object with Diagnosticable' isn't a type.
abstract class State<T extends StatefulWidget> with Diagnosticable {}
               ^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:916:16: Context: This isn't a type.
abstract class State<T extends StatefulWidget> with Diagnosticable {}
               ^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:928:16: Error: 'Object with Diagnosticable' isn't a type.
abstract class State<T extends StatefulWidget> with Diagnosticable {
               ^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:928:16: Context: This isn't a type.
abstract class State<T extends StatefulWidget> with Diagnosticable {
               ^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:2531:40: Error: 'State' isn't a type.
  T? findAncestorStateOfType<T extends State>();
                                       ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:2531:40: Context: This isn't a type.
  T? findAncestorStateOfType<T extends State>();
                                       ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:2544:44: Error: 'State' isn't a type.
  T? findRootAncestorStateOfType<T extends State>();
                                           ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:2544:44: Context: This isn't a type.
  T? findRootAncestorStateOfType<T extends State>();
                                           ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:4986:40: Error: 'State' isn't a type.
  T? findAncestorStateOfType<T extends State<StatefulWidget>>() {
                                       ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:4986:40: Context: This isn't a type.
  T? findAncestorStateOfType<T extends State<StatefulWidget>>() {
                                       ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:5000:44: Error: 'State' isn't a type.
  T? findRootAncestorStateOfType<T extends State<StatefulWidget>>() {
                                           ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:5000:44: Context: This isn't a type.
  T? findRootAncestorStateOfType<T extends State<StatefulWidget>>() {
                                           ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:5781:3: Error: 'State' isn't a type.
  State<StatefulWidget> get state => _state!;
  ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:5781:3: Context: This isn't a type.
  State<StatefulWidget> get state => _state!;
  ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:5782:3: Error: 'State' isn't a type.
  State<StatefulWidget>? _state;
  ^^^^^
/c:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:5782:3: Context: This isn't a type.
  State<StatefulWidget>? _state;
  ^^^^^
Unhandled exception:
Crash when compiling:
Null check operator used on a null value

#0      SourceClassBuilder.buildAliasedTypeArguments.<anonymous closure> (package:front_end/src/fasta/source/source_class_builder.dart:436)
#1      new _GrowableList.generate (dart:core-patch/growable_array.dart:136)
#2      SourceClassBuilder.buildAliasedTypeArguments (package:front_end/src/fasta/source/source_class_builder.dart:433)
#3      ClassBuilderImpl.buildAliasedType (package:front_end/src/fasta/builder/class_builder.dart:348)
#4      NamedTypeBuilderImpl._buildAliasedInternal (package:front_end/src/fasta/builder/named_type_builder.dart:490)
#5      NamedTypeBuilderImpl._buildInternal (package:front_end/src/fasta/builder/named_type_builder.dart:437)
#6      _ExplicitNamedTypeBuilder.build (package:front_end/src/fasta/builder/named_type_builder.dart:767)
#7      NominalVariableBuilder.finish (package:front_end/src/fasta/builder/type_variable_builder.dart:382)
#8      SourceLoader.finishTypeVariables (package:front_end/src/fasta/source/source_loader.dart:1877)
#9      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:438)
<asynchronous suspension>
#10     withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#11     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:385)
<asynchronous suspension>
#12     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:366)
<asynchronous suspension>
#13     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#14     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:77)
<asynchronous suspension>
#15     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:610)
<asynchronous suspension>
#16     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1303)
<asynchronous suspension>
Failed to compile application.

Exited (1).

**Comment by Lavirle** [comment]
Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 6.0.6002

**Comment by roblourens** [comment]
Sounds like maybe this is an issue for the Dart extension
