### ISSUE TITLE
Test: support for `iframe` based editors in floating windows

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#208198]
Ref: https://github.com/microsoft/vscode/issues/195715

- [x] macOS @deepak1556 
- [x] linux @andreamah
- [x] windows @karthiknadig
- [x] web @anthonykim1

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208198%0A%0A&assignees=bpasero)

---

Editors that leverage `iframe` can now be opened in floating (auxiliary) windows. Please make sure you have a good set of custom editors installed via extensions to test this, for example:
* [Luna Paint](https://marketplace.visualstudio.com/items?itemName=Tyriar.luna-paint)
* [Hex Editor](https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor)
* [Draw IO](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio)

**Note:** due to a technical limitation, `iframe` will reload its contents when moved between windows. If the provider of the `iframe` content is not restoring the last state, this means the content will appear fresh as if you had opened the editor for the first time. For example, when you use `Simple Browser` to view a local web site, any action you did in the web site that resulted in change, will be gone.

**Testing (non-custom-editors that cannot be modified)**
* you can use `Simple Browser` or `Markdown Preview` or `Release Notes` for testing
* make sure content appears properly in floating windows like any other editor
* make sure you can move these editors between main and floating window without trouble

**Testing (custom editors that can be modified)**
* make sure content appears properly in floating windows like any other editor
* ensure editors restore when you restart at the position they were in
* test dirty editors
  * with a text-based custom editor such as `Draw IO`
    * make changes to the editor but do not save
    * move the editor to another window
    * make sure it opens as dirty and the state is restored (this depends on the extension actually, but `Draw IO` should support it)
  * with a non-text-based custom editor such as `Luna Paint` that does not support hot exit for larger images
    * open a larger image (e.g. `1024x1024`) and make changes
    * try to move editor to another window
    * verify you get prompted that the editor cannot be moved until you save it
    * save it and move it to a floating window
    * make it dirty again
    * try to close the window and verify you get a prompt that prevents closing for as long as the image is dirty

**Comment by gjsjohnmurray** [comment]
Pinging @isc-bsaviano as I think this may be relevant to our extension.

**Comment by deepak1556** [comment]
Tested with markdown preview, hex editor and luna paint.

**Comment by andreamah** [comment]
Exciting that we're getting support for this! I tried it with simple browser, live preview, drawio, and luna paint.

**Comment by bpasero** [comment]
State handling depends entirely on the extension, its possible that some track state constantly and can restore, I am not sure about simple browser.

**Comment by anthonykim1** [comment]
Testing web, working with markdown preview, luna paint for image dimension: 2972 × 2056. 
See issue for drawio below.
