### ISSUE TITLE
Allow to set keyboard shortcut for `search for text`

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#208100]
Type: <b>Feature Request</b>

Allow keyboard shortcut option for `search for text` command
![image](https://github.com/microsoft/vscode/assets/9264813/7b6ea032-9e6b-4f19-a08d-56633e0d41a6)

VS Code version: Code - Insiders 1.88.0-insider (7c51753f7ce936a7aeb84ac881818c35c5a9ab8d, 2024-03-19T05:48:31.453Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by andreamah** [comment]
You can set a keybinding for the command `Search: Quick Search (Experimental)` 

<img width="265" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/93b8c759-127b-4f64-935e-95449deb5eb2">

However, there are no current plans to add a default keybinding for this.
