### ISSUE TITLE
Pasted text copied from an interactive terminal should retain colors

### ISSUE THREAD

**Issue by daviwil** [microsoft/vscode#20813]
- VSCode Version: VS Code Insiders from 2/17/17
- OS Version: Windows 10

Steps to Reproduce:

1. Copy text from an integrated terminal window which has colored output
2. Paste it into Outlook
3. Observe that the text is pasted without colorization

Now that copied text from an editor pane retains syntax highlighting when pasted into a rich editor, is it possible that we could get the same behavior for copying text from the integrated terminal?  I'll understand if this isn't easy to accomplish, but I know that former users of PowerShell ISE will expect it since that editor provides this capability.

/cc @rebornix @Tyriar

**Comment by Tyriar** [comment]
Opening this up for PRs. @rebornix any tips/links to help someone implement this would be useful.

**Comment by rebornix** [comment]
It's all about setting a `text/html` entry to the clipboard along with `text/plain`. In Monaco, we bind a copy/paste handler to the textarea while in integrated terminal, we are relying on xterm.js to handle the copy and paste.

https://github.com/sourcelair/xterm.js/blob/3a6368ba6c8d5029e1b432f0e32845442d2f26d9/src/handlers/Clipboard.ts#L48 Here is where you can start to tweak.

**Comment by Tyriar** [comment]
@rebornix vscode intercepts copy/paste so the xterm.js stuff is skipped. See https://github.com/Microsoft/vscode/blob/76787cdff259873e24f38ec6e195095908037a82/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L292

**Comment by rebornix** [comment]
@Tyriar we intercepts the key shortcuts but after running `document.execCommand('copy');`, the handler xterm.js binds to the dom finally gets the clipboard event. The thing that I don't understand right now is even though the document has real selection, the clipboard data we get is somehow empty.

**Comment by Tyriar** [comment]
Supporting this now would need hooks from upstream due to canvas.

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/issues/1883

**Comment by LinoBarreca** [comment]
Any news about this? (or a workaround?) it's pretty annoying when you have to forward terminal output with colored build logs and you can't..
is there an extension that can do this?
