### ISSUE TITLE
Please add a confirmation to closing the app

### ISSUE THREAD

**Issue by sirJiggles** [microsoft/vscode#208125]
Type: <b>Feature Request</b>

It is such a basic feature and such a pain in the butt on miss click that the whole dam thing closes without confirmation. please

VS Code version: Code 1.87.2 (Universal) (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin arm64 23.1.0
Modes:

**Comment by gjsjohnmurray** [comment]
Did you try the `window.confirmBeforeClose` setting?

**Comment by alexr00** [comment]
@gjsjohnmurray suggestion should be what you're looking for.

**Comment by sirJiggles** [comment]
amazing thank you 🙏
