### ISSUE TITLE
Test Extension Update Enhancements

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#208185]
Ref: https://github.com/microsoft/vscode/issues/125417

- [x] macOS @rebornix 
- [ ] linux @joaomoreno 
- [x] windows @aeschli

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208185%0A%0A&assignees=sandy081)

---

### Set Up

- Develop a sample extension and publish to Marketplace - https://code.visualstudio.com/api/get-started/your-first-extension
- Have one version older VS Code build installed - https://builds.code.visualstudio.com/builds/insider - Set VS Code auto updates to manual mode from settings. Have auto updates enabled for extensions.

### Testing

- Have your extension installed. Push an update to your extension to Marketplace. 
- Make sure extensions are updated while checking for VS Code updates - to test this - Trigger check for updates on VS Code. 
- When the newer version of the extension is not compatible with current version of VS Code but compatible with newer version of VS Code, test that extension will be updated. After updating, appropriate action is shown on the extension. For eg., **Restart to Update** action is shown if VS Code needs restart for updating. Please test the right action is shown in each platform.

**Note**: You can publish an extension that is not compatible with current insiders version but compatible with newer insiders version by adding date to vscode version in engine. This date should be later than older insiders version but before the newer insiders version. Eg:

```json
"engines": {
		"vscode": "^1.87.0-20240219",
	}
```

## Test Restarting Extensions on Update | Uninstall | Disable

- You can now simply restart extensions when an extension is updated to a newer or another version. Also when you uninstalled the extension. This will update or remove the updated or uninstalled extension in the extension host. Test that this is working as expected.
- Test that this should still show **Reload Required** action in Remote window.

**Comment by aeschli** [comment]
I have started testing and will complete it tomorrow

**Comment by rebornix** [comment]
This is very nice!

**Comment by roblourens** [comment]
Do any of the Linux install methods support the same update flow that mac/win does, where it updates itself and restarts? I’m not sure whether this actually works on Linux.

I did try it on Mac and it worked great

**Comment by joaomoreno** [comment]
This feature doesn't need the full auto update flow to work. It works just fine on Linux, where for deb/rpm/archive we just notify the user that there's an available VS Code update. I've verified that when that happens, there's the following telemetry event fired: `telemetry/galleryService:checkingForUpdates`. Works great!

**Comment by roblourens** [comment]
But it's not going to _install_ the extension update at that time, because it wants to install the extension update at the same time it installs the vscode update, right? That never seemed to happen for me.

**Comment by sandy081** [comment]
When extensions auto update is enabled, VS Code updates the extension while checking the updates. Updating VS Code just acts as another trigger to update extensions, so they are not tightly coupled.

**Comment by roblourens** [comment]
Oh, I see, thanks
