### ISSUE TITLE
[GIT] Rename "Clean" to "Discard changes"

### ISSUE THREAD

**Issue by cvanleeuwen** [Microsoft/vscode#20810]
When I want to undo changes I've made to a file in VS code, it's possible to use the embedded git tools, right click a file with pending changes and choose "Clean". This option keeps confusing me, so I wondered if it might be an idea to give this option an easier to understand name.

![image](https://cloud.githubusercontent.com/assets/4456201/23068566/788fd354-f524-11e6-99c1-4f74b599f2a4.png)

**Comment by joaomoreno** [comment]
I love it! I was never a big fan of Clean anyway.

**Comment by joaomoreno** [comment]
0428dd5dc332d453e40f4e471cf75386b869d41e

**Comment by mgutz** [comment]
Agree, git "clean" wipes out files. Revert might be a better word than discard as revert is used by other vcs (svn, hg) to undo changes.

**Comment by jrieken** [comment]
@joaomoreno It now read `Discard File` which is bogus because it only operates on the changes/delta to the original file.

<img width="233" alt="screen shot 2017-03-30 at 12 00 28" src="https://cloud.githubusercontent.com/assets/1794099/24498972/7e43c86e-1540-11e7-808f-605661f45087.png">
