### ISSUE TITLE
Open a new pane/column without a duplicate file

### ISSUE THREAD

**Issue by ttbarnes** [Microsoft/vscode#20816]
Current behaviour: 
- opening a new pane/column opens the same file in the new pane/column. 
- With this in place, the UX is not the best. To work on a new file in a new pane/column, you have to close the duplicate file first before opening a new file.

Desired behaviour:
- ability to have an option to open an new pane/column as empty, without a duplicate file pane.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/2755
