### ISSUE TITLE
Allow for temporary maximization of editor tabs

### ISSUE THREAD

**Issue by pevogam** [microsoft/vscode#208163]
It would be great if VS Code could "temporarily maximize" editor tabs similarly to Konsole in

![image](https://github.com/microsoft/vscode/assets/1969979/ff9714c2-ca46-4da7-b0a9-c60dfe9ea16c)

The idea is that one can partition the screen space in 2, 4 or more editor areas but can always temporarily focus on a single editor without having to close or get rid of the other editor tabs, then reduce the focused editor view back to its partitioned size.

Any thoughts?

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/196722#issuecomment-1782251148 help?

**Comment by pevogam** [comment]
Indeed, a very good 

> Does [#196722 (comment)](https://github.com/microsoft/vscode/issues/196722#issuecomment-1782251148) help?

Indeed a very good pointer. I would have expected some tiny maximizing icon at the corner for this but it will likely clutter the interface too much anyway. Resolving since this seems to already be possible :+1:
