### ISSUE TITLE
Test: Notebook Timeline entries

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#208266]
Refs: https://github.com/microsoft/vscode/issues/205634

- [x] anyOS @deepak1556
- [x] anyOS @bhavyaus

Complexity: 3

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208266%0A%0A&assignees=DonJayamanne)

---
**PreRequisites**
* Install an extension that creates notebooks, such as Github Issues notebook or Jupyter ext

**Steps**
* Open a workspace folder
* Create a notebook file (Github issues or Jupyter Notebook or other)
* Save this file
* [ ] Verify an entry exists in timeline
* [ ] Verify clicking this entry in timeline shows the diff view
* [ ] Verify closing the diff view still leaves the notebook open
* Insert a cell and save this file
* [ ] Verify the entry `File Saved` shows up
    * If not using a Jupyter notebook, this might not showup.
* Delete this new cell
* Save this file
* [ ] Verify the entry `Delete Cell` shows up
* [ ] Verify clicking this entry in timeline shows the diff view
* [ ] Verify closing the diff view still leaves the notebook open
* Save the file
* Add a markdown cell and save the file
* Next move a cell
* [ ] Verify the entry `Move Cell` shows up
* [ ] Verify clicking this entry in timeline shows the diff view
* [ ] Verify closing the diff view still leaves the notebook open
* Make a few more changes to the notebook, 
* [ ] Verify clicking this entry in timeline shows the diff view
* [ ] Verify closing the diff view still leaves the notebook open

**Comment by bpasero** [comment]
Bug?
