### ISSUE TITLE
Quick chat "x" icon is outside the chat background

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#208207]
<img width="616" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/367c23b2-5de5-42b9-a781-fe99efb4204c">

**Comment by TylerLeonhardt** [comment]
Caused by @roblourens (which I approved 😅) in https://github.com/microsoft/vscode/pull/207648 where it added 20px of margin.

**Comment by roblourens** [comment]
Sorry! Thanks for cleaning up
