### ISSUE TITLE
Font scale is wrong in new window

### ISSUE THREAD

**Issue by mikl0906** [microsoft/vscode#208219]
Type: <b>Bug</b>

1) Open empty VSCode
2) Change the scale of the UI with Ctrl+"+"
3) Open new window of VSCode
4) The scale is default

If I only work with one window the scale works fine. But if I ever open a second window while having one opened, the new one has a default scale.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.62GB (12.29GB free)|
|Process Argv|--crash-reporter-id 337751e4-1a4f-4c82-8b94-a575a2012562|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.175.0
copilot-chat|Git|0.13.1
csdevkit|ms-|1.4.29
csharp|ms-|2.23.2
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.0.2
vscodeintellicode-csharp|ms-|0.1.26
remote-containers|ms-|0.348.0
vscode-nuget-gallery|pat|0.0.24
vscode-icons|vsc|12.7.0
markdown-pdf|yza|1.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30992801
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonaic:30992952

```

</details>

**Comment by bpasero** [comment]
Does it work as expected when you configure `window.zoomPerWindow` to `false`?

**Comment by mikl0906** [comment]
Yes, this setting helps. I set `window.zoomLevel` to set the default value. I got confused since on my Mac the behaviour was different. It turns out this setting was not synced. So it seems like there is no actual issue.
