### ISSUE TITLE
Test: Undo/Redo options in notebook

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#208267]
Refs: https://github.com/microsoft/vscode/issues/205634

- [x] anyOS @bpasero
- [x] anyOS @bamurtaugh

Complexity: 3

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208267%0A%0A&assignees=DonJayamanne)

---
**PreRequisites**
* Install an extension that creates notebooks, such as Github Issues notebook or Jupyter ext

**Steps**
* Open a workspace folder
* Create a notebook file (Github issues or Jupyter Notebook or other)
* Save this file
* Verify you can undo/redo operations using the Ctrl Z (and corresponding keyboard shortcuts)
    * Verify this works as expected
* Make changes to the notebook by adding, removing, moving cells,
* Verify you can undo/redo operations using the Ctrl Z (and corresponding keyboard shortcuts)
    * Verify this works as expected

**Comment by bpasero** [comment]
Maybe I did something wrong, but adding/removing cells never worked for me with undo/redo. Only text edits in cells and moves worked.
