### ISSUE TITLE
Add search to generated in-product Markdown preview (release notes, extension READMEs)

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#20825]
Would it be possible to add search/find to the in-product rendered Markdown previews? This would help navigation in the in-product release notes and long extension READMEs.

This came up during a meeting with the C++ extension team, where they worried that their README was getting too long for easy in-product navigation and would like the user to be able to search for the sections appropriate to their specific C++ configuration.

**Comment by mjbvz** [comment]
Thanks Greg. We're tracking this feature with #2187
