### ISSUE TITLE
Extension details view "Contributions" unclear

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#20827]
In the Extensions details view, the section named "Contributions" is unclear. Sitting with the C++ extension team, they thought this would be a list of the developers who had contributed to the project. Given the use of the terms "contributor", "contributing", and "contributions" (GitHub, our release notes), this may be a  common misunderstanding.

We could change the title for that section to something like "Additions".

Another option would be to rename "Details" to "Readme" and "Contributions" to "Details". We mention README throughout our documentation and this is similar to the "Changelog" title which refers to the filename CHANGELOG.md.

**Comment by joaomoreno** [comment]
@waderyan @seanmcbreen Thoughts?

**Comment by seanmcbreen** [comment]
Personally I would wait until we get a little more feedback - but I can understand some people are not 100% sure what it means.  The same is of course true for changelog.

So for now I would not act.

**Comment by joaomoreno** [comment]
Closing as no-op.
