### ISSUE TITLE
Quick open: Editor history selection lost once file results kick in

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#20828]
- VSCode Version: `1.10.0-insider` 50f8848e44029ffabf0727de49cd18ae4069b4fe
- OS Version: macOS Sierra `10.12.3 (16D32)`

Steps to Reproduce:

1. Open the command palette
2. Start typing a couple of characters of something in the recently opened section
3. Quickly use the arrow keys to move down on the list like you are going to select one of the items in the recently opened section
4. Notice as soon as the auto-complete section below the recently opened section fill out, the selected item will move back to the first item in the list -- instead of staying where it was

It took me a bit to figure out the scenario here, because I just kept noticing that when I'd start searching for something, see it on the recent list, select it and open it -- but it kept opening the wrong file. And it was because the selection was getting reset *just* before I hit enter, so I ended up opening the wrong file.

**Comment by bpasero** [comment]
This is sort of a regression from my "fix" for https://github.com/Microsoft/vscode/issues/20216

/cc @roblourens

**Comment by bpasero** [comment]
Actually no, this is due to the new scorer based sorting that happens via https://github.com/Microsoft/vscode/commit/a62cf834327d7b71cb2b4c3417c77343f5a75701

**Comment by bpasero** [comment]
@eamodio I am a bit confused, in the summary you talk about "Command palette" but in the description you talk about "recently opened section". Can you share a screenshot what you mean?

**Comment by eamodio** [comment]
@bpasero Sorry for the confusion -- here is where I am seeing it

![image](https://cloud.githubusercontent.com/assets/641685/23130700/6eb48342-f755-11e6-86dd-5993d15fe7a8.png)

**Comment by bpasero** [comment]
@eamodio so in that picture you arrow down to e.g. "package.json" and type "p" and you no longer see package.json selected?

**Comment by eamodio** [comment]
![selection-change](https://cloud.githubusercontent.com/assets/641685/23131420/e5302812-f757-11e6-900a-a3003263d37a.gif)

It happens fast in this example, but I typed `com`, arrowed down the the 2nd item, and when the `Files and symbol results` pops in the selection is reset to the top. In the example I showed here it was with a small project, so it happens much more quickly, but on a larger project it take more time for the `Files and symbols results` to show up, which makes the issue much worse.

**Comment by bpasero** [comment]
@eamodio ah, so you manage to arrow down in the "recently opened" before the results of the file search show up, is that it?

**Comment by eamodio** [comment]
@bpasero yes -- and as I mentioned on a larger project (like the one I normally work on) it takes ~3s or so for the search results show up, so it isn't that hard to get it to happen.

**Comment by bpasero** [comment]
This seems to happen due to https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L594 triggering a `autoFocus` even though the user has selected something already.
