### ISSUE TITLE
Chrome Debugger Can't Find "Variables" ID

### ISSUE THREAD

**Issue by abogartz** [Microsoft/vscode#20820]
- VSCode Version: 1.9.1
- OS Version: OSX El Capitan

Steps to Reproduce:

1. Use the Chrome debugger and stop on a breakpoint. Leave it in this state then hit the reload icon in the debugger.

After a while, this output starts being shown in a loop:

```Error processing "variables": Cannot find context with specified id```

**Comment by R9Gateway** [comment]
vscode a comment cannot be blank.

**Comment by abogartz** [comment]
@R9Gateway was that addressed to my issue? Can you explain what you meant there?

**Comment by roblourens** [comment]
This was fixed in 2.5.5, https://github.com/Microsoft/vscode-chrome-debug/issues/364
