### ISSUE TITLE
MacOS: "code ." does not load the contents of the current directory

### ISSUE THREAD

**Issue by richardthombs** [microsoft/vscode#208201]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:57.520Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.4.0
Steps to Reproduce:

This is on a brand new Mac with VSCode installed from the ZIP file.

1. Make sure VS Code is not running
2. Change directory to a folder containing files
3. Launch code from the terminal with `code .`
4. Observe that vscode does not load the folder and instead starts empty.

Note: "code -n ." does work correctly

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by richardthombs** [comment]
Obviously I was able to reproduce this enough to write the bug report, but today... it works! I didn't change anything except maybe a reboot.
