### ISSUE TITLE
source.addMissingImports doesn't work anymore

### ISSUE THREAD

**Issue by kasty** [microsoft/vscode#208293]
Type: <b>Bug</b>

- Start a javascript/typescript project
- I have this in my settings.json

```
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": "explicit",
    "source.addMissingImports": "explicit",
},
```

- I use a dependency without importing it, save my file but the import is not added anymore. This was working before but I can't tell when it started not to work anymore. Maybe since my last vscode update

VS Code version: Code 1.87.2 (Universal) (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|9, 10, 10|
|Memory (System)|32.00GB (1.36GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 4ca0acda-7f9c-4139-a75a-95b1610d0469|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30992800
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonaic:30992952

```

</details>

**Comment by justschen** [comment]
hi @kasty, I'm unable to reproduce this in the latest stable (1.87.2) or in our nightly insiders build (1.88). 

keep in mind that "explicit" means a manual save, either using `File -> Save` or using `CtrlCmd + S`. 

Can you also double check to see if the import is valid? Try running the quick fix on the error and see if it gives you options to import.

**Comment by kasty** [comment]
Hi @justschen, thanks for taking time on my issue !

Well yes, my import is valid, the import is suggested while typing, see for "fetchUrl" :
<img width="553" alt="Capture d’écran 2024-03-22 à 09 46 50" src="https://github.com/microsoft/vscode/assets/5735310/3dac64be-f577-48bc-8861-56e05d608361">

However, the import is not suggested to me on the quick fix and nothing happens when using Cmd + S :
<img width="498" alt="Capture d’écran 2024-03-22 à 09 47 07" src="https://github.com/microsoft/vscode/assets/5735310/2b848904-5c2b-445d-ba8b-bc83aeaa9bdc">


Is it normal that "source.fixMissingImports" is not suggested to me when I edit my settings ?
<img width="532" alt="Capture d’écran 2024-03-22 à 09 52 21" src="https://github.com/microsoft/vscode/assets/5735310/5aec07fa-8a10-4daa-8525-7aaa50a3b47e">

Thanks !

**Comment by justschen** [comment]
@kasty I believe this is a typescript issue, and I just created an issue with them to see if they have more info on this! https://github.com/microsoft/TypeScript/issues/57907

the last issue regarding not being suggested - we've know about this for a while and it's in our backlog!

**Comment by avertx** [comment]
@kasty might check workspace settings.json.  Mine mysteriously was overriding user settings:

"editor.codeActionsOnSave": {
			"source.organizeImports": "never"
		},

**Comment by justschen** [comment]
@kasty are you still running into this?
