### ISSUE TITLE
JSDocs toolip not showing for classes

### ISSUE THREAD

**Issue by dotnetprofessional** [Microsoft/vscode#20829]
- VSCode Version: 1.9.1
- OS Version: Win10

Steps to Reproduce:

1. Create a class with JSDocs associated with the class definition
2. Import the class to a file ie
`import MyClass from "./MyClass";`

When hovering over the class variable the only docs provided are 'import MyClass' which isn't that helpful. However the JSDocs for the class ie that which explains the purpose of the class are missing. JSDocs show up fine for any methods defined on the class. While I get its an alias, it would be very helpful to have these docs show up when hovering over the name.

**Comment by mjbvz** [comment]
Thanks. We're tracking this issue upstream on the TypeScript side with: https://github.com/Microsoft/TypeScript/issues/11099
