### ISSUE TITLE
Launch.json skipFiles not correctly ignoring node_modules

### ISSUE THREAD

**Issue by mfcarroll** [microsoft/vscode#208277]
Type: <b>Bug</b>

I've come across two issues that appear to be related. First, skipFiles doesn't work in some circumstances. With a launch.json containing this:

"skipFiles": ["<node_internals>/**", "**/node_modules/**"]

...I'm still getting errors like this:

`Could not read source map for file:///Users/matthew/Documents/code/sourcemap-test/node_modules/%40auth0/auth0-vue/node_modules/%40auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js: ENOENT: no such file or directory, open '/Users/matthew/Documents/code/sourcemap-test/node_modules/@auth0/auth0-vue/node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js.map'`

For some packages, the debugger fails to find the sourcemaps. It appears to be looking in a nested subdirectory for files that do not exists where the package was installed as a dependency, even though the corresponding files do exists in the root node_modules directory.

This appears to be related to the second issue, which is that the debugger is looking for the source maps in the wrong place. It's looking for auth0-spa-js to be a nested dependency of auth0-vue in:

`/node_modules/@auth0/auth0-vue/node_modules/@auth0/auth0-spa-js/`

...when in fact that package is installed here:

`/node_modules/@auth0/auth0-spa-js/`

For some reason the debugger isn't following the same logic to resolve the package location as node itself is using.

Steps to reproduce:

1. npm create vue@latest
2. npm i @auth0/auth0-vue
3. Add auth0 quick start code to project
4. Set up launch.json to launch node and then chrome debug session

Expected result 1: Should find sourcemap and not give error
Expected result 2: Error should be suppressed by skipFiles

Actual result: Error above

_Note, I used auth0-vue as that was just one of many packages generating this sort of error in my main project. I don't believe the issue is anything to do with auth0._

I've published a simple example here:

https://github.com/mfcarroll/vsc-sourcemap-bug

I believe this is likely the same bug (or related) to this issue which was closed for lack of info:

https://github.com/microsoft/vscode/issues/120662#issuecomment-814468478

I'll subscribe to the issue, and am happy to help pin down the problem if anything else is needed.

VS Code version: Code 1.87.2 (Universal) (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|8, 6, 5|
|Memory (System)|18.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id ff3dde74-923b-422d-b562-80cd69d07ffc|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30992801
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
8082a590:30971561
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonaic:30992952

```

</details>

**Comment by connor4312** [comment]
Thanks for the repo.

The launch configuration attributes define debugging configuration for the Node.js program. The browser is then an entirely separate debug session which does not inherit the settings used to debug the Node.js server (vite). Two ways to do what you want:

- Use the `startDebugging` `action` to reference a Chrome launch configuration which is configured with the skipFiles you want https://code.visualstudio.com/docs/editor/debugging#_triggering-an-arbitrary-launch-config
- Don't use a launch config at all for the Vite server, but instead a [`preLaunchTask`](https://code.visualstudio.com/docs/editor/tasks#_background-watching-tasks) on a Chrome launch configuration that starts the Vite server. This is a little more speedy and also allows you to start a new browser easily without having to restart the Vite server, but does require some extra config.
