### ISSUE TITLE
Test: No unnecessary notebook time line entries

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#208268]
Refs: https://github.com/microsoft/vscode/issues/205634

- [ ] anyOS @mjbvz
- [x] anyOS @joaomoreno

Complexity: 2

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208268%0A%0A&assignees=DonJayamanne)

---
**PreRequisites**
* Install the Jupyter Extension

**Steps**
* Open a workspace folder
* Create a Jupyter notebook
* Save this file
* Verify there's an entry in the timeline view for this notebook
* Save this file a few more times without making any changes
* Verify there are no new entries in the timeline view (previously we'd have one entry for each save operation)

**Comment by joaomoreno** [comment]
@DonJayamanne Bugs don't need to surface as testplan items, since we verify bugs. This would've been better served as verification steps in https://github.com/microsoft/vscode/issues/205634.
