### ISSUE TITLE
Safari: clicking to the right of some text puts cursor at the front

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#208262]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.88.0-insider in Safari
- OS Version: macOS

Steps to Reproduce:

1. In _Safari_ open https://insiders.vscode.dev
2. create a file with:
```
asdf
asdf
asdf
asdf
```
3. click to the right of any `asdf`
4. 🐛 the cursor goes to the beginning of the line not the end

https://github.com/microsoft/vscode/assets/2644648/da460347-23f7-4cc4-bdcf-ae1058a9df92

This does not repro in stable vscode.dev

**Comment by hediet** [comment]
I didn't do any changes the last couple of milestones that could (easily) explain this.
Can you reproduce this in the monaco editor? If so, can you do a bisect?

**Comment by TylerLeonhardt** [comment]
@hediet I bisected it to this commit: https://github.com/microsoft/vscode/commit/fb865521ceb96845e578c3f296663eacc1425921

**Comment by hediet** [comment]
This commit is just a rename refactoring. It is very unlikely it causes this... 
This does not reproduce in chrome, right?

**Comment by hediet** [comment]
Unfortunately, I don't have access to Safari.
Can you double check that this is caused by that commit? Can you locally rename the class back to the original name and see if it still happens?

It does not make any sense that this commit would cause this behavior only on Safari.

**Comment by TylerLeonhardt** [comment]
Ok @hediet and I paired a bit on this and are really stumped. Bad news: That commit I called out seems to be a red herring. Good news: we can repro in the Monaco Editor Playground.

Here's a side by side of two versions of the dev build:
<img width="1680" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/63932390-112e-4654-ab09-2b2dd9c8fce7">

You can see when I click to the right of a line, the older (working) build has the correct position here, while the newer broken build has column 1.

Here are the links to these versions:
* Working: https://microsoft.github.io/monaco-editor/playground.html?source=v0.47.0-dev-20240308#example-creating-the-editor-hello-world
* Broken: https://microsoft.github.io/monaco-editor/playground.html?source=v0.48.0-dev-20240319#example-creating-the-editor-hello-world

I believe this is out of both of our depths at this point so I'm passing to you @alexdima 

This is a regression so I think it should be fixed before we release (assuming I'm not the only one to repro)

**Comment by alexdima** [comment]
Did a bisect using `vscode-bisect -r web` and it points to https://github.com/microsoft/vscode/compare/8c8105002c089e657402b0f7ced80b2ecae6870c...d8880a78e9f88bbb117e4cde079b39838a924349

**Comment by hediet** [comment]
In that case, it is most likely 5faa55a173571edace9b667b9f4dd5e3b5136de3.
