### ISSUE TITLE
HTML Language Features extension for blade files.

### ISSUE THREAD

**Issue by dvlpr91** [microsoft/vscode#208272]
I would like to see the `HTML Language Features` extension also run in the `blade.php` file.

The blade.php file contains HTML, but the javascript suggestions are not exposed inside the `<script>` tag.

**Comment by aeschli** [comment]
PHP is an derivative of HTML, but not HTML. The HTML extension does not understand the PHP tempting tags.
The support needs to come from a PHP extension.
