### ISSUE TITLE
Inline chat appears hidden behind sticky scroll

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#208205]
https://github.com/microsoft/vscode/assets/16353531/d6274d09-c0f4-4a74-9936-914947ac9513

Version: 1.88.0-insider
Commit: f7c827a5e0ddbba66425ea54e33430bce8f53c84
Date: 2024-03-20T06:01:00.977Z
Electron: 28.2.6
ElectronBuildId: 27476517
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

**Comment by jrieken** [comment]
This turned out to be same as https://github.com/microsoft/vscode/issues/208375
