### ISSUE TITLE
More flexible syntax highlighting

### ISSUE THREAD

**Issue by larhun** [microsoft/vscode#208218]
This proposal is for a more flexible syntax highlighting system.

## Summary

The syntax highlighting system is a kind of typography tool. It makes understanding and navigating a source file easier by using different colors and styles for different syntax elements. It should be customizable to suit the user's preferences and needs.

The current implementation is based on two distinct processes: “tokenization” and “theming”. These strongly interact using “scopes” to assign colors and styles. This weird mix of language and theme specifications makes syntax highlighting and user customization a nightmare.

This proposal is about managing syntax highlighting using a standard  semantic “palette” of colors and styles. It extends the current implementation and decouples “tokenization” and “theming”.

The theme designer should assign colors and styles to the standard “palette” without any information about scopes. The language provider should assign scopes to the standard “palette” without any information about colors and styles.

The user customization may apply to the theme or language specifications. In the first case, it modifies colors assigned to a palette by a specific theme. In the latter case, it modifies scopes assigned to a palette by a specific language.

## Current implementation overview

The current syntax highlighting system is based on the interaction between two distinct processes: “tokenization” and “theming”.

“Tokenization” should be the job of a language provider. It should perform a syntax analysis. It should define tokens using a set of “TextMate” grammars and an optional “Semantic Token Provider”. The result should be theme-agnostic.

“Theming” should be the job of a graphic designer. It should define a consistent palette of colors and styles. It should assign colors and styles to all graphic elements in a program view preserving a good contrast between adjacent elements. The result should be language-agnostic.

The interaction between “tokenization” and “theming” is based on “scopes”: tokenization assigns tokens to scopes and theming assigns colors to scopes. The main advantage of the current implementation is that it is based on “TextMate” grammars. Many IDE systems contributed to these grammars and many components are ready to use for different languages and themes.

The main drawback is the poor decoupling between “tokenization” and “theming” because scopes have language-specific semantics injected into the theme specifications that should be language-agnostic. This weird mix of language and theme specifications makes system design and user customization a nightmare even for simple tasks. For example, the system design has all the following disadvantages.

- The theme designer may not have adequate language knowledge. For example, it may provide a good typography solution that fails to emphasize the syntax elements.
- The theme specifications may be hard to define. For example, the same token types with the same scopes may require an accent color for one language and a neutral color for another.
- Different themes may provide logically inconsistent specifications. For example, the same tokens of the same language may be associated with an accent color for one theme and a neutral color for another.

User customization is important and should be easy because users may have different preferences, habits, and needs. For example, the current implementation cannot easily support the following customization tasks.

- Use a theme with different preferences for writing, reviewing, or debugging. For example, a very detailed syntax highlighting for writing and a less distracting one for reviewing.
- Use a theme with different preferences for code and comments. For example, a very detailed syntax highlighting for code and a less distracting one for comments or vice versa.

## Proposal

I propose the following changes or other logically equivalent solutions for decoupling the interaction between “tokenization” and “theming”. They are based on a standard semantic “palette”.

### Standard semantic palette

A standard semantic “palette” is a set of names that identifies the relevance and relative contrast of colors and styles rather than their values. For example, “neutral” for a color with low contrast from a base background and “accent” for a color with high contrast. Maybe a palette with a neutral color, two primary colors, two secondary colors, and some tonal and style variations should be enough to provide a very detailed syntax highlighting.

### Theme specifications

The graphic designer should define a theme using a _*-color-theme.json_ file. In this file, it should include the definitions of the standard palette in the “basic” and “alternate” formats. The “alternate” format should assign a subset of colors and styles used by the “basic” format. Maybe no more than 3 colors. 

For example, the theme file could have the following additional keys.

```json
"palette-basic": {
    "neutral": {
        "foreground": "#839496"
    },
    "accent1": {
        "foreground": "#2d8cd0",
        "fontStyle": "bold"
    },
    "accent2": {
        "foreground": "#30a198",
    }
    ...
},
"palette-alternate": {
    "neutral": {
        "foreground": "#839496"
    },
    "accent1": {
        "foreground": "#2d8cd0",
        "fontStyle": "bold"
    },
    "accent2": {
        "foreground": "#839496",
    }
    ...
}
```

That makes theme specifications truly language-agnostic. They do not depend on scopes. They do not encode syntax information.

### Language specifications

The language provider defines the syntax using a _*.tmLanguage.json_ file. It should pair this file with a _*.palette.json_ file that assigns the used “scopes” to the names of the standard palette.

For example, the theme file could have the following format.

```json
{
    "neutral": ["comment", "variable"],
    "accent1": ["keyword"],
    "accent2": ["string"]
    ...
}
```

These specifications are under the full control of the language provider. They do not directly depend on color and style values. The contract between the language provider and the graphic designer is clear. The syntax is the duty of the language provider. The color and style values are the duty of the graphic designer. They interact through a well-defined semantic palette. For example, the language provider defines which tokens should have a neutral color, the graphic designer defines the value of the neutral color.

### User customization

The user customization of the highlighting system may apply to theme or language specifications.

A theme customization redefines colors and styles assigned to the standard palette of a selected theme. It directly applies to the theme and indirectly propagates to any language through the palette.

A language customization redefines scopes assigned to the palette of a selected language. It directly applies to the language and indirectly propagates to any themes through the palette.

A switch between the “basic” and “alternate” palette formats should be implemented similar to a switch between “dark” and “light” themes.

### Backward compatibility

The proposed system applies if the theme specifications provide the required palette definitions and the language specifications provide the additional palette file. Otherwise, the current implementation applies.

----

Thank you for reading this proposal.

**Comment by aeschli** [comment]
Thanks for the write-up. We have no plans to move away from the TextMate approach of tokenization and theming, nor do we want to add an extra concept. What you suggest can be built on top of what there is, by extensions or by theme generator tools

Example is the https://github.com/Tyriar/vscode-theme-generator is an example of such a tool

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/issues/56855 and https://github.com/microsoft/vscode/issues/105247 are similar requests
