### ISSUE TITLE
Diff Editor support sash on both sides of the gutter

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#208220]
The border on the left side of the gutter looks like a sash which makes me want to resize the diff view from there however it does not work. Would be great to be able to resize the split view from the left side as well.

![Code_-_Insiders_Ya1MvlG7xR](https://github.com/microsoft/vscode/assets/44439583/4dbbc918-565a-476e-8a2b-3bfc4e34bd49)

// cc @joaomoreno

**Comment by bpasero** [comment]
Yes, 💯 , I was about to file the exact same issue 👍

**Comment by bpasero** [comment]
Alternatively, I wonder if we should go back to a design where the shadow only appears where you can resize. Now it seems we added a second shadow, not sure what it adds though. It looks visually nice, but misleads me into thinking I can resize there.

**Comment by rebornix** [comment]
Ran into this in non-default themes and it looks like UI glitches. Hope we can lower the shadow opacity.
