### ISSUE TITLE
Unable to Access VSCode CodeSpaces for CS50X

### ISSUE THREAD

**Issue by TLPrice-52** [microsoft/vscode#208260]
FAILS TO LOAD COMPLETELY

Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
Please report this to your course support channel
