### ISSUE TITLE
Restore contents of quick open when reopening quick open after closing

### ISSUE THREAD

**Issue by marforic** [Microsoft/vscode#2082]
When going to a file (⌘-P) or executing a command (F1/SHIFT-⌘-P) as well as when interacting with other top-window dialogues (SHIFT-⌘-O) it would be really nice to keep the dialogue open (or at least pre-filled with whatever was written into it when tabbing-out and back -in the application.

This is useful when looking up a command online (having to tab-out of vscode and looking into a browser/mail) or also when working with other files (e.g., on a multi-file LaTeX document you start opening a file to edit, forget which is the correct one and quickly check it from the open PDF, when you get back you have to re-type it all in).

Overall it would be nice to have this feature (also potentially behind a setting).

**Comment by joaomoreno** [comment]
:+1:

**Comment by bpasero** [comment]
I wonder if I can detect that focus leaves the workbench. If yes, I think we could make this the default behaviour.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/444

**Comment by joaomoreno** [comment]
Not sure. This one seems lighter: it's about simply restoring the input when you open quick open, selecting the whole text, such that if you type you'd still get the old behaviour.

You don't even need to detect that focus leaves the workbench. Just store the value of the input every time it changes.

**Comment by bpasero** [comment]
@marforic given the new option to keep quick open opened even on focus lost, would you agree this issue is resolved?

**Comment by marforic** [comment]
@bpasero I would say, so, yes! Thank you :)
