### ISSUE TITLE
chevron matching in TypeScript

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#20824]
currently all paired braces, brackets and parentheses are highlighted except for chevrons which TypeScript uses for type parameters/arguments lists

so please enable paired chevron matching and highlighting

**Comment by mjbvz** [comment]
I believe this was an intentional change, see #13295

The old matching logic was causing more problems for some fairly common coding patterns. It could not be implemented correctly without a more complete understanding of the language and grammar
