### ISSUE TITLE
Double backslash in vscode launch.json doesn't work

### ISSUE THREAD

**Issue by thinkanddone** [microsoft/vscode#208300]
.vscode/launch.json

- Configure:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Demo",
            "program": "test",
            "args": ["--file_name=\\\"abc abc\\\""],
            "stopOnEntry": false, 
            "cwd": "${workspaceFolder}",
            "terminal": "console",
        }]
}
```

- Result:
```
"\\\"abc abc\\\""
```

Version: 1.87.1
Commit: 1e790d77f81672c49be070e04474901747115651
Date: 2024-03-06T00:21:36.258Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by roblourens** [comment]
Please file on the debug extension repo, thanks
