### ISSUE TITLE
Inline chat content widget doesn't relayout when having multiple input lines

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#208394]
* start inline chat
* in the content widget author multiple lines
* :bug: the widget's height doesn't change

**Comment by justschen** [comment]
still kind of running into this kinda - height changes, but the prompt layout after querying is unreadable.

also, seems like there is a weird horizontal scroll element on the bottom left of the widget? 
https://github.com/microsoft/vscode/assets/54879025/7faf4837-a555-4180-a558-7af0dd914888

**Comment by jrieken** [comment]
I see. This is because the height of the zone is limited by the overall height of the editor. It doesn't want to take more than 42% - that's something we can tweak but you might be facing a bit of a special case having a multiturn convo and accessibility viewer enabled as well.

**Comment by rzhao271** [comment]
The first prompt handles a long string nicely.
A long string for the follow-up prompt results in content overflow.

![Content overflow during follow-up prompt](https://github.com/microsoft/vscode/assets/7199958/408bef19-fde5-4ff2-8df0-922d089dbe4c)
