### ISSUE TITLE
CodeWindow: renderer process gone (reason: crashed, code: -2147483645)

### ISSUE THREAD

**Issue by Hykaruu** [microsoft/vscode#208363]
Type: <b>Bug</b>

Couldn't open VScode at all.
Tried cleaning cache, settings, disabling all extensions, admin permissions...
Only worked with code --disable-chromium-sandbox.
Issue related to Chromium Sandbox for Electron-based apps?

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (6.12GB free)|
|Process Argv|--disable-chromium-sandbox --crash-reporter-id 3979b308-8805-4fd4-b848-c7224d025fad|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
custom-md-pdf|Dea|2.0.3
copilot|Git|1.175.0
copilot-chat|Git|0.13.1
latex-workshop|Jam|9.19.1
vsc-python-indent|Kev|1.18.0
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.110.2024030815
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.5.2024031109
pdf|tom|1.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30992801
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:30996668
666c4381:30973075
7ghi1836:30988842
dsvsc021:30996838

```

</details>

**Comment by Hykaruu** [comment]
GUI level error is: The window terminated unexpectedly (reason: 'crashed', code: '-2147483645').

**Comment by jayendranarumugam** [comment]
Same here, I tried Insider and the latest version too.

**Comment by Hykaruu** [comment]
> Same here, I tried Insider and the latest version too.

Mine seems to be working well again, I don't know what's the fix. Reboot computer?

NB: I was using Cursor lately and it wasn't working too like VSCode.

**Comment by jayendranarumugam** [comment]
> Mine seems to be working well again, I don't know what's the fix. Reboot computer?

Tried the reboot still the same issue, Besides I don't have cursor in my machine either

**Comment by rzhao271** [comment]
Closing for now. If the issue occurs again on the latest VS Code, feel free to file a new issue and attach a crash report, following the steps at [Creating a Crash Report](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report).
