### ISSUE TITLE
Test: Locked Scrolling (Synchronize Scrolling)

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#208385]
Refs: #33110

- [x] anyOS @eleanorjboyd
- [x] anyOS @hediet

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208385%0A%0A&assignees=benibenj)

---

This iteration we added a feature which allows to scroll all visible editors across editor groups at the same time.

**Setup: Open many Editor groups**
1. Open multiple editor groups (can be done by opening a code editor and running the command `View: Split Editor`)
2. Open at least one editor in a floating window (`View: Move Editor into New Window`)
3. In one of the groups you should run the command `View: Split Editor in Group` (opens side by side editor)
4. Open a notebook in one of the editors

Your setup might look something like this (At least one notebook open, one code editor open and side by side editor open)
<img width="1248" alt="cMZmeGSaHm" src="https://github.com/microsoft/vscode/assets/44439583/cbde598d-f272-4ca6-a5a7-0849d1184563">

**Testing**
1. Run the command `View: Toggle Locked Scrolling Across Editors`
2. You should see an entry in the status bar with the text `Scrolling Locked`
3. Scroll one editor, see how all other editors also scroll. 
4. Make sure for each editor it is possible to scroll all the way to the top/bottom
5. Open and close editors and editor groups. The scrolling should also be synchronized for these newly opened editors
6. Press on the status bar item `Scrolling Locked`. This should stop the synchronized scrolling. Scrolling in one editor does not affect others

**Comment by hediet** [comment]
Nice work!
