### ISSUE TITLE
'document.queryCommandSupported' is deprecated

### ISSUE THREAD

**Issue by Lemour-sudo** [microsoft/vscode#208390]
https://github.com/microsoft/vscode/blob/2fda9b1fa4abf8b121e93e99901a1b04e7ace6f2/src/vs/editor/contrib/clipboard/browser/clipboard.ts#L27-L32

Are there any plans to replace the usage of `document.queryCommandSupported` [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Document/queryCommandSupported) method?

**Comment by mjbvz** [comment]
Closing as there isn't a reason to replace it and it's only being used for Firefox

**Comment by Lemour-sudo** [comment]
@mjbvz Any suggestion on how to work around this when testing with Vitest because this part of the code fails when running tests in both the happy-dom and jsdom environments?
