### ISSUE TITLE
Auto-commit characters do not work consistently

### ISSUE THREAD

**Issue by frevds** [microsoft/vscode#208332]
Type: <b>Bug</b>

In TypeScript, I can use the "." as an auto-commit character for committing the suggestion only in the left-hand-side expression. After an " = " in the right-hand-side they don't seem to work. 
Also, these characters cannot be configured. 

It is extremely annoying during development. I unlearnt my prior behaviour from other editors and am pressing Return or Tab all the time for autocompletion, but am annoyed having to do this explicitly. 

It is surprising that a feature as very basic and essential as this does not get properly implemented in VSCode for such a long time. If Visual Studio is able to do it, VSCode should be. 

Furthermore, committing a suggestion does not recognize what follows, always committing the whole word even if the rest of the word is already there, forcing everybody to delete the rest of the word. These basic convenience features are expected of a proper code editor. If it's too complicated to implement using a Regex-based system, I'm afraid you'll have to find a different way, having this not working properly cannot be excused, it's a must to have, or a reason to switch to a different editor. 

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.34GB free)|
|Process Argv|--crash-reporter-id fd07ca10-4e2d-453c-ba70-cbc1dfbb2fa2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pandoc|Chr|0.4.5
vscode-typescript-to-json-schema|mar|0.0.17
debugpy|ms-|2024.2.0
isort|ms-|2023.10.1
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
jupyter|ms-|2024.2.0
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.6
cpptools|ms-|1.19.8
vscode-xml|red|0.26.1
LiveServer|rit|5.7.9
vscode-counter|uct|3.4.0
vscode-icons|vsc|12.7.0
markdown-pdf|yza|1.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30992801
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30991133
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r3:30958155
dsvsc020:30976470
gee8j676:30988843

```

</details>

**Comment by mjbvz** [comment]
@RyanCavanaugh I think the proper fix is for TS to compute commit characters instead of having VS Code try to derive them: https://github.com/microsoft/TypeScript/issues/27623

Closing in favor of that issue which also should align with lsp

**Comment by frevds** [comment]
May I point out the other part of my request @mjbvz this again: 

> Furthermore, committing a suggestion does not recognize what follows, always committing the whole word even if the rest of the word is already there, forcing everybody to delete the rest of the word. 

Anything that can be done here?
