### ISSUE TITLE
Implementations Code Lens For TypeScript

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#20832]

**Comment by isidorn** [comment]
I tried setting "typescript.implementationsCodeLens.enabled": true - however there was no effect on the vscode worksace.
I only get typescript codelense if I set	"typescript.referencesCodeLens.enabled": true, however `implementationsCodeLens` makes no difference.
What am I doing wrong here?

**Comment by chrmarti** [comment]
It's not connected to the configuration change event. Will link a PR fixing that. Reopening so we can decide on what to do. /cc @kieferrm

**Comment by roblourens** [comment]
Side question, is the implementation supposed to be highlighted like this?

![image](https://cloud.githubusercontent.com/assets/323878/24482354/6c2a30b4-14a5-11e7-8d61-a1e63853f3d4.png)

**Comment by roblourens** [comment]
I guess so, same color as used for 'find references', just... more

**Comment by isidorn** [comment]
@chrmarti I still do not see this working in latest insiders. 
Just wanted to let you know since i think your PR was merged

**Comment by chrmarti** [comment]
Just checked and it seems to work for:
```ts
interface Foo {
    bar(): void;
}

class Baz implements Foo {
    bar() {
    }
}

new Baz().bar();
```

That shows as:
![screen shot 2017-03-30 at 7 38 04 am](https://cloud.githubusercontent.com/assets/9205389/24509741/0d798f02-151c-11e7-8a11-83bceb9b160c.png)

I wonder if `bar()` on the interface should also show an implementation. With the fix, the lenses now update with the configuration change without reload for me. (Closing for verification.)

**Comment by chrmarti** [comment]
Verifier: This requires TypeScript 2.2.0 or higher to work.
