### ISSUE TITLE
VS Code 1.88-insider `glibc` error when connecting to Amazon Linux 2 remote machine

### ISSUE THREAD

**Issue by wlovo** [microsoft/vscode#208313]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.88.0-insider (Universal)
- OS Version: Darwin x64 23.3.0

Hey VS Code team. I'm reaching back out on behalf of the IDE team at Amazon.

We recently started receiving reports from within the company that they are experiencing issues similar to those experienced in https://github.com/microsoft/vscode/issues/203375. Is there a plan to revert the workaround(s) provided by the January recovery release or is this an unexpected issue?

Steps to Reproduce:

1. Install the latest insider version of VS Code
2. Update Remote - SSH extension to insider build
3. Attempt to connect to an Amazon Linux 2 remote machine
4. Encounter an error
```
Failed to connect to the remote extension host server (Error: WrappedError(WrappedError { message: "error checking server integrity", original: "failed to run command \"/home/niebloom/.vscode-server-insiders/cli/servers/Insiders-09d5f4efc5089ce2fc5c8f6aeb51d728d7f4e758.staging/server/bin/code-server-insiders --version\" (code 100): Warning: Missing GLIBC >= 2.28! from /usr/lib64/libc-2.26.so\nWarning: Missing required dependencies. Please refer to our FAQ https://aka.ms/vscode-remote/faq/old-linux for additional information.\n" }))
```

Looking forward to a response, thanks!

**Comment by wlovo** [comment]
Sorry to ping you directly @isidorn

**Comment by deepak1556** [comment]
Hi, we are not reverting the workaround from January release however we are changing some internal implementations in https://github.com/microsoft/vscode/issues/206790 that led to the above temporary breakage. A new version of SSH extension with the changes will be released today and it should the resolve the issue.
