### ISSUE TITLE
Test: Keybinding to move between separators of a quick pick

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#208367]
Refs: https://github.com/microsoft/vscode/issues/70861

- [x] macOS @lramos15
- [x] linux @ulugbekna
- [x] windows @luabud

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208367%0A%0A&assignees=TylerLeonhardt)

---

Try out the new keybinding to move between separators of a quick pick!

* Open a quick pick with separators (like the command palette, but try others that you know!)
* Navigate between the separators!
  * macOS: cmd+up/down
  * linux/windows: alt+up/down
* Open "Quick Search (Experimental)" via the Command Palette
* Search for something
* Navigate between the full-length separators!

Enjoy!

**Comment by luabud** [comment]
this is awesome 🥳
