### ISSUE TITLE
Opening recent from macOS dock creates a duplicate workspace

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#208321]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2
- OS Version:  macOS Sonoma

Steps to Reproduce:

1. From `File/Open Folder` create a new project named Test.
2. Close it.
3. Open it from the VSCode's dock context menu.
4. `File/Open Recent` should now look like:

<img width="547" alt="image" src="https://github.com/microsoft/vscode/assets/2845433/6889429a-9d2c-4291-b4bc-549a876f76cd">

This is not only a duplicated entry in the menu. If you change the state of one of those projects, say you open a new tab with some file, the change is not propagated to the other one. Of course the new file in the folder will be visible by both, I'm just referring to the state of the workspace. They are actually seen as different workspaces at some level.

It's causing this bug https://github.com/REditorSupport/vscode-R/issues/1504

**Comment by bpasero** [comment]
Can you share the contents of the `"history.recentlyOpenedPathsList"` key when you run the command "Log Storage Database Contents"

**Comment by bpasero** [comment]
So how did you manage to open the one path in the one form and the other in the other? Was a terminal involved?

**Comment by memeplex** [comment]
Just as described in the steps above.

1. "File/Open Folder" and create Test in Finder dialog (the encoding for this one is `Maestr%C3%ADa`)
2. Close it.
3. Open the context menu in Dock and select Test.

From the terminal it opens `Maestr%C3%ADa` as in (1). The wrong encoding seems to be the one produced from Dock.

**Comment by bpasero** [comment]
I can reproduce. What puzzles me is how we can have an encoding issue here, as we use UTF-8 for storing these paths everywhere.

My feeling is this maybe another instance of unicode NFD vs NFC from the string we get back...

**Comment by bpasero** [comment]
Yes, it is related to NFD vs NFC form on macOS. Incredible how only now this was reported, given this bug must have existed for pretty much the entire lifetime of VS Code.

Thanks for reporting! Fix coming.

**Comment by memeplex** [comment]
Thank you!
