### ISSUE TITLE
GoToDefinition doesn't scroll to the top of the blue definition UI

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#20835]
- VSCode Version: 1.9.1 and 1.10.0-insiders
- OS Version: Win10

Steps to Reproduce:

1. I'm using a high DPI laptop (not sure if that's required).
2. Cause the Problems/etc. pane to appear and split the UI 50%.
3. Use Go to (Peek) Definition using any language that supports it.

Bug: See the screenshot. The blue "definition" box is not scrolled up to the top, which is really annoying when the document is large and it's hard to scroll up by a small amount to see the definition options on the right. The repro seems 100% when the UI is sufficiently constrained. I need to see the top because that's where the definition list is (when things are defined in multiple places).

Bug#2: The lack of the top/bottom arrow buttons makes it hard to scroll up/down by single lines when the document is large, and using the keyboard to go up lines doesn't work if the keyboard cursor is stuck in the blue box.

![image](https://cloud.githubusercontent.com/assets/19859882/23085789/763027fe-f51e-11e6-9a95-9029e8bb7e57.png)

**Comment by jrieken** [comment]
@sean-mcmanus Do you use code-lenses? Like git version lenses or reference lenses?

**Comment by sean-mcmanus** [comment]
I am not using any code lens. It repros without any extensions. It repros on a non-high DPI machine too. The only repro requirement is to have "not enough" vertical height in the document view. It appears that code needs to be added to ensure that the document scrollbar is set to make the line with the blue cursor visible (i.e. top of the blue peek window).

**Comment by jrieken** [comment]
This got fixed with #23310  and by a new constraint the peek view always fits into the view port
