### ISSUE TITLE
Customizable Commands for GitHub Copilot Chat

### ISSUE THREAD

**Issue by Alsheh** [microsoft/vscode#208334]
As a user of GitHub Copilot, I would like the ability to customize and add commands to the Copilot Chat. Currently, the commands and functionality provided by GitHub Copilot are predefined and cannot be modified by users. This limitation restricts the flexibility and adaptability of the tool to individual user needs.

This feature could be implemented as a settings option where users can define their custom commands and specify the actions to be performed when these commands are used. The custom commands could then be integrated into the existing command structure of GitHub Copilot.

Thank you for considering this feature request.

**Comment by bararchy** [comment]
I'm also interested in that capability

**Comment by roblourens** [comment]
You may be interested in the in-progress participant API: https://github.com/microsoft/vscode/issues/199908
