### ISSUE TITLE
Markdown Preview Suggestion

### ISSUE THREAD

**Issue by dsifford** [Microsoft/vscode#20836]
Hi there. Just a friendly drop in the suggestion box:

One of the biggest pain points I've had in VS Code is how markdown preview works.

Currently, if a user has a dark theme selected, then the markdown preview will render in a dark style. Period. Even with custom CSS set.

I'm a huge proponent for dark themes for code, but I'd prefer to personally read markdown the same way as it will read on Github, Gitlab, etc (with a light theme).

As of right now, I'm finding myself using VS Code for everything -- except markdown -- for this very reason. It's really the only reason I have atom still installed on my machine.

Thanks for considering!

**Comment by mjbvz** [comment]
I've prototype an API that allows extensions to contribute styles and other features to the markdown preview: #22916

Here's a prototype extension that contributes a github style: https://github.com/mjbvz/vscode-github-markdown-preview-style Give it a try in the latest insiders builds and let me know if you run into any issues. Also, please let me know if you are interested in authoring/contributing to an extension that changes the markdown preview style

**Comment by dsifford** [comment]
@mjbvz Sorry for the delay!

Just installed insiders and tried installing using the `vsix` file in that repo and it looks like it's not the right extension. The title is correct, but the details lead me to believe that it's an old build of a test extension that enables GFM checkboxes. Any tips?

> Also, please let me know if you are interested in authoring/contributing to an extension that changes the markdown preview style

I'd be happy to help if that's needed.

**Comment by mjbvz** [comment]
Thanks, I've update the readme and rebuilt the vsix. Here's what the preview normally looks like:

![screen shot 2017-04-14 at 12 11 38 am](https://cloud.githubusercontent.com/assets/12821956/25036160/0626396c-20a7-11e7-9057-aa0ce7546478.png)

and here's what it should look like with the extension enabled:

![screen shot 2017-04-14 at 12 11 18 am](https://cloud.githubusercontent.com/assets/12821956/25036159/0620f81c-20a7-11e7-9a81-b783cbec5674.png)

Feel free to try out the github example extension and submit PRs or file issues against it if you notice any bugs. I'm not going to publish it to the marketplace until we ship this extension functionality in the main VSCode code release

If you have any other ideas on how you could use an extension to customize the markdown preview styling, you can also try putting together a new extension. I'd be happy to help out if you have any questions on this and the Github style extension may be a good starting point for this. I'd also be interested to hear if you run into any obstacles with the new API or have any feedback on it

**Comment by dsifford** [comment]
@mjbvz Hey, sorry about that. I think my brain must have been halfway powered off last night when I tried it 😝 

I'd be happy to maintain a github markdown style package if you're looking to offload that duty to free up bandwidth on yourself. 

That said, I can't really try it out until it lands in the regular build because the insiders edition package for my arch isn't building due to failed checksums. (Arch linux)

I installed the insiders edition on my Macbook pro but it doesn't look like any of my settings carry over between the two so I'd prefer not to travel down that rabbit hole if I can avoid it.

**Comment by ramya-rao-a** [comment]
@mjbvz Installed the six, but I still see the preview in dark background while using dark theme

**Comment by mjbvz** [comment]
Thank you for testing this @ramya-rao-a, but this issue this should not have been included in the milestone. Sorry about that.

We're going to keep the the markdown preview extensions experimental at least one more iteration to give the general preview story Ben is looking into time to settle down

**Comment by ramya-rao-a** [comment]
Then can you move it to the next milestone so that it can verified next month?
