### ISSUE TITLE
Test: Custom Editor Labels

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#208388]
Refs: #41909

- [x] macOS @paulacamargo25
- [x] linux @andreamah
- [x] windows @hediet

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208388%0A%0A&assignees=benibenj)

---

In this iteration we added support to change the labels of open editors (Name displayed in the tabs and open editors view). Users can do this by adding an entry in the `workbench.editor.customLabels.patterns` setting. An entry consists of:
- **Item:** Glob Pattern that matches the file path of the editor. If the pattern is a relative pattern, then it is matched against the relative file path of the editor (relative to current workspace). If the pattern is an absolute pattern (starts with /), then it is matched against the absolute file path of the editor.
- **Value:** Template which defines how the label should be rendered. The template can include the following variables which will then be replaced with the respective values of the current matched pattern:
  - `${extname}`: The file extension of the current editor (`txt`, `py`, `ts`).
  - `${filename}`: The name of the file of the current editor. Does not include the extension. (`root/parentFolder/folder/file.txt` => `file`)
  - `${dirname}`: The name of the folder the file of the current editor is placed in. (`root/parentFolder/folder/file.txt` => `folder`)
  - `${dirname(N)}`: The name of the **nth parent folder** in which the file is located:
    - `${dirname(0)}` is the same as `${dirname}`: (`root/parentFolder/folder/file.txt` => `folder`)
    - `${dirname(1)}` is the parent folder of `${dirname(0)}`: `root/parentFolder/folder/file.txt` => `parentFolder`
    - `${dirname(2)}` is the parent folder of `${dirname(1)}`: `root/parentFolder/folder/file.txt` => `root`
    - `${dirname(3)}` is the parent folder of `${dirname(2)}`: For the file path `root/parentFolder/folder/file.txt`, `root` is at level 2 and does not have a parent folder. In this case there is no value we can replace `${dirname(3)}` with so we render the variable name as is. The reason we render the variable in the name is so that the user is aware that his template doesn't properly work for his case and hence should fix it.

**Testing:**
1. Add a simple patern and a template and see how the editor names are changed. A very simple option could be:
- Pattern: `**`, Template: `Hello World`: 
- The `**` pattern will match with every single editor. This means no matter which editor you open it will be called `Hello World`. Check both the name rendered in the tab and the name rendered in the open editors view

![Code_-_Insiders_qcYQIAkbwT](https://github.com/microsoft/vscode/assets/44439583/a5c85043-9a87-48b7-97ab-75d6722639b1)

2. Set `workbench.editor.customLabels.enabled` to `false`: All editors will have the REAL name again.
3. Set `workbench.editor.customLabels.enabled` back to `true`: All editor will have the `Hello World` name again
4. Remove the previously added pattern.
5. Add a more complex pattern. Here an example for the `AbstractTree.ts` file in the `vscode` repository located at `src/vs/base/browser/ui/tree/abstractTree.ts`. Open the file and add the pattern, see how it will be renamed. 
- Pattern: `src/**/abstractTree.ts`, Template: `${dirname}/${filename}`:
- The file will now be rendered as `tree/abstractTree`. As this is the only editor that matches with the pattern, no other editor is renamed.
![Code_-_Insiders_LRL82rvjHO](https://github.com/microsoft/vscode/assets/44439583/ccd9c42c-0534-4781-8881-f0700699db73)

6. Add one more pattern (you should then have 2 patterns total) which will also match with that file. Make the pattern more specific then the previous one. For example:
- Pattern: `src/vs/base/**/abstractTree.ts`, Template: `${dirname(1)}/${dirname}/${filename}`:
- The file will now be rendered as `ui/tree/abstractTree` because this pattern is more specific compared to the pattern previously 

![Code_-_Insiders_KBjRFSOVEp](https://github.com/microsoft/vscode/assets/44439583/d21c5fd5-3de1-48ce-8160-8aa2028b65be)

**Comment by hediet** [comment]
Super nice feature!

**Comment by andreamah** [comment]
Nifty feature!

**Comment by paulacamargo25** [comment]
Nice work 👍 ❤️

**Comment by ronsig** [comment]
If I want my vscode extension to set the **workbench.editor.customLabels.enabled** setting to **true**, and more importantly, the **workbench.editor.customLabels.patterns** setting inside its contribution point in package.json, how would I go about doing it?
Thanks

**Comment by benibenj** [comment]
@ronsig You can use `configurationDefaults` to set the default value of a setting. We are working on a better way for extensions to provide patterns such that a user can have multiple extensions providing patterns. Tracking this issue here: #211632
