### ISSUE TITLE
Maintain Code Collection State When Reopening Files

### ISSUE THREAD

**Issue by Dhuky** [microsoft/vscode#208301]
Hello!

I'm writing to suggest a feature that I believe would be very useful to many users. Currently, when we collapse blocks of code or functions into our files and close the file, the collapsed state is not maintained when we reopen the file. This might be a little inconvenient, especially when we are working on large code files with many functions and code blocks.

It would be great if VSCode could remember which parts of the code were collapsed and maintain that state when reopening the file. This would make it much easier for us developers to pick up where we left off,
especially in longer coding sessions.

Thank you in advance for considering this feature request. I believe this would significantly improve the user experience in VSCode.

**Comment by aeschli** [comment]
Folding states are remembered across restarts. Can you provide a small sample code with steps that shows this?
Please disable all extension to make sure this is not caused by an extension.
