### ISSUE TITLE
Surround with Snippet not working inside react components return statement

### ISSUE THREAD

**Issue by Fabioni** [microsoft/vscode#208344]
Type: <b>Bug</b>

When clicking "Surround with Snippet", having text selecting inside react components return statement, nothing happens. VS Code does not show the suggestions and also does not show any error

VS Code version: Code 1.87.2 (Universal) (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|36.00GB (2.58GB free)|
|Process Argv|--crash-reporter-id 790309d7-217c-41ad-b649-4383c67a3a2e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-tailwindcss|bra|0.10.5
vscode-eslint|dba|2.4.4
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.9.0
copilot|Git|1.175.0
copilot-chat|Git|0.13.1
todo-tree|Gru|0.0.226
svg|joc|1.5.3
vscode-language-pack-de|MS-|1.87.2024031309
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
vsliveshare|ms-|1.0.5918
react-hooks-snippet|op-|1.1.4
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
region-highlighter|Wie|1.0.1
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30992800
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30991133
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470

```

</details>

**Comment by jrieken** [comment]
This issue lacks

* a copy paste friendly sample of the snippet and file into which you are inserting this

**Comment by Fabioni** [comment]
@jrieken, there is not more to say about this. Just try this code inside https://vscode.dev/ 

```jsx
export const Component = () => {
    const here_it_works = "I like vs code" 

    return (
        <div>
                inside the react html code it does not work
        </div>
    )
}
```

**Comment by ArturoDent** [comment]
You should also show the snippet you are trying to use to surround with.

**Comment by Fabioni** [comment]
As I said "VS Code does not show the suggestions and also does not show any error", so it is independent from the snippet I want to insert, just any snippet. Clicking "Surround with Snippet" is just not doing anything.

But if you think you need one:
```
	"Translate string": {
		"scope": "javascript,typescript,javascriptreact,typescriptreact,",
		"prefix": "t",
		"body": [
			"{t('$1$TM_SELECTED_TEXT')}"
		],
		"description": "Translate a string",
	}
```

**Comment by ArturoDent** [comment]
I see that if the `scope` option is commented-out, it works.  VS Code cannot recognize that part of the file as `javascriptreact` apparently.

Also, just for testing purposes, selecting the entire `div` element does work as expected, but selecting just the `div` content does not.

**Comment by jrieken** [comment]
Please select "F1 > Inspect Editor Tokens and Scopes". Use the picker and select the editor location at which you want the snippet and check what language is detected

**Comment by Fabioni** [comment]
Sometimes it gives: "jsx-tags", this is when it was not working, sometimes "typescriptreact" and it works.

Knowing this, the rest does work as expected. I do not know enough about the internal of vscode to say if this is the proper behaviour, though.

This is now the scope for my snippet: `"scope": "javascript,typescript,javascriptreact,typescriptreact,jsx-tags",`

Thank you so much @jrieken.
