### ISSUE TITLE
copy/paste with another theme

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#20837]
![image](https://cloud.githubusercontent.com/assets/1487073/23088119/727807b6-f52e-11e6-9e53-7ed16f24745d.png)

Turn on default dark them
edit a markdown file
copy, paste text into email

result: the black background of the text is also pasted into the email. I just want the text...

![image](https://cloud.githubusercontent.com/assets/1487073/23088144/b1c77384-f52e-11e6-8b23-4cd8262d4b46.png)

I turned on the dark theme in Visual Studio, copy/pasted some code, and here are the results.  the first block of code is the copy/paste from VS, the second is the copy/paste from VS Code:

![image](https://cloud.githubusercontent.com/assets/1487073/23088224/46cbd9c0-f52f-11e6-8bc9-8870b7b17b03.png)

**Comment by Ikuyadeu** [comment]
Is this related  #20811?

**Comment by rebornix** [comment]
Firstly, we can't just copy the colored text without background as in Dark theme, the font color is light (sometimes just white) so copying white text with no background is not reasonable. You can hardly see anything when pasting it to a light themed application.

Visual Studio has three built-in themes, even if you are in Dark theme, the content is always copied with the light theme. So this feature request is actually similar to Copy text with Syntax Highlighting in another specific theme. It's easy to do so as VS gets all ideas about the light theme but for us, as we support third party themes, we cannot decide what theme to use when copy/paste so right now we choose the one users are using at the moment.

For short, temporary workaround is switching to the ideal theme you want to copy/paste. In the long term, we can provide an option for users to configure what theme they want to use for copy/paste. But users need to pay the price of this feature: we have to render all lines with correct CSS class/styles if you choose any theme other than the one you are using, it might take a while.

**Comment by vscpp** [comment]
Strong request to improve this feature.
Copy the text to Outlook, there is a large black with background color.
But copy to Micorsoft Lync, no background color, it's difficult to read text as below picture.
![untitled](https://cloud.githubusercontent.com/assets/26138585/25003460/1399953c-2082-11e7-836d-96e8899f0cae.png)

Very thanks for your effort.

**Comment by wyckster** [comment]
I think the feature should be that you can set one theme for display, and a separate theme for copy/paste.
I'd like to set my display theme to Dark+ (default dark), but when I copy and paste to another application with formatting, I want the theme to be Light+ (default light).  So there should be a way of selecting those two themes separately.

If nothing else, perhaps there should be a user setting where I can override the theme to apply to copied text.

**Comment by jackhorton** [comment]
I would like to voice my support here -- while I prefer to write code with a dark background, any time I copy/paste it to another app, itll be going against a white background. Neither paste-with-background or paste-without-background are good options, there, and it would really be best to simply copy as if i were using a light theme.

**Comment by oxydron** [comment]
Copy command should be neutral, copy only text and nothing else more.
I need to open my stuff on another editor just to copy text neutral.

**Comment by fungos** [comment]
This is becoming too annoying that I'm considering getting back to sublime only because of this tiny issue. Please, let at least it be configurable like: copyRawTextOnly or something. 

There are times where we want to copy/paste with language syntax highlight, that is fine. But if the text is, like Markdown, a .txt file or just a opened unsaved buffer, then it is raw text and nothing else, so avoid styles and coloring in these situation please.

**Comment by oxydron** [comment]
@fungos and moreover, most text editors I record, do copy/cut operations neutral. To copy stuff with themes, colors, etc, should be a special feature, not the standard option, different from most text editors.

**Comment by NorthboundTrain** [comment]
A simple solution would be to have two capabilities, copy with formatting and copy without formatting, and then let the users decide which one is used when Edit -> Copy is chosen; they can put the other on a different key combination, if desired.

**Comment by oxydron** [comment]
The summary then:
- ctrl+c (or copy) should copy only text
- Provide a copy with formatting option
- Provide a different shortcut for it like ctrl+shift+c

**Comment by stephen-mathew** [comment]
VSCode really lags behind with this feature. Really wish this was present - maybe as someone suggested, that copy+paste works on a default theme always and display has a different theme.

**Comment by amccaugh** [comment]
Adding my voice to the mix, I agree with @oxydron it should be 
- ctrl+c (or copy) should copy only text
- Provide a copy with formatting option
- Provide a different shortcut for it like ctrl+shift+c

Text editors that copy plaintext with ctrl-c:
- SublimeText
- Atom
- Notepad++
- BBEdit
- EditPlus
- Notepad
- Eclipse
- Kedit
- TextEdit

Editors that copy with theme formatting with ctrl-c:
- VS Code

**Comment by jeremychone** [comment]
This is a big productivity breaker. Copy/Paste into a Gmail email has become very cumbersome. Somehow, I did not notice that until a few months ago. 

My workaround right now is to paste it into an empty sublime text tab and then copy paste it back to gmail. I really love VSCode, and I am 99% migrated to VSCode, but for this "feature". 

I think the default should be without style, but even if the default is with style, we should have at least a way to copy text only.

**Comment by davydden** [comment]
> For short, temporary workaround is switching to the ideal theme you want to copy/paste. In the long term, we can provide an option for users to configure what theme they want to use for copy/paste.

why not providing an option to use text copying by default? 

From https://github.com/Microsoft/vscode/issues/21071#issuecomment-303750728

> Make this a user setting like "editor.copyWithFormatting" and with the options true/false.

p.s. I use dark theme but I usually copy-paste the code as plain text. It's very inconvenient right now and I have to open some other editor and first paste the code there...

**Comment by C0FF33** [comment]
+1 This really is a no-brainer user setting to add, in fact, if nothing else, it should be turned off by default.

**Comment by wpj-wpj-wpj** [comment]
I feel good when copy with black background.
![image](https://user-images.githubusercontent.com/26898312/42546959-54fdd8fa-84f2-11e8-8e83-eef83480ab55.png)
After install Xcode，I lost this functionality. I don't know the reaon. How can i get it back? @rebornix 
![image](https://user-images.githubusercontent.com/26898312/42546929-34bcf15c-84f2-11e8-9328-80840acc675e.png)

**Comment by Monolith-681** [comment]
+1. This is a necessity.

**Comment by pragdave** [comment]
While waiting for a fix, I hacked up an ugly bit of Swift (my first time coding Swift) that removes the background color on OS X.

https://gist.github.com/pragdave/6fc95ff2420dea51842717a5da7a98ff

**Comment by rednevals** [comment]
Is anyone working on this? It's very annoying. It's hard to believe that this is not bothering more people, ;)

**Comment by rebornix** [comment]
In latest Insiders, you can disable copy with syntax highlighting by setting `editor.copyWithSyntaxHighlighting` to `false` and command "Copy with syntax highlighting" still works as expected.

Right now,  we don't have plan to support copying with another theme in the near term.

**Comment by platy** [comment]
The config setting which allows switching to a plain text copy `editor.copyWithSyntaxHighlighting` pointed out by @rebornix above is available in the stable release now (possibly since some time ago).

**Comment by jihu** [comment]
> The config setting which allows switching to a plain text copy `editor.copyWithSyntaxHighlighting` pointed out by @rebornix above is available in the stable release now (possibly since some time ago).

This is not correct, sadly. I just tested this, copying an xml attribute that is styled as bold and blue. Setting copyWithSyntaxHighlighting to true removes the blue color from the copied text, but the bold format still remains. That is clearly not "plain text".

**Comment by matkoniecz** [comment]
@jihu In such case you may try to open new issue, if it is not already covered by one of open or rejected ones.

Here "copy with another theme" was rejected, but "copy as a proper plaintext like any sane editor" was not (maybe it was rejected elsewhere!)

**Comment by jihu** [comment]
@matkoniecz I did create a ticket after posting that comment:

https://github.com/microsoft/vscode/issues/117879

**Comment by ivyshaft** [comment]
I recently found this thread. I solved this issue for myself by _setting up a convenient hotkey to toggle the Dark mode._ 

Hit Ctrl + Shift + P to pull up the Command Palette. Search for "Toggle" and you should see the following option appear: "**Preferences: Toggle between Light/Dark Themes**". 

You can set a hotkey combo for this function and VSCode will switch between your preferred Light and Dark themes quickly. This makes copying the text while using light theme much quicker, and allows you to switch back to Dark mode for editing quickly. 


Cheers.

**Comment by wyckster** [comment]
This issue was closed by someone that never copies and pastes code from a dark theme VSCode editor into Word documents or PowerPoint presentations. 😞

**Comment by xKRISTOFx** [comment]
@wyckster it seems that's true but tbh I will probably stick to dark mode because I can't find any well-designed syntax highlighting color scheme for light mode, they all seem not to be as informational as dark one. I feel like they are less informative. And extension I mentioned before has its problems, for example when switching that fast not all syntax is colored because it takes some time cor coloring to fully load which can be observed while changing theme.
