### ISSUE TITLE
ctrl+c in a file without a selection is being handled by chat-codeblock

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#208413]
I find myself accidentally copying he entire file recently, turns out this is because we no longer copy a line when there is no selection but the whole file. When I enable keybinding troubleshooting I see it's being handled by chat-codeblock:

```
2024-03-22 07:10:04.097 [trace] Command 'editor.action.clipboardCopyAction' was handled by 'chat-codeblock'.
```

I didn't have chat open at the time

**Comment by roblourens** [comment]
This is from https://github.com/microsoft/vscode/blob/eff6c61b1ce1217c5f1dcc60c09cd7f781849749/src/vs/workbench/contrib/terminalContrib/chat/browser/terminalChatController.ts#L116-L132

I don't fully understand the `IChatCodeBlockContextProviderService`, but this should be trying to determine whether this codeblock belongs to some chat view, but it just returns the passed in editor all the time.

**Comment by roblourens** [comment]
Since Megan is out, if you want to do some quick fix @Tyriar, I think there is a scheme for all chat codeblocks that Matt added and we could just add a check for that in here.
