### ISSUE TITLE
Improve Translation in Chinese

### ISSUE THREAD

**Issue by wangweixuan** [Microsoft/vscode#20847]
VSCode version: 1.9.1
Language: Chinese Simplified

Key | Text
---|---
openActiveFileContainer | 打开活动文件所在的文件夹
openFileToCopy | 请先打开文件，再复制其路径
openFileToReveal | 请先打开文件，再显示它
openFileToShow | 请先打开文件，再在新窗口中打开它
revealActiveFileInMac | 在 Finder 中显示活动文件
revealActiveFileInWindows  | 在资源管理器中显示活动文件
revealInMac | 在 Finder 中显示
revealInWindows | 在资源管理器中显示
findInFiles | 跨文件查找
replaceInFiles | 跨文件替换

Some common words:

English | Not proper | Proper
---|---|---
preferences | 首选项 | 偏好设置
copy | 复制 | 拷贝 on Mac and 复制 on Windows
recycle bin, trash | 回收站 | 废纸篓 on Mac and 回收站 on Windows
cursor | 游标, 指标 | 光标

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
[CHS (2).xlsx](https://github.com/Microsoft/vscode/files/820880/CHS.2.xlsx)

@wangweixuan  Please, could you check if updated translations in a column "D" are correct in this context ? It is difficult to make any linguistic decision without seeing any ENU/CHS screenshots.

**Comment by lukaschal** [comment]
@wangweixuan Please, could you provide us ENU screenshots of mentioned issues ?

**Comment by wangweixuan** [comment]
I'm sorry to reply to you so late.
"Finder" should not be translated. Please replace "查找器" with "Finder". The other updated translations in the table are all correct.

**Comment by lukaschal** [comment]
Translations from excel sheet implemented except where "finder" occurs in a source. Waiting for linguistic on these last two issues.

**Comment by lukaschal** [comment]
Fixed as suggested.

SRC: Reveal in Finder      
TGT: 在查找器中显示
NEW: 在 Finder 中显示
 
SRC: Reveal Active File in Finder 
TGT: 在查找器中显示活动文件
NEW: 在 Finder 中显示活动文件
