### ISSUE TITLE
Test: Open detected link URI resolving and standardized formatting

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#208457]
Refs: #206260

- [x] windows @ulugbekna
- [ ] anyOS @lramos15

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208457%0A%0A&assignees=Tyriar)

---

The terminal can detect many different formats of links, here is most of the file links:

https://github.com/microsoft/vscode/blob/2cb0fa3f27a50782f71c28006b81a142e4d85774/src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkParsing.ts#L75-L119

The `Terminal: Open Detected Link` command (ctrl/cmd+shift+o) allows quickly navigating to links within the terminal's buffer. Previously it was difficult to determine exactly where the link was, what the line/col was and duplicates would be shown as well. We will now disambiguate the file's resolved folder name as well as show col/line ranges in a consistent format, regardless of what format was used in the actual link:

![image](https://github.com/microsoft/vscode/assets/2193314/0f72c1bf-9f1d-43d0-a624-9eea07f19799)

Shell integration must be activated to support directory detection. Please test various link formats from above, in various working directories in the terminal and try break it!

**Comment by ulugbekna** [comment]
very cool!
