### ISSUE TITLE
Test automatic port forwarding for ports in URL query

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#208428]
Refs: https://github.com/microsoft/vscode/issues/203869

- [x] dev container @anthonykim1
- [x] dev container @benibenj

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208428%0A%0A&assignees=alexr00)

---

General Setup
- Connect to your remote
- Set `"remote.autoForwardPorts": false`
- Remove all forwarded ports that you already have for simpler testing
- Start a server on your remote, then echo a URL with a `localhost` redirect to the terminal. ex: `http://0.0.0.0:3005?redirect_uri=http%3A%2F%2Flocalhost%3A3000`. See detailed setup for an easy way to do this.

Detailed setup
- You can use the vscode-remote-try-node sample to get started quicky (command: Dev Containers: Try a Dev Container Sample...)
- Update server.js to contain the following:
```
const express = require('express');

// Constants
const PORT = 3000;
const HOST = '0.0.0.0';

function createServer(port) {
    const app = express();
    app.get('/', (req, res) => {
        res.send('Hello remote world!\n');
    });

    app.listen(port, HOST);
}

createServer(PORT);
const port2 = PORT + 5;
createServer(port2);
console.log(`Running on http://${HOST}:${port2}?redirect_uri=http%3A%2F%2Flocalhost%3A${PORT}`);
```
- `npm run start`
- Click on the URL that gets logged to the terminal

Verify
- That you see both ports get forwarded in the Ports view

**Comment by anthonykim1** [comment]
<img width="1127" alt="Screenshot 2024-03-25 at 9 17 53 AM" src="https://github.com/microsoft/vscode/assets/62267334/6330ea2a-60b7-418c-82ec-ce6b04683602">
Looks correct to me, but let me know if I'm missing anything! Nice work.

**Comment by alexr00** [comment]
Looks correct, thankn you for testing!
