### ISSUE TITLE
Lost all my work

### ISSUE THREAD

**Issue by fuzzyfall** [microsoft/vscode#208480]
Type: <b>Bug</b>

I was using visual studio code as a place to store data for a game i intend to make. i had so many words and paragraphs of story and im very good with saving. Today i opened VSC and non of my work could be loaded. it would pop up an error code telling me "path not found" or "path doesnt exist."
I am heartbroken about losing my work I hope it can be recovered.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700F (20 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.11GB free)|
|Process Argv|--crash-reporter-id 9a57474e-c824-49c2-a5e8-cfcb5009cb8d --crash-reporter-id 9a57474e-c824-49c2-a5e8-cfcb5009cb8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30998029
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonaic:30996667
dsvsc021:30996838

```

</details>

**Comment by andreamah** [comment]
Do you know where you saved your data? VS Code should explicitly ask you where you want to save things, or if you opened up a folder, it should be there. If you can't navigate to it using the windows file explorer, VS Code probably can't access it either.

**Comment by fuzzyfall** [comment]
I found where the data and everything else was what I believe happened was
that there was a glitch that removed all my files in my documents tab for
my pc somewhere else I did a simple search in the file picker and found
everything not just vs code but even like my steam game apps and blender
models I don’t know what happened but I still have everything it just moved
places for some reason
