### ISSUE TITLE
Variables view does not show custom hover

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#208429]
![image](https://github.com/microsoft/vscode/assets/900690/1c2f38b3-b66f-484e-9c4c-06dc82427fb7)

//cc @benibenj

**Comment by benibenj** [comment]
You can use the `setupCustomHover` function on the HTMLElement to setup the hover. You will need to provide a hover delegate. If you do not require any special behaviour you can call `getDefaultHoverDelegate('mouse')` to get the default hover delegate.

**Comment by roblourens** [comment]
Should be April, right?
