### ISSUE TITLE
Feature Request: Support for private extensions

### ISSUE THREAD

**Issue by gfr2003** [microsoft/vscode#208445]
I would like there to be a feature where it is possible to download private extensions for the development environment in Visual Studio Code, it would help tech companies to improve resources privately for their developers in the company

**Comment by RedCMD** [comment]
you can manually send the `.vsix` file

**Comment by gjsjohnmurray** [comment]
The upcoming feature covered by the #208184 testplan may be relevant.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/21839
