### ISSUE TITLE
File path of the added breakpoint  changed when I debug

### ISSUE THREAD

**Issue by zhoug2020** [microsoft/vscode#208491]
Type: <b>Bug</b>

I used msbuild debug my application. the launch json file is 
 {   "version": "0.2.0",
    "configurations": [  
    {
        "name": "(Windows) Launch qite.exe",
        "type": "cppvsdbg",
        "request": "launch",
        "program": "${workspaceFolder}/qite/config/lib/qite.exe",
        "args": [],
        "stopAtEntry":  false,
        "cwd": "${workspaceFolder}/qite/config",
        "environment": [],
            "console":"internalConsole",
        //"preLaunchTask": "build all",
        "internalConsoleOptions" : "openOnSessionStart",
    }
    ] }
when i run debug, and added breakpoint, the file path with breakpoints has been changed, and assert me that the file is not found.
how to fix it? 

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (15.60GB free)|
|Process Argv|--crash-reporter-id ec17f37d-327d-49d7-bc14-29fe933bbe0e|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
codegeex|AMi|2.7.1
vscode-language-pack-zh-hans|MS-|1.87.2024031309
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.14
java|red|1.28.1
shader|sle|1.1.5
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.56.2
vscode-java-dependency|vsc|0.23.5
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30998030
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30993540
dsvsc020:30976470
pythonait:30996668
dsvsc021:30996838

```

</details>

**Comment by roblourens** [comment]
> the file path with breakpoints has been changed

Not sure I understand, please give more details

**Comment by zhoug2020** [comment]
thank you for your reply.&nbsp; i will give more details 

1. first I added a breakppoint , the file path is " D:\code\VP\21mmMaster_NEW\location\src\location_manager.cpp

2, then I pressed F5, to start debug.
I found the file path was changed to "d:\vp\vp_project\21mm\21mmaster\location\src\location_manager.cpp
the path does not exists , I don't know how it was produced。 





the launch json is as follow:


{
&nbsp; &nbsp; "version": "0.2.0",&nbsp; &nbsp; "configurations": [ &nbsp;
&nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; "name": "(Windows) Launch qite.exe",
&nbsp; &nbsp; &nbsp; &nbsp; "type":"cppvsdbg",
&nbsp; &nbsp; &nbsp; &nbsp; "request": "launch",
&nbsp; &nbsp; &nbsp; &nbsp; "program": "${workspaceFolder}/qite/config/lib/qite.exe",
&nbsp; &nbsp; &nbsp; &nbsp; "args": [],
&nbsp; &nbsp; &nbsp; &nbsp; "stopAtEntry": &nbsp;false,
&nbsp; &nbsp; &nbsp; &nbsp; "cwd": "${workspaceFolder}/qite/config/",
&nbsp; &nbsp; &nbsp; &nbsp; "environment": [],
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "console":"internalConsole",

&nbsp; &nbsp; &nbsp; &nbsp; //"preLaunchTask": "build all",
&nbsp; &nbsp; &nbsp; &nbsp; "internalConsoleOptions" : "openOnSessionStart",
&nbsp; &nbsp; }
&nbsp; &nbsp; ]
}



the workspaceFolder is "D:\code\VP\21mmMaster_NEW" 



Expect your response.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rob ***@***.***&gt;; 
发送时间: 2024年3月31日(星期天) 上午8:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/vscode] File path of the added breakpoint  changed when I debug (Issue #208491)














  
the file path with breakpoints has been changed
  
Not sure I understand, please give more details

**Comment by roblourens** [comment]
Please file this on the extension for the C++ debug extension, thanks
