### ISSUE TITLE
Line breaks in HTML attributes break Format Document command

### ISSUE THREAD

**Issue by cynicaloptimist** [Microsoft/vscode#20844]
Line breaks in HTML attributes break Format Document command

- VSCode Version:
Version 1.9.1
Commit f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
Date 2017-02-09T00:26:45.394Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
- OS Version: Windows 10 V1607

Steps to Reproduce:

1. Create a new document
2. Save as repro.html
3. Insert the following code:
```
<html>

<body>
    <div data-bind="component: {
        
    }">
    </div>
</body>

</html>
```
4. Press Alt+Shift+F to Format Document

Indentation for closing div is wrong.

Thanks!

**Comment by aeschli** [comment]
Fixed by updating the formatter.

**Comment by cynicaloptimist** [comment]
Thanks for the quick fix @aeschli!
