### ISSUE TITLE
Feature request: Incremental / emacs style search/find

### ISSUE THREAD

**Issue by shammabeth** [Microsoft/vscode#20842]
Feature request:

Need to have incremental/Emacs style search.
When activated, it allows you to type in search term and on the fly searches through current document as you type. At any point reactivating it via key binding should skip to the next occurrence. Also have a incremental prev search key binding that goes the prev occurrence.

**Comment by Bill-Stewart** [comment]
Have you tried https://marketplace.visualstudio.com/items?itemName=siegebell.incremental-search ?

**Comment by shammabeth** [comment]
Thanks. The extension works.
