### ISSUE TITLE
The window terminated unexpectedly (reason: 'crashed' code: '-1073741819') 

### ISSUE THREAD

**Issue by thisiswhereitype** [microsoft/vscode#208494]
Type: <b>Bug</b>

Open Extensions tab and a dialogue opens which reads:
`The window terminated unexpectedly (reason: 'crashed' code: '-1073741819') `

[Dump.zip](https://github.com/microsoft/vscode/files/14732979/Dump.zip)

2024/04/30 - NB: With extensions enabled crash occurs shortly after start but I haven't provided the reproduction here.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (10.24GB free)|
|Process Argv|--disable-extensions --crash-reporter-id a3899707-306e-4780-be26-eb47b1ee921e|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30998029
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:30996668
dsvsc021:30996838

```

</details>

**Comment by thisiswhereitype** [comment]
I concluded at somepoint the crash occurs after opening the extensions tab.

**Comment by wangwenqingqq** [comment]
I also have this situation. If I solve it successfully, I will come back to share

**Comment by wangwenqingqq** [comment]
Maybe this can help you. https://stackoverflow.com/questions/76703203/the-window-terminated-unexpectedly-reason-crashed-code-135

**Comment by wangwenqingqq** [comment]
Thanks for your suggestions, I completely uninstalled and reinstalled VSCode, and later found that it can be used normally, and the extension can also be operated graphically。I hope it can be helpful to you。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月24日(星期四) 下午3:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode] The window terminated unexpectedly (reason: 'crashed' code: '-1073741819')  (Issue #208494)





 
Thanks for the suggestions, I have completed these at points. I use a system install but it claims that the files have been edited, this persisted until a few versions ago at the time of writing.
 
My workaround is to use the command line to update all extensions, then don't open the Extensions view. That way I can work as normal.

**Comment by thisiswhereitype** [comment]
I now get various issues, including this but also UI crashing and processes not ending on unspecified crashing. 

I think my GPU has been the cause is now more obviously broken as many other apps are unstable when using GPU such as Steam and Firefox.

**Comment by pjninnim** [comment]
I'm experiencing this same error, but for me it occurs randomly:
![Image](https://github.com/user-attachments/assets/5753f28b-03bf-483d-89de-0a56cdcce0c7)

Have you had any luck in resolving this? All drivers etc are up to date.

**Comment by thisiswhereitype** [comment]
> Have you had any luck in resolving this? All drivers etc are up to date.

No I didn't check a different GPU would help. I believe this error is generic from Electron - probably you should submit a crash dump into a new issue.
