### ISSUE TITLE
Can not fold function with """string""" 

### ISSUE THREAD

**Issue by DmitrySokolov** [microsoft/vscode#208402]
Type: <b>Bug</b>

Folding Groovy function
```groovy
def fn1 ()
{
    def a = """\
qwert\
asdffg\
"""
    def b = 1
}
```

Expected
```groovy
def fn1 ()
{...
}
```

Actual
```groovy
def fn1 ()
{...
qwert\
asdffg\
"""
    def b = 1
}
```

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (43.40GB free)|
|Process Argv|-r D:\\ITC\\jenkins.code-workspace --crash-reporter-id ee5daf53-921f-4db9-9a5d-ec3244a157c7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
doxdocgen|csc|1.4.0
xml|Dot|2.5.1
vscode-guid|hea|1.9.0
jenkinsfile-support|ivo|1.1.0
jenkins-pipeline-linter-connector|jan|1.2.0
plantuml|jeb|2.17.5
better-cpp-syntax|jef|1.17.2
restructuredtext|lex|189.3.0
camelcasenavigation|map|1.1.5
hg|mrc|1.9.0
debugpy|ms-|2024.2.0
isort|ms-|2023.10.1
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.13
powershell|ms-|2024.0.0
vscode-speech|ms-|0.6.0
vsliveshare|ms-|1.0.5918
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.34.0
vscode-commons|red|0.0.6
vscode-xml|red|0.26.1
svelte-vscode|sve|108.3.3
simple-rst|tro|1.5.4
cmake|twx|0.0.17
errorlens|use|3.16.0
vscode-icons|vsc|12.7.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30992800
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30991134
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
7ghi1836:30988842

```

</details>

**Comment by aeschli** [comment]
Out of the box, VS Code only has indentation based folding for Groovy.
To get syntax aware folding, you need a language extension.

I had a quick look in the extension marketplace, and there are a few groovy extension, but none of them seem to provide folding ranges. I suggest to write feature requests there.
