### ISSUE TITLE
Test: Quick Search Preview Editors

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#208477]
Refs https://github.com/microsoft/vscode/issues/204853, https://github.com/microsoft/vscode/issues/205136

- [x] macOS @lszomoru
- [x] linux @roblourens
- [x] windows @cwebster-99

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208477%0A%0A&assignees=andreamah)

---
## Set up
It might help to bind something like `ctrl+shift+f` to the quick search by binding it to `workbench.action.experimental.quickTextSearch`. This way, it's easier to pop up quick search. 

## Testing

https://github.com/microsoft/vscode/assets/31675041/35c213dd-3caa-4533-8ce3-d461a6e45055

This iteration, we introduced a new editor type to support a more 'temporary' editor. This is used by quick search, so editors that it opens will omit history and be preview editors regardless of user settings. Preview editors are editors that have their tab title in italics like so:

<img alt="image" src="https://github.com/microsoft/vscode/assets/31675041/a80db4c1-deab-4c06-aff1-edd2711ac12b">

Try the following with quick search:

1. Ensure that you have `workbench.editor.enablePreview` enabled and `workbench.quickOpen.closeOnFocusLost` enabled. 
2. From an editor, open quick search and preview a few results in different files. If you press `escape` after browsing a file other than the one that you were originally on, you should go back to where you previously were in the editor, with any preview editors closed. 
3. Disable `workbench.editor.enablePreview` and try step 2 again. The same should happen at the end, although the editors that open up look like non-preview editors.
4. Repeat steps 1-3, but click on the editor to exit the quickpick. The editor that you clicked on should still be there, and this should close the picker.
5. Now, disable `workbench.quickOpen.closeOnFocusLost` and disable `workbench.editor.enablePreview`.
6. Use quick search and browse a few files. Navigate to a file other than the file that you were originally on.
7. Ensure that, if you click into the editor (which would otherwise close the file, but since `closeOnFocusLost` is disabled, the picker stays open), it actually doesn't close that editor when you move onto a new file. When you finally press escape, you should notice that any files that you clicked into are actually still open.

**Comment by lszomoru** [comment]
> 2. From an editor, open quick search and preview a few results in different files. If you press escape after browsing a file other than the one that you were originally on, you should go back to where you previously were in the editor, with any preview editors closed.
> 3. Disable workbench.editor.enablePreview and try step 2 again. The same should happen at the end, although the editors that open up look like non-preview editors.

Could you please clarify this? I have disabled editor preview yet in step#3, when I navigate across the various search hits, the opened editor still has an italic name - looks like a preview editor. Is that a bug or am I misunderstanding the test steps? Thanks!

**Comment by roblourens** [comment]
I also don't understand the `enablePreview` distinction, but in general everything looks great!
