### ISSUE TITLE
Inline chat does not respect context-key-disabled intents

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#208469]
1. Have an intent enabled behind a context key, and disabled by default
2. It's correctly hidden in panel chat but not inline chat 🐛

**Comment by connor4312** [comment]
Oop, realized I assigned Rob for some reason.

We should fix this before release since we're feature-flagging one of our intents in copilot, I'll do so sometime tomorrow unless you don't get to it before then

**Comment by jrieken** [comment]
Content keys for inline chat slash command don't exist. It's all dynamic for them and you shouldn't return them when preparing the session (see `prepareInteractiveEditorSession`)

**Comment by connor4312** [comment]
Ah, I see. It's kind of strange there are two different worlds for them.
