### ISSUE TITLE
Test: Terminal word links pulling additional surrounding context

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#208464]
Refs: #190847

- [x] windows @ulugbekna
- [ ] anyOS @meganrogge

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208464%0A%0A&assignees=Tyriar)

---

The terminal supports a [few different types of links](https://code.visualstudio.com/docs/terminal/basics#_links) with the fallback being word/search links. This is when none of the other links can be resolved for that section of a line, for example we will not do a file exists check for arbitrary words without additional indicators to avoid hitting the FS too much. When the link is activated the workspace will be searched for a match, if a single match exists it will open the link, if not it will open go to file with a query filled in. A guaranteed way to know if a link is a word link is that the underline does not show up unless you hold ctrl/cmd.

One issue with these links is that they are defined by the `terminal.integrated.wordSeparators` setting, which means that all the link smarts of validated file links that pulls line/col information from links is not used. This new feature does exactly that; when the link is activated, the surrounding content of the link will be searched to find a matching column/line for the link.

Here is an example of this new feature in action:

![image](https://github.com/microsoft/vscode/assets/2193314/2fa99f2f-939d-4e34-8665-b7df9467e910)

Notice how the word link is just `terminalEnvironment`, but the quick pick opens with `:35` because a link suffix `": line 35` was detected.

To test this, try echoing various word links to the terminal in the below link formats and check if the line/column context is being included correctly:

https://github.com/microsoft/vscode/blob/2cb0fa3f27a50782f71c28006b81a142e4d85774/src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkParsing.ts#L64-L120

**Comment by meganrogge** [comment]
Works great 👏
