### ISSUE TITLE
Test: Issue Report minimum description length 

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#208466]
refs https://github.com/microsoft/vscode/issues/207831

- [x] anyOS @bpasero 
- [x] anyOS @luabud 

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208466%0A%0A&assignees=justschen)

---

### Background
For native issue reporting, we expect descriptions that are helpful and useful when triaging. This ensures that we don't get spam or lazy issue reports.

### Steps

1. From the command palette, `Help: Report Issue...`
2. Fill out the  form on any source or extension.
3. Try submitting with short amounts of text in the description (less than 10 characters)
4. Try again with more text in the description.

### Things to verify

- that you get an error preventing you from submitting.
- that when submitting an empty description, there is a different error
- that when reaching the correct length of description, the error disappears.

**Comment by luabud** [comment]
Worked great!
