### ISSUE TITLE
Test: Automatic rescaling of overlapping glyphs in the terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#208456]
Refs: #206342

- [x] macOS @alexdima
- [x] linux @justschen
- [x] windows @mjbvz

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208456%0A%0A&assignees=Tyriar)

---

An opt-in feature has been added to automatically rescale glyphs in the terminal that may overlap with the following character in order to aid in GB18030 compliance. Set `"terminal.integrated.rescaleOverlappingGlyphs": true` to enable the feature (it will likely become the default next month). Do some exploratory testing with various characters and let me know where:

- It rescales when it shouldn't 
- It doesn't rescale when it should
- Some other rendering issue

The rules for rescaling as of writing this test item are:

- Is single cell width
- Glyph exceeds cell bounds, add 50% to avoid hurting readability by rescaling glyphs that barely overlap
- Never rescale ascii
- Never rescale emoji
- Never rescale powerline or nerd fonts

https://github.com/xtermjs/xterm.js/blob/53bc9f8442994d75ad522a117a0c2ffd78e50781/src/browser/renderer/shared/RendererUtils.ts#L47-L61

**Comment by justschen** [comment]
@Tyriar just double checking if you intended to have it turned on, but I believe this is already enabled true by default - since it's an opt-in feature, I thought it would be default false :0

**Comment by Tyriar** [comment]
@justschen I think I made that change on Friday, you might have been on the older version of Insiders?

https://github.com/microsoft/vscode/blob/738438cfd8474eea16440fc1a064c2d879f7e54a/src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts#L563-L567

**Comment by alexdima** [comment]
:+1: works for me

<img width="316" alt="image" src="https://github.com/microsoft/vscode/assets/5047891/b89c0abe-829e-4063-8bb9-8063847aafd2">
