### ISSUE TITLE
[frature] expose api to run single file or project

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#20843]
- VSCode Version: Code - Insiders 1.10.0-insider (50f8848e44029ffabf0727de49cd18ae4069b4fe, 2017-02-17T13:43:37.461Z)
- OS Version: Darwin x64 16.5.0

Now vscode can easily debug project, or single file(with extension support), but for a single file or project, there looks no way to run it. In sometimes run is more useful than debug. 
A suggestion, expose `CMD+r` to run a single file use language default build tool, for python , user can set use python2 or python3 and add some command line variables through config file, for go, default use `go run ${currentFile}` also with more command line variables defined in config file.

**Comment by rozzzly** [comment]
Checkout my extension, [`vscode-prompt-debug`](https://marketplace.visualstudio.com/items?itemName=rozzzly-dev.vscode-prompt-debug). I made it for debug sessions, but it should work for normal run configurations as well (currently untested; afk at the moment. Let me know if you try and it works/doesn't)

You should just be able to include `${command.prompt-debug.resolve}` in your launch configuration.

**Comment by isidorn** [comment]
Yes this can be achieved by extensions as @rozzzly points out.

The api is already available, more about that can be found here https://github.com/Microsoft/vscode/issues/285 and https://github.com/Microsoft/vscode/issues/6248

**Comment by leaxoy** [comment]
It's run single file or project, not debug.
With debug, I should set `bp` in some lines, but with run, we can run it and see result immediately without debug steps.

**Comment by isidorn** [comment]
It is still possible via an extension more details https://github.com/Microsoft/vscode/issues/2780
In short 'noDebug': true should just be added to the launch configuration

**Comment by rozzzly** [comment]
@leaxoy

> I made it for debug sessions, but it should work for **normal run configurations** as well 

> You should just be able to include `${command.prompt-debug.resolve}` in your launch configuration.
