### ISSUE TITLE
[git] Add extension api event for when a file is commit

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#20845]
- VSCode Version: `1.10.0-insider` 50f8848e44029ffabf0727de49cd18ae4069b4fe
- OS Version: macOS Sierra `10.12.3 (16D32)`

I would love to be able to listen for an event for when the a file in an open editor has been committed. Currently we have api events for when a document changes and is saved, but nothing for when a document is commit.

Specifically this would help out GitLens, to where I could avoid issues where the blame continues to show "Uncommitted changes" because I haven't detected that the file has been committed.

**Comment by joaomoreno** [comment]
You should listen to file system events on the `.git` folder because the user might actually commit the file outside of VS Code.

**Comment by eamodio** [comment]
@joaomoreno that is an excellent suggestion! Thanks so much.

**Comment by eamodio** [comment]
@joaomoreno but at the same time. Vscode must already be doing this to update it's tracking. And with more scm's being added an abstract event would seem to me to be very valuable

**Comment by joaomoreno** [comment]
Code is listening. But it won't tell you that a file has been committed. At best, it can tell you that *something* has changed. Which is exactly what you can do with FS events.

**Comment by eamodio** [comment]
True, but when there are multiple different SCM providers, it allows an extension to not have to know about the details of each one (and vscode will already need to know).

**Comment by joaomoreno** [comment]
It won't actually know. The SCM support is more abstract than that, since some SCM systems don't even have the _commit_ concept;.

**Comment by eamodio** [comment]
Sorry, I was conflating things. I just meant a general SCM changed type of event (with optional other details if possible - but would be specific to the SCM)
