### ISSUE TITLE
rss feed is broken

### ISSUE THREAD

**Issue by lalku** [microsoft/vscode#208417]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Go to https://code.visualstudio.com/updates
2. Select the rss feed subscribe link
![image](https://github.com/microsoft/vscode/assets/45947468/c7d625fc-8e57-4b19-808c-2663bf679510)
3. The following is displayed
![image](https://github.com/microsoft/vscode/assets/45947468/7510135c-94cb-4695-8fcc-864d9900e93d)

**Comment by rzhao271** [comment]
Confirmed that https://code.visualstudio.com/feed.xml is unavailable.

**Comment by rzhao271** [comment]
Fixed. Thanks for the report!
