### ISSUE TITLE
solution explorer

### ISSUE THREAD

**Issue by WILTON-DEV** [microsoft/vscode#208493]
Type: <b>Bug</b>

i have tried deleting and reinstalling this application but solution explorer is not showing

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:14:59.643Z)
OS version: Linux x64 6.2.0-39-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     T5750  @ 2.00GHz (2 x 1994)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|1.88GB (0.38GB free)|
|Process Argv|--unity-launch --crash-reporter-id b476944d-0c16-4432-ab27-c525acdd5653|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.10.5
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.9.0
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
vscode-edge-devtools|ms-|2.1.5
live-server|ms-|0.4.13
LiveServer|rit|5.7.9
lorem-ipsum|Tyr|1.3.1
vscode-icons|vsc|12.7.0
vim|vsc|1.27.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30998029
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonaic:30996667
jchc7451:30973076
7ghi1836:30988842
dsvsc021:30996838

```

</details>

**Comment by gjsjohnmurray** [comment]
Out of the box VS Code doesn't have anything called Solution Explorer, so perhaps you need to install an extension.
