### ISSUE TITLE
Intelli Sense / Suggestions inaccuracy, ordering

### ISSUE THREAD

**Issue by pavelloz** [microsoft/vscode#208401]
I know there's been an issue opened in 2016 about intelli sense ordering: https://github.com/Microsoft/vscode/issues/17796 - but, unless im doing something wrong, the issue is even worse now than 8 years ago.

It got so bad i had to disable all suggestions because they were distracting and almost never helpful.

Does this issue occur when all extensions are disabled?: Yes

Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:57.520Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.4.0

Steps to Reproduce:

1. Install "aws-lambda" package
2. Create new typescript file
3. Paste following code:
 
```js
import { APIGatewayProxyEvent } from "aws-lambda";
function main(event: APIGatewayProxyEvent) {
}
```

4. Try to get some useful suggestions when typing API in the function body.

This is the result in my machine (defaults for suggestions at this moment):

<img width="535" alt="image" src="https://github.com/microsoft/vscode/assets/546845/472f0e76-a8b9-4a6e-bc2a-2d7d1a631645">

I have no idea how this is acceptable, to get suggestions about some packages somewhere, and not get LITERAL suggestion from variable defined in the same file, same letter case, 2 lines above. I find it terrible, terrible experience and i dont know what to do. Turn it off, then VScode is just worse Sublime. Turn it on, it slows me down instead of helping.

**Comment by jrieken** [comment]
Simple repro steps

```
let APIGatewayProxyEvent: any;  
let Api: any;

function main(event: APIGatewayProxyEvent) {
  Api|
}
``

**Comment by jrieken** [comment]
> suggestion from variable defined in the same file, same letter case, 2 lines above.

I assume you mean `APIGatewayProxyEvent`, right? What is type is this? An interface/class/etc or a variable/const etc?

**Comment by jrieken** [comment]
nvm - it looks like a type definition: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/670cb9db970c50afff7bdbe1c01f417273584667/types/aws-lambda/trigger/api-gateway-proxy.d.ts#L72

In your sample you are asking for suggestions at a location that does not allow for types and therefore the type isn't suggested. Try something like `let a:Api` etc
