### ISSUE TITLE
Open "included file" in php.

### ISSUE THREAD

**Issue by sirajalam049** [Microsoft/vscode#20849]
- VSCode Version: 1.9.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. In PHP, files included should be visible as different tabs as it shows in **Adobe Dreamweaver**. It is the only reason I use Dreamweaver editor.
2. Auto closing tags in HTML. The editor should know the last opened tag, so it should auto put a closing tag on just writing </. This is also a feature of **Adobe Dreamweaver**

**Comment by roblourens** [comment]
Sorry, I actually don't understand the request for PHP. Please reply with details if it's still needed.

Auto closing tags in HTML is actually a newly supported feature though.
