### ISSUE TITLE
Ctrl+A in notebook output selects all output temporarily and then de-selects them

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#208555]
https://github.com/microsoft/vscode/assets/876920/026e5307-1041-4e1d-b3d5-5b8c076a2064

As seen in the recording above, all outputs are selected briefly when pressing cmd/ctrl+a, and then they are de-selected. I wonder if we can improve this otherwise users see them flashing. Note that the markdown previews are good.

**Comment by DonJayamanne** [comment]
>  and then they are de-selected

Looks like your are clicking outside the notebook
The cell and output selection colours also changed, Not just output Selection

What or where in vscode are you clicking after selecting all?

**Comment by DonJayamanne** [comment]
Aah, I see the problem (outputs from previous cells are also selected).
