### ISSUE TITLE
Change all occurrences works for first 1000 entries only

### ISSUE THREAD

**Issue by agauniyal** [Microsoft/vscode#20854]
- VSCode Version: 1.9
- OS Version: Linux

Steps to Reproduce:

1. Open a file with same word present multiple times( > 2000).
2. Select some part of word and right click -> change all occurrences. Only selects first 1000 entries.

**Comment by Bill-Stewart** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/5887 ?

**Comment by alexandrudima** [comment]
Yes, thanks @Bill-Stewart . Let's track in #5887
