### ISSUE TITLE
Inline Chat Widget: Icons do not align vertically

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#208567]
Testing #208414

Would be great if the feedback action buttons would vertically align with close/more action buttons

<img width="143" alt="image" src="https://github.com/microsoft/vscode/assets/44439583/f061fbbd-5d73-4fbb-b70c-554cb70d7b8d">

**Comment by jrieken** [comment]
This has changed quite a bit but buttons are now aligned with the input box

![Image](https://github.com/user-attachments/assets/a270b00c-eb89-4f93-ac67-7aec865622e1)
