### ISSUE TITLE
Python debugger stuck at plotting

### ISSUE THREAD

**Issue by Bharad-T** [microsoft/vscode#208575]
![Screenshot 2024-03-25 at 10 03 21](https://github.com/microsoft/vscode/assets/156667754/11028397-3a3d-492f-88c1-1fdf6fbe343b)
Type: <b>Bug</b>

The python debugger keeps getting stuck at matplotlib commands.
It works fine till i issue a plot command. After the plot command, it opens the plot window and does not move forward when I click on the step option.

VS Code version: Code 1.87.2 (Universal) (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 5, 9|
|Memory (System)|18.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id ea61fd97-9a5c-4c57-9736-5277457b53bc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-gmsh|Ber|0.1.2
githistory|don|0.6.20
gitlens|eam|14.9.0
vsc-python-indent|Kev|1.18.0
vscode-latex|mat|1.3.0
git-graph|mhu|1.30.0
debugpy|ms-|2024.3.10731010
python|ms-|2024.3.10791010
vscode-pylance|ms-|2024.3.1
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
vsliveshare|ms-|1.0.5918
code-spell-checker|str|3.0.1
pdf|tom|1.2.2
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30998030
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonaic:30996667
dsvsc021:30996838

```

</details>

**Comment by atvasilopoulos** [comment]
To add to @Bharad-T 's issue, I encounter the same bug when I execute a plot command from the debug console (e.g., `plt.plot(X, Y)`). The plotting window appears as in the original post and the program hangs, requiring restart of the debugging session (pressing stop) or even complete restart of VScode (unresponsive stop). 

I find that if I execute `plt.plot(X, Y); plt.savefig("temp.png"); plt.close()` it works fine though. It's only when you don't close the figure that the issue arises (as in the original post as well)

**Comment by atvasilopoulos** [comment]
Bug seems to be fixed on Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c)

**Comment by Bharad-T** [comment]
I updated to Code 1.88.0, but still have the same issue.

**Comment by roblourens** [comment]
Please file on the python debug extension, thanks
