### ISSUE TITLE
How can I disable this black line?

### ISSUE THREAD

**Issue by HeroFluxx** [microsoft/vscode#208534]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.87.2
- OS Version: Windows 11 Build 22631.3266

Steps to Reproduce:

1. Open any file
2. Scroll down 
![16_44_36](https://github.com/microsoft/vscode/assets/28282044/0add40f9-d0f6-4ee5-8027-e7f387be2eec)

**Comment by ArturoDent** [comment]
That looks like the border and shadow below your editor sticky scroll.  There are these `colorCustomizations`:

```json
    "editorStickyScroll.border": "#7C997C",
    "editorStickyScroll.shadow": "#ff0000",
```

Use six digits for opacity or you could just disable the sticky scroll in the settings if you want.

**Comment by HeroFluxx** [comment]
Thanks!
