### ISSUE TITLE
Lost an unsaved file

### ISSUE THREAD

**Issue by bisma-aa** [microsoft/vscode#208513]
Type: <b>Bug</b>

I was working on a file which was unsaved, i tried saving the file on my desktop as a ipynb file and when i pressed save, VSCODE said it failed to save , so either retry or discard it , i accidentally discarded and now the file is no where to be found 

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.73GB (11.80GB free)|
|Process Argv|--crash-reporter-id 98c54525-7ad1-460a-b902-20bb6165b803|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
project-manager|ale|12.7.0
blackbox|Bla|1.2.80
gitignore|cod|0.9.0
codium|Cod|0.7.54
arm|dan|1.7.4
dscodegpt|Dan|3.2.3
git-extension-pack|don|0.1.3
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.9.0
vscode-mysql|for|0.5.0
copilot|Git|1.175.0
copilot-chat|Git|0.13.1
better-cpp-syntax|jef|1.17.2
black-py|mik|1.0.3
vscode-docker|ms-|1.29.0
debugpy|ms-|2024.2.0
isort|ms-|2023.10.1
python|ms-|2024.2.1
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.8
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
prolog|reb|0.0.4
LiveServer|rit|5.7.9
umlet|the|15.1.0
cmake|twx|0.0.17
json|Zai|2.0.2
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30992801
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
jchc7451:30973076
gee8j676:30988843

```

</details>

**Comment by kk107k** [comment]
have you checked if it is in your closet

**Comment by bisma-aa** [comment]
……

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rebornix** [comment]
Sorry to hear that you lost files, You can use the timeline view to find the history versions of your notebook.
