### ISSUE TITLE
Visualize full-width space character (render whitespace in selection)

### ISSUE THREAD

**Issue by kuyur** [microsoft/vscode#2085]
Hope to support visualizing full-width space character with "○".

**Comment by weinand** [comment]
@kuyur I assume you refer to the "editor.renderWhitespace" setting which shows tab characters but does not show spaces? What do your mean with "full-width space character"?

**Comment by kuyur** [comment]
full-width space is used in Japanese and Chinese.  for example, `　`, you can select the text and will see the its length is double of that of normal Latin character.

**Comment by glen-84** [comment]
Related to #1477.

**Comment by liuliangsir** [comment]
+1
Because i encountered syntax error in js file which contain some full-width character
Sadly, vscode seem not to find out full-width character

**Comment by kuyur** [comment]
I hope that the full-width space character can be always rendered, not only when it is selected.
