### ISSUE TITLE
ESLint and .vscode/extensions is tricky to configure

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#208581]
Testing #208184

Looks like eslint ignores everything inside dot-prefixed folders. I failed to configure this accordingly (tried everything recommended here https://stackoverflow.com/questions/57947585/eslint-warning-file-ignored-by-default-use-a-negated-ignore-pattern). This might become an issue when doing developing a workspace extension more seriously

**Comment by jrieken** [comment]
fyi @dbaeumer

**Comment by sandy081** [comment]
@dbaeumer Do you have any recommendations how to configure ESLint in this case?

**Comment by dbaeumer** [comment]
I will have a look.

**Comment by dbaeumer** [comment]
I am a little lost as well. Tried putting 

```
!.vscode/extensions/vscode-selfhost-test-provider/src/**/*.ts
```

into the `.eslintignore` file. Running

```
./node_modules/.bin/eslint .vscode/extensions/vscode-selfhost-test-provider/src/metadata.ts
```

still produces

![Image](https://github.com/microsoft/vscode/assets/1931590/dc2e0ad8-8b72-45fd-8e6a-bea087fe8e6a)

**Comment by dbaeumer** [comment]
Fixed it: https://github.com/microsoft/vscode/pull/210031
