### ISSUE TITLE
Inline Chat Widget: `Remove Request and Response` leaves a lot of "padding"

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#208570]
Testing #208414

When removing a request and response, there is a lot of empty space left afterwards.

![Code_-_Insiders_99p4Qo8GVS](https://github.com/microsoft/vscode/assets/44439583/4380883a-59a8-428d-a44d-f7e806ff8025)

**Comment by jrieken** [comment]
Seems to be missing a layout but I also wonder if this should be supported here

**Comment by jrieken** [comment]
The UI glitch will be fixed with https://github.com/microsoft/vscode/issues/208418 but the model isn't updated yet

**Comment by jrieken** [comment]
Closing this because the UI is now proper, the model-updating is part of https://github.com/microsoft/vscode/issues/208898 and that's a way bigger story
