### ISSUE TITLE
[FR] Press `Esc` to clear source control commit message

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#208519]
A reboot of https://github.com/microsoft/vscode/issues/124421, the original issue hasn't been solved in 3 YEARS!.

Since both _Search_ and _Extensions_ panel support pressing `Esc` to clear text input, I think it makes sense for the _Source Control_ panel to have this feature as well.

A GIF demonstrates what I mean:

![Demo](https://user-images.githubusercontent.com/28700378/119224578-9efb6800-bb31-11eb-89b7-e64f3425a116.gif)

**Comment by lszomoru** [comment]
@wenfangdu, as far as I can tell `Escape` does not clear the extension/search field out of the box and keybindings have to be configured for that behaviour. Could you please confirm that you have explicitly set up those keybindings? Thank you!

**Comment by wenfangdu** [comment]
@lszomoru Yes, through keybindings, but the scm input box doesn't have a command to bind to, that's the issue.

```json
  {
    "key": "escape",
    "command": "search.action.clearSearchResults",
    "when": "searchViewletFocus"
  },
  {
    "key": "escape",
    "command": "workbench.extensions.action.clearExtensionsSearchResults",
    "when": "sideBarFocus && activeViewlet == 'workbench.view.extensions'"
  }
```

**Comment by lszomoru** [comment]
Verifications steps:
* Open a folder/workspace that contains a git repository
* Make changes to one or more file
* Enter a commit message
* Press ESC and confirm that the commit message is cleared
