### ISSUE TITLE
Inline Chat Widget: `/explain` response is empty

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#208574]
Testing #208414

I find it weird that there is no response in the inline chat widget when running `/explain`. Maybe it could show something like `Responded in panel` and/or `view explanation` which when pressed reveals the response in the panel...

<img width="767" alt="image" src="https://github.com/microsoft/vscode/assets/44439583/7c736b70-40bc-4cf6-809b-592b2dbf7542">

**Comment by jrieken** [comment]
It's a bit weird but when having `/explain` the response should be shown inside the chat panel

**Comment by jrieken** [comment]
fyi @joyceerhl

**Comment by jrieken** [comment]
Pushing a fix to refer /explain to panel chat only when it is the only request in the conversation
