### ISSUE TITLE
[Enhance]Minimap enhancement with some features!

### ISSUE THREAD

**Issue by leaxoy** [microsoft/vscode#20853]
- VSCode Version: Code - Insiders 1.10.0-insider (50f8848e44029ffabf0727de49cd18ae4069b4fe, 2017-02-17T13:43:37.461Z)
- OS Version: Darwin x64 16.5.0
First, the minimap is really useful and exciting feature added recently. 
But there are some enhancements:
one: migrate minimap and scrollbar when minimap enabled, this will make the right part of editor looks simple but powerful.
two: git status in minimap. this would a good feature for people find which parts of code has changed quickly.
three:  make the gray block to identify position of a file more gray.

**Comment by varemenos** [comment]
I'd suggest to instead provide a minimap API for extensions (similar to the one that Atom has) where the extension developers can manipulate parts of the minimap (ie: marking parts of the minimap with a specific color). Atom package developers did some amazing things with the API, here are a few examples:

* highlight current line
* highlight selected word
* highlight search entries from "find and replace"
* git diff output (additions, changes, deletions)
* linter highlighting

**Comment by canada11** [comment]
+1 @varemenos for that, especially the highlight selected word. 

I love in Atom being able to double click a word and quickly seeing in the minimap all the instances of it highlighted (in the minimap) for the whole file.

**Comment by JeremyIglehart** [comment]
I really like being able to double click on a word and see every instance of this word within the file.  I really miss this from atom.

**Comment by mbedded** [comment]
I would love to add some feature-wishes :)

- Make Minimap "full height" like in Visual Studio
- Let Minimap display the full file wh
- Make this feature configurable via options/settings 
- Synchronize Minimap with scroll bar (or remove the scrollbar when Minimap is enabled)

It is annoying that the Minimap "zooms" in and the top or bottom of a file is cut of when a longer file is used. The Minimap in Visual Studio just works nice. A function like this one would be really appreciated.

Screenshot for clarification:
![visual studio code](https://user-images.githubusercontent.com/22235508/41959722-167645a4-79ee-11e8-94d2-c380314593fb.png)

**Comment by lexicalunit** [comment]
git diff highlights in the minimap are super useful.

**Comment by cyphernull** [comment]
2019 7 29; there is still no git diff highlights in minimap

**Comment by RMacfarlane** [comment]
For issue management, it's much easier if each issue is tracking a single feature request. Looking through the existing minimap feature requests, I believe all of these requests are already covered.

migrate minimap and scrollbar when minimap enabled: https://github.com/microsoft/vscode/issues/28653
git status in minimap: https://github.com/microsoft/vscode/issues/20934
highlight current line: implemented in 1.39
highlight selected word: sort of workable in 1.38, highlight word and ctrl f. feel free to open a new issue for this
highlight search entries from "find and replace": implemented in 1.38
linter highlighting: https://github.com/microsoft/vscode/issues/82291

So I will go ahead and close this issue. Please let me know if I missed anything.

**Comment by mbedded** [comment]
@RMacfarlane Thank you for referencing related tickets and features.
From my point of view my issue [see comment above](https://github.com/microsoft/vscode/issues/20853#issuecomment-400574570) is not covered yet. I updated to the newest version on Mac OS.

When i have a very long file like 100 lines with word wrap the right sidebar does not show the complete file. The content of the sidebar is still scrolling with the content. So i just see the current content and something above and below. As i mentioned before a scrollbar like Visual Studio would be nice where i see the whole content so i can switch positions by using one click only.
If you have a longer file and you want to move up and down quickly you have always to scroll or remember the line number and use "go to line".

I guess there could be people who like this feature as it is. Maybe it could be possible to change this behavior by parameter to be "visual studio alike". Ticket #21404 does not resolve the "scrolling minimap" issue.

**Comment by RMacfarlane** [comment]
@mbedded Thanks! Sorry I missed that one, I believe that's already covered by https://github.com/microsoft/vscode/issues/21849

**Comment by mbedded** [comment]
Alright. Thank you for adding the reference.

**Comment by lgpasquale** [comment]
> +1 @varemenos for that, especially the highlight selected word.
> 
> I love in Atom being able to double click a word and quickly seeing in the minimap all the instances of it highlighted (in the minimap) for the whole file.

For anyone interested this is now tracked in issue #84151
