### ISSUE TITLE
Any change to a notebook after a Move Cell operation is still recorded as a Move Cell operation.

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#208565]
Testing #208266

See gif below:

![Recording 2024-03-25 at 13 57 44](https://github.com/microsoft/vscode/assets/25044782/ef11022d-d2c3-45a4-b2ac-c2ef2d46d673)

**Comment by DonJayamanne** [comment]
Yeah, this will be challenging, 
Current design is to always collapse all new edits with the previous edit operations.
However if we stop collapsing all edits, then the only other alternative is to always display each save as `File Saved` as was done here https://github.com/microsoft/vscode/pull/208053

I.e. all operations will show up consistently as `File Saved`
Thoughts @rebornix /cc
I think that would be better than having a mix of `Move Cell`, `File Saved`, I.e. `File Saved` always is consistent and simple.
We can explore ways to make this more fine grained later,
