### ISSUE TITLE
Pressing close button inserts text

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#208585]
Testing #208409

https://github.com/microsoft/vscode/assets/1931590/58b70e05-2308-4509-911d-797144f758f8

I would have expected that the close button is like discard.

**Comment by dbaeumer** [comment]
Pressing `escape` works as expected.

**Comment by jrieken** [comment]
Yeah, it always did that. The X just means hide UI but doesn't mean undo/discard changes.

**Comment by dbaeumer** [comment]
But the hover says `Close (Escape)` so IMO it should behave like pressing the escape key.

**Comment by jrieken** [comment]
cc @benibenj

**Comment by jrieken** [comment]
Got similar feedback from @benibenj. Let's try this and let's have Close discard all changes. The keybinding is ESC _unless_ the user already made tweaks - in that case ESC is disabled.
