### ISSUE TITLE
VS Code spawn too many processes

### ISSUE THREAD

**Issue by sr229** [Microsoft/vscode#20856]
- VSCode Version: Code - Insiders 1.10.0-insider (50f8848e44029ffabf0727de49cd18ae4069b4fe, 2017-02-17T13:49:26.052Z)
- OS Version: Windows_NT ia32 10.0.14393
VS Code seems to spawn too many processes

Suspecting a Memory leak

![image](https://cloud.githubusercontent.com/assets/14976516/23093006/8c62566a-f612-11e6-893a-38f31067317a.png)

Not sure if this is normal or an issue atm

**Comment by mrmlnc** [comment]
> This is a consequence of both how vscode was designed and the fact that it's build on Chromium/Electron. The number of processes should not really matter from an end user perspective, it's the amount of work each process does and the communication between them that are important. Some more info here [#5856 (comment)](https://github.com/Microsoft/vscode/issues/5856#issuecomment-216274544)
> @Tyriar

**Comment by Tyriar** [comment]
Thanks @mrmlnc

**Comment by sr229** [comment]
ah, thanks for the explanation then
