### ISSUE TITLE
Test: Notebook Run in Section contributions

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#208545]
Refs: #207498, #205307, #205315

- [x] anyOS @benibenj 
- [x] anyOS @luabud

Complexity: 3

author: @Yoyokrazy 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23208545%0A%0A&assignees=Yoyokrazy)

--- 
## Summary:
A new action `Run in Section` has been introduced to various places within the notebook editor. The following testing is to ensure cells are being executed as expected in their various places.

## Steps to Test:

- Open a notebook with a number of different sections, organized using markdown headers. Your endgame notebook works nicely for this.
- Enable Sticky Scroll, and open the Outline View
- Test the following Run in Section contributions:
  - Context menu on the sticky scroll header
  - The toolbar on the right side of outline view entries (_you can also use this to fold ranges for the next step_)
  - Collapse a Markdown Header section ==> Use the folded cell hint run button

## Known Issues:
- Visual jumping after you fold a cell, not a clear anchor for the view to fold against. Not directly tied to run in section, but the outline toolbar.

--- 
Thanks so much for testing!

**Comment by luabud** [comment]
+1 to this [issue ](https://github.com/microsoft/vscode/issues/208643) but everything else worked as expected 😊
