### ISSUE TITLE
Custom keybinding have different priority then default keybindings

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#20855]
- VSCode Version: `1.9.1`
- OS Version: `Windows 10`

Steps to Reproduce:

Default scenario:  

Default keybinding:
`{ "key": "f11", "command": "workbench.action.toggleFullScreen" }`

1. Using default keybindings, enter debug mode and stop on a breakpoint.
2. Press `f11`
3. Debugger steps into

Custom keybinding scenario
`{ "key": "f11", "command": "workbench.action.toggleZenMode" }`  

1. Using custom keybindings, enter debug mode and stop on a breakpoint.
2. Press `f11`
3. Enter ZenMode (But I wanted to step into)

Workaround:

Add `"when": "!inDebugMode"` condition.

But the default keybinding doesn't have `"when": "!inDebugMode"` condition, so why does the custom keybinding need it?

**Comment by Tyriar** [comment]
The reason it doesn't need it is because of the order in which the standard keybindings were evaluated. `toggleFullScreen` probably should have the `!inDebugMode` context, just in case the keybindings order happens to change.

**Comment by Tyriar** [comment]
@bpasero created https://github.com/Microsoft/vscode/pull/20898 to fix this if it's desirable.

@CoenraadS as for your issue, adding the `when` context is the right way to do it.

**Comment by bpasero** [comment]
@Tyriar no, the better fix is that the debug keybinding registers with higher priority.

**Comment by isidorn** [comment]
@bpasero step into is already being registered with a stronger keybinding https://github.com/Microsoft/vscode/blame/master/src/vs/workbench/parts/debug/electron-browser/debug.contribution.ts#L114

Should I use some other number than `1` in `KeybindingsRegistry.WEIGHT.workbenchContrib(1)`

**Comment by bpasero** [comment]
@isidorn no, that should work. I am using +10 e.g. in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileActions.contribution.ts#L242 and that seems to work just fine.

**Comment by Tyriar** [comment]
Sounds like nothing needs to be changed then because the keybindings have different weights?

**Comment by isidorn** [comment]
Yes, sounds like that to me
