### ISSUE TITLE
Support terminal `file://` URI links in remote connected windows

### ISSUE THREAD

**Issue by tudortimi** [microsoft/vscode#208572]
It would be great if VS Code would support `file://` URIs. For example, Gradle will write the following in the terminal after running Java tests:

![image](https://github.com/microsoft/vscode/assets/8170909/f2dd71a8-378f-4f6c-902e-0910ee31706b)

(I had to redact some parts of the path, but imagine that it's a full URI starting at `/home` and ending at `index.html`.)

Doing CTRL+click on the URI doesn't open the file, because VS Code is trying to interpret the entire string as a file path, including the `file://` part.

It would also be great if the `CTRL+P` dialog would also support `file://` URIs. This can be useful when copying and pasting text into it.

**Comment by Tyriar** [comment]
The terminal should support this, maybe you're hitting some edge case:

<img width="636" alt="Screenshot 2024-03-25 at 5 35 17 AM" src="https://github.com/microsoft/vscode/assets/2193314/abb8cf73-b03f-4e92-8997-d7a2b43c4c90">

Could you try on the [latest insiders](https://code.visualstudio.com/insiders/) and if it happens there could you try get a `Terminal` trace log when you hover the link? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

---

cc @TylerLeonhardt about supporting file:// paths in quick pick.

**Comment by tudortimi** [comment]
I'm installing and setting up insiders. In the meantime, I got some more info. CTRL + hover over the path underlines it, so VS Code does recognize it:

![image](https://github.com/microsoft/vscode/assets/8170909/867d92ae-05d7-4f0f-8442-5b2432b138f9)

(You don't see the cursor in the screenshot, because I could only do a screenshot with Print Screen, which seems to remove the cursor. The cursor was over the text.)

Clicking the link shows the following:

![image](https://github.com/microsoft/vscode/assets/8170909/6e764b12-0290-4bf1-9c35-b753dca719af)

It seems to have trouble with the leading `/`.

Running in WSL 2, Ubuntu, and VS Code is running in Windows, in case it makes a difference.

**Comment by tudortimi** [comment]
I get the same behavior with both VS Code 1.87.2 and 1.88.0-insider.

**Comment by tudortimi** [comment]
I just tried this in a "real" Linux. There it did work, I could CTRL+click on the `file:///...`. It seems that WSL might be the issue.

**Comment by Tyriar** [comment]
@tudortimi were you using the Remote - WSL extension or just a WSL terminal?

**Comment by tudortimi** [comment]
With remote connection: 

![image](https://github.com/microsoft/vscode/assets/8170909/52bc4bbc-8946-4735-bc89-63ce0371fc07)

So, this extension:

![image](https://github.com/microsoft/vscode/assets/8170909/2dc19828-3323-4361-adf8-5936292923c0)

**Comment by Tyriar** [comment]
Can reproduce:

![image](https://github.com/microsoft/vscode/assets/2193314/4e790eb9-a787-4ddb-8c72-0db6aedfcb93)
![image](https://github.com/microsoft/vscode/assets/2193314/a4be15ef-e812-47f5-83b7-029a5d3d55a5)
