### ISSUE TITLE
display glitching

### ISSUE THREAD

**Issue by wszl23** [microsoft/vscode#208525]
**Environment:**  
- VS Code Version:1.87.2
- OS Version: Window10 version22H2
- Electron Version: 27.3.2
  
**Steps to Reproduce:**  
  
just enter the software

**Actual behavior:**  
display glitching(might be a problem related to Electron)

  
**Does this issue occur when all extensions are disabled?:** Yes/No  
Yes
  
**Additional information:**  
![screenshot-1711263048314](https://github.com/microsoft/vscode/assets/164724115/b844f287-1a84-44be-bf90-85e38fbee87a)

**Comment by gjsjohnmurray** [comment]
Please launch VS Code from a command prompt using `code --disable-gpu`

**Comment by wszl23** [comment]
Is this a common issue?

**Comment by deepak1556** [comment]
Please enable the setting following the steps at https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

/duplicate https://github.com/microsoft/vscode/issues/124226
