### ISSUE TITLE
Placeholder for empty notebook outline view

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#208553]
Re https://github.com/microsoft/vscode/issues/208546

Currently when the document has no headers and we hide code cells, the outline view is empty

![image](https://github.com/microsoft/vscode/assets/876920/cca46bd1-0d97-4bc7-9aea-c12d6d18e048)

When using the outline view with text editor, it shows a placeholder indicating the view is empty. We might want to do the same for notebooks too.

![image](https://github.com/microsoft/vscode/assets/876920/e3a7c62f-676b-40ad-ba65-f2153308e5fc)

**Comment by anthonykim1** [comment]
![Image](https://github.com/user-attachments/assets/d712d2b2-5f17-4f0d-8588-e734a8736072)
seems like all resolved now :)
