### ISSUE TITLE
Regenerate button should respect new input

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#208580]
Testing #208409

- Open inline chat
- request a change
- type into the input box
- press regenerate

Observe: the additional text you types into the input box is lost. I would expected it to be honored.

**Comment by jrieken** [comment]
I understand this as feedback to move the regenerate button closer to the preview request/response or to disable it when typing a new quert. Using the new input isn't its intention because the button runs requests with a different temperature so vary results for one request

**Comment by jrieken** [comment]
Today, the rerun btn hides when you type a new/different query. I believe that makes this less confusing
