### ISSUE TITLE
Ability To Use Application Scope Settings In Workspace Settings File

### ISSUE THREAD

**Issue by Barzi-Ahmed** [microsoft/vscode#208502]
Hello, 
For some reasons, I want to use all of the application scope settings in my workspace settings file. Please provide such ability.

**Comment by sandy081** [comment]
Can you please specify what settings you want to use and why?

**Comment by sandy081** [comment]
I do not think it is a valid scenario to do the behavioural change of these settings which might impact the complete product. I believe you can find other solutions like Settings Sync from VS Code to track your user settings.
