### ISSUE TITLE
Cannot create issues

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#208573]
Testing #208468

I have tested the issue flow on my Linux VM and while things work great I wasn't able to actually file an issue. When I select the "Create on GitHub" button nothing happens... I would expect the browser to open which is something that works fine for links with VS Code

**Comment by justschen** [comment]
@jrieken just tested in my linux VM and was able to submit with no issues (https://github.com/microsoft/vscode-python/issues/23120)

which extension were you filing on and was there any console output?

**Comment by jrieken** [comment]
Also python. It might very well be a setup issue with my VM, so I am fine if you wanna close this
