### ISSUE TITLE
Integrated terminal UTF-8 user input problem

### ISSUE THREAD

**Issue by kaan-yalcinkaya** [microsoft/vscode#208515]
Type: <b>Bug</b>

I am using msvc in VS Code. I set the system codepage to 65001(UTF-8). I also set the code page to UTF_8 with SetConsoleOutputCP and SetConsoleCP in the code. For UCRT I used setlocale(LC_ALL, ".UTF8"). Despite all this, when I read UTF-8 from the user with fgets and print it to the screen, UTF-8 characters are not printed to the screen. I have also tried this with Powershell 7 in the Windows Terminal application and it prints all UTF-8 characters to the screen. I think there is a problem with the integrated terminal of the vs code. I should also mention that I am using Powershell 7 in the integrated terminal.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.13GB free)|
|Process Argv|. --extensions-dir=D:\\vscode\\extentions --user-data-dir=D:\\vscode\\settings --crash-reporter-id b5d28750-f57b-4f1c-89e3-2685264951b1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.14
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30998030
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:30996668
666c4381:30973075
dsvsc021:30996838

```

</details>

**Comment by meganrogge** [comment]
You can try to explicitly set the encoding for the integrated terminal in VS Code settings. Here's how you can do it:

Open the settings in VS Code. You can do this by pressing Cmd + , on your keyboard.
Search for terminal.integrated.env.osx in the settings search bar.
Click on Edit in settings.json.
In the settings.json file, add or update the following lines:
```
"terminal.integrated.env.osx": {
    "LANG": "en_US.UTF-8"
}
```
Save the settings.json file and restart VS Code.
This will set the environment variable LANG to en_US.UTF-8 for the integrated terminal, which should allow it to handle UTF-8 characters correctly.

**Comment by meganrogge** [comment]
You can try to explicitly set the encoding for the integrated terminal in VS Code settings. Here's how you can do it:

Open the settings in VS Code. You can do this by pressing Cmd + , on your keyboard.
Search for terminal.integrated.env.osx in the settings search bar.
Click on Edit in settings.json.
In the settings.json file, add or update the following lines:
```
"terminal.integrated.env.osx": {
    "LANG": "en_US.UTF-8"
}
```
Save the settings.json file and restart VS Code.
This will set the environment variable LANG to en_US.UTF-8 for the integrated terminal, which should allow it to handle UTF-8 characters correctly.

**Comment by meganrogge** [comment]
You can try to explicitly set the encoding for the integrated terminal in VS Code settings. Here's how you can do it:

Open the settings in VS Code. You can do this by pressing Cmd + , on your keyboard.
Search for terminal.integrated.env.osx in the settings search bar.
Click on Edit in settings.json.
In the settings.json file, add or update the following lines:
```
"terminal.integrated.env.osx": {
    "LANG": "en_US.UTF-8"
}
```
Save the settings.json file and restart VS Code.
This will set the environment variable LANG to en_US.UTF-8 for the integrated terminal, which should allow it to handle UTF-8 characters correctly.
