### ISSUE TITLE
"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 2.

### ISSUE THREAD

**Issue by Ayushkumar302** [microsoft/vscode#208531]
Type: <b>Performance Issue</b>

terminal is closing automatically ans giving this "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 2.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.77GB (1.70GB free)|
|Process Argv|--crash-reporter-id 0ef2155e-52df-4c64-b514-46517c882793|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   101	 10476	code main
    0	    92	  1960	window [2] (Issue Reporter)
    0	   174	  5800	extensionHost [1]
    0	    83	 10804	     electron-nodejs (server.js )
    0	   101	 14812	     "C:\Users\acer\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\acer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=5800
    0	    85	 15780	     "C:\Users\acer\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\acer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=5800
    0	    80	 18292	     electron-nodejs (serverMain.js )
    0	   185	  9936	window [1] (index.html - food - Visual Studio Code)
    0	    41	 10504	   utility-network-service
    0	    82	 10648	fileWatcher [1]
    0	    28	 14384	   crashpad-handler
    0	   174	 15784	   gpu-process
    0	    90	 18336	shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - food - Visual Studio Code)
|    Folder (food): 30 files
|      File types: png(15) css(6) html(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
rc-beautify|Ato|1.2.0
vscode-toggle-quotes|Bri|0.3.6
simple-react-snippets|bur|1.2.7
marko-beautify|bus|2.0.0
turbo-console-log|Cha|2.10.4
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|2.0.9
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
randomeverything|hel|0.0.3
myBeautify|Isa|0.3.7
vscode-gutter-preview|kis|0.30.0
java|red|1.28.1
LiveServer|rit|5.7.9
html-to-css-autocompletion|sol|1.1.2
open-in-browser|tec|2.0.0
vscode-lldb|vad|1.10.0
incredibly-in-your-face|Vir|1.0.2
vscode-java-debug|vsc|0.56.2
vscode-java-dependency|vsc|0.23.5
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0
console-ninja|Wal|1.0.294
JavaScriptSnippets|xab|1.8.0
chat-gpt|zha|1.6.63

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30998030
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:30996668
gee8j676:30988843
dsvsc021:30996838

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
