### ISSUE TITLE
WorkspaceEdit.createFile leads to undefined error

### ISSUE THREAD

**Issue by pelikhan** [microsoft/vscode#208547]
Type: <b>Bug</b>

Undefined access when previewing a createfile edit.

- Run this code in a workspace command:

```ts
const edit = new vscode.WorkspaceEdit()
// unique new file name
const fn = vscode.Uri.joinPath(vscode.workspace.workspaceFolders![0].uri, Math.random() + ".txt")
const contents = new TextEncoder().encode("hello world")
// create new file edit
edit.createFile(fn, { overwrite: true, ignoreIfExists: false, contents }, { label: "hello world", needsConfirmation: true })
// opens refactoring UI
vscode.workspace.applyEdit(edit, { isRefactoring: true })
```

- Click on file preview in refactoring UI
- You will get an "undefined ... when trying to read 'template'"

VS Code version: Code - Insiders 1.88.0-insider (Universal) (409da0445d397e37a790ce5d2499688955c3fcfa, 2024-03-22T05:51:39.055Z)
OS version: Darwin x64 23.4.0
Modes:
Remote OS version: Linux x64 6.2.0-1019-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|--enable-proposed-api Microsoft.gptools-vscode --crash-reporter-id 50682cdc-63ac-4745-a4e9-7c251fbd4ff1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: symmetrical doodle|
|OS|Linux x64 6.2.0-1019-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (2 x 2692)|
|Memory (System)|7.74GB (4.94GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.10.0
codesandbox-projects|Cod|0.2.132
file-icons|fil|1.1.0
codespaces|Git|1.16.17
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.110.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.6.2024032109
vscode-speech|ms-|0.7.2024032017
vscode-eslint|dba|2.4.4
codespaces|Git|1.16.17
vscode-pull-request-github|Git|0.82.1
extension-test-runner|ms-|0.0.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805:30301674
vsaa593:30376534
py29gd2263:30784851
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:30998029
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
bf62j303:30968145
cppperfnew:30980852
8082a590:30961435
fegfb526:30952798
bg6jg535:30979844
ccp1r6:30958151
pythonait:30973460
7ghi1836:30988844

```

</details>

**Comment by pelikhan** [comment]
<img width="857" alt="image" src="https://github.com/microsoft/vscode/assets/4175913/13cb711a-02b0-48d5-aae8-0ec4edddc7cf">

**Comment by jrieken** [comment]
@hediet @aiday-mar can you please investigate?
