### ISSUE TITLE
cmd+backspace stops working in the editor after using copilot

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#208549]
- cmd+i
- now cmd+backspace invokes `workbench.action.chat.remove` instead of deleting the line in the text editor

The ChatWidget is writing its context keys to the editor's ContextKeyService, so we need a scoped CKS at some point, either inside the ChatWidget or outside in the inline widgets

**Comment by jrieken** [comment]
@roblourens pushing a fix to use a scoped CKS but this does look like debt. Isn't a better fix to reset context keys when hiding/dispose the chat widget?

**Comment by roblourens** [comment]
I don't think those context keys should be applied on the editor at all, they are intended to just be active inside the widget's dom tree.
