### ISSUE TITLE
all codes on С\С.срр They don't work

### ISSUE THREAD

**Issue by SvyatoslavSatulov** [microsoft/vscode#208624]
Type: <b>Bug</b>

they do not compile and give the error of missing libraries checked and reinstalled changed settings does not help

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (0.96GB free)|
|Process Argv|--crash-reporter-id 9b265b15-818e-4672-bb42-3e7d84d5aee3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|2.0.9
cpptask|kay|0.0.1
vscode-language-pack-ru|MS-|1.87.2024031309
csdevkit|ms-|1.4.29
csharp|ms-|2.22.5
vscode-dotnet-runtime|ms-|2.0.2
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2024.0.0
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30998030
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:30996668
dsvsc021:30996838

```

</details>

**Comment by DonJayamanne** [comment]
Thank you for filing this issue and sorry you are running into this.
However VS Code does not natively support compiling nor display errors about installed/uninstalled libraries.
This functionality is provided by other VS Code extensions.

You seem to have a few extensions related to this, I would suggest you identify the extension and and then file an issue against the corresponding repo.
