### ISSUE TITLE
Nice to have: version of ${dirname} that gives the minimum dirname to differentiate matched names

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#208684]
Testing #208388

When testing this, I thought that it'd be nice to have a version of ${dirname} that gives the minimum pathname to differentiate from matches. For example,

`**/file.json`: `${unique_dirname}/${filename}.${extname}`

with the following filetree
```
my-app/
├─ one/
│  ├─ file.json
│  ├─ new_folder/
│  │  ├─ file.json
├─ two/
│  ├─ file.json
│  ├─ new_folder/
│  │  ├─ file.json
```

If you had `one/file.json` open only, it would just open as `file.json`. If you also opened `two/file.json`, the original file would be `one/file.json` and the second would be `two/file.json`. 

Finally, if you only had `one/new_folder/file.json` open with `two/new_folder/file.json`, you would show those names as I wrote them, as they both share their immediate parent folder name.

**Comment by benibenj** [comment]
We already have a similar concept for the description of the label. When you have multiple files with the same name open, we "dedupe" them by adding the shortest differentiating path as description of the label in the tab (and open editors view).
See in this picture `...\tree` and `...\titlebar`.
<img width="762" alt="image" src="https://github.com/microsoft/vscode/assets/44439583/9d2bde29-b724-44a5-a654-f84d66d9ce5c">

I think it's a good idea to be able to use that logic for rendering the label name as it makes it more visible compared to the description. I'll consider adding this next month depending on feedback from the community.
