### ISSUE TITLE
Terminal Inline Chat: Response does not fit inside widget

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#208676]
The rendered response in inline chat is larger than the widget displays. Seems like the computation of the height of the widget might not be taking the padding of the code blocks into account.

<img width="743" alt="image" src="https://github.com/microsoft/vscode/assets/44439583/3abf0c22-28bf-495d-82be-8f3f204e1fd5">

**Comment by Tyriar** [comment]
Max height has changed since this but it's yb design to max out at 75% of the viewport (or min height of the widget, whichever is higher).
