### ISSUE TITLE
Duplicate option in Explorer file or folder context menu

### ISSUE THREAD

**Issue by ADTC** [microsoft/vscode#208625]
If I right-click a file or folder in the Explorer menu, I'd like to be able to quickly duplicate the file. In my total experience as a developer, I have very frequently duplicated files or copied entire contents of existing files into new files because I use them as a starting point or template to modify into new code. (I'm sure it's not just me. We don't always write code from scratch.)

I noticed that MacOS Finder has a nice option in the file context menu called "Duplicate" which does exactly what it says. It creates a copy of the chosen file, immediately. It doesn't even ask anything (and I don't want it to).

<img width="230" alt="image" src="https://github.com/microsoft/vscode/assets/6047296/6843a4a7-d04a-40a1-bc6d-0bd1f66bf5df">

I have often wished for similar function in VS Code Explorer pane, and at this point there is none. I have to copy the file (presumably into clipboard) and then paste it again to create a copy in the same folder. I believe this two-step process can be sped up by giving a "Duplicate" option in the context menu. (Bypassing the clipboard as well.)

I searched "duplicate" the Extension store, and there are a handful of extensions that offer this functionality (duplicating files). So clearly the demand is there. **I just think that this should be part of the core Explorer functionality, and not something left to an extension.** _(I've resorted to using [this extension](https://marketplace.visualstudio.com/items?itemName=includable.file-duplicate) for now, which matches macOS Finder behavior the closest.)_

~_Note: I tried looking for duplicates but I couldn't really find any. But it's also difficult to search for the word "duplicate" because it refers to duplicate issues._~ [Had better success searching with `in:title`.](https://github.com/microsoft/vscode/issues?q=is%3Aissue+duplicate+in%3Atitle) Seems like this was indeed [asked before](https://github.com/microsoft/vscode/issues/196205), and answered with "this is better left for extensions". Why though?

**Comment by lramos15** [comment]
Duplicate is not standard across OSes, and VS Code aims to provide the minimal core set of features while providing a rich extensibility story so you can customize it to your liking. Adding duplicate as an entry would further clutter the menu with an item that many would not use so if something is accomplishable by an extension we almost always suggest that an extension does it instead of the core product that way users can decide what features they do and don't want .
