### ISSUE TITLE
Quick FTP

### ISSUE THREAD

**Issue by ManPython** [Microsoft/vscode#20861]
Again about FTP.
I think we need decision, that:

1.  main VSC developers **want support this feature or not** and leave this for:
2.  external extensions which exist or can be developed other (maybe bether than exist)
3.  external extensions as own support to solve basic problem what exist in point 2

- [ ] We need **FTP manager as global list of ftp accounts** (should not be as dedicated config.json for main project, easy to disclose secret access data to the servers [login/pass]) 
- [ ] should work similiar as **FTP Explorer** but on remote server 
- [ ] Search, Listing dirs and files
- [ ] **CHMOD** edit options + automaticly add default CHMOD for some files/dir (if edit or created) if need (eg. execute for .py - very often issue on ftp clients - that after upload/changes we must manulay change CHMOD to set execute mode for file)
- [ ] Can be as next icon "qFTP" (Quick FTP [ctr+shift+q]) under "Extensions" icon
- [ ] some backup/tmp philosophy for files (including undo, redo) if saved files in live mode was was done with mistake
- [ ] Sync (exist plugins but this is far from all **Qucik FTP Explorer** )

4. I know about
https://github.com/Microsoft/vscode/issues/18186
https://github.com/Microsoft/vscode/issues/13643

5. Main question - is exist some problem to create extensions as full explorer (clone for ftp), eg. no support from API?

**Comment by ManPython** [comment]
Maybe this can more simple by offering possibility to use folders as shortcuts to ftp accounts?

The shortcuts
`C:\Windows\explorer.exe ftp://username@localhost/`
- more info
http://superuser.com/questions/166469/how-to-make-shortcut-to-ftp-site-open-in-windows-explorer-not-ie
- https://www.youtube.com/watch?v=FFyvehKG6u8 Mapping FTP Server Shortcut in Windows 7 Explorer by Britec

**Comment by Alex360hd** [comment]
Working with folder as FTP account is slow and buggy, I think it would be better to implement remote explorer directly in VS code.

**Comment by ArkhipovK** [comment]
One more minor feature missed is concealing ftp account passwords, for those cases when you've left your workplace and don't want someone steal your ftp acc.

**Comment by jrieken** [comment]
We do have something in the works, lots of proposed API for different 'remote'-scenarios and a sample implementation using FTP, see: https://github.com/jrieken/ftp-sample

**Comment by hidonet** [comment]
Editplus FTP is a good example for native FTP support;

- Supports direct edit remote files, 
- Supports adding remote files to projects, 
- Saves file to remote path with CTRL + S,
- Located in the file manager section,
- "Locate file" command over file tab header opens remote directory of current file,
- No need to create project or workspace. Just select ftp connection and open file

You may check editplus ftp if you planning to add direct FTP/SFTP support.

**Comment by ManPython** [comment]
@hidonet 
> E*itplus FTP is a good example for native FTP support;

You mind other editor or some unknow plugin to VSC?

BTW last time I see that VSC going in way that VSC is some console tool as in linux etc in case that is GUI interface. This made some difrent philosophy than typical soft. Then.. why we need VSC? Back to to past times.. eg. dos

**Comment by hidonet** [comment]
In my side I want to use VSC's advanced functions. But remote editing is a must for me at the moment. I've tested all vsc extensions for vsc. But none of them fits my needs. I think a lot of developer uses their editors/ides in that way.

**Comment by ManPython** [comment]
@microsoft @billgates 
CMON!! Give it for us!  : )

#microsoft

**Comment by gsabater** [comment]
Not a single plugin for vscode or atom are close to what SFTP for sublime text does.
I think that this should be the lowest standard that a plugin for vscode has to aim for.

FTP support is a big deal for a lot of users

**Comment by pwwang** [comment]
This feature has been raised for years, no progress at all. Disappointed.

**Comment by jrieken** [comment]
We are finalising the file system provider api this milestone (April). See https://github.com/Microsoft/vscode/issues/47475. With that extensions authors can add support for ftp, sftp etc.

**Comment by ManPython** [comment]
Hope that somebody can inform that any new good add-in is available.

**Comment by hajekj** [comment]
I suggest looking at this one - https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-remote-workspace, however be aware of https://github.com/mkloubert/vscode-remote-workspace/issues/6

**Comment by mkloubert** [comment]
@ManPython @hajekj 

Thanks for the suggestion!

**Is implemented since version 0.24.0.**

**Comment by hajekj** [comment]
Just tried it with 0.24, I totally suggest @ManPython that you try it, an amazing extension we all have been waiting for!

**Comment by ManPython** [comment]
@mkloubert good to see you in this thread. Let me know if you planing or opened to implement something from my list. Maybe I can join.
