### ISSUE TITLE
Problemas 

### ISSUE THREAD

**Issue by andreshito08** [Microsoft/vscode#20868]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|npm-intellisense|christian-kohler|1.2.1|
|vscode-eslint|dbaeumer|1.2.6|
|xml|DotJoshJohnson|1.7.0|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|vscode-npm|fknop|3.3.0|
|icon-fonts|idleberg|1.6.1|
|ionic2-vscode|jgw9617|1.0.0|
|ionic1-snippets|justinjames|1.0.1|
|vs-color-picker|lihui|0.4.0|
|debugger-for-chrome|msjsdiag|2.5.3|
|ionic2-snippets|oudZy|1.0.0|
|ionic2|Thavarajan|2.3.5|
|ionic2-snippets|uqutub|0.0.4|
|cordova-tools|vsmobile|1.2.6|

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
Sorry, we don't have a crystal ball and don't know what you have meant by this issue. Please update the issue with steps to reproduce and we will reopen it.
