### ISSUE TITLE
vscode.window.visibleTextEditors returns closed document

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#20867]
- VSCode Version: `1.9.1`
- OS Version: `Windows 10`

Steps to Reproduce:

Run the following extension:

```
export function activate(context: vscode.ExtensionContext) {
    vscode.workspace.onDidCloseTextDocument((event) => {
        console.log("Closed document: " + event.fileName);
        console.log("Visible documents:");
        vscode.window.visibleTextEditors.forEach((editor) => {
            if (editor.document) {
                if (editor.document.fileName == event.fileName) {
                    console.warn(editor.document.fileName);
                }
                else {
                    console.log(editor.document.fileName);
                }
            }
        })
    });
}
```

1. In the VSCode editor being debugged, open many files.
2. Drag one of the files into split view
3. Focus the right editor panel
4. Close a file in the left panel, without giving it focus (click the x, just don't click the document first)
5. When the file is closed in the left panel, a new file takes its place
6. But `visibleTextEditors` will return the closed file, not the new file
7. This situation continues until the new file gains focus

Took me ages to figure out how to reproduce this, I hope its not as designed.

**Comment by jrieken** [comment]
I can repro. Thanks for the detailed steps.

**Comment by jrieken** [comment]
The problems seems to be that fact that we update the editor/document mapping with a slight delay and therefore one event 'over takes' the other.

**Comment by jrieken** [comment]
It unfortunately requires a bigger code change and since the last hours of development for the Feb milestone are passing I am forced to push this out to March. 

@CoenraadS As a workaround you might be able to use the `onDidChangeVisibleTextEditors` event

**Comment by jrieken** [comment]
this got fixed with https://github.com/Microsoft/vscode/commit/1239cebb7005a05d6a183d44ca08b303312b3ff4
