### ISSUE TITLE
Unable to `Esc` out of voice chat in terminal

### ISSUE THREAD

**Issue by cwebster-99** [microsoft/vscode#208664]
Testing #207642

Unable to `Esc` to stop dictation after invoking it in the terminal via `Terminal: Start Dictation in Terminal` the same way I am able to exit via `Esc` on other entry points. In order to turn off dictation, I had to hit `Terminal: Start Dictation in Terminal` again (in which I heard the audio cue and the visual also went away). I expect to be able to exit the same way or clearer instructions on how to turn off voice chat after invoked.

**Comment by meganrogge** [comment]
You can assign that keybinding to the Stop command. This set of commands is going to be removed soon, so closing this.
