### ISSUE TITLE
IntelliSense duplicate method as property in completion and miss parameters

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#20865]
- VSCode Version: 1.9.1
- OS Version: MacOs Sierra 10.12.3
Tested with no extensions / no personal config.

Steps to Reproduce:

In a javascript file :
1. type :
```
//     cursor v
"String".toLow|
```
2. press "**tab**"
3. give the result : 
```
//           cursor v
"String".toLowerCase|
```
Expected parenthesis : 
```
//             cursor v
"String".toLowerCase( | )
```

The problem seems to be intellisense consider all exported functions as property too.
It result in a duplicate suggestion, one good, and the other broken. The problem is that the broken one is considered first.

Here is an example, we can show twice the same completion. The second do the job but the first (default) is crap : 
![untitled](https://cloud.githubusercontent.com/assets/5599375/23098297/b8517354-f64a-11e6-8a1c-dda00b36b5b2.gif)

How can i disable the first or priorize the second ?

**Comment by DavidBabel** [comment]
Here is an example, we can show twice the same completion. The second do the job but the first (default) is crap : 
![image](https://cloud.githubusercontent.com/assets/5599375/23098036/02022022-f644-11e6-8be8-4bb585ae4fda.png)

How can i disable the first ?

**Comment by DavidBabel** [comment]
Another example for setTimeout function : 

![grrrr](https://cloud.githubusercontent.com/assets/5599375/23104914/101e54f8-f6d7-11e6-9bb9-02450a1c96a9.gif)

First is awesome, second is totally crap (and is **default**) and third is just acceptable.

The problem with intellisense here, is that we got no idea where it's from and if it's configurable.

**Comment by jrieken** [comment]
There is this setting `"typescript.useCodeSnippetsOnMethodSuggest": false` which also works for JavaScript like that. Maybe a bug @mjbvz ?

**Comment by DavidBabel** [comment]
Thanks @jrieken ,` "typescript.useCodeSnippetsOnMethodSuggest": true` did the trick.

But a way to configure which intellisense are enabled globally can be very usefull since we never know were a suggestion come from, and regarding the mass of extension adding some.

**Comment by mjbvz** [comment]
@DavidBabel I'm not sure the suggestion that completes the function call is coming from. @jrieken is correct that `"typescript.useCodeSnippetsOnMethodSuggest"`" configures the default js/ts suggestions to try to complete function calls, however I only even see one suggestion for methods like `read` and two suggestions (a property and a snippet) for `setTimeout`. 

Can you please try running code using the `--disable-extensions` command line flag to ensure this is not coming from an extension?

**Comment by DavidBabel** [comment]
Actually the problem appear on single suggestion too, without any extension and a config file with only this config : `"typescript.useCodeSnippetsOnMethodSuggest"` set to `true` . Here is best example :

![requirebug](https://cloud.githubusercontent.com/assets/5599375/23210733/2e933528-f8ff-11e6-8453-0d031e1f7da1.gif)

And I still have two `setTimeout` suggestion on fresh installed vscode.

@mjbvz You are right, i did not check which extension it is, but i got an extension adding some intellisense for sure. 
But the problem is : how disable the default behaviour or choose the priority if an extension add better intellisense ? This will allow to choose better default result and remove duplicates.

**Comment by mjbvz** [comment]
@DavidBabel #17068 tracks allowing disabling built-in extensions. I believe there's also been discussion of finer grained control to toggle specific features (such as completion items) of each extension, but this is farther off 

We expect the two `setTimeout` definitions since one is a snippet. You can remove snippets from the suggestion list using `"editor.snippetSuggestions": "none"`

**Comment by DavidBabel** [comment]
Yeah but it remove all the snippets. I like my personnal ones :p 

Actually i did test this`setTimeout` snippet on a new MacOs User session, with no vscode configuration at all, on both vscode 1.9.1 and nightly, and both same result : double suggestion.

If it can help i have a mac touchbar : 
![image](https://cloud.githubusercontent.com/assets/5599375/23235633/857165ac-f956-11e6-883e-e3cf4e76e78b.png)

**Comment by mjbvz** [comment]
@DavidBabel This still sounds like the expected behavior.  There are a couple of issues tracking the various issues you've noted:

* #10565 tracks being able to disable builtin snippets such as `setTimeout`
* #17068 tracks allowing disabling built-in extensions 

Please follow up with the extension that is providing these additional suggestions to get them to return suggestions that are preferred over the builtin TypeScript suggestions
