### ISSUE TITLE
Many view command names are wrong

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#208667]
Not sure what's going on here:

![image](https://github.com/microsoft/vscode/assets/2193314/05a1dcdb-b215-45c0-bc61-ba6bc9ed7835)

Version: 1.88.0-insider (user setup)
Commit: b0d975fc6370f15570c380f41015b1ca2cdcb791
Date: 2024-03-25T05:49:32.344Z
Electron: 28.2.6
ElectronBuildId: 27476517
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by bpasero** [comment]
I think thats fixed now.
