### ISSUE TITLE
Lost inline chat placeholder text

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#208604]
Testing #208411

Press `Cmd I` and you get:

<img width="694" alt="image" src="https://github.com/microsoft/vscode/assets/22350/ee79dd2d-c8e0-401d-bf1a-df2f35458245">

If you hold `Cmd` while doing it, it will switch to:

<img width="707" alt="image" src="https://github.com/microsoft/vscode/assets/22350/3bed92b9-206f-4c3e-b0ff-5a08870c0a7d">

Letting go of `Cmd` loses the placeholder text:

<img width="685" alt="image" src="https://github.com/microsoft/vscode/assets/22350/3528c387-9088-4301-8eca-c84c41c33b68">

**Comment by jrieken** [comment]
This is now fixed
