### ISSUE TITLE
Improve accessible view UX

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#208654]
Testing #207637

Is there a specific reason why the accessible view uses monospace font? We could make it have the regular sans-serif workbench font and use monospace only for code blocks.

That way keyboard shortcuts could be highlighted much better in the commands view. Right now they blend in too seamlessly with the free form English prose:

<img width="629" alt="image" src="https://github.com/microsoft/vscode/assets/22350/f49a63b4-d994-4fe0-b158-6d2d52ff9126">

---

Additionally, should we use different phrasing here? Suggestion:

> From the accessibility view you can perform the following actions:
> - Press `Option+]` to show the next item and `Option+D` to show the previous item.
> - Press `Shift+Command+0` to go to a symbol.
> - Press `Shift+Tab` to navigate to the toolbar.

etc...

**Comment by meganrogge** [comment]
Closing as designed
