### ISSUE TITLE
Should `shellIntegration.executeCommand` throw 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#208661]
Testing #208462

The docs says "_*Note* This is not guaranteed to work as [shell integration](https://code.visualstudio.com/docs/terminal/shell-integration) must be activated._" which is confusing because it should

* then not be possible to reach `TerminalShellIntegration#executeCommand`
* or throw an error

**Comment by Tyriar** [comment]
Stale comment 👍
