### ISSUE TITLE
Undo/redo in cell editor does not apply to notebook cell operations

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#208626]
https://github.com/microsoft/vscode/issues/208609#issuecomment-2017759704

**Comment by bamurtaugh** [comment]
+1 to this issue, was going to also open an issue on this while testing https://github.com/microsoft/vscode/issues/208267.

**Comment by rebornix** [comment]
It works as title when you have setting `notebook.undoRedoPerCell` set to `false`. We didn't opt in by default.
