### ISSUE TITLE
Jump and Limited Scroll for Dragged Windows

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#208679]
Testing #208385

steps:
1. use steps from TPI, get a file, notebook (same window), and editor (new window)
2. drag file from left-most editor panel to middle editor panel (from test_discovery.py spot to ex.ipynb spot) this is what I did with __init__.py
3. 🐛 scrolling cannot see full __init__.py page when on test_discovery.py and when scrolling on venvUtils.ts the editor for __init__.py jumps to line 400 from the top.

(video quality is bad bc the file was too big- lmk if you want me to message it to you)

**Comment by eleanorjboyd** [comment]
video:
https://github.com/microsoft/vscode/assets/26030610/2ccd7820-8c60-4d16-b8b9-f0bfc62155f5

**Comment by benibenj** [comment]
If I understand correctly, this is actually working as designed. What we do is we sync the positions from the moment you lock the scrolling. So if file A is at line 100 and file B at 500 and you scroll B all the way up to line 0 then in theory file A is at line -400, however, we block it at line 0. This means if you then scroll file A down to line 50, then file B will jump to line 450 immediately.
This might seem a bit weird initially, however, it makes sense for the use cases.
