### ISSUE TITLE
Inline chat is centered when the result is very wide

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#208656]
Just asked hi:

![image](https://github.com/microsoft/vscode/assets/2193314/85d2eb48-9174-43f5-a3e8-0f942145e622)

Expected:

![image](https://github.com/microsoft/vscode/assets/2193314/0be3c924-1011-4c88-a16c-42306346d97d)

Version: 1.88.0-insider (user setup)
Commit: b0d975fc6370f15570c380f41015b1ca2cdcb791
Date: 2024-03-25T05:49:32.344Z
Electron: 28.2.6
ElectronBuildId: 27476517
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621

GitHub Copilot Chat
v0.14.2024032501 (pre-release)

**Comment by jrieken** [comment]
because of https://github.com/microsoft/vscode/blob/b0d975fc6370f15570c380f41015b1ca2cdcb791/src/vs/workbench/contrib/chat/browser/media/chat.css#L7

**Comment by jrieken** [comment]
To verify

* configure `"inlineChat.mode": "preview"`
* have a very wide view port 
* ask AI to change some code
* make sure the input widget is full width of the zone widget
