### ISSUE TITLE
Clicking around the outline view and between cells can lead to strange focus results

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#208671]
Testing #208546

Repro:

1. Create a notebook with the following cells (likely doesn't matter exactly type)
2. Show cell symbols in outline filter menu
3. Click on the bottom markdown cell in the outline, it gets highlighted
4. Click on the `b` symbol, :bug: after a little period the parent and all its children are highlighted

I think what's happening here is clicking `b` is setting the top cell as the active one, but since focus is still in the outline, it's unexpected for the selection to be changed:

![Recording 2024-03-25 at 07 45 57](https://github.com/microsoft/vscode/assets/2193314/cc4f1adb-5eb8-4a44-91ab-55ea9fd921bd)

Another problem using the same setup that I suspect is the same root cause is that if I click the bottom markdown cell and then the `b` one quickly, `b` will not be set to active. Likely happening because of the same active cell/focus triggering a race condition.

**Comment by Yoyokrazy** [comment]
Will be handled by https://github.com/microsoft/vscode/issues/208554. Multi-select will be disabled in the notebook toc
