### ISSUE TITLE
cmd+down quick tree shortcut doesn't always show the focused item

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#208696]
Testing #208477

<img width="963" alt="image" src="https://github.com/microsoft/vscode/assets/323878/4874fa31-ec8c-43c7-a2fb-ea8b2159362e">

Here, I pressed cmd+down and it selected the first item under `tsx.tx`, but only reveled the title element before it. I think it should also show the item that is selected, it helps me keep my place.

**Comment by TylerLeonhardt** [comment]
Verification:
* Open Quick Search
* type something like `hi`
* scroll so that just the file name (separator) is the last visible item
* hit cmd/alt+down until focus is given to the item right under that separator

Ensure it is revealed to you.
