### ISSUE TITLE
Performing Azure: Login multiple times duplicates subscriptions in subs list. 

### ISSUE THREAD

**Issue by oising** [Microsoft/vscode#20864]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|aurelia|AureliaEffect|0.2.6|
|azuretoolsforvscode|bradygaster|1.2.0|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.6|
|tslint|eg2|0.8.1|
|beautify|HookyQR|0.8.3|
|csharp|ms-vscode|1.7.0|
|azurerm-vscode-tools|msazurermtools|0.3.4|

---

Steps to Reproduce:

1. Invoke Azure: Login
2. Authenticate
3. Invoke Azure: List Subs (shows my three subs)
4. Invoke Azure: Login
5. Authenticate
6. Invoke Azure: List Subs (shows six subs - my three subs each showing twice)

**Comment by roblourens** [comment]
Looks like this is a bug with the Azure tools extension, can you file a bug on their repo? https://github.com/bradygaster/azure-tools-vscode

**Comment by bradygaster** [comment]
@oising feel free to create an issue for us over in the https://github.com/bradygaster/azure-tools-vscode repository. Thanks!

**Comment by oising** [comment]
https://github.com/bradygaster/azure-tools-vscode/issues/39

**Comment by bradygaster** [comment]
@oising just resolved this.
