### ISSUE TITLE
Inline chat: Should suggestions show up when backspacing to `/` ?

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#208607]
Testing #208411

1. Open inline chat
2. Type `/`, notice suggestions coming up
3. Type another character that doesn't match any suggestion
4. Press `backspace`

❓ Should the suggestions widget come back up, since the only thing in the input is `/`?

https://github.com/microsoft/vscode/assets/22350/9f3e13e1-b830-44e4-a065-91b8174f0828

**Comment by jrieken** [comment]
Unsure, it's like `console` and `.` and type/erase `q`. So consistent but likely something special to trigger characters or about backspacing into a new word or over the boundaries of the current word

**Comment by joaomoreno** [comment]
Yeah I can see both sides 👍  just wanted to bring it up.

**Comment by jrieken** [comment]
Closing as this how it works
