### ISSUE TITLE
Undo/Redo does not add/remove cells

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#208609]
Testing #208267

I was able to undo a move, but never a add or remove of a cell in GH issues notebook or Jupyter.

I would only be able to undo/redo text edits.

**Steps:**
- create a notebook
- add 3 cells
- type in the last one
- undo
- it should undo what you typed
- undo again

=> 🐛 the cell is not removed

**Comment by DonJayamanne** [comment]
> it should undo what you typed

Please can you set focus outside the editor.
Ie click outside the cell editor like the border of a cell or  around the cell and try again

Ie this is by design, info/redo in editor does not apply to Operations in the notebook.

**Comment by bpasero** [comment]
@DonJayamanne I think as a user thats relatively hard to understand, esp. since we put focus into cells quite aggressively, the undo/redo story seems hard to use.

Btw while `Undo` works, `Redo` does not:

![Recording 2024-03-25 at 12 10 50](https://github.com/microsoft/vscode/assets/900690/96c1d726-e376-46d6-88ca-ed3a2a0c884a)

**Comment by DonJayamanne** [comment]
> k as a user thats relatively hard to understand, esp. since we put focus into cells quite aggressively, the undo/redo story seems hard to use.

Understood, given that this is by design, I'll create a separate issue to deal with that, perhaps this is a UX issue.
https://github.com/microsoft/vscode/issues/208626
@rebornix /cc

> Btw while Undo works, Redo does not:

Weird, this works perfectly well for me, please can you use the Edit menu, instead of the shortcuts, 
Possible there's a bug in handling the keyboard shortcuts.

**Comment by bpasero** [comment]
Weird, at home on a different machine I cannot reproduce this anymore.
