### ISSUE TITLE
Inline chat: Pressing Enter on empty input will enter new line

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#208606]
Testing #208411

1. Open inline chat
2. Press `Enter`

:bug: You get a new line. 🙈

**Comment by joaomoreno** [comment]
Well, if you press `Enter` a second you don't get a new line. Or if you first press `Space` and then `Enter` you also don't get a new line.

Nothing really bad other than consistency as to what happens when `Enter` gets pressed.

**Comment by jrieken** [comment]
Yeah, the first enter enables the send command (since the input isn't empty-empty anymore) but the second enter triggers send but I guess that understand the input is trimmed-empty and hence doesn't do anything

**Comment by jrieken** [comment]
@roblourens How about a trim here: https://github.com/microsoft/vscode/blob/b0d975fc6370f15570c380f41015b1ca2cdcb791/src/vs/workbench/contrib/chat/browser/chatInputPart.ts#L329

**Comment by roblourens** [comment]
Yeah in the panel chat we do the same check inside ChatService, but this is better
