### ISSUE TITLE
Notebooks open as text after reload

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#208644]
![chrome_946BFOu5L4](https://github.com/microsoft/vscode/assets/2931520/a5563e2b-fa2e-4df2-bf60-c6a48887b74a)

https://insiders.vscode.dev/github/microsoft/vscode/blob/main/.vscode/notebooks/my-endgame.github-issues

**Comment by bpasero** [comment]
Is this in web? Whats your setup?

**Comment by hediet** [comment]
Yes, this is in web.

When you open https://insiders.vscode.dev/github/microsoft/vscode/blob/main/.vscode/notebooks/my-endgame.github-issues and reload the page, does it open as text for you?

**Comment by lramos15** [comment]
I can reproduce. My guess is it has something to do with the extension not being present on restore

**Comment by bpasero** [comment]
This is strange: the first time I did this, the notebook opened as text. But now when I try to open the link, I am always getting put back to the readme as preview 🤯 

Did we somehow miss the ability to deep-link a file on vscode.dev or is it just me?

**Comment by hediet** [comment]
> Did we somehow miss the ability to deep-link a file on vscode.dev or is it just me?

This works for me.

**Comment by lramos15** [comment]
> This is strange: the first time I did this, the notebook opened as text. But now when I try to open the link, I am always getting put back to the readme as preview 🤯

Whenever I click the link I get the notebook as text regardless of having the extension installed 🤔. I don't get the readme preview though.

**Comment by bpasero** [comment]
![Recording 2024-03-25 at 14 51 22](https://github.com/microsoft/vscode/assets/900690/84191b98-34ce-44ed-8daf-4826d874a02f)
