### ISSUE TITLE
Editor picker: Increase visible length and add close buttons

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#20860]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|language-x86-64-assembly|13xforever|2.2.9|
|read-only-indicator|alefragnani|0.6.0|
|alignment|annsk|0.3.0|
|Doxygen|bbenoist|1.0.0|
|vscode-astyle|chiehyu|0.6.2|
|python|donjayamanne|0.5.8|
|EditorConfig|EditorConfig|0.3.4|
|matlab|Gimly81|0.4.0|
|status-bar-tasks|GuardRex|0.2.0|
|vscode-dimmer|hoovercj|2.1.0|
|docthis|joelday|0.3.11|
|cpptools|ms-vscode|0.10.1|
|vscode-clearcase|OpenNingia|1.5.0|
|vscode-icons|robertohuertasm|7.2.0|
|theme-cyanicpastels|SamuelLampa|0.0.9|
|indenticator|SirTori|0.2.1|
|vscode-hexdump|slevesque|1.1.4|
|code-spell-checker|streetsidesoftware|0.14.8|
|comment-snippets|Tobiah|0.2.0|
|dark-plus-material|vangware|0.2.1|
|change-case|wmaurer|1.0.0|
|highlight-trailing-white-spaces|ybaumes|0.0.2|

---

Steps to Reproduce:

1. Open the recent file list using "Ctrl-P edt ".
2. Have to scroll the list because it doesn't show many entries. Could you increase the length of the visible list so it is quicker to see what it loaded. May be the visible length of the list could be configurable.
3. Can't close unwanted files from the list. Have to go to them individually. Would be useful if you could close them directly from the list.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
