### ISSUE TITLE
Problem view shows `.` next to problems in untitled notebooks 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#208692]
Type: <b>Bug</b>

1. Open workspace
1. Create a new notebook
1. Create a syntax or other error in a cell
1. Open problems view

**bug**
There's an extra `.` to the right of the notebook file title

![Image](https://github.com/microsoft/vscode/assets/12821956/33c5d8d2-bed2-4491-a67d-c9f069b94717)

VS Code version: Code - Insiders 1.88.0-insider (Universal) (b0d975fc6370f15570c380f41015b1ca2cdcb791, 2024-03-25T05:50:56.142Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|5, 4, 4|
|Memory (System)|64.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 0fffb5da-9cd7-46fd-9e7f-a1564e8c5fda|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sandy081** [comment]
It is also same in Search

![Image](https://github.com/microsoft/vscode/assets/10746682/a399784f-4dae-40b8-b68d-7f248131b850)

Probably this should be something handled by the [IResourceLabel](https://github.com/microsoft/vscode/blob/fc50081e232a97c51030fd981ddb32514a6d6a24/src/vs/workbench/browser/labels.ts#L78)

CC @bpasero

**Comment by bpasero** [comment]
Its possible to omit `.` in the label widget for `setFile` because there we know we are in a file context and `.` is not very meaningful for descriptions.

But for the problems view there is an explicit call to `setResource` with an explicit description passed in:

https://github.com/microsoft/vscode/blob/002041ffcb3bd264350816d1b32e333e16b98682/src/vs/workbench/contrib/markers/browser/markersTreeViewer.ts#L184-L188

@sandy081 any reason `setFile` is not used?

**Comment by sandy081** [comment]
I do not remember why we have two branches here - `setFile` and `setResource`. Is there a general suggestion for this? 

> Or maybe we need to enlist the cell scheme as well as we do for untitled scheme.

I am looking for this before digging deep. Is there a way to know this?

**Comment by bpasero** [comment]
Yeah I would pick the `setFile` and see what breaks, but maybe there is something in the history of that change that could explain it?

I think schemes are pretty much hardcoded, here unfortunately while the notebook scheme is `untitled`, the cell schemes are not. @rebornix is there a way to know if a cell scheme is untitled?

**Comment by sandy081** [comment]
It goes back before we used to have label service. I was also not showing the `parent` of the resource if the resource has no file provider. Showing parent was introduced [here](https://github.com/microsoft/vscode/pull/156145/files#diff-f0dd526c86231737a63ff7d5ad4f9fe7e50a04d8bc8d94cb68e95fffcd55051b). 

I believe using `setFile` is the right way to go. I also see Search doing the same.
