### ISSUE TITLE
error diagnostics are added to IW cells

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#208681]
1. create and interactive window and run a cell that will cause thow an error eg `print(x)`
🐛 the line that errored in the cell is underlined and an unfixable problem is added to the problems window

can't even delete the cell to remove the error

**Comment by justschen** [comment]
just to confirm this is intended?

before edit:
![Screenshot 2024-03-26 at 4 41 50 PM](https://github.com/microsoft/vscode/assets/54879025/72380aaa-1a5f-44f3-83c9-876473e10f3c)

after edit:
![Screenshot 2024-03-26 at 4 42 07 PM](https://github.com/microsoft/vscode/assets/54879025/28399900-bc6f-42a3-a22f-a0a83f3205e3)

**Comment by amunger** [comment]
yeah, that's from pylance, different issue https://github.com/microsoft/vscode-jupyter/issues/15376

I guess verification should be to run this in the IW, since it won't fail a static check

```
x = 0
y = 1/x
```
