### ISSUE TITLE
Extra space after each character in output pane

### ISSUE THREAD

**Issue by doxxx** [microsoft/vscode#208637]
Type: <b>Bug</b>

In the output panes created by some extensions, such as the Test Results pane from the C/C++/CMake extensions and the various build output panes created by the ESP-IDF extension, sometimes the text in the pane will have an additional space character after each actual character. Drag-selecting text will select both the character and its following space as a unit.

The workaround is to use Ctrl-Plus and Ctrl-Minus to scale the UI up and down, which gets rid of the extra spaces.

More detail can be found in https://github.com/microsoft/vscode-cmake-tools/issues/3514 where I originally filed this issue before I also saw it in the ESP-IDF extension.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (12.49GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/gordon.tyler/dev/Synaptive/ModusV/embeddedfirmware --crash-reporter-id 483b5d19-9f7f-440e-80ae-49c19a066ddd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (79)</summary>

Extension|Author (truncated)|Version
---|---|---
urscript|Ahe|0.1.16
vscode-avalonia|Ava|0.0.31
vscode-changelog-generator|axe|1.0.4
expect|bda|1.0.1
vscode-standardjs-snippets|cap|0.9.0
vscode-diff-viewer|cap|1.5.0
gitignore|cod|0.9.0
systemd-unit-file|coo|1.0.6
python-snippets|cst|0.1.2
vscode-eslint|dba|2.4.4
githistory|don|0.6.20
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
filter-line|eve|2.0.1
vscode-yarn|gam|2.1.0
matlab|Gim|3.0.2
copilot|Git|1.175.0
copilot-chat|Git|0.13.1
gc-excelviewer|Gra|4.2.59
output-colorizer|IBM|0.1.2
bridlensis|idl|1.2.2
nsis|idl|4.2.4
nsis-plugins|idl|1.3.1
nsl-assembler|idl|1.2.1
better-cpp-syntax|jef|1.17.2
vscode-nuget-package-manager|jmr|1.1.6
cmake-language-support-vscode|jos|0.0.9
hex-fmt|ker|1.0.0
cortex-debug|mar|1.12.1
vscode-catch2-test-adapter|mat|4.11.0
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.25
peripheral-viewer|mcu|1.4.6
rtos-views|mcu|0.0.7
rainbow-csv|mec|3.11.0
vscode-docker|ms-|1.29.0
csdevkit|ms-|1.4.29
csharp|ms-|2.22.5
vscode-dotnet-runtime|ms-|2.0.2
vscodeintellicode-csharp|ms-|0.1.26
autopep8|ms-|2023.8.0
debugpy|ms-|2024.2.0
flake8|ms-|2023.10.0
isort|ms-|2023.10.1
pylint|ms-|2023.10.1
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
azure-account|ms-|0.11.6
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.14
powershell|ms-|2024.0.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
ansible|red|2.13.148
vscode-yaml|red|1.14.0
vscode-zipexplorer|sle|0.3.1
slint|Sli|1.5.1
vscode-standard|sta|2.1.3
rewrap|stk|1.16.3
even-better-toml|tam|0.19.2
errorlens|use|3.16.0
vscode-icons|vsc|12.7.0
jinja|who|0.0.8
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.6.2
linkerscript|Zix|1.0.4
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30992801
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470

```

</details>

**Comment by crrapi** [comment]
+1, Also applicable to Java/JUnit tests

**Comment by crrapi** [comment]
Can no longer repro. Maybe fixed? Will update if it comes up again
