### ISSUE TITLE
Placeholder text does not correlate to agent

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#208622]
Testing #208516

![Recording 2024-03-25 at 12 38 56](https://github.com/microsoft/vscode/assets/900690/0800c1e8-877d-4922-87dd-29d71cd24f08)

In the second case I would have expected placeholder text to indicate it.

**Comment by minsa110** [comment]
Yep, but it still "works" as expected even though the placeholder text doesn't change (the one I selected is the one that gets invoked).

Also, for me, the placeholder text changes when I try invoking the chat participant again the second time:

![duplicat chat participants](https://github.com/microsoft/vscode/assets/10833267/41a87a85-e6f4-40c9-9a96-5b1d04965a0d)

**Comment by roblourens** [comment]
I fixed this last week, thanks
