### ISSUE TITLE
API: provide a wrapper for electron `printToPdf` function

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#20869]
Could it be possible to expose the [`printToPdf`](http://electron.atom.io/docs/api/web-contents/#contentsprinttopdfoptions-callback) API provided by electron?
It's very useful for extensions who want to save preview to file.
As a 'native' solution, it's better than that such as [node-html-pdf](https://www.npmjs.com/package/html-pdf) in many aspects (such as quality and no other required lib).

**Comment by simonl65** [comment]
👍

**Comment by neilsustc** [comment]
Close since I realize that this API cannot be used to print editor content.
