### ISSUE TITLE
Inline chat: No history when starting from rewrite

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#208608]
Testing #208411

1. Run `Document using Copilot`

🐛 The widget will lack any history.

<img width="425" alt="image" src="https://github.com/microsoft/vscode/assets/22350/c8b96a8e-49b9-4810-ab6e-04d7639838f3">

**Comment by roblourens** [comment]
Partly it's complicated by the way I have to track the state along with the history text. Also I think I decided that I should be using `HistoryNavigator2` instead of `HistoryNavigator` here. https://github.com/microsoft/vscode/issues/208847 to track that

**Comment by roblourens** [comment]
I think the main issue is too big for this week, but if you really need this changed in inline chat, I can come up with a simple flag to enable that for inline chat since it doesn't have the 'dynamic variables'.
