### ISSUE TITLE
Quick search - button tooltip missing

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#208659]
Testing #208477

The button on the right hand of the search input does not have a tooltip
<img width="712" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/af9d1f92-5d8b-468c-859e-430b7d85def2">

**Comment by andreamah** [comment]
@TylerLeonhardt is there a way to add a tooltip to this button?

**Comment by lszomoru** [comment]
@TylerLeonhardt, let me know when you add that I would like to move the "Refresh" action to re-generate the branch name. Thanks!

**Comment by TylerLeonhardt** [comment]
Now that we have the action menu on the right, I will close this. The big blue button is really for text like "Close" and not for "codicon only" actions.
