### ISSUE TITLE
regression(insiders): `QuickPick.onDidChangeActive()` stopped working

### ISSUE THREAD

**Issue by nkomonen-amazon** [microsoft/vscode#208715]
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.88.0-insider (Universal)
Commit: b0d975fc6370f15570c380f41015b1ca2cdcb791
Date: 2024-03-25T05:50:56.142Z
Electron: 28.2.6
ElectronBuildId: 27476517
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.3.0
```

The latest insiders has a regression with `QuickPick.onDidChangeActive()`.
Probably connected to #207863 cc @TylerLeonhardt.

Our extension has CI that has started failing a couple weeks ago but nothing has changed on our end.

Steps to Reproduce:

1. From some manual testing, setting `QuickPick.value` has stopped triggering `onDidChangeActive()`.
I'm not sure if this applies to all actions that should trigger onDidChangeActive() 

Please let me know if this isn't enough information to reproduce ([our specific failing test](https://github.com/aws/aws-toolkit-vscode/blob/cf3f0fe020370ed80f55c7f4aba8f3691e8ce73c/packages/core/src/test/shared/ui/pickerPrompter.test.ts#L363))

**Comment by TylerLeonhardt** [comment]
@nkomonen-amazon `.value` is the input box. `.onDidChangeActive` would only fire if the active item changed. Is the active item changing in your case after setting the value and not firing the event?

**Comment by nkomonen-amazon** [comment]
Did a small test, I don't think `onDidChangeActive` is getting triggered at all. Ignoring `.value` completely, changing the `activeItems` triggers `onDidChangeActive` in Stable but not Insiders.

```typescript
it('test onDidChangeActive', async function () {
    const quickpick = vscode.window.createQuickPick()
    
    // Problem: this gets triggered on `Stable` but not `Insiders`
    quickpick.onDidChangeActive((e) => {
        console.log('ActiveChanged!')
    })
    
    // we will await this at the end of the function to ensure our test doesn't complete early
    const capturedEvent = captureEventOnce(quickpick.onDidChangeActive)

    // we must first show the QuickPick so the following line will trigger onDidChangeActive
    quickpick.show()
    // this triggers `onDidChangeActive` on `Stable` but not `Insiders` 
    quickpick.activeItems = [{label: 'nikolas'}]

    // wait for the onDidChangeActive event to be emitted
    await capturedEvent
})

/**
 * Captures the first value emitted by an event, optionally with a timeout
 */
function captureEventOnce<T>(event: vscode.Event<T>, timeout?: number): Promise<T> {
    return new Promise<T>((resolve, reject) => {
        const stop = () => reject(new Error('Timed out waiting for event'))
        event(data => resolve(data))

        if (timeout !== undefined) {
            setTimeout(stop, timeout)
        }
    })
}
```

**Comment by TylerLeonhardt** [comment]
@nkomonen-amazon so, this sample's behavior is accurate in Insiders... and Stable's behavior is wrong.

So, you don't set `.items` at all... So when the quick pick is shown, **there is no actual active item**

but then you set it to `{label: 'nikolas'}` which **is not an actual item** in `.items` so that is basically the equivalent of just setting `.activeItems` to nothing as well.

but it's already nothing... so no event fires.

If you set `quickpick.items = [{ label: 'foo' }]` before setting the `activeItems` this _does_ trigger the `quickpick.onDidChangeActive` because `.activeItems` goes from `{ label: 'foo' }` (because it sets the first item to the active item by default) and then to `[]`.

**Comment by nkomonen-amazon** [comment]
@TylerLeonhardt thanks for the confirmation.

So just to reiterate
- `Stable`'s implementation of `.activeItems` also appending to `.items` if the items did not exist in `.items` is wrong.
- Going forward, if we set `.activeItems` and the item does not also exist in `.items` then nothing happens

Our tests that relied on the behavior of `Stable` are a few years old, so this may be worth pointing out to devs somewhere now that it is being changed (if not already).

**Comment by nkomonen-amazon** [comment]
@TylerLeonhardt thanks for the confirmation!
