### ISSUE TITLE
seeing `provideDiagnostic` in console latest insiders

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#208737]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

I'm not sure what triggers this, but after a while of doing some work in OSS and in insiders, I see the following:
![Screenshot 2024-03-25 at 3 08 51 PM](https://github.com/microsoft/vscode/assets/54879025/58f00e54-9791-4c14-a5d6-7bd51417b74e)

saw @ulugbekna did some work with provideDiagnostics recently?

**Comment by ulugbekna** [comment]
Nope, that's not me. Given you the console.log comes from the extension host and this's OSS (which likely doesn't have extensions outside built-in ones), I suspect this PR might be at fault - https://github.com/microsoft/vscode/pull/207577/files @aeschli

**Comment by aeschli** [comment]
Got fixed here: https://github.com/microsoft/vscode/pull/208474/files
