### ISSUE TITLE
sendText sends command twice in new terminals during onDidChangeTerminalShellIntegration

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#208736]
Testing #208462

In my onDidChangeTerminalShellIntegration handler, I have the following line:
`e.terminal.sendText('echo "Hello shell integration!"', true);`

I notice that when I start my extension, a terminal is already open, and text is not sent to that terminal. Whenever I start another terminal, I notice that the command is placed into the terminal twice and is run each time.

If I change the `true` to `false`, I notice that text is still not sent to the already-open terminal, but that for new terminals, the text is pasted in twice as well, so I get `echo "Hello shell integration!"echo "Hello shell integration!"` in the new terminal.

**Comment by Tyriar** [comment]
This is actually by design, when the shell isn't ready to accept input it just echos the text. The first text is the echoed text, the second is the actual input
