### ISSUE TITLE
Exited with error code -532462766

### ISSUE THREAD

**Issue by emilianemm** [microsoft/vscode#208757]
Type: <b>Bug</b>

Hello,

After I updated VS Code I recieve this error when trying to run dotnet watch --no-hot-reload

dotnet watch ❌ Exited with error code -532462766
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...

Please help me.

Thank you

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.98GB free)|
|Process Argv|--crash-reporter-id 09210121-89ec-4d9a-803e-abb4cb265294|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
ng-template|Ang|17.3.1
quick-html-previewer|dai|1.0.1
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.5.0
live-html-previewer|hdg|0.3.0
vscode-nuget-package-manager|jmr|1.1.6
csharpextensions|kre|1.7.3
csdevkit|ms-|1.4.29
csharp|ms-|2.22.5
vscode-dotnet-runtime|ms-|2.0.3
vscodeintellicode-csharp|ms-|0.1.26
vscode-edge-devtools|ms-|2.1.5
vscode-nuget-gallery|pat|0.0.24
material-icon-theme|PKi|4.34.0
html-preview-vscode|tht|0.2.5
cors-browser|Wsc|1.0.11

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627cf:30244335
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30998029
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonaic:30996667
7ghi1836:30988842
dsvsc021:30996838
g1icg217:30999571

```

</details>

**Comment by justschen** [comment]
@emilianemm does this happen with the same extension on a previous vs code version?

**Comment by emilianemm** [comment]
it happened only after the last update. I solved it by running dotnet dev-certs https and dotnet dev-certs https --trust
