### ISSUE TITLE
When attempting to install Visual Studio Code from the Microsoft Store using WinGet, it installs version 1.83.1 instead of version 1.87.2.

### ISSUE THREAD

**Issue by jagadeish** [microsoft/vscode#208770]
**Issue:**
When attempting to install Visual Studio Code from the Microsoft Store using WinGet, it installs version 1.83.1 instead of version 1.87.2.

**Steps to Reproduce:**

1. Open a PowerShell command prompt and execute the following command line:
**winget search "Visual Studio Code"**

![image](https://github.com/microsoft/vscode/assets/64662882/a4a27ac3-3e33-4135-aa40-f486c28b0868)

The version is unknown in the output.

2. Execute the following command line to install Visual Studio Code from the Microsoft Store:
winget install --id=XP9KHM4BK9FZ7Q --source=msstore

3. As evident in the screenshot below, the aforementioned command is attempting to install Visual Studio Code version 1.83.1 instead of the latest version, which is 1.87.2.

![image](https://github.com/microsoft/vscode/assets/64662882/5a218f99-c10d-44bf-a423-bc349a5978ed)

It seems that Visual Studio Code is not updated to the latest version in the Microsoft Store.

**Comment by joaomoreno** [comment]
1.83.1 was the last release for Windows **32-bit**, I suspect this is the release you're getting.

@sbatten let's go ahead and remove 32-bit from the store.

**Comment by sbatten** [comment]
I have confirmed that the same messaging shows on a 64-bit windows machine. Also, we don't ship a 32-bit version to the Microsoft store. While the messaging says 1.83.1, we always get the latest version. In this case, it shows 1.83.1 but installs 1.87.2. I'm investigating where it gets the 1.83.1 version from as we don't specify that in our store listing.

**Comment by sbatten** [comment]
@denelon Where does winget retrieve the version information for msstore published applications. Specifically in VS Code's case where the package we ship in the store is actually an installer with a version that does not get updated at the cadence of VS Code releases.

**Comment by rzhao271** [comment]
The issue seems to be resolved. I'm seeing 1.96.0 show up.

**Comment by sbatten** [comment]
`winget install --id=XP9KHM4BK9FZ7Q --source=msstore`

still shows the wrong version... it will still install the latest version, but it shows the wrong version in the confirmation screen from OP.

@denelon https://github.com/microsoft/vscode/issues/208770#issuecomment-2024152487 still holds
