### ISSUE TITLE
VSCode server stable version is not available

### ISSUE THREAD

**Issue by KarKLi** [microsoft/vscode#208753]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2
- OS Version:  Linux karkli 5.4.119-19.0009.37 # 1 SMP Wed Oct 18 12:32:51 CST 2023 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1.  Connect to a Linux machine by SSH.
2. Install vscode server and get failed.

The log shown that VSCode server 'stable' version selected and download got 404:
[12:17:46.714] Using commit id "863d2581ecda6849923a2118d93a088b0745d9d6" and quality "stable" for server
[12:17:46.717] Install and start server if needed
<other logs...>
[12:17:52.409] > Acquiring lock on /root/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d
> 9d6/vscode-remote-lock.root.863d2581ecda6849923a2118d93a088b0745d9d6
> Installing to /root/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6.
> ..
> 93faf59d392f%%1%%
> Downloading with wget
[12:17:52.635] > wget download failed
> https://update.code.visualstudio.com/commit:863d2581ecda6849923a2118d93a088b0745
> d9d6/server-linux-legacy-x64/stable: 2024-03-26 12:17:52 ERROR 404: Not Found.

**Comment by zergtant** [comment]
same for me
`
[16:31:22.964] Got request to download on client for {"artifact":"server-linux-legacy-x64","destPath":"/home/tant/.vscode-server/bin//863d2581ecda6849923a2118d93a088b0745d9d6/vscode-server.tar.gz"}

wget download failed
> https://update.code.visualstudio.com/commit:863d2581ecda6849923a2118d93a088b0745d9d6/server-linux-legacy-x64/stable: 2024-03-27 16:31:23 error 404：Not Found。
`

**temp solution**

download tar (change  `server-linux-legacy-x64 ` to `server-linux-x64` ):

https://update.code.visualstudio.com/commit:863d2581ecda6849923a2118d93a088b0745d9d6/server-linux-x64/stable

2. unzip and copy all file to ‘/home/[user]/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/’
  if '863d2581ecda6849923a2118d93a088b0745d9d6' EXISTS  delete it .

it work for me.

and my env is :
VS Code Version: 1.87.2

OS Version: CentOS Stream release 9
Linux version 5.14.0-226.el9.x86_64 (mockbuild@x86-05.stream.rdu2.redhat.com) (gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4), GNU ld version 2.35.2-33.el9) #1 SMP PREEMPT_DYNAMIC Fri Dec 23 16:16:30 UTC 2022

**Comment by KarKLi** [comment]
> same for me ` [16:31:22.964] Got request to download on client for {"artifact":"server-linux-legacy-x64","destPath":"/home/tant/.vscode-server/bin//863d2581ecda6849923a2118d93a088b0745d9d6/vscode-server.tar.gz"}
> 
> wget download failed
> 
> > https://update.code.visualstudio.com/commit:863d2581ecda6849923a2118d93a088b0745d9d6/server-linux-legacy-x64/stable: 2024-03-27 16:31:23 error 404：Not Found。
> > `
> 
> **temp solution**
> 
> download tar (change `server-linux-legacy-x64 ` to `server-linux-x64` ):
> 
> https://update.code.visualstudio.com/commit:863d2581ecda6849923a2118d93a088b0745d9d6/server-linux-x64/stable
> 
> 2. unzip and copy all file to ‘/home/[user]/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/’
>    if '863d2581ecda6849923a2118d93a088b0745d9d6' EXISTS  delete it .
> 
> it work for me.
> 
> and my env is : VS Code Version: 1.87.2
> 
> OS Version: CentOS Stream release 9 Linux version 5.14.0-226.el9.x86_64 ([mockbuild@x86-05.stream.rdu2.redhat.com](mailto:mockbuild@x86-05.stream.rdu2.redhat.com)) (gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4), GNU ld version 2.35.2-33.el9) #1 SMP PREEMPT_DYNAMIC Fri Dec 23 16:16:30 UTC 2022

This is a temporary but useful solution. I am wondering why the link is unavailable and if there is any automatic solution.

**Comment by KarKLi** [comment]
BTW, it works for me, thx 👍 @zergtant

**Comment by zergtant** [comment]
> and




> > same for me ` [16:31:22.964] Got request to download on client for {"artifact":"server-linux-legacy-x64","destPath":"/home/tant/.vscode-server/bin//863d2581ecda6849923a2118d93a088b0745d9d6/vscode-server.tar.gz"}
> > wget download failed
> > > https://update.code.visualstudio.com/commit:863d2581ecda6849923a2118d93a088b0745d9d6/server-linux-legacy-x64/stable: 2024-03-27 16:31:23 error 404：Not Found。
> > > `
> > 
> > 
> > **temp solution**
> > download tar (change `server-linux-legacy-x64 ` to `server-linux-x64` ):
> > https://update.code.visualstudio.com/commit:863d2581ecda6849923a2118d93a088b0745d9d6/server-linux-x64/stable
> > 
> > 2. unzip and copy all file to ‘/home/[user]/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/’
> >    if '863d2581ecda6849923a2118d93a088b0745d9d6' EXISTS  delete it .
> > 
> > it work for me.
> > and my env is : VS Code Version: 1.87.2
> > OS Version: CentOS Stream release 9 Linux version 5.14.0-226.el9.x86_64 ([mockbuild@x86-05.stream.rdu2.redhat.com](mailto:mockbuild@x86-05.stream.rdu2.redhat.com)) (gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4), GNU ld version 2.35.2-33.el9) #1 SMP PREEMPT_DYNAMIC Fri Dec 23 16:16:30 UTC 2022
> 
> This is a temporary but useful solution. I am wondering why the link is unavailable and if there is any automatic solution.

I don't know exactly why. But I guess because there were some problems with checking the os version.

CentOS Stream release 9 was detected as server-linux-**legacy**-x64

**Comment by connor4312** [comment]
This is fixed with our stable release yesterday.
