### ISSUE TITLE
Present Restart to Update action in gear context menu only after extensions are installed 

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#208742]
Testing #208185

What I observed when trying to update VS Code

1. Gear icon shows a pending icon (indicating it's installing updates)
2. It shows "1" when the download is done, indicating I can restart VS Code to update now
3. Now it starts to download/update extensions

Considering that 3 can take some time, users might accidentally restart VS Code after 2 is done. I wonder if we want to move step 2 after 3.

**Comment by Sithusoelwin35** [comment]
#208742

**Comment by sandy081** [comment]
This was thought about and we do not want to have VS Code update blocked on extensions update. Main purpose of this feature is to increase the probability of getting extensions updated on VS Code update and not to completely tie them together.
