### ISSUE TITLE
Ctrl+Alt+Enter to run code block in terminal doesn't do anything if terminal wasn't already open

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#208707]
Testing #207637

1. Close all terminals
2. Ask Copilot for a shell command
3. Ctrl+Alt+Enter to run it in the terminal
4. :bug: a terminal opens but the command isn't appended to the prompt, I have to move focus back into the block I wanted to run in Chat and hit Ctrl+Alt+Enter again

**Comment by Tyriar** [comment]
I hoped I fixed this on Friday 😦 https://github.com/microsoft/vscode/pull/208425

@joyceerhl how long does your shell take to start up, and do you have shell integration on? A gif would be very helpful

**Comment by joyceerhl** [comment]
I do have shell integration and the shell does take a couple seconds to start up (I have no shell customizations, this is just Windows + pwsh)

![Image](https://github.com/microsoft/vscode/assets/30305945/7a2e74b4-9800-4585-bf03-e5c1ec776fa9)

**Comment by joyceerhl** [comment]
I'm on the Insiders from 15 hours ago so should have your fix already

**Comment by Tyriar** [comment]
Looking at the gif I think this is happening because your powershell takes a really long time to start up and we have a 2s cap on that currently:

https://github.com/microsoft/vscode/blob/08d545fff55349100a8a7db6b38212ffa8021fb7/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L842

**Comment by Tyriar** [comment]
I don't think we should do anything for this as making that timeout longer means terminals without shell integration would need to wait that long. @joyceerhl you might want to look in to why powershell takes so long to startup
