### ISSUE TITLE
How to show suggestion every key input using provideCompletionItems?

### ISSUE THREAD

**Issue by bokuweb** [Microsoft/vscode#20870]
- VSCode Version: 1.9.1
- OS Version: 10.11.6

Is there a way to show my custom suggestion every key input using provideCompletionItems?
Suggestion is not always displayed.

- My extension code.

``` typescript
'use strict';

import { languages, TextDocument, ExtensionContext, CompletionItem, Position } from 'vscode';

export function activate(context: ExtensionContext) {
    context.subscriptions.push(languages.registerCompletionItemProvider('*', {
        provideCompletionItems(document: TextDocument, position: Position) {
            return [new CompletionItem('hello world')];
        }
    }));
}
```

Suggestion test in `test.ts`

- case 1. input `h` => `hello world ` is not displayed.
![2017-02-19 11 17 08](https://cloud.githubusercontent.com/assets/10220449/23098581/054f1036-f695-11e6-9479-7463238f30d7.png)

- case 2. input `let h` => `hello world` is displayed.
![2017-02-19 11 18 17](https://cloud.githubusercontent.com/assets/10220449/23098585/24fc7414-f695-11e6-8964-5e5234e453e7.png)

- case 3. input `let h = h` => `hello world ` is not displayed.
![2017-02-19 11 19 19](https://cloud.githubusercontent.com/assets/10220449/23098587/4b6450cc-f695-11e6-82ee-02fd0af363c1.png)

I want to show my custom suggestion in every case.
But above case1 and case3 is not called  `provideCompletionItems`

Thanks

**Comment by jrieken** [comment]
In suggest it depends on how you register your provider. It a little complicated by we have a rule that the language selector (in your sample `*`) gets assigned a [score](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4214). For completions we have a rule that we sort providers by score and ask them in that order. When a group of higher ranked providers produces a result we don't ask other providers anymore (case 1 and 3). When no results are produced we continue with the next rank (case 2).  We have these rules in place to ensure that language specific completion take precedence. 

You can change your registration to use the language name which will give you a higher rank, like `registerCompletionItemProvider('typescript', ...)` or `registerCompletionItemProvider(['typescript', 'javascript'], ...)`. 

Hope that answers your question. Happy coding.
