### ISSUE TITLE
Don't update or ask to update file content if it is changed on file system

### ISSUE THREAD

**Issue by amitguptagwl** [Microsoft/vscode#20876]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 14.1

Steps to Reproduce:

1. Open some file in vscode editor. Do some changes.
2. Go to command line. Revert the changes using GIT GUI.
3. come back to vscode. It doesn't change the file contents. I doesn't event prompt that the file has been changed on file system, do you want to reload? or something similarly.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14298

**Comment by amitguptagwl** [comment]
Both issues are slightly different. issue #14298 says that the contents of files are changed without prompt. While this issue says that the contents of the files are not being changed even when the file is externally modified.

**Comment by bpasero** [comment]
@amitguptagwl maybe I misunderstood the issue. you actually say that you changed the file outside and this change was not reflected in the editor? so you actually want it to update but it did not happen?

**Comment by amitguptagwl** [comment]
So as I mentioned, I done some changes in a file. saved the changes. open `git gui`. reverted the changes. I came back to vscode editor. Neither it prompts me that the file has been changed on the disk nor it loaded the new contents. Now when I closed the file it asked me to save the changes which confused me as I have already reverted the changes.

**Comment by bpasero** [comment]
@amitguptagwl to be clear: you had changes (not saved) in the file and you reverted the file via git and now you would expect that the dirty file is also being reverted as a matter of that?

**Comment by amitguptagwl** [comment]
Both ways it is behaving same.

1. I have saved changes -> I reverted file via git -> vscode did nothing (some prompt expected) -> I closed file in vscode -> it asked me to save the changes again (not expected)
2. I have saved and unsaved changes -> I reverted file via git -> vscode did nothing (some prompt expected) -> I closed file in vscode -> it asked me to save the changes again (not expected)

**Comment by bpasero** [comment]
@amitguptagwl got it

**Comment by cretace** [comment]
Same issue - I edited a file in VS code then used FTP to load back the original file.
I got no message in VS Code to say the file had been changed.
Not good.
It should say "the file has been edited externally" and show options to either keep or lose the edits.

**Comment by jcrben** [comment]
@bpasero I run into this on a daily basis as I switch branches and my dirty files aren't refreshed so I go back and edit them a bit only to create a conflict. Getting more wise about it lately... thoughts about prioritizing this? Seems like it would be a common issue.

**Comment by bpasero** [comment]
Renaming this back to the original title, I think the issue here is missing file events when doing operations outside of VSCode, e.g. git.

**Comment by dmlemos** [comment]
I have this issue. If files get changed on disk (with git), VS Code doesn't update them. Most of the times I just have to refresh the explorer.

**Comment by jcrben** [comment]
fyi, I'm no longer seeing this on macOS 10.12.6

**Comment by dmlemos** [comment]
Now I started seeing an new issue. When renaming a file via VS Code, sometimes it doesn't acknowledged it and I have to force refresh the explorer.

Using 1.22.2
