### ISSUE TITLE
Takes Too long Time to compile 

### ISSUE THREAD

**Issue by sakshisinghhh** [microsoft/vscode#208774]
Type: <b>Bug</b>

Every time i run c program it takes soo much time to compile and most of the time it doestnot complete its run also

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.74GB (0.57GB free)|
|Process Argv|--crash-reporter-id ce4f70b2-9847-459a-9583-c7477209df72|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
project-manager|ale|12.7.0
npx-scripts|arc|1.0.7
code-gnu-global|aus|0.2.2
tailwindshades|bou|0.0.5
bracket-pair-color-dlw|Bra|0.0.6
vscode-tailwindcss|bra|0.10.5
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
gitignore|cod|0.9.0
vscode-eslint|dba|2.4.4
git-extension-pack|don|0.1.3
githistory|don|0.6.20
ink-vscode-snippets|dot|0.0.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.9.0
prettier-vscode|esb|10.4.0
vscode-firefox-debug|fir|2.9.10
linter|fna|0.0.19
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
c-cpp-runner|fra|9.4.7
next-js-snippets|hou|1.0.0
cpptask|kay|0.0.1
start-git-bash|McC|1.2.1
eclipse-new-java-project|mel|1.0.1
vscode-styled-components|mf|0.2.2
vscode-language-babel|mgm|0.0.40
csharp|ms-|2.22.5
vscode-dotnet-runtime|ms-|2.0.3
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
vscode-typescript-next|ms-|5.5.20240325
vscode-react-native|msj|1.13.0
material-icon-theme|PKi|4.34.0
vscode-thunder-client|ran|2.20.0
java|red|1.28.1
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
vs-code-prettier-eslint|rve|6.0.0
projectmanager|Skr|1.1.3
vscode-styled-components|sty|1.7.8
prettier-plus|svi|4.2.2
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.5
vscode-java-pack|vsc|0.25.2024032507
vscode-maven|vsc|0.44.0
json|Zai|2.0.2
vscode-react|zha|0.0.5
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30998029
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:30996668
7ghi1836:30988842
dsvsc021:30996838
g1icg217:30999571

```

</details>

**Comment by roblourens** [comment]
Sounds like this is either an issue with your setup or with an extension you're using, but much more detail would be needed
