### ISSUE TITLE
Suggestion: keybinding to move between separators of the quick search view could move to "more..." 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#208727]
Testing #208367

This is just a suggestion as I was trying out the new keybinding, feel free to close it if it's out of scope or not a good suggestion :p 

As I was playing around with the quick search list and it returned a large results list, I thought it'd ben nice if when navigating between separators using the new keybindings, I could also navigate to to "More..." directly:

 
![quicksearchnavigation](https://github.com/microsoft/vscode/assets/45497113/96d5e96f-48eb-45e3-b788-a193292ecd1b)

**Comment by TylerLeonhardt** [comment]
I don't particularly wanna be in the business of giving quickpicks control of what `cmd+up/down` does.. because that will introduce inconsistencies... so in order to do this, the quick search would need to separate the More's perhaps with a blank inline separator.

@andreamah would make this decision.

**Comment by andreamah** [comment]
Hmm, I wonder if there's a way to set another keybinding for this? One that's not `cmd+up/down`. Not sure which keybinding would be best in this case.

**Comment by TylerLeonhardt** [comment]
You do have the ability to set a context key for a specific picker FWIW... so you _could_ have a unique keybinding. Not sure if it's worth it though.

**Comment by andreamah** [comment]
I'm not sure whether this keybinding would be used a lot. If someone wants to see the results in the search view, they can click the action button beside one of the entries. I'll close this for now, unless there is another use case for this. Thanks!
