### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by exodus1937** [Microsoft/vscode#20875]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|Handlebars|andrejunges|0.2.0|
|ccd-typescript|codechemistry|0.1.2|
|sass-lint|glen-84|0.0.3|
|beautify|HookyQR|0.7.3|
|view-in-browser|qinjia|0.0.3|
|sass-helper|ramyaraoa|0.0.2|
|sass-indented|robinbentley|1.3.0|
|java-snippets|tushortz|0.0.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
Sorry, we don't have a crystal ball and don't know what you have meant by this issue. Please update the issue with steps to reproduce and we will reopen it.
