### ISSUE TITLE
"Rename Symbol" in unsaved file

### ISSUE THREAD

**Issue by redstrike** [Microsoft/vscode#20872]
- VSCode Version: **1.9.1**
- OS Version: **Windows 10 Pro x64 v1607**

**Steps to Reproduce:**
1. Open VS Code, then create a new file [Ctrl + N]
2. Copy & Paste some sample codes.
3. Try to rename a symbol by using F2 / "Rename Symbol" feature.

**Expected:** we can quickly rename the symbol in the current tab / file.
**Actual:** See a warning _"File not found (\untitled:Untitled-1)"_

**User Story:**
I was so glad to know that [Hot Exit feature](https://code.visualstudio.com/updates/v1_8#_hot-exit) has been added to VS Code since version 1.8.1 (I like this feature since the last time with Sublime Text). I usually write some codes in draft mode and throw them after done. Ex: playground, solving coding challenges. Although I will throw them away, I still want to refactor them while coding and make the code easier to read. So, I hope the intelligent of "Rename Symbol" feature would be improved soon.

**Edit:** After sent this issue, I suddenly realize that I could save a playground file on my Desktop to support my use cases. However, it still depends on VS Code Team's decision to improve this feature or not.

**Comment by jrieken** [comment]
@redstrike That depends on the language service doing the job. Some support unsaved files, some don't. Which language did you encounter this?

**Comment by redstrike** [comment]
Oh, I see. They are TypeScript and JavaScript.

**Comment by mjbvz** [comment]
This should be fixed in the current insiders builds. We've improved support for working with untitled JavaScript and TypeScript files. Please give it a try a let me know if you run into any issues
