### ISSUE TITLE
Go to symbol displays symbols from a11y help

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#208705]
Testing #207637

1. Have a11y help open 
2. Shift+Ctrl+O to go to symbol
3. :bug: I get 'symbols' from the a11y help text, I would have expected that the a11y help went away and that the symbols would be those from the chat view

![Image](https://github.com/microsoft/vscode/assets/30305945/c4c59b77-b336-4597-a35c-465bb94c0fd4)

**Comment by meganrogge** [comment]
We want go to symbol to work in the help dialog / accessible view, depending on which is open.
