### ISSUE TITLE
inline chat HC themes input contrast is very low

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#208708]
Testing #208414
![Image](https://github.com/microsoft/vscode/assets/29464607/822a95cd-5371-43da-9504-e5cbb008e5ea)

![Image](https://github.com/microsoft/vscode/assets/29464607/02a99e5a-4ace-4b03-9f4a-615c78e5d11a)

**Comment by meganrogge** [comment]
doesn't reproduce in the panel chat

**Comment by roblourens** [comment]
This isn't nice but there's actually no other way to override the foreground color of an editor- because typically you have syntax highlighting. We do this for all the other "input box"-style editors. I think I opened a feature request when I did this. We should align this rule with your rule for coloring the decoration so that it can override it properly.

**Comment by meganrogge** [comment]
labeling `bug` so it gets verified

**Comment by jrieken** [comment]
Thanks @roblourens

**Comment by meganrogge** [comment]
@roblourens in the latest insider's, still seeing this

![Image](https://github.com/microsoft/vscode/assets/29464607/029cf130-b31d-4462-a869-116d2c24df13)

![Image](https://github.com/microsoft/vscode/assets/29464607/3e0837fb-aa1c-4b0a-b40a-13aec7b36cdf)

**Comment by jrieken** [comment]
There is two separate issues with different steps. There is difference between rendering of slash command and normal prompt text. @meganrogge the only useful/visible information in the original issue description is slash commands (please use words and not images to describe issues!). For verification you have not used slash commands but normal prompt text which is a different case. Please file a separate issue, use words/steps and don't rely on screen captures with just white and white text

**Comment by jrieken** [comment]
Steps to reproduce/verify

* use HC light and dark theme
* open inline chat and type a slash command, e.d `/doc`
* make sure the command is readable when selecting its text
