### ISSUE TITLE
Allow WebviewPanel in secondary window

### ISSUE THREAD

**Issue by triwav** [microsoft/vscode#208790]
I would like to be able to take a WebviewPanel and move or copy it into a new window. Currently these options show up
<img width="299" alt="image" src="https://github.com/microsoft/vscode/assets/1753881/e8662227-0c15-47af-888c-90aec8fac862">
but when I proceed I get `This type of editor cannot be opened in other windows yet.`
<img width="551" alt="image" src="https://github.com/microsoft/vscode/assets/1753881/a0498b80-d1fa-4131-bb80-2daee7181ab5">

Is there any timeline for when this ability will be added?  The text yet makes it seem like it is planned at some point. Thank you.

**Comment by gjsjohnmurray** [comment]
This will become possible in 1.88 which is expected to release next week. You can already try the features by installing Insiders alongside the general release version (aka "Stable")
