### ISSUE TITLE
Periodic warning messages in Git output channel

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#208782]
Type: <b>Bug</b>

```log
2024-03-26 14:00:06.135 [info] > git config --local branch.main.github-pr-owner-number [55ms]
2024-03-26 14:00:06.135 [warning] git config failed: Failed to execute git
2024-03-26 14:05:06.434 [info] > git config --local branch.main.github-pr-owner-number [144ms]
2024-03-26 14:05:06.437 [warning] git config failed: Failed to execute git
2024-03-26 14:10:06.569 [info] > git config --local branch.main.github-pr-owner-number [68ms]
2024-03-26 14:10:06.572 [warning] git config failed: Failed to execute git
2024-03-26 14:15:06.717 [info] > git config --local branch.main.github-pr-owner-number [85ms]
2024-03-26 14:15:06.719 [warning] git config failed: Failed to execute git
```

VS Code version: Code - Insiders 1.88.0-insider (5d8491d7130d25aae121eeaa1633603ef8faa39e, 2024-03-26T05:49:49.370Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (0.41GB free)|
|Process Argv|--enable-proposed-api intersystems-community.vscode-objectscript --enable-proposed-api georgejames.intersystems-serverdiff|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
tsl-problem-matcher|amo|0.6.2
open-in-github-button|ant|0.1.1
vscode-opennewinstance|chr|0.0.12
vscode-eslint|dba|2.4.4
githistory|don|0.6.20
prettier-vscode|esb|10.4.0
vscode-open-in-github|fab|2.2.1
intersystems-dxjetpack|geo|0.1.2
searchable-debug-console|geo|0.0.2
thefoldingstuff|geo|0.2.1
codespaces|Git|1.16.17
copilot|Git|1.175.0
copilot-chat|Git|0.14.2024032601
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.82.1
vscode-memfs|gjs|0.0.3-182309
vscode-favorites|how|1.11.0
rest-client|hum|0.25.1
vscode-pr-pinger|jri|0.0.6
workspace-storage-cleanup|meh|1.1.5
vscode-docker|ms-|1.29.0
debugpy|ms-|2024.3.10861015
python|ms-|2024.3.10861011
vscode-pylance|ms-|2024.3.2
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-powertoys|ms-|0.1.0
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.110.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.0
azure-account|ms-|0.11.6
extension-test-runner|ms-|0.0.6
hexeditor|ms-|1.9.14
live-server|ms-|0.4.13
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
vscode-github-issue-notebooks|ms-|0.0.130
vscode-js-profile-flame|ms-|1.0.8
vscode-markdown-notebook|ms-|0.0.26
vscode-selfhost-test-provider|ms-|0.3.25
vscode-speech|ms-|0.7.2024032017
material-icon-theme|PKi|4.34.0
material-product-icons|PKi|1.7.0
vscode-thunder-client|ran|2.20.0
vscode-xml|red|0.26.1
rest-book|tan|6.2.1
luna-paint|Tyr|0.16.0

(1 theme extensions excluded)

</details>

**Comment by lszomoru** [comment]
Adding @alexr00 as I believe these calls are coming from GHPRI extension that use the git extension API. The error occur as the configuration that is attempted to be read does not exist.

**Comment by alexr00** [comment]
@lszomoru GHPR uses the git config to store which branches have a known PR associated with them. We then check for that value with `getConfig` later. If the value doesn't exist, then we know we need to check GitHub to see if a new PR has been created with this branch. I don't think there's a way to simply check for the existence of a git config value with the git extension API, so we can't avoid this warning right now. We could add more git extension API to introduce a `hasConfig` method if we want to remove this warning.

**Comment by lszomoru** [comment]
Thanks @alexr00. I will go ahead and close this issue as designed for now.
