### ISSUE TITLE
[Bug Transfer from vscode-dotnettools] Contextual UI for test results doesn't render correctly 

### ISSUE THREAD

**Issue by ocallesp** [microsoft/vscode#208714]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.87.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.22631

Original issue:
https://github.com/microsoft/vscode-dotnettools/issues/956

Describe the Issue
See below rendering of right click on the red X icon near LOC 226
![image](https://github.com/microsoft/vscode/assets/510598/d4af25b9-bf0f-435c-9b46-28f2a8df33c7)

Steps To Reproduce
- Spin up a codespaces for this repo https://github.com/Azure/bicep
- Run the test: TryAddProperty_adds_object_properties

Expected Behavior
You can see the test results in the UI

Environment Information
OS: Host: Windows, Codespace: Linux

**Comment by andreamah** [comment]
For the original repro steps, is the C# Dev Kit extension the only extensions needed to detect the tests? I can't seem to get the test explorer to detect the tests in the Bicep repo

**Comment by connor4312** [comment]
The way to verify this is to have multiple test with a multi-line name on the same line (yes it's weird) on a platform where custom context menus are used (not macOS). In the VS Code repo for example:

```
test('has\nClass2', () => {}); test('has\nClass3', () => {});
```
