### ISSUE TITLE
Coverage Sidebar not showing file elements as expandable

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#208724]
Testing #208463

Gave the API a try, everything worked great except I do not have a twistie for the file in the coverage sidebar which means I cannot see or expand any statement coverage. Here is the code I wrote and a branch with those changes:

https://github.com/eleanorjboyd/vscode-python/tree/coverage-demo-tpi
![Screenshot 2024-03-25 at 12 28 50 PM](https://github.com/microsoft/vscode/assets/26030610/ea0b0bbb-d042-4e4e-a9fe-4a8a5b3b028f)

**Comment by connor4312** [comment]
`loadDetailedCoverage` is expected to be set 'globally' for the profile, not per-test. A common implementation might be to store a `WeakMap<vscode.TestRun, SomeObjectWithAdditionalData>` and then use that to implement loadDetailedCoverage. I'll clarify that in the docs for the method.
