### ISSUE TITLE
UI glitch with inline chat 

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/vscode#208739]
Testing #208411

See the video for detailed repro steps, but there are glitches, especially while typing multi-line for inline chat, the focus goes back and forth between what I am typing and the beginning of the inline chat prompt. 

https://github.com/microsoft/vscode/assets/62267334/c3ef18e3-6f9c-49eb-9c5d-fbde39af4e14

**Comment by jrieken** [comment]
This issue lacks

* the full prompt you are typing

**Comment by jrieken** [comment]
@anthonykim1 please add details

**Comment by anthonykim1** [comment]
Exact/full prompt I am typing: 
```
import python ast and import python basic math library that I can use to insert in the current file
```
Github copilot version: v1.176.0
Github copilot chat version: v0.14.2024032601
Insider version: Version: 1.88.0-insider 

command + i (control +i on windows) and typing multi-line prompts have focuses move back and forth between multi-line prompt and beginning of the prompt.

**Comment by jrieken** [comment]
Thanks for clarifying. This should be better since the widget now resizes when multiple lines are received. Tho, once it reaches its max height it still fails to reveal the end/final line. Leaving that for April

**Comment by jrieken** [comment]
Folding this into https://github.com/microsoft/vscode-copilot/issues/6649#issuecomment-2225007522 for which we finally found out the root cause
