### ISSUE TITLE
Does DeclarationCoverage API need an execution count?

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#208722]
Testing #208463

A declaration is only declared once or are there exceptions to this? The 100% in the UI seems a bit off (can it be less than that?):

![Image](https://github.com/microsoft/vscode/assets/9205389/b9862186-70ec-4832-8fcd-2a02f403f0c0)

**Comment by connor4312** [comment]
Declaration count refers to the number of times that declaration was entered, e.g. a function is called. Most test reporters that report whether a declaration is covered also report the number of times it was executed.
