### ISSUE TITLE
ERROR: Unable to start debugging. Unexpected CLRDBG output from command "-exec-run".

### ISSUE THREAD

**Issue by LukeStephen** [Microsoft/vscode#20871]
I am getting this same error all of a sudden, worked fine yesterday, but last night my MacOS did update to 10.12.4 Public Beta 2.

Builds fine, but can't debug any longer, any ideas?

ERROR: Unable to start debugging. Unexpected CLRDBG output from command "-exec-run".
WebApp-OpenIDConnect-DotNet.dll' has exited with code 42 (0x0000002a).

**Comment by mshulman** [comment]
See:
https://github.com/OmniSharp/omnisharp-vscode/issues/1220

**Comment by jrieken** [comment]
closing as this is an OmniSharp issue
