### ISSUE TITLE
use official solarized

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#20873]
use latest official solarized:
http://ethanschoonover.com/solarized
https://github.com/deplorableword/textmate-solarized
from over two years ago does not have different italics for comments between light and dark like the vscode version does
https://github.com/Microsoft/vscode/issues/20574

**Comment by aeschli** [comment]
There are a lot of differences between what we have and what's in https://github.com/deplorableword/textmate-solarized.
Did you see that comments are not italic, neither in [dark](https://github.com/deplorableword/textmate-solarized/blob/master/Solarized%20(dark).tmTheme#L49) nor [light](https://github.com/deplorableword/textmate-solarized/blob/master/Solarized%20(light).tmTheme#L49)?
It seems only HTML comments are.

Given that there are many differences and theme changes are always a very sensitive topic, upsetting all users that like the current form. I'd rather not make changes to the built-in Solarized theme. Instead I suggest you create a new extension that contains the theme from https://github.com/deplorableword/textmate-solarized and publish it from the market place. See [here](https://code.visualstudio.com/docs/customization/themes#_adding-a-new-theme) for detailed instructions.
