### ISSUE TITLE
`Alt+[` / `Alt+]` don't do anything

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#208703]
Testing #207637

The a11y help says I can use `Alt+[` / `Alt+]` to show the next/previous item, but these keybindings don't seem to do anything. It's also unclear to me whether these are for navigating items within a response or for navigating between requests/responses in the chat history

**Comment by meganrogge** [comment]
these are for navigating between chat responses, if any. there's an issue open already to disable these unless there are multiple chat responses.

**Comment by joyceerhl** [comment]
Oh, I just realized this command requires the accessible view to already be open. If I have the accessible view open, then I can use alt+[ and alt+] to navigate between chat responses.
