### ISSUE TITLE
Feature Request: Command to fast deploy to multiline Object and Function Params

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#20887]
More efficient than long speech, here is a demo :

![test](https://cloud.githubusercontent.com/assets/5599375/23102010/487c4a20-f6a1-11e6-902f-84b8e544d1f6.gif)

Most great editor have this feature, but i can't find this commands into vscode.

**Comment by roblourens** [comment]
This could be covered by "format selection" or an extension.

**Comment by mjbvz** [comment]
Yes, this feature requires language specific knowledge. Some existing formatters in the marketplace also already support this formatting style

Closing as extension-candidate
