### ISSUE TITLE
Terminal quick fix dropdown can be obscured by status bar

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#208806]
From @lszomoru in microsoft/vscode-copilot#4711

![image](https://github.com/microsoft/vscode/assets/2193314/dbd1c8ea-e588-4c13-9480-dfda7d0bc6e3)

**Comment by IllusionMH** [comment]
Same can be repooduced without copilot as well
![image](https://github.com/microsoft/vscode/assets/1312662/efc78233-6f33-4af1-bcdd-d1b9c9675aaf)

**Comment by meganrogge** [comment]
Cannot reproduce on mac
