### ISSUE TITLE
Insiders build: installing any npm module fails

### ISSUE THREAD

**Issue by joseds** [Microsoft/vscode#20884]
- VSCode Version: Version1.10.0-insider
- OS Version: Windows 10 Professional

Steps to Reproduce:

1. Open a JavaScript project in VS Code Insiders
2. Open the integrated terminal or an external command prompt (does not matter if administrative or not).
3. Try to install an npm module from the integrated resp. external terminal, e.g. `npm install --save-dev enzyme`
4. The installation fails because some files cannot be renamed (while VS Code is running, see workaround):
```
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\jose\Documents\GitHub\d-portal\node_modules\.staging\domutils-5643046d' -> 'C:\Users\jose\Documents\GitHub\d-portal\node_modules\enzyme\node_modules\domutils'
npm ERR!  { Error
npm ERR!     at destStatted (C:\Users\jose\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:29:7)
npm ERR!     at C:\Users\jose\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:111:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\jose\Documents\GitHub\d-portal\node_modules\.staging\domutils-5643046d' -> 'C:\Users\jose\Documents\GitHub\d-portal\node_modules\enzyme\node_modules\domutils' parent: 'enzyme' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
``` 

**Current workaround**: Close VS Code and run the install from an external command line.

**Comment by jrieken** [comment]
> Please try running this command again as root/Administrator.

Under what user are you running VS Code?

**Comment by joseds** [comment]
Thank you for the suggestion. If I start VS Code as administrator, npm installs work. 

This was not necessary until a few builds ago, though.

**Comment by Tyriar** [comment]
Looks like you're having permissions problems because of your npm install. The VS Code's terminal inherits the user the editor was launched with, you likely installed at some point some part of npm under admin permissions which is now preventing writes.

You will need to address the issue from the npm side.
