### ISSUE TITLE
Delete key no longer works in editors after using inline chat

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#208818]
Type: <b>Bug</b>

1. Open a text editor
2. Ctrl+I to start inline chat
3. Press Escape to dismiss
4. Try to use delete key to delete text to the right of cursor

:bug: => `workbench.action.chat.remove` takes over

VS Code version: Code - Insiders 1.88.0-insider (5d8491d7130d25aae121eeaa1633603ef8faa39e, 2024-03-26T05:49:49.370Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (12.39GB free)|
|Process Argv|--folder-uri file:///d%3A/Source/github/microsoft/vscode --crash-reporter-id 6da3720d-fb86-47a1-91f3-ebd9f5fa64fd|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/208549
