### ISSUE TITLE
Test Explorer: usability issues and regressions when transitioning from test explorer extension

### ISSUE THREAD

**Issue by DesignByOnyx** [microsoft/vscode#208852]
**Background:**

I just switched from the [Test Explorer UI extension](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer) to the native test explorer and have run into a couple usability issues which I cannot work around.

**Regressions:**

I need to select individual tests across multiple test suites. Previously, I was able to select a few tests from one test suite (eg. ctrl + click) and then was able to navigate the other test suites by clicking on the chevrons without losing my selection. Now, it is impossible to expand/collapse another test Suite without deselecting the tests. I must first expand every test suite before selecting the individual tests I want.

**Expected behavior:**

At the very least, clicking the chevron should not select that node - it should only expand or collapse that node. 

If you want to match the behavior of the old test explorer extension, then clicking the node text should only select that node and should not expand/collapse it. This effectively means that the node chevron is only expand/collapse (no select), and the node text is select/deselect (no expand).

**Comment by andreamah** [comment]
Not sure if I verified correctly- I was testing according to my interpretation of this:
> At the very least, clicking the chevron should not select that node - it should only expand or collapse that node.

So I was testing that clicking the chevron would expand/collapse the item without affecting selection.

[![Image from Gyazo](https://i.gyazo.com/ffe47d76dddd5b2cba137d716fea2135.gif)](https://gyazo.com/ffe47d76dddd5b2cba137d716fea2135)

**Comment by connor4312** [comment]
yep that's right :)

**Comment by DesignByOnyx** [comment]
Yes, can confirm that this matches the behavior of the old test-explorer plugin and is sadly missed in the current official vscode test explorer. You guys rock for fixing this!
