### ISSUE TITLE
Token Helight Color Not Working Fine!

### ISSUE THREAD

**Issue by EinOnly** [microsoft/vscode#208869]
Type: <b>Bug</b>

I use the same settings in my windows laptop and mac. But vsccode in mac always show me the different syntax helight from windows. Windows version is exactily what I need and is correct helight. Bty, I find that inspect Editor tokens and scopes is different in macos vscode from windows.

language: C++ 17
Theme: GitHub Dark
settings json:
```
       "editor.tokenColorCustomizations": {
        "enabled": true, // enable for all themes
        "textMateRules": [
            {
                "scope": "comment.block",
                "settings": {
                    "foreground": "#62c27a"
                }
            },
            {
                "scope": "entity.name.function.preprocessor",
                "settings": {
                    "foreground": "#b74fe0"
                }
            },
            {
                "scope": "entity.name.function.macros",
                "settings": {
                    "foreground": "#b74fe0"
                }
            },
            {
                "scope": "keyword.control.directive",
                "settings": {
                    "foreground": "#687f8d"
                }
            },
            {
                "scope": "entity.name.function",
                "settings": {
                    "foreground": "#dbd40c"
                }
            },
            {
                "scope": "string.quoted",
                "settings": {
                    "foreground": "#c8e4d8"
                }
            },
            {
                "scope": "variable.other.local",
                "settings": {
                    "foreground": "#fba741"
                }
            },
            {
                "scope": "constant.numeric",
                "settings": {
                    "foreground": "#788ee0"
                }
            },
            {
                "scope": "comment.line",
                "settings": {
                    "foreground": "#41de7d"
                }
            },
            {
                "scope": "punctuation.separator.namespace.access.cpp.cpp",
                "settings": {
                    "foreground": "#8993d3"
                }
            },
            {
                "scope": "entity.name.class",
                "settings": {
                    "foreground": "#1d1d1d"
                }
            }
        ]
    },

```
 I try all :
```
 {
                "scope": "entity.name.function.preprocessor",
                "settings": {
                    "foreground": "#b74fe0"
                }
            },
            {
                "scope": "entity.name.function.macros",
                "settings": {
                    "foreground": "#b74fe0"
                }
            },
{
                "scope": "entity.name.function",
                "settings": {
                    "foreground": "#dbd40c"
                }
            },
```
Macros and functions show the same color and Scape in mac. And variables never be helighted.

VS Code version: Code 1.87.2 (Universal) (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.50GB free)|
|Process Argv|--crash-reporter-id 1f5fcdd0-1d46-4d2c-8b1f-817b7e88448f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|3.2.3
solidity|Jua|0.0.174
vscode-clang|mit|0.2.4
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.2
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.17.17
cpptools|ms-|1.20.0
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.14
makefile-tools|ms-|0.9.10
remote-explorer|ms-|0.4.3
sqltools|mtx|0.28.1
sqltools-driver-mssql|mtx|0.4.2
shader|sle|1.1.5
cmake|twx|0.0.17
vim|vsc|1.27.2
json|Zai|2.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r3:30993539
dsvsc020:30976470
pythonaic:30996667
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by aeschli** [comment]
Can you also add a small code sample, and screenshots?

You say ` Editor tokens and scopes` is different. How so? Can you take screenshots of the two?

**Comment by EinOnly** [comment]
<img width="631" alt="Screenshot 2024-03-29 at 10 27 14" src="https://github.com/microsoft/vscode/assets/76414574/37a98a2a-b478-419d-b6a1-cb4141d22ed1">
<img width="532" alt="Screenshot 2024-03-29 at 10 27 46" src="https://github.com/microsoft/vscode/assets/76414574/2d15dc43-580b-4a88-99c3-f44f48c76c48">
<img width="568" alt="Screenshot 2024-03-29 at 10 29 14" src="https://github.com/microsoft/vscode/assets/76414574/307883b7-ca31-45b2-a23d-0ef72d9936d1">
<img width="568" alt="Screenshot 2024-03-29 at 10 30 17" src="https://github.com/microsoft/vscode/assets/76414574/caa2319e-75ed-47f9-832f-b967a8d43af4">

It seems that some settings might be causing this outcome, and I've ruled out plugins. I've encountered similar results using the same project on Windows as well. This project can compile successfully.

**Comment by EinOnly** [comment]
Need more information?

**Comment by aeschli** [comment]
So what is wrong? All three screenshots show a function call and all of them are rendered with the same color as I would expect.

**Comment by aeschli** [comment]
Syntax highlighting is only based on the structure of the program. It can't look up symbols and doesn't know that VK_MAKE_VERSION is macro.

To resolve symbols (possibly across files) a language server is needed. It will add 'semantic highlighting' on top of the syntax highlighting.
Looking at your screenshots, there's no semantic highlighting active here.
- make sure you have a C++ language extension installed 
- make sure it is properly configured, e.g. knows the project setup
- make sure semantic highlighting is not disabled. Note: Not all themes support that. Best to use the default themes for testing.

If that's all properly configured, you will see a `semantic token` section showing up in the `Inspect editor scopes..` hover
