### ISSUE TITLE
Compute word based suggestions from all open editors

### ISSUE THREAD

**Issue by wzup** [Microsoft/vscode#20886]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|vscode-database|bajdzis|1.2.0|
|Theme-Monokai-Easylight|davidbabel|1.0.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-npm-script|eg2|0.1.8|
|Theme-FlatlandMonokai|gerane|0.0.4|
|Theme-monokai-best|gerane|0.0.2|
|mediawiki|jakeboone02|2.1.0|
|sublime-babel-vscode|joshpeng|0.2.4|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|theme-readable-material-darker|petemill|0.0.2|
|vscode-icons|robertohuertasm|7.2.0|
|theme-monokaiextended|Scatolina|0.0.1|
|theme-setimonokai|SmukkeKim|0.0.1|
|addDocComments|stevencl|0.0.8|
|react-redux-es6-snippets|timothymclane|2.0.2|
|ReactSnippets|xabikos|1.2.1|

---

Steps to Reproduce:

1. Split IDE in two editors
2. Type any new word in the first editor
3. Start typing the same word in the second editor and click `Ctrl + Space` calling for suggestions.
4. Fail. No suggestions provided.

![no suggestions](https://cloud.githubusercontent.com/assets/3880497/23101934/36895ffe-f6da-11e6-8a65-199e9327f28f.png)

**Comment by juanmaflyer** [comment]
+1 This is a key feature

**Comment by rnemec** [comment]
@juanmaflyer , fyi, you can use the "All Autocomplete" plugin until this is natively supported. The plugin works fine.

**Comment by juanmaflyer** [comment]
Thanks @rnemec. I wasn't aware of that extension.

**Comment by usernamehw** [comment]
Duplicate of #5312 ?

**Comment by jrieken** [comment]
yes
