### ISSUE TITLE
Edit files in .code-search.

### ISSUE THREAD

**Issue by Errox** [microsoft/vscode#208894]
Since it's possible to search for certain strings in vscode and you can beautifully open these in your editor (When pressing the "Open in editor button). However, you can't edit this file to update it in multiple files. (Sort of replace all within your search)
For example here. I'd like to replace all the typo "{autho}" to "{author}" 
![image](https://github.com/microsoft/vscode/assets/10991347/4c1c77b1-03c3-4601-90ff-4c4456e30b83)
Now I can of course use the replace all function in search :). But since it's in a editing tab, I thought it might be a nice feature to be able to easily edit the found files / lines without having to swap between the working tabs and easily do it in one place.

**Comment by andreamah** [comment]
We would need to implement replace first, which is tracked in https://github.com/microsoft/vscode/issues/93031. Perhaps we should tackle this first, so I will close this for now.
