### ISSUE TITLE
Resizing Window makes debug toolbar disappear

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#208895]
Using Windows OS with a large screen
1. Maximize vscode/insiders window
2. Start debugging session
3. Press the maximize/restore WCO button in the top right
4. => Floating debug toolbar disappears

Does not only happen for the maximize/restore WCO button 

https://github.com/microsoft/vscode/assets/44439583/5bb4c38b-abce-49e6-9c07-cc9ea7c21c42

Possibly the same issue as #207346

**Comment by connor4312** [comment]
Thanks for the issue, I think this may be the same as the perplexing https://github.com/microsoft/vscode/issues/208895
