### ISSUE TITLE
Scrolling stutters over notebook outputs

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#208859]
1. Open `my-endgame.github-issues` in VS Code stable and VS Code insiders
2. Run all cells in each
3. Scroll quickly up and down through the notebook
4. :bug: in VS Code insiders scrolling over notebook outputs is not smooth anymore; scrolling appears to stutter and halt over notebook outputs

I took performance profiles in stable and insiders but devtools won't let me save them unfortunately. Nothing stood out though in terms of memory usage or a particular function call increasing in percentage across profiles. LMK if I can provide more info

**Comment by amunger** [comment]
Is this with a trackpad? I might be seeing this. Could be a regression from https://github.com/microsoft/vscode/issues/174913

**Comment by rzhao271** [comment]
I've the same issue with a trackpad on Windows.
