### ISSUE TITLE
TypeScript: use `createFileSystemWatcher` for file events

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#208872]
Refs: https://github.com/microsoft/vscode/pull/193848

- [x] need to check for TS 5.4 at least
- [ ] optimisations
  - [x] pass down need for update/create/delete events all the way down into watcher for correlated requests?
  - [ ] deduplicate watchers that correlate to reduce file handles need?
- [x] is TS deduplicating watch requests on same paths?
- [x] explore how `fs.watch` behaves when `npm i` or `git co`
- [x] we should batch events in the extension and only emit in chunks to prevent 1 IPC call per event?
- [x] enable the setting as experiment, default for insiders but disabled by default (!)
- [x] see if https://github.com/microsoft/TypeScript/issues/54087 is better then
- [x] explore file access with setting enabled using ProcMon on Windows

cc @sheetalkamat

**Comment by bpasero** [comment]
![Image](https://github.com/microsoft/vscode/assets/900690/a8f1feb8-812b-4729-9ab3-591e0deb6637)
![Image](https://github.com/microsoft/vscode/assets/900690/05862a35-0bff-433b-9876-3be874accfb9)

**Comment by bpasero** [comment]
This is done and behind an experiment that we will enable gradually in stable.

**Comment by BurningEnlightenment** [comment]
The current implementation seems to be incompatible with how yarn hooks the SDK to allow access to PnP packages.
