### ISSUE TITLE
Treeview multiselect is flakey

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#208802]
I've been adding multi-select support to GitLens treeview and noticed a few issues with tree views with `canSelectMany` enabled

Using `shift-click`, `ctrl-click` don't usually work correctly the "first" time, but seem to (usually) fix themselves on repeated attempts.

https://github.com/microsoft/vscode/assets/641685/3b90fb79-37db-49ed-9a88-1db52e0d3217

In the above, I've made a quick modification to the TreeView Sample to enabled `canSelectMany` and just added a few more nodes to make it easier to see. And then clicked the first node, and then `shift-click`ed the last, and you can see that it didn't fully select all the nodes in between. But when I repeated the `shift-click` it fixed it. 

I am not sure what causes it to work/not work sometimes and not others -- but it always seems to not work the first time, but there are other cases when it is just flakey.

/cc @alexr00

**Comment by alexr00** [comment]
I'm having trouble reproducing this issue, even on the "first" time. If you find some other way to get a good repro I'd like to take a look!

**Comment by alexr00** [comment]
Possible repro steps: https://github.com/microsoft/vscode/assets/54879025/1052625a-aff6-49fc-bb07-8d8958b976ad

**Comment by eamodio** [comment]
Reproduces easily for me 

https://github.com/microsoft/vscode/assets/641685/3ad87349-c5cc-4b28-bd0a-0a56686ac8f5

I'm on Windows if that matters

**Comment by alexr00** [comment]
I can repro 👍

**Comment by alexr00** [comment]
I can no longer repro.

**Comment by alexr00** [comment]
To verify: 

Here's a branch in the extension samples that shows the flake: https://github.com/microsoft/vscode-extension-samples/tree/alexr00/treeViewMultiselectFlake
Steps:

0. Make sure you're on the latest insiders. I reverted a change that could have hidden this issue last week.
1. Open the tree-view-sample, npm install, and F5.
2. Open the "Test View"
3. Left click on "e"
4. Shift + left click on "a"
5. Verify that all the nodes between "e" and "a", inclusive, are selected
