### ISSUE TITLE
terminal is not working

### ISSUE THREAD

**Issue by taibah-faliq** [microsoft/vscode#208866]
Type: <b>Performance Issue</b>

i wanted to compile a file, so opened the termina but my terminal is not working neither command prompt
it is just showing and epty blank space

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.02GB free)|
|Process Argv|--crash-reporter-id 8929b68c-e8e7-451a-88db-539008e3b425|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   104	  6876	code main
    0	   116	  2472	extensionHost [1]
    0	    89	  7688	ptyHost
    0	    94	  8304	shared-process
    1	   129	 12372	   gpu-process
    0	    29	 16192	   crashpad-handler
    0	    41	 17188	   utility-network-service
    0	    90	 19084	fileWatcher [1]
    0	   174	 20108	window [1] (Visual Studio Code)
    1	    96	 21484	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|2.0.9
vscode-typescript-next|ms-|5.5.20240326

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonaic:30996667
jchc7451:30973076
dsvsc021:30996838
g1icg217:30999571

```

</details>

**Comment by gjsjohnmurray** [comment]
Have you followed the guide at https://github.com/microsoft/vscode/wiki/Terminal-Issues yet?

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal
