### ISSUE TITLE
[Ctrl+K R] doesn't open a containing folder, but opens a browser window

### ISSUE THREAD

**Issue by wzup** [Microsoft/vscode#20880]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|vscode-database|bajdzis|1.2.0|
|Theme-Monokai-Easylight|davidbabel|1.0.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-npm-script|eg2|0.1.8|
|Theme-FlatlandMonokai|gerane|0.0.4|
|Theme-monokai-best|gerane|0.0.2|
|mediawiki|jakeboone02|2.1.0|
|sublime-babel-vscode|joshpeng|0.2.4|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|theme-readable-material-darker|petemill|0.0.2|
|vscode-icons|robertohuertasm|7.2.0|
|theme-monokaiextended|Scatolina|0.0.1|
|theme-setimonokai|SmukkeKim|0.0.1|
|addDocComments|stevencl|0.0.8|
|react-redux-es6-snippets|timothymclane|2.0.2|
|ReactSnippets|xabikos|1.2.1|

---
A follow-up on this https://github.com/Microsoft/vscode/issues/15693

My settings for `ctrl+k r`:

![reveal in explorer - visual studio code 2017-02-19 16 33 22](https://cloud.githubusercontent.com/assets/3880497/23100688/2bf8c876-f6c2-11e6-9ea9-f2a2bb43192e.png)

But this keyboard shortcut doesn't open a containing folder. Instead it opens a browser window on this page https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

![microsoft word - keyboard-shortcuts-windows docx - google chrome 2017-02-19 16 35 48](https://cloud.githubusercontent.com/assets/3880497/23100699/6ed0515a-f6c2-11e6-904d-42fbd3fe8766.png)

How to disable this wrong behavior and turn on settings back?

Steps to Reproduce:

1. `ctrl+k r`

**Comment by bpasero** [comment]
@wzup could it be that you type `ctrl+k ctrl+r`?

![image](https://cloud.githubusercontent.com/assets/900690/23100923/357a9bd6-f68b-11e6-862c-fc822d028925.png)

**Comment by wzup** [comment]
What is the difference? 
I press `Ctrl` and keep it on. Then press `k` one time, then press `r` one time. 
Isn't it the same?

**Comment by bpasero** [comment]
@wzup no its not.

**Comment by wzup** [comment]
Ok. Would you be so kind then to tell me how `ctrl+k r` should be typed? Thank you very much.

**Comment by bpasero** [comment]
Literally pressing Ctrl+K and then R. You cannot keep Ctrl pressed when pressing R.
