### ISSUE TITLE
Create missing intermediate pathname components for new folders

### ISSUE THREAD

**Issue by michaelperrin** [Microsoft/vscode#20883]
- VSCode Version: 1.9.1
- OS Version: MacOS 10.12.3

This is a small feature request that would be useful when creating a new folder from the Explorer tab.

Steps to Reproduce:

1. Go to the Explorer (_View_ menu → _Explorer_)
2. Click on the _New folder_ button
3. Type a name like `folder/subfolder`

Result: an error message like _The name folder/subfolder is not valid_ is shown.

Expected result: the folder _subfolder_ could be created inside the folder _folder_.

Notes:

* What I am describing here would be the equivalent of the Unix `mkdir -p` command
* SublimeText works this way when creating folders.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by michaelperrin** [comment]
@bpasero I did it and couldn't find it unfortunately (and still can't).

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10967 https://github.com/Microsoft/vscode/issues/1169 https://github.com/Microsoft/vscode/issues/12893

**Comment by michaelperrin** [comment]
Indeed, thanks. In the meantime I found this extension: https://github.com/dkundel/vscode-new-file
