### ISSUE TITLE
Collapse All button in Search tab

### ISSUE THREAD

**Issue by Selekena** [microsoft/vscode#208843]
I would like to be able to collapse all the tabs in the search bar. For example, when I search foobar() and it appears in many files each occurrance will appear grouped and nested under the files it appears in. When I need to find a particular file before finding the occurrence, I need to collapse all the nestings so I can read all the files and not do a lot of scrolling. This is similar to the collapse feature in the folder explorer for VS Code represented by the minus sign.

**Comment by gjsjohnmurray** [comment]
Isn't there already a Collapse All button?

**Comment by Selekena** [comment]
You just made my day. Thanks
