### ISSUE TITLE
Working with spread array parameter

### ISSUE THREAD

**Issue by asimolmez** [Microsoft/vscode#20885]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|ReactSnippetsStandard|TimonVS|1.0.3|
|githistory|donjayamanne|0.1.5|
|debugger-for-chrome|msjsdiag|2.5.3|
|vscode-icons|robertohuertasm|7.2.0|
|react-redux-es6-snippets|timothymclane|2.0.2|
|vscode-react-native|vsmobile|0.3.1|
|JavaScriptSnippets|xabikos|1.4.0|

---

Steps to Reproduce:

1. When sending spread array to a parameter of a function, vs code create a problem issue `supplied parameters do not match any signature of call target`.

![image](https://cloud.githubusercontent.com/assets/661983/23101837/d120a958-f6a5-11e6-8747-e3e62300170b.png)

**Comment by mrmlnc** [comment]
It's not related to VS Code. See https://github.com/Microsoft/TypeScript/issues/5296

**Comment by mjbvz** [comment]
Thanks @mrmlnc. Closing as upstream since we are tracking this on the TypeScript side
