### ISSUE TITLE
Debug Batch (.bat) files

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#20882]
The Powershell extension enables debugging (https://blogs.technet.microsoft.com/heyscriptingguy/2017/02/13/debugging-powershell-script-in-visual-studio-code-part-2/) which is a really neat. Unfortunately we still have a lot of older scripts at work due to legacy Win XP machines.

Does a similar functionality exist for Batch (.bat) files? I couldn't find any extension and there doesn't appear to be any built in functionality other than syntax highlighting.

**Comment by weinand** [comment]
@csholmq I'm not aware of any .bat file debugger.

@daviwil do you know whether this is even possible?

**Comment by csholmq** [comment]
If it would be possible to debug, this is more of a feature request than a question.

**Comment by weinand** [comment]
How do you debug .bat files on Windows in general? Is there a debugger?

**Comment by daviwil** [comment]
I am not aware of standard .bat debugger and I don't know how one could be implemented.

**Comment by weinand** [comment]
@daviwil Thanks, that was my assumption.

@csholmq Since there is no implementation in reach, I do not consider this issue a "feature request" for VS Code ;-)

**Comment by csholmq** [comment]
@weinand Only debugger I found was a command line BDEBUGGER https://jpsoft.com/help/bdebugger.htm

Haven't tested it yet, though.

**Comment by weinand** [comment]
Ok, may be someone can write an extension based on BDEBUGGER...

**Comment by weinand** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable.
Thanks for understanding and happy coding!

**Comment by csholmq** [comment]
Fair enough :)
