### ISSUE TITLE
Command palette fuzzy matching prioritizes caps matching over exact matches

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#20888]
- VSCode Version: `1.10.0-insider`
- OS Version: `Windows 10`

Steps to Reproduce:

1. ctrl-shift-p -> sett...

![image](https://cloud.githubusercontent.com/assets/5593825/23102668/e0774ae4-f6ad-11e6-8651-9232a8cad1a3.png)

**Comment by Tyriar** [comment]
It's also matching `set t` over the ideal ones.

![image](https://cloud.githubusercontent.com/assets/2193314/23106363/24214d88-f6a1-11e6-95e1-7142277f50cc.png)
