### ISSUE TITLE
OSX sonoma bash integrated terminal terminates (closes) before interactive prompt

### ISSUE THREAD

**Issue by gigs94** [microsoft/vscode#208860]
- VS Code Version: 1.87.2 (Universal)
- OS Version:  macOS 14.4 (23E214)

It appears there has been behavior change in bash in sonoma.  `bash -l` seems to no longer imply interactive, at least does not appear to when running in the integrated terminal in vscode.   Replacing it in settings.json with `bash -il` allows the terminal to open normally.

Steps to Reproduce:

1.  Set in settings.json
```
    "terminal.integrated.defaultProfile.osx": "bash",
    "terminal.integrated.profiles.osx": {
        "bash": {
            "path": "bash",
            "args": [
                "-l",
            ],
            "icon": "terminal-bash"
        },
```
2.  Open terminal.   Terminal window should open for a few seconds and then close.  Clicking on console stops the panel from closing but going back to the terminal tab continues the time out and subsequent closing of the panel.  

Work arounds:
1.  Changing to zsh works.   (Then you can do `bash -l` to get to bash)
2. Changing "args": [ "-il" ] works.

Suggest changing the default in settings.json if anyone else is having this issue.

Let me know if you want me to test any other settings...

**Comment by meganrogge** [comment]
`bash -l` does not imply interactive. The -l option makes bash act as if it had been invoked as a login shell.

To make it interactive, you need to add the `-i` argument. so this is working as designed AFAICT.

**Comment by gigs94** [comment]
Right, but somewhere in the stack, this changed.   All the documentation
for vscode says  just use -l.   Maybe something changed from bash
implementation that if you don't send it a command it was assumed
interactive?   Or interactive is not the default anymore?   IDK... just
guessing, but this stopped working for me for some reason, and I couldn't
figure out what I changed (if anything).   This is the only solution that I
have found so far.
