### ISSUE TITLE
View: Reset View Locations will not reset visibility property.

### ISSUE THREAD

**Issue by Askhento** [microsoft/vscode#208886]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

Here is a [repo](https://github.com/Askhento/collapsed_view_bug) for reproduction.

### Steps to reproduce

0. run extension with F5
1. click on Zap icon with title "TEST_VIEW_CONTAINER"
2. It should contain 3 views with visibility : [visible, collapsed, hidden]
3. Change view location by dragging somewere and change collapsed state
4. From command palette run : "View: Reset View Locations"
5. Views will jump back, but visibility option will not reset.

**Comment by benibenj** [comment]
It is not expected to change the visibility but just the location
