### ISSUE TITLE
double JSON.stringify/parse when talking to extension host process

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2088]
the default IPC mechanism in nodejs already does [JSON.stringify](https://github.com/nodejs/node/blob/master/lib/internal/child_process.js#L586) and [JSON.parse](https://github.com/nodejs/node/blob/master/lib/internal/child_process.js#L432) before sending and after receiving messages. Maybe we gain a little bit of performance we don't do right before/after.

**Comment by jrieken** [comment]
unsure if this @alexandrudima or @bpasero

**Comment by weinand** [comment]
@alexandrudima please reassign if @bpasero is the author of this code.

**Comment by bpasero** [comment]
I think we are doing more than just JSON.stringify/parse though, there is code that knows how to marshall classes.

**Comment by jrieken** [comment]
yes, but marshalling is not serialising https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/marshalling.ts#L119

**Comment by alexandrudima** [comment]
I was doing the extra JSON stringify/parse intentionally back when the extension host was using electron's IPC which had bugs around serializing the same object twice. e.g.:

```
var obj1 = { hello: 'world' }
var arr = [obj1, obj1];
```

it would arrive on the other side as `[obj1, null]`.

But I think this is no longer mandatory given @bpasero 's refactoring it to a forked process.

**Comment by bpasero** [comment]
@alexandrudima I am not feeling comfortable making any changes to marshalling.ts, I did not touch this when I created the forked process. please go ahead and see what happens when you just take out the serialization.

**Comment by jrieken** [comment]
I'll take on the challenge

**Comment by bpasero** [comment]
:icecream:

**Comment by alexandrudima** [comment]
Thanks! :heart:
