### ISSUE TITLE
Html wrap attribute setting is not working

### ISSUE THREAD

**Issue by abhijit-chikane** [microsoft/vscode#208990]
This setting is not working in vscode insider though working perfectly fine in stable release
![image](https://github.com/microsoft/vscode/assets/50770619/6c945206-0079-4408-9d3d-7c724da93bb1)

**Comment by aeschli** [comment]
Can you paste a small code example that show the issue?

**Comment by abhijit-chikane** [comment]
well this is happening with the any html contnent

> <div class="header">
    <div>
        <h2 class="title">Cases</h2>
        <p-button class="new-case-btn" label="+ New Case"></p-button>
    </div>
    <div>
        {{appStore.userData.currentOrganizationName()}}
    </div>
</div>

here label attribute on line 3 should go on to the next line but it doesn't

**Comment by aeschli** [comment]
I can't reproduce on the latest insiders:
![Peek 2024-04-02 20-47](https://github.com/microsoft/vscode/assets/6461412/6300793e-34ff-4f98-b86b-5f78a84a4ec4)

Make sure the editor is in HTML mode, and that there's no other extension that took over formatting or the HTML mode.

**Comment by aeschli** [comment]
Tested on Version: 1.88.0-insider
Commit: ae59067554575afaba07640320a26435c8e05175
Date: 2024-04-02T12:32:08.997Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
