### ISSUE TITLE
VSCode use old node version

### ISSUE THREAD

**Issue by rexkenley** [microsoft/vscode#208943]
Does this issue occur when all extensions are disabled?: Yes

![image](https://github.com/microsoft/vscode/assets/10548251/c5a5408c-2ae1-42ed-93a0-9674c6d8ef6b)

**Comment by gjsjohnmurray** [comment]
Doesn't seem to be a problem at the moment:

![image](https://github.com/microsoft/vscode/assets/6726799/04d73662-3163-4cf3-a14d-2313504f3f40)

**Comment by rexkenley** [comment]
@gjsjohnmurray , So the vscode nodejs version doesn't reflect what nodejs is installed in the system?

**Comment by rexkenley** [comment]
Thanks
