### ISSUE TITLE
TS/JS Language Server

### ISSUE THREAD

**Issue by PaoloJr90** [microsoft/vscode#208939]
Type: <b>Bug</b>

The TS/JS native language server (v.5.3.2) for VSCode keeps crashing - particularly when I am working in TS-React files.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600 6-Core Processor               (12 x 3493)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.12GB free)|
|Process Argv|--crash-reporter-id 54f1fd68-3a79-4f04-9dd7-935fc921a36d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600 6-Core Processor (12 x 3493)|
|Memory (System)|15.59GB (11.07GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.86.0
vscode-tailwindcss|bra|0.10.5
copilot|Git|1.176.0
copilot-chat|Git|0.13.1
live-server|ms-|0.4.13
powershell|ms-|2024.0.0
vscode-wakatime|Wak|24.4.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? (besides wsl)

**Comment by PaoloJr90** [comment]
@mjbvz thanks for the quick reply. Switching to TS version 5.0.2 (the one currently used for the repo I am working in) seems to have resolved the issue. Simple oversight by me 👍

**Comment by PaoloJr90** [comment]
@mjbvz I spoke too soon 😄 
After a few hours using VS Code, with all extension, the TS server, even when on V 5.0.2 keeps crashing (almost every few minutes - I managed to work through it all). I then switched to VS Code Insiders (TS V 5.0.2), with no extensions enabled (besides WSL) and it has the same effect. Below is my information from VS Code Insiders:

Type: <b>Bug</b>

native TS server keeps crashing. 

VS Code version: Code - Insiders 1.88.0-insider (46b756b8434730593b3c911fd1ca43366b29eb03, 2024-03-28T10:54:31.414Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600 6-Core Processor               (12 x 3493)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (12.48GB free)|
|Process Argv|--crash-reporter-id b4d736ed-939c-47a5-9e78-b9abd3aca956|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600 6-Core Processor (12 x 3493)|
|Memory (System)|15.59GB (10.75GB free)|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.88.0


</details>

**Comment by PaoloJr90** [comment]
@mjbvz this issue is intermittent. When it occurs, the editor becomes very difficult to use. The last few weeks have been much better though 👍 closing the issue
