### ISSUE TITLE
[json] support format 'uri'

### ISSUE THREAD

**Issue by xferra** [Microsoft/vscode#20894]
- VSCode Version: 1.9.1
- OS Version: macOS 10.12.1

Steps to Reproduce:
Create 3 files in the same folder:

Schema.json:
```javascript
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "format": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "value1",
            "value2"
          ]
        },
        {
          "type": "string",
          "format": "uri"
        }
      ]
    }
  }
}
```

Example.json
```javascript
{
    "$schema": "./Schema.json",
    "format": "value1"
}
```
Actual: 'Warning' message: 'Matches multiple schemas when only one must validate.'
Expected: No warnings

Example2.json
```javascript
{
    "$schema": "./Schema.json",
    "format": "file://test"
}
```
Actual: No warnings

Note: There are no warnings with those examples when validating using http://www.jsonschemavalidator.net

**Comment by xferra** [comment]
BTW it also doesn't show errors for invalid values:

```javascript
{
    "$schema": "./s_e.json",
    "format": "not_valid_uri"
}
```

**Comment by aeschli** [comment]
You are using the 'format' attribute of the JSON Schema. Our schema validator does not implement format validation. https://spacetelescope.github.io/understanding-json-schema/reference/string.html#format says its optional, so your schema plays with the fire.

**Comment by xferra** [comment]
I confirm that 'anyOf' will hide a warning, so my issue is resolved for now.
Thank you for the answer!

**Comment by aeschli** [comment]
> BTW it also doesn't show errors for invalid values:
The value set of 'format' is open. You can have anything in there. But there's a set of known formats.
