### ISSUE TITLE
Bad highlighting in Quick Pick

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#208905]
Version: 1.88.0-insider (user setup)
Commit: 246d700c4604eb5ebdbb561a1a86562bf9217a62
Date: 2024-03-27T05:50:10.528Z
Electron: 28.2.6
ElectronBuildId: 27476517
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22635

Theme: 

![Image](https://github.com/microsoft/vscode/assets/1931590/5fbd3c1d-9132-4e64-ac56-f049f093bbdc)

Steps to Reproduce:

1. Ctrl+Shift+P
2. Type VSIX

![Image](https://github.com/microsoft/vscode/assets/1931590/1ddde185-c65a-42ce-a6cc-f4d3b4079300)

**Comment by TylerLeonhardt** [comment]
Caused by: https://github.com/microsoft/vscode/pull/208835
