### ISSUE TITLE
redirect input from file

### ISSUE THREAD

**Issue by novellizator** [Microsoft/vscode#20890]
I'd love to have something like this http://stackoverflow.com/questions/32863807/visual-studio-code-redirect-input-on-debug without a workaround. That is, ability to redirect input from a given file, when debugging.

**Comment by weinand** [comment]
@novellizator Input redirection with '<' is only supported if the command and the arguments are interpreted by a shell. But the launch config used on the stackoverflow page uses the internal debug console of VS Code which doesn't use a 'shell'.
You can add a 'console' attribute to the launch config with either a value of 'integratedTerminal' or 'externalTerminal'. In this case a shell is used and input or output redirection will work.

**Comment by novellizator** [comment]
I have (had) it filled with "integratedTerminal". what should I do to redirect the input from input.txt ?

**Comment by weinand** [comment]
Just use what was done in the stackoverflow article:
```json
  "args": [
    "<",
    "input.txt"
  ]
```

**Comment by novellizator** [comment]
thank you. Anyway, I have had several friends trying to tackle this. maybe it'd be of help to put it into some faq/hacks/tips.

**Comment by weinand** [comment]
@novellizator yes, I will add this to this doc: https://code.visualstudio.com/docs/editor/debugging

**Comment by echosys** [comment]
I tried  "console": "integratedTerminal", but I get an error saying "Property console is not allowed". 
I am using vs code on a mac with lldb. Really trying to find a way to debug my program with input file. The work around doesn't seem to work either.

**Comment by weinand** [comment]
@echosys the `console` attribute is specific to certain debug extensions. What debugger are you using?

**Comment by echosys** [comment]
That could be why. In that case does there exists a solution or work around then? 
I am using the C/C++ extension from Microsoft and lldb debugger on Mac.

**Comment by weinand** [comment]
Please file an issue/question against the C/C++ extension.
Since C/C++ is not built into VS code, we cannot answer.
