### ISSUE TITLE
Parameter types not colour-coded properly

### ISSUE THREAD

**Issue by JeffreyCA** [Microsoft/vscode#20892]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|code-runner|formulahendry|0.6.10|
|cpptools|ms-vscode|0.10.1|
|vscode-icons|robertohuertasm|7.2.0|
|ayu|teabyii|0.2.1|
|debug|webfreak|0.17.0|

---

Steps to Reproduce:
In the following code snippet, all of the parameter types such as double, int, char, should colour-coded as a type.

```
double fn(double (*f)(double), double a, int b, char c) {
...
}
```

Instead, only the **double**s in the first parameter `(double (*f)(double))` are coloured differently.

**Comment by jrieken** [comment]
what language is that?

**Comment by JeffreyCA** [comment]
C

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#209
