### ISSUE TITLE
Implement new `equals` method on `URI` to replace `toString` comparisons

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#208930]
Currently to compare URIs we `uri1.toString() === uri2.toString()`. We could maybe develop a method `.equals` on URIs to compare URIs instead part by part.

**Comment by aiday-mar** [comment]
If @jrieken you think this is a good idea, I can implement this method

**Comment by jrieken** [comment]
We have these utils but they aren't part of `URI` because that would become API. Check out this

https://github.com/microsoft/vscode/blob/ce95d55d9ed62f0f100f146b5c3f70f4ff05cf7e/src/vs/base/common/resources.ts#L360-L376

**Comment by aiday-mar** [comment]
I see thanks for the clarification. I will close this issue.
