### ISSUE TITLE
Github Copilot - Rename suggestions feature doesn't work

### ISSUE THREAD

**Issue by vuon9** [microsoft/vscode#208974]
Type: <b>Bug</b>

It doesn't give me any rename suggestions from Github Copilot and no logs to say if something is going wrong. Even I tried to switch Copilot latest version to pre-release, it still doesn't work after.

VS Code version: Code 1.87.2 (Universal) (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 6, 6|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 66e1c62b-e8b6-4f84-aef4-52139a772312|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.4.2
cucumberautocomplete|ale|2.15.2
incr|ara|1.0.0
gitstash|art|5.2.0
smarty-template-support|asw|2.1.1
vscode-fish|bma|1.0.38
vscode-intelephense-client|bme|1.10.4
transformer|dak|1.12.1
EditorConfig|Edi|0.16.4
phpunit|ema|4.16.1
code-runner|for|0.12.1
ginfuru-vscode-jekyll-syntax|gin|0.1.1
codespaces|Git|1.16.17
copilot|Git|1.176.0
copilot-chat|Git|0.13.1
remotehub|Git|0.62.0
gitlab-workflow|Git|4.8.0
go|gol|0.41.2
gc-excelviewer|Gra|4.2.59
prettier-sql-vscode|inf|1.6.0
minifyall|jos|2.10.0
vscode-zpl-viewer|kam|0.2.0
php-cs-fixer|man|1.0.3
CamelCase|Mar|1.0.5
file-downloader|min|1.0.13
theme-monokai-pro-vscode|mon|1.2.2
vscode-kubernetes-tools|ms-|1.3.16
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
azure-repos|ms-|0.38.0
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.13
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.1
vscode-speech|ms-|0.6.0
color-highlight|nau|2.8.0
vscode-yaml-sort|Pas|6.5.15
vscode-php-getters-setters|php|1.2.3
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
vscode-sort-json|ric|1.20.0
vscode-coverage-gutters|rya|2.11.1
phpstan-vscode|San|2.2.26
even-better-toml|tam|0.19.2
errorlens|use|3.16.0
vscode-gradle|vsc|3.13.5
gitblame|wad|10.10.0
php-debug|xde|1.34.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
9b8hh234:30694863
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:30996668
dsvsc021:30996838
g1icg217:30999571

```

</details>

**Comment by zonterone** [comment]
same for me

**Comment by abelfubu** [comment]
Same for me 😢

I just created a new empty profile with no extensions, installed github copilot and renaming does not show any suggestion.

Working on a windows 11 computer in powershell (no WSL)
Runing VSCODE version 1.88

**Comment by ulugbekna** [comment]
Hi @vuon9 👋🏽 

We are rolling out this feature gradually. Thank you for patience with this! We're working hard to make it available as soon as possible.
