### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script kind should match provided ScriptKind:1 and sourceFile.scriptKind: 3, !entry: false

### ISSUE THREAD

**Issue by DreamYangdhj** [microsoft/vscode#208916]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.4.2

**Steps to reproduce crash**

1.
2.
3.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `typescript-vue-plugin-bundle` contributed by the `Vue.volar` extension

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code - Insiders 1.88.0-insider (246d700c4604eb5ebdbb561a1a86562bf9217a62, 2024-03-27T05:50:10.528Z)
OS version: Windows_NT x64 10.0.26085
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (5.30GB free)|
|Process Argv|D:\\Tech_software\\vue_code\\shopping --crash-reporter-id 4ca6348e-23f6-417d-9c77-b8f3dff91667|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vite|ant|0.2.5
npm-intellisense|chr|1.4.5
md-table-editor|clo|0.2.0
dart-code|Dar|3.85.20240318
vscode-eslint|dba|2.4.4
go|gol|0.41.2
vue-snippets|hol|1.0.4
plantuml|jeb|2.17.5
chrome-app-devtools|jon|1.1.1
code-beautifier|mic|2.3.3
vscode-language-pack-zh-hans|MS-|1.88.2024032709
vscode-ros|ms-|0.9.6
python|ms-|2024.3.10871011
vscode-pylance|ms-|2024.3.101
jupyter|ms-|2024.3.2024032701
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.20.0
js-debug-nightly|ms-|2024.3.2217
remote-explorer|ms-|0.5.2024031109
remote-server|ms-|1.5.1
vuejs-extension-pack|mub|1.9.0
vetur|oct|0.37.3
LiveServer|rit|5.7.9
vue-vscode-snippets|sdr|3.1.1
vscode-scss-formatter|sib|3.0.0
open-in-browser|tec|2.0.0
vscode-icons|vsc|12.7.0
volar|Vue|2.0.7
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.17.0
vitest-explorer|Zix|0.2.46
vue|znc|0.13.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:30784851
vscaac:30438845
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
bf62j303:30968145
cppperfnew:30980852
d34g3935:30961436
fegfb526:30952798
bg6jg535:30979844
ccp1r6:30958151
pythonait:30973460
gee8j676:30988845
g1icg217:30999571

```

</details>

**Comment by mjbvz** [comment]
> Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes
> 
> typescript-vue-plugin-bundle contributed by the Vue.volar extension

Please try these instructions before filing issues
