### ISSUE TITLE
Editor Placeholder Support

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#208976]
@roblourens To verify, go to the VS sources and run:
```
PlaceholderTextContribution.get(editor).setPlaceholderText('myPlaceholder')
```

**Comment by deepak1556** [comment]
Closing for verification.

**Comment by roblourens** [comment]
I'm able to use this when the input box is empty, and it works great, thanks! But when there is an `@` participant in the input, I still use a text decoration to show the participant description after the name. This is fine with me, it's probably not typical usage for input boxes with placeholders.

**Comment by hediet** [comment]
> But when there is an @ participant in the input, I still use a text decoration to show the participant description after the name.

We could support this, but I wonder how the API should look like and what benefits the placeholder feature would give over decorations.

**Comment by roblourens** [comment]
It would have to be something that I add and remove, like a decoration. But it would save a few lines of code in not having to figure out the color or positioning. Low-priority, probably, I don't think anyone else would use it beyond chat right now.
