### ISSUE TITLE
Slash is underlined and can be clicked

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#208935]
Verifying https://github.com/microsoft/vscode/issues/208681 I saw this:

<img width="814" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/5490d587-cd69-43ce-b4ca-0338c2eca758">

Notice the `1/x` has the `/` underlined ... and clicking it gets this:

<img width="817" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/0ca82f69-76e6-425b-a8be-6391de3b7013">

macOS if it's useful.

**Comment by amunger** [comment]
what OS are you on?
if you just run `print('1/x'), is that / underlined in the output?

**Comment by TylerLeonhardt** [comment]
@amunger macOS

only in the error:
<img width="682" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/43c175c3-938e-4749-9162-ea1ad4f7d3d9">

**Comment by rebornix** [comment]
We will track this in https://github.com/microsoft/vscode/issues/236113
