### ISSUE TITLE
vscode extension develop webview Abnormal interface display

### ISSUE THREAD

**Issue by likui1123** [microsoft/vscode#208995]
vscode version 1.81.1
**my html create a input** 

**The datalist option is not directly below the input**

![image](https://github.com/microsoft/vscode/assets/37236882/8273dde8-7a35-4c94-888e-b15f906359bf)

**in browser is normal**
![image](https://github.com/microsoft/vscode/assets/37236882/6df9bb62-3f8b-4f89-8326-93c7b5924975)

**Comment by mjbvz** [comment]
Duplicate of [#129999](https://github.com/microsoft/vscode/issues/129999)
