### ISSUE TITLE
Can not run a program properly

### ISSUE THREAD

**Issue by Visreborn** [microsoft/vscode#208968]
Type: <b>Bug</b>

This issue just has been happening to me recently. Specifically, whenever i copy a code from another source(c++ language) and paste it into one of my file, the program won't run and just collapse! At first, i thought my code was bugged, but it did work on every other online website like onlinegdb, etc.
For instance, when i pasted this code in and run it, the program just collapsed : 

#include<bits/stdc++.h>

using namespace std;

#define sz(x) ((int)x.size())
#define all(x) (x).begin(), (x).end()
const int INF = numeric_limits<int>::max();
const int nax = (int)(201001);
const int mod = 1e9 + 7;

template<class X, class Y>
bool maximize(X& x, const Y y) {
    if (y > x) {x = y; return true;}
    return false;
}
template<class X, class Y>
bool minimize(X& x, const Y y) {
    if (y < x) {x = y; return true;}
    return false;
}

#define NL 2 * si
#define NR 2 * si + 1

struct Segment_tree {
    int seg[4 * nax];
    void reseter(int _n) {
        for (int i = 0; i <= 4 * _n; ++i) {
            seg[i] = -INF;
        }
    }

    void update(int si, int sl, int sr, int idx, int v) {
        if (sl > sr || sl > idx || sr < idx) {
            return;
        }
        if (sl == sr) {
            seg[si] = v;
            return;
        }
        int mid = (sl + sr) >> 1;
        update(NL, sl, mid, idx, v);
        update(NR, mid + 1, sr, idx, v);
        seg[si] = max(seg[NL], seg[NR]);
    }

    int get(int si, int sl, int sr, int l, int r) {
        if (sl > sr || sl > r || sr < l) {
            return -INF;
        }
        if (sl >= l && sr <= r) {
            return seg[si];
        }
        int mid = (sl + sr) >> 1;
        return max(get(NL, sl, mid, l, r), get(NR, mid + 1, sr, l, r));
    }
};

struct Segment_treep {
    int seg[4 * nax];
    void reseter(int _n) {
        for (int i = 0; i <= 4 * _n; ++i) {
            seg[i] = 0;
        }
    }

    void update(int si, int sl, int sr, int idx, int v) {
        if (sl > sr || sl > idx || sr < idx) {
            return;
        }
        if (sl == sr) {
            seg[si] += v;
            return;
        }
        int mid = (sl + sr) >> 1;
        update(NL, sl, mid, idx, v);
        update(NR, mid + 1, sr, idx, v);
        seg[si] = seg[NL] + seg[NR];
    }

    int get(int si, int sl, int sr, int l, int r, int k) {
        if (sl > sr || sl > r || sr < l) {
            return -1;
        }
        if (sl == sr) {
            return sl;
        }
        int mid = (sl + sr) >> 1;
        if (seg[NL] >= k) {
            return get(NL, sl, mid, l, r, k);
        }
        return get(NR, mid + 1, sr, l, r, k - seg[NL]);
    }
};

#define Fi first
#define Se second

int a[nax], mp[nax];
int TYPE[nax], U[nax], V[nax];
vector<int> memo[nax];

int32_t main() {
    ios_base::sync_with_stdio(false);
    cin.tie(0);

    int n, q;
    cin >> n >> q;
    for (int i = 1; i <= n; ++i) {
        cin >> a[i];
        memo[i - 1].push_back(i);
        TYPE[i] = 1; U[i] = i; V[i] = a[i];
    }
    int d = n;
    Segment_treep ITp;
    ITp.reseter(n);
    for (int i = 1; i <= n; ++i) {
        ITp.update(1, 1, n, i, 1);
    }
    for (int i = n + 1; i <= n + q; ++i) {
        cin >> TYPE[i] >> U[i] >> V[i];
        if (TYPE[i] == 1) {
            d++;
        }
    }
    Segment_tree IT;
    IT.reseter(d);
    ITp.reseter(d);
    for (int i = 1; i <= d; ++i) {
        ITp.update(1, 1, d, i, 1);
    }
    for (int i = n + q; i >= 1; --i) {
        if (TYPE[i] == 1) {
            U[i] = ITp.get(1, 1, d, 1, d, U[i]);
            ITp.update(1, 1, d, U[i], -1);
            continue;
        }
        U[i] = ITp.get(1, 1, d, 1, d, U[i]);
        V[i] = ITp.get(1, 1, d, 1, d, V[i]);
    }
    for (int i = 1; i <= n + q; ++i) {
        if (TYPE[i] == 1) {
            IT.update(1, 1, d, U[i], V[i]);
            continue;
        }
        cout << IT.get(1, 1, d, U[i], V[i]) << '\n';
    }
    return 0;
}

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.42GB (1.97GB free)|
|Process Argv|--crash-reporter-id 9e44350a-0cce-40b9-a71a-7886a98b1421|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
c-cpp-compile-run|dan|1.0.58
code-runner|for|0.12.1
remotehub|Git|0.62.0
vscode-pull-request-github|Git|0.82.1
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
vscode-dotnet-runtime|ms-|2.0.3
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
remote-repositories|ms-|0.40.0
vsliveshare|ms-|1.0.5918
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:30996668
666c4381:30973075
gee8j676:30988843
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by roblourens** [comment]
This doesn't sound like an issue with vscoe
