### ISSUE TITLE
Server-base-path not applied to WSS connections

### ISSUE THREAD

**Issue by okalldal** [microsoft/vscode#208998]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: insiders build as of March 27
- OS Version: 

Steps to Reproduce:

1. `code-insiders serve-web --host 0.0.0.0 --port 8080 --server-base-path=/ides/foo`
2. open a local browser and enable developer tools
3. access the server on http://localhost:8080/ides/foo
4. Inspect network connections and check WSS connections
5. These do not have the base server prefix

As a consequence, the following does not work:

Through nginx proxy, for example, when requesting https://foo.example.com/ides/foo, a wss error occurs. By checking the browser console, you can see the wss error, and the request address is wss://[foo.example.com/oss-xxxx](http://foo.example.com/oss-xxxx), which does not include the server base path URI path.

An example configuration for nginx proxy is as follows:

upstream vscode {
  server  [192.168.0.100:8888](http://192.168.0.100:8888/);
}
server {
   servername [foo.example.com](http://foo.example.com/);
   location / {
            proxy_pass http://vscode/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
      }
}

Related issue: https://github.com/microsoft/vscode/issues/208278

**Comment by aeschli** [comment]
`code-insiders serve-web --server-base-path=/ides/foo`

![image](https://github.com/microsoft/vscode/assets/6461412/dab1218b-273b-4769-bab7-21172e4d8030)

**Comment by aeschli** [comment]
That said, I have a problem when running with `0.0.0.0`:
`code-insiders serve-web --host 0.0.0.0 --port 8080 --server-base-path=/ides/foo`
![image](https://github.com/microsoft/vscode/assets/6461412/05d60105-5f14-4f2e-bdba-e7e10ccff98c)

**Comment by aeschli** [comment]
I checked again, the websocket connect uses the server-base path when running `code-insiders serve-web --server-base-path=/ides/foo`
