### ISSUE TITLE
Running c++ on vs code

### ISSUE THREAD

**Issue by rireddy12** [microsoft/vscode#208975]
[c_cpp_properties.json](https://github.com/microsoft/vscode/files/14784974/c_cpp_properties.json)
This issue is happening when i enter a input and try to run it is kept on running but not showing the output. It only runs hello world program. I even uninstalled, restarted but issue is not solved. Also, there is problem in the .vscode folder of c++.
Hope u help me resolve.
![image](https://github.com/microsoft/vscode/assets/114018271/60c18375-c01c-4142-9b56-3a4d311832e8)
![image](https://github.com/microsoft/vscode/assets/114018271/3a61534a-b9d5-48cb-9979-356c45173c25)
![image](https://github.com/microsoft/vscode/assets/114018271/309a9633-e212-40e7-bd1f-d2d3f1e01097)
![image](https://github.com/microsoft/vscode/assets/114018271/e8557de8-2313-4b4e-b490-879bc703f3fd)
[launch.json](https://github.com/microsoft/vscode/files/14784975/launch.json)
[settings.json](https://github.com/microsoft/vscode/files/14784976/settings.json)
[tasks.json](https://github.com/microsoft/vscode/files/14784977/tasks.json)
Above are generated automatically.

Below are something i added with the help of vscode tutorial..

[c_cpp_properties.json](https://github.com/microsoft/vscode/files/14784978/c_cpp_properties.json)
[launch.json](https://github.com/microsoft/vscode/files/14784979/launch.json)
[settings.json](https://github.com/microsoft/vscode/files/14784980/settings.json)

**Comment by rireddy12** [comment]
[c_cpp_properties.json](https://github.com/microsoft/vscode/files/14784997/c_cpp_properties.json)

**Comment by polaritus9801** [comment]
I've also met this problem in my computer :(

**Comment by rireddy12** [comment]
Then did you solve this problem?

**Comment by roblourens** [comment]
Please file this on the C++ debug extension

**Comment by rireddy12** [comment]
Sorry, I didn't understand
