### ISSUE TITLE
clicking `insert into terminal` toolbar action doesn't hide the widget

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#209067]
1. open terminal chat
2. run a command which yields a code block
3. click the `insert into terminal`  toolbar action button
4. 🐛 the action occurs, but the widget doesn't hide

I'm wondering if we should not have this toolbar 🤔 for the terminal's case.

https://github.com/microsoft/vscode/assets/29464607/f349b973-95d8-493a-8116-f438ef46c977

**Comment by Tyriar** [comment]
Should we be hiding the inline chat widget if focus enters or input occurs in the terminal? What we want to do here may change when we action https://github.com/microsoft/vscode-copilot/issues/4720

**Comment by Tyriar** [comment]
I think it works pretty well here as it shouldn't obscured anymore. The user can always press escape if they want the chat to hide.
