### ISSUE TITLE
Pip Installed Inside VENV Is Showing Module Not Found

### ISSUE THREAD

**Issue by iamBHK** [microsoft/vscode#209050]
Type: <b>Bug</b>

I have created new VENV & activated it, I've used pip install spacy now. But, when I run "import pandas" it is showing module not found. I recently updated, looks like there is an issue when new VENV created.

**VS Details:**
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by eleanorjboyd** [comment]
Hi! Can you try installing spacy using `python -m pip install spacy` to ensure you are doing this install on your venv? What I guess might be happening is you have created this venv, but are referencing your global version of python when you look to install packages. If you have a mac you can use `which python` to check that the python you are attempting to run with is the one you think it is. Let me know if this helps!

**Comment by iamBHK** [comment]
Sorry for late reply, this solution worked. But, I need to lower the Python version itself to 3.11.
So, I have created new venv using python path : Programs\Python\Python311\python.exe -m venv uninstall VIRTNAME

Then installed spacy to get it worked.
