### ISSUE TITLE
Flashing text while generating links in panel chat

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#209056]
Testing https://github.com/microsoft/vscode-copilot-release/issues/645

Version: 1.88.0-insider (user setup)
Commit: 246d700c4604eb5ebdbb561a1a86562bf9217a62
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Open panel chat.
2. Ask `@workspace` where the location of a file is.
3. :bug: It looks like a lot of text suddenly appears and then disappears while becoming a link, reminding me of Zalgo.

**Comment by roblourens** [comment]
Can you share the specific example?

**Comment by rzhao271** [comment]
Doesn't repro now :+1:
