### ISSUE TITLE
Keyboard mapping for some special features

### ISSUE THREAD

**Issue by polaritus9801** [microsoft/vscode#209085]
Type: <b>Feature Request</b>

When I'm writing code I discover that it's quite often to meet the case when I want to choose the standby choice in the auto completion. If there is a command for me to be mapped from keyboard, like Ctrl+2 choose the second suggestion, etc. it will be a lot better. Thousand of thanks.

Besides, I also hope vscode could provide the more open key mapping methods, for example for vim users like me could use Alt+A as 1, Alt+S as 2, and so on, then I can use direct numbers 123 to choose auto-complete choice

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes: Unsupported

**Comment by ulugbekna** [comment]
> Besides, I also hope vscode could provide the more open key mapping methods, for example for vim users like me could use Alt+A as 1, Alt+S as 2, and so on, then I can use direct numbers 123 to choose auto-complete choice

This should already be possible with standard keyboard shortcuts. You can open your keybindings as JSON and add a new keybinding such as the one below

```
  // ...
  {
    "key": "alt+s",
    "command": "type",
    "args": {
      "text": "1"
    },
    "when": "editorTextFocus && !editorReadonly"
  },
  // ...
```

vscode-vim extension allows creating keybindings as well in its own way, eg 

`gt` to go to type definition -- In `settings.json`:

```
{
      "before": ["g", "t"],
      "commands": [
        {
          "command": "editor.action.goToTypeDefinition"
        }
      ]
    },
```

----

> When I'm writing code I discover that it's quite often to meet the case when I want to choose the standby choice in the auto completion. If there is a command for me to be mapped from keyboard, like Ctrl+2 choose the second suggestion, etc. it will be a lot better. 

Personally, I find it a lot easier (as a vscode-vim user myself) to press arrow down than reach for ctrl+1, but you can find an existing feature request or create a new one that proposes a new vscode command that allows selecting n-th completion suggestion as an argument. You'd be able to do then something like this


```
{ "key": "ctrl+1", "command": "acceptNthSuggestion", "args": { n: 1 } } 
```
