### ISSUE TITLE
在过去 5 分钟内，TypeScript 语言服务意外中止了 5 次

### ISSUE THREAD

**Issue by E00n** [Microsoft/vscode#20902]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|project-manager|alefragnani|0.13.2|
|GBKtoUTF8|bukas|0.0.2|
|vscode-npm-script|eg2|0.1.8|
|vscode-npm|fknop|3.3.0|
|csharpextensions|jchannon|1.2.0|
|Angular1|johnpapa|0.1.16|
|sublime-babel-vscode|joshpeng|0.2.4|
|language-haskell|justusadam|1.4.4|
|vscode-rust|kalitaalexey|0.3.6|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.5.3|
|vetur|octref|0.3.1|
|java|redhat|0.0.10|
|vscode-icons|robertohuertasm|7.2.0|
|vim|vscodevim|0.5.2|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by smallp** [comment]
One of these extensions have error, so the language server has stoped. You should find and disable the extension that has error.

**Comment by jrieken** [comment]
Sorry, we don't have a crystal ball and don't know what you have meant by this issue. Please update the issue with steps to reproduce and we will reopen it.
