### ISSUE TITLE
[Bug] Can't search chats in quick open

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#209061]
I have a chat open:
![image](https://github.com/microsoft/vscode-copilot-release/assets/28700378/9476c6d9-5610-4c73-a974-7148a949fbfc)
But it can't be found after typing the keywords:
![image](https://github.com/microsoft/vscode-copilot-release/assets/28700378/3331c5d1-0088-4c2f-a56a-2b30655d3904)

**Comment by tcostew** [comment]
Can I be assigned to this?

**Comment by wenfangdu** [comment]
@tcostew Thanks for dropping by, you can start a PR without being assigned.

**Comment by bpasero** [comment]
This is intentional, if you want to strictly search through editors, there are pickers that only list editors.

**Comment by wenfangdu** [comment]
@bpasero Why intentional? With multiple chats open and tons of editors mixed in, it's very hard to pick the wanted chat.

**Comment by bpasero** [comment]
The standard file picker shows recently opened editors at the top when you do not search. This is already a bit inconsistent in that we include non-file editors here as well (for example chats or terminals). But the intent of the picker is to provide file search once you start typing, as you can see from the description:

![image](https://github.com/microsoft/vscode/assets/900690/337c7fa5-7f56-4d54-bbd8-3cf2946489fb)

As such, we exclude results from the list that are not file based (such as chat, terminal).

The `edt <search>` picker is meant for searching through all opened editors:

![image](https://github.com/microsoft/vscode/assets/900690/c6159049-915e-4cde-8068-232c6040a0b6)

**Comment by wenfangdu** [comment]
@bpasero Thanks for the history recap, but I think if you remove the constraints i.e. terminal and chat editors can be searched through typing, it does no harm, right? Since it's an extension not a regression.

**Comment by bpasero** [comment]
Yeah, I think I am not opposed to changing this but then we should include everything from recently opened and drop the check for files.

**Comment by wenfangdu** [comment]
@bpasero Yes, please do so, is there an estimated date for this change? `search.exclude` should still apply though.

**Comment by TylerLeonhardt** [comment]
Verification:
* Say some stuff in chat
* `Open Chat in Editor`... 
* Open any other normal type of file
* cmd/ctrl+p to show recent editors

You should see the chat there and you should be able to search for it.
