### ISSUE TITLE
File models get disposed when contents change on disk

### ISSUE THREAD

**Issue by 928PJY** [Microsoft/vscode#20901]
- VSCode Version:1.8.1
- OS Version:win10

Command "vscode.previewHtml" can only provide two ways to preview a Html resource.
The one is providing Url, but when the Html file changes, how to update the preview content? Is there some sample code?
The second is providing a virtual resource, but when I want to use some js files to render this Html, do I have to give the absolute path? If so, How can I do when js file reference to another js file(in this case, it have to be a relative path(?)).

**Comment by 928PJY** [comment]
I am writing an extension which will preview the [DFM](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html), and what I want to preview is a virtual Html resource, this Html will reference to some js files(in relative path), but the VSCode will translate it into absolute path based on the markdown file, I fix this problem by translate the js files's path into absolute path, but when this js files reference to other files, I don't know how to do.Maybe you can provide some advice.

**Comment by 928PJY** [comment]
When I use the first ways to preview Html(provide a Uri), how to trigger the update event.

**Comment by jrieken** [comment]
When the URI points to a file on disk and that file is inside the current workspace/folder updating happens automatically, when you are showing a virtual resource its content provider must signal changes via an event. Therefore a `TextDocumentContentProvider` can implement a `onDidChange` event which in return will be honoured by the editor. There is an example here: https://github.com/Microsoft/vscode-extension-samples

**Comment by 928PJY** [comment]
There is a small [sample](https://github.com/928PJY/extensionSample),  it doesn't behavior as what you said.

**Comment by jrieken** [comment]
Can you reduce that to something small and simple?

**Comment by 928PJY** [comment]
Yes! Sample is smaller!

**Comment by 928PJY** [comment]
I am going to tell you what I am doing, I was writing an extension, which is going to preview DocFx. Extension pass the markdown content to a child process, which will use DocFx engine to render the markdown file into Html, this Html will be written to a temp file, which is the resource of preview page, But When this temp Html changed, Nothing happens to preview page.

**Comment by jrieken** [comment]
Is this [file](https://github.com/928PJY/extensionSample/blob/sample/src/extension.ts#L31) inside the workspace or did you open the file by itself? Can you open it in source and check if it updates when it is changed on disk?

**Comment by 928PJY** [comment]
The situation is, this file is inside the workspace, but not be opened, and When it is changed by another editor or process, it can't update automatically.

**Comment by jrieken** [comment]
Thanks for sticking with me. There is actually something wrong. The preview updates as long as the file also open in an editor and stops after that. I need to investigate..

**Comment by jrieken** [comment]
This happens because the [`TextFileEditorModelManager`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts#L135) decides to dispose the model instead of updating it. 

>// Dispose models that got changed and are not visible. We do this because otherwise
// cached file models will be stale from the contents on disk.

I don't understand that. There is the `IModelService` but this comment seems to talk about another cache. My expectation was that the workbench listens on file events, updates models (`IModel`) that are alive, such that listeners to that can do their work

**Comment by 928PJY** [comment]
Thank you for reopening this issue, I have already solved my problem through another way, but I still want to see this problem can be fixed, thank you!

**Comment by bpasero** [comment]
Related to https://github.com/Microsoft/vscode/issues/17888

I will revisit this in March given you seem to have a workaround and this is not a recent regression.

**Comment by bpasero** [comment]
I fixed the fact that we dispose models when file changes so that we now update the model with the new contents. However due to #17888 this is still not working properly but should be once #17888 is done.
