### ISSUE TITLE
sendChatRequest should support a default model id

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#209001]
Right now the `sendChatRequest` requires an explicit spell out of the model id.
Models will not be available forever, and this means that extensions will always have to update to make sure they are asking for a supported model.

Does it make sense to introduce a "default model id". So the extension can say "give me the default model, I do not care which one exactly, as long as it is supported". That way extensions will not have to update to the latest model, and we will not be in the business of having to mark them as deprecated if they do not update.

What do you think?

fyi @alexdima

**Comment by isidorn** [comment]
But maybe the current default should be `gpt-3.5`?
Because it is fast and less compute intensive (thus it saves server side resources if extensions that do not care use the cheaper one).

**Comment by roblourens** [comment]
> this means that extensions will always have to update to make sure they are asking for a supported model.

I think this is basically a feature- you are going to get different results with different models and it's hard to build a good model-agnostic feature. I don't see how we can pick a default.
