### ISSUE TITLE
Git: focus moves out of list when clicking into changes list

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#20909]
Steps to Reproduce:

1. click into a change with the mouse
2. try to use the keyboard to move up/down

=> not possible because focus moved to diff editor
=> when using mouse, focus should stay inside the list

**Comment by joaomoreno** [comment]
I can't really fix that without having the possibility to run the `open` command and tell it not to take focus. Is this possible?

**Comment by bpasero** [comment]
@joaomoreno got it, this goes into the direction of allowing to open diff editors via `showTextDocument` where you have an option `preserveFocus`. Again I'd say to make `showTextDocument` be richer instead of making the debt'ish `vscode.open` more powerful.

**Comment by joaomoreno** [comment]
Füxed!
