### ISSUE TITLE
Terminal: Parent Folder relative path formatting issue in terminal

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#20900]
This is on Windows and I noticed it on Thursday or Friday. When using a relative parent folder path in the terminal it is causing weird spacing issues when moving the cursor. @Tyriar I wasn't sure if this was an issue in code or upstream

If the cursor is at the end of the line it forces the `..` to join the previous command in the prompt. I added a gif showing the behavior

- VSCode Version: 1.10.0-Insiders
- OS Version:  Windows 10

Steps to Reproduce:

1. Type a command and then a relative parent path like the following `cd ..\path\to\something` 
2. The `..` will have spacing issues with the **cd** depending on where the cursor is.

![issue](https://cloud.githubusercontent.com/assets/6662208/23109356/2cb70694-f6de-11e6-86c4-87a64f99d815.gif)

**Comment by Tyriar** [comment]
I think this should be fixed in the next build, sounds similar to https://github.com/sourcelair/xterm.js/issues/558

**Comment by gerane** [comment]
@Tyriar That sounds like it is what I am seeing.
