### ISSUE TITLE
Error in QuickPick when clicking enter onDidAccept is not called

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode#209074]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0-insider
- OS Version: MacOs

Steps to Reproduce:
In the python and python debugger extension we use the QuickPick, we add an option to accept the value in the input. It was working in stable, but in insiders it doesn't work.

Steps:
1. Open a picker
2. Write some text in the input box, make sure that it match with one option at first.
3. Click enter, to select the text in the input box.
4. The last value that appeared in the list is the one that is selected.

https://github.com/microsoft/vscode/assets/17892325/1e227ee4-87a0-4869-9f62-e08f8bd00f3b

You can check the implementation [here](https://github.com/microsoft/vscode-python-debugger/blob/main/src/extension/common/multiStepInput.ts#L211).

I was debugging the code a little bit, and found that in stable when you press enter, the function `onDidAccept` is called.
But in insider when you press enter instead of call that function, the function `onDidChangeSelection` is called.

**Comment by TylerLeonhardt** [comment]
Verification:
* Install Python extension
* Open a python workspace
* Open the debug pane and click the "create a launch.json file"
* Choose Python Debugger
* Choose Django
* Type ONLY 'b' and notice that "Browse Files" becomes the active item
* Type then, 'z' and notice that the list is empty
* hit ENTER and notice that the launch.json gets created with "bz" in the `"program": "bz"`

**Comment by rzhao271** [comment]
The fix fully resolves https://github.com/microsoft/vscode-python-debugger/issues/287 as well!

**Comment by eamodio** [comment]
Resolves my issue as well.
