### ISSUE TITLE
screen reader VI accessibility bug with f8 key  when using rust

### ISSUE THREAD

**Issue by DJ-Wolfy** [microsoft/vscode#209083]
Does this issue occur when all extensions are disabled?: Yes/No
No

- VS Code Version: 1.87.2
- OS Version: Windows 11 22H2 (x64) build 22621.3155

Steps to Reproduce:
(while using a screen reader, bug known to occur with NVDA)
1. Create a new rust project (cargo new)
2. Enter it with vscode and go into main.rs
3. Delete what is inside main.rs and insert this broken sample, for instance:
```
fn main(){
    let x = 2;
    x += 1;
}
```
4. Press f8 and listen to the error read out to you
5. Try to type something else after your main function.
6. As you type, you will hear a repeated announcement of the error

**Comment by meganrogge** [comment]
This is by design atm. We're considering reworking / allowing fine tuning of this though in the near future.

#188285

**Comment by DJ-Wolfy** [comment]
It is worth noting that the last error read out with f8 is also read out no matter what line you are on, every time you type a character or delete one
