### ISSUE TITLE
Aux window - registration flawed when devtools is opened

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#209073]
1. Set a breakpoint or log here
 https://github.com/microsoft/vscode/blob/e49b522e12d1a55dfe2950af355767c9d5b824aa/src/vs/workbench/contrib/debug/browser/debugToolBar.ts#L195

2. Move or copy a file into a new floating window
3. Switch between them a few times. The event fires a couple times but then stops firing

**Comment by bpasero** [comment]
@connor4312 does it reproduce without having devtools opened in any of the windows?

**Comment by deepak1556** [comment]
> I keep track of auxiliary windows and so far I have been using webContents.id as identifier, assuming it would always match BrowserWindow.id

That is not the intended contract in the runtime, a BrowserWindow can have multiple WebContents at any point and their ids are independent. WebContent ids are incremental within the same process, so it purely depends on the creation order.

> I need a different way how to figure out the window ID of a floating window...

You can use [BrowserWindow.getWebContents](https://github.com/electron/electron/blob/main/docs/api/browser-window.md#browserwindowfromwebcontentswebcontents) to get the owner window and that should give you the right id.

**Comment by bpasero** [comment]
@deepak1556 I tried that, but at the time `web-contents-created` fires, `BrowserWindow.fromWebContents` returns `undefined`. In other words, the web content is being created before the window is there...

**Comment by deepak1556** [comment]
I think maintaining a `Map<WebContents, AuxWindow>` would suit this scenario, you can access the webContents a BrowserWindow owns via `window.webContents` and this will be valid even at `browser-window-created`. Should be reliable than id.

**Comment by bpasero** [comment]
Yeah, an alternative would be to pro-long aux-window handshake between main and renderer until the `BrowserWindow` is there but I think thats overkill. I will see to keep aux windows identified by `webContent.id`. Its a bit inconsistent because both aux and main window share the same base class and the one will use `webContents.id` and the other `BrowserWindow.id`...
