### ISSUE TITLE
find in terminal highlights the mismatched parts when terminal output scrolls because of new output

### ISSUE THREAD

**Issue by a-sansanwal** [microsoft/vscode#209093]
Type: <b>Bug</b>

Create a test app which outputs foo and bar repeatedly in the terminal console after a sleep of 1 second in loop.
Search for foo or bar.
As the output scrolls the highlighted blocks do not update and they highlight the wrong things now.

Reproduced on mac os Sonoma 14.4.1

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin x64 23.4.0
Modes:
Remote OS version: Linux x64 5.4.0-172-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 5f4c1a6a-53b0-4f59-9815-a4ed521b13df|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.156.142.82|
|OS|Linux x64 5.4.0-172-generic|
|CPUs|Intel(R) Xeon(R) W-2255 CPU @ 3.70GHz (16 x 1204)|
|Memory (System)|55.14GB (18.76GB free)|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.17.2
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
conanlight|Son|1.4.0
ninja|sur|0.0.1
vim|vsc|1.27.2
vscode-bond|yiw|0.0.10
gitlens|eam|14.9.0
copilot|Git|1.176.0
copilot-chat|Git|0.13.1
csdevkit|ms-|1.4.29
csharp|ms-|2.22.5
vscode-dotnet-runtime|ms-|2.0.3
vscodeintellicode-csharp|ms-|0.1.26
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.2
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:30996668
dsvsc021:30996838
g1icg217:30999571

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

If it does repro there, pls attach a gif.
