### ISSUE TITLE
Go to File... preview of currently highlighted file in drawer

### ISSUE THREAD

**Issue by narkowicz** [Microsoft/vscode#20903]
Feature request: this is a helpful feature of Sublime Text currently missing in VS Code.

When the 'Go to File' tool drawer is open, preview the file that is currently highlighted in the drawer in the editor pane (or the pane that has focus, if using split editor) behind the file selection drawer.

Allows easy previewing and selection of correct file before opening; especially useful where files have similar names and / or paths.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by narkowicz** [comment]
Had searched, am still unable to find duplicate. Sorry for the inconvenience.

**Comment by johnste** [comment]
@narkowicz I have the same request and I believe this is the original issue https://github.com/Microsoft/vscode/issues/8939

Took me a while to find, the title could use some work
