### ISSUE TITLE
I meet loop warning!

### ISSUE THREAD

**Issue by panxw** [Microsoft/vscode#20904]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.1|
|debugger-for-chrome|msjsdiag|2.5.3|
|ReactSnippetsStandard|TimonVS|1.0.3|
|vscode-react-native|vsmobile|0.3.1|

---

Steps to Reproduce:

1.
2.

**Comment by mrmlnc** [comment]
Please, provide more detailed information and steps to reproduce your problem.

**Comment by jrieken** [comment]
Sorry, we don't have a crystal ball and don't know what you have meant by this issue. Please update the issue with steps to reproduce and we will reopen it.
