### ISSUE TITLE
TreeView `reveal` gets stuck if `onDidChangeTreeData` was fired with empty array

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#209043]
Type: <b>Bug</b>

To repro the issue use this provider:
```typescript
import {
  EventEmitter,
  ExtensionContext,
  ProviderResult,
  TreeDataProvider,
  TreeItem,
  TreeItemCollapsibleState,
  commands,
  window,
} from "vscode";

class TestTreeViewProvider implements TreeDataProvider<string> {
  private _onDidChangeTreeData: EventEmitter<
    string | void | string[] | null | undefined
  > = new EventEmitter<string | void | string[] | null | undefined>();

  public fireDataChanged(item?: string | string[] | null) {
    this._onDidChangeTreeData.fire(item);
  }

  onDidChangeTreeData = this._onDidChangeTreeData.event;
  getTreeItem(element: string): TreeItem | Thenable<TreeItem> {
    if (element.includes("leaf")) {
      return new TreeItem(element, TreeItemCollapsibleState.None);
    }
    if (element.includes("node")) {
      return new TreeItem(element, TreeItemCollapsibleState.Collapsed);
    }
    return new TreeItem(element, TreeItemCollapsibleState.Expanded);
  }
  getChildren(element?: string | undefined): ProviderResult<string[]> {
    if (element === undefined) {
      return ["root1", "root2"];
    }

    if (element === "root1") {
      return ["node1"];
    }

    if (element === "root2") {
      return ["node2"];
    }

    if (element === "node1") {
      return ["leaf1"];
    }

    if (element === "node2") {
      return ["leaf2"];
    }
  }
  getParent(element: string): ProviderResult<string> {
    if (element === "node1") {
      return "root1";
    }

    if (element === "node2") {
      return "root2";
    }

    if (element === "leaf1") {
      return "node1";
    }

    if (element === "leaf2") {
      return "node2";
    }
    return undefined;
  }
}

export function activate(context: ExtensionContext) {
  const provider = new TestTreeViewProvider();
  const view1 = window.createTreeView<string>("treeview-test", {
    treeDataProvider: provider,
  });

  context.subscriptions.push(
    view1,
    commands.registerCommand("treeview1.switch", async () => {
      if (view1.selection.length > 0 && view1.selection[0] === "node1") {
        await view1.reveal("node2");
      } else {
        await view1.reveal("node1");
      }
    })
  );

  // The empty array below triggers the forever await issue on treeview.
  provider.fireDataChanged([]);
}

export function deactivate() {}
```

The bug is in the `debounce` here, the `current.element` will be empty, so nothing gets pushed into the `result.elements`. Later in the `onDidChangeData` we skip progressing the refreshQueue if the `result.elements` are empty. 
https://github.com/microsoft/vscode/blob/8e386a6a9607d541a37f34a11a98e19c7f1f5829/src/vs/workbench/api/common/extHostTreeViews.ts#L363-L396

That blocks this in `reveal` API: https://github.com/microsoft/vscode/blob/8e386a6a9607d541a37f34a11a98e19c7f1f5829/src/vs/workbench/api/common/extHostTreeViews.ts#L429

If there is a new `onDidChangeData` with actual elements after that, it does recover. 

VS Code version: Code - Insiders 1.88.0-insider (8c8105002c089e657402b0f7ced80b2ecae6870c, 2024-03-11T11:16:23.777Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (18.46GB free)|
|Process Argv|--folder-uri file:///c%3A/GIT/TPI/mar2024/treeview1 --crash-reporter-id 2dc83bb9-7be1-4f42-aae4-df697150aa38|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
vscode-eslint|dba|2.4.4
gitlens|eam|14.9.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
copilot|Git|1.176.793
copilot-chat|Git|0.14.2024031201
remotehub|Git|0.63.2024031101
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.85.2024032704
vscode-docker|ms-|1.29.0
remote-containers|ms-|0.353.0
remote-ssh|ms-|0.110.0
remote-ssh-edit|ms-|0.86.0
remote-ssh-explorer|ms-|0.48.0
remote-wsl|ms-|0.88.0
vscode-remote-extensionpack|ms-|0.25.0
azure-repos|ms-|0.39.2024031101
extension-test-runner|ms-|0.0.6
hexeditor|ms-|1.9.14
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.41.2024022202
remote-server|ms-|1.5.1
code-spell-checker|str|3.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:30784851
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
bf62j303:30968145
cppperfnew:30980852
d34g3935:30961436
fegfb526:30952798
bg6jg535:30979844
ccp1r6:30958151
pythonait:30973460
666c4381:30973073
7ghi1836:30988844
gd77d436:30999572

```

</details>

**Comment by karthiknadig** [comment]
Expected:
https://github.com/microsoft/vscode/assets/3840081/79edf9ec-8276-4e13-a81e-706479586134

Actual:
https://github.com/microsoft/vscode/assets/3840081/3b4ac4bf-d7fd-4b5c-8a56-ff00ee30fdb4

**Comment by alexr00** [comment]
Nice find, and thanks for the analysis!

**Comment by TylerLeonhardt** [comment]
Awesome repro steps @karthiknadig! Even better if you included the `contributes` section of the package.json, but still really easy to verify.
