### ISSUE TITLE
Interactive window accessibility issues for SR users

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#209140]
cc @jooyoungseo

1. select some code in an editor
2. use the context menu to `Run In Interactive Window`
3. the focus does not move to the interactive window and nothing is announced
4. if one navigates to the interactive window, there's no aria label in the input box and no info about how to reach the cells

We should:

- [x] #229181
- [x] #229182
- [x] #229180
- [x] #229178
- [x] #229177
- [x] #232421
- [x] #233237

**Comment by karthiknadig** [comment]
Marking this as verified, since each item under it has the "verification-needed" set or is "verified".
