### ISSUE TITLE
Hide Panel (X) tooltip should include key binding

### ISSUE THREAD

**Issue by roysmith** [microsoft/vscode#209193]
Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:57.520Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 22.6.0

When you hover over the "X" icon to close the panel, you get a tooltip that says "Hide Panel".  I was looking for how to close it in a single keystroke and assumed that since there was no associated key binding shown in the tooltip, none existed.  Eventually I discovered it was Command-J, but had to scrub all the menus to find that; it really should be shown right in the tooltip.

I think what's really going on is that Command-J isn't actually bound to Hide Panel it's bound to Toggle Panel Visibility.  Either way, from a U/X point of view it still makes sense to show me Command-J when I hover over the "X" icon.  Maybe a better fix would be to have that icon execute Toggle Panel Visibility.  To the user, the effect would be the same, and you'd get the keybinding in the tooltip.

<img width="333" alt="Screenshot 2024-03-30 at 10 27 45 AM" src="https://github.com/microsoft/vscode/assets/704337/86e2d343-323a-4abc-be83-c13fcb15c67c">

**Comment by bpasero** [comment]
It does show for me, though its not defined by default:

![image](https://github.com/microsoft/vscode/assets/900690/f7a28416-4185-4ad3-ba87-c440e79e32a2)

**Comment by benibenj** [comment]
We do not seem to have a proper way of having one keybinding for two menus with different labels. There is the toggle condition on Action2 items which could help with this, however, there seems to be some rendering glitches currently.
