### ISSUE TITLE
ISSUE for assignment

### ISSUE THREAD

**Issue by CalebMason45** [microsoft/vscode#209127]
ADD ISSUE DESCRIPTION HERE
Node 16 needs to be node 20

Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by IllusionMH** [comment]
Is it from some course?

This is issue tracker for VS Code editor itself.
Please use proper feedback channel for your course if it's not related to editor.
