### ISSUE TITLE
[i18n] Fix ru locale

### ISSUE THREAD

**Issue by buzzzzer** [Microsoft/vscode#20914]
- VSCode Version: 1.9.1
In the main menu, the russian translation looks ugly & does not correspond generally accepted standards.

En | ru locale now | ru locale fix 
------------ | ------------- | ------------ 
View|Просмотреть|Вид
Edit|Изменить|Правка
Go|Перейти|Переход
Selection|Выбор|Выделение

PS. Where you are translating?
Maybe it makes sense to use the special services, such as transifex.com, etc ?

**Comment by johnliu2016** [comment]
@lukaschal, general menu translation

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
These fixed as suggested.

SRC: &amp;&amp;Edit
TGT: &amp;&amp;Правка

SRC: &amp;&amp;Go
TGT: &amp;&amp;Переход

SRC: &amp;&amp;View
TGT: &amp;&amp;Вид

**Comment by lukaschal** [comment]
@buzzzzer Please, is it possible to add ENU/RUS screenshot with "Selection" string to see context of this term ?

**Comment by buzzzzer** [comment]
@lukaschal, yes.
sublime: Selection > Выделение
![image](https://cloud.githubusercontent.com/assets/1981785/23553867/a96ec484-0033-11e7-8830-71abf4a1c225.png)
Adobe Illustrator: Select > Выделение
![image](https://cloud.githubusercontent.com/assets/1981785/23553902/d835e270-0033-11e7-9f0f-30c325b76829.png)

**Comment by lukaschal** [comment]
Fixed as suggested.

File: src\vs\code\electron-main\menus.nls.resx
ID: ".resx", 0; "mSelection"
SRC: &amp;&amp;Selection
TGT: &amp;&amp;Выделение

**Comment by aldonetti** [comment]
and now all translations of VSCode *are* managed in Transifex, so improved translations/suggestions can be added there. see this for more info https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project (and thank you @buzzzzer for raising the issue and for already suggesting these changes in Transifex!)
