### ISSUE TITLE
I raised an issue 2 days ago and I haven't been assisted!!!!!

### ISSUE THREAD

**Issue by Sonyapap** [microsoft/vscode#209176]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by RedCMD** [comment]
its the weekend
you should expect a response late next week

also you should link your previous issue https://github.com/microsoft/vscode/issues/209177

**Comment by IllusionMH** [comment]
> I'm receiving a zero grade

This is issue tracker for VS Code editor itself, not support forum. You should contact support for your course, not maintainers of editor.

**Comment by Sonyapap** [comment]
> > I'm receiving a zero grade
> 
> This is issue tracker for VS Code editor itself, not support forum. You should contact support for your course, not maintainers of editor.

can you please provide their contact info?

**Comment by RedCMD** [comment]
one of these
![image](https://github.com/microsoft/vscode/assets/33529441/9705bb4c-954d-464b-a7a2-8e82fd2e41c3)

otherwise we have no idea
as VSCode does not provide your course
