### ISSUE TITLE
Instructions for debugging Code dev builds

### ISSUE THREAD

**Issue by adelphes** [Microsoft/vscode#20917]
So I'm following the instructions in [How to Contribute](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source) and attempting to build and debug a dev version of VSCode, but there seems to be steps missing. I can't figure out if it's supposed to be like that or if I'm missing something.

I've successfully cloned, npm-installed, built and executed a dev version of Code and now I'm trying to get my stable (1.9.1) version to attach to the dev version.

The instructions say:

> Using VSCode
> 
> Install the Debugger for Chrome extension. This extension will let you attach to and debug client side code running in Chrome.
> Launch the development version of Code with the following command line option:
> OSX and Linux
> 
> ./scripts/code.sh --remote-debugging-port=9222
> Windows
> 
> scripts\code --remote-debugging-port=9222
> Choose the Attach to VSCode launch configuration from the launch dropdown in the Debug viewlet and press F5.
> 

But the Attach stage doesn't work. The first error is that the Debugger for Chrome extension requires a URL in the config - but there's no URL entry in the Attach config of `launch.json`.
So I guess a URL to add and I get a second error - this time telling me that it cannot connect and also helpfully providing me with a (very long!) `file:///` URL that I appear to need.
I replace the URL in launch.json with this new file URL and it still fails with the same error.

After reading the Debugger for Chrome page, I find that the URL entry supports wildcards - I add a `*` to the end of the URL and it successfully attaches.

Is this correct? Was I supposed to configure something else? Should it just work without the URL parameter? If not, could you update the docs.

**Comment by MartinSGill** [comment]
The following worked for me (although I'm using Windows). Maybe add this to the wiki page?

![image](https://cloud.githubusercontent.com/assets/2271740/23174244/0c91ee86-f85c-11e6-9669-5958a19dabf3.png)

**Comment by roblourens** [comment]
I think it's a bug that the Chrome extension is requiring a URL - will fix. I always use the Launch config, which I think is more convenient. I'll change the wiki to recommend that config.

**Comment by roblourens** [comment]
Edited the wiki and I also have an issue for the bug of requiring a URL, which I didn't realize was a regression: https://github.com/Microsoft/vscode-chrome-debug-core/issues/164
