### ISSUE TITLE
assistance needed

### ISSUE THREAD

**Issue by Sonyapap** [microsoft/vscode#209177]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

Hello,

Could you please assist with the issue below?
I attached screenshots of the workspace, I am not getting any grades although my queries are correct and I retrieve all requested tables, I do not even get the green or red checkmark, could you please assist?

The 1st screenshot is my first try([image]). and the screenshots 2, 3, 4 are my 2nd try. For both I'm receiving a zero grade but all I'm doing is correct and the requested tables and data is being pulled out.

image (3)
image (2)
image (1)
image

Version

**Comment by RedCMD** [comment]
dup of https://github.com/microsoft/vscode/issues/208950
