### ISSUE TITLE
path.dirname is wrong for files in root

### ISSUE THREAD

**Issue by snails118** [Microsoft/vscode#20911]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|javac-linter|faustinoaq|1.2.2|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.2|
|composer|ikappas|0.5.0|
|format-php|Kasik96|1.1.2|
|java|redhat|0.0.10|
|java-imports-snippets|tushortz|0.0.1|
|java-snippets|tushortz|0.0.1|

---

Steps to Reproduce:

1. 不能在打开的根文件夹下,直接新建文件和文件夹;
2.

**Comment by jrieken** [comment]
please file issues in englich

**Comment by King66** [comment]
on windows, open VSCode at "C:\" or  "D:\", then create a file or folder, you have to refresh to see the new file or folder...
