### ISSUE TITLE
A dedicated color item for sidebar title

### ISSUE THREAD

**Issue by d-mahard** [microsoft/vscode#209164]
I know this is a request of a very cosmetic feature, but some of the users (at least myself) may want to set the color of the **sidebar title** (not the sidebar _section header_ - this one already has its own color item) differently from the _sidebar background_ itself. So basically I would love to have the color item `sideBarTitle.background`. This apply for both the primary and secondary sidebar. 

Thank you!

![image](https://github.com/microsoft/vscode/assets/146386738/1151334d-99bb-429b-9674-8d048cc56fdd)

_The theme I use above is [wine bar monokai](https://marketplace.visualstudio.com/items?itemName=d-mahard.wine-bar-monokai) - (I am the maintainer 😁)._

**Comment by benibenj** [comment]
Sounds reasonable to me especially as we also support setting section header background. I added `sideBarTitle.background`

**Comment by benibenj** [comment]
Verification steps:
 1. Open settings file and add: ```
"workbench.colorCustomizations": {
        "sideBarTitle.background": "#ff0000"
    },
```
2. See how the background color of the title section in the primary and secondary sidebar turn red
