### ISSUE TITLE
File search takes time to search 

### ISSUE THREAD

**Issue by delockdown** [Microsoft/vscode#20910]
- VSCode Version: 1.9.1 
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Open up a project with so many file
2. Use 'Go to File' option to search a file 

If this searching file is not perviously searched, it take time to load up the file that matches  for particular string. This is bad, there should be something like fuzzy search which is plugin for Atom.

**Comment by jens1o** [comment]
Naaa... That would increase the ram usage and so you're spending a lot of energy(laptops!11) for just a faster search. I disagree with you.

**Comment by chrmarti** [comment]
Could be addressed with #15382
