### ISSUE TITLE
Debug javascript angular-cli, breakpoints ignored

### ISSUE THREAD

**Issue by doczoidberg** [Microsoft/vscode#20918]
- VSCode Version: 1.9.1
- OS Version: windows 10

Steps to Reproduce:

1. create angular-cli project with some components (e.g. https://github.com/doczoidberg/ang1)
2. install chrome debug extension and use it 1.9.1
ng serve
attach debugger in vs code

debugging console works in vs code so that I think chrome is attached to vs code right.

but when settings a breakpoint in app.component.ts line 9 vs code says 'Breakpoint ignored because generated code could not be found (source map problem?)

this problem does not occur in webstorm 2017. 
Breakpoints are sometimes also set on the wrong line in VS code

**Comment by weinand** [comment]
@doczoidberg how does the launch configuration you are using look like?

**Comment by doczoidberg** [comment]
```
      {
            "name": "9222 attach Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "attach",
             "port": 9222,
            "url": "http://localhost:4200/*",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "sourceMapPathOverrides": {
                     "webpack:///./*": "${workspaceRoot}/*"
            }
        },
```

**Comment by weinand** [comment]
Since this is an issue with the Chrome debugger, I'll move the issue to the correct repository.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-chrome-debug#365

**Comment by doczoidberg** [comment]
I had still to delete the %temp% folder on win64 to get the breakpoints working correct. I think this is a vscode issue and not the plugin issue?
