### ISSUE TITLE
Unable to open remote WSL folder

### ISSUE THREAD

**Issue by ppradeepk** [microsoft/vscode#209152]
Type: <b>Bug</b>

I am trying to select a folder in the drop down for the 'Open Folder' menu and clicking on any of the folder on the remote WSL ubuntu instance does nothing.

VS Code version: Code - Insiders 1.88.0-insider (aa25485166449aa0f9eb8ebd8d0b70376108633c, 2024-03-28T22:10:25.599Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.75GB (21.77GB free)|
|Process Argv|--crash-reporter-id 58f6f73e-a1a7-4a67-ae23-9bad94ab626d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|31.22GB (30.18GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.353.0
remote-wsl|ms-|0.88.0
cmake-language-support-vscode|jos|0.0.9
vscode-docker|ms-|1.29.0
csdevkit|ms-|1.4.29
csharp|ms-|2.22.5
vscode-dotnet-runtime|ms-|2.0.3
debugpy|ms-|2024.3.10881615
python|ms-|2024.3.10871011
vscode-pylance|ms-|2024.3.102
azurecli|ms-|0.6.0
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.9.10
powershell|ms-|2024.0.0
rust-analyzer|rus|0.3.1896
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aacf:30263846
vscod805cf:30301675
vsaa593:30376534
py29gd2263:30784851
vscaat:30438846
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
d6fi2104:30968146
cppperfnew:30980852
d34g3935:30961436
fegfb526:30952798
bg6jg535:30979844
ccp1r6:30958151
pythonait:30973460
7ghi1836:30988844
gd77d436:30999572

```

</details>

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/208937
