### ISSUE TITLE
Improve viewing large text output

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#209158]
Type: <b>Feature Request</b>

While experimenting with LLMs in Jupyter notebook, I often need to validate the text output (custom prompt, documents retrivied, etc). I like the fact that it's rendered in a scrollabe output and I can search text in it. However in order to read through them line by line, I found myself repeatedly:

* Click in the output
* Cmd+A
* Cmd+C
* Cmd+N to open a new text editor
* Cmd+V

Before we have the scrollable output support, we render a command "open in text editor" in the output which can be really convinient, but I'm not sure I want to sacrifice scrollable output for it though.

VS Code version: Code - Insiders 1.88.0-insider (aa25485166449aa0f9eb8ebd8d0b70376108633c, 2024-03-28T22:10:25.599Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by rebornix** [comment]
We can now right click on a large text output and open directly in a text editor 

<img width="741" alt="image" src="https://github.com/user-attachments/assets/b9b3359a-0e82-471e-83d5-1278afba5675">

**Comment by rzhao271** [comment]
I encountered https://github.com/microsoft/vscode-jupyter/issues/15639 but I believe it's due to my setup. Taking the verified label off for someone else to verify.

**Comment by rzhao271** [comment]
I'm confused on how the feature works.
I have set up a Conda environment on my Windows machine and run a notebook with a single cell:
```py
for i in range(1000):
    print(5 * i)
```

I see the following behaviour:
If I run the notebook, close the notebook, and open it again, then I can right-click and view the output in a text editor. ✅ 
If I change the 5 to a 6, run the notebook, and try to right-click and view the output in a text editor, nothing happens. :bug:

**Comment by rebornix** [comment]
Should be fixed now.
