### ISSUE TITLE
[i18n] 'Select icon theme' in RU locale has ugly translation

### ISSUE THREAD

**Issue by zlumyo** [Microsoft/vscode#20915]
- VSCode Version: 1.9.1
- OS Version: Any

Menu item at 'File' -> 'Settings' -> 'Select icon theme' has unnatural translation "Тема значка файла".
It would be better look something like "Выбрать тему иконок" or "Тема иконок файлов".

**Comment by buzzzzer** [comment]
nearby "Фрагменты пользователя"  should be "Пользовательские сниппеты"
"Выберите язык для фрагмента." should be "Выберите язык для сниппетов"

and many other places :(

 contribute i18n via issue very uncomfortable
ping #4109

**Comment by johnliu2016** [comment]
@lukaschal,  linguistic quality issue in Subtenant: VSCode_MonacoTools

"File icon theme"
ResID: 0;"themes.contribution.js"\0;"Strings"\".resx", 0;"selectIconTheme.label" 
File: src\vs\workbench\parts\themes\electron-browser\themes.contribution.nls.resx.lcg 

ResID 0;"themeService.js"\0;"Strings"\".resx", 0;"iconThemeError" 
File: src\vs\workbench\services\themes\electron-browser\themeService.nls.resx.lcg 
Subtenant: VSCode_MonacoTools

"User &amp;&amp;Snippets"
ResID: 0;"menus.js"\0;"Strings"\".resx", 0;"miOpenSnippets" 
File: src\vs\code\electron-main\menus.nls.resx.lcg 

"Select Language for Snippet"
ResID: 0;"snippets.contribution.js"\0;"Strings"\".resx", 0;"openSnippet.pickLanguage" 
File: src\vs\workbench\parts\snippets\electron-browser\snippets.contribution.nls.resx.lcg

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Fixed.

SRC: File Icon Theme
TGT: Тема значков файлов

SRC: User &amp;&amp;Snippets
TGT: &amp;&amp;Фрагменты кода пользователя

SRC: Select Language for Snippet
TGT: Выберите язык для фрагментов кода
