### ISSUE TITLE
Cannot copy/paste in integrated terminal running tmux

### ISSUE THREAD

**Issue by rmgpinto** [microsoft/vscode#209191]
In my terminal, Alacritty, I simply select the text I want to copy and the selection goes automatically to my clipboard.
It doesn't work in VSCode's Integrated Terminal running tmux.

I've tried the following options without success:
`"terminal.integrated.macOptionClickForcesSelection": true`
`"terminal.integrated.rightClickBehavior": "nothing"`

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2 arm64
- OS Version: MacOS Sonoma 14.4.1

Steps to Reproduce:

1. open VSCode
2. open Integrated Terminal
3. run `tmux`
4. try to copy-paste text with mouse

My `tmux.conf`:

```bash
set  -g default-terminal "screen-256color"
set -g status-keys vi
set -g mode-keys   vi
unbind C-b
set -g prefix C-a
set  -g mouse             on
setw -g aggressive-resize on
setw -g clock-mode-style  24
set  -s escape-time       500
set  -g history-limit     2000
```

**Comment by meganrogge** [comment]
I think you're looking for this? `terminal.integrated.copyOnSelection`

**Comment by rmgpinto** [comment]
it works on VSCode integrated terminal, but once I start a `tmux` session it doesn't work.

**Comment by duncanawoods** [comment]
I am also seeing this on `Ubuntu 22.04.04`, `vscode 1.88.0`, `tmux 3.2a`

**Comment by studgeek** [comment]
I'm seeing this also on vscode 1.89.1 tmux 3.3a on linux. I can't seem to select text with mouse using any combination of modifier keys.

**Comment by studgeek** [comment]
Interestingly, in my case I can select if I am using tmux inside vscode integrated terminal inside a bottom pane of original window.
But once I move it to a detached window using "Move Terminal into New Window" I can no longer select text.
If I drag that terminal back into bottom pane of original window then I can select again.

**Comment by studgeek** [comment]
Note related issue was reported and fixed in earlier vscode in #192518.

**Comment by studgeek** [comment]
In my case I found that `"terminal.integrated.macOptionClickForcesSelection": true` allows me to select in detached window also. It still seems weird that behavior is different between in-pane and detached though...

**Comment by studgeek** [comment]
Actually, I do still see a behavior difference between once a terminal is detached.
When in pane I can mouse select text with no modifier key. Once detached I can't select with no modifier key. I have to have  `"terminal.integrated.macOptionClickForcesSelection": true` and also press Option to select.
If I move terminal back in pane then I can select text with no modifier key again.

**Comment by Yujif1Aero** [comment]
neither me.  My vscode in wsl2 is 
```bash
 $ code -v
1.89.1
dc96b837cf6bb4af9cd736aa3af08cf8279f7685
x64
```
tmux is 
```bash
$ tmux -V
tmux 3.2a
```
wsl2 is 
```power shell
wsl -v
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3593
```


[My tmux setting is set for emacs user. ](https://github.com/Yujif1Aero/tmuxSetting/tree/wsl2)
As to copy the shell commands, I use ```emacs ~/.bash_history``` in tmux.
