### ISSUE TITLE
quick chat doesn't close when `insert at cursor` is invoked

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#209134]
Discovered while meeting with @jooyoungseo, who primarily uses the quick chat

1. open quick chat
2. run a command that produces a code block
3. in the code block, use `ctrl+enter`
4. ✅ it's inserted in the editor
5. 🐛 the quick chat is not hidden

**Comment by TylerLeonhardt** [comment]
I don't think we should close it:
* The command says "Insert at cursor" not "Insert at cursor and close Quick Chat"
* Panel chat doesn't go away when you do it there
* maybe you want to interact with Quick Chat still
* You just have to hit ESC to hide the Quick Chat
