### ISSUE TITLE
how open file with spaces in cli?

### ISSUE THREAD

**Issue by Zverushko** [Microsoft/vscode#20919]
Filezilla renemed file if file exist to FILENAME 2.php
and vscode try to open 2 files...

how i can fix this?
thx!

**Comment by kumarharsh** [comment]
escape the space ( or press TAB after typing `FIL` for autocomplete )
```
> code.cmd FILENAME\ 2.php
```

**Comment by smuuf** [comment]
I would be surprised if placing quotes around it wouldn't work.

```
code "FILENAME 2.php"
```

**Comment by buzzzzer** [comment]
code "FILENAME 1.php" "FILENAME 2.php" 
work for me

**Comment by kumarharsh** [comment]
Actually, placing quotes is the right way to do it. I'd been in the linux shell for a long time and completely mixed up my response 😜 (*.cmd + linux-style escapes)
