### ISSUE TITLE
c language char variable

### ISSUE THREAD

**Issue by Prakashtiwari080403** [microsoft/vscode#209185]
![Screenshot 2024-03-30 175511](https://github.com/microsoft/vscode/assets/164559801/b3a0cfd1-acef-48eb-858b-8efc83bec499)
![Screenshot 2024-03-30 175511](https://github.com/microsoft/vscode/assets/164559801/94a7e0b0-a7fb-40bb-afdd-7b9c8bd45c48)
Type: <b>Bug</b>

I got output of every code and variables. but i am not getting output in char variable . please check it

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasteri
![Screenshot 2024-03-30 175511](https://github.com/microsoft/vscode/assets/164559801/5e9c4be3-a76d-462e-93da-39ee60ea5d46)
zation: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.74GB (0.57GB free)|
|Process Argv|--crash-reporter-id 844fe339-83ba-42d8-8748-9bb4490bc207|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</su
![Screenshot 2024-03-30 175511](https://github.com/microsoft/vscode/assets/164559801/90ad505f-293e-4769-93a3-106e8af538be)
mmary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.1
c-cpp-runner|fra|9.4.7
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
LiveServer|rit|5.7.9
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30993540
dsvsc020:30976470
pythonait:30996668
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by Prakashtiwari080403** [comment]
i didnot get any output in char variable type in c language

**Comment by lszomoru** [comment]
Please file an issue here - https://github.com/Microsoft/vscode-cpptools/issues. Thanks!
