### ISSUE TITLE
[css] suggest class names that exist in other css files

### ISSUE THREAD

**Issue by sethstha** [microsoft/vscode#20913]
VSCode is awesome mainly it's intelisense.
I would like to have option to get intelisense suggestion from another opened file.

Currently when working on any CSS or SCSS file. VSCode only suggests for the class name, if it is present in same file. 

Look at here, it is only suggesting class name that are already present there.
![image](https://cloud.githubusercontent.com/assets/2367137/23119187/462bdc66-f77f-11e6-93af-db11946cda4d.png)

It would be really helpful, if we could get suggestion from another opened file. When opened another HTML or CSS file, there should be suggestion coming from them.

This is visually edited. Here it is suggesting for class name that are present on another file.
![suggestion](https://cloud.githubusercontent.com/assets/2367137/23119677/45236968-f781-11e6-841b-bba312db6c43.png)

Thank you
Kudos to VSCode Team

**Comment by aeschli** [comment]
covered by https://github.com/microsoft/vscode/issues/47331
