### ISSUE TITLE
Extensions tab hangs forever

### ISSUE THREAD

**Issue by SecSan** [Microsoft/vscode#20916]
The extension tab hangs forever without showing any extensions (neither installed nor available in the marketplace). So I cannot install any extensions.

- VSCode Version: 1.9.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open Extensions tab
2. It hangs for ever

The same happens when I try to install an extension with CTRL+P > `ext install csharp`

I already tried to completely uninstall VS Code, delete the extensions directory, reboot, and then install it again, but that didn't help.
And since this seems to be a cause of similar issues: I am not behind a proxy.

**Comment by joaomoreno** [comment]
You might not know that you are behind a proxy. Are you in some corporate network?

**Comment by SecSan** [comment]
Yes, I am in a corporate network, but my colleagues don't have such problems with VS Code and they are in the same network.
But I tried the app mentioned in #18103 anyway and it showed no errors. Can I provide any more information?

**Comment by joaomoreno** [comment]
What was the output of that app?

**Comment by SecSan** [comment]
I haven't set a proxy URL or a CA file:

| Test | Status | Hash or Error |
|---|---|---|
| HTTP XHR | 200 | 176510cd5998854b63794674d2203a246adee111 |
| HTTPS XHR | 200 | 176510cd5998854b63794674d2203a246adee111 |
| HTTP Node | 200 | 176510cd5998854b63794674d2203a246adee111 |
| HTTPS Node | 200 | 176510cd5998854b63794674d2203a246adee111 |
| HTTP Node (not strict) | 200 | 176510cd5998854b63794674d2203a246adee111 |
| HTTPS Node (not strict) | 200 | 176510cd5998854b63794674d2203a246adee111 |
| HTTP Node Agent | 200 | 176510cd5998854b63794674d2203a246adee111 |
| HTTPS Node Agent | 200 | 176510cd5998854b63794674d2203a246adee111 |
| HTTP Node Agent (not strict) | 200 | 176510cd5998854b63794674d2203a246adee111 |
| HTTPS Node Agent (not strict) | 200 | 176510cd5998854b63794674d2203a246adee111 |
| HTTP Electron | 200 | 176510cd5998854b63794674d2203a246adee111 |
| HTTPS Electron | 200 | 176510cd5998854b63794674d2203a246adee111 |

**Comment by joaomoreno** [comment]
If you open the Developer Tools, do you see any error? <kbd>F1</kbd> `Developer Tools`

**Comment by SecSan** [comment]
No, that looks good to me. I can inspect the html code, the css style and so on with it.

**Comment by joaomoreno** [comment]
I meant the Console tab.

**Comment by SecSan** [comment]
There I can select `top` or `workerMain.js#editorWorkerService`, but I don't see any messages. The space beneath is completely blank.

**Comment by joaomoreno** [comment]
Can you share a screenshot?

**Comment by SecSan** [comment]
Sure:

![vs code issue20916 developertools](https://cloud.githubusercontent.com/assets/12697319/23202101/bb7d55fe-f8dc-11e6-87bd-9557b52c6459.png)

**Comment by joaomoreno** [comment]
If you remove the `@recommended` and replace it with something else, you get the same behaviour? Do you actually have any `http.proxy` setting? How about a `HTTP_PROXY` env variable?

**Comment by SecSan** [comment]
Yes, the same behavior, no matter what I choose in the extensions tab: `@outdated`, `@disabled`, or nothing (so my installed extensions). It just keeps that way so that it looks as if it would still be loading something. Shouldn't at least the display of installed extensions work independently of any network issues?

I don't have a `HTTP_PROXY` env variable set and I don't know of any other http proxy setting on my system. I definitely didn't set one.

When you think that this problem is network related: Is there anything else I can check to verify this? Would it help for example when I record the network traffic when I open the extensions tab?

**Comment by joaomoreno** [comment]
@SecSan Yes it should...

Can you try out the ZIP release? https://az764295.vo.msecnd.net/stable/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/VSCode-win32-1.9.1.zip

**Comment by SecSan** [comment]
That didn't change anything, the extensions tab still hangs.

**Comment by SecSan** [comment]
Can you tell me where VS Code stores its settings and configuration? Maybe I just need to delete some config files or registry keys, so I can do a completely fresh install.
(I could make a copy of the files before, in case it actually helps. So you can check them to find what causes the problem)

**Comment by joaomoreno** [comment]
Yeah let's try that. It should be somewhere in `%APPDATA%`.

**Comment by SecSan** [comment]
Ok, I deleted the `Code` directory in `%APPDATA%` as it seemed to belong to VS Code, uninstalled the application, and made sure that nothing was left of it in `C:\Program Files (x86)\`. Then I tried first your ZIP release and afterwards the normal setup, but the problem is still there in both versions.

**Comment by joaomoreno** [comment]
Is there any chance you can [clone our code and try it out from source](https://github.com/Microsoft/vscode/wiki/How-to-Contribute)?

**Comment by SecSan** [comment]
I tried to install as described in the article you linked to, but I got the following error:

```
C:\Workspace\GitHub\vscode>scripts\npm install
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

> code-oss-dev@1.10.0 preinstall C:\Workspace\GitHub\vscode
> node build/npm/preinstall.js

/d : Die Benennung "/d" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren
Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und
wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ /d /s /c node build/npm/preinstall.js
+ ~~
    + CategoryInfo          : ObjectNotFound: (/d:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

code-oss-dev@1.10.0 C:\Workspace\GitHub\vscode
`-- d@0.1.1  extraneous

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! code-oss-dev@1.10.0 preinstall: `node build/npm/preinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the code-oss-dev@1.10.0 preinstall script 'node build/npm/preinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the code-oss-dev package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/npm/preinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs code-oss-dev
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls code-oss-dev
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Workspace\GitHub\vscode\npm-debug.log
```

Settings and versions mentioned in the article:

```
C:\Workspace\GitHub\vscode>node -v
v6.10.0

C:\Workspace\GitHub\vscode>npm -v
3.10.10

C:\Workspace\GitHub\vscode>echo %PYTHON%
C:\Python27\python.exe

C:\Workspace\GitHub\vscode>python --version
Python 2.7.10
```

[npm-debug.zip](https://github.com/Microsoft/vscode/files/793743/npm-debug.zip)

**Comment by joaomoreno** [comment]
The article says to use `scripts\npm install`. Not `npm install`.

**Comment by SecSan** [comment]
That's exactly what I did: I was in the `vscode` folder and executed `scripts\npm install`.

**Comment by joaomoreno** [comment]
Oh I misread that, sorry.

What does

```
/d : Die Benennung "/d" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren
Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und
wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
```

mean?

**Comment by joaomoreno** [comment]
Are you in a PowerShell maybe? Can you try a Command Prompt?

**Comment by SecSan** [comment]
The error was actually related to PowerShell, although I executed it from a Command Prompt, but it seems that it used the `COMPSEC` env variable at some point which was set to PowerShell on my system. After changing it to the normal `cmd.exe` I could complete the installation.

And now I can finally use extensions! I installed two extensions (`csharp` and `prettify-json`) and they work as expected.

**Comment by SecSan** [comment]
Just wanted to say that the problem is now also gone with the newest release 1.10.2. I can now finally use extensions again :)
So I am closing this issue.

**Comment by marratj** [comment]
Hi there, wanting to chime in. I have the same problem for a few days now, all the outlined steps above didn't help.

I followed the issue above and really have EXACTLY the same behavior.

I'm still having the same problem with 1.10.2, and also with the insider builds.

**Comment by marratj** [comment]
Nevermind, I somehow skipped over the part with the ComSpec variable.

I too had mine set to PowerShell. Changed back to cmd.exe and extensions are working just fine again.

Really seems that VS Code doesn't want any other ComSpec than cmd.exe under Windows 10.
