### ISSUE TITLE
vscode 1.87.2（package version 863d2581） snap randomly unresponsive on ubuntu23.10

### ISSUE THREAD

**Issue by gdr2333** [microsoft/vscode#209192]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2
- OS Version: Ubuntu 23.10 amd64 (kernel : 6.5.0-26-generic)

Steps to Reproduce:

1. start vscode
2. do anything or just wait
and you will see this:
![图片](https://github.com/microsoft/vscode/assets/90298704/f6076499-be95-4b46-ada2-9b32d8c8bb79)
(Visual Studio Code is not responding.
You can try waiting for it to respond or force quit this app.)

installed extensions:
ms-dotnettools.vscode-dotnet-runtime
ms-dotnettools.csharp
ms-dotnettools.csdevkit
ms-ceintl.vscode-language-pack-zh-hans

**Comment by rzhao271** [comment]
Hi @gdr2333, is the issue still occurring for you on VS Code 1.96 or later?

**Comment by gdr2333** [comment]
> Hi [@gdr2333](https://github.com/gdr2333), is the issue still occurring for you on VS Code 1.96 or later?

I'm running a 1.96.0 snap in a virtual machine and it looks like it's okay already. I'm going to close this issue, thanks!

**Comment by gdr2333** [comment]
> Hi [@gdr2333](https://github.com/gdr2333), is the issue still occurring for you on VS Code 1.96 or later?

I'm running a 1.96.0 snap in a virtual machine and it looks like it's okay already. I'm going to close this issue, thanks!
