### ISSUE TITLE
The text inside the inline code is cut off.

### ISSUE THREAD

**Issue by babakfp** [microsoft/vscode#209199]
`#terminal.integrated.`

![image](https://github.com/microsoft/vscode/assets/44144724/1e064c34-12d5-47e5-811a-0d7000a67a44)

**Comment by meganrogge** [comment]
Works for me in insider's

![Screenshot 2024-04-01 at 8 54 06 AM](https://github.com/microsoft/vscode/assets/29464607/c8068e32-edae-4968-8b00-375787b3613a)

**Comment by babakfp** [comment]
I checked it again and the issue didn't exist anymore (I didn't make any changes) 🤷‍♂️😀.
