### ISSUE TITLE
The color decorator configuration is not available

### ISSUE THREAD

**Issue by Ali-ovo** [microsoft/vscode#209101]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  版本: 1.87.2
- OS Version:  macOS Sonoma 14.3.1

![image](https://github.com/microsoft/vscode/assets/67216143/80efd9a4-dd43-4c01-a537-a102fbe95365)

Steps to Reproduce:

  i use React in vscode, i write `color css in style` , it's worked.
  
![image](https://github.com/microsoft/vscode/assets/67216143/1c912fbc-99cd-410a-b407-5cb32f749cd1)

but i write css in ts file,  its not working.
![image](https://github.com/microsoft/vscode/assets/67216143/e7496009-358c-4b7a-bb9e-08e6ec3c376e)

**Comment by ArturoDent** [comment]
Try enabling this setting:

```
Editor: Default Color Decorators
```

Does that help?

**Comment by Ali-ovo** [comment]
> Try enabling this setting:
> 
> ```
> Editor: Default Color Decorators
> ```
> 
> Does that help?

its worked, thanks
