### ISSUE TITLE
terminated with exit code: 2.

### ISSUE THREAD

**Issue by Ayushkumar302** [microsoft/vscode#209100]
![Screenshot (233)](https://github.com/microsoft/vscode/assets/139211075/295ffe5f-027a-44dc-a960-1fc4d9c28bc9)
Type: <b>Performance Issue</b>

I'm encountering a problem while trying to run PowerShell in Visual Studio Code (VSCode). Whenever I attempt to open a terminal or execute PowerShell commands within VSCode, I receive the following error message:

"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 2

1)I have tried restarting VSCode, restarting my computer, and reinstalling VSCode, but the issue persists.
2)This issue started occurring recently, and I haven't made any significant changes to my system configuration.
3) i have also try to set terminal.integrated.defaultProfile.windows from default to  windows powershell in vscode settings but it doesn't work  

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
rc-beautify|Ato|1.2.0
blackbox|Bla|1.2.82
vscode-toggle-quotes|Bri|0.3.6
simple-react-snippets|bur|1.2.7
marko-beautify|bus|2.0.0
turbo-console-log|Cha|2.10.4
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|2.0.9
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
randomeverything|hel|0.0.3
myBeautify|Isa|0.3.7
vscode-gutter-preview|kis|0.30.0
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
java|red|1.28.1
LiveServer|rit|5.7.9
html-to-css-autocompletion|sol|1.1.2
open-in-browser|tec|2.0.0
vscode-lldb|vad|1.10.0
incredibly-in-your-face|Vir|1.0.2
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
![Screenshot (233)](https://github.com/microsoft/vscode/assets/139211075/0a88eb76-8f01-40c0-aaea-e9d22e73af10)

vscode-maven|vsc|0.44.0
console-ninja|Wal|1.0.297
JavaScriptSnippets|xab|1.8.0
chat-gpt|zha|1.6.63

</details>

**Comment by meganrogge** [comment]
is there a reason you're using windows powershell? I'd suggest updating and using a different powershell.

**Comment by meganrogge** [comment]
you can try changing your `terminal.integrated.profiles.windows` to fix this, providing the path to a newer version of pwsh

**Comment by Ayushkumar302** [comment]
I've updated the terminal.integrated.profiles.windows to point to a newer pwsh version, but the issue is not resolved.
