### ISSUE TITLE
Can't open Remote Explorer folder

### ISSUE THREAD

**Issue by austinmw** [microsoft/vscode#209297]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.88.0-insider (Universal)
- OS Version: MacOS, latest

Steps to Reproduce:

1. Connect to server with Remote Explorer
2. Click "Open Folder", navigate to folder, attempt to click "OK"

Result: "OK" button does nothing when clicked — does not open the remote folder

**Comment by alexr00** [comment]
duplicate of https://github.com/microsoft/vscode/issues/208937
