### ISSUE TITLE
Debug configurations with the same name

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#20927]
If you have two debug configurations with the same name but different signature, and try to run any of them, it would run only the last one as this is the one the code resolves to. It is because it resolves configuration by name, not by a unique ID.

- VSCode Version: 1.10.0
- OS Version: Win 10

Steps to Reproduce:

1. Create two different debug configurations in launch.config with the same name.
2. Go to debug view, select first configuration and run. 
It will run second one defined in the launch.json, instead of the first one.

Expected: follow the same ordering as in launch.json.

ping @isidorn

**Comment by isidorn** [comment]
[`onDidSelect`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/selectBox/selectBox.ts#L34) will also have to emit the index of the selected file, not only the name in order for this to be supported

**Comment by isidorn** [comment]
With the new chrome update now the dropdown natievly always auto selects the first occurrence of a duplicate name (checked os x and win(. So even in a native selector it is never possible to select the second duplicate.
To align with that now we also always pick the first occurence of a duplicate - not the last one. This in combination with the new select box behavior will lead to an overall better user experience
