### ISSUE TITLE
Diff editor left side context menu is covered by right editor

### ISSUE THREAD

**Issue by yume-chan** [microsoft/vscode#209251]
Type: <b>Bug</b>

1. Open a diff editor from SCM view, make sure the window is wide enough for the diff editor to show in side-by-side mode.
2. Right click on the middle left area, where the mouse cursor is in the old (left) editor, but close to the new (right) editor
3. Observe the context menu is covered by the right editor

![image](https://github.com/microsoft/vscode/assets/1330321/125186f8-162c-4ce0-9e1c-58bb10869d99)

It might be caused by https://github.com/microsoft/vscode/commit/b7d35c8bdddeb7d4bfebf81cb6733b4a5ee06aa9#diff-23f85455eabf66e8a43f8b79c7fa7b0607ad62823c4f502d0e949ebf8aff7478R61, by removing `z-index: 1` on `dev.editor.modified`, the context menu displays correctly.

(I have tested with extensions disabled)

VS Code version: Code - Insiders 1.88.0-insider (d994aede3529f4d1af9eeaeb234d32fd936243e7, 2024-03-29T22:23:34.041Z)
OS version: Windows_NT x64 10.0.26040
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (12.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.4.2
vscode-zipfs|arc|3.0.0
markdown-mermaid|bie|1.22.0
vscode-eslint|dba|2.4.4
dprint|dpr|0.16.0
gitlens|eam|14.9.0
prettier-vscode|esb|10.4.0
copilot|Git|1.176.796
copilot-chat|Git|0.14.2024032901
vscode-pull-request-github|Git|0.85.2024032704
rest-client|hum|0.25.1
vscode-env|Iro|0.1.0
search-node-modules|jas|1.3.0
fluent-icons|mig|0.0.18
remote-containers|ms-|0.353.0
remote-wsl|ms-|0.88.0
hexeditor|ms-|1.9.14
js-debug-nightly|ms-|2024.3.2217
typescript-explorer|mxs|0.4.2
abracadabra|nic|9.1.2
material-icon-theme|PKi|4.34.0
vscode-yaml|red|1.14.0
vscode-sort-json|ric|1.20.0
reveal|smu|1.2.7
code-spell-checker|str|3.0.1
luna-paint|Tyr|0.16.0
pretty-ts-errors|Yoa|0.5.3
markdown-all-in-one|yzh|3.6.2
material-theme|zhu|3.17.0

</details>

**Comment by deepak1556** [comment]
Closing for verification.
