### ISSUE TITLE
Support for intelliSense in requirejs projects

### ISSUE THREAD

**Issue by iFarmGolems** [Microsoft/vscode#20924]
Basically title.

Is it possible to add it? Or is there any plugin that can do such thing?

Thanks.

**Comment by mjbvz** [comment]
Can you please provide a small example project and describe the problem you are running into currently?

Thanks

**Comment by iFarmGolems** [comment]
Of course, I set up a little project here: https://github.com/iFarmGolems/requirejs-intellisense-vscode

The thing is, when I am in testmodule and I invoke constructor function from my dependency, vscode will not predict properties on that object.

I may be missing something, but I think that intellisense can not work without pointing it to my config file with respective paths.

**Comment by mjbvz** [comment]
Thanks for the example project. I confirmed that it does not work as expected and was unable to create a configuration that allows for better intellisense in this project type.

We use the TypeScript server for JavaScript language features and support for AMD modules is being tracked upstream: https://github.com/Microsoft/TypeScript/issues/6942 

Closing as upstream

**Comment by MankalMR** [comment]
I would definitely love to have to this feature. I think there are several legacy codebases out there which would benefit from this feature.
One way to resolve the dependencies can be to have the vscode lookup a requires config file (this can be configurable per project).
