### ISSUE TITLE
启动速度太慢了

### ISSUE THREAD

**Issue by 863760763** [Microsoft/vscode#20925]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.启动速度太慢了
2.

**Comment by chiyx** [comment]
是否是 ssd，我用着一直挺快，基本3秒内

**Comment by billyhoomm** [comment]
your PC's Configuration is lower...

**Comment by Emeryao** [comment]
启动慢 真的是你的硬件或者系统问题 
要么是你的硬件不给力 要么是你的系统资源被各种安全卫士占用太多了
VS Code本身的启动速度挺快的 没毛病

**Comment by zhengrenzhe** [comment]
如果是与 sublime 比那确实是挺慢的。

**Comment by bpasero** [comment]
Next time in english please.

**Comment by gefangshuai** [comment]
@Emeryao 笑尿，
