### ISSUE TITLE
cant run any type of code

### ISSUE THREAD

**Issue by zinfamous** [microsoft/vscode#209225]
Type: <b>Performance Issue</b>

each time i write my code and start to click on the 'run' button an alert with the message "Code language not supported or defined" even though i do have multible extensions activated such as 'code runner', i've used vs before for runing my html code and never ran through this issue except recently

VS Code version: Code 1.87.2 (Universal) (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|22, 23, 19|
|Memory (System)|8.00GB (0.19GB free)|
|Process Argv|--crash-reporter-id 2e3513a4-dd57-4994-8d2b-0b89ebd3b939|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	   131	 10716	code main
    3	    57	 10720	   gpu-process
    0	    25	 10721	   utility-network-service
    0	   254	 10722	window [1] (nadin.html — Nadin Hatem)
    1	    82	 10732	shared-process
    0	     0	 11847	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    33	 10773	ptyHost
    0	     0	 11304	     /bin/zsh -il
    1	    74	 11291	extensionHost [1]
    0	    33	 11294	     electron-nodejs (server.js )
    0	    33	 11295	     /private/var/folders/cy/87_qsjjs28l__f2vzjyn7sfm0000gp/T/AppTranslocation/17AE6E38-B314-4AD4-B744-2AB5F78C46E8/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /private/var/folders/cy/87_qsjjs28l__f2vzjyn7sfm0000gp/T/AppTranslocation/17AE6E38-B314-4AD4-B744-2AB5F78C46E8/d/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=11291
    0	    33	 11343	     /private/var/folders/cy/87_qsjjs28l__f2vzjyn7sfm0000gp/T/AppTranslocation/17AE6E38-B314-4AD4-B744-2AB5F78C46E8/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /private/var/folders/cy/87_qsjjs28l__f2vzjyn7sfm0000gp/T/AppTranslocation/17AE6E38-B314-4AD4-B744-2AB5F78C46E8/d/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=11291
    4	    16	 11846	     (docker)
    0	    33	 11292	fileWatcher [1]
    3	    74	 11836	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (nadin.html — Nadin Hatem)
|    Folder (Nadin Hatem): 3 files
|      File types: json(1) html(1)
|      Conf files: launch.json(1)
|      Launch Configs: chrome;
```

</details>
<details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|7.2.1
html-extentions-pack|bou|0.3.0
vscode-tailwindcss|bra|0.10.5
js-codeformer|cms|2.6.1
jsrefactor|cms|3.0.1
vscode-html-css|ecm|2.0.9
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
code-runner|for|0.12.1
live-sass|gle|6.1.2
minify|Hoo|0.4.3
vscode-htmlhint|HTM|1.0.5
vscode-html-format|moh|0.1.6
vscode-attrs-sorter|mrm|2.1.0
vscode-doiuse|mrm|1.6.0
vscode-scss|mrm|0.10.0
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.348.0
vscode-css-peek|pra|4.4.1
LiveServer|rit|5.7.9
html5-boilerplate|sid|1.1.1
js-jsx-snippets|sky|11.0.1
html-to-css-autocompletion|sol|1.1.2
open-in-browser|tec|2.0.0
in-your-face-incredible|TTO|1.1.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-icons|vsc|12.7.0
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:30996668
jchc7451:30973076
7ghi1836:30988842
dsvsc021:30996838
g1icg217:30999571

```

</details>

**Comment by roblourens** [comment]
https://code.visualstudio.com/docs/nodejs/browser-debugging
