### ISSUE TITLE
empty vscode window created each time when open a terminal

### ISSUE THREAD

**Issue by caojeremy** [microsoft/vscode#209237]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.87.2
- OS Version: MacOS 14.4.1 

Steps to Reproduce:

1.  Use zsh shell with initial script **export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"** in ~/.zshrc
2. Then each time open a new terminal or source it will launch a new empty vscode window automatically.
![2024-04-01_11-50-40](https://github.com/microsoft/vscode/assets/27198952/6394d2c9-8b96-4ce2-9f22-e4904845d965)

**Comment by meganrogge** [comment]
why are you adding this /what's your intent with this line?

`export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin" in ~/.zshrc`

**Comment by meganrogge** [comment]
just tried and cannot reproduce. If this is an issue for you, I suggest removing that line.

**Comment by caojeremy** [comment]
@meganrogge I added this line as the document said **https://code.visualstudio.com/docs/setup/mac**, to launch vscode from the from the command line](https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line), remove this line that I can't launch vscode via the command 'code' in terminal.

Also, I tried ** Open the Command Palette (Cmd+Shift+P) and type 'shell command' to find the Shell Command: Install 'code' command in PATH command.
** as document said without adding this line, issue is reproduceable.

**Comment by caojeremy** [comment]
@meganrogge issue found, I overridde the built-in 'diff' command in my script, and somewhere called the 'diff' command after the newly upgrade of MacOS... Sorry for this, and thanks for your time! Have a nice day!
