### ISSUE TITLE
Tree widget does not fire `onDidChangeFocus` when items are cleared out

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#209215]
Simplified repro:

```ts
// Set up a listener
tree.onDidChangeFocus(e => console.log('hit'));

// Set some number of elements, doesn't matter
tree.setChildren(null, elements);
// Set an element to be focused
tree.setFocus([anElement]);
```
We see a hit in console... makes sense, focus changed from nothing to something.

```ts
console.log(tree.getFocus().length);
// see '1' in console
```
```ts
// Now let's set the tree to empty
tree.setChildren(null, []);
```
At this point, we don’t see a hit in the console (🐛?)… but:
```ts
console.log(tree.getFocus().length);
// see '0' in console
```

I would have expected that when the children are set to empty causing focus to change, that an event would be emitted.

Quick Pick usages:

* tree.onDidChangeFocus:
https://github.com/microsoft/vscode/blob/b5b009c1943718b158cf9e324d5d60d4218010af/src/vs/platform/quickinput/browser/quickInputTree.ts#L767
* tree.setChildren (elements will be empty list when you type a filter that doesn't match any item):
https://github.com/microsoft/vscode/blob/b5b009c1943718b158cf9e324d5d60d4218010af/src/vs/platform/quickinput/browser/quickInputTree.ts#L1510
* tree.setFocus (all in here):
https://github.com/microsoft/vscode/blob/b5b009c1943718b158cf9e324d5d60d4218010af/src/vs/platform/quickinput/browser/quickInputTree.ts#L1216-L1375

Because of this behavior, I had to implement the following which feels a little weird:
https://github.com/microsoft/vscode/pull/209157

**Comment by joaomoreno** [comment]
@TylerLeonhardt On https://github.com/microsoft/vscode/pull/218782 I scaffolded a test to verify your findings but I could not reproduce what you describe. Can you see if you can catch the bug in the test?

**Comment by TylerLeonhardt** [comment]
Ah. I think this was happening due to the Identity Provider I was using. I actually no longer have this `_onTriggerEmptySelectionOrFocus` workaround.
