### ISSUE TITLE
VSCode themes CSS variables override Webview's CSS

### ISSUE THREAD

**Issue by Leo-Adlakha** [microsoft/vscode#209253]
Hi, 

I am working on an extension which generates documentation in HTML format for code written in the VSCode editor window and then rendering it in a webview alongside the editor. But, I have observed that CSS variables get added to the Webview's HTML tag which in turn interfere with the generated HTML code, and this leads to un-readable text in the webview. How may I avoid this behavior ?

This is happening for the `Dark Modern` theme only.

![image](https://github.com/microsoft/vscode/assets/52428237/57e8641a-02b3-4619-9b4e-5a80c265f588)

Version: 1.87.2 (system setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 **10.0.19045**

**Comment by mjbvz** [comment]
This is how webviews let you use VS Code theme colors. There is no way to disable it. Try modifying your code if it's somehow causing problems
