### ISSUE TITLE
Debugger clog icon does not exist

### ISSUE THREAD

**Issue by tesmond** [Microsoft/vscode#20921]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.10.0|

---

Steps to Reproduce:
I am attempting to setup PHP debugging but the cog icon is missing.

The following websites
https://code.visualstudio.com/Docs/editor/debugging
and
https://blogs.msdn.microsoft.com/nicktrog/2016/02/11/configuring-visual-studio-code-for-php-development/

have a clog icon which creates a launch.json file for configuring the debugging extension. This icon does not exist on the debugging screen.

I have attached a screenshot demonstrating that the extension is installed and the cog icon is missing from the debugging screen. Please advise what I need to to rectify this.

![capture](https://cloud.githubusercontent.com/assets/2111102/23124715/5047d024-f766-11e6-87fa-e30f47ca577e.PNG)

**Comment by isidorn** [comment]
You need to open a folder in order to have full debug suport.
Namely file > open folder >

Currently you are in a no folder workspace which means you only have a single file debug support - which is not what you are looking for

**Comment by weinand** [comment]
@isidorn the documentation at https://code.visualstudio.com/Docs/editor/debugging doesn't mention 'debugging without a workspace folder'. I've created https://github.com/Microsoft/vscode-docs/issues/855 to track this.

**Comment by isidorn** [comment]
@weinand agree, thanks.
