### ISSUE TITLE
aaa

### ISSUE THREAD

**Issue by lijing928** [Microsoft/vscode#20926]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|generate-react-component|joshjg|0.2.1|
|react-redux-es6-snippets|timothymclane|2.0.2|
|jsx|TwentyChung|0.0.1|

---

Steps to Reproduce:

1.
2.

**Comment by mrmlnc** [comment]
bbb. Please, provide more detailed information and steps to reproduce your problem.

**Comment by charlesmilette** [comment]
ccc

**Comment by jrieken** [comment]
we will reopen when there are steps to repro
