### ISSUE TITLE
Drop file into markdown doesn't create link

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#209239]
Type: <b>Bug</b>

1. Drop an image file from the VS Code explorer into a md file

**Bug**
No markdown image inserted, just the file name

VS Code version: Code - Insiders 1.88.0-insider (Universal) (d994aede3529f4d1af9eeaeb234d32fd936243e7, 2024-03-29T22:24:49.191Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (0.53GB free)|
|Process Argv|--crash-reporter-id 0fffb5da-9cd7-46fd-9e7f-a1564e8c5fda|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by deepak1556** [comment]
Closing for verification.
