### ISSUE TITLE
Unusual graphic glitch, missing lines, broken scroll

### ISSUE THREAD

**Issue by pailhead** [microsoft/vscode#209238]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.87.2
- OS Version:  Windows 10 Home

Steps to Reproduce:
![image](https://github.com/microsoft/vscode/assets/4681282/86a0498d-c526-4869-9b01-801faa228850)

**Comment by RedCMD** [comment]
I assume you're talking about the editor sticky scroll
you can right click it

**Comment by pailhead** [comment]
Yes. Thank you! Where do i right click? As is im trying to toggle the different areas but i can't really see if its toggled on or off.

**Comment by RedCMD** [comment]
https://code.visualstudio.com/docs/getstarted/userinterface#_sticky-scroll
