### ISSUE TITLE
Separate "Just My Code" options for stepping and Raised Exceptions (Python)

### ISSUE THREAD

**Issue by thelazydogsback** [microsoft/vscode#209360]
The option to catch Raised Exceptions is very useful for finding issues in your own codebase.
However, if `JustMyCode` is set to `false` for the project because you wish to step into library code, this feature becomes useless because it seems to be common practice to use exception-handling all over the standard Python codebase and imported libs (for example, doing `try: v = dict[key] except:` vs `if dict contains key` or `dict.get(key)`) -- this barrage of exceptions makes it impossible to catch the exceptions that your own codebase may be raising.

The requested feature is to add a new "Raised Exceptions (JustMyCode)" option here:
![image](https://github.com/microsoft/vscode/assets/4603468/8b2a2a86-7190-4df8-b0f2-0cf6df0015bc)

The current one would be changed to "Raised Exceptions (External Code)" if the behavior is split in two, or would be renamed to "Raised Exceptions (All)" if it keeps its current behavior - if this is checked, then the "JustMyCode" checkbox could be disabled, as it subsumes it.
The other option is to have separate `launch.json` setting for this behavior. (However, I already toggle this enough that I wish it were presented as a checkbox while the debugger was running as well.)

**Comment by roblourens** [comment]
Please file this on the repo for the Python debug extension
