### ISSUE TITLE
theme color schema doesn't auto change

### ISSUE THREAD

**Issue by Diluka** [microsoft/vscode#209313]
Type: <b>Bug</b>

Color Theme: Dark (default)
Preferred Dark Color Theme: Dark (default)
Preferred Light Color Theme: Light (default)
Auto Detect Color Schema: checked

System: Light

VS Code version: Code 1.87.2 (Universal) (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin x64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id e460c12f-c513-4cbc-9755-ba1443bdc1a8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-nginx-conf|ahm|0.3.5
vscode-sqlite|ale|0.14.1
vscode-eclipse-keybindings|alp|0.16.1
path-intellisense|chr|2.8.5
gitignore|cod|0.9.0
vscode-markdownlint|Dav|0.54.0
vscode-eslint|dba|2.4.4
gitlens|eam|14.9.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
vscode-jest-runner|fir|0.4.73
auto-rename-tag|for|0.1.10
copilot|Git|1.177.0
copilot-chat|Git|0.13.1
remotehub|Git|0.62.0
vscode-graphql|Gra|0.9.3
vscode-graphql-syntax|Gra|1.3.5
todo-tree|Gru|0.0.226
vscode-nginx-conf-hint|han|0.3.1
vscode-nestjs-generator|img|2.3.1
vscode-nestjs-pack|img|1.10.0
vscode-nestjs-snippets-extension|img|1.4.0
vscode-nestjs-swagger-snippets|img|1.1.0
drawfolderstructure|jmk|1.2.2
caddyfile-support|mat|0.4.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.29.0
vscode-language-pack-zh-hans|MS-|1.87.2024031309
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.2
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.1
indent-rainbow|ode|8.3.1
vscode-jest|Ort|6.2.3
tsimporter|pmn|2.0.1
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
vscode-nginx|sha|0.6.0
trailing-spaces|sha|0.4.1
autoimport|ste|1.5.4
move-ts|str|1.12.0
even-better-toml|tam|0.19.2
errorlens|use|3.16.0
highlight-matching-tag|vin|0.11.0
vscode-icons|vsc|12.7.0
pretty-ts-errors|Yoa|0.5.3
save-as-root|yy0|1.8.0
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d6fi2104:30959263
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
7ghi1836:30988842
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by aeschli** [comment]
The theme only changes when the OS scheme is changing.
The next time the OS color scheme is changing you will see the VS Code scheme changing.
