### ISSUE TITLE
IntelliSense conflicts with Emmet in PHP files

### ISSUE THREAD

**Issue by danielpost** [Microsoft/vscode#20939]
When writing Emmet code in a PHP file (for example .row>.medium-4.columns), pressing Tab will change the last part to the IntelliSense suggestion instead of executing the Emmet snippet.

The easiest way to fix this would be the ability to disable IntelliSense on Tab, but I could only find the option to disable using IntelliSense with the Enter button.

**Comment by jrieken** [comment]
I would recommend the `"editor.quickSuggestions": false` setting. That makes IntelliSense only appear when explicitly requested (cmd+space) and not while you type (minus auto trigger character as in `console.<trigggered>`).

Alternatively you also change your keybinding in the `keybindings.json` file. E.g remove the tab binding for accepting suggestions or move them up/down to change the priority.
