### ISSUE TITLE
A critical bug, as it can lead to a memory leak if you work with a terminal and a large amount of information.

### ISSUE THREAD

**Issue by Erslsf** [microsoft/vscode#209308]
Does this issue occur when all extensions are disabled?: Yes/No

https://github.com/microsoft/vscode/assets/149724736/cd1d9faa-0987-4d1d-aa93-b9fe1b1e4df1

- VS Code Version: 1.87.2
- OS Version: : Windows_NT x64 10.0.22621

When working with a terminal window, a strange bug occurs. The js code states that after displaying the data, you need to issue the console.clear() command, but if the window is smaller than your output data, scrolling is activated to scroll down so that the user can see more data, but at this moment I don’t know why console.clear( ) does not partially or fully perform its function. In the video that I recorded, you can see that initially I opened the terminal window high, almost the entire screen, then I lowered it so that scrolling would turn on. but after I returned it to its original position and scrolled a little to the top, non-deleted data from the previous session appeared. In my case, the problem was larger because I left collecting information from the Internet for a while and I did not know about this bug, as a result, after 2 hours of absence, my computer began to lag, and the reason for this was that vs code took up 2 GB of RAM. But the problem was that the information displayed was not deleted from the console, but was simply accumulated in it.
In another situation earlier, I wanted to print the values from an array to the console for verification. the array contains more than 500 values. After the output, I immediately saw that the array was not being deleted from the console. and thought that I wrote the js code crookedly, after three hours of psychosis, I gave up on this problem. But in the end, the problem here was not in my code at all.

**Comment by meganrogge** [comment]
Hi, that's a lot of information. Could you pls provide simple steps to reproduce the problem?

**Comment by Erslsf** [comment]
hi Megan, 1. here is my code in NODE JS. By running it in the POWERSHELL
terminal, you will see the generation of random numbers that are located in
an array (the code also uses console.clear()). 2. After running the code in
a few seconds, simply reduce the terminal window, I advise you to make it
super small, and then rotate the window to normal view and then you will
see that the data that should be deleted, on the contrary, will begin to
accumulate. 3. If we talk about the logic, it is very simple: when calling
the console.clear() command, it clears only the visible part of the
PowerShell window and does not clear what is not visible, which begins to
accumulate in the console itself and RAM. Сode: function
generateRandomNumber(min, max) { return Math.floor(Math.random() * (max -
min + 1)) + min; } function clearConsole() { console.clear(); } function
main() { const digitsARR = []; setInterval(() => { clearConsole(); const
newDig = generateRandomNumber(10000, 100000); числаМассив.push(digitsARR);
console.log('Arr of dig:', digitsARR); }, 50); } main();


Вт, 2 апр. 2024 г. в 19:11, Megan Rogge ***@***.***>:

**Comment by meganrogge** [comment]
can you reproduce this in an external terminal?

**Comment by Erslsf** [comment]
In the external terminal the problem is exactly the same. Or do u need screen record?

**Comment by meganrogge** [comment]
if the external terminal has the same problem, as you said, this is not a vscode issue

**Comment by Erslsf** [comment]
Ok, thanks for the clarification.

Ср, 3 апр. 2024 г. в 01:04, Megan Rogge ***@***.***>:
