### ISSUE TITLE
Adding function breakpoint through plugin API does not result in DAP call to add breakpoint

### ISSUE THREAD

**Issue by colin-grant-work** [microsoft/vscode#209386]
Does this issue occur when all extensions are disabled?: No - relates to behavior of plugin API.

- VS Code Version: 1.87.2
- OS Version: RHEL8

Steps to Reproduce:

1. I have a plugin with code like this:

```typescript
    commands.registerCommand("add-a-function-breakpoint", () => {
		debug.addBreakpoints([
			new FunctionBreakpoint("get_char", true)
		]);
	});
```

that I am running together with the [CDT-GDB VSCode plugin](https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode). When this code is run, a breakpoint does appear in the breakpoints widget, but the breakpoint is not sent to the debug adapter, and so it is not set with GDB and cannot be hit.

When the builtin ['Add Function Breakpoint' command](https://github.com/microsoft/vscode/blob/e02d14210805688fc558069c5b8ffeb2d9fbb9f1/src/vs/workbench/contrib/debug/browser/breakpointsView.ts#L1401-L1429) is invoked, it isn't until the user enters the name of the function that [a chain of calls](https://github.com/microsoft/vscode/blob/e02d14210805688fc558069c5b8ffeb2d9fbb9f1/src/vs/workbench/contrib/debug/browser/breakpointsView.ts#L946) is set off that leads to [a transmission to the adapter](https://github.com/microsoft/vscode/blob/e02d14210805688fc558069c5b8ffeb2d9fbb9f1/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L427). When a breakpoint is added via the extension API, no further input is required, so after [the event for a new breakpoint](https://github.com/microsoft/vscode/blob/e02d14210805688fc558069c5b8ffeb2d9fbb9f1/src/vs/workbench/contrib/debug/common/debugModel.ts#L1902) is fired, there is no path leading to actually setting the breakpoint with a debug adapter.

**Comment by roblourens** [comment]
May for verification

**Comment by eleanorjboyd** [comment]
Hi @colin-grant-work ! Are you able to verify this fix is resolved? You can do so by using vscode insiders and making sure you are on the newest version of insiders. Please let me know if you are able to see that the bug is resolved. Thank you!
