### ISSUE TITLE
Incorrect layout of welcome page in the absence of suggestions

### ISSUE THREAD

**Issue by obstrasium** [microsoft/vscode#209335]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2
- OS Version: Windows 10 v19045

Steps to Reproduce:

Same as the issue #178831, viewing the welcome after skipping any suggestions results in the UI resorting to a layout with lots of empty space to the right.

<img width="1120" alt="Code_MFc77LAPso" src="https://github.com/microsoft/vscode/assets/90981666/4896e986-99d2-4a25-993f-c7f672aa649a">

Since the previous issue had been resolved successfully, the fixes implemented previously have probably been overrided or overwritten by a change.

**Comment by bhavyaus** [comment]
This is fixed in the latest stable release.
