### ISSUE TITLE
Minimap: Limit its width to a maximum of 150px

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#20931]
The minimap is today sized (from a width p.o.v) in such a way to fit all characters in the viewport.

Add a limit, of, say, 150px to its width.

A bit too wide:
![image](https://cloud.githubusercontent.com/assets/5047891/23128599/cc5c3a2e-f77f-11e6-8997-20df3f804b8e.png)

**Comment by pohmelie** [comment]
Vote this to be optional, since width based on "fit all characters in the viewport" is pretty straight and nice for me. And, AFAIR, atom have same behavior.

**Comment by gamedevsam** [comment]
Please make this an editable setting, thanks VS code wizzards!
