### ISSUE TITLE
Git - The source file does not have the correct encoding format in the source control comparison tool (Working Tree view)

### ISSUE THREAD

**Issue by GuillaumeBernard3535** [microsoft/vscode#209348]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.87.2
- OS Version: Windows_NT x64 10.0.19045.4170

Steps to Reproduce:

1. Create a file with Windows-1252 encoding. In this file, put special characters like in the French word "accentué"
2. Commit it in git repository
3. Modified the file
4. Go to "Source control" panel, and clic on file change. On left view, special characters are misinterpreted and appear as modifications !

![image](https://github.com/microsoft/vscode/assets/103589825/06d6540d-0d29-4047-b979-8d38b04ae040)

**Comment by lszomoru** [comment]
Sorry for not getting back to you on this until now. Are you still able to reproduce with the latest version of VS Code Insiders? Could you please give that a try and reopen the issue if you are still experiencing this? If you do, could you please share the * values of the following settings:
* files.encoding
* files.candidateGuessEncodings
* files.autoGuessEncoding
