### ISSUE TITLE
Automatically update links when copy/pasting between markdown files

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#209318]
Tracks automatically rewriting links in text that is copy and pasted between markdown files. This includes fixing the paths on relative links and also bringing along link definitions if references are copied

**Comment by Evileoo** [comment]
This is genius !
Spent hours writing docs in markdown and never thought of this 😂

**Comment by mjbvz** [comment]
Will ship as experimental in April. Moving to may to track finalization if everything looks good

**Comment by mjbvz** [comment]
To verify, give a quick run through of the previous test plan item: [#210945](https://github.com/microsoft/vscode/issues/210945)

Also check that the setting names are no longer marked `experimental`

**Comment by DonJayamanne** [comment]
> Also check that the setting names are no longer marked experimental
Verified

Tested https://github.com/microsoft/vscode/issues/210945 and it fails to update the links


![Image](https://github.com/user-attachments/assets/afe6ead7-d4c3-4119-a71f-36e445e174cf)

**Comment by mjbvz** [comment]
@DonJayamanne Works for me. Do you see a widget after pasting that lets you select `update links`:

![Image](https://github.com/user-attachments/assets/4fefdb4f-80c2-49de-83cb-f00fdd066b67)

**Comment by mjbvz** [comment]
Also make sure you haven't disabled `"editor.pasteAs.enabled"`

**Comment by DonJayamanne** [comment]
> Do you see a widget after pasting that lets you select update links:

Yes


![Image](https://github.com/user-attachments/assets/e5eef379-9b35-43fe-a112-97a956eb937a)


> Also make sure you haven't disabled "editor.pasteAs.enabled"

Yes

FYI, this is a new vscode profile (hence using defaults).



![Image](https://github.com/user-attachments/assets/20d34c06-7f2d-4df0-b9b7-93fca260b40d)

**Comment by mjbvz** [comment]
Ok thanks, that's the expected behavior actually now. I forgot that this changed when I finalized this 

The feature should now always be enabled by default but it should never kick in automatically. To verify:

- Confirm that you don't see the widget if you are not copy and pasting markdown that contains any links

- Confirm you see the widget when pasting links. Confirm you can click on the widget to update the links

**Comment by DonJayamanne** [comment]
In that case, the following setting seems misleading
My expectation would be that the links would automatically get updated instead of me having to select some item from a dropdown widget.
I.e. I'd consider re-wording the text


![Image](https://github.com/user-attachments/assets/0c22c680-5ef2-4990-b8c9-e4168d374f12)
