### ISSUE TITLE
[Feature Request] Open Problems/Output/Debug Console/Terminal in different window

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#20933]
- VSCode Version: 1.9
- OS Version: Windows 10

It would be quite useful when working with multiple displays to move the Output Tab into the other screen to see what's going on.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by jens1o** [comment]
What's the issue called? What should I searched for?
