### ISSUE TITLE
Terminal with Pwsh (x64) - CLS leaves 1 line of code behind

### ISSUE THREAD

**Issue by JeremyTBradshaw** [microsoft/vscode#209340]
Type: <b>Bug</b>

When I do CLS (Clear-Console), my last command is left as the very top row.  When I type, I can see the cursor moving behind the letters of that last line of code.  That is, my new command is actually typing onto a blank line but the terminal insists on showing the text from the previous command.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (5.59GB free)|
|Process Argv|--crash-reporter-id adefba71-b7ac-4e94-9af1-1427a7e4d304|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
html-preview-vscode|geo|0.2.5
rainbow-csv|mec|3.11.0
live-server|ms-|0.4.13
powershell|ms-|2024.0.0
kuskus-kusto-syntax-highlighting|ros|1.2.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
8082a590:30971561
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:30996668
7ghi1836:30988842
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by meganrogge** [comment]
a gif would help.

do you have `terminal.integrated.stickyScroll.enabled` on?

**Comment by JeremyTBradshaw** [comment]
You know, I don't even have Microsoft Terminal installed on this system where I'm working from.. Windows 10, MS Store disabled by GPO.  Some store apps available in Software Center.

I was going to try and get you a gif, but I don't know how to make animated gifs and won't be able to install anything.  I bet you're right on the later version of Windows thing.  But I did notice this one for a while and it is super annoying.  It's since recently, though not sure exactly how many VS Code releases ago.  I'll move on and be OK, thanks.
