### ISSUE TITLE
Memory Window stops updating and remains static once the debugger has stopped

### ISSUE THREAD

**Issue by Yazwh0** [microsoft/vscode#209367]
Type: <b>Bug</b>

The Memory window will stop updating once the bugger stops and not refresh when debugging restarts.

This means the window continually needs to be closed and reopened, which isn't a great user experience.

Looking at the DAP messages, there isn't a call to the debugger to update on the new sessions. Its like it forgets about the memory window.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7900X 12-Core Processor             (24 x 4691)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.15GB (48.69GB free)|
|Process Argv|--folder-uri file:///c%3A/Documents/Source/BitMagic/BitMagic.Examples --crash-reporter-id 8edda842-6c09-448c-9791-281fa8c71f31|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.1.4
Bookmarks|ale|13.4.2
nugetpackagemanagergui|ali|2.1.0
masm|bli|0.0.5
npm-intellisense|chr|1.4.5
vscode-markdownlint|Dav|0.54.0
vscode-eslint|dba|2.4.4
vscode-solution-explorer|fer|0.8.5
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.82.1
file-downloader|min|1.0.13
csdevkit|ms-|1.4.29
csharp|ms-|2.22.5
dotnet-interactive-vscode|ms-|1.0.5164010
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.0.3
vscodeintellicode-csharp|ms-|0.1.26
debugpy|ms-|2024.2.0
isort|ms-|2023.10.1
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.2
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.86.0
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.14
makefile-tools|ms-|0.9.10
powershell|ms-|2024.0.0
veriloghdl|msh|1.13.5
deepdark-material|Nim|3.3.1
vscode-versionlens|pfl|1.9.2
bash-debug|rog|0.3.9
code-spell-checker|str|3.0.1
arcade|tha|1.4.16
code-ca65|tlg|1.2.5
cmake|twx|0.0.17
bitmagic|yaz|0.1.18
markdown-all-in-one|yzh|3.6.2

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
f8hc8238:30694864
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g1icg217:30999571

```

</details>

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/debug-adapter-protocol/issues/238
