### ISSUE TITLE
How should I write a ssh config when # appears in the username.

### ISSUE THREAD

**Issue by xu19971109** [microsoft/vscode#209398]
**It seems you didn't support # in User.
I tried `""` to include User. I tried  to add `\` before `#`. Nothing worked!** 

![image](https://github.com/microsoft/vscode/assets/50237122/67d473e3-63b5-4f50-acb8-d9552bae3a01)

**The connection page does not recognize characters before `#`.** 

![image](https://github.com/microsoft/vscode/assets/50237122/017dcb0e-c67c-4755-8182-73253ba93bb4)

**But when I tried to ssh in terminal, use # directly, wrap the user name with "", and add \ before # to successfully connect.
Even `ssh $Host` can work well.
What should I do?**

My vscode version
```
版本: 1.85.2 (Universal)
提交: 8b3775030ed1a69b13e4f4c628c612102e30a681
日期: 2024-01-18T06:40:32.531Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
```

My OS version
```
MacSO Sonoma 14.0 
Apple M2
```

**Comment by xu19971109** [comment]
Who can help me?

**Comment by roblourens** [comment]
The extension doesn't parse your ssh config- this is just however it works in ssh. Maybe you need to quote it
