### ISSUE TITLE
Support Environment variables in settings/  SSH Config files

### ISSUE THREAD

**Issue by seanvandermolen** [microsoft/vscode#209392]
Syncing SSH Configs and Keys using OneDrive for Business to facilitate syncing the config file on a laptop on desktop.
Two issues arise, depending on the time frame the user profile is created/ existing profiles EntraID does not necessarily use the same profile name.  For example, on my laptop it's just my first name all lower caps.  Recently rebuilt my workstation and the profile uses my full name.  Second issue, on my desktop I have my profile relocated on a large SSD so all my SharePoint/ OD files are always available with a custom path/ drive letter. One the laptop it's using default C:\.  

The issue is with the SSH config location un-synced, I'd have to manage two separate config files for each device using the correct paths pointing to the key folder which I'm also keeping within my personal OneDrive store.  If I could use %OneDriveCommercial% in file paths within the config file and settings I'd be able to work around these issues.

**Comment by roblourens** [comment]
We don't do anything custom with the ssh config file- we only invoke `ssh` which reads your config file as normal.
