### ISSUE TITLE
Open file tabs

### ISSUE THREAD

**Issue by sampsont** [microsoft/vscode#209350]
Type: <b>Feature Request</b>

Please make the tab for the currently open file easier to recognize.  Currently, it is very difficult to see which tab is highlighted because the color of the tab is only slightly lighter than all the other tabs.  I'm using the default color scheme.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:14:59.643Z)
OS version: Linux x64 5.15.0-101-generic snap
Modes:

**Comment by gjsjohnmurray** [comment]
Please use the advice at https://code.visualstudio.com/api/references/theme-color to customize the theme to your liking.
