### ISSUE TITLE
VSCode doesn't remember a previous session

### ISSUE THREAD

**Issue by anton-khodak** [Microsoft/vscode#20930]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.4.0-62-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|MagicPython|magicstack|1.0.6|

---

My VSCode app never restores the previous session after exit (files I edited and the layout) and always opens up with a blank `Untitled-1` document. It seems not to be a canonical behavior, from the docs

> -n or --new-window - Opens a new session of VS Code instead of restoring the previous session (default).

**Comment by bpasero** [comment]
@anton-khodak can you share your settings?

**Comment by anton-khodak** [comment]
@bpasero 
```
// Place your settings in this file to overwrite the default settings
{
    "files.associations": {
        "*.cwl": "yaml"
    },
    "files.autoSave": "onFocusChange",
    "workbench.welcome.enabled": true,
    "files.hotExit": "onExit",
    "window.restoreFullscreen": true
}
```

**Comment by bpasero** [comment]
+ @Tyriar as this maybe is a Linux specific issue (with the launcher? or the new cli option to open empty?)

@anton-khodak how do you launch Code so that it results in opening empty? I cannot reproduce like this:

![untitled](https://cloud.githubusercontent.com/assets/900690/23161517/c2854332-f82a-11e6-8e4d-72baed32e3df.gif)

**Comment by Tyriar** [comment]
It would surprise me if it's related to the launcher as I launch insiders almost exclusively with the win+4 hotkey. @anton-khodak any more information on how you launch and what specific operating system you're on would be useful.

**Comment by anton-khodak** [comment]
@bpasero What tool did you use to record gif from screencast?

**Comment by anton-khodak** [comment]
@bpasero @Tyriar 
![peek 2017-02-27 13-00](https://cloud.githubusercontent.com/assets/10351924/23359075/42523cca-fced-11e6-8743-40b56b1989bb.gif)

System information:
Linux Abc 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Desktop environment: Xubuntu

**Comment by bpasero** [comment]
Ok thanks, this is #207
