### ISSUE TITLE
VS Code extension cli options does not work with non-default profiles

### ISSUE THREAD

**Issue by vivekweb2013** [microsoft/vscode#209366]
VS Code is using only the default profile in context of executing [extension cli](https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions). There seems to be no way to install, uninstall, disable or query extensions for a specific profile using the cli.

IMO, The extension specific commands should accept the target profile option and use default profile only when no value is provided for that option.

- VS Code Version: 1.87.2
- OS Version: macOS 14.4.1

Steps to Reproduce:

1. Create a profile in VS Code and switch to that profile
2. Run any [extension cli](https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions)
3. You will find that the commands are executed against the default profile only.

**Comment by sandy081** [comment]
You can pass `--profile` arg with the profile name to manage extensions in that profile.

**Comment by vivekweb2013** [comment]
Indeed! Thanks @sandy081 for sharing this. It is working as expected. 
May I ask where is this `--profile` option documented 🤔 . I only found one [reference here](https://code.visualstudio.com/docs/editor/profiles#_command-line) but this is in context of launching vscode with a profile.
I did not find anything in the [docs](https://code.visualstudio.com/docs/editor/command-line#_core-cli-options) that suggest if this could be used with other CLI options  🤷‍♂️

**Comment by sandy081** [comment]
You can see that in the help

`code --help`
