### ISSUE TITLE
Image preview could support non-file schemes

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#209453]
For example, in GitHub Pull Requests, we have a `pr` scheme for files in a PR that is not checked out.

**Comment by mjbvz** [comment]
Should work. Maybe something on the GitHub pr side with the file system provider.  Debugging, I see the file system request returns an empty file:

![Image](https://github.com/microsoft/vscode/assets/12821956/73064471-3d2a-4524-ad68-bc2fce34cc3b)

@alexr00 Can you please look into the file read request and why GitHub pr isn't returning the image data

**Comment by alexr00** [comment]
I never even saw the file system provider get called. I have a PR for you that adds support for this with data URIs though: https://github.com/microsoft/vscode/pull/209458

**Comment by alexr00** [comment]
Looking again, I'll let you know what I find.

**Comment by alexr00** [comment]
Found the issue and fixed here: https://github.com/microsoft/vscode-pull-request-github/commit/50b817841d6aad0bdf8e494b64662d16b28684b2
