### ISSUE TITLE
django开发web项目，终端命令导致运行报错

### ISSUE THREAD

**Issue by yunfeifei** [Microsoft/vscode#20940]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.0|
|theme-onedark|azemoh|0.4.3|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.5.8|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|beautify|HookyQR|0.8.4|
|mssql|ms-mssql|0.2.1|
|csharp|ms-vscode|1.7.0|
|seti-icons|qinjia|0.1.3|
|vscode-icons|robertohuertasm|7.2.0|
|vscode-sql-beautify|sensourceinc|0.0.4|
|bootstrap-3-snippets|wcwhitehead|0.0.9|

---

Steps to Reproduce:

1.执行python manage.py runserver，显示python无响应。
![2017-02-21_000650](https://cloud.githubusercontent.com/assets/7730601/23132791/b6b1f854-f7c9-11e6-8e1c-2d3e4e886603.jpg)

2.

**Comment by Emeryao** [comment]
It is Python not responding instead of VS Code 
I think maybe you should file an issue for Python not here 😆

**Comment by roblourens** [comment]
It looks like this is a problem with python/django, not vscode. Please add more details if that is not the case.

**Comment by yunfeifei** [comment]
But i run the same command in 'cmd',it works rightly！

**Comment by Emeryao** [comment]
试试管理员身份运行vs code 呢？
另外 你的截图里的terminal是powershell不是cmd哦
