### ISSUE TITLE
Debugging Code Lens Provider Causes Long Debounce

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#209441]
* Register a code lens provider:
```ts
languages.registerCodeLensProvider("javascript", {
   provideCodeLenses(document, token) {
     return [];
   });
});
```
* Put a breakpoint at `return [];` 
* Debug the extension and open a javascript document
* Wait for the breakpoint to be hit.
* Then, wait for 30 seconds (e.g. because stepping through the implementation takes a while)
* Then modify the javascript document to trigger another call to `provideCodeLenses`
* Notice it takes about 30 seconds until  `provideCodeLenses` is called again.

This is quite surprising.

I think this happens because of the dynamic debouncing of language features.
I suggest that dynamic debouncing of language features is set to a maximum of 2 seconds when an extension is debugged (i.e. when the process arg `extensionDevelopmentPath` is present), so it should not have any production impact.

What do you think?

**Comment by hediet** [comment]
Interesting. I can consistently reproduce with yesterdays VS Code build.
```
Version: 1.88.0-insider (user setup)
Commit: ae59067554575afaba07640320a26435c8e05175
Date: 2024-04-02T12:33:18.940Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
```

This is my launch config:
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
				"${workspaceFolder}/demo"
			],
			"outFiles": ["${workspaceFolder}/dist/**/*.js"],
			"preLaunchTask": "npm: watch"
		}
	]
}
```

**Comment by jrieken** [comment]
Read the whole snippet... I works the wrong way around
