### ISSUE TITLE
Inline Chat Widget: Shows Accept button and `Made changes` text when there are no changes

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#209430]
I asked inline chat to make a change to my code. It responded with exactly the same code as I selected (this is ok, it's not the problem). This means there is no changes/diff shown, however, the Accept and Discard are visible even though both accepting and discarding do nothing. Also Copilot answers with the default text `Made changes` even though it did not make changes.

<img width="727" alt="image" src="https://github.com/microsoft/vscode/assets/44439583/5ce03f9e-0b27-4ba0-a7d4-f0847a3179b7">

**Comment by jrieken** [comment]
same/related https://github.com/microsoft/vscode/issues/208576
