### ISSUE TITLE
TERMINAL OUTPUT

### ISSUE THREAD

**Issue by Nju9una** [microsoft/vscode#209404]
Type: <b>Bug</b>

whenever i try to run code on my visual studio code when i am supposed to key in the values on my terminal, it does nor allow me.It brings me the prompt to key in my desired values on the output section but it doesnt let me key in anything or rather it doesnt register down what i am keying in

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:14:59.643Z)
OS version: Linux x64 6.5.0-26-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 3082)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.36GB (11.87GB free)|
|Process Argv|. --crash-reporter-id 6ba22458-737d-4252-9bd8-c673e9b135de|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
vscode-eslint|dba|2.4.4
gitlens|eam|14.9.0
vscode-html-css|ecm|2.0.9
auto-close-tag|for|0.5.15
code-runner|for|0.12.1
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.82.1
vscode-codemetrics|kis|1.26.1
vscode-exec-node|mir|0.5.6
vscode-azurefunctions|ms-|1.14.0
vscode-azureresourcegroups|ms-|0.8.4
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.4.1
azure-repos|ms-|0.38.0
remote-repositories|ms-|0.40.0
vsliveshare|ms-|1.0.5918
vsliveshare-audio|ms-|0.1.93
debugger-for-chrome|msj|4.13.0
vscode-for-node-js-development-pack|nod|2.0.1
vscode-versionlens|pfl|1.9.2
LiveServer|rit|5.7.9
vscode-auto-close-bracket|sdd|0.0.3
code-settings-sync|Sha|3.4.3
node-pack|Swe|0.1.16
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
quokka-vscode|Wal|1.0.634
vscode-import-cost|wix|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyonecf:30548226
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
8082a590:30971561
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:30988843
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
