### ISSUE TITLE
debugging with edge

### ISSUE THREAD

**Issue by dleasman** [Microsoft/vscode#20942]
No matter what debugger I use, the errors come up labeled as "debugger for chrome", even if the chrome debugger is not installed.

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-raml|blzjns|1.0.7|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.6|
|vscode-yaml-validation|djabraham|0.0.1|
|vscode-html-css|ecmel|0.0.33|
|vscode-npm-script|eg2|0.1.8|
|vscode-firefox-debug|hbenl|0.8.8|
|minify|HookyQR|0.3.0|
|copy-markdown-as-html|jerriepelser|1.0.0|
|Angular1|johnpapa|0.1.16|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|debugger-for-chrome|msjsdiag|2.5.3|
|debugger-for-edge|msjsdiag|0.4.1|
|vscode-icons|robertohuertasm|7.2.0|
|sass-indented|robinbentley|1.3.0|
|vscode-sql-beautify|sensourceinc|0.0.4|
|stylelint|shinnn|0.23.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by weinand** [comment]
@dleasman please provide detailed steps what you tried to do.

What launch configuration are you using?

**Comment by weinand** [comment]
no response. closing.
