### ISSUE TITLE
Support for running VS Code Server in a container

### ISSUE THREAD

**Issue by polariton** [microsoft/vscode#209446]
# Summary
Given the prevalence of outdated Linux distributions among Azure tenants and the recent increased version requirements for glibc/libc++ in VS Code, there is a pressing need for supporting the execution of VS Code Server within a container on a remote host. This will enable VS Code Server to run consistently across diverse Linux distributions, eliminating compatibility issues and enhancing the user experience. With the current landscape of diverse and outdated Linux distributions in cloud services, introducing container support for VS Code Server is not just a feature enhancement but a necessity.

# Background
Many cloud services, including Azure, continue to operate on older Linux distributions, which often lack the required updates to support the latest versions of glibc/libc++. As a result, users encounter compatibility issues when attempting to run VS Code Server on these systems. By leveraging containerization technology, VS Code Server can be encapsulated with all its dependencies, ensuring consistent performance and compatibility across various Linux distributions.

# Requested Features
- Add a configurable command line to enable running VS Code Server within a container on a remote host. Examples include:
```
docker exec -d <container-image> <vscode-server>
singularity exec <container-image> <vscode-server>
lxc exec <container-image> -- <vscode-server>
```

- Official container images for dependency management of VS Code Server.

**Comment by aeschli** [comment]
When we build the VS Code server, we have the regular build that requires glibc >= 2.28 as well as a legacy build for older OSes.
See https://code.visualstudio.com/docs/remote/faq#_can-i-run-vs-code-server-on-older-linux-distributions

Our remote development extensions (SSH, Dev Containers, SSH) have been updated to pick the matching build.

Now, you suggest to run the code server in a container on an old Linux System. Yes, that of course possible and should work with the command line examples you suggest. It's basically what the dev containers extension does. 
In fact, the SSH and the Tunnels extension allow you to open a dev container.

So I'm not sure what's missing. The command line you know and creating a container image is what the dev container extension is for.

**Comment by polariton** [comment]
To run extension remotely, one should run VS Code Server first. The missing element is running the remote instance of VS Code Server in a container via user-defined command line, when you use Remote Development extension. Running VS Coder Server in a container allows to override the outdated versions of glibc and libc++. Right now, VS Code Server runs only on a bare host OS.

**Comment by polariton** [comment]
I studied a bit how VS Code Server is written and found that it is a Node.js app. There is already a quick guide on running Node.js apps in a Docker container: https://code.visualstudio.com/docs/containers/quickstart-node . These instructions could be applied to the VS Code Server for solving its dependency problems, as well as to any other Node.js app.

For Singularity, the similar guide can be found here: https://sylabs.io/2018/09/nodejs-on-singularity/ 
Command line to run Node.js as a server in a container is `singularity instance start image.sif node`.

**Comment by aeschli** [comment]
> Right now, VS Code Server runs only on a bare host OS

There's no such restriction. Running the server in a container is already possible and is what we do in the [Dev Container](https://code.visualstudio.com/docs/devcontainers/containers) extension.

You can also connect to a SSH machine, and when in SSH window to a dev container running on that machine.
@chrmarti @connor4312 I didn't find this in the documentation...

Closing the issue

**Comment by chrmarti** [comment]
> You can also connect to a machine with the [Remote-SSH extension](https://code.visualstudio.com/docs/remote/ssh), and when in the SSH window connect to a dev container running on that machine. [@chrmarti](https://github.com/chrmarti) [@connor4312](https://github.com/connor4312) I didn't find this in the documentation...

This is documented here: https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host

**Comment by polariton** [comment]
None of your links are working. I get "Service Unavailable" error all the time.

**Comment by chrmarti** [comment]
We currently have a "legacy" VS Code Server build that is installed when the increased version requirements for libc and libc++ are not met. This will go away within a year though.

To use your proposed approach you could run the VS Code CLI in a container to set up a tunnel. The VS Code CLI is a separate standalone download. See https://code.visualstudio.com/docs/remote/tunnels for details.

Hope that addresses your question.

**Comment by polariton** [comment]
OK, thanks. This should work for now, but it requires manually pre-started VS Code Server in a container on the remote side. The feature I was talking about would do the similar thing but the VS Code Server could run in a container on-demand, when the user connects via SSH.

**Comment by aeschli** [comment]
Closing the issue, no changes planned.
