### ISSUE TITLE
Shell Script here document syntax highlighting fails to recognize the end delimiter in some cases

### ISSUE THREAD

**Issue by vbrozik** [microsoft/vscode#209422]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2 (user setup)
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Open a new text file Ctrl+N (no need to save it).
2. Paste a problematic example content like the following one:
``` bash
#!/bin/sh

cat <<- E+OF
here document
E+OF

# Normal highlighting should resume here but in VS Code it does not.
```
3. Once the word defining the here document delimiter contains a character like `+` or `=` (probably there are additional problematic characters), the redirection operator is the variant with removing of leading tabs `<<-` and there is a space between the operator and the word then VS Code does not recognize the end of the here document delimited by the line with the delimiter (here `E+OF`).

Example of incorrect highlighting - the comment (and possible following lines) is highlighted as if it was part of the here document:

![Example of incorrect highlighting](https://github.com/microsoft/vscode/assets/5073939/72e64784-d53c-4b16-b09f-2996ecb679c3)

These slight modifications are highlighted correctly:

``` bash
#!/bin/sh

cat <<- E-OF
here document
E-OF

# Normal highlighting resumes if "+" is replaced by "-".
```

``` bash
#!/bin/sh

cat <<-E+OF
here document
E+OF

# Normal highlighting resumes if there is no space between the redirection operator and the word.
```

Note: I have encountered this bug because I normally use `+++EOF+++` as a delimiter.

**Comment by alexr00** [comment]
Thanks for providing clear screenshots and code samples! We just made the stable release yesterday and the fix should be available there.

**Comment by vbrozik** [comment]
Thanks. I have upgraded to 1.88.0 stable and the highlighting works correctly.
