### ISSUE TITLE
Feature Request: When opening Command Palette, have the last command used selected

### ISSUE THREAD

**Issue by marlonmarcello** [Microsoft/vscode#20949]
It's very common to have to run the same command multiple times in a row, it would be very nice if when opening the Command Palette, the last command used to be selected, so it's just a quick Enter and 💥 !

Or better yet, when opening the Command Palette, have the most used commands at the top.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by martin-stone** [comment]
#17163
