### ISSUE TITLE
run checks when committing from F1

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#20944]
* make changes
* hit F1 > Git: Commit
* type a long, long message
* 🐛 no validation

**Comment by joaomoreno** [comment]
Actually I can't do this, otherwise @bpasero prevents the user from submitting that text. I still want him to be able to submit the commit message even if there's a warning/error. Maybe we need more semantics on what can be returned, not just a simple `string` which means an absolute error.

**Comment by bpasero** [comment]
@joaomoreno @jrieken to clarify we are talking about support to show a warning in the picker widget but still allow to commit it? Sounds like another feature to add to the picker API?

**Comment by jrieken** [comment]
Yes, a warning instead of an error as we show it today. The API currently doesn't allow that

**Comment by jrieken** [comment]
There is now API for this.
