### ISSUE TITLE
Debugger: show variables in multiple ways: hex, dec, ascii, binary

### ISSUE THREAD

**Issue by GPContributors** [Microsoft/vscode#20941]
VS Code version: 1.8.1
Python Extension version: 0.3.24
Python Version: 3.5
OS and version: Windows 7

It would be nice to show all alternate forms of a variable into the debugger -- hex, dec, ascii, binary -- or have a way to switch between types in the UI.

thanks

**Comment by adelphes** [comment]
Sounds familiar... #17668

**Comment by isidorn** [comment]
Dup of #17668
@adelphes thanks for pointing this out
