### ISSUE TITLE
distinguish configurations base on pressing F5 (debug) or ctrl+F5 (launch)

### ISSUE THREAD

**Issue by qtbit** [Microsoft/vscode#20948]
I'd like to run one npm script defining a normal launch of an application by pressing ctrl+F5 (= launch the app) and the second npm script running the app in a debug mode by pressing F5 (= debug the app).

- VSCode Version: 1.9.1
- OS Version: Win 10

Steps to Reproduce:

1. Define 2 launch configurations.

```
{
    "version": "0.2.0",
    "configurations": [
        {
          "type": "node",
          "request": "launch",
          "name": "Launch Program",
          "cwd": "${workspaceRoot}",
          "runtimeExecutable": "npm",
          "runtimeArgs": [ "run-script", "start" ]
        },
        {
          "type": "node",
          "request": "launch",
          "name": "Debug Program",
          "cwd": "${workspaceRoot}",
          "runtimeExecutable": "npm",
          "runtimeArgs": [ "run-script", "debug" ]
        }
    ]
}

```
2. Run the first configuration by pressing ctrl+F5 and the second by pressing just F5 (debug mode).

**Comment by isidorn** [comment]
Somewhat related to https://github.com/Microsoft/vscode/issues/16613
