### ISSUE TITLE
barra de atividades

### ISSUE THREAD

**Issue by shkFigueiredo** [microsoft/vscode#209494]
Type: <b>Feature Request</b>

Good evening, my name is Andre, my problem is the following, my daughter removed an activity bar from my VS Code and I can't restore it, I can't go back to the original settings, I've tried everything and I can't, I can't use the program like this, can you help me? Anyway, thank you.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by rzhao271** [comment]
Hi Andre, I hope you've been able to get the activity bar back. If not, please try the following menu options. If that still does not work, please upload a screenshot of your VS Code.
![View > Appearance > Activity Bar Position > Default](https://github.com/user-attachments/assets/8e9cc50b-c67a-4585-b8f1-25584505240d)
