### ISSUE TITLE
newline issues in integrated terminal

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode#20955]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.12|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.8|
|Go|lukehoban|0.6.53|
|cpptools|ms-vscode|0.10.1|
|Ruby|rebornix|0.10.4|
|java|redhat|0.0.10|
|annotator|ryu1kn|0.10.1|
|vscode-open-in-github|sysoev|1.4.0|
|Material-theme|zhuangtongfa|1.0.3|
|vscode-proto3|zxh404|0.1.0|

---

**Observed behavior (1):**

Steps to Reproduce:

1. Copy a line with no newlines, but that wraps (because of screen width) from the integrated terminal and paste back into the terminal
2.  The pasted line will now have newlines.

**Observed behavior (2)**

Steps to Reproduce:

1. Start to type a line at a prompt in the terminal
2. Paste additional text whose length should cause the line to wrap
3. The pasted line is garbled on a single line with no wrapping

**Comment by Tyriar** [comment]
These should be fixed with a fix to https://github.com/Microsoft/vscode/issues/8336

**Comment by Dominik-K** [comment]
It is not fixed in the new Version 1.11.1 (1.11.1) on MacOS "El Capitan" 10.11.6 (15G1217).

**Comment by Tyriar** [comment]
Can you provide a screenshot of the issue?

**Comment by Dominik-K** [comment]
Here's a screen"cast" of the behavior. In between, I highlighted the output text and pressed "Cmd+C".

<a href="https://asciinema.org/a/c4d4z6l0mt8cvumb73c5er6g3" target="_blank"><img src="https://asciinema.org/a/c4d4z6l0mt8cvumb73c5er6g3.png" /></a>

**Comment by Tyriar** [comment]
@Dominik-K this is likely due to https://github.com/sourcelair/xterm.js/issues/443, let's track it over there.
