### ISSUE TITLE
VS Code Insider - Welcome tab is hung...

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/vscode#20951]
- VSCode Version: Code - Insiders 1.10.0-insider (64801727521592cf5fe64fd911b1efe41b1ea732, 2017-02-20T07:13:27.765Z)
- OS Version: Windows_NT ia32 10.0.15007
- Extensions: N/A
|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|python|donjayamanne|0.5.8|
|code-runner|formulahendry|0.6.10|
|csharpextensions|jchannon|1.2.0|
|mssql|ms-mssql|0.2.1|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|vscode-icons|robertohuertasm|7.2.0|
|python|tht13|0.2.3|
|python-extended-snippets|tushortz|0.0.1|

---

Steps to Reproduce:

1. After "Close Folder" the Welcome tab is hung trying to refresh the screen".

![vscodeinsider_welcomeblank_2017-02-20_14-18-10](https://cloud.githubusercontent.com/assets/19892435/23138925/05da1620-f778-11e6-9f20-1e4d7a8001ee.jpg)

**Comment by joaomoreno** [comment]
I just hit this.

![image](https://cloud.githubusercontent.com/assets/22350/23156771/92d6f44e-f818-11e6-9942-723b0211663c.png)

**Comment by MartinSGill** [comment]
As of commit #9f9d79eb I'm seeing the Welcome page again, but I'm getting URI errors when I click on links, e.g. documentation:

![image](https://cloud.githubusercontent.com/assets/2271740/23175237/0661a3b4-f85f-11e6-8e00-0d178c16a701.png)

**Comment by chrmarti** [comment]
@MartinSGill That is a limitation when running from sources, some of the URIs and their commands are only configured through the build servers. The bug only reproduces when running an insider build on Windows.

**Comment by MartinSGill** [comment]
@chrmarti yeah sorry my bad. I was running insider build earlier today before switching to source, and got confused. Thanks for clearing up my issue though, hadn't realised that limitation existed in source builds.

**Comment by MaximoTrinidad** [comment]
Just an FYI

I update VS Code Insider Version 1.10.0-insider and I'm still getting a hung up Welcome tab.

![vscodeinsider_welcomeblank_2017-02-21_13-15-10](https://cloud.githubusercontent.com/assets/19892435/23178278/cf1196c0-f837-11e6-8ba9-719d00333f7c.jpg)

Thanks,
:)

**Comment by MaximoTrinidad** [comment]
Thanks guys!!
