### ISSUE TITLE
Getting Incorrectly "FAILED" Gradings

### ISSUE THREAD

**Issue by solluna03** [microsoft/vscode#209554]
In the assignment "Swap.cpp",I am getting the correct output and sortings, but the checker is saying that I am missing parts of my output, despite them clearly being there. Also, in one of the checks, it sorts the numbers 630. 1500. and 9. but is expecting sorted outputs of 2, 2, and 21.

Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by lszomoru** [comment]
@solluna03, seems that this is related to some course work. Please reach out to the support personnel of your corse. This repository  is specific to issues of the VS Code editor. Thanks!
