### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by Kiran-230202** [microsoft/vscode#209531]
Type: <b>Feature Request</b>

Terminal not take input

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes: Unsupported

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

Also , can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
