### ISSUE TITLE
Allow passing arbitrary NODE_OPTIONS to Node when starting TS Server

### ISSUE THREAD

**Issue by MichaelMitchell-at** [microsoft/vscode#209584]
Right now we have `typescript.tsserver.maxTsServerMemory` which lets users configure the `--max-old-space-size` flag value provided to whatever Node is at `typescript.tsserver.nodePath`, but there are other possible cases where one might want additional flags, e.g. `--require=pprof-it` for profiling tsserver or `--min-semi-space-size`/`--max-semi-space-size` for large monorepos similar to `--max-old-space-size`.  Rather than just adding these as options one by one as needed, it would be more future-proof to just provide a single way of providing these flags.

Just some examples of how this might be surfaced:
- Allow specifying these flags as part of `typescript.tsserver.nodePath`,
  e.g. `"typescript.tsserver.nodePath": "/usr/local/bin/node --max-old-space-size=4096"`
  or `"typescript.tsserver.nodePath": "NODE_OPTIONS='--max-old-space-size=4096' /usr/local/bin/node"`
- Add a separate setting, e.g. `"typescript.tsserver.nodeArguments": ['--max-old-space-size=4096'],`

**Comment by MichaelMitchell-at** [comment]
For now we're using this workaround (https://github.com/microsoft/TypeScript/issues/30981#issuecomment-489202213) that folks used to do before `typescript.tsserver.maxTsServerMemory` existed.

**Comment by mjbvz** [comment]
Sounds too specialized to add to core VS Code but as a workaround try pointing `nodePath` a proxy script that spawns node with the arguments you need. Something like:

```sh
#!/bin/sh

MAX_HEAP_SIZE= 12000

node --max-old-space-size=$MAX_HEAP_SIZE "$@" 
```

**Comment by mjbvz** [comment]
Sounds too specialized to add to core VS Code but as a workaround try pointing `nodePath` a proxy script that spawns node with the arguments you need. Something like:

```sh
#!/bin/sh

MAX_HEAP_SIZE= 12000

node --max-old-space-size=$MAX_HEAP_SIZE "$@" 
```
