### ISSUE TITLE
Disable minimap in Interactive playground

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#20950]
- VSCode Version: 1.10-Insider
- OS Version: macOS

We may want to disable disable minimap feature explicitly when creating editors in playground as most of them only contain a couple of lines.

<img width="1546" alt="screen shot 2017-02-20 at 11 17 31 am" src="https://cloud.githubusercontent.com/assets/876920/23138797/3316d048-f75e-11e6-9578-b429dbc367db.png">

**Comment by warpdesign** [comment]
How about doing the same thing for the settings pages ?

![minimap](https://cloud.githubusercontent.com/assets/199648/23186392/489ecf7c-f887-11e6-8803-0f935a137487.png)

**Comment by chrmarti** [comment]
Not sure, these can be large documents. /cc @sandy081

**Comment by sandy081** [comment]
Neutral to it. Ok to disable mini maps there.
