### ISSUE TITLE
Colon in | text block

### ISSUE THREAD

**Issue by almays** [Microsoft/vscode#20959]
I have yaml files with texts.
Texts can be multiline, include markdown. I screen out the texts with `|` thing.
```
En: |
  Some text: continuation of the text. 
```
In this case `Some text` is colorized as a key. But actually due to `|` it is going to be parsed as part of the text.

Yaml2json converter, for example, interpretes this syntax as expected:
```
{
  "En": "Some text: continuation of the text. \n"
}
```

But yaml colorizer mistakenly takes `:` in this case as key/value delimiter.

**Comment by aeschli** [comment]
This issue was moved to textmate/yaml.tmbundle#19
