### ISSUE TITLE
Problem with git command to open the merge editor when the file is renamed 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#209536]
1. Create a branch `testBranch` off of `main`
2. In `testBranch` rename a file
3. in `main` modify the same file
4. Fetch `main` if you haven't already
5. Checkout `testBranch`
6. `git merge main`
7. You'll get a merge conflict. From the SCM view, open the merge editor. The "Current" is correct, but the "Incoming" is empty.

**Comment by alexr00** [comment]
Looking into this and I might make a PR.

**Comment by hediet** [comment]
I think this is a duplicate of https://github.com/microsoft/vscode/issues/182569 or https://github.com/microsoft/vscode/issues/161321 or https://github.com/microsoft/vscode/issues/157818

**Comment by alexr00** [comment]
Not sure about the others, but https://github.com/microsoft/vscode/issues/182569 is definitely the same issue.
