### ISSUE TITLE
[html] Add symbol support for HTML files

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#20956]
WebStorm provides ["File Structure Popup"](https://www.youtube.com/watch?v=7Ai8966qny0&feature=youtu.be&t=39) support for HTML files. The closest vscode analog is file symbols (ctrl+shift+O) which is not currently supported for HTML files.

![image](https://cloud.githubusercontent.com/assets/2957173/23140975/c2e00306-f7b4-11e6-8ac9-b24f265aec23.png)

The vscode-html-language-service needs only a small change to support this. I have opened an [issue](https://github.com/Microsoft/vscode-html-languageservice/issues/8) there as well as a [pull request](https://github.com/Microsoft/vscode-html-languageservice/pull/7) to show how it can be added, but it would also require a change here to begin consuming the language service change.

![image](https://cloud.githubusercontent.com/assets/2957173/23141168/c7f47e0c-f7b5-11e6-8104-42cbc76cf09f.png)

**Comment by aeschli** [comment]
Thanks @hoovercj !
