### ISSUE TITLE
Unable to paste multiple lines to integrated terminal while debugging C++

### ISSUE THREAD

**Issue by gtb0** [microsoft/vscode#209598]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.88.0
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. 
```
#include <iostream>
using namespace std;

int main() {
    char x;
    cin >> x;
    cout << "hello";
    cout << "world";
    cin >> x;
    return 0;
}
```
2. If you add a breakpoint on the line cout << "hello" ;, step over does not work after pasting multiple lines to the terminal.

**Comment by roblourens** [comment]
Please file this on the C++ debug extension with more detail
