### ISSUE TITLE
VS Code restores original window position when opening files in a docked position.

### ISSUE THREAD

**Issue by larsw** [Microsoft/vscode#2095]
A VS Code instance that is docked  to the left or right on the Windows 10 desktop should not restore its orginal position when opening files (File -> Open File...)

**Comment by bpasero** [comment]
@larsw i cannot reproduce, I have a Window docked to the left and open a file in there and the window remains stable.

**Comment by larsw** [comment]
Colleague of mine can reproduce;

Dock VS Code to the right and dock another application to the left. Open file... and choose an arbitrary file. VS Code restores its original position.
(Same thing happens if you dock it vice versa).

**Comment by bpasero** [comment]
@larsw any chance for a video of this? I still cannot reproduce.

**Comment by larsw** [comment]
http://g.recordit.co/fow5Wti7dt.gif

**Comment by bpasero** [comment]
@larsw thanks, this is weird :|

**Comment by larsw** [comment]
Weird, and damn annoying. Let me know if there's any config/diagnostic dump I should append to this issue.

**Comment by larsw** [comment]
It might be worth mentioning that I use the new Virtual Desktop feature in Windows 10; E.g. I've created an additional desktop
by first flipping up the applications with Win-Tab, and on that screen, I've added an extra desktop that hosts some of the applications.

**Comment by bpasero** [comment]
I can reproduce with 0.10.6, but not with our master stream so I assume I fixed this already :+1:

**Comment by aeschli** [comment]
Also works for me.
