### ISSUE TITLE
Temporarily switch to release version of an extension when it is more recent than last pre-release

### ISSUE THREAD

**Issue by sfo** [microsoft/vscode#209522]
Summary
---
Even when being on the pre-release branch of an extension, if there is a more recent release version available, this one should be installed, instead of sticking to an old pre-release version.

Details
---
I am on the pre-release branch of an extension (specifically vscode-jupyter), for which the most current version is 2024.3.2024032701, which is about 1 week old. However, the most recent version of this extension is 2024.3.0, which comes from the release branch and is 1 day old.

Nevertheless, I have to either switch to the release branch or manually install this specific version from the pre-relaese branch using the "Install Another Version..." menu.

VSCode seems not to be able to recognize and install it automatically but rather insists of sticking to a pre-release version, even though the release version is available from the list of pre-release versions: 

![vscode-extension](https://github.com/microsoft/vscode/assets/571497/2c583a39-ab3e-4a4a-8c1b-187561b46d57)

**Comment by sandy081** [comment]
> Even when being on the pre-release branch of an extension, if there is a more recent release version available this one should be installed, instead of sticking to an old pre-release version.

Latest is determined by the semantic version not by publishing date. Even though the release version is published recently, latest pre-release version is greater in version than release version. So semantically, greater pre-release version is more recent than the latest release version.

**Comment by sfo** [comment]
Thanks for clarification.
However, @DonJayamanne [suggests that this is an upstream VS Code issue](https://github.com/microsoft/vscode-jupyter/issues/15488#issuecomment-2038183060), so I asked there to clarify. Maybe you could also give a hint, so we don't end up in a ping-pong about responsibilities for this issue.
