### ISSUE TITLE
Webview wrongly warns about missing CSP

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#209576]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0
- OS Version: macOS Sonoma

To reproduce, create a command that runs the following code:

```typescript
const viewer = vscode.window.createWebviewPanel(
  'foobar',
  `Preview`,
  vscode.ViewColumn.Beside,
);
viewer.webview.options = { enableScripts: true };
viewer.webview.html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
foobar
</body>
</html>`;
```

The warn only happens when setting `viewer.webview.options` after construction. But this seems to be a valid pattern as shown in the [custom-editor-sample](https://github.com/microsoft/vscode-extension-samples/blob/f4e09a3b7bce2604b93be118f9e006ef808e1ae9/custom-editor-sample/src/catScratchEditor.ts#L43).

On a side note, I see no other way to set options for a panel provided to `resolveCustomEditor`, because `registerCustomEditorProvider` only supports `WebviewPanelOptions` (`WebviewOptions` seems to have been overlooked, even the property is called like that).

**Comment by r3m0t** [comment]
Your webview CSP needs to include `webview.cspSource` otherwise the `enableScripts` won't take effect. https://code.visualstudio.com/api/extension-guides/webview

**Comment by mjbvz** [comment]
Hm I'm actually not seeing this warning. Steps:

1. Create new extension with `yo code`
2. Add the above code into the `test-ext.helloWorld` command handler
3. Debug extension and run the `hello world` command

Here's the warnings I see:

![Image](https://github.com/user-attachments/assets/8f6ee845-9475-482d-9d64-ae03759d67d9)

These are all expected right now and not related to the content/settings of the webview

Anything I'm missing?

**Comment by memeplex** [comment]
I'm not in a position to easily recreate this right now. The problem was exactly as described, the warning being about missing CSP, not the ones you saw. So if you're unable to reproduce this with a recent version of VSCode feel free to close it. If needed I will report it again in the future when I resume work on the project that originated this issue.


@r3m0t I fail to see the connection of your comment with what was reported above.

**Comment by mjbvz** [comment]
ok closing but can reopen if we hear about this still  happening
