### ISSUE TITLE
devcontainer extension broken

### ISSUE THREAD

**Issue by omlnaut** [microsoft/vscode#209518]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.87.2
- OS Version: 10.0.19045

Steps to Reproduce:

1. Create a new profile in VsCode
2. Install WSL (v0.86.0) and Devcontainer (v0.348.0) extension
3. Start a devcontainer that previously worked (or create a config from scratch)
4. Observe the error: Microsoft VS Code\Code.exe: bad option: --ms-enable-electron-run-as-node

I tried downgrading a couple of versions from devcontainer and also tried the pre-release versions. This worked yesterday, I don't know what updated to break this.

**Comment by omlnaut** [comment]
Well... completely uninstalling vscode and deleting all files in appdata/userprofile, then reinstalling solved that issue. Not sure what went wrong before :/

**Comment by chrmarti** [comment]
`bad option: --ms-enable-electron-run-as-node` suggests that you had an older version of the Dev Containers extension that no longer works with current VS Code versions.
