### ISSUE TITLE
Faster and/or consistent mouse scrolling

### ISSUE THREAD

**Issue by mchels** [Microsoft/vscode#20954]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Is there a setting that allows for faster scrolling? That is, more lines scrolled per notch of the mouse wheel. If not, I'd like to request it. My OS setting in Mouse Properties is to scroll 6 number of lines which appears to not be reflected in VSCode.

Steps to Reproduce:

1. Open a file with more lines than can be shown on the screen.
2. Scroll one notch with the mouse wheel. On my system the view scrolls about 2.5 lines.

**Comment by alexandrudima** [comment]
@mchels It can be a float:
```
  // A multiplier to be used on the `deltaX` and `deltaY` of mouse wheel scroll events
  "editor.mouseWheelScrollSensitivity": 1
```

**Comment by iwllyu** [comment]
hey @alexandrudima, that's a great setting and it helped me a lot

but I noticed that it only works in the text editor. For example, scrolling the in the sidebar (project navigator, or search results)
