### ISSUE TITLE
Unsaved file indicator on file tab does not respond unless tab switched

### ISSUE THREAD

**Issue by vreddipilli** [microsoft/vscode#209551]
Type: <b>Bug</b>

Expectation - 
1. Making any change on an open file is expected to show the unsaved file indicator in place of the close icon button on the file tab immediately after change. 
2. Also, any change done / undone on an unsaved file that brings the file back to the last saved state should trigger unsaved icon indicator to be replaced back with the close icon on file tab

Bug -
1. But the unsaved indicator does not show on the file tab unless switched to a different file. 
2. Again, the unsaved indicator stays unchanged even if file changes back to last saved state unless switched to a different file

https://github.com/microsoft/vscode/assets/128241268/a86720f7-6ab8-408c-98ce-4d10f015eba6

Interestingly, the Open Editors section header in the Primary Sidebar shows the "1 unsaved" indicator when a file is in unsaved state and clears when back to last saved state. 
Also, the Explorer button icon in the Activity Bar shows the unsaved file count indicator update when a file is brought to unsaved state and clears when no files in unsaved state.

It's just the unsaved indicator on the file tab close icon that doesn't respond to the file being brought to saved or unsaved state unless the tab is switched to another open file tab

VS Code version: Code 1.87.2 (Universal) (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 10, 11|
|Memory (System)|32.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id b2326291-774d-499c-9a03-2f2cbeb24189|
|Screen Reader|yes|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:30988843
dsvsc021:30996838
g1icg217:30999571

```

</details>

**Comment by lramos15** [comment]
Odd, I'm not able to repro this.

**Comment by benibenj** [comment]
@vreddipilli, does the dirty indicator correctly show in the open editors view or is it the same as the tabs?

**Comment by vreddipilli** [comment]
Hi. It had multiple other issues with the open editors view also having issue similar to the tab close icon dirty indicator where it was not reflecting change unless switching to a different tab.

I couldn't work with it and had to re-install VS Code. Issue was fixed after the clean re-install 

Closing this one out. Appreciate the help, all 😄
