### ISSUE TITLE
Unable to Load Iframe in Webview on vscode.dev

### ISSUE THREAD

**Issue by ritikramuka** [microsoft/vscode#209543]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.88.0-insider
- Running on: vscode.dev

Steps to Reproduce:

1. Create a new webview panel with `enableScripts: true`.
2. Set the webview HTML content to include an iframe that loads content from `https://www.wikipedia.org/`.
3. Observe that the iframe fails to load with the following errors:

   - Uncaught TypeError: Cannot read properties of null (reading 'classList') at `onresize` event and `onDocumentLoad` event. (See attached screenshots)
   - The console logs a CORS issue stating: "To use this resource from a different origin, the server needs to specify a cross-origin resource policy in the response headers."

I expected the iframe to load the external content within the webview panel, given that the appropriate permissions (`allow-scripts allow-same-origin`) were set for the iframe's sandbox attribute. However, it appears that there may be additional restrictions in place when running VS Code in the browser (vscode.dev) that prevent the iframe from loading external content due to CSP or CORS policies.

Attached are two screenshots showing the console errors in the developer tools. [Screenshot 1: Console errors with TypeError; Screenshot 2: Network tab showing the CORS issue with `www.wikipedia.org`]

I would appreciate any guidance on how to resolve this issue or if there is an alternative approach to display external content within a webview on vscode.dev.

Thank you for your assistance.

![image](https://github.com/microsoft/vscode/assets/56073559/954414ad-e49e-4d3f-aaa7-876fe9cdaa88)
![image](https://github.com/microsoft/vscode/assets/56073559/96f8b7cf-b81f-423d-8e14-78d75d3f960e)

**Comment by mjbvz** [comment]
Thanks for the detailed error report! This is something that needs to be fixed by the embedded website (wikipedia in this case)

In this case, we require that the embedded page have the `Cross-origin-resource-policy` listed in the error message. I don't think we can fix this on our side
