### ISSUE TITLE
code-snippets autocomplete is broken

### ISSUE THREAD

**Issue by umnovI** [microsoft/vscode#209534]
Type: <b>Bug</b>

1. Add a new snippet to any of the code-snippets for any language
For example:
```json
"test": {
}
```
1. Type `"`, it gets completed to `"|"` (this steps is important)
2. Start typing any of the keywords, for example, "body".
3. Choose autocomplete suggestion

Inserted Autocomplete is an invalid json with `"""`

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|27.86GB (14.35GB free)|
|Process Argv|E:\\cloned-projects\\project-examples\\dioxus\\.docker\\README.md --crash-reporter-id 01bfe09d-0674-44f2-89ca-c8d7b1e31919|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by umnovI** [comment]
![clideo_editor_bcd22b3726e3474aaf9769e263a967a2](https://github.com/microsoft/vscode/assets/30232564/57a1c706-8971-4d9e-83ae-4ae1ee85d57e)

**Comment by jrieken** [comment]
I am using your steps, but I cannot reproduce this. Do you have any other setting that could influence this?

**Comment by RedCMD** [comment]
@jrieken reload VSCode with the file open

**Comment by RedCMD** [comment]
`"[snippets]"` will also need to be added to `"configurationDefaults"`
https://github.com/microsoft/vscode/blob/5410686643f746d444c3379690113a84351ec9e5/extensions/json-language-features/package.json#L130-L143

**Comment by RedCMD** [comment]
partial pr https://github.com/microsoft/vscode/pull/235605

**Comment by jrieken** [comment]
@RedCMD Sorry, I can still not produce. Please help by distilling exact reproducible step and do not jump to any conclusions yet

**Comment by RedCMD** [comment]
https://github.com/user-attachments/assets/c20a43ab-f88c-44d5-a4b0-895ab3b476de

**Comment by jrieken** [comment]
🤷 

https://github.com/user-attachments/assets/40206d19-81fa-4a16-9e44-648df28c6e5c

**Comment by jrieken** [comment]
@aeschli Do you have a clue? This seems to be JSON-schema based completions related but I can't reproduce

**Comment by RedCMD** [comment]
type the double quotes first

**Comment by RedCMD** [comment]
1. make sure `"editor.suggest.insertMode"` is set to default `"insert"`
1. Create `.code-snippets` file with code
```json
{
	"test": {
		""
	}
}
```
2. assign language `snippets`
3. attempt code completion of `"body"` at the `""` position
![image](https://github.com/user-attachments/assets/eb7f43c3-c353-4936-8a83-31bb797e42ab)
4. expect the correct number of valid double quotes
![image](https://github.com/user-attachments/assets/323e9838-6bd2-4029-9d79-f0b9609ada50)

actual:
3 sets of double quotes `"""` are created  🐛

**Comment by jrieken** [comment]
I have updated the original steps, it's important to start with `"|"` before asking for suggestions

@aeschli I can see that JSON gives this completion text and no "overwrite after", which then leads to double quotes 

<img width="1053" alt="Image" src="https://github.com/user-attachments/assets/dace5621-6f29-479b-8919-b24d7a5ffd9d" />

**Comment by aeschli** [comment]
The problem is that for snippets, the default is 'insert' mode. For JSON it is 'replace' mode.

For this example:
```
"test": {
""
}
```
with the cursor between the `""`, the JSON language server produces the following suggestion:
replace: `insertText: "body": "$1"`, range: [1, 0] - [1, 2]
insert: `insertText: "body": "$1"`, range: [1, 0] - [1, 1]

The JSON server produces the correct results, it's just that users don't expect insert mode, they expect replace mode.

**Comment by jrieken** [comment]
> The problem is that for snippets, the default is 'insert' mode. For JSON it is 'replace' mode.

Which is incompatible with VS Code's default. Can't we get alignment here?

**Comment by RedCMD** [comment]
> Which is incompatible with VS Code's default. Can't we get alignment here?

@jrieken https://github.com/microsoft/vscode/issues/209534#issuecomment-2527508338

**Comment by aeschli** [comment]
IMO using insert as default would mean for JSON to no longer return richer completions such as `"value": "property"` when completing inside `""`. The completion would have to be `value` only. The user would then move the cursor over the `"` and type `:` and then complete the value.
That would be quite a change in how JSON editing works and a loss of convenience to the user.
Same would apply to CSS and HTML which also have values as quoted strings
IMO `insert` is not good for languages with quoted strings given that we always auto close strings.

**Comment by jrieken** [comment]
> IMO insert is not good for languages with quoted strings given that we always auto close quotes.

We added replace-ranges quite late to VS Code, how did JSON work the years before that?

**Comment by RedCMD** [comment]
og commit https://github.com/microsoft/vscode/commit/dc31a480024adc121196e9055567bfbb5de08e6d

**Comment by aeschli** [comment]
Code completions started with `insertText`. Shortly after the `range` was added, allowing completions to have full control of what was replaced before and after the cursor as well. That's when JSON/CSS/HTML was mostly written. Only much later, the concepts of `insert` and `replace` mode was added and 'insert' was declared as the default. I already brought it up at the time that this didn't fit well with what we already had with JSON/CSS/HTML and going to a pure 'insert' mode would be a step back for the user experience in JSON/CSS/HTML

**Comment by jrieken** [comment]
> Only much later, the concepts of insert and replace mode was added and 'insert' was declared as the default.

But that's only a user default (because it matches what mostlanguages were doing at the time, and still do). It does not mean each language must implement insert and replace for all completions, you could have left everything as before.

In JSON, with a complex suggestion like `"key": "value"` only offer one variant, for a simple suggestion like `value` offer both, unbiased wrt the user's config.
