### ISSUE TITLE
I use to be able to highlight a word and see copies on my scroll bar they were marked by a grey marker on the scrollbar 

### ISSUE THREAD

**Issue by nbapat43** [Microsoft/vscode#20960]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.4.2|
|debugger-for-ios-web|msjsdiag|0.1.2|

---

Steps to Reproduce:
1.Go to a javascript file (.js file).
1.double click on a word where its highlighted grey
2.on the scroll bar all the matches should show where they are by grey notches.

**Comment by alexandrudima** [comment]
This works fine for me:

![image](https://cloud.githubusercontent.com/assets/5047891/25435119/4dd96b0c-2a8f-11e7-8e9c-7bc67ba9b69e.png)

**Comment by alexandrudima** [comment]
Closing after a number of days without a response
