### ISSUE TITLE
vscode-eslint not fully uninstalled

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#2096]
- install vscode-eslint
- open a workspace with JS files so that the eslint server process is started
- uninstall vscode-eslint from the command palette

-> most of the extension is removed but some folders are left behind (rename .gif -> .zip)
![dbaeumer vscode-eslint-0 10 11 zip](https://cloud.githubusercontent.com/assets/172399/12401581/a90ade8c-be27-11e5-823a-b545cc078951.gif)

As a consquence there is an error on next restart:
```
[C:/Users/egamma/.vscode/extensions/dbaeumer.vscode-eslint-0.10.11]: Cannot read file C:/Users/egamma/.vscode/extensions/dbaeumer.vscode-eslint-0.10.11/package.json: ENOENT: no such file or directory, open 'C:\Users\egamma\.vscode\extensions\dbaeumer.vscode-eslint-0.10.11\package.json'
```

**Comment by joaomoreno** [comment]
We can add a `~/.vscode/extensions/.obsolete` file indicating which extensions should be gone. We shouldn't load an extension listed in there. We should try to delete them at startup.

**Comment by joaomoreno** [comment]
@egamma This took quite some code to get running. It would be great if you could reproduce this and test it properly for verification.

**Comment by egamma** [comment]
@joaomoreno I could reproduce the problem and the tslint wasn't removed completely. After a restart of code the extension got fully uninstalled. 

I've also tried to only 'reload window' but this wasn't sufficient to clean-up the broken extension. Should the clean-up also happen on 'reload window'?

**Comment by joaomoreno** [comment]
No, only on full product restart since other windows might be using the extension.
