### ISSUE TITLE
[bug] VSCode minimap section header display uncompletely on first load

### ISSUE THREAD

**Issue by ScriptBloom** [microsoft/vscode#209603]
Type: Bug

Does this issue occur when all extensions are disabled?: Yes

Yesterday, I noticed the update of VSCode version `1.88.0`, in which I am very interested in the `Minimap section headers` feature, because I often use VSCode to browse my Swift files codes, where large files use `'// MARK: ...'` comments to distinguish code blocks. So I tried this feature and found a bug below:

When the Swift file code is long enough, the first time editor load the file, the section header generated in the minimap is uncomplete, which will only include the section header corresponding to the `'MARK:'` comment visible in the first screen of the editor.

## Expectations:

When opening the file on first load, the minimap displays the complete `'MARK:'` comment corresponding to the section header.

## To reproduce:

- Open the minimap and the section header feature switch (`editor.minimap.showMarkSectionHeaders`);
- Exit and reopen VSCode;
- After VSCode starts, for the first time open a long Swift file containing multiple `'MARK:'` comments (where multiple `'MARK:'` are not displayed in the first screen of the window);
- After the minimap section header is generated, it is found that only the section header corresponding to the `'MARK:'` included in the first screen of the editor(The problem);
- Close the file, reopen the file in the editor, the minimap will update and display multiple section headers(twice I open file, minimap section headers display completely).

## Notes:

- The first picture below shows the problem, my Swift file has two `'MARK:'` comments, but the minimap only generated first section header named `‘Header 1’`; there is no corresponding minimap section header for the `'MARK: - Header 2'` comment that cannot be displayed on the first screen without scrolling in the editor.
- The second picture below shows: when the second `'MARK: Header 2'` comment can be displayed on the first screen without scrolling in the editor, the minimap will generate the corresponding section header correctly.

## Main screenshots of bug:

- picture 1

<div  align="center">
<img src="https://github.com/microsoft/vscode/assets/38654563/352c9ca1-c6b9-4b00-9176-66973fabf30a" alt="vscode_section_header_not_work_when_content_not_in_screen" width="500" height="500" align="center"/>
</div>

- picture 2

<div  align="center">
<img src="https://github.com/microsoft/vscode/assets/38654563/572fbe0c-ca4e-42f7-91e7-97c88b1574c9" alt="vscode_section_header_work_when_in_screen" width="500" height="500" align="center"/>
</div>

## Feature PR:

I have Noticed the corresponding feature(minimap section headers) PR: https://github.com/microsoft/vscode/pull/190759

## VSCode version information:

Version: 1.88.0 (Universal)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:28:18.899Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

## System Info:
<details>
<summary>click to expand</summary>

CPUs | Apple M1 Pro (10 x 24)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_graphite: disabled_off video_decode: enabled video_encode: enabled webgl: enabled webgl2: enabled webgpu: enabled
Load (avg) | 4, 4, 3
Memory (System) | 32.00GB (0.06GB free)
Process Argv | --crash-reporter-id 8c602ea2-89a5-4114-b8e5-8ff63f8c7d18
Screen Reader | yes
VM | 0%

</details>

## VSCode Extension List:
<details>
<summary>click to expand</summary>

Extension | Author (truncated) | Version
-- | -- | --
flutter-snippets | ale | 3.0.0
gitstash | art | 5.2.0
doxdocgen | csc | 1.4.0
dart-code | Dar | 3.86.0
flutter | Dar | 3.86.0
vscode-markdownlint | Dav | 0.54.0
algorithm-mnemonics-vscode | dav | 1.0.3
vscode-eslint | dba | 2.4.4
githistory | don | 0.6.20
gitlens | eam | 14.9.0
prettier-vscode | esb | 10.4.0
filter-line | eve | 2.0.1
git-project-manager | fel | 1.8.2
code-runner | for | 0.12.1
kotlin | fwc | 0.2.34
flatbuffers | gab | 0.1.0
go | gol | 0.41.2
global-config | Gru | 0.0.16
CppSnippets | har | 0.0.15
better-cpp-syntax | jef | 1.17.2
svg | joc | 1.5.3
cmake-language-support-vscode | jos | 0.0.9
jumpprotobuf | ldc | 0.0.3
dart-import | lua | 0.3.1
Kotlin | mat | 1.7.1
vscode-clang | mit | 0.2.4
vscode-docker | ms- | 1.29.0
vscode-dotnet-runtime | ms- | 2.0.3
debugpy | ms- | 2024.4.0
isort | ms- | 2023.10.1
python | ms- | 2024.4.0
vscode-pylance | ms- | 2024.4.1
jupyter | ms- | 2024.3.0
jupyter-keymap | ms- | 1.1.2
jupyter-renderers | ms- | 1.0.17
vscode-jupyter-cell-tags | ms- | 0.1.9
vscode-jupyter-slideshow | ms- | 0.1.6
remote-containers | ms- | 0.354.0
remote-ssh | ms- | 0.110.1
remote-ssh-edit | ms- | 0.86.0
remote-wsl | ms- | 0.88.0
cmake-tools | ms- | 1.17.17
cpptools | ms- | 1.19.9
cpptools-extension-pack | ms- | 1.3.0
hexeditor | ms- | 1.9.14
makefile-tools | ms- | 0.9.10
remote-explorer | ms- | 0.4.3
ios-snippets | orn | 0.0.15
dart-syntax-highlighting-only | osc | 1.0.1
java | red | 1.29.0
rust-analyzer | rus | 0.3.1906
gpthelper | Sil | 0.4.1
swift-lang | ssw | 1.8.1
ayu | tea | 1.0.5
cmake | twx | 0.0.17
vscode-lldb | vad | 1.10.0
intellicode-api-usage-examples | Vis | 0.2.8
vscodeintellicode | Vis | 1.3.1
vscode-java-debug | vsc | 0.57.0
vscode-java-dependency | vsc | 0.23.6
vscode-java-pack | vsc | 0.25.15
vscode-java-test | vsc | 0.41.0
vscode-maven | vsc | 0.44.0
volar | Vue | 2.0.10
markdown-all-in-one | yzh | 3.6.2
material-theme | zhu | 3.17.0
vscode-proto3 | zxh | 0.5.5

</details>

## A/B experiment
<details>
<summary>click to expand</summary>

vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572

</details>

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/pull/209605
