### ISSUE TITLE
Add Cmd+V/Ctrl+V paste support for URLs turning them into Markdown links

### ISSUE THREAD

**Issue by vittorius** [microsoft/vscode#209610]
(I haven't found any existing issues, open or closed, on this topic.)

It would be great to handle the Cmd+V/Ctrl+V on a selected text to auto-create a Markdown hyperlink when inserting a URL, just like the Github web UI does.

**Comment by alexr00** [comment]
To verify:
- Install an extension that provides commenting, such as GitHub Pull Requests.
- Add a comment. In the comment widget editor, past in a url.
- Verify that it pastes as a markdown comment.

**Comment by benibenj** [comment]
Verified assuming that it's not meant to do it automatically, but by using the paste options.

![Code_-_Insiders_ghVBnPOTWy](https://github.com/microsoft/vscode/assets/44439583/566acb41-2b78-40ce-8df0-1718f149b8be)
