### ISSUE TITLE
Coverage feature does not work for Python

### ISSUE THREAD

**Issue by doyled-it** [microsoft/vscode#209684]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.88.0 (Universal)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:28:18.899Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

Steps to Reproduce:

1. Clone a repo (this is the one I'm using):
```shell
git clone https://github.com/janus-llm/janus-llm.git
```
2. Poetry install with python=3.10
```shell
poetry install
```
3. Startup VSCode in this project directory and go to Testing Tab
4. Configure Python Tests
5. `pytest`
6. `janus`

![image](https://github.com/microsoft/vscode/assets/12867253/a4755ac4-8014-473a-a960-5831fda29455)

**Comment by eleanorjboyd** [comment]
Hi! Currently the update to VS Code allows for test coverage compatibility but we have not yet implemented it for Python. Please see this issue were we are discussing how to design the compatibility and give your thoughts if you have any on the design. Thanks!

https://github.com/microsoft/vscode-python/issues/22827
