### ISSUE TITLE
New option for auto-save feature

### ISSUE THREAD

**Issue by BabakAmini** [microsoft/vscode#209667]
I prefer using VS Code's auto-save feature when coding on my remote server. It provides peace of mind since I occasionally experience server connection issues, allowing me to focus on coding rather than saving my work. I also like auto-reloading my project whenever a file changes, but it becomes annoying when I enable auto-save for that project. Is it possible to add an option to auto-save feature so that all changes would be saved automatically but auto-reload done just whenever I use the save shortcut?

**Comment by bpasero** [comment]
How would that work? We are not controlling auto-reload, or maybe I misunderstand the ask?

**Comment by bpasero** [comment]
We are not sending any signal, we save the file to disk. Whatever setup you have that auto-reloads is the one that listens to file changes.

**Comment by bpasero** [comment]
Ah, well we do something like that already as part of the hot exit feature: https://code.visualstudio.com/docs/editor/codebasics#_hot-exit

This allows you to quit VS Code without being forced to save.
