### ISSUE TITLE
nvm can prevent JS debugging when `console: integratedTerminal`

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#209693]
See https://github.com/microsoft/vscode/issues/198550#issuecomment-2040760753

The change that caused this was a standalone fix for a relatively minor bug, so I will back it out for now.

**Comment by rzhao271** [comment]
I'm able to debug a JS file on macOS now with a launch configuration that contains `console: integratedTerminal`

**Comment by claytongulick** [comment]
Just a FYI - I don't use nvm but experienced this issue. The recent update fixed it for me, thanks!!
