### ISSUE TITLE
Vs code debug angular 2 webpackq

### ISSUE THREAD

**Issue by brux88** [Microsoft/vscode#20964]
hello, I am trying to debugging an app created with angular cli from vs code, but it does not work that way?

**Comment by weinand** [comment]
@brux88 please provide details about your setup (VS Code version, platform, node version, launch.json), the exact steps you've tried and what doesn't work.

**Comment by brux88** [comment]
of corse, 
Vs Code : 1.9.1
node : 6.9.5
ng (angular-cli) : @angular/cli: 1.0.0-beta.32.3 [2.7.0]

my launch.json:
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:4200",
            "sourceMaps": true,
            "diagnosticLogging": true,
            "webRoot": "${workspaceRoot}/src",
            "userDataDir": "${workspaceRoot}/.vscode/chrome",
            "sourceMapPathOverrides": {
                "webpack:///C:*":"C:/*"
            }
        },
        {
            "name": "Attach to Chrome, with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "diagnosticLogging": true,
            "webRoot": "${workspaceRoot}/src",
            "sourceMapPathOverrides": {
                "webpack:///C:*":"C:/*"
            }
        }
    ]
}`

i add this string "--remote-debugging-port=9222" in target of chrome.exe ,

The step is:
open vs code, open termina and digit "ng serve" then go on debug and click on "Launch Chrome against localhost, with sourcemaps".

this is my solution:
![2017-02-22_0853](https://cloud.githubusercontent.com/assets/3495339/23202005/63165f0a-f8dc-11e6-9996-d90d259af608.png)


Finally, I wanted to know if it was possible to manage everything from "vs code", ie without have to write ng serve, automatically if you do I debug, the server is started and opens me the solution of chrome

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-chrome-debug#367
