### ISSUE TITLE
Error when starting Remote SSH Code

### ISSUE THREAD

**Issue by jifoxpa** [microsoft/vscode#209600]
Type: <b>Bug</b>

When an unavailable extension is configured in 

"remote.SSH.defaultExtensions": [
     "ms-ceintl.vscode-language-pack-en-gb"
 ]

Then vscode server will fail to start because of an Extension

```
vscode failed to connect to the remote extension host server Failed to connect to the remote extension host server (Error: ExtensionInstallFailed(ExtensionInstallFailed("Extension 'ms-ceintl.vscode-language-pack-en-gb' not found.\nMake sure you use the full extension ID´ including the publisher´ e.g.: ms-dotnettools.csharp\nFailed Installing Extensions: ms-ceintl.vscode-language-pack-en-gb
```

VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 3.10.0-1160.108.1.el7.x86_64
Remote OS version: Linux x64 5.4.0-174-generic
Remote OS version: Linux x64 5.15.0-94-generic
Remote OS version: Linux x64 5.15.0-94-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6354 CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (6.35GB free)|
|Process Argv|--crash-reporter-id fc2df906-66e9-496c-821c-b1a32946d1ec|
|Screen Reader|no|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: scvnetmgmt01|
|OS|Linux x64 3.10.0-1160.108.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz (10 x 2593)|
|Memory (System)|13.54GB (6.97GB free)|
|VM|40%|

|Item|Value|
|---|---|
|Remote|SSH: scvpconf01|
|OS|Linux x64 5.4.0-174-generic|
|CPUs|Intel(R) Xeon(R) Gold 6354 CPU @ 3.00GHz (6 x 2992)|
|Memory (System)|23.44GB (14.37GB free)|
|VM|8%|

|Item|Value|
|---|---|
|Remote|SSH: scvbnetauto01|
|OS|Linux x64 5.15.0-94-generic|
|CPUs|Intel(R) Xeon(R) Gold 6354 CPU @ 3.00GHz (4 x 2992)|
|Memory (System)|15.61GB (9.45GB free)|
|VM|20%|

|Item|Value|
|---|---|
|Remote|SSH: scvbnetauto02|
|OS|Linux x64 5.15.0-94-generic|
|CPUs|Intel(R) Xeon(R) Gold 6354 CPU @ 3.00GHz (4 x 2992)|
|Memory (System)|15.61GB (12.44GB free)|
|VM|20%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
ansible-vault|dho|0.1.3
copilot|Git|1.178.0
copilot-chat|Git|0.14.0
todo-tree|Gru|0.0.226
rainbow-csv|mec|3.11.0
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.4.0
flake8|ms-|2023.10.0
python|ms-|2024.4.0
vscode-pylance|ms-|2024.4.1
autodocstring|njp|0.6.1
jinjahtml|sam|0.20.0
unique-window-colors|stu|1.0.51
graphviz-interactive-preview|tin|0.3.5
numbered-bookmarks|ale|8.4.0
TextFSM-Syntax|and|1.1.0
django-html|bib|1.3.0
django|big|1.0.2
vscode-firefox-debug|fir|2.9.10
vscode-drawio|hed|1.6.6
vscode-edge-devtools|ms-|2.1.5
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.354.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
vscode-speech|ms-|0.8.0
debugger-for-edge|msj|1.0.15
jinja|who|0.0.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572
vstestc:31010171

```

</details>

**Comment by KaparaNewbie** [comment]
Same. Reverting to version 1.87 solved it for me.

**Comment by jifox** [comment]
I edited the settings.json file and removed the extension from list

**Comment by connor4312** [comment]
That extension does not exist: you'll find an error message in your Remote - SSH output saying as much. Please remove the extension or correct its name to make the connection work.
