### ISSUE TITLE
Provider is "undefined" when accessing multidiff editor

### ISSUE THREAD

**Issue by danny-mhlv** [microsoft/vscode#209609]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0 
- OS Version: Ubuntu 22.04.4 LTS

Steps to Reproduce:

1. Bind `multiDiffEditor.openScmDiff` to some key-combination. I'm using `Ctrl` + `Shift` + `G` `M`.
2. Try to apply the shortcut.
3. Get the warning message:
![Screenshot from 2024-04-05 11-29-59](https://github.com/microsoft/vscode/assets/44134636/d0b9824a-896f-4ba6-acee-b229d8fb5857)

**Comment by hediet** [comment]
You have to tell the command which resource group id to open. That is tricky to do by keybinding :/
I think the git extension should provide two commands that call this (rather internal) command with the correct arguments.

**Comment by lszomoru** [comment]
The latest VS Code Insiders release has the following commands that you can define keybindings for:
- git.viewChanges
- git.viewStagedChanges
- git.viewUntrackedChanges

**Comment by danny-mhlv** [comment]
Thank you for your replies and work!
