### ISSUE TITLE
Show Custom Labels in Go to file panel (Ctrl+P)

### ISSUE THREAD

**Issue by jswillard** [microsoft/vscode#209662]
The new custom labels in the editor tabs is great but would it also be possible to show these custom labels when searching for files in the Ctrl+P menu? I am frequently searching for files in a codebase that has many duplicated file names and it would help find the specific one I am looking for.

I'd be happy to look at opening a pr for this if there is interest.

Thanks for your time.

**Comment by benibenj** [comment]
Verification Steps:
1. Create a custom label (`workbench.editor.customLabels.patterns`)
    - For example: item: `**`, value: "/${dirname}"
2. Search for any file in quick open (`ctrl+P`) which matches the pattern specified in step 1. 
    - With the mentioned example every file matches the template
3. The label should be renamed based on the template custom label 
    - With the mentioned example all labels should start with a `/` followed by the name of the folder the file is in
