### ISSUE TITLE
Diff stage and revert button borders

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#209627]
While working on https://github.com/microsoft/vscode/issues/208378, I noticed that we don't really have any button borders anywhere else in our default themes. For consistency, it might be good to remove the borders on theses buttons and let other themes add a border color if they want.

**Comment by hediet** [comment]
Before:

![3OFZIcCheK](https://github.com/microsoft/vscode/assets/2931520/6483db12-97db-4aeb-b245-9e0b53dcd736)

After:

![Code_-_OSS_cCWH6VJcEO](https://github.com/microsoft/vscode/assets/2931520/133aab60-d24d-4b12-9945-0b7ac2a3bf4a)

I'm not sure I like the after more than before, but I agree it is more consistent with the VS Code UI.
