### ISSUE TITLE
Allow emmet and keyboard-shortcuts in the help menu even when being offline

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#20963]
- VSCode Version: 1.10.0 - insider
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Allow emmet and keyboard-shortcuts from the offline help menu, similar to the 'Welcome' option.  Whatever the OS.

**Comment by ramya-rao-a** [comment]
Emmet Expansion is already available in the Edit Menu

![image](https://cloud.githubusercontent.com/assets/16890566/23185565/ab30d8b4-f838-11e6-873f-8709a18df0fc.png)

For rest of the Emmet commands you can click on the "Emmet..." item in the same menu. This will open the command palet with all the Emmet commands pre-filled

There are no shortcuts assigned out of the box for any of the Emmet commands other than expansions. You can assign your own keyboard shortcuts to these commands.
Once you do that, the shortcuts will appear next to the command in the command pallet the next time.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@ramya-rao-a Maybe it was not clear ... it would be in relation to [this page](http://docs.emmet.io/cheat-sheet/), with the link inside the [faq](https://code.visualstudio.com/docs/languages/html#_emmet-snippets) of vscode.

When the [shortcuts](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf) are the ones that come by default ... yes I know we can change, but I particularly prefer to keep the IDE standard until I see the need to change. It would be good for anyone who is starting to use VSCode.

**Comment by ramya-rao-a** [comment]
Oh, so you are saying that you'd like to have a link to the [emmet cheet sheet](http://docs.emmet.io/cheat-sheet/) from the menu?

**Comment by Tekbr** [comment]
My suggestion is:
1- Have the emmet offline available within the VSCode.
2- Make the "Keyboard Shorcuts Reference" option on the Help menu, offline.

Similar to the Release Notes page.

**Comment by ramya-rao-a** [comment]
@bpasero @waderyan This is about having emmet cheatsheet and the keyboard shortcuts reference available offline like the Release Notes. And additionally have menu options to open the same.

Thoughts?

**Comment by bpasero** [comment]
Maybe a crazy idea, but since we can open PDF files inside VS Code, it would probably be possible to open the cheatsheet within Code. However this means we depend on the PDF component and would not be able to take it out later if we wanted to save some MB of download size. I also think the PDF is good for people that want to actually print it. We could detect if the user is offline when clicking on that action and then maybe show the keybindings inside a markdown preview?

**Comment by Tekbr** [comment]
@bpasero  @ramya-rao-a 

I did not think of a PDF.

I thought the same style as the Welcome or Release note page.

Are both made in Markdown, or not?

**Comment by bpasero** [comment]
Yeah, all markdown.

@chrmarti fyi

**Comment by Tekbr** [comment]
@bpasero Like you said `"crazy idea"`. You're right. I'll close this.

An off question, can you answer me:

Note: I think 'Welcome is html'.

File 'Welcome' in VSCode stable: I found the file and it is in html.
File 'Welcome' in VSCode - insider: I did not find the file ..

There was a change of location and the path was not updated.

![capturar](https://cloud.githubusercontent.com/assets/19866231/23265727/514b0706-f9c4-11e6-8d19-4451d544c9fb.PNG)

'Release Notes' could not find the file type.

Is it possible to locate Release Notes in Windows Explorer?

**Comment by bpasero** [comment]
No, I think the release notes are being downloaded from our website.

**Comment by Tekbr** [comment]
What about Welcome?

**Comment by chrmarti** [comment]
I moved the Welcome page from html to a TypeScript file, so we can have it translated the same way we translate most of the UI.

**Comment by Tekbr** [comment]
Thank you all. Sorry for the inconvenience.
