### ISSUE TITLE
Open large file with only one row(40Mb json file) no response

### ISSUE THREAD

**Issue by Jun860** [Microsoft/vscode#20968]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-babel-coloring|dzannotti|0.0.4|
|vetur|octref|0.3.5|

---

I open a json file with only one row.when I process with the data, VScode prompt no response.
But I open the same file with multi-rows , it works normally.

**Comment by alexandrudima** [comment]
@Jun860 Can you please share the file or a very similar file (even generated) that reproduces the problem. What are your settings? Thanks!

**Comment by Jun860** [comment]
[json_file.zip](https://github.com/Microsoft/vscode/files/795330/json_file.zip)

this is the test file, open test_one_row.json will no response,but open test_multi-row.json(with same content) without problem.
