### ISSUE TITLE
Merge editor result could be smarter

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#209629]
In GHPR, we've started using the merge editor to resolve conflicts in PRs. For example:
1. Have branch `main`
2. Create `branchA` from commit `aaa` off of `main`
3. Work happens in both `branchA` and `main`, resulting in a conflict when a PR is create to merge `branchA` in `main`
4. To resolve the conflict, we show the merge editor and set:
- `base`: `aaa`
- `current`: `branchA`
- `incoming`: `main`
- `result`: the file contents at `aaa`

This means that for every change in the file, even ones that would have been automatically merge if there were no conflicts, the user has to accept `current` or `incoming`. This can be very painful for files with lots of changes. 

GHPR doesn't know how to do the diff see which changes are automatically mergable, but VS Code core and the merge editor already know this. It would be very cool if the merge editor would compute these automatic changes to `result`.

**Comment by hediet** [comment]
Solved by including conflict markers in the initial result.
