### ISSUE TITLE
Monokai Dimmed theme: json syntax highlighting colors very different in v1.88.0

### ISSUE THREAD

**Issue by HenryTSZ** [microsoft/vscode#209713]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0 (Universal)
- OS Version: Darwin arm64 23.2.0
Version: 1.88.0 (Universal)

Steps to Reproduce:

now json file color is this:

<img width="906" alt="image" src="https://github.com/microsoft/vscode/assets/55341525/e4600c57-dc3e-4b5f-b243-796427900d23">

it is different with before

because i updated, i can't find the before color

**Comment by aeschli** [comment]
Here is how it looks in 1.87:
![image](https://github.com/microsoft/vscode/assets/6461412/56d6ce9c-b1d6-41a1-8cf7-dbc8545414a2)

**Comment by aeschli** [comment]
Please give more inform about what has changed.

Make sure you have to customised the theme in the settings.

**Comment by HenryTSZ** [comment]
> Here is how it looks in 1.87: ![image](https://private-user-images.githubusercontent.com/6461412/320502141-56d6ce9c-b1d6-41a1-8cf7-dbc8545414a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTc5ODksIm5iZiI6MTcxMzA5NzY4OSwicGF0aCI6Ii82NDYxNDEyLzMyMDUwMjE0MS01NmQ2Y2U5Yy1iMWQ2LTQxYTEtOGNmNy1kYmM4NTQ1NDE0YTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTIyODA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjhiOTVlMmQyNmIzYjFjNDhmNDAxM2VlYWM1MzQ5NTQ1NWEwMjE2Y2ZhZGI2ZDBhOTcyN2IzYTMyNGYxMjM4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DH79iJk87iTzvWu2dydB_IBMvI6o6TXr2k5LWn6b9Gs)

Can you check the colors of v1.86.0?

Perhaps it's a similar issue to this one: #204509

**Comment by HenryTSZ** [comment]
> Please give more inform about what has changed.
> 
> Make sure you have to customised the theme in the settings.

<img width="517" alt="image" src="https://github.com/microsoft/vscode/assets/55341525/9bc67048-bbcc-4a3d-b7c0-d8afb6986436">

**Comment by HenryTSZ** [comment]
> Please give more information about what has changed. The colors look the same to me.

Sorry, I made a mistake. There is also an issue with v1.86.0. Please take a look at v1.85.2

**Comment by aeschli** [comment]
Please provide a screenshot of the version where it worked.

**Comment by HenryTSZ** [comment]
> Please provide a screenshot of the version where it worked.

<img width="668" alt="image" src="https://github.com/microsoft/vscode/assets/55341525/3c862525-dea8-40cc-b219-8f53cab9da2e">

Version: 1.85.2
