### ISSUE TITLE
After upgrading zsh, the vscode terminal is not functioning properly

### ISSUE THREAD

**Issue by IamJasonBoy** [microsoft/vscode#209751]
After upgrading zsh, the vscode terminal is not functioning properly

![image](https://github.com/microsoft/vscode/assets/131987857/8beb9d85-3471-4de8-8ed4-06f0351e08dd)

Switching zsh in the vscode terminal will cause the file to crash. How to solve this problem

**Comment by meganrogge** [comment]
See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
