### ISSUE TITLE
Search for newline character (\n) in regex mode

### ISSUE THREAD

**Issue by turabaq** [Microsoft/vscode#2097]
Currently vscode supports replacing any text with the \n, \r or \t characters, but it still cannot search for \n. Please add this functionality soon.

**Comment by alexandrudima** [comment]
Let's track this in #313

**Comment by dahngeek** [comment]
It seems that it still doesn't work in Search and Replace mode(Shift+Ctrl+F).. But it does work only in search mode (Ctrl+F)

On Search only mode:
![code_2017-02-21_10-16-18](https://cloud.githubusercontent.com/assets/1181865/23173510/fd64a2ec-f81e-11e6-9559-ae6a73b76c9d.png)

On Search and Replace, it selects the whole line.
![code_2017-02-21_10-17-13](https://cloud.githubusercontent.com/assets/1181865/23173514/01a7fe3a-f81f-11e6-9f90-518d3b1cbb7f.png)

**Comment by alexandrudima** [comment]
@dahngeek Please create a separate issue, the "find in files" vs. "find in file" have separate implementations.
