### ISSUE TITLE
Run debugger script with arguements

### ISSUE THREAD

**Issue by trymeouteh** [microsoft/vscode#209736]
Another play button and hotkey next to the play button in the debugger to debug the active script but pass arguments before running the script.

Example:

1. User clicks Starts Debugging With Arguments button or presses hotkey to  Starts Debugging With Arguments
2. A prompt appears were users enters in the arguments to pass
3. User presses Enter to start debugging

**Comment by roblourens** [comment]
You probably want a launch.json https://code.visualstudio.com/docs/editor/debugging#_launch-configurations
