### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by xjh6158118** [Microsoft/vscode#20974]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vue-snippets|hollowtree|0.1.0|
|vue|liuji-jim|0.1.5|
|vue|seanwash|0.4.2|

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
some comment

**Comment by jrieken** [comment]
@xjh6158118 If you want us spent time improving VS Code please file precise issues with steps to reproduce such that we don't have to fish for them. We will reopen this issue as soon as you clarify 'some problem'
