### ISSUE TITLE
A bug about the "Show Code Actions" from clangd

### ISSUE THREAD

**Issue by BrikeX** [microsoft/vscode#209762]
Type: <b>Bug</b>

A blue lightbulb appears when clangd detects an issue and a preferred quick fix is available. But the blue bulb won't go away after the issue is fixed. And a contributor of Clangd said "
I can't reproduce this, but based on the symptoms it seems more likely to be an issue with the editor (vscode) itself rather than the vscode-clangd plugin.
".

System information
Clangd version : 17.0.3
clangd extension version: 0.1.28
Operating system: Linux Mint 21.3
VS Code: March 2024 (version 1.88)

VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:25:57.039Z)
OS version: Linux x64 5.15.0-91-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-14700HX (28 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|15.39GB (12.21GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
easy-highlight|Bra|1.2.0
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.54.0
githistory|don|0.6.20
gitlens|eam|14.9.0
LogFileHighlighter|emi|2.18.0
auto-rename-tag|for|0.1.10
shell-format|fox|7.2.5
latex-workshop|Jam|9.19.2
vsc-python-indent|Kev|1.18.0
vscode-leetcode|Lee|0.18.1
vscode-clangd|llv|0.1.28
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.0
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.4.0
python|ms-|2024.4.0
vscode-pylance|ms-|2024.4.1
remote-containers|ms-|0.354.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
copy-file-name|nem|1.2.0
ltex|neo|13.1.1
autodocstring|njp|0.6.1
vscode-yaml|red|1.14.0
shellman|Rem|5.7.0
shellcheck|tim|0.37.0
cmake|twx|0.0.17
errorlens|use|3.16.0
markdown-all-in-one|yzh|3.6.2
vscode-proto3|zxh|0.5.5

</details>

**Comment by BrikeX** [comment]
![Screenshot from 2024-04-07 01-32-20](https://github.com/microsoft/vscode/assets/42525829/8daeda07-daf4-4328-8894-b574bf625e8e)
![Screenshot from 2024-04-07 01-32-33](https://github.com/microsoft/vscode/assets/42525829/d296ab69-6b63-4a0b-a426-8bb92a859b9e)

**Comment by justschen** [comment]
@BrikeX when clicking on that blue lightbulb after performing the `remove` code action, does an additional menu come up?

**Comment by BrikeX** [comment]
> @BrikeX when clicking on that blue lightbulb after performing the `remove` code action, does an additional menu come up?

Yes and it looks like it can keep deleting lines.

**Comment by BrikeX** [comment]
https://github.com/clangd/vscode-clangd/issues/614#issuecomment-2085416482, @justschen It looks like someone else has encountered the same problem.
