### ISSUE TITLE
Debugging python fails when using git bash as vscode terminal shell

### ISSUE THREAD

**Issue by julie777** [microsoft/vscode#209776]
Does this issue occur when all extensions are disabled?: Yes/No
I don't know because I need the Python debug extension to debug python programs.

- VS Code Version: 1.88.0
- OS Version: Windows 10 19045.4170

Steps to Reproduce:

1. set git bash as the shell for the interactive terminal
2. debug a python file in a virtual environment

Starting debugging fails because all path separators have been converted to '\'.
```
$  c:\Users\julie\home\.venvs\budget\Scripts\python.exe c:\Users\julie\.vscode\extensions\ms-python.debugpy-2024.5.109610112-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher 54257 --
...
bash: c:Usersjuliehome.venvsbudgetScriptspython.exe: command not found
```

This has been reported, fixed and unfixed. However, it is a **blocking issue** for those of us who use bash as our shell.

I understand the reasoning about using the system separator for paths, but in this case it does not work.

Forward slash works with Windows file system APIs.
Forward slash works as a path separator in powershell.
Forward slash is required as a path separator in bash.
Forward slash works as a path separator in Python for all operating systems.

I think that using the proper separator for the shell in the interactive terminal is the correct solution.

I would be satisfied with a work-around of being able to set the predifined variable `${pathSeparator}` in my vscode settings.

If the predefined variables are set and stored in some file during vscode installation then I would like to know which file so that I can change it.

**Comment by roblourens** [comment]
Please file this on the Python debug extension, thank
