### ISSUE TITLE
Language Support for Java(TM) by Red Hat

### ISSUE THREAD

**Issue by dev4jcoder** [Microsoft/vscode#20972]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Scala|itryapitsin|0.1.7|
|java|redhat|0.0.10|
|jenkinsfile-support|secanis|0.1.0|
|python|tht13|0.2.3|

---

Steps to Reproduce:
when i switch on java extension (Language Support for Java(TM) by Red Hat)
1. switch on java extension (Language Support for Java(TM) by Red Hat)
2. very big CPU leak on my PC (Windows 7 x64, Intel Dual Core P7350, 4 Gb RAM)

**Comment by mjbvz** [comment]
If this perf issue appears specific to the Java extension, please try opening an issue against that extension so that they can investigate: https://github.com/gorkem/vscode-java

Thanks
