### ISSUE TITLE
(ctrl + p) can access to any location we need something like it to create any location as well.

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#20973]
Add shortcut on the keyboard to show input box like (ctrl + p) to type location to create any file with any path.

We can make the life easier with this feature. because (ctrl + p) can access to any location we need something like it to create any location as well.

And we can add inside the box auto complete by {TAB key} for exists location to create files to exists directories fast as well.

Thanks for hard work any way.

![aa](https://cloud.githubusercontent.com/assets/17777237/23152801/22d7055e-f80d-11e6-93c7-d3c75cfb7a37.JPG)

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by pixieaka** [comment]
Can you give me issue ID

**Comment by bpasero** [comment]
Ideally users would spend the time to search for issues, but here you go: https://github.com/Microsoft/vscode/issues/12893
