### ISSUE TITLE
When the window is not in focus, I need to click twice to open a file.

### ISSUE THREAD

**Issue by zhanxiaoge** [microsoft/vscode#209741]
Does this issue occur when all extensions are disabled?: Yes

VS Code Version: 1.88.0
OS Version: Windows 10

When the window is not in focus, I need to click twice to open a file.

This issue started occurring in version 1.87 and still persists in 1.88.

I upgraded from version 1.86 to 1.87.

Here is a video demonstrating the issue:
https://github.com/microsoft/vscode/assets/19665552/05a889bd-2a9f-4532-b659-174c0bc5fedf

Thanks @lramos15 for fixing https://github.com/microsoft/vscode/issues/206585, but it didn't resolve my issue.

**Comment by bpasero** [comment]
I am not sure if this fix has made it into stable, so you might need to use insiders for now:  You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by zhanxiaoge** [comment]
> I am not sure if this fix has made it into stable, so you might need to use insiders for now: You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Thank you very much. The 1.89 insider's version has fixed this issue. When will it be released to the stable version?

**Comment by bpasero** [comment]
First week of May.
