### ISSUE TITLE
Scrollbar options menu on right click hidden by z-index of the comparing file

### ISSUE THREAD

**Issue by RicardoGEsteves** [microsoft/vscode#209705]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: [1.88.0](https://github.com/microsoft/vscode/tree/1.88.0)
- OS Version: windows 11

Steps to Reproduce:

1. Open a file
2. Right click on scrollbar
3. you get the bug, the menu is hidden/overlapped from the right window

You can check it out here in this images:

> ![Screenshot 2024-04-06 050633](https://github.com/microsoft/vscode/assets/30535937/10bf9c84-99a0-4420-b2fa-9f74f6b1e7cf)
###
> ![Screenshot 2024-04-06 050810](https://github.com/microsoft/vscode/assets/30535937/1f66c32c-9126-48b2-bf5d-046b2fce5110)
###
> ![Screenshot 2024-04-06 050929](https://github.com/microsoft/vscode/assets/30535937/6ae90244-ff19-44da-835f-00db8c64434d)

**Comment by rzhao271** [comment]
@RicardoGEsteves are you still seeing the issue? It looks like you have a diff editor open, but I'm unable to reproduce the issue when I try it myself.

**Comment by RicardoGEsteves** [comment]
> [@RicardoGEsteves](https://github.com/RicardoGEsteves) are you still seeing the issue? It looks like you have a diff editor open, but I'm unable to reproduce the issue when I try it myself.

Hello @rzhao271, It doesn't happen anymore. That happened just when you open a diff file.
