### ISSUE TITLE
high cpu use

### ISSUE THREAD

**Issue by lwdgit** [Microsoft/vscode#20975]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-clock|Compulim|0.0.1|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|beautify|HookyQR|0.8.4|
|output-colorizer|IBM|0.0.10|
|vscode-docker|PeterJausovec|0.0.12|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.13.2|
|amvim|auiworks|1.20.2|
|npm-intellisense|christian-kohler|1.2.1|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.6|
|githistory|donjayamanne|0.1.5|
|tslint|eg2|0.8.1|
|auto-rename-tag|formulahendry|0.0.11|
|code-runner|formulahendry|0.6.10|
|terminal|formulahendry|0.0.7|
|docthis|joelday|0.3.11|
|language-polymer|jonwolfe|0.7.10|
|vscode-colorize|kamikillerto|0.3.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|ftp-sync|lukasz-wronski|0.3.2|
|vscode-scss|mrmlnc|0.6.1|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|syncing|nonoroazoro|1.2.9|
|pomodoro-code|odonno|0.2.1|
|sass-indented|robinbentley|1.3.0|
|velocity|sodatea|0.0.3|
|vim|vscodevim|0.5.3|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|
|local-history|xyz|1.1.0|

---

Steps to Reproduce:

1. do nothing

**Comment by jrieken** [comment]
please provide more information that allows us to understand and produce this issue
