### ISSUE TITLE
Inline chat sessions show up in chat history

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#209725]
- Use inline chat
- Reload window
- Click the History button in the chat panel
- Those inline chat sessions show up in the history list

**Comment by roblourens** [comment]
If the fix for this is simple, I might do this as a candidate, because it's going to junk up everyone's history list quite a bit

**Comment by roblourens** [comment]
Not exactly sure what to do, since ChatService doesn't track the location at all right now, so nothing distinguishes them. Should `ChatModel` have a location? Or should there by different `_sessionModels` maps by location?

**Comment by jrieken** [comment]
> Should ChatModel have a location?

Yeah, let's have it. I wasn't a fan of it because conversations can/could roam between the locations but we could phrase it like that, e.g chat model has the initial location at which the conversation started

**Comment by deepak1556** [comment]
Closing for verification.

**Comment by deepak1556** [comment]
If the history already had inline chat sessions before this fix it would still show up, only new saves are excluded. I guess that is intended ?

**Comment by roblourens** [comment]
Yeah, there's no way to fix that
