### ISSUE TITLE
VSCode doesn't seem to override html.format.extraLiners config prop

### ISSUE THREAD

**Issue by mlewand** [Microsoft/vscode#20977]
I couldn't reopen #4261, so here it is as a new issue:

It looks like there's a regression, as if VSCode would no longer respect `html.format.extraLiners` config.

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|jslint|ajhyndman|1.2.1|
|Bookmarks|alefragnani|0.11.0|
|ck4-test-mate|mlewand|0.0.1|
|jsrefactor|cmstead|0.5.3|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.6|
|copy-relative-path|enochc|0.1.1|
|beautify|HookyQR|0.8.4|
|copy-markdown-as-html|jerriepelser|1.0.0|
|docthis|joelday|0.4.0|
|copy-github-url|mattlott|0.1.0|
|vscode-exec-node|miramac|0.2.1|
|ecdc|mitchdenny|0.10.3|
|select-part-of-word|mlewand|0.2.0|
|debugger-for-chrome|msjsdiag|2.5.3|
|promise-snippets|progre|0.2.3|
|vscode-open|sandcastle|0.1.0|
|code-settings-sync|Shan|2.4.4|
|code-spell-checker|streetsidesoftware|0.14.6|
|selectline-statusbar|tomoki1207|0.0.1|
|vscode-react-native|vsmobile|0.3.1|
|change-case|wmaurer|1.0.0|
|JasmineSnippets|xabikos|0.2.1|
|JavaScriptSnippets|xabikos|1.4.0|

---

Steps to Reproduce:

1. Set your `"html.format.extraLiners"` to `"head,body,div,p,/html"`.
1. Open new tab with `ctrl+n`.
1. Switch tab language to HTML.
1. Set a following markup:
	```html
	<!DOCTYPE html>
	<html lang="en">
		<head>
			<title></title>
			<meta charset="UTF-8">
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<link href="css/style.css" rel="stylesheet">
		</head>
		<body>
			<div>foo</div>
			<div>foo</div>
			<div>foo</div>
			<p>foo</p>
			<p>foo</p>
			<p>foo</p>
		</body>
	</html>
	```
1. Press `ctrl+shift+f` to execute `Format Document` command.

## Expected

Lines are inserted also after `p` and `div` elements.

```html
<!DOCTYPE html>
<html lang="en">

	<head>
		<title></title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="css/style.css" rel="stylesheet">
	</head>

	<body>
		<div>foo</div>

		<div>foo</div>

		<div>foo</div>

		<p>foo</p>

		<p>foo</p>

		<p>foo</p>

		</body>

</html>

```

## Actual

Missing new lines after `div` or `p`.

```html
<!DOCTYPE html>
<html lang="en">

	<head>
		<title></title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="css/style.css" rel="stylesheet">
	</head>

	<body>
		<div>foo</div>
		<div>foo</div>
		<div>foo</div>
		<p>foo</p>
		<p>foo</p>
		<p>foo</p>
	</body>

</html>

```

**Comment by aeschli** [comment]
It looks like you have extensions installed that does the formatting: https://github.com/HookyQR/VSCodeBeautify.

Please file the issue there.

**Comment by mlewand** [comment]
Oh that's embarrassing, I forgot I even installed it. 😆 Thanks!
