### ISSUE TITLE
Missing optional typing for monaco.languages.CompletionList : range

### ISSUE THREAD

**Issue by Fabioni** [microsoft/vscode#209888]
Hey, the typings for property `range` in `monaco.languages.CompletionList` are wrong. The `range` property should be optional so 
```js
range?: IRange | CompletionItemRanges;
``` 

instead of 
```js
range: IRange | CompletionItemRanges;
``` 

The doc string clearly sayes "defaults to" and it also works exactly like stated when omitting the property.

https://github.com/microsoft/vscode/blob/18c74e3c9d6485afb387f7d6e2b88607ea2b2331/src/vs/monaco.d.ts#L6967-L6976

**Comment by jrieken** [comment]
The `range` property is required, the doc needs to be updated

**Comment by Fabioni** [comment]
I'm using it without range property and it does exactly what the doc say 🫣
