### ISSUE TITLE
Explore indentation issues with the indentation test tool

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#209863]
This issue has been created to track indentation issues that have been found through the usage of the indentation test tool. The indentation test tool applies the reindent lines operation on consecutive pairs of lines on well indented/formatted code, and finds the cases when the suggested indentation differs from the existing indentation. This tool can be run on large repos in order to quickly find cases when the indentation is incorrect.

**Comment by aiday-mar** [comment]
The indentation test tool is introduced in the following PR. It takes in a directory as input, runs over all the TS files (for example), applies the reindentation and writes back the files. Since the files are already properly indented/formatted, edits proposed the reindentation operation correspond presumably to incorrect indentation edits. 

This comment will be used to record the findings from running the tool on different repos. 

**Repo: VS Code**

-

**Comment by aiday-mar** [comment]
After some analysis it appears that the `reindent lines` command does not respect certain onEnter rules. Consider the following case, the `reindent lines` command returns the code inside of the if statement on the same level as the if statement itself, but on pressing Enter after the curly open brace, we get the correct indentation:

![Screenshot 2024-04-09 at 12 05 28](https://github.com/microsoft/vscode/assets/61460952/c989b3f1-7d16-4be7-9bd1-bcf069b2ce7e)

**Comment by aiday-mar** [comment]
More specifically in relation to the comment above, a new tool will be developed, the `indentation onEnter test tool` which will test that the `onEnter` rules work correctly independently of the general indentation.

**Comment by aiday-mar** [comment]
This issue was opened for the purpose of exploration. I will close this issue.

**Comment by heartacker** [comment]
哈哈
