### ISSUE TITLE
Test: Ability to select and start a launch using keyboard

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#20982]
- [x] Any OS @aeschli 
- [x] Any OS @ramya-rao-a 

Complexity: 1

Refs: #16613
We have introduced an ability to select and launch debug configuration through the command palette.

Verify:
- Open command palette (Ctrl+E) and type: `debug ` with space at the end. The list of all debug configurations listed in launch.json should appear. 
- Open command palette and type `>Debug: Select and Start Debugging`, option should appear, upon clicking should be presented with a list of all launch configs.
- Correct debug configuration started upon selection.
- Correct debug configuration is selected in the drop-down menu of debug view upon config running (Ref #20985).

**Comment by jrieken** [comment]
@michelkaporin fyi - please milestone and testplan-item label

**Comment by michelkaporin** [comment]
@jrieken I don't have permissions for this yet, unfortunately. Thanks for the notice anyway!

**Comment by jrieken** [comment]
doh. didn't know that... hope that changes soon

**Comment by MartinSGill** [comment]
I keep getting confused between "task" and "launch" configurations, that is I try to use the command pallet to start a debug "task" and wonder why there's nothing there. 

In my mental model I see both as doing the same thing: running something. One is interactive (i.e. debug) while the other isn't.

Might this be an opportunity to merge/unify these somehow under a single keyword/alias? 

e,g.

```
> Run: "Attach to VS Code" (debug)
> Run: "watch" (task)
```

**Comment by michelkaporin** [comment]
@MartinSGill Thank you for your comment. Task and debug concepts are different in VS Code. The first one is used to automate tasks like building, packaging, testing or deploying, whereas the other one configures the way you want to debug your program. Merging those two concepts into one would be wrong from simple software design perspective, and would lead to those concepts collision, as essentially they target two different purposes.

Please see the links below for further reference.
https://code.visualstudio.com/Docs/editor/debugging and 
https://code.visualstudio.com/Docs/editor/tasks

**Comment by aeschli** [comment]
Verified on Linux
Version 1.10.0-insider
Commit 64cccfc0cf397c13f3349927db12656f3db9336d
Date 2017-02-23T09:13:27.511Z

**Comment by ramya-rao-a** [comment]
Verified on Mac
Version 1.10.0-insider
Commit 64cccfc0cf397c13f3349927db12656f3db9336d
Date 2017-02-23T09:13:27.511Z
