### ISSUE TITLE
File Icon Themes require baked-in padding

### ISSUE THREAD

**Issue by dpetroff** [microsoft/vscode#209860]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0
- OS Version: OS: Ubuntu 22.04.4 LTS

Steps to Reproduce:

1. Use a font that does not bake padding into the glyphs to create a file icon theme:
  ```
  {
    "fonts": [
      {
        "id": "fontawesome",
        "src": [
          {
            "format": "woff2",
            "path": "./fontawesome-webfont.woff2"
          }
        ]
      }
    ],
    "iconDefinitions": {
      "gavel-file": {
        "fontId": "fontawesome",
        "fontCharacter": "\\F0E3"
      }
    },
    "fileExtensions": {
      "gavel": "gavel-file"
    }
  }
  ```
2. The icons are slammed into the twisty in the Explorer view and offset to the left in the editor tab and breadcrumbs:
![image](https://github.com/microsoft/vscode/assets/1384881/19958aea-3fdf-4910-b90a-978098f62449)
3. Compare this with the default icons which come with baked-in padding:
![image](https://github.com/microsoft/vscode/assets/1384881/d700b78c-d056-49c3-87ce-718e01bbc0ce)

It should not be necessary to bake the padding into the icon glyphs. This is not an issue when the same icon is used from a custom codicon in a `TreeView` by adding an item with `iconPath: new ThemeIcon("gavel-file")`:
```
"icons": {
  "gavel-file": {
    "description": "Gavel File Icon",
    "default": {
      "fontPath": "./fontawesome-webfont.woff2",
      "fontCharacter": "\\F0E3"
    }
  }
}
```
The logic used here produces a much more consistent icon so perhaps it should be reused in other parts of the product like the Explorer view and the editor tab and breadcrumbs: ![image](https://github.com/microsoft/vscode/assets/1384881/b227c172-1701-4692-ab74-ef4859e8b943)

**Comment by aeschli** [comment]
Sorry, we're not going to make any changes in the icon sizing / positions. This is how it grew historically.

**Comment by aeschli** [comment]
Of course everyone is welcome to investigate here and come up with a backward compatible solution. The solution needs to be well tested (all platforms, existing icon and product theme and extensions that contribute icons and language icons).
Also, I'd need some commitment to help managing issues that get reported in that area, to figure out if the change has caused any regressions.
