### ISSUE TITLE
Git Changes/Diff Editor broken rendering.

### ISSUE THREAD

**Issue by ArmandBurger** [microsoft/vscode#209820]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0 (user setup)
```text
Version: 1.88.0 (user setup)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:26:18.741Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
```

- OS Version: Windows 11 Home 23H2
```text
Edition:	Windows 11 Home
Version:	23H2
OS build:	22631.3296
Experience:	Windows Feature Experience Pack 1000.22687.1000.0
```

Steps to Reproduce:

1. Open git project `code --disable-extensions .` or `code .`
2. Edit tracked file.
3. Open *Source Control* on Primary Side Bar.
4. Open file with changes in Git Changes/Diff Editor.
5. Select what I want to stage and Left Click to open menu to access *Stage Selected Ranges* menu item.
6. Some elements behind context menu are being rendered in front of the context menu.
7. See example below.
> This rendering issue only occurs in the Git Changes/Diff Editor

![image](https://github.com/microsoft/vscode/assets/22417562/7112e6de-d385-4ec6-8450-43a0b6e57b5b)

## Side Note (Might be related to this issue)
When staging selected ranges for commit, the UI sometimes does not update, or sometimes only updates after ~10 seconds, to only show the unstaged ranges (red & green highlights) as it did previously. I have to unfocus and refocus the window (click outside and back inside the vscode window) to force vscode to correctly show the unstaged changes.

**Comment by lszomoru** [comment]
@hediet, could you please take a look at this one? Thanks!
