### ISSUE TITLE
TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#20989]
* open ts file
* trigger IntelliSense
* select an item with the mouse
* type space, trigger IntelliSense again
* select an item with the mouse
* 💥 the list widget explodes

```
index.js:31 [uncaught exception]: TypeError: Cannot read property 'element' of undefinedonError @ index.js:31(anonymous function) @ index.js:100emitOne @ events.js:96emit @ events.js:188window.onerror @ init.js:120
index.js:34 TypeError: Cannot read property 'element' of undefined
    at ListView.element (file:////Users/jrieken/Code/vscode/out/vs/base/browser/ui/list/listView.js:96:37)
    at file:////Users/jrieken/Code/vscode/out/vs/base/browser/ui/list/listWidget.js:366:91
    at Array.forEach (native)
    at file:////Users/jrieken/Code/vscode/out/vs/base/browser/ui/list/listWidget.js:366:25
    at EventBufferer.bufferEvents (file:////Users/jrieken/Code/vscode/out/vs/base/common/event.js:338:13)
    at List.setFocus (file:////Users/jrieken/Code/vscode/out/vs/base/browser/ui/list/listWidget.js:364:32)
    at MouseController.onPointer (file:////Users/jrieken/Code/vscode/out/vs/base/browser/ui/list/listWidget.js:198:23)
    at file:////Users/jrieken/Code/vscode/out/vs/base/browser/ui/list/listWidget.js:187:89
    at ListView.fireScopedEvent (file:////Users/jrieken/Code/vscode/out/vs/base/browser/ui/list/listView.js:187:13)
    at HTMLDivElement.handler (file:////Users/jrieken/Code/vscode/out/vs/base/browser/ui/list/listView.js:174:55)
```

**Comment by jrieken** [comment]
![feb-21-2017 14-45-18](https://cloud.githubusercontent.com/assets/1794099/23167359/6636327a-f844-11e6-9883-685c9d6ee4de.gif)

**Comment by jrieken** [comment]
Let me know if this is suggest using the list widget wrong.

**Comment by jrieken** [comment]
Oh, and after that the suggest widget is totally broken. Keep throwing the same error until reload

**Comment by joaomoreno** [comment]
Needs these settings:

```
	"files.autoSave": "onFocusChange",
	"files.trimTrailingWhitespace": true
```

**Comment by joaomoreno** [comment]
Reverted.

**Comment by jrieken** [comment]
@bpasero The root cause for this is that `"files.autoSave": "onFocusChange"` saves to early, namely when the cursor loses focus, not when the editor loses focus. That also repos with other things like <kbd>Cmd+F</kbd>. In this particular issue the cursor loses focus when an element is clicked, triggers trim tailing whitespace, cancelling suggest. Now the exploding list widget just covers the real mess which is that you cannot insert a suggestion via click in the presence of certain settings. So unless I miss something instead of `onDidBlurEditorText` the `onDidBlurEditor`-event should be used.

**Comment by jrieken** [comment]
> An event emitted when the text inside this editor or an editor widget lost focus.

Reading the API doc actually not sure anymore. @alexandrudima does above mean there is no editor blur event which is basically 'this editor ~~or~~*and* an editor widget lost'

**Comment by bpasero** [comment]
@jrieken @alexandrudima I once had used onDidBlurEditorText and onDidBlurEditor for auto save and got bugs that under some situations auto save was not triggered (including yourself). So I reverted that back to my solution because I did not want and do not plan to break auto save like that. I am not sure why the event seems to sometimes not fire...

**Comment by alexandrudima** [comment]
@bpasero This is the first I hear about the blur event not firing. That would mean the cursor would still be blinking... even though focus is somewhere else. If you have a repro please let me know.

**Comment by jrieken** [comment]
Unsure how #17729 is related to that but I think if there is an issue blur not being fire that should be fixed. Today, the behaviour is pretty bad because all those save participants (format, trim whitespace, apply quick fix) kick in as soon as the cursor blurs, e.g when searching inside the editor

**Comment by bpasero** [comment]
Yeah I agree. I can either bring back to use the editor events (which I like provided the work reliably) or add a timeout to my blur listener to avoid running save during the event bubbling phase.

**Comment by jrieken** [comment]
The timeout won't work for things like Search, F8 error navigation or any other peek view. We should go back to the before event and understand why it doesn't work at times

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/issues/21273
