### ISSUE TITLE
typeScript wrong

### ISSUE THREAD

**Issue by xingyibiao** [Microsoft/vscode#20987]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|path-intellisense|christian-kohler|1.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.0.33|
|auto-rename-tag|formulahendry|0.0.11|
|vue-snippets|hollowtree|0.1.0|
|beautify|HookyQR|0.8.0|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.2.0|
|guides|spywhere|0.6.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please provide some information about the issue you are seeing
