### ISSUE TITLE
Vscode's Auto Import not working after latest update

### ISSUE THREAD

**Issue by IkramHussainSiyam** [microsoft/vscode#209808]
Does this issue occur when all extensions are disabled?: Yes ✅

- VS Code Version: 1.88.0
- OS Version: Windows 11

After vscode's latest update auto import was not working, at first I thought it was some kind of typescript server error, so I restarted the ts server many times. It didn't help. So I uninstalled vscode completely and reinstalled it, but still, It wasn't working and also it isn't working.

**Comment by mjbvz** [comment]
Duplicate https://github.com/microsoft/TypeScript/issues/58113
