### ISSUE TITLE
VsCode is suddenly not available 

### ISSUE THREAD

**Issue by Cozmeh** [microsoft/vscode#209831]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Mosty the latest version (i don't remember)
- OS Version: Windows 10

Steps to Reproduce:

1. Yesterday  i was working on a project , finished working on it , closed vscode 
2. Today - Opened my laptop , tried to open the project , didn't open , searched for vscode and suddenly its gone!

**Comment by andreamah** [comment]
This might be a machine issue. Perhaps try re-installing, and if it happens again, you can re-file the issue. It's hard to debug unless we can reproduce the issue.

**Comment by Cozmeh** [comment]
> This might be a machine issue. Perhaps try re-installing, and if it happens again, you can re-file the issue. It's hard to debug unless we can reproduce the issue.

Yeah, i did re-install it , all the history is intact!
but why does it happen that way ?  what could be the reason ?

**Comment by andreamah** [comment]
I'm not sure. Although we can explore this more if this happens repeatedly, as there may be reproducible steps.
