### ISSUE TITLE
Terminal does not recognize the line patterns on hover

### ISSUE THREAD

**Issue by abhijit-chikane** [microsoft/vscode#209825]
On the full terminal the url pattern recognition works fine
but in split screen it doesn't 

If I click on the line below the file link it should navigate me to the 46 line no of that file

![image](https://github.com/microsoft/vscode/assets/50770619/9e4a9d56-af3d-4c0a-8b56-a4582166319c)

but in actual it open's this quick panel
![image](https://github.com/microsoft/vscode/assets/50770619/7da3f870-7719-4ca5-9c1a-a7d899b91601)

if the same is open in full terminal it does recognizes the pattern correctly and navigates me to the respective line
![image](https://github.com/microsoft/vscode/assets/50770619/9e365bd9-2e28-424a-a0ac-04459351a89a)

cc //@Tyriar 

Version: 1.89.0-insider (user setup)
Commit: d6eba9b861e3ab7d1935cff61c3943e319f5c830
Date: 2024-04-05T05:52:23.778Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by Tyriar** [comment]
This is a feature I added recently:

![Image](https://github.com/user-attachments/assets/a4ed3301-f54b-45cf-85f2-b46826cb4799)

Currently supporting ripgrep, eslint and git diff formats:

https://github.com/microsoft/vscode/blob/a5539aee23533a8083819cb0b4277b05e1d6525a/src/vs/workbench/contrib/terminalContrib/links/browser/terminalMultiLineLinkDetector.ts#L28-L44

**Comment by abhijit-chikane** [comment]
Today itself I observed this
