### ISSUE TITLE
February Endgame

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#20981]
## Endgame Schedule
- *February, 2/21* Code freeze for the endgame
- *February, 2/28* Endgame done

#### Tuesday, February 21
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms
- [x] All test items contain sufficiently comprehensive test descriptions by 6pm PT

#### Wednesday, February 22
- [x] Test build starts at 7am CET / 10pm PT on Monday
- [x] Test plan ready by 8am CET / 11pm PT on Monday
- [x] Testing

#### Thursday, February 23
- [x] Testing
- [x] Remind team members to assign issues that they intend to fix to the July milestone
- [x] Fixing (self-assigned, milestone assigned)
- [x] [Verification](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification) Since there are quite some old bugs to verify we verify by age, youngest first. The queries are:
  - [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
  - [Issues To Verify](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22February+2017%22)

#### Friday, February 24
- [x] Fixing last issues
- [x] Verification
- [x] Add/update shrink-wrap files for built-in extensions if needed (see [instructions](https://github.com/Microsoft/vscode/issues/8570#issuecomment-229669456))  - **endgame master**
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) after merging shrink-wrap findings - **endgame master**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
- [ ] Check new OSS usage is entered into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) - **endgame master**

#### Monday, February 27
- [x] [Acknowledge Pull Requests](https://vscode-tools.azurewebsites.net/) in release notes. - **endgame master**
- [ ] Satellite modules/npm packages ready, version updated, smoke tested, [PRs acknowledged](https://github.com/Microsoft/vscode-tools/tree/master/thankyou)
  - [x] [vscode](https://github.com/Microsoft/vscode-extension-vscode) **@bpasero**
  - [ ] [vscode-generator-code](https://github.com/Microsoft/vscode-generator-code) **@aeschli**
  - [x] [vsce](https://github.com/Microsoft/vsce) **@joaomoreno**
  - [x] [node debug](https://github.com/Microsoft/vscode-node-debug) **@weinand**
- [x] Translation input - **someone**
- [x] [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - **someone**
  - [x] OS X - **someone**
  - [x] Linux - **someone**
- [x] Update the [Release Notes](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/) (including **notable fixes**) and [documentation](https://github.com/Microsoft/vscode-docs/tree/vnext/docs).
  - [x] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [x] @dbaeumer
  - [x] @bpasero
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @aeschli
  - [x] @rebornix
  - [x] @ramya-rao-a
  - [x] @roblourens
  - [x] @sandy081
  - [x] @mjbvz
  - [x] @mousetraps
- [x] Freeze `insider` builds - **endgame master**
- [x] Branch code to `release/<x.y>` and release `master` - **endgame master**
- [x] Bump up the version in `package.json` - **endgame master**

#### Tuesday, February 28
- [x] Branch code to `release/<x.y> - **endgame master**
- [x] Announce master is open for business - **endgame master**
- [x] Polish release notes  - **@gregvanl**

#### Wednesday, Mar 1
- [x] Merge translations  - **someone**
- [x] Build stable for all platforms  - **@bpasero**
- [x] Sanity check of installable bits
  - [x] Windows - **someone**
  - [x] OS X - **someone**
  - [x] Linux - **someone**
- [x] Publish website **@gregvanl**
- [ ] Publish to stable  - **someone**
- [ ] Publish deb and rpms to repositories manually - **@Tyriar**
- [ ] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z`
- [ ] Enable scheduled `insider` builds  - **someone**
- [ ] Twitter announcement **@seanmcbreen**

**Comment by egamma** [comment]
Closing 1.10 has shipped.
