### ISSUE TITLE
Git operations don't show in reflog history

### ISSUE THREAD

**Issue by BrunnerLivio** [Microsoft/vscode#20980]
- VSCode Version: 1.9.1
- OS Version: Ubuntu 16.04.1 LTS (Xenial Xerus)

Steps to Reproduce:

1. Make file changes & save
2. Goto Git tab (CTRL + SHIFT + G)
3. Click "clean" button to reset all changes
4. Open terminal and run `git reflog`

Expected:
It should show the VSCode git operations (for example `git reset --HARD`). So you can rollback.

**Comment by joaomoreno** [comment]
VS Code spawns git for every git operation.

Clean means `git checkout FILE`, which doesn't cause a `HEAD` change, so it doesn't appear in the reflog.
