### ISSUE TITLE
when at least one extension has the `Restart Extensions` action available, restart them automatically

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#209880]
The `restart extensions` feature is super helpful. But, one has to visually notice the badge to take that action. 

Could we have a setting that, when enabled, automatically restarts the extensions for a user when at least one extension has that action available?

I think this would benefit all, but really help screen reader users. 

cc @jooyoungseo, @rperez030

**Comment by matthewjamesadam** [comment]
This would be a great improvement -- encouraging everyone to stay on evergreen plugin versions would be very useful.

**Comment by sandy081** [comment]
Doing this automatically might be too aggressive that users will see some flickering and sometimes some features like Custom Editors need a veto to restart extensions. 

We can try and experiment this.

**Comment by matthewjamesadam** [comment]
VSCode could maybe wait until it is not in the foreground (ie, the user has focused another app), and do this kind of work then. That way it’s unlikely to be noticeable or get in the users way.

**Comment by rperez030** [comment]
I'm not sure how I feel about an automatic restart specifically for screen reader users. Can't we use the notification system for that? We already have a key-binding for accepting notifications.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/214424
