### ISSUE TITLE
View Stash is missing Apply & Drop command

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#209823]
<img width="195" alt="image" src="https://github.com/microsoft/vscode/assets/2931520/8283bebe-0035-4862-9f66-e595603ded24">

There is only "Apply" and "Drop", both close the view. I usually apply and drop. If I would only apply (but not drop), I wouldn't feel safe about dropping it when cleaning up my stashes at some later point, as I never know if I already applied the stash or not.

**Comment by lszomoru** [comment]
Isn't "Apply & Drop" equivalent to "Pop"? "Pop" is an alternative command on "Apply" that you have access with the "Alt" modifier. Am I missing something? Thank you!

**Comment by hediet** [comment]
Ahh, I'm blind. Thanks!
