### ISSUE TITLE
Unreliable (glitchy) font size in sticky scroll in editor with mouse wheel zoom

### ISSUE THREAD

**Issue by Splines** [microsoft/vscode#209877]
## Description & steps to reproduce

The sticky scroll header glitches when zooming in and out with Mouse wheel zoom activated. That is, the font size keeps using an old value and items are misaligned. See the following screenshot and demo video. After some time, the font size suddenly resets and everything looks normal again.

In the screenshot, see that line 3 in the sticky scroll header (label: _services_) is even cut off.

![sticky scroll header glitch](https://github.com/microsoft/vscode/assets/37160523/3d05a82b-448a-4976-90d3-bb9e831bfcd0)

![sticky-scroll-vscode](https://github.com/microsoft/vscode/assets/37160523/314181d0-bd94-4c34-903a-3f46df5ae6af)

All extensions were disabled to reproduce this issue. 

---

## System information

VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.19045
Modes: Restricted

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (4.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

**Comment by aiday-mar** [comment]
Should be fixed now

**Comment by Splines** [comment]
Thanks a lot, it is indeed 🎉
