### ISSUE TITLE
Ignore the `indentNextLinePattern` rule when next line satisfies the `increaseIndentPattern` rule

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#209822]
This issue derives from the issue https://github.com/microsoft/vscode/issues/209804 and https://github.com/microsoft/vscode/issues/43244#issuecomment-2042078397. 

Recently we have modified the `indentNextLinePattern` pattern so that after a braceless if statement, on pressing Enter, we indent the next line as follows (here the dots signify white spaces):

```
if (true)
....
```

Some users have mentioned in the thread of the link above, that upon writing `{}` they would like the line to outdent, as follows:

```
if (true)
{}
```

We need to polish this.

**Comment by ciabaros** [comment]
This looks like the ideal solution we're looking for, as long as standard intentation rules would apply (e.g. 2 space, 4 space, tab, etc.) and it would support auto indentation in the following cases:
`
// Single line brace-less
if( true )
    logic( );

// Same line brace
if( true ) {
    logic( );
    // etc.
}

// New line brace
if( true )
{
    logic( );
    // etc.
}
`

**Comment by heroboy** [comment]
Not sure I should report this here.
Recent vscode auto indent not working perfect for me .
code: 
```
if (1)
    |
```
when input "{", code become:
```
if (1)
    {|}
```
It should unindent when input "{"
```
if (1)
{|}
```

**Comment by aiday-mar** [comment]
Hi what is the indentation level on that line? It will not outdent if the indentation level is not the exact default indentation level because it will be assumed that the indentation is indentation. 

Could you please show a video of this behavior? I can change the code if needed.

**Comment by heroboy** [comment]
@aiday-mar

![Animation](https://github.com/microsoft/vscode/assets/54468/42f8bafc-bb24-4d8a-9dd7-5c296a4b04b4)

```json
{
"javascript.format.placeOpenBraceOnNewLineForControlBlocks": true,
"javascript.format.placeOpenBraceOnNewLineForFunctions": true,
}
```

```
Version: 1.90.2 (user setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by aiday-mar** [comment]
Hi thank you for the quick response. You are on the latest stable release. A fix for this has been merged recently and is in the latest Insiders release. The next stable release will come out this week. The current behavior on the latest Insiders release is:

https://github.com/microsoft/vscode/assets/61460952/a6053375-f6c7-4fbc-8601-71e1768c0f17

**Comment by aiday-mar** [comment]
This issue will be closed, as the fix is in Insiders
