### ISSUE TITLE
Test: Git as an SCM provider

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#20999]
Test for #18615

- [x] Windows @sandy081 
- [x] OS X @ramya-rao-a 
- [x] Linux @Tyriar 

Complexity: 5

Make sure you `Enable SCM Preview` in the command palette. Most of this code is new, make sure you give a it proper smoke test:

- Git output channel
- Dirty diff (gutter decorations)
- SCM viewlet
  - Click, keyboard nav
  - Title, inline, context menu actions
  - Commit box
- Git status bar
- Merge conflict decorations
- Fetch happens automatically, unless configured otherwise
- SCM Viewlet shows progress during operations
- Global commands
- Editor title actions
- No repo workspace shows "Git Init" action
- Scoped git workspace: open a folder within a git repo, everything should work
- Editor selections
  - Staging, unstaging (global commands)
  - Reverting (global command)
- If you set a [git commit template](https://robots.thoughtbot.com/better-commit-messages-with-a-gitmessage-template) it is picked as a default value for the commit box
- If you use a repository that requires authentication, you get prompted for credentials
- Clone global command

**Comment by Tyriar** [comment]
@joaomoreno it's not clear what "editor title actions" are?

**Comment by joaomoreno** [comment]
@Tyriar Sorry, the "Switch to Changes" and "Switch to File" actions above the editor.
