### ISSUE TITLE
Folder order is wrong between `.` and `_`

### ISSUE THREAD

**Issue by cedvdb** [microsoft/vscode#209991]
Does this issue occur when all extensions are disabled?: Yes/No

![image](https://github.com/microsoft/vscode/assets/22280985/501205fe-860f-4401-954e-687c0b56e706)

Should be

![image](https://github.com/microsoft/vscode/assets/22280985/e228f17d-1a42-41ca-8dcb-1b2c763e8d78)

**Comment by yster-gaurav** [comment]
Yes, This issue is for me as well. 
![Screenshot from 2024-04-10 09-53-18](https://github.com/microsoft/vscode/assets/120642232/e20bacfc-99da-407d-b3c4-ac4603715939)

**Comment by gjsjohnmurray** [comment]
Related to #27759

What platform are you using?
