### ISSUE TITLE
_typescript.tryCompleteJsDoc steels Enter key

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#20990]
* have a snippet with placeholder
* open a TS file
* insert snippets, fill out placeholders
* select Enter to leave snippet mode
* :bug: nothing happens, keybindingResolve shows that `_typescript.tryCompleteJsDoc` wins

**Comment by jrieken** [comment]
While the feature is quite cool the implementation is bad in many ways. There seems to be a misconception of how keybindings work because you cannot make the editor [type Enter](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/typescriptMain.ts#L109) when your command fails to do what it wants to do. That makes zero sense considering a user can re-configures this keybinding to lets say `Cmd+J`. Second, re-routing Enter through the extension (which can take up to 250ms) means that this messes with the typing-order: type `a`, type `Enter`, type `b` and if TS takes long enough you end up with `ab\n` instead of `a\nb`. Last, because the when-condition is weak this breaks all other consumers of Enter. The idea of keybindings is that you have a strong 'when'-condition which is checked *before* dispatching. Once that happened the command should do something and not attempt to back-dispatch (which is hopeless because keybindings are configurable). 

Ideas to make this work:
* Have a good when-condition (managed by TypeScript via the `when`-command) and register the command with that. That means you are still a command with a configurable keybinding or a menu item
* Expose in the API something like the `onWillType` and `onDidType` events we have internally. We have used them to make things like format on type or suggest on trigger character work. That means you are not a command but something like a typing participant. We will enter new terrain with that.
* Hook into IntelliSense, know when you are inside a doc comment, and suggest accordingly. This can be done in addition to the above two

**Comment by alexandrudima** [comment]
Nice! :heart:
