### ISSUE TITLE
Test: Put theme configuration to settings.json

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#20998]
Test for #7358

- [x] any os @joaomoreno 
- [x] any os @roblourens 

Complexity: 2

Theme configuration is now part of the settings. 
```
  // Specifies the color theme used in the workbench.
  "workbench.colorTheme": "Default Dark+",

  // Specifies the icon theme used in the workbench.
  "workbench.iconTheme": null,
```

- Test that changing the theme can still be done through commands and the `Preferences > Color Theme` and `Preferences > File Icon Theme` menu items
   - the setting will be applied to the user settings unless it is already defined in the workspace settings, then it will be applied to the workspace settings
   - if the setting matches the default theme, the setting is removed rather than set
- Test that you can change the theme in the settings editor
   - intellisense, hover should be there
- Test that reloading VSCode restores the correct theme
   - there should not be any color flickering, unless the theme is configured in the workspace
- Test that migrating from a older version of VSCode (1.9 or less) works.
   - no change of theme
   - theme is set in the settings

Older version of vscode:
- [win](https://az764295.vo.msecnd.net/insider/27240e71ef390bf2d66307e677c2a333cebf75af/VSCode-win32-1.9.0-insider.zip)
- [macos](https://az764295.vo.msecnd.net/insider/27240e71ef390bf2d66307e677c2a333cebf75af/VSCode-darwin-insider.zip)
- [linux 32](https://az764295.vo.msecnd.net/insider/27240e71ef390bf2d66307e677c2a333cebf75af/code-insider-1.9.0-1485950021_i386.tar.gz)
- [linux 64](https://az764295.vo.msecnd.net/insider/27240e71ef390bf2d66307e677c2a333cebf75af/code-insider-1.9.0-1485949086_amd64.tar.gz)

**Comment by joaomoreno** [comment]
@aeschli IMO this should have a tester per platform.

**Comment by roblourens** [comment]
@joaomoreno I'm assuming you did Mac, I'll test Windows
