### ISSUE TITLE
Pattern matching bug in serverReadyAction? (`vscode.debug-server-ready`)

### ISSUE THREAD

**Issue by nightgrey** [microsoft/vscode#209937]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  `1.88.0 | 5c3e652f63e798a5ac2f31ffd0d863669328dc4c | x64` + `1.89.0-insider
f8d35f6a712c59f96078161799435d0e83461556`
x64
- OS Version: EndeavourOS x86_64
- Kernel: 6.6.25-1-lts
- KDE Plasma 6.0.3
- Shell: zsh 5.9
- Terminal: konsole 24.2.1 / yakuake 24.02.1 / code 1.88.0
- Node: v21.6.2
- Bun: 1.1.3

**Steps to Reproduce:**

1. Copy either command-by-command or copy into a file and execute (`sh setup.sh`)
```bash
# Setup Remix and Next.js project
npx -y create-remix@latest remix -y && npx -y create-next-app@latest next --ts --eslint --tailwind --src-dir false --app true --import-alias false

# Create .vscode folders
mkdir -p ./next/.vscode && mkdir -p ./remix/.vscode/

# Create launch.json in current folder
read -r -d '' JSON <<'EOF'
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Issue",
            "type": "node-terminal",
            "request": "launch",
            "command": "npm run dev",
            "serverReadyAction": {
                "pattern": ".+Local:.+(https?:\/\/.+)",
                "uriFormat": "%s",
                "webRoot": "${workspaceFolder}",
                "action": "debugWithChrome"
            }
        }
    ],
    "compounds": []
}
EOF
echo $JSON > launch.json

# Symlink ./launch.json into the next and remix project
ln -s ../../launch.json ./next/.vscode/launch.json && ln -s ../../launch.json ./remix/.vscode/launch.json 

# Open both projects
code remix && code next
```
2. Press F5 (or launch "Issue" configuration in "Run and Debug") in both projects and observe the `serverReadyAction`'s opened browser (URL). The Remix project opens `http://localhost5173/` (missing `:`) while the Next.js project opens `http://localhost:3000`. 

I'm not sure why the `:` is omitted in the case of Remix. Is that a bug?

![Screenshot_20240409_121950](https://github.com/microsoft/vscode/assets/6065401/377c0e5e-377c-4e47-bf7c-6690d451c5b1)
![Screenshot_20240409_121932](https://github.com/microsoft/vscode/assets/6065401/3c36f32a-b3d2-4ae0-be8d-0875717919d1)

**Debugging efforts:**

I'm not sure if this is helpful: I sadly don't know how to debug built-in extensions in VSCode, but  I located the responsible part and tried if I could replicate it that way, to see what was causing the issue. I modified the code to only the parts necessary and removed any calls to VSCode classes, instead `console.log`-ing and `console.error`-ing.

I couldn't replicate it:

```ts
import * as util from 'util';

const stdout = '  ➜  Local:   http://localhost:5173/';

const pattern = '.+Local:.+(https?://.+)';
const uriFormat = '%s';

const regexp = new RegExp(pattern, 'i');

function removeAnsiEscapeCodes(str: string): string {
  const CSI_SEQUENCE = /(:?\x1b\[|\x9B)[=?>!]?[\d;:]*["$#'* ]?[a-zA-Z@^`{}|~]/g;

  if (str) {
    str = str.replace(CSI_SEQUENCE, '');
  }

  return str;
}
function openExternalWithString(captureString: string) {
  const URI_PORT_FORMAT = 'http://localhost:%s';
  const URI_FORMAT = '%s';
  let uri;
  if (captureString === '') {
    // nothing captured by reg exp -> use the uriFormat as the target uri without substitution
    // verify that format does not contain '%s'
    const format = uriFormat || '';
    if (format.indexOf('%s') >= 0) {
      console.error(
        `"Format uri ('{0}') uses a substitution placeholder but pattern did not capture anything.",`,
      );
      return;
    }
    uri = format;
  } else {
    // if no uriFormat is specified guess the appropriate format based on the captureString
    const format =
      uriFormat ||
      (/^[0-9]+$/.test(captureString) ? URI_PORT_FORMAT : URI_FORMAT);
    // verify that format only contains a single '%s'
    const s = format.split('%s');
    if (s.length !== 2) {
      console.error(
        "Format uri ('{0}') must contain exactly one substitution placeholder.",
        format,
      );
      return;
    }
    uri = util.format(format, captureString);
  }

  console.log(`would open:`, uri);
}

function detectPattern(s: string) {
  const matches = regexp.exec(removeAnsiEscapeCodes(s));

  if (matches && matches.length >= 1)
    openExternalWithString(matches.length > 1 ? matches[1] : '');
}

detectPattern(stdout); // would open: http://localhost:5173/
```

This outputs `would open: http://localhost:5173/` - so in the end, I'm not sure if the bug is on my side. Can anyone reproduce this?

**Comment by roblourens** [comment]
I'm trying to repro this in a simpler way

```
const stdout = '  ➜  Local:   http://localhost:5173/';
console.log(stdout);
```

and the same `serverReadyAction` that you have. It works fine. Can you check the output of the project that isn't working? Maybe a screenshot or copy/paste of the exact output?

If you want to debug, you can follow the steps at https://github.com/microsoft/vscode/wiki/How-to-Contribute and set a breakpoint somewhere around https://github.com/microsoft/vscode/blob/a4053a1d769c8d73825076168dcc20ff7b6759d4/extensions/debug-server-ready/src/extension.ts#L150

**Comment by nightgrey** [comment]
@roblourens Hey! I'm coming back with results after debugging. :)

<details>
 <summary>Previous steps</summary>

#### 1. `openWithExternalString`

https://github.com/microsoft/vscode/blob/a4053a1d769c8d73825076168dcc20ff7b6759d4/extensions/debug-server-ready/src/extension.ts#L150

Reveals that the value is already set in the detectPattern function.

![image](https://github.com/microsoft/vscode/assets/6065401/d79e55f2-ee4c-4b3d-941f-c67235212dca)

#### 2. `detectPattern`:

https://github.com/microsoft/vscode/blob/9deb01df504be7108c8d2aa79aec5ebe3eefa5ef/extensions/debug-server-ready/src/extension.ts#L140-L142

Reveals that the value that is regex'ed on is:
```
"  ➜  Local:   http://localhost5173/\r\n  ➜  Network: use --host to expose\r\n  ➜  press h + enter to show help\r\n"
```

![image](https://github.com/microsoft/vscode/assets/6065401/37eca8ed-0442-41c1-b5e3-69cb2aa9c3af)

... which results in a matches array of:

```
[
  "  ➜  Local:   http://localhost5173/",
  "http://localhost5173/",
]
```

![image](https://github.com/microsoft/vscode/assets/6065401/e7a686ca-a6cb-4c0a-bf9b-2bcd621e3ce9)

... where matches[1] is picked. Okay, let's go one further back.

</details>

#### `startListeningTerminalData`

The issue becomes visible here.

https://github.com/microsoft/vscode/blob/9deb01df504be7108c8d2aa79aec5ebe3eefa5ef/extensions/debug-server-ready/src/extension.ts#L98

`e.data` has the following value:

```
'  [32m➜[39m  [1mLocal[22m:   [36mhttp://localhost:[1m5173[22m/[39m\r\n[2m  [32m➜[39m  [1mNetwork[22m[2m: use [22m[1m--host[22m[2m to expose[22m\r\n[2m[32m  ➜[39m[22m[2m  press [22m[1mh + enter[22m[2m to show help[22m\r\n'
```

![image](https://github.com/microsoft/vscode/assets/6065401/baeb596b-f4c0-4bfc-9736-ec90d21e952f)

... and after `removeAnsiEscapeCodes`, the value becomes what is given to `detectPattern`:

```
'  ➜  Local:   http://localhost5173/\r\n  ➜  Network: use --host to expose\r\n  ➜  press h + enter to show help\r\n'
```

... missing the `:`.

---

#### Reproduction

To reproduce the issue quickly, you can create a `test.js` that logs the string in `e.data`, as follows:

```js
console.log(`'  [32m➜[39m  [1mLocal[22m:   [36mhttp://localhost:[1m5173[22m/[39m\r\n[2m  [32m➜[39m  [1mNetwork[22m[2m: use [22m[1m--host[22m[2m to expose[22m\r\n[2m[32m  ➜[39m[22m[2m  press [22m[1mh + enter[22m[2m to show help[22m\r\n'`)
```

.. and then start that with the `serverReadyAction` above.

---

Now, my assumption is that `removeAnsiEscapeCodes` shouldn't remove the `:` at this place. Is that correct?

**Comment by nightgrey** [comment]
The culprit matching `:` in the regex seems to be `[\d;:]*`, but I don't know anything about CSI sequences, and just removing this probably breaks other stuff.

**Comment by roblourens** [comment]
Thanks for doing that investigation! I think the problem is actually the `:?`

**Comment by connor4312** [comment]
Indeed, good find

**Comment by TylerLeonhardt** [comment]
There's a lot here and I wanna make sure the steps are clear for verification. Adding verification steps needed.

**Comment by roblourens** [comment]
This should do it- 

- Have a js file that is just 
```
const stdout = '  �[32m➜�[39m  �[1mLocal�[22m:   �[36mhttp://localhost:�[1m5173�[22m/�[39m\r\n�[2m  �[32m➜�[39m  �[1mNetwork�[22m�[2m: use �[22m�[1m--host�[22m�[2m to expose�[22m\r\n�[2m�[32m  ➜�[39m�[22m�[2m  press �[22m�[1mh + enter�[22m�[2m to show help�[22m\r\n';
console.log(stdout)
```
- And add this to your node launch.json
```
            "serverReadyAction": {
                "pattern": ".+Local:.+(https?:\/\/.+)",
                "uriFormat": "%s",
                "webRoot": "${workspaceFolder}",
                "action": "debugWithChrome"
            }
```

When you debug, it should also start a Chrome debug session and the browser should be open to the correct port, `http://localhost:5173` instead of omitting the colon, like `http://localhost5173`
