### ISSUE TITLE
Compare viewer: Revert button doesn't work when only 1 change

### ISSUE THREAD

**Issue by qarlosalberto** [microsoft/vscode#209926]
- VS Code Version: 1.88.0
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Copy code to clipboard.
2. Compare clipboard with empty file.
3. Select inline view:

![imagen](https://github.com/microsoft/vscode/assets/5955143/6073cd72-c125-4776-81ac-2249bcf80f41)

Revert button doesn't work. If you click in the red section and "Revert this change" works fine.

**Comment by qarlosalberto** [comment]
I have tested in 1.86.0 and it works fine.

**Comment by qarlosalberto** [comment]
Is this a known bug?

**Comment by hediet** [comment]
Fixed.
