### ISSUE TITLE
win32AppId in product.json has too many parenthesis

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#20996]
https://github.com/Microsoft/vscode/blob/master/product.json#L12

`win32AppId": "{{E34003BB-9E10-4501-8C11-BE3FAA83F23F}"`

**Comment by roblourens** [comment]
I assume we need to delete one but it's been like that for 7 months.

**Comment by joaomoreno** [comment]
Nope, the bracket is escaped.
