### ISSUE TITLE
Deprecate debug type 'node2' 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#20993]
In order to smoothen the node debugging experience (see #19650) we should try to deprecate the debug type 'node2' and make it as invisible as possible.

If we cannot deprecate the debug type, we should warn the user when launching a 'node2' debug session (which could be done in the node-debug2 extension code).

**Comment by isidorn** [comment]
Feedback on the message welcome

![screen shot 2017-02-21 at 17 21 14](https://cloud.githubusercontent.com/assets/1926584/23173664/37968c1a-f85a-11e6-90e4-7fdfecb754aa.png)

**Comment by weinand** [comment]
I've added a blurb about the 'protocol' to the deprecation message:

![2017-02-21_17-40-12](https://cloud.githubusercontent.com/assets/1898161/23174511/e70a53b4-f85c-11e6-810a-e1db30448aa1.png)
