### ISSUE TITLE
VS Code is crashing when performing basic actions

### ISSUE THREAD

**Issue by OzzyTheGiant** [microsoft/vscode#209919]
It seems that VS Code just crashes for no reason on specific actions:

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0
- OS Version: Ubuntu 22.04.4

Steps to Reproduce:

- Clicking the Commit button in the Source Control panel
  - Expected: The commit succeeds and clears the tracked files from Staging
  - Actual: The whole app crashes
- Attempting to remove a running container in the Docker panel
  - Expected: The container should be removed from the list of available containers
  - Actual: The whole app crashes
- Pressing Ctrl+. on code that has been underlined with an error (such as when attempting to bring up the suggestions for an undefined variable in Python).
  - Expected: The suggestions menu should appear
  - Actual: The whole app crashes
- Clicking the About option on the Help menu
  - Expected: I should see info about VS Code
  - Actual: The whole app crashes

**Comment by OzzyTheGiant** [comment]
Update: now it also happens when I have an unsaved file and I attempt to close the file without saving. This is really bad

**Comment by saschwarz** [comment]
This just happened to me on Windows when I went to save a new file. The native Windows dialog appeared and before I could click anything vscode crashed, installed today's update, and relaunched. Now I'm wondering if I can recover the unsaved file. All my buffers are closed and only the Release Notes buffer is visible.

**Comment by deepak1556** [comment]
If the issue is present with latest stable, please share the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report
