### ISSUE TITLE
Quick Search Polish April 2024

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#209979]
This issue tracks the polish items for Quick Search this iteration.

- Remove experimental flag https://github.com/microsoft/vscode/issues/209976
- Promote quick search in quick access list https://github.com/microsoft/vscode/issues/209974
- Switch `link-external` to `go-to-search` codicon https://github.com/microsoft/vscode/issues/209978

**Comment by pagict** [comment]
hi, did we just miss mention this issue https://github.com/microsoft/vscode/issues/206032 , since it's already merged into main

**Comment by andreamah** [comment]
> hi, did we just miss mention this issue #206032 , since it's already merged into main

This can get tracked in the issue that you linked. This is for quick search, which is a different feature than the search panel.
