### ISSUE TITLE
Bash syntax highlighting breaks on nested arithmetic expression

### ISSUE THREAD

**Issue by AfroThundr3007730** [microsoft/vscode#209901]
Type: <b>Bug</b>

Take the following bash snippet:

```bash
#!/bin/bash

# Some comment before
function foo() {
    # Does cool stuff
    printf '%d\n' "$(printf '%03d' $((2+$1)))"
}
# Some comment after
function foo2() {
    :
}
```

Before the 1.88 update, the nested arithmetic expression didn't break syntax highlighting.

This is what it looks like now:
![image](https://github.com/microsoft/vscode/assets/7613032/78e49d76-d3bf-47cc-8f0b-7e6527733b81)

This doesn't just affect the builtin themes:
![image](https://github.com/microsoft/vscode/assets/7613032/105f6f43-7196-4d1c-bd97-3df6fe4a3dc9)

I've tested this on a fresh profile with no extensions.

VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:25:57.039Z)
OS version: Linux x64 6.8.4-100.fc38.x86_64

**Comment by AfroThundr3007730** [comment]
This actually breaks more than just syntax highlighting, intellisense and other things break after that point as well.

**Comment by alexr00** [comment]
After updating the syntax highlighting grammars I can no longer reproduce this. Fix will be in the next insiders.
