### ISSUE TITLE
Vs Code not responding on Ubuntu 22.04.4.4

### ISSUE THREAD

**Issue by samiramrullah** [microsoft/vscode#209951]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
![Screenshot from 2024-04-09 19-01-25](https://github.com/microsoft/vscode/assets/74055996/b52b8a12-9f24-4ccc-a042-3459d20d3fb6)

- OS Version: 
![Screenshot from 2024-04-09 18-29-10](https://github.com/microsoft/vscode/assets/74055996/e75aebf0-dafb-4f74-8bfc-3dd9291ada8e)

Whenever I open vs code I get message saying "Visual Studio Code " is not responding.
![Screenshot from 2024-04-09 19-03-31](https://github.com/microsoft/vscode/assets/74055996/5f84f4d0-4376-47ed-b5d2-873f5ba1e419)

When I click on wait , It closes.

**Comment by Eggbertx** [comment]
I am having this issue in Arch Linux, using 1.88.0, with all extensions disabled and a fresh install (renamed the ~/.config/Code/ directory)

**Comment by samiramrullah** [comment]
It is resolved,
It needs restart after update and installation of VS code.

**Comment by samiramrullah** [comment]
It is resolved,
It needs restart after update and installation of VS code.
