### ISSUE TITLE
Pull out debug control panel

### ISSUE THREAD

**Issue by osenvosem** [Microsoft/vscode#20992]
- VSCode Version: 1.9.1
- OS Version: MacOS 10.12.3

How to pull the panel out in this situation?

![screen-shot-2017-02-21-at-18 00 21](https://cloud.githubusercontent.com/assets/6762673/23170735/5faccee2-f861-11e6-949c-c0dc4e25f849.png)

**Comment by osenvosem** [comment]
I managed to do this by shrinking editor horizontally to minimum. But, nevertheless, the panel shouldn't be allowed to move behind the visible area. You can close this issue after taking note of this.

**Comment by roblourens** [comment]
#20298 Fixed in Insiders or the next release
