### ISSUE TITLE
Custom labels do not work in file search and diff editor

### ISSUE THREAD

**Issue by circlesmiler** [microsoft/vscode#209931]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0
- OS Version: MacOS 14.4.1

Steps to Reproduce:

1. Create some `index.html` files in multiple sub folders
2. Configure `customLabels` (see below)
3. Search for `index.html` in _file search_

settings.json:

```json
  "workbench.editor.customLabels.patterns": {
    "**/index.html": "${filename}.${extname} (${dirname})"
  },
```

As you hopefully can see in the video, the custom labels are used in the editor tabs and in the open editors switch menu but not in the file search menu:

![VSCode-Bug](https://github.com/microsoft/vscode/assets/22213841/9c6db68f-cb34-4707-b317-e56ae6394e07)

**Comment by dimateos** [comment]
It should probably match the real filename and also the custom label.

Another issue is with the diff editor, when you open the changes of a file it displays the original filename:

![image](https://github.com/microsoft/vscode/assets/26868611/94f8097b-91b1-455f-931d-7315081e0752)

Note that the pattern has wildcards at the end too etc: `**/conanfile.json*": "conan - ${dirname(0)}`

I guess the "(working tree)" or similar could be added to the list of potential `${variables}`, or just always append it at the end.

> Could open a separate issue, but seemed related and discussable here

**Comment by ADTC** [comment]
@circlesmiler could you add "and diff editors" to your title please? It is sadly not working for diff editors (both working tree and index).

**Comment by andreamah** [comment]
@benibenj is this a fix that you need @hediet and I to adopt somewhere?

**Comment by benibenj** [comment]
@andreamah We are still deciding on where to show the custom labels and where not. For the time being we are showing it everywhere we render the current open editors. Depending on the communities feedback/wishes we will expand adoption to all other resource labels such as search. In that case I will provide a very simple way to adopt it.
