### ISSUE TITLE
Add Youtube codecs in the supported codec list

### ISSUE THREAD

**Issue by HaArLiNsH** [microsoft/vscode#209957]
This is a follow up of this issue : 

https://github.com/microsoft/vscode/issues/158858

We are in 2024, Youtube is still present and very largely used and I would like to humbly request that the codec they use are added in the list of supported codecs. 

Otherwise it is nearly impossible to use embedded Yt video files in our projects.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/167685

**Comment by HaArLiNsH** [comment]
This is a Dup of https://github.com/microsoft/vscode/issues/167685

There you are talking about the AAC audio codec, but what about the vp9, av1, opus VIDEO codecs ? 

I get that you don't have a legal response for the AAC codec but the videos one are royalty free. We could at least use the video even without the sound.

**Comment by HaArLiNsH** [comment]
Hi,

This is NOT a Dup of #167685<https://github.com/microsoft/vscode/issues/167685>

There you are talking about the AAC audio codec, but what about the vp9, av1, opus VIDEO codecs ?

I get that you don't have a legal response for the AAC codec but the videos one are royalty free. We could at least use the video even without the sound.




________________________________

**Comment by HaArLiNsH** [comment]
I don’t understand, the wiki page of these codecs says :

 VP9 is an [open](https://en.wikipedia.org/wiki/Open_format) and [royalty-free](https://en.wikipedia.org/wiki/Royalty-free)[[1]](https://en.wikipedia.org/wiki/VP9#cite_note-Gigaom-1) [video coding format](https://en.wikipedia.org/wiki/Video_coding_format) developed by [Google](https://en.wikipedia.org/wiki/Google). 

https://en.wikipedia.org/wiki/VP9


AOMedia Video 1 (AV1) is an [open](https://en.wikipedia.org/wiki/Open_format), [royalty-free](https://en.wikipedia.org/wiki/Royalty-free) [video coding format](https://en.wikipedia.org/wiki/Video_coding_format) initially designed for video transmissions over the Internet.

https://en.wikipedia.org/wiki/AV1


Opus is a totally open, royalty-free, highly versatile audio codec.

https://opus-codec.org/

**Comment by isidorn** [comment]
Sorry but for legal / fee questions I trust our legal team and not Wikipedia.
Thanks for understanding.

**Comment by HaArLiNsH** [comment]
Oh no problem, they must be more competent than my 30 sec of research for sure :)

**Comment by HaArLiNsH** [comment]
I don’t understand your legal team, the wiki page of these codecs says :

VP9 is an open<https://en.wikipedia.org/wiki/Open_format> and royalty-free<https://en.wikipedia.org/wiki/Royalty-free>[1]<https://en.wikipedia.org/wiki/VP9#cite_note-Gigaom-1> video coding format<https://en.wikipedia.org/wiki/Video_coding_format> developed by Google<https://en.wikipedia.org/wiki/Google>.

https://en.wikipedia.org/wiki/VP9


AOMedia Video 1 (AV1) is an open<https://en.wikipedia.org/wiki/Open_format>, royalty-free<https://en.wikipedia.org/wiki/Royalty-free> video coding format<https://en.wikipedia.org/wiki/Video_coding_format> initially designed for video transmissions over the Internet.

https://en.wikipedia.org/wiki/AV1


Opus is a totally open, royalty-free, highly versatile audio codec.

https://opus-codec.org/





________________________________

**Comment by isidorn** [comment]
Closing as dupe. One issue to track codec request is enough for now.
