### ISSUE TITLE
Why Git Readme Stuffs aren't coming in extension home page.

### ISSUE THREAD

**Issue by rahulsahay19** [Microsoft/vscode#20995]
Hi Team,

I have extension [Extension-Page](https://marketplace.visualstudio.com/items?itemName=rahulsahay.Csharp-ASPNETCore). Here, my readme file is not coming in extension home page, which I have created in git repository. It is showing the message "**No overview has been entered by publisher**"

I have also attached package.json file. 

[package.zip](https://github.com/Microsoft/vscode/files/790602/package.zip)

Kindly let me know, if I am missing any thing. 

Thanks,
Rahul

**Comment by roblourens** [comment]
I think the README should be pulled from the package you published with vsce, not github. Did you publish the readme file?

**Comment by rahulsahay19** [comment]
In that case, what will be the schema for pulling the same from package folder say, in package.json I have already provided git url. In the same context, let's suppose, I keep that readme.md file in my vsce folder alsong with snippet, then in that case, what will be the json name-value pair for pulling the readme.md file. You can also refer, my package.json which I already attached.

**Comment by roblourens** [comment]
You don't have to reference it in the package.json file. It should just look for a readme.md file in the package.

**Comment by rahulsahay19** [comment]
Thanks!
