### ISSUE TITLE
When NVIDIA Fast Sync is enabled, the entire window flickers

### ISSUE THREAD

**Issue by sho9029** [microsoft/vscode#209969]
Type: <b>Bug</b>

Steps to Reproduce:

1. Enable Fast Sync in the NVIDIA Control Panel
2. Open VSCode

I recorded the screen with software and nothing happened, so I recorded the screen with a camera.
Also, in the video, extensions are enabled, but the same problem occurs when all extensions are disabled.

https://github.com/microsoft/vscode/assets/49068710/7a41af77-931a-433a-bf6f-4e433b67e1fa

VS Code version: Code - Insiders 1.89.0-insider (f8d35f6a712c59f96078161799435d0e83461556, 2024-04-09T05:49:57.111Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-14700KF (28 x 3418)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.82GB (51.98GB free)|
|Process Argv|--crash-reporter-id 0fa86c3d-6a06-4e7f-8e49-73077c6a5f98|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>

<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
vsaa593:30376534
py29gd2263:30784851
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
bf62j303:30968145
cppperfnew:30980852
d34g3935:30961436
fegfb526:30952798
bg6jg535:30979844
ccp2r3:30958153
pythonait:30973460
666c4381:30973073
gee8j676:31009450
g1icg217:30999571
jg8ic977:31013176

```

</details>

**Comment by carloscbl** [comment]
Same problem here windows 11, but only when i maximize the screen, if i make a specific rule and restart vscode then no problem
im using RTX 2070
![image](https://github.com/microsoft/vscode/assets/8027635/d6688add-6017-48fb-b65f-4d7bff210a5d)

**Comment by deepak1556** [comment]
Closing as this is something to be addressed in the runtime and usually gets resolved with updates.
