### ISSUE TITLE
Allow for Editor Action icons to be shown on inactive Editor Groups

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#209962]
For our extension (VS Code for Education) we have a main webview content pane parked in editor group 1 that hosts our lesson content and we often have a runnable code file parked in editor group 2. To help students with running their code files, we provide a run Editor Action that we add to the editor actions for code files. We also don't show the usual run and debug sidebar section in our basic student profiles, so they need to run via the file editor actions.

Our discoverability problem with this is that in our default layout focus is usually in the lesson content where students are reading text, navigating lesson parts, or answering questions. This means that most of the time the run button on the code file is invisible, and only shows up when clicking over to it. We've seen a lot of new students stuck on initially finding out how to run their code files.

![Recording 2024-04-09 at 08 48 47](https://github.com/microsoft/vscode/assets/812783/1c28ff31-9212-43fd-b952-83bb5d842116)

Ideally, we'd like some way to work around this, either by a general setting we could turn on to show all editor actions in inactive windows, or by letting specific editor action contributions opt into being shown on inactive editor groups. So here we could opt in all or specific primary actions:
https://github.com/microsoft/vscode/blob/fb757ca0415b12fa8f68344dc23e431f5a125951/src/vs/workbench/browser/parts/editor/multiEditorTabsControl.ts#L1619

@asmeets

**Comment by bpasero** [comment]
Maybe as a setting? One thing we have to ensure is not broken is that these actions get the right context. When you click on them while the other group is active, they might make wrong assumptions about which group is active because that state only updates based on focus changes.

**Comment by benibenj** [comment]
This is not easily possible currently due to context keys and focus

https://github.com/microsoft/vscode/assets/44439583/31363fb2-1549-4ef7-8751-10333d895fbb

**Comment by asmeets** [comment]
I completely understand given the context of the desktop environment, and working specifically with side-by-side code. For the extension in the .dev web context where we have curriculum on one side and code on the right, we're facing discoverability issues from new users in EDU, even with prompting - who can't "see" the run button unless focused in that panel.

Just to clarify, is it something that is possible and can be worked on and could be accessed as a setting or another option, or not possible?

CC: Adding @bamurtaugh to this issue.

**Comment by benibenj** [comment]
I think we should be able to figure out a solution for your case. I currently see two options:
1. Add a setting which shows all actions on non-focused Editor Groups: This is probably much harder to support and it might not be possible to guarantee that it always works correctly
2. Add a setting which allows users to specify which actions should be shown on inactive Editor Groups. This probably could work well for your case but might have in general similar problems to option 1. 

Step 2. seems more likely currently, but requires more investigation. I'll have a closer look next week and follow up here

**Comment by benibenj** [comment]
@IanMatthewHuff @asmeets in tomorrows insiders we will support the `workbench.editor.alwaysShowEditorActions` setting which will show editor actions also on inactive groups. Please let me know if you see any unexpected behaviour. 

There is still some work to be done for our existing actions such as making sure they extract the context correctly.

**Comment by IanMatthewHuff** [comment]
@benibenj Thanks so much! Excited to check it out.
