### ISSUE TITLE
Bad behavior and habits around terminal (RMB - paste not showing context menu)

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#209981]
Type: <b>Bug</b>

Right now when clicking on terminal VSC doing paste not showing context menu.
What a stupid think for Win users when RMB is always context menu eg. to find "clear screen" or just past or cut, etc.
If paste, then should be maybe MMB (middle, as scroll btn).

VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by meganrogge** [comment]
sounds like you've tweaked this setting `terminal.integrated.rightClickBehavior`

**Comment by ManPython** [comment]
True, was changed, but I did not changed this manually.. strange.
