### ISSUE TITLE
The users' avatars in Gitlens use default style, not Github account

### ISSUE THREAD

**Issue by Tommy-Yao** [microsoft/vscode#209903]
- VS Code Version: 1.88.0
- OS Version: Ubuntu 22.04

As follow image, The commit made by Github's merge shows correct avatar, but other commits show "robo" avatar.

![image](https://github.com/microsoft/vscode/assets/82805260/0c768be8-868c-4bcd-ae88-798044ba7a97)

The avatar worked well in my previous VM, but it doesn't works on my new VM. Because previous VM has other issues, I setup a new one.
Is there any extra settings for this?

**Comment by lszomoru** [comment]
Please file this issue in [the GitLens extension repository](https://github.com/gitkraken/vscode-gitlens/issues). Thanks!
