### ISSUE TITLE
Git commit message input field no longer resizes

### ISSUE THREAD

**Issue by AndriiTsok** [Microsoft/vscode#210]
OS X 10.11.1
VS Code version 0.10.1 (0.10.1)

Visual bug appears when you narrowed Git sidebar.

![vsbug](https://cloud.githubusercontent.com/assets/733224/11271675/42b78896-8ed0-11e5-8051-d97e8f534ea9.png)

**Comment by AndriiTsok** [comment]
@joaomoreno @bpasero I just tried to see in guts of vscode and I guess possible fixes:

1. Increase field height by 1px on https://github.com/Microsoft/vscode/blob/497788c0bcd20859f736d585b49c208af8dd518f/src/vs/workbench/parts/git/browser/views/changes/changesView.css#L24

2. Make field auto resizable when placeholder is wrapped

3. Make placeholder no-wrap

**Comment by joaomoreno** [comment]
This is a bad regression. The text box should automatically adjust its height based on its contents. Thanks for the report and extra info!

**Comment by joaomoreno** [comment]
Much better. :+1:
