### ISSUE TITLE
Jupyter Notebook Outline Pane Not Responsive

### ISSUE THREAD

**Issue by DavidHJong** [microsoft/vscode#210007]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: V1.88.0
- OS Version: 19045.4239

Steps to Reproduce:

1. open two jupyter notebooks with markdown cells. 
2. switch between them and you will see the outline pane doesn't update to match the active notebook. 
3. This only happens in vscode 1.88.0. when I downgrade it to 1.87.2, the problem is gone.

**Comment by yuuuxt** [comment]
1.88.0 having the same annoying issue (not trying downgrading). Reload window can make the outline responds to the current notebook (as a very limited workaround). Waiting for the fix!

**Comment by Yoyokrazy** [comment]
Hi! This was fixed via recovery release 1.88.1

Please reopen if you are still able to repro the bug within the latest release. Thanks!
