### ISSUE TITLE
Wrong SSH file system shown after VS Code upgrade

### ISSUE THREAD

**Issue by Keno** [microsoft/vscode#210009]
Type: <b>Bug</b>

I just upgraded my VS Code insiders. Now, when I connect via SSH, "Open Folder" will show my local filesystem rather than my remote file system. Attempting to open a previous session from "Recent" gives the following error:
```
The editor could not be opened due to an unexpected error: ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2B
```
while there's an error pop-up in the lower right that reads
```
Failed to connect to the remote extension host server (Error: WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" }))
```

VS Code version: Code - Insiders 1.89.0-insider (f8d35f6a712c59f96078161799435d0e83461556, 2024-04-09T05:49:23.835Z)
OS version: Linux x64 6.8.0-76060800daily20240311-generic
Modes:
Remote OS version: Linux x64 5.4.0-169-generic
Connection to 'SSH: demeter1' could not be established  WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" })

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor (12 x 4262)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.26GB (17.13GB free)|
|Process Argv|--crash-reporter-id 87f6b089-2604-48f2-93c0-c19741185139|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: deepsea3|
|OS|Linux x64 5.4.0-169-generic|
|CPUs|AMD EPYC 7513 32-Core Processor (64 x 1499)|
|Memory (System)|1007.81GB (455.39GB free)|
|VM|0%|

Connection to 'SSH: demeter1' could not be established  WrappedError(WrappedError { message: "server exited without writing socket", original: "channel closed" })
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:30784851
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
bf62j303:30968145
cppperfnew:30980852
8082a590:30961435
fegfb526:30952798
bg6jg535:30979844
ccp2r6:30958154
pythonait:30973460
jchc7451:30973074
gee8j676:31009450
g1icg217:30999571
g316j359:31013175

```

</details>

**Comment by roblourens** [comment]
Please share the log from the Remote-SSH output channel

**Comment by Keno** [comment]
I just tried again (I had switched to the non-insiders in the meantime) and this is fixed in the most recent version:
```
Version: 1.89.0-insider
Commit: 910284865c34fd492e3f6fd5a8ab8e571432cc58
Date: 2024-04-17T05:49:55.550Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.0-76060800daily20240311-generic
```
Must have been something temporary. If I see it again, I'll share the requested logs.

**Comment by SimonBenhamou** [comment]
I have this issue on the current 1.89.1.

I can temporarily fix it by removing the .vscode-server directory on the remote, but the issue comes back systematically after about an hour of work.

It's very annoying and makes vscode pretty much unusable.

**Comment by connor4312** [comment]
@SimonBenhamou can you please

1. Share the "Remote - SSH" output from the Output pane
2. Look for a log file in the output (ctrl+f for ` > ` with spaces around it) and share its contents if it exists. Thanks!

**Comment by SimonBenhamou** [comment]
You'll find the logs here (I masked the IP and company's name):
[enopro_remote_ssh_output_1.txt](https://github.com/user-attachments/files/15536357/enopro_remote_ssh_output_1.txt)

Here is the content of "/home/sbenhamou/.vscode-server/.cli.dc96b837cf6bb4af9cd736aa3af08cf8279f7685.log"

```
Listening on 127.0.0.1:40663
[2024-06-03 14:19:19] info Disposed of connection to running server.
looking for token 4d8f8d3f-5361-419c-8757-f0ca897123d0, got Some("4d8f8d3f-5361-419c-8757-f0ca897123d0")
[2024-06-03 14:19:19] info Checking /home/sbenhamou/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/log.txt and /home/sbenhamou/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/pid.txt for a running server...
[2024-06-03 14:19:19] info Found running server (pid=1498987)
[2024-06-03 14:19:19] info Disposed of connection to running server.
[2024-06-03 14:19:19] info Disposed of connection to running server.
[2024-06-03 14:19:20] info Disposed of connection to running server.
[2024-06-03 14:19:20] info Disposed of connection to running server.
```

**Comment by SimonBenhamou** [comment]
This happens systematically now, at each "reload window" action. Here is the popup I get:

`Failed to connect to the remote extension host server (Error: CodeError(AsyncPipeFailed(Os { code: 2, kind: NotFound, message: "No such file or directory" })))`

Only way to fix it temporarily is to delete .vscode-server-insiders/cli/servers
