### ISSUE TITLE
Can't customise the shorcut for deleting file

### ISSUE THREAD

**Issue by devinjohw** [microsoft/vscode#210079]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0
- OS Version: macOS 14.3.1

Steps to Reproduce:

1. Open Keyboard Shortcuts and find this shortcut which bind to `command + backspace` by default.
<img width="1250" alt="image" src="https://github.com/microsoft/vscode/assets/143488669/e70a225a-386f-4ed1-afdc-4dfd25c6388c">
2. Customize the shortcut for deleting file(I customize it to `command + d`).
<img width="1248" alt="image" src="https://github.com/microsoft/vscode/assets/143488669/5cc63acd-dfdb-4086-8639-ace6376b0c3d">
3. Delete a file with shortcut `command + d`,  nothing happens.

**Comment by ulugbekna** [comment]
Hi 🙂

Thanks for filing this issue! 

Could you please try the [following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

1. Run the command "Developer: Toggle Keyboard Shortcuts Troubleshooting" (you can, for example, run it from the Command Palette). 

   This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.

2. Press exactly the keybinding you desire
 
3. Check what VS Code detects

If you are having trouble understanding the output, please feel free to paste here and we'll be happy to help ☺️
