### ISSUE TITLE
Decorators missing in file explorer when applying patch

### ISSUE THREAD

**Issue by b-lawlor** [microsoft/vscode#210098]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.88.0
- OS Version: Windows 11 Pro 23h2 (using WSL2)

VS Code recently stopped showing me decorators in the file browser when I apply patches to my local repository clone even though it shows the outgoing changes to master in the Source control tab.

There's a lot going on in my set up so it's hard to list exact steps to reproduce:
I'm using Docker, with a clone of a remote git repository
From the container's shell, I'm using git bz to apply a patch from bugzilla
Previously when I applied a patch, I used to see decorators in the VS Code file explorer for the files that the patch modified
Now I don't see any decorators in the file explorer, but in the Source control tab I see the list of modified files under outgoing changes to master
If I browse to the files in VS code file explorer I can see that the changes are there

**Comment by tjhorner** [comment]
May be related to #209641

**Comment by b-lawlor** [comment]
I think I just misunderstood what the decorators were showing. I thought that if I applied commits I would see those as modfied files in my local repo, but since those are actually committed changes they don't show with a decorator.

It would be cool if you could have a decorator to indicate the most recent commit, but I can see that in the Source control tab so it's not really an issue.
