### ISSUE TITLE
multiple node selection of treeView , does not show commands which are supported by all selected nodes

### ISSUE THREAD

**Issue by ajaygera** [microsoft/vscode#210046]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.88.0
- OS Version:  windows 11

Steps to Reproduce:

1) We have created treeview by following sample - https://github.com/microsoft/vscode-extension-samples/blob/main/tree-view-sample/src/testViewDragAndDrop.ts
2) For vscode.TreeItem We have defined different set of commands , to be shown on right click on node based upon context value set in package.json.
3) We have also enabled multiple node selection
4)Now we selected 3 nodes, lets say first node support three commands (c1, c2 and c3) , second node support two commands c1 and c2 and third node support one command c1
5) We right clicked first node , its shows all three commands supported by selected node (c1, c2 and c3) rather than showing commands which are supported by all nodes selected so in this case it should show only c1 command because it is supported by all nodes.
What needs to be done to show only commands which are supported by all nodes selected by  user?

**Comment by ajaygera** [comment]
Thanks for the merge.
Could you please update in which vscode version these changes would be available?

**Comment by alexr00** [comment]
This issue was fixed in the April milestone, which means it should go out in the April release at the beginning of May (next week).

**Comment by ajaygera** [comment]
ok thanks for update

**Comment by rzhao271** [comment]
Hi @ajaygera, could you verify that the fix works for you using [VS Code Insiders](https://code.visualstudio.com/insiders/)?

**Comment by connor4312** [comment]
It seems that now the context menu always uses the context keys for the selected item, even when opening the menu on an item not part of the selection:


https://github.com/microsoft/vscode/assets/2230985/62ae9ebd-4410-46b3-8e3f-d94296914629

Code https://github.com/microsoft/vscode-extension-samples/tree/connor4312/issue-210046/tree-view-sample

**Comment by alexr00** [comment]
@connor4312 that's the behavior I intended. Do you find it to be unexpected?

**Comment by alexr00** [comment]
Discussed during standup, and the proper behavior should be:
- When the right click occurs within the selection, show context menu actions that apply only to the entire selection. The command should get the selection as an argument.
- When the right click occurs outside the selection, show only context menu actions for the right click target. The command should not receive the selection as an argument.

**Comment by connor4312** [comment]
yep, that's the behavior I would expect, thanks!

**Comment by ajaygera** [comment]
@alexr00 this is fixed. 
Thanks a lot for quick resolution.
I am sorry for late reply as I was out of town and i was not having access to internet.
I will update in case i need more info/support on this
