### ISSUE TITLE
Cut-off button in keybindings editor when enabling minimal

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#21006]
- VSCode Version: Code - Insiders 1.10.0-insider (25c55638340197fc9c8767aba9d32a0c29ccf68a, 2017-02-21T07:04:55.691Z)
- OS Version: Darwin x64 15.6.0

---

Steps to Reproduce:

1. enable minimap in settings
2.  Command palette > Preferences: Open Keyboard Shortcuts

![screen shot 2017-02-21 at 10 02 14 am](https://cloud.githubusercontent.com/assets/4674940/23177842/2f34f008-f81d-11e6-92ad-84a7dccb855a.png)

**Comment by ramya-rao-a** [comment]
Isnt this duplicate of #20936?

**Comment by alexandrudima** [comment]
:+1:
