### ISSUE TITLE
extensionHost debug session does not end after restart

### ISSUE THREAD

**Issue by Septh** [microsoft/vscode#210087]
Type: <b>Bug</b>

1. Scaffold a new extension as instructed [here](https://code.visualstudio.com/api/get-started/your-first-extension)<br>
```bash
npx --package yo --package generator-code -- yo code
```
2. Open the project in VS Code and press `F5` to start a debug session.
3. Either click the `Restart` button in VS Code or run the `Developer: Reload Window` command in the extension host.
4. Either click the `Stop` button in VS Code or close the extension host window.

### Actual result
The debug session does not end (and cannot be ended in any other way than reloading the window).

### Expected result
The debug session should end.

VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700K (20 x 3610)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (19.78GB free)|
|Process Argv|--crash-reporter-id 365a2674-a228-4abd-82c2-408321056497|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|2.0.4
vscode-toggle-quotes|Bri|0.3.6
vscode-better-align|cho|1.4.2
vscode-eslint|dba|2.4.4
gitlens|eam|14.9.0
vscode-projects-plus|fab|1.24.0
vscode-todo-plus|fab|4.19.1
seito-openfile|Fr4|2.2.0
remotehub|Git|0.62.0
vscode-pull-request-github|Git|0.86.1
vscode-position|jtr|1.1.2
indentation-level-movement|kai|1.2.1
git-graph|mhu|1.30.0
remote-wsl|ms-|0.88.0
extension-test-runner|ms-|0.0.9
remote-repositories|ms-|0.40.0
sort-lines|Tyr|1.11.0
vscode-conventional-commits|viv|1.25.0
vscode-icons|vsc|12.7.0
pretty-ts-errors|Yoa|0.5.4

</details>

**Comment by roblourens** [comment]
Fixed in Insiders: https://github.com/microsoft/vscode/issues/203472
