### ISSUE TITLE
Invalid shortcuts formating in the menu

### ISSUE THREAD

**Issue by mquandalle** [Microsoft/vscode#21005]
- VSCode Version:  1.10.0-insider (2017-02-17T13:40:32.566Z)
- OS Version: Ubuntu 16.10

![VSCode insiders ubuntu menu](https://cloud.githubusercontent.com/assets/1730702/23176724/a16f2804-f864-11e6-86e2-3dd6971c9143.png)

On the above screenshot the shortcuts in the red rectangle aren't formatted as the others.

**Comment by bpasero** [comment]
@mquandalle there is nothing we can do about it at the moment, electron only allows some keybindings to show up as native keybindings.
