### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by IsmaelJ13** [microsoft/vscode#210078]
Type: <b>Bug</b>

As I was in terminal I was transfering over to bash from powershell, then I went back to powershell to exit which is what I typed hoping to, I guess shut it down and it worked. Then I typed in bash "ls -1" files on my computer came up and stuff like that. So then I wanted to clear everything and start typing in something new. I typed in "clear" pressed enter it didnt clear, then I was like let me just exit and reopen it since its my first time even opening gitbash on vs code and I wanna know how to do it so then I type "exit" and ther terminal shut down on me after it evn cleared everything. I was almost hesitant to type a new command but then everything shut down and when I got to tereminal -- New Terminal it bring me to my search bar and no new termianl is opeing. 

Im on the vscode website right now trying to see if I can fix it on myside  

VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i3-12100F (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (2.60GB free)|
|Process Argv|--crash-reporter-id af14516d-e415-4d09-b3e7-b11c2be76482|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
LiveServer|rit|5.7.9

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30993540
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

**Comment by IsmaelJ13** [comment]
Got it ! Appreciate you ! Sent from my iPhoneOn Apr 10, 2024, at 12:42 PM, Megan Rogge ***@***.***> wrote:﻿
It looks like your report is missing some important information, See this wiki page for more info on how to report actionable terminal issues.
