### ISSUE TITLE
Minimap in output panel does not immediately respond to theme change

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#21007]
- VSCode Version: Code - Insiders 1.10.0-insider (25c55638340197fc9c8767aba9d32a0c29ccf68a, 2017-02-21T07:04:55.691Z)
- OS Version: Darwin x64 15.6.0

---

Steps to Reproduce:

1. enable minimap in settings
2. open output panel
3. change theme

See below. Resizing fixes the issue.

![2u4lb1amri](https://cloud.githubusercontent.com/assets/4674940/23178081/fdcfdc34-f81d-11e6-9a94-889e4faf6282.gif)

**Comment by bpasero** [comment]
Should minimap be disabled in output? Not sure people would expect it there.

**Comment by kieferrm** [comment]
My initial reaction was surprise as I didn't expect a minimap there. But then I found myself using it to navigate the git and typescript output log. Thus, I'm now on the edge whether or not I want it there.

**Comment by alexandrudima** [comment]
I'm not sure, we can leave it in for now and make a separate output setting if people hate it there. I have already removed it from the diff editor (we should perhaps revisit there, we could render the two minimaps next to each other and have a better diff outline, but that is a separate feature), and in the embedded editors (such as find all references).

**Comment by alexandrudima** [comment]
To verify, you can use any plain text file (that doesn't have a TM syntax) and switch themes (i.e. not just the output)

**Comment by kieferrm** [comment]
@alexandrudima works well.
