### ISSUE TITLE
Terminal closes sometimes when re-opening VSCode

### ISSUE THREAD

**Issue by Kokujou** [microsoft/vscode#210019]
Type: <b>Bug</b>

I'm experiencing this issue now for quite some time.
i'm working with a workspace. and in the workspace file i registered an automated task. (it's tsc command that watches the whole folder for "build" errors), in case it's needed:
```json
"tasks": [
            {
                "label": "Check for build errors",
                "type": "shell",
                "command": "./node_modules/.bin/tsc",
                "args": ["-p", "./jsconfig.json"],
                "presentation": {
                    "reveal": "never",
                    "echo": false,
                    "focus": false,
                    "panel": "dedicated",
                    "clear": true,
                    "revealProblems": "never",
                    "showReuseMessage": false
                },
                "problemMatcher": "$tsc-watch",
                "isBackground": true,
                "runOptions": {
                    "runOn": "folderOpen"
                }
            }
        ]
```

now i'm also using a second terminal that i open manually, for things like git commands or npm install or such stuff.
i never manually close this second terminal, but a lot of times when i open VSCode it's still closed. 
but ideally VSCode would remember that i had 2 terminals open and preserve them on restart.

VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.17763
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6246 CPU @ 3.30GHz (8 x 3292)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|20.00GB (14.07GB free)|
|Process Argv|--crash-reporter-id bf054940-8a82-4911-8d88-4d53d2c903c5|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
es6-string-css|bas|0.1.0
lit-html|bie|1.11.1
vscode-html-css|ecm|2.0.9
lit-lang|ego|0.0.7
prettier-vscode|esb|10.4.0
vscode-firefox-debug|fir|2.9.10
generate-switch-case-for-enum-type|her|0.0.10
open-all-files|log|0.0.8
csharp|ms-|2.23.15
vscode-dotnet-runtime|ms-|2.0.3
powershell|ms-|2024.2.0
docthis|oou|0.8.2
lit-plugin|run|1.4.3
blueprint|tea|3.0.0
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572
945dj816:31013170

```

</details>

**Comment by meganrogge** [comment]
this setting `terminal.integrated.persistentSessionReviveProcess` should help you

**Comment by Kokujou** [comment]
i switched it from onExit to OnExitOrWindowClose, let's see if that helps, i'll observe it and report back if it happens again, thanks :)

**Comment by Kokujou** [comment]
> this setting `terminal.integrated.persistentSessionReviveProcess` should help you

sadly it didn't. i applied it both at workspace level and in the VSCode settings. then i restarted. simply closing it... and the second terminal is closed again. so there's still some stuff happening.
