### ISSUE TITLE
Option to show project path in title bar

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#21002]
In viewing the new options in 1.10.0 for display in the window titlebar, I would rather see the path **within my project**  (or "appName" as you call it) instead of the full disk path.

For example, for an open file like
`/Users/stevelombardi/github/designsystem-3/app/assets/sass/documentation/_content.scss`
I don't need to see `/Users/stevelombardi/github/` as every project has that.  

However, seeing this in my titlebar might be helpful: 
`designsystem-3/app/assets/sass/documentation/_content.scss`
So I can see where **in my app** this file is.

I see no way to configure this.

**Comment by bpasero** [comment]
Good suggestion, I added `${activeFilePathRelative}`. Together with `${rootName}` it would allow to compose a title of `designsystem-3/app/assets/sass/documentation/_content.scss` by setting window.title: `${rootName}/${activeFilePathRelative}`
