### ISSUE TITLE
Git multi-diff can't be closed automatically when staged or commited

### ISSUE THREAD

**Issue by g-plane** [microsoft/vscode#210028]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0
- OS Version: Linux

Steps to Reproduce/verify:

1. Make some changes to several files in a Git repository.
2. Open "Multi-diff" in Source Control view.
3. Stage all files.
4. The "Git: Changes" editor tab won't be closed automatically, leaving with a tab title that contains `(0 files)`. Expected behavior is that the tab should be closed automatically when staged changes or commited changes, as "Single-diff" does.

**Comment by hediet** [comment]
I think this should at least be behind a setting.
The multi file diff editor should show a message though that there are no changes to show.

**Comment by g-plane** [comment]
It already re-uses the `"git.closeDiffOnOperation"` setting. When this setting is `false`, the tab won't be closed.
