### ISSUE TITLE
Diff editor shows  "No changes" overlay

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#210077]
* have a diff editor with true changes
* modify the document so that they become identical
* 🐛 the diff editor shows a weird overlay

<img width="705" alt="Screenshot 2024-04-09 at 16 20 40" src="https://github.com/microsoft/vscode/assets/1794099/77e22a09-46f5-423d-ab86-639240988c9c">

**Comment by hediet** [comment]
Duplicate of #210077, which is fixed by now.
