### ISSUE TITLE
Kingsoft Cloud CDN access quality is very bad

### ISSUE THREAD

**Issue by WitherZuo** [microsoft/vscode#210012]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.89-Insider
- OS Version: Windows 11 Insider Preview 26100.1 (ge_release)

In mainland China, downloading or updating VS Code from Kingsoft Cloud CDN access quality is very bad, download speeds are almost non-existent and the download success rate is extremely low, even close to zero.

Steps to Reproduce:

1. Open CMD or PowerShell, type `curl -s https://update.code.visualstudio.com/latest/win32-x64/insider` to get the latest download link.  
2. Copy the link and type `curl -O <copied-download-link>` and see download speed, it almost is 0.  

Microsoft Azure has a proxy operator in mainland China, which is called 21Vianet aka 世纪互联 [www.azure.cn](www.azure.cn). Previously, the VS Code download CDN in mainland China (`vscode.cdn.azure.cn`) was provided by this company, so maybe we can consider cooperating with it?

**Comment by WitherZuo** [comment]
Screenshot:  

![图片](https://github.com/microsoft/vscode/assets/25317916/e20dc798-49f9-4939-8829-78df5cc1f11d)

**Comment by burgerezgo** [comment]
@WitherZuo , can you please give more detail? which city in China that you tested from? and can you please share your testing enviornment? such as carrier company name?

**Comment by WitherZuo** [comment]
> @WitherZuo , can you please give more detail? which city in China that you tested from? and can you please share your testing enviornment? such as carrier company name?

Hi, I tested this in Beijing, ISP is Beijing Unicom (北京联通), I don't have any carriers, only directly connect to this link.  

Sometimes the download speed can keep between 3 MB/s and 7 MB/s, and sometimes just don't have speed at all and stay at 0 KB/s, wait 1 to 2 minutes and then failed to download, as shown in the image above.

**Comment by burgerezgo** [comment]
Maybe you can try again for this same content. The issue from your screenshot looks like the network issue from your place (your last mile) to Kingsoft Cloud Edge. I have tried it on my end (Beijing), it can be downloaded easily with full content in a couple mins.
