### ISSUE TITLE
Custom labels for workspace folders

### ISSUE THREAD

**Issue by CaseyB** [microsoft/vscode#210197]
I understand this may be a niche case but I'm working on a project spread out over a large code base so I've set up a workspace with the folders that I need regular access to. The problem is that all of the folders are named the same thing, they're just at different places in the tree.

![Screenshot 2024-04-11 at 2 24 23 PM](https://github.com/microsoft/vscode/assets/356140/00899d12-a3f8-4791-afef-54c3440443f7)

I would love to be able to add custom labels so I know which one is which. Maybe something like this:

![update Screenshot 2024-04-11 at 2 24 23 PM](https://github.com/microsoft/vscode/assets/356140/74a3055b-ab06-49c4-ac41-beafa9002bfe)

**Comment by gjsjohnmurray** [comment]
https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file-schema for how the `name` property can help you.
