### ISSUE TITLE
Not all "Marks" are shown on the minimap when file is opened.

### ISSUE THREAD

**Issue by B4Ytaddeic** [microsoft/vscode#210150]
Type: <b>Bug</b>

In any file containing "// MARK: ..." type of comments, the minimap sometime does not show all marks when the file is first opened. 

Only marks in the few first lines of the file and those who are currently visible in the editor are correctly displayed.

As soon as the file is modified (note I am using autosave), the minimap reloads correctly.

VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.86GB (1.90GB free)|
|Process Argv|--crash-reporter-id c57a236b-4bc8-400b-bac1-83b2e0b115b1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-neovim|asv|1.8.1
prettier-vscode|esb|10.4.0
vscode-drawio|hed|1.6.6
csdevkit|ms-|1.4.29
csharp|ms-|2.23.15
vscode-dotnet-runtime|ms-|2.0.3
vscodeintellicode-csharp|ms-|2.0.25
js-debug-nightly|ms-|2024.4.817
trxviewer|sca|1.0.3
sonarlint-vscode|Son|4.4.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r3:30993539
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
g1icg217:30999571
da93g388:31013173

```

</details>

**Comment by ScriptBloom** [comment]
Hi, @B4Ytaddeic it's a duplicate issue.

The same issue at: https://github.com/microsoft/vscode/issues/209603

And it has been fixed with PR at: https://github.com/microsoft/vscode/pull/209605 which has been merged yesterday.
