### ISSUE TITLE
Select Discard Changes not on the window with VSCODE Running (with multi monitor)

### ISSUE THREAD

**Issue by tserhere** [microsoft/vscode#210112]
Type: <b>Bug</b>

Use a Pc, with a couple of monitors
Use a Project with Git Source control
Change a file
modify it
Save it
Go to Source Control
Go to changes
Select Discard Changes
***BUG****
The "Are you sure you want to discard changes in..." is  often not displayed centred in the VSCode screen, but as a old popup somewhere on one of the other screens

VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13850HX (28 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.69GB (36.89GB free)|
|Process Argv|--crash-reporter-id f947e526-ce45-491b-9f36-a510f0ac5a67|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.4
gitlens|eam|14.9.0
gitlab-workflow|Git|4.8.0
hcl|has|0.4.0
svg|joc|1.5.3
vscode-docker|ms-|1.29.0
debugpy|ms-|2024.4.0
python|ms-|2024.4.0
vscode-pylance|ms-|2024.4.1
remote-containers|ms-|0.354.0
remote-wsl|ms-|0.88.0
cmake-tools|ms-|1.17.17
vscode-jest|Ort|6.2.3
phind|phi|0.25.0
vscode-yaml|red|1.14.0
markdown-preview-enhanced|shd|0.8.13
sonarlint-vscode|Son|4.4.2
pdf|tom|1.2.2
cmake|twx|0.0.17
gitblame|wad|10.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
g1icg217:30999571
jg8ic977:31013176

```

</details>

**Comment by lszomoru** [comment]
@tserhere, is this issue specific to source control modal dialogs or any modal dialogs in VS Code? You can verify that by disabling auto-save, modifying a file and then try to close it. Thanks!

**Comment by tserhere** [comment]
That also opens in the other display. What i mean is and wanted to get the discission on going...... Vscode is showing the "legacy" behaviour of Windows, regarding to dialog boxes, when it comes to multi monitor. 
Move  vscode to the non-main display. Then the fastest way to reproduce is the Menu [Help] -> About option. You will see that dialog pop up in the Main display, Rather then how more modern  applications behave. (Like the new Windows 11 Notepad ) does.

For example , type something in the famous windows notepad application, then press the close tab options and you will see that the dialog is  shown in the same screen as notepad is.

Now, you could off course consider that  vscode is "behaving by design", but i think, the desktop landscape has evolved into the expectation that popups, related to an application you use, appear on the same screen :-))

And you sure don't want to brag the notepad team that their application is more modern than vscode!

**Comment by lszomoru** [comment]
@deepak1556, could you please take a look at this one? Thank you!

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/85898
