### ISSUE TITLE
Failed debugging python: Missing first part of previous command after ^C input during Python debugging in VSCode

### ISSUE THREAD

**Issue by Qy55** [microsoft/vscode#210155]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0
- OS Version: Windows 11 23H2

Steps to Reproduce:

- When debugging python code using git bash in the terminal in vscode, every second debugging, after ^C (i think this is ctrl + c) is entered in the terminal, debugging is executed with the command with the first part of the command removed from the previous debugging command.

- After this, a timed out waiting for launcher to connect error occurs.

- This did not occur when I downgraded to version 1.87.2 and tested it.

### Screenshot
1. first run and debug (Normal)
![image](https://github.com/microsoft/vscode/assets/46524989/5f1c06ae-797f-4a16-8b54-cb110ce732b1)

3. second run and debug (abnormal)
![image](https://github.com/microsoft/vscode/assets/46524989/5358c008-b0e3-485b-9089-95a689f8d509)

5. error alert window after second run
![image](https://github.com/microsoft/vscode/assets/46524989/f1e495d0-0add-4deb-8e7c-05d4aa9f8f32)

**Comment by Cornpop456** [comment]
Same with c++ and git bash
![2024-04-13_10-17-00](https://github.com/microsoft/vscode/assets/19603736/7308d85b-b416-46b9-a65b-3c1095ec8083)
![2024-04-13_10-17-24](https://github.com/microsoft/vscode/assets/19603736/4bd77a7a-feca-46bb-ab94-61586c08db34)

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/209341
