### ISSUE TITLE
Highlighter Issue

### ISSUE THREAD

**Issue by AlmondRyan** [microsoft/vscode#210151]
Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: 1.88.0
- OS Version: Windows11 23H2, Build 22631.3447

I am reading the QScintilla Code via VSCode, and I see a C++ Identifier is highlighted as Keyword.
This `classname` should be highlighted as identifier, but it's got the `class` keyword and highlighted as Keyword not identifier.
And when I restart VSCode, it's occurs again.
![image](https://github.com/microsoft/vscode/assets/142479613/9b0c9942-1e96-49a1-bd4e-a817d3f9d2ad)

And these are codes I see:
```Cpp
static QAccessibleInterface *factory(const QString &classname, QObject *object) {
    if (classname == QLatin1String("VBase") && object && object->isWidgetType())
        return new Base(static_cast<QWidget *>(object));

    return 0;
}
```

**Comment by RedCMD** [comment]
semantic highlighting affecting `&classname`

**Comment by alexr00** [comment]
@RedCMD I see this even when I don't have the C++ extension installed. It doesn't appear to be related to semantic highlighting.

**Comment by alexr00** [comment]
Moved to the upstream repo: https://github.com/jeff-hykin/better-cpp-syntax/issues/656
