### ISSUE TITLE
Make ctrl-enter focus current single find match

### ISSUE THREAD

**Issue by qpwo** [microsoft/vscode#210183]
* **Goal: The single most common thing I want to do after searching is put the cursor on the current find match.** This should be easier.
* **Current state**:
  * You can ctrl-e an editor selection then ctrl-g to find next, but you can't type in something and jump to it without editing the file.
  * You can select _all matches_ with alt-enter from search box, but you can't select or focus on _one match_.
  * f4 only works in multifile search
  * To put the cursor on the current match via keyboard, you have to install an extension, write a custom command, and write a new custom keyboard shortcut. [see here](https://stackoverflow.com/questions/58968729/vscode-keyboard-shortcut-to-navigate-from-search-bar-to-highlighted-selection)
* **Solution: make ctrl-enter put the cursor on the current find match instead of entering a newline** (I almost never want to enter a newline in the search box, and if I really need to, then I can copy-paste.)

**Example**: pressing ctrl-enter here should put the cursor before after the 'b' on line 2:

![image](https://github.com/microsoft/vscode/assets/10591373/2714eb5e-8dab-45f5-8212-03a9f9748c1f)

**Comment by qpwo** [comment]
Alternative solution: make ctrl-d / cmd-d from search box also move the focus

**Comment by qpwo** [comment]
Other keywords for future googlers:

* focus cursor on current single find match
* move cursor to found line
* select only one match instead of all matches

**Comment by ArturoDent** [comment]
Just to note: as mentioned in that SO you could hit `escape` and that will select the current find match.  But it will also close the Find Widget so if you wanted to return to the find widget you would have to ctrl+f again.  So I don't know if that is exactly what you want...

**Comment by qpwo** [comment]
My reading comprehension strikes again. Thank you.
