### ISSUE TITLE
Cannot create procedure in MySQL

### ISSUE THREAD

**Issue by DanAlphabet** [microsoft/vscode#210193]
ADD ISSUE DESCRIPTION HERE

Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
Embedder: codespaces

When I attempt to create a procedure (shown below), and click 'run', I receive feedback that it was executed successfully. Then, when I call that same method, I receive an error saying that the procedure does not exist. I made sure that the procedure that I created and the procedure that I'm calling have the same name. I cannot proceed with my homework assignment until I get passed this.

-- Problem 27
/*
delimiter //
create procedure prc_cust_add
(NCN in int, NCLN in varchar(30), NCFN in varchar(30), NCBAL in decimal(10,2))
begin
insert into CUSTOMER (CUST_NUM, CUST_LNAME, CUST_FNAME, CUST_BALANCE)
values (NCN, NCLN, NCFN, NCBAL);
end//
*/

call prc_cust_add (1002, 'Rauthor', 'Peter', 0);

**Comment by gjsjohnmurray** [comment]
Please use your course support channel.
