### ISSUE TITLE
Feature: disable specific copilot features

### ISSUE THREAD

**Issue by adam-savard** [microsoft/vscode#210182]
This stems from a specific feature that I find annoying: copilot is now autocompleting my commit messages, which I absolutely do not want it to do. I'd like the ability to turn off specific copilot features, especially that one.

**Comment by lszomoru** [comment]
Thanks for filing this issue. This is a recent regression that should be fixed soon.

**Comment by lszomoru** [comment]
A fix for this issue has been deployed. Please reopen the issue if you can still reproduce it.
