### ISSUE TITLE
Inconsistent wrapping behaviour

### ISSUE THREAD

**Issue by jackweinbender** [Microsoft/vscode#21017]
I'm getting some odd behaviour with wrapping. I'm not using a workspace settings file, but I have a global setting of `"editor.wrappingColumn": 75` 

Yet, I have two markdown files which display differently (this with `--extensions-disabled`). Please note, 

I'm running this on Arch (Antergos), but my Mac seems to behave the same way. 

Version 1.9.1
Commit f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
Date 2017-02-08T23:44:55.542Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

relevant settings:

    }
        "editor.wordWrap": true, // toggling `false` makes no difference
        "editor.wrappingColumn": 75
    }

![unwrapped](https://cloud.githubusercontent.com/assets/1544859/23178893/acf34990-f831-11e6-9e6d-bddd13742dd8.png)
![wrapped](https://cloud.githubusercontent.com/assets/1544859/23178897/b092c684-f831-11e6-9864-a54d2e61ae4b.png)

I don't think I'm misunderstanding the way these settings work. And, either way, with identical settings, shouldn't they at least render the same way?

**Comment by roblourens** [comment]
As far as I know, the first should be wrapped the same.

**Comment by alexandrudima** [comment]
Let's track in #21262. The wrapping settings are confusing and they will get an overhaul
