### ISSUE TITLE
Vertical postion randomly changes when some settings modified in the Settings Editor, Sometimes gone from my sight

### ISSUE THREAD

**Issue by dokcn** [microsoft/vscode#210169]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0
- OS Version: Windows 22H2(22621.3296)

Steps to Reproduce:

1. Open Settings Editor window.
2. Change some settings like check or uncheck checkbox.
3. This setting item leaves it's original position in vertical.

https://github.com/microsoft/vscode/assets/24841978/739dd087-61f0-47be-8dd2-9282ec9c369e

**Comment by dokcn** [comment]
Also happened when I switch to other tabs and return back.

**Comment by dokcn** [comment]
This is so inconvenient when I change a lot of settings at once.

**Comment by rzhao271** [comment]
I find it inconvenient as well, but haven't had the chance to look more into it yet.
Closing in favour of https://github.com/microsoft/vscode/issues/204207
