### ISSUE TITLE
[extensions] Add support for a RelatedFilesProvider

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#21018]
- VSCode Version: `1.10.0-insider` 25c55638340197fc9c8767aba9d32a0c29ccf68a
- OS Version: macOS Sierra `10.12.3 (16D32)`

I just put out a preview of a new extension [Find Related](https://marketplace.visualstudio.com/items?itemName=eamodio.find-related) to be able to quickly jump to files related to the current file. It currently has a tiny set of rules (hopefully will be quickly expanded), but it got me thinking that it could be nice if this was something that was baked into vscode.

So just like the other `*Provider` types an extension could register a new `RelatedFilesProvider` (or something similar) that would allow vscode to show a quick pick of the results (and other extensions could use for other reasons/UI)

Hopefully this make sense.

**Comment by jrieken** [comment]
@eamodio Can you give a sample?

**Comment by eamodio** [comment]
@jrieken sure. I'm assuming you mean use-case samples (but if not code-wise I was thinking it would be similar to the `CodeLensProvider`, but instead returning a set of something like a `QuickPickItem` with a `Uri` -- or something along those lines.

As for use-case examples, I work in Aurelia often and there are conventions (naming) for linking a ViewModel (js or ts) to its View (html), and you will very often jump between the 2. This had been requested of the vscode Aurelia extension https://github.com/aurelia/vscode-extension/issues/29.

dotnet has related files (designer/cs/resx/etc), aspnet has related files aspx/cs, aspnet mvc with controllers and views. And these are just some of the simple file convention based one. But related files could also aggregate attribute references, import statements in typescript/js, etc.

Does that make any more sense? Or am I just rambling? ;)

**Comment by jrieken** [comment]
Understood, I was thinking about the ts->js relation but wasn't sure we are on the same page. Makes sense, but not yet clear how it would look. Also we have some file setting to express that files are related, [this](https://github.com/Microsoft/vscode/blob/master/.vscode/settings.json#L9) is how we filter files from the explorer.

**Comment by eamodio** [comment]
Yeah, it could definitely go multiple ways -- another way I could see it is like the `DocumentSymbolProvider` -- so where you would get a list of "relations" with some more information about how they are related. Like `convention`, `imported`, `reference`, etc. That would be more decoupled from any UI implementation. Especially since while the just file rules are valuable, I think there could be deeper value provided by extensions that have a deeper understanding of the underlying code.

Heh, I just found out about those exclusion settings the other day -- now I need to update my [Toggle Excluded Files](https://marketplace.visualstudio.com/items?itemName=eamodio.toggle-excluded-files) extension to stop wiping those out ;)

**Comment by bpasero** [comment]
+1 for allowing an extension that knows all about a specific file type and language to provide the information about associated resources. Imho that is the only possible solution to requests such as https://github.com/Microsoft/vscode/issues/1567, https://github.com/Microsoft/vscode/issues/3546, https://github.com/Microsoft/vscode/issues/15370, https://github.com/Microsoft/vscode/issues/10097, https://github.com/Microsoft/vscode/issues/6328

There are some requirements throughout all those issues.

**Comment by jrieken** [comment]
Yeah, there is the related-model as sketched [above](https://github.com/Microsoft/vscode/issues/21018#issuecomment-282022374) and we need to define all the places in the UI where those things surface, like explorer, search etc

**Comment by eamodio** [comment]
FYI, I added an [extension api](https://github.com/eamodio/vscode-find-related/blob/master/README.md#extension-api) to my [Find Related](https://marketplace.visualstudio.com/items?itemName=eamodio.find-related) extension. While this looks nothing remotely like an API that would be provided by vscode, it could provide a playground to see some aspects (but certainly not all as mentioned in the other issues above) of what a vscode api would need to support.
