### ISSUE TITLE
Documentation request: Clarify how to ping to re-open tickets

### ISSUE THREAD

**Issue by jbcpollak** [microsoft/vscode#210170]
When [an issue is closed](https://github.com/microsoft/vscode-remote-release/issues/3697) the [VSCodeTriageBot](https://github.com/VSCodeTriageBot) replies with:

> We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

Following the link has this tid-bit:

> If you feel your feature request deserves to stay open, improve your use case or gather more up-votes. Then ping us and we'll consider reopening the feature request.

which adds a bit more information. But neither gives clear and explicit instructions on how to ping the team. I assume the closed issue is no longer reviewed or tracked, so it would be helpful if the documentation could be updated to clarify how to reach out.

**Comment by aeschli** [comment]
Normally you would just ping the person that is currently assigned to the issue.
If there's no assignee set, I suggest to look out for a VS Code committer that replied in the issue. Or file a new issue.
