### ISSUE TITLE
Toolchain download issue

### ISSUE THREAD

**Issue by Aetheris-Guido** [microsoft/vscode#210160]
Type: <b>Performance Issue</b>

I have been trying to download a toolchain at all hours of the day. For a while it will go somewhat, but then it will halt.
 
nRF Connect SDK Toolchain v2.6.0

It will not finish. The most I have seen is about 75%. Usually it halts at 10% to 15%.
What can I do to download this toolchain?

VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3403)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (12.37GB free)|
|Process Argv|--crash-reporter-id 5a7bf81f-c974-446e-b996-c125dd625083|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    98	  9204	code main
    0	    27	   848	   crashpad-handler
    0	    91	  4448	window [2] (Issue Reporter)
    0	   110	  4712	   gpu-process
    0	    40	  7576	   utility-network-service
    0	   153	  8500	window [1] (Welcome - Visual Studio Code)
    0	   172	  8564	extensionHost [1]
    0	    10	  6660	     c:\Users\Guido\.vscode\extensions\nordic-semiconductor.nrf-connect-2024.3.25-win32-x64\platform\nrfutil\bin\nrfutil-toolchain-manager --json install --ncs-version v2.6.0
    0	    10	  5596	       C:\Windows\system32\conhost.exe 0x4
    0	    17	 10612	     c:\Users\Guido\.vscode\extensions\nordic-semiconductor.nrf-connect-2024.3.25-win32-x64\platform\nrfutil\bin\nrfutil-device --json list --hotplug --traits seggerUsb
    0	    10	 10628	       C:\Windows\system32\conhost.exe 0x4
    0	    12	 11128	     c:\Users\Guido\.vscode\extensions\ms-vscode.cpptools-1.19.9-win32-x64\bin\cpptools.exe
    0	     3	 10356	       "c:\Users\Guido\.vscode\extensions\ms-vscode.cpptools-1.19.9-win32-x64\bin\cpptools.exe"
    0	    10	 11244	       C:\Windows\system32\conhost.exe 0x4
    0	   103	  9332	shared-process
    0	    80	  9352	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.19.9
nrf-connect|nor|2024.3.25
nrf-connect-extension-pack|nor|2023.11.3
nrf-devicetree|nor|2024.3.78
nrf-kconfig|nor|2024.3.21
nrf-terminal|nor|2024.3.15
gnu-mapfiles|tro|1.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
9b8hh234:30694863
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572
f3je6385:31013174

```

</details>

**Comment by gjsjohnmurray** [comment]
Have you raised this with the authors of the nRF extensions you are using?

**Comment by Aetheris-Guido** [comment]
I have not. But the issue was resolved as soon as I used a vpn to download the extension. I have no clue as to why that would be required.
Issue resolved. Thanks for responding.
________________________________
