### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by PsyCommando** [microsoft/vscode#210190]
Type: <b>Bug</b>

The whole window crashes randomly since the last update within 5 minutes.
Seems to happen on javascript, css, and txt files. Might be linked to an extension?

![image](https://github.com/microsoft/vscode/assets/8772299/d9c6f307-e3c8-4ab0-ac79-2e9baf19dad4)

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (17.29GB free)|
|Process Argv|--crash-reporter-id 2a608d5b-36e5-41f4-83ed-9da348d1add0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|2.0.5
dmi-editor|ant|1.0.6
vscode-zipfs|arc|3.0.0
lolcode|arw|1.0.0
vscode-eslint|dba|2.4.4
vscode-html-css|ecm|2.0.9
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
vscode-git-history|fab|3.1.0
vscode-github-actions|git|0.26.2
compareit|in4|0.0.2
vscode-docker|ms-|1.29.0
csharp|ms-|2.23.15
vscode-dotnet-runtime|ms-|2.0.3
debugpy|ms-|2024.4.0
isort|ms-|2023.10.1
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
jupyter|ms-|2024.3.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.354.0
remote-wsl|ms-|0.88.0
cpptools|ms-|1.19.9
live-server|ms-|0.4.13
dm-langclient|pla|0.2.3
byond|ss1|2.0.0
auto-comment-blocks|sty|1.1.1
vscode-pets|ton|1.25.1

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572
f3je6385:31013174

```

</details>

**Comment by PsyCommando** [comment]
I've browsed the logs a bit, and saw a bunch of exceptions, but it's unclear if any of those have anything to do with the window crash. 

Here's one that seems new in the sharedprocess.log. Not sure how relevant it is?:
```
2024-04-11 16:49:44.384 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat 'c:\Users\Guill\.vscode\extensions\extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:\Users\Guill\.vscode\extensions\extensions.json.vsctmp'
    at r.create (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:53:30080)
    at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:53:30195)
    at i.fb (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:58:36500)
    at i.stat (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:58:28946)
    at async $.stat (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:58:16092)
    at async K.sb (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:108402)
```

**Comment by andreamah** [comment]
You can use `Help: Start Extension Bisect` to try to narrow down which extension it might be coming from.

**Comment by PsyCommando** [comment]
Alright, after running bisect for a while, I'm under the impression it's an extension that somehow isn't working on the new update and crashes the window. 
I might have to just revert the latest update.
