### ISSUE TITLE
option to disable non-workspace extension recommendations, or make it more clear which extension recommendations are not workspace recomendations

### ISSUE THREAD

**Issue by DetachHead** [microsoft/vscode#210119]
in my project, there are several extensions in our recommended `extensions.json`, but vscode sneaks in recommendations that are not recommended by workspace, but by vscode itself:

![image](https://github.com/microsoft/vscode/assets/57028336/5806c4ef-088b-4928-8c00-f49a250fd095)

in this screenshot, the WSL extension is recommended by vscode, and the YAML extension is recommended by the workspace. you have to hover over the star icon to figure out which recommendations are actually relevant for this workspace. this makes it confusing for new developers who just want to install the extensions required for the workspace, and not random additional ones that vscode suggests.

as a workaround, i can add these vscode recommendations to the `unwantedRecommendations` array, but that's annoying because i would have to update that list whenever new recommendations show up.

**Comment by sandy081** [comment]
VS Code shows workspace recommendations on the top followed by other recommendations. If you are not seeing in this order, can you please share the steps to reproduce?

**Comment by DetachHead** [comment]
i don't know if i could, since it seems to be some sort of recommendation algorithm that shows different results based on all sorts of unknown factors. (i feel like it'd be comparable to coming up with steps to reproduce an ad i saw in a social media feed.) but i'll give it a go

**Comment by DetachHead** [comment]
it seems that the docker and wsl extensions always appear above workspace recommendations.

steps to reproduce:

1. add `redhat.vscode-yaml` to the workspace recommended extensions
2. open a `Dockerfile` to trigger the non-workspace recommendation
3. go to the extensions tab and look at the recommended extensions list
    
    ![image](https://github.com/microsoft/vscode/assets/57028336/0efd1004-5c8f-4d34-91f5-19a020688cc5)
    ![image](https://github.com/microsoft/vscode/assets/57028336/06c6dd77-3e22-4056-ab1a-0a620c34583c)

----

even if these were showing up in the correct order (workspace recommendations first), it's still extremely confusing and misleading to the user to use the exact same icon for two completely different types of recommendations. i get that microsoft wants to get as many people using their extensions as possible, but this seems comparable to an advertisement that is not clearly labelled as one.

**Comment by sandy081** [comment]
I found out that there is a bug in showing them in the right order. Will fix that.

> it's still extremely confusing and misleading to the user to use the exact same icon for two completely different types of recommendations.

I am not sure how much it makes sense to show different icons for different kinds of recommendations. It might be super noisy or confusing. I believe at present we have a right balance to show an icon for recommendation and explanation on hover.
