### ISSUE TITLE
File opens two tabs with inconsistent edits in each?

### ISSUE THREAD

**Issue by nhrones** [Microsoft/vscode#21011]
Duplicate file tab opens on its own, with incorrect file-name capitalization, and showing corrupted/inconsistent/incomplete edits that were being performed in the originally opened tab.

- VSCode Version: 1.9.1
- OS Version: Windows 10

Steps to Reproduce:

1.  create ts file 'Container.js'
2.  add code and save
3.  rename the file using the vscode file explorer, to  ... 'container.ts' (changed cap C to lowercase c)
4.  open file in tab to make edits ... while editing code ...
5.  a new tab opens as 'Container.ts' with same content. ... two tabs (container.ts, Container.ts)
6.  while editing, each tab shows incomplete and inconsistent edits.
7.  often, closing the Container.ts file, then saving the container.ts file creates an error ...
     'File on disk is newer than file being saved.'
8.  Note: only one file exists in the file explorer window ... (container.ts)  
9.  renamed file 'container.ts' to 'newContainer.ts' and problem no longer exists

**Comment by nhrones** [comment]
I built a small project to attempt to reproduce the problem as described above, and was unable to reproduce this issue?  The original issue showed up in a large project. After renaming the file in the original project, using a unique name rather than just a capitalization change, no problems have been observed.
Again, I cannot reproduce this issue?

**Comment by bpasero** [comment]
@nhrones me neither, can you try again a bit more, would love to understand what is going on

**Comment by nhrones** [comment]
in my original project, after renaming the file to a new unique name, I'm
unable to reproduce the problem.  The problem seemed to be about renaming
with only a caps change?  If no one else has reported this, I would
disregard it.

**Comment by bpasero** [comment]
Sounds good.

**Comment by nhrones** [comment]
More info ... I had this happen again.
The issue is with the import statements.
The file name 'container.ts ' contains 'export default class Container implements iContainer {'
In several files the import is ' import Container from "./container" '
In a new file I had added an import that was  ' import Container from "./Container" '

During edits to container.ts, two edit tabs would open ... Container.ts and container.ts ... with each having inconsistent/partial edits.

The 'fix' again, was to rename the file and all import statements to consistent capitalization.

Hope this helps.

**Comment by bpasero** [comment]
@nhrones I pushed a fix today for https://github.com/Microsoft/vscode/issues/12448, can you see if this still reproduces with our insiders build from today:  You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
