### ISSUE TITLE
Bring back vertical splits!

### ISSUE THREAD

**Issue by calloncampbell** [Microsoft/vscode#21014]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|azuretoolsforvscode|bradygaster|1.2.1|
|vscode-svgviewer|cssho|1.3.1|
|net-core-project-manager|ksubedi|0.3.6|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|mssql|ms-mssql|0.2.1|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|azurerm-vscode-tools|msazurermtools|0.3.4|
|vscode-icons|robertohuertasm|7.2.0|
|guides|spywhere|0.6.1|

---

Steps to Reproduce:

1. Create new split editor

Seems like in the recent update the option for creating vertical splits has been removed and replaced with a horizontal split. Why can't we have both?

**Comment by Tyriar** [comment]
I think it was hidden on the UI to save some space. You can still toggle the editor group layout using alt+shift+1.

**Comment by calloncampbell** [comment]
Thanks Daniel but that doesn’t work.

Sent from my Windows 10 phone

**Comment by Tyriar** [comment]
Try searching for "editor group layout" in the command palette (f1)
