### ISSUE TITLE
IntelliSense loses types after closing file

### ISSUE THREAD

**Issue by hypervisor** [microsoft/vscode#210163]
Type: <b>Bug</b>

1. In a JS project, create a /types/something/mytype.d.ts file
2. Open this file and create a type inside a namespace, f.ex

```ts
declare namespace MyNamespace {
  interface MyType {
    itWorks: boolean;
  }
}
```

3. While keeping mytype.d.ts file open in a tab, open a new file and use JSDoc or something to use that type:
```
/** @type {MyNamespace.MyType} */
let x = { .. }
```
4. close mytype.d.ts file (still saved on disk, not modified, just close the tab)
5. See that IntelliSense no longer recognizes your namespace / type

VS Code version: Code 1.88.0 (Universal) (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:28:18.899Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 5, 4|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|. --crash-reporter-id e8d6b9ff-12c6-4e3e-9aea-5386702f30af|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
codewhisperer-for-command-line-companion|ama|0.1.0
Handlebars|and|0.4.1
vscode-tailwindcss|bra|0.10.5
hide-node-modules|chr|1.1.8
vscode-eslint|dba|2.4.4
gitlens|eam|14.9.0
prettier-vscode|esb|10.4.0
ilspy-vscode|ics|0.18.0
csdevkit|ms-|1.4.29
csharp|ms-|2.23.15
vscode-dotnet-runtime|ms-|2.0.3
vscodeintellicode-csharp|ms-|2.0.25
vscode-postgresql|ms-|0.3.0
debugpy|ms-|2024.4.0
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.14
makefile-tools|ms-|0.9.10
vetur|oct|0.37.3
vscode-extension-dmn-editor|red|0.26.0
vscode-xml|red|0.26.1
vscode-styled-components|sty|1.7.8
vscode-stylelint|sty|1.4.0
cmake|twx|0.0.17
volar|Vue|2.0.10
pretty-ts-errors|Yoa|0.5.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
gee8j676:31009558
dsvsc021:30996838
g1icg217:30999571
vstestc:31010171

```

</details>

**Comment by mjbvz** [comment]
This is expected if you are using globals variables and do not have a `jsconfig`/`tsconfig` projects. In this case only the opened files are considered

[Creating a `jsconfig`](https://code.visualstudio.com/docs/languages/jsconfig) will fix this, or adding a import/reference to the typings
