### ISSUE TITLE
Text Color Remains Black and Unreadable Across All Dark Themes

### ISSUE THREAD

**Issue by akikuno** [microsoft/vscode#210282]
In my environment (WSL2-Ubuntu), when I switch to the dark theme, the text color remains black, making it barely unreadable. This happens with all dark themes. I have not done anything to override the settings in vscode specifically for text color.

![image](https://github.com/microsoft/vscode/assets/15861316/99351802-a465-42e3-aa05-03b8d671e66e)

I apologize if this issue has already been discussed, but I would appreciate any guidance on how to address this problem.

- Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: 1.88.1 e170252f762678dec6ca2cc69aba1570769a5d39 x64
- OS Version: Ubuntu 22.04.4 LTS on Windows 10 x86_64

**Comment by okineadev** [comment]
hmmmmmm

**Comment by aeschli** [comment]
I can't reproduce on 1.89.0 insiders (WSL)

**Comment by sandy081** [comment]
Do you see this when you open VS Code locally - not connecting to WSL?
Do you see this issue when you open any markdown, say release notes?
Do you see this issue in all editors?

@mjbvz Any insights

**Comment by mjbvz** [comment]
Does this only happen after switching with the extension page already open? When if you try opening an extension page after switching themes?

**Comment by okineadev** [comment]
Most likely, the problem is in the color theme

**Comment by akikuno** [comment]
I deeply appreciate your comments.

After reviewing all of your comments, I rechecked  my `settings.json` and found a typo in `editor.fontFamily`. 

It was listed as `\"Consolas` instead of `Consolas`. After I removed the `\"`, the text color turned white in all Dark themes.

## Before (`\"`): Black font color
![image](https://github.com/microsoft/vscode/assets/15861316/cd72f74c-c114-45e9-8f2e-43196eefb788)

## After (Remove `\"`): White font color

![image](https://github.com/microsoft/vscode/assets/15861316/2840a5b3-d18a-461e-a7cd-936a43a6a15f)


I'm not sure why, but thank you very much for your assistance!

**Comment by okineadev** [comment]
It's good that everything was resolved.
