### ISSUE TITLE
Make Devin

### ISSUE THREAD

**Issue by avianion** [microsoft/vscode#210266]
I can't think of a company more qualified, with a large amount of usage, to make an AI Software within Vscode. You can create agents, with something similar to Github Copilot, that have their own Vscode environment, access to source control, a browser, internet etc.

**Comment by isidorn** [comment]
I think the GitHub next team is thinking about a similar concept https://github.blog/2024-04-29-github-copilot-workspace/

I will go ahead and close this issue, as it is best to reach out to the GitHub next team for this right now.
