### ISSUE TITLE
extra space to the left and right of the chat view

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#210244]
1. Use the panel chat
2. resize the activity bar width
3. there's increasing empty space to the left and right vs an expanded chat view

Might be fixed in Insider's? 

![Screenshot 2024-04-12 at 7 48 04 AM](https://github.com/microsoft/vscode/assets/29464607/3a7f36c2-0227-4a25-843e-75f87356649a)

**Comment by roblourens** [comment]
By design- reading a really long single line of text is less comfortable than reading something that wraps reasonably. The settings editor is layed out similarly
