### ISSUE TITLE
terminal chat codeblock actions don't work in accessible view

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#210256]
Reported by @jooyoungseo, open terminal chat, run a request that yields a code block.

Open the accessible view. 

Navigate to within the codeblock and use `ctrlCmd+enter`.

🐛 nothing happens

**Comment by meganrogge** [comment]
@jooyoungseo, I am wondering why you use the accessible view for terminal chat. It should almost always return just the command in a monaco editor, which is screen reader friendly.

**Comment by meganrogge** [comment]
Also discovered the terminal chat accessible view content is not correct

**Comment by anthonykim1** [comment]
https://github.com/user-attachments/assets/42611310-f93b-4b57-bd2b-984794bb00be
Believe it is working as expected now :)
