### ISSUE TITLE
"Restart extensions" flow resulting in error notification "Debug adapter process terminated unexpectedly (Extension host shut down)"

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#210236]
Repro: 

1. Start a (TS) debug session (F5)
2. Click on "Restart extensions" button in Extensions explorer - :bug:

<img width="483" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/468fae5f-bc96-43a5-b40d-4ddd85747588">

Expected behavior options: 

- ideal: resume debug session
- ask the user if it's okay for them to interrupt debug session and not show error notification ?

**Comment by connor4312** [comment]
> ideal: resume debug session

We can't generally do this because the debug session can be owned+managed by stateful code in the extension. Resuming the debug session requires starting it anew which would launch any program again, behavior that could be surprising to users.

**Comment by sandy081** [comment]
@connor4312 In core, you can also veto restarting extensions if there is a live debug session 

https://github.com/microsoft/vscode/blob/7bf27d553eac914ff1fb4ea05433161a664bbb49/src/vs/workbench/services/extensions/common/extensions.ts#L444

**Comment by connor4312** [comment]
Thanks, I'll have the session gracefully shut down when the extension host is restarted. Will tackle in debt week.
