### ISSUE TITLE
I want to cry

### ISSUE THREAD

**Issue by AnushkaHada** [microsoft/vscode#210274]
Type: <b>Bug</b>

I have updated mac, docker and visual studio code. For some reason visual studio code keeps telling me to download new version of docker over and over. The problem is that when I click on the link and download the one they want, it tells me its uncompatible with my mac. I want to cry. Every thing is updated, I have newer version of docker, but it don't work. why does it not work. please fix this. I have to do my assignment. 

VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id a9154335-9794-4512-af5a-457d02a13cb5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.86.0
flutter|Dar|3.86.0
bats|jet|0.1.10
remote-containers|ms-|0.354.0
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.9.10
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r3:30993539
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
g1icg217:30999571
01bff139:31013167

```

</details>

**Comment by hamirmahal** [comment]
> I have updated mac, docker and visual studio code. For some reason visual studio code keeps telling me to download new version of docker over and over. The problem is that when I click on the link and download the one they want, it tells me its uncompatible with my mac.

Can you upload a screen recording that shows all of this happening, including the dialog popups?

**Comment by AnushkaHada** [comment]
Hi, here's the video. After I click download the new version, it downloads
one that's incompatible with my mac.

**Comment by hamirmahal** [comment]
It looks like the video didn't get attached.

**Comment by AnushkaHada** [comment]
It seems you have to download it and then it will open. Does it work?

**Comment by hamirmahal** [comment]
I'm not seeing it on GitHub. Could you upload the video on GitHub directly? Attaching it via email might be causing issues.

**Comment by AnushkaHada** [comment]
I put it into a new repository on github.

**Comment by hamirmahal** [comment]
Okay, I'm going to reupload it here so people perusing this issue can get relevant context.

**Comment by hamirmahal** [comment]
https://github.com/microsoft/vscode/assets/43425812/d7939bdf-e191-4535-b31a-ebaa777f5d7f

**Comment by hamirmahal** [comment]
Is clicking `Reopen in Container` something you have to do?

**Comment by hamirmahal** [comment]
I usually use Docker in the command line, separately, while editing source files with VSCode.

**Comment by AnushkaHada** [comment]
Hi,
These were the instructions given. If I am able to get the same result
without "Reopen in Container" then that would be great. This is my first
time using visual studio code and docker.

**Comment by hamirmahal** [comment]
What were the full instructions given, and what's the intended result?

**Comment by AnushkaHada** [comment]
This are the instructions for the project.

**Comment by hamirmahal** [comment]
I don't see any instructions.

Can you drag and drop any attachments on GitHub, directly?

**Comment by hamirmahal** [comment]
Please just drag and drop files onto GitHub like so. You don't need to create a separate repository for standalone files.

[Screencast from 04-12-2024 07:21:14 PM.webm](https://github.com/microsoft/vscode/assets/43425812/0c2c08b1-8d32-4c73-af20-3c1d970706bc)

**Comment by AnushkaHada** [comment]
Hi,
Thank you for the help. I shall be using a different environment to do my
assignment since there seems to be no difference between this
environment and my original one. Appreciate your help and time.

**Comment by hamirmahal** [comment]
You're welcome!

**Comment by hamirmahal** [comment]
If there aren't any problems with `vscode`, you should probably close this issue so that the maintainers of this repository know that there isn't anything for them to investigate.

**Comment by grgar** [comment]
/causedByExtension vscode-remote-release

Plenty of possible dupes there e.g. microsoft/vscode-remote-release#5483

**Comment by Yoyokrazy** [comment]
Thanks for helping out everyone! Going to close this as out of scope for vscode :)

**Comment by hamirmahal** [comment]
You're welcome!
