### ISSUE TITLE
[Bug] VSCode.dev and virtual github workspace - Not empty deleted folders can not be recreated

### ISSUE THREAD

**Issue by daniela-mateescu** [microsoft/vscode#210218]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: vscode.dev

Steps to Reproduce:

1. Open a github remote repository 
2. Create a folder "myFolder" and a file "myFile.txt" inside "myFolder"
3. Delete "myFolder"
4. Recreate the folder "myFolder"
5. The creation fails with the  following error:
![image](https://github.com/microsoft/vscode/assets/4996054/17fa764a-38bc-4b63-b0ac-ee88ec56f4e2)

**Comment by cristian-spiescu** [comment]
I think it's the same as https://github.com/microsoft/vscode-remote-repositories-github/issues/130.

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode/issues/210218.

**Comment by cristian-spiescu** [comment]
Maybe you wanted to paste another link? It points to this task that you have just closed.

**Comment by chrmarti** [comment]
I meant https://github.com/microsoft/vscode-remote-repositories-github/issues/130. Thanks!
