### ISSUE TITLE
Add _javascript_1 file icon to seti icon theme

### ISSUE THREAD

**Issue by desean1625** [microsoft/vscode#210245]
Can we add test.mjs extension to seti icon theme?

This file extension is the default for node js test runner. 

It would be nice to have the same theming as the regular javascript for javascript modules https://github.com/microsoft/vscode/blob/3b3e8c2ebfbfe59b5ecef100e90c26b20f879a2a/extensions/theme-seti/icons/vs-seti-icon-theme.json#L1627

**Comment by aeschli** [comment]
We generate the seti theme from data in https://github.com/jesseweed/seti-ui.
Can you file an issue (or PR) there?
The addition is at https://github.com/jesseweed/seti-ui/blob/8eec7f2e37cd8fd91a98c61d129468bb49735a94/styles/components/icons/mapping.less#L343
