### ISSUE TITLE
When you open VS Code from the command line or open a file associated with VS Code, the command line window will return to the prompt and display the log, and closing the command line window will also cause VS Code to be closed.

### ISSUE THREAD

**Issue by huajingyu** [microsoft/vscode#210243]
Type: <b>Bug</b>

1. Open CMD or PowerShell.
2. In the window you just opened, enter code.exe to open VS Code or enter another file to open the file that has been linked to the VS Code file type.
eg. "test.html" or "code.exe"
3. The window that opens in the first step will redisplay the prompt and be ready to be entered, but will also output a log of VS Code.

PS C:\> 1.txt
PS C:\>
[main 2024-04-12T14:25:42.207Z] update#setState idle
[13360:0412/222548.311:ERROR:ssl_client_socket_impl.cc(975)] handshake failed; returned -1, SSL error code 1, net_error -101
....

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22621
Modes: Restricted

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/66750
