### ISSUE TITLE
TypScript error when opening a JavaScript file from a SharePoint 2010 site

### ISSUE THREAD

**Issue by Toadmyster** [Microsoft/vscode#21027]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|

---

Steps to Reproduce:

1. Start editor
2. Open a javascript file from a drive mapped to a SharePoint 2010 site
Then watch as warning that TypeScript died 5 times in the last 5 minutes continually slides down

**Comment by mjbvz** [comment]
Please try the latest vscode insiders builds. Typescript 2.2 should fix this.
