### ISSUE TITLE
Suggest widget height is calculated incorrectly

### ISSUE THREAD

**Issue by klaussner** [microsoft/vscode#210254]
## Issue description

The height of the suggest widget is calculated so that twelve elements are displayed, but I think the calculation is not quite correct because the height of the widget is too large:

![bug](https://github.com/microsoft/vscode/assets/1312807/1250d377-35ee-4477-917a-3e9118bff6f9)

Because of the two additional pixels, the list elements are shifting when scrolling down:

https://github.com/microsoft/vscode/assets/1312807/ece66535-515d-4754-839f-112db2247043

In the `getLayoutInfo` method, the border width (one pixel for normal themes, two pixels for high contrast themes) is included in the default height, but the `defaultSize` is later used to set the height of the list element *without* the border:

https://github.com/microsoft/vscode/blob/bcca025d403e13914b0b4e0f2fc20ecc298cb256/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L912

https://github.com/microsoft/vscode/blob/bcca025d403e13914b0b4e0f2fc20ecc298cb256/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L884

Here's another example with a high contrast theme:

![bug-hc](https://github.com/microsoft/vscode/assets/1312807/92f94a74-1d13-42ec-b9db-f833c4765432)

## Possible solution

I tried to remove the border from the calculation and the result looks better:

https://github.com/microsoft/vscode/assets/1312807/282b7511-c534-4084-a5c9-ebc5c1c27d50

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:43:08.196Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
Thanks @klaussner !
