### ISSUE TITLE
TS/JS server stop working 

### ISSUE THREAD

**Issue by mdongilli** [microsoft/vscode#210235]
Type: <b>Bug</b>

Open any of my workspaces and a notificatio with "JS/TS language service immediately crashed 5 times". tried to disable almost all extension to find conflicts but issue is still there.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:43:08.196Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 6|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id e4b69788-29b4-4f28-a917-a7baaa8e374f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (86)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
vscode-sqlite|ale|0.14.1
arm-debugger|Arm|1.1.1
environment-manager|Arm|1.1.13
keil-studio-pack|Arm|1.18.2
markdown-mermaid|bie|1.22.0
vscode-tailwindcss|bra|0.10.5
doxdocgen|csc|1.4.0
arm|dan|1.7.4
dart-code|Dar|3.86.0
flutter|Dar|3.86.0
vscode-eslint|dba|2.4.4
memory-inspector|ecl|1.1.0
peripheral-inspector|ecl|1.5.1
prettier-vscode|esb|10.4.0
vscode-expo-tools|exp|1.5.0
html-preview-vscode|geo|0.2.5
vscode-pull-request-github|Git|0.86.1
svgeditor|hen|2.9.0
rest-client|hum|0.25.1
vscode-ngrx-uml|imm|1.0.2
masm-runner|ist|0.4.5
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
break-from-comma|jza|1.1.6
vscode-sshfs|Kel|1.26.1
vscode-clangd|llv|0.1.28
cortex-debug|mar|1.12.1
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.25
peripheral-viewer|mcu|1.4.6
rtos-views|mcu|0.0.7
rainbow-csv|mec|3.11.0
document|min|2.2.1
vscode-docker|ms-|1.29.0
csdevkit|ms-|1.4.29
csharp|ms-|2.23.15
vscode-dotnet-runtime|ms-|2.0.3
vscode-edge-devtools|ms-|2.1.5
debugpy|ms-|2024.4.0
isort|ms-|2023.10.1
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
jupyter|ms-|2024.3.1
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.354.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.0
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.14
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
vscode-embedded-tools|ms-|0.7.0
vscode-react-native|msj|1.13.0
sqltools|mtx|0.28.2
sqltools-driver-mysql|mtx|0.6.1
parallels-desktop|Par|1.0.13
platformio-ide|pla|3.3.3
sqlite-viewer|qwt|0.3.13
java|red|1.29.0
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
salesforcedx-vscode-core|sal|60.8.0
salesforcedx-vscode-lwc|sal|60.8.0
stm32-vscode-extension|STM|2.0.1
vscode-3d-preview|tat|0.2.1
pdf|tom|1.2.2
gnu-mapfiles|tro|1.1.0
simple-rst|tro|1.5.4
cmake|twx|0.0.17
luna-paint|Tyr|0.16.0
vscode-lldb|vad|1.10.0
vscode-gradle|vsc|3.13.5
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.26.0
vscode-java-test|vsc|0.41.0
vscode-maven|vsc|0.44.0
vscode-preview-server|yui|1.3.0
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.6.2
linkerscript|Zix|1.0.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
g1icg217:30999571
724cj586:31013169

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
