### ISSUE TITLE
Test: Terminal Links

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21021]
https://github.com/Microsoft/vscode/issues/7321

- [x] Linux @joaomoreno 
- [x] macOS @kieferrm 
- [x] Windows @alexandrudima 

Complexity: 3

Terminals now add links for URLs and text that looks like a local path. Clicking URLs will open the default browser, clicking files will open the file in an editor. Note that folders will also be links but they will just not do anything, this behavior is expected.

Here are the specific text forms that will be "linkified":

- URLs qualified with `http://` or `https://`
- On Linux/macOS paths in the forms: `./x`, `../x`, `~/x`, `/x`
- On Windows paths in the forms: `.\x`, `..\x`, `~\x` (`~` points at `%HOMEDRIVE%\%HOMEPATH%`), `y:\x`. Windows links also allow mixed slashes, so `.\x\y`, `./x\y`, `./x/y` are all valid

**Comment by kirill-chilingarashvili** [comment]
Is it possible to disable links (make them plain text) from configuration?

**Comment by Tyriar** [comment]
@kirill-chilingarashvili not currently, I've been considering making them only active when ctrl is held similar to the editor though.
