### ISSUE TITLE
Add Extension Recommendation for TypeSpec language

### ISSUE THREAD

**Issue by RodgeFu** [microsoft/vscode#210221]
Hi, 

I am from Azure SDK team and we are now working on TypeSpec which is a language for describing cloud service APIs and generating code. (More detail can be found at http://typespec.io). We have already built a VSCode extension for it (id: typespec.typespec-vscode) and would like vscode to prompt it as a recommendation when user opens a TypeSpec file (i.e. *.tsp, tspconfig.yaml). So could anyone help to suggest what process or action we can do to make it recommendation? Thanks.

Thanks,
Rodge Fu

**Comment by isidorn** [comment]
Hi,

Thanks for working on the extension https://marketplace.visualstudio.com/items?itemName=typespec.typespec-vscode
It looks very interesting!
However, I see it is in preview. I would love us to recommend your extension, but would prefer once you get out of preview?
Can you share the roadmap of your extension? You can also reach out to me on Teams - inikolic. Thanks!

**Comment by mario-guerra** [comment]
Hi @isidorn, we think the extension is ready to move out of preview. Are there specific requirements we need to meet in order to move it out of preview?

**Comment by isidorn** [comment]
Well if you move your extension our of preview that affects your S360 review, since you are treated as "GA".
But from our side nothing is needed.

**Comment by mario-guerra** [comment]
Thanks @isidorn, can you tell me more about the S360 review? Is that a process we need to follow? We've not gone through the process of releasing an extension before and I don't know what an S360 review is.

**Comment by isidorn** [comment]
@mario-guerra S360 is a review process that any product needs to go through when releasing.
This is not special for extensions, but for all DevDiv products.
I suggest to reach out to Paul Chapman since his team owns this for DevDiv, and they can give you pointers.

**Comment by josefree** [comment]
@isidorn thanks, I dropped a mail to Paul asking for more details about the GA process.  Let me sync back here when there is any progress.

**Comment by josefree** [comment]
We have completed the compliance process. Can we regain the work?

**Comment by isidorn** [comment]
Thanks. I still see the extension marked as preview in the Marketplace https://marketplace.visualstudio.com/items?itemName=typespec.typespec-vscode
