### ISSUE TITLE
restart extensions button font is different than usual

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#210231]
Type: <b>Bug</b>

restart extension button font is different than usual
![image](https://github.com/microsoft/vscode/assets/9264813/851e6434-bc8f-46fa-b225-8579cd2de060)

VS Code version: Code - Insiders 1.89.0-insider (50a6f4f200c5a33f47997eb6a8966e50cf219e21, 2024-04-12T05:50:19.038Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (1.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|17.3.1
vscode-markdownlint|Dav|0.54.0
vscode-eslint|dba|2.4.4
githistory|don|0.6.20
gitlens|eam|14.9.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
output-colorizer|IBM|0.1.2
git-graph|mhu|1.30.0
vscode-scss|mrm|0.10.0
vscode-dotnet-runtime|ms-|2.0.3
vscode-edge-devtools|ms-|2.1.5
vscode-typescript-next|ms-|5.5.20240411
angular-console|nrw|18.19.0
vscode-yaml|red|1.14.0
sonarlint-vscode|Son|4.4.2
code-spell-checker|str|3.0.1
vscode-stylelint|sty|1.4.0
vscodeintellicode|Vis|1.3.1
vscodeintellicode-completions|Vis|2.0.0

</details>

**Comment by gjsjohnmurray** [comment]
Also when button label is "Update":

![image](https://github.com/microsoft/vscode/assets/6726799/52581e2a-c1b3-4fe0-8e1f-db7458cfb3a7)

Version: 1.89.0-insider
Commit: 50a6f4f200c5a33f47997eb6a8966e50cf219e21
Date: 2024-04-12T05:50:19.038Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.89.0-insider Chrome/120.0.6099.291 Electron/28.2.8 Safari/537.36

My experiments with DevTools suggest it's caused by an issue with the codicon font.

**Comment by gjsjohnmurray** [comment]
Possibly caused by #209131

**Comment by connor4312** [comment]
It looks like the buttons have the codicon class applied to them, even though (afaik) we never show codicons in those buttons. I'm guessing this is unintentional



![Image](https://github.com/microsoft/vscode/assets/2230985/f410cc7e-9506-482f-bada-cf141d060223)

**Comment by Manbearpiet** [comment]
I have the same behavior:

<img width="392" alt="image" src="https://github.com/microsoft/vscode/assets/43993129/f073385c-d134-4b5c-9d3d-d0a7b400055a">

> Version: 1.89.0-insider
> Commit: 50a6f4f200c5a33f47997eb6a8966e50cf219e21
> Date: 2024-04-12T05:51:02.558Z (3 days ago)
> Electron: 28.2.8
> ElectronBuildId: 27744544
> Chromium: 120.0.6099.291
> Node.js: 18.18.2
> V8: 12.0.267.19-electron.0
> OS: Darwin arm64 23.4.0
