### ISSUE TITLE
editor/title/run rememberDefault doesn't remember that jupyter.runFileInteractive was last selected

### ISSUE THREAD

**Issue by starball5** [microsoft/vscode#210286]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.88.1
- OS Version: Both Ubuntu 23.10 and Windows 11

Steps to Reproduce:

1. Install and enable both the Python and Jupyter extensions
2. Create Python file
3. Click dropdown for `editor/title/run` menu and select "Run Current File in Interactive Window"
4. Hover mouse over `editor/title/run` menu button and observe that tooltip does not say "Run Current File in Interactive Window".

My (potentially) wrong understanding is that `editor/title/run` is supposed to remember what option was last selected and reuse it the next time the button is clicked. This is what it does for the Python "Run Python File" and "Run Python File in Dedicated Terminal" items.

This behaviour was brought to my attention due to https://stackoverflow.com/q/78314406/11107541.

**Comment by amunger** [comment]
It's still not perfect, the action has to be selected while the IW is already open, but it will change to the default action once that is done
