### ISSUE TITLE
Typescript Language Server stuck everything due to third-party extensions

### ISSUE THREAD

**Issue by axetroy** [microsoft/vscode#210284]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.88.1
- OS Version: macOS 14.4.1

Steps to Reproduce:

1. 
2. 

Here is typescript Log in vscode

```log
2024-04-13 11:30:57.675 [info] Starting TS Server
2024-04-13 11:30:57.676 [info] Using tsserver from: c:\Users\Admin\.vscode-server\cli\servers\Stable-e170252f762678dec6ca2cc69aba1570769a5d39\server\extensions\node_modules\typescript\lib\tsserver.js
2024-04-13 11:30:57.676 [info] <syntax> Forking...
2024-04-13 11:30:57.676 [info] <syntax> Starting...
2024-04-13 11:30:57.676 [info] <semantic> Forking...
2024-04-13 11:30:57.676 [info] <semantic> Starting...
```

**Sorry, I can't give feedback via vscode because almost all functions are stuck, including Report Issue**

https://github.com/microsoft/vscode/assets/9758711/7bf53b6e-c5e1-496e-8223-d0ee6becc3fd

Finally, after my investigation, I found that it should be this plug-in [pretty-ts-errors](https://marketplace.visualstudio.com/items?itemName=yoavbls.pretty-ts-errors), ref: https://github.com/yoavbls/pretty-ts-errors/issues/75

It blocks most other features of vscode, including formatting, lint, other extensions loading, etc.

Can vscode have a mechanism to prevent third-party extensions from affecting the main functions of vscode.

Or give a prompt to the user, otherwise I have been wondering if there is something wrong with my typescript project configuration.

**Comment by mjbvz** [comment]
> Sorry, I can't give feedback via vscode because almost all functions are stuck, including Report Issue

Does this still happen if you disable that extension?

**Comment by axetroy** [comment]
> Does this still happen if you disable that extension?

No, it no longer happen after disabling all extensions

**Comment by mjbvz** [comment]
Please file the issue against that extension so they can take a look
