### ISSUE TITLE
Test: Ensure the tsconfig.json validation is exposed

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#21029]
#20163

- [x] any @aeschli 

Complexity: 1

Errors should now be shown in invalid jsconfig and tsconfigs. This flow is still pretty buggy and we're tracking a number of fixes/requests on the TS side to support this better. This only tests the basics

1. Create a new project with an empty ts file and an empty `tsconfig.json`
2. Create an invalid option:
  ```json
  {
      "compilerOptions": {
          "notAnOption": true
      }
  }
  ``` 
3. Switch to the ts file. In the errors view you should see:
  ![screen shot 2017-02-21 at 4 26 23 pm](https://cloud.githubusercontent.com/assets/12821956/23191454/81e428ca-f852-11e6-8cbf-c1738da861c9.png)

4. Change the config to
```json
{
    "files": [
        "notAFile.js"
    ]  
} 
```

5. Switch back to the TS file to see a new error:
  ![screen shot 2017-02-21 at 4 28 55 pm](https://cloud.githubusercontent.com/assets/12821956/23191504/dc650ac6-f852-11e6-8d2b-f5fbe82ae705.png)

6. Try creating other invalid configs and reloading the project to see them

**Known Issues**
* Errors only show up when working in a js or ts file, not in the `jsconfig` or `tsconfig` itself.
* Config file error are show on the first line at the first character.
* Editing the config file causes the errors to go away

**Comment by aeschli** [comment]
I tested the basic as described. Some thoughts:
- To prevent unknown properties: That could also be done in the JSON schema for tsconfig. We take it from http://json.schemastore.org/tsconfig resp. http://json.schemastore.org/jsconfig by setting 'additionalProperties' to false
- To get positions in the JSON file. We created a node module [jsonc-parser](https://github.com/Microsoft/node-jsonc-parser) to be used for that (can also used without allowing comments)
