### ISSUE TITLE
how can i complete my code like vim's ctrl+p?

### ISSUE THREAD

**Issue by donnol** [Microsoft/vscode#21033]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.8.6|
|vscode-todo|MattiasPernhult|0.8.0|
|emoji|Perkovec|0.0.3|
|code-settings-sync|Shan|2.4.4|
|comment-snippets|Tobiah|0.2.0|
|vscode-database|bajdzis|1.2.0|
|ftp-simple|humy2833|0.4.14|
|icon-fonts|idleberg|1.6.1|
|ctags-support|jaydenlin|1.0.7|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|Go|lukehoban|0.6.53|
|vscode-fileheader|mikey|0.0.2|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|startanyshell|remcoros|0.3.1|
|vscode-icons|robertohuertasm|7.2.0|
|vim|vscodevim|0.5.3|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. when i use vim, i can press ctrl+p to complete my code.
2. so, how can i do that on vscode?

**Comment by roblourens** [comment]
I'm not sure if it's exactly the same, but `ctrl+space` will bring up the intellisense/autocomplete menu.

**Comment by donnol** [comment]
i try the ctrl+space, but i only see the 'no suggest' message. how about that?

**Comment by roblourens** [comment]
What language or file type are you editing?

**Comment by donnol** [comment]
golang, thx.

**Comment by roblourens** [comment]
If you're using the Go extension, and it isn't giving you intellisense, you should file an issue over on that repo: https://github.com/microsoft/vscode-go

**Comment by donnol** [comment]
ok, i will try that.
