### ISSUE TITLE
Hot Exit does not work on Mac

### ISSUE THREAD

**Issue by cateyes99** [Microsoft/vscode#21038]
- VSCode Version: 1.8.1, 1.9.1
- OS Version: OS X EI Capitan

Steps to Reproduce:
VSCode settings:

>   "files.hotExit": "onExit"
"files.autoSave": "off",

1. open a folder
2. create 2 new file, type some words in both files without saving.
3. when closing the instance of the VSCode window, it weirdly asks "Do you want to save the changes you made to the following 2 files", click "Don't Save". Next time, open a new instance of VSCode and open the same folder, the two new files the Untitled-1 and Untitled-2 are opend but both are blank.

another test:
1. open a folder
2. open an existing file
3. make some change to the file without saving.
4. when closing the instance of the VSCode window, it weirdly asks "Do you want to save the changes you made to a.cs", click "Don't Save". Next time, open a new instance of VSCode and open the same folder, but the previously modified file shows nothing changed.

**Comment by bpasero** [comment]
@cateyes99 closing a window on macOS does not exit the application. If you want to have hot exit on closing windows you need to configure `onExitAndWindowClose`

**Comment by cateyes99** [comment]
@bpasero u r right. i missed that point. Once change to `onExitAndWindowClose`, it does work thx.
