### ISSUE TITLE
Scrolling skipping

### ISSUE THREAD

**Issue by jim256** [Microsoft/vscode#21035]
When I scroll using my touchpad, the scrolling regularly gets "stuck" and hangs for a minute, then jumps to where it should have been. This has been happening for at least a week, though I can't remember exactly for how long.

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|python|donjayamanne|0.5.8|
|beautify|HookyQR|0.8.6|
|MagicPython|magicstack|1.0.6|
|mssql|ms-mssql|0.2.1|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|partial-diff|ryu1kn|0.2.0|
|vscode-sql-beautify|sensourceinc|0.0.4|

---

Steps to Reproduce:

1. Open any file
2. Scroll using touchpad.

**Comment by roblourens** [comment]
What type of laptop do you have?

**Comment by jim256** [comment]
Surface Book (i7, 16GB, 512GB config) on Windows 1607 build 14393.693.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13612 and https://github.com/Microsoft/vscode/issues/12637
