### ISSUE TITLE
Code is not running properly

### ISSUE THREAD

**Issue by soumyagaur3** [microsoft/vscode#210343]
Type: <b>Bug</b>

When i run the code in vs code in java language it is not getting input from the user but it showing nothing in it 

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22635
Modes:

**Comment by kalebers** [comment]
Can you provide more information or prints for your issue?
