### ISSUE TITLE
Diff editor marks unchanged parts as changed

### ISSUE THREAD

**Issue by adamsol** [microsoft/vscode#210310]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.1
- OS Version: Windows 10

Steps to Reproduce:

1. Go to the Monaco Editor Playground:
https://microsoft.github.io/monaco-editor/playground.html?source=v0.47.0#XQAAAAJBAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0vhciVciAJM8XEuX7Os378jBGtVLkr6ryuhqvky-XZ9Sy0vyFSI1m9lYQpwqOsaKmhydYWIo-9hGbv_4wmytvZiMgxLhxTewfwlFhcmtQr0AZiDHV-6Yg5lfKa4oymWQK4RtEpAr35Ta3OaULjvyFxB0Q-T03LkhXrdzbmHtmDypBF81loxFZ56V_XPIz6sZJ6HpvMGnf1zgmY9CdB-qotv4pXGK3EfTG7TQ5Wur5Qizx8HM7bQW4Rn4MKw_aKmh2DuusFVmLDpt9JdvRhVfYghjVkhk2j-jeOvAYwvpiTk1_q_bkRmKjKRCIqOhPJ8Nw1Cm92FWXhabKcWxaP_rrBOe
2. Notice that the word "one" in the first line is marked as changed, and the digit "3" in the last line is also marked as changed. But they are not changed.

I was going to create an issue in https://github.com/microsoft/monaco-editor, but got redirected here, as it turns out that VS Code behaves the same.

The bug started appearing in v0.46.0 of Monaco Editor.

Enabling `diffAlgorithm: 'legacy'` fixes it.

Since adding something at the end of line changes the behaviour, it may be related to microsoft/monaco-editor#4360, although that one started appearing in v0.44.0 of Monaco Editor.

**Comment by adamsol** [comment]
Let me also document some other problematic cases with the diff editor. The examples are obfuscated, but I've noticed the issues in normal use.

0. [The same link as before](https://microsoft.github.io/monaco-editor/playground.html?source=v0.47.0#XQAAAAJBAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0vhciVciAJM8XEuX7Os378jBGtVLkr6ryuhqvky-XZ9Sy0vyFSI1m9lYQpwqOsaKmhydYWIo-9hGbv_4wmytvZiMgxLhxTewfwlFhcmtQr0AZiDHV-6Yg5lfKa4oymWQK4RtEpAr35Ta3OaULjvyFxB0Q-T03LkhXrdzbmHtmDypBF81loxFZ56V_XPIz6sZJ6HpvMGnf1zgmY9CdB-qotv4pXGK3EfTG7TQ5Wur5Qizx8HM7bQW4Rn4MKw_aKmh2DuusFVmLDpt9JdvRhVfYghjVkhk2j-jeOvAYwvpiTk1_q_bkRmKjKRCIqOhPJ8Nw1Cm92FWXhabKcWxaP_rrBOe), but I'm adding a screenshot for completeness.
![0](https://github.com/microsoft/vscode/assets/17574518/9b83eb58-043d-43e2-9e2b-5e058aa956f4)

1. [Link.](https://microsoft.github.io/monaco-editor/playground.html?source=v0.47.0#XQAAAAKTAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw2EE9RgmSatbNyrNa50VLHWwDOn0YI7IfU0xJ0CGYU1vRtgnKPmZzQcQ1F9I-F9YcvQUj8HivueDk6xk10aTtOwU24ckDCgQuT7L4YDQvToxZpQ6RKSVCwpamK8Bnj7p28BHKGv-nCZJglldDlQZCnajhSApQkVTthjYl0RT98-NLiICo4cvYAFe2hbtpf8iR1A4YEwT-LCGH901dhbGnqe2JYKkDpSifVnhLN0yllAIOvodO4H1RJqKzYEktKbbRea0D3EVfD8v7yvP8Gf10ltxw_MUyklqPfolaNFMNS6O7Dm7ekp6kVAntLtPF3oeHK0PYIgWRy2TwOz8wVRX6P9ByEFvomR1z9bgw2CVmFUP5DLYb4ISWaJXwNFIXJ4EQdQJw5bn6SE0T7FliF1HZ6l3Wptev3pGrr8VWFkrqYXv9vMAi) Some random text. The first 4 and the last 5 characters of the original text are the same as in the modified text, but the diff doesn't reflect that. Instead, it shows that an additional line is deleted, even though it's not, and the modified text displays only 3 characters at the end as unchanged. Removing one character in either text changes the diff substantially. 
![1](https://github.com/microsoft/vscode/assets/17574518/f118c75a-b6b7-4af2-a52b-d6e204e6b9c2)

2. [Link.](https://microsoft.github.io/monaco-editor/playground.html?source=v0.47.0#XQAAAAJCAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0v52NVciAJM8XEuX7Os378jBGtVLkr6ryuhqvky-XZ9Sy0vyFSI1m9lYQpwqOsaKmhydYWIo-9hGbv_4wlPNckWXdNkYmQdwhCQyYgYrzGd0LKI9J2dY44QRlRVb-RacR0LtbyKyhNqwhQCtY8-xgdYwsSzgyi02lhXp1ejDCiXs3LIICfUVY7Es3qGhlVtpvFACdTqOru6cM0wq4LHoithKz5sxwbI3za3sN61h6_okwD-oqqJqaiCkVKHklggiXoUkOrSBXHBuKQgHwesYiU9_w6RBHe0kJCjkJv8fT8N5BCBEx_ECD8TCDyPmgkQ5-jHmWHP8oVtDvTWaA0Tq1gNh_9u3Rs4) Whole text is deleted. It didn't have a trailing newline. Not all characters in the last line have the dark red background; only to the length of the _first_ line of the text. Additionally, the empty lines are marked with dark red in the side-by-side view, while they are marked with light red in the inline view.
![2a](https://github.com/microsoft/vscode/assets/17574518/9315e277-f89e-4af4-b833-0328bdd3e53a)
![2b](https://github.com/microsoft/vscode/assets/17574518/ff9c828e-5eff-46f6-99a1-e17cd494365b)

All of the issues can be fixed by enabling `diffAlgorithm: 'legacy'` (although this algorithm has its own problems, so not a solution).

**Comment by adamsol** [comment]
> 1. [Link.](https://microsoft.github.io/monaco-editor/playground.html?source=v0.47.0#XQAAAAKTAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw2EE9RgmSatbNyrNa50VLHWwDOn0YI7IfU0xJ0CGYU1vRtgnKPmZzQcQ1F9I-F9YcvQUj8HivueDk6xk10aTtOwU24ckDCgQuT7L4YDQvToxZpQ6RKSVCwpamK8Bnj7p28BHKGv-nCZJglldDlQZCnajhSApQkVTthjYl0RT98-NLiICo4cvYAFe2hbtpf8iR1A4YEwT-LCGH901dhbGnqe2JYKkDpSifVnhLN0yllAIOvodO4H1RJqKzYEktKbbRea0D3EVfD8v7yvP8Gf10ltxw_MUyklqPfolaNFMNS6O7Dm7ekp6kVAntLtPF3oeHK0PYIgWRy2TwOz8wVRX6P9ByEFvomR1z9bgw2CVmFUP5DLYb4ISWaJXwNFIXJ4EQdQJw5bn6SE0T7FliF1HZ6l3Wptev3pGrr8VWFkrqYXv9vMAi) Some random text. The first 4 and the last 5 characters of the original text are the same as in the modified text, but the diff doesn't reflect that. Instead, it shows that an additional line is deleted, even though it's not, and the modified text displays only 3 characters at the end as unchanged. Removing one character in either text changes the diff substantially.

In my application using the Monaco Editor, I'm getting also the following assertion error in this case:

```
Error: Assertion Failed
    at assertFn (assert.js:54:71)
    at lineRangeMappingFromRangeMappings (defaultLinesDiffComputer.js:203:69)
    at DefaultLinesDiffComputer.computeDiff (defaultLinesDiffComputer.js:122:25)
    at EditorSimpleWorker.computeDiff (editorSimpleWorker.js:280:38)
    at EditorSimpleWorker.computeDiff (editorSimpleWorker.js:273:43)
    at SimpleWorkerServer._handleMessage (simpleWorker.js:371:65)
    at Object.handleMessage (simpleWorker.js:356:51)
    at SimpleWorkerProtocol._handleRequestMessage (simpleWorker.js:162:38)
    at SimpleWorkerProtocol._handleMessage (simpleWorker.js:131:29)
    at SimpleWorkerProtocol.handleMessage (simpleWorker.js:124:14)
    at eval (errors.js:31:27)
```

And here's the code it's pointing to:

```js
    (0,_base_common_assert_js__WEBPACK_IMPORTED_MODULE_1__.assertFn)(() => {
        if (!dontAssertStartLine) {
            if (changes.length > 0 && changes[0].original.startLineNumber !== changes[0].modified.startLineNumber) {
                return false;
            }
        }
        return (0,_base_common_assert_js__WEBPACK_IMPORTED_MODULE_1__.checkAdjacentItems)(changes, (m1, m2) => m2.original.startLineNumber - m1.original.endLineNumberExclusive === m2.modified.startLineNumber - m1.modified.endLineNumberExclusive &&
            // There has to be an unchanged line in between (otherwise both diffs should have been joined)
            m1.original.endLineNumberExclusive < m2.original.startLineNumber &&
            m1.modified.endLineNumberExclusive < m2.modified.startLineNumber);
    });
```

But the error doesn't appear for the obfuscated example in the playground, and unfortunately I can't share the full code to reproduce it.

**Comment by adamsol** [comment]
In Monaco Editor v0.48, the problem number 1 is mostly fixed: there is no line incorrectly marked as deleted, and no error in the console. Great! However, still there is no indication of unchanged text. i.e. the whole line is dark green or dark red.

**Comment by adamsol** [comment]
And in v0.49 the problem number 2 is also mostly fixed. Although the inconsistency between the inline and side-by-side views still exists.

**Comment by hediet** [comment]
Thanks for the detailed feedback!

[As for 0](https://microsoft.github.io/monaco-editor/playground.html?source=v0.50.0-dev-20240605#XQAAAAJBAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0vhciVciAJM8XEuX7Os378jBGtVLkr6ryuhqvky-XZ9Sy0vyFSI1m9lYQpwqOsaKmhydYWIo-9hGbv_4wmytvZiMgxLhxTewfwlFhcmtQr0AZiDHV-6Yg5lfKa4oymWQK4RtEpAr35Ta3OaULjvyFxB0Q-T03LkhXrdzbmHtmDypBF81loxFZ56V_XPIz6sZJ6HpvMGnf1zgmY9CdB-qotv4pXGK3EfTG7TQ5Wur5Qizx8HM7bQW4Rn4MKw_aKmh2DuusFVmLDpt9JdvRhVfYghjVkhk2j-jeOvAYwvpiTk1_q_bkRmKjKRCIqOhPJ8Nw1Cm92FWXhabKcWxaP_rrBOe):

![image](https://github.com/microsoft/vscode/assets/2931520/2248addb-2f42-4e6e-a5b9-76004211f89e)

This is a heuristic. When the aligned words are too different, the equal characters are marked as different as well. There is a threshold, as you can see when you delete a modified character:

![image](https://github.com/microsoft/vscode/assets/2931520/5e46dd51-de7f-49fb-b4cb-4ba3e4f7ce0e)

[As for 1](https://microsoft.github.io/monaco-editor/playground.html?source=v0.49.0#XQAAAAKTAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw2EE9RgmSatbNyrNa50VLHWwDOn0YI7IfU0xJ0CGYU1vRtgnKPmZzQcQ1F9I-F9YcvQUj8HivueDk6xk10aTtOwU24ckDCgQuT7L4YDQvToxZpQ6RKSVCwpamK8Bnj7p28BHKGv-nCZJglldDlQZCnajhSApQkVTthjYl0RT98-NLiICo4cvYAFe2hbtpf8iR1A4YEwT-LCGH901dhbGnqe2JYKkDpSifVnhLN0yllAIOvodO4H1RJqKzYEktKbbRea0D3EVfD8v7yvP8Gf10ltxw_MUyklqPfolaNFMNS6O7Dm7ekp6kVAntLtPF3oeHK0PYIgWRy2TwOz8wVRX6P9ByEFvomR1z9bgw2CVmFUP5DLYb4ISWaJXwNFIXJ4EQdQJw5bn6SE0T7FliF1HZ6l3Wptev3pGrr8VWFkrqYXv9vMAi), this seems to be fixed. Also, the same heuristic applies to this.

[As for 2](https://microsoft.github.io/monaco-editor/playground.html?source=v0.49.0#XQAAAAJCAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0v52NVciAJM8XEuX7Os378jBGtVLkr6ryuhqvky-XZ9Sy0vyFSI1m9lYQpwqOsaKmhydYWIo-9hGbv_4wlPNckWXdNkYmQdwhCQyYgYrzGd0LKI9J2dY44QRlRVb-RacR0LtbyKyhNqwhQCtY8-xgdYwsSzgyi02lhXp1ejDCiXs3LIICfUVY7Es3qGhlVtpvFACdTqOru6cM0wq4LHoithKz5sxwbI3za3sN61h6_okwD-oqqJqaiCkVKHklggiXoUkOrSBXHBuKQgHwesYiU9_w6RBHe0kJCjkJv8fT8N5BCBEx_ECD8TCDyPmgkQ5-jHmWHP8oVtDvTWaA0Tq1gNh_9u3Rs4), this also seems to be fixed.

> Although the inconsistency between the inline and side-by-side views still exists.

I think there is an issue for this. Unfortunately, for now, we cannot reuse the rendering of decorations in the original document in the side-by-side view in the deleted part of the inline view, as we do not instantiate a monaco editor for that. This explains the inconsistency.

**Comment by adamsol** [comment]
> This is a heuristic. When the aligned words are too different, the equal characters are marked as different as well. There is a threshold, as you can see when you delete a modified character:

Thanks for the explanation. Would it be possible to disable this heuristic or configure a different threshold? It's quite perplexing when I have, let's say, a 2-character identifier or string, I change one character, and the diff tells me I've changed the whole thing. And the same for longer identifiers -- changing more than half of a name during a refactoring is not uncommon, and I'd like to be sure that I didn't edit too much.

FWIW, I've pasted my example into a [random online diff tool](https://text-compare.com/), and it works as I'd expect:

![text-compare](https://github.com/microsoft/vscode/assets/17574518/1dde7878-2eee-4e5c-b0be-9c8222edd6bb)

And [another one](https://www.diffchecker.com/text-compare/) has a dedicated switch to customize the behavior:

![diffchecker](https://github.com/microsoft/vscode/assets/17574518/b7264e5a-9faf-491a-a9e5-8c7486f33ae9)

**Comment by hediet** [comment]
> and it works as I'd expect

For this example, yes. We added the heuristic to significantly reduce the alignment of random matches, when bigger edits took place. Just compare [this](https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0-dev.20230107#XQAAAAJiBgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw_WqqRgmSatbNyrNa50VLHWwDOn0YI7IfU0xJ0CGYU1vRtgnKPmZzQcQ1IYSLB-5f-1dobOlrSyV9lhyCGfRbYzki2ss5zVzMoADqGXLD9-jUH9Cgliv1evh33YIQtVm755RiAVo6REsxlSlZ_342AWqp2R2Y3Ky6OhSevYWfkXWDhdICvnj732MGE1S7DcE75EXHAyTlEoQ9cdRRODl-odw6UBTf_i6YYsb_EBxcBg633gu3l16kA3cmftEgvNv5ZYFeh0R5lnfY0Ofr09lZLgG7hg7yqYeSqZqC7G_BP2fNHNlKyDNBy9_RYbbvxeL4Z0NieTSay_KXxHW9d1qUWTF5omKnTdED9dVbonr4MHFKC4tV_HSr1pBUbWx0oOxTkhIDlXPH34XmhrSwUEFQ1Kz_xZecjKC2aQ2Kl3q3_EUuVlfUjiYdF-HU0WjiLJZOLAc_qm1ClRknZgIUkA_8zzOIhVdlXk4UxRECAQeJtYnSWkCHpgdInuvfNo1QPakXmbVaTKW6fbdr1LobpfjkYBZ6eTNKAmAfubMVX6sXSR7_Nm2n3WKAmL6I9oMHTrW50ZJf6ehe0zTkqKYl2EOoYM1vR1dkv4aIPqxcqL-UBtvOUOyb8WL-ZEbkcLAkUoRM7lOp1T56kf_2lELi) example with [this](https://microsoft.github.io/monaco-editor/playground.html?source=v0.49.0#XQAAAAJiBgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw_WqqRgmSatbNyrNa50VLHWwDOn0YI7IfU0xJ0CGYU1vRtgnKPmZzQcQ1IYSLB-5f-1dobOlrSyV9lhyCGfRbYzki2ss5zVzMoADqGXLD9-jUH9Cgliv1evh33YIQtVm755RiAVo6REsxlSlZ_342AWqp2R2Y3Ky6OhSevYWfkXWDhdICvnj732MGE1S7DcE75EXHAyTlEoQ9cdRRODl-odw6UBTf_i6YYsb_EBxcBg633gu3l16kA3cmftEgvNv5ZYFeh0R5lnfY0Ofr09lZLgG7hg7yqYeSqZqC7G_BP2fNHNlKyDNBy9_RYbbvxeL4Z0NieTSay_KXxHW9d1qUWTF5omKnTdED9dVbonr4MHFKC4tV_HSr1pBUbWx0oOxTkhIDlXPH34XmhrSwUEFQ1Kz_xZecjKC2aQ2Kl3q3_EUuVlfUjiYdF-HU0WjiLJZOLAc_qm1ClRknZgIUkA_8zzOIhVdlXk4UxRECAQeJtYnSWkCHpgdInuvfNo1QPakXmbVaTKW6fbdr1LobpfjkYBZ6eTNKAmAfubMVX6sXSR7_Nm2n3WKAmL6I9oMHTrW50ZJf6ehe0zTkqKYl2EOoYM1vR1dkv4aIPqxcqL-UBtvOUOyb8WL-ZEbkcLAkUoRM7lOp1T56kf_2lELi), and there are more extreme cases.

**Comment by adamsol** [comment]
I understand there are a lot of different cases, but, as is often the case with heuristics, it may have solved one problem only to create another one.

Personally, I don't really mind the random matches with bigger edits, as in such cases I have to read the whole code anyway to understand what's going on. Meanwhile, highlighting unchanged parts is really misleading when viewing small edits, and just looks like a bug.

It would be great if the threshold was configurable: from 0 (full character diff), to 0.5 (around which I assume it is now), to 1 (word diff).
