### ISSUE TITLE
terminal underlines don't appear on windows

### ISSUE THREAD

**Issue by cpendery** [microsoft/vscode#210326]
Terminal underlines don't appear on Windows, but they do appear on when running vscode from WSL.

![image](https://github.com/microsoft/vscode/assets/35637443/bb5d5ae5-2720-410c-be40-73a0f90a1ab9)

![image](https://github.com/microsoft/vscode/assets/35637443/cf040b8e-4f5d-4763-ae84-974bfd863ad0)

Does this issue occur when all extensions are disabled?: Yes

Version: 1.89.0-insider (user setup)
Commit: 50a6f4f200c5a33f47997eb6a8966e50cf219e21
Date: 2024-04-12T05:50:19.038Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Run the following command:
 - bash
```shell
echo -e '\x1b[4:0m4:0 none\x1b[0m \x1b[4:1m4:1 straight\x1b[0m \x1b[4:2m4:2 double\x1b[0m \x1b[4:3m4:3 curly\x1b[0m \x1b[4:4m4:4 dotted\x1b[0m \x1b[4:5m4:5 dashed\x1b[0m'
```
 - powershell
```shell
Write-Output "`e[4:0m4:0 none`e[0m `e[4:1m4:1 straight`e[0m `e[4:2m4:2 double`e[0m `e[4:3m4:3 curly`e[0m `e[4:4m4:4 dotted`e[0m `e[4:5m4:5 dashed`e[0m"
```
2. No underlines appear for any of the escape sequences on Windows

**Comment by Tyriar** [comment]
I think this is a conpty problem, it was only implemented to work on conhost in the Jan 30th release so an eventual update to Windows 11 should bring that functionality in: https://github.com/microsoft/terminal/releases/tag/v1.20.10293.0

**Comment by cpendery** [comment]
I'm not sure how, but `nu` seems to be able to render them on windows. 
![image](https://github.com/microsoft/vscode/assets/35637443/37722f1d-5442-46a5-9f89-4c157ac5d5b2)
and here are the terminal traces from that render.
![image](https://github.com/microsoft/vscode/assets/35637443/9610266f-d9fa-47d3-aeee-1d59dc2c7f8f)

I can't spot the escape they're using. Are links just dash underlined in xterm?

**Comment by Tyriar** [comment]
Nushell might be using something that avoids the Console API emulation? xterm.js has full support for all the styles and colors, the fact that it works in WSL means that the xterm.js side is covered but the sequences are getting dropped on the conpty side.
