### ISSUE TITLE
Test: Experimental VS Code-native PowerShell intellisense

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#210394]
Refs: #154662

- [x] Windows @amunger (pwsh 7)
- [x] Windows @Tyriar ~~@TylerLeonhardt~~ (Windows PowerShell)
- [x] macOS @joaomoreno 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23210394%0A%0A&assignees=Tyriar)

---

Some more work has been happening on PowerShell intellisense and we want to get some more eyes/testing on it. Please do a little exploratory testing in the terminal with the setting on, mostly using the terminal as you would normally do and report issues for when it didn't work as expected or was annoying.

Setup:

Set `"terminal.integrated.shellIntegration.suggestEnabled": true` and create a new pwsh (6+) terminal. See https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7.4 for how to install the latest.

Usage:

Intellisense should show up based on the current prompt when you press ctrl+space:

![image](https://github.com/microsoft/vscode/assets/2193314/2eda9936-4755-4067-86ea-ca6aeda2f93b)

It should show up automatically when you type the `-` character:

![image](https://github.com/microsoft/vscode/assets/2193314/8c3fc722-a00f-4962-9532-baa1e0ab513f)
![image](https://github.com/microsoft/vscode/assets/2193314/acadb26d-b420-4f92-b2f1-a0f967621036)

**Comment by cpendery** [comment]
I think after some of the most recent changes, the suggestions just disappear on first input.

https://github.com/microsoft/vscode/assets/35637443/8d3b770c-e655-47f4-a7dd-55f234256205

**Comment by Tyriar** [comment]
@cpendery this is what I was seeing on macOS before. I made a change to fix it and it seems to have regressed again 🤔

**Comment by Tyriar** [comment]
@cpendery looking into it https://github.com/microsoft/vscode/issues/210562

**Comment by amunger** [comment]
the font is off for me
![image](https://github.com/microsoft/vscode/assets/2019016/764df3fc-9a01-4ac0-9813-1a8a0a8b0b8e)

**Comment by Tyriar** [comment]
@amunger could you make an issue with your settings? I haven't seen that happen in a long time

**Comment by abhijit-chikane** [comment]
> the font is off for me ![image](https://private-user-images.githubusercontent.com/2019016/323339921-764df3fc-9a01-4ac0-9813-1a8a0a8b0b8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1ODIwNzYsIm5iZiI6MTcxMzU4MTc3NiwicGF0aCI6Ii8yMDE5MDE2LzMyMzMzOTkyMS03NjRkZjNmYy05YTAxLTRhYzAtOTgxMy0xYThhMGE4YjBiOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjBUMDI1NjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWY3ZmI0ZDRmNThkOTE4ZWE3Y2QzZjg1MDU4NDAzMzFhYjVmM2JmNWViNmVlMzUwYWIxMzhmY2JlYTZmYzNmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ePuHpsUv_UBgLQ1jt9x4jyck0uX_z_j3GhfEAzt-f-A)

Same for me
But is there a way we don’t have to press the ctrl+space and should show up suggestions as we type just like how it shows up in editor

anyways this is really cool
Nice work👏

**Comment by Tyriar** [comment]
@abhijit-chikane it's meant to show when you type -, something is wrong if that's now happening

**Comment by abhijit-chikane** [comment]
> @abhijit-chikane it's meant to show when you type -, something is wrong if that's now happening
Well i was talking about the font
It does shows up when I press ctrl+space
But I was saying it would be much better if we could show the suggestions as we type just like editor
And one thing I have notice that the suggestions shows only for first word

**Comment by Tyriar** [comment]
@abhijit-chikane thanks for the feedback, maybe we can improve that 👍

**Comment by joaomoreno** [comment]
This is soooo cool 👏

**Comment by TylerLeonhardt** [comment]
Blocked until: https://github.com/microsoft/vscode/issues/211132 @Tyriar is aware of the fix required. Will shift focus to other TPIs while that gets released

**Comment by abhijit-chikane** [comment]
This should work like [this](https://lh7-us.googleusercontent.com/QULxSq2WHjSg2t94A3GtzBvfuG9ZEBVI44CXexGGBTsXXCTGum2TeutNXzsn-eAsQqnkvt7bAS9kClRFjDLXxTIjcFqoNbd073AqO-sRIy0rm9l6ujJNdYioKisK9pdl0-uekitU3n3WjlEUMhZb_tc)

Link to the full [blog](https://blog.jetbrains.com/idea/2024/02/the-new-terminal-beta-is-now-in-jetbrains-ides/#visual-changes)
