### ISSUE TITLE
RTL languages like Arabic for built-in terminal

### ISSUE THREAD

**Issue by radenmuaz** [microsoft/vscode#210391]
Already 6 years, this issue need to be reopened:
https://github.com/microsoft/vscode/issues/28571
related:
https://github.com/xtermjs/xterm.js/issues/701

**Comment by Tyriar** [comment]
We also maintain the xterm.js repo and track some terminal issues there exclusively to simplify project management, the https://github.com/xtermjs/xterm.js/issues/701 issue still remains open.

/duplicate
