### ISSUE TITLE
Simple browser extention showing white

### ISSUE THREAD

**Issue by gusborg88** [microsoft/vscode#210322]
Type: <b>Bug</b>

1. Open any website with the simple browser
2. See nothing appears
I was able to get https://example.com working, but that's it. All other websites don't work.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (10.35GB free)|
|Process Argv|--crash-reporter-id eadc9fd3-1184-4a7b-9972-faeaaebf8100|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.10.4
vscode-html-css|ecm|2.0.9
code-beautifier|mic|2.3.3
debugpy|ms-|2024.4.0
python|ms-|2024.4.1
vshaxe|nad|2.31.0
batch-runner|Nil|1.3.0
funkin-scripting-intellisense|Ral|0.1.0
rech-editor-batch|rec|0.0.22

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r3:30993539
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
showvideoc:31016891
dsvsc021:30996838
gd77d436:30999572
jg8ic977:31013176

```

</details>

**Comment by mjbvz** [comment]
Many popular websites don't allow themselves to be shown in the iframes that simple browser uses. There's no workaround for this
