### ISSUE TITLE
Multi word chat participant names should be handled more gracefully

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#210385]
1. Take the https://github.com/microsoft/vscode-extension-samples/tree/main/chat-agent-sample
2. Open package.json and say it contributes a participant with name "friendly cat"
3. This is not supported in the UI, and when I invoke the agent name it does not get nicely rendered. And the message is not forward to the "friendly cat" 🐛 

I think it is fine to limit agent names to be one word. But we should have a more graceful error. And I can document it in our guidelines.
fyi @jrieken 

![Image](https://github.com/microsoft/vscode/assets/1926584/9764f5fd-2df0-4395-8402-88147431319e)

```json
"chatParticipants": [
            {
		"id": "chat-sample.cat",
                "name": "friendly cat",
                "description": "Meow! What can I teach you?",
                "isSticky": true,
                "commands": [
                    {
                        "name": "teach",
                        "description": "Pick at random a computer science concept then explain it in purfect way of a cat"
                    },
                    {
                        "name": "play",
                        "description": "Do whatever you want, you are a cat after all"
                    }
                ]
            }
        ],
```

**Comment by roblourens** [comment]
This can be supported

**Comment by roblourens** [comment]
I think we should stick to participant names without spaces. I do now properly validate that with a regex at the contribution point so they will see an error.

**Comment by isidorn** [comment]
Works fine. Though error is confusing if you do not know regex
I suggest to add in the package.json description of "name" that "whitespace characters are not accepted".

![Image](https://github.com/microsoft/vscode/assets/1926584/324b7422-aeef-4880-8a73-b21d81fd90f2)

**Comment by roblourens** [comment]
Sure, did that too.
