### ISSUE TITLE
Add Folder Name to Tab Labels for index.js|ts|jsx|tsx Files

### ISSUE THREAD

**Issue by KingMario** [microsoft/vscode#210301]
Hello VS Code team,

I am writing to request a feature that would greatly enhance the usability of VS Code when working with projects that have multiple index.js|ts|jsx|tsx files under different folders.

Feature Description:

When a file with the index.js|ts|jsx|tsx name is open in the editor, it can be difficult to recognize it because the tab label only displays the file name, that is `index.js` or so.

I propose that to update the tab label for such index files with its folder name.

For example, instead of the tab label being just index.js, it could be myFolder/index.js.

Benefits:

This feature would improve the user experience for developers working in large codebases with many files having the `index` name. It would allow them to quickly and easily identify the file. This would be espically useful when the developers open several `index` files without keeping them open, i.e., the `index` files are open in one place.

Implementation:

This could potentially be implemented by modifying the Tab.labels property to include parent folder name of such files.

Thank you for considering this feature request. I believe that this addition would be a valuable enhancement to the VS Code user experience.

BRs, Mario

**Comment by IllusionMH** [comment]
You should be able to configure it to your liking with new Custom labels feature https://code.visualstudio.com/updates/v1_88#_custom-labels-for-open-editors

**Comment by KingMario** [comment]
> You should be able to configure it to your liking with new Custom labels feature https://code.visualstudio.com/updates/v1_88#_custom-labels-for-open-editors

Thanks, that's exactly what I needed. Such a coincidence that this feature is already available in the new version.
