### ISSUE TITLE
[BUG] TunnelFactory Proposed API: registerTunnelProvider doesn't update the ports to the UI

### ISSUE THREAD

**Issue by jonathanpv** [microsoft/vscode#210367]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Go to https://github.com/jonathanpv/codecontext and git clone, install in visual studio code insiders, then try running the command to share context, the port forwards successfully but doesn't display in the vscode opened ports view
2. See it opens the port here
<img width="859" alt="image" src="https://github.com/microsoft/vscode/assets/44036128/3e22f383-cfef-4d8b-b51e-8c73d4f99082">

I can also access it on the web since its public
<img width="859" alt="image" src="https://github.com/microsoft/vscode/assets/44036128/eba36482-af2b-4bc4-8613-cd4672030f04">

however in the ports view i don't get to see the fact its been opened
<img width="859" alt="image" src="https://github.com/microsoft/vscode/assets/44036128/a51ecbcf-c310-4fc7-bc0a-39e77865c4e9">

is this because its still in preview? or doesn't work in dev mode?

**Comment by jonathanpv** [comment]
@connor4312 would like thoughts on this

here's my extension repo
https://github.com/jonathanpv/codecontext

and the issue 
https://github.com/jonathanpv/codecontext/issues/1

**Comment by jonathanpv** [comment]
I could be misusing the api though, so could just be my fault entirely

**Comment by alexr00** [comment]
@jonathanpv some questions and thoughts:
- Are you running your extension when connected to a remote (ex. using the Remote SSH extension)?
- It sounds like you're expecting that processes that listen on a port and are running in the same place as your extension get automatically picked up by VS Code and then forwarded using your tunnel provider. This will only happen if you're also connected to a remote. If you're connected to a remote, then this is controlled by the `remote.autoForwardPorts` and `remote.autoForwardPortsSource` settings. Even if you're connect to a remote I don't think this should work as then the remote extension controls the tunnel provider.
- Also proposed API, which we don't have a plan to finalize: the `openTunnel` can also be used to cause VS Code to forward a port (which would eventually call your tunnel provider.

**Comment by jonathanpv** [comment]
> @jonathanpv some questions and thoughts:
> 
> * Are you running your extension when connected to a remote (ex. using the Remote SSH extension)?

No I'm port forwarding only local ports and my code is nearly identical to
- https://github.com/microsoft/vscode/blob/main/extensions/tunnel-forwarding/src/extension.ts

> * It sounds like you're expecting that processes that listen on a port and are running in the same place as your extension get automatically picked up by VS Code and then forwarded using your tunnel provider. This will only happen if you're also connected to a remote. If you're connected to a remote, then this is controlled by the `remote.autoForwardPorts` and `remote.autoForwardPortsSource` settings. Even if you're connect to a remote I don't think this should work as then the remote extension controls the tunnel provider.

Hmm unsure about the remote, but highlevel overview my extension is:
extension.ts
use the code from the local port forwarding extension, the tunnelFactory api
start a server from the extension at port 6969
port forward 6969 as public and warn the user
i can access the url by going through the output logs from the extension but i have to manually check the logs
i'd like to be able to copy the url from the ports tab and I believed the `registerTunnelProvider` would've gotten me that

i have the repo with my example up and should be reproducable, if not let me know if you need a video

> * Also proposed API, which we don't have a plan to finalize: the `openTunnel` can also be used to cause VS Code to forward a port (which would eventually call your tunnel provider.

Hmm, I'll check openTunnel, I ended up using `provideTunnel` from the example I saw from the built-in `tunnel-forwarding` extension, let me check that one out

**Comment by alexr00** [comment]
> -  i can then access the url by going through the extension output logs but i have to manually check the logs and add the port from the template URL which usually looks something like asdf123-{PORT}.devtunnels.com
> 
> - i'd like to be able to copy the url from the ports tab and I believed the registerTunnelProvider would've gotten me that

I think a screen recording would help me understand. 

`registerTunnelProvider` basically just powers the "Ports" view.  It is not expected that extensions call `provideTunnel`. That should only be called by VS Code.

**Comment by jonathanpv** [comment]
So update, using openTunnel from the proposed 'tunnels' api does update the ports UI

**Comment by alexr00** [comment]
`tunnelFactory` is for extension that know how to forward ports and actually implement port forwarding.

`openTunnel` is for extensions that know about a port that needs to be forwarded and want to cause it to be forwarded.
