### ISSUE TITLE
`files.simpleDialog` adds unepected filename at the end of path

### ISSUE THREAD

**Issue by babakfp** [microsoft/vscode#210344]
Does this issue occur when all extensions are disabled?: Yes/No

```
Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
```

```
Edition	Windows 11 Pro
Version	23H2
```

Steps to Reproduce:

https://github.com/microsoft/vscode/assets/44144724/9b9b1695-e77c-4298-aebd-f0dac165b08d

**Comment by alexr00** [comment]
Weird. Do you have `files.dialog.defaultPath` set to anything?

**Comment by babakfp** [comment]
Yes, it's set to `"C:\\Users\\Babak\\Documents\\Code"`.

**Comment by alexr00** [comment]
I'm having trouble figuring out how this state happens. Do you have something from `c:\users\Babak\AppData\Local\Temp` open in VS Code? Or, did you recently have something from that folder open in VS Code?

**Comment by babakfp** [comment]
I remember it was around the time that I was messing around in the C drive and deleting things.
I wasn't able to reproduce it. Feel free to close the issue and I'll send a reproduction whenever it happens again.
