### ISSUE TITLE
debug configuration button missing

### ISSUE THREAD

**Issue by yokarno** [Microsoft/vscode#21049]
- VSCode Version: 1.9.1
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. install VSCode 1.9.1 and install plugin: Lua 5.3 Debugger
2. debug lua code, select Lua Debugger, but no debug configuration button and no response for running debug, how can i do ?
![capture20170222092031498](https://cloud.githubusercontent.com/assets/23699567/23200614/31db3ef4-f910-11e6-9ee3-ea8547410a56.png)

**Comment by roblourens** [comment]
Is there a `.vscode/launch.json` file in this workspace?

**Comment by isidorn** [comment]
No folder vscode (purple status bar) debugging does not support launch configurations.
For that please open a folder and everything will be nicely supported.

**Comment by yokarno** [comment]
got it,thanks
