### ISSUE TITLE
Trailing whitespace toggle doesn't work

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#210460]
## Description

Toggle trailing whitespace doesn't seem to work in this `yml` file:

https://github.com/microsoft/vscode/assets/22350/36cec923-fb51-46c9-b9a6-05871cb50a78

## Playground Example

[Monaco Editor Playground Repro](https://microsoft.github.io/monaco-editor/playground.html?source=v0.48.0-dev-20240416#XQAAAAJcYQAAAAAAAABBqQkHQ5NjdMeMm-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWdz-byeBk1YcRdnRUQzqbsCJuY37p3qFp1H5WVAD24C2ET5tr1CanAsbEY5U58K5e3GPw7FCcZCsZOggBjju0_zkEmyzZgqeM8Sm_jQoNNI63Cxr2O1qj0_UeyJ9vBm72-I0Pj4kET8k-nmJDOWiEzEJNkIeomXTWi6OPOcCGe6M4_SyWC9Wn2i9vaBMANVA7mP2LUnio5iPLbnQQkrXuGdMDbHgOEQfWwWlxW9Yw9gadnknyi_MKfusKKe8xr3-y_2hgL3cH96dXWrnQs0Jlks51xcBvuSCEsPsz41-KXKWtGEByJFBH1JmsgcFmOemuW1en0X5rCFDex8czb3hqeOQB16Z47HowCdzFa8-ivU7sh0pC9B_4Acq-XIdstdGETnmpIdSwQr8Lzi8QlJ59pxQ_A5HBOMyGo9uHuSHXGSrbJVx7WGHQ72CqPTtozKoaRdPEVQ9zLHznJxJ_xtsQrOMNrECEG9ced7bG2gy_WjPnlNIjN2eM3EXpGaaYfzP-9QVK_WEjSIWxGqgAqPTb654j4rWzT4NOYw0cEB2_uvyIHCrmjh7Ai_aTQFRlmBuY7mVyhLF2EUX5lUlgW93SVDuTnBJd7oTmrdb6XAqOm-5erQYw43zwjTozIN3qQqQjyqDFNKAdP6Nk-ZqNiyYrU7rKbGXqZV1n6gakY1spT0Ak_WeszleV7n9nbDcraz4UtSzNiDS_qmf3IGgvhgbTo6q_TIRdanpVp3_OVHGyOwHS50jdh-u1UKbm_1afP6D4V1HPcz-QqzDz1vDp8Kxi0dOK0XFKUyidjgG1cQQlnXOnt2pJpEbURta2Z9mLPV0M8kP637p2alKcoF-nfRdAxUZTz-pATNNh1dS5K57yGmeQ4Lc0KniubC2wwOuowD-g4amgr-JvNSiqReDSNA3FMNYuXwf1I78Qxwx4gzQszrXWVz9Uy4bI-CyaUNM6OdOzfOQmNbH0lCDzCkpiR_EQXzVvECCMIENWHYKe21bENv0KDqISbDUVKomLK3VhVcWE61inFbktzmv1YfnMUsuisnWmPgixqqlKM_DlzsdVoJi7lv0Oo-YJl3HaP31FJdgmUcIIZbA6OkTN6eZ3dsnzoh7Oy-czZaCkT6rOj_qjOlyQogCrGeBkZUznnxq20ZC5o-Dm1wr0wWDYKtM3jKBxiCMEbgNA0jGU5Oi4lNNgAWgreaEY7FjwKD9UdqpAjxN8AZIEVwdTNX9o8cd5xPse1VVVs449ACbGtEYOPd8ynZ2DAHSnJxEIiI-BOMhzleNadSD1rAH4rgkKOjWjgjgA3cJBNXIlsd75DDiqRBhRgvT3RJzBXmNoaPvNCugq0BvZJbUl6zoiTurg5hdqzj-cObSR5laudwjKCLN2z1P2LdcuaCDpjzV2qqLabBzxHAmfYXMbTL8an0QHAIpiYupHoeptm2qxpBzODQsVCeJXRF1JMuggi4iwtqb1u6I7gJjBND_wQfOhOGJ4tp-ZVTnqaGjeo4hulBaG9ajeiurZTqOlNso-KAXA-Z_uLrOF5zCDbEzqc6goQ-5UFVwH6jwleYcygQTPIlUmee44f2V0pXZkD5PMA1xSLgSQR_VAB2TrtG7B-hJcN1Lyq3PWJHtSjGHyAM5EspNrS0KozjRdWIHIvw8rHdrAc0GGCpeXh2NGe7NRABFJiCorXUho2f3kCUwjQEPHZV9okbzat9ZnRr1wOsNbvcLFDEcXp40IvBXhxgz24v033c3xdYxBsq_cZN1b8INkPtmInFke2MWKMHKLpZVoY8qucBqkN65HKuFXf-09g8lWKyATNDLNOAOyKiaW0n0iErfg1ChiYGpEJHXpcoFFsV5b-IT2JixoMjRUeZJdda3ikDdfxJJdZ-FQ_fB5hl8qxrQZh6iyKJwvpjULsszJr-nXp8FPMGIpq10atdSePj7sMaZmkhYD0YxuIXHVjK2DoCkQj0He8bjcE73C6WJEslWeOMaBMTRyITI_vmU_1FR1TtNLXpocGAxI_eh0db0ihHGzEyoJ5taIZO9q7RiVABrNG7aGwPbri9R3LU_w--fIy-FHUJVODN003YiF7VhhSZ4tPA7uext394i__Y1EvueZpt1nKOPmJhrrUKPaDRctgcHAXB8RIW3yDdMjLlgU3DJuSXOEdXHSKWHwurBwHapCm24kxu6wM2495fvL2lM533KVr2LbcdbQIvF4amfAXS8fPaGh0n4UmiwvXJVMLCxhzNoZ9bj_r44tm09HSWlsBnsgH39bY-592IOUGrGT0buzsIemlbPDHQMOjdG7mS8v1OxjVBWTvagXz41sTqzUdznSu5DUfdhSvio50-q7vz594jBD3fAKdj_Ly1RwvENZjpn_GKkSkvx6PM43LdwnVoFkrmGgk2gJ53xkuPxPluLDwyD0fcI_e8CQKe3Sjk12IYHfJ6W_GoWhZ2QgaHO_e5y5a6_6bam_KYPbgKyZpmx4uVSwQ0WiwcHTTplNR2fd0FVwU6fBZq7EgHOvZn0JMLBuQ62S4MewAiHfMI7xSpPTGZONTB54peI7md5SZ1TWfR51yJXh9st6KtEtyBpGiLMaYO0Xsy-E3kgfBk5UZV0frWutnbtRuCczTi1DQ79OgC6UtzHBqgwTARW3QX7BssIfHXXX5yuz5z3Bgq9b8yyI5bULTi2PWHFQZncWJ4YQvAuQ-U7fUI9ga9NiXGjwzGgtooodz2WYCvrI262MODDAxrX60_8RKO7wLJdrHcEqE8WAceEMqNO6-0YPDWLlXntSFvo_1YwyWI07ZArFrNl7l0mOXRiEwpqRnkeRSA_-_4j9sT7MiTINCAxDvy7tjLRaL2Gc94s_R6hpIfM8DyImaIEEB1WBuKX_1r0yFXpvJu7-Xq11DqV8k7-pXO0m12a9DYjZOWT9vTfcHXAqs-6a55y8ovwJdEc1ILb7GpOrdcAws6meuLXpXbP5o8Scv4G9Dy-oguG8ajQ6v3U0exw6mlTlU5UQuOR1Z-KLqYUf4L-Zf22XlRhyHo0NsoA_x_2AHpNZ5m7H_tXt06Dwu1BYaaz0ROdW9Ng2yJLfJyG8DoZOg-k4w_OhMWWYzKNokDfrtizf0VCaFYQqNJlUnQcafLOfFPF7tcgM21hQ1KXBmixXZnkfqHeaCx3FLHwEofbswkD8fHFkDBFLTqjU3yZCjIH1imF8f1DxWHbVvVEnDRqLxVz653N1sjmGW0OJWnVVMRI07EKScFwhd4J6r5iWxriplQnSJWlVGNMFaoRoOQX4-BiT3ndtx3Ib9IFKbaA111moIfFYatQiUjm1CHwFb14USqT3H2VexTgDsXMRne4o5Kw_OhDrxc3NExXGcDjNsSTEzjjwmIjNVIs7CsFpVY9RLTp0pCopSGYEjayZctxPX5sjAT-mdl3G_9OZPWjLdgYyDrutZ6wFnFZKrkmCzAHgLD-VrnUt7MzFDS81_f_zJ7mwvCXUaLlGiL2sz11ItJblosWPHNZ1SonAN_tYuN_QssvZiAwzc9lbnpLgjiKfvz26SWZ7pzLp3jI58Xjjjy2X00T0GcAFI-M8FYOEQI6TnXSFkB7Q277Dq3oGucD_2wwfR0S_bGSu37taGXEpyBXtCdsaTj0xS4IX7jy9G8fnQ0VMz8J4oiUzbZXUqNbWMUPRpPdojPurzjqgk5pxk_1GI21wJldCJAdT3KMAaJ90onqHsajj1iacOTBky2zm_-1Scy8) (click on "use latest dev" to verify a future bug-fix)

**Comment by hediet** [comment]
@bpasero this seems to be a problem of untitled editors not getting the correct editor options through the editor components.

**Comment by hediet** [comment]
![Code_-_OSS_G9b036v9gL](https://github.com/microsoft/vscode/assets/2931520/17f5b492-6f8f-413a-a45d-4da59b6cd38a)

![Code_-_OSS_U0Ggk1RE8Z](https://github.com/microsoft/vscode/assets/2931520/8c334f0b-f34b-4eab-bffe-7627d2bb320e)

In `override updateOptions(changedOptions: IDiffEditorOptions): void {` I always get `ignoreTrimWhitespace` = false, even if it is true in the settings.

**Comment by bpasero** [comment]
@hediet I am asking because Joaos video does not show any untitled editor I think

**Comment by hediet** [comment]
Hmm, it works reliable for me in an empty profile and empty workspace, investigating...

**Comment by hediet** [comment]
Seems like `affectsConfiguration` has some issues:

![Code_-_Insiders_UYmNPjEBlj](https://github.com/microsoft/vscode/assets/2931520/305f4c37-1597-4cbd-9d8c-eac1f0fb3ef8)

---

Wow, seems like this setting is disabled for yaml files:
![Code_-_Insiders_EhmgqgH0wN](https://github.com/microsoft/vscode/assets/2931520/6e41294d-83da-405b-b1fa-81ac82353519)

And the language override seems to have precedence over the user settings. @sandy081 is this intentional that language specific configuration defaults have higher precedence than non-language specific user-settings?

**Comment by sandy081** [comment]
> And the language override seems to have precedence over the user settings. @sandy081 is this intentional that language specific configuration defaults have higher precedence than non-language specific user-settings?

Yes this is by design and it is this way from the time we introduced lang specific settings.

> But this really feels like something that should be handled by the configuration system.

Can you please elaborate?

**Comment by andreamah** [comment]
> Playground Example
> [Monaco Editor Playground Repro](https://microsoft.github.io/monaco-editor/playground.html?source=v0.48.0-dev-20240416#XQAAAAJcYQAAAAAAAABBqQkHQ5NjdMeMm-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWdz-byeBk1YcRdnRUQzqbsCJuY37p3qFp1H5WVAD24C2ET5tr1CanAsbEY5U58K5e3GPw7FCcZCsZOggBjju0_zkEmyzZgqeM8Sm_jQoNNI63Cxr2O1qj0_UeyJ9vBm72-I0Pj4kET8k-nmJDOWiEzEJNkIeomXTWi6OPOcCGe6M4_SyWC9Wn2i9vaBMANVA7mP2LUnio5iPLbnQQkrXuGdMDbHgOEQfWwWlxW9Yw9gadnknyi_MKfusKKe8xr3-y_2hgL3cH96dXWrnQs0Jlks51xcBvuSCEsPsz41-KXKWtGEByJFBH1JmsgcFmOemuW1en0X5rCFDex8czb3hqeOQB16Z47HowCdzFa8-ivU7sh0pC9B_4Acq-XIdstdGETnmpIdSwQr8Lzi8QlJ59pxQ_A5HBOMyGo9uHuSHXGSrbJVx7WGHQ72CqPTtozKoaRdPEVQ9zLHznJxJ_xtsQrOMNrECEG9ced7bG2gy_WjPnlNIjN2eM3EXpGaaYfzP-9QVK_WEjSIWxGqgAqPTb654j4rWzT4NOYw0cEB2_uvyIHCrmjh7Ai_aTQFRlmBuY7mVyhLF2EUX5lUlgW93SVDuTnBJd7oTmrdb6XAqOm-5erQYw43zwjTozIN3qQqQjyqDFNKAdP6Nk-ZqNiyYrU7rKbGXqZV1n6gakY1spT0Ak_WeszleV7n9nbDcraz4UtSzNiDS_qmf3IGgvhgbTo6q_TIRdanpVp3_OVHGyOwHS50jdh-u1UKbm_1afP6D4V1HPcz-QqzDz1vDp8Kxi0dOK0XFKUyidjgG1cQQlnXOnt2pJpEbURta2Z9mLPV0M8kP637p2alKcoF-nfRdAxUZTz-pATNNh1dS5K57yGmeQ4Lc0KniubC2wwOuowD-g4amgr-JvNSiqReDSNA3FMNYuXwf1I78Qxwx4gzQszrXWVz9Uy4bI-CyaUNM6OdOzfOQmNbH0lCDzCkpiR_EQXzVvECCMIENWHYKe21bENv0KDqISbDUVKomLK3VhVcWE61inFbktzmv1YfnMUsuisnWmPgixqqlKM_DlzsdVoJi7lv0Oo-YJl3HaP31FJdgmUcIIZbA6OkTN6eZ3dsnzoh7Oy-czZaCkT6rOj_qjOlyQogCrGeBkZUznnxq20ZC5o-Dm1wr0wWDYKtM3jKBxiCMEbgNA0jGU5Oi4lNNgAWgreaEY7FjwKD9UdqpAjxN8AZIEVwdTNX9o8cd5xPse1VVVs449ACbGtEYOPd8ynZ2DAHSnJxEIiI-BOMhzleNadSD1rAH4rgkKOjWjgjgA3cJBNXIlsd75DDiqRBhRgvT3RJzBXmNoaPvNCugq0BvZJbUl6zoiTurg5hdqzj-cObSR5laudwjKCLN2z1P2LdcuaCDpjzV2qqLabBzxHAmfYXMbTL8an0QHAIpiYupHoeptm2qxpBzODQsVCeJXRF1JMuggi4iwtqb1u6I7gJjBND_wQfOhOGJ4tp-ZVTnqaGjeo4hulBaG9ajeiurZTqOlNso-KAXA-Z_uLrOF5zCDbEzqc6goQ-5UFVwH6jwleYcygQTPIlUmee44f2V0pXZkD5PMA1xSLgSQR_VAB2TrtG7B-hJcN1Lyq3PWJHtSjGHyAM5EspNrS0KozjRdWIHIvw8rHdrAc0GGCpeXh2NGe7NRABFJiCorXUho2f3kCUwjQEPHZV9okbzat9ZnRr1wOsNbvcLFDEcXp40IvBXhxgz24v033c3xdYxBsq_cZN1b8INkPtmInFke2MWKMHKLpZVoY8qucBqkN65HKuFXf-09g8lWKyATNDLNOAOyKiaW0n0iErfg1ChiYGpEJHXpcoFFsV5b-IT2JixoMjRUeZJdda3ikDdfxJJdZ-FQ_fB5hl8qxrQZh6iyKJwvpjULsszJr-nXp8FPMGIpq10atdSePj7sMaZmkhYD0YxuIXHVjK2DoCkQj0He8bjcE73C6WJEslWeOMaBMTRyITI_vmU_1FR1TtNLXpocGAxI_eh0db0ihHGzEyoJ5taIZO9q7RiVABrNG7aGwPbri9R3LU_w--fIy-FHUJVODN003YiF7VhhSZ4tPA7uext394i__Y1EvueZpt1nKOPmJhrrUKPaDRctgcHAXB8RIW3yDdMjLlgU3DJuSXOEdXHSKWHwurBwHapCm24kxu6wM2495fvL2lM533KVr2LbcdbQIvF4amfAXS8fPaGh0n4UmiwvXJVMLCxhzNoZ9bj_r44tm09HSWlsBnsgH39bY-592IOUGrGT0buzsIemlbPDHQMOjdG7mS8v1OxjVBWTvagXz41sTqzUdznSu5DUfdhSvio50-q7vz594jBD3fAKdj_Ly1RwvENZjpn_GKkSkvx6PM43LdwnVoFkrmGgk2gJ53xkuPxPluLDwyD0fcI_e8CQKe3Sjk12IYHfJ6W_GoWhZ2QgaHO_e5y5a6_6bam_KYPbgKyZpmx4uVSwQ0WiwcHTTplNR2fd0FVwU6fBZq7EgHOvZn0JMLBuQ62S4MewAiHfMI7xSpPTGZONTB54peI7md5SZ1TWfR51yJXh9st6KtEtyBpGiLMaYO0Xsy-E3kgfBk5UZV0frWutnbtRuCczTi1DQ79OgC6UtzHBqgwTARW3QX7BssIfHXXX5yuz5z3Bgq9b8yyI5bULTi2PWHFQZncWJ4YQvAuQ-U7fUI9ga9NiXGjwzGgtooodz2WYCvrI262MODDAxrX60_8RKO7wLJdrHcEqE8WAceEMqNO6-0YPDWLlXntSFvo_1YwyWI07ZArFrNl7l0mOXRiEwpqRnkeRSA_-_4j9sT7MiTINCAxDvy7tjLRaL2Gc94s_R6hpIfM8DyImaIEEB1WBuKX_1r0yFXpvJu7-Xq11DqV8k7-pXO0m12a9DYjZOWT9vTfcHXAqs-6a55y8ovwJdEc1ILb7GpOrdcAws6meuLXpXbP5o8Scv4G9Dy-oguG8ajQ6v3U0exw6mlTlU5UQuOR1Z-KLqYUf4L-Zf22XlRhyHo0NsoA_x_2AHpNZ5m7H_tXt06Dwu1BYaaz0ROdW9Ng2yJLfJyG8DoZOg-k4w_OhMWWYzKNokDfrtizf0VCaFYQqNJlUnQcafLOfFPF7tcgM21hQ1KXBmixXZnkfqHeaCx3FLHwEofbswkD8fHFkDBFLTqjU3yZCjIH1imF8f1DxWHbVvVEnDRqLxVz653N1sjmGW0OJWnVVMRI07EKScFwhd4J6r5iWxriplQnSJWlVGNMFaoRoOQX4-BiT3ndtx3Ib9IFKbaA111moIfFYatQiUjm1CHwFb14USqT3H2VexTgDsXMRne4o5Kw_OhDrxc3NExXGcDjNsSTEzjjwmIjNVIs7CsFpVY9RLTp0pCopSGYEjayZctxPX5sjAT-mdl3G_9OZPWjLdgYyDrutZ6wFnFZKrkmCzAHgLD-VrnUt7MzFDS81_f_zJ7mwvCXUaLlGiL2sz11ItJblosWPHNZ1SonAN_tYuN_QssvZiAwzc9lbnpLgjiKfvz26SWZ7pzLp3jI58Xjjjy2X00T0GcAFI-M8FYOEQI6TnXSFkB7Q277Dq3oGucD_2wwfR0S_bGSu37taGXEpyBXtCdsaTj0xS4IX7jy9G8fnQ0VMz8J4oiUzbZXUqNbWMUPRpPdojPurzjqgk5pxk_1GI21wJldCJAdT3KMAaJ90onqHsajj1iacOTBky2zm_-1Scy8) (click on "use latest dev" to verify a future bug-fix)

Not sure how to toggle trailing whitespace in this editor such that I can verify this. I don't see any diff when I click the link- am I supposed to?

**Comment by hediet** [comment]
This bug actually does not reproduce in the monaco editor, as it is an issue with the user settings.

**Comment by rzhao271** [comment]
@hediet what are some verification steps for this issue?
