### ISSUE TITLE
"Refused to load resource C:\..\seti.woff"

### ISSUE THREAD

**Issue by mee8yt** [microsoft/vscode#210474]
- VS Code Version: 1.75.0 -> 1.88.1 (all versions specified in the range)
- OS Version: Windows 10 22H2

Steps to Reproduce:

1. Launch VS Code
this error does not appear by itself, when you try to open VS CODE, it immediately closes.
The error was output via Command Prompt, and it was written to the console. I couldn't figure out the Crash Report about which is written in "Native Crash Issues" either

![image](https://github.com/microsoft/vscode/assets/129200349/db99e3eb-c5e8-45a0-bd9f-5d07e4eb36f3)

What have I tried:
- reinstalled VS Code
- installed the inside version (nothing new has happened)
- updated Windows (in the update center)
- checked windows environment variables

The bug does not appear on version 1.74.0 and below

I looked at the path mentioned in the error message, and it simply does not exist. I don't know, maybe it is referring to files not from disk, but suppose from a web resource

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/185298

Please follow the steps here https://github.com/microsoft/vscode/issues/185298#issuecomment-1745188533 to resolve the issue.
