### ISSUE TITLE
terminal fails to split after running command in git bash with shell integration enabled

### ISSUE THREAD

**Issue by cpendery** [microsoft/vscode#210413]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.89.0-insider (user setup)
Commit: 6f91cdc47ae284c0a6fec5aa597b9cbcf3cd185c
Date: 2024-04-15T05:50:22.934Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Open Git Bash with shell integration enabled
2. Run a command
3. Try to split the terminal

![image](https://github.com/microsoft/vscode/assets/35637443/023b4d9a-4157-4eb4-8934-a3d0294fa5ad)

**Comment by cpendery** [comment]
I can work on fixing this since I created the issue adding git bash shell integration

**Comment by piyu-sh** [comment]
Hi @cpendery @Tyriar @meganrogge  this issue still happens on the stable(1.89.1) and insider build(1.90.0).

System info:

Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631


![image](https://github.com/microsoft/vscode/assets/7107647/ac0e9c8c-da92-4056-86fc-14b69f63edc5)
