### ISSUE TITLE
Watch task should execute automatically on workspace open

### ISSUE THREAD

**Issue by trstringer** [Microsoft/vscode#2104]
In the `tasks.json` configuration file, you can specify a task to be defined as a watch task by stating `isWatching: true`.  I don't believe I see any benefit to explicitly stating that a task is a watch task.

What I believe would be useful is if the watch task defined in `tasks.json` is actually started automatically by VS Code upon opening the workspace.

From what I can tell, currently you need to explicitly start your watch task `task <watch-task-name>`.

**Comment by kripod** [comment]
This is an extremely important feature which shall be implemented as soon as possible.

I'd be careful about security concerns, though: On the first launch of a specific project, VS Code should ask if the user wants to enable automatic watching, and warn for potential security issues.

**Comment by alexr00** [comment]
Duplicate of #17147

**Comment by dbaeumer** [comment]
Closing as duplicate then.
