### ISSUE TITLE
Debugger is shaking/shifting constantly during debug

### ISSUE THREAD

**Issue by gholt-zift** [microsoft/vscode#210494]
Type: <b>Bug</b>

So far, I didn't do anything other than debug a file I've been using daily to build an app. For some reason, the code is rapidly shifting/shaking while I'm paused on a breakpoint. 

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.20GB (2.00GB free)|
|Process Argv|--crash-reporter-id 915b888a-18cc-405b-844d-1a5346b4c42b|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|2.19.0
aws-amplify-vscode|aws|0.0.4
vscode-intelephense-client|bme|1.10.4
npm-intellisense|chr|1.4.5
vscode-eslint|dba|2.4.4
javascript-ejs-support|Dig|1.3.3
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|10.4.0
gc-excelviewer|Gra|4.2.59
vscode-graphql|Gra|0.9.3
vscode-graphql-syntax|Gra|1.3.5
rest-client|hum|0.25.1
live-share-for-aws-cloud9|ian|0.11.4
aws-cli-configure|mar|0.3.0
rainbow-csv|mec|3.11.0
eclipse-new-java-project|mel|1.0.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.29.0
vscode-edge-devtools|ms-|2.1.5
debugpy|ms-|2024.4.0
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
jupyter|ms-|2024.3.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.354.0
remote-wsl|ms-|0.88.0
cpptools|ms-|1.19.9
vsliveshare|ms-|1.0.5918
vscode-codedeploy|mzi|0.5.3
vetur|oct|0.37.3
indent-rainbow|ode|8.3.1
postman-for-vscode|Pos|1.0.1
java|red|1.29.0
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
php-debug|rob|1.14.0
firacode|Sey|2.2.1
code-settings-sync|Sha|3.4.3
javafx-support|shr|0.0.1
sonarlint-vscode|Son|4.4.2
code-spell-checker|str|3.0.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.26.0
vscode-java-test|vsc|0.41.0
vscode-maven|vsc|0.44.0
vscode-aws-console|vsc|0.0.5
vscode-icons|vsc|12.7.0
vscode-todo-highlight|way|1.0.5
php-debug|xde|1.34.0
php-pack|xde|1.0.3
php-intellisense|zob|1.3.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572
bdiig495:31013172

```

</details>

**Comment by gholt-zift** [comment]
For some reason this stopped being an issue after removing all breakpoints and replacing them.

**Comment by a-merezhanyi** [comment]
I encountered this issue when `debug.inlineValues` was set to `on` or `auto`. Setting it to `off` solved "shaking/shifting", but it made debugging less convenient.
