### ISSUE TITLE
Newline in Files search Regex not working

### ISSUE THREAD

**Issue by rnemec** [Microsoft/vscode#21041]
- VSCode Version: 1.9.1
- OS Version: Mac OS 10.11.6

Steps to Reproduce:

1. Go to the Search sidebar
2. Turn on Regex
3. Search for something like "module\.exports\.(.*);" (without the quotes) - that works OK
4. Change that to "module\.exports\.(.*);\n" - still works OK
5. Change that to "module\.exports\.(.*);\nfunction" - does only find in the open files.
6. Note that in the editor search/replace (CMD-F), it works perfect (both search and replace too)

To make things even worse, when the search sidebar finds something using a regex with newline, if you try to use Replace, the sidebar UI gets completely screwed.

**Comment by roblourens** [comment]
This isn't supported yet - #15727
