### ISSUE TITLE
Typing `/**` should not automatically create a block comment in which each line is prefixed with `*`

### ISSUE THREAD

**Issue by rgrove** [microsoft/vscode#21042]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0

---

Currently, typing `/**` in a JavaScript or TypeScript file results in the insertion of an auto-closed block comment that looks like this:

```js
/** <cursor> */
```

When you press <kbd>enter</kbd>, you end up with a comment body in which each line is automatically prefixed by `*`:

```js
/**
 * <cursor>
 */
```

The editor is trying to be helpful, but there's no actual reason (other than personal aesthetic preference) to prefix each line of a multi-line JavaScript or TypeScript comment with a `*`. I'm not aware of any documentation tool that actually requires prefixed lines (this includes JSDoc).

I prefer my multi-line comment blocks not to have prefixed lines, but VSCode makes this a lot harder than it needs to be. At a minimum, it should be possible to disable comment autocompletion. Please consider removing this feature or making it configurable. Thanks!

**Comment by VitorLuizC** [comment]
Please create a setting to enable/disable this feature.

**Comment by axefrog** [comment]
I use this feature all the time. As @VitorLuizC says, it should be a setting that can be disabled, rather than something to be removed altogether.

**Comment by igor-dragutinovic** [comment]
I started working on this issue and located place in code where I can add IF clause that will handle this behavior based on user setting.
Which configuration class should I use for fetching user settings from languageConfigurationRegistry.ts?
I tried with CommonEditorConfiguration, abstract class. It is implemented in Configuration.ts, but it is not accessible from languageConfigurationRegistry.ts.

**Comment by mjbvz** [comment]
You'll need to make the js/ts language configuration dynamic. See how the experimental folding provider is registered for example: https://github.com/Microsoft/vscode/blob/32bdb4663258bf34228b007e7858ae6c91e5beb9/extensions/typescript/src/languageProvider.ts#L122

**Comment by igor-dragutinovic** [comment]
Thanks for the suggestion. 
When I use the proposed approach, I can't import workspace from 'vscode' due to following error
loader.js:246
Detail: 
loader.js:247
Error: Cannot find module 'vscode'
loader.js:247
Error: Cannot find module 'vscode'
loader.js:249
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (D:\Play\github\vscode\.build\electron\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at nodeRequire (d:\Play\github\vscode\out\vs\loader.js:1660:33)
    at NodeScriptLoader.load (d:\Play\github\vscode\out\vs\loader.js:732:40)
    at OnlyOnceScriptLoader.load (d:\Play\github\vscode\out\vs\loader.js:578:33)
    at loadNextPath (d:\Play\github\vscode\out\vs\loader.js:1426:42)
    at Object.errorback (d:\Play\github\vscode\out\vs\loader.js:1434:26)
Here are the modules that depend on it:
Array(1) ["vs/editor/common/modes/languageConfigurationRegist…"]

**Comment by mjbvz** [comment]
@igor-dragutinovic Without seeing your code I'm not sure what is going wrong. Do you want to open a work in progress PR so I can take a look?

**Comment by igor-dragutinovic** [comment]
Can anyone check #46544 ?

**Comment by mjbvz** [comment]
Yeah sorry. Thanks for taking a look but that PR had merge conflicts when I looked last month and my comments had not been addressed. Please resolve the conflicts and address the comments

**Comment by igor-dragutinovic** [comment]
Comments are addressed, except the extracting some values to constants, you offered help regarding that. As for the merge, it seems that affected folders were renamed. As I am not very good with git commands, I will probably create new pull request with fresh code from master, apply changes there and commit. 
Thanks again for the support.
