### ISSUE TITLE
Ability to move Run and Run Selection buttons from right to left

### ISSUE THREAD

**Issue by maorzoh** [microsoft/vscode#210438]
![image](https://github.com/microsoft/vscode/assets/98945870/f8f2e4c1-27fa-413f-a1dc-f1fc1ed11f8a)

I'm unable to do that and that would be a great option. by far more convenient when using the mouse.

**Comment by maorzoh** [comment]
I'm unable to do that and that would be a great option. by far more convenient when using the mouse.

**Comment by roblourens** [comment]
Sorry, not clear what you want. You want which button to go where?

**Comment by maorzoh** [comment]
Hi Rob,
I want the Run and Run selection buttons on the right top bar to move left if possible.

Maor Zohar
***@***.***

Sent from my iPhone…
________________________________
מאת: Rob Lourens ***@***.***>
‏‏נשלח: Friday, May 24, 2024 1:24:20 AM
‏‏אל: microsoft/vscode ***@***.***>
עותק: Maor Zohar ***@***.***>; Author ***@***.***>
‏‏נושא: Re: [microsoft/vscode] Ability to move Run and Run Selection buttons from right to left (Issue #210438)


Sorry, not clear what you want. You want which button to go where?

**Comment by roblourens** [comment]
The editor tabs go there, so I think this is the best spot for these buttons
