### ISSUE TITLE
Request Feature: Integrated Terminal Auto Run Command

### ISSUE THREAD

**Issue by linroex** [Microsoft/vscode#21044]
Hi

I have a suggest about Integrated Terminal, when Integrated Terminal start, auto run some special command (by lang, by project), This feature can use at:

- Python virtualenv "source /env/bin/activate"
- ssh-add....etc

I am not sure is this can do now, If not, I can handle this request.

**Comment by Tyriar** [comment]
I think something like this would be seldom used and would prefer to defer to extensions to implement this behavior. The extension API should allow you to build what you're after https://code.visualstudio.com/Docs/extensionAPI/vscode-api
