### ISSUE TITLE
Cannot set markdown.editor.filePaste.enabled to always

### ISSUE THREAD

**Issue by HareToAme** [microsoft/vscode#210400]
- VS Code Version: 1.88.1
- OS Version: win11

![图片](https://github.com/microsoft/vscode/assets/85005258/19b34cba-f00c-4836-aff2-0deb1d046f42)

I want to set `markdown.editor.filePaste.enabled` to `always`, but I can't.

![markdown editor filePaste enabled](https://github.com/microsoft/vscode/assets/85005258/e4785466-d643-4989-a911-27b8289cdbf1)

![无标题111111](https://github.com/microsoft/vscode/assets/85005258/da81aa1d-5ee3-4b89-96cf-d2eb00d5d81c)

The smart mode in the Hugo blog's md files is behaving too dumb, so I had to switch to the `always` option. But now I can't set it to `always`.

**Comment by HareToAme** [comment]
I downgraded to version 1.87.2 and got rid of the above-mentioned issue.
![图片](https://github.com/microsoft/vscode/assets/85005258/d97ed62e-d73f-45de-9088-e1a7bbd4a0a3)

**Comment by mjbvz** [comment]
The setting will still work if you add in the json. Just ignore the warnings for now. Will be fixed in the next insiders build

**Comment by HareToAme** [comment]
> The setting will still work if you add in the json. Just ignore the warnings for now. Will be fixed in the next insiders build

I tried adding `always` in the JSON in version 1.88.1, but it didn't actually have any effect. The vscode markdown editor always generates a path string for the file instead of a markdown link.
