### ISSUE TITLE
Feature Request: initialize emmet config

### ISSUE THREAD

**Issue by ogasawara-k** [Microsoft/vscode#21040]
- VSCode Version: 1.10.0-insider (Japanese)
- OS Version: Windows 10 ver:1607 (Japanese)

Steps to Reproduce:

1. install all default ( use: VSCodeSetup-1.9.0-insider.exe )
2. `C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\node_modules\emmet\lib\snippets.json` is default
```json
{
	"variables": {
		"lang": "en",
	...
```
3. type emmet
```html
![tab]
```
4. change
```html
<!DOCTYPE html>
<html lang="en">
...
```

## request

I hope same local setting (vscode lang: Japanese )

- `"lang": "en"` -> `"lang": "ja"`

```html
<!DOCTYPE html>
<html lang="ja">
...
```

**Comment by freMea** [comment]
If users could simply edit and create **emmet** snippets like any other snippet language, it would be easy to change _${lang}_ variable among many other **emmet** things. (see docs [here](https://docs.emmet.io/customization/snippets)).

See #23476

**Comment by ramya-rao-a** [comment]
@ogasawara-k Am sorry it took me so long to respond.

You can do this by customizing the snippets.json file

For example, if you want to use `"lang": "ja"`

- Create a file `snippets.json` with the below content
```json
{
    "variables":{
        "lang":"jp"
    }
}
```
- In your User settings, add setting `"emmet.extensionsPath"` . The value should be the directory where you created the `snippets.json`
- Restart VS Code

For more information on what else you can customize this way in the `snippets.json` file, read https://docs.emmet.io/customization/snippets/

**Comment by ogasawara-k** [comment]
thanks.
I'll give it a try.
