### ISSUE TITLE
Can't have tables with borders because of hard coded !important style

### ISSUE THREAD

**Issue by deanm0000** [microsoft/vscode#210462]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1 (system setup)
- OS Version: Windows_NT x64 10.0.19045

In this snippet
https://github.com/microsoft/vscode/blob/5ccc2db0a2ed24e8c0dc3ecd7d515e4f76c87e69/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L424-L429

the major table related tags have border set to none with !important which makes it so that jupyter notebook tables can't have a border without jumping through hoops to override that !important tag.

On my own installation, I patched out the !important and now my jupyter notebook tables can have borders and I'm not seeing any ill effects. It'd be nice if the next VSC update wouldn't revert that change.

**Comment by amunger** [comment]
run this code in a python cell in a notebook, it should output a table with a border.

```
from IPython.display import HTML
HTML('<table style="border-width: 1px; border-color: red; border-style: solid;" ><tr><td>1</td><td>2</td></tr><tr><td>3</td><td>4</td></tr></table>')
```
