### ISSUE TITLE
Cargo missing

### ISSUE THREAD

**Issue by mering** [microsoft/vscode#210454]
`cargo` is missing from [`.devcontainer`](https://github.com/microsoft/vscode/tree/main/.devcontainer) config and [Wiki](https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites) documentation.

Running `./scripts/code-cli.sh serve-web --help` errors out with `spawn cargo ENOENT`.

**Comment by justschen** [comment]
cc @connor4312 i believe? wiki hasn't had changes regarding that, may just be missing or not specified?

**Comment by connor4312** [comment]
I should update both the devcontainer and wiki

**Comment by mering** [comment]
@connor4312 any updates?
