### ISSUE TITLE
terminal sticky scroll shows command marker for status and copy

### ISSUE THREAD

**Issue by cpendery** [microsoft/vscode#210419]
I'd like to be able to see the command's outcome in the sticky scroll view. Could we add the command marker to the sticky scroll view just like it is for the normal view? This would also allow copying easier without having the scroll up through large outputs

Sticky scroll: 
![image](https://github.com/microsoft/vscode/assets/35637443/cdcc8654-f9dd-4c81-80c7-95406db48d3d)
Normal view: 
![image](https://github.com/microsoft/vscode/assets/35637443/6563268c-e231-4249-9d9b-32de5be82174)

**Comment by Tyriar** [comment]
Yep, definitely want to do this, plus we wanted to explore attaching the quick fix to the sticky command as well instead of the new prompt: https://github.com/microsoft/vscode/issues/198116
