### ISSUE TITLE
Contributed snippet not working in embedded language

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#21046]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|concrete|vscode|0.1.10|
|vscode-eslint|dbaeumer|1.2.6|
|tslint|eg2|0.8.1|
|Theme-TomorrowKit|ms-vscode|0.1.3|
|debugger-for-chrome|msjsdiag|2.5.3|
|vetur|octref|0.3.6|
|vuehelper|oysun|0.0.9|
|vscode-icons|robertohuertasm|7.2.0|
|language-stylus|sysoev|1.6.0|
|vim|vscodevim|0.5.3|

---

1. Install an extension that contributes js snippets
2. Try using it in `<script>` region in a html file
3. Snippet won't be suggested.

However, if the snippet is in user-defined `javascript.json`, it'll be prompted when editing `<script>` region.

**Comment by octref** [comment]
Probably should go to @jrieken.

**Comment by jrieken** [comment]
Yes, the language isn't known yet because no file of it, just embedded content, has been opened yet. Because we lazy load languages and their snippets this happens...
