### ISSUE TITLE
SQL Table Mysteriously Deletes Rows

### ISSUE THREAD

**Issue by aemmertz001** [microsoft/vscode#210526]
I just got a message that this issue was closed because it is about VS Code. That is INCORRECT. This is about a Codespace for Wilmington University for a class on MySQL. Can someone please look into how an entire table was mysteriously deleted/dropped?

When preforming simple quries on the KimTay Databases' SALES_ REP table it does not return row values. The query SELECT REP_ID FROM SALES_REP; only returns the column header REP_ID. And, SELECT * FROM SALES_REP; only returns all Column headers. This one table will not return the row values. I did not DROP or DELETE any data from this table.

I resolved the issue by inserting all of the data for the table. The college has no explanation. How were these rows deleted from this table? Who has control of this database? Someone please look into how an entire table could be effected.

Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
Please contact the course support channel.

**Comment by gjsjohnmurray** [comment]
Related - #210522

**Comment by gjsjohnmurray** [comment]
Please understand that you are using the Web browser variant of VS Code when you interact with the GitHub Codespace that your college provides you. The "Report Issue" option creates issues (tickets) on the GH repository for VS Code.

I think your course support people should be using other channels.

For more context please see https://docs.github.com/en/codespaces/troubleshooting
