### ISSUE TITLE
Minimap obscures 'Add Configuration' Button

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#21053]
Pls see the attached screenshot

![image](https://cloud.githubusercontent.com/assets/172399/23203004/f15e15d8-f8e0-11e6-8642-b7fae45907e3.png)

Since we now support Add Configuration in the drop down one option is to no longer show this in-place button (should verify with telemetry).

**Comment by alexandrudima** [comment]
There are a few places outside the editor core where we need to account for the minimap width

**Comment by alexandrudima** [comment]
Let's track in #20936
