### ISSUE TITLE
theme auto detect stopped working after switching macbooks

### ISSUE THREAD

**Issue by squarewave24** [microsoft/vscode#210563]
Does this issue occur when all extensions are disabled?: Yes

using settings sync, all of my settings appear to be identical to my old machine, but i can't get theme auto detect to work. 

```
  "window.systemColorTheme": "auto",
  "workbench.preferredLightColorTheme": "Default Light+",
  "window.autoDetectColorScheme": true,
  "workbench.preferredDarkColorTheme": "Default Dark+",
  "workbench.colorTheme": "Default Light+"
```

i've used this feature for 1+ years on my old machine. 
to test, i've tried both: toggling the OS theme, and regular times for day/night. neither approach works, but that worked seamlessly on old machine. 

i've tried toggling auto detect color scheme.

i've also tried omitting colorTheme 
```
  "window.systemColorTheme": "auto",
  "workbench.preferredLightColorTheme": "Default Light+",
  "window.autoDetectColorScheme": true,
  "workbench.preferredDarkColorTheme": "Default Dark+",
```

- Mac OS Version:  14.4.1 (23E224)
- VS Code Version: 1.88.1 (Universal)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:42:52.765Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

**Comment by kalebers** [comment]
See if this comment helps: 
https://github.com/microsoft/vscode/issues/158314#issuecomment-1925910407

**Comment by squarewave24** [comment]
> See if this comment helps: [#158314 (comment)](https://github.com/microsoft/vscode/issues/158314#issuecomment-1925910407)

yep! that did it. namely just **removing** this line:
`"window.systemColorTheme": "auto",`

**Comment by kalebers** [comment]
Glad that helped! Any trouble, you know where to find us! :)

**Comment by aeschli** [comment]
This got fixed by https://github.com/microsoft/vscode/pull/211265
