### ISSUE TITLE
Improve Detail for JSDoc Completion Item

### ISSUE THREAD

**Issue by mattbierner** [Microsoft/vscode#21057]
For the JSDoc completion item, the details are not very useful:

![screen shot 2017-02-22 at 12 35 26 am](https://cloud.githubusercontent.com/assets/212305/23203330/ea2f118a-f896-11e6-84da-daca8d3d9abb.png)

We should either use the right-side text of the completion item for the `JSDoc Comment` text, or add some real information about the completion item to the details

**Comment by mjbvz** [comment]
Moved to use `detail` instead of `documentation` for the description
