### ISSUE TITLE
Running Issue

### ISSUE THREAD

**Issue by manishkmr49** [microsoft/vscode#210548]
Type: <b>Performance Issue</b>

my question is quite simple and is regarding VSCode (obviously). I have the extention "code runner" in VSCode and I run my code either by code runner or use VSCode run-button. The problem is VSCode runs the code once only. When I modify the code and try to re-run the code again it doesn't show anything in the terminal. I need to close the terminal window first in order to get it run again.

I use the Java as a programming language. If any more information is needed, please let me know.

Thank you a lot

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (1.03GB free)|
|Process Argv|--crash-reporter-id da241573-5b86-4415-97f2-44f515bf3ad5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   149	 16016	code main
    0	    97	  1148	shared-process
    0	   233	  7524	window [1] (Extension: JSP Language Support - String - Visual Studio Code)
    0	  2731	 10876	     
    0	  2731	 11040	     
    0	   179	  7780	extensionHost [1]
    0	   279	 12652	     "c:\Users\MANISH KUMAR\.vscode\extensions\redhat.java-1.29.0-win32-x64\jre\17.0.10-win32-x86_64\bin\java" --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Djava.import.generatesMetadataFilesAtProjectRoot=false -DDetectVMInstallationsJob.disabled=true -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -Xlog:disable "-javaagent:c:\Users\MANISH KUMAR\.vscode\extensions\redhat.java-1.29.0-win32-x64\lombok\lombok-1.18.32.jar" -XX:+HeapDumpOnOutOfMemoryError "-XX:HeapDumpPath=c:\Users\MANISH KUMAR\AppData\Roaming\Code\User\workspaceStorage\9b22463b9005e656f6f982dbd742262c\redhat.java" -Daether.dependencyCollector.impl=bf -jar "c:\Users\MANISH KUMAR\.vscode\extensions\redhat.java-1.29.0-win32-x64\server\plugins\org.eclipse.equinox.launcher_1.6.800.v20240304-1850.jar" -configuration "c:\Users\MANISH KUMAR\AppData\Roaming\Code\User\globalStorage\redhat.java\1.29.0\config_win" -data "c:\Users\MANISH KUMAR\AppData\Roaming\Code\User\workspaceStorage\9b22463b9005e656f6f982dbd742262c\redhat.java\jdt_ws" --stdio
    0	   132	 16276	     "C:\Users\MANISH KUMAR\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\MANISH KUMAR\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=7780
    0	    96	  8384	   window
    0	   343	  9332	   gpu-process
    0	    84	 10508	fileWatcher [1]
    0	    29	 12040	   crashpad-handler
    0	   102	 13876	window [2] (Issue Reporter)
    0	    92	 13980	ptyHost
    0	    63	  8304	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\MANISH KUMAR\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	    63	  8312	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\MANISH KUMAR\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     7	  8980	     conpty-agent
    0	     7	 12296	     conpty-agent
    0	    69	 14512	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\MANISH KUMAR\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     7	 15760	     conpty-agent
    0	    47	 15096	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: JSP Language Support - String - Visual Studio Code)
|    Folder (String): 10 files
|      File types: java(5) json(2) class(2)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: java(8);
```

</details>
<details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
java-run|cao|1.1.4
code-runner|for|0.12.2
debugpy|ms-|2024.5.11001012
isort|ms-|2023.10.1
python|ms-|2024.5.11021008
vscode-pylance|ms-|2024.4.1
jupyter|ms-|2024.3.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.13
java|red|1.30.2024041608
LiveServer|rit|5.7.9
vscode-jsp-lang|sam|0.1.7
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.26.0
vscode-java-test|vsc|0.41.0
vscode-maven|vsc|0.44.0
vscode-icons|vsc|12.7.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
8082a590:30971561
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
showvideot:31016892
chatpanelt:31018789
dsvsc021:30996838
jg8ic977:31013176

```

</details>

**Comment by pawlakmaly** [comment]
I've got same issue with running TS code using VSC configurations. Version 1.88.1

**Comment by roblourens** [comment]
Please file this on the Code Runner extension
