### ISSUE TITLE
Git: file opened from index needs a better tab title

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21058]
Steps to Reproduce:

1. have a staged new file
2. open it

=> it looks like any other file and needs a better label imho

![image](https://cloud.githubusercontent.com/assets/900690/23203490/06d10b44-f8e3-11e6-8b5c-3c1102f89a7e.png)

In stable:

![image](https://cloud.githubusercontent.com/assets/900690/23203498/0d900d04-f8e3-11e6-8b07-0c66ac70b272.png)

**Comment by joaomoreno** [comment]
I have no control over this through the API.

But IMO this is exactly the same as #19627. That URI should be distinguished in the tab control because it has a `git:` scheme.

**Comment by bpasero** [comment]
Yeah I think that is possible. But we should also think about API to provide label/description explicitly via options. We need to collect all these things and just provide options to `showTextDocument`.

**Comment by eamodio** [comment]
I would love to be able to control the tab title for a document in GitLens as well -- for the same thing - context about the opened file/virtual file.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
