### ISSUE TITLE
Clone repository from GitHub clones wrong repo

### ISSUE THREAD

**Issue by cbrnr** [microsoft/vscode#210554]
Type: <b>Bug</b>

1. In the Explorer pane, click on "Clone Repository"
2. Select "Clone from GitHub" by pressing Enter
3. Enter a repository name, I tried with "cbrnr/PyTables"
4. Confirm with "Enter"
5. A dialog appears with the target folder; it shows a random repository in its title (not the previously selected one)
6. Hitting Enter clones the wrong repository

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:34:12.840Z)
OS version: Linux x64 6.8.6-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|15.38GB (9.24GB free)|
|Process Argv|--unity-launch --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
ruff|cha|2024.16.0
gitlens|eam|14.9.0
copilot|Git|1.180.0
copilot-chat|Git|0.14.1
vscode-pull-request-github|Git|0.86.1
language-julia|jul|1.76.2
wordcounter|kir|2.4.4
debugpy|ms-|2024.5.11001012
python|ms-|2024.5.11021008
vscode-pylance|ms-|2024.4.1
quarto|qua|1.111.0
even-better-toml|tam|0.19.2

</details>

**Comment by cbrnr** [comment]
Here's a screencast which illustrates the issue:

[vsc_clone_repo.webm](https://github.com/microsoft/vscode/assets/4377312/e4f52b1d-9fc7-4b27-8eb4-a92f16018381)

**Comment by gjsjohnmurray** [comment]
I can repro on 1.88.1 but not on the current Insiders

**Comment by nerryc** [comment]
Upvoted, driving me insane

**Comment by lszomoru** [comment]
@cbrnr, @nerryc, are you able to reproduce with the latest VS Code Insiders release? Thanks!

**Comment by cbrnr** [comment]
I can confirm that this issue does _not_ occur with VS Code Insiders, so somewhere along the way it has been fixed 🎉!

**Comment by nerryc** [comment]
Thank you!
