### ISSUE TITLE
Custom Hover in REPL freezes the UI

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#210518]
Does this issue occur when all extensions are disabled?: Yes/No

I ran into this pretty often while debugging extensions 

<img width="1043" alt="image" src="https://github.com/microsoft/vscode/assets/876920/1ce2f72e-f70c-497f-90eb-23fa76ee90f9">

and digging into the call stack, it's coming from custom hover handler for REPL

<img width="1068" alt="image" src="https://github.com/microsoft/vscode/assets/876920/0d6b122b-bccd-4469-bb40-b18799933e86">

**Comment by Tyriar** [comment]
Guessing this is a consequence of using the more convenient but less performance-conscious`setupUpdatableHover`?

**Comment by rebornix** [comment]
adding `important` as currently VS Code is barely usable while debugging Copilot.

**Comment by Tyriar** [comment]
+ @aiday-mar was this change part of the hover enriching work you did? I think when using hovers extensively like this you need to move off `setupUpdatableHover` and manage things yourself via `IHoverService.showHover`

**Comment by aiday-mar** [comment]
Hi @Tyriar probably not, the hover enriching work is not merged yet

**Comment by benibenj** [comment]
It seems like this change might be the culprit: #209058 @connor4312 

[const { store, commands, commandService } = options.hover instanceof DisposableStore ? { store: options.hover, commands: [], commandService: undefined } : options.hover;](https://github.com/microsoft/vscode/blob/a0de9e56ad6a0a3c7c294127997a6ef0f1a297e4/src/vs/workbench/contrib/debug/browser/baseDebugView.ts#L111-L129)

**Comment by Tyriar** [comment]
Hover does seem like the majority but `linkify` is also awfully expensive there 🤔

**Comment by connor4312** [comment]
I assume this happens when a breakpoint gets hit, do you recall where you placed that breakpoint when you got that profile @rebornix?

**Comment by connor4312** [comment]
Do you know in general what you were doing so I can try to reproduce? I don't think I've hit this before in my debugging.

The only slowness I get in the copilot repo is when dealing with source map renames making the initial 'variables' view slow to load (TBD whether there's much I can to do speed that up) but that's not renderer-blocking.

**Comment by rebornix** [comment]
Coming back a bit late. I don't really have a good reproduce.

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-js-debug/pull/2000
