### ISSUE TITLE
sticky scroll not working for edge case

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#210503]
feel free to close if it's not worth fixing this

https://github.com/microsoft/vscode/assets/29464607/6d86751a-6463-4ca2-8290-b8035e0a5976

**Comment by Tyriar** [comment]
Any more details or trace logs on repro?

**Comment by meganrogge** [comment]
I cannot repro this (type fast enough) atm, but I think the issue was I typed `yarn && yarn watch` before the next prompt start.

See the `yarn && yarn watch` printed before the prompt in the gif

**Comment by Tyriar** [comment]
Can't repro ☹️
