### ISSUE TITLE
vscode setting packageManager in package.json unconditionally

### ISSUE THREAD

**Issue by frankli0324** [microsoft/vscode#210556]
Type: <b>Bug</b>

open a package.json file and wait, packageManager appeared as "npm@10.1.0+sha256.7cb31c0a881964a22577fd84e5a9a5b11e6f49ef8aa0893036b0b68015056252". "npm.packageManager" setting doesn't provide a "none" option.

this is happening with all extensions disabled.

VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin arm64 23.1.0
Modes: Unsupported

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
gee8j676:31009558
chatpanelc:31018788
dsvsc021:30996838
f3je6385:31013174

```

</details>

**Comment by frankli0324** [comment]
I know it may have been a feature, yet it doesn't meet expectations. what's more, the behavior modifies and ***saves*** a ***project file*** without any prompt and attempts to overwrite ***repeatedly***, I believe that categorizes this as a bug.

**Comment by meganrogge** [comment]
sounds like something that's coming from an extension. you can set your package manager with this setting

`npm.packageManager`

**Comment by frankli0324** [comment]
> sounds like something that's coming from an extension.

as I said, **all extensions were disabled**

> you can set your package manager with this setting

as I said, "npm.packageManager" setting doesn't provide a "none" option.

**Comment by meganrogge** [comment]
How is that a problem for you?

**Comment by meganrogge** [comment]
I closed because I do not plan to fix this.

**Comment by frankli0324** [comment]
good for you then

**Comment by frankli0324** [comment]
hi @bhavyaus are you able to re-assign this?

**Comment by frankli0324** [comment]
I take back the "trust issues" narrative, however this behavior is still surprising. take a look at the PR please

**Comment by frankli0324** [comment]
I should have attached a screenshot and describe the steps I tried to pin point the issue

![20240418065545_rec_](https://github.com/microsoft/vscode/assets/20221896/f17b8cd9-c2eb-4e51-8b76-e7cd20049cab)

I encountered this issue in an empty folder containing a single package.json, an old project, and a newly created project with `yarn create`

I apologize for my moody expression

**Comment by aeschli** [comment]
I could not reproduce that `npm view --json` updates the `packageManager` property
I tried from the command line with node 20.12.2 / npm 10.5.0
- `corepack use yarn`
- `npm view --json`
@frankli0324 Do you have the steps to reproduce this from the command line?

**Comment by aeschli** [comment]
Verified the fix in code

**Comment by frankli0324** [comment]
make sure the npm you're executing is pointed to the corepack wrapped binary, which, in brew package "corepack", is installed to /opt/node/bin/npm. you can make sure by:

```
➜  head $(which npm)
#!/usr/bin/env node
process.env.COREPACK_ENABLE_DOWNLOAD_PROMPT??='1'
require('./lib/corepack.cjs').runMain(['npm', ...process.argv.slice(2)]);%            
```

**Comment by frankli0324** [comment]
the minimum path from a clean install would be:

```bash
brew install corepack
corepack enable npm
npm view --json
```

**Comment by aeschli** [comment]
corepack is part of node 20, so I used it directly, not using brew (which I don't have on my system)
What's your verion of node?

I kind of think having `npm view --json` making a modification is a bug in npm.
Not seeing that myself could mean it has been fixed.

**Comment by frankli0324** [comment]
```
➜  ~ node -v
v21.7.3
```

have you `enable`d the npm pm globally using corepack?

**Comment by aeschli** [comment]
Ah, the aliases. They were probably not used when I tested it.
