### ISSUE TITLE
Unable to see option to 'Sign in with Github'

### ISSUE THREAD

**Issue by IamChhteri** [microsoft/vscode#210532]
Type: <b>Bug</b>

Hi Team,
I'm unable to see the option to sign in with 'Github'. All the time it's redirecting me to Microsoft account. Attaching screenshot for reference.

![Screenshot 2024-04-16 at 11 25 23 PM](https://github.com/microsoft/vscode/assets/66677742/9d6a3396-7377-4058-86ad-ae36e6e6b2de)

VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 6, 5|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 92d998e1-ad11-44c5-b53b-1c2919a5307a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|14.9.0
debugpy|ms-|2024.4.0
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
showvideoc:31016891
chatpanelt:31018789
dsvsc021:30996838
724cj586:31013169

```

</details>

**Comment by TylerLeonhardt** [comment]
What are you clicking on that launches this quick pick?

**Comment by IamChhteri** [comment]
This orange highlighted  :

![Screenshot 2024-04-18 at 6 48 01 PM](https://github.com/microsoft/vscode/assets/66677742/a6670b4c-63b7-4eaf-951f-79f345db2054)


When I searched I found : "GitHub Authentication" extension is missing my vs-code

**Comment by TylerLeonhardt** [comment]
@IamChhteri why does your gear have a badge on it:
![image](https://github.com/microsoft/vscode/assets/2644648/d7f1e88e-bce2-4f2a-ae02-9a490b6d83c7)

What action does it want you to take?

Also, when search for `@builtin` in the extension pane, do you see GitHub Authentication there?

**Comment by IamChhteri** [comment]
Hi @TylerLeonhardt, 
Thank you now I'm getting option to login with Github. when used `@builtin github` i got the option and it was disable.
Previously i was directly searching 'GitHub Authentication' and didn't found any result. Attaching screenshot for reference.
 
![Screenshot 2024-04-19 at 12 53 19 AM](https://github.com/microsoft/vscode/assets/66677742/0375cce3-b0d0-47a1-8b97-039acba02984)

You can ignore gear badge. Once again thank you.

**Comment by TylerLeonhardt** [comment]
It's odd to me that this extension was disabled. It really should never be... if you have any insight as to why that was disabled, that would be useful.

Anyway, glad you're unblocked.
