### ISSUE TITLE
Splitted Terminal border color and thickness customization

### ISSUE THREAD

**Issue by MetaMmodern** [microsoft/vscode#210579]
Hi! I'm using splitted terminal constantly, since it's very nice and convinient. However, when using it on Windows I've noticed one thing that makes me want to use Windows Terminal app more that the vscode terminal: it's the border, separating two terminals.

With my default theme here's how it looks like:
![image](https://github.com/microsoft/vscode/assets/42899786/649ccca4-b7c6-402c-8aa8-dd5302795048)

You can see that although it's quite obvious where one terminal window ends and where the next one begins, but if you're doing a quick lookup it's a but fuzzy, it's not quite solid.

VSCode allows to customize border color, but honestly it doesn't look that nice because it forced you to customize all panel borders. Also I noticed there's an `editorGroup.border`, which let's customize the editor border. Here's how it looks like with both properties engaged:

![image](https://github.com/microsoft/vscode/assets/42899786/b4217dc4-7fb0-44be-85e6-f1f9ea1cf07f)

You can see it added green borders where I didn't want to have them.

And I've added the red editor border just to demonstrate what I wanted to have instead. It would be nice to have something like

```
terminalGroup.border
```

And just for comparison here's how it looks like in Windows Terminal
![image](https://github.com/microsoft/vscode/assets/42899786/d185e5e7-33a6-4c54-a444-aceef98d615d)

And another thing related to this is the border thickness. You can see that Windows Terminal has around 2-3px of borderSize. It makes it look much more solid. You can see how weak the thin vscode line looks like. I'd like to have an ability to declare in settings what the border size is. Even if you hardcode it to some kind of mapping like "thin"/"thick", that would be better already that what we currently have. 

Thanks in advance!

**Comment by ArturoDent** [comment]
"terminal.border": "#ff0000",

is slightly better - there is no border top colored.

**Comment by MetaMmodern** [comment]
@ArturoDent yep, definetely. Thanks, I'll cope with that one for now:)
