### ISSUE TITLE
VScode cannot start after update getting error 'TypeError require(...).load is not a function'

### ISSUE THREAD

**Issue by MinikGL** [microsoft/vscode#210535]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.1
- OS Version: Windows 11 Enterprise Version 22H2 Build 22621.3296

Steps to Reproduce:

1. Update vscode using the built-in update popup dialog.
2. Tro to execute using with `code --verbose`.
![image_2024-04-17_084948045](https://github.com/microsoft/vscode/assets/142001824/8c976346-2b88-4a99-992c-b932345f6369)

**Comment by MinikGL** [comment]
When downloading vscode from the official page and installing it, it will work again.

**Comment by rzhao271** [comment]
Closing the issue because it seems like a transient issue, or an issue specific to that older version. Let us know if you're still seeing it on VS Code 1.96 or later.
