### ISSUE TITLE
Autosave blocks / hangs extension & file system processes

### ISSUE THREAD

**Issue by joshua-auchincloss** [microsoft/vscode#210599]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.1
- OS Version: MacOS Ventura 13.5.2

Extension Bisect outputs:
```
Extension bisect is done but no extension has been identified. This might be a problem with Code.
```

Steps to Reproduce:

1. Enable autosave.
2. Edit files for a few minutes.
3. Eventually (usually < 15m), you'll see `Saving 'somefile.{go,py}: getting code actions from...`.

Notification from 3 will persist indefinitely, and prevent future autosaving from all changes onwards. Restarting (vscode and/or device) has no effect. Cancelling the save from 3 will then appear to be resolved, however:

1. Attempt to close window which was effected.
2. Code will prompt "Do you want to save the changes you made to ...".
3a. Clicking save will result in indefinitely hanging saving on exit screen.
3b. Clicking don't save will obviously lose the data (not acceptable)

Language / source type appears to be irrelevant (occurs on python and go source code alike). Validated device resources are OK (12+GB free mem). Permissions do not have any effect (eg. parent folder containing project trusted vs project folder).

**Comment by justschen** [comment]
looks like it's hanging on the editor code actions on save (the save is happening and editor code actions are being simultaneously triggered by the save).

@joshua-auchincloss can you see if you have any `editor.codeActionsOnSave` settings enabled?

**Comment by joshua-auchincloss** [comment]
> looks like it's hanging on the editor code actions on save (the save is happening and editor code actions are being simultaneously triggered by the save).
> 
> 
> 
> @joshua-auchincloss can you see if you have any `editor.codeActionsOnSave` settings enabled?

Hey @justschen - apologies for the delay! No `editor.codeActuonsOnSave` settings enabled 😕

**Comment by joshua-auchincloss** [comment]
Hey @justschen, seems good! A bit of lag but nothing out of the norm 👌 Good to close
