### ISSUE TITLE
Max editor count should be configurable

### ISSUE THREAD

**Issue by tstringer** [Microsoft/vscode#2105]
The maximum number of editors currently is **three**.  There doesn't appear to be a way to change this in user settings.

It would be helpful and flexible if there was a configuration option in user settings to override this default max value (i.e. some developers might be able to handle four or five editors and still feel "organized").

I like the max editor cap, but I believe the count of max editors should be configurable.

**Comment by Tyriar** [comment]
Related https://github.com/Microsoft/vscode/issues/1749 (horizontal editor splitting)

**Comment by bmperdue** [comment]
+1

**Comment by xoron** [comment]
+1
