### ISSUE TITLE
wrong font for terminal completions

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#210597]
testing https://github.com/microsoft/vscode/issues/210394#issue-2243874564

I see this on multiple machines, and when using an empty temporary profile where this is the only setting in settings.json

![image](https://github.com/microsoft/vscode/assets/2019016/09af7471-a2e9-4a92-a5c3-edd863f963be)

**Comment by Tyriar** [comment]
Can't repro by just commenting out settings, maybe my installed fonts being different is the issue.

**Comment by JustinGrote** [comment]
Happened to me on Windows.

![image](https://github.com/microsoft/vscode/assets/15258962/f349db4d-6648-4934-9e9e-b61fffbe03db)

**Comment by starball5** [comment]
I'm seeing questions on SO about other font issues and I'm not sure if they're related to this or a separate issue.

- https://stackoverflow.com/q/78597483/11107541 weird accents on letters in inline code in markdown https://i.sstatic.net/L7fBgQdr.png https://i.sstatic.net/MrZUaApB.png
- https://stackoverflow.com/q/78577349/11107541 similar weird accents on letters in suggest widget https://i.sstatic.net/AJTwN7v8.png

Should I tell those people to raise a new issue ticket?

**Comment by poa00** [comment]
+1 
![image](https://github.com/microsoft/vscode/assets/134162878/2df0b2f1-e5e2-4024-a968-709e811756d9)

**Comment by sbatten** [comment]
Same for me when testing https://github.com/microsoft/vscode/issues/223130

**Comment by Tyriar** [comment]
Well that's obvious:

https://github.com/microsoft/vscode/blob/12f9169c935bd3fd2730777130330c3bb19e0005/src/vs/workbench/services/suggest/browser/simpleSuggestWidgetRenderer.ts#L83-L94
