### ISSUE TITLE
How can i debugg polymer components ?

### ISSUE THREAD

**Issue by imacnu** [Microsoft/vscode#21054]
- VSCode Version: 1.9.1
- OS Version: OSX 10.12.3

Steps to Reproduce:

1. Run a Polymer Js component over local sever
2. Start chrome debugger

Debugger start but i can´t add any breakpoint on js files ?

**Comment by roblourens** [comment]
Please file this on the chrome debug repo, but first check out its readme with useful debugging tips.

https://github.com/microsoft/vscode-chrome-debug/
