### ISSUE TITLE
Perf: regression in `workbench.contrib.explorerViewletViews`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#210529]
There is a clear upwards trend of time in the overall workbench contributions that block startup around April 9th - April 10th:

![image](https://github.com/microsoft/vscode/assets/900690/05696f00-f2cb-4fcd-af53-d31cef7064df)

Running stable and insiders shows a clear increase in time we spend in `workbench.contrib.explorerViewletViews`

**Stable**
```
| code/willCreateWorkbenchContribution/1/workbench.contrib.explorerViewletViews                       | 1713330091958 | 0     | 1     |
| code/didCreateWorkbenchContribution/1/workbench.contrib.explorerViewletViews                        | 1713330091960 | 2     | 3     |
```

**Insiders**
```
| code/willCreateWorkbenchContribution/1/workbench.contrib.explorerViewletViews                       | 1713330119050 | 0     | 2     |
| code/didCreateWorkbenchContribution/1/workbench.contrib.explorerViewletViews                        | 1713330119057 | 7     | 9     |
```

I am assigning some folks in this area that could maybe check if there are changes in their areas that could contribute:
* tree / lists (@benibenj)
* views (@sandy081)
* explorer (@lramos15)

//cc @jrieken

**Comment by benibenj** [comment]
The timeline does not match with any hover changes, but still want to reference #210518 here.

**Comment by benibenj** [comment]
@bpasero Thanks for bisecting. You are probably right, the first call to the keybinding service seems to be expensive. I'm pretty sure my change causes this to be called for the first time earlier as it used to. I changed it such that the keybinding service is only used when the user runs this action.
