### ISSUE TITLE
Test: TS extension using our file watchers

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#210687]
Refs #208872

- [x] Windows @eleanorjboyd 
- [x] macOS @paulacamargo25
- [x] Linux @alexr00 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23210687%0A%0A&assignees=bpasero)

---

So far, the TS extension implemented file watching on their level, leveraging node.js `fs.watch` and `fs.watchFile`. With a new setting, this changes to utilise our `vscode.fs.createFileSystemWatcher` API that is more performant and matches our built-in file watcher.

TS makes extensive use of file watching for the language services to know what kind of types exist for a project. Watch out for error squiggles and problems reported even though a type you use exists on disk.

**Steps:**
- make sure that `typescript.tsserver.experimental.useVsCodeWatcher` is configured to `true`
- use typescript projects as test bed, for example `vscode` repo itself but also extensions or samples you work on
- as soon as you open a TS file, the extension will activate and file watchers will install
- if you configure log level to `trace`, a new output channel "File Watcher" gives you verbose information and stats
- do exploratory testing that the TS language services are proper in situation such as:
  - `npm install` of a new module with types that you reference from your code
  - switching back and forth between branches with differing state of TS types
  - defining a new type in a new file and then using it in another file
  - deleting a file with types that are used
- open an empty workspace (no folder) and open a TS file (e.g. from VSCode repo) and verify that changes are also picked up in that case for types you reference
- keep an eye on the window and main logs that the file watcher does not crash or restart

**Comment by karthiknadig** [comment]
I have the log level set to trace:
![image](https://github.com/microsoft/vscode/assets/3840081/6dcdce99-483b-46e9-a6ae-ecf4f1ca6795)

![image](https://github.com/microsoft/vscode/assets/3840081/0a182f9a-36f4-4eab-ac39-bef42390526d)


I don't see a "File Watcher" channel, I tried reloading as well.
![image](https://github.com/microsoft/vscode/assets/3840081/2a8834d2-ceaa-4e87-9fe3-2e84b2ec1146)

**Comment by bpasero** [comment]
@karthiknadig you need to set the overall log level to trace, not just for TS 👍
