### ISSUE TITLE
Theme service stops listening to settings change?

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#21067]
Testing #20998

1. Pick theme A
2. Create a syntax error in settings.json
3. Change to theme B. Get an error message saying to fix the syntax error. The theme is still applied.
4. Fix syntax error, effectively trying to set theme A again

Theme A isn't set back. Further settings change don't trigger the change back to theme A.

**Comment by aeschli** [comment]
I figured that I didn't want to block the user from changing a theme while the settings is in an invalid state. I realize that it takes some steps to fix the settings and to reapply the theme.
