### ISSUE TITLE
FIX YOUR MAUI INSTALLATION PLEASE ITS BEEN LIKE 3 YEARS. 

### ISSUE THREAD

**Issue by Vampeyer** [microsoft/vscode#210625]
https://github.com/dotnet/maui/issues/12080

I AM ON .NET 9.0 AND STILL CANT COMPILE A SIMPLE HELLO WORLD IN C#  , what kind of trash are you guys selling up there   ?

why cant we develop .NET apps on C# ? 
----
https://github.com/dotnet/maui/issues/13276

--- Pay me to handsomly fix it , or we (  the company  ) will have issues.  - You got 1 week to respond fully.    
- You guys have a lot too lose , I don't.
----- And I don't tolerate those sloppy games. ----------  

- Good day.

**Comment by Vampeyer** [comment]
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Numerics.Vectors.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[4884] MyFirstMauiApp.exe' has exited with code 2147942405 (0x80070005).

**Comment by Vampeyer** [comment]
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Numerics.Vectors.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[4884] MyFirstMauiApp.exe' has exited with code 2147942405 (0x80070005).

**Comment by gjsjohnmurray** [comment]
What does this have to do with VS Code?

**Comment by Vampeyer** [comment]
I must confess , I was looking for the Visual Studio Repository last night , and I frantically posted it in the first forum for VS Code I could find.     - To give you an accurate response  what does this have to do with VS Code ? 
- - - Well , Considering I cannot even compile a simple C# MAUI application on visual studio , 

I see this as an opportunity for VS Code to excel , where others have failed.   Simple as that.   

I see there is less and less support for VS code , in light of the new apple M2 chips , - That is a mistake.  

What does this have to do with VS Code  ?    - - -Well , were not compiling any C#  / .NET MAUI apps on VS Code now are we?   

The only real question I have with all of these failures in front of me is , 
Why not ? and what steps need to be taken , to ensure a fully owned and supported IDE for developers ?      
 
With the recent failures of Visual Studio ,    
( That have now continued for 3 years , past 3 updates , on .NET9.0 )    

 Will , (  Support for )  , C# Compilation of .NET MAUI Apps ,  be considered  for VS Code ???   
Thank you sir. 

At the rate things are going , im tempted to ask , WHEN , will .net MAUI app support be available for it?  
Because there seem to be no viable alternatives  with solid support for the language. 


Microsoft handles the situation like a rabid dog.

**Comment by rzhao271** [comment]
Have you checked the docs? https://code.visualstudio.com/docs/csharp/get-started
