### ISSUE TITLE
Setting `TreeView.badge` to `undefined` no longer removes the badge

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#210640]
Type: <b>Bug</b>

I think this is a regression caused by #205589.

I will provide a repro and a PR.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

**Comment by gjsjohnmurray** [comment]
Repro:

1. Clone https://github.com/gjsjohnmurray/vscode-extension-samples.git and checkout the show-210640 branch
2. Open the tree-view-sample folder in VS Code, then build and run the extension as per README.md
3. From Extension Host's Command Palette run `Test View: Change Title` which the extension contributes.
4. When prompted, enter a title, e.g. `Hello`
5. Observe that a badge gets added to the Explorer icon in Activity Bar, and the TEST VIEW header in that view container gets a new title.
6. Rerun the command, and this time leave the field empty.
7. Observe that the view title resets to TEST VIEW ✅ but the badge is not cleared :bug:

**Comment by aeschli** [comment]
I don't see a badge being added to the Explorer view on `Test View: Change Title`

**Comment by gjsjohnmurray** [comment]
@aeschli are you certain you're on the `show-210640` branch?

**Comment by aeschli** [comment]
Oh, sorry, you are right.
Now all works.
