### ISSUE TITLE
Remove a cursor by pressing ALT+CLICK again.

### ISSUE THREAD

**Issue by philipgiuliani** [Microsoft/vscode#2106]
With ALT+CLICK i can create multiple cursors. Is there a way to remove one if i set one wrong? In atom i can just click again on it and it will be removed.

**Comment by csholmq** [comment]
+1

**Comment by alexandrudima** [comment]
In the meantime, you can workaround by using `Ctrl+U` that undoes the latest cursor operation you did.

**Comment by adrianocr** [comment]
PLEASE!
