### ISSUE TITLE
Github Copilot is disabled but still making suggestions

### ISSUE THREAD

**Issue by okaybenji** [microsoft/vscode#210666]
Type: <b>Bug</b>

I have the Github Copilot extension disabled, but it is still making suggestions. It keeps making suggestions when I am trying to add tabs to my code, so rather than adding a tab, it adds the suggestion I don't want. There's no easy way for me to add a tab. If I delete the inserted suggestion, the suggestion just comes back. I wouldn't mind so much if I could change the keybind for accepting a suggestion to something that isn't already being used, but I don't know how to do that. But also, if Copilot is disabled, it shouldn't be working!

VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id aeacc878-4058-45fb-af1e-4f1ab1085a0b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.9.0
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.4.4
vscode-html-css|ecm|2.0.9
prettier-vscode|esb|10.4.0
copilot-chat|Git|0.14.1
vscode-graphql|Gra|0.9.3
vscode-graphql-syntax|Gra|1.3.5
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
node-module-intellisense|lei|1.5.0
vscode-docker|ms-|1.29.0
csdevkit|ms-|1.4.29
csharp|ms-|2.23.15
vscode-dotnet-runtime|ms-|2.0.3
vscodeintellicode-csharp|ms-|2.0.25
remote-containers|ms-|0.354.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.0
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.13
mono-debug|ms-|0.16.3
remote-explorer|ms-|0.4.3
vsliveshare|ms-|1.0.5918
vetur|oct|0.37.3
prisma|Pri|5.12.1
vscode-unitymeta|PTD|0.0.7
vscode-commons|red|0.0.6
vscode-yaml|red|1.14.0
cmake|twx|0.0.17
unity-debug|Uni|3.0.2
vstuc|vis|1.0.1
volar|Vue|2.0.8
pretty-ts-errors|Yoa|0.5.4
propertylist|zho|0.0.2
material-theme|zhu|3.17.0
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30993540
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572
01bff139:31013167

```

</details>

**Comment by jrieken** [comment]
Can you please share your settings? It might be that you getting inline completions from another source, like IntelliSense or snippets

**Comment by okaybenji** [comment]
If you can please let me know which settings you want to see I'll be happy to share them. I'm including a screenshot showing the extension is disabled and a screenshot showing what the suggestions look like, which I think should clearly show that they are not IntelliSense nor Snippets.

<img width="593" alt="Screenshot 2024-04-18 at 12 15 12 PM" src="https://github.com/microsoft/vscode/assets/5256525/1b150c28-98dc-4a1c-b23e-dcab3fca77c2">


<img width="550" alt="Screenshot 2024-04-18 at 12 13 23 PM" src="https://github.com/microsoft/vscode/assets/5256525/c9aa2f5c-8ba2-49e5-a121-a177e541b577">

**Comment by Hackathon757** [comment]
I have also been having this problem for a while and found the solution. If you open settings in VS, there is an option named Inline Suggest under Text Editor: Suggestions. You may want to look at the surrounding options as well, but that's how I was able to fix it.

**Comment by okaybenji** [comment]
> I have also been having this problem for a while and found the solution. If you open settings in VS, there is an option named Inline Suggest under Text Editor: Suggestions. You may want to look at the surrounding options as well, but that's how I was able to fix it.

I appreciate the reply, but I think this must be a different issue. I tested changing the Quick Suggestions Delay, for instance, from 10 to 2000ms. Intellisense became delayed by 2 seconds, but the suggestions like `if (gameObject != null) {}` above still appeared instantly.

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by IndySeh** [comment]
@jrieken Thanks mate! worked for! `IntelliCode Completions Extention` was causing issue!

**Comment by okaybenji** [comment]
> It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following...

Thanks @jrieken, Extension Bisect is brilliant! The result: `Extension Bisect is done and has identified ms-dotnettools.vscodeintellicode-csharp as the extension causing the problem.`
