### ISSUE TITLE
Getting 'Invalid gap' when asking about multiple lines

### ISSUE THREAD

**Issue by orjtor** [microsoft/vscode#210699]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.88.1
- OS Version: Windows 10

Steps to Reproduce:

1. Select two lines of PHP code
2. Ctrl + I
3. Ask "is it safe to make a one-liner of these lines?"
4. Copilot replies "Invalid gap'

![image](https://github.com/microsoft/vscode/assets/28388330/4196c144-d310-484d-92ff-3cba427f82ed)

The GitHub Copilot chat works, but code generation in the PHP file using the command Ctrl + I seems not to work even if the Copilot status seems to be okay and I have restarted the VS Code.

When making a one-liner of the code and ask if that is safe I get a reply with some thoughts that seems resonable, indicating the Copilot is active.

**Comment by justschen** [comment]
cc. @jrieken maybe?

**Comment by alexdima** [comment]
This has been fixed in the meantime.
