### ISSUE TITLE
avoid being closed by Ctrl-W

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#21063]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|tslint|eg2|0.8.1|
|vs-code-xml-format|fabianlauer|0.1.4|
|code-beautifier|michelemelluso|1.6.2|
|vscode-icons|robertohuertasm|7.2.0|
|vim|vscodevim|0.5.3|

---

Steps to Reproduce:

1. Keep press down and up Ctrl + W 
2. then vscode will be closed

Expected: 

close all windows expect vscode itself.

**Comment by CoenraadS** [comment]
I think this should go behind a setting.

In browsers, holding ctrl-w on the last tab will close the browser, and VSCode should probably maintain consistency with that. But I have also accidentally closed VSCode using ctrl-w when I just wanted to close some tabs.

**Comment by bpasero** [comment]
This can be done via keybindings, see: https://github.com/Microsoft/vscode/issues/1764#issuecomment-230674122
