### ISSUE TITLE
"No definition found" widget comes and goes very quickly

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#21064]
Testing #21032

![kapture 2017-02-22 at 10 15 49](https://cloud.githubusercontent.com/assets/22350/23204700/ea8d4c04-f8e7-11e6-8a17-198c83fdf227.gif)

I don't know why it closes, but maybe give it a minimum time it stays open.

**Comment by jrieken** [comment]
Yeah, you too far away for my logic...
