### ISSUE TITLE
Better column indicator icon

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#21062]
Currently we use the same yellow arrow for showing the current line indicator in the glyph margin and inline in the editor to indicate column. As shown in the following gif

![column](https://cloud.githubusercontent.com/assets/1926584/23204039/4001d784-f8e5-11e6-868c-b170dd40ccc4.gif)

After discussing with @weinand we believe a more appropraite icon could be used as a replacement for the current [yellow arrow](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/media/current-arrow.svg#L1) 
We believe a more fitting one would be a thin but high yellow styliezd triangle pointing to the right. This way it would not take so much space in the editor and would still provide the desired functionality. So basically to make the current icon thinner and higher and maybe cut out the left end.

@chryw is it possible for you to give us a hand with this? If not then @chrisdias what is our process when there is no appropriate icon in https://vsicons.azurewebsites.net/

**Comment by chryw** [comment]
@isidorn Visual Studio uses this icon for pointer. Do you want me to update the VS Code pointer icon to match it?
![image](https://cloud.githubusercontent.com/assets/7075677/23281203/3ce1ef7a-f9d1-11e6-966d-d4e7b85ef3a6.png)

**Comment by isidorn** [comment]
@chryw yes we are aware of that icon - @weinand and me have been searching through your nice icons site but we are not happy with it. If possible we would like to have a new icon that fits my description from the comment above.
@chrisdias what is the process here :)

**Comment by chrisdias** [comment]
@isidorn is there a reason the yellow arrow above (same as from VS) doesn't work here? Is there a compelling reason for being different from VS?

**Comment by weinand** [comment]
@chrisdias the icon has too much detail (and a black border) which doesn't match the VS Code style.

**Comment by chryw** [comment]
@isidorn btw if you have access to this link then you can log icon requests [http://aka.ms/dduxicon](http://aka.ms/dduxicon). 

@weinand I can make a VS Code style (no border) yellow arrow.

**Comment by chryw** [comment]
![image](https://cloud.githubusercontent.com/assets/7075677/23533304/cf439320-ff65-11e6-9c3c-6f058ebe2e61.png)
[CurrentInstructionPointer_16x_vscode_inverse.zip](https://github.com/Microsoft/vscode/files/815458/CurrentInstructionPointer_16x_vscode_inverse.zip)

@isidorn @weinand this is the same arrow as VS, just without the border. could you test it with the red dot overlay scenario and see if it works?

**Comment by chrisdias** [comment]
@chryw the other part of this request is to have something that also works well when stepping across inline statements. See in this picture where the yellow instruction pointer is inline, next to the last console.log() statement:

![image](https://cloud.githubusercontent.com/assets/1487073/23533575/70c4b5b6-ff67-11e6-8812-2fa8fc949332.png)

i played with more of a triangle shape which isn't quite right either (looks like a play button):

![image](https://cloud.githubusercontent.com/assets/1487073/23533617/c3635516-ff67-11e6-85fb-39a75789653d.png)

Is there a middle ground?

**Comment by chryw** [comment]
[939597_github_VSCodeDebugPointerArrow.zip](https://github.com/Microsoft/vscode/files/817528/939597_github_VSCodeDebugPointerArrow.zip)
![image](https://cloud.githubusercontent.com/assets/7075677/23562819/e8a5d3a8-fff8-11e6-9e2b-ec96f775e38c.png)

@chrisdias how about this?

**Comment by chrisdias** [comment]
feels heavy to me... @isidorn @weinand ?

**Comment by isidorn** [comment]
Too heavy imho. Can we make it thinner and taller as I originally described

**Comment by weinand** [comment]
Yes, more narrow but taller.

**Comment by chryw** [comment]
looks like it doesn't need to be bigger than the red dot? What do you think of this -
[939597_github_VSCodeDebugPointerArrow_update.zip](https://github.com/Microsoft/vscode/files/817933/939597_github_VSCodeDebugPointerArrow_update.zip)

![image](https://cloud.githubusercontent.com/assets/7075677/23569003/203fa83e-0012-11e7-866a-8babec7dbe1d.png)

**Comment by isidorn** [comment]
@chryw looks best so far. That could work for me - not very distracting inline and can not be confuzed with the play icon. Let's wait for @weinand opinion

**Comment by weinand** [comment]
Yes, looks good. Only question remains: how does it look if a breakpoint is superimposed.
Maybe it needs to be a bit taller and wider for that.

**Comment by isidorn** [comment]
Yes we would also need the design for a counterpart of
I think the size should not be increased for this case, but the red dot inside could be decreases

![screen shot 2017-03-06 at 10 43 50](https://cloud.githubusercontent.com/assets/1926584/23604644/db04acca-0259-11e7-9a80-1783c87122f9.png)

**Comment by chryw** [comment]
I'm not sure if this is stacking the two icons without resizing like below. If we reduce the red dot it's harder to see.
![image](https://cloud.githubusercontent.com/assets/7075677/23623813/446652ce-0258-11e7-9924-c8283f9cfcda.png)

If we can have one separate icon (one file) for this composite state, then I think the red dot needs to stay big when it's by itself.
![image](https://cloud.githubusercontent.com/assets/7075677/23623958/dbd1f85c-0258-11e7-8051-3625405bd81c.png)

**Comment by isidorn** [comment]
@chryw Yes, my original intention was that the red dot stays big when by it's own.
The second picture works for me. Could you please provide me the svgs you use in that picture?

**Comment by chryw** [comment]
[939597_github_VSCodeDebugPointerArrow_update2.zip](https://github.com/Microsoft/vscode/files/832440/939597_github_VSCodeDebugPointerArrow_update2.zip)
@isidorn

**Comment by isidorn** [comment]
@chryw thank you very much, @weinand and me really like the new icon. We just have the following feedback:
* The icon should be 1px larger to the left
* The icon should be exactly the same height as the [previous icon](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/media/current-arrow.svg)
* The icon should not shrink when a breakpoint is added (at the moment the DebugLinePointerBreakpoint is not the same size as the DebugLinePointer, they should be so when the user click to add a breakpoint he does not see the shrinking)

**Comment by chryw** [comment]
![image](https://cloud.githubusercontent.com/assets/7075677/23808414/9e98c2b2-057e-11e7-9bb0-596e03f03dea.png)
![image](https://cloud.githubusercontent.com/assets/7075677/23808441/ba88ba68-057e-11e7-84ff-4dea06bab855.png)
[939597_github_VSCodeDebugPointerArrow_update3.zip](https://github.com/Microsoft/vscode/files/834834/939597_github_VSCodeDebugPointerArrow_update3.zip)
Please try the attached icons

**Comment by isidorn** [comment]
Thanks @chryw these work great! I have pushed to insiders, so now we wait for feedback.
