### ISSUE TITLE
Bad sorting in quick open

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#21068]
![image](https://cloud.githubusercontent.com/assets/22350/23205362/e5552552-f8e9-11e6-8363-3792fed26a02.png)

We should also take in consideration _consecutive_ characters, not just whether their position is early in the string.

I.e. consecutive characters always should sort before: 1 match (`icon`) should always be before two matches (`i` and `con`).

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14727 https://github.com/Microsoft/vscode/issues/20553 https://github.com/Microsoft/vscode/issues/1964 https://github.com/Microsoft/vscode/issues/21019 https://github.com/Microsoft/vscode/issues/14879

Wanted to revisit in March.
