### ISSUE TITLE
Exception view zone overlaps characters

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21066]
Refs: https://github.com/Microsoft/vscode/issues/20812

![image](https://cloud.githubusercontent.com/assets/900690/23205219/52d46d28-f8e9-11e6-88f5-c8c80265b678.png)

Not sure if this is an issue with the editor or the exception widget itself.

**Comment by alexandrudima** [comment]
I couldn't repro in today's insiders. Perhaps @michelkaporin fixed something?

![image](https://cloud.githubusercontent.com/assets/5047891/23250673/6cf6f920-f9aa-11e6-89ed-9d66b914733b.png)

**Comment by michelkaporin** [comment]
It is an issue with the widget itself.

Most likely @bpasero was testing it not on the latest source code yesterday (as some CSS amends where pushed later after yesterday's build). It works now, however there is still the overlap case, when there is a very small size for the editor selected. I am looking into it.

**Comment by bpasero** [comment]
I tested latest running out of sources btw.

**Comment by isidorn** [comment]
Fixed via #21296
