### ISSUE TITLE
TS: quick fix does not go away when import added

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21060]
![untitled](https://cloud.githubusercontent.com/assets/900690/23203581/66cda58e-f8e3-11e6-9295-413722c8afda.gif)

**Comment by jrieken** [comment]
similar steps

* have below snippets
* have `test.abc` with `far\nboo`
* go on second line, see light bulb
* select quick fix :bug: light bulb is still there

```ts
    vscode.languages.registerCodeActionsProvider('abc', {
        provideCodeActions(doc, range, message) {

            if (range.start.line > 0) {
                const beforeLine = doc.lineAt(range.start.line - 1);
                const thisLine = doc.lineAt(range.start);

                if (beforeLine.text === 'far') {
                    return [{
                        title: 'Far -> Foo',
                        command: 'changeFar',
                        arguments: [doc, range.start.line - 1]
                    }];
                }
            }
        }
    });

    vscode.commands.registerCommand('changeFar', (doc, line) => {
        const edit = new vscode.WorkspaceEdit();
        edit.replace(doc.uri, new vscode.Range(line, 0, line, Number.MAX_SAFE_INTEGER), 'foo');
        return vscode.workspace.applyEdit(edit);
    });
```

**Comment by chrmarti** [comment]
- VSCode Version: Code - Insiders 1.10.0-insider (b2a55bd66eb60af11c60ddd61b7581538b216051, 2017-02-24T20:30:00.778Z)
- OS Version: Darwin x64 15.6.0
- Extensions: None

Still reproduces:
![21060](https://cloud.githubusercontent.com/assets/9205389/23321742/94b282ae-fa95-11e6-9928-f24518e93ae1.gif)

**Comment by jrieken** [comment]
This was fixed after the Friday build

**Comment by bpasero** [comment]
@jrieken no it was not, and fwiw I can reproduce running out of sources.

**Comment by jrieken** [comment]
So the flow as described [above](https://github.com/Microsoft/vscode/issues/21060#issuecomment-282258311) works. It goes cursor/diagnostics change event, show light bulb, execute command, update code actions. 

The problem is that TypeScript returns *stale code actions* right after the change as been applied. My guess is that it seems to be waiting for a validation run to finish. I will implement a workaround to accommodate for the TypeScript behaviour.
