### ISSUE TITLE
test: indicate progress to screen reader users

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#210661]
Refs #209661, #196396, #210590

- [x] Windows @dbaeumer 
- [x] macOS @eleanorjboyd 
- [x] Linux @roblourens 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23210661%0A%0A&assignees=meganrogge)

---

Formerly, progress information wasn't communicated to screen reader users. Now, anywhere we have a progress bar, if it takes more than seconds, a progress signal will be played and then repeat every five seconds. 

This happens when something is very slow, such as:
- the first time a notebook editor is loaded
- running a notebook cell with a `sleep` call or a lot of processing 
- running an `@workspace` chat request

The sounds will play in parallel if several things are in progress simultaneously.

- Enable a screen reader. Verify that any time a progress bar is shown for more than 3 seconds, you hear this sound.
- Disable this `accessibility.signals.progress` setting. Verify that you don't hear it. 
- Disable screen reader mode. Verify that you don't hear it. 
- Add this to your settings file, reload the window, verify that the migration to `accessibility.signals.progress` has succeeeded 
```
accessibility.signals.chatResponsePending: {
   "sound": "off",
   "announcement": "off"
}
```

**Comment by eleanorjboyd** [comment]
When I try and put "  "accessibility.signals.chatResponsePending": {
   "sound": "off",
   "announcement": "off"
}" in my settings (both workspace and user level) it grays out and says "Unknown Configuration Setting". Is there something else I need to enable?

**Comment by roblourens** [comment]
That seems by design @eleanorjboyd, it's deprecated
