### ISSUE TITLE
can't access marketplace behind proxy

### ISSUE THREAD

**Issue by eolandezhang** [Microsoft/vscode#21074]
- VSCode Version: Code - Insiders 1.10.0-insider (256d76fed7947e7289f921df10658d7a69233b65, 2017-02-22T07:10:23.895Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.set  “http.proxy ”：“http://username:password@xxx.xxx.xxx.xxx:80"
2.search extension
3.get message : Failed to load resource: https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery net::ERR_TUNNEL_CONNECTION_FAILED

e.doShow	@	workbench.main.js:103

**Comment by roblourens** [comment]
Please try the steps in https://github.com/Microsoft/vscode/issues/18103 to help us debug proxy issues
