### ISSUE TITLE
Promise variables show as undefined although they are not

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2107]
See attached screen shot. The promise argument shows as undefined everywhere but the console reveals the truth when you 'use' it. 

![screen shot 2016-01-19 at 15 00 06](https://cloud.githubusercontent.com/assets/1794099/12420514/6f45f84e-bebd-11e5-8c3f-b705faf79e19.png)

**Comment by jrieken** [comment]
to reproduce:

* set a breakpoint in the unhandledRejection [handler](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/node/pluginHostProcess.ts#L50)
* execute the snippet(*) below in an extension (as command for instance)

when pauses `promise` is undefined

*snippet
```
  const rejectedPromise = new Promise((resolve, reject) => {
            // setTimeout(reject, 500);
            reject('foo');
        });

        setTimeout(() => {
            rejectedPromise.catch(() => {
                console.log('handing error now');
            });
        }, 2000);

```

**Comment by weinand** [comment]
@jrieken this is a limitation of node debugging. **node-inspector** shows the same behavior:
![2016-01-19 15-29-08](https://cloud.githubusercontent.com/assets/1898161/12421280/be86cbf0-bec1-11e5-91a9-1e4f696642fa.png)

**Comment by rebornix** [comment]
Ran into the same situation. Whenever I create a new promise, the intellisense keeps saying it's undefined.
