### ISSUE TITLE
Dirty diff decoration goes into line numbers

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21072]
![image](https://cloud.githubusercontent.com/assets/900690/23205850/b2e55e50-f8eb-11e6-9f88-ff2644e985e7.png)

Steps to Reproduce:

1. paste the contents of a file over and over again to produce high line number
2. wait for dirty diff to kick in

=> it overlaps the line numbers

**Comment by alexandrudima** [comment]
Root cause is #21073
