### ISSUE TITLE
Issue Reporter: Clarify what is meant by a `Performance Issue`

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#210739]
Type: <b>Feature Request</b>

Some issues created through Issue Reporter are categorized by the person reporting them as `Performance Issue` yet don't seem to relate to slow performance, hangs or freezes. Perhaps people who aren't native English speakers interpret the term as meaning that VS Code isn't working (performing) as they expect.

Maybe add some hints to the dropdown entry, e.g. `Performance Issue (slow, freezing, CPU / memory hungry)`?

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by justschen** [comment]
@gjsjohnmurray that's a good point. I'll do some investigation to how often this is might be used! this would definitely decrease the number of "performance issues" that aren't actually performance issues.
