### ISSUE TITLE
SCM: badge size could be aligned

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21079]
At least when the digit is same length the badges could have the same size:

![image](https://cloud.githubusercontent.com/assets/900690/23206887/9b7a9632-f8ef-11e6-8a29-9cb3dc65c865.png)

**Comment by bpasero** [comment]
Ok this actually applies to any badge, was not aware:

![image](https://cloud.githubusercontent.com/assets/900690/23213923/25c91706-f90d-11e6-8e0d-1a6764368703.png)

**Comment by joaomoreno** [comment]
Wow, that one is **really** broken.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
