### ISSUE TITLE
Diffs from ChatResponseTextEditParts should be inline when narrow

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#210793]
Adopting the ChatResponseTextEditPart, it's very nice that it's shown in the diff editor, but it's a bit hard to read due to is narrowness

![image](https://github.com/microsoft/vscode/assets/2230985/3b45cd01-4831-4ad7-9db0-cee3a86530d2)

**Comment by hediet** [comment]
Seems to be intentially disabled:

https://github.com/microsoft/vscode/blob/a49c81edea6647684eee87d204e50feed9c455f6/src/vs/workbench/contrib/chat/browser/codeBlockPart.ts#L608

**Comment by jrieken** [comment]
It will almost always be narrow because chat is in the sidebar or inside an editor. We have discussed

* an explicit toggle
* some smarts that automatically uses inline when diffs are dominated by insertions and/or removals

@hediet Is the latter something the diff editor could support?

**Comment by hediet** [comment]
> some smarts that automatically uses inline when diffs are dominated by insertions and/or removals

Yes, the diff editor could support this! I don't think this feature would work very well for changing/writable files, as it might jump.

**Comment by jrieken** [comment]
> I don't think this feature would work very well for changing/writable files, as it might jump.

You could do this only on first open/load of a model but not on subsequent changes to the models.

**Comment by hediet** [comment]
Verification steps:
* Make the AI suggest an edit in the side bar (you can start in the inline chat and then use "view in sidebar chat")
* Notice that the diff uses the inline view when there are only insertions/deletions (no modifications)
