### ISSUE TITLE
Shutdown: allow to selectively cancel operations that block shutdown

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#210731]
When a save partipant is taking a long time to save a file (clearly an extension issue), one can usually cancel them. However, if that happens while closing VS Code, the only option a user has is to "Close Anyway", losing any unsaved changes to that file.

At least one of the two following things should be possible:
- Cancel waiting for background save participants in order to save the file and shutdown VS Code
- Cancel the VS Code shutdown in order to cancel save participants manually

Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.88.1
- OS Version: Windows 11 23H2

![image](https://github.com/microsoft/vscode/assets/12128514/b4a8c889-93ef-4d61-9f2a-8e98d535f192)

**Comment by bpasero** [comment]
Yes, I think that makes sense.
