### ISSUE TITLE
Panel location

### ISSUE THREAD

**Issue by anwshl** [microsoft/vscode#210749]
Type: <b>Bug</b>

The `workbench.panel.defaultLocation` setting should set Panel location, but it does not work.

A quick search, and I've found the solution.
https://code.visualstudio.com/updates/v1_64#_replacing-panel-location

The update states that the setting is deprecated. If so, should it be removed?

Also, it says that the 'View: Move Panel ...` commands are also deprecated, but they work:)

It's all very confusing. 

I get how to move the Panel, but I don't get why deprecated setting/commands exist.

VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin x64 23.4.0
Modes:

Extensions: none

**Comment by benibenj** [comment]
`workbench.panel.defaultLocation`: Controls the default location of the panel (Terminal, Debug Console, Output, Problems) in a new workspace. It can either show at the bottom, top, right, or left of the editor area.

You can use the `Move Panel XY` to move the panel around
