### ISSUE TITLE
Debugging ANGULAR project in VSCode not working.

### ISSUE THREAD

**Issue by mayank594** [microsoft/vscode#210717]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. In launch.json created Launch Chrome against localhost as:

{
  "version": "0.2.0",
  "configurations": [
      {
          "type": "chrome",
          "request": "launch",
          "name": "Launch Chrome against localhost",
          "url":"https://anonymous.local:3200/Home/Welcome",
          "webRoot": "${workspaceFolder}"
      }
  ]
}
    The url indicates the login page of the application

2. Putting breakpoints at the required places in the angular code(ts files)

3. Selecting  "Launch Chrome against localhost" from and start debugging(f5)
![image](https://github.com/microsoft/vscode/assets/17490407/7a612121-51f4-4ad4-b304-d2108d24c6da)

4. Application starts and logged in successfuly, navigate to page where breakpoint will be hitted->
    application hangs and nothing happens, neither the breakpoint is reached, after few minutes of wait the break point is reached and when press f10 or f5 this message appears: 
![image](https://github.com/microsoft/vscode/assets/17490407/8f7d222f-d81f-4fda-80be-73a46eed0f36)

I have to then either reopen or close vscode which ends up everything.

This is really frustrating as it hampers my daily development,
this was working perfectly fine but from last few updates i am seeing this error.

I have tried uninstalling and re installing vs code, also updated to version 1.87.2 but nothing worked.
Please help me out in resolving this on priority.

**Comment by connor4312** [comment]
Thanks for the issue, unfortunately I'm not able to reproduce it at the moment. Could you share your user settings so I can see if there's something in there I might be missing?

**Comment by mayank594** [comment]
Hi @connor4312 , as suggested i've updated to the latest version 1.89.1 today and unfortunately the issue still persists. 
![image](https://github.com/microsoft/vscode/assets/17490407/553becd1-1d5f-4d47-9444-dd22dca30ef4)

Whenever I attach a debugger it takes a lot of time to the debugger to hit and if it hits and i try to proceed this message appears after waiting for few minutes and i have to restart vscode .
![image](https://github.com/microsoft/vscode/assets/17490407/b4a16df6-6cf1-4b37-8bae-fcb48d1fd90b)


my launch.json file 
![image](https://github.com/microsoft/vscode/assets/17490407/8a18bdcb-01c4-4d3f-b62d-eaac73dd2168)


This is really frustrating as i have to be dependent on browser dev tools to debug any piece of code. I would really appreciate help from your end.

**Comment by connor4312** [comment]
Could you share your user settings as well? Thanks!

**Comment by mayank594** [comment]
Which settings are you referring to?

**Comment by mayank594** [comment]
> Could you share your user settings as well? Thanks!

if you can be more specific which user settings you're referring, will share.

**Comment by connor4312** [comment]
You can open the settings.json though the command **Preferences: Open User Settings (JSON)**

**Comment by mayank594** [comment]
[settings.json](https://github.com/microsoft/vscode/files/15390634/settings.json)
Pls find the file attached.

**Comment by mayank594** [comment]
@connor4312 any suggestions?

**Comment by SPKorhonen** [comment]
I have the same problem. When debugging Edge or Chrome the browser crawls to 1/100th of normal speed. If one tries to stop the debug session, VS Code freezes completely. Only using reload from the "window is not responding" -dialog restores functionality. 

In my experience using FireFox and "Debugger for Firefox" extension works and I'm currently using it as a work-around.

I also have a colleague who has the same issue. Updating or complete re-install doesn't resolve the issue.

**Comment by SPKorhonen** [comment]
Additional datapoints:
- Ms Edge is completely unusable. Slowdown by factor >1000, huge cpu utilization even when page and debugger are idle.
- Brave seems to work just fine based on a few days usage.
- Vivaldi is also viable though noticeably slower than Brave

Thus I'm using Brave as current work-around

**Comment by marksvc** [comment]
Using Code I attach the debugger to a browser that is running an Angular Typescript application. I can hit breakpoints and debug using VSCode 1.94.2. But after upgrading VSCode to 1.95.1, if I have a breakpoint that I would hit then the application in the browser hangs. VSCode doesn't show that it has hit the breakpoint. I don't see anything in DEBUG CONSOLE that seems like new information to me. Nothing seems to happen until I Disconnect the debugger from the attached browser.

This is with Chromium v130.0.6723.69, installed via Snap.
This is happening on Ubuntu 20.04 and 22.04.

If I don't have any breakpoints to hit, then the application does not hang.
I can open dev tools in Chromium and set and hit breakpoints in dev tools.

I have not tried other browsers.

**Comment by connor4312** [comment]
Can you grab a profile of the renderer process so we can try to see what's causing the blockage? https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process has instructions. Just a few seconds of freeze time in the profile should be fine, you don't have to try and profile the entire frozen duration.
