### ISSUE TITLE
VSCode glitches during debugging

### ISSUE THREAD

**Issue by frankyhollywood** [microsoft/vscode#210733]
Type: <b>Bug</b>

This week I was pair programming with a collegue, during debugging when a breakpoint is hit the screen glitches and flickers, that is, all code below the breakpoint moves and flickers.

It was on a Mac so I thought is was a Mac issue, but today on my own laptop (Windows 11, latest updates, latest VSCode, in WSL) I notice the same. 

It seems to disappear when you disable co-pilot, so somehow copilot wants to do something during debugging.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.71GB (32.16GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/dev/git/fairspace-protolm/projects/saturn --remote=wsl+Ubuntu --crash-reporter-id 470a7ea2-b07e-49ed-8eb2-4651ce8fb34d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 2803)|
|Memory (System)|31.20GB (18.03GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 2803)|
|Memory (System)|31.20GB (18.04GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 2803)|
|Memory (System)|31.20GB (18.04GB free)|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.354.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
asciidoctor-vscode|asc|3.2.3
vscode-eslint|dba|2.4.4
python-environment-manager|don|1.2.4
gitlens|eam|14.9.0
prettier-vscode|esb|10.4.0
flow-for-vscode|flo|2.2.1
copilot|Git|1.180.0
copilot-chat|Git|0.14.1
vscode-github-actions|git|0.26.2
rainbow-csv|mec|3.11.0
vscode-docker|ms-|1.29.0
debugpy|ms-|2024.4.0
pylint|ms-|2023.10.1
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
sarif-viewer|MS-|3.4.4
vscode-jest|Ort|6.2.4
java|red|1.29.0
vscode-yaml|red|1.14.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.13.5
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.26.0
vscode-java-test|vsc|0.41.0
vscode-maven|vsc|0.44.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
gee8j676:31009558
dsvsc021:30996838
bdiig495:31013172

```

</details>

**Comment by frankyhollywood** [comment]
https://github.com/microsoft/vscode/assets/29271979/e409eeb2-0f16-4b77-a342-1759d0c81bb1

**Comment by roblourens** [comment]
That's weird. I'm guessing that disabling `debug.inlineValues` works around it as well. @connor4312 looks like this code might have changed?

**Comment by connor4312** [comment]
I've not changed the rendering, it's probably an existing bug.

**Comment by MendelBak** [comment]
I have the same issue when pausing on any breakpoint in my PHP code. Makes it extremely-difficult to near-impossible to perform any debugging.



Here's video of it occurring.

https://github.com/microsoft/vscode/assets/17897003/6fae9a19-f6d0-42c3-8bb4-7e2dcbb57e23

PC Info
Processor	Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor

OS Info
Edition	Windows 11 Home
Version	23H2
Installed on	‎01-‎Nov-‎22
OS build	22631.3447
Experience	Windows Feature Experience Pack 1000.22688.1000.0


VSCode Info
Version: 1.89.0 (user setup)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

I tried rolling back to VSCode version 1.87.2 manually but I had the same glitches on that version.

I just tried @roblourens solution of disabling `debug.inlineValues` which worked to resolve this bug for me and it no longer stutters.

**Comment by connor4312** [comment]
We re-evaluate inline values based on a number of events, including changes to the editor and 'invalidated' events from the debugee. I'm guessing folks have some extension that started triggering aggressive updates somehow. Running "Help: Start Extension Bisect" may help narrow this down if it's an extension other than the debugger. I'll make a change to avoid flickering when updates happen.

**Comment by connor4312** [comment]
I also made a fix for a separate issue, but seen in the videos, where inline values appearing when word wrap is on can change the vertical position of the cursor on screen. We now preserve it.

**Comment by frankyhollywood** [comment]
This 'some extension' is co-pilot, the behavior stops when you disable it. Great you fixed it!

**Comment by alexr00** [comment]
@connor4312 what's the best way to verify this?

**Comment by connor4312** [comment]
1. Have `debug.inlineValues` on
2. Evaluate something in the REPL
3. Verify you don't see them 'flash'
