### ISSUE TITLE
Add Line comment shortcut not working

### ISSUE THREAD

**Issue by NathanHannon** [microsoft/vscode#210778]
Type: <b>Bug</b>

During normal usage, the "Add Line Comment" keyboard shortcut doesnt work. I am using the default of Ctrl + /. My keyboard works because I can use other Ctrl keyboard shortcuts fine.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.14.0-362.8.1.el9_3.x86_64
Remote OS version: Linux x64 5.14.0-362.8.1.el9_3.x86_64

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
chatpanelt:31018789
dsvsc021:30996838
g316j359:31013175

```

</details>

**Comment by ArturoDent** [comment]
Run the `Developer: Toggle Keyboard Shortcuts Troubleshooting` command and paste the results.

**Comment by NathanHannon** [comment]
Here is the output: 

2024-04-23 08:56:30.213 [info] Started local extension host with pid 3004.
2024-04-23 08:56:30.406 [warning] [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
2024-04-23 08:56:30.516 [error] Extension 'github.copilot-chat' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): extensionsAny, newSymbolNamesProvider, interactive, chatProvider, codeActionAI, findTextInFiles, findFiles2, textSearchProvider, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, mappedEditsProvider, aiRelatedInformation, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, contribSourceControlInputBoxMenu, authLearnMore, testObserver, aiTextSearchProvider
product.json (WINS): handleIssueUri, interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver
2024-04-23 08:56:30.563 [warning] [redhat.vscode-commons]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
2024-04-23 08:56:30.563 [warning] [redhat.vscode-xml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
2024-04-23 08:56:30.574 [warning] [redhat.vscode-yaml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
2024-04-23 08:56:33.925 [info] [perf] Render performance baseline is 85ms
2024-04-23 08:56:36.947 [error] [Extension Host] [chat] Registration of interactive providers failed: Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: handleIssueUri, interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat

**Comment by ulugbekna** [comment]
Hi, 

What you posted doesn't include the expected output. Please, try again: 

Could you please try the [following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

1. Run the command "Developer: Toggle Keyboard Shortcuts Troubleshooting" (you can, for example, run it from the Command Palette). 

   This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.

2. Press exactly the keybinding you desire
 
3. Check what VS Code detects

If you are having trouble understanding the output, please feel free to paste here and we'll be happy to help ☺️

**Comment by ulugbekna** [comment]
It seems that `github.copilot.acceptCursorPanelSolution` command seems to be taking over the command to add a line comment. You could either remove that keybinding if you don't use it or make its "when" clause more specific, eg `github.copilot.activated && github.copilot.panelVisible && !editorTextFocus`
