### ISSUE TITLE
VS code becomes very sluggish after running jupyter (Render takes up much RAM)

### ISSUE THREAD

**Issue by ZihaoWang2000** [microsoft/vscode#210735]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.1
- OS Version: MacOS Sonoma 14.4.1 

Steps to Reproduce:

1. When I opened the application, the loading speed is great and everything is fine. But then after I ran the jupyter notebook (which is relatively high-RAM consuming), the whole application becomes very sluggish, especially when I tried to type and used the extension called Pylance (The interface sometimes became unresponsive). The whole interaction speed didn't change at all even after I stopped running and restarted the kernel. 
2. I thought it might be caused by Pylance, so I uninstalled it, restarted the whole application, and reran the code. The whole speed is fine, but weird things happened when I checked the extensions that I have. The details page of each extension takes long to load and respond, and code helper (render) suddenly takes up very high RAM until the loading is done (usually more than 2 seconds). 

https://github.com/microsoft/vscode/assets/114076648/b062dac3-b4aa-4ed6-8228-687d1b2df1b7

**Comment by gjsjohnmurray** [comment]
Did you try the `Start Extension Bisect` command?

**Comment by ZihaoWang2000** [comment]
> Did you try the `Start Extension Bisect` command?

Thank you for your comment! I tried it just now and found "Markdown All in One" might be the cause. However I have to continue to reproduce the steps to see if it is the real cause.

**Comment by Zhangyanbo** [comment]
Same issue. It back to normal when I disabled all extensions. But I'm not sure which extension(s) causes this.

**Comment by ZihaoWang2000** [comment]
![iShot_2024-04-21_21 50 48](https://github.com/microsoft/vscode/assets/114076648/8621123d-8f4f-4f37-a1a1-9b91d7a15149)
After reinstalling Pylance and running the jupyter, the app keeps laggy and the window finally becomes unresponsive.

**Comment by DonJayamanne** [comment]
Then you for filling this issue and sorry you are running into this

Please can you try again with pylance extension disabled/uninstalled

**Comment by DonJayamanne** [comment]
Given that it works with extensions disabled
Please can you to using the extension bisect utility to find the extension that causes this
https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

**Comment by ZihaoWang2000** [comment]
> Given that it works with extensions disabled Please can you to using the extension bisect utility to find the extension that causes this https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

Hi, I think it is a problem caused by long-time code running, so it will take long for the extension bisect to find the real cause. If I understand correctly, the bisect will restart the interface every time, and there is no problem with the renderer and the loading speed since the interface is renewed. But I think Pylance is definitely contributing to the problem, because after I disabled it, there seems no obvious issue with code running or writing, except that the rendering of each extension is still slow.
