### ISSUE TITLE
Notebook editor takes a long time to load

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#210770]
Sometimes opening a fairly small notebook takes over 10 seconds.
Most consistent repro is to reload without any tabs open, wait for everything to settle, then open a notebook.

Perf profiles don't show heavy CPU usage but very long animation blocks (the loading indicator?)
![image](https://github.com/microsoft/vscode/assets/2019016/23fa0494-5b65-4dc4-b708-72925a544dd3)

Extension profile has plenty of idle time while the editor is loading:
![image](https://github.com/microsoft/vscode/assets/2019016/db9af751-838e-4e7a-82eb-c0320050249f)

**Comment by rebornix** [comment]
We added telemetry for tracking if the slowness is coming from creating webview + warming up.
