### ISSUE TITLE
serve-web unable to connection to Extensions marketplace

### ISSUE THREAD

**Issue by NikeahX3** [microsoft/vscode#210705]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.88.1
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Start VS Code via code serve-web --port 7000 --host 0.0.0.0
2. Go to Extensions

I get the following:
![image](https://github.com/microsoft/vscode/assets/115482691/06fd99b2-af3f-47e0-bbaf-f3cbc3966395)

I've got a reverse proxy set up via nginx, config is:

 server {
     listen 443 ssl;

     ssl_certificate /path/to/cert/selfsigned.crt;
     ssl_certificate_key /path/to/key/selfsigned.key;

     location / {
         proxy_pass http://localhost:7000;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection upgrade;
         proxy_set_header Accept-Encoding gzip;
     }
 }

Would be great if this could be resolved..

Appreciate the work that's gone into this, thanks!

**Comment by NikeahX3** [comment]
Just seen the vscode-remote-release repository, should this be filed as an issue over there instead?

**Comment by aeschli** [comment]
Here is the correct repo, but unfortunately accessing the code web server through a reverse proxy (or other means) is outside of our scope. I don't have the resources to test and debug this.
Happy to accept a PR if you find the issue.
