### ISSUE TITLE
code tunnel seems to be using the old instructions

### ISSUE THREAD

**Issue by scott-vsi** [microsoft/vscode#210751]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.1
- OS Version: Fedora 39

Steps to Reproduce:

1. `$ code tunnel` prints out:
```
To grant access to the server, please log into https://github.com/login/device and use code XXXX-XXXX
```

This seems to be using the old [instructions](https://code.visualstudio.com/blogs/2022/07/07/vscode-server#_getting-started), which seem to be outdated (there is a Note at the top of the page pointing to this blog post: https://code.visualstudio.com/blogs/2022/12/07/remote-even-better, and the latest instructions on tunnels (https://code.visualstudio.com/docs/remote/tunnels#_using-the-code-cli) say that after running `code tunnel` I should get a URL tied to the remote machine such as `https://vscode.dev/tunnel/<machine_name>/<folder_name>`

Is this expected?

**Comment by connor4312** [comment]
Yes, it's expected, you need to log in first. We don't allow anonymous tunnel access.

**Comment by scott-vsi** [comment]
Got it. Do you want me to put up a PR that updates the documentation?
