### ISSUE TITLE
Terminal tab folder names aren't showing `e` on Windows PowerShell

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#210783]
Found by @andreamah 

I recently changed the serialization of messages from shell integration so that's likely the cause - `e isn't supported in pwsh 5

![image](https://github.com/microsoft/vscode/assets/2193314/7a80c504-0c3c-4bff-9a41-efa45c53bf87)

**Comment by benibenj** [comment]
Still seeing this in newest insiders
![explorer_BCUgHzLlUj](https://github.com/microsoft/vscode/assets/44439583/8b78b2b5-1883-4840-8e78-c8c35d4bea61)

**Comment by Tyriar** [comment]
Condition is the wrong way around 🤦 

https://github.com/microsoft/vscode/blob/9782bbccd6e096b13e0e745a5f30bc5819586233/src/vs/workbench/contrib/terminal/browser/media/shellIntegration.ps1#L62-L64
