### ISSUE TITLE
If #file outline is larger than limit, the #file is not included in the prompt

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#210742]
From https://code.visualstudio.com/docs/copilot/copilot-chat

"Note: if possible, the full contents of the file will be included when you use `#file`. If that is too large to fit into the context window, an outline of the file will be included that includes functions and their descriptions without implementations. If the outline is also too large, then the file won't be part of the prompt."

Can we handle the case when the outline is too large more gracefully?

Right now a financial institution that is a big Copilot customer is hitting an issue all the time that `#file` is never included in their prompts. They believe this is due to that fact that their files are too large, and the outline always hits that limit.

Starting with @roblourens

**Comment by roblourens** [comment]
We can probably do a smaller summary in some cases but what else can we do?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/1083
