### ISSUE TITLE
Typing becomes slow and choppy in jupyter

### ISSUE THREAD

**Issue by GBoGH** [microsoft/vscode#210720]
Type: <b>Performance Issue</b>

When using jupyter notebooks, after a while, vscode becomes unresponsive/choppy when typing or removing text.

I didnt see this happen with any other file, just jupyter notebooks

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (6.91GB free)|
|Process Argv|--crash-reporter-id 654f2626-32ad-4b3f-8c08-9526a516b162|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   108	 17768	code main
    0	    44	  3228	   utility-network-service
    0	    28	  8796	   crashpad-handler
    1	   417	  9596	window [1] (homework_01_B232.ipynb - bi-ml2-2024-feikjaku - Visual Studio Code)
    0	    90	 12332	ptyHost
    0	   131	  3048	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\Jakub Feik\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     7	 11500	     conpty-agent
    0	     7	 14676	     conpty-agent
    0	   131	 19760	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\Jakub Feik\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	   104	 13572	window [2] (Issue Reporter)
    1	   181	 13692	   gpu-process
    0	   108	 20532	shared-process
    0	   290	 22712	extensionHost [1]
    0	   401	  9232	     electron-nodejs (bundle.js )
    0	    17	 13768	     "c:\Users\Jakub Feik\.conda\envs\ml2\python.exe" "c:\Users\Jakub Feik\.vscode\extensions\ms-toolsai.jupyter-2024.3.1-win32-x64\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py" --ppid 22712
    0	    11	 18500	       C:\Windows\system32\conhost.exe 0x4
    0	    89	 20708	     "C:\Users\Jakub Feik\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Jakub Feik\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=22712
   92	   524	 21588	     electron-nodejs (Nh.js )
    0	    11	  1352	       C:\Windows\system32\conhost.exe 0x4
    0	   141	 23268	   window
    0	    91	 24020	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (homework_01_B232.ipynb - bi-ml2-2024-feikjaku - Visual Studio Code)
|    Folder (bi-ml2-2024-feikjaku): 48 files
|      File types: pkl(34) csv(4) ipynb(2) gitignore(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.4.0
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
jupyter|ms-|2024.3.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
724cj586:31013169

```

</details>

**Comment by rebornix** [comment]
We have made improvements to the typing issue in main branch. Can you please try VS Code Insiders and see if it helps? @GBoGH

**Comment by GBoGH** [comment]
I have not experienced any issues with the insiders version

**Comment by DonJayamanne** [comment]
Fixed as part of https://github.com/microsoft/vscode/issues/209787
