### ISSUE TITLE
Welcome page: weird flow of installing keybindings

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#21077]
Refs: #21034

OS X, insiders
1. Welcome page, click on sublime in keybindings
2. I get a notification about how a window will clickly reload
3. I click ok and no reload is happening, instead the keybinding is being installed and only after the installation a reload happens
4. This is much different than the usual extension install experience and I am not sure why are we differentiating here

I would expect that upon click on sublime we simply install the extension and open the extension viewlet. The extension will then have a reload button so a user can easily reload if he chooses. And not showing any message dialog at the top

![screen shot 2017-02-22 at 11 01 47](https://cloud.githubusercontent.com/assets/1926584/23206545/522ac0f2-f8ee-11e6-985c-f74c37a07d96.png)

**Comment by michelkaporin** [comment]
Linux, insiders.

Agree with @isidorn, probably the best way would be to simply navigate the user to extensions viewlet with the extension selected/focused. Then he would decide himself whether he wants to install it or not by clicking on the 'Install' button. 

This would be consistent with usual extension installation experience.

**Comment by chrmarti** [comment]
The idea here is to shortcut the many clicks and the viewlet with its list of extensions that must seem complex to new users. Instead the message box briefly explains what users would otherwise have to figure out step-by-step by themselves.

**Comment by chrmarti** [comment]
Improvements:
- Install keymap in background while waiting for confirmation. (Keymap will be disabled if not confirmed.)
- Dismiss confirmation after OK / Cancel.
- If not installed 300ms after confirmation, show a message: "Installing the Vim keyboard shortcuts...".

**Comment by isidorn** [comment]
I still dislike this flow but adding verified label since it behaves as you expaplined in your last comment
