### ISSUE TITLE
Inconsistent naming of editor options

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21078]
We have two new options `editor.minimap.enabled` and `editor.enableDragAndDrop`. Both talk about enabling a feature but use the word 'enable' is different ways. Also, we don't use 'enable' for other settings, like `editor.formatOnPaste` and not `editor.formatOnPaste.enabled` or `enableFormatOnPaste`

**Comment by alexandrudima** [comment]
I suggest we rename `editor.enableDragAndDrop` to `editor.dragAndDrop`.

The `editor.minimap.enabled` is using a dot notation because I thought we want to add soon more options. `editor.minimap.maxColumn`, `editor.minimap.renderFindMatches`, etc.

@jrieken Do you have a suggestion ?

**Comment by jrieken** [comment]
I think that's fair. When there are more options we have used the dot notion before.

**Comment by alexandrudima** [comment]
I think it tries to align with `explorer.enableDragAndDrop`...

**Comment by rebornix** [comment]
I'll go with `editor. dragAndDrop` in which case we can have a good alignment with others when we want to extend this dragAndDrop option.
