### ISSUE TITLE
[WelcomeUX] Welcome page: keybindings are already installed

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#21076]
Refs #21034

os x, insiders, welcome page

1. Welcome page, install sublime keyboard shortcuts, reload vscode
2. Click on sublime keybindings - a message bar appears
3. We should try using the message service as little as possible as it is pesky to get rid of (user must click)
4. I propose that instead we open the extensions viewlet and show the list of installed extenssions - that will make it obvious to the user that he has sublime keybindings installed

**Comment by egamma** [comment]
Actually just opening the extensions viewlet doesn't make it obvious that the sublime extension is already installed when I have lots of extension installed.

![image](https://cloud.githubusercontent.com/assets/172399/23209945/b8c06a30-f8fb-11e6-992a-16221c59ef90.png)

**Comment by isidorn** [comment]
Then I prose to open the extensions viewlet and search for 'sublime' that will focus the one you have installed

**Comment by chrmarti** [comment]
A new user might be helped best by a message directly explaining the issue, rather than a still unfamiliar UI with a list hinting at it.

**Comment by isidorn** [comment]
IMHO a new user would not have extensions already installed, so this scenario mostly does not affect brand new users.

**Comment by chrmarti** [comment]
Trying to be more gentle by removing the link for and indicating that it is the current keymap:
![screen shot 2017-02-23 at 3 38 39 pm](https://cloud.githubusercontent.com/assets/9205389/23284089/5d953d8c-f9de-11e6-8b15-14cc3c3cadb2.png)
