### ISSUE TITLE
"Revert Block" buttons don't work anymore if the second file is empty

### ISSUE THREAD

**Issue by ldeluigi** [microsoft/vscode#210885]
Type: <b>Bug</b>

Step 1: Create a file named `a.txt` with this content:
```
aaaa
bbbb
cccc
```

Step 2: create an empty file named `b.txt`

Step 3: Move with a terminal in the folder containing the files and run `code -d a.txt b.txt`

Step 4: Click on the arrow button and see that it doesn't work
![image](https://github.com/microsoft/vscode/assets/44567586/3e4cc46f-da80-4fad-8982-2717dda95729)

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.91GB free)|
|Process Argv|-d a.txt b.txt|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nginx-conf|ahm|0.3.5
swagger-viewer|Arj|3.1.2
freezed|bla|0.9.6
ccs-flutter-color|cir|1.2.4
dart-code|Dar|3.86.0
flutter|Dar|3.86.0
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|2.0.9
copilot|Git|1.180.0
copilot-chat|Git|0.14.1
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.86.1
gc-excelviewer|Gra|4.2.59
todo-tree|Gru|0.0.226
vscode-nginx-conf-hint|han|0.3.1
latex-workshop|Jam|9.20.0
vscode-edit-csv|jan|0.9.1
plantuml|jeb|2.18.1
vscode-peacock|joh|4.2.2
dotenv|mik|1.0.1
vscode-docker|ms-|1.29.0
debugpy|ms-|2024.5.11001012
isort|ms-|2023.13.10681007
python|ms-|2024.5.11021008
vscode-pylance|ms-|2024.4.102
remote-containers|ms-|0.354.0
cpptools|ms-|1.19.9
vscode-thunder-client|ran|2.21.11
nginx-formatter|ray|0.0.13
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
scala|sca|0.5.7
markdown-preview-enhanced|shd|0.8.13
even-better-toml|tam|0.19.2
vscode-icons|vsc|12.7.0
vscode-nginx|wil|0.7.2
txt-syntax|xsh|0.2.2

</details>

**Comment by sundeep-ravella** [comment]
working on this

**Comment by sundeep-ravella** [comment]
Oh wow I did not realize this was fixed. I've been working on it and just submitted a PR for a similar issue.

**Comment by sundeep-ravella** [comment]
My solution was also very similar.

**Comment by hediet** [comment]
@sundeep-ravella sorry! It was tricky to fix though.
