### ISSUE TITLE
Debug: Auto-focuses on source file despite 'Focus Editor On Break' setting disabled

### ISSUE THREAD

**Issue by sachiniSam** [microsoft/vscode#210811]
- VS Code Version:  1.88.1 
- OS Version: Darwin arm64 23.3.0

Even with both `Debug: Focus Editor On Break` and `Debug: Focus Window On Break` disabled, vscode still automatically switches focus to the source file containing the breakpoint when debugging, even if I'm focused on and working in a different file.

**Comment by stellarpower** [comment]
This is extremely annoying for me. My source code ends up littered with keystrokes from other files I am working on whilst I wait for my code to run, and until I found the window focus setting, it also means I could be on a completely different workspace trying to type an email for instance.

It also grabs the keyboard from any other part of VS Code. I could be typing in the terminal, writing a commit description, or telling Copilot how useless it is and this text all ends up going into the source file that is opened. So I think focus editor should at least have an option for focussing if only already within the text editor, if some would like this feature still but are interacting with other UI widgets.

My preferred behaviour would be for the tab to be highlighted in some way - a suitable colour from my current theme would be a nice way to see where the breakpoint has been triggered.

**Comment by roblourens** [comment]
I believe this is the same as https://github.com/microsoft/vscode/issues/189445
