### ISSUE TITLE
Terminal unable to render letter "e" in Workspace name

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#210880]
1. Open vscode or another repository which includes the letter "e"
2. Open a powershell terminal
3. See how the letter "e" is rendered as a box ()

<img width="199" alt="image" src="https://github.com/microsoft/vscode/assets/44439583/c7155237-3254-4dc2-b4bd-c0e02a0d976f">

**Comment by Tyriar** [comment]
Re-creating the terminal should fix it: https://github.com/microsoft/vscode/issues/210783

/duplicate
