### ISSUE TITLE
debug stepping, hot replace and autosave ... one should be off when debugger is active

### ISSUE THREAD

**Issue by avertx** [microsoft/vscode#210822]
Type: <b>Feature Request</b>

while debugging, hot replace is on, and autosave is on, makes for a bad experience.

while debug stepping, its common to modify code, but if you do and autosave is on, it causes hot replace to make your location jump somewhere else as soon as you start typing a few characters.

autosave should probably be inactive temporarily if hot replace is on and you're actively debug stepping.

Alas, you might need to warn the user incase they continue to edit in debug mode...

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin x64 23.4.0
Modes:

**Comment by roblourens** [comment]
Debugging what language?

**Comment by avertx** [comment]
Java

**Comment by roblourens** [comment]
I think this should be filed on the Java debug extension repo, sounds like it's specific to features from there
