### ISSUE TITLE
Minimap headers not detected in language extension

### ISSUE THREAD

**Issue by elringus** [microsoft/vscode#210894]
Type: <b>Bug</b>

Not sure if that's a bug or I'm just missing some config, but the new minimap headers (https://github.com/microsoft/vscode/pull/190759) are not detected with my language configuration.

I have comments specified in the [lang-config.json](https://github.com/naninovel/vscode/blob/1.20/language-configuration.json) as follows:

```json
{
    "comments": {
        "lineComment": ";"
    },
}
```

But it doesn't work:

![](https://i.gyazo.com/c3682c19a9a357a81c0a21baef27d0bc.png)

Here are the full sources of the language extension: https://github.com/naninovel/vscode/tree/1.20

To reproduce, install [the extension](https://marketplace.visualstudio.com/items?itemName=Elringus.naninovel) and add a comment line `; MARK: Test`.

Expected: Minimap header appears
Actual: Nothing appears on the minimap

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (16 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (53.15GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Elringus/Documents/GitHub/naninovel/unity/Assets/Scripts --crash-reporter-id 5553deaa-2949-4706-8450-f98d274a63e4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
naninovel|Elr|1.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
showvideot:31016892
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31022790

```

</details>

**Comment by alexdima** [comment]
@elringus If you run the command `F1 > Developer: Inspect Editor Tokens and Scopes` do you see "standard token type: Comment" ?

**Comment by elringus** [comment]
Nope, I get `Other`. Could it be LSP/semantic tokenizer overriding the default one?

![a899c0838fc23707658fc70771177cd8](https://github.com/microsoft/vscode/assets/2056864/72fd8a72-8165-46a2-842a-c224435c8ce5)

**Comment by alexdima** [comment]
This is a bit complicated:
* in the editor, there are typing operations, such as pressing `'` which behave differently when inside a comment or not. Outside a comment, `'` will auto-close itself. Inside a comment, it will not.
* therefore, we sometimes need to run the tokenization synchronously as part of typing to find out if you're typing in a comment or not. We don't do this all the times (like when typing at the end of a huge file) but we do it when tokenization has reached the line that is being typed on.
* this makes it that typing is predictable, i.e. pressing `'` behaves the same way at a particular code location as long as the line was tokenized before typing, irrespective if tokenisation was fast enough or slow.
* semantic tokens are async, so we cannot block the typing operation to wait on semantic tokens
* we therefore decided that semantic tokens cannot change the token type defined by syntactical highlighting.

**Comment by elringus** [comment]
Ah, so I just had to make a tm grammar with comments. Everything works now. Thanks for the help!
