### ISSUE TITLE
Test: Issue Reporter Walkthrough

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#210874]
Refs https://github.com/microsoft/vscode/issues/46726 and https://github.com/microsoft/vscode/issues/46726

- [x] Windows @karthiknadig 
- [x] macOS @daviddossett
- [x] Linux @andreamah 

note: if you've been a victim of an issue reporter TPI in the past, feel free to hand this off to someone else instead. 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23210874%0A%0A&assignees=justschen)

---

There has been work done in the past few iterations to overhaul our issue reporter flow for extensions, finally coming to a close with the removal of a previous API that was scrapped for a menu contribution point instead.

The purpose of this last issue reporter TPI is to do a final walkthrough and catch any outstanding issues that may exist after removing the API this iteration and shifting completely to not the API.

--- 

## To test:
1. Start an issue report via command palette -> `Help: Report Issue`
2. Try bug fixes, performance issues, feature requests.
3. For `Bug Report`, try some different extensions out, fill in title, description
4. For extensions, make sure to try specifically the Python and Python Debugger extensions. 
5. Try creating issue while logged in AND while logged out.
6. Try creating issues directly from quick access (`ctrl + p`) and typing `issue `.

## Things to verify:
- issues can be created!
- issues have right information
- UI looks good and also right
- switching between extensions doesn't cause issues.

**Comment by justschen** [comment]
@daviddossett we have a separate view in the quick access now (like below)!

<img width="622" alt="Screenshot 2024-04-24 at 1 09 44 AM" src="https://github.com/microsoft/vscode/assets/54879025/36e7f5f0-3c77-4bef-ab03-6b26ee761e0b">

the idea is that we ultimately start having extensions stop contributing directly in the command palette to reduce clutter

**Comment by daviddossett** [comment]
TIL!

**Comment by andreamah** [comment]
Okay I created a new github account and tested filing the issues. Works great!
