### ISSUE TITLE
Different icons support for java files

### ISSUE THREAD

**Issue by MateenKhan** [microsoft/vscode#210801]
Type: <b>Feature Request</b>

In java there are multiple types of files, that unfortunately have extension same ".java". Different file types are classes, interfaces, enums, etc

If there was a way to display those different icons based on the file content that would really help

I thought to configure any extension but unforturnately seems like vscode gives ability to change extension only by file extension not by contents of the file

I really love vscode but this limitation is making me think should i really be using this IDE

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by aeschli** [comment]
You want file icons based on the content of each file.

It's quite expensive to look at the content of a file. There are potentially hundert of file icons that need to be rendered at the same time. We would have to open all these file and parse them.

That certainly can be implemented, but requires a different architecture than we current have (e.g. computing icons in the background, having an index on disk remembering file icons).

We have no plans for such a change.
