### ISSUE TITLE
Support add menu to search panel

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#210835]
I made a extension with a command `search in git changed files`, and want to make it a menu item in search panel menu:

- https://github.com/tjx666/power-edit/commit/89cd3be5b86ddca7841d645fdc0c819e1d4db409#diff-f6bebb5f7443731836b3c64873eabf7338b0180ea95819e66d33dc3e6e229dbe

<img width="1512" alt="image" src="https://github.com/microsoft/vscode/assets/41773861/a95a96cc-dbd8-4a26-b5de-c12bb488244d">

**Comment by gjsjohnmurray** [comment]
https://code.visualstudio.com/api/references/contribution-points#menu-example includes an example of how to contribute a command to any view.

**Comment by tjx666** [comment]
thanks @gjsjohnmurray 

```json
"menus": {
            "view/title": [
                {
                    "command": "power-edit.searchInGitChangedFiles",
                    "when": "view == workbench.view.search",
                    "group": "navigation"
                }
            ]
        },
```
