### ISSUE TITLE
Hello everyone, I want to ask a question, now I use the window terminal ssh to remotely connect to the server, how to use the code command of vscode in the window terminal to open the remote file, when I input code, I encounter code not found

### ISSUE THREAD

**Issue by LeoKun1231** [microsoft/vscode#210823]
Hello everyone, I want to ask a question, now I use the window terminal ssh to remotely connect to the server, how to use the code command of vscode in the window terminal to open the remote file, when I input code, I encounter code not found

**Comment by bhavyaus** [comment]
Hi, could you please ensure that you've followed the setup steps mentioned here: https://code.visualstudio.com/docs/remote/ssh-tutorial

We also have this video tutorial you can reference: [Remote Development using VS Code.](https://www.youtube.com/watch?v=sakjpegUQsk&t=12s)
