### ISSUE TITLE
What is happening

### ISSUE THREAD

**Issue by justday0727** [microsoft/vscode#210863]
my vs code is like tis freezing i dont know what is happening on my screen it is not my screen problems cuz when I screenshot i screen shot it and it does not happen to my other applitcation
![image](https://github.com/microsoft/vscode/assets/140998767/a0d632db-cd48-41cd-8dbc-e6475aa25218)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/124226

Please disable hw acceleration in the application as workaround,
```
* Command Palette search for "Configure Runtime Arguments"
* Set disable-hardware-acceleration: true
* Restart
```

**Comment by dev336** [comment]
> Configure Runtime Arguments

any update in this problame?

**Comment by rzhao271** [comment]
@dev336 Those are steps to mitigate the issue. Let us know if the steps are not working or if you require more help with them.
