### ISSUE TITLE
List/tree: up/down keys should cycle

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#21084]
testing  #20434

* use down to navigate across debug viewlet pane
* reach 'Breakpoints' which is the last
* hit down, nothing happens, it should start atop again

**Comment by isidorn** [comment]
This seems like a general feature request for the tree and the list service -> forwarind to @bpasero

**Comment by bpasero** [comment]
I would not like to add this to any tree, there maybe people that are used to pressing and holding arrow down to reach the end that would be confused to start from the top again. This is also not how any native tree on any OS works as far as I know.

**Comment by joaomoreno** [comment]
This is supported: https://github.com/microsoft/vscode/blob/d1be9d02cd07cfc974a93ddf258ba344125d40dc/src/vs/base/browser/ui/list/listWidget.ts#L1380
