### ISSUE TITLE
Open editors: sections should not be collapsable

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#21086]
Refs: #20440

1. Click in open editors view, have at least two editors side by side
2. Use keyboard to navigate to Left section
3. Arrow left colapses the section
4. This section should not be collapsable - notice how the mouse click has no effect

**Comment by bpasero** [comment]
@joaomoreno not the nicest fix:

```
this.toDispose.push(this.tree.addListener2('item:collapsed', (event: IItemCollapseEvent) => {
	if (event.item && event.item.getElement() instanceof EditorGroup) {
		setTimeout(() => this.tree.expand(event.item.getElement())); // unwind from callback
	}
}));
```

I think what is missing on the tree is some API to tell that a model element cannot be expanded.
