### ISSUE TITLE
Debug: weird column indicator in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21080]
![image](https://cloud.githubusercontent.com/assets/900690/23207012/0c212c02-f8f0-11e6-96e5-284ae2fe4cfa.png)

If I am hitting the first column of a line, I think we should not show the extra indicator.

**Comment by isidorn** [comment]
We do not show it, we only show it if the previous stop happened on the same line.
Let me know if that is not the case and you always see it

**Comment by bpasero** [comment]
Yeah I cannot reproduce if I just hit a breakpoint. Still, I am not sure how I ended up in this state and what it means.

**Comment by isidorn** [comment]
Ok I know how to repro
1. Start debugging and hit first breakpoint.
2. Start debugging again and hit the same breakpoint -> notice column indication

I should clear state in between debug sessions

**Comment by bpasero** [comment]
Yeah thats it 👍
