### ISSUE TITLE
Passing registered chat variable in query param of "workbench.action.chat.open" does not get detected as a chat variable

### ISSUE THREAD

**Issue by k-dot-11** [microsoft/vscode#210819]
Currently when you register a command in vscode extension which executes the "workbench.action.chat.open", you can pass 2 params - 

1.  query : string containing the prompt of the chat
2. isPartialQuery : boolean stating whether accept chat input will run or will it wait for user to submit chat prompt

However if there is a registered chat participant variable lets say #docs then passing it as a string in the query param won't result into the chat detecting it as a variable command rather it will just see it as a simple string.

It would be great if there was a functionality which would automatically detect if there was a registered variable of chat participant in the query string.

**Comment by roblourens** [comment]
Yeah this is a weird API because I don't really want extensions referring to specific syntax like this but there is currently no alternative. I'd like to provide a way for you to pass an actual structured query rather than the special string.

**Comment by k-dot-11** [comment]
> Yeah this is a weird API because I don't really want extensions referring to specific syntax like this but there is currently no alternative. I'd like to provide a way for you to pass an actual structured query rather than the special string.

Is there anything in works for structured queries in the future versions
