### ISSUE TITLE
Can not install or uninstall extensions

### ISSUE THREAD

**Issue by preets7363** [microsoft/vscode#210827]
![Screenshot 2024-04-20 180227](https://github.com/microsoft/vscode/assets/77184609/72e76716-4155-457d-884a-67ef5b07e4c4)
Type: <b>Bug</b>

"Unable to write file
(NoPermissions (FileSystemError): Error: EPERM: operation not permitted"

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.78GB free)|
|Process Argv|--crash-reporter-id 3c0c5fd8-fa33-4dd4-b65f-a2721397c90c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-compile-run|dan|1.0.58
composer-php-vscode|DEV|1.44.14997
intelli-php-vscode|DEV|0.12.14619
phptools-vscode|DEV|1.44.14997
profiler-php-vscode|DEV|1.44.14997
vscode-html-css|ecm|2.0.9
prettier-vscode|esb|10.1.0
rainbow-csv|mec|3.11.0
debugpy|ms-|2024.0.0
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
cmake-tools|ms-|1.17.15
cpptools|ms-|1.19.3
cpptools-extension-pack|ms-|1.3.0
sqltools|mtx|0.28.1
sqltools-driver-mysql|mtx|0.6.0
LiveServer|rit|5.7.9
vscode-spotify|shy|3.2.1
cmake|twx|0.0.17
vscode-icons|vsc|12.7.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
showvideot:31016892
chatpanelc:31018788
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31022790

```

</details>

**Comment by sandy081** [comment]
Looks like user set up issue. Please make sure the directory writeable.
