### ISSUE TITLE
F2 doesn't always work

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21082]
testing  #20434

* have a couple of watch expression, like `4 + 8`, `console.log`, `ttt`
* navigate them with arrow keys
* press F2 on each to change them
* 🐛 it fails to show the rename/input box on the `console.log` item

![feb-22-2017 11-18-09](https://cloud.githubusercontent.com/assets/1794099/23207207/c684e32c-f8f0-11e6-8784-5b1cb7177878.gif)

**Comment by nuc134r** [comment]
Same on Windows so I suggest 'linux' tag is reduntant.

It seems like watch expressions which evaluate as non-simple type (functions, objects, arrays in JS) can't be renamed by F2 and doubleclick.
