### ISSUE TITLE
Caret sometimes randomly becomes white, making it invisible in light themes

### ISSUE THREAD

**Issue by arnavbhate** [microsoft/vscode#210826]
Type: <b>Bug</b>

The caret will sometimes become white after using Visual Studio Code for some time in the default light theme. I have noticed this issue since version 1.86.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 7730U with Radeon Graphics      (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|30.80GB (16.58GB free)|
|Process Argv|--disable-extensions --crash-reporter-id a578dc49-237d-48d4-8415-5fe86fbf5f0f|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30993540
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
chatpanelt:31018789
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31022790

```

</details>

**Comment by arnavbhate** [comment]
> Which carets are you referring to? Screenshots would be helpful here.

I am referring to the I shaped cursor. Like the one in this !(image)[https://upload.wikimedia.org/wikipedia/commons/4/45/I-beam_pointer.png]. Is caret the wrong word for it?

**Comment by lafe** [comment]
@arnavbhate This might be the same as #204181

**Comment by arnavbhate** [comment]
> @arnavbhate This might be the same as #204181

Yes
