### ISSUE TITLE
No rhyme or reason to list of git changes

### ISSUE THREAD

**Issue by mmiller-d8** [microsoft/vscode#210861]
Type: <b>Bug</b>

The list of git changes is largely random as far as I can tell.  Trying to find something in there is nearly impossible if you have any amount of changes at all.

Please, please, please either sort it alphabetically or give a way to filter to find a specific file.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:43:08.196Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (14 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|10, 7, 6|
|Memory (System)|96.00GB (2.40GB free)|
|Process Argv|--crash-reporter-id 1618046c-b005-4c1a-89ae-cb627902572c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.180.0
copilot-chat|Git|0.14.1
vscode-dbml|mat|0.3.5
vscode-docker|ms-|1.29.0
csdevkit|ms-|1.4.29
csharp|ms-|2.23.15
dotnet-maui|ms-|0.10.61
vscode-dotnet-runtime|ms-|2.0.3
vscodeintellicode-csharp|ms-|2.0.25
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.22.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.1
remote-containers|ms-|0.354.0
powershell|ms-|2024.2.1
oracledevtools|Ora|21.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
8082a590:30971561
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30993540
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31022790

```

</details>

**Comment by lszomoru** [comment]
Have you tried the find in trees capability mentioned [here](https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding)? Thanks!

**Comment by mmiller-d8** [comment]
Yeah... that works, but it is not intuitive at all.  I never would have guessed to do that.  I still say it would be way, way better to put them in alphabetical order.  Or to have an obvious and intuitive search box.  Shortcut keys should be a shortcut - they should never be the only way to do something.  @lszomoru

**Comment by lszomoru** [comment]
Changes are being sorted by their paths by default. You can control whether to see the changes as a list/tree or change the sorting order. All these options are available in the `...` menu.

![Image](https://github.com/microsoft/vscode/assets/3372902/ca467f34-9cf5-40b3-9258-5108c83055ee)

If these options do not meet your needs please feel free to reopen the issue. Thanks!

**Comment by mmiller-d8** [comment]
Still not intuitive.  Yes, that's great that it's available.  I appreciate that.  But my point stands that sorting it in a seemingly random order by default is not a good user experience. @lszomoru
