### ISSUE TITLE
Disable drag & drop affordance in read-only editors

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#21085]
Testing #21012

Linux

- open a read-only editor (default settings or left hand side git diff view)
- select some text and drag
- you see the 'drop cursor', but of course dropping will have no effect

**Comment by Mah3** [comment]
drag & drop for text feature not avilable in Windows platform...

**Comment by rebornix** [comment]
@Mah3 it can be turned on by setting `editor.enableDragAndDrop` as `true` but please note we are going to change its name.
