### ISSUE TITLE
Toggle full screen does not work while running VS Code out of sources

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#21088]
Testing #20327 

Steps to Reproduce:

1. Run VS Code from source
2. Toggle Full screen -> Does not work

Same with Zen mode -> Does not go to full screen

**Comment by bpasero** [comment]
I cannot reproduce and I also did not touch this in a while, so I suspect a ZEN issue.

**Comment by isidorn** [comment]
Why would zen mode be related to the full screen action which is completely unrelated. 
Though works for my out of sources -> closing as can not repro - and do not really want to investgiate on Sandeeps machine as it is only happening in out of sources

**Comment by bpasero** [comment]
@isidorn I was assuming that all UI related actions that are ZEN related (fullscreen is) go through one service that deals with being in ZEN mode or not and maybe there is a regression.

**Comment by isidorn** [comment]
@bpasero makes sense
@sandy081 let me know if you can also repro in insiders and I will investigate more

**Comment by sandy081** [comment]
@isidorn Not on insiders, only in dev version. I am build from scratch to make sure my setup is good and update
