### ISSUE TITLE
Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.88.1'.

### ISSUE THREAD

**Issue by nayohan** [microsoft/vscode#210912]
## Environment data

-   VS Code version: 1.88.1
-   Jupyter Extension version (available under the Extensions sidebar): v2024.3.1 and v2024.4.2024041702
-   Python Extension version (available under the Extensions sidebar): v2024.4.1
-   OS (Windows | Mac | Linux distro) and version: Windows | Mac both
-   Python and/or Anaconda version: python 3.11.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local(Mac) | Remote(Linux)

## Expected behaviour
<img width="452" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/18652811/5acbdfa9-96ca-450f-93bf-be4f4f90cc1c">

## Actual behaviour
succesfully install.

## Steps to reproduce:

if i drag "ms-toolsai.jupyter-2024.4.2024041702@win32-x64 (1).vsix" file into vscode extenstion tab -> error occured.
but by search install doesn't have any problem.
The problem is it can't use in offline mode.

## Logs

<details>
 sorry it' doesn't have any error log except small noti pop-up in vscode.
</details>

**Comment by DonJayamanne** [comment]
@sandy081 This is due to users downloading vsix from marketplace (which also lists preview versions) and then isntalling into stable VS Code.

**Comment by ACupofAir** [comment]
And this page https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter don't offer a version of v2024.3.1 which is stable for vscode 1.88.1

**Comment by mkbzas777** [comment]
same issue. The server is offline.That means i can't use this plugin by installing it manually because the website  don't offer a version of v2024.3.1. Please fix it .

**Comment by zzzzzec** [comment]
I have found a way to solve this problem，You can manually change the version requirement for VSCode in the VSCode extension.

- step1. download jupyter extension from marketplace（e.g ms-toolsai.jupyter-2024.4.2024042401@linux-x64.vsix）
- step2. replace '.vsix' to '.zip' and unzip this file 
- step3. you can find `package.json` at  `ms-toolsai.jupyter-2024.4.2024042202@linux-x64.zip\extension\package.json`, open this file and find `"engines":{"vscode":"^1.89.0"}`, replace version to your vscode version(e.g `"engines":{"vscode":"1.88.1"}`)
- step4. zip and rename replace '.zip' to '.vsix', then you may install this extesnion successfully .

This approach seems to manually bypass the version check of the VSCode extension for VSCode. Although I am not sure if it will cause any issues, so far there have been no problems on my machine.

**Comment by sandy081** [comment]
> if i drag "ms-toolsai.jupyter-2024.4.2024041702@win32-x64 (1).vsix" file into vscode extenstion tab -> error occured.

May I know why you are installing like this? It can cause errors like this as you cannot know that the VSIX is compatible with the VS Code or not from Marketplace web site.

Closing this as it is expected if you try to install an incompatible VSIX.
