### ISSUE TITLE
Toggling Zen mode flickers when running VS Code from Sources

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#21091]
Testing #20327 

Steps to Reproduce:

1. Run VS Code from sources
2. Toggle Zen Mode 

![kapture 2017-02-22 at 11 35 32](https://cloud.githubusercontent.com/assets/10746682/23207855/0f646d72-f8f3-11e6-9b89-0a6f05eaa1b7.gif)

**Comment by isidorn** [comment]
Can not repro. It is connected to your broken local electron which can not go full screen
