### ISSUE TITLE
Markdown Language Features Reports Error

### ISSUE THREAD

**Issue by bahadirarslan** [microsoft/vscode#210913]
I was using the Markdown Language Features extension without any problem but suddenly it started to report errors when I open a Markdown file.

I tried to restart VSCode, disable, and re-enable the extension but nothing changed.
Interestingly extension works normally but it generates errors and notifications.

```
[Error - 1:13:31 PM] Request textDocument/definition failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:32 PM] Request textDocument/codeAction failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:33 PM] Request textDocument/codeAction failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:33 PM] Request textDocument/foldingRange failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:33 PM] Request textDocument/documentSymbol failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:33 PM] Request textDocument/foldingRange failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:33 PM] Request textDocument/documentSymbol failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:34 PM] Request textDocument/codeAction failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:34 PM] Request textDocument/documentLink failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:35 PM] Request textDocument/definition failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:35 PM] Request textDocument/definition failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:35 PM] Request textDocument/definition failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:35 PM] Request textDocument/definition failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:35 PM] Request textDocument/definition failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:35 PM] Request textDocument/codeAction failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:36 PM] Request textDocument/definition failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:36 PM] Request textDocument/definition failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:36 PM] Request textDocument/definition failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:36 PM] Request textDocument/codeAction failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:36 PM] Request textDocument/foldingRange failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:37 PM] Request textDocument/documentSymbol failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:37 PM] Request textDocument/foldingRange failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:37 PM] Request textDocument/documentSymbol failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:37 PM] Request textDocument/codeAction failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:38 PM] Request textDocument/codeAction failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:38 PM] Request textDocument/foldingRange failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:38 PM] Request textDocument/documentSymbol failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:38 PM] Request textDocument/foldingRange failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:38 PM] Request textDocument/documentSymbol failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:38 PM] Request textDocument/foldingRange failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:38 PM] Request textDocument/documentSymbol failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
[Error - 1:13:39 PM] Request textDocument/documentLink failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 
```

- VS Code Version: 
Version: 1.88.1 (Universal)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:42:52.765Z (1 wk ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
- OS Version: macOS 14.4.1 (23E224)

**Comment by mjbvz** [comment]
Can you share a project which causes the issue? Possible either related to a file's name or contents

**Comment by bahadirarslan** [comment]
It is a docusaurus project, https://github.com/facebook/docusaurus

After upgrading from 2.0 to 3.2 my project started to generate these errors. At first glance, I thought there was a problem with docusaurus but then realized this is caused by extension.

Is there any way to debug and identify the underlying problem?

**Comment by mjbvz** [comment]
Can you share the project itself or a minimal project which demonstrates the problem?

**Comment by bahadirarslan** [comment]
I wish I could, but I can not share the whole project, however, I narrowed down the problem to this specific admonition of docusaurus.
When I paste this content to a new .md file it starts to generate errors, when I comment it out it stops.

```
:::info
If you add crew, this crew will be automatically added to **Flight Crew List**
:::
```

**Comment by glyad** [comment]
I have the same issue.  :(

**Comment by rsholmqvist** [comment]
This bug definitely appears to be related to "**".  when I do a global search/replace of "**" with "", this following issue goes away

Request textDocument/codeAction failed.
  Message: Request markdown/parse failed with message: Expected a code point, got `undefined`.
  Code: -32603 

I am not able to provide a doc for you to use, because my doc is proprietary and I have not found a simple case, yet

**Comment by rsholmqvist** [comment]
here is a simple example that causes the issue.
You MUST TYPE THIS into the window SLOWLY to see the issue

```
test1:
* test1b

**test2:**
* test2b
```

There are no issues with:
```
test1:
* test1b

**test2:**
```

As soon as you start to type `* test2b` on the line IMMEDIATELY following `**test2:**` the error pops up

![image](https://github.com/microsoft/vscode/assets/72753172/5327d8c7-2e3d-4f21-baea-35b167789980)

For small files, this is annoying.  For large files it seems to break the outline view and no headings can be seen.

Hope this helps!

**Comment by rsholmqvist** [comment]
here is another simple example that you must SLOWLY type into MMD file

```
* **test1**
* **test1b**

* **test2**
    * test2b
```

the following does not have any issues

```
* **test1**
* **test1b**

* **test2**
```

the error pops up as soon as you start to type `    * test2b`

**Comment by Salamandar** [comment]
Can confirm the issue too, linked to `**`.

**Comment by nubidebs** [comment]
I'm coming across the same issue with `**` 🙋‍♀️

**Comment by mjbvz** [comment]
Still doesn't happen for me

@rsholmqvist You specifically mention `MMD` which we don't support natively. Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by rsholmqvist** [comment]
@mjbvz 

Did you MANUALLY TYPE IT SLOWLY as described above?

This is my help:about
````
Version: 1.89.0 (user setup)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
````

Yes, I still get it with extensions disabled

![image](https://github.com/microsoft/vscode/assets/72753172/2e43fdd5-7be9-4384-afb1-163c31b2493e)



![image](https://github.com/microsoft/vscode/assets/72753172/fb8035ec-4b54-41b4-815c-ea84d13dd5a0)

**Comment by mjbvz** [comment]
@rsholmqvist YES :)

Did you restart VS Code after disabling all extensions? Some extensions will still have an effect until you restart

**Comment by rsholmqvist** [comment]
@mjbvz 

Disabling all extensions required a restart of VSCode to stop the error message.

When I click on the setting in the error message, I see
"Notice: This extension is **bundled with Visual Studio Code. It can be disabled but not uninstalled**"

![image](https://github.com/microsoft/vscode/assets/72753172/ac9d1465-89d6-4efc-b2ee-b0856be4d3e7)

**Comment by mjbvz** [comment]
Try to just disable third party extensions, not built ones. You can use  [these instructions](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Was it fixed when disabled third party extensions and restarted VS Code?

**Comment by rsholmqvist** [comment]
@mjbvz

Was it fixed when disabled third party extensions and restarted VS Code?
* yes!

**Comment by rsholmqvist** [comment]
@mjbvz 
I used Extension bisect to determine which extension is causing the issue
![image](https://github.com/microsoft/vscode/assets/72753172/e3b44aaa-6ed6-431b-b63c-567e740c0962)

**Comment by mjbvz** [comment]
Thanks for checking. Please file an issue against that extension so they can investigate
