### ISSUE TITLE
Extensions viewlet: home / end strange behavior

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#21098]
Refs: #20440 

1. Extensions viewlet, have the whole list of extensions with @sort:installs
2. Press `end` key - the very last elements gets focussed (there are like thousands)
3. Press up / down -> the bottom of the huge list gets revelaed
4. Press home -> the first element gets selected but does not get revelead

So there are two werid things here:
1. Home / end should reveal the element in the tree
2. End with an infinite list of items is weird and should be disabled

**Comment by bpasero** [comment]
> End with an infinite list of items is weird and should be disabled

Why? Works fine after my fix.

**Comment by isidorn** [comment]
Ok - it is just a bit weird that end takes me to a random location and there are still items beneath it. But I think it is fine in the end

**Comment by bpasero** [comment]
@isidorn hm, for me I get to the last element of the list. If that was not working, the scrollbar would also be wrong. But maybe there are cases where the list actually does not know how many elements there are. In that case I would need API from the list to actually continue to resolve until the end.

**Comment by isidorn** [comment]
@bpasero got it. Still not something we need to stress about imho

**Comment by aeschli** [comment]
Works for me on Linux. End brings me to the last element.
