### ISSUE TITLE
Local Workspace Extensions for .code-workspace files

### ISSUE THREAD

**Issue by joezimjs** [microsoft/vscode#210914]
Recent release notes mentioned Local Workspace Extensions in the Insiders release. It talked about placing the files for the extension in a .vscode/extensions folder, but what if you're using a .code-workspace file because of a multi-root project? Where would you place the extensions then? If this isn't currently a possibility, can it be added?

**Comment by sandy081** [comment]
You can have local workspace extensions in the `.vscode/extensions` folder of each root workspace folder in multi-root workspace. VS Code detects extensions from all these folders.
