### ISSUE TITLE
Double click on the single parenthesis to select all content including spaces,instead of just selecting the first content separated by blank space

### ISSUE THREAD

**Issue by apwep** [microsoft/vscode#210992]
Type: <b>Feature Request</b>

To select all contents within parentheses by double click on the single parenthesis or click on the position which is before or after the single parenthesis.  In addition to ( ),the same feature should also be applied to ' ' , " " , [ ] , { } etc 

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by gjsjohnmurray** [comment]
Same as #9123, which remains open and in Backlog but maybe overlooked.
