### ISSUE TITLE
Test: Git - new commands to view changes/staged changes/unstracked changes

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#210903]
Refs: https://github.com/microsoft/vscode/issues/209609

- [x] anyOS @eleanorjboyd
- [x] anyOS @aeschli

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23210903%0A%0A&assignees=lszomoru)

---

This milestone we have added new commands to open changes/staged changes/untracked changes using keybindings.

### Prerequisites
* Install the latest VS Code Insiders
* Set the `git.untrackedChanges` setting to `separate`

### Single-repository workspace
* Open a folder/workspace that contains a git repository
* Make a change to a file, and stage it
* Make a change to another file
* Add a new file to the repository
* Switch to the Source Control view
    * Confirm that the "Staged Changes" resource group has one file
    * Confirm that the "Changes" resource group has one file
    * Confirm that the "Untracked Changes" resource group has one file
* Use the command to invoke the "Git: View Staged Changes" command 
    * Confirm that the file in the "Staged Changes" resource group is opened in the multi-file diff editor 
* Use the command to invoke the "Git: View Changes" command 
    * Confirm that the file in the "Changes" resource group is opened in the multi-file diff editor 
* Use the command to invoke the "Git: View Untracked Changes" command 
    * Confirm that the file in the "Untracked Changes" resource group is opened in the multi-file diff editor 

### Multi-repository workspace
* Open a folder/workspace that contains multiple git repositories
* Make a change to a file from one of the git repositories (keep the file opened)
* Use the command to invoke the "Git: View Changes" command  
    * Confirm that the file in the "Changes" resource group is opened in the multi-file diff editor 
* Close all editors (file, multi-file diff editor)
* Use the command to invoke the "Git: View Changes" command  
    * Confirm that a quick pick is shown to pick a git repository
* Pick the repository that contains the changed file  
    * Confirm that the file in the "Changes" resource group is opened in the multi-file diff editor 

### Keybindings
* Open a folder/workspace that contains a git repository
* Setup keybindings for the following commands:
    * `git.viewChanges`
    * `git.viewStagedChanges`
    * `git.viewUntrackedChanges`
* Make a change to a file, and stage it
* Make a change to another file
* Add a new file to the repository
* Invoke the 3 commands using the keybindings
    * Confirm that the correct files are opened in the multi-diff editor

**Comment by aeschli** [comment]
@lszomoru  In 'Multi-repository workspace'`, on `Git: View Changes`,  I always get the quick pick to pick a git repository, regardless if an editor is open or not. Is that as expected?

**Comment by eleanorjboyd** [comment]
> @lszomoru In 'Multi-repository workspace'`, on `Git: View Changes`, I always get the quick pick to pick a git repository, regardless if an editor is open or not. Is that as expected?

I saw this as well
