### ISSUE TITLE
Allow file modification commands when focus is in opened editors view

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21090]
testing #20438

> filesExplorer.copy: copy a file from the files explorer
filesExplorer.paste: paste a file that was copied from the files explorer
filesExplorer.rename: rename a file/folder in files explorer
filesExplorer.moveFileToTrash: move a file/folder to trash from files explorer
filesExplorer.deleteFile: bypass trash and delete a file/folder from files explorer

I don't see a technical justification for above commands not to function for resources on disk that are showing in the open files section? It seems we are now building commands with very explicit names (`filesExplorer`) whereas a later bug fix/feature request could expand them to just work everywhere

**Comment by bpasero** [comment]
@jrieken these are just the commands that show up in the context menu as well and so far we have stayed away from allowing file modification operations from the "opened editors" section. If we allow these commands to work in the opened editors section, they should also show up in the context menu imho.

**Comment by dbkaplun** [comment]
Thanks for reporting this! I would like to be able to delete or rename a file via the command palette.

Is there some recommend method or shortcut to renaming/deleting a file via keyboard? Or is this a mouse-only feature?
