### ISSUE TITLE
Search viewlet end key takes me to last file name, not last result

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#21096]
Refs: #20440

1. Search viewlet, have some results
2. Focus on tree - press end key
3. The last file is focussed, not the last result
4. This is not aligned with the explorer where we always focus the last file, not the last folder

Note: this behavior is also present in the problems view.

**Comment by bpasero** [comment]
Wow, weird.

**Comment by isidorn** [comment]
Not that this is present in most trees (also debug hover)

**Comment by bpasero** [comment]
Actually also reproducible in the explorer once you have the last element be a folder.

**Comment by bpasero** [comment]
@joaomoreno I think the method focusLast is not doing what it is supposed to do:

> Focuses the last element, in visible order.

It only seems to focus the last element that is on the same hierarchy but not below.
