### ISSUE TITLE
Test: Configure Keybinding for Actions in Workbench Toolbars

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#210932]
Refs: #208221

- [x] anyOS @digitarald
- [x] anyOS @hediet

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23210932%0A%0A&assignees=benibenj)

---

In this iteration, we simplified the process of adding keyboard shortcuts to action items by introducing a `Configure Keybinding` option in the context menu of workbench toolbars.

1. Right click on a action in a toolbar which already has a keybinding (By hovering over the action you'll see the keybinding if there is any)
2. A context menu should open with the action `Configure Keybinding` at the top. Press it
3. The command should be revealed in the keybinding editor. If the action has a keybinding, it should show the keybinding in the entry
4. Change the keybinding
5. Go back to the action in the toolbar. It should now show the new keybinding when hovering over the action.
6. Repeat from step 1. with an action which **does not** have a keybinding. If the action has a `when` clause specified, it will be set in the keybindings editor

https://github.com/microsoft/vscode/assets/44439583/b5b1cd95-98c0-44db-9825-339b914e6cab

**Comment by hediet** [comment]
I love this feature!

It does not work for these commands though because of context key issues:
![Code_-_Insiders_rZrF7cW3nQ](https://github.com/microsoft/vscode/assets/2931520/1a21d10f-a6e5-4168-aefc-ceb0c6a67357)

This is probably a bug in the existing key-binding.

**Comment by digitarald** [comment]
Worked great.

Wish it would work in the Activity Bar as well.
