### ISSUE TITLE
User settings.json in *serve-web* (security.workspace.trust.enabled)

### ISSUE THREAD

**Issue by ab077u** [microsoft/vscode#210965]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.88.1
- OS Version:  Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15

Steps to Reproduce:

1. Create user settings.json to overwrite workspace trust setting in `/Users/ab077u/.config/Code/settings.json`.
  ```json
  {
      "security.workspace.trust.enabled": false
  }
  ```
2. Start the vscode web using  the following command -
```bash
code serve-web  --port 8884 --host 0.0.0.0 --without-connection-token --log trace  --user-data-dir ~/.config/Code  --telemetry-level off 
```
3. Attempt to open a folder using "File" > "Open Folder ..."
4. Notice that the above setting has no affect. 

However opening the settings page and `@tag:workspaceTrust` updating the settings in the UI disables the trust.

<img width="1580" alt="image" src="https://github.com/microsoft/vscode/assets/31135452/060ff3ae-3897-45b5-adef-efb419b1fc8b">

I have tried various locations to overwrite the user settings in the context of serve-web. They seem to have no effect.

Is user settings overwrite (through a settings.json) supported when using _serve-web_ and if could you please provide some direction on the designated file location.

**Comment by ab077u** [comment]
Reference: https://code.visualstudio.com/docs/getstarted/settings

**Comment by lszomoru** [comment]
@connor4312, do you mind taking an initial look at this one? Thanks!

**Comment by connor4312** [comment]
Wonder if it's related to https://github.com/microsoft/vscode-dev/issues/1092

**Comment by mkillow** [comment]
I am also seeing this same issue, settings.json in the folder specified by "--user-data-dir " is not being respected for serve-web.

**Comment by sbatten** [comment]
@connor4312 I think that's a separate issue.

In this issue, the settings.json on the user's machine seems to be separate from the settings.json shown after opening code in the browser. I was able to set workspace trust to disabled from the browser, reload and then workspace trust is disabled. If I open the settings json file, it is the only setting in the file even though my local vscode has many settings.

**Comment by mkillow** [comment]
Question - If this is by design does that mean there is no way to override or provide a default settings.json when running "code serve-web" ?  What is the intended purpose of the "--user-data-dir" parameter in this case?
