### ISSUE TITLE
Test Updated copy paste / drop proposals

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#210985]
Test for #179430

- [x] Mac @aiday-mar
- [x] Linux @rzhao271
- [x] Windows @bhavyaus

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23210985%0A%0A&assignees=mjbvz)

---

# Summary
This test plan item involves two very similar API proposals:

- Document paste. This allows extensions to attach metadata when copying text in an editor and change how text is inserted on paste

- Document drop. This allows the same but for drag and drop

Both api proposals are in `src/vscode-dts/vscode.proposed.documentPaste.d.ts`

# Testing
Using the two extension samples (https://github.com/microsoft/vscode-extension-samples/tree/main/document-paste and https://github.com/microsoft/vscode-extension-samples/tree/main/drop-on-document) as starting points, try out the new APIs

Specific areas to focus on:

- Does the documentation in `vscode.d.ts` make sense

- In a paste editor provider, you see attach metadata using `prepareDocumentPaste` and retrieve it in `prepareDocumentPaste`

- The UX makes sense. Try checking what happens if multiple potential edits are returned on paste or drop

- Edits can de-prioritize themselves using `yieldTo`. For example, you can `yieldTo` the default `text.plain` kind if you want normal text pasting to kick in first while still showing your edit as an option 

 

# Known limitations
- These apis do not handle all multi cursor cases themselves. Specifically we don't handle what happens when you copy from multiple locations and paste into the same number of locations. This is instead left up to extensions as we could not figure out how to express this well in the api 

- Any metadata you add on copy will only be visible in the current VS Code editor window

**Comment by rzhao271** [comment]
Remark: I noticed that I could set `additionalEdit` to be a new `vscode.WorkspaceEdit` object, and then call `pasteEdit.additionalEdit.createFile`, causing the paste edit to create a new file.
I'm wondering if this is intended behaviour of the API for more advanced edits?

**Comment by mjbvz** [comment]
@rzhao271 Yes, markdown uses this for example to create an image in the explorer when you paste image data into a md file
