### ISSUE TITLE
Test: large notebook file performance

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#210949]
Refs: https://github.com/microsoft/vscode-jupyter/issues/14459

- [x] macOS @DonJayamanne
- [x] linux @ulugbekna
- [x] windows @digitarald

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23210949%0A%0A&assignees=amunger)

---

### Pre-requisites - If you **don't** have python set up to run notebooks

1. ensure python is installed on your machine
2. open a workspace where you will be running tests for this TPI
3. `Create: new jupyter notebook` and run `print(1)` in a cell. 
  a. If the cell runs successfully, you're already set up, otherwise...
4. The kernel picker should open, select "Python Environments..." -> "Create Python Environment..." -> select venv or conda, and whichever version you'd like.

A virtual environment should get created in your workspace with all necessary packages installed, and the cell should run successfully.

5. run `%pip install plotly.express` to be able to run the example cell in this TPI

### Test Steps

1. Set `"notebook.experimental.remoteSave": true`
2. create a notebook with a large amount of output data, this can be done by running the following code and then copy/pasting that cell to create around ~60 cells which should create an .ipynb file that is around 200MB

```
import plotly.express as px
import random
x = []
y = []
for i in range(100000):
    random_number = random.randint(1, 10000)
    x.append(i + random_number)
    y.append(i + random_number)
fig = px.scatter(x, y)

fig.show()
```

3. Make an edit to make the notebook dirty
4. interact with the notebook without making further edits so that a backup or auto-save is triggered (scrolling, move the cursor around)
5. ensure that the renderer does not lock up for a noticeable amount of time
6. toggle auto-save and repeat steps 3-5
7. Manually trigger a save and ensure no renderer lock-up

**Comment by digitarald** [comment]
Did help me with my survey analysis; which analyzes 200kk survey responses.
