### ISSUE TITLE
Test Markdown link updates on paste

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#210945]
Test for #209318

- [x] Mac @daviddossett
- [x] Linux @connor4312
- [x] Windows @benibenj

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23210945%0A%0A&assignees=mjbvz)

---

# Summary
The new `markdown.experimental.updateLinksOnPaste` setting allows VS Code to automatically update any relative links in text that is copy and pasted between markdown files in the current window. For example, if you copy this text from `./readme.md`:

```md
![alt](img.png)
```

If you paste it into `./sub/other.md`, the text will automatically be rewritten to:

```md
![alt](../img.png)
```

This feature works for:

```md
Relative links and images:

[text](file.md)
[text](/file.md)
[text](../file.md)
[text](file)  No extension used but resolves to `file.md`

---

Links in `src` html elements:

<video src="file.mp4"></video>
<a href="file.md">...</a>

---

Fragment links:

[text](#header-in-current-file)
[text](other.#header-in-other-file)


---

Reference links:

[Some text][def] <-- Copy this and the definition below should get added to the new file on paste

[def]: http://example..com
```

# Testing

- Set `"markdown.experimental.updateLinksOnPaste": true`

- Try copying text that includes some of the link formats above

- Make sure the links are correctly updated on paste

- Try testing other variations or combinations

- Make sure you can use the paste widget to switch back to a normal paste if you want instead

# Known limitations

- This only works for when copy and pasting within editors in the same window. It does not work across VS Code windows or from another app into VS Code

- We currently support multicursor paste but not multi-cursor copy. This means the first cursor's content is always used on paste

**Comment by daviddossett** [comment]
Works great 👍
