### ISSUE TITLE
Test:  Improve automatic theme switching behavior

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#210929]
Refs: https://github.com/microsoft/vscode/issues/158314

- [x] MacOS @sbatten
- [x] Win @hediet
- [x] Linux @connor4312

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23210929%0A%0A&assignees=aeschli)

---

Since a long time we have the setting `window.autoDetectColorScheme` that allows to select a theme based on the OS System Theme.
The work this milestone tries to simplify the experience and make it mode detectable and reliable without breaking existing settings.

Now:

As before, when `window.autoDetectColorScheme` is not enabled, we use the theme configured at `workbench.colorTheme`.
New: when `window.autoDetectColorScheme` is enabled, we ignore  `workbench.colorTheme` and directly use the themes configured at `workbench.preferredDarkColorTheme` resp. `workbench.preferredLightColorTheme`, based on the current OS system theme. `workbench.colorTheme` is ignored, and also not modified if the OS changes the theme or the user changes one of the preferred themes.
The `Preferences: Select Color Theme` picker now directly show (and configures) the currently active theme setting:
- when `window.autoDetectColorScheme` is not enabled, it configures  `workbench.colorTheme`.
- when `window.autoDetectColorScheme` is enabled and we are in a Dark OS, it configures  `workbench.autoDetectColorScheme`.
- when `window.autoDetectColorScheme` is enabled and we are in a Light OS, it configures  `workbench.preferredLightColorTheme`.
- The picker shows what it configure in the placeholder, and it contains a config button to bring you to the settings,

Caveat: We have a setting `window.systemColorTheme` that allows to hardcode the systemColorTheme. In that case theme switching is disabled (even if  `window.autoDetectColorScheme` is checked). We are restricted by Electron here.

Test:
- disable `window.autoDetectColorScheme` and open the theme picker with `Preferences: Color Theme`. Observe that the placeholder mentions that this theme is for all OS System Themes and has a configuration button that brings your to the setting to enabled it.
- enable `window.autoDetectColorScheme` and open the theme picker with `Preferences: Color Theme`. Observe that the placeholder mentions that this theme is for either the Light or Dark OS System Theme theme (matching the OS theme)
- Switch the the OS theme and verify that the theme is switched
- Open the theme picker again (`Preferences: Color Theme`) and verify that the placeholder message reflects the new setting
- Try the Configure button at the end of the Text input box and verify that it brings you to the settings that matter
- Verify the wording of the configuration settings and verify that all config settings descriptions consistent by using `OS System Theme`
- The setting  `window.systemColorTheme` allows you to hardcode the systemColorTheme. Using it will disable the OS system theme detection. Ths setting is only available on Windows and Mac. Verify that the working of the setting makes it clear that this impacts `window.autoDetectColorScheme`. Test that setting it ignores ``window.autoDetectColorScheme``.  `Preferences: Color Theme` now again uses `workbench.colorTheme`.

**Comment by connor4312** [comment]
`window.systemColorTheme` on Linux still seemed to work when added to the settings.json manually, it just didn't show as a valid/documented setting. Not sure if that's intended or not.

**Comment by aeschli** [comment]
> window.systemColorTheme on Linux still seemed to work when added to the settings.json manually, 
Thanks, I fixed that with https://github.com/microsoft/vscode/pull/211265
