### ISSUE TITLE
Test: Executing large notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#210963]
Refs: #209787

- [x] anyOS @sandy081
- [x] anyOS @cwebster-99
- [x] anyOS @roblourens

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23210963%0A%0A&assignees=DonJayamanne)

---

### Pre-requisites 
1. Install the attached VSIX (this is a simple extension that allows extension of notebook cells)
    * It s a dummy extension as all this does is adds some simple outputs to each cell
    * Nothing fancy (pure js, no Python dependencies or the like)
[vscode-notebook-dummy-execution-0.0.1.vsix.zip](https://github.com/microsoft/vscode/files/15068563/vscode-notebook-dummy-execution-0.0.1.vsix.zip)
2. Create a large notebook with at least 500 code cells & 200 markdown cells  (the more cells you have the better)
    * Code cells could contain could be `print("Hello World")`
    * Markdown cells needs to be more complex such as 
    ```markdown
    # Header 1
    ## Header 2
    ### Header 3
    ```
    * Tip:You can create one code cell and one markdown cell, then copy them and paste them a few times.
    * Then copy all cells and copy & paste them
3. Ensure notebook outline is visible
4. Enable the setting `Notebook: Show Code Cells Symbols`
5. Enable `Notebook: Sticky Scroll`

### Test Steps

1. Open the notebook
2. Select the Kernel `Dummy Execution`
3. Select the command `Dummy Execution: Run all (text output)`
4. [ ] Verify the cells run within a few seconds (should be less than 5s)
5. Tip: You can open the output panel `Dummy Execution` to see some of the times.
The entry in the log `Time spent in users perspective: n` should be low.
In stable this would be around 10-30 seconds or more, depending on the size of the notebook (cell count).
Note: the durations displayed in the output panel is in `milliseconds`
7. [ ] Now run the same steps against VS Code stable and verify its very slow.
It should be significantly slower than VS Code insiders.
E.g. if insiders completes in 3s, then stable will take around 30s.

**Comment by roblourens** [comment]
I see this take what seems like a very long time

```
Cells executed 952
Output type text
Time spent in VS Code before extension is notified: 11835
Time spent in Extension Host running all cells: 6498
Time spent in VS Code updating UI after exection completed: 104410
Time spent in users perspective: 122744
```
