### ISSUE TITLE
Cannot read property 'init' of undefined when initializing git repo on an empty folder

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#21095]
Testing #20999 (On Windows)

- Open VS Code on an empty folder (Also happening on non-empty folders)
- Go to SCM view
- Intiailize Git Repo

See following error

![image](https://cloud.githubusercontent.com/assets/10746682/23208303/c82446b0-f8f4-11e6-8873-88d1abd2cb1d.png)

**Comment by joaomoreno** [comment]
Great catch!
