### ISSUE TITLE
Clicking on file in scm viewlet automatically focuses that file

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#21094]
Refs: #20440

1. SCM viewlet, have some changes
2. Click on any file in the scm viewlet
3. Focus is immediatly transfered to the editor
4. I would expect the SCM viewlet to behave like all out other viewlets (explorer, debug) - ony click preserves the focus in the viewlet. Only double click transfers focus. This way it is imposible to focus an item in the tree and then use keyboard for further navigation

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/20909
