### ISSUE TITLE
Returning back some files

### ISSUE THREAD

**Issue by Wiam012007** [microsoft/vscode#210982]
Type: <b>Feature Request</b>

I have delete it my coding work accidentlly, and I saved these files on my pc when they were empty, I work hard for these files and I want them back

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by lramos15** [comment]
You can try `F1` -> `Local History: Find Entry To Restore` is your best bet. Otherwise you're out of luck.

I also recommend enabling autosave.
