### ISSUE TITLE
Strange rendering of inline key bindings in accessibility help

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#211061]
Testing #210668

Code vscode-extension-samples\tree-view-sampleree

```
				{
					"id": "ftpExplorer",
					"name": "FTP Explorer",
					"accessibilityHelpContent": "This is a custom view <keybinding:ftpExplorer.refresh> to explore ftp servers "
				}
```

![Image](https://github.com/microsoft/vscode/assets/1931590/5106a394-29e3-4337-b727-8e8a373745e7)

IMO this should not be rendered that way. 

```
[Configure a keybinding](command:workbench.action.openGlobalKeybindings?%22ftpExplorer.refresh%22)
```

**Comment by rzhao271** [comment]
More examples

![Accessibility help contribution with two keybindings and some text in between them and before and after them](https://github.com/microsoft/vscode/assets/7199958/87fabfdd-1920-44d0-a62a-3dcab83cfd75)
![When the extension is run, the first keybinding is mangled with the second one and the text in between](https://github.com/microsoft/vscode/assets/7199958/59a467f0-b0d0-42f4-98bc-cfed4136f82b)

**Comment by meganrogge** [comment]
yeah, it's not ideal. 

/duplicate https://github.com/microsoft/vscode/issues/210665
