### ISSUE TITLE
Widget doesn't show if there are no suggestions

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#211077]
Testing #210394

Pressing <kbd>Ctrl Space</kbd> in the editor when there are no suggestions available, the suggest widget still comes up:

<img width="345" alt="image" src="https://github.com/microsoft/vscode/assets/22350/07d1346c-c39f-448a-880a-6f429e332bf9">

It simply doesn't come up at all in the terminal and my perception is that something is broken.

**Comment by meganrogge** [comment]
wip `merogge/wip-status-message`
