### ISSUE TITLE
No suggestions on empty input

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#211076]
Testing #210394

Maybe out of your scope, but I get no suggestions when pressing <kdb>Ctrl Space</kbd> when I have typed nothing in PowerShell. I need to type a single character to get suggestions. It would be very cool if it would just work, like in the editor.

**Comment by Tyriar** [comment]
I agree, unfortunately the API that we use to get the completions doesn't allow an empty string 😢

I'll see what can be done here

**Comment by Tyriar** [comment]
Looks like this gives us what we want:

```ps1
[System.Management.Automation.CompletionCompleters]::CompleteCommand('')
```
