### ISSUE TITLE
SCM view is not helpful when there is no SCM repo

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#21103]
Testing #20999 

- OS Version: Windows

Steps to Reproduce:

1. Open VS Code on a folder which does not have SCM repo initialized
2. Open SCM view
- It is not helpful to figure out that you can initialise the repo from there. 
- Top right icon looks like a Git label rather than an action button
- Commit box and changes take much precedence and misleading
- It would be useful if we can make Initialise action much prominent (like in old git)

![image](https://cloud.githubusercontent.com/assets/10746682/23208744/785c01a2-f8f6-11e6-854c-e5b53b402dfe.png)

**Comment by joaomoreno** [comment]
How about if we put the Git Init action in the ... menu?

**Comment by sandy081** [comment]
Probably a different icon to initialise might help. To me, even though I am used to the view with actions on the right.. First impression I got was "Ok, now we are mentioning that, this is a Git SCM using the icon there", But not to initialise. After hovering over it I got to know it is to initialise. But this is my impression. May be others get to it straight.

Is not it possible to show a disable mode for the commit box and not show any changes? Or

How about following flow:

- Show everything under changes
- When user tries to commit, initialise the repo and ask for more custom options ?

**Comment by Tyriar** [comment]
A button like in the explorer to initialize a repo might be good too, that way it would be a more explicit action since it's creating a `.git/` directory:

![image](https://cloud.githubusercontent.com/assets/2193314/23225953/b59dcdec-f8e8-11e6-9144-1bb36002173b.png)

**Comment by joaomoreno** [comment]
Pushing this out to April.

**Comment by joaomoreno** [comment]
Improved a bit:

![image](https://cloud.githubusercontent.com/assets/22350/25476960/24755ac0-2b3c-11e7-954c-30e1f1d2c2a2.png)

There are more ideas coming up.

**Comment by michelkaporin** [comment]
I like the proposal by @Tyriar. 

Also the current 'Initialize Repository' button does not look like a button, rather as a non-clickable text, until you hover over it.
As for now, it's enough, putting verified.
