### ISSUE TITLE
Extracting local variables and refactoring results in inconsistent code behavior before and after refactoring

### ISSUE THREAD

**Issue by DongChunHao** [microsoft/vscode#211010]
Does this issue occur when all extensions are disabled?: Yes/No

VS Code Version: 1.88.1
OS Version: Windows11
-Language：java
Steps to Reproduce:

select "20"
click “Refacator-Extract local variable”
new variable name " existingVariable"

Steps to Reproduce:

1.  select "1"
2. click “Refacator-Extract local variable”
3.  new variable name " y"

class A {
    int y=2;
    int main() {
      // extract variable:1, rename y
        int x = 1; 
        System.out.println(y);
        return 0;
    }
}

refactoring result：
![image](https://github.com/microsoft/vscode/assets/77560508/7d79f35a-6571-4213-8cd7-56f528c618c2)

Reason: When extracting local variables, the masking problem between new variable names and context was not detected

Expected behavior: Check for naming conflicts and masking issues before and after refactoring, and provide warning prompts

**Comment by mjbvz** [comment]
Please move all of the refactoring issues you filed to Java extension's issue tracker
