### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#211052]
Testing #210985

I cloned the vscode-extension-samples repository and tried to return two edits instead of one. Only the first one appears to take effect. I am wondering if this is expected? I guess I was expecting both edits to be applied since it is possible to return an array from the `provideDocumentPasteEdits` method.

https://github.com/microsoft/vscode/assets/61460952/a8b18fab-25cc-47d3-a5e6-b3ab660dfb26

**Comment by aiday-mar** [comment]
Aside from the above comment, on reading the JS Docs, the following thoughts came to mind:

- For the class `DocumentDropOrPasteEditKind`, I was looking at the method `intersects`. Consider the following code:

```
kind1 = vscode.DocumentDropOrPasteEditKind.Empty.append('pasteEdit');
kind2 = vscode.DocumentDropOrPasteEditKind.Empty.append('pasteE');
```

Do the kinds `kind1` and `kind2` intersect here? Or is the intersection evaluated per part, so that the above do not intersect but the below kinds do?

```
kind1 = vscode.DocumentDropOrPasteEditKind.Empty.append('pasteEdit');
kind2 = vscode.DocumentDropOrPasteEditKind.Empty.append('pasteEdit', '2');
```

- I noticed the `DocumentPasteProviderMetadata` refers to file dropping in its JS Doc. I was wondering if this is intended? The JS Doc above the `readonly pasteMimeTypes` field says `Note that {@linkcode DataTransferFile} entries are only created when dropping content from outside the editor`. The same line more-or-less can be found under `DocumentDropEditProviderMetadata`.

**Comment by mjbvz** [comment]
This is expected. Each `PasteEdit` is one potential way of applying the paste. We only apply one at a time and the first one is auto applied 

1. For `DocumentDropOrPasteEditKind`, the kinds are scoped hierarchies of parts. When we talk about intersection, only the second example would return true. The first one would not as the two top level parts `pasteEdit` and `pasteE` are not the same. I'll add an example  in the docs to make this more clear

2. yes it applies but for pasting files. I'll change the word
