### ISSUE TITLE
Accessibly help content not working for standalone views

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#211054]
Testing #210668

- `vscode-extension-samples\tree-view-sample`
- enabled accessibly help content in proposed API
- add the following string here:
```
			"package-explorer": [
				{
					"id": "nodeDependencies",
					"name": "Node Dependencies",
					"icon": "media/dep.svg",
					"contextualTitle": "Package Explorer",
					"accessibilityHelpContent": "This is a custom view to explore node dependencies"
				}
```

- Run the extension
- Bring the package explorer to front
- Press Alt+f1

Observe: no help view is presented.

**Comment by paulacamargo25** [comment]
I've been trying with my extension, and also with the sample-tree but I can't get it to work either.

**Comment by rzhao271** [comment]
I saw the help view after focusing into the view and pressing Alt+F1. When focusing on the view on the default dark theme, I see a large blue outline around the view. If I click on the title on the view, the outline goes away, and pressing Alt+F1 does not show the help content.

**Comment by meganrogge** [comment]
> Bring the package explorer to front

You have to explicitly focus the view with the command to do so / via keyboard. Did you do so?

**Comment by meganrogge** [comment]
A screenshot of your setup would help. also, it would help if you could run the command to inspect context keys when you focus that view and provide me with that output.

**Comment by dbaeumer** [comment]
After focusing the view things worked for me. Pressing the view button in the action bar seems to not focus the view.
