### ISSUE TITLE
Aux window monitor not restored when maximized

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#211072]
Testing https://github.com/microsoft/vscode/issues/210686 on Linux

I have 2 monitors: primary and secondary. 
```
 ------------   ------------
| primary    | | secondary  |
 ------------   ------------
```

I opened VS Code and maximized it on my secondary monitor.
Then I dragged an aux window out and maximized it on my primary monitor.

```
 ------------   ------------
| aux        | | main       |
 ------------   ------------
```

After closing and reopening VS Code, the maximized state of both my main window and my aux window were restored, but both were on my secondary monitor. The aux window was on top.

```
 ------------   ------------
|            | | main & aux |
 ------------   ------------
```

I'm using Remote Desktop + Hyper V, so maybe something is going on there:
Remote Desktop from Windows to another Windows machine. Hyper V to an Ubuntu VM.

**Comment by alexr00** [comment]
Looks like which monitor is primary and which is secondary doesn't seem to matter as the same thing happens when swap the windows that aux and main are on.

**Comment by bamurtaugh** [comment]
I also experienced a variant of this:

- Main VS Code window maximized in primary monitor, 1 aux window maximized in primary monitor, 1 aux window maximized in secondary monitor
- Close VS Code
- Reopen VS Code
- All 3 windows (main and aux) are restored to max, but they're all restored to my primary monitor

I'm testing on Windows 11 Insiders.
