### ISSUE TITLE
Too many changes warning is too persistent and in the wrong place

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#211096]
![image](https://github.com/microsoft/vscode/assets/38270282/1937fcd2-405a-42d8-a9c5-8e2cb235e3c0)

I checked-out an old commit from 7 years ago (a8c629dd0fd99c1eedfc804266ca18942cfada5c). The SCM view got stuck displaying the "busy" badge and showed many file changes, along with a warning about too many changes. 

When I changed views, the warning stuck around even on top of other view containers. Eventually, it moved into the top right corner. The SCM view now appears to be permanently busy.

**Comment by lszomoru** [comment]
That does not look good. I am also able to reproduce in Stable so I believe that this was broken last milestone. 
It's very easy to reproduce by setting `git.statusLimit` to `3` and then making changes to 4 files.

**Comment by lszomoru** [comment]
Adding @benibenj and @TylerLeonhardt to see if this rings a bell for them as the made changes to `IContextViewService` recently. Based on my tests, this worked fine in `1.87` but it's broken with `1.88`. I stepped through the SCM code and it seems that no changes in execution there.

**Comment by TylerLeonhardt** [comment]
I didn't do any crazy changes there AFAIK, I feel like @benibenj was maybe more in there so could you take a look first?

**Comment by benibenj** [comment]
Found the culprit #207520. Fix it with #211219

**Comment by benibenj** [comment]
It turns out the fix actually breaks hovers entirely. @TylerLeonhardt you turned the disposable into a `MutableDisposable` which I believe does not work in this context. I think we should revert https://github.com/microsoft/vscode/pull/207520/commits/09d9b060a3eff4a3db0a19533ba8dfb01846a51c.

**Comment by TylerLeonhardt** [comment]
@benibenj I can drive reverting that commit but think this should be revisited in debt week as we have disposables there not getting disposed of.

**Comment by lszomoru** [comment]
Thank you @benibenj and @TylerLeonhardt.

**Comment by benibenj** [comment]
@TylerLeonhardt I had a closer look at the code. The concept of using disposables for this case was flawed from the start. I created a fix for it.
