### ISSUE TITLE
Terminal shows both ghost suggestions as well as suggestion widget

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#211080]
Testing #210394

I find it confusing to know what happens in this case if I press <kbd>Tab</kbd>:

<img width="937" alt="image" src="https://github.com/microsoft/vscode/assets/22350/57466987-702b-4209-97c9-af8ae6c867d3">

**Comment by Tyriar** [comment]
The ghost text here is a pwsh feature so I'm hesitant to mess with that. We do a decent job now of detecting when ghost text is present so I could try sync it and score the ghost text match the highest?

**Comment by Tyriar** [comment]
This is similar to how it works with ghost text and intellisense. The editor does have smarts for hiding the ghost text when it doesn't match the intellisense option, but unfortunately we don't have that sort of control in the terminal as history-based ghost text is entirely controlled by powershell itself. With deeper integration maybe this is possible, but closing as out of scope for now.
