### ISSUE TITLE
Not being able to create a file

### ISSUE THREAD

**Issue by divya453** [microsoft/vscode#211051]
Type: <b>Performance Issue</b>

i have been trying continously to create a file name index.html but error keeps showing up saying operation not permitted.  also its difficult find an option of permission 

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 5300U with Radeon Graphics          (8 x 2595)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.33GB (2.24GB free)|
|Process Argv|--crash-reporter-id 652e31d2-4f8d-4638-832f-3b2dd6ce6987|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   104	 21036	code main
    0	    84	  2652	fileWatcher [1]
    1	    91	  7828	window [2] (Issue Reporter)
    0	    97	 20500	shared-process
    0	   182	 20696	window [1] (HTML TUTORIAL - Visual Studio Code)
    0	    31	 21152	   crashpad-handler
    0	   108	 21176	extensionHost [1]
    0	   133	 21412	   gpu-process
    0	    43	 21420	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (HTML TUTORIAL - Visual Studio Code)
|    Folder (HTML TUTORIAL): 0 files
|      File types:
|      Conf files:;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
chatpanelc:31018788
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31022790

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by an extension.

**Comment by divya453** [comment]
> Please use the Start Extension Bisect command to investigate whether the problem is being caused by an extension.
yes, just did it and it is caused by the ritwick live server extension i installed . What should i do in this case ?
