### ISSUE TITLE
`Git: View staged changes` is a no-op if there are no staged changes

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#211098]
Testing #210903

When running `Git: View staged changes` when there are no staged changes doesn't do anything. That's a but confusing.

E.g. in the case of multi-folder workspace, I first get prompted for the repo, I select an entry, but then nothing happens

It could show a notification, but IMO it would be better to show the empty multi-editor.
An empty multi-editor is already shown when you stage all entries in it

**Comment by eleanorjboyd** [comment]
I also agree it would be better to show a empty multi-editor

this happened to me when I binding different keys to these command and I kept getting confused that I wasn't using the right keyboard shortcuts because nothing would happen when I did them.

**Comment by lszomoru** [comment]
Decided to go with notifications as that is consistent with the other commands contributed by the git extension.
