### ISSUE TITLE
Explorer commands are overly specific

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21102]
testing #20438

There is a conceptual problem with the newly introduced commands. They are very specific to the explorer even though what they do isn't. For instance, `explorer.copyPath` is artificially limited to work only when the explorer has focus. Instead it should also work when invoked from within an editor. In fact, the context menus for the explorer and editor title both contain this command. To configure a single keybinding that copies the path of either the explorer-selection or the current file, I now need two configurations and two separate commands which is illogical and bloat. The same is true for almost all other commands, like open to side, find in folder (of currently active editor), delete file, etc

To stay in the sample, I would suggestion to just have `copyPath` instead of `explorer.copyPath` and in the future `editor.copyPath` because it eases configuration and is logical.

**Comment by bpasero** [comment]
Candidates:
* `explorer.copyPath` and `workbench.action.files.copyPathOfActiveFile`
* `explorer.revealInOS` and `workbench.action.files.revealActiveFileInWindows`

We never allowed other commands in the context of the active editor for the rest (e.g. delete/rename) but at least for delete there is https://github.com/Microsoft/vscode/issues/4366.

**Comment by jrieken** [comment]
> We never allowed other commands in the context of the active editor for the rest

Yeah, but if we will it might become messy with same, same but different comment ids

**Comment by bpasero** [comment]
For February pushing the following changes in IDs only:
* explorer.copyPath => copyFilePath
* explorer.revealInOS => revealFileInOS
* filesExplorer.deleteFile => deleteFile
* filesExplorer.moveFileToTrash => moveFileToTrash
* filesExplorer.rename => renameFile

Adopting these for the active editor is https://github.com/Microsoft/vscode/issues/21344
