### ISSUE TITLE
Accessible View comments navigation not working when screen not maximized

### ISSUE THREAD

**Issue by ntrogh** [microsoft/vscode#211074]
Testing #210598

VS Code: latest 1.89.0-insider
OS: Windows_NT x64 10.0.22631
GHPR extension: v0.87.2024042204 (pre-release)

1. Open VS Code, not maximized
2. Checkout PR with multiple comments
3. Open Comments pane
4. Open accessible view with Alt+F2
5. Buttons to navigate to the next and previous comment do nothing
6. Maximize the VS Code window -> comments navigation works correctly

**Comment by meganrogge** [comment]
I cannot reproduce. A gif would help if you still can

https://github.com/microsoft/vscode/assets/29464607/0b8f3f92-1d61-4d72-8519-d6496d576a8b

**Comment by meganrogge** [comment]
Thanks for the gif! I see what you mean now. 

Since this requires a user to resize the window while the accessible view is shown, it's a rare edge case that I will not fix.

**Comment by ntrogh** [comment]
The problems occurs whenever the window is not maximized, regardless if the AV was already open or not.

**Comment by meganrogge** [comment]
The window is not maximized for me here and they work. 

https://github.com/microsoft/vscode/issues/211074#issuecomment-2075710230

**Comment by meganrogge** [comment]
Maybe it's a windows only issue. I will try.

**Comment by ntrogh** [comment]
Ok, might be a glitch on my machine then. Thanks for checking.

**Comment by meganrogge** [comment]
thanks for the thorough testing. strange re your machine. here's my recording on windows.

![Recording 2024-04-24 at 14 13 46](https://github.com/microsoft/vscode/assets/29464607/21af1082-53b2-412d-aabb-78e0dc30a7e5)

**Comment by ntrogh** [comment]
Ha, I figured out why it sometimes works:
1. Adjust the width such that the AV is larger than the Search box that sits below (in the title) -> buttons don't register mouse
2. Widen the window such that the AV is smaller than the Search box -> mouse clicks registers and the buttons work
3. If the overlap is partial, only one of the buttons work (see video below)

https://github.com/microsoft/vscode/assets/1908215/3d4dc55a-41d1-4f7b-a5be-e846697850fd

**Comment by meganrogge** [comment]
Thanks for figuring this out. Since screen reader users will use the keyboard shortcuts, `alt+[ ]`, instead of the mouse, this seems fine.
