### ISSUE TITLE
Window activity API - window becomes inactive during long running git operation

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#211064]
Testing #210978

* Add a git pre-commit hook that sleeps for 120 seconds
* Make a change to a file, and commit the change
* Switch to another VS Code window

Expected behaviour:
* Window should be active while the source control operation running

Actual behaviour:
* Window becomes inactive even though the source control operation is still running

**Comment by connor4312** [comment]
Yea, I think that's reasonable, thanks for the suggestion. Will take care of it 🙂
