### ISSUE TITLE
SCM: delete key should clean the selected file

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#21101]
Refs: #20440 

1. scm viewlet, have some changes
2. focus an element, press the `delete` key -> the item should be cleaned or removed from staging
3. this would nicely align with the delete behavior we have in other trees

**Comment by joaomoreno** [comment]
Not a great fan of this. Sorry!

**Comment by isidorn** [comment]
Why not? I think it aligns nicely and is very intuitive imho

**Comment by joaomoreno** [comment]
Because the key is called `Delete`. And what is shown is mostly a file. Delete a file is not the same as revert all the changes done to it. IMO it brings a confusing analogy to the table.
