### ISSUE TITLE
File content does not update if you change it using mmap

### ISSUE THREAD

**Issue by fireattack** [microsoft/vscode#211007]
Type: <b>Bug</b>

If you update the content of a text file using mmap, it will not reflect in VS Code. 

Sometimes, not even after you close and re-open the file in tab.

Repro steps:

1. create a file called run.py with the following content:
```python
import mmap

with open("temp.txt", mode="w", encoding="utf-8") as file_obj:
    file_obj.write("Initial content written. Please check another tab.")

input("Press enter to overwrite the file using open()")

with open("temp.txt", mode="w", encoding="utf-8") as file_obj:
    file_obj.write("Overwritten content using open(), Please check another tab.")

input("Press enter to overwrite the file using mmap")
with open("temp.txt", mode="r+", encoding="utf-8") as file_obj:
    t = b"Overwritten content using mmap, Please check another tab."
    with mmap.mmap(file_obj.fileno(), length=len(t), access=mmap.ACCESS_WRITE) as mmap_obj:
        mmap_obj.write(t)
        mmap_obj.flush() # makes no difference in this case if you flush or not
```

2. Create an empty text file called temp.txt and open it as active tab.
3. Navigate to terminal, and run the script (`python run.py`). Observe the text in opened tab for temp.txt, and keep pressing Enter.

Observed: the content of the temp.txt changes with any write operation in the first two steps. However, at the 3rd step, despite the content of the file has already changed (you can open the file in another text editor to confirm), it is not reflected in the VS Code. Sometimes, even close and re-open the file in the tab will not update it.

Expected: the file content should be dynamically updated once it was changed.

Additional comment:

This issue is particularly annoying because AFAIK VS Code does not offer any force-reload option. So to see the newest content of a file, I often have to re-open VS Code manually. This is very tedious. 

VS Code version: Code - Insiders 1.89.0-insider (5ae5a741bdb676abb667fd4896dc2a40e313db3a, 2024-04-22T05:50:44.921Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.87GB (4.19GB free)|
|Process Argv|--crash-reporter-id bcd92158-6998-4802-84d9-5452edf8ef65|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.4.0
isort|ms-|2023.10.1
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
jupyter|ms-|2024.3.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aacf:30263846
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
fegfb526:30952798
bg6jg535:30979844
ccp2r3:30958153
pythonait:30973460
gee8j676:31009450
showvideot:31016890
chatpanelt:31014475
f3je6385:31013174
pythoncenvpt:31022790
a69g1124:31018687
88717513:31021561

```

</details>

**Comment by fireattack** [comment]
Another shorter STR:

1. Create temp.txt with content `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` and open it in tab.
2. Run a py script with:
```python
import mmap

with open("temp.txt", mode="r+", encoding="utf-8") as file_obj:
    with mmap.mmap(file_obj.fileno(), length=0, access=mmap.ACCESS_WRITE) as mmap_obj:
        mmap_obj.write(b'Python')
```

Observe the content of the file does not change.

**Comment by bpasero** [comment]
> Sometimes, not even after you close and re-open the file in tab.

This indicates to me that it is not a file watcher problem but that we actually do not get the latest contents when we use node.js for reading.

I am not an expert in how `mmap` works or flushes contents to disk, but I would assume it does not follow the same approach as normal file writing goes and/or is limited by what node.js can handle.

We rely on node.js for file reading and I just found https://github.com/nodejs/node/issues/41069 which may suggest it is not supported.

Sorry, but I think we are limited here by what node.js can offer.
