### ISSUE TITLE
Debug: breakpoint from second application does not cause window to take focus

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21111]
Not sure if this is intentional but when I debug 2 apps at the same time and the first app is paused on a breakpoint, letting the second app hit a breakpoint does not bring focus to the debugger and reveal the hit breakpoint.

**Comment by isidorn** [comment]
Strange, I call `windowService.getWindow().focus();` so it should work nicely.
Feb to investigate

**Comment by isidorn** [comment]
Works for me. Can you repro all the time?
On mac? If yes can you set a breakpoint in windowService.getWindow() and check if that gets called properly


![helloben](https://cloud.githubusercontent.com/assets/1926584/23268173/38c63af6-f9ed-11e6-847a-e9caba3dfa0a.gif)

**Comment by bpasero** [comment]
@isidorn i tried with my standup app starting it 2 times and opening a URL in the browser where I had a breakpoint set in the index.js route.

**Comment by bpasero** [comment]
@isidorn ok I think here is what happens:
* I start standup 2 times and have a breakpoint in index route
* I open the first standup app and breakpoint is nicely hit
* I open the second standup app and the window is not focussing likely because i am already in a hit breakpoint from app 1
* now I press "play" for app 1
=> I am still not seeing that app 2 is in breakpoint hit condition

**Comment by isidorn** [comment]
Yes we had some conecerns about always focusing the app that stops, since in a scenario where a user is debugging multiple processes this might make it imposible for him to actually check out the state of a stopped app (e.g. multi cluster node debugging)
Though I agree this could be improved and thank you for providing more detailed steps, puting it to March to investigate more

**Comment by bpasero** [comment]
Maybe one thing to improve is to actually show the second application is being stopped when you press play on the first application. But since I am not a heavy selfhoster of this feature, might be best to do what users expect.

**Comment by isidorn** [comment]
Just tried it out and decided to close as designed.
To be more precise we will nicely focus the other process once you first process has fully terminated, it does not make sense to automatically focus if the first process is still running.

Imagine the scenario where a user continues process A, and then hits the stop button expecting to terminate A, however we have autofocussed B which leads to undesired behavior.
