### ISSUE TITLE
Add SymbolKind 'object' and 'key'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#2111]
In the outline of JSON possible symbol kinds is 'object' and 'null. There's no symbol kind for that yet.
Just using an other kind doesn't work well as the symbol kind not only impacts the icon but also the grouping label (Ctrl+Shift+O, ':'), 
Note, there are already kinds for 'array', 'number' and 'string'

Special case is the keyboard configuration, which we treat special for a better user experience. I use the 'function' icon, but would like to call the grouping 'key'.

IMO the better approach would be to use 'kind' just for the icon and have a 'group' attribute that is used for grouping (as we had it before)

**Comment by jrieken** [comment]
@aeschli I see that `object` uses the `module` icon but I can't see how `null` is used - also `key` isn't used. what icons from our set do you want them to map to?

**Comment by aeschli** [comment]
'null' never worked, we pass 'null' as icon, which doesn't exist. No icon is shown right now. I guess the Boolean icon is a better match.
For keys we use the 'string' icon.
