### ISSUE TITLE
Terminal suggest should replace characters before the suggest trigger/

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#211192]
Testing #210394

![image](https://github.com/microsoft/vscode/assets/2193314/58488223-09a0-4999-90fe-0789a2184f62)

Selecting it:

![image](https://github.com/microsoft/vscode/assets/2193314/463e62ef-1e63-4b2e-8750-38d7652b97d0)

**Comment by connor4312** [comment]
I'm not sure how to get file completions to work but I verified the behavior with commands as shown in the linked PR
