### ISSUE TITLE
[WelcomeUX] - No squiggles in the Errors and Warnings section

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#21119]
Testing #21034

![image](https://cloud.githubusercontent.com/assets/172399/23210106/66154426-f8fc-11e6-9c60-efc791a0ddab.png)

**Comment by chrmarti** [comment]
It takes like 10 seconds for them to show up on my machine. Does this reproduce after reloading the window? If so, does enabling `"typescript.tsserver.trace"` show any progress in the output panel?

**Comment by egamma** [comment]
I never see squiggles and the TypeScript language service is up and running (hovering, intellisense works).

**Comment by chrmarti** [comment]
Closing after not having received additional information.
