### ISSUE TITLE
Incorrect colors in tmux

### ISSUE THREAD

**Issue by musjj** [microsoft/vscode#211185]
### Does this issue occur when all extensions are disabled?: Yes

- VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:34:12.840Z)
- OS version: Linux x64 6.6.28

### Steps to Reproduce:

1. Setup `zsh` with the following `~/.zshrc`:
```bash
if [[ -z $TMUX ]]; then
  exec tmux -L debug -f /dev/null new-session # ensures no config is loaded
fi
```
2. Open a new terminal pane inside VSCode and run the following command:
```bash
echo -e '\033[48;2;20;27;30mHello!\033[0m'
```
### Without tmux:
![image](https://github.com/microsoft/vscode/assets/72612857/e9598c40-d920-4db6-98d6-1ba878f31e72)
Without tmux, I'm getting the expected results: a text with a `#141b1e`-colored background

### With tmux:
![image](https://github.com/microsoft/vscode/assets/72612857/1c9e533a-3005-4fcc-8685-92f98532b9d0)
With tmux, the text background mysteriously gets converted into `#1c1c1c`.

**Comment by Tyriar** [comment]
This is indeed mysterious. This is what I see we (vscode) gets from bash (under Windows/wsl):

```
[?2004l
[48;2;20;27;30mHello![m[K
[?2004h

[34m[1m/mnt/c/Github/Tyriar/xterm.js[m[K
```

and from tmux:

```
[?25l[48;5;234m
Hello![34m[49m[1m[6;1H/mnt/c/Github/Tyriar/xterm.js[32m
```

I also notice that this works just fine under Windows Terminal 😕 I have no idea what's going on here and why tmux is giving us back the wrong color tbh.

**Comment by musjj** [comment]
I managed to figure out a work around by adding this to my `~/.config/tmux/tmux.conf`:
```bash
set -ga terminal-overrides ",xterm-256color:RGB"
```

Does this work for you too?

I'll keep this open, just in case a "proper" fix can be implemented.
