### ISSUE TITLE
Terminal suggest: consider making / and \ trigger characters (maybe also any character after a space?)

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#211194]
Testing #210394

These will often complete to paths:

![image](https://github.com/microsoft/vscode/assets/2193314/eea7b86b-5dbe-46c8-bf45-6d3eccc9ee9c)
![image](https://github.com/microsoft/vscode/assets/2193314/1d14c483-8f39-4080-b258-241097b6c3ba)

**Comment by amunger** [comment]
Every character appears to be a trigger character, is this issue only about triggering after the first word?

![image](https://github.com/microsoft/vscode/assets/2019016/40d5a362-9d17-49f6-996e-208a3d325464)
![image](https://github.com/microsoft/vscode/assets/2019016/eadda76c-d957-4a63-9ec8-c646923f99ad)
![image](https://github.com/microsoft/vscode/assets/2019016/2b061c8d-66b8-4561-bb3d-8cc894a7e601)

**Comment by Tyriar** [comment]
To verify:

1. Enable suggest
1. Open pwsh
2. Type `ge`
3. Press escape to dismiss suggest
4. Press `t`, suggest should NOT appear
5. Press `-`, suggest should appear
6. Complete `Get-Content`
7. Press space
8. Press `.`
9. Press escape to dismiss suggest
10. Press `/`, suggest should appear
11. Press escape to dismiss suggest
12. Backspace to delete the `/`
13. Press `\`, suggest should appear

**Comment by amunger** [comment]
one note - more than . / \ will trigger suggest after a space

![image](https://github.com/microsoft/vscode/assets/2019016/7c06321d-c28f-477a-bc15-7c5a360f646b)
