### ISSUE TITLE
Allow keybinding to expand hover without focusing on hover part

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#211166]
Testing #210904

With a hover showing, I'd expect the keybindings to expand/shrink the hover even if I have clicked on a hover element. Maybe in this case we can expand/shrink all the hover elements?

**Comment by aiday-mar** [comment]
With the PR https://github.com/microsoft/vscode/pull/235848, all the sub hovers will be expanded/contracted if no subhover part is selected.
