### ISSUE TITLE
Don't auto-suggest commands within quotes

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#211103]
Testing #210394

1. Type `echo 'Select-`
:bug: command completions are shown, but none of those commands will actually run in this case

I was specifically playing around with [this example](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-string?view=powershell-7.4#example-2-find-matches-in-text-files), and typing that last pattern will trigger auto-completions that I didn't want.

Get-Alias | Out-File -FilePath .\Alias.txt
Get-Command | Out-File -FilePath .\Command.txt
Select-String -Path .\*.txt -Pattern 'Get-'

Alias.txt:8:Alias            cat -> Get-Content
Alias.txt:28:Alias           dir -> Get-ChildItem
Alias.txt:43:Alias           gal -> Get-Alias
Command.txt:966:Cmdlet       Get-Acl
Command.txt:967:Cmdlet       Get-Alias

**Comment by TylerLeonhardt** [comment]
It's a good question. It's certainly possible but depends on how far down the rabbit hole we wanna go.
* Could look at the AST of what's written and see where we are at - you can do this entirely in PowerShell btw:
  ```pwsh
  [ScriptBlock]::Create('Get-S').Ast
  # or
  { Get-S }.Ast
  ```
  Gets you the AST that you could visit
* Simple stack of quotes ... but this could be error prone

Any other ideas @SteveL-MSFT @daxian-dbw ?

**Comment by Tyriar** [comment]
How it works right now:

![image](https://github.com/microsoft/vscode/assets/2193314/96002046-50f4-44f5-aa2b-e155911e6dc8)

Having said that, I'm also considering showing completions a lot more to align closer with the editor: https://github.com/microsoft/vscode/issues/211194

**Comment by Tyriar** [comment]
Not planning on doing this, instead we will trigger on trigger chars and "quick suggestions" like in the editor.
