### ISSUE TITLE
Ctrl+c in terminal does not scroll to the very bottom

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#211199]
Repro:

1. Fill viewport
2. Scroll up
3. Press ctrl+c, 🐛 the terminal is not scrolled to the very bottom

![Recording 2024-04-23 at 17 51 44](https://github.com/microsoft/vscode/assets/2193314/9ab69275-5e32-47dd-9c1e-30d0504d6c08)

**Comment by Tyriar** [comment]
This is a bug when `"terminal.integrated.smoothScrolling": true` is set

**Comment by Leonikkk** [comment]
Gzt
