### ISSUE TITLE
[WelcomeUX] - Interface overview for errors and warnings is off when workspace has a git repo

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#21116]
Testing #21034

![image](https://cloud.githubusercontent.com/assets/172399/23209696/8b652f5e-f8fa-11e6-830e-4fe758b4748d.png)

Removing the error from the annotation would be a way fix this.

**Comment by chrmarti** [comment]
The general issue is tracked with #18861. This particular one seems to occur often, will check if there is a simple fix.
