### ISSUE TITLE
resolveDocumentPasteEdit failing results in selector not showing up in file

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#211137]
Testing #210985

In the document-paste sample extension, I added a resolveDocumentPasteEdit function that creates a new file and returns the original pasteEdit. I noticed that when the file creation fails, that I don't get a selector anymore in the plain text file after pasting the text.

**Comment by mjbvz** [comment]
Do you mean that your `resolveDocumentPasteEdit` implementation throws? Or that the file creation itself when applying the edit fails?

**Comment by rzhao271** [comment]
The implementation throws due to failing to create a file that already exists.
I realize now that as the extension author, I could just catch the exception on my end.

**Comment by mjbvz** [comment]
Ok thanks @rzhao271. For verification, I'm going to try adding the following behavior:

- If `resolveDocumentPasteEdit` throws, we show an error notification 
- If the workspace edit returned can't be applied (such as trying to overwrite an existing file), we also show an error notification

In both cases we allow switching back to use other paste edits instead, such as the normal text paste
