### ISSUE TITLE
Waiting for suggestions can lock up the terminal

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#211107]
Testing #210394

This is another one that only happened once - 

I typed `Get-AppPackage -`, which I assume triggered the widget for an argument list, but it didn't come up.
Typing other characters did not affect the terminal for about 10 seconds
Suddenly the characters I had been typing showed up and the suggest widget appeared

**Comment by Tyriar** [comment]
I think I saw this but the delay was only a few seconds the first time I used it, after that it seems to be fast. My guess is that it takes some time to run `TabExpansion2` for this particular input, and if so I'm not sure we can do something about that as we only have a single pipe we're working off and the shell is busy.

**Comment by Tyriar** [comment]
I don't think there's anything we can do about this, it's just a consequence of the completion provider for get-apppackage being a bit slower than others. Luckily it's just one time in a session and seems to be fast after that.

**Comment by Tyriar** [comment]
Note that right now for me it locks up for about .5-1s
