### ISSUE TITLE
Outline doesn't always clear the old value

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#211178]
Testing #210961

![image](https://github.com/microsoft/vscode/assets/2019016/1aee0336-47f2-43c6-8e94-2b22526a1bf1)

This happened when updating the file on disk outside of vscode, I'll try to find a consistent repro

**Comment by amunger** [comment]
1. open a notebook with several markdown headers in insiders
2. open the same notebook in stable and add a header
:bug: outline in insiders is not updated
4. remove a different markdown header in insiders
:bug: screencheese

**Comment by amunger** [comment]
![Recording 2024-04-23 at 15 16 44](https://github.com/microsoft/vscode/assets/2019016/0b4221fe-1604-4739-b91f-c894428b652c)


[nb2.ipynb.txt](https://github.com/microsoft/vscode/files/15083644/nb2.ipynb.txt)

**Comment by DonJayamanne** [comment]
Thanks I can replicate this issue.

**Comment by rzhao271** [comment]
Giving the issue back to Aaron to verify. My Python install's a bit broken.
