### ISSUE TITLE
Should there be an initial event fired for `window.onDidChangeWindowState`?

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#211182]
Testing #210978

I'm using a simple extension generated with `yo code` such that I have to activate with a command (`Hello World`).  Once I activate the extension and then become idle or move away, I get the first `onDidWindowChangeState` event to fire.

I'm wondering if an extension author would want that event to fire immediate after activation to "start the clock". Or, is it sufficient to fire it only when someone moves away or becomes inactive. In some sense, the first usage of the tool is a change to the "Active" state.

This is pure speculation on my part, just wanted to ask the question.

**Comment by connor4312** [comment]
This isn't something we do in general: extensions should seed their state by reading the constant/getter (in this case `vscode.window.state`) and then respond to any changes by listening to the event.
