### ISSUE TITLE
Flutter - "command 'flutter.createProject' not found"

### ISSUE THREAD

**Issue by Garciaza1** [microsoft/vscode#211169]
Type: <b>Bug</b>

I don't have Flutter installed on my machine or in the extensions. I had it previously on another PC, but all the settings from my VS Code were transferred to this PC. Since I stopped using Flutter, the error keeps appearing every time I press the 'k' key. The following message appears in the status bar: '(k) was pressed awaiting next chord key.' Then neither the 'k' key nor the next one are typed in the file. I can't type 'k' in VS Code at all. I need help, I've tried restarting, disabling extensions, I've tried everything.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (3.97GB free)|
|Process Argv|--crash-reporter-id be459115-4d63-4680-a0e8-940acae15658 --crash-reporter-id be459115-4d63-4680-a0e8-940acae15658|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bootstrap5-vscode|Anb|0.4.4
vscode-intelephense-client|bme|1.10.4
npm-intellisense|chr|1.4.5
gitlens|eam|14.9.0
vscode-html-css|ecm|2.0.9
prettier-vscode|esb|10.4.0
vscode-docker|ms-|1.29.0
vscode-language-pack-pt-BR|MS-|1.88.2024041009
vsliveshare|ms-|1.0.5918
vscode-yaml|red|1.14.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.34.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31022790

```

</details>

**Comment by IllusionMH** [comment]
You can check your settings to see if there are any old local keybindings left. See https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-generic-keybindings

If still not clear where's problem try
https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting
https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-windows-keybindings

**Comment by Garciaza1** [comment]
thanks to your help man 🙌❤️
