### ISSUE TITLE
Not all the actions in the `Comments` widget are visible in the `Accessible View`

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#211193]
Testing #210598

1. Find a pr using the GitHub Pull Request.
2. Add some test comments to the PR.
3. Open the Accessible view. 
The actions at the top of the accessible view does not contain the `Go To Review` actions which is present in the comments widget.
<img width="1006" alt="image" src="https://github.com/microsoft/vscode/assets/25044782/9429bc2a-d935-4a57-af68-4ca6ededa667">

**Comment by meganrogge** [comment]
This is expected. The actions that should appear in the accessible view are the ones that exist in the comments panel view. 

<img width="650" alt="Screenshot 2024-04-24 at 12 14 09 PM" src="https://github.com/microsoft/vscode/assets/29464607/e26f03c7-3930-4c44-9664-58d3d473048b">
