### ISSUE TITLE
ITextResourceConfigurationService does not take default.override into account

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#211148]
When `default.override` has a value (e.g. `"[yaml]":  { "diffEditor.ignoreTrimWhitespace": false },` as default settings), but the `configurationTarget` is `USER_LOCAL` and the user does not have an override for the language, `_updateValue` does not write the value with an override to the user settings.
Because default settings with an override take precedence over user settings without an override, the `updateValue` has no effect for the given resource (and language id), which is why nothing happens when the user clicks the toggle button.

https://github.com/microsoft/vscode/blob/81cf6c4c164a7faef036c2980f625fa2e6ecc725/src/vs/editor/common/services/textResourceConfigurationService.ts#L40-L58

This is an issue in #210543 (which tries to fix #210460)

**Comment by andreamah** [comment]
Are there some verif steps for this?

**Comment by sandy081** [comment]
@hediet Can you please verify this.
