### ISSUE TITLE
Invalid warning when provided an invalid value for `protocol`

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#21113]
Testing #20991 

![kapture 2017-02-22 at 12 23 27](https://cloud.githubusercontent.com/assets/10746682/23209512/c377a922-f8f9-11e6-8893-64f520c95b4d.gif)

**Comment by isidorn** [comment]
@aeschli I thought the [`errorMessage`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/jsonSchema.ts#L44) gets applied only when the [`pattern`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/jsonSchema.ts#L26) is not respected. Not in the general error case.

If the error message shows always then it would make the feature unusable for my use case.

**Comment by aeschli** [comment]
Are you sure your pattern matches here?

**Comment by aeschli** [comment]
@isidorn Can you point me to your schema?

**Comment by isidorn** [comment]
My pattern does not match there. After further inspection any time I get an error I always get the message.

Here's a pointer to my [schema](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L153). Note that I dynamically fill up the `errorMessage` [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/node/debugAdapter.ts#L229)
