### ISSUE TITLE
button to execute the code in the terminal in vsc deleted

### ISSUE THREAD

**Issue by nilklab** [microsoft/vscode#211298]
Type: <b>Bug</b>

J'ai supprimer l’affichage du bouton pour lancer le code ainsi maintenant je dois aller dans le trois petit point en haut a droite puis sur exécuter ou débugger et après exécuter le fichier python pour exécuté le code, je voudrais savoir comment le faire réapparaître svp. Merci

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600 6-Core Processor               (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.56GB free)|
|Process Argv|--crash-reporter-id 42c8e220-e783-43b1-b9df-91fa7bd3a38b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
blackbox|Bla|1.3.15
codeium|Cod|1.8.28
vscode-language-pack-fr|MS-|1.88.2024041009
debugpy|ms-|2024.5.11141010
python|ms-|2024.5.11021008
pdf|tom|1.2.2
pygame-snippets|tus|0.0.1
vscode-icons|vsc|12.7.0
material-theme|zhu|3.17.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
gee8j676:31009558
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31022790

```

</details>

**Comment by meganrogge** [comment]
english translation:

I removed the display of the button to launch the code so now I have to go to a lot of settings to launch the code, I would like to know how to make it reappear please. Thank you

not sure which run button you mean. I'd suggest checking your settings.json file or right clicking on the view and resetting it.

**Comment by nilklab** [comment]
![Capture d'écran 2024-04-25 002928](https://github.com/microsoft/vscode/assets/125213482/7810ee69-11fa-44ff-abe6-fbafa6af1d02)
this buttton

**Comment by nilklab** [comment]
Its done, I see it now, thank
