### ISSUE TITLE
"Share" context menu in editor gutter lost github-related sharing 

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#211240]
Repro: 

1. Right-click on line number
2. Click on "Share..." 
3. :bug: See no github-related items (but they're present in "Share..." command in command palette)

<img width="1512" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/f42b6812-e743-4632-b900-0f43ee5025cf">

https://github.com/microsoft/vscode/assets/16353531/42f890cd-15a0-46fd-b240-92fa471e662c

**Comment by joyceerhl** [comment]
I can't reproduce this behavior, does this still occur for you?

![Image](https://github.com/user-attachments/assets/a78e70b7-0e89-496f-9f06-4186d7f18f5f)

**Comment by ulugbekna** [comment]
can't repro either

I'm surprised, however, that these actions are not within the "Share..." sub-menu

![Image](https://github.com/user-attachments/assets/c9188a20-0bd9-4612-9f8f-5887b26e7f8d)
