### ISSUE TITLE
Delphi/Pascal not supported

### ISSUE THREAD

**Issue by SkybuckFlying** [microsoft/vscode#211239]
Type: <b>Bug</b>

Really ?!

Windows was based on Pascal,

Shame !

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7950X3D 16-Core Processor           (32 x 4192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.12GB (112.36GB free)|
|Process Argv|--crash-reporter-id 4a7c921f-3af7-4c86-8913-511a5bc9b7a1|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
delphi-pack|ale|2.0.1
numbered-bookmarks|ale|8.4.0
solidity|Jua|0.0.174
generate-code-gemini|Shi|0.5.1
cody-ai|sou|1.14.0
truffle-vscode|tru|2.7.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30993540
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
chatpanelt:31018789
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31022790

```

</details>

**Comment by gjsjohnmurray** [comment]
https://marketplace.visualstudio.com/search?term=Pascal&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by dbaeumer** [comment]
I will close the issue. Additional language support usually comes through extensions in VS Code and there are Pascal extensions in the Marketplace.
