### ISSUE TITLE
Color select

### ISSUE THREAD

**Issue by tomerlgh** [microsoft/vscode#211293]
Type: <b>Feature Request</b>

I just wanted to say THANK YOU
I have the following code:
        td {
            border: 1px solid rgb(14, 0, 211);
            padding: 8px; /* Add horizontal margin */
            text-align: center; /* Center align the text */
        }

In the terminal I have a small sqaure that allow me to select the color
this is GREATE feature.
Big thank you for adding this feature.
Thanks
tomerl

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:34:12.840Z)
OS version: Linux x64 6.5.0-28-generic snap
Modes:

**Comment by aiday-mar** [comment]
Hi we do not have colors in the terminal as far as I know. 

This does not appear to be an issue, so I will close it
