### ISSUE TITLE
about the "Format On Save"

### ISSUE THREAD

**Issue by DeYuanGeGe** [microsoft/vscode#211214]
Type: <b>Bug</b>

I have selected the "Format On Save"  in User > Text Editor > Formatting
my code :
<style lang="scss">
// .kcool,
// .kdark {
//     .chkimg {
//         background-color: #999;
//     }
// }
</style>
issues - the last code line be comment yet
when I Ctrl + S save the code ,the code will be change to：

<style lang="scss">
// .kcool,
// .kdark {
//     .chkimg {
//         background-color: #999;
//     }
// }</style>

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (2.36GB free)|
|Process Argv|--crash-reporter-id c9c6de36-38a8-4ab2-ac4a-892e7f9ced97|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.3
path-intellisense|chr|2.8.5
shell-format|fox|7.2.5
vue-snippets|hol|1.0.4
remote-wsl|ms-|0.88.0
webgl-glsl-editor|rac|1.3.8
shader|sle|1.1.5
volar|Vue|2.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
gee8j676:31009558
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31022790

```

</details>

**Comment by RobinWragg** [comment]
@DeYuanGeGe May I suggest using `code sections` in your comment, or posting screenshots? It should show the formatting problem more clearly.

**Comment by DeYuanGeGe** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jrieken** [comment]
For me it is being formatted into this ⬇️ which seems correct to me

```
<style lang="scss">
	// .kcool, // .kdark { // .chkimg { // background-color: #999; // } // } 
</style>
```

**Comment by jrieken** [comment]
Can you update your steps or attach a recording?

**Comment by DeYuanGeGe** [comment]
for example, my scss code like that:
![sample1](https://github.com/microsoft/vscode/assets/18155333/0a504419-9f01-47b0-9094-bb74cbd9ff08)
but ,when I Ctrl + S save the code , the code will be change to :
![sample2](https://github.com/microsoft/vscode/assets/18155333/8e2706a3-04c2-4dbf-aae9-605faea07db4)
and so I test some time, find, only comment the last line code , can trigger the bug.
the bug only find in <style lang="scss"></style>
![test1](https://github.com/microsoft/vscode/assets/18155333/e38bf3cf-602c-475a-92fe-bad89471279a)

**Comment by IllusionMH** [comment]
Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Looks like issue with Volar extension, as VS Code doesn't support `.vue` files out of the box and should not format these files at all.

Or you can go for full troubleshooting <kbd>F1</kbd> and `> Help: Troubleshoot Issue`

**Comment by DeYuanGeGe** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by IllusionMH** [comment]
Please use English, so content would be accessible for devs and other users.
