### ISSUE TITLE
The close button for tabs is on the right side

### ISSUE THREAD

**Issue by suvrajitbhattacharjee** [microsoft/vscode#211248]
Type: <b>Feature Request</b>

Hi,

It's a small request for the UI. Running VScode on Mac, the tabs have the close button on the right hand side which is a bit weird given that any native Mac app has the close button on the left hand side.

VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin arm64 23.4.0
Modes:

**Comment by benibenj** [comment]
You can change it with `workbench.editor.tabActionLocation: left`
