### ISSUE TITLE
An exception occurred in the style of `rename symbol`

### ISSUE THREAD

**Issue by czfadmin** [microsoft/vscode#211215]
Type: <b>Bug</b>

The style of `rename symbol` is abnormal. The input box is white, and the same is true for multiple color themes.

![image](https://github.com/microsoft/vscode/assets/13393959/02eca2a3-f9c8-424e-84b5-1447c84be6f8)

The following is the result reproduced when all plug-ins are disabled.
![image](https://github.com/microsoft/vscode/assets/13393959/1544b01a-0475-4c80-aaf7-13b4b0a7b267)

VS Code version: Code - Insiders 1.89.0-insider (fd518e4db7bcf89d7e19bf29522786d0cd16a9a6, 2024-04-23T19:08:21.927Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (1.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
Bookmarks|ale|13.5.0
vscode-sqlite|ale|0.14.1
html-class-suggestions|And|1.2.1
ng-template|Ang|17.3.1
chronicler|arc|0.1.16
vscode-tailwindcss|bra|0.10.5
npm-intellisense|chr|1.4.5
gitignore|cod|0.9.0
postcss|css|1.0.9
bookmark-manager|czf|0.0.33
ytheme|czf|1.3.20
redis-xplorer|Dav|1.2.7
npm-browser|den|1.1.4
docs-metadata|doc|1.0.9
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.9.0
vscode-html-css|ecm|2.0.9
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|10.4.0
vscode-todo-plus|fab|4.19.1
auto-close-tag|for|0.5.15
vscode-yarn|gam|2.1.0
leek-fund|gis|3.7.1
codespaces|Git|1.16.19
vscode-pull-request-github|Git|0.86.1
markdown-image|han|1.1.41
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.21.1
vscode-npm-dependency|how|1.2.2
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.18
debugpy|ms-|2024.5.11141010
python|ms-|2024.5.11141012
vscode-pylance|ms-|2024.4.102
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.1
js-debug-nightly|ms-|2024.4.817
live-server|ms-|0.5.2024010901
mono-debug|ms-|0.16.3
remote-explorer|ms-|0.4.3
test-adapter-converter|ms-|0.1.9
vscode-github-issue-notebooks|ms-|0.0.130
vscode-js-profile-flame|ms-|1.0.9
vscode-typescript-next|ms-|5.5.20240423
resourcemonitor|mut|1.0.7
bun-vscode|ove|0.0.12
material-icon-theme|PKi|5.1.0
material-product-icons|PKi|1.7.0
sqlite-viewer|qwt|0.3.17
bash-debug|rog|0.3.9
autoimport|ste|1.5.4
svelte-vscode|sve|108.3.4
errorlens|use|3.17.0
vscode-icons|vsc|12.7.0
volar|Vue|2.0.10
licenser|ymo|1.10.0

(1 theme extensions excluded)

</details>

**Comment by ulugbekna** [comment]
Hi @czfadmin 
Thank you for the issue! This have been fixed in today's insiders (April 24th, 2024)
