### ISSUE TITLE
Cannot open detected link

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#21126]
Testing #21021

* Open `linkComputer.test.ts`
* Add at the bottom:
```
/**
 * .\languageSelector.test.ts
 * ..\modes\languageSelector.test.ts
 */
```
* In the terminal `cd src\vs\editor\test\common\modes`
* In the terminal `cat .\linkComputer.test.ts`
* The links are detected but clicking on them appears to not do anything.
![terminal-links](https://cloud.githubusercontent.com/assets/5047891/23212348/864b39bc-f906-11e6-92b8-fd3ce5512bca.gif)

**Comment by Tyriar** [comment]
@alexandrudima the links are resolved relative to the opened folder in VS Code, not the cwd of the terminal. A solution to the latter is being explored in https://github.com/Microsoft/vscode/issues/20676

Did you have the vscode directory open?

**Comment by alexandrudima** [comment]
Yes, I had `C:\Alex\src\vscode` opened and (as explained in the original steps) I did:
* `cd src\vs\editor\test\common\modes`
* `cat .\linkComputer.test.ts`

I see it is hard to say what should be considered the base. If we use the workspace path as the base, then perhaps interpreting `..\` links does not make a lot of sense (going outside the workspace). There is also the question of what to do when no folder is opened. In any case, a message when clicking fails might be better than doing nothing.

**Comment by Tyriar** [comment]
Until #20676 is looked into we don't have access to the shell's current working directory so this is blocked on that.

On empty workspaces, I've been thinking about the idea of validating the links before adding them to the DOM. It's probably a good idea, to avoid possible performance relayout issues from editing the DOM, a class could be added to indicate the link is invalid. I'll track that in https://github.com/Microsoft/vscode/issues/21226

**Comment by Tyriar** [comment]
Links are now validated (however there is a discussion to remove this for perf reasons https://github.com/Microsoft/vscode/issues/25024).
