### ISSUE TITLE
python debugger not show anything

### ISSUE THREAD

**Issue by wanggaa** [microsoft/vscode#211224]
Type: <b>Bug</b>

offline install newest python plugins, but there is nothing in run&debug taggle

VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin arm64 23.3.0
Modes:
Remote OS version: Linux x64 3.10.0-1160.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|18.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id c49a1e64-1c64-4fcc-b81f-f508b38cd7c2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev|
|OS|Linux x64 3.10.0-1160.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz (128 x 3500)|
|Memory (System)|2015.28GB (1894.40GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.354.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
protein-viewer|Ari|0.1.0
vscode-django|bat|1.15.0
markdown-preview-github-styles|bie|2.0.4
debugpy|ms-|2024.5.11141008
python|ms-|2024.5.11021008
vscode-pylance|ms-|2024.4.102
indent-rainbow|ode|8.3.1
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r3:30993539
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
gee8j676:31009558
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31022790

```

</details>

**Comment by roblourens** [comment]
Not a vscode issue

**Comment by wanggaa** [comment]
![微信图片_20240514143646](https://github.com/microsoft/vscode/assets/7566291/eca485a3-21d9-4a7f-80ac-60a972463b04)
python and python debuger plugins installed successful
![微信图片_20240514143720](https://github.com/microsoft/vscode/assets/7566291/70f47297-aa8a-4da6-9a6b-f888f7cf5ce3)
but in debug channel there is nothing
