### ISSUE TITLE
Not getting any debug commands

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#21132]
Testing #20982

Version 1.10.0-insider
Commit 256d76fed7947e7289f921df10658d7a69233b65
Date 2017-02-22T07:09:05.746Z

Linux

- In the VSCode workspace, open VSCode on the 'extensions/html' folder.
- press Ctrl + E, type: debug with space at the end
- an empty dialog shows up
- click the dialog away
- error message shows up:
Unable to instantiate quick open handler vs/workbench/parts/debug/browser/debugQuickOpen - QuickOpenHandler: {"errorCode":"load","moduleId":"vs/workbench/parts/debug/browser/debugQuickOpen","neededBy":["===anonymous10==="],"detail":{"errno":-2,"code":"ENOENT","syscall":"open","path":"/usr/share/code-insiders/resources/app/out/vs/workbench/parts/debug/browser/debugQuickOpen.js"}}

**Comment by ramya-rao-a** [comment]
![image](https://cloud.githubusercontent.com/assets/16890566/23225484/e82a96d4-f8e6-11e6-97d9-8dc44b5e77fe.png)

![image](https://cloud.githubusercontent.com/assets/16890566/23225491/efbd6e30-f8e6-11e6-8874-30339855f938.png)

**Comment by michelkaporin** [comment]
This has been fixed and awaiting pull request review before merge in.
