### ISSUE TITLE
When I start debugging Node.js in v8.4.0, the process terminates.

### ISSUE THREAD

**Issue by papp888** [microsoft/vscode#211342]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.1
- OS Version: Darwin arm64 21.6.0

Bug Description.

Cannot debug a NodeJS application running on v8.4.0.

Steps to Reproduce:

1. Click the debug button(Launch Programm)

Debug Console
```
Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.js:2
`,CHAR_NO_BREAK_SPACE:"\xA0",CHAR_PERCENT:"%",CHAR_PLUS:"+",CHAR_QUESTION_MARK:"?",CHAR_RIGHT_ANGLE_BRACKET:">",CHAR_RIGHT_CURLY_BRACE:"}",CHAR_RIGHT_SQUARE_BRACKET:"]",CHAR_SEMICOLON:";",CHAR_SINGLE_QUOTE:"'",CHAR_SPACE:" ",CHAR_TAB:"	",CHAR_UNDERSCORE:"_",CHAR_VERTICAL_LINE:"|",CHAR_ZERO_WIDTH_NOBREAK_SPACE:"\uFEFF"}});var Ur=k((Ja,Fr)=>{"use strict";var oo=Qe(),{MAX_LENGTH:Hr,CHAR_BACKSLASH:Tt,CHAR_BACKTICK:io,CHAR_COMMA:ao,CHAR_DOT:lo,CHAR_LEFT_PARENTHESES:uo,CHAR_RIGHT_PARENTHESES:co,CHAR_LEFT_CURLY_BRACE:fo,CHAR_RIGHT_CURLY_BRACE:po,CHAR_LEFT_SQUARE_BRACKET:Mr,CHAR_RIGHT_SQUARE_BRACKET:$r,CHAR_DOUBLE_QUOTE:ho,CHAR_SINGLE_QUOTE:go,CHAR_NO_BREAK_SPACE:mo,CHAR_ZERO_WIDTH_NOBREAK_SPACE:_o}=Br(),yo=(e,t={})=>{if(typeof e!="string")throw new TypeError("Expected a string");let r=t||{},n=typeof r.maxLength=="number"?Math.min(Hr,r.maxLength):Hr;if(e.length>n)throw new SyntaxError(`Input length (${e.len

SyntaxError: Unexpected token {
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/var/folders/89/rnlqv6wj1tvb241hfvgngp3r0000gn/T/vscode-js-debug-bootloader.js:1:63)
Process exited with code 1
```

- Switching to Node.js version 12.22.12 is working.
- It seems to be the same problem as below, but v8.4.0 is not fixed?
  https://github.com/microsoft/vscode/issues/178769

**Comment by connor4312** [comment]
Node 8 reach its end of life date 4 years ago, please update your version of Node.js (22 is newest)

**Comment by papp888** [comment]
Thank you for your answer.

I understand that Node.js v8 support expired a long time ago, but I have to continue using Node.js v8 for a while longer for business reasons.

I would like to use the version that works fine for debugging and check it separately in production.

If there is an alternative, please let me know.

**Comment by connor4312** [comment]
You can attach the debugger this way to get around this issue: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_attaching-to-nodejs

But compatibility forever is not guaranteed.

**Comment by papp888** [comment]
Sorry for the delay in responding.
I was able to debug by the method you suggested. Thank you very much.
