### ISSUE TITLE
Linux: file opens even though it has parent folder with .vscode inside

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21133]
Testing: https://github.com/Microsoft/vscode/issues/20671

- OS Version: Linux

Steps to Reproduce:

1. from the desktop click on a file to open in Code that has a parent with a .vscode folder (I used the hello world TS extension for this)
2. only this file opens, I would assume the parent folder opens

/cc @Tyriar that might be something here with what arguments we are passing over when launching like this on Linux.

**Comment by Tyriar** [comment]
@chrmarti Launching on Linux like this uses the `--new-window-if-not-first` arg, this might be the cause for this? If you plan on changing the behavior you will need to ensure the following all launch a new empty instance on ubuntu

- Open VS Code -> win+shift+<num on taskbar item>
- Open VS Code -> middle click taskbar item
- Open VS Code -> shift+left click taskbar item

**Comment by chrmarti** [comment]
@Tyriar How would I distinguish these cases?

**Comment by Tyriar** [comment]
@chrmarti they don't open files

**Comment by Tyriar** [comment]
We probably want the new behavior on `--new-window` as well, no? I would have expected `--new-window-if-not-first` to work if `--new-window` was covered.

**Comment by Tyriar** [comment]
Discussed this with @chrmarti just now, he makes a good point for why `--new-window` does not have open a folder generally and I'm concerned about adding additional edge cases to `--new-window-if-not-first` at least in its current state.

I do however like the idea of changing `--new-window-if-not-first` to something like `--unity-launch`, adding this open folder behavior (if a file was specified) and documenting it heavily in code. Provided all the edge cases will work fine like this of course.

**Comment by chrmarti** [comment]
`--new-window` always opens a new empty workbench. This is the least surprise, we would otherwise have to check if the corresponding folder is already open and only in that case fall back to opening an empty workbench to obey the request for a new window. Also, `--new-window` seems to belong to the document oriented UX where opening without folder is preferred.

@Tyriar explained: `--new-window-if-not-first` is there to avoid two windows opening (one restored, one new) when no window is open yet. This is specific to Unity already, hence the proposal to adapt its behavior (and name) to allow for opening a folder.

**Comment by Tyriar** [comment]
To verifier, there's a lot that can go long here so there's a bunch of stuff to check. Luckily each of them should take too long. Please check on Ubuntu:

- [ ] Opening from taskbar (with no windows open, no hot exit backups)
  - This should restore the previously opened window
- [ ] Opening from taskbar (with no windows open, hot exit backups)
  - This should restore previous sessions without opening a new window
- [ ] Opening from taskbar (with windows open) by shift+clicking the taskbar icon
  - This should open an empty instance
- [ ] Opening a file via the file explorer (with no windows open)
  - This should open the folder of the file and open the file
- [ ] Opening a file via the file explorer (with windows open)
  - This should open the folder of the file and open the file
- [ ] Opening a file via the file explorer (with no windows open, hot exit backups)
  - This should open the file in one of the windows restored by hot exit
- [ ] Opening a folder via the file explorer (with no windows open)
  - This should open the folder
- [ ] Opening a folder via the file explorer (with windows open)
  - This should open the folder

One more which I'm not sure if it happens or not:

- [ ] Opening a file via the file explorer when the folder is already open (with windows open)
  - This should open the file in the folder that's already opened
