### ISSUE TITLE
Update builtin nodejs version

### ISSUE THREAD

**Issue by fr43nk** [microsoft/vscode#211345]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.1
- OS Version: Windows 10

In my current working environment the daily security scan brought up a possible vulnerability by the used node.js version.

**In detail:**
I'm using the remote.ssh feature - therefor the vscode-server instance that is running on the remote host uses a node.js version equal to the local vscode builtin node.js version (18.18.2).
Is it possible to update this node.js to have the latest bug fixes included?

**Comment by gjsjohnmurray** [comment]
I think #210467 will address this.
