### ISSUE TITLE
Opening of files in the project takes a long time

### ISSUE THREAD

**Issue by anastasiyamazheika** [microsoft/vscode#211325]
Type: <b>Performance Issue</b>

1. Open other typescript classes through shortcuts (e.g. cmd + left mouse key click in my case). Classes should be located in other files

Expected results: opening project files works from other files works fast.

Actual results: the standard opening of other project files takes minutes. Opening through ctrl+p works normally. This issue has been noticed by me for a couple of days

VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 17, 23|
|Memory (System)|32.00GB (0.72GB free)|
|Process Argv|--crash-reporter-id be868c75-e575-4721-991f-6caac31b1317|
|Screen Reader|no|
|VM|0%|
</details><details>

<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
codium|Cod|0.8.5
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|2.4.4
gitlens|eam|14.9.1
prettier-vscode|esb|10.4.0
copilot|Git|1.182.0
copilot-chat|Git|0.14.1
vscode-pull-request-github|Git|0.86.1
inline-parameters|lia|0.2.1
vscode-docker|ms-|1.29.0
csharp|ms-|2.23.15
vscode-dotnet-runtime|ms-|2.0.3
playwright|ms-|1.0.22
remote-containers|ms-|0.354.0
vsliveshare|ms-|1.0.5918
angular-console|nrw|18.20.0
material-icon-theme|PKi|5.1.0
bash-beautify|sha|0.1.1
open-in-browser|tec|2.0.0
pretty-ts-errors|Yoa|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
chatpanelc:31018788
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31022790

```

</details>

**Comment by mjbvz** [comment]
Please share an example project which demonstrates the issue

**Comment by anastasiyamazheika** [comment]
It helped me to clean up installed extensions :) 

https://github.com/microsoft/vscode/issues/211315#issuecomment-2077364406
