### ISSUE TITLE
code tunnel "--name" no longer sets the machine name when a tunnel exists

### ISSUE THREAD

**Issue by LER0ever** [microsoft/vscode#211378]
Does this issue occur when all extensions are disabled?: Yes (N/A)

- VS Code Version: 1.88.1
- OS Version: macOS

Steps to Reproduce:

1. In the shell, run `code tunnel --name {ANYTHING}`, UPDATE: the system need to have a existing tunnel already running
2. Notice that the machine name is always inferred from Hostname instead of the machine name set through `--name`

~~This only happens recently when I upgrade to 1.88, the --name option works on previous releases before the upgrade, but I'm not sure which the last working version is.~~

<img width="931" alt="image" src="https://github.com/microsoft/vscode/assets/10568668/84bbcb3a-826c-48f9-adc0-10a4294593a1">

**Comment by LER0ever** [comment]
Update: I noticed the "Connected to an existing tunnel..." line, and if I kill the tunnel first using `code tunnel kill` and run the same command, it would correctly set the machine name. I'll update the issue description to reflect that.

**Comment by connor4312** [comment]
Yea, if there's an existing tunnel we just connect to it and never enter the process in which the name would be set. Renaming a running tunnel is also possible but could lead to unpredictable side effects. We should just log a warning in this case.

**Comment by amunger** [comment]
still no warning. I made sure I was on the latest

![image](https://github.com/microsoft/vscode/assets/2019016/db5cea4d-941d-4eb4-a08c-75ee644c8a05)

**Comment by connor4312** [comment]
@amunger in your screenshot you can see the warning which is what I added for this.
