### ISSUE TITLE
ctrl+shift+win+L stopped working

### ISSUE THREAD

**Issue by mjmierzwa** [microsoft/vscode#211302]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.0-insider
- OS Version: Windows Server 2022, Windows 10

Steps to Reproduce:

1. Open "Keyboard Shortcuts"
2. Click "Record Keys"
3. Press ctrl+shift+win+L

You will see "ctrl+shift+win" but no L added. Other letters like k, i, j work ok. I tried on different computers with Windows Server 2022 and couple of Windows 10 and it did not work. It worked on Windows Server 2016 though. All tested with the same VSCode zip version. Other Windows programs, like PowerToys Keyboard Manager seems to catch ctrl+shift+win+l properly.

**Comment by ulugbekna** [comment]
Hi 🙂

Thanks for filing this issue! 

Could you please try the [following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

1. Run the command "Developer: Toggle Keyboard Shortcuts Troubleshooting" (you can, for example, run it from the Command Palette). 

   This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.

2. Press exactly the keybinding you desire
 
3. Check what VS Code detects

If you are having trouble understanding the output, please feel free to paste here and we'll be happy to help ☺️

**Comment by mjmierzwa** [comment]
Hi 

Thank you for taking care.
I did "Developer: Toggle Keyboard Shortcuts Troubleshooting" before I submitted the issue. It revealed the same behavior ctrl, shift and win are detected but when they are pressed it does not detect following L. I also asked my friends to test and they confirmed the problem. Tested on many computers with Window 10, 11, Server 2022. The only one that it currently works on is Windows Server 2016. In the past it worked also on Windows 10.

**Comment by ulugbekna** [comment]
Could you try the same shortcut on https://w3c.github.io/uievents/tools/key-event-viewer.html ? 
I don't think we do anything specific for this shortcut; it's likely just windows or some built-in program just capturing it and not passing to vscode.

**Comment by mjmierzwa** [comment]
It seems it is problem in Windows not in VSCode. Windows does not catch Ctrl, Shift, Win + L keydown event.

**Comment by mjmierzwa** [comment]
It seems it is problem in Windows not in VSCode. Windows does not catch Ctrl, Shift, Win + L keydown event.

**Comment by phildaniels** [comment]
> It seems it is problem in Windows not in VSCode. Windows does not catch Ctrl, Shift, Win + L keydown event.

Out of curiosity did you ever find a resolution to this? I'm having similar issues with ctrl+shift+L, where the L keydown is not detected by windows

**Comment by mjmierzwa** [comment]
> Out of curiosity did you ever find a resolution to this? I'm having similar issues with ctrl+shift+L, where the L keydown is not detected by windows
Nope, I gave up at this moment. However, I had no problem with ctrl+shift+L, but only ctrl+win+shift+L KEYDOWN event (keyup had been registered).
