### ISSUE TITLE
Unable to set breakpoints in untitled file with associated path

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21135]
Related to https://github.com/Microsoft/vscode/issues/19415 if you follow Seans steps, you will see that you cannot add breakpoints to untitled files, which imho would be nice in this scenario.

**Comment by isidorn** [comment]
We support it with "debug.allowBreakpointsEverywhere": true
I do not want to treat untitled files specially in this case, so a user would have to enable this setting.
Closing as designed
