### ISSUE TITLE
"Git: Commit Empty" command unexpectedly includes unstaged changes in the commit

### ISSUE THREAD

**Issue by EmilJunker** [microsoft/vscode#211322]
Type: <b>Bug</b>

Step 1: Open a workspace that is under Git source control
Step 2: Make some changes to a file, but don't stage them
Step 3: Run the "Git: Commit Empty" command from the VS Code command palette

Actual behavour: VS Code adds a Git commit that includes the changes you made to the file.

Expected behavior: VS Code adds an empty Git commit. The changes you made to the file are still unstaged.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (21.90GB free)|
|Process Argv|--crash-reporter-id 2b6dfd8a-bec1-40a4-bf6c-03dc33a2d0a7|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
8082a590:30971561
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
showvideot:31016892
chatpanelc:31018788
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31022790

```

</details>

**Comment by lszomoru** [comment]
Pushed a fix so that unstaged changes are not included when creating an empty commit. Please note however that if you have any staged changes, those will be included in the commit when creating an empty commit. That is the expected behaviour.
