### ISSUE TITLE
Git entry under View is not showing key binding

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#21138]
Testing #20999

(Windows)

![image](https://cloud.githubusercontent.com/assets/10746682/23215776/d7fb1d74-f913-11e6-8af6-e3470bd886a4.png)

**Comment by joaomoreno** [comment]
This is due to the intermediate Preview SCM state. As designed.

**Comment by ramya-rao-a** [comment]
Shouldnt the label be "SCM" instead of "Git"?

**Comment by joaomoreno** [comment]
@ramya-rao-a It should, but the current situation is already as complicated as it is.

It should look good for those who haven't enabled Preview SCM, which it does. And it will look good once I drop the classic Git experience.

**Comment by ramya-rao-a** [comment]
got it
