### ISSUE TITLE
Suggest widget shows different suggestions when narrowing vs otherwise

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#211364]
Testing #210394

1. Type `Get-Da` and notice the following suggestions (suggest widget automatically comes up due to the `-`):

<img width="538" alt="image" src="https://github.com/microsoft/vscode/assets/22350/6a11cf3b-8897-4898-a37f-e3c92ba7d57c">

2. Press <kbd>Escape</kbd> to close the widget.
3. Press <kbd>Ctrl Space</kbd> to open it again.

🐛 Only one suggestions is shown:

<img width="563" alt="image" src="https://github.com/microsoft/vscode/assets/22350/640b44ab-7f26-4f6e-b2a3-e5d207773277">

**Comment by Tyriar** [comment]
This is fixed now

**Comment by rzhao271** [comment]
I don't get Get-Date as a suggestion now. When I type G, I only get two suggestions:

![Global and gulpfile are the only terminal widget suggestions](https://github.com/user-attachments/assets/b2ba0207-6817-4bc9-9c72-7099c2b8e7f7)

**Comment by Tyriar** [comment]
@rzhao271 try re-creating the terminal, you might have restarted vscode and reconnected? https://github.com/microsoft/vscode/issues/216818
