### ISSUE TITLE
Copilot Rename Suggestions Progress Bar

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#211352]
It would be great to have a progress bar in the rename suggestion widget when suggestions are being fetched to show progress is being made.

This is how commit message generation is doing this
![Code_-_Insiders_y5OlRi6cJN](https://github.com/microsoft/vscode/assets/44439583/994264db-b291-4449-9e3a-096f609f95b2)

This is how Rename suggestion is now
![Code_-_Insiders_7sVo3ArgmN](https://github.com/microsoft/vscode/assets/44439583/a118941d-068f-454b-9ef2-0f55d6b1d7c6)

**Comment by ulugbekna** [comment]
duplicate https://github.com/microsoft/vscode-copilot/issues/5260
