### ISSUE TITLE
Mac address in telemetry opt-in in stead of opt-out

### ISSUE THREAD

**Issue by icazemier** [microsoft/vscode#211366]
Hi all,

I stumbled up on this ticket and noticed I got a `.mono` directory in my project containing a file with a key referring to a `mac.address` all of a sudden. Originating from the : https://github.com/dotnet/vscode-dotnet-runtime plugin for vscode. 

See below:
![telemetry-privacy-opt-in-not-opt-out](https://github.com/microsoft/vscode/assets/64091093/f63af37c-1ebc-4ea5-8e32-bfe86cef21a6)

I installed VSCode like 2 years ago on this machine, and wasn't asked for permission ("opt-in") from that moment on.

VSCode should not assume one is ok in sending stuff all over the web. Just do not do this...

Please respect privacy and allow people to opt-in, in stead of opt-out 🙏🏼

Now I need to be aware every time I install some add-on in vscode to switch it off before connecting the internet ;) (which is hard).

>              Hi Matthew,
>
>Thanks for reaching out – sorry this took a few days to bubble up to the top after the long weekend.
>
>We use the data that VS Code gathers to provide and improve the product.  For example, in the past, we’ve used the data we collected to isolate several hard to track down sources of crashes and performance regressions.   VS Code may use the hashed MAC address to identify a machine over time.  For example, we may use the hashed MAC address to identify a particular machine experiencing an unusually high number of crashes (which would skew our crash result information).  You are right that we could correlate a machine across data streams, but that’s not how we use it -- we use the unique system information to connect things like crash reports with feature use.
>
>When we first launched VS Code we didn’t allow people to opt out of this collection of data because it was a pre-release product and we were trying to understand if the product was actually useful and had the right mix of features.  As a fully released and supported product from Microsoft, we now let users opt out of providing data -- if users don’t want to provide us with data, then they can [opt out](https://code.visualstudio.com/Docs/supporting/faq#_how-to-disable-telemetry-reporting) but we really appreciate it when we do receive the telemetry as it helps improve the product for all.  That’s said, we want to ensure users have adequate control.
>
>I’d be happy to chat with you on this issue and the points you raise.  I think the easiest way to do that is to connect on email/skype/hangout … I’m smcbreen@microsoft.com.
>Sean
>
_Originally posted by @seanmcbreen in https://github.com/microsoft/vscode/issues/8688#issuecomment-231487752_

**Comment by roblourens** [comment]
Could you file this on the repo that you identified? This doesn't come from VS Code itself. I don't know anything about that file specifically, but it doesn't necessarily look like it's being sent as telemetry to me.
