### ISSUE TITLE
Json Schema Slow and Throwing error with intellisense and validation

### ISSUE THREAD

**Issue by MuhammedKalkan** [microsoft/vscode#211341]
### Monaco Editor Playground Link

https://t.ly/RFBVh

### Reproduction Steps

We are trying to use intellisense and validation with our schema in VSCode. However, after a few nested json children, intellisense and validation slows down leading to high CPU usage and then no suggestion in VSCode editor when schema is added in settings for json files. 

Like: 

`"json.schemas": [
    {
      "fileMatch": [
        "*.json"
      ],
      "url": "file:/../schema.json"
    }
  ]`

Also, monca editor is giving the error shown as below, added for more context

Add this schema and try to create a nested json

[schema.json](https://github.com/microsoft/vscode/files/15108963/schema.json)

![image](https://github.com/microsoft/monaco-editor/assets/19736494/c7058a73-84d8-4887-be13-543960cd97ce)

### Actual (Problematic) Behavior

Intellisense is slowing down and not recommending anymore

![Animation](https://github.com/microsoft/monaco-editor/assets/19736494/dd4d20fe-e7b1-4492-a880-4aa3d44a6603)

### Expected Behavior

It should behave always the same, as fast as the initial code sensing and validation

### Additional Context

We are using the intellisense and json validation for our users to create a correct json file

**Comment by aeschli** [comment]
You have a recursive schema that goes across resources. The current code can not handle that and I don't think we will look at that any time soon.
If that's an option for you, I recommend you to move all in one file.

**Comment by MuhammedKalkan** [comment]
Using definitions in a single file and referring to them in the can' t be also handled because attached json file is in that structure same file

**Comment by aeschli** [comment]
But now, with the updated schema (all in one file) thing seem to work:
![image](https://github.com/microsoft/vscode/assets/6461412/8a8bf6b5-839f-40ec-ad97-70e9232a8138)


What's not working for you?

**Comment by MuhammedKalkan** [comment]
As the children increase it gets slower. And when trying to type 4th nested children it crashes with the callstack error

**Comment by aeschli** [comment]
Ah I see, I take it back, I see the same problem....
