### ISSUE TITLE
Context menu grouping is broken

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode#211488]
Does this issue occur when all extensions are disabled?: No, issue is with extension contributed context menus.

- VS Code Version: 1.89.0-insider 2fb3fa8dd2f85d7f452066f8a64e8bf259d21412
- OS Version: Mac OS X 10_15_7 (ARM)

Steps to Reproduce:

1. Open a context menu in Stable and compare it to the same menu in Insiders. I verified the issue reproduces for multiple extensions including GitLens.

Stable:
<img width="424" alt="image" src="https://github.com/microsoft/vscode/assets/12476526/acaf97a2-fb7c-480c-8de3-dfe01899fba1">

Insiders:
<img width="420" alt="image" src="https://github.com/microsoft/vscode/assets/12476526/1acf28b7-290e-47b9-95bf-349a3a77bd61">

**Comment by bpasero** [comment]
If this is a confirmed regression, it would help to know which change caused it. We maintain a node.js based CLI tool  [`vscode-bisect`](https://github.com/microsoft/vscode-bisect) that automatically downloads and runs previous VS Code insiders and asks for each build if the issue reproduces. It takes up to 8 steps to find exactly the build that caused the regression.

**Steps:**
* install [node.js](https://nodejs.org/en/download) (if not yet done)
* `npx --yes @vscode/vscode-bisect@latest`
* follow the instructions until you found the offending build (its fine to leave the commit empty)
* report back the commit range in this issue

Thanks!

**Comment by bpasero** [comment]
Bisect points to https://github.com/microsoft/vscode/compare/063d715c4504380317f9ca8eefc602d71e56adb5...9cae075e983bed1020eaba0ed4deb2e9b8d71d39

My money would be on https://github.com/microsoft/vscode/commit/7b1acd91466e0be4be50629623b3902c4d5ddefa
