### ISSUE TITLE
Allow the `provideCompletionItems` method to exist with `triggerCharacters` parameters as optional instead of being mandatory.

### ISSUE THREAD

**Issue by LuisCaceres** [microsoft/vscode#211411]
Allow the `provideCompletionItems` method to exist with `triggerCharacters` parameters as optional. In that case, alphanumerical characters are also triggers for code completion by default.

I'm not sure whether this is a bug or a feature. I'll treat it as a feature for now. Anyway, I'm currently using the `provideCompletionItems` method for a VS Code Extension which seems to require at least 1 non-alphanumerical character as a trigger. This is the `triggerCharacters` parameter of that same method. However, that doesn't align with how VS Code works out-of-the-box with code completions from IntelliSense. At least not in a JavaScript file. For example, as soon as you type the character "d" in a JavaScript file, out-of-the-box code completions are already suggested (for example, "debugger"). On the other hand, if I write my own VS Code Extension and I want my own code completions, it seems that I must specify a non-alphanumerical character as a trigger (for example, "/"). What I'd like to do is to allow completions without having to rely on a trigger character that isn't alphanumerical. For example, if I type the letter "a" within a single-line comment then my VS Code Extension can retrieve a list of identifiers in that file that start with the letter "a".

Thank you.

**Comment by RedCMD** [comment]
`"wordPattern"` under `language-configuration.json` is used for triggering intellisense

by default the`standardTokenType`; `string` and `comment` disables auto triggers
this can be changed with `editor.suggest` iirc

ctrl+space will always bring up intellisense (`manual`)

**Comment by jrieken** [comment]
There is two features

1. IntelliSense as you type aka quick suggestions which starts IntelliSense when typing at word ends (setting: `editor.quickSuggestions`)
2. Trigger character which starts IntelliSense when typing other characters, like `.` (setting: `editor.suggestOnTriggerCharacters`)

Both features have their own settings and can be enabled/disabled individually. Therefore we do not allow trigger characters that are also "word ends", e.g the rules for quick suggest are strong than those for trigger characters.
