### ISSUE TITLE
Can you improve markdown.copyFiles.destination in settings?

### ISSUE THREAD

**Issue by zhongqianli** [microsoft/vscode#211431]
I read the guide in https://code.visualstudio.com/Docs/languages/markdown ,  try to change markdown.copyFiles.destination by add 
```
"markdown.copyFiles.destination": {
  "docs/**/*": "images/${documentBaseName}/"
}
```
It can work in "./docs", when I copy image to markdown file, it save to the directory "images/${documentBaseName}/".
I need work in "./", so I change it to:
```
"markdown.copyFiles.destination": {
  "./**/*": "images/${documentBaseName}/"
}
```
but it failed, when I copy image to markdown file, it save to the directory "./" rather than "images/${documentBaseName}/".

**Comment by mjbvz** [comment]
What are you trying to accomplish? `./` isn't supported on destination source as there's nothing relative to resolve it to. If you want to match everything, just use `*` or `**/*`

**Comment by mjbvz** [comment]
Closing for now but open to PRs improving the setting description
