### ISSUE TITLE
jsdoc completions everywhere?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21147]
* have a TypeScript file
* trigger IntelliSense on an empty line
* 🐛 jsdoc-comment is suggested...

![feb-22-2017 15-59-14](https://cloud.githubusercontent.com/assets/1794099/23216949/fb73ad8a-f917-11e6-8de5-b6107c92d857.gif)

```ts



class Foo {
    search(items) {
        var urls = items.map(Foo.initHistoryItem); // <-- ctrl+click here
    };
    static initHistoryItem(hi) {
        hi.info = new URL(hi.url);
        return hi;
    };
};

console.log();

console.log();

console.log();



/**
 *
 * @param a
 * @param b
 */
function doit(a: number, b: typeof document | boolean): boolean {
    return true;
}

interface I {
    x: number;
}

/**
 * ???
 */



/**
 * Doc comment, doc comment, doc comment
 */
class RedSquiggly implements I {

    /**
     * Foo Bar, Far Boo
     */
    readonly x = 123;
    readonly x1 = 123;
    readonly x2 = 123;
    readonly x3 = 123;
    readonly x4 = 123;

    test_name = true;
}



interface FooOption {
    /**
     * Doing boo stuff
     */
    boo(x: number): boolean
}


let url = `http://***/_api/web/lists/GetByTitle('Teambuildingaanvragen')/items`;



```

**Comment by mjbvz** [comment]
@jrieken I've tried to make the new jsdoc completion function somewhat like the old jsdoc snippet did. The snippet allowed completing on empty lines, not just before functions or other documentable elements.

That said, I've been tweaking how often this completion shows up. It should only show up on lines where there is only whitespace before the cursor OR if you are inside a potential jsdoc comment, such as `abc/**| */efg`

Please let me know if you see this completion in any other strange places and I'll investigate

**Comment by jrieken** [comment]
Well, ideal would be to use the typescript parser and check with the syntax tree if the current offset is in good proximity of a jsdoc-receiver (method, class, property, function etc). Running just the parser for a single file shouldn't kill perf (cap it at 10000 lines or so). That also has the advantage of exactly knowing what to replace when inserting the full comment

**Comment by mjbvz** [comment]
@jrieken I believe we do want the jsdoc completion to be available in other contexts as well, in which case it functions just like the old jsdoc snippet. This is by design

I've further tweaked when the completion item will show up, so please give the current code in master a try and let me know if you notice any specific places where the jsdoc completion item shows up when it should not

**Comment by jrieken** [comment]
Yeah, like this sample for instance

![feb-24-2017 09-41-36](https://cloud.githubusercontent.com/assets/1794099/23296462/79e03298-fa75-11e6-96e3-df5230744104.gif)

I know that snippets are stupid but that's not on purpose but a technical limitation which doesn't allow snippets to express in which context they want to be showing. We have issues complaining about this and our suggestion is to then implement a completion item provider which can be smart.
