### ISSUE TITLE
Official way to prevent the explorer panel opening every time I switch active editor tabs?

### ISSUE THREAD

**Issue by allordacia** [microsoft/vscode#211489]
Would love LOVE there to be an officially supported way to stop the explorer panel from re-opening each and every time I switch between active editor tabs. If I minimize while working on file A, it should be an option to keep it minimized when switching to file B. This causes so much needless time wasting by having to re-minimize it constantly.

**Comment by IllusionMH** [comment]
Have you tried setting `"explorer.autoReveal": false`?

**Comment by allordacia** [comment]
Yes, unfortunately it does not work. I have an extension that helps with the issue but the best that it does is allow the side panel to open but immediately close again.

**Comment by lramos15** [comment]
I don't seem to have this problem, can you tell me if I'm missing any repro steps 
![Recording 2024-04-29 at 07 48 29](https://github.com/microsoft/vscode/assets/4544166/9cbd94de-3d8b-4f24-858f-7a07fe6c218d)

**Comment by allordacia** [comment]
@lramos15 thank you for taking the time to test on your end. This at least confirms the issue is on my end and probably the result of a plugin causing this to happen. I am going to start turning them off to see if I can isolate which one is causing my hair to grey faster than it naturally does.

**Comment by lramos15** [comment]
`F1 -> Troubleshoot issue` might be helpful
