### ISSUE TITLE
TypeScript cannot resolve correct overload

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#21140]
while testing #21004:

In my hello world extension I just replaced the showInformationMessage by this:
```js
        vscode.window.showWarningMessage('hello world', { modal: false },
             { title: 'hello', isCloseAffordance: true },
             { title: 'world', isCloseAffordance: true }
        );
```
This works fine and TS does not show an error.

Then I changed the first 'isCloseAffordance' to 'false:
```js
        vscode.window.showWarningMessage('hello world', { modal: false },
             { title: 'hello', isCloseAffordance: false },
             { title: 'world', isCloseAffordance: true }
        );
```

Now I get this TS error:
![2017-02-22_15-33-29](https://cloud.githubusercontent.com/assets/1898161/23215894/467f16c4-f914-11e6-8155-3401b1999a58.png)

So TS can no longer infer the correct overload for showWarningMessage.
Adding an explicit generic typ parameter fixes that: 
```js
        vscode.window.showWarningMessage<vscode.MessageItem>('hello world', { modal: false },
             { title: 'hello', isCloseAffordance: false },
             { title: 'world', isCloseAffordance: true }
        );
```

I would expect that TS does not complain in this case.

**Comment by mjbvz** [comment]
This is not VSCode specific and is the expected behavior for TypeScript here.

For the code:

```ts
 vscode.window.showWarningMessage('hello world', { modal: false },
             { title: 'hello', isCloseAffordance: false },
             { title: 'world', isCloseAffordance: true }
        );
```

The type of of `{ title: 'hello', isCloseAffordance: false },` is `{ title: string, isCloseAffordance: false }`. This becomes the inferred type `T` in `showWarningMessage`. However, the type of `   { title: 'world', isCloseAffordance: true }`  is ``{ title: string, isCloseAffordance: true }` which TypeScript cannot match with `T`.

Two possible fixes:

```ts
 vscode.window.showWarningMessage('hello world', { modal: false },
             { title: 'hello', isCloseAffordance: false as boolean },
             { title: 'world', isCloseAffordance: true }
        );
```

```ts
 vscode.window.showWarningMessage<MessageItem>('hello world', { modal: false },
             { title: 'hello', isCloseAffordance: false },
             { title: 'world', isCloseAffordance: true }
        );
```

**Comment by weinand** [comment]
@jrieken @joaomoreno this TS "feature" results in an awkward API usage experience. I had no idea what was going on and had to ask for help...

**Comment by jrieken** [comment]
I'd say this is very bogus because the `MessageItem` is defined like this

```ts
	export interface MessageItem {
		title: string;
		isCloseAffordance?: boolean;
	}
```

So, because `isCloseAffordance` is defined as boolean I expect it to be a boolean. Otherwise it doesn't make sense that `title` is valid because the type can be made more strict by inferring `title: 'hello'` instead of `title: string`.

@mhegazy can you clarify?

**Comment by mhegazy** [comment]
@mjbvz analysis is accurate. `boolean` is just an alias to `true | false`. when the compiler is inferring for type `T`, it pick us `{title: string, isclosedAffordance: false}` as the type of the first argument, then `{title: string, isclosedAffordance: true}` for the second, where `true` and `false` are not compatible. so you either need to specify the type argument explicitly or cast to `boolean` as @mjbvz noted.

alternatively, the declaration can be changed to drop the generic type parameter and just use `MessageItem`.

**Comment by weinand** [comment]
@mhegazy does the same logic apply to the type `number`as well? Would the use of two different values `0` and `1` result in the same problem?

**Comment by mhegazy** [comment]
No. but it would have applied to unions of literal types of numbers. e.g. `1 | 2`

**Comment by jrieken** [comment]
@mhegazy So that the fact that `T` is defined as `T extends MessageItem` and that `MessageItem` defines `isCloseAffordance` as `boolean` is ignored?

**Comment by mhegazy** [comment]
The fact that it is boolean tells the compiler to try and figure a more specific type, in this case true then false; then it is left with two infrances that do not match.

Think of f<T extends boolean>(t: T): T; you want the output to be 'false' if the input was 'false' and not just boolean.
