### ISSUE TITLE
action buttons in modal messages are flipped

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#21148]
while testing #21004:

In the modal case, the buttons 'hello' and 'world' appear in a different order in the alert as in the non-modal case.

I'm using the following snippet. Just flip the value of 'modal':
```ts
        vscode.window.showWarningMessage<vscode.MessageItem>('hello world', { modal: true },
            { title: 'hello', isCloseAffordance: true },
            { title: 'world', isCloseAffordance: false }
        );
```

**Comment by joaomoreno** [comment]
Each OS will do what is best for its own platform.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
