### ISSUE TITLE
cannot copy with editor drap and drop 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21145]
* open editor
* select text and drag
* press Alt-key
* drop text somewhere
* 🐛 text is moved, not copied which pressing Alt while dragging means (at least on mac)

**Comment by rebornix** [comment]
I didn't touch this part yet as `alt` is multi-cursor related. It requires careful testing against edge cases so let's not rush it in this iteration. 

As we try to mimic the browser behavior, this one is a good feature request.

**Comment by Spown** [comment]
👎 in favor of #21862. ctrl+d&d is more conventional.

**Comment by ffes** [comment]
As said in #21862 

Apparently on a Mac you use the Alt-key when copying. On Windows it is the Ctrl-key.

Maybe the labels can be updated for this issue as this is not a 'mac' only issue

And in that issue I suggested to adjust the mouse cursor while dragging, similar to what Word does.

**Comment by Tekbr** [comment]
[#21862](https://github.com/Microsoft/vscode/issues/21862#issuecomment-283978507)

-- Sorry for the English, I used Google Translator --

Allow to DragAndDrop content to another VSCode tab and to other programs. This is currently not possible. (Without having to click Ctrl)

By clicking Ctrl it would only copy within the same file, right?

**Comment by rebornix** [comment]
Since pressing Alt key first and then clicking on a selection might have special meaning later on (eg, aligning column select with Sublime), right now to use this feature:

* Click on a selection and start dragging
* Press Alt and hold 
* Drop. The selected text is pasted into the editor without cutting old selection.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@rebornix Sorry, but that's not much practice.

Another thing I'm a Windows user and `Ctrl` is better than `Alt`. I think it is possible to do a check of which operating system.


It would not have like him to interpret by pressing `Ctrl` (please change this in Windows) and click and start dragging it?


Another thing .. I still can not drag and drop to another VSCode tab or to another program. Is this in another issue?

**Comment by litera** [comment]
This should definitely be implemented as OS specific feature.

On a Mac one uses <kbd>Alt</kbd> while dragging/dropping selection, but on Windows <kbd>Ctrl</kbd> is used for the same purpose. It **can't simply be unified** for both systems as that will be very confusing for users.

**Comment by rebornix** [comment]
Yes gentlemen, it's Ctrl on Windows now ;) thanks for your feedback.

**Comment by Tekbr** [comment]
@rebornix  

> Another thing .. I still can not drag and drop to another VSCode tab or to another program. Is this in another issue?

**Comment by rebornix** [comment]
@Tekbr that's actually another feature request, thanks!
