### ISSUE TITLE
CSS "Unknown at rule @container" when nested

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode#211464]
Type: <b>Bug</b>

The CSS language support errrors with an `unknownAtRule` error when `@container` is nested inside a selector. The same error is not shown when `@container` is used at the top level:

This is fine:
```css
.selector {
  background: blue;
}

@container (width < 500px) {
  .selector {
    background: red;
  }
}
```

While this errors, even though it is valid CSS:

```css
  .selector {
    background: blue;

    @container (width < 500px) {
/*  ~~~~~~~~~~ Unknown at rule @container  css(unknownAtRules) */
      background: red;
    }
  }
```

On the other hand, nesting works fine for `@media` without any errors.

VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin arm64 23.4.0
Modes:
Remote OS version: Linux x64 6.2.0-1019-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (5.69GB free)|
|Process Argv|--crash-reporter-id beb5ee6d-4e31-45a3-8f59-f51db6d8f411|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: stunning succotash|
|OS|Linux x64 6.2.0-1019-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (32 x 2800)|
|Memory (System)|125.78GB (117.81GB free)|
|VM|0%|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.3
codespaces|Git|1.16.19
remotehub|Git|0.62.0
vscode-graphql-syntax|Gra|1.3.5
css-nesting-syntax-highlighting|jac|0.1.0
endwise|kai|1.5.1
remote-containers|ms-|0.361.0
azure-repos|ms-|0.38.0
remote-repositories|ms-|0.40.0
material-icon-theme|PKi|5.1.0
vscode-ruby|win|0.28.0
comment-tagged-templates|bie|0.3.3
markdown-mermaid|bie|1.22.0
vscode-css-modules|cli|0.5.1
erb|Cra|0.0.1
vscode-eslint|dba|2.4.4
gitlens|eam|14.9.1
vscode-command-runner|edo|0.0.124
prettier-vscode|esb|10.4.0
vscode-byebug|eth|0.1.2
codespaces|Git|1.16.19
octoclip|git|0.0.1
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.86.1
go|gol|0.41.4
vscode-graphql-syntax|Gra|1.3.5
packwerk-vscode|Gus|0.0.5
vscode-codeowners|jas|1.1.1
ctags-support|jay|1.0.22
endwise|kai|1.5.1
vnc-extension|kin|0.0.7
vscode-rdbg|Koi|0.2.2
css-converter|Lak|0.2.4
ruby-rubocop-revived|Lor|0.9.5
erb-linter|man|0.0.9
rainbow-csv|mec|3.11.0
relay|met|2.1.0
ruby-symbols|mig|0.1.8
ruby-rubocop|mis|0.8.6
vscode-azurefunctions|ms-|1.14.1
vscode-azureresourcegroups|ms-|0.8.6
vscode-azurestaticwebapps|ms-|0.12.2
vscode-docker|ms-|1.29.0
vscode-dotnet-runtime|ms-|2.0.3
playwright|ms-|1.0.22
debugpy|ms-|2024.4.0
anycode-rust|ms-|0.0.6
azure-account|ms-|0.11.6
js-debug-nightly|ms-|2024.4.2417
live-server|ms-|0.4.13
remote-repositories|ms-|0.40.0
vsliveshare|ms-|1.0.5918
resourcemonitor|mut|1.0.7
vscode-jest|Ort|6.2.4
vscode-versionlens|pfl|1.9.2
cssvar|pho|2.6.4
material-icon-theme|PKi|5.1.0
ruby|reb|0.28.1
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
cadquery|roi|0.1.3
sorbet-vscode-extension|sor|0.3.33
vscode-styled-components|sty|1.7.8
vscode-stylelint|sty|1.4.0
vscode-mdx|uni|1.8.3
vscodeintellicode|Vis|1.3.1
codetour|vsl|0.0.59
vscode-alternate-file|wil|0.3.1
vscode-ruby|win|0.28.0
pretty-ts-errors|Yoa|0.5.4

(2 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode-css-languageservice/issues/389
