### ISSUE TITLE
window.createWebviewPanel vscode.ViewColumn.Two opens webview in floating panel instead of currently focused window.

### ISSUE THREAD

**Issue by gdomingu** [microsoft/vscode#211491]
Does this issue occur when all extensions are disabled?: Can only test with extension.

- VS Code Version: 1.88.1 (Universal)
- OS Version: Mac OS 14.4.1 (23E224)

Steps to Reproduce:

1. Clone https://github.com/microsoft/vscode-extension-samples/tree/main/webview-sample
2. Update [this line](https://github.com/microsoft/vscode-extension-samples/blob/main/webview-sample/src/extension.ts#L77) to be `vscode.ViewColumn.Two`,
3. Run `npm install` then `npm run watch` and finally `F5` to open the sample in a new window.
4. In the new [Extension development host] window, drag a tab out of the window so it floats.
5. Go back to the original vscode [Extension development host] window.
6. Run the `Cat coding: start cat coding session` command. 
7. See the webview panel with the cat gif open in the floating window, not in the focused window.

Note: works as expected when `viewColumn` option is `vscode.ViewColumn.One`. But `vscode.ViewColumn.Two` creates the issue.

![Image of webview panel in floating window](https://github.com/microsoft/vscode/assets/4443635/fe196b6b-4ff1-43ce-9861-3c5158a2bd1e)

cc: @mjbvz

**Comment by bpasero** [comment]
@gdomingu I think there is a misunderstanding here: editor groups are counted across floating windows, so the floating window will be editor group two. Using `vscode.ViewColumn.Two` will make it open in the second editor group, which is the floating window.

In other words: floating windows are really not special from an editor layout point of view, they just extend the editor groups beyond windows.

**Comment by gdomingu** [comment]
Closing if that is correct behavior.
