### ISSUE TITLE
Tunnels don't work on Windows on Insiders

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#211497]
1. Be on Windows
2. Run `code tunnel` and connect from a browser
3. Depending on the context in which you started code tunnel, you may see an "access denied" error from the CLI trying to spawn the server

**Comment by rzhao271** [comment]
Reopening. The current RC doesn't contain the fix, meaning what actually happened is I couldn't repro the issue.

**Comment by connor4312** [comment]
Closing for verification now that Insiders is out
