### ISSUE TITLE
Debugging python file

### ISSUE THREAD

**Issue by Rakeki** [microsoft/vscode#211485]
Type: <b>Bug</b>

# Behaviour

When trying to debug F5, the first execution will work fine, its almost as if the python execution doenst shut down, the first debug command is:

JL@dPc MINGW64 /d/Dev/TerminalNotey
$  /usr/bin/env c:\\Python312\\python.exe c:\\Users\\JL\\.vscode\\extensions\\ms-python.debugpy-2024.4.0-win32-x64\\bundled\\libs\\debugpy\\adapter/../..\\debugpy\\launcher 52188 -- D:\\Dev\\TerminalNotey\\main.py 

then when you execute again using the same terminal here is the command and error:

JL@dPc MINGW64 /d/Dev/TerminalNotey
$ on312\\python.exe c:\\Users\\JL\\.vscode\\extensions\\ms-python.debugpy-2024.4.0-win32-x64\\bundled\\libs\\debugpy\\adapter/../..\\debugpy\\launcher 52197 -- D:\\Dev\\TerminalNotey\\main.py
bash: on312\python.exe: No such file or directory
## Steps to reproduce:

This has happened on multiple of the development machines and environments, both windows and Linux.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.2
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Unknown<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700F (20 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (7.28GB free)|
|Process Argv|--crash-reporter-id ce4da0a9-c7dc-440d-9fc0-4fe541b0a7e2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
c-cpp-makefile-project|adr|1.1.0
vscode-django|bat|1.15.0
color-info|bie|0.7.2
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
auto-rename-tag|for|0.1.10
output-colorizer|IBM|0.1.2
vsc-python-indent|Kev|1.18.0
dotenv|mik|1.0.1
debugpy|ms-|2024.4.0
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
jupyter|ms-|2024.3.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.354.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
vsliveshare|ms-|1.0.5918
autodocstring|njp|0.6.1
material-icon-theme|PKi|5.1.0
errorlens|use|3.17.0
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
showvideot:31016892
chatpanelt:31018789
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31022790

```

</details>

**Comment by roblourens** [comment]
Please file on the repo for the python extension
