### ISSUE TITLE
Clicking on a Node ESM backtrace file URI in terminal does not jump to file; tries to navigate to URI with a missing slash

### ISSUE THREAD

**Issue by jakebailey** [microsoft/vscode#211412]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Cause an error stack trace with Node ESM. For example:
```
file:///home/jabaile/work/TypeScript/built/local/tsc.mjs:27
  throw Error('Dynamic require of "' + x + '" is not supported');
        ^

Error: Dynamic require of "fs" is not supported
    at file:///home/jabaile/work/TypeScript/built/local/tsc.mjs:27:9
    at getNodeSystem (file:///home/jabaile/work/TypeScript/built/local/tsc.mjs:4915:17)
    at file:///home/jabaile/work/TypeScript/built/local/tsc.mjs:5346:12
    at file:///home/jabaile/work/TypeScript/built/local/tsc.mjs:5352:3
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.12.2
```
2. Ctrl+click on one of the files
3. It goes nowhere, instead opening a prompt with a URI missing a leading slash.

For example, I highlighted the URL here by holding Ctrl:

![image](https://github.com/microsoft/vscode/assets/5341706/c3a2dfa6-51c0-4903-8fce-7c6c81558b93)

It's all linked; the entire thing. But clicking it opens this:

![image](https://github.com/microsoft/vscode/assets/5341706/6906a1d4-27a0-460c-85e5-ab4ea9e9ad1b)

**Comment by Tyriar** [comment]
I'm a little confused by the fact this is Windows and the `/home` path. If you're SSH'd into a machine in your terminal this is by design currently unless you're connected to the remote via Remote - SSH.

**Comment by jakebailey** [comment]
@Tyriar this is WSL, which should have full access to everything regardless of which side of the OS wall you're on.
