### ISSUE TITLE
Markdown: show "open the external website" alert only when URL is actually clicked not on hover

### ISSUE THREAD

**Issue by WebMechanic** [microsoft/vscode#211433]
Type: **Feature Request**

If the mouse pointer is (accidently) hovering over a URL in a Markdown document, pressing CTRL (Windows) to perform another command where the actual **input cursor** is positioned, always triggers the "Do you want Code to open the external website" depite neither the URL under the mouse pointer itself was clicked nor was the "Follow Link" popup.
![image](https://github.com/microsoft/vscode/assets/638340/00fde5ad-c7a8-4e94-b087-af9e42349560)

In this scenario the text "Kirby CMS Panel Vue GUI" was selected to make it bold using the `Ctrl+B` shortcut. The mouse pointer was hovering over a URL a few lines further down. 
It turned blue the second I press CTRL and the alert box prevents me from performing my intended task, to make bold text.
This happens constantly as I shove the mouse away and it ends up hovering a URL somewhere else in the document.

**The "Do you want Code to open the external website" confirmation alert should only appear if a URL was actually "Ctrl-Clicked" similar to the "Follow Link" tooltip and NOT if only the CTRL key is pressed in order to perform a command unrelated to the URL under the mouse pointer.**

If one has a document wil loads of URLs this becomes increasingly annoying because there's a very good chance the mouse pointer will be hovering over any URL at any give time.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by jrieken** [comment]
Doesn't reproduce for me

**Comment by WebMechanic** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

extensions... right... I totally forgot. 
Sorry!

It seems like the culprit is indeed an extension: disabling all "fixes" the issue.
**I'll do a bisect** to find out which one's causing this and report in their repo if needed.

Thank you for your time!
