### ISSUE TITLE
JS/TS Language features constantly crashes

### ISSUE THREAD

**Issue by tobi110289** [microsoft/vscode#211467]
Type: <b>Bug</b>

Have a big repo with a lot of types, infering them from zod objects

VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|64.00GB (2.34GB free)|
|Process Argv|--crash-reporter-id 34a03ddc-92c3-4f5a-af80-148d70885aa4 --crash-reporter-id 34a03ddc-92c3-4f5a-af80-148d70885aa4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
path-intellisense|chr|2.8.5
vscode-eslint|dba|2.4.4
prettier-vscode|esb|10.4.0
gc-excelviewer|Gra|4.2.59
i18n-ally|lok|2.12.0
copy-json-path|Mal|1.3.0
vscode-language-babel|mgm|0.0.40
dotenv|mik|1.0.1
vscode-docker|ms-|1.29.0
remote-containers|ms-|0.354.0
color-highlight|nau|2.8.0
material-icon-theme|PKi|5.1.0
vscode-yaml|red|1.14.0
crates|ser|0.6.6
code-spell-checker|str|3.0.1
tabnine-vscode|Tab|3.96.0
even-better-toml|tam|0.19.2
pretty-ts-errors|Yoa|0.5.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31022790

```

</details>

**Comment by MaximBuz** [comment]
bump

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by tobi110289** [comment]
@mjbvz I tried, and it first seemed to be better, but the crashes are still quite persistent.

VS Code version: Code - Insiders 1.90.0-insider (Universal) (a1f2ea3162c704a5890c35dde4df6ee46283d957, 2024-05-03T05:49:50.917Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|8, 6, 6|
|Memory (System)|64.00GB (0.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
vscrpc:30624061
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
ccp1r6:30958151
pythonait:30973460
showvideot:31016890
chatpanelt:31014475
g316j359:31013175
pythoncenvpt:31022790
a69g1124:31018687
88717513:31021561
dvdeprecation:31036532
pythonprt:31036556
dwnewjupyter:31035176

```

</details>
