### ISSUE TITLE
The lock on my window is gone

### ISSUE THREAD

**Issue by hdthhh** [microsoft/vscode#211423]
Type: <b>Bug</b>

HELP！Previously, there was a lock sign that could lock the input scroll, but now it's gone
![image](https://github.com/microsoft/vscode/assets/100888871/a57da780-b308-4dc3-a1f6-35ec7c927da6)

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12500H (16 x 3110)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (5.63GB free)|
|Process Argv|--crash-reporter-id 42e6fa45-c1f3-44cc-8f08-102e5525dbdf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.5
cssrem|cip|3.1.1
jquerysnippets|don|0.0.1
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
codespaces|Git|1.16.19
vscode-gutter-preview|kis|0.30.0
vscode-fix-checksums|leh|1.1.0
background-cover|man|2.3.6
easy-less|mrc|2.0.0
vscode-docker|ms-|1.29.0
vscode-language-pack-zh-hans|MS-|1.88.2024041009
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
vue-vscode-snippets|sdr|3.1.1
js-jsx-snippets|sky|11.1.3
language-stylus|sys|1.16.0
open-in-browser|tec|2.0.0
volar|Vue|2.0.8
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31022790

```

</details>

**Comment by gjsjohnmurray** [comment]
Is the option on the ... menu?

**Comment by hdthhh** [comment]
No, I tried all sorts of things, and finally reinstalled it and it came back

**Comment by yume-chan** [comment]
![image](https://github.com/microsoft/vscode/assets/1330321/32ae5074-240e-44c3-95f4-4307220062e6)

Right click on `...` and select `Toggle Auto Scrolling`
