### ISSUE TITLE
Wrong syntax colouring for the number 7 in Visual Basic

### ISSUE THREAD

**Issue by SeamusConacher** [Microsoft/vscode#21155]
- VSCode Version: 1.9.1
- OS Version: Windows 10 Pro 1607

Steps to Reproduce:

1. Declare a Dim or Const in Visual Basic with the Visual Basic syntax colouring
2. Set it equal to any number that does not start with 7
3. Set it equal to any number starting with 7

With any number starting with the number 7 the syntax colouring stays the variable colouring, rather than changing to the number colouring.

**Comment by aeschli** [comment]
This issue was moved to textmate/asp.vb.net.tmbundle#7
