### ISSUE TITLE
Typing still allowed while D&D operation under way

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#21156]
Testing #21012:

While dragging some text to a target location, I'm still able to type at the original position where the cursor blinks. 

Neither Sublime nor TextMate support this and I find the blinking cursor rather distracting.
I suggest to disable typing while a d&d operation is under way and to hide the blinking cursor.

In addition I find the dotted d&d cursor difficult to spot.

**Comment by rebornix** [comment]
For the dotted d&d affordance, now I use 2px border instead of 1px as it's hard to recognize a 1px dotted line.

Typing under D&D is similar to typing while selecting characters. These are handled by two different handlers and bad things happen when events for both kick in.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
