### ISSUE TITLE
Confusing icon for expanding collapsed notebook cells

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#211595]
When a few cells have been collapsed via markdown cells, 
a placeholder is displayed `> 5 cells hidden...`

The `>` in the placeholder seems to behave like an icon, hence I keep making the assumption that I can click this.
However clicking this does nothing, but double clicking will edit the header cell.

What I want is the icon to expand the collapsed cells, 

![Screenshot 2024-04-29 at 12 49 48](https://github.com/microsoft/vscode/assets/1948812/3f95af43-d683-40ea-b84e-8c224ce4c5a4)

As you can see here, when the mouse is over the `>` icon, it looks like it can be clicked.

![Screenshot 2024-04-29 at 12 49 45](https://github.com/microsoft/vscode/assets/1948812/3d74cedf-7e96-4c34-aa02-ff98843bdc1f)

**Comment by Yoyokrazy** [comment]
I think there might be some confusion around the purpose of this icon/button. This is the run button for folded sections and doesn't (shouldn't) have any control over the expansion of the folded section. This will execute any code cells within the folded section, and switch to a spinning run indicator (will change in the outline as well if you have code cells visible).

The ellipses on the right-hand side of the hint (`...`) act as the expand section icon, however there is a bug with the cursor state; it should change to the pointer to more clearly show that you can click it on its own. 

As for the run button then, I think this a bug more relating to it appearing when there are no code cells within a collapsed section. That should be an easy fix.

**Comment by rzhao271** [comment]
Moving to May
