### ISSUE TITLE
'Add configuration' opens code assist in different editor

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#21154]
Version 1.10.0-insider
Commit 256d76fed7947e7289f921df10658d7a69233b65
Date 2017-02-22T07:09:05.746Z

- open `launch.json` side-by-side with a editor showing a `foo.ts` file
- set the cursor in `foo.ts`
- click on he 'Add configuration' button in the launch.json editor
- code assist opens in `foo.ts`

![image](https://cloud.githubusercontent.com/assets/6461412/23218223/005c2008-f91c-11e6-880c-f8038393b334.png)

**Comment by isidorn** [comment]
Hehe nice catch
