### ISSUE TITLE
Custom Editor Labels:  Wrong directory for ${dirname}

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#211522]
Example file: `root/static/folder/file.txt`
- Expected: `${dirname} -> folder`
- Bug: `${dirname} -> static`

![Screenshot 2024-04-26 at 19 22 58](https://github.com/microsoft/vscode/assets/51113345/b2f0b708-b204-4c28-b3c8-7d2d0d0048a4)
![Screenshot 2024-04-26 at 19 23 12](https://github.com/microsoft/vscode/assets/51113345/b5bdb516-fbc6-46c9-b22a-4a255ff308d4)

_Originally posted by @riungemaina in https://github.com/microsoft/vscode/issues/41909#issuecomment-2079709549_

**Comment by deepak1556** [comment]
Closing for verification.
