### ISSUE TITLE
Tabs get closed

### ISSUE THREAD

**Issue by hassnaaHamdi** [microsoft/vscode#211504]
Type: <b>Bug</b>

Unfortunately I don't have specific steps to reproduce the issue.
But it happens regularly.
Some tabs get closed suddenly, I open them again, and after some time they get closed again.

VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin arm64 23.1.0
Modes:
Remote OS version: Linux arm64 5.15.0-1058-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 3, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 8def33da-0a95-4f4c-8278-e801396d8e74|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: remote-llvm|
|OS|Linux arm64 5.15.0-1058-aws|
|CPUs|Neoverse-N1 (32 x 0)|
|Memory (System)|123.06GB (117.81GB free)|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
llvm-ir|rev|1.0.5
llvm|RRe|0.2.0
doxdocgen|csc|1.4.0
gitlens|eam|14.9.1
vscode-diff|fab|2.1.2
better-cpp-syntax|jef|1.17.2
vscode-mlir|llv|0.0.11
debugpy|ms-|2024.4.0
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
jupyter|ms-|2024.3.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
partial-diff|ryu|1.4.3
graphviz-interactive-preview|tin|0.3.5
tab-groups|usa|2.1.1
vscode-lldb|vad|1.10.0
debug|web|0.27.0
change-case|wma|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
chatpanelc:31018788
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31022790

```

</details>

**Comment by benibenj** [comment]
Thanks for reporting, however, there is not much I can do with this information without repro steps. Have you tried disabling all extensions and seeing if it still happens then?

**Comment by hassnaaHamdi** [comment]
Hi Ben,
Thanks for your reply.
Sorry I didn't try that because there are a lot of extensions, but I will try that and update you :))
