### ISSUE TITLE
User setting for `extensions.unwantedRecommendations`

### ISSUE THREAD

**Issue by lgarron** [microsoft/vscode#211514]
Extension recommendations can be pretty handy. But there are some recommendations that I never want to install, because I would use them too rarely or because the feature set is not useful to me.[^1] Unfortunately, these recommendations pop up every time I open a relevant workspace/file, which means I constantly have to dismiss the same recommendations over and over.[^2]

[^1]: Also, more extensions tend to cause more buggy interactions. "You have an extension installed, and it's doing something you did not expect" is a common cause of issues filed here. There's a real incentive to run closer to stock VS Code when possible.

[^2]: One workaround is to install an extension and then immediately disable it. But it seems like an anti-pattern to install something because I… don't want it installed. I believe this also wouldn't prevent the recommendations from showing up in codespaces, whereas a settings-based solution would.

The [`extensions.ignoreRecommendations` setting](https://github.com/microsoft/vscode/pull/25038) prevents all recommendations, which certainly solves the problem. But it over-corrects so that I *never* get useful recommendations. In fact, it even suppresses project-recommended extensions in codespaces, which for some projects I *always* want to install.

`extensions.unwantedRecommendations` would be perfect to opt out of a handful of recommendations, but it is only a valid setting for workspaces. I'd love to see it made available in per-user settings as well.

**Comment by sandy081** [comment]
You can do this already using **Ignore Recommendation** action

![Image](https://github.com/microsoft/vscode/assets/10746682/4fd05d35-65c0-4ebd-8438-12c20eade743)
