### ISSUE TITLE
VS does not assign PROPER permissions to folders...

### ISSUE THREAD

**Issue by cryptosoaring** [microsoft/vscode#211594]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest lts
- OS Version: WIndows 10 WSL2

Steps to Reproduce:

1.  When I attempt to open a folder from Ubuntu terminal, the folder will open in VS code. The WSL shows in green at the lower left corner but I cannot create a file or folder in my project...........

Unable to write file 'vscode-remote://wsl+ubuntu-22.04/home/cryptosoaring/trading_bot/.env' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/home/cryptosoaring/trading_bot/.env')

I used to have it working fine. I could create files and folders in VS code.  I had to uninstall Ubuntu because I accidentally deleted some files in the parent folder.  So I reinstalled Ubuntu.  I have seen that I'm not the first person to have this problem.  I want to know the ROOT CAUSE.  I believe it is an installation issue.  It worked before....Why can't I create folders and files now?
3.

**Comment by aeschli** [comment]
We are using the default user when starting WSL.
In your case this seems to be a user called `cryptosoaring`.

Can you test that this user has write permission in the `trading_bot` folder? Maybe you checked out that repo with a different or admin user?
Run `wsl` in a window command prompt and then run `ls -al  trading_bot` to see the permissions.

**Comment by cryptosoaring** [comment]
I start Ubuntu by clicking on the Icon in my windows start menu. I didn't
not get this above from typing cmd.
cryptosoaring is the username I created when I installed Ubuntu.  It asks
for a username and pw.

So before when I dragged a folder from my windows downloads area into
Ubuntu I didn't have any issue with permissions on the folder.
Why does trading_bot say root?  It is not the root. If anything
cryptosoaring would be the root. Isn't that right?
What should I do?


Windows Subsystem for Linux is now available in the Microsoft Store!
You can upgrade by running 'wsl.exe --update' or by visiting
https://aka.ms/wslstorepage
Installing WSL from the Microsoft Store will give you the latest WSL
updates, faster.
For more information please visit https://aka.ms/wslstoreinfo


Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 5.10.102.1-microsoft-standard-WSL2
x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

This message is shown once a day. To disable it please create the
/home/cryptosoaring/.hushlogin file.
***@***.***:~$
***@***.***:~$ ls
hardhat-tutorial  trading_bot  trading_bot.older
***@***.***:~$ cd trading_bot
***@***.***:~/trading_bot$ code
***@***.***:~/trading_bot$ cd ..
***@***.***:~$ ls -al trading_bot
total 352
drwxr-xr-x 6 root          root            4096 Apr 28 21:22 .
drwxr-x--- 9 cryptosoaring cryptosoaring   4096 Apr 28 23:02 ..
-rw-r--r-- 1 root          root             218 Jan 10 07:45 .env.example
-rw-r--r-- 1 root          root             100 Jan 10 07:45 .gitignore
-rw-r--r-- 1 root          root            9872 Jan 10 07:45 README.md
-rw-r--r-- 1 root          root            9998 Jan 10 07:45 bot.js
-rw-r--r-- 1 root          root             526 Jan 10 07:45 config.json
drwxr-xr-x 2 root          root            4096 Apr 28 21:22 contracts
-rw-r--r-- 1 root          root             370 Jan 10 07:45
hardhat.config.js
drwxr-xr-x 2 root          root            4096 Apr 28 21:22 helpers
-rw-r--r-- 1 root          root          288618 Jan 10 07:45
package-lock.json
-rw-r--r-- 1 root          root             477 Jan 10 07:45 package.json
drwxr-xr-x 2 root          root            4096 Apr 28 21:22 scripts
drwxr-xr-x 2 root          root            4096 Apr 28 21:22 test
***@***.***:~$ ls -al
total 56
drwxr-x--- 9 cryptosoaring cryptosoaring 4096 Apr 28 23:02 .
drwxr-xr-x 3 root          root          4096 Apr 28 18:59 ..
-rw------- 1 cryptosoaring cryptosoaring 1316 Apr 29 10:45 .bash_history
-rw-r--r-- 1 cryptosoaring cryptosoaring  220 Apr 28 18:59 .bash_logout
-rw-r--r-- 1 cryptosoaring cryptosoaring 3968 Apr 28 19:57 .bashrc
drwxr-xr-x 3 cryptosoaring cryptosoaring 4096 Apr 28 22:55 .cache
-rw-r--r-- 1 cryptosoaring cryptosoaring    0 Apr 29 10:28 .motd_shown
drwxr-xr-x 5 cryptosoaring cryptosoaring 4096 Apr 28 23:02 .npm
drwxr-xr-x 8 cryptosoaring cryptosoaring 4096 Apr 28 19:59 .nvm
-rw-r--r-- 1 cryptosoaring cryptosoaring  807 Apr 28 18:59 .profile
-rw-r--r-- 1 cryptosoaring cryptosoaring    0 Apr 28 19:04
.sudo_as_admin_successful
drwxr-xr-x 5 cryptosoaring cryptosoaring 4096 Apr 28 21:24 .vscode-server
-rw-r--r-- 1 cryptosoaring cryptosoaring  183 Apr 28 20:10 .wget-hsts
drwxr-xr-x 5 cryptosoaring cryptosoaring 4096 Apr 28 22:55 hardhat-tutorial
drwxr-xr-x 6 root          root          4096 Apr 28 21:22 trading_bot
drwxr-xr-x 6 cryptosoaring cryptosoaring 4096 Apr 28 23:01 trading_bot.older
***@***.***:~$

**Comment by cryptosoaring** [comment]
I should say that I installed and uninstalled Ubuntu a few times. One of those times it created root as the username.  But I uninstalled this and reinstalled it again making cryptosoaring as the username.

**Comment by aeschli** [comment]
`rm -r foldeName` to remove a folder with content.
If root access is needed use `sudo rm -r folerName`.

Closing the issue. It's not an issue of the WSL extension, as the WSL extension doesn't do anything with permissions here, it just uses the default user.
