### ISSUE TITLE
Render Unicode Character u2500 not monospcaed in editor area

### ISSUE THREAD

**Issue by iceynano** [microsoft/vscode#211563]
Does this issue occur when all extensions are disabled?: Yes

I'm using Roboto Mono as my editor font, for some reason I use unicode u2500 `─` in my log output, but it looks like the character is not the same width in the editor area as it is in the terminal area.

![image](https://github.com/microsoft/vscode/assets/34570144/bc1ea6fd-a60d-4583-b9b3-6dad2b868f27)

I've tried using other monospaced fonts such as Jetbrains Mono and it doesn't reproduce the problem, so I can't pinpoint the source of the problem at all. Howerver since the Roboto Mono font behaves normally in the terminal area, I'm guessing this is due to a rendering issue in the editor area, and my other font settings in vs code is default.

Example text (I don't know how to show it in terminal area so I have to execute my program):
```
│ ╭────────────────────────────────────────── locals ───────────────────────────────────────────╮                     │
│ │ btn_idx = 0                                                                                 │                     │
│ │    btns = [{'label': 'Raise exception', 'value': 0, 'color': 'primary', 'disabled': False}] │                     │
│ │ onclick = [<function raise_exception at 0x00000200E7DE3B88>]                                │                     │
│ │  values = ['']                                                                              │                     │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────╯                     │
│                                                                                                                     │
│ F:\AzurLaneAutoScript\module\webui\utils.py:538 in raise_exception                                                  │
│                                                                                                                     │
│   535 │   For testing purpose                                                                 ╭─ locals ─╮          │
│   536 │   """                                                                                 │ x = 3    │          │
│   537 │   if x > 0:                                                                           ╰──────────╯          │
│ ❱ 538 │   │   raise_exception(x - 1)                                                                                │
│   539 │   else:                                                                                                     │
│   540 │   │   raise Exception("quq")                                                                                │
│   541                                                                                                               │
```

- VS Code Version: Code 1.88.1 ([e170252](https://github.com/microsoft/vscode/commit/e170252f762678dec6ca2cc69aba1570769a5d39), 2024-04-10T17:41:02.734Z)
- OS Version: Windows 10 22H2 19045.4291

**Comment by alexdima** [comment]
The editor delegates all font rendering to Chromium, which uses kerning and widths defined by the font for each glyph. In this case, the width of `─` is not equal to the width of other characters. This works well with fonts like inconsolata which make sure to define equal widths for all glyphs.

The reason the rendering looks good in the terminal is because the terminal works with cells and it forces all characters to be equally wide (with some exceptions).
