### ISSUE TITLE
Dynamically adjust code complection lines according to usage frequency

### ISSUE THREAD

**Issue by shrekuu** [microsoft/vscode#211534]
For example, in the screenshot, I wish my code(the second line, @/utils/utils) comes above the first one(sortablejs). 
It would be great if the order is based on the usage frequency.

<img width="485" alt="image" src="https://github.com/microsoft/vscode/assets/3136026/ef708a24-7fcf-40f5-b12a-9d7225b06c11">

**Comment by jrieken** [comment]
Please try out this setting `editor.suggestSelection` and report back if it solves your issue

**Comment by jrieken** [comment]
@shrekuu ping https://github.com/microsoft/vscode/issues/211534#issuecomment-2089827074

**Comment by shrekuu** [comment]
<img width="551" alt="Image" src="https://github.com/user-attachments/assets/49e39ad4-3a4a-4d0f-b170-ac386703a0eb" />

@jrieken Oh my god!!! This is super cool! I set `editor.suggestSelection` to `recentlyUsed`.  I find it automatically selected the one I recently used and scrolls to it. Very cool feature!!! Thanks. Please close this issue.

**Comment by jrieken** [comment]
Glad you like it!
