### ISSUE TITLE
editor loses focus when selection suggestion with mouse

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21153]
* open ts file
* trigger IntelliSense
* select a suggestion with mouse
* 🐛 the editor doesn't have focus...

**Comment by jrieken** [comment]
https://github.com/Microsoft/vscode/commit/6fa2266435d937f0fab15379dc8c62135647ffc7 is a bad fix

**Comment by joaomoreno** [comment]
Reverted.
