### ISSUE TITLE
Feature request/extension idea: disable editing for specific files or folders

### ISSUE THREAD

**Issue by JorensM** [microsoft/vscode#211553]
So I think we've all had a time when we open up the `index.html` file, start editing, only to notice after a few minutes that the file we're editing is the one that was generated by the build step and put into the `/dist` folder, instead of the one in the `src` folder. So my feature request would be to allow for disabling editing for specific files or folders, after which the file won't be editable anymore, unless you enable editing again. An alternative method would be to allow for hiding of folders or files in your project. You could have some sort of an indicator in a corner somewhere saying that you have some files that have been hidden.

Let me know what you think!

**Comment by bpasero** [comment]
That is covered by https://code.visualstudio.com/updates/v1_79#_readonly-mode

**Comment by JorensM** [comment]
> That is covered by https://code.visualstudio.com/updates/v1_79#_readonly-mode

Oh, that's neat, thanks for sharing. This can be closed then.
