### ISSUE TITLE
Managed to get it in this state when the explorer was not focused somehow:

### ISSUE THREAD

**Issue by noon1985krar** [microsoft/vscode#211521]
Managed to get it in this state when the explorer was not focused somehow:

![image](https://github.com/microsoft/vscode/assets/2193314/991acf34-36a7-454f-80ab-ed2af36003a5)

_Originally posted by @Tyriar in https://github.com/microsoft/vscode/issues/197157#issuecomment-1792956023_

**Comment by lramos15** [comment]
Consolidating back to #197157

Will split off if the fix doesn't work for both issues. Thanks!
