### ISSUE TITLE
Remote ssh can't work in Chinese language mode

### ISSUE THREAD

**Issue by pollyhxl** [microsoft/vscode#211552]
Type: <b>Bug</b>

1. F1->Configure display language, change to Chinese
2. Restart VSCode
3. VS Code cannot connect to server which is connected by remote ssh previously in English mode
4. C/C++ debugger can't work even if the connection is successfully sometimes
5. The problem can't be reproduced in English mode

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 4.15.0-128-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (18.63GB free)|
|Process Argv|--crash-reporter-id fc0605c5-de1d-41bb-b669-d83a3bf524ff --crash-reporter-id fc0605c5-de1d-41bb-b669-d83a3bf524ff --crash-reporter-id fc0605c5-de1d-41bb-b669-d83a3bf524ff|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.144.3.150|
|OS|Linux x64 4.15.0-128-generic|
|CPUs|Intel(R) Xeon(R) Gold 6278C CPU @ 2.60GHz (16 x 2600)|
|Memory (System)|31.41GB (29.14GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
snippets|Jia|0.0.2
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.5.2024031109
linkerscript|Zix|1.0.4
tongyi-lingma|Ali|1.2.13
gitlens|eam|14.9.1
cmake-language-support-vscode|jos|0.0.9
git-graph|mhu|1.30.0
vscode-dotnet-runtime|ms-|2.0.3
debugpy|ms-|2024.4.0
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.14
cmake|twx|0.0.17
vscode-counter|uct|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31022790

```

</details>

**Comment by wkmyws** [comment]
In English mode, I have also encountered this issue. After a long waiting time, it eventually works, but displays the error message "connect ETIMEDOUT 20.197.80.108:443".

**Comment by roblourens** [comment]
Can you share the log from the Remote-SSH output channel? Thanks
