### ISSUE TITLE
Cannot enter characters when using Jupyter Notebook after connecting to vscode on Safari

### ISSUE THREAD

**Issue by pyqjw** [microsoft/vscode#211556]
Does this issue occur when all extensions are disabled?: Yes
Use iPad browser Safari to connect to vscode and use jupyter notebook.
When editing a code block, the virtual keyboard pops up and then immediately returns, making it impossible to enter characters.

- VS Code Version: e170252f762678dec6ca2cc69aba1570769a5d39
- OS Version: Windows 11,Windows Feature Experience Pack 1000.22688.1000.0

**Comment by TylerLeonhardt** [comment]
This appears to be fixed now. Are you still seeing this?
