### ISSUE TITLE
Sparkle obstructs text in notebook cell

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#211699]
![image](https://github.com/microsoft/vscode/assets/16353531/4f47ff30-47c2-4459-ab7b-2d08430f536d)

Version: 1.89.0-insider
Commit: dfa434a13c74b847c9edc4a82e5ca0588f24ce9d
Date: 2024-04-29T22:54:38.075Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

**Comment by rebornix** [comment]
@aiday-mar I think this can happen to text editor as well if it only has a single line of content. Let me know if there is anything we can do in notebook to help improve this.

**Comment by aiday-mar** [comment]
Yes thank you for letting me know of this. Would you say we should in this case show the sparkle below the 2nd line @aeschli ?

pinging also @justschen for thoughts

**Comment by ulugbekna** [comment]
> does the white sparkle do the same thing?

do you mean the one near "0.0 s"? I think it does something slightly different (but I do think that having two sparkles is quite confusing @rebornix )

**Comment by justschen** [comment]
@ulugbekna gotcha - I personally like the sparkle location next to the run time, but if that was where we had the sparkle instead, it might not be immediately clear that the sparkle is intended for the error?

**Comment by aiday-mar** [comment]
At some point we were discussing placing the sparkle in the gutter which moved as you would change the selection. We had code initially for this, and then removed it. Perhaps in the case of notebooks, this would have been useful.

**Comment by justschen** [comment]
this should be fixed with https://github.com/microsoft/vscode/pull/221419 which will spawn the lightbulb in the gutter as well.
