### ISSUE TITLE
Bug: `editor.action.showDefinitionPreviewHover` behaves wrongly

### ISSUE THREAD

**Issue by xiyaowong** [microsoft/vscode#211640]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.89.0-insider
Commit: b55887a7d96669ea2e70baff32bb2288c640d015
Date: 2024-04-26T13:03:41.908Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.89.0-insider Chrome/120.0.6099.291 Electron/28.2.8 Safari/537.36

Steps to Reproduce:

1. Use the Command Palette to trigger "Show Hover"
2. Use the Command Palette to trigger "Show Definition Preview Hover"
3. Notice they give the same results, as opposed to Ctrl + Mouse Hover

![hover](https://github.com/microsoft/vscode/assets/47070852/870d4def-438f-4e75-a04a-69d322f29a7c)

Related: #111953

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. This was recently fixed. The fix should appear soon in Insiders
