### ISSUE TITLE
cannot navigate TS files with arrow keys anymore

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21165]
This is a regression from the self-invoking completion item provider (which is to be avoid)

* open `/src/vs/editor/common/editorCommon.ts`
* move down with arrow key
* as soon as I enter a doc comment I am stuck in IntelliSense

![feb-22-2017 17-45-26](https://cloud.githubusercontent.com/assets/1794099/23222024/eba50c5a-f926-11e6-9d2c-5df7db65639c.gif)

**Comment by mjbvz** [comment]
Duplicate of  #21056 which should already be fixed in master
