### ISSUE TITLE
Incorrect display of title link after title update by F2

### ISSUE THREAD

**Issue by hudrid** [microsoft/vscode#211633]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.88.1
- OS Version: Windows 10 Home 22H2 19045.4291

Steps to Reproduce:

1. Add the following code to the md-file:
```markdown

- [Options](#options)

# Options

[Options](#options)
```
2. Go to the end of the header and press `F2`.
3. In the window that appears, add the Cyrillic characters, e.g. `Настройки`:
![image](https://github.com/microsoft/vscode/assets/55594483/2cdfbeab-b2a3-4687-a438-0fbf73397e6d)
4. Press `Enter`.

Result (encoding: UTF-8):
![image](https://github.com/microsoft/vscode/assets/55594483/343106da-635c-4202-90b7-13e42507bce5)

**Comment by mjbvz** [comment]
Should already be fixed in the current insiders build. Fix will also go out in VS code 1.89
