### ISSUE TITLE
Incorporate // MARK: and //#REGION into .vue files

### ISSUE THREAD

**Issue by caseydwayne** [microsoft/vscode#211697]
Please incorporate these organizational techniques into Vue files. Presently I use Pug, SCSS, and of course JS in Vue files - all of which support // comments, but VS Code does not detect // MARK: or //#REGION for code folding/minimap.

**Comment by aeschli** [comment]
You need to file this request against the vue extension: https://github.com/vuejs/vetur/issues
The vue extensions can define the range markers in the `language-configuration.json` file
