### ISSUE TITLE
Modern Radius, Active Scale Effect, and Backdrop Filter.

### ISSUE THREAD

**Issue by huzaifaasim017** [microsoft/vscode#211693]
This effect adds a modern touch to VS Code, with rounded corners and a subtle scaling effect on active elements, reminiscent of Windows 11's design.

![image](https://github.com/microsoft/vscode/assets/64212910/e1cea52d-71c9-4a9a-b664-f2ea8f960da0)

Like in this image, it has no radius when we hover.
This type of look will be great.

![image](https://github.com/microsoft/vscode/assets/64212910/cbc5c3c4-f177-42eb-a6b6-88fca913ab55)

and as we couldn't see the backdrop-filter blur effect under the vs code I think in the search bar or more like this it should has the backdrop filter blur.

![image](https://github.com/microsoft/vscode/assets/64212910/fe6a9b51-0b39-4362-aa56-5c80db19b0bd)

Like we see here.

![image](https://github.com/microsoft/vscode/assets/64212910/a4e76439-87ef-4fed-bd73-ac5acd765e74)

---
Regards, @huzaifaasim017

**Comment by IllusionMH** [comment]
Related #115641
