### ISSUE TITLE
Column breakpoints are hard to place

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#21167]
Testing #20192

- VSCode Version: Code - Insiders 1.10.0-insider (256d76fed7947e7289f921df10658d7a69233b65, 2017-02-22T07:10:23.895Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: None

Steps to Reproduce:

1. Add column breakpoint before `resolve()`
2. F5
3. Debugger stops on breakpoint
4. Breakpoint is moved after `.isDirectory()`

I could understand if it was moved before `!err`, because that needs to be evaluated before `resolve()` is called, but after `.isDirectory()` seems wrong.

![image](https://cloud.githubusercontent.com/assets/9205389/23222791/e3f73a58-f8dd-11e6-88e4-cd4633febb53.png)

**Comment by chrmarti** [comment]
Doing 'Step In' stepped out of that lambda, suggesting that the breakpoint was hit on the way out. The intended placement, when placing it before `resolve()`, was on entering the lambda.

**Comment by chrmarti** [comment]
Also: Placing it in front of `'i: '` makes it move unexpectedly here:
![image](https://cloud.githubusercontent.com/assets/9205389/23223366/b8d03b52-f8df-11e6-989b-c59193e7531b.png)

The breakpoint list shows it at `4:1`, which is not a line in the file:
![image](https://cloud.githubusercontent.com/assets/9205389/23223405/db734096-f8df-11e6-8ebc-772b36bdee8f.png)

**Comment by chrmarti** [comment]
In case this matters: I was using node 6.5.0.

**Comment by chrmarti** [comment]
Column breakpoints are hard to place in general.

Here the only place the breakpoint stuck was on the `&&`:
![image](https://cloud.githubusercontent.com/assets/9205389/23225710/b90a6e96-f8e7-11e6-8859-cd1053a67e4a.png)

Here the only place it stuck was on the beginning of the line:
![image](https://cloud.githubusercontent.com/assets/9205389/23225817/1ed1445c-f8e8-11e6-972f-849297308f57.png)

**Comment by isidorn** [comment]
This comes from the node backend and I believe there is nothing we can do about it. Forwarding to @weinand in any way

**Comment by weinand** [comment]
The node runtime determines where column breakpoints can be placed. This is out o our control.
If possible, try to do them same in the Chrome dev tools. The experience should be similar.

**Comment by isidorn** [comment]
Hmm using the latest vscode-insiders it is quite hard for me to place two column breakpoints on a line. Chrome dev tools does this better since they suggest at what locations to place - I think we should investigate in this to improve this, as the current experience is not so nice imho

**Comment by weinand** [comment]
dup of https://github.com/Microsoft/vscode/issues/23659
