### ISSUE TITLE
Please add an additional option for "copy.eol", separate from "files.eol"

### ISSUE THREAD

**Issue by mphaney** [Microsoft/vscode#21162]
Most of my work requires my files to have a simple LF as the eol character, but copy/pasting content in this format into other Windows apps such as Notepad or (more importantly) CMD, causes the lines to all run together as one single line.  It would be very handy, in settings.json, to specify something like this:

"files.eol": "\n",
"copy.eol": "\r\n"

so that content can be copied to the clipboard with a different eol than the file itself.

**Comment by mphaney** [comment]
Nevermind.  Might still be nice to have it baked in, but in the mean time I've just made an extension to accomplish this:

https://marketplace.visualstudio.com/items?itemName=DrMattSm.copy-eol

**Comment by bpasero** [comment]
Awesome, thats the right way 👍
