### ISSUE TITLE
envFile doesn't work at launch config

### ISSUE THREAD

**Issue by tinovyatkin** [Microsoft/vscode#21169]
- VSCode Version: 1.10.0-insider
- OS Version: macOS 10.12.4 Beta (16E163f)
- Node: 7.6

Steps to Reproduce:

1. add `.env` file into the project root
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch",
      "type": "node",
      "protocol": "inspector",
      "request": "launch",
      "program": "${workspaceRoot}/server/index.js",
      "stopOnEntry": false,
      "args": [],
      "cwd": "${workspaceRoot}",
      "envFile": "${workspaceRoot}/.env",
      "runtimeArgs": [
        "--harmony",
        "--trace-warnings",
        "--nolazy"
      ],
      "sourceMaps": false
    }
  ]
}
```

results in launch error
```
node --inspect=14795 --debug-brk --harmony --trace-warnings --nolazy server/index.js 
Node process error: Error: spawn node ENOENT
```
Changing this configuration to (ie load `.env` via `dotenv` module) work as expected:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch",
      "type": "node",
      "protocol": "inspector",
      "request": "launch",
      "program": "${workspaceRoot}/server/index.js",
      "stopOnEntry": false,
      "args": [],
      "cwd": "${workspaceRoot}",
      "runtimeArgs": [
        "--harmony",
        "--trace-warnings",
        "--nolazy",
        "-r",
        "dotenv/config"
      ],
      "sourceMaps": false
    }
  ]
}
```

**Comment by roblourens** [comment]
Does it work with `"protocol": "legacy"`?

**Comment by tinovyatkin** [comment]
No, the same error with `legacy` and todays Insider build:
![screen shot 2017-02-23 at 08 41 50 am](https://cloud.githubusercontent.com/assets/5350898/23259541/fe7b8a66-f9a3-11e6-95c4-2a35445b6d3e.png)

**Comment by roblourens** [comment]
Any idea @weinand? @tinovyatkin can we see the contents of your envFile? Or, can you check whether it works if the file is empty, or simpler?

**Comment by tinovyatkin** [comment]
It works with empty `.env`, sorry, can't share it (it's full of tokens!) but will try to remove line-by line to find the trigger

**Comment by tinovyatkin** [comment]
Ok, found the problem, it's this line:

```ini
# Add ./node_modules/.bin/ to PATH
PATH=./node_modules/.bin:$PATH
```
commenting `PATH` makes it magically working

**Comment by weinand** [comment]
yes, that was my suspicion. It seems that VS Code uses the PATH initialised from .env to lookup 'node'.

**Comment by tinovyatkin** [comment]
@weinand I use PATH in the `.env` because I use `autoenv` with `zsh` that reads the same file and it was working just fine. I can live without it however, so, I removed `PATH` already.

**Comment by weinand** [comment]
Of course, `zsh` understands the $ syntax and expands variables correctly. But I don't think that the "dotenv" module does. Its doc doesn't mention anything about expanding $ variables. So it will leave the $PATH as it is. And VS Code doesn't expand env variables either.

**Comment by weinand** [comment]
VS Code no longer overwrites existing env variables with variables defined in a .env file. This is the same behaviour as the popular ['dotenv'](https://www.npmjs.com/package/dotenv) npm module.
So something like `PATH=./node_modules/.bin:$PATH` is most likely ignored.
