### ISSUE TITLE
Hit Count on column breakpoint not respected

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#21168]
Testing #20192

- VSCode Version: Code - Insiders 1.10.0-insider (256d76fed7947e7289f921df10658d7a69233b65, 2017-02-22T07:10:23.895Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: None

Steps to Reproduce:

1. Add column breakpoint with Hit Count 1 in example below
2. Start Debug
-> Breakpoint is hit twice

![image](https://cloud.githubusercontent.com/assets/9205389/23223726/ad3d06e8-f8e0-11e6-9907-4f1f5a3dea99.png)

**Comment by chrmarti** [comment]
In case this matters: I was using node 6.5.0.

**Comment by isidorn** [comment]
As designed, you need to set Hit Count 2. Because that means to stop it when the breakpoint is hit twice, if you set hit count 1 then it will stop on the first hit. Which is intuitive to me.
Closing as designed as it works nicely on my machine

fyi @weinand

**Comment by chrmarti** [comment]
My error, I thought hit count == 1 would only break the first time and not later.

**Comment by isidorn** [comment]
No worries, I understand the confusion
