### ISSUE TITLE
Start Debug does not start current file (no launch.json)

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#21160]
- VSCode Version: Code - Insiders 1.10.0-insider (256d76fed7947e7289f921df10658d7a69233b65, 2017-02-22T07:04:54.544Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|autofilename|JerryHong|0.1.3|
|vscode-simple-icons|LaurentTreguier|0.10.0|
|vscode-docker|PeterJausovec|0.0.11|
|azure-cli|chrmarti|0.3.0|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.2.5|
|ghlink|dt|0.0.5|
|tslint|eg2|0.8.1|
|vscode-scss|mrmlnc|0.6.1|
|PowerShell|ms-vscode|0.9.0|
|cpptools|ms-vscode|0.10.0|
|debugger-for-chrome|msjsdiag|2.5.2|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.3.1|

---

Steps to Reproduce:

1. Have a folder with several .js files and no launch.json
2. F5 while one .js is open
3. Another .js is launched

Not sure what might cause this, but I can reproduce in that folder.

**Comment by weinand** [comment]
@chrmarti I cannot reproduce.
Can you reproduce when disabling all extension?
Do you have a package.json with a 'start' script entry? Our "no launch.json" smartness looks into it to find the programs entry point.

**Comment by chrmarti** [comment]
I have a `"main"` entry in my package.json, wasn't aware of that.
