### ISSUE TITLE
Activity bar: bad drag feedback when `contrastActiveBorder` is set

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#211626]
The activity bar ideally looks and feels like the other panel switchers, but there is differences, probably because its the oldest component for views. I am trying to fix parts of it in https://github.com/microsoft/vscode/pull/211624

If you configure `"contrastActiveBorder": "#ff0000"` in settings, the drop feedback breaks:

![Recording 2024-04-29 at 11 31 52](https://github.com/microsoft/vscode/assets/900690/b10c28a0-8688-4697-a076-3b1e61fc81c3)

This does not reproduce in other composite switchers or when the location is at top or bottom. I think the issue is that the drop indicator is on the action item and not the label.

**Comment by benibenj** [comment]
This is what I ended up with:

![Code_-_OSS_BUqNaKFfsZ](https://github.com/microsoft/vscode/assets/44439583/e7aa6bc9-d785-49c0-b2e4-f4b41744ca24)

**Comment by bpasero** [comment]
Yeah 🚀
