### ISSUE TITLE
Error with feature

### ISSUE THREAD

**Issue by MrAmericanMike** [microsoft/vscode#211639]
Does this issue occur when all extensions are disabled?: Yes/No

Don't know it's not a consistent error so hard to test.

- VS Code Version: 1.88.1
- OS Version: Windows_NT x64 10.0.22623

Steps to Reproduce:

1. It's not consistent, so I don't know what caused it to happen or how to make it happen again

![image](https://github.com/microsoft/vscode/assets/8037559/65490313-8bd6-45ed-8559-edbd8c5f9a74)

The image shows the error, not even sure what that feature is called, or what is causing it to hide line 2 and show the function on line 451 in this case.
Independent of the issue itself, how do I disable this feature? I know it was added on some recent update and it was enabled by default for whatever reason.

**Comment by roblourens** [comment]
Looks like the function is folded? Click the `>`. And maybe you have something set for `editor.lineNumbers`

**Comment by MrAmericanMike** [comment]
> Looks like the function is folded? Click the `>`. And maybe you have something set for `editor.lineNumbers`

Not sure if the function been folded caused it, the new feature that VSC added is that when you are scrolling through code they "pin" at the stop the "scope" where you are at, so if I'm scrolling a long function, it will keep the name of that function (or scope) on top.

For example here it's keeping lines 1 and 13 visible.

![image](https://github.com/microsoft/vscode/assets/8037559/2e1d158e-ef9d-4f20-8058-03e9e702a8c6)

That's what I would like to disable. Will check the settings to see if I can find it. 

Even then, the bug is there as we can see it's not working correctly.

**Comment by roblourens** [comment]
Yes, sticky scroll. The second screenshot looks correct to me.
