### ISSUE TITLE
Column breakpoint in middle of word

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#21164]
Testing #20192

- VSCode Version: Code - Insiders 1.10.0-insider (256d76fed7947e7289f921df10658d7a69233b65, 2017-02-22T07:10:23.895Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: None

Steps to Reproduce:

1. Place cursor in middle of word
2. Command Palette > Column Breakpoint

![image](https://cloud.githubusercontent.com/assets/9205389/23221887/15ca329a-f8db-11e6-9b87-f7806ac80b98.png)

**Comment by isidorn** [comment]
As designed, once you start debuggin the extension can update the column location since only the debug adapter know the truth.
