### ISSUE TITLE
Symbol search no longer seems to find classes/interfaces in VS Code

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#211672]
Using the workspace TS version, 5.5.0-dev.20240408:

![image](https://github.com/microsoft/vscode/assets/2230985/f6fea0a2-a498-41b8-8e2d-6ad8bcea764b)
![image](https://github.com/microsoft/vscode/assets/2230985/0cf75342-cbb2-4c79-9a79-b74e8b24528c)
![image](https://github.com/microsoft/vscode/assets/2230985/090f57ac-f47b-49b2-8410-ee42dc5ccf5e)

**Comment by mjbvz** [comment]
Closing for verification
