### ISSUE TITLE
Feature Request:  Add Chat History/Saved Chats for GitHub Copilot in Visual Studio Code

### ISSUE THREAD

**Issue by AdrianeNS** [microsoft/vscode#211601]
Sure, here's a draft for your feature request:

---

**Title:** Feature Request: Add Chat History for GitHub Copilot in Visual Studio Code

**Description:**

Hello,

I recently encountered a situation where I lost a significant amount of work due to the lack of a chat history feature being available within Visual Studio Code for Copilot Chat

I was working on a detailed project with GitHub Copilot over several days. Somehow, the chat window got closed and I was unable to retrieve the chat history. This resulted in the loss of hours of work and valuable information that was exchanged during the chat.  Also, this limits the ability to work on more than one project at a time in Visual Studio Code if it requires use of Copilot Chat.  All of the other LLM models I've used have the chat history automatically saved, so you can jump back to a conversation at any time.

I believe a chat history feature for GitHub Copilot would be extremely beneficial for situations like these. This would allow users to reopen previous chats, ensuring that valuable information is not lost.

I understand that not all feature requests can be implemented, but I believe this would be a valuable addition to Visual Studio Code and GitHub Copilot. I hope you'll consider this request.

Thank you for your time and consideration.

**Comment by roblourens** [comment]
Chats are saved per-workspace, and there is a history button at the top of the chat view
