### ISSUE TITLE
Unable to open 'settings.json': Cannot read property 'filterPreferences' of null.

### ISSUE THREAD

**Issue by fzzr-** [Microsoft/vscode#21161]
- VSCode Version: Version 1.9.1 (1.9.1)
- OS Version: macOS 10.11.6 (15G1217)

Steps to Reproduce:

1. Open three editor tabs in that order: any.file, settings, another.file;
2. Focus must be in any.file editor;
3. Using hotkeys do fast combo for focus another.file editor - it should be very quickly!

![screen shot 2017-02-22 at 19 19 20](https://cloud.githubusercontent.com/assets/888526/23221039/f48bb09a-f934-11e6-91b9-da0f2b3a9361.png)

**Comment by sandy081** [comment]
This should be fixed with changes in 1.10 milestone
