### ISSUE TITLE
Show the run & debug dropdown and run buttons in VS Code without switching to the run `Run and Debug` tab

### ISSUE THREAD

**Issue by raulvaldoleiros** [microsoft/vscode#211766]
It would be great if Vs code add an option to make run debug drop-down sticky without being associated to a view.
Right now I'm forced to change views every time I want to launch the application, which isn't the best experience.

**Comment by roblourens** [comment]
And you can press F5 any time!

**Comment by raulvaldoleiros** [comment]
Didn't know, thanks 👍
