### ISSUE TITLE
.NET development: launchBrowser related features does-not work when working on a Codespace.

### ISSUE THREAD

**Issue by OTonGitHub** [microsoft/vscode#211783]
in .NET development, there is a launchSettings.json file, which has some properties for
launchBrowser and launchUrl, this defines if the browser be launched when the App is run and what would be the launch URL.
That file is illustrated below:

<img src=https://github.com/microsoft/vscode/assets/81725875/56283cd0-1690-45b5-bbd7-89ff970bc58c width=387/>

When I am using a remote Codespace connected to my VSCode, the ports defined in launchSettings.json are forwarded,
however the prompt that comes up when app does not take into consideration the specifications of launch properties, it only seems to detect the port in which the App is launched in and forwards it.

<img src=https://github.com/microsoft/vscode/assets/81725875/7e1e7492-77b4-4e83-baca-595fc6dc5819 width=500/>

As such, I suggest that, for .NET development having this feature to detect launchUrl from the remote server and doing so locally will save time and make developer experience better for devs using codespace or remote development, this may not be .NET specific, but I am reporting as how I encountered it.

Thank you.

**Comment by roblourens** [comment]
The popup is not related to to the launchSettings.json file, as far as I'm aware. If you want something different from launchSettings and the .NET experience, please file an issue on the .NET extension

**Comment by OTonGitHub** [comment]
you're right, thank you.
