### ISSUE TITLE
jsdoc autocomplete should prefer {Object} over {any} in JavaScript

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21179]
#21031

`any` is a TypeScript concept, `Object` is the most generic type in JavaScript which is more meaningful to non-TS devs:

![image](https://cloud.githubusercontent.com/assets/2193314/23225467/d8eb67e8-f8e6-11e6-9008-ee314dbebb0c.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14242
