### ISSUE TITLE
Docstrings are truncated even when expanding completion pop-up window to maximum size 

### ISSUE THREAD

**Issue by BreathBlush** [microsoft/vscode#211737]
# Behaviour

The tooltip for the docstring that pops up when entering a partial function name is truncated, causing long lines to be cut off.

## Steps to reproduce:

1. Defining a function with long docstring input.

![1](https://github.com/microsoft/vscode-python/assets/10967857/2f6f1b7b-2b28-419e-9d8c-e8cda8122416)

2. Entering the function name letter by letter, the docstring tooltip show up

3. Viewing the tooltip and find the long line truncated.

![2](https://github.com/microsoft/vscode-python/assets/10967857/7b7fc526-c722-4229-a435-39283a7fa773)

4. When you've entered the full name of the function and move  your mouse point hover to the function name, the docstring is shown normal.

![3](https://github.com/microsoft/vscode-python/assets/10967857/2434064c-9069-4cbe-ba5e-6b22cc065144)

Hope it'd be fixed.

Best wishes.

**Comment by jrieken** [comment]
@luabud @heejaechang Sorry, but how to I reproduce this? I have python/pylance installed and I am using the file above but I don't get completions

<img width="940" alt="Screenshot 2024-05-02 at 10 27 13" src="https://github.com/microsoft/vscode/assets/1794099/6fef4762-e0e6-4604-8ab2-92c0b68ad980">

**Comment by jrieken** [comment]
Also, with a TS sample I do see a scroll bar for the completions details window (it shows on hover like all our scroll bars)


<img width="1156" alt="Screenshot 2024-05-02 at 10 29 03" src="https://github.com/microsoft/vscode/assets/1794099/dbeb1c68-33ee-4618-86ec-0171fdacec7c">

**Comment by luabud** [comment]
it shouldn't need auto imports enabled for the [example above](https://github.com/microsoft/vscode/issues/211737#issuecomment-2086506878) though, right? I think it's weird that it showed "no suggestions" [here](https://github.com/microsoft/vscode/issues/211737#issuecomment-2089894570). Doing the same thing and hitting  `Ctrl+space` shows the suggestion to me:
![image](https://github.com/microsoft/vscode/assets/45497113/192de653-d088-4e74-bd27-9b13b57dad03)


@jrieken can you make sure Pylance is enabled? You can check if `python.languageServer` is set to Default or Pylance, as well as any errors in the Python Language Server output channel

**Comment by jrieken** [comment]
Please someone extract a simple reproduction dummy extension that doesn't involve getting pylance to run.
