### ISSUE TITLE
I cannot go windowed full screen

### ISSUE THREAD

**Issue by cnkbat** [microsoft/vscode#211780]
Type: <b>Bug</b>

The close and down buttons on the top right are active, but the fullscreen button with the window in the middle is not. I only have problems with vs code.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22621
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (18.87GB free)|
|Process Argv|--crash-reporter-id 9d67f981-db42-4a33-887f-7f5cc4e5f6be|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ue4-snippets|CAP|2.0.1
c-cpp-runner|fra|9.4.7
vscode-vibrancy-continued|ill|1.1.29
configure-c-compiling|ivo|0.2.1
cpptask|kay|0.0.1
lib-search|Kho|0.0.3
unity-code-snippets|kle|2.4.0
smt-lib-syntax|mar|0.0.1
vscode-language-pack-tr|MS-|1.88.2024041009
csdevkit|ms-|1.4.29
csharp|ms-|2.23.15
vscode-dotnet-runtime|ms-|2.0.3
vscodeintellicode-csharp|ms-|2.0.25
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
unity-tools|Tob|1.2.12
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
<img width="180" alt="Ekran görüntüsü 2023-08-13 202657" src="https://github.com/microsoft/vscode/assets/104725177/8fd38ab3-0532-402a-bf9b-6b958a9cd083">

vscodeintellicode|Vis|1.3.1
vstuc|vis|1.0.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
chatpanelc:31018788
dsvsc021:30996838
0ee40948:31013168
pythoncenvptcf:31022791
dwnewjupyter:31035176

```

</details>

**Comment by deepak1556** [comment]
Can you confirm if the issue is present with latest stable.
