### ISSUE TITLE
Layer breaking: notebook contrib imported into notebook core

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#211739]
https://github.com/microsoft/vscode/blob/001929db91b434532f9307ea7643e71aeba4104b/src/vs/workbench/contrib/notebook/browser/viewModel/codeCellViewModel.ts#L25

We should probably do the other way around, creating a notebook contribution like https://github.com/microsoft/vscode/blob/001929db91b434532f9307ea7643e71aeba4104b/src/vs/workbench/contrib/notebook/browser/contrib/cellStatusBar/contributedStatusBarItemController.ts#L15

**Comment by amunger** [comment]
shouldn't a layer break cause a linter error?

**Comment by bpasero** [comment]
You might want to review:

https://github.com/microsoft/vscode/blob/f601d3eb2f8270099bf2fdd0b5c2f49ea9967183/.eslintrc.json#L617

I think we do not detect a `contrib` depending on a `contrib/.../contrib`

**Comment by rebornix** [comment]
It's worth adding a new lint rule
