### ISSUE TITLE
Many timeouts when changing column breakpoints while debugging session is running

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#21171]
Testing #20192

- VSCode Version: Code - Insiders 1.10.0-insider (256d76fed7947e7289f921df10658d7a69233b65, 2017-02-22T07:10:23.895Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: None

Steps to Reproduce:

1. Start debugging session
2. While debugging session is running: Add/remove column breakpoints
-> Quite often a warning about node being unresponsive is shown

Using node 7.6.0 here, but have seen it with 6.5.0 too.

![image](https://cloud.githubusercontent.com/assets/9205389/23224295/a65da290-f8e2-11e6-9d13-012b11f40c43.png)

**Comment by weinand** [comment]
Please share your test program or project.

**Comment by chrmarti** [comment]
Can't reproduce at the moment. I also can't set the column breakpoint before the second `console` anymore. It worked yesterday, as shown in the screenshot above. Double-checked the launch.json uses `node`.

**Comment by chrmarti** [comment]
Not sure why I couldn't set that column breakpoint, but it works again now.

Also got steps that reproduce it:
- File:
```
for (let i = 2; i; i--) {
    console.log('i: ' + i); console.log('i: ' + i);
}
```
- Start debugging without any breakpoints
- Code runs to end, debugger stays on
- Place column breakpoint in front of the second `console`
- Wait like 10 seconds
-> Above warning message about timeout in shown

Reproduce on Windows and Mac. (Node 7.6.0 and 6.5.0 on Windows. Node 6.9.4 on Mac.)

**Comment by weinand** [comment]
no longer a problem in node.js >= 8
