### ISSUE TITLE
Confusing 'current execution point' indicator

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#21174]
Testing #20192 with Node 7.6.0.

- VSCode Version: Code - Insiders 1.10.0-insider (256d76fed7947e7289f921df10658d7a69233b65, 2017-02-22T07:10:23.895Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: None

Steps to Reproduce:

1. Place line breakpoint as shown below
2. F5 to let the debugger break there
-> That yellow arrow left to `&&` is confusing. Did it break there? Maybe line breakpoints should remain unaffected by the column breakpoint decorations?

![image](https://cloud.githubusercontent.com/assets/9205389/23224791/8e275b1a-f8e4-11e6-8e48-9e7d53d6f32a.png)

**Comment by chrmarti** [comment]
Inverse issue: When stopping on a column breakpoint placed at `&&`, there is no current execution point indicator within the line:
![image](https://cloud.githubusercontent.com/assets/9205389/23225422/b876e960-f8e6-11e6-8e2d-f55a963cfaca.png)

Should just be the opposite: Show inline current execution point with column breakpoints, but not with line breakpoints.

**Comment by isidorn** [comment]
Agree that these two decorations should be merged together to display something similar to the gutter icon. Dup of https://github.com/Microsoft/vscode/issues/21121
