### ISSUE TITLE
jupyter data viewer cannot loading when move to new floating window

### ISSUE THREAD

**Issue by xc-gs** [microsoft/vscode#211784]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.88.1
- OS Version:  macos

Steps to Reproduce:

1. "Show variable snapshot in data viewer" in Jupyter variable windows
2. Move the data viewer tab to floating window

**Comment by amunger** [comment]
duplicate of https://github.com/microsoft/vscode-jupyter/issues/15574
