### ISSUE TITLE
Screen Flickering

### ISSUE THREAD

**Issue by Cryton555** [microsoft/vscode#211792]
Type: <b>Bug</b>

Simply open VS Code. Anytime the app is onscreen, it flickers.

VS Code version: Code - Insiders 1.89.0-insider (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:05:10.904Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.47GB free)|
|Process Argv|--crash-reporter-id d6f52400-5f0d-4cdb-bc72-831bb5e061f1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
dadroit-json-generator|Dad|1.1.7
composer-php-vscode|DEV|1.45.15341
profiler-php-vscode|DEV|1.45.15341
go|gol|0.41.4
vs-code-runner|Har|2.0.1
al-test-runner|jam|10.12.2
excel-live-server|loc|4.0.30
r|Mik|0.0.32
csdevkit|ms-|1.5.18
csharp|ms-|2.28.8
vscode-dotnet-runtime|ms-|2.0.3
vscodeintellicode-csharp|ms-|2.0.25
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.22.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.1
debugpy|ms-|2024.5.11172029
python|ms-|2024.5.11172159
vscode-pylance|ms-|2024.4.105
jupyter-keymap|ms-|1.1.2
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.5.2024031109
remote-server|ms-|1.6.2024042409
vscode-serial-monitor|ms-|0.11.240501001
vscode-thunder-client|ran|2.21.18
r-debugger|RDe|0.5.4
r|REd|2.8.2
jinjahtml|sam|0.20.0
ruby-lsp|Sho|0.6.10
vscode-java-debug|vsc|0.57.2024041008
vscode-java-test|vsc|0.41.2024042308

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
fegfb526:30952798
bg6jg535:30979844
ccp2r3:30958153
pythonait:30973460
jchc7451:30973074
gee8j676:31009450
showvideot:31016890
chatpanelt:31014475
01bff139:31013167
pythoncenvpt:31022790
a69g1124:31018687
j0bi8933:31021562
dvdeprecationcf:31030042
pythonprc:31030355
dwnewjupytercf:31035177

```

</details>

**Comment by okineadev** [comment]
Try disabling video card acceleration - https://gist.github.com/andriyudatama/fe5d00deb36feeea30ef35a5ea0f7eff

**Comment by okineadev** [comment]
What is your laptop model?

Do you have an OLED matrix?

**Comment by okineadev** [comment]
If you have it turned on, turn it off

![image](https://github.com/microsoft/vscode/assets/81070564/6404fcc7-adfb-412c-8f55-832964d62195)

**Comment by okineadev** [comment]
In MyASUS app

**Comment by Cryton555** [comment]
That is not an option available to me

**Comment by okineadev** [comment]
Tryb disable / enable MUX switch

**Comment by Cryton555** [comment]
This is not a laptop, it does not use an integrated graphics card. I do not have an MSI Center app installed, and therefore no MUX switch is present.

**Comment by Cryton555** [comment]
I thought I had already tried this, but I double checked and found that I had forgotten a comma at the end of the line. Fixed, thanks for your time!
