### ISSUE TITLE
App always crashing

### ISSUE THREAD

**Issue by LeandreLapidus** [microsoft/vscode#211842]
Type: <b>Performance Issue</b>

Each time i work on VS, the window is crashing asking me reopen. I don't know why

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:34:12.840Z)
OS version: Linux x64 6.5.0-28-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 673)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 4, 2|
|Memory (System)|7.51GB (4.10GB free)|
|Process Argv|--unity-launch --crash-reporter-id c000d861-920b-47e3-a9e4-be7a6f96f047|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   138	 23192	code main
    0	    23	 23197	   zygote
    0	    61	 23228	     gpu-process
    0	    23	 23198	   zygote
    0	     0	 23200	     zygote
    0	  1015	 23250	window [1] (● list.html - kimi-grocery - Visual Studio Code)
    1	    85	 24183	window [2] (Issue Reporter)
    0	    38	 23237	   utility-network-service
    0	    92	 23306	shared-process
    0	     0	 24200	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 24201	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    9	    61	 23307	fileWatcher [1]
    0	    61	 23308	ptyHost
    0	     0	 23357	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 23476	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 23580	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 23936	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 24021	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	   246	 23852	extensionHost [1]
    0	    92	 23890	     electron-nodejs (serverMain.js )
    0	   100	 23901	     electron-nodejs (server.js )
    0	    69	 23913	     /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=23852
    0	    38	 23932	     /home/mranderson/.local/share/virtualenvs/kimi_grocery/bin/python /home/mranderson/.vscode/extensions/ms-python.black-formatter-2024.2.0/bundled/tool/lsp_server.py --stdio
    0	   131	 23935	     /home/mranderson/.local/share/virtualenvs/kimi_grocery/bin/python /home/mranderson/.vscode/extensions/ms-python.pylint-2023.10.1/bundled/tool/lsp_server.py
    0	   215	 23964	     electron-nodejs (bundle.js )
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● list.html - kimi-grocery - Visual Studio Code)
|    Folder (kimi-grocery): 2377 files
|      File types: svg(2048) pyc(93) py(80) html(36) js(18) css(16) json(6)
|                  ttf(4) woff2(4) md(2)
|      Conf files: launch.json(1)
|      Launch Configs: python(2);
```

</details>
<details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
vscode-sqlite|ale|0.14.1
vscode-django|bat|1.15.0
django|big|1.0.2
blackbox|Bla|1.3.16
coddx-alpha|cod|0.3.1
emoji-snippets|dev|1.5.3
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
gitlens|eam|14.9.1
vscode-html-css|ecm|2.0.9
mithril-emmet|Fal|0.7.7
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.86.1
vscode-test-explorer|hbe|2.21.1
vscode-django-support|jun|1.0.30
vsc-python-indent|Kev|1.18.0
python-path|mge|0.0.14
language-gettext|mro|0.5.0
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.4.0
pylint|ms-|2023.10.1
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
test-adapter-converter|ms-|0.1.9
autodocstring|njp|0.6.1
material-icon-theme|PKi|5.1.0
sqlite-viewer|qwt|0.4.3
LiveServer|rit|5.7.9
vscode-status-bar-format-toggle|tom|3.2.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
chatpanelc:31018788
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by deepak1556** [comment]
If the issue is present with latest stable, please share the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report
