### ISSUE TITLE
Fix unsafe type assertions on object literals

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#211878]
`<T>{ ... }` style type assertions are unsafe as they can hide some common typing errors such as missing properties on the object. This has caused errors for me multiple times now, so I think it would be good to make a pass through the code

# Fixing
I've added a new eslint rule for this called `local/code-no-dangerous-type-assertions`. You can turn it on in [`.eslintrc.json`](https://github.com/microsoft/vscode/blob/001929db91b434532f9307ea7643e71aeba4104b/.eslintrc.json#L760)

In most cases, we should prefer using proper typings such as:

```ts
const x = <T>{...};

// Becomes --->

const x: T = {...};
```

```ts
arr.map(x => <T>{ ... })

// Becomes --->

arr.map((x): T => ({ ... }));
```

If you want to make sure an object fulfills a certain type, prefer using the `satisfies` operator instead which will enforce the type without actually changing its shape:

```ts
const x = <T>{...};

// Becomes --->

const x = {...} satisfies T;
```

Note that this rule still allows `<any>` casts for now. You can also suppress this rule in the few cases where you need to workaround it using an eslint comment

---

# Tracking

- [ ] `src/vs/platform/environment/node/argv.ts` @bpasero 
- [ ] `src/vs/platform/list/browser/listService.ts` @joaomoreno 
- [ ] `src/vs/platform/update/common/update.ts` @joaomoreno 
- [x] `src/vs/workbench/api/browser/mainThreadLanguageFeatures.ts` @jrieken 
- [x] `src/vs/workbench/api/common/extHostTypeConverters.ts` @jrieken 
- [ ] `src/vs/base/parts/ipc/common/ipc.ts` @alexdima 
- [x] `src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts` @Tyriar 
- [ ] `src/vs/workbench/contrib/editSessions/browser/editSessionsViews.ts`  @joyceerhl 
- [ ] `src/vs/workbench/contrib/extensions/electron-sandbox/debugExtensionHostAction.ts` @connor4312 
- [ ] `src/vs/workbench/contrib/preferences/browser/keybindingsEditor.ts` @ulugbekna 
- [x] `src/vs/workbench/contrib/preferences/browser/settingsWidgets.ts` @rzhao271 
- [ ] `src/vs/workbench/services/preferences/browser/keybindingsEditorModel.ts` @ulugbekna

**Comment by alexr00** [comment]
I think I got all mine ✅

**Comment by connor4312** [comment]
I got rid of mine, but I had to add a new cast via a `mapValues` function in common/objects.ts -- still better to keep the unsafeness hidden inside well-defined functions.

**Comment by mjbvz** [comment]
Getting close! Thanks for all the help. Let's plan on finishing this up in the October debt week

**Comment by rzhao271** [comment]
@mjbvz I noticed that several of the unassigned entries use generics. In that case, trying to use `satisfies` results in errors such as
```
Type '{}' is not assignable to type 'T'.
  '{}' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'object'.
```
In this case, would it make sense to add a suppression comment instead, or is there another way forward?

**Comment by mjbvz** [comment]
Down to a handful of file. Great work everyone! I've updated the list and also fixed a few more of these myself

@rzhao271 It depends. In some cases you can rewrite to avoid the need for the assertion, for example switching to use a spread operator instead. However in other cases we do need the assertion. After reviewing the code, if you think the assertion still makes sense, you can add a suppression comment. I've added these in a few cases myself

**Comment by mjbvz** [comment]
Thanks all! I've enabled the eslint rule now and added suppressions using `eslint-disable local/code-no-dangerous-type-assertions`

Please give a quick review to any code you own to see if the suppression can be removed
