### ISSUE TITLE
Is TFS SCM integration possible

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21187]
#20999

It's been a while since I used regular TFS but from memory:

- I don't think TFS has a staging concept
- TFS workspaces are readonly until you check out the files explicitly

Given these and more differences with git, would TFS SCM integration be possible?

**Comment by bpasero** [comment]
I actually also thought that SCMs that need to do something to make a file readonly need some work by the extension. I would think that a save participant could be the solution for extensions to make the file writeable (e.g. check out) before the save goes to disk. Seems like a straightforward solution (hopefully).

**Comment by joaomoreno** [comment]
It is possible & they are working on it. 👍
