### ISSUE TITLE
VS not responding

### ISSUE THREAD

**Issue by federicombi** [microsoft/vscode#211898]
Type: <b>Bug</b>

It takes for ever to open, sometimes It won't open at all and i get a window saying it isn't responding

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:08:25.066Z)
OS version: Linux x64 6.8.0-31-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 4199)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|7.62GB (4.87GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id f8e58724-b5c9-4722-86d6-a911ecf71e46|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
chatpanelt:31018789
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled (--disable-extensions)?

**Comment by federicombi** [comment]
i can't launch it at all

**Comment by federicombi** [comment]
i cant launch it at all 
![imagen](https://github.com/microsoft/vscode/assets/164429673/46251299-839e-4af1-974f-2233ffde72ae)

**Comment by federicombi** [comment]
so this is what happened; aparently something got broken when i configured my git repository, i'm assuming this was because the folder of my repository was the same one i access from Windows. Yesterday after some long waiting and re-opening Code several times i was able to actually open it and change the directory, Everything working fine since then.
