### ISSUE TITLE
vscode.ThemeIcon color is ignored due to codeicon !Important CSS directive.

### ISSUE THREAD

**Issue by tumaysem** [microsoft/vscode#211885]
Type: Bug

1. Version of VS Code : 1.88.1
2. Your operating system : Windows 11 Pro
3. List of extensions that you have installed : None 
4. Reproducible steps:
Create an extension with tree view and assign items iconpath to a vscode.TehemIcon with color
+ package.json
```json
"contributes": { 
   "colors": [
      {
        "id": "mycolor",
        "description": "mydescription",
        "defaults": {
          "dark": "#00FF00",
          "light": "#00FF00",
          "highContrast": "#00FF00",
          "highContrastLight": "#00FF00"
        }
      }
    ]
  }
```
+ mydataprovider.ts
```ts
const MY_ICON = new vscode.ThemeIcon(`symbol-field`, new vscode.ThemeColor('mycolor') );
.
.
.
getTreeItem(element: Info): vscode.TreeItem {
    const item = new vscode.TreeItem(element.displayName);
    item.tooltip = `${element.displayName}-${element.currentVersion}`;
    item.description = element.currentVersion;
    item.iconPath = MY_ICON ;
    return item;
  }
```

5. What you expected to see, versus what you actually saw
I have expect to see the assigned color to tree view item but it was overriden by codeicon css.
![image](https://github.com/microsoft/vscode/assets/109538632/185f6e17-68f0-4641-a224-646e107993d8)

```html
<div class="custom-view-tree-node-item-icon codicon codicon-symbol-field" style="color: rgb(0, 255, 0);"></div>
````

[Here is the related code in vs-code repository.](https://github.com/microsoft/vscode/blame/145fcd4fa7fcc43628f673242871bc40d6cf55fb/src/vs/workbench/browser/parts/views/media/views.css#L211)

**Comment by alexr00** [comment]
I am not able to reproduce this. I tried with the a test extension, and also we do this in one of our first party extensions: 

https://github.com/microsoft/vscode-pull-request-github/blob/66a02ec6a9b147c50b600e5647801879ded688e9/src/issues/issuesView.ts#L79-L81
