### ISSUE TITLE
Local workspace (non web) extensions are recommended in web

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#211832]
Local workspace (non web) extensions are recommended in web 

![Image](https://github.com/microsoft/vscode/assets/10746682/e32317bb-1682-4caf-b82b-a326b95d291d)

**Comment by deepak1556** [comment]
Closing for verification.

**Comment by sandy081** [comment]
To verify:

- Open https://vscode.dev/github/microsoft/vscode?vscode-version=dc96b837cf6bb4af9cd736aa3af08cf8279f7685
- Trust the workspace
- Open Workspace Recommendations `@recommended` and make sure **VS Code SelfHost Test Provider** extension is not listed.

**Comment by bpasero** [comment]
I still see a notification though:

![image](https://github.com/microsoft/vscode/assets/900690/65216183-b652-4f39-8881-da624ee7b236)

![image](https://github.com/microsoft/vscode/assets/900690/a2206213-cf52-4175-8b6c-a877c02a67bf)

**Comment by bpasero** [comment]
I do not see the notification. The explorer is broken btw in that version:

![image](https://github.com/microsoft/vscode/assets/900690/6302858a-2031-411e-902a-8e4e986d5824)

**Comment by deepak1556** [comment]
> The explorer is broken btw in that version:

@bpasero to clarify is the explorer broken in the stable build for recovery release ?

**Comment by bpasero** [comment]
When opening: `https://vscode.dev/github/microsoft/vscode?vscode-version=dc96b837cf6bb4af9cd736aa3af08cf8279f7685`
