### ISSUE TITLE
Terminal links: Urls are cut off at %.

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#21188]
While testing #21021

```
bash-3.2$ echo https://www.amazon.com/Dell%2BP2715Q
https://www.amazon.com/Dell%2BP2715Q
bash-3.2$

The url is cut off at `%`.

**Comment by jrieken** [comment]
still seeing this with f02f9930255b5804166bd26c804de474ebb96799

![feb-24-2017 15-06-31](https://cloud.githubusercontent.com/assets/1794099/23306233/e04e06f4-faa2-11e6-8d69-2fc1fac3fc95.gif)
