### ISSUE TITLE
"default:replacePreviousChar"  causes text jitter during IME composition

### ISSUE THREAD

**Issue by xiyaowong** [microsoft/vscode#211856]
Does this issue occur when all extensions are disabled?: Yes

---

Version: 1.89.0-insider
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:05:10.904Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.89.0-insider Chrome/120.0.6099.291 Electron/28.2.8 Safari/537.36

---

Forwarding the arguments of replacePreviousChar to default:replacePreviousChar causes text jitter during ime composition.

Code to reproduce the issue:
```js
vscode.commands.registerCommand("type", (type) => {
    vscode.commands.executeCommand("default:type", type);
});
vscode.commands.registerCommand("replacePreviousChar", (args) => {
    vscode.commands.executeCommand("default:replacePreviousChar", args);
});
```

GIF:

- OK
![ok](https://github.com/microsoft/vscode/assets/47070852/2cef89f0-bf6d-46c1-a7b2-2e3f6711c6e8)

- NG
![ng](https://github.com/microsoft/vscode/assets/47070852/35889de2-8d44-4a9a-b5ff-a554f38db1ac)

**Comment by theol0403** [comment]
Related: https://github.com/microsoft/vscode/issues/156780 https://github.com/microsoft/vscode/issues/150108 (and from a quick search there are more)

**Comment by aiday-mar** [comment]
Hi @xiyaowong thank you for filing this issue. I am currently trying to reproduce this issue, but after having configured neovim, I get the following issue 'neovim gets disconnected' as soon as I reload the window. I saw that in the past two weeks quite a few people have filed this issue to the neovim repo. It would seem like this is an upstream vim issue?

https://github.com/user-attachments/assets/b6cf5d71-f93d-496c-8271-a7aeb6d5bc0f

**Comment by xiyaowong** [comment]
@aiday-mar "Neovim gets disconnected" is an upstream issue with Neovim, but it is unrelated to this issue. The jitter problem mentioned in this issue has been longstanding, and it also occurs with vscodevim.

**Comment by aiday-mar** [comment]
Hi thank you. I was able to verify this does not happen with the setting `editor.experimentalEditContextEnabled`. Closing this issue.
