### ISSUE TITLE
Dismiss not removing items from search and replace

### ISSUE THREAD

**Issue by steveoh** [microsoft/vscode#211820]
Type: <b>Bug</b>

I did a search and opened the carrot to reveal the replace text, then the results display below. When I click the x to dismiss an item or after preforming the replacement action on the match, the row is not removed from the search. 

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:43:08.196Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|36.00GB (0.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
toggle-excluded-files|amo|2.0.0
vscode-json|and|1.5.2
astro-vscode|ast|2.8.6
amvim|aui|1.37.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.23.0
markdown-preview-github-styles|bie|2.0.4
markdown-yaml-preamble|bie|0.1.0
vscode-tailwindcss|bra|0.10.5
npm-intellisense|chr|1.4.5
regex|chr|0.4.0
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|2.4.4
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
copilot|Git|1.184.0
copilot-chat|Git|0.14.1
copy-markdown-as-html|jer|1.1.0
vscode-text-pastry|jkj|1.3.1
pop-n-lock-theme-vscode|Lux|3.32.188
template-string-converter|meg|0.6.1
ecdc|mit|1.8.0
js-debug-nightly|ms-|2024.4.2417
live-server|ms-|0.4.13
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.5918
material-icon-theme|PKi|5.1.0
vscode-yaml|red|1.14.0
vscode-sort-json|ric|1.20.0
svg-preview|Sim|2.8.3
vscode-fileutils|sle|3.10.3
code-spell-checker|str|3.0.1
even-better-toml|tam|0.19.2
vscode-mdx|uni|1.8.3
colonize|vms|2.2.2
vscode-icons|vsc|12.7.0

(3 theme extensions excluded)

</details>

**Comment by andreamah** [comment]
Can you show a screen recording of this?

**Comment by steveoh** [comment]
[searc-replace.webm](https://github.com/microsoft/vscode/assets/325813/d816c161-4707-4d62-bdce-ed5d08f0db76)

**Comment by andreamah** [comment]
https://github.com/microsoft/vscode/assets/31675041/958eb8b2-8cf1-40e5-99de-56fcbb30dfd4



Hmm, that seems to not happen for me. Does this still happen if you right click the result and dismiss it that way?

**Comment by steveoh** [comment]
I showed that in the recording and it wasn't working. It may have been a glitch that has since passed though.

**Comment by andreamah** [comment]
Can you try the latest stable version that was released today? I don't think I implemented a fix for something like this specifically, but there's a chance it could have been fixed (hence why I don't see it).
