### ISSUE TITLE
Git: Support remote management

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21189]
#20999

Might be possible already, but it wasn't clear how to add a remote after hitting this:

![image](https://cloud.githubusercontent.com/assets/2193314/23226545/c9431b0c-f8ea-11e6-8c45-5b835f919e51.png)

I also often do the following to sync from upstream, I don't know if this is possible currently:

```bash
git checkout https://github.com/Tyriar/xterm.js.git
git remote add upstream https://github.com/sourcelair/xterm.js.git
git fetch upstream
git merge upstream/master
git push
```

**Comment by jpzwarte** [comment]
Also missing this feature: i can "Push to..." a new branch to remote "origin" (github), but when i try "git push" from the CLI, it tells me no upstream remote is set and i need to set it. Would be nice if vscode does a "git push -u REMOTE_NAME BRANCH_NAME" when using "Push to...".

**Comment by noamyogev84** [comment]
Hi @joaomoreno. Can I have some pointers for this issue? I'd like to try and tackle it.

**Comment by manjrekarom** [comment]
So we just need to Add/Remove remotes? Like `git remote add <remote-name> <url>` and `git remote rm <remote-name>` but from the Quick Open? Do I understand it right?

**Comment by manjrekarom** [comment]
#60640 Hi! I have added options for adding and removing remotes. I have included removing of remotes using the quick open API.

**Comment by joaomoreno** [comment]
Support for adding and removing remotes is now in `master`, thanks to @manjrekarom!
