### ISSUE TITLE
SCM viewlet no longer has a hint to commit/check in

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21185]
#20999

It's not clear that ctrl+enter would do the commit (this term would probably need to be generic for the SCM provider since not all SCM's use "commit").

![image](https://cloud.githubusercontent.com/assets/2193314/23226105/4526fb50-f8e9-11e6-9dbc-e99b0ddb09c7.png)

![image](https://cloud.githubusercontent.com/assets/2193314/23226088/35005af0-f8e9-11e6-98ac-919995fdc503.png)

Old hint:

![image](https://cloud.githubusercontent.com/assets/2193314/23226094/3b4d07e6-f8e9-11e6-9367-3e4527309b05.png)

**Comment by jordanmkasla2009** [comment]
it would seem that the placeholder isn't being set in [scmViewlet.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L242)
