### ISSUE TITLE
ReportMissingImport and ReportMissingModuleSource

### ISSUE THREAD

**Issue by AitorBascones** [microsoft/vscode#211834]
Type: <b>Bug</b>

I am receiving these two types of warnings and I don't understand. I am using the global python interpreter where all the libraries I am using are installed. I don't know what happened because this didn't happen to me before and I haven't done anything different.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.39GB (9.17GB free)|
|Process Argv|C:\\Users\\aitor\\OneDrive\\Desktop\\MASTER\\Python Master.code-workspace --crash-reporter-id 08c8993f-c21d-4ed7-af0a-fabc01dc1db2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.186.0
copilot-chat|Git|0.14.1
rainbow-csv|mec|3.11.0
vscode-docker|ms-|1.29.1
vscode-language-pack-es|MS-|1.88.2024041009
vscode-dotnet-runtime|ms-|2.0.3
debugpy|ms-|2024.4.0
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
datawrangler|ms-|1.0.0
jupyter|ms-|2024.3.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
r|REd|2.8.2
vscode-icons|vsc|12.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31022790
dwnewjupyter:31035176

```

</details>

**Comment by roblourens** [comment]
If this is an issue with the VS Code Python extension, please file an issue on the repo for the python extension with much more detail. But it sounds like it might be an issue with your code or setup.
