### ISSUE TITLE
VS Code window crashed and I lost my code edits...what should I do?

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#21183]
- VSCode Version: 1.9.1
- OS Version: Win10

Steps to Reproduce:

1. I was editing a .cpp file while debugging our C++ extension with the [Extension Development Host].

Bug: Seemingly randomly, a popup appeared that said the window crashed. All my unsaved edits were lost. Is there anything I can do to help get this fixed? I don't see any crash dumps or error logging being made. I'd prefer to avoid losing my code changes like this.

If our C++ extension is somehow causing the crash then we want to diagnose/fix the problem, but I don't know of any way our extension could be causing the window to crash.

**Comment by bpasero** [comment]
@sean-mcmanus that is bad news, sorry. we actually do frequent backups of edited files and restore them upon next restart, it is very weird that in this case this does not seem to happen. Can you have a look into the backups directory to see if maybe your content is still there? The location is: C:\Users\<user>\AppData\Roaming\Code\Backups

**Comment by sean-mcmanus** [comment]
Yeah, I only lost 5 minutes or edits or something, so maybe the back up kicked in.

**Comment by Tyriar** [comment]
The backup is meant to happen a second after you've stopped typing. So unless you were typing for 5 minutes in the same file without stopping for > 1000ms, the backups *should* have happened :smile: 

If they're not in `C:\Users\<user>\AppData\Roaming\Code\Backups` though they are likely lost. Not sure what else we can do to diagnose.

**Comment by bpasero** [comment]
@sean-mcmanus to clarify, when it restarted you got files showing up as dirty? that would mean the backups got restored.

**Comment by sean-mcmanus** [comment]
Yeah, no back up and restoration occurred then. I assume the window crash somehow prevented the backup from occurring. The file wasn't in that backup location (although I do see newly edited files there). The file with changes did not appear as dirty when the crashed window reloaded.

**Comment by bpasero** [comment]
@sean-mcmanus can you share your VS Code settings? I wonder if a setting could have an impact.

**Comment by sean-mcmanus** [comment]
My settings were all the default, except for extra files.associations (I was editing C++ files). It's possible it had something to do with the fact that I launched the VS Code instance via Launch Extension (debugging our C++ extension). In that scenario, we write a bunch of debug data to the Output window (createOutputChannel, append). I normally edit code in a non-debugging instance of VS Code. Yeah, I don't see any backup data being written when the VS Code instance is launched from Launch Extension...so I have a repro for the lack of a backups (not the window crash though).

**Comment by bpasero** [comment]
@sean-mcmanus you are doing editing inside an extension host window? That is really not encouraged, there is NO data guarantee in that window, you can even close a dirty editor without saving. And we are also not doing any backups in there.

**Comment by sean-mcmanus** [comment]
Yes, that is what happened. I used the [Extension Development Host] to test our C++ extension, then opened our source code folder and started making code changes to fix a bug (i.e. dogfooding). I didn't realize that editing wasn't such a good idea. We have to do some editing in the extension host instance to test our extension, but usually they are throw away edits. Yeah, a warning might be nice. I didn't realize there was any difference between instances.

Okay, thanks. I'll avoid making real code changes in the extension host instance.

**Comment by bpasero** [comment]
@sean-mcmanus ok good to know, closing this then.
