### ISSUE TITLE
Add Reveal in Finder as option for the unsupported files screen

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#211891]
Type: <b>Feature Request</b>

Feedback for the `The file is not displayed in the text editor because it is either binary or uses an unsupported text encoding.` page.

Opening an unsupported file from terminal links or Copilot chat only provides *Open Anyway*. In most cases I didn't even want VS Coder to handle the file but see it in finder.

VS Code version: Code - Insiders 1.90.0-insider (03dd3c3b93322b41fe108a3448308595ee7077a4, 2024-05-02T05:51:09.893Z)
OS version: Darwin x64 23.4.0
Modes:

**Comment by bpasero** [comment]
I am not convinced, you can do this from the tab context menu already or a gobal command:

<img width="483" alt="image" src="https://github.com/microsoft/vscode/assets/900690/9de30e07-2313-40cd-9ce3-11cb61264a63">
