### ISSUE TITLE
Option to customize list of opened windows

### ISSUE THREAD

**Issue by hhung01** [microsoft/vscode#211882]
When viewing the list of opened windows under the Window menu, the opened windows are listed by `[file name] - [project name]` and alphabetized.  If a different file is opened or the focus is changed to a different file, then that filename will be reflected in list and the order will change.  This makes it hard to switch between projects since the order can change.  It takes a few seconds to scan the list for the right project to switch to.  If the name is changed to `[project name] - [file name]`, then the order will be the same regardless of which file is the active one.  This way, it's much quicker to switch between open windows/projects.

**Comment by bpasero** [comment]
Can this not be done when you configure the `window.title` setting accordingly?

<img width="866" alt="image" src="https://github.com/microsoft/vscode/assets/900690/71a3a2ed-1188-41fc-8eca-cb70128305c8">

**Comment by hhung01** [comment]
Yes!  This is exactly what I was looking for!  I wasn't able to find it before, hence this request.  But yes, this does exactly what I want!

Thank you!
