### ISSUE TITLE
SCMs should be able to set the title and icon of the SCM viewlet

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21195]
#20999

This was brought up before, not sure where that went but consider the following screenshot:

![image](https://cloud.githubusercontent.com/assets/2193314/23227196/0a937974-f8ed-11e6-9aeb-78ef13bdca76.png)

As a user I have no idea what that button is going to do unless I read about it on the internet.

**Comment by joaomoreno** [comment]
After some discussion, this won't happen. The Debug viewlet doesn't change its icon or title when we debug a Go app.

We need some affordance to show what's the current provider, though. #23437

**Comment by Tyriar** [comment]
I do like the current icon a lot more, attractive and reasonably generic :+1:
