### ISSUE TITLE
Opening another application causes VSCode to capture the "Return/Enter" multiple times

### ISSUE THREAD

**Issue by olafurw** [microsoft/vscode#211955]
Type: <b>Bug</b>

So this is a weird one. I'm on Ubuntu 24.04 and I noticed that when I pressed the "super" key and type Firefox and hit Enter to open Firefox, that enter command gets "stuck" and VSCode will press Enter multiple times.

This does not happen with other applications. So if I open Text Editor and then open Firefox, text editor will not add a bunch of Enter commands into the window.

Also this only happens with "heavy" applications. So if I have VSCode open and open Text Editor, that "Enter" command to open Text Editor will not stick.

This is very annoying because if you have VSCode open in some code file and then open Firefox, then a bunch of newlines will be added to the file.

Repro is basically.
Ubuntu 24.04.
Open VSCode and have it focused.
Press the super/win button. Type "Firefox", press Enter.
See that a lot of the enter commands are being captured by VSCode.

Here is a video of me reproducing it: https://www.youtube.com/watch?v=-etKd8sNq18

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:08:25.066Z)
OS version: Linux x64 6.8.0-31-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1260P (16 x 1592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|30.96GB (18.88GB free)|
|Process Argv|--crash-reporter-id cb2c1553-3317-4376-b936-680725b39c7b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.4
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
copilot|Git|1.186.0
copilot-chat|Git|0.15.0
vscode-typescript-next|ms-|5.5.20240502
svelte-vscode|sve|108.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by liheyuan** [comment]
may be a wayland problem see https://github.com/microsoft/vscode/issues/212430

**Comment by olafurw** [comment]
Does not happen anymore after normal package updates and kernel/os updates.
