### ISSUE TITLE
ipynb files doesent open

### ISSUE THREAD

**Issue by jocastrocUnal** [microsoft/vscode#211900]
Type: <b>Bug</b>

Since the update, in my ubuntu 22.04 i cant open any notebook. I reinstall de file, reinstal de complements.

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:08:25.066Z)
OS version: Linux x64 6.5.0-28-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 4199)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.22GB (20.02GB free)|
|Process Argv|--crash-reporter-id 4fde2844-528d-4ffe-b270-a8a8356bdfda|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.186.0
copilot-chat|Git|0.15.0
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.4.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
chatpanelt:31018789
dsvsc021:30996838
jg8ic977:31013176
pythoncenvptcf:31022791
dwnewjupytercf:31035177

```

</details>

**Comment by rebornix** [comment]
@DonJayamanne I wonder if it could be our changes in ipynb extension.

**Comment by DonJayamanne** [comment]
@jocastrocUnal Sorry you are running into this issue.
Are you still running into this problem?
Please can you share a screenshot of the error you get when you try to open the ipynb files
Can you open dEv tools using `Toggle Developer Tools`, and then go into the Console window and see if there are any errors once you've tried to open ipynb files, if there are any please share the screenshot of logs of the errors.

@rebornix Unlikely, it should not cause anything to fall over, besides I would have expected a lot more users to report issues.

**Comment by jocastrocUnal** [comment]
Wen the file has big outputs, the file size is also big (100 - 200 mb). We i clear the outputs and reopen the notebook the error is solve.
