### ISSUE TITLE
Bug: Terminal shellArgs ignored

### ISSUE THREAD

**Issue by tracker1** [Microsoft/vscode#21194]
- VSCode Version: 1.9.1  f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. Set User Settings as follows:

    "terminal.integrated.shellArgs.osx": ["-l"],

2. Open terminal view

The terminal seems to be ignoring the shellArgs for the platform.

---

edit: I was able to get it to work with the following...

    "terminal.integrated.shellArgs.osx": ["--init-file", "~/.profile"],

I'm now  unsure if this is an issue with an update to macOS, or if it's related to vscode

**Comment by Tyriar** [comment]
"-l" definitely pulls in `~/.bash_profile`, you may want to source `~/.profile` from that file if that's the behavior you're after? (or keep as is)

**Comment by tracker1** [comment]
@Tyriar yeah.. something else had put something into a fresh `~/.bash_profile`, which is what was being loaded instead of the `~/.profile` ... since corrected.  Sorry for neglecting to update this issue here.

Aside: *love* the integrated terminal (though wouldn't mind seeing the first 2-3 as tabs, as that'd make it easier to switch between them.  Usually have 2-3 terminals as one to run the project with a watcher (nodemon) another for git/npm commands while working, and sometimes another running node cli for interactive bits.

**Comment by Tyriar** [comment]
@tracker1 glad you're liking it, I'll be looking into splitting the terminal soon which would let you have more than 1 terminal visible at a time.
