### ISSUE TITLE
Generic SCM icon is not consistent with other icons

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21192]
#20999

- Stroke is not as strong
- Border isn't as crisp
- Different size: 20x24 (scm) vs 19x23 (explorer)

![image](https://cloud.githubusercontent.com/assets/2193314/23226907/20bcdf70-f8ec-11e6-8b9c-f5f286e895a9.png)

![image](https://cloud.githubusercontent.com/assets/2193314/23227000/718fb2d8-f8ec-11e6-84e4-b1de2d18c878.png)

**Comment by rkeithhill** [comment]
And it looks too much like the Explorer icon and it lacks any sort of "character".  I'd prefer the icon default to Git when no workspace is opened and then switch to a particular SCM's icon when the type of SCM is detected.

**Comment by joaomoreno** [comment]
Not applicable any more. Went through a bunch of icons yesterday with @egamma and settled on

![image](https://cloud.githubusercontent.com/assets/22350/24444181/d0de6182-1465-11e7-926d-abb22055866f.png)
