### ISSUE TITLE
BUG: Code text is beyond scrollbars if interface scale (zoom) is used

### ISSUE THREAD

**Issue by psnet** [microsoft/vscode#211910]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.89.0 (user setup)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10

Steps to Reproduce:

1. Set IDE interface scale to
```json
{
"window.zoomLevel": 3.5
}
```
2. Put long text / code in editor so horizontal and vertical scrollbars appears
3. Code is beyond scrollbars, so accessibility of scrollbars is poor and it becomes less usable
![зображення](https://github.com/microsoft/vscode/assets/1023918/c412f455-02d0-4e47-9d4d-62cd4fa275cc)

**Comment by alexdima** [comment]
@psnet The colors of the scrollbar can be configured and be made opaque e.g.:

```
"workbench.colorCustomizations": {
	"scrollbarSlider.background": "#ccc",
	"scrollbarSlider.activeBackground": "#fff",
	"scrollbarSlider.hoverBackground": "#ddd",
},
```

**Comment by psnet** [comment]
@alexdima You mean that text beyond scrollbars is ok? (even if they can be semitransparent)

**Comment by alexdima** [comment]
Yes, we leave gaps around code so that code will be visible when scrolling.

**Comment by psnet** [comment]
I mean is it allowed to code be right behind scrollbar (in its background)? Because of it only happens if scale (zoom) is used

**Comment by alexdima** [comment]
Text is always allowed to be behind the scrollbar, unrelated to zoom. This is visible because the scrollbars we have are transparent and disappear when the mouse stops moving or when scrolling stops.

**Comment by psnet** [comment]
Ok, than this is not issue, just normal behavior and I will close this ticket. Thanks for explaining.
