### ISSUE TITLE
Spurious ${LOCALAPPDATA} folder created when hovering a dependency name in package.json

### ISSUE THREAD

**Issue by Septh** [microsoft/vscode#211914]
Type: <b>Bug</b>

1. Open any folder with a `package.json` file.
2. Hover any dependency name in `package.json` to display the package's details.
3. An extra folder named `${LOCALAPPDATA}` appears in the same directory where the `package.json` file resides.

![image](https://github.com/microsoft/vscode/assets/11949623/bbd5699c-9647-4d38-8bed-02a15a5e7416)

It appears from the logs in that folder that `vscode` launches `npm view` to get the package details:

![image](https://github.com/microsoft/vscode/assets/11949623/f102ccfa-2f42-47f7-8cec-b910922c273d)

So I tried the same command from the shell:

```bash
npm view --json -- eslint description dist-tags.latest homepage version time
```

The extra folder was not created.

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700K (20 x 3610)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (17.10GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id 365a2674-a228-4abd-82c2-408321056497|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by aiday-mar** [comment]
Not sure who to assign this to. I was wondering @joaomoreno if you would know?

**Comment by Septh** [comment]
I did some digging and it turns out that this may well be a bug in Node's `execFile` API.

The following script is a stripped down version of [the npmView() method](https://github.com/microsoft/vscode/blob/a041421d02c58b0a107c6d7e12f2ee636b5b9d94/extensions/npm/src/features/packageJSONContribution.ts#L286) in the VSCode's builtin npm extension.

```javascript
import { execFile } from 'node:child_process'
import which from 'which'

const npmCommandPath = await which(process.platform === 'win32' ? 'npm.cmd' : 'npm')
const pack = 'eslint'

const result = await new Promise((resolve, _reject) => {
    const args = ['view', '--json', '--', pack, 'description', 'dist-tags.latest', 'homepage', 'version', 'time']
    const cwd = process.cwd()

    // corepack npm wrapper would automatically update package.json. disable that behavior.
    // COREPACK_ENABLE_AUTO_PIN disables the package.json overwrite, and
    // COREPACK_ENABLE_PROJECT_SPEC makes the npm view command succeed
    //   even if packageManager specified a package manager other than npm.
    const env = { COREPACK_ENABLE_AUTO_PIN: "0", COREPACK_ENABLE_PROJECT_SPEC: "0" }
    execFile(npmCommandPath, args, { cwd, env, shell: true }, (error, stdout) => {
        if (!error) {
            try {
                const content = JSON.parse(stdout)
                const version = content['dist-tags.latest'] || content['version']
                resolve({
                    description: content['description'],
                    version,
                    time: content.time?.[version],
                    homepage: content['homepage']
                })
                return
            } catch (e) {
                // ignore
            }
        }
        resolve(undefined)
    })
}).catch(e => null)

console.log(result)
```

When run from the command line, the script creates the `${LOCALAPPDATA}` folder, just like VSCode does. However, **if I remove the `env` option object in the call to `execFile()`, then the folder is not created**. I confirmed this with the latest versions of Node 21, 20, 18 and 16.

The `env` object was added in #210601.

Not sure where to go from here.

One last remark: the `shell: true` option is now mandatory to run `.cmd` files on Windows with `execFile()` - this is something to keep in mind when upgrading the version of Electron used in VSCode.

**Comment by frankli0324** [comment]
should be resolved by https://github.com/microsoft/vscode/pull/213306

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/pull/213306 fixes the issue
