### ISSUE TITLE
Type checker continues type checking after type conversion removed

### ISSUE THREAD

**Issue by MIchaelMainer** [Microsoft/vscode#2119]
Repro step:
1) Add .d.ts file that contains a type definition for a class that doesn't contain a member referenced in the code file. In the attached image, I change the first line to <code> var imageRange = context.document.getSelection() as Word.Range;</code>. <code> Word.Range</code> showed as IntelliSense (auto-completion)
2) Then the type checker gives the warning you see in the image, 'Property X does not exist on type Y.' This behavior is correct as that property is not listed in the .d.ts file. (it is in the js library).
3) Then, if I remove the <code>as Word.Range</code> conversion from the first line, I'd expect that the warning would go away since I'd expect that the type check would go away. The actual behavior is that it looks like it is using a type check cache -- I removed the type conversion for the variable but it still states that the property doesn't exist on the object. I'd expect that message to go away as the code doesn't provide the object type. 

![capture](https://cloud.githubusercontent.com/assets/8527305/12442639/6e3cf968-bf06-11e5-8f6a-02cc4213c9f2.PNG)

**Comment by jrieken** [comment]
@weinand Please do not assign typescript items to me

**Comment by MIchaelMainer** [comment]
This issue would only come up if the definitions are not in sync with the library.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#6557
