### ISSUE TITLE
intellisense doesn't include the completion I want

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#211996]
Steps to Reproduce:

1. type `git checkout -- .` and press `enter`
:bug: intellisense completion was added for the argument instead of running the command

I have a pretty strong muscle memory to run that command, so now I need to remember to press escape before pressing enter

![image](https://github.com/microsoft/vscode/assets/2019016/e05a468c-d5c5-42a7-9b63-a68e85c91518)

**Comment by amunger** [comment]
this is bad enough that I've turned the feature off, I can't even use `git status`

**Comment by amunger** [comment]
one change that would make this much less painful: ctrl+z should undo the auto-complete change as a single action (as is the case with the text editor). 
I press enter really quickly, after typing what I want, and if auto-complete provides something I didn't want, ctrl+z will undo one character at a time.

**Comment by Tyriar** [comment]
Well powershell does support ctrl+z itself. We may be able to undo everything, or nearly everything by using bracketed paste mode, since you can paste something and undo it fine.

**Comment by Tyriar** [comment]
Just tried with Posh-Git and while the commands (`checkout`) and aliases (`co` in mine) work, it still doesn't suggest `.` after checkout:

<img width="859" alt="Screenshot 2024-06-14 at 9 56 45 AM" src="https://github.com/user-attachments/assets/042b751f-4ed2-4858-bba2-7722854c7b30">

**Comment by Tyriar** [comment]
`(TabExpansion2 -inputScript "git co " -cursorColumn 7).CompletionMatches` doesn't show files/folders so we couldn't use that. Maybe using the current completion call, but also providing `.`, `..`, etc. when there are only `ProviderContainer` and `ProviderItem` entries?


```
~/dev/Tyriar/xterm.js [tyriar/vscode_213174 ≡]> (TabExpansion2 -inputScript "git co ." -cursorColumn 8).CompletionMatches

CompletionText           ListItemText                  ResultType ToolTip
--------------           ------------                  ---------- -------
./.devcontainer          .devcontainer          ProviderContainer /Users/tyriar/dev/Tyriar/xterm.js/.devcontainer
./.editorconfig          .editorconfig               ProviderItem /Users/tyriar/dev/Tyriar/xterm.js/.editorconfig
./.eslintrc.json         .eslintrc.json              ProviderItem /Users/tyriar/dev/Tyriar/xterm.js/.eslintrc.json
./.eslintrc.json.typings .eslintrc.json.typings      ProviderItem /Users/tyriar/dev/Tyriar/xterm.js/.eslintrc.json.typings
./.git                   .git                   ProviderContainer /Users/tyriar/dev/Tyriar/xterm.js/.git
./.gitattributes         .gitattributes              ProviderItem /Users/tyriar/dev/Tyriar/xterm.js/.gitattributes
./.github                .github                ProviderContainer /Users/tyriar/dev/Tyriar/xterm.js/.github
./.gitignore             .gitignore                  ProviderItem /Users/tyriar/dev/Tyriar/xterm.js/.gitignore
./.gitmodules            .gitmodules                 ProviderItem /Users/tyriar/dev/Tyriar/xterm.js/.gitmodules
./.mailmap               .mailmap                    ProviderItem /Users/tyriar/dev/Tyriar/xterm.js/.mailmap
./.mocha.env             .mocha.env                  ProviderItem /Users/tyriar/dev/Tyriar/xterm.js/.mocha.env
./.mocharc.yml           .mocharc.yml                ProviderItem /Users/tyriar/dev/Tyriar/xterm.js/.mocharc.yml
./.npmignore             .npmignore                  ProviderItem /Users/tyriar/dev/Tyriar/xterm.js/.npmignore
./.npmrc                 .npmrc                      ProviderItem /Users/tyriar/dev/Tyriar/xterm.js/.npmrc
./.nvmrc                 .nvmrc                      ProviderItem /Users/tyriar/dev/Tyriar/xterm.js/.nvmrc
./.vscode                .vscode                ProviderContainer /Users/tyriar/dev/Tyriar/xterm.js/.vscode
```

**Comment by Tyriar** [comment]
Looks promising 👀 

<img width="861" alt="Screenshot 2024-06-14 at 10 11 11 AM" src="https://github.com/user-attachments/assets/6f289cc9-794a-4c88-9dcc-02605b44505e">
