### ISSUE TITLE
PromptInputModel: Adjust start of prompt input based on input and prompt terminator

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#211945]
Related: https://github.com/microsoft/vscode/issues/211222

Repro:

1. Set "terminal.integrated.developer.devMode": true
2. windows 11/pwsh
3. Create a new terminal and quickly type `g` (or anything)

🐛 the status bar says `|`, not `g|` (or something like `g|[it push]` based on history):

![image](https://github.com/microsoft/vscode/assets/2193314/66ee6ab4-14c3-491e-ad06-74c54cab3bee)

Type `i`

🐛 the status bar starts with `i|`, not `gi|`:

![image](https://github.com/microsoft/vscode/assets/2193314/e3b98924-9b04-4a97-a0bd-f83758cbb0bd)

**Comment by andreamah** [comment]
![image](https://github.com/microsoft/vscode/assets/31675041/e2a464a5-a35e-4a22-9556-098e3c1e2907)
For some reason, only the `|` character is showing in my status bar, regardless of what I type 🤔

**Comment by amunger** [comment]
might have just needed a reload after adding that setting. It does not behave well without reloading, either Andrea's case or growing unnecessarily:
![image](https://github.com/microsoft/vscode/assets/2019016/73859d31-95b5-4a83-bbc3-95b137719aa0)

After reloading it works fine
