### ISSUE TITLE
Notebook breadcrumbs are tied to OutlinePane filters

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#211998]
This is related to `recomputeActive` inside the notebook outline provider. Right now, since this was previously acting as a filter layer, turning off code cells for the outline pane would prevent a recompute of the active element. 

🐛 if you turn off code cells for the outline pane, you will not get any recomputing of the breadcrumbs as you click around code cells. it will only be triggered if you click on an md cell.

🐛 the notebook setting gotosymbols show all symbols is only ever respected when code cells is turned on in the outline

**Comment by andreamah** [comment]
@Yoyokrazy do you have some simple verif steps for this?

**Comment by Yoyokrazy** [comment]
Verification steps:

- open attached notebook
- ensure `breadcrumbs.enabled` is enabled
- ensure `notebook.breadcrumbs.showCodeCells` is enabled
- ensure `notebook.outline.showCodeCells` is DISABLED

Stable (🐛) behavior:
- Click around notebook cells and:
  - breadcrumbs will ONLY update when clicking on the markdown header cells
  - breadcrumbs will never show code cells

Insiders (Fixed) behavior:
- Click around the notebook cells, watching to make sure that the breadcrumbs above the toolbar update correctly.

```json
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# h1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print('test')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# h2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print('test2')"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```
