### ISSUE TITLE
Speed up wrapping points computation

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#21196]
- VSCode Version: <code>Code - Insiders 1.10.0-insider (256d76fed7947e7289f921df10658d7a69233b65, 2017-02-22T07:09:05.746Z)</code>
- OS Version: <code>Linux x64 4.8.0-34-generic</code>
- CPUs: <code>Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2899)</code>
- Memory (System): <code>11.64GB (1.91GB free)</code>
- Memory (Process): <code>170.14MB working set (170.14MB peak, 101.30MB private, 68.84MB shared)</code>
- Load (avg): <code>1, 1, 1</code>
- VM: <code>0%</code>
- Initial Startup: <code>no</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|209|
|renderer|require(workbench.main.js)|758|
|renderer|create extension host => extensions onReady()|869|
|renderer|restore viewlet|532|
|renderer|restore editor view state|856|
|renderer|overall workbench load|1215|
|main + renderer|start => extensions ready|1908|
|main + renderer|start => workbench ready|2202|

---

Testing #20999

When I click on a viewlet button it takes about 500ms to open/hide the viewlet in question. It's instant on stable. Note that the window is otherwise behaving responsively so it's unrelated to https://github.com/Microsoft/vscode/issues/21008

`SplitLinesCollection._constructLines`/`ILineMapperFactory.createLineMapping` seem to be at fault.

![image](https://cloud.githubusercontent.com/assets/2193314/23227481/f3cafdba-f8ed-11e6-9c53-abb5304a4d57.png)

![image](https://cloud.githubusercontent.com/assets/2193314/23227662/83b3d816-f8ee-11e6-84b1-4083458a7d2b.png)

**Comment by alexandrudima** [comment]
@Tyriar I would need the file you are opening and the settings you are using (probably wordWrap on?). 

From the stack it looks like the view model is computing wrapping points as a reaction to a layout change (i.e. resize perhaps?).

Thanks!

**Comment by Tyriar** [comment]
Ah, turns out the file is 133004 lines long. Is there any way to get around recomputing wrapping point for the entire file?

**Comment by alexandrudima** [comment]
Ok, that would explain the slowness. 

We need to compute the mapping for the entire file because:
* we need to know the editor's scrollHeight to be able to render the scrollbar (which is given by the number of view lines)
* we need to paint decorations in the overview ruler that might sit below the viewport

If you share the file and the settings (probably word wrap should suffice?) I can try to take a look again at v8's IR for the wrapping points computation function. Last time I looked there seemed to be nothing more I could do to make it faster in JS.

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/viewModel/characterHardWrappingLineMapper.ts#L78

**Comment by Tyriar** [comment]
Here are the settings that would have an impact:

```js
  "editor.renderIndentGuides": true,
  "editor.rulers": [ 80, 100, 120 ],
  "editor.wordWrap": true,
```

Turning off word wrap gets rid of the delay.

The file is a json file with very few wrapping lines, it's approximate structure is the following repeated about 16000 times:

```

{"id":"some hash",
	"name":"code-insiders",
	"version":"1.10.0-1486968997",
	"owner":"vscode",
	"repositoryId":"some hash",
	"sourceUrl":"https://az764295.vo.msecnd.net/insider/422d7ff1b78fcac514498921551c33a988c4ad34/code-insiders_1.10.0-1486968997_amd64.deb",
	"dataFileName":"code-insiders_1.10.0-1486968997_amd64.deb"}
```

**Comment by alexandrudima** [comment]
This can be done faster if we implement it in C++

**Comment by alexdima** [comment]
For verification, you can try with the following file: (40000 lines, 5MB): [wrapping-large.zip](https://github.com/microsoft/vscode/files/4044492/wrapping-large.zip)
