### ISSUE TITLE
Git: Stage gives ambiguous error message

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21199]
#20999

In file with local changes I did Git: Stage via the command palette:

![image](https://cloud.githubusercontent.com/assets/2193314/23228435/52bb8ddc-f8f1-11e6-82ca-a6d3b1d21b14.png)

**Comment by Tyriar** [comment]
Also occurs with Git: Unstage

**Comment by joaomoreno** [comment]
#21137
