### ISSUE TITLE
Filter gone from Explorer

### ISSUE THREAD

**Issue by andrewkincaid** [microsoft/vscode#211974]
Type: <b>Bug</b>

Previously, I could press CMD+F inside the Explorer, and I could filter the results.  Now, pressing CMD+F brings up the Search in the main editor window.

VS Code version: Code 1.89.0 (Universal) (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:10:10.196Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|19, 18, 9|
|Memory (System)|32.00GB (0.21GB free)|
|Process Argv|/Users/andrew.kincaid/Library/CloudStorage/OneDrive-ServiceNow/Scratch --crash-reporter-id 3b5572ae-2ec4-4443-8e8e-5d6c1bc22749|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
batch-replacer|ang|1.2.1
unique-lines|bib|1.0.0
vscode-eslint|dba|2.4.4
githistory|don|0.6.20
code-runner|for|0.12.2
ecdc|mit|1.8.0
hexeditor|ms-|1.10.0
sqltools|mtx|0.28.3
htmlescape-vscode-extension|ray|0.0.7
vscode-xml|red|0.26.1
code-spell-checker|str|3.0.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
chatpanelc:31018788
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by IllusionMH** [comment]
This change was announced in recent update https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding

But you can rebind command to your preference

**Comment by andrewkincaid** [comment]
Oh... Thank you SO much!!
