### ISSUE TITLE
with explorer can't search trough files anymore

### ISSUE THREAD

**Issue by J1327** [microsoft/vscode#211985]
Does this issue occur when all extensions are disabled?: YES

- VS Code Version:  Latest or as today 1.89.0 or 1.90.0
- OS Version: Win11x64

Steps to Reproduce:

1. Open any existing project folder with in vs code
2. try pressing CTRL + F and as result search bar won't appear or instead forces to use file editor search bar.

works fine on 1.88.1.

**Comment by IllusionMH** [comment]
This change was announced in recent update https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding

But you can rebind command to your preference
