### ISSUE TITLE
Home and End Key don't Work as Expected in the Filter Textbox on the Debug Console View

### ISSUE THREAD

**Issue by sunliangqin** [microsoft/vscode#211979]
Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1.  Navigate to the Debug Console view
2.  Enter some text in the input box
3.  Press Home
    - Actual: nothing happened
    - Expected: cursor moves to the beginning of the text
4. Press End
    - Actual: focus moved to "Clear console"
    - Expected: cursor moves to the end of the text

**Comment by roblourens** [comment]
What OS, Windows?

**Comment by roblourens** [comment]
Oh, I can repro, very strange...

**Comment by roblourens** [comment]
This happens in all the `FilterViewPane` filter inputs, like Problems. Seems like it's related to the fact that this input is an item in an ActionBar and the focus logic there is messing with what you expect in an input. I also see that sometimes tab gets stuck in that input, and there is some custom code to customize some of this already: https://github.com/microsoft/vscode/blob/484cd68eff220ebb03b41b0e04d6956c1c742cb2/src/vs/workbench/browser/parts/views/viewFilter.ts#L238-L248

**Comment by sandy081** [comment]
@roblourens I am on Mac and for me cmd+left and cmd+right keys are working as expected. Moreover above handler captures only `Tab` key. Is there something I am missing?

**Comment by sunliangqin** [comment]
@sandy081 I can consistently repro this issue on Windows. I'm not sure if it reproes on Mac or not.

**Comment by sandy081** [comment]
Fixed by https://github.com/microsoft/vscode/pull/217200

**Comment by roblourens** [comment]
The code I linked is a separate issue that I saw, which probably isn't really related to what you fixed. But if I put focus in the Problems or Debug Console filter input, and do some combination of tab out of the input, shift+tab back into it, type in it, then at some point focus gets stuck in the widget and 'tab' doesn't move focus out to the next toolbar.

**Comment by sandy081** [comment]
> But if I put focus in the Problems or Debug Console filter input, and do some combination of tab out of the input, shift+tab back into it, type in it, then at some point focus gets stuck in the widget and 'tab' doesn't move focus out to the next toolbar.

Since this is fixed and close, can you please create a separate issue for it?
