### ISSUE TITLE
Is "Clean Changes" the best choice of words?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21198]
#20999

The words "clean" and "dirty" are more technical than they need to be imo, something like "undo local changes" might be more generally understandable?

![image](https://cloud.githubusercontent.com/assets/2193314/23227810/09296c5e-f8ef-11e6-9d8a-3d5d16057c51.png)

It has been a while since I learned the meaning of these words but some developers may not know?

**Comment by joaomoreno** [comment]
#20810
