### ISSUE TITLE
Debug hover information disappears too easily

### ISSUE THREAD

**Issue by fabiosantoscode** [microsoft/vscode#211917]
Type: <b>Bug</b>

1. Type out the following code into `index.js`
```js
let x = { a: 1, b: 2, c: 3 };

debugger;
```
2. Run `node index.js` in a debug terminal
3. Hover `x` to see its contents
4. Move your mouse from `x` to the popup in a diagonal, such that the mouse briefly leaves "x" and the popup, and then moves to the popup

What I would expect:
The popup remains open, because even though the mouse left "x" and the popup for a moment, it is now over the popup.

What actually happens:
The popup remains open for a brief moment, and then closes, even though the mouse is over it.

I recorded a short video illustrating the issue. It's for an older VSCode version but the issue remains the same:
https://github.com/microsoft/vscode/assets/1611595/18845ba5-555c-441f-bbe5-05a922345af0

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 6.1.69

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (10.52GB free)|
|Process Argv|--crash-reporter-id 83c0d656-767e-4a63-9216-9ad55f624068|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: localhost|
|OS|Linux x64 6.1.69|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (4 x 3600)|
|Memory (System)|15.63GB (13.85GB free)|
|VM|75%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.110.1
remote-explorer|ms-|0.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
chatpanelt:31018789
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by connor4312** [comment]
There's been some overall discussion about this in hovers, @benibenj please fold this into an existing issue if you have one.

**Comment by benibenj** [comment]
Haven't seen such an issue yet. Assigning @aiday-mar as she owns editor-hovers and has been doing work in this area.

**Comment by aiday-mar** [comment]
Hi yes, I believe the issue here concerns the debug hover which is mostly independent of the editor hover. The editor hover has a configurable `hiding delay` in the settings which controls how long to wait before hiding the hover when the mouse is outside of the hover.

**Comment by fabiosantoscode** [comment]
I'm not familiar with this project, but it seems to me that the issue is about canceling a closing action. The "close later" timer should be started, but when the mouse moves onto the hover, that timer should be cancelled.

My video shows that the mouse is able to get onto the hover, but it closes after that.

https://github.com/microsoft/vscode/assets/1611595/18845ba5-555c-441f-bbe5-05a922345af0

**Comment by connor4312** [comment]
Oh, got it, I misunderstood. That may actually just be a bug in debug land, separate from previous discussion about the 'closer' logic. I'll look into it.

**Comment by capegreg** [comment]
The short delay makes copying variable values on hover very difficult, whereas in prior versions it was working better.

https://github.com/microsoft/vscode/assets/1051118/feaf1b14-4d9f-4daf-9ca2-2dda65128214

Version: 1.89.1 (user setup)
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
