### ISSUE TITLE
Accessibility sound signals delay not configurable

### ISSUE THREAD

**Issue by adns44** [microsoft/vscode#211948]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.89.0
- OS Version: Windows 11 Pro Version 23H2 (OS Build 22631.3447)

Steps to Reproduce:

1. Make an error in a program code
2. Navigate to this line with screen reader.

Hi All,

My problem occurs since the latest VsCode update. When an error detected on a line, the accessibility error signal delay too high. If I navigate too quick, I do not hear the sound.

How can I edit this value? The changelog states that there is an option for this, however, I can not find that.

**Comment by meganrogge** [comment]
thanks for the report, we plan to add this in May https://github.com/microsoft/vscode/issues/211363
