### ISSUE TITLE
Command vscode.editorChat.start is missing

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#211988]
This commit
https://github.com/microsoft/vscode/pull/211902/files#diff-a0ddbc8d458e220a4e838b0039bd79f8607a616964991400062c21bbea96f2cf

removed the ApiCommand `vscode.editorChat.start`, but this is invoked in many places inside vscode and in the copilot chat extension

**Comment by Bartosh-s** [comment]
+1

**Comment by magnocarvalho** [comment]
Same probleme here =/

**Comment by cdkisa** [comment]
+1

**Comment by wxxsfxyzm** [comment]
same

**Comment by RacketyWater7** [comment]
just got this problem. it occurs when I click on the "Fix using Copilot" on an issue's quick fix options.

**Comment by jrieken** [comment]
Sorry for that. I have done some cleanup and accidentially removed that command. https://github.com/microsoft/vscode/pull/212068 will restore it
