### ISSUE TITLE
styles.css file not working

### ISSUE THREAD

**Issue by IT-Nish** [microsoft/vscode#211907]
Type: <b>Bug</b>

my styles.css files is not working i have remaked the css files not a single code is working.

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz (2 x 2926)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: unavailable_off<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|5.87GB (2.20GB free)|
|Process Argv|--crash-reporter-id 483f81b3-af4f-4819-8f3c-5d2bef0d78f5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
amazon-q-vscode|ama|1.1.0
aws-toolkit-vscode|ama|3.1.0
blackbox|Bla|1.3.17
remote-wsl|ms-|0.88.2
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r6:30993542
dsvsc020:30976470
pythonait:31006305
showvideoc:31016891
chatpanelt:31018789
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by aeschli** [comment]
How is this related to VS Code?

Please detailed steps and a code sample to reproduce.

**Comment by IT-Nish** [comment]
Dear Sir,

 

Please check the index.html file and styles.css files code, the html file works fine burt from css file I didn’t get any output. I have shown the basic code to unsure what is the issue but I couldn’t find it.


 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

R

 

 

 








 






Regards,

Nishant R Parashar
IT Executive, Global Wind Power LTD


 <tel:+91%2093282%C2%A05780> +91 93282 57801  |   <https://www.gwpl.co.in/> www.gwpl.co.in  |   ***@***.***> ***@***.***
