### ISSUE TITLE
Error when trying to init a git repo

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21190]
#20999

Steps to repro:

1. Open a folder without a git repo
2. Type something in the commit message (not sure if this made a difference)
3. Press init repo button, error
4. Remove message
5. Press init repo button, error

![image](https://cloud.githubusercontent.com/assets/2193314/23226725/79d09378-f8eb-11e6-9a02-0a6ee9a55f85.png)

Git output:

```
Using git 2.9.3 from git
git rev-parse --show-toplevel
git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git

fatal: Not a git repository (or any of the parent directories): .git

fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by joaomoreno** [comment]
#21095
