### ISSUE TITLE
js ts crashed

### ISSUE THREAD

**Issue by levdalba** [microsoft/vscode#211932]
Type: <b>Bug</b>

js ts servers crashed 5 times in last 5 minutes

VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 6, 5|
|Memory (System)|18.00GB (1.35GB free)|
|Process Argv|--crash-reporter-id 6605b180-e8fd-4aef-831c-d0d026c10056|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-intelephense-client|bme|1.10.4
codescene-vscode|cod|0.7.1
gitignore|cod|0.9.0
composer-php-vscode|DEV|1.45.15272
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.45.15272
profiler-php-vscode|DEV|1.45.15272
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.9.1
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
codespaces|Git|1.16.20
copilot|Git|1.186.0
copilot-chat|Git|0.14.1
vscode-pull-request-github|Git|0.86.1
RelativePath|jak|1.5.0
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.6.0
python|ms-|2024.4.1
vscode-pylance|ms-|2024.4.1
material-icon-theme|PKi|5.1.0
LiveServer|rit|5.7.9
swdc-vscode|sof|2.7.11
pdf|tom|1.2.2
material-theme|zhu|3.17.2
php-intellisense|zob|1.3.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
showvideot:31016892
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Thanks for checking. Could you share a file/project which causes this too. The server should never crash, even with an invalid json file

**Comment by levdalba** [comment]
Those two are main sources of errors

**Comment by levdalba** [comment]
https://github.com/levdalba/Ecommerce-shop you can check whole repository
if you want

**Comment by mjbvz** [comment]
How do you repo the crash? Just opening Ts files doesn't seem to cause it

**Comment by levdalba** [comment]
There was no visual side error. i just had lot of errors and it seems it
was causing those crashes.

**Comment by levdalba** [comment]
close it
