### ISSUE TITLE
gibberish characters in Terminal between output and prompts

### ISSUE THREAD

**Issue by bolducs** [microsoft/vscode#211972]
Type: <b>Bug</b>

My VSC Insider was updated today, and since then, I see extra material between any response from git and the next prompt. The extra material seem to be related with the path for my local repo. For example, the part between "\x0a\x1b[32mREDMOND" and "\x1b[0m":
$ git status
On branch svnielse-suzanne-analytics-build24
Your branch is up to date with 'origin/svnielse-suzanne-analytics-build24'.

nothing to commit, working tree clean
\x0a\x1b[32mREDMOND+sbolduc@NU-SBolduc \x1b[35mMINGW64 \x1b[33m/c/adow/businessapps-copilot-docs-pr\x1b\x0a$ svnielse-suzanne-analytics-build24)\x1b[0m
REDMOND+sbolduc@NU-SBolduc MINGW64 /c/adow/businessapps-copilot-docs-pr (svnielse-suzanne-analytics-build24)
$ 

This material doesn't appear in my other VSC version:
Version: 1.89.0 (user setup)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

VS Code version: Code - Insiders 1.90.0-insider (a1f2ea3162c704a5890c35dde4df6ee46283d957, 2024-05-03T05:49:15.006Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.39GB (15.79GB free)|
|Process Argv|--crash-reporter-id 994b1511-752e-4ac4-9786-a1006bb06b8e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.2.3
vscode-markdownlint|Dav|0.55.0
docs-article-templates|doc|1.0.3
docs-authoring-pack|doc|1.0.1
docs-build|doc|0.4.2
docs-images|doc|1.0.1
docs-markdown|doc|1.0.7
docs-preview|doc|1.0.5
docs-scaffolding|doc|1.0.4
docs-yaml|doc|1.0.1
copilot|Git|1.186.856
copilot-chat|Git|0.16.2024050301
Learn-Training-AI-Assistant|Lea|1.0.37
markdown-shortcuts|mdi|0.12.0
vscode-dotnet-runtime|ms-|2.0.3
vscode-yaml|red|1.14.0
code-spell-checker|str|3.0.1
markdowntable|Tak|0.11.0
errorlens|use|3.17.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
ccp2r3:30958153
pythonait:30973460
showvideot:31016890
chatpanelt:31014475
bdiig495:31013172
pythoncenvpt:31022790
a69g1124:31018687
88717513:31021561
dvdeprecation:31036532
pythonprt:31036556
dwnewjupytercf:31035177

```

</details>

**Comment by caleteeter** [comment]
Same for me on v1.90.0

\x0a$ 1b[32m \x1b[35mMINGW64 \x1b[33m~\x1b[36m\x1b[0m

Version: 1.90.0-insider (user setup)
Commit: a1f2ea3162c704a5890c35dde4df6ee46283d957
Date: 2024-05-03T05:49:15.006Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by jtsom** [comment]
FYI, same for a Powershell terminal, and it's not limited to Git managed directories - this is from the root of my E:\ drive:

![image](https://github.com/microsoft/vscode/assets/13488/7561369e-f19c-44ae-9d3f-a97472512b7d)

**Comment by meganrogge** [comment]
for pwsh, this is a duplicate. /duplicate #211922

for bash, this has already been fixed with https://github.com/microsoft/vscode/pull/211963
