### ISSUE TITLE
Advanced tree navigation is not showing

### ISSUE THREAD

**Issue by fifth-law** [microsoft/vscode#211924]
Type: <b>Bug</b>

https://code.visualstudio.com/docs/getstarted/userinterface#_advanced-tree-navigation

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (2.95GB free)|
|Process Argv|--crash-reporter-id fb9269f8-dd19-446e-80fb-80979736e257|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: dev|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|Memory (System)|7.76GB (2.97GB free)|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.16.20
remotehub|Git|0.62.0
eml|lei|0.4.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.362.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.0
azure-repos|ms-|0.38.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.1
vscode-speech|ms-|0.8.0
aws-toolkit-vscode|ama|3.1.0
vscode-dbt|bas|0.5.1
markdown-mermaid|bie|1.23.0
ruff|cha|2024.20.0
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|2.4.4
xml|Dot|2.5.1
copilot|Git|1.186.0
copilot-chat|Git|0.15.0
vscode-pull-request-github|Git|0.88.0
vscode-dbt-power-user|inn|0.39.1
eml|lei|0.4.0
rainbow-csv|mec|3.11.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.4.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
makefile-tools|ms-|0.9.10
vscode-yaml|red|1.14.0
jinjahtml|sam|0.20.0
svg-preview|Sim|2.8.3
snowflake-vsc|sno|1.7.1
code-spell-checker|str|3.0.1
code-spell-checker-danish|str|2.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by gjsjohnmurray** [comment]
This changed in 1.89

https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding
