### ISSUE TITLE
Is possible to have it on Lumia 950 in near feature with .NET SDK ?

### ISSUE THREAD

**Issue by CyborTronik** [Microsoft/vscode#212]
Is it possible to recompile for Lumia 950, and to use phone for development of .NET apps and libs?
That can be decision factor for buying Lumia 950

**Comment by felixfbecker** [comment]
Title should be "Univerial app version"

**Comment by CyborTronik** [comment]
So this can add +100 karma points to Windows continuum and make it more sell-able... But it also requires to have .NET SDK for ARM (I guess is not difficult to do for Microsoft)

**Comment by felixfbecker** [comment]
The .NET SDK has nothing to do with VS Code and I don't think it will happen. But It would be awesome if we could edit code on Windows Mobile in VS Code that is in some git repo.

**Comment by xied75** [comment]
Given VSCode is done in TypeScript, why it can't run on Lumia 950 or ARM in general?

**Comment by felixfbecker** [comment]
Well you certainly would have to port the Electron / file system read/write stuff

**Comment by xied75** [comment]
Right, had a look of Electron, 77% C++ code, wouldn't be one day's work to port over ARM. :)

BTW, I used to think VS Code is done in Cordova, why now Electron? What is the reasoning behind?

**Comment by jrieken** [comment]
off-topic

**Comment by jrieken** [comment]
VS Code is written in JavaScript without Cordova

**Comment by xied75** [comment]
:+1:

**Comment by jmeier** [comment]
Even this thread is off-topic, a windows phone version of VS Code would be stunning. Especially when working with continuum.
