### ISSUE TITLE
[CSS] Go to definition won't work properly.

### ISSUE THREAD

**Issue by codeleeks** [microsoft/vscode#212064]
Type: <b>Bug</b>

failed to go to definition of any css variables from a different css 

```footer.scss``` has ```margin-top: var(--footer-margin-top);``` where i wanted to go to definition of ```footer-margin-top``` defined in ```_common.scss```

but it won't go there somehow.

although scss variable works for me well, i prefer using css variables.

i was wondering if you are going to support this feature or you already have it.

https://github.com/microsoft/vscode/assets/166087781/e9c3df1e-267f-482b-bcfe-d5f65cd71e03

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 Microsoft Surface (R) Edition (12 x 2196)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.45GB (7.74GB free)|
|Process Argv|--crash-reporter-id 62af4c4a-8c4f-4c7c-bca9-278edcd3f259|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
tailwind-docs|aus|2.1.0
comment-tagged-templates|bie|0.3.3
markdown-mermaid|bie|1.23.0
vscode-tailwindcss|bra|0.10.5
gitignore|cod|0.9.0
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|14.9.1
vscode-html-css|ecm|2.0.9
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
go|gol|0.41.4
headwind|hey|1.7.0
beautify|Hoo|1.5.0
vscode-scss|mrm|0.10.0
vscode-language-pack-ko|MS-|1.89.2024050109
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
LiveServer|rit|5.7.9
svg-preview|Sim|2.8.3
tabnine-vscode|Tab|3.97.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-maven|vsc|0.44.0
markdown-all-in-one|yzh|3.6.2
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31022790
a69g1124:31038041
dwnewjupyter:31035176

```

</details>

**Comment by aeschli** [comment]
The built in css support does not go across files. It's singe file only.

We have https://github.com/microsoft/vscode/issues/47331 as an issue. There's currently no work planed on this.
