### ISSUE TITLE
The search box for a file by name in Explorer no longer works. (macOS)

### ISSUE THREAD

**Issue by SkeletonGamer** [microsoft/vscode#212074]
Type: <b>Bug</b>

The search box for a file by name in Explorer no longer works.

When I do a keyboard shortcut ctrl+f or cmd+f when my cursor is in the explorer, the search module that opens is that of the document opened on the right and no longer the one that was displayed at the top of the 'Explorer. This is very disabling when we have a lot of files in Explorer.

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:10:13.496Z)
OS version: Darwin arm64 23.4.0
Modes: Restricted

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 4, 6|
|Memory (System)|64.00GB (11.16GB free)|
|Process Argv|--crash-reporter-id e8d99b10-1cf7-4e2d-b784-7f494cd1290b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
snippets-geojson|ana|1.0.0
ng-template|Ang|17.3.2
mustache|daw|1.1.1
gc-excelviewer|Gra|4.2.59
classic-asp|ili|0.0.4
vscode-docker|ms-|1.29.1
vscode-language-pack-fr|MS-|1.89.2024050109
vscode-dotnet-runtime|ms-|2.0.3
python|ms-|2024.6.0
vscode-pylance|ms-|2024.4.1
remote-containers|ms-|0.362.0
vscode-yaml|red|1.14.0
vscode-nginx|wil|0.7.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31022790

```

</details>

**Comment by gjsjohnmurray** [comment]
Please see https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding for details of a recent change to the default keybinding.

**Comment by SkeletonGamer** [comment]
Thank you ! I completely missed this change...

**Comment by ttodua** [comment]
it would be good if you have incorporated some kind of "one-time popup" functionality in vscode, where such changes would trigger a popup notice to users. so, i.e. when clicking CTRL+F in explorer, it would have shown one-time popup saying "this functionality changed..." ...etc. I've spent around 1 hour trying to find out whether I had problem with extensions, then googling issues, then opening issue here...

such changes already happened several times in last few months in VSCode, and that "one-time-popups" would have saved many people from headaches and time-wastings.
