### ISSUE TITLE
Compare Directory & All Files Within Directory / SSH Terminal / DB Manager

### ISSUE THREAD

**Issue by gunzanrozes** [Microsoft/vscode#21207]
Would love to see these options available:

Compare Directory & All Files Within Directory - (PHPStorm style)
Remote SSH Terminal
DB Manager

**Comment by bpasero** [comment]
@gunzanrozes please try to avoid filing multiple feature requests in one issue.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
