### ISSUE TITLE
i cant remove a keyboard shortcut

### ISSUE THREAD

**Issue by EatDatLicht** [microsoft/vscode#212059]
Type: <b>Bug</b>

i try to remove a ¨new file¨short cut or create a new keybind, but when i try to remove its just imposible and i cant do anything becouse i try to do in A with when conditiones.

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600 6-Core Processor               (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.60GB free)|
|Process Argv|--crash-reporter-id 526fa97b-102a-4a78-99a9-bf30fc64212c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.6.0
material-icon-theme|PKi|5.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31022790
a69g1124:31038041
dwnewjupyter:31035176

```

</details>

**Comment by ulugbekna** [comment]
Please, provide a screencast with screencast mode enabled (run command "Toggle Screencast Mode" from the command palette (F1))

**Comment by EatDatLicht** [comment]
![image](https://github.com/microsoft/vscode/assets/104707943/aef4501d-b135-49a4-a02c-f0665676f381)


and there is a vid https://outplayed.tv/media/vBnne2
idk if is even a bug but i cant do anything, 
I tried to use the ¨when¨ option but it doesn't always work for me either since I set the restrictions and it didn't let me, it sent me directly to create a new file

**Comment by EatDatLicht** [comment]
![image](https://github.com/microsoft/vscode/assets/104707943/c8161e75-2af1-40b3-a4a2-dab7c294d922)

**Comment by ulugbekna** [comment]
/duplicate this's a known bug (I don't have the issue number at hand at the moment) -- the reason is that the "when" is syntactically incorrect; if you remove the `&&` at the end, the UI should work OR you can remove the keybinding from the `keybindings.json` directly.
