### ISSUE TITLE
intellisense is not working

### ISSUE THREAD

**Issue by Alain27info** [microsoft/vscode#212012]
Type: <b>Bug</b>

intelissense is not working 

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.5.0-1018-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7730U with Radeon Graphics          (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.34GB (6.57GB free)|
|Process Argv|--crash-reporter-id 4a84129b-e3ce-4ed8-be0e-5525294155c2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: didactic space spork|
|OS|Linux x64 6.5.0-1018-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (2 x 2479)|
|Memory (System)|7.74GB (5.26GB free)|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.16.20
cs50|CS5|0.0.1
ddb50|CS5|2.0.0
explain50|CS5|1.0.0
extension-uninstaller|CS5|1.0.9
phpliteadmin|CS5|0.0.1
style50|CS5|0.0.1
codespaces|Git|1.16.20
vscode-pull-request-github|Git|0.88.0
prettier-sql-vscode|inf|1.6.0
vscode-pdf|mat|0.0.6
vscode-docker|ms-|1.29.1
vscode-language-pack-bg|MS-|1.48.3
vscode-language-pack-cs|MS-|1.89.2024050109
vscode-language-pack-de|MS-|1.89.2024050109
vscode-language-pack-es|MS-|1.89.2024050109
vscode-language-pack-fr|MS-|1.89.2024050109
vscode-language-pack-hu|MS-|1.48.3
vscode-language-pack-it|MS-|1.89.2024050109
vscode-language-pack-ja|MS-|1.89.2024050109
vscode-language-pack-ko|MS-|1.89.2024050109
vscode-language-pack-pl|MS-|1.89.2024050109
vscode-language-pack-pt-BR|MS-|1.89.2024050109
vscode-language-pack-ru|MS-|1.89.2024050109
vscode-language-pack-zh-hans|MS-|1.89.2024050109
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.4.1
cpptools|ms-|1.19.9
hexeditor|ms-|1.10.0
vsliveshare|ms-|1.0.5918
java|red|1.30.0
r|REd|2.8.2
vscode-java-debug|vsc|0.57.0
gitdoc|vsl|0.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
chatpanelt:31018789
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by jrieken** [comment]
@vittorioallegra-scai you like have not the same issue but same symptoms. Anyways, also for you: https://github.com/microsoft/vscode/issues/212012#issuecomment-2095316113

**Comment by vittorioallegra-scai** [comment]
> @vittorioallegra-scai you like have not the same issue but same symptoms. Anyways, also for you: [#212012 (comment)](https://github.com/microsoft/vscode/issues/212012#issuecomment-2095316113)

@jrieken I tried, but couldn't identify the extension which is causing this issue

**Comment by Alain27info** [comment]
I delete all the settings j.son and it works for me

**Comment by Alain27info** [comment]
Awesome, thanks!

Le mar. 7 mai 2024 à 09:52, Johannes Rieken ***@***.***> a
écrit :
