### ISSUE TITLE
Remote SSH from different clients "bricks" the target device

### ISSUE THREAD

**Issue by akshaya-a** [microsoft/vscode#212004]
Does this issue occur when all extensions are disabled?: Yes/No

Client (number 2): 

Version: 1.90.0-insider (user setup)
Commit: 816c6f7d7bc4da9796cd19ac6b122b6e26f50d7f
Date: 2024-05-03T17:55:38.086Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

Target:
ubuntu 22 VM running under the latest proxmox

Steps to Reproduce:

1. Happily use remote SSH from laptop to a local ubuntu box, allow the laptop to fall asleep when put on the charger
2. Switch to desktop and Remote SSH into the same target - get ssh errors
3. Order of devices doesn't seem to matter, and a clean shutdown of vscode before swapping *might* not reproduce this? I need to gather more evidence on the latter

OK I know (think?) this one isn't fully vscode's fault, but it has to be the first place to start the investigation I suppose, and I assume there would be the right set of experts to tell me what logs/where to begin this investigation. Tackling a seemingly random set of device hangs, I think I've narrowed it down to my VSCode + RemoteSSH + multiclient workflow.

Symptoms:
Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT

And yes, even a regular ping of this target after this responds with "Destination host unreachable", making it pretty difficult to get logs out during the "bricked" state. A hard power recycle gets everything back into a good state.

I am unable (probably due to ignorance) to reproduce this with bare ssh, probably because something the Remote SSH extension actually does is what triggers it vs the connection itself.

Any thoughts or starting points?

**Comment by roblourens** [comment]
Please share the full log from the Remote-SSH output channel

Are you saying that when the remote is in this state, you are not able to connect with ssh from the terminal?

Is it possible that you have some extension or another process running on the remote which ends up using a lot of CPU/memory?

You might try this again with the latest VS Code Insiders because we may have also fixed some connection-related issues here, but not sure whether it would be related to what you see.

**Comment by akshaya-a** [comment]
> Are you saying that when the remote is in this state, you are not able to connect with ssh from the terminal?

Even more than that, it doesn't respond to ping! (which is why I'm not exactly sure what logs to give you as I would assume they need to be on disk somewhere after the hard device reboot) I could be mistaken but I don't believe the actual output window survives a vscode restart?

> Is it possible that you have some extension or another process running on the remote which ends up using a lot of CPU/memory?

This is very possible, a couple days ago I had to kill a bunch of zombie vscode-insiders processes that pegged all the cpu cores, so perhaps there was some zombie situation? I do recall running close to disk space limits due to docker, in case there is some drive-full-disaster-mode. However, given that at the time I could repro with just a couple client session switches, it doesn't seem to be the same scenario

Feel free to close out this issue as I personally am unblocked (buy just buying a dedicated server, so almost the entire VM -> CPU stack is different now), but thought I'd bring attention to this failure mode.

An actionable outcome might be some documentation or tooling to fetch relevant log files for the remote extension that are on the target device disk?

**Comment by roblourens** [comment]
Thanks for the followup. I was looking for logs from the client when you fail to connect, but those don't seem to be helpful if you can't ssh/ping outside of vscode at all.

I can't think of any logs from the remote that would help- seems most likely that you were just running really close to resource limits
