### ISSUE TITLE
vs code don’t work after update to Fedora 40

### ISSUE THREAD

**Issue by Jhon-Mosk** [microsoft/vscode#212039]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.89.0
- OS Version: Fedora Linux 40 (Workstation Edition)

Steps to Reproduce:

1. code --disable-extensions
2. don't work

Аппаратная информация:
Модель оборудования: ASUSTeK COMPUTER INC. PRIME B250M-PLUS
Память: 16,0 ГиБ
Процессор: Intel® Core™ i7-7700K × 8
Графика: Software Rendering
Ёмкость диска: 2,1 ТБ
Программная информация:
Версия прошивки: 0808
Название ОС: Fedora Linux 40 (Workstation Edition)
Сборка ОС: (null)
Тип ОС: 64-бит
Версия GNOME: 46
Оконный интерфейс: X11
Версия ядра: Linux 6.8.7-300.fc40.x86_64

screen vs code with problem
![image](https://github.com/microsoft/vscode/assets/40711760/6cbfbbff-08bc-4f9f-85fd-11033aeb81e3)
![image](https://github.com/microsoft/vscode/assets/40711760/3502e34a-9770-41d9-bcc4-11b5fbf6af8b)

P.S. video card:

01:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1) (prog-if 00 [VGA controller])
Subsystem: ASUSTeK Computer Inc. DUAL-GTX1060-O6G [GeForce GTX 1060 6GB Dual]
Flags: bus master, fast devsel, latency 0, IRQ 133
Memory at f6000000 (32-bit, non-prefetchable) [size=16M]
Memory at e0000000 (64-bit, prefetchable) [size=256M]
Memory at f0000000 (64-bit, prefetchable) [size=32M]
I/O ports at e000 [size=128]
Expansion ROM at 000c0000 [disabled] [size=128K]
Capabilities: [60] Power Management version 3
Capabilities: [68] MSI: Enable+ Count=1/1 Maskable- 64bit+
Capabilities: [78] Express Legacy Endpoint, IntMsgNum 0
Capabilities: [100] Virtual Channel
Capabilities: [250] Latency Tolerance Reporting
Capabilities: [128] Power Budgeting <?> Capabilities: [420] Advanced Error Reporting Capabilities: [600] Vendor Specific Information: ID=0001 Rev=1 Len=024 <?>
Capabilities: [900] Secondary PCI Express
Kernel driver in use: nouveau
Kernel modules: nouveau

**Comment by deepak1556** [comment]
If the issue is present with latest stable, please share the output of `code --verbose`
