### ISSUE TITLE
[javascript] switch-case `default` not highlighted.

### ISSUE THREAD

**Issue by philipgiuliani** [Microsoft/vscode#2120]
![bildschirmfoto 2016-01-20 um 09 43 03](https://cloud.githubusercontent.com/assets/5446019/12443760/918dae04-bf5a-11e5-8fee-c4e20ee85358.png)

I think the screenshot explains itself.

**Comment by siegebell** [comment]
same with typescript (0.10.6)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#69
