### ISSUE TITLE
VSC crashing and hanged

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#212023]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.89.0
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
- OS Version: W11

Steps to Reproduce:

1. Just start VSC and crashed and if trying open some dir
 ![vsc_new_window_bug_2](https://github.com/microsoft/vscode/assets/25403861/e5a0f493-f67b-4baa-9bbd-bce9fc371f62)
![vsc_new_window_bug_1](https://github.com/microsoft/vscode/assets/25403861/f843cddd-42c5-4a39-b099-efd609c051fb)

2. If not crash then when run python project loosing debugs icons

![vsc_new_window_bug_3](https://github.com/microsoft/vscode/assets/25403861/17112658-ea74-42c9-a9a1-6ec98796c51c)

**Comment by roblourens** [comment]
re: `oom`: sounds like your machine may be low on RAM?

The second issue- the Python extension may not be activated or installed but it's likely related to the first issue?

**Comment by ManPython** [comment]
This can be done easy if code is long or mane files or many problems in code, when VSC is overloaded with some addons.
https://github.com/microsoft/vscode/issues/210085
