### ISSUE TITLE
execution commands for contributed REPLs

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#212051]
shift+enter should execute the input box code as it does in jupyter IWs.
consider how to switch between `enter` vs `shift+enter`

**Comment by anthonykim1** [comment]
Also discussed today the need to figure out shift+enter and enter behavior when both Python extension and Jupyter extension are installed. Should be configurable, not sure what are exactly needed to make this happen though.

**Comment by anthonykim1** [comment]
Need: https://github.com/microsoft/vscode/issues/212427 to properly handle executing on enter and thus allowing Python extension to figure out whether something is a complete or incomplete Python command.

**Comment by anthonykim1** [comment]
We should be good once https://github.com/microsoft/vscode-python/pull/23442 is merged. Handling execute on enter like the traditional interactive REPL in terminal from Python itself closely as we can.
