### ISSUE TITLE
Option to easily modify recently changed auto-indent settings for those who do not use 1TBS in JavaScript

### ISSUE THREAD

**Issue by wwoodsTM** [microsoft/vscode#212037]
I have used vscode for years with Allman-style braces in JavaScript. I realize obviously I am in the minority with this practice, but I started coding with C/C++ and it has stuck, at least for my own personal projects. In the most recent release of vscode, there was a change to the JavaScript language config file that makes it to where any new lines after the start of an if/while/for   auto-indent, treating it like a brace-less block I am assuming. In my case, this is not what I intend, I am simply trying to type the following curly brace on its own line and having to back it up every time while trying to do what is ingrained in muscle memory is not fun.

If there is an option to fix this that is reachable from settings menus or settings.json, I could not find it. I ended up creating my own custom extension just to solve the issue where I reversed the change. I cannot imagine I am the only one that did not love this recent change as far as those who do not always use 1TBS in JavaScript. If I missed some option or setting somewhere, my apologies and sometimes I can miss the obvious, but in the case that it does require making your own extension as I did, there might be some consideration of exposing some of this to at least the settings.json file.

Thank you.

**Comment by aiday-mar** [comment]
Hi @wwoodsTM thank you for posting this issue and sorry to hear that you experience this issue. We are currently not exposing the redefinition of the indentation rules in the settings.json file. I discussed this with colleagues and we thought this would surface perhaps too much complexity to the user.

I am planning on undoing the indentation when a curly brace is detected after a braceless `if/while/for` statement, if that helps.

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. Recently we have made a change so that lines are deindented when a curly brace is typed on a line that is indented after a braceless if statement. This should fix the issue.
