### ISSUE TITLE
Column breakpoint doesn't work in condition statement

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#21204]
Testing #20192

My test JavaScript program is
```java
var a = 1;
if (a === 2 || a === 1) {
	console.log(a);
}
```

I tried to set a column breakpoint after `||` but it adds a breakpoint to next line

![columndebug](https://cloud.githubusercontent.com/assets/876920/23229869/baedba4c-f8f6-11e6-9a8c-9622b06b5cfe.gif)

**Comment by isidorn** [comment]
As desgined. While you are not debugging you can set a column breakpoint anywhere, but while you are debugging a debug extension verifiys the location of all your breakpoints and can update them.
At the end Node decides that the breakpoint should be moved there and we can not affect this.
