### ISSUE TITLE
Search option not appears in explorer section

### ISSUE THREAD

**Issue by soyebamd** [microsoft/vscode#212018]
Type: <b>Bug</b>

Before update the search option are visible but now it is not appear ctrl+f to search a specific file. 

Please fix this bug.

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 5650GE with Radeon Graphics     (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.38GB (1.00GB free)|
|Process Argv|--crash-reporter-id da11f8ff-ac5f-4f99-9707-80d0409632c3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
ACF-Snippet|ant|1.9.0
c-cpp-compile-run-windows|BDZ|0.0.2
htmlplay|bia|0.0.10
vscode-intelephense-client|bme|1.10.4
phpserver|bra|3.0.2
woocommerce|cla|1.1.0
wpcs-whitelist-flags|cla|1.1.0
dartsass|cod|0.9.2
c-cpp-compile-run|dan|1.0.58
composer-php-vscode|DEV|1.45.15272
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.45.15272
profiler-php-vscode|DEV|1.45.15272
vscode-html-css|ecm|2.0.9
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|10.4.0
code-runner|for|0.12.2
live-sass|gle|6.1.2
rest-client|hum|0.25.1
ftp-simple|hum|0.7.6
vscode-wordpress-hooks|joh|1.3.0
ftp-sync|luk|0.3.9
Kotlin|mat|1.7.1
formate|Mik|1.2.1
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.6.0
vscode-pylance|ms-|2024.4.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
vscode-react-native|msj|1.13.0
sftp|Nat|1.16.3
php-docblocker|nei|2.7.0
language-liquid|nei|0.1.1
wordpress-suite|pet|0.0.6
material-icon-theme|PKi|5.1.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|6.0.0
theme-check-vscode|Sho|2.3.0
shopify-liquid|sis|4.0.1
vscode-css-custom-properties|Toc|0.0.5
cmake|twx|0.0.17
quokka-vscode|Wal|1.0.637
wordpress-toolbox|wor|1.3.15
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.34.0
php-pack|xde|1.0.3
html-css-class-completion|Zig|1.20.0
php-intellisense|zob|1.3.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
showvideoc:31016891
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by lramos15** [comment]
This change was announced in recent update https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding

But you can rebind command to your preference
