### ISSUE TITLE
The search box for a file by name in Explorer no longer works. (Windows)

### ISSUE THREAD

**Issue by SkeletonGamer** [microsoft/vscode#212073]
Type: <b>Bug</b>

The search box for a file by name in Explorer no longer works.

When I do a keyboard shortcut ctrl+f or cmd+f when my cursor is in the explorer, the search module that opens is that of the document opened on the right and no longer the one that was displayed at the top of the 'Explorer. This is very disabling when we have a lot of files in Explorer.

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.17763
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Common KVM processor (4 x 2096)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|32.00GB (23.55GB free)|
|Process Argv|--file-uri file:///c%3A/inetpub/extranet/extranet.code-workspace --crash-reporter-id e8c87ad9-80d1-41ad-a955-e66602c77c97|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|17.3.2
npm-intellisense|chr|1.4.5
vscode-office|cwe|3.3.2
vscode-eslint|dba|2.4.4
node-version|fiv|0.0.1
classic-asp-html|jtj|0.1.3
vscode-codemetrics|kis|1.26.1
Angular-BeastCode|Mik|17.0.4
mongodb-vscode|mon|1.6.0
vscode-azurefunctions|ms-|1.14.3
vscode-azureresourcegroups|ms-|0.8.6
vscode-docker|ms-|1.29.1
vscode-language-pack-fr|MS-|1.89.2024050109
azure-account|ms-|0.11.7
vsliveshare|ms-|1.0.5918
vscode-for-node-js-development-pack|nod|2.0.1
vscode-import-cost|wix|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by gjsjohnmurray** [comment]
Please see https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding for details of a recent change to the default keybinding.

**Comment by SkeletonGamer** [comment]
Thank you ! I completely missed this change...
