### ISSUE TITLE
scm.workingSets.enabled steals focus from integrated terminal

### ISSUE THREAD

**Issue by aslatter** [microsoft/vscode#212048]
Type: <b>Bug</b>

I changed a test-projects user-settings to:

```js
{
    "scm.workingSets.enabled": true,
    "scm.workingSets.default": "empty"
}
```

And then opened the integrated terminal.

When I ran the command:

```sh
git switch -c tmp
```

I expected input-focus to remain in the integrated terminal. Instead, focus was removed (I can't tell where focus went, though).

If I then click into the integrated terminal and run:

```sh
git switch -
```

Focus is again removed from the integrated console. This time it lands into the editor window I had open in the previous branch.

When I'm performing branch-switch operations in the terminal I frequently execute additional scm-operations (like creating and pushing a commit).

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:08:25.066Z)
OS version: Linux x64 6.8.7-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 3448)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|7.41GB (3.00GB free)|
|Process Argv|--unity-launch --crash-reporter-id e4ee9f37-a035-4594-8d86-b34257ba10c5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|10.4.0
go|gol|0.41.4
terraform|has|2.30.1
rainbow-csv|mec|3.11.0
csharp|ms-|2.23.15
vscode-dotnet-runtime|ms-|2.0.3
rust-analyzer|rus|0.3.1940
code-spell-checker|str|3.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by aslatter** [comment]
I would like to add that I appreciate the thoughtfulness of the `scm.workingSets` feature in that it works even if I prefer working with my scm system from the terminal.

**Comment by aslatter** [comment]
I tried the workflow again with all extensions temporarily disabled and got the same result (focus is removed from the integrated terminal when switching branches).

**Comment by bduffany** [comment]
I am affected by this behavior as well. Specifically, it seems to happen when I run a `git checkout` command in the terminal which switches branches and results in the editor state being restored from the branch.

Here is a demo: note that while I am typing `????...` the focus suddenly and unexpectedly shifts to the editor.


https://github.com/microsoft/vscode/assets/2414826/7a0d0653-b9e5-44c7-a3d2-24167ccf10ad

**Comment by lszomoru** [comment]
This has been fixed in the latest VS Code Insiders release (version details below). 

```
Version: 1.90.0-insider (Universal)
Commit: fd11ed87fdf1f8e46575e027644406f51f0666f6
Date: 2024-05-27T05:49:50.645Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.4.0
```

The fix will be included in the next VS Code release.
