### ISSUE TITLE
Tasks run task and Configure task commands infinte load or no-op on vscode web

### ISSUE THREAD

**Issue by mahmoudsalah1993** [microsoft/vscode#212047]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.89.0
- OS Version: Any, vscode web

Steps to Reproduce:

1. Open a repository on github, and hit `.` to open vscode.dev
2. Open command palette and run `Tasks: Run Task` or `Tasks: Configure Tasks` 

Expected:

Both commands show list of tasks pertraining to the repository or the option to create tasks.json etc

Actual:

Run tasks command simply is no-op not showing the quickpick.
Configure task keeps infintely loading.

![image](https://github.com/microsoft/vscode/assets/13228044/c8b1e103-656b-467c-bff7-cae1bbad9e6c)

**Comment by meganrogge** [comment]
thanks for the issue, do you know if this happened in earlier versions of vscode.dev?

**Comment by mahmoudsalah1993** [comment]
We've had this issue reported for several months in our internal version of web-based vscode. The issue seemed to stem that both commands awaited for the `onDidRegisterAllSupportedExecutions` event to be fired, which in a web environment this never gets fired, shell executions aren't supported for example.

Changing the condition to fire if any execution type is registered https://github.com/microsoft/vscode/pull/212163 seems to resolve the issue and no issues seem to be visible user flow wise. The warnings generally show only when some non-supported executions are available, but don't cause issues for the dialog or show up as options for users.

**Comment by alexr00** [comment]
Verified, but found two related issues: https://github.com/microsoft/vscode/issues/213824, https://github.com/microsoft/vscode/issues/213825
