### ISSUE TITLE
Occasional error notification for notebook save

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#212087]
When working a python jupyter notebook within vscode, I started occasionally seeing this notification:

![Image](https://github.com/microsoft/vscode/assets/16353531/abe0fda0-bbf6-4d4b-b22e-0c12f5a58fc7)

With this in the dev console: 

```
ERR [stored file working copy] handleSaveError(437) - exit - resulted in a save error: Error: Document version mismatch file:///Users/ulugbekna/code/nlp_course/week01_embeddings/homework.ipynb notebook/jupyter-notebook
```

cc @rebornix 

Version: 1.90.0-insider
Commit: 816c6f7d7bc4da9796cd19ac6b122b6e26f50d7f
Date: 2024-05-03T18:08:45.720Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

**Comment by ulugbekna** [comment]
I still see this in 

Version: 1.90.0-insider
Commit: 1facdf8117ba7aa833fa90539414e310a581e74c
Date: 2024-05-10T06:01:29.967Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0



![Image](https://github.com/microsoft/vscode/assets/16353531/55a5c31a-b6d3-48d6-af5a-5c70bd4a2620)



![Image](https://github.com/microsoft/vscode/assets/16353531/887ed1a4-99b7-4d85-a23b-d9f1cec348a0)

**Comment by amunger** [comment]
The most consistent repro I found: 

1. Enable auto save
2. execute a cell with ctrl+enter (so that focus moves to the container) with the cell contents `input('input: ')`
3. quickly press escape and ctrl+enter again to close the input and then re-run the cell within the 1 second auto-save delay
:bug: notification about save failure

This specific set of operations will put the edit that removes the output last, and since it started with no output, nothing actually changes for that edit, but the version is still incremented. The fix should take care of any case where an edit doesn't actually update anything.

**Comment by ulugbekna** [comment]
The latest fix is not released yet, but I started seeing 



![Image](https://github.com/microsoft/vscode/assets/16353531/61258328-b314-40a8-90bd-0af8e9f16a5b)


with 

Version: 1.90.0-insider
Commit: 26c4a07b47a2bd34480a5e4cba2c2384c590b039
Date: 2024-05-10T18:24:16.069Z
Electron: 29.3.1
ElectronBuildId: 9464424
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.4.0

**Comment by amunger** [comment]
that's probably the same error, but the catch block throws - should be fixed in https://github.com/microsoft/vscode/pull/212459

**Comment by Capsar** [comment]
Good morning,

I am getting a similar error message.

I am connected to a VM through SSH. I am able to edit & save the Jupyter Notebook until I run any cell. After running a cell I can no longer save the notebook, even after the cell has finished running.

![image](https://github.com/microsoft/vscode/assets/10345197/d23f5695-5aef-4517-97ad-8478adf61c5e)

Info:
Version: 1.90.0-insider (user setup)
Commit: 29aeab1cbb350107a7bd5962b5e7efe745e0a3ec
Date: 2024-05-13T05:48:48.053Z
Electron: 29.3.1
ElectronBuildId: 9464424
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by amunger** [comment]
thanks for the update, sounds like the latest change might have made things worse, I'll take another look.

**Comment by amunger** [comment]
@Capsar - is there a specific cell execution behavior that causes this, or just when any cell executes?

 - how long the cell runs for
 - if it produces output
 - if it has an `input` call

**Comment by amunger** [comment]
I think I found the issue introduced in my previous change
