### ISSUE TITLE
PowerShell intellisense in terminal replaces existing text with suggestion

### ISSUE THREAD

**Issue by DJackman123** [microsoft/vscode#212024]
Type: <b>Bug</b>

Turn on VS Code-native intellisense for PowerShell in the terminal.
Type the start of a command:  Get-ChildItem -
List of suggestions comes up, press Enter to take the first suggestion.
Command is changed to:  Get-ChildI-Path

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.69GB (40.00GB free)|
|Process Argv|--crash-reporter-id 4e8321cf-1056-4779-be78-ab68dfb6e262|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
auto-close-tag|for|0.5.15
copilot|Git|1.186.856
copilot-chat|Git|0.15.2024043005
todo-tree|Gru|0.0.226
vscode-dotnet-runtime|ms-|2.0.3
powershell|ms-|2024.2.1
vsliveshare|ms-|1.0.5918
msbuild-project-tools|tin|0.6.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp1r3:30993539
dsvsc020:30976470
pythonait:31006305
showvideoc:31016891
chatpanelc:31018788
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by meganrogge** [comment]
Can you pls provide a gif and say what you expect vs what is actually happening so I am sure I understand?

**Comment by DJackman123** [comment]
What's the easiest/recommended way to capture a gif?  I haven't done that before.
________________________________

**Comment by meganrogge** [comment]
https://[gifcap](https://gifcap.dev/).dev/

**Comment by DJackman123** [comment]
![BugRepro](https://github.com/microsoft/vscode/assets/49529467/5c63a591-79df-423f-bbb5-2f3a2d37f559)

**Comment by Tyriar** [comment]
This will be improved after https://github.com/microsoft/vscode/issues/211222, it's happening because the circle here is on the line above so the positions in our model are a bit messed up:

![image](https://github.com/microsoft/vscode/assets/2193314/f8cf18a0-a82e-40b5-a125-50b02e00f538)

**Comment by Tyriar** [comment]
This should be fixed generally now, if you hit an edge case we don't cover in Insiders, please let us know.
