### ISSUE TITLE
Extension Bisect is active and has disabled 4 extensions. Check if you can still reproduce the problem and proceed by selecting from these options.

### ISSUE THREAD

**Issue by ismailfaridi** [microsoft/vscode#212040]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: x64-1.89.0
- OS Version: Windows 10

I am facing this error while opening VSCode and when compiling the C++ program. I disabled all extensions and also reinstalled VSCode, but the same error occurs.
![image](https://github.com/microsoft/vscode/assets/112934517/48d66af6-253a-44b3-adc4-f235f1955e28)
![image](https://github.com/microsoft/vscode/assets/112934517/617683d4-c2e6-4a24-8585-e69b35668fc7)

**Comment by sandy081** [comment]
What happens when you choose **Stop Bisect** action?

**Comment by ismailfaridi** [comment]
Initially, when I open VSCode, this error occurs: "Extension host terminated unexpectedly 3 times within the last 5 minutes."

When I click on "Start Extension Bisect," all extensions in my VSCode are removed, and I am only able to compile programs using the terminal. However, even without clicking on 'Start Extension Bisect,' I am still able to compile programs using the terminal.

When I click the "Stop Bisect" button, I return to my normal VSCode where all extensions are available, and the same error is displayed in the corner, i.e., "Extension host terminated unexpectedly 3 times within the last 5 minutes."
![steps](https://github.com/microsoft/vscode/assets/112934517/713c90ac-e29e-4843-954e-14ef7c59e104)

**Comment by ismailfaridi** [comment]
**Oh, my VSCode is now working! I removed all extensions, signed out of my Microsoft ID, reinstalled the extensions, and it's working perfectly. Thank you for your time!**
