### ISSUE TITLE
Integrated Terminal Color Prompt escape sequence ansi error

### ISSUE THREAD

**Issue by adarshrajpathak** [microsoft/vscode#212008]
Type: <b>Bug</b>
\x1b[01\x3b32madarshrajpathak@Laptop-Pathak-LX\x1b[00m:\x1b[01\x3b34m~\x1b[00m$ adarshrajpathak@Laptop-Pathak-LX:~$

https://github.com/microsoft/vscode/assets/123010616/5be486eb-3f19-4401-b0d5-ea8e33b6fbfa

Since last nightly update it is not considering correct way the ~/.bashrc  color platte as ansi, i think something is broken. I have searched the internet it is showing something like escape sequence misinterpretation. I have simultaneously vscode also and standalone terminal, but this issue is only with Visual Studio Code Insiders.
Please fix it soon.

VS Code version: Code - Insiders 1.90.0-insider (a1f2ea3162c704a5890c35dde4df6ee46283d957, 2024-05-03T05:52:00.476Z)
OS version: Linux x64 6.8.0-31-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2399)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|11.59GB (8.75GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 187d320d-cf8d-464b-b2ba-5595357ca594|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|10.4.0
code-runner|for|0.12.2
copilot|Git|1.186.856
copilot-chat|Git|0.16.2024050301
vscode-docker|ms-|1.29.1
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.13
java|red|1.31.2024050308
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.57.2024041008
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.26.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.2024013105

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
vscaat:30438846
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
ccp2r3:30958153
pythonait:30973460
showvideot:31016890
chatpanelt:31014475
jg8ic977:31013176
pythoncenvpt:31022790
a69g1124:31018687
88717513:31021561
dvdeprecationcf:31036533
pythonprt:31036556
dwnewjupytercf:31035177

```

</details>

**Comment by adarshrajpathak** [comment]
No fixed in the latest update. Thanks

**Comment by alexclarkmusa** [comment]
This just started happening for me right after the 1.90 update.
