### ISSUE TITLE
Code completion triggered by setting the caret with a mouse button click

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#21201]
1) Open `vscode.d.ts`
2) set caret with mouse button click as shown in screen recording
-> code completion triggered but shouldn't

![yt4qbwfcmd](https://cloud.githubusercontent.com/assets/4674940/23228678/411a4842-f8f2-11e6-9a65-c12053b412cf.gif)

**Comment by mjbvz** [comment]
Duplicate of #21056. Should be fixed in master
