### ISSUE TITLE
Stale pylance errors on first notebook open without selected kernel

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#212080]
Repro: 

1. Open a python notebook with a cell that has external library imports, eg numpy -- notebook must be without a selected kernel -- see the python ext/pylance reporting missing imports for numpy
2. Select kernel -- a python env with numpy installed
3. :bug: The missing imports errors remain even though running the cell with those imports would be successful

https://github.com/microsoft/vscode/assets/16353531/dbd8f458-5a97-4cbc-9e5b-6fe29e6fcc6c

I don't know if it's a python or jupyter issue, so creating the issue in this repo.

Version: 1.90.0-insider
Commit: 816c6f7d7bc4da9796cd19ac6b122b6e26f50d7f
Date: 2024-05-03T18:08:45.720Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

Jupyter v2024.4.2024042601 (pre-release)

Python v2024.7.11241010 (pre-release)

**Comment by karthiknadig** [comment]
@debonte Should this be moved to pylance?
