### ISSUE TITLE
Sort settings by name

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#212122]
I'm checking settings and taking screenshots to record where i stopped, why are they not ordered by name ?

![image](https://github.com/microsoft/vscode/assets/13949704/4e99eaac-fd8f-4f9d-8711-b82466b24d03)

**Comment by RedCMD** [comment]
technically
it looks like they are
`Avatars` > `Branches` > `Files`

**Comment by irvnriir** [comment]
@RedCMD the right screenshot is from the same set of settings

**Comment by rzhao271** [comment]
It's because the order key is explicitly set.
https://github.com/gitkraken/vscode-gitlens/blob/main/package.json#L737
Closing as as-designed. Please file an issue or PR with the vscode-gitlens repository if you believe the ordering is incorrect.

**Comment by irvnriir** [comment]
VSCode should provide ability to force sort them, because in this case each Extension can make the same mistake that compromises user's ability to iterate over all settings .
