### ISSUE TITLE
Missing light theme switcher

### ISSUE THREAD

**Issue by devope** [microsoft/vscode#212149]
Wondering if is it me or now there is no light/dark mode switcher.
There are a lot of users that find the dark theme as a challenge.

**Comment by aeschli** [comment]
You can switch themes with the `Preferences: Color Theme` command.
If you want VS Code follow the System theme from your OS, enable setting `window.autoDetectColorScheme`

**Comment by devope** [comment]
I'm sorry.
My feature issue is referring to the VSC docs site.

I was redirected to this repo but didn't realize that is dedicated to the VSC editor itself.

Where is a more appropriate location to submit an issue about missing functionality of the official site?
