### ISSUE TITLE
Improper syntax highlighting of shell aliases in 1.89.0

### ISSUE THREAD

**Issue by PavelSafronov** [microsoft/vscode#212189]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.0
- OS Version: Sonoma 14.4.1, and also reproduces with vscode.dev

Steps to Reproduce:

1. Navigate to https://vscode.dev/ or open local VSCode
2. Create a new file
3. Set the file Language Mode to "Shell Script"
4. Copy/paste these two alias definitions:
    ```
    alias ll='ls -alF'
    alias ..='cd ..'
    ```
5. Note that syntax highlighting for the second alias is broken
    <img width="143" alt="Screenshot 2024-05-07 at 9 55 45 AM" src="https://github.com/microsoft/vscode/assets/1359724/d8b6b794-878f-4630-b803-524341568f06">

**Comment by RedCMD** [comment]
should report to the upstream grammar repo https://github.com/jeff-hykin/better-shell-syntax

**Comment by PavelSafronov** [comment]
Thanks. Reported: https://github.com/jeff-hykin/better-shell-syntax/issues/87

**Comment by lszomoru** [comment]
FYI @alexr00
