### ISSUE TITLE
API: Attributable Test Coverage

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#212196]
For a variety of reasons, it may be useful to know what tests generated what coverage. So let's add some API for that in the form of a second optional parameter for `addCoverage`.

```ts
declare module 'vscode' {
	export class FileCoverage2 extends FileCoverage {
		/**
		 * A list of {@link TestItem test cases} that generated coverage in this
		 * file. If set, then {@link TestRunProfile.loadDetailedCoverageForTest}
		 * should also be defined in order to retrieve detailed coverage information.
		 */
		fromTests: TestItem[];

		constructor(
			uri: Uri,
			statementCoverage: TestCoverageCount,
			branchCoverage?: TestCoverageCount,
			declarationCoverage?: TestCoverageCount,
			fromTests?: TestItem[],
		);
	}

	export interface TestRunProfile {
		/**
		 * An extension-provided function that provides detailed statement and
		 * function-level coverage for a single test in a file. This is the per-test
		 * sibling of {@link TestRunProfile.loadDetailedCoverage}, called only if
		 * a test item is provided in {@link FileCoverage.fromTests} and only for
		 * files where such data is reported.
		 *
		 * The editor will call this when user asks to view coverage for a test in
		 * a file, and the returned coverage information is used to display exactly
		 * what code was run by that test.
		 *
		 * The {@link FileCoverage} object passed to this function is the same
		 * instance emitted on {@link TestRun.addCoverage} calls associated with this profile.
		 *
		 * @param testRun The test run that generated the coverage data.
		 * @param fileCoverage The file coverage object to load detailed coverage for.
		 * @param fromTestItem The test item to request coverage information for.
		 * @param token A cancellation token that indicates the operation should be cancelled.
		 */
		loadDetailedCoverageForTest?: (testRun: TestRun, fileCoverage: FileCoverage, fromTestItem: TestItem, token: CancellationToken) => Thenable<FileCoverageDetail[]>;
	}
}
```

**Comment by connor4312** [comment]
Peek at initial UI: https://github.com/microsoft/vscode/pull/212403

**Comment by sanket-bhalerao** [comment]
is this feature limited to code for vscode or other projects can utilize this for their test coverage?

**Comment by connor4312** [comment]
Once the API is finalized, anyone can use it. It is subject to change until then, but we encourage folks to try it out and let us know how it works for them.

**Comment by Screwwaka84** [comment]
> For a variety of reasons, it may be useful to know what tests generated what coverage. So let's add some API for that in the form of a second optional parameter for `addCoverage`.
> 
> declare module 'vscode' {
> 	export class FileCoverage2 extends FileCoverage {
> 		/**
> 		 * A list of {@link TestItem test cases} that generated coverage in this
> 		 * file. If set, then {@link TestRunProfile.loadDetailedCoverageForTest}
> 		 * should also be defined in order to retrieve detailed coverage information.
> 		 */
> 		fromTests: TestItem[];
> 
> 		constructor(
> 			uri: Uri,
> 			statementCoverage: TestCoverageCount,
> 			branchCoverage?: TestCoverageCount,
> 			declarationCoverage?: TestCoverageCount,
> 			fromTests?: TestItem[],
> 		);
> 	}
> 
> 	export interface TestRunProfile {
> 		/**
> 		 * An extension-provided function that provides detailed statement and
> 		 * function-level coverage for a single test in a file. This is the per-test
> 		 * sibling of {@link TestRunProfile.loadDetailedCoverage}, called only if
> 		 * a test item is provided in {@link FileCoverage.fromTests} and only for
> 		 * files where such data is reported.
> 		 *
> 		 * The editor will call this when user asks to view coverage for a test in
> 		 * a file, and the returned coverage information is used to display exactly
> 		 * what code was run by that test.
> 		 *
> 		 * The {@link FileCoverage} object passed to this function is the same
> 		 * instance emitted on {@link TestRun.addCoverage} calls associated with this profile.
> 		 *
> 		 * @param testRun The test run that generated the coverage data.
> 		 * @param fileCoverage The file coverage object to load detailed coverage for.
> 		 * @param
