### ISSUE TITLE
Sticky scroll folded headings should keep their margin buttons beside the line-numbers

### ISSUE THREAD

**Issue by walston** [microsoft/vscode#212107]
I would like the new **sticky scroll** feature to keep the "run test" button next to the line of code that acts as the header.

To clarify what I'm specifically calling for, here's a short screen recording.

https://github.com/microsoft/vscode/assets/10055135/d82d49ff-93c5-4f36-98c9-7598336bd1d8

I filed a ticket against jest-community/vscode-jest#1139 thinking this was their issue, but they're pointing me here. 

let me know if there's anything I can do to help bring this to life.

**Comment by connor4312** [comment]
duplicates https://github.com/microsoft/vscode/issues/187834
