### ISSUE TITLE
Go to definition not working for Angular

### ISSUE THREAD

**Issue by info2dharmendra** [microsoft/vscode#212191]
Type: <b>Bug</b>

Steps to reproduce:
1) Initialize an angular project
2) Declare and define a method in app.component.ts
3) Integrate/use that defined method in app.component.html

Click on "Go to Definition" option for method from html.
Expected Result: It should navigate to defined method in app.component.ts
Actual Result : It do not navigate and says "No definition found for <<methodname>>"

VS Code version: Code 1.89.0 (Universal) (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:10:10.196Z)
OS version: Darwin arm64 23.4.0
Modes:

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
vscode-docker|ms-|1.29.1

</details>

**Comment by mjbvz** [comment]
You need to install the angular extension for this
