### ISSUE TITLE
Why is VS Code telling me to configure excludes when intellisense seems to work fine without it

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21214]
#21037

On this repo https://github.com/gwtw/js-fibonacci-heap I'm being told to configure excludes in the status bar which tells me:

![image](https://cloud.githubusercontent.com/assets/2193314/23233661/66c9c722-f904-11e6-80ca-9afa9ce3d5bb.png)

Why do I need to do this when intellisense seems to work fine without it?

**Comment by mjbvz** [comment]
Did you create a jsconfig or tsconfig in this project?

**Comment by Tyriar** [comment]
I didn't think so initially but maybe it was as I can't seem to reproduce without one anymore. It occurs with the following jsconfig.json:

```js
{
    "exclude": [
        "test/**/*"
    ]
}
```

**Comment by mjbvz** [comment]
he intellisense you are seeing is coming from an implicit project with  the set of open js/ts files. However, project wide intellisense has been disabled and you need to configure excludes to get it back.

If you look in the typescript verbose logs, you should see a message like:

```
[Trace - 2:51:05 PM] Event received: projectLanguageServiceState (0).
Data: {
    "projectName": "/home/parallels/Desktop/js-fibonacci-heap/jsconfig.json",
    "languageServiceEnabled": false
}
```

Exclude `node_modules` to fix this.

I'll update the warning message to make what has been disabled more clear
