### ISSUE TITLE
Process Explorer shows limited info about Window/EH

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#212111]
Right now the process explorer no longer shows the relationship between Window (renderer process) and EH, making it harder to tell which extension was enabled for which Window/workspace. For example, in the screenshot below, I'd love to know why Deno was activated, but couldn't tell from the explorer.

![image](https://github.com/microsoft/vscode/assets/876920/83ef0ce8-4fe5-4618-a512-a0d623902149)

**Comment by rebornix** [comment]
cc @deepak1556 as well.

Was this a change from the recent underling package update or it's how we create EH now (from the main process)?

**Comment by rebornix** [comment]
Just learnt that `[x]` suffix can be used to identify which window each process belongs to. Maybe we could group them in the Process Explorer UI.

**Comment by bpasero** [comment]
That is true, the number points to the window. Note that the list does not update live when you keep process explorer open because the info about which process belongs to which window is only sent initially.

I think @Tyriar is the owner of process explorer, not sure though if thats the latest in ownership.

**Comment by deepak1556** [comment]
> Was this a change from the recent underling package update or it's how we create EH now (from the main process)?

The current view replicates the actual process hierarchy, (i-e) EH, shared process, pty host are created from the main process and not from the window. `[x]` was added to relate these process to the corresponding window as you have figured out.

> Maybe we could group them in the Process Explorer UI.

Yeah this should be possible, but it would not then reflect the actual process hierarchy is that still okay ?

**Comment by bpasero** [comment]
I actually think we should reflect the true process hierarchy and not some logical grouping. The idea of the process explorer was (as far as I remember) to show the true hierarchy.

**Comment by rebornix** [comment]
I guess I'm asking for an enhancement for the Process Explorer to help us troubleshoot perf/memory issues. Maybe this can be a mode, where processes for the same window/workspace can be grouped together so users can easily tell which workspace is behaving poorly.

Since I have too many extensions, each time when I update Insiders, my mac will run at 800% CPU for half a minute. Thus I moved to Profile almost per workspace (one for VS Code, one for Jupyter and another for Copilot). This is why I want a better view to help me understand if an EH for a particular profile is under performing.

**Comment by rebornix** [comment]
Here is another example

![image](https://github.com/microsoft/vscode/assets/876920/39f8be69-4b6c-4537-9d96-3a965c0fd741)

I have a dozen `conpty-agent` and I don't know where do they come from (which workspace/extensions started them)

**Comment by bpasero** [comment]
@rebornix but I think for pty host we really have no tracking to the related window id, so that is really missing from the list, even if we had logical grouping.

**Comment by Tyriar** [comment]
No plans to add window relation to pty host procs
