### ISSUE TITLE
Don't show TypeScript version in Status Bar for JavaScript Projects

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21219]
#21037

In a JS project without any `jsconfig.json` (like 90% of the projects I work on), you see the TS version in the status bar (which is very verbose on Insiders):

![image](https://cloud.githubusercontent.com/assets/2193314/23234231/43ff31c6-f906-11e6-88ab-59d98fe42044.png)

Clicking it gives the following:

![image](https://cloud.githubusercontent.com/assets/2193314/23234207/2a4c4aac-f906-11e6-8657-3d9953177e59.png)

Why are we presenting this information at all if there is nothing to action such as in a project without a workspace version of TypeScript? This information is neither useful or easy to understand for JavaScript developers. We could remove the clutter when it's not relevant:

![image](https://cloud.githubusercontent.com/assets/2193314/23234344/a5470b20-f906-11e6-91fe-0199e70a76b4.png)

**Comment by mjbvz** [comment]
This goes back to VSCode 1.9. In VScode 1.8, we only showed the version when you used a custom version of TS as you suggested. In 1.9, we reworked this flow and decided it was more consistent to always show the version. We also use this item to trigger the version switcher where users can learn more about installing other versions of TS.

**Comment by Tyriar** [comment]
That makes more sense when editing TypeScript files. But for a purely JavaScript project where typescript wouldn't even be installed locally, why are we showing this information that cannot be actioned upon and only serves to confuse and add clutter?

**Comment by mjbvz** [comment]
@Tyriar Ok, that makes sense. I've update the issue title to reflection this request and will take a look at this for next sprint

Thanks
