### ISSUE TITLE
Flickering while debugging with debug.inlineValues and editor.wordWrap setting enabled

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#212142]
Starting from VS Code 1.88, debugging Java application will cause the editor area flickering with the setting `"editor.wordWrap": "on"`. By looking into the DAP log, I can see the client keeps requesting inline values continuously when word wrap is enabled. If I turn off workWrap setting, it becomes normal.

https://github.com/microsoft/vscode-java-debug/assets/7119865/e9da1696-0a45-465a-89ed-59a4f926a78d

BTW, this didn't happen for VS Code 1.87, and it looks like a regression of recent VS Code version.

**Comment by JustinGrote** [comment]
I can also reproduce

https://github.com/microsoft/vscode/assets/15258962/64cfb15e-2516-4d16-872a-038369cd4bff

**Comment by 0xPaulo** [comment]
I put this line, the problem disappeared:
"debug.inlineValues": "off"

**Comment by connor4312** [comment]
This is fixed on VS Code Insiders already
