### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FrddySign** [microsoft/vscode#212112]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:
Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit...
waiting for named pipe information from server...
[stdout] {"pipeName":"\\\\.\\pipe\\cece7761"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 1:04:33 PM] [Program] Language server initialized

**Comment by roblourens** [comment]
You can file an issue on the C# extension repo, but it's not clear what the problem is
