### ISSUE TITLE
Cannot hover over hover widget in panel chat code block

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#212101]
Repro: 

1. Ask copilot for a code block with a symbol that can be hovered over, eg "typescript array map example"
2. Hover over map -- hover widget appears, but I can't hover over it (not the case with ordinary editor) 

https://github.com/microsoft/vscode/assets/16353531/f298f4f7-324e-42a2-bef8-eefd2fa6f1de

Version: 1.90.0-insider
Commit: ccba2fc85c14bedeef5a72b7ebc0bde9b0e91948
Date: 2024-05-06T08:08:03.248Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

**Comment by mjbvz** [comment]
This seems to happen for any editor that uses `overflowWidgetsDomNode`. You can see the same behavior inside the notebook diff editor for example. After setting `overflowWidgetsDomNode`, the editor doesn't seem to get the `mousemove` event when the mouse moves over the hover content widget. Without `overflowWidgetsDomNode`, the editor does

@alexdima @hediet  Do you have any ideas on how we might fix this?

**Comment by aiday-mar** [comment]
Issue will be changed into a feature-request and corresponding TPI created for this issue
