### ISSUE TITLE
JavaScript go to configuration does nothing

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21210]
#21037

Steps to reproduce:

1. Open ./index.js
2. Trigger JavaScript go to configuration
3. Create a new file and save it as an empty jsconfig.js
4. Open ./index.js
5. Trigger JavaScript go to configuration again

It's not 100% clear from the documentation but I read it as a minimal jsconfig.json would implicitly include all files in the directory:

> By default the JavaScript language service will analyze and provide IntelliSense for all files in your JavaScript project. You will want to specify which files to exclude or include in order to provide the proper IntelliSense.

https://code.visualstudio.com/docs/languages/jsconfig

**Comment by Tyriar** [comment]
I see this many times in dev tools console:

```
[Extension Host] rejected promise not handled within 1 second
shell.ts:426 cannot open file:///jsconfig.json. Detail: File not found (/jsconfig.json)e.onUnexpectedError @ shell.ts:426
```

**Comment by Tyriar** [comment]
Marking important as this is very broken for me, maybe a Linux only problem? Probably to do with searching for `/jsconfig.json` instead of `./jsconfig.json`.

**Comment by mjbvz** [comment]
Can you please provide some more information about how you are opening the projects / files here? I'm unable to reproduce this on Ubuntu. I believe that the `rootPath` may be empty when we evaluate `const configFile = Uri.file(path.join(rootPath, 'jsconfig.json'));` but we already check for that, so I'm not sure how we are ending up with `file:///jsconfig.json`

**Comment by Tyriar** [comment]
Here's the state of the window when this happened:

![image](https://cloud.githubusercontent.com/assets/2193314/23237991/b2b779ee-f914-11e6-9a30-09dd3cf33c6f.png)

Maybe the fact it's in the folder root?
