### ISSUE TITLE
Lock a VSCode extension to specific version without notice it have to updated

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode#212175]
I am developing a project that need older version of specific VS Code extension. So that I need to install specific version of the extension. So the issue is, VS Code will always show me there is a outdated extension need to be updated. See below:

![image](https://github.com/microsoft/vscode/assets/88981/da95b0eb-34ae-4a61-b488-9c71ead2d9ec)

Is it possible to avoid some extensions notice me it can be updated?

**Comment by doggy8088** [comment]
@sandy081 Hi, which issue been duplicated with this one?

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/79689

**Comment by doggy8088** [comment]
@sandy081 Is it possible to reconsider implement this?

**Comment by sandy081** [comment]
Unfortunately no plans to look into this at present.
