### ISSUE TITLE
[php] Incorrect highlighting of semi-reserved keywords

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#2121]
Take the following example:

``` php
class A {
  static function while() {}
  public function function() {}
}

$a->function();
A::while();

// Just to show that 'while' is dark red normally.
while (0) {}
```

Note how GitHub (like other IDEs) correctly makes the declarations purple-ish and the calls black.

![semi-reserved-keywords](https://cloud.githubusercontent.com/assets/1007463/12447423/4d8f172e-bf2d-11e5-9ab8-255e427d270e.png)
...but everything is blue in VSCode.

**Comment by aeschli** [comment]
This got fixed in the meantime. Verified in 1.10-insiders.
