### ISSUE TITLE
[html] Format onPaste issues with HTML

### ISSUE THREAD

**Issue by FeaRCODE** [Microsoft/vscode#21218]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393

---

Steps to Reproduce:

1. Create an HTML document like below
![image](https://cloud.githubusercontent.com/assets/6901336/23234152/bf43b8d8-f916-11e6-95eb-fefe6f309a7c.png)

2. Copy the `nested-content` div
![image](https://cloud.githubusercontent.com/assets/6901336/23234205/ecf75ef6-f916-11e6-8569-13e1c7238101.png)

3. Since we copied the spacing on the left (along with the text), we should be able to place our cursor to the very left and paste (or even just paste). Instead of the correct formatting we get something like this:
![image](https://cloud.githubusercontent.com/assets/6901336/23234281/2e47d3fe-f917-11e6-9bd8-ca64a5689e00.png)

   or this (without moving the text cursor)
   ![image](https://cloud.githubusercontent.com/assets/6901336/23234306/47277884-f917-11e6-9c54-b7bd6020f27d.png)

I assume this is an issue with the newer format feature, but I could be wrong.

**Comment by warpdesign** [comment]
I'm not sure this should go there but one nice thing I noticed about Java IDE is the fact that when pasting text inside a string, the pasted string is escaped if necessary.

So, pasting `I'm doing well` here:
    let message = "paste here: ";
would result in:
    let message = "paste here: I\'m doing well";

**Comment by King66** [comment]
I have an issue with formatOnPaste:
copy the following code into <script></script> with "editor.formatOnPaste": true, it looks not good
(function() {
  var updateButton = document.getElementById('updateDetails');
  var cancelButton = document.getElementById('cancel');
  var favDialog = document.getElementById('favDialog');

  // Update button opens a modal dialog
  updateButton.addEventListener('click', function() {
    favDialog.showModal();
  });

  // Form cancel button closes the dialog box
  cancelButton.addEventListener('click', function() {
    favDialog.close();
  });
})();

![1](https://cloud.githubusercontent.com/assets/11925432/23697150/902addfe-0421-11e7-8ed6-d1dbc7c6bafa.jpg)

**Comment by FeaRCODE** [comment]
I have found another issue with HTML regarding AutoComplete. When adding another element in a tag like this:

![image](https://cloud.githubusercontent.com/assets/6901336/24332687/c2a50078-1210-11e7-9bb6-a471ab4e2730.png)

And press enter, part of the closing tag gets removed.

![image](https://cloud.githubusercontent.com/assets/6901336/24332691/d8b3163e-1210-11e7-8efb-5f7120cb0e1f.png)

Not sure if this needed another issue created.
@aeschli @kieferrm
