### ISSUE TITLE
Notebook Formatting does not respect default formatters on save + on execution

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#212124]
Related: 
- https://github.com/astral-sh/ruff-vscode/issues/383
- https://github.com/microsoft/vscode/issues/196050
--- 
Looking into reports of X formatter being used instead of Y in various flows. Looking at both on save and on execution formatting participants, one common point is that when `Format Cell` is specifically being used, the intended formatter is applied as expected. 

Some early digging is pointing to a use of `getDocumentFormattingEditsUntilResult` instead of `formatDocumentWithSelectedProvider`, so will be working out a fix there. Will update this thread as is relevant.

**Comment by andreamah** [comment]
@Yoyokrazy do you have some minimal verif steps?

**Comment by Yoyokrazy** [comment]
Verification Steps:
- Install Black Formatter + Ruff
- Create settings.json with only the following:
```json
// issue repro
"editor.formatOnSave": true,
"editor.defaultFormatter": "ms-python.black-formatter",
"notebook.formatOnSave.enabled": true,
"black-formatter.args": [
  "--skip-string-normalization"
],
```
- create notebook with a single code cell, and contents `print('hi')`
- In Stable (🐛)
  - Save Notebook 
  - Black formatter runs => nothing changes
  - Ruff formatter runs => Single quotations turned to double quotations (🐛)
- In Insiders (✅)
  - Save Notebook
  - ONLY Black formatter runs => nothing changes
