### ISSUE TITLE
Add option to create new branch when typed branch doesn't exists

### ISSUE THREAD

**Issue by DarusX** [microsoft/vscode#212116]
![image](https://github.com/microsoft/vscode/assets/20015847/786d7efd-01ef-4f54-b761-79b55453e6f9)
![image](https://github.com/microsoft/vscode/assets/20015847/a004f564-cf8a-4d2e-b1e5-f2bece78f798)

**Comment by gjsjohnmurray** [comment]
That should already happen when you press Enter.

**Comment by gjsjohnmurray** [comment]
Is your VS Code up to date?
