### ISSUE TITLE
Terminal links: url parameters value ignored

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#21225]
- VSCode Version: 1.10 insider
- OS Version: windows 10

Steps to Reproduce:

1. open the terminal from VSCode and have it print an url with an url parameter, like `https://github.com/foo?param=ignored`

Click on the link: the page `https://github.com/foo?param` will be opened instead of the full url with parameters `https://github.com/foo?param=ignored`.

![terminallink](https://cloud.githubusercontent.com/assets/199648/23236211/9e5e6fe0-f958-11e6-823f-6652d9a9d1ff.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/21186
