### ISSUE TITLE
Searching with Match Case turned off still does case matching

### ISSUE THREAD

**Issue by TheDutchCoder** [microsoft/vscode#212263]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.0
- OS Version: MacOS 14.4.1 (23E224)

Steps to Reproduce:

0. Turn off Match Case in the search
1. Search for `isthing` (will match all different casings, **good**)
2. Search for `isThing` (will _only_ match `isThing`, **bad**)

I'd expect #2 to only be correct with Match Case turned **on**

**Comment by TheDutchCoder** [comment]
Holy moly, it's a setting enabled by default
<img width="1003" alt="image" src="https://github.com/microsoft/vscode/assets/1668207/bcc0e948-f336-44be-b07c-d63818b2eaf4">

Please turn this off by default 😬

**Comment by andreamah** [comment]
Smart case should already be off by default. Perhaps it was enabled by accident or by an extension.
