### ISSUE TITLE
Ctrl+click does not work anymore

### ISSUE THREAD

**Issue by JamesFraserLogan** [microsoft/vscode#212200]
Type: <b>Bug</b>

It used to inspect, now it's multiple curors. I can't reset this. I uinstalled, checked for files (none there), reinstalled.

I can't use "click" as a combination for any keybind now.

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900KS (32 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.77GB (53.93GB free)|
|Process Argv|--crash-reporter-id d59e36bf-9dd3-4305-9d5a-39f91afb4b6a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-log-viewer|ber|0.14.1
githistory|don|0.6.20
vscode-drawio|hed|1.6.6
vscode-edit-csv|jan|0.9.1
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.22.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.1
debugpy|ms-|2024.6.0
pylint|ms-|2023.10.1
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter-keymap|ms-|1.1.2
remote-wsl|ms-|0.88.2
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.13
vscode-serial-monitor|ms-|0.11.0
autodocstring|njp|0.6.1
material-icon-theme|PKi|5.1.0
sqlite-viewer|qwt|0.4.9
LiveServer|rit|5.7.9
vscode-qt-for-python|sea|7.6.0
code-spell-checker|str|3.0.1
qtvsctools|ton|0.11.0
vscode-pets|ton|1.25.1
cmake|twx|0.0.17
vscode-arduino|vsc|0.6.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
showvideot:31016892
dsvsc021:30996838
f3je6385:31013174
fchga941:31038042
pythonprc:31039816
dwnewjupyter:31039675

```

</details>

**Comment by JamesFraserLogan** [comment]
I manually deleted %APPDATA%\Code, reinstalled again and it worked.

Oddly, I didn't have to reinstall my addons. Not sure how this makes sense, but I can ctrl+click now and navigate around my code.

**Comment by ulugbekna** [comment]
Closing as this was resolved.
