### ISSUE TITLE
Settings text for window.title hard to read on hover

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#21222]
Testing #20433

See below. This is an issue with all settings that's amplified in this case (AFAIK the descriptive text on other settings doesn't depend as much on line breaks.)
![screenshot from 2017-02-22 17-18-30](https://cloud.githubusercontent.com/assets/762848/23235319/1620d210-f923-11e6-8e8c-c856099db742.png)

**Comment by bpasero** [comment]
@aeschli this is the thing we talked about, I would like the hover to preserve my newlines.

**Comment by aeschli** [comment]
Fixed by Microsoft/vscode-json-languageserver@3c3ab9fe2b51dc203a77234135a624552fa5dd4a
