### ISSUE TITLE
Add command to run all notebook cells above the currently selected one

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#212271]
Re-running all until current cell is very useful in many cases, examples:

- installed a new lib, had to reload kernel, now need to re-run until current cell
- did some out-of-order evaluation of cells during prototyping and need to re-run sequentially to make sure the environment is defined correctly -- all values are as expected by the order of cells
- had to kill kernel due to a bug and need to re-run all until current cell

**Comment by amunger** [comment]
`notebook.cell.executeCellsAbove` is a core command that sounds like what you're looking for.
 or `jupyter.runPrecedentCells` from the jupyter extension to just run the cells that the current one depends on
