### ISSUE TITLE
Unthemable product icons #2

### ISSUE THREAD

**Issue by DeltaRazero** [microsoft/vscode#212259]
Does this issue occur when all extensions are disabled?: Yes (all other extensions disabled)

- Version: 1.89.0
- Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
- Date: 2024-05-01T02:09:22.859Z
- Electron: 28.2.8
- ElectronBuildId: 27744544
- Chromium: 120.0.6099.291
- Node.js: 18.18.2
- V8: 12.0.267.19-electron.0
- OS: Windows_NT x64 10.0.22621

---

This is a continuation of https://github.com/microsoft/vscode/issues/208343. I'm in the process of creating a product icon theme and noticed the following icons not being (properly) replaced. They either appear invisible or are unthemed. There may be more icons that suffer from the same problems described below, but I have not been able to find them as of writing this.

### Settings icon, used for the settings editor tab

The icon is invisible after applying the theme.

This is due to the following CSS rule overriding the `font-family` attribute:
![image](https://github.com/microsoft/vscode/assets/26445643/69a691e1-640c-4271-a446-7611f1a8201a)

### Search icon, used for the search editor tab

Same as settings editor tab icon, it's invisible for the same CSS rule overriding the `font-family` attribute.

### More/three dots (codicon-toolbar-more)

Visible in, for example, output and terminal panel views (left next to close icon), editor tabs more actions (where the 'split editor' action icons is), etc.

This doesn't appear to get any overrides at all, so it remains unthemed.

### Setting editor item chevron-down dropdown icon

The icon is invisible after applying the theme.

This is due to the a second `font-family` attribute always being present and overriding the first attribute that correctly retrieves which value `font-family` should have.

![image](https://github.com/microsoft/vscode/assets/26445643/b986e7ab-d697-42b9-842f-02b7d41ea491)

**Comment by aeschli** [comment]
To verify:
- extends the [product icon theme smaple](https://github.com/microsoft/vscode-extension-samples/blob/main/product-icon-theme-sample)
with
```
		"settings-editor-label-icon": {
			"fontCharacter": "\\e000"
		},
		"toolbar-more": {
			"fontCharacter": "\\e000"
		},
		"more": {
			"fontCharacter": "\\e000"
		},
		"search-editor-label-icon": {
			"fontCharacter": "\\e000"
		},
```

- export it as VSIX, import select the `VSCode 1.0 Icons` theme
- verify that the settings editor has now a explorer icon, as well the more icons
