### ISSUE TITLE
Un collapse line

### ISSUE THREAD

**Issue by PaulSicurello** [microsoft/vscode#212204]
Type: <b>Feature Request</b>

<div class: '...'></div>
how do I get it so that it is not collapsed, I lost.

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:

```[tasklist]
### Tasks
```

**Comment by PaulSicurello** [comment]
![Screenshot 2024-05-07 135743](https://github.com/microsoft/vscode/assets/24198665/2e8212ea-be66-42f7-957b-b90f40c643da)
How do I get it so that my code does not collapse, see screen shot

**Comment by aeschli** [comment]
Folding in the middle of a line is not a feature that we have in the regular VS Code.
Can you run with all extensions disabled?

**Comment by PaulSicurello** [comment]
Well, I uninstalled most of my  extensions  and it is not doing any longer.
Thanks for getting back to me.
