### ISSUE TITLE
Terminal copilot hint shows in restored terminals

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#212278]
When I use a terminal, then reload the window, sometimes the terminal hint shows even though there is history in the terminal. That feels inconsistent, maybe I should only see it in a totally fresh terminal

<img width="725" alt="image" src="https://github.com/microsoft/vscode/assets/323878/ff4b0729-e68f-44af-b80b-1d9c1eb27929">

**Comment by roblourens** [comment]
This also shows a case where the terminal hint didn't overlap my prompt, like in my other issue, but here when I deleted this terminal and created a new one, then it overlapped.

**Comment by roblourens** [comment]
I still see this sometimes, not every time
<img width="402" alt="image" src="https://github.com/microsoft/vscode/assets/323878/4b928ecf-d3b7-456f-bd49-9f52fdf63c3f">

I followed these steps just now
- Have a terminal that I've used
- Hide the panel
- Reload the window
- Go back to the same terminal, run a command
- See the hint

**Comment by meganrogge** [comment]
really weird that you'd see it after running a command 🤔

**Comment by meganrogge** [comment]
for a reconnected terminal, reconnection properties is undefined 
<img width="374" alt="Screenshot 2024-06-03 at 12 28 25 PM" src="https://github.com/microsoft/vscode/assets/29464607/b5d7c0b7-84ab-418c-b787-c831431f96bb">
