### ISSUE TITLE
CSS color picker disappeared and other features in CSS files

### ISSUE THREAD

**Issue by criZorr** [microsoft/vscode#212291]
Type: <b>Performance Issue</b>

I just opened a CSS file and now VS doesn't show the color square (picker), other options like autocomplete properties it doesn't work.
I also disabled all extensions and the issue stills up.

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.88GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id 40eb9858-2968-438b-8ab3-79c014e366ef|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   104	  3692	code main
    0	   101	  2728	shared-process
    0	    39	  7576	   utility-network-service
    0	    88	  7652	fileWatcher [1]
    0	    96	  9492	window [2] (Issue Reporter)
    0	   121	 13508	   gpu-process
    0	    29	 13512	   crashpad-handler
    0	   125	 13708	extensionHost [1]
    0	   186	 13744	window [1] (styles.css - genshin-web-app - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (styles.css - genshin-web-app - Visual Studio Code)
|    Folder (genshin-web-app): 10 files
|      File types: png(3) svg(1) html(1) css(1)
|      Conf files:;
```

</details>
Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
dsvsc021:30996838
9c06g630:31013171
a69g1124:31038041
dvdeprecation:31040881
dwnewjupytercf:31039676

```

</details>

**Comment by aeschli** [comment]
Make sure the editor is in `CSS` language mode. You can see that in the status bar.
Maybe you change the language mode manually or in the settings?

**Comment by bulrush15** [comment]
Fixed it. I have the same problem in VSC 1.72.2 with an scss file. At the bottom right of the status bar it said "Django.txt". I clicked "Django.txt" and changed it to "SCSS" and I can see the color chooser box now. 
![image](https://github.com/microsoft/vscode/assets/7031486/225e50a9-0566-4265-8377-c27335693270)
