### ISSUE TITLE
Terminal Issue

### ISSUE THREAD

**Issue by m-agostina** [microsoft/vscode#212210]
Type: <b>Bug</b>

Hello, I'm having some issues with the terminal. Since the last update it's very slow. I tried unistalling vs code twice but it didn't work. I also deleted all the extensions and the settings.json file. I checked all the settings and changed them but it didn't solve the problem.
Hope you can help me.
Thanks.

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.35GB (13.77GB free)|
|Process Argv|--crash-reporter-id cfbbb867-c0a8-46d8-9693-c800ab722a49|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.4
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.6.0
prettier-vscode|esb|10.4.0
material-icon-theme|PKi|5.1.0
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31018789
dsvsc021:30996838
9c06g630:31013171
pythonprt:31039817
dwnewjupytercf:31039676

```

</details>

**Comment by IllusionMH** [comment]
Have you tried to disable `terminal.integrated.shellIntegration.enabled` setting? Is it faster if disabled?

**Comment by m-agostina** [comment]
> Have you tried to disable `terminal.integrated.shellIntegration.enabled` setting? Is it faster if disabled?

Thanks a lot, that worked just fine!

**Comment by IllusionMH** [comment]
May be related to #212090 but that one is in Insiders
