### ISSUE TITLE
"Diff" files are often not properly detected by automatic language mode detection / syntax highlighting

### ISSUE THREAD

**Issue by mstange** [microsoft/vscode#212265]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.0
- OS Version: macOS 14.4.1

Steps to Reproduce:

1. Run `git diff | code -` when you have local changes in a git repo.
2. Look at the diff and hope that the syntax highlighting makes sense.

Usually the syntax highlighting is wrong because it auto-detected the wrong language; it'll detect Python for Python diffs, Rust for Rust diffs etc. I have to manually switch the language to "Diff".

The diff files I'm looking at all start with `diff --git ` which should be weighted as evidence that this is not Rust / Python.

**Comment by TylerLeonhardt** [comment]
Let's include this with https://github.com/microsoft/vscode/issues/131450

Thanks for the feedback!
