### ISSUE TITLE
Error during MAUI projet compilation: "...building for iOS Simulator, but linking in dylib built for iOS, file 'libHarfBuzzSharp' for architecture arm64"

### ISSUE THREAD

**Issue by Yevhen-Myroshnychenko** [microsoft/vscode#212258]
Type: <b>Bug</b>

I can build and run my project with Visual Studio 2022 for MAC but when I try to use VS Code for this, I get an error:

/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8043/targets/Xamarin.Shared.Sdk.targets(1559,3): error : clang++ exited with code 1: [/Users/yevhenmyroshnychenko/Projects/FacilitEase-Mobile/FacilitEase/FacilitEase.Mobile/FacilitEase.Mobile.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8043/targets/Xamarin.Shared.Sdk.targets(1559,3): error : ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/yevhenmyroshnychenko/.nuget/packages/harfbuzzsharp.nativeassets.ios/2.8.2.3/runtimes/ios/native/libHarfBuzzSharp.framework/libHarfBuzzSharp' for architecture arm64 [/Users/yevhenmyroshnychenko/Projects/FacilitEase-Mobile/FacilitEase/FacilitEase.Mobile/FacilitEase.Mobile.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8043/targets/Xamarin.Shared.Sdk.targets(1559,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation) [/Users/yevhenmyroshnychenko/Projects/FacilitEase-Mobile/FacilitEase/FacilitEase.Mobile/FacilitEase.Mobile.csproj::TargetFramework=net8.0-ios]

VS Code version: Code 1.89.0 (Universal) (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:10:10.196Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|64.00GB (9.10GB free)|
|Process Argv|--crash-reporter-id 547b46b4-5eda-4055-8b59-8dfae93e0d33|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-better-align|cho|1.4.2
copilot|Git|1.187.862
copilot-chat|Git|0.15.2024043005
cloudcode|goo|2.9.0
vscode-docker|ms-|1.29.1
csdevkit|ms-|1.5.20
csharp|ms-|2.28.11
dotnet-interactive-vscode|ms-|1.0.5229040
dotnet-maui|ms-|0.11.57
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.0.5
vscodeintellicode-csharp|ms-|2.1.11
vscode-edge-devtools|ms-|2.1.5
vscode-kubernetes-tools|ms-|1.3.16
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.22.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.1
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.362.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
mono-debug|ms-|0.16.3
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
vscode-speech|ms-|0.8.0
sqltools|mtx|0.28.3
sqltools-driver-mssql|mtx|0.4.3
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
swift-lang|ssw|1.9.0
open-in-browser|tec|2.0.0
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31018789
dsvsc021:30996838
01bff139:31013167
dwnewjupytercf:31039676

```

</details>

**Comment by adamzucchi** [comment]
I am also seeing this bug on VS Code when trying to build and deploy to an iOS simulator.

**Comment by adamzucchi** [comment]
I found a workaround after reading up on the following issue:

https://github.com/mono/SkiaSharp/issues/2307

Apparently we must be using a package that has a dependency on SkiaSharp (and it must be an old out of date version) and when you update to the latest stable (currently 2.88.8) the error above is resolved.

**Comment by joyceerhl** [comment]
This repo is for VS Code-specific issues, please consider filing in https://github.com/dotnet/maui.
