### ISSUE TITLE
Zoom level reset when (auto)saving tasks.json

### ISSUE THREAD

**Issue by ntrogh** [Microsoft/vscode#2122]
You lose the current zoom level when editing and saving tasks.json. I expect the current zoom level to be kept as it was before saving.

Repro steps:
1. open tasks.json
2. change the zoom level
3. make any random edit
4. manually save the file or autosave kicks in
OUTCOME: zoom level is reset

VS Code version: 0.10.6

**Comment by weinand** [comment]
Indeed, I can reproduce this.

**Comment by bpasero** [comment]
I think I fixed this, @weinand did you try with latest?

**Comment by weinand** [comment]
@bpasero I saw this with 0.10.6 but I just verified that it no longer occurs in the latest.
