### ISSUE TITLE
Minimap lacks separation from editor

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#21229]
- VSCode Version: Code - Insiders 1.10.0-insider (256d76fed7947e7289f921df10658d7a69233b65, 2017-02-22T07:04:54.544Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|autofilename|JerryHong|0.1.3|
|vscode-simple-icons|LaurentTreguier|0.10.0|
|vscode-docker|PeterJausovec|0.0.11|
|azure-cli|chrmarti|0.3.0|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.2.5|
|ghlink|dt|0.0.5|
|tslint|eg2|0.8.1|
|vscode-scss|mrmlnc|0.6.1|
|PowerShell|ms-vscode|0.9.0|
|cpptools|ms-vscode|0.10.0|
|debugger-for-chrome|msjsdiag|2.5.2|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.3.1|

---

Because their backgrounds are the same, it sometimes looks like a line is much shorter than it actually is below the minimap's colored content. E.g., line 123:
![screen shot 2017-02-22 at 3 04 03 pm](https://cloud.githubusercontent.com/assets/9205389/23237008/5033d1f4-f910-11e6-8291-5bf80f0bc038.png)

A simple fix might be to end the minimap where its content ends.

**Comment by roblourens** [comment]
Maybe related, it cuts off the special buttons in some editors, like launch.json:

![image](https://cloud.githubusercontent.com/assets/323878/23243017/0c6b6b82-f931-11e6-8310-9338f05484f7.png)

**Comment by bpasero** [comment]
@alexandrudima am I doing something wrong, for me I see no separation to the minimap:

![image](https://cloud.githubusercontent.com/assets/900690/23302062/57db26fe-fa8d-11e6-8171-13e89a940f34.png)

This is running "out of sources".

**Comment by alexandrudima** [comment]
The shadow is dropped when there is a horizontal scrollbar and the scrollLeft is not at its maximum position. Exactly how the top shadow works.

i.e. make a line long enough that it is wider than the viewport.

**Comment by bpasero** [comment]
@alexandrudima oh I see, I somehow thought this would mean to add a general separation from the editor. E.g. I think it still looks a bit weird in this case where the viewzone just stops:

![image](https://cloud.githubusercontent.com/assets/900690/23305183/d6751668-fa9d-11e6-88b0-1be673834554.png)

**Comment by alexandrudima** [comment]
Yeah, that looks slightly weird. I wonder why the tree is not in the same dark blue shade. Perhaps that would help. i.e. on the left hand side it doesn't feel weird. @jrieken 

I would love a UX designer input here ...

**Comment by jrieken** [comment]
Unsure how the color have been defined. I think someone aligned with the explorer... UX input please. Tho it might make sense to always show the drop shadow?

**Comment by alexandrudima** [comment]
The dom arrangement of things doesn't make the shadow work either. I suggest we open a separate issue for the embedded editors case:

![image](https://cloud.githubusercontent.com/assets/5047891/23305955/6b8a268c-faa1-11e6-99de-bb67a1eb3d64.png)

**Comment by bpasero** [comment]
Or maybe start to draw a border if and only if a viewzone is there?

**Comment by alexandrudima** [comment]
Let's track in #21359. This issue solves the problem for the text overflowing case.
