### ISSUE TITLE
getConfiguration() always pulls defaults, even when workspace settings are present

### ISSUE THREAD

**Issue by jhechtf** [microsoft/vscode#212220]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:  1.89.0
- OS Version: Windows 10.0.19045

Steps to Reproduce:

1. Create an extension project through the `yo` generator given in the docs
2. Add in a `contributes.configuration` of 
```json
      "gitAngular.alwaysPresent": {
          "title": "Perpetual",
          "scope": "window",
          "type":"object",
          "default": {
            "jim": "is always here"
          }
        },
```
3. In a project's `settings.json` file add in an entry, which should override the values, like such
```json
"gitAngular.alwaysPresent": {
    "bob": "is a critical member of the team"
  },
```
4. Attempt to get the configuration with the following code, registered in any command your extension offers
```ts
const config = workspace.getConfiguration('gitAngular');
console.info('TESTING', config.get('alwaysPresent');
```
5. Output should include both "bob" and "jim" keys, e.g. 
![image](https://github.com/microsoft/vscode/assets/8152471/da3f65a6-a27e-4e55-9f64-68cf58967a01)

**Comment by sandy081** [comment]
This is designed. We do not override object types, instead we merge them. This is true for all settings of type object.

**Comment by jhechtf** [comment]
Could I get an explanation because that is not at all what I would expect.

**Comment by sandy081** [comment]
This is what the expected behaviour for most of the settings of such type for eg.,  `*.exclude`
