### ISSUE TITLE
Sidebar Explore button hidden when interacting with any other side-bar button on Linux

### ISSUE THREAD

**Issue by sot1986** [microsoft/vscode#212249]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.0
- OS Version: Linux x64 6.5.0-28-generic snap

Steps to Reproduce:

1. Press Cntrl+Shift+F to open search menu

![image](https://github.com/microsoft/vscode/assets/78511840/32ad0ddb-e35a-40c6-9546-a7c9e9569cf4)

__The Exporer button will appear again pressing Cntrl+Shift+E__

- Node.js = 18.18.2
- V8 = 12.0.267.19-electron.0

**Comment by gjsjohnmurray** [comment]
Please use the `Reset View Locations` command.

**Comment by sot1986** [comment]
Unfourtunately it's not helping.
However if it is only my configuration issue and not a version issue (with previous one I don't remember this behaviour) I apologize and you can close it. Thank you.
