### ISSUE TITLE
experimental intellisense for PowerShell dumps a wall of text

### ISSUE THREAD

**Issue by yg-i** [microsoft/vscode#212226]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.89.0
- OS Version: Win10 10.0.19045

Steps to Reproduce:

1. Set `"terminal.integrated.shellIntegration.suggestEnabled": true` in settings.json
2. Focus terminal
3. type `Get-ChildItem`

Here's a gif demonstration

<img src="https://github.com/microsoft/vscode/assets/148152939/79418e29-2044-497b-8fa2-44eb78b31966" width="400" />

**Comment by karthiknadig** [comment]
Please try the latest version and see if this is still happening.

**Comment by Tyriar** [comment]
We're also planning on removing this in favor of a new approach for suggestions, so this code will get ripped out eventually https://code.visualstudio.com/updates/v1_96#_terminal-completions-for-more-shells
