### ISSUE TITLE
`Terminal: Kill All Terminals` command kills remote SSH session on Windows

### ISSUE THREAD

**Issue by torext** [microsoft/vscode#212239]
Type: <b>Bug</b>

On Windows, with the latest versions of VSCode and the Remote - SSH extensions, running the `Terminal: Kill All Terminals` command from the command palette now makes the remote connection die and reconnect. This does not happen on a Linux (specifically Ubuntu) installation of the same versions of VSCode and the remote extension. Moreover, this did not use to happen on Windows either a few weeks ago runninng older versions of VSCode and/or the remote extension.

This is a problem because frequently one would like to kill all idle running terminals while working remotely; now this is impossible on Windows as it messes with the remote connection itself.

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Remote OS version: Linux x64 5.15.0-105-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6242R CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|32.00GB (14.01GB free)|
|Process Argv|--crash-reporter-id 9e773f15-1d9a-4f02-85bc-7289c49113ba|
|Screen Reader|no|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: remote-hostname|
|OS|Linux x64 5.15.0-105-generic|
|CPUs|Intel(R) Core(TM) i9-7940X CPU @ 3.10GHz (28 x 1200)|
|Memory (System)|62.50GB (54.90GB free)|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
vim|vsc|1.27.2
ruff|cha|2024.20.0
gitlens|eam|14.9.1
latex-workshop|Jam|9.20.1
vsc-python-indent|Kev|1.18.0
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
autodocstring|njp|0.6.1
even-better-toml|tam|0.19.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31018788
dsvsc021:30996838
724cj586:31013169
a69g1124:31038041
dwnewjupytercf:31039676

```

</details>

**Comment by roblourens** [comment]
I recommend setting `"remote.SSH.useLocalServer": true`. Note that you need to set this directly in your settings.json file even when it appears checked in the settings editor.

This will switch to a mode where a hidden terminal isn't used to manage the connection and is the default on other platforms, but not windows.

**Comment by torext** [comment]
Ah yes, that seems to have fixed the issue, many thanks!. So does that mean that the default value of that setting has been recently changed on Windows? And, to maybe understand better, what would be the (dis)advantage of setting that to `False`?

**Comment by roblourens** [comment]
It is just disabled by default on Windows because some older version of Windows OpenSSH had some bugs. At this point, most users will have moved off those versions of ssh, so I hope to switch the default to match other platforms.
