### ISSUE TITLE
Terminal copilot hint overlap

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#212221]
I see this, but I think I've seen it correct in the past? But right now it's reproable in new terminals

<img width="708" alt="image" src="https://github.com/microsoft/vscode/assets/323878/9b33ee59-ac7d-4e0e-91bb-10944404ecab">

**Comment by roblourens** [comment]
Maybe related to my zsh prompt config, I can share the zsh config if it helps

**Comment by joaomoreno** [comment]
I see the same, since I use the same setup

<img width="1434" alt="Screenshot 2024-05-07 at 21 49 41" src="https://github.com/microsoft/vscode/assets/22350/6f1b9b25-3dd8-46f9-a275-401fbb5b04cb">

**Comment by meganrogge** [comment]
Yes can you pls share your zsh config?

**Comment by joaomoreno** [comment]
Steps are:

1. use zsh
2. install oh-my-zsh
3. open a terminal in a workspace that has a git repo

Let me know if that doesn't work for you.

**Comment by roblourens** [comment]
Disabled by default in https://github.com/microsoft/vscode/pull/212456 for now

**Comment by meganrogge** [comment]
@isidorn also mentioned he thinks it should use the terminal's font

**Comment by meganrogge** [comment]
Also, any terminal settings would help - do you set the font / letter spacing for example?

**Comment by meganrogge** [comment]
When this happens, I see `handleRightPrompt` in the logs. I also see that for the first prompt, the prompt start marker occurs before the `>>>` (see the status bar).

<img width="900" alt="Screenshot 2024-05-13 at 10 55 04 AM" src="https://github.com/microsoft/vscode/assets/29464607/e5e33a99-3bc3-4dcf-ae38-045db482f88c">

**Comment by meganrogge** [comment]
Handle prompt start happens before the `>>>` is added by the program. 

```
CommandDetectionCapability#handlePromptStart [0,0]
2024-05-13 10:58:34.020 [debug] CommandDetectionCapability#handleCommandStart [11,0]
2024-05-13 10:58:34.020 [debug] CommandDetectionCapability#handleRightPromptStart [128]
2024-05-13 10:58:34.021 [debug] CommandDetectionCapability#handleRightPromptEnd [128]
2024-05-13 10:58:34.021 [debug] Serial port requested application keypad. []
2024-05-13 10:58:34.022 [debug] CommandDetectionCapability#handlePromptStart [0,0]
2024-05-13 10:58:34.022 [debug] CommandDetectionCapability#handleCommandStart [15,0]
2024-05-13 10:58:34.022 [debug] CommandDetectionCapability#handleRightPromptStart [128]
2024-05-13 10:58:34.023 [debug] CommandDetectionCapability#handleRightPromptEnd [128]
2024-05-13 10:58:34.080 [debug] TextAreaSyncAddon#sync: text changed to "❯❯❯ " []
2024-05-13 10:58:34.080 [debug] TextAreaSyncAddon#sync: text changed to "❯❯❯ " []
```

**Comment by meganrogge** [comment]
We should be disposing of the decoration when there's input, even for this case, when that's happening via a shell script.

**Comment by meganrogge** [comment]
In the case of @roblourens, the specific `sorin` theme can be used without this issue if one removes `%(!. %B%F{1}#%f%b.)${editor_info[keymap]}` from the prompt in `$ZDOTDIR/.zprezto/modules/prompt/functions/prompt_sorin_setup`

Also note that the prompt is correct when a user hits enter. It's only the first prompt that is wrongly interpreted.

**Comment by meganrogge** [comment]
some things are done async for that theme and we don't wait for those

<img width="900" alt="Screenshot 2024-05-13 at 10 55 04 AM" src="https://github.com/microsoft/vscode/assets/29464607/811c43e5-c02a-498b-b9dc-effbcb12610b">
