### ISSUE TITLE
[WelcomeUX] Keymap links are missing telemetry

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#21224]

**Comment by chrmarti** [comment]
To verify: There should be 'installKeymap' and 'installedKeymap' events with the keymaps id and outcome.

**Comment by roblourens** [comment]
I see `installKeymap`, but how can I trigger `installedKeymap`? It's triggered if I try to enable a keymap that's already enabled, but the UI doesn't let me do that.
