### ISSUE TITLE
serve-web: `SECRET_KEY_MINT_PATH` does not honour `server-base-path`

### ISSUE THREAD

**Issue by michaelneely** [microsoft/vscode#212369]
The `code serve-web` command was augmented with the `server-base-path` argument here in https://github.com/microsoft/vscode/pull/207932.

Because the  `SECRET_KEY_MINT_PATH` does not include the `server-base-path`, any attempts to mint a key will result in a 404 if the server-base-path is set.

I think this is the reason why I am experiencing an issue that any sign-in attempt in the browser (e.g., Github Copilot, Settings Sync) do not persist between page refreshes.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: x64

Steps to Reproduce:

1. Launch `code serve-web --server-base-path=<something>`
2. Open the browser, observe 404s to `/_vscode-cli/mint-key`

**Comment by TylerLeonhardt** [comment]
@aeschli assigned to you since you approved the original PR
