### ISSUE TITLE
In VSCode, the total number of search results is no longer displayed, even after adjusting the UI settings.

### ISSUE THREAD

**Issue by xiezhipeng-git** [microsoft/vscode#212341]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.89.0
- OS Version: windows11

Steps to Reproduce:

1. the total number of search results is no longer displayed
![image](https://github.com/microsoft/vscode/assets/12825243/1c151602-d8a8-4f33-bfd6-1a966bfefc9b)

2.adjusting the UI settings no longer displayed
![image](https://github.com/microsoft/vscode/assets/12825243/a7cb6844-ad1d-475b-b825-8ce0ae16263e)

in old version.no this prolem.and the total number of search results is very useful.

**Comment by gjsjohnmurray** [comment]
Mine looks like this:

![image](https://github.com/microsoft/vscode/assets/6726799/c65f1f5d-c4e4-4304-9bd5-94a8c30d3bb1)


Please use the `Start Extension Bisect` command to investigate where your "filter" button comes from.

**Comment by xiezhipeng-git** [comment]
![image](https://github.com/microsoft/vscode/assets/12825243/3f5ab54a-8ee6-44d2-8839-3fb7b1d6fea5)
is it?
Could it be related to the Chinese language? That would still be a display issue.

**Comment by rebornix** [comment]
I think this is a notebook find widget. @Yoyokrazy when we update the find widget, we can probably check if the match info div has the same width as the one in the text editor.
