### ISSUE TITLE
VS Code cannot install (stuck on preparing to install page)

### ISSUE THREAD

**Issue by LuBu0505** [microsoft/vscode#212316]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  VSCodeUserSetup-x64-1.89.0.exe
- OS Version:  
```
Edition	Windows 11 Enterprise
Version	23H2
Installed on	‎8/‎2/‎2023
OS build	22631.3447
Serial number	****************
Experience	Windows Feature Experience Pack 1000.22688.1000.0
```
The error page.
![image](https://github.com/microsoft/vscode/assets/69841770/9f5e4aa5-93b7-4093-a7f7-76bbb7090c3c)
Processes info:
![image](https://github.com/microsoft/vscode/assets/69841770/82c6182a-1924-46ff-a6a9-4546d2303d5c)

Always block here. no progress.

Steps to Reproduce:

1. 
2.

**Comment by rzhao271** [comment]
Hi @LuBu0505, apologies for getting to the issue late. Is that your first time installing VS Code? Also, does the problem still occur with the latest installer available from the [Downloads](https://code.visualstudio.com/Download) page?
