### ISSUE TITLE
column location appears for some single-statement constructs

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#21232]
Testing #20793

Repro steps:
1. Launch `app.js` below w/ debugger (Node v.0.12.6, Linux)
```js
setInterval(function() {
    console.log("hello");
}, 1000);
```
2. Hit the breakpoint the first time (everything looks okay)
3. Hit the breakpoint the second time, column pointer appears:
![screenshot from 2017-02-22 18-47-44](https://cloud.githubusercontent.com/assets/762848/23238369/a0f977aa-f92f-11e6-9656-81ae8f81b16d.png)

**Comment by roblourens** [comment]
I'm guessing it shows because the debugger sends 'line x, column 4'. If possible, it might make sense to never show the column pointer if there is only whitespace before that column.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/21080
