### ISSUE TITLE
JS/TS language service crashed 5 times in the last 5 minutes

### ISSUE THREAD

**Issue by jonthemiller** [microsoft/vscode#212359]
Type: <b>Bug</b>

Open VSCode, open TS file. Wait for Intellisense status to load. Get notification of server crashing 5 times in the last 5 minutes.

I have disabled all extensions. I have reinstalled VS Code fresh. I have switched between TS versions from built in version from VS Code, to lib version in repo.

VS Code version: Code 1.89.0 (Universal) (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:10:10.196Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|17, 16, 10|
|Memory (System)|32.00GB (2.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jonthemiller** [comment]
I don't get this issue with a fresh copy of my repo. The repo is a monorepo with multiple TS projects in it, each with their own dependencies, etc. In a freshly checked out copy, I've only installed dependencies for 1 of the projects. 

Is there a limit for number of files the TS Server can be aware of? Are there recommendations for managing a monorepo beyond having a proper `.code-workspace` file?

**Comment by mjbvz** [comment]
Closing since it sounds like a memory issue.  [This guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) has more info about how to handle these and investigate crashes
