### ISSUE TITLE
Jupyter notebook cells pending for a long time before runtime

### ISSUE THREAD

**Issue by danaldea** [microsoft/vscode#212356]
ADD ISSUE DESCRIPTION HERE

After the initial execution of the Jupyter notebook (I'm using a 2processors, 8GB RAM research node), if I want to run any cell, the cell is first in pending mode for a long time, then runs.

An example attached, a cell with very simple instructions takes 3seconds to process but I had to wait a few minutes while it was in pending mode:

![image](https://github.com/microsoft/vscode/assets/40248541/675131b4-a9cf-4f05-a69a-e7668676b7d2)

No other workbooks or cells within a workbook are running.

This happens intermittently but today (09 May 2024) it happened for most of the day.

Version: 1.79.2
Commit: 33ccfa17ba96284baaff94925d567e69c3a2c694
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Embedder: server-distro

**Comment by danaldea** [comment]
![image](https://github.com/microsoft/vscode/assets/40248541/bcf85882-b5e7-41b4-a9c5-5ee66653ad67)

trades is a dataframe with approx 2-300 entries, with the jupyter setting to only display 20 entries (IIRC).
It's just running for a long time

**Comment by danaldea** [comment]
Found another thing, looks like the whole UI is stuck somehow.

Click on Resources does this:

![image](https://github.com/microsoft/vscode/assets/40248541/67d38838-9167-4acd-a692-eac2f558029d)


Entering a question for Mia does nothing when I click Send:

![image](https://github.com/microsoft/vscode/assets/40248541/6ecaaec2-242d-4b23-9011-03a5c5d6831f)

**Comment by amunger** [comment]
> Version: 1.79.2
This is a fairly old version of vs code and there have been some significant performance improvements since then. Try updating and please let us know if these issues persist.

you can also try adding the setting `"notebook.experimental.remoteSave": true` if you are working with a large notebook file
