### ISSUE TITLE
Input variables in launch.json are ignored in favour of those in tasks.json

### ISSUE THREAD

**Issue by makspll** [microsoft/vscode#212384]
Type: <b>Bug</b>

given launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387    
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug a test",
            "type": "lldb",
            "request": "launch",
            "cargo": {
                "args": [
                    "test",
                    "--features",
                    "--package",
                    "${input:features}",
                    "${input:package}",
                    "--lib",
                    "--",
                    // "${input:test_name}",
                    "--show-output"
                ]
            },
            "cwd": "${workspaceFolder}",
            "env": {
                "CARGO_MANIFEST_DIR": "${workspaceFolder}",
                "LD_LIBRARY_PATH": "${workspaceFolder}/target/debug/deps:${env:HOME}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib"
            }
        },
    ],
    // "inputs": [
    //     {
    //         "id": "features",
    //         "type": "promptString",
    //         "description": "Activate theese features",
    //     },
    //     {
    //         "id": "test_name",
    //         "type": "promptString",
    //         "description": "Run only tests including this string in their name",
    //     },
    //     {
    //         "id": "package",
    //         "type": "promptString",
    //         "description": "The crate location of this unit test",
    //         "default": "bevy_mod_scripting"
    //     },
    //     {
    //         "id": "pwd",
    //         "type": "promptString",
    //         "description": "The working directory for the test",
    //         "default": "${workspaceFolder}"
    //     },
    // ]
}
```
and tasks.json
```
{
    "version": "2.0.0",
    "inputs": [
        {
            "id": "test_name",
            "type": "promptString",
            "description": "Run only tests including this string in their name",
            "default": ""
        },
        {
            "id": "package",
            "type": "promptString",
            "description": "The crate location of this unit test",
            "default": "bevy_mod_scripting"
        },
        {
            "id": "features",
            "type": "promptString",
            "description": "Features to activate for the build",
        },
    ]
}
```

Regardless of if you uncomment the variables in launch.json, and then remove them in tasks.json, running the launch config will result in an error.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 6800HS with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.24GB (9.56GB free)|
|Process Argv|--crash-reporter-id aef4ad42-0e17-419b-bb76-4db5dac0ddc6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 6800HS with Radeon Graphics (16 x 3194)|
|Memory (System)|15.62GB (9.34GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sailfish|kog|0.1.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.362.0
remote-wsl|ms-|0.88.2
pdf|tom|1.2.2
errorlens|use|3.17.0
gitlens|eam|14.9.1
copilot|Git|1.188.0
copilot-chat|Git|0.15.1
rust-analyzer|rus|0.3.1950
crates|ser|0.6.6
even-better-toml|tam|0.19.2
vscode-lldb|vad|1.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
showvideoc:31016891
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31043157
pythonprc:31039816
dwnewjupyter:31039675

```

</details>

**Comment by roblourens** [comment]
I think I see what's going on, I think the `cargo` property gets resolved to some kind of task, and that's why it's looking for the inputs in tasks.json. 

I assume the extension is using a DebugConfigurationProvider, so if the extension is expecting this to happen differently, it's possible that they could use `resolveDebugConfigurationWithSubstitutedVariables` to have the variables resolved first. But I don't think vscode is actually doing anything wrong here, even though it's initially confusing.
