### ISSUE TITLE
Attach to Process + Node v0.12.6 (Linux) fails to detect node version

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#21231]
Testing #20991 
![screenshot from 2017-02-22 18-38-23](https://cloud.githubusercontent.com/assets/762848/23238107/689931a8-f92e-11e6-8620-ba7f592b617c.png)

And yet, for some reason it works fine with the Launch Program or Attach to Program configuration

**Comment by roblourens** [comment]
The message is technically true, but not that useful. We are assuming legacy protocol, because it's not using the inspector protocol. This sounds like an error, though. "Debugging with legacy protocol because inspector protocol was not detected"?

**Comment by weinand** [comment]
For the processId case now showing this message: 
"Debugging with legacy protocol because attaching to a process by ID is only supported for legacy protocol."
