### ISSUE TITLE
The application “Visual Studio Code” can’t be opened.

### ISSUE THREAD

**Issue by stefan-THD** [Microsoft/vscode#21230]
- VSCode Version: 1.9.1 Stable
- OS Version: 10.12.3

Steps to Reproduce:

1. Download zip
2. Unzip
3. Drag Visual Studio Code icon to Applications
4. Double click VS Code icon

<img width="532" alt="screen shot 2017-02-22 at 1 49 31 pm" src="https://cloud.githubusercontent.com/assets/25967386/23237509/540f4f7a-f923-11e6-9ac5-63765aa6e6c3.png">

Here is the error log in the console:

![screen shot 2017-02-22 at 5 23 25 pm](https://cloud.githubusercontent.com/assets/25967386/23237586/aac8e3e4-f923-11e6-97ef-3511c084c2c4.png)

**Comment by roblourens** [comment]
Did it work previously? I assume you've tried deleting and reinstalling the app?

**Comment by stefan-THD** [comment]
This is a on a new MacBook Pro, so it would be the first time to install, I tried re-downloading, deleting, reinstalling the app, also got the same issue when I tried the insider version.

**Comment by stefan-THD** [comment]
I tried to make "/Applications/Visual Studio Code.app/Contents/MacOS/Electron" executable and run it to see if I could more information about the issue and this is what it output in the termimal:

```
/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron ; exit;
C02T4H1VGTFJMBP:~ myUser$ /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron ; exit;
dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Visual Studio Code.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
	/Applications/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by joaomoreno** [comment]
How are you extracting the archive?

**Comment by stefan-THD** [comment]
With the default OSX Archive Utility.

**Comment by joaomoreno** [comment]
#17985

Please reconfirm that you're **really** using the default OS X Archive Utility.

**Comment by stefan-THD** [comment]
![screen shot 2017-02-28 at 11 33 13 am](https://cloud.githubusercontent.com/assets/25967386/23416759/c9409c1a-fda9-11e6-9203-1ef06965cbdf.png)

I suspect this issue is either related to my company proxy or disk encryption. My coworker is having the same issue, but I don't have a problem on my personal MBP. I was able to copy the uncompressed app file from my personal laptop to company laptop and it does open.

**Comment by joaomoreno** [comment]
Thanks. Yeah, there might be something on your company's policies.

**Comment by alvincrisuy** [comment]
I am using my personal laptop. And this also happens to me when I suddenly closed the VS Code while downloading in the Marketplace.

<img width="1112" alt="screen shot 2017-07-14 at 8 17 18 am" src="https://user-images.githubusercontent.com/7260700/28193101-f0b5fe2e-686c-11e7-9626-8cbd1407fb09.png">
