### ISSUE TITLE
Tooltip only displaying for Show Settings Watermark Control+,

### ISSUE THREAD

**Issue by manoellvitor** [microsoft/vscode#212355]
Version of VS Code: 1.89.0
![image](https://github.com/microsoft/vscode/assets/20465169/cd5e8a94-8b16-4f93-a329-c3a0e2594b2d)
Your operating system: Windows 11
List of extensions that you have installed: Happens with none installed.
Reproducible steps:
1 - Open VsCode.
2 - Hover over the Show Settings Ctrl + , Watermark
3 - Hover over Find in Files Ctrl + Shift + F
What you expected to see, versus what you actually saw:
When hover on Ctrl + ,
![image](https://github.com/microsoft/vscode/assets/20465169/6c65aee8-36e8-4220-841f-99ec3df97106)

When hover on Ctrl + Shift + F and any other
![image](https://github.com/microsoft/vscode/assets/20465169/d5f1b08e-931d-4ca8-9012-f61eca5c7c39)

https://github.com/microsoft/vscode/blob/9eff384b7799006696343d672afe4ce7b7aa774b/src/vs/workbench/browser/parts/editor/editorGroupWatermark.ts#L39

**Comment by bpasero** [comment]
This is a regression from https://github.com/microsoft/vscode/commit/cff275ae6414cf8ea7e4266b7e84e9eea4459161#diff-8113c62998d6b21d8fb9d4d4c7f811ba447c04d5c6e5dae7a48f4edbd52b2d39

**Comment by eisemsi2** [comment]
@bpasero Does the fix #212406 cause some other bug?

**Comment by bpasero** [comment]
I think we need to properly keep track of disposables.
