### ISSUE TITLE
Consider adding basic intellisense for JSDoc properties

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#21239]
Testing #21031
E.g. when you're inside of a JSDoc comment, @param or @returns would appear in the list.

**Comment by mjbvz** [comment]
Thanks. It looks like we only provide these suggestions after a `@`

I've opened https://github.com/Microsoft/TypeScript/issues/14254 to track returning the jsdoc annotation completions when on an empty doc comment line 

Closing as upstream
