### ISSUE TITLE
Contributing [Bulid & Run from Source] 

### ISSUE THREAD

**Issue by soulshined** [microsoft/vscode#212379]
Does this issue occur when all extensions are disabled?: Yes

## Synopsis 

Unable to complete all instructions as outlined here for Windows 11 https://github.com/microsoft/vscode/wiki/How-to-Contribute

I am getting an error around node_gyp at the step in the instructions that state to run `yarn`

![Screenshot 2024-05-09 141232](https://github.com/microsoft/vscode/assets/11242654/a5b8070a-237b-4c67-8a2a-bc55f1297e76)

I have double checked everywhere and ensured I followed all the directions and I believe I have so not sure if this is an error in instructions or user error

## Details

<details>
<summary> VS Code </summary>

Source: Latest commit from main branch
Developing on: 
Version: 1.89.0 (user setup)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
</details>

<details>
<summary> OS </summary>

Processor	AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
Installed RAM	96.0 GB (95.7 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 11 Home
Version	23H2
Installed on	‎12/‎2/‎2023
OS build	22631.3447
Experience	Windows Feature Experience Pack 1000.22688.1000.0
</details>

<details>
<summary> Misc </summary>

npm version = 10.5.0
node version = v18.20.2
nvm version = 1.1.12
yarn version = 1.22.22
python version = 3.12.3
msvs_version = 2022
</details>

I also ran into someone with similar issues in the extension discussions but I didn't think that was the right place for me to post since it's not really around extensions. https://github.com/microsoft/vscode-discussions/discussions/1151

**Comment by soulshined** [comment]
I tried this on my Windows 10 machine with no issues. My windows 10 machine just so happens to not use OneDrive

My Windows 11 machine I started using OneDrive. So I tried over in a local only folder on 11 and had some progress, I don't know what it is about OneDrive but it wasn't agreeable

![Screenshot 2024-05-10 121504](https://github.com/microsoft/vscode/assets/11242654/67a24930-8c10-4cb6-906f-32b1419c945b)

First thing I ran into was that the pre-install.js build script requires you to use node v20 LTS, but the instructions state we need `>=18.15.x and <19`

Running node-gyp config I get this output running on node v20:

![Screenshot 2024-05-10 142158](https://github.com/microsoft/vscode/assets/11242654/bdc9c147-6244-452b-9b5d-b61e433f9ff6)

I also ensured none of my paths include spaces per other issues users have reported

**Comment by imp-oh** [comment]
I have the same problem. Have you solved it

**Comment by soulshined** [comment]
> I have the same problem. Have you solved it

I haven't. I have been playing around with the preinstall script and changed things to try and it still didn't work. I'll have some time later this week to go deeper into that build lifecycle

**Comment by imp-oh** [comment]
> > I have the same problem. Have you solved it
> 
> I haven't. I have been playing around with the preinstall script and changed things to try and it still didn't work. I'll have some time later this week to go deeper into that build lifecycle


delete `package.json` file 
```json
    "preinstall": "node build/npm/preinstall.js",   // delete 
    "postinstall": "node build/npm/postinstall.js", // delete 
```
In use yarn

**Comment by soulshined** [comment]
> > > I have the same problem. Have you solved it
> > 
> > 
> > I haven't. I have been playing around with the preinstall script and changed things to try and it still didn't work. I'll have some time later this week to go deeper into that build lifecycle
> 
> delete `package.json` file
> 
> ```json
>     "preinstall": "node build/npm/preinstall.js",   // delete 
>     "postinstall": "node build/npm/postinstall.js", // delete 
> ```
> 
> In use yarn

Bummer. Doesn't work for me on Win 11 using Node 18 or 20

This fills a bit too complicated for something that should just be working so I will just wait for guidance
![Screenshot 2024-05-13 201444](https://github.com/microsoft/vscode/assets/11242654/445eb8df-efe7-42a3-a074-429ac2696319)

**Comment by roblourens** [comment]
Can you try again with the latest from main? I think there were some issues with building on windows with the latest Electron update that should be resolved now.

@deepak1556 can you update https://github.com/microsoft/vscode/wiki/How-to-Contribute for the Node version?
