### ISSUE TITLE
JSDoc IntelliSense for anonymous functions doesn't include parameters

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#21237]
Testing #21031

![image](https://cloud.githubusercontent.com/assets/762848/23239788/1b2ceec4-f91e-11e6-92be-5ab29796db91.png)

**Comment by mjbvz** [comment]
Looking through the TypeScript implementation, it looks like this is by design currently but I agree that we should have consistent behavior for function expressions as well

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/14280
