### ISSUE TITLE
Navigate to fully qualified type names (e.g. text::line::tests::widget::render_truncates_right in Rust)

### ISSUE THREAD

**Issue by joshka** [microsoft/vscode#212307]
In a rust tooling, it's common to render the full name of a type / method in a form that separates segments with colons. E.g. `text::line::tests::widget::render_truncates_right` is the name of a test in the `text::line::tests::widget` module, which is found in `src/text/line.rs`

```
failed: text::line::tests::widget::render_truncates_emoji::case_5_right_4
 thread 'text::line::tests::widget::render_truncates_emoji::case_5_right_4' panicked at src/text/line.rs:1104:13:
 buffer contents not equal
```

I'd like to be able to cmd+click (on mac) navigate to such identifiers from tool output (e.g. the output of a failed test). While tool output often also give a file link too, sometimes a test that failed and the location where the failure occurs are different (i.e. when a method that is being tested panics).

This is an interaction that I regularly attempt, with an intuitive expectation that it should work, only to be disappointed when it doesn't. It's possible to work around this, by searching manually, but it would be nice to have this built-in to the search experience (alternatively perhaps there's some interface that could be provided to extensions to extend this search to support this form of navigation).

This probably also applies to other languages that display fully qualified path names to types, not just rust.

Current behavior of Cmd+Click is to display the search files by name popup. This does not handle fully qualified type names.
Search for symbols (Cmd+T) doesn't support this either. It's possible that the trigger for this should be in the terminal as opposed to this being something added to the file search dialog.

**Comment by Tyriar** [comment]
Since this format is very rust-specific which vscode "core" doesn't know about, you should request this feature from the Rust extension which has the ability to do this with the `registerTerminalLinkProvider` api

**Comment by joshka** [comment]
Thanks - I wasn't exactly sure whether this was a built-in feature or language provided one TIL. :)
For anyone coming along behind searching for this the issue already exists for this at https://github.com/rust-lang/rust-analyzer/issues/7354 -  Clicking test link on terminal should be able to go to test
