### ISSUE TITLE
Column pointer doesn't allow insertions immediately before pointer

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#21234]
Testing #20793

Repro steps:
1. Launch debugging w/ app.js below
```
console.log('hello');
var a = function () {
    return "hi";
}

setInterval(function() {
    console.log(a());console.log(1);
}, 1000);
```
2. Step through until column pointer is as shown below:
![screenshot from 2017-02-22 19-04-13](https://cloud.githubusercontent.com/assets/762848/23238827/dca08b20-f931-11e6-8626-3dfd8288f65c.png)

3. Try deleting and re-adding the semicolon, or adding text before the pointer. 
![screenshot from 2017-02-22 19-00-32](https://cloud.githubusercontent.com/assets/762848/23238714/492f61ae-f931-11e6-8a89-d9cf90a36e4c.png)

**Comment by isidorn** [comment]
This is just how editor decorators are behaving. Corner case, closing as designed, will not fix
