### ISSUE TITLE
File encoding detect

### ISSUE THREAD

**Issue by iHuahua** [Microsoft/vscode#2123]
Sometimes the file's encoding is utf-8 or gbk, whatever how do i set, vscode always give me a surprise if the file has Chinese. can vscode detect the file encoding when it open? 
![qq 20160120211852](https://cloud.githubusercontent.com/assets/2878674/12450105/afd3f87a-bfbc-11e5-8b78-2452d8a54131.png)
![qq 20160120212136](https://cloud.githubusercontent.com/assets/2878674/12450106/afe58392-bfbc-11e5-84d3-620eda32a3d0.png)

**Comment by bpasero** [comment]
@iHuahua you can set the encoding globally or per workspace. We only detect the encoding for UTF 8, 16 LE or BE when a BOM is present in the file.

**Comment by iHuahua** [comment]
BOM header? It does not work in gcc env. the *.cpp file start with BOM, it will be so much error. Then, ATOM editor has encoding detect.

**Comment by iHuahua** [comment]
@bpasero BOM header? It does not work in gcc env. the *.cpp file start with BOM, it will be so much error. Then, ATOM editor has encoding detect.

**Comment by bpasero** [comment]
@iHuahua what is wrong with configuring the encoding for the workspace using settings?

**Comment by iHuahua** [comment]
@bpasero our project is cross platform SDK with c++, someone code with Windows/Visual Studio, some MAC/XCode, some linux/VIM, and some text editor, most of text editor save file without BOM header. Then the project contain more than 6000 files, they have different encoding. I love vscode, but it was a nightmare if i read the coce of the project with vscode.  Then, can u speak Chinese ?

**Comment by yucaowang** [comment]
Why this issue was closed? Not saw any plan/progress on this. I agree that auto detecting encoding would be a great help for large projects which may has various encoding for environments difference or historical reasons across thousands of files. Really need this feature +1.

**Comment by bpasero** [comment]
@yucaowang lets move the discussion into https://github.com/Microsoft/vscode/issues/5388
