### ISSUE TITLE
Opening a file in my Downloads folder opens /

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#21236]
I'm guessing that vscode is checking whether the file is open a folder that has been opened before, and so defaults to `/` since I've opened it before? I never want to open `/` automatically though. It makes the file watcher go crazy and feels very odd.

**Comment by chrmarti** [comment]
@roblourens Do you have a `.vscode` folder in `/`? That would trigger this behavior.

**Comment by roblourens** [comment]
I do, I didn't notice that. I deleted it and now I like the behavior.
