### ISSUE TITLE
Brace highlighting also selects column pointer

### ISSUE THREAD

**Issue by mousetraps** [microsoft/vscode#21233]
Testing #20793
![screenshot from 2017-02-22 18-58-09](https://cloud.githubusercontent.com/assets/762848/23238670/0e5bf6aa-f931-11e6-85e7-174cf8b80f5f.png)

**Comment by isidorn** [comment]
I guess this is just how decorators work.
Forwarding to @rebornix to investigate when he has time if bracket matching would not affect inline decorations
