### ISSUE TITLE
Is there a way can change hidden file color in sidebar?

### ISSUE THREAD

**Issue by opjlmi** [Microsoft/vscode#21247]
Hi, there is a question.

I wanna to recognize which is hidden file with color, not just with '.' .
But there is no way could setting hidden file color in sidebar, right?

<img width="356" alt="screen shot 2017-02-23 at 1 46 56 pm" src="https://cloud.githubusercontent.com/assets/6351593/23246763/d5313fde-f9d0-11e6-8688-657e601bc4e8.png">
(Left VS code, Right ATOM)

**Comment by roblourens** [comment]
This was brought up in #78 and is one possible solution to that issue
