### ISSUE TITLE
"when" support when registering a chat participant

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#212447]
User ask from https://github.com/microsoft/vscode/issues/199908#issuecomment-2102284689

fyi @amitjoshi438

**Comment by roblourens** [comment]
Steps:

- Modify https://github.com/microsoft/vscode-extension-samples/tree/main/chat-sample to add a "when" clause to the package.json (requires the `chatParticipantAdditions` proposal)
- When the "when" clause evaluates to false, the participant doesn't appear in the suggest widget in the chat input
- When it's true, the participant can be used normally
