### ISSUE TITLE
typescript语言服务意外中止5次

### ISSUE THREAD

**Issue by zmy3221** [Microsoft/vscode#21242]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.2.0|
|path-intellisense|christian-kohler|1.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.5.8|
|vscode-html-css|ecmel|0.0.33|
|code-runner|formulahendry|0.6.9|
|vue-snippets|hollowtree|0.1.0|
|intellij-idea-keybindings|k--kato|0.2.8|
|Go|lukehoban|0.6.53|
|vscode-icons|robertohuertasm|7.2.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please provide information about the issue you are seeing. Also try the VSCode insiders builds which includes a number of fixes for this sort of crash.
