### ISSUE TITLE
Stage selected lines does not show in git comparison view

### ISSUE THREAD

**Issue by grantborthwick** [Microsoft/vscode#21246]
- VSCode Version: Code - Insiders 1.10.0-insider (256d76fed7947e7289f921df10658d7a69233b65, 2017-02-22T07:10:23.895Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.8.0|
|vstsbuildstatus|jeppeandersen|0.5.0|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|team|ms-vsts|1.113.0|

---

Steps to Reproduce:

1. Open a repository
2. Make some change
3. Switch to the SCM view
4. Click on the change
5. Select some lines
6. Click on the ...
7. Observe the lack of the option to stage selected lines

**Comment by roblourens** [comment]
@joaomoreno should this be present? I see that it was considered part of #18615 at one point.

**Comment by codefoster** [comment]
I'm missing this functionality too. It used to be in the product until the March 2017 release that landed today. I see that Stage Selected Ranges is in there now, but that works differently. It doesn't let you stage one line at a time.

**Comment by joaomoreno** [comment]
Fixed in March. As for the _one line at a time_: #21513

**Comment by iamdevlinph** [comment]
I don't see any `Stage Selected Ranges` or am I missing something here?

![image](https://cloud.githubusercontent.com/assets/19337229/25079097/f60558d4-236b-11e7-9846-5637c391099d.png)

OS: Ubuntu 16.10
VS Code: 1.11.2

**Comment by codefoster** [comment]
I don't either now. They disappeared.

**Comment by joaomoreno** [comment]
@iamdevlinph @codefoster #24052
