### ISSUE TITLE
Japanese IME (input) freezes and unable to input

### ISSUE THREAD

**Issue by juntakata** [microsoft/vscode#212440]
Type: <b>Performance Issue</b>

I am using Windows OS (US locale) with Japanese IME enabled. While working on VS Code, Japanese IME sometimes freezes and I am unable to input Japanese. Enabling/disabling IME or switching windows and getting back to VS code sometimes resolves the issue. However, this is really frustrating experience.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900 (32 x 1997)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.70GB (35.11GB free)|
|Process Argv|--crash-reporter-id 8ff4f694-70a7-465a-9173-a5b6760ef6cc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    99	 39804	code main
    0	   109	  8712	extensionHost [1]
    0	    42	 15432	   utility-network-service
    0	   161	 15524	window [1] (eee-shadowing.txt - Visual Studio Code)
    0	    91	 27828	window [2] (Issue Reporter)
    0	    79	 33240	fileWatcher [1]
    0	    29	 37588	   crashpad-handler
    0	   132	 40200	shared-process
    0	    97	 43248	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.25.1
csdevkit|ms-|1.5.20
csharp|ms-|2.28.11
vscode-dotnet-runtime|ms-|2.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dwnewjupyter:31039675

```

</details>

**Comment by aiday-mar** [comment]
Hi I am trying to reproduce this issue and am not able to. Using Japanese in VS Code on Windows seems to work for me. Next time you see this issue, could you please include a screen recording of the issue as well as the text in the editor you see when the issue happens?
