### ISSUE TITLE
Settings Sync: Extension Uninstall behavior

### ISSUE THREAD

**Issue by ninelore** [microsoft/vscode#212439]
Does this issue occur when all extensions are disabled?: n/a

- VS Code Version: 1.89.1 (any)
- OS Version: any

Ive been seeing this for a while now:

If i use settings sync on multiple machines, uninstall an extension on machine A and the use machine B, the extension uninstalled on machine A will stay installed. In some cases, the uninstalled extension will be reinstalled when i use machine A again

Steps to Reproduce:

1. Have Extensions synced
2. Uninstall extension on machine A
3. Start VSCode on machine B: Extension still installed
5. Start VSCode again on machine A: Uninstalled extension potentially gets reinstalled automatically

I could not identify the conditions on which the extension gets reinstalled.

I would either expect or at least be able to set that uninstalled extensions should be uninstalled on all synced machines

**Comment by an-dr** [comment]
Same problem!

**Comment by sandy081** [comment]
Can you please open the **Settings Sync: Sync Activity (Remote)** view using `Settings Sync: Show Synced Data` command from the Command Palette and check which machine of yours is installing the extension back? 

Then from the machine can you please share/email me (sasmoava@microsoft.com) following data

- F1 > Settings Sync: Download Settings Sync Activity

**Comment by ninelore** [comment]
Hi @sandy081, your mail server rejected my mail with access denied

**Comment by ninelore** [comment]
dont worry. mail sent

**Comment by sandy081** [comment]
@ninelore I looked into your data and I do not see any pattern of extensions being uninstalled and installed by Settings Sync. Can you please let me know the problematic extension that is being uninstalled and installed? Are you able to still reproduce this?

**Comment by ninelore** [comment]
Hi @sandy081, unfortunately I since have stopped using vscode, but I was able to produce this until the end, which was somewhere between the last 1.94 recovery and 1.95. 

Some extension examples that were reinstalled are the entire Azure extension series, C# Dev Kit as well as the SQL Server extension, but I'm pretty sure there was at least 1 3rd party extension as well.

**Comment by sandy081** [comment]
Thanks for sharing info. I am not sure if I can reproduce and investigate the issue with the existing information. It would be great if this can be reproduced again so that we can collect more information. Closing this until then.
