### ISSUE TITLE
Copilot Chat Copy/Paste Broken

### ISSUE THREAD

**Issue by AdrianeNS** [microsoft/vscode#212448]
Type: <b>Bug</b>

Steps to Reproduce: 

1.  Ask GitHub Copilot a question the Copilot Chat left sidebar.
2.  Copy a few words from Copilot's response and paste them into any text editor.
3.  The entire response Copilot gave is pasted, rather than just the copied text.
4.  This is INCREDIBLY annoying!!! Please fix this asap/in the next update!!!

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (5.79GB free)|
|Process Argv|--crash-reporter-id 99e06c70-8cff-41e8-96d6-f52568ef4559|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
packer|4op|0.3.0
vagrant|bbe|0.5.0
vscode-obsidianmd|brp|0.2.0
vscode-markdownlint|Dav|0.55.0
gitlens|eam|14.9.1
copilot|Git|1.188.0
copilot-chat|Git|0.15.1
vscode-pull-request-github|Git|0.88.1
hcl|has|0.4.0
VS-code-vagrantfile|mar|0.0.7
remote-wsl|ms-|0.88.2
markdown-preview-enhanced|shd|0.8.13
vscode-packer-powertools|szT|0.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31018789
dsvsc021:30996838
g316j359:31013175
pythoncenvptcf:31043158
dvdeprecationcf:31040882
dwnewjupytercf:31039676

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/416
