### ISSUE TITLE
Explorer hides 

### ISSUE THREAD

**Issue by akashthapa** [microsoft/vscode#212404]
Type: <b>Bug</b>

Explorer hides when other tabs like source control or extension opened.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 6.5.0-28-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 3500)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.49GB (11.05GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 56bb87d9-126f-4446-b500-fb4bd7a13a13|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vim-cheatsheet|And|0.0.1
vscode-tailwindcss|bra|0.10.5
vscode-html-css|ecm|2.0.9
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
copilot|Git|1.188.867
copilot-chat|Git|0.15.1
ftp-simple|hum|0.7.6
vscode-language-babel|mgm|0.0.40
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
material-icon-theme|PKi|5.2.0
vscode-react-refactor|pla|1.1.3
vscode-thunder-client|ran|2.22.1
LiveServer|rit|5.7.9
code-spell-checker|str|3.0.1
sass-indented|syl|1.8.29
vsfire|tob|1.4.1
vscode-todo-highlight|way|1.0.5
glean|wix|5.2.2
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vswsl492cf:30256860
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31043157
a69g1124:31038041
pythonprt:31039817
dwnewjupytercf:31039676

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Reset View Locations command.

**Comment by lramos15** [comment]
Let me know if what is suggested above doesn't work and will reopen

**Comment by akashthapa** [comment]
Hi, yes that helped me.
