### ISSUE TITLE
Suggestion: for breaking comma separated values into rows

### ISSUE THREAD

**Issue by janzenz** [Microsoft/vscode#21241]
Hi I have a suggestion to include my extension [Break From Comma](https://marketplace.visualstudio.com/items?itemName=jzarzoso.break-from-comma) into VSCode itself. I'm not sure if it's good to merge or keep it as an extension. Let me know.

**Comment by roblourens** [comment]
I think that an extension is probably fine unless other editors commonly include this feature

**Comment by janzenz** [comment]
@roblourens yeah I'm thinking someone who might come up with an extension that will prettify code probably might include this feature. Nonetheless, just letting you know I'll be happy to help add this feature, just in case.

**Comment by mjbvz** [comment]
Closing as extension-candidate
