### ISSUE TITLE
Terminal path does not exist (after 1.89.1 upgrade)

### ISSUE THREAD

**Issue by Pithikos** [microsoft/vscode#212426]
After upgrading VSCode on Ubuntu, a simple shortcut firing `workbench.action.terminal.newWithCwd` just stopped working as seen below. The path definitely exists and restarted the computer - same issue.

**This breaks my whole workflow so can't do any actual work.**

![image](https://github.com/microsoft/vscode/assets/400048/4c942b22-6080-4024-80b9-bc85537ebed2)

Does this issue occur when all extensions are disabled?: **YES**

- VS Code Version: 1.89.1 dc96b837cf6bb4af9cd736aa3af08cf8279f7685 x64
- OS Version: Ubuntu 24.04

Steps to Reproduce:

1. Add the keybinding
```json  
    {
        "key": "ctrl+`",
        "command": "workbench.action.terminal.newWithCwd",
        "when": "editorTextFocus && !editorReadonly",
        "args": {
            "cwd": "${fileDirname}"
        }
    },
```
2. Press \` + `Ctrl` 

![image](https://github.com/microsoft/vscode/assets/400048/4c942b22-6080-4024-80b9-bc85537ebed2)

**Comment by meganrogge** [comment]
does disabling shell integration fix this for you? `terminal.integrated.shellIntegration.enabled`? Also, what's your default profile?

**Comment by Pithikos** [comment]
@meganrogge maybe, but that would change the workflow I already established. 

In any case the issue is only when trying to open the config JSON file of VScode itself. For my workflow (Quake-like terminal) I had to rewrite all my shortcuts and it kind of works now (but no idea what the bug is exactly):

```
    {
        "key": "ctrl+`",
        "command":"workbench.action.terminal.newWithCwd",
        "when": "editorTextFocus",
        "args": {
            "cwd": "${fileDirname}"
        }
    },
    {
        "key": "ctrl+`",
        "command": "workbench.action.terminal.killAll",
        "when": "!editorTextFocus",
    },
    ```
