### ISSUE TITLE
Curly brackets in 'Search in files' / 'files to include' field does not work as intended ?

### ISSUE THREAD

**Issue by as-it** [microsoft/vscode#212428]
- VS Code Version: 1.89.1
- OS Version: Win10 22h2 x64

Steps to Reproduce:

1. I have two folders in D:\data : next, other
2. both folders have same two files, named: C_P101F01.log, P101F01.txt
3. all four files contain string: 5C4266900201
4. in VS Code I open folder: D:\data
5. I try to search '5C4266900201' in 'Search in files' (Ctrl+Shift+F) ... all files are listed (that is OK):
<img width="242" alt="image" src="https://github.com/microsoft/vscode/assets/23263469/757446c0-f40c-4d48-b0ed-2e716468f04f">

6. now I try to put this '{next, other}/{*.txt, *.log}' in 'files to include' field ... the results should be the same, right? ... but no ... only first file in first folder is listed:
<img width="240" alt="image" src="https://github.com/microsoft/vscode/assets/23263469/4d33ddf1-c90d-47c0-96ec-fd595d57f249">

**Comment by RedCMD** [comment]
you have a space after the comma `, `
spaces are not whitespace
they are included in the path name

**Comment by as-it** [comment]
Ok, I did not know that. 
Maybe it should be mentioned (more) in docs.
Thank you
