### ISSUE TITLE
I have upgraded TypeScript to 2.2.1, but the TypeScript service still crashes

### ISSUE THREAD

**Issue by semmy2010** [Microsoft/vscode#21248]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.13.2|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.6|
|vscode-html-css|ecmel|0.0.33|
|auto-rename-tag|formulahendry|0.0.11|
|vue-snippets|hollowtree|0.1.0|
|beautify|HookyQR|0.8.1|
|sky-react-create-snippet|lulinmemeda|0.0.3|
|vscode-icons|robertohuertasm|7.2.0|
|vue|seanwash|0.4.2|
|guides|spywhere|0.6.1|
|react-beautify|taichi|0.3.0|
|vscode-react-native|vsmobile|0.3.1|

---

![aba158d6-f433-11e6-9951-190d8eb79bcb](https://cloud.githubusercontent.com/assets/4402907/23247079/e7aad7cc-f9d2-11e6-8e22-c43a473405c7.png)

**I have upgraded the TypeScript to 2.2.1, but still have this bug**

**Comment by Rwing** [comment]
maybe you'd better upgrade vscode to 1.10.0-insiders

**Comment by mjbvz** [comment]
@semmy2010 Do you see a message about a missing `typescript/...` file? Some antivirus program has also been deleting our TypeScript implementation files which can trigger this error

**Comment by semmy2010** [comment]
@mjbvz I did not see the file with missing typescript/ ...

**Comment by semmy2010** [comment]
@mjbvz I used the command line to upgrade the Typescript "npm update -g typescript" The current TypeScript version is 2.2.1 
![11111](https://cloud.githubusercontent.com/assets/4402907/23337935/3c05c04a-fc38-11e6-8073-9aaf46f72813.png)

**Comment by semmy2010** [comment]
@Rwing Where to download the latest version of VSC, I see the latest version of the official only 1.9.1

**Comment by Rwing** [comment]
@semmy2010 http://code.visualstudio.com/insiders

**Comment by mjbvz** [comment]
VSCode 1.10 is now out. Let me know if you are still hitting this. Also, please check that 360 antivirus is not deleting vscode's bundled tsserver.js file

Thanks

**Comment by Rwing** [comment]
lol 360 antivirus 🤣
