### ISSUE TITLE
VS Code console.log is no effect

### ISSUE THREAD

**Issue by eric-love** [Microsoft/vscode#21240]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 15.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|nativescript|Telerik|0.6.1|
|ReactSnippetsStandard|TimonVS|1.0.3|
|jsx|TwentyChung|0.0.1|
|html-snippets|abusaidm|0.1.0|
|react-toolbox-snippets|alechp|0.12.0|
|vscode-standard-format|chenxsan|0.0.12|
|cjsx|crisward|0.0.6|
|vscode-console-wrapper|fabiodam|0.4.0|
|rest-client|humao|0.12.3|
|javascript-unit-test-snippet|iZDT|1.0.0|
|cpptools|ms-vscode|0.10.1|
|nativescript-xml-snippets|tsvetan-ganev|1.0.4|
|vscode-react-native|vsmobile|0.3.1|
|debug|webfreak|0.17.0|
|vscode-js-console-utils|whtouche|0.7.0|
|nativescript-ng2-snippets|wwwalkerrun|1.2.0|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|

---

Steps to Reproduce:

1.open vs code,run react-native
2.console.log no effect

**Comment by roblourens** [comment]
Can you give any more details? Are you using `console.log` or `process.stdout.write`?

**Comment by kaiwood** [comment]
@eric-love The react-native extension doesn't log to the output pane, if this is what you are struggling with. In fact, react-native itself doesn't do this either. 

But you can simply start a new integrated terminal and type `react-native logs` to see the console output of the simulator.

**Comment by weinand** [comment]
Please create an issue against the react-native extension.
