### ISSUE TITLE
Quickpick items search reveals octicons used in the items

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#21243]
- VSCode Version: `1.10.0-insider` 256d76fed7947e7289f921df10658d7a69233b65
- OS Version: macOS Sierra `10.12.3 (16D32)`

Steps to Reproduce:

1. Open a quick pick menu that uses the built in octicons in the items
![quickpick-before](https://cloud.githubusercontent.com/assets/641685/23244633/bafa221a-f954-11e6-8132-c39db9d35b09.png)

2. Type a character that is in the octicon name
![quickpick-after](https://cloud.githubusercontent.com/assets/641685/23244635/bcabe9b8-f954-11e6-91be-de414ad6207c.png)

3. Octicons get revealed as text

**Comment by eamodio** [comment]
It also looks like the octicon text also shows up in the hover tooltips (title attr)

**Comment by eamodio** [comment]
Any chance to get this on the list for the June (or soon) iteration? This does seem to cause confusion for users as they have no idea what that text that all of a sudden appears is.

**Comment by jens1o** [comment]
Maybe a code position where we could dig in?

**Comment by bpasero** [comment]
The picker is opened from here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L219

**Comment by jens1o** [comment]
Thanks, I'll take a look, but I was never that deep in the code. :/

**Comment by bpasero** [comment]
@eamodio maybe you check the fix out on master with GitLens since you are a heavy customer.

**Comment by eamodio** [comment]
Will do - thanks!

**Comment by eamodio** [comment]
@bpasero I just checked out master and I don't see any tooltips on quickpick items now.

I did notice another issue (not new though), the tooltip over the input (for the placeholder), shows the wrong content (previous content) if the quickpick is replaced with a new one. 

For example, in GitLens if you open file or branch history in a quickpick and see the tooltip over the input (it should be correct), but then pick one of the commits (which will open a new quickpick), and see that the tooltip over the input it still showing the previous tooltip content, not the updated content. (FYI, this is not new, I can reproduce it in 1.19 too)

**Comment by bpasero** [comment]
@eamodio can you file separate issues for that? To be clear: this issue is resolved for you right?

**Comment by eamodio** [comment]
@bpasero No -- now I don't see any tooltips at all -- I was expecting that the octicons would be stripped, but now there is no tooltip at all.

Will do, re: other issue.

**Comment by eamodio** [comment]
Opened: https://github.com/Microsoft/vscode/issues/43114 for the other issue

**Comment by eamodio** [comment]
Sorry, I was getting mixed up on this. The search part works great now -- octicons don't show up

**Comment by jrieken** [comment]
adding verified label based on @eamodio comment
