### ISSUE TITLE
:; in terminal while installing

### ISSUE THREAD

**Issue by kishor-18** [microsoft/vscode#212418]
![Screenshot (249)](https://github.com/microsoft/vscode/assets/139577020/527334bf-2db7-4da1-92f2-5a1a907a66e4)
Type: <b>Bug</b>

While installing packages or creating react app in terminal when the installation begins the :; this symbol is running instead of [......./] installation and loading is not visible 

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.70GB free)|
|Process Argv|--crash-reporter-id 2679159f-51bb-4fe7-bb33-9308f2bb258a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
airship-react-snippets|air|0.0.8
html-class-suggestions|And|1.2.1
codeium|Cod|1.8.36
vscode-markdownlint|Dav|0.55.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.9.1
vscode-html-css|ecm|2.0.9
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
copilot|Git|1.188.0
copilot-chat|Git|0.15.1
autocorrect|hua|2.6.4
vscode-edge-devtools|ms-|2.1.5
sublime-keybindings|ms-|4.1.10
vscode-css-peek|pra|4.4.1
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
indenticator|Sir|0.7.0
vscode-icons|vsc|12.7.0
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvptcf:31043158
fchga941:31038042
pythonprt:31039817
dwnewjupytercf:31039676

```

</details>

**Comment by CoreyMcCoy** [comment]
was this resolved?

**Comment by Tyriar** [comment]
Looks like the app is using braille symbols to show progress, the font you are using does not feature monospace braille and therefore it it leaking into the following cell. This is working as designed from our perspective.

**Comment by CoreyMcCoy** [comment]
I didn't change anything. It just started with the recent update

Corey McCoy

**Comment by Tyriar** [comment]
@CoreyMcCoy it's hard to say what caused it to happen on your end, but it's valid that it's showing up like this as we do not do any special rendering of the braille chars. The fix is to tweak your fontFamily setting.

**Comment by CoreyMcCoy** [comment]
I'll try it. But again "I" didn't change anything. It was working fine
prior to the update. Installing packages before the update worked as it
always had. So it is on your end

Corey McCoy

**Comment by Tyriar** [comment]
@CoreyMcCoy could be in the OS, could be an Electron/Chromium update, could be an extension messing with settings, could be us. Hard to say exactly. It's a waste of time trying to look into this imo since it's literally working as designed, depending on the font setting.
