### ISSUE TITLE
GitHub Copilot Chat Copy/Paste Broken

### ISSUE THREAD

**Issue by AdrianeNS** [microsoft/vscode#212446]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: Windows 11 Home 23H2

**Steps to Reproduce:**

1. Ask GitHub Copilot a question in the Copilot Chat left side bar.
2. Copy a few words from Copilot's response and paste them into a text editor.
3. The entire response Copilot gave is pasted, rather than just the text that was copied.
4. This is **INCREDIBLY** annoying!!!

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/416
