### ISSUE TITLE
plain text dilema

### ISSUE THREAD

**Issue by Eagleknight13** [microsoft/vscode#212481]
Type: <b>Feature Request</b>

hello, i am reaching out to request assistance in a program i am trying to run but i am stopped by a notice the program wont run without a 'plain text" debugger and i have aquired all i can and it is not working so i am looking for advice on what i need or if this can be added.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by gjsjohnmurray** [comment]
It sounds like you haven't told VS Code which language you are coding in. Look at the indicator on the right end of the status bar.
