### ISSUE TITLE
Markdown cannot use 'tab', 'enter' or 'multiple tabs' to produce spaces

### ISSUE THREAD

**Issue by julian62645** [microsoft/vscode#212462]
Type: <b>Bug</b>

> Issue troubleshooting has identified that the issue is with Visual Studio Code. It is confirmed that the issue exists in Visual Studio Code Insiders

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.18363
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.50GB free)|
|Process Argv|--crash-reporter-id ff1e35a4-6391-41f3-933f-3afd4d8b58f4|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31043157
pythonprt:31039817
dwnewjupytercf:31039676

```

</details>

**Comment by julian62645** [comment]
![image](https://github.com/microsoft/vscode/assets/122516112/461387a7-dc96-4315-afd1-face3bcbee26)
![image](https://github.com/microsoft/vscode/assets/122516112/2f077c24-a968-4ae5-b3eb-1f6e8b2a6fbd)

**Comment by julian62645** [comment]
![image](https://github.com/microsoft/vscode/assets/122516112/2232d3b5-9a6c-43bf-8d4c-773284bd2d41)
![image](https://github.com/microsoft/vscode/assets/122516112/e08d299f-cd9f-4871-8c3f-9f19f65ec242)

**Comment by mjbvz** [comment]
I'm not sure what the issue is. To start, please test in [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If you're still seeing the issue, please clearly describe: steps to reproduce the behavior, the expected result, and the actual result
