### ISSUE TITLE
Typing enter doesn't execute command when terminal suggest modal visible

### ISSUE THREAD

**Issue by cpendery** [microsoft/vscode#212450]
Terminal suggest does not execute on typing `enter`, instead it only dismisses the suggest modal

Does this issue occur when all extensions are disabled?: Yes

Version: 1.90.0-insider (user setup)
Commit: 60468916e48fe8293e7641f0fc4ada80d79117b3
Date: 2024-05-08T05:51:16.876Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Open powershell with `"terminal.integrated.shellIntegration.suggestEnabled": true`
2. Type `ls`
3. Hit enter and see the command not executed, but the terminal suggest modal hides

**Comment by Tyriar** [comment]
Current state is enter will pass through to shell unless `runOnEnter` is configured.
