### ISSUE TITLE
Run without debugging hotkey shouldnt have a dropdown

### ISSUE THREAD

**Issue by CanProjects** [microsoft/vscode#212492]
Type: <b>Feature Request</b>

If i am pressing run without debugging, just run using my default python debugger rather than asking me to select from one of one debuggers.

![image](https://github.com/microsoft/vscode/assets/110444153/7e84363a-9118-43b1-9e22-4bcc5a791b91)

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by roblourens** [comment]
I'm going to fold this into https://github.com/microsoft/vscode/issues/150663 which is about this experience with no launch.json in general, there are several improvements that can be made.

You might want to create a launch.json file to avoid this. https://code.visualstudio.com/docs/python/debugging
