### ISSUE TITLE
The multi-level parent-child project of Maven prompts that the dependent project cannot be found.

### ISSUE THREAD

**Issue by lang2hong** [microsoft/vscode#212419]
![image](https://github.com/microsoft/vscode/assets/5197473/e705bc6a-a87d-4b4b-a212-1e8bf830751c)

**Comment by lang2hong** [comment]
![image](https://github.com/microsoft/vscode/assets/5197473/a3f58c7f-75d6-4af5-b561-f4078cef634e)

**Comment by dbaeumer** [comment]
This looks like a Java problem. Can you please report the issue here: https://github.com/redhat-developer/vscode-java
