### ISSUE TITLE
Need for notebook pre-execute handler

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/vscode#212427]
Related: #212051

With the Python REPL IW experiment, Python extension needs access to text inside user's text input box in IW in order to determine whether they have typed complete or incomplete Python command. I assume this will be part of notebook API. 

This needs to handle before the already existing execute-handler since by the time execute-handler is called is too late in a way that the cell output is already attached to the UI. We need to be able to access user's command before execute handler is called.

**Comment by anthonykim1** [comment]
Additional idea: We could have "change event" which would get triggered every time user would type text in the text input box. This would allow Python extension to detect whether enter was typed in empty line or with text. If empty line, we can trigger submit and execute for the IW REPL.

**Comment by amunger** [comment]
> If empty line, we can trigger submit and execute for the IW REPL.

This sounds like a reasonable thing to just implement in core, without needing any extra API or contribution from extensions

**Comment by rebornix** [comment]
> With the Python REPL IW experiment, Python extension needs access to text inside user's text input box in IW in order to determine whether they have typed complete or incomplete Python command

It's a text document so it's already available in the EH.

> We need to be able to access user's command before execute handler is called

Can you elaborate why do we need to access user's command/code before execution?

**Comment by anthonykim1** [comment]
> It's a text document so it's already available in the EH. 

Right, @amunger have also made me aware of this. We discussed this yesterday but the problem about the text document "onDidChange"? event is how do we know if user is done typing and are ready to run their command. 

We could watch if user has pressed enter on a blank line like @karthiknadig mentioned to me.
- If they have pressed enter on a blank line, we could go ask Python side to tell whether that the commands that were typed are "complete" (able to execute on enter) or "incomplete" (should not execute on enter and wait for further input)

However, I'm bit concerned that relying on constantly fired onDidChange event would be pretty expensive in terms of the number of request and response coming back and forth between Typescript side and Python side when user hasn't done typing their Python command and wants to type more into the text box. Meaning we could end up watching for every non-empty line case of user typing in their characters, which seems like a waste.


The biggest concern and the reasoning behind asking for the "pre-execute" handler is wanting to make sure Python extension can receive latest information on user's Python command before actually running the command and returning the output of it for the purposes of: https://github.com/microsoft/vscode/issues/212051
This is to ensure we can execute on "enter" Once enter is made the basic keybinding for executing commands in IW textbox and smartly determine to wait instead of executing if we can figure out something is incomplete command. 

@amunger I might be missing something so feel free to comment!

**Comment by rebornix** [comment]
> If they have pressed enter on a blank line, we could go ask Python side to tell whether that the commands that were typed are "complete" (able to execute on enter) or "incomplete" (should not execute on enter and wait for further input)

I think this can be a core feature. If the input is empty, enter should not trigger an execution, just like what you get in other inputs, e.g., debug console, find widget, etc.

**Comment by rebornix** [comment]
> This is to ensure we can execute on "enter" Once enter is made the basic keybinding for executing commands in IW textbox and smartly determine to wait instead of executing if we can figure out something is incomplete command.

I would argue why do we prevent users from running the code they type in if they decide to? If we want to warn users about the code being "invalid/incomplete", diagnostics is probably the right way.

**Comment by anthonykim1** [comment]
> I would argue why do we prevent users from running the code they type in if they decide to? 

We are not necessarily preventing users from running the code, but rather waiting just like Python interactive interpreter provided by Python itself.

I think the goal for the "native" REPL regardless of which UI shape of form that it takes, we should make sure the behavior of the read-evaluate-print-loop to be consistent to one provided by Python itself.

For example, when I trigger Python REPL from the terminal (via Python, or Python3), and then try to start my for loop:
``` for i in range(100)``` and then press ```enter```, the interactive interpreter will wait with the ```...``` on the very next line because it knows that I am not done writing my for loop. 
<img width="540" alt="Screenshot 2024-05-14 at 12 46 24 PM" src="https://github.com/microsoft/vscode/assets/62267334/c9c1bb52-e3c0-4dad-9b56-9c704f64e721">

**Comment by amunger** [comment]
Here is my understanding of the options discussed and their drawbacks

- Python extension would watch the input box and update a context key from the keybinding's when clause if the input box has an incomplete input
  - the behavior depends on the update being fast enough
    - e.g. if the ext host is busy, enter would execute, otherwise it would be a newline
- Core would call a preExecute handler (peekExecution?) on the controller to let the extension veto the command
  - Not the typical way for the behavior of a command to be determined
- Rely on static regex contributions for core to check if the line should be executed
  - Wouldn't quite match up with the behavior of a typical REPL since we probably couldn't catch every case

**Comment by anthonykim1** [comment]
No longer needed as should be resolved with: https://github.com/microsoft/vscode-python/pull/23442
