### ISSUE TITLE
In VSCode, when inputting Chinese punctuation, the previously entered text is automatically deleted.

### ISSUE THREAD

**Issue by YWtheGod** [microsoft/vscode#212561]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.89.1
- OS Version: WIN11 23H2

https://github.com/microsoft/vscode/assets/41936459/f7924b4f-060c-4f6a-8920-f9b077163444

Steps to Reproduce:

1. Within any file's editor in VSCode, input any Chinese content containing punctuation marks.
2. Observe the input content being corrupted due to the bug.

**Comment by xiyaowong** [comment]
用了什么跟输入有关的扩展？没正确处理好vscode的内部命令type和replacePreviousChar就会有这个问题

**Comment by YWtheGod** [comment]
Indeed, I didn't consider that it might be an issue with the extensions. Here are the ones I have installed:
```
alefragnani.pascal
alefragnani.project-manager
andyyaldoo.vscode-json
anhuizhuojiantechnology.iflycode
batisteo.vscode-django
chrischinchilla.vscode-pandoc
codeium.codeium
codezombiech.gitignore
donjayamanne.git-extension-pack
donjayamanne.githistory
donjayamanne.python-environment-manager
donjayamanne.python-extension-pack
drmerfy.overtype
eamodio.gitlens
fantasy.markdown-all-in-one-for-web
fougas.msys2
franneck94.c-cpp-runner
hbybyyang.gitee-vscode-plugin
huggingface.huggingface-vscode
janschulte.site-to-markdown
kevinrose.vsc-python-indent
kudsu.imgtogitee
luquedaniel.languague-renpy
mechatroner.rainbow-csv
mintlify.document
ms-ceintl.vscode-language-pack-zh-hans
ms-python.black-formatter
ms-python.debugpy
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-powertoys
ms-toolsai.vscode-jupyter-slideshow
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.hexeditor
ms-vscode.makefile-tools
ms-vscode.powershell
njpwerner.autodocstring
pdconsec.vscode-print
rust-lang.rust-analyzer
serayuzgur.crates
shd101wyy.markdown-preview-enhanced
swellaby.rust-pack
tamasfe.even-better-toml
twxs.cmake
vadimcn.vscode-lldb
visualstudioexptteam.intellicode-api-usage-examples
visualstudioexptteam.vscodeintellicode
wholroyd.jinja
xaver.clang-format
yzane.markdown-pdf
yzhang.markdown-all-in-one
ziyasal.vscode-open-in-github
```

**Comment by YWtheGod** [comment]
I tested a completely fresh installation without any plugins, and indeed, I didn't encounter the issue with incorrect punctuation input. However, in the old installation, I disabled the suspicious Codeium AI plugin and Renpy plugin, but that didn't solve the problem. The remaining plugins are quite popular; I'll test them one by one.

**Comment by YWtheGod** [comment]
The extension "Overtype" cause the problem.

**Comment by xiyaowong** [comment]
@YWtheGod  This extension overrides the built-in `type` command, but it does not override the `replacePreviousChar` command.

https://github.com/DrMerfy/vscode-overtype/blob/62eb52e173b43d7d038843cea5526aafff7b2e39/src/extension.ts#L17

This is not an issue with VSCode.
