### ISSUE TITLE
Unable to use alternate font styles on Mac

### ISSUE THREAD

**Issue by swlody** [microsoft/vscode#212511]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0-insider
- Commit: 26c4a07b47a2bd34480a5e4cba2c2384c590b039
- OS Version: MacOS Sonoma 14.4.1 (Darwin arm64 23.4.0)

Steps to Reproduce:

1. Choose a font family that has multiple styles, for example "Avenir Next" since it is installed by default.
2. Attempt to apply any alternate style by appending the style name to the `editor.fontFamily` setting, e.g. "Avenir Next Ultra Light"

Expected behavior: the editor is displaying using the "Ultra Light" style of the font family "Avenir Next"
What happens: the editor defaults to the fallback font family.

"Avenir Next":
<img width="326" alt="image" src="https://github.com/microsoft/vscode/assets/170795/715ba457-6021-4533-8207-9f3aa932194d">

"Avenir Next Ultra Light":
<img width="500" alt="image" src="https://github.com/microsoft/vscode/assets/170795/caedf649-3288-47b1-a308-8b9ac586fbf7">

"Menlo" (Default):
<img width="379" alt="image" src="https://github.com/microsoft/vscode/assets/170795/8081942f-75c8-4560-b660-01b68a4c882e">

On stable VS Code this works as expected: 
<img width="418" alt="image" src="https://github.com/microsoft/vscode/assets/170795/49ea58d6-5bd7-4a5c-86f4-a9f657dbf5cf">

**Comment by spahnke** [comment]
Same problem with `'Iosevka Extended'`. This worked the version before this one, so it might be related to the Electron update? Works without the variation; the variation is fine in other applications. Also works in stable.

```
Version: 1.90.0-insider
Commit: 26c4a07b47a2bd34480a5e4cba2c2384c590b039
Date: 2024-05-10T18:24:16.069Z
Electron: 29.3.1
ElectronBuildId: 9464424
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.4.0
```

**Comment by swlody** [comment]
This is now happening on the latest stable release

**Comment by LastMonopoly** [comment]
Same here for Iosevka Extended

**Comment by leademeule** [comment]
Same issue here with PP Neue Montreal Mono on macOS 14.3 on the current release. The 400 font weight now goes to the thin style instead of the book style. Anything above goes to the medium style. This makes everything too thin or too bold.

**Comment by sambecker** [comment]
Seeing same issue on `1.90`, even without granular font configuration.

Setting only `fontFamily` to a custom font used to "just work." Now weights and italics don't apply as expected.

**Comment by deepak1556** [comment]
I will merge this to https://github.com/microsoft/vscode/issues/214390. Please refer to https://github.com/microsoft/vscode/issues/214390#issuecomment-2154822715 for details and workaround.

Sorry for merging this as duplicate, I know that this issue was created earlier but I realized only after tagging the other issue.
