### ISSUE TITLE
Feature: Allow triggering rename suggestions via keyboard

### ISSUE THREAD

**Issue by xiyaowong** [microsoft/vscode#212568]
We have:
- `editor.action.rename`
- `focusNextRenameSuggestion`
- `focusPreviousRenameSuggestion`

It's inconvenient as rename suggestions cannot be triggered using the keyboard.

**Comment by ulugbekna** [comment]
You can just press `tab` and then `enter` -- it should be sufficient?

**Comment by xiyaowong** [comment]
Oh, it works! I rarely use tab to switch widget focus in VS Code. Thanks!
