### ISSUE TITLE
This file will not be displayed in the editor because it is either binary, very large or uses an unsupported text encoding

### ISSUE THREAD

**Issue by wstaelens** [Microsoft/vscode#21253]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

> This file will not be displayed in the editor because it is either binary, very large or uses an unsupported text encoding

I just want to open an XML file of only 75 MB in size...
oh god now I'm forced to open Notepad++ again.

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.5.2|

---

Steps to Reproduce:

1. open an XML file of 75 MB
2. open Notepad++ to fix your problems.

**Comment by roblourens** [comment]
We don't support files that large yet, #16335
