### ISSUE TITLE
i am getting these two extra lines above my output in terminalcan u plz resolve it 

### ISSUE THREAD

**Issue by shard12** [microsoft/vscode#212575]
![hello java - Visual Studio Code 5_13_2024 1_30_14 PM](https://github.com/microsoft/vscode/assets/168275463/6e5339e6-4f26-47db-8d02-2fa081e04d01)
![hello java - Visual Studio Code 5_13_2024 1_30_14 PM_LI](https://github.com/microsoft/vscode/assets/168275463/7f8e0450-eb92-45b7-a225-8505708983c0)
Type: <b>Bug</b>

if i print a statement in java i get a output in terminsl but above that i get two extra lines first line saying ^c then second line blank then third line i get output i dont want those first two lines please help me resolve the issue

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (10.16GB free)|
|Process Argv|--crash-reporter-id cd7809ce-a4fe-4822-97cb-8f3e25a5529d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
java|red|1.30.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.26.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31018789
dsvsc021:30996838
jg8ic977:31013176
dwnewjupytercf:31039676

```

</details>

**Comment by shard12** [comment]
@IllusionMH @justschen please look into this matter

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to check whether one of your extensions is doing this.

**Comment by meganrogge** [comment]
this is coming from an extension. you can verify this by running this command:

![Screenshot 2024-05-13 at 8 15 16 AM](https://github.com/microsoft/vscode/assets/29464607/984d1734-bc57-4c79-aff7-4010914f2183)

**Comment by shard12** [comment]
@meganrogge @gjsjohnmurray still running with same issue 
![Uploading ● hello.java - Visual Studio Code 5_13_2024 8_58_31 PM.png…]()
