### ISSUE TITLE
Screen shaking on viewport change of vscode window

### ISSUE THREAD

**Issue by Hardik242** [microsoft/vscode#212555]
Type: <b>Bug</b>

1. Open vscode in maximise screen
2. click minimize button 
3. start resizing window according to your viewport convenience of the monitor
4. Whole windows sreen starts flickering and shaking, and it becomes hard to work under that conditions. It even becomes so hard to read even a single text written anywhere.

Closing and reopening the vscode also doesn't work.
Only option left is to restart the PC or Disable and ReEnable the windows graphics driver.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.77GB (2.65GB free)|
|Process Argv|--crash-reporter-id f24655fd-7f9d-4853-8013-13d1513aa300|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color-picker|Ant|0.0.4
vscode-tailwindcss|bra|0.10.5
simple-react-snippets|bur|1.2.8
mobileview|cir|0.0.7
js-codeformer|cms|2.6.1
jsrefactor|cms|3.0.1
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.4.4
es7-react-js-snippets|dsz|4.4.3
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.6.0
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
react-component-tree|Hab|1.1.1
live-server|ms-|0.4.13
color-highlight|nau|2.8.0
material-icon-theme|PKi|5.2.0
react-exclusive-auto-importer|Pro|0.0.1
LiveServer|rit|5.7.9
vscode-stylelint|sty|1.4.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31018788
dsvsc021:30996838
f3je6385:31013174
pythoncenvptcf:31043158
pythonprt:31039817
dwnewjupytercf:31039676

```

</details>

**Comment by deepak1556** [comment]
Does the issue repro with latest stable, if so can you try running with `--disable-gpu`
