### ISSUE TITLE
Goto definition feature

### ISSUE THREAD

**Issue by imran48** [Microsoft/vscode#21250]
it wold be nice if you can implement a goto definition feature.

**Comment by roblourens** [comment]
It is implemented out of the box for some languages like JS/TS and is provided by extensions for other languages. In what context do you see it not working?

**Comment by imran48** [comment]
thanks for prompt reply. Is it also implemented for php?

**Comment by kaiwood** [comment]
With this PHP extension installed, yes: https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense

**Comment by imran48** [comment]
thanks
