### ISSUE TITLE
Run time is very high

### ISSUE THREAD

**Issue by Harsshhhi** [microsoft/vscode#212552]
Type: <b>Performance Issue</b>

i am running a 5 line c porgram with only 1 Print and scanf function and vs code taking more than 10 minute to execute it

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12450H (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (10.53GB free)|
|Process Argv|--crash-reporter-id 7c008a6b-197f-4daf-ba54-d782d7e1c596|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    96	 10948	code main
    0	    29	  3884	   crashpad-handler
    3	    94	  6916	window [2] (Issue Reporter)
    0	   139	  8988	extensionHost [1]
    0	    33	 11780	     c:\Users\hk969\.vscode\extensions\ms-vscode.cpptools-1.20.5-win32-x64\bin\cpptools.exe
    0	    10	  5092	       C:\WINDOWS\system32\conhost.exe 0x4
    0	     3	 10572	       "c:\Users\hk969\.vscode\extensions\ms-vscode.cpptools-1.20.5-win32-x64\bin\cpptools.exe"
    0	    18	 13668	         c:\Users\hk969\.vscode\extensions\ms-vscode.cpptools-1.20.5-win32-x64/bin/cpptools-srv.exe 11780 {0A6F1BC8-5B43-439C-BDFC-2AE0B98A2107}
    0	    10	 12308	           C:\WINDOWS\system32\conhost.exe 0x4
    0	    93	 13868	shared-process
    0	    80	 13916	fileWatcher [1]
    0	   208	 14416	   gpu-process
    0	   204	 15056	window [1] (insex.c - C_prog - CW - Visual Studio Code)
    0	    42	 16312	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (insex.c - C_prog - CW - Visual Studio Code)
|    Folder (C_prog - CW): 3 files
|      File types: c(1) exe(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.2
cmake-tools|ms-|1.17.17
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31018788
dsvsc021:30996838
945dj816:31013170
a69g1124:31038041
dwnewjupytercf:31039676

```

</details>

**Comment by roblourens** [comment]
vscode doesn't run your code. If this is an issue using the debug extension, please file an issue on the repo for the extension
