### ISSUE TITLE
unable to delete extension because it reinstalls

### ISSUE THREAD

**Issue by Tureluurtje** [microsoft/vscode#212509]
Does this issue occur when all extensions are disabled?: Yes/No
No

- VS Code Version: 1.89.1 (user setup)
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. click the uninstall button at the marketplace extensions
2. it uninstalls
3. click on the button reload extensions(shows up when uninstalled the extension)
4. see it installed again

This is for all of my extensions i saw in another post that it maybe had something to do with the python extension i have that installed but i do not know.
For this example i used the Tabnine extension

**Comment by an-dr** [comment]
Same here. It started to happen when I decide to clean up my set-up. I deleted ~80 extensions, they returned in an hour. I did the same two days ago, and today they are back again! Super annoying

**Comment by krystanRamcharan** [comment]
I replicated this issue and this was how I solved this:

1. Uninstall extension.
2. Restart the extension
3. Restart VScode. 

The extension should become unlisted once you do this.

**Comment by an-dr** [comment]
For me it happened after 2 days during which I was closing vscode many times. They were unlisted they just appeared all at once (all 80) once I open it. I didn't see them installing, so I guess, they were not uninstalled from the machine, but just hidden

**Comment by krystanRamcharan** [comment]
Im unsure if it made the difference but I also made a point to select the option to "ignore recommendations" once I uninstalled it. I will monitor if the ones I deleted return though.

**Comment by sandy081** [comment]
> click on the button reload extensions(shows up when uninstalled the extension)

You should be seeing **Restart Extensions** button right? Or are you connected to any remote?

**Comment by krystanRamcharan** [comment]
Yes, but I right click and choose to ignore the recommendation after I
uninstall the extension. I restart vscode after.

**Comment by sandy081** [comment]
> Yes, but I right click and choose to ignore the recommendation after I uninstall the extension.

How is it related to uninstalling the extension. Can you please share a gif/video of what you mean and what you are expecting?

**Comment by Tureluurtje** [comment]
For me it's the moment the extensions refresh, the extension is already back

**Comment by Tureluurtje** [comment]
I looked a bit on the web and i found out it maybe has to do with the python extension(if installed), or the account sync with multiple computers

**Comment by Tureluurtje** [comment]
But i do not think that is the answer
