### ISSUE TITLE
search.exclude to include subfolder from files.exclude

### ISSUE THREAD

**Issue by Thaina** [microsoft/vscode#212502]
In the project that contain submodule folder like node and unity (contain `node_module` and `Library` respectively) there would always exclude those module in from the file listing in vscode.

But it was very beneficial to sometimes search to files and token from some of those module subfolder. Which I have tried by adding `"search.exclude" : { "Library/PackageCache/**" : false }` to the settings.json

```json
{

    "files.exclude":
    {
        "build/":true,
        "Build/":true,
        "library/":true,
        "Library/":true,
        "obj/":true,
        "Obj/":true,
        "ProjectSettings/":true,
        "temp/":true,
        "Temp/":true
    },
    "search.exclude": {
        "Library/PackageCache/**":false,
        "**/*.asset":false,
        "**/*.mat":false,
        "**/*.meta":false,
        "**/*.prefab":false,
        "**/*.unity":false,
    }
}
```

Which actually work for normal files extension (5 below) but didn't work for folder prefix that was directly excluded from `files.exclude`

I don't know internal mechanism of the exclusion logic but is it possible to allow this kind of pattern to work? I mean, when there is subset of glob pattern oppose the superset then it should take precedence

Or, alternatively, are there any way we could specified the pattern so that it could be more fined grain control of inclusion/exclusion of each file?

**Comment by andreamah** [comment]
It's tricky to make many different settings to support ignoring/supporting different patterns. In your case, I *believe* that something like a negative exclude, as discussed here https://github.com/microsoft/vscode/issues/134415. Please contribute to the discussion there.
