### ISSUE TITLE
Console becomes unusable

### ISSUE THREAD

**Issue by calvincaniSA** [microsoft/vscode#212569]
Type: <b>Bug</b>

I run a Docker command docker compose up but then I get an error because of some docker error. The console then becomes unusable and you cannot  type anything in it. Killing it and restarting it does nothing. The same thing happens if there is an error running Python code

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 5.15.0-106-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|15.35GB (8.56GB free)|
|Process Argv|--unity-launch --crash-reporter-id e6213b00-29af-4393-b0b5-afa6336f8700|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
vscode-django|bat|1.15.0
hide-node-modules|chr|1.1.8
emulate|Die|1.6.0
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
go|gol|0.41.4
vs-code-runner|Har|2.0.1
vscode-favorites|how|1.11.0
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
remote-repositories|ms-|0.40.0
material-icon-theme|PKi|5.2.0
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
vue-vscode-snippets|sdr|3.1.1
html5-boilerplate|sid|1.1.1
svg-preview|Sim|2.8.3
lorem-ipsum|Tyr|1.3.1
highlight-matching-tag|vin|0.11.0
volar|Vue|2.0.8
lorem-picsum|Zaf|1.0.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31038041
dvdeprecation:31040881
pythonprt:31039817
dwnewjupytercf:31039676

```

</details>

**Comment by anthonykim1** [comment]
are you able to run this outside of VS Code and see if you are experiencing same problem?
