### ISSUE TITLE
wrong spelling

### ISSUE THREAD

**Issue by lpitsch** [Microsoft/vscode#21259]
- VSCode Version: 1.9.1
- OS Version: 10.12.3

Steps to Reproduce:

1. "Auswahl"
2. "Zeile nach unten koppieren" right would be "Zeile nach unten kopieren"

**Comment by johnliu2016** [comment]
Typo in translation, @lukaschal 

[menus.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fdeu%2Fvscode%2Fsrc%2Fvs%2Fcode%2Felectron-main%2Fmenus.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";miCopyLinesDown" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Co&amp;&amp;py Line Down]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[Zeile nach unten kop&amp;&amp;pieren]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Fixed.
