### ISSUE TITLE
Bash Shell Script Syntax highlight problem after pipe and command with ;

### ISSUE THREAD

**Issue by gullevek** [microsoft/vscode#212572]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.89.1 
- OS Version: 13.6.6 (22G630)

I run a extension Bisect and the problem still exists in each iteration.
I also run VScode with all extensions disabled.

Steps to Reproduce:

1. open vscode
2. select highlight type Shell Script
3. add code as below

```sh
#!/usr/bin/bash

# broken while highlight after pipe
cat $foo |
while read i; do
	# broken done; highlight after output
	echo "output";
done;

# OK
cat $foo |

while read i; do
	echo "output"
done;

# OK
cat $foo | while read i; do
	echo "output";
done

# OK
cat $foo | while read i; do
	echo "output";
	# COMM
done;
```

Note, this happens with other commands like "if" and "for" too where "fi;" and "done;" will be wrong highlighted if the command before has a semicolon ";" at the end

Normal:
<img width="279" alt="Screenshot 2024-05-13 at 15 44 29" src="https://github.com/microsoft/vscode/assets/855861/60277f17-4294-4308-98a0-005cfaf09409">

All extensions disabled:
<img width="792" alt="Screenshot 2024-05-13 at 15 49 30" src="https://github.com/microsoft/vscode/assets/855861/33bb6559-56de-4791-a665-429890854bbc">

**Comment by RedCMD** [comment]
should report to the upstream grammar repo https://github.com/jeff-hykin/better-shell-syntax

**Comment by alexr00** [comment]
Copied to the upstream repo: https://github.com/jeff-hykin/better-shell-syntax/issues/90
