### ISSUE TITLE
Frame Rate Limiter - Background Application setting in Nvidia Profile Inspector causes sluggish UI performance in VS Code even in the foreground

### ISSUE THREAD

**Issue by jyomu** [microsoft/vscode#212587]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: Windows 11 Pro　23H2　22631.3527

Steps to Reproduce:

1. Open the Nvidia Profile Inspector.
2. Navigate to the Frame Rate Limiter - Background Application setting.
3. Set a low FPS value (e.g., 5 FPS).
4. Open VS Code.
5. Observe sluggish UI performance when scrolling or typing, even when VS Code is in the foreground. The background application setting is being applied to the foreground application.

**Comment by RedCMD** [comment]
thank you soo much

Can confirm
I've had the limit set to 20fps for ages
wondered why VSCode always felt slow

**Comment by darkpivot** [comment]
Maybe this is related, but I had the same issue, and also noticed that smooth scrolling only works when the app is not in focus. (e.g. I click into another window, and then hover my cursor over vscode and scroll, it will be smooth. However, if I click into vscode and then try scrolling again, the scrolling is no longer smooth.)
