### ISSUE TITLE
Add Opacity-Setting to Minimap

### ISSUE THREAD

**Issue by Platzer** [Microsoft/vscode#21255]
There is no visual difference between the editor background and the minimap background. If you've one single long line in your code (and we all have those 80+ char lines :stuck_out_tongue_winking_eye:) the minimap cuts of the last characters and you don't realy realise it. 
### Minimap On:
![grafik](https://cloud.githubusercontent.com/assets/3358663/23249323/03cba456-f9a4-11e6-84db-4236456c94c0.png)
### Minimap Off:
![grafik](https://cloud.githubusercontent.com/assets/3358663/23249337/1eb48f94-f9a4-11e6-9263-18142454404d.png)

I suggest a `editor.minimap.opacity` User Settings to add CSS Opacity to the Minimap.
### Minimap with Opacity `0.6`:
![grafik](https://cloud.githubusercontent.com/assets/3358663/23249421/951fb03c-f9a4-11e6-8153-332b55169808.png)

**Comment by Platzer** [comment]
Possible dublicate / solution for #21229?

**Comment by xttn** [comment]
Sorry, i using VSCode ver 1.9.1
how to enable Minimap ?

**Comment by Platzer** [comment]
Got to User Settings and add `"editor.minimap.enabled": true`.

**Comment by roblourens** [comment]
Yeah I think it is covered by #21229

**Comment by xttn** [comment]
Yes, it not ok, why?
![not working](http://i.imgur.com/clfJ3Yo.gif)

**Comment by roblourens** [comment]
It was only fixed a few hours ago, it will be in tomorrow's Insiders build.

**Comment by luncht1me** [comment]
This isn't fixed. Latest insider build and minimap is still cutting off my view. Opacity when not hovered would be nice, and possibly variable height.
