### ISSUE TITLE
Python debug can't connect

### ISSUE THREAD

**Issue by rmetcalfe-msp** [microsoft/vscode#212598]
Type: <b>Bug</b>

After downloading VSCode Insiders to get the fix for https://github.com/microsoft/vscode/issues/209341, the debug behaviour appears to be even worse as I cannot not debug anything. 

Trying to debug a Python application gives me the 'Timed out waiting for launcher to connect' error each time.
```
launch.json
        {
            "name": "Python Debugger: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${workspaceFolder}/main.py",
            "console": "integratedTerminal"
        },
```
Bash debug console output
```
[.venv] AzureAD+ReeceMetcalfe@MSP-D3VCRV3:C:/Users/ReeceMetcalfe/AppData/Local/Programs/Microsoft VS Code Insiders (257-modify-process-to-act-on-database-directly-instead-of-files) 
$  /usr/bin/env c:\\Users\\ReeceMetcalfe\\GitHub\\msp_security_group\\.venv\\Scripts\\python.exe c:\\Users\\ReeceMetcalfe\\.vscode-insiders\\extensions\\ms-python.debugpy-2024.6.0-win32-x64\\bundled\\libs\\debugpy\\adapter/../..\\debugpy\\launcher 55169 -- C:\\Users\\ReeceMetcalfe\\GitHub\\msp_security_group/main.py 
Traceback (most recent call last):
  File "C:\Users\ReeceMetcalfe\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ReeceMetcalfe\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\ReeceMetcalfe\.vscode-insiders\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\launcher\__main__.py", line 91, in <module>
    main()
  File "c:\Users\ReeceMetcalfe\.vscode-insiders\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\launcher\__main__.py", line 47, in main
    launcher.connect(host, port)
  File "c:\Users\ReeceMetcalfe\.vscode-insiders\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\launcher/../..\debugpy\launcher\__init__.py", line 27, in connect
    sock.connect((host, port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```
VS Code version: Code - Insiders 1.90.0-insider (00bc1553bafe83896a96e1b2572024083d14515a, 2024-05-07T05:51:16.352Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900H (20 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.68GB (39.78GB free)|
|Process Argv|--crash-reporter-id 2a92c933-9460-4174-89c4-a0f8e9941b7a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.190.872
copilot-chat|Git|0.16.2024051301
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
showvideot:31016890
chatpanelt:31014475
jg8ic977:31013176
a69g1124:31018687
dvdeprecationcf:31036533
pythonprt:31036556
dwnewjupyter:31039675

```

</details>

**Comment by tfriedel** [comment]
same problem here. Got a "Timed out waiting for launcher to connect" message when trying to debug remotely. This was working fine just a few days ago on vscode insiders. I am now forced to switch to the regular, non-insiders build.

**Comment by roblourens** [comment]
Please file on the repo for the Python debug extension, thanks

**Comment by mikezang** [comment]
Does anyone help me to solve this problem? I can't debug after upgraded to v1.90.0...
