### ISSUE TITLE
Enable dynamic chat variables in the inline chat

### ISSUE THREAD

**Issue by abner-math** [microsoft/vscode#212578]
Chat variables were introduced to the [ChatParticipant API](https://github.com/microsoft/vscode/blob/2ba77dae520eb7c38746631383e7ba047948a3c4/src/vscode-dts/vscode.proposed.chatParticipant.d.ts#L36) with some interesting built-in dynamic variables, in special [#file](https://github.com/microsoft/vscode/blob/2ba77dae520eb7c38746631383e7ba047948a3c4/src/vs/workbench/contrib/chat/browser/contrib/chatDynamicVariables.ts#L202). See screenshot below:
![Screenshot from 2024-05-13 10-21-21](https://github.com/microsoft/vscode/assets/5346170/2971b710-ff65-4ea1-976f-237b9fb9e61f)

Unfortunately, dynamic variables such as #file are not available in the inline chat (CMD + I).
![Screenshot from 2024-05-13 10-23-48](https://github.com/microsoft/vscode/assets/5346170/32d52da3-ad1f-47d7-8142-988353e99156)

Would it be possible to create some parity between chat and inline chat, such as all dynamic variables available in the chat are also available in the inline chat?

**Comment by Rainmen-xia** [comment]
Inline chat can only be use by github copiot？
