### ISSUE TITLE
Markdown previewing tab not binding to the specific file when multiple .md files are in different subfolders

### ISSUE THREAD

**Issue by Seeker98** [microsoft/vscode#212586]
Does this issue occur when all extensions are disabled?: Yes

版本: 1.89.0 (user setup)
提交: b58957e67ee1e712cebf466b995adf4c5307b2bd
日期: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. create a new empty folder, open with code, create a new .md file, (lets say 1.md), write "test" in 1.md and save.
2. create a child folder (let's say child_folder), and create a new file same name to above (1.md) under the child folder, write "test_child" in ./child_folder/1.md and save
3. close all tabs
4. open ./1.md, and ctrl+shift+v to open preview, now the preview window shows "test"
5. open ./child_folder/1.md, and switch to the preview window (which should display the preview of ./1.md), now it shows "test_child". but we assume it to keep showing "test".

This bug (probably?) also reproduces under ubuntu 22.04 with same version and all extensions disabled. If creating more subfolders and more .mds with same name, the preview window always shows content from the last file checked.

this is a visualization of the folder structure and file content.
![image](https://github.com/microsoft/vscode/assets/26476171/5046d74b-1653-4d31-853f-f1c2f5d83f9b)

**Comment by mjbvz** [comment]
This sounds like the expected behavior of the preview. Please see the section of the docs talking about the dynamic preview and preview locking: https://code.visualstudio.com/Docs/languages/markdown#_dynamic-previews-and-preview-locking
