### ISSUE TITLE
Cannot open terminal through ssh connection

### ISSUE THREAD

**Issue by xwang38438** [microsoft/vscode#212535]
Type: <b>Bug</b>

1. Connect to remote ssh
2. open a folder 
3. click terminal + new terminal 
4. nothing reponds

VS Code version: Code - Insiders 1.90.0-insider (26c4a07b47a2bd34480a5e4cba2c2384c590b039, 2024-05-10T18:25:42.483Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.0-105-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (12.20GB free)|
|Process Argv|--crash-reporter-id 62fdc735-8859-448b-b429-b08e2b716358|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.2.191.182|
|OS|Linux x64 5.15.0-105-generic|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 3713)|
|Memory (System)|46.97GB (40.75GB free)|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.365.0
remote-ssh|ms-|0.112.2024050815
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.5.2024031109
open-in-browser|tec|2.0.0
pdf|tom|1.2.2
msft-todo-unofficial|tyl|0.0.18
prettier-vscode|esb|10.4.0
chatgpt-copilot|fei|4.4.1
copilot|Git|1.190.0
copilot-chat|Git|0.16.2024051001
ipython|Hoa|2024.3.0
vscode-docker|ms-|1.29.1
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.6.0
python|ms-|2024.7.11311010
vscode-pylance|ms-|2024.5.100
jupyter|ms-|2024.4.2024042601
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
tensorboard|ms-|2023.10.1002992421
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vswsl492:30256197
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
vscaat:30438846
c4g48928:30535728
vscrp:30624060
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
showvideot:31016890
chatpanelt:31014475
bdiig495:31013172
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupytercf:31039676

```

</details>

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal

**Comment by xwang38438** [comment]
settings.json 

{   
    "liveServer.settings.AdvanceCustomBrowserCmdLine": "Chrome",
    "editor.inlineSuggest.enabled": true,
    "security.workspace.trust.untrustedFiles": "open",
    "files.autoSave": "afterDelay",
    "workbench.editorAssociations": {
        "*.pdf": "default"
    },
    "remote.SSH.remotePlatform": {
        "10.2.191.182": "linux",
        "10.2.191.95": "linux",
        "10.2.191.99": "linux",
        "10.2.191.75": "linux"
    },
    "jupyter.askForKernelRestart": false,
    "git.autofetch": true,
    "open-in-browser.default": "Chrome",
    "liveServer.settings.donotShowInfoMsg": true
}

**Comment by xwang38438** [comment]
I am not sure if this is the correct terminal log: 

2024-05-13 14:53:59.272 [info] Latency measurements for local backend
window<->ptyhost (message port): 0.40ms
window<->ptyhostservice<->ptyhost: 1.00ms
ptyhostservice<->ptyhost: 0.42ms []
2024-05-13 14:54:06.113 [info] Latency measurements for ssh-remote+10.2.191.182 backend
window<->ptyhostservice<->ptyhost: 457.10ms
ptyhostservice<->ptyhost: 0.58ms []
2024-05-13 14:54:06.113 [info] Latency measurements for ssh-remote+10.2.191.182 backend
window<->ptyhostservice<->ptyhost: 456.70ms
ptyhostservice<->ptyhost: 0.51ms []
2024-05-13 14:54:06.113 [info] Latency measurements for ssh-remote+10.2.191.182 backend
window<->ptyhostservice<->ptyhost: 456.70ms
ptyhostservice<->ptyhost: 0.47ms []
2024-05-13 14:54:06.113 [info] Latency measurements for ssh-remote+10.2.191.182 backend
window<->ptyhostservice<->ptyhost: 456.70ms
ptyhostservice<->ptyhost: 0.45ms []
2024-05-13 14:55:13.813 [trace] [6d23137] terminalInstance#ctor (instanceId: 9) [{}]
2024-05-13 14:55:13.847 [debug] [6d23137] Unbinding from mouse events. []
2024-05-13 14:55:13.865 [trace] [6d23137] Webgl was loaded []
2024-05-13 14:55:14.183 [debug] [6d23137] terminalInstance added capability [1]
2024-05-13 14:55:14.184 [trace] [6d23137] Spawning remote agent process [{"terminalId":31}]
2024-05-13 14:55:14.231 [debug] [6d23137] Terminal process ready (shellProcessId: 147043) []
2024-05-13 14:55:14.237 [debug] [6d23137] terminalInstance added capability [3]
2024-05-13 14:55:14.364 [debug] [6d23137] parsing data "]633;P;ContinuationPrompt=> " [[27,93,54,51,51,59,80,59,67,111,110,116,105,110,117,97,116,105,111,110,80,114,111,109,112,116,61,62,32,7]]
2024-05-13 14:55:14.365 [debug] [6d23137] terminalInstance added capability [2]
2024-05-13 14:55:14.610 [debug] [6d23137] Terminal process exit ["instanceId",9,"code",0,"processState",4]
2024-05-13 14:55:14.610 [trace] [6d23137] terminalInstance#dispose (instanceId: 9) []

**Comment by meganrogge** [comment]
thanks for that info, here's the meaning of process state:4 

https://github.com/microsoft/vscode/blob/89b7b824ff5db9106fd3b624c6241c3149361111/src/vs/workbench/contrib/terminal/common/terminal.ts#L316-L318

**Comment by hikariatama** [comment]
Similar issue here, but with zsh crashing on open
Process state 6, exit code 1. Opens fine using plain ssh connection and the executable in error:

![image](https://github.com/microsoft/vscode/assets/36935426/9228560f-02fb-4bea-b916-67fa778392ec)

**Comment by meganrogge** [comment]
does disabling shell integration fix it for you, `terminal.integrated.shellIntegration.enabled`?

**Comment by xwang38438** [comment]
It seems that adding `terminal.integrated.shellIntegration.enabled` in the settings.json works for me. Thank you so much. However, I cannot open the second terminal once I connect to the remote server. I have to delete all terminals, and then everything works fine.
