### ISSUE TITLE
Repl arrow in input not vertically centered

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2125]
@isidorn fyi as shown during standup. maybe the line-height is missing on the element containing the icon?

**Comment by joaomoreno** [comment]
Now it is not vertically centered in macOS:

![image](https://cloud.githubusercontent.com/assets/22350/19799644/05dd74f8-9cf8-11e6-81f6-b582b02bcdf7.png)

**Comment by isidorn** [comment]
DUp of https://github.com/Microsoft/vscode/issues/14429

**Comment by joaomoreno** [comment]
Actually, let's move it to #14649.
