### ISSUE TITLE
HTML formatting problem

### ISSUE THREAD

**Issue by King66** [Microsoft/vscode#21257]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393

after format (alt+shift+f):
![temp1](https://cloud.githubusercontent.com/assets/11925432/23251704/41e5a94a-f9e9-11e6-89aa-a74526890bd6.jpg)
![temp2](https://cloud.githubusercontent.com/assets/11925432/23251711/45573c06-f9e9-11e6-8ab0-501085518c3b.jpg)

[htmlfile.zip](https://github.com/Microsoft/vscode/files/795968/htmlfile.zip)

**Comment by aeschli** [comment]
We're using the [jsbeautifier](http://jsbeautifier.org/) formatter.
Please file issues directly there.

Note that the formatter has a list of tags that are not formatted. The anchor tag (<a>) is one of theme. You can change this by the setting "html.format.unformatted"
