### ISSUE TITLE
Keep Side Bar position per window

### ISSUE THREAD

**Issue by nohmad** [Microsoft/vscode#21254]
- VSCode Version: 1.9.1
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. View - Move Side Bar Right
2. Open new window, name it `window:2`
3. View - Move Side Bar Left on `window:2`
4. Position of Side Bar on the first window changed by step 3.

`Toggle Side Bar` action does work per window as I favor, and I think most of people would expect so.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
