### ISSUE TITLE
hover Widget allowed tags support svg

### ISSUE THREAD

**Issue by OceanBelongsToMe** [microsoft/vscode#212565]
allowed_tags: Some(["ul", "li", "p", "code", "blockquote", "ol", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "em", "pre", "table", "thead", "tbody", "tr", "th", "td", "div", "del", "a", "strong", "br", "img", "span"]) })

Can svg be supported so that events in svg can be triggered?

**Comment by aiday-mar** [comment]
Currently the provideHover method returns MarkdownStrings. I am unsure if SVG is supported within the markdown strings, I suppose yes, pinging @mjbvz about that. 

You mean you would like to detect interactions with the SVG within the rendered Markdown?

**Comment by OceanBelongsToMe** [comment]
> Currently the provideHover method returns MarkdownStrings. I am unsure if SVG is supported within the markdown strings, I suppose yes, pinging @mjbvz about that.
> 
> You mean you would like to detect interactions with the SVG within the rendered Markdown?

Yes, just like the 'markdown.showPreview' command, it will directly render the content within SVG tags, and it retains the commands within the hrefs (although they seem to be ineffective). Likewise, the markdownString in hover ultimately converts into HTML. If there are SVG tags within it, these are converted to HTML SVG tags, for example, in PlantUML, where corresponding command links can be inserted.

**Comment by mjbvz** [comment]
We intentionally don't support inline svgs due to the extra attack surface they introduce. You can use svg images but these will not be interactive

**Comment by OceanBelongsToMe** [comment]
> We intentionally don't support inline svgs due to the extra attack surface they introduce. You can use svg images but these will not be interactive

@mjbvz What if the command link is restricted to the VSCode format, like command:goto_definition?[{%22pos%22:{%22character%22:6,%22line%22:10},%22shortcut%22:7873,%22u_id%22:416}]?

**Comment by DanTup** [comment]
@mjbvz can you clarify what is/isn't supported here? I can't find any docs but your comment above suggests that only inline SVG is blocked, but images are fine. However they're not working for me (see https://github.com/Dart-Code/Dart-Code/issues/5609) and your comment at https://github.com/microsoft/vscode/issues/133389#issuecomment-928261720 suggests that they are also blocked.

Thanks!

**Comment by mjbvz** [comment]
We restrict external svg images currently, again due to concerns about svgs having a larger attack surface that normal images. However you can use svgs images with data Uris. Here's one that is base64 encoded:

<img width="816" height="244" alt="Image" src="https://github.com/user-attachments/assets/907013ae-4cd4-450d-8cab-c82ff25bfeb2" />

**Comment by DanTup** [comment]
@mjbvz got it, thanks for the clarification!
