### ISSUE TITLE
Custom TreeView search ctrl + F does not work anymore

### ISSUE THREAD

**Issue by BoykaZhu** [microsoft/vscode#212550]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.89.1
- OS Version: Window 10

Steps to Reproduce:

1. Open any extension with custom treeview, for example Gitlens ->Branches view
2. Use Ctrl + F
3. Cannot see the small search popup anymore below,

![image](https://github.com/microsoft/vscode/assets/10293068/89d7864c-cee5-40b1-97de-1931fbc7e628)

I did remember in my extension, this also works in my custom view, I can input some keywords and search the matched item quickly, but now I cannot use that small search anymore.

**Comment by IllusionMH** [comment]
This change was announced in recent update https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding

But you can rebind command to your preference
