### ISSUE TITLE
Improve guidance when attaching through legacy launch config to node > v6.9

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#21256]
Testing #20779

- node v6.9.4 installed
- create a launch config 'Node.js: Attach (Legacy Protocol)'

As expected this doesn't work and I get the error: 
![image](https://cloud.githubusercontent.com/assets/172399/23249897/e2765564-f9a6-11e6-8d35-24d6a383174a.png)

Suggest that when an attach is done using the legacy protocol and the attach fails, then the message mentions that attach should be tried using the 'inspector' protocol.

**Comment by weinand** [comment]
Chnanged message to this:
"Cannot connect to runtime via 'legacy' protocol; consider using 'inspector' protocol (timeout after 10000 ms)."

**Comment by roblourens** [comment]
For node2 this error includes "Ensure Node was launched with --inspect." I think I'll leave it as is, it will get too long if I also mention the legacy protocol. And this is consistent with pushing people towards inspector.
