### ISSUE TITLE
Racist hotkey

### ISSUE THREAD

**Issue by Hundo1018** [microsoft/vscode#212515]
Type: <b>Bug</b>

when I using Quick Fix, and i'm using chinese version, the Quick FIx does not work, and appear other non-sense advice, vice-versa It work on the english.

I'm feel offended by this IDE, if you don't, I will post to  Major media.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1280P (20 x 1997)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (4.07GB free)|
|Process Argv|C:\\Projects\\Tetits C:\\Projects\\Tetits\\assets\\Intents\\Intents.ts --crash-reporter-id 06823d6c-2053-4603-a24a-115b2a82d6db --crash-reporter-id 06823d6c-2053-4603-a24a-115b2a82d6db|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
rust-bundle|1Yi|1.0.0
flutter-snippets|ale|3.0.0
shaderlabvscodefree|aml|1.3.6
cocos-debug|Chu|0.0.1
supersharp|cra|0.1.4
dart-code|Dar|3.88.0
flutter|Dar|3.88.0
emulate|Die|1.6.0
rust-syntax|dus|0.6.1
code-runner|for|0.12.2
copilot|Git|1.190.0
copilot-chat|Git|0.15.1
todo-tree|Gru|0.0.226
prettier-rust|jin|0.1.9
vscode-csharp-snippets|jor|1.1.0
unity-code-snippets|kle|2.4.0
csharpextensions|kre|1.7.3
rust-flash-snippets|lor|3.1.0
vscode-open-in-sourcetree|mor|0.6.0
vscode-docker|ms-|1.29.1
csdevkit|ms-|1.5.20
csharp|ms-|2.28.11
vscode-dotnet-runtime|ms-|2.0.5
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
remote-containers|ms-|0.362.0
remote-wsl|ms-|0.88.2
vscode-typescript-next|ms-|5.5.20240505
tsimporter|pmn|2.0.1
rust-analyzer|rus|0.3.1950
crates|ser|0.6.6
shader|sle|1.1.5
sonarlint-vscode|Son|4.5.1
rust-pack|Swe|0.3.38
even-better-toml|tam|0.19.2
hlsltools|Tim|1.1.303
unity-tools|Tob|1.2.12
vscode-lldb|vad|1.10.0
vscode-todo-highlight|way|1.0.5
cocos-effect|Yaj|0.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31038041
dvdeprecationcf:31040882
dwnewjupytercf:31039676

```

</details>

**Comment by Spongman** [comment]
> I'm feel offended by this IDE

lol

**Comment by russeg** [comment]
wont fix

**Comment by WilliamAnimate** [comment]
> wont fix

Don't fix. Let them post to major media, and we shall watch the world burn
