### ISSUE TITLE
Vscode does not automatically refresh after external file changes

### ISSUE THREAD

**Issue by raodoudou321** [Microsoft/vscode#21252]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-onedark|azemoh|0.4.3|
|path-intellisense|christian-kohler|1.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.0.33|
|text-transform|florianloch|0.1.0|
|beautify|HookyQR|0.8.8|
|docthis|joelday|0.4.0|
|vscode-icon-rotation|krizzdewizz|1.0.3|
|vue|liuji-jim|0.1.5|
|vuehelper|oysun|0.1.0|

---

Steps to Reproduce:

1. I am in the outside editor on the VSCODE to open the file was modified, but VSCODE file does not carry out real-time refresh

**Comment by bpasero** [comment]
@raodoudou321 is this reproducible all the time? is this a file from a workspace you opened or outsie?

**Comment by raodoudou321** [comment]
@bpasero 
All files.
I am using ECLIPSE to modify the file, but VSCODE does not have real-time refresh (using other editors to modify VSCODE and no real-time refresh).

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by raodoudou321** [comment]
@bpasero Hello.
I follow the prompts to catch the following BUG:
1. 
workbench.main.js:138 [FileWatcher] Watcher failed to start after retrying for some time, giving up. Please report this as a bug report!

2.
 [FileWatcher] process error: 

[FileWatcher] process error: 
   
[FileWatcher] process error: 由于 Exception.ToString() 失败，因此无法打印异常字符串。

[FileWatcher] terminated unexpectedly (code: 3762504530, signal: null)

[FileWatcher] is restarted again...

**Comment by bpasero** [comment]
@raodoudou321 awesome, this explains why changes do not show up but does not explain why the watcher does not work. Can you attach a screenshot how this error looks? I am missing some info here.

What kind of workspace are you opening and what is the envrionment (e.g. network share, samba share?)

**Comment by raodoudou321** [comment]
![image](https://cloud.githubusercontent.com/assets/3389198/23293050/c2625b3a-fa9e-11e6-9bb5-3f8a4f25dcb6.png)

![image](https://cloud.githubusercontent.com/assets/3389198/23293067/e3dcf09a-fa9e-11e6-977c-1f4fee7fceec.png)

**Comment by raodoudou321** [comment]
@bpasero
[errorPic.zip](https://github.com/Microsoft/vscode/files/798533/errorPic.zip)

**Comment by bpasero** [comment]
@raodoudou321 can you try to run the file watcher from the command line? It is called `CodeHelper.exe` in `C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\files\node\watcher\win32` and just append the folder you are opening in VS Code as argument to the watcher.

**Comment by CNSKnight** [comment]
I see this commonly on linux versions (currently 1.12.2)

- open script
- git stash apply (overwriting script)
- no change

have seen in console:
```
[IPC Library: Watcher] Error: watch /home/steeve/cfa-tmp/spot-app/.git/index.lock ENOSPC
```

**Comment by bpasero** [comment]
@CNSKnight https://code.visualstudio.com/docs/setup/linux#_error-enospc

**Comment by edwin-hendriks** [comment]
Hi there. I have the same problem while opening a jetty.log file. It apparently seems to be a tricky thing to solve. But, why not simply add a refresh or reload command to VS code. That will help out me and probably others as well.
