### ISSUE TITLE
git how to default show unchanged region

### ISSUE THREAD

**Issue by nsnans** [microsoft/vscode#212649]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 

Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
- OS Version: 

Win11

Steps to Reproduce:

I want to show everything by default but can't find where to open Settings
![image](https://github.com/microsoft/vscode/assets/68949154/b6066dc5-9307-4ea1-8ef9-eb7c26bb70b7)

**Comment by nsnans** [comment]
![image](https://github.com/microsoft/vscode/assets/68949154/8fdbfe33-80d7-4c1f-ba90-8fa4781d36a0)

**Comment by nsnans** [comment]
There was no change to the Settings that appeared after updating the vscode version, but I can't find the closed place in the docs update log

**Comment by hediet** [comment]
Please check this button:

![CbsQ8CcNAx](https://github.com/microsoft/vscode/assets/2931520/a2f6a249-7723-4c26-8171-7a55883b2f51)
