### ISSUE TITLE
chat rendering bug / overlapping text

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#212614]
1. have panel chat open
2. focus the editor
3. move hover focus between the editor and panel chat
4. 🐛 see text rendered over the top of panel chat response
https://github.com/microsoft/vscode/assets/29464607/5abae118-f082-44b9-9341-19c51d680431

**Comment by roblourens** [comment]
I fixed an issue yesterday that probably addresses this. If you still see it, let me know and check for an error in the Window log.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/pull/212732
