### ISSUE TITLE
Creating/Removing cells is broken

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#212600]
Cannot create new cells or remove them (I don't have repro steps; it usually stops working after first time creating a new cell)

https://github.com/microsoft/vscode/assets/16353531/f9c08dd1-d64d-45f0-88c9-e6970b1bb604

Version: 1.90.0-insider
Commit: 29aeab1cbb350107a7bd5962b5e7efe745e0a3ec
Date: 2024-05-13T05:59:57.400Z
Electron: 29.3.1
ElectronBuildId: 9464424
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.4.0

**Comment by amunger** [comment]
repro:

1. create an empty cell in a notebook and execute it
2. create a new code cell, clicking `+ code` or using keybindings a/b
:bug: no new cell is added, existing cell's editor is focused
