### ISSUE TITLE
`workbench.action.openChat.copilot` no longer a shortcut option

### ISSUE THREAD

**Issue by BrennerSpear** [microsoft/vscode#212605]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.89.0 (Universal)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:10:10.196Z (1 wk ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.1.0

`workbench.action.openChat.copilot` is no longer a shortcut option. What happened to ti?

Steps to Reproduce:
Try using the shortcut with the latest GitHub Copilot Chat. It does not work anymore

**Comment by BrennerSpear** [comment]
This was changed to `workbench.action.openChat`, but it was not straightforward  to figure this out

**Comment by BrennerSpear** [comment]
this is now just `workbench.action.openChat`, but it wasn't straightforward to figure that out

**Comment by roblourens** [comment]
Yes, this changed, sorry for the confusion
