### ISSUE TITLE
CodeLens cant display number of references in chinese version

### ISSUE THREAD

**Issue by Rwing** [Microsoft/vscode#21266]
- VSCode Version: 1.10.0-insider
- OS Version: osx and windows 7

![image](https://cloud.githubusercontent.com/assets/497333/23254900/90b20ffe-f9f4-11e6-8e14-6c9cfcfa7b29.png)

![image](https://cloud.githubusercontent.com/assets/497333/23254913/9eb631ca-f9f4-11e6-9895-c6b9e0126a68.png)

**Comment by mjbvz** [comment]
@dbaeumer The translation looks incorrect to me. Both the `1 reference` and `* references` translation use the same string: `引用`

Kai said you may know how to go about requesting an updated translation. Can you please let the translation team know about this issue or let me know what steps to take here?

**Comment by Rwing** [comment]
is there any temp solution ?  I want use it asap...

**Comment by dbaeumer** [comment]
@mjbvz simply assign translation issues to @johnliu2016

**Comment by johnliu2016** [comment]
@dbaeumer, "{0} reference"/"{0} references" are well localized to same translation "{0} 个引用", for months, strange to see the actual behavior on build.

**Comment by mjbvz** [comment]
Thanks for taking a look @johnliu2016. It seems that the latest set of strings fixed this: https://github.com/Microsoft/vscode/commit/f3ec75c594bc6914c97bf613db9389ab2ea3f8c4#diff-d1c4255f6aed379a2211bffba1f60c19
