### ISSUE TITLE
Integrated git bash terminal freezing while running commands, but it was working instant at prev versions

### ISSUE THREAD

**Issue by devhik0** [microsoft/vscode#212692]
Type: <b>Performance Issue</b>

- Open VS Code Insiders latest version on Windows 11
- Open Git bash in integrated terminal
- Run a example command like `ls` and show its delay for response.

VS Code version: Code - Insiders 1.90.0-insider (bbc4ba1eff648ee542972589216f211b7a6a08f2, 2024-05-14T05:48:27.714Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (9.57GB free)|
|Process Argv|--crash-reporter-id 4696966f-1613-4508-bab7-54b015895995|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   105	  8596	code-insiders main
    0	    81	  1396	fileWatcher [1]
    1	   138	  1824	   gpu-process
    0	   148	  1996	extensionHost [1]
    0	    98	  9328	     electron-nodejs (tailwindServer.js )
    0	    90	 11648	     "C:\Users\aydin\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Users\aydin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=1996
    0	   232	  6664	window [1] (TODO.txt - crm-saas - Visual Studio Code - Insiders)
    0	    99	  7972	ptyHost
    0	     6	  4260	     conpty-agent
    0	     5	  8600	     C:\Windows\System32\cmd.exe
    0	     5	 10404	     "C:\Program Files\Git\bin\bash.exe" --init-file "c:\Users\aydin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"
    0	    11	  5036	       "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --init-file "c:\Users\aydin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"
    0	     6	 12820	     conpty-agent
    0	     5	 13852	     C:\Windows\System32\cmd.exe
    0	     6	 14960	     conpty-agent
    3	   100	  9172	window [2] (Issue Reporter)
    0	    36	  9228	   crashpad-handler
    2	    95	 15028	shared-process
    0	    44	 15076	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (TODO.txt - crm-saas - Visual Studio Code - Insiders)
|    Folder (crm-saas): 451 files
|      File types: js(114) json(50) tsx(38) ts(31) html(16) meta(14) rsc(14)
|                  yaml(9) pack(6) css(6)
|      Conf files: package.json(4) tsconfig.json(3) github-actions(2)
|                  dockerfile(2);
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-tailwindcss|bra|0.10.5
nebula-theme|Chi|1.3.3
vscode-eslint|dba|2.4.4
prettier-vscode|esb|10.4.0
dotenv|mik|1.0.1
material-icon-theme|PKi|5.3.0
vscode-yaml|red|1.14.0

</details>

**Comment by meganrogge** [comment]
does disabling shell integration fix this, `terminal.integrated.shellIntegration.enabled`?

**Comment by devhik0** [comment]
Yes it's solved now, thanks again.
