### ISSUE TITLE
VScode editor does not open file in editor after restarting remote connection

### ISSUE THREAD

**Issue by mahesh-attarde** [microsoft/vscode#212622]
Does this issue occur when all extensions are disabled?: Yes 

terminal does not create editor with file on  terminal command "code file.txt"
Recently terminal started caching history from last run. It opens same terminal with history restored
but does not open files from terminal. No extra extensions related to terminal or vscode operation.
May be issue with terminal history update?

Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:
1. Open Vscode with terminal, ssh remote machine, open file from remote with `code file.txt`
2. close editor and vscode completely. 
3. Open VSCode terminal 
4.  type code file.txt

**Comment by Tyriar** [comment]
Can repro:

![Image](https://github.com/user-attachments/assets/fda990db-8b30-49dd-9364-2ea920777023)

I think this falls with how the vscode ipc mechanism links the CLI to windows. @aeschli you own this if I'm not mistaken? If you can't see a way forward with the current APIs I think this is out of scope.

**Comment by aeschli** [comment]
When starting a terminal, we also start a server that opens a socket on a file that listens for commands. The name of the socket file is in an environment variable (`VSCODE_IPC_HOOK_CLI`) . We also put a `code` command in the PATH that connects to that socket.

I just tested that this works with WSL. Also tested with a SSH connection to myself. Also works.

The terminal that you open is a integrated terminal in a remote window, correct?
You can not restore the VSCODE_IPC_HOOK_CLI variable across sessions. It's only valid for one session.
Is the shell starting a different process, e.g. tmux?

**Comment by mahesh-attarde** [comment]
> When starting a terminal, we also start a server that opens a socket on a file that listens for commands. The name of the socket file is in an environment variable (`VSCODE_IPC_HOOK_CLI`) . We also put a `code` command in the PATH that connects to that socket.
> 
> I just tested that this works with WSL. Also tested with a SSH connection to myself. Also works.
> 
> The terminal that you open is a integrated terminal in a remote window, correct? You can not restore the VSCODE_IPC_HOOK_CLI variable across sessions. It's only valid for one session. Is the shell starting a different process, e.g. tmux?

I ran on fresh bare machine, in reconnection , i saw different set of processes spawned at remote. I did not use any tmux or screen etc.
