### ISSUE TITLE
Exception widget: Make the exception text respect the newline characters

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#21268]
Make the exception message text respect the newline characters, so that it can be printed nicely, not in a single row.

**Comment by isidorn** [comment]
@michelkaporin make sure that your PRs containe the fraze: 'fixes #ISSUE_NUMBER' so that this issue gets auto closed when we merge the PR

**Comment by jrieken** [comment]
This is not yet in Insiders, right?

![screen shot 2017-02-24 at 12 12 08](https://cloud.githubusercontent.com/assets/1794099/23301499/8259c6fe-fa8a-11e6-94c1-81d2ff978309.png)

**Comment by isidorn** [comment]
Yes - sorry about that @jrieken, will be tomorrow

**Comment by bpasero** [comment]
Very cool: 

![image](https://cloud.githubusercontent.com/assets/900690/23301991/f4b93282-fa8c-11e6-8234-aa2e9306fbc8.png)

**Comment by bpasero** [comment]
Ok now I want link detection in there ;)

**Comment by isidorn** [comment]
I like this screenshot @michelkaporin feel free to steal it for release notes :D

**Comment by michelkaporin** [comment]
Thank you @bpasero. Just file another feature-request issue for link detection, good idea 👍 

@isidorn will do :)

**Comment by isidorn** [comment]
@michelkaporin I will give you all my link detection bugs which are haunting me for quite some time now 😱
https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20assignee%3Aisidorn%20link%20

**Comment by michelkaporin** [comment]
You are so kind @isidorn, thank you! 😄
