### ISSUE TITLE
i am getting these two extra lines above my output in terminalcan u plz resolve it

### ISSUE THREAD

**Issue by shard12** [microsoft/vscode#212629]
![● hello java - Visual Studio Code 5_13_2024 8_58_31 PM](https://github.com/microsoft/vscode/assets/168275463/37955071-0a57-421d-94a5-5c09497f4f36)

Does this issue occur when all extensions are disabled?: Yes/No ---------- YES

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 
![hello java - Visual Studio Code 5_13_2024 1_30_14 PM](https://github.com/microsoft/vscode/assets/168275463/a8fb79e3-7c2e-4350-8ff9-89e5992099f8)

**Comment by meganrogge** [comment]
those terminals are coming from extensions. pls create issues for those.
