### ISSUE TITLE
"npm scripts" explorer view search/filter shortcut no longer works

### ISSUE THREAD

**Issue by laiprorus** [microsoft/vscode#212699]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
- OS Version: Darwin arm64 23.4.0

Steps to Reproduce:

1. Have a NPM project with scripts open in VSCode.
2. Open "npm scripts" explorer view. This feature is described here https://code.visualstudio.com/docs/getstarted/tips-and-tricks?trk=public_post-text#_run-npm-scripts-as-tasks-from-the-explorer
Usually this is hidden and needs to be enabled in following window:
<img width="522" alt="image" src="https://github.com/microsoft/vscode/assets/33106132/28e9ffb5-d2ce-4e80-9bc5-ce87380f0c6f">

3. Set focus in "npm scripts" explorer view, for example by clicking on a script once.
4. Press command+f to open search/filter window.

**Expected**: 
Search/filter window opens inside "npm scripts" exporer view, scripts can be quickly searched/filtered. Especially useful in projects with large number of npm scripts. This was the behaviour in previous VSCode versions. Here is a screenshot from 1.78.2 (Universal)
<img width="1218" alt="image" src="https://github.com/microsoft/vscode/assets/33106132/bd01bfe5-0a55-4f68-94ef-7455529f613e">

**Actual**: 
Search function for current file opens, which is usually package.json after a script has been selected in "npm scripts" explorer view. There seems to be no other way to open search/filter function for "npm scripts" explorer view. Other ways of navigating and running large number of npm scripts are far less optimal.
<img width="1272" alt="image" src="https://github.com/microsoft/vscode/assets/33106132/e58f0807-8255-4a91-97f1-867c687f45f8">

**Comment by meganrogge** [comment]
@benibenj I believe you were looking into changing the find behavior, correct?

**Comment by IllusionMH** [comment]
This change was announced in recent update https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding

But you can rebind command to your preference
