### ISSUE TITLE
Settings enum descriptions: Don't include enum value

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#21264]
With the fix for https://github.com/Microsoft/vscode/issues/20316, the hover of a property with enumDescriptions now also contains the enum value. It is no longer needed to repeat that value in the description.

![image](https://cloud.githubusercontent.com/assets/6461412/23254465/78e02f32-f9b8-11e6-8e01-b1f821d80742.png)

**Comment by aeschli** [comment]
@bpasero I make a pass over all enumDescriptions and fix them.

**Comment by bpasero** [comment]
@aeschli that is nice, thanks!
