### ISSUE TITLE
Search: no longer possible to open an editor to the side using keyboard

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21260]
When pressing `Ctrl+Enter` on a search result I would like to open it to the side. Ever since we use `revealIfVisible` option, this does not work anymore.

fyi @roblourens @sandy081

**Comment by chrmarti** [comment]
Doesn't do anything when the third editor group has focus. I assume that is expected.

**Comment by bpasero** [comment]
Yes 👍
