### ISSUE TITLE
smartStep/SkipFiles and stopOnEntry=true should stop at first actual source line mapped

### ISSUE THREAD

**Issue by mmc41** [Microsoft/vscode#21261]
- VSCode Version: 1.9.1
- OS Version: OS X

VSCode fails to stop at first mapped line of source code encountered inside a project when smartStep/SkipFiles is specified.

Steps to Reproduce:

1. For a nodejs project, add debug launch task for node/node2 and mocha tests, specify smartStep and/or skipFiles so mocha's own source code is not being debugged and specify stopOnEntry=true as shown in the example launch.json file below:
2. Run debugger
3. Note that the debugger breaks at the wrong place and fail to show an active source file.  

Expected behaviour:
The debugger should break at the first available source file inside the project that is both mapped and is not covered by the skipFiles paths.

**Example launch.json**
```
{
    "version": "0.2.0",
    "configurations": [

        {
            "type": "node2",
            "request": "launch",
            "name": "Mocha Tests",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/mocha",
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/mocha.cmd"
            },
            "runtimeArgs": [
                "-u",
                "bdd",
                "--timeout",
                "999999",
                "--colors",
                "${workspaceRoot}/dist/spec/**/*.spec.js"
            ],
            "internalConsoleOptions": "openOnSessionStart",
            "stopOnEntry": true,
            "smartStep": true,
            "skipFiles": [
			    "${workspaceRoot}/node_modules/**/'.js"
		    ]
        }
    ]
}
```

**Comment by westy92** [comment]
Having this same issue with:
Node.js 8.9.0
vscode: 1.17.2
os: Ubuntu 16.04 x64

**Comment by roblourens** [comment]
Seems to work now?
