### ISSUE TITLE
Can't start new terminal session / watch task are not running correctly

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#212678]
Version: 1.90.0-insider (user setup)
Commit: bbc4ba1eff648ee542972589216f211b7a6a08f2
Date: 2024-05-14T05:48:27.714Z
Electron: 29.3.1
ElectronBuildId: 9464424
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22635

Running VS Code remote WSL

Here is what I see:

https://github.com/microsoft/vscode/assets/1931590/3ee23206-fe7c-4131-a22e-07a8e979cbf8

Observe:

- the terminal does not open
- the watch task somehow hangs. It should print something like:

```
[11:03:24 AM] Starting compilation in watch mode...

[11:03:27 AM] Found 0 errors. Watching for file changes.
```

**Comment by dbaeumer** [comment]
Things work fine under Windows without WSL

**Comment by Soneji** [comment]
Same

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal

**Comment by deepak1556** [comment]
Does setting `export UV_USE_IO_URING=0` in the wsl resolves the issue ?

**Comment by dbaeumer** [comment]
Chatted with @deepak1556 about this and it is very likely caused by the io-uring support that got added with Node 20.x. 

Setting `export UV_USE_IO_URING=0` makes things work again

@aeschli may be we should add this to the WSL launcher for now until we figure out why the terminal is not working with `io_uring`

**Comment by dbaeumer** [comment]
@chrmarti  @roblourens  This also affects docker and very likely ssh.

**Comment by chrmarti** [comment]
To set this environment variable for the entire container as a work around you can add the following to the devcontainer.json:
```json
  "containerEnv": {
    "UV_USE_IO_URING": "0"
  }
```

**Comment by deepak1556** [comment]
FYI on the actual fix, it will be available in the next patch update via https://github.com/electron/electron/pull/42128. However in all the fixes we disable the io_uring backend to get terminal working. I will use this issue to investigate why terminal is broken with this new backend, very likely hints to a bug in node-pty 🤷‍♂️

**Comment by dbaeumer** [comment]
@deepak1556 in case it help I also always saw: https://github.com/microsoft/vscode/issues/212688

**Comment by aeschli** [comment]
@deepak1556 should I make a PR that adds `export UV_USE_IO_URING=0` in  https://github.com/microsoft/vscode/blob/main/resources/server/bin/code-server-linux.sh

**Comment by deepak1556** [comment]
@aeschli yes please

@dbaeumer does https://github.com/microsoft/vscode/issues/212688 repro even with io_uring disabled ?

**Comment by aeschli** [comment]
I think I see similar problems on Linux Desktop (not remote).
The watch tasks are sometimes idling without progress. 
I'm now running code-insiders with `UV_USE_IO_URING=0` to see if that makes a difference

**Comment by olivparm** [comment]
Same issue on Linux Desktop when remoting into another Linux (remote-ssh).

**Comment by dbaeumer** [comment]
@deepak1556 haven't seen it with io_uring disabled.

**Comment by Soneji** [comment]
```bash
➜ tail -n 2 ~/.aliases
# https://github.com/microsoft/vscode/issues/212678
export UV_USE_IO_URING=0
```

After adding the env var (I source this file in my `~/.zshrc`), I'm still getting the error, it's more intermittent now though.
