### ISSUE TITLE
ptyhost causes 100% CPU load

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#212688]
Version: 1.90.0-insider (user setup)
Commit: bbc4ba1eff648ee542972589216f211b7a6a08f2
Date: 2024-05-14T05:48:27.714Z
Electron: 29.3.1
ElectronBuildId: 9464424
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22635

Not sure how to reproduce but the ptyHost quite often goes up to 100% CPU load for me on WSL

![Image](https://github.com/microsoft/vscode/assets/1931590/400f8547-84ca-4a05-8f64-0d6e0c0e6363)

**Comment by eldair** [comment]
Same here, started after latest wsl update

**Comment by eldair** [comment]
@dbaeumer same as yours - 1.90.0-insider

**Comment by PCreamix** [comment]
same problem!

Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

![image](https://github.com/microsoft/vscode/assets/22582289/b58e4451-3d32-4412-b12e-8119030b3a98)

**Comment by Tyriar** [comment]
Not actionable unfortunately. If anyone can figure out how to reproduce this we can look into it.
