### ISSUE TITLE
Search-and-replace in more than one file 

### ISSUE THREAD

**Issue by blusoul** [Microsoft/vscode#21269]
- VSCode Version: 1.9.1 & 1.7.1
- OS Version: win10

Steps to Reproduce:

1. Search-and-replace multiple different content in more than one file
2., use the save all on menu bar ,then all the contents of the file into the same,

**Comment by roblourens** [comment]
I don't understand the problem, what happened after you used "save all"?

**Comment by blusoul** [comment]
oh, sorry. I mean,  after all saved, the contents of all the files become the same. You can try it.

**Comment by blusoul** [comment]
before replace 
![image](https://cloud.githubusercontent.com/assets/8167270/23289203/23f93fa6-fa83-11e6-812e-2191611e9a05.png)
replace 
![image](https://cloud.githubusercontent.com/assets/8167270/23289218/4d4dec12-fa83-11e6-976c-a0f66312c8c9.png)
saved
![image](https://cloud.githubusercontent.com/assets/8167270/23289246/6c8c94e8-fa83-11e6-84d0-c98d6b415b10.png)

**Comment by roblourens** [comment]
That's really weird. What did you use to save all the files?

And what's the encoding of the files?

@sandy081 Any ideas?

**Comment by blusoul** [comment]
The Save All button on the menu bar。
utf-8

**Comment by roblourens** [comment]
If you edit the files by hand (instead of using search/replace), then using Save All, does the same thing happen?

**Comment by blusoul** [comment]
After the replacement is complete, a single file will not save the problem, but save all the files will be a problem.

**Comment by sandy081** [comment]
@blusoul I cannot reproduce it. I followed the steps as you showed with screenshots and used Save All action under File menu. It works with out any issues. I wonder if I miss any thing here?

Do you think you have any extensions that could be causing it? If so disable all extensions and try once.

Thanks

**Comment by blusoul** [comment]
Thanks for your reminder. 
I found the problem caused by an extension.   [JS-CSS-HTML Formatter](https://marketplace.visualstudio.com/items?itemName=lonefy.vscode-JS-CSS-HTML-formatter).
I do not need to use this extension, and uninstall it
Thank You. @sandy081 @roblourens

**Comment by roblourens** [comment]
Glad you figured it out! Please file an issue on them: https://github.com/lonefy/vscode-js-css-html-formatter/issues
