### ISSUE TITLE
打开最近的文件这里，出来的都是文件夹而不是文件。。

### ISSUE THREAD

**Issue by tabooc** [Microsoft/vscode#21267]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|1.3.0|
|jquerysnippets|donjayamanne|0.0.1|
|tortoise-svn|fantasytyx|0.1.1|
|autofilename|JerryHong|0.1.3|
|docthis|joelday|0.4.0|
|format-indent|Kasik96|1.3.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|px-to-rem-with-scss|medzhidov|1.0.1|
|vscode-autoprefixer|mrmlnc|2.0.0|
|view-in-browser|qinjia|0.0.5|
|vscode-open-project|svetlozarangelov|0.0.9|
|react-beautify|taichi|0.3.0|
|jsx|TwentyChung|0.0.1|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by Rwing** [comment]
可能你没有使用vscode直接打开文件，如果是先打开文件夹再在vscode里打开文件，是不会增加到最近的文件里的

**Comment by roblourens** [comment]
Sorry, I don't understand
