### ISSUE TITLE
Make command palette remember the last command

### ISSUE THREAD

**Issue by agauniyal** [Microsoft/vscode#21263]
- VSCode Version: 1.9
- OS Version: Linux

Steps to Reproduce:

1. Press Ctrl + Shift + P to open command palette.
2. Enter some command eg. _Toggle Activity Bar visiblity_
3. Now again open command palette -> last entered command is not remembered.

Sublime text has this very useful feature, would love to see in VSCode too.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by agauniyal** [comment]
Sure 👍

**Comment by Eun** [comment]
#17163
