### ISSUE TITLE
Terminal: inline chat widget is not consistently hidden

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#212672]
For the voice integration to chat, I need to rely on an event when inline chat is hidden. I found that there is a `hide` method:

https://github.com/microsoft/vscode/blob/743d036d66778d17eb1240dcb110d48e3087d324/src/vs/workbench/contrib/terminalContrib/chat/browser/terminalChatWidget.ts#L161

However, I see that it is not being called in these cases:
* open a terminal in panel and start inline chat, start voice chat
* open another panel so that terminal is hidden
* 🐛 voice chat does not stop

A similar issue when terminals are in the editor and you open another editor.

Would it be possible for terminal to ensure `hide` is called in these cases? I have https://github.com/microsoft/vscode/pull/212653 for then stopping the voice chat session, but it needs to be called.

**Comment by bpasero** [comment]
Thanks, but it does not work for me, when `this._focusTracker.onDidBlur` is called, `this._instance.isVisible` is still `true`. I tried this:
* open a terminal, open inline chat
* start recording voice (notice on macOS how a new yellow icon appears in the top right indicating audio recording)
* switch to another panel
* recording does not stop

**Comment by bpasero** [comment]
If I have a chat open in a terminal (panel) and click on another panel, the chat is still not getting hidden, so voice actions continue to work even though not visible.

**Comment by meganrogge** [comment]
That also happens in the chat in the editor, so I was following suit. When I hide the editor by clicking a different one, if there's been a response, the voice actions continue to work even though they're not visible. 

https://github.com/microsoft/vscode/assets/29464607/0f26dbd8-e0ea-4ba5-91c4-898aca52ab30

**Comment by bpasero** [comment]
Yeah fair, as long as the voice stuff can still be turned off from the opened widget.
