### ISSUE TITLE
Visual Studio crashed everytime

### ISSUE THREAD

**Issue by LorenzoCampini** [microsoft/vscode#212694]
Type: <b>Bug</b>

code --crash-reporter-directory <absolute-path>
i cannot find this directory.

my vs code crashed after two minutes i open whichever jupyter notebook

''The window is not responding''

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.66GB free)|
|Process Argv|--crash-reporter-id 440c01b0-92fd-477f-a88e-aa8381a60dc9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31046351
pythonprc:31039816
dwnewjupyter:31046869

```

</details>

**Comment by junaid63** [comment]
![Screenshot 2024-05-14 180229](https://github.com/microsoft/vscode/assets/47031689/2bec13f2-0b96-4ad6-a0d6-13189c9062b6)

I am also facing same issue

**Comment by LorenzoCampini** [comment]
![Screenshot 2024-05-14 000534](https://github.com/microsoft/vscode/assets/125394929/7e321374-2753-43ce-afb4-1b11a71c222d)

**Comment by LorenzoCampini** [comment]
@junaid63 check this page, maybe its helpful.. I hope so, I've been struggling for 2 days on this but no other IDE is as nice as vscode

https://stackoverflow.com/questions/71614897/vscode-crashed-reason-oom-code-536870904?newreg=4fdc029a82804233b48c2f99deecab3d

**Comment by junaid63** [comment]
I think this is the bug in the latest release by vs code. When my vs code is idle I get this issue. But will try your suggestion and will let you know. Thanks for your help 

> @junaid63 check this page, maybe its helpful.. I hope so, I've been struggling for 2 days on this but no other IDE is as nice as vscode. I tried deleting /users//.vscode and it does not work
> 
> https://stackoverflow.com/questions/71614897/vscode-crashed-reason-oom-code-536870904?newreg=4fdc029a82804233b48c2f99deecab3d

**Comment by rzhao271** [comment]
Hi @LorenzoCampini and @junaid63,

Does the issue occur when extensions are disabled? You can reload the window with extensions disabled by pressing Cmd+Shift+P to open the Command Palette and running the "Developer: Reload With Extensions Disabled" command.

If the issue does not occur when extensions are disabled, you can run [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to figure out which extension is causing the issue.

If the issue still occurs when extensions are disabled, could you attach a crash report following the steps at [Creating a Crash Report](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report)?
