### ISSUE TITLE
Double enum name hover

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21277]
testing #20316

* hover over `files.hotExit` looks good
* hover over `files.autoSave` looks bad because it reads: 'onFocusChange: 'onFocusChange: bla'

![feb-23-2017 14-33-58](https://cloud.githubusercontent.com/assets/1794099/23261159/5db4b56c-f9d5-11e6-9c23-8feb439c22ff.gif)

**Comment by aeschli** [comment]
fixed by #21264
