### ISSUE TITLE
Inline chat: response associated with the wrong widget?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#212785]
This maybe related to https://github.com/microsoft/vscode/issues/212780.

For the support for text-to-speech from a response, I rely on `IChatWidgetService.getWidgetBySessionId()` to be able to control the lifecycle of the session in the context of the chat. This works fine in most chat locations, but not in inline and I wonder if its related to inline having 2 modes ("lightweight" and "heavy"). I get back a widget that is not the focused chat widget in the following scenario:

**Steps:**
* open the `Helpful` action [here](https://github.com/microsoft/vscode/blob/c1f1d6aba36bf53ff1074a86546407078f75c3ef/src/vs/workbench/contrib/chat/browser/actions/chatTitleActions.ts#L51) to make some changes to demonstrate the problem
* add this code:
```ts
const chatWidgetService = accessor.get(IChatWidgetService);
const widget = chatWidgetService.getWidgetBySessionId(item.sessionId);
console.log(widget === chatWidgetService.lastFocusedWidget);
```
* open inline chat, get a response and click the `Helpful` action

Notice how the widget returned from `getWidgetBySessionId` is not the same as `lastFocusedWidget`. I think the widget associated with the session ID is still the "lightweight" variant?

![image](https://github.com/microsoft/vscode/assets/900690/1590fa83-4f57-4b1a-960f-7f97c53668c9)

**Comment by bpasero** [comment]
I have a workaround btw:

https://github.com/microsoft/vscode/blob/8693728cc3a010b65ed07a0f74121e88276b6bf2/src/vs/workbench/contrib/chat/electron-sandbox/actions/voiceChatActions.ts#L686-L691

**Comment by jrieken** [comment]
> I rely on IChatWidgetService.getWidgetBySessionId() to be able to 

Don't do that. It is realistic that one model is attached to multiple widgets - that's for inline chat but also for chat editors

**Comment by bpasero** [comment]
I see. Then I will need another way of finding the chat widget for a response. I only have a `ChatResponseViewModel` in hand:

https://github.com/microsoft/vscode/blob/ffb2581f0866e2ec33d2853e593955e3e8535796/src/vs/workbench/contrib/chat/electron-sandbox/actions/voiceChatActions.ts#L841-L847

**Comment by jrieken** [comment]
I believe `chatWidgetService.lastFocusedWidget` is the best way to achieve that. Using the `response` argument is already fishy because it won't be set when users invoke your command from a keybinding.

**Comment by bpasero** [comment]
Yeah I will go with that 👍

**Comment by jrieken** [comment]
closing since this seems to have been fixed
