### ISSUE TITLE
Auto save onEditorFocusLost should only save when focus leaves the editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21273]
Steps to Reproduce:

1. enable `autoSave: onEditorFocusLost`
2. make a file dirty
3. bring up the find widget

=> the editor is saved

We have seen numerous issues doing so (https://github.com/Microsoft/vscode/issues/20989, https://github.com/Microsoft/vscode/issues/16659) so the change is to only trigger auto save when the editor actually looses focus, but not when you click to any other widget within the editor.

**Comment by bpasero** [comment]
To verify:
* [ ] Linux
* [ ] macOS
* [ ] Windows

Enable `autoSave: onEditorFocusLost` and verify:
* dirty editor is not being saved unless mouse moves out of the editor (e.g. does NOT save when opening find widget)
* same works for a dirty diff editor
* also verify having multiple editors open side by side and moving focus between them
* quickly also verify that `autoSave: onWindowChange` works as expected and only saves when focus moves out of the entire window

**Comment by jrieken** [comment]
@bpasero How is this a feature request when you comment on multiple bugs that they duplicate this?

**Comment by bpasero** [comment]
@jrieken I only set this to feature request to have it included in the verification needed queries, but actually it seems that the query ignores feature vs bug, so I am fine changing this to bug.
