### ISSUE TITLE
Update tasks from extension or request vscode to call the provider for task updates

### ISSUE THREAD

**Issue by kenkit** [microsoft/vscode#212746]
So my extension registers itself as a taskprovider.
After vscodes requests the tasks later on I might say like let's change a parameter e.g the working directory of the task. I realize that vscode will not call the provider again to request the tasks, but will instead use the previous tasks the provider gave. How do we go about this ?
It's after debugging that I realized the provider is only called once.

**Comment by meganrogge** [comment]
thanks for the issue. this is working as designed. there is not a plan to change this behavior.

**Comment by kenkit** [comment]
Once tasks are retrieved it's a one way street and you can't update them afterwards ?

**Comment by meganrogge** [comment]
Correct, until the user reloads the window
