### ISSUE TITLE
Extensions not showing

### ISSUE THREAD

**Issue by ihssmaheel-dev** [microsoft/vscode#212768]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.89.1
- OS Version: Windows 11

issue: 
Experiencing issues with extensions. Specifically, I am unable to view both the installed extensions and those available in the marketplace.

Steps to Reproduce:

1. Open Vscode
2. Go to extensions

**Comment by sandy081** [comment]
Can you please share a screenshot of what you are seeing?

**Comment by ihssmaheel-dev** [comment]
![Screenshot 2024-05-15 165405](https://github.com/microsoft/vscode/assets/136784079/7e24842f-8bcf-4bc8-b173-31f4458bc99f)
![Screenshot 2024-05-15 165431](https://github.com/microsoft/vscode/assets/136784079/f6f2f283-5e56-4abe-9a26-13ab057194b6)

It's just loading and I've also double-checked my internet connection.

**Comment by sandy081** [comment]
Can you please share following log

- F1 > Open View... > Shared

**Comment by ihssmaheel-dev** [comment]
Hi Sandeep, 
I appreciate your prompt assistance. After reviewing the shared output, I noticed that there might have been a loading issue or something similar. I couldn't see any of the today's shared logs. However, after restarting my PC, everything seems to be functioning correctly now. Thanks again.
