### ISSUE TITLE
Error and unexpected behaviour when deleting file

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21272]
* run F1 > Configure snippets > pick a language you not yet configured snippets for (this makes it a file outside the workspace if that matters)
* reveal that file in the finder
* delete it from there
* 🐛 an error appears on the console
* the file isn't marked as dirty

![screen shot 2017-02-23 at 14 10 57](https://cloud.githubusercontent.com/assets/1794099/23260428/1511ae4e-f9d2-11e6-8b74-00bd27b5e0a5.png)

![feb-23-2017 14-12-25](https://cloud.githubusercontent.com/assets/1794099/23260441/23bded4a-f9d2-11e6-9151-b37a8ebf9726.gif)

**Comment by bpasero** [comment]
As for keeping the editor open when a file gets deleted there is https://github.com/Microsoft/vscode/issues/11642

No matter how hard I try, I am not able to get rid of that error in the console. It seems to be thrown from the watcher once a file gets deleted while you are watching it and bubbles up as unhandled error I suppose. 

I pushed a change to close the editor when the file gets deleted on disk. That is the behaviour we have for files inside a workspace, so we are consistent now.

**To verify:**
* [ ] Windows
* [ ] Linux
* [ ] macOS

Open files which are out of workspace and verify:
* changes to the file are still updating the editor (try with an editor that does not save atomically, e.g. Sublime by default)
* changes to the file are still updating the editor (try with an editor that has an option to save atomically, e.g. Sublime has a setting for atomic save)
* deleting or renaming the file closes the editor (same behaviour as with files that are inside the workspace)
