### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by ankhiwalasmit** [microsoft/vscode#212797]
Type: <b>Performance Issue</b>

my laptop screen continuoulsy blink when i use vscode. this issue doess not occur outside vscode. please provide a solution for this problem. this issue persists since when i installed vscode on my laptop. this issue always starts whenever i open vscode.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.34GB (1.11GB free)|
|Process Argv|D:\\Training --crash-reporter-id 5f5afc8c-aeb8-4a23-81e3-6266ebd52890|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   107	 13364	code main
    0	   227	  2188	   gpu-process
    0	    42	 10208	   utility-network-service
    0	   293	 11164	window [2] (script.js - weather fetch - Visual Studio Code)
    1	   108	 12240	window [4] (Issue Reporter)
    0	    83	 16976	shared-process
    0	    86	 17056	ptyHost
    0	     7	  2140	     conpty-agent
    0	    90	  5664	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\Hp\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	   178	 17508	extensionHost [2]
    0	    89	  3320	     electron-nodejs (tsserver.js )
    0	   124	  3364	     "C:\Users\Hp\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Hp\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=17508
    0	    89	  4792	     electron-nodejs (server.js )
    0	    80	  4860	     electron-nodejs (languageServer.js )
    0	    82	  6220	     "C:\Users\Hp\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Hp\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=17508
    0	   132	 14936	     electron-nodejs (tsserver.js )
    0	    51	  9640	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	   122	 15404	     "C:\Users\Hp\AppData\Local\Programs\Microsoft VS Code\Code.exe" c:\Users\Hp\.vscode\extensions\angular.ng-template-17.3.2\server --logToConsole --ngProbeLocations "c:\Users\Hp\.vscode\extensions\angular.ng-template-17.3.2,d:\Training\weather fetch" --includeAutomaticOptionalChainCompletions --includeCompletionsWithSnippetText --tsProbeLocations "c:\Users\Hp\.vscode\extensions\angular.ng-template-17.3.2,d:\Training\weather fetch" --node-ipc --clientProcessId=17508
    0	    83	 17644	fileWatcher [2]
    0	    27	 17888	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (script.js - weather fetch - Visual Studio Code)
|    Folder (weather fetch): 1 files
|      File types: js(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|17.3.2
dart-code|Dar|3.88.1
flutter|Dar|3.88.0
code-runner|for|0.12.2
mongodb-vscode|mon|1.6.0
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.100
cmake-tools|ms-|1.17.17
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
java|red|1.31.2024051008
LiveServer|rit|5.7.9
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.26.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
fchga941:31046352
dvdeprecation:31040881
pythonprc:31047982
dwnewjupyter:31046869

```

</details>

**Comment by deepak1556** [comment]
Does the issue repro when gpu acceleration is disabled https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
