### ISSUE TITLE
text color problem

### ISSUE THREAD

**Issue by sunilsinghlko** [microsoft/vscode#212782]
Type: <b>Feature Request</b>

why my text color is not having different text color i have changed themes but its not working even i tried many trick by google still it is not working ,
all the text in my code is only white color even my vscode is not showing me error line 

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by aeschli** [comment]
What is the file name and what is the editor language mode (as seen in the status bar)
Can you add a screenshot?

**Comment by starball5** [comment]
I wonder if dup of #214412

**Comment by aeschli** [comment]
Closing the issue due to lack of more information
