### ISSUE TITLE
Alternative character helper dialog misplaced

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#21274]
1. OS X, editor, hold down a letter key, for instance `a`
2. Notice how the alternative character helper is misplaced - it is always on the top of the editor (in the picture my cursor is on line 179)
3. I would expect it appears next to my character like in sublime

I am hitting this all the time when I am doing my german homework 😊
I believe this is happening due to your accessbility hidden text area, right?

![screen shot 2017-02-23 at 14 22 36](https://cloud.githubusercontent.com/assets/1926584/23260782/c45b1b46-f9d3-11e6-87d3-12072c45db73.png)
![screen shot 2017-02-23 at 14 25 17](https://cloud.githubusercontent.com/assets/1926584/23260812/e9e6011e-f9d3-11e6-9fad-dd4b5fa501c1.png)

**Comment by alexandrudima** [comment]
This has been fixed since a few months.

**Comment by mjbvz** [comment]
Testing with  e059563fb6b8905de79ac4c75be537bb6dc74f5f, the placement is closer but still off. Easiest way to see this is to trigger the popup at the top of the editor which causes it to overlap with the editor contents:

![screen shot 2017-09-27 at 3 44 36 pm](https://user-images.githubusercontent.com/12821956/30941543-de973d0c-a39a-11e7-89bc-8411ba11143a.png)
