### ISSUE TITLE
Debugpy, vscode and pytest : tests not found is waiting_for_client

### ISSUE THREAD

**Issue by sylvainmouquet** [microsoft/vscode#212753]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.89.1
- OS Version: Darwin arm64 23.4.0

Steps to Reproduce:

1. in conftest.py, add debugpy with `debugpy.listen((os.getenv("DEBUG_HOST", "127.0.0.1"), DEBUG_PORT))` and `debugpy.wait_for_client()`
2. in vscode in testing, the tests are not found. pytest `--collect-only` is blocked to the `waiting_for_client`

**Comment by roblourens** [comment]
Please file on the repo for the Python extension, thanks
