### ISSUE TITLE
Can we support CR line endings as well as LF and CRLF? #35797

### ISSUE THREAD

**Issue by fharoon786** [microsoft/vscode#212770]
I'd like to reopen feature request:
"Can we support CR line endings as well as LF and CRLF? #35797"

This feature is already supported by Notepad++ for a long time and missing in VS Code.  If this feature is available, then I'd trash Notepad++.

**Comment by fharoon786** [comment]
I work in digital health.  HL7 messaging standard is the workhorse of electronic data exchange in the clinical domain and arguably the most widely implemented standard for healthcare in the world.

HL7 message require CR or \r EOL sequence.  It's very annoying that this feature is unavailable in VS code when saving the message.

**Comment by Jeff-Birt** [comment]
This is the same request at #211461 which is in the backlog. Can these be combined?
