### ISSUE TITLE
Add a better git diff and merge view to VS Code like IntelJ, Meld or Kaleidoscope

### ISSUE THREAD

**Issue by mathisgauthey** [microsoft/vscode#212736]
Hey there. Just like #93593 and #37350, I'd like to open the discussion about having a better git diff and merge UI.

Here is the current VS Code diff view : 

![diff](https://github.com/microsoft/vscode/assets/46576952/2fe92d59-7bcd-44df-ae9e-39482b28eab1)

And here is the current VS Code 3 way merge : 

![merge-editor-overview](https://github.com/microsoft/vscode/assets/46576952/1d754fcd-b600-4d24-9d19-9df792370d21)

While these are not bad, I am really missing the quality of [IntelJ](https://www.jetbrains.com/help/idea/resolve-conflicts.html), [Meld](https://meldmerge.org/) and [Kaleidoscope's](https://kaleidoscope.app/) take on git diff and merge view. I find it **more intuitive and certainly easier to read and use.**

IntelJ diff view : 

![ij_compareFiles](https://github.com/microsoft/vscode/assets/46576952/18f03d46-759e-4aa6-8e58-69e59fc4f362)

IntelJ merge view : 

![32250860-c677e4ce-bec0-11e7-82b5-0196d981cc28](https://github.com/microsoft/vscode/assets/46576952/a6a92582-9a00-480d-9c3c-cdcf5203ee05)

Meld diff view : 

![filediff](https://github.com/microsoft/vscode/assets/46576952/081e92d8-f593-4368-932d-97e02ae28b32)

Kaleidoscope : 

![image](https://github.com/microsoft/vscode/assets/46576952/93c744d3-8e26-4a41-8e8d-4df723c41bf0)

What do you think ? Would it be possible to implement such a feature ?

There is currently no extension that allow to do this seamlessly in VS Code directly. [SemanticDiff](https://semanticdiff.com/vscode/) is close, but having another tab type makes for overlap with other git extensions that uses VS Code default view.

**Comment by hediet** [comment]
Thanks for the feedback!

> I am really missing the quality of [IntelJ](https://www.jetbrains.com/help/idea/resolve-conflicts.html), [Meld](https://meldmerge.org/) and [Kaleidoscope's](https://kaleidoscope.app/) take on git diff and merge view. I find it more intuitive and certainly easier to read and use.

Can you elaborate what you find easier to read and use and why? What can you do faster/easier in which tool?
Could it be that you are just more used to these tools?

**Comment by mathisgauthey** [comment]
> Thanks for the feedback!
> 
> > I am really missing the quality of [IntelJ](https://www.jetbrains.com/help/idea/resolve-conflicts.html), [Meld](https://meldmerge.org/) and [Kaleidoscope's](https://kaleidoscope.app/) take on git diff and merge view. I find it more intuitive and certainly easier to read and use.
> 
> Can you elaborate what you find easier to read and use and why? What can you do faster/easier in which tool? Could it be that you are just more used to these tools?

Hey there. Actually, I've been using VS Code for years now, but I work with someone using IDEA, and I'm always finding it easier to read changes on IntelJ diff view when we're working together on his setup. I'll talk mainly about the diff view, but it extends to the merge view.

I think I prefer IntelJ view because : 

1. The two panels are still `visually connected` with flowing blocks that relates to line numbers. (Diff and merge)
2. I can work on many changes and conflicts at once easily while resolving a 3-way merge conflict.

---

## Diff view

### 1. Panel connections.

In IntelJ, we have some "**flowing**" between the two panels. They help to **smooth the search for diff between two parts as it shows visually the number of line difference**. 

![image](https://github.com/microsoft/vscode/assets/46576952/ef62edd6-f730-44c4-907e-095b6c70988e)

In IntelJ, we can easily see what was `1 = modified`, `2 = deleted`, `3 = added`, `4 = conflicting` : 

<img width="1219" alt="15a673f0-4d79-470f-99ad-63b33df47d67" src="https://github.com/microsoft/vscode/assets/46576952/09401cc6-67c0-45fc-ad8d-b5b84180dcdc">

With VS Code, there is a "brutal" separation between the two panes that I think reduce the ease of noticing changes : 

![diff](https://github.com/microsoft/vscode/assets/46576952/f872246e-01d8-408d-82de-35baf4cf1958)

In addition, I think the UI is less clear about distinguing between what was modified, deleted and conflicting. Maybe it's about the colors.

## Merge view

### 2. Easier whole file merge conflict resolving

IntelJ provides some arrows, like VSCode, to choose between two sides. I know VS Code has a column view, but here again, the overflowing red flows help with noticing which changes are selected across the file : 

<img width="1047" alt="resolveConflict_dark" src="https://github.com/microsoft/vscode/assets/46576952/2d886ed1-d529-4adc-9e8b-b2b6817973dc">

_IntelJ also resolve non-conflicting changes with a magic wand that allows for faster diff and merge._

With the VS Code approach that you can see below, we can see the line numbers, but our eyes need to move quite permanently between the three view to see which one we want, and which one we applied. We need to look for the bottom panel and see if it's written `current` or `incoming` and then look back at which one is which, which makes us lose time.

In addition, this approach **forces us to work on one change at a time** :

![image](https://github.com/microsoft/vscode/assets/46576952/0272f59d-25df-40bb-a2f3-7e0636ee6014)

---

## Conclusion

I think it's really about having a visually "flowing" view that helps us noticing easily what changed (diff view) and which change we accepted (merge view) with a 3 columns UI that allows to work on more changes at once.

It makes us faster at noticing changes and confirming we're doing what we wanted to do.

Hope this helps !

---

Sources :
- #146091 : [Example of why it works well with arrows in IntelJ](https://github.com/microsoft/vscode/issues/146091#issuecomment-1087352389). There's also lot of discussion between the two view styles here.
- #93593 : Superbe comparison between the two views
- #37350 : Origin that led to the current VS Code 3-way merge
- #5770 : Multiple people asking for a IntelJ/Meld diff and merge view
- #25887 : A [gif example](https://github.com/microsoft/vscode/issues/25887#issuecomment-407681513) and some [comparison](https://github.com/microsoft/vscode/issues/25887#issuecomment-1153069612)

**Comment by hediet** [comment]
> # Diff view
> In IntelJ, we can easily see what was 1 = modified, 2 = deleted, 3 = added, 4 = conflicting :

I'm confused, you are comparing the merge view with the vscode diff view?

**Comment by mathisgauthey** [comment]
> > # Diff view
> > In IntelJ, we can easily see what was 1 = modified, 2 = deleted, 3 = added, 4 = conflicting :
> > In addition, I think the UI is less clear about distinguing between what was modified, deleted and conflicting. Maybe it's about the colors.
> 
> I'm confused, you are comparing the merge view with the vscode diff view?
> 
> It feels like you are discussing creating alignment with spacers (what VS Code/Visual Studio do) or with different scroll speeds (what IntelliJ and other tools do). They have both advantages and disadvantages.
> 
> But comparing the diff view with the merge view (which VS Code also has), is unhelpful.

Hey there ! No I'm not, even if the screenshot with the numbers from IntelJ is from a merge view, the UI color and "flowing" lines between the two panes are similar in their diff view.

What I wanted to showcase is how the simple flowing from multiple lines coming to another set of lines with what was removed, modified or added is really helpful and assist in visualizing faster what changed and how. The different colors are helpful as well.

**Comment by hediet** [comment]
> ![](https://private-user-images.githubusercontent.com/46576952/330557822-18f03d46-759e-4aa6-8e58-69e59fc4f362.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwODEzNzIsIm5iZiI6MTcxNzA4MTA3MiwicGF0aCI6Ii80NjU3Njk1Mi8zMzA1NTc4MjItMThmMDNkNDYtNzU5ZS00YWE2LThlNTgtNjllNTlmYzRmMzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDE0NTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZWIwZjcyYTlhOWY2ZTA4ZTIyNzYyYTMyOTJkNzIzZTgwMmY2NDNkZmNhOGFkOTAzYzEzYzMxYjM2NzBmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kHIsVDEgEgZgm24NmmdI5Te5FOhR-Fk91xxqUr28eUw)

Can you post a screenshot how this particular diff would look like in VS Code?

**Comment by mathisgauthey** [comment]
> > ![](https://private-user-images.githubusercontent.com/46576952/330557822-18f03d46-759e-4aa6-8e58-69e59fc4f362.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwODEzNzIsIm5iZiI6MTcxNzA4MTA3MiwicGF0aCI6Ii80NjU3Njk1Mi8zMzA1NTc4MjItMThmMDNkNDYtNzU5ZS00YWE2LThlNTgtNjllNTlmYzRmMzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDE0NTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZWIwZjcyYTlhOWY2ZTA4ZTIyNzYyYTMyOTJkNzIzZTgwMmY2NDNkZmNhOGFkOTAzYzEzYzMxYjM2NzBmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kHIsVDEgEgZgm24NmmdI5Te5FOhR-Fk91xxqUr28eUw)
> 
> Can you post a screenshot how this particular diff would look like in VS Code?

Sure, I would probably think of something like that : 
![ij_diff_in_editor](https://github.com/microsoft/vscode/assets/46576952/a51e4b08-2a7e-4334-9f03-61ff9a5ed647)

And with some drwings on the current VS Code UX : 
![image](https://github.com/microsoft/vscode/assets/46576952/7e1fb0be-e63d-4104-8679-850bc0e48bf0)

Basically in the diff view : 
- Moving or adding line number from `old` (left tab) closer to the `changed` (right tab).
- Adding visual flowing to highlight removals, changes and additions between the two tabs.

And I would also make these changes in the merge view, but only adding the visual flowing to changes that we accepted inside the merge, so that we can visually see easily what, in the result tab, was taken from `current` and what was taken from `incoming`.

Thanks for your time in reviewing these observations with me, that's really great ✌️

**Comment by hediet** [comment]
> Can you post a screenshot how this particular diff would look like in VS Code?

I mean can you do a screenshot of VS Code showing the very same diff (same java code)? You are comparing different diffs here.

**Comment by mathisgauthey** [comment]
> > Can you post a screenshot how this particular diff would look like in VS Code?
> 
> I mean can you do a screenshot of VS Code showing the very same diff (same java code)? You are comparing different diffs here.

Sure thing !

IntelJ IDEA : 

![image](https://github.com/microsoft/vscode/assets/46576952/3dd7768b-6a55-432e-98a4-8bbf3dcc08a5)

VS Code : 

![image](https://github.com/microsoft/vscode/assets/46576952/3774f14a-ff71-4838-be2d-6b32fb3138ef)

All in all, the points I prefer in IntelJ : 
- Overflowing lines that show relations between left and right
- Line number closer
- Ability to select blocks to include in the commit directly from a checkbox

VS Code chose to show delete blocks with the removed lines on the right, it is visual indeed but make us lose time because it creates "dead space" on the right end choice.

It's two different approaches, both have their advantages, but I'd love to be able to find this kind of UI on VS Code someday !

**Comment by hediet** [comment]
Thanks for the screenshot! Personally, I find the VS Code view much easier to process (also because of the moved code detection). I guess it is a matter of personal taste in the end.

I'm going to close this issue due to its unspecific title and unclear actionables, but feel free to create a new issue specifically for "Add option to hide spacers in diff editor, use scroll-alignment instead (as in IntelliJ)".

**Comment by mathisgauthey** [comment]
> Thanks for the screenshot! Personally, I find the VS Code view much easier to process (also because of the moved code detection). I guess it is a matter of personal taste in the end.
> 
> I'm going to close this issue due to its unspecific title and unclear actionables, but feel free to create a new issue specifically for "Add option to hide spacers in diff editor, use scroll-alignment instead (as in IntelliJ)" (though such feature request may exist already).

Fine by me, thanks for listening to my point ✌️

**Comment by guilhermetod** [comment]
I suggest this is reconsidered, I am trying Webstorm and I still prefer VS Code, but the diff editor is much better. The conclusion here might be to being used to VS Code, but I would guess blind tests would lead to majority preferring Webstorm in favor of VS Code diff.
