### ISSUE TITLE
The JS/TS language service immediately crashed 5 times.

### ISSUE THREAD

**Issue by zach-betz-hln** [microsoft/vscode#212731]
Type: <b>Bug</b>

When opening a TS file, the following error shows, and intellisense is lost when typing.

> The JS/TS language service immediately crashed 5 times. The service will not be restarted. This may be caused by a plugin contributed by one of these extensions: VisualStudioExptTeam.vscodeintellicode, VisualStudioExptTeam.vscodeintellicode. Please try disabling these extensions before filing an issue against VS Code.

VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|64.00GB (37.39GB free)|
|Process Argv|--crash-reporter-id 70c62290-a391-44ec-9698-cccd96dd53ab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.20.0
vscode-zipfs|arc|3.0.0
vscode-eslint|dba|2.4.4
gitlens|eam|14.5.2
json-tools|eri|1.0.2
prettier-vscode|esb|10.4.0
vscode-graphql|Gra|0.8.20
vscode-graphql-syntax|Gra|1.2.2
openvpn|idl|0.3.5
copy-json-path|Mal|1.2.0
rainbow-csv|mec|3.9.0
vscode-docker|ms-|1.28.0
playwright|ms-|1.0.19
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
prisma|Pri|5.7.0
even-better-toml|tam|0.19.2
pdf|tom|1.2.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.25.15
vscode-maven|vsc|0.43.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
showvideoc:31016891
dsvsc021:30996838
g316j359:31013175
a69g1124:31046351
pythonprt:31039817
dwnewjupytercf:31046870

```

</details>

<details><summary>Screenshot</summary>

![Screenshot 2024-05-14 at 1 43 51 PM](https://github.com/microsoft/vscode/assets/119352232/260ff544-8814-496a-8f12-d6d203ea9b2c)

</details>

**Comment by zach-betz-hln** [comment]
Potentially related issues:
- https://github.com/microsoft/vscode/issues/212723
- https://github.com/microsoft/vscode/issues/212583
- https://github.com/microsoft/vscode/issues/212395
- https://github.com/microsoft/vscode/issues/212350
- https://github.com/microsoft/vscode/issues/208446
- https://github.com/microsoft/vscode/issues/207998
- https://github.com/microsoft/vscode/issues/206780

**Comment by zach-betz-hln** [comment]
I can reproduce this with the _Visual Studio Code Insiders_ build: 

> The JS/TS language service crashed.

![Screenshot 2024-05-14 at 1 55 33 PM](https://github.com/microsoft/vscode/assets/119352232/862b3654-755b-4b76-ada8-3fb0ffc4bf33)

**Comment by zach-betz-hln** [comment]
My workaround for now was to downgrade from version `1.89.1` to `1.88.1`

**Comment by davidcilley** [comment]
I've been experiencing the same issue regardless of VSCode version. I've tried downgrading to `1.88.1`, and tried the latest insiders build. Narrowed it down to the `TSServer` crashing. I was able to mitigate by installing typescript `5.4.4` globally and point VSCode's TypeScript: Tsdk path to the globally installed version.

**Comment by misaelaguayo** [comment]
I am seeing this as well

**Comment by spark15** [comment]
I test few things like changing computer and clean install. it seems typescript(over 5.4)+yarn with pnp causes error.

**Comment by zach-betz-hln** [comment]
> I test few things like changing computer and clean install. it seems typescript(over 5.4)+yarn with pnp causes error.

Can confirm. Was using Yarn version 4.1.1 in PNP mode with TS version 5.4.3

**Comment by akeating** [comment]
Downgrading to `1.88.1` also resolved this for me. yarn 4.2.2 pnp, typescript 5.4.5

**Comment by agentpietrucha** [comment]
I tried downgrading vs code to version `1.88.1` but without any luck. I am still having issues, especially with intellisense being stuck on loading status

My versions:
node: `v20.13.1`
npm: `10.5.2`
typescript: `5.3.3`

**Comment by ollyak** [comment]
This fixed the issue for me:
1. Uncheck "Experimental: Use Vs Code Watcher" checkbox in VS Code Settings / Extensions / Typescript / Tsserver.
2. Restart VS Code.

**Comment by random42** [comment]
I've solved by doing a clean reinstall of VSCode.

**Comment by mjbvz** [comment]
If you're using yarn, there's a bug on their side: https://github.com/yarnpkg/berry/issues/6304


@zach-betz-hln Are you using yarn? Also did you test disabling with those listed extensions (VisualStudioExptTeam.vscodeintellicode, VisualStudioExptTeam.vscodeintellicode)?

**Comment by zach-betz-hln** [comment]
@mjbvz thanks for the yarn issue link. Yes, am using yarn.

When first creating this issue, I tried searching my extensions for those listed, but no results were found. I'm assuming this is because they're built-in extensions? Am not sure. 

Also, I have no desire to use vscode without intellisense 🤷‍♂️

**Comment by soulice94** [comment]
> This fixed the issue for me:
> 
> 1. Uncheck "Experimental: Use Vs Code Watcher" checkbox in VS Code Settings / Extensions / Typescript / Tsserver.
> 2. Restart VS Code.

This works for me also, thanks so much. Lost a lot of time solving this.

**Comment by LynBean** [comment]
![image](https://github.com/microsoft/vscode/assets/57824016/fd516f2a-ebd8-4f24-b6e2-7f9165f285b9)
For my case, this works for me, due to out of memory in TS Server memory allocation, so just increase the limit and the problem should be solved.

**Comment by Gustavo-Brun** [comment]
> This fixed the issue for me:
> 
> 1. Uncheck "Experimental: Use Vs Code Watcher" checkbox in VS Code Settings / Extensions / Typescript / Tsserver.
> 2. Restart VS Code.

worked for me
