### ISSUE TITLE
"View in Marketplace" makes the hover heavy

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#212760]
Do we really need the "View in Marketplace" part in the hover. My concern is that it makes the hover look heavy.

My suggestion is to cut that. And instead, clicking on the second row in the hover would take the user to the extension view.

If you really want to keep the "View in Marketplace" experience, I suggest:
1) Use the same background as rest of hover
2) Call it "View Extension" instead, since you do not actually take the user to the Marketplace

![Image](https://github.com/microsoft/vscode/assets/1926584/443d181f-0066-4608-bdc8-aaa9695450a6)

**Comment by daviddossett** [comment]
I'm fine getting rid of it. It was a quick design proposal and linking to the extension page seemed like a useful thing to include. Having the extension name be a link could work as an alternative, yeah.

**Comment by roblourens** [comment]
I'm going to leave it for now, it's there, the status bar actions are used for other hovers too, and I haven't heard any other complaints
