### ISSUE TITLE
Chat - if there is content in input I can not navigate history

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#212758]
1. Have some history in your Chat session
2. Have some content in the input box.
3. Press `up` - you are navigated to the first character in the input
4. Press `up` again - history is not shown 🐛 

Notice how the other widgets in VS Code work - terminal, search. I can press `up` as long as I am on the start of the input, and the history will be shown.

This is particularly noticeable in Chat with sticky participants. Since they are always there, and when interacting with them I have no way to navigate to history.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/1208
