### ISSUE TITLE
[Mac] window.titleBarStyle not applying in fullscreen

### ISSUE THREAD

**Issue by subic** [Microsoft/vscode#21270]
- VSCode Version: 1.9.1 (latest)
- OS Version: macOS Sierra 10.12.3 (latest, Hide menubar & Dark menubar enabled )

Steps to Reproduce:

1. In settings: "window.titleBarStyle": "custom" (default)
2. Full screen a vsc window on mac
3. Maximize another vsc window
4. Compare titlebars

![fullscreen](https://cloud.githubusercontent.com/assets/6759483/23257955/566c7894-f9c6-11e6-8744-b0bbcef25eda.png)
![maximized](https://cloud.githubusercontent.com/assets/6759483/23257956/566f884a-f9c6-11e6-8c24-9ef8b2d34073.png)

**Comment by bpasero** [comment]
This is not under our control currently.

**Comment by bpasero** [comment]
There are not plans to implement this, closing.
