### ISSUE TITLE
Git's clean all, delete all files in local machine.

### ISSUE THREAD

**Issue by salvadorhm** [Microsoft/vscode#21279]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.9.9-200.fc25.x86_64
- Extensions:

|Extension|Author|Version|
|---|---|---|
|git-easy|bibhasdn|1.9.1|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.5.5|
|java|redhat|0.0.7|
|Spell|seanmcbreen|0.8.6|
|python|tht13|0.2.3|

---

The git's clean all function, delete all the projects  in  local machine, MEGAFAIL!!!!

Steps to Reproduce:

1. Open Git plugin
2. Clean all

**Comment by roblourens** [comment]
Can you be more specific? I would expect it to clean all your changes. Did it do something else?

**Comment by salvadorhm** [comment]
Yes, clean should delete the files, but delete all the files in the folder,
including files in other projects.

The other files do not have relationship with git project, and they was
delete too.

Thanks for help.

**Comment by joaomoreno** [comment]
You surely had initialised a git repository somewhere above your workspace folder. When you clicked `Clean All` Code told you

> There are unstaged changes in X files. This action is irreversible!
> Are you sure you want to clean all changes?

And you pressed _Yes_.
