### ISSUE TITLE
Tooltip should be above in terms of direction. as it is overalpping with mouse pointer

### ISSUE THREAD

**Issue by hardiklakhalani** [microsoft/vscode#212778]
Type: <b>Bug</b>

I version control & probably all the icons have tooltip _below_ the icon. which is overlaping with mouse pointer. It should be above instead of below.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.71GB free)|
|Process Argv|--crash-reporter-id 321251cb-1eca-46bd-b40a-54edbff67c35|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-laravel-goto|abs|4.28.9
flutter-snippets|ale|3.0.0
amazon-q-vscode|ama|1.4.0
aws-toolkit-vscode|ama|3.3.0
laravel-extra-intellisense|ami|0.6.5
laravel-blade-spacer|aus|2.3.0
docs-view|bie|0.1.0
laravel-goto-view|cod|1.3.11
laravel-goto-view|ctf|0.6.1
dakara-foldplus|dak|1.5.2
devdb|dam|1.7.15
dart-code|Dar|3.88.1
flutter|Dar|3.88.0
vscode-faker|dee|2.0.0
intelli-php-vscode|DEV|0.12.15062
jquerysnippets|don|0.0.1
gitlens|eam|15.0.3
EditorConfig|Edi|0.16.4
copilot|Git|1.192.0
copilot-chat|Git|0.15.1
laravel-create-view|gli|0.0.6
gc-excelviewer|Gra|4.2.59
dummytextgenerator|gur|1.0.1
rest-client|hum|0.25.1
laravel-blade-wrapper|IHu|1.0.1
pubspec-assist|jer|2.3.2
vscode-peacock|joh|4.2.2
dart-import|lua|0.3.1
php-namespace-resolver|Meh|1.1.9
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-git-notify|mkl|0.4.2
laravel-intellisense|moh|0.2.0
laravel-goto-components|nao|1.2.0
awesome-flutter-snippets|Nas|4.0.1
copy-filepath-with-line-number|nis|0.0.5
indent-rainbow|ode|8.3.1
laravel-blade|one|1.36.0
laravel-extension-pack|one|1.3.0
laravel5-snippets|one|1.18.0
dartgettersetter|Pet|1.0.2
laravel-jump-controller|pgl|0.0.33
material-icon-theme|PKi|5.3.0
remove-comments|pli|1.2.2
flutter-print|ric|1.7.2
laravel-artisan|rya|0.0.31
text-marker|ryu|1.11.0
vscode-blade-formatter|shu|0.24.2
code-spell-checker|str|3.0.1
sort-lines|Tyr|1.11.0
errorlens|use|3.17.0
adb-interface-vscode|vin|0.22.4
intellicode-api-usage-examples|Vis|0.2.8
php-debug|xde|1.34.0
php-pack|xde|1.0.3
markdown-all-in-one|yzh|3.6.2
flutter-provider-snippets|Zar|1.5.0
html-css-class-completion|Zig|1.20.0
php-intellisense|zob|1.3.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
724cj586:31013169
pythoncenvptcf:31043158
fchga941:31046352
pythonprc:31047982
dwnewjupyter:31046869

```

</details>

**Comment by MiSchroe** [comment]
**+1** from me for this one.

I'm working on a 4K resolution screen. I have raised the size of the mouse pointer in the Windows settings to spot it easily on the screen and now it hides all the tooltips.

The current position of the the tooltips reduces usability and accessibility.

### Suggestion:
Make the position of the tooltip configurable in the settings.
