### ISSUE TITLE
TS Server fatal error:  UNC host 'iam_nas' access is not allowed

### ISSUE THREAD

**Issue by preethiWDT** [microsoft/vscode#212784]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.4.5

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (7.41GB free)|
|Process Argv|--crash-reporter-id 42ade171-f4f0-4575-a105-b31f69e462d5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
find-and-replace-in-selected-files|Aar|1.0.1
string-converter|ada|0.1.2
ng-copy-structure|adr|1.5.1
copy-relative-path|ale|0.0.2
stackoverflow-search|Ale|1.2.0
better-find-and-replace|ami|0.0.2
html-class-suggestions|And|1.2.1
go-sql-highlight|ant|0.0.4
Bito|Bit|1.3.3
blackbox|Bla|1.3.34
bracket-pair-toggler|dzh|0.0.3
vscode-firefox-debug|fir|2.9.10
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
search-node-modules|jas|1.3.0
google-search|kam|0.0.1
haml|kar|1.4.1
sftp|Nat|1.16.3
indent-rainbow|ode|8.3.1
copy-file-name|ouw|3.0.9
convert-css-in-js|pau|1.1.3
material-icon-theme|PKi|5.3.0
copy|Pra|1.1.1
format-html-in-php|rif|1.7.0
vscode-auto-close-bracket|sdd|0.0.3
trailing-spaces|sha|0.4.1
search|use|0.0.1
reopenclosedtab|uyi|1.1.0
blocks-highlighter|Vas|1.2.2
chatgpt-ai|Yal|0.7.12

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vswsl492cf:30256860
vstes516:30244333
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
g316j359:31013175
fchga941:31046352
pythonprt:31047983
dwnewjupytercf:31046870

```

</details>

**Comment by bpasero** [comment]
Beginning with VS Code `1.78.1` accessing any UNC path (those that begin with `\\`) on Windows is blocked to mitigate a security risk that is further explained in this [Security Advisory](https://github.com/microsoft/vscode/security/advisories/GHSA-mmfh-4pv3-39hr).

Please refer to https://aka.ms/vscode-windows-unc for more information how to make your specific UNC path work again.
