### ISSUE TITLE
Debugging Restart Fails With Azure Sphere Projects 

### ISSUE THREAD

**Issue by snehara99** [microsoft/vscode#212823]
Does this issue occur when all extensions are disabled?: N/A (extensions are necessary to repro)

- VS Code Version: 1.89.1 (user setup)
- OS Version: Windows_NT x64 10.0.22631

**Steps to Reproduce:** 
Note: You cannot reproduce this without an Azure Sphere device so I recorded [this video](https://microsoft-my.sharepoint.com/:v:/p/snehara/Ect7oQ-rPFFNmbbk1QsLJ7cBO4EbuWBd5BsOJbU83y1QrQ?e=qhjq1H) (Microsoft internal).

1. Install Azure Sphere, Azure Sphere UI, C/C++, CMake, and CMake Tools extensions.
2. Install Azure Sphere SDK.
3. Clone Azure Sphere sample app [repo](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sphere-samples%2Ftree%2Fmain%2FSamples%2FHelloWorld%2FHelloWorld_HighLevelApp&data=05%7C02%7Csnehara%40microsoft.com%7C5c9dc4c1ea4340e63bc108dc7463d554%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638513219377289347%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=cAnp01npWsf6jcQUIgD7w8bAfX08LShnf%2FTuSsooSH8%3D&reserved=0) and open the project at the path linked.
4. Connect Azure Sphere device.
5. Hit "Run and Debug" from side panel.
6. Open C/C++ extension output panel to see initial launch configuration.
7. Hit Restart button on debugging toolbar and observe failure.
a. "launch: property 'program' is missing or empty" notification pops up on bottom right, but you can see that this property was provided in the original launch configuration.
8. Open C/C++ extension output panel to see launch configuration on restart and observe how it doesn't contain the properties provided by the Azure Sphere extension on the initial launch.

This is the Azure Sphere configuration provider: [configurationProvider.ts - Repos (azure.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fmsazuresphere%2F4x4%2F_git%2FVsCodeExtension%3Fpath%3D%2FExtension%2Fsrc%2Fdebugger%2FconfigurationProvider.ts&data=05%7C02%7Csnehara%40microsoft.com%7C5c9dc4c1ea4340e63bc108dc7463d554%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638513219377280996%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=pwPOhOscpL%2F66f72yB%2BEQFjOgOeacio%2BhmfuZAbEUM0%3D&reserved=0). [Line 548](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fmsazuresphere%2F4x4%2F_git%2FVsCodeExtension%3Fpath%3D%2FExtension%2Fsrc%2Fdebugger%2FconfigurationProvider.ts%26version%3DGBmain%26line%3D548%26lineEnd%3D548%26lineStartColumn%3D12%26lineEndColumn%3D83%26lineStyle%3Dplain%26_a%3Dcontents&data=05%7C02%7Csnehara%40microsoft.com%7C5c9dc4c1ea4340e63bc108dc7463d554%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638513219377285156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ncpMqwhwHHo%2B5w1RUzzqj7Wxal9PHG49zGdqlv9myHo%3D&reserved=0) is where we start debugging. Our code isn't touched again after hitting restart.

This is a screenshot comparing the project's launch.json, the initial launch configuration given to the C/C++ extension and the launch configuration given to the C/C++ extension on restart:
![image](https://github.com/microsoft/vscode/assets/113148726/b2b6489f-ea81-4169-9bb1-7b13ff205992)

**Comment by snehara99** [comment]
Please let me know if you'd like a virtual walkthrough

**Comment by roblourens** [comment]
The C++ debug adapter doesn't set `supportsRestartRequest`, right?

**Comment by roblourens** [comment]
It looks like you register your own debug adapter type, and resolve it to cppdbg in your provider, is that right?

**Comment by snehara99** [comment]
> The C++ debug adapter doesn't set `supportsRestartRequest`, right?

It doesn't I don't think. Should it be?

**Comment by roblourens** [comment]
> > The C++ debug adapter doesn't set `supportsRestartRequest`, right?
> 
> It doesn't I don't think. Should it be?

No, it just enables a different mode for restarting and I'm checking which path it goes down.

**Comment by roblourens** [comment]
I was thinking about where the problem could be, and I came across a bug here https://github.com/microsoft/vscode/pull/212991 and I think it might fix your issue, but I'm not sure.

Our Insiders releases are paused for the Build conference, so this won't be in an Insiders until around next Thursday. You can try then, or build the vscode repo if you want to try it earlier.

**Comment by snehara99** [comment]
@roblourens thanks, I'll try it out when it releases. I'm not in a rush

**Comment by snehara99** [comment]
@roblourens I tried the insiders release and the issue seems to be fixed! When would this be updated in the main vscode btw?

**Comment by roblourens** [comment]
Thanks for confirming. We will release VS Code this week
