### ISSUE TITLE
android devices is not detecting

### ISSUE THREAD

**Issue by jettinsha** [microsoft/vscode#212884]
Type: <b>Bug</b>

android devices is not detecting

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.33GB (0.75GB free)|
|Process Argv|--crash-reporter-id 2e3a207b-fc77-4715-ab75-9dadb6ece6e0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-import-sorter|azi|0.3.3
vscode-django|bat|1.15.0
fixmyarb|coo|1.0.2
dart-code|Dar|3.88.1
flutter|Dar|3.88.0
emulate|Die|1.6.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
vscode-html-css|ecm|2.0.9
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
remotehub|Git|0.62.0
vsc-python-indent|Kev|1.18.0
vscode-gutter-preview|kis|0.31.2
dart-import|lua|0.3.1
theme-monokai-pro-vscode|mon|1.3.2
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
azure-repos|ms-|0.38.0
remote-repositories|ms-|0.40.0
auto-semicolon-vscode|mya|1.5.1
awesome-flutter-snippets|Nas|4.0.1
color-highlight|nau|2.8.0
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|5.3.0
LiveServer|rit|5.7.9
adb-interface-vscode|vin|0.22.4
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.13.5
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vswsl492cf:30256860
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
g316j359:31013175
fchga941:31046352
pythonprt:31047983
dwnewjupyter:31046869

```

</details>

**Comment by roblourens** [comment]
This sounds like it might be related to an extension
