### ISSUE TITLE
Git open file action not working when diff view shows no changes

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#21285]
1. Have some changes in a file
2. Open git diff view and commit those changes
3. Notice how the diff view is still open, even though there are no changes
4. Click on the `open file` action in the diff view title bar -> nothing happens

**Comment by isidorn** [comment]
Haha there you go with steps dawg

**Comment by joaomoreno** [comment]
Nice memory you got there, Dory.

![dory](http://i.giphy.com/3o6ozgge4UJklqLgIg.gif)

**Comment by isidorn** [comment]
This is once again not working -> reopening, april
