### ISSUE TITLE
Add `Collapse All Runs` button to Test Results view toolbar

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#212876]
Type: <b>Feature Request</b>

The tree of previous testrun results loads expanded when VS Code starts. It would be convenient to have a collapse-all button to collapse them all. Currently I have to focus on one of the top-level rows and press Ctrl+LeftArrow.

![image](https://github.com/microsoft/vscode/assets/6726799/f0389645-dd9f-4e69-a246-7f24da12c676)

VS Code version: Code - Insiders 1.90.0-insider (0cd8d6ac480bc5b4e2a2d7f1eb87eaff9f7d47e1, 2024-05-16T05:49:53.998Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by connor4312** [comment]
We've reworked this display so that older runs are always collapsed when new runs are made
