### ISSUE TITLE
[Bug] Move line up in folded code

### ISSUE THREAD

**Issue by Nimzozo** [Microsoft/vscode#21284]
- VSCode Version: 1.9.1
- OS Version: Win 10

Steps to Reproduce:

1. Fold a part of code and add a line after this folded part.
2. Try to move up this line.
3. The line to move up will be changed with the first line of the folded part of code.

**Comment by aeschli** [comment]
@Nimzozo Can you please attach a small code that shows the issue. Also describe what you think the expected result should be.
I tried this and see that the line gets moved up one line. Then the folding regions are reevaluated. Folding regions are based on the indentations, so either the moved up line likely becomes the last line of the folded range, or goes inside the folded range.
So from how I see it is is all as expected.

**Comment by aeschli** [comment]
Closing as more information is needed.

**Comment by Nimzozo** [comment]
@aeschli I'm sorry, I wasn't very active on Github lately. I admit I can't really reproduce or remember the exact way this bug happened.
Also I'm now using VSCode latest version, so this issue might have been corrected.
