### ISSUE TITLE
Make sure child instantiation service instances are disposed/tracked for disposal

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#212879]
Since recently the instantiation service is disposable. A instantiation service will dispose all service instances it has created and will dispose all its children. In return, children should also be explicitly disposed so that they get released from their parents. This item tracks the adoption of registering child instantiation service instances with a disposable. 

<sup>*</sup> This became an issue because we now prevent GC'ing of child service and thereby implicit clean-up. So, while this is more work/tracking it is true disposing of services. Overall, this isn't severe because the vast majority of insta-children are for scoped context key services

**Comment by jrieken** [comment]
Best-guess assignment, please re-assign along the way. A sample adoption is [d1fdc09](https://github.com/microsoft/vscode/commit/d1fdc09e8a7df5f56f04fffe5c77c4205c14940c)

- [ ] src/vs/workbench/api/browser/mainThreadCLICommands.ts @aeschli 
- [ ] src/vs/workbench/api/common/extHostExtensionService.ts
- [ ] src/vs/workbench/browser/parts/compositePart.ts @sandy081 
- [ ] src/vs/workbench/browser/parts/editor/auxiliaryEditorPart.ts @bpasero 
- [ ] src/vs/workbench/browser/parts/editor/editorGroupView.ts @bpasero 
- [ ] src/vs/workbench/browser/parts/editor/editorPart.ts @bpasero 
- [ ] src/vs/workbench/browser/parts/editor/editorStatus.ts @bpasero 
- [ ] src/vs/workbench/browser/parts/editor/editorTabsControl.ts @bpasero 
- [ ] src/vs/workbench/browser/parts/views/viewPane.ts @sandy081 
- [ ] src/vs/workbench/contrib/chat/browser/chatEditor.ts @roblourens 
- [ ] src/vs/workbench/contrib/chat/browser/chatInputPart.ts @roblourens 
- [ ] src/vs/workbench/contrib/chat/browser/chatListRenderer.ts @roblourens 
- [ ] src/vs/workbench/contrib/chat/browser/chatQuick.ts @TylerLeonhardt 
- [ ] src/vs/workbench/contrib/chat/browser/chatViewPane.ts @roblourens 
- [ ] src/vs/workbench/contrib/chat/browser/chatWidget.ts @roblourens 
- [ ] src/vs/workbench/contrib/chat/browser/codeBlockPart.ts @roblourens 
- [ ] src/vs/workbench/contrib/codeEditor/browser/suggestEnabledInput/suggestEnabledInput.ts @connor4312 
- [ ] src/vs/workbench/contrib/comments/browser/commentThreadZoneWidget.ts @alexr00 
- [ ] src/vs/workbench/contrib/debug/browser/breakpointWidget.ts @connor4312 
- [ ] src/vs/workbench/contrib/debug/browser/repl.ts @connor4312 
- [ ] src/vs/workbench/contrib/extensions/electron-sandbox/remoteExtensionsInit.ts @sandy081 
- [ ] src/vs/workbench/contrib/inlineChat/browser/inlineChatContentWidget.ts @jrieken 
- [ ] src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts @jrieken 
- [ ] src/vs/workbench/contrib/languageStatus/browser/languageStatus.contribution.ts @bpasero 
- [ ] src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts @lyup 
- [ ] src/vs/workbench/contrib/notebook/browser/view/cellParts/markupCell.ts 
- [ ] src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts
- [ ] src/vs/workbench/contrib/output/browser/outputView.ts
- [ ] src/vs/workbench/contrib/scm/browser/menus.ts @lszomoru 
- [ ] src/vs/workbench/contrib/scm/browser/scmViewPane.ts @lszomoru 
- [ ] src/vs/workbench/contrib/search/browser/searchResultsView.ts @andreamah 
- [ ] src/vs/workbench/contrib/search/browser/searchView.ts @andreamah 
- [ ] src/vs/workbench/contrib/searchEditor/browser/searchEditor.ts @andreamah 
- [ ] src/vs/workbench/contrib/terminal/browser/terminalInstance.ts @Tyriar 
- [ ] src/vs/workbench/contrib/testing/browser/testingOutputPeek.ts @connor4312 
- [ ] src/vs/workbench/services/userDataProfile/browser/extensionsResource.ts @sandy081 

- [ ] src/vs/workbench/contrib/inlineChat/test/browser/inlineChatController.test.ts
- [ ] src/vs/workbench/contrib/inlineChat/test/browser/inlineChatSession.test.ts
- [ ] src/vs/workbench/services/preferences/test/browser/preferencesService.test.ts
- [ ] src/vs/workbench/services/textfile/test/browser/browserTextFileService.io.test.ts
- [ ] src/vs/workbench/services/textfile/test/electron-sandbox/nativeTextFileService.io.test.ts
- [ ] src/vs/workbench/services/textfile/test/electron-sandbox/nativeTextFileService.test.ts
- [ ] src/vs/workbench/test/browser/contributions.test.ts

**Comment by alexr00** [comment]
Took care of mine last month with https://github.com/microsoft/vscode/pull/213808

**Comment by bpasero** [comment]
Not sure if this can be closed.

**Comment by jrieken** [comment]
- [ ] src/vs/workbench/contrib/notebook/browser/services/notebookEditorServiceImpl.ts#L232

**Comment by jrieken** [comment]
@rebornix you are last one here 🔝

**Comment by rebornix** [comment]
done!
