### ISSUE TITLE
Javascript Intellisense Often Does Not Work

### ISSUE THREAD

**Issue by martin-wiseweb** [Microsoft/vscode#21286]
- VSCode Version: 1.10.0-insider
- OS Version: Windows 7

_I can't reliably determine steps to reproduce._

### Description

Often when I am working on Javascript projects, VS Code's Intellisense does not work. This is usually when I'm working on existing projects - but this is most of the time. Because I'm working on existing projects it's almost impossible to determine what steps are needed to reproduce.

An example here:

![image](https://cloud.githubusercontent.com/assets/3329959/23265074/9881b254-f9b1-11e6-8dd6-51d27bd9d552.png)

The file is clearly Javascript yet it says "No Symbols Found" and autocompletion doesn't work at all.

Furthermore, I have no errors or any indication of _why_ it isn't working so I'm left pretty much powerless.

**Comment by martin-wiseweb** [comment]
Is there a debug log or something I can refer to in order to try to figure out what is wrong/missing?

**Comment by mjbvz** [comment]
@martin-wiseweb To start:

* Add the setting `"typescript.tsserver.trace": "verbose"`.
* Restart VSCode
* Reproduce the issue.
* Go to `View -> Output` and open the `TypeScript` section of the output view.

Please share the log to help us investigate this. If you can, please also share a small project that shows this behavior

Thanks

**Comment by martin-wiseweb** [comment]
Interestingly, after restarting VS Code, the problem is no longer there.

I'll close this issue until I can provide some better information.

Furthermore, I'll try to replicate in a project whose source I can open up to you :)
