### ISSUE TITLE
Single line code collapsing

### ISSUE THREAD

**Issue by edvinv** [Microsoft/vscode#21288]
Currently when you collapse code block you get two lines. Something like this.
```js
get CurrentSession(): DialerCampaignSessionModel {...
}
```
This is quite unreadable when you collaps a lot of blocks and also IMO the whole point of collapsings is to get as few lines as possible. For me, following is much better and more readable.
```js
get CurrentSession(): DialerCampaignSessionModel {...}
```
It will be nice if there was option to select collapsing type. Of course it should work for all languages.

**Comment by roblourens** [comment]
Master request here: #19690
