### ISSUE TITLE
Extension log does not seem to show up sometimes

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#212804]
From @karthiknadig 

@sandy081 finally i caught the error. This is what I see, some times Python logs don't show up with this error:
```
ERR Error while registering log channel file:///c%3A/Users/kanadig/AppData/Roaming/Code%20-%20Insiders/logs/20240513T105426/window18/exthost/ms-python.python/Python.log Timed out while waiting for file to be created
```

**Comment by karthiknadig** [comment]
![image](https://github.com/microsoft/vscode/assets/3840081/8787153f-579e-4830-82c9-e0b662028a7d)

I now regularly hit this when debugging extensions.

**Comment by karthiknadig** [comment]
@sandy081 I think we can close this. I have not hit this recently.
