### ISSUE TITLE
active tab top border is missing

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#212846]
I'm unable to add it back in manually

![image](https://github.com/microsoft/vscode/assets/2019016/80ee015e-3e28-4f67-bd0b-41c2f7b1af28)

**Comment by benibenj** [comment]
It's working for me

![Image](https://github.com/microsoft/vscode/assets/44439583/71c23919-8714-4da3-bffc-5185a3450d28)

Can you try the newest insiders and in case you still see it, send me your entire `colorCustomizations` setting?
Also, if you have any other tab related setting that would also be helpful to know (even though probably not the cause).

**Comment by amunger** [comment]
it's back on the latest insiders
