### ISSUE TITLE
Chat failed to load. Please ensure that the GitHub Copilot Chat extension is up to date

### ISSUE THREAD

**Issue by lishaobos** [microsoft/vscode#212855]
when i log out github copilot chat

<img width="1498" alt="image" src="https://github.com/microsoft/vscode/assets/46661044/45eda2b8-38e4-40ce-b1dc-b23d63cfec59">

**Comment by lishaobos** [comment]
vscode version: 1.89

**Comment by TylerLeonhardt** [comment]
@roblourens you mentioned you knew about this notification but if it's something actually auth related, throw it back to me

**Comment by roblourens** [comment]
This is fixed in Insiders now, we will have a smarter compatibility check

**Comment by MightyVlad** [comment]
I'm also having this exact error on VS Code 1.89.1, also tried VS code insiders, after installing the extension, it asks to authenticate, after that when I click on the Copilot chat icon on the left side, there is still a button that says Sign in even though it's already signed in. And clicking on the sign in button does absolutely nothing. Please I would appreciate it if there is a fix

**Comment by NayaTest1** [comment]
Any help here please? I am also having the same issue

**Comment by roblourens** [comment]
If you're having trouble using Chat in Insiders, please open a new issue and include the "GitHub Copilot Chat" output channel log, thanks
