### ISSUE TITLE
Sticky header line does not properly update its collapse icon

### ISSUE THREAD

**Issue by Rekkonnect** [microsoft/vscode#212833]
Type: <b>Bug</b>

With sticky header lines I collapse the region from the button on the sticky header, and then re-expand it. Its icon is not properly updated after the expansion.

The region I collapsed also had sub-regions, and it was on a Markdown file.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (1.86GB free)|
|Process Argv|--crash-reporter-id 95c24160-1302-4089-b0cd-a1a57e1301b7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
ide-vscode|daf|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31043157
fchga941:31038042
pythonprc:31039816
dwnewjupyter:31039675

```

</details>

**Comment by aiday-mar** [comment]
Hi @Rekkonnect thank you for posting this issue. Could you please include a screen-recording of the issue, so I can better understand what is happening?

**Comment by Rekkonnect** [comment]
Here you go:
https://github.com/microsoft/vscode/assets/8298332/2305134b-77a3-4c09-9026-3e3bae071f4d

**Comment by aiday-mar** [comment]
I see thanks for the screen recording. Could you paste here the markdown file from the screen recording or any other file which causes the same issue so I can reproduce it on my machine?

**Comment by Rekkonnect** [comment]
Here's the file:
https://github.com/Rekkonnect/Syndiesis/blob/master/docs%2Fchangelog.md

**Comment by aiday-mar** [comment]
Hi may I ask you if you still see this issue in VS Code. Some improvements have been made to sticky scroll these past few months? If you do not see this happening, I will close this issue.
