### ISSUE TITLE
[Feature Request] Capture / replace for Custom Label patterns

### ISSUE THREAD

**Issue by matthew-dean** [microsoft/vscode#212827]
The new Custom Labels feature is great, but it lacks basic replace functionality.

For example, I have a this pattern to reduce the visual noise of `index.*` files:
```json
"workbench.editor.customLabels.patterns": {
  "**/index.*": "${dirname}/.${extname}"
}
```
This works in general, but what I want is to _omit_ index. So, for example, I have this pattern in my files:

- `folder`
  - `index.model.ts`
  - `index.model.old.ts`

These both end up looking like `folder/.ts`. But that's not what I want, I want `folder/.model.ts` and `folder/.model.old.ts`.

### Proposal

Allow glob capture groups.

### Example

```json
"workbench.editor.customLabels.patterns": {
  "**/index(.*)": "${dirname}/$1"
}
```

**Comment by benibenj** [comment]
We are planning on improving `${extname}` and `${filename}` for files with multiple extensions. We are tracking this here: #210166
For the time being we are not planning on adding capture groups as supporting them will impact performance.

Closing this issue for this #210166
