### ISSUE TITLE
Problems panel doubles warnings and errors

### ISSUE THREAD

**Issue by giapelle** [Microsoft/vscode#21280]
- VSCode Version: Code - Insiders 1.10.0-insider (0b27b528a7aac070bced1239310144d0763823bd, 2017-02-23T07:04:58.188Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.6|
|githistory|donjayamanne|0.1.5|
|docthis|joelday|0.4.0|
|debugger-for-chrome|msjsdiag|2.5.3|;

---
Problems panel doubles warnings and errors for file under git source control:

![screenshot 2017-02-23 alle 15 35 26](https://cloud.githubusercontent.com/assets/10326690/23263314/252f2b24-f9de-11e6-9ed5-6191f9b701a7.png)

**Comment by joaomoreno** [comment]
This is as designed. More info: #19627, #20859

cc @Microsoft/vscode
