### ISSUE TITLE
Access Denied with cmd.exe

### ISSUE THREAD

**Issue by kkduncan** [microsoft/vscode#212828]
Type: <b>Bug</b>

Whenever I try to remotely connect to a server, I get the following error:
[13:36:36.526] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:36:36.970] > Access is denied.
> ]0;C:\WINDOWS\System32\cmd.exe

When I run VSCode as an administrator, I don't run into this issue. I started seeing this error after a recent Windows update where Outlook and Teams were updated.

How can I resolve this error without running VSCode as an administrator? Thanks in advance

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.4.0-113-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (3.42GB free)|
|Process Argv|--crash-reporter-id 6e2e8078-64c4-4f59-81f0-1909d778c81f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dgx1-ubuntu_20.04|
|OS|Linux x64 5.4.0-113-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz (80 x 2705)|
|Memory (System)|503.78GB (461.45GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
systemd-unit-file|coo|1.0.6
CppSnippets|har|0.0.15
better-cpp-syntax|jef|1.17.2
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.362.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
notepadplusplus-keybindings|ms-|1.0.7
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31049070
fchga941:31046352
dvdeprecationcf:31040882
pythonprt:31047983
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by roblourens** [comment]
Sorry, something must have changed with your system configuration and I'm not sure what it is actually complaining about.

**Comment by kkduncan** [comment]
VSCode for some reason cannot access the cmd.exe application unless I run it in administrator mode. I don't know what setting was changed to create this issue. Please advise. Thanks.

**Comment by kkduncan** [comment]
Any recommendations? This problem is not resolved for me @roblourens
