### ISSUE TITLE
feature request: Enabling typescript isolated modules

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#212835]
Related #160416

For migrating towards ESM in VSCode, it seems the tsconfig [isolatedModules](https://www.typescriptlang.org/tsconfig/#isolatedModules) option could be useful, ensuring that imports are compatible with ESM. 

For example, this typescript code transpiled to javascript would cause a runtime error because of the `someType` export:

```js
import { someType, someFunction } from "someModule";
 
someFunction();

export { someType, someFunction };
 ```

The `isolatedModules` rule would enforce a type only import for `someType`:

```js
import { type someType, someFunction } from "someModule";
 
someFunction();

export { type someType, someFunction };
```

Enabling the `isolatedModules` tsconfig option in VSCode, it seems these files would need to adjusted:

```
Found 26 errors in 6 files.

Errors  Files
     9  src/vs/base/common/amd.ts:57
     4  src/vs/base/node/processes.ts:14
     1  src/vs/workbench/contrib/accessibility/browser/accessibilityConfiguration.ts:636
     1  src/vs/workbench/contrib/inlineChat/common/inlineChat.ts:172
     8  src/vs/workbench/contrib/performance/browser/perfviewEditor.ts:331
     3  src/vs/workbench/contrib/tasks/common/taskService.ts:18
```

**Comment by jrieken** [comment]
We reverted this because we learnt, albeit very late, that it has disabled inlining of const enums
