### ISSUE TITLE
Coverage disappears when tests run through test explorer

### ISSUE THREAD

**Issue by MarkusAmshove** [microsoft/vscode#212805]
Does this issue occur when all extensions are disabled?: Yes/No
No (because coverage is 

- VS Code Version: 1.88.1 and 1.90 insiders
- OS Version: SLED 15 and Windows 10

Steps to Reproduce:

I've developed an extension that uses the new coverage API from 1.88 and I get the following problem:

- When the coverage profile is run through the test explorer, then the coverage data is appearing for very short time before it disappears

![coverage-flashing](https://github.com/microsoft/vscode/assets/2401875/2ef9675b-0e00-42c6-9e78-473f5ba7c9af)

- When the coverage profile is run through a custom command of mine, then the coverage will remain available

![coverage-staying](https://github.com/microsoft/vscode/assets/2401875/a5446cb5-cfed-4c35-b514-f0515a907178)

I've made sure to debug the input parameter to the `runHandler` in both cases and they're both identical.

The only difference I can see is the callstack in case 1 (explorer):
![CallstackExplorer](https://github.com/microsoft/vscode/assets/2401875/adf81c0f-4878-4771-858f-69ca61880bb2)

vs case 2 (command):
![CallstackCommand](https://github.com/microsoft/vscode/assets/2401875/5cfb158a-49a5-44ed-91e3-df09f033c3fa)

When I set a breakpoint at the very last curly brace of my run handler, then the coverage will stay until somewhere in the callstack which I can't look into:

![coverage-halt](https://github.com/microsoft/vscode/assets/2401875/de30b1f1-6b21-4d6a-92d3-a4b1dd3d7116)

I don't know what I can still try out to resolve this issue.
The coverage is added correctly, as it stays when the program halts and also stays forever when executed through the code lens command.

**Comment by connor4312** [comment]
Are you able to share the source code of your extension so I can look into this a bit?

**Comment by MarkusAmshove** [comment]
While creating a small repro extension, I noticed that I can find the coverage of the run initiated through the text explorer through the `Test Results` view:

![test-results](https://github.com/microsoft/vscode/assets/2401875/84eda34e-871a-4bbc-89b7-a9c61ad32a63)

While this doesn't explain why the coverage is appearing for a split second before closing itself again, using the command `testing.openCoverage` shows a message that no coverage data is available:

![nocoverage](https://github.com/microsoft/vscode/assets/2401875/1a4b5a14-89f1-44c9-8b5a-2ac9cdd24c3f)

My settings.json is the following in the tests:

```
{
    "git.openRepositoryInParentFolders": "never",
    "workbench.startupEditor": "none",
}
```

**Comment by connor4312** [comment]
I see that you have duplicate test runs. This is probably because you're creating a separate TestRunRequest rather than what VS Code provides to you. I recommend not doing this, but this behavior should also be fixed with https://github.com/microsoft/vscode/pull/235758

**Comment by MarkusAmshove** [comment]
Thank you, the hint with the separate `TestRunRequest` was the issue that I didn't find myself. I cloned the request that was passed to me and I don't know why.
Using the original request works as expected :-)
