### ISSUE TITLE
Revert single change from diff view

### ISSUE THREAD

**Issue by tamlyn** [Microsoft/vscode#21299]
When viewing the diff of a modified file against the most recent repository version, I would like to be able to revert (i.e. `git checkout -p`) individual changes one at a time. 

For example in WebStorm I can click the little chevrons next to the change to apply it to the other side:

<img width="496" alt="screen shot 2017-02-23 at 16 35 50" src="https://cloud.githubusercontent.com/assets/115310/23269433/7ae4b02a-f9e8-11e6-9931-33700cba45bc.png">

This is somewhat related to #10782 on the functionality side and to #5770 on the UI side.

**Comment by roblourens** [comment]
This is implemented if you open a diff view, click the `...` button, and select "Revert selected lines". Better UI is tracked in those other issues though.

**Comment by tamlyn** [comment]
Sounds great but I can't see it :(

1. Make some changes to a tracked file
2. Click on <kbd>Switch to Changes View</kbd> icon in top right of editor pane
3. Select the changed lines
4. Click on <kbd>...</kbd> icon in top right of diff pane
5. I see <kbd>Stage Selected Lines</kbd> but nothing about reverting

Where am I going wrong? Using v1.9.1.

**Comment by roblourens** [comment]
Oh sorry this is only in 1.10, the insiders build. It will be released this week. I was thinking it was in 1.9 too.
