### ISSUE TITLE
Hovers appear too quickly when debugging

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#212924]
I know we tuned this at some point. When I hover while debugging, the hover appears immediately with almost no delay, so it tends to get in the way under my mouse.

![Recording 2024-05-16 at 11 51 16](https://github.com/microsoft/vscode/assets/323878/72c074fd-de4f-4663-ba70-2cc24f6e2eb3)

**Comment by roblourens** [comment]
Maybe it's hard to see with the low framerate gif

**Comment by connor4312** [comment]
Hm, I've not changed this recently, but I know there have been other hover refactors that might have affected this.

**Comment by connor4312** [comment]
I don't repro this, what do you have `editor.hover.delay` set to?

**Comment by roblourens** [comment]
I don't have it customized. I'll see whether it's different with your change
