### ISSUE TITLE
Visual Studio code sidebar Vertical guideline (customize sidebar)

### ISSUE THREAD

**Issue by Modarresi** [Microsoft/vscode#21295]
- VSCode Version: 1.7.2
- OS Version: windows 7

Steps to Reproduce:

I want vertical guideline on sidebar (for file and folders) like netbeans.
any issue for that?

![brzbe](https://cloud.githubusercontent.com/assets/12231201/23269034/896c8cb4-fa04-11e6-8b64-0dadcfe54f95.png)

I asked it on <a>http://stackoverflow.com/questions/41898245/visual-studio-code-sidebar-vertical-guideline-customize-sidebar</a>.
but nothing.

**Comment by roblourens** [comment]
I don't known of an existing request. By the way, 1.7.2 is an old version, we're about to ship 1.10. You should consider updating :)

**Comment by kaiwood** [comment]
Dup is here: https://github.com/Microsoft/vscode/issues/17777

**Comment by roblourens** [comment]
Thanks @kaiwood

**Comment by cosmoKenney** [comment]
Both this and the duplicate #17777 were closed, so I guess this is dead. I'm pretty sure there was an update to the three recently, but it would be nice if there were a config value to increase the indent. I don't really need tree lines, but more indent would be great.
