### ISSUE TITLE
Editing TSX randomly makes the --type=extensionHost process use 100% CPU

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#21292]
- VSCode Version: 1.10-Insiders 0b27b5
- OS Version: windows 10 x64

![image](https://cloud.githubusercontent.com/assets/461084/23266094/7f777a96-f9c5-11e6-8f6e-3d51f74acf07.png)
![image](https://cloud.githubusercontent.com/assets/461084/23266109/8956f2a8-f9c5-11e6-9636-3f91f116670b.png)

```tsx
import React from 'react'
import {
  View,
  Button,
  TextInput,
  Picker,
  StyleSheet,
  ScrollView,
  Text,
  TouchableOpacity,
  Alert
} from 'react-native'
import t, { FormComponent } from 'tcomb-form-native'
import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view'

const Model = t.struct({
  cep: t.String,
  neighborhood: t.String,
  name: t.String
})

const Form = t.form.Form

const styles = StyleSheet.create<any>({
  form: {
    padding: 15
  },
})

export default class extends React.Component<any, any> {
  constructor(props) {
    super(props)

    this.state = this.initialState()
  }

  initialState() {
    return {
      form: {
        cep: this.props.defaultCep,
        name: null,
        neighborhood: null,
      },
      disabled: true
    }
  }

  render() {
       return (
      <KeyboardAwareScrollView style={styles.form} keyboardShouldPersistTaps="always">
        <Form
          ref="form"
          type={Model}
          value={this.state.form}
          onChange={(o) =>{ }}
        />

        <View style={{marginVertical: 30}}>
          <Button title="Cadastrar logradouro" disabled={this.state.disabled} onPress={() => {
            Alert.alert('Sucesso', 'Rua cadastrada')

            this.setState(this.initialState())
          }} />
        </View>
      </KeyboardAwareScrollView>
    )
  }
}
```

Edit `<KeyboardAwareScrollView ` to `<View`, then edit any children (Form, View) leaving the `</KeyboardAwareScrollView>` opened, then change it back to `<KeyboardAwareScrollView`, after a few times, the process will start using 100% CPU. closing the editor won't close the child ` --type=extensionHost` process, and typing on the editor becomes sluggish, all Typescript suggestions stop working

**Comment by pocesar** [comment]
![image](https://cloud.githubusercontent.com/assets/461084/23269230/a302555e-f9ce-11e6-8e42-904121db3912.png)

![image](https://cloud.githubusercontent.com/assets/461084/23269269/cb991f2a-f9ce-11e6-9e6c-1937eaccbae5.png)

**Comment by pocesar** [comment]
This one became a blocker, everytime when dealing with children of React Native elements, it happens. having to restart the editor every 10 minutes

**Comment by mjbvz** [comment]
@pocesar Does this still happen if you disable all extensions?

**Comment by pocesar** [comment]
Yes, but it's harder to reproduce, so some pipes might being clogged

**Comment by mjbvz** [comment]
@pocesar So do you still see this after disabling all extensions?

If you do, please try collecting a trace of the TypeScript Server when this occurs. Here's information on to do this using the TSS_LOG environment variable: https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29#logging

From a command line, run:

```
set TSS_LOG=-level verbose -file c:\tmp\tsserver.log
code 
```

Reproduce the problem in VSCode and then share the `c:\tmp\tsserver.log` file

Let me know if you have any questions about this.

Thanks

**Comment by pocesar** [comment]
@mjbvz Yes, I managed to make the external process hang ONCE with all the extensions disabled, but it was a crazy non-sense typing (which I guess wouldn't apply in normal conditions). I couldn't reproduce it again with disabled extensions, but could reproduce it everytime with both extensions (either both enable, or either one, `Auto close tag` and `React Native Tools`)

**Comment by shakram02** [comment]
I have the same problem on Ubuntu Linux, vs-code version:`1.10.1-1488415350`
Typing Angular2 code causes the problem, when this happens, intellisense stops completely ( just displays Loading... )

![image](https://cloud.githubusercontent.com/assets/10996982/23538666/b47a6e4c-ffdd-11e6-9f81-bae5ee64e19e.png)

**Comment by pocesar** [comment]
my insiders, when having TS files open, usually keep a lowish but constant CPU usage, but when using many editors opened at the same time, the system really take a hit

![image](https://user-images.githubusercontent.com/461084/27237950-62477a90-52a1-11e7-867d-2fd82c54da64.png)

this screenshot is when "idle", not typing or doing anything

**Comment by pocesar** [comment]
this seems to have been fixed in latest insiders, although TS in watch mode always make the shell responsiveness inside the editor worst

**Comment by mjbvz** [comment]
Ok, thank you for the followup. I'm not sure what fixed this on the TS side but I'm glad you are no longer seeing this issue
