### ISSUE TITLE
Grammar checking does not work properly in non default user code snippets

### ISSUE THREAD

**Issue by CrystalloidIron** [microsoft/vscode#212903]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: Windows_NT x64 10.0.19045
- Electron: 28.2.8
- ElectronBuildId: 27744544
- Chromium: 120.0.6099.291
- Node.js: 18.18.2
- V8: 12.0.267.19-electron.0

1. 当我想创建一个新的用户配置并为其添加用户代码片段时，我发现为某个语言而创建的代码片段因其后缀名为‘.json’，即使在vscode右下角的语言模式中修改了选项为‘Code snippets’，仍然会被以JSON方式检查代码并报错，并不能如预设那般被以JSONC方式检查。即使已经将所有的拓展关闭，将项目文件夹也关闭，仍然会出现该情况。
<img width="723" alt="屏幕截图 2024-05-16 224348" src="https://github.com/microsoft/vscode/assets/117372044/178f1836-412d-4de2-bb2a-a7d40b4a6c1b">

![image](https://github.com/microsoft/vscode/assets/117372044/72ee5c08-aafc-45a6-b3ad-3a55c38ae6b0)

**Comment by jrieken** [comment]
* lacks copy-paste friendly sample
* steps
* english description

**Comment by RedCMD** [comment]
you should use the file extension `.code-snippets`, not `.json`
