### ISSUE TITLE
VSCode fails to recognize workspace TypeScript SDKs with Yarn PnP setup

### ISSUE THREAD

**Issue by RajaJaganathan** [microsoft/vscode#212971]
Type: <b>Bug</b>

**Description:**
I've been struggling with this issue for more than a year. Despite reinstalling VSCode multiple times, I still cannot get it to work properly with Yarn PnP and TypeScript. I desperately need help to resolve this issue.

Repository to Reproduce the Issue:
I'm using the following repository to reproduce the issue: typescript-node-yarn-pnp-boilerplate. This repository is set up with Yarn PnP, TypeScript, and VSCode, but I've never been able to use the "Workspace TypeScript SDKs".

**Steps to Reproduce:**

Clone the repository: git clone https://github.com/pomSense/typescript-node-yarn-pnp-boilerplate
Navigate to the project directory: cd typescript-node-yarn-pnp-boilerplate
Install dependencies: yarn install

Follow the steps outlined in the [Yarn documentation](https://yarnpkg.com/getting-started/editor-sdks#vscode) for setting up editor SDKs for VSCode: Yarn Editor SDKs

**Expected Behavior:**
VSCode should recognize and use the Workspace TypeScript SDKs as configured by Yarn PnP.

**Actual Behavior:**
VSCode does not recognize or use the Workspace TypeScript SDKs. IntelliSense and other TypeScript-related features do not work as expected.

VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin arm64 23.4.0
Modes:

**Log:** 

2024-05-17 20:32:40.751 [info] Starting TS Server
2024-05-17 20:32:40.751 [info] Using tsserver from: /Users/raja.j/Documents/learn_pkg/typescript-node-yarn-pnp-boilerplate/.yarn/sdks/typescript/lib/tsserver.js
2024-05-17 20:32:40.751 [info] <syntax> Forking...
2024-05-17 20:32:40.751 [info] <syntax> Starting...
2024-05-17 20:32:40.751 [info] <semantic> Forking...
2024-05-17 20:32:40.751 [info] <semantic> Starting...
2024-05-17 20:32:40.942 [error] TSServer exited. Code: 1. Signal: null

![Screenshot 2024-05-17 at 8 48 27 PM](https://github.com/microsoft/vscode/assets/1519011/906ca8f0-46f3-476d-8fcb-14df4181e060)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 15, 19|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipfs|arc|3.0.0
vscode-eslint|dba|2.4.4
prettier-vscode|esb|10.4.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
chatpanelt:31048053
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31049070
fchga941:31046352
pythonprt:31047983
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by mjbvz** [comment]
This is a bug with yarn: https://github.com/yarnpkg/berry/issues/6270
