### ISSUE TITLE
Comment text cut off in comments panel

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#212956]
There is a `...` much earlier than necessary:
![Image](https://github.com/microsoft/vscode/assets/9205389/e58c68cf-6583-49ec-a650-1e28d5d7b262)

**Comment by connor4312** [comment]
There's a bit more space but it's still not as wide as it could be. 


![image](https://github.com/user-attachments/assets/936ace65-c3e3-475b-ab30-dd8471963857)
