### ISSUE TITLE
Code blocks in Markdown render poorly

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode#212988]
## Environment data

-   VS Code version: 1.89.1
-   Jupyter Extension version (available under the Extensions sidebar): v2024.3.1
-   Python Extension version (available under the Extensions sidebar): v2024.4.1
-   OS (Windows | Mac | Linux distro) and version: Fedora 40
-   Python and/or Anaconda version: 3.11
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

When a code block (here, Python) is added to a markdown cell using triple quotes, the block is formatted as code with appropriate language coloration when specified. Here is a working example in a browser-based Jupyter notebook:

![image](https://github.com/microsoft/vscode-jupyter/assets/81476/9ca7bd3a-b779-4e85-9227-f71011999474)

## Actual behaviour

In VSCode, the block is not well defined and does not include language coloration despite the language being specified with the code block. It looks really terrible, almost as if inline code formatting is being used on the block. If  this is the case, it is not the correct encoding.

Note that this is *independent* of which theme is being used in VSCode. They all look similar to this, but using the dominant colors of the theme being used.

![image](https://github.com/microsoft/vscode-jupyter/assets/81476/24148faf-41e8-421b-a89a-6ba3085bc5e9)

## Steps to reproduce:

Create a code block inside of a markdown cell using the triple quote notation (and language label, optionally)

**Comment by fonnesbeck** [comment]
This occurs with any notebook containing markdown code blocks, but [here is a simple example](https://drive.google.com/file/d/1YpUC0mATRwOJHkC4e9CySvtPOHr8a4ty/view?usp=sharing).

**Comment by mjbvz** [comment]
Thanks. Looks fine to me tho:

![Image](https://github.com/microsoft/vscode/assets/12821956/3fafecc9-1c55-418d-b5d4-e1aba24f6d44)

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by fonnesbeck** [comment]
Thank you. It looks like a Markdown preview extension was causing this. Sorry for the trouble!
