### ISSUE TITLE
no popup for private key passphrase when trying to publish new git branch

### ISSUE THREAD

**Issue by X-Dean** [microsoft/vscode#212965]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.86.2 (user setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Publish new branch to a repo using ssh and private key with passphrase

**Comment by lszomoru** [comment]
@X-Dean, does VS Code show the quick input to enter your passphrase for other git operations?

**Comment by X-Dean** [comment]
> @X-Dean, does VS Code show the quick input to enter your passphrase for other git operations?

No, it does not show quick input in any git operation

**Comment by X-Dean** [comment]
> @X-Dean, that seems to indicate that authentication request never reaches VS Code. VS Code is last in the git authentication pipeline so I was wondering if you have anything configure in your git config to handle SSH authentication requests.

Just retried so to give the correct answer.

```
[sysadmin@laptop:~/az_devops/elastic-cloud-service]$ eval `ssh-agent -s`
Agent pid 6853
[sysadmin@laptop:~/az_devops/elastic-cloud-service]$ ssh-add ~/.ssh/my.private
Enter passphrase for /home/sysadmin/.ssh/my.private:
Identity added: /home/sysadmin/.ssh/my.private (/home/sysadmin/.ssh/my.private)
[sysadmin@laptop:~/az_devops/elastic-cloud-service]$ pidof ssh-agent
6853
```
**VS Code**
After enabling ssh-agent I tried to push from VS Code and the issue persists and keep staying at this stage (it does commit):
![image](https://github.com/microsoft/vscode/assets/26165963/88bb3d70-161f-4e20-b522-27b0f1de237a)

**Then from terminal**:
```
[sysadmin@laptop:~/az_devops/elastic-cloud-service]$ git status
On branch feature/az_aad_groups
Your branch is ahead of 'origin/feature/az_aad_groups' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
[sysadmin@laptop:~/az_devops/elastic-cloud-service]$ git push
Warning: Permanently added the RSA host key for IP address 'x.x.x.x' to the list of known hosts.
Enumerating objects: 21, done.
Counting objects: 100% (21/21), done.
Delta compression using up to 8 threads
Compressing objects: 100% (14/14), done.
Writing objects: 100% (15/15), 1.51 KiB | 258.00 KiB/s, done.
Total 15 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Analyzing objects... (15/15) (100 ms)
remote: Validating commits... (1/1) done (0 ms)
remote: Storing packfile... done (85 ms)
remote: Storing index... done (79 ms)
To ssh.dev.azure.com:v3/xxx/xxx/elastic-cloud-service
   9d4c7ef..8b2bc4a  feature/az_aad_groups -> feature/az_aad_groups
```

**Comment by lszomoru** [comment]
@X-Dean, thanks for the additional details. Based on the information that you have shared you have added your SSH key with the passphrase to the ssh agent so this should have worked seamlessly from VS Code. You are running version 1.86 so I was wondering if you could install the latest version? After you install the latest version, please go through these steps:
1. Close all instances of VS Code
2. From a command prompt window run set GIT_TRACE=1 && code
3. Open the integrated terminal and run `git pull`. You should see detailed logs related to SSH auth
4. Click the "Sync Changes" button, or invoke the "Git: Pull" command.
5. Open the https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window and look at the logs. 

We should try to compare the logs generated by step 3) and step 4). Please feel free to share them.

**Comment by X-Dean** [comment]
I think i understood where the issue is!

After I tried git pull from integrated terminal it worked, also from VS Code git GUI. 

```
git pull
Warning: Permanently added the RSA host key for IP address 'x.x.x.x' to the list of known hosts.
Already up to date.
```
But the prompt is like this:
```
[root@laptop:~/az_devops/elastic-cloud-service/testing/elastic-cloud-service]root@laptop ~/az_devops/elastic-cloud-service/testing/elastic-cloud-service (feature/az_aad_groups)$
````
VS Code uses "root user" to perform tasks in wsl (at least in my case) and it was needed to perform any git ssh command towards repo to add IP at known_hosts and maybe start serving ssh-agent.

Can I change this to use the user which invokes code from terminal ?

**Comment by lszomoru** [comment]
@X-Dean, glad that you were able to get to the bottom of this. From the data that you have shown I see two different WSL users (`sysadmin`, and `root`). @aeschli, how does VS Code pick a user within WSL to use when connecting to WSL?

**Comment by X-Dean** [comment]
@lszomoru thanks for your support!

**Comment by aeschli** [comment]
The WSL extension runs WSL with its default user.  See https://learn.microsoft.com/en-us/windows/wsl/basic-commands#change-the-default-user-for-a-distribution on how to change that user.

**Comment by X-Dean** [comment]
As i have exported and imported this distribution a couple of times there was not possible to do it by pwsh, but I could do it from wsl.conf. Now from embedded terminal in VS Code the user is correctly selected.
Thanks for your support!

**Comment by lszomoru** [comment]
Thank you @aeschli! @X-Dean, glad to hear that everything is working as expected.
