### ISSUE TITLE
The TS/JS feature crashes without any reason I guess...

### ISSUE THREAD

**Issue by spark15** [microsoft/vscode#212947]
Type: <b>Bug</b>

Info 0    [15:37:37.375] Starting TS Server
Info 1    [15:37:37.375] Version: 5.4.5
Info 2    [15:37:37.375] Arguments: C:\Users\Ritch\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\Ritch\Documents\GitHub\BitCoding-finalproject-back\.yarn\sdks\typescript\lib\tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\Ritch\AppData\Local\Temp\vscode-typescript\f26fdf56ee121fbb4386\tscancellation-8b780949653a97dc03cf.tmp* --logVerbosity verbose --logFile c:\Users\Ritch\AppData\Roaming\Code\logs\20240517T153729\window1\exthost\vscode.typescript-language-features\tsserver-log-R8JPGn\tsserver.log --locale en --noGetErrOnBackgroundUpdate --canUseWatchEvents --validateDefaultNpmLocation --useNodeIpc
Info 3    [15:37:37.376] Platform: win32 NodeVersion: v18.18.2 CaseSensitive: true
Info 4    [15:37:37.376] ServerMode: undefined hasUnknownServerMode: undefined
Info 5    [15:37:37.381] Binding...
Info 6    [15:37:37.405] FileWatcher:: Added:: WatchInfo: c:\Users\Ritch\Documents\GitHub\BitCoding-finalproject-back\.pnp.cjs 250 undefined WatchType: Config file

It's all I got from log file. I don't know where it crashes. I already clean installed it and moved another machine. 

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.80GB (15.64GB free)|
|Process Argv|--crash-reporter-id 35fe55f9-3b0c-43c8-8ac1-873ca1c5f773|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipfs|arc|3.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vswsl492:30256859
vstes627:30244334
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31049070
a69g1124:31046351
pythonprc:31047982
dwnewjupyter:31046869
fa862199:31048878

```

</details>

**Comment by spark15** [comment]
I downgraded typescript on yarn. It works well with 5.3.3, but it doesn't work for 5.4.5.

**Comment by spark15** [comment]
What I only did is

yarn init -2
yarn add -D typescript@5.4.5
yarn dlx @yarnpkg/sdks vscode
touch index.ts

I tested everything including clean install(even os), and disabling all extensions.

**Comment by mjbvz** [comment]
This is caused by yarn: https://github.com/yarnpkg/berry/issues/6270
