### ISSUE TITLE
task spinner in status bar doesn't stop

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#21290]
Insiders build.

- open 'vscode' workspace in VS Code
- open Output console for tasks
- run 'Unit Tests' launch config

Observe: after the 'electron' task has finished (and the debug sessions starts), the task spinner in the status bar continues to spin. This spinning continues even after the tests have terminated.

If I run the 'electron' task directly, the spinner stops properly. 

/cc @isidorn @alexandrudima

**Comment by alexandrudima** [comment]
fyi @joaomoreno -- d871d315c8f7438ba5b9d13098d0e27cd3af276e

**Comment by dbaeumer** [comment]
This works for me on latest (I have to say I rewrote quite some code in the task area to make it API) which also removes some state from the  output channel runner which could have cause this.

I will close. Please reopen if you sill see this on latest

![cast](https://cloud.githubusercontent.com/assets/1931590/24292173/7b6544aa-108c-11e7-9da2-e6c2c366ad53.gif)

**Comment by alexandrudima** [comment]
@dbaeumer This was reproducible only on linux/mac, as there is a task that **deletes** files that are being used. i.e. it is expected that the task fails and terminates on Windows (I think)... Reproducing was very difficult, it involved deleting the `.electron` folder and clicking play multiple times.

**Comment by dbaeumer** [comment]
@alexandrudima thanks. Wasn't clear to me from the description. Will retry with a Linux machine.
