### ISSUE TITLE
Shared process should have a clone of all profile storages

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#212904]
Discovered from https://github.com/microsoft/vscode/issues/212664

At present when syncing a profile, Settings gets snapshot of each profile storage from main and discards the snapshot as soon as the sync is finished. On an average, settings sync syncs all profiles once per 5 minutes. This means, every 5 minutes settings sync reads all profiles storages from main. 

Ref: https://github.com/microsoft/vscode/blob/da020b932a9ccb89b703b7e03f10633c96f25bb3/src/vs/platform/userDataProfile/common/userDataProfileStorageService.ts#L72-L74

Instead

- get profile storage from main when needed for the first time
- from there on sync the storage from main using listeners - incrementally update the profile storage

**Comment by sandy081** [comment]
@bpasero What is your opinion?

**Comment by bpasero** [comment]
Sounds good 👍
