### ISSUE TITLE
program parameter in launch.json for a node app changes 'commander' to 'command:r' and doesn't find program

### ISSUE THREAD

**Issue by commanderturner** [Microsoft/vscode#21297]
- VSCode Version:Version 1.10.0-insider
- OS Version:Ubuntu 16.04

Steps to Reproduce:

1.hit F5 to launch node program
2.error: 
`Attribute 'program' does not exist ('/home/command:rturner/development/....`
note:  my ubuntu username contains the word 'commander'
launch.configurations has the following entry:

```json
       {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/Server/Server.js",
            "sourceMaps": true
        }
```

tried hardcoding `${workspaceRoot}` to `'/home/commanderturner/development/`
but same error appeared
If I type `node Server/Server.js` in terminal the program starts fine.
previously this has been working fine, so think it is a recent change to insiders build.

**Comment by isidorn** [comment]
Nice catch, thanks commander

**Comment by weinand** [comment]
@isidorn make sure that 'command.' is only replaced in variables. Yesterday I noticed the 'commander' was replaced everywhere.

**Comment by isidorn** [comment]
Agree that is much better and more elegant fix

**Comment by weinand** [comment]
And it is a correct fix :-)

**Comment by isidorn** [comment]
Yes :)

**Comment by commanderturner** [comment]
Cheers guys that was a speedy turnaround :)
