### ISSUE TITLE
Cannot customize (.venv) displaying in my own terminal prompt

### ISSUE THREAD

**Issue by p-i-** [microsoft/vscode#212920]
Type: <b>Bug</b>

Simply create a minimal .bash_profile `PS1='>'` and launch VSCode's Integrated Terminal (supposing it's set to BASH).

There's a `"(.venv)"` displaying.

I'd like to control how it displays. i.e. choose the colour, and use a relative path (relative to pwd). And _where_ it displays in the prompt.

But I can't get at it -- it's added after .bash_profile is executed.

I can see VSCode inserts a hook in PROMPT_COMMAND.

But I've looked through settings and can't find documentation.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:32.757Z)
OS version: Darwin arm64 23.4.0
Modes:

**Comment by meganrogge** [comment]
if you want to control this, you should disable shell integration, `terminal.integrated.shellIntegration.enabled`
