### ISSUE TITLE
focus indication has some room for improvement on mac

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2129]
:scream: 

![screen shot 2016-01-20 at 17 30 32](https://cloud.githubusercontent.com/assets/1794099/12455349/952e2e1c-bf9b-11e5-936e-270c96fd1f7c.png)

**Comment by bpasero** [comment]
@jrieken hm I wonder if this is a CSS caching issue and you get the native OS outline instead of the configured one. Is this a built version or out of dev?

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/12456655/200c5874-bfa1-11e5-8a4e-de66a7e95824.png)

**Comment by jrieken** [comment]
it is out of dev - I try again recompiled

**Comment by jrieken** [comment]
better, but still some clipping

![screen shot 2016-01-20 at 18 23 54](https://cloud.githubusercontent.com/assets/1794099/12457095/02ce4b3a-bfa3-11e5-9978-2cb8abb43f71.png)

**Comment by bpasero** [comment]
@jrieken with clipping you mean that the box does not appear to have the same width on all edges?

**Comment by jrieken** [comment]
yes
