### ISSUE TITLE
Code not highlighting based on syntax

### ISSUE THREAD

**Issue by Fepozopo** [microsoft/vscode#212940]
ADD ISSUE DESCRIPTION HERE
All code is in all white text.

Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
Embedder: codespaces

**Comment by RedCMD** [comment]
what language?
screenshot?
`editor.action.inspectTMScopes`
