### ISSUE TITLE
Toggle Word Wrap should not write to user settings

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#21291]
The Toggle Word Wrap action writes `editor.wordWrap` to user settings, but there are multiple issues:

* if the workspace contains a setting for `editor.wordWrap`, the workspace setting will override the user setting. 

* if there is a language specific setting (as we have for markdown), it will override the user setting.

These cases make the action appear as a no-op.

Related: #19842, #20174, #20675

**Comment by alexandrudima** [comment]
We have decided in today's standup that for 1.10 , we make Toggle Word Wrap "in memory" again. i.e. it will not write to user settings, and it will apply only to the current editor.

It also means that the wrapping is highly transient. i.e. any touch of the settings.json will lead to it being lost. This is being tracked in #21487

**Comment by alexandrudima** [comment]
The action now works exactly as it used to work prior to 1.9

**Comment by bpasero** [comment]
Verified. Just fyi ever since we have mode specific settings we loose the wordWrap setting much more often than by triggering a write to settings (e.g. zoom). I hope this does not cause more confusion than before.

**Comment by bpasero** [comment]
@GregCaldock works for me though on macOS, what kind of settings do you have defined?

**Comment by GregCaldock** [comment]
@bpasero I'm using Linux Mint 18.1 Cinnamon 64-bit. After updating I had "editor.wordWrap": "off" - I removed that and commented out my other settings but it made no difference word wrapping is constant and I cannot view anything 'un-wrapped'

**Comment by bpasero** [comment]
@GregCaldock does it also reproduce when you explicitly pick the action `View | Toggle Word Wrap`

Here is how I try:

![panel-red](https://cloud.githubusercontent.com/assets/900690/23369219/e81c4a06-fd10-11e6-9e42-2c7b8ae1691a.gif)

**Comment by GregCaldock** [comment]
@bpasero neither hitting Alt-z nor selecting View -> Toggle Word Wrap have any effecy.

Both worked fine in 1.8

In 1.9 and early versions of 1.10 I could turn off wrapping by setting editor.wordWrap to true and editor.wrappingColumn to -1 but I had to do this by manually changing the the settings file as Alt-z and using the menu would change the editor.wordWrap to true or false but that wouldn't necessarily change the the actual wrapping as that seemed to rely on editor.wrappingColumn settings.

**Comment by bpasero** [comment]
@GregCaldock I suggest to open a new issue on it
