### ISSUE TITLE
Need to improve the syntax highlighting in Rust

### ISSUE THREAD

**Issue by D101101** [Microsoft/vscode#2130]
Syntax highlighting for Rust works well, but in some places it is clearly not completed yet.
![_2016-01-20_19-25-56](https://cloud.githubusercontent.com/assets/8783865/12456219/d59b9d0e-bfaf-11e5-87d0-4bc0bae63908.png)
![_2016-01-20_20-00-12](https://cloud.githubusercontent.com/assets/8783865/12456383/971635ca-bfb0-11e5-89cd-75d189e8d2b1.png)

**Comment by crumblingstatue** [comment]
I also find it confusing that keywords and type names share the same highlighting color.

**Comment by aeschli** [comment]
This issue was moved to zargony/atom-language-rust#68

**Comment by crumblingstatue** [comment]
@aeschli 
What is the rationale of moving this issue to atom-language-rust?

Does vscode use the atom-language-rust package for Rust syntax highlighting? That doesn't seem to be the case from what I see.

In Atom, the type names and keywords actually have different colors, so this is a vscode specific issue.

**Comment by crumblingstatue** [comment]
To clarify what I mean, I specifically mean user defined types/traits in vscode have the same colors as keywords.

This is how it looks in Atom:
![](http://i.imgur.com/optYorK.png)

And this is how it looks in vscode:
![](http://i.imgur.com/7JNwm6A.png)

**Comment by aeschli** [comment]
In VSCode we use the grammar from atom-language-rust. When you write that keywords and type names share the same highlighting color then this has to do with the grammar. The grammar defines what scopes to return for each token.

In this example:
```rust
fn main(file: &PathBuf) {
    let str: &str = "str"
}
```
`fn` get the `keyword` scope (which makes sense), but `PathBuf` gets the `class.std.storage` scope which is unusual. 

That said, what scopes are the correct ones to use is not well defined (see my comment in https://github.com/Microsoft/vscode/issues/2058). How it eventually colored depends on the theme. It might work well for Atom actually if they use a customized theme, so you are right, moving this to Atom might not be the right way.
Also this issue contains multiple issues that all need to be looked at separately.
I reached out to the authors of 'rusty code' to see if they would like to help. We lack 'Rust' expertise in the VSCode core team.

**Comment by Tyriar** [comment]
There may be an issue on our end, it seems to behave differently on Atom (1.3.3 & 1.4.3, language-rust 0.4.5):

![rust](https://cloud.githubusercontent.com/assets/2193314/12811870/04629c34-cae4-11e5-97e7-757bcac77fca.png)

VSCode (0.10.6 & master):

![rust_vs](https://cloud.githubusercontent.com/assets/2193314/12811899/2b463694-cae4-11e5-9abd-1cbb82599f1e.png)
