### ISSUE TITLE
VS Code auto save on window change doesn't work with AltTab on Mac

### ISSUE THREAD

**Issue by QumiQumi** [microsoft/vscode#213062]
Does this issue occur when all extensions are disabled?: Yes

With a standard window change, autosave works correctly, but when using AltTab the file is not saved on Window change or on Focus change. I've created an issue in AltTab repo https://github.com/lwouis/alt-tab-macos/issues/3367, but nothing they could do with this. Could you please check this out?
![image](https://github.com/microsoft/vscode/assets/43902909/b60bf455-7f2b-4ad0-a23b-2f5de81ae516)
![image](https://github.com/microsoft/vscode/assets/43902909/4d6db0a7-9804-413a-a182-a1012b0d85f8)

- VS Code Version: 1.89.1
- OS Version: macOS Sonoma 14.4.1
- AltTab version: 6.69.0

Steps to Reproduce:

1. Go to 'Preferences -> Files: Auto Save -> On Window Change'
2. Add changes to any file
3. Alt tab to other window and back
4. File is still unsaved

**Comment by bpasero** [comment]
So this does not reproduce when you disable Alt-Tab and use macOS built-in window switching?

**Comment by QumiQumi** [comment]
Yes, with native window switching works just fine.
Pls, check last comments https://github.com/lwouis/alt-tab-macos/issues/3367 in this issue. AltTab developer said nothing they could do with this problem and advised me to ask VS code developers..

**Comment by bpasero** [comment]
We rely on this Electron event being fired: https://github.com/electron/electron/blob/main/docs/api/app.md#event-browser-window-focus to figure out that window focus changed.

The comment in https://github.com/lwouis/alt-tab-macos/issues/1663#issuecomment-1196996219 indicates that AltTab might be using a private API for focusing a window and probably we do not get the focus event from Electron then.

I suggest you change auto save to use `onFocusChange`.

I do not feel this is something VS Code can address, rather AltTab should fix.
