### ISSUE TITLE
Always show the copilot header buttons

### ISSUE THREAD

**Issue by madprops** [microsoft/vscode#213006]
Is there a way to make these buttons always visible?

It's especially bad because the git controls have a similar plus symbol.

I've confused them before and staged a file instead of opening a new copilot conversation.

![copilot234](https://github.com/microsoft/vscode/assets/206498/df6d6bbc-8c0e-4d3f-90a1-86476f445da6)

**Comment by roblourens** [comment]
No, they show on hover, that's just how these buttons work in vscode
