### ISSUE TITLE
Error while clicking on a file in report message in jupyter notebook

### ISSUE THREAD

**Issue by CatEek** [microsoft/vscode#213068]
While performing this sequence of actions :

open a remote connection in vscode to a linux machine
create a file in your home directory touch ~/test.txt
run a cell with print('~/test.txt')
click the link in the cell output

I keep getting Unable to open 'test.txt' error message

**Comment by amunger** [comment]
duplicate of https://github.com/microsoft/vscode-jupyter/issues/14562
