### ISSUE TITLE
Thoughts on how to do this:

### ISSUE THREAD

**Issue by indiasupoort** [microsoft/vscode#213000]
Thoughts on how to do this:
- Change test code to read real python environment
- Add test that verifies imports from the environment
- Update test action to install a module
- Run all test code with virtual environment

Maybe have a flag that only does this on CI? Otherwise local developer will have to run with an environment with those imports in it.

_Originally posted by @rchiodo in https://github.com/microsoft/pyright/issues/5990#issuecomment-1729993125_

**Comment by karthiknadig** [comment]
This looks like it was created in error from a discussion in pyright.
