### ISSUE TITLE
Hyperlinks from commands in the terminal do not work

### ISSUE THREAD

**Issue by sias32** [microsoft/vscode#213022]
Type: <b>Bug</b>

I was interested in being able to open files quickly via terminal, I found that the `ls` and `eza` commands have a **--hyperlink** parameter that inserts links in the filenames. When I try to click on them, nothing happens

For testing I used vscode insider where I installed only the tunnels extension. Connected to linux on debian12, tried in bash and zsh terminal

**EZA**:
When using the `eza --hyperlink` command, a list of files and folders appears with links like `file:///home/user/[file.txt|dir]`, nothing happens when I try to click on them

**LS**
When using the `ls --hyperlink` command, a list of files and folders appears with links like `file://<server>/home/user/[file.txt|dir]`, nothing happens when you try to click on them

Out of interest, I decided to try writing the links to the terminal with the `echo` command, and then the file opens in the current window without any problems

VS Code version: Code - Insiders 1.90.0-insider (f209ce35ef894bd32c12057724e8d1f1139c433f, 2024-05-17T17:49:32.956Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.1.0-20-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (22.92GB free)|
|Process Argv|--crash-reporter-id d1961ca4-6018-4e57-9fa8-b63f691aa267|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|larionov-work|
|OS|Linux x64 6.1.0-20-amd64|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz (2 x 0)|
|Memory (System)|3.82GB (2.29GB free)|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
showvideot:31016890
chatpanelt:31014475
9c06g630:31013171
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by AntonioL** [comment]
Same problem here, I find that links are detected in the terminal but clicking over them does not do anything. Looks like a regression.

**Comment by pamelafox** [comment]
I am also experiencing what appears to be a regression in link clickability. 

My VS Code details:

Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:32.757Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.5.0


Screenshot:
![Screenshot 2024-06-03 at 4 52 38 PM](https://github.com/microsoft/vscode/assets/297042/847efba9-14f1-490f-996d-db80d7e17fd7)

Wait, maybe the keyboard shortcut changed? I just tried option+click and it did actually work. But I thought it was command+click before. Or some other click. I can't remember clicking option.

**Comment by Chealer** [comment]
@pamelafox are you confident your issue is the same? Do you also get different behaviors depending on how the link is generated?

@sias32 can you provide an example command you use for testing `echo`?

**Comment by pamelafox** [comment]
I've now trained myself to use option+click, so it's no longer an issue for me. I still think it was cmd+click before, but I might be imagining things.

**Comment by Chealer** [comment]
@pamelafox I don't know macOS and can't say if that's expected, but for sure your issue is different than the one this ticket tracks.

**Comment by sias32** [comment]
> @sias32 can you provide an example command you use for testing `echo`?

echo "file:///home/user/file.txt"

**Comment by Tyriar** [comment]
@pamelafox it's a little unintuitive, but the modifier changes based on the value of `editor.multiCursorModifier` to keep the open link modifier the same across editor+terminal.
