### ISSUE TITLE
Esc stolen by workbench.action.chat.stopListening

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#213017]
Type: <b>Bug</b>

I ccould not close inline chats or quick picks anymore.

Looks like `workbench.action.chat.stopListening` captured all esc shortcuts. I had used voice input during the session.

VS Code version: Code - Insiders 1.90.0-insider (f209ce35ef894bd32c12057724e8d1f1139c433f, 2024-05-17T17:53:51.447Z)
OS version: Darwin x64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (6.85GB free)|
|Process Argv|--log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
tsl-problem-matcher|amo|0.6.2
emojisense|bie|0.10.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.23.0
markdown-preview-github-styles|bie|2.0.4
markdown-yaml-preamble|bie|0.1.0
mermaid-markdown-syntax-highlighting|bpr|1.6.3
vscode-tailwindcss|bra|0.11.68
esbuild-problem-matchers|con|0.0.3
vscode-eslint|dba|2.4.4
kusto|don|0.4.4
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
codespaces|Git|1.16.22
copilot|Git|1.194.885
copilot-chat|Git|0.16.2024051702
copilot-nes|Git|0.0.1
remotehub|Git|0.63.2024051501
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.89.2024051504
headwind|hey|1.7.0
debug-tracker-vscode|mcu|0.0.15
peripheral-viewer|mcu|1.4.6
vscode-azureresourcegroups|ms-|0.9.0
vscode-docker|ms-|1.29.1
vscode-dotnet-runtime|ms-|2.0.5
debugpy|ms-|2024.7.11371017
isort|ms-|2023.13.11371020
python|ms-|2024.7.11371014
vscode-pylance|ms-|2024.5.101
jupyter|ms-|2024.4.2024042601
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
remote-containers|ms-|0.366.0
remote-ssh|ms-|0.112.2024051615
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
anycode|ms-|0.0.73
azure-repos|ms-|0.39.2024051501
cpptools|ms-|1.20.5
live-server|ms-|0.4.13
remote-repositories|ms-|0.40.0
remote-server|ms-|1.6.2024051509
vscode-github-issue-notebooks|ms-|0.0.130
vscode-markdown-notebook|ms-|0.0.26
vscode-selfhost-test-provider|ms-|0.3.25
vscode-speech|ms-|0.9.2024050912
vscode-typescript-next|ms-|5.5.20240505
prisma|Pri|5.14.0
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
kuskus-kusto-syntax-highlighting|ros|2.0.2
svg-preview|Sim|2.8.3
pdf|tom|1.2.2
vscode-mdx|uni|1.8.5
volar|Vue|2.0.10
gitblame|wad|10.11.0
markdown-all-in-one|yzh|3.6.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
vscaac:30438845
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialogc:30812479
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
showvideot:31016890
chatpanelt:31014475
f3je6385:31013174
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupyter:31046869
impr_priority:31052045
26j00206:31048877

```

</details>

**Comment by bpasero** [comment]
@digitarald are you certain its that command? It is only enabled when a voice chat session is active. When you set the log level to trace, please check what is printed when you trigger `Esc`:

```
TRACE KeybindingService#dispatch Escape [ Will dispatch command workbench.action.chat.stopListening ]
log.js:205 TRACE CommandService#executeCommand workbench.action.chat.stopListening
```

**Comment by digitarald** [comment]
Happened again on a different machines.

The main step of the STR seems to be using voice input (I mostly demo the hold down key usage)

Both times I did troubleshooting and it pointed to the stop listening command.

**Comment by bpasero** [comment]
@digitarald I need some steps to reproduce that you lead you to the issue and the precise location in the UI where this happens (globally anywhere or when you are in a chat input field?)
