### ISSUE TITLE
Scroll behaviour in VS Code.

### ISSUE THREAD

**Issue by indra-kumar-r** [microsoft/vscode#213005]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: 

Steps to Reproduce:

1. I am experiencing a persistent issue with VS Code where scrolling with two fingers on my laptop's touchpad causes sudden and erratic jumps, making it difficult to navigate through my code. This problem occurs regardless of the file size, affecting both small files and those with thousands of lines. I have tried uninstalling and reinstalling VS Code, but the issue persists. This erratic scrolling behavior is unique to VS Code, as other applications on my laptop do not exhibit this problem.

Below I provided a video, were just scrolling down a little bit in the file, it takes me to the end of the file.
Please send me a solution to this.
I'm using VS-code from four years, with this issue, always i scroll up and down with arrow keys or pageUp and pageDown buttons.
But this issue never occurs any other applications, only in vs code i face this issue.

https://github.com/microsoft/vscode/assets/110984003/fa4875ce-4ea8-4f48-a9d0-49df916329f2

**Comment by alexdima** [comment]
@indra-kumar-r It looks like you have defined a very large value for `"editor.mouseWheelScrollSensitivity"`. Please try changing that and let us know if that resolves your problem.

**Comment by indra-kumar-r** [comment]
Yes, it is working.
Thanks for your help.
