### ISSUE TITLE
Sidebar width

### ISSUE THREAD

**Issue by vusal5555** [microsoft/vscode#213069]
Type: <b>Feature Request</b>

I think sidebar must have a fixed width. It should not expand based on the filename length.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by ArturoDent** [comment]
I don't see the Side Bar changing widths - for any reason including the filename lengths.  I get an ellipsis `...` when the filenames are too long to fit.

Can you include a gif of the Side Bar width changing?

**Comment by vusal5555** [comment]
What I am saying is that I do not wanna  drag the sidebar back and forth to adjust its width for my file names and when I click on the sidebar border it gets as larger as it can to fit all the file and folder names so we can it see them at a glance. Now imagine you have a file name that is hundred characters long it will the half of the screen and you will be left with the other half. instead just like terminal when I double click on its border I want it to have a default width.
