### ISSUE TITLE
Private NPM Package details not loading on package.json

### ISSUE THREAD

**Issue by kalesh13** [microsoft/vscode#213009]
This was working 2-3 weeks back. But now it's not and is a good UX to have considering many organizations have their own private registry and always push and pull from there.

**The image below shows me hovering over the `@fastify/jwt` package which is a public package**

<img width="1904" alt="Screenshot 2024-05-18 at 8 12 45 PM" src="https://github.com/microsoft/vscode/assets/19804573/01950ddf-30ce-4ce3-8aba-36aeedd2ced5">

**And, the one below shows me hovering on a private package `@yahaal/ecommerce`**

<img width="1904" alt="Screenshot 2024-05-18 at 8 13 04 PM" src="https://github.com/microsoft/vscode/assets/19804573/5eea83b1-fdbb-425c-a66b-7811212988c3">

Downloading private packages, uninstalls, updates, etc works flawlessly. It's just this small tooltip not showing up

- VS Code Version: 1.89.1
- OS Version: Darwin x64 23.5.0

Steps to Reproduce:

1. Create a `.npmrc` file and add a private registry url
2. Add a package from the private registry on the package.json file
3. Add a public package from npm registry
4. Hover over the public package, you can see the package details, and the latest available version
5. Hover over the private package, nothing shows up.

**Comment by SBokutsWA** [comment]
i have the same issue. previously it worked

**Comment by aeschli** [comment]
We are look for a installed `npm` command. If we find it, we use it with `npm view`. 
- can you check that `npm` is on the PATH? `whereis npm` (on Linux and Mac) `where cmd.cmd` (on Windows) should find the command
- try `npm view @yahaal/ecommerce`

If npm is not found, we fall back to an online service which can not load private repos

**Comment by LucasLongarini** [comment]
I am also having the same issue on mac

**Comment by Timeless0911** [comment]
I also have the same issue, and previously it worked. `npm view` can works for private registry packages.

**Comment by kalesh13** [comment]
@aeschli As you mentioned, I tried `npm view` on the terminal and this is the result

<img width="1331" alt="Screenshot 2024-05-23 at 11 12 08 AM" src="https://github.com/microsoft/vscode/assets/19804573/60fac0a5-4bf5-414e-9fbe-df52115c2913">

As you can see, npm is accessible, and `npm view` can locate the package just fine with all the details. This issue is with VS Code and not with `npm` because everything was working fine 2-3 weeks back before updating VS Code, and I have not updated node or npm in my system.

Also, I see `Loading` text when I hover over the packages before the tooltip crashes. So, my guess, something is breaking between `Loading` and rendering the `npm view` result.

**Comment by dthomason** [comment]
I just noticed this same issue too.  Just last week I was using it when updating our private packages.

**Comment by GRA0007** [comment]
This has been happening for me for the past couple of weeks as well, but for all my packages (I don't have any private packages installed). I use `yarn` so I'm not sure if that's affecting the registry values, but `npm view` works fine. This feature used to work and I haven't changed anything on my end so it's definitely a regression in VSCode.
