### ISSUE TITLE
In terminal, firefox says: Error: Failed to open Wayland display, fallback to X11.

### ISSUE THREAD

**Issue by akihikodaki** [microsoft/vscode#213004]
Type: <b>Bug</b>

Run `firefox` in terminal. It outputs:
```
Error: Failed to open Wayland display, fallback to X11. WAYLAND_DISPLAY='wayland-0' DISPLAY=':0'
```

Note that this error won't happen if `firefox` is invoked from GNOME Terminal.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:30.691Z)
OS version: Linux arm64 6.8.9-402.asahi.fc40.aarch64+16k
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|unknown (8 x 2424)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|22.94GB (12.03GB free)|
|Process Argv|--crash-reporter-id 51db9f8a-de32-42b1-a0dc-4b272906e496|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-clangd|llv|0.1.28
vscode-docker|ms-|1.29.1
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.362.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.17.17
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
remote-explorer|ms-|0.4.3
wordcount|ms-|0.1.0
scala|sca|0.5.7
ruby-lsp|Sho|0.5.21
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31049070
fchga941:31046352
dvdeprecationcf:31052040
pythonprt:31047983
dwnewjupytercf:31046870
fa862199:31048878

```

</details>

**Comment by meganrogge** [comment]
This type of issue is typically related to environment differences between VS Code's terminal and the external terminal. You can try diffing the two environments by printing them (eg. `env`, `Get-ChildItem env:`) and investigating any differences.

Closing this off as it doesn't look actionable on our end, you can read more about our [issue process here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label *question
