### ISSUE TITLE
[WelcomeUX] Panel doesn't look right in interface overlay

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21304]
![image](https://cloud.githubusercontent.com/assets/2193314/23274126/6976cd46-f9b6-11e6-9358-afe8b10fdce5.png)

The panel should be the same color of the welcome page in the overlay as before:

![image](https://cloud.githubusercontent.com/assets/2193314/23274175/8d3aef78-f9b6-11e6-88bc-e6f7c8894dbc.png)

**Comment by chrmarti** [comment]
This is now slightly blurred like the editor already was. It was not intended to not have it blurred before. This is to visually give focus to the overlay and avoid the underlying UI distract from it.

**Comment by Tyriar** [comment]
@chrmarti do you mean in a later build the panel is blurred too? My eyes are drawn to the panel due to the big color difference.

**Comment by chrmarti** [comment]
What OS and commit are you on? I only now realize that yours is not blurred as it should. Mine looks like (Ubuntu):
![screenshot from 2017-02-23 13 28 43](https://cloud.githubusercontent.com/assets/9205389/23279929/0d24ec7e-f9cc-11e6-87a2-a420965c7635.png)

**Comment by Tyriar** [comment]
You're right I was on an older build when I checked this :+1:
