### ISSUE TITLE
org browser not working

### ISSUE THREAD

**Issue by harsha161297** [microsoft/vscode#213063]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by gjsjohnmurray** [comment]
If you are working with Salesforce orgs and using the SFDX extension(s) please consult the extension support channel.

**Comment by aeschli** [comment]
Closing the issue as incomplete. Please add a detailed description of the issue along with steps to reproduce.
