### ISSUE TITLE
Leverage configurationDefaults for languages that we bundle with VS Code

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#21301]
Now that we support default language specific settings #19733 we should make a pass and leverage this new support for languages we bundle.  

For example:
- yaml -> TAB === 2 spaces
- make -> Do not translate tabs to spaces
- ...

**Comment by aeschli** [comment]
I added defaults for 
- go (tabs)
- makefile (tabs)
- yaml (spaces, 2)

**Comment by egamma** [comment]
As discussed in the standup, we will also add a configuration default for Markdown (word wrap, no quick suggest)

**Comment by aeschli** [comment]
Fixed by 8293443262adaaefe758e1167939730c0b082a30
