### ISSUE TITLE
dont know

### ISSUE THREAD

**Issue by esrabalci** [microsoft/vscode#213064]
Type: <b>Bug</b>

when i created a Lightning web component (I used extension), I got this issue. I don't know what was the issue.

VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 042da619-6d65-42b1-8ce5-0973be2e98c0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
salesforce-md-info|Ayu|0.0.7
salesforce-testsuite-manager|Ayu|0.0.2
apex-debug|chu|1.0.3
vscode-eslint|dba|2.4.4
prettier-vscode|esb|10.4.0
lana|Fin|1.14.1
code-runner|for|0.12.2
html-preview-vscode|geo|0.2.5
apex-code-runner|Jos|0.1.7
blockman|leo|1.7.7
git-graph|mhu|1.30.0
theme-monokai-pro-vscode|mon|1.3.2
live-server|ms-|0.4.13
lwc-salesforce|Nik|2.3.0
lwc-builder|nin|0.1.31
material-icon-theme|PKi|5.3.0
vscode-xml|red|0.26.1
salesforce-vscode-slds|sal|1.4.8
salesforcedx-einstein-gpt|sal|0.47.0
salesforcedx-vscode|sal|60.13.0
salesforcedx-vscode-apex|sal|60.13.0
salesforcedx-vscode-core|sal|60.13.0
salesforcedx-vscode-lightning|sal|60.13.0
salesforcedx-vscode-lwc|sal|60.13.0
salesforcedx-vscode-soql|sal|60.13.0
salesforcedx-vscode-visualforce|sal|60.13.0
code-spell-checker|str|3.0.1
errorlens|use|3.17.0
sfdx-package-xml-generator|Vig|2.0.11
vscode-icons|vsc|12.7.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
f3je6385:31013174
pythoncenvptcf:31049071
a69g1124:31046351
pythonprt:31047983
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by gjsjohnmurray** [comment]
If you are working with Salesforce orgs and using the SFDX extension(s) please consult the extension support channel.
