### ISSUE TITLE
VSCode Insiders crashes on start

### ISSUE THREAD

**Issue by Maaaaaaars** [microsoft/vscode#213079]
Since last week Code Insiders crashes every time I open it. I've read similar issues, but found no duplicates.
I couldn't get the dump file, but I have the ```--verbose``` output in a text file: [manualLog.txt](https://github.com/microsoft/vscode/files/15379878/manualLog.txt).
Does this issue occur when all extensions are disabled?: Yes

- VS Code Insiders Version: f209ce35
- OS Version: Linux x64 Ubuntu 23.10

If any additional information is needed I'll try to provide it as quick as possible.

**Comment by Maaaaaaars** [comment]
I tried to open it today and it works. Solved I suppose.

**Comment by deepak1556** [comment]
/fixedWith https://github.com/microsoft/vscode/commit/6e6d38007e3c76ac7686c97502d9c6deefe44b7a
