### ISSUE TITLE
 l._setExceptionValue is not a function

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#21308]
Issue Id: <b>a99788c6-abf0-621a-2f9c-b0a651d523f7</b><br /><br />*Versions* <br />- 1.9.1<br />-  27240e71ef390bf2d66307e677c2a333cebf75af<br />-  fcac9b686abe4292e69a774f61c8c4ce17768bf5<br />-  97a1d7eacdc277ab9f0bb6fddbf7f398ba8c46f4<br />-  fbea777a881523bc01a1358d115b16673dc5942e<br />*Stack* <br />TypeError: l._setExceptionValue is not a function<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1172:0 (_setExceptionValue)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1172:0 (_setExceptionValue))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1813:0 (complete)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1813:0 (complete))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1838:0 (argDone)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1838:0 (argDone))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />    at process._tickDomainCallback (internal/process/next_tick.js:129:7) <no sourcemaps><br />

**Comment by roblourens** [comment]
?
