### ISSUE TITLE
Allow custom text/filename color in explorer

### ISSUE THREAD

**Issue by nullbio** [microsoft/vscode#213003]
I find all of the colors and icons super distracting, so right now my UI looks like this:

![image](https://github.com/microsoft/vscode/assets/721274/2a43f6e4-6335-4bb7-98b0-6c53e8bc4bc2)

However I'd also like to set custom text colors for the filenames depending on what type of file it is. In my case I'd like to set all hidden files (starting with ".") to a darker gray color. 

It'd be great if we could either:

* Have an option to set the text color of hidden files in the explorer view.
or even better:
* Have an option to set text color of files in the explorer view based on a filename regexp match.

This way we could have different filename colors for files with particular extensions as well, like .yml, .md, etc.

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode/issues/31308

**Comment by nullbio** [comment]
That isn't a duplicate of that issue. They're talking about different things. That's talking about tabs or project groups. I'm talking about filename text, based on the contents of the text itself. I'm also not talking about folders or their children.
