### ISSUE TITLE
Some characters are ignored in snippet prefix

### ISSUE THREAD

**Issue by scztt** [microsoft/vscode#213076]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.88.1 
- OS Version: MacOS 14.3.1

Steps to Reproduce:

1. Create a snippet with any of the following prefixes: "////", "----", "!!!"
2. With snippets enabled, type the prefix characters and wait for a snippet completion to be offered.

Result:

Snippets are not offered for these prefixes that only contain certain non-word characters. Note that e.g. "___" works as a prefix, so it's only SOME symbols.

Expected:

Any prefix is valid for a snippet, except in cases where the prefix would significantly disrupt other functionality (e.g whitespace only prefixes probably wouldn't work). At worse, if there are invalid characters for a snippet, I would expect that I would see an error or warning from VSCode's snippet validator, and some mention of it in the documentation.

Context:
I discovered this when trying to add snippets for some pretty obvious and common things that don't start with characters - for example.
```
"Divider": {
  "prefix": "///",
  "body": ["////// $1 //////////////////////////////////////////////////////////////////////////////"]
},
"Region": {
  "prefix": "// #region",
  "body": [ "// #region", "$1", "// #endregion"]
}
```

If the prefix contains any word-like characters, snippet search will match these characters - so the workaround here is relatively easy. However, the snippet match is actively ignoring a subset of characters, and it's not obvious that there's a good reason for it - it would be nice to broaden the matching, or at least document the limitations.

**Comment by jrieken** [comment]
> With snippets enabled, type the prefix characters and wait for a snippet completion to be offered.

Do you mean expect snippet completions to show as you type? But they show when requesting completions manually, via `ctrl+space`? That would be expected for some prefixes because quick suggestions only work when typing at word ends and not everything is a word (by the definition of the language in question).
