### ISSUE TITLE
 Cannot read property 'getLinesContent' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#21309]
Issue Id: <b>180ac88c-d5b0-9825-33f2-85873a2014b3</b><br /><br />*Versions* <br />- 1.9.0<br />*Stack* <br />TypeError: Cannot read property 'getLinesContent' of undefined<br />[/vs/workbench/parts/html/browser/htmlPreviewPart.ts#L50:3 (ITextModelResolverService)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/parts/html/browser/htmlPreviewPart.ts#L50:3 (ITextModelResolverService))<br />[/vs/base/common/eventEmitter.ts#L314:9 (func)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/base/common/eventEmitter.ts#L314:9 (func))<br />[/vs/base/common/eventEmitter.ts#L299:3 (safeInvoke1Arg)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/base/common/eventEmitter.ts#L299:3 (safeInvoke1Arg))<br />[/vs/base/common/eventEmitter.ts#L216:8 (_emitEvents)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/base/common/eventEmitter.ts#L216:8 (_emitEvents))<br />[/vs/editor/common/model/textModel.ts#L279:19 (getVersionId)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/editor/common/model/textModel.ts#L279:19 (getVersionId))<br />[/vs/editor/common/model/textModel.ts#L355:7 (_emitModelContentChangedFlushEvent)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/editor/common/model/textModel.ts#L355:7 (_emitModelContentChangedFlushEvent))<br />[/vs/workbench/api/node/mainThreadDocuments.ts#L24:13 (MainThreadDocuments)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/api/node/mainThreadDocuments.ts#L24:13 (MainThreadDocuments))<br />[/vs/workbench/services/thread/common/abstractThreadService.ts#L63:9 (prototype)](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/workbench/services/thread/common/abstractThreadService.ts#L63:9 (prototype))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L273:1](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/platform/extensions/common/ipcRemoteCom.ts#L273:1)<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L226:19](https://github.com/microsoft/vscode/blob/27240e71ef390bf2d66307e677c2a333cebf75af/src/vs/platform/extensions/common/ipcRemoteCom.ts#L226:19)<br />

**Comment by roblourens** [comment]
Some of the line numbers don't make sense

**Comment by mjbvz** [comment]
I believe that 2481b6ebece30f7c81083cfde22a29edc377200d may have resolved this. It's hard to tell with the line numbers though
