### ISSUE TITLE
Weird black squares all over the place

### ISSUE THREAD

**Issue by huttarichard** [Microsoft/vscode#2131]
Hello guys, 
first of all nice job with VSCODE, love it! Not 100% sure if someone else report it, so rather again.
Im working with vscode about few weeks and almost every week I'm experiencing really weird rendering issue.

It's starting with small black squares which are randomly jumping all over the screen (as you type) and then turn out into something like that:
  
<img width="1440" alt="sreen" src="https://cloud.githubusercontent.com/assets/1809268/12461061/3e1f452c-bfb7-11e5-8c7f-dfdb518ad665.png">

No extensions installed, pure vscode, OSX (retina, el captain) 
Version 0.10.6 (0.10.6)
Build a80232bbcfe8a5cdad1ebc98638673d9dcb02458

Probably related to this issue, chrome is doing the same along with vscode (but only if you actually run vscode).

**Comment by weinand** [comment]
@huttarichard I do not really understand when you are seeing these artifacts: only when running VSCode? Only if you are typing in VSCode or even when typing in a different app but VSCode is running.

What do you mean by "chrome is doing the same along with vscode". Please provide steps that explain what apps are running, and in what app you are doing what...

Thanks.

**Comment by Tyriar** [comment]
@huttarichard If it's happens in Chrome as well it's likely an issue with the tile manager in Chromium. Can you get it to reproduce using only Chrome (multiple windows with multiple tabs)? Also do you know if memory is maxing out on your machine when this happens?

**Comment by huttarichard** [comment]
I was hoping (little bit) that this is known issue and I'm just an idiot which didn't really make a quality issue research :smile:. Im guessing this will be hard to reproduce, since this is happening for me randomly every few days (not really like immediately after startup, usually need some time). I know that "randomly" is not really what you are looking for, I can try to explain little bit more...

@weinand 
> "I do not really understand when you are seeing these artifacts: only when running VSCode?"
> "Only if you are typing in VSCode or even when typing in a different app but VSCode is running."

Not sure about typing in different app. But my guess, only if you type in vscode...

> What do you mean by "chrome is doing the same along with vscode".

Same time and issue. Black squares pops out in every tab you have in chrome as soon as vscode starts doing that.

> "Please provide steps that explain what apps are running, and in what app you are doing what..."

Im developing an meteor web app, which is mobile app as well (cordova). In a moment when issue happens, those apps were on: meteor process, mongodb, robomongo, charles debug proxy, genymotion emulator, few more terminals with fish shell, chrome and 2 instances of vscode. 

Usually I execute command like `code ../meteor_app` and start coding. After few hours (in vscode) issue starts with just one square, for example in the middle of screen, just one 3cm square in the middle. You take a mouse, move over the square and square disappear for few seconds. While you are doing that, more squares pops out, until you get a screen like the one above I send.

@Tyriar 
> "Can you get it to reproduce using only Chrome (multiple windows with multiple tabs)?"

I tried this. Not really able to do that.

> "Also do you know if memory is maxing out on your machine when this happens?"

This was actually first thing which came to my mind. Since debug proxy (charlesproxy.com)  taking a lot to keep a history of request you made to the internet. But to be honest, I was just too lazy to look up for memory stats, I rather kill vscode and run it again and had fun with my code for next few hours :smiley:

**Comment by Tyriar** [comment]
@huttarichard my guess is something to do with RAM or your GPU, a cursory search for "black tiles" on http://crbug.com didn't yield anything relevant so I'm not sure it's been reported to Chromium.

**Comment by huttarichard** [comment]
@Tyriar so are you suggesting report this to chromium issue tracker and close this issue?

**Comment by huttarichard** [comment]
btw, is there any bash command I can execute to stress out ram?

**Comment by bgse** [comment]
@huttarichard I think he's suggesting to check for possible hardware defects with your RAM or GPU, might save you from going on a wild goose chase.

**Comment by Tyriar** [comment]
@huttarichard Either hardware defect or lack of memory would be my guess. Might be a little premature to open a Chromium bug just yet, any more information on repro steps you can get would be helpful as there isn't much to go on now.

**Comment by huttarichard** [comment]
Alright guys, not going to take more time (of yours). I'll wait until happens again. And then we can reopen this issue (with more info)....

**Comment by remcoros** [comment]
I've seen similar artifacts in desktop apps using gpu acceleration (wpf (visual studio), browsers, games) when overclocking my graphics card. Might be a gpu / heating issue.

**Comment by tythewebguy** [comment]
For what it's worth, I've been having the same problem for months. When an update comes out for Code I'll install it and use it for a couple hours, then the black boxes show up everywhere and it's impossible to use the app, so I switch back to Sublime. I'd really like to use Code. 

Today the black boxes showed up again and then Chrome crashed completely. Not sure if the two are related--usually the black boxes only show up in Code. 

Just thought I'd throw that out there in case it's useful to anyone...

**Comment by Tyriar** [comment]
@bpasero do you agree with my hypothesis that this is probably an upstream issue to do with Chromium's tile manager?

**Comment by huttarichard** [comment]
@Tyriar looks exactly same. I stop working with multiple instances of vscode and actually stop stressing out a RAM, never happen since then.

**Comment by bpasero** [comment]
@Tyriar no clue, report it to Electron to find out more.

**Comment by tudorific** [comment]
I started noticing this issue happening about 3 weeks ago with my system. I get similar black squares as you other people reported but only in Chrome and VS Code, no other applications seems to have the issue. I only have 1 instance of VS Code open with a Node.JS project and my RAM usage is only at 25-40% while the black squares are happening. Any ideas what else to try? Restarting VS Code or my laptop prevents the squares for about half an hour but they always come back....
![blacksquares](https://cloud.githubusercontent.com/assets/9408613/16541928/8aeabffa-4048-11e6-9fde-b3f935fe0b4c.png)

**Comment by andyd0** [comment]
I've been having the same issue as well but in my case random black boxes appear if I leave my pc unattended for a bit.  Also, the boxes go away if I scroll in any direction

**Comment by bgse** [comment]
This might indeed be an issue in Chrome/Chromium, while I do not have the issue either on VSCode or Chrome on any of my computers, I've seen something very similar on Chrome-Android quite regularly.
