### ISSUE TITLE
vscode tunnels disappear and couldn't login

### ISSUE THREAD

**Issue by DaneHou** [microsoft/vscode#213180]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.89.1
- OS Version: macOS Sonoma 14.5

Steps to Reproduce:

1. initially, vscode app pops up couldn't find tunnel and ask to pick a different account
<img width="579" alt="image" src="https://github.com/microsoft/vscode/assets/14223172/04cf5010-c355-4a02-bd3c-0c6b445138d0">

2.
<img width="342" alt="image" src="https://github.com/microsoft/vscode/assets/14223172/6aef65ec-4de1-4f80-bf01-c2712fd4b3ed">

tunnel disappears

3. vscode web doesn't work either 
<img width="547" alt="image" src="https://github.com/microsoft/vscode/assets/14223172/80f6ff8e-951b-47f6-9661-6aaefcdaf1ca">

4. tried: recreate tunnels and reinstall app, no luck

Update <May 21 2024 20:36 MST>:  looks like the explorer now show all the tunnels! 

Update <May 21 2024 20:44 MST>:  down again!

Update <May 21 2024 20:50 MST>:  working again!

Update <May 21 2024 20:55 MST>:  back and forth!

Update <May 21 2024 21:14 MST>:  work in my macstudio not iMac but some disappear though the existing tunnel can work until all tunnels appear. very weird!

###  Update <May 22 2024 19:59 MST>: seems they are working on all my computers!

**Comment by mdonato-fn** [comment]
Exactly the same here, just stopped working a couple of hours ago and nothing fixes it. I tried the pre-release version of the extension.

**Comment by BeteixZ** [comment]
Same here, any suggestions are appreciated.

**Comment by bw4sz** [comment]
Same here. Stopped working for me. You can successfully authenticate through github login device.
<img width="511" alt="Screenshot 2024-05-22 at 9 14 22 AM" src="https://github.com/microsoft/vscode/assets/1208492/f2c0ec50-45c6-49d0-ba39-e4491de4f110">
When you go to browser you get

<img width="1671" alt="image" src="https://github.com/microsoft/vscode/assets/1208492/6daa2ab9-b218-421f-928d-a28a0e46def4">

and locally it doesn't show up locally in remote explorer. I'd been using this setup for over a year without interruption.

**Comment by 0rphon** [comment]
same issue here. Ive tried everything i can think of to fix it on my end. glad to know its not just me

**Comment by QuartzWarrior** [comment]
Exact same issue. It was working fine the night before, then I tried logging in yesterday and all my tunnels were gone. Tunnel still running on all my vpses, they are just gone from vscode.dev. Tried with both microsoft and github, no tunnels are being added to any account, or at least it isn't appearing on the frontend side of things..

**Comment by bw4sz** [comment]
I can confirm that my setup is fixed without having changed anything. Seems similar to https://github.com/microsoft/vscode-remote-release/issues/9055

there was a periodic outage. I suggest this gets closed, @DaneHou
