### ISSUE TITLE
Clearing terminal freezes renderer for 20+ seconds

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#213174]
* vscode workspace
* open a terminal, run tests via `./scripts/test.sh`
* run tests again
* run `cmd+k` to clear the terminal
* 🧊 the renderer is frozen for 20+ seconds, looks like `clearBuffer` -> `clearAllMarker` does some endless disposing

<img width="1009" alt="Screenshot 2024-05-21 at 20 55 26" src="https://github.com/microsoft/vscode/assets/1794099/85e51ac9-a547-4731-8c4f-a780f83e0563">

Performance Profile 👇 

[Trace-20240521T205425.json.zip](https://github.com/user-attachments/files/15394321/Trace-20240521T205425.json.zip)

**Comment by jrieken** [comment]
looks like https://github.com/microsoft/vscode/issues/199593 isn't fixed

**Comment by alexanderswerdlow** [comment]
+1 for this. I've been experiencing this for several months, with the scrollback buffer set to 50k.

**Comment by Tyriar** [comment]
The large case was re-enabled in https://github.com/microsoft/vscode/issues/210840 after a fix was done upstream.

@alexanderswerdlow you might be seeing something else if this have been happening for months, you could try create a perf profile when this happens https://github.com/Microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

**Comment by Tyriar** [comment]
It's happening because the buffer lines event emitters have listeners for every marker and they each do an O(n) search to find the marker in question:

https://github.com/xtermjs/xterm.js/blob/2edc65baaa50f8b99c67f3df6f8d5d93c70a69e6/src/common/EventEmitter.ts#L36-L41

https://github.com/xtermjs/xterm.js/blob/2edc65baaa50f8b99c67f3df6f8d5d93c70a69e6/src/common/buffer/Buffer.ts#L622-L644

**Comment by jrieken** [comment]
It's around 500ms now which is much better but also not really great because my machine is way above average and "real world user" are likely seeing a 2second freeze

<img width="515" alt="image" src="https://github.com/user-attachments/assets/11eb2787-a18a-461a-b9f6-cdf7fe75c301">
