### ISSUE TITLE
makup and mermaid extensions are not working

### ISSUE THREAD

**Issue by mavergun** [Microsoft/vscode#21314]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cs-syntax-visualizer|itn3000|0.0.2|
|mdhelper|joshbax|0.0.9|
|md-navigate|jrieken|0.0.1|
|spellcheck|JuliaBay|1.1.4|
|code-spell-checker|streetsidesoftware|0.16.0|
|vscode-mermaid-preview|vstirbu|0.4.3|
|markdown-authoring|yanz|0.1.5|

---

Steps to Reproduce:

1. install Mermaid Preview 
2. Load file containing mermaid encoding
3. the icon on the top right to preview diagram is gray-out

**Comment by mjbvz** [comment]
It sounds like the issue is with the mermaid extension. Please try filing the issue against that extension. 

If you think this is a problem with VSCode itself, please provide some more details about the issue and we can investigate. Thanks
