### ISSUE TITLE
Issue with 'Save All' and 'Save'  Functionality After Latest Update

### ISSUE THREAD

**Issue by cc-qq-gg** [microsoft/vscode#213119]
Type: <b>Bug</b>

1.89.1
Description:
After updating to the latest version of VSCode, I've encountered an issue with the 'Save All' functionality. When I use the shortcut Ctrl + S to save a file, the small black dot indicating an unsaved file remains visible even after the save operation. This dot only disappears after I switch to another file.

Additionally, when I attempt to save all files using the Ctrl + K S shortcut, the same issue occurs. Even though it appears that the files have been saved, they have not actually been saved. I have to manually save each file again to ensure they are written to disk.

Steps to Reproduce:

Open VSCode and update to the latest version.
Open multiple files for editing.
Make changes to one or more files.
Press Ctrl + S to save the current file.
Observe that the unsaved indicator (small black dot) remains.
Switch to another file to check if the indicator disappears.
Use Ctrl + K S to attempt saving all files.
Check the files to confirm whether they have been actually saved.
Expected Result:

The unsaved indicator should disappear after saving with Ctrl + S.
All files should be saved correctly when using Ctrl + K S.
Actual Result:

The unsaved indicator remains after saving with Ctrl + S.
After using Ctrl + K S, files appear to be saved, but they are not actually saved and require manual saving.
Environment:

VSCode version: [INSERT_ACTUAL_VERSION]
Operating System: [INSERT_YOUR_OS]
Extensions installed: [LIST_ANY_RELEVANT_EXTENSIONS]
Additional Notes:

I have tried restarting VSCode and my computer, but the issue persists.
This issue did not occur in the previous version of VSCode.
Please let me know if there is any additional information I can provide to help resolve this issue.

Thank you for your attention to this matter.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.77GB (5.06GB free)|
|Process Argv|--crash-reporter-id 3169eb19-b837-473b-8559-0605b54eb2ee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.2.0
iconify|ant|0.8.1
comate|Bai|2.4.0
vscode-django|bat|1.15.0
bracket-select|chu|2.0.2
miniprogram-vscode-extension|cra|1.4.19
xmind-viewer|cwe|1.0.0
vue-peek|dar|1.0.2
vscode-eslint|dba|2.4.4
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
shell-format|fox|7.2.5
vue-snippets|hol|1.0.4
vsc-python-indent|Kev|1.18.0
git-graph|mhu|1.30.0
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
powershell|ms-|2024.2.2
autodocstring|njp|0.6.1
vetur|oct|0.37.3
LiveServer|rit|5.7.9
any-rule|rus|0.3.18
vue-vscode-snippets|sdr|3.1.1
markdown-preview-enhanced|shd|0.8.13
vue-helper|she|2.6.2
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vswsl492cf:30256860
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
01bff139:31013167
fchga941:31046352
pythonprt:31047983
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by cc-qq-gg** [comment]
> I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

It's quite possible that the issue was indeed caused by a certain extension. After executing this command, it occasionally happens once, but I found that it only occurs in the Vue project, and other projects are ok，thanks.

**Comment by marlun78** [comment]
Had the same issue. After closing the ChatGPT app, all worked as normal for me.
