### ISSUE TITLE
SymbolKind.from and SymbolKind.to do not map SymbolKind.Field

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#21315]
I noticed that `SymbolKind.Field` shows up using the [expected icon](https://github.com/Microsoft/vscode/blob/a32b607f6b109f08a5d9e8e563966390410b3021/src/vs/editor/contrib/suggest/browser/Field_16x.svg) in the suggestion widget but not in the quickoutline widget.

I see that [quickopen.css](https://github.com/Microsoft/vscode/blob/c67ef57cda90b5f28499646f7cc94e8dcc5b0586/src/vs/editor/contrib/quickOpen/browser/quickOutline.css#L58) defines the field icon for high contrast themes and shares a mapping with variable icons, but this same mapping isn't done elsewhere in the css. 

Further, even if the CSS mapping is changed, in [modes.ts](https://github.com/Microsoft/vscode/blob/192db5f7d1218a3b03d7af65a237ac06c75cbb78/src/vs/editor/common/modes.ts#L530) `SymbolKind.from` and `SymbolKind.to` do not map SymbolKind.Field and the switch statement falls through to the default `SymbolKind.Property`, so a property icon would be used.

**Comment by bpasero** [comment]
Via https://github.com/Microsoft/vscode/pull/21318
