### ISSUE TITLE
The JS/TS language service immediately crashed 5 times. The service will not be restarted.

### ISSUE THREAD

**Issue by matt-snow-deepsee** [microsoft/vscode#213186]
Type: <b>Bug</b>

I have restarted the TS Server, deleted the repo and recloned, deleted VSCode and reinstalled, restarted my machine, etc.

TS version: 5.4.5 sdk
node: 20.13.1
vscode: 1.89.1

VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 10, 25|
|Memory (System)|32.00GB (5.39GB free)|
|Process Argv|--crash-reporter-id ca72c7b2-ea2a-4e6a-b6e7-a3cadca3bde9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-jest|Ort|6.2.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
g316j359:31013175
pythoncenvptcf:31049071
a69g1124:31046351
pythonprt:31047983
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by matt-snow-deepsee** [comment]
![image](https://github.com/microsoft/vscode/assets/90271036/4981e51a-3b84-4e79-887e-b8427bc2367a)

**Comment by mjbvz** [comment]
> `5.4.5 sdk`

This is a custom TS version. I believe it is patched by yarn. Please start by filing an issue against them

**Comment by c-eberling** [comment]
@matt-snow-deepsee I have the same issue!!! Gone through the same steps.

**Comment by matt-snow-deepsee** [comment]
If anyone else is experiencing something similar, we finally found the solution that worked for us.  it's an experimental vscode setting called `"typescript.tsserver.experimental.useVsCodeWatcher"` that somehow got turned on by default, but didn't show up in the `settings.json` file.  set it to `false` and reload your window. Hope this helps, and good luck.
