### ISSUE TITLE
sometimes renaming javascript variable does not work 

### ISSUE THREAD

**Issue by v1nce** [Microsoft/vscode#21319]
- VSCode Version: Version 1.9.1
- OS Version: ubuntu 14.04

```
foo= {
    _x: 0,
    _y: 0,
    _z: 0,
    _w: 0,
    set: function(a, b, c, d) {
        this._x = a;
        this._y = b;
        this._z = c;
        this._w = d;
    },
    copy: function(b) {
        this._x = b.x;
        this._y = b.y;
        this._z = b.z;
        this._w = b.w;
    }   
}
```

renaming b parameter of copy does not work : 

if you rename the parameter (b => foo), the changes are not propagated inside the core of method 
copy: function(foo) => 
```
copy: function(foo) {
        this._x = b.x;
        this._y = b.y;
        this._z = b.z;
        this._w = b.w;
    }   
```

if you rename the parameter inside the method the results are even more strange  
this._x = foo.x; => 
```
copy: function(foo) {
        this._foo = b.x;
        this._y = b.y;
        this._z = b.z;
        this._w = b.w;
    }   
```

renaming one of the a,b,c,d parameter of set function is ok

**Comment by mjbvz** [comment]
Thanks. I've opened https://github.com/Microsoft/TypeScript/issues/14278 against TypeScript to track this issue
