### ISSUE TITLE
Unable to view the tests in this inline chat's small view

### ISSUE THREAD

**Issue by abhijit-chikane** [microsoft/vscode#213158]
![image](https://github.com/microsoft/vscode/assets/50770619/69e0a638-e162-4540-a3c8-aff0bb801f40)

unable to view the tests diff in this inline chat's small view
earlier it used to show me preview but from last few days it just show me like this

Version: 1.90.0-insider (user setup)
Commit: 405ce83a24f38fd70751b03438763a1503329fe0
Date: 2024-05-20T23:10:16.407Z
Electron: 29.3.1
ElectronBuildId: 9464424
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/210793
