### ISSUE TITLE
 Unknown injections for grammar <source.json>

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#21310]
Issue Id: <b>d809d47d-27a4-16d5-d8fa-305616973e29</b><br /><br />*Versions* <br />- 1.9.1<br />*Stack* <br />Error: Unknown injections for grammar <source.json><br />    at Registry._loadGrammar (/node_modules/vscode-textmate/release/main.js:2929:30) <no sourcemaps><br />    at Registry.loadGrammarWithEmbeddedLanguages (/node_modules/vscode-textmate/release/main.js:2878:14) <no sourcemaps><br />[/vs/editor/electron-browser/textMate/TMSyntax.ts#L244:25 (loadGrammarWithEmbeddedLanguages)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/electron-browser/textMate/TMSyntax.ts#L244:25 (loadGrammarWithEmbeddedLanguages))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1641:0 (init)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1641:0 (init))<br />[/vs/editor/electron-browser/textMate/TMSyntax.ts#L243:9](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/electron-browser/textMate/TMSyntax.ts#L243:9)<br />[/vs/editor/electron-browser/textMate/TMSyntax.ts#L258:7 (_createGrammar)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/electron-browser/textMate/TMSyntax.ts#L258:7 (_createGrammar))<br />[/vs/editor/electron-browser/textMate/TMSyntax.ts#L147:9 (registerDefinition)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/electron-browser/textMate/TMSyntax.ts#L147:9 (registerDefinition))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L118:26 (call)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/base/common/event.ts#L118:26 (call))<br />[/vs/editor/common/services/modeServiceImpl.ts#L239:25 (fire)](https://github.com/microsoft/vscode/blob/f9d0c687ff2ea7aabd85fb9a43129117c0ecf519/src/vs/editor/common/services/modeServiceImpl.ts#L239:25 (fire))<br />

**Comment by aeschli** [comment]
@alexandrudima Unfortunatly vscode-textmate has a bug that swallows the real error. I made a fix with https://github.com/Microsoft/vscode-textmate/commit/383117ceed34d53e43c4d246250e8b9a0449470d

Can you create a new release of vscode-textmate?

**Comment by aeschli** [comment]
I update vscode-textmate
