### ISSUE TITLE
Mouse side buttons not working in macOS with Logi Options+

### ISSUE THREAD

**Issue by ryuujo1573** [microsoft/vscode#213112]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
1.89.1
dc96b837cf6bb4af9cd736aa3af08cf8279f7685
arm64
- OS Version: Sonoma x64

Steps to Reproduce:

1. Use forward/backward button on logi mouse
2. No responding.

Related to #79078, #88029.
This is not working as speaking of 2024, which is sad.

**Comment by bpasero** [comment]
This is not something VS Code can fix.

**Comment by ryuujo1573** [comment]
> This is not something VS Code can fix. We rely on the mouse properly emitting mouse button events in DOM and if that is not the case, its not configured to do so.

Thank you for your reply. If say, what conditions should be met when we would consider bring `swipeToNavigate` support back, per #79078?

This solves the problem in a proper(?) way whilst `await electronFix`

**Comment by bpasero** [comment]
See https://github.com/microsoft/vscode/issues/204812

**Comment by eliliam** [comment]
I am experiencing the same behavior, and even when I try using the keyboard shortcuts of cmd+ctrl+- and cmd+ctrl++ it does not navigate. Has anyone been able to solve this issue yet?

**Comment by ryuujo1573** [comment]
> I am experiencing the same behavior, and even when I try using the keyboard shortcuts of cmd+ctrl+- and cmd+ctrl++ it does not navigate. Has anyone been able to solve this issue yet?

You might want to use <kbd>ctrl</kbd> + <kbd>-</kbd> and <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>-</kbd>.
