### ISSUE TITLE
Cannot debug typescript with node.js

### ISSUE THREAD

**Issue by xerotolerant** [Microsoft/vscode#21313]
- VSCode Version: 1.9.1
- OS Version: Windows 10

Steps to Reproduce:

1. I really have no idea
2. Magic?

I have been using visual studio code for off and on for a few months now. I have been using it for serious work for about three weeks.

Today I suddenly started getting errors when trying to debug a node.js typescript project.

Prior to these errors I was unable to use the debug side panel.
console.log would however add messages to the debug console.

Today I want to try the debugger to inspect an object returned from a mongodb database using the mongoose library. I added breakpoints but got the error  message:
`Breakpoint ignored because generated code could not be found (source map problem?)`

I searched the problem and found [this question on SO](http://stackoverflow.com/questions/36006303/vs-code-breakpoint-ignored-because-generated-code-not-found-error) 

I set `"sourceMaps": true` in launch.json (no discernible result)

I changed  
`"outFiles" : []`  
to 
`"outFiles": ["${workspaceRoot}/**/*.js"]` 

 When attempting to debug with that setting changed it would just hang. 

launch.json
```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}\\server.js",
            "cwd": "${workspaceRoot}",
            "outFiles": []
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "port": 5858,
            "outFiles": []
        }
    ]
}
```

What do I need to do to be able to use the debugger?

**Comment by roblourens** [comment]
That error means that it can't resolve the .ts file to a .js file running in Node. Setting `outFiles` is often necessary, but you may want to use a more specific path, because it might just spend a lot of time reading all your node_modules js files which you don't want it to do. Set it to look in the path where your built .js files are.

Besides this, if you are using Node v6.9+, try using our new debug adapter by setting `"protocol": "inspector"`.

**Comment by weinand** [comment]
@xerotolerant if you are not using the Insider version of VS Code you cannot use the 'protocol' attribute Rob was mentioning above. Instead set the 'type' attribute to 'node2'.

**Comment by xerotolerant** [comment]
Hello. Thanks for offering help. I can't tell what the solution is supposed to be based on the two above comments. 
I tried 
1) replacing node with node2 in launch.json

```{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            **"type": "node2",**
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}\\server.js",
            "cwd": "${workspaceRoot}",
            "outFiles": []
        },
        {
            **"type": "node2",**
            "request": "attach",
            "name": "Attach to Process",
            "port": 5858,
            "outFiles": []
        }
    ]
}
```

no effect

Also I'm not using an insider version or anything special.

"Setting outfiles is often necessary" Setting it to what though?

**Comment by weinand** [comment]
If you are using TypeScript then you have to transpile it to JavaScript. If this transpilation (aka your build process) generates the JavaScript in a specific folder (and not side by side to the TypeScript source), you can help the debugger locating the generated JavaScript by specifying the `outFiles` attribute as a glob pattern. So if your build process generates the JavaScript in a folder called 'out', you would set 'outFiles' to `[ "${workspaceRoot}/out/**/*.js" ]`

**Comment by xerotolerant** [comment]
I do generate it side by side. I was wondering how I was supposed to reflect that with outfiles.

**Comment by xerotolerant** [comment]
I got it to work 

I set `"sourceMap": true` in tsconfig.json => Compiler options 

Then i set `"program": "${workspaceRoot}/server.ts",`

I think the combinaiton of those two things did the trick

**Comment by roblourens** [comment]
Enabling sourceMaps in your tsconfig so that they're built by TS is definitely required. Glad you got it to work!

**Comment by xerotolerant** [comment]
Thanks for the help. I never had to specifically enable it before. I hide those files in vs code first so I guess i never noticed that they were not there.

**Comment by hellozhangran** [comment]
hello , @xerotolerant  @weinand  i have the same question,  below is my config file 
can you help me ?


launch.json
```
{
    "version": "0.2.0",
    "configurations": [{
            "type": "node",
            "request": "launch",
            "name": "Debug Program",
            "program": "${workspaceRoot}/main.ts",
            "cwd": "${workspaceRoot}",
            "env": {
                "NODE_ENV": "development"
            },
            "skipFiles": [
                "node_modules/**/*.js"
            ],
            "outFiles": [
                "${workspaceRoot}/dist/**/*.js"
            ],
            "stopOnEntry": true,
            "console": "internalConsole"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Port",
            "address": "localhost",
            "port": 5858,
            "outFiles": []
        }
    ]
}
```


tsconfig.json
```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "outDir": "dist",
        "sourceMap": true,
        "rootDir": "src"
    },
    "include": [
        "*.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by hellozhangran** [comment]
hello @xerotolerant i have the same question like you...  
can you help me  figure out how to change ? 

launch.json
```
{
    "version": "0.2.0",
    "configurations": [{
            "type": "node",
            "request": "launch",
            "name": "Debug Program",
            "program": "${workspaceRoot}/src/main.ts",
            "cwd": "${workspaceRoot}",
            "env": {
                "NODE_ENV": "development"
            },
            "skipFiles": [
                "node_modules/**/*.js"
            ],
            "outFiles": [
                "${workspaceRoot}/dist/**/*.js"
            ],
            "stopOnEntry": true,
            "console": "internalConsole"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Port",
            "address": "localhost",
            "port": 5858,
            "outFiles": []
        }
    ]
}
```

tsconfig.json
```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "outDir": "dist",
        "sourceMap": true,
        "rootDir": "src"
    },
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by weinand** [comment]
@hellozhangran could you share some information from the source map for main.ts?
I just need the values for the attributes "sourceRoot" and "sources".
And what is the location of the source map in the project?

**Comment by alohaninja** [comment]
For VS Code - it should suggest that you add `"sourceMap": true` in `tsconfig.json` when you launch node. Currently it just says...

> cannot launch program '<my-file>.ts'; setting the 'outFiles' attribute might help.

**Comment by weinand** [comment]
@alohaninja VS Code's node debugger doesn't know how the JavaScript got produced. So we do not know anything about a tsconfig.json.

**Comment by tomergev** [comment]
I also got this error and I was wondering if anyone can help me because I am constantly using my debugger mode for work. Here is my launch.json file:

`{ // Use IntelliSense to learn about possible Node.js debug attributes. // Hover to view descriptions of existing attributes. // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387 "version": "0.2.0", "configurations": [ { "type": "node", "request": "launch", "name": "Launch Program", "program": "${workspaceRoot}\\bin\\www" } ] }`

And here is the error I have been receiving: Cannot launch program 'c:\PhD-Labs\eight-8\bin\www'; setting the 'outDir or outFiles' attribute might help.

**Comment by roblourens** [comment]
You got a different error, please open a new issue.
