### ISSUE TITLE
[completion] fuzzyScore canComeDiag always be true ?

### ISSUE THREAD

**Issue by lxz26192** [microsoft/vscode#213148]
- VS Code Version: 1.89.1
- OS Version: 

Steps to Reproduce:

https://github.com/microsoft/vscode/blob/a3d7b649f4ff8f584ecb8db9a281796ff68ab020/src/vs/base/common/filters.ts#L678
```
			let score = Number.MIN_SAFE_INTEGER;
			let canComeDiag = false;

			if (wordPos <= maxWordMatchPos) {
				score = _doScore(
					pattern, patternLow, patternPos, patternStart,
					word, wordLow, wordPos, wordLen, wordStart,
					_diag[row - 1][column - 1] === 0,
					hasStrongFirstMatch
				);
			}

			let diagScore = 0;
			if (score !== Number.MAX_SAFE_INTEGER) {
				canComeDiag = true;
				diagScore = score + _table[row - 1][column - 1];
			}
```

the result of _doScore  <= Number.MIN_SAFE_INTEGER
        https://github.com/microsoft/vscode/blob/a3d7b649f4ff8f584ecb8db9a281796ff68ab020/src/vs/base/common/filters.ts#L669
https://github.com/microsoft/vscode/blob/a3d7b649f4ff8f584ecb8db9a281796ff68ab020/src/vs/base/common/filters.ts#L798
![image](https://github.com/microsoft/vscode/assets/22335846/63d8777c-7e61-4e72-8636-12f5f27680a9)

**Comment by jrieken** [comment]
not actionable

**Comment by jrieken** [comment]
oh, now I get it...
