### ISSUE TITLE
MenuBar dropdown option got stuck

### ISSUE THREAD

**Issue by Hardyverma** [microsoft/vscode#213157]
Type: <b>Bug</b>

when click on one of the item in the menubar (like when have to open project) after that the select open      still keep on showing (If switch to any other app it goes away and when switch back to vs code it would still be showing)
I did ignored it at first but, now it is happen every day.
https://i.ibb.co/Vw90Cky/Screenshot-2024-05-21-at-7-26-28-PM.png
https://i.ibb.co/LSb0RPM/Screenshot-2024-05-21-at-7-26-18-PM.png
https://i.ibb.co/Jr9N2r0/Screenshot-2024-05-21-at-7-26-10-PM.png

you may see that in the attachments.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:32.757Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id cf95f115-a421-42fc-9598-8ff13a49d04c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-tailwindcss|bra|0.10.5
dart-code|Dar|3.88.1
flutter|Dar|3.88.0
prettier-sql-vscode|inf|1.6.0
vscode-docker|ms-|1.29.1
vscode-kubernetes-tools|ms-|1.3.16
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.362.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
nuxtr-vscode|Nux|0.2.16
vscode-yaml|red|1.14.0
php-ci|sma|0.4.2
vscode-gradle|vsc|3.13.5
volar|Vue|2.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
g316j359:31013175
pythoncenvptcf:31049071
fchga941:31046352
pythonprc:31047982
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by deepak1556** [comment]
Can you confirm if the issue is present with latest stable
