### ISSUE TITLE
Editor Custom Labels Glob Not Escaping Properly

### ISSUE THREAD

**Issue by 4lch4** [microsoft/vscode#213117]
Type: <b>Bug</b>

I'm trying to create a pattern for the Workbench > Editor > Custom Labels setting that matches any file named `[...slug].astro`, but I can't properly escape the brackets. If I provide a pattern like `**/\[...slug\].astro,`, then the title doesn't change, but if I change it to `**/*.astro`, it works as expected.

I did some digging but could not find any other issues reported like this, and I can't figure out what is going wrong.

I should note, I'm submitting this from the Insiders build as I only have the Astro extension installed there so it serves as a good test bed. I originally found the issue in the 1.89 build, with the following details:

```
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.0-76060800daily20240311-generic
```

The content following the separator was auto-provided when I submitted this issue via the Report Issue feature within VSCode.

---

VS Code version: Code - Insiders 1.90.0-insider (405ce83a24f38fd70751b03438763a1503329fe0, 2024-05-20T23:11:31.993Z)
OS version: Linux x64 6.8.0-76060800daily20240311-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (32 x 5289)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|125.01GB (62.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
astro-vscode|ast|2.10.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
showvideot:31016890
chatpanelt:31014475
bdiig495:31013172
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by 4lch4** [comment]
In case it helps, here is a copy of the relevant setting in my stable version of VSCode that shows the ways I was trying this without any success:

```json
"workbench.editor.customLabels.patterns": {
  "**/[...slug].astro": "${dirname}",
  "**/\[...slug\].astro": "${dirname}", // This isn't technically a valid JSON string but I tried it anyway
  "**/\\[...slug\\].astro": "${dirname}",
  "**/\\\\[...slug\\\\].astro": "${dirname}"
}
```

**Comment by benibenj** [comment]
Here is the documentation of supported syntax for glob patterns: https://code.visualstudio.com/docs/editor/glob-patterns
We do not support the escape character `\` due to performance issues

You'll have to come up with a different pattern. For example `**/?...slug?.astro` could work.
