### ISSUE TITLE
Tabs: review use of `tabsModel` vs. `groupsView` for operating on selection

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#213163]
While reviewing noticed that `tabsModel` is used  for methods `isSelected()`,  which would account for filtering with multi-row tabs.

Since selection is always working across both rows, I was wondering if it should be invalid to use filtered group models when dealing with selection?

**Comment by benibenj** [comment]
Prohibited reading `selectedEditors` from a filtered model and made sure the correct `isSelected()` is used
