### ISSUE TITLE
My codespace is not running in my mobile please solve it fast

### ISSUE THREAD

**Issue by Moin897** [microsoft/vscode#213176]
ADD ISSUE DESCRIPTION HERE

Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36
Embedder: codespaces

```[tasklist]
### Tasks
```

**Comment by Moin897** [comment]
![Screenshot_20240521_125033_Chrome](https://github.com/microsoft/vscode/assets/138836840/2ce98b0a-b79e-41c8-8352-670c43d04266)

**Comment by connor4312** [comment]
Please open an issue on codespaces
