### ISSUE TITLE
Restarting inspect debugger restarts it in legacy mode

### ISSUE THREAD

**Issue by tinovyatkin** [Microsoft/vscode#21316]
- VSCode Version: todays Insider build
- OS Version: macOS latest beta

Steps to Reproduce:

1. Start debugger in `"protocol": "inspector"`
Output:
```
node --inspect=29189 --debug-brk --harmony --trace-warnings --nolazy server/index.js 
```
2. Press Restart button in VSCode
Output:
```
node --debug-brk=13951 --harmony --trace-warnings --nolazy server/index.js 
```
My `launch.json` config for node:
```json
   {
      "name": "Launch",
      "type": "node",
      "protocol": "inspector",
      "request": "launch",
      "preLaunchTask": "pm2:stop",
      "program": "${workspaceRoot}/server/index.js",
      "cwd": "${workspaceRoot}",
      "envFile": "${workspaceRoot}/.env",
      "runtimeArgs": [
        "--harmony",
        "--trace-warnings",
        "--nolazy"
      ]
    }
```

**Comment by isidorn** [comment]
`"protocol":  "inspector"` is nicely passed to the debug adapter on restart also.
So the issue seems to be in node extension.

**Comment by weinand** [comment]
@isidorn and on restart the sessionCommand is used again?

**Comment by isidorn** [comment]
@weinand no, that was never part of the design of the `sessionCommand` - at least from my understanding of it. It is only used when a user explicitly starts a session

**Comment by weinand** [comment]
`"protocol": "inspector"` is not interpreted by the debug adapter in any way. It is the extension code that uses it and sets the debug type. That means if you call the sessionCommand for a type 'node' a session of type 'node2' can be started.
A subsequent 'restart' has to become a 'node2' session, not a 'node' session.

**Comment by isidorn** [comment]
Yes but vscode is not aware what is the type of the current session (only what type is specified in the `launch.json`).

The only proper fix is that the `startSessionCommand` is also called on restart which is not a small refactoring but I can look into it

**Comment by weinand** [comment]
the extension calls this
```js
vscode.commands.executeCommand('vscode.startDebug', config);
```
and here config has the new type. So VS Code knows the correct type of the session.

**Comment by isidorn** [comment]
For now I just pushed a hack fix which takes care of the type.
The issue is that previously we were doing semantly a good thing when restarting (that is we would keep the configuraiton of the process). However due to #19366 we have changed that
