### ISSUE TITLE
Chat tools API

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#213274]
This is a proposal to enable tool use/function calling from chat participants and other extensions that use language models.

Proposal dts: https://github.com/microsoft/vscode/blob/b1252f75d52bcc576ca58415512343a8413fa260/src/vscode-dts/vscode.proposed.chatTools.d.ts

Tool use sample: https://github.com/microsoft/vscode-extension-samples/tree/roblou/tool-user/chat-tools-sample
Basic chat sample: https://github.com/microsoft/vscode-extension-samples/tree/main/chat-sample
Docs: https://code.visualstudio.com/api/extension-guides/chat

Extension authors can subscribe to this issue to get updates about the proposed Tools API.

We are very interested in feedback about how you might use this API.

## September TODO list
- [x] Tools show a progress message when invoked in a chat session using invokeTool
- [x] Enable tools to show a confirmation message before being executed
- [x] Tools can advertise their supported content types, and invokeTool takes a list of requested contentTypes

## October TODO list
- [x] Tools can have tags
- [x] Generic typed tool parameters
- [x] Confirmation dialog should show up when calling invokeTool outside of a chat session
- [x] Remove unenforceable `text/plain` "requirement", but be more clear about usage in docs. Clarify that a `JSON.stringify` result  be simply `text/plain`.
- [x] Remove `ChatMessage` prefix part on tool call/result types.
- [x] Remove `LanguageModelChatMessageToolResultPart#isError`- not sure why we have this, it isn't used
- [x] Decide how to handle tool name/ID, whether it's required to pick a unique name.
  - A unique `name`, explain the situation in docs
- [ ] Normalize description/modelDescription
  - Could be `description: string | { description: string; userDescription?; string }`
- [x] Confirmation message format, recommended wording, whether `participantName` is included. How it's presented in chat session confirmation vs non-chat confirmation dialog
  - Can do a custom markdown dialog
- [x] Is it incorrect to have a generic parameter on `invokeTool`? Should parameters always be Object on this end, since in theory you are calling the tool without knowing the types?
  - Remove this parameter, split the invocation options interfaces
- [x] Decide on shape for `toolChoice` parameter
- [x] https://github.com/microsoft/vscode/issues/225727
- [ ] Remaining TODOs in dts
- [x] `parameters` should be JSON.parsed?
- [x] Find a name for `canBeInvokedManually`, or cut this from finalization
- [ ] Validate JSON schema when calling a tool 💪 
- [ ] An auto-continue button to skip confirmations for a request 💪 
- [ ] Can we do something to make tool calling more automatic? Helper tools or just a better sample that can be copied for now with functions that can be used as a "library" 💪

**Comment by jdchmiel** [comment]
Forgive me if this is the wrong place - I was curious what the model is looking like for when a chat response contains buttons, which map to commands, which then need to use the ChatResponseStream to insert a response from the participant into the chat window.  I have not figured out how to have the command handler gain access to the ChatResponseStream?  It is a common use case for the tools I would like to leverage that will be doing something external in a terminal or an API and then presenting a conversational response within the chat window, so I think I am just overlooking the obvious for how chat tools will relay conversational messaging back?

**Comment by roblourens** [comment]
That's not a case that is supported right now. There's no way to change the chat response after the chat participant handler is complete.

**Comment by jdchmiel** [comment]
Thank you for your response. Do you have any ideas on alternate ways to accomplish invocation of a command ( or local code in any abstraction) and returning the results to the chat?
Would additional use cases help? Like another very simple one might be "why did the build fail" and I would like to parse a CICD platform and respond with the failure reasoning in chat, as a link to the build perhaps.

**Comment by roblourens** [comment]
You can call `executeCommand('workbench.action.chat.open', 'query')` to invoke your participant again, and continue the conversation. That API is a little primitive and I'd like to have a more natural mechanism for this. I opened this issue to track it  https://github.com/microsoft/vscode/issues/213827

**Comment by AaronFriel** [comment]
Hey @roblourens, it looks like this tool calling framework doesn't allow streaming. This precludes incremental rendering of structured responses, for example a structured edit or mixed text and structured response. 

I'd love to contribute the [fn-stream library for streaming JSON parsing](https://github.com/aaronfriel/fn-stream) to VS Code to enable efficient streaming. While it wasn't accepted by Vercel, it is over [100x faster than parsing every prefix](https://github.com/vercel/ai/pull/1883) for long responses. The naive algorithm for streaming JSON parsing, which is to "fix up" the prefix to be a partial object and call `JSON.parse()` on it, is O(n<sup>2</sup>) or more precisely involves parsing ((n*n+1)/2) tokens as for a 100 token stream, the first token is parsed 100 times, the second 99 times, and so on. and especially costly towards the tail of longer responses.

Using a streaming JSON parser we can reduce this to O(n), each token is parsed once and we can work with either a stream of patches or build a partial object incrementally. The example in the linked library and in the "100x faster" pull request to Vercel describe relevant use cases.

**Comment by bwateratmsft** [comment]
Is this API intended to implement a Copilot version of OpenAI function calling, or is it just about chat extensions communicating with other chat extensions?

**Comment by roblourens** [comment]
This API will be a major focus for this month. Here are some things that I want to be able to do with it

- Finish enabling a tool to be invoked manually by the user like a "variable", which was [started last month](https://github.com/microsoft/vscode/blob/466bbfae121015298512e28de6e2cdc51ff6d3fb/src/vscode-dts/vscode.proposed.chatParticipantAdditions.d.ts#L192).
  - And make some of copilot chat's builtin tools work this way
- Enable tools to return different types of content, including arbitrary custom content that could be read by another extension that understands the data format of the tool being called.
  - Including prompt-tsx PromptElements
- Tools should be able to return custom progress updates, which could be optionally rendered by the participant as progress messages. Example: the messages shown by `@workspace` and `#codebase`
- Optional user confirmation for calling tools that have side-effects
  - Is the confirmation flow driven by the tool dynamically, or by vscode based on the tool declaring that it needs permission?
  - If the tool asks for confirmation, it can decide whether to ask at runtime, and build a nice message for the user dynamically. But, this leads to confusing API. Letting vscode drive it is much simpler.
  - The current `confirmation` flow is based on making a new request with the user's permission. This is still a bit confusing for this scenario. Previous brainstorming about this problem https://github.com/microsoft/vscode-copilot/issues/5470

**Comment by jdneo** [comment]
@roblourens I think here the parameter name for `name` should be `id`?

It's confusing here since both `name` and `id` are both available in the contribution point. 

Same to the description of the activation event: `onLanguageModelTool:toolName` should be `onLanguageModelTool:toolId` I guess.

**Comment by wangmingliang-ms** [comment]
[like]  Miller Wang reacted to your message:
________________________________

**Comment by roblourens** [comment]
That's right @jdneo, thanks

**Comment by jdneo** [comment]
Hi,

What's the usage of `[contentType: string]: any;` in `LanguageModelToolResult`. I tried to not set this/these fields in the returned `LanguageModelToolResult`, and looks like it's still working.

**Comment by roblourens** [comment]
The idea was that tools would be able to return different types of content, either a string or some type of rich content. I'm not sure whether we will keep that exact shape. But we are working on the ability for a tool to return essentially a vscode/prompt-tsx PromptElement: https://github.com/microsoft/vscode/pull/225634 which will make it easier to incorporate complex tool results into a prompt.

**Comment by roblourens** [comment]
Here's the current state of things:

LanguageModelTools can be registered using lmTools proposed API. Copilot Chat contributes some tools now. Tools can be invoked using the `invokeTool` method, and a chat participant could using function calling in the LLM to invoke these dynamically, if it wants to.

Tools can also be marked with `canBeInvokedManually` to enable the user to add them manually. The only one right now that does this is `vscodeAPI`. For these tools, they show up as attachments/variables in the UI. When a user adds one to their query, they show up on the ChatRequest as `toolReferences`. Then the participant can make an LLM request to get the arguments for the tool, invoke the tool, and attach the result as context to the prompt, same as the existing `ChatPromptReference`/"variable".

Since `toolReferences` will be a new field on the request, chat participants need to set the `supportsToolReferences` flag in their package.json to enable these to appear. `toolReferences` are adopted on the tool-user chat sample, if you want to see it in action: https://github.com/microsoft/vscode-extension-samples/tree/roblou/tool-user

**Comment by jdneo** [comment]
> But we are working on the ability for a tool to return essentially a vscode/prompt-tsx PromptElement: https://github.com/microsoft/vscode/pull/225634 which will make it easier to incorporate complex tool results into a prompt.

Ok, assume that I returned something like:

```
{
    'foo': ...,
    'bar': ...,
    toString() {
        return 'hello world!'
}
```

How does vscode/copilot knows which one should be used?

**Comment by roblourens** [comment]
Right now it will always use the string. Copilot Chat could pick up a PromptElement, image data, or some other type of content in the future, but still thinking about exactly how that will work.

**Comment by roblourens** [comment]
Merged a PR https://github.com/microsoft/vscode/pull/226483 to support a "when" clause for tools. The tool won't show up in the UI for the user to attach it, or in the API tools list, when the "when" clause is false.

Note that your tool might still be invoked even when you think it's disabled, due to a race between the extension host and window processes, or due to an extension hardcoding a reference to it. It's ok to return an empty result in that situation.

**Comment by roblourens** [comment]
We now show a spinner in the chat session automatically when invokeTool is called. To drive this, you must pass a `ChatParticipantToolToken` from the ChatRequest into `invokeTool`. See the API changes in https://github.com/microsoft/vscode/pull/228181. chat-sample has been updated to show how to use this.

**Comment by jdneo** [comment]
Hi @roblourens,

I'm not sure if I met a bug of when clause or not. Below is the change I made for the chat-sample:

1. Add `"when": "testLmTool"` for `catVoice` tool
2. Set context at the beginning of the activation
    
![image](https://github.com/user-attachments/assets/b6f590c4-49bb-429f-8435-0efd7e782bf0)

3. For convinience, I set the activation events to `"*"` in package.json.

Then when I invoke it in chat, I got:
![image](https://github.com/user-attachments/assets/ce0f809f-3d42-4482-8fae-cd780d4726ca)


Version: 1.94.0-insider
Commit: 6e9d8a281003211220a6732ec538a28c483ff78b
Date: 2024-09-11T05:04:03.124Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.94.0-insider Chrome/124.0.6367.243 Electron/30.4.0 Safari/537.36

**Comment by JasonYeMSFT** [comment]
Where is the updated chat-sample that shows how to use the new `toolInvocationToken` option?

**Comment by roblourens** [comment]
The sample is at https://github.com/microsoft/vscode-extension-samples/tree/roblou/tool-user/chat-sample

@jdneo this is working for me, but I think I fixed a race condition in the Copilot Chat extension for fetching tools that have when clauses. So please try it with the next pre-release build

**Comment by jdneo** [comment]
Tried latest pre-release and insider vscode, it's working now.

**Comment by roblourens** [comment]
Pushed some changes to the tools API, which tools and `invokeTool` users will have to adapt. 

Tools now declare their supported content types, and the tool's `toString` has changed to the mimeType `text/plain`. 

On the `invokeTool` side, you must pass the content types that you want, eg `text/plain` or the prompt-tsx content type.

The tool sample at https://github.com/microsoft/vscode-extension-samples/tree/roblou/tool-user/chat-sample has been updated for this.

**Comment by roblourens** [comment]
Breaking API changes to be aware of

* Previously you had to JSON.parse the `LanguageModelToolCallPart` parameters. This is now a proper parsed object, not a string, so remove that code.
* Tool `id` is now `name`
* Tool `name` (just used for `#` variable references) is now `toolReferenceName`
* `canBeInvokedManually` is now `canBeReferencedInPrompt`
* `prepareToolInvocation` no longer gets the participant name
* A few tweaks other that probably don't affect any of your extensions, but please let me know if you run into issues

**Comment by roblourens** [comment]
Another round of breaking API changes in the next Insiders release. Hopefully the last round!

- The `LanguageModelToolResult` has changed substantially. Tools no longer declare their "supported mime types", and tool callers no longer pass "requested mime types". Tools simply return an array of `LanguageModelTextPart | LanguageModelPromptTsxPart` (or `unknown` for future extensibility). Tool callers can either use the `LanguageModelPromptTsxPart` if they are using prompt-tsx, or if not, they can pass those result parts onto a `LanguageModelToolResultPart` and make a request, and the `LanguageModelChat` will handle them. This hopefully makes the tool calling flow much easier to understand!
- `LanguageModelToolDescription` -> `LanguageModelToolInformation`
- `toolChoice` -> `toolMode`
- `toolCallId` -> `callId`
- `prepareToolInvocation` -> `prepareInvocation`
- `tokenOptions` -> `tokenizationOptions`
- A couple straggler instances of tool `id` changed to `name`

**Comment by heejaechang** [comment]
Will VSCode provide some default tools, such as file search, like OpenAI does? If it does, that would be very helpful for extensions to create agents that can answer specific questions more effectively than the default Copilot agent.

For example, we experimented with the OpenAI Assistant API using the file search tool provided by OpenAI with 50 wiki pages containing detailed information on Pylance’s features and settings. The quality of the answers for those questions, compared to the default responses from VSCode Copilot, was vastly improved.

It would be nice if extensions could easily create such chat participants using the API and default tools, rather than each extension having to implement its own common tools.

**Comment by roblourens** [comment]
We would like to provide a fundamental set of tools, but no immediate plans.
