### ISSUE TITLE
Select disparate sections (i.e. noncontiguous regions) of text

### ISSUE THREAD

**Issue by celvice** [Microsoft/vscode#21328]
Running on:

- VSCode Version: 1.9.1
- OS Version: OS X El Capitan 10.11.3

The possibility to select different parts of text within a file. 
It seems this feature is not currently supported by VS Code.

Thank you!

**Comment by roblourens** [comment]
It is supported - use the alt key to place multiple cursors, or hold alt and drag to select other regions.
