### ISSUE TITLE
Webviews load slowly on vscode.dev

### ISSUE THREAD

**Issue by jonathanyeung** [microsoft/vscode#213284]
Webviews load slowly on vscode.dev.

I have a custom editor and it takes ~4 seconds to load, while the native editor loads documents immediately. This is not unique to my custom editor, as other webview based extensions such as Markdown Preview Enhanced also take similar amounts of time, even the built-in .jpg image previewer. Furthermore, the amount of time it takes to load does not decrease on subsequent opens of the same file.

The slow loading only occurs on vscode.dev. The webviews load quickly in native VS Code.

<img width="1440" alt="Screenshot 2024-05-23 at 11 08 31 AM" src="https://github.com/microsoft/vscode/assets/3203268/a2d726dd-6e9a-4765-9b4e-b1dd1dbc9933">

Thank you!

Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
Embedder: vscode.dev

**Comment by mjbvz** [comment]
What browser are you using?

**Comment by jonathanyeung** [comment]
I've tried on both Edge and Safari and the load times are similar for both. 

Microsoft Edge
Version 124.0.2478.105 (Official build) (arm64)

Safari 
Version 17.4.1 (19618.1.15.11.14)

**Comment by jonathanyeung** [comment]
Hi @mjbvz - is there enough info here for a triage? Thanks.

**Comment by jonathanyeung** [comment]
Issue still exists.
