### ISSUE TITLE
Newline on enter with fully-typed word

### ISSUE THREAD

**Issue by logiclrd** [microsoft/vscode#213234]
Visual Studio has an option in its settings:

> Enter key behaviour:
> ○ Never add new line on enter
> ⦿ Only add new line on enter after end of fully typed word
> ○ Always add new line on enter

I type pretty quickly, and so I regularly type out a short word in full, such as `try` or `else`, and immediately hit enter. Because Visual Studio Code pops up IntelliSense as I am typing the word, though, the newline is subsumed. The result is code that looks like this:

```
if (condition)
{
  foo();
}
else{
  bar();
}
```

Is there any possibility this functionality could be added to Visual Studio Code, so that if I have typed out IntelliSense's suggestion in full, then the Enter key does add a newline?

**Comment by jrieken** [comment]
`editor.acceptSuggestionOnEnter: smart` it is

**Comment by logiclrd** [comment]
Ah, excellent. Would that this were more discoverable :-) Thanks!
