### ISSUE TITLE
textDocument/didOpen now sending "git:/" prefixed URIs

### ISSUE THREAD

**Issue by kburtram** [Microsoft/vscode#21324]
The mssql for VS Code language service application is crashing on today's insider build since the textDocument/didOpen message is now sending "git:/" prefixed URIs.  Previously this event would send "file:/" prefixed URIs which we knew how to interpret.

Is this change intentional that now extensions need to know how to decode the various SCM URI formats?

This is an issue a couple users have reported on our repo at https://github.com/Microsoft/vscode-mssql/issues/718.

Here is what one of the message payloads that is causing problems looks like:

"textDocument/didOpen"

{ {
"textDocument": {
**"uri": "git:/d%3A/xplat/test/test3.sql",**
"languageId": "sql",
"version": 1,
"text": ""
} } }

- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Install the mssql extension on today's insider build and open a SQL file

**Comment by kburtram** [comment]
When investigating further it looks like there are now 2 open document and 2 close document events.  The first with file:/ prefix and second with git:/ prefix.

**Comment by joaomoreno** [comment]
It is intentional, but extension don't need to know how to decode the various SCM URI formats. They just need to pay attention to `file:` URIs. You should filter everything else out.

cc @jrieken

**Comment by jrieken** [comment]
>  Previously this event would send "file:/" prefixed URIs which we knew how to interpret.

It would always send event for *any* document being opened. Most of the time that is file-uris but even before we used to (and still) have things like `untitled`, `index`, `vscode` schema as well as all the schema from virtual document providers so make sure you extension is fit for these kind of documenst
