### ISSUE TITLE
Opening terminal in a new window

### ISSUE THREAD

**Issue by teshnizi** [microsoft/vscode#213200]
Hi,

I usually use a separate monitor when coding, so I have access to both my laptop's screen and a monitor. I'd like to detach the terminal into a new window and move it to my laptop monitor, and have the editor on the external monitor. I know I can use the system terminal, but I prefer VSCode's terminal. Is this feature requested/implemented before?

**Comment by ArturoDent** [comment]
Look at the `Terminal: Move Terminal into a New Window` command.  You can then drag that floating terminal window where you want it.

**Comment by pktiuk** [comment]
This seems to be a duplicate of: https://github.com/microsoft/vscode/issues/210237

Currently, simple workaround is setting `"terminal.integrated.defaultLocation": "editor",` and moving terminal tab into the new window.
