### ISSUE TITLE
 When quitting Google Chrome, VSC is automatically terminated.

### ISSUE THREAD

**Issue by raon0ms** [Microsoft/vscode#21325]
- VSCode Version: 1.9.1
- OS Version: Windows 10 Pro 1607 build 14393.693

Steps to Reproduce:

1. Launch Google Chrome
2. Launch VSC
3. Quit Google Chrome

And then, you can see that VSC is terminated.

**Comment by roblourens** [comment]
That's weird. How are you launching vscode? And how are you launching and quitting Chrome?

**Comment by raon0ms** [comment]
I just double click on the Chrome icon and the VSCode icon. Then click the close button in the upper right corner of the Chrome window.

**Comment by bpasero** [comment]
@raon0ms is that a Windows insider build? If so, can you try with a stable Windows 10 build?

**Comment by raon0ms** [comment]
No, it is stable version. I'm just personal user.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by raon0ms** [comment]
The symptom are also the same under VSCode 1.10.0.

**Comment by bpasero** [comment]
@raon0ms can you run "code --verbose" from the command line and see what kind of output is produced when you quit Chrome?

**Comment by raon0ms** [comment]
Here is the log.

C:\>code --verbose

[93m[main ?ㅽ썑 3:19:35][0m Starting VS Code in verbose mode
[93m[main ?ㅽ썑 3:19:35][0m from: c:\Program Files (x86)\Microsoft VS Code\resources\app
[93m[main ?ㅽ썑 3:19:35][0m args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'new-window-if-not-first': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[23288:0224/151936:ERROR:jump_list.cc(274)] Failed to append custom category '理쒓렐 ?대뜑' to Jump List due to system privacy settings.
[23288:0224/151936:ERROR:jump_list.cc(274)] Failed to append custom category '理쒓렐 ?대뜑' to Jump List due to system privacy settings.
[93m[main ?ㅽ썑 3:19:38][0m IPC#vscode-workbenchLoaded
[23288:0224/151939:INFO:CONSOLE(133)] "%c[Extension Host]", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (133)
[93m[main ?ㅽ썑 3:19:45][0m Lifecycle#window-all-closed
[93m[main ?ㅽ썑 3:19:45][0m Lifecycle#before-quit
[93m[main ?ㅽ썑 3:19:45][0m App#will-quit: disposing resources

**Comment by bpasero** [comment]
Hm, nothing suspicious there. What Chrome version are you using? Does it reproduce when you try with e.g. Chrome Beta?

**Comment by raon0ms** [comment]
My Chrome is 56.0.2924.87 (64-bit), which is stable version.

**Comment by bpasero** [comment]
I cannot reproduce and somehow I think there are not many others that have this issue, I hear it for the first time.

Out of curiosity, can you install another Electron based application (for example the Atom editor) and see if the behaviour is the same?

**Comment by raon0ms** [comment]
I have already installed a GVIM. This issue is not happened with it. Anyway, thank you for your interest.
It may be a problem only on my computer. I will try to solve this issue myself. If I solve it, I will post it here again. Thank you!

**Comment by raon0ms** [comment]
Hi,
I have solved it. It is because of the plug-in modules of Chrome. These are the security modules for the internet banking. After I removed and reinstalled them, then the issue has not happened.

https://chrome.google.com/webstore/detail/touchen-pc%EB%B3%B4%EC%95%88-%ED%99%95%EC%9E%A5/dncepekefegjiljlfbihljgogephdhph?utm_source=chrome-app-launcher-info-dialog

https://chrome.google.com/webstore/detail/inisafe-crossweb-ex/dheimbmpmkbepjjcobigjacfepohombn?utm_source=chrome-app-launcher-info-dialog
