### ISSUE TITLE
How do I open VS Code to a specific folder at startup?

### ISSUE THREAD

**Issue by JeffJustJeff** [Microsoft/vscode#21322]
Assuming I have path to the executable in my environment path, I can start VS Code with 'code -n,' but I don't see any option to specify a folder (or file) to open.

Please add an option to open a file or folder from the command line. I would like to open VS Code from a script.

**Comment by roblourens** [comment]
You should be able to use `code filename` for a folder or file. I do that all the time. Does it not work for you?

**Comment by JeffJustJeff** [comment]
I must have missed that as an option.

Thank you
