### ISSUE TITLE
DeltaDecorations causing page to freeze

### ISSUE THREAD

**Issue by Xiangzi529** [microsoft/vscode#213218]
https://stackblitz.com/~/github.com/Xiangzi529/vue3-monaco-editor?file=src/App.vue 
You can view my bug at this address. Opening 339 lines of comments or 340 lines will cause the page to freeze ，
I can use the deltaDecorations method correctly in Vue2 to add content, but it doesn't work in Vue3. I have tried to freeze the page directly in versions 0.33.0 and 0.48.0

**Comment by Xiangzi529** [comment]
I want to add a decorator to merge some conflicts

**Comment by Xiangzi529** [comment]
还是不知道问题出在哪里

**Comment by hediet** [comment]
Please file a bug in the monaco editor repo. Thanks!
