### ISSUE TITLE
Text is reproducing in Vs studio code authenticated with cs50p

### ISSUE THREAD

**Issue by LassiPK** [microsoft/vscode#213253]
Uploading Screenrecorder-2024-05-23-00-45-50-69.mp4…

ADD ISSUE DESCRIPTION HERE
Whenever I press enter or backspace key, certain text reproduces which makes it impossible to type anything 
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by LassiPK** [comment]
Uploading Screenrecorder-2024-05-23-00-45-50-69.mp4…

This is the recording

**Comment by IllusionMH** [comment]
Not sure how you are trying to upload video, but it's not attached to issue or comment. You should upload it from GitHub's UI

**Comment by LassiPK** [comment]
https://github.com/microsoft/vscode/assets/122905234/58663f1b-2489-4fb6-a12c-193a71b8860f

**Comment by LassiPK** [comment]
> Not sure how you are trying to upload video, but it's not attached to issue or comment. You should upload it from GitHub's UI

It is visible now. Any help would be appreciated 👍☺️

**Comment by LassiPK** [comment]
Please help me bro

**Comment by hediet** [comment]
What OS are you using?

**Comment by LassiPK** [comment]
> What OS are you using?

Oh, it is Xiaomi hyperOS, an Android based OS in my tablet. Thanks for answering though 😃

**Comment by hediet** [comment]
I fear it might be an issue of that OS. Does it reproduce in chrome on a desktop (e.g. with the windows virtual keyboard)?

**Comment by LassiPK** [comment]
Please help bro, it would literally save my Summer break 😭
