### ISSUE TITLE
Terminal: Opening source editor dims color

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#21323]
- VSCode Version: Code - Insiders 1.10.0-insider (0b27b528a7aac070bced1239310144d0763823bd, 2017-02-23T07:04:58.188Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|autofilename|JerryHong|0.1.3|
|vscode-simple-icons|LaurentTreguier|0.10.0|
|vscode-docker|PeterJausovec|0.0.11|
|azure-cli|chrmarti|0.3.0|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.2.5|
|ghlink|dt|0.0.5|
|tslint|eg2|0.8.1|
|vscode-scss|mrmlnc|0.6.1|
|PowerShell|ms-vscode|0.9.0|
|cpptools|ms-vscode|0.10.0|
|debugger-for-chrome|msjsdiag|2.5.2|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.3.1|;

---

Steps to Reproduce:

1. Theme: Dark+, all editors closed, some modification in folder
2. Open terminal, do a `git status` showing the modified file in red
3. Open some source file
4. -> Red text in terminal dims slightly

With no editor open:
![screen shot 2017-02-23 at 3 35 05 pm](https://cloud.githubusercontent.com/assets/9205389/23283975/c594db46-f9dd-11e6-8762-efef9733082c.png)

With editor open:
![screen shot 2017-02-23 at 3 35 25 pm](https://cloud.githubusercontent.com/assets/9205389/23283995/d550d576-f9dd-11e6-87f5-ff9aafe12c71.png)

Also reproduces in 1.9.1.

/cc @rebornix

**Comment by Tyriar** [comment]
Can you check dev tools to see if the red has `font-weight: bold` before and after?

**Comment by chrmarti** [comment]
It doesn't. @rebornix had a look and we gave up after a while. Can you reproduce on your machine?

**Comment by rebornix** [comment]
The funny part is when you open Release Notes, the color dims a little bit and then rolls back quickly. Besides, whenever you open a monaco editor, the terminal widget gets redrawn, it seems that some global css changes and leads to the redrawn (really wild guess).

**Comment by Tyriar** [comment]
I can't reproduce it, it's likely Chromium rendering related though and I doubt we would be able to fix it because of that.
