### ISSUE TITLE
`Reopen with Encoding` should not save file without confirmation

### ISSUE THREAD

**Issue by emisel** [microsoft/vscode#213227]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: MacOS 12.6.6

Steps to Reproduce:

1. Create att sample xml-file with swedish characters:
```
<test>åäö
</test>
```
2. Select "Save with Encoding". Use ISO-8859-10.
3. Close the file and then open it again.
4. VS Code will guess that the encoding is UTF-8 and the file should look like:
```
<test>���
</test>

```
5. Add a whitespace to the file so that VS Code registers that the file has changed.
6. Select "Reopen with Encoding" and use ISO-8859-10 - file will be automatically saved, and will look like:
```
<test>ïŋ―ïŋ―ïŋ―
</test> 
``` 

After step 6 the file is corrupted and I ~can not recover it~ can only recover through the Timeline feature.

**Comment by bpasero** [comment]
You should always be able to restore a previous saved state from the timeline view:

![image](https://github.com/microsoft/vscode/assets/900690/49a9ce7d-2573-4e80-9419-7d417458db50)

Treating this as a fair feature request, we should maybe ask the user what to do if the editor is dirty.

**Comment by emisel** [comment]
> You should always be able to restore a previous saved state from the timeline view:
> 
> ![image](https://private-user-images.githubusercontent.com/900690/332918778-49a9ce7d-2573-4e80-9419-7d417458db50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MDMzMjUsIm5iZiI6MTcxNjQwMzAyNSwicGF0aCI6Ii85MDA2OTAvMzMyOTE4Nzc4LTQ5YTljZTdkLTI1NzMtNGU4MC05NDE5LTdkNDE3NDU4ZGI1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxODM3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjExMzgzNTQ2ZWFlNDY5NDMzMTNlMzkzNTZmNmJkYTE4NTVhM2VkZmYwZGIzZGRlNjNiOTBmZDQ3Nzc1NTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VzHYSQir2PKeAGvAfVcjZU3F9INEomeSFoypcX5JJdc)
> 

Did not know about the the Timeline feature, thanks for the tip!

> Treating this as a fair feature request, we should maybe ask the user what to do if the editor is dirty.

👍
