### ISSUE TITLE
Open VSCode with CLI in file protocol does not work

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/vscode#213215]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:32.757Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.5.0
Steps to Reproduce:

1. `code file:///Users/username/file`
2. Does not open the correct file, but `$PWD/file:/Users/username/file`

**Comment by aeschli** [comment]
This is supported with `code --file-uri file:///Users/username/file`

**Comment by Jack-Works** [comment]
> This is supported with `code --file-uri file:///Users/username/file`

This is inconvenient IMO. Why not support file URLs directly?

**Comment by aeschli** [comment]
I'm not aware of many requests for that. Please open a feature request.
