### ISSUE TITLE
Typing Open Bracket Then Close Bracket Produced Unexpected Result when Text is Selected

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#21326]
1. In a js file (the issue in not language specific) 
2. Select a string such as `abc`
3. Type `(` and then `)` to try and replace `abc` with `()`

**Expected**
After typing `)`, the file is:

```js
()
```

**Actual**
The file is:

```js
())
```

This behavior is feels inconsistent compared to typing `(` and then `)` without a selection:

![feb-23-2017 18-00-02](https://cloud.githubusercontent.com/assets/12821956/23287452/6631c8d4-f9f2-11e6-8b97-5b0c2232ff23.gif)

**Comment by alexandrudima** [comment]
I think this is the very idea of the feature that is considered a bug here.

> when there is a selection and the open bracket is typed, the selection gets surrounded with the bracket pair.

This can be turned off via `editor.autoClosingBrackets`.

**Comment by rebornix** [comment]
This can be merged into https://github.com/Microsoft/vscode/issues/13523 . When you type ( on a selection, we auto surround the selection with  brackets for you. While typing `)`, we don't honor the following unmatched closing paren.
