### ISSUE TITLE
Django official extension

### ISSUE THREAD

**Issue by boschinifederico** [microsoft/vscode#213245]
An official extension for development with the Django framework would be very interesting.
The following features could be implemented:
- Support for Django syntax in html templates with all keywords (for, endfor, if, endif, template tags with filters, etc.)
- Support for abbreviations for keywords (example if you type "for" with tab create structure {% for %} {% endfor %} etc.
- Ability to navigate directly to the definition of a url in the app's urls.py file from an html template via the ctrl+mouse click combo.
<br>

![image](https://github.com/microsoft/vscode/assets/45932646/0d96c252-c800-491e-829d-4d560c14a581)
![image](https://github.com/microsoft/vscode/assets/45932646/a5f4e20c-6318-431c-8fa7-cbf79c93483c)

<br>

I know there are extensions that do much of what you describe, but it would be interesting to have an official one (by the way, the third point is a feature not present in all the extensions I have tried).

**Comment by ImnotEdMateo** [comment]
We need that

**Comment by aeschli** [comment]
Sorry, we have no plans to work on a built-in Django extension
