### ISSUE TITLE
Terminal output slow in VSCode Remote over SSH

### ISSUE THREAD

**Issue by modbw** [microsoft/vscode#213304]
Type: <b>Performance Issue</b>

When we have a lot of terminal output (e.g. building a library like curl) the terminal lags a lot and even VCode itself hangs or loose its connection to the SSH host. If I redirect output to vscode using `someCmd | vscode -` no such lag occours.

A lot of time is spent in then in lineFeed @ InputHandler.ts:709:10 and its children
![image](https://github.com/microsoft/vscode/assets/4498104/bf61e20c-c59f-4523-a9b9-0e20b7ea5a3a)
![image](https://github.com/microsoft/vscode/assets/4498104/44199b2c-11b0-4652-84c3-c16ff5ebb6b3)
![image](https://github.com/microsoft/vscode/assets/4498104/e471ed54-2ae1-4207-88af-f4210fc91b6d)

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.0-107-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics   (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|30.72GB (15.78GB free)|
|Process Argv|--crash-reporter-id ac7bbc20-078a-468a-94f6-3bcaa4308dec|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: build01-xxxxxxxx|
|OS|Linux x64 5.15.0-107-generic|
|CPUs|AMD Ryzen Threadripper 3970X 32-Core Processor (64 x 2200)|
|Memory (System)|125.64GB (99.63GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   135	 18452	code main
    0	   353	 15788	   window
    0	  1131	 18724	window [1] (curl.gsbuild (Working Tree) (curl.gsbuild) - sd (Workspace) [SSH: build01-xxxxxxxx] - Visual Studio Code)
    0	    31	 18800	   crashpad-handler
    0	   872	 19012	   gpu-process
    0	    45	 19060	   utility-network-service
    0	   140	 19960	extensionHost [1]
    0	   111	 19972	shared-process
    0	    82	 19992	fileWatcher [1]
    0	    90	 20764	ptyHost
    0	     8	  3812	     conpty-agent
    0	     5	 20504	     C:\Windows\System32\cmd.exe /c (type "C:\Users\xxxxxxxx\AppData\Local\Temp\vscode-linux-multi-line-command-build01-xxxxxxxx-998210220.sh" | "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 50972 "build01-xxxxxxxx" bash) & exit /b 0
    0	    11	 20124	       "C:\Windows\System32\OpenSSH\ssh.exe"  -T -D 50972 "build01-xxxxxxxx" bash
    0	   303	 23380	   "C:\Program Files\Google\Chrome\Application\chrome.exe" --single-argument https://github.com/open62541/open62541.git
    0	   148	  1144	     window
    0	    55	  1204	     window
    0	    54	  1248	     window
    0	   162	  3376	     window
    0	    93	  6960	     window
    0	   102	  7176	     window
    0	    55	 11356	     window
    0	    23	 12240	     utility-process
    0	    86	 14468	     window
    0	    54	 14560	     window
    0	   155	 18280	     window
    0	    54	 18288	     utility-network-service
    0	    10	 18584	     crashpad-handler
    0	    72	 19836	     window
    0	    57	 21148	     window
    0	    31	 22816	     utility-process
    0	   353	 22852	     gpu-process
    0	   101	 23652	     window
    0	    56	 24484	     window
    0	   191	 25344	     window
    0	    30	 25472	     window
    0	    62	 25892	     window
    0	    55	 26412	     window
    0	    65	 26448	     window
    0	    54	 26556	     window
    0	   101	 24972	   utility-process
    0	   111	 25824	window [3] (Issue Reporter)

Remote: SSH: build01-xxxxxxxx
CPU %	Mem MB	   PID	Process
    0	     0	1599731	remote agent
    0	     0	1599758	   extension-host
    0	     0	1600918	     /home/xxxxxxxx/.vscode-server/extensions/ms-vscode.cpptools-1.20.5-linux-x64/bin/cpptools
    0	     0	1600960	     /home/xxxxxxxx/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/node /home/xxxxxxxx/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=1599758
    0	     0	1602232	     /home/xxxxxxxx/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/node /home/xxxxxxxx/.vscode-server/extensions/streetsidesoftware.code-spell-checker-3.0.1/packages/_server/dist/main.cjs --node-ipc --clientProcessId=1599758
    0	     0	1635331	     /home/xxxxxxxx/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/node /home/xxxxxxxx/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/extensions/markdown-language-features/server/dist/node/workerMain --node-ipc --clientProcessId=1599758
    0	     0	1936539	     perl -MPerl::LanguageServer -e Perl::LanguageServer::run -- --port 13603 --log-level 2 --log-file  --version 2.6.2
    0	     0	1599769	   ptyHost
    0	     0	1600986	     /bin/bash --rcfile /home/xxxxxxxx/projects/sd/MCP/Devices/MCPJ/tools/batch/setenv.sh
    0	     0	2081889	     /bin/bash --rcfile /home/xxxxxxxx/projects/sd/MCP/Devices/MCPJ/tools/batch/setenv.sh
    0	     0	2527577	     /bin/bash --rcfile /home/xxxxxxxx/projects/sd/MCP/Devices/MCPJ/tools/batch/setenv.sh
    1	     0	1599780	   fileWatcher
    0	     0	1785119	   /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	1785120	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: SSH: build01-xxxxxxxx;
```

</details>
<details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
pascal|ale|9.8.0
pascal-formatter|ale|2.8.1
vscode-innosetup|cho|1.9.2
doxdocgen|csc|1.4.0
autoit|Dam|1.0.12
xml|Dot|2.5.1
gitlens|eam|15.0.4
vscode-google-translate|fun|1.4.13
svn-scm|joh|2.17.0
cortex-debug|mar|1.12.1
vscode-catch2-test-adapter|mat|4.12.0
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.25
peripheral-viewer|mcu|1.4.6
rtos-views|mcu|0.0.7
mesonbuild|mes|1.24.0
git-graph|mhu|1.30.0
cmake-tools|ms-|1.17.17
cpptools|ms-|1.20.5
hexeditor|ms-|1.10.0
perl|ric|2.6.2
shader|sle|1.1.5
code-spell-checker|str|3.0.1
code-spell-checker-german|str|2.3.2
cmake|twx|0.0.17
cfg-language-features|weg|1.0.0
srecord|xia|0.0.5
Doxygen|bbe|1.0.0
systemd-unit-file|coo|1.0.6
vscode-systemd-support|han|2.2.0
kconfig|luv|1.0.3
debug-tracker-vscode|mcu|0.0.15
peripheral-viewer|mcu|1.4.6
cadsoft-ulp|mic|1.0.0
remote-containers|ms-|0.362.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
notepadplusplus-keybindings|ms-|1.0.7
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
devicetree|plo|0.1.1
errorlens|use|3.17.0
vscode-icons|vsc|12.7.0
linkerscript|Zix|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
f3je6385:31013174
pythoncenvptcf:31049071
a69g1124:31046351
dvdeprecationcf:31052040
pythonprc:31047982
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by meganrogge** [comment]
do you know if this just started happening for you recently?

**Comment by meganrogge** [comment]
also, what is your value for `terminal.integrated.scrollback`?

**Comment by modbw** [comment]
`terminal.integrated.scrollback` is set to 10000. I was not able to reproduce this behavior with a simple shell loop creating a lot of text. We observed this behavior for about two or three month now but can't tell exactly.

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/213174

**Comment by Tyriar** [comment]
Should also be fixed by https://github.com/xtermjs/xterm.js/pull/5066
