### ISSUE TITLE
Test: text-to-speech in Chat

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#213355]
Refs https://github.com/microsoft/vscode/issues/196261

- [x] Windows @chrmarti 
- [x] macOS @Tyriar 
- [x] Linux @justschen 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23213355%0A%0A&assignees=bpasero)

---

**Setup:**
* latest pre-release version of GitHub Copilot Chat
* latest pre-release version of [VS Code Speech](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-speech)

**Testing:**
* test in various locations that offer Copilot chat including panel chat, quick open chat, inline chat, terminal chat
* from a chat response verify you can click on the 🔈 icon and get the response read out aloud in english
* click the animated pulse icon in the chat input or the 🔈 icon again to stop playback anytime
* use the 🎤 action to use voice for a chat request and verify the response is read out aloud automatically while streaming in
* verify that automated reading does not occur when you configure `accessibility.voice.autoSynthesize: false`
* change `accessibility.voice.speechLanguage` to a language of choice, have a response of that language and verify its being read out aloud properly in that language (you are getting asked to install a language extension if needed)
* play around with various responses (with / without code, references, etc.) and ensure the synthesis is making sense to you **[1]**

**[1]** Note: synthesis may jump over certain parts of the output, for example file references are not read out and source code is not treated any specially and may skip over some characters. We want to explore using [Speech Markup Language](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-synthesis-markup) for this in the future but are a bit limited in what the local model allows to do.

**Comment by justschen** [comment]
@bpasero having issues starting `ctrl + i` on linux (ubunto 22) when selecting or moving my cursor around in the editor

`ctrl + i` works fine to focus on chat panel and start recording tho (when not focusing in an editor)

I see the keybindings here:
<img width="1115" alt="Screenshot 2024-05-28 at 10 58 44 AM" src="https://github.com/microsoft/vscode/assets/54879025/59316e1b-2fb8-404c-89f7-f420c79cc5df">

**Comment by justschen** [comment]
tested in chinese as well, works nicely! very cool that it works with a mix of english terms + chinese as well 👍 
<img width="692" alt="Screenshot 2024-05-28 at 11 15 08 AM" src="https://github.com/microsoft/vscode/assets/54879025/7f9cccca-60f1-4418-a321-89bbaedd6612">
