### ISSUE TITLE
"Your First Extension" quickstart guide broken out of the box

### ISSUE THREAD

**Issue by japem** [microsoft/vscode#213338]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: OSX 14.3

Steps to Reproduce:

Follow the instructions in the [extension quickstart guide](https://code.visualstudio.com/api/get-started/your-first-extension) up to the "Run the Hello World command from the Command Palette" step.

The "Hello World" command doesn't show up. I can't find any reference to my extension anywhere in the debug window (extension view, output logs, etc.); I'm not sure exactly where this would be expected to show up, but it's nowhere to be found.

- `yo` version - 5.0.0 (latest)
- `generator-code` version - 1.9.0 (latest)

**Comment by japem** [comment]
The issue was that the extension code wasn't at the top level of my current VSCode window. It worked when I re-opened the extension folder in its own window. This issue can be closed, but it might be nice to mention in the guide that this is required. IMO it's not intuitive that this is required if you're launching it directly from `extensions.ts` as the guide says.

**Comment by roblourens** [comment]
Sorry for the confusion. The last step of the yo generator opens vscode to the correct folder. So if someone follows those steps, they should end up in the right place.
