### ISSUE TITLE
`Cmd+W` is closing the window with opened tabs

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#213324]
Reproduced on OSS, Mac

Steps to Reproduce:

1. Open Code OSS
2. Open a file
3. Press cmd+w
 🐛 Closes the window

Bisect points to this commit - aa31bfc9fd1746626b3efe86f41b9c172d5f4d23

**Comment by bpasero** [comment]
I can reproduce.

**Comment by bpasero** [comment]
There are context keys that are now loose, for example `EditorsVisibleContext`

**Comment by benibenj** [comment]
Follow up work #213334
