### ISSUE TITLE
WSL/Remote SSH Open Folder issues

### ISSUE THREAD

**Issue by tzengshinfu** [microsoft/vscode#213351]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1 (user setup)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:
When connecting to WSL or Remote SSH
_p.s. Boldface represents the same folder name_

A. Unable to go back to root directory
1. Open `Open Folder...` to the user's home directory
2. Click (..) to go back one level to /home
3. Click (..) again and nothing happens

B. Up one level (..) does not work
Example:
/**folderA**/folderB/**folderA**/folderC

1. Open `Open Folder...` to /**folderA**/folderB/**folderA**/folderC
2. Click (..) to go back one level to /**folderA**/folderB/**folderA**
3. Click (..) again and nothing happens.

C. Unable to enter the next level folder
Example:
/**folderD**/**folderD**

1. Open `Open Folder...` to /folderD
2. Click on the next level folder `folderD` and nothing happens.

**Comment by connor4312** [comment]
Seems to be picked-related, though I don't repro this
