### ISSUE TITLE
VS Code crashes when left idle (behaviour is inconsistent)

### ISSUE THREAD

**Issue by ritcoder** [Microsoft/vscode#2133]
This does not happen every time it is idea but it mostly crashes at least once a day. It gets slow and then crashes. I've been using it exclusively to write elm code so I don't know if it has to do with the plugin.

How can I get detailed log next time it happens?

**Comment by Tyriar** [comment]
Likely a duplicate of https://github.com/Microsoft/vscode/issues/508

**Comment by weinand** [comment]
@ritcoder what OS?

**Comment by ritcoder** [comment]
Using windows 10 pro (insider on the slow ring)
Code version is 0.10.6

**Comment by ritcoder** [comment]
@Tyriar Yes. Looks like you might be experiencing the same issue.

**Comment by bpasero** [comment]
#508
