### ISSUE TITLE
Node CMD flashing when Executing Any Command

### ISSUE THREAD

**Issue by Abhishekrazy** [microsoft/vscode#213319]
Does this issue occur when all extensions are disabled?: Yes/No
No

- VS Code Version: 1.89.1
- OS Version: Windows 11 Pro Version 23H2 Build(22631.3593)

Steps to Reproduce:

1. Creating SFDX Project.
2. Connect the Org
3. Retrieve the Metadata from org
4. After command runs completely node.exe in CMD flashing on the screen

**Comment by Abhishekrazy** [comment]
![image](https://github.com/microsoft/vscode/assets/20985137/e8253389-ee99-4d13-a09f-1873c64bc967)

**Comment by Abhishekrazy** [comment]
https://github.com/microsoft/vscode/assets/20985137/35438b96-912d-4675-9957-583618659d1d

**Comment by lszomoru** [comment]
I would suggest that you reach out to the extension author that provides the support for SFDX Project as this does not seem to be related to VS Code. Thank you very much!
