### ISSUE TITLE
adding a folder

### ISSUE THREAD

**Issue by Clair3e** [microsoft/vscode#213333]
Type: <b>Bug</b>

I am unable to see my folder once i add it to the explorer

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.10.4
phpserver|bra|3.0.2
doxdocgen|csc|1.4.0
docs-images|doc|1.0.3
code-runner|for|0.12.2
better-cpp-syntax|jef|1.17.2
cpptools-extension-pack|ms-|1.3.0
format-html-in-php|rif|1.7.0
cmake|twx|0.0.17
php-debug|xde|1.34.0
php-pack|xde|1.0.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
0ee40948:31013168
pythoncenvptcf:31049071
fchga941:31046352
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by lramos15** [comment]
Try F1-> Reset View Locations.

**Comment by Clair3e** [comment]
Thank youuuuuuuuuuuu so much
