### ISSUE TITLE
test: keybinding resolution in accessibility help dialogs

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#213343]
Refs #210665, #210695

- [x] Windows @luabud 
- [x] macOS @ulugbekna 
- [x] anyOS @connor4312 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23213343%0A%0A&assignees=meganrogge)

---

We now resolve keybindings in accessibility help dialogs in the `AccessibleViewService` for more uniform language and to offer a quick way for users to set unassigned keybindings.

In screen reader mode, please verify that with focus in the following components, when you open the help dialog, `alt+f1`, it reflects the keybindings correctly. Unassign keybindings for commands listed and make sure that using `Option+K` opens a quickpick which allows you to configure them:
- terminal
- notebook cells
- editor
- chat responses
- inline chat responses
- comments

**Comment by ulugbekna** [comment]
> using Option+L opens a quickpick which allows you to configure them:

Did you mean option+k? 

![Image](https://github.com/microsoft/vscode/assets/16353531/ba498615-190e-4c5c-a766-fe070c50747a)

> Focus Sticky Scroll, configure a keybinding (Option+K) to focus the currently nested scopes.

Would it be easier to comprehend if keybinding configuration was mentioned as a side note in parentheses? eg "Focus Sticky Scroll command to focus currently nested scopes (press Option+K to set a keybinding)"

**Comment by meganrogge** [comment]
Yes, but I currently do this via string replacement, so that's not possible @ulugbekna. see #213420

**Comment by connor4312** [comment]
I tested this and it worked in some cases, but not others. From the naive user point of view it was kind of random: 

![image](https://github.com/microsoft/vscode/assets/2230985/2b826184-5995-4649-ac49-fd69018f526f)

In PM Megan mentioned this is covered by an existing bug.

**Comment by AP1400** [comment]
This  think is happening  intell you give me my money
