### ISSUE TITLE
Add an option to share an extension

### ISSUE THREAD

**Issue by daB0bby** [Microsoft/vscode#21339]
It would be great if the would be an option in the extension view for sharing an extension.

```
Share
|- Copy Link
|- ... Other options
```

**Comment by sandy081** [comment]
@daB0bby May I know what is the usecase you are having under sharing the extension?

Is it to share with the team just to other user or recommend the extension for the workspace?

**Comment by daB0bby** [comment]
I colleague of mine is using VSCode too. So I wanted to share an extension with him.

Ich don't want to Google for it to find it in the marketplace. It would be much easier to share it directly from within VSCode.

**Comment by aualdrich** [comment]
I, too, would love this feature, as we like to share cool extensions with other team members in our Slack channel.

**Comment by sandy081** [comment]
Since we do not have plans to implement this in near future and also there is not many requests for this feature, closing this as out of scope.
