### ISSUE TITLE
Typing text in a link - underline shifts after a second

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#21331]
Does not repro in 1.9

- Have an underlined link in an editor
- Type more text in the link
- Its underline starts too high, then after a second, drops down to the right spot

![feb-23-2017 21-15-34](https://cloud.githubusercontent.com/assets/323878/23291432/52fba580-fa0d-11e6-8a3d-53bd4843498e.gif)

**Comment by alexandrudima** [comment]
Introduced with #19645
