### ISSUE TITLE
In shell scripts bracket matching is broken in some expressions and breaks colorisation

### ISSUE THREAD

**Issue by prosenboim** [microsoft/vscode#213303]
Type: <b>Bug</b>

In bash script, line such as 
var1=$(( (var2 & 1 << ${var3})>>var4 ))

Causes first bracket to be colored red, despite it is matched. Also, colorization after this line is broken.

VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin x64 22.6.0
Modes:
Remote OS version: Linux x64 5.15.0-105-generic
Remote OS version: Linux x64 5.15.0-105-generic
Remote OS version: Linux x64 5.15.0-105-generic
Remote OS version: Linux x64 5.15.0-105-generic
Remote OS version: Linux x64 5.15.0-105-generic
Remote OS version: Linux x64 5.15.0-105-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id f92d0235-e90f-4b41-a89c-01040511f220|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: prosenboim-dev|
|OS|Linux x64 5.15.0-105-generic|
|CPUs|Intel(R) Xeon(R) Gold 6152 CPU @ 2.10GHz (6 x 2095)|
|Memory (System)|31.34GB (21.63GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: wbs01-wbb07|
|OS|Linux x64 5.15.0-105-generic|
|CPUs|Intel Core Processor (Broadwell) (6 x 1995)|
|Memory (System)|15.61GB (12.61GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: prosenboim-dev|
|OS|Linux x64 5.15.0-105-generic|
|CPUs|Intel(R) Xeon(R) Gold 6152 CPU @ 2.10GHz (6 x 2095)|
|Memory (System)|31.34GB (21.63GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: pavel-desktop|
|OS|Linux x64 5.15.0-105-generic|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 800)|
|Memory (System)|31.25GB (29.05GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: wbs01-wbb07|
|OS|Linux x64 5.15.0-105-generic|
|CPUs|Intel Core Processor (Broadwell) (6 x 1995)|
|Memory (System)|15.61GB (12.61GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: prosenboim-dev|
|OS|Linux x64 5.15.0-105-generic|
|CPUs|Intel(R) Xeon(R) Gold 6152 CPU @ 2.10GHz (6 x 2095)|
|Memory (System)|31.34GB (21.63GB free)|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.362.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
githistory|don|0.6.20
gitlens|eam|15.0.4
copilot|Git|1.194.0
copilot-chat|Git|0.15.2
vscode-pull-request-github|Git|0.88.1
vscode-dotnet-runtime|ms-|2.0.5
autopep8|ms-|2024.1.11371013
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.7.11371017
python|ms-|2024.7.11371014
vscode-pylance|ms-|2024.5.101
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
rust-analyzer|rus|0.3.1958
even-better-toml|tam|0.19.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31049070
fchga941:31046352
dvdeprecation:31052039
pythonprc:31047982
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by RedCMD** [comment]
should report to the upstream grammar repo https://github.com/jeff-hykin/better-shell-syntax

**Comment by prosenboim** [comment]
I'm not using better shell syntax extention

**Comment by RedCMD** [comment]
VSCode uses the grammar as the default Shell script syntax highlighter
