### ISSUE TITLE
How should this be set

### ISSUE THREAD

**Issue by hulang** [Microsoft/vscode#21335]
- VSCode Version:1.9.1
- OS Version:win 7 x64

Steps to Reproduce:
```javascript
<script>{$rulejson}</script>
```
This is my code
will automatically be converted to
```javascript
<script>
	{
		$rulejson
	}
</script>
```
How to set no conversion?
What I want is：
```javascript
<script>{$rulejson}</script>
```

**Comment by roblourens** [comment]
Looks like it's being formatted. Are you running Format Document, or do you have `editor.formatOn(something)` enabled in settings?

**Comment by hulang** [comment]
By default：false,I don't have to set。。。set :true，Also same

**Comment by mjbvz** [comment]
@hulang I'm unable to repo this. A few questions:

* What language are you working in? Html?
* What extension do you have installed? Does this repo if you run code using `--disable-extenions`?
* Please share your workspace/user settings for formatting
* Please share a complete document that shows this issue

Thanks

**Comment by mjbvz** [comment]
Closing this as I'm unable to repo it  and do not have enough information to investigate further

@hulang If you are still running into this problem, please provide the requested information and we can reopen the issue

Thanks

**Comment by hulang** [comment]
Upgrade to 1.10.2 has been resolved
