### ISSUE TITLE
Unable to Execute Third-Party Unit Test Package with VSCode Debugger

### ISSUE THREAD

**Issue by TeomanEgeSelcuk** [microsoft/vscode#213305]
**VS Code Version:** 1.89.1
**OS Version:** 23H2 (Windows 11)

**Steps to Reproduce:**

1. Create a new Python project in VSCode with a virtual environment (myenv) and install DeepEval using pip.
2. Create a wrapper script (run_deepeval.py) to handle the DeepEval command.
3. Configure the launch.json file with the following settings:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Deepeval",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/langchain_env/run_deepeval.py",
            "args": [
                "test",
                "run",
                "${workspaceFolder}/tests/test_${fileBasename}"
            ],
            "debugStdLib": true,
            "justMyCode": true
        }
    ]
}
```
4. Try to debug the project using the VSCode debugger.

**Expected Behavior:**
The VSCode debugger should execute the DeepEval package and run the unit tests successfully.

**Actual Behavior:**
The VSCode debugger throws an error:
```
C:\Users\myuser\anaconda3\envs\myenv\python.exe: No module named deepeval.__main__; 'deepeval' is a package and cannot be directly executed
```
**Additional Information:**

* I have ensured that DeepEval is installed in the virtual environment (myenv).
* I have verified that the Python interpreter is correctly set to the virtual environment in VSCode.
* I have tried upgrading DeepEval to the latest version (0.21.45) using pip.

**Question:**
How can I configure VSCode to properly execute the DeepEval package within the debugger? Is there something wrong with my launch.json configuration, or is there a better way to set this up?

**Comment by roblourens** [comment]
Please file this on the Python debug extension repo, thanks

**Comment by TeomanEgeSelcuk** [comment]
Hi, I couldn't find the link to the issue, can you please provide it to me?
