### ISSUE TITLE
Test: accessible view refactor

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#213342]
Refs #212138

- [x] Windows @andreamah 
- [x] macOS @isidorn 
- [ ] anyOS @chrmarti 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23213342%0A%0A&assignees=meganrogge)

---

The accessible view implementation was overhauled to use an `AccessibleViewRegistry` this iteration.

Please verify that in screen reader mode, the accessible views still open with `alt+f1` (help, if available) and `alt+f2` (view) when the following are focused via the keyboard:
- terminal
- notebook cells
- editor
- chat responses
- inline chat responses
- comments
- inline completions (no help dialog)
- notifications (no help dialog)
- hovers (no help dialog)

**Comment by andreamah** [comment]
Seemed like a fairly smooth refactor! 👍

**Comment by chrmarti** [comment]
Got it, that also works for me on Linux. 👍
