### ISSUE TITLE
By minimizing the vscode window, parallel computing limits the number of processes

### ISSUE THREAD

**Issue by MuriloZucatelli** [microsoft/vscode#213476]
Type: <b>Bug</b>

Using a Python multiprocessing package
With the Pool tool
create a task to use almost 100% of the CPU for a long period (>2 min)
When running, minimize the Vscode window and you will see the CPU usage drop to 40%, then to 10%

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900KF (24 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.82GB (39.96GB free)|
|Process Argv|C:\\Users\\INTEL\\Documents\\MEGA\\Aleatórios\\remove_outliers.py --crash-reporter-id 579e5406-5854-4b79-8e9e-fffc08f3f9b7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
c-cpp-compile-run|dan|1.0.58
vscode-pull-request-github|Git|0.88.1
gc-excelviewer|Gra|4.2.59
latex-workshop|Jam|9.20.1
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
vscode-language-pack-pt-BR|MS-|1.89.2024050109
vscode-dotnet-runtime|ms-|2.0.5
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.6.0
flake8|ms-|2023.10.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.2
cmake-tools|ms-|1.17.17
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
autodocstring|njp|0.6.1
pdf|tom|1.2.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
showvideoc:31016891
chatpanelc:31048052
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31049070
a69g1124:31046351
dvdeprecationcf:31052040
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by deepak1556** [comment]
Can you provide a detailed repro with clear steps, thanks!
