### ISSUE TITLE
Switch window shortcut Ctrl + W doesn’t work from integrated terminal

### ISSUE THREAD

**Issue by sergeysolovev** [microsoft/vscode#213444]
Type: <b>Bug</b>

Open integrated terminal from menu View -> Terminal. Press Ctrl + W shortcut which is supposed to open the “Switch window” popup, but it doesn’t. It works as expected when the terminal is not on.

Similar features like Cmd + P or Shift + Cmd + P work regardless of the integrated terminal status. So it seems to be a bug.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:32.757Z)
OS version: Darwin arm64 23.2.0
Modes:
Remote OS version: Linux x64 6.1.66-91.160.amzn2023.x86_64
Remote OS version: Linux x64 6.1.90-99.173.amzn2023.x86_64
Remote OS version: Linux x64 6.1.79-99.164.amzn2023.x86_64
Remote OS version: Linux x64 5.15.0-102-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id b96fd8bb-ff73-4546-ab0a-20ff4aa56385 --crash-reporter-id b96fd8bb-ff73-4546-ab0a-20ff4aa56385 --crash-reporter-id b96fd8bb-ff73-4546-ab0a-20ff4aa56385|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sg-01|
|OS|Linux x64 6.1.66-91.160.amzn2023.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz (4 x 3596)|
|Memory (System)|7.55GB (4.42GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sg-02|
|OS|Linux x64 6.1.90-99.173.amzn2023.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz (4 x 3387)|
|Memory (System)|7.49GB (5.14GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sg-03|
|OS|Linux x64 6.1.79-99.164.amzn2023.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz (4 x 3408)|
|Memory (System)|7.49GB (5.44GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ov-01|
|OS|Linux x64 5.15.0-102-generic|
|CPUs|Intel(R) Xeon(R) E-2386G CPU @ 3.50GHz (12 x 3500)|
|Memory (System)|31.23GB (19.33GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-graphql-syntax|Gra|1.3.6
language-cython|guy|0.0.8
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
everforest|sai|0.3.0
gruvbox-material|sai|6.5.2
vscode-icons|vsc|12.7.0
JavaScriptSnippets|xab|1.8.0
vscode-deno|den|3.37.1
gitpod-remote-ssh|git|0.0.51
prettier-sql-vscode|inf|1.6.0
center-editor-window|kai|2.3.0
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31049070
fchga941:31046352
dvdeprecationcf:31052040
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by meganrogge** [comment]
you can add that to `terminal.integrated.commandsToSkipShell` if you want it to skip the terminal

**Comment by sergeysolovev** [comment]
@meganrogge amazing, thank you, it worked!
