### ISSUE TITLE
Using SCP copy file proctocol when using ssh.

### ISSUE THREAD

**Issue by myagizmaktav** [microsoft/vscode#213481]
In VSCode, uploading files to an SSH server is straightforward using the platform's capabilities. However, downloading files from an SSH server via the VSCode platform is not directly supported. To achieve this, one could use the SCP command within the SSH protocol.

**Comment by myagizmaktav** [comment]
![image](https://github.com/microsoft/vscode/assets/115627863/d0529337-28f7-4b74-b3aa-3b63d709f6ce)

**Comment by roblourens** [comment]
You can right click a file in the Explorer and click "Download", is that what you want?

**Comment by myagizmaktav** [comment]
> Member

Yes kind of.

**Comment by roblourens** [comment]
It works for the folder too, try it
