### ISSUE TITLE
opening folder issue

### ISSUE THREAD

**Issue by viral-vadera** [microsoft/vscode#213442]
Type: <b>Bug</b>

while opening a folder on file browser in ubuntu desktop , the selected folder opens when clicked on open button but if the user double clicks on folder the whole visual studio ide quits. 

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 6.8.0-31-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx (4 x 2794)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|9.59GB (4.94GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id cfd34dad-636f-4e3d-9586-8521edd6459d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
945dj816:31013170
pythoncenvptcf:31049071
a69g1124:31058053
dvdeprecationcf:31052040
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by Sanzi87** [comment]
I have the same issue. VSCode has some issue with .mjs files. 

Example 1: If I try to open a Python project, VSCode can open it, but If I create a Next JS project what includes 2 pcs .mjs files (next.config.mjs and postcss.config.mjs) and I try to open the folder from the menu (File>Open Folder), VSCode just quit. If I delete these 2 files temporarily, VSCode can open the folder.
There is 2 ways to open this folder. 1. From the terminal, I can use "code ." command and it opens in VSCode or 2. If I opened this folder earlier I can reopen it from the "File>Open recent>Foldername"

Example 2: If the folder is already open and I click the "File>Open Workplace from File..." button, VSCode quit again. (This not happen if I delete the .mjs files.

Example 3: If I delete a .mjs file and I try to restore it with Ctrl+Z. VSCode Quiet again.

VS Code version: Code 1.89.1
OS version: Linux x64 6.8.0-31-generic snap

**Comment by rzhao271** [comment]
It sounds like the product is crashing in both cases.
Could you two create crash reports following the [Wiki instructions](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues)?

**Comment by deepak1556** [comment]
@Sanzi87 if you can share a minimal repro (folder with problematic .mjs file) to demonstrate the issue it would be helpful for us to debug the issue further.

**Comment by Sanzi87** [comment]
> @Sanzi87 if you can share a minimal repro (folder with problematic .mjs file) to demonstrate the issue it would be helpful for us to debug the issue further.

The simplest way to reproduce the error is to create a new folder, which you then open in VS Code. After that, create a new Next JS 14 project in the VS Code terminal by using the command: "npx create-next-app ." Then, wait for the project to be set up. The .mjs files will be in the project directory. If you try to open the project from the file menu, VS Code exits.

Of course I can share these original files from a Next JS project too. Just uncompress the zip file, open the VS Code and select File>Open Folder and select the unzipped map. (My OS is Ubuntu 24.04.)
[vscodemjsissue.zip](https://github.com/user-attachments/files/15517743/vscodemjsissue.zip)

**Comment by Sanzi87** [comment]
> > @Sanzi87 if you can share a minimal repro (folder with problematic .mjs file) to demonstrate the issue it would be helpful for us to debug the issue further.
> 
> The simplest way to reproduce the error is to create a new folder, which you then open in VS Code. After that, create a new Next JS 14 project in the VS Code terminal by using the command: "npx create-next-app ." Then, wait for the project to be set up. The .mjs files will be in the project directory. If you try to open the project from the file menu, VS Code exits.
> 
> Of course I can share these original files from a Next JS project too. Just uncompress the zip file, open the VS Code and select File>Open Folder and select the unzipped map. (My OS is Ubuntu 24.04.) [vscodemjsissue.zip](https://github.com/user-attachments/files/15517743/vscodemjsissue.zip)

There is a bug in VS Code with commenting in .mjs files. If you create a new folder, open it in VS Code, create a something.mjs file, and just write a comment line, for example: "/* something */", then save it, VS Code will exit.
