### ISSUE TITLE
please help me. I tried many times but my vs code is not working in my laptop.It does not support any language like html,js,c,c++

### ISSUE THREAD

**Issue by sneha24-sg** [microsoft/vscode#213447]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
```

**Comment by sneha24-sg** [comment]
no i nstalled all extension

**Comment by aiday-mar** [comment]
Hi, could you please add more information as to what exactly is not working in VS Code. Please include a screen recording showing the issue.
