### ISSUE TITLE
Improvement: method overriding

### ISSUE THREAD

**Issue by grafa** [Microsoft/vscode#21343]
Hi guys,

I often override methods because Django :rofl: I was wondering if Code can help me override methods which whispers me. Like if I hit let's say SHIFT + Enter onto whispered row it would paste the original method definition.

Example:

I type:
```python
def get_a
```

I get whispered:
![image](https://cloud.githubusercontent.com/assets/198654/23300165/b03166dc-fa84-11e6-8fad-a87773c70706.png)

I hit SHIFT + Enter and I get
![image](https://cloud.githubusercontent.com/assets/198654/23300209/dc817600-fa84-11e6-972b-37ace3ce818f.png)

Thank you and I'm sorry if this is duplicated task. I've looked around but found nothing.

**Comment by bpasero** [comment]
I think this very much depends on the language you are using to provide this kind of information. I know for example that in TS we now have a quick fix to implement an interface but I would also love to get this into IntelliSense when I type in the body of the class.

**Comment by mjbvz** [comment]
@bpasero On the TypeScript side, https://github.com/Microsoft/TypeScript/issues/7158 tracks returning inherited methods in the suggestion list. This suggestion itself would not fill in the full signature , but we could leverage `typescript.useCodeSnippetsOnMethodSuggest` to do this

**Comment by grafa** [comment]
For start (and I guess for 80% of cases) it would be cool enough just to make Code to write in the line it's whispering (just like in my screens).

Thank you wery much, please keep Code making better and better ;)

**Comment by alexandrudima** [comment]
@grafa I think the best in this specific case is to create an issue in the Python extension you are using.

I think our completion API is good enough to insert such an edit.

**Comment by grafa** [comment]
So I should create the issue for every possible language that can override methods?

There is really no way to implement feature in Code itself to be able to write in the current file when a keyboard shortcut is pressed on highlighted whispered item just like I've described in my first post?

It seems to me like a pretty much easy solution that solves the problem and is good enough for 99% cases.

**Comment by mjbvz** [comment]
@grafa Yes, I please open issues against the language where you would like to see this functionality. For Python, please file an issue against the Python extension: https://github.com/DonJayamanne/pythonVSCode/issues/new

Thanks
