### ISSUE TITLE
Too much bottom padding in resizeable hovers

### ISSUE THREAD

**Issue by klaussner** [microsoft/vscode#213460]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0-insider (e82e806f172f30aecb0e6bb04c01f37780c16f22)
- OS Version: macOS Sonoma 14.5

Steps to Reproduce:

1. Hover over a symbol. The widget has too much padding at the bottom.

<img width="705" alt="Padding 1" src="https://github.com/microsoft/vscode/assets/1312807/b75cc780-efe4-4e4c-bab8-98eb8881a8d6">

<img width="705" alt="Padding 2" src="https://github.com/microsoft/vscode/assets/1312807/46072341-d1ad-4180-82f0-927842b79c1d">

https://github.com/microsoft/vscode/assets/1312807/79f59602-cf12-4cc2-a950-4f4c042f35ff

**Comment by klaussner** [comment]
I think the fix for this issue was reverted in these two pull requests: https://github.com/microsoft/vscode/pull/213831 and https://github.com/microsoft/vscode/pull/214001. Did the removal of the bottom padding cause issues or is there another reason why it was reverted? @aiday-mar

**Comment by aiday-mar** [comment]
Hi yes thank you for commenting. Indeed the padding removal was reverted because removing it causes an incorrect layout of the hover unfortunately. I have to look at how to remove the padding and keep the layout the same. I will reopen this issue.

**Comment by aiday-mar** [comment]
This was recently fixed
