### ISSUE TITLE
Opening with -r resizes window.

### ISSUE THREAD

**Issue by paulgmiller** [Microsoft/vscode#2134]
In windows 10 on version 0.10.6. When I open a file with -r. (which I do a lot in a large codebase). It takes my window and resizes it to what I assume is the original window size. Bad because I keep my editor and consiole in maximized split screen.

![image](https://cloud.githubusercontent.com/assets/1474379/12466402/31b5c456-bf89-11e5-856e-6fe313c7620b.png)

Can take a video if you can't easily  repo.

**Comment by bpasero** [comment]
Dupe and fixed.
