### ISSUE TITLE
Update snippets to no longer have command. syntax

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#21345]
![screen shot 2017-02-24 at 11 36 33](https://cloud.githubusercontent.com/assets/1926584/23300781/6e024cba-fa87-11e6-9896-ebb4b79ee0a8.png)

**Comment by weinand** [comment]
This has been fixed 2 days ago. Just create a new snippet with the Insider release.

**Comment by isidorn** [comment]
Oke
