### ISSUE TITLE
${command.xxx} deprecated syntax is not shown in tasks.json

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#21340]
Ref: #16064

- VSCode Version: 1.10.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Go to tasks.json, change `"command"` attribute of the task to `"${env.Path}"`.
2. No highlight that this syntax is deprecated.

Works in launch.json.

**Comment by isidorn** [comment]
Not so easy to do in the tasks world, will need @dbaeumer for this

**Comment by isidorn** [comment]
Assigning to @dbaeumer to add the [following](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/node/debugAdapter.ts#L230) for his tasks schema
