### ISSUE TITLE
`file:` URIs render as text in the Markdown Preview pane.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/vscode#213408]
<table><tr>
	<th>Does this issue occur when all extensions are disabled?</th>
	<td>Yes</td>
</tr></table>

<table><tr>
	<th> VS Code Version </th>
	<td> <code> code-insiders-1.90.0-1716371939.el8.src.rpm </code> </td>
</tr><tr>
	<th> OS Version </th>
	<td> <a href='https://download.fedoraproject.org/pub/fedora/linux/releases/test/40_Beta/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40_Beta-1.10.iso'> <code> cpe:/o:fedoraproject:fedora:40 </code> </a> </td>
</tr></table>

#### **Steps to Reproduce**

As https://github.com/yzhang-gh/vscode-markdown/issues/688#issuecomment-1229240520 explains, enter

```MD
[URI](file://localhost/)
```

into a `.MD` file, and then preview it (with <kbd>Control</kbd> + <kbd>Shift</kbd> + <kbd>V</kbd>):

> ![Screenshot_20240524_183232](https://github.com/microsoft/vscode/assets/42837531/5a24a434-3f1e-4db2-b9b9-e4f5b3d5f5e1)

**Comment by mjbvz** [comment]
Haven't had a compelling reason to support them: https://insiders.vscode.dev/github/microsoft/vscode/blob/main/extensions/markdown-language-features/src/markdownEngine.ts#L305

If you can provide a good use case plus PR, I'd potentially reconsider

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/vscode/issues/213408#issuecomment-2174376317

@mjbvz, I doubt I can provide a useful PR since I'm not familiar with the technologies used in VSC's codebase, but I can certainly provide rationale for the feature: https://gitlab.com/rokejulianlockhart/rokejulianlockhart/-/blob/e8c48058f40e67811c1b510aeaa94315b9e8bf86/%09%60%7Btitle:%20%22Non-Metadata%22,%09id:%20%22s1gvg2%22%7D%60%7B.JSON5%7D.dir/%20%20%5B-%5D%09%60%7Btitle:%20%22Technical%22,%09id:%20%22s20cxw%22%7D%60%7B.JSON5%7D.dir/.%20%5B~%5D%09%60%7Btitle:%20%22Microsoft%20Windows%22,%09id:%20%22%22%7D%60%7B.json5%7D.dir/%09%60%7Btitle:%20%22Logonography%20and%20Iconography%22,%09id:%20%22%22%7D%60%7B.JSON5%7D.txt.MD is a list of icons embedded in DLLs and binaries, which necessarily links to paths. I can put those paths in the standard Win32 format (like `[Windows.UI.ShellCommon\Images](C:%255CWindows%255CSystemResources%255CWindows.UI.ShellCommon%255CImages)`) but all my documents use URIs, and I'd like to extend this document to UNIX-derived OSes too, so I'd like to have the format be consistent.
