### ISSUE TITLE
Exception widget: allow to click on file links if there are any

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21349]
Would be nice if the error stack was actually clickable to navigate:

![image](https://cloud.githubusercontent.com/assets/900690/23301991/f4b93282-fa8c-11e6-8234-aa2e9306fbc8.png)

**Comment by weinand** [comment]
@roblourens We should consider to apply source maps to the files paths.

**Comment by roblourens** [comment]
The inspector protocol adapter does actually, thanks to a PR last month.

**Comment by michelkaporin** [comment]
Addressed in #24451.
