### ISSUE TITLE
GitHub Authentication Not Working

### ISSUE THREAD

**Issue by KinanGH98** [microsoft/vscode#213402]
Type: <b>Bug</b>

1. Launch VSCode.
2. Press account icon on the left side bar.
3. Click 'Sign in to Sync Settings'.
4. Here your browser opens the GitHub page, GitHib asks for your permission.
5. You comfirm.
6. And then VSCode notification is stuck saying 'Signing into GitHub'.
7. You keep waiting until the operation fails.
* This error also happenes when trying any of git command.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.64GB free)|
|Process Argv|--crash-reporter-id a8788a1d-c17e-4037-a972-a5c9d758c286|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|2.0.9
unity-code-snippets|kle|2.2.5
expand-region|let|0.1.4
perforce|mjc|4.15.5
csdevkit|ms-|1.0.14
csharp|ms-|2.9.20
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26
LiveServer|rit|5.7.9
smartsemicolon|seu|1.0.3
code-spell-checker|str|3.0.1
vstuc|vis|0.9.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
showvideot:31016892
chatpanelc:31048052
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31049070
a69g1124:31058053
dvdeprecationcf:31052040
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by TylerLeonhardt** [comment]
What happens when you hit "Cancel" and then "Yes" to the question "would you like to sign in a different way"?

**Comment by KinanGH98** [comment]
> What happens when you hit "Cancel" and then "Yes" to the question "would you like to sign in a different way"?

When pressing Cancel you'll get asked if you want to try again locally, I tried it, and it worked. While having no idea what vscode did. It seems vscode hosts my authentication info on a local server on my machine or something. 
I've logged in successfully using this method, however the GitHubAuthentication extension couldn't sign in.
I've tried reverting to an older version of vscode btw, couldn't sign in the normal way either.

**Comment by TylerLeonhardt** [comment]
So this other flow is a feature of the GitHub Authentication extension where instead of having the browser redirect to `vscode://vscode.github-authentication/...` the extension spins up a localhost server that your browser redirect to instead.

You say "I've logged in successfully using this method, however the GitHubAuthentication extension couldn't sign in"

Can you elaborate on this more? I'm guessing maybe the browser says "it works" but the editor does not? What does it say?

**Comment by TylerLeonhardt** [comment]
@KinanGH98 there is actually one more flow after the localhost one... can you please give that one a try and let me know how it goes? Same steps:
* cancel the "signing in..."
* "Yes" at try a different way

**Comment by KinanGH98** [comment]
> there is actually one more flow after the localhost one

Actually no, there isn't. I've signed out then signed in again and guess what? the normal way of signing in worked just fine, maybe because my authentication info has been cached or something.

I'll retell the steps of what I've done:
(I'm currently signed into vscode btw).

Flow 1 Steps:
1. Clicked the accounts icon on the left bar of vscode.
2. Clicked "account name (GitHub)" option.
3. Clicked "Sign Out" and then confirmed signing out.
4. Clicked the accounts icon on the left bar of vscode.
5. Clicked "Sing in to sync settings".
6. A popup appeared saying "Signing in to GitHub".
7. A browser page of GitHub authentication is opened and then closed immediately, (normally GitHub will ask me if you want to let vscode access your account info or something).
8. Now im signed in correctly in vscode (here is where the original problem was happening).

Now Flow 2 Steps:
Redo the steps above from step 1 until 6.
7. Clicked the "Cancel" button.
8. A popup appeared saying "You have not yet finished... Would you like to try a different way? (local server)".
9. Clicked "Yes".
10. A popup appeared saying "Signing in to github.com".
11. A local browser page of Visual Studio Code is opened telling me "You are signed in now and can close this page." (this happens really fast btw, I think its also due to caching).
12. Now im signed in correctly in vscode.

**Comment by TylerLeonhardt** [comment]
Yes if your browser is already signed in to an account, and you've granted vscode access in the past, it will just speed through the sign in flow (GitHub's behavior). That's the "opened and then closed immediately".

So, at this point, you can't repro the original issue, is that right?
