### ISSUE TITLE
Copy link from editor in a similar behaviour as `editor.action.openlink`, create new command → `editor.action.copylink`

### ISSUE THREAD

**Issue by eevmanu** [microsoft/vscode#213477]
Basically, let's assume you want to copy **only** the link in the next markdowm snippet as example (could be markdown or could be any other file type)

```md
  - [amazon](https://www.amazon.com/dp/XYZXYZXYZ)
```

Locate the cursor between `.com` and `/dp`, with one keyboard shortcut automatically copy the entire url to the clipboard, but only the url, nothing more, nothing less

If I do the standard <kbd>ctrl</kbd> + <kbd>c</kbd>, it will copy the whole line to the clipboard and that's not the behaviour i'd expect

I think the expectation is really similar to what `"command": "editor.action.openLink"` does when used in a `keybindings.json` (probably removing some steps, like without calling the action to open the default browser with the detected url)

I tried to search if there is any similar issue to this but couldn't find anyone 😞.

If there is something similar which could replicate that behaviour natively to vscode and i didn't find it, I'm sorry i tried to search on different places over the documentation but maybe I omit it by mistake

Thanks for pointing any help, I appreciate it a lot and thanks for the amazing work you are doing with **vscode** 🎉👏🏼🎉👏🏼🎉👏🏼

ps: btw, this is not high priority and consider just as a wishlist 😊

**Comment by JoDasix** [comment]
[]()[]()[]()
