### ISSUE TITLE
Improve the formatting of editor.wordWrap description

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#21341]
![image](https://cloud.githubusercontent.com/assets/6461412/23299259/301f6c80-fa81-11e6-8f7a-200915bd03ad.png)

- use new lines to get paragraphs
- use the 'enumDescriptions' property to add documentation for the values
 
e.g. see https://github.com/Microsoft/vscode/blob/0a246ab31cacf5a2c997fcb4e8243c381a52bae9/src/vs/workbench/parts/files/browser/files.contribution.ts#L238

**Comment by alexandrudima** [comment]
@aeschli Using newlines (`\n`) looks ok in the comments, but looks bad in the hover. Any suggestions?

![image](https://cloud.githubusercontent.com/assets/5047891/23307836/477812e2-faa9-11e6-8f74-b1179d0fbd3f.png)

![image](https://cloud.githubusercontent.com/assets/5047891/23307826/3e3a50be-faa9-11e6-839d-f70df50aa0c1.png)
