### ISSUE TITLE
Same length of `Remote Host` and `Activity bar`

### ISSUE THREAD

**Issue by mdragoss** [microsoft/vscode#213479]
To be possible to make the same length `Remote Host` as it is `Activity bar`

<img width="61" alt="Screenshot 2024-05-25 at 21 12 56" src="https://github.com/microsoft/vscode/assets/46487312/c84bef1a-934d-4cb6-b3e1-999a2ec570d9">

---

<img width="72" alt="Screenshot 2024-05-25 at 21 14 34" src="https://github.com/microsoft/vscode/assets/46487312/3951376c-ea4e-4c2c-a50f-56d747508c91">

**Comment by daviddossett** [comment]
On a visual level I agree with this. However, we also know that status bar real estate is often super limited, so I'm not sure it's worth the trade off.

**Comment by mdragoss** [comment]
Indeed, at least yes, remove that color since the action is not primary.

**Comment by kaigian** [comment]
why not reduce the width of the activity bar?
