### ISSUE TITLE
Minimap: scroll shadow missing

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21348]
Small nit but the editor shadow we draw when scrolling down should  also show over the minimap:

![image](https://cloud.githubusercontent.com/assets/900690/23301899/84ecbfbe-fa8c-11e6-9d0a-a30188a91691.png)

**Comment by alexandrudima** [comment]
@bpasero That is somewhat expected.

The minimap now also drops a shadow when scrollLeft is not maximum:

I would find it weird if the top shadow would drop on the minimap as well:

![image](https://cloud.githubusercontent.com/assets/5047891/23302782/91847286-fa90-11e6-9cb0-4d5947d81dcf.png)

![image](https://cloud.githubusercontent.com/assets/5047891/23302804/b566f50c-fa90-11e6-9dfa-1bea01a42f0d.png)

@bpasero Please let me know if you have a better idea of how to do this...

**Comment by bpasero** [comment]
@alexandrudima oh I was not aware of that, I see the issue. If there was shadow on top of the minimap we had lots of shadows around the minimap...

**Comment by alexandrudima** [comment]
Ok, the overall thing will be the same. One action though: the top scroll shadow still appears to drop over the scrollbar. It should stop at the minimap

**Comment by alexandrudima** [comment]
![image](https://cloud.githubusercontent.com/assets/5047891/23303225/2c4d1366-fa93-11e6-929b-8967e495ad70.png)
