### ISSUE TITLE
Feature Request: Autosave on build

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode#21342]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|language-x86-64-assembly|13xforever|2.2.9|
|read-only-indicator|alefragnani|0.6.0|
|alignment|annsk|0.3.0|
|Doxygen|bbenoist|1.0.0|
|vscode-astyle|chiehyu|0.6.2|
|python|donjayamanne|0.5.8|
|EditorConfig|EditorConfig|0.3.4|
|matlab|Gimly81|0.4.0|
|status-bar-tasks|GuardRex|0.2.0|
|vscode-dimmer|hoovercj|2.1.0|
|docthis|joelday|0.4.0|
|cpptools|ms-vscode|0.10.1|
|vscode-clearcase|OpenNingia|1.6.0|
|vscode-icons|robertohuertasm|7.2.0|
|theme-cyanicpastels|SamuelLampa|0.0.9|
|indenticator|SirTori|0.2.1|
|vscode-hexdump|slevesque|1.1.4|
|code-spell-checker|streetsidesoftware|0.14.8|
|comment-snippets|Tobiah|0.2.0|
|dark-plus-material|vangware|0.2.4|
|change-case|wmaurer|1.0.0|
|highlight-trailing-white-spaces|ybaumes|0.0.2|

---

Steps to Reproduce:

1. Edit a file.
2. Run a build command.
3. Expect dirty files to be auto saved before running the build command.

Don't think it should be for all tasks, but probably those marked as auto-save in the tasks.json. Would be good if it could be restricted to files with in the workspace folder. I can have outside files open, e.g. notes. Perhaps something like:
"autoSave": off (default)/all/workspace

**Comment by BillDenton** [comment]
With the extension [Trigger Task on Save](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.triggertaskonsavel) you can trigger a build on save.

**Comment by jabooth** [comment]
Slight typo in your URL there @BillDenton, fixed one:
https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.triggertaskonsave

**Comment by dbaeumer** [comment]
I test this again and files are saved before a task is run. 

Can you provide steps where this is not happening.

**Comment by BillDenton** [comment]
Just tested and I agree it does save on build. I'm not sure when this started happening or how it can be controlled, but for the default build task in 1.18.0 it works.

**Comment by dbaeumer** [comment]
It can't be controlled right now.

**Comment by alexr00** [comment]
@dbaeumer, can this be closed? Based on the discussion, save on build already happens.

**Comment by dbaeumer** [comment]
@alexr00 the reason why I kept it open is that this can't be control. Currently we save for all tasks before we run them. In a perfect world we would allow users to control this on a task to task basis.

**Comment by allefeld** [comment]
In case this becomes configurable at some point, I propose to have three options:

- save nothing
- save active editor
- save all

**Comment by DynConcepts** [comment]
Version 1.87.0 -- most definitely does NOT happen with .Net [.sln, .csproj] and Solution Explorer...
Checked settings as recommended above - do not seem any.
