### ISSUE TITLE
Merge-conflict: Code lens dont show its  todo menu's by default until a change is made

### ISSUE THREAD

**Issue by HassanMirza01** [microsoft/vscode#213492]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.89.1
- OS Version: Kubuntu 22.04.4

Steps to Reproduce:

1. get a conflict under a git project
2. open the file which has conflict and by default you dont see "Accept current change | Accept incoming change | Accept both changes | Compare changes" menu on affected code, it appear if you try to edit something in that file
3. This error started from last 3-4 versions. It was all good before 2024 i remember

**Comment by hediet** [comment]
Can you share a screenshot? Thanks!

**Comment by hediet** [comment]
Can you copy the source code of your screenshot? Thanks!

**Comment by hediet** [comment]
I'd like to reproduce the situtation shown on your screenshots. However, I don't have the time to type the text from your screenshot.

**Comment by hediet** [comment]
Cannot reproduce:

![Image](https://github.com/user-attachments/assets/d1b3fe09-ab8e-4e71-a86d-a30e09380451)
