### ISSUE TITLE
Window Flashes White when restoring

### ISSUE THREAD

**Issue by Michael13435** [microsoft/vscode#213466]
Type: <b>Bug</b>

1. Open Visual Studio Code
2. Minimize VSCode
3. Restore VSCode

This will result in the loading window briefly flashing white. This happens on a lot of apps so it may be a windows problem

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (7.76GB free)|
|Process Argv|--crash-reporter-id 158a4efb-0873-4103-8de8-d29eb4dc1d84|
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

**Comment by Michael13435** [comment]
Here is a video of the bug (Flash Warning)
https://github.com/microsoft/vscode/assets/103131515/6c46b27f-8768-4b71-aeb4-7a331eb4a728

Had to take it on my phone, doesn't seem to happen when obs is recording

**Comment by bpasero** [comment]
I am not aware of a change VS Code can do to have an impact on this OS behaviour, but I am happy to accept a change via contribution if someone knows.
