### ISSUE TITLE
Remote development: Zombie file watcher processes not cleaned up on remote host — regression?

### ISSUE THREAD

**Issue by danilcha** [microsoft/vscode#213485]
Issue #156690 has been fixed in 2022. However, in 2024 I have exactly the same problem with the latest VSCode (Version: 1.89.1).

I'm using the SSH Remote functionality. 

Currently, I have 10 fileWatcher processes running on my Raspberry Pi:

```
ps aux | grep vscode-server | grep fileWatcher | wc
     10     130    2920
```

If I close and reopen the workspace (I don't even need to restart VSCode itself), I get 11 such processes:

```
ps aux | grep vscode-server | grep fileWatcher | wc
     11     143    3212
```

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/211462
