### ISSUE TITLE
Align rendering of links

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21347]
re #21021

See attached screen shot. Initially I thought links don't work because they get the underline only on hover while the editor is more eager to render links. We should align them, obviously I am used the editor style but open for anything...

![screen shot 2017-02-24 at 12 25 14](https://cloud.githubusercontent.com/assets/1794099/23301893/7d68794a-fa8c-11e6-8827-ff624f420c2b.png)

**Comment by Tyriar** [comment]
I'm not so sure aligning is the best thing here. This is why I didn't make terminal links always on:

- gnome-terminal shows the under line on hover
- There is not as much line-height to play with in the terminal, unlike the editor the terminal uses native web selection which you cannot change the height of outside of changing the font-size
- Terminal links are rendered 200ms later to reduce adding a bunch of DOM manipulations which would really slow things

**Comment by alexandrudima** [comment]
I am ok with having them rendered differently.

It is also my understanding that the terminal is much more permissive with links (i.e. for file paths) and that would result in a lot of underlines in potentially unwanted places.

**Comment by Tyriar** [comment]
RE permissive links: This is a temporary situation which will be improved in https://github.com/Microsoft/vscode/issues/21226

**Comment by Tyriar** [comment]
They're now rendered the same as symbols in the editor.
