### ISSUE TITLE
se "rompe" visualmente vsc

### ISSUE THREAD

**Issue by NachoAguilera114** [microsoft/vscode#213596]
Type: <b>Bug</b>

abro vsc y de la nada se empieza a como ver "ruido en todo el programa"

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.11GB free)|
|Process Argv|--crash-reporter-id c818950e-197a-4e6e-b539-1463cae0a62b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
composer-php-vscode|DEV|1.46.15409
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.46.15409
profiler-php-vscode|DEV|1.46.15409
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
prettier-vscode|esb|10.4.0
live-sass|gle|6.1.2
vsc-python-indent|Kev|1.18.0
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
autodocstring|njp|0.6.1
LiveServer|rit|5.7.9
vscode-icons|vsc|12.7.0
image-viewer|vsc|1.6.5
jinja|who|0.0.8
php-debug|xde|1.34.0
php-pack|xde|1.0.3
php-intellisense|zob|1.3.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31049070
a69g1124:31058053
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by eleanorjboyd** [comment]
closing as stale- please comment with the response to the above question if you are still seeing this and I can reopen. Thanks!
