### ISSUE TITLE
Performance report

### ISSUE THREAD

**Issue by luoshasha** [Microsoft/vscode#21353]
- VSCode Version: <code>Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2395)</code>
- Memory (System): <code>3.10GB (1.16GB free)</code>
- Memory (Process): <code>99.68MB working set (141.51MB peak, 76.62MB private, 29.69MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|44|
|main|app.isReady => window.loadUrl()|491|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|553|
|renderer|require(workbench.main.js)|2381|
|renderer|create extension host => extensions onReady()|2562|
|renderer|restore viewlet|0|
|renderer|restore editor view state|1|
|renderer|overall workbench load|3746|
|main + renderer|start => extensions ready|8967|
|main + renderer|start => workbench ready|7244|

---

Additional Steps to Reproduce (if any):

1.
2.

**Comment by bpasero** [comment]
@luoshasha that is quite slow, thanks for the report. First thing to try is to see if it reproduces with extensions disabled (`code --disable-extensions` from the command line) and if it reproduces in with our nightly insiders build (http://code.visualstudio.com/Download#insiders).

**Comment by bpasero** [comment]
I am closing this and ask people that hit slow performance to run `code-insiders --prof-startup` (from our insiders build: http://code.visualstudio.com/Download#insiders) which now supports to run CPU profiles so that we can have a closer look. Running with this argument will guide you through the process of creating a performance report here.
