### ISSUE TITLE
Test: esbuild in the `yo code` samples

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#213572]
Refs: https://github.com/microsoft/vscode-generator-code/pull/461

- [x] anyOS @paulacamargo25
- [x] anyOS @alexr00

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23213572%0A%0A&assignees=aeschli)

---

the `yo code` generators for the TypeScript and the Web extension samples now have a options to select to bundle the extension with `esbuild`

- update to the latest generators with `npm i -g yo generator-code`
- `cd` to a folder where you want to create a new project and start the generator with `yo code`
- pick `New Extension (TypeScript)`, pick a name and when asked what bundler to use, choose `esbuild`
- when completed, open have vscode opened on the generated folder
- verify that there's a esbuild.js file created.
- press F5 to build and launch the extension. To verify the extension works, run the `Hello World` command
- verify that you can debug (set a breakpoint in `extension.ts`) and that source mapping works
- in the dev window, look at the terminals view. It should show 2 build watch tasks. One for esbuild and one for tsc (esbuild only reports syntax errors, so `tsc` is started in `--noemit` mode, just to report type errors
- add and remove a compile error in the extension code (`extension.ts`) and verify that errors are shown in the editor and the problems view. Check that the errors go away when fixed. Test syntax and semantic errors.
- run tests with `npm run test`. Also add more tests and more test files
- test `npm run package`. The `dist/extensions.js` file should be minified and without source maps.
-  test the `npm` scripts `npm run` `compile`, `watch`, `package`

Do the same for `New Extension (TypeScript)`, 
What's special
- additionally to `F5` which runs the web extension in VS Code Desktop, you can also run it in a browser with `npm run run-in-browser`

**Comment by alexr00** [comment]
> Do the same for `New Extension (TypeScript)`,

I think that's the same as in step 3. I'm guessing this should be `New Extension (JavaScript)`.

**Comment by alexr00** [comment]
> I think that's the same as in step 3. I'm guessing this should be New Extension (JavaScript).

I don't see a step in the yo generator to choose a bundler.

**Comment by aeschli** [comment]
Sorry, should have said: Do the same for 'New **Web** Extension (TypeScript)'
