### ISSUE TITLE
Test: Allow for Editor Action icons to be shown on inactive Editor Groups

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#213545]
Refs: [#209962](https://github.com/microsoft/vscode/issues/209962)

- [x] anyOS @DonJayamanne
- [x] anyOS @ntrogh

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23213545%0A%0A&assignees=benibenj)

---

We added a setting `workbench.editor.alwaysShowEditorActions` which when enabled shows the editor action also for inactive editor groups.

These are editor actions:
![Image](https://github.com/microsoft/vscode/assets/44439583/57156f7e-e5ba-4481-9674-fdd94b90fcdd)

1. Enable `workbench.editor.alwaysShowEditorActions`
2. Open at least 2 editor groups
3. Open different types of editors in both editor groups (different language files, multi/diff editor, ...)
4. Makes sure the correct editor actions are shown for each group. Place your cursor in one editor and then place it in the other. The editor actions should not changed when moving focus between editor groups.

Known bugs:
- `Open Settings (JSON)` action does not work when in inactive editor group: [#213548](https://github.com/microsoft/vscode/issues/213548)

**Comment by ntrogh** [comment]
Tested ok on Windows.

**Comment by DonJayamanne** [comment]
Something I've wanted with Jupyter notebooks. Great feature, thanks
