### ISSUE TITLE
Folder operation

### ISSUE THREAD

**Issue by hanson-wen** [microsoft/vscode#213507]
Folder operation:
When you click the folder for the first time with the mouse, the folder will expand or close. In fact, you just want to keep the folder selected, and then right-click to operate some other things.
It changes a little, and I ’m not used to it. I hope you can add an alternative operation method, such as double-clicking a folder, or a better implementation. Thank you.

**Comment by lramos15** [comment]
You could right click on the folder without clicking on it first. I don't think we will change the behavior of this because it will break a lot of muscle memory
