### ISSUE TITLE
Allow creation of custom Profile Templates and base always on profile

### ISSUE THREAD

**Issue by josersleal** [microsoft/vscode#213559]
One can create a profile based on a very basic set of settings and extensions. That means at a minimum taking manual note of other important extension for example that are used no matter what type of project is used and then spending hours re-installing those.
Ideally one should be able to enhance existing Profile Templates or create own Profile Templates.

A "always on" customisable set of extensions would also be usefull in order to have a base set of extensions and settings from scratch.

**Comment by sandy081** [comment]
You can always have a profile that has base set of extensions and you can create a profile from that or create a template from that. Or Am I missing something from what you are asking?

**Comment by josersleal** [comment]
yes you are... I also can install and uninstall at leisure. Or grab the source code and add features myself. But that is not the point of creating an IDE and offer it to the world with the message that it makes life easier or whatever it is. 
PSD: why are developers so lazy?
You already have the copy from profile. The load profile. just add a check if there is a default base profile and load that plus the wanted profile. Or simply when creating a new profile add a check for a default base profile. Donty be lazy!
