### ISSUE TITLE
Vs code takes a few seconds to shut down

### ISSUE THREAD

**Issue by vusal5555** [microsoft/vscode#213592]
Type: <b>Question</b>

After finishing coding in my Nodejs/express and PHP/Laravel code, closing VS Code sometimes takes a few secods, is it normal behavior? Like does it need some time to save all files?

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.75GB free)|
|Process Argv|--crash-reporter-id 794ebb75-3150-45d2-ba79-244d0342617a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
laravel-extra-intellisense|ami|0.6.6
vscode-tailwindcss|bra|0.10.5
phpserver|bra|3.0.2
laravel-goto-view|cod|1.3.11
composer-php-vscode|DEV|1.46.15409
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.46.15409
profiler-php-vscode|DEV|1.46.15409
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
vscode-phpfmt|kok|1.2.12
rainbow-csv|mec|3.12.0
dotenv|mik|1.0.1
inline-fold|moa|0.2.6
laravel-goto-components|nao|1.2.0
color-highlight|nau|2.8.0
laravel-blade|one|1.36.1
material-icon-theme|PKi|5.3.0
vscode-blade-formatter|shu|0.24.2
svg-preview|Sim|2.8.3
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvptcf:31049071
a69g1124:31058053
dvdeprecation:31052039
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the issue is being caused by one of your extensions.

**Comment by vusal5555** [comment]
i ran the test. I have some extensions for PHP like PHP profiler, IntelliPHP and thought they were causing the issue but none of them seems to be the problem.
