### ISSUE TITLE
VSCode stutering

### ISSUE THREAD

**Issue by BarrosRuao** [microsoft/vscode#213591]
Type: <b>Performance Issue</b>

The user interface of VSCode is quite slow. When selecting code, there seems to be a lag. I notice the same when increasing the size of the terminal or expanding the content of a folder, for example. I've already uninstalled and reinstalled, I don't have any extensions installed, and I've reset all settings to factory defaults

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7800X3D 8-Core Processor            (16 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.15GB (23.53GB free)|
|Process Argv|--crash-reporter-id 0715341e-c76e-472c-b719-9392d5e9f572|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   105	  1624	code main
    0	    96	  3772	window [2] (Issue Reporter)
    0	    96	 12604	   gpu-process
    0	   155	 15340	window [1] (Visual Studio Code)
    0	    29	 16320	   crashpad-handler
    0	    75	 18224	fileWatcher [1]
    0	   104	 18668	extensionHost [1]
    0	    94	 18700	shared-process
    0	    41	 19336	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
f3je6385:31013174
pythoncenvptcf:31049071
a69g1124:31058053
dvdeprecationcf:31052040
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by alexmngn** [comment]
I'm facing similar issues where VSCode can take many seconds to update the syntax highlighting, suggest imports or even format the code. 

<img width="722" alt="Screenshot 2024-05-20 at 10 25 59" src="https://github.com/microsoft/vscode/assets/4203845/eafe3899-75b6-4472-90ed-0b473867c40c">

**Comment by deepak1556** [comment]
If you are facing the issue with latest stable, please share the perf profile using the steps from https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process
