### ISSUE TITLE
FTP links are highlighted wrongly and not openable

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#21350]
Ref: #21021

- VSCode Version: 10.0.1-insiders
- OS Version: Windows 10 / Ubuntu

Steps to Reproduce:

1. Go to terminal, type `echo 'ftp://ftp_username@example.com/folder/filename.gif'` and enter it.
2. Hover over it.

Only part starting from `//` is highlighted, and when clicked it does not open a link.

Not sure if we go for all protocol links support (would be good though), however it definitely should not mislead the user by highlighting the link.

**Comment by Tyriar** [comment]
What do you expect to happen when the link is clicked?

Link validation is captured in https://github.com/Microsoft/vscode/issues/21226

**Comment by michelkaporin** [comment]
@Tyriar I would expect it to be navigable, so that the local agent that's configured for opening such links would be used to open it.

**Comment by Tyriar** [comment]
@michelkaporin I'm not sure if we handle opening ftp links anywhere yet though?

**Comment by michelkaporin** [comment]
@Tyriar I am not aware of that. More important would be not to highlight something that we do not handle for open (e.g. FTP links).

**Comment by Tyriar** [comment]
Might close this off in favor of #21226 then as handling FTP links would probably be tricky cross platform.
