### ISSUE TITLE
Intellisense not working for node js after some time

### ISSUE THREAD

**Issue by cmrigney** [Microsoft/vscode#21355]
- VSCode Version: 1.9.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. We have a large project, and after editing in it for a little while all javascript intellisense stops working, including for node modules, and local file functions, etc.

The workaround is to set `typescript.tsdk` in settings to my old install of typescript, which is version 2.0.3.

**Comment by mjbvz** [comment]
@cmrigney Please provide the following additional information to help us investigate:

* Disable all extensions by running code with `--disable-extensions` to rule out an external cause.
* Try out VSCode 1.10 ([VSCode insiders](https://code.visualstudio.com/insiders)). This includes a new version of TypeScript with a number of important fixes and improvements
* If possible, share a minimal repo project.
* Enable `"typescript.tsserver.trace": "verbose"` in your settings. Then restart vs code and repo the issue. Go to the output window and share the output from `TypeScript`

Thanks

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this. @cmrigney Please provide the requested information and we can take a look

**Comment by cmrigney** [comment]
@mjbvz Sorry I haven't had the time recently.  I've been using the workaround.  Thanks for your time and I'll post details when I get the chance.
