### ISSUE TITLE
Incorrect Compatibililty Message in VSCode re CSS Grid Subgrid

### ISSUE THREAD

**Issue by ADun3306x** [microsoft/vscode#213599]
Type: <b>Bug</b>

grid-template-columns: subgrid;

Subgrid is incorrectly being reported in VSCode CSS as not compatible with Chrome Browser including the latest version, however "Can I Use" and Chrome Dev channels confirm that does work. 

I have also tested this and it functions correctly. 

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13980HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (11.89GB free)|
|Process Argv|--crash-reporter-id f1c7f196-25df-484b-95da-108f2618fe68|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
chrome-extension-developer-tools|aar|2.0.4
vscode-django|bat|1.15.0
npm-intellisense|chr|1.4.5
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|2.4.4
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.0.4
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.6.0
prettier-vscode|esb|10.4.0
vscode-firefox-debug|fir|2.9.10
code-runner|for|0.12.2
copilot|Git|1.195.0
copilot-chat|Git|0.15.2
vscode-pull-request-github|Git|0.88.1
live-sass|gle|6.1.2
vsc-python-indent|Kev|1.18.0
vscode-language-babel|mgm|0.0.40
vscode-autoprefixer|mrm|3.0.1
vscode-docker|ms-|1.29.1
vscode-edge-devtools|ms-|2.1.5
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.17.17
js-debug-nightly|ms-|2024.5.217
live-server|ms-|0.4.13
vscode-typescript-next|ms-|5.5.20240505
vscode-react-native|msj|1.13.0
color-highlight|nau|2.8.0
gulptasks|nic|1.3.1
autodocstring|njp|0.6.1
material-icon-theme|PKi|5.3.0
vscode-css-peek|pra|4.4.1
extended-html5-boilerplate|raj|0.0.1
LiveServer|rit|5.7.9
html5-boilerplate|sid|1.1.1
vscode-standard|sta|2.1.3
code-spell-checker|str|3.0.1
sass-indented|syl|1.8.29
open-in-browser|tec|2.0.0
pdf|tom|1.2.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-maven|vsc|0.44.0
vscode-icons|vsc|12.7.0
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31049070
a69g1124:31058053
pythonprt:31056678
dwnewjupyter:31046869
fa862199:31048878

```

</details>

**Comment by ADun3306x** [comment]
![CSS Subgrid Compatibility](https://github.com/microsoft/vscode/assets/39196829/29b6f75b-0632-45fd-a4aa-bf9a67e1a843)

Evidence of Can I Use Compatibility attached  - VSCode is reporting this wrong

**Comment by aeschli** [comment]
Can you make a screenshot of the warning?
The built-in CSS support has very few lint rules. None for `subgrid`.
All it has is the hove which shows the version of each browser from when the feature is supported
![image](https://github.com/microsoft/vscode/assets/6461412/fce2013e-d9c3-47d0-aee7-93f5a7d88889)

I assume the warning message comes from an extension that you have installed.
