### ISSUE TITLE
breakpoints don't work on symlinked files on windows

### ISSUE THREAD

**Issue by mike-kaufman** [Microsoft/vscode#2135]
Using "npm link" to create a symlink from one node project's node_modules to another a project on windows server 2012 R2.  This sets up a directory in node_modules that is a symlink to the "required" project.  VS Code breakpoints in the linked projects' files don't work. I can step into/step through these files - that all seems to work fine, but breakpoints are ignored.  Breakpoints do work in the referencing project. 

Here's repro steps:
1.  Unpack this zip file:
   [symlinkBreakpoint.zip](https://github.com/Microsoft/vscode/files/98401/symlinkBreakpoint.zip)
2.  cd B 
3.  run "npm link" command
4.  cd A
5.  run "npm link B" command
6.  open VS code in A directory. 
7.  Set a breakpoint on line 1 of a.js
8.  launch VS Code debugger.  Initial breakpoint will get hit. 
9.  on line 2 of a.js, step into b.foo() call.   (step into works)
10.   set a breakpoint on line 5 of  b.js
11.  hit f5 (continue).

Expected:  breakpoint on line 5 of b.js will be hit. 

Actual:  breakpoint is skipped & program exits.

**Comment by mihaidma** [comment]
I have the same issue on Ubuntu 14.04

**Comment by weinand** [comment]
@mihaidma symlinked source is not yet supported

**Comment by okev** [comment]
+1 very important for large projects

**Comment by pluswave** [comment]
+1 for OSX

**Comment by GeneralMatok** [comment]
+1 very important for our projects as we plan to have several repos on the local machine. I tested it with regular "folder" it works. Is there something planned to be made available soon?

**Comment by felix-last** [comment]
+1 Our application consists of multiple node apps, would be great to see support for symlinks to be able to debug them properly.

**Comment by lingwooc** [comment]
There is a work around. Open the _original_ location of the file you want to debug and put the breakpoint there. You only can't add breakpoints into the _symlinked_ folder. It does mean "breaking out" of the current project but then again it's all symlinked anyway.

+1 for fixing it properly though. Since it mostly works the problem is just the declared path of the breakpoint.

**Comment by weinand** [comment]
Starting with node.js 6.3 it is possible to pass a `"--preserve-symlinks"` as a runtime argument to node.js. This fixes the issue.
See #23753.
