### ISSUE TITLE
Unable to open `settings.json` file when editor group is inactive

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#213548]
We added a setting `Always Show Editor Actions` (https://github.com/microsoft/vscode/issues/209962) which allows showing editor actions of inactive groups. When the settings editor is in an inactive editor group and a user presses the `Open Settings (JSON)` button, nothing happens. The command probably just checks if the active editor is a Settings Editor and does not use the commands arguments to find the proper editor.

![Image](https://github.com/microsoft/vscode/assets/44439583/badf15db-dee1-41c1-9dfe-f767591fb354)

**Comment by rzhao271** [comment]
@benibenj what are some steps to verify this issue?
I don't see the Open Settings button now when the Settings editor is in an inactive editor group.

![No Open Settings button while Settings editor in inactive editor group](https://github.com/user-attachments/assets/a1da3db1-179c-4fe0-8058-d5070837092c)

**Comment by benibenj** [comment]
When you enable the `workbench.editor.alwaysShowEditorActions` setting you should be able to see the `Open Settings (JSON)` action when the settings UI is in an inactive editor group. Clicking it should open the json file in the editor which the settings UI was in
