### ISSUE TITLE
Able to jump the error in terminal with keyboard

### ISSUE THREAD

**Issue by AurevoirXavier** [microsoft/vscode#213587]
I found a post here: https://superuser.com/questions/1738781/visual-studio-code-use-keyboard-to-jump-to-first-error-from-terminal-output.

This is exactly what I need. As a programmer, frequently moving your hand from the keyboard to the mouse can strain your wrist.

**Comment by Tyriar** [comment]
See https://code.visualstudio.com/docs/terminal/basics#_links for accessing links with the keyboard (ctrl/cmd+shift+o)
