### ISSUE TITLE
Color encoding of find results is a bit weird

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21358]
![untitled](https://cloud.githubusercontent.com/assets/900690/23305959/71ad843c-faa1-11e6-81a4-0a4fbd7c283c.gif)

As you can see in this example while I type the search results either show up in grey or in orange, but what is the rule here?

**Comment by alexandrudima** [comment]
@bpasero I think grey is where the cursor selection sitting on top of a find result, while the rest are find results.

What theme are you using?

**Comment by bpasero** [comment]
@alexandrudima very likely my standard VS dark+ theme that we ship.

**Comment by alexandrudima** [comment]
The two colors can be customized if needed
```
  "editor.findMatchBackground": "#ff0000",
  "editor.findMatchHighlightBackground": "#ff0000"
```
