### ISSUE TITLE
Using git in terminal: %HOMEDRIVE% and %HOMEPATH% are not expanded

### ISSUE THREAD

**Issue by TimYorke** [Microsoft/vscode#21352]
- VSCode Version: 1.9.1
- OS Version: Windows 10
- git version: 2.11.1.windows.1

Steps to Reproduce:

1. Open terminal (either cmd or powershell)
2. Enter `git config --global -l`

The result of the command is:
"fatal: unable to read config file '%HOMEDRIVE%%HOMEPATH%/.gitconfig': No such file or directory"

![image](https://cloud.githubusercontent.com/assets/9195622/23303645/31878e34-fa8d-11e6-8be2-239de9bf4ce8.png)

**Comment by TimYorke** [comment]
The command works fine if run directly in a cmd or powershell window. 

![image](https://cloud.githubusercontent.com/assets/9195622/23303799/10657922-fa8e-11e6-9d5c-f35712edf871.png)

**Comment by Tyriar** [comment]
What is the output of this in the integrated terminal?

```
echo "%HOMEDRIVE%"
echo "%HOMEPATH%"
```

**Comment by TimYorke** [comment]
Unfortunately after logging out and back in, I can no longer recreate this.

**Comment by Tyriar** [comment]
I'll close this off then as I also can't repro, please ping if you get more reliable repro steps. Thanks :smiley:

**Comment by TimYorke** [comment]
@Tyriar I've experienced this again today. I don't know what I did to cause it but was able to get the output of the commands you asked for:

![image](https://cloud.githubusercontent.com/assets/9195622/23667065/a324936e-0354-11e7-8d66-980febd6ae91.png)

**Comment by Tyriar** [comment]
@TimYorke how do you create the terminal and what settings do you have?

**Comment by TimYorke** [comment]
> @TimYorke how do you create the terminal and what settings do you have?

I create the terminal using ```ctrl```-```'```. Here are my settings:
```json
// Place your settings in this file to overwrite the default settings
{
   "editor.tabSize": 3,
   "editor.mouseWheelZoom": true,
   "window.zoomLevel": 0,

   "search.exclude": {
      "**/*.tlog": true
   },
   "terminal.integrated.scrollback": 5000,
   "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
   "workbench.colorTheme": "Visual Studio Light",
   "workbench.iconTheme": "vs-seti",
   "workbench.activityBar.visible": false,
   "python.pythonPath": "py",
   "python.linting.pylintPath": "C:/dev_common/tools/Python/Python36-32/Scripts/pylint.exe"
}
```

**Comment by Tyriar** [comment]
@daviwil know of any reasons HOMEDRIVE/HOMEPATH would go missing in PS?
