### ISSUE TITLE
Test: Multi select for editor tabs

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#213550]
Refs: [#119327](https://github.com/microsoft/vscode/issues/119327)

- [x] anyOS @lramos15
- [x] anyOS @dbaeumer

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23213550%0A%0A&assignees=benibenj)

---

This month we added support for selecting multiple editor tabs and running some action with them.

**How it works:**
- `Ctrl + Click` a tab: Opens the editor as active and the previous opened tab is selected. If it was selected, it unselects the tab if possible.
- `Ctrl + Shift` a tab: Opens the editor as active and selects all editors between the the Anchor editor and the new active tab. 
  - The Anchor editor is the last tab which a user `Ctrl + Click` to add to the current selection. If the user has only has not pressed `Ctrl+Click` during with the current selection, then the active editor is the Anchor editor

With `Ctrl + Click`:
![Image](https://github.com/microsoft/vscode/assets/44439583/0f765778-1e0c-43e4-aff4-2f8afa539059)

With `Shift + Click`:
![Image](https://github.com/microsoft/vscode/assets/44439583/1e9ff432-8b7b-42d8-bafe-d478ba02289f)

**Testing:**
- Select multiple tabs and move them around in the same group
- Select multiple tabs and move them out into a new group/window
- Select multiple tabs and right click on one of them. Run some of the actions available in the context menu.
- Select multiple tabs and press `Ctrl + W` which should close the selected tabs

**Comment by Thaina** [comment]
Is it possible to also indicate multi selected tab in explorer and opened, sync the selected item everywhere?

![image](https://github.com/microsoft/vscode/assets/1042507/8304b9a4-72bc-4383-93db-8230e1b508ee)

Something like this?

![image](https://github.com/microsoft/vscode/assets/1042507/25c842c8-7166-4a28-8ae9-da5e19b904b9)

**Comment by benibenj** [comment]
@Thaina Please please create a feature request for this. It is something we considered, but it's very tricky to solve when a user has multiple editor groups. Also, I'm not to sure about syncing with the explorer as it's possible to select a file which is not currently open, so that could lead to some unexpected behaviour

**Comment by Thaina** [comment]
@benibenj I would like to ask, is it possible or is it have any reason to not do this, or is it intentional to make it like this, or it actually should be and is a bug, before creating the issue for feature request

Your argument about file outside of workspace is also a great counter argument for this
