### ISSUE TITLE
Explorer does not always refresh on git branch changes

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#21351]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.4.0-63-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|swagger-viewer|Arjun|1.3.0|
|vscode-simple-icons|LaurentTreguier|0.10.1|
|vscode-todo|MattiasPernhult|0.8.0|
|material-icon-theme|PKief|1.3.4|
|vscode-docker|PeterJausovec|0.0.12|
|html-css-class-completion|Zignd|1.0.3|
|githistory|donjayamanne|0.1.5|
|phpunit|emallin|1.0.0|
|php-intellisense|felixfbecker|1.1.2|
|text-transform|florianloch|0.1.0|
|auto-close-tag|formulahendry|0.3.9|
|auto-rename-tag|formulahendry|0.0.11|
|theme-dark-starry-night|jerry|1.0.2|
|php-symbols|linyang95|2.1.0|
|Go|lukehoban|0.6.53|
|csharp|ms-vscode|1.7.0|
|better-merge|pprice|0.5.1|
|swaggitor|qnsolutions|0.1.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. working on one branch A, creating folder, commit push, whatever
2. git checkout another branch B. folder disappears (of course)
3. git checkout A again, folder exists but is not shown in explorer

That gave me some heart attacks, when I thought all the work has gone...

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by DasJott** [comment]
It doesn't seems to appear anymore. Hasn't happened since 1.10
