### ISSUE TITLE
Powershell within built-in terminal non-functional and prints ^Q

### ISSUE THREAD

**Issue by rjgscotland** [Microsoft/vscode#21354]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 3.13.0-106-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.8|
|PowerShell|ms-vscode|0.9.0|
|jinja|wholroyd|0.0.7|

---

Steps to Reproduce:

1. Open built-in terminal (I used menu, CTRL+` doesn't seem to work for me on UK keyboard)
2. At the bash prompt, type powershell
3. Try to enter anything into the terminal and get a load of ^Q printed. Example output:

```
PS /home/rob/projects/powershellbackups> d^Q^Q^Q^Q^Q^Qi^Q^Q^Q^Q^Q^Q^Qr^Q^Q
dir : The term 'dir' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ dir
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (dir:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
![vscodeterminalps](https://cloud.githubusercontent.com/assets/1683665/23305101/07e53830-fa95-11e6-9e8b-365b23a522b6.png)

Text input works fine at the bash prompt. Text input works fine in powershell in xfce4-terminal. No issues inputting text into any other elements of VS Code.

System has latest v6.0.0-alpha.16 Powershell Core.

**Comment by Tyriar** [comment]
You'll need to add this to your settings:

```
"terminal.integrated.flowControl": false
```

You can remove this setting in v1.10 as it's no longer needed.

**Comment by rjgscotland** [comment]
Thanks @Tyriar, much appreciated.
