### ISSUE TITLE
Test: Finalized Chat Participant API

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#213514]
Refs: #199908

- [x] macOS @eleanorjboyd
- [x] linux @dbaeumer
- [x] windows @Yoyokrazy

Complexity: 5
Roles: Developer, Engineering Manager

Authors: @roblourens, @jrieken, @joyceerhl 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23213514%0A%0A&assignees=roblourens,jrieken)

---

The Chat Participant API has been finalized. Please look at it to make sure that it is properly finalized and the docs in vscode.d.ts make sense. Here are some things to look at:

- You can start with the chat-sample or build your own from scratch if you want to: https://github.com/microsoft/vscode-extension-samples/tree/main/chat-sample
- You can use it without needing to set any `enabledApiProposals`
- All the new stuff in vscode.d.ts has a doc comment, and the comments are useful and make sense.
- Download this VS Code Stable build: https://builds.code.visualstudio.com/builds/stable?commit=bbb3b1c06b47b6bcaedd631eaa7a057b87e86243 and try to use your chat participant in it. You should get a warning that chat participants are not yet allowed in vscode stable. It should NOT show up in the suggest widget, and if you manually type `@name` it should not be recognized. 
  - But also, your extension should not throw any errors while registering the participant, and other parts of the extension should continue to work fine.

---

- And maybe one of you can do this verification-needed item: https://github.com/microsoft/vscode-copilot/issues/5514

**Comment by dbaeumer** [comment]
@roblourens the link  https://builds.code.visualstudio.com/builds/stable?commit=bbb3b1c06b47b6bcaedd631eaa7a057b87e86243  doesn't have any stable client bits for Linux. Any recommendation?

**Comment by roblourens** [comment]
My integration tests failed in Stable for those, I'll fix it and get a new one running

**Comment by Yoyokrazy** [comment]
> My integration tests failed in Stable for those, I'll fix it and get a new one running

Tested all steps until checking against stable 1.90. No stable client for win x64, waiting on the new build as well.

**Comment by roblourens** [comment]
New stable build in progress: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=275589&view=results

When you test in stable, install Copilot Chat pre-release as well
