### ISSUE TITLE
2018-2024 , This Bug havent resolve !!

### ISSUE THREAD

**Issue by nop4LOL** [microsoft/vscode#213551]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest
- OS Version: windows10

Steps to Reproduce:

1. see gif

![3](https://github.com/microsoft/vscode/assets/117899311/1c04e5f8-3c94-479f-82a2-62d67d1546e3)

2.In 2018, the first time I used vscode, I encountered this problem. Every time I opened the terminal, if I opened cmd, then after opening, when I typed the first character, as you can see in the video, the entire terminal screen would disappear. After I pressed enter, the following commands returned to normal. If I opened PowerShell, when I typed characters, the text background color would automatically change, which I didn't understand at all. None of these terminals were normal. Until today, in 2024, this problem still exists, and I still can't solve it. I hope you can help me. It's been six years, and I'm still stuck here. Thank you.

3.Strangely, I seem to have found a magical solution. When I pulled the terminal window up to this height, it returned to normal cmd and did not inexplicably turn blank. But this is clearly not a real solution, as I cannot make the terminal window such an exaggerated height when I am actually writing code or using the terminal.

![image](https://github.com/microsoft/vscode/assets/117899311/6ee41289-e622-44cc-a079-648165fe2a40)

4. I am always online , im waiting for you good news ,thank you again.

**Comment by meganrogge** [comment]
re powershell, what color theme are you using? 

can you provide me with your settings.json file?

No idea what is happening for you with command prompt. what version of windows are you using?

**Comment by Tyriar** [comment]
Unfortunately the only fix is to upgrade to Windows 11 to move on to the newer conpty component which is what the terminal is built on.
