### ISSUE TITLE
Minimap lacks separation from embedded editors

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#21359]
![image](https://cloud.githubusercontent.com/assets/5047891/23305955/6b8a268c-faa1-11e6-99de-bb67a1eb3d64.png)

**Comment by bpasero** [comment]
This example here makes the issue more obvious because the minimap here does not draw a shadow:

![image](https://cloud.githubusercontent.com/assets/900690/23305183/d6751668-fa9d-11e6-88b0-1be673834554.png)

**Comment by alexandrudima** [comment]
Yes, my screenshot was meant to show that even the shadows don't help entirely because they get interrupted by the widget

**Comment by bpasero** [comment]
Right. One idea was, what if we start to show a border if a view zone is actually showing in the editor.

@stevencl @chrisdias this is maybe something for a UX discussion next sprint

**Comment by alexandrudima** [comment]
:+1: I'm not a big fan of the shadow thing entirely. The line numbers don't drop shadow, while the minimap does...

**Comment by bpasero** [comment]
If it was possible to actually hide our normal scrollbar and use the minimap as scrollbar, maybe it would make sense to use the same border we have today for the scrollbar to the left of the minimap. Just throwing in some ideas...

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

> If it was possible to actually hide our normal scrollbar and use the minimap as scrollb

Use the minimap as a scrollbar, if it is optional. Once it is implemented 'independent minimap scroll on mouse wheel events' link Atom. Can someone tell me if there is a question for this?

> Just throwing in some ideas...

But maybe put the scroll bar to the left of the minimap, no? Like Atom. And decrease the width of the bar slightly.

![capturar1](https://cloud.githubusercontent.com/assets/19866231/23308861/573e9340-fa8b-11e6-8fbf-0ec26f1197a5.PNG)

**Comment by pixieaka** [comment]
I guess putting the scroll bar to the left of the minimap is the best solution 👍

**Comment by bpasero** [comment]
Yeah, I like that idea actually!
