### ISSUE TITLE
Debugger doesn't recognize ES6 'import-export' feature

### ISSUE THREAD

**Issue by Andriy-Kulak** [Microsoft/vscode#21363]
I am getting the following error when trying to debug my ES6 javascript node app. It seems it doesn't recognize the ES6 'import-export' feature, however I am able to run my app fine in dev mode. Any ideas on how to fix this?

```
/Users/andriy.kulak/Sites/DV-Shared-RatingAPI/src/app.js:1
(function (exports, require, module, __filename, __dirname) { import express from 'express';
                                                              ^^^^^^
```
- VSCode Version: 1.9.0
Steps to Reproduce:
1. Set up launch.json config
2. in src/app.js - have at least one import of module in the following style "import express from 'express';"
3. Launch debugger

Below is my launch.json file for reference. Am I missing something here?

```
"version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/src/app.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "internalConsole",
            "sourceMaps": false,
            "outDir": null
        },
```

**Comment by roblourens** [comment]
Are you using babel-node or something in dev mode?

**Comment by weinand** [comment]
@Andriy-Kulak we had a discussion here: https://github.com/Microsoft/vscode/issues/15997#issuecomment-282320824
Can I close this?

**Comment by Andriy-Kulak** [comment]
Yes. Thanks! For anyone that is wondering. The article below details the solution.
- https://medium.com/@katopz/how-to-debug-es6-nodejs-with-vscode-8d00bd6c4f94
