### ISSUE TITLE
ChatFollowup is very generic

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#213631]
Testing #213514

When reading it the first time in the example I had difficulties binding a meaning to it. The doc comment talks about question. Would it make sense to name it `ChatFollowupQuestion` of `ChatFollowupInput` ?

**Comment by roblourens** [comment]
We could add more detail to the doc comment about how it will be displayed and used, would that help? I wouldn't call it a followup question since it's not necessarily a question. Maybe a `ChatFollowupRequest`? But I'm not sure the name needs to be changed.

**Comment by jrieken** [comment]
This is how oxford defines it and I tend to agree that we name is already precise

> follow-up | ˈfɒləʊʌp |
> noun
> a continuation or repetition of something that has already been started or done: [as modifier] : a follow-up study of the > same interviewees after retirement.

**Comment by dbaeumer** [comment]
The thing I had problems with is that you usually follow up on something and it was not clear to me what the follow-up is.

**Comment by jrieken** [comment]
We kept this as-is. Closing because the API is now finalized
