### ISSUE TITLE
[BUG?]: Webview errors

### ISSUE THREAD

**Issue by yan-pi** [microsoft/vscode#213600]
Does this issue occur when all extensions are disabled?: No, sice i need to install the markdown extension to occur

- VS Code Version:  1.89.1 dc96b837cf6bb4af9cd736aa3af08cf8279f7685 x64
- OS Version: linux fedora 40 linux kernel 6.8.9-300.fc40.x86_64

Steps to Reproduce:

1. Install markdown preview or other Rxtension that uses webview
2. Run the command to show webview

![image](https://github.com/microsoft/vscode/assets/102800044/a99fbcdc-cb14-4699-975d-1fecd106c0db)

![image](https://github.com/microsoft/vscode/assets/102800044/c411f720-7730-4576-a384-d61387af61fa)

tried other extensions, none of them are running properly

**Comment by yan-pi** [comment]
I don't think so; the bug appears in every WebView app rendering in Visual Studio Code.

**Comment by DanTup** [comment]
Sorry, I linked the wrong issue - I meant https://github.com/microsoft/vscode/issues/125993

The issue seems to randomly break webviews in VS Code until you completely restart it.

**Comment by yan-pi** [comment]
Yeah,same issue!
will close this one and comment in the other to keep track
