### ISSUE TITLE
Terminal links cut off at umlaut

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21361]
while verifiying https://github.com/Microsoft/vscode/issues/21186

```
bash-3.2$ echo "https://task.krümplr.com/signup?referral=51cfe998f397460200000001"
https://task.krümplr.com/signup?referral=51cfe998f397460200000001
bash-3.2$
```

**Comment by Tyriar** [comment]
Will probably need to add the following ranges to the URL regex https://url.spec.whatwg.org/#url-code-points

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/21125
