### ISSUE TITLE
SCM: Cloning git repository into nonexisting folder

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#21366]
- VSCode Version: 1.10.0
- OS Version: Windows 10

Steps to Reproduce:

1. Try cloning repository into the new (not yet created) folder from command palette.
2. Unfriendly error is shown with no output. The gif below shows the behaviour.
![gif](https://cloud.githubusercontent.com/assets/2239563/23307926/a5e72624-faa9-11e6-9644-8866eff7d282.gif)

I expect friendly message to appear, instead of ENOENT error code.

**Comment by joaomoreno** [comment]
Actually, `ENOENT` comes from not being able to find `git.exe`. Do all the other git features work in your case?

**Comment by michelkaporin** [comment]
@joaomoreno At this point of time git features worked, but cannot reproduce this issue anymore, thus closing.
