### ISSUE TITLE
Wording makes it sound like I can press tab immediately to cycle through hover parts

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#213673]
Follow the setup in https://github.com/microsoft/vscode/issues/213638

1. `ctrl+k ctrl+i` to trigger hover
2. `ctrl+k ctrl+i` to focus into hover
3. `tab` to focus a hover part
4. `alt + F2` to trigger accessibility help
5. The wording makes it sound like I can use `tab` from within the accessible view to cycle through the hover parts, but in reality I need to be focused on the hover first.

![image](https://github.com/microsoft/vscode/assets/38270282/e78094f4-1bb4-42fb-a54e-d54b7b216545)

**Comment by aiday-mar** [comment]
Hi @alexr00 yes you are absolutely right. I will change the wording of that string.
