### ISSUE TITLE
Holding `Ctrl + I` in terminal doesn't start listening

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#213660]
Testing #213355

In the editor, the inline chat opens and starts listening. The same would make sense in the terminal.

**Comment by Tyriar** [comment]
It never seemed to work for me on macOS while testing. I know it did when it was originally implemented.

**Comment by bpasero** [comment]
I can press and hold `Cmd+I` in a terminal and it opens inline chat and records and submits when I release:

![Recording 2024-05-29 at 15 11 35](https://github.com/microsoft/vscode/assets/900690/210c5d92-04af-45d1-9796-fc12225e95ce)

**Comment by chrmarti** [comment]
I was using Windows ARM on Parallels in case this makes a difference.

**Comment by bpasero** [comment]
Works for me there as well. Can you try from a fresh profile without keybindings or settings?

**Comment by chrmarti** [comment]
Now works for me as well.

**Comment by bpasero** [comment]
Thanks!
