### ISSUE TITLE
Unclear what context items operate on multi select vs single selection

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#213699]
Testing #213550

It's unclear to me what context menu items when right clicking will operate on the multi-selected tab context and what will operate on just a single tab. I'm not sure what the best solution is for this, but just wanted to call it out as a confusing user experience. The explorer has a similar issue, but I find those actions are easier to understand if they would be one or many.

**Comment by lramos15** [comment]
Maybe it's just extension contributed ones then. Like `Copy remote file URL`

**Comment by benibenj** [comment]
Yes, exactly. We provide context keys that extensions can use
- `multipleEditorsSelectedInGroup`
- `twoEditorsSelectedInGroup`
