### ISSUE TITLE
Too slow performace - Source Control checkout and Sync

### ISSUE THREAD

**Issue by Hmitta** [microsoft/vscode#213616]
Type: <b>Performance Issue</b>

Its been sometime I'm facing an issue with regards to slowness in VS code performace. Especially the Source Control chechout and sync. Not sure the exact root cause. Need resolution ASAP to avoid impact on productivity. Thanks!

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (18.06GB free)|
|Process Argv|--crash-reporter-id d566c913-7c4b-4d23-851c-44c7ecc3cbd1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   108	 26372	code main
    0	   138	  2720	   window
    0	   104	  4580	shared-process
    0	    45	  4996	   utility-network-service
    0	   458	  7172	extensionHost [1]
    0	    69	  3928	     "C:\Program Files\Java\jdk-17\bin\java" -DwatchParentProcess=false -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=c:\Users\MK00835638\AppData\Roaming\Code\User\globalStorage\redhat.vscode-xml -Xmx64M -cp c:\Users\MK00835638\.vscode\extensions\redhat.vscode-xml-0.27.0-win32-x64\server\org.eclipse.lemminx-0.28.0-uber.jar org.eclipse.lemminx.XMLServerLauncher
    0	    14	 11352	       C:\WINDOWS\system32\conhost.exe 0x4
    0	   115	  8256	     electron-nodejs (server.js )
    0	    95	  8780	     electron-nodejs (server.js )
    0	    98	 21836	     electron-nodejs (visualforceServer.js )
    0	   120	 27196	     electron-nodejs (server.js )
    0	   592	 27556	     "C:\Program Files\Java\jdk-17\bin\java" -cp c:\Users\MK00835638\.vscode\extensions\salesforce.salesforcedx-vscode-apex-60.13.0\dist\apex-jorje-lsp.jar -Ddebug.internal.errors=true -Ddebug.semantic.errors=false -Ddebug.completion.statistics=false -Dlwc.typegeneration.disabled=true -Xmx4096M apex.jorje.lsp.ApexLanguageServerLauncher
    0	    14	 14448	       C:\WINDOWS\system32\conhost.exe 0x4
    0	   118	 27696	     electron-nodejs (server-node.js )
    0	   109	 15888	window [3] (Issue Reporter)
    0	   198	 24924	   gpu-process
    0	   102	 26136	ptyHost
    0	    10	  3612	     conpty-agent
    0	    10	 24036	     C:\Users\MK00835638\AppData\Local\Programs\Git\bin\bash.exe --init-file "c:\Program Files\Microsoft VS Code\resources\app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"
    0	    16	 13420	       "C:\Users\MK00835638\AppData\Local\Programs\Git\bin\..\usr\bin\bash.exe" --init-file "c:\Program Files\Microsoft VS Code\resources\app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"
    0	   197	 26156	window [1] (Git Graph - b2b-sfdc-prod - Visual Studio Code)
    0	    87	 26432	fileWatcher [1]
    0	    32	 26552	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Git Graph - b2b-sfdc-prod - Visual Studio Code)
|    Folder (b2b-sfdc-prod): more than 25974 files
|      File types: xml(9773) cls(4682) email(1235) ts(154) js(106) json(82)
|                  cmp(49) css(34) design(21) auradoc(20)
|      Conf files: github-actions(7) launch.json(1) settings.json(1)
|                  package.json(1)
|      Launch Configs: apex-replay;
```

</details>
<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
apex-pmd|chu|0.7.0
vscode-eslint|dba|2.4.4
prettier-vscode|esb|10.4.0
lana|Fin|1.14.1
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.88.1
git-graph|mhu|1.30.0
vscode-xml|red|0.27.0
vscode-yaml|red|1.14.0
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|60.13.0
salesforcedx-vscode-apex|sal|60.13.0
salesforcedx-vscode-apex-debugger|sal|60.13.0
salesforcedx-vscode-apex-replay-debugger|sal|60.13.0
salesforcedx-vscode-core|sal|60.13.0
salesforcedx-vscode-expanded|sal|60.13.0
salesforcedx-vscode-lightning|sal|60.13.0
salesforcedx-vscode-lwc|sal|60.13.0
salesforcedx-vscode-soql|sal|60.13.0
salesforcedx-vscode-visualforce|sal|60.13.0
sfdx-package-xml-generator|Vig|2.0.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
chatpanelt:31048053
dsvsc021:30996838
jg8ic977:31013176
pythoncenvptcf:31049071
a69g1124:31058053
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by Hmitta** [comment]
Hi @lszomoru,
Please LMK if you want to connect and check the issue live

**Comment by lszomoru** [comment]
When you run into a slow checkout or sync operation you can take a look at the [git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window) as it contains all git commands that are being executed by VS Code. Each command also logs the exact execution time so it would be interesting to see whether the time is spent in the child process that runs the git command, or in VS Code.

**Comment by Hmitta** [comment]
@lszomoru - This has happened when the VS code launch begun. I had my team uninstall and re-install the security in my system. Now, I see the VS code is working fine. But I would like to hold this ticket for sometime to do follow up on the same. If not required, please feel free to close the ticket. I'll create a new ticket and link to it. Thanks for your support!!!

**Comment by lszomoru** [comment]
@Hmitta, will close this issue for now. Please feel free to reopen it in case the issue reoccurs. Thanks!
