### ISSUE TITLE
Accessibility view not opened on Linux

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#213685]
Testing #213342

On Linux there is accessibility help, but no view. Not sure this is expected or not. 🤔

**Comment by chrmarti** [comment]
It's bound to `Shift + Alt + F2` and that works in other parts of the UI. Running the command from the command palette also doesn't show the view. Also tried with binding it to `Ctrl + Shift + A`.

**Comment by meganrogge** [comment]
can you run toggle keyboard shortcuts troubleshooting to see if it's attempting to run the command or something else?

**Comment by meganrogge** [comment]
and does the accessible view open for other features, just not for notebooks?

**Comment by chrmarti** [comment]
It opens for others. It doesn't seem to be an issue with the keybinding as the command in the command palette also doesn't work.

**Comment by meganrogge** [comment]
@amunger do you have access to Linux?

**Comment by amunger** [comment]
only through ssh, and it works for me with that.
To clarify, the accessibility view is for notebook cell output and only .ipynb (not github issues). There is no view for the cells input.
@chrmarti - are you focused on a cell output when trying to open the view?

**Comment by chrmarti** [comment]
> only through ssh, and it works for me with that. To clarify, the accessibility view is for notebook cell output and only .ipynb (not github issues). There is no view for the cells input. [@chrmarti](https://github.com/chrmarti) - are you focused on a cell output when trying to open the view?

That works with the keybinding (not the command palette). 👍
