### ISSUE TITLE
Crash with 250% or 300% scaling under Wayland

### ISSUE THREAD

**Issue by maghoff** [microsoft/vscode#213651]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1 and 1.90.0-insider
- OS Version: Ubuntu 24.04

Steps to Reproduce:

1. Start VSCode using Wayland, in a Wayland session configured with 250% or 300% scaling (I usually run `code --ozone-platform=wayland .`)
2. Move the mouse cursor onto the VSCode window. VSCode crashes abruptly.

Other scale factors will probably also cause the issue, I have only verified with 250% and 300%, but this does not happen when configuring the scaling to 200%. It even works to run VSCode on an attached monitor with 200% scaling while the laptop monitor is still configured to 250% scaling.

If I start VSCode with `--verbose` and give it time to settle before moving the mouse cursor onto its window, I get the following single log line before the process abruptly terminates:

> [355646:0528/123537.580840:ERROR:wayland_event_watcher.cc(43)] libwayland: wl_surface@32: error 2: Buffer size (64x64) must be an integer multiple of the buffer_scale (3).

This problem is a recent regression, I have been running VSCode with fractional scaling under Wayland for a long time.

**Comment by maghoff** [comment]
For all I know, it could be that the issue started when I installed Ubuntu 24.04, and wasn't present in 23.10, but I didn't see it immediately since I was using an external monitor with 200% scaling. I have not verified this, but I see from other similar issues that this buffer size mismatch seems to have been handled more leniently by mutter: https://gitlab.gnome.org/GNOME/mutter/-/issues/2428

**Comment by rzhao271** [comment]
Hi @maghoff does the issue still occur for you on VS Code 1.96 or later?
If yes, could you attach a crash report following the steps at [Creating a Crash Report](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report)?

**Comment by maghoff** [comment]
I cannot reproduce this with VSCode 1.96.1, Gnome 47 (Ubuntu 24.10) and 250% fractional scaling.

As a point of curiosity, the reproducability of this bug has been switching back and forth since I initially reported this. Will report again if it should reappear 🙂
