### ISSUE TITLE
"zenMode.restore": true is global

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21369]
* open two windows, enable zen mode in one, leave the other as it
* have this config: "zenMode.restore": true
* quit VS Code and reopen
* both windows are in zenMode which isn't what I expect from `restore` and isn't what I want. The setting acts like a global setting

**Comment by isidorn** [comment]
I though making it global is more intuitive to align with the fullscreen restore, but I agree with you that it should be per workspace. Since it is a one liner and a new feature pushing it straight to february

**Comment by isidorn** [comment]
Actually I would aslo change the full screen to be persisted per workspace, since these two should be aligned, otherwise it is not a nice experience when they get disconnected.
All in all, nothing for today but debt week -> march

**Comment by isidorn** [comment]
I changed the setting to be per workspace, however for fullscreen I left as it is [here](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/windows.ts#L843)

@bpasero is it possible to change this behavior and do you think it should be changed. Namely, vscode is in fullscreen, file > new window this one also opens in fullscreen.
Due to this some discrepancies happen when in zen mode.

**Comment by bpasero** [comment]
@isidorn the fact that a new window opens in fullscreen mode when you are in fullscreen mode I think is a OS behaviour we cannot control. E.g. I am not explicitly setting a second window to open as fullscreen in the code.

**Comment by isidorn** [comment]
@bpasero that's what I thought, thanks.

**Comment by roblourens** [comment]
I see one issue, is this the discrepancy you're referring to @isidorn?

- Put a window in zen mode
- file > new window
- New window is also in zen mode. Toggle zen mode off
- New window is still in fullscreen mode, and I also have to toggle that off.

**Comment by isidorn** [comment]
@roblourens yes, that is captured in a seperate issue - you can search for it
