### ISSUE TITLE
Accent menus shown in wrong location on macOS

### ISSUE THREAD

**Issue by peterhagelund** [Microsoft/vscode#21368]
- VSCode Version: 1.9.1 (2017-02-08T23:29:25.464Z)
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Create or open a text file
2. In the editor, press and hold a key with accents (or national characters) available (e.g. 'c'): https://support.apple.com/kb/PH25643?locale=en_US&viewlocale=en_US
3. The accent menu should show up right above the character just entered, but it shows up in the editors top, left corner.

**Comment by roblourens** [comment]
Same as #13093, I think

**Comment by peterhagelund** [comment]
@roblourens I agree - sorry for the dup.
