### ISSUE TITLE
Add File to Chat doesn't respect multi select

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#213624]
Testing #213550

- select many tabs
- run `Add File to Chat` from the context menu

Observe: only one file is added.

**Comment by dbaeumer** [comment]
Same for `Find file references`

**Comment by benibenj** [comment]
Will add support depending on what is decided in https://github.com/microsoft/vscode-copilot/issues/5861

**Comment by dbaeumer** [comment]
Should the action then not be disabled / not present on multi select. I find it wired that it takes the resource of the active tab.

**Comment by benibenj** [comment]
The action got removed from the context menu of tabs. Here is the issue where this got discussed: https://github.com/microsoft/vscode-copilot/issues/5861
