### ISSUE TITLE
alt-f1 opens new untitled editor in settings editor

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#213663]
Testing #213342

1. Open settings editor
2. Focus on a setting.
3. Use alt-f1 
4. Notice that this creates a new editor, then shows the accessibility help for a normal editor :bug:

**Comment by meganrogge** [comment]
our default accessibility help dialog is the one for the editor. when there's no open editor, we create one if a user invokes this command. 

while I can see that this might be surprising, it's still what we want to do from an accessibility standpoint.
