### ISSUE TITLE
Closing accessibility help view should always properly return focus

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#213615]
Testing #213342

Closing accessibility help view should always properly return focus. Here's an example when that is not the case:

1. Have a focus in the comments
2. Alt + F2 to move focus to accessible view
3. `esc` to close
4. focus is not returned to the comment where my focus was when I triggered the accessible view 🐛

**Comment by meganrogge** [comment]
this should work 🤔

**Comment by meganrogge** [comment]
We have made a lot of fixes, I don't believe this reproduces anymore, pls reopen if I'm wrong.
