### ISSUE TITLE
LanguageModelChatResponse incorrect documentation for streaming.

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#213634]
Testing #213514

I think the code example should be:

```ts
try {
   // consume stream
   for await (const chunk of response.text) {
    console.log(chunk);
   }
 } catch(e) {
   // stream ended with an error
   console.error(e);
 }
```

e.g. reponse.stream -> response.text

**Comment by jrieken** [comment]
@dbaeumer Unsure which `vscode.d.ts` you have been using but the one in main uses a correct sample

https://github.com/microsoft/vscode/blob/92cc429b6a5b85d5255e3a2c72e39a6935530719/src/vscode-dts/vscode.d.ts#L19011

**Comment by dbaeumer** [comment]
I used goto definition which actually brought me to a local copy of it in the samples :-). Hope that the difference was not too big.
