### ISSUE TITLE
Wrong size and no scroll bar

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#213648]
Testing #213597

* ubuntu
* chromium 125.0.6422.76 (Official Build) snap (64-bit)
* F1 > Report Issue
* :bug: the initial size is too small, there are no scrollbars
* :bug: when resizing the input field grows so that I never see a full submit button

<img width="1938" alt="Screenshot 2024-05-28 at 12 05 11" src="https://github.com/microsoft/vscode/assets/1794099/e5618bd6-4e22-4d78-a588-ac1b1efd9429">

**Comment by rzhao271** [comment]
Same issue on Edge on Windows.

**Comment by justschen** [comment]
noted! realized i added styles only for `.mac.web`
