### ISSUE TITLE
On macOS sheets appear in the wrong location

### ISSUE THREAD

**Issue by peterhagelund** [Microsoft/vscode#21367]
- VSCode Version: 1.9.1 (2017-02-08T23:29:25.464Z)
- OS Version: macOS 10.12.3

VS Code does not follow the human interface guidelines for macOS. Sheets, displayed by a window, should slide out under the window titlebar but the side out at the top in stead. I believe this change happened between VS Code 1.8.x and 1.9.x.

Steps to Reproduce:

1. View Extensions (⇧⌘X)
2. Select any installed extension
3. Click Uninstall
4. VS Code shows a Sheet asking Are you sure you want to uninstall '<extension name>'?

The top of the sheet is aligned with the top of the titlebar in stead of the top of the client view.

**Comment by bpasero** [comment]
@peterhagelund can you share a screenshot of where the sheet is and where you expect it to be?

**Comment by roblourens** [comment]
![image](https://cloud.githubusercontent.com/assets/323878/23310993/5624255a-fa69-11e6-992d-5aefa5e70d24.png)

Probably since we aren't using a native titlebar, the whole window is the "client view" and we probably can't move that dialog arbitrarily.

**Comment by peterhagelund** [comment]
@bpasero here you go:
<img width="1072" alt="screen shot 2017-02-24 at 11 32 00 am" src="https://cloud.githubusercontent.com/assets/15679466/23311697/f08d9548-fa84-11e6-9326-52b462fb8216.png">

**Comment by bpasero** [comment]
Ah yes now I get it, yeah this is due to our custom title bar. Awesome, I think I can fix this via the API for offsetting sheets: https://github.com/electron/electron/blob/master/docs/api/dialog.md#sheets

**Comment by peterhagelund** [comment]
@bpasero Awesome!
