### ISSUE TITLE
`Ctrl + I` does not work when chat input field has focus

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#213637]
Testing #213355

`Ctrl + I` works in the editor and when I hold it, I get into speech mode. But when the chat input field (panel or inline chat) already has focus, `Ctrl + I` does not work.

(Connected to Windows through Remote Desktop in case that matters.)

**Comment by bpasero** [comment]
@chrmarti now I cannot reproduce anymore, so it must be some context key issue, do you have reliable steps?

**Comment by bpasero** [comment]
Oh here you go:
* start voice chat and let it auto submit
* wait for voice reading out aloud
* stop that
* try `Cmd+I` again and it fails

**Comment by bpasero** [comment]
This could also explain what @digitarald was seeing where `Escape` was not working anymore. We fail to reset a global context key for active voice chat session.

**Comment by roblourens** [comment]
I think this still fails? I can hold cmd+I and do a voice chat, but it never works a second time when focus is in the inline chat widget. I see that it's still running `workbench.action.chat.stopListeningAndSubmit`

**Comment by bpasero** [comment]
@roblourens I cannot reproduce, are you sure you are on latest insiders with my fix included? Also, do you have more details how it happens and whether its happening in the lightweight input field:

<img width="489" alt="image" src="https://github.com/microsoft/vscode/assets/900690/3ecfad4b-9821-4ecd-aa0e-5c5c9bef195a">

Or in the full inline widget:

<img width="816" alt="image" src="https://github.com/microsoft/vscode/assets/900690/216b0408-42a5-493d-83f9-cd1cca74d463">

**Comment by chrmarti** [comment]
This now works for me. 👍

**Comment by roblourens** [comment]
Yesterday I was using the latest Insiders, which should have had your changes. It looks like you made another change and today it works exactly as I expect 👍
