### ISSUE TITLE
Keep tab selection when inactive

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#213625]
Testing #213550

- select some tabs
- run any of the split actions

Observe: the split happens correctly, but after the split the editor from which I opened the context menu is selected. I would have expected that the multi select state is preserved.

**Comment by benibenj** [comment]
One design decision we've made is when you have multiple tabs selected in one editor group and the move focus into another editor group, the selection of the previous group is cleared. This is what is happening in this case. This behaviour i not final yet. We are not dure yet what users would prefer.

@dbaeumer Would you expect that the selection is kept when switching focus between editor groups?

**Comment by dbaeumer** [comment]
@benibenj yes that is what I would expect. It is very easy to clear a selection by single clicking on a tab.
