### ISSUE TITLE
Inline chat broken rendering when using accessibility mode

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#213614]
1. Enable accessibility mode
1. New empty file
2. `Cmd + i` to open inline chat
3. "Write sorting function"
4. Inline chat has broken rendering

I can repro 100%. 
Looks like the scroll is off.

![Image](https://github.com/microsoft/vscode/assets/1926584/240a2005-a72f-4e26-980f-dd0aa137b562)

**Comment by jrieken** [comment]
@isidorn You have accessibility mode enabled, right?

**Comment by isidorn** [comment]
Yes. Good catch. 
If I disable accessibility mode I can not repro.

**Comment by jrieken** [comment]
Thanks for clarifying. I have updated the steps accordingly

**Comment by TylerLeonhardt** [comment]
<img width="753" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/2975754f-0a92-4b31-aefc-737c425325ca">
it's better... but still kinda weird with a vertical scroll bar that doesn't scroll anything... just the big white space. I'll open as a new issue and mark this as verified.
