### ISSUE TITLE
Ending the active session gives undefined activeStackItem even if there is another session

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#213646]
Testing #213603

Here is the extension code listening to activeStackItem

```ts
context.subscriptions.push(
        vscode.debug.onDidChangeActiveStackItem(session => {
            console.log('Active debug stack item changed: ', vscode.debug.activeStackItem);
        })
    );
```

Steps

- Open a workspace with two python files
- Install Python Extension
- Open file 1 with content `print ('Hello File 1')`. Keep a break point on this line and start debugging this file. As expected break point hits and the debugging extension logs this stackItem.
- Open file 2 with content `print ('Hello File 2')`. Keep a break point on this line and start debugging this file. As expected break point hits and the debugging extension logs this stackItem.
- Resume the second session to continue.

🐛 Extension logs `undefined` first for `activeStackItem` and after it logs the stack item of first session

**Comment by connor4312** [comment]
Thanks for the bug. This actually represents the view state accurately at the moment: we focus the session, not a thread, and this is not represented in the API. I'll see if consumers run into a case where they need this info, but unless I hear something from consumers I plan to leave as-is.
