### ISSUE TITLE
No text to speech when a change is applied

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#213667]
Testing #213355

There was no audio at all:
![Image](https://github.com/microsoft/vscode/assets/9205389/0791f875-0d62-4620-a7e0-a58e079695e3)

Could be related to https://github.com/microsoft/vscode/issues/213640, though pressing the speaker command doesn't read anything either.

**Comment by TylerLeonhardt** [comment]
So it says "Made changes" now. I don't mind it just saying "made changes" visually because I can also visually see the code changes, but I feel like I wish that it would maybe speak a summary of the diff so it says more than just "made changes"
