### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'activeElement')

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#213649]
Testing #213597

* open issue report on web
* go the extension flow, select a extension
* click into the title input field
* :bug: the console shows the error below 👇 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'activeElement')
    at ot.m (workbench.web.main.js:135:43591)
    at new ot (workbench.web.main.js:135:43760)
    at xe (workbench.web.main.js:135:44211)
    at b.ib (workbench.web.main.js:2406:7508)
    at workbench.web.main.js:2406:5805
```

**Comment by justschen** [comment]
@jrieken can you check this now? I don't see anything anymore and i believe it's fixed with the new DOM checks that just got merged to fix https://github.com/microsoft/vscode/issues/213645
