### ISSUE TITLE
Retain workspace state (opened/pinned tabs,  ...) when opening via command line with a folder and a file as as arguments

### ISSUE THREAD

**Issue by thefasquelle** [microsoft/vscode#213639]
Consider this minimal workspace
![before_close](https://github.com/microsoft/vscode/assets/139963448/e80afde2-c0d7-4e87-9280-a297fb866e1c)

After closing it, when re-opening the folder in vscode via the command line (with `code myfolder`), it restores the workspace last state (opened/pinned tabs, where I was in the file, etc.).

But when specifying the same folder + a file present in this folder (with `code myfolder myfolder/file1.txt`), only the specified file is opened. The previously opened tabs, and more importantly the pinned tab, are now closed
![cmd_folder_and_file](https://github.com/microsoft/vscode/assets/139963448/040485d4-7947-46a3-a570-7c2f148d4442)

I suppose this is by design, but I wish there was an option (maybe a flag) to open the first workspace argument and restore its state as usual, then open in this workspace any additional file specified in other arguments. 

My use case would be to open a huge workspace with a lot of generated files, and focus a specific file in it. The command is launched from the tool that generates the files. As the workspace also contains human-written files that I wan't to keep opened, having them closed whenever I use the command line is pretty annoying and forces me to navigate the workspace to find my files.

**Comment by bpasero** [comment]
Try with `window.restoreWindows` set to `preserve`

**Comment by thefasquelle** [comment]
thank you for your help !
It does 100% meets the feature request (I would have prefer to be able to keep the 'none' behavior when i open vscode from start menu), but your solution is good enough for me.

I think the text description of this settings is misleading. It says (translated from french) "Controls how windows are opened **after the very first startup**. **This parameter has no effect when the application is already running**"; but it does.

**Comment by bpasero** [comment]
Yes, I can make it better.

**Comment by thefasquelle** [comment]
@bpasero Your solution worked for a few days, but now I have an issue.

When I run the command  with a folder and file in this folder as argmuents, 
- if the folder is already opened in vscode, the corresponding window gets focused and the file is opened in it (expected behaviour)
- if vscode is already opened but not the folder given as first argument, it opens a new window for the folder and opens the file in it (expected behaviour)
- if vscode is *not* already opened, it opens the last closed window, opens the file in it, then opens the folder in a new window. What I expect in this scenario is to open the folder in a new window first (because it is first argument) and  then open the file in the new window (because it is contained in its workspace, and is not in other opened workspaces)

I don't know if it is due to 1.90.0 update or if this behaviour was already present but I simply didn't stumbled upon it because I was always in scenarios 1 or 2

is this expected behaviour, and if yes, why ?
Should I open a new issue for this ?

**Comment by thefasquelle** [comment]
I opened a new issue here #216602
