### ISSUE TITLE
@vscode/deviceid not found in WSL

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#213697]
1. Open a folder
2. Reopen in WSL and show logs
3. Observe the error log

![image](https://github.com/microsoft/vscode/assets/2230985/89d16996-a887-4f63-97b6-fd8af58547ae)

**Comment by lramos15** [comment]
Are things broken in this case or just a bad stack trace. I'll take a look to see if I missed a module include somewhere

**Comment by connor4312** [comment]
Just a bad stacktrace from what I see, though I didn't intentionally go test things thoroughly
