### ISSUE TITLE
Is label "Find in Cell Selection" confusing?

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#213666]
Testing #213607

I found "Find in Cell Selection" confusing label for the button given it is to find in selected cells. Does it make sense?

Would "Find in Selected Cells" be a bit easier?

![Image](https://github.com/microsoft/vscode/assets/16353531/4862b9ad-2a0e-4bd7-b274-bc4c015f3e2d)

**Comment by Yoyokrazy** [comment]
Yeah, agreed that the labeling isn't perfect. Will workshop this in the next iteration, as this button will be serving dual purpose as a way to search in textual selections within a cell, as well as searching in multi-cell selections as the feature is currently. Thanks for the feedback!
