### ISSUE TITLE
Theme Icons not showing up

### ISSUE THREAD

**Issue by kumaralg2** [Microsoft/vscode#21360]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.3.3|
|laravel-5-snippets|atefth|0.0.1|
|theme-material|bcmarinacci|1.3.0|
|php-autocomplete|bschulte|0.4.2|
|vscode-html-css|ecmel|0.0.33|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.2|
|Theme-Laravel|gerane|0.0.2|
|laravel-blade|onecentlin|1.8.1|
|laravel5-snippets|onecentlin|1.3.2|
|laravel-artisan|ryannaddy|0.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@kumaralg2 steps?
