### ISSUE TITLE
Pressing Tab on when using Accessible View on hover will close the view

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#213662]
Testing #213342

![image](https://github.com/microsoft/vscode/assets/31675041/fa1204c9-a49b-42fa-9cb1-fe12acb8e3a0)

Not sure whether this is expected:
1. Focus on hover using cursor.
2. Use alt+f2 to open accessible view.
3. The message says to use Tab to cycle through the hover parts. 
4. Pressing Tab seems to close the accessible view. I'm not sure what to expect here, but it seems unexpected? :bug:

**Comment by meganrogge** [comment]
@aiday-mar the bug here is that instead of seeing the hover content in the accessible view here, we are seeing this help message. 

<img width="552" alt="Screenshot 2024-05-30 at 10 23 35 AM" src="https://github.com/microsoft/vscode/assets/29464607/cff3cbfe-8f5e-4edb-b560-c7f95c7523fd">

**Comment by meganrogge** [comment]
making a separate issue for this.

**Comment by aiday-mar** [comment]
This is fixed
