### ISSUE TITLE
No items in Codespaces. 

### ISSUE THREAD

**Issue by shiiiiib** [microsoft/vscode#213656]
Whenever I open these kinds of activities from Mindtap, it wouldn't open fully the file and it will only show the Companion window

Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 OPR/109.0.0.0
Embedder: codespaces

**Comment by meganrogge** [comment]
it's unclear what you mean. pls create an issue for codespaces.
