### ISSUE TITLE
Go-to-symbol command not showing well in inline response for accessible view

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#213665]
Testing #213342

![image](https://github.com/microsoft/vscode/assets/31675041/d6c6ed76-7692-4aa6-b58a-51030a7e3dfc)
Not related to the original TPI, but I noticed that these 'go to symbol' command links look a bit daunting in the accessible view? 

I got to this by:
1. Highlighting some [code](https://github.com/microsoft/vscode/blob/64b74d9a64c54798b7fefa9070cbb8961917d0f9/src/vscode-dts/vscode.proposed.textSearchProvider.d.ts#L266) in inline chat 
2. Sending "explain this"
3. Using accessible view on response.

Not sure if these links can be improved somehow, or whether this is the best way to expressing them?

**Comment by meganrogge** [comment]
good find, we should strip the markdown for inline chat accessible view like we do for the panel chat responses

**Comment by accesswatch** [comment]
Should this be seen in Friday's Insider build of VSCode?

**Comment by meganrogge** [comment]
Nope, this issue will have the label insiders released tomorrow to indicate that
