### ISSUE TITLE
Aid in migrating `editor.wrappingColumn` setting

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#21364]
We should let users know about the deprecation of `editor.wrappingColumn` (done in #21262), so they are aware they should update their settings.

**Comment by alexandrudima** [comment]
To verify:

If the setting `editor.wrappingColumn` appears in user settings.json or in workspace settings.json, a prompt appears when first opening an editor. The prompt informs the new setting to be used. The prompt opens the settings, either at user settings (if the wrappingColumn is used in user settings) or at the workspace settings (if the wrappingColumn is used in workspace settings). The prompt also has an action to never show again. This is stored in local storage and will make that the prompt will never appear again until local storage is cleared.

**Comment by schmuli** [comment]
Just want to point out that I had `editor.wrappingColumn` in a language-specific block (`"[markdown]"`), and the prompt didn't show up, although I already fixed the setting based on what appears here and the linked issue.
