### ISSUE TITLE
Quick fix icon sits on wrong position with word wrapping enabled

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#213657]
The icon should be right above line 2, but it's all the way up at the beginning of line 1.

![image](https://github.com/microsoft/vscode/assets/22350/66910930-cbc9-4dd9-ab24-7fcf4a17f625)

**Comment by justschen** [comment]
this should be fixed with the new lightbulb changes!

**Comment by rzhao271** [comment]
Still able to repro. If I repeat steps 3 and 4, I notice that the sparkle alternates between the two lines.

**Comment by Tyriar** [comment]
I see similar to what @lszomoru saw, but the second time it didn't show at all:

![image](https://github.com/user-attachments/assets/706d9539-a4fe-4d2f-a0a8-ab4ac6651a97)
![image](https://github.com/user-attachments/assets/bcf2f6fe-85fb-41f5-a913-0fe3474d1264)

@justschen I'll push this to September as it doesn't meet the bar to fix at this point imo.

**Comment by justschen** [comment]
@Tyriar @rzhao271 not sure why it removed the unreleased since this commit hasn't been released yet 😢

**Comment by rzhao271** [comment]
It's good now
