### ISSUE TITLE
Minor notebook UI bug - dark bar between two highlighted markdown cells

### ISSUE THREAD

**Issue by devinvalenciano** [microsoft/vscode#213729]
Testing #213607

When I highlight a set of markdown and code cells, I see a darker bar that only appears between two markdown cells.  Image below shows what I'm seeing, with stars indicating where I'm seeing the darker bars:
![highlights](https://github.com/microsoft/vscode/assets/1389808/09696eae-de98-49a7-bcca-f54279ec878c)

**Comment by rebornix** [comment]
I don't reproduce this issue anymore.
