### ISSUE TITLE
Ghost text completion suggestions push cursor to end of suggestion

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#213703]
Using copilot completions in the latest VS Code insiders, I see the cursor being pushed to after the suggested text. This makes it very difficult to work with the text while passive completions are suggested.

<img width="1126" alt="image" src="https://github.com/microsoft/vscode/assets/6561887/e6bdea0f-7531-4a73-8433-c010f09107e8">

**Comment by ulugbekna** [comment]
@hediet is it possible to differentiate between an inline completion and inlay hint in the editor? maybe we could have different behavior in different cases?
