### ISSUE TITLE
Alt +k not working on accessibility view 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#213737]
Testing #213343

 Alt+k should open a quickpick which allows us to configure the keybindings but it's not working on Windows:

![accessibilityaltknotworking](https://github.com/microsoft/vscode/assets/45497113/9ed4533a-f4b4-43ba-a781-62688cf4b1c1)

**Comment by meganrogge** [comment]
@aiday-mar, reverting 7f55a08 fixes this issue for me. Would you pls take a look?

**Comment by meganrogge** [comment]
@aiday-mar this change fixes it, so calling `provider.onClose` here is the issue

![Screenshot 2024-05-28 at 3 46 24 PM](https://github.com/microsoft/vscode/assets/29464607/e910b8d2-7375-4ccc-a822-862f209efba6)

**Comment by meganrogge** [comment]
It looks like the issue is now we call `provider.onClose` when the editor widget is blurred.

Commenting out this code fixes the issue:

https://github.com/microsoft/vscode/blob/05634b5fcdc02792b7f4546d1e56d4b87b5b9296/src/vs/workbench/contrib/chat/browser/actions/chatAccessibilityHelp.ts#L77-L88

**Comment by aiday-mar** [comment]
Hi @meganrogge thank you for taking the time to look into it.
