### ISSUE TITLE
Add ability to update a Quickpick placeholder text dynamically

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#21373]
- VSCode Version: `1.10.0-insider` 256d76fed7947e7289f921df10658d7a69233b65
- OS Version: macOS Sierra `10.12.3 (16D32)`

I would love to be able to change the placeholder text after `showQuickPick` has been called. That way I could have the quickpick say something like `Searching for blah...` while the promise is still waiting, and then switch to different text once its resolved.

Currently I am mimicking this behavior by showing 1 quickpick with the `Searching for ...` text, and then when the promise resolves I am cancelling that quickpick and show a new one -- but if there was text typed during that time it would be lost.

**Comment by jrieken** [comment]
We could use the progress API that is the works and use that area for the progress presentation

**Comment by jrieken** [comment]
We now have API for that.
