### ISSUE TITLE
Add ability to trap `right-arrow` key press on a Quickpick item

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#21374]
- VSCode Version: `1.10.0-insider` 256d76fed7947e7289f921df10658d7a69233b65
- OS Version: macOS Sierra `10.12.3 (16D32)`

I would like to be able to trap a `right-arrow` key press on a Quickpick item, to provide similar behavior to the built-in open files picker.

**Comment by jrieken** [comment]
@bpasero Is the quick select command something we have documented and that can be bound to a different key?

**Comment by bpasero** [comment]
No, the behaviour for right-arrow is still [hardcoded](https://github.com/Microsoft/vscode/blob/ben/next/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L159) and not expressible as command. 

However I am not sure @eamodio asks for that, I think as an extension he wants to define the command that runs when pressing right-arrow in the picker his extension owns.

**Comment by eamodio** [comment]
@bpasero yes, exactly that.

**Comment by jrieken** [comment]
> I would like to be able to trap a right-arrow key press on a Quickpick item, to provide similar behavior to the built-in open files picker.

By that you mean "select the item without closing the picker", right? We don't abstract on the level of keys, unless you wanna implement a keybinding, so it's unlikely that we would expose the pure keypress. Also people usually want to configure keybindings. 

To get the current `arrow right` behaviour you could maybe try a combination of `onDidSelectItem`, a custom context key, and a command that binds to <kbd>-></kbd>

**Comment by eamodio** [comment]
Right, perform some action but leave the picker open.

Oh that is quite interesting on the command with custom context -- there is a lot of power in that. Is there a command to get the value of a custom context? Like a `GetContext` corollary to `SetContext`? Then it would be much easier to coordinate - as `onDidSelectItem` could `SetContext` and then the conditional command could read from that context to perform its action

**Comment by eamodio** [comment]
FYI, I have this working in GitLens now, but I am unable to trap just the `right arrow` (well I think I can most of the time, but then the user can't use the arrows in the input box -- ick), so I am currently trapping `alt+right arrow`. It would be great to have this feature, so it feels more natural with the other vscode behavior. :)

**Comment by eamodio** [comment]
@jrieken @chrmarti instead of actually supporting this -- can we set a context value for which commands can then use to support `right-arrow`. Something like `canUseQuickArrow` or some better name -- which would get set when the cursor in the quick pick input was all the way to the right. With that context value, extensions can then easily support this behavior, without breaking arrow key navigation in the quick pick input.
