### ISSUE TITLE
Notebook cell selection in find widget not updating upon new selection

### ISSUE THREAD

**Issue by devinvalenciano** [microsoft/vscode#213728]
Testing #213607

I select a set of cells with Shift+Click, and I hit Ctrl+F to open the find widget. The cells are then highlighted as such:
<img width="980" alt="image" src="https://github.com/microsoft/vscode/assets/1389808/57936c5c-aafd-40d2-8b96-d31a4fb4a521">

The find widget looks as such:
<img width="247" alt="image" src="https://github.com/microsoft/vscode/assets/1389808/82255a3f-6ecd-4d66-a80d-a8935c8096ff">

I click another cell, or try to Shift+Click and select another set.  I would expect the yellow highlight to now surround my newly selected cells, and the find widget to include the count of the word in the new selection, but nothing updates. See below:
<img width="983" alt="image" src="https://github.com/microsoft/vscode/assets/1389808/06b15b44-9388-4fed-acfd-5f57338e319c">

**Comment by Yoyokrazy** [comment]
This is the intended functionality, as the "search in selection" feature is meant to hold the selection even after you shift your focus. This matches the standard code editor functionality.
