### ISSUE TITLE
Ability to use a custom profile as a default profile

### ISSUE THREAD

**Issue by AWenmanFK** [microsoft/vscode#213721]
Duplicate of a feature that was said to be solved, but nothing is actually changed or solved.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/181677
```

**Comment by gjsjohnmurray** [comment]
The new feature is coming in the 1.90 release, which you can already use if you install VS Code Insiders.

**Comment by AWenmanFK** [comment]
ahh, thank you very much @gjsjohnmurray!!
