### ISSUE TITLE
off topic request throws error

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#213710]
Testing #213552

1. Use unmodified chat extension sample
2. Run `@cat tell me a story`
3. 🐛 see `Language model errored` (I'd expect to see the off topic filter)
4. In dev tools:
```
 ERR [CHAT] extension request ERRORED Error: filtered as off_topic by intent classifier: message was not programming related
    at u2.provideLanguageModelResponse (/Applications/code-insiders-portable-data/extensions/github.copilot-chat-0.16.2024052801/dist/extension.js:1001:3622)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) vscode-samples.chat-sample 496141
log.ts:439   ERR filtered as off_topic by intent classifier: message was not programming related: Error: filtered as off_topic by intent classifier: message was not programming related
    at u2.provideLanguageModelResponse (/Applications/code-insiders-portable-data/extensions/github.copilot-chat-0.16.2024052801/dist/extension.js:1001:3622)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

<img width="1788" alt="Screenshot 2024-05-28 at 11 17 22 AM" src="https://github.com/microsoft/vscode/assets/29464607/9c5b7536-457f-4c12-bd99-a23c4db50f94">

Here are the logs, keyword: `failed request` for the logs that happened around this time
[logs.txt](https://github.com/user-attachments/files/15474282/logs.txt)

**Comment by jrieken** [comment]
We have two options (and should do both)

1. update the sample to do proper error handling (@isidorn)
2. do nicer error printing when invoking a participant fails

**Comment by isidorn** [comment]
I can do 1. I would just log the error. Let me know if there is anything more creative I could do in error handling.

**Comment by meganrogge** [comment]
Should this be labeled a bug so it gets verified @jrieken ?

**Comment by jrieken** [comment]
> Should this be labeled a bug so it gets verified @jrieken ?

Sure, sure but I not yet certain that what I have changed is enough ;-)

**Comment by alexr00** [comment]
What am I supposed to see? I see this in the console:

![image](https://github.com/microsoft/vscode/assets/38270282/ba415bff-8687-4ad0-b72f-f87f80ac4945)

and this in the chat view:

![image](https://github.com/microsoft/vscode/assets/38270282/35f40eb8-6029-4576-b84d-eeacd3fb08e2)

**Comment by roblourens** [comment]
Yeah, ugly raw error but at least we expose the real error instead of the wrapper, so I think this is good default behavior.
