### ISSUE TITLE
Linux: moving folder dialog moves the entire window behind it

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#213767]
Testing #213763

![Recording 2024-05-29 at 06 39 13](https://github.com/microsoft/vscode/assets/900690/8248a197-47d0-40a0-bc0b-967ba2849975)

In stable I was able to move the dialog independent from the parent window but in Electron 29 it seems to move the window as well?

**Comment by deepak1556** [comment]
Yes this is correct behavior, the dialog was not attached to the window in stable and  this was also the reason for the bug https://github.com/microsoft/vscode/issues/146422. Please compare the behavior with `1.65.0` stable.
