### ISSUE TITLE
VS Code git issues

### ISSUE THREAD

**Issue by CDitzel** [Microsoft/vscode#21378]
I am working a large directory and opened vscode in the root folder.

However, in the git area I am only shown the changed files of that very directory rather than those of subdirectories as well.

How can i change that?

**Comment by roblourens** [comment]
Are there git repos in those subdirectories too?

**Comment by CDitzel** [comment]
yes in the form of submodules mostly

**Comment by roblourens** [comment]
I think this will fall under #7829 but I'll leave it for Joao

**Comment by joaomoreno** [comment]
Yup, we don't have submodule support.
