### ISSUE TITLE
Administration

### ISSUE THREAD

**Issue by PaulSicurello** [microsoft/vscode#213754]
Type: <b>Performance Issue</b>

I have new computer and when I download VS Code, it says I will not be able to get updates because I am running as a admin. I have tried down loading more then once but can't seem to get it out of admin mode. Can you Help

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (27.01GB free)|
|Process Argv|--crash-reporter-id 4f856874-cfde-4996-994e-f5caadb2a0b7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   111	  6688	code main
    0	   192	  2568	   gpu-process
    0	   157	  6256	extensionHost [1]
    0	    81	  7840	     electron-nodejs (eslintServer.js )
    0	   141	 11232	     "C:\Users\Paul Sicurello\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Paul Sicurello\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=6256
    0	    41	  6312	   utility-network-service
    1	    94	  6696	window [2] (Issue Reporter)
    0	    29	  7468	   crashpad-handler
    0	   125	  7852	shared-process
    0	   267	  8872	window [1] (index.html - HTML CSS - Visual Studio Code [Administrator])
    0	    86	 12028	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - HTML CSS - Visual Studio Code [Administrator])
|    Folder (HTML CSS): 13 files
|      File types: css(2) otf(1) zip(1) html(1) jpg(1) js(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.4
vscode-html-css|ecm|2.0.9
prettier-vscode|esb|10.4.0
vscode-firefox-debug|fir|2.9.10
powershell|ms-|2024.2.2
LiveServer|rit|5.7.9
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-icons|vsc|12.7.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
724cj586:31013169
pythoncenvptcf:31049071
a69g1124:31058053
dvdeprecationcf:31061161
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by joaomoreno** [comment]
https://www.howtogeek.com/ways-to-run-an-app-as-an-administrator-on-windows/
