### ISSUE TITLE
Simplify filing a bug report for an extension

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#21376]
If there is a "bugs" URL in the extension's package.json, we could:
- Show a link at the top of the extension editor (the one opening when I click on an extension in the extensions viewlet).
- Either let the Report Issues action ask if it's for one of the installed extensions
- Or have a separate action for extensions, e.g., Help > Report Extension Issues, that asks for which of the installed extensions.

**Comment by bpasero** [comment]
I like that 👍

**Comment by chrmarti** [comment]
A related improvement could be to make the list of extensions from Report Issues link to the issues of each extension. That would help us dispatch issues.

**Comment by bpasero** [comment]
Remember that there is a max URL restriction, so we are limited what to put there.

**Comment by jportela** [comment]
@joaomoreno I can work on this one. As for displaying a "Report Issue" button on the extension view, should that button appear near the Uninstall button or the Dependencies link? (see picture below) 

<img width="526" alt="screenshot 2017-04-30 15 55 05" src="https://cloud.githubusercontent.com/assets/1010018/25565368/a5052dd6-2dbd-11e7-9857-90c3be305ed0.png">

Regarding:

> Either let the Report Issues action ask if it's for one of the installed extensions
> Or have a separate action for extensions, e.g., Help > Report Extension Issues, that asks for which of the installed extensions.

Should we implement both? Or just one of those?

**Comment by joaomoreno** [comment]
I think the button should appear near the uninstall button.

Both sounds great!

**Comment by avannaldas** [comment]
I think #27331 can be clubbed with this one. Having a GitHub repo button and Report Issue button separately doesn't make sense.

**Comment by smbkr** [comment]
I think this can be closed now. Help>Report Issue already asks if it's related to an extension and opens the issue on the relevant repo.
