### ISSUE TITLE
no warning that a matching model was not found

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#213716]
Testing #213552

1. modify the chat extension sample by changing the `family` of the `MODEL_SELECTOR` to `fake`
2. requests still succeed
3. a fallback model is used, but there's no indication of that

Perhaps we could say in the docs that this will happen if no matching model is found? Or add a warning?

**Comment by jrieken** [comment]
> a fallback model is used, but there's no indication of that

That would be news to me. There is no fallback and when using a selector like you did nothing should be returned. 

@meganrogge Please share your complete code sample so that I understand what's going on

**Comment by meganrogge** [comment]
@jrieken the only change I made to the sample extension for this case is described in the description.

**Comment by jrieken** [comment]
Indeed
