### ISSUE TITLE
Keybinding is confusing if it has two different cases of enablement

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#213738]
Testing #213343

This is telling me alt+k does two different things:

![image](https://github.com/microsoft/vscode/assets/2230985/fab9ae4c-72b7-40c1-a9d4-cdff0be49aed)

Maybe things that only apply to when the accessibility help view is open should say that to avoid conflicts

**Comment by meganrogge** [comment]
@connor4312 i'm confused, the `when` clause makes that clear. also, we resolve the keybinding for the accessibility help view focused context, so isn't it clear that `alt+k` applies when in the help dialog?

**Comment by connor4312** [comment]
Oh, I misread the help, I thought the two alt+k's were different keybindings. This is fine then 👍
