### ISSUE TITLE
Feature Request: Allow to specify languages in `formatOnSave`

### ISSUE THREAD

**Issue by KalitaAlexey** [Microsoft/vscode#21377]
Created because of [issue in my extension](https://github.com/editor-rs/vscode-rust/pull/74).

Some people needs to be able to specify what languages should be formatted automatically.
It seems right for me.
I suggest to extend `editor.formatOnSave` to be either `Boolean` or `Object` where fields' names are language ids and fields' values are `Boolean` which indicates whether the language should be formatted on save.

It is backward-compatible change.

Before:

```json
"editor.formatOnSave": true
```

After:

```json
"editor.formatOnSave": {
    "rust": true,
    "javascript": false
}
```

**Comment by roblourens** [comment]
Recently we added language-specific settings, so you can set this option only for certain language modes. See details here: https://code.visualstudio.com/updates/v1_9#_language-specific-settings
