### ISSUE TITLE
Right border not visible for focused hover

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#213790]
![Image](https://github.com/microsoft/vscode/assets/16353531/786cd4f7-40b4-4be8-b0b0-d4d3981c1c82)

Version: 1.90.0-insider
Commit: fc8762e773c35d4e52e8a7375704af2e24698e5d
Date: 2024-05-29T05:50:53.996Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

**Comment by aiday-mar** [comment]
hey @ulugbekna yes thank you for posting this issue. I am precisely investigating this issue right now, it is likely to be caused by the following PR https://github.com/microsoft/vscode/pull/213700
