### ISSUE TITLE
The search engine does not appear in my browser / No me aparece el buscador en el explorador

### ISSUE THREAD

**Issue by Cristopher-Iturra** [microsoft/vscode#213704]
Type: <b>Bug</b>

Inglés: 
The search engine does not appear in the project explorer to be able to type a file name and it is highlighted

Previously, one would place CMD + F in the project explorer and find matches with the searched name

Español: 
No me aparece el buscador en el explorador de proyectos para poder escribir un nombre de archivo y me lo resalte 

anteriormente uno colocaba CMD + F en el explorador de proyecto y encontraba coicidencias con el nombre buscado

VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 7, 5|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 123c3ac3-2823-4b9c-a99f-912bf9915532|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-sql-formatter|adp|1.4.4
vscode-phpstorm-formatter|ani|0.0.6
clipboard-history|Anj|1.0.7
sql-formatter-vscode|arn|1.5.2
jsoncrack-vscode|Ayk|2.0.3
vscode-intelephense-client|bme|1.10.4
php-formatter|chu|0.3.0
vscode-html-css|ecm|2.0.9
php-intellisense|fel|2.3.14
search-folder|For|0.0.5
copilot|Git|1.195.0
copilot-chat|Git|0.15.2
minify|Hoo|0.4.3
ionic|Ion|1.87.0
minifyall|jos|2.10.0
vscode-map-preview|jum|0.6.0
vscode-phpfmt|kok|1.2.12
vscode-sql-formatter|lea|2.1.6
vscode-sql-formatter-fork|luc|0.0.1
git-graph|mhu|1.30.0
formate|Mik|1.2.1
clipboard-to-imgur|miy|0.0.6
vscode-language-pack-es|MS-|1.89.2024050109
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
sftp|Nat|1.16.3
color-tabs-vscode-ext|ore|0.14.1
vscode-xml|red|0.27.0
format-html-in-php|rif|1.7.0
myci-extension|Set|0.0.3
php-ci|sma|0.4.2
php-formatter|Sop|0.2.4
vscode-sftp|sun|1.1.1
vscode-icons|vsc|12.7.0
php-debug|xde|1.34.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvptcf:31049071
a69g1124:31058053
dvdeprecationcf:31052040
pythonprt:31056678
dwnewjupytercf:31046870
fa862199:31048878

```

</details>

**Comment by IllusionMH** [comment]
This change was announced in recent update https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding

But you can rebind command to your preference
