### ISSUE TITLE
Changed a setting I can't figure out, can't debug, stuck. New student trying to use for JavaScript.

### ISSUE THREAD

**Issue by DanJ210** [Microsoft/vscode#2138]
I have used Visual Studio 2013 and 2015 for Python coding and debugging. I was just learning it I just started a second semester in programming. Then I read about Visual Studio Code which seemed pretty cool as it says to be a somewhat lightweight and easy IDE and yes it absolutely sure is! I just cannot get the debugging mode to work for the life of me, can't figure out how to run the program, just 3 basic outputs. I changed a location setting somewhere in a wizard to the folder on my computer that I thought I was supposed to do and now I get this error:

request 'launch': program 'c:\Users\Daniel\OneDrive\Documents\School\COP2800 - JAVA\Assignment 1\app.js' does not exist

Now I can't figure out where this app.js file even is by doing file explorer searches, and I have uninstalled, restarted, then reinstalled back into the computer and all my previous settings remained. I had no option to remove and do a clean install or something. So I don't know what to do because I'd like to use code as opposed to eclipse or notepad or jgrasp but I have messed it up somehow. I'm reading everything I can from the Microsoft docs so we will see. I am new to all this, sorry for the newbie stuff.

**Comment by isidorn** [comment]
Hi, for setting up debugging please check out this document https://code.visualstudio.com/docs/editor/debugging

In short, the generated `launch.json` tries to detect your program file automatically, if it does not it points to a generic `app.js`. In this case you need to change the `launch.json` to point to your program entry point.

Out of the box we support node and mono debugging, and there are extensions that support Go, Powershell and Chrome debugging. So Python is not currently supported if that is what you are looking for.
