### ISSUE TITLE
Can not mouse click in IW cell editor

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#213843]
Ran into this while playing with https://github.com/microsoft/vscode-python/issues/23484
https://github.com/microsoft/vscode/assets/876920/05cf4208-7212-4014-8559-8e98b89e269e

**Comment by Adam877773** [comment]
W dniu 23 listopada 2024 00:56:20 CET, Aaron Munger ***@***.***> napisał:

**Comment by anthonykim1** [comment]
seems like mouse click and focusing on cell both work now on IW and native repl
