### ISSUE TITLE
Accessible View not available for own chat messages

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#213853]
Found when testing https://github.com/microsoft/vscode/issues/213102

1. Use screen reader optimized mode
2. send some chat messages in the panel chat.
3. focus on a response from copilot and use alt-f2, you should get an accessible view.
4. focus on a message from you to copilot and use alt-f2- no accessible view 🐛

**Comment by meganrogge** [comment]
this is by design, as a user knows what they sent, so I've been told doesn't need to closely inspect it.
