### ISSUE TITLE
Force vs code to always open files in the left panel/editor

### ISSUE THREAD

**Issue by ccomploj** [microsoft/vscode#213892]
If i click on a file from the explorer, it opens in the panel where I am currently working. Can i set it to open in the left panel as default?
I commonly use split editors (for latex documents that compile on my right panel/editor as pdf), but the file opens in the editor that i have currently active (i.e. where I am currently working, which may be the pdf document that is open on my right panel). Can i set this to open in the left editor?

**Comment by lramos15** [comment]
Try clicking the three little dots in the top right of the right editor and clicking lock group. When you go to open a file it should be placed in the first available unlocked group.
