### ISSUE TITLE
 EPERM: operation not permitted, mkdir 'c:\Users\Platform_00\AppData\Roaming\Code\Backups\1487604966871'

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#21380]
Issue Id: <b>4ea08a17-a739-ec2c-2a94-964c57838c36</b><br /><br />*Versions* <br />- 1.9.1<br />*Stack* <br />Error: EPERM: operation not permitted, mkdir 'c:\Users\Platform_00\AppData\Roaming\Code\Backups\1487604966871'<br />    at Error (native)<br />

**Comment by Tyriar** [comment]
I considered adding a message for this but it would happen so rarely, the error is reasonably readable and this is actually the ideal information to be reported.
