### ISSUE TITLE
Configure tasks in serverless can delete entire tasks file

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#213824]
Found while testing https://github.com/microsoft/vscode/issues/212047

1. Open insiders.vscode.dev/github/microsoft/vscode
2. Command "Tasks: Configure Task"
3. Choose "Open tasks.json file" and go through the prompts
4. The tasks.json will be replaced with a new tasks.json.

**Comment by jeanp413** [comment]
PR fixing it https://github.com/microsoft/vscode/pull/215810
