### ISSUE TITLE
Sparkle is placed on top of text when there would be good space on next line

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#213807]
* open a file with 1 line of content
* place cursor on next line
* observe that the sparkle could appear below the cursor where it would not interfere with any content, but it now appears on top of the text above, interfering with the content there.

<img width="297" alt="image" src="https://github.com/microsoft/vscode/assets/5047891/c249b533-75e3-4827-8dea-dc1c4d287caa">

**Comment by justschen** [comment]
added some fixes to a draft PR! not sure if we want it to go in this late, but the idea and demo is in the PR and we can try it out in insiders next iteration
