### ISSUE TITLE
configure VS Code to automatically open the Debug Console when debugging a test case

### ISSUE THREAD

**Issue by henrycomm100** [microsoft/vscode#213883]
How can I configure VS Code to automatically open the Debug Console when debugging a test case?

I've configured as below in my launch.json file, but it's not working, every time I debug a test, it will open and focus the Test Results tab.

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python Debugger: Current File",
      "type": "debugpy",
      "request": "launch",
      "program": "${file}",
      "console": `"internalConsole",`
      "internalConsoleOptions": "openOnSessionStart"
    }
  ]
}
```
This is what I got when I ask GitHub Copilot -- 
The behavior you're experiencing is a known issue with Visual Studio Code. When you debug a test, VS Code automatically focuses on the Test Results tab, regardless of the "internalConsoleOptions" setting in your launch.json file.

Unfortunately, there's currently no built-in way to change this behavior in VS Code. The "internalConsoleOptions" setting only applies when you start a debugging session manually, not when you debug a test.

As a workaround, you can manually switch to the Debug Console after starting a test by clicking on the "Debug Console" tab in the panel at the bottom of the window, or by using the Ctrl + Shift + Y keyboard shortcut.

If you'd like to see this feature in VS Code, you can submit a feature request on the [VS Code GitHub repository] The VS Code team regularly reviews feature requests and might consider adding this feature in a future update.

**Comment by roblourens** [comment]
You can set the setting `"debug.internalConsoleOptions": "openOnSessionStart"`, not in your launch.json, that seems to work. Does it work for you?

**Comment by henrycomm100** [comment]
> You can set the setting `"debug.internalConsoleOptions": "openOnSessionStart"`, not in your launch.json, that seems to work. Does it work for you?

yes, it does. Thanks so much. @roblourens
