### ISSUE TITLE
Go to file -> crtl+n -> open right not working

### ISSUE THREAD

**Issue by jpokrzyk** [Microsoft/vscode#21385]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.2|
|beautify|HookyQR|0.8.8|
|alignment|annsk|0.3.0|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|prettier-vscode|esbenp|0.9.0|
|git-project-manager|felipecaputo|1.0.1|
|auto-close-tag|formulahendry|0.3.9|
|auto-rename-tag|formulahendry|0.0.11|
|debugger-for-chrome|msjsdiag|2.5.3|
|vscode-react-native|vsmobile|0.3.1|

---

Steps to Reproduce:

Can't open a file in a new panel using the following key combo

1. cmd+p
2. Search for something that produces at least 2 results
2. crtl+n 
3. cmd+enter
4. Nothing happens. I expect file to open in a new panel on the right.

But if I use down arrow for step 3 instead of crtl+n everything works as expected. Thanks for adding crtl+n to the quick open! It was killing me that it wasn't there before ;)

**Comment by roblourens** [comment]
Seems to be fixed in Insiders, can you download that version and try it?

In 1.9 it sometimes doesn't work. @bpasero is that something you knew about?

**Comment by jpokrzyk** [comment]
Close it.

Yep seems to work fine in insiders. Thanks!

**Comment by bpasero** [comment]
Yes, this has been fixed via https://github.com/Microsoft/vscode/issues/20497
