### ISSUE TITLE
Launch.json autocomplete doesn't add the default value

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#21384]
- Go to a node2 launch config
- Type `sma`
- See `smartStep` suggestion, hit enter to accept it
- It completes with only `"smartStep"`, but it should complete with `"smartStep": true`

**Comment by roblourens** [comment]
Works in settings.json though

**Comment by isidorn** [comment]
@roblourens nice catch!

**Comment by bpasero** [comment]
Verified that `smartStep` is being auto completed with default value.
