### ISSUE TITLE
I face window not respond problem 

### ISSUE THREAD

**Issue by DevloperPratikjadhav** [microsoft/vscode#213891]
hey,
i am using Windows 11, version 23H2. recently i opened my vs code and run html& Js file they show me this error (Windows not responding) what i do now . i am totally confused. by reading tutorials i had uninstall 3 times it and reinstall it. although i had uninstall MCAcfee software . please guide me what to do to fix this issue.
![Screenshot 2024-05-30 131144](https://github.com/microsoft/vscode/assets/169687509/7e2c5258-0e42-4e0f-abce-c5dc7c4fae33)
i will add the file see and guide me

**Comment by alexr00** [comment]
> i opened my vs code and run html& Js file 

Can you provide exact steps for what this means?

**Comment by DevloperPratikjadhav** [comment]
Actually, I am learning JavaScript these days, so I use VS Code daily, but today, when I open VS Code and try to run an HTML file, I get this error repeatedly, and VS Code is hanging. I will reinstall VS Code, but still it gives me the same error.
