### ISSUE TITLE
Powershell showing escape characters

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#213811]
Type: <b>Bug</b>

Opening a Powershell terminal shows what looks like ANSI escape characters. (I do have Oh My Posh installed, but I've seen others use this without issue)

![image](https://github.com/microsoft/vscode/assets/13488/ebe05615-3f38-465c-80fc-7b9774495937)

VS Code version: Code - Insiders 1.90.0-insider (fc8762e773c35d4e52e8a7375704af2e24698e5d, 2024-05-29T05:49:46.157Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (17.26GB free)|
|Process Argv|--crash-reporter-id 362817d9-b661-4b35-92b7-fe18e5872851|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
TabOut|alb|0.2.2
githistory|don|0.6.20
xml|Dot|2.5.1
rest-client|hum|0.25.1
csharpextensions|kre|1.7.3
ecdc|mit|1.8.0
vscode-azureappservice|ms-|0.25.2
vscode-azurefunctions|ms-|1.15.0
vscode-azureresourcegroups|ms-|0.9.1
vscode-azurestorage|ms-|0.15.3
vscode-cosmosdb|ms-|0.22.0
csdevkit|ms-|1.7.2
csharp|ms-|2.31.16
vscode-dotnet-runtime|ms-|2.0.5
vscodeintellicode-csharp|ms-|2.1.11
azure-account|ms-|0.12.0
hexeditor|ms-|1.10.0
live-server|ms-|0.5.2024052901
material-icon-theme|PKi|5.3.0
vscode-thunder-client|ran|2.24.7
hl7tools|Rob|2.0.6
msbuild-project-tools|tin|0.6.3
vscodeintellicode|Vis|1.3.1
jwt-debugger|yok|0.6.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
vscrp:30624060
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:30973074
showvideot:31016890
chatpanelt:31014475
0ee40948:31013168
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupytercf:31046870
nb_pri_only:31057983
26j00206:31048877

```

</details>

**Comment by meganrogge** [comment]
/duplicate [#211922](https://github.com/microsoft/vscode/issues/211922)
