### ISSUE TITLE
How to remove that annoying popup in integrated VS Code terminal?

### ISSUE THREAD

**Issue by kodmanyagha** [microsoft/vscode#213884]
Sometimes unnecessary popups appears in integrated terminal. The cursor isn't on any link, but this annoying popup appears every time. How can I remove it? I'm adding screenshot:

![image](https://github.com/microsoft/vscode/assets/3948692/f2aeec33-d74f-45f9-91d4-218961d43b35)

PS: May be this isn't a bug, may be I must ask this to stackoverflow but I already asked this question to stackoverflow but my question deleted. Because this isn't a programming question. Because of that I'm asking here again.

This is the question which I asked in stackoverflow and it deleted and I got negative vote :( I think you must allow us to ask this kind of questions in github, not stackoverflow. Stackoverflow's rules are so boring and annoying.

<img width="929" alt="image" src="https://github.com/microsoft/vscode/assets/3948692/df87b7c8-8593-4437-95dc-6ae97b284565">

**Comment by meganrogge** [comment]
that link is coming from an extension. pls create an issue for the extension.
