### ISSUE TITLE
The terminal initial hint should be easily toggled by right clicking on the hint

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#213813]
Can this support right click to toggle the setting to hidden?

![image](https://github.com/microsoft/vscode/assets/2193314/9db59ec2-05d9-4cf4-8027-e86fe274aada)

**Comment by meganrogge** [comment]
right click shows our terminal context menu, perhaps we should just put it in there rather than adding a new one?

![Image](https://github.com/microsoft/vscode/assets/29464607/6c5d06d5-a571-4d05-9973-5a84a5434f0c)

**Comment by meganrogge** [comment]
this isn't a feature the others offer, thus not a bug IMO
