### ISSUE TITLE
Disable terminal chat hint permanently when the user has triggered ctrl+i

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#213820]
This will help resolve the issue of it being too distracting. I don't often like having state like this that cannot be reverted, but in this case I think it makes sense. It might also be better to hide only when a question has been asked, not just on open.

**Comment by meganrogge** [comment]
it's a little weird IMO that we will do this for the terminal and not for untitled editors, which I see more often than empty terminals

**Comment by Tyriar** [comment]
Yeah, maybe it should there too though?

**Comment by meganrogge** [comment]
I think these should be consistent experiences, so maybe we should discuss before merging this?

**Comment by Tyriar** [comment]
They're already not consistent as we only show there there's a single terminal and will show in a different color. The main take away I got from the discussion in #ux was that we need to reduce the amount it's shown and this suggestion got a bunch of upvotes from the team. Having it in an empty editor is less disruptive.

**Comment by meganrogge** [comment]
I am concerned about the lack of discoverability if we go with this approach.

We could fix the color. Showing it only when there's a single terminal means it's inherently less disruptive. 

Notebooks also don't do this.

**Comment by meganrogge** [comment]
> It might also be better to hide only when a question has been asked, not just on open.

This would help IMO, but still, not sure why we don't do this in other places, like notebooks.

**Comment by meganrogge** [comment]
as long as notebooks follow suit here, this sounds good to me.
