### ISSUE TITLE
Flashing Window when debugging

### ISSUE THREAD

**Issue by gholt-zift** [microsoft/vscode#213833]
Type: <b>Bug</b>

I am unable to get this issue to stop every single time I debug any file. What occurs is all of my variable names rapidly populate, and disappear causing my window to scroll rapidly up and down, resulting in a flashing type effect. I can upload a video for further evidence. 

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.20GB (3.87GB free)|
|Process Argv|--disable-gpu-compositing --crash-reporter-id 915b888a-18cc-405b-844d-1a5346b4c42b|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.10.4
npm-intellisense|chr|1.4.5
vscode-eslint|dba|2.4.4
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|10.4.0
gc-excelviewer|Gra|4.2.59
vscode-graphql|Gra|0.9.3
vscode-graphql-syntax|Gra|1.3.6
rest-client|hum|0.25.1
color-the-tag-name|jzm|0.19.8
rainbow-csv|mec|3.12.0
dotenv|mik|1.0.1
vscode-edge-devtools|ms-|2.1.5
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
remote-wsl|ms-|0.88.2
vetur|oct|0.37.3
indent-rainbow|ode|8.3.1
postman-for-vscode|Pos|1.0.3
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
php-debug|rob|1.14.0
firacode|Sey|2.2.1
code-settings-sync|Sha|3.4.3
sonarlint-vscode|Son|4.5.1
code-spell-checker|str|3.0.1
vscode-icons|vsc|12.7.0
vscode-todo-highlight|way|1.0.5
php-debug|xde|1.34.0
php-pack|xde|1.0.3
php-intellisense|zob|1.3.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31062275
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvptcf:31049071
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by gholt-zift** [comment]
https://github.com/microsoft/vscode/assets/98121924/50055047-592d-4813-b46a-8566ef64484b

**Comment by gholt-zift** [comment]
https://github.com/microsoft/vscode/assets/98121924/c259a518-aab4-46fa-bed5-b79995c50c0b

**Comment by gholt-zift** [comment]
Also of note, I have attempted to disable all extensions and that did not stop the issue. I have no updates currently available for VS Code.

**Comment by Metal001** [comment]
I have exactly the same problem on Arch Linux.

**Comment by roblourens** [comment]
This should be fixed in the latest VS Code Insiders. Try it out or wait for the next release next week. You can also disable `debug.inlineValues` in the meantime.
