### ISSUE TITLE
TS language server crashing repeatedly

### ISSUE THREAD

**Issue by j-wing** [microsoft/vscode#213836]
Type: <b>Bug</b>

Unfortunately I don't know. It seems to happen anytime I start VS code now. It began recently (~this week). 

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (11.07GB free)|
|Process Argv|--crash-reporter-id 8eebaa76-afb0-459d-a5a3-53b28a790d1f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|Memory (System)|15.48GB (12.71GB free)|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
gotemplate|cas|0.5.0
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.4.3
mdx|sil|0.1.1
rewrap|stk|1.16.3
pdf|tom|1.2.2
vim|vsc|1.27.3
vscode-tailwindcss|bra|0.10.5
firecode|ChF|1.3.0
vscode-eslint|dba|2.4.4
gitlens|eam|15.0.4
prettier-vscode|esb|10.4.0
figma-vscode-extension|fig|0.3.5
copilot|Git|1.196.0
copilot-chat|Git|0.15.2
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.88.1
gti-vscode|Gra|0.6.1
vscode-github|Kni|0.30.7
reflow-markdown|mar|2.1.0
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
vscode-jest|Ort|6.2.5
vs-code-prettier-eslint|rve|6.0.0
gitblame|wad|11.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
chatpanelc:31048052
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31049070
a69g1124:31058053
dvdeprecationcf:31061161
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by j-wing** [comment]
I am, yarn v1.22.19

**Comment by mjbvz** [comment]
Thanks. This is caused by Yarn

Here's the upstream issue that also mentioned possible workarounds until it is fixed: https://github.com/yarnpkg/berry/issues/6270

**Comment by j-wing** [comment]
Thanks @mjbvz! Unfortunately neither of the mitigations in that issue helped (unless I'm doing that wrong, which is possible. I'm using TS 4.9.5 and added the relevant setting to `settings.json` (attached). Any advice for further debugging I can do to figure out why the mitigations don't work?

![image](https://github.com/microsoft/vscode/assets/667676/67d28376-c3ec-41d1-a9eb-53d0f20384ec)
[settings.json](https://github.com/microsoft/vscode/files/15493207/settings.json)

**Comment by mjbvz** [comment]
> TS 4.9.5

This is an out of date TS version. Make sure to update to the latest stable release (5.4.5) to get all the most recent fixes
