### ISSUE TITLE
How I can find tab of some extension?

### ISSUE THREAD

**Issue by AndreyChursin** [microsoft/vscode#213888]
Type: <b>Feature Request</b>

Hello,

I've been working with VS Code for a long time, I really like this program and it's its free distribution that makes it first on my list! Thank you so much for your work and this product!

Regarding the problem: I installed the "Todo Tree" extension, it added a tab to the sidebar, and after several years I lost that tab and cannot recover it.
Perhaps somewhere there are instructions on how to return the extension tabs, but reinstalling the extension did not help me.

Suggestion: It would be great to have a search for all extension tabs in the sidebar context menu or in main menu.

Best regards, @AndreyChursin

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin x64 22.6.0
Modes:

**Comment by AndreyChursin** [comment]
@sandy081 no
<img width="468" alt="image" src="https://github.com/microsoft/vscode/assets/11028058/a057db94-2681-4e99-9aa1-86554db7d14d">

**Comment by sandy081** [comment]
May be you would have moved it. Try resetting the locations - `F1 > View: Reset View Locations`.

**Comment by AndreyChursin** [comment]
Maybe, but it will reset all my view preferences. 
This issue mostly "Feature Request"...

**Comment by sandy081** [comment]
You can also find the view from the command pallette and pin it or move it.

`F1 > Open View... > Name of the view`
