### ISSUE TITLE
PHP syntax highlight bug

### ISSUE THREAD

**Issue by aidantwoods** [Microsoft/vscode#21387]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0

---

Steps to Reproduce:

1.
   Give the PHP syntax highlighter the following code
   ```php
   <?php
   
   class Foo
   {
       function bar(
           $baz,
           $boo
       ) {
   
       }
   }
   ```
2. Final param is never correctly highlighted
   <img width="332" alt="screen shot 2017-02-24 at 19 01 26" src="https://cloud.githubusercontent.com/assets/3288888/23316804/d8542606-fac3-11e6-8897-8b8cb206fa2f.png">

**Comment by roblourens** [comment]
Seems that this has been fixed
