### ISSUE TITLE
Editor Screen freezes frequently

### ISSUE THREAD

**Issue by uchiha-satyam** [microsoft/vscode#213875]
Type: <b>Performance Issue</b>

The code editor screen keeps freezing for some seconds from time to time while writing code. This started happening after I updated my windows 11 to new version (24H2). I tried enabling dedicated GPU but the issue didn't resolved. 

My windows version:
![Screenshot 2024-05-30 133914](https://github.com/microsoft/vscode/assets/89510414/4c966dd1-33ef-4751-9938-57978d396633)

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.36GB free)|
|Process Argv|--crash-reporter-id 62b80ad8-fa58-42bc-bcca-98592445dd52|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   118	 21748	code main
    0	   114	  2748	shared-process
    0	   274	  3416	window [1] (4.py - 100 Days of Code - Visual Studio Code)
    0	    89	  4628	fileWatcher [1]
    0	    31	 13920	   crashpad-handler
    0	   101	 17096	window [3] (Issue Reporter)
    0	    44	 20936	   utility-network-service
    0	   100	 21260	ptyHost
    0	     8	  2520	     conpty-agent
    0	     8	  9732	     conpty-agent
    0	   104	 10924	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\satya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	   117	 15840	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\satya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	   104	 16640	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\satya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     8	 21276	     conpty-agent
    0	   250	 21552	extensionHost [1]
    0	   136	  4140	     electron-nodejs (tsserver.js )
    0	    94	 11808	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	   108	  8300	     "C:\Users\satya\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\satya\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=21552
    0	    92	 10136	     "C:\Users\satya\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\satya\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=21552
    0	    86	 14340	     "C:\Users\satya\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\satya\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=21552
    1	   142	 15068	     electron-nodejs (tsserver.js )
    0	    42	 16864	     c:\Users\satya\AppData\Local\Programs\Python\Python38\python.exe c:\Users\satya\.vscode\extensions\ms-python.autopep8-2024.0.0\bundled\tool\lsp_server.py
    0	     7	 11196	       C:\WINDOWS\system32\conhost.exe 0x4
    0	   316	 20412	     electron-nodejs (bundle.js )
    0	    91	 21884	     electron-nodejs (eslintServer.js )
    0	   208	 22572	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (4.py - 100 Days of Code - Visual Studio Code)
|    Folder (100 Days of Code): 10567 files
|      File types: py(4124) pyc(3301) pyi(239) pyd(69) exe(64) txt(62)
|                  typed(54) pyx(45) c(45) f90(39)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
turbo-console-log|Cha|2.10.4
path-intellisense|chr|2.8.5
dart-code|Dar|3.88.1
flutter|Dar|3.88.0
vscode-eslint|dba|2.4.4
javascript-ejs-support|Dig|1.3.3
competitive-programming-helper|Div|6.1.0
es7-react-js-snippets|dsz|4.4.3
file-icons|fil|1.1.0
auto-close-tag|for|0.5.15
code-runner|for|0.12.2
better-cpp-syntax|jef|1.17.2
rainbow-csv|mec|3.12.0
graphql|mqu|0.1.2
autopep8|ms-|2024.0.0
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
remote-containers|ms-|0.362.0
cmake-tools|ms-|1.18.41
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2024.2.2
vsliveshare|ms-|1.0.5918
postman-for-vscode|Pos|1.0.3
LiveServer|rit|5.7.9
cmake|twx|0.0.17
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.6.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31049070
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupyter:31046869
fa862199:31048878

```

</details>

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by uchiha-satyam** [comment]
> Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`
> 
> If that helps, you can permanently configure this option via:
> 
> * Command Palette search for "Configure Runtime Arguments"
> * Set `disable-hardware-acceleration: true`
> * Restart

Thanks for the support. This solution worked 🙂
