### ISSUE TITLE
I'm locked from progressing to the next pag, even though i've follow all the steps and ran the code correctly

### ISSUE THREAD

**Issue by DarylWee** [microsoft/vscode#213991]
I've input all the codes and functions, and the results came out correct, but it says i haven't completed the problem..?
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by gjsjohnmurray** [comment]
/causedByExtension please use your course support channel
