### ISSUE TITLE
Upgrading same plugin multiple times in each window

### ISSUE THREAD

**Issue by akggowda** [microsoft/vscode#213948]
Does this issue occur when all extensions are disabled?: Yes/No
NA

- VS Code Version: 1.89.1
- OS Version: macOS 14.5

Steps to Reproduce:

1. If there's any extension which needs upgrade, then open two windows
2. We could see the same extension being upgraded in both windows. 

<img width="1357" alt="Screenshot 2024-05-30 at 2 33 16 PM" src="https://github.com/microsoft/vscode/assets/170036669/fab88ddf-2d74-4b0e-a001-2fb6de73fdbf">

**Comment by sandy081** [comment]
This update is coming from the extension. Please file the issue against the corresponding extension.
