### ISSUE TITLE
Remote SSH causes memory leak and crash on host machine

### ISSUE THREAD

**Issue by philippe-gagne** [microsoft/vscode#213919]
Issue Type: <b>Bug</b> (Performance)

When SSHing into my host machine, one of the VSCode processes on the host machine to grow in memory consumption continually until it is manually killed, or until it crashes the machine.

Issue #151205 is very similar to what I am experiencing, but that thread closed without a solution because the reporter turned back his VS Code to version 1.66, which stopped the issue. I tried that, but it had no effect.

I've also tried an extension bisect, which couldn't identify a responsible extension.

Using `ps -eo pcpu,pmem,user,pid,command`, I identified the responsible process as:
` /home/pgagne/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/node /home/pgagne/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/out/bootstrap-fork --type=fileWatcher`

Usually, when I am using Remote SSH, I have the entire host machine open as a folder in my workspace. I understand that this might cause memory issues with filewatcher trying to recursively watch too many files simultaneously, but I've previously used remote SSH in the same way on other similar hosts with no issue. And actually, that other host machine had more files on it than this one does.

VS Code version: Code 1.89.1
OS version: Windows_NT x64 10.0.22631
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1360P (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.64GB (3.50GB free)|
|Process Argv|--crash-reporter-id d27520f7-612e-4034-a1af-91e54ef6667e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|2.0.9
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
vscode-typescript-next|ms-|5.5.20240505

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
666c4381:31062274
chatpanelc:31048052
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by lszomoru** [comment]
@deepak1556, do you mind taking a look at this one? Thanks!

**Comment by rzhao271** [comment]
Hi @philippe-gagne does this issue still occur for you on VS Code 1.96?
If it does, could you attach a crash report following the steps at [Creating a Crash Report](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report)?
