### ISSUE TITLE
Add right click Duplicate File context menu option to File Explorer

### ISSUE THREAD

**Issue by panupans** [microsoft/vscode#213907]
Reopening because this was closed without any resolution: https://github.com/microsoft/vscode/issues/127256

Problem statement
Quite often developers start writing code from existing code. Especially for templated code like test cases or REST apis. It currently takes 4 steps to do this in VSCode (copy, paste, find, rename). In macOS finder you can right-click on any file and select duplicate and the file will be copied/duplicated with the suffix -copy added to the name. It would be great to have this functionality as a context menu item in the explorer of VSCode.

Existing workflow
If you want to make a copy of a file in VSCode today, you must right-click and select copy but you cannot right-click and select paste. No, you have to find an empty area of the explorer window or the folder name that you want the file in to right-click and select paste. Then you need to find the file that just got pasted, and right-click a third time and select rename to rename the file. This is four (4) steps just to duplicate one file. This is an extremely clumsy user experience.

Proposed workflow
A developer can highlight any file in the explorer and right-click and select duplicate. The command pallet prompt area would open up with the name of the file requesting the name of the new file. The developer would name the file and press enter and have a new file with a new name with the contents of the original file. I believe this is a much better user experience.

Workarounds
Ctrl+Drag on Windows. Option+Drag on Mac. But I don't think anyone really knows about these. We use Duplicate File a lot, it should be in the context menu with a hint for the shortcut.

Benefit to developers
Developers can duplicate a file with a new name in a single interaction instead of having to perform four steps (copy, paste, find the file, rename)

**Comment by gjsjohnmurray** [comment]
I suggest you look for an extension that does this.

https://marketplace.visualstudio.com/search?term=duplicate%20file&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by panupans** [comment]
Thank you. Since I found the shortcut, I'll be using it.
For reference, XCode has File > Duplicate right under the save button.
<img width="258" alt="Screenshot 2024-05-30 at 20 08 42" src="https://github.com/microsoft/vscode/assets/69979275/552f1fea-44da-4062-98eb-9e0ac70240da">

Hope you guys will add it somewhere more accessible for new users.
