### ISSUE TITLE
Mouse cursor turns into a black 1-inch square

### ISSUE THREAD

**Issue by geneelyn** [microsoft/vscode#213956]
Type: <b>Bug</b>

I got a request to provide VS Code feedback on the bottom right corner.  I clicked on the X to get rid of the box and the mouse cursor became a black 1-inch square.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 6.8.0-31-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13800H (4 x 2918)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|15.62GB (12.87GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id e699ae77-c6b8-48d6-b65d-f3d6a6be1db0|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-tools|ms-|1.18.41
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.9.10
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
666c4381:31062274
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecationcf:31061161
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by hediet** [comment]
Thanks for reporting! Can you share a screenshot?

**Comment by geneelyn** [comment]
I think it is a VS Code problem because that's what I'm using when my
cursor turns into a 1-inch square, but just now it turned into a square
while I was on the Ubuntu desktop wanting to switch from the terminal
window to the VS Code window.  As soon as I hovered over the VS Code icon,
the cursor turned into a 1-inch square.  When I moved it off the VS Code
icon, it became an arrow again.  I am in dark mode which is why it's
usually a black 1-inch square, sometimes with blue lines like lines of code
in VS Code, but I have seen a purple 1-inch square similar to the colors of
the default Ubuntu desktop.  I will send a screenshot next, when I figure
out how to do that on Ubuntu.

Genee Lyn C. Wilson

InTrack Radar Technologies, Inc.

Phone: 719-640-5234

Email: ***@***.***

Website: www.InTrackRadar.com <http://www.intrackradar.com/>

**Comment by geneelyn** [comment]
The black square disappears as soon as I press the "Print Screen" button,
so I'm not able to screenshot it for you.

Genee Lyn C. Wilson

InTrack Radar Technologies, Inc.

Phone: 719-640-5234

Email: ***@***.***

Website: www.InTrackRadar.com <http://www.intrackradar.com/>

**Comment by geneelyn** [comment]
This is no longer an issue after reinstalling Ubuntu and VS Code.

Genee Lyn C. Wilson

InTrack Radar Technologies, Inc.

Phone: 719-640-5234

Email: ***@***.***

Website: www.InTrackRadar.com <http://www.intrackradar.com/>
