### ISSUE TITLE
Network: Folders unable to be opened

### ISSUE THREAD

**Issue by ThatKDB** [Microsoft/vscode#21397]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|htmltagwrap|bradgashler|0.0.3|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|php-debug|felixfbecker|1.10.0|
|auto-close-tag|formulahendry|0.3.9|
|auto-complete-tag|formulahendry|0.0.1|
|auto-rename-tag|formulahendry|0.0.11|
|debugger-for-chrome|msjsdiag|2.5.3|
|vscode-icons|robertohuertasm|7.2.0|
|html-css-class-completion|Zignd|1.0.3|

---
If I try to open a folder either from the explorer tab or file menu, the folder isn't opened. I get the file dialog where I can choose my folder. After choosing the folder I want, the VS Code window flashes, reloads and my folder is not added to the file explorer. I tried creating a test folder on my desktop and got the same results.

Steps to Reproduce:

1. In VS Code Explorer tab click 'open folder' or go to file>open folder...
2. Browse for and select a folder.
3. Click select folder button.

**Comment by roblourens** [comment]
VS Code can only open one folder at a time, so just that one folder should be open. Is that what you see? Just checking since you said "my folder is not added to the file explorer".

**Comment by wstagf** [comment]
I am some problem. When I open folder VSCode don't show all menu and files. 
I am using Mac.

**Comment by ThatKDB** [comment]
No, I'm trying to add a folder with subfolders. But I believe I figured out the issue. My employer uses Active Directory Roaming Profiles and sets the My Documents folder to be what roams. I created a test folder and 3 jest files in a folder in my root (C:) drive and was able to add it as normal. So there seems to be an issue with VS Code and user profile folders when used with AD. I don't have the same issues when using Sublime Text 3 or the latest Atom.

**Comment by roblourens** [comment]
Ok, so if you open a folder under My Documents, then it doesn't open the folder, and the file explorer stays empty?

**Comment by ThatKDB** [comment]
Correct. I was able to add a folder from the downloads in my user folder, but trying to add from the desktop or anywhere in the My Documents folder results in the folder no being added to the sidebar. 

[Screencast of what is happening](http://screencast-o-matic.com/watch/cbnt3w634b)

**Comment by roblourens** [comment]
I see, thanks

**Comment by bpasero** [comment]
@ThatKDB @wstagf 
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by ThatKDB** [comment]
Here you go:

**cmd output:**
λ
←[93m[main 9:24:07 AM]←[0m Starting VS Code in verbose mode
←[93m[main 9:24:07 AM]←[0m from: c:\Program Files (x86)\Microsoft VS Code\resources\app
←[93m[main 9:24:07 AM]←[0m args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'new-window-if-not-first': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
←[93m[main 9:24:10 AM]←[0m IPC#vscode-workbenchLoaded

**VS Code Console output:**
  _Console shows the same same errors on launch and on adding a folder_
index.js:31 [uncaught exception]: Error: EPERM: operation not permitted, lstat '\\ehsd.ds.contra-costa.org\homedirs\homedirs-3'

```
Error: EPERM: operation not permitted, lstat '\\ehsd.ds.contra-costa.org\homedirs\homedirs-3'
    at Error (native)onError @ index.js:31
index.js:34 Error: EPERM: operation not permitted, lstat '\\ehsd.ds.contra-costa.org\homedirs\homedirs-3'

Error: EPERM: operation not permitted, lstat '\\ehsd.ds.contra-costa.org\homedirs\homedirs-3'
    at Error (native)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:25037onError @ index.js:34
errors.ts:33 Uncaught Error: EPERM: operation not permitted, lstat '\\ehsd.ds.contra-costa.org\homedirs\homedirs-3'

Error: EPERM: operation not permitted, lstat '\\ehsd.ds.contra-costa.org\homedirs\homedirs-3'
    at Error (native)
extensionHost.ts:282 [Extension Host] Looking for parseable documents...
extensionHost.ts:282 [Extension Host] vscode-icons is active!
extensionHost.ts:282 [Extension Host] Found no documents
```

**Comment by ThatKDB** [comment]
I'm guessing it is a network share permissions issue or lack of a symlink. I've also had problems accessing the My Documents from Git Bash. But Sublime and Atom seem to be ok. 

I didn't explicitly tell Code to open `\\ehsd.ds.contra-costa.org\homedirs\homedirs-3`, but I had tried to open the the my documents folder before closing Code the previous time it was open. That folder is the share where our my documents folders are stored.

If I enter `code \\ehsd.ds.contra-costa.org\homedirs\homedirs-3 --verbose` Code opens the folder as a blank file.

If I clear the open documents and folders I get the following in the console:

`extensionHost.ts:282[Extension Host] Looking for parseable documents...
extensionHost.ts:282[Extension Host] vscode-icons is active!
extensionHost.ts:282[Extension Host] Found no documents`

**Comment by bpasero** [comment]
@ThatKDB can you run node.js and see if you can `fs.statSync` and `fs.lstatSync` the path `\\ehsd.ds.contra-costa.org\homedirs\homedirs-3` ?

Like so:
* download node.js 6.x
* run node from the command line
* type `require("fs").statSync("\\\\ehsd.ds.contra-costa.org\\homedirs\\homedirs-3")`
* type `require("fs").lstatSync("\\\\ehsd.ds.contra-costa.org\\homedirs\\homedirs-3")`

and post the results here?

**Comment by ThatKDB** [comment]
//Node v 7.7.0

\>  require("fs").statSync("\\\\ehsd.ds.contra-costa.org\\homedirs\\homedirs-3")
Error: EPERM: operation not permitted, stat '\\ehsd.ds.contra-costa.org\homedirs\homedirs-3'
    at Object.fs.statSync (fs.js:907:18)
    at repl:1:15
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:537:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:189:7)
    at REPLServer.Interface._onLine (readline.js:238:10)

<hr>

\>  require("fs").lstatSync("\\\\ehsd.ds.contra-costa.org\\homedirs\\homedirs-3")
Error: EPERM: operation not permitted, lstat '\\ehsd.ds.contra-costa.org\homedirs\homedirs-3'
    at Object.fs.lstatSync (fs.js:902:18)
    at repl:1:15
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:537:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:189:7)
    at REPLServer.Interface._onLine (readline.js:238:10)

**Comment by bpasero** [comment]
@ThatKDB that is bad, we rely on node.js fs library to be able to open and stat folders. Are you 100% sure you have sufficient permissions to access the folder from the logged in user? do commands like dir etc. work?

**Comment by ThatKDB** [comment]
@bpasero I can fully access it from Explorer, CMD/Powershell and Git Bash. I can navigate the full folder path, create and delete files/folders, etc. Sublime Text and Atom Text are able to add folders, but I do get a similar `EPERM: operation not permitted, lstat '\\ehsd.ds.contra-costa.org\homedirs\homedirs-3` error from one of the Atom extensions but it still loads the folder.

**Comment by ThatKDB** [comment]
I found a solution to this. I have to load the folder from the network mapped drive vs just the symlink share. It then will load as expected.

**Comment by bpasero** [comment]
Ok thanks.
