### ISSUE TITLE
Add an option to hide the commit AI suggestion button

### ISSUE THREAD

**Issue by TomasHubelbauer** [microsoft/vscode#213976]
I have not found any existing issues looking for `is:issue hide commit ai`.

Please introduce an option for hiding the sparkle button for filling in AI-generated commit message or disable/hide it when a custom message has been typed in.

I misclick it sometimes erasing my own commit message with AI slop. Fortunately it is possible to recover by pressing the up arrow, but it is still an annoyance especially since I never use the AI commit feature as it has not proved itself to generate useful commit messages.

I found a GitLens issue that is related and lists other good reasons for hiding AI related features which don't apply to me but could apply to other VS Code users and motivate the VS Code team to consider this feature request more broadly: https://github.com/gitkraken/vscode-gitlens/issues/2652.

Thanks for considering.

**Comment by lszomoru** [comment]
You can disable the input action button using the `scm.showInputActionButton` setting.
