### ISSUE TITLE
tar.gz can't finish syncing

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [microsoft/vscode#213996]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```sh
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.1.0-9-amd64
```
- OS Version: 
```sh
$ neofetch
       _,met$$$$$gg.          mmc@deb-kvm 
    ,g$$$$$$$$$$$$$$$P.       ----------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) x86_64 
 ,$$P'              `$$$.     Host: KVM/QEMU (Standard PC (Q35 + ICH9, 2009) pc-q35-7 
',$$P       ,ggs.     `$$b:   Kernel: 6.1.0-9-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 10 mins 
 $$P      d$'     ,    $$P    Packages: 2061 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: zsh 5.9 
 $$;      Y$b._   _,d$P'      Resolution: 1280x800 
 Y$$.    `.`"Y$$$$P"'         DE: Xfce 4.18 
 `$$b      "-.__              WM: Xfwm4 
  `Y$$                        WM Theme: JacWin10 
   `Y$$.                      Theme: Windows10 [GTK2] 
     `$$b.                    Icons: Faenza [GTK2] 
       `Y$$b.                 Terminal: terminator 
          `"Y$b._             CPU: Intel i7-9750H (2) @ 2.592GHz 
              `"""            GPU: 00:01.0 Red Hat, Inc. Virtio 1.0 GPU 
                              Memory: 603MiB / 960MiB
```
Steps to Reproduce:

1. download vscode.tar.gz from website
2. tar zxvf gz file to /opt/VSCode-linux-x64/
3. run it
```sh
cd /opt/VSCode-linux-x64/bin/;./code
```
4. click "Backup and Sync Settings", it will open chromium  and navigate to github.com
![1](https://github.com/microsoft/vscode/assets/7458713/fddee4f1-ce1c-4da7-ab61-24fbb6ba3da8)
5. i choose open xdg-open of course, then  error dialog popuped
![2](https://github.com/microsoft/vscode/assets/7458713/a00f84db-9afd-4e65-ae46-67102fb3aec3)

only tar.gz format of vscode not working, vscode with deb format works fine, maybe this is not a bug, but i don't know how to make it working, thanks for your great work!

**Comment by sandy081** [comment]
@TylerLeonhardt Assigning to you as I suppose this is related to signing.

**Comment by TylerLeonhardt** [comment]
In VS Code, you will see a notification that says "Signing in..." that you can "Cancel". Cancel it... it will then say, "Do you want to try another way?" Say "Yes". This will take you through a different flow to get auth that doesn't use `vscode://.....`

Let me know how that goes

**Comment by ziyouchutuwenwu** [comment]
not successful yet, here is the screen recorder

https://github.com/microsoft/vscode/assets/7458713/dde300aa-5080-4bb1-afea-ef5d76c9dd53

**Comment by ziyouchutuwenwu** [comment]
i start vscode with proxy on, then click cancel for the first approach, and waiting for the second approach of data syncing, it's working now.

thank you very much!!!
