### ISSUE TITLE
`getSessions` from authGetSessions proposed API only returns 1 session

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode#213947]
Does this issue occur when all extensions are disabled?: **No**, extension API issue

- VS Code Version: 1.90.0-insider bc15ede705b9168324a3440b7c80c80644743306
- OS Version: macOS Sonoma 14.5

Using https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.authGetSessions.d.ts

Steps to Reproduce:

1. Sign in to multiple accounts using `vscode.authentication.getSession`. In this case, I'm using the Microsoft provider, and passing `['https://management.azure.com/.default']` for the scopes.
<img width="293" alt="Screenshot 2024-05-30 at 1 50 17 PM" src="https://github.com/microsoft/vscode/assets/12476526/ba2ce610-6181-42ff-95b0-eeec362c6e12">

2. Try to list the different sessions using `await vscode.authentication.getSessions('microsoft', ['https://management.azure.com/.default'])`.

Expect:

Return at least 2 sessions, one for each account

Actual:

Returns only 1 session, for a single account

**Comment by TylerLeonhardt** [comment]
I haven't been able to repro this but Alex's is helping me with steps specific to Azure Resources.

**Comment by TylerLeonhardt** [comment]
A bit of a tricky one to track down... a better repro would probably be:

```ts
// pick account 1
await vscode.authentication.getSession('microsoft', ['https://management.azure.com/.default'], { createIfNone: true, clearSessionPreference: true });
// pick account 2
await vscode.authentication.getSession('microsoft', ['https://management.core.windows.net/.default'], { createIfNone: true, clearSessionPreference: true });

// log this
await vscode.authentication.getSessions('microsoft', ['https://management.azure.com/.default']);
```

Looking at the logic here:

https://github.com/microsoft/vscode/blob/2c626bbdb970cf661d86b22d7c9273312ab01b9a/extensions/microsoft-authentication/src/AADHelper.ts#L245-L276

the behavior makes sense... It gets a single `matchingToken`:

```ts
const matchingTokens = this._tokens.filter(token => token.scope === scopeData.scopeStr);
```

so it skips over the part where it makes a new token for the other account.

The best solution for this is to change the API `getSessions` to something like `getAccounts`. This decouples the scopes from the accounts entirely which is really what we should be doing.

Additionally, to support getting a session for a specific account, you should be able to pass in an account into `getSession` to get a session specific to that account.

**Comment by TylerLeonhardt** [comment]
This issue doesn't really apply anymore with the API change moving to `getAccounts`
