### ISSUE TITLE
Port forwarding protocol switcher does not seem to work

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#213944]
I made HTTPS 'work' for built-in port forwarding in https://github.com/microsoft/vscode/pull/213943, but on macOS:

1. Forward a port
2. Open a context menu and change its protocol to HTTPS
3. 🐛 it doesn't change. `TunnelProvider.provideTunnel` is not called again, and right clicking on it to try to change it again shows it's still HTTP

The protocol is correctly reflected based on what's returned in the Tunnel (HTTP or HTTPS), it just can't be switched.

**Comment by alexr00** [comment]
Looks like there might not be a pre-release version of the Tunnels extension for me to try this with yet.

**Comment by connor4312** [comment]
That PR is the built-in port forwarding extension, but there will not be a published Insiders until after endgame

**Comment by rzhao271** [comment]
@connor4312 what are some verification steps for this issue?
I tried forwarding port 3000 on macOS while there was nothing there and it generated an HTTPS dev tunnels link for me even though the protocol was HTTP.
