### ISSUE TITLE
"Toggle maximized panel" leaves the panel scrolled up

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#21399]
- Have more than a full page of text in the Output panel
- "Toggle maximized panel" to maximize the panel
- Toggle again to de-maximize
- The output should be scrolled to the bottom, but it's scrolled partway up

**Comment by isidorn** [comment]
This is how this feature is designed, it always goes to the previous size.
I believe the current behavior is actually desired thus closing as designed
