### ISSUE TITLE
Git label blinking in Activity Bar (distracts)

### ISSUE THREAD

**Issue by outluch** [Microsoft/vscode#21395]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|lorem-ipsum|Tyriar|1.0.0|
|html-snippets|abusaidm|0.1.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-color|anseki|0.2.3|
|vscode-eslint|dbaeumer|1.2.6|
|tslint|eg2|0.8.1|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|Angular2|johnpapa|2.0.3|
|vue|liuji-jim|0.1.5|
|sublime-keybindings|ms-vscode|1.9.2|
|debugger-for-chrome|msjsdiag|2.5.4|
|stylelint|shinnn|0.23.0|
|JavaScriptSnippets|xabikos|1.4.0|

---

Steps to Reproduce:

1. Open some git repo
2. Code. Sometimes eye will detect something blinking on the left (it is Git uncommitted changes coun label)

**Comment by roblourens** [comment]
The uncommitted changes indicator (the `*`) shouldn't blink. Maybe you're seeing the spinner that shows when a task is running?

**Comment by outluch** [comment]
Definitely disappears for a moment and appears. Not spiner or anything/ Thanks for quick reply, btw

**Comment by roblourens** [comment]
Can you get a screenshot of it so we know exactly what element you're talking about?

**Comment by outluch** [comment]
![app vue - admin 2017-02-25 02-45-55](https://cloud.githubusercontent.com/assets/1479468/23325190/94686c4a-fb04-11e6-88a0-162901de889b.png)

**Comment by roblourens** [comment]
Ok, so you see the blue label disappearing and appearing?

**Comment by outluch** [comment]
Yes. For small moment.
Now I tryed and found, that it blinks every time when I open this Git "tab". For example I go to Explorer, then back to Git and it blinks after about 300-400 ms.
Take a look. I recorded screencast http://take.ms/0H7z9

**Comment by joaomoreno** [comment]
That's the progress badge kicking in. Your repository size & machine specs happen to result in a pretty bad timing for that progress badge to appear: right before it needs to reappear. If you open a bigger repo or try it in a slower machine, you'll see the progress badge show up. In a smaller repo or a faster machine, you won't see the flicker at all.
