### ISSUE TITLE
Allow to move untitled files to other Code windows

### ISSUE THREAD

**Issue by sathyaincampus** [Microsoft/vscode#21390]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.11|
|npm-intellisense|christian-kohler|1.2.1|
|path-intellisense|christian-kohler|1.2.0|
|jshint|dbaeumer|0.10.15|
|vs-code-xml-format|fabianlauer|0.1.4|
|mssql|ms-mssql|0.2.1|
|csharp|ms-vscode|1.6.2|
|java|redhat|0.0.8|

---

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
Probably an issue tracking this but I'm not sure where it is, sorry.

**Comment by sathyaincampus** [comment]
If its tough, there is a work around though. i can simply, select all data, cut and open a new tab in other window an paste it :)

**Comment by bpasero** [comment]
@sathyaincampus you should be able to drag and drop a file to another window, are you saying here specifically it does not work for untitled files or files in general?

**Comment by sathyaincampus** [comment]
Just for untitled

**Comment by bpasero** [comment]
Ok thanks. Untitled are not supported yet.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
