### ISSUE TITLE
git: "the active editor cannot provide timeline information"

### ISSUE THREAD

**Issue by benmkw** [microsoft/vscode#213935]
Type: <b>Bug/ Feature</b>

The timeline view should show the git history of the project/ show all commits, if no file is selected.
Currently only "the active editor cannot provide timeline information" is shown and the commits are only visible when a single file is selected.

This way one could also select different commits/ reorder them etc.

VS Code version: Code - Insiders 1.90.0-insider (fc8762e773c35d4e52e8a7375704af2e24698e5d, 2024-05-29T05:50:53.996Z)
OS version: Darwin arm64 23.5.0

**Comment by gjsjohnmurray** [comment]
Might require https://github.com/microsoft/vscode/issues/94303 which I would also find useful. 

Pinging @lramos15

**Comment by gjsjohnmurray** [comment]
@benmkw does https://github.com/microsoft/vscode/issues/185269 meet your need? It displays in the SCM view rather than the Timeline one, but that might not be a problem for you.

**Comment by benmkw** [comment]
@gjsjohnmurray I'm not sure I can answer that question or understand what this means for the GUI.
Ideally, the timeline view would also support interacting with the commits, such as editing, reordering, and squashing. If the SCM view would support such interactions, this would make it seem more appropriate.

**Comment by lszomoru** [comment]
Closing this issue as the feedback is covered by the "Source Control Graph" view.
