### ISSUE TITLE
Vscode scrolling becomes laggy when using third-party mouse scrolling tools and moving the mouse

### ISSUE THREAD

**Issue by mkdirnow** [microsoft/vscode#213979]
Type: <b>Bug</b>

When using third-party mouse scrolling tools like [Mac Mouse Fix](https://github.com/noah-nuebling/mac-mouse-fix) or [Mos](https://github.com/Caldis/Mos), the scrolling in vscode becomes very laggy. 

VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id a8adbe03-41e8-4770-adb2-5bef5358686c|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.4
todo-tree|Gru|0.0.226
volar|Vue|2.0.19

</details>

**Comment by mkdirnow** [comment]
This is the comparison between vscode and the web version.

https://github.com/microsoft/vscode/assets/17448472/f203b003-bd26-4201-a432-0a66b81e3cd1

**Comment by alexdima** [comment]
@mkdirnow AFAIK we have no special Electron only checks in our mouse handling code. VS Code Stable is now on Chromium 120.0.6099.291, while VS Code Insiders is on 122.0.6261.156 . When you are trying on the web, which version of Chrome are you using? Would it be possible to try out on a similar version as VS Code?

**Comment by mkdirnow** [comment]
@alexdima Thank you for your response. I tried downloading VS Code Insiders, and the issue disappeared. Since I couldn't securely download Chromium 120.0.6099.291, I re-downloaded and reinstalled VS Code Stable, which also resolved the problem. So, the issue was fixed after I reinstalled VS Code Stable. Thanks again!
