### ISSUE TITLE
problem with starting

### ISSUE THREAD

**Issue by gm2317** [microsoft/vscode#214087]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: the last one
- OS Version: what os is?

Steps to Reproduce:

1. I don't know what to do is my first time trying to do something with coding this my first time ever and i can't understand how this thing works I write the code but it dosen't get coloured and it dosen't predict me I was follwing a guide but it dosen't work to me, i don't know where the issue is, please help me
2.

**Comment by bhavyaus** [comment]
I suggest beginning with this series: https://code.visualstudio.com/docs/introvideos/basics. It guides you through the process of configuring VS Code for the programming languages you're interested in developing with.
