### ISSUE TITLE
Typescript intellisense crash

### ISSUE THREAD

**Issue by matthieu-crouzet** [microsoft/vscode#214014]
Type: <b>Bug</b>

Open a project with yarn 2+ configured in PnP 
The intellisense crash 5 times directly
![image](https://github.com/microsoft/vscode/assets/52541061/3bbf623d-f1f8-41fb-8580-edea553105a1)

VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|32.00GB (3.26GB free)|
|Process Argv|--crash-reporter-id 8051ad2a-cdd9-4198-b3e6-689ce3e22398|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.0.0
vscode-zipfs|arc|3.0.0
vscode-eslint|dba|2.4.4
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
codespaces|Git|1.16.22
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.88.1
vscode-scss|mrm|0.10.0
vsliveshare|ms-|1.0.5918
java|red|1.31.0
vscode-xml|red|0.27.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.26.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0
vscode-icons|vsc|12.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31064719
chatpanelc:31048052
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecationcf:31061161
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by IllusionMH** [comment]
AFAIK Yarn 2+ requires patching of TS to support their model.

Have you checked that your yarn version support used TS version and is properly installed?

**Comment by mjbvz** [comment]
This is caused by yarn. Upstream issue which also mentions possible workarounds:  https://github.com/yarnpkg/berry/issues/6270
