### ISSUE TITLE
Integrated terminal in visual studio code is opening externally and not internally

### ISSUE THREAD

**Issue by narasamdya** [microsoft/vscode#214047]
![Screenshot 2024-05-31 174723](https://github.com/microsoft/vscode/assets/40709501/dff508b9-3ef0-4cd4-827f-5b446ec1d7a2)
Type: <b>Bug</b>

Terminal -> New Terminal

None of the following works:
* Reinstall vscode
* Restart windows
* https://stackoverflow.com/questions/58246717/integrated-terminal-in-visual-studio-code-is-opening-externally-and-not-internal
* https://stackoverflow.com/questions/56154957/how-do-i-get-around-the-verified-bug-in-windows-1903-and-launch-the-vscode-integ

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.73GB (38.47GB free)|
|Process Argv|--crash-reporter-id c7c1697c-0ee2-46c4-8216-6c60e417f363|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
dscript|Bui|0.1.204006
copilot|Git|1.197.0
copilot-chat|Git|0.15.2
azure-pipelines|ms-|1.228.0
vscode-azureresourcegroups|ms-|0.9.1
csdevkit|ms-|1.6.8
csharp|ms-|2.31.19
vscode-dotnet-runtime|ms-|2.0.5
vscodeintellicode-csharp|ms-|2.1.11
remote-containers|ms-|0.362.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
azure-account|ms-|0.12.0
cmake-tools|ms-|1.18.41
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
666c4381:31064718
chatpanelc:31048052
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by narasamdya** [comment]
I'm not sure what has changed in VSCode, the workaround that works for me is installing PowerShell 7.

**Comment by deaceves** [comment]
I had the same issue today. And yes, it was resolved installing PowerShell 7

**Comment by jagdishpadeliya** [comment]
I got the same issue after updating the system.

**Comment by kruti-m** [comment]
Multiple users facing the issue since the update. Please check thread [StackOverFlow](https://stackoverflow.com/questions/69047142/visual-studio-code-is-suddenly-defaulting-to-powershell-for-integrated-terminal#:~:text=In%20the%20absence%20of%20both,in%20the%20SHELL%20environment%20variable.)

**Comment by payneio** [comment]
Same problem here. Same solution.

**Comment by saxena26aditya** [comment]
I had the same issue, Thanks for the solution

**Comment by Tyriar** [comment]
I believe in a recent Windows 11 build the default terminal was changed to Windows Terminal. Perhaps that somehow messed with us calling powershell.exe? The only other way I'm aware of this happening is when you set your integrated terminal to open `wt.exe` instead of a shell.

Can anyone who is experiencing this issue still paste in their settings.json file?

**Comment by jagdishpadeliya** [comment]
@Tyriar I can see 3 settings.json file, which one you required?

**Comment by narasamdya** [comment]
@Tyriar , here's my settings.json:

```
{
    "editor.renderWhitespace": "all",
    "omnisharp.useModernNet": true,
    "omnisharp.enableMsBuildLoadProjectsOnDemand": true,
    "editor.inlineSuggest.enabled": true,
    "github.copilot.enable": {
        "*": true,
        "plaintext": false,
        "markdown": false,
        "scminput": false
    },
    "window.zoomLevel": -1,
    "diffEditor.ignoreTrimWhitespace": false,
    "accessibility.signals.sounds.volume": 0,
    "terminal.integrated.automationProfile.windows": {}
}
```

**Comment by narasamdya** [comment]
Does this happen to only MSFT? If it does, it could be related to ICM 508973319.

**Comment by meganrogge** [comment]
Closing as I cannot repro
