### ISSUE TITLE
Creating a comment doc block

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#2140]
Is there anything that will allow for shorthand creation of documentation?

So for example, in C# if I type:

`///` and press <kbd>Enter</kbd>

It would create a doc comment block

    /// <summary>
    ///     Summary of my item
    /// </summary>

It would add things such as:

* Summary
* Parameters
* Return
* Etc.

**Comment by Tyriar** [comment]
I believe you could do this with an extension

**Comment by weinand** [comment]
@TheColorRed did you try snippets? https://code.visualstudio.com/docs/customization/userdefinedsnippets

**Comment by TheColorRed** [comment]
I did do snippets as a final, but you can't have a snippet of `///` so I had to use text instead. However, it would be nice if either: 

* The editor picked up that `///` was a saved snippet
* That this doc feature was built into the editor

**Comment by alexandrudima** [comment]
@TheColorRed Would you expect that typing `///` prepopulates the contents in the doc comment with the parameters and return type of the current method?

cc @jrieken : would be a nice rich language feature

**Comment by jrieken** [comment]
The omnisharp extension should handle that

**Comment by TheColorRed** [comment]
@alexandrudima Yeah, that is what I was thinking would happen. It would also be nice if it was supported in other languages as well.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#20
