### ISSUE TITLE
BUG: VSCode doesn't remember the custom profile I selected with right-click "Open with Code"

### ISSUE THREAD

**Issue by codewizard13** [microsoft/vscode#214019]
Type: <b>Bug</b>

1. Right-click any folder on Windows
2. Select "Open with Code"
3. Code launches
4. Click lower left gear icon > Profiles
5. Select a custom profile (not the default)
6. Create a simple text file in the folder (maybe VSCode requires at least some CRUD activity to record new settings?)
7. Close VSCode
8. Right-click the same folder and select "Open with Code"
9. Observed that you are opened into the profile named "default" instead of the one you chose last

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

### Challenges with Ambiguous Terminology

I perceive there may be a problem using the term "default" among the dev team. Perhaps there is confusion over what is meant by "default" in the ticketing system among the developers on VSCode and that makes it hard to even pose an understandable question. What do I mean?

Well, some devs may hear "**default profile**" and think that means "**the included core profile used if no custom profiles have been created or selected**". But, other devs will think it means "**the profile that VSCode always boots into, no matter what**", as in, when I right-click and choose "Open with Code" from the context menu, or open VSCode any other way, it should boot into this profile by default.

Clearly, these are two different meanings of "default" and I suspect devs are conflating the two. The last meaning is the least desirable and least user-friendly.

Perhaps a different term besides default should be used in the UI and internal ticketing system? Here is one possibility:

* **base profile**: The profile included with core that VSCode boots into if no custom profiles have been created
* **default profile**: The profile the user has chosen to boot into by default. Can be the base profile or any custom profile. VSCode will remember this setting an always boot into this profile until the user changes the setting

I suspect this what many users think when they see the "default profile" option.

---

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900H (20 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.69GB (37.76GB free)|
|Process Argv|C:\\Users\\erich\\Local Sites\\locdev-es-prod\\app\\public\\wp-content\\themes\\elsm-astra-child --crash-reporter-id 43dd3826-4447-4fbe-a62b-fbe94f5c6766|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
ACF-Snippet|ant|1.9.0
markdown-emoji|bie|0.3.0
markdown-preview-github-styles|bie|2.0.4
vscode-intelephense-client|bme|1.10.4
xml2json|bui|1.2.5
vscode-markdownlint|Dav|0.55.0
composer-php-vscode|DEV|1.47.15512
phptools-vscode|DEV|1.47.15512
profiler-php-vscode|DEV|1.47.15512
xml|Dot|2.5.1
prettier-vscode|esb|10.4.0
figma-vscode-extension|fig|0.3.5
vscode-github-actions|git|0.26.2
live-sass|gle|6.1.2
markdown-extended|jeb|1.1.4
vscode-wordpress-hooks|joh|1.3.0
elementor-snippets|lau|0.2.2
rss|luy|0.10.4
markdown-converter|man|5.2.1
rainbow-csv|mec|3.12.0
vscode-language-babel|mgm|0.0.40
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.362.0
remote-wsl|ms-|0.88.2
powershell|ms-|2024.2.2
sqltools|mtx|0.28.3
sqltools-driver-mysql|mtx|0.6.2
vscode-rapidapi-client|Rap|1.10.2
vscode-services|rap|1.0.2
perl|ric|2.6.2
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.9
markdown-snippets|rob|0.9.1
snippets-ranger|rob|1.8.0
es7-react-js-snippets|rod|1.9.3
gitmoji-vscode|sea|1.2.5
lua|sum|3.9.1
pdf|tom|1.2.2
wordpress-toolbox|wor|1.3.15
php-debug|xde|1.34.0
php-pack|xde|1.0.3
five-server|yan|0.3.1
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
showvideot:31016892
chatpanelc:31048052
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31049070
a69g1124:31058053
dvdeprecation:31052039
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by gjsjohnmurray** [comment]
You may like this, which is available in Insiders and will arrive generally when 1.90 ships toward the end of next week.

https://github.com/microsoft/vscode/issues/181677#issuecomment-2133827707

**Comment by AWenmanFK** [comment]
hey again @gjsjohnmurray, I noticed that the mentioned function here was working after one of the recent updates(I believe after the 1.9 like you said), but it seems to be gone/broken again. Selecting an imported custom profile does not stick when closing and reopening the app.

**Comment by gjsjohnmurray** [comment]
What value did you pick for the setting described in https://code.visualstudio.com/updates/v1_90#_configure-custom-profile-for-new-window?

**Comment by sandy081** [comment]
> Right-click the same folder and select "Open with Code"

Does this happen only when you open the folder in above way? Or also when you open the folder from VS Code?

**Comment by AWenmanFK** [comment]
yep I definitely missed that... (-_-"). Everything's working perfectly now, thanks again @gjsjohnmurray !!

**Comment by codewizard13** [comment]
Sorry, it's been a busy month! I just caught this - I'm testing whether the window.newWindowProfile sticks correctly. I will make a note to report back next week! :)

**Comment by codewizard13** [comment]
Confirming: This works! :) Thanks!
