### ISSUE TITLE
Test message peek is too large for contents

### ISSUE THREAD

**Issue by plemarquand** [microsoft/vscode#214011]
If a `TestMessage`'s message is only a single line it can be show entirely in the header of the Message UI. The body UI can be omitted.

Currently VSCode shows the same text twice, and the height of the TestMessage UI is larger than it needs to be.

Screenshot:

<img width="932" alt="Screenshot 2024-05-31 at 9 30 31 AM" src="https://github.com/microsoft/vscode/assets/667875/7f9fc230-25c0-4258-890f-0c8e8020a56d">

**Comment by eleanorjboyd** [comment]
is there any way to test this without swift?

**Comment by connor4312** [comment]
Any test message should do. The peek should not expand significantly beyond the height of the message contents (unless the run history is toggled on on the right, then the height is uncapped)
