### ISSUE TITLE
bug: If logOutputChannel is created again after being disposed, it will disappear

### ISSUE THREAD

**Issue by xiyaowong** [microsoft/vscode#214048]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.90.0-insider
Commit: ca688da9fb6dad00996cee7d5342490daa7bb1fb
Date: 2024-05-31T01:05:41.342Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.90.0-insider Chrome/122.0.6261.156 Electron/29.4.0 Safari/537.36

Steps to Reproduce:

`extension.js`

```ts
import { window } from 'vscode'

export function activate() {
  const log = window.createOutputChannel('test-log-channel', { log: true })
  setTimeout(() => {
    log.dispose()
    window.createOutputChannel('test-log-channel', { log: true })
  }, 1000)
}
```

There is no test-log-channel in the output panel.

**Comment by c3danielxu** [comment]
Thanks for reporting this @xiyaowong, I have the exact same issue. In the meantime I have a workaround:

```js
import { window } from 'vscode'

export function activate() {
  const log = window.createOutputChannel('test-log-channel', { log: true })
  setTimeout(() => {
    // log.dispose()
    window.createOutputChannel('test-log-channel', { log: true })
    window.createOutputChannel('test-log-channel', { log: true })
  }, 1000)
}
```
I was surprised this does not throw, usually if you create something that was not previously disposed, it will throw an error like "command was already registered" or "notebook controller already exists". I am currently commenting out my `dispose()` line in my extension. It's not ideal though.

**Comment by jeanp413** [comment]
PR fixing it https://github.com/microsoft/vscode/pull/225709
