### ISSUE TITLE
floating window notebook is not rendered correctly after reload

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#214020]
1. Create a notebook
2. drag it out of the main window
3. reload the window
:bug:
![image](https://github.com/microsoft/vscode/assets/2019016/15bc7d75-808b-4584-8138-beac4033fd77)

**Comment by amunger** [comment]
@bpasero - this seems like a race condition on when `EditorPane.layout` is called, which comes from the editorService. Any idea about adjusting the order of when this is called. 

One notable difference is that the widget's layout function is called 4 times when the window is detached, but "only" twice when the window is reloaded (both when in aux and main window)

**Comment by bpasero** [comment]
@amunger is it maybe that styles have not yet loaded while you attempt to layout? I know Connor was hitting a similar issue and added a `ILayoutService.whenContainerStylesLoaded`, maybe that helps here?

https://github.com/microsoft/vscode/blob/fca05df7d4a9ce627919af8cd9fc3a3f2e14e029/src/vs/platform/layout/browser/layoutService.ts#L94
