### ISSUE TITLE
perf: notebook serialization for large notebooks blocks cell execution

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#214040]
Steps to Reproduce:

1. enable auto-save
2. create a large notebook: run the code below in a cell to create a chart with a lot of data and copy that cell ~50 times
3. save to disk
4. create another cell with just `print(1)` and run it a few times
:bug: sometimes cell execution takes several seconds

serialization still blocks the extension host for the entire time, which means execution cannot happen

code for large outputs:
```
import plotly.express as px
import random
x = []
y = []
for i in range(100000):
    random_number = random.randint(1, 10000)
    x.append(i + random_number)
    y.append(i + random_number)
fig = px.scatter(x, y)

fig.show()
```

**Comment by arman258** [comment]
@amunger coming from https://github.com/microsoft/vscode/issues/211154, I think this copilot has something to do with this issue. Take a look at the videos below; I just started working on another .ipynb file, not even 2 cells with about 20-30 lines of codes, the slowness started. You can clearly see the copilot trying to do something and lagging the jupyter to show the output. 

I also face the same issue with another AI code completion called Codeium. The behavior is the same. Disabling them seems to handle the jupyter files better, but as the file starts to get complicated, it gets slow again. 

[ms-toolsai.jupyter-unresponsive.cpuprofile.txt](https://github.com/user-attachments/files/15570562/ms-toolsai.jupyter-unresponsive.cpuprofile.txt)

![image](https://github.com/microsoft/vscode/assets/8408861/1c9d1b60-e38a-4f35-b328-bb1a7cff47a6)

https://github.com/microsoft/vscode/assets/8408861/abf37f4f-34dd-4698-87a5-11f4b539681c

https://github.com/microsoft/vscode/assets/8408861/08eb734e-6262-4ed3-b9f2-72d43880b463

**Comment by amunger** [comment]
@arman258 I created another issue for that since it doesn't have anything to do with serializing large notebooks.

**Comment by nojaf** [comment]
Hi @amunger, we are are facing this issue as well and are interested in helping out.
I've pushed my sample project to https://github.com/nojaf/python-notebook-serialization, I can reproduce this in WSL and Windows directly.

When I open my debug VSCode instance, I can't really mimic the exact behaviour as I'm missing some extensions in that instance:

![image](https://github.com/user-attachments/assets/1a936177-9ed5-4be7-a061-abf26c98c5e8)

Is it possible to install extensions in the local VSCode instance? Does that require something special?

In my code, I added some more logs to view some timings:

![image](https://github.com/user-attachments/assets/02e7891d-fb15-42f6-98d9-5cdde58c0be8)

![image](https://github.com/user-attachments/assets/881c613c-5ca8-4b2e-8d8b-a8225a76cd26)

Although I suspect the problem is worse when the actually graphs are rendered.

Any pointers on what might be interesting to investigate next?

**Comment by amunger** [comment]
@nojaf - yes, you can download the necessary extension vsix from the marketplace website and just use "install from visx" in the extensions sidebar menu.

I don't think it actually needs to display though, the performance hit is all within the serialization of the data, which is there whether or not it displays

**Comment by nojaf** [comment]
@amunger thanks for the pointer.

Thinking out loud, would `JSON.stringify(sorted)` (without indentation) be an option to speed up the serialization?
Locally that turns `499.814ms` into `193.844ms` for me.

**Comment by amunger** [comment]
If it makes that much of a difference, then it's worth considering, but it would cause a lot of headaches for people that are using version control for their notebooks as all the whitespace would suddenly change. We would probably need it behind a setting if we went that direction.

**Comment by nojaf** [comment]
@amunger, I'm considering adding a separate timeout setting for `files.autoSaveDelay`. By increasing this to, say, 1 minute, the serialization process wouldn't interfere with cell execution. For users with large notebooks, being able to configure this might be a practical workaround. What do you think?

**Comment by amunger** [comment]
Do you mean a setting that is specific to notebooks? `files.autoSaveDelay` already exists and could be used for this purpose, but it would affect all files.

**Comment by nojaf** [comment]
> Do you mean a setting that is specific to notebooks? files.autoSaveDelay already exists and could be used for this purpose, but it would affect all files.

Yes, exactly.

**Comment by nojaf** [comment]
@amunger, I hate to trouble you again, but is this additional setting worth pursuing? I'm ready to proceed with a PR, but I'd appreciate some confirmation that it's a reasonable addition.

**Comment by nojaf** [comment]
@amunger, ok that sounds fair. Any other avenues to explore here? This is really a problem at our company and we actively want to contribute to fixing this.

**Comment by nojaf** [comment]
I'm trying something behind a feature flag in https://github.com/microsoft/vscode/pull/226632

**Comment by amunger** [comment]
I tested the latest with https://github.com/microsoft/vscode/pull/226632 and the latency is greatly improved. Thanks for getting that change going @nojaf 

Use the setting `"ipynb.experimental.serialization": true` to free up the extension host for execution.
