### ISSUE TITLE
Select a debug configuration

### ISSUE THREAD

**Issue by doaneric** [microsoft/vscode#214085]
I recently downloaded msys64 for coding C++ (I'm a beginner), and I have done everything in https://code.visualstudio.com/docs/cpp/config-mingw but there's an issue: when I run my code, it keeps asking me to choose the configuration, and both the c++.exe and g++.exe work. I want it to stop asking for the configuration.
![issue](https://github.com/microsoft/vscode/assets/138102605/ea575f2f-5a3f-4381-b7c2-05eaf8ef3eda)

**Comment by roblourens** [comment]
Please file an issue on the C++ debug extension, thanks

**Comment by Abuzaher1** [comment]
How did you fix that?
