### ISSUE TITLE
JS/TS syntax highlighting breaks with regex `v` mode and `?` character

### ISSUE THREAD

**Issue by mikestopcontinues** [microsoft/vscode#214090]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: OSX 14.5

Steps to Reproduce:

Syntax highlighting breaks in (at least) three ways:

- Named capture groups: `/(?<name>http)/v`
- Greedy quantifier: `/https?/v`

Here's small demos. It breaks much worse than shown...

![CleanShot 2024-06-02 at 14 45 45@2x](https://github.com/microsoft/vscode/assets/150434/b4b2e3bd-b4b6-449e-b5ed-fe7048327b91)

![CleanShot 2024-06-02 at 14 45 58@2x](https://github.com/microsoft/vscode/assets/150434/df71a37c-440f-435e-b4b6-bf4adfaa076f)

**Comment by RedCMD** [comment]
https://github.com/microsoft/TypeScript-TmLanguage/issues/1021
https://github.com/microsoft/TypeScript-TmLanguage/issues/1006
