### ISSUE TITLE
Command Palette sorting: irrelevant command show up higher

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#214034]
<img width="1136" alt="image" src="https://github.com/microsoft/vscode/assets/876920/81e7da30-18ca-47ab-9540-053a6fe01cc4">

While in a text editor, I attempt to search for "Toggle Word Wrap". After typing "Toggle W", I expect "Toggle Word Wrap" to show up as the first one. However the terminal one shows up first. This is a very bad sorting as I don't have either terminal open, not even the terminal find widget.

For this case in particular, we could add a `when`/`precondition` to the terminal command, however there are two things we can improve:

- We need to have some tests for builtin command sorting. It can be frustrating that the introduction of a new command broke my muscle memory. 
- Command sorting can take context into account.
- Lastly, "Toggle Word Wrap" should properly always have higher priority than "Toggle balabala Whole Word" for "Toggle W"

**Comment by rebornix** [comment]
Another case 

<img width="690" alt="image" src="https://github.com/microsoft/vscode/assets/876920/412e2cc9-9cd3-4833-9aa8-c5804f554abd">

**Comment by rebornix** [comment]
I'm a bit surprised now terminal command often shows up before editor or view

<img width="662" alt="image" src="https://github.com/microsoft/vscode/assets/876920/1fe11511-b752-4876-a144-e75d97f71e4d">

<img width="672" alt="image" src="https://github.com/microsoft/vscode/assets/876920/9e352092-df24-4ebf-ac5b-2d96f2d1ff94">

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/173767

> we have always sorted matching commands by alphabet to try to group related entries together that share the same prefix and keep the order predictable. We have intentionally not added fuzzy search ranking to commands.
