### ISSUE TITLE
I'am sorry about that bug of extensions

### ISSUE THREAD

**Issue by Jabinzou** [Microsoft/vscode#21408]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions:1.9.1

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.download the extensions maybe happened somgthing wrong,it tells me that "unable to verify the first certificate"
2. my first version is not like that happened,although i have tried for many times.do you have some suggestion?  Thank you!

**Comment by joaomoreno** [comment]
Can you help us in  #18103  ?

**Comment by Jabinzou** [comment]
thank you anymore,i have resoleved this.like that:
![qq 20170301103233](https://cloud.githubusercontent.com/assets/14176629/23443548/6c3766fe-fe6a-11e6-9495-b5a5b29d05b5.png)
the value default is false, i have changed it.
