### ISSUE TITLE
Random lines of code appear at top when scrolling

### ISSUE THREAD

**Issue by MikeRich88** [microsoft/vscode#214045]
Type: <b>Bug</b>

Open any file and scroll. Please see the picture.

![image](https://github.com/microsoft/vscode/assets/7113073/7c7a26b1-c158-4796-9809-391e801caf19)

VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin x64 22.6.0
Modes:
Remote OS version: Linux x64 5.14.0-284.30.1.el9_2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (10.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: (redacted)|
|OS|Linux x64 5.14.0-284.30.1.el9_2.x86_64|
|CPUs|DO-Regular (1 x 2294)|
|Memory (System)|1.72GB (0.50GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
composer-php-vscode|DEV|1.47.15512
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.47.15512
profiler-php-vscode|DEV|1.47.15512
php-debug|xde|1.34.0

</details>

**Comment by MikeRich88** [comment]
It appears to be related to a feature called "Sticky Scroll".

Can someone explain to me how that is useful in ANY sense whatsoever?

It literally causes completely random lines to appear at the top of the file.

Stop turning on features that are useless and stop involuntarily updating the program with more bugs.

**Comment by IllusionMH** [comment]
It shows nested context pretty well in TS (class, method name/signature, conditions, loops etc.), so you don't have to scroll up to lookup it yourself.

Not sure how good it works in PHP though and if extension should provide hints for better sticky scroll (as built-in support is limited for PHP).

**Comment by ihssmaheel-dev** [comment]
It's pretty useful

**Comment by aiday-mar** [comment]
Hi yes this feature is called `sticky scroll`. You can enable/disable it from the settings with the following setting `editor.stickyScroll.enabled`. This issue will be closed.
