### ISSUE TITLE
Cannot change default terminal profile

### ISSUE THREAD

**Issue by TaikoG** [microsoft/vscode#214064]
Type: <b>Bug</b>

Command Promt is stuck on default

1. Select `>Terminal: Select Default Profile` in command palette.
2. Select any profile (in my case PowerShell)

or:

1. Select `>Preferences: Open User Settings (JSON)` in command palette
2. add
```
"terminal.integrated.defaultProfile.windows": "PowerShell",
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        }
    }

```
to JSON.

Both do not affect Command Promt being the default.

Disabling extensions does not affect this problem.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 7500F 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (25.86GB free)|
|Process Argv|--crash-reporter-id cb110e85-ba0f-4b02-81c1-4cdb0048e026|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.1.4
better-comments|aar|3.0.2
codesnap|adp|1.3.4
Doxygen|bbe|1.0.0
pythoncpp-debug|ben|0.3.0
ruff|cha|2024.24.0
cmake-format|che|0.6.11
path-intellisense|chr|2.8.5
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.55.0
pyinit|Dio|0.0.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
c-cpp-runner|fra|9.4.8
vscode-c-cpp-config|fra|6.1.0
vscode-c-cpp-dev-extension-pack|fra|0.10.0
vscode-coding-tools-extension-pack|fra|0.8.0
vscode-cpython-extension-pack|fra|0.1.0
vscode-python-config|fra|11.16.0
vscode-python-dev-extension-pack|fra|2.0.0
workspace-formatter|fra|1.1.0
better-cpp-syntax|jef|1.17.2
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
mypy-type-checker|ms-|2023.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.362.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
cmake-tools|ms-|1.18.41
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
open-html-in-browser|pea|2.1.10
vscode-yaml|red|1.14.0
partial-diff|ryu|1.4.3
even-better-toml|tam|0.19.2
cython|tcw|0.1.0
pdf|tom|1.2.2
cmake|twx|0.0.17
errorlens|use|3.18.0
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-svg-previewer|vit|0.7.0
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
666c4381:31064718
chatpanelt:31048053
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecationcf:31061161
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by Tyriar** [comment]
Could you get a trace log when you open the terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by TaikoG** [comment]
[terminal_trace.log](https://github.com/user-attachments/files/15568528/terminal_trace.log)
