### ISSUE TITLE
Updated to version 1.9.1 and i can no longer set breakpoints by clicking on the leftsidebar of the code

### ISSUE THREAD

**Issue by joshiamey** [Microsoft/vscode#21409]
i use vscode for python dev, in earlier versions i was able to set breakpoints by clicking on the left editor bar , but in this version i dont see the bar at all to set the break point.

please suggest how can i set breakpoints now.

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|python|donjayamanne|0.5.8|
|Theme-dimmed-monokai|gerane|0.0.2|
|Theme-Flatgrammer|gerane|0.0.2|
|Theme-FlatlandDark|gerane|0.0.2|
|Theme-FlatlandMonokai|gerane|0.0.4|
|Theme-Monokai-Aurora|gerane|0.0.2|
|Theme-MarkdownKit|ms-vscode|0.1.1|

---

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
Do you have `"editor.glyphMargin": false` set?

**Comment by joshiamey** [comment]
Thank you @roblourens  , it was set to false , dont know how that happened, setting it to true worked
