### ISSUE TITLE
fontLigatures not work after install Chinese (Simplified) Language Pack for VS Code

### ISSUE THREAD

**Issue by LePtC** [microsoft/vscode#214030]
Tested on vscode 1.87.2 and 1.89.0, windows 10:

Ligature works fine before install Chinese (Simplified) Language Pack:

![image](https://github.com/microsoft/vscode-loc/assets/6371171/74d4194b-020c-4cdd-972c-310647849aaa)

after install Chinese (Simplified) Language Pack:

![image](https://github.com/microsoft/vscode-loc/assets/6371171/5fccd110-9cd9-42f2-a3f8-976efed3ebb7)

Ligature works again if I type some chinese characters before the operator, this is so weird and I have no idea why:

![image](https://github.com/microsoft/vscode-loc/assets/6371171/46e10413-5577-45b9-97bb-30e4e2432462)

**Comment by LePtC** [comment]
@TylerLeonhardt thank you for the update!

1. settings:

```json
{
    "editor.fontFamily": "'Sarasa Mono SC', Inconsolata, Consolas, 'Droid Sans Mono', Monaco, 'Courier New', monospace, 'Droid Sans Fallback'",
    "editor.fontLigatures": true,
    "editor.fontSize": 16,
    "editor.minimap.enabled": false,
    "editor.guides.bracketPairs": true,
}
```

installation: just unzip `VSCode-win32-x64-1.89.0.zip` to `C:\Users\Administrator\Downloads\program\VSCode` and run `Code.exe`
(with font `sarasa-mono-sc` already installed on the system)

attached is a gif of this issue:

![VScode FontLigature_2024_06_05_22_06_34_961](https://github.com/microsoft/vscode/assets/6371171/95be604e-f88f-4818-851e-a1943430adcb)

2. VScode is reloaded many times and the issue persists.

3. this issue does not appear for French or German langpack:

![image](https://github.com/microsoft/vscode/assets/6371171/d74795c2-e6a8-4b2b-a6a8-a154dacd465f)

it appears when zh-CN, zh-TW, Japan or Korean langpack installed:

![image](https://github.com/microsoft/vscode/assets/6371171/418c5c08-206b-4af6-899c-7ef3f3061b90)

**Comment by TylerLeonhardt** [comment]
One more question: does this repro if you use a different font family? Like the default value of the setting?

**Comment by LePtC** [comment]
I simplified the settings and the issue is the same

![image](https://github.com/microsoft/vscode/assets/6371171/824c81e3-a3b3-4225-b5d9-7ed3086e6fc4)

![image](https://github.com/microsoft/vscode/assets/6371171/f9b507bf-5220-4b28-96b2-541fe29eefe0)

**Comment by TylerLeonhardt** [comment]
@LePtC I don't have this `Saris Mono SC` font.
1. Does it repro without this font?
2. Where could I get this font to try it out?
