### ISSUE TITLE
Toggle 

### ISSUE THREAD

**Issue by khantm02** [microsoft/vscode#214091]
Type: <b>Feature Request</b>

Is there a way to expand all toggles / folders at once ? There is an icon for collapsing all folders.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode/issues/88682
