### ISSUE TITLE
problem in print

### ISSUE THREAD

**Issue by Madiharshad** [microsoft/vscode#214196]
Type: <b>Bug</b>

Visual Studio Code is not printing the value of a variable, but rather the name of the variable itself. 

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
smart-title-case|awt|0.5.0
vscode-eslint|dba|2.4.4
gitlens|eam|15.0.4
vscode-firefox-debug|fir|2.9.10
copilot|Git|1.198.0
copilot-chat|Git|0.15.2
vscode-docker|ms-|1.29.1
vscode-edge-devtools|ms-|2.1.5
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
cpptools|ms-|1.20.5
vscode-typescript-next|ms-|5.5.20240505
java|red|1.31.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31049070
a69g1124:31058053
dvdeprecationcf:31052040
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by ihssmaheel-dev** [comment]
Hi harshad, I need assistance with capturing the details of the extensions, specifically the summary. Should I manually write it down in markdown, or is there an alternative method I can use?
