### ISSUE TITLE
VS Code as LaTeX Editor jumps when right-clicking file for deletion

### ISSUE THREAD

**Issue by ccomploj** [microsoft/vscode#214111]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.89.1
- OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. click on some .tex file inside your folder
2. after clicking (and opening that file), right click on that file (same location where you clicked before), and try to delete the file or else
3. the highlighted file suddenly jumps to the main document / compiler or PDF 

![image](https://github.com/microsoft/vscode/assets/61836848/4d4aea86-b244-4080-8737-fa08c7b49f42) (overview)
![image](https://github.com/microsoft/vscode/assets/61836848/fa72809e-c7fa-4a0c-85b7-20c840eda7f4) (click/highlight file)
![image](https://github.com/microsoft/vscode/assets/61836848/59bc88a3-6067-469d-a47c-39eba9c707ca) (suddenly jumps after right-click)

**Comment by rzhao271** [comment]
That looks like a massive jump. If the jump was only by a single file, I'd ask whether it was because of the Open Editors viewlet.
Does the problem still occur on VS Code 1.96 or later? If yes, does the problem still occur when all extensions are disabled?

**Comment by ccomploj** [comment]
This is from a long time ago. I cannot reproduce the error anymore. I suppose it was resolved by v1.96 (my version).
