### ISSUE TITLE
Display icons in Git explorer too

### ISSUE THREAD

**Issue by zabel-xyz** [Microsoft/vscode#21412]
- VSCode Version: 1.9.1
- OS Version: Windows 10

Could you display icons also in Git explorer ?
(This can be useful when the filename is the same, and only the extension changes)

![image](https://cloud.githubusercontent.com/assets/16486407/23329516/82429438-fb3a-11e6-8797-ed88cd254b2a.png)

**Comment by roblourens** [comment]
The new SCM experience does have file icons. From the command palette, run "Enable Preview SCM"
