### ISSUE TITLE
Terminal tabs are not restored in another window after closing it and opening again

### ISSUE THREAD

**Issue by adrianbienias** [microsoft/vscode#214183]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: Ubuntu 22.04.4

Steps to Reproduce:

1. Open two or more VSCode windows with different projects
2. Open multiple tabs in terminal in one of those projects, and run some commands in those tabs
3. Close that project window with close window command or choosing menu - file - close window or the given shortcut
4. Reopen the closed project, choosing menu - file - open recent
5. Observe that only the one initial terminal tab is open, the rest of terminal tabs have gone

This issue is present only when one of the multiple VSCode project windows is closed with close window option.
When e.g. the whole VSCode app is exited (all opened windows are closed at once) by choosing menu - file - exit (or the given shortcut), then after reopening the VSCode, all project windows are restored properly with all terminal tabs.

**Comment by meganrogge** [comment]
I cannot reproduce - what do you have for the value of `terminal.integrated.persistentSessionReviveProcess`
