### ISSUE TITLE
vscode "phones home" upon startup with updates and telemetry disabled

### ISSUE THREAD

**Issue by eugene** [Microsoft/vscode#21418]
I've noticed that vscode (both the normal and insiders versions) tries to connect to ```ms-vscode.gallery.vsassets.io``` (and sometimes other marketplace related domains) upon every startup even with update channel and telemetry disabled. 

This only affects versions packaged by Microsoft - a locally built "Code - OSS" does not have this issue. 

Related config parameters: 
```
"telemetry.enableCrashReporter": false,
"telemetry.enableTelemetry": false,
"update.channel": "none"
```
- VSCode Version: 1.9.1, 1.10.0
- OS Version: macOS any version

Steps to Reproduce:

1. Start vscode non OSS version

**Comment by bpasero** [comment]
@eugene does this happen even when you are not opening the extensions viewlet? I wonder if this is just us trying to load the images for extensions you have installed.

**Comment by roblourens** [comment]
Or checking for extension updates?

**Comment by eugene** [comment]
@bpasero @roblourens yeps it happens even when i do not open extension viewlet. Additionally i've disabled automatic extensions updates.

**Comment by joaomoreno** [comment]
You can disable automatic extension updates, but the check for updates will always happen, if you have any extension installed.

**Comment by eugene** [comment]
@joaomoreno Nope, it happens even with no extensions installed.

**Comment by joaomoreno** [comment]
OK. Can you be specific? What network access do you notice?
