### ISSUE TITLE
Make Icons Visible again

### ISSUE THREAD

**Issue by jifoxpa** [microsoft/vscode#214134]
Type: <b>Bug</b>

Open vscode

The Icons on top right window header for "Toggle Primary Sidebar", "Toggle Panel", "Toggle Secondary Side Bar" and "Customize Layout" is not displayed anymore.

I was not able to find any hint on how to set this icons to visible again.

Where is this documented?

Josef

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 5.15.0-105-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6354 CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (7.22GB free)|
|Process Argv|--crash-reporter-id fc2df906-66e9-496c-821c-b1a32946d1ec|
|Screen Reader|no|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: scvbnetauto02|
|OS|Linux x64 5.15.0-105-generic|
|CPUs|Intel(R) Xeon(R) Gold 6354 CPU @ 3.00GHz (4 x 2992)|
|Memory (System)|15.61GB (7.12GB free)|
|VM|15%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
ansible-vault|dho|0.1.3
copilot|Git|1.197.0
copilot-chat|Git|0.15.2
gitlab-workflow|Git|4.14.0
todo-tree|Gru|0.0.226
gitlab-mr|jas|1.4.3
rainbow-csv|mec|3.12.0
vscode-docker|ms-|1.29.1
vscode-language-pack-de|MS-|1.89.2024050109
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.6.0
flake8|ms-|2023.10.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
autodocstring|njp|0.6.1
ansible|red|24.5.2
vscode-yaml|red|1.14.0
jinjahtml|sam|0.20.0
unique-window-colors|stu|1.0.51
graphviz-interactive-preview|tin|0.3.5
numbered-bookmarks|ale|8.4.0
TextFSM-Syntax|and|1.1.0
django-html|bib|1.3.0
django|big|1.0.2
vscode-firefox-debug|fir|2.9.10
vscode-drawio|hed|1.6.6
vscode-edge-devtools|ms-|2.1.5
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.362.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
vscode-speech|ms-|0.8.0
vscode-speech-language-pack-de-de|ms-|0.4.0
debugger-for-edge|msj|1.0.15
jinja|who|0.0.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31064719
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by gjsjohnmurray** [comment]
If you right-click on the titlebar do you get a Layout Controls option to check?

**Comment by jifoxpa** [comment]
Hi John,

Thanks for this quick response.
Click on Titelbar:  ***@***.***


Click on "...":
***@***.***



Von: John Murray ***@***.***>
Gesendet: Montag, 3. Juni 2024 13:38
An: microsoft/vscode ***@***.***>
Cc: Fuchs Josef ***@***.***>; Author ***@***.***>
Betreff: [EXT] Re: [microsoft/vscode] Make Icons Visible again (Issue #214134)

EXTERNAL: This sender is from outside the organisation. If you do not know the sender or cannot verify the integrity of the message, please do not respond or click on links in the message and report the message directly to our IT Support Team.


If you right-click on the titlebar do you get a Layout Controls option to check?

-

**Comment by lanceturbes** [comment]
Also seeing this same behavior on Linux (latest Fedora Workstation, VS Code version 1.90.2). 

Only happens when the tab bar is hidden. VS Code's title bar only seems to want to show either editor actions OR layout controls, but not both at the same time. Bug does _not_ occur VS Code on Mac for me, though.

If you hide "editor actions" via `"workbench.editor.editorActionsLocation": "hidden"`, you can see the layout control icons again, even with the tab bar hidden (at the obvious expense of not being able to see the editor action icons).

**Comment by benibenj** [comment]
We decided to move the layout controls into the overflow menu when the editor actions are in the title bar. We did this because otherwise there would be to many actions showing. Would you prefer seeing both the editor actions and the layout actions at the same time? 

Depending on the type of editor you have open, there might be many editor actions (around 7 when using the diff editor). If you then also show the layout actions, you easily reach >10 actions. The title bar allows to show max 9 items, so some items will be hidden...

**Comment by benibenj** [comment]
Closing as desgined
