### ISSUE TITLE
Add file by Nemo，VSCode was died.

### ISSUE THREAD

**Issue by zhqiyi** [Microsoft/vscode#2141]
System: Ubuntu 14.04 LTS

I Copy a file to the folder what was opened by VSCode, VSCode was died

**Comment by weinand** [comment]
@zhqiyi is this reproducible? If yes, please provide the steps so that we can reproduce the problem (and try to fix it).

**Comment by zhqiyi** [comment]
@weinand  Thanks reply. Yes, it's reproducible.
1. A is a folder that was opened by VSCode 
2. Then, I copy a file to A by Nemo(1.8.4)
3. Switch to VSCode, it was died(suspended animation
)

**Comment by bpasero** [comment]
@zhqiyi can you attach a screenshot?
