### ISSUE TITLE
Feature Request: OpenTextDocument with content

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#21413]
#12283 added an api overload to open a new, untitled text document with an optional language mode.

It would be great if this could be augmented to accept content.

Use case: I have an extension that ships with examples. Currently I have to do one of the following:

- Open the "source" file directly which would allow users to clobber it
- Copy the file to a temp file and open that and then remember to clean it up. Users would still have to "save as" to save it in a location that is useful to them
- Use the new overload to open an untitled, empty text document and then use an edit to populate the contents.

The last one is the most viable but seems unnecessary. I would like to see `openTextDocument(options?: {language: id, content: text})` so I could do something like 

```
openTextDocument(exampleUri).then(exampleDocument => { const exampleText = exampleDocument.getText(); openTextDocument({language: LANG_ID, content: exampleText})
```

**Comment by bpasero** [comment]
@hoovercj why are steps 1 and 2 needed if all you need is the content of a file?

**Comment by hoovercj** [comment]
Sorry @bpasero for the poorly worded issue, I've updated it to clarify that those were 3 distinct options.

**Comment by bpasero** [comment]
@hoovercj nothing prevents you from opening an untitled file and then setting the content, right?

**Comment by hoovercj** [comment]
@bpasero I didn't see a way to set the content without doing an insert textedit which would allow the user to `undo` the text which goes against the spirit of the "open example" command that I've exposed and the "open untitled document with content" that I've  proposed.

From the user perspective, "open example" should be a discrete step. If they make some modifications and want to quickly get back to the original document they can't blindly press "undo" right now because they would get back to a blank page and then have to press "redo" and hope they don't accidentally press a button and then lose the document and need to "open example" again.

Of course, if there is a different way that I've missed to set the document content that doesn't result in an undo, I might be able to use that instead

**Comment by bpasero** [comment]
Ok, good point about the undo.

**Comment by bpasero** [comment]
@jrieken fyi

I think we would be open to a PR here if you are willing to look into it.

**Comment by jrieken** [comment]
Yeah, would be straight forward to pass on a string when calling the open function

**Comment by isidorn** [comment]
@jrieken please verify

**Comment by Niomar** [comment]
Any chance this could be revised so that openTextDocument takes the language/contents option as a separate parameter, instead of inplace of uriOrFileNameOrOptions?: vscode.Uri or string?  I have a similar use case as the original story for this issue, but I also need to name the file.
