### ISSUE TITLE
proposal for termianl UI

### ISSUE THREAD

**Issue by uxitten** [Microsoft/vscode#21414]
this is just a proposal for terminal ui

this UI user can be rename tab for quick find and access 
and add close button on tab section

![vsc terminal](https://cloud.githubusercontent.com/assets/1549069/23329870/5c93e036-fb56-11e6-9855-1a91ec5fbc1e.jpg)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10546
