### ISSUE TITLE
Using borders for underline looks bad and interferes with squiggles

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#21415]
![image](https://cloud.githubusercontent.com/assets/5047891/23330874/cb33b01c-fb5a-11e6-9fc8-d5b8cab77e78.png)

**Comment by alexandrudima** [comment]
The decision in today's standup was to roll back the changes done for #21331 and to also roll back #19645 which leads to reopening #12226

**Comment by bpasero** [comment]
Verified that we are using text-decoration underline for `mtku` style.
