### ISSUE TITLE
Keep focus on terminal when restoring open editors when switching branches

### ISSUE THREAD

**Issue by MattiasOlla** [microsoft/vscode#214121]
I'm a huge fan of the "Save/restore open editors when switching branches" feature (`"scm.workingSets.enabled": true`) introduced in version 1.89, but for me there is one blocker when switching branch from the integrated terminal. When the editor windows restore, the cursor automatically jumps from the terminal to the editor, often leading to me typing the next command in the editor. Would it be possible to save and restore the open files, but not switch the cursor away from the terminal?

https://github.com/microsoft/vscode/assets/17568632/1b036ed7-73cc-47af-b416-49e7ba348c80

**Comment by gjsjohnmurray** [comment]
I think this may have been fixed in the upcoming 1.90, expected to release later this week. Are you able to test using Insiders?
