### ISSUE TITLE
vscode suggests irrelevant code completions

### ISSUE THREAD

**Issue by dotchev** [Microsoft/vscode#21419]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.4.0-63-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-node-readme|bengreenier|1.0.7|
|python|donjayamanne|0.5.4|
|code-runner|formulahendry|0.5.1|
|vscode-exec-node|miramac|0.1.8|

---

Steps to Reproduce:

1. Open a .js file and type `double`
2. vscode shows 4 suggestions none of which are available in node.js or in my project
  - ConstranDouble
  - ConstrainDoubleRange
  - DoubleRange
  - onmsgesturedoubletap
![vscode-suggestion](https://cloud.githubusercontent.com/assets/4962228/23332669/3549e9c8-fb86-11e6-8a50-ec0d1ec96ef5.png)

**Comment by roblourens** [comment]
It gives you suggestions for the browser as well. If you want to exclude them, you can create a `jsconfig.json` file like:

```
{
    "compilerOptions": {
        "lib": [
            "es2015"
        ]
    }
}
```

then reload. And it should exclude DOM-specific JS things.
