### ISSUE TITLE
Extension hotkeys turns off every 5-10 minutes.

### ISSUE THREAD

**Issue by dslpp056193** [Microsoft/vscode#21410]
Extension hotkeys turns off every 5-10 minutes.
And for enable hotkeys need reload VS Code.

Extensions, whose hotkeys turns off:

|Extension|Author|Version|
|---|---|---|
|hex-rgba-converter|medzhidov|1.0.3|
|px-to-rem-with-scss|medzhidov|1.0.1|

---

- VSCode Version: Code 1.9.1 **[Unsupported]** (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|angular1-code-snippets|alexandersage|0.0.3|
|vscode-html-css|ecmel|0.0.33|
|format-indent|Kasik96|1.3.0|
|Material-theme|zhuangtongfa|1.0.3|
|font-awesome-codes-css|medzhidov|0.1.1|
|font-awesome-codes-html|medzhidov|0.0.5|
|hex-rgba-converter|medzhidov|1.0.3|
|px-to-rem-with-scss|medzhidov|1.0.1|
|vscode-scss|mrmlnc|0.6.1|
|seti-icons|qinjia|0.1.3|
|background|shalldie|1.1.9|
|vscode-nginx|shanoor|0.3.1|
|JavaScriptSnippets|xabikos|1.4.0|

**Comment by roblourens** [comment]
If it only happens with those extensions, maybe file an issue with the extension author? https://github.com/dslpp056193/hex-rgba-converter You can also check for errors in chrome devtools.

**Comment by dslpp056193** [comment]
I write it here, because it happens after installing latest vscode updates.
But i will check my extensions.

**Comment by dslpp056193** [comment]
I rewrote my extensions, but trouble not resolved.
I sure that bug in VSCode and will be pleased, if you check this bug.

**Comment by dslpp056193** [comment]
In oldest versions of VSCode all works fine.

**Comment by roblourens** [comment]
This is probably because you have the Background extension installed. It messes with vscode's code so we can't guarantee it. That's why it says "Unsupported" next to your vscode version. I recommend deleting that extension and reinstalling vscode.

**Comment by dslpp056193** [comment]
I've removed this extension, but problem is not resolved.

**Comment by dslpp056193** [comment]
Can i get an answer?

**Comment by roblourens** [comment]
Does it still say "unsupported"?

**Comment by dslpp056193** [comment]
No.
![image](https://cloud.githubusercontent.com/assets/11080873/23537380/b0609fc6-ffdc-11e6-84b0-138a58945309.png)

**Comment by roblourens** [comment]
Ok. Since it's only happening with those two extensions, you should file an issue in their repo, they might be doing something weird. You can also check for errors from the extensions in developer tools.
