### ISSUE TITLE
Issue with escaping characters in launch.json arguments

### ISSUE THREAD

**Issue by HenrikBach1** [microsoft/vscode#214143]
**Description:**
When configuring `launch.json` in VSCode, I am encountering an issue with properly escaping double quotes in my arguments. My current configuration looks like this:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Program",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}/program.exe",
      # args under discussion
      "cwd": "${workspaceFolder}",
      "externalConsole": false,
      "MIMode": "gdb"
    }
  ]
}
```
**Args under discussion**
The result in arg I want is `command "file"`:

1. The first and most obvious args that I tried was `"args": ["-g", "command \"file\"'"]` resulting in running code that `arg` becomes: `command file` and which is not as expected `command "file"`.
2. The second was `"args": ["-g", "command \\\"file\\\"'"]` resulting in running code that `arg` becomes: `command \"file\"`, which is as expected.
3. The third try was `"args": ["-g", "command "file""]` which isn't correct/allowed launch.json syntax, which is also expected.

Isn't there a bug luring around here in the first attempt?

My current VSCode is:
```
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-35-generic snap
```

Thank you in advance
Henrik Bach

**Comment by roblourens** [comment]
Please file this on the repo for the C++ debug extension, thanks. VS Code supports an option for different terminal character escaping modes and I don't know whether they expect to use that or expose it in a launch.json flag.
