### ISSUE TITLE
The feature page of vscode.html plugin is empty.

### ISSUE THREAD

**Issue by ZhiZe-ZG** [microsoft/vscode#214117]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
1.89.1
dc96b837cf6bb4af9cd736aa3af08cf8279f7685
x64
- OS Version: 
Edition	Windows 11 Pro
Version	23H2
Installed on	‎2023-‎11-‎28
OS build	22631.3593
Experience	Windows Feature Experience Pack 1000.22700.1003.0

Steps to Reproduce:

1. Open the VS Code
2. open the introduction page of buildin plugin vscode.html
3. open the FEATURES page
4. It's Empty

**Comment by sandy081** [comment]
I am seeing following

![Image](https://github.com/microsoft/vscode/assets/10746682/89e572f1-2cb9-4dec-9530-a0111aa1a9e9)

**Comment by ZhiZe-ZG** [comment]
@sandy081 Yes, I see the same. There should be details about supported languages like other built-in plugins.

**Comment by aeschli** [comment]
@sandy081 Can you point me to the place I need to fix this?

**Comment by sandy081** [comment]
Here it is https://github.com/microsoft/vscode/blob/b304df66db97f152517075a60deb866e52a15ee4/src/vs/workbench/services/language/common/languageService.ts#L132
