### ISSUE TITLE
Rendering bug on re open project

### ISSUE THREAD

**Issue by pierrejoye** [microsoft/vscode#214112]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  
- OS Version: 
Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1.  select open recent
2. there is a vertical separator visible on smaller window size (does not show if the window is wide enough to show the full path)
<img width="357" alt="vscode-reopen-bug" src="https://github.com/microsoft/vscode/assets/282408/a2d1a7fc-eb48-4084-a652-6369daadd8ab">

**Comment by rzhao271** [comment]
Hi @pierrejoye, the issue looks like a graphics rendering glitch.
Does the issue occur for you on VS Code 1.96 or later when launching the program from the command line with the `--disable-gpu` flag, i.e. `code --disable-gpu`?
