### ISSUE TITLE
Wrong JavaScript types from `vscode.typescript-language-features`

### ISSUE THREAD

**Issue by RobbyCBennett** [microsoft/vscode#214146]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: Windows 11

The extension `vscode.typescript-language-features` is reporting wrong types. This only happens if there is a jsconfig.json file and the JavaScript is in a real file rather than an untitled draft tab.

The types `* | null` and `* | undefined` are reduced to just `*` where the asterisk is a specific type.

Steps to Reproduce:

1. Enable the `vscode.typescript-language-features` extension if it isn't already enabled
2. Open a project without a jsconfig.json file
3. Create a JavaScript file
4. Define a variable/constant, such as `let element = document.getElementById('cart');`
5. Hover over the variable and see that the type is `HTMLElement | null`
6. Create a jsconfig.json file, which may or may not be empty
7. Hover over the variable and see that the type is `HTMLElement`

Screenshots of untitled tabs:
![Untitled tab without jsconfig.json](https://github.com/microsoft/vscode/assets/22121365/200e5cc7-ac53-45a2-8345-815e0073ea68)
![Untitled tab with jsconfig.json](https://github.com/microsoft/vscode/assets/22121365/be35cc71-30f5-421f-b7a7-837746f1df54)

Screenshots of real file tabs:
![image](https://github.com/microsoft/vscode/assets/22121365/8f5134d8-5a5a-42d7-9943-b981b1e9b774)
![image](https://github.com/microsoft/vscode/assets/22121365/b9e626f1-8367-4adb-ad74-7a717b948388)

**Comment by mjbvz** [comment]
Try enabling `strictNullChecks` in your jsconfig. It defaults to off if you have an jsconfig but is enabled for files that aren't part of a jsconifg project
