### ISSUE TITLE
Git extension gets preferential handling for naming its `statusBarCommands` in the Status Bar context menu

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#214191]
https://github.com/microsoft/vscode/blob/5d1faee1610052c3aaca4798e1a7fb3638953386/src/vs/workbench/contrib/scm/browser/activity.ts#L159-L171

If another SCM extension adds more than one command to the status bar the second and subsequent ones list in the status bar context menu with names that include their command ID. For example:

![image](https://github.com/microsoft/vscode/assets/6726799/88b4effd-6dc5-4bd2-aeae-16e04aabe556)

**Comment by lszomoru** [comment]
Thank you very much for the feedback. At the moment we are not planning on making any changes related to this.
