### ISSUE TITLE
Custom powerline git, ln and lock symbols

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#214142]
Upcoming change from xterm.js https://github.com/xtermjs/xterm.js/pull/5054

Before (with a font NOT containing powerline symbols):

![image](https://github.com/microsoft/vscode/assets/2193314/71e1d97b-a813-488c-8d14-343228bbe4e5)

Before (with a font containing powerline symbols):

![image](https://github.com/microsoft/vscode/assets/2193314/5e3d62bf-277c-4916-86fb-4b0c2500d16b)

After:

![image](https://github.com/xtermjs/xterm.js/assets/2193314/3ad6e44b-856e-440c-9a6c-297a33fe34c4)

Zoomed:

![image](https://github.com/xtermjs/xterm.js/assets/2193314/729558e3-c0a3-445a-b40b-ea0438807fe4)

Big letter spacing and line height:

![image](https://github.com/xtermjs/xterm.js/assets/2193314/07087f36-7df5-459d-ae66-a4974d9d03de)

**Comment by Tyriar** [comment]
To verify in powershell:

Run:

```ps1
"`u{e0a0} `u{e0a1} `u{e0a2}"
```

Verify symbols appear

Change terminal line height and letter spacing, verify the symbols rescale.

**Comment by andreamah** [comment]
![image](https://github.com/user-attachments/assets/92d49d29-8920-420e-8547-b677ca236f42)
seems to work for me

**Comment by alexr00** [comment]
@Tyriar apparently it was version 5:
```
PS C:\Users\alros\repos\Microsoft\vscode> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  3672    
```

**Comment by Tyriar** [comment]
@alexr00 ah ok, it likely only works on pwsh 6 or 7+
