### ISSUE TITLE
VScode flickers when the debug session is on

### ISSUE THREAD

**Issue by shirkerohit** [microsoft/vscode#214126]
Does this issue occur when all extensions are disabled?: Yes
I disabled all the extensions and still, this is an issue.

- VS Code Version:
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-35-generic

- OS Version: 
Ubuntu 22.04.4 LTS (64-bit)
Gnome: 42.9

Steps to Reproduce:

1. Open file to debug with vs-code 
2. Set the breakpoints in PHP file. 
3. Click on start debug to start debug session
4. Hit the URL and wait for breakpoint to hit
5. Look for the breakpoint. The screen starts flickering
6. Try to hover over the variables and they too flicker

I tried with the old version (https://github.com/microsoft/vscode/tree/1.87.1) with the same os and the same extension and it works fine. It all started with build 1.88.0

Attached is the screen recording. Let me know if any further details are required.

Note : If i run pure PHP script with debug points it works fine. Not sure how? can this be related to project?

https://github.com/microsoft/vscode/assets/31042658/ffafade6-5e34-4085-9cf0-a23823a90c82

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/210733
