### ISSUE TITLE
Default settings not working 

### ISSUE THREAD

**Issue by laperon** [Microsoft/vscode#21426]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|format-php|Kasik96|1.1.2|
|php-formatter|Sophisticode|0.2.4|
|path-intellisense|christian-kohler|1.2.0|
|githistory|donjayamanne|0.1.5|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.2|
|php-pack|felixfbecker|1.0.0|
|auto-close-tag|formulahendry|0.3.9|
|ftp-sync|lukasz-wronski|0.3.2|
|vscode-icons|robertohuertasm|7.2.0|
|bootstrap4-vscode|thekalinga|2.3.3|
|wordpress-snippet|tungvn|1.1.2|
|bootstrap-3-snippets|wcwhitehead|0.0.9|

---

Steps to Reproduce:

1."editor.formatOnType": true, not working. It's not works. When i open welcome page, formatOnType works good 
2.

**Comment by roblourens** [comment]
What do you mean, when you open the welcome page, it works?

**Comment by laperon** [comment]
Yes

**Comment by laperon** [comment]
1. without "welcome page" https://gyazo.com/50d0dc69b689af355f9e3959de287cb7
2. with "welcome page" https://gyazo.com/6eab8bbdaa9ceb13f59b698e0ab467c1

**Comment by jrieken** [comment]
>  It's not works.

In what language doesn't work this?

**Comment by laperon** [comment]
In php files

**Comment by jrieken** [comment]
Ok, please file this issue against the php formatter you are using then. Format on type is something different that format file and an extension must explicitly implement a `OnTypeFormattingEditProvider` to support this.
