### ISSUE TITLE
Red underline error

### ISSUE THREAD

**Issue by GopalDevda** [microsoft/vscode#214224]
Type: <b>Feature Request</b>

Red line show when I rename a folder and tick change the folder name in imports

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22635
Modes:

**Comment by RedCMD** [comment]
can confirm
typescript doesn't seem to update its internal file index correctly
restarting fixes it

**Comment by mjbvz** [comment]
Please share steps to reproduce the issue

**Comment by RedCMD** [comment]
I can't seem to repo on renaming folders atm
but dragging and dropping files up and down folders can cause issues

https://github.com/microsoft/vscode/assets/33529441/41fc6182-3b59-4f53-89f3-fce027b7da81

you can't see it, but the 'Update imports' pop up only shows up once on the first move
(you can see my mouse go to the center of the screen)
but not the 2nd move
![image](https://github.com/microsoft/vscode/assets/33529441/ae3897d4-5fbb-4fb4-90f8-1487e01074b4)
