### ISSUE TITLE
Visual studio code won't maximize

### ISSUE THREAD

**Issue by AugustFlow** [microsoft/vscode#214244]
Type: <b>Bug</b>

The buttons in the top right work for minimize and close the program but the maximize button doesn't do anything. Dragging the window to the top of the screen doesn't work either. Neither does dragging it to any side of the screen to try to resize it that way. It may be an extension I downloaded but I uninstalled the one I had suspicions about. How do I factory reset visual studio code? I'm going to try uninstalling then reinstalling.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5825U with Radeon Graphics          (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.34GB (5.81GB free)|
|Process Argv|--crash-reporter-id d2b29cc4-adc2-4cf1-83d4-a7e1fe39df7f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|2.0.9
code-runner|for|0.12.2
vscode-drawio|hed|1.6.6
css-snippets|joy|1.0.4
csdevkit|ms-|1.6.8
csharp|ms-|2.31.19
vscode-dotnet-runtime|ms-|2.0.5
vscode-edge-devtools|ms-|2.1.5
live-server|ms-|0.4.13
material-icon-theme|PKi|5.3.0
java|red|1.31.0
LiveServer|rit|5.7.9
bootstrap4-vscode|the|6.1.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vstuc|vis|1.0.2
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0
codetour|vsl|0.0.59
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31064719
chatpanelt:31048053
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecationcf:31061161
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by benibenj** [comment]
@AugustFlow Did reinstalling fix your problem? I'm assuming this is only happening with vscode and no other program?

**Comment by AugustFlow** [comment]
Yes, this only happened with visual studio code.

Reinstalling did Work!!

I think it was one of the extensions I had so I removed the ones I thought
were at fault, deleted VSCode, reinstalled VSCode, and the maximize window
features started working again!
