### ISSUE TITLE
VS Code Freezing With 2+ Projects Open

### ISSUE THREAD

**Issue by iamclaytonray** [Microsoft/vscode#21425]
- VS Code Version: 1.9.1
- Mac OS Version: 10.12.3 

I only have the C/C++ and C# extensions. I primarily write in JavaScript (Node/Express/Angular/React) with VS Code.

1. `code .`
2. VS Code "shell" opens and freezes (about every 2 - 4 times, especially with 2+ projects open)

Not sure how to reproduce for you but about every 2 - 4 times I open VS Code, it simply freezes (it will open the VS Code shell but the sidebar, my files, etc won't show up. Just the shell, where it freezes.) and sometimes I have a hard time force-quitting it. The only way to get it working again is to force quit, but then I quit out of all of my other open projects. I have tested it out on both iTerm and Terminal but the issue still persists. It is worse if I have 2+ apps in other VS Code windows open. It's been going on for about 1 - 2 weeks. Let me know if I can provide anymore details and/or what I can do to resolve this issue if it's on my end. Thanks guys.

**Comment by roblourens** [comment]
If this happens consistently, can you try starting with `--disable-extensions` to check whether one of the extensions is involved?

Also, could you try downloading the Insiders build and check whether it happens there?

**Comment by iamclaytonray** [comment]
Sorry, I've had a slew of doctor appointments and I am finally just getting to this issue. So I tried opening about 10 different projects with the `--disable-extensions` flag and nothing froze or crashed. I will go ahead and download the Insiders build and respond later. Just didn't want to leave you hanging until then.

**Comment by roblourens** [comment]
No worries. It sounds like there might be some extension doing a lot of work - would be really helpful if you can figure out which one by disabling extensions.

**Comment by pawelbujna** [comment]
+1 So I've got a simillar problem. It freezes when changing project using GPM or other project manager. Hmm.. I think it may related to CSS autocomplete extension, but not sure. Will look closer wheres the problem.

**Comment by isidorn** [comment]
Please file those issue to the reposotires of the extensions.
Closing this as it seems unrelated to vscode core
