### ISSUE TITLE
Provide ability to view only changed lines in compare diff view

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#21427]
1.  For some types of comparisons, this provides a much quicker and easier view of the changes when common lines are filtered out.
2. There are times when is is useful to be able to select and copy the text of only the changes

**Comment by rebornix** [comment]
@daanschipper we added a simple diff view which only contains content change and some context, you can play with it by pressing F7. Does this meet your need?

**Comment by dakaraphi** [comment]
@rebornix The new view is better in some uses, but I can't see all changes easily at a glance.  I have to click the next arrow.
Also, there are times when you are diffing a long list of something and you want to capture what is missing or different.  This might be information important to send to someone or save etc.  So being able to select and copy all missing lines or added lines is useful, but I still can't do that with this view.
