### ISSUE TITLE
Fully adopt agents for terminal inline chat

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#214208]
The use of inline chat for terminals relies on a few deprecated methods and code paths. Instead, terminal chat should solely rely on agents, like notebook and editor chat. This means

* register an agent for the terminal location (from the extension)
* inside the extension dispatch the agent invocation
* in the renderer create the widget for the terminal locations
* do away with custom "make request" actions and rely on the chat widget, e.g make sure the default send invokes `ChatService#sendRequest`
* remove more custom logic, like history management, placeholder text etc pp

**Comment by meganrogge** [comment]
Thanks for creating this.

we already have the terminal agent

https://github.com/microsoft/vscode-copilot/blob/9c1ddca4e49012d188f4bf1849c72115d4a4bb4e/src/platform/chat/common/chatAgents.ts#L19

that uses the terminal location

https://github.com/microsoft/vscode/blob/3c6a63a0956835aade45adca303aac82df0dc105/src/vs/workbench/contrib/terminalContrib/chat/browser/terminalChatWidget.ts#L59

will look into the other items

**Comment by jrieken** [comment]
>  I investigated reusing the inline chat actions instead of our custom ones here 

This is not about _inline_ chat actions but about using the normal chat widget actions. Actually, inline chat and notebook chat have no more actions for making requests etc

>  figure out how since we cannot access TerminalChatController in that layer

Some bits of the controller will be less controller'ish, e.g it will not make a request anymore but listen on the current chat model for a new request being added, for response content being received etc


So, in addition the outlined steps above do the following

* as soon as the widget shows, create a chat model using the IChatService
* set that chat model to the widget
* listen to the chat model

**Comment by meganrogge** [comment]
I see, ATM, we're only creating the model when `acceptInput` is called, not when it's shown.

https://github.com/microsoft/vscode/blob/e5ec5c010cefbd654d903867ba60400fc4441302/src/vs/workbench/contrib/terminalContrib/chat/browser/terminalChatController.ts#L253

**Comment by jrieken** [comment]
Yes, have the model being set early and you'll have to remove the custom logic to create/make a request from `acceptInput`.  Instead listen for a request being make and react to it. This is [how editor chat](https://github.com/microsoft/vscode/blob/a9a4ef8a716a2646ba0c39058cce3a7f36104717/src/vs/workbench/contrib/inlineChat/browser/inlineChatController.ts#L572) does it. It just waits for a request to come and then shows it
