### ISSUE TITLE
Misspelled Word in Error Message

### ISSUE THREAD

**Issue by ka684laca** [microsoft/vscode#214293]
Type: <b>Bug</b>

Minecraft datapack:
give @s bow[enchantments={levels:{"minecraft:infinity":1,"minecraft:unbreaking":3}}] 1

The error message VS Code gives misspells the word "separate".

Error message:
Expected a space to seperate two arguments.datapack

VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 1, 2|
|Memory (System)|16.00GB (1.15GB free)|
|Process Argv|--crash-reporter-id 78f54d01-f8fc-4b0e-ba9c-bc70dc6b0fd5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
language-mcfunction|arc|0.18.0
syntax-mcfunction|Min|0.6.0
datapack-language-server|SPG|3.4.19
mcfunction-debugger|van|1.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
showvideoc:31016891
chatpanelt:31048053
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecationcf:31061161
pythonprt:31056678
dwnewjupytercf:31046870
newcmakeconfigv2:31067619
26j00206:31048877

```

</details>

**Comment by DonJayamanne** [comment]
Thank you for filing this issue.
Unfortunately, I'm struggling to where this error message is displayed or what extension displays this.
Please can you disable all extensions and try again.
If the problem doesn't exist when extensions are disabled, then I'd suggest you file the issue against the relevant extension (given the fact that you have just 4 extensions, that should be easy enough to figure out).

**Comment by ka684laca** [comment]
Happens when these two extensions are the only ones enabled:
Data-pack Helper Plus
syntax-mcfunction

**Comment by DonJayamanne** [comment]
Thank you for getting back.
Given that these are external extensions, I would suggest filing an issue with the repositories of those extensions.
