### ISSUE TITLE
Visual Studio-style folding

### ISSUE THREAD

**Issue by Sensuikan-U511** [microsoft/vscode#214299]
Visual Studio recognises the line above a free-standing opening bracket as the basis for folding and folds it all into one line, like so:

![2024-06-04 13_02_45](https://github.com/microsoft/vscode/assets/165439707/38f27047-15d9-4b6d-b70b-c74503a0d3f3)
![2024-06-04 13_02_51](https://github.com/microsoft/vscode/assets/165439707/cf92137f-b409-46a6-b364-4d857af71ec4)

In comparison, even with extensions, the closest I can get to replicating this behaviour in VSCode is this:  
![2024-06-04 13_19_33](https://github.com/microsoft/vscode/assets/165439707/425509d0-38b9-44bf-9032-24840288ce06)
![2024-06-04 13_19_36](https://github.com/microsoft/vscode/assets/165439707/2633809e-ae9c-41c2-91ea-ed1262a67255)

I have been informed by the extension developer that it is not possible to fix this issue by extension. 
Although I've come to prefer VSCode in all other aspects, this lone issue does detract from the experience of using it as someone who has always written code in Allman-style. It doubles the vertical space consumed by a folded block, and it's much less clean to read.
If this will not be accepted as a feature, I would be grateful to receive a pointer as to where I could change this behaviour so that I can build a personal fork.

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/issues/3352 captures the request to have closing bracket in the folded region.

There's currently no plan to work on such a feature.

**Comment by aeschli** [comment]
You want the folding marker to be with the function identifier, not on the opening bracket.
That decision is made by the language extension that you use. In your case C#?
e.g. for TypeScript, there the folding marker stays on the identifier.

![Peek 2024-06-05 21-13](https://github.com/microsoft/vscode/assets/6461412/14e01e74-d8f5-402a-a116-499d2badabf2)

You could file a request against the C# extension.

**Comment by aeschli** [comment]
Thats strange. It's not what I see with TypeScript. 
Yes, the language extensions contribute a folding provider that is in full control where the folding ranges start and end.
That said, as a user you can switch to indentation based folding using the setting `"editor.foldingStrategy": "indentation"`.
Maybe that's what you currently use?
