### ISSUE TITLE
When extensions panel is opened, focus should default to search input

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#21428]
Whenever I open the extensions panel, my first action is to search for something.  However, the focus does not start in the search input box.

**Comment by bpasero** [comment]
@dakaraphi where is your focus when you open the extensions viewlet? How do you open it?

**Comment by dakaraphi** [comment]
@bpasero current focus is usually within an editor.  I execute the 'ext' command from the command palette.

**Comment by roblourens** [comment]
Maybe a bug, any other way of opening the viewlet focuses the input box.

**Comment by joaomoreno** [comment]
@dakaraphi The command is `View: Show Extensions` This will focus the text box.

**Comment by dakaraphi** [comment]
@joaomoreno so you are saying that the 'ext' command should not set focus when the extensions panel is opened?  Why would I want to open the extensions and not do anything with the panel?

**Comment by joaomoreno** [comment]
I'm not saying that it shouldn't. It's just that `ext ` is a deprecated way of going to your extensions. <kbd>Cmd Shift X</kbd> or the `View: Show Extensions` command is the best way to go there. Do you still want to get focus on `ext `?

**Comment by dakaraphi** [comment]
@joaomoreno Well, it is already committed to muscle memory, but I can change :-)
Thanks for the explanation.
