### ISSUE TITLE
Typescript 2.2 Auto Import and Tslint Formatting

### ISSUE THREAD

**Issue by arciisine** [Microsoft/vscode#21424]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.  Tslint Rules
```json
{
   "rules" : {
       "quotemark" : [
          true,
          "single"
        ]
    }
}
```

2. Use the new auto import feature 

3.  The import is added with double quotes (instead of single quotes)

The import should be added with matching quotes with respect to tslint.json

**Comment by vigie** [comment]
My work around until this is fixed is to use

`"tslint.autoFixOnSave": true`

**Comment by mjbvz** [comment]
I believe this would be related to #17627, which tracks honoring tslint format settings in general. Also potentially related to https://github.com/Microsoft/TypeScript/issues/11320

I've opened https://github.com/Microsoft/TypeScript/issues/14347 against TypeScript to track the import quick fix  quotes specifically.

**Comment by mjbvz** [comment]
Closing as tracked upstream by https://github.com/Microsoft/TypeScript/issues/13270
