### ISSUE TITLE
Unit test failure: CodeEditorWidget suite

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#214296]
Refs https://dev.azure.com/monacotools/Monaco/_build/results?buildId=276771

Regressed via https://github.com/microsoft/vscode/commit/3bb57eb6ef04824b426e4dd76e305cb2bfca3f75 . Currently `main` branch PR pipeline is broken, increasing priority on this issue. PTAL, thanks!

**Comment by hediet** [comment]
Fixed.
