### ISSUE TITLE
Enable Preview From Quick Open

### ISSUE THREAD

**Issue by dima007arenko** [microsoft/vscode#214273]
Could we just have by default always open in new tab. Why it was set to same tab in the first place? it is the worst setting which no one uses at all.
Also after recent update you need to hold control to open from cmd + p. Is it expected?

**Comment by TylerLeonhardt** [comment]
@dima007arenko 

> Could we just have by default always open in new tab. Why it was set to same tab in the first place? it is the worst setting which no one uses at all.

is this the setting you are looking for?
<img width="898" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/053e5ccf-4060-4979-b76f-8b8f28af6b55">

> Also after recent update you need to hold control to open from cmd + p. Is it expected?

I do not experience this, can you provide repro steps?

**Comment by dima007arenko** [comment]
Hi @TylerLeonhardt here some screens of my settings and repro steps:

## Option A

1. hit ctrl/cmd + p 
2. enter file name
3. hit enter
4. hit ctrl/cmd + p again
5. enter new file name (better to use file in same folder as 1st one)
6. hit enter
**Expected result:**
2 new tabs opened
**Actual result**
1 new tab 

## Option B

1. ctrl/cmd + b to open left/right side panel with file overview
2. open file in some folder by click it with left mouse button
3. open differnt file from the same folder
**Expected Result**
2 new tabs 
**Actual result**
1 new tab


![Screenshot 2024-06-05 at 1 11 38 PM](https://github.com/microsoft/vscode/assets/146958701/ba93e45a-4743-4e1f-8882-8f84c175cdf2)
![Screenshot 2024-06-05 at 1 11 29 PM](https://github.com/microsoft/vscode/assets/146958701/35b95371-c750-4326-a634-3ea732b6fe28)
![Screenshot 2024-06-05 at 1 11 20 PM](https://github.com/microsoft/vscode/assets/146958701/42d10c2f-1fb5-468e-9515-5aea59a7e9dd)

**Comment by dima007arenko** [comment]
thank you @TylerLeonhardt !
works like a charm.
Google said that you should mark that checkbox in order to open new tab each time
