### ISSUE TITLE
Mem perf: large launch schema ends up being retained as string

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#214205]
Doing a snapshot of heap right after startup with a `package.json` opened shows the launch schema to be a top retainer in strings:

<img width="1052" alt="image" src="https://github.com/microsoft/vscode/assets/900690/73a77fea-6d1a-45d9-be99-630a6d73c3f2">

That schema is really huge (more than 1.5 MB in size as string).

Can we try to only load this after startup or lazily when needed?

**Comment by bpasero** [comment]
Actually the real reason why we end up retaining a huge string is because this schema gets loaded as text document:

<img width="974" alt="image" src="https://github.com/microsoft/vscode/assets/900690/c0a1c99c-eed8-4f40-8d8f-50ca4b399ad5">

We must have a built-in extension that loads these schemas as text documents which will retain them as string in memory. It feels like the wrong way to have the schemas, why not just load them via file services?

**Comment by aeschli** [comment]
That schema should only load when you open a `launch.json` file in an editor.

**Comment by bpasero** [comment]
@aeschli This is opening a `package.json`.

**Comment by aeschli** [comment]
That's how the launch.json schema gets loaded:
- package.json has a `contributes` section where `configurationDefaults` is a possible section. That brings in the configurationSchema that contains a setting `'launch` where one can define a launch configuration.
- The launch configuration schema is huge with a lot of repetition

I know there's een alreayd a lot of work done in launch to shar common sections, but it looks like there still much more to do.
I can't really pinpoint the problem.
What I can do is look into automatically using refs when serializing twice the same object.

**Comment by connor4312** [comment]
Potentially improved with https://github.com/microsoft/vscode/issues/53557 too

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode/pull/219883 and https://github.com/microsoft/vscode/pull/221136
