### ISSUE TITLE
Accessibility : unhelpful screen reader announcement when switching editor tabs

### ISSUE THREAD

**Issue by RichCaloggero** [microsoft/vscode#214245]
Type: <b>Bug</b>

If I have more than one editor open and I press control+tab to cycle among these open editors, the screen reader should immediately announce the next tab as I press the key. For instance, if I've got f1 and f2 open and am currently editing f1, pressing control+tab should immediately announce f2.

CUrrently, what happens is that the screen reader repeats the name of the file I'm currently editing (f1 in this case), sometimes multiple times, then eventually gets around to announcing the file I'm moving to (in this case f2).

If I've got only two files open this isn't much of a problem, but if I'm working on a project and have several files open at once, cycling among them becomes very painful, slow, and error prone.

Try it with NVDA (without looking at the screen) and you'll see...

VS Code version: Code - Insiders 1.90.0-insider (fc8762e773c35d4e52e8a7375704af2e24698e5d, 2024-05-29T05:49:46.157Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (9.77GB free)|
|Process Argv|C:\\users\\rich\\Projects\\dsp.git --crash-reporter-id da8aa860-ae68-41ac-aa82-9caa04dc7fc1|
|Screen Reader|yes|
|VM|31%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.10
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
remote-wsl|ms-|0.88.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:30973074
showvideot:31016890
chatpanelt:31014475
f3je6385:31013174
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupytercf:31046870
nb_pri_only:31057983
fa862199:31048878
nativerepl2:31062443
refactort:31061298

```

</details>

**Comment by meganrogge** [comment]
Yeah, I see it's saying `Entering list box, f1` then `f2`. This is because we're using the quick-pick for this action, so when that's focused, it's announcing `Entering list box, f1`. We don't want to try to control what the screen reader is reading here, so I think this is as designed. 

I believe @jooyoungseo uses a different editor navigation strategy - `ctrl+1` `ctrl+2` etc. I'd recommend that approach.
