### ISSUE TITLE
Import Update When File Move Won't Work for path alias specified in tsconfig.json

### ISSUE THREAD

**Issue by leeyuky9802** [microsoft/vscode#214217]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

prep:

create tsconfig.json including such compilerOptions:

      "baseUrl": "./",
      "paths": {
        "@/*": ["./*"]
      }

1. 
create a file ./a.ts
export const a = 1;

create a file ./b.ts
import {a} from './a';

change the name of a.ts to aa.ts
imports in ./b.ts changes
2. 
create a file ./a.ts
export const a = 1;

create a file ./b.ts
import {a} from '@/a';

change the name of a.ts to aa.ts
imports in ./b.ts won't change

**Comment by rhys-okane-instil** [comment]
+1, this definitely worked fine before in the previous version.
Can reproduce on the following version:
```
Version: 1.89.1 (Universal)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:24.611Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.3.0
```
