### ISSUE TITLE
Paste not working in "search and replace" toolbar

### ISSUE THREAD

**Issue by devkhan** [Microsoft/vscode#21420]
- VSCode Version: 1.9.1 (1.9.1)
- OS Version: macOS Sierra 10.12 Beta

Steps to Reproduce:

1. Copy anything from anywhere.
2. Try to paste in either of the `Search` or `Replace`

P.S.: `Context Menu` -> `Paste` works fine, but `cmd+v` doesn't.

**Comment by roblourens** [comment]
This works for me. This is the find widget (`cmd+f`) right?

**Comment by devkhan** [comment]
No, this happens in the "search and replace" (`cmd+shift+f`). Find (`cmd+f`) works fine.

**Comment by roblourens** [comment]
Ok, so nothing happens when you press `cmd+v`? @sandy081 Any idea what could be the problem?

**Comment by devkhan** [comment]
@roblourens Sorry, I just checked, `cmd+v` isn't working in find, search and replace, extensions search, `cmd+p` or `cmd+shift+p`. But it's working in the editor.

**Comment by devkhan** [comment]
And I tried the `--verbose` mode too, but nothing came up in the console on `cmd+v`.

**Comment by roblourens** [comment]
Are there any errors in chrome devtools? (Help > Toggle Developer Tools)

And could you try downloading the Insiders build to see if it works there?

**Comment by devkhan** [comment]
Sorry again, it was due to an emacs binding extension I had installed, which overrode the `cmd+v` binding. I'll open an issue there. Thanks.
