### ISSUE TITLE
Highlight all pasted area

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#21421]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|concrete|vscode|0.1.10|
|vscode-eslint|dbaeumer|1.2.6|
|tslint|eg2|0.8.1|
|Theme-TomorrowKit|ms-vscode|0.1.3|
|debugger-for-chrome|msjsdiag|2.5.4|
|vetur|octref|0.3.8|
|vuehelper|oysun|0.1.0|
|vscode-icons|robertohuertasm|7.2.0|
|language-stylus|sysoev|1.6.0|
|vim|vscodevim|0.5.3|

---

Currently when pasting to replace multi lines of text (select everything in target, then paste):

![image](https://cloud.githubusercontent.com/assets/4033249/23333432/2a8ca66a-fb59-11e6-855c-50ff5fd6c553.png)

This creates the illusion that only last two lines changed, when the paste essentially rewrote on the four lines.

**Comment by octref** [comment]
Probably belong to @rebornix

**Comment by rebornix** [comment]
![paste-multiline](https://cloud.githubusercontent.com/assets/876920/23484568/563af9ca-fe8c-11e6-8abb-9bad2969645a.gif)

@octref not sure if I did anything wrong but pasting will lead to single cursor instead of selection so the behavior is like above. Can you help me with how to run into the state you described?

**Comment by octref** [comment]
Oh, forgot to mention, I was using `V` in VSCodeVim to select top 4 lines then `Cmd + C`.
Then I move down, `V` to select bot 2 lines and `Cmd + V`.

**Comment by octref** [comment]
![vim](https://cloud.githubusercontent.com/assets/4033249/23536323/117a9a50-ff92-11e6-93b0-33739cf86f07.gif)

**Comment by octref** [comment]
This has been fixed now there is no highlighting.
