### ISSUE TITLE
Can no longer create branch when running `Git: Checkout`

### ISSUE THREAD

**Issue by Meowbeast** [Microsoft/vscode#21439]
- VSCode Version: Code - Insiders 1.10.0-insider (b2a55bd66eb60af11c60ddd61b7581538b216051, 2017-02-24T20:35:46.683Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.6|
|vscode-icons|robertohuertasm|7.3.0|;

---

Steps to Reproduce:

1. Click branch in bottom right
2. New window no longer allows to create branch

Here is what it looked like before the insider release:
![image](https://cloud.githubusercontent.com/assets/22228023/23338116/32490178-fbc7-11e6-9382-a68e466175ed.png)

Now the option is purely branch to checkout:
![image](https://cloud.githubusercontent.com/assets/22228023/23338125/53df338e-fbc7-11e6-8eb3-4a1b03371a79.png)

**Comment by joaomoreno** [comment]
@bpasero Could we augment the current pick API such that I still get what the user picked? Possibly I should also be able to update the informational message, as the user types.

**Comment by bpasero** [comment]
@joaomoreno you mean to have API to return what the user typed even if there is no matching pick entry in the list?

**Comment by joaomoreno** [comment]
Yeah, corrected my typo, sorry!

**Comment by bpasero** [comment]
Maybe this should be baked into the [`onDidSelectItem`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1401) callback?

**Comment by bpasero** [comment]
Makes sense, I think we can add something to the [`QuickPickOptions`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1377) API.

/cc @jrieken on the idea of https://github.com/Microsoft/vscode/issues/21439#issuecomment-282995527

**Comment by jrieken** [comment]
@joaomoreno You want a combination of quick pick and input box, right? Since the API promises to return one of the items (can be objects) it is tricky to just come up with an item based on invalid user input. This needs thinking...

**Comment by Meowbeast** [comment]
This seems to be resolved on the build released today.

![image](https://cloud.githubusercontent.com/assets/22228023/23483122/3c35c2a2-fe97-11e6-9042-218a355bd667.png)

**Comment by bpasero** [comment]
@Meowbeast we only enabled the new SCM features in the insiders release. Since you seem to be using stable, you are back to the old SCM world.

**Comment by Haroenv** [comment]
So how do you make a new branch now, isn’t it possible anymore?

**Comment by joaomoreno** [comment]
There's a global command `Git: Create Branch...`

![image](https://cloud.githubusercontent.com/assets/22350/24346922/d226ae68-12d6-11e7-8ba3-f0b84a9d2f24.png)

**Comment by reaction1989** [comment]
Anything on this. This one made it into the new stable release. Missing the workflow of just clicking the branch in the lower left and create a new one from it

**Comment by akulbe** [comment]
It's interesting that this was marked a duplicate. I was able to create a git branch successfully from 1.10.2 (that was the third screenshot I included in my report #24315). ¯\_(ツ)_/¯

Thank you for your work, in any case!!

**Comment by ryanbowden** [comment]
Any idea when this one will be fixed?

**Comment by joaomoreno** [comment]
It is assigned for April 2017 right there in the Milestone assignment.

**Comment by eamodio** [comment]
Even outside of this issue, I think it would be great if this ability was added (opt-in) of course to the `QuickPickOptions` as suggested here https://github.com/Microsoft/vscode/issues/21439#issuecomment-283018897

**Comment by AmirSavand** [comment]
I really liked it when you just click on the branch name on bottom left and start typing the branch you want to create. no longer there 😢

**Comment by joaomoreno** [comment]
Gonna have to push this until we figure out a good API for it: #25140

**Comment by jeffmcaffer** [comment]
Using 1.11.2 and have to say I really miss the click and type experience.  It is unclear from the comments above if it will be coming back.

**Comment by akulbe** [comment]
Is it possible to bring the functionality back on a temporary basis, while the larger API issues get sorted out? Please? @jrieken @joaomoreno

**Comment by kai23** [comment]
Is there any update of this removed-but-everyone-like-it feature ? :)

**Comment by joaomoreno** [comment]
Found a little workaround for this. 👍 

![image](https://user-images.githubusercontent.com/22350/27869190-6e3b7fa6-619f-11e7-847f-d185cb89ba3a.png)
