### ISSUE TITLE
`<textarea>` in webviews don't support spellcheck

### ISSUE THREAD

**Issue by evangrayk** [microsoft/vscode#214367]
Does this issue occur when all extensions are disabled?: No (N/A, applies to webview extension API so requires an extension)

- VS Code Version: 1.90-insider
- OS Version: macOS (universal)

Steps to Reproduce:

1. Have an extension with a webview with a `<textarea>` with `spellcheck="true"`. For example, add `<textarea spellcheck="true"></textarea>` to the [Cat Coding webview sample](https://github.com/microsoft/vscode-extension-samples/blob/main/webview-sample/src/extension.ts#L208)
2. type some misspelled text into the textarea
3. No red squiggles appear to correct typos

![Screenshot 2024-06-05 at 11 26 20 AM](https://github.com/microsoft/vscode/assets/1762690/7f4c21a9-80ff-4362-b5d4-b7cf7beb0d38)

This bug prevents our [Sapling extension](https://marketplace.visualstudio.com/items?itemName=meta.sapling-scm)'s commit message editor from providing spell checking.

**Comment by karl-meiser1** [comment]
@evangrayk @sherwyn33 I'm hoping to get the Anthropic community to help push for this feature in VSC; If you're willing to upvote https://github.com/anthropics/claude-code/issues/70049 would greatly appreciate it!
