### ISSUE TITLE
Golden ratio for split views/editors

### ISSUE THREAD

**Issue by muzaffar-omer** [microsoft/vscode#214320]
Hi,

Coming from Emacs, having the [golden ratio](https://github.com/roman/golden-ratio.el) in VSCode would really be great. I see it has been raised in https://github.com/Microsoft/vscode/issues/25903.

By any chance, could it be considered again? or do we have the API that could be used to implement an extension?

Thank you, and thanks for all the work in :heart_hands:  VSCode :heart_hands:

**Comment by bpasero** [comment]
I believe there is now sufficient API for extensions to do this. You might want to check for an existing extension doing this already in the marketplace.

**Comment by WarrenMarshall** [comment]
I use this all the time in the various JetBrains IDEs.  It's super useful.

**Comment by muzaffar-omer** [comment]
> I use this all the time in the various JetBrains IDEs. It's super useful.

Indeed, it was super useful in Emacs as well. Specially when working in the laptop (without having a big monitor). 

I've never coded a VSCode extension, but I'm interested to try coding a Golden Ratio extension for VSCode.

**Comment by thegass** [comment]
would be a super usefull feature. i used it with neovim and now i am constantly resizing my vscode splits.
