### ISSUE TITLE
Support Inrease & Decrease Number using key bindings

### ISSUE THREAD

**Issue by rohmanhm** [Microsoft/vscode#21432]
- VSCode Version: 1.9.1
- OS Version: OSX El Capitan

Steps to Reproduce:

1. I think it would be nice if you add support increase and decrease number directly via key bindings. Example: `⌘+CTRL+↑` to increase number from `190` to `191` and `⌘+CTRL+↓` to decrease number from `191` to `190`

**Comment by roblourens** [comment]
I see at least a couple extensions that can do this, like https://marketplace.visualstudio.com/items?itemName=nmsmith89.incrementor. I recommend trying one out.

**Comment by rohmanhm** [comment]
@roblourens Thanks for your suggestion. 👍🏼

**Comment by mjbvz** [comment]
Closing as extension candidate. Emmet also provides built in support for this. See `emmet: increment by 1` and `Emmet: decrement by 1`
