### ISSUE TITLE
typeScript error

### ISSUE THREAD

**Issue by suanmou** [Microsoft/vscode#21437]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please provide information about the issue you are seeing
