### ISSUE TITLE
Enable extensions to have "file level" comments

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#214327]
Proposal: let the comment thread `range` be `undefined` to indicate a file level comment.

https://github.com/microsoft/vscode/blob/1ed0758b5f0e9b6f7b78b4ef7a376c17d6bc176e/src/vscode-dts/vscode.proposed.fileComments.d.ts#L14-L18

**Comment by jrieken** [comment]
@alexr00 just fyi that @mjbvz and I are 👍 for this

**Comment by alexr00** [comment]
Thanks for the heads up! I will just finalize it then. I also added an new return type to `provideCommentingRanges` that allows the extension to say that users can leave a file level comment. Should I make a new interface for the return type?

https://github.com/microsoft/vscode/blob/f388d52dc74931acf9831da7d9cec3f285763ce6/src/vscode-dts/vscode.proposed.fileComments.d.ts#L84-L85

Something like this:

```
export interface ProvidedCommentingRanges {
    fileComments: boolean;
    ranges?: Range[];
}
```

**Comment by jrieken** [comment]
maybe `enableFileComments` or `allowFileComments`

**Comment by alexr00** [comment]
@gjsjohnmurray I see you thumbs-upped this proposal. Is this something you're interested in using? It's been around a while so I'd like to finalize it, but we don't have any 3rd party extensions that want to use it (we almost had one, but they've since decided to use a code lens).

**Comment by gjsjohnmurray** [comment]
@alexr00 I could try using it in [one of my extensions](https://marketplace.visualstudio.com/items?itemName=georgejames.codespex), but not until next week at the earliest.

**Comment by alexr00** [comment]
@gjsjohnmurray there's no rush at all! If you end up trying it out at some point I would appreciate any feedback.
