### ISSUE TITLE
Replace In File very Slow For Many Replacements

### ISSUE THREAD

**Issue by mattbierner** [Microsoft/vscode#21434]
- VSCode Version: 1.10-insiders b2a55bd66eb60af11c60ddd61b7581538b216051
- OS Version: Mac OS 10.11.6

**Steps to Reproduce**

1. Open this 4.5mb json file in VSCode: https://raw.githubusercontent.com/zeke/cmu-pronouncing-dictionary/master/index.json
2. Perform a simple text replacement, such as `"` to `'`

**Bug**
This hangs the entire UI for about 15 seconds. For comparison, in completely non-scientific testing:

* Text Edit and Text Wrangler can do the same in well under a second.
* Text Mate takes about 7 seconds
* Atom - ??? but over 2 minutes

**Suggested Fixes**
* Investigate why this hangs the UI instead of just freezing the editor
* Show some sort of indicator while the operation is taking place. Right now, it feels like the app has crashed
* Investigate improving find/replace performance in files

**Comment by roblourens** [comment]
FYI @Tyriar related to your issue?

**Comment by Tyriar** [comment]
I had a case of a regex search the other day where it would crash VS Code, we should have some safety checks in place to make sure it doesn't lock up the UI. /cc @sandy081

**Comment by sandy081** [comment]
@Tyriar Sorry I do not understand above comment. May I know what regex search you are mentioning about?
