### ISSUE TITLE
Input method of the problem and vue file

### ISSUE THREAD

**Issue by linmodev** [Microsoft/vscode#21430]
- VSCode Version: Code - Insiders 1.10.0-insider (256d76fed7947e7289f921df10658d7a69233b65, 2017-02-22T07:04:54.544Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-class-suggestions|AndersEAndersen|1.0.3|
|EditorConfig|EditorConfig|0.3.4|
|output-colorizer|IBM|0.0.11|
|html-css-class-completion|Zignd|1.0.3|
|theme-atom-one-dark|andischerer|0.0.1|
|vscode-color|anseki|0.2.3|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.6|
|vscode-dash|deerawan|1.3.0|
|githistory|donjayamanne|0.1.5|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.0.33|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|auto-rename-tag|formulahendry|0.0.11|
|terminal|formulahendry|0.0.7|
|Theme-Brogrammer|gerane|0.0.3|
|path-autocomplete|ionutvmi|1.4.1|
|webpack|jeremyrajan|1.0.0|
|docthis|joelday|0.4.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|sublime-keybindings|ms-vscode|1.9.2|
|debugger-for-chrome|msjsdiag|2.5.3|
|vetur|octref|0.3.8|
|vuehelper|oysun|0.1.0|
|seti-icons|qinjia|0.1.3|
|view-in-browser|qinjia|0.0.5|
|babelrc|waderyan|1.0.0|
|webpack-progress|wk-j|0.0.8|

---

Steps to Reproduce:

1.In Chinese and English input method when switching, im always jump around, and 
2.Please increase support for the vue file.

**Comment by mjbvz** [comment]
Can you please describe the bug better or capture a gif of the issue?

Also, does this still repo if you disable all extensions by launching code with `--disable-extensions`?

Thanks

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this
