### ISSUE TITLE
an issue with my editor

### ISSUE THREAD

**Issue by propking123** [microsoft/vscode#214336]
Type: <b>Performance Issue</b>

I have been using vs code for well few months and I have made a few prototype websites but a few days ago my editor just somehow started gliching and then all the themes i downloaded were well gone the file had icons based on the languages but it was also gone and in html suddenly I coudn't link a file of html to css and my codes just stopped working so please fix this and this all just happened randomly it all happened when I made a new folder for my new website.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i3-1215U (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.68GB (0.48GB free)|
|Process Argv|--crash-reporter-id b25bf713-791b-49af-a6a7-2bb3c0ec5e1f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   127	  7216	code main
    1	    62	  5476	window [2] (Issue Reporter)
    1	   174	 10808	   gpu-process
    0	   116	 12216	shared-process
    0	   142	 15112	extensionHost [1]
    0	    53	  5492	     "C:\Users\PROMISE NZUBE\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\PROMISE NZUBE\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=15112
    0	    71	 13544	     "C:\Users\PROMISE NZUBE\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\PROMISE NZUBE\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=15112
    0	    86	 15640	fileWatcher [1]
    0	    41	 19760	   utility-network-service
    0	    29	 21812	   crashpad-handler
    0	   283	 22048	window [1] (xplore.html - xplore - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (xplore.html - xplore - Visual Studio Code)
|    Folder (xplore): 4 files
|      File types: png(3) html(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
vscode-intelephense-client|bme|1.10.4
vscode-html-css|ecm|2.0.9
codespaces|Git|1.16.22
css-snippets|joy|1.0.4
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
notepadplusplus-keybindings|ms-|1.0.7
LiveServer|rit|5.7.9
bootstrap4-vscode|the|6.1.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.34.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
666c4381:31064718
chatpanelt:31048053
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecationcf:31061161
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by aeschli** [comment]
We need reproducible steps to be able to investigate...

**Comment by propking123** [comment]
> We need reproducible steps to be able to investigate...

umm ok i will send screenshots

**Comment by propking123** [comment]
![Screenshot 2024-06-06 163807](https://github.com/microsoft/vscode/assets/164385366/26e453b3-c94c-40a9-8956-35ea64134382)
![Screenshot 2024-06-06 163837](https://github.com/microsoft/vscode/assets/164385366/1ae7af67-6a5f-43a1-b00f-ef9692e9f314)
These are my code files
![Screenshot 2024-06-06 164006](https://github.com/microsoft/vscode/assets/164385366/aace0e0f-bec9-46a8-8df3-cbbfb1180dc0)
This is my website and if you look at the screenshot of my code you will see that the symbols of my files, their symbols don't match the languages.
Also, the themes I installed are missing now I only have the basic ones.
![Screenshot 2024-06-06 164358](https://github.com/microsoft/vscode/assets/164385366/f77de0db-e718-4ea6-ae7b-91b461e497ee)

**Comment by propking123** [comment]
please help to fix this and I had also uninstalled it and reinstalled it but still the same thing

**Comment by aeschli** [comment]
Use the command  `Preferences > File Icons` to configure file icon theme with different file icons.
Install new themes in the Extensions viewlet.
You should not loose them unless you uninstall them or switched to a different profile

**Comment by propking123** [comment]
Thanks
