### ISSUE TITLE
Double-clicking on a `SourceControlHistoryItemChange` of a non-git SCM extension fails to open diff editor

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#214387]
This code assumes that the uris of the `SourceControlHistoryItemChange` have a query element consisting of a JSON string representation of a two-property object:

https://github.com/microsoft/vscode/blob/a003d5fb8d6d026b5e0019ed06b8ee864acfa6db/src/vs/workbench/contrib/scm/browser/util.ts#L77-L80

I think the code should be conditional on `uri.scheme === 'git'`

**Comment by lszomoru** [comment]
Closing this issue as this piece of code has been removed.
