### ISSUE TITLE
闪烁

### ISSUE THREAD

**Issue by Mango-mao** [Microsoft/vscode#21438]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|typescript-react-snippets|abotteram|0.1.9|
|html-snippets|abusaidm|0.0.18|
|npm-intellisense|christian-kohler|1.2.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-express|Compulim|0.0.5|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.0.32|
|auto-rename-tag|formulahendry|0.0.11|
|vscode-auto-open-markdown-preview|hnw|0.0.3|
|backbone-js-snippets|ioanaapetrei|0.0.1|
|redux-snippets|jameshrisho|0.0.1|
|docthis|joelday|0.3.9|
|spellcheck|JuliaBay|1.1.4|
|vscode-codemetrics|kisstkondoros|1.1.6|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|debugger-for-chrome|msjsdiag|2.4.2|
|emoji|Perkovec|0.0.3|
|vscode-css-peek|pranaygp|1.2.4|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.1.2|
|background|shalldie|1.1.9|
|stylelint|shinnn|0.22.0|
|es6-mocha-snippets|spoonscen|0.0.2|
|guides|spywhere|0.6.1|
|react-beautify|taichi|0.3.0|
|react-redux-es6-snippets|timothymclane|2.0.2|
|jsx|TwentyChung|0.0.1|
|vscode-react-native|vsmobile|0.2.5|
|stylint|vtfn|0.0.2|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.2.0|
|ReactSnippets|xabikos|1.2.0|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please provide information about the issue, perhaps a gif showing what is going wrong

Thanks
