### ISSUE TITLE
Certain fonts are not applied when set

### ISSUE THREAD

**Issue by DanielHZhang** [microsoft/vscode#214380]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.90.0 (Universal) Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
- OS Version: macOS 14.5

Steps to Reproduce:

1. Download the Iosevka font (e.g. `brew install font-iosevka`)
2. Set `"editor.fontFamily": "Iosevka Extended"` in your `settings.json`

Expect that the font be applied to the editor, but it was not applied. This behaviour does occur in v1.89.1; the font gets applied correctly in the previous VSCode version.

**Comment by king724** [comment]
I am experiencing the same issue.

**Comment by swlody** [comment]
**https://github.com/microsoft/vscode/issues/212511**

**https://github.com/microsoft/vscode/issues/214390**

**Comment by deepak1556** [comment]
Will merge to https://github.com/microsoft/vscode/issues/212511, please follow that issue for updates. Thanks!
