### ISSUE TITLE
The JS/TS server crashed 5 times.

### ISSUE THREAD

**Issue by bacaxnot** [microsoft/vscode#214372]
Type: <b>Bug</b>

The JS/TS server crashed 5 times. I'm sending this because there was a prompt to report it, so maybe it's useful.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:32.757Z)
OS version: Darwin arm64 23.2.0
Modes:
Remote OS version: Linux x64 6.5.0-1021-azure
Remote OS version: Linux x64 6.5.0-1021-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id a4a1d836-7e10-4717-96d5-955ded1efe1d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: effective doodle|
|OS|Linux x64 6.5.0-1021-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (4 x 2808)|
|Memory (System)|15.61GB (10.01GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: justpaid-frontend|
|OS|Linux x64 6.5.0-1021-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (4 x 3243)|
|Memory (System)|15.61GB (2.24GB free)|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
emojisense|bie|0.10.0
es7-react-js-snippets|dsz|4.4.3
auto-close-tag|for|0.5.15
codespaces|Git|1.16.22
fluent-icons|mig|0.0.18
symbols|mig|0.0.17
remote-containers|ms-|0.362.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
vscode-speech|ms-|0.8.0
pdf|tom|1.2.2
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
better-comments|aar|3.0.2
file-nesting|ant|1.1.2
emojisense|bie|0.10.0
github-markdown-preview|bie|0.3.0
markdown-preview-github-styles|bie|2.0.4
vscode-tailwindcss|bra|0.10.5
npm-intellisense|chr|1.4.5
vscode-eslint|dba|2.4.4
javascript-ejs-support|Dig|1.3.3
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|2.0.9
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
figma-vscode-extension|fig|0.3.5
auto-close-tag|for|0.5.15
codespaces|Git|1.16.22
copilot|Git|1.199.0
copilot-chat|Git|0.15.2
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.88.1
todo-tree|Gru|0.0.226
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.25.1
color-picker|Mar|1.0.0
rainbow-csv|mec|3.12.0
template-string-converter|meg|0.6.1
fluent-icons|mig|0.0.18
symbols|mig|0.0.17
vscode-docker|ms-|1.29.1
test-adapter-converter|ms-|0.1.9
vscode-typescript-next|ms-|5.5.20240505
vsliveshare|ms-|1.0.5918
vscode-auto-restart-typescript-eslint-servers|neo|0.0.5
docthis|oou|0.8.2
vscode-css-peek|pra|4.4.1
html-to-jsx|ria|0.0.1
vs-code-prettier-eslint|rve|6.0.0
console-ninja|Wal|1.0.323
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
pretty-ts-errors|Yoa|0.5.4
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
showvideot:31016892
chatpanelc:31048052
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecationcf:31061161
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
