### ISSUE TITLE
Suggestion for a small adjustment to the command center/command palette

### ISSUE THREAD

**Issue by SebastianMantey** [microsoft/vscode#214324]
**Current Situation:**

If I understand it correctly, then the command center allows you to quickly access all of VS Code's functionality. To open it you can click into the search field in the title bar. Then, a drop-down list opens, where the command “Go to file” is automatically selected, i.e. you can just start typing to search for files.

If you type “>”, you access the “Show and Run Commands”-command, i.e. the command palette. And as the name suggests, you can execute many different commands with the command palette. So, if you would want to define it, you would say that it allows you to quickly access all of VS Code's functionality.

Therefore, even though the command palette is a subset of the command center, you would give it essentially the same definition. Conceptually, this doesn’t really make sense to me and seems redundant.

**My Suggestion:**

Simply switch up the “Go to file” and “Show and Run Commands” commands (the positions in the drop-down list, the symbols to access them and the keyboard shortcuts). This way, if you click into the search field, the command palette is automatically selected, i.e. you can just start typing to access the different commands.

And then, if you want to quickly access a specific type of command, e.g. for opening files, you can do that by typing the symbol “>” (instead of typing the actual command).

Conceptually, this would make more sense to me because this way you simply open the command palette to access all of VS Code's functionality. And then, within the command palette you can use specific symbols, e.g. ">", to quickly access specific types of commands.

PS: The keyboard shortcuts wouldn't really need to change because that is something that you can easily adjust yourself within VS Code

**Comment by gjsjohnmurray** [comment]
Changing the order of the options will disturb muscle memory for existing users.

@SebastianMantey I suggest that instead of using the mouse to click into the field, press F1 or Ctrl/Cmd+Shift+P. That way your hands are already on the keyboard ready to start typing the command you want.

**Comment by SebastianMantey** [comment]
@gjsjohnmurray 

I’m actually using the keyboard shortcut for the command palette. It’s just that I am currently working on a YouTube tutorial for VS Code, and I have the feeling that the “command center” as a component of the UI is superfluous. One could, so to say, refactor it out of the UI and don’t loose anything. It is, as far as I am aware, also never mentioned in the documentation. Only the command palette gets mentioned.

So, my suggestion is more geared towards new users of VS Code. But I would also say that, if one keeps the keyboard shortcuts Ctrl/Cmd+P and Ctrl/Cmd+Shift+P as they are, and only implements the other changes that I suggested, then the muscle memory of existing users wouldn’t be affected.
