### ISSUE TITLE
VSCode connects to Linux using key and saves key password

### ISSUE THREAD

**Issue by luweijun1992** [microsoft/vscode#214391]
Now I need to enter the key password when connecting to Linux.
Can I save the key password so that I don't have to enter it every time?
![image](https://github.com/microsoft/vscode/assets/58923704/545dface-dbd6-451d-910c-316b234629eb)

**Comment by roblourens** [comment]
https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent

**Comment by luweijun1992** [comment]
> https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent

I have followed the steps to enable ssh-agent and restarted vscode.
But `ssh-add -l` still cannot see the information
![image](https://github.com/microsoft/vscode/assets/58923704/e62e5f65-926e-41c8-a757-b7b315360c42)

**Comment by luweijun1992** [comment]
> https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent

@roblourens 
What else do I need to set up?
I still need to enter the key password every time I open it.

![image](https://github.com/microsoft/vscode/assets/58923704/452a1645-8889-42c2-9cde-082d5303822f)

![image](https://github.com/microsoft/vscode/assets/58923704/b4c0eced-a8b5-4bc3-b6a7-3dd13ecaa237)
