### ISSUE TITLE
Integrated Terminal is unusable with themed/customized PowerShell prompt

### ISSUE THREAD

**Issue by dannymcgee** [microsoft/vscode#214386]
Type: <b>Bug</b>

### Repro

1. Follow the instructions [here](https://ohmyposh.dev/docs/installation/windows) to install Oh My Posh for Windows PowerShell
2. Configure Windows PowerShell to use Oh My Posh
   - Create or edit a [PowerShell Profile](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-5.1#profile-types-and-locations)
   - Add this line to the top of the file:
   ```powershell
   oh-my-posh init pwsh | Invoke-Expression
   ```
3. Open Windows Powershell in VS Code's integrated terminal

### Summary

As of VS Code 1.90.0, Windows PowerShell 5.1 is unusable in the integrated terminal with a custom prompt theme (e.g., one provided by Oh My Posh). The integrated terminal seems to pre-fill the `stdin` with a bunch of garbage text that can't be deleted. Trying to submit any command fails due to this pre-filled input.

### Additional info

- This is occurring on Windows PowerShell 5.1. I have not tested on PowerShell 7+.
- `oh-my-zsh` running in a WSL/Ubuntu shell seems to be unaffected.
- Disabling the new `terminal.integrated.rescaleOverlappingGlyphs` setting does not resolve the issue. That's the only documented terminal change I could find in the release notes, but let me know if there's anything else I could try.

#### VS Code v1.90.0

![terminal-vscode-1_90_0](https://github.com/microsoft/vscode/assets/13191586/94b6b530-227d-4df3-a70c-ccff9b118721)

#### Windows Terminal

![windows-terminal](https://github.com/microsoft/vscode/assets/13191586/80c05b6e-8316-4964-9f18-4e14c10673b3)

### Auto-filled info from the issue reporter

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (42.21GB free)|
|Process Argv|C:\\Users\\danny\\OneDrive\\Documents\\WindowsPowershell --crash-reporter-id 81b942da-7304-4262-a11f-91f272e44c3f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by neilenns** [comment]
Yep, can confirm I'm having the same issue. This is what I get in integrated terminal:

![image](https://github.com/microsoft/vscode/assets/9524118/005c6f1a-98e6-48e7-afc5-d729064b3a86)

This is the same folder in Windows Terminal:

![image](https://github.com/microsoft/vscode/assets/9524118/d0a65ddc-e142-41aa-904f-d3e9865425af)

I'm using _Cascadia Code NF_ with Oh My Posh. 

Version: 1.90.0 (user setup)
OS: Windows_NT x64 10.0.22631

**Comment by desiwalle** [comment]
Same issue here - using Fira Code NF on Win 11.

![image](https://github.com/microsoft/vscode/assets/44332231/3b3983d9-ae11-4caf-9c37-f2eab291eaaf)

**Comment by xoxoooooo** [comment]
I'm having the same issue here~ 

版本: 1.90.0 (user setup)
提交: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
日期: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

![image](https://github.com/microsoft/vscode/assets/24760591/ba27b683-f9b0-43ec-937c-893ce4d26538)

**Comment by Joonbie** [comment]
![image](https://github.com/microsoft/vscode/assets/163788771/cc4c4503-64b4-414f-9716-5831e59e3531)
Same issue here on win 11
Using Fira Code NF

**Comment by dreampasssser** [comment]
Same bug too on Win11.
I'm using `MesloLGM NF` font and `powerlevel10k_rainbow` theme.

![图片](https://github.com/microsoft/vscode/assets/24749464/1e60100e-8f24-4ccb-abd1-d68b6dbedb1e)

```
版本: 1.90.0 (system setup)
提交: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
日期: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by xftxyz2001** [comment]
Same issue here on Win 11. Terminal loading and command execution seem to be much slower.

PowerShell:
```
PowerShell 7.4.2
```

PowerShell_profile:
```
Import-Module oh-my-posh
Set-Theme Paradox
```

vscode:
```
Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.90.0 Chrome/122.0.6261.156 Electron/29.4.0 Safari/537.36
```

![image](https://github.com/microsoft/vscode/assets/22099765/3fe6cf81-2557-4d61-9bc6-8e2722c808c2)

**Comment by fernandogprieto** [comment]
I have the same problem[
![Screenshot 2024-06-05 185539](https://github.com/JanDeDobbeleer/oh-my-posh/assets/113651560/b36122eb-9e9a-4809-a7ca-6fd9d0216afc)
](url)

**Comment by imlinhanchao** [comment]
I have the same issue. and disable `terminal.integrated.shellIntegration.enabled` will fixed it.

**Comment by JanDeDobbeleer** [comment]
> I have the same issue. and disable terminal.integrated.shellIntegration.enabled will fixed it.

This is an issue with shell integrations indeed. Something changed and the prompt hijacking turns some ANSI sequences on literal strings.

**Comment by ravaga** [comment]
Same issue on Windows 10 when using Oh-my-posh.

**Comment by fernandogprieto** [comment]
Wtf this guy close this and the original post has the same problem 1 month ago without solution

**Comment by meganrogge** [comment]
@fernandogprieto we are planning to address the bug, just closing this to consolidate the issues

**Comment by juliusl** [comment]
@meganrogge is there a PR up already?

**Comment by meganrogge** [comment]
Not yet
