### ISSUE TITLE
I cant write my commit message on the little box

### ISSUE THREAD

**Issue by shadowforce78** [microsoft/vscode#214374]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.1
- OS Version: Windows 11 23H2

Steps to Reproduce:
![image](https://github.com/microsoft/vscode/assets/65604210/e1048866-64a8-44c9-9396-6b75602f7487)

BTW if I use the same github account but on a different computer it works

**Comment by shadowforce78** [comment]
after updating my software to 1.89.1 I still cant write my commit message

**Comment by gjsjohnmurray** [comment]
Please check your `git.showCommitInput` setting.

**Comment by shadowforce78** [comment]
Mhh where can I see this ?

**Comment by gjsjohnmurray** [comment]
> Mhh where can I see this ?

[Settings Editor](https://code.visualstudio.com/docs/getstarted/settings)

**Comment by shadowforce78** [comment]
Oh thanks
![image](https://github.com/microsoft/vscode/assets/65604210/72a6a960-ddb0-403b-909f-60c3c894ec9d)
it was disabled, by enabling it the message commit showed up
thank you very much
