### ISSUE TITLE
HTML Preview: use custom CSS for scrollbars

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2143]
The markdown preview uses its own CSS for styling scrollbars so that they look similar to the scrollbars in VS Code and not like the ugly native ones. The CSS is defined for every theme we have starting here: https://github.com/Microsoft/vscode/blob/master/src/vs/languages/markdown/common/markdownWorker.ts#L38

There is also some CSS defined in https://github.com/Microsoft/vscode/blob/master/src/vs/languages/markdown/common/markdown.css that we maybe should take into the HTML preview:
* size images to a maximum of 100% so that they do not cause horizontal scrolling
* styling for anchors
* styling for focused elements (when you tab around)

The rest of the rules are just for making markdown look better and probably does not apply for the raw HTML preview.

@jrieken fyi

**Comment by jrieken** [comment]
agreed

**Comment by bpasero** [comment]
Nice
