### ISSUE TITLE
Typescript and Javascript Language Features are not working

### ISSUE THREAD

**Issue by nvuhung** [microsoft/vscode#214368]
Type: <b>Bug</b>

I don't know how to reproduce it. But the Typescript and Javascript Language Features are not working. I tried installing the old VSCode version, installing typescript version 5.3, uninstalling vscode, reinstalling and completely removing all extensions, restarting the computer but it still doesn't work. I tried using Cursor (code editor similar to VS Code) and got the same error.

I tried adding this config to settings.json but it didn't work:
```
  "typescript.tsserver.experimental.useVsCodeWatcher": false,
```

<img width="1565" alt="image" src="https://github.com/microsoft/vscode/assets/11483168/aac64299-781f-4d38-8cc6-9ee91f38da7a">

<img width="1373" alt="image" src="https://github.com/microsoft/vscode/assets/11483168/42e803c8-1f4d-4adc-a663-54b90095d2e1">

It is blocking both Source Control and other extensions

<img width="505" alt="image" src="https://github.com/microsoft/vscode/assets/11483168/ba146ee9-41b9-4146-ba6e-2eba2903effd">

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin x64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|32.00GB (13.80GB free)|
|Process Argv|--crash-reporter-id 05b74417-ec4e-42ab-a8e9-4ed559b211f3 --inspect-extensions=23085 --crash-reporter-id 05b74417-ec4e-42ab-a8e9-4ed559b211f3|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
