### ISSUE TITLE
open visual stadio code  ,CPU will 100%

### ISSUE THREAD

**Issue by rimtd** [Microsoft/vscode#21431]
- VSCode Version:1.9.1
- OS Version:window 10 ent or windows server 2012 R2 datacenter

Steps to Reproduce:

1.when i create my development virual mathine in windows server 2012 R2 with hyper-v ,and Install window 10 or windows server 2012 R2 at virual mathine ,then Install visual stadio code ,successful
2.when i open the  visual stadio code application in window 10 or windows server 2012 R2 virual mathine,the CPU will go 100%

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by rimtd** [comment]
see it
![qq 20170226212918](https://cloud.githubusercontent.com/assets/1570512/23340140/282d8236-fc6c-11e6-85fa-550a2cf1acc1.png)

**Comment by bpasero** [comment]
@rimtd is that a single core CPU environment?

**Comment by rimtd** [comment]
multiple  core CPU(XEON e3 1230 v3)，but  virual mathine ,assign one CPU，you can think it's single core CPU

**Comment by bpasero** [comment]
Ok this is https://github.com/Microsoft/vscode/issues/17097 then
