### ISSUE TITLE
1.90 closes immediately after startup with latest snap refresh

### ISSUE THREAD

**Issue by cornmonger** [microsoft/vscode#214392]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0
- OS Version: Ubuntu 24.04 (x86_64)

Steps to Reproduce:

I have Code installed via Snap on Ubuntu. It started crashing on startup as soon as it updated via the automatic snap store refresh (a few moments ago). 

```bash
$ code --version
1.90.0
89de5a8d4d6205e5b11647eb6a74844ca23d2573
x64

$ snap info code
[...]
snap-id:      Ht0aUHi7ofh9Fbwh6m7jUN2pAy6kzBiu
tracking:     latest/stable
refresh-date: today at 18:31 PDT
channels:
  latest/stable:    89de5a8d 2024-06-05 (160) 327MB classic
  latest/candidate: ↑                               
  latest/beta:      ↑                               
  latest/edge:      ↑                               
installed:          89de5a8d            (160) 327MB classic
```
It returns an exit code 0 when ran.

I've tried running it with the "New Empty Window" option from GNOME and that fails as well.

Using `snap revert` is the only thing that works so far.

I had not ran a system (apt) upgrade recently, so I tried that along with a reboot, to no avail.

1. Run `code --disable-extensions`
2. Observe that Code starts up, shows a project, then closes.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/212494, please follow that issue for updates.

**Comment by aymenkrifa** [comment]
Not the best solution, but this should solve it for now
`snap install code --revision 159`

**Comment by Yyote** [comment]
Same issue on Ubuntu 22.04 with latest snap release

**Comment by mazzo23** [comment]
sudo snap revert code --revision 159 

works too :+1:

**Comment by buggcatcher** [comment]
Same issue here. That fix doesn't work for me tho. VS code closes immediately after being started.

**Comment by MatheusJulidori** [comment]
Seems like the problem is only with Snap version.
Installing latest version from .deb package works just fine.

Some workarounds I've found so far:
Install .deb package from [official source](https://code.visualstudio.com/download)
Run `code --in-process-gpu` on terminal
Run `code --use-gl=angle --use-angle=swiftshader`
Revert to older snap version with `sudo snap revert code --revision 159`

**Comment by pavelToman** [comment]
Same problem for me with Ubuntu 24.04.
`sudo snap revert code --revision 159` works for me, but either with `snap refresh --hold code` to prevent snap to auto update (even I do not have automatic updates enable in Software and Updates)

**Comment by ratulSharker** [comment]
I have to uninstall existing vscode first from snap store by command:

```sh
sudo snap remove code
```

then install the specific revision by:

```sh
sudo snap revert code --revision 159 --classic
```

from the vscode `settings.json`
```json

"update.showReleaseNotes": false,
"update.mode": "none",

```
to turn off the auto update.
