### ISSUE TITLE
[IntelliSense] [JavaScript] Go to Definition Doesn't Use Source Map

### ISSUE THREAD

**Issue by niedzielski** [Microsoft/vscode#21433]
- VSCode Version: v1.9.1
- OS Version: Ubuntu v16.10

Steps to Reproduce:

1. Bundle a collection of JavaScript files local to the project and generate a source mapping.
2. Import the bundle.
3. Go to definition on any symbol present in the bundle.

The expected result is to go to the definition in the local JavaScript files. The actual result is to go to the definition in the bundle.

## [Example 1](https://github.com/niedzielski/vscode-map-go-to-def) (very tiny)

1. Open test/index.js.
2. Control-click the `foo` import.

The expected result is to go to the definition of foo in src/index.js. The actual result is to go to the definition in the build product, build/index.js.

## [Example 2](https://github.com/wikimedia/applib/blob/c6b0866/test/CollapseElement.js#L7)
We transpile and bundle our code to applib.js and a corresponding map, applib.js.map. The code that is exercised by our unit tests comes from this bundle directly. This is partially due to the suggested Rollup configuration but also means the same code exercised is the same code distributed. Unfortunately, go to defintion of `applib.CollapseElement.getTableHeader` goes to the bundled code instead of the original sources under `src/`.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15063
