### ISSUE TITLE
Pixels on the entire screen

### ISSUE THREAD

**Issue by Edumorcar** [microsoft/vscode#214384]
Type: <b>Bug</b>

When I don't touch the mouse or write, the pixels don't appear. They take up the entire screen and grow slowly until everything is pixelated.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.29GB free)|
|Process Argv|--crash-reporter-id 7f26dde5-c0dd-4e26-98ef-7efa25ffaa53|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|9.8.0
path-intellisense|chr|2.9.0
prettier-vscode|esb|10.4.0
code-runner|for|0.12.2
vscode-peacock|joh|4.2.2
vscode-codemetrics|kis|1.26.1
vscode-gutter-preview|kis|0.31.2
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.6.0
pylint|ms-|2023.10.1
python|ms-|2024.8.0
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.18.41
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.13
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
pip-installer|Pet|0.0.4
material-icon-theme|PKi|5.3.0
ruby-lsp|Sho|0.7.2
code-spell-checker|str|3.0.1
vscode-stylelint|sty|1.4.0
lua|sum|3.9.1
pdf|tom|1.2.2
cmake|twx|0.0.17
errorlens|use|3.18.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
fa862199:31048878

```

</details>

**Comment by spartanatreyu** [comment]
Can you add or link to a video of this happening?

**Comment by Edumorcar** [comment]
![Screenshot 2024-06-05 194250](https://github.com/microsoft/vscode/assets/128945857/6c153ea2-96c1-43a0-9d16-4c28bb4131b3)

**Comment by justschen** [comment]
@Edumorcar have you tried when starting vs code with gpu acceleration disabled? try `code --disable-gpu` from Windows Terminal?

1. Close all instances of VS Code.
2. Open Windows Terminal.
3. Run the command `code --disable-gpu`

**Comment by Edumorcar** [comment]
![imagen](https://github.com/microsoft/vscode/assets/128945857/a7abce9e-5bc1-46f4-a161-3ec946e2cf2f)
Pixels keep appearing

**Comment by justschen** [comment]
check out this comment as well: https://github.com/microsoft/vscode/issues/124226#issuecomment-848512471


1) Do you see the issue when opening https://vscode-web-test-playground.azurewebsites.net/ on your chrome or edge browser ?
2) Do you see the issue when you have the setting either `"window.titleBarStyle": "native"` or `"window.titleBarStyle": "custom"`
3) Are you running vscode as administrator ?

**Comment by Edumorcar** [comment]
![imagen](https://github.com/microsoft/vscode/assets/128945857/381d984e-fcb0-4edb-8f87-5ae2e93c1a29)
https://vscode-web-testplayground.azurewebsites.net/, I can't log in

**Comment by deepak1556** [comment]
Please use the runtime argument to disable hw acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration. Merging to https://github.com/microsoft/vscode/issues/124226
