### ISSUE TITLE
CodeLens Position doesn't change

### ISSUE THREAD

**Issue by George-Ogden** [microsoft/vscode#214362]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.89.1
- OS Version: Debian GNU/Linux 12 (bookworm)

Steps to Reproduce:

1. create `CodeLensProvider`
2. create a CodeLens with a position
3. change the character of the position

![image](https://github.com/microsoft/vscode/assets/38294960/b5499d03-6686-497e-992a-3aed552386b5)

I can't change the position of a CodeLens. I would like to add the annotation below the line but instead, I am trying to use the next line and change the `character` so that it starts further along. 
Changing `new vscode.Position(lineno, 0);` to `new vscode.Position(lineno, 4);` seems to make no difference.

Is this possible? I get the impression that the character does nothing and perhaps this should be documented?

**Comment by George-Ogden** [comment]
> Does this issue occur when all extensions are disabled?: Yes
> 
> * VS Code Version:  1.89.1
> * OS Version: Debian GNU/Linux 12 (bookworm)
> 
> Steps to Reproduce:
> 
> 1. create `CodeLensProvider`
> 2. create a CodeLens with a position
> 3. change the character of the position
> 
> ![image](https://private-user-images.githubusercontent.com/38294960/336947483-b5499d03-6686-497e-992a-3aed552386b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDk3NTYsIm5iZiI6MTcxNzYwOTQ1NiwicGF0aCI6Ii8zODI5NDk2MC8zMzY5NDc0ODMtYjU0OTlkMDMtNjY4Ni00OTdlLTk5MmEtM2FlZDU1MjM4NmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDE3NDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3YzBkYTQ0NzZjZTBjNjkxM2MwNTI2OWNlODY4MWFiMGNhMzc4MDQyNjY1OWUwNzFjYTRmMGRlY2U3YTk1OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tH4AryLhkSvzJEvQR3wkUfgfsoj3stz54ni08I7a8KQ)
> 
> I can't change the position of a CodeLens. I would like to add the annotation below the line but instead, I am trying to use the next line and change the `character` so that it starts further along. Changing `new vscode.Position(lineno, 0);` to `new vscode.Position(lineno, 4);` seems to make no difference.
> 
> Is this possible? I get the impression that the character does nothing and perhaps this should be documented?

If I am approaching this the wrong way and should be using another part of the extension API to support displaying values and allowing the user to hover over them, please, let me know.

**Comment by jrieken** [comment]
> Is this possible? I get the impression that the character does nothing and perhaps this should be documented?

The position doesn't change the rendering of the code but is used internally for sorting/tracking. The rendering is always starting at the start and above the line

**Comment by George-Ogden** [comment]
Is this worth putting in the docs? It currently says _"The range in which this code lens is valid. Should only span a single line."_ but perhaps you can mention explicitly how the display works?
