### ISSUE TITLE
Finalize chat participant "when" clause

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#214379]
The static "when" clause on chat participants should be moved to the set of things that are finalized.

**Comment by jrieken** [comment]
@roblourens what would happen when a participant becomes "disabled" after having been interacted with? Evaluating `when` going from `false` to `true` and to `false` again

**Comment by roblourens** [comment]
It would just stop showing up in the suggest widget and you wouldn't be able to invoke it. But it can still show up in your conversation thread. Same as if you uninstall a chat extension.

**Comment by roblourens** [comment]
Verify that `"when"` can be set and used on the chat participant contribution in package.json. You can use vscode-copilot or the [sample extension](https://github.com/microsoft/vscode-extension-samples/blob/main/chat-sample) or something else.
