### ISSUE TITLE
Dropdown in settings editor does not work anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#214303]
I cannot click the dropdown anymore in settings editor:

![image](https://github.com/microsoft/vscode/assets/900690/977fa08e-c487-4011-86b2-3b5f3ce31e8d)

**Comment by rzhao271** [comment]
Unable to repro.
Which OS and commit?

**Comment by bpasero** [comment]
Caused by https://github.com/microsoft/vscode/pull/213465

**Comment by lramos15** [comment]
@remcohaszing We're going to need to revert your PR because of this. Let me know if you want to try a fix for this case.

**Comment by remcohaszing** [comment]
I pushed a fix and made sure to test this specific case manually.
