### ISSUE TITLE
Ctrl + dot prints a weird underlined e character

### ISSUE THREAD

**Issue by omermecitoglu** [microsoft/vscode#214399]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0
- OS Version: Linux x64 6.5.0-35-generic (Ubuntu 22.04)

Steps to Reproduce:

1. open any file
2. hit Ctrl + . (will print the weird character)
3. hit Ctrl + . again (will remove it)

I noticed this is happening when trying to do a quick fix action. you can hover over the error and trigger the quick fix manually but it's pretty annoying atm. I thought there is a conflict between keyboard shortcuts, removed everything else using Ctrl + dot other than quick fix, but it's still like that.

**Comment by omermecitoglu** [comment]
It doesn't happen in 1.90.1

**Comment by Zaporozhec7** [comment]
For me it happens in 1.90.1
