### ISSUE TITLE
in explorer there is not showing my project file i tried but still not getting

### ISSUE THREAD

**Issue by manish23devlopr** [microsoft/vscode#214351]
Type: <b>Feature Request</b>

Dear Team,

Please fixed my issue when i click on view to explorer there is not showing my project file details 

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<img width="948" alt="image" src="https://github.com/microsoft/vscode/assets/123832766/f7b4a152-1d38-45b8-ae08-b80361b27fa9">
![Screenshot 2024-02-13 075731](https://github.com/microsoft/vscode/assets/123832766/b6260b5b-58ef-499b-b8fd-f183edee34ae)

**Comment by lramos15** [comment]
F1 -> Reset View Locations
