### ISSUE TITLE
Theme Picker: Add interface to set as workspace theme

### ISSUE THREAD

**Issue by judfs** [microsoft/vscode#214363]
The theme picker currently only lets you set your global theme. I would like to be able to set the workspace theme from the same interface.

It is more cumbersome to open all settings, selecting the workspace tab, and finding the theme settings. The general settings ui also doesn't live update while scrolling through the options.

![image](https://github.com/microsoft/vscode/assets/39133604/c43f7f7c-4d59-4d70-9e75-eb6558433789)

The current settings gear within the picker widget is only there to open extension settings.

**Comment by aeschli** [comment]
Do you have a suggestion how we can add that option in an elegant way?
Setting the theme for a workspace is not so common and I don't want to overload the picker
