### ISSUE TITLE
Order folder by groups

### ISSUE THREAD

**Issue by sergip76** [Microsoft/vscode#21449]
It would be great to be able to order the folders by groups.

**Comment by roblourens** [comment]
Which folders and groups are you talking about?

**Comment by sergip76** [comment]
I mean folders on explorer window.
On VSCode each folder is like a project. But I'd like to group several folders (projects) under one group.

**Comment by roblourens** [comment]
It sounds like you're asking for something similar to https://github.com/Microsoft/vscode/issues/396 or #2686
