### ISSUE TITLE
BUG: No `Preferences: Configure Runtime Arguments` menu item

### ISSUE THREAD

**Issue by psnet** [microsoft/vscode#214423]
Does this issue occur when all extensions are disabled?: Yes

In release notes of 1.90 version:

![зображення](https://github.com/microsoft/vscode/assets/1023918/3159a9a5-120e-4042-a908-49f4ed5165db)

Menu `File` doesnt have that item

![зображення](https://github.com/microsoft/vscode/assets/1023918/bfdc1d09-2ef2-461e-aeb6-6bdc10d72a2c)

Version: 1.90.0 (user setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573

**Comment by gjsjohnmurray** [comment]
It's a Command Palette (F1 or Ctrl/Cmd+Shift+P) command.

**Comment by psnet** [comment]
Maybe also put this into menu `File`?

**Comment by gjsjohnmurray** [comment]
It's so rarely needed that I doubt the team will agree to a dedicated menu option.

**Comment by psnet** [comment]
Maybe you are right, let them have a look at this and then I will close this issue

**Comment by roblourens** [comment]
I agree with @gjsjohnmurray, it's not a commonly-used command.
