### ISSUE TITLE
Multi-line pastes are handled improperly when using multiple carets

### ISSUE THREAD

**Issue by aem** [Microsoft/vscode#21447]
- VSCode Version: v1.9.1
- OS Version: macOS 10.12.1

Steps to Reproduce:

1. Copy multi-line text to the clipboard
2. Create multiple carets (2 is sufficient)
3. Paste the clipboard contents

Expected behavior: the full contents of the clipboard are pasted at the location of each caret
Actual behavior: one line of the keyboard is pasted to the location of each of the carets

![vscode](https://cloud.githubusercontent.com/assets/1909883/23341572/0583a08c-fc42-11e6-8bd3-57c257c90110.gif)

**Comment by Srekel** [comment]
Personally I think that's the correct way to do it. I quite frequently find myself copying things from a certain structure to another structure. Like this:

![vscode_bug_21447](https://cloud.githubusercontent.com/assets/1578924/23341900/a1fe51e2-fc50-11e6-9aef-c6ff50b82b72.gif)

Maybe another paste command could be added to accommodate both use cases?

**Comment by aem** [comment]
Another paste command might be the proper solution, I'd argue both use cases are valid

**Comment by rebornix** [comment]
Currently we are doing differently as you expect but we already have an issue talking about it https://github.com/Microsoft/vscode/issues/4996 , let's track it there.
