### ISSUE TITLE
API: support call stacks in TestMessages

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#214488]
Currently, messages that are shown when tests fail can only be shown at a single `Location`. Often (https://github.com/connor4312/nodejs-testing/issues/37, https://github.com/microsoft/vscode/issues/214287#issuecomment-2151028322, among others) folks want to see the full call stack of the test failure.

I propose some API to add this information:

```ts
declare module 'vscode' {
	export class TestMessage2 extends TestMessage {
		/**
		 * The stack trace associated with the message or failure.
		 */
		stackTrace?: TestMessageStackFrame[];
	}

	export class TestMessageStackFrame {
		/**
		 * The location of this stack frame. This should be provided as a URI if the
		 * location of the call frame can be accessed by the editor.
		 */
		file?: Uri;

		/**
		 * Position of the stack frame within the file.
		 */
		position?: Position;

		/**
		 * The name of the stack frame, typically a method or function name.
		 */
		label: string;

		/**
		 * @param label The name of the stack frame
		 * @param file The file URI of the stack frame
		 * @param position The position of the stack frame within the file
		 */
		constructor(label: string, file?: Uri, position?: Position);
	}
}
```

**Comment by timheuer** [comment]
@connor4312 does this track that not only the stack but stack + any stdout would show in same UX? /cc @peterwald

**Comment by connor4312** [comment]
Yes, output is already trackable and associable to a test case via the `run.appendOutput` API

**Comment by peterwald** [comment]
We are using `appendOutput()` to record all stdout written by tests. In addition, the `test.fail()` is used to record the failure message and stack for each test failure.

**Comment by connor4312** [comment]
UI: https://github.com/microsoft/vscode/pull/222126

**Comment by mjbvz** [comment]
@connor4312 Just check with Joh and this looks good to move into finalized!

**Comment by connor4312** [comment]
@mjbvz do we want to bundle this with any of the other testing proposals (#212196, #126932)?
