### ISSUE TITLE
Integrated terminal loses environment variables.

### ISSUE THREAD

**Issue by Thirdwinter** [microsoft/vscode#214422]
Does this issue occur when all extensions are disabled?: Yes/No
yes

- VS Code Version: 1.90.0
- OS Version: win10 22H2 19045.4291

Steps to Reproduce:

1. When I start the integrated terminal and enter commands such as 'gcc -v (scoop installed)', they don't work, but they work in an external terminal. Similarly, I've lost the environment variables for several tools installed through scoop, making them unusable within VS Code.
2. 
![image](https://github.com/microsoft/vscode/assets/149876001/0c5296b6-6062-4599-b212-9ac667e640c2)
![image](https://github.com/microsoft/vscode/assets/149876001/db472042-581e-4b99-9e95-13f9bdb02fad)

**Comment by meganrogge** [comment]
did this work in earlier versions? what shell are you using?

**Comment by Thirdwinter** [comment]
The issue arose after updating to v1.9. The screenshot shows Nushell, and other shells such as pwsh have the same problem.

**Comment by meganrogge** [comment]
does disabling shell integration, `terminal.integrated.shellIntegration` fix it for you?

**Comment by Thirdwinter** [comment]
The issue has been fixed, possibly a random bug after a computer reboot.
