### ISSUE TITLE
Hide deprecated extensions from search

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/vscode#214440]
VSCode extension can be deprecated. If an extension is deprecated, that means:

- It shows up in search, but greyed out and a striked-through.
- It can’t be installed

Since they can’t be installed, I don’t see a reason to show them in the search results at all. All it does is push non-deprecated extensions down.

![VSCode extensions search results for _“vue”_](https://github.com/microsoft/vscode/assets/779047/4aa40eac-73b8-4aef-b3c4-5857e9bfa9e8).

I suggest to remove them from search, unless they are already installed.

**Comment by sandy081** [comment]
We want to be transparent to show the extensions even if they are installable.
