### ISSUE TITLE
Crash when launching in Ubuntu 

### ISSUE THREAD

**Issue by tmskrt** [microsoft/vscode#214402]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.0 89de5a8d4d6205e5b11647eb6a74844ca23d2573 x64
- OS Version: Ubuntu 22.04.4 LTS

[crashreport.zip](https://github.com/user-attachments/files/15604354/crashreport.zip)

Hi,
This morning when I tried to start vscode, it shows a window for a few seconds and then shuts down again without a warning. I generated a [crash report]( https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues) and attached dmp files which were located in the ```pending``` subfolder. 
Thanks for your help,
Thomas

**Comment by tmskrt** [comment]
Crash occurs with and without extensions enabled.

**Comment by tmskrt** [comment]
Also tried reinstalling:
```sudo snap remove code```
```rm ./.vscode```
```rm -rf ~/.config/Code/```
```sudo snap install --classic code```

Did not help!

**Comment by soma2000-lang** [comment]
@joyceerhl I am also facing the same issue .Kindly help

**Comment by PoLaKoSz** [comment]
Workaround: https://askubuntu.com/a/1373424/955461
```
snap revert code
```

**Comment by tmskrt** [comment]
> Workaround: https://askubuntu.com/a/1373424/955461
> 
> ```
> snap revert code
> ```

Thanks PoLaKoSz! I did not help, though: 
```error: cannot revert "code": no revision to revert to```

**Comment by preitinger** [comment]
How can we specify a working version as a snap channel if we unfortunately uninstall code for trying to re-install it?

**Comment by preitinger** [comment]
which snap revision? dc96b... is too long for a revision.

**Comment by preitinger** [comment]
> Reverting to
> 
> ```
> 1.89.1
> dc96b837cf6bb4af9cd736aa3af08cf8279f7685
> x64
> ```
> 
> fixed it for me

Thank you Perondas, but can u please explain how you exactly executed the snap revert command?

**Comment by Perondas** [comment]
> > Reverting to
> > ```
> > 1.89.1
> > dc96b837cf6bb4af9cd736aa3af08cf8279f7685
> > x64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > fixed it for me
> 
> Thank you Perondas, but can u please explain how you exactly executed the snap revert command?

The revision is ```dc96b837``` 
Id doesn't seem to be published on any channel tho, so unless snap revert works for you, I don't know how you could get it.

**Comment by Perondas** [comment]
Never mind 
```sh
snap install code --revision 159
``` 
should do it

**Comment by toancea** [comment]
For those interested, this issue doesn't seem completely new and is investigated in this other [issue](https://github.com/microsoft/vscode/issues/212494)

**Comment by KERELKO** [comment]
> Never mind
> 
> ```shell
> snap install code --revision 159
> ```
> 
> should do it

thx you, it helped

**Comment by gjsjohnmurray** [comment]
/duplicate

Pointing dups to https://github.com/microsoft/vscode/issues/204159#issuecomment-2151226947
