### ISSUE TITLE
VSCode is crashing

### ISSUE THREAD

**Issue by arthurfurtunato** [microsoft/vscode#214491]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573)
- OS Version: Ubuntu 22.04.4 LTS

Steps to Reproduce:

1. Open the terminal
2. Run 
```shell
code .
``` 
3. VSCode Open and close afterward.

**Comment by meganrogge** [comment]
I can't repro

**Comment by arthurfurtunato** [comment]
It's working now

**Comment by tolgacangoz** [comment]
How :D I have the same issue in Ubuntu 24.04.

**Comment by arthurfurtunato** [comment]
Really? Now, it's working. I don't know why

**Comment by erickduran-stx** [comment]
Same issue, still broken.

**Comment by ikskoder** [comment]
> GPU process isn't usable. Goodbye

Same problem on Ubuntu 20.04.6 LTS. AMD GPU

> If I add `--in-process-gpu` flag, it seems to work

For me it does not work as a fix

**Comment by GuySartorelli** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/214432

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/212494

You can start the application with `--use-angle=swiftshader` as workaround until fix is released.
