### ISSUE TITLE
Inline widget is hardly visible in HC themes

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#214489]
Looks like we need a border here.

![CleanShot 2024-06-06 at 10 49 24@2x](https://github.com/microsoft/vscode/assets/25163139/7bf057ca-2b1b-45a2-8465-515882926bdf)

![CleanShot 2024-06-06 at 10 50 13@2x](https://github.com/microsoft/vscode/assets/25163139/5e0feb97-26a8-4a0d-9fd8-3f31619fb8b3)

**Comment by connor4312** [comment]
The new inline chat widget looks good in HC
