### ISSUE TITLE
V1.89.1 crashes when entering a folder with a "prefs.js" file inside

### ISSUE THREAD

**Issue by sergio-costas** [microsoft/vscode#214444]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.89.1
- OS Version: Ubuntu 24.04

Steps to Reproduce:

1. Create a folder with a file called "prefs.js" that has its first line as "// -*- mode: js; js-indent-level: 4; indent-tabs-mode: nil -*-"
2. Open VSCode
3. Go to File -> Open folder
4. Navigate into the folder that contains that "prefs.js" file using double click (don't press "Select" button)
5. As soon as the user enters the folder, Code crashes.

I've been noticing this bug for several versions. It seems to have been fixed in 1.90.0, but since I didn't notice anything specific about this in the list of changes, I'm afraid that the fix was "accidental" and can reappear again in the future. That's why I fill this.

**Comment by rzhao271** [comment]
Hi @sergio-costas, sorry for the late reply.

Does the issue still occur on the latest VS Code, 1.95?

**Comment by sergio-costas** [comment]
It seems to have been fixed in 1.95. Thanks!
