### ISSUE TITLE
Git bash slow since last update

### ISSUE THREAD

**Issue by xGeekoo** [microsoft/vscode#214407]
Type: <b>Performance Issue</b>

Since the last update, the integrated git bash terminal inside vscode have a high latency (around 5 seconds) after initialize it or running a command

Disabling all extension, removing settings and reinstalling git bash didn't fix the issue

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (23.92GB free)|
|Process Argv|--crash-reporter-id 272e7d0b-09f8-4746-b771-4ed25fa88b99|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   106	 16488	code main
    0	    81	  2656	fileWatcher [1]
    0	   105	  3024	   gpu-process
    0	    93	  7788	ptyHost
    0	     5	   360	     "C:\Program Files\Git\bin\bash.exe" --init-file "c:\Users\Geekoo\AppData\Local\Programs\Microsoft VS Code\resources\app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"
    0	    11	 18240	       "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --init-file "c:\Users\Geekoo\AppData\Local\Programs\Microsoft VS Code\resources\app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"
    0	     6	  4092	     conpty-agent
    0	   101	 13804	shared-process
    0	    42	 13880	   utility-network-service
    0	   218	 16220	window [1] (settings.json - oauth2 - Visual Studio Code)
    0	   145	 16336	extensionHost [1]
    0	    96	 10356	     "C:\Users\Geekoo\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Geekoo\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=16336
    0	    89	 16060	     electron-nodejs (serverMain.js )
    0	   103	 16568	window [3] (Issue Reporter)
    0	    29	 18120	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (settings.json - oauth2 - Visual Studio Code)
|    Folder (oauth2): 6 files
|      File types: json(2) env(1) gitignore(1) js(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-tailwindcss|bra|0.10.5
vscode-eslint|dba|2.4.4
javascript-ejs-support|Dig|1.3.3
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
dotenv|mik|1.0.1
color-highlight|nau|2.8.0
material-icon-theme|PKi|5.3.0
LiveServer|rit|5.7.9
svg-preview|Sim|2.8.3
vscode-styled-components|sty|1.7.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
showvideoc:31016891
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
fa862199:31048878

```

</details>

**Comment by shivapoudel** [comment]
It's so true that Git Bash is slow. I tried the external terminal, which is as expected but the integrated terminal is slow.

**Comment by xGeekoo** [comment]
I just saw that settings "terminal.integrated.shellIntegration.enabled" to false fix the issue.
This settings seem to impact other issue related to other terminal too

https://github.com/microsoft/vscode/issues/214386

**Comment by shivapoudel** [comment]
@xGeekoo For the current situation the setting as mentioned above works well. Thanks!

**Comment by hitrust** [comment]
Also, there is another issue, some characters have being attached to python venv's name, just like below.

x1b[36m\x1b[0m\x0d\x0a$ \x1b]633\x3bB\x07(prostarlette)

**Comment by hitrust** [comment]
It added some unnecessary features, it's just fine using version 1.88.1, and turn off the update.

**Comment by rud-holmgren** [comment]
I have the same issue - and "terminal.integrated.shellIntegration.enabled" seems to fix it.

Just wondering what other implications disabling that feature may have?

**Comment by JVJimenezC** [comment]
> It added some unnecessary features, it's just fine using version 1.88.1, and turn off the update.

This fixed it for me.

My git bash was also displaying strange text and a line break before my "username@computer ~/folders/..." prompt

**Comment by Lord-Fec** [comment]
Thanks to @nbrinks, disable "shell integration" make git-bash faster!
![image](https://github.com/microsoft/vscode/assets/47498451/3859f161-5a9b-4b67-9e4b-1817e7aff327)

**Comment by kira0x1** [comment]
god.. thank you this saved me.

> I just saw that settings "terminal.integrated.shellIntegration.enabled" to false fix the issue. This settings seem to impact other issue related to other terminal too
> 
> #214386

**Comment by webgolub** [comment]
> I just saw that settings "terminal.integrated.shellIntegration.enabled" to false fix the issue. This settings seem to impact other issue related to other terminal too
> 
> #214386

Unfortunately didn't work for me.

**Comment by kira0x1** [comment]
> > I just saw that settings "terminal.integrated.shellIntegration.enabled" to false fix the issue. This settings seem to impact other issue related to other terminal too
> > #214386
> 
> Unfortunately didn't work for me.

make sure you click the delete / trash icon on the terminal and create a new one, hopefully that helps.

**Comment by James-Wilkinson-git** [comment]
Setting wouldnt save the first time had to do it a few times before it saved using the GUI, then restarted and it's back to normal.

**Comment by kira0x1** [comment]
> Setting wouldnt save the first time had to do it a few times before it saved using the GUI, then restarted and it's back to normal.

wow

**Comment by DanielTheEntomologist** [comment]
It seems that whatever VCS is doing when wrapping Bash terminal is detected as suspicious activity by my antivirus.
Haven't tried disabling the antivirus to test if it will speed-up again.

**Comment by JP-Zeta** [comment]
> Thanks to @nbrinks, disable "shell integration" make git-bash faster! ![image](https://private-user-images.githubusercontent.com/47498451/337490277-3859f161-5a9b-4b67-9e4b-1817e7aff327.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4Nzg0MzQsIm5iZiI6MTcxNzg3ODEzNCwicGF0aCI6Ii80NzQ5ODQ1MS8zMzc0OTAyNzctMzg1OWYxNjEtNWE5Yi00YjY3LTllNGItMTgxN2U3YWZmMzI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDIwMjIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNDg2YTQ4MzRiNzFiNGNiZmJmMzRhZGNiNDk0Y2IwZjhkZjJkZmJlY2RiNmIzOWYyZWU1NjhkZWU5ZTZjYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZKcQSXfDR1Q6FM99qL148L3DeLxsSAesAxjWZZo1Al4)

Thank you very much for the contribution, it worked for me, it was already giving me a headache because it took a long time to execute the code and print the message "b[0m\x0d\x0a$" at the end of it.

**Comment by ArkangelGab** [comment]
"terminal.integrated.shellIntegration.enabled"
The mentioned configuration does solve the problem. You must delete the terminal and reopen it for the changes to take effect.

**Comment by fpavlik** [comment]
Oh lord, `terminal.integrated.shellIntegration.enabled = false` helped me too! Thank you!

**Comment by dhachcar** [comment]
`terminal.integrated.shellIntegration.enabled = false` fixed for me as well!

**Comment by jessicacastro** [comment]
@xGeekoo Thanks! The `terminal.integrated.shellIntegration.enabled` as `false` worked for mee. It was driving me crazy.

**Comment by LitoHDD** [comment]
Thanks to @nbrinks for the fix. Now Git Bash works as it should in your Windows version

**Comment by hugotannus** [comment]
> Also, there is another issue, some characters have being attached to python venv's name, just like below.
> 
> x1b[36m\x1b[0m\x0d\x0a$ \x1b]633\x3bB\x07(prostarlette)

@hitrust I was having the same issue, in node.js repository.

It seems to be kind of a "leak" of characters related to the coloration of the current branch name.

That was fixed just disabling the `terminal.integrated.shellIntegration` option as suggested above.

**Comment by djkepa** [comment]
well for me still the same 😢

**Comment by Harsha21122002** [comment]
terminal.integrated.shellIntegration.enabled after diabling it you need to open new terminal seems like working now

**Comment by ivu-mawi** [comment]
I noticed that during these 5 second waits for the prompt, the Windows Defender CPU usage spikes. So, I wonder if Windows Defender exacerbates or causes the issue. I can't test that as I can't turn Defender off on my company laptop.

**Comment by adan-garley** [comment]
thanks, it worked for me too.

**Comment by aidev13** [comment]
`terminal.integrated.shellIntegration.enabled` helped me as well! Gosh, that was annoying...

**Comment by hitrust** [comment]
@hugotannus 
Thanks.
Currently, I think it's enough using version 1.88.1, then no more uncertain annoying during working.

**Comment by bztoy** [comment]
Thanks everyone here, this issue was annoying me for 2 weeks time, the suggestion by @xGeekoo and everyone helped me as well.

**Comment by nyxisnyx** [comment]
Yep, i have the issue as well. The proposed fix solved some of it, but it's still about 50% as fast as it was before

**Comment by jamesautodude** [comment]
For me even disabling the mentioned setting isn't fixing it. If I disable my server's "ConfigServer Security" then it works again, but that shouldn't be necessary and was fine being on before...

**Comment by jamesautodude** [comment]
For me, my VS Code machine's IP address was blacklisted from multiple attempts in my server security. So even when changing the mentioned setting, I still wasn't getting any connection. I had to allow my IP and disable that setting to get an actual connection again. Crazy

**Comment by jamesautodude** [comment]
This issue has came back with 1.90.2! And it's worse with disconnects and other issues. UGH
