### ISSUE TITLE
latest update on mac causing window bar to be cut off

### ISSUE THREAD

**Issue by WolfEYc** [microsoft/vscode#214465]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.0
- OS Version: Sonoma 14.5 (23F79)

Steps to Reproduce:

1. install latest vscode version for mac
![image](https://github.com/microsoft/vscode/assets/75498060/32a1f27d-68ab-4db6-a81b-295301351d06)

**Comment by WolfEYc** [comment]
As you can see, after i installed the latest version of VSCode on mac, it cut off the top bar.
The previous version did not have this bug.

**Comment by bpasero** [comment]
What settings are you using?

**Comment by deepak1556** [comment]
Can you also confirm if the issue is present with new profile, from command palette run `Profile: Create a Temporary Profile`

**Comment by WolfEYc** [comment]
![image](https://github.com/microsoft/vscode/assets/75498060/329d4796-dc5a-4e39-bd06-01f0c7caa281)
after using 
Profile: Create a Temporary Profile

**Comment by WolfEYc** [comment]
strange... after creating a temporary profile, then switching back to my "default" profile it seems to resolve the issue!

**Comment by WolfEYc** [comment]
Yall can close this if you want, but i'm curious what caused the issue in the first place.

I'm not surprised such bugs exist on the ARM chip macbook, not specifically in vscode but in general many things. I'm not a fan of Apple PCs but unfortunately my work makes us use them because it is "modern" or something. If i had my choice id have a workstation with linux mint on it.

**Comment by WolfEYc** [comment]
Oh no!

when i open a new vscode window the issue still persists

**Comment by WolfEYc** [comment]
Ok i have an update, it seems that whenever i toggle zen mode, 
then reload / (close and reopen window)
it will cause the bug!

**Comment by deepak1556** [comment]
I am unable to repro with the above steps, can you share a recording of the issue from a temporary profile. Thanks!
