### ISSUE TITLE
Quick search should not search certain files 

### ISSUE THREAD

**Issue by elieobeid7** [microsoft/vscode#214431]
In the command palette, if you type `ctrl+p` on Windows, you can search files by typing `%`

I find that much more convenient than `ctrl+shift+F`

But it's unusable because it searches everything, including `.git` files, how to exclude folders from being searched, or better yet, get it to respect `.gitignore`?

Currently, it searches everything, including files inside the `.git` folder, making this feature useless.

**Comment by gjsjohnmurray** [comment]
Please review advice at https://github.com/microsoft/vscode/wiki/Search-Issues

**Comment by elieobeid7** [comment]
@gjsjohnmurray I might have missed something, if so please let me know

As far as I can tell, the document talks about search in general (`ctrl+shift+F`) and how to exclude stuff etc.

In that case, the document doesn't address the issue I'm reporting here. `ctrl+shift+F` is working perfectly fine as expected.

This issue is not about search in general nor about `ctrl+shift+f`, this issue is strictly about searching via `ctrl+p` and then `%`

`ctrl+shift+f` does not search under any circumstances files inside .git folder nor gitignored files whereas `%s` does


I even opened a reddit question about it, just because I thought I didn't use the feature correctly, but no one could answer [my question](https://www.reddit.com/r/vscode/comments/1d5vh7g/how_to_ignore_files_in_quick_search/)

**Comment by gjsjohnmurray** [comment]
@elieobeid7 sorry, I misread your post. @andreamah has now been assigned this and will surely be able to help.

**Comment by andreamah** [comment]
Hmm, it's not supposed to search those files. What do you have for your `files.exclude` and `search.exclude` settings?

**Comment by elieobeid7** [comment]
interesting thank you, I had `files.exclude: false` for `.git` in settings.json, the issue is caused by an extension which toggles the visibility of files in file explorer. I removed that settings and the issue is solved thanks.
