### ISSUE TITLE
Setting to disable sound when using backspace in Integrated Terminal?

### ISSUE THREAD

**Issue by stoberov** [Microsoft/vscode#21441]
This could just be me, but when using the **Integrated Terminal** with _"terminal.integrated.shell.windows"_  set to **powershell.exe** and deleting characters with **backspace** there is a high-pitched, old-school **sound warning** when there are no more characters to delete back. It would be wonderful if there is a setting to disable that sound, like _"terminal.integrated.sound": "false"_

I also recorded the audio [here ](https://dl.dropboxusercontent.com/u/10976481/vscode-sound.wav)

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393

**Comment by Tyriar** [comment]
You'll need to do this by configuring PowerShell or changing the shell http://superuser.com/a/1113450

**Comment by chris-grabcad** [comment]
How about making is an option still ... and invoking that as part of creating a powershell session from vscode? - Save people having to dig.

**Comment by Tyriar** [comment]
That sort of feature should probably belong in the powershell extension https://github.com/PowerShell/vscode-powershell

**Comment by rendall** [comment]
Here's another vote for this feature to be added.  It's unpleasant and is different behavior from all other terminals.
