### ISSUE TITLE
In `argv.json` found `"disable-color-correct-rendering": true,`, is it still needed as I see related issue is closed?

### ISSUE THREAD

**Issue by psnet** [microsoft/vscode#214430]
Does this issue occur when all extensions are disabled?: Yes

In `argv.json` found `"disable-color-correct-rendering": true,`, is it still needed or can be deleted as I see related issue is closed?

![зображення](https://github.com/microsoft/vscode/assets/1023918/9aa61311-d116-493b-8a0d-2f0583725ae4)

**Comment by bpasero** [comment]
You can remove it, we no longer support it.

//cc @deepak1556 @rzhao271
