### ISSUE TITLE
vscode opens and instantly closes

### ISSUE THREAD

**Issue by therealnin3** [microsoft/vscode#214432]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0 x64
- OS Version: Ubuntu 22.04.4 LTS

Steps to Reproduce:

1. Open vs-code in any way

Last night (5 June 2024) vscode worked fine. When clicking on the vscode icon or right clicking and making a new window or using the terminal, the vscode window is displayed and then instantly closes/crashes. I uninstalled and reinstalled and rebooted. Still the same issue. 
A lot of people in the Ubuntu Store comment section (6 June 2024) all commented the same issue. 
![Screenshot from 2024-06-06 12-18-02](https://github.com/microsoft/vscode/assets/90702569/a35d6bab-7c3b-4f43-b41b-8e3c0997b72d)

**Comment by jamshaidbutt055** [comment]
temporary solution is to use 
`sudo snap revert code`

**Comment by MarcellHarmaci** [comment]
__Adding `--in-process-gpu` to the starter command can be a workaround as well.__

I tried a few things by starting vscode from the terminal and opening an emtpy `tmp` folder like so, to isolate the problem:
```
code -n tmp --verbose --log debug --disable-extensions --no-sandbox
```

I got errors like this in the log:
```
MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: iris
[main 2024-06-06T10:42:00.069Z] [SharedProcess] IPC ready
[main 2024-06-06T10:42:00.069Z] Main->SharedProcess#connect: connection established
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load swrast driver
[16983:0606/124200.072515:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
[16781:0606/124200.075411:WARNING:gpu_process_host.cc(1015)] Reinitialized the GPU process after a crash. The reported initialization time was 0 ms
[main 2024-06-06T10:42:00.090Z] [File Watcher (node.js)] Request to start watching: /home/<user>/.config/Code/User (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),/home/<user>/.config/Code/User/settings.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
[main 2024-06-06T10:42:00.092Z] [File Watcher (node.js)] Started watching: '/home/<user>/.config/Code/User'
[main 2024-06-06T10:42:00.093Z] [File Watcher (node.js)] Started watching: '/home/<user>/.config/Code/User/settings.json'
[main 2024-06-06T10:42:00.112Z] [SharedProcess] Overall ready
[main 2024-06-06T10:42:00.117Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[16781:0606/124200.134992:INFO:CONSOLE(655)] "%cTRACE color: #888 Renderer->SharedProcess#connect: connection established", source: vscode-file://vscode-app/snap/code/160/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (655)
[main 2024-06-06T10:42:00.162Z] [File Watcher (node.js)] Request to start watching: /home/<user>/.vscode/extensions (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),/home/<user>/.vscode/extensions/extensions.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
[main 2024-06-06T10:42:00.162Z] [File Watcher (node.js)] Started watching: '/home/<user>/.vscode/extensions'
[main 2024-06-06T10:42:00.163Z] [File Watcher (node.js)] Started watching: '/home/<user>/.vscode/extensions/extensions.json'
[main 2024-06-06T10:42:00.234Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[16781:0606/124200.242375:ERROR:gpu_process_host.cc(993)] GPU process exited unexpectedly: exit_code=133
[16781:0606/124200.242394:WARNING:gpu_process_host.cc(1364)] The GPU process has crashed 6 time(s)
[16781:0606/124200.242404:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.
```

The log showed some gpu error, so added `--in-process-gpu` and the IDE started fine. Gradually removing the other options and keeping `--in-process-gpu` was still okay.

**Comment by mastersans** [comment]
> temporary solution is to use `sudo snap revert code`
> 
> or you can just installed deb package of 1.90

@jamshaidbutt055 i have 1.90.0 installed but its still crashing

**Comment by MarcellHarmaci** [comment]
> > temporary solution is to use `sudo snap revert code`
> > or you can just installed deb package of 1.90
> 
> @jamshaidbutt055 i have 1.90.0 installed but its still crashing

1.90.0 is the version, that crashes.

**Comment by misrolox** [comment]
I have the same problem. Downgrading to 1.89 does the trick.

code --verbose output:
[vscode_crash.txt](https://github.com/user-attachments/files/15619036/vscode_crash.txt)

**Comment by kemalcem** [comment]
thnx to @MarcellHarmaci **--in-process-gpu** is a work around solution for the time being.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/212494

You can start the application with `--use-angle=swiftshader` as workaround until fix is released.

**Comment by tkossak** [comment]
Same problem here.
Linux Manjaro, vscode v1.90 installed from `aur/visual-studio-code-bin`.
Even though I removed `~/.vscode`, it didnt' start working at the begining, but after several restarts it did. I restored old `~/.vscode` and for now it works, so not sure what fixed it exactly.

**Comment by leonardoprimieri** [comment]
> thnx to @MarcellHarmaci **--in-process-gpu** is a work around solution for the time being.

this one worked for me, thanks
