### ISSUE TITLE
keep Loading

### ISSUE THREAD

**Issue by ManivelManikandan** [microsoft/vscode#214476]
Type: <b>Performance Issue</b>

i can't open any file it's loading 

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:34:48.028Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 4fd0d58e-194c-4ebc-b9bb-e68872831dbf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    5	   164	  4631	code main
    6	    66	  4634	   gpu-process
    0	    33	  4635	   utility-network-service
    4	   254	  4636	window [1] (README.md — testvuetify)
    0	   131	  4953	extensionHost [1]
    0	     0	  5310	     <defunct>
    0	    90	  4964	shared-process
    0	     0	  5376	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    49	  4965	fileWatcher [1]
    0	    57	  4966	ptyHost
    0	     0	  4970	     /bin/zsh -il
    0	    74	  5322	extensionHost [1]
    0	    98	  5325	extensionHost [1]
    0	   131	  5326	extensionHost [1]
    0	    49	  5339	     electron-nodejs (start-server.js )
    0	    98	  5370	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (README.md — testvuetify)
|    Folder (testvuetify): 52 files
|      File types: js(10) vue(6) css(4) json(3) svg(2) ico(2) html(2)
|                  browserslistrc(1) editorconfig(1) gitignore(1)
|      Conf files: jsconfig.json(1) package.json(1);
```

</details>
<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.9.0
cssrem|cip|3.1.1
vscode-eslint|dba|2.4.4
gitlens|eam|15.0.4
vscode-highlight|fab|1.9.0
vscode-pull-request-github|Git|0.88.1
vue-snippets|hol|1.0.4
vue-nuxt-snippets|mat|0.8.0
vscode-language-babel|mgm|0.0.40
csdevkit|ms-|1.6.8
csharp|ms-|2.31.19
vscode-dotnet-runtime|ms-|2.0.5
vscodeintellicode-csharp|ms-|2.1.11
vscode-styled-components|sty|1.7.8
vscode-stylelint|sty|1.4.0
volar|Vue|2.0.8
vuetify-vscode|vue|0.2.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by DonJayamanne** [comment]
Sorry you are running into this, and sorry for not getting back to you on this issue.
Are you still running into this issue, please can you share a screenshot of the message.

**Comment by ManivelManikandan** [comment]
after re-install Vs code working good... Thanks
