### ISSUE TITLE
Ask to add command line tool for launching from terminal

### ISSUE THREAD

**Issue by aayushkapoor206** [Microsoft/vscode#2144]
I would be great if at first run, VSCode asks to install a CLI tool to directly launch it from the command line instead of manually adding it to the script.

**Comment by aayushkapoor206** [comment]
Will this be implemented in the future releases?

**Comment by joaomoreno** [comment]
This is now fixed:

- Windows: you can set up the launcher script at install time
- OS X: there are now actions in the command palette to install the launcher in the PATH
- Linux: deb and rpm packages are coming which will place Code in the PATH

**Comment by Tyriar** [comment]
Related https://github.com/Microsoft/vscode/issues/4426
