### ISSUE TITLE
Degrees character '°' is corrupted on saving a file

### ISSUE THREAD

**Issue by G109B** [Microsoft/vscode#21446]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|format-php|Kasik96|1.1.2|
|cpptools|ms-vscode|0.10.1|

---

Steps to Reproduce:

1. Load a source file containing, for example, strchr(str,'°'), for editing.
2. Save file with cntl-s, without touching this statement.
3. Re-load file to find that '°' has been changed to hieroglyphics.
4. VS2015 does not do this, and MSVC 6.0 compiles it into something other than the degrees symbol.
5. If VSCode is then used to examine this line of code, the single quotes contain a question mark inside a diamond, and if this is then changed to '°' by VSCode it then seems to persist OK.

**Comment by roblourens** [comment]
I don't see this. What is the encoding of the file? (right side of the status bar)

**Comment by G109B** [comment]
UTF-8. It was created on WinXP with MSVC 6.0 and I am using VSC on it on Win10. I corrected it on XP, copied it to my Win10 system, and the problem is plain to see.
	if ((t=strchr(s,'#')) || (t=strchr(s,'�'))) *t = '~';

**Comment by G109B** [comment]
Same line same file using VS2015:
	if ((t=strchr(s,'#')) || (t=strchr(s,'°'))) *t = '~';

**Comment by Pajn** [comment]
What encoding do you see in VS2015? It sound like you uses different encodings in different editors.

**Comment by G109B** [comment]
"Use Multi-Byte Character Set"
This is not something I have chosen, or been aware of, it is just the app defaults.
Is there a way to change VSCode to Multi-byte ?

**Comment by G109B** [comment]
OK, I googled it, and VSCode is incompatible with VS2015 because VS2015 recognizes a "Multi-Byte" character set and chooses it in preference to UTF, whereas VSCode can only use Unicode. I suppose VS2015 users never bother with VSCode, and I guess I will have to join them.

**Comment by CoenraadS** [comment]
Multi-byte is a very old encoding. If you are porting you app from XP to Windows 10 (and upgrading MSVC versions in the process), consider dropping multi-byte and developing in utf-8. I understand this is not always possible depending on the project, but consider fixing it in your project. Visual Studio retains backwards compatibility, but is probably one of the few programs that still does.

**Comment by G109B** [comment]
Thanks for the clarification CoenraadS, I will keep this in mind. Given the number of '°' and '£' problems I have just had to clear up, I guess it will not be until I can abandon the XP platform. (plug: thank goodness for DiffMerge !).
