### ISSUE TITLE
Failed to preview markdown after upgrade to 1.90.0

### ISSUE THREAD

**Issue by marswong** [microsoft/vscode#214405]
Type: <b>Bug</b>

Just open any `.md` file and then press `ctrl + k`, then press `v`:

![image](https://github.com/microsoft/vscode/assets/10388933/90f94a7c-71dd-4561-b955-04f27b9caba6)

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900 (32 x 1997)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.70GB (36.29GB free)|
|Process Argv|--crash-reporter-id a8b922df-e1f2-44c0-95b1-9dc6475ace98|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.10.5
vscode-eslint|dba|2.4.4
githistory|don|0.6.20
gitlens|eam|15.0.4
vscode-html-css|ecm|2.0.9
EditorConfig|Edi|0.16.4
copilot|Git|1.199.0
copilot-chat|Git|0.16.0
go|gol|0.41.4
autoconf|mae|0.2.0
csdevkit|ms-|1.6.8
csharp|ms-|2.31.19
vscode-dotnet-runtime|ms-|2.0.5
vscodeintellicode-csharp|ms-|2.1.11
vscode-kubernetes-tools|ms-|1.3.16
playwright|ms-|1.1.6
debugpy|ms-|2024.6.0
python|ms-|2024.8.0
cpptools|ms-|1.20.5
vscode-yaml|red|1.14.0
rust-analyzer|rus|0.3.1983
even-better-toml|tam|0.19.2
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by RushilJalal** [comment]
@marswong it works alright for me

**Comment by marswong** [comment]
Just tried updating the Windows and restart the system, it works now.
