### ISSUE TITLE
vscode update to 1.90 make git bash very slow

### ISSUE THREAD

**Issue by Lord-Fec** [microsoft/vscode#214448]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90
- OS Version: Windows 22631.3672

Steps to Reproduce:
vscode update to 1.90 make git bash very slow
1. open vscode 
2. open new terminal(git bash), but very slow, evergy operation in bash is very slow 
![Snipaste_2024-06-06_20-18-34](https://github.com/microsoft/vscode/assets/47498451/aeda5d0c-d89d-4fdd-9953-7fd35d020784)

**Comment by tsdineshjai** [comment]
Very slow. No matter if I use gitbash / power shell, the rendering of output is very slow.

In addition to that the input is also being delayed. I tried to reinstall and but nevertheless , this update has been a nightmare. 
Zero Productivity since the udpate.

**Comment by tsdineshjai** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No
> 
>     * VS Code Version: 1.90
> 
>     * OS Version: Windows 22631.3672
> 
> 
> Steps to Reproduce: vscode update to 1.90 make git bash very slow
> 
>     1. open vscode
> 
>     2. open new terminal(git bash), but very slow, evergy operation in bash is very slow
>        ![Snipaste_2024-06-06_20-18-34](https://private-user-images.githubusercontent.com/47498451/337259929-aeda5d0c-d89d-4fdd-9953-7fd35d020784.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NzY4MzUsIm5iZiI6MTcxNzY3NjUzNSwicGF0aCI6Ii80NzQ5ODQ1MS8zMzcyNTk5MjktYWVkYTVkMGMtZDg5ZC00ZmRkLTk5NTMtN2ZkMzVkMDIwNzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDEyMjIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZmJhM2RkZDdmZGZlZTA4MWY4MDFlMjBmNDM5ZTA0NTljZGUwNjYyZTZhYWVkMWZhYzhlNTczNzRlNzAzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pjHZJwUxaLLFF8m8kNuHeuiUtEBQulhuu_4NE5pKLxQ)

Thanks for raising the issue. I thought the issue was my comp.

**Comment by Lord-Fec** [comment]
> > Does this issue occur when all extensions are disabled?: Yes/No
> > ```
> > * VS Code Version: 1.90
> > 
> > * OS Version: Windows 22631.3672
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Steps to Reproduce: vscode update to 1.90 make git bash very slow
> > ```
> > 1. open vscode
> > 
> > 2. open new terminal(git bash), but very slow, evergy operation in bash is very slow
> >    ![Snipaste_2024-06-06_20-18-34](https://private-user-images.githubusercontent.com/47498451/337259929-aeda5d0c-d89d-4fdd-9953-7fd35d020784.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NzY4MzUsIm5iZiI6MTcxNzY3NjUzNSwicGF0aCI6Ii80NzQ5ODQ1MS8zMzcyNTk5MjktYWVkYTVkMGMtZDg5ZC00ZmRkLTk5NTMtN2ZkMzVkMDIwNzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDEyMjIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZmJhM2RkZDdmZGZlZTA4MWY4MDFlMjBmNDM5ZTA0NTljZGUwNjYyZTZhYWVkMWZhYzhlNTczNzRlNzAzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pjHZJwUxaLLFF8m8kNuHeuiUtEBQulhuu_4NE5pKLxQ)
> > ```
> 
> Thanks for raising the issue. I thought the issue was my comp.

Hope microsoft team solve this problem as soon as possible!

**Comment by tsdineshjai** [comment]
> Hope microsoft team solve this problem as soon as possible!

Except for the bot, no one has commented on this. I am not sure they are even aware about the bug?

**Comment by KUGDev** [comment]
> > Hope microsoft team solve this problem as soon as possible!
> 
> Except for the bot, no one has commented on this. I am not sure they are even aware about the bug?

Hi
I found to reinstall the previous version as the best workaround for now

**Comment by tsdineshjai** [comment]
> > > Hope microsoft team solve this problem as soon as possible!
> > 
> > 
> > Except for the bot, no one has commented on this. I am not sure they are even aware about the bug?
> 
> Hi I found to reinstall the previous version as the best workaround for now

Yeah. No other way. Until they fix it, gotta use the previous version.

**Comment by tsdineshjai** [comment]
> > > Hope microsoft team solve this problem as soon as possible!
> > 
> > 
> > Except for the bot, no one has commented on this. I am not sure they are even aware about the bug?
> 
> Hi I found to reinstall the previous version as the best workaround for now

Sorry to say this. But the issue persists even with the previous version 1.89.1

**Comment by nbrinks** [comment]
I think this may be related to the "shell integration" feature.
If I run `unset PROMPT_COMMAND` the terminal is much snappier for that session.
Note, the default setting for `PROMPT_COMMAND` is `__vsc_prompt_cmd_original`

You can also disable shell integration entirely in settings.
![image](https://github.com/microsoft/vscode/assets/1877109/149ec319-9c07-4567-8b73-dbc6068993af)

**Comment by tsdineshjai** [comment]
> > > > > Hope microsoft team solve this problem as soon as possible!
> > > > 
> > > > 
> > > > Except for the bot, no one has commented on this. I am not sure they are even aware about the bug?
> > > 
> > > 
> > > Hi I found to reinstall the previous version as the best workaround for now
> > 
> > 
> > Sorry to say this. But the issue persists even with the previous version 1.89.1
> 
> It is strange as everythin works well for me with these parameters: Version: 1.89.1 (user setup) Commit: [dc96b83](https://github.com/microsoft/vscode/commit/dc96b837cf6bb4af9cd736aa3af08cf8279f7685) Date: 2024-05-07T05:13:33.891Z Electron: 28.2.8 ElectronBuildId: 27744544 Chromium: 120.0.6099.291 Node.js: 18.18.2 V8: 12.0.267.19-electron.0 OS: Windows_NT x64 10.0.22631

Hmm.. The parameters are same. I will try with much older versions. Can anyone else comment on this if they made it work with the pervious version.

**Comment by nbrinks** [comment]
Duplicate: https://github.com/microsoft/vscode/issues/214407

**Comment by Lord-Fec** [comment]
> shell integration

Very thanks! This work for me! I just disable it
![image](https://github.com/microsoft/vscode/assets/47498451/83e3a25f-aee7-4f50-8c99-72d95e9c3584)

**Comment by is-jonreeves** [comment]
> I think this may be related to the "shell integration" feature.

Also resolved this for me. Thx

**Comment by sundayhk** [comment]
system:  windows 11
update to 1.90 git  bash very slow，I really can't stand it.
then  i downgraded to 1.85 and it's normal.
The world is restored to goodness.
https://code.visualstudio.com/updates/v1_85

**Comment by programmeranish** [comment]
the 1.90 version is also lagging in ubuntu downgraded to 1.89 and its fine
