### ISSUE TITLE
User task `workbench.action.pinEditor` stopped working after update to 1.90

### ISSUE THREAD

**Issue by freddydumont** [microsoft/vscode#214480]
Type: <b>Bug</b>

The following user task running on `folderOpen` stopped working correctly after the update to 1.90.

The first task (Open Git Graph) executes correctly, but the second (Pin Active Editor) doesn't do anything. The tab isn't pinned.

```json
    {
      "label": "Open Git Graph",
      "command": "${command:git-graph.view}",
      "hide": true
    },
    {
      "label": "Pin Active Editor",
      "command": "${command:workbench.action.pinEditor}",
      "hide": true
    },
    {
      "label": "Open and Pin Git Graph",
      "hide": true,
      "dependsOn": ["Open Git Graph", "Pin Active Editor"],
      "dependsOrder": "sequence",
      "runOptions": {
        "runOn": "folderOpen"
      }
    },
```

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:34:44.157Z)
OS version: Darwin x64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (19.92GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
turbo-console-log|Cha|2.10.4
npm-intellisense|chr|1.4.5
vscode-eslint|dba|2.4.4
dotfiles-syntax-highlighting|dot|0.1.0
antidote|dru|1.0.21
gitlens|eam|15.0.4
EditorConfig|Edi|0.16.4
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|10.4.0
code-runner|for|0.12.2
codespaces|Git|1.16.22
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.88.1
vscode-graphql-syntax|Gra|1.3.6
nix-ide|jno|0.3.1
svg|joc|1.5.3
md-footer|k-k|1.0.2
vscode-go-to-mdn|kby|1.2.0
caddyfile-support|mat|0.4.0
template-string-converter|meg|0.6.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
debugpy|ms-|2024.6.0
python|ms-|2024.8.0
vscode-pylance|ms-|2024.5.1
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
color-highlight|nau|2.8.0
vscode-versionlens|pfl|1.13.0
ansible|red|24.5.2
vscode-yaml|red|1.14.0
vscode-fileutils|sle|3.10.3
vscode-styled-components|sty|1.7.8
even-better-toml|tam|0.19.2
d2|Ter|0.8.8
lorem-ipsum|Tyr|1.3.1
ulss|Uly|1.0.2
vscode-mdx|uni|1.8.8
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-icons|vsc|12.8.0
vscode-import-cost|wix|3.3.0
markdown-all-in-one|yzh|3.6.2
material-theme|zhu|3.17.2

(2 theme extensions excluded)

</details>

**Comment by AndrewLaganaro** [comment]
Same here. I have the same script and it is not working anymore on linux ubuntu
0
In Windows 11 it still works apparently (when Vscode does not opens as SSH, but directly in windows instead)
