### ISSUE TITLE
VS Code does NOT exit Administrator Mode

### ISSUE THREAD

**Issue by Ryan-Hafen** [microsoft/vscode#214457]
Type: <b>Bug</b>

VS Code will not exit Administrator mode. I have un-installed VS Code and deleted all vs code folders. I have re-install tried re-installing both the user version as well as the system version. I have verified that the "Run this program as an Administrator" is UN-checked in Visual Studio Code Properties->Compatibility.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400H CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.64GB (3.67GB free)|
|Process Argv|--crash-reporter-id 9a7d525e-86a8-4542-b784-e9bb3a592b7b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
python-environment-manager|don|1.2.4
prettier-vscode|esb|10.4.0
shortcut-menu-bar|jer|3.0.4
vscode-peacock|joh|4.2.2
vsc-python-indent|Kev|1.18.0
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.18
debugpy|ms-|2024.6.0
python|ms-|2024.8.0
vs-keybindings|ms-|0.2.1
indent-rainbow|ode|8.3.1
quicktype|qui|23.0.170
icons|tal|3.8.0
win-ca|uko|3.5.1
errorlens|use|3.18.0
vscodeintellicode|Vis|1.3.1
vscodeintellicode-completions|Vis|2.0.0
json|Zai|2.0.2

</details>

**Comment by deepak1556** [comment]
Is this user setup or system setup ? Can you also share the steps that was used to enter administrator mode ?

**Comment by Ryan-Hafen** [comment]
> Is this user setup or system setup ? Can you also share the steps that was used to enter administrator mode ?

This issue happens no matter which setup I use. I have uninstalled all versions of vscode from the PC, deleted all vscode folders, and re-installed vscode using both the user and system setup (having uninstalled vscode as before). 
The steps to re-create as I installed vs code. That's it. It enters administrator mode even on the first run of the application.

**Comment by Ryan-Hafen** [comment]
> Did the issue only start with 1.90.0 update or do you also see it with older versions v1.89 ?

It happened when I installed version 1.86 in January 2024 and I have continued no matter which version I install or upgrade to.

**Comment by mikedice** [comment]
I have exactly the same issue. Of course VSCode gets uninstalled and re-installed a few time in an attempt to correct the problem. Now I am on 1.92.2. Start VSCode, it thinks it is running as Administrator. It says 'Administrator' at the top and pops a warning that it won't install any updates. My Windows 11 machine is an Azure VM.

**Comment by gjsjohnmurray** [comment]
When you launch a Windows command prompt by typing "cmd" in the taskbar's Search field and simply pressing Enter, does the titlebar of the command window that appears include the word "Administrator" in its titlebar?

**Comment by mikedice** [comment]
Affirmative. That command prompt also says Administrator.

I isolated my repro and it was pretty easy. Create a new Azure VM with Windows 11 Pro, install the user mode version of VS Code and then run VS Code. You only get Administrator as described in the repro steps. It is probably some policy set up on the VM by Azure.

**Comment by gjsjohnmurray** [comment]
@Ryan-Hafen what result do you get? Maybe UAC is disabled on your Windows.
