### ISSUE TITLE
Breakpoints on justMyCode: false not working properply in 1.90.0

### ISSUE THREAD

**Issue by michuhu** [microsoft/vscode#214451]
Does this issue occur when all extensions are disabled?: Yes/No

Impossible to verify without extenstions

- VS Code Version: 
```
Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:34:48.028Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

Python: v2024.8.0

```

- OS Version: 
```
Apple M1
Sonoma 14.5 (23F79)
```

Issue also submitted here here, but with no details: [here](https://github.com/microsoft/vscode/issues/214409)

Steps to Reproduce:

1. VSCode version 1.90.0
2. `"justMyCode": false`,
3. set breakpoint anywhere in outside of your code.
4. hit run - the breakpoint will highlight somewhere in your code, the breakpoint outside of your code will be in green and steps will not move the selection forward (the app will proceed however). With each step, vscode will come back to some line or breakpoint in your code.

** Works in version 1.89.1 **

**Comment by roblourens** [comment]
Please file on the python debug extension repo, thanks
