### ISSUE TITLE
Configure font size for Problems in settings

### ISSUE THREAD

**Issue by gamedev-pnc** [microsoft/vscode#214429]
Visual Studio Code allows to configure different font sizes for **Editor**, **Terminal**, **Output**, but not for **Problems**:

```
	"editor.fontSize": 14, // Editor
	"terminal.integrated.fontSize": 11,	// Console: Terminal
	"[code-runner-output]": {
		"editor.fontSize": 11	// Console: Output
	}
```

The lack of such option is inconvenient.

**Comment by porky11** [comment]
The problems tab font size seems very important to me. My screen is rather small with a high resolution. And I don't want to change the resolution just to be able to see the problems properly.
