### ISSUE TITLE
Retrigger completions on accept

### ISSUE THREAD

**Issue by Pajn** [Microsoft/vscode#21445]
I'm developing a language server and is providing completions on import paths.
In my language, a directory can not be imported. I have therefore set `/` as an completion
trigger so that files are automatically suggested. So far does everything work as expected.

However when a folder is accepted by the user I would like to add a trailing slash in the
insertText to help the user know that he or she must continue the path, but when I do that
the completion list is not automatically opened again and the user must press `ctrl+space`,
or type a character, or remove the `/` and type it again.
If I don't insert the `/` and let the user type it manually, the completions open as expected.

I think that if a trigger character is specified as the last character of the insert text it should
be treated the same as if the user had typed it manually and thus retrigger the completions.

**Comment by jrieken** [comment]
> I think that if a trigger character is specified as the last character of the insert text it should
be treated 

Sounds reasonable for this case, but I wonder if it breaks others... As a *workaround* you can define a command with the id `editor.action.triggerSuggest`. That is the same command we trigger on Ctrl+Space or trigger characters.

**Comment by Pajn** [comment]
Unfortunately I could not get that to work, the suggestion window does not open again.

>but I wonder if it breaks others

That is a concern, the safest way might be to introduce an option in the protocol. But that might be a bit too much instead...
However the only use case I can see for including a trigger character as the last character in an edit is for continuing paths. Languages like JS that allows importing a directory doesn't want a slash at the end in that case anyway. But there are of course a lot of completion positions in a lot of languages so it's next to impossible to judge them all.

**Comment by neutrinonerd3333** [comment]
We tried to define a command on the CompletionItem, but it appears that commands are not supported for StandaloneLanguages (for context, we're using Monaco). Fortunately, it wasn't difficult to add this support; would you be open to a PR allowing standalone language completion items to carry a command on them?

**Comment by jrieken** [comment]
> but it appears that commands are not supported for StandaloneLanguages (for context, we're using Monaco).

Why? Can you give me more detail on that?

**Comment by neutrinonerd3333** [comment]
[`monaco.languages.CompletionItem`](https://github.com/Microsoft/monaco-editor/blob/77b9f57/monaco.d.ts#L4107) doesn't carry a `command` field. Fortunately, all we had to do was to
- add an optional `command` field in `CompletionItem` [here](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/standalone/browser/standaloneLanguages.ts#L457)
- add `command: item.command` [here](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/standalone/browser/standaloneLanguages.ts#L594)

**Comment by jrieken** [comment]
Ok, go for it. PR welcome
