### ISSUE TITLE
Powershell displaying path with escaped charaters in terminal after prompt

### ISSUE THREAD

**Issue by aburgett87** [microsoft/vscode#214571]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Open VSCode
2. Open powershell terminal in VSCode
3. Observe PWD after prompt with escaped characters

The powershell instance is 100% operational

Screenshot of behaviour
![image](https://github.com/microsoft/vscode/assets/4073978/27ba0c89-9fd6-43eb-8c47-10aa9bc36743)

**Comment by SashiRin** [comment]
I have the same issue, too.

![image](https://github.com/microsoft/vscode/assets/37045113/7b400d20-05d7-4329-a30f-c7683b710099)

**Comment by only-su** [comment]
same
![image](https://github.com/microsoft/vscode/assets/16153554/ce192b57-3a86-4441-9a09-94c7ce63c88f)

**Comment by philstenning** [comment]
I also have the same issue and I am also using Oh-my-posh powershell plugin
![image](https://github.com/microsoft/vscode/assets/1886110/985c16a8-9795-4918-8ead-0434af93b4dd)
and get it in both standard and insiders version (1.91.0)

**Comment by philstenning** [comment]
see [https://github.com/JanDeDobbeleer/oh-my-posh/issues/5018](https://github.com/JanDeDobbeleer/oh-my-posh/issues/5018) in the  Oh-my-posh repo
