### ISSUE TITLE
Keyboard accessibility and focus indication

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2145]
- [x] win @alexandrudima 
- [x] mac @joaomoreno 
- [x] linux @isidorn 

We no longer hide the focus outline when using the `Tab` key to move focus into an element in the DOM. We added more support for using `Tab` and `Arrow` keys to navigate between UI controls in the workbench and editor.

**Note**: Enable accessibility mode in the editor to be able to tab out of it (`F1 | "Toggle Use of Tab Key..."`)

**Note**: You might end up in a situation where you do not see any focus indication. Open the console and type `document.activeElement` to find out where you are currently at and file a bug if you think something is wrong.

* verify you can use `Tab` to jump to UI controls and you get meaningful focus indication
* verify you can use the `Arrow` keys in UI control groups to jump between controls (e.g. in action bars)
* verify you never end up in a situation where you can not continue to tab out of a control

**Comment by alexandrudima** [comment]
I have also found useful: `setInterval(function() { console.log(document.activeElement); }, 2000);`

**Comment by alexandrudima** [comment]
Mostly works well! :+1:

**Comment by bpasero** [comment]
Thanks :heart:
