### ISSUE TITLE
Terminal not loading ~/.zprofile and not setting LC_ALL

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#21451]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|concrete|vscode|0.1.10|
|vscode-eslint|dbaeumer|1.2.6|
|tslint|eg2|0.8.1|
|Theme-TomorrowKit|ms-vscode|0.1.3|
|debugger-for-chrome|msjsdiag|2.5.4|
|vetur|octref|0.3.8|
|vscode-icons|robertohuertasm|7.3.0|
|language-stylus|sysoev|1.6.0|
|vim|vscodevim|0.5.3|

---

I'm using zsh as login shell, but when I launch terminal in VSCode, `~/.zprofile` is not loaded.

VSCode:

![image](https://cloud.githubusercontent.com/assets/4033249/23342238/b808f176-fc24-11e6-8e0f-40652608988d.png)

Not running `echo HI`, not setting LC_ALL.

![image](https://cloud.githubusercontent.com/assets/4033249/23342256/017bc6f8-fc25-11e6-9122-83daf3c2a603.png)

iTerm2:

![image](https://cloud.githubusercontent.com/assets/4033249/23342245/d1f3269c-fc24-11e6-965d-fb5acbbb2152.png)

@Tyriar

**Comment by Tyriar** [comment]
@octref hmm, I'm not sure why `.zprofile` wouldn't get sourced if you're running it as a login shell (`["-l"]` in shellArgs).

As for `LANG` being set, this should be fixed in Insiders (and stable when it's released today), a change was made to fall back to sensible language variants if only the language is provided by Electron.

**Comment by octref** [comment]
LANG seems fixed now for 1.10. Previous I was using `diff-so-fancy` and it was complaining no default lang set.

Sorry seems I had a misunderstanding of zprofile. It's sourced when logging in and all the env variables are carried over, and shells spawned later will inherit all the env var. That's why I should only set env var like `GOPATH` there.

However iTerm2 does load zprofile each time I open a new terminal whereas VSCode doesn't.

**Comment by Tyriar** [comment]
@octref Normally `~/.zprofile` will run on a login shell (ie. `zsh -l`), if it doesn't exist `~/.profile` will. You can also set the file to source using shellArgs which might be helpful, or you could source it from your `~/.zshrc`:

```bash
. ~/.zprofile
```

I'll close this off as it's the shell's responsibility to do this, let me know if you find more info though :smiley:
