### ISSUE TITLE
Python Debugger F11 and sometimes F10 appear broken

### ISSUE THREAD

**Issue by fierval** [microsoft/vscode#214514]
Type: <b>Bug</b>

In a Python file, try stepping into a method hitting F11. The indicator simply blinks and nothing happens. Only F5 appears to work.

Additionally, even though just-my-code is set to "false", breakpoints in packages are ignored.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor             (32 x 4491)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.14GB (107.25GB free)|
|Process Argv|--folder-uri file:///c%3A/git/fetch/theia-models --crash-reporter-id ebad9e78-b813-4680-b34a-3acad8c2e7ed|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (98)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
numbered-bookmarks|ale|8.4.0
aws-toolkit-vscode|ama|3.8.0
shaderlabvscodefree|aml|1.3.6
atlascode|atl|3.0.10
cmake-format|che|0.6.11
indent4to2|Com|0.1.2
doxdocgen|csc|1.4.0
python-snippets|cst|0.1.2
vscode-fsharp-refactor|dan|0.6.2
vscode-markdownlint|Dav|0.55.0
vscode-terminal-for-ubuntu|Doc|0.0.2
githistory|don|0.6.20
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
gitlens|eam|15.0.4
env-switcher|Eck|0.5.2
vsc-material-theme|Equ|34.3.1
vsc-material-theme-icons|equ|3.6.0
vs-code-xml-format|fab|0.1.5
codespaces|Git|1.16.22
copilot|Git|1.200.919
copilot-chat|Git|0.16.2024060502
vscode-pull-request-github|Git|0.88.1
vscode-test-explorer|hbe|2.21.1
yaml-plus-json|hil|1.12.2
Untabify|ili|0.0.2
latex-workshop|Jam|9.20.1
better-cpp-syntax|jef|1.17.2
vscode-graphviz|joa|0.0.9
vscode-dask|joy|0.0.4
vsc-python-indent|Kev|1.18.0
vscode-gutter-preview|kis|0.31.2
vscode-cudacpp|kri|0.1.1
MagicPython|mag|1.1.0
rainbow-csv|mec|3.12.0
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
theme-monokai-pro-vscode|mon|1.3.2
vscode-docker|ms-|1.29.1
csdevkit|ms-|1.6.8
csharp|ms-|2.31.19
vscode-dotnet-runtime|ms-|2.0.5
vscodeintellicode-csharp|ms-|2.1.11
autopep8|ms-|2024.0.0
debugpy|ms-|2024.6.0
python|ms-|2024.8.0
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.369.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.9.10
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
test-adapter-converter|ms-|0.1.9
vsliveshare|ms-|1.0.5918
vscode-paste-image|mus|1.0.4
color-highlight|nau|2.8.0
autodocstring|njp|0.6.1
emoji|Per|1.0.1
proto|pet|0.0.4
vscode-poetry|poe|0.5.0
vscode-commons|red|0.0.6
vscode-xml|red|0.27.1
vscode-yaml|red|1.14.0
manim-sideview|Ric|0.2.13
scala|sca|0.5.7
uss|sgd|1.0.1
git-merger|sha|0.4.1
shader|sle|1.1.5
urdf|smi|0.3.0
svelte-vscode|sve|108.5.0
ros-snippets|swe|0.1.0
spellchecker|swy|1.4.0
even-better-toml|tam|0.19.2
html-preview-vscode|tht|0.2.5
snakeviz|til|0.0.2
chatgpt|tim|1.1.2
simple-rst|tro|1.5.4
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vstuc|vis|1.0.2
jinja|who|0.0.8
clang-format|xav|1.9.0
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.6.2
json|Zai|2.0.2
vscode-python-poetry|zes|0.17.20
vscode-proto3|zxh|0.5.5

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
2f103344:31067618
26j00206:31048877

```

</details>

**Comment by fierval** [comment]
[https://www.dropbox.com/scl/fi/nj7ea0yyel73730k5tkwh/Code_2kSFZUh1K7.mp4?rlkey=fzi0br4mwm3qxi6daq83w3ab9&dl=0](Screen Grab)

**Comment by fierval** [comment]
https://github.com/microsoft/vscode/assets/987574/81e5bc60-1d86-4669-8d5b-7a0a24a26960

**Comment by fierval** [comment]
Downgraded to 1.89.1 works fine.

**Comment by roblourens** [comment]
Looks like you are stepping through `module.py` which is a hidden library file. Not sure whether it is supposed to be opening the editor for module.py or if this is expected for this scenario.

Could you open this on the vscode-python repo? It might help to include an example of what you see different in 1.89

**Comment by fierval** [comment]
It happens on ANY file, I just posted an example for visual clarity. I'll re-open in the other repo.
