### ISSUE TITLE
Vs Code auto-importing does not work with Vue js 3

### ISSUE THREAD

**Issue by vusal5555** [microsoft/vscode#214597]
Type: <b>Bug</b>

I have been trying to auto-import components into App.vue but vs code for some reason does not recognize them.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.03GB free)|
|Process Argv|.\\vue-blog\\ --crash-reporter-id 6b2f1274-0587-46b1-9a78-a26c6614eef9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
laravel-extra-intellisense|ami|0.6.6
vscode-tailwindcss|bra|0.10.5
laravel-goto-view|cod|1.3.11
composer-php-vscode|DEV|1.47.15512
phptools-vscode|DEV|1.47.15512
profiler-php-vscode|DEV|1.47.15512
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
vscode-phpfmt|kok|1.2.12
rainbow-csv|mec|3.12.0
dotenv|mik|1.0.1
inline-fold|moa|0.2.6
laravel-goto-components|nao|1.2.0
color-highlight|nau|2.8.0
laravel-blade|one|1.36.1
material-icon-theme|PKi|5.3.0
vue-vscode-snippets|sdr|3.1.1
vscode-blade-formatter|shu|0.24.2
svg-preview|Sim|2.8.3
cody-ai|sou|1.20.3
errorlens|use|3.18.0
vue|Wsc|1.0.26

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
newcmakeconfigv2:31067619
26j00206:31048877

```

</details>

**Comment by mjbvz** [comment]
Vue support is provided by an extension. Please file the issue against them
