### ISSUE TITLE
Alt + Up/Down to move a line of code no longer automatically aligns the context of the code

### ISSUE THREAD

**Issue by lujinzhu** [microsoft/vscode#214550]
When writing Lua code in VSCode, using Alt + Up/Down to move a line of code no longer automatically aligns the context of the code. Before the update, it would automatically align.

**Comment by lszomoru** [comment]
@aiday-mar, could you please help triage this issue? Thank you!

**Comment by aiday-mar** [comment]
Hi @lszomoru yes thanks for the ping, this appears to be related to some recent auto-indentation changes I have made.

**Comment by aiday-mar** [comment]
should be fixed with https://github.com/microsoft/vscode/pull/214577
