### ISSUE TITLE
"Folded code" arrow misplaced within sticky scroll

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#214592]
Repro:
1. fold code
2. scroll slowly until you see:

![Image](https://github.com/microsoft/vscode/assets/16353531/b9457b06-ed34-4b10-97ea-1283c62ce3de)

https://github.com/microsoft/vscode/assets/16353531/5bdc0185-5876-43f2-b3b0-e7b84dc3e1b5

**Comment by aiday-mar** [comment]
should be fixed with https://github.com/microsoft/vscode/pull/235804
