### ISSUE TITLE
Regression in indentation applied when moving code down

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#214569]
Start with the following code:
```ts

class ConfigurationServiceImpl {

	constructor() {
	}

	private _getConfiguredValue<T>(key: BaseConfig<T>): T | undefined {
		if (this.config[key.firstPart] && this.config[key.firstPart][key.secondPart] !== undefined) {
			return this.config[key.firstPart][key.secondPart];
		}
		const valueFromSettings = this.config.get(key.id);
		if (valueFromSettings !== undefined) {
			return valueFromSettings as T;
		}
	}

	override async getExperimentBasedConfig<T>(key: ExperimentBasedConfig<T>, experimentationService: IExperimentationService): Promise<T> {
		const configValue = this._getConfiguredValue(key);
		const tmp = await experimentationService.getTreatmentVariableAsync<boolean>('vscode', 'key', true);
		if (tmp || configValue) {
			res = 'x';
		}
		
		const tmp = await experimentationService.getTreatmentVariableAsync<boolean>('vscode', 'key', true);
		if (routingEnabled || configValue) {
			res = 'x';
		}
	}
	
}
```
* select the first method
* move it down

### vscode 1.91.0-insiders 5f646b8e67a869ef33061085ffe0e377d5ba040c

https://github.com/microsoft/vscode/assets/5047891/a02fa65a-936e-456b-a6a7-f66956158b2a

### vscode 1.85.1

https://github.com/microsoft/vscode/assets/5047891/749f14c2-df1c-4455-a99e-697ac670e7b6

**Comment by alexdima** [comment]
This reproduces for very simple examples:

https://github.com/microsoft/vscode/assets/5047891/166ae16d-6b80-4712-8b26-7da0b28af7cc

**Comment by ArturoDent** [comment]
See also https://github.com/microsoft/vscode/issues/214562 and https://github.com/microsoft/vscode/issues/214779

**Comment by aiday-mar** [comment]
Should be fixed with https://github.com/microsoft/vscode/pull/214577
