### ISSUE TITLE
vscode keeps crashing on open.

### ISSUE THREAD

**Issue by m-nathani** [microsoft/vscode#214542]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0 89de5a8d4d6205e5b11647eb6a74844ca23d2573 x64
- OS Version: Linux Ubuntu 22.04.4 LTS

Steps to Reproduce:

1. open vscode manual or in terminal `code .`
2. it opens and then crashes

Here you can find the logs attached for command `code . --verbose > logs.txt`

[logs.txt](https://github.com/user-attachments/files/15698723/logs.txt)

**Comment by rdong8** [comment]
#212494

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/212494

You can start the application with `--use-angle=swiftshader` as workaround until fix is released.

**Comment by RushiVachhani** [comment]
Keeps crashing for me too.

However this worked for me try it out

```
code --in-process-gpu
```
