### ISSUE TITLE
Selected region search and replace functionality change

### ISSUE THREAD

**Issue by krperry** [microsoft/vscode#214522]
Type: <b>Feature Request</b>

If I select a region and do search and replace.  Why do I have to check the check box to search and replace in the region.  If I wanted to search and replace in the whole file I wouldn't have selected the region. It should be by default search and replace in the  region if you have selected text.

Expected behavior:

select a block of text
search and replace in that block

Do not select a region 
Search and replac ein file

No check box needed.  

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by rebornix** [comment]
This can be archived via setting editor.find.autoFindInSelection.
