### ISSUE TITLE
Any plans for resolving JS function parameter types from .d.ts?

### ISSUE THREAD

**Issue by rnemec** [Microsoft/vscode#21454]
If somebody for various reasons needs to keep the code itself as plain ES6 javascript (in .JS files), but is using .d.ts files for VSCode assistance (which in indeed incredible!), would it be possible to derive the types of the function parameters not from the JSDoc @ param but from the .d.ts itself?

Right now, any **other** file, importing a module, can benefit from the type information in .d.ts - but the module itself **cannot**.

Is this something being cooked in the vscode secret labs, just not finished yet? Is there a roadmap item  for this?

Thanks vscoders for the awesome tool!

**Comment by mjbvz** [comment]
Thanks. I verified this issue and have opened https://github.com/Microsoft/TypeScript/issues/14342 to track this on the TypeScript side. I was not able to find a workaround for this, but perhaps the TypeScript folks will be able to suggest one.

Closing as upstream
