### ISSUE TITLE
Expand line selection does not select all of wrapped line

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#21450]
- VSCode Version: latest

Steps to Reproduce:

1. Enable line wrapping
2. Go to a wrapped line
3. Run the `expandLineSelection` command e.g. `cmd+i`

Expected: all lines in the wrapped line will be selected

Actual: only the current line of the wrapped line is selected

**Comment by stewartadam** [comment]
Ran into this as well. I have to resort to disabling line-wrap, selecting, then re-enabling it.

**Comment by yingw787** [comment]
Also encountered this issue. I think it might be giving me problems when I am cutting and pasting, because I would copy only the non-wrapped part, then paste that instead of the full line.

**Comment by sashkab** [comment]
Any known workaround for this, except making window wider?

**Comment by rebornix** [comment]
We can probably expand the selection the while line when users press cmd+i the second time, which means the workflow becomes

* cmd+i selects the wrapped line
* Second cmd+i selects all

**Comment by ebr** [comment]
Is there any movement on this issue? I could have sworn that in the past wrapped lines were selected with a single `Ctrl-L` (or `Ctrl-I` previously). I used to be on Mac, and now am on Linux. At some point this changed, and wrapped lines are no longer selected entirely.

**Comment by foreignmeloman** [comment]
![a](https://user-images.githubusercontent.com/11769352/64480360-288cca00-d1d7-11e9-924d-2d772b8b9019.gif)

Same here, using the latest insiders build. I can't believe that issue like this remains open for 2 years.

**Comment by mrob95** [comment]
+1 for changing this behaviour or adding a setting to control it. Other line actions like `copyLinesDown` do not depend on zoom/wrap settings.
