### ISSUE TITLE
Custom icons in the chat stream.progress

### ISSUE THREAD

**Issue by cjlapao** [microsoft/vscode#214590]
I'm currently collaborating with @isidorn on a new chat extension. One of the features we need is the ability to customize the icons displayed on the chat stream. Currently, when we set the progress, a loading animated icon is shown, which then automatically changes to a check mark when we move to the next task. While this is good, for multi-step processes, we might want to change the icons to better convey the status, such as displaying an 'X' if a step fails.

It would also be helpful to have the option to retain this icon information in the chat. By default, the progress is cleared once the chat stream ends, but in certain circumstances, such as a failed step, we might want to preserve this information.

**Comment by roblourens** [comment]
Sort of related to the proposed "progress with task" API here https://github.com/microsoft/vscode/blob/4a4ae4603279ad4d836c4d2b17f055f6708d59ff/src/vscode-dts/vscode.proposed.chatParticipantAdditions.d.ts#L88 where we can offer more control and dynamic updating of the progress task.
