### ISSUE TITLE
Activity Bar Product Icon Size

### ISSUE THREAD

**Issue by mattegray** [microsoft/vscode#214557]
Type: <b>Feature Request</b>

The current icon sizes on the Activity Bar look too big, at `24px`, while the Activity Bar width is `48px`. How about changing the icon sizes to `20px`?

VS Code version: Code 1.90.0 (Universal) (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:34:44.157Z)
OS version: Darwin arm64 23.4.0
Modes:

**Comment by mattegray** [comment]
This is the Activity Bar with icon size `20px`
<img width="48" alt="Screenshot 2024-06-07 at 3 36 22 PM" src="https://github.com/microsoft/vscode/assets/69251011/7cbbece9-171b-42e0-92b0-5310c5b09f91">
And this is the current size at `24px`
<img width="48" alt="Screenshot 2024-06-07 at 3 36 41 PM" src="https://github.com/microsoft/vscode/assets/69251011/f325a61c-90a2-4227-a856-0868eff855da">

**Comment by widersky** [comment]
How about give us an option to set this value ourselves?

**Comment by mattegray** [comment]
For reference, Figma's toolbar is also `48px` in width, but the icons are smaller, somewhere around `18px`.

<img width="570" alt="Screenshot 2024-06-07 at 6 50 32 PM" src="https://github.com/microsoft/vscode/assets/69251011/52a166fd-eb8e-47ae-b79a-1c3a58161fc8">
