### ISSUE TITLE
Typing "Theme" In Command Palette Does Not Select The Main Command

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#214573]
This is in a fresh incognito tab:

![chrome_pWL5NbdVBZ](https://github.com/microsoft/vscode/assets/2931520/241d1739-b1f5-46dc-b88d-d4662dd51f88)

"Preferences: Color Theme" should be selected here.

Can we use telemetry to figure out which commands are "hot" and boost them in the sorting?

**Comment by isidorn** [comment]
Thanks for opening these. I 100% agree, and hit this as well.

@TylerLeonhardt is there some metadata a command can provide to boost it's score in quick pick sort? Also related #214574

**Comment by TylerLeonhardt** [comment]
duplicate https://github.com/microsoft/vscode/issues/173767#issuecomment-2075149607
