### ISSUE TITLE
Integrated Terminal is slow with Conpty enabled

### ISSUE THREAD

**Issue by Sammy-T** [microsoft/vscode#214529]
Type: <b>Performance Issue</b>

Using bash in the Integrated Terminal runs significantly slower when `terminal.integrated.windowsEnableConpty` is enabled. Specifically, the executed command appears to complete within a reasonable amount of time but the terminal stalls on a blank line afterwards which delays the ability to input another command.

With task manager up, I see that executing a command triggers CPU activity on my antivirus service (Malwarebytes in this case but if I disable it then Windows Defender responds similarly).

If I disable `terminal.integrated.windowsEnableConpty`, bash launches in the integrated terminal and commands execute much more quickly. This is similar performance to what I see if I use bash outside of VS Code.

## Steps to reproduce:
1. Enable `terminal.integrated.windowsEnableConpty`
2. Open a new bash terminal inside VS Code
3. Enter a command \
ex. `echo "hello"`

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (22.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   111	 14872	code main
    0	   205	  1800	window [1] (Settings - tmp-test - Visual Studio Code)
    0	    93	  7224	ptyHost
    0	     5	  1000	     "C:\Program Files\Git\bin\bash.exe" --init-file "c:\Users\Sammy\AppData\Local\Programs\Microsoft VS Code\resources\app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"
    0	    11	 18156	       "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --init-file "c:\Users\Sammy\AppData\Local\Programs\Microsoft VS Code\resources\app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"
    1	     7	  3836	     conpty-agent
    0	   109	  9272	extensionHost [1]
    0	   112	  8068	     "C:\Users\Sammy\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Sammy\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=9272
    0	    40	 12716	   utility-network-service
    0	    86	 13048	fileWatcher [1]
    0	   101	 15936	window [2] (Issue Reporter)
    0	   105	 16068	shared-process
    0	   172	 16988	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings - tmp-test - Visual Studio Code)
|    Folder (tmp-test): 0 files
|      File types:
|      Conf files:;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-todo-highlight|way|1.0.5

</details>

**Comment by IllusionMH** [comment]
Do you have `terminal.integrated.shellIntegration.enabled` enabled? And if yes - do you see improvements if you disable it?

Asking as it might be related to #212090

**Comment by laptomp** [comment]
> Do you have `terminal.integrated.shellIntegration.enabled` enabled? And if yes - do you see improvements if you disable it?
> 
> Asking as it might be related to #212090

I was having the same issue. Disabling either `terminal.integrated.windowsEnableConpty` or `terminal.integrated.shellIntegration.enabled` worked to remove the delay, so the two are probably related.

**Comment by Sammy-T** [comment]
> Do you have `terminal.integrated.shellIntegration.enabled` enabled? And if yes - do you see improvements if you disable it?
> 
> Asking as it might be related to #212090

I'm seeing the same as @laptomp. Disabling either of them improves the delay.

I didn't see that issue before so I'll close this one in favor if it.
