### ISSUE TITLE
I'm on windows 11 but keep receiving this error code 

### ISSUE THREAD

**Issue by dazcodes** [microsoft/vscode#214516]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 
!
![issues with VSC](https://github.com/microsoft/vscode/assets/85360799/d9ae89e3-fabd-4361-9a71-c4f9c740e3ac)

**Comment by IllusionMH** [comment]
Please check if you are running VS Code in compatibility mode.

Looks like duplicate of https://github.com/microsoft/vscode/issues/189664#issuecomment-1707901089
