### ISSUE TITLE
Move line up/down causes indentation to break

### ISSUE THREAD

**Issue by pvettori** [microsoft/vscode#214562]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0
- OS Version: Windows 10 Home 22H2 build 19045.4412 (+ WSL2 inside Win10)

Steps to Reproduce:

(similar to this issue: https://github.com/microsoft/vscode/issues/78788)
1. Sample code:
```php
<?php
if (true) {
    $a = 1;
}
$lineTo = 'move';
```
2. Set cursor at line 5 and perform `editor.action.moveLinesUp` 3 times.
3. The moved line is misplaced:
```php
<?php
    $lineTo = 'move';
if (true) {
    $a = 1;
}
```

In a vscode window opened in WSL this also happens:
1-WSL. Sample code:
```php
<?php
$lineTo = 'move';
if (true) {
    $a = 1;
}
```
2-WSL. Set cursor at line 2 and perform `editor.action.moveLinesDown` 3 times.
3-WSL. The last bracked is misplaced:
```php
<?php
if (true) {
    $a = 1;
    }
$lineTo = 'move';
```

**Comment by aiday-mar** [comment]
should be fixed by https://github.com/microsoft/vscode/pull/214577
