### ISSUE TITLE
Vscode does not open

### ISSUE THREAD

**Issue by Quiago** [microsoft/vscode#214518]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. I can't open vscode after the new update, other ubunutu user report the same issue
2.

**Comment by GuySartorelli** [comment]
Presumed duplicate of https://github.com/microsoft/vscode/issues/214432

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/212494

You can start the application with `--use-angle=swiftshader` as workaround until fix is released.
