### ISSUE TITLE
Copy or cut all occurrences found?

### ISSUE THREAD

**Issue by Scr1pt3r** [Microsoft/vscode#21455]
- VSCode Version: 1.9.1
- OS Version: Windows 10

In vscode is it possible to copy or cut occurrences found?
With example in _sublime-text_, Please look at the image:
![copy_find_all_occurrences](https://cloud.githubusercontent.com/assets/7041995/23343860/08820e36-fc51-11e6-9a3a-f41d8873212f.png)

**Comment by roblourens** [comment]
You can select all results (alt+enter) then copy or cut.

**Comment by Scr1pt3r** [comment]
Thank you very much!
