### ISSUE TITLE
Ability to change the font family and font size of the explorer

### ISSUE THREAD

**Issue by FlareShip** [microsoft/vscode#214563]
The ability to change the _font family_ and _font size_ of the explorer (and other components) would be helpful.

I was able to change the _font family_ with [Apc Customize UI++ Extension](https://marketplace.visualstudio.com/items?itemName=drcika.apc-extension) but not the _font size_, by the way there were other solutions for the _font size_ but it would greatly help if I can change both the settings without any extension.

**Comment by lramos15** [comment]
Duplicate #519
