### ISSUE TITLE
IntelliSense Not Working

### ISSUE THREAD

**Issue by swainsboroGT** [microsoft/vscode#214693]
I cannot get my intellisense to work on my terminal.  Please assist.

Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0
Embedder: codespaces

**Comment by Tyriar** [comment]
This feature feature is experimental and the old pwsh-only implementation will actually be removed soon. See https://github.com/microsoft/vscode/issues/226562
