### ISSUE TITLE
Profiles table should look less like a table

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#214622]
You are using the table for rendering here. The goal should be alignment, not that everything looks like a table. If everything looks like a table, then the UI change is stark compared to when we use a tree. Thus I suggest:

* The table title row should have same background as everything else
* Do not have "Actions" item in the title row
* Do not use bold for "Use Default Action"

That will make it look lighter and blend better with the rest of the UI imho.

![Image](https://github.com/microsoft/vscode/assets/1926584/c075adb3-6cef-455c-b994-da1460324990)

**Comment by sandy081** [comment]
This is how it looks with your suggestions

![Image](https://github.com/user-attachments/assets/6fef8b23-39d4-4eb8-aaeb-25c01a17d830)

I do not have strong opinion here. 

CC @joaomoreno

**Comment by isidorn** [comment]
This looks better to me. Though would also like to see it in product to get a better sense.

**Comment by sandy081** [comment]
Actually after looking at both of them again, I liked the one with the header with background colour - this seems to have organised layout.

**Comment by sandy081** [comment]
To be in consistent with our existing tables, I picked the same format and styling for headers.
