### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by fanchengsheng** [Microsoft/vscode#21461]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.2|
|vscode-eslint|dbaeumer|1.2.6|
|vscode-stylesheet-formatter|dbalage|0.2.0|
|vscode-instant-markdown|dbankier|1.0.0|
|python|donjayamanne|0.5.8|
|beautify|HookyQR|0.8.8|
|vscode-codemetrics|kisstkondoros|1.2.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|debugger-for-chrome|msjsdiag|2.5.3|
|typescript-hero|rbbit|0.12.0|
|react-beautify|taichi|0.3.0|
|react-redux-es6-snippets|timothymclane|2.0.2|
|jsx-snippets|TwentyChung|0.0.1|
|JavaScriptSnippets|xabikos|1.4.0|

---

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
Details?
