### ISSUE TITLE
Program constanly crashing

### ISSUE THREAD

**Issue by allthatgroove89** [microsoft/vscode#214624]
Type: <b>Bug</b>

VSC was working fine until last night which keeps crashing on me, I restart it, disable/restart extensions but keeps crashing, the only new thing I can think of is that I created an virtual environment, dont know if that could be the issue.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:43:07.605Z)
OS version: Linux x64 5.15.0-107-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2778)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 1|
|Memory (System)|7.54GB (0.80GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 363f9ce2-5800-4c6d-a883-0c3efa9b336d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
c-compiler|bra|0.0.4
dscodegpt|Dan|3.3.36
vscode-markdownlint|Dav|0.55.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
code-runner|for|0.12.2
copilot|Git|1.200.0
copilot-chat|Git|0.16.0
vsc-python-indent|Kev|1.18.0
rainbow-csv|mec|3.12.0
c-auto-prototypes|Mol|3.0.0
vscode-docker|ms-|1.29.1
autopep8|ms-|2024.0.0
debugpy|ms-|2024.6.0
python|ms-|2024.8.0
vscode-pylance|ms-|2024.6.1
cpptools|ms-|1.20.5
vscode-speech|ms-|0.10.0
autodocstring|njp|0.6.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vim|vsc|1.27.3
gitblame|wad|11.0.1
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
f8hc8238:30694864
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/212494
