### ISSUE TITLE
A better way to provide multi-line Snippets support

### ISSUE THREAD

**Issue by broven** [Microsoft/vscode#21465]
ps: I'm not  excellent in English, but I'll try to make it clear.

now, we add custom snippets use json file, for example, add a for loop snippets:
```json
"For Loop": {
        "prefix": "for",
        "body": [
            "for (var ${1:index} = 0; ${1:index} < ${2:array}.length; ${1:index}++) {",
            "\tvar ${3:element} = ${2:array}[${1:index}];",
            "\t$0",
            "}"
        ],
        "description": "For Loop"
    }
```
In `body`, we need add useless quotes and `\t` for good format, I think this is not good enough.

But if we use some Notations like  [CSON]("https://github.com/bevry/cson"), we write snippets will like this:
```
'For Loop':
    'prefix': 'for'
    'body': """
        for (var ${1:index} = 0; ${1:index} < ${2:array}.length; ${1:index}++) {
            var ${3:element} = ${2:array}[${1:index}];
            $0
            }
"""
```
I think this is a better way to write snippets.
or we just use it like
#15140

**Comment by roblourens** [comment]
It looks like this is covered by #15140. I agree it seems a little awkward.

**Comment by broven** [comment]
@roblourens I don't think is duplicate with #15140 , He ask how to use multi-line in JSON, my point is use CSON for Snippets file, because CSON is much better in this case
