### ISSUE TITLE
`typescript.tsserver.experimental.useVsCodeWatcher` leaking inotify watches

### ISSUE THREAD

**Issue by frewsxcv** [microsoft/vscode#214605]
Does this issue occur when all extensions are disabled?: Yes (except for the TypeScript extension)

- VS Code Version: 1.90.0
- OS Version: macOS 13.6

Steps to Reproduce

1. Ensure `typescript.tsserver.experimental.useVsCodeWatcher` is turned on
2. Open TypeScript files, indexing a large project
3. Close and reopen VSCode, and reindex

Repeat these steps a few times and inotify watches will be held onto. Eventually inotify watches will be exhausted which causes VSCode to hang, and performance degradations.

![image](https://github.com/microsoft/vscode/assets/416575/75d428d4-3f52-4156-9232-d381f74d4908)

**Comment by frewsxcv** [comment]
My coworkers who work on the same project can also confirm this behavior with this setting on.

**Comment by frewsxcv** [comment]
Potentially related to https://github.com/microsoft/vscode/issues/211462

**Comment by connor4312** [comment]
#211462 is only tracking running under Remote - SSH. If that's not the case for you, this is a different issue.

**Comment by connor4312** [comment]
Marking as a duplicate
