### ISSUE TITLE
 Reopen!: Cursor changes into a "plus" when ALT is typed #206338 

### ISSUE THREAD

**Issue by michal-gora** [microsoft/vscode#214674]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0
- OS Version: Windows 11 23H2

Steps to Reproduce:

1. change settings.json and add: "terminal.integrated.altClickMovesCursor": false
2. Restart
3. Open Integrated Terminal
4. ==> Pressing alt still changes the cursor to "plus"

**Comment by crazyboycjr** [comment]
Yeah I find it quite annoying, and `"terminal.integrated.altClickMovesCursor": false` does not work.

**Comment by Tyriar** [comment]
The cursor change is primarily for hinting that it's in column select mode:

![Recording 2024-07-16 at 03 18 02](https://github.com/user-attachments/assets/5d66af22-ccad-482a-a45f-ea3fb11a6b77)

Let me know if I'm misunderstanding something.

**Comment by crazyboycjr** [comment]
@Tyriar many people use alt + [key] quite a lot in the terminal. E.g, alt + left or right for fast navigating between words. However, the current behavior is that whenever a single alt is pressed (and released), the mouse cursor becomes a plus, with a possibility that the blinking cursor in the command line lose its focus.

It would make more sense to go into column select mode if alt is long-PRESSED, not just clicked. Or simply make sure `"terminal.integrated.altClickMovesCursor": false` can disable this feature as intended.

**Comment by crazyboycjr** [comment]
@futureengco How brilliant you are! 👍👍👍👍👍👍

**Comment by Tyriar** [comment]
> Or simply make sure "terminal.integrated.altClickMovesCursor": false can disable this feature as intended.

You're still misunderstanding, alt click moves cursor is not why the cursor changes.

> It would make more sense to go into column select mode if alt is long-PRESSED, not just clicked.

The cursor only changes when you hold alt _and_ move the mouse, long pressing without moving the mouse doesn't change the cursor.

![Recording 2024-07-16 at 12 28 35](https://github.com/user-attachments/assets/802062ca-5816-439d-91a8-d117381b2f16)

Do you see something different to the above?

You might ask why I'm so resistant to a simple new setting, it's because every setting increases the complexity of the codebase and product.

**Comment by michal-gora** [comment]
I just opened VSCode to try it out and opened the internal terminal, and it changes the cursor to a plus when pressing alt (without moving the cursor). Sometimes, I guess when clicking quickly on the alt, the focus changes to the upper navigation bar (File, Edit, Selection, View, ...). I don't know if the problem just occurs on windows or what is going on, at least I'm on windows. Maybe, if you're on Linux there is a bug in the windows release.

I understand the increasing complexity with simple settings, but it's about an existing non-working one. At least not working for me and some other users in this thread.

**Comment by Tyriar** [comment]
Looking a little into this, it's actually meant to change immediately when pressing the key so I'm not seeing the right behavior for some reason.

Sorry but we're not changing this, doing so would require a new API in xterm.js, a new setting in vscode and it's just not worth it. Especially when it's such a small thing that is doing exactly what it's meant to; indicate what the cursor will do when you use the mouse.
