### ISSUE TITLE
Terminal is incorrectly rendering characters with oh-my-posh

### ISSUE THREAD

**Issue by Begad666** [microsoft/vscode#214667]
Type: <b>Bug</b>

When using oh-my-posh with powershell 7, the integrated terminal renders the color escape codes as text.
This did not occur in 1.89.1, and I tried with all extensions disabled.

1.90:
![image](https://github.com/microsoft/vscode/assets/47504169/9fd31d62-e1bf-479e-ba9e-8d72a1351fa5)
1.89.1:
![image](https://github.com/microsoft/vscode/assets/47504169/8765298e-4162-481e-9546-c5ec90770ea8)

On a different theme with a more complex prompt, the terminal shows this:
1.90:
![image](https://github.com/microsoft/vscode/assets/47504169/6e96c4df-5882-42d2-a419-e6c29baa973c)
1.89.1:
![image](https://github.com/microsoft/vscode/assets/47504169/ad1eb750-4cc0-435e-9489-3f25442e54ba)

Disabling shell integration fixes the problem:
![image](https://github.com/microsoft/vscode/assets/47504169/3dfeb60b-8706-4fea-a37c-613396196d4f)

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by yapancha** [comment]
<img width="723" alt="image" src="https://github.com/microsoft/vscode/assets/149987391/94b908f7-01f6-4e56-a4bc-64d288dc16b3">

Same issue for me, and it doesn't happen in windows terminal. Only inside vscode terminal .

**Comment by aodendaal** [comment]
A work around from @JanDeDobbeleer [here](https://github.com/JanDeDobbeleer/oh-my-posh/issues/5029) is to disable shell integration in Settings and restart VSCode

**Comment by Begad666** [comment]
This issue was fixed in the latest version (1.90.2) so I'm closing it now.
