### ISSUE TITLE
"review with copilot" button should move left

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#214651]
I use the + button many times a day, and I think it would be nicer to keep the + button as the rightmost button so it matches the + on individual files so it doesn't break muscle memory, what do you think? The ✨ button could go to the far left, or just one spot left

<img width="440" alt="image" src="https://github.com/microsoft/vscode/assets/323878/7e0239ed-d558-4e5c-91aa-08743bdc0e39">

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by chrmarti** [comment]
Fixed with https://github.com/microsoft/vscode-copilot/pull/6186
