### ISSUE TITLE
Git Branch Picker Race Condition

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#214626]
If I paste the branch too quickly and then press enter, it does not switch to it, but creates a new branch.
This breaks muscle memory, as it works when you do it slowly.

![Code_-_Insiders_peF36XR6nS](https://github.com/microsoft/vscode/assets/2931520/d5d901c1-ad87-4c36-afe5-2a3a4d267800)

Once loading completes, it should select the branch again.

**Comment by lszomoru** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/218628
