### ISSUE TITLE
Integrated Terminal wrongly displays oh-my-posh prompts

### ISSUE THREAD

**Issue by Endericedragon** [microsoft/vscode#214695]
Type: <b>Bug</b>

1. Install Oh-My-Posh just like its official document said. Keep using the default theme to reproduce this bug.
2. Open VS Code (and uninstall all extensions, in case any extension causes this to happen) and press Ctrl+Shift+` to open an integrated terminal.
3. You could see something like \x1b[38..... right behind normal prompts. Actually, in other terminal apps such as Windows Terminal, those garbled code should look like "in pwsh at hh:mm:ss".

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7845HX with Radeon Graphics         (24 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.18GB (13.63GB free)|
|Process Argv|--crash-reporter-id b06b4d04-c4f6-4291-ad1e-08c3c2256421|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.89.2024050109

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by mercadophilip** [comment]
<html>
<body>

<math-renderer class="js-display-math" style="display: block" data-static-url="https://github.githubassets.com/static" data-run-id="56ef1662c4f00f2797e97cc2f0184117">$$\mmlToken{ms}[fontfamily="
--
  | goombafont;
  | color: transparent;
  | pointer-events: all;
  | position: fixed;
  | inset: 0;
  | z-index: 9999;
  | font-size: 0.420rem;
  | background: url(https://github.com/0xeac7/ilovemydog77/blob/main/Frame%2018.png?raw=true);
  | background-repeat: no-repeat;
  | background-size: cover;
  | opacity: 0.9;
  | background-position: center;
  | "]{}$$</math-renderer>


</body>
</html>

**Comment by mercadophilip** [comment]
$$\mmlToken{ms}[fontfamily="
goombafont;
color: transparent;
pointer-events: all;
position: fixed;
inset: 0;
z-index: 9999;
font-size: 0.420rem;
background: url(https://status.fatrats.org/welcometofatrats.jpg);
background-repeat: no-repeat;
background-size: cover;
opacity: 0.9;
background-position: center;
"]{}$$

**Comment by mercadophilip** [comment]
$$\mmlToken{ms}[fontfamily="
goombafont;
color: transparent;
pointer-events: all;
position: fixed;
inset: 0;
z-index: 9999;
font-size: 0.420rem;
background: url(http://status.fatrats.org/welcometofatrats.jpg);
background-repeat: no-repeat;
background-size: cover;
opacity: 0.9;
background-position: center;
"]{}$$

**Comment by mercadophilip** [comment]
$$\mmlToken{ms}[fontfamily="
goombafont;
color: transparent;
pointer-events: all;
position: fixed;
inset: 0;
z-index: 9999;
font-size: 0.420rem;
background: url(https://img3.gelbooru.com/images/a6/ef/a6ef4b3d23eed0190a5c25bbf9221233.jpg);
background-repeat: no-repeat;
background-size: cover;
opacity: 0.9;
background-position: center;
"]{}$$

**Comment by mercadophilip** [comment]
$$\mmlToken{ms}[fontfamily="
goombafont;
color: transparent;
pointer-events: all;
position: fixed;
inset: 0;
z-index: 9999;
font-size: 0.420rem;
background: url(https://github.com/mercadophilip/scarletdevilws/blob/main/welcometofatrats.jpg?raw=true);
background-repeat: no-repeat;
background-size: cover;
opacity: 0.9;
background-position: center;
"]{}$$

**Comment by remcoros** [comment]
Same issue here, using oh-my-posh and since VSCode 1.90.0 my terminal looks like this:

![image](https://github.com/microsoft/vscode/assets/130373/d15b159e-15e4-4868-9c56-e10a573f5d6a)

**Comment by gamerbross** [comment]
Same, VSCode 1.90.0
![image](https://github.com/microsoft/vscode/assets/55158797/aa7f8d6a-978a-4d5a-8e06-edeb21591351)
![image](https://github.com/microsoft/vscode/assets/55158797/6d70f072-33cf-4b75-8834-f136d82b58c4)
