### ISSUE TITLE
This codespace is currently running in recovery mode, and check50: command not found

### ISSUE THREAD

**Issue by avchernetsov** [microsoft/vscode#214691]
ADD ISSUE DESCRIPTION HERE

Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Embedder: codespaces

codespaces-6516fc:/workspaces/168073574/numb3rs$ check50 cs50/problems/2022/python/numb3rs
bash: check50: command not found

This codespace is currently running in recovery mode due to a configuration error. Please review the creation logs, update your dev container configuration as needed, and run the "Rebuild Container" command to rectify.

![Снимок экрана от 2024-06-08 16-17-22](https://github.com/microsoft/vscode/assets/168073574/c843f4f0-3374-43cb-bce9-8e4f9c294e99)

**Comment by avchernetsov** [comment]
The problem is solved. I Rebuild Container.

**Comment by connor4312** [comment]
Please open an issue on the codespaces extension https://github.com/orgs/community/discussions/new?category=codespaces
