### ISSUE TITLE
Frame skipped from debugging during step-in.

### ISSUE THREAD

**Issue by jinec** [microsoft/vscode#214666]
Type: <b>Bug</b>

my launch.json is :
        {
            "name": "Python 调试程序2",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false
        },
Currently, I am unable to access the third-party plugin code library.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 5.4.0-173-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.33GB free)|
|Process Argv|--crash-reporter-id 355d7c60-19c6-4c73-a57e-705f1ac85de4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 219.159.22.37|
|OS|Linux x64 5.4.0-173-generic|
|CPUs|Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz (128 x 900)|
|Memory (System)|1007.53GB (951.63GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.4.3
vscode-django|bat|1.15.0
vscode-markdownlint|Dav|0.55.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
vsc-python-indent|Kev|1.18.0
vscode-language-pack-zh-hans|MS-|1.89.2024050109
debugpy|ms-|2024.7.11591012
python|ms-|2024.8.0
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
makefile-tools|ms-|0.10.9
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
pythonpack|shi|0.3.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by sam-bercovici** [comment]
I concur. 
With version 1.90.0 debugging python code and stepping into third party libraries when "justMyCode": false stopped working.
Reverted back to version 1.89.1 and the functionality is working.

**Comment by AlexandreOuellet** [comment]
Did you mean justMyCode: true?  I couldn't step into 3rd party libs with justMyCode: false before.  with 1.90.0, I can with justMyCode: true, but for some reason, everytime I step into the 3rd party libs, the call stack goes back into my code.  I need to re-expand the callstack, and select where I was again.  It is so annoying that I had to revert to 1.89

**Comment by jaydosi** [comment]
See also issue #214433 that goes into more detail. I would mark this as duplicate.

**Comment by sam-bercovici** [comment]
Hi @AlexandreOuellet , AFIK, **justMyCode: _false_** means that I can step debug (F11) into 3rd party code which is not my own.
This is what's broken in 1.90.0.

@jaydosi , [#357](https://github.com/microsoft/vscode-python-debugger/issues/357) and [#359](https://github.com/microsoft/vscode-python-debugger/issues/359) are same as the current issue.
If [#214433](https://github.com/microsoft/vscode/issues/214433) is covering both of them, then this is a duplicate.

**Comment by AlexandreOuellet** [comment]
@sam-bercovici : You are entirely correct, I stand corrected (and I also needed some sleep...)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/214433
