### ISSUE TITLE
Can not watch the hole linklist in golang when debugging

### ISSUE THREAD

**Issue by NachtZ** [Microsoft/vscode#21462]
I can not watch a hole linklist's value when debugging. For example:
```
type linkNode struct {
	Val  int
	Next *linkNode
}

func test(root *linkNode) {
	for root != nil {
		fmt.Print(root.Val, " ")
		root = root.Next
	}
	fmt.Println()

}
func main() {
	var root linkNode
	tmp := &root
	for i := 1; i < 10; i++ {
		tmp.Next = &linkNode{
			i,
			nil}
		tmp = tmp.Next
	}
	test(&root)

}

```
when running this code and set a breakpoint in `test(&root)`, I can only read  `root` and `root.Next` in `Variables` . If I want to watch deeper, I need to set watch the value `root.Next.Next`, and the watch of `root.Next.Next` also can olny see 2 level deeper.

- VSCode Version: 1.911
- OS Version: Windows 10/x64
- Golang Version: go version go1.6.2 windows/amd64

Steps to Reproduce:

1. run the code
2. set breakpoint in `test(&root)`
3. Look at pannel `Variables` and `Watch`

**Comment by roblourens** [comment]
Typically the debugger lets you look at individual objects and their properties. It doesn't know that you have a linked list, or how to interpret that class. If there's something else the debug adapter can do, please file a feature request on the Go extension.
