### ISSUE TITLE
Profiles - double click on profile should make it in use

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#214618]
Double click on a Profile in the Profiles list should make it in use.
This way the only way to Use a profile is to use context menu - awkward interaction.

![Image](https://github.com/microsoft/vscode/assets/1926584/9b069a04-ae37-4d3d-92f2-0f014a016210)

**Comment by sandy081** [comment]
> Double click on a Profile in the Profiles list should make it in use.

Using a Profile to current window is an action that brings lot of changes. Generally, I would expect double clicking on an entry to open that. If this interaction changes my profile I will be very surprised. I would like an explicit interaction to switch the profile for a current window. I also believe switching a profile on a workspace is done less often once you have set the profile.
