### ISSUE TITLE
My problem 

### ISSUE THREAD

**Issue by nada589** [microsoft/vscode#214694]
### Description
I am unable to get Java output in the OUTPUT panel in Visual Studio Code on macOS.

### Steps to Reproduce
1. Install OpenJDK 17 on macOS.
2. Install Visual Studio Code and the Java Extension Pack.
3. Create a simple Java file with a `main` method that prints "Hello, World!".
4. Attempt to run the Java file using the Run button in VS Code.

### Expected Behavior
The output "Hello, World!" should be displayed in the OUTPUT panel.

### Actual Behavior
No output is displayed in the OUTPUT panel.

### Environment
- macOS Version: [your macOS version]

**Comment by roblourens** [comment]
You might need to look in the Debug Console, not Output. See https://code.visualstudio.com/docs/languages/java for more and file an issue on the Java extension repo if you think there's a bug
