### ISSUE TITLE
input method bar misplaced on 4K resoluation

### ISSUE THREAD

**Issue by bravomikekilo** [Microsoft/vscode#21464]
HiDPi
OS Version: Ubuntu 16.10

Steps to Reproduce:

1. Install vscode
2. input some Chinese chars
![screenshot from 2017-02-27 10-49-54](https://cloud.githubusercontent.com/assets/17548436/23347078/8e5eee3c-fcda-11e6-8cfc-8616bb8ee965.png)
![screenshot from 2017-02-27 10-46-58](https://cloud.githubusercontent.com/assets/17548436/23347085/9917e3ba-fcda-11e6-9a69-ad14dee063df.png)

The problem maybe cause by the window scaling of the gnome

**Comment by roblourens** [comment]
Same as #13093
