### ISSUE TITLE
Ctrl + C doesnt work on external terminal

### ISSUE THREAD

**Issue by VyrekXD** [microsoft/vscode#214655]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0
- OS Version: Windows 11 23H2

Steps to Reproduce:

1. Set terminal on windows to cmd.exe
2. Open external terminal and run a code that makes the script run indefinitely or sleep
3. try to use ctrl + c

**Comment by meganrogge** [comment]
this is not a VS Code issue if it's happening in an external terminal

**Comment by VyrekXD** [comment]
It's literally just the terminal vs code opens
