### ISSUE TITLE
git commands are very slow to execute and return to prompt in bash terminal

### ISSUE THREAD

**Issue by IngridAtMicrosoft** [microsoft/vscode#214634]
Type: <b>Performance Issue</b>

git commands are very slow to execute and return to prompt in bash terminal

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (19.34GB free)|
|Process Argv|--crash-reporter-id 886f0b6e-bc1b-410b-98a3-7ff6f17bec7e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   107	  9856	code main
    0	    89	   276	ptyHost
    0	     6	  1628	     conpty-agent
    0	     5	 16248	     "C:\Program Files\Git\bin\bash.exe" --init-file "c:\Users\inhenkel\AppData\Local\Programs\Microsoft VS Code\resources\app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"
    0	    11	  5124	       "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --init-file "c:\Users\inhenkel\AppData\Local\Programs\Microsoft VS Code\resources\app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"
    0	    28	  9376	   crashpad-handler
    0	    96	 10944	window [2] (Issue Reporter)
    0	   180	 11988	extensionHost [1]
    0	    40	 12396	   utility-network-service
    0	   106	 12896	shared-process
    0	   208	 15076	   gpu-process
    0	   204	 17048	window [1] (Settings - azure-video-indexer - Visual Studio Code)
    0	    87	 17792	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings - azure-video-indexer - Visual Studio Code)
|    Folder (azure-video-indexer): 331 files
|      File types: png(150) md(105) jpg(9) svg(7) yml(6) json(2) mp4(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.2.3
vs-code-xml-format|fab|0.1.5
vscode-dotnet-runtime|ms-|2.0.5
debugpy|ms-|2024.6.0
python|ms-|2024.8.0
vscode-pylance|ms-|2024.6.1
powershell|ms-|2024.2.2
vscode-yaml|red|1.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by martin-blostein-innovasea** [comment]
I wonder if this is the same issue I am seeing with 1.90.0. For me, all commands using git bash in the integrated terminal take ~5 seconds to return. Even just an empty command.

There is no delay when using Git Bash outside of VSCode, or when using other terminals within VSCode. Disabling all extensions did not fix the issue, but downgrading to 1.89.1 did.

**Comment by IngridAtMicrosoft** [comment]
I disabled this setting and that fixed it. You also have to delete the terminal session and restart VSC.
terminal.integrated.shellIntegration.enabled

**Comment by boltex** [comment]
I also noticed this lately, even changing folder, i.e. "cd someFolder" takes 5-6- seconds to show the next prompt!
