### ISSUE TITLE
Double-click anywhere on an un-pinned editor should pin it

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#21466]
- VSCode Version: Code - Insiders 1.10.0-insider (b2a55bd66eb60af11c60ddd61b7581538b216051, 2017-02-24T20:30:00.778Z)
- OS Version: Darwin x64 16.4.0

Currently the only way to "pin" an editor is either to double-click on the tab itself or start editing. It would be nice if just double-clicking on the editor itself would cause it to be pinned -- that way you don't have to travel so far when attempting to open multiple files.

**Comment by bpasero** [comment]
I suggest to use this action which is bound by default:

`{ "key": "cmd+k enter", "command": "workbench.action.keepEditor" }`
