### ISSUE TITLE
Profiles - "Open" is too generic action name

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#214620]
Right now the action is called "Open". This action name is too generic, and does not mention that a new window will be opened.
I suggest to instead go with the "Safari" naming. "New PROFILE_NAME Window"

![Image](https://github.com/microsoft/vscode/assets/1926584/b23de5c0-06a6-408e-bf86-2b87a7f15e6d)

**Comment by sandy081** [comment]
I also have Open Profile actions in the File menu

![Image](https://github.com/user-attachments/assets/12ded458-4b31-473b-b7d8-6f64411ad813)

This is feedback from @joaomoreno.

**Comment by sandy081** [comment]
Fixed

![Image](https://github.com/user-attachments/assets/474ac349-8184-4ac5-9f1d-ff3efc04e563)



![Image](https://github.com/user-attachments/assets/4d35ef41-c952-4f90-81f3-e55b33c8a2fe)

**Comment by isidorn** [comment]
Thanks. This is great!
