### ISSUE TITLE
Terminal freezes after executing any command

### ISSUE THREAD

**Issue by Vilbat** [microsoft/vscode#214607]
Does this issue occur when all extensions are disabled?: Yes

- 1.90 - Latest version as of 7th june: 
- Windows 11 Pro: 

Steps to Reproduce:

1. Install git
2. Use bash in the vs code integrated terminal
3. Run any command such as ls

After pressing enter, the command runs at usual speed. But the terminal is frozen for 1-2 seconds after executing any command. This issue does not occur when running powershell in the integrated terminal. I've downgraded to version 1.89 which works fine and there is no freezing.

**Comment by Ponjimon** [comment]
Why have you closed this, did you find a solution?
