### ISSUE TITLE
Package with Additional Extensions

### ISSUE THREAD

**Issue by andrewhertog** [microsoft/vscode#214633]
I want to create a build of this which automatically installs additional extensions, either from Github or from the Extensions library.

Is this possible, and if so, how can I accomplish this?

I've attempted to add it to the "builtin Extensions" section of the product.json. The extension installs but doesn't want to activate and run. It keeps saying the extension needs to restart. I assume the extensions need some modification to work as a Builtin Extension.

**Comment by IllusionMH** [comment]
There are Extension packs already https://code.visualstudio.com/api/references/extension-manifest#extension-packs
Does it work for your case?

**Comment by isidorn** [comment]
Thanks for opening this issue. What exactly are you trying to achieve here?

**Comment by isidorn** [comment]
For that I suggest to use Profiles or an Extension Pack.

https://code.visualstudio.com/docs/editor/profiles
https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup

Building VS Code with more built-in extensions is not the right path to achieve this.
