### ISSUE TITLE
Integrated terminal fails to respect foreground colour VT sequence

### ISSUE THREAD

**Issue by pfmoore** [microsoft/vscode#214696]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.90.0 (user setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Start the integrated terminal (with powershell as the shell)
2. Enter the following text:
```
"`e[48;2;138;118;156m`e[38;2;255;255;255mhello`e[0m"
```
3. The following output is displayed:
![image](https://github.com/microsoft/vscode/assets/1110419/ee6ee751-15e6-4b03-9e3e-f62dffc8c402)

Note that the text is in a dark colour (near-black) when the VT code requests white.

**Comment by meganrogge** [comment]
what happens if you change the value of `terminal.integrated.minimumContrastRatio`?

**Comment by meganrogge** [comment]
This is intentional to meet accessibility standards. We have the setting so that if you dislike that, you can change it.
