### ISSUE TITLE
Migrating VS 2015 C# Windows Universal app Missing TargetFrameWorkVersion 4.5.2

### ISSUE THREAD

**Issue by WallyZambotti** [Microsoft/vscode#21470]
- VSCode Version:
dotnet --info output:
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
Version: 1.0.0-rc4-004771
Commit SHA-1 hash: 4228198f0e

Runtime Environment:
OS Name: ubuntu
OS Version: 16.04
OS Platform: Linux
RID: ubuntu.16.04-x64
Base Path: /usr/share/dotnet/sdk/1.0.0-rc4-004771
VS Code version:
1.9.1
C# Extension version:
1.7.0

Steps to Reproduce:

1.Open a VS 2015 Community Edition Visual C#/Windows/universal Solution/Project
2. dotnet restore
3. dotnet build

Build FAILED.

/usr/share/dotnet/sdk/1.0.0-rc4-004771/Microsoft.Common.CurrentVersion.targets(1111,5): error MSB3644: The refere
nce assemblies for framework ".NETFramework,Version=v4.5.2" were not found. To resolve this, install the SDK or T
argeting Pack for this framework version or retarget your application to a version of the framework for which you
have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (
GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for
the framework you intend. [/home/wallyz/DBTransferImportAgent/DropBoxTransferAgent.csproj]
0 Warning(s)
1 Error(s)

Additional Comments

I have tried changing the framework to a variety of different versions but none are found.

Pointers to some documentation for supported .Net target frameworks would be appreciated. I recall reading something on the web but now can't find anything.

Also tried the dotnet msbuild with same results.

**Comment by isidorn** [comment]
This repository is for filing bugs for VS Code, not VS 2015 community.
It seems like you are having issues with dotnet, consider filing this bug here https://github.com/Microsoft/dotnet

**Comment by WallyZambotti** [comment]
So what you are saying is .net is not supported by vs code.

Then the only problem was my expectation!

Sent from my Sony Xperia™ smartphone on the Telstra™ Mobile network

---- Isidor Nikolic wrote ----

**Comment by isidorn** [comment]
.net is supported by vscode, you just need to use the C# extension
