### ISSUE TITLE
Font scaling issue in VSCode folder opening dialog

### ISSUE THREAD

**Issue by n-r-w** [microsoft/vscode#214794]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0
- OS Version: Kubuntu 24.04

Steps to Reproduce:

1. Set system global scale to 125% in KDE display configuration
2. Click File->Open Folder in vscode
3. As a result, the folder opening dialog box will have a very small font compared to other applications

For example. Left - Kate editor, right - vscode
![2024-06-10_19-05](https://github.com/microsoft/vscode/assets/38435980/5c2e1832-d550-4801-a3a8-a378946865d0)

**Comment by deepak1556** [comment]
The runtime just calls into xdg-desktop-portal for the file dialogs, I don't see how we can control the scaling of the native dialogs. Closing as non actionable.
