### ISSUE TITLE
make the editor font zoom shortcuts trigger the new terminal zoom commands when terminal has focus

### ISSUE THREAD

**Issue by yg-i** [microsoft/vscode#214718]
I'd like to request that these three commands introduced in Feb this year, and unbound by default, be bound to the standard editor font zoom keys (ctrl+= for zoom in, ctrl+- for zoom out, ctrl+0 for zoom reset) when terminal has focus.

![image](https://github.com/microsoft/vscode/assets/148152939/e4a40bf9-9213-4c04-bd40-4cc6e2ae5804)

AFAIC these bindings do not conflict with any existing ones, and arguably better conform to user expectations.

At the very least, I'd like know how to write a when-expression that will allow me to do this on my own!

**Comment by Tyriar** [comment]
ctrl+-/+ resize the whole window, not just the editor. We can't replace that as it would be inconsistent
