### ISSUE TITLE
Support "Paste" & "Paste and Indent" 

### ISSUE THREAD

**Issue by BigYu** [Microsoft/vscode#21471]
In the Sublime Text we have ctrl + v/ctrl + shift + v for paste/paste and indent.
Could code support this?

It'll be even better to make paste and indent as default pasting behavior.

**Comment by roblourens** [comment]
There is `"editor.formatOnPaste": true`. Does that cover this case?

**Comment by isidorn** [comment]
Closing until more details are provided
