### ISSUE TITLE
\x0d\x0a$ in terminal

### ISSUE THREAD

**Issue by Less24H** [microsoft/vscode#214746]
<img width="552" alt="Screenshot 2024-06-10 071112" src="https://github.com/microsoft/vscode/assets/124092534/6cf4a282-537b-4f43-86fa-0279df9f546d">
Type: <b>Bug</b>

Hello,

I have an issue, everytime i'm using terminal after type something and enter it always show this "\x0d\x0a$" and it delayed 5 seconds. It's annoying and waste of time.

Can someone tell what is that and how to remove it?

Thank you

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.47GB free)|
|Process Argv|--crash-reporter-id f0d9da8c-c35f-43ff-8301-d4b628a976da|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
html-snippets|abu|0.2.1
vscode-color|ans|0.4.5
vscode-intelephense-client|bme|1.10.4
vscode-tailwindcss|bra|0.10.5
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
vscode-eslint|dba|2.4.4
jquerysnippets|don|0.0.1
bracket-pair-toggler|dzh|0.0.3
vscode-html-css|ecm|2.0.9
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
vue-snippets|hol|1.0.4
vscode-env|Iro|0.1.0
vscode-colorize|kam|0.11.1
vscode-gutter-preview|kis|0.31.2
vscode-duplicate|mrm|1.2.1
debugpy|ms-|2024.6.0
python|ms-|2024.8.0
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
vscode-typescript-next|ms-|5.5.20240505
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|5.3.0
vscode-css-peek|pra|4.4.1
cody-ai|sou|1.20.3
errorlens|use|3.18.0
volar|Vue|1.8.27
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.34.0
php-pack|xde|1.0.3
html-css-class-completion|Zig|1.20.0
php-intellisense|zob|1.3.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
2f103344:31067618
26j00206:31048877

```

</details>

**Comment by gjsjohnmurray** [comment]
Are you using git bash? If so please see the related pinned issue.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed
