### ISSUE TITLE
Extensions cannot override console.log

### ISSUE THREAD

**Issue by boltex** [microsoft/vscode#214735]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.90.0 (user setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

I'm writing a vscode extension. I want to temporarily override the console.log behavior, so I did this :

                this.old = console.log;
                console.log = this.write.bind(this);

(write is a method of a class in my extensions, I kept the real console.log in an 'old' variable to set it back to normal shortly afterward.)

Problem is that this does not seem to actually reassign the "log" method of the console.

Is the console object instance protected in extensionHosts process of vscode or something?

**Comment by connor4312** [comment]
Yes, this is intentional. Extensions all run in the same context and we do not want extensions to intentionally and overwrite this in a way that would interefere with other extensions.
