### ISSUE TITLE
Moving lines down should not affect indentation

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#214779]
Have the following code

```
if (model) {
				model.sendRequest(messages, options, token)
				const messages = [
					vscode.LanguageModelChatMessage.User(`Not sure how the message is being used `),
					vscode.LanguageModelChatMessage.User(request.prompt)
				];
					
				const chatResponse = await model.sendRequest(messages, {}, token);
				for await (const fragment of chatResponse.text) {
					// Process the output from the language model
					// Replace all python function definitions with cat sounds to make the user stop looking at the code and start playing with the cat
					const catFragment = fragment.replaceAll('def', 'meow');
					stream.markdown(catFragment);
				}
			}
```

Move line mode.send request down via `ctrl+down-arrow`
Notice how the lines that have been passed change. Their indentation gets modified. The move line down command should not mutate lines it passes.

https://github.com/microsoft/vscode/assets/1926584/76af7e66-6422-4161-8841-c79838fd6f1e

**Comment by ArturoDent** [comment]
See https://github.com/microsoft/vscode/issues/214569 and https://github.com/microsoft/vscode/issues/214562 for similar/duplicates.

**Comment by aiday-mar** [comment]
should be fixed by https://github.com/microsoft/vscode/pull/214577

**Comment by isidorn** [comment]
Thanks for the fix!
