### ISSUE TITLE
Check VS Code Compilers & Extensions are Ok

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/vscode#214763]
Type: <b>Bug</b>

I am not sure how to phrase it.  But I would like VS Code to be able to check that the extensions installed in it are correct with the language compilers from third party sources.  For example, if I installed the C/C++ extension, it should load the correct C/C++ compiler (in this case, VS IDE C/C++ compiler and MinGW) without going on an complain that it needs LLVM etc. I have also encountered issues such as the Java Language Server cannot load when I have a valid OpenJDK 21 installed. These issues make coding in VS Code unpleasant. 

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (7.94GB free)|
|Process Argv|--crash-reporter-id 3ab84b27-3b66-48e1-b94b-f4055dc42152|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|2.0.5
fsharp-interactive-datascience|and|1.0.12
vscode-django|bat|1.15.0
django-html|bib|1.3.0
path-intellisense|chr|2.9.0
c-cpp-compile-run|dan|1.0.58
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
code-runner|for|0.12.2
dotnet|for|0.0.4
c-cpp-runner|fra|9.4.8
fsharp-language-server|geo|0.1.28
vscode-javac|geo|0.2.46
vscode-test-explorer|hbe|2.21.1
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|7.20.1
c-cpp-flylint|jbe|1.15.0
cpptask|kay|0.0.1
vsc-python-indent|Kev|1.18.0
csharpextensions|kre|1.7.3
vscode-language-babel|mgm|0.0.40
vscode-clang|mit|0.2.4
csdevkit|ms-|1.6.8
csharp|ms-|2.31.19
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.0.5
vscodeintellicode-csharp|ms-|2.1.11
debugpy|ms-|2024.6.0
python|ms-|2024.8.0
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
cmake-tools|ms-|1.18.41
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
test-adapter-converter|ms-|0.1.9
godot-csharp-vscode|nei|0.2.1
autodocstring|njp|0.6.1
java|red|1.31.0
csharp-snippet-productivity|ric|2.1.1
LiveServer|rit|5.7.9
code-spell-checker|str|3.0.1
tabnine-vscode|Tab|3.106.0
python-extended-snippets|tus|0.0.1
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscodeintellicode-completions|Vis|2.0.0
vscode-gradle|vsc|3.13.5
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0
vscode-spring-initializr|vsc|0.11.2
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
The check (and possible warnings) should happen in the  C/C++ resp Java extensions. VS Code doesn't have any C++ knowledge by itself.
Please create an issue here: https://github.com/Microsoft/vscode-cpptools/issues
