### ISSUE TITLE
explorer problem

### ISSUE THREAD

**Issue by shivamagrawaldz** [microsoft/vscode#214740]
https://github.com/microsoft/vscode/assets/171699548/10d3931e-b342-421e-8928-07546e851702

https://github.com/microsoft/vscode/assets/171699548/747c2a89-4e35-4072-8323-f80689ce5627

Type: <b>Feature Request</b>

it is not showing open folder button below explorer even if i choose to open folder from file open then open folder this also not working , i attach two videos below one of vs code and onother one is of vs code insider in which that feature is okay

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x6

https://github.com/microsoft/vscode/assets/171699548/3527f875-acd7-488d-bc40-4de640b92bf7

https://github.com/microsoft/vscode/assets/171699548/9f6dee7c-7ab5-4aa3-881b-8f2a30cde336

https://github.com/microsoft/vscode/assets/171699548/2ddb552c-5abd-48fa-b51f-c8c416ec5432

4 10.0.22631
Modes:

**Comment by IllusionMH** [comment]
Execute `> View: Reset View Locations` in Command Palette (<kbd>F1</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

**Comment by shivamagrawaldz** [comment]
Thankyou very much Microsoft team
This thing ruined my whole one day and even I didn't get the solution
Ur solution is just 300 damaged aim like head shot thanks a lott❤️❤️❤️
