### ISSUE TITLE
Context menu display issue on sidebars

### ISSUE THREAD

**Issue by jdbruxelles** [microsoft/vscode#214710]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.0
- OS Version: Windows 11

The context menu in VSCode is not displaying correctly when I right-click on an embedded editor. As shown in the screenshot, the menu items are cut off and not fully visible. This issue makes it difficult to use the context menu effectively.

![Screenshot showing the context menu not correctly displayed](https://github.com/microsoft/vscode/assets/18559798/ad3f85f5-e196-461c-aa03-41099bdb2d5d)

Steps to Reproduce:

1. Open GitHub Copilot on Side bar (left or right).
2. Ask for a code snippet...
3. You got an answer containing preformatted code.
4. Right-click on an element or somewhere in the editor.
5. Observe that the context menu appears but is not fully displayed (You may have to right-click at the very end/start of the window for the context menu to be displayed in the opposite direction).

Expected Behavior:

The context menu should be fully visible, with all menu items displayed correctly.

**Comment by mjbvz** [comment]
I believe this has been fixed. Please let me know if you're still seeing this in VS Code 1.93+

**Comment by jdbruxelles** [comment]
Yes. Seems to be fixed. Thanks.

<details>
<summary>Details</summary>

![Screenshot of resolved UI issue](https://github.com/user-attachments/assets/9f89063f-b52b-440c-8c53-e232f7600be7)

</details>
