### ISSUE TITLE
Support line ranges in links and to navigate to file to a particular line column

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#21472]
The output window supports (hardcoded) local links to line ranges in its [LinkComputer](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/common/outputLinkComputer.ts#L83). The set of regular expressions matches the error messages from common build tools. It would be useful to also support this in the integrated terminal. 

Supporting links to line column would also cover #21401.

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/issues/24832
