### ISSUE TITLE
Can not add debug point while running a project for flutter

### ISSUE THREAD

**Issue by sa3951** [microsoft/vscode#214783]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.90.0 (Universal)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:34:44.157Z (5 days ago)
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0 
- OS Version: MacOS 14.5 (23F79)

Steps to Reproduce:

1. Add break point when app is running in iOS simulator

https://github.com/microsoft/vscode/assets/75849634/c78905c7-693c-473f-9f11-7770a6806ee6

**Comment by roblourens** [comment]
Please file this on the repo for the debug extension

**Comment by sa3951** [comment]
Thanks @roblourens !
