### ISSUE TITLE
VSCode 1.9.1 crashes when using git compare a large file

### ISSUE THREAD

**Issue by Teamop** [Microsoft/vscode#21475]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.6|
|githistory|donjayamanne|0.1.5|
|EditorConfig|EditorConfig|0.3.4|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. I have a file which is about 15.6M, upgrade to vs code 1.9.1 version, then the use the git panel to compare with history, it crashes most of the time or loads very very slowly. I notice for version 1.9, vs code has some changes about git implementation. In the previous version, I don't have this issue.

Thanks for your help in advance

**Comment by joaomoreno** [comment]
Do you have `Preview SCM` enabled?

**Comment by Teamop** [comment]
No, I don't have Preview SCM enabled

**Comment by joaomoreno** [comment]
Which version worked for you? Can you send us the file?

@alexandrudima This might be updated syntax colouring together with the diff editor?

**Comment by Teamop** [comment]
For me, this issue is after version 1.9, in the previous version, I didn't have this issue.
I can not send the file, but it's just a JS file.

**Comment by joaomoreno** [comment]
Is it minified?

**Comment by Teamop** [comment]
no, not minified. just concatenation

**Comment by alexandrudima** [comment]
@Teamop I wonder if you are running into an Out-Of-Memory situation.

For files < 20MB, we:
* allow for tokenization to occur
* allow for diffing to occur

When I diffed on my machine a 4MB js file with a 16MB js file, I saw the following heap usage:
* renderer process: 209MB (logical heap usage)
* worker thread: 37MB (logical heap usage)

The Resident Set Size (linux 64 bit) for the renderer process is 831MB.

@Teamop can you check with process explorer the VSCode processes and report here the memory usage. I'm thinking perhaps we shouldn't tokenize such large files (to reduce memory pressure)

**Comment by Teamop** [comment]
sure, I will get to you tomorrow. thanks

**Comment by Teamop** [comment]
@alexandrudima 
memory usage:
1. just open the project
![image](https://cloud.githubusercontent.com/assets/8519685/23447085/6edeed0a-fe83-11e6-913c-601589d7159c.png)
1. diff files
tried with a dozen time, actually today it worked at first, even though sometimes too long to respond, but clicked "continue to wait", it still worked.
But finally, it didn't respond and like frozen. Then the memory usage at this time:
![image](https://cloud.githubusercontent.com/assets/8519685/23448544/9f602ce2-fe8c-11e6-9789-17896ad84bec.png)
Just two processes left:
- "C:\Program Files (x86)\Microsoft VS Code\code.exe" --type=gpu-process --channel="1196.0.1061925480\801745167" --mojo-application-channel-token=A65C84CDD1DCD0A4B62D88865CA62107 --no-sandbox --disable-d3d11 --disable-direct-composition --supports-dual-gpus=false --gpu-driver-bug-workarounds=5,11,13,14,15,18,31,48,56 --gpu-vendor-id=0x8086 --gpu-device-id=0x0166 --gpu-driver-vendor="Intel Corporation" --gpu-driver-version=8.15.10.2725 --gpu-driver-date=4-9-2012 --gpu-secondary-vendor-ids=0x0000;0x10de --gpu-secondary-device-ids=0x0000;0x0def --mojo-platform-channel-handle=1052 /prefetch:2
- "C:\Program Files (x86)\Microsoft VS Code\code.exe" "c:\Program Files (x86)\Microsoft VS Code\resources\app\out\bootstrap" --type=SharedProcess

**Comment by alexandrudima** [comment]
I've tried generating large files via. These are the worst-case scenario for diffing where each line is different:

```js
var fs = require('fs');

var str = '';
for (var i = 0; i < 100000; i++) {
    str += 'imgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimgimg-' + Math.floor(Math.random() * 10000000) + '.pdf\n';
}
str + 'hi';

fs.writeFileSync('out.txt', str);
```

and I could not cause a crash to occur. 

@Teamop Please let me know if you can share files that cause crashes or scripts that generate files that cause crashes. Also, using the 64 bit version of VSCode might alleviate the memory pressure.

**Comment by Teamop** [comment]
@alexandrudima Now I use the latest stable 64 bit version 1.16.1, and I haven't met this issue for a long time.
