### ISSUE TITLE
light bulb (code action) not display when text only has one line

### ISSUE THREAD

**Issue by wszgrcy** [microsoft/vscode#214711]
Does this issue occur when all extensions are disabled?: Yes

compile vscode with commit d40dff9ef9aacb8e5226bcf3938c71f4b9543120
Version: 1.91.0
Commit: Unknown
Date: Unknown
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

I find if text length> 2(like hello) ,and select start>1( like llo).bulb can display

![image](https://github.com/microsoft/vscode/assets/9607121/02aab498-61cf-4007-9a49-f8b9ee106988)
select start less than 2.not display
![image](https://github.com/microsoft/vscode/assets/9607121/080e6daa-8439-4a72-87f6-7a1e7c429314)

code action always return array

```ts
export class CodeActionService
  implements vscode.CodeActionProvider
{
  #prompt = inject(PromptService);
  public static readonly providedCodeActionKinds = [
    vscode.CodeActionKind.Refactor,
  ];
  async provideCodeActions(
    document: vscode.TextDocument,
    range: vscode.Range | vscode.Selection,
    context: vscode.CodeActionContext,
    token: vscode.CancellationToken,
  ): Promise<(vscode.CodeAction | vscode.Command)[]> {
    if (
      range.start.line === range.end.line &&
      range.start.character === range.end.character
    ) {
      return [];
    }

    const list = await this.#prompt.actionConfig.get();
    if (!list) {
      return [];
    }
    console.log(list);

    return list.map((item) => {
      const codeAction = new vscode.CodeAction(
        item.title,
        vscode.CodeActionKind.Refactor,
      );
      return codeAction;
    });
  }
  resolveCodeAction(
    codeAction: vscode.CodeAction,
    token: vscode.CancellationToken,
  ): vscode.ProviderResult<vscode.CodeAction> {
    return codeAction;
  }
}
```

**Comment by justschen** [comment]
this should be fixed in our latest release. this was fixed with a new heuristic which now spawns it in the best case scenario, including the gutter when available. https://github.com/microsoft/vscode/pull/221419 please update and try it out, thanks!
