### ISSUE TITLE
cant choose programming language

### ISSUE THREAD

**Issue by andeemfdel** [microsoft/vscode#214789]
Type: <b>Performance Issue</b>

when i create new file, it just create an empty text file

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 2500U w/ Radeon Vega Mobile Gfx (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|14.93GB (6.81GB free)|
|Process Argv|--crash-reporter-id fdb6e70f-953a-4a87-a448-8572783e23c6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   109	  1532	code main
    0	    26	  3228	   crashpad-handler
    0	   365	  4656	window [2] (Untitled-1 - Visual Studio Code)
    0	    89	  5836	ptyHost
    0	    38	  7164	   utility-network-service
    0	   108	 12048	shared-process
    0	   127	 14628	   gpu-process
    0	    87	 15896	fileWatcher [2]
    0	   152	 17724	extensionHost [2]
    0	    95	 17920	window [3] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.6.6
htmlplay|bia|0.0.10
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
laravel-goto-view|cod|1.3.11
devdb|dam|1.10.0
vscode-eslint|dba|2.4.4
composer-php-vscode|DEV|1.47.15512
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.47.15512
profiler-php-vscode|DEV|1.47.15512
vscode-html-css|ecm|2.0.9
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
cshtml|fir|0.1.3
errorhelper|FoP|1.1.1
html-preview-vscode|geo|0.2.5
laravel-create-view|gli|0.0.6
laravel-blade-wrapper|IHu|1.0.1
search-node-modules|jas|1.3.0
statusbarerror|Joe|0.4.0
vscode-codemetrics|kis|1.26.1
dotenv|mik|1.0.1
vscode-exec-node|mir|0.5.6
vscode-azurefunctions|ms-|1.15.0
vscode-azureresourcegroups|ms-|0.9.1
csdevkit|ms-|1.6.8
csharp|ms-|2.31.19
vscode-dotnet-runtime|ms-|2.0.5
vscodeintellicode-csharp|ms-|2.1.11
vscode-kubernetes-tools|ms-|1.3.16
live-server|ms-|0.4.13
mono-debug|ms-|0.16.3
vsliveshare|ms-|1.0.5918
laravel-goto-components|nao|1.2.0
godot-csharp-vscode|nei|0.2.1
vscode-for-node-js-development-pack|nod|2.0.1
laravel-blade|one|1.36.1
laravel-extension-pack|one|1.3.0
laravel5-snippets|one|1.18.0
laravel-jump-controller|pgl|0.0.33
java|red|1.31.0
vscode-yaml|red|1.15.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.9
laravel-artisan|rya|0.0.31
vscode-blade-formatter|shu|0.24.2
html-to-css-autocompletion|sol|1.1.2
bootstrap4-vscode|the|6.1.0
html-preview-vscode|tht|0.2.5
errorlens|use|3.18.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0
vscode-import-cost|wix|3.3.0
html-snippets|wsc|1.0.6
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
newcmakeconfigv2:31067619
26j00206:31048877

```

</details>

**Comment by arjunneo** [comment]
yes, using Ctrl + N in VS Code opens a blank text file. That's because VS Code is like a super-flexible workbench, not a program specifically built for one language like Java. So, it can't guess what kind of code you want to write right away.

The easiest way around this is to just make a new file (Ctrl + N) and then save it with a name that includes the right extension (like .py for Python or .js for JavaScript). VS Code will figure it out from there and help you code like a champ!

**Comment by IllusionMH** [comment]
In addition to answer above you can start typing or paste and rely on language detection, try `files.defaultLanguage`, change it from status bar or with `> Change Language Mode` command.
See https://code.visualstudio.com/docs/languages/overview#_change-the-language-for-the-selected-file
