### ISSUE TITLE
Double header, double actions in panel

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#214769]
* move timeline view into panel
* there are double headers and double actions

<img width="1500" alt="Screenshot 2024-06-10 at 11 41 38" src="https://github.com/microsoft/vscode/assets/1794099/4ab4b219-2643-4178-87d2-f3b718a8c0ac">

**Comment by gjsjohnmurray** [comment]
This comes from my PR #214010 which you recently approved.

Pinging @lramos15 too.

**Comment by jrieken** [comment]
Let's revert

**Comment by gjsjohnmurray** [comment]
Can we agree another way of having titleDescription visible then?

Pinging @daviddossett re https://github.com/microsoft/vscode/issues/166000#issuecomment-1310436092

**Comment by daviddossett** [comment]
I'll take a look at this during endgame or debt week
