### ISSUE TITLE
Translation input: can not find module iconv.node

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#21480]
1. Mac, follow steps in [OneNote](https://microsoft.sharepoint.com/teams/DD_OTP/_layouts/OneNote.aspx?id=%2Fteams%2FDD_OTP%2FDocuments%2FTicino%2FNotebooks%2FVSCode&wd=target%28Development.one%7C8557A876-0489-401B-A073-CECF1B859862%2FLocalization%20VSCode%7C50625778-369E-4422-9157-5E143C02A7DF%2F%29)
2. Get an error when trying to run scripts in the `MonacoLocalization` folder

`gulp import --component vscode/src --locData ../VSCode-darwin/resources/app/out/nls.metadata.json --dest .`

```
(node:15833) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
module.js:457
    throw err;
    ^

Error: Cannot find module '../build/Debug/iconv.node'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/isidor/Development/MonacoLocalization/lib/node_modules/iconv/lib/iconv.js:29:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

On a related note: transforming backward to forward slashes is error prone. The one note should also contain exact instructions for mac.

**Comment by dbaeumer** [comment]
@isidorn looks like iconv didn't get compiled for you on the Mac. 

Can you delete the node_modules folder and run npm install ?

**Comment by isidorn** [comment]
Yes, just delete node_modules and npm install finished without an error.
Running the scripts again produces the same error

**Comment by dbaeumer** [comment]
My fault :-). There is a lib directory which contains the library code. Can you try the following please:

- cd lib
- delete node_modules
- npm install
- cd ..
- run the command

**Comment by isidorn** [comment]
Thanks, after that the command finishes without any errors.
Now when running the second command I get an error, here's the command
`gulp import --components ../vscode/extensions/* --baseDir ../  --locData "**/*.nls.json" --dest .`

[11:54:37] Using gulpfile ~/Development/MonacoLocalization/gulpfile.js
[11:54:37] Task '../vscode/extensions/clojure' is not in your gulpfile
[11:54:37] Please check the documentation for proper gulpfile formatting

**Comment by dbaeumer** [comment]
May be it is easier if we sit together at your  Mac to understand what is happening. This could be a / \ problem on my end. It is looking at the wrong files. When will you be in again.

**Comment by isidorn** [comment]
This week I am working from remote, so next monday I am in the office and we can look at it together.

**Comment by dbaeumer** [comment]
OK. Lets have a look next Monday then.

**Comment by dbaeumer** [comment]
@isidorn we will replace the old story with Transifex beginning of April. Until then I will simply do the input from a windows machine.
