### ISSUE TITLE
feature request: optionally expose semantic tokens for markdown files, to enable customizing colors via `editor.semanticTokenColorCustomizations` (not just `editor.tokenColorCustomizations`) 

### ISSUE THREAD

**Issue by yg-i** [microsoft/vscode#214822]
Currently markdown files have rich language server support (via the built-in extension "Markdown Language Features"), but no semantic tokens have been made available for styling via decorations:

![image](https://github.com/microsoft/vscode/assets/148152939/a07a5b14-9ab8-44b4-89dc-6f1c60fcd4e1)

I'd like to request the ability to style e.g. code blocks and code spans via decorations, not just textmate scopes, since decorations are inherently more powerful.

Thanks for considering!

**Comment by mjbvz** [comment]
@aeschli Is this true:

> I'd like to request the ability to style e.g. code blocks and code spans via decorations, not just textmate scopes, since decorations are inherently more powerful.

I don't see a compelling reason to add semantic highlighting for md since text mate already works fine

**Comment by aeschli** [comment]
As much as possible should be done with grammar based syntax highlighting. Semantic highlighting is delayed and intended as an addition to syntax highlighting for cases where a language service that has the full understanding of the project is required.

See https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide from more information.

**Comment by mjbvz** [comment]
Thanks @aeschli. Closing since it sounds like this is already supported for normal syntax highlighting
