### ISSUE TITLE
Investigate the gpu process request for loading resource from pak files in snap

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#214830]
This is a continuation of https://github.com/microsoft/vscode/issues/212494 to implement a proper fix in the runtime or application as necessary.

**Known data points:**

* SIGTRAP when gpu tried to access resource bundle to load a label for assigning display name when computing vsync interval using the internal implementation rather than the gl extension. Also name from resource bundle is only requested for builtin-displays and not virtual https://source.chromium.org/chromium/chromium/src/+/main:ui/base/x/x11_display_util.cc;l=449-456

```
Crash reason:  SIGTRAP
Crash address: 0x0
Process uptime: 0 seconds

Thread 24 (crashed)
 0  code!ui::ResourceBundle::GetSharedInstance() [immediate_crash.h : 176 + 0x1]
 1  code!l10n_util::GetStringUTF8(int) [l10n_util.cc : 809 + 0x5]
 2  code!ui::BuildDisplaysFromXRandRInfo(ui::DisplayConfig const&, unsigned long*) [x11_display_util.cc : 448 + 0xd]
 3  code!ui::GetPrimaryDisplayRefreshIntervalFromXrandr() [x11_display_util.cc : 517 + 0xb]
 4  code!ui::(anonymous namespace)::XRandrHelper::GetInterval() [x11_xrandr_interval_only_vsync_provider.cc : 60 + 0x5]
 5  code!ui::XrandrIntervalOnlyVSyncProvider::GetVSyncParameters(base::OnceCallback<void (base::TimeTicks, base::TimeDelta)>) [x11_xrandr_interval_only_vsync_provider.cc : 77 + 0x5]
``` 

* Using gpu codepath from main process `--in-process-gpu` serves as a workaround.
* Debian package on the same system didn't trigger the crash codepath, very likely a different gl backend was used.

**Next steps:**

1) Compare gl initialization trace between snap 1.89 and 1.90, using the following categories `--enable-tracing="ozone,ui,gpu,toplevel,disabled-by-default-gpu.service,disabled-by-default-gpu.debug"`
2) Compare gl initialization trace between debian 1.90 and snap 1.90
3) Confirm if resource bundle access from gpu process is necessary moving forward.

**Comment by deepak1556** [comment]
This turned out to be a regression from https://chromium-review.googlesource.com/c/chromium/src/+/5098130 which causes the gpu process when using the software display compositor to reach into the resource bundle. Before the CL, gpu process will not call into `BuildDisplaysFromXRandRInfo` only the main process did.

**Comment by amunger** [comment]
@deepak1556 is there something to verify here?

**Comment by deepak1556** [comment]
This is related to the candidate issue https://github.com/microsoft/vscode/issues/212494 and I was just using it to track fixes. Nothing particular to verify for this particular issue, maybe confirm the checksums for both branches are same https://github.com/microsoft/vscode/blob/main/build/checksums/electron.txt vs https://github.com/microsoft/vscode/blob/1.90.2/build/checksums/electron.txt
