### ISSUE TITLE
importing module with backticks breaks IntelliSense

### ISSUE THREAD

**Issue by s130059660** [Microsoft/vscode#21488]
- VSCode Version: latest (1.10.0-insider)
- OS Version: Windows 10 + Docker

Steps to Reproduce:

1. import a module in node.js with backtick qoutation. Example: const fs = require(`fs`);

2. check IntelliSense autocomplete. Example: fs dot

With double quote, IntelliSense works:
![doublequote](https://cloud.githubusercontent.com/assets/22569741/23359586/f2dbb814-fcf7-11e6-86bc-b79663c2b62b.PNG)

However, with back-tick IntelliSense doesn't work.
![backtick](https://cloud.githubusercontent.com/assets/22569741/23359595/ff624012-fcf7-11e6-9a4f-9050dba38224.PNG)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14345
