### ISSUE TITLE
After Recent Update Select a language to get started. Start typing to dismiss, or don't show this again does not show up

### ISSUE THREAD

**Issue by GrimSleet721363** [microsoft/vscode#214851]
![Screenshot 2024-06-11 131940](https://github.com/microsoft/vscode/assets/172370233/32ca4d39-c243-45a3-ae7d-c85898c1f639)
![Screenshot 2024-06-11 131948](https://github.com/microsoft/vscode/assets/172370233/523be086-f782-49b1-9f81-4a15d40006c6)
Type: <b>Bug</b>

When you click on File - New Text File, there was a prompt which informs "Select a language to get started. Start typing to dismiss, or don't show this again", but after the recent update it seems that it has disappeared.
Even in settings workbench.editor.empty.hint is set to text the prompt does not show up.

Steps Tried to Fix it: 
1] Deleting settings.json file from Code folder in AppData
2] Disabling all installed extensions
3] Tried changing workbench.editor.empty.hint to hidden and then restarting VS Code to again changing workbench.editor.empty.hint to text and restarting to see if it helps.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.42GB (7.59GB free)|
|Process Argv|--crash-reporter-id 65fb2916-ead6-4070-911d-f4d38d141ac2|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
2f103344:31071589
26j00206:31048877

```

</details>

**Comment by starball5** [comment]
Related on r/vscode: [New Text File select file type missing?](https://reddit.com/r/vscode/comments/1ddlzzb/new_text_file_select_file_type_missing/)

**Comment by marium0505** [comment]
I used to have it enabled as well, but suddenly the promp was gone. 
I went through all the workbench settings, and finally found the setting. 

It seems like they changed the setting (ID) from `workbench.editor.untitled.hint` to `workbench.editor.empty.hint`, and when doing that set the setting to hidden regardless of the current value.

It's bad enough that they changed the setting ID (which I assume will break backup/restore of settings(.json)), but equally bad that they ignored current value (when it is compatible with the new setting values).

**Comment by starball5** [comment]
> It's bad enough that they changed the setting ID (which I assume will break the backup/restore of settings.json)

VS Code has features for migrating setting changes when there are schema changes like this. I'm too lazy right now to check that feature was used for this one.

**Comment by marium0505** [comment]
> VS Code has features for migrating setting changes when there are schema changes like this. I'm too lazy right now to check that feature was used for this one.

Fair enough.

**Comment by BTGRCohen** [comment]
I had the same issue where the hint disappeared in 1.90.x. 
I checked on1.89, and I didnt have workbench.editor.untitled.hint at all. Seems it was already set as workbench.editor.empty.hint, and was set as "text".
On 1.90.x, it's set to "text" by default, but I still don't get the prompt for new files. 
Tried setting to hidden, and then back to text, but no luck.
If i re-install 1.89, it works again. Anyone else have the same issue?

**Comment by GrimSleet721363** [comment]
> I used to have it enabled as well, but suddenly the prompt was gone. I went through all the workbench settings and finally found the setting.
> 
> It seems like they changed the setting ID from `workbench.editor.untitled.hint` to `workbench.editor.empty.hint`, and when doing that, set the setting to hidden regardless of the current value.
> 
> It's bad enough that they changed the setting ID (which I assume will break the backup/restore of settings.json), but equally bad that they ignored the current value (when it is compatible with the new setting values).

It could be broken for very sure, as even removing the settings.json filed does not helps.

**Comment by joyceerhl** [comment]
Duplicate https://github.com/microsoft/vscode/issues/214679, this is already fixed in Insiders. We did implement a migration from `workbench.editor.untitled.hint` to `workbench.editor.empty.hint` that has been in place for 9 months, so the old setting value should have been preserved under the new key name
