### ISSUE TITLE
Unable to stop read aloud in Github copilot chat window

### ISSUE THREAD

**Issue by mathaimon** [microsoft/vscode#214878]
Does this issue occur when all extensions are disabled?: No

Version: 1.90.0 (user setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Create a new chat in the copilot chat window.
2. Press the read aloud button to start reading
3. Press the read aloud button to stop reading

The read aloud in copilot chat window does not stop the voice even after clicking the `Stop Read Aloud` button. On subsequent clicks of the read aloud button new voices are being spawned along with the earlier voices but can't stop the voices.

**Comment by bpasero** [comment]
I cannot reproduce, when I click the :speaker: icon, I see the blue animation and can stop it either from there or from clicking the :speaker: icon again:

![Recording 2024-06-11 at 17 13 20](https://github.com/microsoft/vscode/assets/900690/d899ac62-b545-4e4c-81e9-440a21d37d1c)

**Comment by mathaimon** [comment]
Issue is fixed when I uninstalled and reinstalled both copilot and speech extensions

**Comment by mathaimon** [comment]
The issue just reappeared

https://github.com/microsoft/vscode/assets/64730205/8fc1ea5e-abbe-4f95-bc79-0023e780eee8
