### ISSUE TITLE
Enabling terminal suggest breaks Windows PowerShell

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode#214869]
Type: <b>Bug</b>

Whenever I type in PowerShell inside of VSCode, I get an error every character I type, screenshot below. This only happens inside VSCode, it does not happen if I open PowerShell from Windows Start (the error message indicates it's a script in the VSCode folder)

![image](https://github.com/microsoft/vscode/assets/849948/86f9053e-1c57-44a7-861b-2654eb322d98)

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (20.58GB free)|
|Process Argv|--crash-reporter-id 06338080-eec2-498d-98e0-cf3111dc1cde|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (105)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icalendar|af4|1.0.1
vscode-m3u|af4|1.0.0
vscode-caniuse|aga|0.5.0
case-change|Aka|1.0.2
rtf|ale|2.8.0
vscode-sqlite|ale|0.14.1
swagger-viewer|Arj|3.1.2
armview|ben|0.4.6
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.23.0
vscode-tldr|bmu|1.0.0
mermaid-markdown-syntax-highlighting|bpr|1.6.3
npm-intellisense|chr|1.4.5
gitignore|cod|0.9.0
disableligatures|Coe|0.0.10
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|2.4.4
rushcore|Dev|1.0.2
rushnav|Dev|1.0.2
githistory|don|0.6.20
xml|Dot|2.5.1
escaping-characters|drp|1.0.0
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.16.4
vscode-macros|EXC|1.4.1
git-project-manager|fel|1.8.2
scriptcsRunner|fil|0.1.0
vscode-firefox-debug|fir|2.9.10
url-encode|fle|1.1.0
shell-format|fox|7.2.5
macros|ged|1.2.1
matlab|Gim|3.0.2
vscode-pull-request-github|Git|0.88.1
gc-excelviewer|Gra|4.2.59
vscode-markdown-footnote|hou|1.0.0
vscode-favorites|how|1.11.0
rest-client|hum|0.25.1
path-autocomplete|ion|1.25.0
mediawiki|jak|2.1.0
markdown-katex|jef|0.1.4
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
vscode-peacock|joh|4.2.2
gpg|jva|1.1.1
docomment|k--|1.0.0
vscode-liquid-snippets|kil|2.0.3
gnuplot|mam|1.0.5
zotero|mbl|0.1.11
markdown-shortcuts|mdi|0.12.0
openapi-lint|mer|1.2.0
azure-pipelines|ms-|1.228.0
azure-dev|ms-|0.8.3
vscode-azureappservice|ms-|0.25.2
vscode-azurecontainerapps|ms-|0.7.0
vscode-azurefunctions|ms-|1.14.3
vscode-azureresourcegroups|ms-|0.9.0
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.15.3
vscode-azurevirtualmachines|ms-|0.6.5
vscode-bicep|ms-|0.27.1
vscode-cosmosdb|ms-|0.22.0
csharp|ms-|2.28.11
vscode-dotnet-runtime|ms-|2.0.5
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.22.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.1
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-ai-remote|ms-|0.48.0
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.2
azure-account|ms-|0.12.0
azurecli|ms-|0.6.0
hexeditor|ms-|1.10.0
live-server|ms-|0.4.13
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
vscode-node-azure-pack|ms-|1.2.0
azurerm-vscode-tools|msa|0.15.11
debugger-for-edge|msj|1.0.15
language-liquid|nei|0.1.1
bib|phr|0.3.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.14.0
kuskus-kusto-language-server|ros|3.1.3
kuskus-kusto-syntax-highlighting|ros|2.0.2
vscode-zipexplorer|sle|0.3.1
addDocComments|ste|0.0.8
msbuild-project-tools|tin|0.6.3
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
nanoid-generator|vk-|0.1.2
vscode-icons|vsc|12.7.0
JavaScriptSnippets|xab|1.8.0
t4-support|zbe|0.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by Tyriar** [comment]
That code should only be hit if you have the experimental `terminal.integrated.suggest.enabled` setting on. Disabling it should fix it, what version of PowerShell is that?

**Comment by af4jm** [comment]
that explains why it's only happening on my personal machine & not my work PC (which I hadn't realized until now), because that setting is on in my personal profile but not in my work profile... both machines are on PS 7.4.2

**Comment by Tyriar** [comment]
Good to hear! That means we just need to ensure this code doesn't get called for Windows PowerShell.
