### ISSUE TITLE
After updating this version, the font settings have been lost

### ISSUE THREAD

**Issue by huye** [microsoft/vscode#214835]
Type: <b>Bug</b>

In the new version, the font settings have no effect. I saw that CSS in the developer tool has font settings. Is it caused by updating the underlying engine?

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:34:44.157Z)
OS version: Darwin x64 23.5.0
Modes:
Remote OS version: Linux x64 5.10.0-23-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.86GB free)|
|Process Argv|--crash-reporter-id 15cc245c-aeec-42e3-ab0f-31fcac4737ed|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ai1.serv.fk|
|OS|Linux x64 5.10.0-23-amd64|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (72 x 1200)|
|Memory (System)|503.78GB (422.65GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
cmake-tools|ms-|1.18.42
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
26j00206:31048877

```

</details>

**Comment by huye** [comment]
Although I used remote editing function in the report, But I have tested that local editing still doesn't work.

**Comment by IllusionMH** [comment]
Looks like duplicate of #214390 see https://github.com/microsoft/vscode/issues/214390#issuecomment-2154822715 and check if it works

**Comment by huye** [comment]
> Looks like duplicate of #214390 see [#214390 (comment)](https://github.com/microsoft/vscode/issues/214390#issuecomment-2154822715) and check if it works

Thank you for your help! I have found the following way to fix this bug, which is to start vscode with the following command:
`
open -a "Visual Studio Code" --args --disable-blink-features=FontMatchingCTMigration
`
