### ISSUE TITLE
Node hangs when invoked from a JavaScript Debug Terminal

### ISSUE THREAD

**Issue by szszoke** [microsoft/vscode#214872]
Does this issue occur when all extensions are disabled?: No

Only the `Dev Containers` extension is active and it is unknown if the issue is caused by it or not.

- VS Code Version: 1.90.0
- OS Version: Linux x64 6.9.3-arch1-1

Since updating to 1.90.0, `node` just hangs when it is invoked in a `JavaScript Debug Terminal`. This only seem to happen inside a Dev container and not when run things on the host machine directly.

Before updating to 1.90.0 I was able to run `node` applications in the `JavaScript Debug Terminal` and VS Code would pick up the debug session.

Steps to Reproduce:

Repo with minimal reproducible example: https://github.com/szszoke/vscode-node-hangs

**Comment by szszoke** [comment]
As a workaround I reverted to 1.89.0

**Comment by harmsk** [comment]
I'm experiencing the same issue. Typescript project in a devcontainer running on the latest Fedora (40). 

I have several launch configurations in this project. All those with type `node` work without issue. 

However, launch configurations of type `node-terminal` appear to hang (`command: "pnpm dev"`). But, they don't actually hang. Rather, they are running very slowly and will eventually launch about 10 minutes later. `top` in the devcontainer shows that 99-100% of the CPU is being consumed by `lsof` during this time. Once it finally launches, CPU usage goes back to normal.

I can confirm that downgrading to VS Code 1.89.1 works; all debugger launch configurations work as expected with 1.89.1.

**Comment by szszoke** [comment]
We have tested the repo on an M-something MacBook where the issue didn't occur so it might be something specific to Linux.

**Comment by connor4312** [comment]
Fun, I didn't know lsof could do that. Caused by https://github.com/microsoft/vscode-js-debug/pull/2005/commits/14af88d558d77d4fa0b9b1b7e82b95481b804ab7, we should probably just take the safe 'slow' path all the time. Node.js starts faster nowadays so the slow path is not as slow as it used to be...

**Comment by connor4312** [comment]
Fixed in tonight's [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)

**Comment by nati-maskens** [comment]
Thank you very much @connor4312, had the same issue exactly (`lsof` hangs for long time) on Arch Linux.
Can confirm that nightly build fixed it.
