### ISSUE TITLE
Feature Request: `<filename>:@<symbol>` Syntax to allow for jumping directly to file and symbol at the same time

### ISSUE THREAD

**Issue by mofosyne** [microsoft/vscode#214870]
I do some documentation occasionally and found that using line number to be a bit inflexible when the code evolve that the line reference is no longer accurate.

Currently we can do `<file>:<linenumber>` but what would be nice is if you can also do `<file>:<symbol>`

I noticed you can do `@<symbol>` so if you are worrying about conflicting syntax, you could consider `<file>:@<symbol>`...

So you may type `gguf.c:@gguf_context` to jump to gguf.c and locate the closest symbol matching `gguf_context`.

---

Extra consideraton. Perhaps you can chain both the line number and symbol so that it will pick the symbol closest to the line number (this is still okay as long as there is not too much line number deviation...) `<file>:<line>:@<symbol>`

**Comment by mjbvz** [comment]
Where are you requesting that this be supported?

**Comment by mofosyne** [comment]
I would like it to be in `Command Palette` when typing `ctrl+p`.

When sharing a reference between people I typically send file:num to others etc... with this new approach i can also send file:symbolname instead and tell them to throw it in the same command pallet where they would usually paste the file and line number.

**Comment by mofosyne** [comment]
Ideally see if you can make these search syntax composable so you can join it together etc...

**Comment by mjbvz** [comment]
Closing this based on lack of additional feedback/upvotes since it was opened
