### ISSUE TITLE
in search file by name (go to file) "@" is symbol not working with specified file

### ISSUE THREAD

**Issue by abdullah1116** [microsoft/vscode#214895]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.0
- OS Version: Ubuntu 23.10 x86_64

Steps to Reproduce:

1. open go to file
2. enter [file name]@[symbol name]

It was working month ago, but in recent update its broken.

It is working when searching by file name or symbol name individually. However, when combining file name and symbol name in the search, its not working. i have tested this in both php and js project.

**Comment by andreamah** [comment]
When you go to the file, does just `@` show the symbols correctly?

**Comment by abdullah1116** [comment]
yes

**Comment by abdullah1116** [comment]
these are the screenshots what will help you.

in old vscode when it was working
![Screenshot from 2024-06-14 08-04-16](https://github.com/microsoft/vscode/assets/59234351/4c6bb341-474c-4bdf-ae14-877051574ba2)


and in new vscode update
![image](https://github.com/microsoft/vscode/assets/59234351/475e3ecb-802b-4fa8-9cd4-2211dfd1d9b5)

**Comment by TylerLeonhardt** [comment]
👋 we'll get this fixed in the recovery build this week. In the meantime, http://code.visualstudio.com/insiders/ has the fix already if you want to be unblocked. Sorry for that!

**Comment by mreduar** [comment]
Ty @abdullah1116 @joyceerhl 🙏

**Comment by abdullah1116** [comment]
Fixed in stable build. Thanks 👍️.
