### ISSUE TITLE
Auto indentation in C++ extension

### ISSUE THREAD

**Issue by vishalmehta1991** [Microsoft/vscode#21486]
**std::vector< std::vector<int> > var**

Auto indentation by cntrl+shift+I cause std::vector<std::vector<int>> var, causing compilation failure with regards to operator >>, a space has to be maintained in templated object declaration.

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.4.0-64-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|CppSnippets|hars|0.0.7|
|cpptools|ms-vscode|0.10.1|
|reloaded-cpp|reloadedextensions|0.1.5|
|debug|webfreak|0.17.0|

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Please file this against the C++ extension here https://github.com/Microsoft/vscode-cpptools
