### ISSUE TITLE
Workbench > issue Activity bar location top

### ISSUE THREAD

**Issue by victorlunam** [microsoft/vscode#214894]
Type: <b>Bug</b>

when the “activity bar” position is set to “top”. there is space available for display but the extensions are hidden.

VS Code version: Code 1.90.0 (Universal) (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:34:44.157Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|12, 6, 6|
|Memory (System)|8.00GB (0.49GB free)|
|Process Argv|--crash-reporter-id e55d0d8a-670b-4793-b1bc-a5ae92d3e339|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.10.5
vscode-eslint|dba|2.4.4
gitlens|eam|15.1.0
prettier-vscode|esb|10.4.0
copilot|Git|1.200.0
copilot-chat|Git|0.16.0
symbols|mig|0.0.17
code-spell-checker|str|3.0.1
errorlens|use|3.18.0
dory-notes|vic|0.0.1
pretty-ts-errors|Yoa|0.5.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
fa862199:31048878

```

</details>

**Comment by benibenj** [comment]
@victorlunam have you used the following extension? https://marketplace.visualstudio.com/items?itemName=drcika.apc-extension
I've seen other users report this bug and it turned out it was being cause by the extension. If that is the case, you'll need to report this bug to the extension

**Comment by benibenj** [comment]
If you are not on the latest version of vscode, updating it might fix this problem. Makes sure the extension is uninstalled when doing this. The latest vscode version is `1.90.2`

**Comment by victorlunam** [comment]
thanks for helping me, I have updated vscode to the latest version and the problem has been solved.

<img width="311" alt="image" src="https://github.com/microsoft/vscode/assets/98234382/c15059c9-94ac-4dc9-be86-cda5fc7e13c7">
