### ISSUE TITLE
Trigger character always force a new completion session

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21484]
from https://github.com/eclipse/eclipse.jdt.ls/issues/166#issuecomment-282667530

* have a completion item provider that is triggered on `*`
* have another completion item provider that return completions like `foo.bar`
* trigger completion from the latter, type to filter until the `.` 💥

**Comment by jrieken** [comment]
Sample providers:

```ts
    vscode.languages.registerCompletionItemProvider('*', {
        provideCompletionItems(doc, pos) {
            return [new vscode.CompletionItem('foo.bar')];
        }
    });

    vscode.languages.registerCompletionItemProvider('*', {
        provideCompletionItems(doc, pos) {
            return [new vscode.CompletionItem('boom')];
        }
    }, '.');
```

![feb-27-2017 11-17-21](https://cloud.githubusercontent.com/assets/1794099/23357508/5f4035da-fcde-11e6-9a19-9d3c4ac019f6.gif)

**Comment by martinlippert** [comment]
Awesome, thanks for fixing, much appreciated !!!
