### ISSUE TITLE
光标问题

### ISSUE THREAD

**Issue by 1ds6f1afd** [microsoft/vscode#214834]
Type: <b>Feature Request</b>

Cursor is invisible in light color themes

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by IOLOII** [comment]
Please upload a screenshot, gif or video.
