### ISSUE TITLE
VSCode Crashes When Switching Extension Detail Pages After Using Search

### ISSUE THREAD

**Issue by OccDeser** [microsoft/vscode#214836]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0 (Universal) / 1.89.1 (user setup)
- OS Version: Darwin arm64 23.5.0 / Windows_NT x64 10.0.19043

Steps to Reproduce:
1. Open Visual Studio Code.
2. Navigate to the Extensions view by clicking on the Extensions icon in the Activity Bar.
3. Click on any extension to open its detailed page.
4. Press `Cmd+F` (or `Ctrl+F` on Windows/Linux) to open the search box within the extension detail page.
5. Enter any text into the search box.
6. Without closing the search box, click on another extension to open its detailed page.

Additional Information:
- Version: 1.90.0 (Universal)
- Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
- Date: 2024-06-04T19:34:44.157Z (6 days ago)
- Electron: 29.4.0
- ElectronBuildId: 9593362
- Chromium: 122.0.6261.156
- Node.js: 20.9.0
- V8: 12.2.281.27-electron.0
- OS: Darwin arm64 23.5.0

Same with a windows machine:

- Version: 1.89.1 (user setup)
- Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
- Date: 2024-05-07T05:13:33.891Z
- Electron: 28.2.8
- ElectronBuildId: 27744544
- Chromium: 120.0.6099.291
- Node.js: 18.18.2
- V8: 12.0.267.19-electron.0
- OS: Windows_NT x64 10.0.19043

![bug](https://github.com/microsoft/vscode/assets/55315125/d8d67522-ffff-4740-b5c8-92a6fcda96fb)

**Comment by NDBTjay** [comment]
I got the same problem on MacOS
Version: 1.89.1 (Universal)
Date: 2024-05-07T05:14:24.611Z 
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.5.0

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/177046
