### ISSUE TITLE
slow terminal

### ISSUE THREAD

**Issue by Matteonegridev** [microsoft/vscode#214811]
Type: <b>Bug</b>

when i change directory in bach terminal using the cd command, or touch, or creating folders, it takes few more seconds while it used to be pretty much instant instead . how do I fix that?

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.91GB free)|
|Process Argv|--crash-reporter-id 2211662f-1b4b-43b8-a79a-71bfce9ed869|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
a-file-icon-vscode|ato|1.2.0
vscode-tailwindcss|bra|0.10.5
macos-modern-theme|dav|2.3.19
vscode-eslint|dba|2.4.4
githistory|don|0.6.20
gitlens|eam|15.1.0
vscode-great-icons|emm|2.1.105
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
calm-days-sober-nights-theme-vscode|gio|7.1.6
live-sass|gle|6.1.2
monokai-pro-new-kc|kvn|0.0.4
batman-classic|mat|0.0.1
git-graph|mhu|1.30.0
document|min|2.2.2
theme-monokai-pro-vscode|mon|1.3.2
test-adapter-converter|ms-|0.1.9
vscode-speech|ms-|0.10.0
synthwave-vscode|Rob|0.1.15
theme-switcher|sav|2.0.2
vscode-windows-xp-theme|sin|0.1.2
vscode-icons|vsc|12.8.0
windows-nt-vscode-theme|was|0.0.12
emmet-live|yse|1.0.0
material-theme|zhu|3.17.2

(27 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by bodgergely** [comment]
I experience the same issue exactly on Windows. Please see the Issue https://github.com/microsoft/vscode/issues/214810 with a bit more details.
