### ISSUE TITLE
vscode crashed if enable chromium sandbox

### ISSUE THREAD

**Issue by nickbanana** [microsoft/vscode#214832]
Does this issue occur when all extensions are disabled?: Yes/No Yes

- VS Code Version: 1.90.0 (commit 89de5a8d4d)
- OS Version: win11 x64

Steps to Reproduce:

1.  open vscode without --disable-chromium-sandbox
2. error: CodeWindow: renderer process gone (reason: crashed, code -2147483645)

**Comment by deepak1556** [comment]
Can you attach the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

**Comment by nickbanana** [comment]
> Can you attach the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

I repro the step, however the crash-reporter directory only contain two empty folders: attachments, reports and settings.dat. There's no dmp file

As a sidenote, if open vscode with --disable-chromium-sandbox, and open another code without the parameter, the new code instance won't crash

**Comment by deepak1556** [comment]
Does v1.89 work fine without the flag ? Can you also confirm if this is a user install or system install ?

**Comment by nickbanana** [comment]
> Does v1.89 work fine without the flag ? Can you also confirm if this is a user install or system install ?

it's user install, do I just simply reinstall v1.89 to check whether or not it's working?

**Comment by nickbanana** [comment]
#208363 Seems like it's related issue, and restart pc helps
Maybe there's some issue regard to renderer process hang

**Comment by nickbanana** [comment]
close as it's duplicated.
