### ISSUE TITLE
Sorry, we're not going to make any changes in the icon sizing / positions. This is how it grew historically.

### ISSUE THREAD

**Issue by dpetroff** [microsoft/vscode#214875]
Sorry, we're not going to make any changes in the icon sizing / positions. This is how it grew historically.

_Originally posted by @aeschli in https://github.com/microsoft/vscode/issues/209860#issuecomment-2044529841_
            
Sorry, the old issue became locked. However, this needs a more productive discussion than writing it off as "this is how it grew historically." I think the way things grew historically has created some totally inconsistent APIs, which is especially apparent in the linked issue. While I accept that Microsoft doesn't care about this much, the open-sourced project will benefit from a clean-up of some of these organically grown APIs so the fact that Microsoft won't fix it does not mean that nobody else in the open-source community is interested in fixing it.

"This is how it grew historically" is not a very strong argument to keep inconsistent APIs forever and make the extension developer learning curve shoot for the moon. Frankly, while all the APIs undisputedly "work as intended" they are somewhat counter-intuitive and too sparsely documented for easy entry by anyone trying to pick up extension development from scratch. There is always a gotcha or inconsistency that you have to spend a day or two figuring out. Leaving things as they have grown historically will only make things worse.

**Comment by aeschli** [comment]
Of course everyone is welcome to investigate here and come up with a backward compatible solution in a PR. The solution needs to be well tested (all platforms, existing icon and product theme and extensions that contribute icons and language icons).
Also, I'd need some commitment helping managing issues that get reported in that area, to figure out if the change has caused any regressions.

**Comment by dpetroff** [comment]
Thanks. It might make sense to also unlock and potentially reopen the issue to allow the conversation to be continued by others as per the `help-wanted` label. Not sure how `closed`, `help-wanted`, and `out-of-scope` labels align in this repo though. In my mind `closed` and `help-wanted` seem to be mutually exclusive.
