### ISSUE TITLE
Toggle Word Wrap gets lost after touching settings.json

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#21487]
* Run Toggle Word Wrap
* Execute View > Zoom In (this writes to user `settings.json` behind the scenes)

* observe: the word wrap state is reset again, Toggle Word Wrap needs to be run again.

**Comment by bpasero** [comment]
@alexandrudima I already looked into only updating the editor when the options change and have a fix ready. Still, I am currently not smart enough to handle the case where someone changes some word wrap unrelated editor setting (aka I only check for the entire editor setting being same or not). I can look into doing a simple object-diff on the editor setting and only update you with the options that actually have changed in the editor?

**Comment by bpasero** [comment]
I pushed a change to only apply the minimal diff of editor settings that have changed, let's see how that goes.
