### ISSUE TITLE
vscode crashes right after startup 

### ISSUE THREAD

**Issue by Shoreshen** [microsoft/vscode#214852]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
1.90.0
89de5a8d4d6205e5b11647eb6a74844ca23d2573
x64
- OS Version: 
[shore@shore-82wm manjaro_note]$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        24.0.2
Codename:       Wynsdey
[shore@shore-82wm manjaro_note]$ uname -a
Linux shore-82wm 6.8.12-3-MANJARO #1 SMP PREEMPT_DYNAMIC Mon Jun 10 09:44:22 UTC 2024 x86_64 GNU/Linux

Steps to Reproduce:

1. Open a few vscode windows (I did 6 of them)
2. Reboot, vscode will remember the opened windows
3. run `code`

crash reports:
[vscode-crash-report.tar.gz](https://github.com/user-attachments/files/15785101/vscode-crash-report.tar.gz)
[crash_report (1).tar.gz](https://github.com/user-attachments/files/15785102/crash_report.1.tar.gz)
[crash_report.tar.gz](https://github.com/user-attachments/files/15785104/crash_report.tar.gz)

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/issues/212494

**Comment by Shoreshen** [comment]
> Maybe #212494

Hi thanks, I cannot find previous package for arch, the maintainer is saying that should be fixed at version of 1.90.1, and shall I wait??

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/214833
