### ISSUE TITLE
How to hide lines generated with calls from IPython's `publish_display_data` function?

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#214886]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/15303

<div type='discussions-op-text'>

<sup>Originally posted by **maximlt** March  6, 2024</sup>
Hi all,

I'm one of the maintainers of the plotting library [hvPlot](https://github.com/holoviz/[hvplot](https://github.com/holoviz/hvplot)). The library depends on the dashboarding library [Panel](https://github.com/holoviz/panel) to handle layouts and to enable interactive plot exploration. When hvPlot is imported, Panel injects some JS and styling into the notebook using IPython's [publish_display_data](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.publish_display_data) function, calling it three times. This is required to enable some interactivity. Doing so in a VSCode notebook displays three empty rows. Is there a way to hide these empty lines?
<img width="348" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/35924738/7e7cb83e-5568-4fa7-b635-7be9e37a1eed">

In Jupyterlab, this only displays a small empty line (which is a bit less annoying):
<img width="214" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/35924738/0e1217ff-a90e-4a5d-82e0-7913196d53c9">

For reference: https://github.com/holoviz/hvplot/issues/1284</div>

**Comment by amunger** [comment]
thanks for the ping, looks like this never got assigned.

It looks like the output that we try to render is some javascript code:

```
"outputs": [
    {
     "data": {
      "application/javascript": "(function(root) {\n  function now() {\n ...
      "application/vnd.holoviews_load.v0+json": ""
     },
```

And since it's three separate outputs, we render an output menu for each one. We might be able to check if the output content is empty after the renderer finishes and optionally hide it if so.
