### ISSUE TITLE
Add font configuration for the output console

### ISSUE THREAD

**Issue by DFelten** [Microsoft/vscode#21489]
- VSCode Version: 1.10.0-insider
- OS Version: Windows 10

Suggestion:
Please add a possibility to change the font size of the output console. My general font size is too big for the output console. Something like this would be great:

- `output.console.fontSize`
- `output.console.fontFamily`

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/1957

**Comment by DFelten** [comment]
Oh, I didn't know that the debugging console and the output will use the same settings. Then, of course, this is a duplicate.

**Comment by isidorn** [comment]
@DFelten Sorry about that I misunderstood you.
Output respectes the editor font size.

You are arguing that you want a different font between the editor an the output?

**Comment by DFelten** [comment]
Maybe output isn't the correct translation, the field is called "Ausgabe" in German, the field next to the problems. I'm creating a React Native app with VSC and there the output is too large. It has the same size as the normal font, but this is too big for the output, since here much more is displayed. So it's tiring to find the desired information in the output. 

It would be great if you can adjust the size of the output separately from the normal editor font size.

**Comment by isidorn** [comment]
Got it, then it is a seperate feature request to allow output to have an independent font size

**Comment by isidorn** [comment]
This will do the trick
```
"[Log]": {

		"editor.fontSize": 15
	}
```

**Comment by monk-time** [comment]
@isidorn: "[Log]"? Wow, didn't expect that. Is this syntax documented anywhere? Is there a similar setting for debug console and debug sidebar?

**Comment by isidorn** [comment]
@monk-time not sure if this is documentd but we accept PRs in our vscode-docs repo that fix this. 
There is not a similar setting for debug console and debug sidebar
