### ISSUE TITLE
vscode crashes right after startup

### ISSUE THREAD

**Issue by Shoreshen** [microsoft/vscode#214833]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
1.90.0
89de5a8d4d6205e5b11647eb6a74844ca23d2573
x64
- OS Version: 
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux

Steps to Reproduce:

1. Open a few vscode windows (I did 6 of them)
2. Reboot, vscode will remember the opened windows
3. run `code`

dump with `code --crash-reporter-directory`:

[vscode-crash-report.tar.gz](https://github.com/user-attachments/files/15781138/vscode-crash-report.tar.gz)

**Comment by deepak1556** [comment]
Crash in sqlite3, very likely related to workspace data. Can you create a temporary profile using the steps `Profile: Create a Temporary profile` and check if the crash happens with reboot of this profile.

**Comment by Shoreshen** [comment]
> Crash in sqlite3, very likely related to workspace data. Can you create a temporary profile using the steps `Profile: Create a Temporary profile` and check if the crash happens with reboot of this profile.

Thanks, here are what I did:

1. Open 5~6 windows
2. try `F1` and type in `Profile: Create a Temporary profile` one by one
3. Try to reboot and reopen

Here is what happend:

1. It crashes 2 times when try to create temporary profile (4~5)
2. I succeed one time and reboot+reopen, it hasn't crash and quit the temporary profile
3. leave it and reboot+reopen, it crashes again

log file for the crash
[crash_report.tar.gz](https://github.com/user-attachments/files/15781663/crash_report.tar.gz)

**Comment by Shoreshen** [comment]
> Crash in sqlite3, very likely related to workspace data. Can you create a temporary profile using the steps `Profile: Create a Temporary profile` and check if the crash happens with reboot of this profile.

Hi I reproduced the process (open 5 windows and make them all temporary profile, reboot+reopen), this time it crashes.

log file for crash:
[crash_report.tar.gz](https://github.com/user-attachments/files/15781713/crash_report.tar.gz)

**Comment by Shoreshen** [comment]
@deepak1556 Hi I just updated 1.90.1-1, the problem persists

**Comment by Shoreshen** [comment]
@deepak1556 I just found out that if I didn't maximize the window, it works fine.

The following is the report with command `code --crash-reporter-directory /home/shore/文档/conf/vscode-crash-report --verbose > log`:

[no-crash-report.tar.gz](https://github.com/user-attachments/files/15832927/no-crash-report.tar.gz)

**Comment by Shoreshen** [comment]
@deepak1556  I think my problem may be different, since the problem only happens when I maximize all the opened vscode windows. If I didn't maximize them, it works fine. The dump for not maximizing the windows and successful opening is uploaded above

**Comment by Shoreshen** [comment]
@deepak1556 I've updated to 1.90.2 and the problem persists

**Comment by 6NiceRice9** [comment]
> @deepak1556 1.90.2 same story, when the git extension is active. Works fine if the source control is disabled.

**Comment by 6NiceRice9** [comment]
> @deepak1556 Hi I just updated 1.90.1-1, the problem persists
1.90.2 same story, when the git extension is active.

Works fine if the source control is disabled.

**Comment by Shoreshen** [comment]
> Version: 1.90.2
> 
> 1. deactivate in the project folder (project/.vscode/settings.json)
>    `"git.enabled": false`
> 2. let vscode start and change the settings back to:
>    `"git.enabled": true`
> 3. it works until restart of vscode, seems to be that vscode has some trouble to load git during program startup

Thanks, I did the following:

1. open all projects's settings.json and added `"git.enabled": false` in it
2. try to open vscode, it crashes
3. make all `"git.enabled": false` into `"git.enabled": true`
4. try to open vscode, it also crashes T T

**Comment by Shoreshen** [comment]
@deepak1556 update to 1.91, the problem persists

**Comment by Shoreshen** [comment]
@deepak1556 furthermore, when opening multiple vscode windows, it also has possibility of random crash

**Comment by Shoreshen** [comment]
@deepak1556 Hi if anything or other information you need to resolve this issue, please let me know and I'll try my best to provide

**Comment by Shoreshen** [comment]
@deepak1556 I tried version 1.89, it works fine

**Comment by Shoreshen** [comment]
@road2react @deepak1556  I updated to 1.91 and the problem persists. Also the insider version has the same problem

**Comment by Shoreshen** [comment]
@deepak1556 hi, there is still ppl waiting for solving this bug

**Comment by Shoreshen** [comment]
@deepak1556 hi, how is it going

**Comment by Shoreshen** [comment]
@deepak1556 update to 1.91-1, problem persist

**Comment by Shoreshen** [comment]
@deepak1556 vscode randomly quit now, even after start up

**Comment by Shoreshen** [comment]
@deepak1556 still experiencing random crash

**Comment by Shoreshen** [comment]
@deepak1556 solved in 1.92
