### ISSUE TITLE
JS/TS Service crash

### ISSUE THREAD

**Issue by rollercodester** [microsoft/vscode#214891]
Type: <b>Bug</b>

This happens whever VSCode is restarted. I'm having issues where renamed files cause getEditsForFileRename failure. So, I switched to VSCode's TypeScript version (instead of project version) and restart and this error occurs.

VS Code version: Code 1.90.0 (Universal) (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:34:44.157Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 7, 7|
|Memory (System)|64.00GB (6.96GB free)|
|Process Argv|--crash-reporter-id 67205f15-70bb-4c31-87d0-276269affd4c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
dbclient-jdbc|cwe|1.3.5
vscode-postgresql-client2|cwe|7.4.6
vscode-eslint|dba|2.4.4
gitlens|eam|15.1.0
prettier-vscode|esb|10.4.0
vscode-jest-runner|fir|0.4.73
copilot|Git|1.200.0
copilot-chat|Git|0.16.0
color-picker|Mar|1.0.0
prisma|Pri|5.15.0
svg-preview|Sim|2.8.3
code-spell-checker|str|3.0.1
pretty-ts-errors|Yoa|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
2f103344:31071589
26j00206:31048877

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? Also make sure you are using the latest TS version
