### ISSUE TITLE
Show expressions evaluated with "Evaluate in Debug Console" in history

### ISSUE THREAD

**Issue by gursimar** [microsoft/vscode#214820]
### Description

When you do "Evaluate in Debug Console" for a python expression, it should show up in history. However, if you hit key up/ down, the expression ran using "Evaluate in Debug Console" never show up. Only expressions input manually using keyboard are shown by using key up/ down. This is quite confusing as the user would expect the previously ran expression to show up in history despite the method (Evaluate in Debug Console or Manually using keyboard). This was previously raised as a bug here https://github.com/microsoft/vscode/issues/172718. The bug is closed but seems like, the fix was never provided.

### Please check version details below
- Version: 1.90.0 (user setup)
- Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
- Date: 2024-06-04T19:33:54.889Z
- Electron: 29.4.0
- ElectronBuildId: 9593362
- Chromium: 122.0.6261.156
- Node.js: 20.9.0
- V8: 12.2.281.27-electron.0
- OS: Windows_NT x64 10.0.19045**

**Comment by roblourens** [comment]
I'm unsure about this. I think that in input history, I'd only expect to see expressions that I typed into the repl input. Don't you think it could be confusing to see history that I didn't actually type?

**Comment by gjsjohnmurray** [comment]
I find it confusing that these don't appear in my history.

Sometimes I select a complex expression, use the context menu to evaluate it in the debug console, and discover I don't get the value I expected. Then I realise what's probably wrong with the expression, so I want to test a correction to it. But I can't just arrow up, edit it and re-evaluate. Instead I must reselect it in the code, copy it to the clipboard, paste it, and only then can I try a variant.

**Comment by gursimar** [comment]
IMO, no matter how an expression landed in debug console (manually or by some other method "Evaluate in Debug Console"), it should be added to history.  In pycharm, this is how it happens by default.
