### ISSUE TITLE
VS code bugging

### ISSUE THREAD

**Issue by Haris123346** [microsoft/vscode#214849]
![imagade](https://github.com/microsoft/vscode/assets/93548238/04aefb8f-1b89-4776-beee-aa4e83ca855a)
![imad3dage](https://github.com/microsoft/vscode/assets/93548238/d8d2ea4e-87f3-4587-ac91-35d8174c8c39)
Type: <b>Performance Issue</b>

My vs code has been running very poorly, its been lagging and there are these white color lines that keep appearing on the interface, i dont even know what the problem is, its just slow laggy and buggy

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12450H (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (4.14GB free)|
|Process Argv|C:\\Users\\user\\Desktop\\nuke-bot --crash-reporter-id 48de9015-91ba-451b-acc2-e170b1349fa7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   110	  4600	code main
    0	   189	  8640	   gpu-process
    0	    66	  8716	ptyHost
    0	    62	  6720	     C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	    63	 16636	     C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     7	 17216	     conpty-agent
    0	     7	 21088	     conpty-agent
    0	    45	 15700	   utility-network-service
    0	   261	 20608	window [1] (nuke-bot - Visual Studio Code)
    0	   141	 20860	extensionHost [1]
    0	    92	 21624	     "C:\Users\user\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=20860
    0	    58	 24416	     C:\Users\user\AppData\Local\Programs\Python\Python312\python.exe c:\Users\user\.vscode\extensions\ms-python.python-2024.8.0\python_files\run-jedi-language-server.py
    0	    11	 10960	       C:\windows\system32\conhost.exe 0x4
    0	    88	 20920	shared-process
    0	    29	 21924	   crashpad-handler
    0	   104	 22524	window [2] (Issue Reporter)
    0	    89	 22984	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (nuke-bot - Visual Studio Code)
|    Folder (nuke-bot): 1 files
|      File types: py(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
discord-vscode|icr|5.8.0
python|ms-|2024.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
showvideoc:31016891
chatpanelc:31048052
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
26j00206:31048877

```

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/124226

Please disable hw acceleration in the application as workaround,
```
* Command Palette search for "Configure Runtime Arguments"
* Set disable-hardware-acceleration: true
* Restart
```
