### ISSUE TITLE
explorer overwrites its contents while scrolling a long file list

### ISSUE THREAD

**Issue by nipatriknilsson** [microsoft/vscode#214860]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0
- OS Version: Linux x64 6.6.15-amd64

Steps to Reproduce: Have a long file list in the explorer

![overwrite](https://github.com/microsoft/vscode/assets/26184140/fe3044b1-b1c4-4d73-84e5-1faf1c497627)

It would be better to have a cleaner explorer!

**Comment by lramos15** [comment]
How big of a file list is this? I've tried on the VS Code repository and cannot reproduce.

**Comment by nipatriknilsson** [comment]
You wrote you couldn't see it, I was thinking about if something with my settings could make it. Try setting `"sideBar.background": "#00000002"`.

**Comment by IllusionMH** [comment]
Looks like sticky scroll + missing background in explorer/side bar.
Adding non-opaque `sideBarStickyScroll.background` should help

**Comment by nipatriknilsson** [comment]
`"sideBar.background": "#f0f0f0"` will be good!
