### ISSUE TITLE
1.90.0 crash for extensions loading webcrypto

### ISSUE THREAD

**Issue by aaronvg** [microsoft/vscode#214823]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:  Version: 1.90.0 (Universal)

- OS Version: Darwin arm64 22.6.0

Steps to Reproduce:
I have a language server that loaded webcrypto like this:
`(globalThis as any).crypto = require('node:crypto').webcrypto`

but in 1.90.0 it does not work anymore:

```
TypeError: Cannot set property crypto of #<Object> which has only a getter
    at src/server.ts (/Users/vscode/extensions/boundary.baml-extension-0.36.0/language-server/out/bin.js:17336:23)
```

**Comment by aaronvg** [comment]
seems like I didn't need that line anymore. After I removed it from my extension it still seems to work fine. But if anyone else is trying to load webcrypto it will fail for them.

**Comment by deepak1556** [comment]
webCrypto is enabled by default since Node.js v19 https://github.com/nodejs/node/compare/572d55645c0bd446e7f88e0f2120e5a115257234...2849283c4cebbfbf523cc24303941dc36df9332f, with VS Code 1.90 we moved from Node.js v18 to v20. Closing as it is expected.
