### ISSUE TITLE
Building... never stops

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#214859]
![image](https://github.com/microsoft/vscode/assets/900690/7fa84c9e-83cb-4696-bfb2-8b30c7b9634a)

Since the new insiders, I often end up with Building... and it never clears. I trigger the default build task for vscode.

**Comment by meganrogge** [comment]
I can reproduce.

**Comment by meganrogge** [comment]
the only recent tasks change lately: https://github.com/microsoft/vscode/pull/211973

**Comment by meganrogge** [comment]
that change should be fine though. this is working for me, any other steps to reproduce @bpasero ?

<img width="707" alt="Screenshot 2024-06-12 at 1 31 12 PM" src="https://github.com/microsoft/vscode/assets/29464607/40fd35a8-c515-4ff3-a73a-fbaa0c2b5eeb">

**Comment by bpasero** [comment]
I am in a multi root workspace with `vscode`, `vscode-distro` and `vscode-docs`.

**Comment by bpasero** [comment]
@connor4312 a regression from the user activity changes in progress, you never return the result of the task. Fix in https://github.com/microsoft/vscode/pull/215409

**Comment by meganrogge** [comment]
Thanks for figuring that out @bpasero ! Nice find
