### ISSUE TITLE
Copilot Chat Extension “Add Selection to Chat ” not work on remote hosts

### ISSUE THREAD

**Issue by pennbay** [microsoft/vscode#214858]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.0 (user setup)
- OS: Windows 11 x64 26100.712

Steps to Reproduce:

1. The "Add Selection to Chat" feature works well on the local Windows 11 version of VSCode.
![image](https://github.com/community/community/assets/26505726/74806d74-9fab-4c17-8fb6-e0dca99f4404)

2. Connect to a remote host via SSH.
3. Strangely, this feature is not working on the remote host, but other functions of Copilot Chat are operating normally.
![image](https://github.com/community/community/assets/26505726/105617e6-693c-48cc-9474-8b8fed2b7717)

4. I have tried many times, and the result remains the same.

**Comment by roblourens** [comment]
Maybe a file scheme check?
