### ISSUE TITLE
Configured terminal environments aren't used by tools

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/vscode#214890]
Type: <b>Bug</b>

When connecting to remote workspace (SSH), the tools aren't using environment set for teminal.
I.e. when run `git fetch` in remote terminal, it's connecting fine, but when I ask VS Code to execute `git fetch` via extension, it fails to authenticate.
The cause is it loses `$SSH_AUTH_SOCK` about 20 minutes into session on all the jumps and reconnects, and the redirected socket (the one with stable name coming from `~/.ssh/rc` and set up through `terminal.integrated.env.linux`) is not passed to the tools.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz (4 x 3303)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (8.18GB free)|
|Process Argv|C:\\Users\\anrdaemon\\Documents\\.sh\\git-hub|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
theme-defaults|vsc|1.0.1
vscode-json|and|1.5.2
diff|dup|0.0.1
gitlens|eam|15.1.0
EditorConfig|Edi|0.16.4
todo-tree|Gru|0.0.226
branch-in-window-title|wis|0.2.0
gitconfig-lsp|yy0|0.10.2

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/9819
