### ISSUE TITLE
<shell Defaut namespace not declared

### ISSUE THREAD

**Issue by Alex04MATH** [microsoft/vscode#214920]
Type: <b>Bug</b>

AppShell.xaml Default namespace not declared

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (4.27GB free)|
|Process Argv|D:\\proyectos\\MAUI --crash-reporter-id f341f319-8272-4325-8e44-033fab2c95a8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
comet-debug|Cla|0.7.1
dart-code|Dar|3.90.0
flutter|Dar|3.90.0
netcore-extension-pack|dog|1.10.0
githistory|don|0.6.20
code-runner|for|0.12.2
codespaces|Git|1.16.22
vscode-pull-request-github|Git|0.88.1
ilspy-vscode|ics|0.18.0
Ionide-fsharp|Ion|7.20.1
vsc-python-indent|Kev|1.18.0
unity-code-snippets|kle|2.4.0
csharpextensions|kre|1.7.3
fluent-icons|mig|0.0.18
vscode-docker|ms-|1.29.1
vscode-language-pack-es|MS-|1.89.2024050109
csdevkit|ms-|1.6.8
csharp|ms-|2.31.19
dotnet-interactive-vscode|ms-|1.0.5229040
dotnet-maui|ms-|0.11.96
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.0.6
vscodeintellicode-csharp|ms-|2.1.11
debugpy|ms-|2024.6.0
pylint|ms-|2023.10.1
python|ms-|2024.8.0
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.369.0
makefile-tools|ms-|0.9.10
powershell|ms-|2024.2.2
noesisgui-tools|Noe|0.0.48
vscode-nuget-gallery|pat|1.1.0
vscode-versionlens|pfl|1.13.1
material-icon-theme|PKi|5.3.0
practal|Pra|0.0.13
ayu|tea|1.0.5
errorlens|use|3.18.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vstuc|vis|1.0.2
visual-snake-code|Zho|1.0.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
fa862199:31048878

```

</details>

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, however VS Code extension does not provide any messages about namesapces not being declared or the like.
This is most likely caused by one of the extensions installed. Please file the issue against the corresponding extension.
