### ISSUE TITLE
Editor pressing "del" continuously

### ISSUE THREAD

**Issue by Envrmore** [microsoft/vscode#214944]
Type: <b>Bug</b>

Fedora Linux 40, VS Code 1.89 (code-1.89.1-1715060595.el8.x86_64)

This error appeared out of nowhere mid-work, it never happened before. A popup appeared on the bottom right corner that told me an update is available, I clicked "Later". Suddenly, VS Code continuously deleted my code character by character as if I were holding the 'del' key. I thought the del key in my keyboard was stuck, turns out it didn't.

To stop it from deleting, I just need to press any key that will input a character (A-Z, 0-9, del, etc). It's easy, but in long term this is gonna be obnoxious and a hassle to deal with.

I uninstalled my Vim integration extension, restarted it, then I updated VS Code to 1.90 without uninstalling the current one (1.89), the issue is still there.

I tried to open another of my project folder to see what would happen. It is still the same, the editor deleted my code one by one, character by character. I restarted VS Code and reopened my working folder, it did not fix anything. 

I realized that now everytime the VS Code window get minimized and re-maximized again, this buggy behaviour would happen again. In fact, even this dialogue box for reporting the issue is affected. When I minimized my dialogue box (Issue Reporter), the editor will delete my code one by one, and if I maximized the dialogue box again the text that i typed will be deleted one by one until I press a key.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:43:07.605Z)
OS version: Linux x64 6.8.11-300.fc40.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2365M CPU @ 1.40GHz (4 x 1396)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 7, 7|
|Memory (System)|11.47GB (7.03GB free)|
|Process Argv|--crash-reporter-id 8be4dfd1-dfda-4369-9cf6-a5a8f0dc060c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
2f103344:31071589
26j00206:31048877

```

</details>

**Comment by alexdima** [comment]
Does this reproduce when disabling all extensions? Press `F1` and then choose `Developer: Reload Window with Extensions Disabled`

![Kapture 2020-07-20 at 15 28 23](https://user-images.githubusercontent.com/5047891/87943040-c3b02a80-ca9d-11ea-847d-5f850fae8f05.gif)
