### ISSUE TITLE
VsCode often randomly renders entire system unresponsive, and then crashes - while not even using it

### ISSUE THREAD

**Issue by php4fan** [microsoft/vscode#214907]
Does this issue occur when all extensions are disabled?: impossible to tell

- VS Code Version: 1.90.0
- OS Version: Manjaro Linux

Steps to Reproduce:

1. I have VSCode open, with a project open, but I am not using it at the moment
2. I am using other applications and often Chrome, with several tabs open

Suddenly the entire system becomes sluggish. The mouse cursor moves slowly, clicks on anything in any application take long to respond and sometimes just don't.
When I manage to open a terminal or a virtual console and run top, usually I'll find a "kswapd" process consuming 100% CPU, and then some other apparently random process/es, not always the same ones, also consuming several 100% CPU. The last time it has happened, besides kswapd, it was NetworkManager.

After a few minutes and usually before I have the time to actually do anything (because it takes long to even be able to open the terminal in the first place), everything goes back to normal, and then I realize that VScode is no longer open, that is, it has crashed. Which is what tells me that it's probably the culprit (which otherwise I would have assumed to be Chrome because it was the application I was actually interacting with). The only application that systematically crashes every single time when this happens, and the instant it crashes everything else goes back to working normally, is VSCode.

Usually, perhaps even 100% of the times, this does NOT happen while I am actually interacting with VSCode, but while it's open and idle doing nothing.

**Comment by chrmarti** [comment]
Please run `code --status` next time this happens and post the output here. Also see https://github.com/Microsoft/vscode/wiki/Performance-Issues for more information.

**Comment by php4fan** [comment]
> Please run code --status next time this happens and post the output here.

It happened again, so I did, but the command got stuck for several minutes producing no output, until the system went back to normal, then it produced the output below. This time VSCode didn't crash.

```
Version:          Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:43.666Z)
OS Version:       Linux x64 6.6.32-1-MANJARO
CPUs:             12th Gen Intel(R) Core(TM) i7-1255U (12 x 2800)
Memory (System):  15.32GB (0.68GB free)
Load (avg):       46, 20, 8
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id 827876e4-f236-4a67-a26e-b49b669b700a
GPU Status:       2d_canvas:                              enabled
                  canvas_oop_rasterization:               disabled_off
                  direct_rendering_display_compositor:    disabled_off_ok
                  gpu_compositing:                        enabled
                  multiple_raster_threads:                enabled_on
                  opengl:                                 enabled_on
                  rasterization:                          enabled
                  raw_draw:                               disabled_off_ok
                  skia_graphite:                          disabled_off
                  video_decode:                           enabled
                  video_encode:                           disabled_software
                  vulkan:                                 disabled_off
                  webgl:                                  enabled
                  webgl2:                                 enabled
                  webgpu:                                 disabled_off

CPU %   Mem MB     PID  Process
    0       94  126298  code main
    0        0  126301     zygote
    0       63  247139       gpu-process
    0        0  126302     zygote
    0        0  126304       zygote
    0      235  126379  window [1] (functions_post_thanks.php - codebasehq - Visual Studio Code)
    0      502  126405  window [2] (twa.js - WVTelegramBots - Visual Studio Code)
    0        0  126338     utility-network-service
    0       94  126469  extensionHost [2]
    0      612  126548       /home/teo/.vscode/extensions/devsense.intelli-php-vscode-0.12.15062-linux-x64/out/server/intelliphp.ls
    0      330  126576       /home/teo/.vscode/extensions/devsense.phptools-vscode-1.47.15578-linux-x64/out/server/devsense.php.ls
    0       47  126886       /opt/visual-studio-code/code /opt/visual-studio-code/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=126469
    0       63  212219       electron-nodejs (tsserver.js )
    0       94  212220       electron-nodejs (tsserver.js )
    0       16  212238         electron-nodejs (typingsInstaller.js typesMap.js )
    0       16  212455       /opt/visual-studio-code/code /opt/visual-studio-code/resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=126469
    0       31  126479  shared-process
    0       31  126480  fileWatcher [1]
    0       63  126481  extensionHost [1]
    0      204  126546       /home/teo/.vscode/extensions/devsense.intelli-php-vscode-0.12.15062-linux-x64/out/server/intelliphp.ls
    0      863  126606       /home/teo/.vscode/extensions/devsense.phptools-vscode-1.47.15578-linux-x64/out/server/devsense.php.ls
    0       31  126875       /opt/visual-studio-code/code /opt/visual-studio-code/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=126481
    0       16  126482  fileWatcher [2]

Workspace Stats: 
|  Window (twa.js - WVTelegramBots - Visual Studio Code)
|  Window (functions_post_thanks.php - codebasehq - Visual Studio Code)
|    Folder (WVTelegramBots): 6107 files
|      File types: php(4092) i(138) md(135) json(84) rst(31) txt(29) yaml(24)
|                  twig(23) svg(18) xml(16)
|      Conf files: settings.json(1)
|    Folder (codebasehq): more than 25600 files
|      File types: i(15504) php(829) xml(72) txt(57) backupfiles(25) desc(25)
|                  d(21) fncache(19) js(19) dirstate(16)
|      Conf files:
```

**Comment by jrieken** [comment]
Please follow this guide then https://github.com/Microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

**Comment by php4fan** [comment]
> Please follow this guide then https://github.com/Microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

I tried but when this happens it's impossible to open the dev tools because the entire UI of VSCode is completely unresponsive. I hit F1 several times but the menu wouldn't show up.

**Comment by php4fan** [comment]
My suspicion is that this has to do with some weird interaction between VSCode and Chrome, and this is based on two observations:
- the first few times that this happened, it always ended with VSCode crashing, and no other app ever crashed. But the last few times that I have observed this, VS hasn't crashed anymore.
- in a couple of occasions while this was happening, I killed Chrome and this immediately resulted in everything going back to normal

**Comment by php4fan** [comment]
It's been a while since the last time it happened.
I guess I'll reopen if it happens again.
