### ISSUE TITLE
too much lag and unable to run commands

### ISSUE THREAD

**Issue by gudellivikaschaitanyatr** [microsoft/vscode#214949]
Type: <b>Bug</b>

Hi team, 

I am able to run the command in one terminal. However, when the same command is run on different terminal, it is throwing log in error. I restarted my system and VS code as well. but the issue still persists. Could you please look into this issue? My colleagues are facing the similar issue. Kindly look into this on priority. 
Thanks, 
Vikas. 

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (16.73GB free)|
|Process Argv|--crash-reporter-id aba86782-64ff-4843-a692-0fc08dc91f32|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
amazon-q-vscode|ama|1.8.0
aws-toolkit-vscode|ama|3.9.0
kubernetes-tools|clo|1.3.18
copilot|Git|1.200.0
copilot-chat|Git|0.16.1
start-git-bash|McC|1.2.1
vscode-docker|ms-|1.29.1
vscode-kubernetes-tools|ms-|1.3.16
debugpy|ms-|2024.6.0
python|ms-|2024.8.0
vscode-pylance|ms-|2024.6.1
remote-wsl|ms-|0.88.2
vscode-speech|ms-|0.10.0
vscode-yaml|red|1.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
26j00206:31048877

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/issues/212090
