### ISSUE TITLE
Syntax highlight for C code breaks with macro definition containing a function/parenthesis

### ISSUE THREAD

**Issue by mopsfelder** [Microsoft/vscode#21493]
- VSCode Version: 1.9.1
- Extensions: ms-vscode.cpptools@0.10.1
- OS Version: Fedora 25

Steps to Reproduce:

1. Create a basic C program with macro definition containing a function.  For example:

```c
#include <stdio.h>

#define FOO bar()

int main(void)
{
        return 0;
}
```
2. With the above code example, the syntax highlight for C code breaks, turning `main()` definition entirely blue-ish.  See:

![selection_032](https://cloud.githubusercontent.com/assets/2346907/23363321/e2961a36-fcd8-11e6-8c2e-236519a2f0c4.png)

It seems that the syntax highlight motor expects a comma `;` after a pair of parenthesis is added to macro definition, correcting the colors:

![selection_033](https://cloud.githubusercontent.com/assets/2346907/23363344/fcadf010-fcd8-11e6-8006-139170c84f0b.png)

**Comment by mjbvz** [comment]
This issue was moved to atom/language-c#211

**Comment by mopsfelder** [comment]
Hi, @mjbvz. Thanks for handling this issue. 

Can you please clarify to me what's the relationship between vscode and atom/language-c? Does vscode uses atom/language-c under the hood?

**Comment by mjbvz** [comment]
Yes. We try to share grammars as much as possible and this particular grammar was originally created for Textmate / Atom. We want to make sure any fixes happen upstream so that those tools can also benefit from them

**Comment by mopsfelder** [comment]
Thank you Matt.
