### ISSUE TITLE
Activity Bar Badge should show +99 for values larger than 99

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#214930]
Does this issue occur when all extensions are disabled?: No, it also persists in a fresh user dir

Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:34:44.157Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.90.0 Chrome/122.0.6261.156 Electron/29.4.0 Safari/537.36

Steps to Reproduce:

1. Open folder w/ 100 new files added
2. Move SCM view to secondary sidebar
3. :bug: numbers missing from SCM badge

w/ 99
![CleanShot 2024-06-11 at 21 36 49@2x](https://github.com/microsoft/vscode/assets/35271042/9a016095-7f35-4865-8e08-32d443e2cb43)

+99:
![CleanShot 2024-06-11 at 21 37 09@2x](https://github.com/microsoft/vscode/assets/35271042/87cd374d-9550-4117-96dc-fa3a735213d4)

**Comment by lszomoru** [comment]
I believe that this is by design. @sandy081 could you please confirm? Thanks!

**Comment by sandy081** [comment]
Thats right.

**Comment by miguelsolorio** [comment]
It looks broken, why not show other characters better communicate this? 

![CleanShot 2024-06-12 at 09 11 44@2x](https://github.com/microsoft/vscode/assets/35271042/5e91863a-1a23-4b00-b725-c38e2239175e)

**Comment by gjsjohnmurray** [comment]
Would `>99` be better?

**Comment by benibenj** [comment]
Possibly, I'll try both and see which feels better

**Comment by miguelsolorio** [comment]
It should probably stay consistent, the activity bar uses `99+`:

![CleanShot 2024-06-14 at 09 08 08@2x](https://github.com/microsoft/vscode/assets/35271042/1ac20ace-d964-4eb4-9d2e-4eb30e65b498)
