### ISSUE TITLE
Stop scrolling when there's nothing more to scroll to

### ISSUE THREAD

**Issue by novellizator** [Microsoft/vscode#21497]
When I have an open text file and scroll all the way down to the bottom of the file the bottom line appears on the top of the editor followed by nothing.

What I suggest is that the scrolling would stop, when the last line of the file still appeared at the bottom of the editor (instead of the top).

**Comment by CoenraadS** [comment]
I think this is already a setting

`  "editor.scrollBeyondLastLine": false,`

**Comment by mjbvz** [comment]
Thanks @CoenraadS! That is indeed the setting to control this behavior.

@novellizator Please give this setting a try and let us know if you run into any problems
