### ISSUE TITLE
Markdown preview scrolls to top when "scroll-lock" is turned off

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#21491]
Have the following settings:
```
	"markdown.preview.scrollPreviewWithEditorSelection": false,
	"markdown.preview.scrollEditorWithPreview": false,
```

**Manually** set the preview scroll position to a desired location. Type in the .md file. Observe that the preview scrolls to the top when I would expect it to stay at the scroll top I have **manually** selected.

![preview-scroll-to-top](https://cloud.githubusercontent.com/assets/5047891/23363158/87263c14-fcf9-11e6-883b-5e5aed0513c4.gif)

This is a regression from 1.9.1, where the markdown preview respects my manual set scroll position (with the same two settings):

![preview-no-scroll-1 9 1](https://cloud.githubusercontent.com/assets/5047891/23363258/1b7b50ac-fcfa-11e6-984b-2c6e1d00da58.gif)

Leaving at your consideration if this should be fixed for 1.10, I had to downgrade to 1.9.1 to write my release notes.

**Comment by mjbvz** [comment]
There seems to be some sort of race condition that did not exist before. In `web-view.pre`:

```js
		setTimeout(function () {
			if (newFrame.contentDocument.body && scrollTop !== newFrame.contentDocument.body.scrollTop) {
				newFrame.contentDocument.body.scrollTop = scrollTop;
			} else {
				console.log(newFrame.contentDocument.body )
				debugger;
			}
			document.body.removeChild(frame);
			newFrame.style.display = 'block';
		}, 0);
```

Logs null when this happens but when debugging, `newFrame.contentDocument.body` exists . Changing the timeout to `100` fixes the issue but I'm looking into a proper fix
