### ISSUE TITLE
Visual Studio Code is having stuttering graphics

### ISSUE THREAD

**Issue by GipsyDangerMk3** [microsoft/vscode#214921]
Type: <b>Performance Issue</b>

Seems to happen when I'm actively moving my mouse sometimes within VS Code. The frames keep stuttering but then relaxes when I'm not doing anything. Half the time I don't see the stuttering but when I do it last a good 3 seconds.

It for sure happens when I commit & sync to github, when I go full screen.

I'm working with three monitors and I notice it does not happen on my 2nd monitor.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.92GB (113.43GB free)|
|Process Argv|--crash-reporter-id 3d2014de-b253-48ba-8d6c-229b77a3571b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   112	 17840	code main
    1	    98	  4660	window [3] (Issue Reporter)
    0	   115	 10324	shared-process
    0	    95	 15240	ptyHost
    0	    72	 23724	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"f:\Javascript Projects\VS Code\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     6	 26176	     conpty-agent
    1	    97	 16364	   gpu-process
    0	   115	 20196	extensionHost [1]
    0	    98	  5692	     "F:\Javascript Projects\VS Code\Microsoft VS Code\Code.exe" "f:\Javascript Projects\VS Code\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=20196
    0	   105	  7884	     "F:\Javascript Projects\VS Code\Microsoft VS Code\Code.exe" c:\Users\Riley\.vscode\extensions\streetsidesoftware.code-spell-checker-3.0.1\packages\_server\dist\main.cjs --node-ipc --clientProcessId=20196
    0	    85	 19536	     "F:\Javascript Projects\VS Code\Microsoft VS Code\Code.exe" "f:\Javascript Projects\VS Code\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=20196
    0	    38	 22416	   utility-network-service
    0	   211	 23384	window [1] (style.css - css-exercises - Visual Studio Code)
    0	    26	 25684	   crashpad-handler
    0	    81	 26396	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (style.css - css-exercises - Visual Studio Code)
|    Folder (css-exercises): 210 files
|      File types: html(42) css(42) png(32) md(25) js(5) gif(4) jpg(4)
|                  gitignore(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
live-server|ms-|0.4.13
LiveServer|rit|5.7.9
code-spell-checker|str|3.0.1
bootstrap4-vscode|the|6.1.0
cors-browser|Wsc|1.0.11
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
showvideot:31016892
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
2f103344:31071589
26j00206:31048877

```

</details>

**Comment by deepak1556** [comment]
Can you confirm if the issue happens with latest stable, if so please try running with `--disable-gpu`
