### ISSUE TITLE
It shows a spinning circle while copy pasting

### ISSUE THREAD

**Issue by Akshaypmna18** [microsoft/vscode#214954]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.0
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. I don't know

Version: 1.90.0 (user setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

<a href="https://drive.google.com/file/d/1Ch-6VMr-nl4WDCp52EttOcwDtCjfkIg4/view?usp=drivesdk">provided video link of the issue</a>

![image](https://github.com/microsoft/vscode/assets/67232475/a3a56067-7b6d-4d8a-ab88-a4350423b5a9)

**Comment by mjbvz** [comment]
Should already be fixed
