### ISSUE TITLE
Find (Cmd+F) and Replace (Cmd+Alt+F) non-standard behavior

### ISSUE THREAD

**Issue by marianoprettysimple** [Microsoft/vscode#21495]
While the current behavior is consistent, it's a bit confusing when moving back and forth from other apps that implement the find / replace in a more standard way. What I'd expect, judging from other editors I use all the time (Sublime, Xcode, Android Studio) is:
- Cmd+F opens the find dialog, collapsed to only show the find field (and not the replace field), which makes it clearer what operation you're performing
- Cmd+Alt+F opens the replace dialog, expanded showing both find and replace filed, and focuses input on the find field

**Comment by rebornix** [comment]
@marianoprettysimple based on your description, if I understand correctly, your feature request is like (without mentioning what we already have)

* when we run Find, only show Find Input Box
* when we run Replace, always focus Input Box

is this correct?

**Comment by marianoprettysimple** [comment]
@rebornix Yes, that's it.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
