### ISSUE TITLE
Python Debugger ("JustMyCode: false) is not working

### ISSUE THREAD

**Issue by FilippoFlorindiKAI** [microsoft/vscode#214905]
Type: <b>Bug</b>

I set in the lunch.json the config "JustMyCode": false. Then if I add a breakpoint inside a script of third-party library or if I want just to step into a third-party funcion while debugging, the debugger doesn't open the third-party scripts and do not show any variables. I'm still able to move forward but I cannot see at which point in the code the debugger is.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/214433
