### ISSUE TITLE
latest update on mac causing window bar to be cut off 2

### ISSUE THREAD

**Issue by WolfEYc** [microsoft/vscode#214950]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.0
- OS Version: Sonoma 14.5

Steps to Reproduce:

1. Toggle zen mode ON
2. Reload window
Top bar should be cut off now

Steps to "fix":
1. Toggle fullscreen mode ON
2. Toggle zen mode OFF
3. Toggle fullscreen mode OFF
Top bar should not be cut off now
4. (Optional) Toggle zen mode ON
Top bar should still be fine.
5. Reload window
Top bar will be cut off now.

The issue seems to stem from launching vscode into ZEN mode on a mac. only on the new version

Previous versions did not have this issue.

**Comment by WolfEYc** [comment]
I closed the previous ticket as it did not have enough info

**Comment by WolfEYc** [comment]
I installed v1.89.1 in the meantime and it does not have this bug on apple silicon.

**Comment by jonasjuni** [comment]
this is happening both on my Mac and Windows PC when zen mode is active and VSCode is opened

**Comment by benibenj** [comment]
Closing as a duplicate and has been fixed this month
