### ISSUE TITLE
API Request: onSelectionsChanged(Selection[])

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#21499]
- VSCode Version: `1.9.1`
- OS Version: `Windows 10`

Hello

For my extension I would like to receive an event for when the user moves the cursor in the document. I am looking to set decorations based on cursor position, so I would rather not have to rely on polling.

**Comment by jrieken** [comment]
tata: [`onDidChangeTextEditorSelection`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3569)

**Comment by CoenraadS** [comment]
doh I didn't realise it was under Window, I was checking under TextEditor. Thanks!

**Comment by jrieken** [comment]
Yeah, all of our event a global'ish and the payload identifies the source of the event
