### ISSUE TITLE
PHP snippets not showing up. Instead, VSCode uses HTML snippets

### ISSUE THREAD

**Issue by mariojankovic** [Microsoft/vscode#21496]
- VSCode Version: 1.9.1
- OS Version: Windows 10, build 15031

Steps to Reproduce:

1. Add any working snippet to PHP
2. Snippet won't show up

I am happy to see HTML snippets in my PHP files, but seems to me that PHP snippets are being completely ignored. Can they run alongside each other? If no, then please let us at least have PHP snippets separated from HTML.

**Comment by thecodechef** [comment]
@roblourens 
@kieferrm 

just change the **scopeName** from `text.html.php` to `source.php` that work for me but do it in the main extension of php

**Comment by ekeskiner** [comment]
Go settings and change "editor.tabCompletion": false,  to **true** and php snippets work only inside "<?php ... ?> " if don't want write inside or see it anytime write your snippet on html.json

**Comment by roblourens** [comment]
I don't see a problem- I can add a PHP snippet and it shows up in a PHP file as expected.

Is there something particular about your PHP file where they don't show up?

**Comment by mariojankovic** [comment]
This seems to be resolved in the meantime without changing any settings on my end.

**Comment by mettaworldjon** [comment]
I still have the problem of not being able to use my html snippets inside of my php. When i say snippets i mean user snippets
