### ISSUE TITLE
Copied content in terminal gets overwritten by search content in terminal

### ISSUE THREAD

**Issue by esola-thomas** [microsoft/vscode#214916]
Type: <b>Bug</b>

I don't know if its just me but I find it quite annoying when I have something saved on my clipboard and in the terminal windown I do Ctrl+F look for something in the log and then try to paste whatever I had in the clipboard, this gets overwritten by whatever I looked for in the terminal

Reproduction: 
- Ctrl+Shift+`
- Right Click to copy selected text
- Right Click to paste clipboard (Work with no problem)
- Ctrl+F in terminal (type in a word)
- Right Click to paste clipboard (copeies the word searched)
- Right Click again paste the word you searched (you have lost what was in your clipboard)

System Info:
- VS Code Version:  1.89.1
- OS Version: Windows 11 23H2

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Connection to 'ssh-remote'
Remote OS version: Linux x64 4.18.0-477.27.1.el8_8.x86_64
Remote OS version: Linux x64 4.18.0-477.27.1.el8_8.x86_64

**Comment by meganrogge** [comment]
I cannot reproduce, do you have `terminal.integrated.copyOnSelection` enabled?

https://github.com/microsoft/vscode/assets/29464607/d0d8d74e-4eef-410c-a2fe-bee7fe0da9b3

**Comment by esola-thomas** [comment]
@meganrogge was the video I sent helpful?

**Comment by meganrogge** [comment]
This does not reproduce for me

**Comment by movy** [comment]
This looks like a regression of this issue: https://github.com/microsoft/vscode/issues/151902
Right now whenever I search something in VSCode terminal, the found text is _selected_ and this selection OVERWRITES my clipboard contents (not expected). I think, instead of being selected,  the found string should be highlighted instead and clipboard should be left intact.
