### ISSUE TITLE
Accidentally deleted all my submissions for cs50. How do I recover them? Please this is urgent.

### ISSUE THREAD

**Issue by alucard004** [microsoft/vscode#214922]
Accidentally deleted all my submissions for cs50. How do I recover them? Please this is urgent.

Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by alucard004** [comment]
I was redoing all the projects again for good practice and I wanted to save the new ones in a different folder for organization purposes but in the attempt to delete a wrongly saved folder the whole thing was highlighted.

**Comment by alucard004** [comment]
command Z was of no use.

**Comment by chrmarti** [comment]
You can open the file and then check the `Timeline` view (usually below the file explorer tree) for previous versions. If you deleted a file you can use `F1` > `Local History: Find Entry to Restore`. HTH!
