### ISSUE TITLE
profile analysis worker is broken

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#214945]
* have the renderer or a worker go slow
* see the profile analysis worker failing to start

this was caused by https://github.com/microsoft/vscode/commit/828118d55e5b4da1e06536d4cbf933b74eb51291#diff-a8d63e03d2b4ed8a2080e0e9cc22b7a597c207afb25973dfa53fe543ef8555d5

```
ReferenceError: window is not defined
    at eval (profileAnalysisWorker.js:3:1798)
    at t._safeInvokeFunction (workerMain.js:5:1248)
    at t._invokeFactory (workerMain.js:5:1428)
    at t.complete (workerMain.js:5:1685)
    at L._onModuleComplete (workerMain.js:6:1051)
    at L._resolve (workerMain.js:6:510)
    at L.defineModule (workerMain.js:5:5564)
    at n (workerMain.js:6:1745)
    at eval (profileAnalysisWorker.js:3:1550)
    at anonymous (profileAnalysisWorker.js:8:4534)
```

**Comment by alexdima** [comment]
The old code was also accessing `window` and why is this worker the only one failing 🤷 :
```ts
const ttPolicy = window.trustedTypes?.createPolicy('defaultWorkerFactory', { createScriptURL: value => value });
```

**Comment by andreamah** [comment]
> have the renderer or a worker go slow

Is there an easy way to do this? What do you mean by 'go slow'?

**Comment by jrieken** [comment]
To verify

* enable this setting `"application.experimental.rendererProfiling": true`
* close TypeScript workspace https://github.com/microsoft/TypeScript
* open the `checker.ts` file
* open dev tools console
* select F1 > Force Retokenize
* wait while everything is froozen
* when vscode recovers wait for a message like " WARN [perf] Renderer reported VERY LONG TASK (7139ms), starting profiling session '386d1579-8adc-476d-87e4-fb3bcdd13afe'"
* immediately run F1 > Force Retokenize again
* verify that you don't see the error from mentioned above
* verify that you do see "errors" like " ERR PerfSampleError: by <<renderer>> in ..."
