### ISSUE TITLE
there is a nag hint bar when edit golang source file

### ISSUE THREAD

**Issue by wly65535** [Microsoft/vscode#21503]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.open *.go to edit a golang source file.
2.there is some hint in the top every FIVE SECOND,eg: The "gopkgs" command is not available, Use "go get xxxx" to intall, The "go def" command is not available, Use xxx to install. if I close the hint bar, it will be appear again soon, less than five seconds, I can't find any option as "no longer prompt"

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-go#823
