### ISSUE TITLE
Consider changing IDE name

### ISSUE THREAD

**Issue by Anjmao** [Microsoft/vscode#2150]
I think Visual Studio Code is terrible name for this IDE, because:
1. If I google for any problem, 50 % I get search result for Visual Studio, not for Visual Studio Code.
2. Code word don't really help you know different between Visual Studio and Visual Studio Code.
3. Word Code in visual studio have more meanings. for example it can be actual source code.

My suggestions: Visual Studio Light, any other words except Visual Studio

**Comment by DavidPereira69** [comment]
I sort of agree, though it seems a tough sell. A better solution would be to start using VS Code as shorthand, since that seems to be the general direction comments are taking. Google will quickly catch up.

**Comment by Tyriar** [comment]
Googling `"Visual Studio Code"` (with quotes) or `vscode` returns the desired results. I use the latter when searching and for hashtags etc., works well.

**Comment by jrajav** [comment]
Such a simple search works fine of course, but when searching for anything more specific (where the search is just preceded with `"visual studio code"`) there are plenty of times you run into a conflict with a lot of the results leading to Visual Studio pages instead. Just one example I've run into out of several in the past few days alone: https://www.google.com/search?q=visual+studio+code+tomorrow+theme Top 3 results are all for visual studio though it isn't obvious right away, the correct result is 5 down. This search would have brought that result to the top and the other confusing results wouldn't be anywhere to be seen, if the name were something more unique.

**Comment by Tyriar** [comment]
@jrajav Quotes in search engine search for the full term, just quote visual studio code and not tomorrow theme for that to work; `"visual studio code" tomorrow theme`

`vscode` is likely to be what everyone will use as a keyword though, it's what most extension repositories are prefixed with.

**Comment by manad777** [comment]
Seriously, what a terrible name. It's (was) 2015. You can't be naming your software with zero regards for search results.

**Comment by leegee** [comment]
It's a poor choice for all the reasons above, and because it is boring. It shows no imagination - which might be what is expected of MS, but really is not fair on the product, its developers, or its users.

Also, a new name, without ref to Visual Studio would allow the product to reach those prejudiced against MS, lure them in: they'd be hooked to the great fixtures, and then the brand can reveal itself.....

**Comment by Tyriar** [comment]
Closing, see https://github.com/Microsoft/vscode/issues/2722
