### ISSUE TITLE
Debug bar gets stuck out of screen bounds on the left

### ISSUE THREAD

**Issue by Enamex** [Microsoft/vscode#21502]
- VSCode Version: 1.9
- OS Version: Windows 7

Steps to Reproduce:

1. Start a debugging session
2. Drag the debug bar to the far left off the editor screen

Restarting VSCode doesn't reset it.

![image](https://cloud.githubusercontent.com/assets/5769148/23366480/7d92d75a-fd0f-11e6-83f6-a3c36c540cde.png)

**Comment by isidorn** [comment]
Sorry about that! Dup of https://github.com/Microsoft/vscode/issues/20298 which contains a workaround

**Comment by Enamex** [comment]
@isidorn That's a lot of issues o_o
I promise I searched. Just didn't know what its official name was.

**Comment by isidorn** [comment]
@Enamex no worries. There is already a new vscode stable coming out in a couple of days which will fix this.
