### ISSUE TITLE
move/rename operation with git

### ISSUE THREAD

**Issue by fiurthorn** [Microsoft/vscode#21501]
If a Project is tracked by git do rename or move files and folder by git, to keep the file history.
This helps git to merge changes by the new location.

**Comment by isidorn** [comment]
This is done automatically by git - it is enough that you just stage your files and git will auto-detect move/rename.

What are you expecting VS Code to do which it is not doing now?
Can you please clarify?

**Comment by fiurthorn** [comment]
I think it is not done by Git automaticly. If it should, it doesn't.
attachted two screenshots "renamed by git" and "renamed by vs code".

![renamed by vscode](https://cloud.githubusercontent.com/assets/13510039/23399961/8e58f3b0-fda2-11e6-80be-026381bd4867.JPG)
![renamed bygit](https://cloud.githubusercontent.com/assets/13510039/23399960/8e58d74a-fda2-11e6-98d1-f9513288bcfa.JPG)

**Comment by joaomoreno** [comment]
A move in git is *only* detected once both the addition and deletion changes are staged.
