### ISSUE TITLE
extending navigation, layout and toolbars? 

### ISSUE THREAD

**Issue by xblox** [Microsoft/vscode#21505]
Hi,
might it be possible to add toolbars (ribbons and the like) to VSCode from within extensions ? I was checking the extension documentation but I couldn't answer this question.

I am evaluating the possibility to use VSCode as replacement for our home grown IDE and convert our application specific code into extensions just. As shown [here in the screenshots](https://github.com/xblox/xblocks-commander/issues/1), I am also wondering I can add my own tree-views to the navigation panel or replace the file-panel with our own.... 

Of course, this is not an issue. Feel free to close this here just. Its a rather a simple yes/no question. I am aware I could fork VSCode just and try to add this but I'd love to archive it via extensions (may be in the future roadmap?). 

thanks a lot,
guenter

**Comment by isidorn** [comment]
No, this is not possible. VSCode extension model does not support customizing the UX experience. More details https://code.visualstudio.com/Docs/extensions/overview

Some custom viewlets which contain trees are possible. More details https://github.com/Microsoft/vscode/issues/12163
