### ISSUE TITLE
Strange theme background color

### ISSUE THREAD

**Issue by yuchiko** [Microsoft/vscode#21508]
- VSCode Version: 
- OS Version: macOs Sierra 10.12.3 macbook 13'

Steps to Reproduce:

1.  Install VS on mac

![alt text](https://i.stack.imgur.com/roGZI.jpg)

**Comment by gus-bolste** [comment]
same, it seems to be only with dark themes.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12473
