### ISSUE TITLE
“Find All References” across files for a method/function in javascript

### ISSUE THREAD

**Issue by MankalMR** [Microsoft/vscode#21507]
- VSCode Version:1.9.1
- OS Version:OSX

Steps to Reproduce:

1.Select a method in javascript
2.Right click on Find all References

Expected Result: Find all references across files in a project
Actual Result: finds references in the current file.

**Note:** The project i'm working on uses requirejs to load and utilize module dependencies.

**Comment by MystK** [comment]
I think related to #20924

**Comment by MankalMR** [comment]
I just looked at the thread. That does not a resolution either? Any idea if this is being looked up on priority?

**Comment by njgraf512** [comment]
Any update on this?

**Comment by andy-ms** [comment]
The original issue is certainly Microsoft/TypeScript#6942; TypeScript doesn't resolve AMD-style imports.

**Comment by Hoishin** [comment]
Is it intended that CommonJS module references don't get shown in Find All References too?

**Comment by andy-ms** [comment]
@Hoishin Could you provide a repro?

**Comment by Hoishin** [comment]
Yes!

env:
- Version 1.20.1 (1.20.1)
- no extension enabled
- config
```json
{
  "editor.renderWhitespace": "all",
  "editor.rulers": [
    80,
    100
  ],
  "explorer.confirmDragAndDrop": false,
  "files.autoSave": "onFocusChange",
  "files.insertFinalNewline": true,
  "instantmarkdown.autoOpenBrowser": false,
  "sync.anonymousGist": false,
  "sync.askGistName": false,
  "sync.autoDownload": true,
  "sync.autoUpload": true,
  "sync.gist": "<removed but has gist id>",
  "sync.lastDownload": "2018-02-27T17:47:11.358Z",
  "sync.lastUpload": "2018-02-27T18:30:16.262Z",
  "sync.forceDownload": false,
  "sync.host": "",
  "sync.pathPrefix": "",
  "sync.quietSync": false,
  "workbench.colorTheme": "Dracula",
  "workbench.iconTheme": "material-icon-theme",
  "workbench.startupEditor": "none",
  "editor.quickSuggestions": {
    "other": true,
    "comments": true,
    "strings": true
  },
  "window.zoomLevel": 0,
  "markdown.extension.preview.autoShowPreviewToSide": true
}
```

procedure:
1. `module.export = ` something
2. `require()` it in different file
3. select Find All References on `module.exports`
4. says "no result"

![code-bug](https://user-images.githubusercontent.com/28832095/36747782-45cc586a-1c39-11e8-8db6-ba1ffe01118c.gif)

**Comment by andy-ms** [comment]
@Hoishin In that case the export has no name so we don't have references for it. If you write `module.exports = function f() {}` we can find references for `f`. We could add some special-casing to support `module.exports` though. Microsoft/TypeScript#22205

**Comment by Hoishin** [comment]
@andy-ms Ah, I see. You have to have name it and/or assign to variable, and find reference from those instead of `module.exports`.
It'd be nice to be able to list references from module.exports indeed. Looking forward to the feature if possible.

**Comment by Hoishin** [comment]
@andy-ms Also, it might be unrelated, but it would be nice if I can also see `require('...')` itself when it is used directly as function or something. For example

```js
server.plugin = {
  plugin: require('awsome-plugin'),
  options: require('./config/awesome-plugin'), // shown in find-all-references in awsome-plugin.js
};
```

Might be too much of asking though...

**Comment by Hoishin** [comment]
@andy-ms I've been playing with Reference All References today. I found that the way you export affect Find All References, outside of what I have mentioned so far.
```js
const something = 1234;
module.exports = {something}; // doesn't work
module.exports = {something: something}; // doesn't work
module.exports.something = something; // works
```
These are kind of reasonable from what you have said, since in the first two situations, the actual exported objects are not named, while the third one exports the named object directly.
Sorry if you are already aware of this, but just thought of sharing because why not :)

**Comment by mjbvz** [comment]
Closing this generic issue in favor of tracking individual case that are causing problems. Since `Find All References` not working has many possible causes, tracking individual issues will let us understand the problems people are hitting in real world code and hopefully get those cases addressed.

Please open a new issue with some example code or small example project if you see `Find All References` not working as expected

**Comment by AlJohri** [comment]
I also found that `module.exports = {something};` isn't able to Find All References for me.

**Comment by stephengardner** [comment]
I'm struggling with this as well.

Attempting to find usages of a file.
I wasn't the original creator of the code, but the file has: `export default {};` and is imported due to other functionality within the file.

I need to find other files that import this file.

**Comment by andy-ms** [comment]
@stephengardner You should be able to run find-all-references on the `default` keyword.

**Comment by andy-ms** [comment]
Microsoft/TypeScript#28221
