### ISSUE TITLE
feature: allow selecting search results

### ISSUE THREAD

**Issue by kobi2187** [Microsoft/vscode#21516]
- VSCode Version: insiders nightly

Version 1.10.0-insider
Commit 40fecfaa77f01672e8a147be71f6f7ccb9cf8a12
Date 2017-02-27T14:13:35.653Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
- OS Version: Linux Mint Cinnamon 18.1 64-bit.

Feature request example:
1. search for some regex.
2. hit Ctrl+c
... all the highlighted search results are now stored as lines in the clipboard.
3. open a new document, and paste.
Result: all the search items are now shown as a list.

Bonus points addendum: Another operation to put virtual cursors in each of them, allowing for simultaneous editing.

**Comment by dakaraphi** [comment]
@kobi2187 from your description, I believe what you want is 'alt+enter' after search.  This will create cursors for each selection and you can copy the selections to the clipboard.

**Comment by roblourens** [comment]
Yeah i guess I'm not sure if @kobi2187 is talking about 'search' (across workspace) or 'find' (in one file)

**Comment by kobi2187** [comment]
Nice! I wasn't aware of alt+enter. it does just what I asked for. 
I'm fine with closing the issue, but would recommend to include a description of the feature in the documentation, as it seems pretty powerful. 

I haven't thought about find across files actually. It can be useful to have a simple mechanism to extract text, directing it either to a new text file, or a pane. maybe after passing the data thru one of the operations. 
For example, extracting all todo comments from the project, then capitalizing every line (operation is either built in or from extension) and directing to the "Output" pane.
But this is probably material for another issue. (macros related)
