### ISSUE TITLE
Working Files list should be ordered by last viewed.

### ISSUE THREAD

**Issue by vishal123** [Microsoft/vscode#2151]
I'm currently ignoring the Working Files window because I'm not finding it entirely useful.
As I'm working with files, I've memorised the location of the files I'm switching between and the list stays fairly static so its easy to go from one file or another.

The working files windows however I'm assuming is ordered by when opened, so it changes across coding sessions.

I, personally, would find it more useful if it acted like a stack. Anytime I switch to a file, it should raise to the top of the working files list, and so the first item is the active file, and the second is the last viewed file.

In essence, the list should be ordered by last viewed.

Not sure if anyone shares my preference here, but I'd be interested to hear for or otherwise.

**Comment by bpasero** [comment]
@vishal123 what about Ctrl/Cmd+P? it does exactly that!

**Comment by vishal123** [comment]
@bpasero Yup, perfect! Didn't know about that :+1:

**Comment by bpasero** [comment]
We will not change this given our tab work.
