### ISSUE TITLE
Mapped types incorrect intellisense

### ISSUE THREAD

**Issue by goodmind** [Microsoft/vscode#21519]
- VSCode Version: 1.9.1
- OS Version: OS X El Capitan 10.11.6

Steps to Reproduce:

1. Clone this repo: https://github.com/goodmind/vscode-intellisense-bug
2. Open files `test/ok_intellisense.ts` and `test/fail_intellisense.ts` and try to write some properties

FAIL              | OK
------------ | ------------
![image](https://cloud.githubusercontent.com/assets/3275424/23377707/d28862f0-fd52-11e6-9679-fb539cdb9dce.png) | ![image](https://cloud.githubusercontent.com/assets/3275424/23377714/d9905f8a-fd52-11e6-93da-a54eaaeff597.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14344
