### ISSUE TITLE
SCM preview does not support multi-select

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21510]
- VSCode Version: Code - Insiders 1.10.0-insider (40fecfaa77f01672e8a147be71f6f7ccb9cf8a12, 2017-02-27T14:13:35.653Z)
- OS Version: Linux x64 4.8.0-38-generic
- Extensions: none
---

This is in the smoke test https://github.com/Microsoft/vscode/wiki/Smoke-Test#git

**Comment by joaomoreno** [comment]
#21000
