### ISSUE TITLE
Markdown's Open Preview editor toolbar item: Open to the side

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#21511]
- VSCode Version: Code - Insiders 1.10.0-insider (40fecfaa77f01672e8a147be71f6f7ccb9cf8a12, 2017-02-27T14:09:29.088Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none

Currently the Markdown editor has the Open Preview action in its toolbar. It would be more convenient if that was the Open Preview to the Side action.

**Comment by bpasero** [comment]
@chrmarti whats wrong with Alt-click on the icon to get the other action?

**Comment by chrmarti** [comment]
@bpasero It's not discoverable. (I didn't know it was there.)

**Comment by bpasero** [comment]
I think it is quite common to trigger an "alternative" action when you press a modifier key, e.g. we also allow you to open "to the side" from the explorer when you press Ctrl key while clicking. What is nice about the editor toolbar is that the action icon even changes to indicate the semantics.

I find it hard to argue that the default should be changed. I think you can find many users that prefer the current solution of not opening to the side.

**Comment by chrmarti** [comment]
My intuition is the opposite: Most users would prefer the side-by-side action, because that gives them the better editing experience.

What seems to make it harder to discover:
- Wouldn't Cmd/Ctrl be the more appropriate modifier, since that is used in browsers for opening a link in a new tab?
- The icon only changes when pressing the modifier and mousing over that toolbar item.

**Comment by dbaeumer** [comment]
Agree with @chrmarti that ctrl would be more appropriate than alt since we use it in the files explorer. Took me quite some time to recognize that this is alt in markdown.

**Comment by King66** [comment]
With the setting "window.menuBarVisibility": "toggle", the menu bar will show after "alt+click", it's annoying...

**Comment by mjbvz** [comment]
@chrmarti e392265 changes the default action to: open preview to side. I agree this is the more common use case for the preview

Regarding `alt` vs. `ctrl`, this seems to be defined by editor. Markdown contributes a toolbar item with an alternate action, but I believe the editor is what determines which key modifier to use to activate this action

**Comment by jrieken** [comment]
> Markdown contributes a toolbar item with an alternate action, but I believe the editor is what determines which key modifier to use to activate this action

It's the menu implementation. The reason for using *alt* and not *control* is that this allows to show an *Alt*ernative action in that place. This is inspired by the mac which changes menus when pressing Alt.
