### ISSUE TITLE
git gutters not visible for network paths

### ISSUE THREAD

**Issue by jrad88** [Microsoft/vscode#21528]
- VSCode Version: 1.9.1
- OS Version: Windows 10

Steps to Reproduce:

1.  Open a git repo from a network share, e.g. `\\Other-PC\Path\To\Repo`
2.  Make any change

You'll see no gutters.  I've tracked this down locally to this change:
https://github.com/Microsoft/vscode/commit/4af3d1797da4c3fe0e92c69ad39d2af990d1c592

**Comment by jrad88** [comment]
Just to update this bug, the latest release has now broken git diff entirely for files on a network share, or other UNC path.

The program is hardly usable anymore.

**Comment by joaomoreno** [comment]
@jrad88 How is it different now from before?

**Comment by jrad88** [comment]
Well, first the gutter indicators for which lines have changes from git don't show up in the code editor window because of the change mentioned above.  But before this version I could view changes in the git view and see a side by side view of what changed.  After this update, the left side of the comparison is blank and the right side is my file.  This is happening for all of my files, which are on a network drive.

**Comment by joaomoreno** [comment]
Got it, thanks. I'll merge this with #23297
