### ISSUE TITLE
Phantom `git:/` virtual paths sometimes appear in Problems View

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#21526]
- VSCode Version: Code - Insiders 1.10.0-insider (40fecfaa77f01672e8a147be71f6f7ccb9cf8a12, 2017-02-27T14:15:13.224Z)
- OS Version: Windows_NT ia32 10.0.14393

### Repro steps:
1. create new php file with an error - e.g. `a.php`
```php
<?php

function a () {
```
2. Open the problems view
3. Switch to a different tab, switch back
4. Notice that two problems appear in view
![image](https://cloud.githubusercontent.com/assets/762848/23384815/41978d3a-fd01-11e6-99f2-0dc88c179033.png)

### Additional notes:
* the folder is not under source control (I know the screenshot above shows that it is, but it was also broken before initializing the repo)
* I've also seen the issue appear for ESLint files as well, so it's not just PHP, although I haven't been able to find a small and consistent repro for this one (the following case *was* under source control, but still made no sense)
![image](https://cloud.githubusercontent.com/assets/762848/23384842/63b32ca8-fd01-11e6-891c-d645131342cb.png)
* The issue cannot be reproduced when you launch from the latest bits in master `scripts/code.bat` (and I haven't seen any recent changes that would have addressed this issue)
* The issue doesn't appear to reproduce for all extensions (or at least not that I've seen)
* The issue does not reproduce in v1.9.1, so this is a regression.
* sometimes the errors linger after issue in the actual file is addressed, and sometimes they do not. 
* the phantom virtual file only appears for one file at a time unless the error lingers
* attempting to navigate to the phantom file yields a totally blank and un-editable file

**Comment by joaomoreno** [comment]
More info: #19627, #20859

cc @Microsoft/vscode

**Comment by dbaeumer** [comment]
To mitigate this for now I added a hard coded rule to exclude git:// from validation.

**Comment by kieferrm** [comment]
@joaomoreno  can you provide some additional info? #20859 is forward looking discussion, #19627 was closed for 1.9. How do they solve the issue at hand?

**Comment by joaomoreno** [comment]
This was mitigated by changing the file extension of `git:` resources, minimising the number of extensions which would create diagnostics for those resources. Usually those extensions filter file events on file extensions, like ESLint does.

Then, this becomes a duplicate of #20859: we need fine grained control of what features are enabled for what resources.
