### ISSUE TITLE
Spaces in path to git repositoy leads to error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by vaibhav-y** [Microsoft/vscode#21527]
- VSCode Version: 1.9.1 Recovery Build
- OS Version: Windows 10 Home (version 1607, build 14393.693)

Steps to Reproduce:

1. Create a git repository at any path containing at least a single whitespace (in my case:  `D:\theyenaman\Google Drive\Documents\UFlorida\Courses\notes`
2. Open repository using vscode, ENOENT: no such file or directory, lstat `D:\theyenaman\Google`
3. I followed @mattn's solution in #4651 which fixes the original problem but am now stuck with this new thing.

Please let me know if you need any additional info

**Comment by wimspaargaren** [comment]
Hello, since I'm new here and this was labeled beginner, I wanted to help, but I don't seem to be able to recreate:

1. Got a git repo with path containing space D:\Documents\vs code bug test\gitproject
2. Open VsCode
3. Choose File -> Open folder -> select gitproject
4. Everything seems to work as expected.

**Comment by vaibhav-y** [comment]
I tried it with another repo without any spaces in it, and it works fine for that. However i've confirmed the spaces issue on another directory. Perhaps this is some strange interaction?

Tried on directory: `D:\theyenaman\books\gi tproj`, got error: ENOENT: no such file or directory, lstat `D:\theyenaman\books\gi`

Is there any information I can provide to help with this? I ran `code --disable-extensions` which also produces the above error.

**Comment by marckassay** [comment]
Along with @wimspaargaren I wasn't able to replicate the issue (using 85e31cf).  I did come across a minor glitch when adding a new repo, but that got resolved upon restarting the debugger window of VS Code and hasn't happened again.  Below is my recording:
![21527_c](https://cloud.githubusercontent.com/assets/459665/26766041/250b2896-4957-11e7-95fd-8045a0aaef37.gif)

**Comment by joaomoreno** [comment]
@vaibhav-y Does this still reproduce in the latest insider release?

**Comment by vaibhav-y** [comment]
I just confirmed, this is no longer happening on my system. Please close the issue at will.
