### ISSUE TITLE
Network: Left side explore folders don't always open

### ISSUE THREAD

**Issue by network211** [Microsoft/vscode#21520]
- VSCode Version:1.9.1
- OS Version: windows 7

Steps to Reproduce:
Don't know how to reproduce this consistently.

I can be editing along and want to go to a folder in the Explorer on the left.
I hit the folder name with the mouse. The caret changes from pointing right to pointing down, but the subfolder do not open.  (see the 2 attached files, open and closed). 
![closed](https://cloud.githubusercontent.com/assets/16655822/23377813/f693ef68-fcf6-11e6-9d4e-8f7980caba9b.png)
Click on folder. It is still closed, but now looks like this:
![open](https://cloud.githubusercontent.com/assets/16655822/23377812/f692e5e6-fcf6-11e6-8024-e3d5059cc749.png)

If I reload the folder and hit refresh, it seems to work
![correct](https://cloud.githubusercontent.com/assets/16655822/23377901/32b22fa0-fcf7-11e6-99b4-3b70d9c0a5c4.png)

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by network211** [comment]
I have attached a screenshot of the dev tools when running under verbose.

Toggling the folder does not add any entries to the console, The yellow warning  appear at the top are caused by plugin Bookmark. I removed the plugin and restarted. The yellow warnings disappeared, but the toggle behavior is the same.. 
![devtools](https://cloud.githubusercontent.com/assets/16655822/23479965/d9a0ad2e-fe8b-11e6-9020-a8b35e3e9036.png)

Here is a capture of the verbose login. I have removed duplicate entries related to file watcher.
[console.txt](https://github.com/Microsoft/vscode/files/811960/console.txt)

**Comment by bpasero** [comment]
@network211 is this some special file system? could you have some security tool running that maybe blocks Code from accessing the file system in a weird way?

**Comment by network211** [comment]
It is a networked mapped drive, a drive letter mapped to a share on another server within our local network.

-------- Original message --------

**Comment by network211** [comment]
Also, when this happens, it doesn't happen for all folders. I.e., I can open other folders, just not certain ones.

**Comment by bpasero** [comment]
@network211 and you can use the command line to list the contents of these without errors?

**Comment by network211** [comment]
dir v:\classes
dir v:\classes\local  (that is the subfolder under classes)
lists all correctly

Or from git bash shell
ll /v/classes/local

lists all correctly.

Also no problem when File | Open which uses the windows file open dialog

Also no problem when Ctrl+E and then type the file name or path\filename

**Comment by bpasero** [comment]
Ok, sorry to tell that but I am out of ideas. Since this issue comes from node.js there does not seem to be a workaround.

**Comment by network211** [comment]
Thanks. I’ll see if I can determine how to reliably reproduce this issue (ie what steps) and post them.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/20207
