### ISSUE TITLE
Disconnects every two minutes when ssh to the compute node of the cluster.

### ISSUE THREAD

**Issue by qmpotential** [microsoft/vscode#215385]
- VS Code Version: 1.90.0
- OS Version: Sonoma 14.4.1
When connected to the cluster, after 2 minutes VSC is trying to reconnect to the cluster and looses its ssh connection. 

I would appreciate any help and advice on what to do and how to avoid it.

Sincerely,

**Comment by Khahan1104** [comment]
hi88.com tk khahan1104

**Comment by Khahan1104** [comment]
Hi88.con

**Comment by joshspicer** [comment]
For us to best help, please include your Remote - SSH logs (`> Remote-SSH: Show Log` in the command palette). Also, please try directly `ssh`'ing to the machine outside of VS Code with `-v`, don't touch it for 2+ minutes, and see if you get disconnected.  Without knowing anything about this machine you're connecting to, perhaps there is some timeout on the cluster to keep it available for others (just a guess).

Also, i'd suggest taking a look at these common troubleshooting steps: https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting.  I'm not sure from this issue what solutions you've tried yet, but these will likely be helpful to identifying _if_ there is any potential issue with the extension
