### ISSUE TITLE
Force quit with the ability to revert changes silently

### ISSUE THREAD

**Issue by xconverge** [Microsoft/vscode#21536]
With Vim keybinding extensions, there is a command :q! that is a force quit.

When you execute this command it quits, without prompting, and without storing any changes. This is what differentiates it from hotexit, all changes should be **reverted**.

All prompts should be suppressed and the editor should be closed right away.

Currently there is nothing in the API to allow us to do this 

```:q! to quit without saving (short for :quit!)```

Over at VSCodeVim this is one of our highest rated issues:
https://github.com/VSCodeVim/Vim/issues/979

**Comment by xconverge** [comment]
@bpasero thanks for the comments on the other ticket!

**Comment by bpasero** [comment]
This sounds like a good issue to work on via PR 👍

**Comment by xconverge** [comment]
It was a trap!

**Comment by misoguy** [comment]
If no one is on this yet, I'll try to look into this issue

**Comment by misoguy** [comment]
I have roughly implemented force quit and added an API linked to it. Since i'm not really sure if this is the right way to do it, it would be nice to get some comments about the PR

**Comment by misoguy** [comment]
After implementing, I realized it might be better to add the revert() function into 
```interface IEditorInput```
and directly call the revert function from newly implemented ```ForceCloseEditorAction```
Any thoughts?

**Comment by bpasero** [comment]
@misoguy I think you can do everything with the current API without introducing a lot more. You can use the `IEditorGroupService` from your action to access the model (`IEditorStacksModel`) which holds any editor that is open. You can iterate over the groups and editors and call `revert()` on the ones which are dirty. After that is done you can close the editors.

Btw is it really that `q!` should close all editors? Maybe this should keep the editors open but just revert all?

**Comment by misoguy** [comment]
@bpasero It seems like the ```revert()``` function is only implemented in the ```abstract class EditorInput``` and not declared in ```interface IEditorInput```. That is why i asked if declaring the ```revert()``` function into the interface was a good idea so that it could be invoked in my action as you proposed.

As for the ```q!``` command, it is to my understanding that it should only close the activeEditor, therefore there is no need to iterate over all editors that are open. Did i understand it right? @xconverge

**Comment by bpasero** [comment]
@misoguy yeah the interface doesn't mean a lot, so try to add it there but watch for compile errors.

**Comment by misoguy** [comment]
@bpasero I tried to use the ```IEditorGroupService``` in my action as you said, and spent more time looking deeply into the code base. After understanding more of the code, it feels like the code change in my current PR #21548 is more suitable to implement the ```q!``` command.
It would be nice if you could briefly review my codes and comment on the changed lines if you still think ```IEditorGroupService``` is a better way. Thanks in advance! :)

**Comment by bpasero** [comment]
@misoguy I would first collect the actual requirements of what q! should do before going on. Does it close all files or the active file? Does it only revert? Does it quit?

**Comment by xconverge** [comment]
q! only reverts and quits the active editor

**Comment by bpasero** [comment]
@xconverge what does "active editor" mean when you have multiple editors open. Does it literally reverts and close the currently active tab in the tab UI or revert all tabs and close the window?

**Comment by xconverge** [comment]
Yes the tab, if a user does "qa!" Then we will use this command and iterate over the tabs from our side

**Comment by bpasero** [comment]
@xconverge thanks, looks like we need 2 new commands then.

@misoguy I still think using the editor group API to get the current active editor or all editors and then calling revert is a better approach. The API is all there so we should not arbitrarily introduce new API.

**Comment by xconverge** [comment]
Why do you need 2 new commands? We will use the "force close tab" command and then loop over all tabs and execute the same command

2 commands would be fine though, just no guarantees we would use the "close all tabs of editor" command

**Comment by misoguy** [comment]
After carefully reading the comments, I have newly implemented the command "workbench.action.forceCloseActiveEditor".
As for "force closing all tabs", I wasn't sure if it should be implemented or not.

**Comment by bpasero** [comment]
There is now a `workbench.action.revertAndCloseActiveEditor` that keybinding can be associated with.

**Comment by xconverge** [comment]
What a hero
