### ISSUE TITLE
Sign In button doesn't work for Copilot

### ISSUE THREAD

**Issue by keaedwar** [microsoft/vscode#215387]
Type: <b>Bug</b>

I brought up VS Code and opened a folder. I wanted to run a GitHub Copilot request, but when I pressed the Copilot Chat icon on the left, it showed me a left panel that said, "Sign in with GitHub to use Copilot, your AI pair programmer.", but the Sign In button didn't do anything. It looks like I'm already loggeed in.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.20GB (25.72GB free)|
|Process Argv|--crash-reporter-id c6576603-b60e-4776-b8b0-7344f1723162|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
copy-relative-path|ale|0.0.2
npm-intellisense|chr|1.4.5
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|2.4.4
githistory|don|0.6.20
gitlens|eam|15.1.0
vscode-html-css|ecm|2.0.10
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
vscode-firefox-debug|fir|2.9.10
auto-close-tag|for|0.5.15
dotnet-test-explorer|for|0.7.8
copilot|Git|1.201.0
copilot-chat|Git|0.16.1
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.88.1
rest-client|hum|0.25.1
vscode-gutter-preview|kis|0.31.2
Kotlin|mat|1.7.1
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.1
csdevkit|ms-|1.7.25
csharp|ms-|2.33.17
vscode-dotnet-runtime|ms-|2.0.6
vscodeintellicode-csharp|ms-|2.1.11
vscode-edge-devtools|ms-|2.1.5
vscode-kubernetes-tools|ms-|1.3.16
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.22.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.1
playwright|ms-|1.1.6
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.369.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
azure-repos|ms-|0.38.0
hexeditor|ms-|1.10.0
live-server|ms-|0.4.13
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.1
vscode-github-issue-notebooks|ms-|0.0.130
material-icon-theme|PKi|5.3.0
quicktype|qui|23.0.170
vscode-commons|red|0.0.6
vscode-yaml|red|1.15.0
vue-vscode-snippets|sdr|3.1.1
autoimport|ste|1.5.4
code-spell-checker|str|3.0.1
vscode-mdx|uni|1.8.8
veracode-vscode-plugin|Ver|1.9.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
volar|Vue|2.0.8
console-ninja|Wal|1.0.324
quokka-vscode|Wal|1.0.646
wallaby-vscode|Wal|1.0.379
vscode-todo-highlight|way|1.0.5
vscode-mdx-preview|xyc|0.3.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by TylerLeonhardt** [comment]
Hi @keaedwar  👋 I'm wondering if sbuchersg's suggestion helped you?

**Comment by keaedwar** [comment]
> Hi @keaedwar 👋 I'm wondering if sbuchersg's suggestion helped you?

Yes, I was able to logout and log back following @sbuchersg 's suggestion.  Thanks!

**Comment by TylerLeonhardt** [comment]
Cool. I'll close this for now but let us know if you see this again
