### ISSUE TITLE
Provide Intellisense for module import

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#2153]
TypeScript module exports can be fairly opaque in regard to their exports. Particularly when modules grow bigger.

With bigger modules (particularly with modules exporting other modules' exports) it becomes very hard to see which entities a module actually is exporting.
<br/>
##### So I suggest to provide an Intellisense feature for module imports, which

1. provides a file browser dropdown box displaying valid module files
1. provides a module browser dropdown box displaying an imported module's exported entities

<br/>
#### The first part of the suggestion I propose to work like `LINQ`:
After entering the keyword `from` and hitting the [TAB] key, a file browser dropdown should be displayed, listing all valid module files. After confirming a file from the dropdown box, VS Code should automatically create a full `import {} from "[...]"` statement, move the cursor position between the curly braces and display a dropdown box listing all the exports of that module.
<br/>
##### Here's a visualization:

![provide intellisense for import](https://cloud.githubusercontent.com/assets/9283914/12483755/17e59744-c057-11e5-9992-599d511cf826.gif)

<br/>
#### The second part of the suggestion I propose to work like common Intellisense:
Everytime when hitting [CTRL]+[SPACE] from within the curly braces of an `import` statement, dropdown box (2) should be displayed, listing the module's exported entities. Selecting an entry should then add the selected export entity to the list of already imported entities within the curly braces.

**Comment by atifsyedali** [comment]
We have around 25k lines of Typescript with hundreds of Typescript modules, and we use CommonJS style module imports.

Not having Intellisense for module import as described here is the main reason why we don't use VS Code. Would be really nice if you can add this (or push the Typescript team to provide it on a language service level :) )

**Comment by Haemoglobin** [comment]
:+1:

**Comment by dbaeumer** [comment]
This is actually a feature that has to come from the tsserver.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10092
