### ISSUE TITLE
Referencing variables in settings

### ISSUE THREAD

**Issue by SaswatPadhi** [Microsoft/vscode#21534]
### Referencing variables in settings

- VSCode Version:
```
Version 1.10.0-insider
Commit 40fecfaa77f01672e8a147be71f6f7ccb9cf8a12
Date 2017-02-27T14:13:35.653Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

As of the current insider build of VS Code, I don't see a way of referencing the values of previously refined variables. For example, in my settings:
```json
  // Controls the wrapping column of the editor when `editor.wordWrap` is 'wordWrapColumn' or 'bounded'.
  "editor.wordWrapColumn": 80,

  // Width to word-wrap to when using gq.
  "vim.textwidth": 80,
```
I want to keep the values of both the variables consistent. It would be nice to have something like:
```json
"vim.textwidth": @"editor.wordWrapColumn",
```

Not sure if JSON has a standard way of referencing previous objects, but this would be a nice feature to have at least within VS Code. YAML doesn't support referencing directly either, but at least you can define node anchors and then reference them later.

**Comment by sandy081** [comment]
@SaswatPadhi Thanks for the input. Looks to me an interesting idea. We have to collect more inputs and requirements for this idea and make it concrete. 

For your use case, why not consulting the VIM extension to handle this case? If no text width is provided for VIM, take the width from word wrap column?

**Comment by SaswatPadhi** [comment]
Hi @sandy081,
Thanks for considering the idea.
I agree that this particular case could be handled by the Vim extension. But there could be many other instances where a good-default for the option needs to be a user-defined variable.

By the way, even within VS, I would like these two to stay in sync for example:
```json
"editor.minimap.maxColumn": @"editor.wordWrapColumn"
```

**Comment by sandy081** [comment]
@alexandrudima Does the above assignment makes a valid case for introducing variables ? Or you would like to handle this differently by introducing a new setting?

**Comment by alexandrudima** [comment]
I think it is ok to have these as separate settings. i.e. someone might want to configure them with different values.

I leave it to you to decide what you'd like to do with variables in settings.json

**Comment by sandy081** [comment]
Closing this as we do not have plans in implementing this in next 12 months. It is also not often requested.
