### ISSUE TITLE
shift-click should extend word-wise text selection in terminal

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode#215328]
When selecting text in the terminal, if I double-click to select a word and then shift+click elsewhere the selection should be extended "word-wise" up to the word I clicked rather than just extending to the character I clicked on. This enables more efficiently selecting text and matches the behavior of both the editor and regular text fields in VSCode as well as Mac OS apps generally. I'm not familiar with what the standard behavior is on Windows so this may be a Mac OS-only feature.

**Comment by meganrogge** [comment]
This works for me already, pls add a gif of it not working for you

**Comment by diminutivesloop** [comment]
Here's a screen recording of me reproducing the issue w/ the latest insiders and default settings:

https://github.com/microsoft/vscode/assets/667716/c8345150-3bc1-4183-8aa1-4d7c978f2b2e

I also checked and the word-wise selection works in the default Terminal app so this isn't an issue w/ my shell configuration either.
