### ISSUE TITLE
proxy not working

### ISSUE THREAD

**Issue by helphi** [Microsoft/vscode#21538]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.4.0-64-generic
- Extensions:

---

Steps to Reproduce:

1. set `http_proxy`, `https_proxy` environment variables
1. open VSCode `1.9.1`, click `Extensions` -> `Show Popular Extensions`, no result 
1. open VSCode `1.6.1`, click `Extensions` -> `Show Popular Extensions`, extension list displayed

**Comment by joaomoreno** [comment]
Can you help us in #18103 ?
