### ISSUE TITLE
Debug toolbar and tab row overlap

### ISSUE THREAD

**Issue by codematix** [Microsoft/vscode#21537]
- VSCode Version: Code - Insiders 1.10.0-insider (40fecfaa77f01672e8a147be71f6f7ccb9cf8a12, 2017-02-27T14:09:29.088Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|EditorConfig|EditorConfig|0.3.4|
|beautify|HookyQR|0.7.4|
|vscode-docker|PeterJausovec|0.0.11|
|vscode-nsp|adambaldwin|1.0.1|
|vscode-caniuse|akamud|0.5.3|
|Bookmarks|alefragnani|0.10.2|
|project-manager|alefragnani|0.13.2|
|vscode-database|bajdzis|1.2.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.5|
|vscode-instant-markdown|dbankier|1.0.0|
|githistory|donjayamanne|0.1.5|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|git-project-manager|felipecaputo|1.0.1|
|flow-for-vscode|flowtype|0.5.0|
|rest-client|humao|0.12.1|
|Scala|itryapitsin|0.1.7|
|docthis|joelday|0.3.11|
|Go|lukehoban|0.6.53|
|prettify-json|mohsen1|0.0.3|
|debugger-for-chrome|msjsdiag|2.5.3|
|seti-icons|qinjia|0.1.3|
|vscode-icons|robertohuertasm|7.2.0|
|sass-indented|robinbentley|1.3.0|
|preview-vscode|searKing|1.1.1|
|stylelint|shinnn|0.22.0|
|gitblame|waderyan|1.3.0|
|JavaScriptSnippets|xabikos|1.4.0|
|vscode-open-in-github|ziyasal|1.2.3|;

---

Steps to Reproduce:

1. Open multiple tabs from your project
2. Start a debugging session
3. Notice that the debug toolbar overlaps with the tab bar.
4. We can only move the toolbar left or right but we cannot get rid of the overlap.

Expectation
It may not be an issue to have a fixed mini toolbar above the tab-bar. Launching a debug session, stopping, restarting, step-over, etc can be buttons on there.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/2513
