### ISSUE TITLE
Git push/pull process loader is keeping moving if internet is disconnected in between the process.

### ISSUE THREAD

**Issue by shahidmau** [Microsoft/vscode#21539]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 14.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|crane|HvyIndustries|0.2.2|
|Angular2|UVBrain|0.4.1|
|project-manager|alefragnani|0.13.2|
|elasticsearch-snippets|dandric|0.1.2|
|angular2-snippets|danwahlin|1.0.12|
|vscode-quick-select|dbankier|0.2.1|
|php-intellisense|felixfbecker|1.1.3|
|es-query|jitcoder|0.0.5|
|mssql|ms-mssql|0.2.1|
|vscode-fileutils|sleistner|2.3.3|
|local-history|xyz|1.1.0|

---

Steps to Reproduce:

1. Commit your changes
2. Click on bottom left button "Synchronize Changes"
3. Disconnect your internet (turn of wi-fi)
4. After 10-15 seconds turn on wi-fi
5. You will notice that process never ends and we have to restart the editor

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
