### ISSUE TITLE
Emmet Wrap with abbreviation

### ISSUE THREAD

**Issue by anthonyargatoff** [microsoft/vscode#215321]
Type: <b>Bug</b>

Emmet wrap with abbreviation doesn't work for a particular file that I am working on, but works on every other file in my project.

Steps: Go the the specific file (Workflow.tsx). Open command pallete, and select Emmet: Wrap with abbreviation. After the selection, I receive no prompt asking what word to wrap with. The expected behavior is that once the option is selected, I should receive a prompt asking for text input, which will then wrap my selection (this works on all of my other files).

I have this issue on different computers for the same particular file.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:43:07.605Z)
OS version: Linux x64 5.15.0-112-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 3753)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|7.49GB (3.20GB free)|
|Process Argv|--crash-reporter-id bfd8900c-f964-4e79-83f5-0b5c1e846c97|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.3
prettier-vscode|esb|10.4.0
vscode-language-babel|mgm|0.0.40
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
js-debug-nightly|ms-|2024.5.217
remote-explorer|ms-|0.4.3
vscode-typescript-next|ms-|5.6.20240611
stats-bar|njz|0.5.2
LiveServer|rit|5.7.9
gitblame|wad|11.0.1
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by j-krl** [comment]
Here to report the same bug. Wrap with abbreviation is definitely ignored if I've highlighted a div and its children. It never pops the second prompt asking what abbreviation I want to use, it just highlights the text.

**Comment by rzhao271** [comment]
I'm unable to reproduce the issue. Could you paste a sample code block that causes the issue?
