### ISSUE TITLE
C# start debugging not working

### ISSUE THREAD

**Issue by manishgupta31286** [microsoft/vscode#215423]
Type: <b>Bug</b>

when i issue dotnet build from terminal, it builds without any issue. However, when I go to Run --> Start Debugging, it issues dotnet build C:\Users\manis\Desktop\Xebia\Projects\customerportalmicroservice_notification\Rak.Motori.MS.CustomerPortal.sln /target:Rak_Motori_MS_CustomerPortal_API . Now my project is Rak.Motori.MS.CustomerPortal.csproj, so start debugging, why is it changing . seperator to _. 
It fails with 
error MSB4057: The target "Rak_Motori_MS_CustomerPortal_API" does not exist in the project. 
Please suggest any fix. This issue started happening today only.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
csharp-convert-ts|con|0.1.31
csharpier-vscode|csh|1.7.3
dscodegpt|Dan|3.3.39
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|15.1.0
prettier-vscode|esb|10.4.0
vs-sharper|ese|0.2.0
copilot|Git|1.201.0
copilot-chat|Git|0.16.1
go|gol|0.41.4
terraform|has|2.30.2
vscode-guid|hea|1.9.0
rest-client|hum|0.25.1
cscurlyformatter|Iro|0.0.7
Angular2|joh|16.0.1
git-graph|mhu|1.30.0
azure-dev|ms-|0.8.3
vscode-azureappservice|ms-|0.25.2
vscode-azurecontainerapps|ms-|0.7.0
vscode-azurefunctions|ms-|1.15.0
vscode-azureresourcegroups|ms-|0.9.1
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.15.3
vscode-azurevirtualmachines|ms-|0.6.5
vscode-cosmosdb|ms-|0.22.0
vscode-docker|ms-|1.29.1
csdevkit|ms-|1.7.25
csharp|ms-|2.33.17
vscode-dotnet-runtime|ms-|2.0.6
vscodeintellicode-csharp|ms-|2.1.11
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.8.0
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.369.0
remote-wsl|ms-|0.88.2
azure-account|ms-|0.12.0
makefile-tools|ms-|0.9.10
vscode-node-azure-pack|ms-|1.2.0
java|red|1.31.0
vscode-yaml|red|1.15.0
angular-formatter|sdt|1.2.0
angular-template-formatter|str|0.1.5
tabnine-vscode|Tab|3.108.0
ansible-studio|Vir|1.1.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0
format-all-files|xyk|0.2.0
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
newcmakeconfigv2:31071590
26j00206:31048877

```

</details>

**Comment by roblourens** [comment]
Please file on the C# extension repo

**Comment by weinixuehao** [comment]
![image](https://github.com/microsoft/vscode/assets/17869361/6b1ea3cb-3be1-4676-8e69-030359483fe6)
I am also faced with this problem

**Comment by manishgupta31286** [comment]
@weinixuehao Were you managed to resolve this ?
