### ISSUE TITLE
VSCode crashes when closing developer tools at the second time

### ISSUE THREAD

**Issue by King66** [Microsoft/vscode#21545]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. toggle developer tools and close.
2. toggle developer tools and close, then VS crashes.

In addition, sending usage statistics always seem to fails in my place...
![12](https://cloud.githubusercontent.com/assets/11925432/23396691/ed7c0b98-fdcf-11e6-9b70-14cebd0602a6.jpg)
[VSCode crashes when closing developer tools.zip](https://github.com/Microsoft/vscode/files/806039/VSCode.crashes.when.closing.developer.tools.zip)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4430
