### ISSUE TITLE
java project are very slow to debug

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode#215454]
Type: <b>Performance Issue</b>

System: Linux openSUSE TW + KDE

I've given up with java project, a simple maven java project will take forever to debug. The debugger is doing something for what seems like 1 minute before starting the execution and then hitting a breakout.

I was actually trying to debug a spring boot junit test.

VS Code version: Code - Insiders 1.90.0-insider (81c89c4d00663e1718871bab2f9bf2064a060b63, 2024-05-22T09:30:48.825Z)
OS version: Linux x64 6.9.3-1-default
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 4000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|62.72GB (46.44GB free)|
|Process Argv|/home/yadav/dev/docs/guides --crash-reporter-id 210d9130-10f4-4cf9-ad76-187d60112fd6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma6|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   257	  5581	code-insiders main
    0	     0	  5586	   zygote
    0	   128	  5621	     gpu-process
    0	     0	  5656	       broker
    0	     0	  5587	   zygote
    0	     0	  5589	     zygote
    0	   257	  5666	window [1] (Preview spring-boot-rest.md - guides - Visual Studio Code - Insiders)
    0	   128	  6363	       window
    0	   193	 32001	window [7] (JetBrains - Visual Studio Code - Insiders)
    0	    64	 32391	window [8] (Issue Reporter)
    0	    64	  5628	   utility-network-service
    0	   193	  5742	extensionHost [1]
    0	    64	  5866	     /home/extras/apps/VSCode-linux-x64/code-insiders /home/extras/apps/VSCode-linux-x64/resources/app/extensions/markdown-language-features/server/dist/node/workerMain --node-ipc --clientProcessId=5742
    0	    64	  6091	     /home/extras/apps/VSCode-linux-x64/code-insiders /home/extras/apps/VSCode-linux-x64/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=5742
    0	    64	  6225	     electron-nodejs (eslintServer.js )
    0	    64	  5784	shared-process
    0	     0	 32417	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    64	  5785	fileWatcher [1]
    0	    64	 30522	ptyHost
    0	    64	 32052	fileWatcher [7]
    0	   128	 32065	extensionHost [7]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (JetBrains - Visual Studio Code - Insiders)
|  Window (Preview spring-boot-rest.md - guides - Visual Studio Code - Insiders)
|    Folder (JetBrains): 438 files
|      File types: xml(245) zip(98) txt(15) json(6) db(5) vmoptions(4) java(3)
|                  icls(2) updated_plugins_list(1) lock(1)
|      Conf files:
|    Folder (guides): 940 files
|      File types: png(344) md(173) js(87) ts(36) json(30) svg(15) css(10)
|                  uxf(8) gitignore(6) xcf(6)
|      Conf files: package.json(8) tsconfig.json(5) tslint.json(4)
|                  settings.json(2);
```

</details>
<details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
ng-template|Ang|18.0.0
biome|bio|2.3.0
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|2.4.4
java-decompiler|dgi|0.0.4
java-debug|DSn|0.0.2
EditorConfig|Edi|0.16.4
rest-client|hum|0.25.1
ionic|Ion|1.88.0
java-properties|ith|0.0.2
plantuml|jeb|2.18.1
angular-file-changer|joh|0.0.4
vscode-peacock|joh|4.2.2
sort-typescript-imports|mic|1.4.1
vscode-docker|ms-|1.29.1
playwright|ms-|1.1.7
cpptools|ms-|1.20.5
js-debug-nightly|ms-|2024.5.217
live-server|ms-|0.4.13
angular2-inline|nat|0.0.17
platformio-ide|pla|3.3.3
java-ide-pack|pve|1.2.1
java|red|1.31.0
vscode-commons|red|0.0.6
vscode-community-server-connector|red|0.26.16
vscode-rsp-ui|red|0.24.11
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
markdown-preview-enhanced|shd|0.8.13
vscode-checkstyle|she|1.4.2
java-generate-setters-getters|soh|8.0.1
tailwind-fold|sti|0.1.0
sass-indented|syl|1.8.29
find-then-jump|tra|2.0.5
sort-lines|Tyr|1.11.0
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.55.0
vscode-gradle|vsc|3.13.2024061308
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.1
vscode-lombok|vsc|1.1.0
vscode-maven|vsc|0.44.0
vscode-spring-boot-dashboard|vsc|0.14.0
vscode-spring-initializr|vsc|0.11.2
markdown-pdf|yza|1.5.0
vscode-aspell|zap|0.1.4

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aa:30263845
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
showvideot:31016890
chatpanelt:31014475
01bff139:31013167
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupyter:31046869
nb_pri_only:31057983
26j00206:31048877
nativerepl2:31071685
refactort:31073763

```

</details>

```pre
Operating System: openSUSE Tumbleweed 20240610
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.1
Kernel Version: 6.9.3-1-default (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 5900X 12-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3080/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7A38
System Version: 8.0
```

**Comment by roblourens** [comment]
Probably running a task. If you have a launch.json, you can check for a `preLaunchTask`. If not, you can file an issue on the debug extension
