### ISSUE TITLE
vscode is not smooth on linux manjaro

### ISSUE THREAD

**Issue by AntonioBerna** [microsoft/vscode#215477]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90
- OS Version: Linux Manjaro

Steps to Reproduce:

1. I went to a working directory and used the `code .` command.
2. The vscode program opens correctly but is very slow in movements such as selecting the code or scrolling the code with the mouse wheel.
3. I tried opening `htop` and found this:

![Screenshot_2024-06-13_22-22-41](https://github.com/microsoft/vscode/assets/60107274/2d458d83-52ed-4112-9590-8dcecc9568c8)

it seems that vscode runs on the gpu but if I use the `nvidia-smi` command there is no `vscode` process.

Before the last update everything worked correctly and above all there wasn't all that information on `htop`.

**Comment by deepak1556** [comment]
This is a side effect of the temporary fix we landed for https://github.com/microsoft/vscode/issues/212494 to use software compositing. Issue will be resolved when revert the workaround. Please follow the above issue for updates.
