### ISSUE TITLE
[Remote] Will remote window of VS Code listen to the Node.js program I currently start and override the port it is listening on?

### ISSUE THREAD

**Issue by inlann** [microsoft/vscode#215414]
Does this issue occur when all extensions are disabled?: Not sure

- VS Code Version: 
Version: 1.90.0 (Universal)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:34:44.157Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin x64 22.6.0
- OS Version: Darwin x64 22.6.0

When I run yarn start in the terminal on MacOS to start my React application, it defaults to listening on port 3000. At this point, I can normally access the application by visiting localhost:3000 in my browser. However, if I open VS Code and start a remote window, my local localhost:3000 becomes inaccessible, and I get the following error:

![image](https://github.com/microsoft/vscode/assets/33852855/6981690b-557a-42a2-b519-af47d09c40ee)

I can only restore access by closing the remote window in VS Code. Additionally, the terminal running the yarn start command is not necessarily the default terminal application on macOS; the same issue occurs when using the terminal within VS Code. Another clear scenario is when I have a remote terminal open in VS Code. If I stop the yarn start command using ctrl + c and then restart it, I am notified that port 3000 is already in use. Even if I choose "yes" at this point, repeatedly using ctrl + c and running yarn start does not release the port. Instead, the available port number in the notification keeps increasing.

![image](https://github.com/microsoft/vscode/assets/33852855/7b0143b5-427c-4025-a0b3-fce9b302ed83)
(PS: I changed the default port to 5000 by running: `export PORT=5000 && yarn start`

Steps to Reproduce:

1. Open a terminal application and run a React application: yarn start
2. Open a remote window in VS Code 
3. Kill the React application with ctrl + c and restart it
4. You will be notified that the default port 3000 is in use

**Comment by alexr00** [comment]
@inlann it sounds like the VS Code remote window in forwarding a port. Can you open your remote window again, make sure you can reproduce the issue, then from the remote window open the Ports view? Can you share a screenshot of the Ports view?

**Comment by inlann** [comment]
@alexr00 Hello, Thanks for your reply.

When attempting to open the Ports view in the remote window, it gets stuck in the loading state:

![image](https://github.com/microsoft/vscode/assets/33852855/b9ce7c22-61bc-4daf-a622-a7e98ef52e0d)

**Comment by inlann** [comment]
@alexr00 Sry, There is the "Ports" view:

![image](https://github.com/microsoft/vscode/assets/33852855/8fd6efc9-5a68-42e6-9663-40f51df4534c)

Does VS Code add the port automatically or I did something?

Perhaps I executed `export FLASK_APP=wsgi.py && flask run --port=5000` in the terminal of the remote window in VS Code, and then it was recognized by VS Code?

**Comment by alexr00** [comment]
> Perhaps I executed export FLASK_APP=wsgi.py && flask run --port=5000 in the terminal of the remote window in VS Code, and then it was recognized by VS Code?

Yes, that's probably what happened. If you want to use port 5000 for something locally you can un-forward the port by using the "x" action in the Ports view. If you never want automatic port forwarding you can disable it with the setting `remote.autoForwardPorts`.

**Comment by inlann** [comment]
@alexr00 Really appreciate!

**Comment by inlann** [comment]
@alexr00 It seems that whenever I refresh my Chrome window, VS Code automatically adds port forwarding in the remote window. How can I disable this feature?

**Comment by alexr00** [comment]
The setting `remote.autoForwardPorts` should be. Are you saying all your settings get deleted when you refresh?

**Comment by inlann** [comment]
> Are you saying all your settings get deleted when you refresh?

No, the setting works fine.

![image](https://github.com/microsoft/vscode/assets/33852855/d49a97ed-121c-4692-a260-0fe45683efd1)

Another question, what does `new running processes` mean? Does VS Code detecte new processes started in the terminal of the remote window or all new processes of the remove machine? Since my service (a flask server) on the remote machine is started via the Terminal application of MacOS and detected by VS Code.

**Comment by alexr00** [comment]
For that, check out the setting `remote.autoForwardPortsSource`. If it's set to `process`, then it will watch the proc file system for new running processes. Otherwise, it will watch terminal and debug output.

**Comment by inlann** [comment]
The `remote.autoForwardPortsSource` is set to output(default).
