### ISSUE TITLE
Graph visualization for Incoming/Ougoing view

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#215439]

**Comment by sanket-bhalerao** [comment]
@lszomoru 
the `incoming/Outgoing` appears at the end of the changes visible in the SCM panel. not always visible. 
one has to scroll all the way down to view it.
any plans to make this as a separate view in the SCM panel?

**Comment by lszomoru** [comment]
@sanket-bhalerao, thank you very much for the feedback.
For the time being we do not have plans to move this into a separate view but we will continue to listen to user feedback.

**Comment by abhijit-chikane** [comment]
> @lszomoru the `incoming/Outgoing` appears at the end of the changes visible in the SCM panel. not always visible. one has to scroll all the way down to view it. any plans to make this as a separate view in the SCM panel?

I also like this idea.

**Comment by sanket-bhalerao** [comment]
the Graph is now separated and has its own panel/pane. awesome.
