### ISSUE TITLE
[Accessibility, UX] New WCAG target size accessibility requirements 

### ISSUE THREAD

**Issue by gpeuc** [microsoft/vscode#215422]
Hello dear VS Code people!

There's a new WCAG accessibility requirement to make targets have 24px area:

https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html

To clarify, this doesn't mean **hit** area, so it doesn't mean that icons have to be 24×24px big, because margins count as well.

So for example, these icons are OK because it's 20×20 icon, but it has 4px margin on the right, and that makes the whole space actually have 24px "safe" area.

![Screenshot 2024-06-13 at 09 56 41](https://github.com/microsoft/vscode/assets/44162846/6935dbcb-d7b7-4bbc-865c-875c4c0a7966)

However, there are some places in VS Code that are just a little bit shy of 24px.

For example, this is 23px tall.

![Screenshot 2024-06-13 at 09 57 54](https://github.com/microsoft/vscode/assets/44162846/2b3c9005-1dd6-4283-97dd-5cbb61ee4bc7)

File browser is 22px.

![Screenshot 2024-06-13 at 09 58 22](https://github.com/microsoft/vscode/assets/44162846/ca6b12d1-6fdc-4c9c-a980-2e44b3c055e5)

- - - - - -

**The question is:** are you investing some effort into bumping up these sizes so that they meet the 24px target size requirement?

The main reason I am asking is that we build products inside VS Code, and these products follow strictly what the parent design system is doing (so what VS Code designers are doing). And we have a slight conflict here, because from SAP's side we would like to follow WCAG guidelines in order to be accessibility compliant, however, we would also like that our products feel like they belong into VS Code environment and not look like Frankenstein monster stapled together. 🧟‍♂️

**Comment by isidorn** [comment]
We are thinking about this. Our understanding that this requirement is still not "active" which gives us more time to tackle it.
Having said that, it would still help if you have already identified all the places where we are not respecting this requirement. 

fyi @daviddossett

**Comment by gpeuc** [comment]
Regarding the "active" requirement. The standard itself is live. It's active. It's just a decision by the various companies now how to implement it and on which timeline. From our side (SAP) we have one year to implement the changes brought to us by the WCAG 2.2 standard. Of course, I don't know Microsoft's inner workings and what are your decisions on how to implement the changes or are you even aiming to implement them.

At the moment, the places where I found this 24px standard not met are various line items that are stacked vertically one on top of another. So Command Palette, File Browser, regular Dropdowns, vertical menus, and so on. And those are 1-2 pixels off.

<img width="395" alt="Screenshot 2024-06-13 at 17 31 56" src="https://github.com/microsoft/vscode/assets/44162846/ce2b6001-e0cd-49c6-a5d7-c41226cfb7d0">

<img width="305" alt="Screenshot 2024-06-13 at 17 32 40" src="https://github.com/microsoft/vscode/assets/44162846/2cfb26ec-c15f-4088-bfdc-0bb3b0e54696">

**Comment by isidorn** [comment]
No action items planned, thus closing this one for now
