### ISSUE TITLE
Hovering over few predefined methods doesn't show method description

### ISSUE THREAD

**Issue by RushilJalal** [microsoft/vscode#215412]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0
- OS Version: Windows 11

Steps to Reproduce:

1. Open up a JS file
2. Write the following code
![image](https://github.com/microsoft/vscode/assets/54212357/014d4302-2aa1-4f62-afec-85ca92ec5702)
3. Notice that function is not recognised and method description is not shown.

An MDN page exists for the following method so I think the description should be shown in VS Code as well with a link to the MDN document
https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation

This is just one of the many examples of predefined JS methods not being recognised but it's my first time opening an issue about it.

**Comment by mjbvz** [comment]
In this case, you need to add some JSDoc type annotations:

```js
function foo( /** @type {Event} */ event) { ... } 
```

Otherwise there's no way to know what type `event` is

**Comment by RushilJalal** [comment]
> In this case, you need to add some JSDoc type annotations:
> 
> ```js
> function foo( /** @type {Event} */ event) { ... } 
> ```
> 
> Otherwise there's no way to know what type `event` is

Yep. I get it.
But why does the same happen with an array which has already been defined?
@mjbvz
