### ISSUE TITLE
Add option to let new windows cascade when set to inherit

### ISSUE THREAD

**Issue by amol9** [Microsoft/vscode#21549]
- VSCode Version: 1.9.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a new window from an existing window.

This is related to: New windows should get the size of the previous active window #10864. It's great that the new setting ("window.newWindowDimensions": "inherit") was added to preserve the window size.

But, the new window overlaps exactly on the existing window. It might be a little bit confusing. A user may think that the previous window was closed. Or, was replaced by a new one. I think it should follow the behavior of widely used applications such as Windows Explorer or Firefox, both of which cascade the new window a little bit so as to differentiate it with the previous one.

Probably a new configuration setting such as, "window.newWindowPosition" with options, "same" and "cascade" could be added.

It's a feature request. No hurry.

Thanks.

**Comment by bpasero** [comment]
I agree this can only be a new option.

**Comment by amol9** [comment]
A suggestion after second thoughts.

Adding a new setting for this could be an overkill. There are already hundreds of settings. This can be made default, not configurable behavior, since, it is user friendly and it is the convention used by many popular applications.

**Comment by bpasero** [comment]
I didn't mean to introduce a new setting, just another option for the `window.newWindowDimensions` setting.

**Comment by amol9** [comment]
But, "cascade" option would not be meaningful in context of a setting called newWindowDimensions. Sure, it could mean "inherit and cascade", but, a user may not make a connection that it is "inherit" and then "cascade".

**Comment by bpasero** [comment]
Then it has to be called `inheritAndCascade` and `defaultAndCascade`. Even though probably the default is always cascading.

**Comment by amol9** [comment]
Don't you think this is an overkill? Who wants that much control over cascading or not cascading? Besides, these option values are getting unnecessarily long. I think a default behavior of cascading a new window when it inherits the size, not configurable, should be enough. If anyone still wants control of that, they can use one of the many window positioning managers available.

**Comment by lslqtz** [comment]
i have same problem...but other editors that I use will not

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
