### ISSUE TITLE
Creating a new folder in open dialog needs a manual refresh (like F5) to show up

### ISSUE THREAD

**Issue by amol9** [Microsoft/vscode#21544]
- VSCode Version: 1.9.1
- OS Version: Windows 10 (Version 1511, Build 10586.545)

Steps to Reproduce:

1. Open VS Code.
2. From File menu, select "Open File" (or "Open Folder", or "Save As").
3. Try to create a new folder by clicking "New Folder".
4. The new folder does not show up.
5. Press F5 to refresh.
6. The new folder shows up.
7. Now, try to rename the folder.
8. When you hit enter after renaming the folder, it still shows as "New Folder".
9. Hit F5.
10. Now, it shows as the renamed folder.

It may be a bug in the common library being used for development for Microsoft products. I verified using Firefox and Notepad. In Firefox, the behavior is alright. I can create new folder and rename it without having to refresh. But, in Notepad, the above mentioned issue is present.

Probably, the developers/maintainers of this project know best where to forward this issue in case it needs to be fixed by some other team at Microsoft.

Thanks.

**Comment by isidorn** [comment]
The issue is not related to VS Code since you can reproduce it in notepad.
However I am not sure where to best file Windows 10 bugs - I would try to us the windows feedback application.
