### ISSUE TITLE
error error MSB4057

### ISSUE THREAD

**Issue by ismelloa** [microsoft/vscode#215472]
Type: <b>Bug</b>

it keeps saying error msb4057 but the file is on the folder

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:01:24.262Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.46GB free)|
|Process Argv|--crash-reporter-id ce853cc3-e1cd-4220-95d4-ee41736a04a3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
csdevkit|ms-|1.7.25
csharp|ms-|2.33.17
vscode-dotnet-runtime|ms-|2.0.6
debugpy|ms-|2024.6.0
python|ms-|2024.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870

```

</details>

**Comment by programaciondb** [comment]
Same issue here, since update getting the error when debugger starts.
_dotnet build /Users/*/wais-distributed/wais-ms/WAIS.sln /target:WAIS_Services_AccessControl /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:Configuration=Debug /p:Platform="Any CPU"_ 
If I open the project alone without the solution, it creates a new sln with only this project and works.
I tried recreating sln file adding one by one the projects trough cli, but it doesn't work when I open the multiproject sln.

**Comment by jacokok** [comment]
Can confirm same issue. Works when I run it with dotnet run but not from vscode debugging.

**Comment by AlexanderInova** [comment]
Same issue here.

This issue is also reported in "vscode-csharp": https://github.com/dotnet/vscode-csharp/issues/7235

**Comment by WardenGnaw** [comment]
This can be closed due to this issue being a specific extension's issue.
