### ISSUE TITLE
White spaces before open bracket is removed

### ISSUE THREAD

**Issue by noopole** [Microsoft/vscode#21547]
- VSCode Version:  1.9.1
- OS Version: Windows 7

Steps to Reproduce:

1. I define a function in Javascript: 
`function myFunction () {`

2. I press [Enter]

The space before the open bracket is suppressed, but I want to keep it.

**Comment by isidorn** [comment]
Do you have "editor.formatOnType" enabled in your user / workspace settings?
Do you still see this behavior if you disable all extensions?

**Comment by noopole** [comment]
Yes it's enabled because I want the auto-formatting feature.
What do you meand by "disable all extensions"? Those you can see with [Ctrl + Maj + X]?

**Comment by isidorn** [comment]
Well the formating defines how to treat the whitespace around the brackets but all of this should be confiurable.
So you should simply configure your formatter.
If that does not suite you you should install a custom formatter extension for javascript.

**Comment by noopole** [comment]
It's not a question it a feature request.
