### ISSUE TITLE
Search results don't automatically update on editor changes, if I move the Search view to another location

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#215437]
1. Open any file
2. Search for `foo`, see some results
3. Type `foo` in the editor, see that result shows up in the search view
4. Delete `foo`, see that result disappears
5. Move the search view below the File Explorer
6. Repeat steps 3-4

:bug: Search results no longer automatically update

**Comment by jeanp413** [comment]
PR fixing it https://github.com/microsoft/vscode/pull/215764
