### ISSUE TITLE
Put shell integration prompt reporting behind a setting

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#215482]
To verify when quality = stable:

1. Enable trace logging
2. Open Terminal output channel
3. Open a pwsh terminal
4. Ensure `P;Prompt` is not in the output
3. Open a bash terminal
4. Ensure `P;Prompt` is not in the output

**Comment by alexr00** [comment]
@Tyriar does this require a sable build to verify?

**Comment by Tyriar** [comment]
Yes, or out of sources with quality=stable

**Comment by rzhao271** [comment]
Step 4 fails. Step 6 seems fine. I have quality=stable and I'm on Windows 11.

![P;Prompt is still shown in Step 4](https://github.com/user-attachments/assets/45369eb7-3d83-4af6-8e9a-200e6d095dd1)
