### ISSUE TITLE
Increase commands history amount in Debug Console

### ISSUE THREAD

**Issue by ttodua** [microsoft/vscode#215433]
in "Debug Console", only  around last 50 run commands are stored in history. Would be good to have an option to manually configure that amount, i.e. increase to last 100 or 200

**Comment by roblourens** [comment]
I think 100 is a good number and matches what we have for history in some other inputs

**Comment by ttodua** [comment]
@roblourens is there an option so user could override it in workspace settings .json ?

**Comment by roblourens** [comment]
No, I don't think it makes sense for this to be customizable

**Comment by ttodua** [comment]
Well, i think one of the major a advantage of VScode is user being able to customize **anything**, regardless what dev.team might be thinking. just my 2 cents. anyway, thanks for the quick pull request
