### ISSUE TITLE
About the security of extensions in the marketplace

### ISSUE THREAD

**Issue by 3f6a** [microsoft/vscode#215429]
I'm not sure if this is the right place to post this. But I've seen several articles about the poor security of extensions in the Market Place, e.g.: https://www.bleepingcomputer.com/news/security/malicious-vscode-extensions-with-millions-of-installs-discovered/

Are there any plans to address these concerns? By perhaps hardening security checks of published extensions?

**Comment by Peter-118** [comment]
We use this tool extensiontotal.com[https://www.extensiontotal.com/](url) API to manage the risk across the organization. I think the same guy who developed it posted this research.

**Comment by isidorn** [comment]
https://code.visualstudio.com/docs/editor/extension-marketplace#_can-i-trust-extensions-from-the-marketplace
