### ISSUE TITLE
Error viewing changelog

### ISSUE THREAD

**Issue by dusrdev** [microsoft/vscode#215463]
Type: <b>Bug</b>

Using the command "view change log" to see the changes in the vscode version, results in an error window:

Title: "Command `View Change Log` resulted in an error"
Description: "command `git.commit.ViewChangeLog` not found

VS Code version: Code 1.90.1 (Universal) (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:41.372Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.23GB free)|
|Process Argv|--crash-reporter-id f7354264-bad7-4e1e-98e4-103ef719805d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
add-reference|adr|1.0.2
vscode-avalonia|Ava|0.0.31
toml|be5|0.6.0
path-intellisense|chr|2.9.0
auto-dark-mode-windows|dan|1.0.11
vscode-markdownlint|Dav|0.55.0
auto-region-folder|DNE|1.0.1
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|15.1.0
vscode-html-css|ecm|2.0.10
font-switcher|eva|4.1.0
unity-dev-pack|fab|3.0.1
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
visual-nuget|ful|0.2.1
copilot|Git|1.201.0
copilot-chat|Git|0.16.1
vscode-pull-request-github|Git|0.88.1
rest-client|hum|0.25.1
ilspy-vscode|ics|0.18.0
better-cpp-syntax|jef|1.17.2
vscode-peacock|joh|4.2.2
vscode-csharp-snippets|jor|1.1.0
roslynator|jos|4.12.4
vscodeilviewer|jos|0.0.1
mips|kda|0.1.1
unity-code-snippets|kle|2.4.0
compare-folders|mos|0.24.3
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.29.1
csdevkit|ms-|1.7.25
csharp|ms-|2.33.17
dotnet-maui|ms-|1.0.6
vscode-dotnet-runtime|ms-|2.0.6
vscode-edge-devtools|ms-|2.1.5
remote-containers|ms-|0.369.0
hexeditor|ms-|1.10.0
makefile-tools|ms-|0.9.10
vscode-speech|ms-|0.10.0
vscode-witcherscript|nic|1.0.9
dotnet-meteor|nro|4.6.3
unity-toolbox|pix|100.0.2
markdown-checkbox|PKi|1.9.1
material-icon-theme|PKi|5.4.1
material-product-icons|PKi|1.7.0
vscode-unitymeta|PTD|0.0.7
vscode-xml|red|0.27.1
LiveServer|rit|5.7.9
partial-diff|ryu|1.4.3
code-spell-checker|str|3.0.1
code-spell-checker-hebrew|str|2.0.2
unity-tools|Tob|1.2.12
pdf|tom|1.2.2
vscode|uno|0.14.1
vstuc|vis|1.0.2
generic-pseudocode|Wil|1.4.1
change-case|wma|1.0.0
txt-syntax|xsh|0.2.2
highlight-trailing-white-spaces|yba|0.0.2
html-css-class-completion|Zig|1.20.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870

```

</details>

**Comment by lszomoru** [comment]
@dusrdev, the "view change log" command is probably contributed by one of the extensions that you have installed. You would probably have to track down the extension that contributes it, and reach out to the extension author to track down the root cause of the error.
