### ISSUE TITLE
Make sticky scroll more explicit for new users

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#215440]
Sticky scroll is turned on by default for a couple of builds now. We are receiving issues and concerns from users who do not know what the sticky widget is and who confuse it with the editor lines. They think the sticky widget is an editor bug. This issue is about how to handle this issue. Several ideas have been proposed:

- Turn the sticky widget on by default only when an outline provider is available. For some languages like C# where allman style braces are used, if there are no outline providers, one can see only brackets in the sticky widget, which provides little useful information. To mitigate this, we can introduce a setting which shows the sticky scroll lines only when an outline provider is available. The lines in the sticky widget would then carry in general more useful information. 
- Add a pin on the sticky widget in the far right bottom corner of the sticky widget. When the pin is unpinned (by clicking on it), this would remove the sticky widget. This is a quick way to remove the sticky lines, and indicates to new users this is an individual widget. 
- Instead of adding a pin, we could add a gear icon on the far bottom right, which when clicked, opens the context menu from which it would be possible to toggle the sticky scroll on and off.
- The sticky widget background color corresponds to the editor background color. This is done for aesthetic purposes. Perhaps we could change the sticky scroll widget background color to something lighter or darker than the default background colors of the base themes. 
- We could also make larger the drop shadow of the sticky widget. This would make it clearer that the sticky widget lies on top of the editor.
- We could add a tooltip on the sticky widget. When you would hover over the sticky scroll lines, you would see a tooltip with some information like 'Line 14 is the sticky scroll widget'.

Pinging @daviddossett about thoughts, cc @hediet

**Comment by aiday-mar** [comment]
Hi @daviddossett I was wondering what your thoughts are concerning the above?

**Comment by daviddossett** [comment]
In general I like the idea of having something like a pin to more clearly convey that metaphor. We should play with a few ideas here. I can find sometime after we chat in the UX sync.

**Comment by daviddossett** [comment]
Sounds good, I think that's a good place to start and we can tweak from there

**Comment by JeremyTBradshaw** [comment]
Throwing my name in the hat for those who are unfamiliar with sticky scroll and do not like it.   The thing buggers up in Terminal (WindowsPowerShell/PowerShell, doesn't matter) and you simply cannot get a clean CLS / Clear-Host.  I just realized I could hover my mouse over the sticky scroll area and right-click to un-check it being enabled.  Would have no idea how to describe the issues caused, and have somebody here understand (way too difficult to describe concisely).  I tried once before and was told it's an issue only with Windows 10, not 11, which I never have confirmed.  In any case, would totally agree this feature came out of the blue and for me, not knowing anything about it, or wanting it, has just be a pain, which I have gotten clear of by disabling the feature.

**Comment by aiday-mar** [comment]
Closing this issue as sticky scroll has been enabled by default for a long time and we have increased the length of the drop down shadow. I will monitor if other issues about making sticky scroll more explicit pop up.

**Comment by t1u1** [comment]
@aiday-mar Is the drop-shadow only visible in certain color themes? I can see it in the default themes but not in [August Themes](https://github.com/inci-august/august-themes), for example. Do I need to raise an issue with individual theme developers if I can't see the drop shadow?

**Comment by aiday-mar** [comment]
Hi the drop shadow of sticky scroll still exists as an option. If you do not see it, you can raise an issue with the specific themes.

**Comment by MasterInQuestion** [comment]
I have &#x60;`"editor.stickyScroll.enabled": false`&#x60; by default.
    And only toggle it on need. (typically via keyboard shortcut; at times by toolbars menu)
