### ISSUE TITLE
syntax and unknown error

### ISSUE THREAD

**Issue by khaingphyo123** [microsoft/vscode#215497]
Type: <b>Bug</b>

All of my html file is good before updating vs studio app, but after updating, it shows all of the html elements as syntax and unknown error.

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:01:24.262Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.77GB (1.89GB free)|
|Process Argv|--crash-reporter-id 40e21ba0-2ce5-420a-99dd-8c9e4e97e147|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.2.1
vscode-intelephense-client|bme|1.10.4
vscode-eslint|dba|2.4.4
composer-php-vscode|DEV|1.47.15512
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.47.15512
profiler-php-vscode|DEV|1.47.15512
javascript-ejs-support|Dig|1.3.3
vscode-html-css|ecm|2.0.10
vscode-toggle-column-selection|eri|1.0.6
prettier-vscode|esb|10.4.0
file-icons|fil|1.1.0
auto-close-tag|for|0.5.15
html-snippets|gey|0.2.3
stylelint-plus|hex|0.57.0
php-namespace-resolver|Meh|1.1.9
live-server|ms-|0.4.13
color-highlight|nau|2.8.0
material-icon-theme|PKi|5.4.2
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|6.0.0
php-debug|xde|1.34.0
php-pack|xde|1.0.3
html-css-class-completion|Zig|1.20.0
php-intellisense|zob|1.3.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
newcmakeconfigv2:31071590

```

</details>

**Comment by aeschli** [comment]
The built-in HTML extension does not do any validation of HTML. You need to find out which extension does that. 
You can use the command `Start Extension Bisect` to help you finding that extension
