### ISSUE TITLE
When closing the application with ZenMode enabled, the Title Bar set to custom disappears (hidden) upon re-opening

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [microsoft/vscode#215408]
Type: <b>Bug</b>

- Set the "Title Bar Style" to "custom"
- Set "Custom Bar Visibility" to "never"
- Show the "Command Center"
- Set "Menu Bar Visibility" to `visible`
- Disable "ZenMode: Restore" (personally I disable all options and enable "hide activity bar")
- Go into zen mode
- Close the application
- Open the application, the control center should be missing

https://github.com/microsoft/vscode/assets/1329559/94110b1b-d01d-4f22-9b21-75e3370c0caf

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:43:07.605Z)
OS version: Linux x64 6.5.0-35-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 3867)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|31.24GB (22.80GB free)|
|Process Argv|--crash-reporter-id 581ff5cd-8418-40ad-99d9-462a99958945|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (95)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
hurl|Ale|0.0.1
All-Autocomplete|Ati|0.0.26
rtorrent-rc-helper|ber|1.0.0
emojisense|bie|0.10.0
markdown-emoji|bie|0.3.0
markdown-preview-github-styles|bie|2.0.4
pgformatter|bra|1.28.1
vscode-gemfile|bun|0.4.2
circleci|Cir|2.8.3
vscode-postgres|cko|1.4.3
gotoanything|Cma|0.4.1
gitignore|cod|0.9.0
markdown-table-prettify|dar|3.6.0
vscode-eslint|dba|2.4.4
javascript-ejs-support|Dig|1.3.3
chmod|dle|1.1.1
prettier-vscode|esb|10.4.0
markdown-table-formatter|fcr|3.0.0
shell-format|fox|7.2.5
vscode-hcl-format|fre|1.0.0
kotlin|fwc|0.2.34
macros|ged|1.2.1
ctrl-semicolon|Gfo|0.1.0
copilot|Git|1.201.0
copilot-chat|Git|0.16.1
vscode-pull-request-github|Git|0.88.1
gleam|gle|2.9.0
go|gol|0.41.4
gc-excelviewer|Gra|4.2.59
vscode-systemd-support|han|2.2.0
hcl|has|0.5.0
vscode-drawio|hed|1.6.6
vscode-es6-string-html|hjb|1.1.1
crontab-syntax-highlight|hog|0.0.2
vscode-power-mode|hoo|3.0.2
path-autocomplete|ion|1.25.0
pfeifer-hurl|Jac|1.3.2
elixir-ls|Jak|0.22.0
vscode-insertdatestring|jsy|2.3.1
haml|kar|1.4.1
fuzzy-goto-line|kyl|0.9.1
bash-ide-vscode|mad|1.41.0
tmux|mal|0.4.0
rainbow-csv|mec|3.12.0
file-downloader|min|1.0.13
revealfileinfolder|Mol|0.0.4
compare-folders|mos|0.24.3
git-web-link|mro|1.2.0
vscode-docker|ms-|1.29.1
playwright|ms-|1.1.6
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.8.0
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.369.0
azure-repos|ms-|0.38.0
cpptools|ms-|1.20.5
remote-repositories|ms-|0.40.0
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.5932
sqltools|mtx|0.28.3
sqltools-driver-pg|mtx|0.5.4
angular-console|nrw|18.21.4
advanced-new-file|pat|1.2.2
excalidraw-editor|pom|3.7.4
calc|rai|2.3.2
ansible|red|24.6.0
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
vscode-gitweblinks|red|2.11.0
elixir-formatter|sar|1.3.0
markdown-preview-enhanced|shd|0.8.13
ruby-lsp|Sho|0.7.4
slim|sia|0.1.2
vscode-fileutils|sle|3.10.3
snowflake-vsc|sno|1.7.5
rbs-syntax|sou|0.2.1
even-better-toml|tam|0.19.2
fuzzy-search|tat|1.4.0
shellcheck|tim|0.37.1
es6-string-html|Tob|2.15.0
highlight-matching-tag|vin|0.11.0
whichkey|VSp|0.11.4
vscode-nginx|wil|0.7.2
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.6.2
html-css-class-completion|Zig|1.20.0
vscode-open-in-github|ziy|1.3.6
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
showvideot:31016892
chatpanelt:31048053
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
26j00206:31048877

```

</details>

**Comment by benibenj** [comment]
Thanks you for reporting this bug. It seems to be caused by the `zenMode.fullScreen` setting.

**Comment by eleanorjboyd** [comment]
how do I do the set `"Menu Bar Visibility" to visible` in order to test this?

**Comment by Fire-Dragon-DoL** [comment]
> how do I do the set `"Menu Bar Visibility" to visible` in order to test this?

_File -> Preferences -> Settings_, search "menu bar visibility", it shows the option: "WIndow: Menu Bar Visibility". From the select box, choose `visible`

If your menu is hidden and you can't figure out how to open it, use the following command `>View: Toggle Menu Bar` which should make it appear again.

**Comment by andreamah** [comment]
@benibenj I'm still getting a missing command center on reload when I'm on zen mode.

![image](https://github.com/user-attachments/assets/38fa84cc-a6d4-4a82-8e3f-3e06d19e980d)
