### ISSUE TITLE
Please support skipfiles and entries starting with '!'

### ISSUE THREAD

**Issue by mmc41** [Microsoft/vscode#21542]
- VSCode Version: 1.9.1
- OS Version: OS X 10.12

When using component-based development with node (multiple of my own npm packages in play) and when debugging a project, it is very useful to be able to skip all node_modules EXCEPT one's own npm's (see example below). Unfortunately, when trying to do so, I get a msg "skipFiles entries starting with '!' aren't supported and will be ignored."

```
        "skipFiles": [
	       "${workspaceRoot}/node_modules/**/*.js",
                "!${workspaceRoot}/node_modules/my-own-module**/*.js"
	 ],
```

**Comment by weinand** [comment]
For the debug type 'node' glob patterns with '!' are supported.
@roblourens for 'node2' this is not implemented, right?

**Comment by mmc41** [comment]
Forgot to say, that I am using node2

**Comment by roblourens** [comment]
Tracking it here: https://github.com/Microsoft/vscode-chrome-debug-core/issues/137
