### ISSUE TITLE
Show execution status in the left column for collapsed cells/

### ISSUE THREAD

**Issue by davies-w** [microsoft/vscode#215487]
I come from colab land, and while I like being able to run Jupyter in VS Code, one feature of Google Colab that I really miss is the ability to see the run time, execution time, even when the cells are collapsed. Colab lets you see these statuses in the sidebar next to cell. 

Why is this an issue? Well, cells often get to be pretty large, and so once they're working I tend to fold them up so I can focus on the next stage, but sometimes I'll need to re-run one, and its nice to see the last time they were last run, without having to expand the cell and then find the bottom etc.

Thanks for considering it,
 Winton

**Comment by DonJayamanne** [comment]
Closing as fixed as we do display such an indicator today for collapsed cells.
![Image](https://github.com/user-attachments/assets/77e51153-7169-4011-94de-f0464e119c7a)
