### ISSUE TITLE
when at the bottom of the terminal, terminal chat doesn't show

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#215456]
1. open a terminal and fill it so the prompt is at the bottom
2. try to use `ctrl/cmd+i` to open chat
2. we bound the bottom and the top, so it's not visible

**Comment by meganrogge** [comment]
should we:
1. clear the terminal, which brings the chat into view at the top 
2. just keep it really small at the bottom
3. start to show it above the prompt

**Comment by Tyriar** [comment]
What's the problem? Hasn't this always worked so if it regressed we should just go back to how it was?

**Comment by meganrogge** [comment]
It hasn't always worked. I made changes to fix https://github.com/microsoft/vscode-copilot/issues/5228

**Comment by Tyriar** [comment]
The way I intended for it to work was when it shows up it pushed the terminal up, such that the cursor is visible. I think we missed the case initially for when the chat is too tall it should be restricted such that the cursor is still visible (ie. it's on the top line)

**Comment by meganrogge** [comment]
Yes, what's happening at the moment is it's disappearing when it gets larger than the terminal container. It should instead look like what happens when I run `clear` after, agreed?

https://github.com/user-attachments/assets/19b6aad5-090d-4a63-8341-b625f2890b03

**Comment by meganrogge** [comment]
```
with prompt at the top and widget filling terminal height:
wrapper height 459
terminalChatWidget.ts:163 widget height 461
terminalChatWidget.ts:164 top 95

with prompt at the bottom and widget filling terminal height:
wrapper height 459
terminalChatWidget.ts:163 widget height 526
terminalChatWidget.ts:164 top 459
```
