### ISSUE TITLE
Strange behaviour when writing backticks with Norwegian keyboard.

### ISSUE THREAD

**Issue by Astroxslurg** [microsoft/vscode#215450]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90
- OS Version: Ubuntu 22.04

Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:43:07.605Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.0-35-generic

### VSCode enters some kind of mysterious mode when writing backtick character with Norwegian keyboard layout.

Using a Norwegian keyboard layout, when writing a backtick (using shift + the button just left of backspace) VSCode enters some kind of mysterious mode - shown by an underscore under the backtick.  
  ![image](https://github.com/microsoft/vscode/assets/155447548/0836b160-08df-4534-877c-3e24b1dea7fd)

At this point most buttons will only cause this mode to be exited (meaning you will have to push it two times to get the wanted behaviour). However, what I usually want to do is to to navigate to the end of the word using `ctrl+right` (cursorWordEndRight).
This however, causes the word left of the cursor to be hightlighted while the cursor itself is still shown next to the backtick. See picture below, where `ctrl+right` have been pressed 3 times:  
![image](https://github.com/microsoft/vscode/assets/16885190/d10dd504-7720-4760-99e7-fba9a4d3fa63)

Finally, when another backtick is written, this backtick will actually overwrite the last character next to the (invisible) cursor!  
![image](https://github.com/microsoft/vscode/assets/16885190/255d41be-5f3a-486e-9108-bdec4aaecc32)

## Steps to Reproduce:

1. Use a Norwegian keyboard layout (or perhaps also another scandinavian keyboard?)
2. Write a backtick

At this point it's already annoying, but for maximum annoyance:

3. Press ctrl+right
4. Write another backtick

**Comment by alexdima** [comment]
It looks like backtick is used for input composition. Here is how it looks like on a mac, but I suppose you're seeing something similar on Linux


https://github.com/user-attachments/assets/9b596249-26d5-4bed-af05-63dfcd2108f2

**Comment by Astroxslurg** [comment]
That makes sense 😅 
Thank you for the clarification! 🙏🏻 

I will see if I'm able to find a way to disable this feature and post it here for posterity!

**Comment by Astroxslurg** [comment]
Disabling this feature seems to be a big hassle.
Easiest fix is to just press backtick twice every time it's used.
