### ISSUE TITLE
abnormal

### ISSUE THREAD

**Issue by luoqi21178** [microsoft/vscode#215411]
ADD ISSUE DESCRIPTION HERE

Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by DonJayamanne** [comment]
Closing this issue due to the lack of infmormation `ADD ISSUE DESCRIPTION HERE`
If you are still facing issues, please feel free to create a new issue providing more information about the issue you are facing, probably with logs or screenshots of the error/problem.
