### ISSUE TITLE
After update now it feels slow

### ISSUE THREAD

**Issue by akashthapa** [microsoft/vscode#215503]
Type: <b>Performance Issue</b>

After update scroll and switching file tabs became slow. 

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:43.666Z)
OS version: Linux x64 6.5.0-35-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 3499)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|15.49GB (12.24GB free)|
|Process Argv|--force-user-env --no-sandbox --use-gl=angle --use-angle=swiftshader --crash-reporter-id 56bb87d9-126f-4446-b500-fb4bd7a13a13|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   159	  4134	code main
    0	    32	  4136	   zygote
    0	    32	  4137	   zygote
    0	   349	  4209	window [1] (InviteManager.ts - user-dashboard - Visual Studio Code)
    0	    95	  4608	window [2] (Issue Reporter)
    0	    63	  4185	   utility-network-service
    0	    79	  4242	ptyHost
    0	     0	  4333	     /usr/bin/bash --init-file /snap/code/161/usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	   270	  4252	extensionHost [1]
    0	   111	  4304	     electron-nodejs (tsserver.js )
    0	   206	  4305	     electron-nodejs (tsserver.js )
    0	    63	  4321	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    63	  4354	     electron-nodejs (serverMain.js )
    0	   206	  4407	     /snap/code/161/usr/share/code/code /home/akash/.vscode/extensions/streetsidesoftware.code-spell-checker-3.0.1/packages/_server/dist/main.cjs --node-ipc --clientProcessId=4252
    0	    95	  4431	     electron-nodejs (tailwindServer.js )
    0	    95	  4267	shared-process
    0	     0	  4622	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  4623	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   111	  4268	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (InviteManager.ts - user-dashboard - Visual Studio Code)
|    Folder (user-dashboard): 625 files
|      File types: tsx(248) ts(125) svg(36) png(31) css(17) json(8) txt(5)
|                  md(4) map(3) js(3)
|      Conf files: launch.json(1) settings.json(1) package.json(1)
|                  tsconfig.json(1)
|      Launch Configs: chrome;
```

</details>
<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vim-cheatsheet|And|0.0.1
vscode-tailwindcss|bra|0.10.5
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
copilot|Git|1.202.932
copilot-chat|Git|0.16.1
ftp-simple|hum|0.7.6
vscode-language-babel|mgm|0.0.40
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
material-icon-theme|PKi|5.4.2
vscode-react-refactor|pla|1.1.3
vscode-thunder-client|ran|2.24.11
LiveServer|rit|5.7.9
code-spell-checker|str|3.0.1
sass-indented|syl|1.8.29
vsfire|tob|1.4.1
quokka-vscode|Wal|1.0.646
vscode-todo-highlight|way|1.0.5
glean|wix|5.2.2
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
newcmakeconfigv2:31071590

```

</details>

**Comment by emilyhunt** [comment]
Can confirm I'm noticing a similar issue on Ubuntu 24.04 with vscode installed via snap. Selecting text and general editing feels much slower. 

Reverting to 1.89.1 has completely fixed the issue.

**Comment by shelvesdragon** [comment]
This is likely related to the workaround in #212494 being implemented as a temporary fix to crashes on startup with the snap package. Since the issue was only partially resolved, it is recommended to revert to 1.89.1/snap revision 159 since that avoids the crashes or to switch to the debian package until the issue is resolved.

> Please revert to v1.89 or use debian package till this issue is fixed.
https://github.com/microsoft/vscode/issues/212494#issuecomment-2166941209

Snap revert: 
```bash
sudo snap revert code --revision 159
```
Properly installing debian package with signature checks working can be found in this comment: https://github.com/microsoft/vscode/issues/212494#issuecomment-2119250968

**Comment by sylvainpelissier** [comment]
It is the same to me and Manjaro and is is related to #215502.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/212494, please follow the issue for updates.
