### ISSUE TITLE
Git - Stage Changes (`git.stageFile`) doesn't seems to work using a keybinding

### ISSUE THREAD

**Issue by Skazio** [microsoft/vscode#215587]
# Git: Stage Changes

I tried to add a keybinding for "Git: Stage Changes" (`git.stageFile`) and use it to stage a file, but nothing happened

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d) x64
- OS Version: Win10

## Pre-requisite

Add a Keybinding for "Git: Stage Changes" (`git.stageFile`)

## Steps to Reproduce:

1. Open a folder
2. Run `git init` in that folder
3. Create a new file
4. Open "Source Control" (`Ctrl+Shift+G`)
5. Tab (or use vim keybinding) to hover the file
6. Press the `git.stageFile` keybinding

=> **The file is not staged**

---

You can also:

1. Open a folder
2. Run `git init` in the folder
3. Create a new file
4. Open the file
5. Press the `git.stageFile` keybinding

=> **The file is not staged**

I don't know if I'm using the keybinding wrongly or if this is really a problem

**Comment by lszomoru** [comment]
The `git.stageFile` command is specific to the multi-file diff editor. The "+" action in the "Source Control" view executes the `git.stage` command. Having said that, the problem with executing a command using a keybinding is that no context (ex: the resource URI) is being passed to the command, hence the command exits silently as it does not have the necessary context information. I will see if there is anything that we an do in order improve this experience.
