### ISSUE TITLE
Filtering in tree views no longer works

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#215548]
1. Open stable VS Code 1.89
2. Ctrl+F in the explorer and notice tree filtering works
3. Open Insiders or VS Code 1.90
4. Ctrl+F in the explorer and notice you can no longer filter in tree views

**Comment by benibenj** [comment]
The keybinding has been changed to `Ctrl+Alt+F` but you can switch it back by changing the `list.find` keyboard shortcut

**Comment by connor4312** [comment]
As mentioned in chat, we should really have some kind of signal or hint to users that a keybinding changed. Probably too late now though, but we could at least have a label for the keybinding in the keybindings editor so users can find it more easily.
