### ISSUE TITLE
Ruby 2.3 tilda (squiggly) heredoc not recognised as a string

### ISSUE THREAD

**Issue by raldred** [Microsoft/vscode#21553]
- VSCode Version: 1.9.1
- OS Version: OSX 10.12.3

Steps to Reproduce:

1. Create a ruby file
2. Enter the following, observe lack of formatting

```
string = <<~STRING
Example heredoc squiggly heredoc introduced in ruby 2.3 not recognised as string
STRING
```

Original ruby heredoc format works fine. 
```
string = <<-STRING
Example heredoc standard heredoc not recognised as string
STRING
```

**Comment by isidorn** [comment]
Please file this agains the ruby extension here https://github.com/rubyide/vscode-ruby

**Comment by raldred** [comment]
Sorry about that, I will do.
