### ISSUE TITLE
New update brought back ansi escape codes

### ISSUE THREAD

**Issue by Mhytos** [microsoft/vscode#215507]
Type: <b>Bug</b>

I have had this problem before the newest update and fixed it by replacing a .ps1 file with one from a previous commit. now the error is back again, showing me ansi escape codes in the terminal when using powershell with oh-my-posh

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:01:24.262Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7940HS w/ Radeon 780M Graphics      (16 x 3992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.22GB (16.09GB free)|
|Process Argv|--crash-reporter-id 745abfdc-e7f8-4a03-8304-446b4a06f2ac|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
vim-cheatsheet|And|0.0.1
ng-template|Ang|18.0.0
codeium|Cod|1.8.59
githistory|don|0.6.20
git-project-manager|fel|1.8.2
auto-rename-tag|for|0.1.10
gitlab-workflow|Git|4.15.1
git-graph|mhu|1.30.0
mongodb-vscode|mon|1.6.0
vscode-docker|ms-|1.29.1
csdevkit|ms-|1.7.25
csharp|ms-|2.33.17
vscode-dotnet-runtime|ms-|2.0.6
debugpy|ms-|2024.6.0
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
remote-containers|ms-|0.369.0
indent-rainbow|ode|8.3.1
LiveServer|rit|5.7.9
markdown-preview-enhanced|shd|0.8.13
vscode-pets|ton|1.27.0
vscode-icons|vsc|12.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
showvideoc:31016891
chatpanelc:31048052
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
newcmakeconfigv2:31071590

```

</details>

**Comment by meganrogge** [comment]
this is already fixed in insider's
