### ISSUE TITLE
serve-web | error: unexpected argument '--no-sandbox' found | Since VSCode 1.90+

### ISSUE THREAD

**Issue by kevinderuijter** [microsoft/vscode#215535]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: 1.90.1 | 611f9bfce64f25108829dd295f54a6894e87339d | x64
- OS Version: Ubuntu 24.04 (Updates 14 Jun 2024)

I get the error `error: unexpected argument '--no-sandbox' found` on a fresh installation of Ubuntu 24.04 and VSCode 1.90.1
**Everything works fine with VSCode version `1.89.1` dc96b837cf6bb4af9cd736aa3af08cf8279f7685.**

Steps to Reproduce:

1. Install latest version of Ubuntu 24.04.
2. Run `snap install code --classic` command.
3. Run `code serve-web` command.

**Comment by mbuttery-ghd** [comment]
Hi @Clement-Lelievre 
Having this `code tunnel` issue on remote VM Ubuntu 20.4. Install errors with `error: cannot find signatures with metadata for snap "./stable.snap"`
Solved by using the `--dangerous` flag
