### ISSUE TITLE
VS Code Native REPL and Interactive Window shows unexpected error when interactive tab is moved 

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/vscode#215544]
![Screenshot 2024-06-14 at 12 26 52 AM](https://github.com/microsoft/vscode-python/assets/62267334/20c53388-45de-473f-b137-28abde3bbfa1)
When opening REPL( Or interactive window)  tab (opens beside active tab), and then moving that tab into active tab or other section, it suddenly crashes REPL tab that was opened.

notebookEditor becomes undefined, and trying to look for notebookEditor using saved referenced of notebookDocument via ```return window.visibleNotebookEditors.find((editor) => editor !== undefined);``` doesnt work because ```window.visibleNotebookEditors``` simply returns no notebook editors. so there is nothing to search for

Same happens for interactive window: 

https://github.com/microsoft/vscode-python/assets/62267334/0e93cf45-3012-4ef2-9dc3-572dfb15163a

**Comment by amunger** [comment]
It looks like the scoped instantiation service is tied to the editor group, and when that group is closed because it has no more tabs, the instantiation service is disposed.
There doesn't seem to be any usage of the instantiation service after the initial setup of the editor, except for the `notebookEditorToolbar`, when using the `WorkbenchAlwaysLabelStrategy`, so the notebook toolbar breaks, and also throws an uncaught exception when the editor is shown.

**Comment by amunger** [comment]
Looks like a regression from https://github.com/microsoft/vscode/pull/185168, specifically right here: https://insiders.vscode.dev/github/microsoft/vscode/blob/main/src/vs/workbench/contrib/notebook/browser/viewParts/notebookEditorToolbar.ts#L83 

repro steps:
1. open two text editors side by side in two tab groups
2. focus the second tab group and open a notebook
3. move the notebook to the first tab group
4. close the rest of the tabs from the second tab group

:bug: toolbar disappears

5. focus the other editor to hide the notebook, then focus the notebook editor

:bug: editor fails to load

**Comment by amunger** [comment]
this affects more than just the toolbar, so we need a broader fix, regressed when we started cleaning up instantiation service children in https://github.com/microsoft/vscode/pull/209421

**Comment by anthonykim1** [comment]
I can still repro this in 1.91.0 - insider 

https://github.com/microsoft/vscode/assets/62267334/195e7c2d-2e77-4e52-9233-733d731b576c
Should we  be concerned?

**Comment by amunger** [comment]
insiders hasn't been updated yet for some reason (the issue is still tagged with unreleased)
