### ISSUE TITLE
I don't like the font that VS Code is using

### ISSUE THREAD

**Issue by andreshg112** [Microsoft/vscode#21559]
![font visual studio code](https://cloud.githubusercontent.com/assets/15859884/23410758/339b681c-fd9e-11e6-91e1-751ae8421a96.png)

I'm not sure what is happening but I think that after installing PlayOnLinux, I have this problem.

How can I restore VS Code's default font?

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.4.0-64-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|compulim-vscode-closetag|Compulim|0.1.2|
|ejs-language-support|QassimFarid|0.0.1|
|eval|Stormspirit|0.0.6|
|html-snippets|abusaidm|0.1.0|
|vscode-css-formatter|aeschli|0.0.2|
|htmltagwrap|bradgashler|0.0.3|
|vscode-svgviewer|cssho|1.3.1|
|githistory|donjayamanne|0.1.5|
|jquerysnippets|donjayamanne|0.0.1|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.3|
|auto-rename-tag|formulahendry|0.0.11|
|vscode-firefox-debug|hbenl|0.8.8|
|docthis|joelday|0.4.0|
|Angular1|johnpapa|0.1.16|
|ionic1-snippets|justinjames|1.0.1|
|HTMLHint|mkaufman|0.3.3|
|cssclasshint|nicolasalcaraz|0.0.3|
|laravel5-snippets|onecentlin|1.3.2|
|laravel-artisan|ryannaddy|0.0.3|
|standard|shinnn|0.2.3|
|html5-boilerplate|sidthesloth|1.0.1|
|cordova-tools|vsmobile|1.2.6|

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Double check both your user and workspace settings - there migth be some setting which is changing your font.
Then I see you have a lot of extensions installed, maybe some of them is changing the font. Try disabling all extensions and see if the issue reproduces.

You can also always manually set your `editor.fontFamily` in your settings to whatever font you want

**Comment by andreshg112** [comment]
Thanks, @isidorn.
What's the default fontFamily for VS Code?

**Comment by isidorn** [comment]
http://stackoverflow.com/questions/29960057/which-font-is-used-in-visual-studio-code-editor-and-how-to-change-fonts

**Comment by andreshg112** [comment]
I run in my terminal: `code --disable-extensions`
However, I still have the same ugly font.
I've had to use Verdana.

**Comment by deeptimhe** [comment]
@andreshg112 
I got this problem as well. Did you any way to figure out?

**Comment by andreshg112** [comment]
@deeptimhe, I didn't solve it but I decided to use the font Verdana. It was good enough for me.

**Comment by sjdweb** [comment]
For me at least, this was solved by first viewing the user settings (File>Preferences>Settings), and when I added `editor.fontFamily` to the object I found the default settings out, which were:
```json
"editor.fontFamily": "'Droid Sans Mono', 'Courier New', monospace, 'Droid Sans Fallback'",
```

As I'm running Linux Mint I don't believe this distro or Ubuntu carry **Droid Sans Mono** by default any more, so I simply downloaded it from Google Fonts (direct link: `https://fonts.google.com/download?family=Droid%20Sans%20Mono`) and installed it via the normal means.

Restarted VS Code and voila! Nice fonts again.

**Comment by asuraphel** [comment]
@andreshg112 I changed the font to `DejaVu Sans Mono`. The difference was unbelievable.

**Comment by RyanPridgeon** [comment]
@asuraphel Thanks! This has just saved my life

**Comment by bensonkb** [comment]
@asuraphel Thanks !

**Comment by knsong** [comment]
@sjdweb  Yes, nice fonts again. Thanks!

**Comment by valeriy-devpronet** [comment]
the same was happened after installing `sudo apt-get install ubuntu-restricted-extras` which was shipped with MS fonts. Solution of @asuraphel solved the problem

**Comment by bay007** [comment]
may be this like you https://m.genbeta.com/herramientas/han-disenado-una-tipografia-ideal-para-escribir-codigo-y-es-open-source

**Comment by dagolinuxoid** [comment]
in your terminal `vi ~/.config/Code/User/settings.json` set **"editor.fontFamily": "Liberation Mono",
    "editor.fontSize": 14** it looks gorgeous :)

**Comment by highskillzz** [comment]
Upto the newest update in my vs code there was no problem with the font in the integrated terminal but now it suddenly changed to something very awful Now I am using 1.17.1 version. I checked the user setting and nothing changed.
Please help

**Comment by sjdweb** [comment]
@highskillzz seeing this too after updating just now! Is there an issue submitted for this?

**Comment by wizardion** [comment]
Same too. I don't understand what happened with new version of VSCode, but here my screens before and after:

![screenshot from 2017-09-15 10-06-37](https://user-images.githubusercontent.com/2981194/31485678-4f5306d6-af3d-11e7-9c72-3fc4c4da0b0b.png)

![screenshot from 2017-10-12 10-45-35](https://user-images.githubusercontent.com/2981194/31485692-59a64ca6-af3d-11e7-970a-12eea9153641.png)

"terminal.integrated.fontFamily": "Source Code Pro"

**Comment by sjdweb** [comment]
Issue here #35991

**Comment by wizardion** [comment]
Thanks for the quick fix!

**Comment by harrytallbelt** [comment]
Same thing happened after finally installing ttf-mscorefonts-installer package on Ubuntu 16.04. So it isn't really a bug - before installing the fonts Code probably just fell back on Liberation Mono, which happen to look nicer on Ubuntu.
