### ISSUE TITLE
Ruler in notebook cells should extend to the border of the cell (not just the invisible end of the editor)

### ISSUE THREAD

**Issue by rehmsen** [microsoft/vscode#215517]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.1
- OS Version: macOS Sonoma 14.5

Steps to Reproduce:

1. Configure a ruler, e.g. with
    ```
    "editor.rulers": [
        80
    ]
    ```
2. Open a notebook file e.g. /Users/oler/Code/vscode/extensions/vscode-api-tests/testWorkspace/test.ipynb

Actual:

<img width="1081" alt="image" src="https://github.com/microsoft/vscode/assets/29040/877debcc-1788-4b62-952c-f59204cd3f8a">

Expected: 

The ruler should probably extend to the end of the cell. I think it's because the actual editor is only those two lines, and then there is a status bar with the language. But visually it looks a bit broken because the editor has no bottom boundary, so stopping the ruler there is weird.

**Comment by rebornix** [comment]
Agree that it looks out of place.

Currently the cell status bar is rendered next to the cell editor, maybe we could explore setting a padding bottom in the text editor, and then render the cell status bar on top of the text editor with a higher `zindex`.
