### ISSUE TITLE
SecCodeCheckValidity -67062 v1.91.0-insider

### ISSUE THREAD

**Issue by TicTak21** [microsoft/vscode#215529]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.91.0-insider
- OS Version: MacOS Catalina 10.15.7

Steps to Reproduce:

1. Launch code-insiders from the terminal or as an application

```
[0614/124607.824447:ERROR:codesign_util.cc(109)] SecCodeCheckValidity: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)" (-67062)
1.91.0-insider
0a417782b1781d39803b8f1791cfb22f8835ddae
x64
```

Also I got a [dmp.zip](https://github.com/user-attachments/files/15836526/dmp.zip) file by following [this guide](https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues)

Related to: #210760, #204085

**Comment by TicTak21** [comment]
@joaomoreno Hello, I still have this error. Any chance you can help?

**Comment by kirillsh93** [comment]
Found this solution on StackOverflow (not sure what it does but it helped):
`codesign --force --deep --sign - /Applications/Visual\ Studio\ Code.app`

[source](https://stackoverflow.com/questions/78023478/vs-code-code-cli-returns-seccodecheckvalidity-error)

**Comment by TicTak21** [comment]
Closing, as v1.92.0-insider works for me.
