### ISSUE TITLE
VSCode Won't Run on Mac OSX 10.8.5

### ISSUE THREAD

**Issue by DavidPereira69** [Microsoft/vscode#2155]
I just downloaded a fresh copy of VSCode-darwin.zip from https://code.visualstudio.com/, upzipped, dragged to my Applications directory, and tried to run it. After the initial "Verifying Visual Studio App" window ran, the dock icon bounced a few times then vanished and the app didn't load. Subsequent attempts yielded the same result. Anyone else experience this? Any known conflicts or dependencies for 10.8.5?

**Comment by chriskacerguis** [comment]
@DavidPereira69 Electron isn't really supported on 10.8 see https://github.com/Microsoft/vscode/issues/1058
