### ISSUE TITLE
Open Timeline View for a folder or workspace

### ISSUE THREAD

**Issue by michaelkremenetsky** [microsoft/vscode#215515]
Currently (at least to my knowledge) you can only open the Timeline View on an individual file. It would be quite helpful if you could right-click on a folder and have something like "Open Timeline View" and have it open the timeline for the whole directory.

This would be quite helpful for debugging to figure out when an issue started or if you accidentally deleted a bunch of files and wanted to restore them in bulk.

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode/issues/95332
