### ISSUE TITLE
Vs Code crashing

### ISSUE THREAD

**Issue by swapnilphalke03** [microsoft/vscode#215533]
Type: <b>Bug</b>

When trying to collapse a certain code, the vs code crashes and gets closed.

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:43.666Z)
OS version: Linux x64 5.15.0-107-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2507)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|9, 6, 3|
|Memory (System)|15.50GB (9.24GB free)|
|Process Argv|--force-user-env --no-sandbox --use-gl=angle --use-angle=swiftshader --crash-reporter-id 56579e10-585e-4699-83f9-e66ff1106bd6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.1.0
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
vscode-docker|ms-|1.29.1
remote-containers|ms-|0.369.0
vscode-react-native|msj|1.13.0
sonarlint-vscode|Son|4.6.0
autoimport|ste|1.5.4
chat-gpt|zha|1.7.9
vscode-react|zha|0.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
newcmakeconfigv2:31071590

```

</details>

**Comment by Luise8** [comment]
I'm getting this too

**Comment by deepak1556** [comment]
Can you attach the crash dumps following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

**Comment by gitdingus** [comment]
> Can you attach the crash dumps following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

I'm also having problems with the 1.90.1 crashing. It happens intermittently when collapsing/expanding code but also seems to be happening randomly when vscode gets focus back from other programs. I followed the steps to create a crash report but there are no .dmp files generated. Just a few empty directories, a client_id file, and settings.dat

I was also effected by 1.90.0 crashing on startup and had to revert to an earlier version.

**Comment by deepak1556** [comment]
Can you try the build from https://github.com/microsoft/vscode/issues/212494#issuecomment-2168893148 and confirm if the crash persists.

>  I followed the steps to create a crash report but there are no .dmp files generated. Just a few empty directories, a client_id file, and settings.dat

@gitdingus it might not be a crash in your case, if the issue persists in the linked build attach the output of `code --verbose`

**Comment by gitdingus** [comment]
> @gitdingus it might not be a crash in your case, if the issue persists in the linked build attach the output of `code --verbose`

Running it with the verbose flag allowed me to find where it was dumping the crash reports. The attached archive has crash reports from Friday as well as a fresh one from today. 

[vscode-crash.tar.gz](https://github.com/user-attachments/files/15873850/vscode-crash.tar.gz)
