### ISSUE TITLE
aparece un mensaje contiuno y se cierra y vuelve aparecer

### ISSUE THREAD

**Issue by oscarvh** [Microsoft/vscode#21554]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-npm|fknop|3.3.0|
|icon-fonts|idleberg|1.6.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Please file this issue in english and provide steps to reproduce

**Comment by isidorn** [comment]
Closing until more details are provided
