### ISSUE TITLE
Allow profiles to be window specific

### ISSUE THREAD

**Issue by Nathan-Furnal** [microsoft/vscode#215524]
Right now, when I open two different VSCode windows, if I switch to a profile in one window, it affects the other window and its profile changes as well. I would like to be able to have two different windows with different profiles. For example, I'd like to work on the same project but have one Python profile for the backend in one window and one Vue+TS profile in the other window, for the frontend. 

I'm open to a solution with workspaces if it's an alternative but I don't really see it documented anywhere.

Current VSCode version:

```
1.90.1
611f9bfce64f25108829dd295f54a6894e87339d
arm64
```

Thanks

**Comment by sandy081** [comment]
You can have two different profiles for two different windows and it should work. Can you please share a gif showing that it is not working for you?

Regarding opening same folder in multiple windows - we do not support this scenario.

**Comment by Nathan-Furnal** [comment]
Hi,

Yeah in the case of the monorepo I would've liked to be able to open the same project/folder in two different windows but with different profiles. Isn't there a workaround?

**Comment by sandy081** [comment]
> I would've liked to be able to open the same project/folder in two different windows

You can use multi folder workspace as an alternative

**Comment by Nathan-Furnal** [comment]
@sandy081 

Any chance that setting up the profiles in multi-root workspaces would be possible like this? 

```json
{
	"folders": [
		{
			"name": "main",
			"path": "."
		},
		{
			"name": "backend",
			"path": "backend",
			"profile": "Python"
		},
		{
			"name": "frontend",
			"path": "frontend", 
			"profile": "Vue"
		}
	],
	"settings": {}
}
```

**Comment by sandy081** [comment]
Unfortunately not. You can have only one profile associated per workspace.

**Comment by Nathan-Furnal** [comment]
That's too bad, thx for the answers!
