### ISSUE TITLE
Allow configuring rulers separately for notebook editors

### ISSUE THREAD

**Issue by rehmsen** [microsoft/vscode#215514]
VSCode supports configuring editor rulers, globally or for a language, using the "editor.rulers" preference. In our case we have style guides that prescribe certain line lengths for regular Python files, but they don't apply to Python cells inside notebooks, so we would like to be able to turn off rulers only in notebook editors, but not for all Python files. 

Is that already possible somehow, or could this be added?

**Comment by rebornix** [comment]
@rehmsen this can be archived via 

```
"notebook.editorOptionsCustomizations": {
        "editor.rulers": [
            80
        ]
    }
```
