### ISSUE TITLE
'${workspaceFolder}' is NOT working in the env field of tasks.json

### ISSUE THREAD

**Issue by ypli-chn** [microsoft/vscode#215518]
I want to customize a task using tasks.json and pass in an environment variable in the task, but ${workspaceFolder} doesn't seem to be expanded.
```
{
  "tasks": [
  {
    "env": {
      "EXEC_PATH": "${workspaceFolder}/bin/xxx"  // not work
    },
    // xxx
}
```

**Comment by meganrogge** [comment]
closing as this works for me 

<img width="660" alt="Image" src="https://github.com/user-attachments/assets/685d2371-6aa8-42da-8dd2-6b477d40b093" />
