### ISSUE TITLE
VS code does not work smoothly

### ISSUE THREAD

**Issue by Sh0g0-1758** [microsoft/vscode#215562]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.1
- OS Version: Ubuntu 24.04

Steps to Reproduce:

1. Open Vs code
2. Hover over files. It feels super slow and buggy.

**Comment by Sh0g0-1758** [comment]
For now I have reverted to a previous release using `sudo snap revert code`

**Comment by noahajohn** [comment]
I believe this is related:  https://github.com/microsoft/vscode/issues/215546.

As you discovered, reverting VS Code to 1.90.0 appears to be workaround.
