### ISSUE TITLE
Linux: vscode can't be display correct

### ISSUE THREAD

**Issue by lyguodong** [Microsoft/vscode#21555]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.8.0-39-generic
- Extensions:

|Extension|Author|Version|
|none|---||

---

Steps to Reproduce:

1.install the vscode on ubuntu 16.4
2.open, but not a word can be display, it just black. and the vscode windows always on the top, can't be closed.
3. I also the latest version: code_1.9.1-1486597190_amd64.deb version,  but it just as the same.

**Comment by bpasero** [comment]
Try running `code --disable-gpu` to workaround.

**Comment by bpasero** [comment]
Since this issue is rather old, I am closing this and ask anyone to open a new issue if this is still happening.
