### ISSUE TITLE
when i rename the "const name = ref('')" in vue3, it change other files, its wrong

### ISSUE THREAD

**Issue by lincolnkjy** [microsoft/vscode#215511]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

in vue3, i rename 'name' of  'const name = ref('--')', but it changed other files, i only want change this file.
follow is rename preview
![image](https://github.com/microsoft/vscode/assets/45555405/7a0bb6ee-af42-445e-b59d-b44d6c26b1d6)

**Comment by mjbvz** [comment]
Vue support is provided by extensions. Please file an issue against them
