### ISSUE TITLE
'Open recent' list should be longer

### ISSUE THREAD

**Issue by boris-ilijic** [Microsoft/vscode#21551]
- VSCode Version: 1.9.1
- OS Version: Windows 10

Steps to Reproduce:

1. Choose: File -> Open recent
2. Open recent list is shown: 10 recent files & 10 recent folders.

If would be great if this list is longer or even better configurable. E.g. like it is in VS: "XX items shown in recently used list".
The same feature can be applied to the Welcome screen's Recent list.

**Comment by matheusrocha89** [comment]
@boris-ilijic I am not sure if the recent list has a limit if you use the keyboard shortcut, did you try? On mac it's `Ctrl+R`. Or you can open the command palette and search for `File: Open Recent`.

**Comment by bpasero** [comment]
Yes, you can get the full contents (up to 100 folders and files) from the "Open Recent..." command.

**Comment by boris-ilijic** [comment]
Thanks!
