### ISSUE TITLE
Editor is very sluggish on 1.90.1

### ISSUE THREAD

**Issue by upsuper** [microsoft/vscode#215539]
Type: <b>Performance Issue</b>

General editing is very sluggish. There is no step needed to reproduce the issue other than normal editing, e.g. scrolling the editor, clicking different location in the code, using keyboard to move the cursor. It is noticably slow.

I have also tried to revert to 1.90.0, and the issue is gone, so it's likely a regression introduced in 1.90.1.

Also I tried to record a profile, but when I try to save the profile to file, vscode crashes and exits. I can't save it. I have briefly looked through the profile, and I can see there are a lot of frames dropped, but there is no long task shown in the profile. Long frames appear and frames get dropped in spite of majority of time being shown as idle. However, in the system monitor, I can see GPU processes keep taking a significant amount of CPU, while the profile shows GPU tasks to take very little time.

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:43.666Z)
OS version: Linux x64 6.8.0-31-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 1899)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|62.71GB (51.88GB free)|
|Process Argv|--force-user-env --no-sandbox --use-gl=angle --use-angle=swiftshader --crash-reporter-id 6c96f9ab-fe61-4358-8123-50e787b690e9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   128	119886	code main
    0	     0	119888	   zygote
    0	     0	119889	   zygote
    0	   257	119974	window [1] (presenter.ts - app - Visual Studio Code)
    0	    64	121585	window [2] (Issue Reporter)
    0	    64	119923	   utility-network-service
    0	    64	120071	shared-process
    0	     0	121635	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	121636	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    64	120072	fileWatcher [1]
    0	   128	120474	extensionHost [1]
    0	    64	120499	     electron-nodejs (tsserver.js )
    0	    64	120500	     electron-nodejs (tsserver.js )
    0	    64	120577	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    64	120515	     electron-nodejs (server.js )
    0	   193	120516	     /home/upsuper/.cargo/bin/deno lsp
    0	    64	120690	     electron-nodejs (eslintServer.js )
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (presenter.ts - app - Visual Studio Code)
|    Folder (app): 103 files
|      File types: ts(42) tsx(15) css(9) json(6) lock(2) editorconfig(1)
|                  env(1) nvmrc(1) yaml(1) cjs(1)
|      Conf files: launch.json(1) settings.json(1) package.json(1)
|                  tsconfig.json(1)
|      Launch Configs: node;
```

</details>
<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-modules|cli|0.5.1
vscode-eslint|dba|2.4.4
vscode-deno|den|3.37.1
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|10.4.0
vscode-firefox-debug|fir|2.9.10
vscode-clangd|llv|0.1.28
smalise|Loy|0.0.12
hg|mrc|1.9.0
vscode-docker|ms-|1.29.1
remote-containers|ms-|0.369.0
idl|myt|0.3.1
autotrim|Nat|1.0.6
java|red|1.31.0
rust-analyzer|rus|0.3.1995
apklab|Sur|1.7.0
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0
vim|vsc|1.27.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870

```

</details>

**Comment by upsuper** [comment]
While I can't save the profile, this is a screenshot of the profile. As can be seen, there are a lot of frames dropped can be seen in the Frames row being very red, while the vast majority of time is marked idle, and the GPU tasks are also reasonably short.

![Screenshot from 2024-06-14 23-13-04](https://github.com/microsoft/vscode/assets/333750/87b41be1-a5fb-450e-9271-ecac337123bd)

**Comment by MrIsak** [comment]
Same.
When updating from snap rev 159 to 161 the gui is horrible to work with. Reverted to rev 159, and it all works like a sharm again.
`snap revert code --revision 159`

**Comment by orbtz** [comment]
The very same was happening to me and my colleagues.
As a temporary solution, I followed [this](https://stackoverflow.com/a/58762168). Basically:
- Open the Command Palette (Ctrl+Shift+P).
- Run `Preferences: Configure Runtime Arguments`
- Add `"disable-hardware-acceleration": true`
- Restart VS Code.

**Comment by deepak1556** [comment]
This is a side-effect of the workaround we added for https://github.com/microsoft/vscode/issues/212494

Please refer to https://github.com/microsoft/vscode/issues/212494#issuecomment-2168072242 for workarounds and follow the issue for updates.

**Comment by pauloimon** [comment]
Thanks, @orbtz! Worked for me.

**Comment by mckirk** [comment]
Thanks @orbtz! This was driving me insane all day and I was wondering what had changed. What made it especially weird was that it seemed fine _sometimes_, in some VSCode instances, which originally made me suspect it was related to a specific folder/project. But disabling HW acceleration fixed it completely, so it seems that was causing the issue.

**Comment by alimousavi71** [comment]
> The very same was happening to me and my colleagues. As a temporary solution, I followed [this](https://stackoverflow.com/a/58762168). Basically:
> 
>     * Open the Command Palette (Ctrl+Shift+P).
> 
>     * Run `Preferences: Configure Runtime Arguments`
> 
>     * Add `"disable-hardware-acceleration": true`
> 
>     * Restart VS Code.

Great

**Comment by jkergal** [comment]
> I also solved it by disabling hardware acceleration. However, today VS Code crashed on start no matter what I tried. I reverted to 1.90.1, still crashing. Only after removing the line about disabling hardware acceleration in ~/.vscode/argv.json, did it start again.

same issue here, disabling hardware acceleration make my vs code crash on Ubuntu 22.04.4 LTS (snap package)

**Comment by nicosilverx** [comment]
> I also solved it by disabling hardware acceleration. However, today VS Code crashed on start no matter what I tried. I reverted to 1.90.1, still crashing. Only after removing the line about disabling hardware acceleration in ~/.vscode/argv.json, did it start again.

I was able to launch VS Code by starting it with the `--in-process-gpu` argument.
