### ISSUE TITLE
Install has extra directory in path

### ISSUE THREAD

**Issue by zeilsell-user1** [microsoft/vscode#215610]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.90.1 (user setup)
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:01:24.262Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1.  rebooted PC
2.  started WSL (ubuntu 22.04)
3. cd to work directory
4. code .

failed with 

$>~/InternalAdminServer$ code .
Updating VS Code Server to version 611f9bfce64f25108829dd295f54a6894e87339d
Removing previous installation...
Installing VS Code Server for Linux legacy-x64 (611f9bfce64f25108829dd295f54a6894e87339d)
Downloading: 100%
Unpacking: 100%
ERROR: Unpacking failed: Files expected: 1689, is 1690
/mnt/c/Users/richa/.vscode/extensions/ms-vscode-remote.remote-wsl-0.88.2/scripts/wslCode.sh: 68: /home/richard/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/bin/remote-cli/code: not found

$>cd /home/richard/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d
$>ls -la
total 12
drwxr-xr-x 3 richard richard 4096 Jun 15 09:46 .
drwxr-xr-x 3 richard richard 4096 Jun 15 09:46 ..
drwxr-xr-x 6 richard richard 4096 Jun 15 09:46 611f9bfce64f25108829dd295f54a6894e87339d-1718441199

As a workaround I created symlinks

$> ln -s 611f9bfce64f25108829dd295f54a6894e87339d-1718441199/LICENSSE LICENSE
$> ln -s 611f9bfce64f25108829dd295f54a6894e87339d-1718441199/bin bin
$> ln -s 611f9bfce64f25108829dd295f54a6894e87339d-1718441199/extensions extensions
$> ln -s 611f9bfce64f25108829dd295f54a6894e87339d-1718441199/node node
$> ln -s 611f9bfce64f25108829dd295f54a6894e87339d-1718441199/node_modules node_modules
$> ln -s 611f9bfce64f25108829dd295f54a6894e87339d-1718441199/out out
$> ln -s 611f9bfce64f25108829dd295f54a6894e87339d-1718441199/package.json package.json
$> ln -s 611f9bfce64f25108829dd295f54a6894e87339d-1718441199/product.json product.json
$> code .

This started vs code. There was a new warning box when I opened the second instance of vscode

**Comment by rzhao271** [comment]
Hi @zeilsell-user1, apologies for getting to your issue so late. Are you still seeing the issue when using VS Code 1.96 or newer?
