### ISSUE TITLE
React Native packager still running in the background when debugger exists

### ISSUE THREAD

**Issue by jpokrzyk** [Microsoft/vscode#21569]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.2|
|beautify|HookyQR|0.8.8|
|alignment|annsk|0.3.0|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|prettier-vscode|esbenp|0.9.0|
|git-project-manager|felipecaputo|1.0.1|
|auto-close-tag|formulahendry|0.3.9|
|auto-rename-tag|formulahendry|0.0.11|
|debugger-for-chrome|msjsdiag|2.5.5|
|vscode-react-native|vsmobile|0.3.1|

---

When I debug a react native application in vs code the webpack packager is still running in the background even though I stop debugging. I have to completely quit the VS code window to kill it.

Steps to Reproduce:

1. Create a react native project
2. Debug ios react native app with the following launch config
3. Stop the vs code react native debugger by hitting the red box stop button
4. Keep the window open
4. Run `react-native run-ios` from a terminal. Normally this would spawn another terminal. But in this case it won't because the webpack packager is running hidden in vs code.

If you're not familiar with react native. It spawns a separate terminal for the web pack packager. In VS Code that's still running somewhere in the background even though I have stopped debugging.

Not a huge deal. Just thought I would mention it. Thanks.

**Comment by isidorn** [comment]
Thanks for filling this issue, however it is caused by the vsocde-react-native extension. As that extension should kill the webpack packager once vscode sends the `disconnect` request.
Can you please file an issue here https://github.com/Microsoft/vscode-react-native
