### ISSUE TITLE
Ability to navigate between changed sections of a file according to git

### ISSUE THREAD

**Issue by xconverge** [Microsoft/vscode#21561]
It would be nice if there was a command and keyboard shortcut to navigate to the next and previous changed area of a file. This would essentially jump between green/blue areas in the gutter representing the git diff.

If you have a huge file where you only changed a few things and random places, this would let you get back to where the action is easily.

**Comment by xconverge** [comment]
@joaomoreno any preference on how this would be done if I wanted to tackle it?

**Comment by dacap** [comment]
Don't `workbench.action.compareEditor.nextChange` and `workbench.action.compareEditor.previousChange` commands already do this?

**Comment by xconverge** [comment]
looks like I am a dupe of #7717

**Comment by joaomoreno** [comment]
Thanks, dupe.
