### ISSUE TITLE
Watch expressions and function breakpoints input box left / right navigation broken

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#21560]
1. Have a watch expression
2. Add another watch expression, left / right navigation is not working while in the input field

Also happens for function breakpoints.
This is a regressoin. Not sure about candidate since it is not critical imho.

@bpasero why is this working nicely in all other trees (exporer, variables) and not here

**Comment by bpasero** [comment]
@isidorn the difference is that in the explorer when the input box opens the tree is being set into highlight mode (setHighlight), I suggest to do the same for debug to be consistent and not run into this bug.

**Comment by isidorn** [comment]
@bpasero for some weird reason the fix I pushed seems to fix it.
If i set the highlight to the exact element like I should than the tree gets into a weird highlight state (everything is blurred - pic attached). it is probably some timing issue, the pushed fix seems to get the job done so opted for that instread of continuing the investigation.

![screen shot 2017-03-01 at 11 42 09](https://cloud.githubusercontent.com/assets/1926584/23456538/2506bc30-fe74-11e6-8b6b-2ab5dd97393a.png)

**Comment by bpasero** [comment]
@isidorn after the input box closes you have to call `clearHighlight` to get out of this mode! See https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L332

**Comment by isidorn** [comment]
@bpasero I know I am doing that, this is something else (while the input box is open). After the input box closes all is good
