### ISSUE TITLE
SO SLOW THAT I CANNOT WORK AT ALL ON UBUNTU22

### ISSUE THREAD

**Issue by lordspace** [microsoft/vscode#215670]
When I disable hardware acceleration VS Code crashes without an error right after opening the project. Process explorer crashes too.

Type: <b>Performance Issue</b>

THIS IS SUPER SLOW. FREAKING SLOW.
I HAVE 32GB OF RAM! AND 8 cores

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:43.666Z)
OS version: Linux x64 6.5.0-35-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 7, 6|
|Memory (System)|31.22GB (14.30GB free)|
|Process Argv|--force-user-env --no-sandbox --use-gl=angle --use-angle=swiftshader --crash-reporter-id da43ad9b-0e6c-4e1f-88e2-93f488251d25|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   160	 46798	code main
    0	    32	 46800	   zygote
    0	    32	 46801	   zygote
    0	   224	 46879	window [1] (pubspec.yaml - 14 Chat App - Visual Studio Code)
    0	    96	 52696	window [2] (Issue Reporter)
    0	    64	 46837	   utility-network-service
    0	   192	 46927	extensionHost [1]
    0	    64	 47027	     /home/qs/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart tooling-daemon --machine
    0	    64	 47029	     electron-nodejs (config.js )
    0	   735	 47036	     /home/qs/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.90.0
    0	    64	 47088	     /home/qs/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart devtools --machine --allow-embedding --dtd-uri ws://127.0.0.1:38335/YvXyOIm3nu2sR4fD
    0	    96	 46977	shared-process
    0	     0	 52710	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 52711	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    64	 46978	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (pubspec.yaml - 14 Chat App - Visual Studio Code)
|    Folder (14 Chat App): 216 files
|      File types: dart(56) json(15) lock(11) yaml(11) png(10)
|                  flutter-plugins(9) flutter-plugins-dependencies(9) md(1)
|                  firebaserc(1) gitignore(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.90.0
flutter|Dar|3.90.0
copilot|Git|1.203.0
copilot-chat|Git|0.16.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
2f103344:31071589

```

</details>

**Comment by kumarp149** [comment]
I too am facing the same issue with vscode 1,90.1 in Ubuntu 22.04

**Comment by shelvesdragon** [comment]
This is likely caused by the temporary fix in version 1.90.1 on the snap package that switched the OpenGL backend to software emulation in order to prevent the crashes reported with version 1.90.0 in #212494 . If it is related, your options for now are mentioned in this comment: https://github.com/microsoft/vscode/issues/212494#issuecomment-2168072242
Hope this helps!

**Comment by lordspace** [comment]
I managed to find a fix and wrote about it: https://wpsandbox.net/development/fix-visual-studio-code-crashes-ubuntu-p1139

```code --in-process-gpu .```

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/212494, please follow the issue for updates.
