### ISSUE TITLE
material icon theme  does not work :( 

### ISSUE THREAD

**Issue by strix25** [Microsoft/vscode#21568]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|material-icon-theme|PKief|1.3.4|

---

Steps to Reproduce:

1.
2.

**Comment by Daylien** [comment]
Did you select the icon theme ? If not go to File > Preferences > File icon theme > now choose your icon theme.

Hope I could help you.

**Comment by strix25** [comment]
tnx
