### ISSUE TITLE
Save Menu Item is disabled - Update 1.90.1 made it worse!

### ISSUE THREAD

**Issue by promethyttrium** [microsoft/vscode#215615]
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.90.1 (system setup)
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:01:24.262Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
```

Steps to Reproduce:

1. Open code in editor, make changes.
2. Alt - F - S, menu sticks around because Save menu item is disabled despite file being changed
3. Grumble/shake fist, Ctrl-S -- file saved. 
4. Switch editor tabs within the same group and switch back, Alt-F-S works now
5. Make more changes, switch file groups to look at other code, switch back
6. Alt-F-S doesn't work anymore, grumble/shake fist, Switch editor tabs within the same group to get Save reenabled.
7. Grumble more and write up bug report on vscode.

**Comment by promethyttrium** [comment]
Made edits to the steps to repro -- apparently switching editor tabs within the same editor group reenables the menu item. Switch to a different group definitely disables it.

**Comment by promethyttrium** [comment]
Where do I get the "system setup" for a previous release? the Update page download link only points to the "User setup"

**Comment by promethyttrium** [comment]
Nevermind, found it, wasn't easy to find... thanks a lot!

For others in my predicament: 
(System Setup because User Setup stupidly disabled updates which might have been a good thing when they put out a buggy release with a bad regression) 

https://update.code.visualstudio.com/1.89.1/win32-x64/stable

**Comment by benibenj** [comment]
/duplicate #214496
The bug is fixed in the newest insiders release

**Comment by benibenj** [comment]
June update in 2 weeks
