### ISSUE TITLE
formatOnPaste: true pastes the rest of the line in SCSS files

### ISSUE THREAD

**Issue by kurtnovack** [Microsoft/vscode#21562]
- VSCode Version: 1.9.1
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. set "editor.formatOnPaste" to true in you settings.json file
2. copy & paste any css value to another attribute in any scss file:

(ignore the linter errors)

#### copy
![screen shot 2017-02-28 at 10 56 58 am](https://cloud.githubusercontent.com/assets/4550817/23412763/a86e4122-fda4-11e6-85f0-df27f7b7f2f7.png)

#### paste
![screen shot 2017-02-28 at 10 56 36 am](https://cloud.githubusercontent.com/assets/4550817/23412771/aea4af54-fda4-11e6-898f-ac6c9c1ec7a8.png)

**Comment by hannupekka** [comment]
I've had similar experiences:
![y_u_do_dis_vscode](https://cloud.githubusercontent.com/assets/4472477/23498335/00c888b4-ff30-11e6-8ac4-a57aedf6a57f.gif)

When I pasted "foobar" inside that console.log, formatting broke.

**Comment by alexej-d** [comment]
Having the same issue in v1.10 even without `editor.formatOnPaste` set to `true`…

**Comment by sbubaron** [comment]
having same issue here, on scss and json files as well.  Turning editor.formatOnPaste to false seems to resolve.

**Comment by rebornix** [comment]
It seems to be related to css formatter, assign to @aeschli first to help.

**Comment by aeschli** [comment]
We don't have a CSS formatter built-in VSCode.
There are various formatters available as extensions, such as https://marketplace.visualstudio.com/items?itemName=aeschli.vscode-css-formatter.

I realize that that formatter doesn't implement range format correctly, instead it formats the whole document, causing the bug you see.
I created https://github.com/aeschli/vscode-css-formatter/issues/7

I suggest to use a different formatter in the meantime.
