### ISSUE TITLE
Collapse all children in explorer tree?

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#21566]
- VSCode Version: 1.10.0
- OS Version: 10.12.3

It would be most convenient if I could right-click a folder in the explorer tree and choose "collapse all children".  

Many times, over the course of the day, I have opened many folders and subfolders.  This makes it difficult to focus/locate what I am currently working on.  I need to close each folder and its parent(s) in turn.

MacOS' Finder has the ability to collapse a folder and all child folders by option-click on the disclosure
 triangle, as in

![feb-28-2017 12-34-44](https://cloud.githubusercontent.com/assets/835148/23416821/6a1bc184-fdb2-11e6-8135-7e32482d95bb.gif)

As you can see when I re-open it, the child folder had been closed along with its parent.

I would love to be able to do this with my main "app" folder, and then open it and open the child module I need to actually work on.

**Comment by bpasero** [comment]
Is https://github.com/Microsoft/vscode/issues/9456
