### ISSUE TITLE
Red bar spanning the editor where my cursor is

### ISSUE THREAD

**Issue by noedlm** [Microsoft/vscode#21575]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-toothpaste|aalaap|0.0.1|
|vscode-svgviewer|cssho|1.3.1|
|python|donjayamanne|0.5.8|
|Theme-Blackboard|gerane|0.0.2|
|Theme-Sunburst|gerane|0.0.2|
|Theme-Zeus-Sublime-Text|gerane|0.0.2|
|rest-client|humao|0.12.3|
|theme-chrome-devtools-dark|ivanzusko|0.0.1|
|vscode-icons|robertohuertasm|7.3.0|
|theme-obsidian|rprouse|0.2.0|
|ColdFusion|SketchPunk|0.0.1|
|Theme-Sunburst Univar|gerane|0.0.2|

---

Steps to Reproduce:

1. red bar is consistently showing up on all files in the editor
![image](https://cloud.githubusercontent.com/assets/627454/23436261/7fe58a96-fdcf-11e6-94dc-6f8220d5ba38.png)

**Comment by isidorn** [comment]
Please change the theme you are using by 
F1 > Preferences Color Theme

If that does not help it then disable some of the extensions you are using it is probably caused by them.
