### ISSUE TITLE
[css] Propose list of available values after property

### ISSUE THREAD

**Issue by ArkhipovK** [Microsoft/vscode#21573]
Is it possiable to propose list of available values after properties, like in atom and modern browsers?
For example: i typed text-align: [here it should be a list of values like: right, center, left and so on]

**Comment by isemantics** [comment]
This already works? I can open vscode, open a new CSS file, type  html { text-align: } and press ctrl-space after the colon and it shows me the available values. I have disabled nearly all extensions, so I guess it is not some extension doing this for me.

**Comment by aeschli** [comment]
Yes, there CSS property code completions. If i doesn't work for you, please file an issue with a code snippet that reproduces the issue.

**Comment by ArkhipovK** [comment]
Yes, sorry. I'd been tested the sass file, thats why did't noticed. The real problem is that proposed list is arranged in alphabetical order insted of property type order. But this is the subject of another issue.
![default](https://cloud.githubusercontent.com/assets/9945452/23502183/b8644472-ff58-11e6-85dd-7023e3cf9ed2.png)
