### ISSUE TITLE
Breakpoints set in promises in .ts files are not hit

### ISSUE THREAD

**Issue by briancr-ms** [Microsoft/vscode#2157]
A breakpoint set in a .ts file within a promise (in the then promise function) is never hit. Setting the same breakpoint in the generated .js file works.

VS Code on Windows:
Version 0.10.6
Commit a80232bbcfe8a5cdad1ebc98638673d9dcb02458
Date 2015-12-19T11:34:58.895Z
Shell 0.34.5
Renderer 45.0.2454.85
Node 4.1.1

**Comment by weinand** [comment]
Could not reproduce in VS Code 1.3.0 and node 5.11 or 6.2.2
