### ISSUE TITLE
Css mso-height-rule:

### ISSUE THREAD

**Issue by jhonrsalcedo** [Microsoft/vscode#21572]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-css-formatter|aeschli|0.0.2|
|vscode-color|anseki|0.2.3|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.6|
|vscode-html-css|ecmel|0.0.33|
|tslint|eg2|0.8.1|
|beautify|HookyQR|0.8.8|
|sublime-babel-vscode|joshpeng|0.2.4|
|format-php|Kasik96|1.1.2|
|sass-indented|robinbentley|1.3.0|
|guides|spywhere|0.6.1|
|stylint|vtfn|0.0.2|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Please provide more details.
What is the expected behavior, what you are seeing and what are the steps to reproduce?

**Comment by isidorn** [comment]
Closing until more details are provided
