### ISSUE TITLE
Debian package `postinst` interferes with DEB822 repo style

### ISSUE THREAD

**Issue by papamoose** [microsoft/vscode#215744]
Steps to Reproduce:
1. Install previous version of vscode
2. Remove /etc/apt/sources.list.d/vscode.list
3. Create /etc/apt/sources.list.d/vscode.sources
4. Upgrade vscode and see that now vscode.list and vscode.sources exist
5. apt is now broken

I don't think the `postinst` script should be responsible for managing vscode.list. 

Another option would be to support DEB822 when it is detected... or at least not interfere with it.

**Comment by rzhao271** [comment]
Duplicate https://github.com/microsoft/vscode/issues/22145
