### ISSUE TITLE
The JS/TS language service crashed. TVisualStudioExptTeam.vscodeintellicode, VisualStudioExptTeam.vscodeintellicode, Vue.volar.

### ISSUE THREAD

**Issue by kobbiman** [microsoft/vscode#215750]
Type: <b>Bug</b>

The JS/TS language service crashed. This may be caused by a plugin contributed by one of these extensions: VisualStudioExptTeam.vscodeintellicode, VisualStudioExptTeam.vscodeintellicode, Vue.volar. Please try disabling these extensions before filing an issue against VS Code.

VS Code version: Code - Insiders 1.91.0-insider (Universal) (51d598183ea632c658c34e0a11da5706192a1b69, 2024-06-12T05:51:34.591Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|37, 15, 6|
|Memory (System)|64.00GB (16.17GB free)|
|Process Argv|--crash-reporter-id 3cabbca4-4e05-4301-8cdc-40414ea6a1d4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (127)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
vscode-sql-formatter|adp|1.4.4
react-hooks-snippets|AlD|1.2.0
vscode-sqlite|ale|0.14.1
tailwindcss-extension-pack|and|1.1.4
ng-template|Ang|18.0.0
vscode-apollo|apo|1.20.0
atlascode|atl|3.0.10
tailwind-docs|aus|2.1.0
react-hooks|AYa|1.1.0
azurite|Azu|3.30.0
markdown-extension-pack|bat|0.7.0
env-vscode|Ber|0.1.1
ts-reveal-types|bet|1.0.4
emojisense|bie|0.10.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-image-size|bie|0.0.4
markdown-preview-github-styles|bie|2.0.4
prettier-toml|bod|0.1.0
vscode-tailwindcss|bra|0.10.5
graphql-codegen-vscode|cap|1.1.2
flylang|car|0.1.1
compulim-vscode-closetag|Com|1.2.0
language-postcss|cpy|1.1.0
jsdoc-generator|cry|2.1.0
excel-to-markdown-table|csh|1.3.0
postcss|css|1.0.9
dbclient-jdbc|cwe|1.3.5
vscode-postgresql-client2|cwe|7.4.8
aws-cloudformation-yaml|Dan|0.2.2
markdown-table-prettify|dar|3.6.0
dart-code|Dar|3.90.0
flutter|Dar|3.90.0
vscode-eslint|dba|2.4.4
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
vscode-docker-syntax|dun|0.1.5
gitlens|eam|15.1.0
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.105
prettier-vscode|esb|10.4.0
vscode-jest-runner|fir|0.4.73
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
docker-explorer|for|0.1.7
copilot|Git|1.201.0
copilot-chat|Git|0.16.1
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.88.1
mdmath|goe|2.7.4
vscode-graphql|Gra|0.11.0
vscode-graphql-execution|Gra|0.2.6
vscode-graphql-syntax|Gra|1.3.6
terraform|has|2.30.2
ReactCodeSnippets|haz|1.2.1
headwind|hey|1.7.0
fish-redux-template|hua|0.0.7
githd|hui|2.3.5
toml-formatter|ice|0.0.3
vscode-react-typescript|inf|1.3.1
path-autocomplete|ion|1.25.0
vscode-env|Iro|0.1.0
jenkinsfile-support|ivo|1.1.0
vscode-pnpm|Jac|0.0.3
svg|joc|1.5.3
angular-essentials|joh|17.0.0
Angular2|joh|16.0.1
vscode-peacock|joh|4.2.2
graphql-for-vscode|kum|1.15.3
tailwind-sass-syntax|mac|1.3.0
vscode-dbml|mat|0.3.5
ts-error-translator|mat|0.10.1
markdown-shortcuts|mdi|0.12.0
vscode-github-actions|me-|3.0.1
git-graph|mhu|1.30.0
gitignore|mic|1.0.1
document|min|2.2.2
compare-folders|mos|0.24.3
vscode-azurefunctions|ms-|1.15.0
vscode-azureresourcegroups|ms-|0.9.1
vscode-docker|ms-|1.29.1
csdevkit|ms-|1.7.25
csharp|ms-|2.33.17
vscode-dotnet-runtime|ms-|2.0.6
debugpy|ms-|2024.6.0
python|ms-|2024.8.0
vscode-pylance|ms-|2024.6.1
remote-containers|ms-|0.372.0
makefile-tools|ms-|0.9.10
vscode-typescript-next|ms-|5.6.20240612
vscode-react-native|msj|1.13.0
sqltools|mtx|0.28.3
sqltools-driver-sqlite|mtx|0.5.1
color-highlight|nau|2.8.0
vscode-groovy-lint|Nic|3.3.1
env-cmd-file-syntax|Nix|0.3.0
prettier-standard-vscode|num|1.0.2
material-icon-theme|PKi|5.4.1
prisma|Pri|5.15.0
typedoc-live-preview|psu|1.0.1
java|red|1.31.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.15.0
postcss|ric|2.0.0
markdown-preview-enhanced|shd|0.8.13
even-better-toml|tam|0.19.2
vscode-markdown-paste-image|tel|1.0.2
codegpt3|tim|1.1.2
type-doc-vscode|Tre|0.0.35
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0
vscode-icons|vsc|12.8.0
volar|Vue|2.0.10
gitblame|wad|11.0.1
ReactSnippets|xab|2.4.0
vscode-mdx-preview|xyc|0.3.3
pretty-ts-errors|Yoa|0.5.4
aidoc-complete|yoo|0.0.1
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.6.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
showvideot:31016890
chatpanelt:31014475
945dj816:31013170
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupyter:31046869
2f103344:31071589
legacy_priority:31057981
fa862199:31048878
nativerepl2:31071685
refactort:31067743

```

</details>

**Comment by mjbvz** [comment]
The issue tells you the likely cause and what to try:

> This may be caused by a plugin contributed by one of these extensions: VisualStudioExptTeam.vscodeintellicode, VisualStudioExptTeam.vscodeintellicode, Vue.volar. Please try disabling these extensions before filing an issue against VS Code.

Please follow those suggestions first
