### ISSUE TITLE
Wordrap toggle not working correctly after the the most recent update

### ISSUE THREAD

**Issue by kakins** [Microsoft/vscode#21574]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.0|
|mssql|ms-mssql|0.2.0|
|csharp|ms-vscode|1.5.3|
|java|redhat|0.0.9|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1.  Whenever I hit ALT+Z or select Toggle Wordwrap from the menu, it no longer turns off wordwrap.

**Comment by kakins** [comment]
I didn't realize there was a setting for editor.WrappingColumn.  When I incremented this value it formatted my document correctly, turning off word wrapping.  I'm not sure why incrementing this value allowed the wrapping to be toggled correctly.  It seems if I wanted to turn wrapping off it shouldn't be concerned about the WrappingColumn setting.  I had thought that there was a standard 'turn wrapping completely off' toggle state, was I mistaken?

**Comment by alexandrudima** [comment]
@kakins In 1.10 we have overhauled the wrapping related settings and we've also changed the Toggle Word Wrap action. The release will be published in the following days, or you can use the insiders channel today.

Please see #21291 and #21262

**Comment by kakins** [comment]
Great, thanks!
