### ISSUE TITLE
Blurry default font on Mac with non-high-dpi display

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#21577]
- VSCode Version: Code - Insiders 1.10.0-insider (40fecfaa77f01672e8a147be71f6f7ccb9cf8a12, 2017-02-27T14:09:29.088Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Default (especially 'e' and 'a' are bad):
![screen shot 2017-02-28 at 2 28 10 pm](https://cloud.githubusercontent.com/assets/9205389/23437231/298c7afe-fdc2-11e6-9172-2ad6451dc6e9.png)

Font-size 14 helps, but is a little clunky:
![screen shot 2017-02-28 at 2 30 39 pm](https://cloud.githubusercontent.com/assets/9205389/23437314/84391250-fdc2-11e6-9432-16257ce54c88.png)

Fira Code, size 14:
![screen shot 2017-02-28 at 2 31 43 pm](https://cloud.githubusercontent.com/assets/9205389/23437357/a9fdf83e-fdc2-11e6-8c32-b1a015c66683.png)

Hack, size 14:
![screen shot 2017-02-28 at 2 35 07 pm](https://cloud.githubusercontent.com/assets/9205389/23437474/2c6c9514-fdc3-11e6-95d3-cdc5bd0123d7.png)

Fira Code, size 14, with ligatures (which Hack doesn't support):
![screen shot 2017-02-28 at 2 45 38 pm](https://cloud.githubusercontent.com/assets/9205389/23437952/c71ceda6-fdc4-11e6-95da-e99a06e43dde.png)

**Comment by alexandrudima** [comment]
@chrmarti From zooming in, it appears the font is rendered using subpixel antialising, which was in the past a main source of bluriness.

Possible related: #9152

Maybe you can try playing with `-webkit-font-smoothing: antialiased;` ? Does that make a difference for the better?

Specifically on the mac, there are other issues reporting that the text is rendered too thick. Perhaps you can also play with `editor.fontWeight` ?

**Comment by chrmarti** [comment]
Default:
![screen shot 2017-03-01 at 8 18 38 am](https://cloud.githubusercontent.com/assets/9205389/23469261/02438190-fe58-11e6-873e-7c27f385f8c4.png)

`-webkit-font-smoothing: antialiased;`
![screen shot 2017-03-01 at 8 19 20 am](https://cloud.githubusercontent.com/assets/9205389/23470487/610e0184-fe5b-11e6-87f7-cc4371a8dfda.png)

`-webkit-font-smoothing: antialiased; font-weight: bold;`
![screen shot 2017-03-01 at 8 20 05 am](https://cloud.githubusercontent.com/assets/9205389/23470532/772cb8e8-fe5b-11e6-9f3f-8ebda8069d3c.png)

**Comment by chrmarti** [comment]
@alexandrudima See the above. `antialiased` made it too light, `bold` counters that, but the result looks worse to my eye than the original.

**Comment by alexandrudima** [comment]
@chrmarti I agree, all screenshots look bad.

Perhaps some more CSS tweaks if you'd like to try them out on your setup (I think you're using a mac connected to a non-retina display, right?).

Maybe if we find some of these to have a positive effect I can create an editor setting toggling them on/off:

### text-rendering
```
/* Keyword values */
text-rendering: auto;
text-rendering: optimizeSpeed;
text-rendering: optimizeLegibility;
text-rendering: geometricPrecision;
```

### -webkit-text-stroke
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke

### -webkit-font-smoothing: subpixel-antialiased

**Comment by chrmarti** [comment]
I can't get `text-rendering` nor `subpixel-antialiased` to make a difference. Tried stroke width with `antialiased`:

Stroke width 0.5px:
![screen shot 2017-03-09 at 4 02 10 pm](https://cloud.githubusercontent.com/assets/9205389/23776323/7fe24ae2-04e2-11e7-93cf-77862b669fab.png)

Stroke width 1px:
![screen shot 2017-03-09 at 4 02 56 pm](https://cloud.githubusercontent.com/assets/9205389/23776355/a6aa7ee2-04e2-11e7-9d50-bd45c8c21b82.png)

Font smoothing antialiased, stroke width 0.5px:
![screen shot 2017-03-09 at 4 03 40 pm](https://cloud.githubusercontent.com/assets/9205389/23776369/c13fd7a2-04e2-11e7-88e3-dea6721f5fd3.png)

Font smoothing antialiased, stroke width 1px:
![screen shot 2017-03-09 at 4 04 00 pm](https://cloud.githubusercontent.com/assets/9205389/23776374/cd3c2df8-04e2-11e7-96db-a56a05e8c0cc.png)

Using stroke doesn't seem to work well here. Let me know if there are other combinations I should try.

**Comment by alexandrudima** [comment]
I'm sorry, there's nothing more I can think of. Now I'm just fishing [in here](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/css/resolver/FontBuilder.cpp):

Here are the last CSS knobs I could find in that code that you haven't been through yet (IMHO unlikely they would improve things):
* [`font-size-adjust`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust)
* [`font-stretch`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch)
* [`font-kerning`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-kerning)

**Comment by bpasero** [comment]
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders

**Comment by chrmarti** [comment]
Doesn't look like it changed:

Before:
![screen shot 2017-03-01 at 8 18 38 am](https://cloud.githubusercontent.com/assets/9205389/23469261/02438190-fe58-11e6-873e-7c27f385f8c4.png)

After:
![screen shot 2017-04-11 at 8 17 37 am](https://cloud.githubusercontent.com/assets/9205389/24916563/59a58e04-1e8f-11e7-99ad-8a134f5d7556.png)

**Comment by infojasyrc** [comment]
@chrmarti is really easy to play with css changes without going to "Help > Toggle Developer Tools" in vsCode? are they permanent?

**Comment by chrmarti** [comment]
@infojasyrc I did not make any permanent changes to try this. Personally I'm using the Fira Code font with ligatures enabled and size 14. That looks good also on normal resolution displays, my concern here is more with the initial user experience.

**Comment by infojasyrc** [comment]
@chrmarti I think It will be great to have a less|sass|any css file to modify this globals settings for VSCode as atom has.

**Comment by chrmarti** [comment]
@infojasyrc That is tracked in #459.

**Comment by bpasero** [comment]
@chrmarti can this be closed?

**Comment by chrmarti** [comment]
Yes, not actionable.
