### ISSUE TITLE
VSCode does not hint or autocomplete event.target.parentNode;

### ISSUE THREAD

**Issue by linocatucci** [Microsoft/vscode#21570]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.8.8|
|jslint|ajhyndman|1.2.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.6|
|githistory|donjayamanne|0.1.5|
|auto-close-tag|formulahendry|0.3.9|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|vscode-icons|robertohuertasm|7.3.0|
|open-in-browser|techer|0.0.3|

---
Hello,

with some code in VSCode the autocomplete and hints are not working.

For instance with the following codeL
`console.log(event.target.parentNode); `
Visual studio code does not show the options when I type in `event.target.ParentNode` or with `event.target.
`
Can somebody help me?

cheers,
Lino

Steps to Reproduce:

1. type in console.log(event.target.p -> parentNode is expected
2.type in event.ta -> target is expected.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14374
