### ISSUE TITLE
Offer to open settings when php path not set / invalid

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#21581]
- VSCode Version: Code - Insiders 1.10.0-insider (40fecfaa77f01672e8a147be71f6f7ccb9cf8a12, 2017-02-27T14:09:29.088Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|autofilename|JerryHong|0.1.3|
|vscode-simple-icons|LaurentTreguier|0.10.1|
|vscode-docker|PeterJausovec|0.0.12|
|azure-cli|chrmarti|0.3.0|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.2.6|
|ghlink|dt|0.0.5|
|tslint|eg2|0.8.1|
|vscode-scss|mrmlnc|0.6.1|
|PowerShell|ms-vscode|0.9.0|
|cpptools|ms-vscode|0.10.1|
|debugger-for-chrome|msjsdiag|2.5.4|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.4.0|;

---

I think new users would be greatly helped with an Open Settings button as part of that message:

![screen shot 2017-02-28 at 3 59 13 pm](https://cloud.githubusercontent.com/assets/9205389/23440210/97390614-fdcf-11e6-8433-304e813ab12e.png)

**Comment by roblourens** [comment]
#8735
