### ISSUE TITLE
typescript language service died!

### ISSUE THREAD

**Issue by truthwzl** [Microsoft/vscode#21589]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|swagger-viewer|Arjun|1.3.0|
|vs-freemarker|dcortes92|0.0.4|
|Go|lukehoban|0.6.53|
|cpptools|ms-vscode|0.10.0|
|PowerShell|ms-vscode|0.9.0|
|proto|peterj|0.0.2|
|vscode-icons|robertohuertasm|7.3.0|
|jinja|wholroyd|0.0.7|
|vscode-proto3|zxh404|0.1.0|

---

Steps to Reproduce:

1.
2.

**Comment by truthwzl** [comment]
reinstall the visual code 1.9.1 ，the error no longer show!

**Comment by mjbvz** [comment]
@truthwzl This may be related to #20552. Try checking your antivirus settings. 360 antivirus specifically has been deleting our typescript files for some reason
