### ISSUE TITLE
Vscode cannot open external terminal debugging by setting the console

### ISSUE THREAD

**Issue by z-lizhao** [Microsoft/vscode#21585]
- VSCode Version:1.9.1
- System:window

I pass before launch. Json configuration externalConsole for 'true' open external terminal test, but not now.I set the console to "externalTerminal".What should I do

**Comment by isidorn** [comment]
Please set `"console": "externalTerminal"` in your 'launch.json' file.
If that does not work please paste your complete 'launch.json' file and we can investigate further.
