### ISSUE TITLE
Cannot find runtime 'node' on PATH.

### ISSUE THREAD

**Issue by Allenharveyiii** [Microsoft/vscode#21587]
**Version and Extention Information:**

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|hopscotch|idleberg|0.1.4|
|csharp|ms-vscode|1.7.0|

---

**Steps to Reproduce:**

- Open VS Code
- Create a "Hello World!" JavaScript Program.
- Run JS program in VS Code Debugger.

**Code Snippets:**
- helloworld.js
`console.log('Hello World.');`

- launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/helloworld.js",
            "cwd": "${workspaceRoot}"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "port": 5858
        }
    ]
}
```

**Self troubleshooting:**
- I tried restarting my PC.
- I tried re-installing VS Code.
- Searched for over an hour on google and GitHub for a solution.

**Images of Issue:**
![vscode_error_02-28-2017_1](https://cloud.githubusercontent.com/assets/26099581/23443077/72d6dc62-fdfa-11e6-9870-b5ea2419d85a.PNG)
![vscode_error_02-28-2017_3](https://cloud.githubusercontent.com/assets/26099581/23443086/782a5cf2-fdfa-11e6-9f6b-829be0b2e0a3.PNG)

**Update:**
- I also tried to re-run the debugger with all of my extensions disabled.

**Comment by mjbvz** [comment]
@Allenharveyiii Just to make sure, you have Node.js installed? What does `where node` show when run on the command line? How about `echo %PATH%`?

**Comment by Allenharveyiii** [comment]
When I run `where node` in the terminal in VS Code it doesn't return anything.
