### ISSUE TITLE
Command URIs not triggering in markdown preview

### ISSUE THREAD

**Issue by estruyf** [microsoft/vscode#215939]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.0-insider
- OS Version: macOS 13.3.1

Steps to Reproduce:

1. Create a Markdown file and add a command URI like:
```markdown
## Testing

[Test command](command:simpleBrowser.show)

[Docs](https://frontmatter.codes/docs/settings/overview#frontmatter.projects)

[View in VS Code](command:simpleBrowser.show?%5B%22https://frontmatter.codes/docs/settings/overview%23frontmatter.projects%22%5D)
```
3. Clicking on links work in the raw markdown file contents
4. Open the markdown preview and try clicking on the links. Only the second link works. Both command URI links are not working.

https://github.com/microsoft/vscode/assets/2900833/66c6ff75-74b1-4aa8-8c46-c6b4ad772452

**Comment by mjbvz** [comment]
These are disabled for security reasons. No plans to change this at this time
