### ISSUE TITLE
VSCode extremely slow since this morning

### ISSUE THREAD

**Issue by Anouchka-M** [microsoft/vscode#215946]
Type: <b>Performance Issue</b>

Since this morning I notice vscode is extremely slow, it's painful to work with. Didn't change anything during week-end on my side.

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:43.666Z)
OS version: Linux x64 6.5.0-35-generic snap
Modes:

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/issues/212494#issuecomment-2168893148 for a preview of the planned 1.90.2 that should fix your issue.
