### ISSUE TITLE
[merge editor]  the operating button doesn't show 

### ISSUE THREAD

**Issue by taco-wang** [microsoft/vscode#215920]
![image](https://github.com/microsoft/vscode/assets/16523103/4a3c297e-0e99-40d8-b4a7-c845d4aaa0d2)

**Comment by hediet** [comment]
This is weird. Can you check the dev tool logs?

**Comment by taco-wang** [comment]
[Extension Host] send ping
workbench.desktop.main.js:sourcemap:138 [Extension Host] WebSocket is not open. Message not sent: ping
workbench.desktop.main.js:sourcemap:138 [Extension Host] send ping
workbench.desktop.main.js:sourcemap:138 [Extension Host] WebSocket is not open. Message not sent: ping
workbench.desktop.main.js:sourcemap:138 [Extension Host] send ping
workbench.desktop.main.js:sourcemap:138 [Extension Host] WebSocket is not open. Message not sent: ping
workbench.desktop.main.js:sourcemap:138 [Extension Host] send ping
workbench.desktop.main.js:sourcemap:138 [Extension Host] WebSocket is not open. Message not sent: ping
workbench.desktop.main.js:sourcemap:138 [Extension Host] send ping
workbench.desktop.main.js:sourcemap:138 [Extension Host] WebSocket is not open. Message not sent: ping
workbench.desktop.main.js:sourcemap:138 [Extension Host] send ping
workbench.desktop.main.js:sourcemap:138 [Extension Host] WebSocket is not open. Message not sent: ping
