### ISSUE TITLE
add properties to indicates OutputChannel visibility status

### ISSUE THREAD

**Issue by wayou** [Microsoft/vscode#21595]
according to the [vscode doc](https://code.visualstudio.com/Docs/extensionAPI/vscode-api#_a-nameoutputchannelaspan-classcodeitem-id940outputchannelspan) there's only `hide()` and `show()` method but without detecting the status of the outputchannel.

if there's a property indicates the status of the outputpannel that would be nice.

**Comment by jrieken** [comment]
closing as dupe of #6192
