### ISSUE TITLE
VS code crashes frequently

### ISSUE THREAD

**Issue by rexremigius** [microsoft/vscode#215937]
Type: <b>Performance Issue</b>

For the past 1 month I am facing VS code crashing multiple number of times.
Crashes while working and closes automatically.Need to open it again

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:43.666Z)
OS version: Linux x64 5.15.0-107-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 3014)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 5, 5|
|Memory (System)|15.31GB (7.79GB free)|
|Process Argv|--force-user-env --no-sandbox --use-gl=angle --use-angle=swiftshader --crash-reporter-id 6e1c4972-9c34-47ba-b577-7ae0545f54da|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   172	 62059	code main
    0	    31	 62061	   zygote
    0	    31	 62062	   zygote
    0	   329	 62133	window [1] (model_compiler.py - UntetherAI_SpeedAI - Visual Studio Code)
    0	    94	 68636	window [2] (Issue Reporter)
    0	    63	 62096	   utility-network-service
    0	   266	 62163	extensionHost [1]
    0	   125	 62275	     electron-nodejs (server.js )
    0	    78	 62291	     electron-nodejs (languageserver.js )
    0	    31	 62311	     /bin/python3 /home/rex-mcw/.vscode/extensions/ms-python.black-formatter-2024.2.0/bundled/tool/lsp_server.py --stdio
    0	  1128	 62666	     /home/rex-mcw/.nvm/versions/node/v20.14.0/bin/node --max-old-space-size=8192 /home/rex-mcw/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist/server.bundle.js -- --clientProcessId=62163 --cancellationReceive=file:28bbd15e423c58604d673c0aa5072256dc0b8eb8da --stdio
    0	    63	 62758	     /snap/code/161/usr/share/code/code /snap/code/161/usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=62163
    0	   110	 62173	shared-process
    0	     0	 68667	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 68668	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   157	 62174	fileWatcher [1]
    0	    78	 62344	ptyHost
    0	     0	 62387	     /usr/bin/bash --init-file /snap/code/161/usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (********.py - ************ - Visual Studio Code)
|    Folder (**********): more than 28316 files
|      File types: c(5504) cpp(4711) h(1301) m(681) o(590) hpp(540) keep(415)
|                  py(407) rst(241) s(237)
|      Conf files: makefile(76) cmake(53) dockerfile(8) settings.json(2)
|                  devcontainer.json(1) tasks.json(1);
```

</details>
<details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
td-code|arc|0.5.0
atlascode|atl|3.0.10
llvm-syntax-highlighting|col|0.0.3
arm|dan|1.7.4
gitlens|eam|15.1.0
vscode-assorted-languages|Edw|0.30.0
prettier-vscode|esb|10.4.0
code-runner|for|0.12.2
c-cpp-runner|fra|9.4.8
codespaces|Git|1.16.23
vscode-pull-request-github|Git|0.88.1
llvm-tablegen|jak|0.0.2
lldb-vscode|lan|0.2.3
vscode-mlir|llv|0.0.11
autoconf|mae|0.2.0
cortex-debug|mar|1.12.1
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.25
peripheral-viewer|mcu|1.4.6
rtos-views|mcu|0.0.7
git-graph|mhu|1.30.0
theme-monokai-pro-vscode|mon|1.3.2
vscode-docker|ms-|1.29.1
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.6.0
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.369.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.18.42
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.9.10
remote-explorer|ms-|0.4.3
material-icon-theme|PKi|5.4.2
code-debug|qua|1.0.64
vscode-yaml|red|1.15.0
llvm-ir|rev|1.0.5
LiveServer|rit|5.7.9
llvm|RRe|0.2.0
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-icons|vsc|12.8.0
debug|web|0.27.0
clang-format|xav|1.9.0
linkerscript|Zix|1.0.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
2f103344:31071589

```

</details>

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/issues/212494#issuecomment-2168893148

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/212494, please follow the issue for updates.
