### ISSUE TITLE
[json] deprecation warning indicator should be shown under attribute name, not value

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#21597]
![image](https://cloud.githubusercontent.com/assets/323878/23445898/c960a0b0-fdf3-11e6-915a-bcb7db7a3c9a.png)

The warning is that 'outDir' is deprecated, so 'outDir' should be underlined. If an attribute isn't recognized, then the attribute is underlined in that case.

**Comment by isidorn** [comment]
AFAIK this is currently not supported by the json schema
Also I think there is already a bug for this but I could not find it
