### ISSUE TITLE
The VScode has become slow after recent update

### ISSUE THREAD

**Issue by ghobadkhan** [microsoft/vscode#215910]
Type: <b>Performance Issue</b>

After the recent update (1.90.1) The main vscode window has become very slow and sluggish. I tried to disable all of the extensions but it didn't change anything. When I open the process monitor I see no extra process usage, killing different processes also don't help.

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:43.666Z)
OS version: Linux x64 6.5.0-35-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz (8 x 4224)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 2|
|Memory (System)|15.32GB (11.67GB free)|
|Process Argv|--force-user-env --no-sandbox --use-gl=angle --use-angle=swiftshader --crash-reporter-id 2eb1c369-5f3a-4345-8d2d-ef9f11197927|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   157	 29082	code main
    0	    31	 29084	   zygote
    0	    31	 29085	   zygote
    0	   235	 29161	window [1] (Visual Studio Code)
    0	    94	 29636	window [2] (Issue Reporter)
    0	    63	 29120	   utility-network-service
    0	   126	 29409	extensionHost [1]
    0	    63	 29466	     /snap/code/161/usr/share/code/code /snap/code/161/usr/share/code/resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=29409
    0	   110	 29475	     electron-nodejs (tsserver.js )
    0	   110	 29476	     electron-nodejs (tsserver.js )
    0	    78	 29507	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    94	 29490	     /snap/code/161/usr/share/code/code /snap/code/161/usr/share/code/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=29409
    0	    63	 29492	     /snap/code/161/usr/share/code/code /snap/code/161/usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=29409
    0	   110	 29425	shared-process
    0	     0	 29659	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 29660	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    78	 29426	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869

```

</details>

**Comment by ghobadkhan** [comment]
It seemed it needed a fresh install. The issue is fixed after Uninstalled, deleted the config folder and re-installed.

**Comment by hajipour** [comment]
Check the following issue: [](https://github.com/microsoft/vscode/issues/215512).
The following revert command works for me:
`sudo snap revert code`

**Comment by LcsGa** [comment]
> Check the following issue: . The following revert command works for me: `sudo snap revert code`

It worked for me! Thanks!
