### ISSUE TITLE
Bug in the builtin shell script extention

### ISSUE THREAD

**Issue by skyp0714** [microsoft/vscode#215908]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.90.1
- OS Version: Mac OS Sonoma 14.5

Steps to Reproduce:

1. Open any bash scripts 
2. Use left shift operator(`<<`) inside the arithmetic expansion(`$(())`). e.g. `a=$((1<<2))`
3. The code after the line is not highlighted properly. ( $(( is indicated as a string, and all the following lines as well)

But it works well in the arithmetic if condition. e.g. `if [[ 1<<2 > i ]]; ...`

**Comment by alexr00** [comment]
Can you share a screenshot?

**Comment by alexr00** [comment]
The image you included doesn't show. Can you please add it on github.com?

**Comment by skyp0714** [comment]
![image](https://github.com/microsoft/vscode/assets/49219254/ac64598a-22cf-42c6-bb85-502841228d70)

**Comment by alexr00** [comment]
Thanks! Moved to https://github.com/jeff-hykin/better-shell-syntax/issues/93, which is where we get our shellscript grammar from.
