### ISSUE TITLE
Cannot fully copy the output from DEBUG CONSOLE

### ISSUE THREAD

**Issue by Master76** [Microsoft/vscode#21590]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-svgviewer|cssho|1.2.0|
|python|donjayamanne|0.5.8|
|java-debug|DSnake|0.0.2|
|language-polymer|jonwolfe|0.7.8|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.4.1|
|PowerShell|ms-vscode|0.7.2|
|debugger-for-chrome|msjsdiag|2.2.2|
|svg-snippets|sidthesloth|1.0.0|

---

Steps to Reproduce:

1. it seems that the selected text in the debug console, can only be the text in showing, for example:
this is the full output:

Minibatch: 0, Train Loss: 1.6113964427601208, Train Evaluation Criterion: 0.8863636363636364
Minibatch: 10, Train Loss: 1.551224118187314, Train Evaluation Criterion: 0.40476190476190477
Minibatch: 20, Train Loss: 1.4858395323461415, Train Evaluation Criterion: 0.3877551020408163
Minibatch: 30, Train Loss: 1.4213421843772711, Train Evaluation Criterion: 0.37209302325581395
Minibatch: 40, Train Loss: 1.3918920818128084, Train Evaluation Criterion: 0.42105263157894735
Minibatch: 50, Train Loss: 1.3830745333716983, Train Evaluation Criterion: 0.47619047619047616
Minibatch: 60, Train Loss: 1.3504153781467014, Train Evaluation Criterion: 0.4444444444444444
Minibatch: 70, Train Loss: 1.3280073125311669, Train Evaluation Criterion: 0.46808510638297873
Minibatch: 80, Train Loss: 1.2096052402403297, Train Evaluation Criterion: 0.3902439024390244
Minibatch: 90, Train Loss: 1.2241703601593668, Train Evaluation Criterion: 0.425531914893617
Minibatch: 100, Train Loss: 1.1858400132921008, Train Evaluation Criterion: 0.35555555555555557
Minibatch: 110, Train Loss: 1.4261653206565164, Train Evaluation Criterion: 0.5454545454545454
Minibatch: 120, Train Loss: 1.1954298434050188, Train Evaluation Criterion: 0.41304347826086957
Minibatch: 130, Train Loss: 1.411391171542081, Train Evaluation Criterion: 0.5681818181818182
Minibatch: 140, Train Loss: 1.2751765478224981, Train Evaluation Criterion: 0.5
Minibatch: 150, Train Loss: 1.2901817321777345, Train Evaluation Criterion: 0.48
Minibatch: 160, Train Loss: 1.3577163869684392, Train Evaluation Criterion: 0.5227272727272727
Minibatch: 170, Train Loss: 1.3920311151548874, Train Evaluation Criterion: 0.627906976744186
Minibatch: 180, Train Loss: 1.1295534178268078, Train Evaluation Criterion: 0.37209302325581395
Minibatch: 190, Train Loss: 1.4650361975845025, Train Evaluation Criterion: 0.6326530612244898
Minibatch: 200, Train Loss: 1.095071099021218, Train Evaluation Criterion: 0.36363636363636365
Minibatch: 210, Train Loss: 1.372345769128134, Train Evaluation Criterion: 0.5581395348837209
Minibatch: 220, Train Loss: 1.4153381694446912, Train Evaluation Criterion: 0.5909090909090909
Minibatch: 230, Train Loss: 1.2177626291910808, Train Evaluation Criterion: 0.5
Minibatch: 240, Train Loss: 1.0675820638967115, Train Evaluation Criterion: 0.37209302325581395
Minibatch: 250, Train Loss: 1.2622828674316406, Train Evaluation Criterion: 0.46
Error: 0.460000

2. I started the selection at the beginning of the first line.
3. Move the cursor to the end.
4. Because of the size of DEBUG CONSOLE, this will make scrollbar move. And the first several line will not be showed. for example: it can only show 15 lines at a time.
5. Then I press ctrl+c, the text I copied is not the whole output. but the last 15 lines.

Hope you can understand what I am saying.
Sincerely.

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/2163
