### ISSUE TITLE
The cursor location in Terminal is incorrect

### ISSUE THREAD

**Issue by Crazy7** [Microsoft/vscode#21594]
- VSCode Version:1.9.1
- OS Version:Windows 10 15042

Steps to Reproduce:

1. Open or create .net core project
2. Click 'Terminal' tab

![image](https://cloud.githubusercontent.com/assets/1475303/23445022/8d0d667c-fe73-11e6-9e10-bc1b739c9c87.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
