### ISSUE TITLE
JSDoc intellisense & highlight not work for properties with hyphen in it

### ISSUE THREAD

**Issue by VitorLuizC** [Microsoft/vscode#21592]
- VSCode Version: Code - Insiders 1.10.0-insider (40fecfaa77f01672e8a147be71f6f7ccb9cf8a12, 2017-02-27T14:15:13.224Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|vscode-eslint|dbaeumer|1.2.6|
|EditorConfig|EditorConfig|0.3.4|
|typescript-javascript-grammar|ms-vscode|0.0.18|
|typescript-hero|rbbit|0.12.0|
|language-stylus|sysoev|1.6.0|;

---

Steps to Reproduce:

1. Write some JSDoc `@typedef` that has a property with hyphens;
Ex.
```js
/**
 * @typedef Product
 * @property {string} title
 * @property {boolean} high-top
 */
```
2. Highlight and intellisense don't work.

![Screenshot proving highlight don't work](https://i.gyazo.com/95b8276599aa4f87759fb14edbe08b5c.png)

![Screenshot proving intellisense don't work](https://i.gyazo.com/c702b6f57c9d72a7f978cbe8b25ed020.png)

**Comment by mjbvz** [comment]
Thanks. There are two issues here:

* Broken syntax highlighting. Tracked by https://github.com/Microsoft/TypeScript-TmLanguage/issues/424
* Broken intellisense. Tracked by https://github.com/Microsoft/TypeScript/issues/14395

Closing this as upstream
