### ISSUE TITLE
Run task on save?

### ISSUE THREAD

**Issue by glen-84** [Microsoft/vscode#2159]
I've written this task for [sass-lint](https://github.com/sasstools/sass-lint) – is it possible to run it automatically when I save a `*.scss` file?

``` json
{
    "version": "0.1.0",
    "command": "sass-lint",
    "isShellCommand": true,
    "args": ["-c", "path/to/.sass-lint.yml", "-v", "${file}"],
    "showOutput": "silent",
    "problemMatcher": {
        "owner": "sass",
        "fileLocation": "absolute",
        "pattern": [
            {
                "regexp": "^([^\\s].*)$",
                "file": 1
            },
            {
                "regexp": "^\\s+(\\d+):(\\d+)\\s+(error|warning|info)\\s+(.*)\\s\\s+(.*)$",
                "line": 1,
                "column": 2,
                "severity": 3,
                "message": 4,
                "code": 5,
                "loop": true
            }
        ]
    }
}
```

**Comment by felixfbecker** [comment]
Thats what you would use watch tasks for

**Comment by Ciantic** [comment]
I don't agree watch is always a good choice, especially since if you have watch running you can't execute other tasks without terminating.

Also creating another process just for watching less, sass is a overkill, it would be a better if IDE could be made to trigger the task when certain filetype changed, like:

```
{
    "triggerOnChange" : "*.sass",
    "args": ["-c", "path/to/.sass-lint.yml", "-v", "${file}"],
    ...
}
```

**Comment by domaa11** [comment]
This tool seem to do the trick: https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave

**Comment by Ciantic** [comment]
@domaa11  It does the trick, but one must duplicate all tasks to separate file. Maybe if it were rewritten to run tasks on saving it would do exactly that.

**Comment by dbaeumer** [comment]
We have plans to support running multiple tasks in parallel. So such a watch task would not blocking running other tasks anymore.

**Comment by dbaeumer** [comment]
Watching tasks should be implemented using watch support of exist task runners. Always starting a task on save is not very performant nor battery friendly.

With task 2.0.0 you can run multiple tasks in parallel. So I will close the issue.
