### ISSUE TITLE
")," is being linkified in the editor

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21591]
- VSCode Version: Code - Insiders 1.11.0-insider (799198928b772d1def661d3cd7962f04b7f38b98, 2017-02-28T07:09:02.848Z)
- OS Version: Linux x64 4.8.0-37-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|theme-glacier|Tyriar|0.0.10|
|theme-sapphire|Tyriar|0.0.5|
|vscode-terminal-here|Tyriar|0.0.5|
|vscode-svgviewer|cssho|1.3.1|
|tslint|eg2|0.8.1|
|git-project-manager|felipecaputo|1.0.1|
|vsc-travis-ci-status|felixrieseberg|1.0.5|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.1|
|csharp|ms-vscode|1.7.0|
|seti-icons|qinjia|0.1.3|
|annotator|ryu1kn|0.10.1|;

---

![image](https://cloud.githubusercontent.com/assets/2193314/23444683/74667754-fdeb-11e6-98b9-99f2930e9d62.png)

/cc @mjbvz (markdown)

**Comment by isidorn** [comment]
@mjbvz no need to add verifcation-needed label if there is already a 'bug' label
