### ISSUE TITLE
1.90 high cpu usage in idle (when editor focused), and even higher when typing

### ISSUE THREAD

**Issue by jwhtkr** [microsoft/vscode#215996]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.1 (snap package)
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Upgrade snap package from the previous version (1.89.1) to 1.90.1
2. Watch CPU usage soar while using vscode
3. Ok, more specifically, the usage is very high while typing or idling with an editor window focused. It is not high when, for example, the terminal is focused.

Under idle (editor is focused, but no typing, scrolling, or other activity)
![idle-usage](https://github.com/microsoft/vscode/assets/28744886/75d08c04-84c6-4c94-89a5-3f52c67fc4bd)

When typing
![typing-usage](https://github.com/microsoft/vscode/assets/28744886/4b3e0787-fae7-4220-aad8-6ecd892cbe55)

Note that this usage is with all extensions disabled, but gets dramatically even worse with some extensions enabled. Like to the point where there is SIGNIFICANT lag for typing/interacting with the editor (like a second between key press and the letter appearing).
While I could do an extension bisect to determine the extensions that cause this, the evidence seems to point to this being a root VSCode problem that is just exacerbated by extensions.

Reverting the snap package does result in SIGNIFICANTLY improved CPU usage:
Idle:
![old-idle-usage](https://github.com/microsoft/vscode/assets/28744886/2b22e5e9-c492-4e51-98ea-825b373f0aee)
Typing:
![old-typing-usage](https://github.com/microsoft/vscode/assets/28744886/4029b3f7-b8f6-40e1-8b8c-a740aa5ee41c)

For now I'm going to continue using the reverted snap package, but am willing to test out with the new version if helpful.

Note: May be related to #212494, although that issue is about crashes with the new snap package, not CPU usage.

**Comment by Programie** [comment]
I've stumbled across the same issue. Reverting to the previous version (89de5a8d in my case) fixed it.

**Comment by shelvesdragon** [comment]
> Note: May be related to https://github.com/microsoft/vscode/issues/212494, although that issue is about crashes with the new snap package, not CPU usage.

#212494 is likely related since version 1.90.1 tried to address the crashes on start up related to hardware acceleration there by switching OpenGL backend to software emulation, which is causing the high resource usage. There is a candidate build mentioned here https://github.com/microsoft/vscode/issues/212494#issuecomment-2168893148 that addresses both the crashes and the CPU usage, where feedback is needed in order to get it to release with v1.90.2. Otherwise, the comment above https://github.com/microsoft/vscode/issues/212494#issuecomment-2168072242 has the instructions on the options until the release of 1.90.2
Hope this helps!

**Comment by jwhtkr** [comment]
@shelvesdragon Thank you for pointing me to these. Using the build you pointed to seems to work so far. I'm sorry for missing that discussion in #212494; it is now quite a long discussion, and the discussion of the performance impacts has gotten buried. Thank you for pointing me to those salient comments!
