### ISSUE TITLE
Add bread crumbs support

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#21607]
- VSCode Version: Code - Insiders 1.10.0-insider (40fecfaa77f01672e8a147be71f6f7ccb9cf8a12, 2017-02-27T14:09:29.088Z)
- OS Version: Darwin x64 16.5.0

Add bread crumbs support like jetbrain idea IDE or chrome element inspects!

**Comment by isidorn** [comment]
Can you please elaborate on the feature. What does it do exactly?

**Comment by isidorn** [comment]
Closing until more data is provided.

**Comment by leaxoy** [comment]
Bread is indicate cursor location in a file, or file path.
![](http://o8z0dg641.bkt.clouddn.com/WX20170307-093101@2x.png)

**Comment by isidorn** [comment]
fyi @bpasero

**Comment by luqmanrom** [comment]
Does VSCode have the file breadcrumbs ?

**Comment by isidorn** [comment]
@luqmanrom no, this is an open feature request.

**Comment by luqmanrom** [comment]
Oh I am just curious, because the attached picture only highlighted the function breadcrumbs

**Comment by mjbvz** [comment]
Duplicate of #9418
