### ISSUE TITLE
Opening using context menu starts two copies of VSCode

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [Microsoft/vscode#21606]
- VSCode Version: Version 1.10.0-insider (40fecfaa77f01672e8a147be71f6f7ccb9cf8a12)
- OS Version: Windows 10 AU (1607, 14393.693)

Steps to Reproduce:

1. Find folder with code and right click on it
2. Press "Open with Code"

Excepted Result: One VSCode window with folder we selected
Actual Result: Opens two copies of VSCode - one for folder, second is empty

**Comment by joaomoreno** [comment]
When did it start happening?

Does it repro after a full reinstall?

**Comment by bpasero** [comment]
Does not reproduce for me.

**Comment by DaFri-Nochiterov** [comment]
It starting happening after updates on stable and Insider builds. And not happens after reinstall.

**Comment by bpasero** [comment]
@DaFri-Nochiterov so you cannot reproduce anymore?

**Comment by bpasero** [comment]
ok lets keep an eye on it.

**Comment by DaFri-Nochiterov** [comment]
Started VSCode from Start menu and got two windows. What can cause it?
![image](https://cloud.githubusercontent.com/assets/10401817/24259744/5cd782b8-1024-11e7-9506-c6f4c6899609.png)

Window with project `twitch_penguin` was closed three or more days ago 🤔 
![image](https://cloud.githubusercontent.com/assets/10401817/24259827/a2c7ceae-1024-11e7-965e-0984d54d2a10.png)
