### ISSUE TITLE
vscode 1.9.1 ctrl+j is not working with the terminal

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#21608]
![ks](https://cloud.githubusercontent.com/assets/17777237/23451579/28d91692-fe69-11e6-81e4-d4cf97d34c8b.gif)

**Comment by Tyriar** [comment]
@pixieaka If you want it to toggle the panel this is as designed, ctrl+j is passed to the terminal which handles it. You can skip the terminal by adding the command to the `terminal.integrated.commandsToSkipShell` setting.
