### ISSUE TITLE
Go to implementation should show all implementations if there are multiple

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21602]
Steps to Reproduce:

1. Go to implementation on a method that has multiple implementations

=> you end up in any of those
=> I would expect all implementations to show up in our peek UI (same as find references)

**Comment by mjbvz** [comment]
Can you please provide some example code that shows this. I just tested a few basic scenarios and confirmed that we do show the peek UI when multiple implementations are returned

**Comment by bpasero** [comment]
I cannot reproduce anymore, I know it happened with [`resolveContents`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/files/common/files.ts#L67)
