### ISSUE TITLE
to save the last command in the command palette

### ISSUE THREAD

**Issue by jonygli** [Microsoft/vscode#21603]
- VSCode Version: 1.9.1
- OS Version: win7

Steps to Reproduce:

1.Ctrl+Shift+P
2.command palette, but the last command is not saved, could we save the last command?

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by Eun** [comment]
#17163
