### ISSUE TITLE
Wont calculate grade

### ISSUE THREAD

**Issue by Pdugan22** [microsoft/vscode#216011]
ADD ISSUE DESCRIPTION HERE

Version: 1.90.1
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0
Embedder: codespaces

**Comment by mjbvz** [comment]
I'm guessing this is cs50 or a similar online course. Please file this issue against them instead as VS Code itself doesn't prove any grading functionality
