### ISSUE TITLE
I'm unable to authenticate GitHub with VS code

### ISSUE THREAD

**Issue by dee-goyal** [microsoft/vscode#216027]
Type: <b>Bug</b>

Sign in failed: Error: API rate limit exceeded for user ID 142106293. If you reach out to GitHub Support for help, please include the request ID 306D:2B845B:D24F41:D55A5B:66708D9E and timestamp 2024-06-17 19:25:19 UTC.

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:01:24.262Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.35GB (1.10GB free)|
|Process Argv|--crash-reporter-id 46989261-4195-4742-be00-ad36f36c34d8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
phpserver|bra|3.0.2
vscode-eslint|dba|3.0.10
javascript-ejs-support|Dig|1.3.3
vscode-toggle-column-selection|eri|1.0.6
prettier-vscode|esb|10.4.0
figma-vscode-extension|fig|0.3.5
file-icons|fil|1.1.0
auto-close-tag|for|0.5.15
code-runner|for|0.12.2
copilot|Git|1.204.0
copilot-chat|Git|0.16.1
vscode-pull-request-github|Git|0.90.0
stylelint-plus|hex|0.57.0
rainbow-csv|mec|3.12.0
debugpy|ms-|2024.6.0
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.18.42
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
color-highlight|nau|2.8.0
vscode-xml|red|0.27.1
LiveServer|rit|5.7.9
cmake|twx|0.0.17
php-debug|xde|1.34.0
php-pack|xde|1.0.3
php-intellisense|zob|1.3.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
showvideot:31016892
chatpanelc:31048052
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870

```

</details>

**Comment by TylerLeonhardt** [comment]
Hi @dee-goyal, are you still seeing this?

**Comment by dee-goyal** [comment]
The issue has been resolved.. Thank you sir.

**Comment by ITSjwags** [comment]
was there something done to fix this? i'm seeing this fairly consistently as well.
