### ISSUE TITLE
VS Code takes over .js file icon and type

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#2160]
On Windows install, VS Code is taking over .js and various .js flavor file extension icon and file type.  In Windows explorer, the user no longer sees the JavaScript icon and the detail file Type is "Visual Studio Code".
.php is also overridden.
doc feedback verbatim: "All my files show up with similar icon and similar file description type. It is hard to distinguish now which is the .php file and which is .css file. Even changing registry values doesn't help. It still opens with Code (that's OK) but the icons and file descriptions are very confusing. All my files now show "Visual Studio Code" and nothing else."

**Comment by joaomoreno** [comment]
The user can still define any other application to be the default application to open those files. What happened in this story is that VS Code is the *only* application able to open those types of files and thus is automatically associated to them.

If we need to create icons and descriptions for every file type we are able to run, then that's another issue.
