### ISSUE TITLE
In the fedora to install the vscode failure

### ISSUE THREAD

**Issue by zyfjfj** [Microsoft/vscode#21610]
help
libpthread.so.0()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libpthread.so.0(GLIBC_2.2.5)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libpthread.so.0(GLIBC_2.3.2)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libpthread.so.0(GLIBC_2.3.3)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libgtk-x11-2.0.so.0()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libgdk-x11-2.0.so.0()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libatk-1.0.so.0()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libgio-2.0.so.0()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libpangocairo-1.0.so.0()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libgdk_pixbuf-2.0.so.0()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libcairo.so.2()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libpango-1.0.so.0()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libfreetype.so.6()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libfontconfig.so.1()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libgobject-2.0.so.0()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libdbus-1.so.3()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libXi.so.6()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libXcursor.so.1()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libXdamage.so.1()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libXrandr.so.2()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libXcomposite.so.1()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libXext.so.6()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libXfixes.so.3()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libXrender.so.1()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libX11.so.6()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libXtst.so.6()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libXss.so.1()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libgconf-2.so.4()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libgmodule-2.0.so.0()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	librt.so.1()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libglib-2.0.so.0()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libnss3.so()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libnssutil3.so()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libsmime3.so()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libnspr4.so()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libasound.so.2()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libcups.so.2()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libdl.so.2()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libexpat.so.1()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libstdc++.so.6()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libstdc++.so.6(GLIBCXX_3.4)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libstdc++.so.6(GLIBCXX_3.4.10)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libstdc++.so.6(GLIBCXX_3.4.11)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libstdc++.so.6(GLIBCXX_3.4.14)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libstdc++.so.6(GLIBCXX_3.4.15)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libstdc++.so.6(GLIBCXX_3.4.9)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libm.so.6()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libm.so.6(GLIBC_2.2.5)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libgcc_s.so.1()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libgcc_s.so.1(GCC_3.0)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libgcc_s.so.1(GCC_4.0.0)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libc.so.6()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libc.so.6(GLIBC_2.11)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libc.so.6(GLIBC_2.2.5)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libc.so.6(GLIBC_2.3)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libc.so.6(GLIBC_2.3.2)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libc.so.6(GLIBC_2.3.4)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libc.so.6(GLIBC_2.4)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libc.so.6(GLIBC_2.6)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libc.so.6(GLIBC_2.7)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libc.so.6(GLIBC_2.9)(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要
	libxcb.so.1()(64bit) 被 code-1.9.1-1486597190.el7.x86_64 需要

**Comment by Tyriar** [comment]
You need to provide more information:

- What package are you installing?
- What OS version/bitness?
- How are you installing?

**Comment by zyfjfj** [comment]
i installed 
1、code-1.9.1-1486597190.el7.x86_64.rpm
2、fedora 25
3、use dnf install 
thanks

**Comment by Tyriar** [comment]
If this a message you got during `dnf install`? Those are the dependencies you'll need to install vscode. Did you update the package cache?
