### ISSUE TITLE
"Invalid regular expression" using `PHOTO(?s)(.*)REV` despite `regex101.com` validating it.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/vscode#216105]
<table><tr>
	<th>Does this issue occur when all extensions are disabled?</th>
	<td>Yes</td>
</tr></table>

<table><tr>
	<th>VS Code Version</th>
	<td><code>code-insiders-1.91.0-1718259485.el8.rpm</code></td>
</tr><tr>
	<th>OS Version</th>
	<td><a href='https://download.fedoraproject.org/pub/fedora/linux/releases/40/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40-1.14.iso'><code>cpe:/o:fedoraproject:fedora:40</code></a></td>
</tr></table>

#### **Steps to Reproduce**

1.  Enter `.VCF` data containing a `PHOTO` element, with a `REV` element beneath it:

	```VCF
	BEGIN:VCARD
	VERSION:3.0
	PRODID;VALUE=TEXT:ez-vcard 0.11.3
	FN:Placeholder
	UID:47759cae-7de1-4ae5-82c1-b3bc560e90da
	PHOTO;ENCODING=BASE64;TYPE=GIF:R0lGODdhYABgAPAAALccHMlFJiH5BAEAAAEALAAAAABgAGAAAAJuhI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8YhMKpfMpvMJjUqn1Kr1is1qt9yu9wsOi8fksvmMTqvX7Lb7DY/L5/S6/Y7P6/f8vv8PGCg4SFhoeIiYqLiIUgAAOw==
	REV;VALUE=DATE-AND-OR-TIME:20240224T161008Z
	END:VCARD
	```

	

3.  Try to select those using `PHOTO(?s)(.*)REV` at https://regex101.com./#.

	This shall work.

5.	Test it in VS Code:

	1.	> Invalid regular expression: `/PHOTO(?s)(.*)REV/gu`: Invalid group
	
	1.	> ![image](https://github.com/microsoft/vscode/assets/42837531/87bd2f76-f4ff-492b-92d4-7dba8bd08a71)

**Comment by RyanCavanaugh** [comment]
This relates to VS Code, not TS:

![image](https://github.com/microsoft/vscode/assets/6685088/9a17a046-473f-446f-b1ae-9ff662db8fbd)

**Comment by mjbvz** [comment]
@IllusionMH That's what I thought too but the issue is very unclear:

![Image](https://github.com/user-attachments/assets/af7c74d5-fce2-40ba-b370-8137ce402c52)

@RokeJulianLockhart Please provide full repo steps

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/vscode/issues/216105#issuecomment-2174362276

@mjbvz, what reproduction steps are absent? I've provided sample code and the expression itself, and the version of VSC I'm using.

**Comment by mjbvz** [comment]
Share what are you doing. Provide exact steps (with screenshots if useful)

**Comment by RedCMD** [comment]
@RokeJulianLockhart you hadn't stated that the bug was about the ctrl+F `Find` regex

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/vscode/issues/216105#issuecomment-2174555495

@mjbvz, per the undermentioned, I'm trying to select with RegEx the manually selected line (from `PHOTO` to the `\n` before `REV`) but `PHOTO(?s)(.*)REV` - RegEx which selects that line when the depicted content is utilized at https://regex101.com./# - is considered invalid by VSC.

> ![Screenshot_20240617_235658](https://github.com/microsoft/vscode/assets/42837531/b0ab87f4-769c-4a40-8ce4-3b875ebda848)

Apologies if that explanation is not what you request.

**Comment by IllusionMH** [comment]
Regexp101 also shows an error if you switch to ES/JS
![image](https://github.com/user-attachments/assets/89fc0598-80f0-4a7a-b6c7-3021c6269abe)
Editor's find widget uses ES/JS engine and its grammar, as mentioned above, and correctly report issue with your pattern.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/vscode/issues/216105#issuecomment-2343057920

@IllusionMH, so I should the issue as unactionable? Would be nice if the dialogue demonstrated which engine it was using for a given operation.
