### ISSUE TITLE
jsdoc completions in glob patterns

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21612]
related to  https://github.com/Microsoft/vscode/issues/21147

<img width="607" alt="screen shot 2017-03-01 at 10 27 18" src="https://cloud.githubusercontent.com/assets/1794099/23453740/c69ec656-fe69-11e6-903a-6dee9dc15365.png">

**Comment by mjbvz** [comment]
Fixed by 946b275e0a19ebc649ab615294cb0dfc9a9a8807
