### ISSUE TITLE
Make Terminal hyperlinks configurable

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#21616]
I find it very annoying that Terminal hyperlinks just work on hover & click. Many times I click a terminal because I want to focus it; now with hyperlinks I often find myself navigating somewhere I didn't want to because I happened to hit a hyperlink inside the terminal.

I'd expect links to only work as I hold <kbd>Ctrl</kbd> or <kbd>Cmd</kbd>, just like iTerm and our editor work.

Since this may be a user preference, I suggest to create a setting for it. I also propose to have the default behaviour be the same as the editor: hyperlinks only show and work when holding the keyboard key.

**Comment by Tyriar** [comment]
I'm actually planning on making ctrl+click the default for the reasons you mention https://github.com/Microsoft/vscode/issues/21506

**Comment by joaomoreno** [comment]
Sorry for not searching beforehand 🐙
