### ISSUE TITLE
Starting IW from Active Editor Column will launch two IW editors

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#216156]
Does this issue occur when all extensions are disabled?: Yes/No

https://github.com/user-attachments/assets/386b2206-61e0-495b-99aa-517e809d903f

Example code

```
const interactiveWindowObject = (await vscode.commands.executeCommand(
				'interactive.open',
				{
					preserveFocus: true,
					viewColumn: vscode.ViewColumn.Active,
				},
				undefined,
				controller.id,
				'Node REPL',
			)) as { notebookEditor: vscode.NotebookEditor };
```

**Comment by amunger** [comment]
this doesn't repro when setting `"jupyter.interactiveWindow.viewColumn": "active"`

did you update this piece of the function as well? (you don't need to call that if you call `interactive.open`)

```
await vscode.window.showNotebookDocument(notebookDocument, { viewColumn: vscode.ViewColumn.Beside });
```

**Comment by rebornix** [comment]
@amunger I updated the code `await vscode.window.showNotebookDocument(notebookDocument, { viewColumn: vscode.ViewColumn.Active });` and then I got two IWs. It is likely a bug in the core.

**Comment by rebornix** [comment]
I was using different locations for the notebook document open and `interactive.open`, and since we support showing the the same IW in multiple editor groups, the behavior is as expected. Sorry for the confusion.
