### ISSUE TITLE
Explorer: Collapse all subfolders when collapsing a folder

### ISSUE THREAD

**Issue by misantronic** [Microsoft/vscode#21613]
- VSCode Version: 1.9.1
- OS Version: macOC 10.12.3

A feature I love about Webstorm is, when collapsing a folder, all subfolders will be collapsed. Very useful.
Would you consider adding this as an option or per default?

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
