### ISSUE TITLE
Running debugger with yarn

### ISSUE THREAD

**Issue by bomb-on** [Microsoft/vscode#21620]
I have a NodeJS project which I can start from command line with `yarn start` command. My `package.json` looks similar to this:

```
{
  "name": "projectname",
  "version": "0.0.1",
  "description": "",
  "author": "My Name",
  "license": "",
  "scripts": {
    "start": "yarn dev",
    "dev": "yarn stop && pm2 start pm2-dev.yaml && webpack-dev-server --progress",
    "prod": "yarn stop && yarn build && pm2 start pm2-prod.yaml",
    "build": "rimraf dist lib && babel src -d lib --ignore test.js && cross-env NODE_ENV=production webpack -p --progress",
    "stop": "rimraf logs/* && pm2 delete all || true"
  },
  "dependencies": {
    "body-parser": "~1.16.0",
    "ejs": "2.5.5",
    "express": "^4.14.1",
    "pg": "^6.1.2",
    "react": "^15.4.2",
    "redux": "^3.6.0",
  },
  "devDependencies": {
    "babel-cli": "^6.22.2",
    "cross-env": "^3.1.4",
    "eslint": "^3.13.0",
    "pm2": "^2.3.0",
    "redux-mock-store": "^1.2.2",
    "rimraf": "^2.5.4",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.2.1"
  }
}
```
I am trying to start this project in debugging mode with Visual Studio Code but with almost no luck. I have defined my launch configuration in VS Code `launch.json` file like this:

```js
{
  // Use IntelliSense to learn about possible Node.js debug attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "yarn",
      "runtimeExecutable": "yarn",
      "runtimeArgs": [
        "start"
      ],
      "port": 5858,
      "cwd": "${workspaceRoot}",
      "timeout": 10000
    }
  ]
}
```
The problem with this configuration is that it usually times-out because `webpack-dev-server` build is longer than 10 seconds. I can increase the `timeout` in my configuration, but I have noticed that VS Code results with a message `Cannot connect to runtime process (timeout after 30000 ms).` eventually, so I assume that this is not a good solution. Also, my breakpoints are ignored with this kind of config which tells me that I am definitely doing something wrong here.

This is the first time I am trying out Visual Studio Code and I usually don't use NodeJS, but I got this project with all these scripts in `package.json` already defined so I'm trying to adopt to it and therefore all the confusion about how to run it properly.

Can Visual Studio Code run a project like this with full debugging functionality at all, and if so, how should I configure my launch script?

- VSCode Version: 1.9.1
- OS Version: OS X 10.12.3

**Comment by aarontyler** [comment]
Potentially what you want to do is run the JS file that your **yarn start** configuration is pointing at. For example, in my configuration I had:

```
"start": {
      "command": "node bin/dev-server",
      "env": {
        "DEBUG": "app:*"
      }
```

Which I setup in the VS Code launch.json as:

```
{
      "type": "node",
      "request": "launch",
      "name": "Launch dev-server",
      "program": "${workspaceRoot}/bin/dev-server.js"
}
```

This might work for you too.

**Comment by weinand** [comment]
@bomb-on does your yarn "start" script really starts your program in debugging mode? If not, you will have to pass some debugging flags (e.g. what debugging port to use) in the "runtimeArguments".

**Comment by Sequoia** [comment]
My launch config:
```js
    {
      "type": "node",
      "request": "launch",
      "name": "`yarn start`",
      "cwd": "${workspaceRoot}",
      "runtimeExecutable": "yarn",
      "runtimeArgs": [
        "start"
      ],
      "stopOnEntry": false
    },
```

Debug console output:
```
Debugging with legacy protocol because a runtime executable is set.
yarn --debug-brk=21203 start 
yarn install v0.23.4
error `install` has been replaced with `add` to add new dependencies. Run "yarn add start" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Why is it addeing `--debug-brk=21203`, which seems to be throwing off "yarn start"?

**Comment by weinand** [comment]
@Sequoia By default a launch config assumes the use of node.js-like runtimes which typically takes a `--debug` or `--debug-brk` argument to turn on debug mode.

If you want to prevent VS Code from doing that, just add a "port" attribute to your launch config. In this case VS Code assumes that the "runtimeExecutable" knows best how enable debug mode and it no longer adds`--debug` or `--debug-brk` arguments. On the other hand now VS Code needs to know what debug port is used. And for this you have to specify the debug port.

So in your case make sure that "yarn start" enables debug mode and set the debug port. Otherwise VS Code will try to attach without success.

**Comment by okoala** [comment]
https://github.com/eggjs/egg/issues/1052#issuecomment-308424839
