### ISSUE TITLE
mac os 10.12.3  dlv

### ISSUE THREAD

**Issue by zuojinmin** [Microsoft/vscode#21625]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by zuojinmin** [comment]
First, open a port Request used to listening to the network, and then to debug the program, can't open, shows that the port has occupied then that I want to close off this service all not a line, the kill pid have failedZuojinmindeMacBook - Pro: zuo0118 zuojinmin $lsof - I: 8080COMMAND PID USER FD TYPE DEVICE SIZE/OFF the NODE NAMEThe debug 1467 zuojinmin 3 u x2802924a2f2f6d2d IPv6 0 0 t0 TCP * : HTTP - Alt (LISTEN)ZuojinmindeMacBook - Pro: zuo0118 zuojinmin $kill 9 1467ZuojinmindeMacBook - Pro: zuo0118 zuojinmin $lsof - I: 8080COMMAND PID USER FD TYPE DEVICE SIZE/OFF the NODE NAMEThe debug 1467 zuojinmin 3 u x2802924a2f2f6d2d IPv6 0 0 t0 TCP * : HTTP - Alt (LISTEN)



chinese

首先 ,开启一个端口 用来监听网络请求,然后重新debug 此程序,显示端口已被占用无法开启,然后这个我想关闭掉这个服务都不行了,kill pid 都失败

zuojinmindeMacBook-Pro:zuo0118 zuojinmin$ lsof -i:8080
COMMAND  PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
debug   1467 zuojinmin    3u  IPv6 0x2802924a2f2f6d2d      0t0  TCP *:http-alt (LISTEN)
zuojinmindeMacBook-Pro:zuo0118 zuojinmin$ kill -9 1467
zuojinmindeMacBook-Pro:zuo0118 zuojinmin$ lsof -i:8080
COMMAND  PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
debug   1467 zuojinmin    3u  IPv6 0x2802924a2f2f6d2d      0t0  TCP *:http-alt (LISTEN)

**Comment by isidorn** [comment]
Please provide exact steps nad format your issue nicely. Currently it is unreadable

**Comment by zuojinmin** [comment]
First of all, the debug code, he is just the first time, when I want to add something to debug,Then we have a problem, prompt the port being used, I can't use kill command closed, when I go to the background check process of CPU time found DLV has been running, to debug, DLV increases and will not disappear, unless close DLV the process

**Comment by isidorn** [comment]
Can you please format this issue so it becomes readable. Thank you
Also try to provide exact steps to reproduce otherwsie it is very hard for us to help here

**Comment by ramya-rao-a** [comment]
@zuojinmin From what I can understand, you are trying to debug your Go program and are using the Go extension. First time debug runs fine. But the second time you debug, you get a message saying that the port is already in use.

If that is what it is, then this particular issue is tracked in https://github.com/Microsoft/vscode-go/issues/438 

The fix is out in the latest update of the Go extension (0.6.55)

Please update and let us know if the issue is fixed for you.

**Comment by ramya-rao-a** [comment]
Closing this issue as we havent heard back from the OP in a while. 

@zuojinmin For more Go related issues you can log an issue at https://github.com/Microsoft/vscode-go
