### ISSUE TITLE
VSCode

### ISSUE THREAD

**Issue by elzoq** [Microsoft/vscode#21624]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|php-autocomplete|bschulte|0.4.2|
|jquerysnippets|donjayamanne|0.0.1|
|vs-code-xml-format|fabianlauer|0.1.4|
|auto-close-tag|formulahendry|0.3.9|
|auto-complete-tag|formulahendry|0.0.1|
|auto-rename-tag|formulahendry|0.0.11|
|JSDocTagComplete|HookyQR|0.0.2|
|Angular2|johnpapa|2.0.3|
|format-indent|Kasik96|1.3.0|
|debugger-for-chrome|msjsdiag|2.5.5|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Please provide exact reproducable steps and we can reopen this issue
