### ISSUE TITLE
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z) - OS Version: Windows_NT ia32 10.0.14393

### ISSUE THREAD

**Issue by Kibos** [Microsoft/vscode#21623]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.1.0|
|javadebugger|donjayamanne|0.0.2|

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Please provide exact reproducable steps and what seems to be the issue and we can reopen this
