### ISSUE TITLE
A issue of using Mono Debug to debug a example with gui.

### ISSUE THREAD

**Issue by tengxianbing** [Microsoft/vscode#21626]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 3.19.0-80-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.1|
|csharp|ms-vscode|1.7.0|
|mono-debug|ms-vscode|0.15.3|

---

Steps to Reproduce:

1. Use mono-debug to debug a c# example with gui, it works.
2. The debug feature doesn't work(can't step over or step into to watch variables) when the gui of example showing.
3. Could you help check?

**Comment by weinand** [comment]
@tengxianbing how does your launch configuration look like?

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-mono-debug#24
