### ISSUE TITLE
VSCODE frequently crashing

### ISSUE THREAD

**Issue by pradeep7893** [microsoft/vscode#216340]
Version: 1.90.1
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:02:43.666Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 5.15.0-107-generic snap

it is still occouring with extensions diabled

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/issues/212494#issuecomment-2168893148 will help. Or wait for 1.90.2

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/212494, should be fixed in `1.90.2`
