### ISSUE TITLE
Enable consumers to hook into the terminal link matcher by specifying a priority for the link matchers

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21637]
Right now link matchers are considers in the order in which they are declared, meaning any task framework link matchers that are registered will be the last considered so the local link matchers would always beat it.

/cc @dbaeumer

**Comment by Tyriar** [comment]
@dbaeumer this should be good to go now, any custom links registered with ITerminalInstance.registerLinkHandler should be higher priority than the generic local link matcher, and lower priority than the http link matcher.

**Comment by isidorn** [comment]
@dbaeumer please verify

**Comment by Tyriar** [comment]
The fact that tasks can add links means this is verified.
