### ISSUE TITLE
skipFiles stopping on file in node_modules even though excluded

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode#21636]
- VSCode Version: 1.10.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Launch unit tests with "all exceptions" selected
2. Watch it break in `node_modules/json3/lib/json3.js`

This is running unit tests using mocha + ts-node/register (not sure if this has anything to do with it -- seems the glob matching should really know/care about that)

![image](https://cloud.githubusercontent.com/assets/573056/23469227/0dc068d0-fe71-11e6-8469-aeda5c059059.png)

launch config:

```json
        {
            "name": "Launch Unit Tests",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
            "stopOnEntry": false,
            "args": [
                "--watch",
                "--debug",
                "test/unit/**/*.ts"
            ],
            "runtimeExecutable": null,
            "env": {
                "NODE_ENV": "mocha"
            },
            "sourceMaps": true,
            "console":"internalConsole",
            "outFiles": [
                "dist"
            ],
            "skipFiles": [
                "node_modules/**/*.js",
                "<node_internals>/**/*.js"
            ]
        }
```

**Comment by Brayyy** [comment]
I just noticed this problem today but found a workaround. It appears that relative paths aren't working, but if you include the variable for workspace root, the node_modules directory is correctly ignored.

```
"skipFiles": [
  "${workspaceRoot}/node_modules/**/*.js",
  "<node_internals>/**/*.js"
]
```

**Comment by weinand** [comment]
Yes, skipFiles glob patterns must be absolute paths.

**Comment by jamietre** [comment]
OK - my config is copied directly from the documentation, so that should probably be updated.

https://code.visualstudio.com/docs/editor/node-debugging#_skipping-uninteresting-code-node-chrome

imho the way it's documented is more intuitive and consistent with other types of file pattern matching config in vscode (e.g. for excluding files from searches and CTRL+P) than requiring a root path, seems more flexible too (since rooted is an option with glob, but not vice-versa)

**Comment by weinand** [comment]
@jamietre for debug adapters all paths are absolute (even if VS Code is able to use relative paths in other areas). This applies to glob patterns too.

Thanks for spotting the doc problem. I'll fix it now.

**Comment by jamietre** [comment]
Probably you shouldn't describe this as "glob" patterns  if the paths have to be absolute.

Will the fact that these paths have to be absolute still work if I have symbolic links in `node_modules`? That is, if I'm using `npm link` to include modules from paths that are not rooted under the project root.

**Comment by weinand** [comment]
The paths must match against the paths seen by node when hitting breakpoints etc. (and node paths are always absolute). So it doesn't matter where they are rooted.

**Comment by jamietre** [comment]
Sorry i edited that last one hafl a dozen times ;)

Would this `/**/node_modules/**/*.js` work?

**Comment by weinand** [comment]
I haven't tried this but it could very well work (at least for the legacy node debugger). Try it!

**Comment by jamietre** [comment]
Just tried it and answered my own question `/**/node_modules/**/*.js `*it does not* - so I'm still unclear on exactly what is allowed here.

**Comment by jamietre** [comment]
Legacy - I haven't been able to get inspector to work (though I didn't try too hard)

**Comment by jamietre** [comment]
@weinand I am still having a lot of trouble getting this to work with any consistency. When running with mocha (legacy protocol) it breaks in `%APP_DATA%/npm/node_modules/**` which kind of make sense, since I'm running mocha from the CLI. So I added a directive to try to fix this using a hard rooted path (which is not really great - since it will only work on my machine - but don't think there is another way):

            "skipFiles": [
                "${workspaceRoot}/node_modules/**/*.js",
                "<node_internals>/**/*.js",
                "D:/users/[username]/appdata/roaming/npm/node_modules/**/*.js"
            ],

It no longer stops in the global `node_modules` folder - but it now stops in node internals as well as node_modules for the application! Somehow adding that third directive caused the others to no longer work. Any ideas...
