### ISSUE TITLE
Tab key will randomly stop inserting tabs into editor

### ISSUE THREAD

**Issue by krworks** [Microsoft/vscode#21638]
- VSCode Version:1.9.1
- OS Version:Ubuntu GNOME 15.04

Steps to Reproduce:

1. Use VSCode code editor; use the tab key to indent
2. Tab key will eventually stop inserting a tab character into the code editor pane and act as a focus switch over to the console (or other pane thats next in line)

It can take days before this happens.  Sometimes, however it can happen almost immediately.  Restarting VSCode is the only thing that helps.

**Comment by isidorn** [comment]
Do you see an indiciation in the status bar:
You might have triggered an action that tab moves focus - you should be able to get out of this state by triggering the action in the command palette for tab key to move focus

![screen shot 2017-03-01 at 20 01 39](https://cloud.githubusercontent.com/assets/1926584/23476109/ee7cb17e-feb9-11e6-84d0-421e9ef84bd2.png)


![screen shot 2017-03-01 at 20 01 13](https://cloud.githubusercontent.com/assets/1926584/23476083/d73c5a00-feb9-11e6-8d42-0d1ba1f5a98b.png)

**Comment by krworks** [comment]
It looks that's what was happening.  That action was effectively bound to Meta+M on my system and was inadvertently triggered. Thanks.
