### ISSUE TITLE
command line to launch task is badly formed for integrated terminal

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode#21635]
- VSCode Version: 1.10.0-insider
- OS Version: Windows 10

Steps to Reproduce: 

1. Create a launch config using "integratedTerminal"
2. Run it

My configuration creates the following command line, which isn't valid (pehaps there should be an && there instead of the semicolon?)

`cd d:\Users\JAMIE\code\project; env NODE_ENV=mocha node --debug-brk=45564 --nolazy node_modules\mocha \bin\_mocha --watch --debug test/unit/**/*.ts`

This is the config 

```json
        {
            "name": "Launch Unit Tests",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
            "stopOnEntry": false,
            "args": [
                "--watch",
                "--debug",
                "test/unit/**/*.ts"
            ],
            "runtimeExecutable": null,
            "env": {
                "NODE_ENV": "mocha"
            },
            "sourceMaps": true,
            "console":"integratedTerminal",
            "outFiles": [
                "dist"
            ],
            "skipFiles": [
                "node_modules/**/*.js",
                "<node_internals>/**/*.js"
            ]
        }
```

**Comment by dbaeumer** [comment]
@isidorn I assign back to you. It is a launch config without a pre task. Not sure so if this is debug or the integrated terminal.

**Comment by isidorn** [comment]
As far as I understand, this is the integrated terminal can not handle some output the users program is computing. If I am mistaken then please provide more details @jamietre 
Unrelated to debug. Assigning back to @Tyriar

**Comment by jamietre** [comment]
This is a command generated by Visual Studio when I start my task called "Launch Unit Tests". It's not any code of mine or a user program. I assume it is produced entirely from the `launch.json` config I included above.

If I try to start this task using `integratedTerminal`, it fails, and it shows this command line in my integrated console:

`cd d:\Users\JAMIE\code\project; env NODE_ENV=mocha node --debug-brk=45564 --nolazy node_modules\mocha \bin\_mocha --watch --debug test/unit/**/*.ts`

If I start it using `internalConsole` then it works, and it only show this command line:

`node --debug-brk=43169 --nolazy node_modules\mocha\bin\_mocha --watch --debug test/unit/**/*.ts `
So using the `integratedTerminal` option seems to generate an extra `cd` command (even though the terminal already seems to open in the working directory) and separates it from the debug launch command with a semicolon.

**Comment by Tyriar** [comment]
@isidorn @weinand I think it's related to debug launching the user configured shell, not a specific one so the command appending being used is not reliable. You can also set the `cwd` in `IShellLaunchConfig` when creating an `ITerminalInstance` now which is the best fix for this.

**Comment by isidorn** [comment]
Assigning to @weinand since [TerminalSupport](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/terminalSupport.ts#L14) is handling this I believe

**Comment by jamietre** [comment]
I haven't tried this in a few days, but In today's preview, using "intergratedTerminal" or "externalTerminal", it's broken in a different way:

![image](https://cloud.githubusercontent.com/assets/573056/23998856/d7289d2a-0a2c-11e7-9d43-a9516dbffa6f.png)

Seems like it's not quoting the CLI exe path itself properly now...

    "terminal.integrated.shell.windows": "c:\\program files\\JPSoft\\TCCLE14x64\\tcc.exe",

Opening a terminal window works fine still, but launching a task with it doesn't at all any more. "internalConsole" is the only one working.

**Comment by weinand** [comment]
Verification notes:
The fix addresses issues that occurred when configuring the `console` attribute in launch configs to `integratedTerminal` **and** configuring a shell for the integrated terminal via the `terminal.integrated.shell.*`settings:
- if the configured shell is not recognised the code no longer falls back to assume a unix shell but uses the platform default, on Windows: cmd.exe on linux & macOS: bash.
- if a bash shell is configured on Windows (e.g. git bash.exe or WSL bash.exe), it is properly recognised.

**Comment by aeschli** [comment]
Verified the first item
