### ISSUE TITLE
Feature Request: TypeScript Imports Management

### ISSUE THREAD

**Issue by jkyoutsey** [Microsoft/vscode#21632]
I would like to see better management of imports in Typescript.  There are some extensions out there, but don't work so well.

I would like to be able to organize imports, auto-fold imports, and get auto/shortcut import of missing imports.

**Comment by mjbvz** [comment]
I've created separate issues to track the first two requests, but the last one is about " get auto/shortcut import of missing imports" is unclear to me. Could you please explain that one a bit more, perhaps with an example of the expected behavior

**Comment by mjbvz** [comment]
Please open a new issue for the last feature you mention. Closing this issue out as separate issues are now tracking the other two feature requests
