### ISSUE TITLE
Typescript intellisense not working

### ISSUE THREAD

**Issue by snraets** [Microsoft/vscode#21630]
- VSCode Version: Version 1.9.1
- OS Version: Windows 10 Version 1511

Steps to Reproduce:

1. Create an NPM project on a Windows shared drive
2. Use the Typescript included in Visual Studio Code

I am working on a project that sits on a shared drive.  When I start Visual Studio Code, the intellisense feature for Typescript works fine with the @Types installed.  Eventually, after using it once, it starts to fail.  It stops giving suggestions.  I have to close code and then re-open.  Either reloading the window or restarting code seems to fix the problem.

**Comment by mjbvz** [comment]
There were a few issues with network drives in TypeScript 2.1.6 that shipped with VSCode 1.9. Please try upgrading to TypeScript 2.2 by using VSCode 1.10 which should be coming out shortly (you can also always use the current insiders build).

Please let me know if this still fails with TypeScript 2.2 on VSCode 1.10.

Thanks
