### ISSUE TITLE
Flaky Test: Terminal - Terminal Tabs - should reset the tab name to the default value when no name is provided

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#216460]
See https://dev.azure.com/monacotools/Monaco/_build/results?buildId=278932&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=9ab437b3-ee70-5588-b120-442542e6d570

**Comment by Tyriar** [comment]
@meganrogge are you aware of any recent changes that could have affected this? It looks like the single tab is visible in the failure screenshot:

![playwright-screenshot-1-should_reset_the_tab_name_to_the_default_value_when_no_name_is_provided](https://github.com/user-attachments/assets/4e284211-ccc2-48be-b0fc-fc73701fc4fb)

**Comment by Tyriar** [comment]
I think it's related to this line not clearing the quick pick:

https://github.com/microsoft/vscode/blob/be0e53510d8128ee4d17205fcb9511963a5bbb43/test/smoke/src/areas/terminal/terminal-tabs.test.ts#L45
