### ISSUE TITLE
files.associations not working properly for pre-existent files

### ISSUE THREAD

**Issue by Alecsou** [microsoft/vscode#216432]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.1
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Start with an empty "files.associations" field in the Code/User/settings.json
2. Clone any repository with a .yml file for example, not recognized natively as YAML
3. `CTRL`+`K` `M` to open Language settings, then `Configure file association for .yml`, then select YAML
4. The Code/User/settings.json is modified, but nothing is updated. 

Reloading the windows with or without extension doesn't fix, restarting VSCode doesn't fix, restarting the PC doesn't fix.
Manually assigning the language does work for the file you assigned, but not others of the same extension.
Creating a new file will be assigned the correct language.
Updating a file won't be assigned the correct language.

**Comment by bpasero** [comment]
I cannot reproduce. Btw `.yml` for me already opens as `YAML` by default without doing anything.

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Alecsou** [comment]
Alright, sorry for the false claim, it looks like that one repo I was testing with had a .vscode with a settings.json file that was mis-configured. Apologies!
