### ISSUE TITLE
Broken rendering in Copilot Chat

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#216483]
Latest insiders, copilot chat pre-release

1. Open chat view, say "Write a bubble sort algorithm"
4. Get response, say "Write a quick sort algorithm"
5. Reload. Broken rendering, the code part of the response is badly cut off, and I can not sort 🐛 
 
I can repro this 100%

![Image](https://github.com/user-attachments/assets/bbc23efb-0ae6-43f2-8f9a-e94bca48fd6f)

**Comment by roblourens** [comment]
I suspect it's related to https://github.com/microsoft/vscode-copilot/issues/6247, but we'll see

**Comment by roblourens** [comment]
I think it's gone now

**Comment by isidorn** [comment]
Correct, I can no longe reproduce.
