### ISSUE TITLE
JS files no longer get type checked

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#216424]
Steps to Reproduce:

1. open a file such as `src/vs/base/node/unc.js`
2. rename a function that is used

=> 🐛 no compile error anymore even though `//@ts-check` is set

**Comment by mjbvz** [comment]
You need to have `//@ts-check` before `'use strict'`:

```
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
//@ts-check

'use strict';
```

I tested as far back as TS 4.0 and see the same behavior so I don't think this is a regression. Will submit a PR changing this

I think we may have had a top level tsconfig/jsconfig file handled this, but this also caused a bunch of extra files to get loaded. If there are enough JS files under `src` where this happens, we could create a jsconfig for them

**Comment by bpasero** [comment]
@mjbvz isn't our top level `tsconfig.json` taking care of some via `includes`:

https://github.com/microsoft/vscode/blob/40e1b609926a4dc7545c186eeceecfed436aa0c6/src/tsconfig.json#L27-L41

**Comment by mjbvz** [comment]
Yes good find. Since we are explicitly listing the includes instead of having a glob like `**/*.js`, we could add it to the list there too and remove the `@ts-check` comment. You can decide if this makes sense or not for `unc.js`

**Comment by bpasero** [comment]
@mjbvz I do not see compile errors in the opened editor when I remove `//@ts-check`, even if the file is listed in `tsconfig.json`
