### ISSUE TITLE
Automatic Type Acqusition not working on Fedora

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#21646]
- VSCode Version: Code 1.10.0 (49129d126e2c3c5592cfc8a509d872067b69d262, 2017-03-01T17:09:34.031Z)
- OS Version: Linux x64 4.5.5-300.fc24.x86_64
- Extensions: none
---

Steps to Reproduce:

1. Open `test.js`
2. `require('express')().`
3. -> Does not show type-specific proposals

There is a single file in the cache: `.cache/typescript/package.json` with just the empty object in it.

/cc @Tyriar

**Comment by mjbvz** [comment]
The root cause seems to be that `npm` is not installed. I'm investigating this on other platforms as well

**Comment by mjbvz** [comment]
Two issues are tracking this on the TypeScript side:

* No error being generated: https://github.com/Microsoft/TypeScript/issues/14398
* Add error message to typings install failure: https://github.com/Microsoft/TypeScript/issues/14447

**Comment by mjbvz** [comment]
With TS 2.2.2 insiders we just picked up, an error notification is now generated in this case. It still does not have a good user facing message about not having npm installed. That is being tracked by  https://github.com/Microsoft/TypeScript/issues/14447
