### ISSUE TITLE
GIT or SCM?

### ISSUE THREAD

**Issue by gautamsi** [Microsoft/vscode#21645]
- VSCode Version: Code - Insiders 1.10.0-insider (40fecfaa77f01672e8a147be71f6f7ccb9cf8a12, 2017-02-27T14:15:13.224Z)
- OS Version: Windows_NT ia32 10.0.14986
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|MochaSnippets|Alan|0.0.1|
|Bookmarks|alefragnani|0.11.0|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|vscode-npm-source|dkundel|1.0.0|
|githistory|donjayamanne|0.1.5|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|Theme-azure|gerane|0.0.2|
|beautify|HookyQR|0.8.1|
|JSDocTagComplete|HookyQR|0.0.2|
|docthis|joelday|0.3.11|
|tsd-recommender|jrieken|0.0.2|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|new-cmd|odonno|0.2.0|
|material-icon-theme|PKief|1.3.3|
|startanyshell|remcoros|0.3.1|
|autoimport|steoates|1.2.2|
|addDocComments|stevencl|0.0.8|
|vscode-gulp|tanato|0.0.4|
|cordova-tools|vsmobile|1.2.6|
|iis-express|warren-buckley|0.0.6|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|D3Snippets|yoyo|0.1.11|;

---

Steps to Reproduce:

1. open a gihtub repo (mine is a Typescript project)
2. notice the icon for Git status, it says SCM now

**Comment by isidorn** [comment]
As designed. More details can be found here https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_10.md#contributable-scm-providers
