### ISSUE TITLE
Model comes back as "undefined"

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#216477]
```typescript
const MODEL_SELECTOR: vscode.LanguageModelChatSelector = { vendor: 'copilot', family: 'gpt-3.5-turbo' };
const [model] = await vscode.lm.selectChatModels(MODEL_SELECTOR);
```

Model is undefined 🐛 

This was working yesterday. Can repro with Chat Sample https://github.com/microsoft/vscode-extension-samples/tree/main/chat-sample

**Comment by jrieken** [comment]
@isidorn you need to look for `[LM] registering language model chat`,

**Comment by isidorn** [comment]
That does not show up in none of the following Output channels: Window, Extension Host, GitHub Copilot Chat, GitHub Copilot

**Comment by isidorn** [comment]
Might that be the actual bug? That with the latest version of Copilot Chat, the actual language model does not get registered÷

**Comment by jrieken** [comment]
Yeah, looks like https://github.com/microsoft/vscode-copilot/blob/c8f92afca67e8285a8e38401e41e47c00a8de295/src/extension/vscode-node/extension.ts#L143 doesn't return a token anymore. Therefore we don't register any language model

**Comment by TylerLeonhardt** [comment]
This is actually due to a Copilot Chat bug... PR out now.

**Comment by isidorn** [comment]
Verified it works now. Thanks!
