### ISSUE TITLE
crash when showing repository path tooltip in source control

### ISSUE THREAD

**Issue by TimSlechten** [microsoft/vscode#216479]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.1
- OS Version: Ubuntu 24.04 and 20.04

Steps to Reproduce:

1. go to Source Control view
2. make sure multiple repositories are listed
3. hover over the repository name to get a tooltip with the repo path

Vscode crashes 1-2 seconds after the tooltip is shown. I have the same behavior on 2 different laptops. The issue still exists when I remove all workspace settings.

**Comment by lszomoru** [comment]
@deepak1556, are you aware of any issues related to native hover?

**Comment by deepak1556** [comment]
Not aware, @TimSlechten are you using snap installation of VS Code ? Does the crash repro with `1.90.2` release ?

**Comment by deepak1556** [comment]
If the crash persists with latest stable, can you share the crash dump following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

**Comment by TimSlechten** [comment]
I'm not able to reproduce it with 1.90.2.

**Comment by deepak1556** [comment]
Seems like addressed with fix for https://github.com/microsoft/vscode/issues/212494, closing.
