### ISSUE TITLE
Opening a file with autoSave=afterDelay shows in Git status

### ISSUE THREAD

**Issue by rfgamaral** [Microsoft/vscode#21644]
- VSCode Version: 1.9.1
- OS Version: Windows 10

I have `files.autoSave: "afterDelay"` and when I open a file without making any modifications, the file will still show up in Git status as "modified". But the contents have not been modified at all. 

**How can I prevent VS Code from actually auto saving a file if no content changes have been made to the file?**

**Comment by isidorn** [comment]
Probably some whitespace got formated or end of line characters got added - since you do not see the modified content.
You should turn on format on save setting
