### ISSUE TITLE
how to change theme in visual sudio

### ISSUE THREAD

**Issue by Dhinesh1918** [microsoft/vscode#216438]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by ravm** [comment]
![Image 18 6 2024 at 14 03](https://github.com/microsoft/vscode/assets/98459176/7cf4d24c-7c4d-4b46-99c0-4a7a063ae35b)

**Comment by aeschli** [comment]
You can find more information in our documentation: https://code.visualstudio.com/docs/getstarted/themes
