### ISSUE TITLE
Allow continuous key bindings to be pressed and execute every action?

### ISSUE THREAD

**Issue by rfgamaral** [Microsoft/vscode#21642]
- VSCode Version: 1.9.1
- OS Version: Windows 10

I come from Sublime Text and I have a simple suggestion to make... Not sure if there's any kind of setting to make this possible right now, but there probably isn't.

This is probably stupid but I often switch `Ctrl+P` with `Ctrl+Shift+P`. I mean, I use the `Ctrl+P` shortcut when I actually wanted to use `Ctrl+Shift+P` and vice-versa.

What is happening in the current VS Code version is that when I press `Ctrl+P` and I realize that's not what I wanted, I quickly press `Ctrl+Shift+P`. In Sublime Text I will see the "file picker" menu followed by the "command palette" menu, which is nice. In VS Code however, I will see the "file picker" menu and when I press  `Ctrl+Shift+P` to fix my mistake, the first file with a `p` in the name will be opened. In other words, the second shortcut will take no effect.

**It's like VS Code is ignoring that I have `Ctrl+Shift` pressed while pressing the `p` with the "file picker" opened.**

Sorry if my description is not clear enough but I don't know how else to explain it.

**Comment by alexandrudima** [comment]
The input box of `ctrl+p` somehow prohibits `ctrl+shift+p` from being dispatched by the kb service.

**Comment by rfgamaral** [comment]
Yeah, that makes sense.

Do you consider this a defect or working as intended? Are you willing to improve on this behavior?

**Comment by bpasero** [comment]
@rfgamaral this is because of the following keybinding rule that you should easily be able to disable:

{ "key": "shift+cmd+p", "command": "workbench.action.quickOpenNavigatePrevious" "when": "inQuickOpen" }

(on Windows it will show you the Ctrl character).

**Comment by rfgamaral** [comment]
@bpasero That was it. Fixed it by adding the following to my `keybindings.json`:

```json
{
    "key": "ctrl+shift+p",
    "command": "-workbench.action.quickOpenNavigatePrevious",
    "when": "inQuickOpen"
}
```

Thanks guys :)
