### ISSUE TITLE
WSL Connection in code doesn't resolve PATH variable properly 

### ISSUE THREAD

**Issue by cipherswami** [microsoft/vscode#216554]
Does this issue occur when all extensions are disabled?: No

 
VS CodeVersion: 1.90.1 (user setup)
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:01:24.262Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Connect to WSL Ubuntu LTS 23.4.3 in code using remote WSL Targets.
2. In terminal you wont be able see "/snap/bin" in path variable even though it is being loaded by /etc/profile.d/apps-bin-path.sh
3. That script runs normal if run from plane terminal without using code.
4. The bug is from WSL extension I guess, initially able to bisect but it later not able to bisect this extension for some reason.
5. WSL extension is also from microsoft.com.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/6096
