### ISSUE TITLE
Method Intellisense mangled & truncated

### ISSUE THREAD

**Issue by bitcrazed** [Microsoft/vscode#2165]
Playing around with ASP.NET Core and noticed that the pop-up intellisense for one of the API's I am accessing appears to be broken in several ways:
![image](https://cloud.githubusercontent.com/assets/961950/12498200/94c53c44-c055-11e5-8374-9d1b1696aa73.png)

The text is:

1. Garbled - the API text doesn't appear to be readable end-user intellisense
1. Truncated - the API text/docs are truncated to the right

Running VS Code 0.10.6 on Windows 10 11099 on Surface Pro 4.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#13
