### ISSUE TITLE
Figure out what to do with update notification now that the Linux repos exist

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#21651]

**Comment by Tyriar** [comment]
It may be tricky to reliably check whether the user's package manager is correctly picking up the repo (what about custom repos?). Maybe we should just delay the notification by a week or so to catch these cases while at the same time not annoying people who update via package manager?

**Comment by intijk** [comment]
Could we just get this annoying notification out, instead of a number on top of the gear, how about just show a bubble and disappear? 

Users are clever enough to control their version, if I specifically choose to use old version, I think I still have the rights to **TURN THE NOTIFICATION OFF!**

**Comment by snoopdouglas** [comment]
I'm using Fedora 27 and getting bugged to install VSCode 1.19.3 from my version 1.19.2, but `dnf clean all && dnf update` says nothing to do.

**Comment by Tyriar** [comment]
Closing as out of scope, you can always disable the updates in the settings which might work better if you periodically update via a software manager. Set update mode to manual.
