### ISSUE TITLE
" - OSS" in Windows context menu

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21659]
I saw this reported on Twitter: https://twitter.com/CalvinAllen_/status/837061089544269824

![image](https://cloud.githubusercontent.com/assets/2193314/23483622/94601838-fe88-11e6-8c7a-d9e328b8ab61.png)

**Comment by marekr** [comment]
I got it too after upgrading to 1.1. Irking the living hell out of me

**Comment by King66** [comment]
![1](https://cloud.githubusercontent.com/assets/11925432/23492100/6637c7a2-ff3d-11e6-844c-520fc5387bb9.jpg)

**Comment by marekr** [comment]
Installed 1.10.1 upgrade......OSS was added back to the menu..

**Comment by Tyriar** [comment]
@marekr this should come in 1.10.2 within a few days.

**Comment by joaomoreno** [comment]
**Verification steps**

Install on Windows, making sure to choose the **context menu** option in the setup. It should say `Open with Code` only.

**Comment by isidorn** [comment]
Looks good on my win10 machine, adding verified label

![screen shot 2017-03-07 at 16 49 13](https://cloud.githubusercontent.com/assets/1926584/23664489/0617bfae-0356-11e7-8990-8f216098547b.png)
