### ISSUE TITLE
Toggle Wordwrap should toggle back to configured value

### ISSUE THREAD

**Issue by tiago-plank** [Microsoft/vscode#21656]
- VSCode Version: Code 1.10.0 (49129d126e2c3c5592cfc8a509d872067b69d262, 2017-03-01T15:59:13.140Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: All extensions disabled

---

Steps to Reproduce:

1. In user/workspace settings, set `"editor.wordWrap": "wordWrapColumn"` and `"editor.wordWrapColumn": 120`
2. Pressing ALT+Z to toggle word wrap will toggle between no wrapping at all, and wrapping at viewport width. It is only possible to go back to wrapping at 120 columns by reopening the file

I'd expect that with wordWrap set to `wordWrapColumn`, Toggle Word Wrap would toggle between no wrapping, and wrapping at `wordWrapColumn`

**Comment by ghjang** [comment]
Similar problem happens on macOS Sierra 10.12.3 with Code 1.10.2.

I have tested it on a fresh VM. No extensions were installed.

Steps to reproduce:

1. Make two plain text files containing long lines.
2. Select one text file and press 'Option + Z' shortcut to wrap lines. It seems to works.
3. Select the other text file. The word-wrap is suddenly turned off.
4. Select the text file on setp-2 again. The word-wrap is also turned off.

**Comment by GGillan** [comment]
@ghjang I am also seeing this on Windows 7, with source code files and with plain text files.
