### ISSUE TITLE
VS Code Debug Console: Variables Defined in Debug Console Not Recognized

### ISSUE THREAD

**Issue by RohollahHS** [microsoft/vscode#216579]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.1
- OS Version:  Edition Windows 11 Pro - Version 23H2

 I'm encountering an issue while debugging in Visual Studio Code. When I define a new variable in the debug console, I get an error saying the variable is not defined when I try to access it.

I always use debugging. Previously, I always set a breakpoint, and when I reached the breakpoint, I could define any new variable in the debug console. However, today I encountered this issue: I cannot define new variables in the debug console. I searched on Google, but I did not find anything.

![image](https://github.com/microsoft/vscode/assets/41644972/5cd357aa-da73-4e26-b9f2-17fb1215f1e9)
![image](https://github.com/microsoft/vscode/assets/41644972/6d6e4fa0-f654-4f0b-b294-70d4b06a0ede)

**Comment by t1m0thyj** [comment]
This also happens for me with VS Code 1.90.2 and macOS Sonoma.

**Comment by roblourens** [comment]
Is this Python? Please file on the repo for the Python debug extension, thanks
