### ISSUE TITLE
Unclickable space is still an issue

### ISSUE THREAD

**Issue by Saratii** [microsoft/vscode#216585]
Type: <b>Bug</b>

https://github.com/microsoft/vscode/issues/188407 this should not be closed as it is not fixed and was never actually addressed. I am able to recreate this issue on the newest version of vsc on ubuntu 24.0.4. `code-insiders --ozone-platform=wayland` launches it correctly but its still an unfixed bug. 

VS Code version: Code - Insiders 1.91.0-insider (b631c0aa4d30ff471171dd75376c6b49504f7ba1, 2024-06-18T08:27:24.007Z)
OS version: Linux x64 6.8.0-31-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7700X 8-Core Processor (16 x 5349)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|30.54GB (26.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
showvideot:31016890
chatpanelt:31014475
bdiig495:31013172
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31057980
nativerepl1:31071684
refactort:31073763

```

</details>

**Comment by newne** [comment]
the same problem.
```
版本: 1.91.1
提交: f1e16e1e6214d7c44d078b1f0607b2388f29d729
日期: 2024-07-09T22:08:12.169Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.8.8-060808-generic
```
hostnamectl:
```
Operating System: Ubuntu 24.04 LTS                  
Kernel: Linux 6.8.8-060808-generic
Architecture: x86-64
```

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/210624
