### ISSUE TITLE
Visual Studio Performance Slow

### ISSUE THREAD

**Issue by YufengJin** [microsoft/vscode#216596]
Type: <b>Performance Issue</b>

I am experiencing significant performance issues with Visual Studio on my computer. The editor's response time is very slow, particularly when typing. This slowdown is impacting my productivity.

More Infos:
1. My computer's overall system load is high when Visual Studio is running.
2. trials on extensions, not fixed issues:
    - I have updated all installed extensions to their latest versions.
    - Currently, I have only two extensions enabled. (Copilot/Python Debugger)
I would appreciate any guidance on troubleshooting steps I can take to resolve these performance issues.

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:43.666Z)
OS version: Linux x64 5.15.0-107-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics (16 x 4064)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|31.19GB (22.19GB free)|
|Process Argv|--force-user-env --no-sandbox --use-gl=angle --use-angle=swiftshader --crash-reporter-id fc0ccda1-d29c-42d8-8dc1-0a984fea9979|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   160	 54734	code main
    0	    32	 54736	   zygote
    0	    32	 54737	   zygote
    0	   256	 54808	window [1] (Extension: Python - 100MHurdles - Visual Studio Code)
    0	    64	 55331	     window
    0	    96	 55648	window [2] (Issue Reporter)
    0	    64	 54770	   utility-network-service
    0	    96	 54856	shared-process
    0	     0	 55659	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 55660	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   128	 54858	fileWatcher [1]
    0	    64	 54896	ptyHost
    0	     0	 54929	     /usr/bin/bash --init-file /snap/code/161/usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 55023	     /usr/bin/bash --init-file /snap/code/161/usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 55390	     /usr/bin/bash --init-file /snap/code/161/usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 55473	     /usr/bin/bash --init-file /snap/code/161/usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	   319	 55347	extensionHost [1]
    0	    96	 55365	     electron-nodejs (server.js )
    0	   415	 55513	     electron-nodejs (bundle.js )
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: Python - 100MHurdles - Visual Studio Code)
|    Folder (100MHurdles): more than 21242 files
|      File types: py(7629) pyc(7586) png(424) pyi(357) h(339) stl(229)
|                  msh(175) so(124) xml(100) txt(85)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.204.0
copilot-chat|Git|0.16.1
debugpy|ms-|2024.6.0
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vim|vsc|1.27.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
2f103344:31071589
legacy_priority:31077528

```

</details>

**Comment by MarcusSp** [comment]
See https://github.com/microsoft/vscode/issues/216593.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/212494.

Issue will be addressed in the next update this week.
