### ISSUE TITLE
Reparsing on every keypress causing slow editor experience

### ISSUE THREAD

**Issue by spintonp4** [microsoft/vscode#216590]
Type: <b>Performance Issue</b>

Open a large C++ project. Edit any C++ file and the parsing icon in the bottom status bar is displayed on every key press. As a consequence typing is really slow in the editor. I've turned off as many editor features as I can find, but still no luck in stopping the constant reparse.

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:43.666Z)
OS version: Linux x64 6.8.0-35-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (8 x 0)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 1, 1|
|Memory (System)|23.42GB (20.38GB free)|
|Process Argv|--no-sandbox --use-gl=angle --use-angle=swiftshader --crash-reporter-id 534804b0-60c7-44f3-b658-7cd9d8e6fb0d|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    96	  4479	code main
    0	     0	  4482	   zygote
    0	     0	  4483	   zygote
    0	   408	  4557	window [1] (F_NatLoop.lzz - head2 (Workspace) - Visual Studio Code)
    0	    72	 38887	window [3] (Issue Reporter)
    0	   192	  4510	   gpu-process
    0	    24	  4524	   utility-network-service
    0	   120	  4575	extensionHost [1]
    0	   360	  5152	     /home/spinton/.vscode/extensions/ms-vscode.cpptools-1.20.5-linux-x64/bin/cpptools
    0	    24	  5237	     /snap/code/161/usr/share/code/code /snap/code/161/usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=4575
    0	    48	  4590	shared-process
    0	     0	 39805	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   120	  4591	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (F_NatLoop.lzz - head2 (Workspace) - Visual Studio Code)
|    Folder (head2): more than 23774 files
|      File types: C(6883) h(2345) expect(2295) cc(1847) cpp(1725) cxx(531)
|                  lzz(357) cm(335) prj(315) out(305)
|      Conf files: makefile(115) launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: lldb(5) python(2) cppdbg;
```

</details>
<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
bpftrace|bpf|0.2.1
xml|Dot|2.5.1
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
jinjahtml|sam|0.20.0
graphviz-interactive-preview|tin|0.3.5
vscode-lldb|vad|1.10.0
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
newcmakeconfigv2:31071590
legacy_priority:31077528

```

</details>

**Comment by gjsjohnmurray** [comment]
Do you still have the problem after updating to 1.90.2?

**Comment by Kossak-esky** [comment]
I had the same experience. Moving cursor down 1 line took about 1 second! I thought some extension might be the cause, but upgrading to 1.90.2 fixed the issue for me.

**Comment by spintonp4** [comment]
Yes, I'm on 1.90.2 now and the problem seems to have gone. As I type, the code and gnome-shell processes are taking far less CPU (they were up to about 300% CPU if I held down a key).

**Comment by spintonp4** [comment]
Yes, I'm on 1.90.2 now and the problem seems to have gone. As I type, the `code` and `gnome-shell` processes are taking far less CPU (they were up to about 300% CPU if I held down a key).
