### ISSUE TITLE
Highlight current hitted breakpoint

### ISSUE THREAD

**Issue by fr43nk** [microsoft/vscode#216592]
If I debug my software project I sometime have a lot of active breakpoints. If one breakpoint gets hit, from time to time I want to disable it. But in the breakpoint list, it is hard to find, because it is not highlighted as active or the current hit. Is it possible to integrate such a feature?

Best regards,
Frank

![image](https://github.com/microsoft/vscode/assets/3279247/6a8ae30c-2ec1-4c17-898b-84aa86e80b0e)

**Comment by fr43nk** [comment]
Any news about this request?

**Comment by roblourens** [comment]
vscode supports this, you can file an issue on the debug extension to support `hitBreakpointIds`
