### ISSUE TITLE
The size of the vertical scroll bar in the integrated terminal does not match the size of the editor scroll bars

### ISSUE THREAD

**Issue by uRohan** [microsoft/vscode#216521]
Type: <b>Bug</b>

Steps to Reproduce:

1. Open Visual Studio Code.
2. Open the integrated terminal (usually accessible via `View` > `Terminal`).
3. Compare the vertical scroll bar size of the integrated terminal to the vertical scroll bar size of the editor.

Expected Behavior:

The size of the vertical scroll bar should be consistent. The vertical scroll bar in the integrated terminal should match the size of the vertical scroll bar in the editor.

Here's what it looks like:

| Dark Modern | Light Modern |
| ----------- | ------------ |
| ![Screenshot from 2024-06-18 18-43-46](https://github.com/microsoft/vscode/assets/11392016/27ee1312-7a1a-4cc0-9b55-509b99beceb9) | ![Screenshot from 2024-06-18 18-42-53](https://github.com/microsoft/vscode/assets/11392016/17105a71-1e84-46db-a744-9dbfbf45fb6a) |

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:43.666Z), Code - Insiders 1.91.0-insider (b631c0aa4d30ff471171dd75376c6b49504f7ba1, 2024-06-18T08:27:24.007Z)
OS version: Linux x64 6.5.0-41-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (8 x 3092)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|7.63GB (3.93GB free)|
|Process Argv|--force-user-env --no-sandbox --crash-reporter-id e8f86e41-3f8c-4aac-8c41-cb59fad957aa|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
showvideot:31016890
chatpanelt:31014475
da93g388:31013173
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupyter:31046869
nb_pkg_only:31057982
nativerepl1:31071684
refactort:31073763

```

</details>

**Comment by meganrogge** [comment]
There's less space in the terminal, so a thinner scrollbar makes sense here IMO, @Tyriar reopen if you disagree

**Comment by Tyriar** [comment]
Something changed, it never used to be like this:

![image](https://github.com/user-attachments/assets/bdfca028-b1dc-419c-b6cd-f6c8b7973966)

Maybe an Electron update changed what scroll bar styling is available?

**Comment by meganrogge** [comment]
May version is the same:

![Screenshot 2024-06-19 at 7 03 16 AM](https://github.com/user-attachments/assets/02e1e350-a26b-4213-8b97-86e7fb2694b7)

**Comment by Tyriar** [comment]
I think it's related to an Electron/Chrome update breaking how we styled scroll bars.

This doesn't seem easy to fix. The real fix here is to add API to xterm.js to allow the use of vscode's scrollable element.

**Comment by s-h-a-d-o-w** [comment]
> There's less space in the terminal, so a thinner scrollbar makes sense here IMO

This is a significant accessibility problem. Not everybody can use a scroll wheel.
Thin scroll bars that can't be configured to be wider should not be acceptable for any project.

**Comment by Tyriar** [comment]
I disagree that it's _significant_, just wait until you try use one of our sashes to resize panes if you think this is hard to hit which I think has a 3px target:

![Image](https://github.com/user-attachments/assets/d07f7ae3-bff3-456b-ba65-b32719538adc)

Especially since there are alternate options (wheel, keybindings). Also the mouse target actually seems to be wider than the slider's size.

Regardless, here's `scrollbar-width: thin` with decorations:

![Image](https://github.com/user-attachments/assets/6a817309-d1df-4bbb-9d94-f7e046ea069c)

And `scrollbar-width: auto`:

![Image](https://github.com/user-attachments/assets/11f3b8e0-601a-4d2b-9fdc-e8716e08f4e5)

It's a shame this happened at all as the decorations were perfectly sized for the old scroll bar. `auto` does look better now and closer to the editor so we should go with that imo. Hopefully there aren't any side effects to making this change.

**Comment by s-h-a-d-o-w** [comment]
> just wait until you try use one of our sashes to resize panes if you think this is hard to hit

Resizing panes is something that I do maybe once a month. But this is why I have a voice command for resizing windows to a specific size, since I can't avoid that as well.

> Hopefully there aren't any side effects to making this change.

Thanks, looking forward to this fix.
