### ISSUE TITLE
1.90 crashes on ubuntu 20.04 under tigervnc X server

### ISSUE THREAD

**Issue by cleemesser** [microsoft/vscode#216569]
s

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: Xubuntu 20.04.3
This is basically a headless server that runs the vncserver. It has several nvidia gpus on it so it is possible that is causing some of the problem. Steps to Reproduce:

1. install Xubuntu 20.04.3 (x86_64/amd64) as "host A"
2. download the "Debian, ubuntu" ".deb" option from [the microsoft visual code download page](https://code.visualstudio.com/download)
```
$ apt install ./code_1.90.1-1718141439_amd64.deb 
$ sudo apt install tigervnc-standalone-server
```
3. on the command line, start the vncserver:
```
$ vncserver :1 
```
4. on another host B install tigervnc-viewer or TurboVNC viewer
6. from host B login to the vnc-server desktop on host A using vncviewer
7. from the command line in the virtual desktop of host A, type 
```
code <argument options as described below>
```
without any arguments, nothing happens for 10-30 seconds, then sometimes I get a "application has failed, send information to developer alert. The VS Code windows never appear.

I also have been having problems with crashing on ubuntu 20.04.3 LTS since 1.90 came out. I run code on my xubuntu desktop atop a vncserver X session (tigerVNCor TurboVNC ). VS code has worked on this system using code version 1.89.1 (https://github.com/microsoft/vscode/commit/dc96b837cf6bb4af9cd736aa3af08cf8279f7685 x64). And, I have been using prior versions of code successfully for a year or two at least in the same desktop.

But with anything in the 1.9.0 1.9.1 range I get an immediate failure to launch.
```
$ sudo apt upgrade code  # using deb package from repo 
# 
$ code --version --verbose
1.90.1
611f9bfce64f25108829dd295f54a6894e87339d
x64

$ code --verbose
<--- Last few GCs --->


<--- JS stacktrace --->



#
# Fatal process out of memory: Oilpan: CagedHeap reservation.
#
``` 

### **Further tests:**
Unfortunately, I get same result for: either code or code-insiders for each of the following arguments. I also tried combing --disable-extensions with some of the others
```
$ code --verbose --disable-gpu
$ code --verbose --disable-extensions
$ code --verbose --disable-extensions
$ code --verbose --in-process-gpu
$ code --verbose --user-data-dir /tmp/code-1-90
$ code --verbose --use-gl=swiftshader

### update for 1.90.2 and 1.91.0-insider 
still no joy, same results

**Comment by deepak1556** [comment]
Can you test if the issue repros with our [exploration build](https://vscode.download.prss.microsoft.com/dbazure/download/exploration/cdbcba35e4c9789e77dfe75692696d3771262219/code-exploration_1.91.0-1718857945_amd64.deb). If it does, please attach the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

**Comment by cleemesser** [comment]
No luck getting you a dmp file so far. Sorry.
```
sudo dpkg -i code-exploration_1.91.0-1718857945_amd64.deb 
```
```
code-exploration --crash-reporter-directory /home/clee/Downloads/codecrash --verbose --disable-extensions
<--- Last few GCs --->


<--- JS stacktrace --->



#
# Fatal process out of memory: Oilpan: CagedHeap reservation.
#
----- Native stack trace -----

```
This does not produce a .dmp file 


There is a gnome/ubuntu crash report which I sent to "the developers" unfortunately, I can't just save it or copy-paste it from the pop up panel. I can type out a little from it. It looks like the bottom of the stack traces ends at a null 0x00 address. The p_thread trace also does this but 

### side info
Possibly related, when i run google-chrome-stable (ver 1.90.2-171875186) it runs in this tigervnc environment but gives the message:
```
google-chrome-stable 
[3317485:3317485:0623/172800.702640:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
```

**Comment by cleemesser** [comment]
I will close it because it only happens on one machine with one account. I don't know what causes it but a fresh install or account then code works on tigervnc
