### ISSUE TITLE
Policy request - Extension allow-list/deny-list

### ISSUE THREAD

**Issue by kylebavis** [microsoft/vscode#216542]
Per this page: https://code.visualstudio.com/docs/setup/enterprise

I'm requesting that policy settings be made available to do the following:

- Force installation of specific extension(s)
- Deny the installation of specific extension(s)

VS Code has a significant footprint in my environment, and this piece makes me concerned about extensions as a vector for malicious code: https://medium.com/@amitassaraf/the-story-of-extensiontotal-how-we-hacked-the-vscode-marketplace-5c6e66a0e9d7

**Comment by tamuratak** [comment]
Might be duplicate of #84756

**Comment by kylebavis** [comment]
Agreed. I didn’t see that one when I checked before submitting.
