### ISSUE TITLE
Scrollback access freezes VSCode

### ISSUE THREAD

**Issue by jvacek** [microsoft/vscode#216509]
Type: <b>Bug</b>

I've set my scrollback to 10000 lines which shouldn't be that much.

When I have my terminal open, and I either resize the window or I change the size of the terminals, the entire window freezes.

The same thing happens when I change the settings for the amount of scrollback lines.

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:44:54.914Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 40e3f71a-08a9-4079-80f2-c2e9763a3415|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.2
increment-selection|alb|0.2.0
vscode-sqlite|ale|0.14.1
atlascode|atl|3.0.10
vscode-django|bat|1.15.0
multi-cursor-case-preserve|Car|1.0.5
ruff|cha|2024.26.0
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|3.0.10
vscode-dash|dee|2.4.0
python-environment-manager|don|1.2.4
gitlens|eam|15.1.0
EditorConfig|Edi|0.16.4
shell-format|fox|7.2.5
copilot|Git|1.204.0
copilot-chat|Git|0.16.1
gitlab-workflow|Git|4.16.0
cloudcode|goo|2.12.0
terraform|has|2.30.2
vscode-test-explorer|hbe|2.21.1
vscode-edit-csv|jan|0.9.1
vscode-peacock|joh|4.2.2
vsc-python-indent|Kev|1.18.0
vscode-python-test-adapter|lit|0.8.2
bash-ide-vscode|mad|1.41.0
rainbow-csv|mec|3.12.0
djlint|mon|2024.6.0
autopep8|ms-|2024.0.0
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.6.0
flake8|ms-|2023.10.0
isort|ms-|2023.10.1
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
test-adapter-converter|ms-|0.1.9
vsliveshare|ms-|1.0.5932
autodocstring|njp|0.6.1
django-test-runner|Pac|3.0.4
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
shellman|Rem|5.7.0
code-spell-checker|str|3.0.1
even-better-toml|tam|0.19.2
shellcheck|tim|0.37.1
autoflake|Tru|0.0.3
errorlens|use|3.18.0
vscodeintellicode|Vis|1.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
legacy_priority:31077528

```

</details>

**Comment by Tyriar** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
