### ISSUE TITLE
Add missing deb package dependencies when installing on Debian

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21654]
https://news.ycombinator.com/item?id=13768705

**Comment by intdel** [comment]
Other dependencies that are missing are:
 libasound2, libxss1, libgconf2.0

**Comment by Tyriar** [comment]
apt-transport-https will probably go into the recovery build. I'd be more comfortable putting the other deps into a release earlier on to get some additional testing https://github.com/Microsoft/vscode/issues/13089

**Comment by Tyriar** [comment]
@intdel thanks, https://github.com/Microsoft/vscode/issues/13089 was tracking those (and more)

If they're blocking installation on Debian I'll try get it into the recovery build with this then. Are you using regular 64-bit Debian?

**Comment by intdel** [comment]
Yes, I am running Debian 64 bit testing. It doesn't block it but it will just give you an error when launching "code". Like "libxss.so missing" or something like that.

**Comment by Tyriar** [comment]
@intdel so turns out the right fix for this is to install the repository using the http protocol, not https. This appears to be how Debian's system packages are installed and since we have a signing key which is installed via https (either by downloading deb or via curl) no man-in-the-middle attacks should occur. Further reading: http://askubuntu.com/a/352972

As for the other packages I'll defer to #13089, I also don't think this meets the bar for the recovery build since it's pretty easily fixed and should be obvious what went wrong if it happens.
