### ISSUE TITLE
Environment variable $DISPLAY removed when using remote ssh extension in linux 

### ISSUE THREAD

**Issue by Turdari** [microsoft/vscode#216671]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2
5437499feb04f7a586f677b155b039bc2b3669eb
x64

- OS Version: ubuntu 22.04 (vanilla in existing HW, not WSL, not VM)

Steps to Reproduce:
1. install vscode and enable remote ssh 
2. add new host with ssh -X username@host 
3. connect.

following above instruction, can easily met status where $DISPLAY environment variable removed. 
If we connect with integrated terminal + 'ssh -X username@host', $DISPLAY env is alive and no problem detected.
but if we connect with ssh-remote + integrated terminal, $DISPLAY variable got removed.
this is causing issue when using vscode in linux environment, Xforwarding is actually basic operation, and many people having same issue with this.

Example )
https://stackoverflow.com/questions/76309713/vscode-remote-ssh-setting-display-variable

looks like something in ssh-remote override $DISPLAY variable when connecting with SSH.

**Comment by Turdari** [comment]
some more add on Steps to Reproduce

1. install vscode and enable remote ssh
2. add new host with ssh -X username@host
3. connect.
4. Terminal -> New Terminal

**Comment by a-usr** [comment]
Just to clarify, is the $DISPLAY environment variable supposed to live on the remote machine or on the local machine

**Comment by a-usr** [comment]
And it works when you do ssh-remote + integrated terminal and manually set $DISPLAY ?

**Comment by Turdari** [comment]
Hmm... actually, that "works" not properly works.

If I connect with other shell (for example bash terminal) and connect with ssh -X,  local & remote creates display connection rule, between local and remote. that is what we called $DISPLAY in remote machine. 

what we call "manually setting $DISPLAY" is borrowing those connection temporary.
When we lost other shell (for example bash terminal) which maintaining that connection,
$DISPLAY broke and not working any more.

**Comment by Turdari** [comment]
for example )
 ssh-remote + integrated terminal  connected to remote get's 
 $DISPLAY variable of "" which is null
 
 in this case, what how we should set $DISPLAY ?
 answer is we don't know.
 
 to get answer, we need to prepare another ssh connection, which is not "ssh-remote + integrated terminal "
 and after ssh connection, we get proper $DISPLAY
 and copy it to our "ssh-remote + integrated terminal " to make display work.
 
 $DISPLAY is dynamic in ssh connection so above procedure is mandatory.
 if you think this situation is weird, please care.

**Comment by a-usr** [comment]
Could you check wether `remote.SSH.enableX11Forwarding` is enabled?

**Comment by a-usr** [comment]
also `remote.SSH.enableAgentForwarding`

**Comment by Turdari** [comment]
Hi, I'm here to post sorry text.

two configurations are all enabled,
remote.SSH.enableX11Forwarding
remote.SSH.enableAgentForwarding

but, after restarting remote for test, "ssh-remote + integrated terminal" works with no problem.
it creates proper $DISPLAY variable and everything works fine.
maybe it was just initialization problem in remote server.

**Comment by Turdari** [comment]
May I close this issue?

**Comment by a-usr** [comment]
You may.
