### ISSUE TITLE
Value of showing previous inline chat interactions?

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#216694]
Right now the inline chat shows all the previous interactions I had. With my questions and the responses.

What is the actual value for the user of seeing this? For me it is random responses from the past (that do not actually have the code change I am interested in).

Right now I can not click on it to "go back to that state". Would that be a potential value of showing this?

![Image](https://github.com/user-attachments/assets/0c6e0ce5-749a-458b-a205-69f83dc9ce4a)

**Comment by daviddossett** [comment]
I like the idea of framing these as a traversable history. Kind of like Timeline, in a way. The chat is useful for explaining fixes and asking natural language questions (read: not generating edits). I agree that confirming every edit with the typical "Sure!.." isn't all that useful.

I could see a world where changes were explained so users didn't have the burden of reading a large diff every time. Maybe that's where @jrieken is headed?

**Comment by jrieken** [comment]
> What is the actual value for the user of seeing this? For me it is random responses from the past (that do not actually have the code change I am interested in).

That's a misunderstanding. The last reply and code edit is always based on the whole history of the current conversation, not just the last prompt. 


> Right now I can not click on it to "go back to that state". Would that be a potential value of showing this?

It's buggy right now but in theory you can (or should be able) to remove requests and the editor reverts to that state. Tho, that needs work, esp when removing an in-between request

**Comment by isidorn** [comment]
> That's a misunderstanding. The last reply and code edit is always based on the whole history of the current conversation, not just the last prompt.

Thanks for clarifying. Do you also include previous responses from the model? Or just the user requests?

> It's buggy right now but in theory you can (or should be able) to remove requests and the editor reverts to that state. Tho, that needs work, esp when removing an in-between request

Cool. Happy to give it another try once ready.

**Comment by jrieken** [comment]
> Thanks for clarifying. Do you also include previous responses from the model? Or just the user requests?

Depends on the intent/handler but usually pass the current code and say something like "this code the outcome of the following conversation, now the user asks XYZ"

**Comment by jrieken** [comment]
Closed without change. The rendering is more compact and I believe we have clarity/alignment on how history and inline chat works
