### ISSUE TITLE
The event.waitUntil not working

### ISSUE THREAD

**Issue by hans000** [microsoft/vscode#216676]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90
- OS Version: macos 12.6.3

Steps to Reproduce:

this is a extension code. the purpose is i want to prevent the document to save after 10s. but it not working. why?

``` ts
    vscode.workspace.onWillSaveTextDocument(async (event) => {
      console.log('start')
      event.waitUntil(new Promise((resolve) => {
        setTimeout(() => {
          console.log('end')
          resolve()
        }, 10_000);
      }))
    });
```

**Comment by gjsjohnmurray** [comment]
API doc describes a 1.5 second maximum.

**Comment by hans000** [comment]
> API doc describes a 1.5 second maximum.

so, this code `event.waitUntil(Promise.reject())` also not working. that's the feature not bug?

**Comment by jrieken** [comment]
> so, this code event.waitUntil(Promise.reject()) also not working. that's the feature not bug?

Feature! In short, you cannot prevent saving for long and cannot prevent saving with an errors. Here are the full docs: https://github.com/microsoft/vscode/blob/cb9d1e4589a05bed292f298acba7369e812f8cf1/src/vscode-dts/vscode.d.ts#L13450-L13463
