### ISSUE TITLE
Exclude search results by string

### ISSUE THREAD

**Issue by alexandernst** [microsoft/vscode#216698]
I'd like to be able to filter search results (`ctrl + shift + f`) by text (bonus points if I can apply multiple filters).
Currently I can filter the results by files/folders (paths), but there is no way to filter by text.

For example, let's say that I have multiple files containing one or more of the following strings:

```
foo.bar.xyz
foo.bar.abc
foo.bar.ijk
foo.bar.qwe
foo.bar.poi
```

I'd like to be able to search `.bar` and **exclude** `bar.xyz`, which would give me all lines in all files that contain `foo.bar.abc`, `foo.bar.ijk`, `foo.bar.qwe` and `foo.bar.poi`.

This would be the same as running `grep ".bar" | grep -v "foo.bar"`.

PD: I know this particular example could be workaround-ed using regex search, but regex search just isn't easy to do on a large/complex strings, or with multiple exclusion rules (`grep ".bar" | grep -v "foo.bar" | grep -v "foo.abc"`)

**Comment by andreamah** [comment]
We likely wouldn't make new UI elements for this type of advanced search. Once the `FindTextInFiles` API is finalized, I would prefer that this gets contributed via extension. https://github.com/microsoft/vscode/issues/59924
