### ISSUE TITLE
slowly when ts organization imports

### ISSUE THREAD

**Issue by huangwei1024** [microsoft/vscode#216677]
Type: <b>Performance Issue</b>

"editor.formatOnSave": true, 
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": "explicit",
        "source.organizeImports": "explicit"
    },

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900KF (32 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.81GB (31.38GB free)|
|Process Argv|--crash-reporter-id b2acc847-87e1-4abf-8c39-1ae181723248|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   204	 14120	code main
    0	   743	  5828	window [2] (Running Extensions - client - Visual Studio Code)
    0	   180	 11868	fileWatcher [2]
    0	   151	 54340	shared-process
    0	   121	 69460	     "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork" ms-vscode.pwa-chrome "{\"common.vscodemachineid\":\"41e98cc8cde9e5ce56debfc1483448844e571b6e768d000556ec6d7ad5c1b808\",\"common.vscodesessionid\":\"d95806c0-e581-4897-a2da-add37a285ae91718855923277\"}" 0c6ae279ed8443289764825290e4f9e2-1a736e7c-1324-4338-be46-fc2a58ae4d14-7255
    0	   123	 58004	window [3] (问题报告程序)
    0	   390	 58556	   gpu-process
    0	   112	 58956	fileWatcher [1]
    0	   306	 62328	window [1] (limit_gift.py - h5_server - Visual Studio Code)
    0	   122	 66452	ptyHost
    0	    27	 18300	     conpty-agent
    0	    27	 48372	     conpty-agent
    0	   111	 50764	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	   102	 69388	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	   450	 68092	extensionHost [1]
    0	    50	 68648	     c:\Python310\python.exe c:\Users\hwisk\.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\lsp_server.py
    0	    30	 44668	       C:\Windows\system32\conhost.exe 0x4
    0	   270	 70632	     electron-nodejs (bundle.js )
    0	    73	 68804	   utility-network-service
    0	    47	 68836	   crashpad-handler
    0	   702	 69464	extensionHost [2]
    0	  1000	 19448	     electron-nodejs (tsserver.js )
    0	  1091	 63420	     electron-nodejs (tsserver.js )
    0	   122	 27668	       electron-nodejs (typingsInstaller.js typesMap.js )
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Running Extensions - client - Visual Studio Code)
|  Window (limit_gift.py - h5_server - Visual Studio Code)
|    Folder (client): more than 34717 files
|      File types: json(6061) meta(3930) ts(1582) zip(119) manifest(53)
|                  old(25) js(20) log(12) ldb(9) map(8)
|      Conf files: tasks.json(6) launch.json(1) settings.json(1)
|                  package.json(1) tsconfig.json(1)
|      Launch Configs: debugpy node chrome
|    Folder (h5_server): 1391 files
|      File types: go(708) py(289) json(33) empty(16) md(14) h(8) sh(7)
|                  tmpl(7) conf(5) yml(4)
|      Conf files: launch.json(1) settings.json(1) makefile(1)
|      Launch Configs: debugpy;
```

</details>
<details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
bracket-pair-toggler|dzh|0.0.3
gitlens|eam|15.1.0
vsc-material-theme|Equ|34.4.0
vsc-material-theme-icons|equ|3.6.1
prettier-vscode|esb|10.4.0
code-runner|for|0.12.2
copilot|Git|1.204.0
copilot-chat|Git|0.16.1
remotehub|Git|0.62.0
go|gol|0.41.4
todo-tree|Gru|0.0.226
ts-debug|kak|0.0.6
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.1
vscode-language-pack-zh-hans|MS-|1.90.2024061209
vscode-dotnet-runtime|ms-|2.0.6
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.369.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
azure-repos|ms-|0.38.0
cmake-tools|ms-|1.18.42
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
makefile-tools|ms-|0.9.10
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
sublime-keybindings|ms-|4.1.10
vetur|oct|0.37.3
indent-rainbow|ode|8.3.1
multi-command|ryu|1.6.0
swdc-vscode|sof|2.7.13
lua|sum|3.9.3
rainbow-bracket|tal|1.0.2
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
vscode-gradle|vsc|3.14.1
vscode-icons|vsc|12.8.0
volar|Vue|2.0.21
gitblame|wad|11.0.1
cc-plugin-debugger|xuy|0.0.1
pretty-ts-errors|Yoa|0.5.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
legacy_priority:31077528

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
