### ISSUE TITLE
Debug session dropdown is not available when debug toolbar is set to commandCenter

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#216601]
Normally I can change between active debug sessions using this dropdown in the debug toolbar:

![Screenshot 2024-06-19 110943](https://github.com/microsoft/vscode/assets/1078012/169e4d25-37f3-42f5-bb49-af6bd7994856)

However if I set the toolbar to be in "commandCenter", this dropdown vanishes and there's no way (that I can find) to change between sessions.

![Screenshot 2024-06-19 110954](https://github.com/microsoft/vscode/assets/1078012/a245421f-b417-48d0-8563-6ec9f02e03f7)

**Comment by gjsjohnmurray** [comment]
See also #194881
