### ISSUE TITLE
Consider reducing/tweaking the word highlighting delay

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#216632]
Currently there is a hardcoded 250ms delay between cursor movement and triggering the word highlighting:

https://github.com/microsoft/vscode/blob/3cb3a37238888e5546e1c406d8bb6a99ea955098/src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts#L731

https://github.com/microsoft/vscode/blob/3cb3a37238888e5546e1c406d8bb6a99ea955098/src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts#L200

If we reduce this the editor feels a lot snappier:

![Recording 2024-06-19 at 07 06 26](https://github.com/user-attachments/assets/4b2f7404-409d-47d3-af7a-cfa860a0d485)

Reducing it in all case does lead to a less than optimal situation where holding down `down` for example will cause find highlighting to flicker a lot. I think ideally we would instantly or near instantly highlight, _unless_ a key is held down. So in particular, a cursor move via _pressing_ a key or clicking the mouse would be instant.

**Comment by Tyriar** [comment]
My comments from standup:

- Maybe this should be an `experimental.` setting for now as we're not sure on the final shape of the setting we want
- Should the setting be a delay setting where it's a number instead of a boolean?
- I'd love this to be the default, or at least lower the default delay eventually. This would need some team self-hosting and consensus. I believe this will go a long way in improving perceived performance.

**Comment by Yoyokrazy** [comment]
> Maybe this should be an experimental. setting for now as we're not sure on the final shape of the setting we want

This was the only point I found trouble with ironically, as it seems like there's a number of different standards for implementing settings. In `EditorOptions` we don't have a way to define experimental settings and I believe this would be the correct place to define the setting.

The only place I see `editor.experimental.xyz` is in `editorConfigurationSchema.ts` and that was causing issues with reading the schema. Clearly I've missed something there in getting the setting hooked up, but overall I think there's a broader issue of editor settings not having a clear way to define them and list them as experimental. 

It think the shape makes a lot of sense to be granular and it mirrors the rest of the delay settings nicely, so I don't think there's issue with just introducing the setting and defaulting to 250 for now. It's tagged experimental so we can play with reducing the default down to 0. I think it'd be reasonable to put this inside our workspace .vscode settings file

**Comment by Yoyokrazy** [comment]
Verification steps:
- Using [this setting](vscode-insiders://settings/editor.occurrencesHighlightDelay), configure wordhighlighting delay to have a value less than default (<250)
- Click through the file comparing the highlight responsiveness to the default (it should feel noticeably "snappier")
- Hold up or down arrows, ensure that the highlight request is debounced and only fires when you have released the key
