### ISSUE TITLE
ms-mssql.mssql extention not returning result set

### ISSUE THREAD

**Issue by tofy** [Microsoft/vscode#21661]
- VSCode Version: Code 1.10.0 (49129d126e2c3c5592cfc8a509d872067b69d262, 2017-03-01T15:59:13.140Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|mssql|ms-mssql|0.2.1|
|csharp|ms-vscode|1.7.0|;

---

Steps to Reproduce:

1. type any select query
2. right click > Execute Query

**Comment by tofy** [comment]
it was working before the last update

**Comment by kevcunnane** [comment]
@egamma - we've just verified this is happening to the MSSQL extension (which we ship). This does not repro on the Insiders build which we were testing against. However it does repro in the official 1.10 release for:
- Viewing our changelog. In this case we call the following to open a static HTML file on disk:
```
       // get the URI for the release notes page
        let docUri = vscode.Uri.file(
            this._context.asAbsolutePath(
                'out/src/views/htmlcontent/dist/docs/index.html'));

        // show the release notes page in the preview window
        vscode.commands.executeCommand(
            'vscode.previewHtml',
            docUri,
            vscode.ViewColumn.One,
            'mssql for VS Code Release Notes');
```
- Our results view (which uses the same API pattern, but uses it against a local Node.js server)

This is completely blocking our extension right now. Any assistance would be appreciated

**Comment by kieferrm** [comment]
A fix is being prepared.

**Comment by kieferrm** [comment]
The issue was fixed with https://github.com/Microsoft/vscode/commit/594bc2587657bf5467b28e89633ac621aa0e85ff.
