### ISSUE TITLE
allow to enable minimap only for files longer than X lines

### ISSUE THREAD

**Issue by capaj** [Microsoft/vscode#21663]
I'd love to use a newly released minimap, but only for files which are roughly 3 times the height if my monitor. I'd imagine to be able to set it somehow like this:

```
"editor.minimap.enabled": 225, // since my monitor displays 75 lines roughly
```

Do you think this is worth working on? This should be doable PR for me if it is a desirable feature.

**Comment by noinkling** [comment]
Or even just when the current file exceeds the height of the editor, since for small files it's kinda pointless and just takes up horizontal space.

Was going to request this myself.
