### ISSUE TITLE
Terminal links - chrome devtools link isn't clickable

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#21668]
These links look like `chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=localhost:9229/79e1ddbc-e79f-48c0-953d-60482c6ae5e7` and are only underlined from the first slashes to the first `&`. Not sure if the problem is the `chrome-devtools` protocol, or @ character, or something else

**Comment by Tyriar** [comment]
@roblourens they should no longer be highlighted from tomorrow's build as links are validated now. Does support for such a link make sense? Would telling Chrome to load a link like that work?

**Comment by roblourens** [comment]
I think supporting them makes sense and would be very awesome. To get them to be highlighted, I need to change `chrome-devtools` to `http`, and add a `.com` on devtools, so I guess we would need it to recognize those as valid parts of a url.

**Comment by Tyriar** [comment]
Is the desired behavior to just open it in the default web browser (and assume it's Chrome?). I'm not sure how reliable `google-chrome` is on the PATH (does it change with canary, same on all platforms, etc).

**Comment by roblourens** [comment]
I think that opening with the default browser would be expected (ie treating it like any other link), even though it probably won't work in a non-chrome browser.

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/599

**Comment by aponzani** [comment]
+1 for this to be supported (i.e. opening the link in default browser).  FYI, this is the type of debug link produced by running `node --inspect --debug-brk mynodefile.js` so it would make for a very nice workflow to aid in debugging node scripts from VS Code.

However, FWIW, this link doesn't appear to be clickable in my zsh shell outside of VS Code either.

**Comment by Tyriar** [comment]
If anyone wants to help with this you can add support here: https://github.com/sourcelair/xterm.js/blob/master/src/Linkifier.ts#L18

Basically you need to allow the new protocol and ensure it's linkified (make sure you can use it without a top level domain; .com, etc.).

**Comment by Tyriar** [comment]
Tracking in https://github.com/xtermjs/xterm.js/issues/583
