### ISSUE TITLE
on enter in the terminal, terminal chat should hide and not prevent terminal command execution

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#216624]
Steps to Reproduce:

1. open terminal chat 
2. use chat response as guide to type command
3. hit enter to execute command
4. 🐛 it won't execute and chat remains open

https://github.com/user-attachments/assets/94d045d0-259b-4f37-a46f-ded813a9c153

**Comment by Tyriar** [comment]
Looks like `terminalChatFocus` is true when it shouldn't be:

```
2024-06-26 08:57:18.110 [info] [KeybindingService]: \ From 31 keybinding entries, matched workbench.action.terminal.chat.makeRequest, when: terminalChatFocus && terminalHasBeenCreated && !inlineChatEmpty && !terminalChatActiveRequest || terminalChatFocus && terminalProcessSupported && !inlineChatEmpty && !terminalChatActiveRequest, source: built-in.
```

**Comment by rzhao271** [comment]
Terminal command execution works now, but the terminal chat still shows for step 4.

![Terminal chat showing under hand-typed and executed command](https://github.com/user-attachments/assets/492d747e-9f82-4e38-9c8d-55b66c63c5f2)

**Comment by Tyriar** [comment]
Chat remains open is fine imo, @meganrogge and I should have a discussion about this if she disagrees. Marking as verified since the primary bug was fixed.

**Comment by meganrogge** [comment]
When using this, my flow is often:

- get response from chat
- there are parameters I have to fill in manually, so I don't use `run` or `insert`
Example:
![Image](https://github.com/user-attachments/assets/5957cd88-262e-4145-81b6-b366e9a78267)
- I type the text based on the response's suggestion and hit enter

I'm not sure it's useful to keep chat open for this case. @Tyriar what do you think?
