### ISSUE TITLE
When the GitHub Pull Request & Issues extension switched to using this new Authentication API it lost the support for enterprise GitHub deployments. I assume that's because the above API is missing something fundamental for that specific style of access (API key based instead of username/password based?)

### ISSUE THREAD

**Issue by limzk8906** [microsoft/vscode#216604]
When the GitHub Pull Request & Issues extension switched to using this new Authentication API it lost the support for enterprise GitHub deployments. I assume that's because the above API is missing something fundamental for that specific style of access (API key based instead of username/password based?)

What are the plans for updating the API to add in what was missing for GitHub enterprise auth? I assume other extensions will need similar capabilities as well.

_Originally posted by @neilenns in https://github.com/microsoft/vscode/issues/88309#issuecomment-631122431_
            
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/pull/211826
- [ ] https://github.com/microsoft/vscode/issues/216421
```

**Comment by TylerLeonhardt** [comment]
@limzk8906 can you please elaborate on what you mean by api key based auth?

We support the device code flow, and if you cancel the device code flow, it gives you an option to put in a PAT.
