### ISSUE TITLE
Commands Documentation

### ISSUE THREAD

**Issue by arb** [Microsoft/vscode#21660]
Is there a list of *all* the supported vscode commands? I've reviewed the complex commands, but I feel like there are many more and haven't been able to find these documents.

**Comment by gregvanl** [comment]
You can see a list of the most commonly used commands at [Key Bindings](https://code.visualstudio.com/docs/getstarted/keybindings) and the platform specific Keyboard Shortcut Reference PDFs (example for Windows https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf).
For a full list of commands including those which are not currently bound to a keyboard shortcut, you can open keybindings.json (Preferences: Open Keyboard Shortcuts) and see the commented list at the bottom (// Here are other available commands:).
Hopefully this answers your question.
