### ISSUE TITLE
Inline chat - hover feedback for "title buttons" needs more breathing room

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#216692]
Right now the hover feedback seems to take 105% of the available space.
Looks a bit cramped to me. Can we give it some breathing room so it does not touch the other elements so closely.

![Image](https://github.com/user-attachments/assets/191723c3-13ae-44a1-87b8-aea63d31119c)

For example, here's the hover feedback of inline chat actions

![Image](https://github.com/user-attachments/assets/146b256e-3915-4c01-aa3c-af891a2bf9c9)

**Comment by daviddossett** [comment]
Agreed—it looks like it is styled like that once a request has been made, but not in the initial state. I wasn't able to figure out how to align them without diving deeper.

![Image](https://github.com/user-attachments/assets/f37b9508-f577-4f7b-ab9e-cc1300ad321e)

![Image](https://github.com/user-attachments/assets/d27bd965-e27f-4037-8064-346dd739e5e7)
