### ISSUE TITLE
Undeclared dependency shows problem/warning for extraneous module

### ISSUE THREAD

**Issue by tyrsius** [Microsoft/vscode#21666]
- VSCode Version: Version 1.10.0 (1.10.0)
- OS Version: macOS Sierre 10.12 (16A323)

Steps to Reproduce:

1. Create an empty project with the following `package.json` file
```json
{
  "name": "vscode-bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "engine-handlebars": "^0.8.0",
    "express": "^4.14.0",
    "newrelic": "^1.36.2",
    "node-uuid": "^1.4.7"
  },
  "devDependencies": {
    "autoprefixer-stylus": "^0.11.0",
    "babel-core": "^6.3.21",
    "babel-eslint": "^7.0.0",
    "babel-loader": "^6.2.0",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-plugin-webpack-alias": "^2.1.1",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-tape-runner": "^2.0.1",
    "blue-tape": "^1.0.0",
    "chokidar-cli": "^1.2.0",
    "deep-extend": "^0.4.1",
    "immutable": "^3.8.1",
    "json-loader": "^0.5.4",
    "localforage": "^1.4.3",
    "npm-run-all": "^4.0.1",
    "qs": "^6.3.0",
    "raw-loader": "^0.5.1",
    "react": "^15.3.2",
    "react-addons-test-utils": "^15.3.2",
    "react-document-title": "^2.0.2",
    "react-dom": "^15.3.2",
    "react-hot-loader": "^3.0.0-beta.6",
    "react-markdown": "^2.4.2",
    "react-redux": "^4.4.5",
    "react-router": "^2.8.1",
    "react-router-redux": "^4.0.6",
    "redbox-react": "^1.3.2",
    "redux": "^3.6.0",
    "redux-thunk": "^2.1.0",
    "skin-deep": "^0.16.0",
    "snazzy": "^5.0.0",
    "source-map-loader": "^0.1.5",
    "standard": "^8.4.0",
    "stylus": "^0.54.5",
    "tap-spec": "^4.1.1",
    "url-join": "^1.1.0",
    "webpack": "^1.11.0",
    "webpack-dev-server": "^1.10.1"
  },
  "author": "",
  "license": "ISC"
}
```
2. run `npm install`
3. You will see the following problems listed for `dependencies`
>[npm] Module 'https-proxy-agent' is extraneous
>[npm] Module 'node-pre-gyp' is extraneous
>[npm] Module 'readable-stream' is extraneous

These packages are not dependencies of the package, and this error should not show.

**Comment by sandy081** [comment]
@tyrsius Do you have any extensions that generate these problems?

**Comment by banyudu** [comment]
I have this issue, too.

Message 

> [npm] Module 'https-proxy-agent' is extraneous

was generated by the extension 'npm'.

**Comment by ttraenkler** [comment]
Visual Studio Code 1.10.2 on latest macOS Sierra 10.12.3
warning for "dependencies" in package.json: 'Module 'node-pre-gyp' is extraneous'
Here a list of the extensions installed:
<img width="332" alt="bildschirmfoto 2017-03-24 um 15 56 09" src="https://cloud.githubusercontent.com/assets/347722/24299958/1d26da6a-10ab-11e7-9ebb-5ecaa94b0878.png">
<img width="333" alt="bildschirmfoto 2017-03-24 um 15 56 20" src="https://cloud.githubusercontent.com/assets/347722/24299960/1f798d62-10ab-11e7-80c8-6aaf75b54efa.png">

**Comment by sandy081** [comment]
These problems are generated from the extension `npm`. Please file issue against that extension.

**Comment by tyrsius** [comment]
@sandy081 I am experiencing this issue and I do not have that extension installed

**Comment by sandy081** [comment]
@tyrsius Ca you please provide the screenshot of the problems you are seeing in the problems panel?

**Comment by egamma** [comment]
@tyrsius @ttraenkler @banyudu this warning is correct and indicates that you have a module in your node_modules folder that isn't listed in the package.json. This can happen when it was installed without the `--save` or `--savedev` options.

Why is this bad? When the folder is shared through an SCM system and the node_modules are not checked in, then your team mate cannot just run `npm install` to have the same modules installed as you have.

The fix is to add these modules as `devDependencies` in your package.json file.

**Comment by tyrsius** [comment]
@egamma If I follow the steps I posted in my initial post, in a new folder with a fresh npm install, I get this warning. I am sorry, but this warning is not correct.

**Comment by ttraenkler** [comment]
@egamma I am using "yarn add" to add dependencies, not "npm install", which "adds" the --save parameter implicitly.

**Comment by tyrsius** [comment]
The install process is too long to capture in a gif. However, as you can see from this screenshot of the terminal, the only thing in this folder before I ran `yarn` was the `package.json` file, no `node_modules` folder. After installing, you can see the problems for extraneous packages.

![mar-28-2017 08-38-13](https://cloud.githubusercontent.com/assets/1187432/24413991/f37618b8-1391-11e7-94c6-1b24d86ac4c4.gif)

**Comment by tyrsius** [comment]
The install process is too long to capture in a gif. However, as you can see from this screenshot of the terminal, the only thing in this folder before I ran yarn was the package.json file, no node_modules folder. After installing, you can see the problems for extraneous packages.

![vs code bug](https://cloud.githubusercontent.com/assets/1187432/24414113/4a0ff11c-1392-11e7-8d3a-431db87265ba.gif)

**Comment by banyudu** [comment]
@egamma Yes, it works with **npm**. But if someone use **yarn** or [**cnpm**](https://github.com/cnpm/cnpm) instead of **npm**, things are different.

`npm install --save-dev eslint` should create only one directory named 'eslint' under node_modules, while `yarn add eslint` and `cnpm install --save-dev eslint` will create lots of directories(or symbolic links) under node_modules.

**Comment by egamma** [comment]
I followed the steps and didn't get the warning. Not clear what the difference between yours and my setup is. 

This warning actually comes from `npm` and is derived from the output of `npm ls --depth 0 --json`. Can you run this command from the command line in the root of the workspace and include the output.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-npm-scripts#34
