### ISSUE TITLE
Git SCM Extension: Cannot do "git checkout [new branch name]" anymore :(

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#21667]
- VSCode Version: Insiders 1.10.0  40fecfaa
- OS Version: MacOS

Steps to Reproduce:

1. open up a workspace that is backed by a git repo
2. click on the branch in the lower left corner of the status bar (in my case, master)
3. when command palette comes up, try to type in a new branch name to create it (e.g. chrisdias/22)

![image](https://cloud.githubusercontent.com/assets/1487073/23485950/b7cc520a-fe92-11e6-9fde-cb2068be4117.png)

Result: press enter, nothing happens

4. try to use command "git checkout chrisdias/22"

Result: press enter, nothing happens

Expected:
with the built in Git experience i could click on the branch, the command palette comes up with nice prompt to let me quickly create a new branch:

![image](https://cloud.githubusercontent.com/assets/1487073/23485927/9062c4ba-fe92-11e6-97f7-448291681e6b.png)

I miss this nice workflow with the extension :(

**Comment by joaomoreno** [comment]
#21439

**Comment by abhijeetahuja** [comment]
+1
