### ISSUE TITLE
Upgrade from 1.9.0 turns on minimap in user settings

### ISSUE THREAD

**Issue by rnemec** [Microsoft/vscode#21665]
- VSCode Version: 1.10.0
- OS Version: 10.11.6

Steps to Reproduce:

1. Upgraded
2. See minimap
3. Don't like minimap
4. Open settings - enabled = false by default
5. Wonder
6. Copy setting to user settings and set again to false
7. CANNOT GET RID of that minimap. SAM-I-AM - I do not like green eggs and ham.

**Comment by rnemec** [comment]
Please, let me know what other information I can provide. I cannot believe that this bug is not yet logged - it must be something unusual in my setup...

**Comment by Sartan4455** [comment]
I'm with you.  I like the minimap but would like to toggle it like toggle-sidebar(ctrl-b) toggle-panel(ctrl-j)

**Comment by jordanmkasla2009** [comment]
I can't reproduce this. What OS / Extensions / User Settings are you using?

**Comment by rnemec** [comment]
OS = Mac OS 10.11.6
and several extensions (although WHY would they break the mini-thing?) Is there an easy way to dump some useful info for you? I assume this must be something local here since nobody else is complaining...

**Comment by rnemec** [comment]
## Mystery solved!

After the upgrade, for some reason the **workspace settings** had minimap.enable set to "true". I didn't put that in there, but it is there (until now).
I apologize, I didn't look at the workspace settings because I usually only set the user settings, not workspace.

**Comment by cjsaylor** [comment]
@rnemec I had the same thing happen as well. Seems to be some sort of bug with the upgrade from 1.09 to 1.10.

**Comment by rnemec** [comment]
Reopening as upgrade bug.

**Comment by fengcen** [comment]
I found that this extension "Sublime Text Keymap" will automatically create `.vscode` folder and settings.json

**Comment by rnemec** [comment]
I don't have "Sublime Text Keymap" extension. And I already had the settings.json in the workspace's .vscode, just not used much.
Is it possible that the upgrade would just add the minimap.enabled=true if there is settings.json in workspace's .vscode?

**Comment by rnemec** [comment]
I just upgraded to 1.10.1 and guess what - the upgrade added the minimap.enabled=true to my workspace settings **again**.

**Comment by fengcen** [comment]
I only know that "Sublime Text Keymap" will automatically enable minimap and create workspace setting.

It works fine for me after I disable this extension.

**Comment by rnemec** [comment]
Qiu, you are correct!
Keymap plugins.
I am using "Atom Keymap" and whenever the workspace is reloaded, it turns on the minimap. When the plugin is disabled, it behaves OK.

**Comment by gluons** [comment]
For me, `.vscode` folder always automatically created every time I open VSCode. That's really annoying.
I'm using `Atom Keymap` too.

**Comment by rnemec** [comment]
A workaround for all who cannot wait for the Atom Keymap plugin to get fixed (not sure about other plugins):
1. go to file `~/.vscode/extensions/ms-vscode.atom-keybindings-2.0.0/out/src/extension.js`
2. comment out the body of the activate method (I'm having trouble NOT commenting)
3. enjoy

Plus or minus some version number, and possibly something similar may work for the other plugin.

**Comment by alexandrudima** [comment]
We are looking into publishing a fixed version of this extension.

**Comment by alexandrudima** [comment]
We published a new version of this extension that no longer writes to workspace settings.

**Comment by egamma** [comment]
Moving the issue to the sublime extension repository.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-sublime-keybindings#48

**Comment by marvambi** [comment]
Hello folks,
I'm currently using VS Code version: 1.13.1 
Disabling the minimap is just changing your settings as follows:
Step 1. Go to Your "File" menu and mouse over Preferences
Step 2. Select or Click on Settings from the sub menu that appears to the right of Preferences
Step 3. Type minimap in the Search Settings Box that appears
Step 4. From the list of minimap settings that appear, click on the edit icon (pencil) that appear beside it
Step 5. Select false to disable the minimap or true to show it.

You can also achieve this using the following Keyboard Combination:
Step 1. Press **Ctrl + Comma**
Step 2. Type minimap in the Search Settings Box that appears
Step 3. From the list of minimap settings that appear, click on the edit icon (pencil) that appear beside it
Step 4. Select false to disable the minimap or true to show it.

But I think it will be nice to have it toggle on/off the old way.
