### ISSUE TITLE
C++ debugging: keyboard shortcut to change variable value in Watch Window. 

### ISSUE THREAD

**Issue by pmaciejew** [microsoft/vscode#216625]
There is  a shortcut "debug.setVariable" to change variable name in Watch window. 

Can I ask for something like debug.setVariableValue, to change variable value? Normally I have to select "Set Value" from context menu, which is slower than keyboard shortcut.

**Comment by roblourens** [comment]
`debug.setVariable` is to set the value. `debug.renameWatchExpression` is to change the expression
