### ISSUE TITLE
command center disappear when click it then click another window

### ISSUE THREAD

**Issue by shutaozhenzhen** [microsoft/vscode#216695]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. drag tab to create a new windows
2. click command center in the new windows (do nothing)
3. click origin vscode window(or other software window)
4. command center in new window disappeared(always)
5. ctrl+g in new window, click new windows, command center appeared.
6. click origin vscode window command center then click new window, origin vscode window command center disappeared.(sometimes)

**Comment by shutaozhenzhen** [comment]
AAfter a total week, no one reply.fter a total week, no one reply.

**Comment by shutaozhenzhen** [comment]
another week. @sbatten @mojodna @doudou

**Comment by shutaozhenzhen** [comment]
another week.

Version: 1.91.1 still has this problem

**Comment by shutaozhenzhen** [comment]
Version: 1.92.0 still has this problem

**Comment by bpasero** [comment]
**To reproduce:** open the command center picker in the aux window and then click back into the main window.
