### ISSUE TITLE
Extension does not get update even though it is enabled and "Auto Update Extensions" is set to "Enabled Extensions"

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#216797]
![Code_-_Insiders_dI2seBNzbN](https://github.com/user-attachments/assets/2a2921c1-e6aa-422e-a4d9-feb485a14a9d)

**Comment by sandy081** [comment]
Can you please provide steps to reproduce?

**Comment by alambertt** [comment]
Check this out. I have the same trouble.

Version: 1.90.2 (Universal)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:37:41.291Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin x64 19.6.0


https://github.com/microsoft/vscode/assets/6148597/a09784a6-71ba-4caf-9745-89b92093e454

**Comment by sandy081** [comment]
@alambertt I suppose you are hitting this issue - https://github.com/microsoft/vscode/issues/214778 - which is different from this.

**Comment by alambertt** [comment]
Yes, you're correct

**Comment by hediet** [comment]
I don't know the steps. But it stays like this even after reloading/restarting/updating VS Code.

**Comment by hediet** [comment]
I don't know the steps. But it stays like this even after reloading/restarting/updating VS Code.

**Comment by sandy081** [comment]
@hediet I have done some changes to auto update mechanism. Please check if you are still seeing this issue in Insider. If so reopen it with the steps to repro.
