### ISSUE TITLE
Diff editor show "no changes" while still loading

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#216788]
* open a multifile diff
* reload window
* while the diff editor stores and loads it says that there are no changes yet

<img width="1178" alt="Screenshot 2024-06-21 at 09 16 43" src="https://github.com/user-attachments/assets/13e821d8-977b-4518-ad30-fab707e9b5ba">

**Comment by hediet** [comment]
Thanks for filing! Briefly looked into it, but fixing it is a little bit more complex than I thought. The model creation is what takes a while, and during that time the multi file diff editor just has no model. It would be better if the model creation is immediate, but it has some `isLoading` property, that the editor could then show.
