### ISSUE TITLE
Stream of `LanguageModelChatResponse` doesn't really work

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#216720]

**Comment by ianm-stripe** [comment]
@jrieken this issue doesn't provide much context but we are also having trouble today getting the assistant to output anything via 

```
  for await (const fragment of chatResponse.stream) {
    stream.markdown(fragment);
  }
```

where `chatResponse` is a `LanguageModelChatResponse`

**Comment by jrieken** [comment]
> @jrieken this issue doesn't provide much context but we are also having trouble today getting the assistant to output anything via

@ianm-stripe Updated the issue but you issues seems unrelated. Note `.stream` is NOT final API but part of a newer proposal. You should be using `.text` instead

**Comment by ianm-stripe** [comment]
@jrieken ah got it, switching to `.text` unblocked us. Thanks! ... how should we think about the intended difference between `.text` and `.stream`?

**Comment by jrieken** [comment]
> ... how should we think about the intended difference between .text and .stream?

It is part of a new proposal that allows for function/tool calling. With that `stream` is an async iterable that either text or function-use parts. Then think of `text` being `stream` filtered to just text parts
