### ISSUE TITLE
User settings reset/lost on upgrade

### ISSUE THREAD

**Issue by seanpk** [Microsoft/vscode#21676]
After the upgrade to 1.10.0 I lost all my user and workspace settings.

The only setting that seems to have survived is my theme.

Here is my new `settings.json`:
```json
{
  "workbench.colorTheme": "Solarized Light"
}
```

If I can find/get out of a backup my old one, I'll add it to this issue.

- VSCode Version: Code 1.10.0 (49129d126e2c3c5592cfc8a509d872067b69d262, 2017-03-01T15:53:09.975Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|vscode-docker|PeterJausovec|0.0.12|
|git-easy|bibhasdn|1.9.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.7|
|githistory|donjayamanne|0.1.5|
|tslint|eg2|0.8.1|
|csharp|ms-vscode|1.7.0|
|jscs|ms-vscode|0.1.9|
|debugger-for-chrome|msjsdiag|2.5.5|
|addDocComments|stevencl|0.0.8|
|code-spell-checker|streetsidesoftware|0.17.2|;

---

Steps to Reproduce (speculative):

1. with my plugins and my original settings
2. upgrade to 1.10.0

**Comment by seanpk** [comment]
Here is what my settings were before:
```json
// Place your settings in this file to overwrite the default settings
{
	"editor.rulers": [80,	100, 120, 150],
	"editor.tabSize": 2,
	"editor.wrappingColumn": 0,
	"editor.wrappingIndent": "indent",
	"editor.acceptSuggestionOnEnter": false,
	"editor.folding": false,
	"editor.trimAutoWhitespace": false,

	"diffEditor.renderSideBySide": false,

	"files.watcherExclude": {
		"**/.git/objects/**": true,
		"**/bower_components/**": true,
		"**/node_modules/**": true
	},
  "search.exclude": {
		"**/bower_components": true,
		"**/node_modules": true,
		"**/coverage": true,
		"**/typings": true,
		"dist": true
  },

  "jscs.disableIfNoConfig": true,

	"explorer.openEditors.visible": 0,
	"workbench.editor.showTabs": false,
	"window.reopenFolders": "all",

  "terminal.external.osxExec": "iTerm.app",
  "git.confirmSync": false,
  "window.zoomLevel": 0,

  "cSpell.userWords": [
    "semver",
    "SIGINT",
    "SIGHUP",
    "callee",
    "dereferenced",
    "Schemas",
    "nbsp",
    "etag",
    "instantquote",
    "nbind",
    "nodeify",
    "Pageview",
    "npost",
    "yaml",
    "Eventbus",
    "blueoak",
    "preversion"
  ],
  "editor.renderWhitespace": "none",
  "editor.renderControlCharacters": false
}
```

I see that `"editor.wrappingColumn"` is identified as 'Unknown configuration setting' in 1.10.0

**Comment by seanpk** [comment]
fwiw, I've restored my settings from backup and had to make these changes:
1. replace the `"editor.wrappingColumn"` line with `"editor.wordWrap": "on"`
2. add back the only setting in place after the upgrade, i.e. `"workbench.colorTheme": "Solarized Light"`

**Comment by evanfuture** [comment]
Same here, that was a waste of 20 minutes to get it back to normal (no backups).  I'm not sure I remembered everything either.

**Comment by aeschli** [comment]
@seanpk Thanks a lot for sharing the options. That's very useful.

I tried to reproduce the issue with the given settings, but wasn't able. The text edits computed where correct and the new setting properly added. So it looks like it doesn't have to do with the actual settings content. Maybe something in the ConfigurationEditingService 
@sandy081 Can you help chasing this down?

**Comment by bugpowder** [comment]
For what it's worth, had the same experience. My user settings were wiped after the update, with the exception of the UI theme, which was still remembered for some reason. Latest OS X.

**Comment by sandy081** [comment]
@seanpk Were you using any icon theme in 1.9?

**Comment by seanpk** [comment]
@sandy081 no icon theme

**Comment by awebdev** [comment]
I lost my settings too

**Comment by aeschli** [comment]
#21750 pushed to release/1.10

**Comment by stickyhands** [comment]
Lost my config too,
considering to abandon vscode studio ...

**Comment by sandy081** [comment]
@stickyhands Very sorry for it.

May I know, how did you loose it ? 
Is it during an upgrade ? If so, from which version you are upgrading?

**Comment by richarddewit** [comment]
I've just spent over an hour configuring my settings including ~10 custom Vim shortcuts. Then a popup showed up saying VSCode had to restart because of some functionality (update perhaps? can't remember exactly, no idea what version I had before it) 

Then BAM, all my settings are gone...
I was really considering switching from Atom to VSCode.

**Comment by qoops-1** [comment]
feels like vs code still has this problem. I have recently lost my settings for the second time. That's very annoying even with a backup. First time it was caused by an update, second time not sure what caused it...

**Comment by aeschli** [comment]
Please file a new issue with details on how it happened.

**Comment by richarddewit** [comment]
Why don't you just make it so that the configuration file cannot be overwritten by empty content?!
