### ISSUE TITLE
window.title   ${activeFilePath} not work

### ISSUE THREAD

**Issue by huangzhiyang166** [Microsoft/vscode#21679]
- VSCode Version: 1.10.1
- OS Version: windows7  64

Steps to Reproduce:

1."window.title": "${dirty}${activeFilePath}${separator}${rootPath}${separator}${appName}"
2.

**Comment by bpasero** [comment]
Late in the end game we decided to rename `${activeFilePath}` to `${activeEditorLong}`. Then it should work.
