### ISSUE TITLE
C++ language mode make minimap selectionOccurrenceHighlight not working

### ISSUE THREAD

**Issue by rmg-nik** [microsoft/vscode#216747]
Type: <b>Bug</b>

When selected Plain Text language then minimap.selectionOccurrenceHighlight works as expected.
But when selected C++ language then minimap.selectionOccurrenceHighlight does not work.

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|15.1.0
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
vscode-clangd|llv|0.1.28
git-graph|mhu|1.30.0
vscode-dotnet-runtime|ms-|2.0.6
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
remote-containers|ms-|0.369.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
cmake-tools|ms-|1.18.42
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
vs-keybindings|ms-|0.2.1
vscode-commons|red|0.0.6
vscode-xml|red|0.27.1
code-spell-checker|str|3.0.1
code-spell-checker-ukrainian|str|1.2.3
cmantic|tde|0.9.0
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0

(1 theme extensions excluded)

</details>

![PlainTextMode](https://github.com/microsoft/vscode/assets/17927086/0aec5135-a31b-459d-ad98-73203ed25608)
![CppMode](https://github.com/microsoft/vscode/assets/17927086/206050d2-d256-4da5-9199-b58657797701)

An old issue I found https://github.com/microsoft/vscode-cpptools/issues/9674.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/153485

When having semantic highlights, the overview ruler and minimap rendering is turned over to the semantic highlights.
