### ISSUE TITLE
Can't remove a BP when it's moved past the end of the file

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#21673]
See https://github.com/Microsoft/vscode-node-debug2/issues/90

If the debug adapter returns a BP at line 11, but the file is only 10 lines long, then it can't be removed by clicking on the BP icon. If you click on that line, it tries to set a new BP on 10, but doesn't remove the one at 11

Ideally the debug adapter wouldn't do that, but in this case, Chrome/Node will actually return the BP being on an invalid line. No clue why. And the debug adapter doesn't know how many lines the file is, so it can't validate/trim it.

**Comment by isidorn** [comment]
You can still remove it using the breakpoint pane.
I could leave it open as a feature request but I do not think anybody would tackle it so closing for now. If popularity rises I can reopen
