### ISSUE TITLE
Auto close open file

### ISSUE THREAD

**Issue by sapismyini** [Microsoft/vscode#21678]
Previous to this last update 3/1/2017 - I used to be able to have a file open in split editor
I would run a batch file that would delete the file and recreate it and in the split window it would just update.. now it closes the split and the file. I looked though settings and did not see anything pertaining to closing a deleted file. 

There a setting to keep this open I missed?

Thanks,

- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-runner|formulahendry|0.6.12|
|AWK|luggage66|0.0.2|
|csharp|ms-vscode|1.6.2|;

---

Steps to Reproduce:

1. Open file
2. Add to split
3. Delete file that was just opened.

**Comment by bpasero** [comment]
This is as designed, we close files that get deleted. If you are deleting the file and then creating it again, I suggest to just change the file contents instead.

The thing that changed in 1.10 is that we now also do this for files which are "out of workspace", that is either you work in an empty workspace and open files or you opened a file from outside a workspace. No matter what, this behaviour is now consistent with how we do it for files inside a workspace.

There is another issue that asks for keeping a file open even if it has been deleted on disk. I suggest you add your vote there.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11642

**Comment by bpasero** [comment]
With todays insider build (get it from http://code.visualstudio.com/Download#insiders) there is a new setting `workbench.editor.closeOnFileDelete` that will keep editors open when set to `false` provided that the file has been deleted outside of Code. This might help in this case here, please let me know.
