### ISSUE TITLE
args in launch.json not getting picked up.

### ISSUE THREAD

**Issue by rkavalap** [Microsoft/vscode#2167]
I am trying with the below configuration. args for the program are not getting picked up. Is there something I am missing. ?
I am expecting something like "node node_modules/nightwatch/bin/runner.js --test buildOutput/JavaScript1.js --env devtest-chrome-win8" to be executed. 
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "node_modules/nightwatch/bin/runner.js",
			"stopOnEntry": false,
			"args": [
                "--test buildOutput/JavaScript1.js --env devtest-chrome-win8"
            ],
			"cwd": ".",
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "development"
			},
			"externalConsole": true,
			"sourceMaps": false,
			"outDir": null
		},
		{
			"name": "Attach",
			"type": "node",
			"request": "attach",
			"port": 5858
		}
	]
}

**Comment by weinand** [comment]
@rkavalap you have to pass the arguments as individual string elements:

```json
"args": [
   "--test", "buildOutput/JavaScript1.js",
   "--env", "devtest-chrome-win8"
]
```
