### ISSUE TITLE
Poetry VENV is not getting restored with terminal history after Code restart

### ISSUE THREAD

**Issue by mitsukuri** [microsoft/vscode#216723]
When Code is closed with an existing terminal that had a correct Poetry VENV set up, the VENV won't restore on restart, and it is necessary to close the restored terminal and launch a new one in order to get the VENV picked up again.

Not sure if this belongs to the PyLance repo, so trying here first.

https://github.com/microsoft/vscode/assets/88905839/290a7ed6-c192-45f1-9fb4-9fe8c47ddaba

Ubuntu 22.04, Code 1.92, PyLance 2024.6.1

**Comment by mitsukuri** [comment]
So it seems it's just a matter of calling `source <venv-path>` or failing to do so automatically

**Comment by meganrogge** [comment]
which zsh file is that script sourced in?

**Comment by mitsukuri** [comment]
My bad, had not set `"python.terminal.activateEnvironment": true` and `"python.terminal.activateEnvInCurrentTerminal": true`, assuming that those should have been set by default since I had PyLance installed. Closing.
