### ISSUE TITLE
Dont overwrite desktop file on linux

### ISSUE THREAD

**Issue by zub0r** [microsoft/vscode#216793]
Dont overwrite the code.desktop file on linux if it exists. 
There is a bug that displays apps blurry if there is a fractional scaling enabled, so I have to change it after every update to enable wayland features:

```
[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland %F
Icon=vscode
Type=Application
StartupNotify=false
Categories=TextEditor;Development;IDE;
MimeType=application/x-code-workspace;
Actions=new-empty-window;
Keywords=vscode;
StartupWMClass=code-url-handler

[Desktop Action new-empty-window]
Name=New Empty Window
Name[de]=Neues leeres Fenster
Name[es]=Nueva ventana vacía
Name[fr]=Nouvelle fenêtre vide
Name[it]=Nuova finestra vuota
Name[ja]=新しい空のウィンドウ
Name[ko]=새 빈 창
Name[ru]=Новое пустое окно
Name[zh_CN]=新建空窗口
Name[zh_TW]=開新空視窗
Exec=/usr/share/code/code --new-window --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland %F
Icon=vscode
```

**Comment by ReillyBrogan** [comment]
This is user error. Files in `/usr/share/applications` are managed by your package manager and should not be modified directly by end-users or the changes will be overwritten on the next package update. To make persistent changes to a .desktop file copy it to `~/.local/share/applications` and make your changes to that copy.

CC @deepak1556 to close this
