### ISSUE TITLE
Typing `c#` triggers variable suggestions in chat

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#216757]
Type: <b>Bug</b>

1. Open chat input
2. Type `c#`

**bug**
Completions show up

VS Code version: Code - Insiders 1.91.0-insider (Universal) (6afc1c279374106ca4c60382c0d92ed661f4c7e4, 2024-06-20T05:50:16.512Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|4, 5, 5|
|Memory (System)|64.00GB (0.53GB free)|
|Process Argv|--crash-reporter-id 0fffb5da-9cd7-46fd-9e7f-a1564e8c5fda|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bsShoham** [comment]
This looks interesting, I'm thinking of trying to have a go at this issue, may I, and is it available?

I believe this could be solved in a generic way by adding to the `CompletionItemProvider` interface a function that accept the context (the text model, position, perhaps some other stuff) and returns whether or not suggestion should be shown, allowing each completion provider to add it's own logic

**Comment by roblourens** [comment]
This needs a fix somewhere around https://github.com/microsoft/vscode/blob/1c7fa5ef1e67c86302bdd432da48ffe91b8c4d52/src/vs/workbench/contrib/chat/browser/contrib/chatInputCompletions.ts#L397 to make sure that the `#` for the variable completion comes after whitespace or the beginning of the prompt, feel free to attempt it if you'd like

**Comment by bsShoham** [comment]
@roblourens 
Created a PR (#224174), for my test, I used your recommendation and added an option to `computeCompletionRanges` to only return the range if the matching regex is at word start
