### ISSUE TITLE
pls add Stylus support

### ISSUE THREAD

**Issue by Venegrad** [Microsoft/vscode#21670]
Hi. guys many developer already using not sass and not less, stylus better them all, pls add support, because plugin, what add stylus support  working is not fine

**Comment by mjbvz** [comment]
Please try out some of the stylus extensions. This one looks promising: https://marketplace.visualstudio.com/items?itemName=sysoev.language-stylus

**Comment by djut** [comment]
They what I got to fight back and I'm getting all who violated my right

Sent from my iPhone

On Mar 1, 2017, at 5:45 PM, Matt Bierner <notifications@github.com<mailto:notifications@github.com>> wrote:


Please try out some of the stylus extensions. This one looks promising: https://marketplace.visualstudio.com/items?itemName=sysoev.language-stylus

**Comment by dsifford** [comment]
@mjbvz Is there any chance that vscode could add the ability for other languages to implement `colorDecorators` (similar to how less and scss are able to access it)?

I tried forking the repo and attempted to make a few changes to see if it would be as easy as just adding `styl` or `stylus` to [here](https://github.com/Microsoft/vscode/blob/3c0ac993119ade496174ea0030ec4657921ce757/extensions/css/client/src/cssMain.ts#L37-L39) and [here](https://github.com/Microsoft/vscode/blob/3c0ac993119ade496174ea0030ec4657921ce757/extensions/css/client/src/cssMain.ts#L60-L74), but it seems to be a deeper-rooted issue than just doing that.

Stylus is a pretty popular language. I'm sure @Venegrad and I aren't the only ones who are interested in this.

(Also, the `Color Highlight` package, while being an alright substitute, is not what I'm looking for. I prefer the square decorators over the entire hex being highlighted).

Thanks in advance. Happy to help if you can just point me in the right direction.
