### ISSUE TITLE
Some extensions are giving an error

### ISSUE THREAD

**Issue by M-Farjad** [microsoft/vscode#216749]
Type: <b>Bug</b>

When I open an image or open the side bar of my thunderclient extension the VS code gives me this error:
"Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.."

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (0.57GB free)|
|Process Argv|--crash-reporter-id e8c8d9ae-8e97-4a84-b025-a1b88ed04bd4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-django|bat|1.15.0
django|big|1.0.2
vscode-intelephense-client|bme|1.10.4
dart-code|Dar|3.91.20240620
flutter|Dar|3.91.20240529
gitlens|eam|15.1.0
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|10.4.0
figma-vscode-extension|fig|0.3.5
code-runner|for|0.12.2
copilot|Git|1.205.0
copilot-chat|Git|0.16.1
rainbow-csv|mec|3.12.0
mongodb-vscode|mon|1.6.0
vscode-dotnet-runtime|ms-|2.0.6
debugpy|ms-|2024.6.0
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.18.42
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.5.2024062001
jsontodart|Muh|0.2.2
material-icon-theme|PKi|5.4.2
vscode-thunder-client|ran|2.24.11
java|red|1.31.0
LiveServer|rit|5.7.9
pdf|tom|1.2.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscode-gradle|vsc|3.14.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
showvideot:31016892
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31077528

```

</details>

**Comment by gjsjohnmurray** [comment]
Does a restart of VS Code fix it?

**Comment by M-Farjad** [comment]
Yes it got fixed after restarting the machine
