### ISSUE TITLE
Pointer capture when moving sashes or scrollbars

### ISSUE THREAD

**Issue by mquandalle** [Microsoft/vscode#21675]
- VSCode Version: 1.10
- OS Version: Ubuntu 16.10

---

While dragging the sash, the mouse cursor changes when going over different UI elements:

![pointer capture broken](https://cloud.githubusercontent.com/assets/1730702/23487727/4b0931f0-fee8-11e6-85d0-8b91e269c5fa.gif)

In the above gif, I'm maintaining my mouse button pressed during the entire sash drag, but the cursor change from the vertical double arrow to the pointer and then insert variants. The expected behavior is that the cursor should be “captured” by the element being dragged and shouldn't change even if it hover different elements.

Since Electron/Chrome doesn't support the [setCapture]() API which would be the canonical solution to this problem, we have to rely on workarounds using JavaScript events and CSS. I changed the implementation when implementing #4702 and at that time it was working—at least on my machine, but the implementation has changed since then. The following blog post describe an approach that seems more robust than what I had implemented: http://code.fitness/post/2016/06/capture-mouse-events.html.

**Comment by mquandalle** [comment]
Note that this issue arises when dragging other elements as well, like the scrollbar or the minimap.

**Comment by mquandalle** [comment]
This was caused by e0b601e.

**Comment by isidorn** [comment]
fyi @bpasero seems to be your commit

**Comment by bpasero** [comment]
@isidorn we can return that ugly CSS rule (that seems to be the only way) conditionally, e.g. `createStyleSheet` only on mouse down and then remove it afterwards.

**Comment by isidorn** [comment]
@bpasero I would prefer no action for now. It is a minor issue.
