### ISSUE TITLE
Inline chat: remove send icon when text buttons are enabled

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#216772]
Seems like the send icon is redundant with this new mode, especially given the goal of minimizing the amount of elements we have to show in this new UI.  

![Image](https://github.com/user-attachments/assets/fb4a9849-c1b1-44f5-8570-4ce6f37f99c4)

**Comment by jrieken** [comment]
I like and you can do this manually via "right click -> hide" but I need find a way to do this programmatically
