### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: getScriptInfo

### ISSUE THREAD

**Issue by 259522** [microsoft/vscode#216879]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.5.0-dev.20240603

**Steps to reproduce crash**

1.
2.
3.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `typescript-vue-plugin-bundle` contributed by the `Vue.volar` extension

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code - Insiders 1.91.0-insider (63d06667600a2c40245a0ab1f9e2ea816d2fe849, 2024-06-21T10:23:24.518Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3492)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|19.94GB (14.66GB free)|
|Process Argv|E:\\Project\\aiyi2023\\aiyi-admin --crash-reporter-id ade0f473-d86c-4bc1-90d9-cdf1bc36f2a0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.1.0
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
intellij-idea-keybindings|k--|1.7.2
vscode-colorize|kam|0.11.1
auto-comment-blocks|kev|1.0.1
vscode-language-pack-zh-hans|MS-|1.91.2024061909
vscode-versionlens|pfl|1.14.2
element-ui-snippets|SS|0.7.2
highlight-matching-tag|vin|0.11.0
vscode-icons|vsc|12.8.0
volar|Vue|2.0.21
material-theme|zhu|3.17.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aa:30263845
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
724cj586:31013169
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
2f103344:31071589
nb_pri_only:31057983
nativerepl1:31071684

```

</details>

**Comment by mjbvz** [comment]
As this issue notes, this is very likely caused by `typescript-vue-plugin-bundle`. Please file an issue against them
