### ISSUE TITLE
Unable to disable `editor.formatOnSave`

### ISSUE THREAD

**Issue by avengerx** [microsoft/vscode#216816]
Type: <b>Bug</b>

1. Start VSCode without any extensions enabled
2. Create a new text file
3. Add contents, with trailing whitespace characters, i.e.:
```
This is a text file.                
```
![image](https://github.com/microsoft/vscode/assets/808610/0472c861-2d53-49cf-ae97-262b570e47f4)

4. Save the file

Notice how the whitespaces at end of file are removed on save.
![image](https://github.com/microsoft/vscode/assets/808610/43c41c62-865b-4059-bc82-99dcf7c7a9cd)

5. Undo the cleanup (`ctrl+z`)
6. File > Preferences > Settings
7. Search for `formatOnSave`
8. Click it to set, then unset (so it's not "reset", but explicitly "false" in config file)
Notice at this point, there shouldn't be an option to choose between **User** and **Workspace** scopes because the project was not started by opening a folder. Switching to a scenario where a folder is opened makes no difference, thus disabling the setting to user/workspace scopes makes no difference either.
9. Repeat (4), after ensuring (5) added back the whitespace characters to the end of the sentence, or just adding back the whitespace characters to the end of the line.
The result is the same as (4), the file is cleaned from the trailing whitespaces regardless of `editor.formatOnSave` being `false`.

This has been reported a long time ago in https://github.com/Microsoft/vscode/issues/53988, and also has a relevant upvote in https://stackoverflow.com/questions/61827206/vscode-disable-all-auto-formatting-on-save

The accepted solution in the thread (replace the `ctrl+s` hotkey to "save without formatting") is the only effective workaround, and by the answer there, the user is in macos, so this seems to be a cross-platform issue haunting it for a long time.

It does not matter whether user or workspace setting for `file.formatOnSave` is reset, enabled or disabled for either user or workspace scopes.

There are other issues reported where the original reporter didn't confirm it was caused by an extension, like #29335, Besides, to reproduce the scenario above, I simply opened VSCode, then created a new file and saved it in a new, empty directory.

### Context

This is actually a nice feature when set up properly, but it can become a bother when VSCode can't talk properly with version control system in a (legacy) project with lots of formatting issues (or different formatting tastes), thus polluting considerably a file change, say, when there's a small fix.

This would mean, for instance, even with `editor.formatOnSaveMode` as `modifications`, it would format the whole file every time it is saved, literally making a commit to the file useless to the purpose of identifying the actual changes in the file.

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.38GB (14.40GB free)|
|Process Argv|--crash-reporter-id ad07fdab-2683-44ea-ac8c-c9213242f60f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
classic-asp-html|jtj|0.1.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
legacy_priority:31077528

```

</details>

**Edit:** I had the classic asp extension disabled during the step thru but I didn't restart vscode. now restarted vscode after disabling the extension and reproduced the issue. The issue reporter then reported `Extensions: none` when I generated a new bug report template.

**Comment by jrieken** [comment]
Sorry, it confusing but it's a different setting: `editor.trimAutoWhitespace`
