### ISSUE TITLE
Tasks: Duplicated Terminals

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#216826]
Sometimes, when reloading VS Code, the tasks terminals get duplicated:

![Code_-_Insiders_aWIJScfFVY](https://github.com/user-attachments/assets/f59451a5-56d3-4e5b-b567-084706684a3c)

This is not bounded:

![image](https://github.com/user-attachments/assets/fb92368c-01aa-4021-ba41-d6f015432ebc)

[Repro steps.](https://github.com/microsoft/vscode-internalbacklog/issues/4974)

**Comment by meganrogge** [comment]
I just reloaded 20 times, followed the instructions, and am not able to reproduce. Could you please enable `task.verboseLogging` and provide the output when you see this?

**Comment by hediet** [comment]
Today I didn't manage to reproduce... :/

**Comment by meganrogge** [comment]
Likely fixed by https://github.com/microsoft/vscode/pull/224435

**Comment by meganrogge** [comment]
Since we cannot reproduce, closing.

**Comment by lszomoru** [comment]
@meganrogge, does this need to be verified? If no verification needed, could we update the issue label? Thanks!
