### ISSUE TITLE
Problem with text render, when using the keyboard shortcut "Ctrl + /"

### ISSUE THREAD

**Issue by YarLama** [microsoft/vscode#216893]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1.  Choose ur line (16).
![image](https://github.com/microsoft/vscode/assets/52606645/0e491ccf-f75c-47a6-aaa3-ac03a360c2e8)
2.  Using the keyboard shortcut "Ctrl + /".
![image](https://github.com/microsoft/vscode/assets/52606645/b444de10-7f04-4903-8398-dfe5ec27b16c)
3. And again.
![image](https://github.com/microsoft/vscode/assets/52606645/3f826519-ada8-40f7-b198-51ba5de96047)
4. And if i change any symbol in code, then all fine. (remove ; in 16 line).
![image](https://github.com/microsoft/vscode/assets/52606645/e1a6b348-b7db-404b-9647-a2da91a11e0c)
5. This happens with any language, not only JS.
6. I tried:
- disable all extensions
- change vs code theme
- clear vs code cache
- clear user settings.json
- check new updates
- reinstall vs code
- reboot Windows

**Comment by alexdima** [comment]
@YarLama I cannot reproduce, here is what I tried:
* I created a new empty folder
* inside the empty folder I created a file issue.js with the content
* on the line I press cmd+/


https://github.com/user-attachments/assets/2a1f0c25-2d12-4543-8a9d-9b0ef0c61dd6

**Comment by YarLama** [comment]
> @YarLama I cannot reproduce, here is what I tried:
> 
> * I created a new empty folder
> * inside the empty folder I created a file issue.js with the content
> * on the line I press cmd+/
> 
>  Kapture.2024-06-24.at.11.54.44.mp4

I created new file on desktop, and try later create file in new empty folder. But have same problem.
[d2ed36a1-3e6e-48f0-bedc-c747b31fe32d.webm](https://github.com/microsoft/vscode/assets/52606645/48d93546-2f7d-4e02-ac75-2f6953dec50f)

**Comment by YarLama** [comment]
Problem solved after update to 1.91.0 version
