### ISSUE TITLE
Incorrect path for windws uninstall instructions.

### ISSUE THREAD

**Issue by alex4747-pub** [microsoft/vscode#216837]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Open https://code.visualstudio.com/docs/setup/setup-overview
2. Scroll down to clean uninstall instructions, the windows path is incorrect %APPDATA%\Code it should be %APPDATA%\Roaming\Code

**Comment by rzhao271** [comment]
%APPDATA% actually goes to AppData\Roaming from what I can tell, at least on Windows 11. Closing as false positive, but let us know if it redirects differently for you.
