### ISSUE TITLE
Add Setting to Adjust Tooltip Position

### ISSUE THREAD

**Issue by RomanCalderon** [microsoft/vscode#216882]
Type: <b>Bug</b>

Note: This is more so a feature request. Selecting the Feature Request dropdown causes the submit button to grey out, so I'm going with Bug Report! I guess that's a bug report in itself~

Actual Request:

Recently I've struggled with reading many tooltips because it appears below the hovered UI element, where my cursor sits and it covers a large portion of the tooltip text, making it difficult to read.

Suggestion: Add a user/workspace setting to customize the position of tooltips relative to the hovered UI element. i.e. top vs. bottom, maybe left/right as well?

Thanks!

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by alexdima** [comment]
@RomanCalderon Do you mean the editor hover or the hover in other areas of the workbench? For the editor, there is a configuration called `"editor.hover.above": true`, maybe you have configured that value to be `false`?

**Comment by RomanCalderon** [comment]
@alexdima Thanks for looking into this. I've checked and that setting is configured to be true, however the hover popups still show below. For example, when I hover over a button in the Search window from the sidebar, the hover popup/tooltip appears below and underneath my cursor - unless the setting doesn't apply to all hovers across the editor?
