### ISSUE TITLE
Could not close git diff document

### ISSUE THREAD

**Issue by hangxingliu** [Microsoft/vscode#21680]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:21:13.228Z)
- OS Version: Linux x64 4.8.0-39-generic

---

1. I opened **git panel** to review modifications (there has a file I deleted `gulpfile.js`). Because I turn off these configurations: `"workbench.editor.enablePreviewFromQuickOpen": false, "workbench.editor.enablePreview": false,`.  So after I review and open each modification, the modification(diff) document would not auto close.
2. Then I selected files and commit in git. 
3. Finally, I close each diff document. But I found I could not close a diff document(because I deleted this file).The situation look like below:
![2017-03-02 10-44-02](https://cloud.githubusercontent.com/assets/4303130/23491085/1111eb6e-ff37-11e6-99f3-ef37ec2486b0.png)
4. No matter how I click the close button on the left side of document title, I could not close it.

**Comment by bpasero** [comment]
@hangxingliu something in the logs? 
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by hangxingliu** [comment]
![2017-03-03 00-12-28](https://cloud.githubusercontent.com/assets/4303130/23515899/927f6f18-ffa6-11e6-9fef-ef371f0d0386.png)
![2017-03-03 00-14-18](https://cloud.githubusercontent.com/assets/4303130/23515903/9626ea6a-ffa6-11e6-9e75-4c717c57d8a9.png)

So, after my second commit(deleted gulpfile.js). The diff document still keep in the VSCode and could not be close even if how I click the close button in the left side of filename.

**Comment by bpasero** [comment]
@hangxingliu would you be able to provide me with some simple to follow steps to reproduce this that lead to the issue? Kind of hard from reading through the description. One thing that is suspicious is that after committing I would have expected all git related editors to close automatically.

**Comment by hangxingliu** [comment]
1. `git init`
2. `echo '//Test file' > gulpfile.js`
3. `echo '# Test file' > README.md `
4. `git add . && git commit -m "first commit"`
5. `code .`
6. Delete `gulpfile.js` in VSCode
7. Modify `README.md` content
8. Open `git` panel and click `gulpfile.js` and `README.md`
9. Then add these two files to git stage in VSCode
10. And type some commit message then `Ctrl+Enter` to commit
11. After you commit, these two documents(diff) still keep in the VSCode. I could close `README.md` document by clicking button or `Ctrl+W` but could not close `gulpfile.js` by using anyway
    - Just like the situation in the screenshot above.(There still an empty document)

**Comment by hangxingliu** [comment]
These are extensions I have installed in my VSCode

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.8.8|
|crane|HvyIndustries|0.2.2|
|eval|Stormspirit|0.0.6|
|comment-snippets|Tobiah|0.2.0|
|vscode-translate|chun|0.0.2|
|vscode-eslint|dbaeumer|1.2.7|
|githistory|donjayamanne|0.1.5|
|vscode-html-css|ecmel|0.0.33|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|vscode-npm|fknop|3.3.0|
|docthis|joelday|0.4.3|
|vscode-coding-tracker|hangxingliu|0.3.2|
|Kotlin|mathiasfrohlich|1.2.0|
|vs-code-quick-require|milkmidi|0.0.22|
|vscode-apache|mrmlnc|1.1.0|
|cpptools|ms-vscode|0.10.1|
|csharp|ms-vscode|1.7.0|
|js-atom-grammar|ms-vscode|0.1.12|
|debugger-for-chrome|msjsdiag|2.5.5|
|node-modules-resolve|naumovs|1.0.2|
|sass-indented|robinbentley|1.3.0|
|code-spell-checker|streetsidesoftware|0.17.2|
|html-preview-vscode|tht13|0.1.1|;

**Comment by bpasero** [comment]
@hangxingliu thanks, I see some weirdness but also notice that we will soon replace the entire GIT implementation with an extension where a lot of things have changed. You can already enable the new GIT extension by:
* open command palette
* find SCM: Enable preview SCM
* restart

Does it still reproduce if you try with the new SCM system?

**Comment by bpasero** [comment]
@hangxingliu any updates?

**Comment by hangxingliu** [comment]
I am so sorry. after I upgrade my VSCode to 1.10.0. I could not reproduce this bug.

But if I disable preview SCM, I need to typing twice times `Ctrl+W` to close the diff document about the file I deleted after I commit my Git repository.

And under the preview SCM mode. All bugs above are disappeared.

(P.s. I think if you and your team don't care about the bug in the old version, you can just close this issue. Because in my eyes, every smart user will upgrade they VSCode if there has a new version released)
