### ISSUE TITLE
Minimap: scroll shadow is not always rendered.

### ISSUE THREAD

**Issue by c633** [Microsoft/vscode#21682]
- VSCode Version: Version 1.10.1 (1.10.1)
- OS Version: macOS

Steps to Reproduce:

1. Open a source code file.
2. Notice that the scroll shadow of the minimap is missing. It does render the shadow sometimes but not always. Some missing cases I have noticed are:
- Open a file.
- Resize the window.

See the attachment:
![screen shot 2017-03-02 at 10 44 36](https://cloud.githubusercontent.com/assets/5112602/23492237/ce9e582c-ff35-11e6-94a8-e3dbc8a4353b.png)

**Comment by alexandrudima** [comment]
The idea is the shadow drops when there is text "behind" the minimap. Similar how the top shadow drops when there is text "behind" the title area (i.e. when scrolling past line 1).

We need some UX love here... Related #21359

**Comment by c633** [comment]
Oh, thanks for this explanation @alexandrudima. But I guess people would like to see a consistent shadow rendering tho. 
Anw, thank you guys for this great work!
