### ISSUE TITLE
Test: Proposed API `getAccounts` API & `AuthenticationProvider` changes

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#216836]
Refs: https://github.com/microsoft/vscode/issues/152399

- [x] anyOS @sandy081
- [x] anyOS @bhavyaus

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23216836%0A%0A&assignees=TylerLeonhardt)

---

This iteration we've moved away from the previous proposed `getSessions` API... to something that separates the concept of "Accounts" and "Sessions".

An "Account" is basically an identity, without access to anything. It just says who you are... while a "Session", on the other hand, has an `accessToken` that can access whatever scopes were requested. This also means that the concept of `scopes` doesn't matter to an "Account"... and scopes only matter to "session".

Put plainly, 1 account can have multiple sessions tied to it.

Next context! An `AuthenticationProvider` can be marked as supporting only 1 account or multiple accounts at a time. For this TPI, it's really only applicable when you support multiple accounts so make sure you do that.

Alright, enough chat... let's test.

### Prereqs

* Have an extension (don't have one? [create one](https://code.visualstudio.com/api/get-started/your-first-extension)!)
* Add the proposed API in the package.json:
  ```json
  "enabledApiProposals": ["authGetSessions"],
  ```
* Run `npx @vscode/dts dev` to get the proposed API file

### Implement an Authentication Provider

You'll want to:
* Contribute an Auth Provider in the `authentication` contribution section of the package.json
* Then register an Auth Provider using:
  ```ts
  vscode.authentication.registerAuthenticationProvider(id, name, yourAuthProvider, { supportsMultipleAccounts: true });
  ```

You can absolutely attempt to implement a full auth provider if you'd like... I'm not gonna stop you :) Here's [what my Spotify one looks like](https://github.com/TylerLeonhardt/vscode-spotify-auth/blob/main/src/web/authProvider.ts) (but it's not multi-account).

But it's not necessary. Having `getSessions` and `createSession` return dummy data is totally fine for this TPI. Just make sure you test having it:
* return zero sessions (which cases `createSession` to run)
* return 1 or many sessions but of only 1 account
* return several sessions with different accounts

The important part is having `getSessions` and `createSession` take in the new:
```ts
	export interface AuthenticationProviderSessionOptions {
		/**
		 * The account that is being asked about. If this is passed in, the provider should
		 * attempt to return the sessions that are only related to this account.
		 */
		account?: AuthenticationSessionAccountInformation;
	}
```
and do something with it.  This property will be used to filter down the list of sessions we have to only the account passed in or used to create a session specific to that account.

Once you have an Auth Provider, it's time to use it.

### Implement something that uses the new `getAccounts` & additions to `getSession` API

Now time for the consumer! (you can do this in the same extension via a Command or something)

Play around with the `vscode.authentication.getAccounts` API which should return all accounts that you are logged in to.

Additionally, play around with passing an account returned by that API into `vscode.authentication.getSession` via the options.

**Comment by bhavyaus** [comment]
Reused the auth provider sample and signed into multiple Azure Dev ops accounts.
