### ISSUE TITLE
I can't connect to codespace

### ISSUE THREAD

**Issue by polynak** [microsoft/vscode#216878]
Codespace sends me an error message an I can not have access to my projects. The message is:  An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: exception was thrown by handler. exception: failed to start vs code remote server.)
I reloaded the page several times but the same error appears.

Version: 1.90.2
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by lszomoru** [comment]
@polynak, are you still able to reproduce this issue? Have you tried attempting to create a new codespace?

**Comment by polynak** [comment]
I have resolved the issue.
Thank you very much.

Στις Τρί 25 Ιουν 2024 στις 4:30 μ.μ., ο/η Ladislau Szomoru <
***@***.***> έγραψε:

**Comment by lszomoru** [comment]
Thanks for the update. Glad you were able to resolve the issue.
