### ISSUE TITLE
Suggest commands are not serialized

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#216818]
Related: https://github.com/microsoft/vscode/issues/210753

Currently on shell start up all aliases/commands are sent over from pwsh. This is not being serialized land restored so suggest doesn't work properly after.

Before reload:

![image](https://github.com/user-attachments/assets/c6ca7b53-a245-405c-8f89-2d42ca6f337a)

After reload:

![image](https://github.com/user-attachments/assets/9121cce5-53eb-4d85-8d60-100bffdb14c3)

**Comment by alexr00** [comment]
Am I verifying this correctly?
1. Install the PowerShell extension
2. New pwsh terminal
3. `G` in the terminal
4. See suggest show with lots of good cmdlet suggestions
5. Reload window.
6. `G` in the same re-attached terminal
7. See suggest show with lots of good cmdlet suggestions

**Comment by Tyriar** [comment]
yep 👍
