### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by LielDesenv01** [microsoft/vscode#216841]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.5.0-dev.20240603

**Steps to reproduce crash**

1.
2.
3.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `@vsintellicode/typescript-intellicode-plugin` contributed by the `VisualStudioExptTeam.vscodeintellicode` extension
- `ms-vsintellicode-typescript` contributed by the `VisualStudioExptTeam.vscodeintellicode` extension

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code - Insiders 1.91.0-insider (63d06667600a2c40245a0ab1f9e2ea816d2fe849, 2024-06-21T10:23:24.518Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.92GB free)|
|Process Argv|D:\\ASProjetos\\ASPlataformaWEB --crash-reporter-id 0e1c1e46-c92c-47f8-b443-39491cf5fca2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode-standard|bys|0.22.1
path-intellisense|chr|2.9.0
xml|Dot|2.5.1
vscode-language-pack-pt-BR|MS-|1.91.2024061909
js-atom-grammar|ms-|0.1.14
sublime-keybindings|ms-|4.1.10
material-icon-theme|PKi|5.4.2
LiveServer|rit|5.7.9
tabnine-vscode|Tab|3.112.0
pdf|tom|1.2.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
html-snippets|wsc|1.0.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
vscaac:30438845
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
01bff139:31013167
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
2f103344:31071589
nb_pkg_only:31057982
nativerepl1:31071684

```

</details>

**Comment by mjbvz** [comment]
The issue report you filed tells you the likely problem and what to try:

> ❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes
