### ISSUE TITLE
why there is not a forum for vscode?

### ISSUE THREAD

**Issue by zzzgit** [Microsoft/vscode#21685]
I have two questions:

1. why isn't there a forum for vscode
2. how could I get shutcut with the same functionality like sublime's `ctrl+M`

![image](https://cloud.githubusercontent.com/assets/1060733/23493009/7968b678-ff43-11e6-8c6a-416019809947.png)

**Comment by Tyriar** [comment]
You can get similar results as the sublime command by adding this to your keybindings.json:

```json 
{ "key": "ctrl+m",          "command": "editor.action.jumpToBracket", "when": "editorTextFocus" },
```

**Comment by isidorn** [comment]
1. We prefer GitHub to forums

**Comment by i-give-up** [comment]
The way is I see that each serves a different purpose (though there may be some extent of overlap)

- a forum is good for usage help and general discussions (e.g. "how do I do so and so?", "is there a plugin to do this?", "does VS code have this feature...")
- the Github issue tracker is good for reporting issues or what one perceives to be bugs and posting feature requests.

Of course, you can just have everything in Github Issues but that just causes clutter.
