### ISSUE TITLE
Integrated terminal: sticky scroll header has wider letter spacing

### ISSUE THREAD

**Issue by ian-h-chamberlain** [microsoft/vscode#216817]
Type: <b>Bug</b>

Configuration using all defaults except these:
```jsonc
{
    // I think Monaspace makes it obvious but other fonts are also affected:
    "terminal.integrated.fontFamily": "Monaspace Argon, Input Mono, Monaco, monospace",
    "terminal.integrated.fontSize": 11,
    "terminal.integrated.fontWeight": "400",
    "terminal.integrated.fontWeightBold": "800",
    // more obvious with 1 set here, but 0 also reproduces
    "terminal.integrated.letterSpacing": 1,
}
```
1. Run a few commands in the integrated terminal
2. Scroll down to trigger sticky scroll

Compare the non-sticky appearance:
![Screenshot 2024-06-21 at 10 55 00](https://github.com/microsoft/vscode/assets/11131775/e183b93d-d6de-467e-b4a5-309fde4fb661)

With the sticky appearance:
![Screenshot 2024-06-21 at 10 55 13](https://github.com/microsoft/vscode/assets/11131775/9b64c100-5d9a-4024-a133-3fc4c5ba319d)

Side by side:
![cropped_normal](https://github.com/microsoft/vscode/assets/11131775/c7576911-91ac-4f16-8d5f-fa945fce4264)
![cropped_sticky](https://github.com/microsoft/vscode/assets/11131775/13e9c10d-1b22-40e1-82d0-a6374f126d4e)

After experimenting a bit with the `letterSpacing` configuration, I suspect the sticky bar is rendered with a spacing `terminal.integrated.letterSpacing + 1` - it always seems to be wider spacing than the rest of the terminal.

----

VS Code version: Code - Insiders 1.91.0-insider (63d06667600a2c40245a0ab1f9e2ea816d2fe849, 2024-06-21T10:24:54.816Z)
OS version: Darwin x64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|32.00GB (2.97GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 58c9d45f-6b80-48d3-8c0b-d09f8a479b86|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
vscrpc:30624061
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
showvideot:31016890
chatpanelt:31014475
01bff139:31013167
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
impr_priority:31057980
nativerepl1:31071684

```

</details>

**Comment by Tyriar** [comment]
This is because they use different renderers, see https://github.com/microsoft/vscode/issues/218427

**Comment by Tyriar** [comment]
@L0laapk3 yep, it should look exactly the same when https://github.com/microsoft/vscode/pull/218941 lands

**Comment by roblourens** [comment]
The spacing is correct, but I still see a slight difference in how the two are rendered. Is that wrong or is it just some expected artifact of rendering?

![Image](https://github.com/user-attachments/assets/1ca3da26-1f8b-4e2a-9469-0b3a9b179ef5)

**Comment by roblourens** [comment]
With no special terminal font settings, there's still a slight difference

**Comment by andreamah** [comment]
For some reason, sticky scroll isn't working in my powershell instance. I have `terminal.integrated.stickyScroll.enabled: true`

**Comment by Tyriar** [comment]
@andreamah I fixed an issue with shell integration not working in pwsh 5 yesterday, that is likely why

**Comment by andreamah** [comment]
hmm I thought i have powershell 7 now? 

![Image](https://github.com/user-attachments/assets/7f2163e7-402c-4bad-b424-8a6ba828a20d)
