### ISSUE TITLE
Copy With Syntax Highlighting not work with Keynote/Pages

### ISSUE THREAD

**Issue by othree** [Microsoft/vscode#21686]
- VSCode Version: 1.10.1
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Use command+shit+p and execute *copy with syntax highlighting*
2. Paste to Keynote

Expect Result: Paste code block with style to Keynote

Actual Result: Paste plain text to Keynote

If I paste to MS Word first, copy from Word. Then paste to Keynote.  
Then the style of code is correct.

**Comment by mjbvz** [comment]
I confirmed this

Pages and keynote may not support pasting html content http://apple.stackexchange.com/questions/124152/how-do-you-paste-syntax-highlighted-code-into-keynote-13 . I suspect that copying code from Word works because Word copies RTF text to the clipboard in addition to html content. It seems to me that this RTF text is what Pages and Keynote are looking for

**Comment by rebornix** [comment]
For short, we can't do this with current design at this moment.

The long reason is that all our copy and paste stuff (and type, screen reader, etc) relies on HTML Dom. We listen to Copy/Paste events on textarea and we access the clipboard through the events. It's the browser (Chromium in our case) who handles all the clipboard work for us. If Chromium doesn't set HTML content in the system clipboard reasonably, then we can't.

As @mjbvz  mentioned above, Word may set RTF text to system clipboard through some native API. If we want to do the same thing, we may need some nodejs power to access clipboard.

**Comment by nitish24p** [comment]
Anyone found a work around this? still seem to be facing this issue

**Comment by ch-hans-chen** [comment]
> Anyone found a work around this? still seem to be facing this issue
@nitish24p 

You can try to  copy code block as html format onto Apple's TextEdit.app then re-copy to keynote. The TextEdit.app will translate into RTF format for you. Hope this help.  [reference](https://apple.stackexchange.com/questions/124152/how-do-you-paste-syntax-highlighted-code-into-keynote-13)

**Comment by nitish24p** [comment]
Yes i did that back then and it worked
