### ISSUE TITLE
URI: Resources with backslashes do not preserve backslashes

### ISSUE THREAD

**Issue by wenshiqi0** [Microsoft/vscode#21684]
- VSCode Version: 1.9.1
- OS Version: osx 10.11.6

Steps to Reproduce:

If a folder have two sub folders which is named as "test" and "\test\\", you will find two folders will have the same name displayed on the project tree of vscode.
<img width="574" alt="2017-03-02 11 51 07" src="https://cloud.githubusercontent.com/assets/12891758/23492327/b645f4de-ff3e-11e6-9abe-c5428cdcb0c0.png">

**Comment by bpasero** [comment]
We use URI's everywhere and it looks like a path of `/Users/someone/\test\` ends up being `/Users/someone//test/` when passed to the URI function and then later `fsPath` just returns `/Users/someone/test`. I am honestly not sure we can fix this without introducing a new "thing" only for file resources that uses a different paths.

**Comment by jrieken** [comment]
When you create an URI via `file` we simply normalize all backslashes to forward slashes. You can always construct URIs manually but I can check if there is something we can do...

**Comment by bpasero** [comment]
Yeah, I guess in most places throughout our code we just use `URI.file()` so maybe it should happen in that call that backslashes are preserved (macOS, Linux).
