### ISSUE TITLE
Lower-case `d` starting `<!docType>` HTML tag causes it to render in the Markdown previewer.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/vscode#216834]
<table><tr>
	<th>Does this issue occur when all extensions are disabled?</th>
	<td>Yes</td>
</tr></table>

<table><tr>
	<th>VS Code Version</th>
	<td><code>code-insiders-1.91.0-1718942998.el8.rpm</code></td>
</tr><tr>
	<th>OS Version</th>
	<td><a href='https://download.fedoraproject.org/pub/fedora/linux/releases/40/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40-1.14.iso'><code>cpe:/o:fedoraproject:fedora:40</code></a></td>
</tr></table>

#### **Steps to Reproduce**

1.	```MD
	<!doctype Markdown>
	```

	> ![Screenshot_20240621_182019](https://github.com/microsoft/vscode/assets/42837531/8ee1b572-ff61-4f8b-9b04-80bbca7dc068)

	I use *camelCase* for all HTML tags, so I noticed this when I entered `<!docType Markdown>`.

1.	```MD
	<!Doctype Markdown>
	```

	> ![Screenshot_20240621_182023](https://github.com/microsoft/vscode/assets/42837531/5691e4ed-d39a-46bd-b94a-31737b533a40)

	Solely the first letter matters, which doesn't make any sense - if it should always be capitalized, then the check should validate the entire tag content.

**Comment by mjbvz** [comment]
Please justify why the the use case and why this should be supported

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/vscode/issues/216834#issuecomment-2187144310

@mjbvz:

1.	Inline HTML should be as valid as is possible, meaning that `<docType>` should be used in a Markdown document containing HTML.
1.	HTML is case-insensitive, and readability matters, so camelCase HTML is common.
	1.	The parsing is nonsensical (why would the case of the first letter determine anything?)

**Comment by mjbvz** [comment]
This doesn't answer my question: why do you need to write a docType tag at all? The resulting html isn't valid

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/vscode/issues/216834#issuecomment-2187461867

@mjbvz, if targeting HTML5, it should be if you don't use a YAML preamble, since the `<docType>` is first. To my knowledge, as long as a Document Type (before anything else) `<head>`, and `<body>` tag are present, it's valid.

**Comment by mjbvz** [comment]
The markdown is rendered to an html fragment that is then included on an html page. This means you're going to end up with:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- ... -->
</head>

<body>
    <!-- ... -->


    <!-- Begin VS Code markdown content  -->

    <!DOCTYPE markdown>

    <!-- Actual rendered MD .... -->

</body>

</html>
```

We don't render the markdown to a complete html file (we don't even have built-in support for preamble's). We target the most common case for markdown 

If you a more specialized use case, you'll need to write tooling to support that. Closing this issue because it's out of scope of our builtin markdown support

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/vscode/issues/216834#issuecomment-2207470800

@mjbvz, makes sense. Does seem like there's something wrong with your parser if, for this specific tag, it only accepts it if solely the first letter is upper case. If it needed to be upper case, surely the entire tag would need be, not just the first letter.
