### ISSUE TITLE
end value has mixed support, consider using flex-end instead

### ISSUE THREAD

**Issue by TheHomeRepo** [microsoft/vscode#216830]
To avoid postcss warnings, `end` and `start` can be replaced with `flex-end` and `flex-start`.

Line to be updated: https://github.com/microsoft/vscode/blob/68ca9a7f4c6ec11004294bd236244139473b0745/src/vs/editor/contrib/hover/browser/hover.css#L46

**Comment by aiday-mar** [comment]
Has been changed since then
