### ISSUE TITLE
Editor Jumps When Code Lenses Are Inserted

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#216824]
I think the editor used to preserve the vertical position of the line where the the cursor is in.
It jumps now:
![aHV2ZN34RN](https://github.com/user-attachments/assets/81560424-d599-40f8-b8b6-c3120e6e1a7a)

Repro steps:
* Enable Code Lenses for TypeScript
* Navigate to a symbol in a file that has not been opened yet
* Notice that the editor reveals the symbol correctly, but without code lenses yet
* Notice that the editor jumps once code lenses appear

Verification steps:
* Observe that the line the cursor is in does not jump anymore.

If I don't misremember, there was a change made here recently?

**Comment by jrieken** [comment]
> If I don't misremember, there was a change made here recently?

No changes for code lens since long. Doesn't reproduce for me. Can yo consistently repro? Can you try without custom settings?

https://github.com/user-attachments/assets/09fd76fb-c18d-48e8-a33b-165c50f7a633

**Comment by alexdima** [comment]
@hediet The current logic is to keep the first line in the viewport stable. A good improvement might be to keep the line where the cursor is stable (if it's in the viewport), but that is not what we have implemented.

**Comment by hediet** [comment]
Oh, somehow I didn't realizing the jumping then.

> No changes for code lens since long. Doesn't reproduce for me. Can yo consistently repro? Can you try without custom settings?

Did you open this file before in the VS Code session?
In the first frame where `editorBrowser.ts` shows, the code lens feature already reserved some (empty) space (which I don't think the feature knows the first time the text model is opened):

![chrome_BNUwjdyg7w](https://github.com/user-attachments/assets/b60fde20-64bf-43b2-8a84-9cd187377843)

**Comment by jrieken** [comment]
>  the code lens feature already reserved some (empty) space to prevent layout shifts (which I don't think the feature knows the first time the text model is opened):

Between reloads the slots are persisted and optimistically shown for a couple of seconds so that the actual extension/provider can compute theirs (which is usually the same)

**Comment by hediet** [comment]
I think there is something fishy going on with persisting the code lens cache (https://github.com/microsoft/vscode/issues/221005).

**Comment by hediet** [comment]
Closing in favor of #224822 (which addresses the one possible solution to this).

To be honest though, I think https://github.com/microsoft/vscode/issues/221005 is what caused my feeling of this happening much more often.
