### ISSUE TITLE
Stuck on Downloading VS Code server on Remote SSH Connection (OPEN)

### ISSUE THREAD

**Issue by limesqueezy** [microsoft/vscode#216851]
For some reason the issue was closed an limited to comment by microsoft even though the claim by @roblourens does not hold true,

"We fixed the previous known issue."

The issue isn't fixed.

Please open the [previous issue](https://github.com/microsoft/vscode/issues/208117) since a lot of users are facing difficulties and will resort to our rather clumsy ChatGPT script.

**Comment by joshspicer** [comment]
A lot has changed since that issue was closed. Indeed now 'exec server' is the default.  Could you please share your logs  (`> Remote-SSH: Show Log` in the command palette)  so we can look into what you're running into?

**Comment by limesqueezy** [comment]
I've already shared some logs in the previous post, the issue persists when you guys roll out a new version of VSC so this is only reproducible then.

**Comment by joshspicer** [comment]
We appreciate you continuing to follow up with us.

Are these the logs you're referring to? https://github.com/microsoft/vscode/issues/208117#issuecomment-2101666424

What happens after the last line shown in this log? I would expect _something_ to print after that line, a VS Code dialog to pop up, etc...   We don't see a large volume of issues come in after VS Code updates, so I want to understand what else could be in play here.

We pushed a VS Code update two days ago, did the issue repro?  We also have [insider](https://code.visualstudio.com/insiders/) builds that usually release daily.  That would simulate a new stable release for us to debug this.
