### ISSUE TITLE
Can't attach to nodejs process after Feb 2017 update

### ISSUE THREAD

**Issue by sheam** [Microsoft/vscode#21688]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Handlebars|andrejunges|0.2.0|
|jshint|dbaeumer|0.10.15|;

---

Steps to Reproduce:

1. Launch application on Node 4.2.4
2. Attach to process from debug mode of VS Code.

Result:
node js crashes.

Expected:
Before the update, I could attach to node process and set breakpoints.

**Comment by weinand** [comment]
@sheam I cannot reproduce your problem with VS Code 1.10.1 and node 4.2.4.

Can you share your launch configuration that you are using?

**Comment by sheam** [comment]
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": false,
            "outDir": null,
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/home/vagrant/website"
        }
    ]
}
```

I am not sure why I said node 4.2.4. I am on node 4.5.0 in a linux VM (vagrant).

I run VS Code on the host os (Mac). Port 5858 is forwarded from the vagrant instance, and vm and host share code directory via NFS. Have been using this setup for 6+ months now.

With 1.10.1 my node process crashes as soon as I attach (says 'crashing child'). With 1.9.1 it runs fine, and I can set breakpoints, etc.

**Comment by sheam** [comment]
It seems that with Version 1.11.0-insider (1.11.0-insider)/2017-03-10T07:02:27.704Z I am able to set break points and debug...

**Comment by weinand** [comment]
@sheam is this still a problem in the stable March release (VS Code 1.11.0)?

**Comment by MTBandolier** [comment]
I'm seeing similar behavior with the March release (1.11.1).  For me, the node process doesn't crash, but the status bar flickers from blue to orange (debugging mode) and then back to blue.  The debug console shows:
```
Debugging with legacy protocol because it was detected.
```
If I roll back to the January release (1.9.1), I'm able to attach, and there is no output in the debug console.

**Comment by sheam** [comment]
The current production version is working fine again. Thanks. If no one else is having issues, this can be closed.

**Comment by weinand** [comment]
@sheam thanks for the update!
