### ISSUE TITLE
Terminal is often off set

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#216810]
Sorry, I don't know how to reproduce this and if there is logging that can be enabled but I often see the terminal like this 👇 

<img width="468" alt="Screenshot 2024-06-21 at 16 01 11" src="https://github.com/user-attachments/assets/c0e30bf7-1109-4c75-8d9e-c81a7f933fa2">

This is all scrolled back and sometimes the start/first command isn't at the top but off by a few pixels. Resizing (upwards) fixes this but I also see how resizing is janky/stutters. Maybe in some cases it misses a resize all together 

(janky resize)

https://github.com/user-attachments/assets/d35ebd68-8876-4e95-85a9-d14922821892

**Comment by Tyriar** [comment]
The top row not showing is by design, looking at the screenshot it looks like the row height is 30px:

<img width="546" alt="Screenshot 2024-06-21 at 8 45 28 AM" src="https://github.com/user-attachments/assets/511bbc0f-1cb1-41bc-9261-e19e8bd159de">

And you can see that it goes 3px beyond the container height:

<img width="544" alt="Screenshot 2024-06-21 at 8 45 44 AM" src="https://github.com/user-attachments/assets/9252fd1a-1d8c-4add-8464-66cc83d53f1c">

We don't show partial lines as that would look strange for most terminal apps.

As for the janky resizing, it's debounced due to reflow being expensive. However, it's only really expensive when it's resized horizontally, so I might look into making it resize faster when it's just a vertical resize.

**Comment by jrieken** [comment]
> The top row not showing is by design, looking at the screenshot it looks like the row height is 30px:

I don't really understand what that means but there is row above that line. It's the first top most thing I see when scroll up and it's not always 30px

**Comment by Tyriar** [comment]
It's easier to see when there's a selection. Below I selected `sta` and resized to the closest pixel before the line appears:

<img width="711" alt="Screenshot 2024-06-21 at 9 17 58 AM" src="https://github.com/user-attachments/assets/b3a5cfce-3de0-42b2-831e-f19450bb1c77">

Based on this it looks like it's actually 2 scaled pixels off for me (4 actual pixels as devicePixelRation is 2), as it should show the row as long as the border of the tabs pane is taller than or equal to where the last row should be

🐛  row should show but doesn't:

<img width="450" alt="Screenshot 2024-06-21 at 9 21 27 AM" src="https://github.com/user-attachments/assets/5474d67e-6b9a-40fc-9aef-3c8209ce3232">

🐛  row should show but doesn't:

<img width="324" alt="Screenshot 2024-06-21 at 9 22 38 AM" src="https://github.com/user-attachments/assets/05099695-ee93-4f72-9c48-0048f94f4962">

✅ row should not show:

<img width="535" alt="Screenshot 2024-06-21 at 9 23 30 AM" src="https://github.com/user-attachments/assets/9aa80c66-f085-4427-82f9-b930c0a2cc5e">

Will look into that too

**Comment by tisilent** [comment]
There is another scenario where when one of the two terminals is closed and switched from the group, this issue also occurs. I will go to the internal version for verification tomorrow.

**Comment by tisilent** [comment]
![123](https://github.com/microsoft/vscode/assets/48614781/efcc6a99-72eb-4a3f-9c6c-7526367e4962)
@Tyriar

**Comment by tisilent** [comment]
https://github.com/microsoft/vscode/assets/48614781/50170bf7-2344-425a-96f3-66ca8741aa49

**Comment by bhavyaus** [comment]
I can't tell the difference between the changes in my insider and the latest stable release. Would appreciate some verification steps or info on how to verify this.

**Comment by Tyriar** [comment]
To verify:

1. Set zoom level to 0 (100%)
2. Open 2 terminals
3. If tabs are on right: Right click tabs and show them on the left
4. Resize the terminal such that the very top row is 1 pixel away from disappearing - grab the sash and go down until the top row disappears, then go back up 1 pixel
5. Select the top-left most text
6. Take a screenshot
7. Zoom in and verify that the top of the selection aligns with the top of the tab border like this:
    ![image](https://github.com/user-attachments/assets/9b708af3-072c-4a4a-b711-a8d53f7add03)

**Comment by andreamah** [comment]
Couldn't quite verify b/c of https://github.com/microsoft/vscode/issues/218925. Perhaps there's something funky going on with my terminal

**Comment by Tyriar** [comment]
@andreamah you don't need to make the terminal tiny to repro this, you just need content on the top row that you can select

**Comment by andreamah** [comment]
> grab the sash and go down until the top row disappears, then go back up 1 pixel

When I go back one pixel, the whole content moves upwards. The way that this is phrased suggests that it should re-expose the first line. Do I scroll back to reveal the first line?

https://github.com/user-attachments/assets/2b111e42-a30a-4ba0-b0b5-64a26263555e

**Comment by Tyriar** [comment]
@andreamah I mean the first row in the viewport, not necessarily the first in the buffer. The reason it's doing that is again due to pty emulation on Windows only which doesn't matter. As long as you can select the top row (you don't even need text), you can verify the issue.

**Comment by Tyriar** [comment]
Maybe an easier way to repro is to select all in the terminal and then resize to the right pixel position. You just need to check the top of any selection to make sure it lines up against that line

**Comment by andreamah** [comment]
![image](https://github.com/user-attachments/assets/90967993-970f-44b4-92ad-5330df77cd6d)

Looks fine, I think. Thanks!

**Comment by Tyriar** [comment]
@andreamah yep, thanks!
