### ISSUE TITLE
onDidChangeConfiguration fires before onDidChangeWorkspaceFolders when removing folder

### ISSUE THREAD

**Issue by KalleDK** [microsoft/vscode#216862]
Type: <b>Bug</b>

Create an extension with

- onDidChangeConfiguration
- onDidChangeWorkspaceFolders
- A settings with the scope of ressource (boolean in this example)

Add two folders to a workspace

Set the setting to true on the workspace and false on a folder

Remove the folder from the workspace

onDidChangeConfiguration now fires and affectsConfiguration is true for the folder that is getting removed, and the value is now true, as it's getting it from the workspace now (is my guess)

onDidChangeWorkspaceFolders  now fires.

The reason I noticed this is due to some watchers I have, that can be controlled per folder. In a test where I wanted all folders to have it, but a single folder disabled, I saw that the watcher from the disabled folder got activated as the folder was removed (and then disabled as part of the removal of the folder)

```typescript
	const conf_watcher = vscode.workspace.onDidChangeConfiguration((e) => {
		console.log(e);
		vscode.workspace.workspaceFolders?.forEach((ws) => {
			if (e.affectsConfiguration('pdminterpreter.autoChange', ws)) {
				const conf = get_config(ws);
				ctx.logger.info('AutoChange changed for ' + ws.name + ' to ' + conf.autoChange);
				if (conf.autoChange) {
					watchers.enable(ws);
				}
				else {
					watchers.disable(ws);
				}				
			}
		});
	});
	context.subscriptions.push(conf_watcher);

	const ws_watcher = vscode.workspace.onDidChangeWorkspaceFolders((e) => {
		e.removed.forEach((ws) => {
			ctx.logger.info("Removed: " + ws.name);
			console.log("Removed: " + ws.name);
			watchers.disable(ws);
		});
		e.added.forEach((ws) => {
			ctx.logger.info("Added: " + ws.name);
			console.log("Added: " + ws.name);
			const conf = get_config(ws);
			if (conf.autoChange) {
				watchers.enable(ws);
			}
		});
	});
	context.subscriptions.push(ws_watcher);
```
When removing a folder this is the result
```
2024-06-22 01:33:49.840 [info] AutoChange changed for flaf2 to true
2024-06-22 01:33:49.840 [info] Enabling watcher for flaf2
2024-06-22 01:33:49.928 [info] Removed: flaf2
2024-06-22 01:33:49.928 [info] Disabling watcher for flaf2
```

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Ultra 7 165U (14 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.46GB (38.01GB free)|
|Process Argv|--crash-reporter-id 40da3fd2-810d-4975-b213-01098f136a26|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
copilot|Git|1.206.0
copilot-chat|Git|0.16.1
go|gol|0.41.4
debugpy|ms-|2024.6.0
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
remote-containers|ms-|0.369.0
remote-wsl|ms-|0.88.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31077528

```

</details>

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/73353

**Comment by KalleDK** [comment]
@sandy081 I can see they are related - but it's the opposite that they talk about. As I understand, they all talk about when you add a folder. I'm talking about when you are removing a folder. And It makes sense that the config should be there before adding event - but like a stack it should not trigger when removing (or at least trigger after)?

**Comment by sandy081** [comment]
Config change happens before any operation to the workspace folder. Changing the order will make it inconsistent and hard to program against.
