### ISSUE TITLE
PHP - automatic use statements and better autocompletion required

### ISSUE THREAD

**Issue by neeravp** [Microsoft/vscode#21687]
- VSCode Version: 1.10.0
- OS Version: Windows 10Pro
- Build: 14393.693

I am really enjoying VS Code while working with JS and Html. Thanks for the wonderful product.  
However, I am bit unhappy when it comes to working with PHP in VS Code. I know that VS Code is not an IDE - its an editor.  
  
This is more like a feature request and I don't think that it would be too hard as similar has already been implemented in Atom and works quite well.  

The PHP intellisense by Felix Becker is a welcome addition, however it is slow. 
Features required/requested:

1. Better Autocompletion with improved speed of indexing - something like Atom's  php-integrator-auto-completion
2. Automatic use statements - Included in Atom's php-integrator-auto-completion  
3. **If possible** Basic refactoring like renaming variables/methods and extract selected code block to a method - again Atom has a package php-integrator-refactoring  
  
Atom's `php-integrator` package suite works quite well and since Atom is also built using electron, I believe it won't be that difficult for VS Code team to provide such features for PHP developers.    

Below are the Atom packages repositories which I have mentioned, if it helps  
https://github.com/php-integrator/core  
https://github.com/php-integrator/atom-autocompletion 
https://github.com/php-integrator/atom-refactoring

**Comment by neeravp** [comment]
@mousetraps Any progress? I understand your services are honorary and I thank you  for your time and efforts.  
  
However I am still awaiting, in fact very eagerly, for speedy **auto-completion** and **Automatic use statements**.   
  
As much as I love VS Code, absence of these is really counter productive. Also trying to figure out how Sublime's PHP Companion does the job wonderfully.  
  
Please let me know if there's any progress

**Comment by neeravp** [comment]
Hello @mousetraps !  Are you still working on it? I mean can I remain hopeful to get some magical solution from your end to help me with the functionality which I need/desire in VS  code? Please respond..

**Comment by neeravp** [comment]
Hello! Anyone listening........?  
Please respond. I love VS Code but am loosing out on productivity because of non-availability of auto-completing and more importantly Go to Definition and Automatic `use` statements.  
  
Please let me know if any work is in progress on my requested features an if not I may shift to some other editor for time being.

**Comment by isidorn** [comment]
fyi @kieferrm @felixfbecker

**Comment by felixfbecker** [comment]
@neeravp Speed improvements will come with the integration of @mousetraps's new parser: https://github.com/felixfbecker/php-language-server/pull/357
If you have specific performance problems it might be related to your environment or project structure - e.g. caching indexes for Composer dependencies was added quite some time ago. Open an issue at the language server repo or jump on Gitter if you think some specific improvements could be done.

Automatic use statements isn't tracked in an issue yet, feel free to open one at the language server repo and/or to do a PR - I don't think it's a particularly difficult feature and the code is all written in PHP ;)

Support for renaming symbols is tracked here: https://github.com/felixfbecker/php-language-server/issues/21
It's also not very difficult to add as it's essentially the same logic as find-all-references.

Any updates to any of these feature requests will be posted on the specific issues ;)

**Comment by bmewburn** [comment]
@neeravp, perhaps you'd find this extension useful for auto completion
https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

**Comment by ifeltsweet** [comment]
@neeravp, there's this incomplete but working extension that has one part of PHP Companion functionality: https://github.com/ivonunes/vscode-php-namespace

I think with a little bit of effort you could polish it to work just like PHP Companion on Sublime Text.

I too, miss PHP Companion the most after switching to VS Code.

**Comment by neeravp** [comment]
@ifeltsweet Thanks. Will give it a try.

**Comment by roblourens** [comment]
The new parser has landed in php-intellisense so that should be faster now. I think the other requests make the most sense in extensions and I don't see anything to track here, so closing this.

**Comment by ifeltsweet** [comment]
Guys, at last there is a plugin for it!

https://github.com/MehediDracula/PHP-Namespace-Resolver
