### ISSUE TITLE
On restart / reboot windows do not restore in the correct places

### ISSUE THREAD

**Issue by DaveAppleton** [Microsoft/vscode#21695]
- VSCode Version: 1.10.1
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Two monitor system
2. Several Code workspaces in fullscreen mode on each monitor
3. Reboot / restart on upgrade
4. Workspaces have switched monitors

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
