### ISSUE TITLE
Salsa - use a better icon for generic identifier completion proposals

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#2169]
![salsa-icon](https://cloud.githubusercontent.com/assets/172399/12505425/288b63ae-c0e7-11e5-93e3-e98436c83f41.png)

@jrieken pls check whether we can use a better default otherwise we should work with @bgashler1 to get a better icon.

**Comment by jrieken** [comment]
I can use the variable icon which looks a little better

![screen shot 2016-01-22 at 11 42 29](https://cloud.githubusercontent.com/assets/1794099/12508613/53a0acbe-c0fd-11e5-82b7-0f37b6548278.png)

**Comment by egamma** [comment]
It is too subtle, when the good inferred proposal is a property. See below, the `title` suggestion is an inferred one and not distinguishable from the `global identifiers`.

We should find a more distinct icon for the `global identifiers`.
![icons-intellisense](https://cloud.githubusercontent.com/assets/172399/12608332/e317292c-c4db-11e5-9b66-175b2cbafe35.png)

**Comment by jrieken** [comment]
This is how it look when we use the file icon (our other candidate is used for enum btw) 
<img width="331" alt="screen shot 2016-01-27 at 12 46 10" src="https://cloud.githubusercontent.com/assets/1794099/12612590/1c459fcc-c4f4-11e5-83b2-3c202142a179.png">
@egamma
