### ISSUE TITLE
TextDocument cache returns stale file contents

### ISSUE THREAD

**Issue by vaclavHala** [microsoft/vscode#216964]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.90.2
- OS Version: Debian 12

VSCode seems to fail to clear cached content of a `TextDocument` when the underlying file is deleted and recreated with different content. This makes it impossible for me to write automated tests for refactoring in a file using the `TextDocument` and `TextEditor` APIs as subsequent tests observe stale content left over by previous tests interacting with the same file. Note I'm trying to tell VSCode to drop all cached info about the file by invoking the `workbench.action.revertAndCloseActiveEditor` while the file in question is open in editor before removing and recreating it, but there seems to still be some info about the document left over.

What I'm really trying to achieve is setup a predictable initial state for each of my tests which use the document and editor APIs.
I've read in many places that VSCode does not expose the lifecycle of a `TextDocument` to the extension by design, but here this abstraction seems to leak as I'm unable to isolate individual tests short of restarting the whole VSCode process

Steps to Reproduce:

1. `git clone -b stale-text-document git@github.com:vaclavHala/vscode-workspace-race.git`
2. `cd vscode-workspace-race/stale-text-document`
3. `npm i`
4. `npm run test`

**Expected result:**
The test passes

**Actual result:**
```
AssertionError [ERR_ASSERTION]: Observed file content: 'old content'
        at Object.run (/home/hala/codasip/git/vscode-workspace-race/stale-text-document/test.js:19:5)
```

What the reproduction code shows would normally be two subsequent tests and their setup/teardown hooks
```ts
// first test opens the document and does some refactorings in it
await vscode.window.showTextDocument(fileUri)

// teardown of the test tries to clear the file
await vscode.commands.executeCommand('workbench.action.revertAndCloseActiveEditor')
await vscode.workspace.fs.delete(fileUri)

// setup of the second test prepares different content in the same file for different scenario
await vscode.workspace.fs.writeFile(fileUri, Buffer.from("new content"))
// second test tries to work with the same file but sees content left over from first test
const doc = await vscode.workspace.openTextDocument(fileUri)
const text = doc.getText()
```

Also putting a `sleep` seems to help but is not deterministic and needs to be pretty long which makes the whole suite run much longer than it should

Using different file for each test is possible but would complicate the suite significantly as some of the file names are "magic" in the domain (meaning name of the file determines its meaning) so I'd have to also instrument the actual code being tested to expect different "magic" name (computed dynamically e.g. using global number sequence) in each test case

**Comment by yyx1111** [comment]
I am also quite puzzled by this issue. The vscode.window.showTextDocument is not being displayed, and the document does not synchronize with file updates made by the operating system. If you absolutely need to change the document in VSCode, it will inevitably cause the document to be displayed on the interface. The official should provide an API that allows updating vscode.TextDocument in the background (without displaying it) or a feature that enables synchronization of content in the background (without displaying it) as the operating system updates the file.

**Comment by bpasero** [comment]
This issue could originate from a problem with file watching. Let me explain how file watching works in VSCode first and then provide some details how to get more logging data from how file watching behaves in your case.

**Synopsis**
VSCode has different strategies for file watching depending on your workspace and setup:
* no folder opened: files in opened editors are watched via node.js `fs.watch`
* folder opened: folder is watched recursively for all changes via [parcel](https://github.com/parcel-bundler/watcher), opened editors with files not within the folder are watched via node.js `fs.watch`

If you are connected to a remote (SSH, WSL, Docker), the file watcher will run within the target file system. As such, even though you maybe on Windows where VSCode runs, if the remote is Linux, the file watcher will run in the Linux environment.

**Platforms**
Depending on the platform you are on, file watching is differently implemented:
* macOS: using `fsevents` services
* Windows: using `ReadDirectoryChangesW` method
* Linux: using `inotify`

Specifically on Linux, watching a large folder recursively can result in VSCode consuming too many file handles. If that is the case, you will see a warning notification with instructions how to solve that.

**Limitations**
File watching comes with a set of limitations:
* symbolic links are not followed automatically but you can explicitly add symbolic links to be watched via the `files.watcherInclude` setting
* mapped network drives or third party file system drivers are not guaranteed to produce file events
* in general, the operating system may decide to drop file events at any time, there is no 100% guarantee

**Settings**
Please review your settings to see if maybe a folder is excluded by accident. Specifically, the `files.watcherExclude` setting is relevant.

**Logging (local)**
!!! This is ONLY when you open a local workspace, for remote see below !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the local workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `View | Output`
* select `File Watcher` from the dropdown on the right
* attach the output when doing the operation that exhibits the issue

<img width="907" alt="image" src="https://github.com/user-attachments/assets/61245ecf-65db-47f1-8f38-d7769571f8df">


**Logging (remote)**
!!! This is ONLY when you open a remote workspace (WSL, Docker, SSH), for local see above !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the remote workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `View | Output`
* select `Server` from the dropdown
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323886-6b7dfa25-d6ac-4316-9150-80e5c8104d04.png)
