### ISSUE TITLE
Right click menu - dont make print the first option on mac

### ISSUE THREAD

**Issue by sgreener** [microsoft/vscode#216902]
Type: <b>Feature Request</b>

When I right click code in VSCode, the Print option is the first one shown.

No one prints code that much to need it to be the first option!

Please either remove or move it lower down the menu.

Goto Definition should be first.

VS Code version: Code 1.90.2 (Universal) (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:37:41.291Z)
OS version: Darwin arm64 23.5.0
Modes:

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
