### ISSUE TITLE
No new GitHub issue after click 'Create on GitHub' with 'Report Issue' from the 'Help'

### ISSUE THREAD

**Issue by Flavio78** [microsoft/vscode#216907]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2 Date: 2024-06-18T22:34:26.404Z Commit: [5437499](https://github.com/microsoft/vscode/commit/5437499feb04f7a586f677b155b039bc2b3669eb)
- OS Version: Windows_NT x64 10.0.22631 build 22631.3737

Steps to Reproduce:

1. use 'Report Issue' from the 'Help' menu in VS Code
2. select:
   - 'This is': 'Bug Report' (default option)
   - 'For': 'Visual Studio Code'
3. fill 'Title' and 'Steps to Reproduce' fields
4. check 'Include my system information', 'Include my enabled extentions' and 'Include mA/B experiment info'
5. click 'Create on GitHub'
6. nohing happens: no prompt, no message window, no new issue in GitHub

**Comment by justschen** [comment]
@Flavio78 is this still happening?

**Comment by Flavio78** [comment]
@justschen with:
- all extensions disabled
- VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
- OS version: Windows_NT x64 10.0.26100 build 26100

once clicked "Create on GitHub", the default browser opens, and title and description are filled with the values from Visual Studio Code Issue Reporter window.

The problem seems to be solved. Thanks for asking.

Best regards.

**Comment by justschen** [comment]
gotcha thanks! will close for now then, feel free to let me know if it happens again.

**Comment by eleanorjboyd** [comment]
marked as verified since the issue is reported as no longer reproducible by user
