### ISSUE TITLE
I can't hide the minimap

### ISSUE THREAD

**Issue by rcbcerwin** [Microsoft/vscode#21698]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 16.3.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|insertnumbers|Asuka|0.9.1|
|calculate|acarreiro|1.1.0|
|vscode-theme-onedark|akamud|1.3.1|
|Bookmarks|alefragnani|0.11.0|
|python|donjayamanne|0.5.8|
|code-runner|formulahendry|0.6.12|
|Theme-FlatlandMonokai|gerane|0.0.4|
|CppSnippets|hars|0.0.7|
|cpptools|ms-vscode|0.10.2|
|sublime-keybindings|ms-vscode|2.0.0|
|vscode-icons|robertohuertasm|7.3.0|;

---

Steps to Reproduce:

"editor.minimap.enabled": false    
    it unworking.

**Comment by fengcen** [comment]
See [#21665](https://github.com/Microsoft/vscode/issues/21665)

**Comment by fengcen** [comment]
Remove this folder `~/.vscode/extensions/ms-vscode.sublime-keybindings-2.0.0/out`. Then you can disable minimap in your workspace setting or remove your workspace setting.

**Comment by isidorn** [comment]
Dup of #21665
