### ISSUE TITLE
Running a counter on the integrated terminal will eventually crash VS Code

### ISSUE THREAD

**Issue by eduardosm** [microsoft/vscode#216908]
Type: <b>Bug</b>

Running a counter on the integrated terminal will eventually crash VS Code

Steps to reproduce:

1. Launch VS Code and open the integrated terminal
2. Run the command `i=0; while true; do let i++; echo -n $'\r'"$i"; done`
3. Let it run for some time (usually, less than one hour)

This is just a way of reproducing it, but it will also crash with heavy use of CLI applications that show some kind of progress on the terminal.

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:33:48.698Z)
OS version: Linux x64 6.8.11-300.fc40.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 4900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|33, 24, 17|
|Memory (System)|31.22GB (24.96GB free)|
|Process Argv|--crash-reporter-id 853fabfd-e6cd-453e-a10b-12e1248e4b6f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-es|MS-|1.90.2024061209

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
legacy_priority:31077528

```

</details>

**Comment by meganrogge** [comment]
what do you have `terminal.integrated.scrollback` set to?

**Comment by eduardosm** [comment]
1000 (the default)

**Comment by meganrogge** [comment]
does this also happen in an external terminal?
