### ISSUE TITLE
Allow pinning debug action pane to debug sidebar

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/vscode#21696]
- VSCode Version: 1.10.1
- OS Version: Windows 10 Anniversary x64

No matter where I move the debug action pane, it always blocks something so that I have to move it again.
Why not pin it to the debug sidebar, just under debug configuration. At least make it a setting so users can turn it on if they don't need floating one.

**Comment by isidorn** [comment]
I will create a setting for hidding it, that should definetelly solve some of the issue

**Comment by isidorn** [comment]
I have pushed a setting for hidding the debug action bar called 'debug.hideActionBar'. Feedback on the name is welcome.
As for the custom positioning of the debug action bar that is already captured here https://github.com/Microsoft/vscode/issues/9093

fyi @weinand

**Comment by cnshenj** [comment]
@isidorn Since #9093 will add the feature to dock debug action pane to sidebar, the setting name probably should be "debug.actionBarLocation" or "debug.actionBarPosition". The valid values are "float" and "hidden" now. When #9090 is implemented, we can easily add a third value "sidebar" without changing the setting name.

**Comment by isidorn** [comment]
@cnshenj thanks for thinking ahead and I will take that into consideration. However we want to keep the setting name simple for now and #9093 is not on the horizon. I think the users should be able to nicely interect with the widget via UI and not via settings. To hide it is just a temporary solution

**Comment by isometriq** [comment]
Please allow it to dock!
It's really annoying when it's floating, yes.. but I want to use it! (reload, step over, step into, etc...)

**Comment by chevex** [comment]
What @isometriq said. Hiding it is just as annoying. Sure I can step through code with hotkeys but it's nice to have the quick buttons. Not to mention that the action bar is one of the only obvious indicators that the debugger is running. I really wish I could dock this action bar inside the debug pane itself. I'd rather it take up a bit of room in the debug pane than have it cover up things. I also do not know how to stop the debugger without the action bar. It doesn't seem to have a hotkey for that.
