### ISSUE TITLE
Adopt list commands for editor's "Find References" peek UI

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21692]
Looks like I forgot the adoption in the find references list ([`ReferencesWidget`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/referenceSearch/browser/referencesWidget.ts#L484)):

![image](https://cloud.githubusercontent.com/assets/900690/23494505/8aadee56-ff13-11e6-97a6-dc1300f27eed.png)

//fyi @rebornix

**Comment by timbanaveen** [comment]
Hi @bpasero 

I would like to take up this task if possible, but i am not sure about what is 'adoption' and to add that.

Please help

Thanks

**Comment by bpasero** [comment]
@timbanaveen this is about adopting the `IListService` for the tree within find references. For example, here is my take on the search viewlet: https://github.com/Microsoft/vscode/commit/b317d23ec23ff3c1694f8706d7e978e2fed52b4f

The work boils down to:
* register the tree in `IListService`
* provide a standalone editor `IListService` or make the service optional for the standalone editor
* fix all the mouse/keyboard interaction within the find references tree to work properly and via commands

**Comment by timbanaveen** [comment]
Cool, will have to do same for ReferenceWidget also, Thanks :)

**Comment by timbanaveen** [comment]
Hi @bpasero 

I have made some early changes for adding commands in ReferenceWidget. Review from you at this stage will be very helpful for right direction. Please check [this commit](https://github.com/timbanaveen/vscode/commit/b50b2e6b439236ed2913ede3f36f8b790e93d28b).

Thanks :)

**Comment by bpasero** [comment]
@timbanaveen can you open a PR on it please? makes it easier to track

**Comment by timbanaveen** [comment]
@bpasero created one PR, please check.
