### ISSUE TITLE
TS Server fatal error:  Cannot read properties of undefined (reading 'charCount')

### ISSUE THREAD

**Issue by j-Cis** [microsoft/vscode#216916]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.6.0-dev.20240622

**Steps to reproduce crash**

1.
2.
3.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `typescript-deno-plugin` contributed by the `denoland.vscode-deno` extension
- `@twind/typescript-plugin` contributed by the `sastan.twind-intellisense` extension
- `@vsintellicode/typescript-intellicode-plugin` contributed by the `VisualStudioExptTeam.vscodeintellicode` extension
- `ms-vsintellicode-typescript` contributed by the `VisualStudioExptTeam.vscodeintellicode` extension

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code - Insiders 1.91.0-insider (c2e20cb17fae44eb26611cb9a4690059cea0e605, 2024-06-19T05:48:47.170Z)
OS version: Windows_NT x64 10.0.26058
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.18GB free)|
|Process Argv|C:\\ARCHIWUM\\PROJEKTY\\SKANOTEKA\\github-skorobaczSkanoteki --crash-reporter-id 1e2a8f96-e02a-457b-add5-a597748d52c5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (112)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.5.0
vscjsontableeditor|Alt|0.10.0
better-comments-2|ami|2.1.0
browse-lite|ant|0.3.9
gitflow-actions-sidebar|ard|0.5.2
toml|be5|0.6.0
vscode-tailwindcss|bra|0.11.76
path-intellisense|chr|2.9.0
regex|chr|0.4.0
codesnippetsai|cod|1.1.4
gitignore|cod|0.9.0
wai-vscode|cor|2.0.3
jsdoc-generator|cry|2.1.0
vscode-office|cwe|3.3.6
vscode-markdownlint|Dav|0.55.0
vscode-deno-html-tools|day|0.0.11
vscode-eslint|dba|3.0.10
vscode-deno|den|3.37.1
githistory|don|0.6.20
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
bracket-pair-toggler|dzh|0.0.3
vscode-html-css|ecm|2.0.10
better-comments-next|edw|3.2.5
prettier-vscode|esb|10.4.0
git-commits|Exe|4.2.0
vscode-monorepo-workspace|fol|1.3.1
workspace|Foo|1.3.0
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
vscode-github-actions|git|0.26.3
gc-excelviewer|Gra|4.2.59
fresh-mini-codegen|has|0.0.5
svgeditor|hen|2.9.0
githd|hui|2.3.5
code-spell-checker-language-pack|hyo|1.0.0
output-colorizer|IBM|0.1.2
vscode-postfix-ts|ipa|1.13.2
prettier-rust|jin|0.1.9
svg|joc|1.5.3
vscode-peacock|joh|4.2.2
vscode-colorize|kam|0.11.1
tsdoc-comment|kin|1.1.3
l13-diff|L13|1.3.8
deno-std-lib-snippets|lau|0.0.8
json-table-viewer|len|0.0.5
vscode-line-history|lih|0.2.0
vscode-smart-column-indenter|lmc|0.0.13
better-comments-enhanced|lov|1.0.3
git-graph|mhu|1.30.0
vscode-svg|mic|2.0.6
dotenv|mik|1.0.1
hg|mrc|1.9.0
vscode-language-pack-pl|MS-|1.91.2024061909
vscode-edge-devtools|ms-|2.1.5
live-server|ms-|0.5.2024062001
powershell|ms-|2024.3.2
vscode-typescript-next|ms-|5.6.20240622
vscode-react-native|msj|1.13.0
code-svgr|Nat|1.0.0
vscode-json-editor|nic|0.3.0
vscode-preact-snippets|nic|1.0.2
vscode-designer-addon|nod|1.1.15
indent-rainbow|ode|8.3.1
vscode-versionlens|pfl|1.14.2
markdown-checkbox|PKi|1.9.1
material-icon-theme|PKi|5.4.2
material-product-icons|PKi|1.7.0
vscode-gitextensions|pmi|1.3.1
tsimporter|pmn|2.0.1
vscode-css-peek|pra|4.4.1
prettyxml|Pra|5.0.2
typedoc-live-preview|psu|1.0.1
quicktype|qui|23.0.170
geo-data-viewer|Ran|2.6.0
vscode-xml|red|0.27.2024053103
vs-code-prettier-eslint|rve|6.0.0
unotes|rya|1.5.2
vscode-workspace-switcher|sad|1.15.3
preact-preact-router-snippets|sar|0.1.2
twind-intellisense|sas|0.2.1
svg-snippets|sid|1.0.1
svg-preview|Sim|2.8.3
indenticator|Sir|0.7.0
vscode-fileutils|sle|3.10.3
vscode-native-svg-preview|snd|1.72.0
guides|spy|0.9.3
autoimport|ste|1.5.4
code-spell-checker|str|4.0.3
code-spell-checker-czech|str|1.0.6
code-spell-checker-german|str|2.3.2
code-spell-checker-greek|str|1.2.2
code-spell-checker-hebrew|str|2.0.2
code-spell-checker-italian|str|1.1.1
code-spell-checker-medical-terms|str|3.0.2
code-spell-checker-polish|str|2.1.2
code-spell-checker-russian|str|2.2.2
code-spell-checker-turkish|str|1.1.1
code-spell-checker-ukrainian|str|1.2.3
even-better-toml|tam|0.19.2
scm-buttons-vscode|tom|0.1.1
vscode-workspace-explorer|tom|1.5.0
gitflow|vec|1.2.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
windicss-intellisense|voo|0.23.5
vscode-todo-highlight|way|1.0.5
vscode-svgts|xpe|0.2.2
json|Zai|2.0.2
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
f3je6385:31013174
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
2f103344:31071589
legacy_priority:31057981
nativerepl1:31071684

```

</details>

**Comment by mjbvz** [comment]
> ❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

Please look at the issue you just filed. It tells you what is likely wrong and what to try
