### ISSUE TITLE
Go to Previous Problem (Error, Warning, Info) goes to NEXT problem

### ISSUE THREAD

**Issue by mcshaman** [microsoft/vscode#216924]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2 (Universal)
- OS Version: macOS 14.5

Steps to Reproduce:

1. Create new JavaScript file e.g. `testfile.js`
2. Past the following code with errors into the file:
```
const a = "foo"
a = "bar"

const b = "foo"
b = "bar"
```
3. Put the cursor on line 3 so that it is in between the error on line 2 and line 5
4. Select "Go to Previous Problem (Error, Warning, Info)" from the command pallet
5. Observe cursor move to error on line 5 (not line 2)

**Comment by jrieken** [comment]
Thanks for your patience and this great issue report. Clear steps, simple sample ❤
