### ISSUE TITLE
Add IntelliSense in settings.json and tasks.json to all variables

### ISSUE THREAD

**Issue by robsonpeixoto** [Microsoft/vscode#21697]
Currently the IntelliSense do not suggest the pre-defined [VScode variables](https://code.visualstudio.com/Docs/editor/tasks#_variable-substitution). Example:

`tasks.json`
![image](https://cloud.githubusercontent.com/assets/124390/23494947/a352c9a0-fef4-11e6-80ca-433ff440646c.png)

`settings.json`
![image](https://cloud.githubusercontent.com/assets/124390/23494952/ad4d0682-fef4-11e6-9715-177f29fbe451.png)

A variable suggesting here will help a lot!

Thanks

**Comment by isidorn** [comment]
Agree it would be nice to have this. 
@aeschli could you be so kind to give me some pointers on how to contribute these custom completions?

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/8370
