### ISSUE TITLE
Viewing the same file with two separate tabs--second tab freezes

### ISSUE THREAD

**Issue by michaelbarski** [microsoft/vscode#216918]
In the past, I've been able to do the following with an ipynb file in VS Code: 
- select a given file from my working directory to open it
- click on the tab of that file in the top left and select "Split Right"
- view the file conjointly using two tabs 

Now when I try to do that, the second tab freezes when I attempt to scroll. 

In my case it's convenient for me to be able to see some code on that file in one tab while writing some other code in the other tab. For example, I might want to see a function's definition in one tab while writing code that references it below in the other tab. 

I understand that I could just store that function (or whatever code) in another file, but up until now I've been able to have the file open in two tabs without any problems. Just wanted to bring it up if that is something that should still be supported/working.

**Comment by michaelbarski** [comment]
Looks like this might only happen when there is more than one tab open on the right split.

![image](https://github.com/microsoft/vscode/assets/109234047/a0d740f5-93ca-4c66-8745-bd81ee58bfdd)


Here, there don't seem to be any issues with freezing on scroll.

**Comment by rebornix** [comment]
@michaelbarski this issue is fixed now in Insiders, it would be great if you can give https://code.visualstudio.com/insiders/ a try, thanks!
