### ISSUE TITLE
Prompt save of new file when run debug

### ISSUE THREAD

**Issue by Flavio78** [microsoft/vscode#216904]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2 Date: 2024-06-18T22:34:26.404Z Commit: [5437499](https://github.com/microsoft/vscode/commit/5437499feb04f7a586f677b155b039bc2b3669eb)
- OS Version: Windows_NT x64 10.0.22631 build 22631.3737

Steps to Reproduce:

1. open folder project with vscode
2. Open "Run and Debug" then click on "Run and Debug" button
3. Select "App Web (Chrome)" as debugger, and leave the suggested `launch.json` unchanged
4. create a new text file (CTRL-N in Windows) and leave it unchanged once create, without saving it
5. in debug, start the lauch configuration created at point 3 "Run Chrome against localhost".
6. a window will prompt for saving the new file from point 4.

Other steps to Reproduce:

1. open folder project with vscode
2. create a new text file (CTRL-N in Windows) and leave it unchanged once create, without saving it
3. Open "Run and Debug" then click on "Run and Debug" button
4. a window will prompt for saving the new file from point 2.

**Comment by roblourens** [comment]
See the setting `debug.saveBeforeStart`
