### ISSUE TITLE
[scss/less] color decorators for variables

### ISSUE THREAD

**Issue by IIIu6ko** [Microsoft/vscode#21705]
If the variable color is displayed colorDecorators

**Comment by mrmlnc** [comment]
More details? Now you can look at `scss.colorDecorators.enable`.

**Comment by IIIu6ko** [comment]
@mrmlnc 
![screenshot](https://cloud.githubusercontent.com/assets/20703084/23528160/e1212bcc-ffa9-11e6-9f70-81bf4501d57f.png)

Color variables in the preprocessor.

В общем, у меня с английским не очень))
Нужно чтобы vscode понимал, что в переменной находится цвет и отображал его. Такое же я думаю не сложно реализовать? В атоме, есть хороший плагин, который так умеет https://atom.io/packages/pigments

**Comment by bgarrant** [comment]
any updates on this?

**Comment by aeschli** [comment]
There are currently no plans to implement. If you like to give it a try, PRs are welcome. The code for this is in https://github.com/Microsoft/vscode-css-languageservice/blob/master/src/services/cssNavigation.ts#L134
