### ISSUE TITLE
The .NET Core Debugger is still being downloaded. See the C# Output Window for more information.

### ISSUE THREAD

**Issue by tojiamathew** [Microsoft/vscode#21701]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.7.0|
|mono-debug|ms-vscode|0.15.3|;

---

Steps to Reproduce:

1. Create a C# "Hello World!l" console sample. 
2. Put a break point on the console.writeline.
3. Click the Debug button(Green Arrow)
4. The compilation in the output screen shows 0 warnings and errors.
5. Finally the error "The .NET Core Debugger is still being downloaded. See the C# Output Window for more information.", prefixed with the "Error" text in red background is shown.

The error:
![image](https://cloud.githubusercontent.com/assets/26132432/23495124/92a7ab10-fedc-11e6-8b83-878b840fe9c1.png)

launch.json file content:
![image](https://cloud.githubusercontent.com/assets/26132432/23495137/ae5214c2-fedc-11e6-9684-b3bc14b30a22.png)

**Comment by isidorn** [comment]
Please file this issue against the vscode c# extension as this is handled by the extension
https://github.com/OmniSharp/omnisharp-vscode

**Comment by NiclasLindqvist** [comment]
Does anyone know if an issue was opened at omnisharp regarding this? Or any other progress? Can't debug since last week!

**Comment by isidorn** [comment]
@NiclasLindqvist I would suggest you just open a new issue, and if one was created already they will simply close it as a duplicate
