### ISSUE TITLE
Broken syntax highlighting in 0.10.x

### ISSUE THREAD

**Issue by EvilBeaver** [Microsoft/vscode#2170]
Versions after 1.10.1 broke syntax highlighting for language pack 1C:BSL (https://marketplace.visualstudio.com/items/xDrivenDevelopment.language-1c-bsl)

![image](https://cloud.githubusercontent.com/assets/2657561/12505784/e6d33e3c-c0fa-11e5-89c7-2a98f1c85ceb.png)

**Comment by nixel2007** [comment]
So, a few things that i've discovered.
Tokenizer counts 1 cyrillic symbol as 2 symbols (maybe cause cyrillic is twice long in bytes, compared to latin symbols).
So if you need to highlight `Возврат` (return in eng), vscode highlightes strLen("Возврат") = 10 symbols.

**Comment by nixel2007** [comment]
You can check this out by simply typing 
`Возврат long_var_name;`
and
`return long_var_name`

Here is the result.
![default](https://cloud.githubusercontent.com/assets/1132840/12505983/8778fb46-c0fc-11e5-97f4-f74b82814a40.PNG)

Regexp for this word is pretty simple - https://github.com/xDrivenDevelopment/vsc-language-1c-bsl/blob/master/syntaxes/1c.tmLanguage#L165

**Comment by fi11er** [comment]
Here is screenshot of Help->Show welcome-> view source.
Version 0.10.6
![image](https://cloud.githubusercontent.com/assets/1236847/12527473/0d8a23e6-c18d-11e5-81be-cf4384e2b9b4.png)

**Comment by nixel2007** [comment]
More screenshots with the same text from 
0.10.1:
![2015-12-22_104140](https://cloud.githubusercontent.com/assets/9781644/11950351/c0110e20-a898-11e5-8523-e97b3eb298c7.jpg)


And 0.10.5
![2015-12-22_110214](https://cloud.githubusercontent.com/assets/9781644/11950683/b0222384-a89b-11e5-887a-f9b854e1ae4e.jpg)
