### ISSUE TITLE
Misplaced green/red markers in diff view. Bug since upgrade to v1.10

### ISSUE THREAD

**Issue by fungilation** [Microsoft/vscode#21703]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.5.1|
|vscode-theme-onedark|akamud|1.3.1|
|Bookmarks|alefragnani|0.11.0|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.7|
|githistory|donjayamanne|0.1.5|
|vscode-babel-coloring|dzannotti|0.0.4|
|flow-for-vscode|flowtype|0.5.0|
|string-manipulation|marclipovsky|0.0.2|
|Theme-1337|ms-vscode|0.1.2|
|color-highlight|naumovs|1.3.2|
|Lodash|oysun|1.0.0|
|vscode-icons|robertohuertasm|7.3.0|
|react-beautify|taichi|0.3.0|
|react-redux-es6-snippets|timothymclane|2.0.2|
|vscode-react-native|vsmobile|0.3.1|
|babelrc|waderyan|1.0.0|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|
|Material-theme|zhuangtongfa|2.0.4|;

---

Steps to Reproduce:

1. Open Git side bar
2. Open a file that's changed
3. See attached. The first diff lines are correctly scrolled to, but the diff green/red markers in the scroll bar are misplaced to higher to where it should be.
![screenshot 2017-03-01 22 12 20](https://cloud.githubusercontent.com/assets/3803466/23495197/2c1e89e6-fecc-11e6-8830-c97a23717129.png)

First reported on https://twitter.com/garyfung/status/837129744105627648

**Comment by alexandrudima** [comment]
The problem is that the file is somehow triggering the minified code detection logic (i.e. more than half of the characters in this file sit on a line longer than 1000 characters) and the file is forced to wrap. The diff editor should never wrap files.

Related #21674

**Comment by fungilation** [comment]
Ya I can see it's the word wrapping that's the issue.

But a side issue. I like that the diff editor would word wrap now. So why should it never wrap?

**Comment by alexandrudima** [comment]
@fungilation If we want to support wrapping in the diff editor, the "gaps" (the space rendered with diagonal lines) should have the height of the wrapped lines. Today, it has the height of the un-wrapped lines. The request to add this is tracked in #10572
