### ISSUE TITLE
SettingsEditorModel leaks text models

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21706]
Looks like the settings editor model creates a reference that it never disposes: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/preferencesService.ts#L225

Refs: https://github.com/Microsoft/vscode/issues/17073

We should fix these right away if possible.

**Comment by sandy081** [comment]
This one is back of my mind to clean it up and thanks for reminding it again. Cleaned it up.

**Comment by bpasero** [comment]
Thanks!
