### ISSUE TITLE
Circulation  Prompt warning form 

### ISSUE THREAD

**Issue by zhj2159815** [Microsoft/vscode#21700]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Can you please provide more details?
What is the behavior you are seeing? What is the expected behavior?
What are the reprodcuable steps to get this?

**Comment by ramya-rao-a** [comment]
@zhj2159815  Closing this issue as we havent heard back from you in a while.

If you can provide use more details, and steps to reproduce the issue and some screenshots, then we can re-open this issue

**Comment by djut** [comment]
Your really funny are you sure the going let you screen  them idonthinkso but that what an admin Thinks but mess with a device manager they battling


On Mar 6, 2017 at 10:42 AM, <Ramya Rao<mailto:notifications@github.com>> wrote:


@zhj2159815<https://github.com/zhj2159815> Closing this issue as we havent heard back from you in a while.

If you can provide use more details, and steps to reproduce the issue and some screenshots, then we can re-open this issue

**Comment by djut** [comment]
Data course can be erase and code to confrol not just communication but anydevice that use electricty


On Mar 6, 2017 at 10:42 AM, <Ramya Rao<mailto:notifications@github.com>> wrote:


@zhj2159815<https://github.com/zhj2159815> Closing this issue as we havent heard back from you in a while.

If you can provide use more details, and steps to reproduce the issue and some screenshots, then we can re-open this issue
