### ISSUE TITLE
JSON Hover: invalid regular expression

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#21704]
Seeing this running "out of sources" hovering over setting keys:

![image](https://cloud.githubusercontent.com/assets/900690/23496359/0637f4a4-ff1e-11e6-9ab4-d853f0a27cb3.png)

**Comment by aeschli** [comment]
I asume you create that regex.

**Comment by michelkaporin** [comment]
I get the same issue when I trying to add a new setting key asking IntelliSense (Ctrl+Space).

**Comment by sandy081** [comment]
Reopening for candidate discussion

**Comment by weinand** [comment]
The golden rule of query languages:
"Never build regular expressions (or any other query language) from user input without sanitizing the input first"
