### ISSUE TITLE
Performance report - slow start

### ISSUE THREAD

**Issue by senssei** [Microsoft/vscode#21718]
- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:10:18.838Z)</code>
- OS Version: <code>Windows_NT ia32 6.3.9600</code>
- CPUs: <code>Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz (4 x 2594)</code>
- Memory (System): <code>7.88GB (1.64GB free)</code>
- Memory (Process): <code>128.70MB working set (129.41MB peak, 104.78MB private, 31.61MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|57|
|main|app.isReady => window.loadUrl()|1716|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|1447|
|renderer|require(workbench.main.js)|1397|
|renderer|create extension host => extensions onReady()|9038|
|renderer|restore viewlet|1144|
|renderer|restore editor view state|2|
|renderer|overall workbench load|3252|
|main + renderer|start => extensions ready|14261|
|main + renderer|start => workbench ready|7896|

[7dcd_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/813075/7dcd_main.cpuprofile.txt)
[7dcd_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/813074/7dcd_renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
@bpasero Also here `setJumpList`, takes ~250ms. The menu is even slower...

![screen shot 2017-03-03 at 15 30 18](https://cloud.githubusercontent.com/assets/1794099/23554670/5cf5a026-0026-11e7-8987-18fd6a9dd28f.png)

**Comment by jrieken** [comment]
and crazy slow in starting the shared process and the process that gets  the mac-address (~1sec) fyi @joaomoreno 

![screen shot 2017-03-03 at 15 30 07](https://cloud.githubusercontent.com/assets/1794099/23554713/8c4dd91a-0026-11e7-9fa9-9cdcb3eddc90.png)

**Comment by bpasero** [comment]
@jrieken this is interesting because at least on Windows, you cannot interact with the menu until the window is opened so maybe there we should create it only after the window has been opened.

**Comment by jrieken** [comment]
> after the window has been opened

+💯

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/21964
