### ISSUE TITLE
Closing files tree in sidebar

### ISSUE THREAD

**Issue by kresogalic8** [Microsoft/vscode#21715]
Hey guys, I'd like to have an option to close all files in the sidebar like we have in the webstorm. It's hard and it's time-consuming to click one by one to close it. If I have the big file structure that's really the pain in the ass... 

Just to have the clear picture here's the screenshot. I just want to click for example on CSS folder and close all below. Then again expand those things that I need, same behaviour is in the webstorm editor.

![screen shot 2017-03-02 at 8 51 25 am](https://cloud.githubusercontent.com/assets/7289406/23497898/7f3374f8-ff25-11e6-9c6a-5ede78a37dc1.png)

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
