### ISSUE TITLE
Dropdown refactoring menu items lose focus if mouse moves outside of the refactoring menu.

### ISSUE THREAD

**Issue by pzinov** [Microsoft/vscode#21713]
- VSCode Version:
1.10.1
- OS Version:
Windows 10 x64

Steps to Reproduce:

1. Call refactoring window (I rebinded it to Ctrl + , as in Visual Studio).
2. Try to navigate dropdown menu with keyaboard, while moving the mouse somewhere out of popup window.

**Comment by isidorn** [comment]
We do not have a refactoring window afaik.
If you elaborate more I can reopen this issue
