### ISSUE TITLE
extension 

### ISSUE THREAD

**Issue by gentoo96** [Microsoft/vscode#21714]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|GBKtoUTF8|bukas|0.0.2|
|mssql|ms-mssql|0.2.1|;

---

Steps to Reproduce:

If I open the file with the right-click menu, the extension (GBKtoUTF8) will not be run,
Will appear garbled

I can only open vsCode, open the file, it will not appear garbled
(我安装了gbktoutf8用右键菜单打开文件会出现乱码,只能打开窗口在打开文件才不会出现)

**Comment by isidorn** [comment]
Please ilfe this to the github repository of yuor extension.
This is not handled in the vscode core.

**Comment by gentoo96** [comment]
Can you give me a link

**Comment by isidorn** [comment]
https://github.com/huanz/vscode-GBKtoUTF8

**Comment by gentoo96** [comment]
thank
