### ISSUE TITLE
Cannot  open Visual Studio Code after try to upgrade to 1.10.1 on windows

### ISSUE THREAD

**Issue by didacrios** [Microsoft/vscode#21711]
Cannot  open Visual Studio Code after update:

Javascript error occurred in the main process

- VSCode Version: 1.9.1
- OS Version: Windows 8.1 Enterprise

Steps to Reproduce:

1. Try update to 1.10.1
2. VS Code asks to try to close all the programs 
3. Press abort
4. Reboot windows
5 . Open Visual Studio Code
6. Error appear

![image](https://cloud.githubusercontent.com/assets/211009/23497271/9880d7aa-ff22-11e6-81e4-28f1a71193e0.png)

**Comment by bpasero** [comment]
@didacrios try to uninstall and reinstall

**Comment by joaomoreno** [comment]
Yes, please manually reinstall. Sorry for the hassle.
