### ISSUE TITLE
Add auto-resize to sidebar

### ISSUE THREAD

**Issue by tesseslol** [Microsoft/vscode#21719]
Can you add this option/function to vs code?

Like this: https://atom.io/packages/tree-view-autoresize

**Comment by isidorn** [comment]
fyi @bpasero

**Comment by bpasero** [comment]
@tesseslol  as a workaround, DoubleClick on the right hand drag handle of the explorer will cause it to size to show all elements without scrolling.

**Comment by bpasero** [comment]
@tesseslol does the new setting `workbench.tree.horizontalScrolling: true` help you maybe? That will show a horizontal scrollbar in the side bar if space is little.

**Comment by gersilex** [comment]
@bpasero I think it does not add to the feature requested. From a technical perspective I think it would be sufficient if the `DoubleClick the drag handle` action is executed when the content of the *file-explorer* is initially filled with elements (files and folders) or is updated (files or folders changed).

Does this help or can we provide more information on this?

**Comment by bpasero** [comment]
Let's see what @tesseslol has to say

**Comment by gersilex** [comment]
As @tesseslol did not answer, yet, I am willing to try and develop an extension or this feature on my own and have it reviewed by you.

@bpasero Can you point me in the right direction where I could find the actions that get fired, when the sash is dblclicked? It also might to subscribe to an event that gets emitted when the file-exporer content changes, but that's second on my list.

Thanks in advance
