### ISSUE TITLE
Saving on format adds newline in style tags with multiple classes

### ISSUE THREAD

**Issue by Urethramancer** [Microsoft/vscode#21717]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|sp-tools|Mike|0.3.0|
|vscode-docker|PeterJausovec|0.0.12|
|spremoteapi|SteveCurran|1.5.1|
|unity-tools|Tobiah|0.1.9|
|unity-debug|Unity|1.1.0|
|unity-snippets|YclepticStudios|0.1.2|
|jquerysnippets|donjayamanne|0.0.1|
|tslint|eg2|0.8.1|
|vs-code-xml-format|fabianlauer|0.1.4|
|csharpextensions|jchannon|1.3.0|
|net-core-project-manager|ksubedi|0.3.6|
|Go|lukehoban|0.6.54|
|cpptools|ms-vscode|0.10.2|
|csharp|ms-vscode|1.7.0|
|typescript-hero|rbbit|0.12.0|
|vscode-icons|robertohuertasm|7.3.0|
|yo|samverschueren|0.9.3|
|html5-boilerplate|sidthesloth|1.0.1|
|lua-for-vscode|xxxg0001|0.0.23|;

---

Steps to Reproduce:
1.Create a blank HTML file, naming it <something>.html.
2.Add HTML boilerplate with a style section, or just a lone style section, similar to this:
```html
	<style>
		.something {
			list-style: none;
		}
		.somethingelse {
			border: 1px solid black;
		}
		.whatever {
			color: black;
		}
	</style>
```

3.Save.
4.Repeat step 3 a few times.

A newline is inserted between each CSS class for each save as long as VSCode's HTML formatting is enabled. Just one class won't exhibit this.

I've tried running it with --disable-extensions, but it made no difference.

**Comment by mjbvz** [comment]
Confirmed this as well. It does not seem to be caused by any extension. Each format call inserts  a new line

![mar-02-2017 00-12-01](https://cloud.githubusercontent.com/assets/12821956/23498532/ef9f5480-fedc-11e6-9c7b-ca1371d4af43.gif)

**Comment by ofabricio** [comment]
Same problem here.

Please fix this quickly... it is not possible to work. lol

**Comment by isidorn** [comment]
Adding canddiate to discuss at standup

**Comment by aeschli** [comment]
Pushed to release/1.10

**Comment by transtone** [comment]
please release the bug-fix version, the bug is so annoying.
