### ISSUE TITLE
C++ language components update failed

### ISSUE THREAD

**Issue by NickZengXL** [Microsoft/vscode#21710]
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (2580 KB) ..............

This process is broken and stop at 67%, don't know why. I tried to reboot vscode several times, but still failure.

- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.8|
|xml|DotJoshJohnson|1.7.0|
|yang|marko2276|0.1.3|
|cpptools|ms-vscode|0.10.2|
|vscode-docker|PeterJausovec|0.0.12|
|vscode-icons|robertohuertasm|7.3.0|
|cmake|twxs|0.0.15|
|robotframework|vivainio|0.1.2|
|vscode-proto3|zxh404|0.1.0|;

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Please file this against the C++ extension here https://github.com/Microsoft/vscode-cpptools
