### ISSUE TITLE
Test: Allow multiple extensions to contribute default settings values for object settings

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#217238]
Refs: #211632

- [x] anyOS @anthonykim1
- [x] anyOS @sandy081

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23217238%0A%0A&assignees=benibenj)

---

Previously, when multiple extensions contributed default values for an object setting like `workbench.editor.customLabels.patterns`, only the default value from the most recently added extension was used. We have now added support to merge default values for object settings from all contributing extensions.

- **Extension 1 provides**
```
"configurationDefaults": {
      "workbench.editor.customLabels.patterns": {
        "a": "1",
        "b": "2"
      }
    }
```

- **Extension 2 provides**
```
"configurationDefaults": {
      "workbench.editor.customLabels.patterns": {
        "b": "20",
        "c": "30"
      }
    }
```

- **After merging defaults:**
```
"workbench.editor.customLabels.patterns": {
    "a": "1",
    "b": "20",
    "c": "30"
}
```

### Testing

1. Get two extensions to provide multiple default settings values for both the `workbench.editor.customLabels.patterns` and `files.exclude` setting. This is done in the `package.json` file of the extension in `contributions: { configurationDefaults: { ... } }`
    - You can either get the source codes of 2 sample extensions, move them into workspace extensions (`.vscode/extensions/`) and build them (`npm install` in each extension folder) and install the extensions from the `extensions recommended` view
    - or, add `configurationDefaults` for built in extensions such as `git` and debug vscode
2. Go to Settings Editor and check both the `workbench.editor.customLabels.patterns` & `files.exclude` settings and check that all default values are set
3. Uninstall one of the extensions (and restart extension host if needed)
4. Make sure the default values of the uninstalled extension are removed

**Comment by anthonykim1** [comment]
@benibenj  Bit lost on ``` move them into workspace extensions (.vscode/extensions/```. Would we essentially make a directory path .vscode/extensions/ and put the source code or .vsix of them into newly created .vscode/extensions/ directory?

**Comment by benibenj** [comment]
You open a workspace and create a `.vscode/extensions`. Into that folder you move the source code of 2 extensions and you then build them both.
