### ISSUE TITLE
Issue with text selection over minimap

### ISSUE THREAD

**Issue by kovacevjosip** [Microsoft/vscode#21729]
- VSCode Version: 1.10.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

- When minimap is disabled, selecting text, that is wider than current VS code window, is nice and smooth.
- When minimap is enabled, you have to select all over the minimap to the scrollbar to select text line (since this happens instant, selecting one part of text line is not possible).

![screenshot from 2017-03-02 09-45-51](https://cloud.githubusercontent.com/assets/14251756/23500040/d288e742-ff2e-11e6-815f-108190b11ce2.png)
![screenshot from 2017-03-02 09-47-13](https://cloud.githubusercontent.com/assets/14251756/23500042/d3fd20e8-ff2e-11e6-98f4-e0996938e1df.png)

Maybe it would be nice if minimap is little bit transparent since with vertical split screen it takes too much space. This is rather feature then bug.

**Comment by alexandrudima** [comment]
A gif showing the problem from @Tekbr in #21822:

![select](https://cloud.githubusercontent.com/assets/19866231/23524204/6168d51a-ff68-11e6-99a4-c1159094e8e4.gif)
