### ISSUE TITLE
Not having the alt key hardcoded for toggling the MenuBar

### ISSUE THREAD

**Issue by NiggyWizzyWoz** [Microsoft/vscode#21725]
Version 1.10.1
Commit 653f8733dd5a5c43d66d7168b4701f94d72b62e5
Date 2017-03-02T00:47:58.633Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
Linux Manjaro i3 

Steps to Reproduce:
1. Hide the menu bar.
2. Try to switch screens by pressing alt + 1, alt + 2, alt + 3...
3. Whenever you switch to the vscode screen the menu bar will show up because the alt key functionality is hardcoded.

@bpasero, please let us overwrite this functionality as it is utterly annoying for i3 users :(

**Comment by bpasero** [comment]
@NiggyWizzyWoz there is a setting that hides the menu even when Alt key is pressed, did you try that?

**Comment by NiggyWizzyWoz** [comment]
Oh okay, thanks for that.
 "window.menuBarVisibility": "hidden" does the job
Closed the issue.
