### ISSUE TITLE
Slow start warning

### ISSUE THREAD

**Issue by MikeyMCZ** [Microsoft/vscode#21721]
[02d2_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/813137/02d2_main.cpuprofile.txt)
[02d2_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/813136/02d2_renderer.cpuprofile.txt)

- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:10:18.838Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15022</code>
- CPUs: <code>Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)</code>
- Memory (System): <code>23.87GB (13.62GB free)</code>
- Memory (Process): <code>150.37MB working set (150.38MB peak, 110.89MB private, 41.60MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|50|
|main|app.isReady => window.loadUrl()|642|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|721|
|renderer|require(workbench.main.js)|1539|
|renderer|create extension host => extensions onReady()|1889|
|renderer|restore viewlet|1415|
|renderer|restore editor view state|913|
|renderer|overall workbench load|2945|
|main + renderer|start => extensions ready|5022|
|main + renderer|start => workbench ready|5922|

**Comment by jrieken** [comment]
Thanks. We could identifier https://github.com/Microsoft/vscode/issues/22086 and https://github.com/Microsoft/vscode/issues/22089
