### ISSUE TITLE
Had a slow startup.

### ISSUE THREAD

**Issue by Alonski** [Microsoft/vscode#21720]
[438c_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/813091/438c_renderer.cpuprofile.txt)
[438c_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/813090/438c_main.cpuprofile.txt)

- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:10:18.838Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)</code>
- Memory (System): <code>7.89GB (1.24GB free)</code>
- Memory (Process): <code>135.82MB working set (147.29MB peak, 109.94MB private, 30.85MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|69|
|main|app.isReady => window.loadUrl()|835|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|597|
|renderer|require(workbench.main.js)|3479|
|renderer|create extension host => extensions onReady()|2430|
|renderer|restore viewlet|1778|
|renderer|restore editor view state|1367|
|renderer|overall workbench load|3442|
|main + renderer|start => extensions ready|7784|
|main + renderer|start => workbench ready|8513|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\owner\438c_main.cpuprofile.txt`
-`C:\Users\owner\438c_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Thanks. We have identified https://github.com/Microsoft/vscode/issues/22086 and https://github.com/Microsoft/vscode/issues/22087
