### ISSUE TITLE
Test: Accessible Editor Hover View/Help

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#217237]
Refs: 

- [x] macOS @justschen
- [x] linux @roblourens
- [x] windows @alexr00

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23217237%0A%0A&assignees=aiday-mar)

---

Last iteration, we have added an accessible view and an accessible help to improve the editor hover accessibility. These two widgets used to show information relative to the current focused hover part only if it was a markdown hover. For other hover parts (like hover parts containing a color picker or the hover status bar) no information would be shown  (see https://github.com/microsoft/vscode/issues/213638 for more information). This iteration, we have worked on adding accessible content for all hover parts. If a hover part is focused, the view and the help show information relative to that part. If the full hover is focused, the view and the help show information relative to the full hover.

To test please do the following:

- For your operating system, install and turn on a screen reader. On macOS you can use VoiceOver, on Windows you can use NVDA and on Linux you can use Orca.
- Toggle the screen reader mode using the `Toggle Screen Reader Accessibility Mode` command, if it is not already turned on.
- Open a file, write some code, make an editor hover appear. Make sure that the editor hover has several parts. Hover parts are visually separated by borders. Make sure that the hover contains different types of hover information/hover parts. Consider the following example:

```
/**
 * | Month    | Savings |
 * | -------- | ------- |
 * | January  | $250    |
 * | February | $80     |
 * | March    | $420    |
 *
 * ### Examples
 * See [title](https://www.example.com/) for examples
 */
export class SomeInterface {}
export class SomeInterface {}
```

If you hover on the first line `export class SomeInterface {}`, you should see 3 hover parts as in the picture below: the first contains a diagnostic, the second contains the JS Doc information and the third contains the status bar (which for the purpose of this TPI is considered like a hover-part). This hover has several hover parts, each containing different information.

<img width="481" alt="Screenshot 2024-06-24 at 17 30 02" src="https://github.com/microsoft/vscode/assets/61460952/6b66d702-fc8b-44b4-b421-14db8df90e0d">

Another example of a hover containing several hover parts is the following:

```
.monaco-sashdebug {
    background: hsla(232, 90%, 92%, 0.823);
}
```

When in a CSS file, there will be a color decorator in front of the word `hsla`, and when you hover on the color decorator, a hover should appear containing a color picker as well as some additional information below. 

<img width="719" alt="Screenshot 2024-06-24 at 17 39 00" src="https://github.com/microsoft/vscode/assets/61460952/9cfdb481-86f5-43bd-ad81-c61ac2956f34">

- Focus the entire hover. You may use for that the keybindings `cmd+k, cmd+i`. If the hover is visible, the keybindings make the hover appear at the current cursor position, and if already visible, they will focus the entire hover.
- Press the keybindings to make the accessible view appear (the command ID is `editor.action.accessibleView`). On macOS, this is `option + F2`. The editor hover accessible view should appear and focus moved there. 
- Read the text with the screen reader (press the left and right arrows to navigate in the accessible view). Make sure the text in the view makes sense. The accessible view will show some accessible text for each hover part - sometimes it will show the actual hover content and other times, when more appropriate,  it will show text describing the hover part. An example of the latter is that the accessible view will contain the text `There is a color-picker here` when there is a color picker in the editor hover.
- Press on the keys to make the accessible help appear. The command ID is `editor.action.accessibilityHelp`. On macOS, the keybindings are `option + F1`.
- Read the text in the accessible help with the screen reader. The text that is shown at the moment is mostly the same as the text that is shown for the accessible view. In some cases it can be different (especially when you are focused on an expandable markdown hover, please see https://github.com/microsoft/vscode/issues/213638 for more details). The accessible help acts like a more detailed accessible view. Let me know if you think the text displayed there could be improved and if other helpful text could be added.
- Exit from the accessible help. Focus on a _hover part_, a sub part with grey borders within the hover.
- Make the accessible view/help appear while focused on the hover part. Read the text with the screen reader, make sure it makes sense. 
- Generally test the accessibility of the editor hover with the screen reader.
- Repeat the steps above, with several different editor hovers.

**Comment by alexr00** [comment]
This felt like more of a complexity 4 TPI to me!

**Comment by justschen** [comment]
overall worked well!

**Comment by roblourens** [comment]
Works as described, but the accessible view/help always have the same content in the editor, is that expected?

Also, these work on editor hovers but not workbench hovers, is that right? If I focus a workbench hover and use these commands, it always moves focus to the editor and get the "You are in a code editor" accesibility help.

**Comment by aiday-mar** [comment]
Hi @roblourens I am not sure I understood your first question. Do you mean that when you make the accessible view/help appear from different focused hover parts, you see the same content?

The current work is indeed only for editor hovers. I believe @Tyriar is responsible for the workbench hover. Perhaps we could consider adding an accessibility help/view for the workbench hover

**Comment by Tyriar** [comment]
@meganrogge do you think a generic hover a11y help is needed?

**Comment by roblourens** [comment]
I mean that the accessible help always has the same content as the accessible view, so wondering what the difference between the two is exactly.

**Comment by aiday-mar** [comment]
Ah yes right, the accessible help mostly has the same content yes, but was designed initially to provide more information. I could add descriptions of the commands that can be run for the hover with their keybindings in there for example
