### ISSUE TITLE
Enable extension menu contributions to chat codeblocks

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#217287]
An extension should be able to contribute a menu button to the floating toolbar on chat codeblock editors. There should be a context key for the language of the codeblock and it should be able to get the URI of that editor. eg- Live Preview previewing 'html' codeblocks

**Comment by bhavyaus** [comment]
This should also support scenarios such as contributing a button to help insert suggested settings into the user's settings.json file.

**Comment by roblourens** [comment]
Yeah, but I wonder how we would differentiate between that and other json codeblocks. Maybe the extension needs to be able to set a custom context key on the codeblock.

**Comment by bhavyaus** [comment]
> Yeah, but I wonder how we would differentiate between that and other json codeblocks. Maybe the extension needs to be able to set a custom context key on the codeblock.

The extension would be aware of the codeblocks being streamed and could set the context key on the codeblock at that point?

**Comment by roblourens** [comment]
Yeah, but we don't have a mechanism to set a context key that is scoped to a codeblock.

**Comment by roblourens** [comment]
Hooked up normal editor context keys for codeblocks, so that context menu actions can show normally, that's enough for now
