### ISSUE TITLE
Explore using the shellIntegration API to react to git operations like pull and fetch in the terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#217244]
Please look at this for July so we can get some feedback before finalizing the API

**Comment by Tyriar** [comment]
API proposal: https://github.com/microsoft/vscode/blob/64e01374b338c95820f0547cec1eca78fc710363/src/vscode-dts/vscode.proposed.terminalShellIntegration.d.ts

**Comment by lszomoru** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/220995
