### ISSUE TITLE
Test: Source Control incoming/outgoing graph

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#217398]
Refs: https://github.com/microsoft/vscode/issues/215439

- [x] anyOS @TylerLeonhardt
- [x] anyOS @benibenj

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23217398%0A%0A&assignees=lszomoru)

---

This milestone we have started working a new visualization of the incoming/outgoing changes in the "Source Control" view. Instead of using collapsible groups showing the changes, we are using a graph to show the incoming/outgoing changes. The feature is experimental and we are planning on polishing it next milestone but we should like to do a test pass in order to validate the basic functionality. Thank you!

### Prerequisites
* Install the latest VS Insiders release
* Ensure that the following experimental setting is enabled:
    * `scm.experimental.showHistoryGraph`

### Default branch flow
* Open a folder/workspace that contains a git repository
* Switch to the main branch and click the "Sync Changes" button if there are any incoming/outgoing changes
    * Confirm that at this point the "Incoming/Outgoing" section is not being shown
* Make changes to one or more file. Commit the changes
    * Confirm that there is one outgoing change
    * Confirm that a graph with two commits is shown (main, origin/main)
    * Review the graph and provide whether it conveys the state of the repository
* Click on each of the two commits
    * Confirm that the multi-file diff editor is opened and the changes are correct
* Make changes to one or more file. Commit the changes
* Make changes to one or more file. Commit the changes
    * Confirm that you have 3 outgoing changes
* Open origin/main in the browser and create 2 commits
* Invoke the "Git: Fetch" command
    * Confirm that there are 2 incoming changes and 3 outgoing
    * Confirm that the graph shows these commits
    * Review the graph and provide whether it conveys the state of the repository
* Click the "Sync Changes" button
    * Confirm that the graph is not shown after the operation completes

### Topic branch flow
* Open a folder/workspace that contains a git repository
* Switch to the main branch and click the "Sync Changes" button if there are any incoming/outgoing changes
    * Confirm that at this point the "Incoming/Outgoing" section is not being shown
* Create a new topic branch (ex: topic-branch)
* Make changes to one or more file. Commit the changes
    * Confirm that the graph shows two commits (origin/main, topic-branch)
* Click on the "Publish Branch" button
    * Confirm that the graph shows two commits (origin/main, topic-branch, origin/topic-branch)
* Make changes to one or more file. Commit the changes
    * Confirm that the graph shows three commits (origin/main, topic-branch, origin/topic-branch)
* Open origin/main in the browser and create 2 commits
* Switch to the "main", and invoke the "Git: Fetch" command
* Switch back to the topic branch
    * Confirm that the graph reflects the new changes
    * Review the graph and provide whether it conveys the state of the repository
* Invoke the "Git: Merge" command and merge main -> topic-branch
    * Confirm that the graph reflects the new changes
    * Review the graph and provide whether it conveys the state of the repository

**Comment by benibenj** [comment]
Very cool!

**Comment by TylerLeonhardt** [comment]
Very cool visualization! 👏
