### ISSUE TITLE
Chinese input method (Baidu), enter the Chinese cursor does not follow,

### ISSUE THREAD

**Issue by youxdd** [Microsoft/vscode#21736]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|sublime-keybindings|ms-vscode|2.0.1|;

---

Steps to Reproduce:

1Chinese input method (Baidu), enter the Chinese cursor does not follow, (win10)
2.

**Comment by King66** [comment]
1. 如果其他输入法正常，百度不正常，你确定这不是百度输入法的问题？
2. 人家都是英语提issue，你这真好意思。

**Comment by alayii** [comment]
[weasel](https://github.com/rime/weasel) input method on windows 7 64bit also have this problem when I type more than one chinese character.

**Comment by King66** [comment]
I am using Windows 10 build-in input method and QQ pinyin, that's fine with me.

**Comment by alayii** [comment]
weasel works fine in atom, sublime text 3 and other editor/ide. 
reproduce is kind of easy:

![image](https://cloud.githubusercontent.com/assets/1555320/23579087/97e0da8e-0120-11e7-88c5-6accf3cc0a9c.png)

1. first go to [http://rime.im/download/](http://rime.im/download/)
2. click red arrow pointed url in above image, download the input method then install it.
3. switch input method to weasel(小狼毫) and try it in vscode, make sure multiple chinese character is appear, then press space key.

and cursor is not gonna follow.

I'm not using windows for now, cannot screenshot it.

if it is confirmed as input method issue, I will report it to them. thanks.
