### ISSUE TITLE
 [loc][Query][VSCode] Please clarify meaning of the string

### ISSUE THREAD

**Issue by v-sinovo** [Microsoft/vscode#21735]
Hello,
we have a question from our translator. Can you help please? Thanks!

**Resource ID:** ".resx", 0; "commit message"
**File:** extensions\git\out\commands.nls.resx
**Source:** Commit message

**Question:** Is "Commit" a verb here?

**Comment by joaomoreno** [comment]
It's a noun: the commit message is used for committing.
