### ISSUE TITLE
Weird visualization of the visual studio code environment

### ISSUE THREAD

**Issue by Geor17** [microsoft/vscode#217384]
Type: <b>Performance Issue</b>

When I open VS, strange black and white figures suddenly start appearing in the VS tab. I am new in coding, please help me :(

This image explains the issue better than my words: 
![image](https://github.com/microsoft/vscode/assets/110853923/722e7d89-4645-4f3a-b81b-dfb9fabc153c)

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (20.98GB free)|
|Process Argv|--crash-reporter-id 147b4456-c62c-42dc-9897-0f5b009e6085|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   101	  5292	code main
    0	   184	  9096	window [1] (Untitled-1 - Visual Studio Code)
    0	    95	  9764	window [2] (Issue Reporter)
    0	   160	 15724	extensionHost [1]
    0	   167	 17276	     electron-nodejs (bundle.js )
    0	    29	 15876	   crashpad-handler
    0	    77	 16220	fileWatcher [1]
    0	    95	 20684	shared-process
    0	   138	 20988	   gpu-process
    0	    41	 22104	   utility-network-service
    0	    94	 22560	ptyHost
    0	     6	  6544	     conpty-agent
    0	    63	  6924	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.6.0
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31077528

```

</details>

**Comment by Geor17** [comment]
I think i found the solution, it seems to be an issue with Nvidia GPU.

**Comment by Geor17** [comment]
![image](https://github.com/microsoft/vscode/assets/110853923/f8a38340-e1b7-4c76-a4e3-4d11f9d9d90c)
We have to go here and disable "Image Scaling" or "Image Sharpening" and voila.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/124226
