### ISSUE TITLE
Mouse cursor disappears in editable windows

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode#217357]
Does this issue occur when all extensions are disabled? Yes

```
Version: 1.90.2 (user setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.26100
```

Steps to Reproduce:

1. Run VSCode on Windows 11 24H2
2. Move mouse over editable windows e.g., code editor or terminal pane.

Mouse cursor disappears initially. It often comes back when you move it again. ~~I tried recording a screencast but the mouse cursor always shows up, so~~ this may be some sort of accessibility issue with the editor? I can't replicate it in other editor implementations e.g., notepad.exe. The mouse cursor also always shows over (default) non-editable panes like the explorer pane or an output pane. Seems it's just something with the editor.

This is causing significant productivity issues since I can't see where my cursor is, and though I use a combination of keyboard and mouse, I'm often starting off with my mouse to click into where I need...which I can't see, so I'm having to zero in on where I want or revert to only using the keyboard. I started coding before mice were mainstream. I'd rather not have to go back.

Edit: recorded a screencast using my phone since the cursor would always show up when doing a screencast on the computer itself, hence wondering if this might be related to accessibility or something.

https://github.com/microsoft/vscode/assets/1532486/d4b5109a-045e-41df-a487-babaed4832d9

**Comment by deepak1556** [comment]
Can you confirm if starting the application with `--disable_direct_composition=1` helps ?

**Comment by deepak1556** [comment]
Please also check if the issue is addressed with our [exploration builds](https://vscode.download.prss.microsoft.com/dbazure/download/exploration/874284c6e45a08f900ddf83115f70ed9c52d38c8/VSCodeUserSetup-x64-1.91.0-exploration.exe)

**Comment by heaths** [comment]
> Can you confirm if starting the application with `--disable_direct_composition=1` helps ?

I've been running VSCode started with this switch for about an hour now and have not seen the issue, so that seems to be related or even the cause. Prior, I seem to recall the issue of the disappearing mouse cursor to be immediate. As the system strained (vmmmem ever-growing) the mouse would stay invisible longer. Typically, if I moved the mouse enough it would appear but would take longer if the system was under strain. It was inconsistent, though.

**Comment by Nirmal4G** [comment]
I'm hitting this too. But on all text fields everywhere in all the apps not just VSCode. It is especially worse in Electron/Chromium based apps. The least badly affected are UWP apps. IMO, seems to be problem with 24H2 update. Setting the mouse theme to "Windows Black" helps but I don't know if it is a problem with the theme or the graphics sub-system.

**Comment by Nirmal4G** [comment]
As I suspected, the actual problem is in Windows! apparently GDI and Windows Composition are trying to one up the other. 😂

Some background on this issue is in chromium bug report: [chromium#40239916](https://issues.chromium.org/issues/40239916#comment72)

Temporary fix is to [disable MPO in DWM](https://github.com/microsoft/vscode/issues/204103#issuecomment-2163999095) without needing to change the pointer theme.

**Comment by deepak1556** [comment]
I will merge this to https://github.com/microsoft/vscode/issues/204103, pending fix in the OS. Please try one of the workarounds mentioned in the upstream issue 

1) Try pointer themes with shadows
2) Disable dwm composition with `--disable_direct_composition=1` but has impact on rendering performance.
