### ISSUE TITLE
Option to choose quotes for add missing import feature

### ISSUE THREAD

**Issue by cyrilletuzi** [Microsoft/vscode#21730]
- VSCode Version: 1.10.1
- OS Version: macOS

Steps to Reproduce:

1. `class A implements B {}`
2. Use the new quick fix option to "import B from x".
3. Works, but uses double quotes for the import path (`import { B } from "x"`), which breaks linting in projects configured with single quotes only (like Angular ones).

**Comment by mjbvz** [comment]
Thanks. This being tracked upstream by https://github.com/Microsoft/TypeScript/issues/13270
