### ISSUE TITLE
Error processing "setBreakpoints" on console using new inspector protocol, but breakpoint works

### ISSUE THREAD

**Issue by jmesa-sistel** [Microsoft/vscode#21731]
- VSCode Version: 1.10.1
- OS Version: Windows 10

Steps to Reproduce:

I have a project with node in typescript with sourcemaps.
Using this configuration:

            "type": "node",
            "request": "launch",
            "protocol": "auto",
            "name": "Iniciar programa",
            "program": "${workspaceRoot}\\src\\app.ts",
            "outFiles": [ "${workspaceRoot}\\dist\\**\\*.js" ]

With the new inspector protocol I have an error on console when I set or remove a breakpoint when debugging, but the breakpoint works.
Console output when I set or remove a breakpoint:
`Error processing "setBreakpoints": Error: Set breakpoints request timed out
    at Timeout.setTimeout (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\utils.js:55:24)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
Thu, 02 Mar 2017 09:04:15 GMT express deprecated req.host: Use req.hostname instead at <anonymous>:1:49`

**Comment by roblourens** [comment]
Which version of Node are you using? Probably 7.5 or .6 in which case this is https://github.com/nodejs/node/issues/11589

**Comment by jmesa-sistel** [comment]
You are right, node v7.7.0

**Comment by roblourens** [comment]
Ok. This is a nasty bug. But you'll see the same thing using chrome devtools, and there's not a lot I can do.

**Comment by roblourens** [comment]
I should add a note to docs somewhere...

**Comment by jmesa-sistel** [comment]
ok, thank you.
Closing it.

**Comment by roblourens** [comment]
I'll leave it open so I remember to make a note somewhere :)

**Comment by jmesa-sistel** [comment]
What a powerful todo list  ;)

**Comment by roblourens** [comment]
I made a change to make this a slightly better experience. And I wrote a SO question for people to find: http://stackoverflow.com/questions/42567417/error-set-breakpoints-request-timed-out-while-debugging-node-in-vs-code/42567422#42567422

It seems like a too specific thing to add to official docs, but I did want to write it down somewhere.
