### ISSUE TITLE
editor.defaultFormatter configuration is ignored in Codespace

### ISSUE THREAD

**Issue by barberadam** [microsoft/vscode#217380]
Type: <b>Bug</b>

# Behaviour

In a Github codespace, we have the Python extension as well as the "ms-python.black-formatter" extension. In our devcontainer.json we have:
```
"features": {
  "ghcr.io/devcontainers/features/python:1": {
    "installTools": true,
    "version": "3.11"
  },
  ....
},
...
"customizations": {
  "vscode": {
    "settings": {
      "[python]": {
        "editor.defaultFormatter": "ms-python.black-formatter"
      },
      ...
    },
    "extensions": [
      "ms-python.black-formatter",
      ...
    ]
  }
}
```

The black formatter is installed, but when I go to format the Python extension asks me to configure a default between `black` and `autopep8`. This configuration doeesn't seem to persist anywhere either. I don't see conflicting settings in my other JSON settings files.

Output->Python shows: `Default formatter is set to null for workspace /workspaces/...`

## Steps to reproduce:

1. Create a `devcontainer.json` file as described above and a Dockerfile using `mcr.microsoft.com/devcontainers/python:1-3.11-bullseye`
2. Launch the codespace and wait for it to bulid and for all extensions to be installed
3. Attempt to format a python file

# Diagnostic data

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
2024-06-24 18:02:39.421 [info] Experiment 'pythonCreateEnvOnPipInstall' is active
2024-06-24 18:02:39.421 [info] Experiment 'pythonRecommendTensorboardExt' is active
2024-06-24 18:02:39.421 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2024-06-24 18:02:39.421 [info] Experiment 'pythonTestAdapter' is active
2024-06-24 18:02:39.421 [info] Default formatter is set to null for workspace /workspaces/dbt
2024-06-24 18:02:40.465 [info] > /usr/local/bin/python -I ~/.vscode-remote/extensions/ms-python.python-2024.8.1/python_files/get_output_via_markers.py ~/.vscode-remote/extensions/ms-python.python-2024.8.1/python_files/interpreterInfo.py
2024-06-24 18:02:40.480 [info] > pyenv which python
2024-06-24 18:02:40.480 [info] cwd: .
2024-06-24 18:02:40.672 [info] Python interpreter path: /usr/local/bin/python
2024-06-24 18:02:46.551 [info] Starting Pylance language server.
```

</p>
</details>

Extension version: 2024.8.1
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:54:35.075Z)
OS version: Darwin arm64 23.3.0
Modes:
Remote OS version: Linux x64 6.5.0-1021-azure
Remote OS version: Linux x64 6.5.0-1021-azure

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.9
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>
<summary>User Settings</summary>
<p>

```

languageServer: "Pylance"

testing
• pytestArgs: "<placeholder>"
• pytestEnabled: true

```
</p>
</details>

<details>
<summary>Installed Extensions</summary>

|Extension Name|Extension Id|Version|
|---|---|---|
|autopep8|ms-python.autopep8|2024.0.0|
|Better Jinja|samuelcolvin.jinjahtml|0.20.0|
|Black Formatter|ms-python.black-formatter|2024.2.0|
|ESLint|dbaeumer.vscode-eslint|3.0.10|
|GitHub Copilot|GitHub.copilot|1.207.0|
|GitHub Copilot Chat|GitHub.copilot-chat|0.16.1|
|GitHub Pull Requests|GitHub.vscode-pull-request-github|0.90.0|
|Power User for dbt Core™|innoverio.vscode-dbt-power-user|0.40.3|
|Pylance|ms-python.vscode-pylance|2024.6.1|
|Pylint|ms-python.pylint|2023.10.1|
|Python|ms-python.python|2024.8.1|
|Python Debugger|ms-python.debugpy|2024.6.0|
|Table Visualizer for JavaScript Profiles|ms-vscode.vscode-js-profile-table|1.0.9|
</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
legacy_priority:31077528

```

</details>

**Comment by jrieken** [comment]
> This configuration doeesn't seem to persist anywhere either. I don't see conflicting settings in my other JSON settings files.

Please check your user-settings because that's where the choice is persisted. We don't write into workspace settings because it will affect the whole team that also works on this project and such changes require more explicit action, like manually configuring the default formatter

**Comment by barberadam** [comment]
> > This configuration doeesn't seem to persist anywhere either. I don't see conflicting settings in my other JSON settings files.
> 
> Please check your user-settings because that's where the choice is persisted. We don't write into workspace settings because it will affect the whole team that also works on this project and such changes require more explicit action, like manually configuring the default formatter

It is not being persisted in my User settings. This may be because this is running in a codespace. I do see:
```
	"[python]": {
		"editor.defaultFormatter": "ms-python.black-formatter"
	},
```
in my Remote settings, but that comes from my `devcontainer.json` and is not being respected (VSCode asks me to set the default formatter every time).

I did clean up some old (seemingly inactive) settings in my User Settings and maybe that resolved it? I'll go ahead and close and re-open if the issue pops up again.
