### ISSUE TITLE
"Report issues" menu item does not work

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#21737]
When I press the menu item, usually a Github issues form opens up in a browser, but now nothing happens.

- VSCode Version: 1.10.1
- OS Version: W10

Steps to Reproduce:

1. open menu item Help/Report Issues
2. nothing happens

**Comment by michelkaporin** [comment]
Wasn't able to reproduce.

**Comment by PunchyRascal** [comment]
What should I do then?

**Comment by michelkaporin** [comment]
Do you have system configured default program (browser) to open http links?

**Comment by PunchyRascal** [comment]
Yes - for example when I click the "Documentation" menu item in the same Help menu, it opens https://code.visualstudio.com/docs#vscode in my browser.

**Comment by michelkaporin** [comment]
Works good for me on the same setup as you have. 

Answering your question on 'What should I do then?' Just follow the following guidelines manually if you want to create an issue: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md
Essentialy this menu item just opens a GitHub issue report page with predefined template.

**Comment by PunchyRascal** [comment]
I know what it does, I was asking what should I do with this bug report if you say that you can't reproduce it. But apparently you closed it, so I probably shouldn't bother.

**Comment by michelkaporin** [comment]
It would be good to have more details about your setup. Which browser, version are you using?


Can you copy over this link and paste it in your default browser?
https://go.microsoft.com/fwlink/?LinkId=534872&body=-%20VSCode%20Version%3A%20Code%20-%20Insiders%201.11.0-insider%20(4db944bc08e34fb15c5805927d9cb67470776606%2C%202017-03-02T07%3A10%3A18.838Z)%0A-%20OS%20Version%3A%20Windows_NT%20ia32%2010.0.14393%0A-%20Extensions%3A%20none%0A---%0A%0ASteps%20to%20Reproduce%3A%0A%0A1.%0A2.

Can you create this link on your local file system and navigate through it, will it be opened?

**Comment by PunchyRascal** [comment]
I use Vivaldi browser:
-----------------------
Vivaldi	1.7.735.46 (Stable channel) (32-bit)
Revision	b5bc5a3efa32f49a389ebf766e3aa3c5215b6a20
OS	Windows 
JavaScript	V8 5.6.329
Flash	24.0.0.194 

Windows info:
------------------
OS Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	I-THINK
System Manufacturer	LENOVO
System Model	20B00008MC
System Type	x64-based PC
System SKU	LENOVO_MT_20B031_BU_Think_FM_ThinkPad S5-S531
Processor	Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz, 1801 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	LENOVO GKET33WW (1.13 ), 27. 8. 2014

Using the link
------------------
Upon clicking your link, it opens up the new issue form on github:
![image](https://cloud.githubusercontent.com/assets/821272/23510708/e8dac818-ff5a-11e6-9c8c-d61a61a0421d.png)
When I create new file - type shortcut (New Internet shortcut.url), it works ok as well - opens up the new issue form.

And like I said, other links in the Help menu work fine - Documentation, Join us on Twitter etc.

**Comment by michelkaporin** [comment]
I have tried reproducing it with Vivaldi browser and no luck, it seems also that there is no problem with amount of characters in the query string when reporting a bug. Added to March milestone for further analysis and reproduction.

**Comment by michelkaporin** [comment]
@PunchyRascal Most likely it is the case that your instance of VS Code does not pass integrity checks. Have you touched any of these files in the installation folder of VS Code?

> resources/app/out/vs/workbench/electron-browser/workbench.main.js
> resources/app/out/vs/workbench/electron-browser/workbench.main.css		
> resources/app/out/vs/workbench/electron-browser/bootstrap/index.html
> resources/app/out/vs/workbench/electron-browser/bootstrap/index.js
> resources/app/product.json

**Comment by PunchyRascal** [comment]
Not that I am aware of, they all have the same timestamp from 8 Mar 2017, which is I presume when I last updated VScode. The button still does not work.

**Comment by michelkaporin** [comment]
@PunchyRascal Sorry, last question - how many extensions do you have installed? Maybe the link is too long to be opened by the browser because you have too many of them installed, and we try to concatenate all of them in the URL to report issue.

**Comment by PunchyRascal** [comment]
No worries. I have lots of extensions since I tried lots of themes. Most are disabled, but they are still there I suppose, cca. 40 - 50.

**Comment by PunchyRascal** [comment]
AHA! I uninstalled about 10 themes and voilla! The link works :-)

**Comment by michelkaporin** [comment]
@PunchyRascal Great! I will speak to the team if we would like to tackle this case programmatically in future.

**Comment by michelkaporin** [comment]
For verification:
1. Add many extensions that produce extensions table for GitHub issue that is more than 1750 characters.
2. Click on Report Issues
3. Github should open with the following text under 'extensions':
`the listing exceeds the lower minimum of browsers' URL characters limit`

**Comment by ramya-rao-a** [comment]
@michelkaporin I can still repro this.

I installed about 40 extensions and the Report Issues does nothing
I uninstalled all of them and Report Issues starts working.

Am using Insiders dated 31st March, 2017 on Windows 10

**Comment by michelkaporin** [comment]
@ramya-rao-a good spot! Forgot to encode URI before performing length check.
