### ISSUE TITLE
slow start on https://github.com/rsdn/CodeJam project

### ISSUE THREAD

**Issue by alexey-tyulkin** [Microsoft/vscode#21732]
[97de_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/813231/97de_main.cpuprofile.txt)
[97de_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/813230/97de_renderer.cpuprofile.txt)

- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:10:18.838Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)</code>
- Memory (System): <code>15.83GB (6.91GB free)</code>
- Memory (Process): <code>142.33MB working set (149.62MB peak, 107.61MB private, 35.89MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|31|
|main|app.isReady => window.loadUrl()|300|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|359|
|renderer|require(workbench.main.js)|1159|
|renderer|create extension host => extensions onReady()|1800|
|renderer|restore viewlet|459|
|renderer|restore editor view state|762|
|renderer|overall workbench load|2166|
|main + renderer|start => extensions ready|3810|
|main + renderer|start => workbench ready|4035|

**Comment by jrieken** [comment]
Thanks. We could identify https://github.com/Microsoft/vscode/issues/22086 and #21963 in those traces
