### ISSUE TITLE
[js] Salsa - JS ReactNative - use the TypeScriptReact grammar for JS

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#2174]
To support ReactNative, which uses JSX constructs inside .js files, We should use the typescriptReact grammar for JS.

Salsa will also make the change to use the JSX parser for JS.

**Comment by egamma** [comment]
Salsa is now using the same parser for .jsx and for .js files, this means it also supports jsx constructs in .js files. Now the coloring of the jsx constructs is missing for full ReactNative support.

**Comment by jpierson** [comment]
Does 0.10.7 include any of the Salsa stuff?

**Comment by egamma** [comment]
@jpierson yes, but you have to enable it. Please see https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/latest.md
