### ISSUE TITLE
Settings suggestions are broken

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#21745]
Latest insiders or out of dev

1. settings.json
2. Trigger intelli-sense - no suggestions

This makes it impossible to discover settings.

![screen shot 2017-03-02 at 11 12 17](https://cloud.githubusercontent.com/assets/1926584/23502729/1cbfbd54-ff39-11e6-8ac8-53d010c13020.png)

**Comment by sandy081** [comment]
Duplicate #21704
