### ISSUE TITLE
AltGr (Right Alt) issues (HU keyboard layout) with plugins (or other Ctrl+Alt+ keybindings)

### ISSUE THREAD

**Issue by realee94** [Microsoft/vscode#21746]
- VSCode Version: 1.11.0-insider
- OS Version: Windows 10 Pro 64bit

Steps to Reproduce:

1.  Install plugin (RestAPI client or Deploy for example)
2. Press right alt + F ( '[' character ) or right alt + C ( '&' ) and it fires the plugin's shortcut which is defined as Ctrl+Alt+F, etc.

Is there a fix apart from rebinding the plugin keymaps all the time?

**Comment by isidorn** [comment]
You should be able to configure nicely all the keybindings in your keybindings.json.
Your user defined keybindings will take priority over the extension keybidnigns.

Preferences > keyboard shortcuts
