### ISSUE TITLE
Not getting css/scss suggestions since 1.10.1 upgrade

### ISSUE THREAD

**Issue by Nikki1993** [Microsoft/vscode#21748]
- VSCode Version: 1.10.1
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Create a scss file
2. type anything like `background-size:` then hit ctrl + space to get suggestions 
3. Embrace endless loading screen. 

<img width="581" alt="screen shot 2017-03-02 at 12 25 17" src="https://cloud.githubusercontent.com/assets/1446529/23503244/7e824b38-ff43-11e6-8627-378ae645fff0.png">

**Comment by mrmlnc** [comment]
Please, provide your list of installed extensions 🐼

**Comment by Nikki1993** [comment]
I got 

2gua.rainbow-brackets
HookyQR.beautify
IBM.output-colorizer
Shan.code-settings-sync
Zignd.html-css-class-completion
abusaidm.html-snippets
akamud.vscode-theme-onedark
alefragnani.project-manager
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
dbaeumer.vscode-eslint
donjayamanne.githistory
eg2.tslint
formulahendry.auto-rename-tag
idleberg.hopscotch
ionutvmi.path-autocomplete
johnpapa.Angular2
jrebocho.vscode-random
keyring.Lua
nwallace.language-vscode-javascript-angular2
rbbit.typescript-hero
robertohuertasm.vscode-icons
seanmcbreen.Spell
spywhere.guides
xabikos.JavaScriptSnippets

What's funny @mrmlnc is that after running `code --disable-extentions` and then re-running code normally via `code .` with all extensions turned on, suggestions do work. What might have happened?

**Comment by aeschli** [comment]
When you ran VS Code  with 'code --disable-extentions' did you still see the issue?

If you have this reproducible, please check out the developer tools console if there is anything suspicious.
Also there's the [pulse-monitor extension](https://marketplace.visualstudio.com/items?itemName=aeschli.vscode-pulse-monitor) that can provide additional logging.

**Comment by Nikki1993** [comment]
@aeschli I couldn't reproduce the issue without extensions, but as I mentioned earlier, after relaunching vscode with all extensions enabled there was no issue, as if certain extensions perhaps failed to load after update or smth. I will monitor the situation and see if I can reliably reproduce this behaviour if at all.

**Comment by aeschli** [comment]
Thanks @Nikki1993 . I'll close the issue for now, assuming it is related to an extension. Feel free to reopen anytime if you see it more often or even have steps to reproduce.
