### ISSUE TITLE
Prompted slow startup issue

### ISSUE THREAD

**Issue by arebee** [Microsoft/vscode#21742]
- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:10:18.838Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Xeon(R) CPU E3-1245 v3 @ 3.40GHz (8 x 3392)</code>
- Memory (System): <code>7.91GB (3.76GB free)</code>
- Memory (Process): <code>119.72MB working set (149.63MB peak, 94.53MB private, 27.44MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|30|
|main|app.isReady => window.loadUrl()|523|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|266|
|renderer|require(workbench.main.js)|1159|
|renderer|create extension host => extensions onReady()|12436|
|renderer|restore viewlet|0|
|renderer|restore editor view state|1|
|renderer|overall workbench load|2495|
|main + renderer|start => extensions ready|15511|
|main + renderer|start => workbench ready|4488|

---
[8fc6_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/813359/8fc6_renderer.cpuprofile.txt)
[8fc6_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/813360/8fc6_main.cpuprofile.txt)

**Comment by jrieken** [comment]
Thanks. Looking at the traces I can spot these issues with will make sure to get fixed soon: #21963, https://github.com/Microsoft/vscode/issues/22086, and https://github.com/Microsoft/vscode/issues/22090

**Comment by arebee** [comment]
Thanks!
