### ISSUE TITLE
Keybindings editor's info tooltips are misaligned

### ISSUE THREAD

**Issue by azixMcAze** [Microsoft/vscode#21740]
- VSCode Version: 1.10.1
- OS Version: macOS 10.12.3 & Windows 10 (both in french)

The info tooltip displaying the keybinding in the current keyboard layout is not aligned with the key combinations and some info tooltips are displayed where there is no key combination. The key displayed on the tooltip text for these bogus tooltips is ";"

The cursor position is also misaligned on lines with info tooltips. 

In the screenshot, the cursor is at the end of line 3, typing text will insert it after the comma, but the cursor is displayed 2 characters before. On line 7 the cursor will be displayed 4 characters before. The rest of a line after a word-wrap is not affected.

![capture d ecran 2017-03-02 a 10 32 53](https://cloud.githubusercontent.com/assets/1919205/23501303/ad6f8614-ff33-11e6-99fc-fb04825a67b1.png)

This affects the user's keybinding.json editor and the Default key combinations editor. The issue was already present in VSCode 1.9.

**Comment by alexandrudima** [comment]
workaround: use the setting `"editor.disableMonospaceOptimizations": true`
