### ISSUE TITLE
insider version 1.11.0

### ISSUE THREAD

**Issue by mindfocus** [Microsoft/vscode#21741]
- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:10:18.838Z)</code>
- OS Version: <code>Windows_NT ia32 6.1.7600</code>
- CPUs: <code>Intel(R) Xeon(R) CPU E3-1220 v3 @ 3.10GHz (4 x 3092)</code>
- Memory (System): <code>7.83GB (2.55GB free)</code>
- Memory (Process): <code>196.86MB working set (196.86MB peak, 92.23MB private, 95.95MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|37|
|main|app.isReady => window.loadUrl()|366|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|2220|
|renderer|require(workbench.main.js)|2035|
|renderer|create extension host => extensions onReady()|1929|
|renderer|restore viewlet|543|
|renderer|restore editor view state|959|
|renderer|overall workbench load|2446|
|main + renderer|start => extensions ready|6814|
|main + renderer|start => workbench ready|7142|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\Administrator\3182_main.cpuprofile.txt`
-`C:\Users\Administrator\3182_renderer.cpuprofile.txt`

[Uploading 3182_renderer.cpuprofile.txt…]()
[Uploading 3182_main.cpuprofile.txt…]()

**Comment by mindfocus** [comment]
thanks very much

**Comment by jrieken** [comment]
@mindfocus Sorry, but the profile files are missing

**Comment by jrieken** [comment]
closing because profiles are missing...
