### ISSUE TITLE
Minimap: screen does not move along when dragging below the minimap end

### ISSUE THREAD

**Issue by SteveVanOpstal** [Microsoft/vscode#21744]
- VSCode Version: 1.10.1
- OS Version: Windows 10

Steps to Reproduce:

1. Take a file where the minimap does not fill your entire screen
2. Start dragging below where the file in the minimap ends
3. Drag upwards
![minimap_error](https://cloud.githubusercontent.com/assets/7734728/23501999/7592620e-ff36-11e6-9efc-47798e097696.gif)

I expected the screen to move along

**Comment by alexandrudima** [comment]
The slider will drag only when clicking on the slider. Clicking on any other region in the minimap will reveal the clicked line in the center of the viewport. See also #21708
