### ISSUE TITLE
Intellisense in sass is confusing

### ISSUE THREAD

**Issue by ArkhipovK** [Microsoft/vscode#21747]
While using itellisense within sass file, i've noticed that the proposed list of values is huge and arranged in alphabetical order.  I think it much more useful when the order is based on type of value. Is is possible?
![default](https://cloud.githubusercontent.com/assets/9945452/23502183/b8644472-ff58-11e6-85dd-7023e3cf9ed2.png)

**Comment by aeschli** [comment]
We already filter values based on the type. What's missing is the filtering for functions. That's #23576.
For variables it would be more difficult as we would have to detect the type from the values assigned to is. I personally don't think we should hide any variables, it would just be confusing.
