### ISSUE TITLE
Add Toggle Minimap command

### ISSUE THREAD

**Issue by Leedehai** [Microsoft/vscode#21754]
- VSCode Version: 1.10.1
- OS Version: macOS 10.12

I hope there is a hotkey to display and hide the minimap (like, cmd+M). Toggling the minimap in the settings.json file every time I want to see it is distracting.

**Comment by hoovercj** [comment]
@Leedehai I have published an extension that allows you to change any setting using keyboard commands. It is called [Settings Cycler](https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler) and it allows you to cycle through different values for a setting -- either to enable or disable a setting or to cycle between values (for example, themes).

I hope it helps!

**Comment by Leedehai** [comment]
Wow that's really great! Thanks a lot!






On Fri, Mar 10, 2017 at 1:28 PM -0800, "Cody Hoover" <notifications@github.com> wrote:












@Leedehai I have published an extension that allows you to change any setting using keyboard commands. It is called Settings Cycler and it allows you to cycle through different values for a setting -- either to enable or disable a setting or to cycle between values (for example, themes).


I hope it helps!

**Comment by y0n1** [comment]
👍

**Comment by alexandrudima** [comment]
Related: #22423

**Comment by rgraham717** [comment]
Toggling the minimap shouldn't require a plugin.  Even a menu option like Sublime would be better than simply a setting in the json file.

**Comment by eduardomart** [comment]
The Microsoft way, make everything that should be simple, annoyingly impossible.

**Comment by ajmas** [comment]
Even without a hot key, simply having it in the view menu would be a useful starting point.

**Comment by monk-time** [comment]
The command was added in 1.16 with https://github.com/Microsoft/vscode/commit/3927d042875f80d00f69379cdb9f8f6b744e647b.
