### ISSUE TITLE
Editor panel getting off screen in split screen

### ISSUE THREAD

**Issue by Shashwat-0077** [microsoft/vscode#217571]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 

Type: Bug

All extensions were disabled when issue occured

How to reproduce
Step 1 : create 2 files
Step 2 : open them side by side in the editor
Step 3 : now on the left hand side editor panel write something really long, you will see that after some characters panel will go off screen to the left

Reloading the window would solve the problem, but this shouldnt happens in the first place, window should not go off screen

https://github.com/microsoft/vscode/assets/102245652/4b1f192c-0074-4d3d-a372-16b072784427

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.86GB (3.51GB free)|
|Process Argv|--crash-reporter-id c1484ebf-826e-4c1f-b711-833d42388471|
|Screen Reader|yes|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31077528

```

</details>

**Comment by hediet** [comment]
Can you share your settings?

**Comment by Shashwat-0077** [comment]
> Can you share your settings or try in an empty profile? This does not happen for me.

Should i share my user's settings json ?

**Comment by hediet** [comment]
> Should i share my user's settings json ?

Please! Just make sure you remove PII.

**Comment by Shashwat-0077** [comment]
Dont know how, but the issue is solved on its own, no more of that panel displacement
