### ISSUE TITLE
slow start

### ISSUE THREAD

**Issue by idkjs** [Microsoft/vscode#21752]
- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:04:47.508Z)</code>
- OS Version: <code>Darwin x64 15.6.0</code>
- CPUs: <code>Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)</code>
- Memory (System): <code>8.00GB (0.32GB free)</code>
- Memory (Process): <code>178.05MB working set (0.00MB peak, 123.60MB private, 95.11MB shared)</code>
- Load (avg): <code>2, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|138|
|main|app.isReady => window.loadUrl()|515|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|571|
|renderer|require(workbench.main.js)|1978|
|renderer|-> of which require() node_modules|161|
|renderer|create extension host => extensions onReady()|1168|
|renderer|restore viewlet|456|
|renderer|restore editor view state|1523|
|renderer|overall workbench load|1945|
|main + renderer|start => extensions ready|4527|
|main + renderer|start => workbench ready|5178|

---

:warning: Make sure to **attach** these files: :warning:
-`/Users/klik/6832_main.cpuprofile.txt`
-`/Users/klik/6832_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
closing because profile-files are missing

**Comment by idkjs** [comment]
[6832_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/824017/6832_renderer.cpuprofile.txt)
[Uploading 6832_main.cpuprofile.txt…]()

**Comment by jrieken** [comment]
@idkjs Sorry, the last file didn't finish uploading
