### ISSUE TITLE
Support for GitHub Flavored Markdown

### ISSUE THREAD

**Issue by db6edr** [Microsoft/vscode#2175]
In the Common Questions section of https://code.visualstudio.com/docs/languages/markdown it says "Code supports GitHub Flavored Markdown".

This support is incomplete as at least Code's internal preview does not render task lists correctly. They are described as part of GFM here: https://help.github.com/articles/writing-on-github/

Please add this to Code's previewer.

**Comment by bpasero** [comment]
We support what ever marked support: https://github.com/chjj/marked

**Comment by db6edr** [comment]
Ok, I'll take my request there.
Could you please update the answer in the Common Questions section?

**Comment by bpasero** [comment]
Done: https://github.com/Microsoft/vscode-docs/commit/930ab8bb995f9237ee580f37e0babfaf8dd0eb90

**Comment by db6edr** [comment]
Great, thanks!

**Comment by rob3c** [comment]
Hi, I love that vscode has the markdown preview feature! Unfortunately, the marked project that you're depending on appears to be dead :-(

Are there any plans to move to something more active where support for things like task list support will actually have a chance of being addressed?

**Comment by agusmba** [comment]
yep, the PR is there but nobody merges or answers, see chjj/marked#587

**Comment by txomon** [comment]
I looks like marked project is unmaintained. 304+ issues, 150 open PRs, and no commits since  January 14...

**Comment by SimplyInk** [comment]
Is github flavored task-list supported?

https://help.github.com/articles/basic-writing-and-formatting-syntax/#task-lists

This would be awesome!

**Comment by agusmba** [comment]
@SimplyInk you could check out [vscode-markdown-checkboxes](https://github.com/mjbvz/vscode-markdown-checkboxes)

That plugin is referenced from the abandoned PR I mentioned above. I haven't tested it yet but will probably do so real soon.
