### ISSUE TITLE
Mistranslation in Japanese

### ISSUE THREAD

**Issue by yu-miura** [Microsoft/vscode#21758]
- VSCode Version: 1.10.1
- OS Version: Windows 10

The **Go** menu **Forward** is translated as 転送 in Japanese.
We usually translate "forward" which is the antonym of "back" as "次へ" which is the antonym of "戻る".
"転送" is a word for email.
Thank you!

**Comment by hasan-abdul-rahman** [comment]
> "転送" is a word for email.

I didn't understand until I looked up in a dictionary; "email forwarding".

**Comment by johnliu2016** [comment]
Mistranslation in following resource string, correct is "次へ"

ResID 0;"menus.js"\0;"Strings"\".resx", 0;"miForward" 
File: src\vs\code\electron-main\menus.nls.resx.lcg

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Linguistic answer:

Agree that the current translation is not appropriate in the context. As the suggested "次へ" is usually a translation of "Next". Considering consistency suggesting alternate translation.

File: src\vs\code\electron-main\menus.nls.resx
ID: ".resx", 0; "miForward"
SRC: &amp;&amp;Forward
TGT: 進む(&amp;&amp;F)
