### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lsxredrain** [Microsoft/vscode#21755]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|git-easy|bibhasdn|1.9.1|
|vscode-npm-script|eg2|0.1.8|
|git-project-manager|felipecaputo|1.0.1|
|vscode-npm|fknop|3.3.0|
|debugger-for-chrome|msjsdiag|2.5.5|
|vscode-icons|robertohuertasm|6.0.0|;

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Please provide more details and steps.
What error are you seeing, how to reproduce that error?

**Comment by ramya-rao-a** [comment]
@lsxredrain Closing this issue as we havent heard back from you in a while.

If you can provide us more details, steps to reproduce the issue and some screenshots, then we can re-open this issue
