### ISSUE TITLE
Crashing in debug model

### ISSUE THREAD

**Issue by saurabhnachankar** [Microsoft/vscode#21757]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharpextensions|jchannon|1.3.0|
|net-core-project-manager|ksubedi|0.3.6|
|csharp|ms-vscode|1.7.0|
|vscode-icons|robertohuertasm|7.3.0|;

---

Issue - crashing in debug mode.

**Comment by isidorn** [comment]
Can you please provide more details?
What app are you debugging? Do you constantly see this? 
Do you also see this if you disable all your extensions?

**Comment by saurabhnachankar** [comment]
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace ErpOneCore
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
    }
}

It stops at host.run()

**Comment by isidorn** [comment]
Please file this against the vscode C# extension here https://github.com/OmniSharp/omnisharp-vscode
