### ISSUE TITLE
Had solved the VSCODE 

### ISSUE THREAD

**Issue by saurabhnachankar** [Microsoft/vscode#21759]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharpextensions|jchannon|1.3.0|
|net-core-project-manager|ksubedi|0.3.6|
|csharp|ms-vscode|1.7.0|
|vscode-icons|robertohuertasm|7.3.0|;

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Please add more details to this issue. What is going wrong, what are the steps to reproduce.

**Comment by ramya-rao-a** [comment]
@saurabhnachankar  Closing this issue as we havent heard back from you in a while.

If you can provide us more details, steps to reproduce the issue and some screenshots, then we can re-open this issue
