### ISSUE TITLE
JSON language server error with settings

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#21751]
- VSCode Version: Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:04:47.508Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.8|
|mono-debug|ms-vscode|0.15.3|
|debugger-for-chrome|msjsdiag|2.5.5|;

---

Steps to Reproduce:

1. start VS Code Insider on a vscode workspace
2. open settings

Observe: the following JSON language server error appears on the output channel:

```
[Error - 11:42:31 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Invalid regular expression: /\[(plaintext|Log|plaintext|Log|bat|clojure|coffeescript|c|cpp|csharp|css|diff|dockerfile|fsharp|git-commit|git-rebase|go|groovy|handlebars|hlsl|html|ini|properties|java|javascriptreact|javascript|jsx-tags|json|less|lua|makefile|markdown|objective-c|objective-c++|perl|perl6|php|powershell|jade|python|r|razor|ruby|rust|scss|shaderlab|shellscript|sql|swift|typescript|typescriptreact|vb|xml|xsl|yaml|testOutput)\]$/: Nothing to repeat
  Code: -32603 
```

**Comment by weinand** [comment]
The reg exp was broken by the addition of the "objective-c++" language.

**Comment by sandy081** [comment]
duplicates #21704
