### ISSUE TITLE
Zen mode file unsaved indicator

### ISSUE THREAD

**Issue by Nighthawk22** [Microsoft/vscode#21762]
- VSCode Version: 1.10.1
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. Open file in zen mode
2. Change it

For me the unsaved file indicator near the name of the file is missing in the zen mode.

**Comment by bpasero** [comment]
@Nighthawk22  when tabs are disabled, the indicator is on the right hand side where the close button is.

**Comment by Nighthawk22** [comment]
I can't find it?! 😂

![Uploading Screenshot at März 02 12-58-40.png…]()

**Comment by bpasero** [comment]
@isidorn a bug in Zen mode? The close button seems gone.

**Comment by Nighthawk22** [comment]
Note: it's on mac os in fullscreen mode. The close button are only visible on hover at top. The close button does change when the file is unsaved. But it is not visible all the time.

**Comment by isidorn** [comment]
Yes there seems to be the issue.
When using the part service to hide tabs the title bar does not update to show the close button and the dirty indicator.

**Comment by isidorn** [comment]
@Nighthawk22 nice catch. It should be fixed in the next insiders.
I was improparly keeping tab options state in some clases which should just get it from a central place.
