### ISSUE TITLE
Option to set spaces after/before braces in import statements typescript

### ISSUE THREAD

**Issue by kukjevov** [Microsoft/vscode#21763]
- VSCode Version: 1.10.1
- OS Version: Windows 10

Steps to Reproduce:

1. Currently when i use quick fix "Add missing import" (which is totally awesome feature) i get 
`import { Something } from 'something'`
2. It would be nice to have option to specify whether put spaces after `{` and before `}` braces, so i could get 
`import {Something} from 'something'` without spaces

Thank you for great job

**Comment by mjbvz** [comment]
Thanks. This is being tracked by https://github.com/Microsoft/vscode/issues/18043

TS 2.3 preview builds includes a support for this option, so we will pick up support for it once we adopt the final TS 2.3 release in VSCode
