### ISSUE TITLE
[suggestion] There should be a "Goto Next Change" in diff view

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#21765]
- VSCode Version: ANY
- OS Version: ANY

Just like the <kbd>F8</kbd> key for jumping to next error/warning, the git (scm) diff view should also have a goto next / previous change. With the new `Stage Selected Ranges` command, I can use partially use my keyboard for committing, so this feature would improve that experience.

**Comment by joaomoreno** [comment]
#21561
