### ISSUE TITLE
Intellisense popup gets in the way. It should be locatable elsewhere in the UI

### ISSUE THREAD

**Issue by jsumners** [Microsoft/vscode#21769]
- VSCode Version: 1.10.0
- OS Version: macOS 10.12.3

In the screenshot below the encircled popup is _very_ annoying. I do not like the way that it covers up code that I may want to read while typing. I would like to move it to the top right corner of the editor via CSS or some other mechanism. It's nice to have the information, but not in such an obtrusive way.

![image](https://cloud.githubusercontent.com/assets/321201/23509688/a106897c-ff24-11e6-8b9e-accb14056f8c.png)

**Comment by bill-mybiz** [comment]
@jsumners Are you using VsCodeVim by chance? 

If so, then be sure to give [this VsCodeVim issue](https://github.com/VSCodeVim/Vim/issues/1360) a thumbs up. 

If not, then I find `esc` works great for dismissing it (I have `caps` mapped to `esc` for convenience). When you want it to pop back up use `ctrl + shift + space`.

**Comment by jsumners** [comment]
@bill-mybiz no. I only inflict Vim upon myself when working remotely or for quick edits.

The root of the issue is that having to dismiss the popup is disruptive to my workflow. Yet, I want to be able to glance at the information if I need it without having to invoke a three fingered hotkey.
