### ISSUE TITLE
Test chat rendering

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#217639]
Refs: #214915

- [x] macOS @aiday-mar
- [ ] linux @connor4312
- [x] windows @luabud

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23217639%0A%0A&assignees=roblourens)

---

I made some large and potentially impactful changes to chat response streaming/rendering late in this iteration, and I need your help to ensure that nothing broke. Try a bunch of different types of chat requests and check things like

- The markdown content streams in relatively smoothly
- No content is missing
- You don't see the issue where codeblocks may all have the same content when it's supposed to be different, or their content changes in a weird way while streaming in
- You don't see two paragraphs of markdown text streaming at the same time, or a markdown paragraph streaming above some other type of content like a button or file tree
- You can click links and "used references" while content is still loading
- Open the "Window" log while using chat and watch for exceptions that look like they may have come from the chat renderer, or event leak warnings
- Scroll up and down while content is loading, make sure that doesn't mess anything up

Please try each of our chat participants and slash commands at least once. Including `@github`, and if you have access to any other remote github agents, you can try those too.

If you need to file an issue,

- "Set Log Level" > "Trace"
- Reproduce the issue
- Include the trace-level "Window" log in an issue
- A screen recording would help too

**Comment by luabud** [comment]
I was able to hit a few cases where I was not able to navigate to links while the content was loading, but I didn't manage to reproduce it any time that I was recording the screen. It might have been that my computer was just too slow to open the links when that happened.
Other than that it all worked well on Windows!
