### ISSUE TITLE
Typescript - "Add Missing Import" Quick Fix not available in TSX markup

### ISSUE THREAD

**Issue by snerks** [Microsoft/vscode#21764]
- VSCode Version: 1.10.0
- OS Version: Windows 7 SP1 64-bit

Steps to Reproduce:

1. Add a Typescript React TSX file to a React Typescript Workspace
2. Add contents similar to that below, such that an imported `Component` is used in TSX markup
3. Comment-out the `import` statement for `ContactForm`, to test Quick Fix
4. Right-click the squiggled word `ContactForm` in the `render` method

**Expected behaviour**
Quick Fix to `Add Missing Import` is offered in a context menu

**Actual Behaviour**
No Quick Fix is offered for the missing TSX `ContactForm` reference.

_Note: Quick Fix works nicely for `ContactFormData`, which is referenced in non-TSX code._

```typescript

import * as React from 'react';
import { Dispatch } from 'redux';
import ContactForm, { ContactFormData, ContactFormProps } from './ContactForm';

export interface ContactPageProps {
}

class ContactPage extends React.Component<ContactPageProps, {}> {

    save(values: ContactFormData, dispatch: Dispatch<{}>, props: ContactFormProps) {
        // tslint:disable-next-line:no-console
        console.log('ContactPage.save');
        // tslint:disable-next-line:no-console
        console.log(values);
    }

    render() {
        return (
            <ContactForm onSubmit={this.save} />
        );
    }
}

export default ContactPage;
```

**Comment by mjbvz** [comment]
@snerks I'm unable to repo this issue:

<img width="641" alt="screen shot 2017-03-06 at 6 17 00 pm" src="https://cloud.githubusercontent.com/assets/12821956/23638880/26048a44-0299-11e7-9a03-760fad36d36b.png">

A few questions:

* Do you have any extension installed? Does this repo if you run code with `--disable-extensions`?
* Can you share the definition of `ContactForm`, along with your `tsconfig.json`?

Thanks

**Comment by snerks** [comment]
Apologies for the late reply...

I tried using the `--disable-extensions` switch. Did not resolve the problem here.

The repo I am using is here:
[https://github.com/snerks/redux-form-1](https://github.com/snerks/redux-form-1)

**Comment by mjbvz** [comment]
I don't believe this is related to tsx/jsx. The root cause seems to be that `ContactForm` is a default export without any symbol associated with it:

```ts
export default reduxForm({
    form: 'contact',  // a unique identifier for this form,
    validate
})(ContactForm);
```

I believe this is why we cannot find a quick fix for the name `ContactForm ` in this instance

**Comment by snerks** [comment]
OK. Thanks for investigating.

Is there an alternative way of defining that `export default`, such that it has an associated symbol, therefore a Quick Fix?

**Comment by mjbvz** [comment]
@snerks Not that I'm aware of, but I've opened https://github.com/Microsoft/TypeScript/issues/14663 to track this feature on the TS side
