### ISSUE TITLE
Don't hide minimap slider

### ISSUE THREAD

**Issue by pohmelie** [Microsoft/vscode#21761]
When mouse don't hover minimap position rectangle disappears and I can't determine in which position of code I am. Possible solution is to make rectangle more transparent, but not disappear.

**Comment by michaelott-stormbox** [comment]
Agreed. This is a little annoying. I can't think of a single UX benefit to having it disappear.

**Comment by mikeott** [comment]
Agreed. I can't think of a single UX benefit to having it disappear. It would be nice if it were always visible, and be able to tweak the opacity in user settings.

**Comment by alexandrudima** [comment]
Let's consolidate into one issue. Giving preference to #21784 due to more upvotes.
