### ISSUE TITLE
Test: Intellisense in Code Actions on Save

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#217611]
- [x] anyOS @aiday-mar
- [x] anyOS @cwebster-99
- [x] anyOS @andreamah

Complexity: 1

Related: https://github.com/microsoft/vscode/issues/161284

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23217611%0A%0A&assignees=justschen)

---

Allows contributed code actions (source actions) from extensions to be shown by default. Will list all available code actions on save via intellisense. 

### Testing
- Make sure you have a few extensions installed (try Ruff, Black, Eslint, etc)
- in `settings.json`, check `editor.codeActionsOnSave`
- You should see a few more code actions on save via Intellisense.
- Make sure these work for `explicit`, `always`, and `never`

### Things to note:
- currently does not work for notebook code actions (`notebook.codeActionsOnSave`), but is on our backlog.

**Comment by andreamah** [comment]
Works well for me 👍
