### ISSUE TITLE
UX: Tab View and Indicators for Panel

### ISSUE THREAD

**Issue by pankajpatel** [Microsoft/vscode#21768]
This is not an issue but a UX suggestion for the bottom panel.

1. Tabbed View 
![tabbed-view-for-panel](https://cloud.githubusercontent.com/assets/251937/23509475/3ce0a162-ff56-11e6-9ef1-0d6c9a3e06df.png)

2. Indicators for the Panel Items
![indicators-for-panel](https://cloud.githubusercontent.com/assets/251937/23509465/33b30710-ff56-11e6-9625-939fc728bcaf.png)

**Comment by bpasero** [comment]
@pankajpatel looks good, but we explicitly decided against a tab look and feel that comes close to our editor tab UX simply because it is far from being the same (e.g. you can not drag and drop things between panel and editor). People would get confused as to why they cannot move things from the top to the bottom. If we ever want to make this look better we:
* should use the same tab UX we have in the editor area
* allow to drag and drop things around in any dimension (= grid)

**Comment by pankajpatel** [comment]
@bpasero it makes sense to have same UX as the editor tabs. The images were to show the idea.

How about the indicators? Or may be we can change the colour of the tab title.

**Comment by bpasero** [comment]
@pankajpatel indicators are for what, activity? I think we should maybe have similar indicators for activity and status as we have for viewlets today already:

![image](https://cloud.githubusercontent.com/assets/900690/23514168/c06424fe-ff66-11e6-9a71-98a154a29679.png)

**Comment by pankajpatel** [comment]
@bpasero yeah similar ones on the panels, customisable enough to be reported or not.

like "panel.(terminal | debugger | output | problems ).indicator": Enum("error", "log", "verbose", "none")

**Comment by gmsDave** [comment]
@pankajpatel imo I disagree that the integrated terminal panel should have the same tab UX as the editor tabs.

**Comment by bpasero** [comment]
@stevencl @chrisdias fyi

**Comment by pankajpatel** [comment]
@gmsDave if not then it might break when applying various themes. Or we would have to stick to the same view/colours etc in panels even after applying themes.

If we go for different UX for the panel tabs, it would require separate support form the theme which might be breaking or lead to poor experience.

**Comment by snarum** [comment]
I think it is a bit difficult to distinguish the source code window from the panel, at least if they have same background color, as all default themes have. Tabifying the window would help with this, but could it be a quick fix to add a panelTitle.background settings in color scheme?

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable.
Thanks for understanding and happy coding!

Also we have added badges to the panel titles, but they just need to be adopted across panel clients. As for tabs in panel, there are other feature request covering this.
