### ISSUE TITLE
Slow Startup Detected

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#21766]
- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:25:36.875Z)</code>
- OS Version: <code>Linux x64 4.8.0-39-generic</code>
- CPUs: <code>Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)</code>
- Memory (System): <code>2.86GB (0.27GB free)</code>
- Memory (Process): <code>182.04MB working set (183.96MB peak, 113.66MB private, 68.38MB shared)</code>
- Load (avg): <code>1, 1, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|109|
|main|app.isReady => window.loadUrl()|1315|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|666|
|renderer|require(workbench.main.js)|1745|
|renderer|create extension host => extensions onReady()|3058|
|renderer|restore viewlet|1897|
|renderer|restore editor view state|2101|
|renderer|overall workbench load|2763|
|main + renderer|start => extensions ready|7073|
|main + renderer|start => workbench ready|6641|

**Comment by jtsom** [comment]
[1c11_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/813859/1c11_main.cpuprofile.txt)
[1c11_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/813860/1c11_renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
Thanks, this is mostly because of a slow starting shared process: https://github.com/Microsoft/vscode/issues/22091
