### ISSUE TITLE
Add confirmation for folders and files movement in File Tree

### ISSUE THREAD

**Issue by Arilas** [Microsoft/vscode#21778]
Some of developers accidentally move folders or files in another folder when inaccurate trying to open some file or expand folder (by moving mouse when doing action).
And sometimes he can just revert it using git or trying to find it manually.

It will be good to add optional prompt for confirmation for this actions. In future some of extensions can subscribe to this actions to perform refactoring (by changing paths in dependent components).

**Comment by isidorn** [comment]
How did you get 8 thumbs up in 20 minutes? Is this an orchestrated effort :)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1414

**Comment by Arilas** [comment]
@isidorn Just mentioned this issue is two of working chats :smiley: . We all use VSCode for a while and sometimes had a problems with this.

**Comment by johnfrades** [comment]
is there any solution on this?

**Comment by bpasero** [comment]
You can disable DND in the explorer via `"explorer.enableDragAndDrop": false`, but a confirmation dialog has not been added yet. I can look into that.
