### ISSUE TITLE
Unknown system crash

### ISSUE THREAD

**Issue by nonameolsson** [Microsoft/vscode#21772]
My Mac just shut down, and I have no idea of why. When I booted up again and opened VS Code, I got prompted to send an issue. Here it comes.

- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:04:47.508Z)</code>
- OS Version: <code>Darwin x64 16.4.0</code>
- CPUs: <code>Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)</code>
- Memory (System): <code>16.00GB (7.40GB free)</code>
- Memory (Process): <code>177.71MB working set (0.00MB peak, 109.47MB private, 92.95MB shared)</code>
- Load (avg): <code>73, 20, 7</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|133|
|main|app.isReady => window.loadUrl()|714|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|612|
|renderer|require(workbench.main.js)|1512|
|renderer|-> of which require() node_modules|193|
|renderer|create extension host => extensions onReady()|5746|
|renderer|restore viewlet|0|
|renderer|restore editor view state|2|
|renderer|overall workbench load|671|
|main + renderer|start => extensions ready|15222|
|main + renderer|start => workbench ready|9876|

---

:warning: Make sure to **attach** these files: :warning:
-`/Users/nonameolsson/fd12_main.cpuprofile.txt`
-`/Users/nonameolsson/fd12_renderer.cpuprofile.txt`

**Comment by kieferrm** [comment]
@nonameolsson Do you mind attaching the cpu profiles listed above?
