### ISSUE TITLE
There is a bug, when I minimize the window, click VSC back and forth in the taskbar, the window switches between maximizing and minimizing, and the white screen will suddenly flicker

### ISSUE THREAD

**Issue by BraveMomo** [microsoft/vscode#217794]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.2
- OS Version: 22631.3737

https://github.com/microsoft/vscode/assets/22335503/b07cc2e0-c16d-437e-b0ff-8e260ffb11e9

Steps to Reproduce:

1. There is a bug, when I minimize the window, click VSC back and forth in the taskbar, the window switches between maximizing and minimizing, and the white screen will suddenly flicker, as if the black has not had time to render, sometimes I click on it and it will trigger, then it will be very dazzling, if possible, I hope to optimize and fix it.
2.

**Comment by FuadTalukder85** [comment]
How did you fix it?
