### ISSUE TITLE
Add extra single quote, when replace double quotes with CTRL+D

### ISSUE THREAD

**Issue by yt-scopelliti** [Microsoft/vscode#21777]
- VSCode Version: 1.10.1
- OS Version: Windows 10

Steps to Reproduce:

1. Select the first double quote
2. Select also the other double quote, by pressing ctrl+d
3. Replace the double quote with single quotes

![test](https://cloud.githubusercontent.com/assets/11980775/23510332/6a070e8a-ff59-11e6-8b21-c92e80c44da3.gif)

**Comment by stenowtf** [comment]
same with _single quotes_ → _double quotes_. cheers!

**Comment by alexandrudima** [comment]
Today, multiple cursors operate "independently" and in this case one of them decides it's a good idea to "replace", while the other decides it's a good idea to "surround" (probably has to do with one of the cursors starting outside a string and the other starting inside a string.

All cursors should do the same thing. Let's track this in #20891
