### ISSUE TITLE
Colour errors?

### ISSUE THREAD

**Issue by mistw4lk3r** [Microsoft/vscode#21779]
This is how monokai-dimmed used to look
![How monokai-dimmed used to be](http://i68.tinypic.com/rmscva.png)

And this is how it's looking after last update
![Actual monokai-dimmed](http://i67.tinypic.com/111thma.png)

Seems the problem is because it removed/renamed jade as pug in the language selector.

- VSCode Version: February 2017 (version 1.10)
- OS Version: MAC OSx El Capitan

Extensions:

Extension | Version
------------ | -------------
An Old Hope Theme | 2.0.0
Angular 1 JavaScript and TypeScript Snippets for VS Code | last version
Angular UI Bootstrap Snippets for VS Code | 4.0.6
Bootstrap 3 Snippets | 0.0.9
Guides | 0.6.1
HTML Boilerplate | 1.0.1
ionic1-snippets | 1.0.1
Monokai Theme EasyLight | 1.0.0
Paste and Indent | 0.0.8
Theme-TinaciousDesign | 0.1.1
View in Browser | 0.0.5

**Comment by aeschli** [comment]
It's not related to the pug -> jade rename, but to the changes to our theme matching code.
We are now using the proper algorithm to match a color based on the scope hierarchy, while before we didn't use the hierarchy.
So what we're now seeing (and I verified that matching is correct) is what Monokay Immed intends for `entity.other.attribute-name`.
