### ISSUE TITLE
Unexpected breakpoint behaviour after changing code with breakpoint

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#21770]
- VSCode Version: 1.11.0
- OS Version: Win10

Steps to Reproduce:

1. Set a breakpoint
2. Type some text on the line with breakpoint

Additional inline breakpoint at the beginning of the line appears.

![additional breakpoint](https://cloud.githubusercontent.com/assets/2239563/23509976/0d352e7c-ff58-11e6-860e-166c0912095b.gif)

Removing the new text does not bring the breakpoint away.

**Comment by isidorn** [comment]
Nice way to file an issue - great short steps and a gif.
Though somehow slipped through my fingers so closing as a dup of a newer bug which is not so nice in general https://github.com/Microsoft/vscode/issues/21881
