### ISSUE TITLE
go-to-definition in Copilot chat code block continuously sends textDocument/didOpen & didClose requests without stopping

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#217797]
I'm testing Java language features in the Copilot chat code block, and found an issue that the "go-to-definition" feature enters a dead cycle.

Steps to reproduce:

1. Move the cursor to a symbol.
2. Press the Ctrl key to wait for the link to be resolved and an underline to appear.
3. Move the cursor away to cancel the "go-to-definition" action.

After these steps, the VS Code client continuously sends textDocument/didOpen and textDocument/didClose requests for the selected symbol's document.

![image](https://github.com/microsoft/vscode/assets/14052197/9a019578-1f37-4815-b22a-4c6853c94e29)

**Comment by mjbvz** [comment]
Do you mean it sends these even when you're not doing anything at all in the UI? Or you're seeing these while you using the mouse `go to definition` feature, even if you're not actually clicking any of the definition links?

**Comment by testforstephen** [comment]
I'm using mouse for `go to definition`, but don't actually click the links. It then keeps opening/closing the target document in the background. The open/close behavior is not visible at the UI, but the LSP verbose log shows numerous open/close document events being requested.

If you want to reproduce it with Java extension, you can turn on LSP log for Java via the setting `"java.trace.server": "verbose"` and go to the **OUTPUT** channel for "**Language Support for Java**" to view LSP logs.

**Comment by mjbvz** [comment]
Thanks. That's expected for now. You should see that the document is open for the duration of the `go to definition` request

We are investigating changing how this works in the future however. Tracked in #218240

**Comment by testforstephen** [comment]
I understand that it sends open/close requests, but the issue is that it keeps sending them repeatedly and endlessly. This can cause the language server to become too busy responding, making it unusable for other features. I have to restart VS Code to stop this behavior.
