### ISSUE TITLE
Minimap: add scale (font size) option

### ISSUE THREAD

**Issue by mickdekkers** [microsoft/vscode#21773]
It would be great if there was an option to adjust the font size of the minimap.

I have a high DPI monitor (1440p) and the minimap is smaller than I'd like:

![minimap](https://user-images.githubusercontent.com/5085260/42998280-ef42584a-8c19-11e8-8ce8-7d6167693252.png)

Screenshot taken with these minimap settings:
```json
{
  "editor.minimap.enabled": true,
  "editor.minimap.renderCharacters": false
}
```

**Comment by Kongsea** [comment]
Need this feature.

**Comment by hellonearthis** [comment]
Need this because on a 4k the minimap looks like a nanomap

**Comment by jaywehner** [comment]
Please add this! Old eyes need zoom :)

**Comment by mixtum** [comment]
Same thing... Just too small in 4K display!

**Comment by whardier** [comment]
Too small on 4k display.. needs percentage option from main font size at the least.

**Comment by potatoqualitee** [comment]
These old eyes need some zoom too please!

**Comment by JonathanTroyer** [comment]
I think it would be nice to be able to grab the edge of the minimap to resize it (much like we can resize panels). In fact, when I first saw the minimap, I tried to do just that.

**Comment by cw-mswanson** [comment]
Still needed in june 2019

**Comment by alexander-rieder** [comment]
i also need this....

**Comment by tonybounty** [comment]
I have also a 4K laptop monitor and minimap is unusable in this resolution. Please add witdh feature.

**Comment by ckrippendorf** [comment]
I don't know if just saying 100 times "I want this feature" will increase the possibility of implementation, but....I also want to have this feature! :-D

**Comment by tonybounty** [comment]
I never develop anything in vscode project, and I have a poor experience in JavaScript, nevertheless I program for 10 years in several programming language.
So my question: is someone interested to try to improve minimap for HighDP with me ?

**Comment by potatoqualitee** [comment]
yesssssss thanks so much!

**Comment by JonathanTroyer** [comment]
Not to beat a dead horse, but @connor4312 is there any way to make this work with any decimal value? I find myself wanting to use 1.5.

**Comment by connor4312** [comment]
In the current implementation, the scale is actually the pixel width of each character in our minimap 'font'. Having them be constant values means that we don't need to deal with aliasing, we can copy prerendered pixel values straight from our buffer onto the canvas. Dealing with non-constant values would entail implementing some aliasing, which has a performance and complexity cost I didn't tackle in my initial PR. I'm open to investigating it some more though.

Opened https://github.com/microsoft/vscode/issues/84168 on it.

**Comment by cw-mswanson** [comment]
For extra wide screens, a value of 4, 5, 6 or 7 would be helpful.
