### ISSUE TITLE
Merge objective-c and objective-cpp again?

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#21775]
#21599 added a new language 'Objective-c++' with 'objective-c++' as language id.

Having two different languages 'objective-c' and 'objective-cpp' adds some benefits, such as the possibility of separate providers/snippets for each 'flavour', but also breaks existing extensions that so far contributed just to 'objective-c' and were enabled on both m and mm files.

There are only few objective-c extensions. If we decide to keep going with two language ids, we should contact these extensions.

**Comment by aeschli** [comment]
If we go with two language ids, we need to update the language id reference at https://code.visualstudio.com/docs/languages/identifiers

**Comment by mjbvz** [comment]
I do think we want to have two separate language ids for this case. `.mm` files were previously being treated as c++, which is not expected. Treating them as plain old objective-c also doesn't seem correct.

I'll update the documentation and try reaching out the effected extensions

**Comment by mjbvz** [comment]
Filed PRs against the main effected extensions and updated docs
