### ISSUE TITLE
Not able to change keybinding for column select

### ISSUE THREAD

**Issue by RugnirViking** [Microsoft/vscode#21785]
- VSCode Version: v1.10
- OS Version: Windows 10 v1511 

Steps to Reproduce: 

1. Look in the default keybindings file for column select (by dragging)
2. I am unable to find it

Expected Result:
I am able to change the key binding for column select for example to just alt

Notes:
I do not mean the ctrl+shift+alt+<arrow key> bindings, I mean shift+alt+drag with the mouse style selection

**Comment by RugnirViking** [comment]
I'd also like to see column select work closer to how it does in visual studio (virtual space) if possible

**Comment by alexandrudima** [comment]
let's track in #3130
