### ISSUE TITLE
Mysterious focus on second tab

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#217853]
Testing #217202

1. Enable text buttons and reload
2. `ctrl+i`
3. Start typing, then hit tab once.
4. ✅ Tab goes to microphone
5. Hit tab again
6. I can't tell where the focus is. It's not on the "enter to send" button, because I can see that focus moves there on a subsequent, third, tab.
![Recording 2024-06-25 at 11 09 47](https://github.com/user-attachments/assets/9a66d8e8-6b00-4287-ad1b-dd28fad6cb41)

**Comment by jrieken** [comment]
Looks like the (empty) list below grabs focus...

<img width="1298" alt="Screenshot 2024-06-25 at 14 12 05" src="https://github.com/user-attachments/assets/2b1c46e6-a67b-43a6-b239-281bb3fe35ca">

**Comment by Tyriar** [comment]
Verified but noticed that the hover feedback on this button is only the hover:

![Image](https://github.com/user-attachments/assets/1877fa42-f6d8-4d00-98b7-de22c51a4599)
