### ISSUE TITLE
Tooltip "New Window" is unclear

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#217851]
Testing #217139

I think "Open Profile In New Window" would be more clear here

![Code_-_Insiders_UgqLJyfpfg](https://github.com/user-attachments/assets/f2633e79-41f4-4330-b224-c600f81cfc27)

**Comment by gjsjohnmurray** [comment]
Or maybe "New Window with Profile", for consistency with https://github.com/microsoft/vscode/issues/184594#issuecomment-2183104573
