### ISSUE TITLE
Errors are not removed automatically when fixing them on an another file

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#2178]
I have noticed that errors in one current file are not removed automatically when I fix them in an another file where the error originates from. 

Non-existent has red squiggles:
```typescript
import { nonexistent } from './some-where.ts';
```
And then define in `some-where.ts`:
```typescript
export function nonexistent () {}
```

Then the error in the first file is not removed. I need to type something then it will be removed.

**Comment by dbaeumer** [comment]
This works for me using 0.10.6 using a proper tsconfig.json file in the root. My tsconfig.json file looks like this:
{
	"compilerOptions": {
		"module": "commonjs"
	}
}

Without that file or a files section in that file the newly created some-where.ts file will not be part of the same 'project' scrope as the file having the import hence resulting in an error.

**Comment by tinganho** [comment]
Though I think I have a proper `tsconfig.json` file?

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": true,
        "outDir": "Build",
        "rootDir": ".",
        "experimentalDecorators": true,
        "jsx": "react",
        "removeComments": true
    },
    "exclude": [
        "node_modules",
        "vendor"
    ]
}
```

**Comment by tinganho** [comment]
I'm using `sshfs` to mount a file system on my Mac. If that helps to narrow down the problem.

**Comment by dbaeumer** [comment]
@tinganho the mounted file system shouldn't make a difference. Does this work for you if you take the minimal tsconfig.json I used ?

**Comment by tinganho** [comment]
@dbaeumer I think it only happens on `tsx` files.
![jan 28 2016 23 55](https://cloud.githubusercontent.com/assets/1324476/12649686/a1e66694-c61a-11e5-8ae3-8b43827bcb78.gif)

**Comment by dbaeumer** [comment]
Thanks. I reopen so that we can investigate for next milestone.

**Comment by dbaeumer** [comment]
I tested it with tsx files on the upcoming February build that uses TS 1.8.x and wasn't able to reproduce. See attached 
![bug](https://cloud.githubusercontent.com/assets/1931590/13174250/aa13eb68-d702-11e5-8598-86d39dacd2a0.gif)
video.

**Comment by dbaeumer** [comment]
If you still see this can you please provide a test case for me to reproduce.

**Comment by tinganho** [comment]
@dbaeumer I think I still see this issue. I'm using the latest version with `tsdk` setting.

![feb 24 2016 13 05](https://cloud.githubusercontent.com/assets/1324476/13276160/5326007c-daf7-11e5-831c-81ee2ef69b45.gif)

**Comment by tinganho** [comment]
Have you tried changing from `ts` to `tsx`?
