### ISSUE TITLE
Missing underlines in notebook MD cells

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#217814]
Testing #217636

* enable link underlines
* open a notebook, add a MD cell with `Hello [test](http://www.example.com) world!`
* render the MD cell
* :bug: the link doesn't have an underline

**Comment by jrieken** [comment]
the same is true for extension editors (and I assume other webview based editors)

**Comment by daviddossett** [comment]
Fixed by https://github.com/microsoft/vscode/pull/216859, which I thought had merged before endgame 🤦‍♂️
