### ISSUE TITLE
Ctrl+Esc to stop doesn't stop on Windows

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#217861]
Testing #217202

1. Enable text buttons
2. `ctrl+i` 
3. Highlight some code and ask "What does this do?"
4. Streaming starts, and the "ctrl+esc to stop" button shows.
5. `ctrl+esc`. 
6. It actually opens the Windows start menu and streaming continues. It seems like this is a default Windows shortcut.

**Comment by roblourens** [comment]
They have a whole keyboard button for that, why are they taking ctrl+esc too... 😠

**Comment by roblourens** [comment]
Going with alt+backspace

**Comment by alexr00** [comment]
Works great!
