### ISSUE TITLE
Clicking on an opened dropdown should close it

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#217852]
Testing #217139

If you do it too fast, it even triggers a double click:

![MPn7cUnIyn](https://github.com/user-attachments/assets/701940f5-3415-4afa-b087-90ff7f92fadd)

![Code_-_Insiders_nisyy4JF4M](https://github.com/user-attachments/assets/c381dac4-3c93-4040-9e78-ab5f0c082d26)

**Comment by sandy081** [comment]
Fixed by radio buttons
