### ISSUE TITLE
Show tooltips on caret/cursor movement

### ISSUE THREAD

**Issue by MayhemYDG** [Microsoft/vscode#21786]
- VSCode Version: 1.10.1
- OS Version: Windows 7

Steps to Reproduce:

1. Move caret to a word with an error or warning (with the fuzzy underline).

I wish I didn't need to use my mouse or use a keybinding to see what an error or warning is.

**Comment by alexandrudima** [comment]
You can use either `F8` (Go to Next Error or Warning) or `Ctrl+K Ctrl+I` to Show Hover
