### ISSUE TITLE
error

### ISSUE THREAD

**Issue by verybigorange** [Microsoft/vscode#21788]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.1|
|path-intellisense|christian-kohler|1.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|vscode-html-css|ecmel|0.0.33|
|mithril-emmet|FallenMax|0.6.1|
|auto-rename-tag|formulahendry|0.0.11|
|Angular2|johnpapa|2.0.3|
|vscode-exec-node|miramac|0.2.8|
|easy-less|mrcrowl|1.3.4|
|typescript-hero|rbbit|0.12.0|
|guides|spywhere|0.6.1|
|open-in-browser|techer|0.0.3|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please provide information about the error
