### ISSUE TITLE
Cannot get types for vue, vuex in javascript

### ISSUE THREAD

**Issue by vonweb** [Microsoft/vscode#21787]
I installed vue, vuex, because they provide their own type definitions, vscode don't give me any parameter info. how can I get type info in javascript
- VSCode Version:1.10.1
- OS Version:win10 1607

Steps to Reproduce:

1.npm install -S vue vuex
2.in jsconfig.json add typeAcquisition: {include: ['vue', 'vuex']}
but in my js file I cannot get any parameter info, please help me out

**Comment by JimiC** [comment]
Quoting from Release Notes 1.10.1

> Vue
While Vue.js files may look like HTML files, they are much more than that. For that reason, the .vue file extension is no longer associated with HTML by default. However we do recommend you use a Vue.js specific extension for language support and the vetur extension is a good choice.

**Comment by vonweb** [comment]
@JimiC In .vue file I can get highlight, but intellisense and lint is gone, so I want to write vue component in .js file. At the moment ts is perfect, my working company is using js, so...

**Comment by vonweb** [comment]
I can manually copy their types to %appdata%\Local\Microsoft\TypeScript\node_modules\@types, is there any automatic solution

**Comment by mjbvz** [comment]
Please try installing [this Vue extension](https://marketplace.visualstudio.com/items?itemName=octref.vetur) to see if that helps for working with vue

If you are still running into this problem, please share some example code or a small sample project so that we can investigate

Thanks
