### ISSUE TITLE
Bold text is streamed with asterisks and changed to bold font later + thinking icon flickers as it is turning

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#217946]
Testing #217639

I created a new notebook with the `/newNotebook` command. As the response is streaming in, you see bold text streamed in with asterisks in front, when the closing asterisks are found, the corresponding text is changed to bold text. I am wondering if this can somehow be changed so that we directly stream in bold text on encountering asterisks?

After the text is streamed in, there is a turning circular icon that appear that has the associated text `thinking`. The icon flickers as it is turning. The icon movement is not smooth.

https://github.com/microsoft/vscode/assets/61460952/832d4bf5-ed42-462f-9cce-16f62f9f9f52

The log in the Window output is appended here.

[testing4.docx](https://github.com/user-attachments/files/15969923/testing4.docx)

**Comment by roblourens** [comment]
Problem 1: we fix up markdown lists that use `-` and numbers, but not `*` 😠 

Problem 2: the intent is sending duplicate progress events: https://github.com/microsoft/vscode-copilot/issues/6482
