### ISSUE TITLE
need this Feature

### ISSUE THREAD

**Issue by yuu2lee4** [Microsoft/vscode#2179]
just like sublime show：
![qq 20160122193742](https://cloud.githubusercontent.com/assets/8046366/12509749/9fdaacc8-c13f-11e5-89bd-dbc5114fb20c.png)

**Comment by weinand** [comment]
@yuu2lee4 I don't quite understand what you mean?

**Comment by yuu2lee4** [comment]
@weinand  you can open multiple files in sublime，then you can compare，you can edit etc

**Comment by weinand** [comment]
@yuu2lee4 you can open multiple file in VSCode too:
![2016-01-22 15-45-52](https://cloud.githubusercontent.com/assets/1898161/12513669/5b31ed72-c11f-11e5-9809-04fcde451504.png)

An you can compare files:
![2016-01-22 15-47-49](https://cloud.githubusercontent.com/assets/1898161/12513714/8c2fb2c4-c11f-11e5-87af-d32dd47e99bd.png)
