### ISSUE TITLE
Provide JavaScript TM scope for exported function names in Node modules

### ISSUE THREAD

**Issue by dbstraight** [Microsoft/vscode#21796]
There is currently no JavaScript TM scope which can identify function names when they are specified as part of a Node module export. This makes it impossible to have a consistent styling for function names where functions are defined.

- VSCode Version: 1.10.1
- OS Version: Windows 7 Professional, Version 6.1.7601

Steps to Reproduce:

1. Create a JavaScript file with the content `module.exports.square = function(x) { return x * x; };` or `exports.square = function(x) { return x * x; };`.
2. Use the builtin TM scopes inspector to view scopes for `square`. Available scopes are `entity.name.function.js` and `source.js`. Both of these are used in many other places.
3. Compare to scopes available for `square` in `function square(x) { return x * x; }`. This time the scope `meta.definition.function.js` is available which can be used to style function names where they are defined. This styling is not possible when the function name is only given as part of a Node module export.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#425
