### ISSUE TITLE
Missing content when using /fix in panel chat

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#217931]
Testing #217639

I ran the command `/fix` from the panel chat. There was an error in my current active editor file, which was that the identifier `SomeInterface` was appearing twice in the same scope. The panel chat responded with just the code block containing the fix, there was no explanation however of the error and how to fix it. The response was quite bare bones and I am wondering if there isn't some missing content.

https://github.com/microsoft/vscode/assets/61460952/f4360c1c-9e8e-4550-9880-2b3b8f70bdd1

The log from the Window output is appended here.

[testing3.docx](https://github.com/user-attachments/files/15969628/testing3.docx)

**Comment by roblourens** [comment]
It looks like that is indeed all the content we got from the chat participant
