### ISSUE TITLE
Missing underlines in .NET MAUI extension getting started

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#217986]
Testing #217636

* enable underlines
* install ".NET MAUI"  and click through their getting started
* missing underline here

<img width="1010" alt="Screenshot 2024-06-25 at 13 52 43" src="https://github.com/user-attachments/assets/fcaca023-d12b-4e91-97fa-8259f72030e3">

**Comment by daviddossett** [comment]
Same as before, fixed by https://github.com/microsoft/vscode/pull/216859/files and forgot to merge in time.
