### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by aryanpatel05** [microsoft/vscode#217926]
Type: <b>Bug</b>

Could not update simulator linking permissions: ENOENT: no such file or directory, open '/Users/aryanpatel/Library/Developer/CoreSimulator/Devices/BBA913FA-5F11-43B8-9F9F-057074AE1300/data/Library/Preferences/com.apple.launchservices.schemeapproval.plist'. showing this error

VS Code version: Code 1.90.2 (Universal) (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:37:41.291Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|33, 27, 15|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 2814a987-5f4a-436d-b40b-3fe2391a6183|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.0.0
composer-php-vscode|DEV|1.48.15635
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.48.15635
profiler-php-vscode|DEV|1.48.15635
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.90.0
vscode-language-babel|mgm|0.0.40
debugpy|ms-|2024.6.0
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
vscode-thunder-client|ran|2.24.11
LiveServer|rit|5.7.9
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31082724

```

</details>

**Comment by roblourens** [comment]
This seems like an issue with your system, or an extension, or something else besides vscode
