### ISSUE TITLE
Should the editor hover accessible view have the status bar actions?

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#217975]
Testing #217237

Once again, I'm not sure what the norms are here, but would it be useful to have the actions in the status bar show in the accessibly view?

<img width="607" alt="image" src="https://github.com/user-attachments/assets/df1f4047-e71b-42e4-bb14-2a1de8917f68">

**Comment by aiday-mar** [comment]
Hi @alexr00 yes that would make sense. Good point!
