### ISSUE TITLE
Request: Debian auto package management

### ISSUE THREAD

**Issue by AravK** [Microsoft/vscode#21794]
I hope the team realizes that if you push all your .deb files to some spot like `https://code.visualstudio.com/vscode/debian/<PACKAGE>` you could save all Debian peoples a great deal of time and effort. If you add a file to your packages at `/etc/apt/sources.list.d/vscode.list` and inside put `deb [arch=amd64] https://code.visualstudio.com/vscode/debian stable main` that'd be awesome!

**Comment by Tyriar** [comment]
Install the latest deb and you'll get a repo installed, you can also automate your setup by installing the repo manually https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions
