### ISSUE TITLE
enabling interactiveWindow.executeWithShiftEnter does not update hint

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#217901]
Testing #216852

* From gear icon, enable the setting `interactiveWindow.executeWithShiftEnter`
* Switch back to the interactive window and see no hint in the input box
* Reloading the workspace does not help as well
```
Name: Jupyter
Id: ms-toolsai.jupyter
Version: 2024.6.2024062401
Publisher: Microsoft

Name: Python
Id: ms-python.python
Version: 2024.9.11762330
Publisher: Microsoft

Version: 1.91.0-insider
Commit: 3e9cab05385c88a3174175e47085952bd3caf8a3
Date: 2024-06-25T06:01:04.514Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.6.0
```

<img width="1031" alt="Screenshot 2024-06-25 at 18 49 24" src="https://github.com/microsoft/vscode/assets/964386/ed0dfd16-58e8-451f-aa68-73b6628463ee">

**Comment by amunger** [comment]
does shift+enter work as a keybinding?

**Comment by deepak1556** [comment]
Yes the keybinding works, issue is only about the hint UI.

**Comment by rzhao271** [comment]
@amunger the hint text keeps saying "Press Command+Enter to execute" and doesn't update depending on the setting.
I was expecting the hint to display "Enter" or "Shift+Enter" depending on the setting.

**Comment by amunger** [comment]
@rzhao271 - can you enable the shift+enter option, run `toggle keyboard shortcuts troubleshooting` and try to press enter in the input box? Do you get something like this in the troubleshooting logs?

```
2024-06-26 12:59:26.904 [info] [KeybindingService]: / Received  keydown event - modifiers: [shift], code: Enter, keyCode: 13, key: Enter
2024-06-26 12:59:26.905 [info] [KeybindingService]: | Converted keydown event - modifiers: [shift], code: Enter, keyCode: 3 ('Enter')
2024-06-26 12:59:26.905 [info] [KeybindingService]: | Resolving shift+Enter
2024-06-26 12:59:26.905 [info] [KeybindingService]: \ From 17 keybinding entries, matched interactive.execute, when: 
```

**Comment by amunger** [comment]
it looks like you may have a custom keyboard layout that changes the `Enter` key label to `[Enter]`. I don't know how many ways there are to modify key labels, so I'll just rely on the order of the keybinding registration to show shift+enter instead of always showing cmd/ctrl+enter. It might still show cmd+enter when in the python REPL experiment with a custom keyboard layout, but I think this is as close as I can reliably get.

**Comment by amunger** [comment]
verification: 
with Jupyter and python extensions installed
run `Create Interactive Window`
The execution hint should show in the input box
click the gear, change the setting shift+enter setting
the hint should update

`shift+Enter` should at least show in the hint with the setting enabled. When disabled, it will either show `Enter` or `Ctrl/Cmd+Enter`

**Comment by eleanorjboyd** [comment]
<img width="1381" alt="Screenshot 2024-06-27 at 10 21 16 AM" src="https://github.com/microsoft/vscode/assets/26030610/8fe01cd6-cf39-4962-bb2b-24e16b8b26fc">

still occurring - key bindings come in as Resolving meta+[Enter] and Resolving shift+[Enter]
