### ISSUE TITLE
Allow control over quick diff decorations

### ISSUE THREAD

**Issue by farfromrefug** [Microsoft/vscode#21795]
if i am not wrong there is no way to disable SCM (git) in the gutter. I really would like to disable it.
I want my gutter to be clean and almost only see problems in there.

Thanks

**Comment by seanmcbreen** [comment]
If you right click on the item you can remove it from the activity bar.

![image](https://cloud.githubusercontent.com/assets/1051190/24982835/693a2f64-1f98-11e7-9efc-20585ea771fc.png)

Additionally if you right click in an open area you can bring it back:

![image](https://cloud.githubusercontent.com/assets/1051190/24982854/7a947b20-1f98-11e7-9da5-3d865f67be30.png)

I think this covers your scenario so closing this issue for now - please re-open if there is something we missed.

Thanks,
Sean - VS Code Team Member

**Comment by farfromrefug** [comment]
@seanmcbreen that s actually not the same feature.
The gutter is the scroll background to the right of the editor.
There you see scm modifications. Those are the one i would like to remove
Can you reopen the issue?
Thanks

**Comment by joaomoreno** [comment]
I also thought the same as @seanmcbreen, actually. A screenshot is always helpful in these issues. 👍

**Comment by farfromrefug** [comment]
@joaomoreno your are right! My bad.
Here is a screenshot
![image](https://cloud.githubusercontent.com/assets/655344/24995318/b1ae518a-202e-11e7-8dd8-4fb6462770c8.png)

**Comment by jens1o** [comment]
@joaomoreno Can you point me to some direction? I digged in for almost an hour, but I couldn't find the point it publishes these infos...

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/blob/337ded059ae5140b86caf07e67ce92a41a8e6581/src/vs/workbench/parts/scm/electron-browser/dirtydiffDecorator.ts#L33-L62

**Comment by jens1o** [comment]
Okay, I made that change, but unfortuanetly, my machine is too weak to build it in an acceptable time to test the changes.

**Comment by FabianLauer** [comment]
@jens1o Have you pushed a branch to [your clone](https://github.com/jens1o/vscode) already? Didn't find anything, I'd love to help if necessary 👍

**Comment by jens1o** [comment]
Ah, not yet. I was kinda frustrated and disappointed in me. Will push after lunch and ping you up.

**Comment by jens1o** [comment]
@FabianLauer There you go: https://github.com/jens1o/vscode/commit/b7b7d251482f771be2cf35ab71d30cec1d612fc3

**Comment by FabianLauer** [comment]
@jens1o No worries, your changes work 😃

**Comment by usernamehw** [comment]
Was it solved in [1.16 (August 2017)](https://code.visualstudio.com/updates/v1_16#_theming-improvements)  ?
```json
"workbench.colorCustomizations": {
    "editorOverviewRuler.addedForeground": "#0000",
    "editorOverviewRuler.modifiedForeground": "#0000",
    "editorOverviewRuler.deletedForeground": "#0000",
}
```

**Comment by joaomoreno** [comment]
You can now control this with `scm.diffDecorations`, which has the following possible values: `['all', 'gutter', 'overview', 'none']`.

**Comment by farfromrefug** [comment]
@joaomoreno  great news! I dont see that parameter in the insider build yet. Will try an let you know once it s in the insider build

Thanks

**Comment by ramya-rao-a** [comment]
@joaomoreno It wasnt very clear to me what the `overview` option did until I played around with all the values. Would you consider adding more details in the description of the setting?
