### ISSUE TITLE
Support find/replace in selection for multiple cursor selections

### ISSUE THREAD

**Issue by Jazcash** [microsoft/vscode#21792]
- VSCode Version:  1.9.1
- OS Version: Windows 10

Steps to Reproduce:

1. Make a multi-cursor selection using Shift + Alt + Left click
2. Find in selection button is greyed out

![example](https://cloud.githubusercontent.com/assets/1434248/23514746/26393186-ff60-11e6-99b5-b36422f5b9dd.jpg)

**Comment by isidorn** [comment]
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/browser/findWidget.ts#L508

**Comment by karl-tpio** [comment]
@scottpelak, i think this is already "in" VS Code.  The "find all" + cursor at each occurrence is _the_ biggest feature of ST3   that i use dozens of times every day.

Right now, i have found the `Change All Occurrences" via right click on any of the find results. This will then give me a cursor at every occurrence.  i can move the cursor around to the beginning / end of a line ... etc

**Comment by ldexterldesign** [comment]
Hi @scottpelak,

I'm not immediately clear on your goal - why isn't your starting position where you need to be and how does this relate to the OP (i.e. "Find in selection")?

Hope to hear back

Cheers

**Comment by isidorn** [comment]
fyi @rebornix
