### ISSUE TITLE
missing a important function!

### ISSUE THREAD

**Issue by khuangia** [Microsoft/vscode#21799]
it's so important to coders to have a function summary view who maintains a project that over 10k lines in 1 cpp file.

plz making this feature in a priority.

i'v been using so many IDE/notepad, but vscode is the best!

**Comment by hoovercj** [comment]
[Search for symbols](https://code.visualstudio.com/docs/languages/cpp#_search-for-symbols) should list and allow you to search for symbols in C++ files.

Is that what you are asking for?

**Comment by isidorn** [comment]
Please add more details regarding this.
What are you missing. As @hoovercj points out we have a lot of this funtionality already

**Comment by rbenson** [comment]
It would also be handy if the docs included information on how to add symbols to languages the community has made. The easiest example would be python classes or even headings in markdown

**Comment by hoovercj** [comment]
@rbenson as far as I know, the only way to add symbols are through creating a new extension.

To make sure, could you clarify what you mean by "add symbols to languages the community has made"?

If you mean you want to add symbols that show up when you press `ctrl+shift+o`, then you would create an extension that satisfies the [DocumentSymbolProvider](https://code.visualstudio.com/Docs/extensionAPI/vscode-api#_a-namedocumentsymbolprovideraspan-classcodeitem-id590documentsymbolproviderspan) api.

If you're talking about symbols that could appear as completions, you would need the [CompletionItemProvider](https://code.visualstudio.com/Docs/extensionAPI/vscode-api#_a-namecompletionitemprovideraspan-classcodeitem-id786completionitemproviderspan) api.

For the markdown example, to create a DocumentSymbolProvider, you could create an extension that would parse markdown files and find all the headings. In fact, one of the vscode devs already did that in [this extension](https://marketplace.visualstudio.com/items?itemName=jrieken.md-navigate). You can take a look at [the code](https://github.com/jrieken/md-navigate/blob/master/src/extension.ts) for an idea of how it works. If a person wanted that extension to do more, they could fork the extension and parse out images, links, or footnotes in markdown and include them as symbols.

**Comment by rbenson** [comment]
@hoovercj thanks, didn't see the `DocumentSymbolProvider` method before. I was using markdown purely as an example. This is exactly what I meant.

**Comment by ramya-rao-a** [comment]
@khuangia Closing this issue as we havent heard back from you in a while.

If you can provide us more details as to what exactly you are looking for, then we can re-open this issue
