### ISSUE TITLE
Webdav network drive not work

### ISSUE THREAD

**Issue by PooLP** [Microsoft/vscode#218]
Hi,

It's impossible to open a folder on a Webdav Network Drive (ex : Webdav SharePoint Folder/file Access).

It work perfectly with Brackets.

Bye

**Comment by bpasero** [comment]
@PooLP does it work with Atom?

**Comment by PooLP** [comment]
Hi,
I do not use Atom.

**Comment by PooLP** [comment]
It work on Atom.

**Comment by bpasero** [comment]
Anyone that can give me instructions how to setup WebDav with Sharepoint, please let me know I would like to reproduce. Alternatively if I can access to some test environment that would also be nice.

**Comment by bpasero** [comment]
@PooLP are you able to build Code locally and could help me identify the issue? Might be easier than me trying to setup a Sharepoint locally with WebDav.

Also, when you say it does not work, does the explorer show empty or do you get an error earlier? Can you open the developer console when this happens to see if something is printed (from Help menu, last entry).

**Comment by PooLP** [comment]
For Sharepoint, use a O365 Sahrepoint site, on any library click in Ribbon "Open with Explorer" and create a network drive with adress (Warning, the time to create a network drive is short)

![o365webdav](https://cloud.githubusercontent.com/assets/582733/11361327/200fea84-928d-11e5-9d15-ef718876d095.jpg)

For erro i have this :
![vsc-error](https://cloud.githubusercontent.com/assets/582733/11361483/2653e192-928e-11e5-9cf4-f2fa179155ce.jpg)

I must see if I have the tools for build locally.

Thanks, and sorry for time response and for my english ^^.

**Comment by bpasero** [comment]
@PooLP thanks so much, I can finally reproduce locally :)
