### ISSUE TITLE
Slow start up, asked to submit

### ISSUE THREAD

**Issue by s1nf3rn0** [Microsoft/vscode#21805]
- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:10:18.838Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)</code>
- Memory (System): <code>31.94GB (10.43GB free)</code>
- Memory (Process): <code>147.13MB working set (149.44MB peak, 116.39MB private, 36.68MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|182|
|main|app.isReady => window.loadUrl()|401|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|474|
|renderer|require(workbench.main.js)|919|
|renderer|create extension host => extensions onReady()|1682|
|renderer|restore viewlet|969|
|renderer|restore editor view state|536|
|renderer|overall workbench load|2407|
|main + renderer|start => extensions ready|3828|
|main + renderer|start => workbench ready|4402|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\jason.schultz\
[b670_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/814593/b670_renderer.cpuprofile.txt)
[b670_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/814594/b670_main.cpuprofile.txt)

b670_main.cpuprofile.txt`
-`C:\Users\jason.schultz\b670_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Thanks for reporting. We have identified these perf issues from the traces
* https://github.com/Microsoft/vscode/issues/22086
* https://github.com/Microsoft/vscode/issues/22087
