### ISSUE TITLE
Allow to select + copy all in debug console

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#2180]
Common question for resolving issues with debug adapters is "paste the logs". This is currently easier said then done because you cannot press Ctrl+A in the debug console and you can only select text that is currently visible. It would also be nice to be able to toggle line wrap.

**Comment by isidorn** [comment]
Dup of #2163

**Comment by felixfbecker** [comment]
Sorry.

**Comment by isidorn** [comment]
No need to be sorry just file issues and we will close them if they are dups :smile:
