### ISSUE TITLE
nit: Single item in an overflow menu is a bit strange

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#218099]
Testing #217202

<img width="499" alt="image" src="https://github.com/user-attachments/assets/7db660c0-4634-4003-95d2-a64e1ad3e7ad">

**Comment by daviddossett** [comment]
I have 

![Image](https://github.com/user-attachments/assets/3d8192c5-c8d4-47a8-adbd-d4498d6c3d7a)

**Comment by jrieken** [comment]
It depends on the type of reply. When it's text only the "view in chat" actions moves into the primary group.

**Comment by jrieken** [comment]
I could always have "Toggle Changes" and mange its enablement (instead of visibility)
