### ISSUE TITLE
Unable to hide minimap on OSX El Capitan

### ISSUE THREAD

**Issue by christrinidad** [Microsoft/vscode#21808]
On OSX 10.11 El Capitan MBP, even with "editor.minimap.enabled": false, I cannot hide/disable the minimap.  

- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 15.0.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|1.3.1|
|vscode-eslint|dbaeumer|1.2.7|
|atom-keybindings|ms-vscode|2.0.0|
|debugger-for-chrome|msjsdiag|2.5.5|;

---

Steps to Reproduce:

1. settings.json ->     "editor.minimap.enabled": false
2. restart vs code
3. see on editor windows, minimap on right.  

note: workaround I do is to make maxColumn = 0, but the shadow is still visible.

**Comment by christrinidad** [comment]
My mistake.  Global settings were set correctly 'false', but in project, there is a .vscode/settings.json that had it set to 'true'.  Not sure how that happened.  Did not enter that manually.  Oh well.  Thanks anyway!

**Comment by dinusuresh** [comment]
Thanks for taking the time to post the solution @christrinidad  :+1:
