### ISSUE TITLE
Shouldn't 'occured' be 'occurred'?

### ISSUE THREAD

**Issue by adelphes** [Microsoft/vscode#21806]
- VSCode Version: 1.10.1
The new (and highly visible) exception view:

![occured](https://cloud.githubusercontent.com/assets/13035517/23519569/4e85d248-ff6f-11e6-9c34-c26c867ceb7c.jpg)
![occurred](https://cloud.githubusercontent.com/assets/13035517/23519572/50d32898-ff6f-11e6-90ce-0eb129fdeae2.jpg)

**Comment by michelkaporin** [comment]
Thank you for reporting this. Fixed in bd2ea4458727d8565a6712af50591c919e2487f1.

**Comment by isidorn** [comment]
@michaelchiche once you fix issue please close them :)
