### ISSUE TITLE
ServiceWorker: `workbench.web.main.nls.js` is blocked

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#218050]
Testing #216888

* FF
* open devtools
* open https://insiders.vscode.dev/?vscode-version=43f70eca0c428e6f1a5bfad59a9b2a66f99b748d
* :bug: the NLS file cannot be loaded because of CORS issues

```
The resource at “https://main.vscode-cdn.net/insider/43f70eca0c428e6f1a5bfad59a9b2a66f99b748d/out/vs/workbench/workbench.web.main.nls.js” was blocked due to its Cross-Origin-Resource-Policy header (or lack thereof). See https://developer.mozilla.org/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)#
```

**Comment by bpasero** [comment]
Hm, I am a bit clueless here. It seems to happen when a request results in a 404 and then maybe the service worker tries to step in and attempts to load it from there in the background? 

The 404 will go away once we ship the new solution, currently vscode.dev is in a hybrid mode.

**Comment by bpasero** [comment]
Merging into https://github.com/microsoft/vscode-dev/issues/1157. We should not load this file with newer versions, but I would only do that change when we are back from vacation season.
