### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by ayush000** [Microsoft/vscode#21809]
- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:04:47.508Z)</code>
- OS Version: <code>Darwin x64 16.5.0</code>
- CPUs: <code>Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)</code>
- Memory (System): <code>4.00GB (0.10GB free)</code>
- Memory (Process): <code>150.23MB working set (0.00MB peak, 85.18MB private, 54.95MB shared)</code>
- Load (avg): <code>4, 3, 3</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|218|
|main|app.isReady => window.loadUrl()|626|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|708|
|renderer|require(workbench.main.js)|1925|
|renderer|create extension host => extensions onReady()|2035|
|renderer|restore viewlet|1166|
|renderer|restore editor view state|2307|
|renderer|overall workbench load|2847|
|main + renderer|start => extensions ready|6020|
|main + renderer|start => workbench ready|6668|

---

:warning: Make sure to **attach** these files: :warning:
-`/Users/swarn/e749_main.cpuprofile.txt
[e749_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/814676/e749_main.cpuprofile.txt)
[e749_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/814677/e749_renderer.cpuprofile.txt)

`
-`/Users/swarn/e749_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Thanks. Looking at the profile, it seems like you suffer from #22087. Closing this as dupe.
