### ISSUE TITLE
Starting debugger updates the file in current active tab 

### ISSUE THREAD

**Issue by cedricnicolas** [Microsoft/vscode#21802]
When starting the debugger, the currently opened file (inside the active tab in VScode), is updated. 
Problem : when run with tool like nodemon and grunt watch, this restarts node, and then stops the debugger.
This issue is since last update (1.10.1) of VsCode, was not like that before.

- VSCode Version: 1.10.1
- OS Version: Mac Os 10.11.4

Steps to Reproduce:

1. Have nodemon and grunt watch running 
2. Open any js file
3. Start debugger with config : 
```
 {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5857,
            "address": "localhost",
            "restart": false,
            "sourceMaps": true,
            "outDir": null,
            "localRoot": "${workspaceRoot}",
            "remoteRoot": null
        },
```
==> the currently opened tab is updated, just after clicking on debugger start. eg : nodemon output

```
>> File "schemas/customerSchema.ts" changed.
Running "ts:node" (ts) task
Compiling...
Using tsc v2.1.6
```

Result : impossible to debug, because updating a source file launch through grunt watch typescript compiler (it is what we want, indeed). Compiler then force node to restart, and then debugger is stopped...back to the beginning......

**Comment by cedricnicolas** [comment]
Improvement on my post :

Using tsc -w instead of grunt watch, it is better : tsc -w delivers this : 
```
18:00:53 - File change detected. Starting incremental compilation...
18:00:56 - Compilation complete. Watching for file changes.
```
tsc -w detects a file change, but doesn't fully relaunch compiler, then nodemon doesn't restarts node. Maybe tsc is detecting that in reality nothing changed in the file.

Still an issue, as we can't use grunt anymore with that issue.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/21681#issuecomment-283870770
