### ISSUE TITLE
Chat outline in response title is cut-off

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#218031]
1. Chat view, "What are the issues from this repo assigned to me"
2. You get a response, click on the `GitHub Copilot used ...` line
3. Outline is cut 🐛 

The outline should contain the actions on the right

![Image](https://github.com/user-attachments/assets/c42b051e-fda6-4f0a-b871-c0655ed76aed)

**Comment by isidorn** [comment]
Better than before -> verified
However the outline should be 1px or 2px larger. If you zoom in you can see how the outline cuts in the gray circle around the icon.

@roblourens let me know if you want a new issue for this.


![Image](https://github.com/user-attachments/assets/4642cd8a-6f87-47d7-9e78-2f45b1f6473d)
![Image](https://github.com/user-attachments/assets/1deb5042-22ad-4eb7-b3ed-6293625b6c49)

**Comment by roblourens** [comment]
Pushing a fix for that
