### ISSUE TITLE
References view overlaps scrollbar

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#218083]
Testing #217202

<img width="678" alt="image" src="https://github.com/user-attachments/assets/75f7749c-128e-45b2-beef-f161444f4f4e">

Note the response text area seems appropriately margined/padded.

**Comment by daviddossett** [comment]
Hm, might just be a matter of applying padding a different layer to avoid the scrollbar appearing as such. The quick input might be some useful prior art here given the effect of list items appearing with padding but the container without.

![Image](https://github.com/user-attachments/assets/1239f9c9-9e1d-41dc-a55c-56b6b55e642c)
