### ISSUE TITLE
Memory leak related to editor

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#218077]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2	
- OS Version: Ubuntu 24.04

### Steps to Reproduce

1. Create a file "a.txt" with contents "a"
2. Create a file "b.txt" with contents "b"
3. Open file "a.txt", then open file "b.txt"
4. Repeat switching tabs several times
5. Notice that the number of detached Canvas elements increases by 3 each time

### Test script

```sh
git clone git@github.com:SimonSiefke/vscode-memory-leak-finder.git &&
cd vscode-memory-leak-finder &&
git checkout v5.49.0 &&
npm ci &&
node packages/cli/bin/test.js --cwd packages/e2e --only  editor.switch-between-tabs --check-leaks --measure-after --measure canvas-count --runs 17 &&
cat .vscode-memory-leak-finder-results/canvas-count/editor.switch-between-tabs.json 
```

### Test results

The number of canvas elements increases each time, indicating a memory leak:

![canvas-count](https://github.com/microsoft/vscode/assets/23744935/c3155a65-4be5-4539-86a8-d5b115380f89)

### Additional information 

- The memory leak seems not related to event listeners. The number of event listeners doesn't seem to increase during the tests. 

- *Something* seems to be holding on to disposed monaco editors, each monaco editor containing 3 canvas elements.

**Comment by TylerLeonhardt** [comment]
@bpasero assigned you from an editor/tabs perspective? Maybe you have an idea

**Comment by bpasero** [comment]
Sounds to me like it could be Minimap.

**Comment by SimonSiefke** [comment]
I tested again with VSCode 1.92.1 and found no more memory leaks related to canvas.

v1.90.2
![canvas-count](https://github.com/user-attachments/assets/a7e4345f-cebc-4d76-aeda-9370978133a6)


<br>

v1.91.2: 
![canvas-count-new](https://github.com/user-attachments/assets/795b9cb0-edc2-4385-8aea-92e0f5296568)
