### ISSUE TITLE
Apostrophe breaks syntax highlighting for Ini files

### ISSUE THREAD

**Issue by thijsvandien** [Microsoft/vscode#21804]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.9|
|vim|vscodevim|0.5.3|;

---

Steps to Reproduce:

1. Create an ini file where a text value contains an apostrophe in the middle, e.g.:

```
[Sample]
SomeKey=Someone's Value
SomeOtherKey=42
```

2. Note that from the apostrophe onward, the rest of the file is considered a string.

Different ini implementations have their own interpretations of values. E.g., Windows does not consider the apostrophes of a quoted value part of that value. I'm not aware of the exact rules, but at least the current highlighting behavior is wrong. I think it would be better to stick to the universally valid rules – sections, keys and values – and not to consider apostrophes special at all.

**Comment by aeschli** [comment]
This issue was moved to textmate/ini.tmbundle#3
