### ISSUE TITLE
Docker's agent response in chat streams code as if it was raw markdown

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#218199]
Testing #217639

Using the docker agent, you can see how it renders the code weirdly as it's being streamed: 

![Image](https://github.com/user-attachments/assets/1d19f445-7b1c-4ba9-9dcb-ecd1635bdd08)

**Comment by roblourens** [comment]
Same as https://github.com/microsoft/vscode/issues/217915 I think, although I can't get this kind of response out of `@docker`, it just returns an error for me :)
