### ISSUE TITLE
Show the profile name badge and provide ability to hide

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#218124]
Testing #217139

If I create a new profile and name it, the preview shows this:

![CleanShot 2024-06-25 at 10 12 21@2x](https://github.com/microsoft/vscode/assets/25163139/9613147b-1447-4cbc-a10e-4500434ff009)

When I change the icon, the badge goes away and I see the icon only

![CleanShot 2024-06-25 at 10 12 35@2x](https://github.com/microsoft/vscode/assets/25163139/08448627-b655-4892-9ea6-343bfedc13ff)

Not clear what the intended behavior is here—feels like we're in between UX approaches. Maybe include an option to show/hide the badge?

**Comment by sandy081** [comment]
> Maybe include an option to show/hide the badge?

I like this.

**Comment by gjsjohnmurray** [comment]
See also #194910

**Comment by gperdomor** [comment]
I don't understand why this was closed, it's a very useful feature in my opinion... At the end the idea is give to the user. the chose to hide or show the badge...
