### ISSUE TITLE
Extension Details pages don't show link underlines

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#218160]
Testing #217636

No links in an extension metadata page show links underlined...

![Image](https://github.com/user-attachments/assets/ea4d4f19-7517-4226-9aa0-96e1a6c6d75c)

**Comment by daviddossett** [comment]
Same as before, fixed and not merged in time via https://github.com/microsoft/vscode/pull/216859 and added underlines for the domain and resource section in #218214
