### ISSUE TITLE
Touch support can be improved in webviews

### ISSUE THREAD

**Issue by PowerSnail** [microsoft/vscode#21812]
- VSCode Version: Insider 1.11.0
- OS Version: Windows 10, Build 15046
- Machine: Surface Pro 3, with latest drivers

There are several places where touch support needs improvement:

1. In extension description pages, scrolling by touch does not work. 
2. In markdown preview, scrolling by touch does not work
3. When there is a split view, or when I just closed a tab, there is a possibility where tapping the tabs does not work. This is not reproducible every time. 

Touch is an essential functionality in many senarios. I often find it easier to scroll through webpages (like markdown previews) by touch than using the trackpad. There are also times people might use VS Code without a trackpad or mouse. It would be great help if touch support can be improved.

**Comment by sandy081** [comment]
Not sure where and who owns the touch related functionality. Hence starting with you @bpasero .

**Comment by bpasero** [comment]
I suspect an issue with touch support in our webviews. As for the issue around tabs I suggest to file a separate bug.

**Comment by mjbvz** [comment]
@bpasero I somewhat fixed touch support in the html preview (markdown preview) with d9de64e. This change applied absolute positioning to the `webview` element

However I'm not sure why touch support did not work in the first place. Also, on my Surface 3, the touch support was somewhat flaky. It would sometimes refuse for work for a few seconds when first loading the html preview and I'm not sure if this was specific to my Surface 3 or not.

@mousetraps Can you please do a quick test of the latest insiders builds on your Surface Book? Just try opening up a markdown preview and interacting with it on the touch screen. Let me know if you also see any odd behavior. 

If anyone else with a touch screen computer has a chance, please test out the markdown preview in the latest VSCode insiders builds and let me know what works and what doesn't

**Comment by mousetraps** [comment]
@mjbvz I'm running into the same flaky behavior. A few observations:
* the issue only occurs when multiple markdown previews have been opened in the session.
* tapping a few times on the webview seems to unlock it sometimes. 
* when the issue does occur, touch sometimes also stops working momentarily in the tab well (tapping another tab does not switch tabs as expected). This might be a totally unrelated issue, however. Touch continues working fine everywhere else as far as I can tell. 
* scrolling by touching the scrollbar in the webview also stops working

**Comment by codefoster** [comment]
Any motion on this? Willing to help test. I have a Surface Book.

**Comment by nealot** [comment]
I'm running linux with a laptop that has touch support. Would be interested in testing any developments for this environment.

**Comment by mjarkk** [comment]
It's also not possible to move the window via the custom title bar with touch.  

System:  
- OS: Solus 4.0 (linux)
- Desktop env: Budgie
- VSCode version: 1.33.1

**Comment by wmertens** [comment]
I don't see this mentioned, but you also can't scroll the editors with touch, a very natural gesture.

**Comment by wmertens** [comment]
In the most recent VSCode, scrolling editors with touch works :tada:.

Selecting doesn't but I think that's probably quite hard to get right anyway.

**Comment by Yamilquery** [comment]
The selection through touch is still not working. It would be great to have this feature soon

**Comment by wmertens** [comment]
@Yamilquery how would you propose it should work? double-tap, long-tap, and then drag markers?

**Comment by Yamilquery** [comment]
@wmertens it would be great with long-tap I think so! 🙌
