### ISSUE TITLE
Closing tabs on save through ssh

### ISSUE THREAD

**Issue by NicolaiBa** [Microsoft/vscode#21811]
- VSCode Version: version 1.9
- OS Version: ubuntu 16.04 LTS

Document tab closes upon saving. The documents in question are accessed via a remote server through ssh.

Steps to Reproduce:

The problem is hard to reproduce due to an irregular occurrence rate (about 1 in 10).
1. Alter a remote located file accessed through ssh.
2. Save the changes, then the tab closes

**Comment by bpasero** [comment]
@NicolaiBa this seems to be https://github.com/Microsoft/vscode/issues/13665

It would be awesome if you could follow https://github.com/Microsoft/vscode/issues/13665#issuecomment-283922320 and help me out find out more.
