### ISSUE TITLE
Unable to sign into settings sync with Github

### ISSUE THREAD

**Issue by SyntaxisCS** [microsoft/vscode#218115]
- VS Code Version: 1.90.2
- OS Version: MacOS Sonoma 14.1.1 (23B81)

I recently wiped my mac and reinstalled VSCode, I have been for a while and currently use Github to sync my settings and extensions between my other machines and this one. I still use Github to sync my settings and extensions on my windows machine but for some reason the option for a Microsoft account is the only that appears. If i click sign into settings sync and it immediately takes me to sign in to microsoft. Same happens for the account section. I provided some pictures of what I see at the bottom.

I'm not sure if this just something that is no longer an option or what but any help would be appreciated. As while it's not THAT big of a deal to switch to a microsoft account for sync, I'd just rather not.

<img width="285" alt="Screenshot 2024-06-25 at 12 51 00 PM" src="https://github.com/microsoft/vscode/assets/58380022/90f1005b-439a-401b-9ecd-3713a4afaa92">
<img width="316" alt="Screenshot 2024-06-25 at 12 53 58 PM" src="https://github.com/microsoft/vscode/assets/58380022/ed85fa18-0089-40da-aa62-6862db212fbd">

**Comment by TylerLeonhardt** [comment]
@sandy081 this user says that they are not given the option to sign in with GitHub so I think this is your domain.

**Comment by sandy081** [comment]
To switch accounts you should Turn Off Settings Sync and Turn On again - https://code.visualstudio.com/docs/editor/settings-sync#_switching-accounts
