### ISSUE TITLE
Configure KeyBinding Doesn't Work

### ISSUE THREAD

**Issue by sunliangqin** [microsoft/vscode#218187]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.2
- OS Version: Windows 23H2

Steps to Reproduce:
1. Make sure you have multiple repos
2. Right click on the commit id/branch of one repro, then select "Configure Keybinding"
3. Couldn't find the command

![image](https://github.com/microsoft/vscode/assets/211268/c1bdf81b-9c3d-4a6d-af4b-0eac202ff036)

**Comment by benibenj** [comment]
We are unable to support the `Configure Keybinding` action for status bar actions. Let me remove it from the context menu

**Comment by TylerLeonhardt** [comment]
Looks disabled now

![Image](https://github.com/user-attachments/assets/549aea65-2e28-49af-9aca-0e03db38c0dd)

**Comment by lszomoru** [comment]
@benibenj, I think we should completely remove the action as that will never work as far as I understood.

**Comment by benibenj** [comment]
I think it's fine to align with the hide action and disable the action when it's not supported. Each action in that toolbar has the hide and key binding action, so I think it makes more sense to disable these actions when they are not supported compared to just not showing them for some actions
