### ISSUE TITLE
Minimap does not highlight the visible part of the screen unless you hover on it

### ISSUE THREAD

**Issue by sarmadka** [Microsoft/vscode#21810]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:47:58.633Z)
- OS Version: Linux x64 4.4.0-64-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.2|
|cmake|twxs|0.0.15|
|vscode-react-native|vsmobile|0.3.1|;

---

Steps to Reproduce:

1. Enable minimap
2. Open a long file
3. Move mouse away from minimap

Actual:
Visible section highlight disappears.

Expected:
Visible section should remain highlighted.

**Comment by hellonearthis** [comment]
A quick fix would involve building VS Code from source and changing the minimap.css file.
[Stackoverflow question **vs code minimap location highlighting**](http://stackoverflow.com/questions/42561099/vs-code-minimap-location-highlighting/42564972#42564972).

**Comment by alexandrudima** [comment]
Let's track in #21784
