### ISSUE TITLE
Profiles Editor: expected delete icon on list item

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#218129]
Testing #217139

Why not include delete icons here? I only see them when the profile is not yet created.

![CleanShot 2024-06-25 at 10 15 36@2x](https://github.com/microsoft/vscode/assets/25163139/c5b2cf0d-5786-44f5-bc87-8930f5efac93)

**Comment by sandy081** [comment]
They are in the context menu.

![Image](https://github.com/user-attachments/assets/03cf5f8f-cac0-48c3-bab6-fe277125afe3)

I see in your sketch you have added them as primary actions here - https://github.com/microsoft/vscode/issues/218162. Lets discuss in that issue.
