### ISSUE TITLE
Editor Playground, Release Notes don't respect underline setting

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#218175]
Testing #217636

Expect links in Editor Playground (Help > Editor Playground) to support underline setting:

![Image](https://github.com/user-attachments/assets/a2f52f51-05c3-4ed8-8b2f-1f33b2dd597d)

Same issues in Help > Release Notes.

May be same as #217810

**Comment by daviddossett** [comment]
Another instance that was fixed by https://github.com/microsoft/vscode/pull/216859 but wasn't caught in time

![Image](https://github.com/user-attachments/assets/e22f0853-5671-4aef-b347-f72737ae7c57)
