### ISSUE TITLE
Profiles Editor: dirty state not obvious in editor

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#218110]
Testing #217139

I liked that we're using the typical editor tab/titlebar dots to indicate dirty state in the editor. It wasn't obvious in the tree which item was dirty though. Perhaps we should use the dot or some other decoration on the italicized list item here?

![CleanShot 2024-06-25 at 09 50 21@2x](https://github.com/microsoft/vscode/assets/25163139/bfd83a6d-9d60-4b89-b42f-e1d750fc41ce)

**Comment by sandy081** [comment]
It seems we do not show any indication in the explorer tree neither. Should this be a consistent experience everywhere?
