### ISSUE TITLE
Profiles Editor: align with form layout/settings UI

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#218162]
Testing #217139

Related to other feedback I've given, here's a quick sketch of what I think gets us more aligned with things like the settings UI. Ideally we could even reuse the basic settings UI under the hood, but I don't know how portable it is off the top of my head. This isn't totally thought through but hopefully conveys the general idea I had in mind.

Main talking points:
- Name and icon inputs are clearly labeled and have their own rows
- Descriptions are added where needed
- Actions are consolidated on the list item for each profile
- Form actions are moved to the bottom
- Table gets a name/description

![CleanShot 2024-06-25 at 11 06 49@2x](https://github.com/microsoft/vscode/assets/25163139/17cdc67d-e323-4f66-936a-cd4dac45d7bb)

**Comment by sandy081** [comment]
Thanks for the feedback. I like it is aligned with Settings UI and will incorporate these changes in the next milestone.

**Comment by sandy081** [comment]
Regarding primary actions on the profile in the LHS, I think **New Window** should be the only primary action and other should be in the overflow.
