### ISSUE TITLE
Cannot turn off wordwrap

### ISSUE THREAD

**Issue by joshualemli** [Microsoft/vscode#21816]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Despite careful perusal of the settings (including the "Toggle Words Wrap" menu option), lines continue to wrap on screen.  This issue seems oddly intermittent --, sometimes when I load up the editor, word wrap is OFF, but after switching tabs, it turns ON.

Specifically, this issue affects PHP files I am editing.  Other files don't seem to have this issue (JS,HTML, CSS...).

Steps to Reproduce:

1. modify settings to turn off word wrap
2. frustration

**Comment by xavadu** [comment]
duplicated here: https://github.com/Microsoft/vscode/issues/21801

I have the same issue.

**Comment by alexandrudima** [comment]
Let's track in #21801
