### ISSUE TITLE
Profiles Editor: modal for successful export seems heavier than needed

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#218137]
Testing #217139

Any particular reason we wouldn't just use a notification here?

![CleanShot 2024-06-25 at 10 24 21@2x](https://github.com/microsoft/vscode/assets/25163139/cdb10402-5270-461e-91cd-8169cc538fdc)

**Comment by sandy081** [comment]
Notification can be lost in silent mode and I think it is necessary for the user to know when a profile exporting is successful, given that it is a long running operation.
