### ISSUE TITLE
Default setting value from extension doesn't seem to be respected.

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/vscode#218173]
Testing #217238

Not sure if I'm missing something, but not able to get the setting values to be merged properly.

Steps to repro:
1. Pull two sample repository from samples extension (specifically chat-sample and theme-sample)
2. Create new workspace directory called testingWS. 
3. Create .vscode/extensions directory and place the two repository code inside.
4. Observe recommended extension show up as expected
5. Go to each of the sample extension repo code and add ```"configurationDefaults": {
      "workbench.editor.customLabels.patterns": {``` as directed:
- For example: 
```  "contributes": {
    "configurationDefaults": {
      "workbench.editor.customLabels.patterns": {
        "a": "1",
        "b": "2"
      }
    },
``` 

for chat-sample and 
```  "contributes": {
    "configurationDefaults": {
      "workbench.editor.customLabels.patterns": {
        "b": "20",
        "c": "30"
      }
    },

``` 

for theme-sample in each of their package.json.
6. npm install in each repository and finally install recommended extensions.
7. Direct to settings editor UI: 
<img width="332" alt="Screenshot 2024-06-25 at 11 22 32 AM" src="https://github.com/microsoft/vscode/assets/62267334/37f86cb8-a702-4863-a54e-53674e8e5b93">
and check in the UI and both settings.json from the UI and see that workbench.editor.customLabels.patterns" is not showing up. 

Rather, ones that I manually define within the UI does show up in the settings.json and settings editor UI itself:
<img width="766" alt="Screenshot 2024-06-25 at 11 24 40 AM" src="https://github.com/microsoft/vscode/assets/62267334/69fa79c4-b848-41fa-8011-d35adb98d3a2">

<img width="451" alt="Screenshot 2024-06-25 at 11 25 28 AM" src="https://github.com/microsoft/vscode/assets/62267334/66152288-181f-434a-a1c5-8a22f79c40e7">

**Comment by benibenj** [comment]
Ohh I think the sample extensions did not activate. I should have mentioned you need to also make sure the sample extensions have an activationEvent specified in the package.json file. You should be able to use `activationEvents: ["*"]` for testing. Please give this another try

**Comment by anthonykim1** [comment]
@benibenj I see.. I did include activationEvents as you mention in each of the two package.json file, but still not able to get this: 
```  
"configurationDefaults": {
    "workbench.editor.customLabels.patterns": {
      "b": "20",
      "c": "30"
    }
  },
  "activationEvents": ["*"] 
}
```
in one of the repository,

```
  "configurationDefaults": {
    "workbench.editor.customLabels.patterns": {
      "a": "1",
      "b": "2"
    }
  },
  "activationEvents": ["*"]
}
``` 
in the other. 

Still just end up getting
```"workbench.editor.customLabels.patterns": {
    "e": "10"
},
``` through settings editor :/ 
"e":"10" is what I have manually added in the setting editor itself.

**Comment by benibenj** [comment]
I probably missed a step in the instructions, really sorry about that. I just tried it and it works. You need to make sure to check the dev tools to see the extension activate to be sure everything is set up correctly.
I ran `yarn` to install all dependencies and `npm run compile` to build the extension. It worked then.

Closing this issue as it works for me and others.
