### ISSUE TITLE
Links to Settings not underlined or highlighted

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#218154]
Testing #217636

Links to overridden settings (here is shows as _Modified in_ **_User_**) to show as links nor are they affected by the `underlineLinks` setting.

![Image](https://github.com/user-attachments/assets/89750b13-5b40-41e0-808d-8e02d168ff74)

**Comment by daviddossett** [comment]
As in, they don't use the typical link color? @rzhao271 is that intentional? 

Agreed that they should pick up the setting, in any case.

**Comment by daviddossett** [comment]
Here's how it would look

![Image](https://github.com/user-attachments/assets/cdbf05d2-4bfc-46d7-92b6-ffab3ca75fc2)

**Comment by rzhao271** [comment]
I don't remember whether it was on purpose in order to not make the link stand out too much.
I'm alright with changing the colour of the link and keeping the underline for improved accessibility.

**Comment by daviddossett** [comment]
Agreed. Merged the change and we can tune it from there if needed.
