### ISSUE TITLE
Should the Getting Started page links support underline?

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#218156]
Testing #217636

Should the Getting Started page links to create a new file, open folder, etc. have links as well. The TPI says links are added under `<p>` elements, but as a user I don't know where those are, I just see links in the product.

![Image](https://github.com/user-attachments/assets/0131c46e-3ca5-411e-8956-cd91ae73073c)

**Comment by daviddossett** [comment]
Fixed by https://github.com/microsoft/vscode/pull/216859, I just forgot to merge it yesterday 🤦‍♂️

![Image](https://github.com/user-attachments/assets/9dfb1017-fbd8-4753-945d-0d645d5dbf64)
