### ISSUE TITLE
Terminal Hover Feedback

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#218118]
Testing microsoft/vscode-python#23674

![image](https://github.com/user-attachments/assets/43c3f879-c1af-4863-8abd-ddd83e5a5fd0)

I would use capital casing. Also the links seem cut off on the right @Tyriar

**Comment by Tyriar** [comment]
@daviddossett thoughts?

**Comment by daviddossett** [comment]
Seems like we aren't consistent here. But I'd agree that we generally should use capital casing for commands. I think I've seen that pattern used more often than not.

![Image](https://github.com/user-attachments/assets/42b7ca88-8f05-4afe-a39e-e9b4fc945715)

![Image](https://github.com/user-attachments/assets/d3a2db0c-d372-4756-b8dc-88e18aeeb66c)
