### ISSUE TITLE
Profiles Editor: default profile should be default for new windows if no others exist

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#218131]
Testing #217139

I would have expected this checkbox to be checked for the default profile if no others exist yet. It probably makes sense to keep it checked unless users change that in some subsequently created profile.

![CleanShot 2024-06-25 at 10 18 41@2x](https://github.com/microsoft/vscode/assets/25163139/f5d295db-343e-48e1-ad05-d479ff7b0085)

**Comment by sandy081** [comment]
I see what you mean. But this is not the truth when there are more than one profile. Profile for new windows is the last active window profile by default. Instead, it makes sense to remove this configuration when there are no profiles?
