### ISSUE TITLE
Profiles Editor: not clear why table dropdowns turn into checkboxes

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#218135]
Testing #217139

As a user, I don't know why these turned into checkboxes. Can I not choose to configure this to copy from a profile post-creation? If that's the case, maybe disable the option in the dropdown + provide messaging? It's strange to see the overall UI component change. 

![CleanShot 2024-06-25 at 10 21 31@2x](https://github.com/microsoft/vscode/assets/25163139/02a16861-855c-4c39-bbcc-d2f4ae8ca5f6)

**Comment by sandy081** [comment]
> Can I not choose to configure this to copy from a profile post-creation?

Yes. Copy from option is not available on existing profiles. Only configuration allowed is to Use Default Profile or not. Dropdown will have then following options

- Use Default Profile
- Use this Profile

May be showing the dropdown with these two options is more explanatory.

**Comment by sandy081** [comment]
This is fixed with the latest UI
