### ISSUE TITLE
Profiles Editor: Templates should use relevant icons

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#218120]
Testing #217139

Seems like it would be more appropriate to use the Python icon for the Python template, Java icon for Java templates(s), and so on.

![CleanShot 2024-06-25 at 10 03 41@2x](https://github.com/microsoft/vscode/assets/25163139/64a61d22-1047-4bbe-87c3-5311f0005fa6)

**Comment by sandy081** [comment]
@isidorn This needs to be changed in the templates

**Comment by isidorn** [comment]
To verify - 
1. open profiles editor
2. New profile dropdown > from template. Choose Python, Java or Doc writer
3. Make sure you get a nice suitable icon

**Comment by TylerLeonhardt** [comment]
This doesn't seem released yet. Maybe next insiders?

**Comment by rzhao271** [comment]
Still not seeing it in the 3-hour old Insiders

**Comment by sandy081** [comment]
Published templates are not yet available on CDN. Lets wait for some more hours and check later.
