### ISSUE TITLE
How to disable tooltips in the sidebar with display of file/directory paths?

### ISSUE THREAD

**Issue by peter31990** [microsoft/vscode#218257]
How to disable tooltips in the sidebar with display of file/directory paths?
![obraz](https://github.com/microsoft/vscode/assets/11589305/a605d208-bd81-4e58-aa6a-55027c9757c5)

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode/issues/70768

**Comment by monk-afk** [comment]
Here's a workaround that worked for me; a broken setting to the workbench.hover.delay in User/settings.json:

```json
    "editor.hover.enabled": false,
    "workbench.hover.delay": null,
```
