### ISSUE TITLE
`Commit (amend)` is syncing which is not clear

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#218216]
Testing #217398

* Be in this state where you have a local commit already and a _staged_ change:

<img width="297" alt="image" src="https://github.com/user-attachments/assets/fb92d1e9-80e3-42b0-b9f1-a5dc8c4af1a6">

* Run `Commit (Amend)`:

<img width="487" alt="image" src="https://github.com/user-attachments/assets/8fed6392-bdd9-4b11-93f4-4dc816dfecbf">

* Accept the commit message

* 🐛 the commit does get amended, but then sync changes occurs and my code is pushed:
<img width="378" alt="image" src="https://github.com/user-attachments/assets/8f46e67a-0954-4629-84cb-0e7282603ea0">

I was expect no push/sync since it's in the top section of this menu:

<img width="236" alt="image" src="https://github.com/user-attachments/assets/ab8a71eb-5fe1-4bb7-89fd-e5fcba5a795c">

**Comment by lszomoru** [comment]
What is the value of your `git.postCommitCommand` setting? Thanks!

**Comment by TylerLeonhardt** [comment]
Yeah it's set to `"git.postCommitCommand": "sync",`

**Comment by lszomoru** [comment]
The current implementation is that the command from this setting is executed after all the commit types of actions. I can revisit that.
