### ISSUE TITLE
1.10.1 Installer adds OSS version of Right Click Context Menu

### ISSUE THREAD

**Issue by johnduhart** [Microsoft/vscode#21827]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. Install/Update to the 1.10.1 official build of Visual Studio Code with right click context menus enabled
2. Right click on a file in Windows Explorer
3. Menu shows 'Open with Code - OSS' rather than Visual Studio Code

![Right click menu](http://i.jhd5.net/2017/03/Code_2017-03-02_15-08-01.png)

**Comment by michelkaporin** [comment]
Thank you, however it was already raised and subsequently fixed in #21659.
