### ISSUE TITLE
Visually a bit confusing when you have local, remote, and main all different commits

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#218223]
Testing #217398

<img width="283" alt="image" src="https://github.com/user-attachments/assets/1d7059b5-3db9-4f08-bb84-50411b7c5eee">

The state:
* checkout a topic branch from main
* `[topic]` change something & commit
* `[topic]` push
* switch to main branch
* `[main]` change something & commit
* switch to the same topic branch as before
* `[topic]` change another thing & commit

Couple things:
* I think it's difficult to know which line represents which thing... ok I can understand that the blue line with the "blue circle in the blue ring" with the target-looking icon on the right represents the local side of things... but I can't tell just by looking which line is the remote `topic` branch vs the `main` branch. There should probably be visual indication between them without me having to hover over the icon on the right to figure that out
* The local branch is associated with the remote branch of the same name... yet the local branch line is on the left and the remote branch is all the way on the right... they don't really seem associated if the main branch is sitting in the middle of them

**Comment by lszomoru** [comment]
Thanks for the feedback. We are planning on making some improvements in the upcoming milestones to help with this.

**Comment by lszomoru** [comment]
There have been several UX improvements in the "Source Control Graph" view:
* Badges shown on the right hand side are now colored
* Badges shown on the right hand side contain the branch name (truncated if needed)

> The local branch is associated with the remote branch of the same name... yet the local branch line is on the left and the remote branch is all the way on the right... they don't really seem associated if the main branch is sitting in the middle of them

The "swim lane" order is determined by git. We are using "topological order" which was created to make git graphs look nicer.
