### ISSUE TITLE
Incorrect block end detection when using cat << EOF with a backslash

### ISSUE THREAD

**Issue by sergio-costas** [microsoft/vscode#218287]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2
- OS Version: Ubuntu 24.04

Steps to Reproduce:

1. Create a .sh file with this content:
```
cat <<\EOF >/output.file
a block of text/data/whatever you want
EOF

echo yada yada yada
echo blah blah blah

# a comment here
```
2. All the code is marked as the content being sent to the file, when it should be marked only up to the EOF line
![Captura desde 2024-06-26 12-09-04](https://github.com/microsoft/vscode/assets/105285003/e2168cc0-57df-4d35-a938-3a5abe271556)
3. Removing the backslash in the first line shows the code correctly colored:
![Captura desde 2024-06-26 12-08-56](https://github.com/microsoft/vscode/assets/105285003/afd39575-2288-4925-ab57-159ee0e72d12)

The backslash in the `cat` instructs the shell parser to not expand neither environment variables nor other escaped sequences inside the block, thus copying it verbatim.

**Comment by alexr00** [comment]
Moved to the upstream repo: https://github.com/jeff-hykin/better-shell-syntax/issues/107
