### ISSUE TITLE
Website text easily gets jagged on download page

### ISSUE THREAD

**Issue by Pajn** [Microsoft/vscode#21829]
- OS Version: Ubuntu 16.10
- Browser: Firefox 51.0.1

Steps to Reproduce:

1. Open http://code.visualstudio.com/docs/?dv=linux64_deb
2. Hover over a link or scroll hastily
3. Now text look like this 
![screenshot from 2017-03-02 21-04-43](https://cloud.githubusercontent.com/assets/817422/23525213/f59dab00-ff8d-11e6-90cb-61d0e6760329.png)

This only happens on the download page and it only seem to happen when the loading animation for the top extensions are running (which by the way seems way to long?).
I realize that this probably is due to a bug in Firefox, the Intel graphic drivers or somethings else but I have never seen it on any other page so I wanted to start by reporting it here. I don't know, maybe you are doing something strange on that page.
I tried changing the font of the page to a standard system font but the behavior did not change.

**Comment by waderyan** [comment]
This is wild! I'll take a look. Let me know if you discover anything else.

**Comment by yfdyh000** [comment]
This issue should be report to https://bugzilla.mozilla.org/describecomponents.cgi?product=Core&component=Graphics%3A%20Text#Graphics%3A%20Text.

**Comment by Pajn** [comment]
I agree that it probably should be reported to Mozilla instead.
I can no longer reproduce it though so I wont do that right now at least.
Hover I'm closing this, I can't see how it can be the pages fault. I no longer know why I reported it here in the first place, sorry for the noise!
