### ISSUE TITLE
Easier `Add all missing imports`

### ISSUE THREAD

**Issue by ravshansbox** [microsoft/vscode#218236]
Type: <b>Feature Request</b>

Allow `Add all missing imports` as a separate command without forcing cursor to be on top of an unimported symbol

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:54:35.075Z)
OS version: Darwin arm64 23.5.0
Modes:

**Comment by mjbvz** [comment]
There's a already a source action for this:

![Image](https://github.com/user-attachments/assets/47456748-5e8c-4027-aa22-2d20791c5f59)

You can even setup a keybinding using `editor.action.sourceAction` if you'd like
