### ISSUE TITLE
SCM Graph - How about some actions on these commits? "Revert commit" "reset commit", etc

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#218207]
Testing #217398

<img width="373" alt="image" src="https://github.com/user-attachments/assets/aade16f2-33ae-485e-a2bb-7134e08328cd">

It'd be cool if I could right click on one of the commits and revert or reset it in case I accidentally commit or something.

**Comment by lszomoru** [comment]
Closing as duplicate of [#217987](https://github.com/microsoft/vscode/issues/217987)
