### ISSUE TITLE
markdown latex title rendering bug: $\arccot x$

### ISSUE THREAD

**Issue by zyjdmmm** [microsoft/vscode#218244]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2
- OS Version: Windows 10 专业版 22H2 19045.4529

Steps to Reproduce:

1. copy this to *.md
```
#### $\arccot x$ have bug
#### $\arcsin x$
#### $\arccos x$
```
2. but it runs good running in typora

**Comment by mjbvz** [comment]
See https://github.com/KaTeX/KaTeX/issues/2274

Please open a new issue against Katex if you think this should be supported by default

**Comment by zyjdmmm** [comment]
i have a new discovery:
```
$\operatorname{arccot} x$//it runs
```
