### ISSUE TITLE
`security.allowedUNCHosts` does not appear to work

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#218234]
I'm not sure what I'm supposed to do here, according to the documentation this should(?) work:

![image](https://github.com/user-attachments/assets/f3cd387e-00f9-4af5-bd03-f53934fb260c)

**Comment by gjsjohnmurray** [comment]
Is the note in the penultimate paragraph of https://code.visualstudio.com/docs/setup/windows#_working-with-unc-paths (about remote workspaces) relevant to you?

**Comment by bpasero** [comment]
Did you restart?

**Comment by connor4312** [comment]
I thought I restarted, but maybe I didn't. It works today 🤔
