### ISSUE TITLE
editor.occurrencesHighlight: "multiFile" not working

### ISSUE THREAD

**Issue by GioGiglio** [microsoft/vscode#218261]
Type: <b>Bug</b>

1. set editor.occurrencesHighlight to "multiFile"
2. open two files side by side
3. select a word (that is present in both files) in one of the files

the editor will highlight all occurrences of the same word in the current editor, but not on the other one, and viceversa.

Something else I've noticed: if I restart vscode and **immediately** select something on one editor, the highlight will work on the other editors as well, but if I wait a couple of seconds after restarting it doesn't work anymore. This also happens with all extensions disabled and without settings customizations except for editor.occurrencesHighlight.

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.55GB (16.85GB free)|
|Process Argv|--crash-reporter-id 9adbe916-c415-45f8-a1cb-9386deaf588d|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31082724

```

</details>

**Comment by Yoyokrazy** [comment]
Apologies for the late reply, is the issue still occurring in the latest stable release (`1.91`)? Also, are you expecting to see all textual occurrences (just the same string, no semantic knowledge) highlighted, or are these semantic occurrences (ie an exported class in another file, etc).

If the issue is reproducible, I would appreciate consistent/detailed steps, as I am unable to reproduce this bug on my current environment. Thanks!
