### ISSUE TITLE
Add semantic highlighting/folding range support for Copilot chat code blocks

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#218246]
![image](https://github.com/microsoft/vscode/assets/14052197/03953937-93c9-4408-9df2-7de1171a7a63)

No highlighting for Java import part, it might be helpful to support semantic highlighting for them. Also we can enable folding range to expand/collapse code range.

// cc: @mattbierner

**Comment by Yoyokrazy** [comment]
I'm not able to reproduce this, and currently we do support semantic highlighting within chat codeblocks. 

https://github.com/user-attachments/assets/96f69ff2-54c2-499c-ad8e-deaf26ac23cd
