### ISSUE TITLE
"Select to copy" in integrated terminal

### ISSUE THREAD

**Issue by gswalden** [Microsoft/vscode#21821]
[iTerm2](https://www.iterm2.com/documentation-general-usage.html) has a very convenient feature which copies any selection to your clipboard immediately upon _mouseup_. If VS Code could implement this in the integrated terminal, I think it'd be great! 

I will also note I fully understand I could use iTerm2 has an external terminal to make use of this feature today.

**Comment by smuuf** [comment]
If implemented, please **make this an option**. ***I*** wouldn't want to overwrite *my precious* clipboard just by selecting something in the terminal.

**Comment by ffes** [comment]
The Cygwin mintty has this feature as well and I always miss it when I open use my terminal in Xubuntu. I would immediately enable such a feature.

**Comment by Tyriar** [comment]
In the meantime you may want to turn this one on which is common on Windows:

```js
  // When set, this will prevent the context menu from appearing when right clicking
  // within the terminal, instead it will copy when there is a selection and paste when
  // there is no selection.
  "terminal.integrated.rightClickCopyPaste": true,
```

**Comment by Tyriar** [comment]
No plans to implement this, there are already many ways to configure copy/paste in the terminal.

**Comment by vikas027** [comment]
Hey @Tyriar , 
As of now, I am using`cmd+c` to copy text in terminal. What is the alternative (as mentioned in the previous comment) there to do the same by just selecting text?

**Comment by gswalden** [comment]
@vikas027 using the setting he mentioned [here](https://github.com/Microsoft/vscode/issues/21821#issuecomment-284007083) you can select then right-click to copy.

**Comment by vikas027** [comment]
Thanks @gswalden , I got it now. So it is select, right-click to copy, and then right-click to paste.

**Comment by mikecarr** [comment]
@Tyiar "No plans to implement this, there are already many ways to configure copy/paste in the terminal" do you wish to elaborate? Is there a link somewhere we can go see how? Is this tribal knowledge? This may not be evident to new users.

**Comment by Tyriar** [comment]
@mikecarr I did a write up on this here http://www.growingwiththeweb.com/2017/03/mastering-vscodes-terminal.html#copy-and-paste

**Comment by Tyriar** [comment]
This ended up being added, see https://github.com/Microsoft/vscode/issues/36271. See the `terminal.integrated.copyOnSelection` setting
