### ISSUE TITLE
Refer issue no. 151668 . Facing same issue in 1.90.2 . Downgrading to 1.86.1 works

### ISSUE THREAD

**Issue by kirtisingh803** [microsoft/vscode#218242]
Does this issue occur when all extensions are disabled?: Yes. I just installed from the deb file, and tested it.

- VS Code Version: 1.90.2
- OS Version: Linux Mint 21.3
- Kernel: 5.15.0-91-generic

Steps to Reproduce:

1. Open a file from a folder
2. Then click, File -> Open File , the dialog goes to the user's home folder instead of the opened file folder.

When I downgraded from 1.90.2 to 1.86.1 , this issue was not then not present.

**Comment by justschen** [comment]
ref: https://github.com/microsoft/vscode/issues/151668

**Comment by drankinatty** [comment]
I have seen similar problems with the file-open dialog not being displayed at all in the vscodium build starting with Ver 1.90.0. Downgrading to 1.89 solves the problem. The file-open dialog issues may be related. Details at [Linux - vscodium no longer displays file-dialog after update to Ver. 1.90.0](https://github.com/VSCodium/vscodium/issues/1927)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/213780, please follow the issue for updates.
