### ISSUE TITLE
switching language and reloading does not update language in core functionality

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#218231]
Testing #216888

seeing extensions have updated the language to spanish (both after clicking through the change dialog and after reloading the window) but the core functionality such as sidebar views do not update to spanish
<img width="1279" alt="Screenshot 2024-06-25 at 3 19 53 PM" src="https://github.com/microsoft/vscode/assets/26030610/58b1b6a9-7643-4883-a9fa-fce5dab89707">
<img width="1285" alt="Screenshot 2024-06-25 at 3 19 43 PM" src="https://github.com/microsoft/vscode/assets/26030610/8ec659d9-617f-4f6c-a811-f032abd7066c">

**Comment by bpasero** [comment]
@eleanorjboyd is this web or macOS? does it help to reload with devtools opened to bypass caches?

**Comment by eleanorjboyd** [comment]
This is on web- how do I load with devtools? Like with F12? I am not seeing the toggle dev tools command I normally see on desktop version on web.

**Comment by bpasero** [comment]
Can you re-test with latest after clearing caches, we pushed some changes.

**Comment by eleanorjboyd** [comment]
looks good now! Thanks
