### ISSUE TITLE
SCM history: allow to show/hide dynamically

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#218263]
I want to use the history feature, but would love to bring it in ad-hoc without having to change the setting. I think I am very much used to the changes view being empty when I am done with my change and populated otherwise. With the timeline showing lots of things, it makes me feel I need to review:

<img width="412" alt="image" src="https://github.com/user-attachments/assets/32290a04-f567-47f0-b987-046066413f4e">

Some ideas:
* allow to collapse the view
* make it a real view to toggle?
* have a action to show/hide

**Comment by gjsjohnmurray** [comment]
Another idea is to allow toggling between history and graph view via the gearwheel menu. At the moment this always offers history-mode settings, even when graph has been enabled:

![image](https://github.com/microsoft/vscode/assets/6726799/ea8cd3bc-866f-4b88-b362-1ab292d5ccbf)

**Comment by lszomoru** [comment]
Closing this issue as the "Incoming/Outgoing" section has been removed.
