### ISSUE TITLE
Is the graph suppose to be chronological?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#218228]
Testing #217398

I found myself in this state:

* checkout a topic branch from main
* `[topic]` change something & commit
* `[topic]` push
* switch to main branch
* `[main]` change something & commit
* switch to the same topic branch as before
* `[topic]` change another thing & commit
* Merge `main` into `topic

Which gave me this:
<img width="896" alt="image" src="https://github.com/user-attachments/assets/f6f8d1ac-546e-4f64-a095-e0a2424745b9">

I did have a merge conflict that I had to fight, but addressed it.

Here's what's odd to me... 

`commit something local` was committed _after_ `stuff 2`... so idk... I feel like I would expect `commit something local` to be above `stuff 2` in the graph (making the graph sorted chronologically where newest is on top)... but in this case, it's under `stuff 2`.

Is this expected?

**Comment by lszomoru** [comment]
Thanks for the feedback. The commits are in topological order as we are using the [`--topo-order`](https://git-scm.com/docs/git-log#Documentation/git-log.txt---topo-order) flag. This is the flag that is being used when you run `git log --graph` as it makes sure that the graph is more readable.
