### ISSUE TITLE
Inline chat buttons overlap with focus border

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#218395]
* make a inline chat request
* select 👍 or 👎 
* 🐛 the borders overlap

![Image](https://github.com/user-attachments/assets/4fb00c88-f43a-42af-afa9-8b19cffc78d8)

**Comment by TylerLeonhardt** [comment]
looks good now

![Image](https://github.com/user-attachments/assets/fc3ee4e0-811b-4bf5-9b98-3b4bb266c0be)
