### ISSUE TITLE
Multi-target debugging fails to execute second configuration saying it doesn't exist when exact copy of name of configuration

### ISSUE THREAD

**Issue by JohnGalt1717** [Microsoft/vscode#21838]
- VSCode Version: 1.10.1
- OS Version: Windows 10 Anniversary Edition

Steps to Reproduce:

1. I have a asp.net spa angular 2 application that I'm trying to debug both .net core and into chrome, firefox or Edge automatically on F5.
2. I have the following launch.json:
```
{
    "version": "0.2.0",
    "compounds": [
        {
            "name": "Debug in Chrome",
            "configurations": [
                ".NET Core Launch (console)",
                "Launch Chrome"
            ]
        },
        {
            "name": "Debug in Edge",
            "configurations": [
                ".NET Core Launch (console)",
                "Launch Edge"
            ]
        },
                {
            "name": "Debug in Firefox",
            "configurations": [
                ".NET Core Launch (console)",
                "Launch Firefox"
            ]
        }
    ],    
    "configurations": [        
         {
            "name": "Launch Edge",
            "type": "edge",
            "request": "launch",
            "url": "http://localhost:5000",
            "webRoot": "${workspaceRoot}/app/files",
            "sourceMaps": true
        },
        {
            "type": "firefox",
            "request": "launch",
            "name": "Launch Firefox",
            "url": "http://localhost:5000",
            "webRoot": "${workspaceRoot}"
        },
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:5000",
            "webRoot": "${workspaceRoot}/wwwroot",
            "userDataDir": "${workspaceRoot}/.vscode/chrome"
        },
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/netcoreapp1.1/<dllname>.dll",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "externalConsole": false,
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceRoot}/Views"
            }
        },
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/netcoreapp1.1/<dllname>.dll",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceRoot}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command.pickProcess}"
        }
    ]
}
```

3. If I use  .NET Core Launch (console) or Launch Chrome they work fine by themselves.
4. If I use the Debug in Chrome (or Edge or Firefox) VS Code gives me an error saying that the configuration "Launch Chrome" doesn't exist in my launch.json which it clearly does.
5. If I move the compounds to the bottom of the file it doesn't matter. No matter what it gives the same error.
6. If I change the order of the configurations so that the Launch Chrome configuration is first this works and both launch but if you interact with the browser at all it crashes.
7. Also note that the browser starts before the .NET Core Launch (console) is finished starting. It's important that this waits otherwise you end up having to refresh the browser after it finishes building and running the .net core solution even if this was to work. (it would be better if the .NET core Launch (web) instead of launching browser could launch another configuration so that it was clear when it was done and then ran the second one automatically (i.e. all of the configurations should allow that once done to run additional configurations in a nested style (recursively)

**Comment by JohnGalt1717** [comment]
Does this mean that it's planned to be fixed for the march update?

**Comment by isidorn** [comment]
@JohnGalt1717 this means I plan to investigate into fixing it. After I gather more details I can give a more precise estimate

**Comment by JohnGalt1717** [comment]
What further details do you need? Because right now this entire feature is broken.

**Comment by isidorn** [comment]
@JohnGalt1717 can you please try to reproduce this with latest vscode insiders that you can get here http://code.visualstudio.com/docs/?dv=win&build=insiders

* I am not able to reproduce the issue pointed in step 4. Is it possible that you create a minimalistic repository on github for which you see this? You should be able to do this just by using simple nodejs samples as the compound logic in vscode is indepenedet of the language debugged
* As for the issue pointed in step 6 if you interect with a browser it crashes, I suggest to report an issue against the chrome vscode extension here https://github.com/Microsoft/vscode-chrome-debug
* As for the timing of launching each dependent configuration, we already had a long discussion about this in our team and currently it is only possible to do this by manually first launching one configuraiton, waiting some time and then launching the other one.

**Comment by JohnGalt1717** [comment]
Just do a dotnet new and then use the launch.json that I posted above and you've got a repro.

And #6 only happens if you put "Launch Chrome" first to try and avoid the bug. If you manually run them one after the other you won't get this problem.

And obviously the whole point to compound debugging is so that you don't have to manually run them, and there is absolutely no scenario where you'd want compound debugging to work as it does now and not sequentially like Vs.net does and has done forever so I'm at a loss as to why this was designed as it was and why this isn't a bug to be fixed because the current functionality is basically useless.

**Comment by aubrym** [comment]
Hi @isidorn . I have the same problem.
I created a "solution" with some projects and configured the launch.json file to debug more than one at the same time using a compound.
But when I try to run the compound with two or more projects I receive the following message:

> Configuration 'SecondProject' is missing in 'launch.json'.

I already verified this and the configuration exists in the launch.json file.

Can I help you in the resolution of this case with reports, scenarios or testing?

Best Regards,

Aubry Maciel

**Comment by isidorn** [comment]
@aubrym the best thing for me would be if you could create a minimalistic repository on github that simply reproduces this behavior. Then I could just clone it and repro the issue locally.
If possible using node, since I would prefer not having to setup dotnet on my machine.
I am asking for this since I was unable to create a simple repository that shows this issue.
And also make sure you can reproduce this in vscode insiders https://code.visualstudio.com/insiders

Thanks!

**Comment by JohnGalt1717** [comment]
How is it that you got asigned a ticket about .Net when you don't want to install .Net in your machine?

You need to reassign this to someone that actually wants to solve the issue or step up and do as I instructed in the first place to reproduce this bug.

*Headbang* how the heck does a Microsoft project have someone fixing bugs that doesn't want to use .Net?
________________________________

**Comment by JohnGalt1717** [comment]
*bump*  This is major blocker bug in vs code. Anyone else at MS want to take responsibility for this and install .net?

**Comment by aubrym** [comment]
Hi @isidorn. I'll try to create this minimalistic repository.

**Comment by isidorn** [comment]
@aubrym great - thanks

**Comment by Hoostine** [comment]
@isidorn I created a repo that reproduces the issue for me at https://github.com/Hoostine/vscode-issue-21838
the "Full Stack" launch config will encounter the error the SECOND and subsequent time it's run. It looks like it happens when there is more than one launch configuration involved with preLaunchTask's defined. e.g. one on Server and one on Full Stack in the repo above.

HOWEVER this is all moot because it doesn't seem to affect the insider's build. the preLaunchTask defined on the second config _isn't run_*, but it also doesn't seem to break things.

*i put `npm install` as a preLaunchTask on the node launch and the browser launch, then started the compound containing them both, and was immediately presented with an exception from node about requiring unknown modules. shortly after, the npm install text popped into the output window and the browser opened. it only fired the task once for the first launch it started (i presume.)

**Comment by isidorn** [comment]
@Hoostine sorry only got to this issue today. As far as I see you are saying it is working for the insiders build. Can you please verify that and if that is true then this issue seems to be fixed and will be available in the stable in around 10 days?
Thanks

**Comment by JohnGalt1717** [comment]
It's fixed in the latest public release. This can be closed.

**Comment by isidorn** [comment]
@JohnGalt1717 great, thanks!
