### ISSUE TITLE
Feature request: Add option for current opened file's directory to 'terminal.integrated.cwd'

### ISSUE THREAD

**Issue by Splike** [Microsoft/vscode#21837]
Currently when opening the integrated terminal, we have two options for the default terminal path:
1. The path is set to the current working directory (i.e. the current working project folder).
2. The path is set to an explicit path given by the user.

There should be a 3rd option, where the path is the current opened file's directory.

**Comment by Tyriar** [comment]
Right now this use case is covered by https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here
