### ISSUE TITLE
Missing a line break before closing ``` in accessible view

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#218397]
Found testing https://github.com/microsoft/vscode/issues/213941

![Image](https://github.com/user-attachments/assets/6936d656-cb1f-4c2e-a32d-3826938c26ed)

**Comment by TylerLeonhardt** [comment]
![Image](https://github.com/user-attachments/assets/1afcdc78-a631-4349-9d2a-8fe7833a7cef)

Looks good now
