### ISSUE TITLE
Tree in broken state after File Copy/Paste

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/vscode#21833]
- VSCode Version: 1.10.1, commit 653f8733dd5
- OS Version: Ubuntu 16.04

I apologize in advance that I wasn't able to come up with a smaller repro.

After copy/pasting a file in a deeply nested directory within the open workspace, the directory the file was pasted into appears to be the top-level directory of the workspace... kind of. The higher level directories appear below the pasted directory, and the pasted directory appears in the "normal" part of the file tree. Moreover, the pasted directory appears to be open in the "normal" part of the tree, but it's contents are not located below the pasted directory's name. Hopefully the clip below will provide some clarification.

![file_copy_messes_up_file_tree](https://cloud.githubusercontent.com/assets/3226984/23527325/58b4b5ce-ff4a-11e6-9740-7554fd61f25b.gif)

Steps to Reproduce:

1.
```
git clone https://github.com/Microsoft/TypeScript
cd TypeScript
code .
```
2. Right click to copy some file under `tests/cases/fourslash`. For sake of consistency, use `tests/cases/fourslash/breakpointValidationDo.ts`
3. Right click paste the file under the directory `tests/cases/fourslash`. Note that `tests/cases/fourslash` must be expanded for the bug to occur.
4. Observe that the file navigation tree is in a weird state.

**Comment by bpasero** [comment]
Looks like a tree bug to me. Adding @joaomoreno 

@aozgaa any chance we could access to that workspace? Does it reproduce reliably? When it reproduces can you check if there is something in the logs:

Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by joaomoreno** [comment]
Awesome that it reproduces always! Thanks for the detailed steps.

As @bpasero pointed out, it would be great to get access to that repo. Is it open source?

**Comment by aozgaa** [comment]
Wow, super fast turn around on the issue, thanks!
