### ISSUE TITLE
Auto JSDoc comments should also add other tags @returns, @throws, etc.

### ISSUE THREAD

**Issue by tSte** [Microsoft/vscode#21832]
It would be good if [Auto JSDoc comments](https://code.visualstudio.com/updates/v1_10#_auto-jsdoc-comments) automatically added also other annotations than `@param`. It should at least add `@return` (or `@returns`) and `@throws`. It would be great if those were also configurable (e.g. prefer `@return` or `@returns`; do not add `@return` if function returns only `undefined`; and so on).

**Comment by mjbvz** [comment]
`@returns` support is being tracked upstream by https://github.com/Microsoft/TypeScript/issues/14248

`@throws` support and configuration are interesting ideas. I'll keep this issue open to track support for those

**Comment by SandHilt** [comment]
If you wish or i need ideas about it, you can see a vscode extension called '[Document This](https://marketplace.visualstudio.com/items?itemName=joelday.docthis)'.

**Comment by mjbvz** [comment]
Closing as upstream
