### ISSUE TITLE
Git log viewer like in Jetbrains IDEs

### ISSUE THREAD

**Issue by siva636** [Microsoft/vscode#21848]
We need a smart log viewer for Git like in Jetbrains IDEs such as Webstorm / PHPStorm:
https://d3nmt5vlzunoa1.cloudfront.net/phpstorm/files/2013/11/phpstorm_7_1_log_viewer.png 

(There are many Git log related extensions for VSC, but none of them are user friendly and feature rich like in Jetbrains IDEs)

**Comment by joaomoreno** [comment]
#68
