### ISSUE TITLE
Use the webgl renderer in terminal sticky scroll

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#218427]
Notice how powerline symbols via custom glyphs don't work above:

![Image](https://github.com/user-attachments/assets/b8f6d630-400a-47d7-b926-6f470326ad9d)

The dimensions are also slight off due to this https://github.com/microsoft/vscode/issues/216817

**Comment by andreamah** [comment]
The glyphs render, but I get some strange rendering changes once it becomes sticky. It's as if there is an extra white outline.
[![Image from Gyazo](https://i.gyazo.com/a47a172ccd23ffc959cb126dfc16ec90.gif)](https://gyazo.com/a47a172ccd23ffc959cb126dfc16ec90)

I'm using [atomic](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/atomic.omp.json) from ohmyposh.

**Comment by Tyriar** [comment]
@andreamah that was spotted in https://github.com/microsoft/vscode/issues/216817 so tracked over there
