### ISSUE TITLE
vscode报错：在过去的5分钟内，TypeScript语言服务以外中止了5次

### ISSUE THREAD

**Issue by wade1860** [Microsoft/vscode#21845]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.一打开vscode，正上方就开始频繁的弹“vscode报错：在过去的5分钟内，TypeScript语言服务以外中止了5次”
2.一直弹，几乎每秒弹2、3下

**Comment by f111fei** [comment]
也行是你安装了360杀毒，360杀毒会把vscode安装目录里面的`tsserver.js`删除掉。 建议卸载流氓软件360杀毒然后重新安装一下vscode

**Comment by mjbvz** [comment]
Thanks @f111fei! This is likely the root cause.

@wade1860 please let me know if you suspect otherwise
