### ISSUE TITLE
VSCode 

### ISSUE THREAD

**Issue by azbo** [Microsoft/vscode#21844]
- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:10:18.838Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1796)</code>
- Memory (System): <code>9.82GB (4.86GB free)</code>
- Memory (Process): <code>125.48MB working set (125.48MB peak, 94.95MB private, 34.12MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|47|
|main|app.isReady => window.loadUrl()|871|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|693|
|renderer|require(workbench.main.js)|1406|
|renderer|create extension host => extensions onReady()|1836|
|renderer|restore viewlet|628|
|renderer|restore editor view state|1|
|renderer|overall workbench load|2510|
|main + renderer|start => extensions ready|5149|
|main + renderer|start => workbench ready|5555|

---
:warning: Make sure to **attach** these files: :warning:
-`C:\Users\Demo\6018_main.cpuprofile.txt`
-`C:\Users\Demo\6018_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
closing because files are missing
