### ISSUE TITLE
Terminal inline chat bottom padding is messed up

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#218402]
Think this started happening in the last ~2 days

![Image](https://github.com/user-attachments/assets/db43f09b-1117-4ab3-bc30-60bc745afb46)

**Comment by Tyriar** [comment]
In code oss 😕 


![Image](https://github.com/user-attachments/assets/1a4c99cc-b748-47ee-bbf0-74dc0c214859)

**Comment by Tyriar** [comment]
Seems related to `"inlineChat.experimental.textButtons": true`

**Comment by Tyriar** [comment]
It's meant to look like this:



![Image](https://github.com/user-attachments/assets/43288c6e-4893-4ea6-addd-63a10becc4fb)

**Comment by amunger** [comment]
fyi - it looks like @jrieken also pushed a fix for this https://github.com/microsoft/vscode/issues/218021

the end result looks find tho

**Comment by Tyriar** [comment]
That's great as I couldn't repro the padding-less bottom in OSS, my change just fixed the text not showing so this all makes sense
