### ISSUE TITLE
BUG: When search is open & you're editing files, vscode lags dramatically

### ISSUE THREAD

**Issue by jamesone** [Microsoft/vscode#21842]
- VSCode Version: Version 1.9.0 (1.9.0)
- OS Version: macOS Sierra 10.12

Steps to Reproduce:

1. Go into your project & search for something that occurs regularly - E.g the name of a react component
2. Wait for the results to appear in the left sidebar
3. Click on a file that contains the SEARCH term
4. Start editing that file
5. Notice the lag

Confirmed that this happens when searching for a term that occurs 3 times - The code editor will lag

Probably due to vscode dynamically updating the search in the sidebar every time a change is made? I do notice that the sidebar will dynamically change the snippet of code if it as been changed

**Comment by roblourens** [comment]
Hm, I've never seen a lag here. We just released a new version of vscode, can you try updating to 1.10 to check if it reproes?

**Comment by roblourens** [comment]
Also I'm curious whether an extension could impact this. Can you try launching with `--disable-extensions` and check whether it reproes?

**Comment by jamesone** [comment]
After the update: Can confirm it still lags
Launching without extensions: Wasn't able launch without them

It could be eslint maybe 🤔 

Anyway if anyone else comes across this error - Then we can further investigate it.

**Comment by roblourens** [comment]
Can you tell me what problem you had launching without extensions?

**Comment by jamesone** [comment]
@robertohuertasm Disabled all extensions & the lag was still there

**Comment by roblourens** [comment]
Is this an especially large file?

Any ideas @sandy081 ?

**Comment by jamesone** [comment]
The files that this occurs on are pretty standard, >= 100 @roblourens To remove the lag I just change to the another tab (mostly the folder tab).

**Comment by sandy081** [comment]
Just to confirm, you see the lag in editing only when Search viewlet is open ?

**Comment by jamesone** [comment]
That's correct! 

Sent from Outlook




On Tue, Mar 7, 2017 at 9:13 PM +1100, "Sandeep Somavarapu" <notifications@github.com> wrote:












Just to confirm, you see the lag in editing only when Search viewlet is open ?

**Comment by sandy081** [comment]
@jamesone Is it possible to post a video of what you are seeing which might help us in figuring out what's happening? 

Also, can you open developer tools using command `Toggle Developer Tools` and see if there are any errors or anything fishy?

Also, is it possible to provide the profile by doing following steps

- To create a CPU profile using developer tools in VS Code:
    * select Help > Toggle Developer Tools
    * click on Profiles
    * click the start button
    * do whatever you need to do to reproduce the problem
    * wait for some time (10-20 seconds should be enough)
    * stop the profiling
    * click the save button and attach the output file to this issue

Thanks in advance

**Comment by TroubadourFabiolas** [comment]
Hello,
I have the same problem since 1 week or more,
My Config : 
- OS X El Capitan version 10.11.4
- Visual Studio Code : 1.10.1

You can my output file profile, here : https://we.tl/Tn3f7Qdzmc

Here a screenshot from my Activiy Monitor : 

<img width="792" alt="capture d ecran 2017-03-07 a 16 11 23" src="https://cloud.githubusercontent.com/assets/8639345/23663640/83a2b53a-0353-11e7-9bc0-b113c87b003c.png">


Thank you

**Comment by TroubadourFabiolas** [comment]
Hello,
I tested with 1.10.2 version and I have the same problem

Any idea ?

**Comment by roblourens** [comment]
We changed the search backend and hopefully this isn't around anymore. If anyone still reproes it, please see https://github.com/Microsoft/vscode/issues/21842#issuecomment-284690656

**Comment by TroubadourFabiolas** [comment]
Yes, i'm not the bug anymore. Thank you.

**Comment by jeffom** [comment]
Hi I'm having this issue
Attaching the profile while reproducing it,
[CPU-20170816T125216.cpuprofile.zip](https://github.com/Microsoft/vscode/files/1228754/CPU-20170816T125216.cpuprofile.zip)

I'm using the vscode in a fairly big Unity Project
