### ISSUE TITLE
JSDoc autogeneration not working?

### ISSUE THREAD

**Issue by rhys-vdw** [Microsoft/vscode#21843]
- VSCode Version: 1.10.1
- OS Version: OSX Sierra

Behaviour of my VSCode doesn't match [release notes](https://code.visualstudio.com/updates/v1_10#_auto-jsdoc-comments)

No `@param`s are added to the generated block.

![autodoc](https://cloud.githubusercontent.com/assets/822105/23534099/b079d98c-0009-11e7-8322-c8383f5dd4c9.gif)

**Comment by mjbvz** [comment]
I'm unable to repo this with a simple exported function. Can you please share some source code that shows this problem?

**Comment by origin1tech** [comment]
Seeing slightly different issue. JSDoc markup is output however it is missing types.

This outputs:

    /**
    * @param name
    */

But this is expected:

    /**
    * @param {string} name
    */

![jsdoc](https://cloud.githubusercontent.com/assets/1781771/23572819/9a8c881e-0026-11e7-8cd5-2ecfdecbba18.gif)

**Comment by mjbvz** [comment]
@origin1tech That is by-design for TypeScript. See [my comment](https://github.com/Microsoft/vscode/issues/21728#issuecomment-283779770) about why this is the case. Basically, the TypeScript types are source of typing truth in TypeScript files, not jsdoc types

**Comment by origin1tech** [comment]
Thx @mjbvz yeah I honestly wondered that or gave that thought, but the example shows the types so it was a bit misleading.

wondering now how doc compilers will work with that for building out documentation sites.

**Comment by rhys-vdw** [comment]
Ah, okay. I've worked out what happened. This is not a bug.

I had this keybinding config:

```json
    { "key": "enter", "command": "-acceptSelectedSuggestionOnEnter" },
```

And I was pressing <kbd>Enter</kbd> anyway... (Typically I press <kbd>Tab</kbd> while I'm coding, I guess I just didn't think about it here.) Apologies for the false report. I was thrown by the different newline handling for JSDoc:

![block comment](https://cloud.githubusercontent.com/assets/822105/23592405/76b3c67a-0254-11e7-97d5-bdc5aecd1630.gif)
