### ISSUE TITLE
sorting files should be correct

### ISSUE THREAD

**Issue by tyeth** [microsoft/vscode#218423]
Type: <b>Bug</b>

If I have four files in a folder then they show mostly in order (alphabetical), but not the bmp3xx. Order shows as follows:

bme280.py
bme680.py
bmp3xx.py
bmp280.py

Clearly the bmp sensor files should be in reverse, 3 is **incorrectly sorted** before 2, probably some artifact of the x's being used for encoding with \x2F for example.

VS Code version: Code - Insiders 1.91.0-insider (4580ba51fe1914ca29916f829adb35930089b013, 2024-06-25T15:29:07.211Z)
OS version: Windows_NT x64 10.0.26120
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.54GB free)|
|Process Argv|--crash-reporter-id d7fc61b6-5fea-46f9-8100-b1286f2d3d11|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|9.8.0
teleplot|ale|1.1.3
berry|ber|0.1.1
vscode-innosetup|cho|1.9.2
vscode-eslint|dba|3.0.10
copilot|Git|1.207.0
copilot-chat|Git|0.17.2024062601
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.90.0
vscode-rdbg|Koi|0.2.2
vscode-lottie|lot|1.0.5
vscode-docker|ms-|1.29.1
csharp|ms-|2.34.12
vscode-dotnet-runtime|ms-|2.0.7
autopep8|ms-|2024.1.11501016
black-formatter|ms-|2024.3.11501016
debugpy|ms-|2024.6.0
pylint|ms-|2023.11.13481007
python|ms-|2024.9.2024062601
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.374.0
remote-ssh|ms-|0.113.2024062515
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
cmake-tools|ms-|1.18.42
cpptools|ms-|1.21.0
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2024.3.2
remote-explorer|ms-|0.5.2024061309
remote-server|ms-|1.6.2024061709
vscode-serial-monitor|ms-|0.12.0
vsliveshare|ms-|1.0.5932
vscode-nanoframework|nan|1.0.165
pico-w-go|pau|3.8.2
proto|pet|0.0.4
platformio-ide|pla|3.3.3
vscode-protolint|ple|0.8.0
sqlite-viewer|qwt|0.6.2
polaris-for-vscode|Sho|0.9.8
ruby-extensions-pack|Sho|0.1.9
ruby-lsp|Sho|0.7.5
sorbet-vscode-extension|sor|0.3.35
cmake|twx|0.0.17
wokwi-vscode|Wok|2.5.1
clang-format|xav|1.9.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
chatpanelt:31014475
g316j359:31013175
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
2f103344:31071589
nb_pri_only:31057983
nativerepl1:31071684
pythonrstrctxt:31083681

```

</details>

**Comment by tyeth** [comment]
![image](https://github.com/microsoft/vscode/assets/6692083/cdff4ef2-7938-4270-9a1f-88e93da1c0cd)

**Comment by gjsjohnmurray** [comment]
Related meta-issue #27286

**Comment by lramos15** [comment]
Try playing around with this setting and let me know if none of those work 


![Image](https://github.com/user-attachments/assets/8ccf54b0-4309-4f99-a225-e1d6dc5ebdf6)

**Comment by tyeth** [comment]
Sorry haven't got access to the machine now. I'll try and come back to this, but it should be an easy recreation. I'm on UK English if that helps narrow anything down.

**Comment by lramos15** [comment]
Yeah with setting set to unicode I see 

![Image](https://github.com/user-attachments/assets/053861c6-5d43-4003-8c1b-c6bf36a67002)

**Comment by tyeth** [comment]
Aha, good deduction/guess! Emojis for the win then I suppose...

**Comment by tyeth** [comment]
Oh that's a shame, should I retitle "Default sorting isn't predictable" and
reopen or create a new issue. I have no user setting nor workspace setting
etc, so would expect the default to be unicode or something close to
alphanumeric.

**Comment by lramos15** [comment]
I've filed https://github.com/microsoft/vscode/issues/218530 around changing the default
