### ISSUE TITLE
editorScroll has regressed in VSCode 1.10

### ISSUE THREAD

**Issue by johnfn** [Microsoft/vscode#21857]
In VSCodeVim, we are using the "editorScroll" command to move both the cursor and the page up and down by half-pages when the user types Ctrl-u and Ctrl-d, respectively.

In VSCode 1.9.1, this worked fine.

In VSCode 1.10.0, this has broken. The cursor no longer consistently moves up or down the page.

This has accumulated (relatively, for us anyways) a large number of thumbs up on our issues page: https://github.com/VSCodeVim/Vim/issues/1348#issuecomment-283712969 

Help!

**Comment by rebornix** [comment]
```
// Ensure the view is the first event handler in order to update the layout
this.eventDispatcher.addEventHandler(this);
```

We triggered the cursor update (which reads layout info) when View receives `onScrollRequest` event, however the ViewLines doesn't update the layout yet as it receives the event later than View as View is ensured to be the first one.

**Comment by johnfn** [comment]
Wow, well done @rebornix! 🔥

**Comment by alexandrudima** [comment]
Follow-up: #22147

**Comment by alexandrudima** [comment]
```
{
    "key": "ctrl+f2",
    "command": "editorScroll",
    "when": "editorTextFocus",
    "args": { "to": "up", "value": 1, "by": "halfPage", "revealCursor": true }
}
```

**Comment by alexandrudima** [comment]
@rebornix Can you please also verify this?

**Comment by jrieken** [comment]
being a vim-noob, `ctrl+u/d` seems to do the right thing but I leave it @rebornix to verify

**Comment by rebornix** [comment]
It's pretty good.

**Comment by gwojan** [comment]
I'm still not sure scrolling is working correctly. ```Ctrl-d```, ```Ctrl-u```, ```Ctrl-f```, ```Ctrl-b``` do not scroll down like gvim.

With the cursor at the start of the document pressing ```Ctrl-f``` locates the cursor at the bottom of the screen. Pressing ```Ctrl-f``` a second time moves the current line to the top of the visual window.

```Ctrl-f``` in gvim scrolls by one screen-height of text with each press.
