### ISSUE TITLE
Report issue button dosen't work in new update 1.10.1

### ISSUE THREAD

**Issue by mihirp1730** [Microsoft/vscode#21856]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. report issue not working
2.

**Comment by isidorn** [comment]
Works for me. On what os are you seeing this?
What error are you getting?
Please provide more details

**Comment by ramya-rao-a** [comment]
@mihirp1730  Closing this issue as we havent heard back from you in a while.

If you can provide us more details as per @isidorn's questions, then we can re-open this issue
