### ISSUE TITLE
Commented content shows in output

### ISSUE THREAD

**Issue by mihirp1730** [Microsoft/vscode#21855]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Old comment is good
2. Commented content
![bug-vscode](https://cloud.githubusercontent.com/assets/24892060/23539363/d0f9ed9a-0000-11e7-89b7-76e83343d193.JPG)
 cant be seen in ouput

**Comment by isidorn** [comment]
Please provide steps on how to reprodce this issue and what the actuall issue is.
What are you expecting, what are you seeing and how can I reproduce this on my machine

**Comment by mihirp1730** [comment]
you can see the comment was appear in view of application. i want to comment that portion, but it shows with comment and end comment added. i'm expecting that please remove the bug and simply don't show commented part.

i'm using Windows 10 pro, before the last update visual code working perfectly.

**Comment by isidorn** [comment]
I appologize but I am having a hard time undersatanding what you are trying to say. Please provide exact deterministic steps on how to reproduce the issue you are seeing.

Thank you

**Comment by mihirp1730** [comment]
i'm sorry that you don't get my point.

if you do comment during code what it effect?

Here snippet.

{% comment %}
    <ion-nav-buttons side="right">
        <button class="button button-clear icon ion-ios-cart"
ng-click="vm.showCart()"></button>
    </ion-nav-buttons>{% endcomment %}

the same thing shows in view/output,

i want to do this.



this will not shows in output.

**Comment by aeschli** [comment]
Do you want a new feature that turns {% comment %} into <!-- ?

Maybe use find/replace?

**Comment by mihirp1730** [comment]
Yup cause it doesn't comment the code. It just show that cade was
commented.. if same feature do the same thing means do comment the code
properly than its ok...

On 7 Mar 2017 2:07 p.m., "Martin Aeschlimann" <notifications@github.com>
wrote:

Do you want a new feature that turns {% comment %} into <!-- ?

Maybe use find/replace?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/21855#issuecomment-284656496>,
or mute the thread

**Comment by aeschli** [comment]
I checked our code and the only language that adds {% %} comments is python.
HTML always does <!--
I don't know how your {% comments got added, maybe it was an extension?
If you added them yourself and the request is to have a feature that changes them from {% to <!-- then I suggest to use find/replace.
