### ISSUE TITLE
Broken comment syntax highlight (JavaScript)

### ISSUE THREAD

**Issue by fabiogusmao** [Microsoft/vscode#2185]
Just a minor issue but I noticed that if you put a comment line in the middle of a function declaration the comment line is not showing in gray.

![image](https://cloud.githubusercontent.com/assets/2974851/12515884/bf54b75c-c111-11e5-9d60-c51b9c73f8f9.png)

**Comment by fabiogusmao** [comment]
Ah yeah and it also happens that the word **default**  is not highlighted in a switch/case block.

![image](https://cloud.githubusercontent.com/assets/2974851/12521862/5c7fb190-c134-11e5-88ed-5360f1e68819.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#61
