### ISSUE TITLE
After the string length error in git commit, send button is disabled

### ISSUE THREAD

**Issue by DaviMenezes** [Microsoft/vscode#21858]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-file-peek|abierbaum|1.0.1|
|vscode-theme-onedark|akamud|1.3.1|
|one-monokai|azemoh|0.2.4|
|theme-onedark|azemoh|0.4.3|
|theme-firewatchneutral|bernardodsanderson|0.2.0|
|theme-desertex|casualjim|0.0.5|
|theme-itgdark|chriscarrick|0.2.0|
|theme-harmonic16-light|cotto|0.0.3|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.3|
|file-icons|file-icons|1.0.2|
|vscode-flatland-icon-theme|gebilaoxiong|0.0.6|
|Theme-Ocean-Dark-Soda|gerane|0.0.2|
|crane|HvyIndustries|0.2.2|
|hopscotch|idleberg|0.1.4|
|peachpie-vscode|iolevel|0.5.4|
|crayon-vscode|jansenfuller|0.1.3|
|theme-onedark-sublime|joshpeng|0.3.6|
|theme-material-theme|jprestidge|1.0.1|
|theme-glacier|Kal|0.0.1|
|format-indent|Kasik96|1.3.0|
|csharp|ms-vscode|1.7.0|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|theme-railscasts|PaulOlteanu|2.0.0|
|material-icon-theme|PKief|1.3.4|
|vscode-icons|robertohuertasm|7.3.0|
|ayu|teabyii|0.2.1|
|Material-theme|zhuangtongfa|2.1.2|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
What send button are you refering to? Can you please provide a picture?
Can you also reproduce this if you disable all your extensions?

**Comment by ramya-rao-a** [comment]
Closing this issue as we havent heard back from the OP in a while
