### ISSUE TITLE
[i18n] Chinese Translation Issue

### ISSUE THREAD

**Issue by King66** [Microsoft/vscode#21850]
i18n/chs/src/vs/workbench/parts/extensions/browser/extensionsActions.i18n.json
![1](https://cloud.githubusercontent.com/assets/11925432/23535823/c89b3fbe-fffb-11e6-91d7-1e9b0bafd9dc.jpg)

The translation of "enableAll" and "disableAll" are the same.

**Comment by King66** [comment]
Has been solved in latest version!

**Comment by johnliu2016** [comment]
Issue's closed. Correct translation is in file.
