### ISSUE TITLE
 Integrated Terminal File Link Prefix Removal

### ISSUE THREAD

**Issue by superlevure** [microsoft/vscode#218515]
I'm very much interested in this feature request that got closed: https://github.com/microsoft/vscode/issues/114301

Would the VSCode team consider a pull request from the community to add this?

**Comment by Tyriar** [comment]
A lot of functionality will fall over when you're remoted into a machine/container/etc., sorry but I don't think the proposed solution is elegant and generally useful enough to include as you'd need to encode paths in your docker container(s) into your local settings.

If you're a heavy docker user I'd recommend using the [containers extension](https://code.visualstudio.com/docs/devcontainers/containers) where links should work.
