### ISSUE TITLE
Shift + Alt + F: formatting adds whitespace in css mixed with html

### ISSUE THREAD

**Issue by lainz** [Microsoft/vscode#21852]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. Create a single html page wich contains a style tag with different styles, or see the sample attached
2. Format the code pressing Shift + Alt + F
3. Every time you format a single line is added between classes

**Comment by transtone** [comment]
#21717

**Comment by isidorn** [comment]
Dup of #21717
