### ISSUE TITLE
Accessibility signals are shipped in web

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#218695]
I am not sure if we support signals in web? But we do ship a lot of MP3 files in our `web-standalone` [drop](https://vscode.download.prss.microsoft.com/dbazure/download/insider/cb9d1e4589a05bed292f298acba7369e812f8cf1/vscode-web.tar.gz):

![Image](https://github.com/user-attachments/assets/0c2a3115-df44-4eca-94ae-2855f6a76471)

**Comment by meganrogge** [comment]
We do support them in the web 😄
