### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by jacobNNHS** [microsoft/vscode#218617]
ADD ISSUE DESCRIPTION HERE

Code space is not loading. Have exited and restarted multiple times.

Version: 1.90.2
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by aeschli** [comment]
For problems with Codespaces you have to contact the Github Support: https://support.github.com/contact?tags=rr-general-technical
