### ISSUE TITLE
We[official] have uninstalled the plugin which was reported to be problematic

### ISSUE THREAD

**Issue by godkun** [microsoft/vscode#218653]
Does this issue occur when all extensions are disabled?: Yes/No

![image](https://github.com/microsoft/vscode/assets/26134303/9218b7da-adf2-45d0-ae6b-2383a39e036f)

Hello official team, this morning we suddenly found that the vscode vivo-ai-code plugin was officially removed from the shelves. This plugin is only for internal employees of vivo and does not have any external services. 

We are very confused. When scanning vscode plugins, how do you determine if there is a problem with the plugin? We have not received any warnings or notifications about the removal, telling us what changes we need to make. We need the support of the official team to tell us the reason for the removal. We will make changes to meet the requirements for restoration.

**Comment by chrisdias** [comment]
Hello,

Thanks for creating this issue. 

However, I am going to close it because you are already having a conversation about the extension through email with the Marketplace security team.
