### ISSUE TITLE
Crash shortly after opening a 15MB .txt file

### ISSUE THREAD

**Issue by jpierson** [Microsoft/vscode#21869]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|elm-format|abadi199|0.1.0|
|Handlebars|andrejunges|0.2.0|
|cake-vscode|cake-build|0.6.0|
|Gradle|cazzar09|1.1.2|
|gitignore|codezombiech|0.5.0|
|vsc-rustfmt|Connorcpu|0.1.0|
|vscode-npm-source|dkundel|1.0.0|
|javadebugger|donjayamanne|0.0.2|
|xml|DotJoshJohnson|1.7.0|
|vscode-pandoc|DougFinke|0.0.8|
|java-debug|DSnake|0.0.2|
|EditorConfig|EditorConfig|0.3.4|
|vscode-npm-script|eg2|0.1.8|
|nuget4code|fforjan|0.0.2|
|Ionide-FAKE|Ionide|1.2.3|
|Ionide-fsharp|Ionide|2.23.5|
|Ionide-Paket|Ionide|1.6.1|
|tsd-recommender|jrieken|0.0.2|
|vscode-rust|kalitaalexey|0.3.8|
|Go|lukehoban|0.6.52|
|gitignore|michelemelluso|1.0.1|
|mssql|ms-mssql|0.2.1|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|debugger-for-chrome|msjsdiag|2.5.4|
|RustyCode|saviorisdead|0.19.1|
|elm|sbrink|0.8.3|
|velocity|sodatea|0.0.3|
|eval|Stormspirit|0.0.5|
|code-spell-checker|streetsidesoftware|0.17.2|
|vscode-open-in-github|sysoev|1.4.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. Open a specific large file with a .txt extension that holds about 15MB of XML content.

Expected behavior: File should open as normally, understandably laggy given the size.

Actual behavior: File opens for a few seconds and then VSCode consistently crashes shortly after.

NOTE: The file holds confidential data but it is invalid XML that doesn't appear to have line breaks at a glance.

**Comment by alexandrudima** [comment]
@jpierson I could not reproduce. I have tried to generate a file resembling what you describe via the following script:

```js
var _a = 'a'.charCodeAt(0);
var _z = 'z'.charCodeAt(0);

function getRandomInt(min, max) {
	return Math.floor(Math.random() * (max - min + 1)) + min;
}

function getRandomString(minLength, maxLength) {
	let length = getRandomInt(minLength, maxLength);
	let r = '';
	for (let i = 0; i < length; i++) {
		r += String.fromCharCode(getRandomInt(_a, _z));
	}
	return r;
}

var fs = require('fs');
var str = '';
for (var i = 0; i < 50000; i++) {
	var tagName = getRandomString(4, 8);
	var count = getRandomInt(1, 10);
	str += `<${tagName}>`;
	for (var j = 0; j < count; j++) {
		if (j !== 0) {
			str += ' ';
		}
		str += getRandomString(30, 70);
	}
	str += `</${tagName}>\n`;
}

fs.writeFileSync('out.xml', str);

```

The output was a ~15MB file looking like this:
<img width="1150" alt="screen shot 2017-07-06 at 09 45 06" src="https://user-images.githubusercontent.com/5047891/27900776-e2ee112a-622f-11e7-9ce6-52838bc3c7bd.png">

Can you consistently reproduce the OOM crash? Does it reproduce with `code --disable-extensions` ? Can you tweak our generating code above to generate a file that exhibits the crash ? Should lines be longer or shorter? Should there be more lines? etc.
