### ISSUE TITLE
Installation appears corrupt

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#21861]
![image](https://cloud.githubusercontent.com/assets/22350/23542915/fc189eba-ffef-11e6-8d61-e27aae46963e.png)

I got this yesterday at home and today in the office. Today's version is 4db944bc08e34fb15c5805927d9cb67470776606

I'm pretty sure I don't have an extension which ruins the files.

**Comment by alexandrudima** [comment]
@joaomoreno When you are in this state, can you please collect the following information:
- commit version
- save the following 4 files:
		"vs/workbench/electron-browser/workbench.main.js"
		"vs/workbench/electron-browser/workbench.main.css"
		"vs/workbench/electron-browser/bootstrap/index.html"
		"vs/workbench/electron-browser/bootstrap/index.js"
- we can then compute manually the md5 checksums and compare the files with the ones we shipped and determine if:
  - the files on your HDD are different than the ones we shipped
  - (or) we shipped with wrong md5 checksums

**Comment by alexandrudima** [comment]
Related: #20863

**Comment by alexandrudima** [comment]
We have been able to reproduce this. It appears that on OSX, when we show the update available pop-up, the underlying update mechanism already applies the update. That means that it is possible that we start up with version N, read the product.json from version N, and then 10s after startup we try to validate the files are OK, and we end up reading files from version N+1 (under the same path). 

This can have serious consequences, especially in cases when the main process is started at version N and a new window is opened with code from version N+1.

**Comment by joaomoreno** [comment]
Dupe #20863
