### ISSUE TITLE
Versatile Search Across All Files Specified by Name Within a Local Repository

### ISSUE THREAD

**Issue by VickySekhon** [microsoft/vscode#218665]
I don't know if there is any way to do this, however, I often find that I need to search for specific keys in multiple files. It would be extremely helpful for me to specify the files beforehand, and then initiate a search for my key. This eliminates redundancy and would improve my workflow when searching for things I know exist but may exist in a different file.

Think, MS Excel's search across the workbook feature. Instead, we specify the searchable files beforehand (perhaps using a mutable checkbox) and then click enter.

**Comment by gjsjohnmurray** [comment]
Can you leverage the existing option to search in open files only?

**Comment by VickySekhon** [comment]
That would work but is a bit cumbersome. At it's peak, my workspace becomes rather cluttered with many open files consisting of tests, code, or logic-based files. In many cases, only a select few of my files require a search.

**Comment by andreamah** [comment]
Could you use the `files to include` field to specify the file paths that you want to search?

**Comment by VickySekhon** [comment]
Oh this may work. Where is this option included?

**Comment by andreamah** [comment]
![Image](https://github.com/user-attachments/assets/0abed913-2f38-432b-a16f-0a24320c1e9a)

If you click the three dots in the viewlet, these fields should show.

**Comment by VickySekhon** [comment]
Sorry, I am not seeing this. 

I have the following:
![image](https://github.com/user-attachments/assets/c3a5ff3e-f1cd-441b-8347-1ce132affd32)

**Comment by gjsjohnmurray** [comment]
That is the Find widget, used for locating text in a single document. The screenshot from @andreamah is the Search view. Use the magnifier icon in the Activity Bar to get there.

**Comment by VickySekhon** [comment]
![image](https://github.com/user-attachments/assets/bfa4b778-2b92-4759-a835-aa5ea69d350d)

Yup! That about solves it. I am assuming that the 'files to include' menu starts at the root directory of a repository? 

For example, if I have the following filepath: ```schools -> teachers -> teacher.py, classesTaught.py, ...```

Then the search begins at folder ```schools```? Can you confirm this.

**Comment by andreamah** [comment]
If your workspace folder starts with everything under `schools`, then this path with start after `schools`, as you mentioned. You can also use [globs](https://code.visualstudio.com/docs/editor/glob-patterns) to get everything under one folder.

**Comment by VickySekhon** [comment]
Got it, thank you for your help @andreamah. You have been great : )
