### ISSUE TITLE
No response when I open a compressed javascript file

### ISSUE THREAD

**Issue by hangxingliu** [Microsoft/vscode#21860]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:47:58.633Z)
- OS Version: Linux x64 4.8.0-39-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.8.8|
|crane|HvyIndustries|0.2.2|
|eval|Stormspirit|0.0.6|
|comment-snippets|Tobiah|0.2.0|
|vscode-translate|chun|0.0.2|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.7|
|githistory|donjayamanne|0.1.5|
|vscode-html-css|ecmel|0.0.33|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|vscode-npm|fknop|3.3.0|
|vscode-coding-tracker|hangxingliu|0.3.2|
|Kotlin|mathiasfrohlich|1.2.0|
|vs-code-quick-require|milkmidi|0.1.0|
|vscode-apache|mrmlnc|1.1.0|
|cpptools|ms-vscode|0.10.2|
|csharp|ms-vscode|1.7.0|
|js-atom-grammar|ms-vscode|0.1.12|
|debugger-for-chrome|msjsdiag|2.5.5|
|node-modules-resolve|naumovs|1.0.2|
|sass-indented|robinbentley|1.3.0|
|code-spell-checker|streetsidesoftware|0.17.2|
|html-preview-vscode|tht13|0.1.1|;

---

1. Just use VSCode open this document: [mdjs.min.js](https://raw.githubusercontent.com/hangxingliu/mdjs/master/mdjs.min.js) 
2. Then VSCode will not response and system toast a "No response and would you want to restart" modal dialog

**Comment by alexandrudima** [comment]
@hangxingliu I cannot reproduce, for me the file opens fine.

Does the issue still occur when you launch VS Code w/ extensions disabled? From the command line: `code --disable-extensions`

**Comment by hangxingliu** [comment]
Thanks for your guide. After `code --disable-extensions` and `code --extensions-dir=tmp`, I found this is a bug in the extension `js-atom-grammar`.I think that I should create an issue in `js-atom-grammar` project

**Comment by hangxingliu** [comment]
I found there are not `js-atom-grammar` repository. And it's author is "Microsoft". So I think that this bug should be processed by developer in Microsoft.

**Comment by hangxingliu** [comment]
How to reproduce:

1. Installing extension `js-atom-grammar` (the version I am using is `0.1.12`)
2. Then downloading and opening the file <https://raw.githubusercontent.com/hangxingliu/mdjs/8815d3c0dedf312360618f1d31f1a23d532f10ca/mdjs.min.js> (This is a javascript file compressed by `uglify-js`)
3. You will find your VSCode has not response and then crash.

---
And if you open the file: <https://raw.githubusercontent.com/hangxingliu/mdjs/master/mdjs.min.js>   
You will find your VSCode has not response some seconds and then the highlight of this file be broken.

**Comment by aeschli** [comment]
The Atom JavaScrip grammar comes from https://github.com/atom/language-javascript.

I created https://github.com/atom/language-javascript/issues/500 for you there.
