### ISSUE TITLE
There is not a find box on outline view

### ISSUE THREAD

**Issue by aGensinger** [microsoft/vscode#218657]
Type: <b>Bug</b>

issue: When click ctrl+F on outline view, there is not a find box on top of outline, but the find box in the source file edit view will be highlighted.

Version: 1.90.2 (user setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
gitlens|eam|15.1.0
msys2|fou|0.10.0
better-cpp-syntax|jef|1.17.2
git-graph|mhu|1.30.0
remote-containers|ms-|0.369.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Please use Ctrl+Alt+F.

See https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding for why this changed in 1.89.

**Comment by VickySekhon** [comment]
Yes, I believe Ctrl + Alt + F will be the fix you are looking for. This was a recent patch.

**Comment by aGensinger** [comment]
> Please use Ctrl+Alt+F.
> 
> See https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding for why this changed in 1.89.

Okay! you are right, thanks!
