### ISSUE TITLE
Text is bolded in markdown code blocks

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#218612]
We should ignore asterisks and such when we're inside a code block:

![image](https://github.com/user-attachments/assets/efab8124-0dc3-4866-aa39-e39328637c71)

**Comment by roblourens** [comment]
Nothing specific to chat here- is it the same in a normal markdown editor? Something with your font? I can't repro

**Comment by mjbvz** [comment]
It depends on the theme. For some themes this is what normal md files can look like too
