### ISSUE TITLE
FTP file gets deleted when drag and drop from file explorer

### ISSUE THREAD

**Issue by BrunnerLivio** [Microsoft/vscode#21868]
- VSCode Version: 1.10.1
- OS Version: Windows 10 Home 1607

Steps to Reproduce:

1. Open file explorer
2. Open any ftp folder 
![FTP File explorer](http://i.imgur.com/28etJqL.png)
3. Drag an drop any file from FIle Explorer into VSCode 
4. The dragged file gets removed from FTP folder, but it is not openend in VSCode

**Comment by bpasero** [comment]
@BrunnerLivio we never delete a file when importing via DND, the file must still be there. Can you double check?
