### ISSUE TITLE
Opening code files from ZIP files does not open the file

### ISSUE THREAD

**Issue by skest3qc** [Microsoft/vscode#21865]
- VSCode Version: 1.10.1
- OS Version: Windows 10 1607

Steps to Reproduce:

1. Open a zip file with f.e. cs files in it. *.cs file is set to open default with VS Code (URL:vscode)
2. Double clicking this file opens an empty instance op VS Code instead of opening the code file.

**Comment by joaomoreno** [comment]
Does it work when you configure it to open with another app? Notepad, for example.

What zip app do you have?

**Comment by skest3qc** [comment]
Yes it does work with default app as Notepad or Notepad++.
It does not work with 7zip and with Windows File Explorer.

**Comment by skest3qc** [comment]
Now i have switched back to VS code and it works now.
Type before was URL: code
now it is C# source file
