### ISSUE TITLE
Sticky Scroll font size issues when using Mouse Wheel Zoom

### ISSUE THREAD

**Issue by jolsen-mitsu** [microsoft/vscode#218667]
Type: <b>Bug</b>

This is when using the editor "sticky scroll" feature in VS Code and with the Mouse Wheel Zoom feature enabled.

If you scroll down enough that some sticky lines are present in the sticky area and then use ctrl+mousewheel to zoom the editor in or out, the font size of the text in the sticky areas gets out of sync with the font size of the rest of the text in the editor pane. If you then scroll up to the sticky lines, they are redrawn with the proper text size and maintain the proper size when scrolling back down (at least until using ctrl+mousewheel to zoom again).

This is only an issue when using the ctrl+mousewheel to zoom the editor. The ctrl+plus and ctrl+minus zoom for all of VS Code works properly. 

Thanks!

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|95.67GB (59.62GB free)|
|Process Argv|--crash-reporter-id e7f98140-221c-42ff-a3dd-68dcf6f443d9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu2004|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 0)|
|Memory (System)|46.89GB (41.36GB free)|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|8.4.0
separators|ale|2.6.1
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.4.3
vscode-streamdeck|nic|4.1.6
rewrap|stk|1.16.3
remove-empty-lines|use|1.0.1
vscode-color|ans|0.4.5
gitstash|art|5.2.0
launch-config|Art|0.8.4
atlascode|atl|3.0.10
openmatchingfiles|bca|0.5.4
replacerules|bhu|0.4.2
dbclient-jdbc|cwe|1.3.5
vscode-mysql-client2|cwe|7.5.1
gitlens|eam|15.1.0
todo-tree|Gru|0.0.226
vscode-edit-csv|jan|0.9.1
favorites|kdc|2.4.5
rainbow-csv|mec|3.12.0
render-crlf|med|1.8.1
git-graph|mhu|1.30.0
ecdc|mit|1.8.0
vscode-docker|ms-|1.29.1
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.7.11591012
isort|ms-|2023.10.1
mypy-type-checker|ms-|2023.9.11501016
pylint|ms-|2023.11.13481007
python|ms-|2024.9.2024062701
vscode-pylance|ms-|2024.6.102
datawrangler|ms-|1.4.0
powershell|ms-|2024.2.2
vsliveshare|ms-|1.0.5932
reload|nat|0.0.7
autodocstring|njp|0.6.1
csv-to-table|php|1.4.0
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
sonarlint-vscode|Son|4.6.0
code-spell-checker|str|3.0.1
selectline-statusbar|tom|0.0.2
vscode-json-stable-stringify|Tra|1.3.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
change-case|wma|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
legacy_priority:31082724

```

</details>

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. This should be fixed in recent insiders
