### ISSUE TITLE
Allow copy for "editor.dragAndDrop"

### ISSUE THREAD

**Issue by ffes** [Microsoft/vscode#21862]
- VSCode Version: 1.10.1
- OS Version: Win10

I enabled `editor.dragAndDrop` and it works as expected.

But I also expected Ctrl+DragAndDrop to copy the selection to the new location (without using the clipboard) instead of moving it.

If you implement this, please change the mouse cursor while dragging it, similar to Word.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

Allow to DragAndDrop content to another VSCode tab and to other programs. This is currently not possible. (Without having to click `Ctrl`)

By clicking `Ctrl` it would only copy within the same file, right?

**Comment by ffes** [comment]
Indeed a dup of #21145 

Apparently on a Mac you use the Alt-key when copying. On Windows it is the Ctrl-key.

**Comment by rebornix** [comment]
@Tekbr yes you'll have Ctrl on Windows.
