### ISSUE TITLE
object definition highlight bug

### ISSUE THREAD

**Issue by ki11en** [Microsoft/vscode#21871]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-icons|robertohuertasm|7.3.0|;

---

Steps to Reproduce:

1. Create *.js File
2. Create an object with number fields
3. Fields names like numbers will be not painted.

![image](https://cloud.githubusercontent.com/assets/10799208/23546633/940fc2cc-0011-11e7-967c-128493f42061.png)

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript-TmLanguage/issues/417
