### ISSUE TITLE
UX: unnecessary "Reload window?" prompt after extension update

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#21873]
I've got around 20 extensions installed and their updates are hence quite frequent. I often see this dialog:

![image](https://cloud.githubusercontent.com/assets/101152/23547302/f78a7306-0002-11e7-8a0a-26603a14a4fe.png)

I don't think it's useful as the operation is safe (especially with hot reload) and was explicitly invoked by me moments ago.

**Comment by sandy081** [comment]
Duplicates #18354
