### ISSUE TITLE
Inconsistent typescript type highlighting

### ISSUE THREAD

**Issue by anvish** [Microsoft/vscode#21872]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-file-peek|abierbaum|1.0.1|
|Bookmarks|alefragnani|0.11.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.7|
|tslint|eg2|0.8.1|
|auto-close-tag|formulahendry|0.3.9|
|auto-rename-tag|formulahendry|0.0.11|
|contextualduplicate|lafe|0.2.0|
|vscode-stylefmt|mrmlnc|2.2.2|
|debugger-for-chrome|msjsdiag|2.5.5|
|typescript-hero|rbbit|0.12.0|
|stylelint|shinnn|0.23.0|;

---

Steps to Reproduce:
```ts
function a(): { [key: string]: number } | { [key: string]: number } { throw 1 }

function b(a: { [key: string]: number } | { [key: string]: number }): void { }
```

![bug5](https://cloud.githubusercontent.com/assets/1114090/23547154/2dbeceda-0013-11e7-91ef-6a70c21695a5.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#427
