### ISSUE TITLE
md与http请求显示，会重叠。

### ISSUE THREAD

**Issue by acckcc** [Microsoft/vscode#21878]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|DfmPreview|928pjy|0.0.21|
|rest-client|humao|0.12.3|
|theme-material-theme|jprestidge|1.0.1|
|pandoc-format|monofon|0.0.2|
|cpptools|ms-vscode|0.10.2|;

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Can you please file this issue in english with reproducable steps.
Thank you

**Comment by ramya-rao-a** [comment]
Google translates that to 
"Md and http request display, will overlap"

@acckcc Can you provide screenshots, steps to reproduce and more details

**Comment by ramya-rao-a** [comment]
@acckcc 
Closing this issue as we haven't heard back from you in a while.
Feel free to re-open when you have more details to share
