### ISSUE TITLE
Error message when clicking on "Release Notes" button in update message.

### ISSUE THREAD

**Issue by BobbyBabes** [Microsoft/vscode#21875]
- VSCode Version:
```
Version 1.9.1
Commit f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
Date 2017-02-08T23:44:55.542Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```
- OS Version:
```
Linux designbox 4.9.11-1-ARCH #1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017 x86_64 GNU/Linux
```

This issue is back : https://github.com/Microsoft/vscode/issues/17455
Not exactly a showstopper.

Steps to Reproduce:

1. Start Visual Studio Code.
2. Wait for the info message "There is an available update" to appear.
3. Click the "Release Notes" button.
4. Error pops : ``Unable to open 'Release Notes: 1.10.1': Cannot read property 'replace' of null``

![vscode-update-message-cannot-read-property-bug-1](https://cloud.githubusercontent.com/assets/22870070/23547663/61658e0e-0004-11e7-8c73-4736c6967228.png)

![vscode-update-message-cannot-read-property-bug-2](https://cloud.githubusercontent.com/assets/22870070/23547675/6cca7390-0004-11e7-8a46-90496a7f2b6e.png)

**Comment by joaomoreno** [comment]
#21652
