### ISSUE TITLE
Fold/Unfold shortcuts like Ctrl+K Ctrl+1, Ctrl+K Ctrl+J do not work on Windows 10

### ISSUE THREAD

**Issue by jnachtigall** [Microsoft/vscode#21870]
- VSCode Version: 1.10.1
- OS Version: Windows 10

Steps to Reproduce:

* Manually `Fold Level 1` (or 2, 3, 4) from "Show and Run Commands" bar works, but all shortcuts `Ctrl+K` `Ctrl+1` (or `2`, `3`, `4`) does not work
* The shortcut `Ctrl+K` `Ctrl+J` (`Unfold all`) also does not work. Works only when calling manually from "Show and Run Commands" bar

I looked if there might be another program (closed almost everything) on Windows which might capture `Ctrl+K` globally, but could not find any. Also in the Extensions panel `Ctrl+K` `Ctrl+M` works ("Show recommended keymaps")

**Comment by jnachtigall** [comment]
After disabling all extensions and then enabling all extension again (so same extensions as before): It works. No idea why, maybe due to disabling/enabling some kind of vscode config was reset

**Comment by bobmagicii** [comment]
additionally, this can be caused by the new crappy nvidia geforce experience. just an fyi in case anybody ends up here again. disabling "share" (formerly called shadowplay) fixes it.
