### ISSUE TITLE
Improved support for remote node debugging

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2188]
- [x] win @SofianHn 
- [x] mac @joaomoreno  
- [x] linux @aeschli 

The followings fixes and features enable the VSCode node debugger to better support remote debugging (which includes debugging into a docker container).

* A remote debug session will no longer terminate after 3 seconds (a watchdog timer was tracking the **local** existence of the node process which does not really make sense in the remote case...)
* the `attach` launch config got the `address` attribute back. So it is again possible to specify a TCP/IP address. Please note that remote debugging is only supported on recent versions of node.
* the `attach` launch config now supports a `localRoot` and a `remoteRoot` attribute that can be used to map paths between a local VS Code project and a (remote) node folder. This works even locally on the same system or across different operating systems.

Verify that you can remote debug node apps. Here are some examples for what scenarios to test:
- debug a node app running inside a docker container (e.g. Windows -> Docker).
- debug a node app running inside a virtual machine (e.g. Mac -> Window, Mac -> Linux).
- debug a node app running locally from a different folder than the VS Code workspace.
- debug a node app running on a real remote system.

**Comment by SofianHn** [comment]
mac->windows
windows->mac
mac->docker
windows->docker

**Comment by aeschli** [comment]
Tested Linux -> Windows

**Comment by GeorgeHahn** [comment]
Has anyone tested Windows -> Linux?

I've been unable to get the remote to local mapping behavior to work such that I am shown writable files while debugging. I've tried a number of things based on what I've seen in the docs, issues, and the source. I think there may be a bug here, but I'm not positive enough to create an issue for it. I'll let you know if I find anything definite.
