### ISSUE TITLE
Unexpected shift key bubbling

### ISSUE THREAD

**Issue by otakustay** [Microsoft/vscode#21882]
- VSCode Version: 1.10.1
- OS Version: macOS Sierra

Steps to Reproduce:

1. Hold CMD
2. Hold SHIFT
3. Release CMD
4. Release SHIFT

In China many input methods use SHIFT key to switch between English and Chinese mode, however in vscode & macOS Sierra if we try "hold CMD -> hold SHIFT -> (press any other key) -> release CMD -> release SHIFT" system will detect a keypress event of SHIFT key and change the input mode, which is very annoying in coding job

I know this issue is related to webkit since google chrome has the exact same behavior, however vscode is deeply affected by it because there are many key combinations when coding, e.g. "CMD + SHIFT + LEFT" to select characters before cursor, this can randomly trigger the change of input mode, so is it possible this issue could be fixed in the scope of vscode?

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
