### ISSUE TITLE
Ctrl+C in Git Bash kills whole Integrated Terminal on Windows

### ISSUE THREAD

**Issue by jnachtigall** [Microsoft/vscode#21885]
- VSCode Version: 1.10.1
- OS Version: Windows 10

**Steps to Reproduce:**

1. Open integrated Terminal with Git Bash for Windows as described at https://code.visualstudio.com/docs/editor/integrated-terminal#_windows. Setting is `terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`
2. Ctrl+C at any time

**Expected Results:**
Kill/Empty current command

**Actual Results:**
Kills the terminal

See the screencast here: I just enter "ls " followed by Ctrl+C

![terminal-corrupt](https://cloud.githubusercontent.com/assets/3307404/23550043/53af6aea-000f-11e7-9008-5a9a985707a0.gif)

**Comment by Tyriar** [comment]
Do you have any errors on the dev tools console (Help > Toggle Developer Tools)?

**Comment by jnachtigall** [comment]
@Tyriar Nope, the Console prints no errors/warning related to the Integrated Terminal or Git bash. This is what it looks when "killing" the Terminal with `Ctrl+C`:

![2017-03-06 09_27_01-results js - gender-portal - visual studio code](https://cloud.githubusercontent.com/assets/3307404/23602126/1d99b018-024f-11e7-84cc-e24d60f9d9d7.png)

**Comment by jamiewinder** [comment]
I've just faced the same problem. Nothing is logged to the console when this occurs.

**Comment by jnachtigall** [comment]
If I press `Ctrl+D` then at least a quick `exit` is printed in the Terminal. For `Ctrl+C` there's just nothing like @jamiewinder said.

**Comment by jnachtigall** [comment]
@jamiewinder After upgrading Git Bash for Windows to the latest version, I do no longer have this problem. Closing as this does not seem to be a VSCode issue.

**Comment by Tyriar** [comment]
@jnachtigall good to know, thanks for follow up :smiley:

**Comment by IanOvenden** [comment]
I was also experiencing this issue on version 2.5.0.windows.2, updated to 2.12.2.windows.2 which appears to have resolved the issue.

It has led to me finding another issue around viewing a git log - when I exit out (ctrl+c) anything I type is invisible. Will log as separate issue.
