### ISSUE TITLE
reference number is missing from Source object

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#21887]
After we've moved the reference number from the path to a query parameter of the internal debug uri, it is no longer passed to the DAP in the Source objects.

**Comment by isidorn** [comment]
@weinand can you please let me know in what exact case is the source reference not passed to the DAP?
I tried setting a breakpoint in a internal module and the source reference of the source is correctly passed.

![screen shot 2017-03-03 at 17 49 04](https://cloud.githubusercontent.com/assets/1926584/23560142/b7b18648-0039-11e7-9fb1-a8b7785af3c0.png)

**Comment by weinand** [comment]
@isidorn yep, could be an issue on my side...

**Comment by weinand** [comment]
@isidorn  sorry, something was broken in my Insiders. Restarting fixed it.
