### ISSUE TITLE
Completion entries in package.json disappear when typing dot/period

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#21880]
- VSCode Version: 1.10.1
- OS Version: Windows 10 Pro

I was adding some `configurationDefaults` to my `package.json`. I typed `"editor"` as shown here and got completion for all the different options. However when I press the dot, all of the completion options vanish, despite the dot being the next character in the completion items.

![Completion items vanish when typing dot](https://cloud.githubusercontent.com/assets/1078012/23548769/0200e3b2-0001-11e7-808d-5d2c6c5af868.png)

![Dot typed; completion items gone](https://cloud.githubusercontent.com/assets/1078012/23548830/3ecf0c92-0001-11e7-8bb7-b919fd5104ab.png)

Pressing Ctrl+Space causes the list to reappear; but it seems like it shouldn't vanish (it doesn't when typing the other, non-dot characters).

**Comment by aeschli** [comment]
I'm not able to reproduce in the latest. Not sure there has been any changes though. Please reopen if you still see this and maybe paste your example file as well.
 
![json-codeassist](https://cloud.githubusercontent.com/assets/6461412/24791155/56478884-1b79-11e7-8695-e81111134dc5.gif)

**Comment by DanTup** [comment]
Sorry for the delay - I can't repro in 1.11 either :-)
