### ISSUE TITLE
Little debugger icons in source text

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#21881]
Not yet sure how that happened but  after some copy-pasting I have ended up with double breakpoints - in the gutter and in the source...

![mar-03-2017 12-08-04](https://cloud.githubusercontent.com/assets/1794099/23548950/2d7bacda-000a-11e7-8b5d-9abcecb41206.gif)

**Comment by isidorn** [comment]
I believe this is a dup of https://github.com/Microsoft/vscode/issues/21950 thus that the node2 debug adapter transfomrs regular breakpoints to column breakpoints and that for your debugging session you got automatically swithcted to using node2.

But let's wait for Rob to fix that issue and see if you still see this on your side

**Comment by isidorn** [comment]
Fixed via f6f74ea
