### ISSUE TITLE
Shortcut key is displayed incorrectly

### ISSUE THREAD

**Issue by m4kee** [Microsoft/vscode#21891]
- VSCode Version: **1.10.1** and 1.11.0
- OS Version: Linux 4.9.11-1-ARCH

Steps to Reproduce:

1. open toolbar > File or Edit or View
2. Shortcut key is displayed incorrectly for item "Open file" and "Close folder" and "Preference" and ...
![vscode-bug](https://cloud.githubusercontent.com/assets/18725631/23550571/f449c6d8-0011-11e7-9a9b-a7b86c771dab.png)

**Comment by bpasero** [comment]
I suspect the installed system font does not include the character we are using to display brackets: `〔` and `〕`

@Tyriar have you ever seen this on Linux?

**Comment by m4kee** [comment]
My font default in linux is Sans regular and in your comment this problem continues, my browser is chrome and firefox.

**Comment by bpasero** [comment]
Maybe @Tyriar has an idea if this is something Linux users should fix or if we should (on Linux) use a more generic ASCII character.

**Comment by m4kee** [comment]
Ok, and I opened the source to try and see what happens there and I discover that it is not the only character to have this problem, I can make a list if need.
With gedit all is well.

**Comment by Tyriar** [comment]
Works fine on Ubuntu:

![image](https://cloud.githubusercontent.com/assets/2193314/23560115/29979564-ffee-11e6-8707-e848b0894551.png)

@bpasero any reason `[` and `]` are not used?

**Comment by bpasero** [comment]
No, we just felt it looked nicer that way and less technical.

**Comment by Tyriar** [comment]
Yeah I'd go with () or [] for Linux, I guess Windows and macOS should be fine or we would have seen reports by now?

**Comment by bpasero** [comment]
Sounds good.

**Comment by bpasero** [comment]
I am now using "`(`" and "`)`" on all platforms (normal ASCII character).
