### ISSUE TITLE
Interactive Window (IW) shows scrollbar after closing Settings editor

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#218931]
Testing #217901 

On Windows:
1. Click on the IW gear icon. The Settings editor appears
2. Close the Settings editor
3. :bug: A scrollbar shows up on the IW input box

![Scrollbar on right of IW input box](https://github.com/user-attachments/assets/4dc250e4-7c4a-4689-96e2-19d6d6934df2)

**Comment by amunger** [comment]
settings gear is gone so hopefully this is resolved. (I don't think I ever saw it)
