### ISSUE TITLE
Why i cannot write anything on my terminal

### ISSUE THREAD

**Issue by mayishaamin** [microsoft/vscode#218923]
ADD ISSUE DESCRIPTION HERE

Version: 1.90.2
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
