### ISSUE TITLE
The path is not saved in a terminal

### ISSUE THREAD

**Issue by leekyrave** [microsoft/vscode#218935]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Open n-directory using "Open with code"
![image](https://github.com/microsoft/vscode/assets/61426541/e4f844ae-4e69-48be-a1e1-40268131a767)

2.  Create new terminal
![image](https://github.com/microsoft/vscode/assets/61426541/939d5d75-c559-404a-a4f4-bc80ab0d120c)

3. Open random directory, for example "frontend" 
![image](https://github.com/microsoft/vscode/assets/61426541/78f65252-6246-4542-b4cb-363fc8c717e9)

4. Close VS Code
5. Do the first step again, and it will not save entered path in the terminal
![image](https://github.com/microsoft/vscode/assets/61426541/a8d6ae01-17c5-45f7-a59d-8bef5814eb9b)

The essence of the bug is that the path in the terminal is not saved after a restart.
I think that it should be saved, because when working in one window with several projects, this is required, for example, to launch different applications.
That is, so that the entered path is saved for each individual terminal.

**Comment by meganrogge** [comment]
this works for me. it looks like you don't have shell integration `terminal.shellIntegration.enabled` which is required for this.
