### ISSUE TITLE
Updating VS Code - not working on macOS Sierra

### ISSUE THREAD

**Issue by Marshevskyy** [Microsoft/vscode#21897]
- VSCode Version: 1.9.1 (1.9.1)
- OS Version: macOS Sierra

Steps to Reproduce:

1. get popup "An update is ready to install" (you can get it by clicking Code -> check for updates) (see screenshot 1 below)
2. click on Add Halper
3. as result I got notification like (see screenshot 2 below)
4. once I click on "Update Now" or Code -> Restart To Update... button (see screenshot 3 below), it just close VS Code, instead of restart it with latest updates
5. then I have to manually open VS Code, and getting popup as in step 1. then this workflow is repeating.

screenshot 1 <img width="1177" alt="screenshot 2017-03-03 16 12 04" src="https://cloud.githubusercontent.com/assets/6871431/23554389/7c19ecf8-002d-11e7-815d-9000cd25ead1.png">
screenshot 2 <img width="1135" alt="screenshot 2017-03-03 16 13 37" src="https://cloud.githubusercontent.com/assets/6871431/23554390/7c2337f4-002d-11e7-9aa5-4ebba237d8b4.png">
screenshot 3 <img width="376" alt="screenshot 2017-03-03 16 19 14" src="https://cloud.githubusercontent.com/assets/6871431/23554388/7c192714-002d-11e7-8750-b24d37d15272.png">

**Comment by joaomoreno** [comment]
#7426
