### ISSUE TITLE
Show a back/forward button prominently in a toolbar

### ISSUE THREAD

**Issue by arunkalesh** [Microsoft/vscode#21890]
- VSCode Version: 1.10.1
- OS Version:Windows 10 

Steps to Reproduce:

1. Presently we use, ctrl + T , and search bar but back button will be much better from user point of view.

**Comment by bpasero** [comment]
@arunkalesh what back button are you talking about? and what desired page?

**Comment by arunkalesh** [comment]
In Visual Studio at the top left we have a Back and forward button to easily access the files opened previously and  also contains a list of file that were opened. But in VS code we do not have that functionality and due to which it becomes complex to get the previously opened files except searching in tabs opened and doing a ctrl + T or a search.

**Comment by bpasero** [comment]
@arunkalesh what about this:

![image](https://cloud.githubusercontent.com/assets/900690/23563167/cdb4078e-0045-11e7-8577-40befaa5efa3.png)

**Comment by arunkalesh** [comment]
I agree and that is extremely great. But after using Visual Studio, and coming to VS Code having a back button at the top without going in any of the option will be much better.

**Comment by novikov-alexander** [comment]
It would be great if it is also possible to use "back" button on a mouse.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by arunkalesh** [comment]
Hope it will be in the 2019 road map.

**Comment by bpasero** [comment]
@arunkalesh did you know that you can use mouse buttons 4 and 5 for navigating back and forward?

**Comment by arunkalesh** [comment]
yes.
