### ISSUE TITLE
CentOS: window.newWindowDimensions does not properly inherit the existing window

### ISSUE THREAD

**Issue by bsharrow** [Microsoft/vscode#21896]
- VSCode Version: 1.10.1
- OS Version: CentOS 7.3.1611

Steps to Reproduce:

1. Open "User Settings" and confirm `"window.newWindowDimensions": "inherit"` is set.
2. In a non-maximized, non-fullscreen window, open a new window with `Ctrl+Shift+N`.
3. The new window is maximized and does not inherit the previous window dimensions.

Developer Tools output provides no error response in the console.

Additional info:

- The window setting worked as expected in 1.9.1 release.
- I had installed the previous version (1.9.1) via RPM download and upgraded to 1.10.1 via the new CentOS Yum repository. 
- GNOME is the active window manager.

**Comment by bpasero** [comment]
Since I cannot reproduce on my Ubuntu Linux I suspect this is either a problem with CentOS or a software that is running that hijacks the window dimensions to always be maximized.

**Comment by bsharrow** [comment]
After a routine restart of my CentOS machine, the property in question is working as intended.  I am not sure if the Yum upgrade process from 1.9.1 to 1.10.1 was part of the issue or not; surface-level look at a few OS logs don't provide anything of note.  Closing issue.
