### ISSUE TITLE
JavaScript IntelliSense Problem

### ISSUE THREAD

**Issue by amkgo** [Microsoft/vscode#2189]
Windows 7 / VS Code 0.10.6

A simple JavaScript project folder with two files:  

`crt.js` file is used as the source of intellisense function.
```
var foo = {};
foo.Version = '1.0';

var bar = {
  Version: '1.0';
}
```

`main.js` file use the variables defined in `crt.js` file:
```
foo.(no suggestion shows here)
bar.(shows Version as suggestion)
```
Can we have the foo show suggestions as bar?

Andrew

**Comment by Nimzozo** [comment]
:+1:

**Comment by jrieken** [comment]
As we now ship with project Salsa this should work
