### ISSUE TITLE
Code Helper and 100% cpu usage - macOS

### ISSUE THREAD

**Issue by hinok** [Microsoft/vscode#21895]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-class-suggestions|AndersEAndersen|1.0.3|
|EditorConfig|EditorConfig|0.4.0|
|beautify|HookyQR|0.8.8|
|vscode-smart-split-into-lines|JulioGold|0.0.1|
|ejs-language-support|QassimFarid|0.0.1|
|vscode-caniuse|agauniyal|0.5.0|
|Bookmarks|alefragnani|0.11.0|
|alignment|annsk|0.3.0|
|htmltagwrap|bradgashler|0.0.3|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-css-modules|clinyong|0.2.0|
|gitignore|codezombiech|0.5.0|
|vscode-svgviewer|cssho|1.3.1|
|vscode-eslint|dbaeumer|1.2.7|
|githistory|donjayamanne|0.1.5|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-npm-script|eg2|0.1.8|
|LogFileHighlighter|emilast|1.1.1|
|vscode-npm|fknop|3.3.0|
|auto-close-tag|formulahendry|0.3.9|
|auto-rename-tag|formulahendry|0.0.11|
|search-node-modules|jasonnutter|1.0.2|
|vscode-random|jrebocho|1.3.0|
|vscode-colorize|kamikillerto|0.3.2|
|contextualduplicate|lafe|0.2.0|
|node-module-intellisense|leizongmin|1.3.0|
|bem-expand|lukazakrajsek|0.1.1|
|vscode-csscomb|mrmlnc|4.0.1|
|vscode-duplicate|mrmlnc|1.1.0|
|vscode-scss|mrmlnc|0.6.1|
|vscode-icons|robertohuertasm|7.3.0|
|stylelint|shinnn|0.23.0|
|open-in-browser|techer|0.0.3|
|babelrc|waderyan|1.0.0|
|gitblame|waderyan|1.3.0|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:

1. Open file with svg code
2. `Code Helper` processes should use 100% cpu.

---

![zrzut ekranu 2017-03-03 o 15 00 14](https://cloud.githubusercontent.com/assets/1313605/23553681/2e66df3a-0022-11e7-824f-274f5a7e4777.png)

**Comment by hinok** [comment]
I'm not sure if it helps but this problem shows up when I'm building a react component with svg code. Here are my settings

```
{
    "caniuse.browser_scope": ">= 1%, last 2 versions",
    "editor.dragAndDrop": true,
    "editor.fontFamily": "'Source Code Pro', Menlo, Monaco, 'Courier New', monospace",
    "editor.fontSize": 14,
    "editor.minimap.enabled": true,
    "editor.minimap.renderCharacters": false,
    "editor.renderIndentGuides": true,
    "editor.rulers": [100],
    "editor.wordWrap": "off",
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "window.zoomLevel": 0,
    "auto-close-tag.activationOnLanguage": [
        "html",
        "xml",
        "php",
        "javascript"
    ],
    "vsicons.projectDetection.autoReload": true,
    "terminal.external.osxExec": "iTerm.app",
    "files.associations": {
        "*.js": "javascriptreact"
    },
    "scss.showErrors": true,
    "workbench.statusBar.visible": true,
    "workbench.activityBar.visible": true,
    "workbench.iconTheme": "vscode-icons"
}
```

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by hinok** [comment]
@bpasero So weird, I cannot reproduce it even without enabled extensions. I think that very specific portion of code that I've had, has caused this bug. If I experience this issue in the future, I will reopen this issue. For now I think it's ok to close it.

**Comment by jasonslyvia** [comment]
I'm experiencing this issue right now.

- VSCode: Version 1.14.2 (1.14.2)
- OSX: 10.11.5 (15F34)

![image](https://user-images.githubusercontent.com/1336484/29138115-34b93984-7d75-11e7-8a28-1d0f190eb263.png)

After disabling all extensions, nothing changes much. I doubt it's related to a TypeScript project I'm watching using iTerm.

**Comment by purge** [comment]
I am also experiencing this every time I try and edit an SVG file
