### ISSUE TITLE
Long strings not highlighted correctly in Javascript

### ISSUE THREAD

**Issue by rcwwilliams** [microsoft/vscode#219057]
Type: <b>Bug</b>

When creating a string of more than 2485 characters, in a Javascript source file, it is not highlighted correctly and shows in a different colour.

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:33:48.698Z)
OS version: Linux x64 6.8.0-35-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700 (20 x 4108)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.09GB (17.16GB free)|
|Process Argv|--no-sandbox --crash-reporter-id f78647a4-f9a2-4314-893f-0be24897be66|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
legacy_priority:31082724

```

</details>

**Comment by RedCMD** [comment]
can you send a code snippet a screenshot please

**Comment by rcwwilliams** [comment]
Here are the screenshots as requested:

This is a string shorter than 2485 which shows the string color I specified in my settings.json:
![Screenshot from 2024-06-28 07-56-18](https://github.com/microsoft/vscode/assets/8653462/3a66b994-ae55-4177-9077-084bf15b6815)

This is a string longer than 2485 which does not show the correct color :
![Screenshot from 2024-06-28 07-55-42](https://github.com/microsoft/vscode/assets/8653462/aace2ecd-6782-4c70-bf48-9a33e15162e2)

Hope that helps.

**Comment by RedCMD** [comment]
by default JavaScript limits line tokenization to 2500 for performance reasons
https://github.com/microsoft/vscode/blob/aea213b7fcc7de5c24ad797ac1af209b159d451f/extensions/javascript/package.json#L15

you can increase the max line length via the setting `editor.maxTokenizationLineLength`
```json
"[javascript]": {
    "editor.maxTokenizationLineLength": 10000
}
```

**Comment by rcwwilliams** [comment]
Brilliant - thanks very much - greatly appreciated

**Comment by rcwwilliams** [comment]
Brilliant - thanks very much - greatly appreciated
