### ISSUE TITLE
C++ syntax highlighting not working properly when constructor initializer list has multiple lines

### ISSUE THREAD

**Issue by veerajskhokale** [Microsoft/vscode#21904]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:47:58.633Z)
- OS Version: Linux x64 4.4.0-64-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.5|
|vscode-clang|mitaki28|0.2.1|
|cpptools|ms-vscode|0.10.2|
|vscode-icons|robertohuertasm|7.3.0|
|Material-theme|zhuangtongfa|2.1.3|;

---

Steps to Reproduce:

Syntax highlighting for keywords like noexcept and delete is not working as shown in the screenshot with the following code:

#include <iostream>

class Myclass
{
public:
    Myclass()
        : x(), y(),
        z()
    {
    }

    Myclass(const Myclass&) noexcept = delete;
    void print() { std::cout << 1 << std::endl; }

private:
    int x;
    int y;
    int z;
};

1. It is observed that this issue occurs when the constructor initializer list is spread over more than a line.
2. Issue exists for all themes and when all extensions are disabled as well
3. Code works and tested with g++
![screenshot at 2017-03-03 21 16 41](https://cloud.githubusercontent.com/assets/20010212/23557662/be9ca3e4-0056-11e7-9c5f-24baf41e1ec4.png)

**Comment by isidorn** [comment]
Can you please file this against the C++ extension here https://github.com/Microsoft/vscode-cpptools
Thank you
