### ISSUE TITLE
"paused on debugger statement" instead of exception in the inspector

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#21905]
- VSCode Version: 1.10.1
- OS Version: W10x64
- Node: 6.9.3

Launch config regarding console: 
```
"internalConsoleOptions": "neverOpen"
"console": "externalTerminal"
```

A simple case of trying to access property of ``undfined``:
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2017-03/Code_2017-03-03_16-54-35.png)

Error still passed to debug console:
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2017-03/Code_2017-03-03_17-11-42.png)

Shouldn't debugger just show the exception in the inspector on the left in the first place? In my case it just shows the normal local scope, as if it were a breakpoint stop

If I unwrap the lines, it shows that the break happens (at least visibly) one the line prior the one containing the problem:
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2017-03/Code_2017-03-03_17-13-39.png)
Regarding "debugger statement" - isn't it too vague?

If I step forward it gets thrown into the external console also, which is probably a correct behavior.
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2017-03/cmd_2017-03-03_17-17-57.png)

I don't know... some of it may be different issues, some are not even bugs (maybe I'm just used to node2 debugger). Also, it is probably related to #19750

thanx

**Comment by isidorn** [comment]
@Spown what debugger are you using. node or node2?

**Comment by Spown** [comment]
it looks the same in both node with "protocol": "inspector" and node2

**Comment by roblourens** [comment]
I see the problem, I thought that this was handled through the same path as an exception, but apparently not. Maybe it was in an earlier version of Node.
