### ISSUE TITLE
Code - OSS dev does not start when I run npm run watch

### ISSUE THREAD

**Issue by DAlperin** [Microsoft/vscode#21906]
- VSCode Version: code-oss-dev: 1.11.0
- OS Version: Mac Os 10.12.3 (16D32)

Steps to Reproduce:

1. I forked the repo then followed the steps in the wiki [here](https://github.com/Microsoft/vscode/wiki/How-to-Contribute) And it worked. it launched when I ran npm run watch
2. I then saw their where changes so I ran ran git pull https://github.com/Microsoft/vscode.git master everything went fine I reinstalled and then ran npm run watch it ends with 
`[10:29:55] Finished compilation with 0 errors after 77029 ms`
`[10:30:00] [monaco.d.ts] Starting monaco.d.ts generation`
`[10:30:02] [monaco.d.ts] Finished monaco.d.ts generation`
But it does not launch. It hangs. I have had this running for 30 minutes. 

I am new to the code so if I am missing something simple Im sorry I am used to writing node.js backend in a team of 3.

**Comment by isidorn** [comment]
You should simply call the `scripts/code.sh` command in parallel  once the build command is finished.

This should be documented here https://github.com/Microsoft/vscode/wiki/How-to-Contribute#validate-your-changes

**Comment by DAlperin** [comment]
Oh I feel stupid. Thanks
