### ISSUE TITLE
There are two search icon in activity bar

### ISSUE THREAD

**Issue by ZCShou** [microsoft/vscode#219046]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.0-insider (system setup)
- OS Version: Windows_NT x64 10.0.22635

Steps to Reproduce:

1.  open vscode but do not open any folder
![image](https://github.com/microsoft/vscode/assets/8591065/ba15612e-54b4-4487-a0b8-92d6c6c64dd8)

2. the one of search icon will disappear if open a folder. But the shortcut will be incorrect
![image](https://github.com/microsoft/vscode/assets/8591065/e0c1450c-58de-44d1-9b69-f4e2e0074834)

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by gjsjohnmurray** [comment]
I assume the "Makefile", "Bitbake" etc entries on the context menu in your earlier screenshot no longer appear. What does it now look like?

Do both magnifier buttons in Activity Bar produce the same content in the Sidebar (the SEARCH view, I assume)?

**Comment by ZCShou** [comment]
> I assume the "Makefile", "Bitbake" etc entries on the context menu in your earlier screenshot no longer appear. What does it now look like?

I do not disable all extensions in the first screenshot.  so there are Makefile, Bitbake etc on the context menu. After you reply me, I disable all extensions, but the situation remains the same

> Do both magnifier buttons in Activity Bar produce the same content in the Sidebar (the SEARCH view, I assume)?

One of Search Icon's view is empty, and the other is ok. Please watch the video below, thanks.


https://github.com/microsoft/vscode/assets/8591065/2f3e5618-d020-4019-99dd-dcc461300647

**Comment by andreamah** [comment]
You can fix this by running `View: Reset View Locations`. Does that help?

**Comment by ZCShou** [comment]
> You can fix this by running `View: Reset View Locations`. Does that help?

It's useful. Thank you very much!
