### ISSUE TITLE
Installation: No executable and windows.h not found error

### ISSUE THREAD

**Issue by zippoxer** [Microsoft/vscode#2190]
I'm using Ubuntu, nvm and node 5.3.0. I followed the build instructions carefully and after executing `npm.sh install`, I successfully built and ran VSCode via `scripts/code.sh`. The problem is that this script is meant for development mode, and I'd like to run VSCode in production mode.

I don't find any executable named `Code` anywhere in node's bin or VSCode's source directory.

Also, during the installation procedure the `windows-mutex` package attempts to install and of course fails (I'm on Ubuntu):

```
  CXX(target) Release/obj.target/CreateMutex/src/main.o
../src/main.cc:2:21: fatal error: windows.h: No such file or directory
 #include <windows.h>
                     ^
compilation terminated.
CreateMutex.target.mk:91: recipe for target 'Release/obj.target/CreateMutex/src/main.o' failed
```

Why can't I see VSCode's executable? Could this error be part of the problem?

**Comment by joaomoreno** [comment]
`windows-mutex` is listed as an optional dependency. This means `npm` will attempt to install it and proceed even if it fails. Not a problem.

If you want to build a production version of code you can run `gulp vscode-linux-ia32` or `gulp vscode-linux-x64`, depending on your architecture. This will create a `VSCode-Linux` folder next to the repo folder.

**Comment by joaomoreno** [comment]
The installation of `windows-mutex` will fail but `npm` itself will succeed. It will just spit out this message:

```
-npm WARN optional dep failed, continuing windows-mutex@0.2.0
```

If your build is failing there is something else happening, maybe you can send me the log?

**Comment by Tyriar** [comment]
[There was something else happening](https://github.com/Microsoft/vscode/issues/2474), I guess the error only shows when something else fails? Not ideal but I guess that's alright, it was a bit misleading is all.

**Comment by joaomoreno** [comment]
True that!
