### ISSUE TITLE
Code Lenses Overlapping When File Content Resets

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#219097]
This happened briefly (for about 1-2 seconds) after changing profiles from my default profile to the empty profile. Maybe when the text model changes in some unexpected way?
"references" should not be shown in json files.

![Image](https://github.com/user-attachments/assets/17c320fa-01d0-4f08-825a-da98f3a2ab6c)

Unfortunately I did not manage to reproduce this issue, so feel free to close if this issue is unactionable.

**Comment by jrieken** [comment]
Likely an extension issue, amplified by the EH start. When the model changes (which I assume) we ask for new lenses, existing lenses continue to follow their respective decoration, and once new lenses/lens-positions are return we update existing lenses. 

@hediet did settings.json change from long to short/empty? do you normally have lenses in that file?

**Comment by hediet** [comment]
> did settings.json change from long to short/empty?

I doubt that this file changed from long to short, as it is the settings file from the empty profile, which should not change when changing the current profile.
Also, the code lenses read "references", which I think is the typescript code lens for the file "extHostExtensionService".

> Likely an extension issue, amplified by the EH start.

Could very well be.
