### ISSUE TITLE
warnning: last 5 minutes, Typescript language service accidentally suspended 5 times. [report problem]

### ISSUE THREAD

**Issue by junhwong** [Microsoft/vscode#21903]
That problems tip box flashes, cannot close it.

- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-svgviewer|cssho|1.3.1|
|python|donjayamanne|0.5.8|
|vscode-rust|kalitaalexey|0.3.10|
|Go|lukehoban|0.6.54|
|vscode-docker|PeterJausovec|0.0.12|
|RustyCode|saviorisdead|0.19.1|;

---

Steps to Reproduce:

1. Nothing to do, just open .ts files.
2.

**Comment by mjbvz** [comment]
Do you see a message about a missing `typescript/...` file? If so, you may be hitting #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds


If this does not sound correct, please set `"typescript.tsserver.trace": "verbose"` in your user settings, restart VSCode and reproduce the issue, and then share the `TypeScript` output in the output panel

**Comment by junhwong** [comment]
@mjbvz Thank you for your reply, it is the cause of that.  But :
> That problems tip box flashes, cannot close it.

that tips always flashes, should be regarded as BUG, I think every time you open (vscode or .ts files ) prompt once enough.

**Comment by mjbvz** [comment]
@junhwong Thanks. I've already checked a fix in for the alert box flashing

**Comment by junhwong** [comment]
@mjbvz Got it, nice work!
