### ISSUE TITLE
Directory context menu entry confusingly calls Visual Studio Code by the name "Code - OSS"

### ISSUE THREAD

**Issue by sandersaares** [Microsoft/vscode#21901]
VSCode Version:
Version 1.10.1
Commit 653f8733dd5a5c43d66d7168b4701f94d72b62e5
Date 2017-03-02T00:33:15.706Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
OS Version: Windows 10 (14393.693)

![image](https://cloud.githubusercontent.com/assets/9914262/23556223/81eec03e-0034-11e7-9528-e788cbff02d2.png)

Steps to Reproduce:

1. Right click on folder.
2. Observe menu entry for opening the directory with VS Code.

The editor I use is Visual Studio Code. I have no idea what this OSS means. The context menu entry confuses me. After the latest update that introduced this, I am no longer confident it opens my stuff in the right "mode" or whether I should use another way of opening my stuff.

**Comment by Tekbr** [comment]
Fixed in #21659 .

**Comment by sandersaares** [comment]
Great. Closing as duplicate in that case!
