### ISSUE TITLE
VSCode repeatedly prompts me to update despite having the latest version

### ISSUE THREAD

**Issue by demeralde** [microsoft/vscode#219068]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.90.1 (Universal)
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:02:41.372Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

Steps to Reproduce:

1. Open VSCode
2. Manually check for updates (or wait for it to periodically do this)
3. It should say you need to update to the latest version (i.e the one I already have)
4. Install the update
5. Restart VSCode. Repeat steps 1-4 and it should do the exact same thing. No matter how many times I do it, it still tells me I need to update

This only started happening recently. I haven't made any significant (or probably any) changes to VSCode in several months and it never used to do this. It only started happening recently, and needless to say it's annoying AF to have the popup notification show all the time.

I don't have many extensions installed so I doubt that's the problem too. But here's the full list so you can reproduce my environment:

```
anseki.vscode-color@0.4.5
apollographql.vscode-apollo@1.20.0
bradlc.vscode-tailwindcss@0.12.2
dbaeumer.vscode-eslint@3.0.10
eamodio.gitlens@15.1.0
editorconfig.editorconfig@0.16.4
esbenp.prettier-vscode@10.4.0
expo.vscode-expo-tools@1.5.0
github.copilot@1.208.0
github.copilot-chat@0.16.1
github.github-vscode-theme@6.3.4
github.vscode-github-actions@0.26.3
github.vscode-pull-request-github@0.90.0
golang.go@0.41.4
graphql.vscode-graphql@0.11.0
graphql.vscode-graphql-syntax@1.3.6
kaleidoscope-app.vscode-ksdiff@1.0.2
kisstkondoros.vscode-gutter-preview@0.31.2
mikestead.dotenv@1.0.1
monokai.theme-monokai-pro-vscode@1.3.2
ms-azuretools.vscode-docker@1.29.1
ms-python.debugpy@2024.6.0
ms-python.isort@2023.10.1
ms-python.python@2024.8.1
ms-python.vscode-pylance@2024.6.1
ms-vscode-remote.remote-containers@0.369.0
redhat.vscode-xml@0.27.1
ricard.postcss@2.0.0
sdras.night-owl@2.0.1
shd101wyy.markdown-preview-enhanced@0.8.13
simonsiefke.svg-preview@2.8.3
vscodevim.vim@1.27.3
yoavbls.pretty-ts-errors@0.5.4
yzhang.markdown-all-in-one@3.6.2
```

**Comment by demeralde** [comment]
@gjsjohnmurray what am I supposed to do about this, though? I don't want to have to reinstall VSCode and all my extensions again.

**Comment by demeralde** [comment]
Still having this issue even after this long, it's been really annoying.

**Comment by rzhao271** [comment]
After installing the update, there is a restart to update option, and you need to wait for the editor to close and restart itself after pressing it. I believe another approach is to manually install a newer version of VS Code, which keeps the extension and settings data.

Are you still seeing the issue after these steps?
