### ISSUE TITLE
Slow start-up

### ISSUE THREAD

**Issue by George-Gi** [microsoft/vscode#219062]
Hi, since yesterday my VSCode takes too much time to start-up. Here is the result of profiling it

## System Info

* Code: 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb)
* OS: win32(10.0.19045)
* CPUs: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz(16 x 2400)
* Memory(System): 31.76 GB(7.91GB free)
* Memory(Process): 245.33 MB working set(176.61MB private, 0.20MB shared)
* VM(likelihood): 50%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                       |
| --------------------------------------------------------------- | -------- | ------------------------- | ---------------------------------------------------------- |
| start => app.isReady                                            | 10126    | [main]                    | initial startup: true                                      |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                      |
| require(main.bundle.js)                                         | 62       | [main]                    | initial startup: true                                      |
| start crash reporter                                            | 10052    | [main]                    | initial startup: true                                      |
| serve main IPC handle                                           | 2        | [main]                    | initial startup: true                                      |
| create window                                                   | 68       | [main]                    | initial startup: true, state: 0ms, widget: 34ms, show: 0ms |
| app.isReady => window.loadUrl()                                 | 175      | [main]                    | initial startup: true                                      |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 29733    | [main->renderer]          | NewWindow                                                  |
| require(workbench.desktop.main.js)                              | 237      | [renderer]                | cached data: YES, node_modules took 0ms                    |
| wait for window config                                          | 1        | [renderer]                | -                                                          |
| init storage (global & workspace)                               | 21       | [renderer]                | -                                                          |
| init workspace service                                          | 27       | [renderer]                | -                                                          |
| register extensions & spawn extension host                      | 416      | [renderer]                | -                                                          |
| restore viewlet                                                 | 0        | [renderer]                | -                                                          |
| restore panel                                                   | 0        | [renderer]                | -                                                          |
| restore & resolve visible editors                               | 264      | [renderer]                | 0:                                                         |
| create workbench contributions                                  | 20       | [renderer]                | 66 blocking startup                                        |
| overall workbench load                                          | 420      | [renderer]                | -                                                          |
| workbench ready                                                 | 40724    | [main->renderer]          | -                                                          |
| renderer ready                                                  | 692      | [renderer]                | -                                                          |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                          |
| extensions registered                                           | 40962    | [renderer]                | -                                                          |

## Extension Activation Stats

| Extension                           | Eager | Load Code | Call Activate | Finish Activate | Event                          | By                                  |
| ----------------------------------- | ----- | --------- | ------------- | --------------- | ------------------------------ | ----------------------------------- |
| vscode.git-base                     | true  | 2         | 0             | 0               | *                              | vscode.git-base                     |
| vscode.github                       | true  | 6         | 1             | 1               | *                              | vscode.github                       |
| arturock.gitstash                   | true  | 4         | 2             | 0               | *                              | arturock.gitstash                   |
| hbenl.vscode-test-explorer          | true  | 23        | 3             | 0               | *                              | hbenl.vscode-test-explorer          |
| ms-vscode.test-adapter-converter    | true  | 4         | 0             | 0               | *                              | hbenl.vscode-test-explorer          |
| vscode.debug-auto-launch            | false | 3         | 0             | 0               | onStartupFinished              | vscode.debug-auto-launch            |
| vscode.emmet                        | false | 5         | 8             | 0               | onLanguage                     | vscode.emmet                        |
| vscode.extension-editing            | false | 4         | 0             | 0               | onLanguage:markdown            | vscode.extension-editing            |
| vscode.github-authentication        | false | 11        | 1             | 2               | onAuthenticationRequest:github | vscode.github-authentication        |
| vscode.json-language-features       | false | 14        | 0             | 10409           | onLanguage:jsonc               | vscode.json-language-features       |
| vscode.markdown-language-features   | false | 32        | 3             | 20530           | onLanguage:markdown            | vscode.markdown-language-features   |
| vscode.markdown-math                | false | 7         | 0             | 0               | api                            | vscode.markdown-language-features   |
| vscode.merge-conflict               | false | 8         | 2             | 2               | onStartupFinished              | vscode.merge-conflict               |
| vscode.typescript-language-features | false | 19        | 2             | 4               | onLanguage:jsonc               | vscode.typescript-language-features |
| alefragnani.project-manager         | false | 5         | 3             | 3               | onStartupFinished              | alefragnani.project-manager         |
| eamodio.gitlens                     | false | 50        | 24            | 18              | onStartupFinished              | eamodio.gitlens                     |
| esbenp.prettier-vscode              | false | 65        | 19            | 0               | onStartupFinished              | esbenp.prettier-vscode              |
| jebbs.plantuml                      | false | 343       | 2             | 0               | api                            | vscode.markdown-language-features   |
| ms-vscode-remote.remote-wsl         | false | 17        | 46            | 6               | onStartupFinished              | ms-vscode-remote.remote-wsl         |
| vscode-icons-team.vscode-icons      | false | 21        | 2             | 817             | onStartupFinished              | vscode-icons-team.vscode-icons      |

## Terminal Stats

| Name                                    | Timestamp     | Delta | Total |
| --------------------------------------- | ------------- | ----- | ----- |
| code/terminal/willGetTerminalBackend    | 1719557090863 | 0     | 0     |
| code/terminal/didGetTerminalBackend     | 1719557090863 | 0     | 0     |
| code/terminal/willReconnect             | 1719557090863 | 0     | 0     |
| code/terminal/willGetTerminalLayoutInfo | 1719557090863 | 0     | 0     |
| code/terminal/didGetTerminalLayoutInfo  | 1719557090864 | 1     | 1     |
| code/terminal/didReconnect              | 1719557090864 | 0     | 1     |
| code/terminal/willReplay                | 1719557090864 | 0     | 1     |
| code/terminal/didReplay                 | 1719557090864 | 0     | 1     |
| code/terminal/willGetPerformanceMarks   | 1719557090864 | 0     | 1     |
| code/terminal/didGetPerformanceMarks    | 1719557090865 | 1     | 2     |

## Workbench Contributions Blocking Restore

* Total (LifecyclePhase.Starting): 33 (11ms)
* Total (LifecyclePhase.Ready): 36 (8ms)

**Comment by bpasero** [comment]
A lot of time spend in non-vscode things, e.g. `start => app.isReady` or `window.loadUrl() => begin to require(workbench.desktop.main.js)`

**Comment by George-Gi** [comment]
I am not sure what happened, but after a couple of days and resets the problem is fixed. Probably some Windows update.
