### ISSUE TITLE
Strict Pair When typing prefix of code snippets

### ISSUE THREAD

**Issue by HiNeal** [microsoft/vscode#219055]
I’ve created some snippets, but I find that when I type ‘oynote’, even some unrelated options appear. Is there any way to only show results with consecutive strings? If it can strictly match my input and then retrieve from the snippets, that would be even better, I would be very grateful ! 

<img width="384" alt="image" src="https://github.com/microsoft/vscode/assets/64223900/457fd4d4-3cf1-411d-9086-f89509d3cb03">

**Comment by jrieken** [comment]
No, the design to show all matching suggestions/snippets but sort them by match-quality and select the best (as it did in this case)
