### ISSUE TITLE
TypeScript - Loading IntelliSense status

### ISSUE THREAD

**Issue by its-dev-yogesh** [microsoft/vscode#219059]
Type: <b>Performance Issue</b>

This issue occurs when i need suggestions in Next Js. Whenever i press ^cmd in mac it just shows loading and at the status bar it shows Loading IntelliSense status and keep processing

VS Code version: Code 1.90.2 (Universal) (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:37:41.291Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id c76c0e22-c7d4-4840-a827-dc30a9c64b42|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   156	 21725	code main
    2	    74	 21733	   gpu-process
    0	    33	 21734	   utility-network-service
    0	    74	 21750	shared-process
    0	     0	 25298	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    49	 21767	ptyHost
    0	     0	 24519	     /bin/zsh -il
    0	    41	 24776	       npm run dev
    0	    41	 24787	         node /Users/yogesh/Documents/Projects/sms/node_modules/.bin/next dev
    0	    74	 24788	           next-server (v14.2.4)
    1	   352	 24514	window [5] (AuthLoginForm.tsx — sms)
    0	    66	 24515	fileWatcher [5]
    0	   147	 24516	extensionHost [5]
    0	    66	 24537	     electron-nodejs (tailwindServer.js )
    0	    57	 24539	     electron-nodejs (index.js )
    0	    90	 24543	     /private/var/folders/vx/11fhvtdx38s98cj6d47l986m0000gn/T/AppTranslocation/41163637-3C04-4837-8ACE-AFE924AAAA34/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /private/var/folders/vx/11fhvtdx38s98cj6d47l986m0000gn/T/AppTranslocation/41163637-3C04-4837-8ACE-AFE924AAAA34/d/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=24516
    0	    82	 25237	     electron-nodejs (tsserver.js )
   99	   246	 25238	     electron-nodejs (tsserver.js )
    0	    57	 25240	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    98	 25291	window [6] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (AuthLoginForm.tsx — sms)
|    Folder (sms): 307 files
|      File types: tsx(156) json(16) js(8) gz(5) svg(3) gitignore(2) ts(2)
|                  mjs(2) eslintignore(1) sh(1)
|      Conf files: package.json(3) settings.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-tailwindcss|bra|0.12.2
turbo-console-log|Cha|2.10.4
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.1.0
prettier-vscode|esb|10.4.0
vscode-typescript-next|ms-|5.6.20240627
nextjs-snippets|Pul|1.0.2
console-ninja|Wal|1.0.326

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
legacy_priority:31082724

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
