### ISSUE TITLE
Visual Studio Code should be opening a new instance with center clicking the taskbar icon

### ISSUE THREAD

**Issue by allancm** [Microsoft/vscode#21900]
- VSCode Version: 1.10.1
- OS Version: Windows 10 Enterpsie 10586.753

Steps to Reproduce:

1. Open VS Code
2. Use the mouse "center click", or "wheel click" in the icon of the opened app in the taskbar.

I expect to have a new instance of the VS Code without going to the menu and entering Ctrl+Shift+N.
When you "center click" any other instance of many apps (explorer, VS), including UWP apps (Edge, Calc), it is expected to have a new instance of the app clicked.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13905
