### ISSUE TITLE
A tiny little problem with over scrolling minimap

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#21907]
- VSCode Version: latest and greatest
- OS Version: macOS sierra

If VS Code just missed one feature it was this and now it's compelete! Such a nice implementation and great performance. (@alexandrudima as always you fascinate me!)

Just one simple thing that I noticed:

![out-of-screen-scroll](https://cloud.githubusercontent.com/assets/2157285/23557582/c264e420-0045-11e7-9ea6-8789f30db9de.gif)

And also I have to say that I first [wrote a comment here about it](https://github.com/Microsoft/vscode/issues/4865) in case of duplicates

**Comment by alexandrudima** [comment]
Duplicate of #21346
