### ISSUE TITLE
VSCode freezes when I find in the terminal if the terminal content is large enough

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/vscode#219044]
Type: <b>Bug</b>

1.  Run a command that produces tons of output, filling the terminal
2. Search in the terminal - the moment you start typing, VSCode freezes
3. If VSCode doesn't freeze for a significant amount of time, increase the scrollback buffer size and try again.

Searching terminal output seems to be done on the UI thread, it should be done on a background thread.  Obviously this is not as convenient to do in JS as in most languages, but that's not a reason the UX should suffer.  Either the terminal content should be copied to a background thread that does search, or stored in a `SharedArrayBuffer` so that it can be truly shared with the background thread.

VS Code version: Code 1.90.2 (Universal) (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:37:41.291Z)
OS version: Darwin x64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|9, 9, 8|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|/Users/andy/gh/deploy-clarity-prod --crash-reporter-id 17e73030-ddb2-453b-ac15-1ac312aeca89|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
terminal-commands|adr|1.0.5
vscode-eslint|dba|3.0.10
gitlens|eam|15.1.0
prettier-vscode|esb|10.4.0
vscode-astx|jed|0.0.1
vscode-flow-ide|jed|1.6.2
vscode-dude-wheres-my-module|vsc|2.1.1
graphql-typegen|vsc|1.1.3
paste-as-snippet|vsc|1.0.1
vim|vsc|1.27.3
markdown-all-in-one|yzh|3.6.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
legacy_priority:31082724

```

</details>

**Comment by meganrogge** [comment]
/duplicate [#204042](https://github.com/microsoft/vscode/issues/204042)
