### ISSUE TITLE
New command `Open Folder of Current Active File` 

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#219074]
I am not sure if this already exists. I was trying to find the path of the `Default Keyboard Shortcuts` file and I was looking for a command which would open the system folder containing this file. I then wanted to copy and paste the file from the folder. There does not seem to be such a command. I would find that really useful.

**Comment by gjsjohnmurray** [comment]
Are either of these what you want?

![image](https://github.com/microsoft/vscode/assets/6726799/b064000c-0394-4b0c-9e21-7c139dfcf858)

**Comment by aiday-mar** [comment]
Hi @gjsjohnmurray yes I think that was it! Thanks for the help. I will close this issue.
