### ISSUE TITLE
I just now updated the VS code

### ISSUE THREAD

**Issue by SailleshPawar** [Microsoft/vscode#21909]
HI Team,

I just now updated VS code i am not able to get IntelliSense while downloading package in project.json file.
Is anybody facing the same.

**Comment by aeschli** [comment]
That code moved to the [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp).

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1283
