### ISSUE TITLE
Stepping into internal module results in uri error

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#21908]
Insiders:

- start node debug session and step into an internal module, e.g. 'path.js'

Observe:
![2017-03-03_17-33-28](https://cloud.githubusercontent.com/assets/1898161/23559554/a2fcf324-0037-11e7-8034-913a1cde7d66.png)

**Comment by isidorn** [comment]
@weinand I can not reproduce this with a simple node sample and also for our express smoke test. I tried both node and node2.
Can you please provide a small sample for which you can reproduce this?

**Comment by weinand** [comment]
@isidorn  sorry, something was broken in my Insiders. Restarting fixed it.
