### ISSUE TITLE
PHP has bad comma handling in function calls

### ISSUE THREAD

**Issue by TrekkerUK** [Microsoft/vscode#21913]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Ran with --disable-extensions

---

Given the following code:

```php
<?php

$foo = in_array($bar, [1, 2, 3]);

$foo = in_array($bar, ['1', '2', '3']);
```

The commas in the inline array confuse the hint popup with which parameter you're currently in.
![bad commas](https://cloud.githubusercontent.com/assets/13033095/23561107/c5cb4390-0034-11e7-9eff-bab156afa595.gif)

With strings, the hint disappears entirely.
![hint disappears](https://cloud.githubusercontent.com/assets/13033095/23561116/cb5ab854-0034-11e7-8909-65009e57e8a4.gif)

I've tested in a .js file and it seems to handle it fine, so I believe this is limited to PHP.

**Comment by bmewburn** [comment]
@TrekkerUK the following extension may help you out, it has signature help that handles nested comma separated lists.
https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

**Comment by roblourens** [comment]
Our builtin PHP handling is simple and doesn't actually parse the PHP. A full featured PHP extension will be able to handle things like this.
