### ISSUE TITLE
Display test indicators in sticky scroll headers

### ISSUE THREAD

**Issue by macbookandrew** [microsoft/vscode#219135]
I love the pass/fail/running test indicators in the gutter.

How feasible would it be to display them in the sticky scroll header as well? Try the `editor.stickyScroll.enabled` setting:

![337744277-cc011124-8cea-48ef-a2b5-830b37630da6](https://github.com/microsoft/vscode/assets/784333/b39c5303-8790-46e5-bed1-c74dd4f43fd8)

I’m willing to try submitting a PR for this, but I’m really not quite sure where to start with it…any tips would be great

**Comment by aiday-mar** [comment]
Hi @macbookandrew thank you for posting this issue. Yes you can track this issue here https://github.com/microsoft/vscode/issues/187834 which addresses the same concern. I will close this issue in the meantime.
