### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by thepixelguy** [Microsoft/vscode#21911]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|debugger-for-chrome|msjsdiag|2.5.5|
|python|tht13|0.2.3|
|erlang-otp|yuce|0.2.1|

---

Steps to Reproduce:

1. Click "update" when shown.
2. Nothing happens.

1. Click "read notes".
2. Cannot read property of null.

**Comment by tomahawkzx** [comment]
The same happens here.

- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.15031
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|react-toolbox-snippets|alechp|0.12.0|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|vscode-simpler-icons|davidbabel|1.3.0|
|vscode-eslint|dbaeumer|1.2.2|
|dark-plus-plus-theme|DryWolf|0.0.7|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|vsc-material-theme|Equinusocio|0.0.3|
|icons-fania|fania|0.4.0|
|file-icons|file-icons|1.0.0|
|vscode-flatland-icon-theme|gebilaoxiong|0.0.6|
|easy-icons|jamesmaj|0.3.1|
|vsclassic-icon-theme|jez9999|1.0.3|
|ionic2-vscode|jgw9617|1.0.0|
|Angular2|johnpapa|0.5.7|
|vscode-icon-theme|jtlowe|1.4.0|
|theme-dark-plus-contrast|k3a|0.1.101|
|vscode-simple-icons|LaurentTreguier|0.10.0|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.5.3|
|indent-rainbow|oderwat|0.4.1|
|material-icon-theme|PKief|1.3.2|
|seti-icons|qinjia|0.1.3|
|vscode-icons|robertohuertasm|7.2.0|
|indenticator|SirTori|0.2.1|
|react-beautify|taichi|0.3.0|
|ayu|teabyii|0.2.1|
|ionic2|Thavarajan|2.1.3|
|react-redux-es6-snippets|timothymclane|2.0.2|
|jsx|TwentyChung|0.0.1|
|ionic2-snippets|uqutub|0.0.4|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.2.0|
|ReactSnippets|xabikos|1.2.0|
|Material-theme|zhuangtongfa|1.0.3|;



![image](https://cloud.githubusercontent.com/assets/18285859/23562540/9e2177a0-0021-11e7-9e6c-0e8e7d75a79a.png)

![image](https://cloud.githubusercontent.com/assets/18285859/23562557/ac6afaac-0021-11e7-9b2c-e188991235e1.png)

**Comment by joaomoreno** [comment]
#21652
