### ISSUE TITLE
Opening internal module results in error

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#21912]
Insiders:

- start node debugging session
- stop somewhere
- in CALL STACK view select internal module, e.g. 'module.js'

Observe:
![2017-03-03_18-14-00](https://cloud.githubusercontent.com/assets/1898161/23561168/64bb96b4-003d-11e7-91d6-7f774f124596.png)

**Comment by isidorn** [comment]
@weinand I can not reproduce this with a simple node sample. I tried both node and node2.
Can you please provide a small sample for which you can reproduce this?

**Comment by weinand** [comment]
@isidorn  sorry, something was broken in my Insiders. Restarting fixed it.
