### ISSUE TITLE
Error terminal code python 

### ISSUE THREAD

**Issue by willybc** [Microsoft/vscode#21916]
S C: \ Users \ UserPC \ Desktop \ Python> `python hello.py`
```
Python: The term 'python' is not recognized as the name of a cmdlet, function, script file, or
Executable program. Check to see if you typed the name correctly, or if you included a path,
Check that the path is correct and try again.
Online: 1 Character: 1
+ Python hello.py
+ ~~~~~~
     + CategoryInfo: ObjectNotFound: (python: String) [], CommandNotFoundException
     + FullyQualifiedErrorId: CommandNotFoundException
```

i configurate Environment variables, and everything is correct , 
If I open it from another console either cmd.exe or powershell.exe, if it works
The problem is the terminal of visual studio code, I do not know why but
It does not work there

**Comment by Tyriar** [comment]
Can you try completely shutdown VS Code, relaunch and try again?

**Comment by willybc** [comment]
Yes, I did that and it worked
thanks.

**Comment by Tyriar** [comment]
Great, you probably just needed to reset VS Code's environment.
