### ISSUE TITLE
As you can see, when the output is too long, it will automatically wrap the line instead of a horizontal scroll bar, I have seen other problems, and it is not solved.

### ISSUE THREAD

**Issue by qiaozhi-4** [microsoft/vscode#219117]
Please, add the possibility to turn on a horizontal scrollbar in the terminal window (not editor).
As you can see, when the output is too long, it will automatically wrap the line instead of a horizontal scroll bar, I have seen other problems, and it is not solved.
![image](https://github.com/microsoft/vscode/assets/82357518/55ea910d-13ad-4b3d-9c4a-129e0b5b207c)
![image](https://github.com/microsoft/vscode/assets/82357518/ba07320c-d38e-4b2a-ab33-3aa9c9cc6ae9)

**Comment by qiaozhi-4** [comment]
Want a feature like this
![image](https://github.com/microsoft/vscode/assets/82357518/d8075e9b-3247-4dd0-9968-0e01ff6f44e9)

**Comment by qiaozhi-4** [comment]
Wrapping will make the table unreadable
![image](https://github.com/microsoft/vscode/assets/82357518/e1c7f77e-17b4-4cbe-a16c-f983932210a2)

**Comment by albertosantini** [comment]
You can in terminal use Alt + Z keybinding to toggle between the wrap and unwrap.

**Comment by qiaozhi-4** [comment]
> 您可以在终端中使用 Alt + Z 键绑定在包装和解包之间切换。

Thank you. I'm not sure what you mean. I tried it, and the effect was that the pointer changed to a crosshair

**Comment by albertosantini** [comment]
https://code.visualstudio.com/docs/terminal/basics#_fixed-dimension-terminals

**Comment by qiaozhi-4** [comment]
> https://code.visualstudio.com/docs/terminal/basics#_fixed-dimension-terminals

Thank you very much🥳
