### ISSUE TITLE
Tab gets stuck in Problems filter input

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#219199]
> The code I linked is related to a separate issue that I saw, which probably isn't really related to what you fixed. But if I put focus in the Problems or Debug Console filter input, and do some combination of tab out of the input, shift+tab back into it, type in it, then at some point focus gets stuck in the widget and 'tab' doesn't move focus out to the next toolbar. 

 _Originally posted in [#211979](https://github.com/microsoft/vscode/issues/211979#issuecomment-2187963936)_

**Comment by meganrogge** [comment]
@sandy081 my investigation in #223957 might help you

**Comment by sandy081** [comment]
@meganrogge Thanks for the fix.
