### ISSUE TITLE
Request prepareRename failed with message: Document has been closed

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#219126]
![Image](https://github.com/user-attachments/assets/f4e8480d-67ac-421e-ac00-9129c9b116c4)

Reloading the window fixed it.

**Comment by mjbvz** [comment]
Any repo steps? I don't see this when I tested in the vscode-docs repo

**Comment by hediet** [comment]
Unfortunately, it did not happen again since then.

**Comment by mjbvz** [comment]
ok let me know if you see this again
