### ISSUE TITLE
Create new folder and new file in it.

### ISSUE THREAD

**Issue by amikitevich** [Microsoft/vscode#21917]
Hello. Create new File in directory from file in tab is really really cool feature. It would be really cool can create newFolder and File in created folder
![newfileandfolder](https://cloud.githubusercontent.com/assets/3390519/23563157/7fd96f7a-0056-11e7-8551-9d30d63aa4db.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12893
