### ISSUE TITLE
Open Editors list is displays incorrect list when the SCM Working Sets feature is used

### ISSUE THREAD

**Issue by yottalogical** [microsoft/vscode#219159]
Type: <b>Bug</b>

1. Enable SCM Working Sets in the VS Code settings
2. Open a repository in VS Code and switch between different branches, opening different tabs on each branch
3. Eventually, the "Open Editors" dropdown on the left sidebar should become out-of-sync with the actual list of open tabs

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:54:35.075Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 344f97b2-7f1e-4a1d-8b5c-6f485f88af68|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ron|a5h|0.11.0
cucumberautocomplete|ale|3.0.5
astro-vscode|ast|2.10.2
vscode-intelephense-client|bme|1.10.4
vscode-eslint|dba|3.0.10
gitlens|eam|15.1.0
elm-ls-vscode|elm|2.8.0
phpunit|ema|4.16.1
prettier-vscode|esb|9.16.0
vscode-firefox-debug|fir|2.9.10
copilot|Git|1.208.0
copilot-chat|Git|0.16.1
vscode-graphql|Gra|0.11.0
vscode-graphql-syntax|Gra|1.3.6
lalrpop-syntax-highlight|guy|0.0.5
vscode-test-explorer|hbe|2.21.1
Lisp|mat|0.1.12
dotenv|mik|1.0.1
vscode-docker|ms-|1.29.1
autopep8|ms-|2024.0.0
isort|ms-|2023.10.1
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.369.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
cpptools|ms-|1.20.5
remote-explorer|ms-|0.4.3
test-adapter-converter|ms-|0.1.9
vsliveshare|ms-|1.0.5932
sqltools|mtx|0.28.3
java|red|1.32.0
rust-analyzer|rus|0.3.2011
crates|ser|0.6.6
markdown-preview-enhanced|shd|0.8.13
rewrap|stk|1.16.3
vscode-open-in-github|sys|1.18.0
even-better-toml|tam|0.19.2
errorlens|use|3.20.0
vscode-lldb|vad|1.10.0
jinja|who|0.0.8
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
legacy_priority:31077528

```

</details>

**Comment by bpasero** [comment]
This needs exact, reliable steps how to reproduce.

**Comment by ToLive** [comment]
> This needs exact, reliable steps how to reproduce.

Hi! I have steps to reproduce:
1. Turn on Working set feature for user and select "current" for new branch.
2. Turn on "View - Appearance - Secondary side bar" and move Opened editors to secondary bar.
3. Open (double click, NOT preview) 3-4 files. They should appear normally in both tab bar and opened editors.
4. Switch to another new branch.
5. Open another file for preview (one click, name will be showing in italic). File should be visible in tab bar and opened editor.
6. Switch to the first branch
7. Do step 5 with another file
8. Switch to the branch as in step 4
9. Try to open file in preview. Now you will have a bug, with file in Tab bar and not in the Opened editors.

I made a video how to reproduce it https://youtu.be/cX8gqt8DfAE Looks like the problem is with file preview and how it is handled on the branch switch.

**Comment by bpasero** [comment]
Latest insiders should include the fix: You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ToLive** [comment]
> Latest insiders should include the fix: You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Thank you! Looks good for me, I can't reproduce the bug anymore.
