### ISSUE TITLE
Warning when restarting Code with active terminal sessions

### ISSUE THREAD

**Issue by DaveAppleton** [Microsoft/vscode#21910]
- VSCode Version: 1.10.1
- OS Version: 10.11.6

Steps to Reproduce:

1. Write some code (e.g.a webserver in Go)
2. Open bash terminal and run it from the terminal
3. Maybe have half a dozen other instances open
4. Wait for a VS Code release
5. Agree to restart VS Code
6. Wait for the warning that you have active processes before closing the bash sessions...
7. swear when you realise that you inadvertantly restarted something that you were testing ...

**Comment by isidorn** [comment]
Hmm I am not getting a confirmation message, here's my scenario
I have zsh shell

1. Terminal, npm run watch
2. Reload vscode -> no warning even though my watch task is runnning

**Comment by Tyriar** [comment]
Oh sorry, you will need to set: 

```ts
"terminal.integrated.confirmOnExit": true
```

**Comment by isidorn** [comment]
@Tyriar adding verified. However I would not expect the warning if my terminal instance is not busy. To be more precise, now if I simply open the terminal and have the setting and reload I am prompted.

**Comment by Tyriar** [comment]
@isidorn there's no way to detect this. Most IDEs work in this way I believe, if you have a terminal shell open it will warn.
