### ISSUE TITLE
Test Explorer For Unit Testing 

### ISSUE THREAD

**Issue by SoheilAlizade** [Microsoft/vscode#21920]
Use **Test Explorer** to run unit tests from Visual Studio Code or third-party unit test projects.
Like [Visual Studio  IDE](https://www.visualstudio.com/en-us/docs/test/developer-testing/getting-started/getting-started-with-developer-testing)
![ic845727](https://cloud.githubusercontent.com/assets/22220356/23564014/45c7dbfc-005e-11e7-85ae-8045404d06a1.jpeg)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/9505

**Comment by SoheilAlizade** [comment]
[.NET Core Test Explorer for Visual Studio Code](https://github.com/formulahendry/vscode-dotnet-test-explorer)
