### ISSUE TITLE
Can't load same repository on 2 or more monitors

### ISSUE THREAD

**Issue by soljohnston777** [Microsoft/vscode#21927]
- VSCode Version: 1.10.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a new window
2.under Recent click on the repository you have open in your in your 2nd monitor.

Nothing will happen.  It tries to open that which is already opened instead of allowing you to open it on a second screen also.

Thanks!

**Comment by isidorn** [comment]
dup of https://github.com/Microsoft/vscode/issues/2686
