### ISSUE TITLE
Comparing two large files keeps loading forever

### ISSUE THREAD

**Issue by perigozin** [microsoft/vscode#219259]
# Does this issue occur when all extensions are disabled?: Yes/No

Yes

# Software version:

- VS Code Version: 1.90.2
- OS Version: Windows 11 23H2

# Steps to Reproduce:

1. Select two somewhat large files to compare
2. Wait indefinitely

# Additional context:

- I'm trying to compare two plain text files that have around 30.000 lines (URLs) each. It keeps loading as if it was doing something but it never reaches the end (I waited a few hours just to see if it would finish).
- VSCode keeps using 10~15% of CPU while it's loading the comparison until I close the tab manually (which is weird, I would've thought it would be using 100% or something). RAM seems unaffected.

**Comment by hediet** [comment]
/duplicate the diff algorithm has some performance issues (there are many issues about this).

> VSCode keeps using 10~15% of CPU

Probably because it is single-threaded.
