### ISSUE TITLE
MiniMap doesn't allow to scroll correctly on the side

### ISSUE THREAD

**Issue by maxime4000** [Microsoft/vscode#21924]
- VSCode Version: 1.10.1
- OS Version: Windows 7

Bug from this feature [MiniMap](https://github.com/Microsoft/vscode/issues/4865)

Steps to Reproduce:

1. Select long text that you have to scroll to the right to see most of it.
2. Click and hold mousse.
3. Select all and try to scroll right but with the minimap it doesn't scroll to the right.
4. After the minimap, you just go to the end of the line.

![issue](https://cloud.githubusercontent.com/assets/4070713/23564759/3548eeb4-0019-11e7-8980-15bce365befc.gif)

What it could be : Minimap opacity 40% and when your selecting some text and your mouse have no interaction on it when you're selecting ?

**Comment by maxime4000** [comment]
Sorry I did a duplicate of https://github.com/Microsoft/vscode/issues/21915

**Comment by ValdemarTerte** [comment]
I thought I made something with my settings XD

**Comment by isidorn** [comment]
Closing as duplicate then
