### ISSUE TITLE
Terminal Pane Locks up VS Code when Displayed on Chromebook

### ISSUE THREAD

**Issue by spillz** [microsoft/vscode#219268]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2 for Chromium 122.0.6261.156
- Also tested: 1.91.0-insider (Chromium 122.0.6261.156)
- OS Version: Chromebook 125.0.6422.197 (Official Build) (64-bit ARM) with Linux ARM 64 6.6.25

Steps to Reproduce:

1. Open VS Code
2. Press Ctrl+` or View->Terminal

This issue has been present for at least a couple of weeks on my Chromebook and makes the embedded terminal completely unusable. I wonder if it is a version incompatibility between the device used to build the ARM64 build (version 122) and more up-to-date ChromeOS releases (e.g., version 125 or 126).

**Comment by wu-kan** [comment]
I have encountered the same problem.

```shell
版本: 1.90.2
提交: 5437499feb04f7a586f677b155b039bc2b3669eb
日期: 2024-06-18T22:42:23.413Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux arm64 6.6.25-01713-g2f237acc8e50
```

- HP Chromebook X2 11 8GB
- ChromeOS 125.0.6422.197

[output.webm](https://github.com/microsoft/vscode/assets/44857941/8070917d-f75e-4033-9db3-d037218e12cd)

**Comment by spillz** [comment]
After some experimenting, I found a workaround by turning `Terminal > Integrated: Gpu Acceleration` to `off` (control+, search for `gpu acceleration`). Not ideal but it works.

**Comment by meganrogge** [comment]
We removed the canvas renderer recently, which was called out in the release notes. https://github.com/microsoft/vscode/pull/211449 I am guessing that for your particular machine, gpu acceleration isn't well supported, which is why you were seeing this issue. Glad that you've figured it out.

**Comment by spillz** [comment]
Ah, i see, thanks. My GPU setting was set to auto, which I assume is the default shipping setting. Is there no way to adjust the detection so that it would correctly switch off GPU rendering?
