### ISSUE TITLE
Disable strict SSL in ./node_modules/vscode/bin/install script?

### ISSUE THREAD

**Issue by emackey** [Microsoft/vscode#21926]
I'm on a corporate network (not a proxy) that imposes its own self-signed SSL certificate on outbound https traffic.

I already have this in my `settings.json`, which is insecure but at least allows me to install vscode extensions:

```
    "http.proxyStrictSSL": false
```

Likewise, I can turn off strict ssl to install npm modules, with `npm set strict-ssl false`.  This is git bash on Windows:

```
$ npm config ls -l | grep strict-ssl
strict-ssl = false
```

```
$ cat package.json
{
  "name": "test-vscode-install",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "engines": {
    "vscode": "^1.0.0"
  },
  "scripts": {
        "vscode:prepublish": "node ./node_modules/vscode/bin/compile",
        "compile": "node ./node_modules/vscode/bin/compile -watch -p ./",
        "postinstall": "node ./node_modules/vscode/bin/install"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "typescript": "^2.2.1",
    "vscode": "^1.0.5"
  }
}
```

```
$ npm install

> test-vscode-install@1.0.0 postinstall C:\path\test-vscode-install
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.0.0
Error installing vscode.d.ts: Error: self signed certificate in certificate chain
```

So, to summarize:

* :+1:  vscode settings.json is configured for insecure SSL, and can install extensions from the marketplace.
* :+1: npm is configured for insecure SSL, and can install ordinary npm packages without trouble.
* :x: The vscode "postinstall" node script is still choking on the self-signed cert.

Is there a way to fix this?  Thanks!

**Comment by joaomoreno** [comment]
@bpasero The code to fetch `vscode.d.ts` should maybe pay attention to npm's value of `strict-ssl`?

**Comment by bpasero** [comment]
This issue was moved to Microsoft/vscode-extension-vscode#57
