### ISSUE TITLE
VSCode and VS extension sites have gone missing.

### ISSUE THREAD

**Issue by LTIOfficial** [microsoft/vscode#219243]
Forgive me if there's a more appropriate place to report this, but the Marketplace website is currently producing a 404 Not Found.
https://marketplace.visualstudio.com/vscode

Same issue for Visual Studio.
https://marketplace.visualstudio.com

**Comment by LTIOfficial** [comment]
VSCode's Marketplace is back up, but Visual Studio's is still down.

**Comment by MichelMunoz** [comment]
It's worse now, plugins page is not accessible, trying to go to [https://marketplace.visualstudio.com/vscode](url) using a browser
causes a redirect to a MS login page:

![Screenshot 2024-07-01 a](https://github.com/microsoft/vscode/assets/18261174/be977aa0-d400-4423-b98a-4f820e22bbca)

the redirect is to 
`https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?client_id=499b84ac-1321-427f-aa17-267ca6975798&scope=499b84ac-1321-427f-aa17-267ca6975798%2Fuser_impersonation%20openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Fapp.vssps.visualstudio.com%2F_msal%2F_popup&client-request-id=01906d7c-b530-79aa-9646-f45633eecdd0&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=3.10.0&client_info=1&code_challenge=mVS3qIIu7crQO9ODf4fUfFhCU2jWYWPzrFl_3UZiwl4&code_challenge_method=S256&nonce=01906d7c-b530-7bd0-aec1-dfc29520a084&state=eyJpZCI6IjAxOTA2ZDdjLWI1MzAtN2I1ZS1hZmRlLTRmOTQ3MTY2ZThjYSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D%7C%7B%22service%22%3A%2200000029-0000-8888-8000-000000000000%22%2C%22isLegacyDomain%22%3Atrue%2C%22accessMapping%22%3A%22PublicAccessMapping%22%2C%22type%22%3A%22redirect%22%7D`

**Comment by roblourens** [comment]
I think the service was having an issue last week, but it seems to be back up now
