### ISSUE TITLE
Indent guides

### ISSUE THREAD

**Issue by adolfojbarreto** [Microsoft/vscode#2192]
Hi, is there any chance we can get indent guides (the vertical lines that run down to matching indents). Could not find reference to them anywhere in VS code or the gallery. Thanks - Adolfo

**Comment by greybax** [comment]
Do you mean like it describes in this issue https://github.com/Microsoft/vscode/issues/1673 ?

**Comment by adolfobarreto75** [comment]
Hi greybax, No, but thanks for the response :) ...let me see if i can draw it out here:

<li>
.    <p>
.    .      slkdfjkldsfaksdflkdasjf
.    .     <br>
.    .      alsdkfjieakegan;eikgie
.    </p>
</li>

The guides are the dots that help align the tags above.

**Comment by adolfobarreto75** [comment]
ok that did not work...lol. Basically they are lines or dots that connect open and closing tags. they help you align the code.

**Comment by stkb** [comment]
I think you're wanting something like the [Indent Guides](https://visualstudiogallery.msdn.microsoft.com/e792686d-542b-474a-8c55-630980e72c30) extension for Visual Studio?

![screen](https://cloud.githubusercontent.com/assets/6125444/12529713/1a2681e6-c1c2-11e5-9769-2316c513c133.png)


However, I find that if you turn on whitespace rendering by setting the ```"editor.renderWhitespace"``` setting to ```true```, you get something that works almost just as well:

![whitespace](https://cloud.githubusercontent.com/assets/6125444/12529701/7153b8cc-c1c1-11e5-8579-c21d74ba9e2c.png)

It shows arrows for tabs and small dots for spaces

**Comment by adolfobarreto75** [comment]
Hi yes...that's it. Thank You!

**Comment by sylvainlap** [comment]
+1

I really think that indent guide (vertical lines) would be useful.

**Comment by ianwesterfield** [comment]
:+1:

@stkb has it right on. Would love to see a similar indent guide extension for vscode. 

Aside from the actual indent guide lines, a separate color for the lines in the currently active indent level (cursor line) really pluses the experience up.

**Comment by bgashler1** [comment]
This will address #3803, where users have had trouble seeing where the left edge of the code editor is and where subsequent tabs are (especially with smaller tab sizes).

**Comment by emergugue** [comment]
This [extension ](https://marketplace.visualstudio.com/items?itemName=spywhere.guides)solves the problem

**Comment by Tyriar** [comment]
@alexandrudima see https://github.com/Microsoft/vscode/issues/6470, indent guides are essentially done with the exception of this issue https://github.com/spywhere/vscode-guides/issues/1 which we could tweak the API to cover.

**Comment by poetinha** [comment]
I would like to see Indent Guides in Visual Studio Code.

**Comment by greybax** [comment]
agree with @poetinha that it shouldn't be as extension. This is a basic functionality most of IDEs

**Comment by dvlsg** [comment]
Also agree with @poetinha. I think this functionality is standard enough that it should be part of the application itself.

I will say that the `vscode-guides` extension does work pretty well in the interim, though. It gets a little bit confused do some swapping back and forth between tabs/spaces, but I do that fairly rarely, and the extension always catches up automatically and gets back to normal.

**Comment by jwurmitzer** [comment]
Yes please ! Indentation Guides are needed!

**Comment by bj7** [comment]
I would also love to see this natively implemented! This is such a great editor!

**Comment by alexandrudima** [comment]
Behind `editor.renderIndentGuides`

![image](https://cloud.githubusercontent.com/assets/5047891/16460248/cfd6f440-3e26-11e6-88a3-e9f2f4d8c80c.png)

**Comment by JetLua** [comment]
How to set the indent guide color?

**Comment by JetLua** [comment]
@alexandrudima How to set the indent guide color?

**Comment by dvlsg** [comment]
Access to the indent styling in general through the standard settings would be great. I love the indents, but they're pretty distracting compared to other indent lines I'm used to. Access to change the opacity, specifically, would be awesome.

**Comment by shauntrennery** [comment]
Also being able to highlight a selected indent guide would be great for navigating longer code blocks.

**Comment by bgashler1** [comment]
@shauntrennery can you create a dedicated issue for your idea?  Also please tag it `feature-request`.  It's a great idea!  Thanks.

**Comment by shauntrennery** [comment]
@bgashler1 Added #14017, sorry not sure how to tag it.

**Comment by mosajjal** [comment]
Hi. I've experienced some issues with the extension in large files [#19982]. So I'm also asking for native support for this feature as it's a pretty basic need of every developer out there.

**Comment by Tyriar** [comment]
@mosajjal native support was added some time ago https://github.com/Microsoft/vscode/issues/2192#issuecomment-229410639

**Comment by mosajjal** [comment]
I just found it in the configuration. Thanks :)

**Comment by gatspy** [comment]
[Guides](https://marketplace.visualstudio.com/items?itemName=spywhere.guides) can try it.

**Comment by mosajjal** [comment]
@gatspy Guides can cause #19982

**Comment by M-Fasciano** [comment]
"editor.renderIndentGuides": true

**Comment by C0rn3j** [comment]
"editor.renderWhitespace": "all"

Used to show dots for spaces and arrows for tabs, new version doesn't have this, how do I reenable it?

**Comment by mosajjal** [comment]
`"editor.renderWhitespace": "boundary"` works for me in 1.11

**Comment by C0rn3j** [comment]
@mosajjal I'm on the git version, and there it doesn't work anymore. I'm 2 days behind though, maybe it's fixed by now, I'll see about compiling the new version.
Version 1.12.0
Commit 5e5e9e3bb56a3182e58ad097e107966633643253

**Comment by techsin** [comment]
@M-Fasciano worked ++++1

**Comment by hernimen** [comment]
ident guides!!! plz!!!!

**Comment by AliAtrash** [comment]
Super help. Thanks!

**Comment by abrahaobittar** [comment]
Thanks, worked 1.12.2

**Comment by vsudakov** [comment]
Would be great to see it also in "Explorer" panel...

**Comment by aaaaeinai** [comment]
Would be great if the color of the Indent Guide can be modified like (my IDE has black background and I just want grey instead of white).

**Comment by juancampa** [comment]
Would be great to also have an option to show the guides only on hover
