### ISSUE TITLE
Minimap + Scrollbar (and minimap highlighting)

### ISSUE THREAD

**Issue by ValdemarTerte** [Microsoft/vscode#21925]
- VSCode Version: 1.10.1
- OS Version: Windows 10

Good day! It is not useful enough when you must use the functions of minimap and scrollbar at the same.
So, in my opinion, it would be very kind of you, if you add the options like:
"editor.scrollbar.vertical": false
"editor.scrollbar.horizontal": false
and possibility of hiding the highlighting of active viewport when a cursor is over on the minimap:
"editor.minimap.highlight": false

**Comment by ValdemarTerte** [comment]
It's critically(about the scrollbar) when you use two viewports together

**Comment by ghiscoding** [comment]
This is a duplicate and already tracked under #21404 and #21784.
