### ISSUE TITLE
Git extension shell

### ISSUE THREAD

**Issue by r34son** [microsoft/vscode#219221]
Does this issue occur when all extensions are disabled?: No

Version: 1.90.2
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:54:35.075Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.3.0

Steps to Reproduce:

1. add `echo $SHELL && exit 1` in git pre-commit hook
2. After commiting in GUI i can see in output that bash shell is used

How can I change it to zsh so that all git commands by extension will run in zsh?

**Comment by r34son** [comment]
same question on SO https://stackoverflow.com/questions/78204185/how-to-configure-the-shell-that-vscode-extensions-use

**Comment by lszomoru** [comment]
Sorry for not getting back to you on this until now. When you perform a source control operation VS Could would spawn a child process and execute `git.exe`. This child process "inherits" the environment variables from VS Code and in turn VS Code inherits the environment variables from where it was launched. What is the reason for using zsh for running the git commands? Is it merely the environment variables?

**Comment by r34son** [comment]
I wanna use zsh to run scripts and get env vars from .zshrc

**Comment by lszomoru** [comment]
Could you try opening a Terminal that uses zsh and launch `code` from there? Thanks!
