### ISSUE TITLE
Window non responsive after trying to create new window during debugging

### ISSUE THREAD

**Issue by Devon7925** [microsoft/vscode#219277]
Type: <b>Bug</b>

1. Start a debugging session
2. Stop on a breakpoint
3. Try to drag tab to create a new window
4. Window is unresponsive
Video of what was happening
https://github.com/microsoft/vscode/assets/22968971/b18f58f1-2faf-4d3b-9c67-b6f71ef450bb

It didn't consistently happen, and I got a variety of results testing this. Sometimes it would create a phantom debugging session that was unstoppable. Even when it worked, it made the debugging tool thingy disappear from the main window until I clicked another tab.

VS Code version: Code - Insiders 1.91.0-insider (aea213b7fcc7de5c24ad797ac1af209b159d451f, 2024-06-28T05:56:20.804Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700F (24 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (11.84GB free)|
|Process Argv|--crash-reporter-id 9a4abf6c-ce75-43bf-8b93-13ddcbeeb78a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (97)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ron|a5h|0.11.0
vscode-css-formatter|aes|1.0.2
Bookmarks|ale|13.5.0
tsl-problem-matcher|amo|0.6.2
language-mcfunction|arc|0.18.0
insertnumbers|Asu|0.9.1
npm-intellisense|chr|1.4.5
doxdocgen|csc|1.4.0
vscode-download-file|dar|0.0.1
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|3.0.10
vscode-notepad|dev|0.1.2
vscode-wavefront|dmn|1.0.1
vscode-wasm|dts|1.4.1
gitlens|eam|15.1.0
EditorConfig|Edi|0.16.4
json-tools|eri|1.0.2
glsl-language-support|fil|0.0.4
vscode-firefox-debug|fir|2.9.10
codespaces|Git|1.16.23
copilot|Git|1.208.960
copilot-chat|Git|0.17.2024062801
remotehub|Git|0.62.0
gc-excelviewer|Gra|4.2.59
todo-tree|Gru|0.0.226
vscode-drawio|hed|1.6.6
smartmulticursor|ida|0.0.4
pgn|jak|1.0.2
latex-workshop|Jam|10.1.0
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
regex-notebook|jri|0.0.6
markdown-math|koe|0.1.0
restructuredtext|lex|190.4.1
calculator|lix|0.1.1
vscode-language-babel|mgm|0.0.40
fluent-icons|mig|0.0.18
file-downloader|min|1.0.13
vscode-nbt|Mis|0.9.1
compare-folders|mos|0.24.3
vscode-language-pack-fr|MS-|1.91.2024062609
csdevkit|ms-|1.7.27
csharp|ms-|2.34.12
dotnet-interactive-vscode|ms-|1.0.5229040
vscode-dotnet-runtime|ms-|2.0.7
isort|ms-|2023.13.11511010
python|ms-|2024.9.2024062703
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.6.2024062802
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
anycode|ms-|0.0.73
anycode-c-sharp|ms-|0.0.5
anycode-cpp|ms-|0.0.5
anycode-go|ms-|0.0.5
anycode-java|ms-|0.0.5
anycode-kotlin|ms-|0.0.5
anycode-php|ms-|0.0.6
anycode-python|ms-|0.0.5
anycode-rust|ms-|0.0.6
anycode-typescript|ms-|0.0.5
azure-repos|ms-|0.38.0
cpptools|ms-|1.21.0
hexeditor|ms-|1.10.0
live-server|ms-|0.4.13
mono-debug|ms-|0.16.3
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
vscode-github-issue-notebooks|ms-|0.0.130
vscode-markdown-notebook|ms-|0.0.26
vscode-typescript-next|ms-|5.6.20240628
vsliveshare|ms-|1.0.5932
glsl-analyzer|nol|1.3.0
indent-rainbow|ode|8.3.1
fix-json|oli|0.1.2
vscode-jest|Ort|6.2.5
wgsl|Pol|0.1.17
gdscript-toolkit-formatter|Raz|1.2.3
vscode-commons|red|0.0.6
vscode-xml|red|0.27.1
vscode-sort-json|ric|1.20.0
datetime|rid|2.2.2
rust-analyzer|rus|0.4.2017
crates|ser|0.6.7
vscode-fileutils|sle|3.10.3
wav-preview|suk|2.5.0
even-better-toml|tam|0.19.2
pdf|tom|1.2.2
luna-paint|Tyr|0.16.0
errorlens|use|3.20.0
intellicode-api-usage-examples|Vis|0.2.8
vstuc|vis|1.0.2
cursor-align|yo1|1.1.2
markdown-pdf|yza|1.5.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
vscaat:30438846
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
chatpanelt:31014475
g316j359:31013175
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31057980
nativerepl1:31071684
refactort:31084545
pythonrstrctxt:31083681

```

</details>

**Comment by roblourens** [comment]
Is it only doing this specifically when you try to drag the tab to a new window? Or is it just related to debugging?

**Comment by Devon7925** [comment]
It was doing it when I tried to drag a tab out of the window while debugging. Dragging a window out without debugging worked fine, and debugging itself worked fine.

**Comment by roblourens** [comment]
I'm not sure what's going on, but I wonder whether this particular debuggee, or this Nvidia overlay that pops up are somehow involved. I notice you get this 🚫 cursor which I haven't seen before and doesn't look windows-native.

**Comment by Devon7925** [comment]
That cursor happens any time I drag a tab out of the window. I can no longer replicate this issue, and although my rust extension did update, they didn't mention my issue in their changelog. I'll try to see if I can disable the NVidia overlay to see if that fixes it if the issue reoccurs in future. I'll close this for now.
