### ISSUE TITLE
Infinite loop of "The TypeScript language service died unexpectedly" (2)

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#21921]
- VSCode Version:1.11.0-insider (also happens in `1.10.1`)
- OS Version: Linux Mint 18

This is essentially the same as #9215.
I am able to work normally using `"typescript.tsdk": "/home/andy/.nvm/versions/node/v7.7.1/lib/node_modules/typescript/lib"`, but when I try using vscode's built-in typescript compiler I get errors.

Steps to Reproduce:

1. Navigate to an empty directory.
2. `code-insiders .`
3. Create a new file `a.ts`.
4. In addition to a warning `Version mismatch! global tsc (2.3.0-dev.20170303) != VS Code's language service (2.2.1). Inconsistent compile errors might occur`, I repeatedly get an error `The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.`.

**Comment by mjbvz** [comment]
To help investigate, please enable "typescript.tsserver.trace": "verbose",` and share the output from `TypeScript` in the output panel 

Thanks

**Comment by andy-ms** [comment]
I set `"typescript.tsserver.trace": "verbose"` in my user settings, but I just see this over and over:
```
[Error - 12:52:25 PM] TSServer exited with code: 1
[Info  - 12:52:25 PM] Using tsserver from location: /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Error - 12:52:25 PM] TSServer exited with code: 1
[Info  - 12:52:25 PM] Using tsserver from location: /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js
```

**Comment by mjbvz** [comment]
Can you check the `TSS_LOG` as well please?

**Comment by andy-ms** [comment]
Sorry, where is that?

**Comment by mjbvz** [comment]
See this comment for enabling logging on the tsserver: https://github.com/Microsoft/vscode/issues/21442#issuecomment-282903822

**Comment by andy-ms** [comment]
Running `export TSS_LOG="-level verbose -file /home/andy/tsserver.log"` made the problem disappear!
Running `export TSS_LOG="-level verbose"` (which it seems it was set to before) makes the language service start crashing again.
May be crashing in the code that parses `TSS_LOG`? But I wonder why setting `"typescript.tsdk"` made the error go away.

**Comment by mjbvz** [comment]
We don't parse the `TSS_LOG` file on the VSCode side. `typescript.tsdk` only logs our communications with the TSServer. It may be a timing issue of some sort. I suspect this is a TypeScript issue, but after debugging the TS, you believe that VSCode is doing something wrong, please let me know

**Comment by mjbvz** [comment]
@andy-ms Please let me know if you believe there is an issue on the VSCode side here.

One possible cause of the crashing is an invalid TSS_LOG environment variable: https://github.com/Microsoft/TypeScript/issues/14528 . That may explain why running `export TSS_LOG=...` fixed things

Thanks
