### ISSUE TITLE
Support terminal link matchers in tasks v2

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#21928]
Part of tasks v2: https://github.com/Microsoft/vscode/issues/15179

Use `ITerminalInstance.registerLinkMatcher` to register expected regexes.

**Comment by dbaeumer** [comment]
Moved to April due to #23262, #23263, #23264

**Comment by dbaeumer** [comment]
Moving due to shifted priorities.

**Comment by dbaeumer** [comment]
Moving due to  #23263

**Comment by dbaeumer** [comment]
Marking as dup of #21928 since there is no link matching planned in the old output runner.

**Comment by dbaeumer** [comment]
Wrong issue :-).

**Comment by Tyriar** [comment]
@alexr00 does tasks need this? What sort of links?

**Comment by alexr00** [comment]
I don't think so. It looks like this was going to be used to use the task problem matcher regex to make links in the terminal. But we have problems for nice links. The terminal also does a nice job of making links already.

**Comment by tmcguire** [comment]
Since this has been closed as out-of-scope, can #39920 be re-opened again? It was originally closed as a duplicate but looks like it has a smaller scope.
