### ISSUE TITLE
Show exception widget for promise rejection

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#21929]
I set different StoppedEvent reasons for exceptions vs promise rejections, and we should show the exception widget for promise rejections too. From #21905

It seems like it's currently only shown when `reason === 'exception'`, but it should be shown either whenever the exception text is set, or when `reason === 'promise rejection'`

**Comment by weinand** [comment]
Let's do this after I've added support for a "robust reason attribute" to the DAP (currently the "reason" attribute is localized).

**Comment by weinand** [comment]
@roblourens I'm a bit reluctant to hardcode an additional StoppedEvent reason into the VS Code frontend. Could you try to use "exception" reason for promise rejections and use the new "description" attribute for conveying the "Promise Rejection" to the UI?

With the "robust reason attribute" work "reason" is no longer shown in the UI if a "description" attribute is present.

**Comment by jrieken** [comment]
@roblourens @weinand While this seems to work the information seems to be pretty useless. I understand that in this case rejection happens with `null` but at least the error message should talk about 'Rejected Promise' instead of 'Exception has occurred: null'

![screen shot 2017-04-26 at 14 33 03](https://cloud.githubusercontent.com/assets/1794099/25434629/4e4bf778-2a8d-11e7-93a2-cfdb045f2bf0.png)

**Comment by weinand** [comment]
@michelkaporin we do not seem to show the "description" attribute. Its value would be "Promise Rejection" in this case (and this already shows in the CALL STACK view).

**Comment by michelkaporin** [comment]
@weinand we do surface `description` attribute in exception widget. I can see that 'null' is coming from DA for description, and it is surfaced in UI as-is.

**Comment by weinand** [comment]
Ok, I've tweaked the use of the "description" attribute in node-debug.

Here is how it looks now for different values passed to reject():

![2017-04-27_15-16-38](https://cloud.githubusercontent.com/assets/1898161/25485097/e49ac5fe-2b5c-11e7-911c-8d13ffb9be85.png)
![2017-04-27_15-16-04](https://cloud.githubusercontent.com/assets/1898161/25485101/e7d186c2-2b5c-11e7-87ca-752aa5f18336.png)
![2017-04-27_15-15-36](https://cloud.githubusercontent.com/assets/1898161/25485102/ea780cd4-2b5c-11e7-9ecd-5f67df652335.png)
![2017-04-27_15-15-16](https://cloud.githubusercontent.com/assets/1898161/25485103/ed5f0060-2b5c-11e7-887d-26cde9625b82.png)

BTW, the missing stacktrace bug is tracked by https://github.com/Microsoft/vscode/issues/25555

**Comment by weinand** [comment]
To align better with the "inspector" debugger, I've changed the wording from "Rejected Promise" to "Promise Rejection":

![2017-04-27_16-50-51](https://cloud.githubusercontent.com/assets/1898161/25489332/ca74084a-2b69-11e7-8f42-1d665c27f076.png)
