### ISSUE TITLE
Navigate-back does not work for "Go to definition" < 5 lines

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#21922]
- VSCode Version: 1.11.0-insider
- OS Version: Linux Mint 18

Steps to Reproduce:

1. Make a new file:
```ts
function a() {
}

a();
```

2. Move cursor to `a()`. Hit `F12` to go-to-definition.
3. Hit Alt-Left to go back.
4.
  - VSCode 1.10.1: Goes to the line *after* `a();`.
  - VSCode insiders: Does nothing.

**Comment by bpasero** [comment]
@andy-ms even in 1.10.1 I am not able to "go back". Are you sure its the same code and it works there?

The reason why this does not work is that we have a hardcoded limit of 5 lines before we consider an entry to the history. I do agree though that certain events like "Go to definition" should force a history event. I think I have an idea how to fix that.

**Comment by andy-ms** [comment]
It works for me in VSCode 1.10.1, although it goes all the way to the bottom rather than to the line I was at before.
![vscode](https://cloud.githubusercontent.com/assets/19274678/23579874/8122c6b0-00ab-11e7-828e-fa544fc405ba.gif)

In VSCode Insiders, nothing happens, even if I put a bunch of blank lines between `function a()` and `a();`. Tested on 2 comptuters now.

**Comment by bpasero** [comment]
My fix is to always add an entry to the navigation stack if the source of the line change is a 'api'. This will support to navigate < 5 lines for many programmatic selection changes:
* goto definition
* quick outline
* goto line

I hope there is no regression from this change but I think it makes sense overall.

**Comment by andy-ms** [comment]
This is happening for spans >5 lines. I can't navigate back at all in VSCode insiders.

**Comment by bpasero** [comment]
@andy-ms my change did not make it into yesterdays insider build, please try again today and report back 👍

**Comment by andy-ms** [comment]
Navigation works on windows, but I still can't do navigate-back in insiders on either of my linux machines.

**Comment by bpasero** [comment]
@andy-ms how do you navigate back? To distinguish a keyboard issue from the rest, please use the "Go" menu.

**Comment by andy-ms** [comment]
I hit Alt-Left to go back. It works if I use Go -> Back.

**Comment by bpasero** [comment]
@andy-ms how does your keybindings.json file look like?

**Comment by andy-ms** [comment]
Empty.
```js
// Place your key bindings in this file to overwrite the defaults
[
]
```

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by andy-ms** [comment]
It doesn't seem to contain any useful output.

`code-insiders --verbose .` console output:

```
[main 9:20:42 AM] Starting VS Code in verbose mode
[main 9:20:42 AM] from: /usr/share/code-insiders/resources/app
[main 9:20:42 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[main 9:20:44 AM] IPC#vscode:broadcast null vscode:changeColorTheme vs vscode-theme-quietlight-themes-QuietLight-tmTheme
[2986:0309/092044:INFO:CONSOLE(137)] "%c[Extension Host]", source: file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js (137)
[main 9:20:44 AM] IPC#vscode-workbenchLoaded
[2986:0309/092044:INFO:CONSOLE(137)] "%c[Extension Host]", source: file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js (137)
[2986:0309/092044:INFO:CONSOLE(137)] "%c[Extension Host]", source: file:////usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js (137)
```

Developer tools console output:

```
[Extension Host] git (vscode.git) uses PROPOSED API which is subject to change and removal without notice
workbench.main.js:137
[Extension Host] typescript (vscode.typescript) uses PROPOSED API which is subject to change and removal without notice
workbench.main.js:137
[Extension Host] ObjectexitCode: 128gitCommand: "rev-parse"gitErrorCode: "NotAGitRepository"message: "Failed to execute git"stderr: "fatal: Not a git repository (or any of the parent directories): .git↵"stdout: ""__proto__: Objectd.logExtensionHostMessage @ workbench.main.js:137
```

**Comment by bpasero** [comment]
Yeah nothing really. Is it only at random that Alt+Left does not work? Or all the time?

**Comment by andy-ms** [comment]
All the time.

**Comment by bpasero** [comment]
@andy-ms what about you assign Alt+Left to another keybinding (like quick open), does it work? Trying to understand if this is a keybinding issue or issue with history navigation.

**Comment by andy-ms** [comment]
Oh! Looks like I had a `keybindings.json` in VSCode 1.10 that gave me the ability to use `Alt`+`Left`. So I just had to copy-paste that into Insiders to get it to work.
The default on Linux appears to be `Ctrl`+`Alt`+`-`.
