### ISSUE TITLE
Search term issue

### ISSUE THREAD

**Issue by gangadhararaop** [microsoft/vscode#219251]
Type: <b>Bug</b>

The term I am entering is not showing up in the search results, even though it is present in the codebase.

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.67GB (4.43GB free)|
|Process Argv|--crash-reporter-id 62c4e1a8-9ac9-4cab-a954-9fee41ea4027|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|15.1.0
prophet|Sqr|1.4.40

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
legacy_priority:31082724

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the guidance at https://github.com/microsoft/vscode/wiki/Search-Issues

**Comment by gangadhararaop** [comment]
Thanks for the information. Now, I can see the search results.


Best Regards,



Gangadhara Rao Posimsetti

Analyst - Salesforce Commerce Technology,

M :  +919398868217.

[cid:b9a8f6df-2112-452e-8257-fe667f3042b1]

www.etgdigital.com<http://www.etgdigital.com/> | Careers<https://www.etg.digital/careers/>|  [cid:b27a2fe6-f1d2-48c8-8227-075112abf8f6] <https://www.linkedin.com/company/etg-digital/>   [cid:251aed09-4246-4a86-9730-b1807fc0a8fc] <https://www.instagram.com/etg_digital/>  [cid:6b23fb4f-7fcf-40e5-9aae-81f2067ff774] <https://www.facebook.com/ETGDigital>  [cid:761f9af8-cac6-49ea-811a-b70745b279d2] <https://twitter.com/ETG_Digital>

[cid:722daf25-9904-4d0d-8f4e-9a40eae1ac3c]<https://appexchange.salesforce.com/appxConsultingListingDetail?listingId=a0N3A00000FYEUpUAP>  [cid:e58ffefa-5d5b-4cd4-8038-c37340dccaa3] <https://appexchange.salesforce.com/appxConsultingListingDetail?listingId=a0N3A00000FYEUpUAP>  [cid:b7aee9bf-23f6-46d9-a236-013d1e6eee1c] <https://appexchange.salesforce.com/appxConsultingListingDetail?listingId=a0N3A00000FYEUpUAP>

________________________________
