### ISSUE TITLE
Sticky scroll doesn't get current functions

### ISSUE THREAD

**Issue by jistro** [microsoft/vscode#219314]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2
- Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
- Date: 2024-06-18T22:33:48.698Z
- Electron: 29.4.0
- ElectronBuildId: 9728852
- Chromium: 122.0.6261.156
- Node.js: 20.9.0
- V8: 12.2.281.27-electron.0
- OS: Linux x64 6.9.3-76060903-generic

Steps to Reproduce:

1. Open a `.sol` document.
2. Scroll into a function.
3. Get the bug

[](https://github.com/microsoft/vscode/assets/22781439/e95226c4-8e9e-41d4-a8cf-0eab66cd8c0a)

**Comment by gjsjohnmurray** [comment]
Are you using an extension to add SOL support to VS Code?

Please see https://github.com/microsoft/vscode/issues/168428#issuecomment-2042016610 for information about s setting controlling how sticky scroll decides what is sticky.

**Comment by jistro** [comment]
> Are you using an extension to add SOL support to VS Code?
> 
> Please see [#168428 (comment)](https://github.com/microsoft/vscode/issues/168428#issuecomment-2042016610) for information about s setting controlling how sticky scroll decides what is sticky.

Yes, I use an extension for .sol files, but disabling the extension still reproduces the bug. This occurs without using the approach mentioned in https://github.com/microsoft/vscode/issues/168428#issuecomment-2042016610. However, implementing the fix described in that comment resolves the problem.

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. Could I ask you to add here a copy-paste of the text that caused this issue, so I can look into it?
