### ISSUE TITLE
Can we have a light action bar with the light theme?

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#21938]
I love VS Code and I think everyone knows that. I have opened many issues and stuff but one thing that I always wanted and is really starting to bother me is the dark action bar on the light theme. 

<img width="191" alt="screen shot 2017-03-03 at 10 18 49 pm" src="https://cloud.githubusercontent.com/assets/2157285/23564525/830f6d76-005f-11e7-91ef-54b5c0e8e848.png">

I mean look at this:

<img width="1280" alt="screen shot 2017-03-04 at 12 52 11 am" src="https://cloud.githubusercontent.com/assets/2157285/23569508/d9ec022a-0074-11e7-8d12-ad8073a0616f.png">

Now if we just hide status bar and activity bar, this will be the result:

<img width="1280" alt="screen shot 2017-03-04 at 12 51 53 am" src="https://cloud.githubusercontent.com/assets/2157285/23569588/308b6990-0075-11e7-886d-bf992bf9e8ef.png">

Look at it, how clean and beautiful it gets when you just make it all-light. I get that most of the people use the dark theme so somehow a very small portion care about light one, but can we have a light activity bar?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/3112
