### ISSUE TITLE
Issues with files.autoSave

### ISSUE THREAD

**Issue by objectuser** [Microsoft/vscode#21935]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-elixir|mjmcloug|0.1.1|
|Ruby|rebornix|0.10.4|
|rewrap|stkb|1.3.0|;

---

Since the 1.10.1 update, autosave works intermittently. I've tried both `onFocusChange` and `onWindowChange`. Currently, `"onWindowChange"` appears to work.

Steps to Reproduce:

1. Use `"files.autoSave": "onFocusChange"`
2. Edit code, switch away from window and see it's unsaved.

**Comment by bpasero** [comment]
Let's continue in https://github.com/Microsoft/vscode/issues/21948
