### ISSUE TITLE
terminal.external.windowsExec opened pwsh with title `\\`

### ISSUE THREAD

**Issue by zhaojjiang** [microsoft/vscode#219323]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2 (user setup)
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. create pure windows sandbox with powershell 7.x and vscode installed
2. update user settings to set `"terminal.external.windowsExec": "C:\\Program Files\\PowerShell\\7\\pwsh.exe"`
3. use `Ctrl+Shift+C` to invoke an external pwsh terminal
4. the terminal title showing `\\`

![image](https://github.com/microsoft/vscode/assets/39524531/8ed988f9-804c-43d7-84db-6f8c1fae1cdf)

**Comment by meganrogge** [comment]
we have no control over the external terminal / what directory it opens to by default
