### ISSUE TITLE
Slow startup performance for VSCode-Insiders

### ISSUE THREAD

**Issue by stevebering** [Microsoft/vscode#21936]
- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:10:18.838Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)</code>
- Memory (System): <code>31.93GB (21.70GB free)</code>
- Memory (Process): <code>137.59MB working set (137.61MB peak, 113.88MB private, 27.49MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|133|
|main|app.isReady => window.loadUrl()|1059|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|2203|
|renderer|require(workbench.main.js)|1198|
|renderer|create extension host => extensions onReady()|3157|
|renderer|restore viewlet|2431|
|renderer|restore editor view state|2231|
|renderer|overall workbench load|4272|
|main + renderer|start => extensions ready|8252|
|main + renderer|start => workbench ready|8897|

---
[7027_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/817960/7027_main.cpuprofile.txt)
[7027_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/817961/7027_renderer.cpuprofile.txt)

:warning: Make sure to **attach** these files: :warning:

**Comment by jrieken** [comment]
profile files are missing
