### ISSUE TITLE
Emmet not expanding in HTML file when certain characters at end of string

### ISSUE THREAD

**Issue by macintacos** [Microsoft/vscode#21939]
- VSCode Version: 1.10.1
- OS Version: macOS 10.12.3

There seem to be issues with the expansion provided by emmet. Any ideas? Gif provided below for explanation.

![divissues](https://cloud.githubusercontent.com/assets/8128941/23570046/7f27b454-0030-11e7-8a3f-0e8c68e95b63.gif)

Steps to Reproduce:

1. Try expanding things like 'div.tools' or 'div.tool'
2. See how emmet does not expand properly

**Comment by humilulo** [comment]
fyi: i just installed Visual Studio Code (yes MS version, not vscode) today on Windows 10, which is version 1.10.1 also, and i don't find this bug. I used the untitled document, set the file type to HTML at bottom right of screen so emmet works, then used 'html:5' to generate the basic HTML 5 page, and inside the body tag, div.tool nor div.tools works as the gif shows. Just wanting to help you narrow this down. :)

**Comment by ramya-rao-a** [comment]
Thanks @humilulo 
I tried in both Windows and Mac OS X(10.11.6) and I cannot repro either

**Comment by macintacos** [comment]
I've tried turning off every extension that might affect HTML files or emmet expansions and I'm still getting the same issue. I've attached a list of my current extensions to see if that helps at all.

Also, I'm running a newer version of macOS, not sure if that would affect the outcome.

![2017-03-06-vs-code-extension-list](https://cloud.githubusercontent.com/assets/8128941/23628621/de823d26-0282-11e7-8edc-3659ec550419.jpg)

**Comment by ramya-rao-a** [comment]
Run this in the terminal `code --disable-extensions` This will run VS Code with all extensions disabled.
And see if you still see the issue

**Comment by macintacos** [comment]
@ramya-rao-a just did so and it works fine now, guess it was an extension I installed or updated. I'll re-enable one by one until I find the culprit. Thank you.

**Comment by macintacos** [comment]
Turns out that it is a problem with h HTL Snippet extension, not VS Code itself. Closing the issue and forwarding it to the maintainer of that extension, sorry for the alarm.

**Comment by ramya-rao-a** [comment]
No problem, glad that the root cause was found, Happy Coding!
