### ISSUE TITLE
Download Progress not showing during installation in Terminal

### ISSUE THREAD

**Issue by Aryan-Garg-dev** [microsoft/vscode#219334]
Type: <b>Bug</b>

Whenever I am downloading any library, the progress and text that used to show while downloading are not showing up, instead only a spinner comes and only after everything is downloaded, text comes up.

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700HX (24 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (6.06GB free)|
|Process Argv|--crash-reporter-id 236ad759-0032-40c6-afd1-5fe3e056cdfc|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
legacy_priority:31082724

```

</details>

**Comment by Aryan-Garg-dev** [comment]
https://github.com/microsoft/vscode/assets/148696092/59ccd092-353c-4bb5-ad3f-8d236da00057

**Comment by Aryan-Garg-dev** [comment]
https://github.com/microsoft/vscode/assets/148696092/63da97ed-7e4b-426d-8d02-2c8f1096cb0f

**Comment by meganrogge** [comment]
thanks for the gif, I'm not sure what you mean - could you be more specific or provide a gif where they were working in prior versions?

**Comment by Aryan-Garg-dev** [comment]
https://stackoverflow.com/questions/78693097/terminal-not-displaying-installation-progress-properly

I have posted this on StackOverflow, it has the links to reference videos.

**Comment by meganrogge** [comment]
looks like you're in a different working directory when you ran in the new vs old

**Comment by Aryan-Garg-dev** [comment]
Yes, because these video are of 2 different devices

**Comment by meganrogge** [comment]
The different environments are likely the cause, unrelated to vs code

**Comment by Aryan-Garg-dev** [comment]
Okay, but do you know the fix, any suggestions?
