### ISSUE TITLE
Text is reformatting itself when I Save.

### ISSUE THREAD

**Issue by simsketch** [Microsoft/vscode#21930]
http://somup.com/cbeeYV92l

- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.7|
|githistory|donjayamanne|0.1.5|
|tslint|eg2|0.8.1|
|vscode-npm|fknop|3.3.0|
|beautify|HookyQR|0.8.8|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|debugger-for-chrome|msjsdiag|2.6.0|;

---

Steps to Reproduce:

http://somup.com/cbeeYV92l

**Comment by coryshaw1** [comment]
You can turn off format on save in your settings.

`"editor.formatOnSave": false`

**Comment by jordanmkasla2009** [comment]
This is more of an issue with vscode-JS-CSS-HTML-formatter. It garbles JSX syntax when it is contained in a `.js` file instead of a `.jsx` file. tested this using `ALT+SHIFT+F`

**Comment by aeschli** [comment]
Closing. Please file against the https://github.com/lonefy/vscode-js-css-html-formatter for formatting issues.

**Comment by simsketch** [comment]
Weird part is, editor.formatOnSave _was_ set to `false`

**Comment by simsketch** [comment]
I've disabled the formatter in the meantime so I can continue using VS Code as I normally would. Thank you all.
