### ISSUE TITLE
VS Code is crashing on mac

### ISSUE THREAD

**Issue by vgtummala** [Microsoft/vscode#21931]
2017-03-03 12:11:14.609 Electron[62006:5046591] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Critical error: required built-in appearance SystemAppearance not found'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff94702ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff91ffbf7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9470298d +[NSException raise:format:] + 205
	3   libdispatch.dylib                   0x00007fff8689a33f _dispatch_client_callout + 8
	4   libdispatch.dylib                   0x00007fff8689a237 dispatch_once_f + 67
	5   AppKit                              0x00007fff911f2219 +[NSAppearance _defaultAppearance] + 22
	6   AppKit                              0x00007fff91220b85 +[NSAppearance appearanceNamed:] + 24
	7   AppKit                              0x00007fff91202e36 +[NSWindow initialize] + 166
	8   libobjc.A.dylib                     0x00007fff91ff23c8 _class_initialize + 711
	9   libobjc.A.dylib                     0x00007fff91ff1d08 lookUpImpOrForward + 179
	10  libobjc.A.dylib                     0x00007fff91fec591 objc_msgSend + 209
	11  AppKit                              0x00007fff911e883d +[NSApplication initialize] + 719
	12  libobjc.A.dylib                     0x00007fff91ff23c8 _class_initialize + 711
	13  libobjc.A.dylib                     0x00007fff91ff2156 _class_initialize + 85
	14  libobjc.A.dylib                     0x00007fff91ff1d08 lookUpImpOrForward + 179
	15  libobjc.A.dylib                     0x00007fff91fec591 objc_msgSend + 209
	16  Electron Framework                  0x000000010e873fb1 _ZN4atom20AtomBrowserMainParts23PreMainMessageLoopStartEv + 33
	17  Electron Framework                  0x000000010f126333 _ZN4base8internal14NarrowingRangeIilE3minEv + 8118883
	18  Electron Framework                  0x000000010f12b767 _ZN4base8internal14NarrowingRangeIilE3minEv + 8140439
	19  Electron Framework                  0x000000010f1259b5 _ZN4base8internal14NarrowingRangeIilE3minEv + 8116453
	20  Electron Framework                  0x000000010f08e7c0 _ZN4base8internal14NarrowingRangeIilE3minEv + 7497456
	21  Electron Framework                  0x000000010f08d9a6 _ZN4base8internal14NarrowingRangeIilE3minEv + 7493846
	22  Electron Framework                  0x000000010e7d4347 AtomMain + 71
	23  Electron                            0x000000010e7c7f26 main + 38
	24  libdyld.dylib                       0x00007fff839cd5ad start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by bpasero** [comment]
@vgtummala when does this happen? which Code version?

**Comment by vgtummala** [comment]
When I opened VS code on mac I am getting an error window has crashed error. Looked into other issues. My keyboard setup is already US_en.  I did start it from command line and posted exception in this issue.
![2017-03-07_10-05-52](https://cloud.githubusercontent.com/assets/26173368/23670765/a968ab70-031d-11e7-8654-e4a1b5a29821.png)

**Comment by bpasero** [comment]
@vgtummala do you happen to define an environment variable called `NEXT_ROOT`? Can you try to start from the command line with a no additional environment variable overridden?

**Comment by vgtummala** [comment]
NEXT_ROOT environment variable is causing the crash. It worked fine after unsetting this environment variable.

**Comment by bpasero** [comment]
No, but it looks like this is causing something weird.
