### ISSUE TITLE
Type parameter list not displayed in find all refs/go to definition dialog

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/vscode#2194]
![image](https://cloud.githubusercontent.com/assets/972891/12525276/1184dcc2-c118-11e5-868e-870873b58e78.png)

**Comment by dbaeumer** [comment]
@jrieken moving to you since there is no good in the TS extensions producing the list. Could it be that < is not proper escaped. 

Please move back if there is something I can do to fix it.

**Comment by jrieken** [comment]
great find

**Comment by DanielRosenwasser** [comment]
:+1: thanks!
