### ISSUE TITLE
Compile times are too long

### ISSUE THREAD

**Issue by Himanshu-Singh-Chauhan** [microsoft/vscode#219416]
I searched and looked through lots of issues (even engineering tagged issues also), vscode YouTube, internet but was not able to find anything useful.
Yes, I did have read the documentations and contributing guidelines.

I am trying to understand vscode repo, I tried making some changes, but every time I make a change, I have to run `yarn compile` again, which takes about 2 minutes and then reload my window to see changes. why compile time is so long for even small changes, and if I reload my window in between of compilation, then it crashes, I have to restart. 
`yarn watch` does not show that its compiling when it detects changes, after 2 minutes it shows compilation finished. 

also, I run, yarn watch in separate terminal, and ./scripts/code.sh to run code in separate terminal.

is this the right way to do it? does it take same time for everyone to compile and see changes? I feel like I am doing something wrong and there are better ways.

I know it's not an issue, sorry, I will close it after I find some satisfactory answer.

**Comment by roblourens** [comment]
You can run `yarn watch`, you don't need to run compile each time. We typically run the default build task through vscode and this works fine for me.

**Comment by Himanshu-Singh-Chauhan** [comment]
the problem was auto save feature in vscode, when i am making changes, its auto saving and yarn watch is picking up those changes constantly thats why it hangs or takes longer time to compile.

i disabled auto save, and saved manually, and it compiled instantaneously, and then i only had to reload the window to see changes.
