### ISSUE TITLE
Emmet extension for expansion and all other actions using the new apis

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#21943]
**For April Milestone:**

Emmet features are now modularized in https://www.npmjs.com/%7Eemmetio
For example: https://github.com/emmetio/expand-abbreviation is a stand alone module for the Expand Abbreviation feature from emmet. 

This issue is to track the below emmet features in a VSCode extension using the new APIs and is essentially emmet 2.0

- [x] Get emmet expansions in auto-complete suggestion list
- [x] Wrap with Abbreviation
- [x] Remove Tag
- [x] Update Tag
- [x] Go to Matching Pair

**For May Milestone**

- [x] Balance Inward 
- [x] Balance Outward 
- [x] Split/Join Tags
- [x] Merge Lines
- [x] Toggle Block Comment (html)
- [x] Toggle Block Comment (stylesheet)
- [x] Go to Next/Previous edit point
- [x] Select Next/Previous item (html)
- [x]  Select Next/Previous item (stylesheet)

**Deferred to next Milestone**
- [ ] Increment/Decrement by n
- [ ] Update Image Size
- [ ] Evaluate Math Expression
- [ ] Reflect CSS Value

**Comment by ramya-rao-a** [comment]
Initial commit: https://github.com/ramya-rao-a/vscode-emmet

**Comment by ramya-rao-a** [comment]
At the end of April milestone, here is what we have

- The extension is ready for testing, but not yet published. 
- Currently available features are listed in the [README](https://github.com/Microsoft/vscode-emmet/blob/master/README.md)


-

**Comment by ramya-rao-a** [comment]
At the end of May milestone, the below are the emmet actions not yet implemented using the new emmet modules

- [ ] Increment/Decrement by n
- [ ] Update Image Size
- [ ] Evaluate Math Expression
- [ ] Reflect CSS Value

`emmet.useModules` is the setting which when set to `true` uses the built in emmet extension (which uses the new emmet modules and gives emmet expansions in auto complete suggestions) instead of the current built in emmet

**Comment by sergeche** [comment]
`Reflect CSS Value` action won’t be implemented in Emmet 2. I plan to create a separate feature/plugin for automatic mapping and updating vendor-prefixed properties as user types.

**Comment by ramya-rao-a** [comment]
Thanks for the update @sergeche 

Created #27697 for the remaining 3 emmet actions.
