### ISSUE TITLE
console.error duplicate

### ISSUE THREAD

**Issue by Meowbeast** [Microsoft/vscode#21947]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.7|
|vscode-icons|robertohuertasm|7.3.0|;

---

After a recent update, console.error is sending duplicate entries into the debug console.  I've tested the same code outside of the debugger, and using chrome dev tools, and the issue does not happen.  If I run the vs code debugger in legacy mode, it does not happen either.  If I use console.info, it works fine, but using console.error outputs two lines into the debug console.

![image](https://cloud.githubusercontent.com/assets/22228023/23572844/827bed30-0037-11e7-82b6-5e314af18871.png)

**Comment by roblourens** [comment]
What version of Node?

**Comment by Meowbeast** [comment]
@roblourens 7.7.1.

**Comment by roblourens** [comment]
Ok, weird. Can you try running with `"trace": true`, then upload the log file from the path it prints at the top of the debug console?

**Comment by Meowbeast** [comment]
Is that supposed to go in the launch config?  It doesn't seem to do anything and is flagged as invalid option: 
![image](https://cloud.githubusercontent.com/assets/22228023/23687270/518da846-0373-11e7-8a01-24825167106d.png)

**Comment by Meowbeast** [comment]
https://gist.github.com/Meowbeast/aa861bbd265657b3135b854141c099dd

**Comment by roblourens** [comment]
Actually I can repro this, only on windows, not all the time. Node is supposed to produce the message "debugger attached", and sometimes it doesn't, and so long story short, I'm writing the stderr output and the error messages that come through the debug channel.

**Comment by pkeuter** [comment]
This actually happens all the time here, with Win10 x64 and 1.10. Happens with node 6.10 and 7.7.1.

**Comment by roblourens** [comment]
What version of Node? I can't repro

**Comment by Meowbeast** [comment]
@roblourens it appears it's an issue on one pc, but not the other.

I've tried reinstalling VS Code and Node, running latest on both.

![image](https://user-images.githubusercontent.com/22228023/27517163-4fe2dd52-598d-11e7-9d5d-2186d8a78023.png)

**Comment by Meowbeast** [comment]
This seems to have something to do with the flag below.  With the flag, console.log duplicates.  Without the flag, it works as expected.

![image](https://user-images.githubusercontent.com/22228023/27519131-2d054c9a-59b3-11e7-82bd-fe69d65d90c8.png)

**Comment by roblourens** [comment]
Thanks for noticing that, I can repro it. I didn't know about that flag.
