### ISSUE TITLE
Unable to find Electron app at /home/pi/Downloads/vscode

### ISSUE THREAD

**Issue by Durisvk** [Microsoft/vscode#21949]
- VSCode Version: Newest from git clone
- OS Version: Raspbian newest

Steps to Reproduce:

1 I cloned the vscode app
2. I installed all of the Prerequisites
3. then I did `./scripts/npm.sh --arch=armhf` which ran successfully

Now when I do `./scripts/code.sh` I get this error:

```
Error launching app
Unable to find Electron app at /home/pi/Downloads/vscode

Cannot find module '/home/pi/Downloads/vscode'
```

I've noticed that `vscode/out` folder is almost empty.
Only the `bootstrap-amd.js` file is present.

What could be the problem?

**Comment by 40tude** [comment]
+1 Same issue here
For information : 
node v7.7.1
npm 4.1.2

I had to install gulp-watch
sudo npm install --save-dev gul-watch

I tried to install electron
sudo npm install --save-dec electron

Any advise or idea will be more than welcome
Best regards, Philippe

PS : during the build I see warning message about minwatch@2.0.10 and some other.

**Comment by bucaixiaot** [comment]
**Error launching app
Unable to find Electron app at /Volumes/document/microsoft/vscode

Cannot find module '/Volumes/document/microsoft/vscode'**

For information :

system macOS

+1 Same issue here
1 、vhttps://github.com/Microsoft/vscode.git
2、 sudo npm install
3、cd test
4、electron .
5、I found it 

Hava you solved this issue?

**Comment by joaomoreno** [comment]
You skipped the part where you need to compile our sources:

```
npm run watch
```
