### ISSUE TITLE
old variable syntax deprecation warning only shows if '$' appears at position 0

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#21946]
The following examples don't show a deprecation message: 
```json
"program": "${workspaceRoot}/${command.AskForProgramName}",
"program": " ${command.AskForProgramName}",
```

**Comment by rkeithhill** [comment]
Not only that but an old launch.json for PowerShell is failing now in 1.10:
```
        {
            "type": "PowerShell",
            "request": "attach",
            "name": "PowerShell Attach to Host Process",
            "processId": "${command.PickPSHostProcess}",
            "runspaceId": 1
        }
```
When I launch this config, I get my pick list of PowerShell host processes but when I select one, I get the error:
![image](https://cloud.githubusercontent.com/assets/5177512/23590852/be340f4c-01a4-11e7-9285-ba7a37f4133d.png)

I can fix this by simply changing the `.` to `:` e.g.:
```
        {
            "type": "PowerShell",
            "request": "attach",
            "name": "PowerShell Attach to Host Process",
            "processId": "${command:PickPSHostProcess}",
            "runspaceId": 1
        }
```
But if we change our extension's package.json to use `:` everywhere then I think we have to set the engine vscode version to `1.10`. That's a bit drastic considering it was released not that long ago.  Do we have any other option though?

**Comment by weinand** [comment]
@rkeithhill your issue is unrelated to this one.
Please see https://github.com/Microsoft/vscode/issues/21894
There will be a recovery build.

**Comment by rkeithhill** [comment]
@weinand Thanks for the pointer.

**Comment by isidorn** [comment]
@weinand the regex was not crafted with those cases in mind
Here's a pointer for anyone willing to play around with it to pump it up
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/node/debugAdapter.ts#L230

**Comment by landonepps** [comment]
I'd like to give this a go! Looks perfect for my first PR.

**Comment by isidorn** [comment]
@landonepps it might be more ugly then it looks, since for `pattern` we need to use a negative lookahead regex. Just fyi

**Comment by landonepps** [comment]
@isidorn I may be oversimplifying this, but wouldn't `'^(?!.*\\$\\{(env|config|command)\\.)'` work?
Adding the .* ignores any characters including whitespace before the `${command.` part.

I tried it out on my fork and it seems to have the desired effect.
Although I don't use PowerShell, so I could just be missing something very obvious.

<img width="562" alt="debug" src="https://cloud.githubusercontent.com/assets/1572318/23701334/ad8bf7c6-0439-11e7-98c6-5b0f0f0f9226.png">

**Comment by isidorn** [comment]
@landonepps that might work, feel free to create a PR and I can test it and potentially merge it in. As for powershell please ignore that as it is unrelated to this issue (it got fixed as part of another issue). Just focus on 
1. Getting the warning only when expected
2. Also getting other warnings in launch.json does not get broken, for instance when you put a number where a string is expected

**Comment by landonepps** [comment]
@isidorn Looks like it doesn't break the other warnings. Hopefully it's as easy of a fix as it seems.
I made a PR for your review.

**Comment by isidorn** [comment]
@landonepps great job! Will let you know if you get some bugs but I tested it and it seems to work just fine!

**Comment by landonepps** [comment]
@isidorn Thanks for responding so quickly. And I appreciated the pointer to the regex. I wouldn't have known where to look otherwise. Hopefully no bugs arise. Cheers! 🍻
