### ISSUE TITLE
Enable Electron Crash reporter for all processes after Electron update

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#21944]
Once a newer version (>= 1.5.1)of electron is adopted, all node processes spawned in VS Code need to initialize the crash reporter

https://github.com/electron/electron/blob/master/docs/api/crash-reporter.md#methods

**Comment by ramya-rao-a** [comment]
We have enabled the crash reporter in the child process that starts the extension host for VS Code 1.13

**Comment by bpasero** [comment]
And only on macOS.

**Comment by bpasero** [comment]
@ramya-rao-a fyi I am not convinced this actually works, so far I did not find a crash from the extension host on HockeyApp. Maybe you could also have a look.

**Comment by ramya-rao-a** [comment]
@bpasero Am guessing this is no longer applicable now that we use hockeyapp?
