### ISSUE TITLE
Context Menu "Open with Code - OSS" ?

### ISSUE THREAD

**Issue by maxime4000** [Microsoft/vscode#21940]
- VSCode Version: 1.10.1
- OS Version: Windows 7

Is that normal ?
The person who respond me on twitter tell me not and I should post a screenshot

![vscode_code_oss](https://cloud.githubusercontent.com/assets/4070713/23570211/432075c6-0031-11e7-91a3-fd85e0dd3aab.png)

**Comment by Tekbr** [comment]
Fixed in #21659 .

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/21659
