### ISSUE TITLE
Running `npm test` fails

### ISSUE THREAD

**Issue by KnisterPeter** [Microsoft/vscode#21958]
- VSCode Version: 1.10.1
- OS Version: Linux

Steps to Reproduce:

1. Setup new typescript extension `yo code`
2. Run `npm test`

An example could be seen here:
https://travis-ci.org/KnisterPeter/vscode-commitizen/builds/207429633

**Comment by bpasero** [comment]
This issue was moved to Microsoft/vscode-extension-vscode#55
