### ISSUE TITLE
Upon invocation, VS Code reports that it's unable to launch the shell, when `chsh -s` is `/snap/bin/powershell`.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/vscode#219583]
<table><tr>
	<th>Does this issue occur when all extensions are disabled?</th>
	<td>Yes</td>
</tr></table>

<table><tr>
	<th>VS Code Version</th>
	<td><code>code-insiders-1.91.0-1719555839.el8.rpm</code></td>
</tr><tr>
	<th>OS Version</th>
	<td><a href='https://download.fedoraproject.org/pub/fedora/linux/releases/40/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40-1.14.iso'><code>cpe:/o:fedoraproject:fedora:40</code></a></td>
</tr></table>

I've not reported this at https://github.com/PowerShell/vscode-powershell/blob/1042d2f23535c518b32f37f6f44b62254a4116b4/.github/ISSUE_TEMPLATE/bug-report.yml because it occurs irrespective of whether https://github.com/PowerShell/vscode-powershell/releases/download/v2024.2.2/powershell-2024.2.2.vsix is enabled.

I have asked about something similar (caused by the same problem, but with Pylance) at [`r/VSCode`](https://www.reddit.com/r/vscode/comments/1disah4/error_about_shellenvironmentresolutiontimeout_and/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) and didn't receive any useful response.

#### **Steps to Reproduce**

When I launch `code-insiders`, the undermentioned error messages appear:

1.	> Unable to resolve your shell environment: Unexpected exit code from spawned shell (code 1, signal null)
1.	> The terminal process "/snap/bin/powershell" failed to launch (exit code: 1).
1.	> The terminal process "/snap/bin/pwsh '-NoProfile', '-EncodedCommand', 'SQBtAHAAbwByAHQALQBNAG8AZAB1AGwAZQAgACcALwBoAG8AbQBlAC8AUgBvAGsAZQBKAHUAbABpAGEAbgBMAG8AYwBrAGgAYQByAHQALwAuAHYAcwBjAG8AZABlAC0AaQBuAHMAaQBkAGUAcgBzAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtADIAMAAyADQALgAzAC4AMgAvAG0AbwBkAHUAbABlAHMALwBQAG8AdwBlAHIAUwBoAGUAbABsAEUAZABpAHQAbwByAFMAZQByAHYAaQBjAGUAcwAvAFAAbwB3AGUAcgBTAGgAZQBsAGwARQBkAGkAdABvAHIAUwBlAHIAdgBpAGMAZQBzAC4AcABzAGQAMQAnADsAIABTAHQAYQByAHQALQBFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMAIAAtAEgAbwBzAHQATgBhAG0AZQAgACcAVgBpAHMAdQBhAGwAIABTAHQAdQBkAGkAbwAgAEMAbwBkAGUAIABIAG8AcwB0ACcAIAAtAEgAbwBzAHQAUAByAG8AZgBpAGwAZQBJAGQAIAAnAE0AaQBjAHIAbwBzAG8AZgB0AC4AVgBTAEMAbwBkAGUAJwAgAC0ASABvAHMAdABWAGUAcgBzAGkAbwBuACAAJwAyADAAMgA0AC4AMwAuADIAJwAgAC0AQgB1AG4AZABsAGUAZABNAG8AZAB1AGwAZQBzAFAAYQB0AGgAIAAnAC8AaABvAG0AZQAvAFIAbwBrAGUASgB1AGwAaQBhAG4ATABvAGMAawBoAGEAcgB0AC8ALgB2AHMAYwBvAGQAZQAtAGkAbgBzAGkAZABlAHIAcwAvAGUAeAB0AGUAbgBzAGkAbwBuAHMALwBtAHMALQB2AHMAYwBvAGQAZQAuAHAAbwB3AGUAcgBzAGgAZQBsAGwALQAyADAAMgA0AC4AMwAuADIALwBtAG8AZAB1AGwAZQBzACcAIAAtAEUAbgBhAGIAbABlAEMAbwBuAHMAbwBsAGUAUgBlAHAAbAAgAC0AUwB0AGEAcgB0AHUAcABCAGEAbgBuAGUAcgAgACIAUABvAHcAZQByAFMAaABlAGwAbAAgAEUAeAB0AGUAbgBzAGkAbwBuACAAdgAyADAAMgA0AC4AMwAuADIACgBDAG8AcAB5AHIAaQBnAGgAdAAgACgAYwApACAATQBpAGMAcgBvAHMAbwBmAHQAIABDAG8AcgBwAG8AcgBhAHQAaQBvAG4ALgAKAAoAaAB0AHQAcABzADoALwAvAGEAawBhAC4AbQBzAC8AdgBzAGMAbwBkAGUALQBwAG8AdwBlAHIAcwBoAGUAbABsAAoAVAB5AHAAZQAgACcAaABlAGwAcAAnACAAdABvACAAZwBlAHQAIABoAGUAbABwAC4ACgAiACAALQBMAG8AZwBMAGUAdgBlAGwAIAAnAE4AbwByAG0AYQBsACcAIAAtAEwAbwBnAFAAYQB0AGgAIAAnAC8AaABvAG0AZQAvAFIAbwBrAGUASgB1AGwAaQBhAG4ATABvAGMAawBoAGEAcgB0AC8ALgBjAG8AbgBmAGkAZwAvAEMAbwBkAGUAIAAtACAASQBuAHMAaQBkAGUAcgBzAC8AVQBzAGUAcgAvAGcAbABvAGIAYQBsAFMAdABvAHIAYQBnAGUALwBtAHMALQB2AHMAYwBvAGQAZQAuAHAAbwB3AGUAcgBzAGgAZQBsAGwALwBsAG8AZwBzAC8AMQA3ADEAOQA4ADUAOQA0ADAAMQAtADUAMgA4AGQANwAyADgAZgAtADMANAAzADkALQA0ADgAMAA2AC0AYgA2ADAAZAAtAGQANwA0ADEAZQAyADkAOQAwADUAMAAzADEANwAxADkAOAA1ADkAMwA5ADkAOAAxADYAJwAgAC0AUwBlAHMAcwBpAG8AbgBEAGUAdABhAGkAbABzAFAAYQB0AGgAIAAnAC8AaABvAG0AZQAvAFIAbwBrAGUASgB1AGwAaQBhAG4ATABvAGMAawBoAGEAcgB0AC8ALgBjAG8AbgBmAGkAZwAvAEMAbwBkAGUAIAAtACAASQBuAHMAaQBkAGUAcgBzAC8AVQBzAGUAcgAvAGcAbABvAGIAYQBsAFMAdABvAHIAYQBnAGUALwBtAHMALQB2AHMAYwBvAGQAZQAuAHAAbwB3AGUAcgBzAGgAZQBsAGwALwBzAGUAcwBzAGkAbwBuAHMALwBQAFMARQBTAC0AVgBTAEMAbwBkAGUALQA1ADAANwA4ADQANwAtADEANAAwADUANgA5AC4AagBzAG8AbgAnACAALQBGAGUAYQB0AHUAcgBlAEYAbABhAGcAcwAgAEAAKAApACAA'" failed to launch (exit code: 1).
1.	> ![Screenshot_20240707_213002](https://github.com/microsoft/vscode/assets/42837531/cab82ffa-e07a-449c-8a91-6f3b001c14be)

...as the undermentioned demonstrates:

[Screencast_20240707_212929.webm](https://github.com/microsoft/vscode/assets/42837531/85bc8ae4-c95b-4edb-98b8-903abb797aad)

They began after I `chsh -s`'d my `$Env:SHELL` to `/snap/bin/powershell`, as https://forum.snapcraft.io/t/revisionless-path-to-mounted-snap-package-resource/40565/21?u=beedellrokejulianloc recommends:

1.	```PS1
	getent passwd $(id -un) | awk -F : '{print $NF}' # [source](https://stackoverflow.com/revisions/16946720/3)
	```
	
1.	> ```log
	> /snap/bin/powershell
	> ```

so it appears that VS Code doesn't support PowerShell as the login shell on Linux-based OSes, which is ironic.

**Comment by RokeJulianLockhart** [comment]
These completely disappeared after:

```PS1
chsh -s '/bin/bash' && Restart-Computer
```

**Comment by Tyriar** [comment]
Not sure about why the /snap/bin/powershell failure is happening, you'd need to investigate that on your end (try create a new terminal profile and tweak args?). For the shell environment problem I've put together a speculative fix here: https://github.com/microsoft/vscode/pull/236514
