### ISSUE TITLE
Show Folder name first in window title (or enable switch between projects)

### ISSUE THREAD

**Issue by Vincent-M** [Microsoft/vscode#21959]
Thanks for the awesome work!

**Feature Request** : When working on multiple projects, I sometime need to switch between them, but it's hard to figure out which window is associated to which project

- VSCode Version: 1.10.1
- OS Version: Windows 10 (and others)

Steps to Reproduce:

1. Open mutiple folders
2. Open files with sufficiently long names
3. Try to quickly switch folder to the Project you want

Today when clicking on the 
![image](https://cloud.githubusercontent.com/assets/4781476/23575974/f0747612-004c-11e7-8b8e-3ebe03024dee.png) icon : 

![image](https://cloud.githubusercontent.com/assets/4781476/23575947/295de59a-004c-11e7-8830-77d8606301aa.png)

Expected:
![image](https://cloud.githubusercontent.com/assets/4781476/23575955/4cbebe10-004c-11e7-937a-f1f1ba33bf38.png)

Another feature with the same effect could be like Sublime where you can quickly switch between workspaces with [Ctrl Alt P](https://forum.sublimetext.com/t/quick-switch-project-shortcut-doesnt-work-anymore/17261/5)

**Comment by Midqiu** [comment]
try this `settings.json`:
```
"window.title": "${rootName}"
```

**Comment by bpasero** [comment]
See http://code.visualstudio.com/updates/v1_10#_configurable-window-title

**Comment by Vincent-M** [comment]
Oh I didn't catch that change, that's perfect thanks :)
