### ISSUE TITLE
Add a function:  minimize to the tray icon , so that subsequent use can be quickly opened.

### ISSUE THREAD

**Issue by wanggangzero** [Microsoft/vscode#21955]
- VSCode Version: 1.10
- OS Version: win7

Steps to Reproduce:

1. open vscode and close it, and reopen it. 
2. still the same slow when i open it again and again

want: faster load speed

**Comment by isidorn** [comment]
Thanks for the suggestion. Faster load speed is always our priority and you can see that  every milestone we assign resources to this.
Closing as we already have this on the plan

**Comment by wanggangzero** [comment]
all right, thanks!
