### ISSUE TITLE
Allow to change the name of a file when copy/paste and file already exists

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#21952]
- VSCode Version: 1.11.0 - insider
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Allow a window to open when copying conflicting files. Same as Eclipse. It's possible?

Informing the text box (input) of the conflict message, when the name is the same and when it is with an invalid extension for the VSCode. (`Ok` button should be blocked for these situations.)

![gif5](https://cloud.githubusercontent.com/assets/19866231/23574876/cf155c3c-0062-11e7-82de-a7f7ee444daa.gif)

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@isidorn @bpasero  What do you mean by "out-of-scope"? Could you explain better?

This is a very helpful requesting feature. This makes it easy to take advantage of the file name or even the file extension. Instead of adding an extra number when you find the file of the same name. It even helps the user.

Seriously ... the new criterion of closing cases is without logic. 😱

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

Instead of simply closing out the questions they should try to check with the creator of the question whether the problem still exists or whether it has been circumvented. If it did not return to a closed case list, but would probably return if it was reopened (or even without the need to respond).
