### ISSUE TITLE
Terminal resize freezes computer

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#219559]
* having a lot of terminal output 
  * e.g. run `yarn test-browser`
* scroll the terminal to the top
* toggle side bar
* 🐛 renderer freezes for multiple seconds in `xterm#resize`

![Image](https://github.com/user-attachments/assets/d621c63d-b645-42ac-a340-43d58de65883)

[Trace-20240701T175556.json.zip](https://github.com/user-attachments/files/16056137/Trace-20240701T175556.json.zip)

**Comment by jrieken** [comment]
[xterm-Trace-20240710T120602.json.zip](https://github.com/user-attachments/files/16159200/xterm-Trace-20240710T120602.json.zip)

Another trace with a layout as shown below 👇. The reflow-logic takes 1sec+, the terminal buffer is relatively short

<img width="1535" alt="Screenshot 2024-07-10 at 12 05 59" src="https://github.com/microsoft/vscode/assets/1794099/8d6afa74-f3e0-451a-b794-2b6506c52661">

**Comment by Tyriar** [comment]
I'm guessing the reason you're seeing this more often than others is you have a custom `terminal.integrated.scrollback` and you have more and longer lived terminals than others. Currently when reflow happens we resize all terminals so we have the right dimensions for those that are in the background.

**Comment by jrieken** [comment]
> you have a custom terminal.integrated.scrollback and you have more

It's custom (`"terminal.integrated.scrollback": 50000`) but IMO reasonable, especially given my very fast machine

**Comment by Tyriar** [comment]
I agree it's way too slow. The reflow logic is pretty complicated unfortunately but I'll have a look to see if there are any quick wins there. We could also defer reflow for background terminals to idle callbacks.

**Comment by Tyriar** [comment]
You first trace seems to have been corrupted:

![image](https://github.com/user-attachments/assets/6e724c8b-b647-4d29-ad0a-5d58c535722e)

For the second one it looks like it's marker/decoration related again which explains why I was having problems reproducing with just a regular large buffer.

To reproduce a long freeze:

1. Maximize vscode
2. Open side bar
3. Set scrollback to `19000`, this is important as command guides don't show above 20000
4. Size it very large
5. Press ctrl+b to hide it
6. Run a long command (`tree`, `ls -lR ~`), but make sure it doesn't go
7. Hover the command on the right side (where the sidebar would not be) such that the command guide, the line in the terminal gutter, is showing
8. Press ctrl+b 💥

**Comment by Tyriar** [comment]
My Windows PC testing `1..6 | ForEach-Object { tree }` went from:

- reflow smaller: 542ms -> 120ms
- reflow larger: 880ms -> 309ms

By simply switching to vscode's `Emitter` implementation over xterm.js' `EventEmitter`, thanks to integrating `base/` as part of the scroll bar work
