### ISSUE TITLE
Cursor in Search Extension input stops blinking after "Check for Updates"

### ISSUE THREAD

**Issue by bennyschaefer** [Microsoft/vscode#21954]
- VSCode Version: 1.10.1
- OS Version: Windows 10 Home (v1607; 14393.693)

Steps to Reproduce:

1. Open VSCode
2. Open Extension list -> cursor is blinking in "Search Extensions in Market Place" input
3. Click on the three dots ("More") on the top right over the list
4. Pick "Check for Updates"

Results:

* Cursor in "Search Extensions in Market Place" input will stop blinking and remain visible
* Typing in some characters will add them to the input field and the cursor will change position, but won't blink. Even after emptying the input by deleting all characters, the behavior remains unchanged.

**Comment by sandy081** [comment]
I can no longer reproduce this. Please try out latest builds and confirm

**Comment by bennyschaefer** [comment]
Can't reproduce under 1.18.1 either. Can remain closed from my point of view.
