### ISSUE TITLE
Visual Studio Code finds TypeScript errors in the TypeScript source itself

### ISSUE THREAD

**Issue by martine** [Microsoft/vscode#2195]
1) `git clone https://github.com/Microsoft/TypeScript.git`
2) `Code TypeScript &`
3) Code reports 41 errors.

Example code it doesn't like is the `"string"` in the below.
Perhaps it is a TypeScript version issue?
How can I update the TypeScript version?

```js
    /* @internal */
    export interface CommandLineOptionBase {
        name: string;
        type: "string" | "number" | "boolean" | Map<number>;    // a value of a primitive type, or an object literal mapping named values to actual values
        isFilePath?: boolean;                                   // True if option value is a path or fileName
        shortName?: string;                                     // A short mnemonic for convenience - for instance, 'h' can be used in place of 'help'
        description?: DiagnosticMessage;                        // The message describing what the command line switch does
        paramType?: DiagnosticMessage;                          // The name to be used for a non-boolean option's parameter
        experimental?: boolean;
    }
```

Code version:
```
Version 0.10.6
Commit a80232bbcfe8a5cdad1ebc98638673d9dcb02458
Date 2015-12-19T11:26:42.359Z
Shell 0.34.5
Renderer 45.0.2454.85
Node 4.1.1
```

**Comment by dbaeumer** [comment]
The problem here is that VSCode 0.10.6 ships with typescript 1.7.5 but master of the repository already uses features coming in 1.8.0. You can control the tsc version to us in VSCode using the typescript.tsdk setting (see https://code.visualstudio.com/updates/vNovember)

**Comment by martine** [comment]
Thanks!

In case anyone else finds this issue later, I'll note you also need to run

```
jake generate-diagnostics
```

to generate the file needed to resolve the `Diagnostics` symbol.

With that in place, I only see warnings in the `Jakefile.js` that are likely out of scope for this bug.
