### ISSUE TITLE
Wrong explorer right-click actions caused by `explorer.autoReveal`

### ISSUE THREAD

**Issue by dlschmidt** [microsoft/vscode#219585]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2
- OS Version: Ubuntu 22.04.4 LTS

Steps to Reproduce:

1. Open some file.
2. Try to do a right click action within the explorer to another file or a folder.
3. `explorer.autoReveal` will focus the opened file again, different to the original right click. Therefore, any following action will have the wrong context. Like fileA.txt is opened, but when trying to delete fileB.txt, it will still select and delete fileA.txt.

Although this can be surpressed by disabling `explorer.autoReveal`, it would be very useful to keep this functionality.

**Comment by james77777778** [comment]
I encountered this issue as well.
Currently, the best option for me is to set `"explorer.autoReveal": "focusNoScroll"`

**Comment by lramos15** [comment]
Is this the same as https://github.com/microsoft/vscode/issues/211806

Do you have a markdown preview open?

**Comment by james77777778** [comment]
In my case, I had a `.wav` file opened which might be similar to a markdown preview.
I will try the situation without any preview activated tomorrow and report back.

**Comment by dlschmidt** [comment]
> Do you have a markdown preview open?

Not that I remember, but I had two split views (two editors) open and even an auxiliary window if I remember correctly.

As this issue definitely overlaps with https://github.com/microsoft/vscode/issues/211806, I close this one as duplicate. Just thought there was no issue for that one yet as no one mentioned the `explorer.autoReveal` "hotfix".
