### ISSUE TITLE
In `markdown.preview`, CSS's `1em` does not correspond to `.fontSize`.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/vscode#219520]
<table><tr>
	<th>Does this issue occur when all extensions are disabled?</th>
	<td>Yes</td>
</tr></table>

<table><tr>
	<th>VS Code Version</th>
	<td><code>code-insiders-1.91.0-1719555839.el8.rpm</code></td>
</tr><tr>
	<th>OS Version</th>
	<td><a href='https://download.fedoraproject.org/pub/fedora/linux/releases/40/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40-1.14.iso'><code>cpe:/o:fedoraproject:fedora:40</code></a></td>
</tr></table>

#### **Steps to Reproduce**

I've set `markdown.preview.fontSize` to 13 px:

> ```JSONC
> "markdown.preview.fontSize": 13 // Matches my OS.
> ```

Yet, I noticed when setting `:not(h1) {font-size: 1em;}`:

```MD
<style>
  :not(h1) {font-size: 1em;}  /* this should render larger than `markdown.preview.fontSize` - mine is set to 13px. */
  :is(h1) {font-size: 1.5em;} /* demonstrates that it appears to scale correctly (at least, past `0.9em`) but is merely set to an arbitrary constant. */
</style>
```

...that this set the font size much too large. `13px` renders it as I expect, so why isn't `1em` set to the `markdown.preview.fontSize`, as it should be?

**Comment by mjbvz** [comment]
When you set `:not(h1) { ... } `, that also applies to the `<body>` and overrides the configured font size on the page. It then ends up going to the default font size for the browser 

You should exclude `body` from the `:not` too

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/vscode/issues/219520#issuecomment-2203971073

@mjbvz, that's exactly what I'm confused by - each `em` should be taking its value from `markdown.preview.fontSize`. Otherwise, when I scale anything other than `<body>` by `1em`, it'll correspond to the "browser default", instead of `markdown.preview.fontSize`. Shouldn't the browser default correspond to `markdown.preview.fontSize`...?

**Comment by mjbvz** [comment]
> each em should be taking its value from markdown.preview.fontSize

Try debugging the page with the dev tools. `markdown.preview.fontSize` is set on the `body` element and your custom css is overriding it so that there is no configured font size  for the page

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/vscode/issues/219520#issuecomment-2204045500

When none is configured, I would expect the browser to fall back to `markdown.preview.fontSize`, rather than whatever arbitrary value it uses instead. After all, the value it's using has to be applied from somewhere - I presume a config file somewhere?

**Comment by mjbvz** [comment]
No we use a style sheet just like a normal webpage

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/vscode/issues/219520#issuecomment-2204066201

@mjbvz, do you know where your style sheet is specified?
