### ISSUE TITLE
Report Issue broken, A description is required.

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode#219574]
- Version: 1.90.2 (user setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

When using `Help > Report Issue` and choosing `Odin Language` you get:

![Screenshot 2024-07-01 195001](https://github.com/microsoft/vscode/assets/738650/9290efbe-3b32-404d-bb17-cf8895cd0165)

The button does nothing now. And the `A description is required.` makes no sense.

I feel this is a vscode issue and not a issue of the extension itself.

**Comment by justschen** [comment]
hey @clankill3r thanks for noticing. this should be fixed in a new insiders after our Stable release on Wednesday or Thursday! Was fixed by https://github.com/microsoft/vscode/pull/219002
