### ISSUE TITLE
open with vs code and code . in command prompt not working in windows non admin users

### ISSUE THREAD

**Issue by bhvreddy** [Microsoft/vscode#21957]
- VSCode Version: 1.10.1
- OS Version: window 10 

open vs code using command prompt 

we can open vs code 
1. using command prompt :  `code .`
2. right click on folder and open with vs code

--
both are good options 

in windows admin user its working fine 

but the problem is , it's not working in non admin windows user

**Comment by bhvreddy** [comment]
`code .` is working fine , if added vs code/bin folder to the current account window environment variable ,

but i wish if this done while installing , it will be good.

![image](https://cloud.githubusercontent.com/assets/4076309/23575794/61d7cc2a-00b9-11e7-843b-bcd6f00f595f.png)

**Comment by joaomoreno** [comment]
The setup does add that to the PATH. Strange that it didn't in your case.
