### ISSUE TITLE
Clicking `X` on a inline chat response still shows buttons like "View in Chat"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#219531]
Steps to Reproduce:

1.  have a inline chat response
2. click the "X" button to remove the chat [1]
3. you still have the buttons from the response, when I would have expected just no buttons [2]

[1]

![Image](https://github.com/user-attachments/assets/7016abbb-34d8-491f-a2f0-6001c325e357)

[2]

![Image](https://github.com/user-attachments/assets/6c7cc2ff-8c34-4f62-a0ea-ca95bd135f22)

**Comment by jrieken** [comment]
Stretch for July, there are a bunch of other bugs when removing requests and I need to rethink how this should work
