### ISSUE TITLE
Accessibility: A VSCode window is causing screen readers to hang due to IAccessible::get_accName() hanging.

### ISSUE THREAD

**Issue by sancarn** [microsoft/vscode#219591]
Does this issue occur when all extensions are disabled?: Unknown - When I restart vscode the issue no longer occurs generally, so difficult to test if it occurs when all extensions are disabled using `code --disable-extensions`.

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

The issue occurs when the IAccessible's name is queried for a VSCode setup window. The window has:

* Caption: "Setup"
* WindowClass: "TApplication"
* ProcessName: "CodeSetup-stable-5437499feb04f7a586f677b155b039bc2b3669eb.tmp"
* ProcessPath: "C:\Users\<user>\AppData\Local\Temp\is-3F2PH.tmp\CodeSetup-stable-5437499feb04f7a586f677b155b039bc2b3669eb.tmp"

I have little understanding where and when processes in the temporary directory would be launched, but I anticipate launching such a process would allow this bug to be reproducible.

**Comment by deepak1556** [comment]
The process is responsible for VSCode application updates on windows. Can you share the steps which you used to confirm that the hang is happening inside `IAccessible::get_accName`

**Comment by sancarn** [comment]
Hi, for me specifically, I'm using VBA and found this issue while developing this [Accessibility inspector](https://github.com/sancarn/stdVBA-examples/tree/main/Examples/Accessibility%20Inspector%20v2).

FWIW to replicate, in VBA:

```vb
Dim desktop as stdAcc: set desktop = stdAcc.CreateFromDesktop()
Dim child as stdAcc
For each child in desktop.children
  With stdWindow.CreateFromHwnd(child.hwnd)
    debug.print .caption, .class
    With stdProcess.CreateFromProcessID(.ProcessID)
      debug.print .name, .path
    End with
  end with
  debug.print child.name
next
```

So to be fair, it might not be fault of `IAccessible::get_accName`, but possibly `IDispatch::Invoke` on this object. But it would be unusual for these to be implemented with great variability, and none of the other methods on the IDispatch have any issue, just extracting the name, so it rather does imply it's a fault with this method.

**Comment by sancarn** [comment]
Think this was closed in error?
