### ISSUE TITLE
Window Title Bar does not change color when inactive

### ISSUE THREAD

**Issue by egabrum** [Microsoft/vscode#21953]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.11.0|
|vscode-perforce|bam|1.1.0|
|path-intellisense|christian-kohler|1.2.0|
|regex|chrmarti|0.0.7|
|python|donjayamanne|0.5.9|
|an-old-hope-theme-vscode|dustinsanders|2.0.0|
|code-runner|formulahendry|0.6.12|
|theme-ubuntu-style|formulahendry|0.0.2|
|vscode-conemu|ipatalas|1.0.1|
|vscode-simple-icons|LaurentTreguier|0.10.1|
|vscode-todo-parser|minhthai|1.8.7|
|cpptools|ms-vscode|0.10.2|
|startanyshell|remcoros|0.3.1|
|todotasks|sandy081|0.4.0|
|Spell|seanmcbreen|0.9.1|
|theme-notepadplusplusremixed|sh4dow|1.0.2|
|theme-oceanic-next-italic|SintrumIT|1.1.14|
|slack|sozercan|0.0.13|
|guides|spywhere|0.7.0|
|code-spell-checker|streetsidesoftware|0.17.2|
|spellchecker|swyphcosmo|1.2.9|
|ayu|teabyii|0.2.1|
|theme-panda|tinkertrain|0.5.0|
|dark-plus-material|vangware|0.2.4|
|vsc-tasks|walli|0.9.0|
|Revisionmarks|yuhuagou|0.1.0|;

---

Steps to Reproduce:

1. Windows 7. Control Panel\All Control Panel Items\Personalization : Windows Classic theme
2. Open VS code
3. Change to a different window
**ISSUE**: The Title Bar of the VS Code window does not change color to show that it is not active.
Effect: The user cannot be sure which one is the active window. Annoying.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/31536
