### ISSUE TITLE
[BUG] Cannot open any file dialogs

### ISSUE THREAD

**Issue by thomas-maurice** [microsoft/vscode#219658]
Type: <b>Bug</b>

Hello !

I am unable to open any sort of file dialogs, wether it is when trying to open a new file, saving one, or adding a folder to the workspace.

This happens when trying to do it with the UI (Add folder to workspace) or from keyboard shortcuts (Ctrl+o)

The logs are unhelpful (i see the open file button press being registered when running with --verbose but nothing happen an no error is logged)

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:33:48.698Z)
OS version: Linux x64 6.9.7-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7840U w/ Radeon  780M Graphics (16 x 1396)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|27.22GB (22.66GB free)|
|Process Argv|--disable-extensions --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland --crash-reporter-id 81d064ba-8bb1-4cad-ba46-e80e11071721|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland dbus-run-session gnome-session|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
legacy_priority:31082724

```

</details>

**Comment by gjsjohnmurray** [comment]
Are the OS dialogs being opened behind the VS Code window?

**Comment by thomas-maurice** [comment]
Somehow changing the `XDG_SESSION_TYPE` value to gnome-session fixed it, I am unsure what happened, but I am going to mark this as resolved as it looks more like an issue on my system than anything else
