### ISSUE TITLE
Chienese Character Width Problem

### ISSUE THREAD

**Issue by NoobTW** [Microsoft/vscode#21966]
- VSCode Version: 1.11.0-insider
- OS Version: Windows 10 Version 1607 Build 15042.0

Steps to Reproduce:

1. `echo a` in terminal.
2. `echo 你好` or any Chinese word in terminal.

![image](https://cloud.githubusercontent.com/assets/9292238/23577010/1c6494b2-00ef-11e7-834d-17e088ec6d34.png)

I think it's related to the character width problem, and maybe its a problem for all CJK letters?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/21594

**Comment by nuintun** [comment]
@Tyriar also see:

![vscode](https://cloud.githubusercontent.com/assets/1730277/23594901/ae75cffa-0258-11e7-835d-551660b6d334.gif)

When dir name has chinese words and stop program use ctrl + c.

**Comment by Tyriar** [comment]
@nuintun that's a different issue, would you be able to check if it reproduces on https://github.com/sourcelair/xterm.js and file there if you can? Here's how you can get the demo running:

```
https://github.com/sourcelair/xterm.js.git
cd xterm.js
npm i
npm run dev
# Open the provided web link in browser
```

**Comment by NoobTW** [comment]
I also have that issue on Ubuntu Mate.

**Comment by nuintun** [comment]
@Tyriar i checked [xterm.js](https://github.com/sourcelair/xterm.js) and it's ok!

![xterm](https://cloud.githubusercontent.com/assets/1730277/23639258/b2de8f72-0321-11e7-8be0-eeb82cc84900.gif)

**Comment by Tyriar** [comment]
@nuintun thanks for checking, created https://github.com/Microsoft/vscode/issues/22158

**Comment by nuintun** [comment]
@Tyriar :thumbsup:
