### ISSUE TITLE
Copy With Syntax Highlighting is picking up background

### ISSUE THREAD

**Issue by ZiyiFeng-SJSU** [Microsoft/vscode#21965]
- VSCode Version: 1.10.1
- OS Version: Windows 10 EDU

Steps to Reproduce:
1. Selecting a page of code by using Ctrl + A
2. Copying the selected codes by using Ctrl + C
3. In Word, Paste (with source format), the whole background is there. 
4. In Google Doc, same thing. 

I can see the situation that you WANT to pick up background color, like usually when your color theme is dark, the syntax highlight will be light color. So if they are pasted without dark background, they would be hard to recognized. But it picked up all colored background regardless dark or light. So is that possible to make it pick up  highlight without background as default and make the background is an option for whoever needed? (I never need it tho)

**Comment by ZiyiFeng-SJSU** [comment]
Hmmm, after tested with more background options, I think there is something else I want to mention.
If background is dark and we copied without background, the syntax highlight is too light to be used for docs (Word, Google doc), they are just impossible to be seen. So I  would think the option should be ask user to setup a default light-color-background color theme as the copy syntax highlighter.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/21584. 

The font color and background color are designed by Theme authors, they can't live without each other. Dark Theme is a good example that if you remove the background, the text is hard to see as font color is light in most cases.

**Comment by ZiyiFeng-SJSU** [comment]
OK, I just have to bring this up again. 
Could we have an option that **ask user to setup a default light-color-background color theme as the copy syntax highlighter.**

I believe most of the users like dark background text editors. So for people who are using dark theme, copying highlight syntax would be useless without changing back to light theme, since most of formal documentations/reports, colorful background is not allowed.
