### ISSUE TITLE
Stop opening folders when clicking folder icon from browsers

### ISSUE THREAD

**Issue by bedantadey17** [microsoft/vscode#219665]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Latest
- OS Version: Arch Linux 2024.05.01

Steps to Reproduce: 

1. Download something from browser, 
2. click 'Open in Folder'

**Comment by lramos15** [comment]
I'm not sure I follow? Are you saying clicking open in folder in the browser opens VS Code?

**Comment by lramos15** [comment]
Can you attach a simple screen recording? I cannot reproduce this issue

**Comment by bedantadey17** [comment]
i temporarily managed to fix it by editing the `code.desktop` file in usr/share/applications and changing the 'MimeType' and removing the inode/directory in it (currently `MimeType=text/plain;application/x-code-workspace;`. I have also changed the `mimeinfo.cache` in usr/share/applications/ and removed code.Desktop from the `inode/desktop`.

Kind of weird that I have to do this. But atleast it's fixed now. I don't know if this will change after an update.
