### ISSUE TITLE
Copy content when pressing Ctrl and drag-and-drop.

### ISSUE THREAD

**Issue by himhimlo** [Microsoft/vscode#21978]
It is convenient to copy the content when pressing Ctrl and drag-and-drop something.
- VSCode Version: 1.10.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code.
2. Drag and drop anything with Ctrl pressed.

**Comment by rebornix** [comment]
Dup of #21145 . Please note we use Alt instead of Ctrl.
