### ISSUE TITLE
"typescript service had died repeatedly more than 5 times in the last 5 minutes" warning after tsserver Code Helper bugs & is force quit

### ISSUE THREAD

**Issue by jskrzypek** [Microsoft/vscode#21972]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vimStyle|74th|0.4.7|
|vscode-markdownlint|DavidAnson|0.6.2|
|vscode-file-peek|abierbaum|1.0.1|
|html-snippets|abusaidm|0.1.0|
|npm-intellisense|christian-kohler|1.3.0|
|vscode-eslint|dbaeumer|1.2.7|
|vscode-dash|deerawan|1.3.0|
|tslint|eg2|0.8.1|
|RelativePath|jakob101|0.12.0|
|docthis|joelday|0.4.3|
|Angular2|johnpapa|2.0.3|
|HTMLHint|mkaufman|0.3.3|
|lit-it|mohseenrm|1.2.10|
|prettify-json|mohsen1|0.0.3|
|csharp|ms-vscode|1.7.0|
|latex|ms-vscode|0.1.3|
|sublime-keybindings|ms-vscode|2.0.1|
|debugger-for-chrome|msjsdiag|2.5.5|
|node-modules-resolve|naumovs|1.0.2|
|vscode-icons|robertohuertasm|7.3.0|
|sass-indented|robinbentley|1.3.0|
|yo|samverschueren|0.9.3|
|stylelint|shinnn|0.23.0|
|addDocComments|stevencl|0.0.8|
|cordova-tools|vsmobile|1.2.6|
|change-case|wmaurer|1.0.0|
|html2jade|wmaurer|0.2.0|
|join-lines|wmaurer|0.2.2|
|vscode-jumpy|wmaurer|0.3.1|
|JavaScriptSnippets|xabikos|1.4.0|;

---
Scenario:

I'm not sure how to reproduce this; if I manage to do it again, I'll update the issue. 
I was seeing high (~97-100%) CPU usage from this `Code Helper.app` process running `tsserver.js`:
```
/Users/jskrzypek/Downloads/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/jskrzypek/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /usr/local/lib/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry
```
I noticed that both this process and another Code Helper running `typescript`
```
/Users/jskrzypek/Downloads/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/jskrzypek/.nvm/versions/node/v6.9.5/lib/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/jskrzypek/Library/Caches/typescript --enableTelemetry
```
stuck around after quitting vscode. I googled for an issue and found #20260 which had an instruction to try using the `TSS_LOG` shell parameter to enable tsserver logging. I "force quit" the misbehaving `tsserver.js` activity from the Activity Monitor and then followed the instructions in the comment https://github.com/Microsoft/vscode/issues/20260#issuecomment-282408109 and ran this:
```
export TSS_LOG="-level verbose -file ~/tss.log"
code .
```
After vscode opened, I got a warning at the top of the window informing me that the typescript service had died repeatedly more than 5 times in the last 5 minutes. This warning modal kept appearing repeatedly, leading me to believe that whatever was triggering the warning kept occurring. I clicked on the button to create the issue and then quit vscode. When I looked, the `tts.log` file did not  exist. After running `code .` a second time the warning did not appear.

Other notes:

It noticed that I also have a Sublime Text node process running `tsserver.js` hanging around long after I've quit ST that is also showing high cpu use. I was running bot ST and vscode simultaneously at some point recently, I think on the same project/folder.

**Comment by mjbvz** [comment]
@jskrzypek Thank you for looking into this.

Try using an absolute path in the `TSS_LOG` environment variable, such as `export TSS_LOG="-level verbose -file /Users/MyUserName/tss.log"`. If you can collect some logs, please share them and we'll take a look

@mhegazy, any other recommendations for investigating the root cause here?

**Comment by jskrzypek** [comment]
Ok, so I hadn't been able to reproduce this bug previously, but apparently that was because I'd already switched out the relative path in `TSS_LOG` for an absolute one. Based on your reply I tried going back to `export TSS_LOG="-level verbose -file ~/tss.log"` and was able to trigger the repeated warning problem.

So we have these steps to reproduce:
--------------------------------
 1. run `export TSS_LOG="-level verbose -file ~/tss.log"`
 2. run `code .`

**Comment by mjbvz** [comment]
Thanks, I've opened https://github.com/Microsoft/TypeScript/issues/14528 to track the invalid TSS_LOG file issue.

**Comment by mjbvz** [comment]
@jskrzypek, if you are still seeing the original TSServer crash when using a valid `TSS_LOG` path, please try collecting the logs and I'll take a look

**Comment by jskrzypek** [comment]
Cool, I'll update & check it out

**Comment by jskrzypek** [comment]
Ok I tried this again just now and instead of the tsserver repeatedly restarting with a warning, vscode now reports this:
<img width="1188" alt="tsserver_crash" src="https://cloud.githubusercontent.com/assets/1513265/23891412/ecb52d64-089e-11e7-9bc8-43adc495352b.png">

Is that the expected behavior? The `~/tss.log` path is just invalid and won't ever be supported? (which is fine, but probably should be documented somewhere)

Anyhow, here's the error log produced by the "Report Issue" button:

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vimStyle|74th|0.5.0|
|vscode-markdownlint|DavidAnson|0.7.0|
|vscode-file-peek|abierbaum|1.0.1|
|html-snippets|abusaidm|0.1.0|
|npm-intellisense|christian-kohler|1.3.0|
|vscode-eslint|dbaeumer|1.2.7|
|vscode-dash|deerawan|1.4.0|
|tslint|eg2|0.8.1|
|RelativePath|jakob101|0.12.0|
|docthis|joelday|0.4.3|
|Angular2|johnpapa|2.0.3|
|HTMLHint|mkaufman|0.3.3|
|lit-it|mohseenrm|1.2.10|
|prettify-json|mohsen1|0.0.3|
|csharp|ms-vscode|1.8.0|
|latex|ms-vscode|0.1.3|
|sublime-keybindings|ms-vscode|2.0.1|
|debugger-for-chrome|msjsdiag|2.6.0|
|node-modules-resolve|naumovs|1.0.2|
|vscode-icons|robertohuertasm|7.3.0|
|sass-indented|robinbentley|1.3.0|
|yo|samverschueren|0.9.3|
|RustyCode|saviorisdead|0.19.1|
|stylelint|shinnn|0.23.0|
|addDocComments|stevencl|0.0.8|
|cordova-tools|vsmobile|1.2.7|
|change-case|wmaurer|1.0.0|
|html2jade|wmaurer|0.2.0|
|join-lines|wmaurer|0.2.2|
|vscode-jumpy|wmaurer|0.3.1|
|JavaScriptSnippets|xabikos|1.4.0|;

I'll try jumping to the insider channel and see if that does anything different

**Comment by mjbvz** [comment]
Yes if the server crashes 5 times in 10 seconds, we do not attempt to restart it. The TSServer requires an absolute path for TSS_LOG. We're working making TS server log collection simpler in the next release

**Comment by jskrzypek** [comment]
I get the same error with the insiders build.
