### ISSUE TITLE
screen gets blurry when i open vs code 

### ISSUE THREAD

**Issue by Shivam-dot13** [microsoft/vscode#219722]
Type: <b>Performance Issue</b>

the screen gets blurry and buttons get fuzzy

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.75GB free)|
|Process Argv|--crash-reporter-id 5b9eb1ab-dc69-4613-9511-f58a71957fb2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   127	 23012	code main
    0	    99	  2684	ptyHost
    0	     7	  5824	     conpty-agent
    0	     7	 16148	     conpty-agent
    0	    63	 16704	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\SHIVAM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	    63	 19276	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\SHIVAM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     7	 21304	     conpty-agent
    0	    62	 21332	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\SHIVAM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    1	   100	  7692	window [2] (Issue Reporter)
    0	   118	 11344	shared-process
    0	     9	  4584	     "C:\WINDOWS\System32\DriverStore\FileRepository\asussci2.inf_amd64_ad7e5f4b857611df\ASUSOptimization\AsusOSD.exe" 
    0	    30	 12764	   crashpad-handler
    0	    88	 13340	fileWatcher [1]
    1	   138	 14616	   gpu-process
    0	   202	 14952	extensionHost [1]
    0	    51	  3168	     c:\Users\SHIVAM\AppData\Local\Microsoft\WindowsApps\python3.12.exe c:\Users\SHIVAM\.vscode\extensions\ms-python.black-formatter-2024.3.11501016\bundled\tool\lsp_server.py --stdio
    0	    28	  9020	       c:\Users\SHIVAM\AppData\Local\Microsoft\WindowsApps\python3.12.exe c:\Users\SHIVAM\.vscode\extensions\ms-python.black-formatter-2024.3.11501016\bundled\tool\lsp_runner.py
    0	    10	 23172	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    91	  7092	     "C:\Users\SHIVAM\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\SHIVAM\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=14952
    0	     6	  8332	     c:\Users\SHIVAM\.vscode\extensions\ms-python.python-2024.9.2024062703-win32-x64\python-env-tools\bin\pet.exe server
    0	    10	 16064	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    50	  8384	     c:\Users\SHIVAM\AppData\Local\Microsoft\WindowsApps\python3.12.exe c:\Users\SHIVAM\.vscode\extensions\charliermarsh.ruff-2024.30.0-win32-x64\bundled\tool\server.py
    0	    10	 12408	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    90	  8752	     electron-nodejs (server.js )
    0	    90	 12464	     electron-nodejs (server.js )
    0	   200	 14040	     electron-nodejs (bundle.js )
    0	   214	 15600	window [1] (python.py - Python - py - Visual Studio Code [Administrator])
    0	    44	 20400	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (python.py - Python - py - Visual Studio Code [Administrator])
|    Folder (Python): 2 files
|      File types: py(2)
|      Conf files:;
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ruff|cha|2024.30.0
python-environment-manager|don|1.2.4
vscode-docker|ms-|1.29.1
black-formatter|ms-|2024.3.11501016
python|ms-|2024.9.2024062703
vscode-pylance|ms-|2024.6.103
remote-containers|ms-|0.374.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
autodocstring|njp|0.6.1
even-better-toml|tam|0.19.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31082724

```

</details>

**Comment by deepak1556** [comment]
Does it still happen with latest stable ?

/gifPlease

**Comment by Shivam-dot13** [comment]
yes that still happens, I have attached screen recording as you can see what is happening to my screen as i open vscode but as soon as i move my cursor the screen gets normal for a moment and that blurry thing happen to the screen once again as soon as i bring the cursor to rest. Please fix this bug soon i am not able to code for quite a while on it now forcing me to use other IDE's![Image](https://github.com/user-attachments/assets/255646a3-ae43-4d9e-b93a-4572c7c7c927)

**Comment by Shivam-dot13** [comment]
yes it does still happen

**Comment by deepak1556** [comment]
Please enable the setting following the steps at https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

/duplicate https://github.com/microsoft/vscode/issues/124226

**Comment by Shivam-dot13** [comment]
thank you so much it is working very well now
