### ISSUE TITLE
Copilot icon covering code in notebooks 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#219713]
The copilot icon popping up and covering code while typing is extremely distracting and annoying. It happens throughout the entire notebook and all cells as typing

![image](https://github.com/microsoft/vscode-jupyter/assets/19276747/99bd0e47-e22a-423f-8b15-4836cebf1e95)
![image](https://github.com/microsoft/vscode-jupyter/assets/19276747/44c6dffd-72a4-408b-ab0f-b8418cec0159)

## Expected behavior

For code not to be covered by popup icons

## Actual behavior

Code being covered by icons popping up

**Comment by elgerm** [comment]
+1 super annoying

**Comment by justschen** [comment]
@elgerm @claudiaregio this should be fixed in our latest release. this was fixed with a new heuristic which now spawns it in the best case scenario, including the gutter when available. https://github.com/microsoft/vscode/pull/221419 please update and try it out, thanks!
