### ISSUE TITLE
The window is not responding

### ISSUE THREAD

**Issue by Shanthosh16** [microsoft/vscode#219721]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by Shanthosh16** [comment]
i tried everything i found on web to solve the issue, but  it is not solved.

**Comment by chrmarti** [comment]
Please provide steps that result in the window not responding and attach a screenshot of the unresponsive window.

**Comment by chrmarti** [comment]
Also include which version of VS Code you are using.
