### ISSUE TITLE
Add autoFindInSelection option to find widget

### ISSUE THREAD

**Issue by rodrigoestevao** [Microsoft/vscode#21976]
- VSCode Version: 1.10.1
- OS Version: Windows 7 64bits, OSX 10.6

Steps to Reproduce:

1. Select some block of text;
2. Ctrl + H to replace some text

**Comment by alexandrudima** [comment]
To limit the searching (or the replacing) to a selection you must press the "Find in selection" button in the find widget:

![image](https://cloud.githubusercontent.com/assets/5047891/23696597/944f0a82-03e4-11e7-848b-aba6452d66cf.png)

**Comment by rodrigoestevao** [comment]
Yes Sir, 
I'm doing this, but it's very common for most text editors consider the selected text as default start point. I'd suggest just check this option automatically whenever you have some selected text block.
Cheers 

    On Wednesday, March 8, 2017 5:50 AM, Alexandru Dima <notifications@github.com> wrote:
 

 To limit the searching (or the replacing) to a selection you must press the "Find in selection" button in the find widget:—

**Comment by alexandrudima** [comment]
Ok, I understand. You would like the "Find in Selection" toggle to automatically be set to on when launching the find widget from an editor which has a selection. There are plenty of other users that do not want such a behaviour, I therefore suggest we rename the issue to something more clear such as: "Add autoFindInSelection option"

**Comment by rodrigoestevao** [comment]
Yes Alex, this is my suggestion.  Thank you a lot for your attention.

**Comment by alexandrudima** [comment]
I ran today across a duplicate, so I suggest we track this request in #15148
