### ISSUE TITLE
Visual Glitch: Transparent Modal and Mouse Cursor Imprint in KDE on Wayland in VirtualBox

### ISSUE THREAD

**Issue by taaheer** [microsoft/vscode#219703]
Does this issue occur when all extensions are disabled?: Yes

- **Name:** visual-studio-code-bin
- **Version:** 1.90.2-1
- **Architecture:** x86_64
- **Depends On:** libxkbfile, gnupg, gtk3, libsecret, nss, gcc-libs, libnotify, libxss, glibc, lsof, shared-mime-info, xdg-utils, alsa-lib
- **Optional Deps:**
  - glib2: Needed for move to trash functionality [installed]
  - libdbusmenu-glib: Needed for KDE global menu [installed]
  - org.freedesktop.secrets: Needed for settings sync [installed]
  - icu69: Needed for live share
- **Distro:** Arch Linux
- **KDE Plasma Version:** 6.1.1
- **KDE Frameworks Version:** 6.3.0
- **Qt Version:** 6.7.2
- **Kernel Version:** 6.9.7-arch1-1 (64-bit)
- **Graphics Platform:** Wayland, X11

I installed VS Code from [AUR](https://aur.archlinux.org/packages/visual-studio-code-bin).

Apparently this occurs only in VirtualBox.

I have arch installed in a pendrive and sometimes I need both Windows and Linux at same time so I have plug pendrive and boot in VirtualBox. But when I boot Arch directly and attempt to recreate, this glitch didn't occur.  

### VirutalBox setting

- Video Memory: 64MB
- 3D acceleration: Enabled 

### Steps to Reproduce:

1. Boot Arch on KDE with Wayland in VirtualBox.
2. Open VS Code 
3. Click any option that opens a VS Code inbuilt modal, such as 'Publish to GitHub' in Source Control.

### Bug Description:

The modal window is transparent, the buttons are white with no text, and you can see your code through it. In Wayland, if you hover your mouse over the modal, the mouse cursor will imprint on the modal window. Additionally, if you open another window over the modal, that window will also imprint on the modal. This issue also occurs in X11, but without the mouse cursor being imprinted.

### Screenshots:

- **Wayland:**
  ![Wayland](https://github.com/microsoft/vscode/assets/99655331/39820797-3e0d-45c8-af80-e6d59cc10892)
- **X11:**
  ![X11](https://github.com/microsoft/vscode/assets/99655331/ef149e72-d962-415a-a1d9-7ed896c4483f)
- **X11 (another example):**
  ![X11 2](https://github.com/microsoft/vscode/assets/99655331/a20c42d3-43a3-4860-8f06-cba8cf586f0c)

**Comment by deepak1556** [comment]
Can you check if the issue repros after enabling the following setting https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by taaheer** [comment]
> Can you check if the issue repros after enabling the following setting https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

Sorry, I don't have that workstation anymore.
