### ISSUE TITLE
Syntax highlighting bug for attributes

### ISSUE THREAD

**Issue by chriskuech** [Microsoft/vscode#21979]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.0|
|language-haskell|justusadam|1.4.4|
|cpptools|ms-vscode|0.7.1|
|csharp|ms-vscode|1.6.2|
|vscode-mssql|sanagama|0.0.4|

---

Steps to Reproduce:

1. create a new file 
2. set language mode to "CSS"
3. add `[myattr] {}` to the sheet
4. notice that the `]` color should match the color on `[` but instead matches the color on `myattr`

**Comment by ugurozturk** [comment]
![21979](https://cloud.githubusercontent.com/assets/7994408/23588210/ce1ea4bc-01c2-11e7-8c13-d26d3e65cc68.PNG)

VS Code : 1.10.1
Theme : Dark+ (default dark)
Language : CSS

@chriskuech i think this is already fixed in new realeases

**Comment by isidorn** [comment]
Works for me in latest, please try it with latest vscode or vscode insiders
