### ISSUE TITLE
vscode 1.10.1 - the typing indicator disappear when I zooming out with multi cursor option.

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#21974]
@alexandrudima 
------------------------
![ks](https://cloud.githubusercontent.com/assets/17777237/23579545/7d806254-00f8-11e7-8f89-beeadb1bf6cf.gif)

**Comment by isidorn** [comment]
I think this is as designed. Forwarding to Alex to decide

**Comment by alexandrudima** [comment]
The secondary cursors are always rendered. They are rendered as a 1px wide line. When zooming out, it appears Chromium decides to render them with a width below 1px, which ends up being 0 screen pixels.

I can only recommend to not use window zoom and to use fontSize instead.

**Comment by pixieaka** [comment]
@alexandrudima 

Can we fix that soon ?

**Comment by pixieaka** [comment]
I guess if all cursors same width of the main cursor, the problem will solved. Because the main cursor not hide in all situations

**Comment by alexandrudima** [comment]
We have made significant progress in #28542, so I suggest to continue tracking this issue in #28542
