### ISSUE TITLE
Debugger: do not attach, error, grey breakpoints

### ISSUE THREAD

**Issue by osenvosem** [Microsoft/vscode#21973]
- VSCode Version: 1.10.1
- OS Version: macOS 10.12.3

Sometimes debugger do not attach to a process run with `node --inspect` command until I make http request to my app. Breakpoints are grey and there is an error in debug console:

```
Error processing "setBreakpoints": Error: Set breakpoints request timed out
    at Timeout.setTimeout (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/utils.js:55:24)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```
Also after I save file debugger sometimes do not reattach to process.

```json
    {
      "name": "Attach",
      "type": "node",
      "protocol": "inspector",
      "request": "attach",
      "restart": true,
      "skipFiles": [
        "node_modules/**/*.js",
        "<node_internals>/**/*.js"
      ],
      "smartStep": true,
      "port": 9229
    }
```

Looks like this:
![ozmsjpggyz](https://cloud.githubusercontent.com/assets/6762673/23578438/20d9a854-00e8-11e7-9d99-c9316072413f.gif)

I also have this error:
![screen shot 2017-03-04 at 21 14 29](https://cloud.githubusercontent.com/assets/6762673/23581141/cb052628-011f-11e7-97d8-c3b12a098dd0.png)

**Comment by ancarrera** [comment]
The gray breakpoint problem can be that you do not enable sourceMap and you do not specify the webRoot project. You can try to add this:

```json
    {
      "name": "Attach",
      "type": "node",
      "protocol": "inspector",
      "request": "attach",
      "restart": true,
      "skipFiles": [
        "node_modules/**/*.js",
        "<node_internals>/**/*.js"
      ],
      "smartStep": true,
      "port": 9229,
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}"
    }
```

**Comment by osenvosem** [comment]
@ancarrera I do not transpile server code, I don't those.

**Comment by roblourens** [comment]
The "set breakpoints request timed out" issue is expected and can be ignored. Details: http://stackoverflow.com/questions/42567417/error-set-breakpoints-request-timed-out-while-debugging-node-in-vs-code

Do you get the other error "Cannot read property 'Debugger'" when the process is restarting? Or another time?

Are you using nodemon?

**Comment by osenvosem** [comment]
> Do you get the other error "Cannot read property 'Debugger'" when the process is restarting? Or another time?
The error sometimes occurs when I stop debugger. I got this error with both: nodemon and node.

Debugger very rarely attaches to the process until I make first http request to the app. Although breakpoints are grey most of the time, they are hit.

**Comment by roblourens** [comment]
I see the problem - the fix for the "Cannot read property 'Debugger'" error message will be in the Insiders build tomorrow.

The timeout error, and the fact that breakpoints stay gray until they are hit, is a Node bug which should be fixed in their next release.
