### ISSUE TITLE
Extension host crash with long string in `vscode.window.createOutputChannel`

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode#219785]
Does this issue occur when all extensions are disabled?: No, requires calling the API

- VS Code Version: 1.91.0-insiders
- OS Version: Windows (Mac will NOT repro)

Steps to Reproduce:

1. Add the following line to Hello World sample (138 characters): 	`vscode.window.createOutputChannel("123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678");`
2. Run the extension and run the Hello World command and observe that the VS Code instance crashes

Maybe there should be an error message here instead of crashing

**Comment by sandy081** [comment]
It seems to work for me. Can you please retry and let us know if you still see the crash?
