### ISSUE TITLE
Tasks menu items not shown in Russian locale

### ISSUE THREAD

**Issue by Reddds** [Microsoft/vscode#21987]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|githistory|donjayamanne|0.1.5|
|xml|DotJoshJohnson|1.7.0|
|vscode-npm-script|eg2|0.1.8|
|vscode-npm|fknop|3.3.0|
|knockoutjs|furstenberg|0.1.0|
|vscode-xslt-snippets|marvinhagemeister|0.1.0|
|Arduino|moozzyk|0.0.4|
|cpptools|ms-vscode|0.10.2|
|csharp|ms-vscode|1.7.0|
|vscode-icons|robertohuertasm|7.3.0|
|vscode-gulp|tanato|0.0.4|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. Setup VS Code 
2. set "locale":"ru"
3. Restart VS Code
4. Ctrl+Shift+P and type Task
![qip shot - screen 012](https://cloud.githubusercontent.com/assets/2176187/23582578/88657416-013e-11e7-9640-ca1ffdab3c19.png)

**Comment by dbaeumer** [comment]
This already got fixed for the next release.

The tasks do show up when typing the Russian version of the command.
