### ISSUE TITLE
Add : Right click the file in left panel add "Copy project path" PLZ

### ISSUE THREAD

**Issue by goldenfreemanchina** [Microsoft/vscode#21980]
- VSCode Version: 1.10.1
- OS Version:openSuse

Steps to Reproduce:

1.Right click the file in left panel?

**Add : Right click the file in left panel add a item-"Copy project path",PLZ;Already has a item named"Copy Path" ,but useless;"Copy project path" will helpful**~THX

OR Instead:

**Add autocomplete with file path under project?**~THX

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by goldenfreemanchina** [comment]
THX~（づ￣３￣）づ╭❤～
