### ISSUE TITLE
Copy Paste Syntax Highlighting does not paste installed font

### ISSUE THREAD

**Issue by rodrigortz** [Microsoft/vscode#21989]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:47:58.633Z)
- OS Version: Linux x64 4.9.13-200.fc25.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.3.4|
|vscode-chester-atom|chriseckenrode|0.1.7|
|hopscotch|idleberg|0.1.4|;

The copy paste of syntax highlighting works half-way since it does not paste the font used in VS Code, even when installed in the system.
---

Steps to Reproduce:

1. Select text in VS Code with a programming font such as Source Code Pro.
2. Paste in Outlook New Mail window with "Keep Formatting" option.

**Comment by rebornix** [comment]
Sorry I can't reproduce this issue. Outlook is telling me the pasted content is Source Code Pro.

![screen shot 2017-03-06 at 12 01 29 pm](https://cloud.githubusercontent.com/assets/876920/23627197/a8cd2146-0264-11e7-8c6f-f8b2de7447ec.png)
