### ISSUE TITLE
JS/TS language service keeps crashing

### ISSUE THREAD

**Issue by jayeeson** [microsoft/vscode#219872]
Type: <b>Bug</b>

Opened a workspace on my Windows PC that is connected over SSH to files on my Ubuntu 24.04 system. After some time the service crashes. It happens repeatedly.

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 6.8.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (19.06GB free)|
|Process Argv|--crash-reporter-id 5f1e55a6-f41b-4d9f-b736-b4d5eeac579f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.0.31|
|OS|Linux x64 6.8.0-36-generic|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 3104)|
|Memory (System)|30.93GB (15.03GB free)|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
QML|bbe|1.0.0
javascript-ejs-support|Dig|1.3.3
remotehub|Git|0.62.0
better-cpp-syntax|jef|1.17.2
vscode-edge-devtools|ms-|2.1.5
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
azure-repos|ms-|0.38.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
umlet|the|15.1.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.1.0
prettier-vscode|esb|10.4.0
vscode-jest-runner|fir|0.4.73
copilot|Git|1.209.0
copilot-chat|Git|0.16.1
vscode-graphql|Gra|0.11.0
vscode-graphql-syntax|Gra|1.3.6
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.1
vsliveshare|ms-|1.0.5932
vscode-react-native|msj|1.13.0
vscode-versionlens|pfl|1.14.2
inline-sql-syntax|quf|2.16.0
vscode-stylelint|sty|1.4.0
vscode-css-variables|vun|2.7.1
vscode-perfect-css-modules|wan|0.5.0
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31082724

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by jayeeson** [comment]
Issue hasn't repro'd once over the day with VS Code Insiders, extensions disabled or enabled.
I guess the fix is already in! Thanks.
