### ISSUE TITLE
the window is not responding ubuntu, and slowly work

### ISSUE THREAD

**Issue by RostislavZalevsky** [microsoft/vscode#219878]
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`prof-LbNsbG7i.main.cpuprofile.txt`

**Comment by RostislavZalevsky** [comment]
file:///home/rostyslav/prof-LbNsbG7i.main.cpuprofile.txt

**Comment by RostislavZalevsky** [comment]
[Uploading prof-LbNsbG7i.main.cpuprofile.txt…]()

**Comment by jrieken** [comment]
@RostislavZalevsky please re-upload or re-capture the profile trace as your previous update didn't succeed.

**Comment by RostislavZalevsky** [comment]
now i cant re-report since i reinstalled VS Code. And i dont see any issues 
Thanks
