### ISSUE TITLE
Source control icon flashes every second if "Autofetch period" is set to 1

### ISSUE THREAD

**Issue by AdamWr** [microsoft/vscode#219877]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.0 (user setup)
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:52:22.949Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621
- OS Version: Windows 11

Steps to Reproduce:

1. Set `Git: Autofetch` to `true`
2. Set `Git: Autofetch period` to `1`
3. Look at the `Source control` icon

https://github.com/microsoft/vscode/assets/29142494/9d0be9d4-e9b1-4edb-a05c-0385860a87b1

I'm not sure if it's a new feature or a bug, but it wasn't like that in previous version (1.90).

**Comment by lszomoru** [comment]
Thanks for reporting this issue. This will be fixed in tomorrow's VS Code Insiders release and the next VS Code Stable release.

**Comment by AdamWr** [comment]
Thank you for checking and fixing it.
