### ISSUE TITLE
Git stash -> commit ->push flow is gone

### ISSUE THREAD

**Issue by Fuzzyma** [microsoft/vscode#219851]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.2
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Change a file
2. Arrow top open menu for commit & push is disabled:

![grafik](https://github.com/microsoft/vscode/assets/3540542/f244d0ec-8ef2-4eea-82bb-37098bd4cb3f)

This happend since the last updated that I just installed.
Before, it would let you click "commit & push" without explicitely stashing them and a popup would show to ask if you want to stash all changes before commiting

**Comment by lszomoru** [comment]
@Fuzzyma, by "stash" you mean "stage"? Could you please tell me the values of the following settings:
* git.enableSmartCommit
* git.suggestSmartCommit
* git.smartCommitChanges

**Comment by lszomoru** [comment]
Thanks for the update and I am glad that you were able to track down and fix the issue.
