### ISSUE TITLE
Build failed — Smoke test

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#219894]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=282201
Changes: https://github.com/Microsoft/vscode/compare/e6a828c...a101882

Smoke test seems to be showing a sign in page?

**Comment by TylerLeonhardt** [comment]
Seemed to pass on retry so optimistically closing this unless it comes up more often
