### ISSUE TITLE
Custom telemetry collection for teams managing VSCode deployment

### ISSUE THREAD

**Issue by ryanwilsonperkin** [microsoft/vscode#219863]
VSCode has a great set of telemetry primitives to enable extension authors to collect telemetry, we would love to see something similar provided for organizations that manage a large team of developers using VSCode and are looking to collect telemetry.

Specifically, we would like to be able to collect metrics that would answer questions like:
- "How long does do code actions take?"
- "How long does a file save take?"
- "How long does initialization of the language server take?"
- "How frequently does VSCode's builtin tsserver process crash?"
- "What errors are occurring in our users' installed extensions?"

For organizations with a team of hundreds of developers using VSCode, collection of this data can be very cumbersome and reactive. We would much prefer to be proactive and be able to analyze these metrics to see if misconfigurations in our projects or recommended extensions are causing a degraded experience for our developers.

**Comment by brian-mcnamara** [comment]
+1 on this, we too are currently looking into how we can monitor VSCode used within the organization. It would be nice for us to have this out of the box without having to come up with our own distribution to patch the telemetry implementation.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now to gather more feedback. Thanks
