### ISSUE TITLE
expose an ability (for extensions) to color some code pieces

### ISSUE THREAD

**Issue by amigo421** [Microsoft/vscode#21984]
- VSCode Version:1.10.1
- OS Version:Win10/x64

feature request.

I'm using the editor for C++ development, so the case when some code pieces are inactive due the language features (simple example is preprocessor definitions). I've [asked](https://github.com/Microsoft/vscode-cpptools/issues/510) your collegues who works on cpp-tools about this feature (highlight some code as inactive/greyed, like IDEs usually do this) 
![image](https://cloud.githubusercontent.com/assets/3259933/23139466/91108c02-f7bd-11e6-8282-166b2a3cbf70.png)
but they told me that vscode doesn't expose this ability. any chance to implement this? 
I suppose this also can be used e.g. for code coverage

Thank you

**Comment by hoovercj** [comment]
This is already possible. You can look at my [dimmer](https://github.com/Microsoft/vscode/pull/21981) extension to see how I am dimming certain sections of code.

The official API for "decorations" is [here](https://code.visualstudio.com/Docs/extensionAPI/vscode-api#DecorationRenderOptions).

**Comment by hoovercj** [comment]
Apologies, I had an incorrect link in my earlier comment, I've fixed that now.

Also, here is [a link](https://github.com/hoovercj/vscode-dimmer/blob/master/src/extension.ts) to where I set the style in my dimmer extension.

**Comment by amigo421** [comment]
I'm like a bridge between vscode team and cpp-tools extension team :) 
I'm only trying to confirm cpp-tools team that is possible to improve their product

thank you!

**Comment by aeschli** [comment]
Please file your feature request against the [cpp extension](https://github.com/Microsoft/vscode-cpptools/issues). You can point them to @hoovercj example that shows how to use decorations.

**Comment by amigo421** [comment]
yeah, I did exactly that earlier with a link on this discussion, so just only wait their response
thank you!
