### ISSUE TITLE
Option to use macOS standard titlebar

### ISSUE THREAD

**Issue by kohlmannj** [Microsoft/vscode#21985]
- VSCode Version: 1.10.1 (1.10.1)
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Install the latest version of VSCode (v1.10.0 or higher)
2. Examine the window titlebar, and note that its appearance and functionality are a custom implementation rather than the macOS standard titlebar

I would appreciate a setting to use the macOS standard titlebar for a few reasons:
1. The [titlebar proxy icon](http://hints.macworld.com/article.php?story=2010031117415674) is a powerful macOS standard feature that VSCode's custom titlebar doesn't support
2. The macOS standard titlebar right-click offers a better interface (with icons) than the duplicate functionality implemented by VSCode's custom titlebar
3. Some applications such as [HyperDock](https://bahoom.com/hyperdock/) add system-wide functionality to window titlebars (in this case, scrolling on them to maximize the window), which doesn't work with VSCode's custom titlebar

Thanks for your consideration!

**Comment by bpasero** [comment]
`"window.titleBarStyle": "native"`
