### ISSUE TITLE
Use MSALjs for vscode.dev

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#219871]
We have received reports around Conditional Access where users are unable to use this route do to our existing Microsoft auth support in vscode.dev.

We should consider enabling MSAL-based auth for this route.

Upsides:
* Conditional Access will be happy

Downsides:
* Sessions can only last 24hrs before the page needs to be refreshed

Since the downsides are being seen more and more as a feature request these days, we should probably just make this change...

**Comment by TylerLeonhardt** [comment]
renamed for all of vscode.dev since we need to do this for all

**Comment by MUHAMMADIHSANALIKAP** [comment]
Thanksgiving and confirming myself with this email.![image](https://github.com/user-attachments/assets/61b435d7-2274-4e65-92c2-de6164dd644d)
