### ISSUE TITLE
c_cpp_properties.json not giving correct c++ library path under windows

### ISSUE THREAD

**Issue by mysterytony** [Microsoft/vscode#21988]
- VSCode Version: 1.10.1
- OS Version: windows 10

Steps to Reproduce:
1. create a `.cpp` file, write a `#include` statement, for example, `#include <iostream>`
2. hover the mouse on the yellow lightbulb and generate `c_cpp_properties.json`
3. the `includePath` property is not correct in my case. VSCode gives `C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*` which in my case, the c++ library is under `C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.10.24930\\include\\*`

Perhaps need to detect which version of visual studio one has?

**Comment by isidorn** [comment]
Please file this agaist the VSCode c++ extension here https://github.com/Microsoft/vscode-cpptools
