### ISSUE TITLE
Git: allow a stash-pull-pop flow

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#219823]
When I sync/pull with uncommited changes I get this:

![Image](https://github.com/user-attachments/assets/00ca96a7-7698-4f76-bfd4-00a7e31df3c3)

Then I need to manually stash, pull and pop. Maybe git could do this for me.

**Comment by lszomoru** [comment]
Duplicate of [#186431](https://github.com/microsoft/vscode/issues/186431)
