### ISSUE TITLE
VS Code Insider Build - Editor region does not recognize PowerShell syntax on a file saved with ps1 extension

### ISSUE THREAD

**Issue by rkyttle** [Microsoft/vscode#21982]
- VSCode Version: Code - Insiders 1.11.0-insider (84e56fc527047223a6ad22c31a906d4a579680d0, 2017-03-03T07:10:29.111Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|0.9.0|;

---

Steps to Reproduce:

1. Create new file, save file with .ps1 extension
2. Start typing some PowerShell, such as Get-Help
3. Intellisense does not recognize your command
4. Attempting to run a selection of code (F8) does not work either

I tried the same steps on VSCode Version: Code 1.10.1 with PowerShell extension 0.9.0 and everything works as it should

**Comment by isidorn** [comment]
Please file this agains the powershell extension here https://github.com/PowerShell/vscode-powershell
