### ISSUE TITLE
intellisense doesn't work in front matter astro.js project

### ISSUE THREAD

**Issue by dai-re** [microsoft/vscode#219990]
Type: <b>Bug</b>

Previously I was using version 1.90 and my Astro JS project worked perfectly then I upgraded vscode to version 1.91 when I wanted to continue my Astro JS project I didn't get Intelense in my Astro Frontmater file.

![Screenshot_20240704_230955](https://github.com/microsoft/vscode/assets/112737993/0ca3c746-c570-42c4-a3a1-7d725ee39bf6)

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:41.959Z)
OS version: Linux x64 6.9.7-200.fc40.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 799)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 0, 0|
|Memory (System)|7.63GB (3.63GB free)|
|Process Argv|--crash-reporter-id bad357ce-2458-4cae-9781-8a75f44f8192|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
astro-vscode|ast|2.10.2
vscode-tailwindcss|bra|0.12.4
turbo-console-log|Cha|2.10.4
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
vscode-gutter-preview|kis|0.31.2
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|5.4.2
markdown-preview-enhanced|shd|0.8.13
tabnine-vscode|Tab|3.121.0
errorlens|use|3.20.0
pretty-ts-errors|Yoa|0.5.4
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31082723

```

</details>

**Comment by Princesseuh** [comment]
Issue has been fixed downstream
