### ISSUE TITLE
No autocomplete of Component paths in .Vue files and no go to definition in ES6 imports

### ISSUE THREAD

**Issue by gkatsanos** [Microsoft/vscode#21992]
- VSCode Version:Version 1.10.1 (1.10.1)
- OS Version: Sierra ( 10.12.3 (16D32) ) 

Steps to Reproduce:

1. clone https://github.com/gkatsanos/gplus (branch : redesign) 
2. there's no autocomplete, can't go to Components with cmd+click.

 I tried adding a jsconfig.json with this:
```
{
    "compilerOptions": {
        "module": "es6"
    }
}
```

no change

**Comment by Akryum** [comment]
Also, there is no auto completion of exports from a module.

**Comment by mjbvz** [comment]
We don't support Vue out of the box. Try using the https://marketplace.visualstudio.com/items?itemName=octref.vetur plugin which should add support for these features

**Comment by gkatsanos** [comment]
Thanks Matt. VSCode is nice but I decided to just go back to Jetbrains
which has all those out of the box. Too many missing features, needs a bit
more work till it's something it can replace a professional tool. If one
needs a simple cool editor there's always sublime atom or brackets.

On 23 May 2017 02:26, "Matt Bierner" <notifications@github.com> wrote:

We don't support Vue out of the box. Try using the https://marketplace.
visualstudio.com/items?itemName=octref.vetur plugin which should add
support for these features

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/21992#issuecomment-303255853>,
or mute the thread
