### ISSUE TITLE
Do not enable auto update when installing an extension via VSIX

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#219932]
Installing an extension from VSIX is same as installing a specific version of an extension. Therefore, such an installed extension should not be auto updated.

**Comment by isidorn** [comment]
Thanks for this!

**Comment by sandy081** [comment]
To verify

- Create an extension VSIX (you can also download it from Marketplace)
- Install the VSIX by dropping it in extensions view
- Make sure Auto Update checkbox is disabled after installing the VSIX.

CC @hediet
