### ISSUE TITLE
Open window on first monitor upon first launch

### ISSUE THREAD

**Issue by myst6re** [Microsoft/vscode#21990]
- VSCode Version: 1.10.1
- OS Version: Windows 10

Steps to Reproduce:

1. Fresh Installation on a computer with two screens
2. First launch of the application

On the first launch, the main window was centered on my secondary screen, not on my primary screen. It may sounds dumb, but my secondary screen is often turned off, so I didn't see the window on the first launch until I realised it may be on the secondary screen.

Besides, I'm not sure, but is it recommended to choose a screen and a position on the screen in Windows OS? I though it is better to let the OS to set the position of the window.

**Comment by bpasero** [comment]
@myst6re could it be that your primary display is to the right of the secondary display? Can you share a screenshot of the monitor layout on Windows? 

In https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/windows.ts#L955 I seem to pick up the first display that I find, but that might not be the primary display after all.

**Comment by myst6re** [comment]
Exactly, my primary display is on the right and my secondary on the left.
![2017-03-06 20_12_06-parameters](https://cloud.githubusercontent.com/assets/8015696/23625375/3861b710-02a9-11e7-8b19-6c32a155b839.png)

**Comment by bpasero** [comment]
Pushed a change to prefer the `screen.getPrimaryDisplay()` instead of picking just the first display.
