### ISSUE TITLE
Light+ Theme - added color is barely diffrentiable

### ISSUE THREAD

**Issue by Noitidart** [Microsoft/vscode#21998]
- VSCode Version: 1.10.1
- OS Version: Win10

Steps to Reproduce:

0. Have "Light+ (default light)" theme selected
1. To a existing file, add a word on a line
2. Then do git view
3. You will see the "added" shade is barely visible from the green behind it, here is a screenshot, I added the word `, clearCover`:

![](http://i.imgur.com/n18BUjA.png)

Please make the light green and dark green more diffrentiated so it catches our eye while scrolling by. In the screenshot I used the green in the arrow, we can see we can't differentiate it.

**Comment by alexandrudima** [comment]
@Noitidart With the latest VS Code version you can customize these colors by yourself. e.g.

```
"workbench.colorCustomizations": {
	"diffEditor.insertedTextBackground": "#9bb95566", // the default is #9bb95533

}
```

<img width="733" alt="screen shot 2017-05-31 at 19 15 28" src="https://cloud.githubusercontent.com/assets/5047891/26644589/8b307b64-4635-11e7-992e-ad839b399167.png">

4+ years ago I took the colors from Visual Studio. I am sorry I am not the right person to tweak the default colors. To me, the current default colors look great and I can distinguish the different shades immediately.
