### ISSUE TITLE
Terminal sparkle is cut off

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#219970]
* have side by side terminal
* trigger the sparkle in the RHS
* :bug: it isn't fully visible

![Image](https://github.com/user-attachments/assets/0928f527-1334-4f9b-a39b-0f4ce203d848)

**Comment by Tyriar** [comment]
I'm not sure how to repro without starting out with shell integration enabled, creating decorations or a quick fix (fail a command), then switching shell integration off:

![image](https://github.com/user-attachments/assets/1c88789e-3531-4c1d-b737-62d5b22df8fd)
