### ISSUE TITLE
Feature request: Disable compact folder in source control

### ISSUE THREAD

**Issue by LozanoMatheus** [microsoft/vscode#219988]
It would be nice to have the same as the `"explorer.compactFolders": false` in SC, something like `"scm.compactFolders": false`. This makes it easier to visualize and follows the same as the explorer which in my case makes things not difficult when switching from two different views.

IMO, this makes things look the same and reduces the time needed to get used each time you switch between two views, making the experience less annoying and more homogeneous.

It could also be something like this to apply globally:

```json
"[compactFolders]": {
  "enabled": false
},
```

**Comment by tisilent** [comment]
Only scm.compactFolder has been added.
globally.   priority.   😨

**Comment by lszomoru** [comment]
Verification steps:
1. Launch VS Code Insiders and open a folder/workspace that contains a git repository
2. Switch to the "Source Control" view and switch to viewing the changes as Tree
3. Make a change to a folder that is 2/3 folders deep
4. Toggle the `scm.compactFolders` and confirm that it works as expected
