### ISSUE TITLE
New profile name replaced when selected another profile to copy from

### ISSUE THREAD

**Issue by vanowm** [microsoft/vscode#219972]
Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. make sure `workbench.experimental.enableNewProfilesUI` is enabled
2. in profiles window click `New Profile` button
3. type your new profile name
4. below select another existing profile in `Copy from` dropdown
5. observe your profile name has been replaced by the name of the profile from step 4.

```
Version: 1.91.0
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:52:22.949Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by gjsjohnmurray** [comment]
Similar to #219705 which is reportedly fixed in Insiders.

**Comment by vanowm** [comment]
Thanks, I didn't find that issue in my search.
