### ISSUE TITLE
File corrupted while saving after close all

### ISSUE THREAD

**Issue by zhoudxnz** [Microsoft/vscode#21993]
- VSCode Version: 1.10.1
- OS Version: Windows 10

Steps to Reproduce:

1. With multiple files open in the editor, some of which have been modified but not been saved.
2. Click 'Close All' (Ctrl K W). Click Save when prompted.
Sometimes files get corrupted, i.e., a file could be overwritten or partially overwritten by the content from another file.

**Comment by zhoudxnz** [comment]
Turned out to be a bug of the lonefy.vscode-JS-CSS-HTML-formatter-0.2.2 plugin.  The problem went away when I truned autosave off.
{
onSave: false,
...
}

**Comment by isidorn** [comment]
Great
