### ISSUE TITLE
vscode 10.0.1 - Why tab get 3 spaces it should 2 spaces only

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#21999]
Why tab get 3 spaces it should 2 spaces only !!!
Can i customize the number of spaces for tab key ?
![ks](https://cloud.githubusercontent.com/assets/17777237/23585492/6cb214ae-0189-11e7-9e3a-096aaac9c475.gif)

**Comment by isidorn** [comment]
Yes this is customazible -> in the status bar you can click on tab size: 3 and after that continue using the quick pick and all of this should be customizable.
You also have some settings in your settings.json file
