### ISSUE TITLE
"potential listener LEAK detected" for comment DOM elements that are recreated on every "display" call but not disposed of

### ISSUE THREAD

**Issue by rehmsen** [microsoft/vscode#219984]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Head
- OS Version: Browser

## Steps to Reproduce:

1. Switch back and forth between the comments panel and some other panel.

This will trigger this warning:
https://github.com/microsoft/vscode/blob/3ce0d742a353b0df2e867b4d4fd531bba4a77395/src/vs/base/common/event.ts#L869

## Likely cause

* The DOM nodes for each comment thread are recreated whenever the comment is displayed, see:
https://github.com/microsoft/vscode/blob/3ce0d742a353b0df2e867b4d4fd531bba4a77395/src/vs/workbench/contrib/comments/browser/commentThreadBody.ts#L73-L104

* The new nodes are registered for cleanup, however to the lifecycle of the CommentThreadBody:
https://github.com/microsoft/vscode/blob/3ce0d742a353b0df2e867b4d4fd531bba4a77395/src/vs/workbench/contrib/comments/browser/commentThreadBody.ts#L259-L270

* This means they are eventually cleaned up, but only when the entire comment thread is cleaned up. 

## Possible fix

There is already a separate commentsDisposable, which seems to be used to dispose comments when they are deleted in updateCommentThread. But not when the display function recreates the elements.

**Comment by alexr00** [comment]
@rehmsen the file `commentThreadyBody.ts` is for the comment widget in the editor, not the "Comments" view, that shows in the panel. If you share the full warning that you see then it might have some pointers wo where the leak is coming from.

**Comment by rehmsen** [comment]
Here is what I have:

```
[fg9] potential listener LEAK detected, having 291 listeners already. MOST frequent listener (117):

Ucb.console.<computed>	@	logger.ts:93
check	@	event.ts:891
_event._event	@	event.ts:1072
onWillAddFirstListener	@	menuService.ts:395
_event._event	@	event.ts:1080
createActionsToolbar	@	commentNode.ts:352
createHeader	@	commentNode.ts:278
ySb.CommentNode	@	commentNode.ts:140
_createInstance	@	instantiationService.ts:162
createInstance	@	instantiationService.ts:128
createNewCommentNode	@	commentThreadBody.ts:260
updateCommentThread	@	commentThreadBody.ts:198
updateCommentThread	@	commentThreadWidget.ts:220
update	@	commentThreadZoneWidget.ts:331
(anonymous)	@	commentsController.ts:911
(anonymous)	@	commentsController.ts:907
_deliver	@	event.ts:1172
_deliverQueue	@	event.ts:1183
fire	@	event.ts:1207
updateModelThreads	@	commentService.ts:324
updateComments	@	commentService.ts:403
updateCommentThread	@	mainThreadComments.ts:336
$updateCommentThread	@	mainThreadComments.ts:601
_doInvokeHandler	@	rpcProtocol.ts:484
_invokeHandler	@	rpcProtocol.ts:469
_receiveRequest	@	rpcProtocol.ts:394
_receiveOneMessage	@	rpcProtocol.ts:319
(anonymous)	@	rpcProtocol.ts:179
_deliver	@	event.ts:1172
fire	@	event.ts:1203
f.onmessage	@	webWorkerExtensionHost.ts:274
```

What the same problem not also occur for editors? I assume `display()` is also called when you switch between editors, maybe even when you scroll comment in and out of view. If that recreates the DOM, but does not ever clean up the listeners, should would that explain the error I see?

**Comment by alexr00** [comment]
It looks like there is a second, more quickly occuring issue, with comment nodes not getting disposed properly too.

**Comment by alexr00** [comment]
I found several leaks. To repro the leaks that I've fixed:
- Create a comment with the GitHub Pull Requests extension
- Add 10 replies to the comment.

I did not address the "leak" (not so much a leak and intentionally having lots of listeners) in https://github.com/microsoft/vscode/issues/219984#issuecomment-2210855829 as it should only happen with you have over a hundred comments.

@rehmsen please try with https://github.com/microsoft/vscode/pull/220091 and see if your issue persists.

**Comment by rehmsen** [comment]
Thanks Alex for taking a look and sending a fix. I am happy to try it out, unfortunately you catch me on my way out for a week of vacation, so it will take me a good week to get back to you. Probably don't wait for me with your PR.

**Comment by alexr00** [comment]
Thanks for the heads up!

**Comment by eleanorjboyd** [comment]
Hi @rehmsen! Were you able to verify if this fixed works for you? Thanks!

**Comment by alexr00** [comment]
@eleanorjboyd you can also verify following the steps in https://github.com/microsoft/vscode/issues/219984#issuecomment-2210953499!

**Comment by rehmsen** [comment]
Sorry for the delay. I did just run the test and can confirm that this seems to have solved our problem. Thanks!
