### ISSUE TITLE
all the comments are red and i cannot change theme after thelast update

### ISSUE THREAD

**Issue by George35mk** [Microsoft/vscode#21994]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-refresh-html|bajdzis|0.0.2|
|vscode-eslint|dbaeumer|1.2.6|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|beautify|HookyQR|0.8.8|
|vs-color-picker|lihui|0.4.0|
|vscode-icons|robertohuertasm|7.3.0|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|1.0.3|
|html-css-class-completion|Zignd|1.0.3|;

---

all the comments are red color

Steps to Reproduce:

1.
2.

**Comment by George35mk** [comment]
ok all ok no panic :)

**Comment by anaganisk** [comment]
@George35mk how did you solve it?

**Comment by George35mk** [comment]
i just update all my extensions thats all
