### ISSUE TITLE
Copilot issue- Getting error Unable to resolve chat model with family selection: gpt-4

### ISSUE THREAD

**Issue by shaivebansal374** [microsoft/vscode#219944]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91.0
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Open copilot chat ask any question
2. Its giving this error

**Comment by alessando-guida** [comment]
I have been experiencing the same issue. before the error was as shaivebansal374 reported: "Unable to resolve chat model with family selection: gpt-4".  Now, after installing version 0.17.1, the error has changed to "read ECONNRESET".

**Comment by chrmarti** [comment]
`ECONNRESET` might indicate a firewall or network proxy in your company's network that denies access to `api.githubcopilot.com`. Please also run `F1` > `GitHub Copilot: Collect Diagnostics` and post the output here, this will also check connectivity with a few additional servers required for GitHub Copilot.

**Comment by alessando-guida** [comment]
Thanks for your feedback. I can ask the IT department to white-list specific IP and ports. 

Should I request to have whitelisted  api.githubcopilot.com and  140.82.113.21 as well?


here is the full diagnostic:


## Copilot

- Version: 1.212.0
- Build: prod
- Editor: vscode/1.91.0

## Environment

- http_proxy: n/a
- https_proxy: n/a
- no_proxy: n/a
- SSL_CERT_FILE: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
- SSL_CERT_DIR: /etc/pki/tls/certs
- OPENSSL_CONF: n/a

## Feature Flags

- Send Restricted Telemetry: enabled
- Chat: enabled

## Node setup

- Number of root certificates: 146
- Operating system: Linux
- Operating system version: 4.18.0-513.24.1.el8_9.x86_64
- Operating system architecture: x64
- NODE_OPTIONS: n/a
- NODE_EXTRA_CA_CERTS: n/a
- NODE_TLS_REJECT_UNAUTHORIZED: n/a
- tls default min version: TLSv1.2
- tls default max version: TLSv1.3

## Network Configuration

- Proxy host: n/a
- Proxy port: n/a
- Kerberos SPN: n/a
- Reject unauthorized: disabled
- Fetcher: HelixFetcher

## Reachability

- github.com: HTTP 200
- api.github.com: HTTP 200
- copilot-proxy.githubusercontent.com: HTTP 200
- api.githubcopilot.com: read ECONNRESET
- default.exp-tas.com: HTTP 200

## VS Code Configuration

- HTTP proxy: 
- HTTP proxy authentication: n/a
- Proxy Strict SSL: true
- Extension HTTP proxy support: override

## Extensions

- Is `win-ca` installed?: false
- Is `mac-ca` installed?: false

## Authentication

- GitHub username: alessando-guida

**Comment by chrmarti** [comment]
> Thanks for your feedback. I can ask the IT department to white-list specific IP and ports.
> 
> Should I request to have whitelisted api.githubcopilot.com and 140.82.113.21 as well?

`https://*.githubcopilot.com` would be better because there are additional hosts for enterprise subscriptions. Please also check: https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot

**Comment by alessando-guida** [comment]
whitelisting `https://*.githubcopilot.com` solved the problem for me. Thanks

**Comment by shaivebansal374** [comment]
Issue gets resolved after IT team has whitelisted the **https://*.githubcopilot.com**. Thanks!!
