### ISSUE TITLE
Notebook cell comment is picked only from the first owner/provider

### ISSUE THREAD

**Issue by rehmsen** [microsoft/vscode#219924]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Head
- OS Version:  Any

Steps to Reproduce:

1.  Have two comment providers.
2. Make the first one return no comments for a cell, and the second one return a comment for that cell.

Expected:

The one comment from the second owner is picked.

Actual: 

No comment is shown, because we only check the first provider if it has a comment.

See: 
https://github.com/microsoft/vscode/blob/d69a8fb36d408b6bd89197668ba3b039d5f9bb91/src/vs/workbench/contrib/notebook/browser/view/cellParts/cellComments.ts#L138-L142

I will send a PR to fix that.

**Comment by rebornix** [comment]
mitigated via https://github.com/microsoft/vscode/pull/219926
