### ISSUE TITLE
Bug Report: Issue Creating New Files/Folders in VS Code

### ISSUE THREAD

**Issue by Rahul5114** [microsoft/vscode#219954]
Does this issue occur when all extensions are disabled?: Yes
Description:
When attempting to create a new file or folder in VS Code, I encounter a bug (or perhaps an unintended feature). After clicking to create a new file or folder, VS Code starts to create it inside an existing folder instead of independently at the root level. 
I have also provided a video representation for the same .

Expected Behavior:
The new file or folder should be created at the root level, not inside an existing folder.

Workaround:
I found a workaround by clicking somewhere else (e.g., the coding section) and then clicking on the 'New File' or 'New Folder' button again. However, this is not an ideal solution and can be frustrating at times.

Please investigate and provide a fix for this issue. Thank you.

https://github.com/microsoft/vscode/assets/125982089/fefd7abb-c7fa-4d2c-aee7-b5b4a5421fd0

- VS Code Version: 1.91.0
- OS Version: Windows 11 Pro

Steps to Reproduce:

1. Click the 'New File' or 'New Folder' button in the Explorer sidebar.
2. Observe that the new file or folder is created inside an existing folder rather than independently.

**Comment by lramos15** [comment]
It's based on where you last clicked. So if you last clicked in the empty root space then it creates it at the root. This is as designed
