### ISSUE TITLE
The devcontainer extensions do not work with a custom profile 

### ISSUE THREAD

**Issue by Lupennat** [microsoft/vscode#219941]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91.0 (Universal)
- OS Version: Darwin arm64 23.5.0

Steps to Reproduce:

1. create new profile test
2. switch to new profile
3. Open in Devcontainer

devcontainer.json sample
```json
{
	"name": "Alpine",
	"image": "mcr.microsoft.com/devcontainers/base:alpine-3.20",
	"customizations": {
		"vscode": {
			"extensions": [
				"dbaeumer.vscode-eslint"
			]
		}
	}
}
```
**container is loaded without extensions.**
Opening in DevContainer with the default profile works correctly.
Works correctly with the previous version of vscode 1.90.2

**Comment by talk2sunil83** [comment]
Same For Me

**Comment by sliekens** [comment]
+1 extensions from devcontainer.json are not enabled in the container when using a custom profile.

Although the container logs does report that the extension was successfully installed, and I can see it is installed in the container, in `/home/vscode/.vscode-server/extensions`. It's just not enabled when using a custom vscode profile.
