### ISSUE TITLE
Development Environment Improvements (code.bat/code.sh)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#22]
There is some work remaining to make the development environment nicer.

- [x] Do not create the Electron-Build folder outside of the source repository
- [x] Warn the user when node_modules are missing and a npm install is required
- [x] Warn the user when he runs npm install and not scripts/npm
- [x] Warn the user when out folder is missing and gulp watch is required

**Comment by joaomoreno** [comment]
:heavy_check_mark:
