### ISSUE TITLE
Allow VS like flexibility of view layout

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#220]
Like VS proper, I want more control over the arrangement of my workspace.
I've been using VS for almost 15 years, it's annoying and pointless to adapt to "everything on the left side". This is a dealbreaker for my switching while developing under linux for me.
I want the callstack, watch, output window in a row along the bottom, not on the left.

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/3360

**Comment by bpasero** [comment]
Closing, please file individual issues on the debug things you mentioned. I think we are looking into moving some parts of debug land into the panel. Meanwhile, output is also horizontal.
