### ISSUE TITLE
Unrelated settings in settings editor

### ISSUE THREAD

**Issue by abhijit-chikane** [microsoft/vscode#220004]
Right now I have not installed the copilot chat extension still it shows me the chat settings
![image](https://github.com/microsoft/vscode/assets/50770619/4719d7de-7b45-4c33-bac5-1a4b969bfd03)

**Comment by rzhao271** [comment]
It looks like this behaviour applies to several inline chat settings.
Adding @jrieken

**Comment by jrieken** [comment]
Inline chat (and very many other features) consist usually of three pieces

* an agnostic UI implementation that can show and do things (this also comes with settings)
* an API
* one or more extensions that implement the API to drive said UI

The settings you are seeing are for the (extension agnostic UI). I do agree that without matching extensions they aren't helpful but also cause no harm. 


@rzhao271 I'd say this is "as designed" unless the settings editor/model has a trick to hide settings that drive features which require extensions. In theory this applies to almost all features (IntelliSense, formatting, SCM) but practically we ship default extension for those too
