### ISSUE TITLE
Question about intended way to respond to file saves in language server

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#2200]
I'm looking for clarification on the intended use of the api's in a "normal" extension vs a language server. It's common to give users the choice between an action happening when files are saved or as the user types. In a normal extension that uses the `vscode` api directly, the following is possible:

```javascript
this.documentListener = vscode.workspace.onDidChangeTextDocument(this.handleChange);
this.documentListener = vscode.workspace.onDidSaveTextDocument(this.handleSave);
```
The object passed to the functions contains a nice `languageId` field to check to make sure you're only dealing with the right types of files.

The [official example](https://github.com/Microsoft/vscode-languageserver-node-example) illustrates it being done a bit differently in language servers. File changes are synced using a nice `documentSelector` which automatically handles the `languageId` above. To handle file saves, though, a file system watcher is used which only accepts a glob pattern. This example shows the `createFileSystemWatcher` call being used for `.clientrc` files, but if the extension needs to monitor `cpp` files, each possible C++ extension would have to be included in the blob. Have I missed a part of the api or is this the intended way for a language server to be able to respond to saves?

Language Client:
```javascript
let clientOptions: LanguageClientOptions = {
	documentSelector: ['plaintext'],
	synchronize: {
		configurationSection: 'languageServerExample',
		fileEvents: workspace.createFileSystemWatcher('**/.clientrc')
	}
}
```

Language Server:
```javascript
documents.onDidChangeContent((change) => {
	validateTextDocument(change.document);
});

connection.onDidChangeWatchedFiles((change) => {
	connection.console.log('We recevied an file change event');
});
```

**Comment by dbaeumer** [comment]
The problem is that the language server doesn't expose a Save event on the document which it should. The file system events are like the file system events in the vscode API. @hoovercj can you please open an issue here https://github.com/Microsoft/vscode-languageserver-node so that we can implement the Save event.
