### ISSUE TITLE
Re orders insatnces of vs code

### ISSUE THREAD

**Issue by EnenDaveyBoy** [microsoft/vscode#220080]
Type: <b>Feature Request</b>

Hi

I am building Azure Functions as MicroServices and when testing locally i need an instance of each microservice, so i can upto 10 instances open at once all running multiple functions, plus a frontend like next js.

however there are times i need to restart vs code because the debugger breaks and won't restart after trying to run it with errors and it not attaching properly and not ending, if i have to change things files which require a full restart, or just forgetting to open one up because im a cluts.

however its always nice to know the order so you can access the the right instance easily. and being able to put them back in order would be greate.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by roblourens** [comment]
Not sure, what you mean by "order", can you explain more?

And you can file an issue on the repo for the debug extension you're using, if you wnat

**Comment by EnenDaveyBoy** [comment]
so i open an instance of vs code and i open x c# solution, i start another instance of vs code and i open y c# solution, i open another instance z nextui folder, when you mouse over the vs code icon in the tool bar they are order x, y and z, however i now want to focus more x so placing after z makes more sense or i tend to want to order my instances in order they are called my the process so there easy to find, but i can sometimes need to add more instance which then puts them out of order, and its a pain.

**Comment by roblourens** [comment]
I see. I don't think this is really under VS Code's control. I think this is up to the OS. You might be interested in a multiroot workspace: https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by EnenDaveyBoy** [comment]
i am on windows if it makes a differences, not a problem, i already use multi root workspaces for each solution, the problem with them is if they access the same library as the same time it causes an error and then functions don't run
