### ISSUE TITLE
Code lines are struckthrough and red

### ISSUE THREAD

**Issue by JoelMTaylor** [microsoft/vscode#220022]
Type: <b>Bug</b>

When I opened my workspace, I noticed that some or all (depending on the page) of the text is red and struckthrough (strikethrough appearance). I did nothing.

I disabled all extensions and restarted the window, and it is still the same. I assume this was an update, but I cannot see why based on the update docs.

I am writing documents using Markdown. This is for a docs site that uses Retype. 

Image:
![image](https://github.com/microsoft/vscode/assets/97919641/868159cc-f6f6-4958-9e72-9575f319830e)

Code snippet:
```
---
{{ include "joel-taylor" }}
date: 2024-05-17
description:
title:
label:
categories:
 - Teachers
 - Curriculum Managers
 - School Leaders
tags:
image: null
icon:
layout: default
order: 46
visibility: public
---

# Class Tools

{{ include "under-construction" }}

## Introduction



## Class Placemat

The **Class Placemat** summarises key class data for the teacher's review.

 1. Select the Year Level, Subject and Class, then click **Find**.
 2. Students are grouped based on their previous end of semester result in the subject (into A's, B's, etc.).\
```

Seems to be due to use of `---`  - which is used for [page metadata](https://retype.com/configuration/page/). Without these, it does not occur.
![image](https://github.com/microsoft/vscode/assets/97919641/cd40f286-dc7c-45c3-b540-9ad39abb72f2)

VS Code version: Code - Insiders 1.92.0-insider (34f8428e4b0e3bf822f4b9e8b4e3e0cab69ef2ce, 2024-07-04T05:49:09.268Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (16.21GB free)|
|Process Argv|--crash-reporter-id ee44e8e0-455e-4929-a9e8-c4c377757877|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azureautomation|azu|1.2.4
azurite|Azu|3.31.0
spellright|ban|3.0.132
solargraph|cas|0.24.1
bracket-pair-toggler|dzh|0.0.3
vscode-msgraph-autocomplete|eli|1.2.0
vscode-msgraph-essentials|eli|0.0.5
code-runner|for|0.12.2
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.3
gc-excelviewer|Gra|4.2.59
path-autocomplete|ion|1.25.0
RelativePath|jak|1.5.0
powerplatform-vscode|mic|2.0.61
vscode-azurefunctions|ms-|1.15.1
vscode-azureresourcegroups|ms-|0.9.1
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.15.3
vscode-azurevirtualmachines|ms-|0.6.5
remote-wsl|ms-|0.88.2
azure-account|ms-|0.12.0
azure-repos|ms-|0.38.0
powershell|ms-|2024.2.2
remote-repositories|ms-|0.40.0
indent-rainbow|ode|8.3.1
markdown-preview-enhanced|shd|0.8.13
code-spell-checker|str|3.0.1
vscode-ltex|val|13.1.0
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
chatpanelt:31014475
da93g388:31013173
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
nb_pri_only:31057983
nativerepl2:31071685
refactort:31084545
pythonrstrctxt:31089940
0c838689:31088353

```

</details>

**Comment by RedCMD** [comment]
screenshot and
````markdown
```markdown
code snippet
```
````
please

**Comment by JoelMTaylor** [comment]
> screenshot and
> 
> ```
> ```markdown
> code snippet
> ```
> ```
> 
> please

@RedCMD, I have updated the original post with the screenshots and code.

It seems that the theme - the colours and formatting of the code - has changed, too. I assume this is related.

**Comment by RedCMD** [comment]
the [page metadata](https://retype.com/configuration/page/) is written in YAML

YAML states anything after the `{{ include "joel-taylor" }}` is invalid (because it is missing an ending `:`)
however that text is preprocessed into valid YAML when the markdown is loaded

I've removed the ~~strikethrough~~
and filled a bug report to https://github.com/microsoft/vscode-markdown-tm-grammar/issues/164 for YAML escaping the ending `---`
I'll change the how an invalid `{{ ... }}` is interrupted

**Comment by RedCMD** [comment]
Will still need to wait for the fix at https://github.com/microsoft/vscode-markdown-tm-grammar/pull/162

![image](https://github.com/microsoft/vscode/assets/33529441/e4fe312d-49ea-4b63-aafd-69cac24f7e3e)

**Comment by mjbvz** [comment]
Fixed by picking up the latest grammar. Thanks @RedCMD!
