### ISSUE TITLE
Raw HTML in a header gets included in its id attribute (in preview mode)

### ISSUE THREAD

**Issue by AZeed18** [microsoft/vscode#220064]
Does this issue occur when all extensions are disabled? Yes

- VS Code Version: 1.91.0.0
- OS Version: Windows 10 build 19045.4598

Steps to Reproduce:

1. Put a header with a raw HTML element
    ```md
    # <mark>header</mark>
    ```
2. Raw HTML is included in markdown header anchors (`mark` is included!)
    ```md
    ![](#markheadermark)
    ```

**Comment by AZeed18** [comment]
Note: links without the HTML tag work in editor mode only

**Comment by mjbvz** [comment]
This is for path completions, right? Seems to work fine for me

![Image](https://github.com/user-attachments/assets/7c5d5a1b-7211-4d5d-9f6e-1e21760b26e6)

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by AZeed18** [comment]
I'm not referring to autocompletion, but what I mean is for the anchor links to work in **preview** mode (editor mode is fine) they have to include raw HTML tags

I.e., the ids generated for headers include raw HTML tags

I tested it in with all extensions disabled and same result, but still I will test it in insiders build

**Comment by AZeed18** [comment]
@mjbvz, tested at <https://insiders.vscode.dev> (clean), same results
