### ISSUE TITLE
Suggestion: Offer a secondary slower release cycle?

### ISSUE THREAD

**Issue by johanbove** [Microsoft/vscode#22001]
The amount of work done in this project is amazing and highly commendable. Thank you!

However if Visual Studio Code wants to become more popular I feel like a slower release cycle would be welcomed as professionals can avoid issues that happen after speedy releases. Things / bugs / issues slip through too easily on the monthly release cycle and sometimes new functionality is not wanted or needed, at least not for a while.

Therefor I would like to offer this suggestion: 

Can we create two release paths for Visual Studio Code: a fast-lane (current monthly releases) and a slower lane of quarterly releases?

Of course, bug fixes and patches could be released still on a monthly basis.

People can then pick if they would prefer updates faster or like to stick with an existing release longer.
Thanks for reading and your consideration.

**Comment by chrisdias** [comment]
We are grooming our issue backlog this month (see #58224). This issue doesn't meet the criteria we've established for keeping the issue open ([criteria](https://github.com/Microsoft/vscode/wiki/Issue-Grooming): not enough votes, unlikely to be done in the next 6-12 months, doesn't align with roadmap).
