### ISSUE TITLE
Allow to write multiple rules for the same glob pattern

### ISSUE THREAD

**Issue by Midqiu** [Microsoft/vscode#22007]
![image](https://cloud.githubusercontent.com/assets/5728399/23587169/aa26138c-01e1-11e7-9ea3-db4b79b3e49c.png)

**Comment by bpasero** [comment]
@egamma didn't you once had a trick to make this work by producing a similar matching pattern on the left hand side that was still different so that you can use it in that JSON?

**Comment by bpasero** [comment]
Closing, since questions are better asked here: http://stackoverflow.com/questions/tagged/vscode

**Comment by egamma** [comment]
@Midqiu @bpasero 

This is how to do it (filed an issue to add this to the FAQ)
   
"**/*.js": { "when": "$(basename).ts" },
"**/**.js": { "when": "$(basename).tsx" }

**Comment by bpasero** [comment]
@egamma awesome trick!
