### ISSUE TITLE
VSCode and Chrome deadlock in Windows 11

### ISSUE THREAD

**Issue by Arlen22** [microsoft/vscode#220093]
Does this issue occur when all extensions are disabled?: Unsure, but presumably yes.

- VS Code Version: Multiple, for at least the past year, I think
- OS Version: Windows 11

Steps to Reproduce:

1. Wake computer from sleep when both Chrome and VSCode are open.
2. Watch both programs lock up at the same time within a few minutes of startup, and fix by closing and reopening one of them.

I have also experienced this with other electron-based programs if they happen to have any windows open. Basically all chromium based windows will lock up at once. I have to close all but one program in order to break the freeze, which is why it seems like a deadlock. 

That being said, since I'm having the problem the most with VS code, I'm filing it here.

**Comment by deepak1556** [comment]
Can you start the application with `code --verbose` and attach the output when this issue happens
