### ISSUE TITLE
Component Intellisense and imports break in astro with latest release

### ISSUE THREAD

**Issue by lstephensca** [microsoft/vscode#220082]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.91.0
- OS Version: 13.2.1

After upgrading (automatically) from 1.90.2 to 1.91.0, intellisense within astro projects as it relates to component suggestions and imports appear to be broken. Downgrading to the previous version appears to solve the issue. 

```
---
import DemoHey from "@components/DemoHey";
import WhyWhy from "@components/WhyWhy";
import DefaultLayout from "@layouts/DefaultLayout.astro";
---

<DefaultLayout>
  <main>
    <DemoHey />
    <WhyWhy title="A title" body="some sample text" />
  </main>
</DefaultLayout>
```

If I do upgrade to the latest version, I will sporadically get intellisense for components, but no imports occur.

**Comment by mjbvz** [comment]
Please file this against the astro extension. We don't support that language out of the box
