### ISSUE TITLE
Cached text remains even after deleting.

### ISSUE THREAD

**Issue by dehghani-mehdi** [Microsoft/vscode#22004]
Hello,

- VSCode Version: 1.10.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open up `script.js`, already contains `id` (some js variable)
2. Select all content & press Del (_I mean I deleted all `script.js`'s content_)
3. if I start typing `i`, VSCode show me `id` as suggestion. it got happens after about 30 minutes later too, so seems like the cached items remains until re-open VSCode.

p.s: `id` here is just an example. also I'm not sure it happens in other editors (css, html, ...) too.

Thanks!

**Comment by jrieken** [comment]
My assumption is that is JavaScript all symbols completion

**Comment by mjbvz** [comment]
@dehghani-mehdi If you enter `id` in your document and run `go to definition`, are any results returned? I want to check if there is a definition in another file that is getting picked up

**Comment by dehghani-mehdi** [comment]
@mjbvz no, because I have just 1 js file in opened folder.

**Comment by mjbvz** [comment]
@dehghani-mehdi To help us investigate, please:

* set `"typescript.tsserver.trace": "verbose"` in your user settings
* Restart VSCode with extensions disabled: `--disable-extensions`
* Reproduce the issue
* Share the output from the `TypeScript` section of the Output Panel

**Comment by dehghani-mehdi** [comment]
@mjbvz I follow the steps, but I could not see anything in output panel, btw take a look at:
![aaa](https://cloud.githubusercontent.com/assets/9152330/23691594/a965120a-03de-11e7-885e-6f142419face.gif)

**Comment by mjbvz** [comment]
@dehghani-mehdi Make sure to switch to the `TypeScript` section of the output panel using the drop down. Also, please share the complete source of the file that you are working on

**Comment by dehghani-mehdi** [comment]
@mjbvz Okay, I'll asap!

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this
