### ISSUE TITLE
Quick copy lines in diff view

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#22003]
When I'm comparing files before I commit them to Git, it would often be useful to quickly revert a hunk by clicking some small arrow like this (I'm not a designer):

![image](https://cloud.githubusercontent.com/assets/101152/23585829/56d5e3c8-0188-11e7-85db-23b696ae088a.png)

I use a similar feature in Beyond Compare (note that in this example, both sides are editable hence the arrows work in both directions):

![image](https://cloud.githubusercontent.com/assets/101152/23585835/86824684-0188-11e7-9f73-135b51a3baf7.png)

**Comment by joaomoreno** [comment]
This is coming with #18615

**Comment by borekb** [comment]
@joaomoreno Any chance this could be reopened? I think this request is different from what was delivered #18615 (specifically, https://github.com/Microsoft/vscode/issues/18615#issuecomment-297340851):

- #18615 only works in the context of SCM, not in generic diffs ('Select for Compare' + 'Compare with ...')
- Clicking an arrow is a faster and more discoverable UI.

**Comment by Otiel** [comment]
I also vote to reopen this.
