### ISSUE TITLE
Menu leaked in variables view

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#220044]
I noticed while addressing https://github.com/microsoft/vscode/issues/213145 that the menu in `renderActionBar` is not disposed:

https://github.com/microsoft/vscode/blob/31493f3a024372180610abfa199de4f324712900/src/vs/workbench/contrib/debug/browser/variablesView.ts#L503-L508

**Comment by alexr00** [comment]
There a couple `this.menuService.createMenu` there that should be disposed. I'm adding a `getMenuActions` method to the menu service that you might find useful if you would just dispose the menu right away: https://github.com/microsoft/vscode/pull/219964

**Comment by connor4312** [comment]
Cool, I'll wait until that PR is in and adopt it there and in several other places :)

**Comment by alexr00** [comment]
I ended up just adopting `getMenuActions` in all the obvious places!
