### ISSUE TITLE
highlighting color not clear 

### ISSUE THREAD

**Issue by AsimNet** [Microsoft/vscode#22009]
- VSCode Version: 1.10.1
- OS Version:10.12.3

Steps to Reproduce:

1. set your theme solarized light
2.highlight any text

![screen shot 2017-03-05 at 3 41 06 pm](https://cloud.githubusercontent.com/assets/3624441/23588135/0a1089f2-01ca-11e7-8978-2ce4eebdaa51.png)

it would be better if highlighting is darker, it's hard to deal with it now, specially if you have an apostrophe at the end.
 

thank you

**Comment by ugurozturk** [comment]
@AsimNet  your png file is not visible

**Comment by AsimNet** [comment]
@ugurozturk and now?

**Comment by ugurozturk** [comment]
@AsimNet You might look here https://marketplace.visualstudio.com/items?itemName=gerane.Theme-Solarized-light or https://github.com/gerane/VSCodeThemes

**Comment by aeschli** [comment]
We use colors of the original design of the [Solarized light](https://github.com/deplorableword/textmate-solarized/blob/master/Solarized%20(light).tmTheme) theme and rather come up with our own colors.
You might want to look at other themes to use. There's also request #11556 to allow user configurable themes.
