### ISSUE TITLE
Please fix local/code-import-pattern violations in promptInputModel.test.ts

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#220054]
`yarn eslint` was broken for some time and I re-enabled it today.. However eslint failures were reported in promptInputModel.test.ts and I disabled them. Please have a look and fix the corresponding errors.

**Comment by Tyriar** [comment]
Should have been fixed 2 days ago /duplicate https://github.com/microsoft/vscode/pull/219850
