### ISSUE TITLE
Vs Code Slow my os 

### ISSUE THREAD

**Issue by Hemil09** [microsoft/vscode#220002]
Type: <b>Performance Issue</b>

Vs Code high usage my all memory and slow my system. No such extensiona and plugins all thing just 2 filed opent they usage memory 3 gb up to and slow my os

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|5.88GB (0.32GB free)|
|Process Argv|--crash-reporter-id bbb779aa-c2b8-41eb-8249-f52df36c489a|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    82	 12232	code main
    0	     5	  2256	   crashpad-handler
    0	    95	  3596	   gpu-process
    0	    10	  4080	ptyHost
    0	    44	  4584	shared-process
    0	    14	  6412	   utility-network-service
    0	   275	  9504	window [1] (index.vue - gmfrontend - Visual Studio Code)
    0	    94	 12472	extensionHost [1]
    0	   421	  5500	     electron-nodejs (vueServerMain.js )
    0	    15	  5704	     "C:\Users\hemil\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\hemil\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=12472
    0	    68	  6008	     electron-nodejs (eslintServer.js )
    0	    44	  7068	     electron-nodejs (tsserver.js )
    0	   859	  7368	     electron-nodejs (tsserver.js )
    0	    19	  4088	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    48	 13248	     electron-nodejs (server.js )
    0	    44	 14316	fileWatcher [1]
    0	    90	 14800	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.vue - gmfrontend - Visual Studio Code)
|    Folder (gmfrontend): 3586 files
|      File types: js(725) svg(723) png(374) scss(352) json(342) vue(197)
|                  jpg(195) css(92) gif(41) md(9)
|      Conf files: settings.json(1) jsconfig.json(1) package.json(1);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
goto-alias|ant|0.1.6
vscode-eslint|dba|3.0.10
prettier-vscode|esb|10.4.0
mdc|Nux|0.2.0
nuxt-vscode-extentions|Nux|0.0.6
vetur|oct|0.37.3
vue-vscode-snippets|sdr|3.1.1
volar|Vue|2.0.26
vue|znc|0.12.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
legacy_priority:31082724

```

</details>

**Comment by deepak1556** [comment]
If the issue persists with latest stable, please share the full commandline of the processes using high cpu
