### ISSUE TITLE
Can't create/delete/edit profiles

### ISSUE THREAD

**Issue by maflAT** [microsoft/vscode#220030]
Type: <b>Bug</b>

The menu item to create/delete/edit profiles are gone.
The menu item for the new profile editor isn't there either.
Right now there is no way to manage profiles.

![grafik](https://github.com/microsoft/vscode/assets/13979550/eeeba1d3-0d76-420d-b29e-80ce96e7bb4c)

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (4.73GB free)|
|Process Argv|--crash-reporter-id decff9bd-bda7-49cb-bf7c-adcfb6f98939|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-sqlite|ale|0.14.1
vscode-json|and|1.5.2
ascii-tree-generator|apr|1.2.4
scratchpads|bue|1.0.0
ini-for-vscode|Dav|0.0.4
xml|Dot|2.5.1
gitlens|eam|15.1.0
simple-alignment|ear|1.0.1
vscode-drawio|hed|1.6.6
svg|joc|1.5.4
vsc-python-indent|Kev|1.18.0
rainbow-csv|mec|3.12.0
render-crlf|med|1.8.1
vscode-language-pack-de|MS-|1.91.2024070309
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.7.11591013
isort|ms-|2023.10.1
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.104
jupyter|ms-|2024.6.0
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cpptools|ms-|1.20.5
powershell|ms-|2024.2.2
autodocstring|njp|0.6.1
explorer-exclude|Pet|1.3.2
visual-scxml-editor|Phr|0.5.0
material-icon-theme|PKi|5.4.2
vscode-xml|red|0.27.1
vscode-sort-json|ric|1.20.0
vscode-text-tables|Rom|0.1.5
vscode-qt-for-python|sea|7.6.0
comment-divider|sta|0.4.0
rewrap|stk|1.16.3
code-spell-checker|str|3.0.1
code-spell-checker-german|str|2.3.2
even-better-toml|tam|0.19.2
markdown-all-in-one|yzh|3.6.2
vscode-python-poetry|zes|0.17.22

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
legacy_priority:31082724

```

</details>

**Comment by vuluu2k** [comment]
Same your issue, I can't create or delele my profile

**Comment by sandy081** [comment]
Can you please check if following setting is enabled?

![Image](https://github.com/user-attachments/assets/1f2a6570-7a8f-4504-962a-e3d6727340a8)

Are you able to see the actions from the gear icon?

![Image](https://github.com/user-attachments/assets/cedc9c45-b0c8-4f31-8a5a-e65d7fab4f02)

**Comment by vuluu2k** [comment]
![image](https://github.com/microsoft/vscode/assets/73820126/96be71ac-4b50-4ad9-ac35-69303be8cccd)
I don't find it in my setting @sandy081

**Comment by maflAT** [comment]
@sandy081 I had it disabled originally. With it enabled, the new, experimental profile editor shows up.

**Comment by vuluu2k** [comment]
@gjsjohnmurray  I have updated new version so I find it

**Comment by sandy081** [comment]
@maflAT Can you please confirm following?

- Disable `workbench.experimental.enableNewProfilesUI`
- Do you see profile management actions in File > Preferences Menu and Settings Gear menu?
