### ISSUE TITLE
High CPU Usage Over %300

### ISSUE THREAD

**Issue by ignacioxyz** [microsoft/vscode#220098]
Type: <b>Bug</b>

I just installed VSCode on a brand new laptop. I have not installed any extensions or opened any code projects yet. While I was installing other tools that I need, I noticed the laptop became laggy. This was caused by VSCode using over 300% of the CPU.
<img width="415" alt="Captura de pantalla 2024-07-05 a la(s) 11 01 53 a  m" src="https://github.com/microsoft/vscode/assets/92755604/620b3cbd-b1b0-43e1-8e82-fd6e51fdda71">

VS Code version: Code 1.91.0 (Universal) (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:54:18.541Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.84GB free)|
|Process Argv|--crash-reporter-id 839dded8-b689-4eb3-9c39-5bcb092b6749|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
legacy_priority:31082724

```

</details>

**Comment by githubuser6000** [comment]
Same issue on Fedora. vscode is extremely laggy, input delay is over a second, completely unuseable. 
I tried without extensions too, same issue. It works as expected a few seconds after opening any project, but then the lag kicks in and vscode occupies around 30-80% of CPU usage as reported by htop.

**Comment by githubuser6000** [comment]
![image](https://github.com/user-attachments/assets/5de912da-633e-4c85-8db5-6afb1ed05a22)

Seems to also be that vscode is capping framerate at 60 and dropping frames all over the place, even on an 120hz monitor

**Comment by deepak1556** [comment]
If the issue persists with latest stable,  please capture the cpu profile following the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process
