### ISSUE TITLE
Windows Download is unavailable 

### ISSUE THREAD

**Issue by vbzvbz** [Microsoft/vscode#22002]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.Try Download Visual Studio Code at https://code.visualstudio.com/docs/?dv=win
2.Download is unavailable

**Comment by isidorn** [comment]
Works for me.

**Comment by vbzvbz** [comment]
not for windows maybe you on linux or other ios

**Comment by isidorn** [comment]
@vbzvbz no, i tried for windows

**Comment by waderyan** [comment]
This is also working for me on all three OS's. 

@vbzvbz can you give us more information about your setup?

**Comment by vbzvbz** [comment]
https://i.imgur.com/rbW8jph.png
thats my screen when i try to download visual studio code for windows, i ask my friends to try to download but they also tell me that its unable to download so its weird if its only my pc or home

**Comment by waderyan** [comment]
Hmm... az764295 is a CDN in Azure. Looks like that is down in your region... i will investigate.

**Comment by waderyan** [comment]
Please LMK if it resolves for you.

**Comment by vbzvbz** [comment]
i will let know you when I'm able to download the visual studio code from microsoft website, but in the meanwhile could you recommend me any way around to get visual studio code on my pc since i have to do work with this program but since i cant get it im getting behind in my job

**Comment by waderyan** [comment]
Can you send me an email - wade.anderson@microsoft.com? Let's jump on a call and get to the bottom of this.
