### ISSUE TITLE
Not working with Unity

### ISSUE THREAD

**Issue by HentxiSimpLord** [microsoft/vscode#220094]
Type: <b>Bug</b>

I tryed to use VS Code with Unity but its not working. VS Code don't marks Errors in the Code. I tried every thingh I could find online but still nothing works. I'd like to totally reset VS Code but don't know how. pls help me

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz (16 x 3792)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (22.00GB free)|
|Process Argv|--crash-reporter-id 1c9758cc-7a1c-4c54-a767-a4e4bffa3c68|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.29.1
csdevkit|ms-|1.7.27
csharp|ms-|2.34.12
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.0.8
vscode-dotnet-sdk|ms-|0.8.0
remote-containers|ms-|0.375.0
unity-toolbox|pix|100.0.2
vstuc|vis|1.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
legacy_priority:31082724

```

</details>

**Comment by roblourens** [comment]
Sounds like an issue with the unity extension, you can file an issue on their repo
