### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by noctkun** [microsoft/vscode#220146]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.5.0-dev.20240603

**Steps to reproduce crash**

1.
2.
3.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `@vsintellicode/typescript-intellicode-plugin` contributed by the `VisualStudioExptTeam.vscodeintellicode` extension
- `ms-vsintellicode-typescript` contributed by the `VisualStudioExptTeam.vscodeintellicode` extension

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code - Insiders 1.91.0-insider (0da59bdde2339d6ba632524dc8f3fb6f4b8a2bcb, 2024-06-14T10:07:53.538Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.42GB (5.00GB free)|
|Process Argv|--crash-reporter-id 7fffbacf-8426-4f2c-b00f-8660094ccfeb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.13.17
exe-runner|bra|1.1.1
es7-react-js-snippets|dsz|4.4.3
code-runner|for|0.12.2
copilot|Git|1.211.0
copilot-chat|Git|0.17.0
debugpy|ms-|2024.7.11591013
python|ms-|2024.11.2024070502
vscode-pylance|ms-|2024.6.104
cmake-tools|ms-|1.18.42
cpptools|ms-|1.21.0
cpptools-extension-pack|ms-|1.3.0
vscode-react-native|msj|1.13.0
postman-for-vscode|Pos|1.1.0
vscode-rapidapi-client|Rap|1.10.2
vscode-services|rap|1.0.2
java|red|1.32.0
LiveServer|rit|5.7.9
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.23.7
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vsc_aacf:30263846
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
vscrpc:30624061
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialogc:30812479
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
chatpanelt:31014475
bdiig495:31013172
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
nb_pri_only:31057983
nativerepl2:31071685
refactort:31084545
pythonrstrctxt:31089940
0c838689:31088353

```

</details>

**Comment by mjbvz** [comment]
The warning shown in the editor and the issue text explains the likely problem and what to try:

> ❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes ...
