### ISSUE TITLE
Windows: snapped windows are not restoring correctly after restart

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#22010]
- VSCode Version: 1.10.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Launch vs code
2. To dock window to the right side of the screen
3. Restart vs code

Result:
Window height has decreased by a few pixels:
![window-restore-1](https://cloud.githubusercontent.com/assets/10602367/23587272/25dabcb6-01b1-11e7-87a3-2b5f41d027ba.jpg)
Note: window.newWindowDimensions setting does not affect the result

Expected Result:
Window height is not changed:
![window-restore-2](https://cloud.githubusercontent.com/assets/10602367/23587338/96f2f390-01b2-11e7-9f19-55e4f2b3370b.jpg)

**Comment by bpasero** [comment]
I can reproduce but I also see that the window state I am restoring is exactly the window state I am getting from electron. Maybe snapped windows have a special state (like maximized).

**Comment by Tyriar** [comment]
Snapped windows do have a special state and shouldn't be restored (if we get that info from Electron).
