### ISSUE TITLE
[bug] gulp vscode-win32-zip failed

### ISSUE THREAD

**Issue by f111fei** [Microsoft/vscode#2201]
TypeError: electron.zfsdest is not a function.

https://github.com/Microsoft/vscode/blob/master/build/gulpfile.vscode.js#L242

electron.zfsdest has removed

https://github.com/joaomoreno/gulp-atom-electron/commit/b04fd5829b5ddff7e81f105c6d6ffb0a406583c9

@joaomoreno

**Comment by joaomoreno** [comment]
Removed those targets.

**Comment by dbaeumer** [comment]
Verified that those targets are gone.
