### ISSUE TITLE
support cloning git repos or switching branches via URLs

### ISSUE THREAD

**Issue by jstrachan** [Microsoft/vscode#22014]
I [noticed](https://github.com/Microsoft/vscode-docs/issues/791) that we can open files via URLs nicely in VS Code (docs: https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/codebasics.md#opening-vs-code-with-urls).

I spotted this [Chrome plugin today for IDEA](https://chrome.google.com/webstore/detail/jetbrains-toolbox-extensi/offnedcbhjldheanlbojaefbfbllddna?hl=en) which adds an `Open in IDEA` button to Chrome when looking at github. It'd be cool to have something like this for VS Code when viewing github projects, branches or PRs so folks can click from the github site in Chrome and it'd prompt the user to clone the git repo with 1 click. 

We'd just need to add some UI support to let the user pick where to clone the git repo or to switch branches etc.

**Comment by andrii1812** [comment]
I think  it should be different app with this functionality, like it is done in JetBrain's extension that uses Toolbox app to implement this feature

**Comment by jstrachan** [comment]
@andrii1812 Toolbox is the URL handler for IDEA (which supports opening local files too). Not sure why we'd need 2 different URL handlers in 2 separate processes for VS Code just so that we can open github projects as well as local files?

**Comment by joaomoreno** [comment]
#20291
