### ISSUE TITLE
Ctrl+click moves to the wrong implementation if there are two functions with the same name

### ISSUE THREAD

**Issue by RaniSharim** [Microsoft/vscode#22011]
- VSCode Version: 1.10.1
- OS Version: windows 10

Steps to Reproduce:

1. Create two files with the following code:
function a() {
    b();
}

function b() {

}

2. Open both of them in tabs and select the "first" (leftmost) tab

3. Ctrl+click the "b()" line in the first file

4. It show the implementation int the second file.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/963221/23587678/4251b6ac-01ba-11e7-8bd6-35c2c2632a30.gif)

**Comment by mjbvz** [comment]
Thanks for the report. This looks like another manifestation of https://github.com/Microsoft/TypeScript/issues/14279

Closing as upstream
