### ISSUE TITLE
VSCode holds *.asar file locked

### ISSUE THREAD

**Issue by bzw1204** [microsoft/vscode#220134]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:
![image](https://github.com/microsoft/vscode/assets/9693637/6e53d321-cdc5-49d9-81a8-0ab7501d4f84)

1. 
2.

**Comment by lszomoru** [comment]
Please download [Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) as that will help you track down who has a lock on the file.

**Comment by bzw1204** [comment]
> Please download [Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) as that will help you track down who has a lock on the file.

![image](https://github.com/microsoft/vscode/assets/9693637/065aa635-265d-4d5d-bc20-a4b815b9ef0e)

**Comment by lszomoru** [comment]
There are multiple child processes that are run within VS Code so next we should try to understand which process is holding onto the file. You can use the "Developer: Open Process Explorer" command in VS Code which will show all processes within VS Code. You can then use the ID (ex: `29920`) to see which VS Code process is holding onto the file.

**Comment by bzw1204** [comment]
> There are multiple child processes that are run within VS Code so next we should try to understand which process is holding onto the file. You can use the "Developer: Open Process Explorer" command in VS Code which will show all processes within VS Code. You can then use the ID (ex: `29920`) to see which VS Code process is holding onto the file.

![image](https://github.com/user-attachments/assets/885c5cad-7f82-4379-943d-edd3e6155225)
I did not find the occupying process in Process Explorer, but I found out through deleting plugins one by one that it was caused by a Tencent AI intelligent suggestion plugin. Is there something wrong with how I am using Process Explorer?
The problem has been identified now, thank you very much for your help!

**Comment by bzw1204** [comment]
> Thanks for the update. I am glad that you were able to identify the extension causing this issue. As far as Process Explorer you have to use both Process Monitor and VS Code Process Explorer and check the PID of the process in both. Given that this was caused by an extension I would expect that the PID would have been one of the child processes of "extensionHost".

Thanks for your help
