### ISSUE TITLE
[decorators] After decoration can extend the length of other decorations

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#22017]
- VSCode Version: Code - Insiders 1.11.0-insider (84e56fc527047223a6ad22c31a906d4a579680d0, 2017-03-03T07:04:55.533Z)
- OS Version: Darwin x64 16.4.0

Steps to Reproduce:

1. Add an after decoration to a line that has another decoration that spans the whole line, see below

![decoration](https://cloud.githubusercontent.com/assets/641685/23589312/8be0ae62-0198-11e7-87e0-f5bae7569697.gif)

2. See that the line decoration expands into the after decoration

**Comment by alexandrudima** [comment]
Same root cause as #22018
