### ISSUE TITLE
Stucked at codespace saving file

### ISSUE THREAD

**Issue by VisualLaser10New** [microsoft/vscode#220141]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.0-insider
- OS Version: Windows 10 22H2 (19045)

After a while (not precise) vs-code-insiders is connected to a codespace, while saving, remains stucked at "Saving file ..." without any possibilities to save/open anothers file or compile a code. I can continue editing the file, but newest changes won't be saved.

Every time only possibility is to close vs-code, stop codespace and restart it, by losting last work.
I tried to create a new codespace but the problem persist.

Steps to Reproduce:
There are no steps

**Comment by bpasero** [comment]
Please report to GH Codespaces: https://github.com/community/community/discussions/categories/codespaces
