### ISSUE TITLE
[decorators] After decoration on a line with just whitespace incorrectly places the cursor

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#22018]
- VSCode Version: Code - Insiders 1.11.0-insider (84e56fc527047223a6ad22c31a906d4a579680d0, 2017-03-03T07:04:55.533Z)
- OS Version: Darwin x64 16.4.0

Steps to Reproduce:

1. Add an after decoration to a line that nothing but whitespace (space/tab) -- must also have visible whitespace off (note that the underline shown below, doesn't have any effect on this behavior -- it happens with or without any other decorations)

![decoration](https://cloud.githubusercontent.com/assets/641685/23589279/04914ef8-0198-11e7-8e4d-889cd68f6d6b.gif)

2. See that the cursor is positioned incorrectly at the end of the after decorator, rather than at the end of the content (like it does for non-whitespace only lines)

**Comment by jens1o** [comment]
Not fixed in last insider: 
![image](https://user-images.githubusercontent.com/11234139/26837461-bf4e1b70-4add-11e7-9760-2171721d3113.png)

(As long as this is the same issue)

**Comment by alexandrudima** [comment]
@jens1o Thanks for checking on this. The underline is similar to the font-weight (these font styles are applied inline to the text) and different than the squiggles which are painted on a separate layer. Let's track the underlines also in https://github.com/Microsoft/vscode/issues/28079#issuecomment-306694516
