### ISSUE TITLE
Starting code from Total Commander opens and keeps cmd open

### ISSUE THREAD

**Issue by jakubsuchybio** [Microsoft/vscode#22013]
- VSCode Version: 1.9.1
- OS Version: Windows 10 Pro version 1607 - build 14393.693

Steps to Reproduce:
1. Start Total Commander
2. In the command prompt textbox on the bottom type ```code```
3. Visual Studio Code starts, but also with cmd window, which doesn't close by itself. I can close that cmd and the Code instance still lives.

I just don't get why the cmd window won't close itself, if it isn't required to be opened for code to run.

Starting code from Total Commander:
![](http://i.imgur.com/Qiy1Me6.png)

Started code, which also started cmd window:
![](http://i.imgur.com/z4gZaXE.png)

Closed cmd window, but code is still running fine:
![](http://i.imgur.com/lahG7nU.png)

**Comment by bpasero** [comment]
I am assuming this is our CLI script starting, not Electron directly.

**Comment by joaomoreno** [comment]
Can you change `code` in Total commander to point to `code.exe` and not `bin\code.cmd`?

**Comment by jakubsuchybio** [comment]
Yeah, when I go to ```c:\Program Files (x86)\Microsoft VS Code\``` and start it via ```code.exe``` then the cmd won't open (or stay open). Can't see if it was openned or not.

**Comment by joaomoreno** [comment]
> Can't see if it was openned or not.

What do you mean?

Can you then create an alias in Total Commander to use `Code.exe` instead of `code.cmd`?

**Comment by jakubsuchybio** [comment]
> Can't see if it was openned or not.  
I literally can't see the cmd, that is why I don't know if it was or wasn't opened with the ```code.exe```

However yes, I was able to create an alias for my purpose of having it on some shortcut to run code without the cmd window. 

But I still don't get why there is that code.cmd which seems to be running, when I type only ```code``` and which is starting the cmd?

**Comment by joaomoreno** [comment]
`code.cmd` exists because we need it when running `code` from a Command Prompt, because reasons. It's what we put in the `PATH`, instead of `Code.exe`.

I'm glad you could create a command in Total Commander that unblocks you!
