### ISSUE TITLE
`terminal.external.windowsExec` not work as expected when path contains spaces

### ISSUE THREAD

**Issue by zhaojjiang** [microsoft/vscode#220129]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.91.0
- OS Version: Windows_NT_x64 10.0.22631

Steps to Reproduce:

1. install powershell 7.x
2. set `"terminal.external.windowsExec": "C:\\Program Files\\PowerShell\\7\\pwsh.exe"`
3. invoke external terminal by `Ctrl+Shift+C`
4. **the terminal title showing `\\`**

Additional Info:

**this happens not only with powershell 7.x， it may happen with all terminal which path contains space**

I found relate code: [externalTerminalService.ts#L40-L74](https://github.com/microsoft/vscode/blob/f8b1bef21437608c6fee422ab044253b13224cda/src/vs/platform/externalTerminal/node/externalTerminalService.ts#L40-L74), the code converted to node command is
```shell
# you can try this in node interactive shell, this will open a terminal with title \\
child_process.spawn('cmd.exe', ['/c', 'start', '/wait', '""', 'C:\\Program Files\\PowerShell\\7\\pwsh.exe'], {cwd: 'D:\\temp', detached: true})
```
the comment for [externalTerminalService.ts#L57-L61](https://github.com/microsoft/vscode/blob/f8b1bef21437608c6fee422ab044253b13224cda/src/vs/platform/externalTerminal/node/externalTerminalService.ts#L57-L61) said `""` used to solve something, but now it cause `\\` showing,

```js
if (exec.indexOf(' ') >= 0) {
    // The "" argument is the window title. Without this, exec doesn't work when the path
    // contains spaces
    cmdArgs.push('""');
}
```

> but i tried node command above without `'""'` and works fine,
> is this caused by system version or something else?

```shell
#  not ok
child_process.spawn('cmd.exe', ['/c', 'start', '/wait', '""', 'C:\\Program Files\\PowerShell\\7\\pwsh.exe'], {cwd: 'D:\\temp', detached: true})
# ok
child_process.spawn('cmd.exe', ['/c', 'start', '/wait', 'C:\\Program Files\\PowerShell\\7\\pwsh.exe'], {cwd: 'D:\\temp', detached: true})
```

**Comment by tisilent** [comment]
'""' => '\"\"'

**Comment by Tyriar** [comment]
To verify make sure you can still open a pwsh+cmd external terminal on Windows
