### ISSUE TITLE
Cannot find module 'original-fs' when running vs code test task on windows

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#22019]
OS: Windows 10

Steps to Reproduce:
1. Clone, install, and open vscode
```
git clone https://github.com/microsoft/vscode
cd vscode
scripts\npm install
code .
```
2. Use `ctrl+b` to run the build task. After it completes, terminate the task
3. Open the command palette and "Run test task"

**Expected:** test task runs
**Actual:** Error

> [18:07:19] Using gulpfile c:\PATH\vscode\gulpfile.js
> [18:07:19] Starting 'test'...
> { errorCode: 'load',
>   moduleId: 'original-fs',
>   neededBy: [ 'vs/code/node/windowsUtils' ],
>   detail: 
>    { Error: Cannot find module 'original-fs'
>        at Function.Module._resolveFilename (module.js:440:15)
>        at Function.Module._load (module.js:388:25)
>        at Module.require (module.js:468:17)
>        at require (internal/module.js:20:19)
>        at NodeScriptLoader.load (C:\PATH\vscode\out\vs\loader.js:609:39)
>        at OnlyOnceScriptLoader.load (C:\PATH\vscode\out\vs\loader.js:519:37)
>        at loadNextPath (C:\PATH\vscode\out\vs\loader.js:1279:41)
>        at Object.errorback (C:\PATH\vscode\out\vs\loader.js:1287:25)
>        at OnlyOnceScriptLoader.triggerErrorback (C:\PATH\vscode\out\vs\loader.js:532:36)
>        at C:\PATH\vscode\out\vs\loader.js:519:156
>        at ReadFileContext.callback (C:\PATH\vscode\out\vs\loader.js:622:25)
>        at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13) code: 'MODULE_NOT_FOUND' } }
>

**Comment by dbaeumer** [comment]
Same when running from a terminal.

@joaomoreno are you the right person with the gulp test task ?

**Comment by joaomoreno** [comment]
Don't know what `original-fs` is, but blaming its usages points to @bpasero

**Comment by bpasero** [comment]
@chrmarti I think you moved this to `code/node`, `original-fs` is provided only be electron, so you need to move it back to main imho or find a way to make this still testable.

**Comment by chrmarti** [comment]
The code doesn't depend on the unpatched `original-fs`, changing to `fs`.
