### ISSUE TITLE
File quick picker shows "deprecated PCRE2" warning as first entry, doesn't pick correctly

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/vscode#220125]
Type: <b>Bug</b>

When I pop the file quick pick menu open, I see the following:

"Deprecated. PCRE2 will be used automatically when using regex features that are only supported by..."

![Quick picker says "Deprecated. PCRE2 will be used automatically when using regex features that are only supported by..."](https://github.com/user-attachments/assets/3a750802-e8ed-41e4-99dd-a49fc1f4b992)

VS Code version: Code - Insiders 1.92.0-insider (82104a3a6cf8713b81e5bbd97960dbf5c82a816a, 2024-07-05T00:00:00.000Z)
OS version:   
Modes:

System Info: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
dprint|dpr|0.16.2
codespaces|Git|1.17.1
copilot|Git|1.211.973
copilot-chat|Git|0.18.2024070501
vscode-pull-request-github|Git|0.92.0
cmake-tools|ms-|1.18.42
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
deoptexplorer-vscode|rbu|1.1.2
cmake|twx|0.0.17

(2 theme extensions excluded)

</details>

**Comment by DanielRosenwasser** [comment]
Also, it doesn't prioritize files with a more similar name (especially ones that are currently open)

![Image](https://github.com/user-attachments/assets/34ed9fc9-1af7-489d-b90c-8fb7244f634c)

**Comment by TylerLeonhardt** [comment]
Talked to @DanielRosenwasser ... he says he's not seeing this anymore so I'm gonna close this.
