### ISSUE TITLE
Broken formatting for jsx in case :: function binding

### ISSUE THREAD

**Issue by clicman** [Microsoft/vscode#22023]
- VSCode Version:1.10.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1.Open [BadFormatting.js](https://gist.github.com/clicman/3a1c0721763b81f2eadc7ea8f95c2c02) as jsx or babel.
2. Format file (Ctrl+Shift+I).

As result formatting is brken:
![image](https://cloud.githubusercontent.com/assets/1079535/23590207/78dc142a-020e-11e7-8f0b-4f1afc25da5b.png)

If I remove :: function binding all become ok.
![image](https://cloud.githubusercontent.com/assets/1079535/23590299/9604bef2-020f-11e7-9ebb-feec9642c1a9.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14491
