### ISSUE TITLE
vim mode requested

### ISSUE THREAD

**Issue by VarunSharma3520** [microsoft/vscode#220268]
Hey! Microsoft
Can You add in-built vim mode in vs code like zed?

it is really helpful

because neovim extension actually sucks!

pls....pls......

**Comment by timsu92** [comment]
Maybe you can try this: https://marketplace.visualstudio.com/items?itemName=vscodevim.vim
Not fully implemented, but already enought for me

**Comment by VarunSharma3520** [comment]
> Maybe you can try this: https://marketplace.visualstudio.com/items?itemName=vscodevim.vim Not fully implemented, but already enough for me

I Have try but it slow and difficult to customise on windows as I do not use Arch btw!

**Comment by timsu92** [comment]
Why did you mention Arch? I'm not coming up with any Arch-specific function provided by this plugin🤔

**Comment by VarunSharma3520** [comment]
I am microsofty so I always bash Arch

**Comment by isidorn** [comment]
Closing as dup of https://github.com/microsoft/vscode/issues/114851
