### ISSUE TITLE
Find all references permanently hangs while checking for references with the method declaration file open with calls outside of that file. 

### ISSUE THREAD

**Issue by curxxx** [Microsoft/vscode#22027]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|empty-indent|DmitryDorofeev|0.2.0|
|beautify|HookyQR|0.8.8|
|minify|HookyQR|0.3.0|
|vscode-paste-and-indent|Rubymaniac|0.0.8|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.1|
|project-manager|alefragnani|0.13.2|
|path-intellisense|christian-kohler|1.2.0|
|githistory|donjayamanne|0.1.5|
|phpunit|emallin|1.0.0|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.3|
|auto-close-tag|formulahendry|0.3.9|
|code-runner|formulahendry|0.6.13|
|vs-code-phpunit-snippets|jameshrisho|0.0.2|
|theme-onedark-sublime|joshpeng|0.3.6|
|indent-rainbow|oderwat|0.4.1|;

---

Steps to Reproduce:

1. Open a php file
2. Call a method from a class outside of the class file
3. Find all references for that method while inside that class file.
4. It hangs, doesn't find the call you created in 2.

**Comment by Niinor** [comment]
same version
C/C++ Find all references can not find the result, but not hangs, no matter inside or outside the file

**Comment by roblourens** [comment]
This must have been using php-intellisense? If it's still an issue, file on that extension.
