### ISSUE TITLE
Web extension debug just hangs

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#220271]
Steps to Reproduce:

1. install latest `yo` and `generator-code`
2. run `yo code` and pick the option to do a web extension
3. open it in VS Code insiders
4. build it
5. hit F5

=> 🐛 it just hangs

![Image](https://github.com/user-attachments/assets/60d6a952-de10-4182-aed8-f0605d5fef31)

**Comment by connor4312** [comment]
Do you have any prelaunch tasks stuck/running? (ref https://github.com/microsoft/vscode/issues/218267)

**Comment by bpasero** [comment]
But how would I tell, I only see a progress bar never stopping?

**Comment by aeschli** [comment]
It would be good if the launch will show a message if it runs a task with an unknown problem matcher

**Comment by connor4312** [comment]
If you have a prelaunch task still running you will probably see a terminal and a spinner on it indicating the task didn't finish.

Closing this in favor of the previous issue unless you think this is different.
