### ISSUE TITLE
Revert git change by clicking on a git change gutter indication

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#22025]
- VSCode Version: 1.10.1
- OS Version: macOS 10.12.3

This is a feature request.

It would be really helpful if the gutter indication of a git change could be revertable by clicking on that indication. NetBeans has it and it's unbelievably addictive. Especially during prototyping.

And how it could work? If there is a "git change gutter indication", then after the click on such indication, the context menu (maybe just a small graphics with a "back" icon) could appear with an option to "Revert" that chunk.

Just try it, you will definitely love it!

Thanks a lot.

**Comment by obrejla** [comment]
More specifically after a click, the "change itself" should be shown in a popup...that's the core feature. And then show e.g. some button to revert it (or in context menu by right click).

This change showing feature is really must have...it is absolutely ineffective to go to "diff" view just to see a single change :(

A lot of devs from our team do not use VSCode just because of lack of this feature :(

Thanks!

**Comment by AndersDJohnson** [comment]
https://github.com/Microsoft/vscode/issues/10782

**Comment by usernamehw** [comment]
@joaomoreno, isn't this implemented in https://github.com/Microsoft/vscode/issues/10782 ?
