### ISSUE TITLE
Can't spawn long-running process from debug adapter

### ISSUE THREAD

**Issue by hbenl** [Microsoft/vscode#22022]
- VSCode Version: 1.10.1
- OS Version: Windows 7

In [my debug adapter](https://github.com/hbenl/vscode-firefox-debug) I want to be able to spawn Firefox as a long-running process so that future debugging sessions can re-attach to it:
```
let childProc = spawn(firefoxPath, args, { detached: true, stdio: 'ignore' });
childProc.unref();
```
However, on Windows the Firefox process is still terminated at the end of the debugging session.

I am now using a workaround: I use `fork` to create another node process and spawn Firefox from there - now Firefox keeps running at the end of the debugging session.

**Comment by isidorn** [comment]
I guess this is a designed.
On stop of debug session vscode will send the disconnect to your adapter and then shut it down. Beacuase your process created new process I believe these are shut down as well.
What do you do in this situation for the chrome debugger @roblourens 

fyi @weinand

**Comment by weinand** [comment]
@hbenl yes, the current behaviour works as designed.
A workaround would be to launch your long running process in the extension instead of the debug adapter (there is even a hook command "startDebug" which you can implement to get notified when VS Code is about to launch a new debug adapter).

In addition please see https://github.com/Microsoft/vscode/issues/22080 for a related feature that could be of interest for you.

**Comment by hbenl** [comment]
I think you misunderstood me: Of course the termination of the debug adapter is as designed.
And when the debug adapter process is terminated, so are processes spawned by this process - _except_ if it is spawned with the options shown in the OP. With these options, the spawned process should _survive_ the termination of the spawning process. And it does survive if it is spawned like this from any other node process. Only when I use these lines in a debug adapter process, the spawned process does not survive the termination of the spawning process...

It's not a big deal, especially since there are workarounds, but I still think it's a bug.

**Comment by roblourens** [comment]
I've seen the same thing, I assume it's related to electron or something but haven't figured it out. I hadn't found that workaround though. Does the forked node process get killed when the debug adapter stops?

**Comment by hbenl** [comment]
@roblourens This is where it gets weird: currently the forked process exits immediately after spawning Firefox, and Firefox keeps running. But if I change the script running in the forked process so that the forked process doesn't quit (e.g. by appending some setTimeout() call at the end) then the forked process is terminated when the debug adapter is terminated (this is what I expected) and the Firefox process that it spawned is suddenly also terminated!
Even weirder: on Linux if I spawn Firefox directly from the debug adapter, it keeps running when the debug adapter is terminated (as expected - that's what the options in the OP are for). _But_ if I fork a process that in turn spawns Firefox and keep the forked process running, it will be terminated when the debug adapter is terminated (as expected) and it will also terminate Firefox (WTF?)
