### ISSUE TITLE
Regular expressions search - VSC hags

### ISSUE THREAD

**Issue by sasa-cj-jovanovic** [Microsoft/vscode#22020]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|htmltagwrap|bradgashler|0.0.3|
|jsrefactor|cmstead|0.7.2|
|jshint|dbaeumer|0.10.15|
|githistory|donjayamanne|0.1.5|
|debugger-for-chrome|msjsdiag|2.6.0|
|code-spell-checker|streetsidesoftware|0.17.2|;

---

When irregular regexp is used - VSC hangs

Steps to Reproduce:

1. open search in all files 
2. <sup(.+)*(.+)</sup    - forgotten escape on star 
2. click on replace in all files

**Comment by roblourens** [comment]
Covered by #16665 - If we don't take ripgrep this month, I should fix it.
