### ISSUE TITLE
Setting ctrl+f<num> on Mac as a Keyboard shortcut does not work

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#22029]
- VSCode Version: 1.10.1
- OS Version: macOS Sierra 10.12.3
- Locales: cs_CZ

Steps to Reproduce:

1. set some grunt task to be runnable by keybinding "ctrl+f6" in keybindings.json
2. press "ctrl+f6"
3. nothing happens...it does not work
4. try to set it to e.g. "cmd+f6"
5. press "cmd+f6"
6. it works!

Thanks a lot!

**Comment by alexandrudima** [comment]
@obrejla Can you please try the following steps and check if VS Code receives these key-presses?

There are a number of reasons why certain keybindings would not reach VS Code. e.g.: the OS binds OS functionality to them, other installed sofware "captures and steals" them, etc.

### To find out if a keybinding arrives in VS Code:

1. Open `Preferences` > `Keyboard Shortcuts`
2. Click on `Define Keybinding`
3. Press your desired key combination
(e.g. doing it for <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>1</kbd>):
![image](https://cloud.githubusercontent.com/assets/5047891/22168002/1df3bb24-df6a-11e6-93f8-0842e8f37b3d.png)
4. If the key combination does not reflect what you press or shows "unknown", it means VS Code is not receiving these key down events.

**Comment by obrejla** [comment]
Thanks for the response.

The result is: ctrl+unknown for ctrl+f6

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in today's Insiders build) appear to behave correctly for F keys. I have attached a standard QWERTY keyboard to a mac mini and configured OSX to use the US layout. Pressing F keys appear to be interpreted correctly:

![image](https://cloud.githubusercontent.com/assets/5047891/24297854/7630eb70-10a4-11e7-9c04-e2d2082522f8.png)
