### ISSUE TITLE
vs repository error

### ISSUE THREAD

**Issue by tjp2579** [Microsoft/vscode#22032]
- VSCode Version: error There was an issue running a git operation. Please review the output or use a console PLEASE help me connect 
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Seems like a git issue - click on the view > output > choose git and it should have more details as to what is the cause of the issue. 
This is not a forum for asking questions but for filling bugs to vscode. Thus closing.
