### ISSUE TITLE
Disabling the bottom bar showing up on startup

### ISSUE THREAD

**Issue by sebhewelt** [Microsoft/vscode#22033]
- VSCode Version:
February 2017
- OS Version:
Windows 10

Steps to Reproduce:

1. I open VS Code and the bottom bar with "Problems" and "Terminal" tabs is expanded.

What i would like to have is an option to prevent the bottom bar from being expanded on startup.

**Comment by isidorn** [comment]
It will stop being expanded if you simply close it. Try ctrl + J. It should remain hidden.
If that is not the case let me know and I can reopen this issue
