### ISSUE TITLE
Linux Nautilus Integration

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [Microsoft/vscode#22036]
When in Windows, if I right-click a file or folder, in the context menu I have an option to open the file/folder with VSCode.

I'd like to ask to have the same behavior in Linux.

A solution for that is the `python-nautilus` that allows for the creation of context menus on nautilus. Please visit https://wiki.gnome.org/Projects/NautilusPython

**Comment by mortezaPRK** [comment]
You may want to use this package. http://www.nautilus-actions.org/

**Comment by RicardoEPRodrigues** [comment]
@mortezaPRK are you able to add context menu entries without the GUI? From what I've seen you always need the user to create a new entry with the Configuration Tool.

**Comment by RicardoEPRodrigues** [comment]
I'll even give you the solution! 😄 

[VSCodeExtension.zip](https://github.com/Microsoft/vscode/files/821028/VSCodeExtension.zip)

Just unzip and `make`. **BEWARE:** Your nautilus will quit!

**Comment by Tyriar** [comment]
I tweeted about this recently, we could probably install the entry in the deb package https://twitter.com/Tyriar/status/807315495644893184, I think there's a CLI that can be used to add it so it won't break existing entries.

**Comment by Tyriar** [comment]
Actually I think this is the CLI https://code.visualstudio.com/docs/setup/linux#_xdgopen

**Comment by RicardoEPRodrigues** [comment]
That would replace my default editor with VSCode. What I mentioned was actually an extra entry on the context menu that allowed to open the file or **folder** in VSCode.

![screenshot](https://cloud.githubusercontent.com/assets/7673578/23623807/4d02168c-029b-11e7-8c17-4073ed7dc5ab.png)

![screenshot2](https://cloud.githubusercontent.com/assets/7673578/23623859/896de362-029b-11e7-9b6f-db612990b7a4.png)

**Comment by Tyriar** [comment]
Ah, I think that would be better off somewhere near https://code.visualstudio.com/docs/setup/linux#_setting-vs-code-as-the-default-text-editor on the website

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/Microsoft/vscode-docs/issues/873
