### ISSUE TITLE
Build error on OS X

### ISSUE THREAD

**Issue by aayushkapoor206** [Microsoft/vscode#2203]
Whenever I try to build, i get the error:
`Error: Cannot find module '/Users/aayushkapoor206/GitHub/vscode/extensions/vscode-api-tests/node_modules/vscode/bin/install'`
[npm-debug.log.zip](https://github.com/Microsoft/vscode/files/102049/npm-debug.log.zip)

**Comment by jcperez** [comment]
@aayushkapoor206 Which version of npm do you have?

**Comment by aayushkapoor206** [comment]
It's 3.5.3. I attached the debug log along if that'll help.

**Comment by aayushkapoor206** [comment]
I cloned again in a different directory and this time it worked!
