### ISSUE TITLE
Allow to configure `window.title` with _external variables_

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#22037]
Hi,

In the February Release, we can now [Customize the Window Title](https://code.visualstudio.com/updates/v1_10#_configurable-window-title), based on a set of variables, which is a great feature 👍 

Had you thought about allowing extensions to _publish new variables_ to be used by `window.title` setting?

[This issue](https://github.com/alefragnani/vscode-project-manager/issues/98) was added on my  [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) extension, and the idea is to _publish_ the `Project Name`.

I was thinking that it could be achieved using something like the `setContext` command, used for customizing key bindings rules

Thanks in advance

**Comment by bpasero** [comment]
Yes, we have a similar request to put the current git branch into the title, which imho is also a variable that is provided from an extension and not core.

**Comment by dan185818** [comment]
I would love to have the ability to pull in environment variables to the window.title also.  The reason for this is that I have an administrative account and a regular account. Plus we're in the middle of a domain migration, so I actually end up with 4 accounts I could be using.  I log in with my regular account, which has NO elevated AD permissions.  With the PowerShell ISE, I am able to have the username prepended to the title bar text, which tells me which user is running when I do a "run as different user".  This means I can tell at a glance if the PS script will be able to change things in AD (or on servers etc).  With VS Code, I have to guess.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
