### ISSUE TITLE
mini map background color not using background color

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#22030]
playing around with themes
mini map takes "background" color if set, like edit/tree pane does
mini map does not take "background" color from the base theme specified with the uiTheme tag

so if I make a empty theme with no settings except pointing to vs or vs-dark ui theme
the light one will have light background
the dark one will have dark background but light mini map background

**Comment by rakkarage** [comment]
![2017-03-06](https://cloud.githubusercontent.com/assets/962340/23630962/f6fe0436-028a-11e7-8e59-145440aff483.png)
![2017-03-06 1](https://cloud.githubusercontent.com/assets/962340/23630968/fa2e8fd6-028a-11e7-96e6-3344d463cea6.png)

**Comment by alexandrudima** [comment]
@aeschli the theme service is the place which knows if a theme is dark or light. It could enforce the presence of a "default" foreground and "default" background in themes where these are not set. At the TMSyntax level we no longer know if a theme is dark or light.

**Comment by rakkarage** [comment]
even though I do not set a background color the base theme background color is being inherited and used by many ui elements like editor background, tabs, tree view already

this is usually not a problem because usually a theme can/does specify a background to hide this

but I was trying to use the same file for both light and dark and therefore had to remove my background color to inherit it

thanks
