### ISSUE TITLE
Setting theme doesn't respect indentation in settings

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#22031]
* Open the command palette
* Choose "Color theme"
* Select a theme
* Open the command palette
* Choose user settings

**Expected:** The theme setting would match the indentation style of the settings file

**Actual:** It uses tabs instead of spaces despite the file using only spaces and the settings configured to use spaces.

![image](https://cloud.githubusercontent.com/assets/2957173/23592025/e7d2950c-01fa-11e7-898d-612b66b4d7b3.png)

**Comment by sandy081** [comment]
Duplicates #19152
