### ISSUE TITLE
TypeScript意外终止

### ISSUE THREAD

**Issue by caogenyin** [Microsoft/vscode#22039]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|csharp|ms-vscode|1.7.0|
|vscode-icons|robertohuertasm|7.3.0|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.
2.

**Comment by cca313** [comment]
看看是不是360删了

**Comment by bucaixiaot** [comment]
我都没有完整的安装过，你能把你的整个安装命令让我看看吗

**Comment by caogenyin** [comment]
@cca313 果然是360干的

**Comment by isidorn** [comment]
Please file this issue in english with reproducable steps. Closing until then

**Comment by cca313** [comment]
360 delete the files after we installed vs code @isidorn
