### ISSUE TITLE
Intellisence not recognizing folders as modules for node

### ISSUE THREAD

**Issue by u9520107** [Microsoft/vscode#22043]
F12 to find definition only works if the path points to a js file. Doesn't work when node style index based modules are used.

```javascript
import work from './src/work'; // => ./src/work.js
import notWorking from './src/notWorking'; // => ./src/notWorking/index.js

```

- VSCode Version: 1.10.1
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Press F12 on desired module imports to try to jump to the file.
2. Doesn't work if the path points to a folder containing a index.js file.

**Comment by mjbvz** [comment]
Try creating a `jsconfig.json` in the root of your workspace:

```json
{
    "compilerOptions": {
        "module": "commonjs"
    }
}
```

This lets our JavaScript and TypeScript language tools know that you are working with node.js style module.
