### ISSUE TITLE
[html] attribute on separate line formatting

### ISSUE THREAD

**Issue by stephenlautier** [Microsoft/vscode#2204]
HTML Formatting ideally should have a feature to separate attributes on new lines when using `format code`.

e.g.

``` html
<my-hero-list [heroes]="heroes" (selectHero)="onSelect($event)" class="nav"></my-hero-list>
```

When using format code should be formatted as:

``` html
<my-hero-list [heroes]="heroes" 
    (selectHero)="onSelect($event)"
    class="nav">
</my-hero-list>
```

**Comment by JVimes** [comment]
From [what I've read](https://github.com/Microsoft/vscode/issues/4806#issuecomment-204279786), the [js-beautify](https://github.com/beautify-web/js-beautify) project is what's used for HTML formatting in VSCode. I submitted [a suggestion](https://github.com/beautify-web/js-beautify/issues/916) to them to implement this feature (feel free to up-vote it). If/when they do, VSCode will need to implement the configuration to support the feature.

**Comment by siulung4073** [comment]
+1

**Comment by Maus3rVonDutch** [comment]
+1

**Comment by Maus3rVonDutch** [comment]
**For people wanting this feature right now, read on.**

Ok it seems this function is already implemented on js-beautify, see: https://github.com/beautify-web/js-beautify and look for this setting:
` -A, --wrap-attributes              Wrap attributes to new lines [auto|force] ["auto"]`

So, I did some digging in the source code and found the setting in the _beautify-html.js_ script. I modified the **wrap-attributes** settings from **auto** to **force** and voila, it works!

Here is the repro for people wanting this feature also:

* locate the **beautify-html.js** file (mine was located here: _C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\languages\lib\common_) and create a backup of the original file, just in case you mess up the file.
* For people on Windows, first copy the original file to a location where you are allowed to modify the file, because you are not allowed to edit the file directly at the 'Program Files (x86)' folder.
* Then look for this setting: w=void 0===i.wrap_attributes?"**auto**":i.wrap_a and just replace **auto** with **force**, so you get: w=void 0===i.wrap_attributes?"**force**":i.wrap_a
* Now just copy back the modified file and restart VS Code. Now you should be able to format the html with Shift+Alt+F and get the html attribute formatted on separate lines.

**Comment by stephenlautier** [comment]
@Maus3rVonDutch  Thanks for this temporarily solution! The only ugly way obviously is to set it up, otherwise it would be brilliant.

**Comment by chief10** [comment]
+1 to wanting this

**Comment by mae1st0rm** [comment]
+1, MUST HAVE!

**Comment by farin99** [comment]
+1

**Comment by stochris** [comment]
+1

**Comment by chief10** [comment]
+1

**Comment by MeirionHughes** [comment]
Yeah this is really needed; doing binding interpolations on things like SVG element attributes can make the elements rather long.

**Comment by iamdevlinph** [comment]
+1 For readability of elements

**Comment by Emidomenge** [comment]
@Maus3rVonDutch 
Your solution works pretty well until version **1.6.1** of VS Code

I updated to 1.7.1 and it doesn't work anymore, is there any other solution/fix ?

**Comment by cristian-stoicescu** [comment]
It seems a new option was added for the ---wrap-attributes flag ( force-aligned ) js-beautify library. Maybe this solves the problem?

**Comment by Emidomenge** [comment]
Indeed, I saw this new option too but it doesn't work also.

I tried to set **wrap-attributes** settings to : 

- 'force' --> didn't work
- 'force-aligned' --> didn't work
- 'force aligned' --> didn't work

:( ...

**Comment by hneuer** [comment]
'force-align' is not out yet, see https://github.com/beautify-web/js-beautify/issues/916 

Hopefully 1.6.5 of js-beautify will come out soon so this feature can find its way into vscode!

**Comment by mribichich** [comment]
I'm using "wrap_attributes" with jsbeautify in vscode.

I have:

vscode: *1.7.1*
js-beautify for VS Code: *0.4.1*
Embedded version of js-beautify: *1.6.4 *

I'm using a `.jsbeautifyrc` file with:

```
{
  "wrap_attributes": "force"
}
```

then calling `Beautify file` cmd works fine

**Comment by charlieargue** [comment]
Is anyone having this break with the latest vscode? (1.8.1)? 

My jsbeautify wrap_attributes stopped working with that version. 

Thanks!

**Comment by mrmashal** [comment]
Using VSCode 1.9.0 with the following setting works fine:

    "html.format.wrapAttributes": "force"

**Comment by vitaly-andriyanets** [comment]
Using 1.9.1 on code:
`<div>
    <div>
        <div attr1="" attr2=""></div>
    </div>
</div>`

With settings:
`"html.format.wrapAttributes": "force"`

Result:
`<div>
    <div>
        <div attr1=""
             attr2=""></div>
</div>
</div>`

**Comment by vitaly-andriyanets** [comment]
Using 1.9.1 on code:
```html
<div>
    <div>
        <div attr1="" attr2=""></div>
    </div>
</div>
```
With settings:
`"html.format.wrapAttributes": "force"`
Result:
```html
<div>
    <div>
        <div attr1=""
             attr2=""></div>
</div>
</div>
```
With js-beautify extension and .jsbeautifyrc:
```
{
    "wrap_attributes": "force"
}
```
the same result

**Comment by aeschli** [comment]
@vitaly-andriyanets You can file your issue directly against https://github.com/beautify-web/js-beautify which is the formatter VSCode use.

**Comment by mvdenk** [comment]
This issue is [fixed](https://github.com/beautify-web/js-beautify/issues/1115) in version js-beautify 1.6.9

**Comment by vigie** [comment]
@mvdenk Is there any way to get vscode to "consume" this js-beatify fix? I am on VS Code 1.9.1 and experiencing this issue.

**Comment by iamdevlinph** [comment]
@vigie I'm also at VS Code 1.9.1 and it works for me. I just use it like this: `"html.format.wrapAttributes": "force"` but the problem is that the closing tags of htmls will also be broken.

**Comment by aeschli** [comment]
An updated version for jsbeautify went into VSCode 1.10 has the fix.

**Comment by mvdenk** [comment]
@vigie To temporary fix this in VSCode 1.9.1 you can replace C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\html\server\node_modules\vscode-html-languageservice\lib\beautify\beautify-html.js with [beautify-hytml.js](https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify-html.js).

**Comment by vigie** [comment]
@mvdenk Works like a charm, thanks!

**Comment by mtpultz** [comment]
@mvdenk using the setting `"html.format.wrapAttributes": "force",` in VSCode v1.10.2 the format of the attributes are not aligned with the initial attribute anymore:

```
<div [ngClass]="{'has-error': formError.password}">
  <label for="password">Password<span>*</span></label>
  <input id="password"
    type="password"
    placeholder="Password"
    formControlName="password">
  <span *ngIf="formError.password">
    {{formError.password}}
  </span>
</div>
```

instead of:

```
<div [ngClass]="{'has-error': formError.password}">
  <label for="password">Password<span>*</span></label>
  <input id="password"
         type="password"
         placeholder="Password"
         formControlName="password">
  <span *ngIf="formError.password">
    {{formError.password}}
  </span>
</div>
```

**Comment by Gheoan** [comment]
@mtpultz The code sample you showed is not valid html. I don't think `js-beautify` supports that. This is one of the reason I do not like Angular ;).

**Comment by lacroixdavid1** [comment]
@mtpultz what about `"html.format.wrapAttributes": "force-aligned"` ?

**Comment by zatchgordon** [comment]
@mtpultz That seems to be working for me

**Comment by mtpultz** [comment]
Thanks @lacroixdavid1 you're right.  I had `"html.format.wrapAttributes": "force"` not `"html.format.wrapAttributes": "force-aligned"`

**Comment by skotturi** [comment]
Neither 
`"html.format.wrapAttributes": "force"` 
nor
` "html.format.wrapAttributes": "force-aligned"` 
are working for me. Was working a week or so ago... 

This break for anyone else?

Version 1.15.1

**Comment by jitendravyas** [comment]
I added `"html.format.wrapAttributes": "force-aligned"` but nothing is happening

**Comment by christianmalek** [comment]
Maybe someone uses Vetur or other plugins and it's not working. It's possible that they use their own settings. For example Vetur uses the property `vetur.format.html.wrap_attributes": "force-aligned"`.

**Comment by JesseNewman19** [comment]
I really want a setting that allows me to align the attributes if they are on a new line, but not force them.

My ideal setting would be something like so:

"html.format.wrapLineLength": 50,
"html.format.wrapAttributes": "align"

That way it drops attributes to a new line if they get too long, but also aligns them properly.

As far as I can tell there is no way to do this with the current VSCode options.
