### ISSUE TITLE
目录显示错误，刷新几次之后显示正常

### ISSUE THREAD

**Issue by bibinbin** [Microsoft/vscode#22041]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|aessoft-class-autocomplete|AESSoft|0.1.0|
|xml|DotJoshJohnson|1.7.0|
|beautify|HookyQR|0.7.3|
|crane|HvyIndustries|0.2.2|
|format-indent|Kasik96|1.3.0|
|vscode-todo|MattiasPernhult|0.8.0|
|emoji|Perkovec|0.0.3|
|vscode-docker|PeterJausovec|0.0.11|
|code-gnu-global|austin|0.2.1|
|theme-material|bcmarinacci|1.3.0|
|typings-installer|benjaminromano|0.2.0|
|GBKtoUTF8|bukas|0.0.2|
|vscode-eslint|dbaeumer|1.2.2|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.5.8|
|phpunit|emallin|1.0.0|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.1|
|vscode-phpfmt|guodf|0.0.4|
|path-autocomplete|ionutvmi|1.4.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|Go|lukehoban|0.6.53|
|vscode-todo-parser|minhthai|1.8.6|
|prettify-json|mohsen1|0.0.3|
|cpptools|ms-vscode|0.10.0|
|debugger-for-chrome|msjsdiag|2.5.2|
|vscode-icons|robertohuertasm|7.2.0|
|Spell|seanmcbreen|0.9.1|
|Align|steve8708|0.2.0|
|rewrap|stkb|1.1.0|

---

Steps to Reproduce:

1.
2.

**Comment by bucaixiaot** [comment]
我都没有完整的安装起来过，你能把你的完整的安装命令给我看看吗

**Comment by bibinbin** [comment]
你现在安装最新的，不再像1.0 那样不好用了。配置什么的都好简单。

**Comment by bucaixiaot** [comment]
我就是最新的
第一步git clone xxx
第二部sudo  .scripts/npm.sh install
第三部sudo npm install gulp-watch
第四部npm run watch
然后报错

**Comment by bucaixiaot** [comment]
我都快放弃了

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/22045
