### ISSUE TITLE
Folder created by npm/webpack does not show up

### ISSUE THREAD

**Issue by ozluy** [Microsoft/vscode#22046]
I created __dist__ folder with npm using webpack it was visible before but currently folder is invisible although its there when I check in Finder

- VSCode Version:
1.10.1
- OS Version:
macOS Sierra 10.12.3

Steps to Reproduce:
1. create folder using webpack with npm cli

**Comment by bpasero** [comment]
@ozluy please provide exact steps for me how to reproduce

**Comment by ozluy** [comment]
@bpasero  I guess I wrote good description for how I created it on following line...
`I created dist folder with npm using webpack it was visible before but currently folder is invisible although its there when I check in Finder`

**Comment by bpasero** [comment]
@ozluy does it show when you restart Code or refresh the explorer?

**Comment by ozluy** [comment]
Unfortunately no @bpasero.

**Comment by ozluy** [comment]
I found the problem, I added following setting to my user settings
```
 "files.exclude": {
       ...
       "**/dist": true
    }
```
if I remove the ` "**/dist": true` line the folder shows up again. Thank you @bpasero
