### ISSUE TITLE
Multi-cursor pastes in reverse order

### ISSUE THREAD

**Issue by paustint** [Microsoft/vscode#2205]
When using the multi-cursor mode, when pasting from the clipboard the results are sometimes in reverse order.  The order of the data should be retained and not reversed.

Steps to reproduce (windows default key bindings)
1. alt+click on two or more places and hold shift (or ctrl+shift) and use the arrow keys to select some text.
2. ctrl+c to copy text
3. alt+click on the same number of lines as are copied on the clipboard where the pasted data should be placed
3. past data, notice that the results are in reverse order

```javascript
var dataload;
var apiLogs;
var tenant;
```
Pasting the results in the data in the wrong order as follows:
```javascript
var dataload = api;
var apiLogs = tenant;
var tenant = apiLogs;
var api = dataload;
```

**Comment by paustint** [comment]
I realized after posting this that the paste order is driven by the order that the new cursors are created.  This behavior differs from the standards of other applications and is an annoyance.  I would like to confirm if this behavior is a bug or if it is working as designed.

**Comment by paustint** [comment]
With more prototyping I have found when this really becomes an issue:

If there is a list of items and the cursor is on the bottom item and ctrl + alt + up is pressed to increase the cursors, then if text is copy and pasted it is pasted in reverse order.

**Comment by RobBiddle** [comment]
I'm having this problem still with the latest VSCode 1.9.0

Copying from VSCode to a PowerShell console on Windows 10 [Version 10.0.14393] inverts the order of multi-line code.  

If I paste into SublimeText first and copy the code again then the past order is corrected. However, if I use Notepad as the intermediary the problem persists.

**Comment by isidorn** [comment]
@RobBiddle please create a new issue as this one is outdated and close. From that issue link back to this one and try to give exact reproducable steps. Thanks!
