### ISSUE TITLE
Opening a file on a specific line number is remembered in the Recent Files

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#22052]
The file appears twice in the list:

![image](https://cloud.githubusercontent.com/assets/22350/23604166/3f9f6b36-0258-11e7-9e74-d71d4f601791.png)

**Comment by bpasero** [comment]
@joaomoreno I cannot reproduce, did you start like this:

`./code-cli.sh -g ~/Desktop/test-js/package.json:3`

Or somehow differently?

**Comment by joaomoreno** [comment]
No idea, actually. 😮  I just saw it in the menu today.

Also tried the url handling (`open vscode-insiders://file/Users/joao/Desktop/endgame.rtf:80`), but still don't repro there.

**Comment by bpasero** [comment]
Ok let me know when you found out steps.
