### ISSUE TITLE
Improve Insiders release notes

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#22051]
- Publish `vnext` version of release notes to the website
- Have VSCode open that version in product

**Comment by gregvanl** [comment]
@joaomoreno What if we included the release notes Markdown in the product instead of pulling down from the website? As devs were working on the notes, they would be updated with each nightly build. We could then take a snapshot of the release notes to put on the website at the final release for those customers still reading on the website. After we branch for the release, we would replace the content of the release notes with a clean placeholder for the next release.

**Comment by joaomoreno** [comment]
Why have an extra way of handling Release Notes? Ideally there's as few mechanisms to maintain as possible. We already have two: dynamic loading & website redirection... I don't want to maintain an extra one.

**Comment by gregvanl** [comment]
I think we can go down to one mechanism for in-product release notes. An added benefit is that by including the release notes markdown and images in the product install, users can view the release notes offline. We no longer need the other two mechanisms, those code paths can be removed. The final snapshot on the website is only for completeness and for users who prefer to read the notes without the product.

**Comment by joaomoreno** [comment]
Yeah but we lose the ability to fix the release notes after the product has been shipped.

**Comment by gregvanl** [comment]
Yep, that just occurred to me. I've published two workarounds in the release notes since the 1.11 release. That said, we usually have a recovery build (or two) when we could update the release notes.

**Comment by joaomoreno** [comment]
Recovery builds are meant for severe bugfixes only. If there won't be any, we won't release just to get release notes in.

**Comment by gregvanl** [comment]
Not sure I understand your question. If we think there are too many issues with bundling the release notes and having them available offline isn't a big benefit, then no.
We can go back to the earlier proposal to change the vscode-docs vnext CI build to commit to vscode-website master. It will still be a manual step to review the release notes and publish live.

**Comment by joaomoreno** [comment]
I meant it as: we should rely on the fact that we're gonna have a recovery build any way, in order to update the release notes after releasing.

I'd always go with any solution that places the release notes from `vnext` into the web.

**Comment by gregvanl** [comment]
Closing this issue since the changes to support easier flow of release notes content to the Insiders build will be done in the vscode-docs website generation code. Tracking with https://github.com/Microsoft/vscode-website/issues/611.
