### ISSUE TITLE
Coloring issue with Peacock theme?

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#22058]
Pls see the following twitter thread: https://twitter.com/AndrewNCassidy/status/837915671761543168

The original Peacock theme from color sublime has no red: http://colorsublime.com/?q=peacock.

Interestingly, the Peacock theme on the market place shows red tokens: https://marketplace.visualstudio.com/search?term=peacock&target=VSCode&sortBy=Relevance

**Comment by alexandrudima** [comment]
Duplicate of #22054
