### ISSUE TITLE
Add alias support to commands

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#22057]
- VSCode Version: 1.10.x
- OS Version: all

Commands do not provide an alias property hence we can't show an original English version of a command.

I broke tasks for 1.10 since the workbench actions got moved to commands for better keyboard shortcut support.

**Comment by isidorn** [comment]
@michelkaporin please verify

**Comment by michelkaporin** [comment]
We got rid of the alias as part of #17549 in PR #23105. Hence, putting verified.
