### ISSUE TITLE
Cannot open vscode!

### ISSUE THREAD

**Issue by rabbitooops** [microsoft/vscode#220582]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Latest
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Click vscode icon
2. Quit immediately
I can open it few days ago, maybe cause by the automatically update, i guess it doesn't support macOS 10.15.7

**Comment by rabbitooops** [comment]
Could vscode allow us to download old version and avoid auto update? it's not good to crash in old OS.

**Comment by fa2002** [comment]
https://github.com/microsoft/vscode/issues/219893

**Comment by fa2002** [comment]
It's been 4 days and the problem has not been solved yet.
https://github.com/microsoft/vscode/issues/219893
