### ISSUE TITLE
"Open change" button on extension description page

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#22059]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.5|
|gitlens|eamodio|2.10.1|
|code-runner|formulahendry|0.6.13|
|beautify|HookyQR|0.8.9|
|vscode-hexdump|slevesque|1.2.0|;

---

Steps to Reproduce:

1. open Extensions tab
2. click on any extension

Expected: workable "Open change" button in top right corner, or invisible it

Actual: not workable "Open change" button in top right corner

**Comment by stef-levesque** [comment]
I can't find a way to know if the active editor is an Extension tab, or Release Notes or anything.

I can check if there is an activeTextDocument, but I still want the `Show Hexdump` button to show for picture preview, which is not a regular TextDocument

**Comment by stef-levesque** [comment]
Any plan to expose IEditor or getEditorType() to the Extensions ?

**Comment by sandy081** [comment]
@joaomoreno This is coming from Git extension, I do not think it is intendend?

**Comment by SailorMax** [comment]
Same problem with "Git log" created document.

**Comment by stef-levesque** [comment]
fyi, vscode-hexdump is fixed with version 1.2.1
Added `resourceScheme == file` to the `when` parameter
