### ISSUE TITLE
tab autocomplete is wrong

### ISSUE THREAD

**Issue by iscraft** [Microsoft/vscode#22055]
- VSCode Version:1.10.1
- OS Version:windows7

Steps to Reproduce:

1.
![20170306_183030](https://cloud.githubusercontent.com/assets/5448825/23606365/5a8c8454-029b-11e7-83f7-5c955c168b69.png)

press tab key

2.
![20170306_183041](https://cloud.githubusercontent.com/assets/5448825/23606390/76686bb6-029b-11e7-904b-5a0bee467012.png)

**Comment by roblourens** [comment]
No longer an issue, with new emmet work.
