### ISSUE TITLE
Prevent IntelliSense suggesting previous filled value

### ISSUE THREAD

**Issue by mufatkix** [Microsoft/vscode#22063]
- VSCode Version: 1.10.1
- OS Version: macOS 10.11.6

Is there any way to prevent IntelliSense suggesting previous filled values? For example, in the below img, "acs" is the value previously filled in, is there any mechanism to prevent/disable IntelliSense suggesting that value?
![screen shot 2017-03-06 at 12 41 10](https://cloud.githubusercontent.com/assets/26221591/23608571/47649960-026a-11e7-8eec-546404f0e2ec.png)

**Comment by jrieken** [comment]
Yes, the setting is called `"editor.wordBasedSuggestions"` and it can be turned off via `"editor.wordBasedSuggestions": false`

**Comment by mufatkix** [comment]
@jrieken 
Thanks for the reply! I've tested it while editing a JSON file and those values are still shown although `"editor.wordBasedSuggestions"` is turned off. 
Below you see that when I'm editing name field of my JSON, previously filled-in values are still suggested.
![screen shot 2017-03-07 at 14 42 52](https://cloud.githubusercontent.com/assets/26221591/23658890/7f2efb6c-0344-11e7-95a4-c40bb14b9ae5.png)

Here is my settings.json:
```json
{
    "editor.tabSize": 2,
    "editor.quickSuggestions": true,
    "editor.acceptSuggestionOnEnter": true,
    "editor.quickSuggestionsDelay": 10,
    "editor.wordBasedSuggestions": false,
    "editor.parameterHints": true,
    "editor.wordWrap": "on"
  }
```

**Comment by jrieken** [comment]
@aeschli will know, but I believe our JSON-server is smart and proposes the last n-values you have assigned to `name`

**Comment by aeschli** [comment]
We look at other usages of that property and suggest these values. There's currently no way to turn that off.

The best is if you provide a JSON schema. In the schema you can provide the set of valid values.
Check out https://code.visualstudio.com/docs/languages/json#_json-schemas-settings
