### ISSUE TITLE
"Format Selection" doesn't work with Multi Select

### ISSUE THREAD

**Issue by bennyschaefer** [Microsoft/vscode#22062]
* **Operating System**: Windows 10 Home (v1607; 14393.693)
* **VS Code Version**: 1.10.1

## Action performed
* Open file (for instance HTML file)
* Select part of the code
* While holding ALT (Option key on Mac), select more code somewhere else in the file (=VSCode's multi-select feature)
* "Format Selection"

## Expected results
* both sections should be formatted

## Actual results
* only the section selected first is formatted

**Comment by jrieken** [comment]
Good request, tricky to get right tho...

**Comment by jinkin1995** [comment]
same question too...
