### ISSUE TITLE
Allow extensions to participate in tasks using commands

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#22067]
Currently the task framework can only trigger external commands (programs or shell scripts). Since Ctrl+Shift+B is taken by the task framework we should allow extension to participate in 'build' and 'test' (and any other composite task) by executing a command in the extension itself.

**Comment by dlech** [comment]
Duplicate of #11396?

**Comment by dbaeumer** [comment]
Correct :-)
