### ISSUE TITLE
Remove spam.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/vscode#220787]
<strike>

1.	https://github.com/microsoft/vscode/issues/220786#issue-2394201419
2.	https://github.com/microsoft/vscode/issues/220785#issue-2394201409
3.	https://github.com/microsoft/vscode/issues/220784#issue-2394201399
4.	https://github.com/microsoft/vscode/issues/220783#issue-2394200444
5.	https://github.com/microsoft/vscode/issues/220780#issue-2394196151
6.	https://github.com/microsoft/vscode/issues/220777#issue-2394195167
7.	https://github.com/microsoft/vscode/issues/220776#issue-2394195154
8.	https://github.com/microsoft/vscode/issues/220775#issue-2394195146
9.	https://github.com/microsoft/vscode/issues/220790#issue-2394202882
10.	https://github.com/microsoft/vscode/issues/220788#issue-2394202872
11.	https://github.com/microsoft/vscode/issues/220793#issue-2394203437
12.	https://github.com/microsoft/vscode/issues/220792#issue-2394203429
13.	https://github.com/microsoft/vscode/issues/220791#issue-2394203427

Compiled so that none are missed.

</strike>

Too many. See https://github.com/microsoft/vscode/issues/220787#issuecomment-2212560965. I'll leave this open so that I know when the problem has been remediated, since there's no way that any triaging is occurring whilst this attack is occurring.

**Comment by RokeJulianLockhart** [comment]
https://github.com/microsoft/vscode/issues?q=sort%3Aupdated-desc+is%3Aissue+label%3Ainvalid+ - wow. That's a lot.

**Comment by billythekid** [comment]
Hi @RokeJulianLockhart :wave:

I'm on the Platform Health team and we're responsible for catching spammers on GitHub. I know this has been an ongoing campaign annoying maintainers of popular repositories, and I appreciate how frustrating this can be.

I just wanted to drop in to reassure you that we're actively fighting this, it's firmly on our radar and I think I've removed everything from your list above. I've given the invalid issues a quick scan and it looks like I've caught them all or they've scrolled off to obscurity now.

Please feel free to report any individual accounts that slip through our detection systems following the guidelines in our [Reporting abuse or spam](https://docs.github.com/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam) doc.

Cheers,
Billy 🤠
