### ISSUE TITLE
Surface new Exception DAP in UI

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#22078]
In the last milestone we've added new debug adapter protocol to retrieve [information about a thrown exception](https://github.com/Microsoft/vscode-debugadapter-node/issues/97) and we've introduced a peek UI [to show this information to the user](https://github.com/Microsoft/vscode/issues/16860).

Now we have to bring both things together.

**Comment by weinand** [comment]
I've implemented a first cut of the new exception info request in node-debug.
Now VS Code needs to make use of this.

If the capability object returned from the InitializeRequest has a value true for the `supportsExceptionInfoRequest`, the `exceptionInfoRequest` is supported by the DA. In this case VS Code should populate the exception peek UI from the values returned from the `exceptionInfoRequest` instead of using the StoppedEvent.

The `exceptionInfoRequest` expects the `threadId` as the only input argument.
It returns the following structure:

![2017-03-16_16-11-34](https://cloud.githubusercontent.com/assets/1898161/24005044/3625ca7e-0a68-11e7-87fa-2845735c70f4.png)

The additional information (for now) is the `breakMode` and the `details.stacktrace`. Both should be surfaced in the peek UI.

**Comment by isidorn** [comment]
This has been done by @michelkaporin in https://github.com/Microsoft/vscode/pull/22948

**Comment by isidorn** [comment]
Tried it out and it looks good to me.
@weinand why does the protocol surround the stack trace with quotes - I think it would look nicer if no quotes were shown
@roblourens it would be cool if node2 debug adapter also picks up the support for exceptions so we do not have inconsistencies between these two expeirences
@michelkaporin can you please create a short test plan item for this feature

![screen shot 2017-03-22 at 12 47 13](https://cloud.githubusercontent.com/assets/1926584/24196338/b3185062-0efd-11e7-89df-99a90ac43e2f.png)

**Comment by weinand** [comment]
The stack trace is surrounded by quotes because it is a "string" value (and we always do the value formatting in the backend so that VS Code does not have to second guess). So I will remove the quotes in this case.

@michelkaporin I suggest to introduce some space between the exception description ("Unhandled exception has occurred....") and the stack trace (e.g. 1/2 a line). Without this the UI looks a bit crammed.

**Comment by weinand** [comment]
I'm removing the quotes from the stacktrace now: 
https://github.com/Microsoft/vscode-node-debug/commit/81c69edfccaae8641c0b7db48b1c733f1ec73b5b

**Comment by roblourens** [comment]
Btw I just took a PR to apply sourcemaps to stacktraces. I think it will look very nice with this widget.

https://github.com/Microsoft/vscode-chrome-debug-core/pull/190

**Comment by weinand** [comment]
But this requires the ExceptionInfo request for node2...

**Comment by roblourens** [comment]
I have an issue to implement it for node2

**Comment by michelkaporin** [comment]
@weinand You've mentioned:
> The additional information (for now) is the breakMode and the details.stacktrace. Both should be surfaced in the peek UI.

Sometimes details.stacktrace is not available from the DA response. What would be your suggestion to show instead of it in the exception widget then?
Currently DA response if surfaced the following way (structure with current showcase below):
> `breakMode`-type exception has occurred. `description`
> `details.stackTrace`

![image](https://cloud.githubusercontent.com/assets/2239563/24454682/0e8d241a-148d-11e7-95cc-5d1dd9b69a51.png)

My proposal would be to fall back to the UI case when DA does not support exceptionInfo request, but with `breakMode`-type message included (see the image below).

![image](https://cloud.githubusercontent.com/assets/2239563/24454771/6534ea14-148d-11e7-8a96-d7f4ed26a759.png)

Would be good to hear @isidorn opinion also. 

This decision is needed as part of fixing #23388.

**Comment by michelkaporin** [comment]
FYI This is how it looks like when DA does not support exceptionInfo request:
![image](https://cloud.githubusercontent.com/assets/2239563/24455047/88c68586-148e-11e7-8360-6f0a18fc7205.png)

**Comment by weinand** [comment]
If details (and hence the stacktrace) is missing we should still continue to use the new layout and not fallback to the old layout.

The rational behind this is as follows:
In the future there will be more details coming through the ExceptionInfo request and we will have to integrate them into the layout as well. Always falling back to the old layout doesn't make a lot of sense because there will be always some details provided that are not covered by the old layout at all.

**Comment by isidorn** [comment]
I agree with @weinand

**Comment by michelkaporin** [comment]
Makes perfect sense. So this is the way we go for then, omitting the stack trace completely if it is not returned by DA:
![image](https://cloud.githubusercontent.com/assets/2239563/24456718/3726b42a-1494-11e7-97c7-9b2fb0b55dab.png)

**Comment by weinand** [comment]
the latest DA will always return an exceptionID (as spec'ed). So this will result in:
```
Unhandled exception has occurred. string: heello
```

**Comment by michelkaporin** [comment]
Currently we don't surface exceptionID, so I would be glad to hear how do we do it in a better way, because node DA description already contains exceptionID in its current implementation. 

Printing it twice would make the information redundant.

**Comment by weinand** [comment]
In the original [protocol change request](https://github.com/Microsoft/vscode-debugadapter-node/issues/97#issue-202998764) 'Exception ID' got this example usage:

> Exception ID (e.g. "CLR/System.ArgumentException")

In VS it is shown prominently as the title:
![2017-02-02_17-48-49](https://cloud.githubusercontent.com/assets/1898161/22558996/fa819fca-e96f-11e6-9c76-0f570188b7bf.png)

So my proposal would be:

```
${breakMode} exception: ${exceptionID}
${description}

${details.stackTrace}
```

**Comment by michelkaporin** [comment]
@weinand I agree with your proposal, and currently it looks the following way with the latest version of node DA. 
- Node DA with `exceptionInfo` request support:
![image](https://cloud.githubusercontent.com/assets/2239563/24462916/867fbee8-14a5-11e7-85a7-394c20d40333.png)
![image](https://cloud.githubusercontent.com/assets/2239563/24462921/8c0fb4a8-14a5-11e7-9325-da14b5524763.png)

- Node DA **without** `exceptionInfo` request support:
![image](https://cloud.githubusercontent.com/assets/2239563/24462966/a915559e-14a5-11e7-8a0e-9e0bc5e2bbb2.png)

It would be great to hear also @isidorn's feedback on that, and then to have your change in node DA so that it does not return redundant information as in the first image, for instance.

**Comment by weinand** [comment]
Since the description is optional, I'm planning to omit the description if it appears in the stack trace.

@michelkaporin Please make sure that there are not two empty lines in that case.

**Comment by weinand** [comment]
@roblourens VS Code now uses the following layout for the exception peek UI:

```
${breakMode} exception: ${exceptionID}
${description}

${details.stackTrace}
```

To avoid duplication of the description ("Error: heello" from above), I'm now omitting the description from the response if it already appears at the beginning of the stack trace (I prefer this approach over removing the first line from the stacktrace because it leaves the stacktrace as it is).

**Comment by roblourens** [comment]
I see 'undefined' in the exception widget now:

![image](https://cloud.githubusercontent.com/assets/323878/24487858/b0fe58ba-14c7-11e7-9399-3c8ff3a2225e.png)

**Comment by michelkaporin** [comment]
> @roblourens VS Code now uses the following layout for the exception peek UI:
I have not pushed my changes yet to make this layout, waiting for our UI master @isidorn's feedback and then will update the widget accordingly.

Hence, @roblourens you started seeing 'undefined' because of @weinand change above, which is not in sync with current widget UI.

**Comment by roblourens** [comment]
Oh ok. I'll make the same change in node2.
