### ISSUE TITLE
VS Code window does not open on Primary screen if it's set to an external display

### ISSUE THREAD

**Issue by balcsida** [Microsoft/vscode#2207]
I recently fresh installed VS Code. I use my laptop as a desktop PC with Windows 10 and I have a connected external display.
The display projection setting is set to "Second screen only".
At the first launch the VS Code's icon has been appeared on the taskbar but nothing happened.
Hovering over the icon shows that the window is actually opened and VS Code is running.
However, it is positioned to the laptop screen (which is not used/turned off).
Workaround: set Project (Win+P) to Extend, then back to Second screen only.
![image](https://cloud.githubusercontent.com/assets/1768446/12537596/14d23e22-c2c3-11e5-9880-ba40a78434e0.png)

**Comment by bpasero** [comment]
I just tried this with my Win10 machine having a second screen connected and changing it to "Second screen only". Starting VS Code shows up on the second screen just fine. Is there any chance that maybe you had VS Code running already and then connected the second screen or changed the projection?

**Comment by balcsida** [comment]
Yes, it worked for me too (I did a complete Windows reinstall)
