### ISSUE TITLE
Clear "replace" field when opening the search/replace dialog via "Find in files"

### ISSUE THREAD

**Issue by CZDanol** [Microsoft/vscode#22071]
When I open "Find in files" dialog (via ctrl+f), the vs code should automatically clear the replace bar, as replace previews are opened when going through results - that is messy.

**Comment by alexandrudima** [comment]
Replace previews => search viewlet (not find widget)

**Comment by sandy081** [comment]
We now hide the replace input box when opening Search viewlet when it is not visible.
