### ISSUE TITLE
Allow reporting of extensions

### ISSUE THREAD

**Issue by donsingh** [Microsoft/vscode#22073]
We need to clean up our marketplace quick! Some extensions are starting to deprecate and worse, get abandoned. Due to most people downloading top-rated or top-downloaded extensions, this could mean hours of frustration only to find out this extension/s are broken.

**Please allow the ability to report/ flag extensions for either breakage or plagiarism via the marketplace and/or extension page.**

Take for example:

PHP Code format;
https://marketplace.visualstudio.com/items?itemName=Kasik96.format-indent

One of the highlight downloaded formatting tools and yet, check the reviews. (Repo and issues page are MIA btw). I think there needs to be better moderation on our marketplace if we want it to grow properly.

Would love to hear people's input on it.

**Comment by joaomoreno** [comment]
cc @modigrv @hamenon

**Comment by mjbvz** [comment]
There is now a report link under `More info` in the marketplace:

![Screen Shot 2019-05-01 at 4 07 07 PM](https://user-images.githubusercontent.com/12821956/57048995-362fb300-6c2b-11e9-9e9e-1062d53b8d67.png)
