### ISSUE TITLE
Add debug menu to improve discoverability

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#22077]
To make the debug actions more discoverable, we should add a debug menu.

**Comment by isidorn** [comment]
The initial version of this has been done.
Leaving this item open as we still need to look into enabling / disabling actions in the menu and try to introduce a `menuService`

![screen shot 2017-03-06 at 15 16 20](https://cloud.githubusercontent.com/assets/1926584/23613484/e77616ee-027f-11e7-8fa0-f54a03b264f2.png)

**Comment by isidorn** [comment]
@jrieken we should sync on the menu service some time next week and how we could use it for the top menu actions if possible.

**Comment by isidorn** [comment]
Closing this item as we have introduced the debug menu, as for making the application menu contributable from the renderer we have created this PR to track it https://github.com/Microsoft/vscode/pull/23030
