### ISSUE TITLE
tryListenOnPipe can be slow

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#22086]
We are receiving traces that `tryListenOnPipe` is slow and takes up to 1sec

<img width="927" alt="screen shot 2017-03-06 at 17 49 04" src="https://cloud.githubusercontent.com/assets/1794099/23619828/329a9d38-0295-11e7-9b65-0b34a16bb7c1.png">

**Comment by jrieken** [comment]
The main thread and extension host communication via a named pipe, like other parts in our system. To generate the (random) name for that pipe I have used [`crypto#randomBytes`](https://nodejs.org/dist/latest-v6.x/docs/api/crypto.html#crypto_crypto_randombytes_size_callback). Contradicting to the docs it turns out that this call, on windows, takes roughly 1 second to finish. 

Adding *candidate*-label for consideration, fix is trivial.

**Comment by alexandrudima** [comment]
:+1:
