### ISSUE TITLE
Continue from #21999

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#22082]
#21999 
----------------
First line = 2 tabs ((( first tab make 1 space only, second tab make 2 space )))
Second line = 1 tab and left arrow and 1 tab again ((( first tab make 1 space, second tab make 1 space )))
Third line = it just 1 tab ((( first tab make 2 spaces. which the right for my settings )))

![ks](https://cloud.githubusercontent.com/assets/17777237/23616690/46351924-0293-11e7-912e-6c75b157ca34.gif)

**Comment by ramya-rao-a** [comment]
This seems to be html specific, but cc @rebornix and @alexandrudima for insights on the tab spacing

**Comment by aeschli** [comment]
Pressing tab always moves to the next tab stop. If you are one space away, it will be just adding one space. If it's 2 away, it adds two. 
use the settings
```json
  "editor.tabSize": 4,
  "editor.insertSpaces": true
```
to control where the tab stops are and wheter you like tab characters or spaces.

(nothing HTML specific here)

**Comment by pixieaka** [comment]
I get this problem in .js or .vue When i write html inside any type different than regular html
![capture](https://cloud.githubusercontent.com/assets/17777237/23650930/7f4e3274-032c-11e7-8ab1-a2d8c466f103.JPG)

**Comment by aeschli** [comment]
It's just how tabs work. Nothing language specific.

**Comment by pixieaka** [comment]
@aeschli 

![ks](https://cloud.githubusercontent.com/assets/17777237/23652295/03055878-0331-11e7-8f84-cdb0a8265ad3.gif)

My settings is
`{
    "workbench.welcome.enabled": false,
    "window.zoomLevel": -1,
    "editor.fontFamily": "source code pro",
    "editor.quickSuggestions": false,
    "terminal.integrated.shell.windows": "cmd.exe",
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/vendor": true
    },

    "editor.tabSize": 2,
    "editor.insertSpaces": true,
    "editor.detectIndentation": false
  }`

**Comment by alexandrudima** [comment]
Given your settings:
```
"editor.tabSize": 2,
"editor.insertSpaces": true,
```
Pressing Tab will insert:
* one space when cursor sits at an odd column
* two spaces when cursor sits at an even column

Pressing Tab will insert the amount of spaces required to bring you to a multiple of `tabSize`. This is how Tab works by design. (This perhaps becomes more obvious when configuring `tabSize` to a larger number).

Here we are e.g. with:
```
"editor.tabSize": 10,
"editor.insertSpaces": true
```
![22082](https://cloud.githubusercontent.com/assets/5047891/23661297/987dda22-034c-11e7-8661-7efd22ebd3a1.gif)
