### ISSUE TITLE
Consider to support a server mode for debug adapters

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#22080]
Today VS Code starts a new debug adapter process for every debug session.

Only in "debug adapter development mode" we support to have a debug adapter running as a server and to have VS Code just connect to it for a debug session.

We should consider to make the "server mode" an official run option for debug adapters. 

/cc @isidorn @daviwil

**Comment by daviwil** [comment]
Oh, I didn't realize `debugServer` was only enabled in development mode.  I'd definitely like to have this since the default path of the PowerShell extension will be for the debugging session to be shared with the current editing session.  If the debug configuration can specify the TCP port to the long-running debug session (and have it modified by my `startSessionCommand` if needed), then I think this will be great!

**Comment by gorkem** [comment]
There are some limitations on _server mode_ in its current form. 1) It has a fixed port number which will not allow two vscode instances to run the same debugger at the same time. 2) It does not allow an extension to run a prepare code for instance to find an available port or init debugger.

**Comment by weinand** [comment]
@daviwil no, `debugServer` works in production too. But it was only **meant** to be used in development mode.
(And if the statically assigned port is already in use, debugging will most likely fail).

**Comment by daviwil** [comment]
`debugServer` defines a local TCP port of an already-running server, correct?  When I intercept my extension's debug requests with a `startSessionCommand` handler, can I add `debugServer` to the configuration and send it to `vscode.startDebug`?  That's all I would need.

**Comment by isidorn** [comment]
@daviwil I think that would work. Try it out :)

**Comment by daviwil** [comment]
Had been planning to, just didn't get around to it yet :)  I'm finally at the point now with my extension where using `debugServer` makes sense, so I'll give it a shot soon and let you know.

**Comment by weinand** [comment]
I don't think that `debugStart` is called in server mode.  `debugStart` is supposed to return the command to launch the debug adapter, and this makes no sense in  server mode.

**Comment by weinand** [comment]
@gorkem the "fixed port" is configurable, so there is no problem running multiple instances of the same debugger.

**Comment by gorkem** [comment]
@weinand Is this a configuration per instance or per installation? Is it possible for a bit of code to be executed to calculate the next available port?

**Comment by weinand** [comment]
@gorkem You are in control of the configuration. So it can be anything you like.

I've just prototyped this for your case.

In your extension you can register a hook for the 'startSession' event, which is triggered when a new debug session is launched. In this hook you determine the port on which the java debug adapter listens (or you can even start the debug adapter there). Then you assign the port number to the `debugServer` attribute (if this is still undefined).

Here is the complete extension code that goes into the `activate` hook:

```js
context.subscriptions.push(vscode.commands.registerCommand('extension.java.startSession', config => {
	if (!config.debugServer) {
		config.debugServer = 12345;	// determine debug port 
	}
	vscode.commands.executeCommand('vscode.startDebug', config);
});
```

In the package.json you need these contributions:

```js
"activationEvents": [
	// ...
	"onCommand:extension.java.startSession"
	// ...
],
"contributes": {
	"debuggers": [
		{
			"type": "java",
			// ...
			"startSessionCommand": "extension.node-debug.startSession"
			// ...
		}
	]
}
```

@daviwil  so your suggestion works as expected by @isidorn

**Comment by weinand** [comment]
I do not see a need for anything else at the moment.
