### ISSUE TITLE
Select more files to open from "Go to File" dialog

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#22085]
Hi!

- VSCode Version: 1.10.1
- OS Version: macOS Sierra

Steps to Reproduce:

1. press Cmd+P to open Go to File dialog
2. find some file pattern (which e.g. in JS project matches a File and its FileSpec file)
3. ...and here, I'm not able to open more files at once.

E.g. by pressing Shift any Down to select more files to be opened...or select them by Ctrl (Cmd)+click and opening them by Return. I must open one file, invoke Go to File again, again write a pattern and select another file. It's too lengthy :(

Thanks a lot!

**Comment by alefragnani** [comment]
Hi @obrejla ,

You could press the `Right` key, to open the file _in background_. It will open the file and keep the list open.

Hope this helps

**Comment by obrejla** [comment]
Huh, seems to work quite nicely! :) Different behavior from what I'm used to but I'll give it a try ;) Thanks for quick response!
