### ISSUE TITLE
Improve on inconsistent language: Side Bar vs Activity Bar

### ISSUE THREAD

**Issue by adamvoss** [Microsoft/vscode#22088]
- VSCode Version: Version 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5)
- OS Version: Linux Mint 18.1 64-bit

Steps to Reproduce:

1. Open the View Menu
2. Observe the following options:
   * Move Side Bar [Right/Left]
   * Toggle Side Bar
   * ...
   * Hide Activity Bar

Here we have both "Side Bar" and "Activity Bar" referring to the Vertical Menu and drawer.  It seems "Side Bar" is supposed to refer to the expanded part and "Activity Bar"; however, this is not very discoverable and the Activity Bar can reasonably expected to be the referenced Side Bar.  The "Activity Bar" is *a sidebar* and it moves when I choose "Move Side Bar" and the drawer I perceive as attached to it expands/collapses (shows/hides) when I choose "Toggle Side Bar."  However, when I want to hide it I need an option related to the "Activity Bar" rather than the "Side Bar." (In my case I had to come to GitHub and search issues to find that the behavior I was looking for was that option).

edit: [there is evidence I am not the only person to encounter this confusion](https://github.com/Microsoft/vscode/issues/15310#issuecomment-259962222)
___

## Suggestions

Assuming the current names are to be kept, I recommend the following changes:

* Standardize on Toggle or [Show/Hide].
So either "Toggle Activity Bar" or "[Show/Hide] Side Bar".  This helps to put widgets on equal footing and the consistency helps to lessen the possible association that "Toggling" the side bar changes the state or the Activity Bar rather than showing/hiding an independent widget. (Note: This would apply to more than this entry)

* Make "Move Side Bar [Right/Left]", "Move Activity Bar [Left/Right]"
This helps to establish the name "Activity Bar" and explains why the option moves the Activity Bar when the option is selected and not just the Side Bar.

**Comment by isidorn** [comment]
I agree with all your points. However I think chaning anything noew would only cause even more confusion.
Thus closing as will not fix
