### ISSUE TITLE
Hightlight of closing tag doesn't work in High Contrast theme

### ISSUE THREAD

**Issue by albu77** [Microsoft/vscode#22084]
- VSCode Version:1.10.1
- OS Version: Windows7 64

Steps to Reproduce:

1.Disable any extension
2.Open a html file
3.DOuble click on a div tag
![image](https://cloud.githubusercontent.com/assets/624802/23618800/db01e57a-0291-11e7-8db2-7ba83927f714.png)
4.It show all the matchinf tags but not the closing one.....

**Comment by ramya-rao-a** [comment]
In your example, I can see the second occurrence of "div" (the one on the third line) not being highlighted. Rest are all highlighted. 

So what are you referring to when you say that the closing tag is not being highlighted in this example?

**Comment by albu77** [comment]
I don't understand how I could do it anyway I took another image and you can see the closing </div> tag is not highlight. What I would expect is to be able to check the closing tag for any tag. Am I wrong?
![image](https://cloud.githubusercontent.com/assets/624802/23630583/f8d52ccc-02bb-11e7-9d86-b85a8d4e21ee.png)

**Comment by ramya-rao-a** [comment]
When you double click on a tag, all other tags with the same name get highlighter. This is not a HTML feature. This happens in any other file type as well. You double click a word, all occurrences of the word in the file are highlighted

If you just want to find closing tag, then just click once a tag, and the matching tag will get highlighted

**Comment by albu77** [comment]
I try diiuble click because the simple click doesn't work.

**Comment by albu77** [comment]
To me, since Emmet had been included, this matching had been disabled. Emmet is "on" but with no short keys (it seems to me , and don't understand why...) So Added my own shortkey and work with ctrl+shift+m
 {"key": "ctrl+shift+m",   "command": "editor.emmet.action.matchingPair", "when": "editorTextFocus"}

**Comment by aeschli** [comment]
To my knowledeg, double click doesn't do anything special, ist just expanding the selection to the current word.
@albu77 Can you paste your code here?

**Comment by ramya-rao-a** [comment]
@albu77 The matching done when you single click on a tag is independent of the Emmet matching pair command.

The former just highlights the matching tag, but doesnt move the cursor
The latter moves the cursor to the matching tag

So what is your scenario? You just want to see the matching tag, or go to the matching tag?

**Comment by albu77** [comment]
I know and understand , but for me it's the only thing working

**Comment by ramya-rao-a** [comment]
Can you run `code --disable-extensions` in your terminal and try again, just to ensure that no extension is interfering here?

**Comment by albu77** [comment]
**That doesn't change anything**
_But interesting on another point which  I understant  is another matter anyway_ _So feel free to not considering it_:
I work on two project located in two different folder.
On the first where I was trying to get closing tag matching I already disabled the extension so the command `code --disable-extensions` didn't do anything on the extensions panel and neither for the matching.
On the second project I didn't disabled any extension and so I discover extensions are somehow folder or project related: is that right?. Anyway when I run the commande `code --disable-extensions` it doesn't show anything in the extensions panel, I mean noway to know that the extensions are disabled  is that normal? and that even after restarting vscode (but that probably normal for the restarting, since I hope the command doesn't changed the extensions config).

**Comment by aeschli** [comment]
Extensions are not folder related. Make sure all instances of code are closed before starting on the second folder. Otherwise the second run will just tell the first instance of code to open a new window and command line options of the first run will apply.

**Comment by aeschli** [comment]
But please send your code example here. Maybe it's a bug in the code that detects the matching tags.

**Comment by albu77** [comment]
**Extensions are related to workspace**
VsCode with first project open

![image](https://cloud.githubusercontent.com/assets/624802/23709406/97142150-0419-11e7-9ae6-45cc03128e5c.png)
VsCOde with other project: we can see extension unactive
![image](https://cloud.githubusercontent.com/assets/624802/23709471/d83ab46e-0419-11e7-8145-45d93c8de5b2.png)
No other vscode process running

- Create e new folder
- Start Vscode
- run code --disable-extensions
- Open this Folder
- Create a simple html file
- Same problem

![image](https://cloud.githubusercontent.com/assets/624802/23709963/61f43bde-041b-11e7-9e08-f4dcdb2acc57.png)

Sa

**Comment by ramya-rao-a** [comment]
Its a theme issue!!

Looking at the latest screenshot, it looks like you are using the "High Contrast" theme.

I tried the same, and I can repro the issue now.

**Comment by albu77** [comment]
**Yes, you are right**, but strange because it was the first thing I tried and don't remember that it made any difference.  _Anyway  I will keep on using my workaround because I really need the high contrast._
Thanks for your assistance.
