### ISSUE TITLE
Detect identation is not working as expected

### ISSUE THREAD

**Issue by manishgupta31286** [microsoft/vscode#220977]
Type: <b>Bug</b>

Hi,

I have C# file and my workspace settings.json are

    "editor.insertSpaces": true,
    "editor.detectIndentation": true,

But these settings are not working, as after saving any file, it converts existing space identation to tabs. Also if I set detectIdentation to false, and insertSpaces: true, VS Code still inserts tabs. So both settings are not working as expected.

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (2.19GB free)|
|Process Argv|--crash-reporter-id c695d0a3-87c1-4271-88e2-2edda513f5da|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
csharp-convert-ts|con|0.1.31
csharpier-vscode|csh|1.7.3
dscodegpt|Dan|3.4.20
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|15.1.0
prettier-vscode|esb|10.4.0
vs-sharper|ese|0.2.0
copilot|Git|1.211.0
copilot-chat|Git|0.17.0
go|gol|0.41.4
terraform|has|2.31.0
vscode-guid|hea|1.9.0
rest-client|hum|0.25.1
cscurlyformatter|Iro|0.0.7
Angular2|joh|16.0.1
git-graph|mhu|1.30.0
azure-dev|ms-|0.8.3
vscode-azureappservice|ms-|0.25.2
vscode-azurecontainerapps|ms-|0.7.0
vscode-azurefunctions|ms-|1.15.1
vscode-azureresourcegroups|ms-|0.9.1
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.15.3
vscode-azurevirtualmachines|ms-|0.6.5
vscode-cosmosdb|ms-|0.22.0
vscode-docker|ms-|1.29.1
csdevkit|ms-|1.7.27
csharp|ms-|2.34.12
vscode-dotnet-runtime|ms-|2.0.8
vscodeintellicode-csharp|ms-|2.1.11
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.22.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.1
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.375.0
remote-wsl|ms-|0.88.2
azure-account|ms-|0.12.0
makefile-tools|ms-|0.9.10
vscode-node-azure-pack|ms-|1.2.0
java|red|1.32.0
vscode-yaml|red|1.15.0
angular-formatter|sdt|1.2.0
angular-template-formatter|str|0.1.5
tabnine-vscode|Tab|3.122.0
ansible-studio|Vir|1.1.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.23.7
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0
format-all-files|xyk|0.2.0
vscode-react|zha|0.0.5
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31082723

```

</details>

**Comment by andrii-riabchun** [comment]
Try to disable the `cscurlyformatter` extension. It resolved the issue for me.
