### ISSUE TITLE
[scss] when completing functions place cursor between brackets

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#22096]
- VSCode Version: Code - Insiders 1.11.0-insider (a3b1076f079c150d921a7b91d91c6783fa04450a, 2017-03-06T07:04:45.166Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.5.1|
|sort-lines|Tyriar|1.2.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.12.0|
|project-manager|alefragnani|0.13.3|
|nord-visual-studio-code|arcticicestudio|0.1.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.7|
|python|donjayamanne|0.5.9|
|tslint|eg2|0.8.1|
|copy-relative-path|enochc|0.1.1|
|Angular2|johnpapa|2.0.3|
|vscode-icon-theme|jtlowe|1.5.0|
|theme-karyfoundation-themes|karyfoundation|11.0.0|
|restructuredtext|lextudio|0.0.21|
|HTMLHint|mkaufman|0.3.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-csscomb|mrmlnc|4.0.1|
|vscode-stylefmt|mrmlnc|2.2.3|
|stylelint|shinnn|0.23.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|1.2.0|
|theme-tesla|smlombardi|6.0.0|
|vscode-todo-highlight|wayou|0.4.5|
|change-case|wmaurer|1.0.0|;

---

Probably affects CSS as well.

Steps to Reproduce:

1. Type a scss function, such as `transform: scaleX()`, allowing Intellisense to complete the `scaleX` part for you
2. the cursor/insertion point is placed *after* the parens instead of between them.  This means to type a value, you need to place the cursor inside the parens manually.  See gif:

![mar-06-2017 12-46-44](https://cloud.githubusercontent.com/assets/835148/23622014/fb04493e-026a-11e7-9431-450e8ae34404.gif)

**Comment by ramya-rao-a** [comment]
@aeschli 
I can repro even with all extensions disabled.
