### ISSUE TITLE
readFromDomElement sometimes slow

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#22090]
We receive profiles that show `_readFromDomElement` being very slow in some cases. This is the umbrella item which point to the profiles.

**Comment by jrieken** [comment]
@alexandrudima https://github.com/Microsoft/vscode/issues/22173 with 11seconds in that method...

**Comment by alexandrudima** [comment]
@jrieken Please understand that is the time it takes Chromium to do a layout and not the time taken by that method.

I can look into "cheating" (i.e. writing the font information to local storage and reuse it from there, and validate it after some time). But this huge time spent will appear in the next function that causes Chromium to do a layout.

**Comment by jrieken** [comment]
I understand it's not us, but we have to acknowledge reality and start to play tricks

**Comment by alexandrudima** [comment]
maybe I should start taking screenshots of the last painted editor on shutdown next

**Comment by alexandrudima** [comment]
Added a workaround where we:
* store the actual read font info to local storage
* on startup, we restore the actual read font info from local storage
* after 5 seconds from startup, we validate that the font info was correct (i.e. in case a font was installed on the OS between VS Code restarts)

Good luck to the next function call where the Chromium layout shows up
