### ISSUE TITLE
Click to preview image  bug

### ISSUE THREAD

**Issue by xiucaixiu** [microsoft/vscode#220986]
![image](https://github.com/microsoft/vscode/assets/153316562/6dc5993d-9d41-428e-af5b-6cc7d9dc9bd4)    
When writing in css, the path opened by ctrl+ left mouse in vscode is 
src\views\vitalSignsSuper2\views\oldComponents\jtbj\components\@\assets\images\screen\shengmingtizheng\index_18.png
![image](https://github.com/microsoft/vscode/assets/153316562/7338b938-0f21-4b23-bc92-ee2db5969928)

**Comment by aeschli** [comment]
The built-in CSS language extension does not know what `@` is. It's not part of the CSS spec. Maybe you are using a preprocessor?

**Comment by xiucaixiu** [comment]
Not just css, but also html vue img
![image](https://github.com/microsoft/vscode/assets/153316562/3749f2f6-c0ce-4c20-8272-728f48de484e)

**Comment by aeschli** [comment]
Ah, this is vue. Please file the issue against the vue extension (vetur?)
