### ISSUE TITLE
VsCode Keep Crashing Then BSOD With Reason Memory Error

### ISSUE THREAD

**Issue by H0llyW00dzZ** [microsoft/vscode#220971]
Does this issue occur when all extensions are disabled?: `N/A`

- VS Code Version: 
- `Latest`
- OS Version: 
- `Windows 11 Pro - Version: 23H2 - OS Build: 22631.3737`

Steps to Reproduce:

1. When Switching Golang source code from New Window then Select Another Golang Source Code
2. It Crash with this reason :

![image](https://github.com/microsoft/vscode/assets/17626300/a06653be-3362-47cc-a4ea-483a9bd64ca4)

3. Then when Click `New Window` it just BSOD With Reason Memory Error

**Comment by H0llyW00dzZ** [comment]
Also, it keeps crashing now, even after I reinstalled VS Code.

**Comment by deepak1556** [comment]
If you still experience the issue with latest stable, please share the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report
