### ISSUE TITLE
Move lines honor indentation rules

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#22093]
It can be part of https://github.com/Microsoft/vscode/issues/4039 but more doable. While implementing this feature, I'll add a new config and that can be extended further for auto indents.

**Comment by borekb** [comment]
So as I move some lines through e.g. TypeScript classes and functions, it will re-indent those lines automatically? From other IDEs, I find this more natural:

- First, I move lines and the editor does _not_ do anything to the indentation.
- Then I press keyboard shortcut to reindent lines.

**Comment by ice-blaze** [comment]
In fact I had already created an issue 5 months ago #14390
