### ISSUE TITLE
Investigate to provide guidance for technology stacks

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#22098]

**Comment by isidorn** [comment]
Please provide steps on how to verify this

**Comment by chrmarti** [comment]
- If the Welcome page shows only a single Quick Links section, set `"telemetry.experiments.mergeQuickLinks": false`.
- Verify the `Languages and Tools` button provides guidance for technology stacks by installing support when clicking on one of its links.

Related: #27430
