### ISSUE TITLE
Windows: Today's Insiders update failed

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#220999]
From @bpasero: 

Sorry, a regression from https://github.com/microsoft/vscode/commit/82c54248fd1373da9f4b4c3606d9778f0d08fc1a that unfortunately already impacted `~14.000` Windows users on insiders. Since they are now on a version that cannot update without failure, you will have to manually install a good version from before.

While we work on a fix, existing users that are impacted, please revert back to Thursdays version `34f8428e4b0e3bf822f4b9e8b4e3e0cab69ef2ce`:

* User Setup (x64): [Download](https://vscode.download.prss.microsoft.com/dbazure/download/insider/34f8428e4b0e3bf822f4b9e8b4e3e0cab69ef2ce/VSCodeUserSetup-x64-1.92.0-insider.exe)
* User Setup (ARM64): [Download](https://vscode.download.prss.microsoft.com/dbazure/download/insider/34f8428e4b0e3bf822f4b9e8b4e3e0cab69ef2ce/VSCodeUserSetup-arm64-1.92.0-insider.exe)
* System Setup (x64): [Download](https://vscode.download.prss.microsoft.com/dbazure/download/insider/34f8428e4b0e3bf822f4b9e8b4e3e0cab69ef2ce/VSCodeSetup-x64-1.92.0-insider.exe)
* System Setup (ARM64): [Download](https://vscode.download.prss.microsoft.com/dbazure/download/insider/34f8428e4b0e3bf822f4b9e8b4e3e0cab69ef2ce/VSCodeSetup-arm64-1.92.0-insider.exe)

**Original Message:**

Version: 1.92.0-insider
Commit: 82104a3a6cf8713b81e5bbd97960dbf5c82a816a
Date: 2024-07-05T00:00:00.000Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.92.0-insider Chrome/122.0.6261.156 Electron/29.4.0 Safari/537.36

Steps to Reproduce:

1. Have a user-type installation of VS Code
2. Check for updates
3. See (1) badge on gearwheel
4. Use its "Install Update... (1)" option.
5. Receive a UAC dialog and approve it.
6. See a VS Code notification.
![image](https://github.com/microsoft/vscode/assets/6726799/d2e18c3b-51a6-413e-bc55-b3c23a812d81)

7. Click "Update Now"
8. VS Code Insiders closes and an error messagebox appears:

![image](https://github.com/microsoft/vscode/assets/6726799/6706ec18-f67e-406f-b9f3-c65ab024f20d)

Screenshot also shows contents of referenced log file.

The updater mistakenly seems to think it is updating a System type installation.

**Comment by bpasero** [comment]
Uncertain if this could be a regression from https://github.com/microsoft/vscode/commit/7c8097dbbfcb9c102a0d3cf014f4ac9b7cfaa0da. Will sync with @joaomoreno

**Comment by bpasero** [comment]
While we work on a fix, existing users that are impacted, please:

⚠ Windows Insiders users please revert back to Thursdays version:
* User Setup (x64): [Download](https://vscode.download.prss.microsoft.com/dbazure/download/insider/34f8428e4b0e3bf822f4b9e8b4e3e0cab69ef2ce/VSCodeUserSetup-x64-1.92.0-insider.exe)
* User Setup (ARM64): [Download](https://vscode.download.prss.microsoft.com/dbazure/download/insider/34f8428e4b0e3bf822f4b9e8b4e3e0cab69ef2ce/VSCodeUserSetup-arm64-1.92.0-insider.exe)
* System Setup (x64): [Download](https://vscode.download.prss.microsoft.com/dbazure/download/insider/34f8428e4b0e3bf822f4b9e8b4e3e0cab69ef2ce/VSCodeSetup-x64-1.92.0-insider.exe)
* System Setup (ARM64): [Download](https://vscode.download.prss.microsoft.com/dbazure/download/insider/34f8428e4b0e3bf822f4b9e8b4e3e0cab69ef2ce/VSCodeSetup-arm64-1.92.0-insider.exe)

**Comment by rmscode** [comment]
> Sorry, a regression from [82c5424](https://github.com/microsoft/vscode/commit/82c54248fd1373da9f4b4c3606d9778f0d08fc1a) that unfortunately already impacted `~14.000` Windows users on insiders. Since they are now on a version that cannot update without failure, you will have to manually install a good version from before.
> 
> **Update:** A fix has been pushed, so please manually install https://code.visualstudio.com/insiders/ over your current installation.

Apologies for the silly question . . . so just proceed by clicking yes rather than uninstalling my current version and then installing the new? 
![image](https://github.com/user-attachments/assets/1a906445-408f-4355-a138-06e88290f33e)

**Comment by rmscode** [comment]
Thanks!

**Comment by Aligorkem04** [comment]
> From @bpasero:
> 
> Sorry, a regression from [82c5424](https://github.com/microsoft/vscode/commit/82c54248fd1373da9f4b4c3606d9778f0d08fc1a) that unfortunately already impacted `~14.000` Windows users on insiders. Since they are now on a version that cannot update without failure, you will have to manually install a good version from before.
> 
> Please manually install the latest version from https://code.visualstudio.com/insiders/ to get updates again.
> 
> **Original Message:**
> 
> Version: 1.92.0-insider Commit: [82104a3](https://github.com/microsoft/vscode/commit/82104a3a6cf8713b81e5bbd97960dbf5c82a816a) Date: 2024-07-05T00:00:00.000Z Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.92.0-insider Chrome/122.0.6261.156 Electron/29.4.0 Safari/537.36
> 
> Steps to Reproduce:
> 
> 1. Have a user-type installation of VS Code
> 2. Check for updates
> 3. See (1) badge on gearwheel
> 4. Use its "Install Update... (1)" option.
> 5. Receive a UAC dialog and approve it.
> 6. See a VS Code notification.
>    ![image](https://private-user-images.githubusercontent.com/6726799/346483889-d2e18c3b-51a6-413e-bc55-b3c23a812d81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTczMTgsIm5iZiI6MTcyMTYxNzAxOCwicGF0aCI6Ii82NzI2Nzk5LzM0NjQ4Mzg4OS1kMmUxOGMzYi01MWE2LTQxM2UtYmM1NS1iM2MyM2E4MTJkODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMDI1NjU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2Y1ZDYyMDhmMDg5Mzg2ZWFkMWE1ZDVjMjYxZGY1MGY0MGQxZWJkMmFhNzBlZmRiN2UwMjAwZGZiNDkzMjIwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YOLgrWNSQGWy2RNnuHcsl945Pu5I_utef9CmHcTWsbw)
> 7. Click "Update Now"
> 8. VS Code Insiders closes and an error messagebox appears:
> 
> ![image](https://private-user-images.githubusercontent.com/6726799/346483661-6706ec18-f67e-406f-b9f3-c65ab024f20d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTczMTgsIm5iZiI6MTcyMTYxNzAxOCwicGF0aCI6Ii82NzI2Nzk5LzM0NjQ4MzY2MS02NzA2ZWMxOC1mNjdlLTQwNmYtYjlmMy1jNjVhYjAyNGYyMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMDI1NjU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDdiZWI4YjJjMmM5MmMzNjRmNDhiNDc3OTY5OTIyMjcxOTNkNzM3ZTJlOGFmMWRiNzI2OWU4ZDMzOTk4ODQ2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sVh05TZS8mkot_sTxjZVOLWGbyNDCHXSv3yq4LP2Uu4)
> 
> Screenshot also shows contents of referenced log file.
> 
> The updater mistakenly seems to think it is updating a System type installation.

**Comment by Aligorkem04** [comment]
- [ ] #222708
