### ISSUE TITLE
Can not reach my virtual environment by remote

### ISSUE THREAD

**Issue by joguy56** [microsoft/vscode#220988]
Type: <b>Bug</b>

The link with my remote environment seems to be broken on the last 1.91 update.

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Connection to 'SSH: airphone-vm-dev' could not be established  WrappedError(WrappedError { message: "failed to download file", original: "No space left on device (os error 28)" })

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 5650U with Radeon Graphics      (12 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|14.83GB (4.93GB free)|
|Process Argv|--crash-reporter-id f68a4f03-5f8e-4eef-974d-575dbaed89d2|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: airphone-vm-dev' could not be established  WrappedError(WrappedError { message: "failed to download file", original: "No space left on device (os error 28)" })
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
json-merger|Amo|0.0.1
vscode-django|bat|1.15.0
javascript-extensions-pack---js-essentials|Bre|0.0.2
vscode-pytest|Cam|0.1.1
gitignore|cod|0.9.0
python-snippets|cst|0.1.2
epub-reader|cwe|1.0.0
vscode-pytest-intellisence|dat|0.0.1
vscode-eslint|dba|3.0.10
git-extension-pack|don|0.1.3
githistory|don|0.6.20
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
gitlens|eam|15.1.0
LogFileHighlighter|emi|3.2.0
vsc-material-theme|Equ|34.4.0
vsc-material-theme-icons|equ|3.6.1
prettier-vscode|esb|10.4.0
html-preview-vscode|geo|0.2.5
copilot|Git|1.211.0
copilot-chat|Git|0.17.0
git-worktrees|Git|2.2.0
vscode-ansi|ili|1.1.7
web-preview|Jab|1.0.3
vsc-python-indent|Kev|1.18.0
log-helper|Log|0.0.3
bash-ide-vscode|mad|1.41.0
code-groovy|mar|0.1.2
vsc-webshark|mbe|2.1.0
git-graph|mhu|1.30.0
autopep8|ms-|2024.0.0
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.375.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
cpptools|ms-|1.20.5
live-server|ms-|0.4.13
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
test-adapter-converter|ms-|0.1.9
vscode-groovy-lint|Nic|3.3.1
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
vscode-jest|Ort|6.2.5
material-icon-theme|PKi|5.4.2
text-power-tools|qcz|1.47.1
vscode-xml|red|0.27.1
chordpro|ric|0.2.0
LiveServer|rit|5.7.9
pdf|tom|1.2.2
simple-rst|tro|1.5.4
python-extended-snippets|tus|0.0.1
pypi-assistant|twi|2.0.5
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
vscode-open-in-github|ziy|1.3.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31082723

```

</details>

**Comment by roblourens** [comment]
> `No space left on device`

Seems that your disk is out of space
