### ISSUE TITLE
Launching shared process is slow

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#22091]
We receive cpu profiles that show spawning the shared process being very slow in some cases. 
<img width="766" alt="screen shot 2017-03-06 at 18 18 16" src="https://cloud.githubusercontent.com/assets/1794099/23621022/599d65b0-0299-11e7-932d-915a525cad19.png">

**Comment by jrieken** [comment]
I assume this resolves itself when we start to use a browser window, right?

**Comment by joaomoreno** [comment]
Hopefully, can I get your help on measuring perf after I merge #21879? This will happen today.

**Comment by jrieken** [comment]
sure

**Comment by FloMaetschke** [comment]
If you need someone to test, i am here! ;)

**Comment by joaomoreno** [comment]
@jrieken This is how it looks like now:

![image](https://cloud.githubusercontent.com/assets/22350/23665257/439306e8-0358-11e7-983b-e7ba70b8b4fa.png)
