### ISSUE TITLE
custom ssh not work

### ISSUE THREAD

**Issue by SplitGemini** [microsoft/vscode#220973]
Type: <b>Bug</b>

Set remote ssh path to C:\Program Files\Git\usr\bin\ssh.exe
It is a valid ssh executable, but vscode won't use it.
Output: 
```
Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
ssh is not exiting, continuing
The specified path C:\Program Files\Git\usr\bin\ssh.exe is not a valid SSH binary
```

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.72GB (1.35GB free)|
|Process Argv|--crash-reporter-id 62872d0c-ed99-4b09-a2ad-3d1e1020f069|
|Screen Reader|no|
|VM|15%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nginx-conf|ahm|0.3.5
project-manager|ale|12.8.0
tongyi-lingma|Ali|1.3.2
meson|asa|1.3.0
gitignore|cod|0.9.0
systemd-unit-file|coo|1.0.6
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|3.0.10
fileheadercomment|doi|0.0.5
git-extension-pack|don|0.1.3
githistory|don|0.6.20
python-environment-manager|don|1.2.4
gitlens|eam|15.1.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
shell-format|fox|7.2.5
codespaces|Git|1.17.1
vscode-drawio|hed|1.6.6
output-colorizer|IBM|0.1.2
vscode-ansi|ili|1.1.7
cmake-language-support-vscode|jos|0.0.9
bash-ide-vscode|mad|1.41.0
vscode-docker|ms-|1.29.1
vscode-language-pack-zh-hans|MS-|1.91.2024070309
vscode-dotnet-runtime|ms-|2.0.8
autopep8|ms-|2024.0.0
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.8.1
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.375.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
cmake-tools|ms-|1.18.42
remote-explorer|ms-|0.5.2024070409
color-highlight|nau|2.8.0
devicetree|plo|0.1.1
nginx-formatter|ray|0.0.13
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
bash-debug|rog|0.3.9
rust-analyzer|rus|0.3.2020
markdown-preview-enhanced|shd|0.8.13
code-spell-checker|str|3.0.1
shellcheck|tim|0.37.1
cmake|twx|0.0.17
vscode-todo-highlight|way|1.0.5
vscode-nginx|wil|0.7.2
markdown-all-in-one|yzh|3.6.2
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
legacy_priority:31082724

```

</details>

**Comment by guoh27** [comment]
Oh, its my PC's problem, sometimes ssh running stucked, it fixed after I reboot my PC.
