### ISSUE TITLE
vscode forces file extension while saving new file

### ISSUE THREAD

**Issue by luboi75** [microsoft/vscode#220990]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.91.0
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:52:41.959Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.9.7-100.fc39.x86_64
- OS Version: 
Linux 6.9.7-100.fc39.x86_64 x86_64
NAME="Fedora Linux"
VERSION="39 (KDE Plasma)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
VARIANT="KDE Plasma"
VARIANT_ID=kde

Steps to Reproduce:

1.  create new file
2.  write some content, use yaml syntax, so vscode identifies file as yaml
3. attempt to save
4. remove yaml extension from name in save dialog
5. complete save operation
6. file has yaml extension even though you removed it in dialog

**Comment by bpasero** [comment]
Could be a regression from the file dialog rewrite on Linux.

**Comment by bpasero** [comment]
I can actually not reproduce on Ubuntu at least.

**Comment by luboi75** [comment]
disappeared ... now I see checkbox under the dropdowns in save dialog that allows me to avoid txt suffix 
unsure whether this was caused by vs-code, gtk, kde or any other update in the meantime ..
