### ISSUE TITLE
[editor] Inconsistent highlight colour/style in CSS. Leads to perceived slow perf

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#2209]
Notice when selecting an element vs selecting a class:

Class:
![1iott3](https://cloud.githubusercontent.com/assets/465069/12539705/a76b221e-c2ad-11e5-8af1-b834b73b2183.gif)

Element (and IDs behave same way)
![kxaktu](https://cloud.githubusercontent.com/assets/465069/12539714/c52caee4-c2ad-11e5-9c19-ec27dbc0232c.gif)

Former has highlight that looks like low opacity version of text colour. The highlight has some delay (shows more in the app than the gif) and little (or no?) transition.

The latter has a blue (at least in dark theme) highlight, and has a slow transition effect.

As well as being inconsistent, the delay and the fade give a perceived lack of performance as you need to wait for the highlight to finish. IMHO no transition or a speeded up transition-duration would feel faster.

**Comment by aeschli** [comment]
What you first see is the selection color, later overpainted by the mark occurrences feature, with a delay and using the transition effect.
What themes are these animations made with. Is it the same theme in both?

**Comment by dstorey** [comment]
yes, this is both the same default dark theme.

**Comment by dstorey** [comment]
This bug report comes from a Twitter discussion: https://twitter.com/camcavers/status/691382766987038720
https://twitter.com/camcavers/status/691387330825949184

**Comment by aeschli** [comment]
This never bothered me. I agree the animation is a bit slow and could be sped up.

**Comment by alexandrudima** [comment]
@aeschli I'm sorry, I don't understand why it looks different when selecting a tag name compared to selecting a class name. If you understand then please go ahead and edit whatever css animations we have around there.

**Comment by aeschli** [comment]
Closing, no action planed here.
