### ISSUE TITLE
Option to "keep open" by default for all new tabs?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/vscode#22100]
I *always* end up Ctrl + K / Enter -ing to keep the tab open. It's a little irritating. Would it be reasonable to add an option to always keep tabs open by default?

**Comment by ramya-rao-a** [comment]
Try `"workbench.editor.enablePreview": false`

**Comment by JoshuaKGoldberg** [comment]
👍 thanks!

**Comment by sullerandras** [comment]
In case someone ends up here from a google search as i did, in my experience disabling preview as suggested above results in a lot of unnecessary tabs. I found that disabling only the following setting is better (and more similar to other editors like Atom and Sublime Text):
```
"workbench.editor.enablePreviewFromQuickOpen": false
```
