### ISSUE TITLE
Add open in preview button to SVG files, like Markdown

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#2210]
Image file currently show the image when opened in VSCode. For SVG files, it would be useful to have the same "open in preview" button as markdown, to give a preview of how the image is rendered. Bonus points if it updates as the source is updated without having to press refresh.

This would make working with SVG files much easier.

**Comment by dstorey** [comment]
The markdown preview can already handle SVG markup, including live editing, so it is probably possible to share code here.

**Comment by egamma** [comment]
@jrieken fyi

**Comment by kisstkondoros** [comment]
FYI: https://marketplace.visualstudio.com/items?itemName=kisstkondoros.svgpreview

**Comment by jrieken** [comment]
Agreeing @kisstkondoros that this should be done via an extension. We have added API to add commands/action to editor titles and context menus
