### ISSUE TITLE
[php] syntax highlighter issue with SQL

### ISSUE THREAD

**Issue by Gonkers** [Microsoft/vscode#22105]
The PHP syntax highlighter seems to have a bug. It attempts to syntax highlight SQL code within PHP strings, but if there is a SQL comment on the last line of the string, the highlighter gets confused...
![image](https://cloud.githubusercontent.com/assets/8480646/23629003/424967f2-0284-11e7-8944-0c04bc2bf0a5.png)

- VSCode Version: 1.10.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a php file.
2. Add the following code...
```
        $sql = "SELECT value1
                FROM table_name t
                WHERE t.column1 = 3
                  --AND t.column2 = 'value';"
```

**Comment by aeschli** [comment]
This issue was moved to atom/language-php#187
