### ISSUE TITLE
Persisting Code Lens Cache does not work in some cases

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#221005]
This seems very fishy:

https://github.com/microsoft/vscode/blob/603b0ee03b82cc77f90f56a5e0ecfbeee3213de1/src/vs/editor/contrib/codelens/browser/codeLensCache.ts#L64-L68

There is also `WillSaveStateReason.NONE`, in which case the event handler just unsubscribes because of the `once`.

I think this code should be like this:
```ts
const onWillSaveStateBecauseOfShutdown = Event.filter(storageService.onWillSaveState, e => e.reason === WillSaveStateReason.SHUTDOWN);
Event.once(onWillSaveStateBecauseOfShutdown)(e => {
	storageService.store(key, this._serialize(), StorageScope.WORKSPACE, StorageTarget.MACHINE);
});
```

I have a PR here: https://github.com/microsoft/vscode/pull/221007

**Comment by jrieken** [comment]
Nice find. Fix is ✅ tho I believe the original usage of `once` is because services didn't get disposed. So, `once` could also be replaced with a registered listener that gets disposed with the owning service
