### ISSUE TITLE
Differently encoded files show modified decoration

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#22109]
- Get a encoded as UTF-16 or some other non-UTF-8 encoding, like 
[utf-16-big-endian.txt](https://github.com/Microsoft/vscode/files/822645/utf-16-big-endian.txt)
- Initialize a git repo with that file, commit it
- Open the file
- The whole thing shows the blue modified indicator on the side:

![image](https://cloud.githubusercontent.com/assets/323878/23631950/ee29680c-0274-11e7-98df-69bead0a2b55.png)

**Comment by joaomoreno** [comment]
#21146
