### ISSUE TITLE
Unable to open 'Release Notes: 1.10.1': Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by gstar42** [Microsoft/vscode#22107]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.3.0|
|qub-xml|qub|0.3.0|
|vscode-icons|robertohuertasm|1.6.5|

---

Steps to Reproduce:

1. Click on 'read release notes' before actually loading update
2.

**Comment by chrisdias** [comment]
i just saw this on another person's machine... this came up when clicking on the "release notes" link on the information bar that prompts the user to update their version.

**Comment by wusphinx** [comment]
I also saw this on my MacBook Pro(os sierra 10.12), 
but my vscode version is:
1.9.1 

f9d0c687ff2ea7aabd85fb9a43129117c0ecf519

2017-02-08T23:29:25.464Z

**Comment by joaomoreno** [comment]
Fixed in 1.10
