### ISSUE TITLE
code slow startup

### ISSUE THREAD

**Issue by olebg** [Microsoft/vscode#22106]
- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:10:18.838Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15031</code>
- CPUs: <code>Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz (4 x 3009)</code>
- Memory (System): <code>7.96GB (3.77GB free)</code>
- Memory (Process): <code>135.82MB working set (136.31MB peak, 107.75MB private, 33.59MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|38|
|main|app.isReady => window.loadUrl()|526|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|641|
|renderer|require(workbench.main.js)|936|
|renderer|create extension host => extensions onReady()|1667|
|renderer|restore viewlet|0|
|renderer|restore editor view state|670|
|renderer|overall workbench load|2135|
|main + renderer|start => extensions ready|3985|
|main + renderer|start => workbench ready|4300|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\olebg\ed71_main.cpuprofile.txt`
-`C:\Users\olebg\ed71_renderer.cpuprofile.txt`

**Comment by ramya-rao-a** [comment]
@olebg You need to attach the files 

- C:\Users\olebg\ed71_main.cpuprofile.txt
- C:\Users\olebg\ed71_renderer.cpuprofile.txt

**Comment by olebg** [comment]
I don't have those files. Instead I have ed71_main.cpuprofile.txt and ed71_renderer.cpuprofile.txt

**Comment by olebg** [comment]
[ed71_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/824621/ed71_main.cpuprofile.txt)
[ed71_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/824622/ed71_renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
Thanks for the profiles, we have found #22086  and #21963. Fixes for both should land in insiders very soon. Happy Coding!

**Comment by olebg** [comment]
Thank you. 😊
