### ISSUE TITLE
Output console error catch (feature)

### ISSUE THREAD

**Issue by opensw** [Microsoft/vscode#22104]
Hello there, will be nice to have an error handler from output console; I mean, if I want to compile a file with gcc/g++ or make (from task.json) and during compilation there are some errors, will be great to (Ctrl +) click on the error showed on output console of Visual Studio Code and to be redirected to specified file at specified line number and column number (like in Eclipse).

The format error string showed on the output console is like (in python it is almost the same) :
fileName:line number:column number: error: description error

Just an error example:
file.cpp:630:6: error: expected '}' before 'else'

What do you think? I think this feature can improve a lot the productivity.

Cheers
Paolo

**Comment by ramya-rao-a** [comment]
This should be do-able using problem matchers by extensions
@dbaeumer Can you add more insights here?

**Comment by dbaeumer** [comment]
This will be possible when running tasks in the terminal.

**Comment by opensw** [comment]
Great :), what is the best approach @ramya-rao-a  @dbaeumer  among the following:
1) Handling by specific extension (i.e. C++, python and so on)?;
2) Handling directly by Visual Studio Code (like in the case of PROBLEMS console)?;
3) Create a new extension and share with the community?
4) Other?

Can you give me just a starting point from where to start to implement this feature? I do not know anything about type script but it does not seem so complex compared to C/C++/C#/Python etc...

Thank you

**Comment by opensw** [comment]
@dbaeumer  OK, if you need a beta tester for C/C++, C# and Python I am here :)

**Comment by dbaeumer** [comment]
OK. Thanks for offering.

**Comment by ramya-rao-a** [comment]
The Go extension sends the build output to the a separate output channel, and the underlined text is clickable and takes you to the right file/line.

![image](https://cloud.githubusercontent.com/assets/16890566/23673546/87408bb2-0327-11e7-8d18-1442f9922ca8.png)

No tasks are used here though. And all the Go extension does is print out the file and line number in this format: `${file}:${line}` See: https://github.com/Microsoft/vscode-go/blob/be89ac1c298f8fe7a54e43cb44f325ab3008bfbb/src/goCheck.ts#L87

@dbaeumer Any reason why this wont work for the Tasks output channel?

**Comment by dbaeumer** [comment]
@ramya-rao-a  the reason is that most compilers print relative file paths and those aren't auto detected by the output panel do to too many false positives. The terminal on the other side allows to customize these link detector to make them specific to the problem matcher defined in tasks.json. Such a support got never added to the output panel.

**Comment by ramya-rao-a** [comment]
Understood, thanks @dbaeumer

**Comment by dbaeumer** [comment]
Dups #21928
