### ISSUE TITLE
allow focusing chat response list via keyboard for terminal chat

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#221147]
> @meganrogge @Tyriar I can't remember what terminal chat looked like in March, do you still want this disabled? I think we probably want it enabled in all chat widgets now: https://github.com/microsoft/vscode/issues/208927 

 _Originally posted by @roblourens in [#218088](https://github.com/microsoft/vscode/issues/218088#issuecomment-2197419000)_

**Comment by meganrogge** [comment]
This is already possible - though it's reversed compared to what a user might expect - `cmd/ctrl+downArrow` focuses the chat response list and the opposite focuses the input. We have a similar issue with the quick chat. #228598

**Comment by meganrogge** [comment]
this is working AFAICT

**Comment by rzhao271** [comment]
On Windows,

1. I have to use Ctrl+Up to both go to the list and to go back down to the inputbox.
2. Even after I focus the list, when I press Up again, it goes back in the input history instead of the list.

![Focus is on list but input updated](https://github.com/user-attachments/assets/8485d11e-436b-4f86-be3c-b1cdf5f5a0c9)

**Comment by meganrogge** [comment]
Only tested on mac. Strange that they're different. @rzhao271 does that reproduce in the panel chat?

**Comment by rzhao271** [comment]
No. It only occurs in terminal chat

**Comment by rzhao271** [comment]
My current experience is I can use Ctrl+Up and Ctrl+Down to switch between the input box and the chat messages. While focused on the chat messages, I have to use Shift+Up and Shift+Down to navigate the messages, otherwise it goes through the input box history instead.
