### ISSUE TITLE
"editor.minimap.enabled": true

### ISSUE THREAD

**Issue by Topmawei** [Microsoft/vscode#22116]
- VSCode Version: <code>Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)</code>
- OS Version: <code>Windows_NT ia32 6.1.7601</code>
- CPUs: <code>Pentium(R) Dual-Core  CPU      E5400  @ 2.70GHz (2 x 2693)</code>
- Memory (System): <code>3.90GB (1.12GB free)</code>
- Memory (Process): <code>123.27MB working set (144.51MB peak, 89.20MB private, 40.11MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|94|
|main|app.isReady => window.loadUrl()|1177|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|1894|
|renderer|require(workbench.main.js)|2648|
|renderer|create extension host => extensions onReady()|5859|
|renderer|restore viewlet|2064|
|renderer|restore editor view state|2905|
|renderer|overall workbench load|6690|
|main + renderer|start => extensions ready|12114|
|main + renderer|start => workbench ready|12543|

---

Additional Steps to Reproduce (if any):

1.
2.

**Comment by ramya-rao-a** [comment]
@Topmawei What is the issue? Can you provide details and repro steps? We can't figure out anything from the title and description.

**Comment by ramya-rao-a** [comment]
@Topmawei 
Closing this issue as we haven't heard back from you in a while.
Feel free to re-open when you have more details to share
