### ISSUE TITLE
Align X button in activity bar between primary and secondary side bars

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#221129]
Currently only the secondary sidebar has the close button. It should align with when the activity bar is at the top with the primary sidebar.

**Comment by gjsjohnmurray** [comment]
With the change that's about to land in 1.92 it's now less convenient for a right-side Activity Bar person like me to close the Secondary Side Bar that appears on the left when I use (for example) `Find All References` from a code editor context menu. Either I move my mouse all the way to the right-hand end of the window title and untoggle the relevant WCO button, or I go to the top menubar, choose View, then Appearance, then untoggle Secondary Side Bar there.

Personally I think the opposite change would have been preferable, i.e. show an [X] button at the right-hand end of the Primary Side Bar's tabs when Activity Bar is at the top. This would make it consistent with Panel, which always has an [X] top-right.

**Comment by kenzaflow** [comment]
My god, today I open vscode and I find that the X is not there, and I find that they took it out deliberately, not even a setting to toggle it

**Comment by benibenj** [comment]
@gjsjohnmurray do you use the layout controls to hide and show the primary sidebar when the activity bar is at the top?

**Comment by gjsjohnmurray** [comment]
@benibenj I know I can do that. In reality I tend to leave my right-positioned top-tabbed primary sidebar visible all the time. It's the secondary sidebar that I typically hide when I don't need it, e.g. after a References search caused it to appear. I didn't mind the inconsistency of there being an [X] on the secondary sidebar but not the primary.
