### ISSUE TITLE
VSCode generates wrong ${command.pickProcess} for .NET Core project

### ISSUE THREAD

**Issue by cateyes99** [Microsoft/vscode#22113]
- VSCode Version: 1.10.1
- OS Version:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
Steps to Reproduce:
1. create a .net core project by running the command `dotnet new console`
2. In `Show Debug` window, click `Add Configuration...`, in the drop-down list select `.NET Core`
3. In the newly generated `launch.json` file, check `"processId": "${command.pickProcess}"` which should be `"processId": "${command:pickProcess}"`

**Comment by ramya-rao-a** [comment]
The contents of the launch.json file gets generated by the extension and not VS Code (unless you are doing  node debugging).
Please figure out which extension you are using for .net work, and log an issue in the repo for that extension
