### ISSUE TITLE
Open File via a shortcut in diff editor opens files in read only in some cases

### ISSUE THREAD

**Issue by fcFn** [microsoft/vscode#221137]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.0
- OS Version: Windows 10 10.0.19045 Build 19045

### Steps to Reproduce:

1. Have outgoing changes in your source control view.
2. Click on a file that has changes in a commit to open diff view.
3. Configure a shortcut for the `Open File` action.
4. Press the shortcut. 
5. Observe that the file is opened in read only mode.
6. Go back to the diff view and click the `Open File` button with a mouse.
7. Observe that the file opened in writeable mode.

### Expected results:
1. The way the action is invoked should not affect the mode in which the file is opened. I would personally prefer it to always open file in writeable mode if possible.

**Comment by abradley-storengy** [comment]
+1, also experiencing this

**Comment by lszomoru** [comment]
Sorry for not getting back to you on this. Could you please provide a screenshot or the contents of the keybinding that you have defined for the "Open File" action. You should also note that the git extension defines two "Open File" actions: `git.openFile`, and `git.openFile2`.
