### ISSUE TITLE
Allow to bind keybindings for opening individual indexes of the opened editors

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#2211]
The usual keystroke pattern on a Mac for referencing one of several windows (as might be open on the left Explorer/Working Files area) is cmd-1, cmd-2, etc, either from top to bottom or left to right. What would be the proper way to adjust my settings so that I accomplish this way of selecting windows in the Working Files area? 

Besides that, I'm not sure why choosing cmd-2 would open a second/duplicate window for the one I'm already on...

**Comment by bpasero** [comment]
@resir014 workbench.view.explorer is the action to focus the explorer and you can bind it to cmd+0 for example.

**Comment by rhires** [comment]
Well, yes, I can focus on the Working Files area (is that "Workbench"?), but that's only half the solution. The other part is, how do I tell cmd-1 to open the top-most item in the list, and cmd-2 the 2nd item from the top? If there isn't, I would like to see this added.

**Comment by bpasero** [comment]
@rhires so you want cmd+1 to open explorer, cmd+2 to open search, cmd+3 to open git and cmd+4 to open debug?

**Comment by rhires** [comment]
Hmmm...In the Working Files area is a list of my currently "active" documents. If I'm on the third one in the list, and I push cmd-1, I want the one at the top of the list to show up in place of the one I am currently on. If I hit cmd-2, then the 2nd from the top of the list of files shows up. This would be similar to what happens when I hit this key combination in Firefox - cmd-1 shows the left-most window, cmd-2 shows the one to the right of that, etc.  I hope this screenshot is ok, since I'm not doing so well with the words.

![image](https://cloud.githubusercontent.com/assets/12577765/12613571/a2971f78-c4c8-11e5-88e6-eefcb64812ef.png)

**Comment by bpasero** [comment]
Ok I see, that is different then from what I thought.

**Comment by bpasero** [comment]
@rhires maybe you can get used to Cmd+Tab?

**Comment by rhires** [comment]
Yes, alt-tab works well enough, I guess, but it's kinda fumbly, if you take my technical talk ;-) 

To rephrase: while that is an option, it's not as easy or precise as I would like. I can alt-tab, but the focus hits the icons on the left first (they "highlight" or turn from grey to white, one at a time), then the focus disappears for a few key strokes, then the Working Files area gets the focus. Once I'm there I can then up-arrow/down-arrow to choose the file that I want...but that's a lot of fumbling around to get where I want to go.

**Comment by bpasero** [comment]
@rhires I meant Cmd+Tab, leave Cmd key down, use Tab to navigate up and down, release to open.

**Comment by rhires** [comment]
Yes, I thought you did, but on Macs cmd-tab is the same as alt-tab on Windows (the keys are in the same places) - it changes the window/program. I didn't acknowledge that difference in my previous response. I also want to acknowledge how wonderful and awesome it is to be able to develop on my Mac using all the tools that Microsoft has provided. VSCode is a great tool and I'm very happy to have it!

**Comment by bpasero** [comment]
@rhires a sorry man, I am so used to Ctrl+Tab, it is of course that, not Cmd+Tab !

**Comment by rhires** [comment]
@bpasero Ha! It's ok. Xplat is confusing in these smaller issues. ctrl-tab is useful! But as it is a "recently opened" list, I see other things that are, well, recently opened but aren't currently in the "Working Files" area, so I can toggle between the two or three _really most recently_ opened, which generally are in the Working Files area. So I guess that's ok. I'd still like the other thing, though.  :-)

**Comment by bpasero** [comment]
Got it, there is more people that ask for a "Working Files" only solution.

**Comment by bpasero** [comment]
@rhires for february we land a quick picker for working files, see demo https://github.com/Microsoft/vscode/issues/441#issuecomment-181423099

feedback welcome

**Comment by rhires** [comment]
Awesome!!
