### ISSUE TITLE
Drag&Drop from Open File Dialog causes VS Code to Freeze

### ISSUE THREAD

**Issue by StarTether** [Microsoft/vscode#22114]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.15048
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.6.2|;

---

Steps to Reproduce:

1. Click "File"->"Open File..." 
2. Find some file to open
3. Instead of clicking "Open" in the Open File Dialog, drag the file into the main window.
4. Close the Open File Dialog without selecting a file

Expected:
Can continue to use VS Code as usual.
Actual:
VS Code shows the "edit text" mouse cursor and is no longer interactive. I typically have to kill the process to resume.

**Comment by d8vjork** [comment]
Me too, trying to drag&drop a file from explorer then explorer freeze

**Comment by bpasero** [comment]
i cannot reproduce on my Win10 box...

**Comment by StarTether** [comment]
It may be because I am on a preview build of Windows 10. Currently I am on 15058.0. I haven't tried to repro this lately, though.
