### ISSUE TITLE
Reformat ternary operator

### ISSUE THREAD

**Issue by lijunray** [Microsoft/vscode#22110]
- VSCode Version: 1.9.1
- OS Version: MacOS 10.12.3

Steps to Reproduce:

The default reformatting for ternary operator is working unexpectedly.

What I want:

[![enter image description here][1]][1]

After Reformatting:

[![enter image description here][2]][2]

How can I config the reformatting so that it works as I expect?

  [1]: https://i.stack.imgur.com/vnwGM.png
  [2]: https://i.stack.imgur.com/yhZei.png

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14494
