### ISSUE TITLE
VS Code do not show side bar after press hotkey(ctrl+shift+F，G or E).

### ISSUE THREAD

**Issue by xiaoski** [Microsoft/vscode#22119]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|1.3.1|
|vscode-markdownlint|DavidAnson|0.6.2|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.9|
|xml|DotJoshJohnson|1.7.0|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.10.2|
|material-icon-theme|PKief|1.3.4|
|vscode-icons|robertohuertasm|7.3.0|
|vscode-hexdump|slevesque|1.2.0|
|ayu|teabyii|0.2.1|
|gitblame|waderyan|1.3.0|
|Material-theme|zhuangtongfa|2.1.7|;

---

Steps to Reproduce:

1.Hide the side bar, and then set focus on edit area.
2.press ctrl+shift+(F G or E) 
3.VS Code won't show sider bar.

Expecedt Behavior:
If side bar is hide, VS code should show it first when user press those hotkey.

**Comment by ramya-rao-a** [comment]
The side bar appears when using the hot keys for me.
But when I hide the activity bar, and then use the hot keys, only the side bar appears and the activity bar doesnt.

Are you referring to the activity bar or the side bar?

Below A is the Activity bar and B is the side bar

![image](https://cloud.githubusercontent.com/assets/16890566/23639696/f422e94e-029d-11e7-9081-e40ba625a236.png)

**Comment by xiaoski** [comment]
In fact, I means the activity bar. I will corecte the description, Thank you.

**Comment by xiaoski** [comment]
I mean the side bar which can be hide or show by hotkey Ctrl + B. My activity bar shows all the time, usually i only hide the side bar to enlarge edit area. But when I have to search something in the project, I have to press Ctrl + B to show it, and then press Ctrl + Shift + F. I really like VS Code, but this is not convenient.

**Comment by ramya-rao-a** [comment]
Thanks @xiaoski , I still cant repro it
@bpasero would know more

**Comment by xiaoski** [comment]
I think I have found the reason. A IME sofware caused it. I'm sorry to trouble you guys.

**Comment by ramya-rao-a** [comment]
No problem @xiaoski, glad you are unblocked now. Happy Coding!
