### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ravechan** [Microsoft/vscode#22120]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vue-snippets|hollowtree|0.1.0|
|vue|liuji-jim|0.1.5|
|ejs-language-support|QassimFarid|0.0.1|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please provide some information about the error
