### ISSUE TITLE
Can't auto update vscode anymore if installed in custom path

### ISSUE THREAD

**Issue by tisonv** [microsoft/vscode#221237]
Type: <b>Bug</b>

1. Install VSCode on `D:\` or any path
2. Lauch VSCode and Check for updates
3. Agree to install the update
4. Update will fail with message `ERRO Bad arguments: Code path doesn't seem to exist: C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe`

Updating from .exe works nicely.

VS Code version: Code - Insiders 1.92.0-insider (b7c13a78e93c2762972be705c032fe8295a87ddb, 2024-07-08T14:53:42.931Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.39GB free)|
|Process Argv|--crash-reporter-id ea8c49f9-12cc-4e3b-9b05-94db850bf79c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipfs|arc|3.0.0
vscode-eslint|dba|3.0.11
gitlens|eam|2024.7.818
vscode-great-icons|emm|2.1.105
prettier-vscode|esb|10.4.0
playwright|ms-|1.1.7
sonarlint-vscode|Son|4.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialogc:30812479
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
chatpanelt:31014475
da93g388:31013173
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nb_pri_only:31057983
nativerepl2:31071685
refactort:31084545
pythonrstrctxt:31089940
0c838689:31088353
1iic9185:31091668

```

</details>

**Comment by gjsjohnmurray** [comment]
My guess is that you were affected by https://github.com/microsoft/vscode/issues/220999

**Comment by tisonv** [comment]
Indeed !
Didn't think to search on already closed issues. My bad.
