### ISSUE TITLE
Allow to save readonly documents

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#22121]
- Debug a node app
- Click a stack frame from some internal node module like timers.js or module.js
- Execute 'save as', cmd+shift+s

It should open a save dialog for me to save the contents of the editor to some file on disk, but it does nothing.

**Comment by bpasero** [comment]
With the re-work on save/saveas for custom editors, I decided to give this another shot and it should work fine now for any readonly editor that is using the text model content provider.

**Comment by bpasero** [comment]
**Verification:** debug a node.js program and step into a node internal. Make sure you can File > Save As the contents to a file on disk.
