### ISSUE TITLE
Codelens Location setting to the right of the code

### ISSUE THREAD

**Issue by Anongh** [Microsoft/vscode#22127]
- VSCode Version: 1.10.1
- OS Version: Windows 8

~~~
	public List<AdjacentInfo> openList;     11 references
	public List<Vector2> closeList;         5 references
	public AdjacentInfo currentTile;        2 references
	public AdjacentInfo parent;             7 references

	Vector2 targetPos;   // destination     4 references
	List<Vector2> path;                     7 references

	void RemoveStartingNode()               4 references
	{
		openList.Remove(currentTile);
		closeList.Add(currentTile.currentPos);
	}
~~~

Each time codelens appears, the code oscillates and increases its length.
So I suggest the above.

Thank you.

**Comment by ramya-rao-a** [comment]
On very long lines of code, the codelens ends up out of the viewport in this design though.

**Comment by stevencl** [comment]
I understand the concern, but we did a lot of research into the placement of codelens indicators and positioning them above the associated symbol was one that made it easier to see and to associate with the symbol itself.

As well as the point that @ramya-rao-a makes about the length of a line impacting the ability to see codelens indicators, it's also possible that at some point in the future we may decide to do what Visual Studio does. It places lenses at the end of the line when stepping through code in the debugger to show how long it took to execute that line:

![image](https://cloud.githubusercontent.com/assets/1704059/23708635/83b7df62-040e-11e7-9ff7-814b375caca0.png)

**Comment by Anongh** [comment]
@ramya-rao-a It's a good point. If it's a problem to go to the end of the viewport, why not arrange the code lens without alignment?

@stevencl If the codelens has more elements then the codelens should be set as now.
~~~
        0 referances | Someone, 5 days ago | 1 author, 1 change | 0 requests | 0 exceptions
	public List<AdjacentInfo> openList;  
	public List<Vector2> closeList;  5 references
	public AdjacentInfo currentTile;  2 references
	public AdjacentInfo parent;  7 references

	Vector2 targetPos;   // destination  4 references
	List<Vector2> path;  7 references

	void RemoveStartingNode()  4 references
	{
		openList.Remove(currentTile);
		closeList.Add(currentTile.currentPos);
	}
~~~

Anyway thanks for the answers.

**Comment by pflannery** [comment]
I have a request for code lenses in [versionlens](https://github.com/vscode-contrib/vscode-versionlens/issues/40) to be place-able on the right hand side. 
This would be a nice option to have and they wouldn't go off screen in most cases.
