### ISSUE TITLE
Initializing JS/TS language features crash all the time

### ISSUE THREAD

**Issue by VincentWeyh** [microsoft/vscode#221266]
Type: <b>Bug</b>

I'm just opening ts files and the Initializing JS/TS language features crash all the time

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (13.05GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/home/vincent/glb-hotels --crash-reporter-id 216d0dc8-34c2-491a-b8f4-bc05d0bf91c0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 0)|
|Memory (System)|15.59GB (10.42GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.88.2
vs-keybindings|ms-|0.2.1
material-icon-theme|PKi|5.4.2
vscode-eslint|dba|3.0.10
gitlens|eam|15.1.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
copilot|Git|1.211.0
copilot-chat|Git|0.17.0
vs-keybindings|ms-|0.2.1
vsliveshare|ms-|1.0.5932
vsliveshare-pack|ms-|0.4.0
material-icon-theme|PKi|5.4.2
volar|Vue|1.8.27

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31082723

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

The most likely is Volar

**Comment by johnsoncodehk** [comment]
> The most likely is Volar

I don't think so in this case, `Vue.volar` only includes the TS plugin when >=2.0.0, this report is using `Vue.volar` 1.8.27, and `Vue.vscode-typescript-vue-plugin` is not installed, so the Vue extension will not affect tsserver.

@VincentWeyh The crash is more likely related to the upgrade of VSCode 1.91 to TS 5.5. It may be helpful if you can provide the log file opened by executing the "TypeScript: Open TS Server log" command.

**Comment by VincentWeyh** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
> 
> The most likely is Volar

I think the crash happens in plain ts files too, after some times.

> > The most likely is Volar
> 
> I don't think in this case, `Vue.volar` only includes the TS plugin when >=2.0.0, this report is using `Vue.volar` 1.8.27, and `Vue.vscode-typescript-vue-plugin` is not installed, so the Vue extension will not affect tsserver.
> 
> @VincentWeyh The crash is more likely related to the upgrade of VSCode 1.91 to TS 5.5. It may be helpful if you can provide the log file opened by executing the "TypeScript: Open TS Server log" command.

Thanks for the hint, I'll have a look on that !

(I didn't mentioned it but I'm using WSL)
