### ISSUE TITLE
Git action buttons doesn't react to git action complete

### ISSUE THREAD

**Issue by Legend-Master** [microsoft/vscode#221252]
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.91.0 (user setup)
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:52:22.949Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045
```

This is especially annoying when I go from a branch to main branch and do a pull and then try to delete the branch I was previously in

Steps to Reproduce:

1. Click `Pull` in the SCM panel's 3 dots menu
2. Open that menu again and wait for `Pull` to complete
3. Buttons are still disabled after `Pull` completed, needs to re-open the menu to click on those buttons

https://github.com/microsoft/vscode/assets/68118705/411cb1a8-0139-438d-8790-f4fdabce3aa8

**Comment by gjsjohnmurray** [comment]
It might not be possible for the enablement state of context menu items to be updated while the menu is open.

I suggest you watch the progress indicator on the view and only reopen the `... ` menu when the indicator disappears.

**Comment by lszomoru** [comment]
Adding @jrieken who should be able to confirm whether this is possible to implement.

**Comment by jrieken** [comment]
> Adding @jrieken who should be able to confirm whether this is possible to implement.

Only half possible... Custom menus (as shown above) could react to menu update and could update/rerender (I'll leave it to @sbatten for why they don't) but native electron menus (like we use form macOS and linux) cannot be updated. That's an unfortunate Electron limitation

**Comment by sbatten** [comment]
Custom menus attempt to mimic what we can do with native menus, nothing more.
