### ISSUE TITLE
Background colour contributions for some `testing` UI elements do not have any effect

### ISSUE THREAD

**Issue by robertrossmann** [microsoft/vscode#221264]
It looks like the background-related colour contribution points for `testing` UI elements do not have any effect. I tested the following ones:

```
testing.message.error.lineBackground
testing.messagePeekHeaderBackground
```

and I assume `testing.message.info.lineBackground` will also not work.

Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.91.0
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:54:18.541Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.91.0 Chrome/122.0.6261.156 Electron/29.4.0 Safari/537.36
```

Steps to Reproduce:

1. Set a colour for `testing.message.error.lineBackground`
2. Trigger a test failure
3. Observe the inline error decoration has no background colour

![testing UI](https://github.com/microsoft/vscode/assets/3058150/5cf97a95-f353-49c9-ae44-230f39bf80a6)

**Comment by connor4312** [comment]
`testing.messagePeekHeaderBackground` is used for peeking logged output messages, which are different than errors/failures. The failure will use `testing.peekHeaderBackground`.

`testing.message.error.lineBackground` was lost in refactoring, good catch
