### ISSUE TITLE
Integrated terminal loads old environment variables, not the current value in .env file

### ISSUE THREAD

**Issue by s01868** [microsoft/vscode#221271]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.0
- OS Version: Darwin arm64 23.5.0

Steps to Reproduce:

In our Remix project, we are using `dotenv` to load environment variables from the `.env` file. But if we were to log a process variable to the console:

1. when running the app through the VS Code integrated terminal, an old value will be logged
2. if we switch to another terminal, the correct value from the `.env` file will be logged

Similar issue were also reported at https://github.com/microsoft/vscode/issues/212606, but the issue was closed without conclusion.

**Comment by meganrogge** [comment]
We source the env of the terminal on startup of VS code. If you make a change, close VS Code, reopen it, and create a new terminal in VS Code, does it reflect that change?

**Comment by s01868** [comment]
Did restart VS Code, even restarted my laptop but the problem still persisted.
