### ISSUE TITLE
The horizontal scroll bar is somewhat hidden

### ISSUE THREAD

**Issue by TFrascaroli** [Microsoft/vscode#22126]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

The bar is not fully visible.

Steps to Reproduce:

1.Just open Visual Sutio Code, and open a file with long enough lines to allow for the horizontal bar to appear.
![image](https://cloud.githubusercontent.com/assets/9716061/23645748/e8861d66-030d-11e7-8a47-40e4f7b1d647.png)
![image](https://cloud.githubusercontent.com/assets/9716061/23645795/2810a0a0-030e-11e7-8bce-78893b778281.png)

**Comment by ramya-rao-a** [comment]
The bar does get a more solid color on hover.

**Comment by TFrascaroli** [comment]
It's not the color, it looks like the bar is narrower than its vertical
counterpart. Maybe it's my eyes playing tricks on me?

**Comment by stevencl** [comment]
Yes, the horizontal bar is not as tall as the vertical bar is wide. I am not sure why that is the case.

@bpasero @alexandrudima - do either of you know why this is?

**Comment by bpasero** [comment]
I have no clue, sorry.

**Comment by alexandrudima** [comment]
Yes, it is intentional that the horizontal scrollbar height !== vertical scrollbar width.

The vertical bar needs more space to show:
* git diff annotations
* find matches, highlights, etc.
* errors, warnings, etc.

**Comment by TFrascaroli** [comment]
Alright, sorry for the troubles. Great job guys!
