### ISSUE TITLE
VS Code - Typescript service died unexpectely 5 times in last 5 mins.

### ISSUE THREAD

**Issue by AAcoder** [Microsoft/vscode#22123]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|tslint|eg2|0.8.1|
|code-runner|formulahendry|0.6.12|
|Angular2|johnpapa|2.0.3|
|react-beautify|taichi|0.3.0|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Do you see a message about a missing `typescript/...` file? If so, you may be hitting #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds

If this does not sound correct, please set `"typescript.tsserver.trace": "verbose"` in your user settings, restart VSCode and reproduce the issue, and then share the `TypeScript` output in the output panel
