### ISSUE TITLE
error typescript service

### ISSUE THREAD

**Issue by advence-liz** [Microsoft/vscode#22129]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|angular1-code-snippets|alexandersage|0.0.3|
|vscode-eslint|dbaeumer|1.1.0|
|jquerysnippets|donjayamanne|0.0.1|
|latexcompile|mathiasfrohlich|0.7.0|
|csharp|ms-vscode|1.5.3|
|latex|ms-vscode|0.1.3|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Do you see a message about a missing `typescript/...` file? If so, you may be hitting #20496 in which an antivirus program is deleting our TypeScript implementation. See [this comment](https://github.com/Microsoft/vscode/issues/20496#issuecomment-279518845) for workarounds


If this does not sound correct, please set `"typescript.tsserver.trace": "verbose"` in your user settings, restart VSCode and reproduce the issue, and then share the `TypeScript` output in the output panel
