### ISSUE TITLE
Search's regex does not work when there is line break

### ISSUE THREAD

**Issue by Hasan-Mir** [microsoft/vscode#221280]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.0
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Write this text in a file:
```js
import {
    login, register
} from './api'
```
2. Go to vscode search section, enable the regex and write `import\s*\{[^}]*\bregister\b[^}]*\}`

I tried it in WebStorm and regex101.com and they are working.

![vscode regex](https://github.com/microsoft/vscode/assets/62181905/78a7234c-97b0-4045-b249-85ea1abc5af8)

**Comment by ArturoDent** [comment]
Because of the way vscode handles newlines in find/search regular expressions, you need to **explicitly** include a `\n` in the regex to signal vscode to start looking for newlines - `\s` is not sufficient.  There are a couple of things you could do to accomplish this:

    import[\s\n]*\{[^}]*\bregister\b[^}]*\}   // you see I added a `[\s\n]*`

    \n{0}import\s*\{[^}]*\bregister\b[^}]*\}  // tack on a `\n{0}` to the front

**Comment by andreamah** [comment]
> Because of the way vscode handles newlines in find/search regular expressions, you need to **explicitly** include a `\n` in the regex to signal vscode to start looking for newlines - `\s` is not sufficient. There are a couple of things you could do to accomplish this:
> 
> ```
> import[\s\n]*\{[^}]*\bregister\b[^}]*\}   // you see I added a `[\s\n]*`
> 
> \n{0}import\s*\{[^}]*\bregister\b[^}]*\}  // tack on a `\n{0}` to the front
> ```

This is correct ^.

 We are tracking this in https://github.com/microsoft/vscode/issues/75265.
/duplicate https://github.com/microsoft/vscode/issues/75265.
