### ISSUE TITLE
Git gutter indicators not appearing in some files.

### ISSUE THREAD

**Issue by MrSimmmons** [microsoft/vscode#221228]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

Version: 1.91.0 (Universal)
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:54:18.541Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

Steps to Reproduce:

1. Have a git repo open with no files modified
2. Modify a file
3. Note that the gutter indicators on the left side of the code editor next to the numbers no longer show

View in the code editor on an ~800 line file
![Screenshot 2024-07-09 at 12 04 20 PM](https://github.com/microsoft/vscode/assets/26075792/2c040d62-b115-443b-9f2c-8241c1656895)

View in the source control panel on an ~800 line file
![Screenshot 2024-07-09 at 12 03 34 PM](https://github.com/microsoft/vscode/assets/26075792/a06a36cf-7480-4e69-8547-bcac918762d1)

View in the code editor on a smaller file (~80 line file)
![Screenshot 2024-07-09 at 12 18 46 PM](https://github.com/microsoft/vscode/assets/26075792/327fd8c6-14d7-49c8-a0b9-cc6682f04b19)

No errors or relevant logs appear in the dev tools js console (screenshot taken from extensions disabled mode) 
![Screenshot 2024-07-09 at 12 30 39 PM](https://github.com/microsoft/vscode/assets/26075792/91cdc7d7-b28f-48de-8bff-c6db8dfdaead)

Whats weird is that this doesn't happen on all large files, only some. I did a little bit of digging around the HTML of the page, and the `div` that contains the number of the line is missing the child `div` which contains the classes `cldr dirty-diff-glyph dirty-diff-added` on the ~800 line file. Where as the ~80 line file contains that child `div`, thus rendering the green gutter indicator

Codebase is company owned so I cant share any files unfortunately, but I'm happy to help with any debugging. Just not sure where to begin 😅

**Comment by MrSimmmons** [comment]
Also worth noting that it works fine on other colleagues macs. Ive also tried doing an app restart, a computer restart & rolling  back multiple versions and the issue still occurs after trying all those.

**Comment by lszomoru** [comment]
@MrSimmmons, is there a chance that your setup contains any symbolic links on the path? 
Are you able to reproduce on files in a particular folder but not others? Thanks!

**Comment by MrSimmmons** [comment]
No symbolic links in that project, and has only happened on 1 particular file so far.

It is a rather large monorepo, though I don't see how that would affect things as all the other files I've opened so far work normally.

**Comment by alexr00** [comment]
I'm not sure what could be going on here. @MrSimmmons, do you have that specific file open twice in VS Code?
