### ISSUE TITLE
Auto-indenting fails when the line contains '$var = $(something)' [using PowerShell]

### ISSUE THREAD

**Issue by supergoatie** [Microsoft/vscode#22125]
- VSCode Version: 1.10.1
- OS Version: Windows 7
- PowerShell plug-in 0.9.0 (if that helps at all)

Steps to Reproduce:
1. Turn on editor.formatOnSave setting
2. Code language - PowerShell
3. If I have code that has a line that has a variable configured with "$foo = $(3+5)", the indenting of the subsequent line is not correct, it falls back one indentation level, and it shouldn't as follows.

Example 1 - both lines should be at the same indentation level:

    $foo = $(3+5)
$bar = "hello world"

or

Example 1 - All three lines should be at the same indentation level:

    $bar = "world"
    $foobar = $("hello " + $bar)
Write-Warning ($foobar)

The subsequent line after the code that contains '= $(' does a negative indention whereas it should remain on the same indentation level.

Thanks,
Steve.

**Comment by rebornix** [comment]
It looks like an issue with the extension you use, please file issues against them :)

**Comment by supergoatie** [comment]
Thanks rebonix,
I've tested it again with a later version of the PowerShell Extension (0.12.2) and it's formatting correctly now.
