### ISSUE TITLE
Latest debian version of VS Code unresponsive to mouse clicks

### ISSUE THREAD

**Issue by Noah-Nelson** [microsoft/vscode#221298]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.0
- OS Version: Debian GNU/Linux 12 (bookworm), on chromeos v 126.0.6478.132

Steps to Reproduce:

1. Download VS Code debian v 1.91.0 & install
2. Launch VS Code
3. Attempt to click anything (menu options, side panel buttons, recent shortcuts, etc. -- none of it works)

Note: keyboard shortcuts appear to work. Mouse works in all other applications.

**Comment by samlarsen1** [comment]
I have the same problem

VS Code Version: 1.91.1
OS Version: Debian GNU/Linux 11 (bullseye), on chormeos

**Comment by Noah-Nelson** [comment]
As a late update, this issue appeared to have resolved itself without me updating.

At the time, I had tried uninstalling and reinstalling VS Code a few times, to no avail. But after a day or two it started working, without any VS Code or Chromeos updates. Not sure how that could be, but there you have it.

**Comment by bhavyaus** [comment]
closing as no repro since the issue appears to be fixed.

**Comment by neuromagus** [comment]
Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.9.7+bpo-amd64 (Debian 12)

>closing as no repro since the issue appears to be fixed.

nope... If mouse right click on folder in Explorer (for adding new or adding file etc), autopressed menu items ("Cut or "Find in folder") under the mouse cursor...
