### ISSUE TITLE
How exactly do I download a repository if there's no "initialize" button? 

### ISSUE THREAD

**Issue by leocrespo** [Microsoft/vscode#2213]
Hi, 

Sorry for the newbie question. I'm following this tutorial (http://michaelcrump.net/using-github-with-visualstudio-code/) and others too but all of them assume that there is a "Initialize" button on my Visual Studio Code. 
http://michaelcrump.net/files/addtogitvscode.jpg

However mine doesn't have any of this. http://cl.ly/3q1m3I0Z2K2T

How exactly do I download I get started with a repository? How do I download and initialize it if there's no initialize button? 

Thanks in advance and sorry for the newbie question. 

Regards,

Leo

**Comment by joaomoreno** [comment]
Use the `File > Open...` action.

![image](https://cloud.githubusercontent.com/assets/22350/12548988/66d05f14-c35a-11e5-99bc-563e7c4b788c.png)
