### ISSUE TITLE
Close group tabs button includes the active tab in the close action

### ISSUE THREAD

**Issue by g-ongenae** [microsoft/vscode#221340]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91.0
- Validation: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
- Date: 2024-07-01T18:53:23.353Z
- Electron: 29.4.0
- ElectronBuildId: 9728852
- Chromium: 122.0.6261.156
- Node.js: 20.9.0
- V8: 12.2.281.27-electron.0
- OS Version: Darwin arm64 22.6.0

Steps to Reproduce:

1. Open multiple tabs
2. Keep a tab you don't want to close active (different group)
3. Click to close a different group (from the one with the active tab)

Demo:

https://github.com/microsoft/vscode/assets/9453090/2a41c06a-2b96-426b-b99d-9a09e2b0a715

**Comment by benibenj** [comment]
Thanks for reporting, I've fixed this last week with the editor commands debt work
