### ISSUE TITLE
Lock a tab feature

### ISSUE THREAD

**Issue by Ri-2020** [microsoft/vscode#221344]
we all have some configuration files in the development of any application if there is a feature to lock the tab for example i have settings.dart file in my development I lock that tab and now I can always find that tab opened and need not to search that file again

**Comment by gjsjohnmurray** [comment]
You can right-click on its tab and choose `Pin`

**Comment by Ri-2020** [comment]
ohh thanks,wasn't visible unitil you told.... happens sometimes
