### ISSUE TITLE
"Rename Symbol" should not rename shorthand property names

### ISSUE THREAD

**Issue by geon** [Microsoft/vscode#22133]
- VSCode Version: 1.10.1
- OS Version: macOS 10.12.3 

Steps to Reproduce:

1.

    const foo = 'foo';
    const bar = {foo};

2. Try renaming the symbol `foo`. It will change the property name in the object `bar` as well, which is semantically different, not just cosmetically.

Result:

    const newName = 'foo';
    const bar = {newName};

Expected result

    const newName = 'foo';
    const bar = {foo: newName};

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14514
