### ISSUE TITLE
opening folders from CLI tries to open a file

### ISSUE THREAD

**Issue by FernandoMiguel** [microsoft/vscode#221382]
Type: <b>Bug</b>

On Mac, try to open a folder in vscode , from iterm2
$ code -n work

This opens a non-existing file, instead of the folder in the SCM

VS Code version: Code - Insiders 1.92.0-insider (8703a11164db333db471576d38ddc143d6ad7ead, 2024-07-10T08:26:11.347Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (0.16GB free)|
|Process Argv|-n work/di/SRE/sre-dev-consul-kv work/di/SRE/sre-dev-nomad-scheduler|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
inline-hasher|ale|1.1.0
spellright|ban|3.0.132
iam-policy|bin|0.0.1
copilot|Git|1.211.978
copilot-chat|Git|0.18.2024071001
terraform|has|2.32.2024070910
vscode-kubernetes-tools|ms-|1.3.16
indent-rainbow|ode|8.3.1
ytt-lint|phi|0.3.1
vscode-yaml|red|1.15.0
vscode-gitweblinks|red|2.11.0
iam-legend|Seb|1.1.49
kubernator-vscode|smp|1.0.0
code-spell-checker|str|3.0.1
shellcheck|tim|0.37.1
sort-lines|Tyr|1.11.0
errorlens|use|3.20.0
vscode-icons|vsc|12.8.0

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
I ran into this as well today

**Comment by connor4312** [comment]
Probably https://github.com/microsoft/vscode/pull/221373?

**Comment by deepak1556** [comment]
/fixedWith https://github.com/microsoft/vscode/commit/0dffaf0a35c044ecdff3e60deedf702809cfc660
