### ISSUE TITLE
User activity api regression on stable

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#221396]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: stable/from sources
- OS Version: 

Regression from https://github.com/microsoft/vscode/pull/214264

@connor4312 This broke user activity api, with this any extension that runs some background task using  `showProgress`  will make the api report as `active` which is not desired.

In my case:
- I use the api to send heartbeat events to backend
- GHPR extension runs some background git commands periodically
- Git extension calls the showProgress api which in turn makes user activity api report as `active`

Would be good to fix it for recovery release 🙏

**Comment by connor4312** [comment]
Thanks for the issue, I made a PR that should hopefully mitigate the problem for you. Please let me know how it goes on the next Insiders.

**Comment by amunger** [comment]
this was fixed long enough ago that I think we can just mark as verified
