### ISSUE TITLE
After the update the VS Code stopped running

### ISSUE THREAD

**Issue by iamrealmarsel** [microsoft/vscode#221334]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91.0
- OS Version: macOS 10.15.7

Hi!

A notification appeared that VS Code needed to be updated, I updated it, and now VS Code does not start. I downloaded the new version from your site, but it still won't start.

**Comment by ischintsan** [comment]
I have the same problem as you

**Comment by artpechenin** [comment]
Similar situation. How to fix it?

**Comment by iamrealmarsel** [comment]
> Sorry for the breakage, I am currently investigating this issue. There has not been any obvious runtime changes in this update that could trigger this.
> 
> Please download https://code.visualstudio.com/updates/v1_90 and disable updates via `"update.mode": "none"` till this issue is resolved.

_Originally posted by @deepak1556 in https://github.com/microsoft/vscode/issues/219893#issuecomment-2207559915_

**Comment by deepak1556** [comment]
The issue has been addressed in [insiders](https://code.visualstudio.com/insiders) and will be available in the recovery release `1.91.1` this week for which you can track progress at https://github.com/microsoft/vscode/issues/221133

Merging to https://github.com/microsoft/vscode/issues/219893

**Comment by artpechenin** [comment]
> **Временное решение:**
> 
> > Извините за поломку, я сейчас изучаю эту проблему. В этом обновлении не было никаких очевидных изменений в среде выполнения, которые могли бы вызвать это.
> > Пожалуйста, загрузите https://code.visualstudio.com/updates/v1_90 и отключите обновления, `"update.mode": "none"`пока эта проблема не будет решена.
> 
> _Первоначально опубликовано@deepak1556в [#219893 (комментарий)](https://github.com/microsoft/vscode/issues/219893#issuecomment-2207559915)_

Excellent! Everything worked! Thank you! 🙏
