### ISSUE TITLE
HoverWidget - codicons are not vertically aligned

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#221359]
Steps to Reproduce:

1.  Open a folder/workspace that contains a git repository
2. Open a file, make some changes, and create a commit
3. In the Source Control view hover over a particular commit in the incoming/outgoing section (notice that the codicons are not aligned)

![Image](https://github.com/user-attachments/assets/2bd7b8f8-ad40-414d-bb46-77745716f01b)

**Comment by lszomoru** [comment]
Fixed with https://github.com/microsoft/vscode/pull/221251

**Comment by andreamah** [comment]
I see this is styled differently now:


![Image](https://github.com/user-attachments/assets/aed6444c-10a7-46e3-9e21-e3989faa0476)

I assume that this alignment isn't needed anymore.

**Comment by lszomoru** [comment]
The layout of the hover changed, but the alignment fix can be observed with the "account" and "history" icons.
