### ISSUE TITLE
Files no longer refresh on the IDE when they're changed on the filesystem

### ISSUE THREAD

**Issue by divmgl** [microsoft/vscode#221378]
Type: <b>Bug</b>

1. Open a file.
2. Change the file externally. I'm using Git to do this.

VSCode does not refresh the file even though the file has no changes.

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:53:23.353Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 7, 8|
|Memory (System)|32.00GB (0.69GB free)|
|Process Argv|--crash-reporter-id b59d9bea-6641-4c84-b21a-98b44bb2c734|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
codesnap|adp|1.3.4
codewhisperer-for-command-line-companion|ama|0.1.0
vscode-color|ans|0.4.5
astro-vscode|ast|2.11.0
vscode-tailwindcss|bra|0.12.5
vscode-postgres|cko|1.4.3
vscode-eslint|dba|3.0.10
gitlens|eam|15.1.0
prettier-vscode|esb|10.4.0
copilot|Git|1.211.0
copilot-chat|Git|0.17.0
go|gol|0.41.4
terraform|has|2.31.0
prettier-sql-vscode|inf|1.6.0
rainbow-csv|mec|3.12.0
remote-containers|ms-|0.375.1
makefile-tools|ms-|0.9.10
vscode-speech|ms-|0.10.0
prisma|Pri|5.16.1
vscode-todo-highlight|way|1.0.5

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31082724

```

</details>

**Comment by divmgl** [comment]
This latest version of VSCode has several big regressions. Would you happen to have a link so I can go back to the May update?

**Comment by dbaeumer** [comment]
How to download previous versions is decribed here: https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions

**Comment by claycoleman** [comment]
the impacts of this on source control per #222098 (if they are linked) is rather painful, really appreciate your efforts here 🙏

**Comment by bpasero** [comment]
@divmgl do you have reliable steps to reproduce?

**Comment by bpasero** [comment]
Does it help to configure `typescript.tsserver.experimental.useVsCodeWatcher` to `false` in settings?
