### ISSUE TITLE
Ctrl+tab shows show in search panel button

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#221369]
![image](https://github.com/user-attachments/assets/2b02d270-88b5-44f9-883c-18fc268694d1)
![image](https://github.com/user-attachments/assets/9106a67c-8ebb-473c-b602-506b5029b8bf)

**Comment by andreamah** [comment]
What's the expected behavior for ctrl+tab?

**Comment by TylerLeonhardt** [comment]
Already fixed in https://github.com/microsoft/vscode/pull/221403
