### ISSUE TITLE
Launching Debug Configuration Does Not Alert of Errors

### ISSUE THREAD

**Issue by noeda-lam** [microsoft/vscode#221394]
Type: <b>Bug</b>

I am experiencing an issue where when I run one of my build and debug configurations on VS Code for Windows 10, Code no longer displays the message the warning that says "Errors exist after running preLaunchTask".

I am not exactly sure if this is a VS Code issue or the C++ extension.

The bug is recent, up until ~1 month ago I had no issues. I'm not certain if the issue is due to the problem matcher.

My build system is a bit unusual. I use MSVC 2017, Intel C++ compiler 2018.4, Incredibuild, & scons to build. I have a default build task set up to call my two line build script. The script activates my mamba environment then calls Incredibuild with my scons command.

Describing reproduction instructions is difficult, as the bug is not consistent. On ocassion, the build errors warning will show up after my first build, then never again. Unfortunately , I found this bug on my work machine, so I can not share my code.

I thought the issue may be with my `problemMatcher` or tasks.json file. I tried deleting it and recreating it. Then, I tried a variety of `problemMatcher` entries, none of which solved the problem.

I verified the issue isn't caused by Incredibuild. If I change my bat script to call scons directly, the issue persists. Additionally, this used to work.

I tried adding `"problems.showCurrentInStatus": true` to my user `settings.json` file and that did not seem to make an difference. Additionally, I tried `"debug.onTaskErrors": "showErrors"` to my settings. This did not work, however, it led me to a work around.

The workaround is not consistent. When I add `"debug.onTaskErrors": "showErrors"` to my user settings file, save it, comment out that line, then save again, & finally run a build I get the expected pop up. After clicking "Show Errors" I can see the expected build errors.

The steps I have taken are as follows:
- Add an error to your C++ code
- Create a default build task to call my `vsbuild.bat` file
- Create a C++ launch task with a `"preLaunchTask"` the calls my default build task
- Press F5 or Run and Debug
- Observe the exe can't be found launch error

Desired behavior
- Add an error to your C++ code
- Create a default build task to call my `vsbuild.bat` file
- Create a C++ launch task with a `"preLaunchTask"` the calls my default build task
- Press F5 or Run and Debug
- Observe the "Errors Exist After running preLaunchTask" pop up.

Example of my tasks.json:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "cppbuild",
            "label": "Build App",
            "command": "vsbuild.bat",
            "args": [],
            "options": {
                "cwd": "<path to my src>"
            },
            "problemMatcher": [
                "$msCompile",
                {
                    "owner": "cpp",
                    "fileLocation": "autoDetect",
                    "pattern": {
                        "regexp": "^(.*)\\((\\d+)\\): (warning|error):(.*)$",
                        "file": 1,
                        "line": 2,
                        "severity": 3,
                        "message": 4
                    }
                },
                {
                    "owner": "cpp",
                    "fileLocation": "autoDetect",
                    "pattern": {
                        "regexp": "^(.*)\\((\\d+)\\): (warning|error) #(\\d+):(.*)$",
                        "file": 1,
                        "line": 2,
                        "severity": 3,
                        "message": 5
                    }
                }
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Builds executables"
        }
    ]
}
```

My build script:
```
call mamba activate <my env>
call buildconsole /command="scons -j 100"
```

Example of my launch.json:
```
"configurations": [
        {
            "name": "B&L app",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "<path to my exe>",
            "args": [],
            "stopAtEntry": false,
            "cwd": "<path to my src>",
            "console": "internalConsole",
            "requireExactSource": false,
            "preLaunchTask": "Build App"
        },
```

This is my first bug report, please let me know if you need me to provide more information. I'll do my best to answer any questions.

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|79.73GB (65.37GB free)|
|Process Argv|--crash-reporter-id 114b958b-07f6-47fb-baf8-47ad176e07e5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
copilot|Git|1.211.0
copilot-chat|Git|0.17.0
remotehub|Git|0.62.0
vsc-python-indent|Kev|1.18.0
vscode-clangd|llv|0.1.28
hg|mrc|1.9.0
vscode-docker|ms-|1.29.1
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.6.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.375.1
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
azure-repos|ms-|0.38.0
cmake-tools|ms-|1.18.42
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.2
vsliveshare|ms-|1.0.5932
autodocstring|njp|0.6.1
code-spell-checker|str|3.0.1
qtvsctools|ton|0.11.0
cmake|twx|0.0.17
win-ca|uko|3.5.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-icons|vsc|12.8.0
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31082724
4930e709:31092288

```

</details>

**Comment by roblourens** [comment]
When this happens, do the problems show up? Meaning, do you see errors in the Problems panel? 

![Image](https://github.com/user-attachments/assets/91b3ca7b-cc1d-49ef-b9a9-76e1c96dc91a)

**Comment by noeda-lam** [comment]
Hello,
I do see errors in the problems pane; however, the errors appear to be from clangd rather than build errors.

As mentioned previously, the bug shows up inconsistently. At the time of writing, I see two error types in my problems pane: `cpp` and `clang`. When the problem matcher is ignored / an "old" build is launched regardless, I only see `clang` errors in the problems tab.

**Comment by roblourens** [comment]
If you don't see the errors from the task showing up in the problems pane, then probably there's an issue with the problemMatcher or the task that ran, and the debugger won't pick them up.

**Comment by noeda-lam** [comment]
I believe the bug is related to the problem matcher itself. My `problemMatcher` entry and build task have not changed in over a year. While this bug only appeared within the last couple of months. The fact that the behavior is inconsistent also leads me to think this is a bug and not a configuration problem.
Here's my `problemMatcher`
```
"problemMatcher": [
                "$msCompile",
                {
                    "owner": "cpp",
                    "fileLocation": "autoDetect",
                    "pattern": {
                        "regexp": "^(.*)\\((\\d+)\\): (warning|error):(.*)$",
                        "file": 1,
                        "line": 2,
                        "severity": 3,
                        "message": 4
                    }
                },
                {
                    "owner": "cpp",
                    "fileLocation": "autoDetect",
                    "pattern": {
                        "regexp": "^(.*)\\((\\d+)\\): (warning|error) #(\\d+):(.*)$",
                        "file": 1,
                        "line": 2,
                        "severity": 3,
                        "message": 5
                    }
                }
            ],
```

**Comment by roblourens** [comment]
Can you give an example of the task output that the problemMatcher should match, but isn't?

**Comment by noeda-lam** [comment]
Hello,
I apologize for the delay, I missed the previous comment.

Here's an example of a missed semicolon error not being detected.
This is the output in the VS Code Terminal window. I've modified the output to remove file names.

```
scons: Building targets ...
Compiling (NT40_x64,devoptimize,native)
File.cpp
Path\File.cpp(1215): error C2059: syntax error: '}'
scons: *** [Path\File.obj] Error 2
scons: building terminated because of errors.
```

The error does not appear as an error in the Problem's pane as a cpp error.

**Comment by noeda-lam** [comment]
Hello,
I hope you devs are doing well. I'm going to close the issue as I found a workaround.

For those with this issue in the future, I found changing my tasks.json `"type"` to `"shell"` from `"cppbuild"` seems to have fixed the issue.
The project I am building using the tool scons. Up until earlier this year, using `"type": "cppbuild"` worked fine. I'm not sure what changed.

**Comment by noeda-lam** [comment]
Hello,
I hope you devs are doing well. I'm going to close the issue as I found a workaround.

For those with this issue in the future, I found changing my tasks.json `"type"` to `"shell"` from `"cppbuild"` seems to have fixed the issue.
The project I am building using the tool scons. Up until earlier this year, using `"type": "cppbuild"` worked fine. I'm not sure what changed.
