### ISSUE TITLE
Layout controls never shown when `Editor Actions Position` set to `Title Bar`

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#221383]
When `Editor Actions Position` set to `Title Bar`, the layout controls never appear and the `Layout Controls` toggle is ignored:

![Image](https://github.com/user-attachments/assets/578cabcf-f968-406f-89ed-f66187aee63f)

**Comment by mwerle** [comment]
How about not hiding them when there's enough space in the title bar?  It just took me several days to figure out why the controls were hidden on one machine, but visible on another.

Failing that, what is the overflow menu and how do we access it/show it? (Google failed to give an answer)

**Comment by benibenj** [comment]
The overflow menu are the 3 dots on the right

**Comment by benibenj** [comment]
Closing as this will be solved when the layout actions will be moved to the respective corners
