### ISSUE TITLE
Shortcut to Reveal file in sidebar

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#22130]
Hi,

- VSCode Version: 1.10.1
- OS Version: macOS Sierra

I'm not able to set a keyboard shortcut to reveal a file in a sidebar. It is possible only for Reveal file in a Finder.

How can I achieve that? I don't want to have "auto reveal" option set to true, but writing "cmd+shift+p reve Down Down Enter" is a bit lengthy.

Maybe making this action public could help? `"_workbench.action.files.revealInExplorer"` :) Not sure ;)

Thanks for your suggestions.

**Comment by obrejla** [comment]
Well, from code base I found out that the action could be invoked also from editor tab context menu :+1: But having a shortcut could be also great ;) Thanks.

**Comment by ramya-rao-a** [comment]
You can assign your own keyboard shortcut to the command `workbench.files.action.showActiveFileInExplorer`  to achieve this

**Comment by obrejla** [comment]
Aaaaha. Didn't find that command. Thanks for your response.

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
