### ISSUE TITLE
Terminal content is showing at fixed height after word wrap using Alt + z

### ISSUE THREAD

**Issue by riteshOodles** [microsoft/vscode#221348]
Type: <b>Bug</b>

step 1 - Run any command or project whose lines does'nt fit in single line
step 2 - Your terminal can be full sized or small size does'nt matter
step 3- Presss Alt + z to wrap line in terminal
Step 4 - Resize your terminal window

Example - 
        If initially terminal window height is 100px from the bottom then  word wrap using Alt + z and after that increase or discrease the size of terminal window. You will find that content is still showing in 100px of height

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:41.959Z)
OS version: Linux x64 5.15.0-113-generic
Modes:

**Comment by riteshOodles** [comment]
![Screenshot from 2024-07-10 17-00-42](https://github.com/microsoft/vscode/assets/168412241/744fa7e9-369b-42d7-aaa1-e0f11066e0cf)

**Comment by riteshOodles** [comment]
![Uploading Screenshot from 2024-07-10 17-15-21.png…]()

**Comment by riteshOodles** [comment]
![Screenshot from 2024-07-10 17-15-21](https://github.com/microsoft/vscode/assets/168412241/7bba5baa-2b3f-4c84-9026-b055efd94bdf)

**Comment by meganrogge** [comment]
@riteshrhkr there is not

**Comment by riteshrhkr** [comment]
@meganrogge Can you make it happen like Eclipse 
Please 🥺

**Comment by Tyriar** [comment]
@riteshrhkr i haven't seen it in eclipse but I'm guessing they're using the old console api on windows which isn't really compatible with the pty based system that we use.

**Comment by roblourens** [comment]
Works, but I never see a horizontal scrollbar with word wrap disabled, should I expect to? I see it in the screenshot above.
