### ISSUE TITLE
Action button in quick input menu is not aligned 

### ISSUE THREAD

**Issue by jmg-duarte** [microsoft/vscode#221335]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91.0
- OS Version: MacOS Sonoma 14.5

Steps to Reproduce:

1. `Ctrl+R`
2. Hover the action button
3. See everything disaligned 

<img width="46" alt="Screenshot 2024-07-10 at 09 48 44" src="https://github.com/microsoft/vscode/assets/15343819/82f7899b-7545-45cc-9f7d-7471581f3495">

Bigger and more demonstrative example
<img width="86" alt="Screenshot 2024-07-10 at 09 52 00" src="https://github.com/microsoft/vscode/assets/15343819/b1da444e-795f-4bcf-9b8b-faad4d1b789a">

**Comment by tomasalagoa** [comment]
I seem to have the same issue on Windows 11, though in my case I cannot reproduce the cogwheel problem.

VS Code Version: 1.91.1
OS Version: Windows_NT x64 10.0.22621

![Misaligned](https://github.com/user-attachments/assets/69935f81-3d78-434a-8b82-87d92aae8dc3)
