### ISSUE TITLE
`getTerminalActionBarArgs` called twice

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#221377]
I'm not sure if that's an oversight, but `getTerminalActionBarArgs` is called twice.

https://github.com/microsoft/vscode/blob/6f2f74c6b21ac220f644509145e729a0dd78dd76/src/vs/workbench/contrib/terminal/browser/terminalView.ts#L276

and then again in

https://github.com/microsoft/vscode/blob/6f2f74c6b21ac220f644509145e729a0dd78dd76/src/vs/workbench/contrib/terminal/browser/terminalView.ts#L280

**Comment by sandy081** [comment]
Verified via code review
