### ISSUE TITLE
Allow Visual Studio Code to be installed for System via Winget

### ISSUE THREAD

**Issue by ward-horsfall** [microsoft/vscode#221318]
Hi,

Allow Visual Studio code to be installed as a system type installation. (C:\Program Files\Microsoft VS Code)

This option is not available via the Winget method of installation.

Thanks
Ward

**Comment by o-l-a-v** [comment]
You can install for all users / system context with WinGet, but user context is the default.

Here's the latest manifest:

* <https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/VisualStudioCode/1.91.0/Microsoft.VisualStudioCode.installer.yaml>

Heres doc on `winget install`, with the `--scope` switch:

* <https://learn.microsoft.com/en-us/windows/package-manager/winget/install>

**Comment by rzhao271** [comment]
Closing as *question. Let me know if you still need help, Ward.
