### ISSUE TITLE
Polish affordance to maximize panel

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#22135]
1. Add a default keybinding
2. Add an icon in the panel header

Currently there is only the action `View: Toggle Maximized Panel` in the command palette

**Comment by isidorn** [comment]
1. I am planning to add keybinding in the likes of `cmd + k p`, or `cmd + k m`, both of these are free but I hit this issue https://github.com/Microsoft/vscode/issues/22211
2. I plan to add an icon left of the close icon to all panels. Searched thorugh VS icons and I think we could use the following two (note that there are two states, so the icon would toggle)

![expand_16x](https://cloud.githubusercontent.com/assets/1926584/23702357/2a400a8a-03fb-11e7-8bac-84b250f70fea.png)
![collapse_16x](https://cloud.githubusercontent.com/assets/1926584/23702354/29079a84-03fb-11e7-8f22-81901af92685.png)

These icons are currently in the VS style, I tried converting them to VS Code sytle icons but failed using @chryw utils methods [here](https://github.com/chryw/iconutil/blob/master/gulpfile.js#L105). The scripts ask me for input and output for which I give absolute paths on my mac but this produces no effect. What am I doing wrong here?

The downside of these icons is that the plus could be confused with the plus to add a terminal.
An alternative set of icons could be the win native ones to maximize / restore window position. However I could not find those in the Visual Studio icon repository

ping @bpasero @Tyriar @chrisdias @stevencl for feedback

**Comment by bpasero** [comment]
Sorry, but these icons do not imply to me a maximize/minimize behaviour at all. They look like icons used for trees to expand/collapse. Can we find something that is more typical, e.g. for window management where you have this typically:

![image](https://cloud.githubusercontent.com/assets/900690/23706938/948d9514-0410-11e7-846d-2b54109e606d.png)

**Comment by isidorn** [comment]
Yeah that idea I describe in my comment also in the last paragraph.
And I agree that solution would be the most intuitive, however could not find anything like that on the vscode icons site so we might need custom icons.

**Comment by stevencl** [comment]
Visual Studio uses the following when in maximised mode (minimise, restore to previous size, close)

![image](https://cloud.githubusercontent.com/assets/1704059/23708179/fa090742-040c-11e7-8df2-6ab2456f0a9e.png)

And then these when not in maximised mode: (minimise, maximise, close)
![image](https://cloud.githubusercontent.com/assets/1704059/23708194/0bee7226-040d-11e7-9f02-e7d7e761168e.png)

I imagine that Christy could get these icons for us?

**Comment by bpasero** [comment]
Do we want all three, I wonder. We already have actions there and would probably end up with more than 3...

**Comment by bpasero** [comment]
Ah ok I was thinking that minimize would put the panel into the minimal height it can have instead of closing.

**Comment by Tyriar** [comment]
Don't use `cmd+k p`, the `ctrl` variant is copy active file path on Linux  and Windows, which I use :smile: 

```js
{ "key": "ctrl+k p", "command": "workbench.action.files.copyPathOfActiveFile" }
```

The VS icons are a much better choice than `-`/`+`. Another option is to use a the old close button `v` for restore and invert it for maximise `^`.

If we need I can write some SVGs in the style of the VS restore/maximise icon.

**Comment by isidorn** [comment]
I actually like the idea of using `v` and `^` in this case. Though I still feel like those original icons we used might be a bit too heavy and we could experiment with making them just a bit lighter

**Comment by chryw** [comment]
I like ^ and v for expand/collapse a panel that's on the bottom. I can make the icons. Just want to double check (sorry not a frequent VS Code user), is the panel always docked to bottom?

BTW @isidorn the path didn't work probably because I used a dirty quick workaround to turn "\" into "/" for Windows' sake. You can get rid of the replace if you're already on unix environment.
 gulp.src([`${response.srcPath.replace('\\', '/') || 'src'}/**/*.svg`]) --> 
 gulp.src([`${response.srcPath || 'src'}/**/*.svg`])

**Comment by Tyriar** [comment]
@chryw the panel is always docked to the bottom, however that may change in the coming months. If we did go with `^`/`v` I expect we would rotate the icons 90° when the panel is vertical.

**Comment by isidorn** [comment]
@chryw I agree with @Tyriar point about possibly rotating. So let's go ahead and create those icons. Keep in mind that we previously already had a `v` icon, but it was too thick and did not fit well with the rest of the icons used in the title bar imho. So we could use something similar but I would prefer if it fits a bit better with the following

![screen shot 2017-03-10 at 09 25 41](https://cloud.githubusercontent.com/assets/1926584/23787712/9144569a-0573-11e7-8283-b30a8dfa948c.png)
![screen shot 2017-03-10 at 09 25 46](https://cloud.githubusercontent.com/assets/1926584/23787711/9144369c-0573-11e7-8a97-ce0ca2b3ef1a.png)
![screen shot 2017-03-10 at 09 25 50](https://cloud.githubusercontent.com/assets/1926584/23787713/9144d99e-0573-11e7-9f0d-af28f62c4320.png)

**Comment by chryw** [comment]
@isidorn 
We have 2 sets of chevron icons. Do you think any of these works for the terminal panel?
![image](https://cloud.githubusercontent.com/assets/7075677/23809142/648c4000-0581-11e7-93d5-c7b4ee9e2bdb.png)
[945738_github_VSCodeTerminalExpandCollapse_Update1.zip](https://github.com/Microsoft/vscode/files/834905/945738_github_VSCodeTerminalExpandCollapse_Update1.zip)

**Comment by Tyriar** [comment]
@chryw Maybe the second one's size with the first one's weight?

![image](https://cloud.githubusercontent.com/assets/2193314/23809923/4fefdf78-0584-11e7-96aa-4f5e0cdf0779.png)

![image](https://cloud.githubusercontent.com/assets/2193314/23809937/616b1ccc-0584-11e7-8a3d-ad19cefb7bbd.png)

---

For reference here's a screenshot from an older version with the older icon:

![image](https://cloud.githubusercontent.com/assets/2193314/23810008/aa1400e2-0584-11e7-93cf-937224878aba.png)

**Comment by chryw** [comment]
Let's try these -
[945738_github_VSCodeTerminalExpandCollapse_Update2.zip](https://github.com/Microsoft/vscode/files/835157/945738_github_VSCodeTerminalExpandCollapse_Update2.zip)

**Comment by isidorn** [comment]
After discussing with @Tyriar we have agreed that no default keybinding is necessery especially since now the action is more visible.
@chryw thanks a lot for the icons, these work for me

![panel](https://cloud.githubusercontent.com/assets/1926584/23896104/71796a66-08a8-11e7-8829-0206fc9c4147.gif)
