### ISSUE TITLE
Don't fire onDidEndTerminalShellExecution with exitCode undefined immediately after first onDidChangeTerminalShellIntegration

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#221399]
I think what is causing problems for @anthonykim1 is that calling `executeCommand` immediately after `onDidChangeTerminalShellIntegration` would fire multiple times and end up triggering an invalid `onDidEndTerminalShellExecution` with exitCode=undefined but the execution was set when it shouldn't have been. We should suppress this event if possible.

**Comment by Tyriar** [comment]
Can not reproduce this, maybe something was happening in the profile of the terminal that was launched?

**Comment by anthonykim1** [comment]
Not sure what has changed but I dont get the undefined exitCode like I demoed, but rather 0,1 depending on the actual result of executeCommand, which is great:

Code being used: 
```
        const myTerm = window.createTerminal();
        window.onDidChangeTerminalShellIntegration(async ({ terminal, shellIntegration }) => {
            if (terminal === myTerm) {
                const execution = shellIntegration.executeCommand('echo "Hello world"');
                
                window.onDidEndTerminalShellExecution((event) => {
                    if (event.execution === execution) {
                        console.log(`Command exited with code ${event.exitCode}`); 
                        traceLog(`HERE ${event.exitCode} HERE I AM WITH THE EXIT CODE`);

                    }
                });
            }
        });
```
