### ISSUE TITLE
VS Code editor not switching branches 

### ISSUE THREAD

**Issue by sahilambre** [microsoft/vscode#221313]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91.0
- OS Version: macOS 14.5

![Screenshot 2024-07-09 at 7 08 59 PM](https://github.com/microsoft/vscode/assets/59484827/656b4f8e-4b8b-4934-8b0b-4b7c0e940db8)

I have been facing this issue where, when I try to switch branches using my terminal, it does change but on my editor it still stays in the previous branch, and I have to change it manually by clicking the branch icon.

**Comment by lszomoru** [comment]
@sahilambre, are you able to consistently reproduce this as I am unable to reproduce this issue. Thanks!
