### ISSUE TITLE
Eating up all the available memory at startup (x64)

### ISSUE THREAD

**Issue by ababak** [microsoft/vscode#221325]
Type: <b>Bug</b>

Three latest releases are eating up all the available memory at startup. I have to install the VS Code 1.88.1 -- the latest working version.
It spawns an endless number of bash.exe instances until it fills up all the available memory.

The latest VS Code 1.91.0

![CleanShot 2024-07-10 at 09 50 31@2x](https://github.com/microsoft/vscode/assets/11334363/14871820-f547-42ee-b59c-74e25b2729c3)

Getting back to normal after quitting VS Code

![CleanShot 2024-07-10 at 09 51 00@2x](https://github.com/microsoft/vscode/assets/11334363/4f287037-becf-4e19-aa2a-0c0503dedddf)

The last working version 1.88.1

![CleanShot 2024-07-10 at 09 54 30@2x](https://github.com/microsoft/vscode/assets/11334363/15a00c65-dc9b-4fa5-bba4-ca6ef4fa8021)

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)

OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|

|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (53.58GB free)|
|Process Argv|--crash-reporter-id 358dba80-56fc-470c-833a-f2ad595e317d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|15.1.0
vscode-docker|ms-|1.29.1
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.6.0
python|ms-|2024.4.1
vscode-pylance|ms-|2024.7.1
remote-containers|ms-|0.375.1
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
color-highlight|nau|2.8.0
autodocstring|njp|0.6.1
psi-header|psi|1.23.0
sass-indented|syl|1.8.30

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
legacy_priority:31082724

```

</details>

**Comment by ababak** [comment]
The same happens if I am running VS Code  1.88.1 on Windows and VS Code 1.91.0 on my Mac and connect to that PC remotely.

![CleanShot 2024-07-10 at 10 07 35@2x](https://github.com/microsoft/vscode/assets/11334363/03b96f1d-0629-4e18-b0ea-8c2160b644f9)

After quitting VS Code on my mac:

![CleanShot 2024-07-10 at 10 08 09@2x](https://github.com/microsoft/vscode/assets/11334363/ae869c7e-59bf-4289-975b-f2ded9a195bd)

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command on Command Palette {F1} to investigate whether the problem is being caused by one of your extensions.

If that doesn't identify an extension, use the command to use a temporary profile, in case one of your settings is the cause.

**Comment by ababak** [comment]
Here we go. It works fine until I click a Python file. Then I see a "reactivating terminals" status line and it starts to die.

**Comment by ababak** [comment]
Removing `shellIntegration-bash.sh` from `.bashrc` fixes the issue for now. Shell integration seems to work as well.
