### ISSUE TITLE
Allow to toggle status bar visibility in zen mode

### ISSUE THREAD

**Issue by km-tr** [Microsoft/vscode#22136]
- VSCode Version: 1.10.1 
- OS Version: Mac OSX 10.12.3

Steps to Reproduce:

1.  Switch to Zen mode
2. cmd+shift+p `View: Toggle Status Bar visibility`

**Comment by ramya-rao-a** [comment]
Toggle Side Bar works in Zen mode
Toggle Activity and Status bar doesnt work in Zen mode.

@bpasero was this intentional?

**Comment by isidorn** [comment]
Yes this is intentional, please add in your settings
`"zenMode.hideStatusBar": false`

**Comment by km-tr** [comment]
I know that setting.
I wanted to switch when I was in Zen mode.

**Comment by isidorn** [comment]
Not supporeted, reopening this as a feature request

**Comment by mryall-mawson** [comment]
For future visitors - this issue is actually fixed. The preference mentioned above is visible in the Settings panel.

Just search for Zen mode, and toggle the "hide status bar" setting off. You will need to close and open Zen mode again for it to take effect.
