### ISSUE TITLE
Breakpoints stuck under line numbers

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#221478]
I notice on the latest insiders now when I start and stop debugging the breakpoints are ending up below the line numbers instead of the gutter

![Image](https://github.com/user-attachments/assets/7d8c4836-b50c-4464-9ba2-9c85bac44861)

**Comment by connor4312** [comment]
@justschen this CSS rule applies to all glyph margin widgets, maybe you want to scope it more specifically for the lightbulb widget?

https://github.com/microsoft/vscode/blob/31f831310c643ae03c4b84124b5a427d0bed0483/src/vs/editor/contrib/codeAction/browser/lightBulbWidget.css#L48-L53
