### ISSUE TITLE
Remove loop cursor.ts -> viewImpl.ts -> cursor.ts in editorScroll

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#22147]
If we're at it, we might also want to write tests for this cursor command.

**Comment by alexandrudima** [comment]
The loop has two sources in `cursor.ts`:
* `_scrollByReveal` (cursor reveal range event)
* `_scrollUpOrDown` (cursor scroll request event)

@rebornix will look into removing `revealCursor` from the cursor scroll request event.

**Comment by johnfn** [comment]
While you guys are investigating these commands, would you consider fixing #16248 as well? It's another bug that seems related to these commands.

**Comment by alexandrudima** [comment]
@johnfn `select` can now be used for `editorScroll`. e.g. `keybindings.json` for https://github.com/VSCodeVim/Vim/issues/907:

```
    {
        "key": "ctrl+d",
        "command": "editorScroll",
        "when": "editorTextFocus",
        "args": {
            "to": "down",
            "by": "page",
            "revealCursor": true,
            "select": true
        }
    }
```

**Comment by TyOverby** [comment]
Any update on this?
