### ISSUE TITLE
Running a task does not show the build terminal if an editor terminal is open

### ISSUE THREAD

**Issue by stk-ableton** [microsoft/vscode#221464]
Type: <b>Bug</b>

Preparation: create the following `.vscode/tasks.json` file:
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Test",
      "type": "shell",
      "command": "sleep 10"
    }
  ]
}
```

1. In the terminals panel, create a new shell terminal
2. Drag it to the main editor area to make it a full-size terminal
3. Also open an editor tab (any file will do, including Command-N)
4. Make sure the panel is closed (press Command-J to close it if it is open)
5. Run the above task (e.g. with Command-P, then type `task Test`)

Expected: the panel opens and shows the running task
Actual: the editor terminal is brought to the front, and the panel stays closed

VS Code version: Code - Insiders 1.92.0-insider (c37f4a49e28831cec1aec1af0f626edaada1f7ce, 2024-07-11T05:03:58.450Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 5, 6|
|Memory (System)|32.00GB (3.14GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id 0af73232-1e42-4c3f-95c4-5b10f8deb228|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by tisilent** [comment]
```javascript copy
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Test",
      "type": "shell",
      "command": "sleep 10",
      "presentation": {
           "focus": true
       }
    }
  ]
}
```

In this scenario, focus also fails.

**Comment by stk-ableton** [comment]
I can confirm that #221684 fixes the problem for me. Thanks!
