### ISSUE TITLE
Do we have an action for minimap toggle?

### ISSUE THREAD

**Issue by mosajjal** [Microsoft/vscode#22148]
Hi. I've looked for minimap toggle action in keybindings and settings but I haven't found one. Is there a way to create a keyboard shortcut for toggling minimap?

Thank you

**Comment by mosajjal** [comment]
Also, it'd be a really neat idea to add a setting to toggle minimap automatically off when using split windows.

**Comment by obrejla** [comment]
And also have a possibility to switch it off for e.g. Output window.

**Comment by alexandrudima** [comment]
Duplicate of #21754

**Comment by hoovercj** [comment]
@mossajal  @obrejla I have published an extension that allows you to change any setting using keyboard commands. It is called [Settings Cycler](https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler) and it allows you to cycle through different values for a setting -- either to enable or disable a setting like the minimap or to cycle between values (for example, themes).

I hope it helps!
