### ISSUE TITLE
Debug toolbar misplaced after window resize, overlaps with window controls

### ISSUE THREAD

**Issue by hj5230** [microsoft/vscode#221438]
Type: <b>Bug</b>

After resizing, the debug toolbar is misplaced and overlaps with the window control buttons (close, minimize, maximize) at the top of the window. This makes it impossible to drag the toolbar to elsewhere

To reproduce:
1. open vscode
2. start debug
3. drag debug toolbar to top-left corner of the window
4. resize the window

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:53:23.353Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|. --crash-reporter-id 644bae35-eb75-4ff7-b9b6-cb01dd302987|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
vscode-eslint|dba|3.0.10
dprint|dpr|0.16.2
gitlens|eam|15.2.0
vscode-swan|efe|0.1.0
prettier-vscode|esb|10.4.0
codespaces|Git|1.17.1
copilot|Git|1.211.0
copilot-chat|Git|0.17.2024062801
go|gol|0.41.4
vscode-docker|ms-|1.29.1
remote-containers|ms-|0.375.1
svg-preview|Sim|2.8.3
vscode-wakatime|Wak|24.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
legacy_priority:31082724

```

</details>

**Comment by hj5230** [comment]
![image](https://github.com/microsoft/vscode/assets/98270829/4304fe60-a59f-466a-8cec-b33248d92002)

**Comment by hj5230** [comment]
![image](https://github.com/microsoft/vscode/assets/98270829/1ecfe570-0d08-4713-9c2b-84673e3515b8)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/221519
