### ISSUE TITLE
In-project custom extension in `.vscode/`

### ISSUE THREAD

**Issue by merrywhether** [microsoft/vscode#221406]
For large projects, it can make sense to have very customized VSCode extensions that are tightly coupled to specific patterns and policies within the codebase and aren't meaningfully generalizable. Currently there isn't a great solution for these use-cases:
- publishing to [public marketplace](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions) creates unnecessary clutter and isn't viable for anything "secret" to an org
- publishing to an [internal marketplace](https://github.com/coder/code-marketplace) creates extra a lot of extra overhead and cost to essentially boomerang an extension back its only relevant project
- distributing [`vsix` packages](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#packaging-extensions) is inelegant at scale and loses the ability to automatically propagate updates to users

Ideally a project could define its own extension(s) in the `.vscode/` directory and have that extension be automatically loaded and activated when working within its workspace. This would enable a much more streamlined project+extension integration and effortless propagation of updates to users. There are some edge-cases that would have to be considered, like how to trigger reloads of extension during forward development or branch switching and whether users can opt out of the extension.

This could also have the side-effect of making some initial extension development easier in general, as work could be started directly against the codebase that inspired the idea before being split out into its own standalone project.

**Comment by gjsjohnmurray** [comment]
The [Workspace Extensions](https://code.visualstudio.com/updates/v1_89#_local-workspace-extensions) feature arrived in April 2024

See #206783

**Comment by merrywhether** [comment]
Oh awesome. I didn't see it in the docs, but I'm hyped that it's already available. Thanks!
