### ISSUE TITLE
VSCode is autocorrecting rubocop issues on save, after latest version upgrade - Version: 1.91.1 (Universal)

### ISSUE THREAD

**Issue by kapso** [microsoft/vscode#221489]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 
Version: 1.91.1 (Universal)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:54.982Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
macOS 14.5

Steps to Reproduce:

1. I disabled the rubocop extension, but still seeing the issue
2. when rubocop ext is enabled, I unchecked the following, but the issue still exixts
<img width="550" alt="Screenshot 2024-07-11 at 10 52 56 AM" src="https://github.com/microsoft/vscode/assets/344198/960e9c79-6716-4b14-8460-7abfb80c7e9b">

**Comment by dbaeumer** [comment]
If it works with all extensions disabled you can use the guide here https://code.visualstudio.com/blogs/2021/02/16/extension-bisect to track down the extension that is causing this.
