### ISSUE TITLE
Crash/Glitch when connecting

### ISSUE THREAD

**Issue by sebastianrodriv** [microsoft/vscode#221452]
Type: <b>Performance Issue</b>

When I try to connect to a remote-ssh or open a new terminal, the google app starts glitching and then completely crashes. Everything is up to date to the latest versions. I've also unistalled and installed the app again and it's presenting the same issue

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:51:47.542Z)
OS version: Linux arm64 6.6.30-02725-g3e8c91b46252
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|unknown (8 x 0)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|6.48GB (5.75GB free)|
|Process Argv|--crash-reporter-id d8af242c-61ce-403c-b21e-dcd2136852cf|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|X-Generic|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   159	  2250	code main
    0	    40	  2253	   zygote
    1	   126	  2285	     gpu-process
    0	    40	  2254	   zygote
    0	     7	  2258	     zygote
    0	   219	  2316	window [1] (Welcome - Visual Studio Code)
    2	   100	  2638	window [2] (Issue Reporter)
    0	    60	  2291	   utility-network-service
    0	   106	  2356	shared-process
    0	     0	  2652	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  2653	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    86	  2357	fileWatcher [1]
    0	   113	  2377	extensionHost [1]
    0	    86	  2401	ptyHost
    0	     0	  2426	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31082723
pythonrstrctxtcf:31093870

```

</details>

**Comment by sebastianrodriv** [comment]
Any update please?

**Comment by joshspicer** [comment]
Hey there! Could you please clarify what you mean by 'Google app'?  Is that Google Chrome, or something else?

**Comment by sebastianrodriv** [comment]
Sure! I mean VsCode, the downloaded app, sorry fot the confusion. Now, the issue has changed a bit. I'm able now to open VsCode an connect to a remote-SSH server but, when I try to open a New Terminal, the whole app starts glitching and I'm not able to use it. Hope I'm able to make myself clear, thanks!

**Comment by joshspicer** [comment]
Thanks for clarifying.   Could you please check if this reproduces on the latest [Insiders](https://code.visualstudio.com/insiders/)?  

If possible, a video demonstrating the repro steps leading to the glitching that you're seeing may be helpful for us to triage this more effectively - thanks!

**Comment by sebastianrodriv** [comment]
Hi Josh,

Thanks for the response! Yes, it's happening also on insiders.

Attaching a video of both, have a great day.

BR,

Sebastián Rodríguez Rivera

**Comment by sebastianrodriv** [comment]
Here's the other one, cheers!

**Comment by joshspicer** [comment]
Thanks for the response, unfortunately I don't seem to be able to view any attachments

**Comment by sebastianrodriv** [comment]
Sorry about that, here they are, please let me know if you can see them

**Comment by joshspicer** [comment]
Unfortunately we're unable to see your attachment.  Please feel free to re-open after updating the issue with the information we've requested.  The URL to this issue is https://github.com/microsoft/vscode/issues/221452
