### ISSUE TITLE
How to reference the parent directory of the ${workspaceRoot} in tasks.json command?

### ISSUE THREAD

**Issue by stefan2410** [Microsoft/vscode#22140]
I have asked this question also in [stackoverflow](http://stackoverflow.com/q/42630755/2103764)
 
I have installed the node_modules in  the parent directory  of a  group of related JavaScript ES6  projects with common configuration.
Each one with its workspace, in VSCode.
I did not find yet a way to reference in the tasks.json a directory above ${workspaceRoot}.
But if I set in the tasks.json of every project, in the "command": the absolute windows path with the node_modules, everything works fine.
webpack, babel-loader, hot reload.
Is there a way from VSCode enviroment to set  the parent directory of the ${workspaceRoot} ?
 
thanks

**Comment by dbaeumer** [comment]
I would think ${workspaceRoot}/../dir should do the trick. t may be I misunderstand the questions since it looks to easy. If not, can you make an example with a directory structure.
