### ISSUE TITLE
The `Response` type should be disposable

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#221479]
With https://github.com/microsoft/vscode/commit/a5fa6ad389aface52d3a4983e44008ab1ba8bb36 the `Response`-type has gotten an emitter/event but it doesn't over dispose, meaning the emitter is leaked

**Comment by jrieken** [comment]
BTW I encountered this because I needed eventing for the `Request`-type. I ended up taking a different route in https://github.com/microsoft/vscode/pull/221482. Instead of having each element be a emitter the parent emit events "mentioning" them. That might be the better solution because it means less listening and less disposing overall.

**Comment by roblourens** [comment]
Was going to remove the Emitter from Response but it makes sense for it to fire for the async `progressTask`.
