### ISSUE TITLE
No way to edit "expandable" watch items

### ISSUE THREAD

**Issue by jjwhitney** [Microsoft/vscode#22146]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.9|;

---

Steps to Reproduce:

1. In debug mode, create an "expandable" watch item. ("['test', 'array']" in Python, for example.)
2. Double-click expands or collapses the item, leaving no way to edit it.

**Comment by isidorn** [comment]
Fixed in latest VSCode insiders version. Will be available in the next stable start of april.
