### ISSUE TITLE
Debug Session

### ISSUE THREAD

**Issue by l1qu1d** [microsoft/vscode#221484]
Type: <b>Bug</b>

Can't run debug session as it immediately closes with no error or warning. Debugging only works on the July 8th or eariler versions. I tried the last few releases after (including today's release) and still doesn't work and I have to downgrade back to the July 8th version.

I'm debugging a Flutter app and won't run debug on physical or virtual device.  

VS Code version: Code - Insiders 1.92.0-insider (c37f4a49e28831cec1aec1af0f626edaada1f7ce, 2024-07-11T05:03:58.450Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.91GB (12.19GB free)|
|Process Argv|--crash-reporter-id 4381238b-f901-444c-9458-8d357d75e957|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
reveal-button|anw|1.1.1
a-file-icon-vscode|ato|1.2.0
regex|chr|0.4.0
dart-code|Dar|3.93.20240708
flutter|Dar|3.93.20240702
vscode-markdownlint|Dav|0.55.0
githistory|don|0.6.20
xml|Dot|2.5.1
vsc-material-theme|Equ|34.4.0
vsc-material-theme-icons|equ|3.6.1
prettier-vscode|esb|10.4.0
codespaces|Git|1.17.1
copilot|Git|1.211.981
copilot-chat|Git|0.18.2024071101
remotehub|Git|0.63.2024061801
vscode-pull-request-github|Git|0.93.2024071104
todo-tree|Gru|0.0.226
vscode-lottie|lot|1.0.5
vscode-docker|ms-|1.29.1
remote-containers|ms-|0.377.0
remote-wsl|ms-|0.88.2
azure-repos|ms-|0.39.2024061901
hexeditor|ms-|1.10.0
remote-explorer|ms-|0.5.2024070409
remote-repositories|ms-|0.41.2024022202
remote-server|ms-|1.6.2024070809
material-icon-theme|PKi|5.4.2
vscode-thunder-client|ran|2.24.12
vscode-xml|red|0.27.2024053103
flutter-riverpod-snippets|rob|1.2.2
code-spell-checker|str|3.0.1
vsfire|tob|1.4.1
vscode-pets|ton|1.27.0
tab-groups|usa|2.1.1
adb-interface-vscode|vin|0.22.4
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vim|vsc|1.27.3
markdown-all-in-one|yzh|3.6.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
vscrpc:30624061
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
chatpanelt:31014475
jg8ic977:31013176
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31057980
nativerepl1:31093711
refactort:31084545
pythonrstrctxt:31093868
0c838689:31088353
hdi1a554:31091669

```

</details>

**Comment by l1qu1d** [comment]
Still broken in today's release (July 12).

**Comment by Ahmed-Reda-Dev** [comment]
![Screenshot 2024-07-12 185738](https://github.com/user-attachments/assets/fdee3c39-ca4e-4467-9d25-95b5413dbb20)
this is an error 
flutter is Unable to determine VS Code version.

**Comment by l1qu1d** [comment]
In the meantime, you can run the `flutter run` command in the terminal to get a debug session going. The main issue is that you must re-run the command to restart the debugging session. You can press `r` in the terminal to do hot reloading, but I'm working on state stuff, which needs a complete rerun.

**Comment by Ahmed-Reda-Dev** [comment]
Yeah I know but I mean it is the reason that caused this error in the vscode insider.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/224184
