### ISSUE TITLE
html.format.wrapLineLength: 0 -- breaks with long script tags

### ISSUE THREAD

**Issue by ajoslin103** [Microsoft/vscode#22143]
html.format.wrapLineLength: 0 -- breaks with long script tags

when you open a .html file with a very long line in a script tag then that line wraps, as does the rest of the file at that point.

note: when you paste in the line it works ok and doesn't wrap.  but when you save the file and open it again then it's wrapping.

- VSCode Version:1.10.1
- OS Version:OS X 10.12.3

Steps to Reproduce:

1. add html.format.wrapLineLength: 0 setting to your prefs
2. open html with long script tag -- wrapping

**Comment by aeschli** [comment]
`html.format.wrapLineLength: 0` only applies when you format a file
(for example using the `Format Document` command).

What you see is the automatic wrapping of very long lines. This is done for performance reasons.
@alexandrudima knows more

**Comment by ajoslin103** [comment]
This is a killer for that type of file.  In those cases I make standalone .html files as reports and they contain a hideously long line of data.  When such a choice has to be made for performance reasons (a reason that I am happy to agree with!) could those lines be made collapsable?

**Comment by alexandrudima** [comment]
Let's track in #21801
