### ISSUE TITLE
Allow all configurations to be effective in workspace settings.json.

### ISSUE THREAD

**Issue by tfuto** [microsoft/vscode#221446]
Main issue: Some settings in the user `settings.json` won't work if placed in the workspace `settings.json`. Some of these are:
```
update.mode
extensions.autoUpdate
extensions.autoCheckUpdates
telemetry.telemetryLevel
```

Problems with this:
1. In a completely sandboxed environment, or in a strictly proxied environment, extranet actions should be completely suppressed. (Current issue I am trying to solve.)
2. Although it makes sense to handle these as user settings, it does not make sense to **disallow** specifying/overwriting them in the workspace `settings.json`.
3. `--user-data-dir`, in its current form, is not readily versionable. There are a mixture of various content aside of configuration JSON files there.

Ideal setup:
 - The project is self-contained, including user settings.
 - The project can be versioned in Git without scripts to back up/change settings external to the project folder.
 - A `git clone` should restore **everything** that is required for a successful build.

Suggestions:
 - Either allow specifying/overwriting the user settings in the workspace `settings.json` file or
 - Support a `userSettings.json` file in the workspace so that user settings could be stored there (maybe also overwriting some global user `settings.json` values.

**Comment by sandy081** [comment]
> Either allow specifying/overwriting the user settings in the workspace settings.json file 

This cannot be supported

> Support a userSettings.json file in the workspace so that user settings could be stored there (maybe also overwriting some global user settings.json values.

You can use symlinks - symlink the settings.json file from your user settings to point to the one from workspace settings.
