### ISSUE TITLE
Enabling dropIntoEditor disables drag/drop within a custom editor

### ISSUE THREAD

**Issue by thomasAtToem** [microsoft/vscode#221481]
Hi all,
we develop a custom editor in vscode that supports drag and drop.
Recently we noticed that this is not working anymore.
After getting into "dragover" we encounter a "dragleave" without leaving the actual element (afterwards the drag listeners do not get any event anymore but the drop image is still with cursor !!!) 
We found that this is related to dropIntoEditor --  when disabling , drag/drop inside the custom editor is working again.
Its also somehow working when holding the shift key, but this conflicts with the typical drag/drop usage.

So, how to allow dropIntoEditor but keep the possibility of drag/drop inside the custom editor?
thanks,
thomas

**Comment by mjbvz** [comment]
Which vs code version?

**Comment by thomasAtToem** [comment]
Latest version I got - 1.91.

**Comment by swordensen** [comment]
@thomasAtToem  do you still encounter this on the latest version of vscode? (1.93)

**Comment by mjbvz** [comment]
I believe this has been fixed by the work around #224967
