### ISSUE TITLE
files.autoSave: onFocusChange - No longer working or seems intermittent 

### ISSUE THREAD

**Issue by brianjaikens** [Microsoft/vscode#22142]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.12.0|
|vscode-markdownlint|DavidAnson|0.6.2|
|vscode-instant-markdown|dbankier|1.0.0|
|jquerysnippets|donjayamanne|0.0.1|
|xml|DotJoshJohnson|1.7.0|
|classic-asp|ilich8086|0.0.2|
|font-awesome-codes-html|medzhidov|0.0.6|
|code-beautifier|michelemelluso|1.6.2|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|Theme-TomorrowKit|ms-vscode|0.1.3|
|debugger-for-chrome|msjsdiag|2.6.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|;

---

Steps to Reproduce:

1.
2.

**Comment by hworld** [comment]
Same for me. I can't seem to really figure out what it is. I _does_ seem to randomly save some times, but most of the times it doesn't. I don't use tabs and usually just switch between files by using ctrl+p. It doesn't seem to trigger an autosave when doing that.

**Comment by igrayson** [comment]
Same here. Version 1.10.1, `653f8733dd5a5c43d66d7168b4701f94d72b62e5`, OSX 10.11.6

**Comment by bpasero** [comment]
@hworld @igrayson @brianjaikens can you please try out our insiders build (from http://code.visualstudio.com/Download#insiders) where I pushed a possible fix to verify that it fixes the issue for you?

**Comment by igrayson** [comment]
Insider build works correctly, for me.

**Comment by bpasero** [comment]
@igrayson thanks 👍
