### ISSUE TITLE
Creating commands that can be used in the Ctrl+I menu

### ISSUE THREAD

**Issue by yurifw** [microsoft/vscode#221490]
When you press Ctrl + I in VsCode a little Input text appears where you can "Ask Copilot or type / for commands". Some example of commands are /doc to add documentation and /fix to fix problems in the code.

It would be nice if we could create commands of our own that would be basically shortcuts for prompts, for example:

I could type `/clear` instead of typing the prompt `Remove all unused imports, variables and all the comments that are not documentation in this file`

or

`/component` instead of `create a new functional component with the same name as this file`

**Comment by jrieken** [comment]
fyi @aeschli @digitarald

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/228177
