### ISSUE TITLE
connect ETIMEDOUT 191.238.172.191:443

### ISSUE THREAD

**Issue by amvoidhub** [Microsoft/vscode#22151]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-eslint|dbaeumer|1.2.2|
|python|donjayamanne|0.5.6|
|cpptools|ms-vscode|0.10.0|
|csharp|ms-vscode|1.6.2|
|vscode-icons|robertohuertasm|7.1.2|
|guides|spywhere|0.6.1|;

---

Steps to Reproduce:

1.
2.

**Comment by sean-mcmanus** [comment]
Can you provide more details? Our cpptools extension gives that message if it can't download runtime dependencies, but it says something like: "Updating C/C++ dependencies...Error: connect ETIMEDOUT ".

**Comment by amvoidhub** [comment]
whenever I update extensions, this error shows up.

**Comment by sean-mcmanus** [comment]
Okay, that's an issue with VS Code or your internet connection and/or http.proxy settings (and not extensions).
