### ISSUE TITLE
I need help with my codespace / cs50 program

### ISSUE THREAD

**Issue by MileidyVega** [microsoft/vscode#221520]
ADD ISSUE DESCRIPTION HERE
I am using codespace for my CS50 program intro to python but i think some how i broke to connection that the space wont allow me to do python commands and i honesty don't know how to fix it 
Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by dmalan** [comment]
Best to email sysadmins@cs50.harvard.edu with @cs50 questions!
