### ISSUE TITLE
"Failed To Save" - Unknown File System Error

### ISSUE THREAD

**Issue by PN-03** [microsoft/vscode#221524]
Hello,

Whenever my computer goes into Sleep/Hibernate Mode or Locks itself while VS Code is Running and I log back in, VS Code will give this Error When Saving A File:

![VS Code - Unable To Save Error](https://github.com/user-attachments/assets/a52aa23b-2883-4954-89a3-15128c9ce241)

This happens regardless of whether AutoSave is Turned On or Off. VS Code won't be able to save any files unless I use the "Scan and Repair" tool for the drive I'm using. Only then will saving work again. Restarting VS Code doesn't fix the issue.

**Comment by bpasero** [comment]
This does not sound like a defect VS Code can fix, rather a configuration issue.
