### ISSUE TITLE
Debug Console Filtering Seems Inaccurate

### ISSUE THREAD

**Issue by coreyogburn** [microsoft/vscode#221594]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.0-insider
- OS Version: 
Linux x64 6.5.0-42-generic
Ubuntu 23.10 Mantic

Steps to Reproduce:

1. Type filter into debug console
2. Observe lines that should be filtered out but aren't, observe lines that should be filtered in but aren't

The debug console seems to lump "lines" together by the timing of the output from the debugged process. I mostly work in Go and I see this behavior on a daily basis. Different log statements in my program will appear to be grouped together when I mouse over the debug console output.

Here's a sample of some debug output present in the debug console among other lines of a paused program:

> DEBUG[0100] Preprocessing request     processorPriority=0 processorType=*web.BasePreprocessor
>  DEBUG[0100] Preprocessing request     processorPriority=100 processorType=*statickeyauth.StaticKeyAuthImpl
>  DEBUG[0100] Authorization check via API key isApiKeyAccepted=true requestId=386a46c5-b190-4111-9535-964790728f56
>  DEBUG[0100] Preprocessing request     processorPriority=110 processorType=*kratos.KratosPreprocessor
>  DEBUG[0100] Evaluated authorization for requestor authorized=true permission=nodes/write primaryRoles=[agent config-admin event-admin] user=00000000-0000-0000-0000-000000000000
>  DEBUG[0100] Evaluated authorization for requestor authorized=true permission=nodes/write primaryRoles=[agent config-admin event-admin] user=00000000-0000-0000-0000-000000000000
>  DEBUG[0100] Evaluated authorization for requestor authorized=true permission=nodes/read primaryRoles=[superuser] user=ed1ade5b-0986-44f3-afe9-de9420157fc2
>  DEBUG[0100] Broadcasting message to WebSocket connection messageKind=node sourceIp=192.168.122.1
>  DEBUG[0100] Evaluated authorization for requestor authorized=true permission=jobs/process primaryRoles=[agent config-admin event-admin] user=00000000-0000-0000-0000-000000000000

When I mouseover any individual line, a visual highlight box lumps these lines together. Filtering seems to take place at the "block" level and not the line level. If I filter for `Preprocessing request` I expect the 1st, 2nd, and 4th lines to be present and everything else to be filtered out but instead this group remains as a whole. When I filter for `processorPriority=1` I expect the 2nd and 4th lines to remain, or at least the chunk to remain, but the entire block is filtered out.

It seems the equals sign is what's resulting in zero results. `processorType` filters chunks as expected, but `processorType=` will filter everything out. Does the symbol have an alternative use here that I don't know of such as the ! to exclude terms? Escaping the equals sign does not seem to make a difference.

Can the console be configured to filter by lines instead of chunks of seemingly simultaneous output?

**Comment by roblourens** [comment]
The debug console filters by OutputEvents from the debug extension. From what you're describing, it seems likely that the Go debug extension is grouping multiple output lines into a single OutputEvent. From vscode's perspective, it looks the same as one multiline string, so it doesn't make sense for us to filter lines here.

You could open an issue on the Go extension to see whether that's the case, but also, I'll fold it into this issue which essentially describes this and some other issues https://github.com/microsoft/vscode/issues/204391
