### ISSUE TITLE
Breakpoints ignored for JavaScript module that requires another JS module

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#22155]
- VSCode Version: 1.11.0-insider
- OS Version: Windows 10 Enterprise
- Node.JS version: 7.7.1

Steps to Reproduce:

**a.js**

```js
function f() {
    console.log("f");
}
exports.f = f;

if (!module.parent) {
    f();
}
```

**b.js**
```js
const { f } = require("./a");

if (!module.parent) {
    console.log("b");
    f();
}
```

**.vscode/launch.json**

```js
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/b.js",
            "cwd": "${workspaceRoot}",
            "protocol": "inspector"
        }
    ]
}
```

1. Put a bunch of breakpoints in `a.js` and `b.js`.
1. Change `launch.json` "program" to `a.js`. Hit F5. Debugging works.
2. Change `launch.json` "program" back to `b.js`. Hit F5. The program's output goes to the debug console, but none of the breakpoints (in either file) are hit.

```
node --inspect=42343 --debug-brk b.js 
Debugger listening on port 42343.
Warning: This is an experimental feature and could change at any time.
Debugger attached.
Waiting for the debugger to disconnect...
b
f
```

It doesn't work with `"protocol": "legacy"` either.

**Comment by roblourens** [comment]
This is a Node bug after 7.0 - I filed an issue on Node.

**Comment by weinand** [comment]
@roblourens thanks for figuring this out! Could you please add the node issue link here and then close this issue.

**Comment by michelkaporin** [comment]
@weinand Nothing to verify. Should we move it to the backlog or April milestone as it has not yet been addressed by Node.js?

**Comment by weinand** [comment]
I've moved it to the backlog.
