### ISSUE TITLE
Settings editor - Put cursor at current find result

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#22159]
- Open settings editor
- cmd+f to do a search
- Press enter to focus a search result that exists in your settings.json
- Press cmd+1 to move focus to settings.json

The cursor should be at the current highlighted search result, but instead it's just at its previous location.

**Comment by dakaraphi** [comment]
@roblourens how about just using cursor down to move focus to settings.json.
This would be similar to how the global file search allows you to press down cursor to move to the results from the search box.
Also, if the default were 'cmd+1' I would lose the ability to jump back to the first editor group if I open the settings in a different group.

**Comment by roblourens** [comment]
I think using the arrow key could work too, that's a good point. 

I say 'cmd+1' here as the usual 'focus first editor group'. If you open the settings in the second editor group, you can use 'cmd+2' for it, and get back to the first group with cmd+1. I don't know how discoverable that is either, since in my scenario, focus is already in the first group, so would it occur to people to use it to focus the editor?

**Comment by sandy081** [comment]
Good thoughts.. will think about the key for focussing the editor.

**Comment by sandy081** [comment]
<kbd>down</kbd> already focuses into the editable settings editor. 

Added support to position the cursor to currently focussed / matched setting.

To Verify:

- Open settings editor
- cmd+f to do a search
- Press enter to focus a search result that exists in your settings.json
- Press down and settings.json is focussed and the cursor is placed at the currently focussed matching setting
