### ISSUE TITLE
More friendly terminating of running task

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#22154]
Hi!

- VSCode Version: 1.10.1
- OS Version: macOS Sierra

It is a bit lengthy to terminate current running task by "cmd+shift+p term up|down to select Tasks: Terminate Running Task and Enter".

It would be great to have e.g.
- Terminate Task context action on Task Output window, or better
- to have a button inside Output Window which will terminate current task (Terminal window also have custom icons at the top right corner ;)

Thanks for evaluating!

**Comment by ramya-rao-a** [comment]
You can bind a keyboard shortcut to the command "workbench.action.tasks.terminate" for a quicker termination.

**Comment by obrejla** [comment]
Yep, that's definitely better than using command search. But button would be much better...because it would be in the "right context" ;) Global command is just too "general" in this case ;) Thanks a lot.

**Comment by dbaeumer** [comment]
We are moving to running tasks in the terminal which makes terminating them a lot easier since the terminal panel already has support to terminate a terminal. No further action is planned for the output panel.

I am closing this issue since the terminal will support the requested functionality.

**Comment by obrejla** [comment]
You can't even imagine how I'm glad to hear it! :-) That's what I actually want in #22156 

Do you have some time estimate when it could be live? Because running thousands of JS tests through Output window is unusably slow. Thanks ;)

**Comment by dbaeumer** [comment]
Support for this is already in 1.9 and 1.10 but not on by default. See the release notes for 1.9 and 1.10 how to enable this. In 1.10 you can simply change the version field of the tasks.json to 2.0.0. But be aware that running in the terminal is work under construction. And it might change a little in the future.

**Comment by obrejla** [comment]
Sounds great, will definitely try that, thanks!
