### ISSUE TITLE
How to close the annoying terminal status window, which show  information about PID, etc.?

### ISSUE THREAD

**Issue by ZedRover** [microsoft/vscode#221531]
I use Visual Studio Code to edit code on my MacOS. I often utilize VSCode Remote to run some Python code on a server. I usually open multiple terminal windows to conveniently view different code results. However, I frequently encounter the issue of being unable to select a specific terminal from the terminal tabs because that annoying terminal status windows always appears under my cursor when I move my mouse over a terminal, blocking my selection of the corresponding window. This fucking window moves very quickly, and I often find myself in the awkward situation of being unable to select the terminal. I wish I could completely disable this utterly useless prompt window.

<img width="523" alt="image" src="https://github.com/user-attachments/assets/122b5db6-12ab-4167-ba50-c3ff610a7bdd">

**Comment by Tyriar** [comment]
From the thick border it looks like you're holding alt which will [lock its visibility}(https://code.visualstudio.com/docs/editor/accessibility#_hover-accessibility). But regardless, I agree we could position it better.
