### ISSUE TITLE
Can't horizontal scroll to the end of logpoint's and conditional breakpoint's placeholder

### ISSUE THREAD

**Issue by yamgomes** [microsoft/vscode#221506]
Type: <b>Bug</b>

1. Have a narrow-ish VS Code window (so that the tooltip doesn't fit)
2. Click to add a logpoint or conditional breakpoint
3. Try horizontal scrolling (Shift + Scroll) to see the end of the message

Expected: See the entire placeholder message
Actual: The placeholder message cuts off after "'Escape' to c..."

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600 6-Core Processor               (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (7.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600 6-Core Processor (12 x 0)|
|Memory (System)|23.47GB (15.66GB free)|
|VM|0%|
</details>Extensions: none

**Comment by yamgomes** [comment]
This is the farthest the scrolling goes, no matter the width of the window. Maybe the scrollable width is not taking the offset from the dropdown into account?

![image](https://github.com/user-attachments/assets/70a20a3a-a20c-4304-adce-0241da71f40a)

![image](https://github.com/user-attachments/assets/8ab86512-94f5-4df5-ab01-4a9007088bf0)

**Comment by roblourens** [comment]
I wasn't expecting this to scroll since we hide the scrollbar. It surprises me that it does... I think we should just show the placeholder in a tooltip.
