### ISSUE TITLE
Odd terminal behavior on Chinese locale

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#22158]
Reported by @nuintun in https://github.com/Microsoft/vscode/issues/21966#issuecomment-284289178

![ae75cffa-0258-11e7-835d-551660b6d334](https://cloud.githubusercontent.com/assets/2193314/23666372/b5bc2888-030f-11e7-8981-b5f7d68e26af.gif)

Does not repro in xterm.js:

![b2de8f72-0321-11e7-8be0-eeb82cc84900](https://cloud.githubusercontent.com/assets/2193314/23666375/b6f39cf4-030f-11e7-8359-ced001bdd93e.gif)

Could be related to node-pty 0.6 since xterm.js is still on 0.4?

**Comment by nuintun** [comment]
@Tyriar 

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-caniuse|akamud|0.5.3|
|Bookmarks|alefragnani|0.14.1|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|vscode-svgviewer|cssho|1.4.0|
|vscode-npm-source|dkundel|1.0.0|
|githistory|donjayamanne|0.2.0|
|vscode-html-css|ecmel|0.1.2|
|EditorConfig|EditorConfig|0.9.3|
|tortoise-svn|fantasytyx|0.1.1|
|auto-rename-tag|formulahendry|0.0.11|
|beautify|HookyQR|1.0.2|
|docthis|joelday|0.4.3|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|vscode-icons|robertohuertasm|7.5.1|
|aspnet-helper|schneiderpat|0.6.3|
|code-spell-checker|streetsidesoftware|1.0.2|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.1.0|

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/24743
