### ISSUE TITLE
Split Up/Down menu items not working

### ISSUE THREAD

**Issue by plastikfan** [microsoft/vscode#221587]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.2
- OS Version: 11.7.10 (Big Sur)

Steps to Reproduce:

1. open vscode
2. open an editor window
3. select View-> Editor Layout-> Split Down

Nothing happens.

However there is a work around: hold down the alt key and click on the Split Editor XX on the top right of the editor window (the last icon in the list before the elipses). XX is dynamic depending on wether you are hlding the alt key. When you activate window splitting using this method it works. So just the menu item is broken. I've only checked Split up and Split Down.

Version info:

Version: 1.90.2
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:37:41.291Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin x64 20.6.0

PS: I am not using the latest version of vs code because the latest version is broken for macOS Big Sur as I found out just a few days ago and the work-around was to downgrade to this version until a fix is released.

**Comment by gjsjohnmurray** [comment]
FYI the 1.91.1 release (which works on your macOS) came out yesterday.

**Comment by benibenj** [comment]
This should be fixed in the newest update
