### ISSUE TITLE
vs code terminal(zsh) : Timestamps do not fit on the right side

### ISSUE THREAD

**Issue by wowqhb** [microsoft/vscode#221526]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: v1.91.1
- OS Version: Ubuntu20.04LTS

**VS Code Version Detail:**
版本: 1.91.1
提交: f1e16e1e6214d7c44d078b1f0607b2388f29d729
日期: 2024-07-09T22:08:12.169Z
浏览器: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.91.1 Chrome/122.0.6261.156 Electron/29.4.0 Safari/537.36

Steps to Reproduce:
![image](https://github.com/user-attachments/assets/5996daa8-48c0-4e86-8386-9f04431e4d00)

**shell environment: zsh + zim  + powerlevel10k**

**Comment by meganrogge** [comment]
/duplicate [#219892](https://github.com/microsoft/vscode/issues/219892)
