### ISSUE TITLE
Always fails to launch any external program

### ISSUE THREAD

**Issue by sietseringers** [Microsoft/vscode#22152]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.2|
|cmake|twxs|0.0.15|;

---

When trying to compile a C++ project, VSCode tells me it "Failed to launch external program sh -c". `process.env.PATH` looks like it's correctly populated. Replacing `sh` with `/bin/sh` or `bash` or `/bin/bash` in tasks.json doesn't work. Whether I use bash or fish as login shell does not seem to matter; the problem always occurs. Launching Code via the Finder or command line also does not matter.

This does not seem to be the same as #21655 or #8434, which had to do with incorrectly parsed $PATHs. @joaomoreno 

Steps to Reproduce:

1. Try to compile a project using shift-command-B

**Comment by joaomoreno** [comment]
Yup, this seems tasks specific.

**Comment by sietseringers** [comment]
Indeed. After having experimented a bit in tasks.json, the problem has suddenly dissapeared - even though my tasks.json is now exactly the same as it was before! Happy it works though.

**Comment by dbaeumer** [comment]
Closing then. If you see it again, please ping. Best with a reproducible case or a GitHub repository we can clone.
