### ISSUE TITLE
Inline chat does not expand sufficiently to show new lines

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#221598]
Type the following in inline chat:

```
foo

bar

baz
```

Notice the bad behavior when typing the last line

https://github.com/user-attachments/assets/0256dbc9-654f-4807-83d0-8e41226ff77d

**Comment by jrieken** [comment]
dupe of https://github.com/microsoft/vscode/issues/216843 but this should be fixed by having sticky scroll disabled
