### ISSUE TITLE
Trim trailing whitespace not working

### ISSUE THREAD

**Issue by zealoussnow** [microsoft/vscode#221621]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:54.982Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin x64 21.6.0

- OS Version: macOS 12.7.5 (21H1222)

Steps to Reproduce:

1. Open Settings, add ` "files.trimTrailingWhitespace": true` in settings.json
2. Add trailing whitespace  in my file
3. Save file, but trailing whitespace not working
4. And when I set `editor.trimAutoWhitespace` from false to true, no effect too

![vscode](https://github.com/user-attachments/assets/56adc5e4-4801-4389-bf0a-4d81d1d12517)

**Comment by hediet** [comment]
Is this specific to SSH? Can you try to reproduce on a local workspace?

**Comment by zealoussnow** [comment]
> Is this specific to SSH? Can you try to reproduce on a local workspace?

Yes, I’m using the RemoteSSH plugin. I’m currently working on it in my local workspace and haven’t encountered any problems.
![vscode-local-workspace](https://github.com/user-attachments/assets/288b408c-fbfe-4a71-860f-a5fd977dce5d)

**Comment by zealoussnow** [comment]
> Is this specific to SSH? Can you try to reproduce on a local workspace?

I found the reason. I don’t know when, but I mistakenly added files.trimTrailingWhitespace to `.vscode/settings.json`.
