### ISSUE TITLE
The terminal Closes automatically

### ISSUE THREAD

**Issue by mdharoon15304** [microsoft/vscode#221657]
Type: <b>Bug</b>

I opened the  cs50 codespace for programming and it used to work fine before but now after opening , no terminal is visible at all and if i click on new terminal in terminal tab , the terminal opens for 1 sec and then closes automatically

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22635
Modes:
Remote OS version: Linux x64 6.5.0-1022-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.36GB (1.11GB free)|
|Process Argv|--crash-reporter-id a2f62c34-b1cf-47a4-a6c4-98d51df75506|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: redesigned space potato|
|OS|Linux x64 6.5.0-1022-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (2 x 0)|
|Memory (System)|7.74GB (5.77GB free)|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.17.1
cs50|CS5|0.0.1
ddb50|CS5|2.0.0
explain50|CS5|1.0.0
extension-uninstaller|CS5|1.0.9
phpliteadmin|CS5|0.0.1
style50|CS5|0.0.1
codespaces|Git|1.17.1
vscode-pull-request-github|Git|0.92.0
prettier-sql-vscode|inf|1.6.0
vscode-pdf|mat|0.0.6
vscode-docker|ms-|1.29.1
vscode-language-pack-bg|MS-|1.48.3
vscode-language-pack-cs|MS-|1.91.2024071009
vscode-language-pack-de|MS-|1.91.2024071009
vscode-language-pack-es|MS-|1.91.2024071009
vscode-language-pack-fr|MS-|1.91.2024071009
vscode-language-pack-hu|MS-|1.48.3
vscode-language-pack-it|MS-|1.91.2024071009
vscode-language-pack-ja|MS-|1.91.2024071009
vscode-language-pack-ko|MS-|1.91.2024071009
vscode-language-pack-pl|MS-|1.91.2024071009
vscode-language-pack-pt-BR|MS-|1.91.2024071009
vscode-language-pack-ru|MS-|1.91.2024071009
vscode-language-pack-zh-hans|MS-|1.91.2024071009
vscode-language-pack-zh-hant|MS-|1.91.2024071009
autopep8|ms-|2024.0.0
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
cpptools|ms-|1.20.5
hexeditor|ms-|1.10.0
vsliveshare|ms-|1.0.5932
java|red|1.32.0
vscode-java-debug|vsc|0.58.0
gitdoc|vsl|0.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31094925
refactort:31093865
4930e709:31092288

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
