### ISSUE TITLE
VS Code breaks <pre> indention when formatting the documentation.

### ISSUE THREAD

**Issue by zwcloud** [microsoft/vscode#221618]
Does this issue occur when all extensions are disabled?: Yes
![](https://github.com/user-attachments/assets/78972523-8045-4c67-9962-dfe7f4eb2b2c)

- VS Code Version:
> Version: 1.91.1 (user setup)
> Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
> Date: 2024-07-09T22:06:49.809Z
> Electron: 29.4.0
> ElectronBuildId: 9728852
> Chromium: 122.0.6261.156
> Node.js: 20.9.0
> V8: 12.2.281.27-electron.0
> OS: Windows_NT x64 10.0.22631
- OS Version:
> Microsoft Windows 11 Pro 10.0.22631 Build 22631

Steps to Reproduce:

1. Create a html file
2. Add following content
```html
<html>
<head></head>
<body>
    <pre>
12345
12345
12345
    </pre>
</body>
</html>
```
3. format the documentation
4. see result that incorrectly adding indent to `<pre>` element's content, which should not happen:
```html
<html>

<head></head>

<body>
    <pre>
        12345
        12345
        12345
    </pre>
</body>

</html>
```
expected result is
```html
<html>

<head></head>

<body>
    <pre>
12345
12345
12345
    </pre>
</body>

</html>
```

Turn off auto-indent is Not a solution. Obviously it is a bug that the text inside a `<pre>` element is not preserved after formatting.

video
https://github.com/user-attachments/assets/c352a86b-0cb3-4c8c-8b8a-0224cdb41f0a

exported .code_profile file
[sample_profile.zip](https://github.com/user-attachments/files/16201055/sample_profile.zip)

**Comment by RedCMD** [comment]
I cannot confirm

formatting results in:
```html
<html>

<head></head>

<body>
    <pre>
12345
12345
12345
    </pre>
</body>

</html>
```

are you using a 3rd party formatter? Prettier?

**Comment by zwcloud** [comment]
Add a screenshot as proof that no extension is enabled.

**Comment by RedCMD** [comment]
you have the `"html.format.contentUnformatted"` setting set to `null`

**Comment by zwcloud** [comment]
But I never touched this settings. Reset `html.format.contentUnformatted` to `pre` works as expected now. Thank you.
