### ISSUE TITLE
Cannot debugWithChrome

### ISSUE THREAD

**Issue by craftyc0der** [microsoft/vscode#221645]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 192
- OS Version: OS X

Steps to Reproduce:

1. Version: 1.92.0-insider (Universal) Commit: a35380d6f0ff65f7c35345baafcf1c3f8a378d38 Date: 2024-07-12T05:08:08.550Z (1 day ago)
2. Launch chrome debugger with
    {
      "name": "React Debug",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceRoot}/typescript",
      "runtimeExecutable": "pnpm",
      "runtimeArgs": ["web:debug"],
      "serverReadyAction": {
        "pattern": "localhost:([0-9]+)",
        "uriFormat": "http://localhost:%s",
        "action": "debugWithChrome",
        "webRoot": "${workspaceRoot}/typescript",
        "killOnServerStop": true,
      },
    },
This shows when no sessions are running:
![image](https://github.com/user-attachments/assets/04669b32-fbf6-4f93-8c55-3ffdd8cf2370)
Browser opens and immediately crashes.

Open VS code 191.1 and everything works as expected.

**Comment by connor4312** [comment]
Please open an issue on Chrome for this. They will probably want a crash log that you can get from `~/Library/Logs/DiagnosticReports` or `chrome://crashes`
