### ISSUE TITLE
github copilot not working. unhandled status from server:400 bad request

### ISSUE THREAD

**Issue by Naveens-Harman** [microsoft/vscode#221636]
Type: <b>Bug</b>

Git hub copilot notworking. While usinfg chat, getting error message as "unhandled status from server:400 bad request". Signed out and signed back still issue not resoved

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by Landibar19** [comment]
im having the same issue to

**Comment by olgabrushuk** [comment]
I'm having the same issue. Is it something to do with the payment?

**Comment by roblourens** [comment]
There was a transient issue a couple weeks ago that should be resolved now. 

@olgabrushuk you are still seeing this now? Anything interesting in the "Copilot Chat" output channel log?
