### ISSUE TITLE
Server initialization failed.

### ISSUE THREAD

**Issue by pannous** [Microsoft/vscode#22163]
- VSCode Version:
1.10.1
- OS Version:
10.12.3

Steps to Reproduce:
Obviously a rare case, but whenever I try to start debugging **anything** I get this in the Output pane:
```
Server initialization failed.
Message: Request initialize failed with message: Cannot read property 'replace' of null
  Code: -32603 
```

The debug console just says "`node`"

Problems pane: `no problems have been detected in your workspace so far.`

**Comment by isidorn** [comment]
@pannous This seems like an output of your `preLaunchTask`.
Can you share your `launch.json`.
What happens if you just launch your task without even debugging?

**Comment by pannous** [comment]
this happens in an empty folder without `launch.json`

update: removing ~/.vscode helped
