### ISSUE TITLE
Tooltips/Popups are more sticky than before

### ISSUE THREAD

**Issue by ghnp5** [microsoft/vscode#221607]
Type: <b>Bug</b>

Since the upgrade to 1.91.1, the tooltips/popups (that show function documentation on mouseover, for example) have become a hinder, because they seem to get sticky, being in the way when I want to select/click something on the lines that the tooltip/popup is overlaying.

I'm not 100% sure how to explain this, or what exactly changed, but I know this wasn't a problem in the version before. Something definitely changed in version 1.91.1.

I'm not sure if it's because they're appearing faster, or taking longer to disappear, or...

Thank you!

--

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (14.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-intelephense-client|bme|1.10.4
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.0
prettier-vscode|esb|10.4.0
duplicate|gee|1.0.2
vscode-github-actions|git|0.26.3
php-cs-fixer|jun|0.3.13
vscode-phpunit|rec|3.2.2
vscodeintellicode|Vis|1.3.1
php-sniffer|won|1.3.0
php-debug|xde|1.34.0

</details>

**Comment by aiday-mar** [comment]
Hi @ghnp5 the editor hover has not been fundamentally changed last iteration. Last iteration I have refactored the editor hover code so this could be the source of the new issue you are seeing. For me to understand better the situation, next time you see the issue you described, could you post a screen recording here and an example of the code where you are seeing the issue?

**Comment by ghnp5** [comment]
Thank you.

I cannot show much of the code, but here's a short video which I hope helps. (I tried to "exaggerate/force" a bit, but it should show what I mean)

These editor hovers have been annoying me all day, since the update. They just keep being in the way.

In previous versions, wasn't the hover disappearing when the mouse leaves the tooltip?
Or when the user is selecting text?

Thanks.

https://github.com/user-attachments/assets/b935bcc6-ca47-4ff7-9a8d-3648acf78798

**Comment by gjsjohnmurray** [comment]
What version were you previously on?

**Comment by aiday-mar** [comment]
Hi @ghnp5 the hover should still disappear if you keep your mouse outside of the hover for long enough. Perhaps you could change the value of the setting `editor.hover.hidingDelay`. This setting controls how quickly the hover disappears. The default is 300 ms, meaning that after 300 ms outside of the hover it disappears. Similarly you could tweak the setting `editor.hover.delay` - this setting controls how quickly the hover shows, ie how long the cursor needs to be on a word before the hover is shown.

**Comment by ghnp5** [comment]
> What version were you previously on?

I believe I was on 1.91.0, but maybe I didn't use it enough between upgrading to that one, and 1.91.1, to find this issue.

Before that, I was on last month's iteration, which definitely didn't have this problem.

> Perhaps you could change the value of the setting editor.hover.hidingDelay. 

Thank you. I was going to change that option, and then I saw a hint about `editor.hover.sticky` having to be enabled. So, what I did is I actually **disabled** that one.
Seems to have improved a bit. It seems to be still remaining sticky if I do put the mouse over it, so I'm not sure what exactly that option does (its description says the hover will remain visible when mouse is moved over it), but somehow, disabling this option makes the hover disappear if I move the mouse outside the code that triggered the hover, which is similar to the behavior I had before, I think. And if I click on the hover, it remains sticky, which is good/expected.

> Similarly you could tweak the setting editor.hover.delay

Great. I changed from 300 to 600, so it doesn't appear so quickly.

--

Thank you for the tips.

I think there's still one question left -- what about when I'm selecting text (like shown in the video above) ? Wasn't the hover supposed to disappear, once I'm selecting text, and therefore the user is not interested in having a hover in the way of the selection? :)

Many thanks, again!

**Comment by aiday-mar** [comment]
Hi @ghnp5 thank you for the comment. When the cursor has some text selected, and you hover on a word long enough, the editor hover will appear. Here the editor selection does not affect the appearance of the editor hover, currently what matters is that the mouse is on or outside of the hover long enough for it to appear/disappear. The idea you put forth is interesting however, and I will open an issue about it. If the community votes sufficiently for it, I can make this change.

**Comment by Savedyou** [comment]
I am having an issue with this as well since updating versions.  I attached some images.

attempting to drag selected text into the object
![Untitled](https://github.com/user-attachments/assets/65a200c0-285d-40ff-8006-bcf5081fc488)

once selected tooltip stays in place permanently blocking destination
![Untitled2](https://github.com/user-attachments/assets/9e33713a-a262-4a0a-8890-7d3ae38f1293)

I think once you hold down left click on a selection to start moving, the tooltip should always disappear.  At least that is the behavior that you would expect in most applications.

**Comment by SeanDoh** [comment]
+1 to this, also experiencing the same issue after updating versions

**Comment by MohenjoDaro** [comment]
Also having this issue. The Hover Hide Delay is using the Hover Delay instead, so if you have a long delay before the tooltip appears, you will have a long delay before it disappears.

If you set the Hover Delay to 0 and the Hover Hide Delay to 1000, should see the tooltip appear and disappear instantly

**Comment by SADA-Sam** [comment]
> Hi @ghnp5 thank you for the comment. I believe the way the editor hover works is that when you click outside of the hover, the hover disappears. Meaning when you start a selection it disappears.

I have noticed and issue when using VS Code, in which the clicking outside of a tooltip will no longer dismiss hover. This occurs after leaving VS Code open for a while, including after a sleep/hibernate cycle. When this happens I have to restart VS Code, otherwise, clicking anywhere, including to initiate text selection does not dismiss any existing tooltip and the tool tip then interferes with the selection process.

Perhaps there is a bug that is causing the described tooltip/click behavior to break after leaving VS Code open for some time. It might be related to this issue of tooltips being more sticky than intended.

--

Version: 1.92.1 (user setup)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by gjsjohnmurray** [comment]
@MohenjoDaro https://github.com/microsoft/vscode/issues/221607#issuecomment-2267397977 supports your theory.

**Comment by aiday-mar** [comment]
Hi @MohenjoDaro thanks a lot for finding this error in the code. If you would like you can make a PR containing this finding, so we can merge your fix and you can participate as a community member into the project. If not I will make the fix that you write :). Thanks for the catch.

**Comment by MohenjoDaro** [comment]
@aiday-mar If you could make the fix, that'd be great, I'm not very familiar with git

**Comment by aiday-mar** [comment]
Sounds good thanks again

**Comment by aiday-mar** [comment]
Hi the PR that fixes this issue is here https://github.com/microsoft/vscode/pull/225687. When this is merged, you should see the correct behavior in tomorrow's insiders release or next month's stable release. Please let me know if this is not the case and you continue seeing this issue.
