### ISSUE TITLE
Language Selection Mode not working

### ISSUE THREAD

**Issue by AbdulRehman908** [microsoft/vscode#221670]
Type: <b>Bug</b>

I can't convert from HTML to JSX. The option for language selection mode is not available or missing in my react app

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.96GB free)|
|Process Argv|C:\\Users\\PC\\Desktop\\Enriched Life Services --crash-reporter-id bfef7efc-e086-420b-8f79-7e597dd4bf33|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
blackbox|Bla|1.3.62
simple-react-hooks-snippets|bry|1.0.0
simple-react-snippets|bur|1.2.8
npm-intellisense|chr|1.4.5
vscode-eslint|dba|3.0.11
es7-react-js-snippets|dsz|4.4.3
vscode-babel-coloring|dza|0.0.4
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
copilot|Git|1.213.0
copilot-chat|Git|0.17.1
vscode-language-babel|mgm|0.0.40
mongodb-vscode|mon|1.6.0
vsliveshare|ms-|1.0.5932
vscode-react-native|msj|1.13.0
java|red|1.32.0
html-to-jsx|ria|0.0.1
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
js-jsx-snippets|sky|11.1.3
autoimport|ste|1.5.4
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.23.7
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.2024070902
vscode-icons|vsc|12.8.0
quokka-vscode|Wal|1.0.647
es7-react-js-snippets|woo|2.5.1
JavaScriptSnippets|xab|1.8.0
vscode-react|zha|0.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31094925
refactort:31093865

```

</details>

**Comment by aeschli** [comment]
I don't think we have a tool that converts HTML to JSX. Can you explain more?
Is this a feature request?
