### ISSUE TITLE
kill terminal and close panel do the same thing.

### ISSUE THREAD

**Issue by highdali** [Microsoft/vscode#22167]
- VSCode Version: 1.10.1
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:
---
Why do`kill terminal` and `Close panel` in the console panel(,problems,output,debug console, **terminal**) do the same thing? (it does *closing panel*)
In the terminal mode, i thought icon of `kill terminal` means `clear terminal`.

**Comment by Tyriar** [comment]
Kill terminal kills the terminal process and the closed the panel if it was the only terminal (you can have multiple at one).
Close panel will just close the panel while keeping the terminal process running.
