### ISSUE TITLE
Odd state if sidebar is toggled while terminal inline chat is responding

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#221608]
1. Ask inline chat in the terminal a question
2. Realize you want to see more contents and toggle the sidebar while it's responding
3. It closes when you do (😕), use cmd+I to reopen it
4. You get this odd state:

<img width="671" alt="image" src="https://github.com/user-attachments/assets/6703d46c-2e5f-4cda-9192-a6758cd872b2">

**Comment by legomushroom** [comment]
The issue didn't repro on stable 1.96.0, Copilot Chat 0.23.0 on Mac OSx today, so I assume it is fixed by now. Please reopen if you still see the issue.
