### ISSUE TITLE
VScode terminal with powershell is unresponsive

### ISSUE THREAD

**Issue by ArthurKun21** [microsoft/vscode#221631]
Type: <b>Bug</b>

1. Create new python project with poetry
2. Open the terminal
3. Create the virtual environment with `virtualenvs.in-project = true` with python poetry
4. Select the create virtual environment as the default python env
5. Close the terminal and open it again
6. Add new library and it will hang
  poetry add rich <- this was supposed to happened
  poetry add r <- hangs up here

Another thing
I was also using git commands and was also able to reproduce this like doing normal git command stuff like git rebase but unable to continue the typing as it got stack

This is the error on the Developer tools
```js
workbench.desktop.main.js:sourcemap:1780 Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
    at new h (workbench.desktop.main.js:sourcemap:1780:28015)
    at f.o (workbench.desktop.main.js:sourcemap:655:1608)
    at f.createInstance (workbench.desktop.main.js:sourcemap:655:1100)
    at o.$ (workbench.desktop.main.js:sourcemap:1781:6794)
    at o.Z (workbench.desktop.main.js:sourcemap:1781:6385)
    at o.M (workbench.desktop.main.js:sourcemap:1781:4760)
    at o.L (workbench.desktop.main.js:sourcemap:1781:3896)
    at t.OscHandler._handler (workbench.desktop.main.js:sourcemap:1781:2759)
    at t.OscHandler.end (OscParser.ts:223:18)
    at t.OscParser.end (OscParser.ts:159:45)
    at c.parse (EscapeSequenceParser.ts:777:43)
    at k.parse (InputHandler.ts:486:35)
    at n._action (CoreTerminal.ts:146:99)
    at n._innerWrite (WriteBuffer.ts:164:27)
    at WriteBuffer.ts:124:29
```

```json
"terminal.explorerKind": "external",
"terminal.integrated.defaultLocation": "editor"
```

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (1.77GB free)|
|Process Argv|--crash-reporter-id f2d7c226-0dba-4a11-8d60-a9c5f90055c2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
ruff|cha|2024.30.0
gitignore|cod|0.9.0
githistory|don|0.6.20
python-environment-manager|don|1.2.4
prettier-vscode|esb|10.4.0
copilot|Git|1.213.0
copilot-chat|Git|0.17.1
todo-tree|Gru|0.0.226
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.1
vscode-kubernetes-tools|ms-|1.3.16
black-formatter|ms-|2024.3.11501016
debugpy|ms-|2024.9.11931011
python|ms-|2024.11.2024071203
vscode-pylance|ms-|2024.7.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.377.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vscode-typescript-next|ms-|5.6.20240712
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
vscode-yaml|red|1.15.0
code-spell-checker|str|3.0.1
even-better-toml|tam|0.19.2
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31094925

```

</details>

**Comment by meganrogge** [comment]
a gif would be helpful - if you can repro with just git commands, that would be better than the python ones to rule out any involvement there. thanks

**Comment by meganrogge** [comment]
do you have `terminal.integrated.suggest.enabled` enabled?

**Comment by Tyriar** [comment]
Closing as this is pretty stale at this point
