### ISSUE TITLE
Visual Code studio in macOS M1 Pro gets a too resources impact in the system

### ISSUE THREAD

**Issue by sincorchetes** [microsoft/vscode#221633]
Does this issue occur when all extensions are disabled?: **YES**

- VS Code Version: 1.91.1
- OS Version: macOS Sonoma 14.5

Steps to Reproduce:

1. Open VSCode (with or without extensions)
2. Open a project (optional)
3. Run a Python code that outputs more lines.
4. Check the terminal you cannot type in.
5. Open a terminal and run htop, you get 100% CPU expenses.

**Comment by legomushroom** [comment]
Cannot repro this today on stable 1.96.0 on Mac OSx 15.1 so closing as fixed. If you still experiencing this, please reopen, providing specs of your machine and type of shell you are using so we can investigate effectively.
