### ISSUE TITLE
Hash # in a folder name leads to error during Live Share

### ISSUE THREAD

**Issue by RicardoNiepel** [microsoft/vscode#221635]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.1 (user setup)
- OS Version: Windows_NT x64 10.0.22631

**Steps to Reproduce:**
1. Use a hash '#' inside a folder name
2. Start a Live Share session, share a file which is under the folder containing '#' inside the name
3. Opening this Live Share session in the web leads to the error message "file could not be opened"

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the LiveShare extension. Please file a new issue for it: https://github.com/MicrosoftDocs/live-share/issues
