### ISSUE TITLE
Add setting to change the reply font

### ISSUE THREAD

**Issue by jmg-duarte** [microsoft/vscode#221699]
First of all, apologies for the small screenshot, I can't share more as it's a private repo.

![Screenshot 2024-07-04 at 11 07 50](https://github.com/microsoft/vscode-pull-request-github/assets/15343819/6f46ca15-5e4a-487b-be37-a6f05ce4199b)

It does illustrate my point, I use Berkeley Mono for the code and would like to use it for the replies as well, since they're already using the monospaced Menlo.

I searched for a `githubPullRequests.replyFont` or similar and couldn't find anything. Outside the extension, the same.

**Comment by alexr00** [comment]
Let's start by just respecting the setting `editor.fontFamily` in the comments editor (we probably should have always done this). If we need to, we can add a separate comment editor font setting later.

**Comment by jmg-duarte** [comment]
> Let's start by just respecting the setting editor.fontFamily in the comments editor

Works for me tbh, thanks!
