### ISSUE TITLE
Editor Limit does not work.

### ISSUE THREAD

**Issue by MTtheman** [microsoft/vscode#221611]
1. I can't open more than one editor tab at once.
2. Editor Limit setting does not work.

**Comment by gjsjohnmurray** [comment]
Do you know about Preview Mode?

https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

**Comment by MTtheman** [comment]
> Do you know about Preview Mode?
> 
> https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
 I didn't, and it fixed it. Thanks!
