### ISSUE TITLE
Sometimes, Buttons in Open Editors don't work at all. 

### ISSUE THREAD

**Issue by pouyakary** [microsoft/vscode#221627]
Type: <b>Bug</b>

Sometimes---and I have not figured out why---the buttons in "Open Editors" section don't work when I try to close tabs. This is happening since the 2 last releases I guess.

https://github.com/user-attachments/assets/3fcdee63-adc1-4f67-9bb1-9a6426755789

Sorry but I haven't found why it happens. It just seem to happen every 1/3 or even 2/3 of the times I open the editor.

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:46.768Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
raku-navigator|bsc|0.3.2
dart-code|Dar|3.92.0
flutter|Dar|3.93.20240702
vscode-pull-request-github|Git|0.92.0
arendelle|kar|2.1.7
comment|kar|23.3.0
idf|kar|3.0.0
justifier|kar|0.0.13
karyscript|kar|0.0.5
moves|kar|1.0.1
pageman|kar|1.2.4
righteous|kar|2.1.3
theme-karyfoundation-themes|kar|35.0.0
virtuous-vscode|kar|0.0.7
typst-lsp|nva|0.13.0
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
theme-check-vscode|Sho|2.4.2
code-spell-checker|str|3.0.1
tldraw-vscode|tld|2.2.0
pdf|tom|1.2.2

</details>

**Comment by benibenj** [comment]
Do you by chance work with notebooks? I've heard someone mention the close did not work for notebooks for him so I wonder if the problem is with notebooks or if the button does not work for general files.

**Comment by pouyakary** [comment]
@benibenj no I haven't used notebooks at all actually, and sadly I cannot find what makes it happen.

**Comment by benibenj** [comment]
I just remembered, I think I've fixed this issue last week in this PR: https://github.com/microsoft/vscode/pull/221131. The fix should be available in the newest [insiders](https://code.visualstudio.com/insiders/) version.
