### ISSUE TITLE
Frosted screen after latest Update

### ISSUE THREAD

**Issue by sudheerkaushik** [microsoft/vscode#221615]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

VScode screen turns to frosted screen if left idle.

![image](https://github.com/user-attachments/assets/9b959200-944b-4816-9dcd-dc8aa4edcf97)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/124226

Please disable hw acceleration in the application as workaround,
```
* Command Palette search for "Configure Runtime Arguments"
* Set disable-hardware-acceleration: true
* Restart
```
