### ISSUE TITLE
VSCode hangs when working with .code-workspace files

### ISSUE THREAD

**Issue by daeh** [microsoft/vscode#221676]
Type: <b>Bug</b>

I haven't pinned down the conditions precisely, but it has happened around 10 times over the last 2-3 months. I'll create, open, or save a *.code-workspace file, and something hangs. I can still cycle between the windows of open projects, so it's not like the application itself is frozen (and MacOS doesn't think that VSCode has frozen). And I can open the File menu, but I can't quit the app (it's greyed out file menu and clicking "quit" in the contextual menu of the application in the dock has no effect). And I can't interact with any of the windows open in vscode --- while I can cycle between them, i can't highlight text, change tabs or type. 

I think that it usually happens when I'm working with a new *.code-workspace file

Thanks!

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:46.768Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|15, 13, 10|
|Memory (System)|32.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id be529c7e-98ce-4bb8-8c48-79eeb363c861|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.4.0
TabOut|alb|0.2.2
Bookmarks|ale|13.5.0
project-manager|ale|12.8.0
line-jumper|ale|0.1.0
git-temporal-vscode|bee|1.0.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.23.1
markdown-preview-github-styles|bie|2.0.4
markdown-yaml-preamble|bie|0.1.0
shell-syntax|bma|1.0.5
ruff|cha|2024.30.0
bracket-select|chu|2.0.2
codediagram|Cod|0.0.65
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
vscode-docker-syntax|dun|0.1.5
gitlens|eam|15.2.0
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|10.4.0
vscode-postfix-python|fil|0.1.3
copilot|Git|1.213.0
copilot-chat|Git|0.17.1
todo-tree|Gru|0.0.226
stan-vscode|iva|0.2.4
git-tree-compare|let|1.16.0
highlight-regex|mbl|1.2.2
highlight-on-copy|mgu|1.1.4
git-graph|mhu|1.30.0
regexsnippets|Mon|1.0.2
anaconda-extension-pack|ms-|1.0.1
debugpy|ms-|2024.8.0
pylint|ms-|2023.10.1
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
datawrangler|ms-|1.4.2
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-explorer|ms-|0.4.3
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
docthis|oou|0.8.2
select-compare-tabs|out|1.0.3
vscode-subword-navigation|ow|1.2.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.15.0
vscode-paste-and-indent|Rub|0.0.8
semanticdiff|sem|0.9.0
mark-jump|spy|0.9.0
code-spell-checker|str|3.0.1
unique-window-colors|stu|1.0.51
markdowntable|Tak|0.12.0
even-better-toml|tam|0.19.2
python-extended-snippets|tus|0.0.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-icons|vsc|12.8.0
pretty-ts-errors|Yoa|0.5.4

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by daeh** [comment]
Hi — Thanks for the response. The issue is pretty sporadic and I haven't found a way to reliably reproduce it. If I can identify a way to invoke it, I'll definitely check whether can extension is the culprit. Thanks!
