### ISSUE TITLE
Mac OS X: Change shell for integrated terminal

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#22161]
I'd like to change the shell for the integrated terminal, without changing my default shell, on Mac OS X. I'd like to keep ZSH as my default shell, but change my integrated terminal to use PowerShell. From the documentation, it seems that this capability is exclusive to the Windows version of VSCode. Can this capability be added to Linux and Mac versions of VSCode as well?

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by Tyriar** [comment]
You can do this now:

```js
"terminal.integrated.shell.osx": "/path/to/powershell"
```

**Comment by pcgeek86** [comment]
Just tested this out, works great.
