### ISSUE TITLE
Visual Studio Code is down

### ISSUE THREAD

**Issue by amirzarbakhsh** [microsoft/vscode#221658]
My operating system is macOS Big Sur Version 11.7.10 I don't know what happened but since 3-4 days ago "Visual Studio Code" stopped working on my system! This is so weird, I haven't installed any new software on the good system!

I have only one solution and that is to install the old version of Visual Studio Code, but when I turn off and on my operating system, everything goes back to the previous state and I have to install Visual Studio Code again. In addition, in this solution, many of the possibilities of Visual Studio Code do not work and it is not a useful solution.

(The same thing happened to Anaconda-Navigator on my system and it has not been running for a long time!)

I installed the latest version of Visual Studio Code on my system and I still have the same problem!

(I used visual studio for python.)

Does anyone know the reason for this strange event!?

**Comment by gjsjohnmurray** [comment]
Please install 1.91.1 which fixes the macOS problem.

**Comment by amirzarbakhsh** [comment]
> Please install 1.91.1 which fixes the macOS problem.

Do you mean I install version 1.91.1 of Visual Studio Code

**Comment by gjsjohnmurray** [comment]
Yes

**Comment by rzhao271** [comment]
@amirzarbakhsh are you still seeing this issue after installing VS Code 1.91.1 or newer?
