### ISSUE TITLE
MORE INPUT PROBLEMS

### ISSUE THREAD

**Issue by RJS183** [microsoft/vscode#221678]
Type: <b>Bug</b>

{
	"name": "ModuleNotFoundError",
	"message": "No module named 'sklearn'",
	"stack": "---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[12], line 1
----> 1 import sklearn
      2 #3from sklearn.datasets import fetch_california_housing
      3 #import matplotlib.pyplot as plt
      4 #import pandas as pd
      5 #housing = fetch_california_housing()

ModuleNotFoundError: No module named 'sklearn'"
}

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.83GB (1.03GB free)|
|Process Argv|C:\\Users\\Owner\\Documents\\Eastern\\DSC 502\\Week 6\\DSC502_Summary_and_preview.ipynb --crash-reporter-id 3ff904dd-d75c-4b2c-add3-b85ed3b885f8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
r|REd|2.8.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
legacy_priority:31094926
4930e709:31092288

```

</details>

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, based on the error message, you need to install the `sklearn` package
Please ensure you have installed this into the right Python environment

to find the environment, you can either check the kernel picker & have a look at the selected kernel (Python environment)
Or just run the following code to determine the same
```python
import sys
print(sys.executable)
```

As this isn't an issue with the extension, but an issue with the fact that the packge isn't installed, I'm closing this.
