### ISSUE TITLE
Git with GPG still fail even after using `export GPG_TTY=$(tty)` in Integrated Shell

### ISSUE THREAD

**Issue by tn-072** [microsoft/vscode#221652]
Type: <b>Bug</b>

1. Open Integrated Shell
2. `git commit -S -m "......"`, fail
3. Do 2. after `export GPG_TTY=$(tty)`, still fail
4. Do 3. in shell out of VSCode, succeed
5. Do 3. in Integrated Shell after 4., succeed

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin x64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 x 1100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.73GB free)|
|Process Argv|--crash-reporter-id 62cfa310-8df8-4e0e-a145-dbcaa17c8040|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-footnotes|bie|0.1.1
markdown-yaml-preamble|bie|0.1.0
catppuccin-vsc|Cat|3.14.0
catppuccin-vsc-icons|Cat|1.13.0
linter-gfortran|for|3.2.0
latex-workshop|Jam|10.1.0
vscode-clangd|llv|0.1.28
csdevkit|ms-|1.8.14
csharp|ms-|2.34.12
dotnet-maui|ms-|1.1.16
vscode-dotnet-runtime|ms-|2.0.9
vscodeintellicode-csharp|ms-|2.1.11
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.18.43
cpptools|ms-|1.20.5
hexeditor|ms-|1.10.0
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
xmake-vscode|tbo|2.3.5
cmake|twx|0.0.17
markdown-all-in-one|yzh|3.6.2

</details>

**Comment by lszomoru** [comment]
@Tyriar, does this ring a bell? Thank you!

**Comment by tn-072** [comment]
> @Tyriar, does this ring a bell? Thank you!

No.

P.S. It seems that I can't reproduce this problem now, so I close this issue.
