### ISSUE TITLE
Migrate machineId from renderer to main process

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#22169]
Follow-up on #22166

**Comment by isidorn** [comment]
@chrmarti please provide verification steps

**Comment by roblourens** [comment]
I see 

```
customEvents
| where application_Version contains "1.12" 
```

returning nothing, so my Kusto-fu must be too weak. All the openFolder events I see are from <=1.11

**Comment by chrmarti** [comment]
You might be looking at the older Kusto cluster.

**Comment by bpasero** [comment]
Looks like the same machineid reports for main and renderer now:

![image](https://cloud.githubusercontent.com/assets/900690/26675630/f5b2a040-46c4-11e7-9b36-1463d1a037ae.png)
