### ISSUE TITLE
Keyboard shortcuts are changed en masse

### ISSUE THREAD

**Issue by ac10n** [microsoft/vscode#221730]
Type: <b>Bug</b>

I've been using vscode for a long time. Now my keyboard shortcuts are changed en masse. For instance, ctrl+` no longer opens a new terminal. Almost all shortcuts are changed or removed.

I looked for settings and did not find anything related. Also looked for any extesions that might have changed these, again, no chance.

So:

1. How did this happen? I'm using vscode on windows+linux+mac, but I've not turned on sync.
2. How to fix this?

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:08:12.169Z)
OS version: Linux x64 6.9.8-200.fc40.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (32 x 400)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|30.55GB (13.76GB free)|
|Process Argv|--enable-features=UseOzonePlatform --ozone-platform=wayland --crash-reporter-id aae31f76-74e1-48d7-beaf-b93ecd51fa3f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.1.2
markdown-mermaid|bie|1.23.1
mermaid-markdown-syntax-highlighting|bpr|1.6.6
dart-code|Dar|3.92.0
flutter|Dar|3.92.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.0
vscode-solution-explorer|fer|0.8.6
copilot|Git|1.213.0
copilot-chat|Git|0.17.1
csdevkit|ms-|1.8.14
csharp|ms-|2.34.12
vscode-dotnet-runtime|ms-|2.0.9
remote-containers|ms-|0.375.1
vs-code-prettier-eslint|rve|6.0.0
svelte-vscode|sve|108.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31094925
pythonrstrctxtcf:31093870

```

</details>

**Comment by ulugbekna** [comment]
Hi :-)

Thanks for filing this issue! 

0. Have you changed possibly your keyboard layout? 

1. Could you provide at your keybindings.json file contents? (invoke command "Preferences: Open Keyboard Shortcuts (JSON)" to open it)

2. Could you please try the [following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

2.1. Run the command "Developer: Toggle Keyboard Shortcuts Troubleshooting" (you can, for example, run it from the Command Palette). 

   This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.

2.2. Press exactly the keybinding you desire
 
2.3. Check what VS Code detects 

If you are having trouble understanding the output, please feel free to paste here and we'll be happy to help ☺️

**Comment by ac10n** [comment]
Before I go into your suggestion @ulugbekna 

I uninstalled VsCode, removed `~/.vscode` and `~/.config/Code`, and reinstalled VsCode, which fixed the problem.

After logging in with copilot, things were messed up again.

**Comment by ac10n** [comment]
```~/.config/Code/User/keybindings.json
// Place your key bindings in this file to override the defaults
[
]
```

**Comment by ac10n** [comment]
This happened twice:
The problem is observed, I invoke "Developer: Toggle Keyboard Shortcuts Troubleshooting" and then then shortcuts are back! First time I thought it can be because of something else. This time I only did that and I'm back on track!

**Comment by ac10n** [comment]
OK. It happened again. This time `Developer: Toggle Keyboard Shortcuts Troubleshooting` did not fix it.

```
2024-07-18 16:56:24.903 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-07-18 16:56:24.903 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2024-07-18 16:56:24.903 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
2024-07-18 16:56:24.903 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
2024-07-18 16:56:24.903 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2024-07-18 16:56:25.123 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-07-18 16:56:25.123 [info] [KeybindingService]: | Resolving ctrl+[Backquote]
2024-07-18 16:56:25.123 [info] [KeybindingService]: \ No keybinding entries.
2024-07-18 16:56:25.123 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: Backquote, keyCode: 192, key: Unidentified
2024-07-18 16:56:25.123 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: Backquote, keyCode: 91 ('`')
2024-07-18 16:56:25.123 [info] [KeybindingService]: | Resolving ctrl+[Backquote]
2024-07-18 16:56:25.123 [info] [KeybindingService]: \ No keybinding entries.
2024-07-18 16:56:25.304 [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.
```

**Comment by ac10n** [comment]
I'm still having this problem. It's more of a transient nature. I've been unable to guess what are the exact conditions (or even if there are).
Can someone help? This really causes hiccups while working.

**Comment by adsick** [comment]
Hi, I've just had a very similar issue. I think the root cause (and what we have in common) is `wayland`. Recently I managed to switch from running VSCode via XWayland fallback (current default) to native Wayland.
> --enable-features=UseOzonePlatform --ozone-platform=wayland 
by the way you don't need these, you can `export ELECTRON_OZONE_PLATFORM_HINT=auto` in your `.bashrc`

It looks like when you switch layouts (I use Dvorak + two cyrillic layouts) some state breaks and keybinding malfunctions. I also have <code>Ctrl+`</code> not opening the terminal when it happens.
