### ISSUE TITLE
Request for Database Permissions

### ISSUE THREAD

**Issue by Mansi-mp123** [microsoft/vscode#221725]
Hello,

I am currently working on Lab 7 StayWell and have encountered an issue that requires additional database permissions. The specific permission I need is the ability to use the GRANT command.

Having this permission will allow me to run my code and complete my task.

Could you please assist in granting me this permission or guide me on how to obtain it?

Thank you for your time and assistance.

Best, 
Mansi

Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
Please use the course support channel.

**Comment by andreamah** [comment]
> Please use the course support channel.

^ please do as mentioned here
