### ISSUE TITLE
Publish ARM64 Windows server

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#221755]
It appears that this is possible now, and we should consider adopting this in VS Code

(https://vscodeteam.slack.com/archives/C03ERNTC03X/p1720049557043389?thread_ts=1701362534.308269&cid=C03ERNTC03X)

**Comment by joshspicer** [comment]
There is community interest: https://github.com/microsoft/vscode-remote-release/issues/9677#issuecomment-2250042628

**Comment by OkGoDoIt** [comment]
👍 Please add this!

**Comment by deepak1556** [comment]
**Steps for verification:**

* Connect to Windows arm64 using the latest pre-release of SSH extension (https://github.com/microsoft/vscode/wiki/Sanity-Check#windows-using-remote-ssh)
* Verify that connection is successful
* Use `dumpin /headers <path-to-remote-executable>` or similar tool to confirm that executable is of `arm64` architecture.
