### ISSUE TITLE
Too much battery drain on Macbook Pro (M1 Pro)

### ISSUE THREAD

**Issue by koushikb19** [microsoft/vscode#221706]
Type: <b>Bug</b>

I'm using VSCode on my 14" Macbook Pro (M1 Pro) and there is too much battery drain on VS code since the last couple of days. Even on standby mode. My laptop had discharged because of this

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 5, 7|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 8fdebaa2-4c93-44ad-8319-623cc539b442|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
ng-template|Ang|18.1.2
npm-intellisense|chr|1.4.5
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.0
vscode-html-css|ecm|2.0.10
vsc-material-theme|Equ|34.4.0
vsc-material-theme-icons|equ|3.6.1
auto-rename-tag|for|0.1.10
copilot|Git|1.213.0
copilot-chat|Git|0.17.1
npm|ide|1.7.4
Angular2|joh|16.0.1
vscode-peacock|joh|4.2.2
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
remote-containers|ms-|0.375.1
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
gremlins|nho|0.26.0
svelte-autoimport|piv|1.0.4
material-icon-theme|PKi|5.5.0
vscode-css-peek|pra|4.4.1
code-spell-checker|str|3.0.1
svelte-vscode|sve|108.5.4
JavaScriptSnippets|xab|1.8.0
city-lights-icon-vsc|Yum|1.1.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
legacy_priority:31094926
pythonrstrctxt:31093869
0c838689:31092287

```

</details>

**Comment by JayaSurya-27** [comment]
I am also  experiencing the same issue , any fix ?

**Comment by jonathanbodart** [comment]
Experiencing the same, specifically after installing the Copilot extension at my end

**Comment by mh-saeed** [comment]
I'm also experiencing same issue in my MacBook Pro (M2 Pro)!

**Comment by deepak1556** [comment]
Please share the full commandline of the process that is causing the cpu usage, it would help us to provide better debugging steps.
