### ISSUE TITLE
HTML "script" tags improperly scoped

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#22176]
- VSCode Version: Code - Insiders 1.11.0-insider (5e9357bd5111eacf2b8fb39455c8afb5a42d632f, 2017-03-07T07:07:17.647Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.5.1|
|sort-lines|Tyriar|1.2.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.12.0|
|project-manager|alefragnani|0.13.3|
|nord-visual-studio-code|arcticicestudio|0.1.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.7|
|tslint|eg2|0.8.1|
|Angular2|johnpapa|2.0.3|
|vscode-icon-theme|jtlowe|1.5.0|
|theme-karyfoundation-themes|karyfoundation|11.0.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-csscomb|mrmlnc|4.0.1|
|vscode-stylefmt|mrmlnc|2.2.3|
|stylelint|shinnn|0.23.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|1.2.0|
|theme-tesla|smlombardi|6.0.0|
|vscode-todo-highlight|wayou|0.4.5|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

Please see attached screenshots:  the `=` for attributes is not the same color for `script` tags as all other html tags.

This is because all other tags they are scoped `meta.tag.inline.any.html`, whilst script tags are only `text.html.basic`. This is a bug IMHO.

Script tag:
![screen shot 2017-03-07 at 2 53 38 pm](https://cloud.githubusercontent.com/assets/835148/23675150/5ffddbc6-0346-11e7-9a8b-d6c99e7f3b57.png)

Sample other tag:
![screen shot 2017-03-07 at 2 54 07 pm](https://cloud.githubusercontent.com/assets/835148/23675162/6d6895ee-0346-11e7-8f7b-a7fb7f731a0a.png)

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#52
