### ISSUE TITLE
extension contributes languages icon not loaded

### ISSUE THREAD

**Issue by max529** [microsoft/vscode#221741]
- Version: 1.91.1 (user setup)
- Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
- Date: 2024-07-09T22:06:49.809Z
- Electron: 29.4.0
- ElectronBuildId: 9728852
- Chromium: 122.0.6261.156
- Node.js: 20.9.0
- V8: 12.2.281.27-electron.0
- OS: Windows_NT x64 10.0.19045

I'm the maintainer of Aventus extension. After the update from 1.90.X to 1.91.1 all icons set inside contribute.languages section aren't loaded.

This is the contribute section :

```json
"contributes": {
  "languages": [
    {
      "id": "Aventus HTML",
      "extensions": [
        ".wcv.avt"
      ],
      "configuration": "./syntaxes/html-language-configuration.json",
      "icon": {
        "light": "./icons/aventus-view.png",
        "dark": "./icons/aventus-view.png"
      }
    }
  ]
}
```
I can't find a section into to release that can explain why it's working on 1.90.X and not on 1.91.1

**Comment by daviddossett** [comment]
@sandy081 any ideas?

**Comment by max529** [comment]
I downloaded the 1.92.1. My icon files still don't appear. If you need any further information, please do not hesitate to contact me.

**Comment by sandy081** [comment]
@daviddossett Unsure.

@alexdima / @aeschli should be know this

**Comment by aeschli** [comment]
Seems to work in the latest.

Tested on 1.93.1 and 1.94 insiders
![Image](https://github.com/user-attachments/assets/bc62a9f0-a59a-4299-b5fa-aa8b87bb127c)
