### ISSUE TITLE
File-breaking error in VS Code editor

### ISSUE THREAD

**Issue by Viridimontanus** [microsoft/vscode#221708]
I've twice now encountered a file-breaking error with VS Code. The only extensions I have installed are "Live Server (Five Server)" and the XML one. Since I installed the former extension some weeks ago but the bug has only occurred in the recent days, I can't say whether it has to do anything with it, i. e. with its live status, or not.

The issue is: for the second time now, a file I had been working on in VS Code has broken so fully that it not only can't be executed or opened/edited but it can't even be deleted anymore (it seems I'd need to fully format my USB drive if I wanted to delete those two files). So far it has always happened when I left my pc for a few minutes, not even enough for it to enter idle mode, leaving the file open in VS Code. It happened both with a js file and with an html one. When I returned, I couldn't save or execute it anymore – luckily, it was still possible to save everything under a new name, leaving me with the un-deletable old file separately.

Google is quite silent about this specific bug so I thought I'd ask here.

Does this issue occur when all extensions are disabled?: Yes/No (not sure)

- VS Code Version: 1.91.1
- OS Version: Windows 11 Education

Steps to Reproduce:

1. (probably, not sure yet) leave a file open in editor for too long

**Comment by bpasero** [comment]
Steps to reproduce reliably?
