### ISSUE TITLE
Prompt to pick TS version when both are same value

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#22171]
- VSCode Version: 
![image](https://cloud.githubusercontent.com/assets/1487073/23673336/c6dd3942-0326-11e7-9fd2-fcec0f6d3e46.png)

- OS Version: MacOS

Steps to Reproduce:

1. install typescript v 2.2.1 globally on your machine
2. in a new folder, run `yo code`
3. `npm install && code-insiders .`

Result:

![image](https://cloud.githubusercontent.com/assets/1487073/23673324/b7225708-0326-11e7-94f6-22affc16bd20.png)

I don't understand why I need to pick since they are both the same value...

**Comment by mjbvz** [comment]
This is the expected behavior when a workspace contains a custom typescript version that happens to match the bundled typescript version. We still present the choice here, since users may upgrade the workspace version separately

**Comment by chrisdias** [comment]
This prompt only shows up if there is a `typescript.tsdk` setting in `settings.json` for the workspace. I was using an older version of `generator-code` to scaffold an extension, which at the time included the `.tsdk` setting. Upgrading `generator-code` (`npm install -g generator-code`) fixes this issue.
