### ISSUE TITLE
Visual Studio Code Insiders Not updating hence some extensions not working optimally.

### ISSUE THREAD

**Issue by Peter-Kibet** [microsoft/vscode#221758]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  14
- OS Version:  Windows 11 insiders

Steps to Reproduce:

1. Have a user-type installation of VS Code

2. Check for updates

3. See (1) badge on gearwheel

4. Use its "Install Update... (1)" option.

5. Receive a UAC dialog and approve it.

6. See a VS Code notification.
7. Click "Update Now"
8. VS Code Insiders closes and an error messagebox appears:

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/issues/220999

**Comment by Peter-Kibet** [comment]
I got a solution to fix this.
