### ISSUE TITLE
Getting Error while updating the vs code

### ISSUE THREAD

**Issue by MandarSant** [microsoft/vscode#221788]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Latest
- OS Version: Win 11 latest

Steps to Reproduce:

1. Click on update in vscode

Here are the SS of error
![Vscode1](https://github.com/user-attachments/assets/b1e50ea7-3b98-4f92-bd17-3f21e486ddef)
![VScode2](https://github.com/user-attachments/assets/d4afcb78-c508-4cb1-bcac-c29c161b6310)

**Comment by MandarSant** [comment]
@joaomoreno @VSCodeTriageBot No any reply / update

**Comment by RedCMD** [comment]
what do the log files contain?

**Comment by MandarSant** [comment]
> what do the log files contain?

Aug 03 11:26:38.224 INFO Starting: C:\Users\manda\AppData\Local\Programs\Microsoft VS Code\Code.exe, false, Updating Visual Studio Code...
Aug 03 11:26:38.224 INFO Checking for running Code.exe processes... (attempt 1)
Aug 03 11:26:38.231 INFO Code.exe is not running
Aug 03 11:26:38.232 INFO Checking for possible conflicting running processes... (attempt 1)
Aug 03 11:26:38.237 INFO Inno Updater v0.11.1
Aug 03 11:26:38.237 INFO Starting update, silent = false
Aug 03 11:26:38.265 INFO do_update: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe", _
Aug 03 11:26:38.265 INFO move_update: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\unins000.dat", _
Aug 03 11:26:38.266 INFO Reading directory: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code"
Aug 03 11:26:38.266 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\chrome_100_percent.pak" (attempt 1)
Aug 03 11:26:38.266 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\chrome_200_percent.pak" (attempt 1)
Aug 03 11:26:38.266 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 1)
Aug 03 11:26:38.266 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.VisualElementsManifest.xml" (attempt 1)
Aug 03 11:26:38.266 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\d3dcompiler_47.dll" (attempt 1)
Aug 03 11:26:38.266 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\debug.log" (attempt 1)
Aug 03 11:26:38.266 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\ffmpeg.dll" (attempt 1)
Aug 03 11:26:38.266 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 1)
Aug 03 11:26:38.316 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 2)
Aug 03 11:26:38.517 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 3)
Aug 03 11:26:38.968 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 4)
Aug 03 11:26:39.768 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 5)
Aug 03 11:26:41.019 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 6)
Aug 03 11:26:42.820 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 7)
Aug 03 11:26:45.271 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 8)
Aug 03 11:26:48.471 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 9)
Aug 03 11:26:52.522 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 10)
Aug 03 11:26:57.523 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 11)
Aug 03 11:27:03.573 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 12)
Aug 03 11:27:10.774 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 13)
Aug 03 11:27:19.225 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 14)
Aug 03 11:27:29.026 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 15)
Aug 03 11:27:40.277 INFO Get file handle: "C:\\Users\\manda\\AppData\\Local\\Programs\\Microsoft VS Code\\history.log" (attempt 16)
Aug 03 11:30:17.976 ERRO Failed to create file handle: Access is denied.
