### ISSUE TITLE
Typing is slow and deletes characters 

### ISSUE THREAD

**Issue by joneuhauser** [microsoft/vscode#221720]
Type: <b>Performance Issue</b>

Since updating to Ubuntu 24.04, most operations in vscode on Wayland take a second or two to even react. This includes typing - letters often show up, then get deleted and reappear 2 seconds later, as for example in this box. 

Also tried a current code-insiders, with no change.

Disabling hardware acceleration makes no difference.

Works fine on Xorg.

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:08:12.169Z)
OS version: Linux x64 6.8.0-35-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 4092)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|11, 5, 3|
|Memory (System)|62.71GB (56.76GB free)|
|Process Argv|--crash-reporter-id 95802a40-5152-4bb1-8f95-66008618a866|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-wayland|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-wayland|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   128	 67232	code main
    0	     0	 67236	   zygote
    0	   193	 67271	     gpu-process
    0	     0	 67308	       broker
    0	     0	 67237	   zygote
    0	     0	 67239	     zygote
    0	   385	 67297	window [1] (● hello world this is a test • Untitled-1 - rm1705 - Visual Studio Code)
    0	    64	 67881	window [2] (Issue Reporter)
    0	     0	 67276	   utility-network-service
    0	   128	 67388	shared-process
    1	   193	 67408	extensionHost [1]
    0	    64	 67824	     /usr/share/code/code /usr/share/code/resources/app/extensions/markdown-language-features/server/dist/node/workerMain --node-ipc --clientProcessId=67408
    2	    64	 67426	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● hello world this is a test • Untitled-1 - rm1705 - Visual Studio Code)
|    Folder (rm1705): more than 23314 files
|      File types: o(2339) page(1514) html(1286) h(1217) c(856) png(556)
|                  cpp(473) md5(441) map(438) lo(415)
|      Conf files: makefile(103) cmake(57) settings.json(4);
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-de|MS-|1.91.2024071009

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31094925

```

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/212430
