### ISSUE TITLE
Include Hierarchy

### ISSUE THREAD

**Issue by ecstrema** [microsoft/vscode#221703]
I have been migrating a few projects to CMake lately, and I've found Visual Studio's include hierarchy to be very very helpful.

In general, similarly to call the call hierarchy, knowing who includes what and why is very useful for debugging, especially when you have multiple headers with the same name and other such issues.

Here's a screenshot of [include file hierarchy viewer](https://www.codeproject.com/Articles/3478/Include-File-Hierarchy-Viewer)

![image](https://github.com/user-attachments/assets/bd77aed5-9e30-40b3-b67e-22c04b722a2c)

Also, as includes are not particular to a single language, I believe this should be part of vscode (or maybe the language server protocol) and not specific to a particular language extension.

Request: get a similar import/include/require/use hierarchy in vscode

**Comment by jrieken** [comment]
VS Code has a call and type hierarchy but it depends on extension support. Please report this issue against the corresponding language extension, e.g TypeScript and Java have this

**Comment by ecstrema** [comment]
There may be some misunderstanding here: I am not talking about a call or a type hierarchy, but specifically an _include/import_ hierarchy.

You see which files imports which other files.
