### ISSUE TITLE
column breakpoints displayed when i edit a line

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#22172]
- VSCode Version:
![image](https://cloud.githubusercontent.com/assets/1487073/23673465/3f274474-0327-11e7-951e-b796d2903aa4.png)

- OS Version: MacOS

Steps to Reproduce:

1. `yo code`
2. `npm install && code-insiders .`
3. open `extension.ts`
4. put breakpoint on line 17 (`let disposable = vscode.commands.registerCommand...`
5. `F5` to run
6. In development instance, press F1 and run Hello World command
7. Hit breakpoint
8. Step
9. Put breakpoint on line 22 (`vscode.window.showInformationMessage...`)
10. Press `F5`, hit breakpoint, press `F5` again to continue
11. Stop debugging
12. put cursor at end of line 17 in `extension.ts`, press ENTER

Result:

![image](https://cloud.githubusercontent.com/assets/1487073/23673457/37f11cc0-0327-11e7-9242-56fb86ecb4a8.png)

I get this a lot when debugging and editing an extension in TypeScript, not just in this single scenario.

**Comment by chrisdias** [comment]
`node --version`
`v6.3.1`

**Comment by isidorn** [comment]
@chrisdias thank you for the detailed steps! I was able to find and fix the issue.

For future keep in mind that for us it is easiest to get the smallest number of steps which reproduce always the issue, in this particular scneario it was the follwoing
1. add breakpoint on a line
2. press enter before that line -> notice the breakpoint inline decoration

I am not trying to be an asshole here but just trying to improve your bug filling process 😇

**Comment by chrisdias** [comment]
@isidorn sorry for the number of steps... i didn't realize it was that simple. i tried a bunch of different ways to make it happen and the flow that i came up with was reproducible, so i captured it in detail to make it easier for you to repeat.

**Comment by isidorn** [comment]
@chrisdias thanks, no need to be sorry I was simply trying to make us better in the future.
