### ISSUE TITLE
Simple Browser is not working inside vscode.dev

### ISSUE THREAD

**Issue by aleleba** [microsoft/vscode#221715]
I would like to show in simple browser my dev tunnel url of the service I am developing, but simple browser is not working on vscode.dev

**Comment by mjbvz** [comment]
Try adding a `Cross-Origin-Resource-Policy` header to your service. We enabled this feature on vscode.dev so all embedding content must also have this header

**Comment by aleleba** [comment]
Already tested like that and not working.
<img width="1106" alt="Captura de pantalla 2024-07-15 a la(s) 12 38 53 p  m" src="https://github.com/user-attachments/assets/86feebf5-8b14-4d00-8b44-2a9c427078a6">

**Comment by mjbvz** [comment]
Check the network tab in the browser dev tools too. It will explain why the content isn't being loaded
