### ISSUE TITLE
Color coded project identification

### ISSUE THREAD

**Issue by Thomastasa** [Microsoft/vscode#22170]
Hi, it would be awesome if there was some way to easily identify which open VSCODE window is which project.  Preferably with a color coding system similar to how the bottom git bar is colored.  

_Top Bar_
Perhaps the top bar with the project name / file name could be utilized to change the background color. Maybe the user settings could implement something like: `"window.titleBar": [ { "path": "/project/location", "bar_color": "#5a6b7c", "font_color": "#ffffff" } ]` which defaults to the current (based of theme?) color settings.

_Side Bar_
Or perhaps colorize the side bar which houses Explorer, Search, Git, etc. it could use a similar implementation: `"window.sideBar": [ { "path": "/project/location", "bar_color": "#5a6b7c", "icon_color": "#ffffff" } ]`

I dont know if this feature exists already in the form of an extension, i did a search but couldnt find something that matched what i needed.  If anyone knows an extension or even a value to set in the settings, i would be much appreciated.

Thank you, and keep up the good work!

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
