### ISSUE TITLE
Debugger unable to attach to node process (node version 0.12.12)

### ISSUE THREAD

**Issue by alpeshgaglani** [Microsoft/vscode#22174]
- VSCode Version: 1.10.1
- OS Version: Windows 10

Steps to Reproduce:

1. Run a nodejs script with node version 0.12.12 (node --debug test.js)
2. Try to attach to the process
Fails to attach with error: Attach to process: cannot enable debug mode for process '2976' (Error: Command failed: node -e process._debugProcess(2976)

Attach works fine with Webstorm. However, we really want to use Node. We cannot upgrade node version, since this is the version we are stuck with on production for the next 6 months.

**Comment by weinand** [comment]
@alpeshgaglani could you share your launch configuration?

**Comment by alpeshgaglani** [comment]
{
            "name": "Attach to Process",
            "type": "node",
            "request": "attach",
            "processId": "${command:PickProcess}",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": true,
            "outFiles": [],
            "localRoot": "${workspaceRoot}",
            "remoteRoot": null
        }

**Comment by weinand** [comment]
@alpeshgaglani and it is important for you that you can attach to a process by process ID?

**Comment by alpeshgaglani** [comment]
Thanks @weinand . The default config didnt have an object with just port and localhost. It's pretty confusing to figure out - just curious: is this behavior documented?

**Comment by weinand** [comment]
@alpeshgaglani the default config (which is automatically generated when there is none) looks like this:
```js
{
	// Use IntelliSense to learn about possible Node.js debug attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${file}"
		},
		{
			"type": "node",
			"request": "attach",
			"name": "Attach to Process",
			"address": "localhost",
			"port": 5858
		}
	]
}
```

The "Attach to Process" config is exactly what you need.

This is documented here: https://code.visualstudio.com/docs/editor/node-debugging#_launch-configuration-attributes

**Comment by weinand** [comment]
Currently this feature is blocked by https://github.com/Microsoft/vscode/issues/22233
