### ISSUE TITLE
include both configure kb actions in accessible view toolbar

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#221744]
idea from @Tyriar

**Comment by meganrogge** [comment]
1. enable screen reader mode
2. focus a feature that has an accessibility help dialog, like the terminal
3. open the dialog `alt+f1` 
4. see the configure keybinding actions in the toolbar

![Image](https://github.com/user-attachments/assets/6a6ba8aa-b254-4b09-b175-e32143d9a015)

**Comment by aiday-mar** [comment]
I noticed that the first keybinding label is `Accessibility Help Configure Keybindings`, the second is `Accessibility Help Configure Assigned Keybindings`. The first label does not mention that the keybindings are not unassigned, perhaps we could add the word `unassigned` before?
