### ISSUE TITLE
Scrolling jittering after a day

### ISSUE THREAD

**Issue by rodrigogalvez** [microsoft/vscode#22175]
- VSCode Version: 1.10.1
- OS Version: Microsoft Windows [Versión 10.0.14393]

Steps to Reproduce:

1. Work one day as usual. 
2. Performing scroll with the wheel mouse and/or two fingers touch-pad gesture.
3. The source code start jittering during scrolling.

Work around:
1. open CMD.
2. Go to %appdata%\code (cd %appData%\code)
3. Delete everything but storage.json and Users\settings.json.
4. Start vscode again and works properly... for one day. On next day, the problem comes back.

Others work around:
Uninstalling, deleting everything and reinstalling the app. 
Using another account. 
Using different mouse (Bluetooth, wired, wireless, many vendors).

**Comment by csuwildcat** [comment]
I experience this as well, and it starts after just a few minutes of using VS Code. Scrolling starts out smooth, but something occurs that seems to flip it into a state where every scroll is janking, with longer and longer periods of jank until longer freezes start. I have tried disabling all extensions, but nothing helps.
