### ISSUE TITLE
Terminal should have a border at the top of the overview ruler

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#221723]
Editor:

![image](https://github.com/user-attachments/assets/a355fa99-2eff-4c14-ba97-71190ce284b1)

Terminal:

![image](https://github.com/user-attachments/assets/58a55cfb-98aa-412c-9520-8afeed51c083)

**Comment by roblourens** [comment]
I see it but I'd expect it to line up with the top of the terminal tabs list


![Image](https://github.com/user-attachments/assets/d52b7558-0c91-4688-99d5-9692c07f80aa)

**Comment by Tyriar** [comment]
@roblourens I wanted to do that but it was kind of difficult to accomplish that due to the actual terminal size not filling the height of the panel. It'll probably bug me enough at some point that I'll go down the rabbit hole
