### ISSUE TITLE
Replacement of standard icons with Material Icon Theme

### ISSUE THREAD

**Issue by okineadev** [microsoft/vscode#221714]
I think that the standard icons of vscode are rather gloomy, there are no and many icons for different types of files are missing, and I think that it would be better to replace them with [**Material Icons**](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme), because these icons are **much more** attractive, clearer and the most popular (24M+ downloads), you can see for yourself:

| Default icons | Material icons |
| :-: | :-: |
| <img alt="Default icons" src="https://github.com/user-attachments/assets/175d9ffc-a47b-4a22-9ac7-0a1106801a2a"> | <img alt="Material icons" src="https://github.com/user-attachments/assets/628e7322-fb5b-47b0-ac6e-bccb453ab5a9"> |

If they are pre-installed in **vscode**, then the editor will be **much better**

---

If you accept this update, make it so that the new default icons appear only for **new** users, and for those who currently have default icons, they will remain the same, this will be the most tolerant solution

**Comment by aeschli** [comment]
As you know, the The Material Icon Theme is not owned and maintained not by us, but by [Philipp Kief](https://marketplace.visualstudio.com/publishers/PKief) with the help of many contributors. Philipp does a fantastic job, and I can tell you that maintaining a icon theme is a lot of work. 

Making the Material theme a built-in theme would mean for us to take ownership of it. Its (a.) not what we want; we have too much on our plate already and  (ab) (I think) also Philipp isn't keen of giving away his work and loosing the freedom to improve the theme the way he likes.

It's very easy for users to install a theme from the marketplace and the sharing of work is the best model for the success of VS Code and to the benefit of all user, even, if it means a few extra clicks to install a theme.

Closing as out-of-scope

**Comment by okineadev** [comment]
> As you know, the The Material Icon Theme is not owned and maintained not by us, but by [Philipp Kief](https://marketplace.visualstudio.com/publishers/PKief) with the help of many contributors. Philipp does a fantastic job, and I can tell you that maintaining a icon theme is a lot of work.
> 
> Making the Material theme a built-in theme would mean for us to take ownership of it. Its (a.) not what we want; we have too much on our plate already and (ab) (I think) also Philipp isn't keen of giving away his work and loosing the freedom to improve the theme the way he likes.
> 
> It's very easy for users to install a theme from the marketplace and the sharing of work is the best model for the success of VS Code and to the benefit of all user, even, if it means a few extra clicks to install a theme.
> 
> Closing as out-of-scope

The thing is, I didn't say to give you the [Material Icons repository](https://github.com/material-extensions/vscode-material-icon-theme), but to make them **pre-installed**, I don't know exactly how it works for you, but I'm thinking of just putting the `.vsix` extension in the vscode build

And to have the **Material icons theme** as the default and the old default vscode icons to be pre-installed as well and can be selected at **any** time

**Comment by okineadev** [comment]
@aeschli, would it be possible to do it as written in my plan?

**Comment by aeschli** [comment]
All extensions that are built-in VS Code are open source and maintained/owned by us. There are various benefits to that, in particular we can ensure that all changes are reviewed and tested.

**Comment by okineadev** [comment]
> All extensions that are built-in VS Code are open source and maintained/owned by us. There are various benefits to that, in particular we can ensure that all changes are reviewed and tested.

First, please reopen this issue

Second, I will try to create a fork with these icons if possible

---

> All extensions that are built-in VS Code are open source and maintained/owned by us. There are various benefits to that

What are the other benefits? 🧐

And why should they be yours or should you maintain them?

**Comment by okineadev** [comment]
refresh
