### ISSUE TITLE
Shift+Alt+R keybind open Run menu instead of executing bound shortcut

### ISSUE THREAD

**Issue by seritools** [microsoft/vscode#221808]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 

```
Version: 1.92.0-insider (user setup)
Commit: 01eef174c20a0c9ce7d49db93d9dade6c684f66e
Date: 2024-07-15T12:53:32.802Z (1 day ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100
```

It worked yesterday IIRC.

- OS Version: Windows 11 10.0.26100

 
Steps to Reproduce:

1. Ensure `Reveal in File Explorer` is bound to `Shift+Alt+R`
2. Press `Shift+Alt+R`

Expected: Reveals current file in explorer
Actual: Opens the "Run" menu (like Alt+R would), as the `R` accessor (underscored letter) seems to now have precedence?

**Comment by seritools** [comment]
Hmm, there's is more broken that might be related?

I have `Reveal in Explorer View` bound to `Shift+Alt+E`:
![image](https://github.com/user-attachments/assets/deeb73f7-59ee-45da-a2b4-07d68a5aa048)


1. It doesn't work anymore
2. It _also_ doesn't open the Edit menu which I would have expected
3. The shortcut assignment doesn't show up in the tab context menu:  
![image](https://github.com/user-attachments/assets/05192dda-ef6c-42ca-8da5-4e7a97382c74)
4. Clicking the entry _also_ doesn't work anymore.

**Comment by seritools** [comment]
The explorer issue of my second comment (reveal in Explorer view) seems to have been fixed in today's nightly.

```
Version: 1.92.0-insider (user setup)
Commit: 4a103b0eea7de96d12fc2cbada846ca7ef4f1298
Date: 2024-07-17T05:03:59.373Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100
```

The initial issue is still remaining, but I accidentally found some additional info:

The Run menu _only_ opens if the editor has focus. If I e.g. have the focus on the explorer view and trigger the Reveal in File Explorer action via Shift+Alt+R, it works fine.

**Comment by benibenj** [comment]
The `Reveal In File Explorer` and `Reveal Active File in Explorer` commands in Insiders should be working the same as in Stable again. `Reveal In File Explorer` is only meant for when you are interacting with explorer and open editor view. You could remove the when clause `!editorFocus` and it should work also for the active editor.

**Comment by seritools** [comment]
Oh yeah, you're right, I think I always pressed Shift+Alt+E, Shift+Alt+R quickly, and when `Shift+Alt+E` didn't work anymore the focus stayed on the editor meaning the `!editorFocus` filtered it out, causing it to open the menu instead 🧠. Thanks for the explanation @benibenj!
