### ISSUE TITLE
When pressing ctrl+F5 to debug, the terminal output has ^C

### ISSUE THREAD

**Issue by fengmoke** [microsoft/vscode#221893]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
![bug](https://github.com/user-attachments/assets/3ed8a9ba-13bc-424f-9cdf-0425a4b337ea)

2. 

```[tasklist]
### Tasks
```

**Comment by roblourens** [comment]
We are trying to make sure that we reuse the terminal safely and cancel any other command that the user had started typing in it, before  running another command
