### ISSUE TITLE
cursor appearing on wrong position when beyond 300 in php file

### ISSUE THREAD

**Issue by nbapat43** [Microsoft/vscode#22181]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.6.2|
|debugger-for-chrome|msjsdiag|2.4.2|
|debugger-for-ios-web|msjsdiag|0.1.2|;

---

Steps to Reproduce:

1. create a .php file and create a line of code that goes over 300 columns/ characters  in  the text editor. You will notice that the cursor is partially over the the next character not inbetween them
2. If you go over 900 columns/ characters  in  the text editor it is beyond the next character

**Comment by alexandrudima** [comment]
@nbapat43 I cannot reproduce. To help me reproduce, can you please:
* perhaps take a screenshot or a screen recording demonstrating the problem.
* share your entire settings (especially those around the font, or zoom level)

Thanks!
![22181](https://cloud.githubusercontent.com/assets/5047891/23695842/579d0510-03e1-11e7-8c75-c4808af44fd9.gif)

**Comment by nbapat43** [comment]
see attachment

Neal Bapatनील बापट



---- On Wed, 08 Mar 2017 00:28:25 -0800 Alexandru Dima &lt;notifications@github.com&gt; wrote ---- 

@nbapat43 I cannot reproduce. To help me reproduce, can you please:
  perhaps take a screenshot or a screen recording demonstrating the problem.
 share your entire settings (especially those around the font, or zoom level)
  Thanks!

**Comment by alexandrudima** [comment]
@nbapat43 Thank you for the screenshot. Could you please also share your settings?

**Comment by nbapat43** [comment]
{
    "php.validate.executablePath": "C:/php7/php.exe",
    "workbench.welcome.enabled": false,
    "php.validate.run": "onType",
    "workbench.iconTheme": "vs-seti",
    "editor.minimap.enabled": true,
    "editor.cursorBlinking": "solid"
}

**Comment by W4RH4WK** [comment]
I encountered a similar issue when zooming using `Ctrl +`. The cursor was offset to the text, sometimes even right on a character.

Here are my [settings](https://github.com/W4RH4WK/dotConfig/blob/master/vscode/settings.json) from which you can see that I am using [Hack](http://sourcefoundry.org/hack/) as my font.

**Comment by alexandrudima** [comment]
I believe this shared the same root cause as #26151 and the fix for #26151 should also fix this issue.
