### ISSUE TITLE
c# anonymous type breaks syntax highlight

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#22189]
- VSCode Version: Code - Insiders 1.11.0-insider

![2017-03-07 2](https://cloud.githubusercontent.com/assets/962340/23687854/b1c69d48-037e-11e7-8dd0-73eaa00b236d.png)

I guess this might be an OmniSharp issue

**Comment by mjbvz** [comment]
Yes, I was unable to reproduce this using our builtin c# grammar.

Please try disabling all extensions by running code with `--disable-extensions`. This should help identify if OmniSharp is the the root cause here. If you still see the syntax highlighting issue with extension disabled, please post the source of the file up and I can take a look

Thanks

**Comment by rakkarage** [comment]
thanks.

this simple theme + c# causes it
not theme alone, theme + c#
it says in the theme inspector that the ending parenthesis has no theme selector
idk

https://marketplace.visualstudio.com/items?itemName=henrysoftware.theme-rage

`{
	"name": "Rage",
	"settings": [
		{
			"settings": {
				"guide": "#333333",
				"selection": "#3f7fbf7f",
				"inactiveSelection": "#003f7f3f",
				"lineHighlight": "#003f7f3f",
				"findRangeHighlight": "#003f7f3f",
				"rangeHighlight": "#003f7f3f",
				"findMatchHighlight": "#3fbf3f3f",
				"currentFindMatchHighlight": "#3fbf3f3f",
				"selectionHighlight": "#3fbf3f3f",
				"referenceHighlight": "#3fbf3f3f",
				"wordHighlight": "#3fbf3f3f",
				"wordHighlightStrong": "#bf3f3f3f"
			}
		},
		{
			"scope": "invalid",
			"settings": { "foreground": "#bf7f7f" }
		},
		{
			"scope": "invalid.deprecated",
			"settings": { "foreground": "#bf7fbf" }
		},
		{
			"scope": "comment, punctuation.definition.comment",
			"settings": { "foreground": "#3fbf3f7f" }
		},
		{
			"scope": "punctuation",
			"settings": { "foreground": "#7f7f7f" }
		},
		{
			"scope": "constant",
			"settings": { "foreground": "#bfbf7f" }
		},
		{
			"scope": "string",
			"settings": { "foreground": "#bf7f7f" }
		},
		{
			"scope": "keyword",
			"settings": { "foreground": "#7f7fbf" }
		},
		{
			"scope": "storage",
			"settings": { "foreground": "#3fbfbf" }
		},
		{
			"scope": "variable, support.variable, entity.name, meta",
			"settings": { "foreground": "#569cd6" }
		},
		{
			"scope": "entity.name.function, support.function",
			"settings": { "foreground": "#bf7fbf" }
		}
	]
}
`

**Comment by rakkarage** [comment]
without c# it is punctuation.curlybrace.close.cs
with c# it is nothing?
