### ISSUE TITLE
HCL (Terraform) syntax highlighting not working for code blocks

### ISSUE THREAD

**Issue by alexander-nolan** [microsoft/vscode#221823]
- VS Code Version:  1.86.1
- OS Version: Windows 10 22H2 Build 19045.3930
- Logs:

Co-pilot chat isn't applying any formatting or syntax highlighting to HCL code. It was working for me since I started using the extension several months ago. Syntax highlighting works for all other languages I've tested. 

I've tried the current version, insiders preview and tried downgrading to v0.11.*, but when I try to downgrade authentication fails over and over. I've installed a couple of different terraform syntax highlighting extensions and it doesn't seem to affect the code produced by co-pilot chat. It always produces white text with a black background.

![image](https://github.com/microsoft/vscode-copilot-release/assets/34385107/056e0460-e61a-4659-acc1-24055fb21b3c)

Steps to Reproduce:

1. Ask co-pilot chat to produce terraform code

**Comment by mjbvz** [comment]
Actually not windows specific. You just need to install the HCL extension (the one also provided by hashicorp)

Not sure why the terraform extension doesn't include  hcl support out of the box. However this is not a VS Code issue so closing

**Comment by alexander-nolan** [comment]
That worked. Thank you.
