### ISSUE TITLE
No reliable way to disable automated port forwarding

### ISSUE THREAD

**Issue by ManfredLange** [microsoft/vscode#221888]
Does this issue occur when all extensions are disabled?: not applicable

- VS Code Version: 1.91.1
- OS Version: Ubuntu 22.04.4 LTS

Steps to Reproduce:

1. Set up a nodejs based dev container with explicit port forwarding in a docker-compose file
2. Create a React app default
3. Start react app with "npm run start"
4. It will automatically forward the port despite the fact the port has already been statically forwarded.

I am aware of and use these mechanisms to disable automated forwarding:

In `.devcontainer/devcontainer.json`
```json
"forwardPorts": []
```

and in `.vscode/settings.json
```json
   "remote.autoForwardPorts": false,
   "remote.restoreForwardedPorts": false,
   "remote.autoForwardPortsSource": "output",
```

However, these don't make a difference.

**Comment by alexr00** [comment]
@ManfredLange can you share a screen recording of the port getting auto-forwarded? With `"remote.autoForwardPorts": false,` it should not happen.
