### ISSUE TITLE
Pytest - allow to stop / kill a test

### ISSUE THREAD

**Issue by sylvainmouquet** [microsoft/vscode#221804]
I'd like to be able to stop or kill a test. When a test is started and remains like a zombie, I can't stop it or kill it. I need to restart VSCode

**Comment by eleanorjboyd** [comment]
Hi! We have made changes here recently to fix issues regarding zombie processes especially around debugging. Are you still seeing this issue?

**Comment by sylvainmouquet** [comment]
Hello @eleanorjboyd 
I have tested it.


Well, I don't understand why the button 'Stop' in the toolbar has not the same effect than the button 'Cancel test run'. When i click on 'Cancel test run' the toolbar is still active. 

If i trigger a test i can trigger a second test, but the second test will never been processed. It is canceled after the first test is finishing to process.

Another feedback, the icons are like a christmas tree, they switch to processing to stop to processing.
My version of VSCode is ```Version: 1.93.1 (Universal)```

For the main subject, i don't reproduce the zombification of processes
