### ISSUE TITLE
When selecting the file directory, the disk character will be lost, resulting in the problem, now I have a terminal problem, because the path is not disk character

### ISSUE THREAD

**Issue by F-Yanyu** [microsoft/vscode#221889]
Type: <b>Bug</b>

When selecting the file directory, the disk character will be lost, resulting in the problem, now I have a terminal problem, because the path is not disk character

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13400 (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.78GB (12.22GB free)|
|Process Argv|--crash-reporter-id a709ddef-dec5-45c8-af20-be73c0e6fa9b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
pug|ama|1.0.1
tsl-problem-matcher|amo|0.6.2
browse-lite|ant|0.3.9
iconify|ant|0.9.0
slidev|ant|0.49.16
unocss|ant|0.61.5
vite|ant|0.2.5
where-am-i|ant|0.2.0
antmove-vscode-plugin|ant|1.1.19
Bito|Bit|1.3.5
cssrem|cip|3.1.1
EnglishChineseDictionary|Cod|1.1.0
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.2.0
vscode-html-css|ecm|2.0.10
EditorConfig|Edi|0.16.4
vsc-material-theme-icons|equ|3.6.1
prettier-vscode|esb|10.4.0
file-icons|fil|1.1.0
copilot|Git|1.214.0
copilot-chat|Git|0.17.1
vscode-pull-request-github|Git|0.92.0
comment-translate|int|2.3.3
i18n-ally|lok|2.12.0
vscode-docker|ms-|1.29.1
vscode-language-pack-zh-hans|MS-|1.91.2024071009
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vscode-typescript-next|ms-|5.6.20240716
color-highlight|nau|2.8.0
vetur|oct|0.37.3
material-icon-theme|PKi|5.6.0
pluralsight|Plu|0.4.2
vscode-sort-json|ric|1.20.0
LiveServer|rit|5.7.9
gruvbox-material|sai|6.5.2
code-settings-sync|Sha|3.4.3
vue-helper|she|4.2.0
code-spell-checker|str|3.0.1
sass-indented|syl|1.8.30
tabnine-vscode|Tab|3.129.0
vscode-sort-package-json|uni|1.5.2
errorlens|use|3.20.0
volar|Vue|2.0.26
vscode-typescript-vue-plugin|Vue|1.8.27
code-translate|w88|1.0.20
vscode-wakatime|Wak|24.6.0
quokka-vscode|Wal|1.0.647
snippet-generator|wen|0.3.8
eno|Wsc|2.3.53
material-theme|zhu|3.17.2
grammarly|znc|0.24.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31094925
refactort:31098051
ccplc:31098109
pythonrstrctxt:31093869
hdi1a554:31097393

```

</details>

**Comment by F-Yanyu** [comment]
![image](https://github.com/user-attachments/assets/a255acb4-f8a1-4aa8-85b0-112272c890bf)
![image](https://github.com/user-attachments/assets/e247e225-31e6-4dcc-8a20-e0f96c867ec4)

**Comment by alexr00** [comment]
Can you please provide repro steps?
