### ISSUE TITLE
User shows up twice even though it's the same account

### ISSUE THREAD

**Issue by LT1Z51** [microsoft/vscode#221876]
Type: <b>Bug</b>

I log in with my MSA to sync settings which VSCode logs in as <email>@outlook.com.  I installed the C# Dev kit and enabled the Trusted Extension but somehow it uses my <email>@gmail.com (which is linked to my MSA) and now I have two accounts shown.  I can't get VSCode to move the Trusted Extension to the @outlook.com and I can't get it to sysn settings to the @gmail.com.  Its the same account WHY IS IT LOGGED IN TWICE.  The UI is clearly wrong, or on the server side something is borked.

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (54.15GB free)|
|Process Argv|--crash-reporter-id ad6f6d02-20d1-4bac-b4a9-84128fedc658|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
vscode-firefox-debug|fir|2.9.10
csdevkit|ms-|1.8.14
csharp|ms-|2.34.12
vscode-dotnet-runtime|ms-|2.0.9
remote-wsl|ms-|0.88.2
notepadplusplus-keybindings|ms-|1.0.7
powershell|ms-|2024.2.2
vscode-yaml|red|1.15.0
rust-analyzer|rus|0.3.2037

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31094925
refactort:31098051

```

</details>

**Comment by LT1Z51** [comment]
![image](https://github.com/user-attachments/assets/83a64fc3-95d1-4a44-94d6-bc4d5ceae826)

**Comment by TylerLeonhardt** [comment]
This is probably because of this line:
https://github.com/microsoft/vscode/blob/main/extensions/microsoft-authentication/src/AADHelper.ts#L565

I'm guessing the "preferred_username" claim is defined in the token that Settings Sync gets back, but not defined in the token the C# Dev Kit gets back.
