### ISSUE TITLE
Linux machines don't show file icons

### ISSUE THREAD

**Issue by Yingzi1234** [microsoft/vscode#221875]
Type: <b>Bug</b>

More info:
This issue is only reproduced on Linux machine

Repro steps:
1. Open VScode and clone this repo, e.g., https://github.com/clibs/clib.git
2. Open the “Exploer” page
3. Check if the file's icon is displayed correctly

**Expected result:**
The file icon will be displayed

**Windows and mac machines:**
![image](https://github.com/user-attachments/assets/30307b52-a7c0-4813-80ed-b01796003a89)

**Actual result:**
No file icon displayed

**Linux machine:**
![image](https://github.com/user-attachments/assets/9e985fa6-4c28-40ad-b216-c9c7702986c0)

VS Code version: Code 1.91.1
Machine: Linux

**Comment by lramos15** [comment]
Do the tabs when you open the files have file icons?

**Comment by justschen** [comment]
I'm not seeing this on my linux setup. closing and requesting author verification then

**Comment by Yingzi1234** [comment]
@justschen @lramos15 Closing is the correct behavior, this issue is no longer reproduced.
![Image](https://github.com/user-attachments/assets/b1bb4c9a-ed00-4115-acf6-5976dab00b28)
