### ISSUE TITLE
VS Code background operations should not steal user's text input focus

### ISSUE THREAD

**Issue by stewartadam** [Microsoft/vscode#22187]
- VSCode Version: 1.10.1
- OS Version: Windows 10 (Anniversary Update)

I opened VS Code today and tried to switch files, and as I did so I VS Code pulled focus to the console because it was automatically updating packages. This is a poor UX.

Steps to Reproduce:
1. Open VS Code (with outdated packages)
2. Ctrl+P
3. Switch to file
4. Try to type code

Expected result:
Update packages in the background, or don't pull text focus if the console needs to open automatically.

**Comment by bpasero** [comment]
@stewartadam can you share the output of the console? trying to understand which extension causes this.

**Comment by weinand** [comment]
I think this is independent from extensions. The question is more: should the console be able to pull focus?

**Comment by bpasero** [comment]
Yes, we have API to control this (for all view parts and editors).

**Comment by stewartadam** [comment]
When it happens again I'll copy the output. The text I saw said it was updating extensions, with one line for each extension being downloaded... I only have C# and Python installed atm.

**Comment by bpasero** [comment]
@stewartadam when you found out please report it to the extension (either Python or C#).

**Comment by stewartadam** [comment]
I saw this happen again while someone else was giving a presentation yesterday, appears to be the C# extension (updating NuGet packages, I think). Will try to repro and report against the extension.
