### ISSUE TITLE
connection to serve-web hanging indefinitely

### ISSUE THREAD

**Issue by theswit** [microsoft/vscode#221883]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.92.0-insider
Commit: 06f8ef165cc37104bc78b7f36209d95333474348
Date: 2024-07-16T05:03:41.928Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
- OS Version: Linux x64 4.18.0-513.18.1.el8_9.x86_64

Steps to Reproduce:

1. start serve-web (via systemctl user service, if that matters). exact start command: `code-insiders serve-web --host 127.0.0.1 --port 59005 --without-connection-token`
2. try to connect via google chrome (locally or via ssh connection with port forwarded appropriately)

The feature is working fine with the latest non-insider release, v1.91.1, both locally (via localhost) and port forwarded ssh connection.
code-insiders launches fine locally, only when trying to use serve-web on insider v1.92 do i run into the issue.

The symptom: when I try to connect via chrome (eg localhost:59005 on the host machine), it tries to load and never completes. if i stop serve-web on the host, trying to connect via the browser immediately fails (expected. I just say this to confirm the host & port are correct).

One other thing to note: the service log/status (`systemctl --user status code-insiders`) shows no errors, and prints the URL to connect to as I'd expect).

**Comment by theswit** [comment]
> Can you share the log output of the program when run with `--verbose`?

Here's the output after I tried to connect via the browser one time:

> $ code-insiders serve-web --host 127.0.0.1 --port 59005 --without-connection-token --verbose                     
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
> Web UI available at http://127.0.0.1:59005
> [2024-07-17 09:13:27] debug [reqwest::connect] starting new connection: https://update.code.visualstudio.com/
> [2024-07-17 09:13:27] debug Resolved quality Insiders to 4a103b0eea7de96d12fc2cbada846ca7ef4f1298
> [2024-07-17 09:13:27] debug refreshed latest release: 1.92.0-insider (commit 4a103b0eea7de96d12fc2cbada846ca7ef4f1298)
> [2024-07-17 09:13:27] info Downloading server 4a103b0eea7de96d12fc2cbada846ca7ef4f1298
> [2024-07-17 09:13:27] debug [reqwest::async_impl::client] redirecting 'https://update.code.visualstudio.com/commit:4a103b0eea7de96d12fc2cbada846ca7ef4f1298/server-linux-x64-web/insider' to 'https://vscode.download.prss.microsoft.com/dbazure/download/insider/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/vscode-server-linux-x64-web.tar.gz'
> [2024-07-17 09:13:27] debug [reqwest::connect] starting new connection: https://vscode.download.prss.microsoft.com/
> [2024-07-17 09:13:27] trace Downloading server: 0/65796309 (0%)
> [2024-07-17 09:13:27] trace Downloading server: 2105321/65796309 (3%)
> [2024-07-17 09:13:27] trace Downloading server: 4202489/65796309 (6%)
> [2024-07-17 09:13:27] trace Downloading server: 6307832/65796309 (10%)
> ...
> [2024-07-17 09:13:28] trace Downloading server: 65232876/65796309 (99%)
> [2024-07-17 09:13:28] trace Downloading server: 65796309/65796309 (100%)
> [2024-07-17 09:13:29] info Starting server 4a103b0eea7de96d12fc2cbada846ca7ef4f1298
> [2024-07-17 09:13:30] info [4a103b0 stderr]: Loading "original-fs" failed
> [2024-07-17 09:13:30] info [4a103b0 stderr]: Error: Cannot find module 'original-fs'
> [2024-07-17 09:13:30] info [4a103b0 stderr]: Require stack:
> [2024-07-17 09:13:30] info [4a103b0 stderr]: - $HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at Module._load (node:internal/modules/cjs/loader:986:27)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at Module.require (node:internal/modules/cjs/loader:1233:19)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at require (node:internal/modules/helpers:179:18)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at n ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:3:98)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at r.load ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:2:1637)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at h.load ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:1:13977)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at u ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:3:9338)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at Object.errorback ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:3:9457)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at h.triggerErrorback ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:1:14271)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at $HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:1:14022
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at r.load ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:2:1654)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at h.load ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:1:13977)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at u ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:3:9338)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at a._loadModule ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:3:9466)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at a._resolve ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:4:452)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at a.defineModule ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:3:5561)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at Function.p [as define] ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:4:1741)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at out-build/bootstrap-amd.js ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:4:6445)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at $HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:1:132
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at Object.<anonymous> ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:4:9767)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at Module.load (node:internal/modules/cjs/loader:1208:32)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at Module._load (node:internal/modules/cjs/loader:1024:12)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     at node:internal/main/run_main_module:28:49 {
> [2024-07-17 09:13:30] info [4a103b0 stderr]:   code: 'MODULE_NOT_FOUND',
> [2024-07-17 09:13:30] info [4a103b0 stderr]:   requireStack: [
> [2024-07-17 09:13:30] info [4a103b0 stderr]:     '$HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js'
> [2024-07-17 09:13:30] info [4a103b0 stderr]:   ],
> [2024-07-17 09:13:30] info [4a103b0 stderr]:   phase: 'loading',
> [2024-07-17 09:13:30] info [4a103b0 stderr]:   moduleId: 'original-fs',
> [2024-07-17 09:13:30] info [4a103b0 stderr]:   neededBy: [ 'fs' ]
> [2024-07-17 09:13:30] info [4a103b0 stderr]: }
> [2024-07-17 09:13:30] info [4a103b0 stderr]: Here are the modules that depend on it:
> [2024-07-17 09:13:30] info [4a103b0 stderr]: [ 'fs' ]
> [2024-07-17 09:13:30] info [4a103b0 stdout]: *
> [2024-07-17 09:13:30] info [4a103b0 stdout]: * Visual Studio Code Server
> [2024-07-17 09:13:30] info [4a103b0 stdout]: *
> [2024-07-17 09:13:30] info [4a103b0 stdout]: * By using the software, you agree to
> [2024-07-17 09:13:30] info [4a103b0 stdout]: * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> [2024-07-17 09:13:30] info [4a103b0 stdout]: * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> [2024-07-17 09:13:30] info [4a103b0 stdout]: *
> [2024-07-17 09:13:30] info [4a103b0 stdout]: Server bound to /tmp/code-insiders-1c532788-952e-4dbe-b219-fc1911ee9ca2
> [2024-07-17 09:13:30] info [4a103b0 stdout]: Extension host agent listening on /tmp/code-insiders-1c532788-952e-4dbe-b219-fc1911ee9ca2
> [2024-07-17 09:13:30] info [4a103b0 stdout]:

**Comment by connor4312** [comment]
You appear to have set `ELECTRON_RUN_AS_NODE` when you set up the service, which is causing some logic to think it's running in Electron. Please do not set this environment variable.

**Comment by theswit** [comment]
I ran the above command from within an active vscode (1.91) embedded terminal. When running from a non-vscode shell, I get the same/similar error:

> $ env | grep ELECTRON
> $ code-insiders serve-web --host 127.0.0.1 --port 59005 --without-connection-token --verbose
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
> Web UI available at http://127.0.0.1:59005
> [2024-07-17 09:38:34] debug [reqwest::connect] starting new connection: https://update.code.visualstudio.com/
> [2024-07-17 09:38:35] debug Resolved quality Insiders to 4a103b0eea7de96d12fc2cbada846ca7ef4f1298
> [2024-07-17 09:38:35] debug refreshed latest release: 1.92.0-insider (commit 4a103b0eea7de96d12fc2cbada846ca7ef4f1298)
> [2024-07-17 09:38:35] info Starting server 4a103b0eea7de96d12fc2cbada846ca7ef4f1298
> [2024-07-17 09:38:35] info [4a103b0 stderr]: Loading "original-fs" failed
> [2024-07-17 09:38:35] info [4a103b0 stderr]: Error: Cannot find module 'original-fs'
> [2024-07-17 09:38:35] info [4a103b0 stderr]: Require stack:
> [2024-07-17 09:38:35] info [4a103b0 stderr]: - $HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at Module._load (node:internal/modules/cjs/loader:986:27)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at Module.require (node:internal/modules/cjs/loader:1233:19)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at require (node:internal/modules/helpers:179:18)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at n ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:3:98)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at r.load ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:2:1637)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at h.load ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:1:13977)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at u ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:3:9338)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at Object.errorback ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:3:9457)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at h.triggerErrorback ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:1:14271)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at $HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:1:14022
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at r.load ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:2:1654)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at h.load ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:1:13977)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at u ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:3:9338)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at a._loadModule ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:3:9466)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at a._resolve ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:4:452)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at a.defineModule ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:3:5561)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at Function.p [as define] ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:4:1741)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at out-build/bootstrap-amd.js ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:4:6445)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at $HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:1:132
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at Object.<anonymous> ($HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js:4:9767)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at Module.load (node:internal/modules/cjs/loader:1208:32)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at Module._load (node:internal/modules/cjs/loader:1024:12)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     at node:internal/main/run_main_module:28:49 {
> [2024-07-17 09:38:35] info [4a103b0 stderr]:   code: 'MODULE_NOT_FOUND',
> [2024-07-17 09:38:35] info [4a103b0 stderr]:   requireStack: [
> [2024-07-17 09:38:35] info [4a103b0 stderr]:     '$HOME/.vscode-insiders/cli/serve-web/4a103b0eea7de96d12fc2cbada846ca7ef4f1298/out/server-main.js'
> [2024-07-17 09:38:35] info [4a103b0 stderr]:   ],
> [2024-07-17 09:38:35] info [4a103b0 stderr]:   phase: 'loading',
> [2024-07-17 09:38:35] info [4a103b0 stderr]:   moduleId: 'original-fs',
> [2024-07-17 09:38:35] info [4a103b0 stderr]:   neededBy: [ 'fs' ]
> [2024-07-17 09:38:35] info [4a103b0 stderr]: }
> [2024-07-17 09:38:35] info [4a103b0 stderr]: Here are the modules that depend on it:
> [2024-07-17 09:38:35] info [4a103b0 stderr]: [ 'fs' ]
> [2024-07-17 09:38:35] info [4a103b0 stdout]: *
> [2024-07-17 09:38:35] info [4a103b0 stdout]: * Visual Studio Code Server
> [2024-07-17 09:38:35] info [4a103b0 stdout]: *
> [2024-07-17 09:38:35] info [4a103b0 stdout]: * By using the software, you agree to
> [2024-07-17 09:38:35] info [4a103b0 stdout]: * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> [2024-07-17 09:38:35] info [4a103b0 stdout]: * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> [2024-07-17 09:38:35] info [4a103b0 stdout]: *
> [2024-07-17 09:38:35] info [4a103b0 stdout]: Server bound to /tmp/code-insiders-c99273af-7870-49a5-a0b7-e0e0333d7114
> [2024-07-17 09:38:35] info [4a103b0 stdout]: Extension host agent listening on /tmp/code-insiders-c99273af-7870-49a5-a0b7-e0e0333d7114
> [2024-07-17 09:38:35] info [4a103b0 stdout]:

**Comment by theswit** [comment]
I also nuked ~/.vscode-insiders/cli/ and re-launched serve-web, same error after re-downloading server.

**Comment by connor4312** [comment]
Can you confirm the value of any `ELECTRON_RUN_AS_NODE` environment variable where you see that error?

**Comment by theswit** [comment]
The variable is not set. I tried to show that in my [very long!] output [above](https://github.com/microsoft/vscode/issues/221883#issuecomment-2233741445). Here it is by itself:

> $ env | grep ELECTRON
(no output)

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/blob/6eb023ca6f89e3bec4d2db277776a4d5ae2f5533/src/bootstrap-amd.js#L194-L198

@deepak1556 do you know why else this condition would get hit?

**Comment by deepak1556** [comment]
Debugging shows `process.env.ELECTRON_RUN_AS_NODE` is defined, @connor4312 can you share how the server-main.js is invoked from the cli, definitely seems like a env leak from there from the esm refactor.

Additionally, `process.versions.electron` should be sufficient to detect electron environment, in `ELECTRON_RUN_AS_NODE` there is no `original-fs` so we can update the check to fix this issue.

**Comment by connor4312** [comment]
From here to its callers:

https://github.com/microsoft/vscode/blob/65a6a2f783dbc87fb3b1408c6a9b3e8d455a60a2/cli/src/tunnels/code_server.rs#L594

We don't set any/override any environment variables when it gets spawned, in any code path

**Comment by deepak1556** [comment]
Yeah I believe the issue with env variable being passed into the tunnel binary was always there just wasn't apparent until the above change landed. We should remove the env [here](https://github.com/microsoft/vscode/blob/3fa56e14efd2a8289bd04feeb851845467e75f73/src/vs/code/node/cli.ts#L59-L78) similar to what we do when launching the [actual application](https://github.com/microsoft/vscode/blob/3fa56e14efd2a8289bd04feeb851845467e75f73/src/vs/code/node/cli.ts#L188).

**Comment by theswit** [comment]
Confirming that with the latest insider build, I'm able to connect again. Thanks for the quick fix!

Also note, FWIW, that I can start the server from within a vscode embedded terminal window, which has `ELECTRON_RUN_AS_NODE=1` set in the env, and it works well there too.
