### ISSUE TITLE
VS Code Insiders updater tried to update machine-wide install even though I installed as single-user

### ISSUE THREAD

**Issue by dagood** [microsoft/vscode#221835]
Type: <b>Bug</b>

Attempting to install an auto update led to unexpected elevation prompt and this install failure log:

```
Jul 16 16:30:36.682 INFO Starting: C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe, true, Updating Visual Studio Code...
Jul 16 16:30:36.684 ERRO Bad arguments: Code path doesn't seem to exist: C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe
```

That path contains uninstallers and some other files, but not VS Code itself, because VS Code is actually installed to `C:\Users\dagood\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe`.

* Seems like the same root cause as: https://github.com/microsoft/vscode/issues/221824

VS Code version: Code - Insiders 1.92.0-insider (82104a3a6cf8713b81e5bbd97960dbf5c82a816a, 2024-07-05T00:00:00.000Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (41.50GB free)|
|Process Argv|--crash-reporter-id 85e4839e-1404-4fbf-838e-703840532cdb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
chatpanelt:31014475
945dj816:31013170
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nb_pkg_only:31057982
nativerepl2:31093712
refactort:31084545
pythonrstrctxt:31093868
4930e709:31088354
hdi1a554:31091669

```

</details>

**Comment by dagood** [comment]
Installing again from https://code.visualstudio.com/insiders/ got me to:

* Version: 1.92.0-insider (user setup)
* Commit: 06f8ef165cc37104bc78b7f36209d95333474348

But it seems really unfortunate that there isn't a clearer way to get this info than filing an issue and/or looking for a closed duplicate.

**Comment by gjsjohnmurray** [comment]
> But it seems really unfortunate that there isn't a clearer way to get this info than filing an issue and/or looking for a closed duplicate.

I guess this is why that issue is still pinned.

**Comment by gjsjohnmurray** [comment]
I have edited the title of that issue to make it more helpful I hope.

**Comment by dagood** [comment]
Thanks, yeah, I hope so too. 😄

I guess I'm not too familiar with the audience of VS Code Insiders but it seems to me like a fairly narrow announcement--I'm just surprised that there's no way to have the editor or update process itself provide this info. Anyway, it is Insiders, I guess I just need to be on my toes a bit more.
