### ISSUE TITLE
Markdown Fenced Code Block in Indented List Not Properly Highlighted

### ISSUE THREAD

**Issue by quanticle** [Microsoft/vscode#22185]
When I put a fenced code area in the middle of a bulleted list, I notice that list entries following the fenced code area lose their formatting, like so:

![repro screenshot](http://i.imgur.com/vWeLSst.png)

[Gist with repro case](https://gist.github.com/quanticle/d1ec9d0858a604ca0bf89f7070a690ec)

Is this intentional behavior? Am I formatting my markdown wrong? Is there any way that I can have formatting in both the fenced code block and the subsequent list items?

**Comment by mjbvz** [comment]
The current formatting is somewhat off: the second list is treated as code block.

![screen shot 2017-03-07 at 4 22 54 pm](https://cloud.githubusercontent.com/assets/12821956/23684245/64949966-0352-11e7-877b-e3e8afd213fb.png)

This is expected and is in keeping with the common mark spec. The correct formatting would be to indent fenced code block as well:

```md
---
title: Markdown highlight problem
---

* List entry one
	* Second level entry one
	* Second level entry `two`
	```javascript
	for(var i = 0; i < 5; i++){
		Console.log("Hello");
	}
	```
	* Second level entry two (note the lack of color on the bullet)
	* `code blocks` are no longer highlighted either
```

![screen shot 2017-03-07 at 4 24 18 pm](https://cloud.githubusercontent.com/assets/12821956/23684262/894703d4-0352-11e7-8488-ef10b43b8dbd.png)


Our syntax coloring is off here though, with the indented code block no longer being highlighted as js

**Comment by quanticle** [comment]
Okay. I didn't read the markdown specification closely enough to understand that the code block should be highlighted as well. I had tried indenting the code block, but when the indented code block lost syntax highlighting, I thought I was doing something incorrect.

Should I update the title of this issue to indicate that the real problem is that indented code blocks lose formatting?

**Comment by mjbvz** [comment]
Thanks @quanticle. I've just gone ahead and updated the title of the issue to: "Markdown Fenced Code Block in Indented List Not Properly Highlighted". If you do not feel that the new title accurately captures the bug here, feel free to update the title again

**Comment by quanticle** [comment]
New title looks good. Thanks!

**Comment by colinfang** [comment]
I made an extension to fix this

https://marketplace.visualstudio.com/items?itemName=colinfang.markdown-fenced-code-block-fix 

Surely it would cause side effects but it is worth it for me at the moment.
