### ISSUE TITLE
How to hide lines like notepad++ or VS region?

### ISSUE THREAD

**Issue by laterz** [Microsoft/vscode#22196]
- VSCode Version:1.10.1
- OS Version:win7-64

like the title,how to hide selected lines to make it looks clear?

notepad++ has the funtion: select lines->right click ->Hide Lines

vs also has region...

**Comment by hashhar** [comment]
I really like how Vim does this.

You add a config called `foldMarker` of type string.

Now when the editor sees text of the format `<comment-symbol>(.*)<foldMarker>(.*)` it replaces it with something like `<fold>numOfFoldedLines: \1 \2`.

I don't how folding is currently implemented but will edit this with more details and an implementation idea once I read the code.

**Comment by aeschli** [comment]
Mark this as a duplicate of #18805.
Fold regions is #12146
