### ISSUE TITLE
maxContentLength size of -1 exceeded

### ISSUE THREAD

**Issue by JVKeller** [microsoft/vscode#221973]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.91.1
- OS Version: Windows 11 Enterprise

Steps to Reproduce:

1.  Connect to remote WebDAV workspace 
2.  Attempt to open xml, html or similar.

![image](https://github.com/user-attachments/assets/edc51f21-2ea2-4d1a-be74-6e28b9ff62b3)

Other file types will open and save but certain types will not open.

This example file will not open: test.html
```
test.html
HTTP/1.1 200 OK
Date: Wed, 17 Jul 2024 18:24:36 GMT
Server: milton.io-1.8.1.3
Last-Modified: Wed, 17 Jul 2024 18:11:17 GMT
Content-Type: text/html
Content-Length: 4096

```
This example file does open: test.txt
```
test.txt
HTTP/1.1 200 OK
Date: Wed, 17 Jul 2024 18:24:43 GMT
Server: milton.io-1.8.1.3
Last-Modified: Wed, 17 Jul 2024 18:19:26 GMT
Content-Type: text/plain
Content-Length: 81

```
FIletype and file size is there, and small, so why would I get this error?

**Comment by JVKeller** [comment]
What I have figured out so far, webdav reports the file size as an estimated chunk at 4096 bites, and the actual file size is different, so I think that is why the error is being thrown.

**Comment by JVKeller** [comment]
I made an html file that was exactly 4096 bytes on the server, tried to load it and got the same error. 

I made an html file that was exactly 4096 bytes in VSCode, tried to save it and got the same error. 

Editing other text files are fine, it only seems to be XML.

**Comment by bpasero** [comment]
> Connect to remote WebDAV workspace

How does this work? Through an extension?

**Comment by JVKeller** [comment]
There are a few different extensions for connecting via webdav. I tried a few different ones and they have have the same result.

The one I felt was the best implementation is: https://marketplace.visualstudio.com/items?itemName=kowd.vscode-webdav

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by JVKeller** [comment]
I had already tested it with everything disabled, fresh install, you name it. Even tried to figured out of I could make an override to skip that check.

**Comment by bpasero** [comment]
Got it. I do not think this is a bug in VS Code we can fix. I would see how you setup WebDAV on your machine and report an issue to the tool you are using.
