### ISSUE TITLE
Always start on Source Control when opening a project

### ISSUE THREAD

**Issue by jjnxpct** [microsoft/vscode#221928]
Is it possible to always start on 'Source Control when opening a project?' If not this option would be nice to have.

So I would like to be able to set VSCODE to alway start on the Source Control tab. But I can not find a setting for this.  The main reason for this is that this tab will indicate to me (in the big blue button) there are remote commits or local changes I have not synced yet.

**Comment by gjsjohnmurray** [comment]
Related to https://github.com/microsoft/vscode/issues/203288

**Comment by lszomoru** [comment]
Closing in favour of the related issue.
