### ISSUE TITLE
"Initializing JS/TS language features" is stuck for a big project which is a mono repo

### ISSUE THREAD

**Issue by maruffahmed** [microsoft/vscode#221972]
Type: <b>Performance Issue</b>

My typescripts feature is completely unusable. The initializing is stuck and TS server is crush multiple times

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:46.768Z)
OS version: Darwin arm64 23.5.0
Modes:
Remote OS version: Linux x64 6.5.0-1022-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id c2f80c4f-7493-4766-abe3-4bedf22335e0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: maruf codespace|
|OS|Linux x64 6.5.0-1022-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (4 x 0)|
|Memory (System)|15.61GB (5.99GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    6	   106	 13062	code main
    8	    41	 13106	   gpu-process
    0	    16	 13107	   utility-network-service
    1	    41	 13405	shared-process
    0	     0	 76559	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    16	 32780	ptyHost
    8	   188	 72244	window [8] (ChatHistoryItem.tsx — flow [Codespaces: maruf codespace])
    0	    33	 72323	fileWatcher [8]
    0	    66	 72324	extensionHost [8]
    0	    33	 72338	     electron-nodejs (serverMain.js )
    0	    82	 76471	window [9] (Issue Reporter)

Remote: Codespaces: maruf codespace
CPU %	Mem MB	   PID	Process
    2	    98	   664	remote agent
    0	    25	   933	   ptyHost
    0	   139	 42543	   extension-host
    0	    90	 43180	     /vscode/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/node /home/node/.vscode-remote/extensions/bradlc.vscode-tailwindcss-0.12.5/dist/tailwindServer.js --node-ipc --clientProcessId=42543
    0	    25	 43207	     /vscode/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/node /vscode/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=42543
    0	    82	 51957	     /vscode/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/node --max-old-space-size=3072 /vscode/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /tmp/vscode-typescript1000/ccdeb9f41b1f81787c3f/tscancellation-97f22a7437f89c093e54.tmp* --logVerbosity verbose --logFile /home/node/.vscode-remote/data/logs/20240717T174318/exthost2/vscode.typescript-language-features/tsserver-log-1i2lJ6/tsserver.log --locale en --noGetErrOnBackgroundUpdate --canUseWatchEvents --validateDefaultNpmLocation --useNodeIpc
    0	   303	 42555	   fileWatcher
    0	     0	 52339	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 52340	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: Codespaces: maruf codespace|    Folder (flow): 13173 files|      File types: png(4888) ts(1605) tsx(1360) js(484) json(417) java(327)
|                  map(279) h(208) xml(205) go(189)
|      Conf files: project.json(85) package.json(30) tsconfig.json(29)
|                  github-actions(23) dockerfile(13) makefile(4) tasks.json(2)
|                  devcontainer.json(1) settings.json(1) launch.json(1);
```

</details>
<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
postcss|css|1.0.9
es7-react-js-snippets|dsz|4.4.3
auto-rename-tag|for|0.1.10
codespaces|Git|1.17.1
vscode-graphql-syntax|Gra|1.3.6
vscode-react-typescript|inf|1.3.1
dotenv|mik|1.0.1
remote-containers|ms-|0.375.1
material-icon-theme|PKi|5.6.0
sqlite-viewer|qwt|0.5.10
vscode-icons|vsc|12.8.0
vscode-todo-highlight|way|1.0.5
vscode-tailwindcss|bra|0.12.5
vscode-eslint|dba|3.0.10
prettier-vscode|esb|10.4.0
codespaces|Git|1.17.1
vscode-pull-request-github|Git|0.92.0
gitless|maa|11.7.2
stats-bar|njz|0.5.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31094925
refactort:31098051
1iic9185:31097392

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
