### ISSUE TITLE
The editor.wrappingColumn option was deleted ?

### ISSUE THREAD

**Issue by cdoco** [Microsoft/vscode#22197]
- VSCode Version: 1.10.1
- OS Version: macOS 10.12.3

The editor.wrappingColumn option was deleted ?

I want to close the wrap what now?

**Comment by AntSworD** [comment]
Check `editor.wordWrapColumn` and `editor.wordWrap`

**Comment by cdoco** [comment]
I set `"editor.wordWrap": "wordWrapColumn"` and `"editor.wordWrapColumn": 800`, But it doesn't seem to work.

**Comment by AntSworD** [comment]
```
 "editor.wordWrapColumn": 80,
  "editor.wordWrap": "wordWrapColumn",
```
work for me

**Comment by cdoco** [comment]
`editor.wordWrapColumn` can only be set to 80 ? 

I want to close the wrap what now?

**Comment by AntSworD** [comment]
`"editor.wordWrap": "off",`

**Comment by cdoco** [comment]
I set `"editor.wordWrap": "off"`, But it still did not wrap.

**Comment by AntSworD** [comment]
> I want to close the wrap what now?

disable or enable?  What are you want?

**Comment by cdoco** [comment]
I want to disable .

**Comment by AntSworD** [comment]
> I set "editor.wordWrap": "off", But it still did not wrap.

I didn't know what you mean.

It work for me.

**Comment by cdoco** [comment]
![image](https://cloud.githubusercontent.com/assets/8597204/23699887/eaa89492-042b-11e7-8559-e74835d83eec.png)

![image](https://cloud.githubusercontent.com/assets/8597204/23699876/dde50a1a-042b-11e7-9429-e94b5847890d.png)

It doesn't work on my computer.

**Comment by AntSworD** [comment]
Can you restart VSCode try again?
Or delete other setting option for a test

**Comment by ramya-rao-a** [comment]
Also, read http://code.visualstudio.com/updates/v1_10#_word-wrap-settings-redesign

**Comment by cdoco** [comment]
![image](http://www.cdoco.com/images/vacode.gif)

I found a strange phenomenon, I only like this file is WordWrap, but when I put a piece of text copied to a new file is not wrap, but I repeat it again after the switch tab, wrap the.

**Comment by alexandrudima** [comment]
Files that appear to be minified end up always wrapped. Let's track in #21801.

https://github.com/Microsoft/vscode/issues/21801#issuecomment-284746137 explains the issue and offers a workaround for the Insiders Channel builds.
