### ISSUE TITLE
JSLint error with ES2017 Decorator

### ISSUE THREAD

**Issue by AntSworD** [Microsoft/vscode#22198]
- VSCode Version: 1.10.1 (1.10.1)
- OS Version: MacOS sierra 10.12.3 (16D32)

When use decorator with koa:
![image](https://cloud.githubusercontent.com/assets/2549087/23694292/fe4d893e-0413-11e7-9707-e115ab918935.png)

I got: 
![image](https://cloud.githubusercontent.com/assets/2549087/23694306/11c399ea-0414-11e7-9995-2f78cb9f4db6.png)

My setting:
.babelrc:
```
{
  "presets": ["es2015", "es2017"],
  "plugins": [
    "transform-decorators-legacy",
    "transform-runtime",
    "add-module-exports"
  ]
}
```
jsconfig.json:
```
{
  "compilerOptions": {
    "target": "ES6",
    "module": "commonjs",
    "experimentalDecorators": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14587
