### ISSUE TITLE
Option to disable sidebar sync

### ISSUE THREAD

**Issue by imoby** [Microsoft/vscode#22192]
Description: Add option to disable automatically navigating to a file in tree view/sidebar when searching with go to file

- VSCode Version: 1.10.1
- OS Version: macOS (all)

Steps to Reproduce:

1. Have sidebar/tree view open with multiple files searchable
2. Initiate go to file (command+p) and navigate to file
3. Observe in the sidebar/tree that it automatically navigates to the file in the tree view

**Comment by bpasero** [comment]
`"explorer.autoReveal": false`

**Comment by imoby** [comment]
@bpasero thanks man! I would suggest giving that a better name though.
