### ISSUE TITLE
Extension walkthroughs do not launch upon install

### ISSUE THREAD

**Issue by katiesavage** [microsoft/vscode#221964]
Does this issue occur when all extensions are disabled?: Yes/**No**, this is an extension-related issue that arises across extensions with walkthroughs

- VS Code Version: 1.91.1
- OS Version: Windows 11

Extension walkthroughs are not launching upon install. Expected behavior: walkthrough launches automatically upon install.
Tested on C# Dev Kit extension and Python extension. Seemed to work in 1.90.0 but does not work in 1.91.1.

Steps to Reproduce [Windows Sandbox]:

1. Launch a Windows Sandbox
2. Open Edge and download VS Code (stable) from the VS Code website
3. Install the C# Dev Kit extension. 
*Note:* Upon install the walkthrough is supposed to launch automatically. This is not happening, but I can manually open the walkthrough using these steps.
4. Open command palette. 
5. Use command 'Welcome: Open Walkthrough'
6. Select 'Get Started with C# Dev Kit'
![image](https://github.com/user-attachments/assets/434706d5-f6f6-4f04-918b-44af6600acef)

7. Repeated steps 3-7 with the Python extension. Same behavior.

Steps to Reproduce [VS Code stable and VS Code insider]:

1. Open VS Code
2. Uninstall C# Dev Kit (if you have it installed)
3. Reload VS Code
4. Install C# Dev Kit extension.
5. *Note:* Upon install the walkthrough is supposed to launch automatically. This is not happening, but I can manually open the walkthrough using these steps.
4. Open command palette. 
5. Use command 'Welcome: Open Walkthrough'
6. Select 'Get Started with C# Dev Kit'
7. Repeated steps 2-7 with the Python extension. Same behavior.

**Comment by rzhao271** [comment]
\closedWith 0c5a528

**Comment by meganrogge** [comment]
@bhavyaus using the steps above, I am not seeing the walkthrough open when I reinstall the extension

**Comment by roblourens** [comment]
Was just talking with @bhavyaus about this- if you've had it installed in the past, it won't work, but for me it works in a window with a clean user-data-dir
