### ISSUE TITLE
Terminal suggestions are highlighting for the completion text, not the label

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#221953]
Repro:

1. Open pwsh
2. Create a `test` folder
3. Type `yarn t`

![image](https://github.com/user-attachments/assets/fe56084b-8626-4873-ad4f-d8ba8d1cac57)

This is happening because the actual completion that will happen is `.\test` where the highlights would make more sense.

**Comment by alexr00** [comment]
Verified, but the font is strange:


![Image](https://github.com/user-attachments/assets/442f0f75-2369-48d1-b200-abe0a2df7fd2)

**Comment by Tyriar** [comment]
@alexr00 that's fixed but was only merged an hour ago https://github.com/microsoft/vscode/pull/223507
