### ISSUE TITLE
about "Process exiting with code: null"

### ISSUE THREAD

**Issue by Nivea01** [Microsoft/vscode#22193]
- VSCode Version:1.10.1
- OS Version:macOs 10.12.3

1. shell command: go env
GOARCH="amd64"
GOBIN="/Users/xxxxxxx/Development/gocode/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xxxxxxx/Development/gocode"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
...

2.
workspace:  "/Users/xxxxxxx/Development/gocode"     <-- same as $gopath
file:       "/Users/xxxxxxx/Development/gocode/src/nivea.net/nivea/nivea.go"

3. test file: nivea.go
package nivea
import "fmt"
func main() {
	fmt.Println("Hello World!")
}

4. launch.json
{
    "version": "0.2.1",
    "configurations": [
        {
            "name": "Launch1",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "/Users/xxxxxxx/Development/gocode/src/nivea.net/nivea/nivea.go",
            "env": {"GOPATH":"/Users/xxxxxxx/Development/gocode"},
            "args": [],
            "showLog": true
        }
    ]
}

5. settings.json
{
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.buildTags": "",
    "go.buildFlags": [],
    "go.lintTool": "golint",
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.testOnSave": false,
    "go.coverOnSave": false,
    "go.useCodeSnippetsOnFunctionSuggest": false,
    "go.formatOnSave": true, 
    "go.formatTool": "goreturns",
    "go.formatFlags": [],
    "go.goroot": "/usr/local/go",
    "go.gopath": "/Users/xxxxxxx/Development/gocode",
    "go.inferGopath": false,
    "go.gocodeAutoBuild": false
}

and  it always show  "Process exiting with code: null" on debug window.

Could you help me to know what happened in this issue?
maybe i missed some settings...

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-go#847
