### ISSUE TITLE
Tyriar unprofessional behaviour regarding bug report. (Issue #214674), why?

### ISSUE THREAD

**Issue by michal-gora** [microsoft/vscode#221958]
Regarding Issue #214674 https://github.com/microsoft/vscode/issues/214674

@Tyriar **cannot read or understand that there is a bug** regarding "terminal.integrated.altClickMovesCursor": false.
Closes and locks issue without proper reason, only that it would mean to have to add
> a new setting in vscode and it's just not worth it.
when it is not about adding a new setting, just fixing an existing one, or am I not understanding it right? (but even then dont lock the issue)

This is **not** a feature request. It's a bug report. This setting "terminal.integrated.altClickMovesCursor" does not work, wether set to true or to false, it always changes the cursor to a plus.
None of his answers even regard anything being written. There is multiple people writing that they have the same issue and trying to explain with Tyriar just ignoring, anyone ever said anything. Instead closing and locking the issue to not give the chance to even dispute his understanding because he clearly does not.
There is no possible workaround to sending ALT to the console. Except opening an external Terminal of course which is a dealbreaker for some applications like VSCode plugins. ALT + arrow is for example often used to quickly navigate recommendations of a console program. It is not that rare to need ALT in the console.

**I would like for someone else to be assigned to this issue.**

**Comment by Tyriar** [comment]
Please stop spamming the repo. As I said before you're misunderstanding and **the cursor change is unrelated to that setting**.
