### ISSUE TITLE
Too many menus

### ISSUE THREAD

**Issue by khuangia** [Microsoft/vscode#22190]
If you provided CTL+SHIFT+P, why add so many stupid menus??????????

**Comment by imoby** [comment]
I dont think its always fair to assume that everyone favors keyboard shortcuts (I do of course though).

**Comment by bpasero** [comment]
@khuangia what menu specifically "is stupid"?

**Comment by khuangia** [comment]
you are right. not everyone think moving a  mouse is an expensive thing during coding. maybe he is just view a txt file
