### ISSUE TITLE
Find widget too wide

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2220]
On Mac the find widget is too wide, the matches space is too large, especially in this case when I have single digit numbers. Due to this the lower checkboxes seems misaligned

![screen shot 2016-01-25 at 09 54 38](https://cloud.githubusercontent.com/assets/1926584/12546393/c93654ee-c349-11e5-8725-58a8b2012a0b.png)

**Comment by alexandrudima** [comment]
@stevencl Feedback starts to come in :)

**Comment by stevencl** [comment]
@alexandrudima What would it take to align the replace and replace all buttons? Ideally I would think they would be left aligned (i.e., the left most edge of the replace button is left aligned with the index while the left most edge of the replace all button is left aligned with the count).

Is the 'of' in '1 of 2' in a fixed position or does it move to the right when the count is more than one digit? How feasible (and desirable) do you think it would be to refresh the layout when the count and index change?

**Comment by c5inco** [comment]
Yeah I just saw this in the latest update.  I see the value but it definitely needs some UX love.  As @isidorn stated, it makes the widget way too wide (think split editor scenarios) and when expanded everything looks poorly aligned.  I would considering place that text actually left aligned underneath all the controls, to look more like status text.  

I don't have a mock for you unfortunately, but I think @bgashler1 can help you out there.  Or if I have free cycles later this month. ;)

**Comment by stevencl** [comment]
@bgashler1 - can you mock this up and then work with @alexandrudima on this?

**Comment by bgashler1** [comment]
Sure no problem.

**Comment by bgashler1** [comment]
This is my proposal
![2220-find-and-replace-b](https://cloud.githubusercontent.com/assets/11839736/12939466/ccb9e798-cf74-11e5-8aac-c80ac3e06beb.gif)

![2220-find-and-replace-c](https://cloud.githubusercontent.com/assets/11839736/12939614/366ddad6-cf76-11e5-992a-aee6cd0f0b17.png)

We can address alignment problems between index/count and the adjacent buttons by changing the max-width as pictured above.  `.monaco-editor .find-widget .matchesCount { min-width: 46px; }`

Thoughts?

**Comment by bgashler1** [comment]
Just talked with Isidor, and we need 4 digit support.  Max value (999+).

**Comment by rebornix** [comment]
As we already have some investigation under this issue, let's use this issue to track the Find Widget position/size issue.

**Comment by rebornix** [comment]
I don't have a good idea about how to handle those whitespaces right this moment. Push it to later iteration.

**Comment by snys98** [comment]
Maybe the widget should be **resizable**, or moved to the bottom of document view? It feels awful when I'm trying to write a long regex.

**Comment by isidorn** [comment]
fyi @misolori maybe you have some good idea and if you also think this is an issue we can consider to reopen this

**Comment by rebornix** [comment]
I mark this as out-of-scope because I don't know yet how to make this possible but not making it complex. If @misolori has ideas of improving the find widget in anyways, we can reopen it.
