### ISSUE TITLE
Can generate html directly from markdown preview?

### ISSUE THREAD

**Issue by bluesky139** [Microsoft/vscode#22208]
I'm using markdown and the preview is very nice, I can see instant preview while typing, but when I use other tool to generate html, it always not as I expect, or I have to adjust markdown source again and again. (Preview is not useful for me anymore)

So does VSCode support to generate html from preview directly? Or this is a new feature request.

**Comment by rhires** [comment]
I had this question about a year ago: #4481 - and yes, it's a feature request. I haven't kept up with this issue since I raised it, so I have no idea if anything has changed on that front.

**Comment by mjbvz** [comment]
We use markdown it for generating the html. Here are instructions on setting up a task to generate html from markdown: https://code.visualstudio.com/Docs/languages/markdown#_compiling-markdown-into-html You still have to bring your own stylesheets.

Exporting the preview html exactly as it appears in the editor is not a scenario we are targeting. Instead, I recommend creating a custom style stylesheet that works for both the preview and the exported html: https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css
