### ISSUE TITLE
Add ability to change snippets icon

### ISSUE THREAD

**Issue by BrunnerLivio** [Microsoft/vscode#22206]
I would like to colorize or optionally add a own icon for snippets. 

Use Case:

I have snippets, which "converts" to hex codes. I don't want to write a whole extension, just to see the color of the outcoming hex code.

Example Image: 
![Example Image](http://i.imgur.com/phIWHZA.png)

A solution to add styling could be :
```JSON
"Material Active Icon Light": {
	"prefix": "md-active-icon-light",
	"body": [
		"rgba(255, 255, 255, 1)"
	],
        "display": {
                 "style" : {
                         "background-color": "green" 
                 }
        }
}
```

**Comment by GriNAME** [comment]
+

**Comment by GriNAME** [comment]
I like how it looks is Atom
 
![image](https://cloud.githubusercontent.com/assets/8003716/23745108/1290a822-04c8-11e7-955e-84d52051bd83.png)

**Comment by jrieken** [comment]
You can achieve this when not using snippets but a `CompletionItemProvider` that returns completions of type `color`. Our css/less/sass tooling does exactly that. 

![screen shot 2017-03-09 at 11 10 56](https://cloud.githubusercontent.com/assets/1794099/23745610/19dcf1e4-04b9-11e7-835c-883382372965.png)

**Comment by BrunnerLivio** [comment]
@jrieken Thanks for the response!

I know that it is possible using CompletionItemProvider. But do you consider adding this option also to a snippets configuration? So it would be easy for everyone to add color preview.

**Comment by aStonedPenguin** [comment]
@jrieken That's a bit much for most use cases don't you think? Custom colors/icons would be a great way to make use of the limited text space with snippets.

**Comment by jrieken** [comment]
> So it would be easy for everyone to add color preview.

I'd learn more about this. It seems you think having a completion item provider isn't easy? Why is that? You shouldn't need much more than this

```ts
    vscode.languages.registerCompletionItemProvider('abc', new class implements vscode.CompletionItemProvider {
        provideCompletionItems(doc, pos) {

            return [
                this._createColorItem('$color-accent', 'rgb(0, 122, 204)'),
                this._createColorItem('$color-bg-dark', '#0000cc'),
                this._createColorItem('$color-bg-light', 'HSL(30%, 100%, 50%)'),
            ];
        }
        private _createColorItem(label: string, color: string) {
            let item = new vscode.CompletionItem(label);
            item.documentation = color;
            item.kind = vscode.CompletionItemKind.Color;
            return item;
        }
    }());
```

**Comment by BoomRaccoon** [comment]
I was wondering why this has been layed off. I would love to have the option to add the default icons VSCode uses.
Having a visual help to differentiate between methods, objects and properties is great. And an additional JSON-key to add a background-color to snippets would make it clear which snippets are user defined.
