### ISSUE TITLE
`workbench.list.defaultFindMode: "filter"` not respected

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode#222081]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: `1.91.1`
- OS Version: `Microsoft Windows [Version 10.0.19045.4651]`

Steps to Reproduce:

1. Change setting: `"workbench.list.defaultFindMode": "filter"`
2. Open a folder with a few files
3. Run `Explorer: Focus on Folders View` command (`workbench.explorer.fileView.focus`)
4. Type some keyword to filter files.
5. Nothing filtered like before. I can only focus to specific files when typing match prefix of the filename.

I expected to filter items just like before.

**Comment by IllusionMH** [comment]
If you expect "filter on type" feature - it was removed some time and replaced with keybinging.
Keybinging was recently changed https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding
