### ISSUE TITLE
vscode crash

### ISSUE THREAD

**Issue by DanneLeung** [Microsoft/vscode#22203]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.12.0|
|vscode-node-readme|bengreenier|1.0.7|
|tortoise-svn-for-vscode|cdsama|0.1.1|
|vscode-eslint|dbaeumer|1.2.7|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|beautify|HookyQR|0.8.9|
|minify|HookyQR|0.3.0|
|webpack|jeremyrajan|1.0.0|
|vscode-todo|MattiasPernhult|0.8.0|
|vscode-jade-snippets|mrmlnc|1.0.1|
|vscode-pugbeautify|mrmlnc|1.0.2|
|vetur|octref|0.5.1|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.3.0|
|sass-indented|robinbentley|1.3.0|
|lodash-snippets|tomphilbin|0.8.0|
|vscode-react-native|vsmobile|0.3.1|
|babelrc|waderyan|1.0.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|html2jade|wmaurer|0.2.0|
|join-lines|wmaurer|0.2.2|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@DanneLeung any info?

**Comment by DanneLeung** [comment]
Many typescript errors shown up!  Then, I reinstalled the latest version, it's work now!
