### ISSUE TITLE
Search and replace bug

### ISSUE THREAD

**Issue by BerendKemper** [microsoft/vscode#222031]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91.1
- OS Version: Windows_NT x64 10.0.19045
![image](https://github.com/user-attachments/assets/53374f18-c26f-4c80-be5b-325f26a8040c)

Steps to Reproduce:

1. Use the global Search feature in order to find certain string occurences in your repository (in my case ```up: `out` ```)
2. For 70 files inside the repository replace the matching string occurence with another string (in my case ```op: `in` ```).
![image](https://github.com/user-attachments/assets/62a2d532-bf80-41ad-b1ee-dde22df5b774)
3. It can turn out that a few of these files are incorrectly handled by the global search and replace feature.

Proof below in the form of screenshots:
![image](https://github.com/user-attachments/assets/651c2a00-95f0-4d7b-b553-616d147f87a4)
![image](https://github.com/user-attachments/assets/501f5587-92b0-47d1-8399-6fbc5ecfb96a)
![image](https://github.com/user-attachments/assets/0ff72bb5-b965-40ed-8e2f-837b8d6096db)
![image](https://github.com/user-attachments/assets/6a24b8a6-dbbf-45dc-935f-8f46deff4a4d)
![image](https://github.com/user-attachments/assets/1ab2d44c-a3c8-4a1a-9174-37d1ae817cd4)
![image](https://github.com/user-attachments/assets/93fede97-9428-4be8-a22d-8f086ef38a79)
![image](https://github.com/user-attachments/assets/03a1417a-6ce5-4534-a184-e0bbc900d27c)
![image](https://github.com/user-attachments/assets/1564fdfc-de3c-407e-9c4e-912009609e81)

**Comment by BerendKemper** [comment]
My collegue tells me he experiences the same issue occasionally.

**Comment by andreamah** [comment]
Hmm.. that's strange. when it first matches, does it match the correct ranges? Do you have a repo that I could test with?

**Comment by BerendKemper** [comment]
Please give me some time to provide an example repository.
The repository where it is taking place is not public and owned by my employer. 
I cannot share the repository from my employer.
Can provide a repository over the weekend.

**Comment by BerendKemper** [comment]
I am adding some screenshots from git differences in order to help this ticket  and or [ticket 223289](https://github.com/microsoft/vscode/issues/223289).

74 files were changed during a single search and replace action.
Amongst these 74 files:
- 6 files were corrputed and had two instances of keywords that were meant to be replaced.
- 27 files were not corrputed and had two instances of keywords that were replaced.
- 41 files were not corrupted and had one instance of keywords that were replaced.

## 6 corrupted files - 2 instances keywords:

![image](https://github.com/user-attachments/assets/cb96cfa8-d724-4007-aeee-489a66d064b7)

![image](https://github.com/user-attachments/assets/d11886d6-6291-4df9-b3ec-8530611454f9)

![image](https://github.com/user-attachments/assets/c68b30e2-854d-430b-849e-bf54b8acfab0)

![image](https://github.com/user-attachments/assets/7d01a562-d151-4e49-b9b6-a4bc8e149ec6)

![image](https://github.com/user-attachments/assets/0a8a7586-5ef0-47da-91e0-eebc4a87e021)

![image](https://github.com/user-attachments/assets/7911cd9b-1a5a-48ae-b6e1-7c268a8ecea3)

## 27 not corrupted files - 2 instances keywords:

![image](https://github.com/user-attachments/assets/245173c3-2354-4d96-a43b-e9db6a613015)

## 41 not corrupted files - 1 instance keyword:

![image](https://github.com/user-attachments/assets/7f1700c4-0016-40fe-9ddd-2b3c6a195194)

**Comment by andreamah** [comment]
That's really strange. In the issue you linked, it was a different issue because the corrupted lines were the ones that had multiple matches in one line. However, it seems like there's no matches that were meant to be on the same line. Do you have a repo that I can clone to try to reproduce this?
