### ISSUE TITLE
Feature Request: Setting shortcut

### ISSUE THREAD

**Issue by Ne-Ne** [Microsoft/vscode#22204]
I would like a keyboard shortcut to be present for the editor.

Often I like to enter the settings panel. The addition of a keyboard shortcut would create 1 less click for the end user.

**Comment by hoovercj** [comment]
Are you asking for something different than `workbench.action.openGlobalSettings` or `workbench.action.openWorkspaceSettings`? Those are commands that you can configure to have keyboard shortcuts

**Comment by ramya-rao-a** [comment]
@Ne-Ne Like @hoovercj mentioned above you can bind your own keyboard shortcuts to open the settings.
