### ISSUE TITLE
Markdown: Add a baseUrl setting to improve handling of image file paths (and other media)

### ISSUE THREAD

**Issue by harrislapiroff** [microsoft/vscode#222020]
It's common to have HTML or Markdown files that reference other files (links, images, etc.) using absolute URLs. Sometimes this absolute URL doesn't share the project root, though. For example, a common structure for a static site builder project might be:

```
/
├ config.js
├ ... [other config files]
└ src/
  ├ media/
  │ └ ... [image files]
  └ posts/
    └ ... [markdown files]
```

Then, if I put the following in a markdown file

```md
![image](/src/media/image.png)
```

I get a nice little preview like so:

<img width="559" alt="image" src="https://github.com/user-attachments/assets/eb747f84-1739-4b1f-a7d0-751aad47024f">

But unfortunately, since `src/` is the root of my server directory, the path I need for my site builder to serve my site correctly is:

```md
![image](/media/image.png)
```

which gives me a sad broken image:

<img width="482" alt="image" src="https://github.com/user-attachments/assets/7055519a-74d1-4141-b7ae-05c8b79cb8d9">

A `baseUrl` setting could allow VSCode to handle image paths more elegantly. (This could also improve path generation when using the nice "paste image" feature in the markdown support.)

**Comment by mjbvz** [comment]
Duplicate of #114319
