### ISSUE TITLE
Breakpoint Line Number incorrect/changes

### ISSUE THREAD

**Issue by theSonGoku1991** [microsoft/vscode#222028]
Hello,

upfront: I am pretty new to github and since my previous issue https://github.com/microsoft/vscode/issues/220550 is stuck in ~info-needed even though I added information in form of comments and updated the thread itself, I decided to open a new one. Feel free to share with me, what I can do next time to get "rid" of the ~info-needed label.

So, to the issue:
When using Visual Studio Code and adding breakpoints, most of the time I notice that the line I set the breakpoint for does not match the label on the right to the breakpoint in the debugger.

Alot of the times, it is not even clear to me whether the breakpoint has really been set now or not, because the indicator sometimes is just an empty circle with a white contour and other times it is red as it should be.

VS Code also seems to add the breakpoint to the bottom left list two times/three times here and there.

I am using Flutter and Dart. My current VS Code version is 1.91.0 (user setup), but I have had that issue for month, it just did not annoy me enough to create an issue for it yet (and, I am not yet skilled enough with github and all of that stuff). The platform I am developing for are mobile apps for android and ios. I am coding on Windows 10.

It is even the case that I have to click into the line for the breakpoint several times until the label in the debugger shows the actually correct break point line (for example, when the breakpoint is in line 260, at happens that I press and get 272, then 270, then 240 etc. until I get 260 after like 4-5 clicks in the very same line).

The debugger also sometimes hangs itself up, meaning I have to restart the emulator and the debugger.

In this video you see

- VS Code not setting the breakpoint I wanted to set multiple times in a row
- VS Code changing the line number of the breakpoint I want to set multiple times in a row, even though the line does not change
- VS Code (not really but you know what I mean) adding the breakpoint twice instead of once
I would also like to add that it happens to me occasionally that the debug bar with stop, continue etc. does not show (not even in the main.dart file).

Its no breaking bug but really annoying and likely not how it is supposed to be.

Regards
Thomas

**Comment by roblourens** [comment]
Sorry for the slow response, the previous issue is somewhere buried in my notifications :)

Responding on the original issue
