### ISSUE TITLE
markdown.showToolbar not dispayed when set up correctly for Learn Authoring Pack

### ISSUE THREAD

**Issue by magjanas** [microsoft/vscode#222039]
Type: <b>Feature Request</b>

Hello,
I have enabled the Markdown Show Toolbar setting for Learn Authoring Pack as described in the instructions, and the toolbar is still not displayed at the bottom of the page. How to resume the toolbar. 

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by mjbvz** [comment]
I think that setting comes from that extension. Please file an issue against them
