### ISSUE TITLE
Option for tasks.json 2.0.0 to always run task in new terminal

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#22202]
Hi!

- VSCode Version: 1.10.1
- OS Version: macOS Sierra

I would be great to have a possibility to set a task property to e.g. `openNewWindow: true` and it will always run such task in a new terminal window.

Thanks.

**Comment by ramya-rao-a** [comment]
cc @Tyriar

**Comment by Tyriar** [comment]
@obrejla I'm curious what your specific use case is for this?

**Comment by obrejla** [comment]
That's simple... I run tests by Tasks and I want previously ended runs in separate windows so I can see the previous results. Currently, previous results are shifted/removed from the terminal after running some next task. Thanks!

**Comment by Tyriar** [comment]
@obrejla The previous output is removed? I was under the impression that the previous output remained above the new output. Do you need to up your terminal scrollback to retain more than 1000 lines?

```js
"terminal.integrated.scrollback": 5000,
```

**Comment by obrejla** [comment]
I already have a big scrollback, but our codebase has almost 7000 tests for now, so running them produces tens of thousands of lines... And even if I set a really big number for scrollback, I definitely don't want to scroll such a big number of lines or try to find out "which run of test was this error from...is it from the first run? Eleventh run? Or what run??". It would be absolutely uncomfortable... In such case, there is no benefit from running my tasks from Code, because running such tasks in one window is a blocker. Creating new output windows for tests works great in other editors/IDEs (e.g. NetBeans) and it is awesome. So it would be really great to have such possibility in Code to mark a Task so it opens new window for each run. Thanks.

**Comment by Tyriar** [comment]
@dbaeumer this feels more like a setting rather than a task config value since it defines a user preference?

**Comment by dbaeumer** [comment]
@Tyriar I do think that there are scenarios where task a wants a fresh terminal (for example tests) and task b (some webpack runner) can reuse a terminal since the output is not very interesting.

**Comment by dbaeumer** [comment]
The got added to the task 2.0.0 runner using the new presentation.panel attribute.
