### ISSUE TITLE
Viewing temporarily unzipped files using 7-Zip

### ISSUE THREAD

**Issue by vojtechhabarta** [Microsoft/vscode#22207]
I would like to use VSCode also in the following use case:
- configure 7-Zip to use VSCode as editor
- open zip file in 7-Zip, select compressed file, hit F4
- file should open in VSCode

Currently the behavior varies:
- the file is opened in VSCode but it is immediately closed (in most cases)
- VSCode displays an error saying that file was not found (sometimes)
- file stays open in VSCode as expected (exceptionally) 

This feature could probably be implemented by #11642 but maybe it is not enough.

Currently I use Notepad++ for opening those files in which case
1. 7-Zip somehow knows that the file is being viewed and it doesn't delete it
2. Notepad++ asks user whether it should keep deleted file opened when 7-Zip already deleted the file

- VSCode Version: 1.10.1
- OS Version: Windows 10

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14534

**Comment by bpasero** [comment]
With todays insider build (get it from http://code.visualstudio.com/Download#insiders) there is a new setting `workbench.editor.closeOnFileDelete` that will keep editors open when set to `false` provided that the file has been deleted outside of Code. This might help in this case here, please let me know.

**Comment by vojtechhabarta** [comment]
Great, thanks. So far it works as expected.
I also like "(deleted from disk)" marker.
And I vote for making this default.
Thanks again.

**Comment by bpasero** [comment]
Awesome 👍

**Comment by Lukas238** [comment]
Hi,

I'm trying to edit a html file from inside 7zip using vsCode as the configured editor (html files opens in Chrome by default in Windows).

```"workbench.editor.closeOnFileDelete": false``` have not effect on vsCode 1.17.2 and 7-zip 9.20. :(

On editing the file in 7zip, nothing happens. 7Zip works fine if I edit in notepad.exe, or Notepad++.

Thanks!
