### ISSUE TITLE
Debugger doesn't stop at a breakpoint which is set in my extension's code

### ISSUE THREAD

**Issue by KalitaAlexey** [Microsoft/vscode#22201]
Hello everyone.

Visual Studio Code's version: 1.10.1
OS: Windows 10, Ubuntu 16.04, Fedora 25

At first, I tried it with my extension, it didn't work.

I created a new one via `yo code`, chose **TypeScript**.
I set a breakpoint at the beginning of `activate()`.
I ran it.
It didn't stop.

I modified **launch.json** in order to set `"stopOnEntry"` to `true`.
I ran it again.
It stopped.

**Comment by isidorn** [comment]
It seems like your extension is not getting activated.
If you put a console.log message in your activate does not log get printeted?
Please try creating a vanilla extensoin using the yo code generator and you will see that you nicely hit breakpoints.

**Comment by KalitaAlexey** [comment]
@isidorn,
Read the description more carefully.
I did `yo code`. I created a new one.
The extension is activated (I tried console.log).

**Comment by weinand** [comment]
This is the expected behaviour. 
If an extension is activated early and if you want to debug the activation code it is necessary to set `stopOnEntry` to true. Without it registering the breakpoint might come too late because the extension might already be done with executing the activation code.

**Comment by KalitaAlexey** [comment]
Where is that documented?

**Comment by weinand** [comment]
https://code.visualstudio.com/docs/editor/node-debugging#_launch-configuration-attributes
