### ISSUE TITLE
HTML IntelliSense not working.

### ISSUE THREAD

**Issue by edDimensi** [Microsoft/vscode#22209]
- VSCode Version: 1.10.1
- OS Version: Ubuntu 16.04

In .html files intelliSense not work. 

![image](https://cloud.githubusercontent.com/assets/11390039/23701252/1d3b153a-0407-11e7-8310-afbf1dd53678.png)
![image](https://cloud.githubusercontent.com/assets/11390039/23701266/28b538aa-0407-11e7-9607-70afa584abc2.png)

**Comment by ramya-rao-a** [comment]
Can you close all VS Code windows and run `code --disable-extensions` in the terminal and try again?
This is to ensure that none of the extensions are interfering and causing this issue

**Comment by edDimensi** [comment]
![image](https://cloud.githubusercontent.com/assets/11390039/23719873/ffb34d4c-044d-11e7-9acd-7f00ba980a02.png)

**Comment by aeschli** [comment]
Use intellisense after a `<` character to see proposals for html tags.
![image](https://cloud.githubusercontent.com/assets/6461412/24057879/4bb28468-0b49-11e7-932c-f8444926774f.png)
