### ISSUE TITLE
Detection of tasks  does not work with tasks 2.0.0

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#22200]
Hi!

- VSCode Version: 1.10.1
- OS Version: macOS Sierra

Steps to Reproduce:

1. started Code and let it detect all tasks (tasks.json generated with 0.1.0)
2. "cmd+p task" ...and all my tasks provided by grunt file are there, so far so good
3. added one custom modified task to tasks.json
4. tried to run that task...still works
5. changed version of tasks from 0.1.0 to 2.0.0
6. "cmd+p task" ...and only my explicitly defined task is there, any other task from grunt file :/
7. explicit task can be run without any problem...but any other task

Thanks!

**Comment by dbaeumer** [comment]
Actually we are debating whether this auto task detection is something we want to bring back in 2.0.0. Reason is that this is currently only supported for grunt and gulp and there are valid concerns why we treat these so special.

@obrejla how much would you be hurt if this would go away?

**Comment by obrejla** [comment]
It depends... 

When I want to e.g. pass some arguments to my grunt task by vscode automatically, then I need to rewrite it to tasks.json manually. That seems to be ok, BUT...then only that one specific task could be run from vscode commands dialog, all other tasks will need to be written manually in Terminal windows. Which is a bit strange...one task can be run from vscode infrastructure and others can't. 

Or you can rewrite all tasks from gruntfile to tasks.json manually, which is an overkill I think. Especially when tasks in gruntfile change. You must track such changes in codebase and make corresponding changes in tasks.json manually again...

So for me, it makes sense to have an auto detection of grunt tasks (e.g. NetBeans have such autodetection as well and it's great ;).

Thanks!

**Comment by obrejla** [comment]
Uff...now I have almost 2 weeks of such "no-detection" experience and it is very bad :/ Our project has really lot of tasks and all of them are occasionally needed...so from the switch to v2.0.0 without detection, there is not a day without duplicating a task to `tasks.json` :( I hope this experience will help you deciding to re-add auto-detection. Thanks a lot!

**Comment by dbaeumer** [comment]
I am working on it :-). The new terminal runner will get official API so that extension can contribute tasks via API. This will allow us to get rid of the pre-supported runners in our core but we depend on the community to provide the extensions to detect tasks in the various task runners out there.

**Comment by dbaeumer** [comment]
Merged grunt support into master for the next release.
