### ISSUE TITLE
It's impossible to provide icons that always look correct

### ISSUE THREAD

**Issue by Maddimax** [microsoft/vscode#222021]
Type: <b>Bug</b>

When adding icons to an extension for a language they always look misaligned with the default "seti" icon theme. It looks like the margins are off between svg and font icons.

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv|--log theqtcompany.qt=error --crash-reporter-id 4803c9bb-a4d3-4855-8582-bdc75d6ed146|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.6
cursor-charcode|but|0.9.2
regex|chr|0.4.0
xml|Dot|2.5.1
viml|dun|0.1.7
gitlens|eam|15.2.0
vsc-material-theme-icons|equ|3.6.1
copilot|Git|1.214.0
copilot-chat|Git|0.17.1
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.92.0
go|gol|0.42.0
cpp-reference|Guy|0.2.3
debug-visualizer|hed|2.4.0
rest-client|hum|0.25.1
better-cpp-syntax|jef|1.27.1
vscode-clangd|llv|0.1.29
crumbs|luk|0.1.6
base64|m4n|1.0.0
vscode-qrc|Mar|1.0.0
theme-monokai-pro-vscode|mon|1.3.2
vscode-docker|ms-|1.29.1
vscode-dotnet-runtime|ms-|2.1.1
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
cmake-tools|ms-|1.19.24
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
live-server|ms-|0.4.14
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
vsliveshare|ms-|1.0.5936
bun-vscode|ove|0.0.12
tmlanguage|ped|1.0.0
material-icon-theme|PKi|5.6.0
vscode-yaml|red|1.15.0
schemastore|rem|1.0.161
synthwave-vscode|Rob|0.1.15
vscode--gerrit|San|1.2.41
lua|sum|3.9.3
ninja|sur|0.0.1
qt-official|the|0.9.1
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31094925
pythonrstrctxtcf:31093870
1iic9185:31097392

```

</details>

**Comment by aeschli** [comment]
Sample code?

**Comment by RedCMD** [comment]
if I grab the seti JSON svg icon
https://github.com/jesseweed/seti-ui/blob/master/icons/json.svg

and shove it into my extension
![Image](https://github.com/user-attachments/assets/826e55a3-cae0-4cba-8d89-33ed6160e00f)

you will see it doesn't line up
![Image](https://github.com/user-attachments/assets/fadd95c6-5bf3-4c2a-9ea2-b2a6431f2a1e)

VSCode handles built-in icons differently to extension ones

**Comment by aeschli** [comment]
It's a fundamental weakness of language icons and a reason we hesitate long to provide the feature: There's no icon that fits all file icons theme's out there: Be it size, margins or looks. 
-> You have to find a compromise that goes well with the major themes
-> You have to fiddle margins and sizes
-> If your language is widely used, you want to look into file icon themes to provide an icon for your language

Language icons are rendered the same way as file icons themes based on SVG. Ideally use a 16 x 16 px SVG

Closing the issue, as I don't see how we can improve the situation. Language icons are intended to be a fall back and only used for rarely used language.

**Comment by Maddimax** [comment]
I've experimented with the dev tools a little and replaced certain icons from the font with a simple 'X' content:
<img width="195" alt="Image" src="https://github.com/user-attachments/assets/7c17aa96-fff5-49be-a6ad-dc1d014f3f20" />

You can see that the X is nicely centered under the SVG, while the icons from the font are misplaced.

<img width="202" alt="Image" src="https://github.com/user-attachments/assets/07bd8b08-8b53-41ac-abb5-d81e887da5c9" />

(I've added "text-align: center", and replaced content with 'X')

So it seems the issue is with the Font directly (and the missing text-align:center in vscode)

**Comment by RedCMD** [comment]
> Language icons are rendered the same way as file icons themes based on SVG. Ideally use a 16 x 16 px SVG

@aeschli VSCode uses the Seti icons right?
then how come when I use the Seti icons
VSCode renders them incorrectly?

shouldn't VSCode render the exact same icon the exact same way?

[seti-ui-theme-and-vs-code-icon-pack](https://github.com/jesseweed/seti-ui/tree/master?tab=readme-ov-file#seti-ui-theme-and-vs-code-icon-pack)
> This repo contains the latest version of the Seti UI theme. It contains the default icons used in [VS Code](https://code.visualstudio.com/).

**Comment by aeschli** [comment]
The Seti theme is defined an icon font. The [seti-ui](https://github.com/jesseweed/seti-ui/) repo (not owned/controlled by us) has the script to generate the icon font from SVGs. From that and other metadata we generate the Seti icon theme:
https://github.com/microsoft/vscode/blob/f283262be0d06d0c6759e52c1c47fbde06e2b172/extensions/theme-seti/icons/vs-seti-icon-theme.json

The HTML/CSS for showing a SVGs and an icon font is quite different.
