### ISSUE TITLE
Text "edt mru" in "show opened file list" only on linux

### ISSUE THREAD

**Issue by saiballo** [microsoft/vscode#222029]
When I open the panel  "show opened file list", the message "edt mru" always appears. This behavior forces me to delete the text every time to perform a search. The issue seems to appear only on Linux.

Does this issue occur when all extensions are disabled?: Yes

    VS Code Version: latest
    OS Version: Mint 22

Steps to Reproduce:

    Press Ctrl+E
    Observe garbage text in the input: "edt mru"

![Senzanome](https://github.com/user-attachments/assets/a752f75b-2ba1-4d37-b655-fb3e0bc389d4)

**Comment by TylerLeonhardt** [comment]
This is working as expected. If you wanna perform a file search, you wanna do `ctrl+p`. The `edt mru` is defined here:
<img width="523" alt="image" src="https://github.com/user-attachments/assets/42f9bb57-0923-4618-a2be-76ca0b3843fc">
"Show all opened editors by most recently used"

They keybindings are configurable too if you wanna change them.
