### ISSUE TITLE
whether can get full type of variable when pop up completion item list?

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#2221]
when user type c# code in vscode, it will trigger the intellisense, but the completionitem didn't show the full type of variable ,anyone know how to get it in vscode source?

![atest](https://cloud.githubusercontent.com/assets/15098626/12546846/98fc9d90-c387-11e5-8fc9-ea5aa7447624.png)

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#19
