### ISSUE TITLE
terminal very slow response 

### ISSUE THREAD

**Issue by pragadeesh-735** [microsoft/vscode#222181]
Type: <b>Performance Issue</b>

i am employee please resolve the issue

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 7520U with Radeon Graphics          (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.28GB (1.87GB free)|
|Process Argv|--crash-reporter-id fa60bc29-0630-4967-b8e4-f2874e3204df|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   111	  9196	code main
    1	   140	 14420	   gpu-process
    0	    44	 14500	   utility-network-service
    0	   204	 15556	extensionHost [1]
    0	    84	  3124	     electron-nodejs (serverMain.js )
    0	   100	 16620	window [2] (Issue Reporter)
    0	   212	 16708	window [1] (Welcome - Visual Studio Code)
    0	   121	 16996	shared-process
    0	    29	 17244	   crashpad-handler
    0	    90	 17384	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.10.4
path-intellisense|chr|2.9.0
vscode-terminal-for-ubuntu|Doc|0.0.2
auto-rename-tag|for|0.1.10
vscode-github-actions|git|0.26.3
search-node-modules|jas|1.3.0
node-module-intellisense|lei|1.5.0
git-graph|mhu|1.30.0
emoji-icons|mig|1.6.1
vscode-exec-node|mir|0.5.6
vscode-for-node-js-development-pack|nod|2.0.1
prettier-standard-vscode|num|1.0.2
postman-for-vscode|Pos|1.1.0
seti-icons|qin|0.1.3
LiveServer|rit|5.7.9
node-js-express-snippets|sur|2.0.0
delete-node-modules|Wsc|1.0.6
php-debug|xde|1.35.0
php-intellisense|zob|1.3.3
js-runner|Zol|3.2.0
node-modules|zyr|1.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31094925
pythonrstrctxtcf:31093870

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal
