### ISSUE TITLE
Keyboard in VS Code files is frozen, it does not let me type anything 

### ISSUE THREAD

**Issue by Mr-Gerasimenko** [microsoft/vscode#222188]
Type: <b>Performance Issue</b>

The issue of a frozen keyboard happened two days ago while writing a code in Python file, it unexpectedly froze and did not let me edit anything in the code - neither add nor delete. I thoroughly checked all the related settings and have not foung any bugs or issues. Furthermore, I diagnosed my MacOs and it turns out that it works perfectly well, implying that it is not a problem with general hardware. Also, restarted all the extensions. The very problem is about editing a code, the rest of interface of VS Code works how it should.

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (0.66GB free)|
|Process Argv|--crash-reporter-id 647229fe-bcce-4297-b0e2-7dd93c9effd3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    8	   197	  1344	code main
    0	    82	  1347	   gpu-process
    0	    49	  1348	   utility-network-service
    1	   393	  1349	window [1] (Selection Sort.py — Coding)
    0	   147	  1354	shared-process
    0	     0	  1530	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	  1355	fileWatcher [1]
    0	   360	  1356	extensionHost [1]
    0	     0	  1371	     /Users/George_426/.vscode/extensions/ms-python.python-2024.10.0-darwin-arm64/python-env-tools/bin/pet server
    0	   426	  1472	     electron-nodejs (bundle.js )
    0	    98	  1474	     electron-nodejs (server.js )
    0	    66	  1357	ptyHost
    0	     0	  1421	     /bin/zsh -i
    0	     0	  1502	     /bin/zsh -il
    0	    98	  1524	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Selection Sort.py — Coding)
|    Folder (Coding): more than 20716 files
|      File types: py(6788) pyc(6773) pyi(2107) so(198) mat(109) txt(98)
|                  afm(60) DS_Store(53) h(51) typed(49)
|      Conf files: launch.json(1) tasks.json(1);
```

</details>
<details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
vim-cheatsheet|And|0.0.1
vscode-django|bat|1.15.0
macos-modern-theme|dav|2.3.19
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
gitlens|eam|15.2.0
prettier-vscode|esb|10.4.0
code-runner|for|0.12.2
copilot|Git|1.214.0
copilot-chat|Git|0.17.1
go|gol|0.42.0
go-nightly|gol|2024.7.1618
simple-vim|jpo|0.0.5
vsc-python-indent|Kev|1.18.0
python-path|mge|0.0.14
vim-emulator|Mix|0.0.2
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.18.43
cpptools|ms-|1.21.1
cpptools-extension-pack|ms-|1.3.0
autodocstring|njp|0.6.1
vetur|oct|0.37.3
vim-like-cursor-navigator|Ran|0.1.0
java|red|1.32.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-vlang|vla|0.1.14
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.23.7
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0
vim|vsc|1.27.3
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
viml|Xad|2.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31094925
ccplti:31098112
pythonrstrctxtcf:31093870

```

</details>

**Comment by roblourens** [comment]
Can you give more details about the freeze? You just can't type in the file? Can you type in other non-python files? Does this happen regularly?
