### ISSUE TITLE
Unable to open '175929186'

### ISSUE THREAD

**Issue by rollymaeagustin** [microsoft/vscode#222140]
I left the codespace last ight and when I re-open, it says "disconnected from codespace and unable to connect to the server".

Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by joyceerhl** [comment]
Likely due to https://status.dev.azure.com/_event/524064579. Please let us know if you're still unable to reconnect.
