### ISSUE TITLE
TypeError: Failed to execute 'createPolicy' on 'TrustedTypePolicyFactory': Policy with name "defaultWorkerFactory" already exists.

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#222193]
I see this error a lot in the VS Code insider dev tools:

![Image](https://github.com/user-attachments/assets/0e0b2b09-5aec-4d44-8f6a-a705780cd998)

![Image](https://github.com/user-attachments/assets/c5048019-b01e-424c-8a7c-20cc0e56cc90)

**Comment by deepak1556** [comment]
Bisect points to the following,

```
demohan@Deepaks-MacBook-Pro vscode % git bisect good
f6f90e016301f288ac5b36936d15ff8af9d70923 is the first bad commit
commit f6f90e016301f288ac5b36936d15ff8af9d70923
Author: Benjamin Pasero <benjamin.pasero@microsoft.com>
Date:   Fri Jun 28 11:55:48 2024 +0200

    Implement NLS without AMD loader (#214588)
```

https://github.com/microsoft/vscode/blob/b97d0a2cb5733af8e2c1fa71699c7d477fd30695/src/vs/base/browser/defaultWorkerFactory.ts#L77 which was only effective with cross-origin scripts previously now is used in all scenarios to bootstrap NLS configs, some worker scripts like the renderer auto profiler end up loading the `defaultWorkerFactory` inside the worker which leads to double creation of the same name policy. Fun fact the duplicate policy creation is not raised when performing the same actions in a nested worker, possibly a bug in Chrome. Simple repro, https://gist.github.com/deepak1556/3e9d238c0d70c07dd23595df09152f25

**Comment by hediet** [comment]
Thanks for fixing!
