### ISSUE TITLE
grunt watch not worked on my lunux system where it worked with other editors. 

### ISSUE THREAD

**Issue by rhushi-lokhande** [Microsoft/vscode#22218]
I am working on the angular2 application. I was facing issue with the grunt watch function. whenever I edit any file and save my watch function is not trigged. My whole team facing save issue.

**Comment by ramya-rao-a** [comment]
cc @dbaeumer

**Comment by Tyriar** [comment]
@rhushi-lokhande How are you triggering `grunt watch`?
