### ISSUE TITLE
Chords not working when terminal has focus

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#22211]
OS X, insiders, zsh shell

1. Open terminal, focus the input
2. Try to execute some keybinding that has a chord (e.g. zen mod `cmd + k z`) - it is not working, notice that the terminal is ignoring the switch to chord mode

The issues seems to be that most terminal clear the terminal with cmd + k or ctrl + k. At least I tried zsh on osx and powershell on win10 and they both have that behavior

**Comment by Tyriar** [comment]
Good point, chords won't work in the terminal unless configured to do so. This is as designed since cmd+k is used to clear the terminal which is a common keybinding on macs, on other platforms it's eaten by the terminal since we can't assume the terminal won't handle it.

Do we really need a default keybinding for this?

**Comment by isidorn** [comment]
We do not really need a default keybinding, but I can still add some chord which will work in all other panels except the terminal.
Though if we have the icon I could live without the keybinding

**Comment by Tyriar** [comment]
I think no keybinding is the way to go, power users who would want a keybinding should by able to figure out how to add one.

No one has mentioned anything about the fac that chords don't work in the terminal after I added the cmd+k to clear shortcut several months. If the user really wants to use chords then it's possible by unbinding cmd+k from clear.

**Comment by isidorn** [comment]
@Tyriar agree that no shortcut is the way to go.
On the other hand I still think you should not bind `cmd+k` to clear, as we are introducing new actions all the time and we have already run out of keybindings, thus we will introduce more and more chords. None of this will be possible to execute frmo the terminal. We should fix this imho.

So currently you can not go in and out of zen mode while the terminal has focus for instance.

**Comment by Tyriar** [comment]
@isidorn unfortunately it's not as simple as we just support chrods within the terminal, when we did do this there were quite a few requests from Mac users who had cmd+k muscle memory as it's a platform standard within Terminal.app and iTerm2. Additionally ctrl+k is a shortcut in bash that removes everything to the right of the cursor which is essentially for some users.

I made a design decision to align with the terminal standards when the terminal is focused and allow configuration via `terminal.integrated.commandsToSkipShell`. So far I think this is the only issue opened about lack of chord support within the terminal but previously there were a number of issues/votes on the lack of cmd+k (https://github.com/Microsoft/vscode/issues/12585, https://github.com/Microsoft/vscode/issues/7240, https://github.com/Microsoft/vscode/issues/11242, https://github.com/Microsoft/vscode/issues/12585) to clear and ctrl+k to delete in bash (https://github.com/Microsoft/vscode/issues/19248, https://github.com/Microsoft/vscode/issues/19228)

**Comment by isidorn** [comment]
@Tyriar if that's what the users want then it makes sense I guess. Thanks for the explanation.
