### ISSUE TITLE
'crashed', code: '5'  (Every 10 minutes)

### ISSUE THREAD

**Issue by hugonascimento** [microsoft/vscode#222113]
Type: <b>Bug</b>

Every 10 minutes the application crashes with a window with this error:
The window terminated unexpectedly (reason: 'crashed', code: '5')
With option to reshare the project or leave

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin x64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|64.00GB (39.46GB free)|
|Process Argv|--crash-reporter-id cc65b054-59f9-49a2-9125-dd6685978254|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bito|Bit|1.3.6
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.0
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
vscode-import-cost|wix|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31094925

```

</details>

**Comment by deepak1556** [comment]
Please share the crash dumps following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

**Comment by hugonascimento** [comment]
> Please share the crash dumps following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report
[b0c3bf6d-0dd1-4185-9025-3dc95ddf6bf9.dmp.zip](https://github.com/user-attachments/files/16415424/b0c3bf6d-0dd1-4185-9025-3dc95ddf6bf9.dmp.zip)
Thank you for your support.
