### ISSUE TITLE
Snippet's prefix can't be superset of another prefix

### ISSUE THREAD

**Issue by vsobotka** [Microsoft/vscode#22216]
- VSCode Version: 1.10.1 (653f8733)
- OS Version: Windows 10 Pro (10.0.14393)

Steps to Reproduce:

1. Have following user snippets defined
```
{
    "lc": {
        "prefix": "lc",
        "description": "external character",
        "body": [
            "define variable lc${<name>} as character no-undo."
        ]
    },
    "ilc": {
        "prefix": "ilc",
        "description": "define input parameter character",
        "body": [
            "define input parameter ilc${<name>} as character no-undo."
        ]
    }
}
```
2. Have following user settings
```
{
    "editor.tabCompletion": true,
    "editor.quickSuggestions": false,
    "editor.snippetSuggestions": "top"
}
```
3. Try both snippets
- `lc` triggers `lc` snippet
- `ilc` does not work (`tab` does not trigger snippet)
- `xlc` triggers `lc` snippet
4. Delete `lc` snippet
- `ilc` triggers `ilc` snippet

Which is both logical and strange. It is logical, kind of, because in `ilc` it presumably matches both `lc` and `ilc`. It does not show the `lc` in suggestions though. In suggestions it shows only `ilc` and yet it does not expand it on `tab`.

When I, in step 3, use `xlc` and press `Ctrl + Space` to show suggestions, I do not see any. But if I press `Tab`, the `xlc` will expand to `xdefine variable lc${<name>} as character no-undo.` (take notice of the `x` at the beginning). It is strange, because it does not suggest anything, yet it expands.

In all those cases though, it is possible to expand the snippet manually through suggestions window (if populated).

Is this the right behaviour? Is it possible for me to have fully functional both `lc` and `ilc`? I have a lot of snippets from UltiSnips where one prefix is superset of another.

**Comment by jrieken** [comment]
Yeah... Tab-completion cannot handle the case in which more than one snippet matches. We should then bring up the suggest widget but today silently fail...

**Comment by vsobotka** [comment]
@jrieken Thanks. If more than one snippet matches, why it shows only one in the suggestion window then?

**Comment by jrieken** [comment]
hm, yeah that would be an OK intermediate solution. We could pick the snippet with the longest overlap

**Comment by vsobotka** [comment]
@jrieken Is this a good opportunity for new contributor? Would you accept PR on this issue?

**Comment by jrieken** [comment]
Yeah, the stepping stone you proposed in https://github.com/Microsoft/vscode/issues/22216#issuecomment-285301318 would be a very good getting-started case

**Comment by vsobotka** [comment]
Awesome. I will get to it then. Thank you :)

**Comment by jrieken** [comment]
code pointer: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/snippets/electron-browser/tabCompletion.ts#L69
