### ISSUE TITLE
shift+cmd+t not working

### ISSUE THREAD

**Issue by mweidner037** [microsoft/vscode#222100]
Type: <b>Bug</b>

According to the command palette, shift+cmd+t is the shortcut for "View - Reopen closed editor". However, that shortcut does not work for me (it does nothing). Accessing the command via the command palette works as expected.

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 0a02ccbf-b1b2-45c7-8e4a-95cb8c4a8ca5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-prettier-glimmer|Ada|1.0.3
Handlebars|and|0.4.1
vscode-mjml|att|1.6.0
folder-source-actions|bie|0.2.1
vscode-tailwindcss|bra|0.12.5
vscode-coloured-status-bar-problems|bra|0.2.0
vscode-glimmer|chi|0.0.6
npm-intellisense|chr|1.4.5
codestream|Cod|15.11.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.0
prettier-vscode|esb|10.4.0
file-icons|fil|1.1.0
vscode-pull-request-github|Git|0.92.0
todo-tree|Gru|0.0.226
headwind|hey|1.7.0
customize-ui|ioc|0.1.65
monkey-patch|ioc|0.1.23
elixir-ls|Jak|0.22.1
vscode-peacock|joh|4.2.2
ember-related-files|jos|1.5.0
vscode-ember-unstable|lif|3.0.55
vscode-glimmer-syntax|lif|1.0.35
vscode-rufo|mbe|0.2.1
handlebars-formatter|mfe|1.1.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.29.1
atom-keybindings|ms-|3.3.0
vsliveshare|ms-|1.0.5936
status-bar-param|msc|1.6.0
color-highlight|nau|2.8.0
postcss|ric|2.0.0
vscode-sort-json|ric|1.20.0
elixir-formatter|sar|1.3.0
vscode-fileutils|sle|3.10.3
file-hopper|suc|0.3.5
glint-vscode|typ|1.3.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-icons|vsc|12.8.0
codetour|vsl|0.0.59
material-theme|zhu|3.17.2

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31094926
pythonrstrctxtcf:31093870
hdi1a554:31097393

```

</details>

**Comment by connor4312** [comment]
Please collect some more info for us: https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by mweidner037** [comment]
Thanks, it turned out to be an issue with the Headwind extension: https://github.com/heybourn/headwind/issues/98
I've disabled it and now Cmd+Shift+T works as expected.

(The issue was fixed in Headwind's source repo, but the fix was never released to the marketplace.)
