### ISSUE TITLE
Global search failure

### ISSUE THREAD

**Issue by chenqingyu000** [microsoft/vscode#222147]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91.1
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:
1. Open the search 
2. If you search for file.html and search for content @m, the content cannot be searched. Only when you search for specific @mousewheel, the content found will be displayed

**Comment by andreamah** [comment]
Can you provide a screen recording of the problem?
