### ISSUE TITLE
vscode unable to start, keeps saying unexpected error. 

### ISSUE THREAD

**Issue by Reconnoiter** [microsoft/vscode#222137]
ADD ISSUE DESCRIPTION HERE:

I am getting this message every time I try to log into vscode:

"An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: exception was thrown by handler. exception: failed to start vs code remote server.)'

I have reset my computer, tried from multiple devices and wifis, attempted cs50.dev.restart and the issue persists.

Any help is greatly appreciated. 

Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by Reconnoiter** [comment]
It appears fixed. Perhaps it was due to the crowdstrike problems.

**Comment by roblourens** [comment]
Thanks for the followup
