### ISSUE TITLE
underscores hidden in terminal command prompt

### ISSUE THREAD

**Issue by cookhe** [microsoft/vscode#222108]
Type: <b>Bug</b>

I run VS Code on Ubuntu 22.04.4 LTS.

Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:08:12.169Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 5.14.0-1059-oem

My layout puts the terminal on the bottom of the window.

When the terminal prompt is at the bottom of the panel, underscores that I type are hidden and appear as spaces.

For example, when I list the contents of a directory and then want to change into a directory named `plot_dir`, the prompt appears as
`$ cd plot dir `
when I have in fact typed an underscore between `t` and `d`. The command executes successfully.

This behavior leads me to think the underscore is correctly recognized when typed but is not rendering properly. At my current resolution, the tail of the `p` extends three pixels below the loop. The underscore seems to be on a line four pixels below that of the `p`'s loop (and the bottom of other characters).

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:08:12.169Z)
OS version: Linux x64 5.14.0-1059-oem
Modes:
Remote OS version: Linux x64 5.14.0-362.24.1.el9_3.0.1.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 3717)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|31.07GB (19.85GB free)|
|Process Argv|--crash-reporter-id 6769aaf4-46b7-475e-a5ff-0af4a73b725d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: stampede3.tacc.utexas.edu|
|OS|Linux x64 5.14.0-362.24.1.el9_3.0.1.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8468 (96 x 2584)|
|Memory (System)|250.90GB (236.48GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
python-snippets|cst|0.1.2
better-cpp-syntax|jef|1.27.1
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.375.1
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.4.3
pdf|tom|1.2.2
linter-gfortran|for|3.2.0
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
cmake-tools|ms-|1.18.43
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.9.10
cmake|twx|0.0.17

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31094925
pythonrstrctxt:31093869

```

</details>

**Comment by cookhe** [comment]
Here is a screenshot demonstrating the behavior.

![image](https://github.com/user-attachments/assets/22a2fade-3f0e-4208-8b5e-dd7e90adaa6e)

**Comment by meganrogge** [comment]
/duplicate [#211933](https://github.com/microsoft/vscode/issues/211933)
