### ISSUE TITLE
Feature Request: $-Prefix selection on double click

### ISSUE THREAD

**Issue by Espigah** [Microsoft/vscode#22213]
Angular use $ for everything =/

- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|vscode-file-peek|abierbaum|1.0.1|
|html-snippets|abusaidm|0.1.0|
|vscode-caniuse|akamud|0.5.3|
|workbench|andrew-lis|0.1.3|
|Gradle|cazzar09|1.1.2|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|jsrefactor|cmstead|0.7.2|
|angular2-snippets|danwahlin|1.0.12|
|jshint|dbaeumer|0.10.15|
|vscode-stylesheet-formatter|dbalage|0.2.0|
|python|donjayamanne|0.5.9|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|vscode-npm-script|eg2|0.1.8|
|code-runner|formulahendry|0.6.13|
|sass-lint|glen-84|0.0.3|
|beautify|HookyQR|0.8.9|
|docthis|joelday|0.4.3|
|Angular1|johnpapa|0.1.16|
|vscode-codemetrics|kisstkondoros|1.2.0|
|refactorix|krizzdewizz|0.3.2|
|code-beautifier|michelemelluso|1.6.2|
|vscode-todo-parser|minhthai|1.8.7|
|HTMLHint|mkaufman|0.3.3|
|prettify-json|mohsen1|0.0.3|
|vscode-scss|mrmlnc|0.6.2|
|debugger-for-chrome|msjsdiag|2.6.0|
|cursor-tools|naumovs|1.0.0|
|peep|nwallace|0.0.5|
|indent-rainbow|oderwat|0.4.1|
|js-complexity-analysis|TomiTurtiainen|1.0.4|
|cordova-tools|vsmobile|1.2.6|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JasmineSnippets|xabikos|0.2.1|
|html-css-class-completion|Zignd|1.0.3|;

**Comment by ramya-rao-a** [comment]
Use the setting `editor.wordSeparators`. Copy the default value and remove "$" from it.
