### ISSUE TITLE
always open file in the same editor window

### ISSUE THREAD

**Issue by hzieept** [Microsoft/vscode#22219]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|tortoise-svn|fantasytyx|0.1.1|
|vue-snippets|hollowtree|0.1.0|
|weex|jaylinwang|0.4.0|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|debugger-for-chrome|msjsdiag|2.5.3|
|vetur|octref|0.4.1|
|vscode-icons|robertohuertasm|7.2.0|
|markdown-pdf|yzane|0.1.6|
|Material-theme|zhuangtongfa|1.0.3|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
Can you provide details on how you are opening the file? From terminal? From context menu in File explorer? From the menu in VS Code?

**Comment by bpasero** [comment]
`"workbench.editor.enablePreview": false`
