### ISSUE TITLE
Error code 174979597

### ISSUE THREAD

**Issue by 1Moonman** [microsoft/vscode#222136]
Hey! 
I was watching the 1st course and during the "Meow" section I pressed the wrong key because it kept write meow over and over and wouldn't stop. Making it impossible to stop it, clear, etc. I refreshed the page, but it went straight to meow and repeating 'meow.' Closed the tap and now when I go to the cs50.dev site and this is what pops up. 

"Unable to open '174979597'
Unable to resolve resource vscode-remote://codespaces%2Bfriendly-space-yodel-v6gww55x6pxpcx7xj/workspaces/174979597"

Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by lszomoru** [comment]
Please reach out to your course support personnel.
