### ISSUE TITLE
【vscode.dev】there is no prompt for any ts errors in ts file

### ISSUE THREAD

**Issue by darrenweb** [microsoft/vscode#222150]
1,In the latest version of Chrome open https://vscode.dev/github/microsoft/vscode-vsce

2,Open the ts file and write some wrong ts code.
 But there is no prompt for any ts errors.
i  also set typescript validation to enable.
See the screenshot.

![3O8NY}(I6(X7_`@LV0QQNXM](https://github.com/user-attachments/assets/040a5a6b-4592-4ad7-8b23-69ca7214f717)

![J5(X0C9~E8$QT)CL86O7 4](https://github.com/user-attachments/assets/fa579fa3-ad99-46ec-bac9-3199dd5b3ad7)

**Comment by mjbvz** [comment]
Try setting `"typescript.tsserver.web.projectWideIntellisense.suppressSemanticErrors": false`
