### ISSUE TITLE
Can't search in symlinked folders

### ISSUE THREAD

**Issue by lamplightdev** [Microsoft/vscode#22210]
- VSCode Version: 1.10.1
- OS Version: macOS Sierra 10.12.3 (16D32)

Steps to Reproduce:

1. Create a directory structure a/b/c/
2. Create a file in c/ with content 'testme'
3. Create a symlink d in a/ pointing to c/ (ln -s b/c/ d)
4. Open a/ in VSCode
5. Search a/ for 'testme' - one result returned as expected
5. Search a/d/ for 'testme' - no results returned

**Comment by roblourens** [comment]
What are you doing when you search a/d/? Do you open a/d/ in vscode, or use the search filters to narrow it to that folder?

**Comment by lamplightdev** [comment]
I open a/ in vscode, and right click the folder (d) and click 'Find in Folder'

**Comment by roblourens** [comment]
When you search a/ and it finds a result, does it report its path as the actual path, or the symlink path (with a/d/)?

**Comment by lamplightdev** [comment]
It doesn't find anything in the symlinked folder, so neither :)

**Comment by lamplightdev** [comment]
This seems to be fixed in the latest release (1.11)
