### ISSUE TITLE
JS/TS Crash

### ISSUE THREAD

**Issue by sanyam-aggarwal-shipsy** [microsoft/vscode#222166]
Type: <b>Bug</b>

VS code prompted up to report this error

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.5.0
Modes:
Remote OS version: Linux x64 5.4.0-29-generic
Remote OS version: Linux x64 5.4.0-29-generic
Connection to 'ssh-remote+test' could not be established
Connection to 'ssh-remote+test' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id a0964a2b-bf9d-4dcf-bc84-405643fbe79d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: test|
|OS|Linux x64 5.4.0-29-generic|
|CPUs|AMD EPYC 7542 32-Core Processor (24 x 0)|
|Memory (System)|172.75GB (74.37GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: test|
|OS|Linux x64 5.4.0-29-generic|
|CPUs|AMD EPYC 7542 32-Core Processor (24 x 0)|
|Memory (System)|172.75GB (74.37GB free)|
|VM|0%|

Connection to 'ssh-remote+test' could not be established

Connection to 'ssh-remote+test' could not be established
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.375.1
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vscode-postgres|cko|1.4.3
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.0
copilot|Git|1.214.0
copilot-chat|Git|0.17.1
vscode-pull-request-github|Git|0.92.0
mongodb-vscode|mon|1.6.1
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
postman-for-vscode|Pos|1.1.0
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31094926
refactorc:31098050
ccplt:31098110

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled) (besides wsl)?
