### ISSUE TITLE
Can't run certain apps in terminal

### ISSUE THREAD

**Issue by Master811129** [microsoft/vscode#222247]
Does this issue occur when all extensions are disabled?: **Yes**

- Version: 1.91.1
- Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
- Date: 2024-07-09T22:08:12.169Z
- Electron: 29.4.0
- ElectronBuildId: 9728852
- Chromium: 122.0.6261.156
- Node.js: 20.9.0
- V8: 12.2.281.27-electron.0
- OS: Linux x64 6.8.0-38-generic snap

Installed the app as a classic Snap. It looks like that some apps can't be run from VSCode's terminal. CPU goes 100% and ram gets filled up and crashes the system:

NO extensions BTW

#### Steps to Reproduce:
1. open a terminal in code (snap)
2. run `dolphin` as an example and CPU goes 100%

#### Screencast: ignore the flashing

Ignore the flashing

https://github.com/user-attachments/assets/d9429512-9256-44bf-96fe-d9e72c4861a8

**Comment by meganrogge** [comment]
does this happen if you run that in an external terminal?

**Comment by Master811129** [comment]
No, It only happens in vscode terminal. I believe this occurs due to snap sandbox blocking something.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/179086

The library variables we set like GTK_PATH, GIO_MODULE_DIR interfere with launching external applications.

**Comment by Master811129** [comment]
> The library variables we set like GTK_PATH, GIO_MODULE_DIR interfere with launching external applications.

The app I ran here was `dolphin` which is a Qt app not GTK. Are you sure that this is related to my problem?
I dont have many GTK apps installed on my system but `gnome-disks` and `lutris` work fine from VSCode(snap) terminal.

Tried with more qt apps some of them just won't do anything, Halt the termianl and use 100% CPU and some of them will open up without issues. Note that all of them work fine on my normal Konsole its just vscode's terminal.
- `dolphin`❌
- `kdialog --msgbox "Hello world"`✅
- `kdialog --getsavefilename`❌
- `kmines`✅
- `kate`❌
- `systemsettings`❌
- `qbittorrent`✅
- `ark` opens but clicking on "Open Archive..." which opens a file dialog hangs the app

**Comment by AmeyaVS** [comment]
I suggest dumping the environment variables in your default terminal into a file.
Then dump the environment variables in the VSCode terminal to another file.
Compare the 2 files, and observe if any new environment variable related to Qt/Gtk by either unsettling them in the VSCode terminal to see if any fixes the issue.
