### ISSUE TITLE
Open file from diff defunct

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#22225]
* make changes
* look at changes in diff 
* commit changes, diff stays open
* select 'Open File'
* 🐛 nothing happens...

**Comment by joaomoreno** [comment]
AHAH cc @isidorn 

Fixed by 9774590996be39972f6973eb8d413e7c5e95e855

**Comment by isidorn** [comment]
@joaomoreno I told you everybody would hit this 🤓

**Comment by jrieken** [comment]
Reopening this because when the diff editor is open in slot 2 or 3 the original file open in slot 1 which is not what I want. @joaomoreno You don't wanna use the `open`-command but the actual API for this

**Comment by joaomoreno** [comment]
Closing, since the original issue is fixed. Moved @jrieken's suggestion to #23667
