### ISSUE TITLE
Support opening file from console with some prefix

### ISSUE THREAD

**Issue by NN---** [microsoft/vscode#222264]
While building the errors might have an additional prefix such as process number or anything else, in such case VSCode cannot open a file with Ctrl+Click:

Ctrl+Click opens the file
```
c:\test\file.txt
```

Ctrl+Click does not open the file
```
1>c:\test\file.txt
```

**Comment by Tyriar** [comment]
@NN--- what tool outputs this format?

**Comment by NN---** [comment]
MSVC.
When there is an error the output is the following:

`1>c:\dir\file.cpp(123,1): error C2143: syntax error: missing ';' before '}'`

**Comment by Tyriar** [comment]
Thanks, I think we should support this then :+1:

**Comment by wdhongtw** [comment]
Hi @NN--- 

In my manual experiment, the prefix before `c:\` does not have impact on the link detect logic.
As long as the file do exists, the link should be clickable and opened to the correct file.
(I simulate the output pattern from cmake + msvc error output and add `1>` prefix manually)

Would you like to elaborate more about how to reproduce this issue?
e.g. viewing MSVC build log from macOS, using vscode web version ...

**Comment by Tyriar** [comment]
@wdhongtw you're right, we should already support this 🤔 

![image](https://github.com/user-attachments/assets/72030752-d0cf-456c-b62b-8ad08c4ef99f)
