### ISSUE TITLE
TypeScript: Quick fix all

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#22220]
With TS, I see there is now the option to apply a quick fix e.g. for unused imports:

![image](https://cloud.githubusercontent.com/assets/921609/23706289/7b76e4aa-0405-11e7-88a4-bd24b210cd0e.png)

However this is no option to apply all quick fixes. This might be useful, for example, for removing all unused imports from a file.

**Comment by mjbvz** [comment]
Thanks. This is something that we have discussed and I believe it is a good idea.

This will require a change on the TypeScript side to implement properly, so I've opened https://github.com/Microsoft/TypeScript/issues/14549 to discussion how we may go about implementing this.

Closing this issue as upstream
