### ISSUE TITLE
When entering Chinese, the cursor does not follow(BaiDuPinYin)

### ISSUE THREAD

**Issue by mko684** [Microsoft/vscode#22221]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-npm-script|eg2|0.1.7|
|Angular2|johnpapa|1.0.2|
|sublime-keybindings|ms-vscode|1.8.2|;

---

Steps to Reproduce:

1.
2.

**Comment by rebornix** [comment]
@mko684 can you provide Gif or so to help troubleshoot? I can't reproduce with latest VS Code.
