### ISSUE TITLE
Create Dark Modern theme with Github Dark Default background colors

### ISSUE THREAD

**Issue by BerndHme** [microsoft/vscode#222272]
Type: <b>Feature Request</b>

Can someone create a new theme, based on the existing default Dark Modern,
but with all the background colors (dark black blueish) of the Github Dark default theme?

**Comment by MrSuddenJoy** [comment]
@BerndHme this is perfect example of easy DIY type of thing. Its extremely easy to create theme.

**Comment by BerndHme** [comment]
I know, i've tried these

```
    "workbench.colorCustomizations": {
        "[Default Dark Modern]": {
            "editor.background": "#0d1117",
            "sideBar.background": "#010409",
            "activityBar.background": "#0d1117",
            "statusBar.background": "#0d1117",
            "titleBar.activeBackground": "#0d1117",
            "titleBar.inactiveBackground": "#010409"
        },
    }
```

But if you type `background` to get all props
... you get about 25000 entries

So I assume "the pro builders" have somekind of generator from which you can easily mix these themes.

**Comment by BerndHme** [comment]
Ok apparently you can just copy-paste everyting from the color:{} from the local extension file,

`C:\Users\UserName\.vscode\extensions\github.github-vscode-theme-6.3.4\themes`

and paste it in `workbench.colorCustomizations`.
