### ISSUE TITLE
Losing window input focus closes Go-to-File result 

### ISSUE THREAD

**Issue by bad32** [Microsoft/vscode#22222]
- VSCode Version: 1.10.1 (653f873)
- OS Version: Window 7 SP1 64-bit

Steps to Reproduce:

1. Open folder with several files
2. Go to file (`ctrl`+`p`) 
3. Type a few letters 
4. Click on a different window (or `alt`+`tab`)

This will stop the operation mid-search in a large project.

![issue](https://cloud.githubusercontent.com/assets/24456233/23706651/bc67bb30-0417-11e7-8f3a-ae437f9dbfcf.gif)

**Comment by bpasero** [comment]
`"workbench.quickOpen.closeOnFocusLost": false`
