### ISSUE TITLE
Add hover help for the 'trace' launch config attribute

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#22228]
Since the 'trace' attribute is now documented [here](https://code.visualstudio.com/docs/editor/node-debugging#_launch-configuration-attributes), we should add proper hover help too.

**Comment by weinand** [comment]
@roblourens I've added this description:

![2017-03-08_16-14-00](https://cloud.githubusercontent.com/assets/1898161/23709593/44dce24a-041a-11e7-865d-61926d9918c5.png)

**Comment by roblourens** [comment]
In node2 it has different semantics, it can be 'true' or 'verbose', where 'true' only writes to a file. This is because I've given up on making this output readable to anyone else, and I have another tool for sourcemap path debugging, the `.scripts` command. Maybe we should just add 'true' as a valid value so it doesn't get underlined?

**Comment by weinand** [comment]
Is 'true' of type string or a boolean?

For me the type of 'trace' is string and I did not bother to create a schema for the individual values (because they can be combined in any way). The value is not validated and will not result in errors.
So a 'true' (as a string is not problem).

However, if we agree on a string type, I suggest that we use something more self-explanatory like 'on', 'off', instead of 'true' and 'false'.
And I could replace my 'all' by 'verbose'.

**Comment by roblourens** [comment]
`true` is a boolean here. What I expect people to do most of the time is to use `"trace": true` and upload the log file to github, and I thought a boolean would be simpler for that case than some other string. "verbose" is useful to me but probably not many other people.

**Comment by weinand** [comment]
I've changed the schema to support `"boolean" | "string"`.
And the description is now:
![2017-03-14_15-06-27](https://cloud.githubusercontent.com/assets/1898161/23904377/f171e3e6-08c7-11e7-8413-90c8bebd1dfa.png)

**Comment by onethread** [comment]
I get a "Property trace is not allowed" hover text now. Has `trace` been eliminated as a property?

**Comment by weinand** [comment]
@onethread no, `trace` hasn't been eliminated.
I assume you are using VS Code stable (1.10.2), correct? `trace` was not an official attribute in VS Code version < 1.11. 
In 1.11 it will become an official attribute. You can try it already in the Insiders build.

**Comment by onethread** [comment]
@weinand Ah that makes more sense now. It is listed in [the official docs](https://code.visualstudio.com/docs/nodejs/nodejs-debugging), though. Thanks for clearing that up.
