### ISSUE TITLE
Incorrect preview pointer when the inlay hints label location was not in the same file

### ISSUE THREAD

**Issue by jetjinser** [microsoft/vscode#222297]
Installed extension:
- `justusadam.language-haskell`
- `haskell.haskell`

In the file "CodeLens.hs", goto the definition by ctrl click inlay hints label `eval_cfg_diff`, which location `uri` is "Config.hs", but the preview pointer (idk its name) points to location `range`, but still in "CodeLens.hs".

![image](https://github.com/user-attachments/assets/9cfdc323-3b37-4843-ac3d-1fd9f4be478a)

```json
{
    "label": [
        {
            "location": {
                "range": {
                    "end": {
                        "character": 17,
                        "line": 14
                    },
                    "start": {
                        "character": 4,
                        "line": 14
                    }
                },
                "uri": "file:///home/jinser/vie/projet/HLS/haskell-language-server/plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Config.hs"
            },
            "value": "eval_cfg_diff"
        },
        {
            "value": ", "
        },
        {
            "location": {
                "range": {
                    "end": {
                        "character": 22,
                        "line": 15
                    },
                    "start": {
                        "character": 4,
                        "line": 15
                    }
                },
                "uri": "file:///home/jinser/vie/projet/HLS/haskell-language-server/plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Config.hs"
            },
            "value": "eval_cfg_exception"
        }
    ],
    "paddingLeft": true,
    "position": {
        "character": 31,
        "line": 309
    },
    "textEdits": [
        {
            "newText": "EvalConfig {eval_cfg_diff, eval_cfg_exception}",
            "range": {
                "end": {
                    "character": 32,
                    "line": 309
                },
                "start": {
                    "character": 18,
                    "line": 309
                }
            }
        }
    ],
    "tooltip": "Expand record wildcard"
}
```

FYI, I'm looking into the inlay hints feature of haskell-language-server and I'm not sure if the location `uri` has to be in the same file

- About:
```
Version: 1.92.0-insider
Commit: 89690b9d76a88fab676d26651134a1ffa4562732
Date: 2024-07-19T05:03:57.939Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.6.37
```

Steps to Reproduce:

> The HLS inlay hints are developing on my machine and I don't know how to actually reproduce it. But it may be an LSP problem, so I will give a rough description.

1. In A file, ctrl click the inlay hints label that location uri is B file.
2. check the preview.

**Comment by jrieken** [comment]
I am sorry, but I have trouble following this and reproducing this. Can you try to create minimal repro using just the VS Code API or use the built in TS extension (which supports navigatable inlay hints)

>(1) In A file, ctrl click the inlay hints label that location uri is B file. (2) check the preview.

Ctrl+click'ing an inlay should not open preview but jump straight to the location. Or did you ctrl+click the text next to the inlay hint?
