### ISSUE TITLE
Terminal suggest: Don't rewrite whole line when it's not needed

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#222233]
1. Most noticeable on mac
2. In vscode repo
3. Type ./script
4. Enter, 🐛 `./script` is deleted first, then `./scripts/` is typed

![Recording 2024-07-19 at 12 39 20](https://github.com/user-attachments/assets/de435eb0-1433-486e-bfcc-b39b8c53e3d4)

**Comment by aiday-mar** [comment]
Testing this on Mac and I see the following behavior on the latests Insiders. It seems to me that the terminal is cleared and the suggestion added

https://github.com/user-attachments/assets/7d2cc2e0-6877-4937-9ad3-c9c71593ad7d

**Comment by Tyriar** [comment]
@aiday-mar that's because you're completing build -> .build. It will rewrite it from the common prefix
