### ISSUE TITLE
Cannot drag views to secondary side bar when activity bar is hidden

### ISSUE THREAD

**Issue by laverdet** [microsoft/vscode#222283]
Type: <b>Bug</b>

When the activity bar is hidden (`"workbench.activityBar.location": "hidden"`) I cannot drag views to the secondary side bar.

This occurs in the current version 1.91.1 and 1.92.0-insider build. I am attaching a screen recording as well which clearly demonstrates the issue.

https://github.com/user-attachments/assets/764e14a8-735e-4eca-8c4c-baf58cb4d3f2

---

VS Code version: Code - Insiders 1.92.0-insider (Universal) (89690b9d76a88fab676d26651134a1ffa4562732, 2024-07-19T05:03:57.939Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 5, 7|
|Memory (System)|64.00GB (37.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
vscode-graphql|Gra|0.11.0
vscode-graphql-syntax|Gra|1.3.6
vscode-yaml|red|1.15.0
vscode-stylelint|sty|1.4.0
shellcheck|tim|0.37.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jg8ic977:31013176
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
impr_priority:31057980
nativerepl1:31093711
refactort:31084545
pythonrstrctxt:31093868
0c838689:31088353
hdi1a554:31091669
flightc:31100342

```

</details>

**Comment by pseudovector** [comment]
Having same issue with "workbench.activityBar.location": "default"

**Comment by abhijit-chikane** [comment]
Could you please reconsider [this](https://github.com/microsoft/vscode/issues/195561)?
