### ISSUE TITLE
Popup Menu Quickly Appears and Obstructs Text Selection in VSCode

### ISSUE THREAD

**Issue by halil-akgun** [microsoft/vscode#222261]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.91.1
- OS Version:  Microsoft Windows 10 Pro 10.0.19045 Build 19045

**Describe the bug**
When using the mouse in VSCode, a popup menu quickly appears, obstructing my ability to select and view text properly.

Steps to Reproduce:
1. Open a file in VSCode.
2. Attempt to select text using the mouse.
3. Observe that a popup menu quickly appears and obstructs the text selection.

screen recording:
https://drive.google.com/file/d/1OtVnbv1Iqp5b6fEVUqoW2uxqyqsO1Xal/view

Note: In the screen recording, I am attempting to select the text by double-clicking.

**Comment by darkenwarlock** [comment]
I am having the same issue with VSCode version 1.92.0 and Windows 11 Home 10.0.22631 Build 22631.

**Comment by connor4312** [comment]
Can you confirm what the setting `editor.hover.delay` is set to, if anything?

**Comment by halil-akgun** [comment]
> Can you confirm what the setting `editor.hover.delay` is set to, if anything?

![Image](https://github.com/user-attachments/assets/9dba14a1-0fc4-4186-a0e8-8b57e667ecd5)

I haven’t used VS Code for a while, but I just tested it again to see if the issue still occurs, and I couldn’t reproduce it. It seems that the problem has been resolved with recent updates. Thank you!

**Comment by connor4312** [comment]
Thanks for confirming! Let us know if you see it again.
