### ISSUE TITLE
Extension with onLanguage Activation Event gets not activated in workspace

### ISSUE THREAD

**Issue by Stonebubble** [microsoft/vscode#222225]
Type: <b>Bug</b>

valeryanm.vscode-phpsab is an example for that.

The extension starts and works when opening a folder in vscode but does not start when opening the same folder as a workspace. The runtime status says that it is not activated yet although a php file is open and vscode is set to process the file as php. The extension uses the onLanguage php activation Event. The command the extension is searchable with strg + shift + p but an error occours with the title "command 'name of the command' resulted in an error" that says "command 'comand id' not found". It works when opening the same folder not as an workspace.

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|19.88GB (4.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian0|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 0)|
|Memory (System)|9.66GB (7.46GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian0|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 0)|
|Memory (System)|9.66GB (7.46GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.6.6
vscode-intelephense-client|bme|1.10.4
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
vscode-html-css|ecm|2.0.10
live-sass|gle|6.1.2
html-tag-wrapper|hwe|0.2.3
string-highlight|jen|0.0.8
sftp|Nat|1.16.3
php-docblocker|nei|2.7.0
laravel-blade|one|1.36.1
run-on-save|puc|1.9.0
LiveServer|rit|5.7.9
vscode-blade-formatter|shu|0.24.2
vscode-scss-formatter|sib|3.0.0
vscode-phpsab|val|0.0.18
php-debug|xde|1.35.0
php-pack|xde|1.0.3
better-minify|yud|1.1.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
vscode-apache|mrm|1.2.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
php-docblocker|nei|2.7.0
laravel5-snippets|one|1.18.0
material-icon-theme|PKi|5.6.0

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Please share the list of activation events your extension uses

**Comment by Stonebubble** [comment]
The extension given as an example uses the mentioned onLanguage Activation event. In this case *.php files.
