### ISSUE TITLE
warning: powershell detected that you might be using a screen reader and has diabled psread line for compatibiltity purpose. if you want to re-enable it, run ' import -module psreadline'

### ISSUE THREAD

**Issue by shailendrasaini172006** [microsoft/vscode#222285]
### ### _*Type:**_**_ <b>Feature Request</b>

please give me this problem solution 

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by meganrogge** [comment]
Hi, that warning is coming from powershell, so there's nothing we can do about it. Are you in `screen reader optimized mode`?
