### ISSUE TITLE
Typo in Spanish Translate of Welcome Page

### ISSUE THREAD

**Issue by kmorope** [Microsoft/vscode#22226]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. In Welcome Page says "3Iniciar" but the number 3 is unnecessary

**Comment by chrmarti** [comment]
@johnliu2016 Is this something you can take care of? Since the fix seems obvious, we could apply the linked PR so it's corrected in the insiders builds before the next full update.

**Comment by niroyb** [comment]
PR is wrong, the file edited is auto generated somehow. I could not find the source for it.

**Comment by chrmarti** [comment]
@niroyb Thanks for reporting and providing the PR. The master copy of translations is indeed not in this repository. We might still use your PR to avoid having to wait for the next update of translations.

**Comment by johnliu2016** [comment]
@lukaschal, typo in following string
[vs_code_welcome_page.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fesn%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Fparts%2Fwelcome%2Fpage%2Felectron-browser%2Fvs_code_welcome_page.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";welcomePage.start" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Start]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[3Iniciar]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by cmgg** [comment]
The XPath to the header where the typo is 

`//*[@id="workbench.editor.walkThroughPart"]/div/div[1]/div/div/div[2]/div[1]/div[1]/h2`

**Comment by lukaschal** [comment]
Fixed.

File: src\vs\workbench\parts\welcome\page\electron-browser\vs_code_welcome_page.nls.resx
ID: ".resx", 0; "welcomePage.start"
SRC: Start
TGT: Iniciar
