### ISSUE TITLE
Test: debugging accessibility help dialogs & debug console accessible view

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#222238]
Refs https://github.com/microsoft/vscode/issues/213413, https://github.com/microsoft/vscode/issues/221971, https://github.com/microsoft/vscode/issues/213413, https://github.com/microsoft/vscode/issues/221512, https://github.com/microsoft/vscode/issues/221603

- [x] Windows @karthiknadig 
- [x] macOS @chrmarti 
- [x] anyOS @andreamah 

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23222238%0A%0A&assignees=meganrogge)

---

In order to improve the debugging experience for screen reader users, help dialogs have been added for the debug view and for the debug console. 

Enable a screen reader and verify that:
- You hear a hint about opening the accessibility help dialog when either view is focused
- You can disable that hint with the setting, `accessibility.verbosity.debug` and the setting description makes sense.
- You learn about the other view and how to focus it from within each dialog.
- Commands in the dialog are relevant and keybindings are rendered correctly or it's clear there is no keybinding assigned.

When using the debug console, screen reader users formerly had to hear the content read line by line. With the introduction of an accessible view (`alt+f2`), they can now navigate it char by char. 

Due to performance implications, we only render child elements one layer deep.

Verify that:
 - You can open the accessible view from the debug console and it contains the contents of the debug console
 - If you have an element focused (or its child - only up to one layer deep), the view opens to that element 
 - When you close the accessible view, the formerly focused element receives focus

In order to make the accessible view happen, we had to enable `debug.autoExpandLazyVariables` by default for screen reader users. This required the migration of the setting from a `boolean` to an `enum` of `auto | on |  off`. 

Verify that:
- The the setting descriptions are clear
- In screen reader mode, with the default value of `auto`, lazy variables are expanded - IE you don't see an 👁 button in the debug console row of the element
- Change the setting value and verify that it respects that
- Set the value to `true` or `false`, reload the window, and ensure that it gets migrated correctly

**Comment by chrmarti** [comment]
On the above "You learn about the other view and how to focus it from within each dialog.": Accessibility Help in the Debug Console mentions Accessibility View. I don't see any other cross-references, I assume that's fine, but let me know if I'm missing something.

**Comment by andreamah** [comment]
Tested- great to see accessibility in debug getting better. Good job!

**Comment by meganrogge** [comment]
> On the above "You learn about the other view and how to focus it from within each dialog.": Accessibility Help in the Debug Console mentions Accessibility View. I don't see any other cross-references, I assume that's fine, but let me know if I'm missing something.

What I meant by this was in the accessibility help dialog that appears when you've focused the debug console, you learn how to access the Run and Debug view, via this message: `The Show Run and Debug view command (Shift+Command+D) will open the Run and Debug view.`. When you are in the accessibility help dialog that appears when the run and debug view is focused, you see this message: `The debug console is a REPL (Read-Eval-Print-Loop) that allows you to evaluate expressions and run commands and can be focused with<keybinding:workbench.panel.repl.view.focus>.`

**Comment by karthiknadig** [comment]
Good job, I really liked the improvements.
