### ISSUE TITLE
window.zoom decimals numbers are not working as expected with zoom in/out

### ISSUE THREAD

**Issue by cozuya** [Microsoft/vscode#22227]
- VSCode Version: 1.10.1
- OS Version: MacOS Sierra

Steps to Reproduce:

Personally, coming from Sublime, the zoom in/out is too much of a jump.  In order to correct that I tried using decimals on the window.zoom setting.  While this does work, it then causes zoom in and out to behave strangely.  Specifically it looks like (in javascript terms) Math.round() is being called prior to zooming with the hotkeys.  In other words, a setting of 1.1 and hitting zoom up sets it to 2, while a setting of 1.6 zoomed up sets it to 3.  This doesn't seem right at all, and also, it doesn't always live update that screen immediately, sometimes you'll need to close the preferences window and reopen.  Let me know if you need more information.

**Comment by alexandrudima** [comment]
@cozuya Unless you are presenting to a live audience, I would not use `zoomLevel`. If you care about pixel perfection, please use `editor.fontSize`.

**Comment by bpasero** [comment]
Yes, `editor.fontSize` is the recommended thing to do.
