### ISSUE TITLE
Code Insiders: No installation of Visual Studio Code insider was found in Command-line

### ISSUE THREAD

**Issue by JergenRoss** [microsoft/vscode#222250]
Type: <b>Bug</b>

1. installing or add PATH environments for `code-insiders`
2. observe to type `code-insider is installed or not` in terminal as cmd, shell, etc.

Expected: type `code-insiders` will working
actual: Error and It says "No installation of Visual Studio Code insider was found"

VS Code version: Code - Insiders 1.92.0-insider (89690b9d76a88fab676d26651134a1ffa4562732, 2024-07-19T05:03:57.939Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU N4200 @ 1.10GHz (4 x 1094)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.83GB (0.93GB free)|
|Process Argv|--crash-reporter-id cbbe804e-79b2-4e58-a4de-8bac5e7557ee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
increment-selection|alb|0.2.0
chronicler|arc|0.1.16
multi-cursor-case-preserve|Car|1.0.5
vscode-office|cwe|3.3.9
jumpy2|Dav|1.7.0
prettier-vscode|esb|10.4.0
codespaces|Git|1.17.2
warm-up-typing-test|Jeu|1.1.0
vscode-insertdatestring|jsy|2.3.1
remote-explorer|ms-|0.5.2024070409
remote-server|ms-|1.6.2024070809
batch-runner|Nil|1.3.1
sourcepawn-vscode|Sar|8.0.2
vscode-fileutils|sle|3.10.3
file-size|zh9|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aacf:30263846
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
g316j359:31013175
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31057980
nativerepl1:31093711
refactort:31084545
pythonrstrctxt:31093868
0c838689:31088353
1iic9185:31091668

```

</details>

![Image-0](https://github.com/user-attachments/assets/f4be217e-f077-43a1-b8a2-d794348c43cb)
![Image-0](https://github.com/user-attachments/assets/a5a96369-a5ed-40de-90fe-8f73df49d251)

**Comment by IllusionMH** [comment]
Have you tried to restart cmd or even PC?
Also can you try to move it up in the order?

**Comment by JergenRoss** [comment]
Fixed by removed cli zip was conflict in path env. thank you for your suggest. sorry I double checked read my list of path env. this is closed case now.
