### ISSUE TITLE
On multi-selection I'm not able to select to the end of line

### ISSUE THREAD

**Issue by gustavokrause** [Microsoft/vscode#22224]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.6.0|
|vscode-docker|PeterJausovec|0.0.12|
|ejs-language-support|QassimFarid|0.0.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.7|
|tslint|eg2|0.8.1|
|vscode-relative-line-numbers|extr0py|0.0.5|
|Go|lukehoban|0.6.55|
|sublime-keybindings|ms-vscode|2.0.1|
|debugger-for-chrome|msjsdiag|2.6.0|
|vim|vscodevim|0.6.2|;

---

Steps to Reproduce:

1. select a block of code using multi-selection.
2. and press right util the end of the line.

**Comment by rebornix** [comment]
Can you provide some recording/gif to describe what you have run into? I can't reproduce from my side.

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.
