### ISSUE TITLE
multiselect sequence 

### ISSUE THREAD

**Issue by Florian1948** [microsoft/vscode#222374]
It would be great to have an automatic sequence from x to y with a multiselect, so you can quickly adjust tets, constants, or other variables. It is often the case that you can remove many parts of columns with the multiselect, but it takes a long time to fill them with other values.

**Comment by IllusionMH** [comment]
Could you please provide more detailed examples of behavior that you expect?

**Comment by ArturoDent** [comment]
Do you want to tab through selections, so you can add/replace text at each separately?  If so, I think you will need an extension to do that like https://marketplace.visualstudio.com/items?itemName=danseethaler.tab-through-selections.
