### ISSUE TITLE
Update Snippets for TypeScript 

### ISSUE THREAD

**Issue by Majirefy** [Microsoft/vscode#22231]
- VSCode Version: 1.10.1 (1.10.1)
- OS Version: macOS 10.12.3 (16D32)

Steps to Reproduce:

1. Type "import" in a TypeScript file to insert an import statement snippet.
2. this statement uses single quote mark(') instead of double quotemark(").

From TypeScript's source code and tslint recommendations, TypeScript should use double quotes for string.(As mentioned in coding guidelines: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines).

Please update these snippets to match the guide line.

**Comment by mjbvz** [comment]
Feel free to submit a PR with the change. Here's the file where the snippet is defined: https://github.com/Microsoft/vscode/blob/master/extensions/typescript/snippets/typescript.json

**Comment by mjbvz** [comment]
Fixed by #22255

**Comment by Aides359** [comment]
Is there any way to customize/disable/remove this import?
In our team we use single quotes for string literals and the best way to solve this at the moment is creating a user snippet with a name that comes alphabetically sorted before "import statement" and then there is still the possibility to get the wrong one.

**Comment by adyavanapalli** [comment]
@Aides359 please refer to the following [thread](https://github.com/Microsoft/vscode/pull/22255)
