### ISSUE TITLE
Make column selection work on the model, not the view model

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode#22235]
Steps to Reproduce:

1. In settings: "editor.wordWrap": "on" for view port wrapping. This makes long lines easy to read.
2. Column select using mouse drag with Shift+Alt.
3. Column select over a line that has been view port wrapped. The wrapped text is included in the selection. The wrapped text is only displayed in the same column. It isn't actually in the same column so shouldn't be included in the selection.

---

- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601

**Comment by alexandrudima** [comment]
This appears to work correctly for me. Are there more steps I'm missing:

![column-select](https://cloud.githubusercontent.com/assets/5047891/24366371/37e372d0-1319-11e7-95d9-b1bd7355c6ee.gif)

**Comment by BillDenton** [comment]
I made a mistake in my original description. I consider the behaviour shown above to be incorrect. Updated the last two sentences from:
> The wrapped text is only displayed in the same column. It isn't actually in the same column so should be _**should**_ included in the selection.

to

> The wrapped text is only displayed in the same column. It isn't actually in the same column so _**shouldn't**_ be included in the selection.
The word wrapping is only for display to allow long lines to fit on the display. When programming this helps to ensure that the whole line is seen. So do a column select in for example C/C++ file produces unexpected behaviour. This works as expected in SlickEdit (where the feature is called Soft Wrap (menu View, Soft Wrap). I'll try to create an animation showing this behaviour (similar to the one above), but I don't know how to do it.

**Comment by BillDenton** [comment]
Managed to get GIF using http://www.screentogif.com/, which shows the expected behaviour. Probably would have to easier to understand on code, but can't show that.
![slickedit soft word wrap](https://cloud.githubusercontent.com/assets/17859340/25240897/0a70526a-25ec-11e7-851d-9293b7ca2104.gif)

**Comment by alexandrudima** [comment]
At this time, "box selection" is implemented to work on the view model and not on the model. We need to find out if this is unexpected (i.e. what do other editors do).
