### ISSUE TITLE
Debugger: Launcher Configuration Extensions

### ISSUE THREAD

**Issue by trymeouteh** [microsoft/vscode#222310]
A way to create debugging launcher configuration extensions which can be used to run with other debugger configurations.

* * *

Lets say this is your launch configuration in the global `settings.json`

```
"launch": {
    "configurations": [
      {
        "name": "My NodeJS Debugger",
        "type": "node",
        "request": "launch",
        "program": "${file}"
      }
    ]
  },
```

And you also have a launch configuration in the `.vscode/launch.json`

```
{
  "configurations": [
    {
        "name": "My NodeJS Debugger (1)",
        "type": "node",
        "request": "launch",
        "program": "script.js",
        "args": ["a", "b", "c"]
    }
  ]
}
```

In the VSCode debugger dropdown, you will have two options when working in the workspace...

- My NodeJS Debugger
- My NodeJS Debugger (1)

This can work if you want to use the same launch configuration from `settings.json` but with additional configurations such as adding arguments for the workspace project. I would like to suggest the following layout...

```
{
  "configurations": [
    {
        "extend-name": "My Arguments abc",
        "program": "script.js",
        "args": ["a", "b", "c"]
    }
  ]
}
```

By adding new configuration options such as...

- extend-name: This will indicate that this configuration is not a configuration, but will act as a extensions of any other configuration.

Now in the debugger dropdown options, you will have these two options...

- My NodeJS Debugger
- My NodeJS Debugger+

When you run *My NodeJS Debugger* it will run the *My NodeJS Debugger* debugger from the `settings,json` config as is. When you run *My NodeJS Debugger+* it will run the *My NodeJS Debugger* debugger from the `settings,json` config and then prompt the user to choose an extended config to add onto it, The options that will be displayed in this example will be *My Arguments abc*. And all configurations from  *My Arguments abc* will overwrite the config settings in *My NodeJS Debugger* such as the `program` property which will be overwritten to `script.js` from *My Arguments abc*.

Therefore when you run *My NodeJS Debugger+* with the *My Arguments abc*, it will basically use this as a configuration when debugging...

```
    {
        "name": "My NodeJS Debugger+",
        "type": "node",
        "request": "launch",
        "program": "script.js",
        "args": ["a", "b", "c"]
    }
```

This way less configuration setup for your projects when

**Comment by roblourens** [comment]
Interesting idea, but I'm not sure it's a good fit because not everyone using that workspace config will have a user config with that name. Maybe you can tell me more about the problem you're having.

**Comment by roblourens** [comment]
Thanks for the explanation. I see how it could be useful for you but since workspaces are typically shared between multiple developers, I don't think we should build features that assume that the user has configured some other launch config, because not everyone would do that. Also I think this would just complicate and confuse the setup. I think that configuring some custom snippets for your reused launch configs would probably be the fastest way to get what you want with less typing.
