### ISSUE TITLE
Feature request: [cpp]/[c] editor settings for editor.acceptSuggestionOnEnter

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#22237]
We want something like this to work, similar to the [go]/etc. language-specific settings. Or some way for extensions to add it.

    "[cpp]": {
        "editor.acceptSuggestionOnEnter": false
    },
    "[c]": {
        "editor.acceptSuggestionOnEnter": false
    }

This matches the C++ completion behavior of Visual Studio, and it prevents annoying unwanted completions when a line ends with alphanumeric text and the intent is to go to the next line and not autocomplete.

**Comment by ramya-rao-a** [comment]
Adding this in the settings works as expected for me

```
"[cpp]": {
		  "editor.acceptSuggestionOnEnter": false
	  }
```

Do you mean that you want this to be added by default as described here: http://code.visualstudio.com/updates/v1_10#_language-specific-editor-settings ?

**Comment by sean-mcmanus** [comment]
Oh, I didn't even think that was possible, because it wasn't in the autocomplete list. Yeah, if our C++ extension can just read/modify the user settings with that, then we don't really care if VS Code itself has it defaulted or not.

**Comment by sean-mcmanus** [comment]
Oh, I found that extensions can add this to package.json, which is perfect. I don't know why I missed that before:

Default language specific editor settings: Extension authors can now contribute default language specific editor settings using the newly introduced extension point configurationDefaults in package.json.
Following example contributes default editor settings for the markdown language.
contributes": {
    "configurationDefaults": {
        "[markdown]": {
            "editor.wordWrap": "on",
            "editor.quickSuggestions": false
        }
    }
}
