### ISSUE TITLE
Diagnostic hover doing "word-wrap: break-word;" which makes them hard to read

### ISSUE THREAD

**Issue by joshbw** [Microsoft/vscode#22239]
- VSCode Version: 1.10.1 & Insider for Mar 8 2017 
- OS Version: Win 10 RS1

Steps to Reproduce:

1. Install an extension with fairly long diagnostic hovers (an example included below)
2. trigger the diagnostic hover
3. notice that the wrapping of text is breaking words, which makes reading the hover content much more difficult

I'm not entirely certain what to recommend to address this.  For the majority of text it is better to just have the word drop down a line rather than be broken, but for long URLs and such breaking a word is preferable.  I don't know if you can selectively break words by wrapping them in a span with css "word-wrap: break-word;", but if you can a strategy might be to preprocess the hover text and wrap URLs/UNC paths in said span (I don't know what else other than URLs and paths would be long enough that they need to break-word to fit in the hover box).  Alternatively, and this is my preference, you could support links within the hover, so that link text rather than the full URL can be shown.  That both makes it easier for people to access the URL (they could just click on it, instead of copying it out of the hover box and pasting in a browser) and provides a mechanism to show shorter text that doesn't need to be broken up

If you want a diagnostic that reproduces this scenario you can grab and install vscode-devskim-0.1.0.vsix from https://github.com/Microsoft/DevSkim-VSCode-Plugin.  Once installed, create a new .cpp file and type  gets(str); into it - DevSkim will catch the use of gets and add a diagnostic with text long enough that it triggers the undesired wrap conditions

**Comment by jrieken** [comment]
@joshbw can you attach a screen shot/capture please?

We have some special behaviour here because often diagnostics messages are 'ascii-formatted' like below and try to preserve that. Unsure if other word-wrap tricks can be used

```
some.code()
          ^^^^^
          unknown something, /some/file.fooLang,12,7
```

**Comment by joshbw** [comment]
![wrap](https://cloud.githubusercontent.com/assets/12884476/23775544/10694282-04de-11e7-91a5-0fcf8955359f.png)

you can see that condition and a couple other words are broken in the middle

**Comment by joaomoreno** [comment]
There is a constraint here. We use monospace font for diagnostics just so we can support the `^^^^` scenario, despite most text in this container is plain English, by far. Also despite the fact that we could render such information in much more user friendly way. But monospace fonts increase the width of each character and thus of each line, increasing the probability of wrapping.

At the same time, people sometimes place `reallyLongMethodNamesOrFunctionsThatAreBig` in these, making _wrap by words_ look really ugly.

So the only way to solve this is to continue with monospace and have character wrapping.

---

Going forward. Deprecate the current diagnostics API and have it  work just like the regular hover: a Markdown string which defaults to a non-monospace font but still lets language feature providers open up monospace code blocks with triple back quotes.

**Comment by joshbw** [comment]
> make them work just like the regular hover: a Markdown string 

That would be great - I'd love to have access to MD in a diagnostic

**Comment by smarter** [comment]
> Going forward. Deprecate the current way diagnostics are rendered and make them work just like the regular hover: a Markdown string which defaults to a non-monospace font but still lets language feature providers open up monospace code blocks with triple back quotes.

+1 to that, just had a user of our language server implementation report this and I guess there's nothing we can do on our side: https://github.com/lampepfl/dotty/issues/2665

**Comment by smarter** [comment]
Opened https://github.com/Microsoft/language-server-protocol/issues/250 to track this on the LSP side.

**Comment by jrieken** [comment]
closing this in favour of #54272
