### ISSUE TITLE
Window Corruption Upon Loading Monitor Configuration After Waking From Sleep

### ISSUE THREAD

**Issue by Evanjs** [Microsoft/vscode#22232]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cake-vscode|cake-build|0.6.0|
|cpptools|ms-vscode|0.10.2|
|csharp|ms-vscode|1.7.0|
|slack|sozercan|0.0.13|
|cmake|twxs|0.0.17|;

---
![image](https://cloud.githubusercontent.com/assets/1847524/23712541/4a679832-03f1-11e7-8643-8a6fb32b5f2e.png)

Steps to Reproduce:
(Note: My monitor configuration does not persist upon waking from sleep)
1. Let display go to sleep
2. Unlock computer
3. Load monitor configuration from NirSoft's MultiMonitorTool

P.S - Slack acts similarly and the entire application window is corrupted, whereas only the tab bar in Chrome is affected.

**Comment by bpasero** [comment]
Still happening?
