### ISSUE TITLE
Feature Request: ability to review 'git push' and compare to remote

### ISSUE THREAD

**Issue by MonkeySlut** [Microsoft/vscode#22238]
Hey, I may be missing something but, as for now when I finish coding and had already made some local commits and I'm ready to push changes to remote git branch, I cannot review the changes or even select which files should be pushed. 
Use cases: 
1. Local config files which should be locally committed but not pushed to remote.
2. Not yet ready changes but locally committed files that should not be pushed to remote (yet).
3. Last-minute review and comparison of changes that will be made when pushing (= git diff)

**Comment by joaomoreno** [comment]
#18676
