### ISSUE TITLE
Add command editor.action.hideHover + when context hoverVisible

### ISSUE THREAD

**Issue by jdanbrown** [microsoft/vscode#222316]
I'm trying to make keybindings to control hovers, suggestions, and parameter hints in the editor, but I'm stuck on hovers because vscode is currently missing a command for `editor.action.hideHover` and a when context for `hoverVisible`. This feature request is to add them:
- Add a command `editor.action.hideHover`
  - It should close the hover shown by the command `editor.action.showHover`
  - Similar to the existing command `closeParameterHints` for parameter hints
  - Similar to the existing command `hideSuggestWidget` for suggestions
- Add a when context `hoverVisible`
  - It should be true when the hover from the command `editor.action.showHover` is visible
  - Similar to the existing when context `parameterHintsVisible` for parameter hints
  - Similar to the existing when context `suggestWidgetVisible` for suggestions

For example, here are the keybindings I'd _like_ to define, for consistent keyboard controls across hovers + parameter hints + suggestions, but currently I can only make this work for parameter + suggestions, and not hovers:
```jsonc
  // Hover
  //  - [TODO Doesn't work -- missing editor.action.hideHover + hoverVisible]
  {
    "key": "ctrl+space",
    "command": "editor.action.showHover",
    "when": "textInputFocus && !hoverVisible",
  },
  {
    "key": "ctrl+space",
    "command": "editor.action.hideHover",
    "when": "textInputFocus && hoverVisible"
  },
  {
    "key": "escape",
    "command": "editor.action.hideHover",
    "when": "textInputFocus && hoverVisible && vim.mode == 'Normal'"
  },
```

```jsonc
  // Parameter hints
  //  - [Does work]
  {
    "key": "shift+cmd+space",
    "command": "-editor.action.triggerParameterHints",
    "when": "editorTextFocus && editorHasSignatureHelpProvider"
  },
  {
    "key": "shift+cmd+space",
    "command": "editor.action.triggerParameterHints",
    "when": "editorTextFocus && editorHasSignatureHelpProvider && !parameterHintsVisible"
  },
  {
    "key": "shift+cmd+space",
    "command": "closeParameterHints",
    "when": "editorTextFocus && parameterHintsVisible"
  },
  {
    "key": "escape",
    "command": "closeParameterHints",
    "when": "editorTextFocus && parameterHintsVisible && vim.mode == 'Normal'"
  },
```

```jsonc
  // Suggest
  //  - [Does work]
  {
    "key": "alt+escape",
    "command": "-editor.action.triggerSuggest",
    "when": "textInputFocus && editorHasCompletionItemProvider && !editorReadonly && !suggestWidgetVisible"
  },
  {
    "key": "alt+escape",
    "command": "editor.action.triggerSuggest",
    "when": "textInputFocus && editorHasCompletionItemProvider && !suggestWidgetVisible"
  },
  {
    "key": "alt+escape",
    "command": "hideSuggestWidget",
    "when": "textInputFocus && suggestWidgetVisible"
  },
  {
    "key": "escape",
    "command": "hideSuggestWidget",
    "when": "textInputFocus && suggestWidgetVisible && vim.mode == 'Normal'"
  },
```

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. I made this PR to add a hide hover action : https://github.com/microsoft/vscode/pull/235806. 

There are already context keys: `editorHoverVisible` and `editorHoverFocused`

**Comment by aiday-mar** [comment]
To verify:

Verify there is an action `editor.action.hideHover` in the command palette which you can use to hide the hover
You may have to bind keybindings
