### ISSUE TITLE
Allow to easily search in right-clicked folder

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#22247]
Hi,

- VSCode Version: 1.10.1
- OS Version: macOS SIerra

I would really appreciate when I could easily search the directory by
- right click the directory in Explorer
- select "Search..." action item
- it could switch to Search panel with properly predefined Directory for search...

Thanks!

**Comment by ramya-rao-a** [comment]
Right-clicking a directory in the explorer gives you the below menu. The "Find in Folder" menu option is what you are looking for?

![image](https://cloud.githubusercontent.com/assets/16890566/23724805/f9ace796-0402-11e7-870c-bc99b783a783.png)

**Comment by obrejla** [comment]
I'm really sorry, I was absolutely blind :( That's exactly what I needed... really don't know how could I overlook that. Sry for wasting your time. Thanks.

**Comment by ramya-rao-a** [comment]
:) No problem
