### ISSUE TITLE
powershell auto complete opens when terminating a program with ctrl+c

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#222475]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Run a program which launches in the terminal and waits for input
2. press ctrl+c to escape the program

:bug: auto complete opens

![Recording 2024-07-21 at 09 45 34](https://github.com/user-attachments/assets/cbbe4809-3c1a-41cf-b70b-759bffc18da6)

**Comment by Tyriar** [comment]
I think this is fixed, need to try again in tomorrow's build

**Comment by Tyriar** [comment]
Works for me, @amunger please reopen if you still see it
