### ISSUE TITLE
Launching or reloading task on Windows pastes clipboard text before launch command in terminal

### ISSUE THREAD

**Issue by jdforsythe** [Microsoft/vscode#22245]
- VSCode Version: 1.10.1
- OS Version: Windows 10

Steps to Reproduce:

1. Copy text to clipboard
2. Use F5 to launch node task

Here's an example of what shows up in the terminal tab:

![vscode-terminal-paste](https://cloud.githubusercontent.com/assets/286972/23719901/04e6f9dc-040b-11e7-89e1-b7cdca383e28.PNG)

As you can see, when it switches to the terminal tab and "pastes" in the command to execute, it also pastes in what's on the clipboard - "imported_shift" in this case.

This does not happen every time but it has happened a lot today. I'll try to note any pattern.

Launch config
```json
{
      "name": "Debug All (node2)",
      "type": "node2",
      "request": "launch",
      "stopOnEntry": false,
      "args": [
        "--nolazy",
        "${workspaceRoot}/debugall.js"
      ],
      "cwd": "${workspaceRoot}/",
      "preLaunchTask": null,
      "runtimeExecutable": null,
      "env": {
        "NODE_ENV": "development",
        "LOGSQL": "false",
        "USE_COMPRESSION": "false",
        "ENABLE_DEV_DOMAIN": "true"
      },
      "sourceMaps": false,
      "outDir": null,
      "console": "integratedTerminal",
      "skipFiles": [
        "<node_internals>/**",
        "**/node_modules/**"
      ]
    },
```

**Comment by jdforsythe** [comment]
Changed the title because it just happened when the app was already running and I clicked the restart button in the debug bar.

![pasting-again](https://cloud.githubusercontent.com/assets/286972/23727757/5681c58a-0427-11e7-8248-2a6de92ece43.PNG)

**Comment by isidorn** [comment]
VSCode is only adding output to the terminal if this is coming from the debug adapter [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L366)

Thus assigning to @roblourens to check if his `node2` adapter is sending something unexpected.

**Comment by roblourens** [comment]
I have no idea what could cause this. I doubt that the debug adapter is reading the clipboard, but just to check exactly what it's sending to vscode, can you set `"diagnosticLogging": true`, and send me the log file at the path that it prints at the top of the console?

**Comment by jdforsythe** [comment]
Does the `"diagnosticLogging"` flag get set in `launch.json`? It isn't outputting anything about a log file in the console or terminal.

Launch config:
```json
{
      "name": "Debug All (node2)",
      "type": "node2",
      "request": "launch",
      "stopOnEntry": false,
      "args": [
        "--nolazy",
        "${workspaceRoot}/debugall.js"
      ],
      "cwd": "${workspaceRoot}/",
      "preLaunchTask": null,
      "runtimeExecutable": null,
      "env": {
        "NODE_ENV": "development",
        "LOGSQL": "false",
        "USE_COMPRESSION": "false",
        "ENABLE_DEV_DOMAIN": "true"
      },
      "sourceMaps": false,
      "outDir": null,
      "console": "integratedTerminal",
      "skipFiles": [
        "<node_internals>/**",
        "**/node_modules/**"
      ],
      "diagnosticLogging": true
    },
```

Terminal:
```sh
PS C:\dev\SenSourceOne> cd 'c:\dev\SenSourceOne/'; $env:NODE_ENV='development'; $env:LOGSQL='false'; $env:USE_COMPRESSION='false'; $env:ENABLE_DEV_DOMAIN='true'; $env:LOCALS3='false'; $env:LOCALFS='false'; node --inspect=15041 --debug-brk --nolazy c:\dev\Sen
SourceOne/debugall.js
>>
Debugger listening on port 15041.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=localhost:15041/9dc214a7-e882-4be1-a6d9-a22c49c0a36f
Debugger attached.
2017-03-14T15:21:01.079Z - debug: io.entities
```

The final ("debug: io.entities") line is where the application starts. In the debug console the "io.entities" line is the first to show. I don't see anything about a log file.

**Comment by roblourens** [comment]
The log file line is actually written to the debug console, not the terminal.

**Comment by jdforsythe** [comment]
@roblourens it doesn't appear to get printed at all when using "console": "integratedTerminal"

**Comment by jdforsythe** [comment]
@roblourens I got the path. Can I email the log? It isn't a public project. I'll grab a copy of it when it happens again.

**Comment by roblourens** [comment]
Sure, my email is in my profile

**Comment by jdforsythe** [comment]
@roblourens After not experiencing this for awhile I think I've found the issue. This is probably a result of inadvertent right-clicking into the terminal pane at some point before hitting F5 or clicking Play to start the application.

If the launch config is set for `integratedTerminal` the terminal tab that is used for the launch gets reused, including whatever partial command is typed (or in this case, pasted) in.

So for me this isn't a bug so much as an annoyance. But knowing the cause, I can deal with it!

**Comment by roblourens** [comment]
Oh, that makes perfect sense!
