### ISSUE TITLE
High CPU usage under WSL even when vscode is idle

### ISSUE THREAD

**Issue by tusharsnx** [microsoft/vscode#222412]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
```
Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.26100
```
- OS Version: Windows_NT x64 10.0.26100

Steps to Reproduce:

1. Open vscode from within wsl:
```
(wsl) $ code .
```
2. Use `htop` or similar tool to monitor CPU usage.

### Issue Description

I recently noticed high CPU usage and faster battery drain (intel cpu) when working with any project under WSL. To find out what's taking so much cpu time (even when I'm doing nothing, apart from staring at the screen), I used `htop` to list processes in the order of cpu usage:

![Screenshot 2024-07-21 190742](https://github.com/user-attachments/assets/0628ff78-4188-4be9-9f2d-5c6063bd525c)

Looked like vscode's remote server running inside wsl is taking CPU. So, I went a little further to profile the running instance of the remote server and I found:

![Screenshot 2024-07-21 190858](https://github.com/user-attachments/assets/fea1be5e-5755-492d-97f9-0731c7096d32)

![Screenshot 2024-07-21 191001](https://github.com/user-attachments/assets/54b2af48-5926-46c5-80a8-9f023264c138)

`I` from `extensionHostProcess.js` is being called at a regular interval with a small delay (~1000ms). `I`:

![Screenshot 2024-07-21 191040](https://github.com/user-attachments/assets/07bf8e9a-273b-4f00-8a30-d6ff684a2b5e)

I was able to trace `I` back to [findCandidatePorts()](https://github.com/microsoft/vscode/blob/0eec43797f37c7c66e400f0a7a5f8f15e25caddc/src/vs/workbench/api/node/extHostTunnelService.ts#L243):

![Screenshot 2024-07-21 191217](https://github.com/user-attachments/assets/2373095e-cd81-4d91-b5d9-3b632f899ef6)

And I finally found where it is being called repeatedly:

![Screenshot 2024-07-21 191329](https://github.com/user-attachments/assets/233aafa5-30e0-4f42-af10-5b8087a669b3)

Now, why is it a bug? Because I've disabled all `remote.autoForwardPorts` related settings in my config, yet the tunnel monitoring service is running in the background. I expect the service to not be running when `remote.autoForwardPorts` or related configs are disabled. The service is currently always running.

**Comment by tusharsnx** [comment]
Since this was tagged as invalid, I'm curious about how to write a 'valid' bug report.

**Comment by tusharsnx** [comment]
Okay, I get the point, the issue tracker is plagued with massive issue spam. I created another issue but this time from within vscode's "Report issue" option 👍

**Comment by bhavyaus** [comment]
Apologies for the overhead. 
Please feel free to close this issue for the newer one.

**Comment by tusharsnx** [comment]
Sure, thanks.
