### ISSUE TITLE
Keybinding changes take a few seconds to take effect

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#22240]
- Open keybindings
- Add `{ "key": "ctrl+u", "command": "workbench.action.toggleSidebarPosition" }`, and save
- Remove that line, save, and press ctrl+u a few times
- The keybinding is still in effect for several seconds before it stops working. I can imagine this could be confusing if you were make quick changes to keybindings.

**Comment by bpasero** [comment]
There is a couple of things that happen when you save the keybindings:
* the user saves keybinding.json in the renderer
* we react to a file change event an that for some reason seems to have a delay of 1s on the main side
* we find out if the keybindings have actually changed and ask the renderer to resolve keys again
* renderer sends keys back to main
* we update the menu after another delay of 0ms (just a timeout)

I am not sure why I decided to have a 1s delay before reacting to changes to keybindings.json, I can reduce this to 100ms.
