### ISSUE TITLE
Add a symbol list in view bar or side bar

### ISSUE THREAD

**Issue by forevering** [Microsoft/vscode#22248]
Hi, I think the Minimap is a really great feature in latest version. However, I'd like a symbol list in view bar or side bar like the VS have. Because it's really convenient for me to find the function from hundreds of functions. So, could you guys think about it in the future version? Thanks!

**Comment by hoovercj** [comment]
@forevering add a thumbs up (not a +1 comment) on #5605

**Comment by ramya-rao-a** [comment]
This is tracked in #5605
