### ISSUE TITLE
Custom Theme disables other language colors

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#22246]
Hi,

- VSCode Version: 1.10.**2**
- OS Version: macOS Sierra

I created a custom theme which uses `*.js` scopes to define colors for such recognized scopes. Unfortunately, the side effect is that all other file types are affected by that custom theme, it means that other file types ".json, .md, or whatever" are not colorized.

I would expect that only exact scope will be affected and other scope types will use default from Theme I selected as default during last `yo code` step when creating Custom Theme.

Or am I absolutely wrong?

I just want to rewrite `.js` file coloring to my colors. Is it simply possible, by e.g. extending some default light theme?

Thanks!

**Comment by aeschli** [comment]
Text mate theme are self contained and do not inherit rules from an other theme.
Instead of modifying the rules, just duplicate them first and modify the copy.

**Comment by obrejla** [comment]
Well, thanks. And where can I find e.g. the Default Light+? Because [this](https://github.com/Microsoft/vscode/blob/80f8000c10b4234c7b027dccfd627442623902d2/extensions/theme-colorful-defaults/themes/light_plus.tmTheme) does not seems to be the right tmTheme...at least at first glance, there are in fact no rules for HTML, Json, or specific languages? Thanks for the advice.

**Comment by obrejla** [comment]
What I tried, I copied [QuietLight theme](https://github.com/Microsoft/vscode/blob/80f8000c10b4234c7b027dccfd627442623902d2/extensions/theme-quietlight/themes/QuietLight.tmTheme) and pasted my specific rules from my base theme to the end (and also to start) of the file and it didn't work either. Only rules from QuietLight theme were applied...really don't know what should I do more.

**Comment by obrejla** [comment]
Sorry, it behaves really strangely...if I copy the content of Defaul Light+ theme file to my custom theme and select it (without my rules, just plain Default rules), then rules are applied only for javascript files, but not for json or html... But if I select Default Light+ from color themes select dialog (that real default theme), then everything is colored properly...all files...

What should I do? I'm starting to be a bit lost in it...

**Comment by aeschli** [comment]
Default Light+ uses an internal format (in JSON) that can inhert from other formats.
We're working on making that an officially supported format, but for now we resommend to use tmTheme files. With tmTheme you need to include all color rules.

**Comment by obrejla** [comment]
Oh god :/ Nevermind, thanks for the response. Do you have some time estimate, when it could be out? I don't wanna write a coloring for other languages, or all possible rules...that's just timewasting :( Thanks a lot!
