### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by Arcilac** [microsoft/vscode#222462]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.6.0-dev.20240720

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3250U with Radeon Graphics          (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|5.94GB (0.52GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/arcila/apptiempo --remote=wsl+Ubuntu --crash-reporter-id 18f58d4e-8794-4e0c-8cba-56bd428aafa2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 3 3250U with Radeon Graphics (4 x 0)|
|Memory (System)|2.88GB (0.44GB free)|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-neovim|asv|1.18.5
auto-rename-tag|for|0.1.10
output-colorizer|IBM|0.1.2
dotenv|mik|1.0.1
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.4.3
pdf|tom|1.2.2
errorlens|use|3.20.0
vim-cheatsheet|And|0.0.1
vscode-npm-import-package-version|axe|0.8.1
vscode-tailwindcss|bra|0.12.5
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
duplicate|gee|1.0.2
copilot|Git|1.214.0
copilot-chat|Git|0.17.1
vscode-github-actions|git|0.26.3
rest-client|hum|0.25.1
path-autocomplete|ion|1.25.0
vscode-edit-csv|jan|0.9.2
rainbow-csv|mec|3.12.0
template-string-converter|meg|0.6.1
vscode-docker|ms-|1.29.1
vscode-typescript-next|ms-|5.6.20240720
gremlins|nho|0.26.0
prisma|Pri|5.17.0
LiveServer|rit|5.7.9
code-spell-checker|str|3.0.1
code-spell-checker-spanish|str|2.3.4
quokka-vscode|Wal|1.0.649
pretty-ts-errors|Yoa|0.5.4
jwt-debugger|yok|0.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31094925
pythonrstrctxt:31093869

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled) (besides the typescript nightly)?
