### ISSUE TITLE
Multiple column breakpoints on the same line only sends first to the debugger

### ISSUE THREAD

**Issue by wesrupert** [Microsoft/vscode#22249]
- VSCode Version: 1.10.2 [commit 8076a19]
- OS Version: Windows 10
![image](https://cloud.githubusercontent.com/assets/2474675/23722601/d5b2d43e-03fa-11e7-95b3-621b82ca8a58.png)

##  Steps to Reproduce:

1. Create a sample C# app with multiple code blocks on the same line:
![image](https://cloud.githubusercontent.com/assets/2474675/23721519/ea63d670-03f6-11e7-9c57-a7422d80fd14.png)

2. Set multiple column breakpoints on the line **while not debugging**
![image](https://cloud.githubusercontent.com/assets/2474675/23721553/10ba467e-03f7-11e7-9f48-504dd15df34f.png)

3. F5 the app

## Results:
**Expected:** setBreakpoints request has multiple breakpoints on the same line

**Actual:** setBreakpoints request only has the first breakpoint from that line, causing the remaining ones to disappear once the debugger sends a response
![image](https://cloud.githubusercontent.com/assets/2474675/23721736/b0a553d6-03f7-11e7-9ce9-d737a580d7a1.png)

## Sample
[sample - repro.zip](https://github.com/Microsoft/vscode/files/828871/sample.-.repro.zip)

Debug protocol log from C# debugger:
```json
...Some messages truncated...
-> (C) {"command":"launch","arguments":{"name":".NET Core Launch","type":"coreclr","request":"launch","preLaunchTask":"build","program":"e:\\Share\\Samples\\XPlat\\sample - repro/bin/Debug/netcoreapp1.1/sample - repro.dll","args":[],"cwd":"e:\\Share\\Samples\\XPlat\\sample - repro","logging":{"engineLogging":true}},"type":"request","seq":2}
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"launch"}
<- (E) {"seq":5,"type":"event","event":"initialized","body":{}}
-> (C) {"command":"setBreakpoints","arguments":{"source":{"path":"e:\\Share\\Samples\\XPlat\\sample - repro\\Program.cs","name":"Program.cs"},"lines":[37],"breakpoints":[{"line":37,"column":35}],"sourceModified":false},"type":"request","seq":4}
<- (R) {"seq":6,"type":"response","request_seq":4,"success":true,"command":"setBreakpoints","message":"","body":{"breakpoints":[{"id":1,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts."}]}}
-> (C) {"command":"setExceptionBreakpoints","arguments":{"filters":["user-unhandled"]},"type":"request","seq":5}
<- (R) {"seq":7,"type":"response","request_seq":5,"success":true,"command":"setExceptionBreakpoints"}
-> (C) {"command":"configurationDone","type":"request","seq":6}
-> (C) {"command":"threads","type":"request","seq":7}
<- (R) {"seq":10,"type":"response","request_seq":6,"success":true,"command":"configurationDone"}
...Some messages truncated...
```

**Comment by wesrupert** [comment]
Note: Column breakpoint support for the C# extension is in-progress, so the response will not be the same in the wild. The important part is the setBreakpoint command.

```json
{"command":"setBreakpoints","arguments":{"source":{"path":"...","name":"Program.cs"},
>>>>    "lines":[37],"breakpoints":[{"line":37,"column":35}],
"sourceModified":false},"type":"request","seq":4}
```

**Comment by isidorn** [comment]
@wesrupert great catch - we should have caught this in the endgame. It will be available in tomorrow's insiders.
We also recommend all our debug extension writers to use vscode insiders to faster spot bugs and get on fixes earlier.

**Comment by weinand** [comment]
All column breakpoints are now sent correctly.
However, they are immediately removed from VS Code model (see https://github.com/Microsoft/vscode/issues/23659)
