### ISSUE TITLE
--uninstall-extension doesn't seem to work

### ISSUE THREAD

**Issue by bobbrow** [Microsoft/vscode#22258]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.2|
---

Steps to Reproduce:

1. code --uninstall-extension ms-vscode.cpptools

Description:
We have a user who is asking for scriptability with updating extensions.  I didn't see a --update-extension switch for vs code, so I was trying out --uninstall-extension to see if they could script an update by uninstalling and reinstalling the extension.  This is what code prints out when I attempt to uninstall via the cmd line:
```
Uninstalling ms-vscode.cpptools...
{ [Canceled: Canceled] name: 'Canceled', message: 'Canceled' }
```
see: https://github.com/Microsoft/vscode-cpptools/issues/306

**Comment by joaomoreno** [comment]
#18826
