### ISSUE TITLE
API feature request to NOT modify the file after TextEditorEdit#setEndOfLine is called

### ISSUE THREAD

**Issue by jedmao** [Microsoft/vscode#22259]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:

1. Using the API, call [`TextEditorEdit#setEndOfLine`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nametexteditoreditaspan-classcodeitem-id339texteditoreditspan)
2. Notice that the file is now marked dirty.

This would be OK for most purposes, but for the purpose of [`editorconfig-vscode`](https://github.com/editorconfig/editorconfig-vscode), we don't wish to modify the file (marking it dirty) on open.

This feature request is requesting an option I can send along, like so:

```ts
setEndOfLine(eol, { modify: false });
```
This would be backwards compatible.

Related issues:
 - https://github.com/Microsoft/vscode/issues/9494
 - https://github.com/editorconfig/editorconfig-vscode/issues/57 and the host of duplicates filed (see the bottom of the page).

**Comment by jrieken** [comment]
@jedmao Are you saying the file should be immediately saved to disk after that? If you change it (that includes changing the EOL-sequence) the file will be dirty because it got modified. Please clarify. Thanks

**Comment by jedmao** [comment]
@jrieken no. I'm saying that `{ modify: false }` would ensure the file is NOT saved. Basically, allowing me to set my end of line "mode" w/o modifying the file. This way, someone can have their `.editorconfig` file setup with `end_of_line = lf` and they will see `LF` in the status bar whenever they open a file (w/o modfiying the file on open).

I'm saying please give me a way to set the end of line sequence w/o saving or modifying the file.

**Comment by jedmao** [comment]
@jrieken the `files.eol` user/workspace setting works in such a way that when you open a file the EOL mode is selected for you w/o modifying the file. I'm basically asking for the ability to do the same thing w/ the extension API, also NOT modifying the file, because this is a file open operation.

**Comment by jrieken** [comment]
> I'm saying please give me a way to set the end of line sequence w/o saving or modifying the file.

Isn't that then a no-op? Do you wanna make the new eol-sequence only effective when *other* changes happen in that file? And then for the whole file or just the affected lines? Today the status bar reflects the 'is' not the 'wants'.

**Comment by jedmao** [comment]
> Today the status bar reflects the 'is' not the 'wants'.

@jrieken that's not actually true. I created a file with mixed line endings that looks like this:

```
foo\r\n
bar\n
```

Then, I opened the file in vscode w/o extensions enabled. In the status bar, it reflects my user settings:

```json
"files.eol": "\r\n"
```

I see `CRLF` in the status bar, but the file is not marked dirty. This is because on file open, vscode's status bar reflects the 'wants', not the 'is'.

If I then manually change the EOL sequence, the file is marked dirty.

**Comment by jrieken** [comment]
>  vscode's status bar reflects the 'wants', not the 'is'.

We take the predominant line ending occurring in the file because we cannot show this per-line in the status bar. Add one more line with `\n` and the status bar will show it like that, not the preference.

**Comment by jedmao** [comment]
Interesting! Well, I guess I'll have to set the EOL sequence just before file save then.

**Comment by jrieken** [comment]
Yes, be a `onWillSaveTextDocument`-listener and make you changes *before* the file is being saved.

**Comment by jedmao** [comment]
@jrieken you're not joking that it's bumpy! I have an implementation [here](https://github.com/jedmao/editorconfig-vscode/blob/debddb1d502c416a889377af00d5867c90f91c01/src/transformations/endOfLine.ts#L25-L36), but it doesn't work for the very reasons you mentioned above, that it takes the predominant line ending on file open as the EOL setting.

As such, [this test](https://github.com/jedmao/editorconfig-vscode/blob/debddb1d502c416a889377af00d5867c90f91c01/test/index.test.ts#L113-L123) fails:

```ts
test('end_of_line = lf', async () => {
	const savedText = await withSetting(
		'end_of_line',
		'lf',
		{
			contents: 'bar\r\n'
		}
	).saveText('foo\r\n');
	assert.strictEqual(savedText, 'foo\nbar\n',
		'editor fails to convert CRLF line endings into LF on save');
});
```
As you can see, the initial contents have `\r\n` as the line ending, so CRLF will be the initial EOL setting on file open. Even if I programmatically change those CRLFs into LFs `onWillSaveTextDocument` it just changes them right back on save.

**Comment by jedmao** [comment]
@jrieken I got a before-save implementation working just fine. The only problem is that I have to find the editor for the text document that's going to be saved first and then `await` the `setEndOfLine` to complete before doing the rest. Seems to work!

See https://github.com/editorconfig/editorconfig-vscode/pull/116 for more context.
