### ISSUE TITLE
Dynamic string completions from TypeScript are not respected by default

### ISSUE THREAD

**Issue by ssalbdivad** [microsoft/vscode#222583]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.1
- OS Version: Windows 11 + WSL (Ubuntu)

By default, the `strings` key in `editor.quickSuggestions` is set to `"off"`.

I presume this is to reduce noise and clutter among suggestions, as string suggestions based on other words in the file or similar are not always particularly helpful.

However, it also prevents TypeScript from providing completions that some types were explicitly designed to offer. E.g. in [ArkType](https://github.com/arktypeio/arktype), when a user has written `type("string | num")`, they should get a suggestion `"string | number"`, but this only works if they have explicitly opted in to the following setting:

```json
	"editor.quickSuggestions": {
		"strings": "on"
	}
```

While I encourage them to do so, not everyone finds that information and those who don't have a significantly worse DX as a result.

Perhaps this setting could have additional granularity and a default that avoids filtering out suggestions that were clearly intended?

**Comment by mjbvz** [comment]
You can still manually trigger suggestions inside strings

If you want suggestions are you type inside of a string, changing the setting seems reasonable for specialized use case  like this
