### ISSUE TITLE
Prelaunch task not working with tasks v2.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#22250]
- VSCode Version: 1.10.0

From https://github.com/Microsoft/vscode/issues/981

I have another problem with this:
in launch.json (v 0.2.0) i have added some debugging entries with a preLaunchTask.
when i now debug, i get: There is a task {0} running. Can not run pre launch task build.
if i empty the content of the preLaunchTask, it works but the code is not built before.
Could it be that upgrading the tasks,json to v2.0.0 while having a launch,json at version 0.2.0 creates some incompatibilities?
launch.json
"version": "0.2.0",
    "configurations": [{
     {
            "name": ".NET Core Launch (myapp)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/Services/myapp/src/bin/Debug/netcoreapp1.1/myapp.dll",
            "args": [],
            "cwd": "${workspaceRoot}/Services/myapp/src/bin/Debug/netcoreapp1.1/",
            "stopAtEntry": false,
            "externalConsole": false,
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Local",
                "ASPNETCORE_URLS": "http://*:5000"
            }
     }]
tasks.json
"version": "2.0.0",
    "command": "",
    "isShellCommand": true,
    "args": [],
    "tasks": [{
            "taskName": "build",
            "command": "dotnet",
            "args": [
                "build"
            ],
            "options": {
                "cwd": "${workspaceRoot}"
            },
            "isBuildCommand": true,
            "showOutput": "always",
            "problemMatcher": "$msCompile"
        },
        //... some other tasks here not related to build and a dependency between those.
]}

**Comment by Jonathan34** [comment]
Thanks!

**Comment by dbaeumer** [comment]
OK. The problem seems to be that the terminal doesn't signal a process end if that process has never written to the console. Therefore the debugger thinks that the build hasn't finished.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/23119

**Comment by Jonathan34** [comment]
This still does not work with Version 1.11.0-insider although i see the dup is set as fixed.
`There is a task {0} running. Can not run pre launch task build.`

tasks.json is "version": "2.0.0",
and launch.json is "version": "0.2.0",

**Comment by dbaeumer** [comment]
@Jonathan34 this is strange. I tested this two days ago and it worked for me without any problems using a comparable TS setup.

**Comment by dbaeumer** [comment]
@Jonathan34 can you provide me with a sample I can clone to further investigate ?

**Comment by dbaeumer** [comment]
Here is what I see with dotnet core and a simple console app.

![cast](https://cloud.githubusercontent.com/assets/1931590/24546009/cc74dea0-1609-11e7-959a-7db72507722e.gif)

**Comment by dbaeumer** [comment]
So there must be something different with our setup which I don't see.

**Comment by Jonathan34** [comment]
I just received an update to commit: cc46bbf5b0412e464f89280e828d602fbc06a0f4 (2017-03-31T13:40:54.578Z) and now it seems to work!

I did an update yesterday, may be it was not there yet?

Can be closed!

**Comment by alexriedl** [comment]
I just got the latest inside build and I am still having this issue. It seems to happen after I run a different task, then try to launch my application.
Example steps I ran:
1. <ctrl+p> - type in "task test"
2. Let tests run and finish
3. <f5> - to launch the application

`There is a task {0} running. Can not run pre launch task build.` message pops up.

**Comment by dbaeumer** [comment]
@alexriedl thanks a lot for the steps. Was able to reproduce.

**Comment by Jonathan34** [comment]
Sorry, if i click the play button on the top left to start debugging, it says `There is a task {0} running. Can not run pre launch task build.` so this is not yet fixed i guess.

I can send the launch.json and tasks.json if you need, just give me one email address

**Comment by dbaeumer** [comment]
@Jonathan34 this needs a released insider build which has not happened yet since we are in endgame process. The build must be at least 2017-04-04:....

**Comment by dbaeumer** [comment]
If you can still reproduce in a newer build can you please provider a reproducible case. Simply having the tasks.json and launch.json is most of the time not enough. Best would be a GitHub repository to clone from.

**Comment by Jonathan34** [comment]
@dbaeumer works with 2017-04-04T10:14:08.729Z!
thanks

**Comment by alexriedl** [comment]
The issue is still happening with the inside build 2017-04-04T10:22:56:510Z.

I through together a small project that is structured similar to my project to demo the issue [in my github](https://github.com/alexriedl/prelaunch-task). Steps to reproduce are in the readme. Let me know if you need any other details.

**Comment by Jonathan34** [comment]
yes i confirm @alexriedl !

**Comment by dbaeumer** [comment]
@alexriedl @Jonathan34 sorry, my fault. The fix went into master, but the current insiders are build for the release/1.11 branch. When we have released 1.11 the insider will switch to master again and then the fix will be available there. Sorry for the confusion around this.

**Comment by jagadeesh1492** [comment]
any solution for this https://stackoverflow.com/questions/43627751/visual-studio-code-could-not-find-the-prelaunchtask-build#

**Comment by dbaeumer** [comment]
@jagadeesh1492  This got addressed in the latest inside build and will be available in the next release. A workaround is to close and reopen VS Code on the workspace.
