### ISSUE TITLE
JSDoc completer not adding params to functions that are assigned to object keys

### ISSUE THREAD

**Issue by alexkrolick** [Microsoft/vscode#22251]
### Expected behavior

The params are inferred from the function signature, like this:

<img width="383" alt="screen shot 2017-03-08 at 12 31 57 pm" src="https://cloud.githubusercontent.com/assets/1571667/23722726/50df8f8a-03fb-11e7-908a-80e8b92aec6f.png">

### Actual behavior

If the assigned variable is an object key, no params are inferred:

<img width="347" alt="screen shot 2017-03-08 at 12 31 38 pm" src="https://cloud.githubusercontent.com/assets/1571667/23722784/8b1ed552-03fb-11e7-9e55-21c452fc5d08.png">

This particularly affects commonjs exports:

<img width="412" alt="screen shot 2017-03-08 at 12 25 29 pm" src="https://cloud.githubusercontent.com/assets/1571667/23722543/a0559fd8-03fa-11e7-8e49-524781c1821e.png">

- VSCode Version: 1.10.2
- OS Version: Darwin 16.4.0

**Comment by mjbvz** [comment]
Tracked upstream as https://github.com/Microsoft/TypeScript/issues/14134
