### ISSUE TITLE
Raspberry issue during npm run watch (gulp watch --max_old_space_size=4096)

### ISSUE THREAD

**Issue by 40tude** [Microsoft/vscode#22256]
- VSCode Version: git fetch from today. (1.11.0)
- OS Version: Linux raspberrypi3 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

Steps to Reproduce:

1. git fetch origin
2. cd vscode
3. sudo ./scripts/npm.sh install
4. sudo npm run watch 

Please find below the output in the console and the content of npm-debug.log
Any help and advises are welcome
Best regards, Philippe

PS : similar behavior if step 3 above is
3. sudo ./scripts/npm.sh install -arch=armhf

// --------------------------------------------------------------
// --------------------------------------------------------------
// --------------------------------------------------------------
> code-oss-dev@1.11.0 watch /home/philippe/Documents/vscode
> gulp watch --max_old_space_size=4096

[23:01:33] Node flags detected: --max_old_space_size=4096
[23:01:33] Respawned to PID: 5894
Segmentation fault

npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "watch"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! code-oss-dev@1.11.0 watch: `gulp watch --max_old_space_size=4096`
npm ERR! Exit status 139
npm ERR! 
npm ERR! Failed at the code-oss-dev@1.11.0 watch script 'gulp watch --max_old_space_size=4096'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the code-oss-dev package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp watch --max_old_space_size=4096
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs code-oss-dev
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls code-oss-dev
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/philippe/Documents/vscode/npm-debug.log

// --------------------------------------------------------------
// --------------------------------------------------------------
// --------------------------------------------------------------
Content of npm-debug-log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'watch' ]
2 info using npm@4.1.2
3 info using node@v7.7.1
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle code-oss-dev@1.11.0~prewatch: code-oss-dev@1.11.0
6 silly lifecycle code-oss-dev@1.11.0~prewatch: no script for prewatch, continuing
7 info lifecycle code-oss-dev@1.11.0~watch: code-oss-dev@1.11.0
8 verbose lifecycle code-oss-dev@1.11.0~watch: unsafe-perm in lifecycle true
9 verbose lifecycle code-oss-dev@1.11.0~watch: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/philippe/Documents/vscode/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle code-oss-dev@1.11.0~watch: CWD: /home/philippe/Documents/vscode
11 silly lifecycle code-oss-dev@1.11.0~watch: Args: [ '-c', 'gulp watch --max_old_space_size=4096' ]
12 silly lifecycle code-oss-dev@1.11.0~watch: Returned: code: 139  signal: null
13 info lifecycle code-oss-dev@1.11.0~watch: Failed to exec watch script
14 verbose stack Error: code-oss-dev@1.11.0 watch: `gulp watch --max_old_space_size=4096`
14 verbose stack Exit status 139
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid code-oss-dev@1.11.0
16 verbose cwd /home/philippe/Documents/vscode
17 error Linux 4.4.50-v7+
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "watch"
19 error node v7.7.1
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error code-oss-dev@1.11.0 watch: `gulp watch --max_old_space_size=4096`
22 error Exit status 139
23 error Failed at the code-oss-dev@1.11.0 watch script 'gulp watch --max_old_space_size=4096'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the code-oss-dev package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp watch --max_old_space_size=4096
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs code-oss-dev
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls code-oss-dev
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by joaomoreno** [comment]
Can you retry everything all over again without using sudo at all?

**Comment by 40tude** [comment]
Bonjour
Worked like a charm
This is all my fault
Just to make sure you know what I did wrong : it was an issue of ownership
of the directory
It is a shame... Sorry for that.

One quick question :
What is the purpose of "*npm run watch*" and when one is suppose to use it?
I saw few words about it in the documentation but the reason why one have
to invoque it is not clear for me
Thank for your reply

You can close the "issue"
Thank you again and best regards, Philippe




Cordialement, Philippe
// -------------------
40tude.fr

2017-03-09 9:38 GMT+01:00 João Moreno <notifications@github.com>:

**Comment by joaomoreno** [comment]
`npm run watch` compiles our TypeScript sources into JavaScript, which is what gets executed.
