### ISSUE TITLE
TypeScript mode created to eagerly which results in unnecessary plugin activation

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2225]
For Salsa we changed the TypeScript extension to be activated on JavaScirpt files which no leads to all plugins being activated that deal with TypeScript files (e.g. tslint). Here is what is happening:

- open workspace
- open JavaScript file
- this activates the TypeScript extension
- the extension registers declarative supports.
- registering a declarative support eagerly creates the TypeScript mode
- this activates all extensions that deal with TypeScript sources

IMO registering a declarative support shouldn't result in eagerly creating the mode.

**Comment by dbaeumer** [comment]
The bahaviour can be observer in the following way:

- new workspace
- install tslint extension
- create a JS file in the workspace
- open the JS file

Observe: tslint prompts you for the missing tslint node module.

**Comment by dbaeumer** [comment]
Below a stack trace showing this activation:
![capture](https://cloud.githubusercontent.com/assets/1931590/12551677/79c2f80e-c36c-11e5-9e77-985e7035b060.png)

**Comment by alexandrudima** [comment]
@dbaeumer Registering a mode support means the support must sit (be stored) somewhere. Since the code was written this is implemented as instantiating the mode and then storing the support on the mode itself.

So registering a support for mode 'X' will instantiate and activate the language 'X'.

I am not sure I understand what you'd want me to do.

**Comment by dbaeumer** [comment]
@alexandrudima I think registering a declarative support should but the description into a registry. When the mode get instantiated the first time the supports should be put onto the mode. Otherwise registering a support will trigger creating the mode which leads to early extension activation. But nothing for January.

**Comment by alexandrudima** [comment]
@dbaeumer Moving this to Feb given the current workaround for Salsa.

**Comment by egamma** [comment]
@alexandrudima coolo, thanks

**Comment by dbaeumer** [comment]
Verified.
