### ISSUE TITLE
Feature Request: Keybind/Enable by default : Collapse All for find results

### ISSUE THREAD

**Issue by medic27** [Microsoft/vscode#22257]
Hi, I didn't see a setting or keybind for Collapsing all in search results so that only filenames are displayed. Would like to request this feature as a default as well as keybindable.

Thanks.

**Comment by roblourens** [comment]
I assume you've seen the button (next to the search results refresh button). Suggestions for a keybinding?

**Comment by medic27** [comment]
Hmmm, maybe "Cmd+]" to Collapse, "Cmd+[" to un-Collapse?
Reason I think it's useful is cuz when i'm searching, i usually don't care to parse thru the exact line that contains the keyword i'm searching for. I just want results that show the files that it's being used in and be able to access those files without defining which line i want to jump to.

**Comment by faktycznie** [comment]
A possibility to set 'Collapse all' option as default (in settings) would be very helpful :)

**Comment by vgsystems** [comment]
Yes! It would be very helpful !

**Comment by roblourens** [comment]
Note that anyone can set their own keybinding for the `search.action.collapseSearchResults` command

**Comment by roblourens** [comment]
The setting was implemented in https://github.com/Microsoft/vscode/pull/56438
