### ISSUE TITLE
When does JS DOC support the arrow function?

### ISSUE THREAD

**Issue by cjd6568358** [Microsoft/vscode#22264]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by demohi** [comment]
+1

**Comment by demohi** [comment]
* VSCode Version: 1.10.2

**Comment by mjbvz** [comment]
It is unclear to me what this issues is requesting. Generating JSDocs for arrow functions is already supported:

![mar-08-2017 21-38-10](https://cloud.githubusercontent.com/assets/12821956/23737376/90fb5378-0447-11e7-97c5-725705b41b52.gif)

If you are thinking of a different issue around jsdocs and arrow functions, please add some more information to this bug along with some example code.

Thanks

**Comment by cjd6568358** [comment]
@mjbvz 
it doesn't work like this:
class A{
 /**???
  b= async ()=>{}
}

thanks

**Comment by mjbvz** [comment]
We don't support the class properties proposal for JS yet, but, more generally, we are tracking support jsdocs of assignment type expressions here: https://github.com/Microsoft/TypeScript/issues/14134
