### ISSUE TITLE
preview to show multiple line but no \n kept as orginal code

### ISSUE THREAD

**Issue by andyysj** [Microsoft/vscode#22267]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.10.2|
|vim|vscodevim|0.6.2|;

---

Steps to Reproduce:

1. Push mouse on one multiple lines function name, the preview will show the contents
2. Check the contents you will find no \n as original code, all codes keep one line and wrap up.

**Comment by ramya-rao-a** [comment]
@andyysj Can you share a screenshot?

**Comment by andyysj** [comment]
Oh, I just found it is that Macro will not be previewed well if there are
multiple lines.

**Comment by ramya-rao-a** [comment]
So the issue is that while hovering on a function name whose declaration spans multiple likes, the preview does not have `\n` ?
And this is in a cpp file?

**Comment by sean-mcmanus** [comment]
It sounds like an issue with our cpptools extension on "hover". The macro definition is shows without new lines in the hover tooltip. The behavior is "by design" and matches Visual Studio behavior.

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-cpptools#544
