### ISSUE TITLE
Security - Scripts in Markdown files are executed when files are previewed

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#22268]
In versions prior to v1.10.2, scripts contained in script tags inside markdown files are executed when previewing the markdown file using <kbd>Cmd+Shift+P</kbd> > `Markdown: Open Preview` or `Markdown: Open Preview to the Side`.

If users preview markdown files they have not closely inspected, they are expose to any potential security risk posed by the scripts contained within the markdown file.

With version v.1.10.2, scripts are no longer executed by default. Users are informed if a markdown file contains scripts, and can decided if the preview should execute the scripts.

**Comment by xnnkmd** [comment]
@kieferrm Do you have a changeset reference ? I have run into some of the same concerns in another project, I would like to see how you solved it?

**Comment by dolmen** [comment]
@kieferrm Found it: 4ebfc2fc18ad1ca65b44f5c1c7c95ad347367beb
