### ISSUE TITLE
Unicode shade characters rendered too tall - overlapping lines

### ISSUE THREAD

**Issue by adamfk** [Microsoft/vscode#22262]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|Bookmarks|alefragnani|0.11.0|
|vscode-twig-pack|bajdzis|1.0.0|
|npm-intellisense|christian-kohler|1.2.1|
|docthis|joelday|0.3.11|
|cpptools|ms-vscode|0.10.1|
|debugger-for-chrome|msjsdiag|2.5.3|
|vscode-icons|robertohuertasm|7.2.0|
|nunjucks|ronnidc|0.2.3|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. Copy and paste the following text into vscode:
```
░
 ▒
  ▓
  
▒▒▒▒▒▒▒▒▒▒
▒ A BOX! ▒
▒▒▒▒▒▒▒▒▒▒
```
This is how it looks to me:
![image](https://cloud.githubusercontent.com/assets/274012/23730249/17a6c202-042c-11e7-8b6e-f8529bd41d83.png)

I would expect something like this (from Notepad++):
![image](https://cloud.githubusercontent.com/assets/274012/23730277/39505ae4-042c-11e7-85a2-d21f9ab39378.png)

This is my settings.json file:
```
{
    "window.zoomLevel": 0,
    "editor.tabSize": 2,
    "editor.useTabStops": false,
    "git.enabled": false,
    "workbench.iconTheme": "vscode-icons"
}
```

Here's a link to information on one of the shade characters: http://www.fileformat.info/info/unicode/char/2591/index.htm

The only work around I've found is changing the font to 'Courier New' which I can't stand or setting "editor.lineHeight": 26 which looks pretty silly.

P.S. Loving vscode!

**Comment by adamfk** [comment]
It appears to be a 'consolas' font issue, however, Word 2016 renders it well enough:
![image](https://cloud.githubusercontent.com/assets/274012/23730704/88b3b94e-042e-11e7-999d-dcf40df90025.png)

Also the font is listed as supporting those characters:
http://www.fileformat.info/info/unicode/char/2591/fontsupport.htm

**Comment by alexandrudima** [comment]
All font rendering is ultimately handled by Chromium. There are very few knobs we can turn on our side to influence it.

Please create or find an existing issue in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and link to it here.

**Comment by adamfk** [comment]
Chromium bug ticket: https://bugs.chromium.org/p/chromium/issues/detail?id=700036

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.

**Comment by adamfk** [comment]
I understand closing the issue.

My personal work around was to use a different font. `"editor.fontFamily": "'Source Code Pro', 'Courier New', monospace"`

Source Code Pro can be downloaded freely here: https://fonts.google.com/specimen/Source+Code+Pro
