### ISSUE TITLE
Editor screen very dimmed after update to 1.10.2

### ISSUE THREAD

**Issue by bohap** [Microsoft/vscode#22263]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.4.0-65-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-eslint|dbaeumer|1.2.7|
|tslint|eg2|0.8.1|
|vscode-icons|robertohuertasm|7.3.0|
|autoimport|steoates|1.2.2|;

After a update to version 1.10.2, main screen is very dimmed. See the difference between the same theme in sublime
![img](https://cloud.githubusercontent.com/assets/16247401/23731349/4d60d87e-046d-11e7-807d-6f06626944db.png)
I tried other themes and the same thing is happening

**Comment by aeschli** [comment]
There hasn't been any changes within VSCode. See the comparison with an older version:
![image](https://cloud.githubusercontent.com/assets/6461412/23740327/6378aed0-04a3-11e7-8fbc-a87596e120aa.png)

The difference to Sublime is caused by #9629.

**Comment by bohap** [comment]
@aeschli  I tried a older version and the same thing is happening. before it work fine. It looks like the main screen opacity is set to very low. I don't know how that happened. I tried removing all the settings, and reinstalling it again, but no help.  Do you have any idea of how to fix this problem?

**Comment by aeschli** [comment]
Does it maybe have to do with the font that is used? The actual font is provided from the operating system. Maybe something new got installed there? You can select a different for with "editor.fontFamily"

**Comment by bohap** [comment]
Changing the font family fixed the problem. Thanks
