### ISSUE TITLE
Add a shell selection prompt on Windows

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#22260]
To avoid issues users have been having with the new default PS and also enable easier selection of their preferred terminal I'm proposing that on Windows^ only we show a quick pick to select a terminal shell the first time they open the terminal:

1. ctrl+`
2. quick pick: Select shell (cmd, PS\*, WSL bash\*, Git bash\*)
3. User selects a shell and `terminal.integrated.shell.windows` is written to `settings.json`

Technically this would work by defaulting `terminal.integrated.shell.windows` to `null` on Windows and always show the quick pick when the value is null. That means pressing `ESC` to dismiss the quick pick will not launch a terminal.

There is the concern of more choice will detract from the lightweight feeling of the product but I believe it's worth the trade off in this case. It should be a very easy decision for the user, we can track feedback from Insiders.

*\* If present*
*^ The reason it's Windows only is because on Mac and Linux `$SHELL` will contain the correct shell in the vast majority of cases so no need to bug the user.*

/cc @daviwil @kieferrm

**Comment by Tyriar** [comment]
Here's how PowerShell is detected in the PS extension: https://github.com/PowerShell/vscode-powershell/blob/8f4a2bd72696c335ffa207ed93513927060c8f21/src/session.ts#L545

**Comment by Tyriar** [comment]
@weinand @dbaeumer FYI the plan is to make `terminal.integrated.shell.windows` `null` by default which will force a quick pick for the user. You may want to fallback to cmd.exe when it's `null` so the quick pick is avoided.

**Comment by dbaeumer** [comment]
Why can't we rely on ComSpec on Windows which should point to the right shell as well. It is the counterpart to $SHELL. I am actually not a big fan of prompting the user. If we want to provide UI then I think we should add an action 'Terminal: change used terminal' which users can trigger from the command palette to change the terminal without going through the settings.json file.

**Comment by Tyriar** [comment]
@dbaeumer comspec points to 32-bit cmd which introduces a bunch of problems. That's what it used to be and then it switched to hardcoded detection of 64-bit cmd then 64-bit powershell (since powershell.exe points at 32-bit version). I there was a real equivalent to `$SHELL` on Windows that actually had the correct bitness and the user's desired shell then this would not be a problem.

I get issues very frequently of people asking how to set cmd, wsl bash, git bash, etc. so this puts the decision right in front of them at the time they launch the terminal, which should be a very easy decision in most cases. I agree it's a slippery slope forcing a decision on the user like this, but the alternative is a terminal switcher button on the panel and that is a slippery slope as well, we're already up to 4 button with toggle maximize. I don't think just putting a command in the command palette will solve the problem for users as it will have similar discoverability issues as the settings.

From what I've got working so far it's a pretty nice experience imo. Good feedback though, I'm going to show it today to everyone in stand up and see what they think of the experience. Will do a post in the UX channel soon.

**Comment by Tyriar** [comment]
I guess an alternative we could think about is an info box that pops up on first launch that will trigger the change command. I'll bring this up today.

**Comment by Tyriar** [comment]
I asked for feedback on this on Twitter, you can see what it looks like and some of the responses here https://twitter.com/Tyriar/status/841812585506775040

**Comment by dbaeumer** [comment]
@Tyriar how will the flow work when a user starts the first task without every having the terminal open. Will he be prompted?

**Comment by Tyriar** [comment]
@dbaeumer I would recommend a fallback for consumers as mentioned in https://github.com/Microsoft/vscode/issues/22260#issuecomment-286590879

I'm beginning to be more fond of the message box idea though; instead of forcing them to choose before the terminal will work, the terminal will launch with the default (PS) and also give them a message box that allows them to open the quick pick. Seems to solve the problem too.

**Comment by dbaeumer** [comment]
Regarding a consumer implementing a fallback: I dislike that idea. I don't want to have any path knowledge in the consumer code. I currently use mergeDefaultShellPathAndArgs to get the default settings. Would that still work?

**Comment by Tyriar** [comment]
@dbaeumer I'll put together the alternative option soon with the message box to see how it looks, this may be pushed out to April.

FYI I exposed that method on the interface so you don't need that ugly casting https://github.com/Microsoft/vscode/commit/6f99f893199185169a4bec3881aea95ec70b1281

**Comment by dbaeumer** [comment]
@Tyriar thanks for the info.
