### ISSUE TITLE
Crash when backspace near double byte unicode character

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#2227]
In vscode/extensions/typescript/src/typescriptServiceClient.ts on the line 142 with the salsa unicode character.

- Insert a blank after salsa character (column 34)
- backspace, backspace

-> Code crashes

**Comment by alexandrudima** [comment]
@egamma Great find! I suspect it is a crash in oniguruma caused by us allowing for edits that cause invalid unicode points in multi-byte code points

**Comment by alexandrudima** [comment]
I don't get a crash anymore after atom/node-oniguruma#49
