### ISSUE TITLE
Add output specific setting for minimap

### ISSUE THREAD

**Issue by chanchancl** [Microsoft/vscode#22271]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|django-html|bibhasdn|1.2.0|
|django-snippets|bibhasdn|1.1.0|
|vscode-eslint|dbaeumer|1.2.7|
|python|donjayamanne|0.5.9|
|tslint|eg2|0.8.1|
|code-runner|formulahendry|0.6.13|
|beautify|HookyQR|0.8.9|
|PowerShell|ms-vscode|0.9.0|
|debugger-for-chrome|msjsdiag|2.6.0|
|java|redhat|0.0.11|
|vscode-icons|robertohuertasm|7.3.0|;

![qq 20170309134445](https://cloud.githubusercontent.com/assets/11457297/23737580/fe25eaa8-04ce-11e7-82a4-77bc26afbed1.png)

---

Steps to Reproduce:

1.Open the folder of vscode resource
2.There are some problems with minimap，as the picture shows
3.A part of the mini map appears in the console box.

**Comment by ramya-rao-a** [comment]
That's actually the minimap for the contents of the Output pane.

@alexandrudima Are we considering a setting to not show minimap in the output pane?

**Comment by alexandrudima** [comment]
fyi @isidorn

**Comment by isidorn** [comment]
We can add a setting or to consider if it should be off in the output.
Let's wait to get more feedback and then I can jump on this

**Comment by alexandrudima** [comment]
I think I've heard both requests, folks wanting it on and folks wanting it off...

**Comment by isidorn** [comment]
@alexandrudima than a setting seems like the right thing to do

**Comment by isidorn** [comment]
Using a language specific setting works for this case. Please add this to your setting

```json
"[Log]": {
    "editor.minimap.enabled": false
}
```

**Comment by chanchancl** [comment]
Thanks :)
