### ISSUE TITLE
No 32 bit linux repository

### ISSUE THREAD

**Issue by brendanddlc** [Microsoft/vscode#22278]
Ok so I'm not sure if I'm using the wrong value or if VSCode doesn't have a 32 bit repository but when I try to add the repo manually I get an error saying VSCode doesn't support the arch, I have tried it with (i386,i686,32,x86,32bit) none of these seem to work. Please add a 32 bit repo for people with coal powered PCs who want an easy and streamlined update procedure. BTW thanks for the great app VSCode is awesome!

- VSCode Version:Latest
- OS Version:Xubuntu 16.04

Steps to Reproduce:
Enter into terminal ->
`kk@kk-lpt:~$ sudo sh -c 'echo "deb **[arch=i386]** http://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

kk@kk-lpt:~$ sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://packages.microsoft.com/repos/vscode stable InRelease                             
Hit:3 http://download.mono-project.com/repo/debian wheezy InRelease                           
Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:6 http://archive.ubuntu.com/ubuntu xenial-security InRelease
Reading package lists... Done                     
**N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://packages.microsoft.com/repos/vscode stable InRelease' doesn't support architecture 'i386**'`

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/20790
