### ISSUE TITLE
Integrate Vorlon Desktop into vscode

### ISSUE THREAD

**Issue by jangajack** [Microsoft/vscode#22272]
Feature request: [Vorlon.js](http://www.vorlonjs.io/) is awesome and since it's a [Mircosoft open source](https://github.com/MicrosoftDX/Vorlonjs/) project and the Vorlon Desktop version is based on Electron I think it should be integrated as an additional debugging panel in vscode.

Also, Vorlon is not as well known as it should be and the current distribution of vscode would increase its adoption by people that aren't aware of it yet.

**Comment by isidorn** [comment]
Thanks for the suggestion. 
This should be done as an extension once we have opened viewlets to be contributable

fyi @weinand @chrisdias

**Comment by weinand** [comment]
Since I do not see a lot of activity in the Vorlon repository and since this feature request is not on our [radar](https://github.com/Microsoft/vscode/wiki/Roadmap) for the next 12 months I will close this.
Thanks for understanding and happy coding!
