### ISSUE TITLE
Setting "editor.wordWrapColumn" is ignored

### ISSUE THREAD

**Issue by moigagoo** [Microsoft/vscode#22273]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.15048
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.9|
|vscode-icon-theme|jtlowe|1.5.0|
|nim|kosz78|0.5.19|
|Go|lukehoban|0.6.55|
|vscode-docker|PeterJausovec|0.0.12|
|debug|webfreak|0.17.0|
|jinja|wholroyd|0.0.7|;

---

Steps to Reproduce:

1. Set "editor.wordWrap" to "bounded."
2. Set "editor.wordWrapColumn" to "79."
3. Observe that content is wrapped on viewport width in all cases.

**Comment by moigagoo** [comment]
UPD: It's only ignored in .md files, weirdly.

**Comment by alexandrudima** [comment]
The reason for that is that we ship with language specific settings for markdown. i.e. our defaults look like this:

```
  "editor.wordWrap": "off",
  "editor.wordWrapColumn": 80,
  "[markdown]": {
    "editor.wordWrap": "on",
    "editor.quickSuggestions": false
  },
```

@sandy081 I think this is a usability issue problem with the language specific settings. I have also created #22282

**Comment by moigagoo** [comment]
@alexandrudima Thanks for the tip! I had no idea about markdown-specific settings.

**Comment by sandy081** [comment]
Yeah, this is more specifically due to default language specific settings. Now extensions can contribute language specific settings without knowing to users. This is same with Editor config extension. I think we need a way for user to know what settings are being applied to the current editor and where are they coming from. Created the following issue for this - https://github.com/Microsoft/vscode/issues/22283

**Comment by sandy081** [comment]
Duplicates #22283

**Comment by sandy081** [comment]
I am closing this in favour of the feature request #22283 that helps to give information to the user about the editor settings. Please add your opinions or ideas there or reopen this if not agreed and I am open to feedback here.

Thanks.
