### ISSUE TITLE
Test tour: MERN starter kit

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#22277]
[Test Tours/Exploratory Testing](https://msdn.microsoft.com/en-us/library/jj620911(v=vs.120).aspx#bkmk_tours). We will use a starter kit and use it for a 'GuideBook Tour'. The final goal would be to show a cool demo of how you can use VS Code to do MEARN.

You have discovered the MERN starter kit http://mern.io/ and want to get started with it using Code

- do you get the extension recommendations (e.g. eslint)?
- set it up for development. 
  - setup debugging
  - setup tasks if applicable
  - eslint is already setup, check the linting behaviour when using the vscode-eslint extension.
  - check Intellisense behaviour
- start implement something fun
- are there additional JSON schemas that should be defined/used to simplify development
- check that all artifacts/file types have syntax coloring
- think of demo of some of the VS Code goodness

Link issues you discover to this issue.
Share findings in this issue.

**Comment by egamma** [comment]
Related issues:
-  #22378 Debugger setup tuning for using VS Code with the mearn.io starter kit debug
- #23317 No IntelliSense for Express in MERN starter kit

**Comment by michelkaporin** [comment]
### Extensions required to use MERN fully with VS Code
**Tasks**: npm support,
**Linting**: ESLint
**Chrome Debug**: Debugger for Chrome

### Report
- Extension recommendations include both of the extensions, however they are not at the top of the recommendation list. Maybe this can be improved?
- eslint linting behaviour works well, no problems found with it. ✔️ 
- Intellisense works fine. ✔️ 
- No additional JSON schemas needs to be defined to simplify development, as to my mind. ✔️ 
- Syntax colouring. ✔️ 

### Some configuration examples
- tasks.json can be setup with 'npm support' module and tasks work fine for test, watch and lint commands. Example:
```
{
    "taskName": "lint",
    "args": ["run", "lint"]
}
```
- Chrome debug can be setup the following way:
```
{
    "name": "Launch localhost", 
    "type": "chrome",
    "request": "launch",
    "url": "http://localhost:8000",
    "webRoot": "${workspaceRoot}",
    "sourceMapPathOverrides": {
        "webpack:///*": "${webRoot}/*"
    }
},
{
    "name": "Attach localhost",
    "type": "chrome",
    "request": "attach",
    "port": 9222,
    "url": "http://localhost:8000",
    "sourceMaps": true,
    "webRoot": "${workspaceRoot}",
    "sourceMapPathOverrides": {
        "webpack:///*": "${webRoot}/*"
    }
}
```

**Comment by waderyan** [comment]
* https://github.com/Microsoft/vscode/issues/24255 - Debugger breaks inappropriately

**Comment by weinand** [comment]
A first cut of a "MERN Recipe" is available here: https://github.com/weinand/vscode-recipes/tree/master/MERN-Starter
