### ISSUE TITLE
Incomplete link in console

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/vscode#22274]
- VSCode Version: Version 1.10.2 (1.10.2)
- OS Version: OS X 10.11.6

For a failing test, the link generated for file path in console is incomplete and doesn't resolve.

See screenshot: 
<img width="562" alt="screen shot 2017-03-09 at 08 37 04" src="https://cloud.githubusercontent.com/assets/372735/23740466/f9ecbbfe-04a3-11e7-8f2c-13281d7251ae.png">

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/21182
