### ISSUE TITLE
Make find widget resizeable

### ISSUE THREAD

**Issue by lopezpa79** [Microsoft/vscode#22270]
- VSCode Version: 1.10.2
- OS Version: Windows 8

Please can I request a larger search box or search area so that it is easy to type longer search criteria.

**Comment by sandy081** [comment]
@lopezpa79 Is it the Search box in Search viewlet or in Editor find widget?

**Comment by lopezpa79** [comment]
Mainly the Editor Find Widget, as I usually work with single files.

The Search box in the viewlet I can expand the panel to view more, but at the expense of the editor window viewing area.

Would be useful if it could be a re-sizeable floating "find" / "find in files" window that could be docked on any side (top/bottom/left/right).

**Comment by catlan** [comment]
I was looking for a setting to change the editor find widget style to the one in the settings editor. I prefer the search bar style which spans across the editor width. 

editor find widget:
<img width="490" alt="editor find widget" src="https://cloud.githubusercontent.com/assets/45803/24585185/8d9b6c86-1784-11e7-8523-c5bb69fac81c.png">

search in the settings editor:
<img width="498" alt="settings editor search bar" src="https://cloud.githubusercontent.com/assets/45803/24585189/b2a362e0-1784-11e7-913b-633455b2ec11.png">

**Comment by MichaelRBond** [comment]
Also, be able to move it to the bottom of the screen, like in Atom, Sublime, emacs, etc ...

**Comment by lopezpa79** [comment]
Just found another request with the same details: #20447

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/2657 and work on it in May. Thanks for your input!
