### ISSUE TITLE
Feature Request: Explorer should support custom order of folders/files

### ISSUE THREAD

**Issue by kmolerov** [Microsoft/vscode#22281]
It will be very useful to be able to reorder folders/files in explorer with drag&drop. In my project I am ordering my folders based on significance, so it is easier to find them, instead of searching for it based on name order.
View order could be stored in some dedicated project file view-order.json 
{name: 'folder-name', viewOrder: 1}. Hierarchy in file is not needed, as order is done per-node.
Folders/files which does not have view order entry should be ordered by name with lower priority than the once that have.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by kmolerov** [comment]
I didn't find any old issue that has something to do with custom view order of folders. This is very needed functionality for me. 
I don't think that it should be closed!
