### ISSUE TITLE
Test localization Support

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2228]
- [x] Linux @aeschli 
- [x] MaxOS @bpasero
- [x] Windows @isidorn

The January drop ships with localization support for the main, the renderer, the service (search app, shared service, ...) and the extension host processes. Also pseudo localization is supported. Test the following:

## Pseudo localization

- start VSCode from a command line with the argument --locale=pseudo
- verify that all strings in the UI are enclose in [ ] and that vowels are doubled. The UI should look something like this:

![capture](https://cloud.githubusercontent.com/assets/1931590/12552337/8e0f594c-c371-11e5-8e11-8cafa7eefcd5.png)

### Import new strings into the translation database

- build VSCode locally (e.g. execute gulp vscode-win32). Assume that VSCode got built into p:\mseng\vscode\VSCode-win32
- clone the VSO git repository mshttps://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization
- cd to the MonacoLocalization directory and run npm install
- cd to lib, run npm install and cd to parent
- make sure you have gulp install globally
- run gulp import --component vscode/src --locData ${vscode-build}\resources\app\out\nls.metadata.json where ${vscode-build} is the folder vscode got built into (e.g. p:\mseng\vscode\VSCode-win32)
- ensure that some lcg and lci files got modified and added. Compare some of them. Modified files should contain new strings introduced lately, new files correspond to new files introduced lately.

### Export bundles from the translation database

- from the MonacoLocalization directory execute gulp export --component vscode/src --locData ${vscode-build}\resources\app\out\nls.metadata.json --dest ${vscode-build}\resources\app\out
- ensure that ${vscode-build}\resources\app\out\vs\workbench contains files like workbench.main.nls.de.js

## Translated Version

- start the VSCode version you have built above with --locale=de
- ensure that parts of the UI is in German (parts of the UI is still English because we are mssing the corresponding translations from the translation team)
- switch your OS locale to German and start VSCode without the --locale command line parameter. Ensure that the UI is partly German
- start VSCode with --locale=de-DE. Ensure that the UI is German as well.

![capture](https://cloud.githubusercontent.com/assets/1931590/12553067/9819c4a0-c375-11e5-8657-6d45b50579)

**Comment by isidorn** [comment]
Could not change my win locale no matter what I tried - i believe my win10 internal version might not support it. 
Eveything else looks good, and Dirk tested the win10 in german so checking off.

**Comment by aeschli** [comment]
Alle Schritte auf Linux getestet. Läuft wie geschmiert!

**Comment by bpasero** [comment]
Works, but found https://github.com/Microsoft/vscode/issues/2495
