### ISSUE TITLE
Format document action is not working properly with objects in functions parameters

### ISSUE THREAD

**Issue by micnic** [Microsoft/vscode#22285]
Format document action is not working properly when providing multiple objects as parameters to javascript functions.

- VSCode Version: 1.10.2
- OS Version: Linux Ubuntu 16.04 and Windows 10 tested

Steps to Reproduce:

1. Write the following lines in a `.js` file:
```js
someRandomFunction({
    prop1: 1,
    prop2: 2
}, {
    prop3: 3,
    prop4: 4
}, {
    prop5: 5,
    prop6: 6
});
```
2. Press the format document editor action keys (Ctrl + Shift + I)

3. See the following result:
```js
someRandomFunction({
    prop1: 1,
    prop2: 2
}, {
        prop3: 3,
        prop4: 4
    }, {
        prop5: 5,
        prop6: 6
    });
```

Expected result would be to keep the indentation of the objects.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14589
