### ISSUE TITLE
Save All should save existing files even when an unsaved file is currently open

### ISSUE THREAD

**Issue by NiekPas** [Microsoft/vscode#22297]
**Feature request**

- VSCode Version: 1.10.2
- OS Version: Windows 10 Home 1607

Steps to Reproduce:

1. Open an existing file
2. Make a change to said file
3. Create a new file (CTRL+N)
4. Make a change to the newly created file
5. Save all (CTRL+K S by default)

Expected behavior: the changes to the previously existing file are saved, and a 'Save As' dialog opens asking where to save the newly created file.

Actual behavior: as above, but the changes to the previously existing file are **not** saved.

**Comment by chrmarti** [comment]
@NiekPas I cannot reproduce the problem with 1.10.2 nor the latest insiders build on Windows 10. Is there anything specific about your setup or the files? Does the console in the dev tools (Help > Toggle Developer Tools) show any errors? (Back to you @bpasero)

**Comment by bpasero** [comment]
@NiekPas ping

**Comment by NiekPas** [comment]
@bpasero Oddly, I cannot reproduce the bug any longer either, neither on VS Code 1.10.2 nor on 1.11.1. Very strange.
