### ISSUE TITLE
Typescript and Javascript indentation problems

### ISSUE THREAD

**Issue by ofabricio** [Microsoft/vscode#22295]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|EditorConfig|EditorConfig|0.6.0|
|autoimport|steoates|1.2.2|
|Angular2|UVBrain|0.4.1|;

---

Steps to Reproduce:

I made a gif to illustrate:

![hi](https://cloud.githubusercontent.com/assets/1385704/23751550/a7ef8504-04b0-11e7-8b51-9ceab7d83b20.gif)

Notice how `C` parameter and `.do` method are not correctly indented after format document depending on `.mergeMap` position.

It happens either in Typescript or Javascript syntax.

It seems a bug. People in gitter/vscode agreed, so I opened this issue.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14586
