### ISSUE TITLE
cannot conitinue？

### ISSUE THREAD

**Issue by wukongtea** [Microsoft/vscode#22299]
in vscode, the code cant conitinue.
![image](https://cloud.githubusercontent.com/assets/25115961/23753569/f7ff3a80-0514-11e7-906d-5b6c69beba38.png)
in cmd ,it can work.
![image](https://cloud.githubusercontent.com/assets/25115961/23753612/19771f34-0515-11e7-8503-7817907ae698.png)

**Comment by ramya-rao-a** [comment]
We need more details. Do you see any error in the VS Code window or the debug console?
What version of VS Code are you using?

**Comment by isidorn** [comment]
Can you also share your `launch.json`?
When you say can't continue are you debugging and clicking on the continue action and nothing is happening?

**Comment by wukongtea** [comment]
Nothing happened in the debug console,VS code version is 1.10. Python 3.6.
The code in CMD model is well applied. 
![image](https://cloud.githubusercontent.com/assets/25115961/23788826/3f588fdc-05b3-11e7-862d-8c2def17a491.png)

**Comment by isidorn** [comment]
Please file this to the vscode pythong extension here please
https://github.com/DonJayamanne/pythonVSCode
