### ISSUE TITLE
The resource manager didn't update folers and files by git checkout <branch>

### ISSUE THREAD

**Issue by motopia** [Microsoft/vscode#22290]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ejs-language-support|QassimFarid|0.0.1|;

---

Steps to Reproduce:

1.terminal :git checkout branch
2.The resource manager didn't update folers and files

**Comment by ramya-rao-a** [comment]
What do you mean by resource manager in this context?
