### ISSUE TITLE
Initializing JS/TS language features never over

### ISSUE THREAD

**Issue by machaos2** [microsoft/vscode#222965]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91.1
- OS Version: Windows_NT x64 10.0.19045

other infomation:
Version: 1.91.1 (user setup)
Submission: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2022-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. When I open the project, the JS/TS language function is constantly initialized, and the related code prompt function cannot be used properly
2. ![f60ba0a2695b4ceb964f7035d75634f](https://github.com/user-attachments/assets/b09f4eb8-4886-45f8-9169-5bc0c4a9a2cd)
3. When I rolled back the VSCode version to 1.89.1, this feature worked properly

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
