### ISSUE TITLE
VSCode stages the wrong content

### ISSUE THREAD

**Issue by javahaxxor** [Microsoft/vscode#22294]
staging a changed but unsaved file stages the old contents of the file.
VSCode should probably autosave the changes and THEN stage

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 3.16.0-4-amd64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|indenticator|SirTori|0.2.1|
|html-css-class-completion|Zignd|1.0.3|
|vscode-eslint|dbaeumer|1.2.7|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.0.33|
|backbone-js-snippets|ioanaapetrei|0.0.1|
|debugger-for-chrome|msjsdiag|2.6.0|
|better-merge|pprice|0.5.1|
|diff|rafaelmaiolla|0.0.1|
|stylelint|shinnn|0.23.0|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. change a file, do not save
2. stage file
3. examine changes in staged file - changes do not match what's in the editor

**Comment by joaomoreno** [comment]
Tricky. Not sure if people really expect this to happen automatically.

**Comment by javahaxxor** [comment]
Yea it's a bit tricky.. I might be alone, but I expect what I see to be staged. Maybe a pop-up warning that the editor content hasn't been saved, and something else will actually be staged? That would probably be even better

**Comment by javahaxxor** [comment]
Autosave might not be a good idea. I just had a colleague wipe out a couple of days work, and if VSCode would have kept the editor contents I would have been saved. So probably a warning that the editor contents do not match the saved version would be the way to go

**Comment by joaomoreno** [comment]
Not going to go with anything here.
