### ISSUE TITLE
Improve find counter UI

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2229]
Just so we track it:

- give less contrast to the red in dark theme
- don't use monospace, since we don't use it anywhere else other than actual code in the product

![image](https://cloud.githubusercontent.com/assets/22350/12552726/d1233f58-c373-11e5-8c80-92ec5dcf7132.png)

ping @bgashler1

**Comment by alexandrudima** [comment]
Thanks! Hope you like it more now:

![image](https://cloud.githubusercontent.com/assets/5047891/12563177/91cc7f7a-c3b1-11e5-8dbf-ec0626c38a4d.png)

**Comment by joaomoreno** [comment]
:+1:
