### ISSUE TITLE
Test URL handling for settings

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#223027]
Refs: https://github.com/microsoft/vscode/issues/212079

- [x] macOS @justschen
- [x] linux @joshspicer
- [x] windows @lszomoru

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23223027%0A%0A&assignees=alexr00)

---

## Test just the URL

VS Code now has url handling for settings URLs and opening the settings editor to the specified setting. This is the format:
```
vscode-insiders://settings/<setting id>
```
Example
```
`vscode-insiders://settings/files.autoSave`
```

1. Verify that these settings URLs work as you'd expect. 
2. Verify that anything extra you add on to the end of the URL isn't used.

## Test settings URLs in the release notes

In the release notes, you can specify a value for the setting using a VS Code specific `codesetting` property. When we render the release notes, we do special rendering for links like this that lets the setting be configured directly from the release notes. Example

```
### Editor Sticky Scroll

This iteration we're enabling Sticky Scroll in the editor by default. You can change this using the setting <a href="vscode://settings/editor.stickyScroll.enabled" codesetting="true">`editor.stickyScroll.enabled`</a>.
```

1. Test that you can add links like this to the release notes and that they work the way you'd expect. You can render markdown as release notes using the command "Developer: Open Current File as Release Notes".
2. Verify that adding a link like this looks and works fine in the browser. They should just show as a regular link, and they should work as above when you tested just the URL.

**Comment by justschen** [comment]
works well! 

I wonder if there's something special we can do to indicate that it's clickable? There's the icon but it might not be immediately understood that it's something you can click.
