### ISSUE TITLE
.editorconfig.end_of_line, and previewing files with conflicting eol's, auto modifies file on preview

### ISSUE THREAD

**Issue by papercuptech** [Microsoft/vscode#22307]
- VSCode Version: 1.10
- OS Version: Win 10

Steps to Reproduce:

1. Create/find file known to have `crlf` eol's
2. Create `.editorconfig` with `end_of_line = lf`
3. Single-click filename to preview
4. File is opened, and then instantly modified automatically

This issue occurs, for example, when on Windows and using `git` to clone a repo from github, which will convert line endings on-the-file to match destination O/S eol preference. If the repo also has an `.editorconfig` with an `eol_of_line` in conflict with O/S preference, the issue becomes prevalent.

Double-clicking a filename will open a dedicated editor tab, but does not automatically modify line endings. File previewing should work the same in that the file is not automatically modified.

**Comment by alexandrudima** [comment]
@papercuptech Perhaps you can log this issue against the editor config extension -- https://github.com/editorconfig/editorconfig-vscode

**Comment by papercuptech** [comment]
For others arriving here, see [https://github.com/editorconfig/editorconfig-vscode/pull/116](https://github.com/editorconfig/editorconfig-vscode/pull/116)
