### ISSUE TITLE
CommentController.activeCommentThread not updated when navigating from ruler or Comments panel

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#223021]
CommentThread.reveal() and clicking into the comment triggers an update of CommentController.activeCommentThread, but it doesn't update when I expand a comment from the left editor ruler or the Comments panel.

**Comment by meganrogge** [comment]
Generated some copilot review comments, clicked them in the panel, and they were navigated to, so marking as verified. @alexr00 lmk if I'm misunderstanding the steps. 
 

https://github.com/user-attachments/assets/5c4b04d0-5753-4b03-ab7a-facdb65c6566

**Comment by chrmarti** [comment]
Clicking from the panel works. Clicking in the left editor gutter still doesn't. I'll open a new issue.
