### ISSUE TITLE
Terminal not opening closed automatically

### ISSUE THREAD

**Issue by gsivaprabu** [Microsoft/vscode#22302]
Terminal not opening closed automatically

**NodeJS Installed Path:-** 
C:\Program Files\nodejs

**Git Installed Path:-**
C:\Program Files\Git

**Code installed path**
C:\Program Files (x86)\Microsoft VS Code

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.2.9200
- Extensions: none
---

Steps to Reproduce:

1.
2.

FYI:-

![image](https://cloud.githubusercontent.com/assets/2444608/23756601/33dface8-050a-11e7-866f-8069f6feb2c3.png)

**Comment by Tyriar** [comment]
Do you have any settings in your settings.json?

**Comment by gsivaprabu** [comment]
In My Settings :- 

![image](https://cloud.githubusercontent.com/assets/2444608/23782972/2154a6fe-057e-11e7-8cfe-2d9857081813.png)

**Comment by gsivaprabu** [comment]
Hi @Tyriar 

My doubt is because of this error only i am not able to run the terminal , How to fix the below issue

![image](https://cloud.githubusercontent.com/assets/2444608/23783034/7cf7084e-057e-11e7-8d60-e7508821d3e5.png)

**Comment by ramkumarganapathi** [comment]
Hi @Tyriar @ramya-rao-a 

I have solved the issue because the Windows environment variable wrongly given.

FYI:

How to change the environment variable


![](https://i.stack.imgur.com/WhMP8.jpg)


Please close the issue,
Thanks for your support

**Comment by gsivaprabu** [comment]
Hi @Tyriar @ramya-rao-a 

I have solved the issue because the Windows environment variable wrongly given.

FYI:

How to change the environment variable


![](https://i.stack.imgur.com/WhMP8.jpg)


Please close the issue,
Thanks for your support

**Comment by Tyriar** [comment]
@gsivaprabu do you know what in the environment in particular caused the problem (for future reference)?

**Comment by gsivaprabu** [comment]
@Tyriar  NodeJS path mentioned wrongly in  Windows environment variable
