### ISSUE TITLE
include file not found in include path 

### ISSUE THREAD

**Issue by Eraldoosantos** [Microsoft/vscode#22309]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.2|;

---

Hello, I've had some problems when I was programming in C language. So, everytime when I put the headers (includes) appeared this: "include file not found in include path". How can I fix this? The GCC compiler is installed in my computer. Ah, I'm using Windows 10 pro version. Could you solve this for me? I'm waiting for your answer.

Thanks for all =]

**Comment by sean-mcmanus** [comment]
The location for C++ extension issues is: https://github.com/Microsoft/vscode-cpptools/issues .

You should click the yellow lightbulb to add your include path to the includePath setting in c_cpp_properties.json.

**Comment by ramya-rao-a** [comment]
Please log C++ extension issues at https://github.com/Microsoft/vscode-cpptools/issues .

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-cpptools#545
