### ISSUE TITLE
Switch language issue

### ISSUE THREAD

**Issue by lego963** [microsoft/vscode#223006]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.1
- OS Version: ubuntu 24.04/22.04

Steps to Reproduce:

1. ALT+SHIFT

ALT+SHIFT changes language but it selects `File` button and I can't continue typing. If i switch language with SHIFT+ALT it's ok

PS:
I can swith language with this combination, because I use tweaks tool

**Comment by andreamah** [comment]
Hmm, it keeps focus for me.  If you open `Preferences: Open Keyboard Shortcuts (JSON)`, do you have any non-default keyboard shortcuts set? You can also troubleshoot keyboard shortcuts using this guide and perhaps find what is causing it to not focus
https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings

**Comment by lego963** [comment]
@andreamah I didn't set any other keyboard shortcuts
![image](https://github.com/user-attachments/assets/9674e451-e8f3-4662-9f98-9e97cabfc794)

**Comment by bpasero** [comment]
Does it reproduce with custom menu?

**Comment by TylerLeonhardt** [comment]
I think @benibenj owns this stuff now over @sbatten
