### ISSUE TITLE
Terminal display bug

### ISSUE THREAD

**Issue by runfan** [Microsoft/vscode#22301]
- VSCode Version:1.10.2
- OS Version:windows 10

Steps to Reproduce:

1.ctrl + `  open terminal
2.Terminal display error like bottom

``` shell
版权所有 (C) 2016 Microsoft Corporation。保留所有权利。
                                                                                                                 PS E:\小工具
>


```

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/21594
