### ISSUE TITLE
Intellisense: full documentation

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2230]
- [x] win @alexandrudima 
- [x] mac @egamma 
- [x] linux @bpasero

Intellisense now gives you the chance to see the full documentation of its items.

![image](https://cloud.githubusercontent.com/assets/22350/12553367/4b9fb542-c377-11e5-81cc-1f5a46802446.png)

It can be reached by clicking the blue **i** icon at the right of the suggestion or by pressing the intellisense keybinding once again <kbd>Ctrl-Space</kbd>.

![image](https://cloud.githubusercontent.com/assets/22350/12553382/5c630c76-c377-11e5-9e62-a359481cdd7c.png)

**Comment by alexandrudima** [comment]
@joaomoreno Nice job!

**Comment by csinco** [comment]
@joaomoreno cool stuff, but is the info icon the right UI affordance for this?  I feel like you could just have blue text that says "More".  My two cents.

FYI @bgashler1 @stevencl

**Comment by alexandrudima** [comment]
:+1: for something more like "more" ;)
