### ISSUE TITLE
Noticeable pause when entering doc comments

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#22304]
See attached screen capture and notice the pause between deleting the stub and inserting the completion. We should go for an atomic edit.

![mar-09-2017 16-31-11](https://cloud.githubusercontent.com/assets/1794099/23758168/251fa576-04e9-11e7-88ef-62f74406ce1f.gif)

**Comment by mjbvz** [comment]
Depends on https://github.com/Microsoft/TypeScript/issues/24468

**Comment by mjbvz** [comment]
Fixed by d5bd9803bddfc85ae5f2e473abd78f7fe0cd8713
