### ISSUE TITLE
Debug Console opens automatically even when disabled

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode#223053]
Type: <b>Bug</b>

(this issue is reproducible in VSCode stable as well as insiders)

1) Hide "Debug Console" in panel
2) Run Debug (console doesn't show up)
3) Reload window
4) Run Debug again (console shows up)
5) Show and hide "Debug Console" in panel again
6) Run Debug (console doesn't show up)

In other words, hiding Debug Console is only respected until window reload, after a reload it will show up automatically again when running debug.

VS Code version: Code - Insiders 1.92.0-insider (65a6a2f783dbc87fb3b1408c6a9b3e8d455a60a2, 2024-07-18T05:04:30.247Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.14.0-435.el9.x86_64
Remote OS version: Linux x64 5.14.0-435.el9.x86_64
Remote OS version: Linux x64 5.14.0-435.el9.x86_64
Connection to 'ssh-remote+7b22686f73744e616d65223a2243564c5f4d6564766564227d' could not be established
Remote OS version: Linux x64 5.14.0-435.el9.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (2.26GB free)|
|Process Argv|--crash-reporter-id 1ec82b55-0019-4497-ac0d-5453a1fdb689|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: NewBallz|
|OS|Linux x64 5.14.0-435.el9.x86_64|
|CPUs|Genuine Intel(R) 0000 (120 x 1900)|
|Memory (System)|251.16GB (238.86GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: NewBallz|
|OS|Linux x64 5.14.0-435.el9.x86_64|
|CPUs|Genuine Intel(R) 0000 (120 x 1900)|
|Memory (System)|251.16GB (238.86GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: NewBallz|
|OS|Linux x64 5.14.0-435.el9.x86_64|
|CPUs|Genuine Intel(R) 0000 (120 x 1900)|
|Memory (System)|251.16GB (238.86GB free)|
|VM|0%|

Connection to 'ssh-remote+7b22686f73744e616d65223a2243564c5f4d6564766564227d' could not be established

|Item|Value|
|---|---|
|Remote|SSH: NewBallz|
|OS|Linux x64 5.14.0-435.el9.x86_64|
|CPUs|Genuine Intel(R) 0000 (120 x 3909)|
|Memory (System)|251.16GB (238.86GB free)|
|VM|0%|
</details><details><summary>Extensions (90)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.5.0
project-manager|ale|12.8.0
myst-tml-syntax|chr|0.1.3
systemd-unit-file|coo|1.0.6
vscode-systemd-support|han|2.2.0
golang-snippets|hon|1.2.0
output-colorizer|IBM|0.1.2
vscode-todo-highlight|jgc|2.0.8
vsc-python-indent|Kev|1.18.0
dotenv|mik|1.0.1
meson-build|Mrm|0.2.1
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.113.2024071915
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
azure-repos|ms-|0.39.2024061901
remote-explorer|ms-|0.5.2024070409
remote-repositories|ms-|0.41.2024022202
diff|raf|0.0.1
rewrap|stk|1.16.3
errorlens|use|3.20.0
vscode-icons|vsc|12.8.0
calculate|aca|2.1.0
project-manager|ale|12.8.0
markdown-preview-github-styles|bie|2.0.4
gitignore|cod|0.9.0
doxdocgen|csc|1.4.0
macros|ctf|1.1.0
vscode-markdownlint|Dav|0.55.0
githistory|don|0.6.20
gitlens|eam|15.2.0
EditorConfig|Edi|0.16.4
vscode-git-history|fab|3.1.0
copilot|Git|1.214.997
copilot-chat|Git|0.18.2024072201
vscode-pull-request-github|Git|0.93.2024072204
go|gol|0.42.0
gc-excelviewer|Gra|4.2.59
todo-tree|Gru|0.0.226
triggertaskonsave|Gru|0.2.17
vscode-systemd-support|han|2.2.0
rest-client|hum|0.25.1
auto-comment-blocks|kev|1.0.1
vsc-python-indent|Kev|1.18.0
restructuredtext|lex|190.4.1
vsls-whiteboard|los|0.0.12
add-to-gitignore|mac|1.0.0
rainbow-csv|mec|3.12.0
gitexplorer|mfe|1.0.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.1
vscode-dotnet-runtime|ms-|2.1.1
autopep8|ms-|2024.1.11501016
debugpy|ms-|2024.9.12011011
isort|ms-|2023.13.11511010
pylint|ms-|2023.11.13481007
python|ms-|2024.11.2024072201
vscode-pylance|ms-|2024.7.100
jupyter|ms-|2024.6.2024070901
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
references-view|ms-|0.0.89
vsliveshare|ms-|1.0.5936
vsliveshare-pack|ms-|0.4.0
python-docs|Muk|0.8.3
gremlins|nho|0.26.0
pokowaka-iwyu|pok|1.0.3
vscode-commons|red|0.0.6
vscode-yaml|red|1.15.0
bash-debug|rog|0.3.9
rust-analyzer|rus|0.4.2044
partial-diff|ryu|1.4.3
bracket-jumper|sas|1.1.8
markdown-preview-enhanced|shd|0.8.13
git-autoconfig|shy|0.0.2
rewrap|stk|1.16.3
esbonio|swy|0.95.0
simple-rest-client|Tin|1.4.2
simple-rst|tro|1.5.4
errorlens|use|3.20.0
vscode-lldb|vad|1.10.0
clang-format|xav|1.9.0
save-as-root|yy0|1.8.0
markdown-all-in-one|yzh|3.6.2
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialogc:30812479
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
bdiig495:31013172
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
nb_pri_only:31057983
nativerepl1:31093711
refactort:31084545
pythonrstrctxt:31093868
0c838689:31088353
1iic9185:31091668
flighttreat:31100343

```

</details>

**Comment by ArturoDent** [comment]
When you restart you are starting a new `session` so that the setting:

    Debug: Internal Console Options

if set to `OpenOnFirstSessionStart` should open the Debug Console even if it is disabled.  You may want to consider the other options for that setting.

Note: I see that the context menu for hiding the Debug COnsole isn't updated on the forced open on session starts and still shows the Debug Console unchecked even if it is showing.

**Comment by anatolyburakov** [comment]
That sounds like a very odd design choice. If I disable the Debug Console, I expect it to not show up. It is not obvious that there's another setting that controls it that does not respect my toolbar setting. I wonder if this could be improved.

**Comment by roblourens** [comment]
@anatolyburakov you're not disabling the debug console when you hide the view. You're just setting it to be hidden by default. Easy to imagine that someone might want it hidden normally but then it should still appear when they start debugging.
