### ISSUE TITLE
Feature Request - File open and save as

### ISSUE THREAD

**Issue by G4143** [Microsoft/vscode#22308]
Why do we, by default, have to open a new file and then save the file with a name. Won't it make sense to have a feature where you could choose a new file and save as in one step? I never understood why editors never offered a choice to create new file and save as in one step? Maybe its just me but it makes sense to do this in one step instead of two.

**Comment by ramya-rao-a** [comment]
cc @chrmarti

**Comment by bpasero** [comment]
![panel-red](https://cloud.githubusercontent.com/assets/900690/23782997/8f25ab2c-0558-11e7-915e-2fb543b31248.gif)
