### ISSUE TITLE
Hover on editors which have `overflowWidgetsDomNode` set

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#223085]
Ref: https://github.com/microsoft/vscode/issues/212101

- [x] anyOS @paulacamargo25
- [x] anyOS @sandy081

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23223085%0A%0A&assignees=aiday-mar)

---

A couple of iterations back, it has been noticed that it is not possible to hover on the editor hover inside of editors that have the `overflowWidgetsDomNode` field set to some node. This node is set when we want to allow the content and overlay widgets to overflow out of the editor. In this case the content and overlay widget nodes are added into the `overflowWidgetsDomNode` which is a sibling (not a child) to the editor dom node. Examples of editors where the `overflowWidgetsDomNode` is set are: code blocks inside of the panel chat, the multi-diff editor, the SCM commit input box. In all of these, when you make an editor hover appear and move your mouse towards the hover, it disappears before the user is able to place their mouse on the hover. We would like to test that the fix that we have developed solves this issue as expected. To test please do the following:

1. Open an editor that has the `overflowWidgetsDomNode` field set within VS Code (see examples above for such editors).
2. Make an editor hover appear 
3. Move your mouse towards the hover. Check that you can place the mouse on top of the hover.
4. Move the mouse out of the hover. Move the mouse about on top of other editors/areas of VS Code
5. Verify that after this, you can still make a hover appear in the same editor, and are able to place your mouse on it.
6. Repeat this with different mouse movement speeds and editors.

cc @hediet

**Comment by sandy081** [comment]
@aiday-mar 

> Make an editor hover appear

It would be helpful if you can provide one example with steps for how to get such an editor hover appear.

**Comment by aiday-mar** [comment]
Yes, in the panel chat for example, you can first make a code block appear, by typing an instruction like `output the recursive fibbonnacci function`. The code block that appears is an editor. Now hover on some token inside of the code block and the editor hover should appear.

For the SCM view, you can download the extension `Code Spell Checker` from the marketplace with the ID: streetsidesoftware.code-spell-checker. With this extension, you can write a series of characters in the SCM input box that do not make sense. A blue squiggle should appear under the commit message which you can hover on to make the editor hover appear.

For the multi-diff editor, it is sufficient to just open a PR and look at the changes in a multi-diff editor. Then you can hover on any token inside of the editor to make the editor hover appear.
