### ISSUE TITLE
Add `type` property for `preLaunchTask`

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#223081]
Idea from @alexr00:

In order to reduce the number of activations, we could add a `type` property to the `preLaunchTask` so that we know which extensions, if any, to activate when a user starts debugging and don't have to activate all of them. 

No extensions are activated for type `shell`
```
preLaunchTask: {
      "name": "Ensure Prelaunch Dependencies",
      "type": "shell"
}
```

or 

Only `npm` extension is activated
```
`"prelaunchTask": {
    "taskType": "npm",
    "taskLabel": "npm: build"
}
```

**Comment by connor4312** [comment]
Correct me if I'm wrong -- I don't know all the intricacies of the task system by far -- but doesn't the label string already reference a task defined in the tasks.json, and could we read the type from there?

**Comment by meganrogge** [comment]
Based on logging, I'm seeing only the relevant extension activated when I start debugging. Example using the terminal ext sample:


![Image](https://github.com/user-attachments/assets/53ad21f9-7ddb-4937-b290-e16457bf5516)

**Comment by meganrogge** [comment]
So, I believe that we're only activating all extension providers when we cannot find the right one in the `tasks.json` file.

**Comment by meganrogge** [comment]
@roblourens, you mentioned seeing this frequently. Do you know which workspace you're in when you see it?  / which extensions are getting activated?

**Comment by meganrogge** [comment]
One can already add a `type` property but needs to also provide a `script`. 

The repro for this is set `preLaunchTask` to be the default build task.

![Image](https://github.com/user-attachments/assets/8c72f5c9-a22e-478c-a36a-727c8307615b)

**Comment by meganrogge** [comment]
So ideally, we'd check if the `tasks.json` file contains the default build task before activating all providers.

**Comment by connor4312** [comment]
Referencing `preLaunchTask: "npm: start"` with this in my tasks.json, it still activates all task providers before running it:

```
    {
      "type": "npm",
      "script": "start",
      "problemMatcher": [],
      "label": "npm: start",
      "detail": "echo hello"
    }
```

It's hard for me to give good input here as I don't really know how tasks work in relation to `preLaunchTask`. In the [docs](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes) we only say that prelaunchTask can be set to "the label of a task specified in [tasks.json](https://code.visualstudio.com/docs/editor/tasks)". I don't have a good grasp on any implicit behavior outside of that. It seems like:

- They can also reference tasks provided on the fly by task providers -- how would a user know what `label` to set this to when provided dynamically? Or is this only really relevant to programmatically generated launch.jsons?
- As discussed in [157957](https://github.com/microsoft/vscode/issues/157957#issuecomment-1847778075), they can be objects, but only for task types that are provided by extensions. Is it the case that this just allows extension-provided tasks to be "inlined" into the config? (There's no intellisense here so we don't provide any hints for users to go off of)

**Comment by meganrogge** [comment]
I think I have a solution. We should not be resolving tasks that aren't `isDefault` when the `defaultBuildTask` variable gets evaluated.

**Comment by meganrogge** [comment]
Closing this issue. We don't need to add a `type` property, just need to be smarter about when and what we activate.

**Comment by meganrogge** [comment]
Before, we were fetching all tasks, activating, then narrowing down which was the build task. Instead, I think we should try to find a default task in the `tasks.json` first. If there isn't one, then we activate all providers.
