### ISSUE TITLE
Test: Git - refresh model based on terminal command execution

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#223068]
Refs: https://github.com/microsoft/vscode/issues/220995

- [x] macOS @roblourens
- [x] linux @joshspicer
- [x] windows @bhavyaus

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23223068%0A%0A&assignees=lszomoru)

---

Refreshing the "Source Control" view is either triggered by performing a git operation using VS Code or by file system events. This milestone we started leveraging the new terminal shell extension API to listed to various git operations executed in the integrated terminal and refresh the "Source Control" view based on that. We are currently refreshing the "Source Control" view if the following git commands are executed in the VS Code integrated terminal: `add`, `branch`, `checkout`, `clean`, `commit`, `fetch`, `reset`, `revert`, `pull`, `push`, `switch`. If you can think of any other commands that should be added to the list please let me know. Thanks!

### Prerequisites
1. Install the latest version of VS Code Insiders
2. Open the Output view, and switch to the Git extensions channel
3. Click on the Gear icon, select "Trace". 
4. Click on the Gear icon, select "Set As Default"

### Test plan
1. Open a folder/workspace that contains a git repository
2. Make a change to a file 
3. Open the integrated terminal and run `git add .`
4. Open the git output channel
    * Confirm that you see the following entry:
      ```log
      [trace] [TerminalShellExecutionManager][onDidEndTerminalShellExecution] Matched git subcommand: add
      ```
5. Try other git sub-commands from the list and confirm that an entry is added to the it output channel
6. Execute a command that would result in an error (ex: `git add ..`)
    * Confirm that no entry is being recorded in the git output channel
7. In the integrated terminal switch to a different folder that contains a git repository
8. Execute the following command - `git fetch`
    * Confirm that the git output channel contains the following entries
      ```log
      [TerminalShellExecutionManager][onDidEndTerminalShellExecution] Matched git subcommand: fetch
      [TerminalShellExecutionManager][onDidEndTerminalShellExecution] Unable to find repository for current working directory: file:///PATH
      ```

**Comment by roblourens** [comment]
How about the commands `mv`, `rebase`, `rm`? And there's `switch` and `restore` which are new commands that are related to `checkout`.

**Comment by bhavyaus** [comment]
Also `stash` and `cherry-pick` which result in changes to the git repo.
