### ISSUE TITLE
Using json loop and Html Showing Problem

### ISSUE THREAD

**Issue by VR-Rathod** [microsoft/vscode#223051]
Type: <b>Bug</b>

When using Django templates in VSCode, I'm experiencing a false positive error detection. The error "css-lcurlyexpected" is incorrectly reported for a <style> block containing a Django template block ({% block css %}{% endblock %}). This error is not relevant to the Django template syntax and should be ignored. The file path is .../basic.html. Please consider updating the CSS linting rules to accommodate Django template syntax."

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
godot-files|alf|0.0.9
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
prettier-vscode|esb|10.4.0
code-runner|for|0.12.2
vsc-python-indent|Kev|1.18.0
csdevkit|ms-|1.8.14
csharp|ms-|2.34.12
vscode-dotnet-runtime|ms-|2.1.1
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
cmake-tools|ms-|1.18.43
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
vsliveshare|ms-|1.0.5936
material-icon-theme|PKi|5.6.0
LiveServer|rit|5.7.9
svelte-vscode|sve|108.5.4
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vstuc|vis|1.0.2
vscode-icons|vsc|12.8.0
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
legacy_priority:31094926
refactort:31098051
ccplt:31098110
pythonrstrctxt:31093869

```

</details>

**Comment by aeschli** [comment]
The Django file is opened as  a HTML file?

The built-in HTML extension does not do any validation. This must come from an extension.
You can use the `Help: Start Extension Bisect` command to find out which extension does that. When found, please file the issue against that extension.
