### ISSUE TITLE
Custom Labels (`customLabels`) Not Escaping Properly - Backslash Doesn't Work

### ISSUE THREAD

**Issue by babakfp** [microsoft/vscode#223107]
Hi 👋

https://github.com/microsoft/vscode/issues/213117

The goal is to match a string that contains `[]` with whatever inside it. But because of the backslash (`\`) limitation, this is not possible. 

Using something like `**/?...slug?.astro` is not a good solution because `[]` may contain any words (with or without `...`).

This regex escape limitation is present in other places in vsCode too.

If this issue gets fixed, I can do something like this in my vsCode config:

```json
{
    "workbench.editor.customLabels.enabled": true,
    "workbench.editor.customLabels.patterns": {
        "**/+*.*": "${dirname}/${filename}.${extname}",
        "**/\\[*]\\/+*.*": "${dirname(1)}/${dirname(0)}/${filename}.${extname}",
        "**/routes/+*.*": "${filename}.${extname}"
    },
}
```

@benibenj

**Comment by benibenj** [comment]
I believe this is a limitation we are not able to fix easily, @bpasero do you know if we have a way to escape `[]`? I'm parsing the glob pattern which turns `/` into `//`.

**Comment by bpasero** [comment]
I think not.

https://github.com/microsoft/vscode/blob/5014de668c9c2c8bca1224d82feb7b4b4b09e908/src/vs/base/common/glob.ts#L112

**Comment by benibenj** [comment]
@babakfp there might be another way to match the [], but it is a bit hacky. I was able to match the file `folder/[hello].py` with `**/[[]*[]].py`. Let me know if this works for your case.

**Comment by babakfp** [comment]
Thank you, @benibenj. Your solution worked perfectly!

This solves the issue for my use case, so if needed, feel free to close the issue.

---

This is my config for SvelteKit `+` files:

```json
{
    "workbench.editor.customLabels.patterns": {
        "**/+*.*": "${dirname}/${filename}.${extname}",
        "**/[[]*[]]/+*.*": "${dirname(1)}/${dirname(0)}/${filename}.${extname}",
        "**/routes/+*.*": "${filename}.${extname}"
    },
}
```

Result:

- `src/routes/+page.svelte` will be `+page.svelte`.
- `src/routes/about/+page.svelte` will be `about/+page.svelte`.
- `src/routes/posts/[id]/+page.svelte` will be `posts/[id]/+page.svelte`.
  Can be turned into `posts/[]/+page.svelte` by using `"${dirname(1)}/[]/${filename}.${extname}"` instead.

**Comment by benibenj** [comment]
related #https://github.com/microsoft/vscode/issues/213117
