### ISSUE TITLE
Workspace Trust doc link broken

### ISSUE THREAD

**Issue by illlust** [microsoft/vscode#223157]
Type: <b>Bug</b>

Welcome - Learn the Fyndamentals
Safely browse and edit code
Workspace Trust Link 
https://github.com/microsoft/vscode-docs/blob/workspaceTrust/docs/editor/workspace-trust.md
404 - page not found

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes: Restricted

**Comment by lszomoru** [comment]
@illlust, could you please provide a screenshot of where this broken link is? Thanks!

**Comment by ntrogh** [comment]
@lszomoru Got it - issue is in the walkthrough. Fix incoming. Thanks for signaling this @illlust.

**Comment by rzhao271** [comment]
Is this a candidate? The change has been merged to the main branch but not the release branch, and so the fix is not in the latest Insiders.

**Comment by ntrogh** [comment]
IMO, it can go with the next one.
