### ISSUE TITLE
Non dirty save with a keymap does not trigger correct file 'touch' behavior

### ISSUE THREAD

**Issue by NinoFloris** [Microsoft/vscode#22313]
- VSCode Version: 1.10.2
- OS Version: 10.12 osx sierra

Steps to Reproduce:

1. install intellij keybindings
2. run a file watcher to see if it picks up changes, gulp/webpack watch or something like it.
3. open a file, don't change anything
4. with the keybindings enabled (and command+s is still save in intellij keybindings) it won't trigger the watcher. without this enabled it works like you would expect.

**Comment by waderyan** [comment]
Apologize for the delay here. This fell through the cracks. 

This looks like an issue with the intellij keybinding extension. Please open an issue on that repository. https://github.com/k--kato/vscode-intellij-idea-keybindings/issues

**Comment by NinoFloris** [comment]
So keymaps are extensions?

**Comment by waderyan** [comment]
Yes. https://marketplace.visualstudio.com/search?target=VSCode&category=Keymaps&sortBy=Downloads
