### ISSUE TITLE
Batch Syntax Highlighting - support multiline comments with `::` and `^`

### ISSUE THREAD

**Issue by Andrej730** [microsoft/vscode#223115]
Does this issue occur when all extensions are disabled?: Yes

System:
```
Version: 1.92.0-insider
Commit: 82104a3a6cf8713b81e5bbd97960dbf5c82a816a
Date: 2024-07-05T00:00:00.000Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22635
```

Steps to Reproduce:
1. There is a way to create multiline comments in batch files by combining `::` and `^` (to create multiline commands).
```bat
:: multiline comment ^
echo hi, it's still multiline comment ^
and still...
@echo it's printed as multiline comment is over.
```

2. See the syntax highlight, lines `echo hi, it's still multiline comment ^` and `and still...` are not greyed out as comments though they kind of are.
![image](https://github.com/user-attachments/assets/bfe27cb2-6516-4bd7-b0a4-2c6dc519c4e0)

**Comment by alexr00** [comment]
I'm having trouble finding official documentation that describes this multiline comment. @Andrej730 could you please point me to the official documentation that describes this multiline comment?

**Comment by Andrej730** [comment]
Sorry, I don't know if there's any official documentation for this - it's just a combination of `::` that's used for comments and line-continuation `^` that prolongs comment block to the next line.
Even `::` might not be officially documented as a comment operator as it's essentially a label that acts as a comment.

**Comment by Andrej730** [comment]
@alexr00, would this be out of scope for the syntax highlighter? Though it's not officially documented, it is a consistent behavior for cmd scripts, and it would be great if the syntax highlighter could accommodate it.

**Comment by RedCMD** [comment]
VSCode uses https://github.com/jeff-hykin/better-shell-syntax as the builtin syntax
so make a feature request there

**Comment by Andrej730** [comment]
> VSCode uses [jeff-hykin/better-shell-syntax](https://github.com/jeff-hykin/better-shell-syntax) as the builtin syntax
> so make a feature request there

I believe it's the syntax for shell (bash), not for windows cmd.

**Comment by RedCMD** [comment]
sorry my bad

batch repo looks abandoned https://github.com/mmims/language-batchfile
