### ISSUE TITLE
can not change terminal tabs icon

### ISSUE THREAD

**Issue by wqxl** [microsoft/vscode#223195]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:
1. set "terminal.integrated.tabs.defaultIcon": "circle-large-filled"
2. open new terminal
3. see the terminal tab icon

![QQ_1721701403533](https://github.com/user-attachments/assets/bdc6bf4b-4e9d-4ead-83eb-5b79fc6663e9)

below is my expectation.
![QQ_1721701462383](https://github.com/user-attachments/assets/3b637c1f-a731-44c9-90c5-5f6103fffb35)

**Comment by meganrogge** [comment]
cannot reproduce - are there more steps required?

![Image](https://github.com/user-attachments/assets/afff088f-3ffd-4e37-bf4b-91b254c8575d)

**Comment by wqxl** [comment]
no more steps, but i reproduce every time
![QQ_1721780883410](https://github.com/user-attachments/assets/c7a378a1-d03f-49d3-b7d1-601a735ae8ea)

**Comment by wqxl** [comment]
> cannot reproduce - are there more steps required?
> 
> ![Image](https://private-user-images.githubusercontent.com/29464607/351482905-afff088f-3ffd-4e37-bf4b-91b254c8575d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3ODI2MDEsIm5iZiI6MTcyMTc4MjMwMSwicGF0aCI6Ii8yOTQ2NDYwNy8zNTE0ODI5MDUtYWZmZjA4OGYtM2ZmZC00ZTM3LWJmNGItOTFiMjU0Yzg1NzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDAwNTE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYTNlZjA2M2M3YzlmMjk1ZWEwOWRlY2UxODFhMmYxNWJkYTRkOTVjZDllNTFmODYyY2JiMzk3NmY0MGZhYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.go5Yt9j9i6k7Ooytuxzt6kkEyKCn7bxYGV4jbzGnORg)

closed???? why?????

**Comment by wqxl** [comment]
> cannot reproduce - are there more steps required?
> 
> ![Image](https://private-user-images.githubusercontent.com/29464607/351482905-afff088f-3ffd-4e37-bf4b-91b254c8575d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3ODI2MDEsIm5iZiI6MTcyMTc4MjMwMSwicGF0aCI6Ii8yOTQ2NDYwNy8zNTE0ODI5MDUtYWZmZjA4OGYtM2ZmZC00ZTM3LWJmNGItOTFiMjU0Yzg1NzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDAwNTE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYTNlZjA2M2M3YzlmMjk1ZWEwOWRlY2UxODFhMmYxNWJkYTRkOTVjZDllNTFmODYyY2JiMzk3NmY0MGZhYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.go5Yt9j9i6k7Ooytuxzt6kkEyKCn7bxYGV4jbzGnORg)

no more steps, but i reproduce every time
![QQ_1721780883410](https://github.com/user-attachments/assets/c7a378a1-d03f-49d3-b7d1-601a735ae8ea)

**Comment by meganrogge** [comment]
Unless you can provide more info abt how to reproduce, I can't action this. Pls don't create another issue.

**Comment by wqxl** [comment]
> Unless you can provide more info abt how to reproduce, I can't action this. Pls don't create another issue.
i just do what i say:
1，set terminal.integrated.tabs.defaultIcon
2，open new terminal
no more steps......

**Comment by wqxl** [comment]
why you close this issue??????

**Comment by wqxl** [comment]
Didn't you notice that your system is macOS?
