### ISSUE TITLE
[Javascript] Support JSDoc optional params in syntax check (ts(6133))

### ISSUE THREAD

**Issue by jasonpolites** [microsoft/vscode#223161]
JSDoc prescribes a syntax for [optional parameters](https://jsdoc.app/tags-param): Namely, square brackets:

Optional
```javascript
/**
 * @param {string} [somebody] - Somebody is optional
 */
```

Not optional
```javascript
/**
 * @param {string} somebody - Somebody is not optional
 */
```

Ideally the syntax checker that highlights an unused parameter (ts(6133)) would recognize that a parameter was optional:

![image](https://github.com/user-attachments/assets/537d0874-dc46-4c3d-83ff-fd7130260c9f)

![image](https://github.com/user-attachments/assets/c017c7e5-90e7-49b5-984f-b040a4341b3a)

**Comment by mjbvz** [comment]
It's shown as unused because the parameter is never used anywhere, not because the parameter is optional. This is very likely a mistake

As soon as you use `data` in the function body it won't be shown as unused anymore

**Comment by jasonpolites** [comment]
Yes.. this is correct, however the particular case (which I realize I omitted from my screenshot), is when attempting to use JSDoc to represent an abstract method in a JS class.

JSDoc defines an [@abstract](https://jsdoc.app/tags-abstract) tag that _"identifies members that must be implemented (or overridden) by objects that inherit the member."_

So in this case there is no implementation of the method, and thus no opportunity to use the parameter.

Perhaps it would be more correct to request that class methods with the `@abstract` tag omit the unused warning?

It would also be possible to do something like:

```
/**
 * @abstract
 * @param {string} somebody - Somebody argument
 */
foobar () {}
```

Where the argument is not specified in the method declaration at all, but somehow this seems wrong.
