### ISSUE TITLE
Test: Aux Window Issue Reporter

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#223158]
- [x] windows @brettcannon 
- [x] macOS @deepak1556
- [x] linux @joshspicer 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23223158%0A%0A&assignees=justschen)

---

Continuation of https://github.com/microsoft/vscode/issues/217547

The aux window version of the issue reporter is now enabled by default in non-stable versions via setting. Continuing the ongoing issue reporter new feature/update saga, so please give it another test!

### Testing
- setting to control is `issueReporter.experimental.auxWindow`, enable by default for everything except stable
- Help -> Report Issue or `Ctrl + P ` -> `issue `
- Make sure the window opens.
- Check for `System Info`, etc and make sure it all makes sense.
- Try submitting a few issues.
- Try submitting on `Python` specifically (this will trigger the extension command)
- Type something in title and description, make sure when you hit `ctrl + w`, it gives you a dialog. 

### Known issues and limtations
- When in full screen, this will open an issue reporter tab in a new full screen.

Any recommendations on general styling, workflow, etc are appreciated!

**Comment by joshspicer** [comment]
Worked great!
