### ISSUE TITLE
Move CancellationToken into own npm package

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#22318]
JavaScript does not have a native way to represent cancellation of async operaions, and there have been many discussions and failed attempts to fold this into the language. [The most promising tc39 proposal](https://github.com/tc39/proposal-cancelable-promises) has been withdrawn (which used `CancellationToken`s), bluebird has cancellable promises and RxJS Observables are cancellable.

VS Code uses `CancellationToken` from C# for cancellation. They are also used in the TS Server, vscode-jsonrpc and vscode-languageserver. Currently, this comes down to just two classes: `CancellationToken` and `CancellationTokenSource`. These classes seem to be duplicated in the code of every of the above examples. This imposes a problem, because one of the biggest concerns with cancellations is what a promise should resolve to when it is cancelled - typically it is rejected with a `CancelledError`, and code needs to differentiate between a true error and a cancellation in eg `catch` blocks. The TS Server for example does define its own `OperationCancelledException` (which weirdly doesn't inherit from `Error`). If every API defines its own classes and there is no uniform interface, it is impossible to do proper checks for CancellationErrors in catch blocks (eg with `instanceof` or some other type check).

Adding to that, the implementation is lacking basic features that were discussed in the tc39 proposal and available in C#, for example composition of CancelTokens. It is a basic use case to combine multiple CancellationTokens, creating a new CancellationTokenSource from an existing CancellationToken or `throwIfRequested()`.

Moving cancellation into a standalone open source library that anyone could use would greatly improve the interoperability between APIs and allow to easily add more features that improve usage ergonomics.

**Comment by morrme** [comment]
@jrieken I am new to this codebase but am curious about the process of building the package to solve this issue. Is mentoring available?

**Comment by jrieken** [comment]
Yes, sure. While one could extract the cancellation token into a separate node module it would be hard for us to adopt tho. The problem is that we are mono-source for VS Code and the Monaco Editor and that we have not yet invested in making the latter, which runs inside browsers, consume node-modules. Still, during the process of creating a new node module from the cancellation token implementation I can help. 

Also note that there are a few catches that make it less slick and less powerful than it is in C# or other multithreaded languages. Because Javascript is _singlethreaded_ certain things just don't work well. Image code like this

```js
function callMe(token: CancellationToken) {
  while(!done) {
    if(token.isCancellationRequested) {
      return;
    }
   // do some very heavy lifting
  }
}
```

So because JS is single threaded and because the while loop run synchronous, e.g never releases the event loop, there is zero chance of the cancellation token ever flipping its state.

**Comment by felixfbecker** [comment]
@jrieken the motivation behind my idea was that TypeScript added Cancellation too, vscode has them and vscode-jsonrpc too. If you are using e.g. TypeScript and vscode-jsonrpc, but use different types of CancellationErrors. If you call these functions and e.g. catch errors, you likely want to log true errors, but exclude cancellation errors. This already is a challenging task because of the different types.

Since you brought up the discussion, I met several issues with CancellationTokens too that ultimately made me stop using them myself. In particular
- It is very hard to compose them - e.g. create a CancellationToken that is cancelled when one of multiple others are cancelled, or create one that is cancelled when all of multiple others are cancelled. When multiple consumers need to await the same operation, you should only cancel it when all consumers requested cancellation.
- It's hard to track Cancellations to do e.g. when disposing an object because of the decoupling of CancellationTokenSource and CancellationToken - imagine a language server where `shutdown` is called and all pending async operations should be called. To accomplish this, you have to create a new CancellationTokenSource, link it to the CancellationToken, save the source and use the new token from the new source.

I found much more success in using Observables: subscribing to an Observable returns a Subscription, that can be unsubscribed from and saved. An Observable can react to unsubscribing, and especially all operators will automatically propagate unsubscribing. So if you join multiple Observables, all will be unsubscribed from, when you limit the results, the source will be unsubscribed from as soon as you have everything you need, etc. If an Observable has multiple consumers (subscribers), the source is only truly unsubscribed until all consumers unsubscribed.

But I still need to work with the cancellation mechanisms of vscode-jsonrpc and TypeScript. 

Btw, you could make your example work by making the function `async` and adding a `await new Promise(resolve => process.setTimeout(resolve, 0))` to the loop.

> The problem is that we are mono-source for VS Code and the Monaco Editor and that we have not yet invested in making the latter, which runs inside browsers, consume node-modules.

I'm curious, what is the challenge here? Afaik Monaco is distributed as a single bundle file, so wouldn't that already require the usage of browserify/webpack?

**Comment by nicksnyder** [comment]
Has there been any discussion around pulling in something like RXJS? Having an Observable primitive in the VS Code codebase would be helpful, especially in the case of streaming data (e.g. references, quick open results, etc.). Using PPromise feels clunky.

**Comment by felixfbecker** [comment]
One problem is that the C# functions you are using like `CreateLinkedCancellationSource` or `CancelAfter` don't actually exist in TS, so you first have to implement them. There is also only an API for composing tokens in an ANY/OR semantic, but no API for composing in an ALL/AND semantic. An example is a memoized function that returns the same result promise on subsequent calls - it must only be cancelled when ALL consumers requested cancellation, not when ANY of the consumers did.

You don't need your own `Set` with Rx, all `Subscription`s are composable - you can just call `add()` to link more Subscriptions that will be unsubscribed from together.

`CancelAfter` in Rx is simply the `timeout` operator.

The pletora of ways async operations can be combined in Rx operators would be really hard to achieve with cancellation tokens, it's not always serial operations. Think about advanced use cases like debouncing a text input and doing an async request (e.g. VS Code's symbol search), which should be cancelled once the next request is made. In Rx, that is 3 lines of code, using the `debounceTime` and `switchMap` operators. `switchMap` will then cancel the previous request when it does a new one. I can't think of an implementation from the top of my head, but I imagine this to be way more code with CancellationTokens.

Here are some examples from a real TS project that I refactored from CancellationTokens to Observables:

- Unsubscribing on dispose/shutdown [with CancellationTokens](https://sourcegraph.com/github.com/sourcegraph/javascript-typescript-langserver@3a829d1a7d9337ff0afb7907024365e66f7e203e/-/blob/src/project-manager.ts#L28:22$references) | [with Observables](https://sourcegraph.com/github.com/sourcegraph/javascript-typescript-langserver/-/blob/src/project-manager.ts#L95:17$references)
- [Helpers I had to write to support cancellable memoization](https://sourcegraph.com/github.com/sourcegraph/javascript-typescript-langserver@8b35cfda45908047db8c9f9fe5952e40c337fe08/-/blob/src/cancellation.ts#L1:34) (now deleted as not needed anymore with Observables)

**Comment by ljw1004** [comment]
It's true that existing cancellationToken combinator libraries haven't seen practical use of the "all" semantics, and so haven't provided library methods for it. It's always been easy to write one in C# but I've never seen anyone do that.

Here are the use-cases you describe. How do they compare with RX? (1) They're no more complicated. (2) They have the very appealing property that you can set a debug breakpoint anywhere and easily figure out the flow -- how you got here, why. The debug operations 'step-over' and 'step-in' and 'step-out' all work nicely with the steps in your behavior. (3) In general, with async and cancellation tokens you can build up the desired behavior easily out of the much smaller set of primitives provided, and in a form that's readable+understandable by the junior programers on your team. There are fewer lambdas, you don't have to master the huge RX combinator library.

```
// Scenario: a search box, where we cancel any outstanding
// requests when a new key is typed in.

var cts = new CancellationTokenSource();

textEdit.onDidChange((text) => {
  cts.cancel();
  cts = new CancellationTokenSource();
  DisplayResults(await GetResultsAsync(text, cts.Token));
});
```

Another. This one uses a 'RateLimiter' class that's a nice small composable building block, and easy to write.

```
// Scenario: we wish to rate-limit to avoid overburdening
// the server. (People often approximate this with 'debouncing',
// but that's a poor solution because it pessimistically forces
// extra latency even in cases where latency isn't need.)

var cts = new CancellationTokenSource();
var limiter = new RateLimiter(300, cancelPrevious: true);

textEdit.onDidChange((text) => {
  await limiter.nextAsync();
  cts.cancel();
  cts = new CancellationTokenSource();
  DisplayResults(await GetResultsAsync(text, cts.Token));
});
```

Another:

```
// Scenario: okay, very well, we'll use debouncing if you insist!
// With the behavior that we wait until at least 300ms of idle time
// have passed before proceeding. I wrote this so it allows a prior
// request to continue even when the user types keys in case this
// provides a nicer user experience. If it doesn't, we'd move the two
// "cts" lines earlier.

var cts = new CancellationTokenSource();
var debounceCts = new CancellationTokenSource();

textEdit.onDidChange((text) => {
  debounceCts.cancel();
  debounceCts = new CancellationTokenSource();
  await Task.Delay(300, debounceCts.Token);
  cts.cancel();
  cts = new CancellationTokenSource();
  DisplayResults(await GetResultsAsync(text, cts.Token));
}
```

**Comment by felixfbecker** [comment]
There are still a few problems with the examples you provided. `Task.Delay()` or `RateLimiter` also don't exist in JS, so these would need to be implemented first. The first should be easy to find on npm, but with a 99.9999% chance it will not support CancellationTokens. For RateLimiter I think JS devs usually go with lodash's `debounce` with the `leading` option, but that doesn't have support for promises and CancellationTokens. So you have to home-bake them first. Those implementations have to be learnt by a junior developer just like the `debounceTime` operator has to be learned (although I would imagine even a junior dev knows what debouncing is). Additionally, they need to be well tested to ensure they are bug-free, and even then have potential to not work as designed (I've been there with my own CancellationToken helpers, it eats up time).

Second problem is one I already mentioned, the handling of the CancelledError. In your example, `Task.Delay()` and `GetResultsAsync` will throw `CancelledError`s when they are cancelled. The event handler is dispatched from the event loop, so depending on your Node version it will either crash the process on cancellation (since Node has no concept of a "CancelledError") or log an ugly "UnhandledPromiseRejection" warning. So your code actually becomes:

```ts
let cts = new CancellationTokenSource();
let debounceCts = new CancellationTokenSource();

textEdit.onDidChange(async text => {
  try {
    debounceCts.cancel();
    debounceCts = new CancellationTokenSource();
    await cancellableDelay(300, debounceCts.token);
    cts.cancel();
    cts = new CancellationTokenSource();
    displayResults(await getResultsAsync(text, cts.token));
  } catch (err) {
    if (!isCancelledError(err)) { // ignore CancelledErrors
      throw err;
    }
  }
});
```

Observables don't have this problem, if you unsubscribe, you expressed you are not interested anymore and won't get any handlers called afterwards, not even `error` with a `CancelledError` (except the `finally` operator handler, which is always called as you would expect).

Now, this is mostly personal preference (also of functional style over imperative), but overall I find this more readable:
```ts
Observable.fromEvent(textEdit, 'change')
  .debounceTime(300)
  .switchMap(getResults)
  .subscribe(displayResults, handleError)
```
I can still set breakpoints inside the arrow functions thanks to VS Code's column breakpoint support.

**Comment by felixfbecker** [comment]
Closing this, as JavaScript now has native [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/AbortController) and [`AbortSignal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) classes already shipped in FF and Edge, which work just like CancellationTokens.
Abort errors have `name` set to `AbortError`.

![image](https://user-images.githubusercontent.com/10532611/32094275-0889abc4-bab4-11e7-9e68-9a7e57b8923c.png)

I believe this is what everyone should use to ensure the best interoperability.
