### ISSUE TITLE
Test: Test Message Stacktrace

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#223148]
ref https://github.com/microsoft/vscode/issues/214488

- [x] anyOS @DonJayamanne 
- [x] anyOS @Yoyokrazy

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23223148%0A%0A&assignees=connor4312)

---

This iteration, I've added some API and UI to support call stacks in test messages. I've adopted this for the selfhost test provider that we use in VS Code. The UI PR with some explanation is implemented here https://github.com/microsoft/vscode/pull/222126

- Make some tests in VS Code fail with exceptions
- Explore the UI show both in the error peek at the Test Results view (when clicking on failing tests in the view's history)
- See that interactions make sense and that the UI functions well, e.g. as it's resized.
- Check out the API proposal and see whether it makes sense to you https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.testMessageStackTrace.d.ts

**Comment by DonJayamanne** [comment]
@connor4312 Please can you provide details on how I should enable this?
I've installed latest insiders, built vs code, ran a test and still do not see the new UI


![Image](https://github.com/user-attachments/assets/5542f725-dc3a-46ab-86f3-8a9310afe6b5)

**Comment by connor4312** [comment]
This works for me. You may need to restart the extension host on the VS Code window if you just pulled down and built the latest changes, as it may have already loaded the selfhost provider that previously existed on disk.

![image](https://github.com/user-attachments/assets/fe6ffed7-524d-4cfb-af22-eb0274394fb7)
