### ISSUE TITLE
Test: Lightbulb Widget in the Gutter

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#223145]
ref https://github.com/microsoft/vscode/issues/214711 

- [x] anyOS @ulugbekna 
- [x] anyOS @bamurtaugh

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23223145%0A%0A&assignees=justschen)

---

### Background
There has been a long standing papercut where the lightbulb widget will often spawn over code in the editor and notebook. We mitigate this by trying a `best case` for each scenario. 

### Steps

1. Find some code that does not have indent. 
2. Click or highlight around and see where the lightbulb renders. 
3. Make sure clicking on the lightbulb in the gutter and in the editor actually do something. 

example:
<img width="471" alt="Screenshot 2024-07-22 at 3 31 06 PM" src="https://github.com/user-attachments/assets/b4259b19-3139-464c-90a1-dc18c878b894">

### Things to verify

- When breakpoints are in the gutter, the lightbulb will not spawn there.
- When text is blocking above and below, lightbulb will spawn in the gutter
- Also try in cases without indents - the widget will still spawn in the best case scenario based on available space.

**Comment by ulugbekna** [comment]
I guess this is a known issue but a lightbulb still appears on code when there's a breakpoint

![Image](https://github.com/user-attachments/assets/8332087e-038e-421f-b729-f87e341c0546)
