### ISSUE TITLE
Allow Profiles to be pinned to Windows Taskbar/MacOS Dock OR Let VSCode remember which profile a folder was opened with

### ISSUE THREAD

**Issue by Sparker0i** [microsoft/vscode#223149]
### Feature Request

1. Allow Profiles to be pinned to Windows Taskbar/MacOS Dock, OR 
2. Let VSCode remember which profile a folder was opened with

### Background:
I have lots of profiles in VSCode for programming in various languages: Scala, Python, Golang, NodeJS etc. Each profile has its own set of extensions and keyboard shortcuts.
At the moment VSCode allows to only pin the default executable to the MacOS dock. When we open using this icon, it opens up all the last open windows from all profiles. 
If I am in a profile 1, and then From there if I choose to open a folder in a new window which should be used with profile 2, it ends up opening the folder in profile 1. This is a problem.

With VSCode gaining extensions for almost all programming languages, people can configure VSCode profiles to be good alternatives to Full fledged IDEs. 
Many companies have started to consider VSCode as an IDE and have started consolidating the tooling from other IDEs to VSCode.

Thus it would be a good to have feature if we can have either one or both of the below features:

1. Allow to pin VSCode Profiles to the MacOS Dock
  a. This will allow us to open new window directly into the intended profile, and not open all previous windows of all profiles
  b. We can then choose to open the folder in this correct profile.
2. Let VSCode remember what profile was used to open a given folder in a window
  a. In this way, even if we open a new Window using Cmd+Shift+N in a wrong profile, VSCode will remember what profile was used to previously open this folder and hence open it in the correct window.
  b. If the profile happens to be deleted, VSCode can then open either in the same profile or use the Default one.

**Comment by msdemt** [comment]
> > If I am in a profile 1, and then From there if I choose to open a folder in a new window which should be used with profile 2, it ends up opening the folder in profile 1. This is a problem.
> 
> You can always configure which profile to use by default for new windows using following setting
> 
> ![Image](https://private-user-images.githubusercontent.com/10746682/351399309-ed3d2064-1671-4c12-80cc-e53c27b5f524.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTMxMTgsIm5iZiI6MTcyMTk5MjgxOCwicGF0aCI6Ii8xMDc0NjY4Mi8zNTEzOTkzMDktZWQzZDIwNjQtMTY3MS00YzEyLTgwY2MtZTUzYzI3YjVmNTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDExMjAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZmQ4OGY1MWFkNDBmZTRlOGNhOWY0ZDkxZTExYTgxMTgxNjdkZmZhOWVmZjczMTg3NzRkZTUzOTFjMWEzMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v_71NE-_kpxBYwu-tIRnhUjNyi7QjK5u9RQTHagaFgY)
> 
> Please use this setting and let us know if it helps. If it helps, let us know what else is missing?

I think use different profile for different platform is a good idea

for example , create a profile named masos_profile for macos system, create a profile named ubuntu for ubuntu system.

but when open a new window, profile reset to Default, is a annoying things, so I agree with sandy081's statement

**Comment by sandy081** [comment]
> but I believe VSCode can still have an enhancement where it remembers which Profile was a window/project open in.

It does and works like this from beginning. Can you please confirm this behaviour and provide steps to reproduce if it is not?

**Comment by Sparker0i** [comment]
> > but I believe VSCode can still have an enhancement where it remembers which Profile was a window/project open in.
> 
> It does and works like this from beginning. Can you please confirm this behaviour and provide steps to reproduce if it is not?

Checked again and it is working now provided the New Window Profile is set to Default and not the one from Active Window. However there were few instances where it did not open in the right profile. Unable to reproduce them using Open source repos.

**Comment by sandy081** [comment]
Thanks for the confirmation. Please reopen or create a new issue with required steps to reproduce if you see the issue again. Thanks.
