### ISSUE TITLE
Microsoft Copilot

### ISSUE THREAD

**Issue by daedaevibin** [microsoft/vscode#223110]
I would like Microsoft Copilot to be integrated into VS Code as more people might use it, such as myself, because of the easy access and easily understandable responses that are well detailed 90% of the time. This would be extremely helpful (At least to me) who use AI to give feedback on already created works and search for issues to correct problems in their code.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, we do have an extension for this, 
Please try using https://marketplace.visualstudio.com/items?itemName=GitHub.copilot
