### ISSUE TITLE
Thoughts regarding the integrated terminal

### ISSUE THREAD

**Issue by pharmmd-rich** [Microsoft/vscode#22319]
First of all, great work on the integrated terminal everyone!  I tried it again recently after not using for a while and it has improved significantly.  That being said, I have a couple thoughts regarding the look, feel, and key usage of the terminal.

1) Rather than having the tabs for Problems, Output, Debug Console, and Terminal be at the top, why not put them at the side or bottom and then convert the terminal drop down list to tabs?  This would allow 1 click to switch between tabs vs 2.
2) The dropdown list currently displays a list of processes, however, I like giving my terminals custom names in OS-X.  The drop down list does not appear to honor these names. (they are set using: `printf '\033]0;title\007'"`.
3) It would be great if you could use a custom theme just for the terminal.  While I use the default theme for VSCode, I would like the background to be black for the terminal to provide cleaner separation.
4) When closing a terminal and the default shell isn't the current active process, it would be great if you could pop up a warning message.  I've accidentally closed terminals with running processes in them...leaving the process orphaned.  I then have to go in and kill the process manually. 

Just a few thoughts.  Thanks for an awesome editor!

**Comment by Tyriar** [comment]
Thanks for the comments!

1. Covered by https://github.com/Microsoft/vscode/issues/10546
2. Good idea, this is supporting in the underlying library already so it's probably doable. Created https://github.com/Microsoft/vscode/issues/22325
3. Covered by https://github.com/Microsoft/vscode/issues/6979 (coming soon)
4. This is a very specific that would see very low usage imo, it's also particularly difficult to implement at the moment.
