### ISSUE TITLE
Empty entry in find all references peek view

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#22310]
- VSCode Version: Code - Insiders 1.11.0-insider (8ec754970c4a284a45db701d4e47a535b153a048, 2017-03-09T07:26:13.968Z)
- OS Version: Linux x64 4.8.0-39-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-svgviewer|cssho|1.3.1|
|githistory|donjayamanne|0.2.0|
|EditorConfig|EditorConfig|0.6.0|
|tslint|eg2|0.8.1|
|git-project-manager|felipecaputo|1.0.1|
|vsc-travis-ci-status|felixrieseberg|1.0.5|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|csharp|ms-vscode|1.7.0|
|seti-icons|qinjia|0.1.3|
|annotator|ryu1kn|0.10.1|
|lorem-ipsum|Tyriar|1.0.0|
|shell-launcher|Tyriar|0.1.1|
|theme-glacier|Tyriar|0.0.10|
|theme-sapphire|Tyriar|0.0.5|
|vscode-terminal-here|Tyriar|0.0.5|;

---

It worked and then didn't next time I ran it. I think I did a branch change, git pull (catching up 200 commits) and an `npm run watch`

![image](https://cloud.githubusercontent.com/assets/2193314/23760039/4b8857b2-04a3-11e7-92a5-58a3e54db35c.png)

**Comment by mjbvz** [comment]
Let me know if you have specific repo steps. I've only seen this intermittently, usually after doing a git operation

**Comment by Tyriar** [comment]
I think I've only ever seen this once
