### ISSUE TITLE
Test: Terminal PowerShell Intellisense

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#223130]
Refs: #154662, #221977, #223063, #222408, #222302, #222068

- [x] macOS @aiday-mar
- [x] windows @andreamah
- [x] windows @sbatten 

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23223130%0A%0A&assignees=Tyriar)

---

## Setup

- Install PowerShell 7 https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4
- Set `"terminal.integrated.suggest.enabled": true`
- Set `"terminal.integrated.shellIntegration.enabled": true` (default)
- Set `"terminal.integrated.developer.devMode": true`. This is a hidden setting which enables this status bar item that shows VS Code's understanding of the prompt.
- Set the default profile to pwsh
  ![image](https://github.com/user-attachments/assets/36e9a434-929e-44d6-8d3a-76c5b7fa2f24)
- Set log level to trace, use the button on the right to make it sticky across reloads
  ![image](https://github.com/user-attachments/assets/f74936c7-4d1f-4373-8fc1-5083c539056e)

To make sure everything is working, try open a pwsh terminal and make sure you see this circle in the gutter, that means that shell integration is working correctly:

![image](https://github.com/user-attachments/assets/0b68fc27-d30f-40c5-a5b8-acd0554663c6)

You should be able to then type any character and an intellisense popup should appear:

![image](https://github.com/user-attachments/assets/620573a2-528f-4fa4-b147-c617a5dc828b)

When it's shown up is driven by `terminal.integrated.suggest.quickSuggestions` and `terminal.integrated.suggest.suggestOnTriggerCharacters`, but can also be manually invoked with ctrl+space.

## Diagnostics

The dev mode status bar is useful to include in issue reports where the problem is likely caused by a bad prompt understanding:

![image](https://github.com/user-attachments/assets/c0a7f446-788f-48d2-8d9c-de4f59ab0f89)

Also when completions are incorrect the Pty Host output trace log is useful:

![image](https://github.com/user-attachments/assets/91da0894-c244-46a2-8e11-0f44e00017b9)

## Test

This iteration saw a lot of changes to our experimental PowerShell intellisense:

![image](https://github.com/user-attachments/assets/294e8e18-a2c0-4048-824b-13a081f5492d)

Please try use the terminal with the feature enabled and see where it's good, where it gets in the way and test some of the improvements mentioned below.

- Better reliability!
- Completions will now show exactly what will be typed, this fixes some problems with highlighting in the suggest widget
- Polished the `cd <path>` experience: `/` or `\` is added to the end of suggestions such that they request completions immediately after accepting.
- For directory completions, `/` and `\` are filtered the same
- New `terminal.integrated.suggest.runOnEnter` setting which configures whether pressing enter will execute the command or just complete.
- Faster start up, at the cost of requesting "global" completions when first typing
  - A consequence of this is that it's possible to get into a state where they are stale. If you hit this I'd be interested to hear what happened. To workaround it you can run the `Terminal: Clear Suggest Cache` command or just toggle the `suggest.enabled` setting.
- File-specific completion scoring: Files are sorted by file name length ascending, then by file extension.
- File extensions get score boosts depending on the platform. For example ps1/bat/cmd get a boost on Windows and bat/cmd get a negative boost on non-Windows.
- Built-in `git` completions (`terminal.integrated.suggest.builtinCompletions`)
- Built-in `code` and `code-insiders` completions (`terminal.integrated.suggest.builtinCompletions`)
  - ⚠️ The VS Code completions are very basic and not currently context aware, don't spend long on this part. The work in progress is being included since it's better than nothing.

**Comment by aiday-mar** [comment]
I am not sure if I setup my environment correctly to test this plan item. I installed powershell on MacOS, then opened an integrated powershell in VS Code. I was typing `cd`, a completion appeared, and then I expected that pressing `Tab` would accept the completion. Pressing `Tab` made the completion disappear. To accept the completion, I had to use the right arrow key. This seems to contradict the `terminal.integrated.suggest.runOnEnter` setting description, which mentions that the Tab key can be used to accept the result. Am I testing correctly?

https://github.com/user-attachments/assets/8349e811-dbed-4c1a-ba85-8ba9123e0732

**Comment by Tyriar** [comment]
FYI what @aiday-mar was seeing is ghost text for history that is provided by pwsh itself, not us. So this feature is unrelated:

![image](https://github.com/user-attachments/assets/00ac31a4-78f9-4aad-87bc-af8abcf97d90)

**Comment by andreamah** [comment]
Hmm. I can't seem to get completions on linux.


![Image](https://github.com/user-attachments/assets/2784c1ad-1b19-4d32-b144-d08137ab9104)

![Image](https://github.com/user-attachments/assets/75583cb2-ef44-4a1f-8ab3-a2921b51c345)

![Image](https://github.com/user-attachments/assets/976c3e9e-e8a0-4be4-b728-464229588fd0)

@Tyriar do you know what I could be doing wrong?

**Comment by andreamah** [comment]
Currently blocked on this due to the problem above, which might be fixed by https://github.com/microsoft/vscode/issues/223374 in the next release.
