### ISSUE TITLE
Trailing slash in tab title "./" is unnecessary

### ISSUE THREAD

**Issue by robbiewxyz** [microsoft/vscode#223129]
VSCode has this helpful feature where it shows the directory name when two files with the same name are open. If one of those is at the project root it unnecessarily prints a trailing slash after the ".". See the below screenshot:

<img width="514" alt="image" src="https://github.com/user-attachments/assets/1637de84-465f-43a8-af31-07b826d3efcb">

Fixing this would free up some tab bar space and make the directory path formats consistent.

**Comment by benibenj** [comment]
Do you suggest removing `./` or just `/`? I think it would visually look a bit confusing when there would be only a `.` at the end.

**Comment by robinplace** [comment]
> Do you suggest removing `./` or just `/`?

I'd suggest `.`. I'm inspired by the common Unix convention where `.` is used to refer to the current directory.

```
$ ls -la
drwxrwxr-x@ 24 robin  staff     768 Apr 30 13:10 .
drwxr-xr-x@ 51 robin  staff    1632 Sep  2 14:18 ..
drwxrwxr-x@ 14 robin  staff     448 Sep 21 20:21 .git
drwxrwxr-x@  3 robin  staff      96 Oct  4  2023 .github
-rw-rw-r--@  1 robin  staff      67 Apr  8 23:51 .gitignore
-rw-rw-r--@  1 robin  staff       7 Oct  4  2023 README.md
-rwxr-xr-x@  1 robin  staff     296 Apr  9 00:35 build
drwxrwxr-x@  6 robin  staff     192 Apr  8 23:58 src
```
