### ISSUE TITLE
In insiders vscode.dev our extension cannot load files into the workspace anymore

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#223134]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: Current insiders.vscode.dev
- OS Version: Web issue only (repro)

The repro steps for this are entering via the VS Code for education route for insiders.vscode.dev

Steps to Reproduce:

1. Login to ppe.vscodeedu.com with MS credentials
2. From the courses list, select the 'Getting Started' course
3. insiders.vscode.dev should be launched with our extension and course loaded
4. At this point you can already see the errors in the dev console
5. But to see the specific issue select the "Coding Challenge" section
![image](https://github.com/user-attachments/assets/626d2390-b17d-4d2d-96db-ebbed5e96531)
In this section a code editor file should have been opened up in the editor, but it is missing.

We see the following in the dev console when the course is loaded. I don't have a full bead on exactly what is happening here, but we have not been changing the extension this sprint, so it seems to be a recent new issue that is just in insiders and not in stable (which works fine still and does not have the errors).

![image](https://github.com/user-attachments/assets/98fc3073-6907-49cb-87cc-34621cc5c04d)

I took a look at recent issues and this one comment appeared here that might be related? https://github.com/microsoft/vscode/issues/220171#issuecomment-2219842702

**Comment by IanMatthewHuff** [comment]
[insiders.vscode.dev-1721684119886.log](https://github.com/user-attachments/files/16339996/insiders.vscode.dev-1721684119886.log)

Adding the log file here.

**Comment by IanMatthewHuff** [comment]
For comparison, this is the same scenario in stable vscode.dev:
![image](https://github.com/user-attachments/assets/02d3fd51-97f8-4347-a999-ff3bf8104958)

And insiders:
![image](https://github.com/user-attachments/assets/526d067a-42a9-44be-9799-469179ce4d2d)
Note the errors, plus terminal and editor have not opened up.

**Comment by IanMatthewHuff** [comment]
@bpasero Hope you don't mind a direct ping here, but I think you might have context both on the VS Code for Education route and possibly on the issue above?

**Comment by mjbvz** [comment]
@deepak1556 [believes](https://github.com/microsoft/vscode/issues/222193#issuecomment-2243060150) this is related to https://github.com/microsoft/vscode/pull/214588

Looks like we may need to add `blob:` to the `web-worker-ext-host-iframe` iframe content security policy. Taking a look at this now

cc @joaomoreno @bpasero
