### ISSUE TITLE
Search+Replace in project fails

### ISSUE THREAD

**Issue by cstoribal** [microsoft/vscode#223289]
Type: <b>Bug</b>

When doing Ctrl+Maj+F in a large folder (let’s say I search a "keyword"), if I try to replace too quickly the found keywords with another word (of a different size) with Ctrl+Maj+1, VS Code replace the keywords at the place they were found (or that's what I suspect from the errors I get).
But if two or more keywords are found at the same line, any replacement in the line offsets the following keywords by an amount of caracters. However, VS Code will still replace the keywords at the place they were originally found, making a mess with offseted words if the replacement is made too quickly.

Seems related to https://github.com/microsoft/vscode/issues/222031

Does not happen with "replace all"

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1345U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (4.94GB free)|
|Process Argv|--crash-reporter-id ca81abd7-08f7-46d3-bd7b-59b4ed5977bd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Doxygen|bbe|1.0.0
gitlens|eam|15.2.0
git-graph|mhu|1.30.0
prettify-json|moh|0.0.3
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
cmake-tools|ms-|1.18.43
cpptools|ms-|1.21.2
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31094925
refactorc:31101458
pythonrstrctxt:31093869
hdi1a554:31097393

```

</details>

**Comment by andreamah** [comment]
/duplicate https://github.com/microsoft/vscode/issues/166437https://github.com/microsoft/vscode/issues/166437
