### ISSUE TITLE
versioning and release practices

### ISSUE THREAD

**Issue by JayAndCatchFire** [Microsoft/vscode#22321]
I'm confused on the versioning and release practices for VSCode.

- My locally installed executable version is currently at 1.10.2 (via an in-app update from the initially installed version of 1.10.1).
- The latest version that's been tagged is 1.10.1.
- The latest version in the github releases is 1.10.1.
- The latest version in the release/1.10 branch (according to package.json) is 1.10.2.
- The version in the master branch (according to package.json) is 1.11.0.

What's the process or protocol by which a release is sent out to clients if it's not related to git tags or github releases?  I've seen [this wiki page](https://github.com/Microsoft/vscode/wiki/Release-Process), but it may be outdated based on what I'm seeing in the tags, branches, and releases currently.

**Comment by ramya-rao-a** [comment]
- The version in the master branch is always the version we are currently working on, this matches with the version for the insiders build and the upcoming release.
- A release branch is created for every update in the minor version. When there is a patch, we don't create a new branch, we just update the branch that matches major and minor version.
- The tag and github releases should match the latest released version which at the moment should be 1.10.2 Thanks for catching that we didnt update for 1.10.2 Just fixed this.
- Yes, the wiki does look outdated. Assigning to @joaomoreno to update the wiki

@joaomoreno Correct me if I got any of the above wrong

**Comment by JayAndCatchFire** [comment]
That all makes sense to me.  I'm glad I wasn't crazy, missing the tag/release.  👍

**Comment by joaomoreno** [comment]
Yep, we just seem to **constantly** forget to tag every time we release.

I've also slightly updated the wiki. It was mostly correct.
