### ISSUE TITLE
Consumes loads of power

### ISSUE THREAD

**Issue by samsonpaul** [Microsoft/vscode#22326]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|angular-material|1tontech|0.6.0|
|vscode-markdownlint|DavidAnson|0.6.2|
|beautify|HookyQR|0.8.8|
|html-css-class-completion|Zignd|1.0.3|
|angular1-code-snippets|alexandersage|0.0.3|
|vscode-color|anseki|0.2.3|
|theme-onedark|azemoh|0.4.3|
|npm-intellisense|christian-kohler|1.3.0|
|gitignore|codezombiech|0.5.0|
|githistory|donjayamanne|0.1.5|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-npm-script|eg2|0.1.8|
|git-project-manager|felipecaputo|1.0.1|
|vscode-npm|fknop|3.3.0|
|Theme-Blackboard|gerane|0.0.2|
|rest-client|humao|0.12.3|
|Angular2|johnpapa|2.0.3|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|Go|lukehoban|0.6.55|
|MagicPython|magicstack|1.0.7|
|theme-go|mikegleasonjr|0.0.3|
|HTMLHint|mkaufman|0.3.3|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|angular-cli|pkosta2006|1.0.1|
|python|tht13|0.2.3|
|dark-plus-material|vangware|0.2.4|
|Material-theme|zhuangtongfa|2.1.7|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by samsonpaul** [comment]
on it, thanks

**Comment by bpasero** [comment]
Any update?

**Comment by samsonpaul** [comment]
Disabling the all the plugins  but `Go plugging` made a huge difference. So I went ahead and enabled the rest of the plugins one at a time just to find which caused the power mayhem, but non really showed  the signs. It turned out that having "many/all the plugins" running caused the power mayhem. Decided to uninstall most of them and left with  the ones I considered `primary`.

Sorry I got lost in hacking and didn't remember to get leave a feedback on the same sooner

**Comment by bpasero** [comment]
Yeah, if an extension is busy doing things, it is a bit outside of our control. In that case it would be best to report this to the extension causing the CPU spikes if possible.

**Comment by samsonpaul** [comment]
Will try and figure out which one specifically does this and report. Thank you @bpasero

**Comment by samsonpaul** [comment]
Hope its okay if I close  this here for now
