### ISSUE TITLE
Mention shell integration is important for suggest to work

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#223277]
-

**Comment by Tyriar** [comment]
Looks like shell integration wasn't on, I updated the instructions in https://github.com/microsoft/vscode/issues/223130 but will make sure this is mentioned in the setting

**Comment by aiday-mar** [comment]
Issue closed because no longer relevant

**Comment by Tyriar** [comment]
Was going to action this by updating setting text

**Comment by Tyriar** [comment]
Oh this is actually already in the description.
