### ISSUE TITLE
Settings URL handling - "Open Current File as Release Notes" command not working

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#223291]
Testing #223027

* Created a new Markdown file - test.md
* Added the release notes sample to the file and saved it
* Invoked the "Open Current File as Release Notes" command and it failed
      ![Image](https://github.com/user-attachments/assets/3daa0820-1363-4dc6-ada8-07fdab1ff87f)

Not seeing anything in the developer tools console nor in the various output channel logs.

**Comment by alexr00** [comment]
I think that the document can't start with a header like that. To unblock yourself, you can modify one of the existing release notes to include something similar to the release notes.
