### ISSUE TITLE
"The editor is not accessible at this time" when it is

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#223273]
Testing #222238

Screenreader mode is already enabled:

![Image](https://github.com/user-attachments/assets/83d324f0-2086-416c-9592-153ddba770f9)

**Comment by andreamah** [comment]
This also happened to me on windows. I needed to reload the window before the setting took effect.

**Comment by meganrogge** [comment]
Did you have a screen reader enabled at the time that you saw this?

**Comment by meganrogge** [comment]
That message comes from our detection of a screen reader, not just from being in screen reader optimized mode. So, if you had a screen reader enabled at that time, it's an issue with our detection of it. If you did not, this is expected.

**Comment by chrmarti** [comment]
Yes, the text bubble is from macOS' VoiceOver screen reader.

**Comment by meganrogge** [comment]
I can repro - if you enable screen reader mode and haven't reloaded the window, the debug console is created with the editor option of screen reader mode not set. Reloading the window fixes this.

**Comment by meganrogge** [comment]
I haven't heard feedback from users about this and think I recall seeing them reload when this has happened, will ask JooYoung in our weekly sync if this needs to be addressed.
