### ISSUE TITLE
Show progress when enabling/disabling auto update of all extensions

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#223262]
Testing #223091

- Disable Auto Update for All Extensions.
- Enable Auto Update for All Extensions.
- Search for an installed extension.
- Auto Update is not checked. 🐛 

When I clear the search box, sometimes the checkboxes are then checked. Again searching for an installed extension shows the boxes unchecked.

**Comment by sandy081** [comment]
> When I clear the search box, sometimes the checkboxes are then checked. Again searching for an installed extension shows the boxes unchecked

Do you mean the checkbox is not checked when you search for an installed extension? Otherwise it is checked?

**Comment by chrmarti** [comment]
Yes.

**Comment by chrmarti** [comment]
Actually now I just reproduced it without searching. This is after enabling auto update for all:
<img width="1272" alt="image" src="https://github.com/user-attachments/assets/803cd434-f36d-47f2-9247-cf27ef5e43a6">

**Comment by chrmarti** [comment]
Oh...it updated after a while! I also noticed that when I clear the search box it takes a very long time for the Extensions panel to show the installed extensions when I just enabled or disabled auto update for all extensions. There seems to be a performance issue.

**Comment by sandy081** [comment]
Thats right, this action updates all extensions to disable auto update. This is any async operation. I would probably show a progress to indicate that operation is running.
