### ISSUE TITLE
Open Accessibility Help still mentioned after disabling

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#223278]
Testing #222238

![Image](https://github.com/user-attachments/assets/050c754e-811a-438f-bb5c-565a49215dd0)

**Comment by andreamah** [comment]
Did you reload? I noticed that mine was like this, but then I noticed that the description says to reload.

**Comment by meganrogge** [comment]
we create the view once per reload, so there's not much I can do about this besides https://github.com/microsoft/vscode/issues/223282, which seems like a good idea. Closing in favor of that issue.
