### ISSUE TITLE
Upgrade from `findFiles` to `findFiles2New` is a breaking API change

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#223279]
Testing #223154

I'm sure you already know this, but upgrading from `findFiles` to `findFiles2New` is a breaking change since the first parameter goes from `GlobPattern` to `GlobPattern[]`.

**Comment by Tyriar** [comment]
How about `exclude?: GlobPattern | GlobPattern[];` instead?

**Comment by andreamah** [comment]
Yup! I was thinking of supporting both types (where the old one would be deprecated). I edited the original post to reflect this.
