### ISSUE TITLE
Hide private methods/properties

### ISSUE THREAD

**Issue by Rain-io** [Microsoft/vscode#22329]
I would like to ask if it was possible to add a feature which hide private methods/properties of intellisense out of the class in which they are defined in JavaScript ?
We could determinate a private method/properties when it begin with an underscore or/and with the jsdoc.

Thanks for all your work ;)

**Comment by ramya-rao-a** [comment]
I believe this can be an extension candidate.
@mjbvz ?

**Comment by mjbvz** [comment]
Here's more context on this issue: http://stackoverflow.com/questions/42650996/vscode-hide-properties-and-methods-with-an-underscore-to-intellisense/42655204?noredirect=1#comment72532432_42655204

**Comment by mjbvz** [comment]
We can't do the filtering on our side easily since you want a class's private members when working inside of the class itself. This likely has to be provided either by TypeScript or by a TSServer plugin that marks `_VAR` members as private: https://github.com/Microsoft/TypeScript/issues/11976

**Comment by mjbvz** [comment]
Closing as typescript plugin candidate
