### ISSUE TITLE
Expose list of valid language ids to extensions

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#22332]
I apoligize if I've overlooked this, but it would be great if there was an api call that could return a list of valid language ids.

Use case: I just released an extension that allows users to configure commands that open new files with the language mode set. However, without a list of language modes available to the extension, I rely on users to configure a list of languages that they would like to create commands for. If I had a list available through the API then I could use that to automatically generate the commands I need.

**Comment by jrieken** [comment]
tata: [`vscode.languages.getLanguages()`](https://github.com/Microsoft/vscode/blob/joh/eol/src/vs/vscode.d.ts#L4216)

**Comment by hoovercj** [comment]
Thanks! I thought I had seen it but then when I tried searching again I couldn't find it.
