### ISSUE TITLE
Emmet doesn't works with multicursors

### ISSUE THREAD

**Issue by jmpp** [Microsoft/vscode#22337]
- VSCode Version: 1.10.1
- OS Version: Windows Seven Professionnal

Steps to Reproduce:

1. Just open any HTML file.
2. Create multiple cursors and try to use a Emmet snippet.
3. Run "Expand"

Snippet won't expand on multicursors :'(

![Bug example](http://i.imgur.com/CvmZg1Z.gif)

**Comment by ramya-rao-a** [comment]
Tracked in #9571

**Comment by ramya-rao-a** [comment]
@jmpp 
Set `emmet.useNewEmmet` to `true` (in the latest Insiders dated 6/1 or above and eventually in the stable release of 1.13 and higher) to get emmet abbreviation expansions in the suggestion list.
This will work in multi cursor too

For details on this setting read https://github.com/Microsoft/vscode/issues/1952#issuecomment-305390464

**Comment by sant123** [comment]
Hi @jmpp, it works thank you! However, ¿is this going to be implemented by default in a future release?

**Comment by jmpp** [comment]
@sant123 Dunno. Maybe you should ask @ramya-rao-a ;-)

**Comment by ramya-rao-a** [comment]
Yes. Best case scenario is
- We set `emmet.useNewEmmet` to `true` by default in 1.14. Users can fallback to the old model by setting this to `false`
- We remove the setting altogether and only have the new model in 1.15

**Comment by sant123** [comment]
My mistake @jmpp 😂 😂 😂 
Thank you @ramya-rao-a

**Comment by simgooder** [comment]
@ramya-rao-a When I enable this flag, `tab-completions` cease to work in stylesheets.

**Comment by ramya-rao-a** [comment]
@simgooder can you give an example?

**Comment by simgooder** [comment]
To use tab-completions in HTML with multiple-cursors, I turned this setting to `true`. When I move into a stylesheet (`scss`) and attempt to tab complete `display: inline-block;` using the shorthand `dib + [tab]`, it just tabs - no completion.

**Comment by ramya-rao-a** [comment]
In the new emmet model:
-` tab` is no longer bound to emmet expansion.
- you will see emmet expansion in the suggestion list

General notes on suggestion list:
- pressing tab when suggestion list is present, chooses the first item in the suggestion list
- If you have `editor.quickSuggestions` turned off, then the suggestions won't show up as you type. You can still trigger the suggestions by `Ctrl+Space`

I am able to emmet to work in scss file in multi cursor mode using both the suggestion list and via the emmet expansion command

![multi](https://user-images.githubusercontent.com/16890566/27988225-03e55958-63d2-11e7-84f8-6f21a4aaedf5.gif)
