### ISSUE TITLE
[debt] ThemeService and StorageService mixup

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2233]
We have a theme service that doesn't know the currently selected theme and then there is a storage service which, given you know the right constants, allows you to figure that out. The latter seem like an implementation detail of the former.

**Comment by bpasero** [comment]
Ping pong ;)

**Comment by aeschli** [comment]
I see your point, but not sure why this is important. I didn't want to add workbench specific knowledge in the ThemeService. Right now it's stateless and just help loading and apply themes. 

No action planned.

**Comment by jrieken** [comment]
@aeschli Are you saying there should be no easy way to get the current used theme or are you saying it doesn't make sense to have that in the theme service?

**Comment by aeschli** [comment]
If there is a request to have such an API then I can add it. Unless there isn't, no action planned.

**Comment by jrieken** [comment]
please understand this bug as such a request

**Comment by aeschli** [comment]
@jrieken What's your use case?

**Comment by jrieken** [comment]
the html preview part needs to know what the current theme is, it also needs to know when a theme changes. also the SelectThemeAction would benefit from this. 

this is a debt, there should be something better than `let currentTheme = this.storageService.get(Constants.Preferences.THEME, StorageScope.GLOBAL, Themes.DEFAULT_THEME_ID);`

**Comment by aeschli** [comment]
Implemented by bb6f634ff5 and ddd2a37aff

**Comment by jrieken** [comment]
👯
