### ISSUE TITLE
Incorrect Highlighting of Function Parameters in Completion Items

### ISSUE THREAD

**Issue by morgilad** [microsoft/vscode#223341]
#### Description

There appears to be an issue where the highlighted text incorrectly includes function parameters, even though the `filterText` does not contain these parameters. 

In the attached image, it is visible that in the second completion item, the “o” is highlighted within the function parameter, which is incorrect. The `filterText` for that item is `array_rotate_right`, not `array_rotate_right(array, rotate_count)`. The highlighting should be within the function name (which is the `filterText` value).

#### Steps to Reproduce

1. Trigger IntelliSense for a function that has parameters.
2. Observe the highlighting behavior in the completion items.
3. Note that the highlighting incorrectly includes characters within the function parameters.

#### Expected Behavior

The highlighting should be limited to the function name based on the `filterText` value, not extending into the function parameters.

#### Example

- **Incorrect Highlighting**: `array_rotate_right(array, rotate_count)` with “o” highlighted within the parameters.
- **Correct Highlighting**: `array_rotate_right` with “o” highlighted within the function name only.

#### Attached Image

<img width="673" alt="image" src="https://github.com/user-attachments/assets/5ce29313-5a7b-48f2-81dd-b770ff69a50f">

**Comment by jrieken** [comment]
> The filterText for that item is array_rotate_right, not array_rotate_right(array, rotate_count). The highlighting should be within the function name (which is the filterText value).

When using `filterText` we do a best-guess effort to highlight the query characters in the label. Tho, you can use `CompletionItemLabel` to express what a label and what the "signature" is
