### ISSUE TITLE
Selection management

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#223343]
Testing #223152

1) set a selection within a given cell
2) ESC -> cell gets focus
3) Cmd+/ -> selection from step 1 is lost and all content of the cell is selected
4) Arrow-up or down
5) Cmd+/ -> now you have two cells with fully selected content

I would expect that the selection from step 1 is retained/restored. And, if I don't have a selection after step 3, no selection would be visible.

**Comment by rzhao271** [comment]
It looks like step 2 still causes the selection to be lost and step 3 still comments out everything.

**Comment by andreamah** [comment]
pair verified with @Yoyokrazy
