### ISSUE TITLE
Does FindFiles2OptionsNew.maxResults impact performance?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#223395]
Testing #223154

If so, should we mention it?

https://github.com/microsoft/vscode/blob/d4bb523d43261a3ec2c4c9ca01052faeb0a874e7/src/vscode-dts/vscode.proposed.findFiles2New.d.ts#L20-L23

Also, should this have a conservative default value to help developers from misusing it?

**Comment by andreamah** [comment]
The default value for now is 20k, but I'm debating whether it should just be whatever the user sets as the max number of results from search (`search.maxResults`). The default value for this setting is 20k.

**Comment by Tyriar** [comment]
The default should be called out, I was under the impression is was infinite by default
