### ISSUE TITLE
Do we want users to be able to override search.followSymlinks?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#223398]
Testing #223154

`FindFiles2OptionsNew.followSymlinks` seems to exist for this sole purpose. But `search.followSymlinks` defaults to true, so a user likely only ever changes it if it was a problem. So why are we letting extension developers override this?

**Comment by andreamah** [comment]
That's a good point. A big use case for this would be where following symlinks slows down search a lot. If the extension knows that resolving symlinks is not necessary, then they could force-disable for better performance.

**Comment by andreamah** [comment]
I still think that I'm leaning towards keeping it for the reason above. I'm taking the viewpoint where I want to keep the API as loose as possible within reason.
