### ISSUE TITLE
Scrolling is not working on contents section

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode#223382]
Testing #223080

1. Open the Profiles view, and choose a profile.
2. Open settings.
3. Open one extension.
4. When the width of the window is too small, the two finger gesture in Mac to scroll does not work. So i can not scroll. 🐛

<img width="1425" alt="Screenshot 2024-07-23 at 1 45 53 PM" src="https://github.com/user-attachments/assets/eee9bee6-c77e-44cd-bb2d-1a1907d39b7f">

**Comment by paulacamargo25** [comment]
Update: I also tried scrolling up/down with the scroll gesture, and when the pointer is in the content view, it doesn't work either

**Comment by sandy081** [comment]
Scrolling does not work when you scroll on top of the contents section right? If you do scrolling on other areas like **Name** section, it works?
