### ISSUE TITLE
NVDA reads REPL as 'replace'

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#223350]
Testing #222238

Not sure whether this is something in your control, but I noticed that NVDA reads REPL as replace when it's reading this:

![Image](https://github.com/user-attachments/assets/79efa574-894e-44a8-b15f-e693c2eadde4)

Might be a bit confusing.

**Comment by meganrogge** [comment]
Strange, but yeah, I can work around this by removing the acronym. 

Note to self and testers: this appears in both the debug console and debug view's accessibility help dialogs.
