### ISSUE TITLE
Extension hover is often dismissed too early

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#223368]
Testing #223090

The hover widget of the extension is often dismissed too early and making it hard to move cursor to the hover widget and click on the links.

https://github.com/user-attachments/assets/89aff1b2-5c54-45c4-9ed9-3a1b4017a509

From the recording above you can see that I only get it working 1 out of 3 times.

**Comment by Tyriar** [comment]
This is because you hover the scroll bar which dismisses it, currently you need to hold alt to lock the hover.

@sandy081 consider adding the `showHoverHint` option:

https://github.com/microsoft/vscode/blob/b4eb7c94495e25b5dc968a4d3a723346e27f48a3/src/vs/base/browser/ui/hover/hover.ts#L203-L209

We can also remove this `hideOnHover` requirement which I think will be needed to get this to work in your case:

https://github.com/microsoft/vscode/blob/b4eb7c94495e25b5dc968a4d3a723346e27f48a3/src/vs/editor/browser/services/hoverService/hoverWidget.ts#L225

**Comment by sandy081** [comment]
@Tyriar It seems this option `showHoverHint` is not available for `setupManagedHover`

https://github.com/microsoft/vscode/blob/dde43f978fc93d84249fe16f755076266e4937fc/src/vs/base/browser/ui/hover/hover.ts#L65

**Comment by Tyriar** [comment]
@sandy081 will merge https://github.com/microsoft/vscode/pull/223765 after we branch off

**Comment by rebornix** [comment]
https://github.com/user-attachments/assets/f4dde175-0b5d-4f84-af0e-7035cfe9813b

Another case for scm view. @Tyriar does your fix cover this too?

**Comment by Tyriar** [comment]
@rebornix there you're hovering an element with a different hover which is why it's dismissed, related but different case and i think we're acting as designed there.

**Comment by rebornix** [comment]
@Tyriar in the recording I was attempting to move cursor into the hover so I can click on the button in the rich hover. It seems we don't have a large enough "hit area" in general and the hover is easily dismissed.

**Comment by mjbvz** [comment]
Still seeing this. If there's a scrollbar like below I can't move the cursor to the hover without it getting dismissed: 

![Image](https://github.com/user-attachments/assets/f160d1e8-78c6-4353-903e-06f05215320f)



Holding alt works

**Comment by sandy081** [comment]
Fix here is to show the hint to Hold Alt and it seems not to be shown. 

@Tyriar I have set the flag `showHoverHint` while showing the hover and it is still not shown.

https://github.com/microsoft/vscode/blob/d1388fd24fc0acf17ae1f759e85c1acf559ed759/src/vs/workbench/contrib/extensions/browser/extensionsWidgets.ts#L545-L576

**Comment by Tyriar** [comment]
Seems to show unless the extension is verified:

<img width="733" alt="Screenshot 2024-08-28 at 8 23 38 AM" src="https://github.com/user-attachments/assets/e620717c-f90f-44f5-9bc7-d23ad6092c0d">
