### ISSUE TITLE
Automatically detect .ejs templates (and other common template extensions) as HTML file

### ISSUE THREAD

**Issue by nicolehaugen79** [Microsoft/vscode#22333]
Today, if you are working with EJS as your server side template engine for node.js, these html files have an .ejs extension. As a result, VS Code doesn't recognize by default that this is an html file and then you don't get intellisense when writing html tags. 

VS code has a drop-down at the bottom of the window that allows you to switch between treating the file as "Plain Text" to "HTML" - however, I didn't notice this drop-down right away. Ideally, for a Node.js dev, it would be nice to auto-detect some of these common extensions so that we treat them as HTML by default - .ejs is just one common extension.  There are others that we should treat the same way, such as .pug.

**Comment by aeschli** [comment]
The problem with template languages is that they are always more that html and there are special rules for validation, colorization and formatting. It would be better if there were a proper support for it.
I add it now, but will have to remove it again if bugs starts to arrive pointing to an incomplete support of the ejs language.
