### ISSUE TITLE
Extension update - review extension does not always focus the changelog tab

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#223318]
Testing #223090

1. Close all opened editors
2. Open the Extensions viewlet, hover on a extension that is not auto-updated, and click on the "review the extension" link. This will open the extension details in the editor and will focus the "Changelog" tab.
3. Click on the "Details" tab in the extension editor
4. Click on the "Update"button which will show a warning dialog
5. Click on the "Review" button 
    * This should focus the "Changelog" tab but it does not

**Comment by sandy081** [comment]
Good catch!

**Comment by sandy081** [comment]
This is available only on an extension whose currently installed version has no code and the version to be updated has code.

**Comment by DonJayamanne** [comment]
Thats exactly what I've done, if you have a look at `testupdates1`, you'll see that it doesn't have any code in the first version, but second version has code.
https://marketplace.visualstudio.com/items?itemName=donjayamanne.testupdates1

**Comment by sandy081** [comment]
Gotcha.. Please enable auto update on this extension then. Or click on Update button.
