### ISSUE TITLE
`workbench.action.terminal.sendSequence` keybinding does not trigger on linux

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#223374]
Testing #223130

On Linux, `workbench.action.terminalsendSequence` doesn't fire correctly on `ctrl+space` because it checks for `terminalShellType == 'pwsh'`. However, when looking at the context keys, `terminalShellType` is not set

**Comment by Tyriar** [comment]
Things have changed here, soon it won't be sent to the shell at all as the old pwsh one will get removed eventually.
