### ISSUE TITLE
Resizing stacktrace UI causes a line to be hidden

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#223373]
Testing #223148

There's only one frame in the stack trace, pull down to resize and notice how a line goes missing from the editor.
Line 116 vanishes

![Image](https://github.com/user-attachments/assets/4f3947a6-51db-4d57-a57e-bc4fb1cd3896)

**Comment by DonJayamanne** [comment]
@connor4312 has this feature been removed or moved behind some experimental flag. I can no longer see this.
I recall some mention about discussions around the UX, nothing beyond that, Apologies if i missed something.

**Comment by connor4312** [comment]
This is still available with the same steps, but note that if the top stack frame is the same location as the message (e.g. a failing assertion within a test) then it's omitted
