### ISSUE TITLE
TextSearchQueryNew has conflicting options

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#223310]
Testing #223154

From the API:

```ts
export interface TextSearchQueryNew {
		/**
		 * The text pattern to search for.
		 */
		pattern: string;

		/**
		 * Whether or not `pattern` should match multiple lines of text.
		 */
		isMultiline?: boolean;

		/**
		 * Whether or not `pattern` should be interpreted as a regular expression.
		 */
		isRegExp?: boolean;

		/**
		 * Whether or not the search should be case-sensitive.
		 */
		isCaseSensitive?: boolean;

		/**
		 * Whether or not to search for whole word matches only.
		 */
		isWordMatch?: boolean;
	}
```

What is the behavior supposed to be in the following cases:
- The pattern contains `\n`.
- The pattern contains `\n` and `isMultiline` is false.
- The pattern is a regex and `isCaseSessitive` is false.
- The pattern contains whitespace and `isWordMatch` is true.

**Comment by andreamah** [comment]
> The pattern contains \n.

If regex is not on, it just looks for `\n` literally. 

> The pattern contains \n and isMultiline is false.

I believe that this actually acts as if `isMultiline` is true (if I'm interpreting [this](https://github.com/microsoft/vscode/blob/2d6df400a7ee2c3bc458ff23b18b9df4d6500ad6/src/vs/workbench/services/search/common/queryBuilder.ts#L308-L310) code correctly). Any time that you have regex enabled and explicitly match a newline, it will be multi-line. I should probably document this.

> The pattern is a regex and isCaseSessitive is false.

Any characters in the regex will also match the other case. ie: `[a-z]` should also match all characters, not just lowercase letters.

> The pattern contains whitespace and isWordMatch is true.

It will look for the whitespace, and will look for line boundaries on either side of the search string.

**Comment by andreamah** [comment]
I can also add extra examples for corner cases so that this is more clear.
