### ISSUE TITLE
Configuring a non-existing browser alias fails silently

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#223349]
Testing #220989

Not sure if this is possible, but I set the `workbench.externalBrowser` to `firefox` even though I don't have Firefox... then I tried to open something and nothing happened. I was confused because I thought I had Firefox installed, but I guess I remembered incorrectly!

I think something like this is increasingly important in the workspace-setting level. Sure, the protection of this is behind Workspace Trust... but I don't seem to get any notification or indication that there's a setting applied that influences how VS Code opens the browser or if it's going to no-op.

Considering this setting influences things like user auth flows, I think we should try to do something here. I was surprised that no browser was opened when I attempted to log in to a GitHub extension... which makes sense if this setting is set to something invalid.

**Comment by bpasero** [comment]
I think this might be reported as https://github.com/sindresorhus/open/issues/272 and misses a fix or workaround.

**Comment by TylerLeonhardt** [comment]
It appears that this is fixed by opening the default instead of what is configured. That makes sense to me.
