### ISSUE TITLE
Terminal Scrollbar: Right Click on scrollbar does paste not scroll

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#223358]
Testing #223132

Right clicking on the scrollbar does a paste into the terminal, as if I was in any other part of the terminal. Given the behavior of scrollbars in the editor I expected the terminal to scroll at a minimum (and a context menu might be nice).

**Comment by Yoyokrazy** [comment]
right clicking on the scrollbar itself will still run the paste action, right clicking on a different part of the scrollbar (that we aren't scrolled to) scrolls as expected based on the issue.

https://github.com/user-attachments/assets/8724e674-c228-4b33-b478-2589b48cfe5f

**Comment by rzhao271** [comment]
I see a context menu after right-clicking in a pwsh terminal. I'm unsure how to get right click to paste directly.

**Comment by Tyriar** [comment]
@rzhao271 it depends on the `rightClickBehavior` setting.

**Comment by rzhao271** [comment]
Confirmed that a single right click scrolls.
A double right click still pastes.
