### ISSUE TITLE
C++14 digit separators are not properly highlighted

### ISSUE THREAD

**Issue by teki** [Microsoft/vscode#22339]
Digit separators: https://en.wikipedia.org/wiki/C%2B%2B14#Digit_separators

- VSCode Version: 1.10.2
- OS Version: OSX 10.12.3

Steps to Reproduce:

C++ source code:
t.cpp
```
const int a = 1'000'000;
const int b = 1'000;
const int c = 1;

int main(int argc, char** argv)
{
    return a + b + c;
}
```

This will compile without any error with:
`clang++ -Wall -std=c++14 t.cpp`

but looks like this:
<img width="419" alt="screen shot 2017-03-10 at 10 15 29 am" src="https://cloud.githubusercontent.com/assets/5516/23775068/e1fe0f8e-057a-11e7-919e-29ff280f7e13.png">

**Comment by sean-mcmanus** [comment]
The bug has been fixed with the latest atom/language-c (as of Feb 2nd). Can someone get an updated version into the Insiders build?
