### ISSUE TITLE
alt+f2 doesn't show console info if debug session is done

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#223352]
Testing #222238

1. Make a js file at the root that console.logs something.
2. Make a launch config to run it using node like:
```
		{
			"name": "Run Test JS file 1",
			"program": "${workspaceFolder}/test1.js",
			"request": "launch",
			"skipFiles": [
				"<node_internals>/**"
			],
			"type": "node"
		}
```
3. Run it and see the logs persist in the debug console.]
4. Try to use alt+f2 to read it
5. 'no debug session is active'

![Image](https://github.com/user-attachments/assets/dd18e6e8-cd9c-46f4-9a78-6ddccdeab5a7)

**Comment by meganrogge** [comment]
@connor4312 is there a way to get the `replElements` from an inactive session?

**Comment by connor4312** [comment]
Reviewing the code some more I think the more reliable way to get the displayed session is to use `replView.tree.getInput()`. Currently it uses viewModel.focusedSession which won't include ended sessions as Andrea found

**Comment by meganrogge** [comment]
I think that will be a little involved, so deferring
