### ISSUE TITLE
I'm not aware of an ".ignore" file?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#223396]
Testing #223154

Is this a thing?

https://github.com/microsoft/vscode/blob/d4bb523d43261a3ec2c4c9ca01052faeb0a874e7/src/vscode-dts/vscode.proposed.findFiles2New.d.ts#L26

When I try search for it I only find results talking about `.gitignore`?

**Comment by andreamah** [comment]
This is supported on the ripgrep side. See: https://github.com/BurntSushi/ripgrep/blob/58e7d2ea6375860fa09a043d6a1ba20518dfb462/GUIDE.md#L180-L192

**Comment by Tyriar** [comment]
Is there enough for a developer to make that link? I did a quick web search and couldn't figure it out from that and therefore wasn't sure about format, etc.

**Comment by andreamah** [comment]
I can add a doc comment that tells the user how `.ignore` files are formatted. I think that the main motivation behind this is for patterns that the user would want search to ignore, but not git to ignore (?).
