### ISSUE TITLE
How do I do Edge and Chrome flavors?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#223351]
Testing #220989

For `workspace.externalBrowser`...

I don't really wanna put in an absolute path but I wanna do like `edge-dev` `edge-canary` `chrome-canary` or whatever and that "just works".

**Comment by connor4312** [comment]
That's the syntax of js-debug and I have a package to do that: https://www.npmjs.com/package/@vscode/js-debug-browsers If there's interest I could make that slightly more generic for usage here.

**Comment by bpasero** [comment]
Since we are using https://github.com/sindresorhus/open here, I would suggest to open a PR to them to support this. For the time being I suggest to use the path to the executable.
