### ISSUE TITLE
git autorefresh is  Invalid

### ISSUE THREAD

**Issue by jjj-guo** [microsoft/vscode#223322]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91.1
- OS Version: Apple M2 Pro

Steps to Reproduce:

1. When I Modify a file,the git not refresh
<img width="374" alt="12" src="https://github.com/user-attachments/assets/e664b369-0066-46dd-9a3e-173eea86d632">
2.Even if I set "git.autorefresh": true, it's still ineffective.I currently have to manually click refresh myself.

**Comment by xitice** [comment]
+1

**Comment by lszomoru** [comment]
Could you please use the following [wiki page](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues) to collect and share the file watcher logs? Thanks!

**Comment by jjj-guo** [comment]
I don't know how to use this, today I updated the latest vscode version still has the above problem.It is an occasional problem that is not easy to monitor

**Comment by lszomoru** [comment]
Could you please try setting the `typescript.tsserver.experimental.useVsCodeWatcher` setting to `false`? 
Does that resolve the issue? Thanks!

**Comment by jjj-guo** [comment]
> Could you please try setting the `typescript.tsserver.experimental.useVsCodeWatcher` setting to `false`? Does that resolve the issue? Thanks!

It's still invalid.

**Comment by lszomoru** [comment]
@jjj-guo, could you please implement the steps from [the wiki page](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues) and share the logs? Thanks!
