### ISSUE TITLE
Saving an new profile focuses back to the curent profile

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#223375]
Testing #223080

- In the new profile editor, hit "new profile"
- Save the profile
- 🐛 the default profile is focused back, I would expect to stay on the same profile

**Comment by sandy081** [comment]
It works for me - newly created profile is focused. Can you please provide the exact steps you followed to repro?

**Comment by connor4312** [comment]
I can't repro this. Maybe related to the weird state in #223378 🤷
