### ISSUE TITLE
QuickPick doesn't consistently honor selectedItems in VS Code Insiders 

### ISSUE THREAD

**Issue by robertohuertasm** [microsoft/vscode#223363]
Does this issue occur when all extensions are disabled?: Yes

If we show a `QuickPick` with `selectedItems` by using a command being executed from the `command palette` everything seems to work fine. But if we try to execute this command from an `View Action` or a context command in a tree, the `QuickPick` selection will flip from selected to unselected.

I was able to reproduce this in Insiders only. Stable seems to be working fine, so it may be a regression. I tested this in Mac, Windows 11 and WSL2.

[Link to repository to reproduce the issue](https://github.com/robertohuertasm/quickpick-insiders-issue). The readme explains the steps to reproduce the issue as well.

https://github.com/user-attachments/assets/f2a7c810-e86e-41f4-81a9-138e3db35860

Tested in:

Version: 1.92.0-insider (Universal)
Commit: 89690b9d76a88fab676d26651134a1ffa4562732
Date: 2024-07-19T05:03:57.939Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

---

Version: 1.92.0-insider (user setup)
Commit: 22e3447b4b410dcf8426bf70743c5dd4030d6122
Date: 2024-07-23T05:03:52.385Z
Electron: 30.2.0
ElectronBuildId: 9884022
Chromium: 124.0.6367.243
Node.js: 20.15.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**(Both with WSL2 and directly with Windows)**

The only similar issue I found was #209132. Unsure if it's related or not.

**Comment by robertohuertasm** [comment]
While I was testing I have discovered that if I set the `selectedItems` after calling `quickPick.show()` everything works.

So instead of [this](https://github.com/robertohuertasm/quickpick-insiders-issue/blob/master/src/extension.ts#L16-L17):

```ts
quickPick.activeItems= selectedItems;
quickPick.show();
```
If we do this:

```ts
quickPick.show();
quickPick.selectedItems = selectedItems;
```
Then it works.

Not sure how the fact of executing the command from the command palette makes it work regardless of the order.

**Comment by robertohuertasm** [comment]
Hi @TylerLeonhardt, thank you for the quick fix! Can we assume that this fix will be in the next stable release?

**Comment by TylerLeonhardt** [comment]
@robertohuertasm yep! And we'd love confirmation from you in tomorrow's Insiders that it's fixed if you don't mind!

**Comment by robertohuertasm** [comment]
@TylerLeonhardt sure! You can count on it!

**Comment by robertohuertasm** [comment]
@TylerLeonhardt, good news! I can confirm it works! Thank you so much for this fix. 🙇🏻
