### ISSUE TITLE
Would be useful to add a space after completion

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#223313]
Testing #223130

In certain cases I would find it useful to add a space after the completion. I typed `c` in the terminal. One of the completions was `cd`. I typed `Enter` in order to select this completion. The completion `cd` was inserted into the terminal. I thought at this moment that it would have been nice for an additional space to be inserted after `cd` so that I could continue typing the path.

https://github.com/user-attachments/assets/48d79de2-132a-483e-b6ca-c159fbd37fd1

**Comment by Tyriar** [comment]
I hadn't considered this. It's a little more complicated than just a blanket rule though but maybe it should be based on the type of completion. For example commands (cd), files, but not directories. I wonder if that's just going to make everything feel a little inconsistent 🤔
