### ISSUE TITLE
An explicit way to restart TypeScript service (tsserver)

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#22335]
VSCode sometimes displays ghost TypeScript errors, and it's not that rare in my experience. For example, I have something underlined in red in VSCode but if I run `tsc` on the project, it compiles fine.

Ideally, these situations wouldn't happen but as long as they do in practice, it would be good to have a command to reload tsserver. For example, WebStorm has this piece of UI:

![image](https://cloud.githubusercontent.com/assets/101152/23774445/f6161b26-0523-11e7-8c91-8142b144c855.png)

There is "TypeScript: Reload Project" command in VSCode but I didn't observe any effect of it.

VSCode 1.10, Windows 10.

**Comment by OliverJAsh** [comment]
Also related https://github.com/Microsoft/vscode/issues/22614

**Comment by mjbvz** [comment]
@OliverJAsh Can you please also open a bug about the ghost errors you are seeing. I'd like to look into that issue

**Comment by rjdestigter** [comment]
I'm having similar issues. I ofthen have to restart the editor after adding a declaration file to the project or checking out to a different branch with updated/different declaration files.

```
Version 1.18.0
TypeScript 2.6
```
