### ISSUE TITLE
Focusing on a node doesn't read the level

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#223353]
Testing #222238

> If you have an element focused (or its child - only up to one layer deep), the view opens to that element

I tried this:

1. Use the code:
```
const obj = {
    one : {
        two: {
            three:{
                foo:'bar'
            }
        }
    }
}
console.log(obj);
console.log('done');
```
2, Set a breakpoint at the last line.
3. Try to open the accessible view when focused on `three`
4. The dialog does not show `three`

![Image](https://github.com/user-attachments/assets/dbb82ab5-1503-41d2-8c18-4193e8c87769)

**Comment by meganrogge** [comment]
This is a known issue that we don't plan to fix due to performance implications - `If you have an element focused (or its child - only up to one layer deep), the view opens to that element`
