### ISSUE TITLE
alt+tab needs to open any editor regardless of group

### ISSUE THREAD

**Issue by boldwade** [Microsoft/vscode#22338]
- VSCode Version:
Version 1.10.2
Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
Date 2017-03-08T14:02:52.799Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:
Windows 10

Alt+tab needs to open recently used editor REGARDLESS of group. I understand there is a showAllEditors command that you can map to alt+tab. But that's NOT the same thing.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by boldwade** [comment]
I tried to use the search but couldn't find anything. Would you mind linking the related already reported issue. Thanks.
