### ISSUE TITLE
Should ExcludeSettingOptions be an enum?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#223386]
Testing #223154

There are 3 options:

https://github.com/microsoft/vscode/blob/d4bb523d43261a3ec2c4c9ca01052faeb0a874e7/src/vscode-dts/vscode.proposed.findTextInFilesNew.d.ts#L112-L128

Why not `searchExclude`? What if we add another exclude type in the future?

**Comment by andreamah** [comment]
What do you suggest we have instead of an enum? We could probably just add a new field for only `searchExclude` if we ever go that route (which is pretty unlikely I think).

**Comment by Tyriar** [comment]
`excludeSettings: { files?: boolean, search?: boolean}`?

**Comment by andreamah** [comment]
Hmm. I guess this runs into the same issue as the ignore files: someone could set something that is invalid (`excludeSettings: { files: false, search: true}`). With this, we guide the user through valid combinations.

I guess you could argue that it's not very flexible, but after discussing with others, I don't think that there's any plans to support globs that apply to search, but show up in the explorer (at least sourced from the settings).

**Comment by Tyriar** [comment]
Why would `files: false, search: true` be invalid? Isn't it just atypical?

**Comment by andreamah** [comment]
We currently don't support something like that via the UI. We would also need to tweak the code a little bit if we were to support this, as it only looks for search excludes if file excludes are enabled. 

@roblourens do you think that it makes sense to support `search.excludes` without `files.excludes` via the API? I think we discussed something like this before. Someone could make the argument that, since this is an API, it should be more flexible than the UI options.

**Comment by roblourens** [comment]
I don't think it makes sense, I think it's just assumed that search excludes build on top of file excludes. The setting says "Inherits all glob patterns from the Files: Exclude setting".

**Comment by andreamah** [comment]
Yeah, that makes sense to me too.  I don't see us ever changing that, and `findFiles`/`findTextInFiles` are meant to very much be "leverage vscode's search" type of thing. I don't really see a use case for someone only needing the `search.excludes` and not the `flles.exclude`. Opinions @Tyriar ?

**Comment by Tyriar** [comment]
@andreamah fine here 👌
