### ISSUE TITLE
Extensions - Auto Update button feedback

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#223320]
Testing #223090

![Image](https://github.com/user-attachments/assets/ae3886f8-25a9-4c67-a2bc-9728287c295b)

Should the checkbox only change state if the user clicks on it? clicking on the "Auto Update" label also updates state.

**Comment by sandy081** [comment]
It is consistent with other check box interaction in our UI, for eg., in the settings editor - clicking on the description also toggles the check box. What is missing here is hover feedback.
