### ISSUE TITLE
Open to the side action is not working properly

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode#223380]
Testing #223080 

When i am creating a Profile:
1. Select a copy from: `Python`
2. In the case of Settings the default option selected is python, i click on `Open to the side Action`
3. It will open the setting for Python
4. Close the settings.
5. Change the source to default, and click again `Open to the side Action`
6. It opened again the `Python Settings` and not the `default settings`. 🐛
<img width="1170" alt="Screenshot 2024-07-23 at 1 39 24 PM" src="https://github.com/user-attachments/assets/53ed4aaf-d67c-4849-8275-128f071aceae">

**Comment by sandy081** [comment]
Good catch!
