### ISSUE TITLE
Code showing Errors in extension repository after updating launch and other files.

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#22331]
I have tried updating the launch.json for code settings sync and now getting alot of 100+ errors in JS when compiled from TS in out folder.

```
git clone https://github.com/shanalikhan/code-settings-sync.git
cd code-settings-sync
npm install
code .
```

Also configuration is at version 0.1.0

https://github.com/shanalikhan/code-settings-sync/tree/master/.vscode

**Comment by mjbvz** [comment]
From the description, this sounds more like a build issue for your extension than a VSCode issue.

Please try disabling all extensions and reproducing the issue. If you still see errors, describe the exact repo steps that lead up to this and share the errors themselves
