### ISSUE TITLE
... button should stay visible when opening context menu

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#223302]
Testing #223080

![Image](https://github.com/user-attachments/assets/cf229660-21ca-4eb8-95f5-b927e944207f)

Just like here:

![Image](https://github.com/user-attachments/assets/38fed76c-b222-4131-91a3-7d3c1360e285)

**Comment by sandy081** [comment]
I cannot reproduce it on Mac. I suspect this is tree/toolbar related issue in windows? 

@hediet Can you please check if you see similar behaviour in other trees?

**Comment by hediet** [comment]
I don't know of other trees that have such a context menu button.
Also, it reproduces consistently on all windows devices.

**Comment by sandy081** [comment]
Ok, I can reproduce this with custom menu (not with native menu). 

@sbatten Any idea how this should get fixed?

**Comment by hediet** [comment]
I think this got closed by mistake?

**Comment by sandy081** [comment]
@sbatten A friendly ping for your insights here.

**Comment by sbatten** [comment]
This is the property that needs to be set on the dropdown for this to stay visible: https://github.com/microsoft/vscode/blob/d91b89d9a831b9ba8790dd020b094abe225d02f5/src/vs/base/browser/ui/dropdown/dropdown.ts#L169

**Comment by sandy081** [comment]
@sbatten 

Using this option is causing following behaviour. Menu is getting trimmed.

![Image](https://github.com/user-attachments/assets/8db4bed1-e9e7-41bf-8e9f-3702523efc55)

**Comment by sbatten** [comment]
@sandy081 yes, unfortunately that's how it works with the shadow dom. You either need to tweak the parent tree to avoid overflow clipping or live with the item disappearing.

**Comment by hediet** [comment]
I think this should not be closed, as it is a true UI bug.

I understand that there might be more important bugs to fix, but this is very basic UI which I think we have to get right.
