### ISSUE TITLE
Can't open a11y help for focused chat response if notebook is also open

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#223331]
Testing #222240

1. Open a notebook in the editor
2. Focus a chat response
3. Alt + F1
4. :bug: a11y help appears for notebook, I have to close the notebook before I can get a11y help for chat

**Comment by meganrogge** [comment]
@amunger need a stricter `when` clause here I think https://github.com/microsoft/vscode/blob/b95c4b532ee92378992aa2d032f3584ac7ac17e1/src/vs/workbench/contrib/notebook/browser/notebookAccessibilityHelp.ts#L19
