### ISSUE TITLE
Hover shows zero files changed even though opening the commit shows the files diff

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#223305]
Testing #223106

Hover shows zero files changed even though clicking on the commit shows multiple files changes

https://github.com/user-attachments/assets/c7c7ce67-0739-4be9-9b62-613712ac72f3

**Comment by lszomoru** [comment]
This has already been fixed. Could you please confirm that you are able to reproduce with the latest Insiders?

**Comment by sandy081** [comment]
I can reproduce the issue on latest insiders still.

**Comment by sandy081** [comment]
This seems to be fixed after updating git to latest version ie., `2.45.2`
