### ISSUE TITLE
Branch name is not included in the hover

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#223303]
Testing #223106

https://github.com/user-attachments/assets/5b7a4588-edab-44b1-9c07-d1e55f74fb74

Check that branch name is not included when hovered on commit 1

**Comment by lszomoru** [comment]
Technically speaking from a git perspective a branch is just a pointed to a particular commit. That is why currently the branch name is only included in the hover of the commit where a branch points to. I will keep the issue opened to gather more feedback.

**Comment by lszomoru** [comment]
Closing this issue as the "Incoming/Outgoing" section has been removed.
