### ISSUE TITLE
Error: Unable to find repository for current working directory on a windows VM

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#223432]
Testing #223068

I'm on a windows VM on my mac, and I see this error regardless of where my integrated terminal is rooted:
![Image](https://github.com/user-attachments/assets/188d6577-4b83-40ce-a4ff-3df93c259fc7)

I DO NOT see this error on non-VM windows install.

**Comment by lszomoru** [comment]
@bhavyaus, are you still able to reproduce this issue?
How exactly did you open the folder/workspace in the VM?
