### ISSUE TITLE
ReferenceWidget does not dispose _previewModelReference on dipose

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/vscode#22349]

**Comment by ramya-rao-a** [comment]
Can you provide details about your scenario?

**Comment by akosyakov** [comment]
@ramya-rao-a For monaco i've build a custom text model resolver service that counts references to a resolved model and dispose the model when reference count is zero and then i've noticed that if i use find references when there is always one undisposed reference. After skimming through the code it seems to me that `ReferenceWidget. _previewModelReference` is only disposed when the next reference is revealed, but never when the widget is disposed.

**Comment by jrieken** [comment]
Nice find. Thanks @akosyakov

**Comment by alexandrudima** [comment]
Looked at the diff, appears to correctly dispose the `previewModelReference` in the `dispose()` method
