### ISSUE TITLE
Does not announce inline values

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#223429]
Testing #222238

https://github.com/user-attachments/assets/3ce59bc5-1cf9-4191-8fa4-ec92c87810d9

**Comment by meganrogge** [comment]
Thanks for the gif. I think this issue is about the inline values that we show as a decoration not getting announced by the screen reader? If so, I mentioned this to @connor4312 in standup the other day. 

In order to hear the changed watch value here, `v`, you'd have to step over or continue.
