### ISSUE TITLE
VSCode hangs randomly while idling

### ISSUE THREAD

**Issue by mdeter** [Microsoft/vscode#22344]
- VSCode Version: 1.10.2
- OS Version: Ubuntu 16.04.2 LTS

Steps to Reproduce:

1. Launch VSCode and have some files in the file tree and some open in tabs.
2. Wait between 1 minute and 1 hour.  Editing files is not required.  User input is not required.
3. VSCode hangs.  Requires kill -9 of session leader PID and a restart of code.

This has been happening since 1.8 or so, but it's become much more frequent with 1.9 and 1.10.  Basically VSCode ALWAYS hangs.  It's just a matter of time.  100% reproducible.

I unloaded all my extensions but the hangs persist.  Not extension related.  Also doesn't seem related to the number of files in the file tree.  (large tree of ~4000 files and small directory with 10 files both lead to hangs)

I'm not sure which process is hanging or how to get a call stack of the hang.  Please advise and I can provide more info.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by mdeter** [comment]
Yes, I downloaded the insiders build and the issue is still present.  It seemed less willing to hang while idling.  But I opened a few python files and it hung while I was editing them.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by mdeter** [comment]
As mentioned in the original post, I disabled extensions to insure they were not the cause.  I used the UI originally.  I re-tested with "--disable-extensions" and it still hangs.  Definitely a bug in the editor not the extensions.  Sometimes it hangs within 5 minutes, sometimes it take a little longer.

**Comment by bpasero** [comment]
@mdeter how about running `code --disable-gpu`?

**Comment by mdeter** [comment]
--disable-gpu doesn't help.

**Comment by bpasero** [comment]
@mdeter does it still reproduce? does it happen with any file you open?

**Comment by mdeter** [comment]
Yes, this bug is still present in 12.1.  It doesn't seem to matter what kind of file I work on, although I am mostly editing C and Python files.  The source tree is very large (75k files).  Maybe that has something to do with it?  It's odd, because sometimes it will hang very soon after opening (within an hour) and other times it will last the whole day (8-10 hours) without hanging.  But unless I close it myself, it will eventually hang given enough time.

**Comment by mdeter** [comment]
I am using 1.12.2 now and have not seen the hang so far.  Too early to close this, but I will check back in a while longer with another update.  *crosses fingers*

**Comment by mdeter** [comment]
Defect still present.  3 hangs today alone, all within an hour of launching.  (One time the window didn't even finish initial startup painting before it hung.)  Version 1.12.2 with all plugins disabled.  I now wrote a script which kill -9's the hung process and restarts code because it happens so often.  :(

**Comment by bpasero** [comment]
Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line - NOT the integrated terminal of Code)
    - if it does not reproduce with extensions disabled, you can stop testing and report this!
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`
