### ISSUE TITLE
 AbstractMirrorModel.getPositionFromOffset: Model is disposed

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#2234]
Issue Id: <b>70b18577-7bef-134a-009f-883d9af52536</b><br /><br />*Versions* <br />- 0.10.6-release<br />-  dfc08dc9edf6607483b193bf934d3badc3fa2e11<br />*Stack* <br />Error: AbstractMirrorModel.getPositionFromOffset: Model is disposed<br />[/vs/editor/common/model/mirrorModel.ts#L130:9 (AbstractMirrorModel.getPositionFromOffset)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/editor/common/model/mirrorModel.ts#L130:9 (AbstractMirrorModel.getPositionFromOffset))<br />[/vs/languages/json/common/jsonWorker.ts#L174:37 (JSONWorker.doValidate)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/languages/json/common/jsonWorker.ts#L174:37 (JSONWorker.doValidate))<br />    at Array.forEach (native)<br />[/vs/languages/json/common/jsonWorker.ts#L169:41 (JSONWorker.doValidate)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/languages/json/common/jsonWorker.ts#L169:41 (JSONWorker.doValidate))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1127:0 (_notify)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1127:0 (_notify))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1311:0 (_run)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1311:0 (_run))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1127:0 (_notify)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1127:0 (_notify))<br />

**Comment by aeschli** [comment]
Now with the JSON language in an extension this won't happen in VS code anymore. However, other legacy modes Monaco might be impacted

The JSON worker gets the mirrorModel from the resourceService. It always gets it new on every 'validate', so it looks like a bug in the resourceService that it would hand over a disposed model.

**Comment by jrieken** [comment]
We don't have that code anymore
