### ISSUE TITLE
Debug console does not announce type

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#223417]
Testing #222238

![image](https://github.com/user-attachments/assets/4d0df614-3036-4128-bb26-096cd76c7e25)

In the above scenario, one is string and the other is integer, but the type is not announced.

**Comment by meganrogge** [comment]
since the user is requesting the variable, they know what type it is. i'll ask the screen reader users I work with if this is something they'd like to handle differently, closing for now.

**Comment by karthiknadig** [comment]
This issue might be unique to python, as the type might not be known until runtime.
