### ISSUE TITLE
Can't `cd` up a directory

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#223404]
Testing #223130

Repro:
1. Type `cd ..` (suggest widget shows `..`)
2. Hit `enter`

:bug: => replaces `cd ..` with `..`

**Comment by sbatten** [comment]
Btw this is not 100% repro, not sure what the condition is but once I'm stuck, I have to dismiss the suggest widget to get out of it

**Comment by Tyriar** [comment]
I haven't seen this, could you check the prompt status bar item?

![image](https://github.com/user-attachments/assets/92155385-c987-412e-92b0-0a99341cdfb3)

Sometimes the shell integration decoration is on the wrong line if you have a multi-line prompt as well which makes everything fall apart.
