### ISSUE TITLE
Integrated Terminal Touch Scrolling Does Not Work

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#22348]
Using a surface running Windows 10, I am unable to scroll the integrated terminal using the touchscreen. Other elements such as the debug console can be scrolled properly.

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/594

**Comment by Tyriar** [comment]
Basic touch scrolling should now work, just not ballistic scroll which is tracked in https://github.com/xtermjs/xterm.js/issues/594
