### ISSUE TITLE
Repeats breakpoint announcement twice

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#223431]
Testing #222238

This is the same recording as in #223429 . It seems to be announcing the breakpoint twice. Not sure if this is a issue.

https://github.com/user-attachments/assets/3ce59bc5-1cf9-4191-8fa4-ec92c87810d9

**Comment by meganrogge** [comment]
I noticed this too, @connor4312 any idea why this happens? It's particularly problematic because disrupts the `alert` of the watch variable info.

**Comment by connor4312** [comment]
That seems to be coming from here. Maybe we just remove the line content there? That happens after we call `stackFrame.openInEditor` so we know the line will just have been focused at that point

https://github.com/microsoft/vscode/blob/8a82c2a35564f46afe7539b235659e0b89347b08/src/vs/workbench/contrib/debug/browser/debugService.ts#L977

**Comment by meganrogge** [comment]
What I was seeing is the whole statement "debugging paused...line content..." was being read twice. I am not sure just removing the "... line content..." will help. Is there a way to prevent it from hitting that twice?

**Comment by connor4312** [comment]
I think that's different than what Karthik reported in the issue above, and I don't reproduce that with the Python debugger but I do with js-debug (probably dealing with nested sessions)

**Comment by connor4312** [comment]
Made a PR to fix that, do you want to also tweak the message?

**Comment by meganrogge** [comment]
I think the message is good 👍 thanks
