### ISSUE TITLE
`j = {a: {…}} ` is read as `j=a` by the screen reader

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#223412]
Testing #222239

I noticed that, I have a variable that changes to something nested like `j = {a: {…}} `, it just reads as 'j=a'. Not sure if this is expected, but at least when reading from the debug console, it will tell the user whether the node is expanded or not, hinting that there is more nesting.

**Comment by meganrogge** [comment]
Thanks for inquiring about this. The announcement is just meant to give a quick update; the user can further inspect it in the debug console output area.
