### ISSUE TITLE
Git - history graph does not show commits for an unpublished repository

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#223475]
1. Open a folder/workspace in VS Code Insiders
2. Initialise a git repository in the folder
3. Create a file, make changes to it, and create multiple commits
Expected: commits should appear in the history graph
Actual: no commits are being shown in the history graph

**Comment by DonJayamanne** [comment]
@lszomoru this only works when there are multiple commits.
I.e. if we has just one commit in the repo, then history isn't displayed.
Else works as expected.

**Comment by lszomoru** [comment]
Thanks! I have filed https://github.com/microsoft/vscode/issues/223622 to handle the single commit scenario
