### ISSUE TITLE
SCM - history graph empty after publishing branch

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#223492]
Steps to Reproduce:

1. Open a folder/workspace that contains a git repository
2. Create a topic branch, and create multiple commits
3. Click the "Publish Branch" action button to publish the topic branch 

Expected: history graph should be updated with the label for the published branch
Actual: history graph is empty

**Comment by DonJayamanne** [comment]
Are you referring to the tooltip for the `cloud icon` on the top right
I doubt it, as this already works in stable as well.
My confusion is around the term `label`, not sure which/what label is being referenced here.


![Image](https://github.com/user-attachments/assets/3ac7f398-a774-400b-90f1-9f51b55d39f1)

**Comment by lszomoru** [comment]
Thanks Don! Yes, by "label" I meant the UX elements on the right side of the "another" commit. 
It is working as expected in Stable, but it regressed couple of days in Insiders so I have to get it fixed.
