### ISSUE TITLE
Use net module in shared process

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#223452]
Since https://github.com/microsoft/vscode/pull/202053 we have `electron:net` module available in all utility process which allows making requests via the network service without having to go through the main process, the shared process today uses ipc to make requests from the main process https://github.com/microsoft/vscode/blob/3cbdd820c5be204b35ca2aeef7384d9cf4920d70/src/vs/code/node/sharedProcess/sharedProcessMain.ts#L274-L275 which can now be switched.

**Comment by sandy081** [comment]
@deepak1556 Shared process is packaged under `node`. Is it possible to access `electron:net` from `node`?

**Comment by deepak1556** [comment]
Yup it is available in the desktop case, for remote you would need to conditionally skip it.
