### ISSUE TITLE
Buit-in PHP docs and intellisence

### ISSUE THREAD

**Issue by rogeriotaques** [Microsoft/vscode#22343]
Would be great if we could have built-in PHP docs, as we do have for JS and a proper intellisence that be able to map classes and functions from my project files, besides PHP native functions.

**Comment by ramya-rao-a** [comment]
By PHP docs, do you mean the information on hover?

**Comment by rogeriotaques** [comment]
Hey @ramya-rao-a. Nop, I'm talking about the comment block started by `/** ...  */` . It would be really useful if it works for PHP in the same way it's working now for JS files.

As for intellisence, I mean a buit-in one, coz now I'm using some extensions, but usually it duplicates the suggestions and doesn't understand some FW packages, such as Codeigniter.

**Comment by ramya-rao-a** [comment]
cc @mjbvz who worked on the jsdocs

@mousetraps can speak more to the intellisense part of the query

**Comment by rogeriotaques** [comment]
Great! I'd love to hear from them. :) Thanks.

**Comment by mjbvz** [comment]
@rogeriotaques For the PhpDocs support, did you mean picking up intellisense information from the phpdoc comments or were you referring to the JSDoc autocomplete support vscode provides in JavaScript and TypeScript?

**Comment by rogeriotaques** [comment]
@mjbvz the second, the autocomplete support vscode provides for JSDoc in JavaScript and TypeScript.

Just in case, if possible to have the intellisence (from PHPDocs) too, that would be amazing good!

**Comment by rogeriotaques** [comment]
@mjbvz have u seen my last message?

**Comment by dwengs** [comment]
Hello all. I've searched issues with "PHP and Comment" query and this comes up.
I also would be happy, if PHP language has the same intellisense option when you type /**

**Comment by mjbvz** [comment]
@mousetraps is maintaining the PHP extension so she can follow up on the feature request.

I've marked as help wanted in case anyone wants to start taking a look. We use [onEnter rules](https://github.com/Microsoft/vscode/blob/70e074ac2f2d9258d6792d0b224557f56060b5d4/extensions/typescript/src/typescriptMain.ts#L260) for basic jsdoc expansion in JS/TS. The auto filled JSdoc templates come  through this [completion provider](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/jsDocCompletionProvider.ts). Intellisense inside of jsdocs comes from the typescript server that powers our js and ts language features

**Comment by bmewburn** [comment]
Here's another php intellisense offering that might be suitable: https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

**Comment by rogeriotaques** [comment]
@bmewburn thanks. Will give a try.

**Comment by roblourens** [comment]
Only the extensions would be able to do this. Also the fixed comment matching support just landed.
