### ISSUE TITLE
ps1 scripts not getting promoted?

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#223409]
Testing #223130

Repro:
1. Open vscode repo
2. type `.\scripts\` and trigger suggest in terminal

I would expect that the `.bat` and `.ps1` scripts all live at the top based on your description, but I don't see that behaviour

**Comment by Tyriar** [comment]
Do you see this?

![image](https://github.com/user-attachments/assets/d59aef36-a149-48cf-9e03-68b011eeeccb)

It first sorts by file length, and only if the file excluding the extension is the same will it sort based on file type. This is to get it as close as possible to what tab does in pwsh where it completes the common prefix of all matches.
