### ISSUE TITLE
Allow to use as Code as commit message editor in running instance

### ISSUE THREAD

**Issue by leonp1991** [Microsoft/vscode#22345]
SMALL FEATURE REQUEST :)
when I use git from the cli, I use code for commit messages and it opens a new window, it would be nice if it opened in my already open workspace.

reason for this workflow:
while I am quite happy with the git tools in code:
  - they are not as reliable in large projects.
  - I prefer to perform complicated tasks from the cli.

- VSCode Version: 1.10.2
- OS Version: macOS 10.12

Steps to Reproduce:
1. set git config editor to code
2. make a git commit

**Comment by wgj** [comment]
I haven't ran into the issue you're describing but I use Code as my git editor, and I reuse `code` windows a lot. Maybe you can combine the two by setting your gitconfig `core.editor` to `code --wait --reuse-window`?

Here's a snippet of my gitconfig. I typically use Code's built-in Git client, so I don't worry about reuse here
``` 
~ $ grep code ~/.gitconfig -B 1
[core]
	editor = code --wait
--
	excludesfile = /Users/wes/.gitignore
[difftool "vscode"]
	cmd = code --wait --diff $LOCAL $REMOTE
```

But I do like to reuse Code windows if I'm using the interactive terminal
```
~ $ grep -B1 code ~/.bash_profile
if ! [[ $VSCODE_PID == "" ]]; then
  alias code='/usr/local/bin/code --reuse-window'
```

Hope that helps.

**Comment by leonp1991** [comment]
@wgj , that was not a bad idea. Seemed like it would work, but alas the --reuse-window option seemed to make it impossible for git to know when the commit message had been entered? Tryed saving commit message and closing window.

Thanks plenty for your help.

**Comment by bpasero** [comment]
We currently do not support this because the --wait parameter is not aware of a single editor closing inside an existing instance, it has to rely on window close.

**Comment by leonp1991** [comment]
@bpasero, ahh thank you for your input :). would be keen to see this in vscode, but can see how this would not be on the top of many contributors lists.

**Comment by DAddYE** [comment]
> @bpasero, ahh thank you for your input :). would be keen to see this in vscode, but can see how this would not be on the top of many contributors lists.

**Comment by bpasero** [comment]
Let's merge this into https://github.com/Microsoft/vscode/issues/24327

**Comment by DAddYE** [comment]
Thanks guys!
