### ISSUE TITLE
Both main and desc of suggestion entry end too early

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#223415]
Testing #223130

![Image](https://github.com/user-attachments/assets/cbed3ca3-3cb7-4e95-98cf-e8f7c629a3b9)

From this, I really want to know the name of the most nested folder, but both strings end too early for me to know. It seems that they both get in eachother's way. Would there be a way to omit a description if the title was too long? Or is there another way of remedying this?

**Comment by Tyriar** [comment]
Moving to @jrieken as it would need to be fixed there first.
