### ISSUE TITLE
Access notification actions via keyboard

### ISSUE THREAD

**Issue by jaywick** [Microsoft/vscode#22341]
![image](https://cloud.githubusercontent.com/assets/3955052/23775664/de7bbd22-057d-11e7-948d-8e615aa986e4.png)

Basically a way to click those two buttons using just the keyboard

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by jaywick** [comment]
Thanks @bpasero. For anyone else who gets here, the banner notifier thing is called an `informationMessage` and the duplicate feature request is #5538!
