### ISSUE TITLE
Unsure about when to expect suggestions to automatically appear

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#223420]
Testing #223130

I notice that sometimes, I need to trigger the suggest widget manually (ctrl+space). For example, I have` git add .\.vscode\notebooks\` typed, and I need to ctrl+space to see the filenames.

**Comment by Tyriar** [comment]
Can repro. This isn't meant to be possible as completions should be requested again after the `\` is typed:

![image](https://github.com/user-attachments/assets/9d18e808-ce1a-40f6-934c-5547cca7075f)
