### ISSUE TITLE
Closing editors (tabs) can repeatedly prompt on unsaved changes

### ISSUE THREAD

**Issue by isg** [Microsoft/vscode#22342]
- VSCode Version: 1.9.1
- OS Version: Mac OS 10.11.6

Steps to Reproduce:

1. Create a new file (e.g. CMD + N).
2. Type some text (e.g. "foo").
3. Close the editor repeatedly (e.g. hit CMD + W multiple times)

Result:
Unsaved changes prompt appears repeatedly, once for every time you hit CMD+W.

Expected Result:
Unsaved changes prompt appears a single time.

The main use case where this is very disruptive is when you have a lot tabs open and want to close them. I often hit CMD+W many times very quickly to close out a bunch of the tabs -- but if you accidentally hit a tab that has unsaved changes, you might end up having to resolve the unsaved changes dialog many times.

I tested this in other editors, and for example Sublime Text handles this properly -- no matter how many times you hit CMD+W, you will only have to handle the dialog once.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11928

**Comment by isg** [comment]
Thanks, apologies for the dupe!
