### ISSUE TITLE
Don't show delete git branches in command pallet

### ISSUE THREAD

**Issue by bartlewis** [Microsoft/vscode#22340]
- VSCode Version: 1.10.2
- OS Version: Mac OS 10.11.6

Steps to Reproduce:

1. Click the branch name in the lower left
2. View the suggestions in the command pallet.

All of these branches shown in the below screenshot are deleted already. They should not be shown as options. 

![screen shot 2017-03-09 at 3 18 23 pm](https://cloud.githubusercontent.com/assets/779139/23775115/e539dfa6-04db-11e7-9990-1cff9d2823b6.png)

**Comment by briancodes** [comment]
Hi. Why was this closed @bartlewis. Did you find a solution to this? I've been looking for an automated way of updating the VSCode command palette to reflect the current git status in regards to deleted remote branches, but have to delete each branch individually on my local system

**Comment by bartlewis** [comment]
@briancodes A couple of things that I did to resolve this.

1) I created an alias for git delete-merged.

```
// ~/.gitconfig
[alias]
 delete-merged = !git branch --merged | egrep -v \"(^\\*|master|development)\" | xargs git branch -d
```

Which you can run via:
```
// Terminal
$ git delete-merged
```

2) Git Prune: `git remote update --prune`
