### ISSUE TITLE
Workspace extensions not loaded in multiroot workspace

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#223511]
- Open multiroot workspace that includes 'vscode'
- "VS Code Selfhost Test Provider" doesn't appear in `@recommended` or the installed section
- It works when I open the 'vscode' folder by itself

**Comment by sandy081** [comment]
It is working for me. But there is one scenario which it did not work is following:

- Open empty window
- Add vscode folder to the empty window (add folder to the workspace)
🐛 Workspace extension is not shown
It works after reloading the window though.

Fixed above scenario.

@roblourens Can you please confirm if this is what you are seeing? If not, can you please share more details about the steps you followed?

**Comment by roblourens** [comment]
In my scenario I'm just opening a preexisting workspace that has the `vscode` and `vscode-copilot`. I just followed these steps to repro again

- Open a new window
- "Add folder to workspace" -> vscode
- Save the workspace config, reload the window just for good measure
- The workspace extension does show up in Recommended ✅ 
- Add another folder to the workspace -> `vscode-copilot`, reload the window
- Now the workspace extension does not show up

**Comment by sandy081** [comment]
After repeating above steps exactly, I see following recommended extensions

![Image](https://github.com/user-attachments/assets/ab4f71e6-3ac5-47ab-ae4c-65dc292e97b0)

**Comment by roblourens** [comment]
I still see the issue, lmk how I can help debug it

**Comment by roblourens** [comment]
Btw I still see the issue. Don't know whether it's something weird for me, or an issue that you'd want to fix before release, but I'm happy to set some breakpoints. Lack of test running is getting to me 😅

**Comment by sandy081** [comment]
Lets meet and investigate together.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/216433
