### ISSUE TITLE
Issue Reporter: Picking "Feature Request" in first dropdown results in blue button being permanently labelled "Loading data..."

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#223501]
Type: <b>Bug</b>

1. Launch Issue Reporter, e.g. from `Help: Report Issue` off Command Palette.
2. Change the first dropdown to `Feaure Request`

VS Code version: Code - Insiders 1.92.0-insider (7ed4cdc56d037146b2c4c890f09e78b2ba14b49d, 2024-07-24T07:50:18.385Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by justschen** [comment]
good catch, thanks! looks like an issue with the refactor 👍
