### ISSUE TITLE
ZSH Completions not working on integrated terminal

### ISSUE THREAD

**Issue by devsheva** [microsoft/vscode#223540]
Type: <b>Bug</b>

I'm using antigen for zsh with ohmyzsh plugin and zsh-completions bundle.
The completions perfectly work on my external terminal (my default is Warp), but when using the integrated one in VSCode it doesn't work. When i press tab to get completion, it just starts selecting one of the files in current workdir.

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|. --crash-reporter-id c5c50fd1-9de7-40de-85c9-64405017e16f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.55.0
vscode-deno|den|3.38.0
prettier-vscode|esb|10.4.0
copilot|Git|1.214.0
copilot-chat|Git|0.17.1
vscode-github-actions|git|0.26.3
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.1
live-server|ms-|0.4.14
material-icon-theme|PKi|5.7.0
errorlens|use|3.20.0
gitflow|vec|1.2.1
turbo-vsc|Ver|2.0.0
vscode-wakatime|Wak|24.6.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
legacy_priority:31094926
refactort:31101459
ccplc:31098109
wkspc-onlycs-c:31100201

```

</details>

**Comment by meganrogge** [comment]
does it work if you disable shell integration, `terminal.integrated.shellIntegration.enabled`?

**Comment by devsheva** [comment]
no still the same, but i noticed that it seems only deno completions don't work. they work fine in my external terminal, but in the integrated one it still doesn't provide completions

**Comment by meganrogge** [comment]
what happens if you manually source your zshrc?

`source ~/.zshrc`

**Comment by devsheva** [comment]
same thing, nothing changes

**Comment by meganrogge** [comment]
> only deno completions don't work

do you know where those are defined in your startup scripts? guessing that's not getting run

**Comment by devsheva** [comment]
i followed this [guide](https://docs.deno.com/runtime/manual/getting_started/setup_your_environment/#zsh-example-with-ohmyzsh-and-antigen). they should be run when doing `antigen bundle deno`, and as i said they work in my main terminal.


this is my `.zshrc` 

```

source $HOME/antigen.zsh

# Load the oh-my-zsh's library
antigen use oh-my-zsh

antigen bundles <<EOBUNDLES
    # Bundles from the default repo (robbyrussell's oh-my-zsh)
    git

    # Syntax highlighting bundle.
    zsh-users/zsh-syntax-highlighting

    # Fish-like auto suggestions
    zsh-users/zsh-autosuggestions

    # Extra zsh completions
    zsh-users/zsh-completions

    # Enable asdf
    asdf

EOBUNDLES

# Load the theme
antigen theme robbyrussell

antigen bundle deno
antigen apply

alias dev="cd ~/develop"

eval "$(starship init zsh)"
```

**Comment by Tyriar** [comment]
Does it work in the default Terminal.app? Can you show a screenshot of that vs vscode?

**Comment by devsheva** [comment]
`Warp` (my main terminal, the working one)
<img width="791" alt="Screenshot 2024-07-25 at 19 06 11" src="https://github.com/user-attachments/assets/bcf6aceb-4771-49d7-bcda-4ccc0b9d6321">

`VSCode`
<img width="552" alt="Screenshot 2024-07-25 at 19 06 43" src="https://github.com/user-attachments/assets/c88b3d72-8a43-414e-981d-e254f237746e">

`Terminal.app`
<img width="469" alt="Screenshot 2024-07-25 at 19 08 24" src="https://github.com/user-attachments/assets/7bbbdf12-891a-4fc5-beb6-f32fa2711450">

**Comment by Tyriar** [comment]
@devsheva the `task test` you show in VS Code is the completions, no? The Warp screenshot is showing their native intellisense which we don't have for zsh right now

**Comment by devsheva** [comment]
it's the output of autosuggestions plugin of zsh, cause i already typed it so it gets autosuggested from the history. i just typed `deno`  and pressed `Tab` key, and it started showing the current dir files instead of completions. 

i don't think it's just a Warp feature, cause what sense would have had to make a guide on official deno docs? they just tell there to run those commands in a zsh terminal, no matter where

**Comment by devsheva** [comment]
I resolved this by adding the `ZSH_CACHE_DIR` to `fpath` https://github.com/ohmyzsh/ohmyzsh/issues/12581#issuecomment-2254179750
