### ISSUE TITLE
In debug mode, sidemenu showing that the variable has some value in it. But when hover over the same variable in the editor, it shows "undefined"

### ISSUE THREAD

**Issue by PhymasSC** [microsoft/vscode#223575]
Type: <b>Bug</b>

Attach debugger to nodejs, then run the function and step over a statement, then hover over the variable and see it is "undefined" but the variable windows shows that the variable has a value.

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1355U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (3.20GB free)|
|Process Argv|. --crash-reporter-id 66b516fb-2272-4c1c-9399-8006f8e1292b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
npm-intellisense|chr|1.4.5
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.2.1
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
copilot|Git|1.216.0
copilot-chat|Git|0.17.1
graphql|mqu|0.1.2
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|5.8.0
react-labyrinth|rea|1.0.3
md-editor|see|0.0.5
vscode-mdx|uni|1.8.9
console-ninja|Wal|1.0.332
pretty-ts-errors|Yoa|0.5.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31101459
ccpltc:31103427
pythonrstrctxt:31103193

```

</details>

**Comment by roblourens** [comment]
Merging into https://github.com/microsoft/vscode/issues/221503
