### ISSUE TITLE
gutter Unable to display code modification highlight

### ISSUE THREAD

**Issue by dept11ms** [microsoft/vscode#223581]
Type: <b>Bug</b>

After installing a certain extension, the issue appears. After deleting the extension, the issue disappears. Currently, I don't know which extension is causing the problem

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.0-113-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700 (12 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|18.85GB (11.13GB free)|
|Process Argv|--crash-reporter-id 0988dbec-35ff-404e-831b-a20a6c52273c|
|Screen Reader|no|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.40.32|
|OS|Linux x64 5.15.0-113-generic|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700 (20 x 4500)|
|Memory (System)|31.08GB (1.57GB free)|
|VM|33%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
vscode-better-align|cho|1.4.2
gitlens|eam|15.2.1
copilot|Git|1.216.0
copilot-chat|Git|0.17.1
go|gol|0.42.0
vscode-language-pack-zh-hans|MS-|1.91.2024071009
cpptools|ms-|1.21.3
cpptools-extension-pack|ms-|1.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
9b8hh234:30694863
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31101459
ccplti:31103428
pythonrstrctxt:31103193
hdi1a554:31097393
wkspc-onlycs-t:31102394

```

</details>

**Comment by lszomoru** [comment]
Please use the extension bisect tool (https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to track down the culprit.
