### ISSUE TITLE
Error: Failed to execute git

### ISSUE THREAD

**Issue by uli2k** [Microsoft/vscode#22355]
- VSCode Version: 1.10.2
- OS Version: ubuntu 14.04 64bit Chinese Version
- GIT Version: 2.11.0

Steps to Reproduce:

1. Type "code" to run vscode.
2. Open a folder without the ".git"
3. Try to edit a C source file.
![2017-03-10 15 18 16](https://cloud.githubusercontent.com/assets/19323792/23785909/ed770bca-05a4-11e7-9c43-eec7b4551753.png)

**Comment by ramya-rao-a** [comment]
Any errors in the console?
Run `Developer: Toggle Developer Tools` to open the console

**Comment by fcharlie** [comment]
@ramya-rao-a @joaomoreno 
Bug here: https://github.com/Microsoft/vscode/blob/7f0f3103ee5fe1b50d11520bd999bacb34d9853f/src/vs/workbench/parts/git/node/git.lib.ts#L190

Git error message will change according to build local language

**Comment by joaomoreno** [comment]
Can you prove that the error message you get is not in English? We make sure to always run git in English:
https://github.com/Microsoft/vscode/blob/7f0f3103ee5fe1b50d11520bd999bacb34d9853f/src/vs/workbench/parts/git/node/git.lib.ts#L234

Can you give our [Insiders release](http://code.visualstudio.com/insiders) a try?

**Comment by uli2k** [comment]
@ramya-rao-a @joaomoreno My Ubuntu language is simplified Chinese, so Git is also the Chinese version, stderr is also Chinese, it means: not a git repository (or any parent directory)
![2017-03-20 13 58 42](https://cloud.githubusercontent.com/assets/19323792/24089871/1a374e8a-0d76-11e7-8731-66f765001a4b.png)

**Comment by uli2k** [comment]
@joaomoreno The Insiders release version has the same error message.
![2017-03-20 14 17 57](https://cloud.githubusercontent.com/assets/19323792/24090126/777dd788-0d78-11e7-8768-7ae04297c44f.png)

**Comment by joaomoreno** [comment]
@uli2k In the Gnome Terminal, can you `cd` to that folder and then run:

```
git status
```

Then, run:

```
LANG="en_US.UTF-8" git status
```

What's the output of both commands?

**Comment by uli2k** [comment]
@joaomoreno 
zhang@zhang-ThinkPad:~$ cd projects/jjj/
zhang@zhang-ThinkPad:~/projects/jjj$ ls -l
总用量 16
drwxrwxr-x 9 zhang zhang 4096  2月  6 08:29 build
drwxrwxr-x 4 zhang zhang 4096  2月  6 08:29 devel
drwxrwxr-x 2 zhang zhang 4096  1月  7 09:44 devel_isolated
drwxrwxr-x 4 zhang zhang 4096  1月  9 08:58 src
zhang@zhang-ThinkPad:~/projects/jjj$ git status 
fatal: 不是一个 git 仓库（或者任何父目录）：.git
zhang@zhang-ThinkPad:~/projects/jjj$ LANG="en_US.UTF-8" git status 
fatal: 不是一个 git 仓库（或者任何父目录）：.git
zhang@zhang-ThinkPad:~/projects/jjj$ 

Does it help you?Screenshot below.
![2017-03-22 10-21-26](https://cloud.githubusercontent.com/assets/19323792/24179902/f5576e60-0eec-11e7-9f12-eeaa46eeda9e.png)

**Comment by joaomoreno** [comment]
Uh-hoh!!!

How about:

-  `LC_ALL="en_US. UTF-8" git status`
-  `LC_ALL="en_US" git status`
-  `LANG="en_US" git status`

**Comment by uli2k** [comment]
zhang@zhang-ThinkPad:~/projects/jjj$ LC_ALL="en_US.UTF-8" git status
fatal: 不是一个 git 仓库（或者任何父目录）：.git
zhang@zhang-ThinkPad:~/projects/jjj$ LC_ALL="en_US" git status
fatal: Not a git repository (or any of the parent directories): .git
zhang@zhang-ThinkPad:~/projects/jjj$ LANG="en_US" git status
fatal: Not a git repository (or any of the parent directories): .git
zhang@zhang-ThinkPad:~/projects/jjj$

**Comment by uli2k** [comment]
@joaomoreno It Worked!

**Comment by joaomoreno** [comment]
Awesome, pushing a fix for this.

**Comment by michelkaporin** [comment]
@uli2k can you please validate if it works on the latest insiders?

**Comment by uli2k** [comment]
@michelkaporin yeah, it worked at code-insiders_1.12.0-1491545409_amd64.deb
