### ISSUE TITLE
Build failed - flaky git tests

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#223563]
```
1) opens diff editor     2) stages correctly     3) stages, commits changes and verifies outgoing change
```

Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=285012
Changes: https://github.com/Microsoft/vscode/compare/06643dd...ad09ae2

**Comment by rzhao271** [comment]
Assuming it's a flake that hasn't happened in a while. Closing.
