### ISSUE TITLE
Terminal displays UTF graphemes 👩‍🚒 as 👩<200d>🚒

### ISSUE THREAD

**Issue by shaozi** [microsoft/vscode#223571]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.91.1
  Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
  Date: 2024-07-09T22:07:54.982Z
  Electron: 29.4.0
  ElectronBuildId: 9728852
  Chromium: 122.0.6261.156
  Node.js: 20.9.0
  V8: 12.2.281.27-electron.0

- OS Version: OS: Darwin x64 21.6.0

Steps to Reproduce:

1. Open terminal, copy and paste 👩‍🚒
2. terminal cannot display it, instead, it displays 👩<200d>🚒

**Comment by meganrogge** [comment]
https://github.com/xtermjs/xterm.js/issues/2668

**Comment by Tyriar** [comment]
Let's track upstream
