### ISSUE TITLE
Mixed column numbers and character counts

### ISSUE THREAD

**Issue by Jamu2800** [microsoft/vscode#223503]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.1
- OS Version: Windows 11 23H2

Steps to Reproduce:

1. Enter `1234` and `１２`, `    `, and tab on the vscode.
2. Confirm the column number.

| input str | col num |
| :-: | -: |
| `1234` | 5 |
|  `１２` | 3 |
|  `    `  | 5 |
| tab | 5 |
![image](https://github.com/user-attachments/assets/417fc9fe-7524-4d62-9fd1-268aea15feab)

You will see that the number of characters is displayed, not the column number.

I thought this was a bug.
I only understand Japanese and I use deep.com for translation.
So there might be some inappropriate expressions. Sorry.
Thanks for reading this far.

**Comment by fandecheng** [comment]
I am a Chinese user. Let me paste what Visual Studio 2022 displays for the column number:

![Image](https://github.com/user-attachments/assets/2de044ba-2240-4bef-8eae-50b1474ddfb1)

As you can see, Visual Studio 2022 does distinguish the character number and the column number. Would you please consider this feature also for Visual Studio Code? Thanks.
