### ISSUE TITLE
Open type: sometimes hard to distinguish different types

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#22357]
As in this example for the `FileService`:

![image](https://cloud.githubusercontent.com/assets/900690/23785981/ace7c3e0-056a-11e7-99ba-21d7b84adb7c.png)

**Comment by mjbvz** [comment]
Let me know if anyone has any suggestions on improving this. I imagine adding additional icons to differentiate these would be the easiest fix

**Comment by bpasero** [comment]
@mjbvz how would that help for the 2 `updateContent()` methods inside `FileService`? The only difference is in which file (= module) they are declared. This would be the information I am missing here.

**Comment by mjbvz** [comment]
@bpasero Ok, yes it was not clear to me what the problem was from the original report. I can look into exposing the file name at least

**Comment by bpasero** [comment]
Thanks!

**Comment by mjbvz** [comment]
Here's two prototypes. Using workspace relative path:

![screen shot 2017-05-08 at 2 49 29 pm](https://cloud.githubusercontent.com/assets/12821956/25826995/f2ee50d6-33fd-11e7-8869-344a30325103.png)

using just filename:

![screen shot 2017-05-08 at 2 52 05 pm](https://cloud.githubusercontent.com/assets/12821956/25826988/ed3d097a-33fd-11e7-963f-74cec36a27df.png)

The full paths are perhaps more useful but they do clutter up the results and the long name can hide the filename if the UI is more compressed

**Comment by bpasero** [comment]
@mjbvz why don't we start with showing the file name first and see how that goes?
