### ISSUE TITLE
++Viral!!full video Umesh Kumar Mohammed Shami original Hq

### ISSUE THREAD

**Issue by Devnulldev** [microsoft/vscode#223513]
Mohammed Shami's friend opens up on his suicide attempt: 'He was standing on balcony'
Mohammed Shami's good friend Umesh Kumar recently opened up on the suicide attempt by the India fast bowler during the lowest phase of his career.

[Watch 🟢 ➤ ➤ ➤ 🌐 Click Here To link (Full Viral Video Link)](https://leakedvideohdtv.blogspot.com/2024/07/big-seans-alleged-upcoming-album-leaked.html)

[🔴 ➤►DOWNLOAD👉👉 (Full Viral Video Link)](https://leakedvideohdtv.blogspot.com/2024/07/big-seans-alleged-upcoming-album-leaked.html)

In Short
Shami's friend opens up on his suicide attempt
Umesh reveals he saw him standing at balcony at night
Shami had allegations of match fixing for Pakistan game
Star India fast bowler Mohammed Shami’s friend Umesh Kumar recently opened up on fast bowler’s tragic time of his career and personal life which even led him have suicidal thoughts. Notably, Shami’s wife Hasin Jahan had filed for divorce in March 2018 alleging domestic violence and infidelity by the cricketer.

However, the fast bowler denied all allegations calling the entire saga ‘an attempt to malign his image’. To make matters worse for the cricketer, the 33-year-old also found himself in another controversy after his poor performance against Pakistan in the T20 World Cup 2021 with some people alleging his involvement in match-fixing. The fast bowler was also subjected to religious abuse on his social media accounts.

ADVERTISEMENT
Recalling the lowest point of Shami’s career, his friend Umesh Kumar, who’s also a member of the Uttarakhand Legislative Assembly, revealed that the India star was shattered by all the allegations against him during that period.

"Shami was fighting with everything during that phase. He lived with me in my house. But when the fixing allegations with Pakistan broke, and led to a probe that night, he was shattered. He said that I can tolerate everything but not allegations of betraying my country," Umesh said on Shubhankar Mishra's podcast 'Unplugged'.

Further speaking ahead, Kumar opened up on the reports of the cricketer attempting suicide and recalled an incident when he saw him standing tensed on the balcony at night.

"It also came in the news that he wanted to do something drastic that night [end his life]. It was around 4 AM in the morning when I got up to drink water. I was on my way to the kitchen when I saw that he was standing on the balcony. It was the 19th floor we were living in. I understood what happened. That night of Shami's career, I feel, was the longest. Later, one day, when we were talking, he got a message on his phone saying he got a clean chit from the committee that was investigating the matter. He was probably happier that day than he would have been if he had won a World Cup," he added.

Mohammed Shami undergoing rehabilitation
Shami was cleared of all the baseless allegations and the then India captain Virat Kohli also came out in support of the cricketer slamming his trolls. Following the incident, Shami won back the love of his fans with a record-breaking performance in the ODI World Cup 2023.

The speedster finished as the highest wicket taker of the tournament with 24 wickets to his name from seven innings. Since, then the cricketer hasn’t made any other international appearance and underwent a surgery for his ankle injury. Shami is on the road to comeback and is currently undergoing rehabilitation at the National Cricket Academy (NCA) in Bengaluru.

[Watch 🟢 ➤ ➤ ➤ 🌐 Click Here To link (Full Viral Video Link)](https://leakedvideohdtv.blogspot.com/2024/07/big-seans-alleged-upcoming-album-leaked.html)

[🔴 ➤►DOWNLOAD👉👉 (Full Viral Video Link)](https://leakedvideohdtv.blogspot.com/2024/07/big-seans-alleged-upcoming-album-leaked.html)

[Watch 🟢 ➤ ➤ ➤ 🌐 Click Here To link (Full Viral Video Link)](https://leakedvideohdtv.blogspot.com/2024/07/big-seans-alleged-upcoming-album-leaked.html)

[🔴 ➤►DOWNLOAD👉👉 (Full Viral Video Link)](https://leakedvideohdtv.blogspot.com/2024/07/big-seans-alleged-upcoming-album-leaked.html)

[Watch 🟢 ➤ ➤ ➤ 🌐 Click Here To link (Full Viral Video Link)](https://leakedvideohdtv.blogspot.com/2024/07/big-seans-alleged-upcoming-album-leaked.html)

[🔴 ➤►DOWNLOAD👉👉 (Full Viral Video Link)](https://leakedvideohdtv.blogspot.com/2024/07/big-seans-alleged-upcoming-album-leaked.html)

**Comment by nicolanfx** [comment]
[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)
