### ISSUE TITLE
Workspace extensions are not visible in @recommended section if they are installed

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#223509]
1. Open the vscode repo
2. Search `@recommended` extensions
3. See the Selfhost Test Runner extension, Install it
4. Reload the window
5. Search `@recommended` extensions
 🐛 See the Selfhost Test Runner extension is not visible

**Comment by sandy081** [comment]
I cannot reproduce the issue. I also tried on fresh user data directory. Can you please share more specific details of the steps you followed to reproduce the issue?

**Comment by connor4312** [comment]
Oh, I see, workspace extensions don't show under `@recommended` if they're already installed, unlike other extensions.

Maybe a slight oddity to fix if easy, will let you close it if not.

**Comment by sandy081** [comment]
> Oh, I see, workspace extensions don't show under @recommended if they're already installed, unlike other extensions.

Hmm, that's not what I expected too. They should be shown always. I will fix that.
