### ISSUE TITLE
(full video!!) Love Island USA's Kendall Leaked Video On Twitter And Reddit

### ISSUE THREAD

**Issue by Devnulldev** [microsoft/vscode#223505]
13 sec ago-Love Island USA's Kendall Leaked Video On Twitter And Reddit

[Watch 🟢 ➤ ➤ ➤ 🌐 Click Here To link (Full Viral Video Link)](https://leakedvideohdtv.blogspot.com/2024/07/big-seans-alleged-upcoming-album-leaked.html)

[🔴 ➤►DOWNLOAD👉👉 (Full Viral Video Link)](https://leakedvideohdtv.blogspot.com/2024/07/big-seans-alleged-upcoming-album-leaked.html)

Love Island USA's Kendall Washington Addresses Leaked NSFW Video

Concerns for Love Island USA’s Kendall as ‘private video’ circulates online

Love Island star Kendall finished the dating show with Nicole. However, the highs of getting to the final were torn apart when a private video appearing to feature Kendall was leaked online.

Kendall’s sister, Taylor, has shared concern for her brother’s mental health after a private video was released. She is calling on Love Island USA bosses to put “serious mental health resources” into action.

Private video of Kendall shared online
A video appearing to feature Kendall Washington, a Love Island USA finalist, involved in intimacy has been doing the rounds on X (Twitter). Fans are in shock after seeing the video, which saw him in his birthday suit.

He has not yet been given back his phone after reaching the final, but fans are rushing to report the videos, which are rumored but not confirmed to have been shared by friends, to take them down.

In the video, he appears to be on a double bed before turning around. There does not appear to be anyone else involved in the private video.

AWW: Love Island USA winners make fans ‘believe in love again’
GRV Media and Reality Tidbit have contacted Love Island representatives for comment.

Sister ‘concerned’ for her brother
Kendall, whose sister, Taylor, surprised him via video call in the last week of Love Island USA, has spoken out against the content being shared. She said she “doesn’t have the capacity to reply to everyone”.

However, she continued to write on her Instagram Story: “I appreciate everyone reaching out concerned about Kendall’s mental health. I am too,” before tagging Love Island bosses.

She told them, “I really hope y’all have serious mental health resources in place for him so he doesn’t come back from the high of this experience to seeing he’s been unfairly exposed.”

@therealkatherine
wow this is literally so wild loveislandusaseason6episode36 LoveIslandUSASeason6 loveislandusaseason6finale lovislandusa

♬ original sound – katherine
View TikTok
Love Island USA fans back Kendall
Fans – even those who admit they don’t particularly like Kendall – are backing him after the video was circulated. Most of all, they fear he’ll find out after getting his phone back.

One viewer wrote, “Yea he [doesn’t] deserve it that’s online for the whole Love Island cast & his family to see,” while another penned, “I’m choosing to believe it is AI and I’m really wishing him and his family strength.”

A fellow fan reacted with, “Y’all sharing Kendall’s private video should be ashamed of yourselves. Do you not realize how that could affect his mental health, and his family. That’s

Love Island USA’s Kendall Washington Speaks Out After NSFW Nude Videos Surface

Click to share on Facebook (Opens in new window)
Click to share on Twitter (Opens in new window)
Love Island USA’s Kendall Washington Speaks Out After NSFW Nude Videos Surface
Kendall Washington. Ben Symons/Peacock
Life outside the Love Island USA villa isn’t exactly drama-free for Kendall Washington.

Less than one day after Peacock aired the show’s season 6 finale, one finalist spoke out on social media when NSFW nude videos were leaked online.

“What a way to get my phone back y’all,” Kendall, 27, shared via his Instagram Stories on Monday, July 22, when seemingly addressing the private videos. “I just want to address the content that came out from my past. That was something I shared to someone in confidence and trust. It’s unfortunate that it’s no longer private but it is what it is.”

Kendall went on to thank everyone “for the calls/texts to support me during this time.” He also continued to express gratitude for his experience on Love Island USA.

Love Island USA Couples Status Check Who Is Still Together and Who Broke Up After Leaving Villa 719
Related: ‘Love Island USA’ Status Check: Which Couples Are Still Together?
“I am so grateful for my Love Island experience and I love you all for turning in to watch my journey,” he continued. “Excited for what’s next.”

During the final episode, which aired on Sunday, July 21, Kendall and Nicole Jacky expressed their love for each other after being coupled up for a majority of the season.

“Looking back at the moment we first met, still gives me the chills,” Kendall shared with the California native. “When I heard the sound of your high heels getting closer to me, you then took my blindfold off me. Until this day, I have never laid eyes on something so beautiful.”

He continued, “Nicole Danielle Jacky, when I say these words, I mean them. I love you.”

[Watch 🟢 ➤ ➤ ➤ 🌐 Click Here To link (Full Viral Video Link)](https://leakedvideohdtv.blogspot.com/2024/07/big-seans-alleged-upcoming-album-leaked.html)

[🔴 ➤►DOWNLOAD👉👉 (Full Viral Video Link)](https://leakedvideohdtv.blogspot.com/2024/07/big-seans-alleged-upcoming-album-leaked.html)

**Comment by nicolanfx** [comment]
[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video DOWNLOAD👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)

[🔴 ➤Full Video WATCH👉 Full Viral Video Link](https://viralvideohd.xyz/viral-lacked-videos/)
