### ISSUE TITLE
Lua Symbols not support!!!

### ISSUE THREAD

**Issue by DFVSQY** [Microsoft/vscode#22350]
- VSCode Version: 1.10.2

There is no have support for lua symbols, it's really bad experience.
Really hope provide build-in support, some plugin for this feature is not so good.

**Comment by ramya-rao-a** [comment]
What kind of support are you looking for?

**Comment by DFVSQY** [comment]
for lua file, like sublime text3:

**Comment by DFVSQY** [comment]
For lua files, like **Sublime Text 3**:
![image](https://cloud.githubusercontent.com/assets/8075421/23829709/207afed8-0734-11e7-8373-d1eb18a5d7d2.png)
Sublime Text 3 will list lua functions, I hope vs code will support it.

**Comment by ramya-rao-a** [comment]
That kind of language support comes from extension and not the core product of VS Code

Please try the extensions from the marketplace https://marketplace.visualstudio.com/search?term=lua&target=VSCode&sortBy=Relevance

**Comment by keweilizhe** [comment]
yes, thanks for @ramya-rao-a   , i'v find a proper one, recommend extension name: vscode-lua
