### ISSUE TITLE
Font difference in menu bar vs drop-down/context menu

### ISSUE THREAD

**Issue by jakuup** [microsoft/vscode#223595]
Type: <b>Feature Request</b>

There is a visible difference in font size used in menu bar and drop down or context menus: seems that menu bar uses system font and both drop down and context menu use different. I compared with "regular" VS Code and it seems that menu drawing is different: rounded shape in Insiders, rectangle in "regular".
I didn't notice which Insiders version introduced this change and not sure it's bug or intentional change. If intentional, I would prefer to have a option/possibility to use system menu appearance as it is more compact (I haven't found configuration for that).

VS Code version: Code - Insiders 1.92.0-insider (50560b991207e2bb70a6e177f2c2e88949a01e6c, 2024-07-25T05:04:21.378Z)
OS version: Linux x64 5.15.0-116-generic snap
Modes:

![insider](https://github.com/user-attachments/assets/aea27be8-299a-4655-8c56-f5acc40f5895)
![regular](https://github.com/user-attachments/assets/a7402b8b-d29b-4b0f-afe4-80ef8f3f85f8)

**Comment by chapmanjacobd** [comment]
This is essentially the same as https://github.com/microsoft/vscode/issues/224515 which has more participants. The old context menu is rendered by your DE while the new one is rendered by VSCode
