### ISSUE TITLE
Allow arguments for status bar item commands

### ISSUE THREAD

**Issue by AnWeber** [microsoft/vscode#22353]
It should be possible to execute complex commands with the StatusBarItem. At the moment it is not possible to provide arguments for the command. Please adjust the interface like the recent change in v1.10 in the task key bindings:
```
{
    "key": "ctrl+h",
    "command": "workbench.action.tasks.runTask",
    "args": "tsc"
}
```

Thanks

**Comment by fabiospampinato** [comment]
@AnWeber it's actually already possible, not obviously easy how to do it though. My [Commands](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-commands) extension has this capability.

Btw I think also context menus entries and pretty much everything that is currently able to trigger a command should define an `arguments` property for easily implementing this.

**Comment by mattacosta** [comment]
I agree. It would be a lot easier if it were like a TreeItem which takes a `Command` (an identifier and array of arguments) instead of a simple string.

**Comment by hediet** [comment]
Loosly inspired by @fabiospampinato this is my workaround:
```ts
import { commands, Disposable } from "vscode";

let curId = 0;
const commandId = (id: number) => `anonymous-command.${id}`;

export function getAnonymousCommand(
	func: () => void
): { command: string; disposable: Disposable } {
	const id = curId++;
	const parametrizedCommand = commandId(id);
	const d = commands.registerCommand(parametrizedCommand, () => {
		func();
	});

	return {
		command: parametrizedCommand,
		disposable: d,
	};
}

export function getParametrizedCommand(
	command: string,
	args: unknown[]
): { command: string; disposable: Disposable } {
	return getAnonymousCommand(() => {
		commands.executeCommand(command, ...args);
	});
}
```
