### ISSUE TITLE
Partially Broken Complex Script Rendering of Tamil

### ISSUE THREAD

**Issue by KTSamy** [Microsoft/vscode#22352]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.7.0|;

---

Steps to Reproduce:

1. Editing an xml file which contains tamil translated strings
2.Whenever I open rendering or some letters are always broken at random points every time. But the same letter is rendered properly on other locations in the same file. Just look at the last word of line no 146. (Left: Brackets - Right: Visual Studio Code). As I said the position of broken text changes on every launch.

<img width="1428" alt="screen shot 2017-03-10 at 10 02 19 am" src="https://cloud.githubusercontent.com/assets/8410178/23782247/d79b0256-0578-11e7-9f1b-96f199d099d5.png">

Original File:
[strings (1).xml.zip](https://github.com/Microsoft/vscode/files/832981/strings.1.xml.zip)

**Comment by alexandrudima** [comment]
Reduced repro:

* open a new untitled file:
```
JoyShareல் பின்தொடர்ந்து, விடீயோ, ஜோக்குகள், அனிமேசன், நகைச்சுவை படங்கள் மற்றும் செய்திகளை பெறுவீர்
```
Type spaces at the beginning of the line:

![kapture 2018-04-04 at 11 44 34](https://user-images.githubusercontent.com/5047891/38300634-93371efc-37fd-11e8-91aa-73b1555e8079.gif)

**Comment by alexandrudima** [comment]
Another repro (from #42700):
```
वो ऐसा क्या है जो हमारे अंदर भी है और बाहर भी है। जिसकी वजह से हम सब हैं। जिसने इस सृष्टि की रचना की है।
```

**Comment by alexandrudima** [comment]
Another repro, using 'COMBINING ACUTE ACCENT' (U+0301):

```
12345689012345678901234568901234567890123456890abába
```

![image](https://user-images.githubusercontent.com/5047891/38300928-7567595e-37fe-11e8-8035-3fa9e0eb372f.png)

**Comment by roblourens** [comment]
I can't repro this in 1.22.2

**Comment by alexandrudima** [comment]
@roblourens To repro you need to have default settings. i.e. use a monospace font and not use ligatures or other extensions that introduce inline decorations on lines.
