### ISSUE TITLE
macOS: BundleIdentifier present on my .zshrc file

### ISSUE THREAD

**Issue by AkdM** [Microsoft/vscode#22366]
- VSCode Version:  Code Version 1.10.2
- OS Version: macOS 10.12.3

---

I have an alias `morning` on my *.zshrc* file that opens automatically my apps, folders and files on the morning when I am at work.
In this alias, I have this simple function:

``` shell
echo "Opening $# apps..."
for appBundleIdentifier in "$@"
do
  $(open -b $appBundleIdentifier)
done
```

Where `appBundleIdentifier` holds things like `com.apple.mail`, `com.fournova.Tower2`, but also `com.microsoft.VSCode`, which is the Bundle Identifier of Microsoft VS Code.
When I open up VSCode, I have the following message:

> Code needs to change the 'code' shell command. Would you like to do this now ?

then

> Please remove the alias referencing 'com.microsoft.VSCode' in '/MyUser/.zshrc' (line xxx) and retry this action.

then 

> Please remove the 'code' alias from '/MyUser/.zshrc' before continuing.

The thing is I don't have any `code` alias present there. I guess it takes the `com.microsoft.VSCode` as the code alias and thinks it would break the code shell command (which works perfectly btw).

It would be better to dismiss this message and/or disable the check of `code` in the shell ressource file in the VSCode settings.

---

Steps to Reproduce:

1. Put the VSCode Bundle Identifier on your .bashrc (or .zshrc or any other shell ressource), for example: `echo 'com.microsoft.VSCode'`. Note that it won't work if you put it in comments.
2. Open up VSCode.

**Comment by joaomoreno** [comment]
Sorry about this... The code is in for fixing a very old launch setup on the mac... I think we can remove it by now. 👍
