### ISSUE TITLE
command 'extension.vim_backspace' not found

### ISSUE THREAD

**Issue by Johnishaya** [Microsoft/vscode#22365]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|delphi-keybindings|alefragnani|0.1.0|
|vscode-eclipse-keybindings|alphabotsec|0.9.2|
|vscode-standard-format|chenxsan|0.0.12|
|compulim-vscode-closetag|Compulim|0.1.2|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.7|
|javadebugger|donjayamanne|0.0.2|
|jquerysnippets|donjayamanne|0.0.1|
|javac-linter|faustinoaq|1.2.2|
|php-debug|felixfbecker|1.10.0|
|vscode-javac|georgewfraser|0.0.23|
|live-html-previewer|hdg|0.0.1|
|vscode-emacs|hiro-sun|0.1.1|
|beautify|HookyQR|0.8.9|
|crane|HvyIndustries|0.3.1|
|phpcs|ikappas|0.7.0|
|Angular1|johnpapa|0.1.16|
|intellij-idea-keybindings|k--kato|0.2.10|
|format-indent|Kasik96|1.3.0|
|phpmd|linyang95|1.1.4|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|MagicPython|magicstack|1.0.7|
|mssql|ms-mssql|0.3.0|
|atom-keybindings|ms-vscode|2.0.1|
|sublime-keybindings|ms-vscode|2.0.1|
|typescript-javascript-grammar|ms-vscode|0.0.18|
|vs-keybindings|ms-vscode|0.1.3|
|language-vscode-javascript-angular2|nwallace|0.0.11|
|Ruby|rebornix|0.10.4|
|vscode-icons|robertohuertasm|7.3.0|
|nativescript|Telerik|0.6.1|
|html-preview-vscode|tht13|0.1.1|
|vim|vscodevim|0.6.2|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|2.1.8|;

---

Steps to Reproduce:

1.
2.

**Comment by rebornix** [comment]
@Johnishaya can you provide more info?

**Comment by molysama** [comment]
same problem
VSCode Version: Code 1.10.2
OS Version: debain8

**Comment by rebornix** [comment]
@molysama thanks for the info. I want to ask a few more questions as below:

* Does this happen immediately after you install VSCodeVim?
* Do you restart VS Code after installing the extension?
* When you run into the problem, does restarting VS Code mitigate this issue?

**Comment by molysama** [comment]
@rebornix 
In fact, I don't know how it works.  
Today I update the extension to 0.6.6, this issue happened again.

**Comment by molysama** [comment]
@rebornix 
1. remove all of my extensions
2. delete the files on extensions folder.
3. install extensions, It works.

When I install I found that some extension is can not be found, I think it is the reason.
My English is very poor, hope to help you

**Comment by rebornix** [comment]
@molysama can you help confirm that if it's similar to https://github.com/Microsoft/vscode/issues/25026 ? When you open VS Code, the commands are not available immediately, usually you need to wait for a few seconds. Can you help verify that as well?

**Comment by molysama** [comment]
@rebornixI think the reason should be some extensions expired and lost， this is not caused by vim plugin.
I think you may find some no longer exists while clearing extension.

**Comment by sandy081** [comment]
@molysama @Johnishaya 

May I know if there are any errors in the console. Run the command `Developer: Toggle Developer Tools` and check the console?

**Comment by sandy081** [comment]
>> I think the reason should be some extensions expired and lost， this is not caused by vim plugin.

@molysama Not sure how not having other extensions is causing this issue? Does the vim extension depends on some of them?
