### ISSUE TITLE
Tasks lint and intellisense have conflicting suggestions

### ISSUE THREAD

**Issue by wgj** [Microsoft/vscode#22367]
When using the ["Hello World" Tasks example](https://code.visualstudio.com/docs/editor/tasks#_hello-world), there's a linter for tasks.json. If I resolve the issue, I incur Intellisense's wrath with a red squiggle.

![tasks syntax error](https://cloud.githubusercontent.com/assets/463564/23790006/238ac544-0532-11e7-8dd1-16d4ed71b770.png)

![escape with tooltip](https://cloud.githubusercontent.com/assets/463564/23790010/25993d84-0532-11e7-90a1-0ca13aa0986f.png)

- VSCode Version: 1.10.2 (1.10.2)
- OS Version: MacOS 10.12.3 (16D32)
- Tasks Version: 2.0.0

Steps to Reproduce:

1. Add "Hello World" to tasks.json, and observe syntax suggestion in Output.
```
        {
            "taskName": "echoTest",
            "command": "echo",
            "isShellCommand": true,
            "args": ["Hello World"],
            "showOutput": "always",
            "echoCommand": true
        }
```

2. Escape "Hello World" spaces, and observe Intellisense error, and tool tip.

**Comment by dbaeumer** [comment]
Tricky :-). Since you want to pass `Hello\ World` to the terminal and you enter the string in a JSON file you need to escape the `\` character as well. So it should be `Hello\\ World`.

**Comment by wgj** [comment]
Thanks @dbaeumer, though for what it's worth, I don't _want_ to pass `Hello\ World`, I'm trying to follow the Task linting and Intellisense suggestions while working through the STR for #22377. I opened this issue for user experience and [documentation accuracy](https://code.visualstudio.com/docs/editor/tasks#_hello-world).

`Hello\\ World` resolves the Intellisense suggestion, but still triggers the Tasks linting:
![screen shot 2017-03-13 at 2 58 55 am](https://cloud.githubusercontent.com/assets/463564/23849660/a748960e-0799-11e7-811f-820a7c3fe231.png)

Which is moot because I get the desired results if I just ignore the lint warning:
![screen shot 2017-03-13 at 3 02 48 am](https://cloud.githubusercontent.com/assets/463564/23849676/b0f8bc7e-0799-11e7-8d80-de5bd05c1c54.png)

**Comment by dbaeumer** [comment]
The linting failure (in the output window) is correct and shouldn't happen. Will reopen to address this.

**Comment by michelkaporin** [comment]
I think you forgot to reopen it, @dbaeumer.

**Comment by dbaeumer** [comment]
To verify:

- Mac / Linux
- command with args which escape the space using \
