### ISSUE TITLE
Provide command to toggle minimap in the menu

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#22360]
From twitter:

![image](https://cloud.githubusercontent.com/assets/172399/23786830/6bdd70ac-056f-11e7-9d09-9ebe8fef8147.png)

It is a valid request given that we have toggles for all the other UI elements
![image](https://cloud.githubusercontent.com/assets/172399/23786907/b9a19980-056f-11e7-9def-d48e5ae65fed.png)

// fyi @alexandrudima

**Comment by alexandrudima** [comment]
Duplicate of #22423
