### ISSUE TITLE
Some suggestions are missing on Windows with pwsh

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#223658]
I was trying to verify https://github.com/microsoft/vscode/issues/222233.
1. Open VS Code window
2. In pwsh terminal `.\sc`
3. I expect to see a suggestion for the `.\scripts\` folder

![Image](https://github.com/user-attachments/assets/7b8edb63-4142-4ec3-abf6-d54bdde11c39)

**Comment by Tyriar** [comment]
Regressed recently, should be fixed in https://github.com/microsoft/vscode/pull/223650

**Comment by Tyriar** [comment]
Actually this won't be fixed by that as it only applies when all completions are files or directories (eg. `cd <file|dir>`), but your case have other commands too.
