### ISSUE TITLE
The "Search in Current File" extension should be added by default

### ISSUE THREAD

**Issue by PoignardAzur** [microsoft/vscode#223612]
[Search in Current file](https://marketplace.visualstudio.com/items?itemName=shibayu36.search-in-current-file) is a simple extension that adds a small command to go from the "Find" widget to the "Find in files" pane scoped to the current file.

The README also recommends adding these keyboard shortcuts:

```json5
// Only type ctrl+o when using Find.
// the query in Find is filled into the query in Search.
{
  "key": "ctrl+o",
  "command": "search-in-current-file.searchInCurrentFile",
  "when": "editorFocus && findInputFocussed"
},
{
  "key": "ctrl+cmd+o",
  "command": "search-in-current-file.searchInCurrentFile",
  "when": "editorFocus"
},
```

It doesn't add new UIs or new widgets, it's just a quality of life "command sugar".

It's a feature I've wished for *a lot* before I found this extension, and the extension implements it in a clever and simple way. [The file with most of the implementation](https://github.com/shibayu36/vscode-search-in-current-file/blob/b684f04f94c6dee0dfb362c0307465ccb2bf135f/src/extension.ts) is 30 lines long.

**Comment by andreamah** [comment]
Unfortunately, we want to limit the number of extensions that ship natively with vscode, as we don't want to bloat it and we become responsible for any bugs and vulnerabilities that the extension may bring to our users. We welcome people to add this extension manually as they see fit.

**Comment by PoignardAzur** [comment]
Right, but in that case the extension is about 30 lines long. It should be fairly easy to port to the existing find-in-files implementation without much bloat.

**Comment by andreamah** [comment]
This still leaves the issue where we need to support it and resolve any potential security risks. 
The functionality is niche enough that it is fine as a standalone extension. Not everyone expects the content of the find widget to transfer to the search widget.
