### ISSUE TITLE
Terminal: Cannot read focus of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#22368]
Not sure how I got into this state but suddenly I see an error when I toggle the panel (with the terminal inside):

![image](https://cloud.githubusercontent.com/assets/900690/23790238/9649dd26-057e-11e7-9f14-376523a18ff9.png)

Using todays insider build.

**Comment by bpasero** [comment]
Not reproducible after a restart......

**Comment by Tyriar** [comment]
I can't repro either... Did the terminal otherwise work fine and you got a prompt when this happened?

**Comment by bpasero** [comment]
@Tyriar yes everything was working fine, I am using tmux btw.

**Comment by Tyriar** [comment]
Walked through the logic and it all seems like it should work so I added a null check to prevent the exception if it gets in that state.
