### ISSUE TITLE
Add option to Disable MDN link in .tsx/.jsx/.ts./.js IntelliSense

### ISSUE THREAD

**Issue by farhadxf** [microsoft/vscode#223634]
### Type: Feature Request

As a styled-components user, I believe the following improvements would significantly enhance the development experience in VS Code:

1. **Color Decorators on `.ts` and `.js` Files**
    - **Issue**: Color decorators are not functioning correctly.
    - **Request**: Provide an option to default to RGB values when defining color names (e.g., `red`). Also, enable RGB control when clicking on color decorators in `.ts` or `.tsx` files.

2. **Disable MDN Documentation on Hover**
    - **Issue**: The MDN documentation popup on hover in `.tsx/.ts` or `.jsx/.js` files is intrusive.
    - **Request**: Introduce an option to disable this feature for these file types.

These changes would greatly benefit many developers, especially those using styled-components with TS | JS.

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.5.0
Modes:

**Comment by mjbvz** [comment]
Please just one issue per issue. However the first is an extension candidate issue as we don't provide built-in color detection for js/ts files

Let's use this issue to track your second request: disabling mdn links in documentation
