### ISSUE TITLE
Could the keybindings  shortkeys internationalized

### ISSUE THREAD

**Issue by albu77** [Microsoft/vscode#22362]
- VSCode Version: 1.10.2
- OS Version: Windows 7

Steps to Reproduce:
There is a problem with keyboard layout (I'm using Azerty) when defiining a shortkey and even in the default keybinding file, for example shortcut labelled as xx+yy+\ but on an AZERTY keyboard it is xx+yy+:.
![image](https://cloud.githubusercontent.com/assets/624802/23787846/43290e6e-0574-11e7-9c07-4e8df6002250.png)
Is there a another  way of having the correct shortkeys,could it be possible to have several shortkeys default json one for each keyboard layout?

**Comment by nosick** [comment]
also russian

**Comment by alexandrudima** [comment]
We don't ship with keyboard layout specific default keybindings, that is something you can upvote in #1240
