### ISSUE TITLE
Configure unassigned keybindings, command name incorrect

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#223706]
- Place cursor in the panel chat
- Open the accessibility help
- Click on the icon `Accessibility Help Configure Unassigned Keybindings`
- The command list does not contain actual command names

https://github.com/user-attachments/assets/73b8b4da-2bdf-4664-9d47-7c7d2bde73a0

**Comment by meganrogge** [comment]
Good catch, this is a special case. It appears to be working for the others:

![Image](https://github.com/user-attachments/assets/3e042c77-783f-471c-b54a-34e80f10fd6a)
