### ISSUE TITLE
Does Profiles Editor need an Actions column?

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#223796]
I love the action in the Profiles Editor to `Open to the Side`, but I was confused why there is an entire column dedicated to this if it's just the same action for each entry:

![Image](https://github.com/user-attachments/assets/9ce05d51-af79-458d-9c6d-b20f88dd2755)

Is there a scenario and/or plan to have a greater variety of actions in the future? Or could it be an option to remove the Actions column and instead make the actual file names for instance clickable (and clicking on the file will open it to the side):

![Image](https://github.com/user-attachments/assets/8e47aac5-cfe0-4625-a3d5-3c22b7c4851a)

**Comment by isidorn** [comment]
Good points.
I think @sandy081 wanted to use a table as an implementation for this, and then just saved on column for the actions. The table works well in Create New Profile flow. 

I am not aware of any plans of adding more actions here. And I do agree that the actions column might not be needed.
Let's see what @sandy081 feels like. I am fine removing it and using some other UI.

![Image](https://github.com/user-attachments/assets/d9376de9-a0b6-4fe7-952c-3c2bf0489def)

**Comment by sandy081** [comment]
I have removed the title but not the column
