### ISSUE TITLE
Profiles Editor entry point name

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#223793]
Related to https://github.com/microsoft/vscode/issues/214617:

I love the new Profiles Editor! As one piece of feedback, I might've expected its entry point to be named something like `Editor`, `Profiles Editor`, `All Profiles`, `Configure`, or `Configure Profiles`, rather than just `Profiles`:

![Image](https://github.com/user-attachments/assets/906abaff-f5cf-45ca-84f4-e35c6c0b669e)

**Comment by isidorn** [comment]
Thanks Brigit. I like this suggestion. And I had a similar thought.
+1 for Profiles Editor, or Configure Profiles

Or alternatively, "Profiles...". The `...` should make it stand out more, and user input is actually expected (so it aligns with our naming patterns). I might prefer this name.

@sandy081 what do you think?

**Comment by sandy081** [comment]
It is consistent with existing editors like `Settings`, `Keyboard Shortcuts` and `Extensions`. Hence I called it `Profiles`

**Comment by sandy081** [comment]
From @bpasero:

> Similar maybe the command should be renamed then as well, because you are not "opening" profiles, you open a management UI to edit them.

![Image](https://github.com/user-attachments/assets/4c093b81-56e3-4464-87f1-bafa1e821cbe)

---

I chose this title to be consistent with Settings 

![Image](https://github.com/user-attachments/assets/27cd490c-4bf1-4c1d-90c3-2346acad636b)

**Comment by bpasero** [comment]
I also think this is a good change, I wonder for the wording: now we have "Profile" => "Profiles". How about something more explicit for the second entry:
* `Manage Profiles`
* `Manage`

Similar maybe the command should be renamed then as well:



![Image](https://github.com/user-attachments/assets/4c093b81-56e3-4464-87f1-bafa1e821cbe)

Because you are not "opening" profiles, you open a management UI to edit them.

**Comment by bpasero** [comment]
Btw I would not expect a `...` here because further input is not required. Similar to "Settings".

**Comment by isidorn** [comment]
Having process all the suggestions, "Configure Profiles" and "Manage Profiles" works best for me.
