### ISSUE TITLE
Add environment setup support for tasks configuration

### ISSUE THREAD

**Issue by Matumba2** [microsoft/vscode#22374]
Im using the tasks.json file to configure my grunt Tasks. Some of them expectect that a given environment variable is set, because they normally are executed with Jenkins where the used plugins for the job execution sets some environment variables I evaluate within the grunt tasks.

It would be awesome if it's possible to pass an array of environment variables, like it's possible with the command args, for example:

```
{
            "taskName": "myCustomGruntTask",
            "identifier": "myCustomGruntTask",
            "args": [""],

            // Set some environment variables here
            "env": [
                     { "PATH": "$PATH;Some value ..." },
                     { "BRANCH_NAME": "testBranch" },
                     .
                     .
                     .
             ]

            "isBuildCommand": true,
            "isWatching": false,
            "problemMatcher": [
                "$lessCompile",
                "$tsc", 
                "$jshint"
            ]
}
```

**Comment by Matumba2** [comment]
Additional it would be nice if it would be possible to replace the part
```
{ "BRANCH_NAME": "testBranch" }
```

with somethink like
```
{ "BRANCH_NAME": "{git.currentBranch}" }

**Comment by cnshenj** [comment]
Interestingly, the [schema of tasks.json](https://code.visualstudio.com/docs/editor/tasks_appendix) does have an `option` property which contains an `env` property. But it has no effect.

**Comment by dbaeumer** [comment]
This works if the task defines its own command and doesn't inherit the command from the global scope. Keep a feature request open to support this in a global use case as well.

**Comment by alexr00** [comment]
This works in tasks v2:
```
{
	"version": "2.0.0",
	"command": "echo %FOO%",
	"tasks": [
		{
			"type": "shell",
			"label": "echo the var",
			"options": {
				"env": {
					"FOO": "this is a foo"
				}
			}
		}
	]
}
```
Tasks v1 is not being developed. Closing since this is done!
