### ISSUE TITLE
tasks.json TypeScript build produces different errors than `tsc` on command line

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#22376]
_VSCode 1.10, Win10._

This is my task definition & the output of its run:

![image](https://cloud.githubusercontent.com/assets/101152/23792012/8cb821a8-0585-11e7-891c-016ec08f9d0d.png)

This is what I see when I execute `tsc` manually:

![image](https://cloud.githubusercontent.com/assets/101152/23792087/d57b5efa-0585-11e7-8ddf-c700634b6928.png)

How can they be different?

**Comment by borekb** [comment]
I've tried changing something in `tsconfig.json` and now, the Build action in VSCode doesn't report any errors while `tsc` and WebStorm do.

My guess at the moment is that there is something funny going around `tsconfig.json` changes.

**Comment by mjbvz** [comment]
@borekb There is likely a mismatch between the version of TypeScript you are using in the editor and the `tsc` you are running. To see what may be causing this, please:

* share your `tsconfig.json`.
* Are you using a workspace version of TypeScript? What version? Do you have a `typescript.tsdk` setting?
* What does `tsc --version` return?

**Comment by borekb** [comment]
Both versions are 2.2.1, both are invoked via `tsc`. I don't see a difference.

**Comment by mjbvz** [comment]
@borekb Please provide the other information as well

**Comment by borekb** [comment]
I cannot reproduce it so will close this issue. Just out of curiosity, @mjbvz, does it matter which version of TypeScript is configured for VSCode? I thought that these two lines in tsconfig.json:

```json
{
    "command": "tsc",
    "args": ["-p", "."]
}
```

mean that `tsc -p .` will be run on a command line literally. So that will use my system-wide `tsc`, right?
