### ISSUE TITLE
Visual Code will no longer launch under Centos7+SSH

### ISSUE THREAD

**Issue by drorl** [Microsoft/vscode#22371]
- VSCode Version: 1.10.2
- OS Version: Centos 7

Hi,
I recently installed Visual Code, I configutred it and managed to work with it successfuly for couple of days (both locally and using ssh).
However, since yesteday I can no longer work with it using SSH (I can do it only locally).
I type /bin/code --user-data-dir=/home/user/vscode,
then nothing happens. I tried changing the directory, uninstalling all plugins, reinstalling visual code, restarting the machine - nothing helped. 

Steps to Reproduce:
1.  Connect using SSH (I use MobaXtern for that, but I tried others as well) 
2. Type /bin/code --user-data-dir=/home/user/vscode, nothing happens
3. Run the same command locally and it launch fine...

Attaching a --verbose output:
[6425:0310/123937:WARNING:audio_manager.cc(314)] Multiple instances of AudioManager detected
[6425:0310/123937:WARNING:audio_manager.cc(275)] Multiple instances of AudioManager detected
[main 12:39:37 PM] Starting VS Code in verbose mode
[main 12:39:37 PM] from: /usr/share/code/resources/app
[main 12:39:37 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'user-data-dir': '/home/user/vscode' }
[6452:0310/123938:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 12:39:43 PM] IPC#vscode-workbenchLoaded
[6425:0310/123944:INFO:CONSOLE(66)] "Conflict detected, command `C_Cpp.SwitchHeaderSource` cannot be triggered by alt+o due to extension.switch", source: file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (66)
[main 12:39:44 PM] IPC#vscode:broadcast null vscode:changeColorTheme vs-dark vscode-theme-defaults-themes-dark_plus-json
 
Any suggestions?
Thanks!

**Comment by Tyriar** [comment]
@drorl maybe `--disable-gpu` will work?

```
/bin/code --disable-gpu --user-data-dir=/home/user/vscode
```

Closing this off as we don't officially support this so there's not much more we can help with.
