### ISSUE TITLE
Explorer greys out any folder/item with the word "cut"

### ISSUE THREAD

**Issue by KGeetings** [microsoft/vscode#223791]
Type: <b>Bug</b>

If you rename a folder to "Cut Sheet" for example, that folder and anything below it becomes a "greyed" out folder. If you have a file that is named "Cut Data.vba" for example, this is also greyed out. Renaming any of these makes them a normal folder/item icon. I have confirmed that this is not a .gitignore issue, nor does it appear to be a theme issue.

Please see the image below.
![Greyed Out VS Code](https://github.com/user-attachments/assets/f8807cc0-8ecf-4202-86c6-2b794e8947f7)

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (12.66GB free)|
|Process Argv|--crash-reporter-id 3137ea81-ae9a-485d-afa2-717d2bb5d0f9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
amazon-q-vscode|ama|1.17.0
vscode-intelephense-client|bme|1.10.4
phpserver|bra|3.0.2
vscode-yarn-script|car|0.0.1
path-intellisense|chr|2.9.0
codeium|Cod|1.10.1
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.55.0
composer-php-vscode|DEV|1.49.15728
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.49.15728
profiler-php-vscode|DEV|1.49.15728
xml|Dot|2.5.1
gitlens|eam|15.2.1
vscode-html-css|ecm|2.0.10
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
vscode-yarn|gam|2.1.0
copilot|Git|1.218.0
copilot-chat|Git|0.17.1
remotehub|Git|0.62.0
vscode-pull-request-github|Git|0.92.0
gc-excelviewer|Gra|4.2.59
todo-tree|Gru|0.0.226
vscode-test-explorer|hbe|2.21.1
better-cpp-syntax|jef|1.27.1
vscode-nuget-package-manager|jmr|1.1.6
cmake-language-support-vscode|jos|0.0.9
vscode-autohotkey-plus-plus|mar|5.0.5
rainbow-csv|mec|3.12.0
compare-folders|mos|0.24.3
vscode-docker|ms-|1.29.1
csdevkit|ms-|1.8.14
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.1
vscodeintellicode-csharp|ms-|2.1.11
debugpy|ms-|2024.8.0
gather|ms-|2022.3.2
isort|ms-|2023.10.1
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.379.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
cmake-tools|ms-|1.18.43
cpptools|ms-|1.21.3
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.14
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.2
test-adapter-converter|ms-|0.1.9
vscode-speech|ms-|0.10.0
vsliveshare|ms-|1.0.5936
indent-rainbow|ode|8.3.1
word-count|Oli|0.1.0
material-icon-theme|PKi|5.8.0
LiveServer|rit|5.7.9
vscode-vba|ser|0.11.0
logos-vscode|tal|1.0.1
pdf|tom|1.2.2
cmake|twx|0.0.17
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.15.0
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.27.0
vscode-maven|vsc|0.44.0
vscode-todo-highlight|way|1.0.5
php-debug|xde|1.35.0
php-pack|xde|1.0.3
php-intellisense|zob|1.3.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
refactorc:31101458
ccplc:31103425
pythonrstrctxt:31103193
wkspc-onlycs-t:31102394

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Do you have `cut` mentioned in `file.exclude` setting for user or workspace or do you have it in ignore file?

**Comment by KGeetings** [comment]
It still occurs when I reload window with extensions disabled. And I do not have `cut` mentioned in my files.exclude in my user or workspace settings JSON. My workspace does not have a a files.exclude. My user settings has the following: 

>"files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
	},

See attached image showing extensions disabled and both settings.json files.
![image](https://github.com/user-attachments/assets/ee998e56-7899-4b93-9955-519739ce1880)

And here's a picture of my .gitignore file:
![image](https://github.com/user-attachments/assets/5b705e25-ae18-4d13-89d0-019be7caf811)

**Comment by Ou7law007** [comment]
Same problem here

![image](https://github.com/user-attachments/assets/f249cdd9-f3c8-4a25-ae45-72b6dffd4faa)

**Comment by jeanp413** [comment]
PR fixing it https://github.com/microsoft/vscode/pull/225455
