### ISSUE TITLE
Tasks echoCommand does not show command in Terminal

### ISSUE THREAD

**Issue by wgj** [Microsoft/vscode#22377]
When using `echoCommand` in tasks.json, the command isn't echoed in the Integrated Terminal.

![harmlessunhappyfeline](https://cloud.githubusercontent.com/assets/463564/23792014/1f6e3312-053a-11e7-8799-ab677c442a94.gif)

- VSCode Version: 1.10.2 (1.10.2)
- OS Version: MacOS 10.12.3 (16D32)
- Tasks Version: 2.0.0

Steps to Reproduce:

1. Run Task "echoTest" with `echoCommand`.
```
      {
            "taskName": "echoTest",
            "command": "echo",
            "isShellCommand": true,
            "args": ["Hello World"],
            "showOutput": "always",
            "echoCommand": true
        }
```
2. Observe that output to Integrated Terminal does not prepend the underlying command of Task "echoTest" per [documentation](https://code.visualstudio.com/docs/editor/tasks#_echocommand).

**Comment by Tyriar** [comment]
@dbaeumer is this as designed under tasks v2?

**Comment by dbaeumer** [comment]
@Tyriar yes and no. I simply couldn't find a way to print something to the terminal. The command itself is started with the runTerminal and therefore it is not printed. Would it be possible for the terminal to echon that if I asked it to do so.

**Comment by Tyriar** [comment]
@dbaeumer it's not possible now, would this make sense as a member on `IShellLaunchConfig` that is parsed and written to the terminal front end before the process starts (including escape sequences)?

**Comment by dbaeumer** [comment]
Yes, would make perfect sense on `IShellLaunchConfig`

**Comment by Tyriar** [comment]
I added `IShellLaunchConfig.initialText` which you can set with escape sequences so you can style if you wish. Tested by setting: `_shellLaunchConfig.initialText = 'abc foo \x1b[33mbar\x1b[0m adsa';`, here's the result:

![image](https://cloud.githubusercontent.com/assets/2193314/23924045/5f52657c-08c6-11e7-8ced-96dc78fc4397.png)

Note my prompt has an empty line at the start so only the first line was added.

**Comment by wgj** [comment]
Hey everyone, 

I think we may have missed the usecase on this one. I have many tasks defined in task.json, and when I run them, I'd like visual feedback on what command, with which parameters, was ran. 

8481570 appears to prepend a hardcoded string to every shell instance, without a reference to a given task (as in `tasks.command` and `tasks.args`from tasks.json)

**Comment by dbaeumer** [comment]
@wgi this needs adoption in the task framework this is why I opened #22655

**Comment by wgj** [comment]
Alright :)

I don't understand the process, and I had a mild panic when I saw this issue had been closed. Thank you.
