### ISSUE TITLE
Hide interface suggestion in intellisense

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#22372]
- VSCode Version: 1.10.2
- OS Version: MacOs Sierra

Steps to Reproduce:
- in javascript file :
![suggestions](https://cloud.githubusercontent.com/assets/5599375/23790983/a50672d6-0581-11e7-84bd-bca63ccda0bc.gif)

Is there an existing option to hide all of this (never usefull) interfaces snippets ?
It completely foul my intellisense :(

**Comment by mjbvz** [comment]
All of the suggestions you are seeing are coming from the dom and many have associated instances. Instances are also used on their own for jsdocs typigns

To disable dom intellisense, create a `jsconfig.json` with the content:

```json
{
    "compilerOptions": {
        "lib": [
            "es2015"
        ]
    }
}
```

**Comment by DavidBabel** [comment]
omg thank you !

**Comment by DavidBabel** [comment]
Oh, this remove all methods from classic javascript too. Not usefull at all

**Comment by patrickxie** [comment]
were you able to solve this issue @DavidBabel? If so could you briefly state the solution to this problem? Thank you

**Comment by DavidBabel** [comment]
No i don't :(

**Comment by james89** [comment]
Looking for a way to do the same thing, the 'interface' types are just clogging up the autosuggestion list :/ and I know I'll never use them.

**Comment by mjbvz** [comment]
We're also working to improve this upstream on the TypeScript side: https://github.com/Microsoft/TypeScript/issues/15750

**Comment by kczx3** [comment]
Being able to filter out certain types of Intellisense would be a welcome addition.  I agree that the interfaces are just clutter.

**Comment by greggb** [comment]
Should this have been fixed with #27899?

**Comment by mjbvz** [comment]
@greggb Yes we did end up implementing this with #27899. Please let me know if you are still seeing unexpected JavaScript intellisense suggestions in VS Code 1.18

**Comment by greggb** [comment]
Yes, working perfectly. Thanks for the update.

**Comment by greggb** [comment]
For anyone stumbling on this issue, here's are the steops that got this working for me:

- Update to >= 1.18 and restart 
- Close all open js files
- `"javascript.implicitProjectConfig.checkJs": false` in your user settings.
- Save settings and reopen your files.

**Comment by greggb** [comment]
Actually, @mjbvz I'm seeing flakiness with this feature. Files will occasionally still show me these suggestions. Should I open a new issue?

**Comment by mjbvz** [comment]
@greggb Yes. Please include some sample code or a small example project that demonstrates the problem
