### ISSUE TITLE
How to use "oneOf" extension configuration?

### ISSUE THREAD

**Issue by ThisIsManta** [Microsoft/vscode#22375]
Inside package.json of my VS Code extension:
```
"contributes": {
  "configuration": {
    "properties": {
      "mysetting": {
        "type": "oneOf", // what attributes work with this type
        // let say the choices are: "aaa", "bbb", "ccc"
        "default": "aaa"
      }
    }
  }
}
```
Another question, I have another config which its value can be either **boolean** or **array of string**. How can I write that in extension config?

Thank you in advance.

I'm really desperate as I could not find detailed explanation of the **extension configuration schema** in the docs of the official site.

**Comment by hoovercj** [comment]
It is better to ask questions on Stackoverflow with the tag "vscode".

I'll try to help, though. If I have a configuration that has a set of valid values, such as "on" and "off", I use the enum attribute to specify what those values can be.

```
"myconfig.setting": {
    "type": "string",
    "enum": ["on", "off"]
    "default": "on"
}
```

Regarding multiple types, you can pass an array to `type` and then specify the type of the items like this:

```
"myconfig.setting": {
    "type": ["boolean", "array"],
    "default": true,
    "items": {
        "type": "string"
    }
}
```

**Comment by ThisIsManta** [comment]
Much appreciated!

**Comment by mrmlnc** [comment]
Just tip for future: also you can read – http://json-schema.org

**Comment by ThisIsManta** [comment]
Oh, I didn't realize it was JSON-schema. I'm such a fool. Thank you, **mrmlnc**
