### ISSUE TITLE
SCM: unable to open file from a change on the index

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#22373]
Steps to Reproduce:

1. stage a change and open the diff
2. try to find the action to open the file

=> does not exist
=> we have it in the old git world

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/blob/proxy-auth/extensions/git/package.json#L513

Now we don't have `OR`... what can I do?

**Comment by joaomoreno** [comment]
Fixed!

**Comment by joaomoreno** [comment]
Pushed hack fix. Very sad!

**Comment by bpasero** [comment]
![wow](https://cloud.githubusercontent.com/assets/900690/23794108/c510a620-058e-11e7-843e-30884a46c089.gif)
