### ISSUE TITLE
Global font size modifier

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#223766]
I would like a global font size modifier setting. I want to be able to increase the _font size_ of the editor and all UI elements **without** increasing the size of buttons and widgets and whatnot. I can change the zoom level, but that increases the size of sidebars and whatnot, squeezing the editor smaller. I can change the editor font size but that has no effect on the file explorer/etc.

**Comment by rzhao271** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/519
