### ISSUE TITLE
Move line down is not multi cursor aware

### ISSUE THREAD

**Issue by GrantSolar** [microsoft/vscode#22382]
This is likely related to issue #22380. Box selecting from top-to-bottom then shifting with ALT+UP/DOWN produces a different line order than if the box select was performed from bottom-to-top.

- VSCode Version: 1.10.2
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open a new file and paste in the following contents (note that there is no trailing whitespace):

```javascript
var a = 'apple crumble';
var b = 'bun'; 
var c = 'chocolate cake';
var d = 'doughnuts';
var e = 'egg';
```

2. Box select from the `b` in `bun` to the `g` in `doughnuts`
3. Release all keys then press ALT+DOWN

Resulting line order: a, c, b, d, e

4. Return the file to the original state
5. Box select from the `g` in `doughnuts` to the `b` in `bun` (reversed direction of selection to the above test)
6. Release all keys then press ALT+DOWN

Resulting line order: a, c, b, e, d

**Comment by alexandrudima** [comment]
Other steps:
> When I have N cursors on the same line and i duplicate the line, it's being duplicated N times instead of 1 time.

**Comment by alexdima** [comment]
Let's track in #11809
