### ISSUE TITLE
Feature Request - Add "Copy Relative Path" to Explorer

### ISSUE THREAD

**Issue by henryJack** [Microsoft/vscode#22386]
- VSCode Version: 1.10
- OS Version: Windows 10

Adding the correct relative path for import statements takes time. For example, if you have a lot of files in your project it takes time to determine the correct path i.e.
`import { Link } from '/data-structures/sanitised-data/link';`
`import { Link } from './data-structures/sanitised-data/link';`
`import { Link } from '../data-structures/sanitised-data/link';`
`import { Link } from '../../data-structures/sanitised-data/link';`
 It would be really useful if when you right click on a file in the VS Code explorer there was the option to `copy relative path` next to `Copy Path` and `Copy`. Where the relative path is compared to the active window you have open at the time so you can just copy the import statement in straight away.

**Comment by adambowles** [comment]
#12518

**Comment by henryJack** [comment]
Oops, mark as a duplicate in that case! I did try to search for other issues but none came up, honest (https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=Copy%20Relative%20Path)

**Comment by adambowles** [comment]
You can close this issue yourself if you're confident it's a duplicate 👍

**Comment by ramya-rao-a** [comment]
Thanks @adambowles 
Closing as duplicate

@henryJack you can add any additional thoughts to the linked item #12518
