### ISSUE TITLE
Selecting text using column select then moving lines up/down with ALT+arrow inconsistently affects lines

### ISSUE THREAD

**Issue by GrantSolar** [Microsoft/vscode#22380]
- VSCode Version: 1.10.2
- OS Version: Windows 10 x64

When selecting text using columns (either CTRL+SHIFT+ALT+ARROW or SHIFT+ALT+MOUSE1), moving the selected text using ALT+UP/DOWN will always shift the line of the initial cursor position. Shifting the other selected lines appears to depend on whether the selected column exists on the line above.

Steps to Reproduce:

1. Open a new file and paste in the following contents (note that there is no trailing whitespace):

```javascript
var a = 'apple crumble';
var b = 'bun'; 
var c = 'chocolate cake';
var d = 'doughnuts';
var e = 'egg';
```

2. Box select from the `a` in `apple crumble` to one of the `o`s in `chocolate cake`
3. Release all keys then press ALT+DOWN.

Expected result: All 3 selected lines move. Columns are still selected
Line order: d, a, b, c, e

Actual result: Only first line moves. Only first line has column selected
Line order: b, a, c, d, e

4. Return the file to the original order
5. Box select from the `r` in `apple crumble` to the `s` in `doughnuts`
6. Release all keys then press ALT+DOWN

Expected result: All 3 lines with selected text move. Columns are still selected
Line order: b, a, e, c, d

Actual result: Only first and third lines are moved. Only columns from these 2 lines are selected
Line order: b, a, d, c, e

**Comment by alexandrudima** [comment]
Let's track in #21400
