### ISSUE TITLE
Comment threads can end up with an empty expanded reply box

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#223842]
![Image](https://github.com/user-attachments/assets/34fe7ea9-970e-435d-b89d-f4bdaff07cef)

**Comment by alexr00** [comment]
Caused by https://github.com/microsoft/vscode/issues/214661. 

I caused https://github.com/microsoft/vscode/issues/214661 when I fixed an issue when there are multiple text editors open with the same uri with comments. When I tried to fix https://github.com/microsoft/vscode/issues/214661 I made it so when extensions call `createCommentThread` and pass in `[]` for the comments, we always expand the reply editor, resulting in the bad behavior above.

I took a quick look, and it seems very common for extensions to pass in `[]` for the comments and then immediately set them.

**Comment by alexr00** [comment]
To verify:
- Check out PR with comments that you left
- Reload to make sure there's not state left over from when you left the comments
- Open the file with the comments and click on the comment icon in the comment bar to expand the comment
- Verify that the reply input button is collapsed and isn't a big empty rectangle.

**Comment by isidorn** [comment]
Works great -> verified.
