### ISSUE TITLE
Duplicate go to definition request from LSP when use ctrl+click

### ISSUE THREAD

**Issue by chouzz** [microsoft/vscode#223817]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.92.0-insider
- OS Version: windows11

Seems vscode send two same go to definition requests from LSP, this could happened in any language server, here is an example from C/C++ language server.

When using shortcut(`ctrl+click`), press the first key `ctrl` will send definition request and if there are results, it will show a link with the symbol, and then continue pressing click, it will go to the symbol, the problem is that press the click will send the second definition request which exactly same with the first one. Seems it's duplicate request, vscode don't need the second request because it already gets the results from the first request.

Steps to Reproduce:

1. install C/C++ extension and enable debug log
2. Go to definition(use `ctrl+click`) for `foo`

Current behavior:
There are two requests from LSP for the same symbol

Expected behavior:
There should be only one request for definition request.

Logs from C/C++
```
...
LSP: Sending response (id: 35)
LSP: (received) textDocument/definition: file:///d%3A/src/samples/cpp/demo/expect_eq/expect_eq.c (id: 36)
LSP: (invoked) textDocument/definition: file:///d%3A/src/samples/cpp/demo/expect_eq/expect_eq.c (id: 36)
LSP: Sending response (id: 36)
LSP: (received) textDocument/definition: file:///d%3A/src/samples/cpp/demo/expect_eq/expect_eq.c (id: 37)
LSP: (invoked) textDocument/definition: file:///d%3A/src/samples/cpp/demo/expect_eq/expect_eq.c (id: 37)
...
```

Screenshot:

![image](https://github.com/user-attachments/assets/d2bd3c32-ada2-4c83-b340-6323c42ff96d)

**Comment by jrieken** [comment]
One request is for showing a preview in the hover and the second request is when clicking
