### ISSUE TITLE
build vscode from source code with release/1.85 MSB1009: Project file does not exist.

### ISSUE THREAD

**Issue by fuya-rule** [microsoft/vscode#223825]
vscode branch: release/1.85
os: windows 11 home
node.js version: v18.19.0
npm version: 10.5.2
yarn version: 1.22.22
vs build tools:  VS2022 (17.8.34330.188)
python: python310

Steps to Reproduce:
1. prerequisites build environment
2. cd vscode
3. yarn

error information:

[4/4] Building fresh packages...
[1/20] ⠂ @parcel/watcher
[2/20] ⠂ @vscode/policy-watcher
[3/20] ⠂ @vscode/windows-ca-certs
[6/20] ⠄ @vscode/sqlite3
error virtual_absolute_path\vscode\node_modules\@vscode\policy-watcher: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: virtual_absolute_path\vscode\node_modules\@vscode\policy-watcher
Output:
virtual_absolute_path\vscode\node_modules\@vscode\policy-watcher>if not defined npm_config_node_gyp (node "virtual_absolute_path\node18\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@18.19.0 | win32 | x64
gyp info find Python using Python version 3.10.9 found at "virtual_absolute_path\python310\python.exe"

gyp info find VS using VS2022 (17.8.34330.188) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn virtual_absolute_path\python310\python.exe
gyp info spawn args [
gyp info spawn args 'virtual_absolute_path\\node18\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'msvs',
gyp info spawn args '-I',
gyp info spawn args 'virtual_absolute_path\\vscode\\node_modules\\@vscode\\policy-watcher\\build\\config.gypi',
gyp info spawn args '-I',
gyp info spawn args 'virtual_absolute_path\\node18\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args '-I',
gyp info spawn args 'virtual_absolute_path\\AppData\\Local\\node-gyp\\Cache\\27.3.2\\include\\node\\common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=virtual_absolute_path\\AppData\\Local\\node-gyp\\Cache\\27.3.2',
gyp info spawn args '-Dnode_gyp_dir=virtual_absolute_path\\node18\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args '-Dnode_lib_file=virtual_absolute_path\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\27.3.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args '-Dmodule_root_dir=virtual_absolute_path\\vscode\\node_modules\\@vscode\\policy-watcher',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'virtual_absolute_path\\vscode\\node_modules\\@vscode\\policy-watcher\\build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args undefined,
gyp info spawn args '/clp:Verbosity=minimal',
gyp info spawn args '/nologo',
gyp info spawn args '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
MSBUILD : error MSB1009: Project file does not exist.
Switch: undefined
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (virtual_absolute_path\node18\node_modules\npm\node_modules\node-gyp\lib\build.js:209:23)
gyp ERR! stack at ChildProcess.emit (node:events:517:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:292:12)
gyp ERR! System Windows_NT 10.0.22631
gyp ERR! command "virtual_absolute_path\\node18\\node.exe" "virtual_absolute_path\\node18\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd virtual_absolute_path\test\vscode\node_modules\@vscode\policy-watcher

**Comment by TylerLeonhardt** [comment]
Have you tried building a newer version of this repo? `release/1.85` is quite old.
