### ISSUE TITLE
SCM - `scm.showOutgoingChanges` and `scm.showIncomingChanges` settings are ignored

### ISSUE THREAD

**Issue by prryplatypus** [microsoft/vscode#223832]
Type: <b>Bug</b>

1. Set the following settings in your user settings:
```
  "scm.showOutgoingChanges": "never",
  "scm.showIncomingChanges": "never",
```
2. Open a repository
3. Commit a change
4. Observe how the incoming/outgoing tree displays regardless of the setting

VS Code version: Code - Insiders 1.92.0-insider (bcbdd8e575684d6df1def9a478d645c37129c033, 2024-07-25T23:12:28.613Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|36.00GB (2.77GB free)|
|Process Argv|--crash-reporter-id 427cb644-d627-42a0-aa3a-ac68ebc3e7d1|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vsc_aa:30263845
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialogc:30812479
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
g316j359:31013175
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nb_pri_only:31057983
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
1iic9185:31091668
flighttreat:31102345

```

</details>

**Comment by prryplatypus** [comment]
<img width="1496" alt="Screenshot 2024-07-26 at 10 57 43" src="https://github.com/user-attachments/assets/8e418792-c847-4e80-acc4-d0c1298ef38b">

**Comment by prryplatypus** [comment]
@lszomoru - since you seem to be taking most if not all the SCM issues lately

**Comment by kursat-ozer** [comment]
When I found this issue I realized there are many features that we don't want to use. 

Just a personal note: Please, but really please, don't make any idea as feature. At least make it disabled as default and if someone wants to open it, s/he can search for it. 

Lets come back to topic. The main issue here is there are 2 very different (visually) features here. Let me explain:
1- The `showIncommingChanges`/`showOutgoingChanges` is a list of changes (not a git graphical visualization):

<img width="826" alt="Screenshot 2024-08-02 at 03 05 56" src="https://github.com/user-attachments/assets/8b0a602f-e5e6-4016-a9a7-217be1b8e9ef">




2- The `showHistoryGraph`is graphical visualization of the past commits:

<img width="1038" alt="Screenshot 2024-08-02 at 03 09 44" src="https://github.com/user-attachments/assets/8af6cefe-4df5-4ea2-8125-7f4bd02e6ef0">




As the result, bot features and their settings working correctly. 
Thanks, and keep going.

**Comment by prryplatypus** [comment]
> I see them as "Incoming/Outgoing", not "history graph".

So do they. It literally says "Incoming/Outgoing" at the top of the "history graph" 😁

**Comment by lszomoru** [comment]
These settings have been removed as the history graph has been moved into its own view - Source Control Graph.

**Comment by target-san** [comment]
Can you please clarify this? Does this mean we no longer are able to disable history graph?

**Comment by lszomoru** [comment]
The history graph is in its own view. You can both completely hide the view, or collapse it.
