### ISSUE TITLE
Go to definition does not find a definition in typescript

### ISSUE THREAD

**Issue by pkeuter** [Microsoft/vscode#22385]
- VSCode Version: 1.10.2
- OS Version: Win10 x64

Steps to Reproduce:

1.  Create a .ts file with this content: 
```
interface ITest {
    test(): void;
}

class Test implements ITest {
    test() {
        return null;
    }
}
```

2. Right click on the test() implementation and click 'go to definition'.  It will say there is "no definition found for 'test'". I expected it to go to the definition. 

Go to implementation from the interface does work.

**Comment by mjbvz** [comment]
The current behavior seems correct to me.  If you right click on `test` in `Test`, you are already at the definition of the method.

Are you expecting it to go to `ITest` `test` instead?

**Comment by pkeuter** [comment]
Yes, because test() in Test is the implementation, isn't it, and test() in ITest is the definition? I would say it's a good thing to let the user be able to go to the Interface from the implementation. From what I see, there is no way now to go directly to the Interface declaration from the class implementation, is there?

**Comment by mjbvz** [comment]
No not currently.

I'm still not sure that `go to definition` should go to the interface declaration in this case, but perhaps `go to type definition` should do what you describe?

I've opened https://github.com/Microsoft/TypeScript/issues/14588 against TypeScript to track this and discuss the design of this feature

Thanks.
