### ISSUE TITLE
Make update notifications less intrusive

### ISSUE THREAD

**Issue by HermanEldering** [Microsoft/vscode#22387]
It seems like VS Code has some kind of update each time I run it, which is great. However, the big notifications break my workflow. I would love it if the notifications could get out of my way.

- For me the notification has no use. I always click the button 'Later' and the update gets installed silently when I close/reopen at some time. It is a text editor, not a banking app that needs the latest security patch.

- The notification is rather big, so (for me) hard to ignore. Even if I could resist it I am forced to do it because it covers the tabs in the editor.

- If there are release notes, then I want to read those when it suits me. I don't want to interrupt something I'm working on to check the release notes and then figure out what I was supposed to be doing.

What I would like is there to be some kind of small unobtrusive notification (like the flag in regular Visual Studio) that would tell me that there is an update. It could also link to the release notes (after an update) so that I can leave it flagged until I have time to check out the new features. Or just have an option to turn off all notifications related to updates, and always install them silently.

**Comment by stevencl** [comment]
Thanks, we're exploring this here: https://github.com/Microsoft/vscode/issues/22388
