### ISSUE TITLE
Only show "The internet connection appears to be offline" message when relevant

### ISSUE THREAD

**Issue by johnbillion** [Microsoft/vscode#22381]
When using VS Code while not connected to the internet (eg. while traveling), the message stating `The internet connection appears to be offline` quickly becomes an annoyance.

This message ought to only appear when the user _actively_ performs an action which requires an internet connection, for example searching the extension marketplace. Alternatively, it could be replaced with a small icon in the status bar that's much more subtle.

- VSCode Version: 1.10.2
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Disconnect from the internet
2. Launch VS Code

**Comment by joaomoreno** [comment]
#21601
