### ISSUE TITLE
Code click has no response

### ISSUE THREAD

**Issue by fanjinweide** [microsoft/vscode#223834]
Type: <b>Bug</b>

I used two screens, and then split it into three compilers, which took up one and a half screens, and the first screen was sometimes insensitive to click

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.92GB (2.51GB free)|
|Process Argv|--crash-reporter-id 91f7e963-4294-45be-9591-f3367a07be79|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
cssrem|cip|3.1.1
vscode-eslint|dba|3.0.10
app-migrator|deb|0.0.6
auto-rename-tag|for|0.1.10
shell-format|fox|7.2.5
easy-less|mrc|2.0.2
vscode-language-pack-zh-hans|MS-|1.91.2024071009
vscode-css-peek|pra|4.4.1
any-rule|rus|0.3.18
css-tree|sac|1.1.0
open-in-browser|tec|2.0.0
volar|Vue|2.0.28

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31101459
ccplti:31103428
pythonrstrctxt:31103193

```

</details>

```[tasklist]
### Tasks
```

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
