### ISSUE TITLE
Intellisense import suggestions is acting up

### ISSUE THREAD

**Issue by gregg-cbs** [microsoft/vscode#223857]
### Something has broken intellisense importing

Does this issue occur when all extensions are disabled?: Yes

Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

Video Recording:
https://github.com/user-attachments/assets/b08c9dad-a81d-4fee-ae43-a20955447f02

Steps to Reproduce:
1. Create a couple files in an empty folder in vscode
2. use named exports to export some functions from those files
3. import those files and see intellisense will work and suggestion function imports
4. reload vscode by using ctrl+shift+p and using Developer: Reload window
5. now start typing the functions name to get import suggestions and notice there are no suggestions
6. this is happening on windows and mac, different vscodes in multiple projects and even blank folders
7. import suggestions seems to be broken regardless of doing 'reload window' or loading vscode for the first time

**Comment by mjbvz** [comment]
Please also share the example project you used to demonstrate this

**Comment by gregg-cbs** [comment]
this was a blank folder, it was no special project

**Comment by mjbvz** [comment]
Please share the code as text for all relevant files

**Comment by gregg-cbs** [comment]
This is happening across any project I open. It seems to be a bug with vscode. I think its less reported because people think its their computers or project setups but after experiencing this on different computers, different vscodes with different extensions, different operating systems and different projects it is safe to assume the problem lies in vscode somewhere.

Anyways we are just moving on with it.
