### ISSUE TITLE
Open the html in either Finder or specific Browser

### ISSUE THREAD

**Issue by upradeepk** [Microsoft/vscode#22384]
- VSCode Version:Version 1.9.1 (1.9.1)
- OS Version:10.11.5

Steps to Reproduce:

There is currently no option to open the html file in Finder or a browser directly from VSCode. You have to Reveal the item in Finder and then open it from there. Would be handy to have a open in browser feature directly.

**Comment by mjbvz** [comment]
Duplicate of #15928
