### ISSUE TITLE
Initializing JS/TS language features never complete!

### ISSUE THREAD

**Issue by callmeten** [microsoft/vscode#223850]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.91.1 (system setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1.  Create a .ts file and add a line of comment in the format of "/* * code--*/". 
![Snipaste_2024-07-26_18-13-29](https://github.com/user-attachments/assets/536fef04-9369-4c39-a09e-c8b12584059b)

**Comment by callmeten** [comment]
deleted "--" in the comment can resolve this issues!

**Comment by mjbvz** [comment]
I can't reproduce this

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
