### ISSUE TITLE
 TypeError: Cannot read property 'getControl' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#2239]
Issue Id: <b>ea508d4f-14d6-132b-af18-a803d3e91e54</b><br /><br />*Versions* <br />- 0.10.6-release<br />-  dfc08dc9edf6607483b193bf934d3badc3fa2e11<br />*Stack* <br />TypeError: Cannot read property 'getControl' of null<br />[/vs/workbench/api/common/mainThreadEditors.ts#L227:16 (MainThreadTextEditor.matches)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/workbench/api/common/mainThreadEditors.ts#L227:16 (MainThreadTextEditor.matches))<br />[/vs/workbench/api/common/pluginHostEditors.ts#L561:34 (MainThreadEditors._tryShowTextDocument)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/workbench/api/common/pluginHostEditors.ts#L561:34 (MainThreadEditors._tryShowTextDocument))<br />[/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1127:0 (_notify)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/base/common/winjs.base.raw.js#L1127:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1311:0 (_run)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/base/common/winjs.base.raw.js#L1311:0 (_run))<br />[/vs/workbench/api/common/pluginHostEditors.ts#L548:5 (MainThreadEditors._tryShowTextDocument.contd)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/workbench/api/common/pluginHostEditors.ts#L548:5 (MainThreadEditors._tryShowTextDocument.contd))<br />[/vs/workbench/api/common/pluginHostEditors.ts#L551:5 (MainThreadEditors._tryShowTextDocument)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/workbench/api/common/pluginHostEditors.ts#L551:5 (MainThreadEditors._tryShowTextDocument))<br />[/vs/base/common/callbackList.ts#L63:26 (CallbackList.invoke)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/base/common/callbackList.ts#L63:26 (CallbackList.invoke))<br />[/vs/base/common/event.ts#L107:26 (Emitter.fire)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/base/common/event.ts#L107:26 (Emitter.fire))<br />

**Comment by jrieken** [comment]
fixed by https://github.com/Microsoft/vscode/commit/0edca427dbef03a8bfd80a004bbec99003a88f7f
