### ISSUE TITLE
Path file not correct.

### ISSUE THREAD

**Issue by sosensible** [Microsoft/vscode#22393]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ColdFusion|ilich8086|0.0.5|
|vscode-angular2-emmet|jakethashi|1.0.11|
|Angular2|johnpapa|2.0.3|;

---

Steps to Reproduce:

1. Update Path file
2. In a fresh started VSC open terminal and enter path, no go on update

PATH=C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\Syst
em32\WindowsPowerShell\v1.0\;C:\WINDOWS\CCM;C:\WINDOWS\CCM;C:\WINDOWS\CCM;C:\WINDOWS\CCM;C:\WINDOWS\CCM;C:\WINDOWS\CCM;C:\WINDOWS\CCM;C:\WINDOWS\CCM;C:\WINDOWS\CCM;C:\WINDOWS\CCM;C:\WINDOWS\
CCM;C:\WINDOWS\CCM;C:\WINDOWS\CCM;C:\WINDOWS\CCM;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program
Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\nodejs\;C:\Program Files\Seapine\Surround
SCM;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\B
inn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Users\jfarrar\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin;C:\dev\box\.\jre\\bin

Note: The goal is figuring out how to get CommandBox running through the terminal.

https://www.ortussolutions.com/products/commandbox

Here is the actual path file.

C:\Users\jfarrar\AppData\Roaming\npm;c:\dev\box;C:\Program Files (x86)\Microsoft VS Code\bin;

**Comment by Tyriar** [comment]
You likely didn't completely close all VS Code windows before launching a new one. When VS Code is launched the environment will be set for all following windows to the current system `PATH`.
