### ISSUE TITLE
A recommended important extension should be shown on top of the recommendation list

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#22392]
Pls see below.

In the scenario below the Docker extension is recommended, but when I click on 'Show Recommendations' it appears somewhere in the list and I have to look for it.

I suggest to either show the recommended extension on top of the list. Or to filter the list so that only the Docker extension is shown.

![recommendation](https://cloud.githubusercontent.com/assets/172399/23796103/5c54df06-0599-11e7-851c-d50a690957ee.gif)

**Comment by joaomoreno** [comment]
Hard to do. What we could maybe do is provide a direct action to install that extension.

**Comment by philipmat** [comment]
Maybe pre-filter the list of extensions by some keyword (whatever triggered the recommendation, in @egamma's example *docker*).

**Comment by egamma** [comment]
@joaomoreno how about seeding the extensions viewlet with `@recommendations Docker`, then the viewlet is filtered for the recommended extension and the user can still read the README before installing the extension.

**Comment by joaomoreno** [comment]
Why don't we drop the `Show Recommendations` action for a `Open Extension` action, which will open that extension in the editor?

**Comment by ramya-rao-a** [comment]
In the September 2017 release, the important recommendation in the pop up will show in the top of the list

In the October 2017 release, an "Install" option is made available in the pop up
