### ISSUE TITLE
No keybindings in menu when running with Brazilian Portuguese layout

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#22399]
- VSCode Version: 1.11.0 - insider (01091bb)
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Menu shortcuts have disappeared.

I already uninstalled and installed again.

I installed an old version of Insiders and then I did the update and the problem continues.

I have already disabled all extensions.

![shortcuts](https://cloud.githubusercontent.com/assets/19866231/23800325/b47e9140-058a-11e7-9a94-958b9fb849d8.gif)

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by Tekbr** [comment]
@bpasero Command Prompt: 
```
[93m[main 08:23:12][0m Starting VS Code in verbose mode
[93m[main 08:23:12][0m from: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app
[93m[main 08:23:12][0m args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[93m[main 08:23:14][0m IPC#vscode-machineId
[93m[main 08:23:15][0m IPC#vscode-workbenchLoaded
[93m[main 08:23:16][0m IPC#vscode:broadcast null vscode:changeColorTheme vs-dark vscode-theme-defaults-themes-dark_plus-json
```

In the Toggle Developer Tools did not show anything!

**Comment by bpasero** [comment]
@Tekbr can you share your keybindings.json file?

**Comment by Tekbr** [comment]
@bpasero Is empty. I did not change the shortcuts.

**Comment by bpasero** [comment]
@Tekbr does it reproduce in stable?

**Comment by Tekbr** [comment]
@bpasero Stable works properly. The problem began to occur in the insiders in the quoted commit.

**Comment by bpasero** [comment]
@Tekbr does it change anything once you add a keybinding to keybindings.json?

**Comment by Tekbr** [comment]
@bpasero No. I added a default shortcut again and a modified one, and nothing happened.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@bpasero Even after some updates from Insiders, I still have the problem. I installed VSCode-insiders on Windows 8 on a Virtual Machine using VirtualBox and had the same problem. Were you able to reproduce the problem?

**Comment by bpasero** [comment]
@Tekbr no

**Comment by Tekbr** [comment]
@bpasero I use POR - PTB2 Portuguese keyboard (Brazil ABNT2).

**Comment by bpasero** [comment]
@Tekbr does it reproduce if you stop VS Code, change to US keyboard and then start again?

**Comment by Tekbr** [comment]
@bpasero The menu shortcuts are still not displayed after changing the keyboard language and starting the VSCode again.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@bpasero I installed VSCode - insiders on a virtual machine in Windows 8 in Spanish and I had the same problem.

![espw8](https://cloud.githubusercontent.com/assets/19866231/23995566/f2cd08bc-0a28-11e7-8e44-476a2ef3101a.gif)

I also installed VSCode - insiders in a virtual machine in Ubuntu 14.10 in Brazilian Portuguese and I had the same problem.

![ubuntu](https://cloud.githubusercontent.com/assets/19866231/23995572/f6a218ce-0a28-11e7-9a1d-f46e2570b7d7.gif)

**Comment by bpasero** [comment]
@Tekbr awesome I can reproduce when I use that language for the keybinding!

**Comment by Tekbr** [comment]
@bpasero Is it only Portuguese Brazil? As I showed in the gif with VM Windows 8 in Spanish it also does not load.

Windows 8 on the VM is entirely in Spanish. There was no installation in Portuguese and then change the language to Spanish.

**Comment by bpasero** [comment]
@Tekbr I have a fix ready, it is likely happening in a lot more keyboard layouts.

**Comment by Tekbr** [comment]
@bpasero Okay, thank you so much for the attention.

**Comment by bpasero** [comment]
Fixed, will be in tomorrows insider build.

**Comment by Tekbr** [comment]
Ohh, very fast. Thank you so much!!

**Comment by alexandrudima** [comment]
Verified on Ubuntu + Portuguese (Brazil)
