### ISSUE TITLE
Terminal quick fix results in `@vscode /explain` in panel chat

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#223948]
1. run a command that yields an error in the terminal
2. use the quick fix, `Explain Using Copilot` in the terminal, `cmd+.` -> `
3. See `@vscode /explain #terminalLastCommand` in panel chat

![Image](https://github.com/user-attachments/assets/3e9c9db1-0967-453c-a1f0-dfb7f7af4efd)

**Comment by bhavyaus** [comment]
I'm unable to repro this. However I do see an issue with additional unnecessary contexts being invoked

![Image](https://github.com/user-attachments/assets/cb94dc5f-bcc7-49ea-a2d1-e0875c703d72)

**Comment by joyceerhl** [comment]
I cannot reproduce this behavior when coming from the terminal quick fix @meganrogge:



![Image](https://github.com/user-attachments/assets/50fbc2f1-8e41-4d55-af25-47728d659f42)

**Comment by joyceerhl** [comment]
But the very first time I attempt submitting the query, I see that `@terminal` is not picked up by VS Code, cc @roblourens:

![Image](https://github.com/user-attachments/assets/5b8a2566-c3da-4630-b4c5-3556c27ad507)

**Comment by joyceerhl** [comment]
Actually, I now repro `@terminal` not being picked up 100% of the time. We have two `@terminal`s and we're picking the first one, then dropping it because it's not available in panel chat https://github.com/microsoft/vscode-copilot/blob/be960dbb84447b100951e51c1257e509eac8064a/package.json#L280-L314. https://github.com/microsoft/vscode/pull/224220

**Comment by meganrogge** [comment]
Today, I'm not seeing the copilot quick fix in the terminal at all 🤷‍♀ 

![Image](https://github.com/user-attachments/assets/cc3e27c2-0758-48a5-abd1-d9c059d9f359)

**Comment by joyceerhl** [comment]
Works for me on Windows with Powershell, latest Insiders + prerelease :shrug:
