### ISSUE TITLE
Let StoppedEvent's 'description' attribute override 'reason'

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#22398]
With DAP change https://github.com/Microsoft/vscode-debugadapter-node/issues/105 we have introduced a new optional `description` attribute for the textual representation of the StoppedEvent's reason.

As a consequence VS Code now needs to make use of the `description` attribute when showing the reason. The new strategy is as follows:
- if `description` exists use the string in the UI without modification.
- if `description` does not exist use the old behaviour (that is embed the `reason` attribute in the "Paused on" string). 
- code that needs to interpret the reason can now safely use the `reason` attribute without being affected by translations.

**Comment by isidorn** [comment]
@michelkaporin please verify
