### ISSUE TITLE
Insider's Update unable to close ExtensionHost during Update on Windows

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#22396]
For the last 3-4 days, the Insider's update has been failing when using the "Update Now" button. The Setup is failing to close background processes and gives the following error:

![codeupdateerror](https://cloud.githubusercontent.com/assets/6662208/23797682/a3b65718-0566-11e7-8786-70096677b17a.png)

I can see that there are still multiple Processes running that aren't getting closed.

![codeupdaterunning](https://cloud.githubusercontent.com/assets/6662208/23797725/ce69d4c6-0566-11e7-9320-c964505e8349.png)

When looking at what processes are still running with Process Explorer you can see that these are Extension Host processes with child Extension Processes.

![codeupdateecthost](https://cloud.githubusercontent.com/assets/6662208/23797766/033178ee-0567-11e7-9453-184563c08b2b.png)

The 2 parent processes show the ExtensionHost commandline

```
"C:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\bootstrap" --type=extensionHost
```

![codeupdateexthostparent](https://cloud.githubusercontent.com/assets/6662208/23797774/0951841c-0567-11e7-8bcb-7a884724e4d2.png)

I have to manually kill these processes to get the update to continue.

- VSCode Version: 1.11.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. I have several windows open when updating, but unsure if this has any impact. I am running the PowerShell Extension which is 2 of the still running child processes of the 2 running Extension Hosts.
2. Click the "Update Now" button to start the Update.
3. When it starts to update it errors saying it was unable to close all of the running Code processes.

**Comment by joaomoreno** [comment]
There must be an extension preventing the shutdown of the extension host process, may be that PowerShell extension.

Does the problem reproduce when shutting down Code manually (not from an update). I.e.: do processes lay around?

Does the problem reproduce when disabling the PowerShell extension?

**Comment by gerane** [comment]
@joaomoreno I will try this on the next update. I didn't have code open when it updated this morning.

cc @daviwil

**Comment by joaomoreno** [comment]
You can simulate an update by just redownloading Code's setup.exe and running that while Code is running.

**Comment by gerane** [comment]
@joaomoreno If I close out of all of the windows naturally by using context menu, there doesn't seem to be any left over processes. I also tried disabling PowerShell Extension, closing all windows and reopening, but still get the same error.

I then tried open a single new window without an open project or file and saw the same behavior.

So I closed Code, made sure there were no processes running, and reopened a single window of code using `--disable-extensions`, but still getting the error. 

So, I tried manually closing it again and ran it with no windows open, and it ran without issue. 

Anything else I can try? Currently the only way I can get it to work is by manually closing Code.

**Comment by joaomoreno** [comment]
Currently out of ideas @gerane. 😕

**Comment by gerane** [comment]
It seems it has cleared up over the last week or so for me now. @joaomoreno do you want to close this and I'll just open a new one and reference this one if I see it again?

**Comment by joaomoreno** [comment]
Let's close it, you can just ping me here if it happens again.
