### ISSUE TITLE
Remote extension host terminates

### ISSUE THREAD

**Issue by dgolod-oncai** [microsoft/vscode#223961]
Type: <b>Bug</b>

Start up VS Code on WSL and error seen
"Remove Extension host terminated unexpectedly 3 time within the last 5 minutes."

VS Code version: Code - Insiders 1.92.0-insider (4d17e85cfd911fb6b116e08a4d7c37cd725a966a, 2024-07-26T13:12:28.318Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.75GB (52.54GB free)|
|Process Argv|--file-uri vscode-remote://wsl%2Bubuntu-22.04/home/dgolod/src/nsclc-classifier/nsclc-classifier.code-workspace --crash-reporter-id 18690a16-8ea5-4a56-b5c6-d270807e7c95|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 0)|
|Memory (System)|47.05GB (45.91GB free)|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
01bff139:31013167
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
2f103344:31071589
nb_pkg_only:31057982
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
hdi1a554:31091669
flightc:31105041
nativeloc2:31101556

```

</details>

**Comment by chrmarti** [comment]
Maybe from an extension. Could you run `F1` > `Help: Start Extension Bisect` to check?

**Comment by dgolod-oncai** [comment]
Unlikely. This is what I can see when doing "Extension Bisect":
![image](https://github.com/user-attachments/assets/859b49e1-5634-4a90-a247-76c5b1b81afa)

**Comment by chrmarti** [comment]
In this case you would choose "I can reproduce". It will then reload with a different set of extensions enabled.

**Comment by dgolod-oncai** [comment]
I should have been clearer, this was the first pass during which all of the extensions were disabled. I have a total of 23 extensions. If I click "I can reproduce" it will give me 
![image](https://github.com/user-attachments/assets/faf24e06-e45d-4373-a84f-d2836fa2c2e2)

**Comment by chrmarti** [comment]
Maybe https://github.com/docker/for-mac/issues/6824? Which version of Docker Desktop are you using?
