### ISSUE TITLE
Is it possible to use wsl bash php for php.validate.executablePath

### ISSUE THREAD

**Issue by g0ld3lux** [Microsoft/vscode#22391]
Can Someone Clarify to me if i can use my php in WSL ?

**Comment by dbaeumer** [comment]
In principal yes. However you need to use the `c:\windows\sysnative\bash.exe` as the `php.validate.executablePath` and then use the php executable as a command line argument to bash. You might also want to consider passing -c so that the shell exists when the php executable has finished.

**Comment by codeguy** [comment]
Following up on this since  I cannot get it to work here using Windows Creators Update,  WSL enabled, with latest VSCode. I have set `php.validate.executablePath` to `C:\\Windows\\sysnative\\bash.exe`, to `C:\\Windows\\sysnative\\bash.exe -c`, to `C:\\Windows\\sysnative\\bash.exe -c php`, and it does not work in VSCode. It either does not recognize the executable path, or it simply does not work. Do you have any further thoughts on this? I'd love to integrate VSCode with WSL php, but there seems to be a translation issue when VSCode tries to find binaries or tries to supply Windows C:\ style file paths into WSL.

**Comment by codeguy** [comment]
I also tried using `C:\\Users\\josh\\bin\\RunInBash.exe php`, and that did not work. See:

https://neosmart.net/blog/2017/meet-your-new-best-friend-for-wsl/

**Comment by dbaeumer** [comment]
@codeguy you are right. It doesn't work. I forgot to consider that we besides the pure executable pass additional command line arguments to the executable. These arguments make the bash start fail. To fix this we need to add an additional property to the configuration to request validation in a shell. Something like `php.validate.inShell: Boolean | { executable: string; shellArgs: string[] }`

**Comment by dbaeumer** [comment]
@codeguy would you be willing to work on a PR for this. The code is here: https://github.com/Microsoft/vscode/blob/master/extensions/php/src/features/validationProvider.ts#L248

**Comment by codeguy** [comment]
For sure! I'll fork and work on it later today.

**Comment by codeguy** [comment]
See https://github.com/Microsoft/vscode/pull/25576

**Comment by dbaeumer** [comment]
@codeguy Great. Will look at the PR.

**Comment by tooy** [comment]
this is possible with a old school .bat
php.bat 
`@echo off
c:\windows\sysnative\bash.exe -c "php %*"`
setting.json
`"php.validate.executablePath": "c:\\PATH_TO\\php.bat"`

**Comment by GioBonvi** [comment]
While I am happy to see that this problem is being addressed I managed to put together two workaround scripts as I could not get any of the scripts found online to work (like the one posted by @tooy).

This one is called `php.bat` and is placed in `C:\wsl-tools\`:  

```batch
@echo OFF
setlocal ENABLEDELAYEDEXPANSION

rem Collect the arguments and replace:
rem  '\' with '/'
rem  'c:' with 'mnt/c'
rem  '"' with '\"'
set v_params=%*
set v_params=%v_params:\=/%
set v_params=%v_params:C:=/mnt/c%
set v_params=%v_params%
set v_params=%v_params:"=\"%

rem Call the windows-php inside WSL.
rem windows-php is just a script which passes the arguments onto
rem the original php executable and converts its output from UNIX
rem syntax to Windows syntax.
C:\Windows\sysnative\bash.exe -l -c "windows-php %v_params%"
```

This one is called `windows-php` and is placed somewhere in the WSL path (i chose `/usr/local/bin`).

```bash
# Pass all the arguments to PHP.
output=$(php "$@")
# Perform UNIX->WINDOWS syntax replacements.
output="${output//$'\n'/$'\r'$'\n'}"
output="${output//\/mnt\/c/C:}"
output="${output//\//\\}"
# Echo corrected output.
echo $output
```

Setting `"php.validate.executablePath": "c:\\wsl-tools\\php.bat"` works for me.

**Comment by roblourens** [comment]
@dbaeumer Is this still needed? Did you look at the PR?

**Comment by dbaeumer** [comment]
@roblourens that slipped through the cracks. I will look at the PR but in general we should look into a more generic solution to WSL than this. 

And what is about the PHP language server. Does that report errors and might make the start of the php executable obsolete ?

**Comment by roblourens** [comment]
I don't believe any of the PHP intellisense extensions have done any work in particular to support WSL.

If this is hard to land, I won't push for it. I'd rather see the extensions implement it, but I don't see anyone filing issues on them for it.

**Comment by erdemece** [comment]
Any news about this? Thanks.

**Comment by dbaeumer** [comment]
No news yet on this particular item. But we started thinking about how we could better support WSL to make these errors be handled more generically than on a extension by extension base.

**Comment by jstummbillig** [comment]
Any update? :)

**Comment by rodrigoratan** [comment]
@GioBonvi , I liked the idea but my Wsl dont have a C:\Windows\sysnative\bash.exe file, I'm using Ubuntu

**Comment by edwinhuish** [comment]
@neyronius any news? I tried, and still error.

![image](https://user-images.githubusercontent.com/5207925/45253036-e9912200-b392-11e8-9cc9-2367bd419f67.png)

![image](https://user-images.githubusercontent.com/5207925/45253040-00d00f80-b393-11e8-8b5b-5975181e784a.png)


![image](https://user-images.githubusercontent.com/5207925/45253076-9f5c7080-b393-11e8-8d5f-baf043b6b030.png)

**Comment by sachieldvangel** [comment]
"php.validate.executablePath": "wsl php"

**Comment by resonancedesigns** [comment]
I was excited about @GioBonvi & @neyronius batch script fix for this until I tried it and god "Error spawning PHP: Command failed: C:\Dev\Scripts\wsl\php.bat --version zsh:1: command not found: php" so I guess if you have zsh or something similar installed, this work-around won't work... Any news on official wsl php support?

**Comment by tanmancan** [comment]
@resonancedesigns 
I was able to get @GioBonvi script working by using `C:\Windows\System32\wsl.exe` as @neyronius suggested. But I kept the second file. I am using zsh, but I do not get any errors.

I also added `#!/bin/bash` to the top of the `windows-php` script. Just one thing to note - I did change the path from C:\ to D:\ in the replacements.


The scripts are in `D:\wsl-tools\` and `windows-php` is symlinked inside my `/usr/local/bin`.

```
windows-php -> /mnt/d/wsl-tools/windows-php
```

**php.bat**

```bat
@echo OFF
setlocal ENABLEDELAYEDEXPANSION

rem Collect the arguments and replace:
rem  '\' with '/'
rem  'd:' with 'mnt/d'
rem  '"' with '\"'
set v_params=%*
set v_params=%v_params:\=/%
set v_params=%v_params:D:=/mnt/d%
set v_params=%v_params%
set v_params=%v_params:"=\"%

rem Call the windows-php inside WSL.
rem windows-php is just a script which passes the arguments onto
rem the original php executable and converts its output from UNIX
rem syntax to Windows syntax.
C:\Windows\system32\bash.exe -l -c "windows-php %v_params%"
```

**windows-php**
```bash
#!/bin/bash
# Pass all the arguments to PHP.
output=$(php "$@")
# Perform UNIX->WINDOWS syntax replacements.
output="${output//$'\n'/$'\r'$'\n'}"
output="${output//\/mnt\/d/D:}"
output="${output//\//\\}"
# Echo corrected output.
echo $output
```

**Comment by ianzhi** [comment]
这么久了，也没有官方的解决方案么。。。

**Comment by edwinhuish** [comment]
> 这么久了，也没有官方的解决方案么。。。

@ianzhi  请看清楚 @GioBonvi 和 @tanmancan 的解决方案。。。

**Comment by ianzhi** [comment]
> > 这么久了，也没有官方的解决方案么。。。
> 
> @ianzhi 请看清楚 @GioBonvi 和 @tanmancan 的解决方案。。。

ok,tks

**Comment by RMacfarlane** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development

**Comment by erdemece** [comment]
How does remote development solve this issue? What is the setting for php.validateexecutablePath now?

**Comment by roblourens** [comment]
See some details about developing in WSL here: https://code.visualstudio.com/docs/remote/wsl

In that scenario, that setting would be the path to PHP on the WSL side.

**Comment by erdemece** [comment]
> See some details about developing in WSL here: https://code.visualstudio.com/docs/remote/wsl
> 
> In that scenario, that setting would be the path to PHP on the WSL side.

```
{
    "php.validate.executablePath": "/usr/bin/php",
}

This doesn't work. Im sorry I am not very good at these things.

I run code-insiders from wsl and I have all the remote development extensions installed.
```

**Comment by edwinhuish** [comment]
> > See some details about developing in WSL here: https://code.visualstudio.com/docs/remote/wsl
> > In that scenario, that setting would be the path to PHP on the WSL side.
> 
> ```
> {
>     "php.validate.executablePath": "/usr/bin/php",
> }
> 
> This doesn't work. Im sorry I am not very good at these things.
> 
> I run code-insiders from wsl and I have all the remote development extensions installed.
> ```

I don't know why the people like to wrote very short words with link which is very long history.

The solution correctly is:

1. Install [Visual Studio Code Insiders](https://code.visualstudio.com/insiders/), (***NOT THE NORMAL ONE***)
2. Install [Remote - WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)  for [Visual Studio Code Insiders](https://code.visualstudio.com/insiders/) (***NOT THE NORMAL ONE***)
3. Open [Visual Studio Code Insiders](https://code.visualstudio.com/insiders/) by ```$ code-insiders <path>``` in the WSL bash

**NOW YOU CAN ENJOY YOUR VSCODE IN WSL**
