### ISSUE TITLE
Git - terse error message when doing a git commit

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#22390]
Please see the screenshot below. The error message only consists of a file name.  

Minimally add a generic message that a git operation failed.

What is strange about the error message is that the file that is causing the trouble is .vscode/launch.json, but the .vscode folder is listed in the .gitignore file.

![image](https://cloud.githubusercontent.com/assets/172399/23795735/61d7bfb8-0597-11e7-8919-2e1bb940dba4.png)

**Comment by joaomoreno** [comment]
This should be fixed now, please give it another try:

![image](https://cloud.githubusercontent.com/assets/22350/24190521/1ba14ba8-0ee9-11e7-8c0a-9ba47e35ad27.png)
