### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'activateByEvent' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#2240]
Issue Id: <b>3c9fb48e-1ae2-0107-91ae-22bdb75982f2</b><br /><br />*Versions* <br />- 0.10.6-release<br />-  dfc08dc9edf6607483b193bf934d3badc3fa2e11<br />*Stack* <br />TypeError: Cannot read property 'activateByEvent' of undefined<br />[/vs/workbench/services/keybinding/electron-browser/pluginKeybindingService.ts#L525:29 (PluginWorkbenchKeybindingService._invokeHandler)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/workbench/services/keybinding/electron-browser/pluginKeybindingService.ts#L525:29 (PluginWorkbenchKeybindingService._invokeHandler))<br />[/vs/platform/keybinding/browser/keybindingServiceImpl.ts#L260:8 (KeybindingService._dispatch)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/platform/keybinding/browser/keybindingServiceImpl.ts#L260:8 (KeybindingService._dispatch))<br />[/vs/platform/keybinding/browser/keybindingServiceImpl.ts#L157:8 (KeybindingService.constructor)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/platform/keybinding/browser/keybindingServiceImpl.ts#L157:8 (KeybindingService.constructor))<br />[/vs/base/browser/dom.ts#L277:2 (handler)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/base/browser/dom.ts#L277:2 (handler))<br />    at EventEmitter.ipc.sendSync (C:\Program Files (x86)\Microsoft VS Code\resources\atom.asar\renderer\api\lib\ipc.js:21:31) <no sourcemaps><br />    at BrowserWindow.Object.defineProperty.get [as id] (C:\Program Files (x86)\Microsoft VS Code\resources\atom.asar\renderer\api\lib\remote.js:160:27) <no sourcemaps><br />[/vs/workbench/services/window/electron-browser/windowService.ts#L64:35 (WindowService.getWindowId)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/workbench/services/window/electron-browser/windowService.ts#L64:35 (WindowService.getWindowId))<br />[/vs/workbench/services/lifecycle/electron-browser/lifecycleService.ts#L29:36 (LifecycleService.registerListeners)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/workbench/services/lifecycle/electron-browser/lifecycleService.ts#L29:36 (LifecycleService.registerListeners))<br />[/vs/workbench/services/lifecycle/electron-browser/lifecycleService.ts#L25:7 (LifecycleService.constructor)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/workbench/services/lifecycle/electron-browser/lifecycleService.ts#L25:7 (LifecycleService.constructor))<br />[/vs/workbench/electron-browser/shell.ts#L298:25 (WorkbenchShell.initInstantiationService)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/workbench/electron-browser/shell.ts#L298:25 (WorkbenchShell.initInstantiationService))<br />

**Comment by alexandrudima** [comment]
Added check:
```typescript
	protected _invokeHandler(commandId: string, args: any): TPromise<any> {
		if (this._pluginService) {
			return this._pluginService.activateByEvent('onCommand:' + commandId).then(_ => {
				return super._invokeHandler(commandId, args);
			});
		}
		return TPromise.as(null);
	}
```
