### ISSUE TITLE
Terminal suggest: Environment variable completion doesn't work good when the variable is the first part

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#224036]
Repro:

1. Windows/pwsh
2. Suggest enabled
3. Open pwsh
4. Type $env, 🐛  suggestions don't show
5. Press ctrl+space, 🐛  suggestions still don't show

**Comment by rzhao271** [comment]
I still get the bug in step 4.
For step 5, I'm unsure whether I'm seeing the right suggestions:

![Suggestions seem to list everything as a completion to env](https://github.com/user-attachments/assets/5aad9ac0-4421-4cfe-8ae1-9e7725b34958)
