### ISSUE TITLE
Executing .ipynb cell scrolls to next cell, not to output

### ISSUE THREAD

**Issue by p-i-** [microsoft/vscode#224045]
Type: <b>Bug</b>

Suppose we execute a .ipynb cell.

This cell produces output. But VSCode scrolls so that the next cell is now at the top of my .ipynb window.

This means that to see the output, I have to scroll up.

It's very disorienting, as I'm now staring at alien code (I'm fixing an old notebook, and I haven't yet turned my attention to later cells).

So I don't instantly know where I am, or where to scroll, or what to do.

Sensible behaviour would be one of the following:
1. the notebook scrolls so that the output is at the top of the screen
2. (better) the notebook scrolls so that the end of the code-cell and the start of the output are both visible.
3. the notebook animated-scrolls to (2), hence removing any opportunity for disorientation.

I'll attach screenshots in a followup message.

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:46.768Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|24.00GB (0.52GB free)|
|Process Argv|--crash-reporter-id f10d97cd-2115-4dba-a34a-07be9312995a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
dvt-remote-ssh|ami|1.0.0
nestedtext|bma|2.0.0
githistory|don|0.6.20
copilot|Git|1.218.1013
copilot-chat|Git|0.17.2024062801
vsc-python-indent|Kev|1.18.0
rainbow-csv|mec|3.12.0
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.375.1
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
yaml-cloudformation-highlighter|paq|2.0.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31094925
refactort:31101459
ccplc:31098109
pythonrstrctxt:31093869

```

</details>

**Comment by p-i-** [comment]
Before executing with SHIFT+ENTER:
<img width="789" alt="Screenshot 2024-07-27 at 07 15 00" src="https://github.com/user-attachments/assets/2707fb21-1f5d-4bc6-9111-479d634f690d">

After executing:
<img width="780" alt="Screenshot 2024-07-27 at 07 15 12" src="https://github.com/user-attachments/assets/4adeb35b-16f5-476a-a61d-3d217c1c23e7">

**Comment by p-i-** [comment]
PS on the subject of smooth-scroll, this would be _really_ nice in the case when you're using DOWN key to scroll thru lines of your cell, and you pass down into the next cell. Currently your whole screen is replaced instantly. Probably this qualifies as a separate feature request, but I'll suggest it here for your consideration.

**Comment by amunger** [comment]
can you try the setting `"notebook.scrolling.revealNextCellOnExecute": "firstLine"` and see if that is closer to your expected behavior

**Comment by p-i-** [comment]
@amunger Yes, it is an improvement, thankyou!

However it still glitches.

Consider the following case:

https://github.com/user-attachments/assets/f589986a-0bcf-46fb-be2c-704980d6178a

When I execute, it catapults me into the middle of the next cell, and I don't even get to _see_ the output:

It really jangles to have everything in front of me disappear and be replaced with something else.

A smooth animation with a sigmoid transition-curve would solve all of this.

**Comment by p-i-** [comment]
Closing, as I've created a clean fresh issue.
