### ISSUE TITLE
Hex/Binary display of debug variables in C++

### ISSUE THREAD

**Issue by nilanjan** [Microsoft/vscode#22406]
- VSCode Version:
- OS Version:

Please add the C++ debug variable display format support. For example HEX/Binary etc. Absolutely imperative feature for C++ developers.

**Comment by sean-mcmanus** [comment]
You can display the debugger values in hex via "var, h" with the Windows debugger, but I'm not sure how to do that with gdb (I assume there's some command you can use). I don't know if VS Code has a way for us to add a hex option.

**Comment by nilanjan** [comment]
I am trying on OS, X and Linux. Is there any way I can do this?

**Comment by isidorn** [comment]
Please file this is a feature request to the c++ vscode extension here
https://github.com/Microsoft/vscode-cpptools

thank you
