### ISSUE TITLE
How to dynamically contribute to the menu?

### ISSUE THREAD

**Issue by MrYZhou** [microsoft/vscode#224090]
According to the document https://code.visualstudio.com/api/references/contribution-points#contributes.menus I found the contribute menu title button.

![image](https://github.com/user-attachments/assets/2e4e553f-7e97-456d-83b6-e66da0d8c3ba)

so,my code like :
"contributes": {
    "commands": [
      {
        "command": "dy-btn.action",
        "title": "add dynamic button11",
        "icon": "$(debug-start)"
      }
    ],
    "menus": {
        "editor/title": [{
            "command": "dy-btn.action",
            "group": "navigation"
        }]
    },

But static configuration is troublesome, I need a personalized API. Allow me to register myself in the code. For example, providing an API: 
`vscode. menus. registMenus()`

**Comment by gjsjohnmurray** [comment]
Related to #110218.

**Comment by MrYZhou** [comment]
comment on issue Related to https://github.com/microsoft/vscode/issues/110218.
