### ISSUE TITLE
Strange search behavior in default settings.json

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#22408]
Hi,

- VSCode Version: 1.10.2
- OS Version: macOS Sierra

I see that in default settings it is not possible to just press Cmd+F for search as in any other file (I really don't see a rational reason...why? it breaks the UX...), but at least pressing Cmd+F could put the caret inside that "special" search bar, so one can start searching right after pressing the common shortcut.

Thanks!

**Comment by jasonhuhx** [comment]
Agree, pressing Cmd+F should focus cursor at search bar

**Comment by sandy081** [comment]
Sorry for it. It used to work and the behaviour broke after. It got fixed in latest insiders. Please try insiders [here](http://code.visualstudio.com/insiders) and provide feedback. Thanks.
