### ISSUE TITLE
Extension Pack dependencies are not being installed

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#22405]
- VSCode Version: Insiders latest
- OS Version: Mac 10.11.1

Steps to Reproduce:

1. Uninstall all extensions
2. Search for [Node.js extension pack](https://marketplace.visualstudio.com/items?itemName=waderyan.nodejs-extension-pack) in extension viewlet. 
3. Click dependencies

I expect to see a list of the dependencies as contained in the extension [manifest file](https://github.com/waderyan/nodejs-extension-pack/blob/master/package.json#L30). 

Instead I see a blank list. 

![image](https://cloud.githubusercontent.com/assets/2449568/23804797/491d2228-0570-11e7-9544-e31f7a201812.png)

4. Install the extension.

I expect to see a prompt asking me to install all the dependences. 
Instead I do not see the prompt. 

I expect to see the dependencies installed. 
Instead none of the dependences are installed and I see errors in the dependencies tab. 

![image](https://cloud.githubusercontent.com/assets/2449568/23804859/7dff9a70-0570-11e7-989c-b6b61b93408e.png)

Some things I have tried:
- change all the extension and publisher names to lower case
- match the engine to the [Azure extension pack](https://github.com/Microsoft/vscode-azure-pack/blob/master/package.json)

**Comment by waderyan** [comment]
@sandy081 trying to debug this on my own... it seems that the Marketplace is not giving us the correct data:

![image](https://cloud.githubusercontent.com/assets/2449568/23805266/0a53d0a8-0572-11e7-81d0-f9a2a796a36e.png)

**Comment by sandy081** [comment]
@waderyan May I know what version of VSCE are you using to publish the extension. If not latest, can you please update it and try? 

Also can you please generate the VSIX file using your VSCE and provide it to me ?

Thanks

**Comment by waderyan** [comment]
That fixed it!
