### ISSUE TITLE
No codicon found for CompletionItemKind undefined

### ISSUE THREAD

**Issue by hetchzhao** [microsoft/vscode#224040]
monaco-editor-core: 0.33.0
monaco-languageclient: 0.18.1
reconnecting-websocket: 3.2.2
vscode-json-languageservice: 4.1.9
vscode-languageserver: 7.0.0

According to the code below, I want to establish a connection with the backend and implement the code completion feature. The connection has been established, but the frontend displays an error. However, according to the documentation, I have set the kind property, and during breakpoint inspection, I found that some data has kind, while some do not. In fact, I have set the kind property for each object.

```
      await languageClient.value.onReady();
      languages.register({
        id: 'sql',
        extensions: ['.sql'],
      });

      languages.registerCompletionItemProvider("sql", {
        provideCompletionItems: (model, position) => {
          const params = {
            textDocument: {
              uri: model.uri.toString(),
            },
            position: {
              line: position.lineNumber - 1,
              character: position.column - 1
            }
          };
          return languageClient.value.sendRequest<Array<{
            label: string,
            kind: number,
            detail: string,
            documentation: string,
            insertText: string,
            range: Range,
          }>>("textDocument/completion", params)
            .then((items) => {
              const suggestions = items.map((item) => ({
                label: item.label,
                insertText: item.insertText,
                kind: languages.CompletionItemKind.Keyword,
                range: new Range(
                  position.lineNumber,
                  position.column,
                  position.lineNumber,
                  position.column
                ),
              }));
              return {
                suggestions: suggestions,
              }
            });
        },
        resolveCompletionItem: (completionItem) => {
          return languageClient.value.sendRequest<languages.CompletionItem>("completionItem/resolve", completionItem)
            .then((resolvedCompletionItem) => {
              console.log("resolvedCompletionItem", resolvedCompletionItem);
              completionItem.documentation = resolvedCompletionItem.documentation;
              completionItem.detail = resolvedCompletionItem.detail;
              return completionItem;
            })
        }
```

<img width="1217" alt="image" src="https://github.com/user-attachments/assets/05df5d8b-0257-4ab8-8723-0b29ed53c1c3">
<img width="792" alt="image" src="https://github.com/user-attachments/assets/88090802-cca6-4a5f-8106-4915df3184e3">
<img width="781" alt="image" src="https://github.com/user-attachments/assets/3e8c422c-9aed-4d25-9fdf-4cc0f27d4984">
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/6dbd1c66-e4c1-4913-8fb6-50ffd6b1ac07">

**Comment by jrieken** [comment]
Please provide a minimal set of steps/data that is required to reproduce this.
