### ISSUE TITLE
[Debug] VSCode is sending empty "hover" evaluate requests to debug adapters.

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#22407]
- VSCode Version: 1.10.2
- OS Version: macOS Sierra 10.12.3

VSCode seems to be sending "hover" evaluate requests for "" (empty string) to debug adapters when the cursor is hovering over non-identifier symbols (semicolons, parentheses, brackets, etc).

I can't think of a language where an empty string would evaluate to anything meaningful, so this is must be a bug.

**Comment by isidorn** [comment]
Nice catch, thanks!
You can try this out in tomorrow's vscode insiders
