### ISSUE TITLE
Search in settings editor is showing invalid results for search term '4'

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#22401]
![image001](https://cloud.githubusercontent.com/assets/10746682/23804454/3683da4a-05ba-11e7-920b-022f6a19b27b.png)

**Comment by sandy081** [comment]
Looks like a bug in our prefix matching.. This also occurs here

![image](https://cloud.githubusercontent.com/assets/10746682/23809350/a38a86d0-05cd-11e7-94e9-dc487e468f0f.png)

@joaomoreno FYI

**Comment by joaomoreno** [comment]
@bpasero

**Comment by rpjproost** [comment]
The problem is in the _matchesPrefix method in `base\common\filter.ts`

```
	const wordChar = word.charCodeAt(i);
	const wordToMatchAgainstChar = wordToMatchAgainst.charCodeAt(i)
```
"4"=52 and for "T"= 84

``` 
	const diff = wordChar - wordToMatchAgainstChar;
	if (diff === 32 || diff === -32) {
           continue;
        }
```

Not sure why the 32 value is used though, so I don't know how to change it at this moment.

**Comment by sandy081** [comment]
@bpasero @joaomoreno any reason behind this logic in prefix matching

**Comment by rpjproost** [comment]
Made a PR: #22743 
Adjusted the method to exactly the same phenomenon in `base/common/strings.ts`

**Comment by wimspaargaren** [comment]
@sandy081 We think to have figured it out. The distance between an upperCase and lowerCase [Javascript characters](https://www.w3schools.com/charsets/ref_html_ascii.asp) is 32, but a capital T minus 32 happens to be the letter 4. So the thing which was wrong here, was also doing this check for numbers, so we adjusted the `isALphanumeric` to `isAsciiLetter`.

**Comment by bpasero** [comment]
@wimspaargaren thanks, you pointed to the right problem. I pushed a fix to reuse code I had written already in strings.ts so that we do not end up having 2 implementations of the same [`beginsWithIgnoreCase`](/Users/bpasero/Development/monaco/src/vs/base/common/strings.ts) logic.
