### ISSUE TITLE
Aux window: `WindowMode.Custom` cleanup

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#224051]
With https://github.com/microsoft/vscode/pull/222315, a new `WindowMode.Custom` was added. This is to enforce a native title bar (I believe).

I suggest to make this more explicit and not by hijacking the `WindowMode` property, which is mainly for driving if the window is fullscreen, maximized or not.

**Comment by bpasero** [comment]
Adding myself to review a PR from this work.

**Comment by bpasero** [comment]
One idea: maybe we could make custom title bar actually work for the issue reporter? That should not be too hard 🙏

**Comment by justschen** [comment]
yep! i think the first instinct was actually that I tried 

https://github.com/microsoft/vscode/blob/a1a996552e4676a0f3e77ff73ea6a15f761b3dda/src/vs/workbench/browser/parts/editor/auxiliaryEditorPart.ts#L119

iirc, i wasn't sure what to do with some of the typings so i scrapped it and went for the native title bar 😅 

I'll give it another look and let you know if I have questions 👍

**Comment by bpasero** [comment]
Yes that should work, but you might have to add some flags to the custom title bar to prevent things like command center or layout controls to appear. But should be all doable, I think we only want the window controls.
