### ISSUE TITLE
Debug in terminal broken in Insiders

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#22409]
- Debug Node app with `"console": "integratedTerminal"`, on Windows or Mac, inspector or legacy
- Terminal opens, nothing happens
- Error: "Cannot launch debug target in terminal (timeout)."

**Comment by isidorn** [comment]
I believe this is coming from the [`TerminalSupport`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/terminalSupport.ts#L19) thus forwarding to @weinand  and @Tyriar

**Comment by Tyriar** [comment]
@roblourens have any relevant settings? And what platform?

**Comment by roblourens** [comment]
Windows or Mac at least. All you have to do is have any simple Node app, add `"console": "integratedTerminal"` to your launch config, and start debugging.

**Comment by Tyriar** [comment]
@weinand this was due to a change I made around `ITerminalConfiguration` (I didn't meant for it to be exposed outside the part). Please review/tidy up https://github.com/Microsoft/vscode/commit/b431c763ded1508b148590a10d140585c2055a2e, I'm not sure how to verify debugging on the dev build.

**Comment by weinand** [comment]
@Tyriar I've verified this on macOS and Windows. Thanks for fixing this.
