### ISSUE TITLE
CSS @media in HTML file breaks syntax highlighting

### ISSUE THREAD

**Issue by ggregoire** [Microsoft/vscode#22404]
- VSCode Version: last one
- OS Version: macOS

Hi,

`@media` into `<style></style>` breaks the syntax highlighting.

![screen shot 2017-03-10 at 11 00 17](https://cloud.githubusercontent.com/assets/591804/23804767/e70f76b0-0580-11e7-9340-b00cfc0260f7.png)

**Comment by aeschli** [comment]
Reproduce with
```html
<html>
<style>
h1 {
  color: red;
  
}@media only screen {
  
}
</style>
</html>
```

**Comment by aeschli** [comment]
This issue was moved to atom/language-css#107
