### ISSUE TITLE
`vscode.executeCodeActionProvider` result not eqal to `WorkspaceEdit.renameFile`

### ISSUE THREAD

**Issue by AlexCannonball** [microsoft/vscode#224064]
Type: <b>Bug</b>

Hello,

I've made unit/integration tests for vscode extension via `@vscode/test-electron`.

When I compare an actual `renameFile` code action obtained via

```ts
async function getCodeActions(
  uri: Uri,
  expectedRange: Range,
): Promise<CodeAction[]> {
  return commands.executeCommand<CodeAction[]>(
    'vscode.executeCodeActionProvider',
    uri,
    expectedRange,
  );
}
```

and the expected code action created via

```ts
const renameFileAction: TExpectedActions = function (uri, { parsedMessage }) {
  const fixedUri = Uri.joinPath(uri, '..', parsedMessage[FIX_KEY]);

  const action = new CodeAction('', CodeActionKind.QuickFix);

  action.isPreferred = true;
  action.edit = new WorkspaceEdit();

  action.edit.renameFile(uri, fixedUri, {
    overwrite: false,
  });

  return [action];
};
```

I see that there is difference in `edit.c[0].to._formatted` property. The value in actual object is not null, unlike the expected value (red color for the actual value):

![image](https://github.com/user-attachments/assets/637ee9cd-3da9-4a2a-812e-c63213cb4bb6)

The extension code building this code action is similar to the snippet for expected object in tests:

```ts
    const action = new CodeAction(
      `Rename the file to '${parsedMessage[FIX_KEY]}'`,
      CodeActionKind.QuickFix,
    );

    action.isPreferred = true;
    action.edit = new WorkspaceEdit();

    const fixedUri: Uri = Uri.joinPath(uri, '..', parsedMessage[FIX_KEY]);

    action.edit.renameFile(uri, fixedUri, { overwrite: false });
```

The issue is reproduced when I run tests normally and isn't reproduced when I debug the extension tests with breakpoints.

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|14.82GB (6.24GB free)|
|Process Argv|--log info --log plex.vscode-protolint=trace --crash-reporter-id 1760485e-64d5-4472-924c-6ff6ba32397c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
remote-wsl|ms-|0.88.2
vscode-twoslash-queries|Ort|1.2.2
vscode-yaml|red|1.15.0
code-spell-checker|str|3.0.1
pretty-ts-errors|Yoa|0.5.4
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactorc:31101458
pythonrstrctxtcf:31093870
wkspc-onlycs-t:31100202

```

</details>

**Comment by jrieken** [comment]
> I see that there is difference in edit.c[0].to._formatted property. The value in actual object is not null, unlike the expected value (red color for the actual value):

That's an internal property that's used for caching. It will be populated when reading `.fsPath`

**Comment by AlexCannonball** [comment]
Thank you for the reply, just for the record, I have fixed my test calling `toString()` method:

```ts
const renameFileAction: TExpectedActions = function (uri, { parsedMessage }) {
  const fixedUri = Uri.joinPath(uri, '..', parsedMessage[FIX_KEY]);

  fixedUri.toString(); // Here.

  const action = new CodeAction('', CodeActionKind.QuickFix);

  action.isPreferred = true;
  action.edit = new WorkspaceEdit();

  action.edit.renameFile(uri, fixedUri, {
    overwrite: false,
  });

  return [action];
};
```
