### ISSUE TITLE
[html] Auto-indent to the next level after pressing `Enter` at the end of a tag name

### ISSUE THREAD

**Issue by e22m4u** [microsoft/vscode#224197]
When you pressing Enter at the end of a tag name the cursor should go to the next indentation level to avioid pressing the Tab button to fix attributes indentation.

<img src="https://github.com/user-attachments/assets/8e8d679c-ccca-4712-bd53-f2cbcf4797a5" width="500">
<br/>
<br/>  
This makes sense when you starts typing many wrapped attributes.
<br/>
<br/>
<img src="https://github.com/user-attachments/assets/be8bce50-57c6-444a-90ec-eb2bca12d6e3" width="500">

**Comment by Tiny1233** [comment]
If you type `enter` after character `>` like '<div>[press enter]', the mouse pointer will go to the next indention level, if you don't type `>`, the mouse pointer will go to the same indention level.
