### ISSUE TITLE
Docs opened by "Open loaded scripts" are blank after debug session

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#22417]
- Start legacy protocol debug session
- Open something via "Open loaded scripts"
- Stop debugging

All new tabs are still open, but their contents are blank. I think either they should stay visible, or the docs should be closed completely.

**Comment by isidorn** [comment]
Can not reproduce. Please let me know what are you doing different than me in this gif?
Also please note this issue https://github.com/Microsoft/vscode/issues/22741

![loadedscripts](https://cloud.githubusercontent.com/assets/1926584/25394814/5cee42da-29df-11e7-88a1-8f6154b2a098.gif)
