### ISSUE TITLE
DebugAdapterExecutable does not support passing `shell: true` so `.bat`-based debug adapters are broken in current Insiders

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#224184]
In current Insiders (and presumably the upcoming release), spawning a `.bat` file on Windows without `shell: true` fails due to a breaking change in NodeJS:

https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2

> It is important to note that there has been a breaking change for Windows users who utilize `child_process.spawn` and `child_process.spawnSync`. Node.js will now error with `EINVAL` if a `.bat` or `.cmd` file is passed to `child_process.spawn` and `child_process.spawnSync` without the `shell` option set.

It appears that there's no way to signal this to [DebugAdapterExecutable](https://code.visualstudio.com/api/references/vscode-api#DebugAdapterExecutable) and therefore any `.bat`-based debug adapters launched this way fail in current Insiders (and will presumably fail in stable soon).

Could `shell: bool?` be added to `DebugAdapterExecutableOptions`? I don't know enough to contribute this, but this seems quite important.

**Comment by DanTup** [comment]
I started trying to fix this here:

https://github.com/DanTup/vscode/commit/750a66d8f62a59fb027ea487c2484f0d749c63e2

However I'm unable to get VS Code compiling locally, it spews lots of errors that don't make much sense to me:

```
[watch-extensions] [14:54:13] Error: C:/Dev/Microsoft/vscode/.vscode/extensions/vscode-selfhost-test-provider/src/importGraph.ts(8,26): Cannot find module 'cockatiel' or its corresponding type declarations.
[watch-extensions] [14:54:13] Error: C:/Dev/Microsoft/vscode/extensions/css-language-features/client/src/browser/cssClientMain.ts(22,40): Type 'Worker' has no properties in common with type 'LanguageClientOptions'.
[watch-extensions] [14:54:13] Error: C:/Dev/Microsoft/vscode/extensions/html-language-features/client/src/browser/htmlClientMain.ts(21,40): Type 'Worker' has no properties in common with type 'LanguageClientOptions'.
[watch-extensions] [14:54:13] Error: C:/Dev/Microsoft/vscode/extensions/git/src/encoding.ts(83,83): Argument of type '{ detectEncodings: string[]; } | undefined' is not assignable to parameter of type '{ minimumThreshold: number; } | undefined'.
[watch-extensions]   Object literal may only specify known properties, and 'detectEncodings' does not exist in type '{ minimumThreshold: number; }'.
[watch-extensions] [14:54:13] Error: C:/Dev/Microsoft/vscode/extensions/json-language-features/client/src/browser/jsonClientMain.ts(21,40): Type 'Worker' has no properties in common with type 'LanguageClientOptions'.
[watch-extensions] [14:54:13] Error: C:/Dev/Microsoft/vscode/extensions/vscode-api-tests/src/singlefolder-tests/proxy.test.ts(9,21): Cannot find module 'node-forge' or its corresponding type declarations.
[watch-extensions] [14:54:13] Error: C:/Dev/Microsoft/vscode/extensions/vscode-api-tests/src/singlefolder-tests/proxy.test.ts(13,45): Cannot find module 'straightforward' or its corresponding type declarations.
[watch-extensions] [14:54:13] Error: C:/Dev/Microsoft/vscode/extensions/vscode-api-tests/src/singlefolder-tests/proxy.test.ts(88,27): Parameter 'context' implicitly has an 'any' type.
[watch-extensions] [14:54:13] Error: C:/Dev/Microsoft/vscode/extensions/vscode-api-tests/src/singlefolder-tests/proxy.test.ts(88,36): Parameter 'next' implicitly has an 'any' type.
[watch-extensions] [14:54:13] Error: C:/Dev/Microsoft/vscode/extensions/vscode-api-tests/src/singlefolder-tests/proxy.test.ts(94,23): Binding element 'clientSocket' implicitly has an 'any' type.
[watch-extensions] [14:54:13] Error: C:/Dev/Microsoft/vscode/extensions/typescript-language-features/src/languageFeatures/fileConfigurationManager.ts(194,4): Object literal may only specify known properties, and 'preferTypeOnlyAutoImports' does not exist in type 'UserPreferences'.
[watch-extensions] [14:54:13] Error: C:/Dev/Microsoft/vscode/extensions/typescript-language-features/src/typescriptService.ts(79,20): 'ts.server.protocol' has no exported member named 'MapCodeRequestArgs'. Did you mean 'CodeFixRequestArgs'?
[watch-extensions] [14:54:13] Error: C:/Dev/Microsoft/vscode/extensions/typescript-language-features/src/typescriptService.ts(79,46): 'ts.server.protocol' has no exported member named 'MapCodeResponse'. Did you mean 'CodeFixResponse'?
[watch-extensions] [14:54:13] Error: C:/Dev/Microsoft/vscode/extensions/typescript-language-features/src/typescriptService.ts(80,26): Namespace 'ts.server.protocol' has no exported member 'GetPasteEditsRequestArgs'.
[watch-extensions] [14:54:13] Error: C:/Dev/Microsoft/vscode/extensions/typescript-language-features/src/typescriptService.ts(80,58): Namespace 'ts.server.protocol' has no exported member 'GetPasteEditsResponse'.
```

I'm happy for someone else to fix this if it's faster :-)

**Comment by DanTup** [comment]
I managed to solve my build errors (I was missing spectre-mitigated libraries from the VS installer), however I'm still unable to run from sources - it claims a file doesn't exist that definitely does:

![image](https://github.com/user-attachments/assets/ca762d85-1689-429d-ae7f-698a2ad957dd)

**Comment by DanTup** [comment]
I have a fix in a PR at https://github.com/microsoft/vscode/pull/224204


Although because I sneakily have a space in the path to my DA, I also noticed that enabling `shell: true` also changes behaviour, and the path to the executable will need quoting/escaping. I've called this out on the doc for `shell` because it's something extension authors will need to consider when switching to use this.

![Screenshot 2024-07-29 165337](https://github.com/user-attachments/assets/172f0042-40e7-4ffb-a960-ab39a9f3bf17)

![Screenshot 2024-07-29 165356](https://github.com/user-attachments/assets/ad121d63-820c-47b1-91ad-f480afd6d0f9)

**Comment by DanTup** [comment]
@roblourens I noticed you assigned this to the August milestone - does this mean that the next stable will ship without a fix for this? It breaks debug adapters that use `.bat` like Flutter, which will affect a considerable number of users.

**Comment by roblourens** [comment]
Well, I can't take the PR for the next Stable because it adds extension API and we can't add that two days before we release. I'll take a look at this. 

Maybe you could wrap your `.bat` in a node script where you can call `spawn` yourself, and vscode can run the node script?

**Comment by connor4312** [comment]
Please see https://github.com/gitkraken/vscode-gitlens/issues/3387 for guidance -- that was the issue template we automated posting on on extensions that contained `bat` files.

This is not really related to DAP. DAP does not know anything about the runtime that debug adapters are executed in.

**Comment by DanTup** [comment]
@roblourens 

> Well, I can't take the PR for the next Stable because it adds extension API and we can't add that two days before we release. I'll take a look at this.

The Flutter extension has almost 9m installs and this issue breaks starting debug sessions for all of them on Windows. Surely if a critical issue like this is discovered right before a release, some solution should be looked at? The change could be made without an API change by having VS Code just check for `.bat` on the end of the DA executable, but I'm not sure if that's a better fix.

> Maybe you could wrap your .bat in a node script where you can call spawn yourself, and vscode can run the node script? You just have to connect the stdin and stdout pipes.

This might work, but I suspect there are edge cases (like handling termination of additional processes) that IMO make this a riskier fix to ship the day before a release than adding `shell: true`.

@connor4312 

> Please see https://github.com/gitkraken/vscode-gitlens/issues/3387 for guidance

Dart-Code never got this template. If I did, I could've sent the PR weeks ago :-(

But I think you have misunderstood the issue. I am familiar with the breaking change - this is a process being spawned by VS Code, not the extension. All my extension code has always used `shell: true` where necessary, but this is code where we provide the executable and args to VS Code and it spawns the process - it does not use (and gives us no ability to pass) `shell: true`. Please see [my linked PR](https://github.com/microsoft/vscode/pull/224204) which fixes the issue.

**Comment by roblourens** [comment]
I just discussed this with Connor, and we agree that this is different than the other issues. We can likely check for a DebugAdapterExecutable command that ends in `.bat` and set the shell flag ourselves (and escape spaces). We can do that on vscode's end without new API. And maybe can get that in before the next stable release. I will try that out today.
