### ISSUE TITLE
Aux window: open issue reporter on current screen

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#224137]
atm, when you open a new aux window when your main vs code window is in another secondary screen/monitor, it will open the aux window the main screen/monitor.

- in these two examples, i have one large curved secondary monitor where vs code is.
- open an aux window, and it spawns it in my laptop's screen.
- same thing if full screened on secondary monitor. different when full screen on main screen (see https://github.com/microsoft/vscode/issues/224136)

https://github.com/user-attachments/assets/44837bfe-703d-4883-b49e-cbb3a3cc66ad

https://github.com/user-attachments/assets/d3181ab7-b897-4f7f-99e6-9751630eede9

wondering if there is a way it can spawn on the current screen? ie, centered to where the vs code window is.

**Comment by bpasero** [comment]
@justschen that should be possible if you provide the coordinates for where to open the window via `IAuxiliaryWindowOpenOptions`:

https://github.com/microsoft/vscode/blob/d12c0c7892a9ff59f62091eee061d471614dc206/src/vs/workbench/services/auxiliaryWindow/browser/auxiliaryWindowService.ts#L244

You would have to calculate the right coordinates based on all opened monitors, which is a bit tricky and probably requires you to go to the main process to do the math. This could be exposed from the `nativeHostMainService`.

Alternatively, another custom vscode feature flag that allows you to pass in the identifier of a window to center the issue reporter over.
