### ISSUE TITLE
Aux window: prevent fullscreen for issue reporter

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#224136]
when in full screened, opening an aux window will always make that aux window full screen

example with issue and `move to new window`:

https://github.com/user-attachments/assets/284a062a-0f4a-4658-bad7-ac7048a94169

normal issue reporter:

https://github.com/user-attachments/assets/e7d00ff8-e45d-4aaf-b7bf-a8e44eca439b

is there a flag or a way to make it not full screened? played around with:
https://github.com/microsoft/vscode/blob/a1a996552e4676a0f3e77ff73ea6a15f761b3dda/src/vs/workbench/services/auxiliaryWindow/browser/auxiliaryWindowService.ts#L326

but wasn't able to change anything when it was full screened

**Comment by bpasero** [comment]
@justschen if you want to take a stab at this, it seems possible to prevent fullscreen by setting `fullscreenable: false` here in the `BrowserWindowConstructorOptions`:

https://github.com/microsoft/vscode/blob/5cebe615e66c4a58bbc4552adf1da7891b62602b/src/vs/platform/auxiliaryWindow/electron-main/auxiliaryWindowsMainService.ts#L90-L94

In that case the window will not be allowed to be made fullscreen, you can only maximize it.

For that we probably need another vscode specific window feature to be sent down to the main process.
