### ISSUE TITLE
vscode extension `configurationDefaults` load slow

### ISSUE THREAD

**Issue by wszgrcy** [microsoft/vscode#224108]
- VS Code Version: 1.91.1
- OS Version: windows 10

Steps to Reproduce:

1.  write a vscode extension
2.  add 

```
    "configurationDefaults": {
      "workbench.colorTheme": "Default Light+"
    },
```
3. if theme not config( default light).The theme will first brighten and then darken
4. Similar mutations may also occur in other configurations

**Comment by sandy081** [comment]
Yes, configuration defaults are loaded later - when extensions are loaded. VS Code built in configurations are loaded on start up to give better experience. Postponing them until config defaults are loaded give bad experience to the user/
