### ISSUE TITLE
Provide a way (command) to switch between panes of a diff view

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#22412]
- VSCode Version: Code - Insiders 1.11.0-insider (01091bb0831f7ce07db3cdc3ad66abb4141ffd8d, 2017-03-10T07:05:03.565Z)
- OS Version: Darwin x64 16.4.0

---

Currently I can't find a way switch between the right and left panes of a diff editor. It would be great if there was a command to do it both for shortcut keys and extensions.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/16707
