### ISSUE TITLE
[Theme] allow to set editor gutter background

### ISSUE THREAD

**Issue by gforcada** [Microsoft/vscode#22410]
- VSCode Version:  1.10.2
- OS Version: Linux Fedora 25

When working with code that is all about nesting (i.e. SCSS) one really needs to see if the closing bracket 10 lines below the one you are in is at the very beginning or it has still some nesting. Usually editors help on that by having the line numbers background color be slightly different from the code background color.

So far I haven't seen any theme that makes this difference, is that because it is not possible? I would love to have that.

**Comment by ramya-rao-a** [comment]
Can you share a screenshot of the expected behavior from any other editor that does this?

**Comment by gforcada** [comment]
@ramya-rao-a yes of course, here it is
![lines](https://cloud.githubusercontent.com/assets/1155680/23833543/cc66c43a-0747-11e7-8f56-7c609b5b6da6.png)

You can clearly see where the lines and gutter ends and where the code starts.

**Comment by alexandrudima** [comment]
@gforcada Would any of the following work for you:

#### Option 1. indent guides `"editor.renderIndentGuides": true`
![image](https://cloud.githubusercontent.com/assets/5047891/24407903/8f98ec68-13cc-11e7-9550-d64d6c1b5bea.png)

#### Option 2. render whitespace "editor.renderWhitespace": "boundary",
![image](https://cloud.githubusercontent.com/assets/5047891/24408002/bdfbc13e-13cc-11e7-800f-25befca85ea6.png)

#### Option 3: "editor.renderLineHighlight": "gutter"
![image](https://cloud.githubusercontent.com/assets/5047891/24408026/d59b2dd4-13cc-11e7-8263-bd8e1842a72c.png)

#### Option 4: "editor.rulers": [ 0 ]
![image](https://cloud.githubusercontent.com/assets/5047891/24408045/e85d78c8-13cc-11e7-928c-d7060e78947e.png)

**Comment by gforcada** [comment]
@alexandrudima thanks for all the tips, I only knew about the 2nd!

Indeed this alleviates a bit the need for a different color on the gutter, though personally, it still does not fulfill the same. But is low-priority now for me, so triage as you wish.

Thanks!

**Comment by alexandrudima** [comment]
:+1: I think the request is valid. We should offer themes the ability to customize the gutter background color

**Comment by albel727** [comment]
I was disappointed to find that this is not implemented in customizable theming still. I can't imagine what anyone making the gutter and the code be the same color could be thinking. But at least give us a way to save our eyes, please.

**Comment by gforcada** [comment]
@albel727 I guess that you did not pay for this software, right? And I hope you are not forced to use it, right?

If that's the case and you want this feature, just like I do, at the very least not insulting the ones that are working on it will definitely help way more on raising awarness that this issue is important for us.

Keep it calm and educated please.

**Comment by albel727** [comment]
@gforcada I'm not sure what's the point of your guesses like "you didn't pay for a software that is free". It's free because Microsoft benefits from it indirectly. Therefore I can offer reasonable critique regardless of the amount of money paid, and it's in their own interest too. Zero insults were intended to be given, and even if they were, it isn't your duty or right to ask amends and reprimand me. Keep it calm and educated by not calling out people just because you feel like acting a social justice warrior on behalf of people who never asked you to do it.

**Comment by aeschli** [comment]
I added `editorGutter.background' and 'peekViewEditorGutter.background`
