### ISSUE TITLE
Protocol "auto" suddenly required to debug simple node script. Why?

### ISSUE THREAD

**Issue by billyzkid** [Microsoft/vscode#22416]
Suddenly with the latest vscode (version 1.10.2) I am no longer able to debug a node script that contains array destructuring, e.g. `const [a,b,c] = [1,2,3];`

I was able to finally get this working by adding a launch.json configuration file that uses `"protocol": "auto"`, but this was not necessary in the previous version of vscode.

**Comment by roblourens** [comment]
What's the error? What version of Node?

**Comment by billyzkid** [comment]
My debug console shows this:

```
node --debug-brk=11016 --nolazy scripts\changelog.js 
Debugger listening on [::]:11016
TypeError: Cannot read property 'next' of undefined
    at exec.then.result.split.filter.map (c:\Code\temp\scripts\changelog.js:63:14)
    at Array.map (native)
    at exec.then (c:\Code\temp\scripts\changelog.js:62:63)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

The node version I installed is this:
```
PS C:\Code\temp> node -v
v6.10.0
```

My vscode About box shows this:
![image](https://cloud.githubusercontent.com/assets/974855/23811128/779a1f70-0589-11e7-848d-eae1675a4c67.png)

**Comment by weinand** [comment]
@billyzkid you do not need "auto". But you probably need the new "inspector" protocol instead of the default "legacy" protocol.
"auto" tries to determine the best protocol for your setup (which happens to be the "inspector" protocol).
Please set "protocol" to "inspector" and verify that this works for you.

**Comment by billyzkid** [comment]
Ok, this works, but I don't feel it is intuitive for users that the version of node used for debugging is somehow tied to a "protocol" setting, especially if the default "legacy" setting means we are using an older version of node that doesn't support es6 features such as destructuring.

**Comment by weinand** [comment]
Destructuring works fine for the 'inspector' protocol but doesn't work for the 'legacy' protocol. This issue is tracked in https://github.com/Microsoft/vscode-node-debug/issues/132.
