### ISSUE TITLE
Split VS code terminal to a new window

### ISSUE THREAD

**Issue by Janco-09** [microsoft/vscode#224177]
Would it be possible to split the terminal in a new window?

**Comment by meganrogge** [comment]
You can split and then run this command

![Image](https://github.com/user-attachments/assets/217c6562-47e2-4031-8523-e462f19e0db4)

**Comment by meganrogge** [comment]
You could add a keybinding to run both of these commands for you

**Comment by Janco-09** [comment]
Thank You !
