### ISSUE TITLE
"Open Loaded Scripts" often doesn't work on second run

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#22418]
Not every time, but

- Start legacy protocol debug session
- Open something via "Open loaded scripts"
- Stop debugging
- Start debug session again
- Open same script as before

Nothing happens. Debugging, I see that at

```
vscode.workspace.openTextDocument(uri).then(doc => {
  vscode.window.showTextDocument(doc);
});
```

openTextDocument returns undefined, and showTextDocument fails.

**Comment by roblourens** [comment]
I just noticed that I see something similar for eval scripts in general - have `eval('debugger')`. It will load the source during the first debug session, but not in subsequent debug sessions, unless the window is reloaded.

**Comment by isidorn** [comment]
FYI might be connected to https://github.com/Microsoft/vscode/issues/22741

**Comment by weinand** [comment]
yes, dup of #22741
