### ISSUE TITLE
Ctrl+C does not cancel command in ZSH terminal

### ISSUE THREAD

**Issue by ivanstepanovftw** [microsoft/vscode#224135]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Flatpak VSCode
- OS Version: Fedora Linux 40

Steps to Reproduce:

1. 
![image](https://github.com/user-attachments/assets/8708c261-aa82-4a26-863a-9977f39c0e5c)

2. 
![image](https://github.com/user-attachments/assets/6e2bbb49-3a5a-4463-8baa-90c9e0fff24d)

**Comment by ivanstepanovftw** [comment]
```json
    "terminal.integrated.profiles.linux": {
        "zsh": {
            "path": "/usr/bin/flatpak-spawn",
            "args": ["--host", "--env=TERM=xterm-256color", "zsh"],
            "overrideName": true,
        }
    },
    "terminal.integrated.defaultProfile.linux": "zsh",
```

**Comment by ivanstepanovftw** [comment]
Ctrl+Z is not working either

**Comment by OIRNOIR** [comment]
My only solution was to switch to the traditional repository, so I did that. The flatpak had this issue for me.

**Comment by OIRNOIR** [comment]
The issue #184713 is clearly for MacOS, but this problem occurs on Linux.

**Comment by meganrogge** [comment]
also on linux https://github.com/microsoft/vscode/issues/184713#issuecomment-2233997952
