### ISSUE TITLE
Cannot open new window from task bar

### ISSUE THREAD

**Issue by abist** [Microsoft/vscode#22414]
- VSCode Version: 1.10.2
- OS Version: Win 10 Enterprise

Steps to Reproduce:

1. Right click the VSCode application to open a "New Window" under "Tasks". Nothing happens.
2. The "New Window" from "File" in the menu bar works though.

**Comment by ramya-rao-a** [comment]
Am sorry, but I don't follow what you mean by "Tasks" in the below statement

> Right click the VSCode application to open a "New Window" under "Tasks"

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13905
