### ISSUE TITLE
Unable to navigate the method name from vscode, while using dynamic import of service file in NodeJS.

### ISSUE THREAD

**Issue by Tirth886** [microsoft/vscode#224181]
## Registering service
![image](https://github.com/user-attachments/assets/7a7acb46-3cbb-4a50-b3a7-aa10d1e8538c)
## Call one method from the another service (BrandPage)
![image](https://github.com/user-attachments/assets/b1620830-5ce8-4cc5-a480-1b06aa39a801)
## While navigating unable to find the definition
![image](https://github.com/user-attachments/assets/f709b47c-7827-42cf-8534-3c6cf5f5bcc3)

## Description
Based on this above images, i am dynamic registering my services, it's just simply a dependency injection. After importing this object and call one of the method of another service called "BrandPage", then i try to navigate the method which i have mention it's says (No definition found for 'getConversationWiseBrandPagePlatform'). 

<b>Is there any extention for this or have some path resolver setting in vscode. if any do let me know</b>

**Comment by mjbvz** [comment]
Please share a self contained, minimal code sample (as text) that demonstrates the issue
