### ISSUE TITLE
error while cli cmd

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#224150]
can not type cli cmd
just start code instead of showing info
![image](https://github.com/user-attachments/assets/5e1a67f4-4392-4520-ba28-0dc8f2397661)

版本: 1.91.1
提交: f1e16e1e6214d7c44d078b1f0607b2388f29d729
日期: 2024-07-09T22:06:49.809Z
浏览器: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.91.1 Chrome/122.0.6261.156 Electron/29.4.0 Safari/537.36

**Comment by legomushroom** [comment]
Was not repro this on stable 1.96.0 on Mac OSx 15.1.

@heartacker I see that in your screenshot the `--help` part is grayed-out so wondering if that could be a suggestion and you've never typed it?

I also explored to see if a language pack can be involved here but could not reproduce it anyway.
