### ISSUE TITLE
some C++ keywords not colorized correctly

### ISSUE THREAD

**Issue by bobbrow** [Microsoft/vscode#22419]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.2|
---

Steps to Reproduce:

1. Open a c++ file
2. Type any of the missing keywords into the editor (sizeof, static_cast, dynamic_cast, reinterpret_cast)

Copied from: https://github.com/Microsoft/vscode-cpptools/issues/551

I see that these keywords are listed in the grammar for C/C++.  I'm not sure why the editor is not coloring them correctly.

**Comment by sean-mcmanus** [comment]
The "bug" is that the default VS Code theme is making the color the same as normal text. How should this be solved?

**Comment by rbenson** [comment]
@sean-mcmanus The Language needs to updated. `sizeOf`, for example, is not being caught correctly somewhere in the [`.tmLanguage`/`.cson`/`.json` file](https://github.com/atom/language-c/tree/master/grammars). Looking at C's file, it is named in 8 places, but in C++'s it's 0. Thus making `sizeof`'s scope `source.cpp`, which is the default text color. Hope this helps

**Comment by sean-mcmanus** [comment]
I don't understand. sizeof doesn't render as the default text color when you change the theme. I don't see any difference in behavior between C and C++.

**Comment by bobbrow** [comment]
@rbenson, the C++ grammar scope includes the C grammar scope (it's a superset)

```
  {
    'include': 'source.c'
  }
```

**Comment by aeschli** [comment]
Added to our default themes.

**Comment by sean-mcmanus** [comment]
I see this got fixed for sizeof/etc., but we're still having the same issue with the alignof keyword. Should I open a new bug for that? https://github.com/Microsoft/vscode-cpptools/issues/938
