### ISSUE TITLE
"Run To Cursor" does nothing in run mode

### ISSUE THREAD

**Issue by rajkumar42** [Microsoft/vscode#22411]
Related issue : https://github.com/OmniSharp/omnisharp-vscode/issues/1297

"Run To Cursor" context menu is available when the process is running. When invoked it does nothing. 

Either it should not be displayed when the application is not in a break state or it should set a breakpoint on that line.

**Comment by isidorn** [comment]
@rajkumar42 I agree. We are now not showing the action if debugging is not stopped.

**Comment by rajkumar42** [comment]
@isidorn Thanks!
