### ISSUE TITLE
Continuity copy/pasting rich text from iOS to macOS does not work properly in the editor

### ISSUE THREAD

**Issue by fwcd** [microsoft/vscode#224128]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.1
- OS Version: Darwin arm64 23.5.0

### Steps to Reproduce

1. Copy text from Safari on an iOS device
2. Paste the text into a VSCode instance running on macOS (with the same iCloud account and continuity features enabled)

### Expected Result

The editor should paste a plain text version of the copied data.

### Actual Result

Instead of pasting a plain text version of the data, the editor inserts a string like this:

```
/var/folders/bp/fvm0x9c92xb3x02w8qsg21jh0000gn/T/com.apple.useractivityd/shared-pasteboard/items/AC079EB3-C47A-48B3-95DC-C03990D76EF1/42514c636c7fe381d40102cae8877a9c82f0aeb8.rtfd
```

### Video Demo

A short demo of pasting the same data in three separate places (VSCode's terminal with Neovim, TextEdit and VSCode's editor):

https://github.com/user-attachments/assets/a4e8586e-8381-4625-977a-2e0b2574f88c

**Comment by marlapativ** [comment]
@fwcd, I've tried replicating this on Version: 1.92.0 and it works fine.
(I copied some text in safari in my iphone and pasted it in vscode and it looked good to me)

Can you reconfirm if its fine in 1.92?

**Comment by mjbvz** [comment]
I also can't reproduce this

If you're still seeing this in the latest VS Code builds, please provide specific steps (for example, what exactly you copied on safari) and I'll take another look
