### ISSUE TITLE
SCM: New option to close multiple files: "Close unmodified only"

### ISSUE THREAD

**Issue by NCC1701M** [microsoft/vscode#224164]
When working with many files that have been opened one by one, it often happens that many have only been opened to look at something while other files have been changed and marked as “modified” or “untracked” by the repository.

Since the unmodified and modified files are listed together, it would be helpful to introduce a new option to close multiple files. This option should offer to close only the unmodified files, while the modified or untracked files remain open.

This new option should be available everywhere where the (context) menu offers the possibility to close several files at once.

**Comment by bpasero** [comment]
It is called "Close Saved":



![Image](https://github.com/user-attachments/assets/b2217be6-a238-4d4d-8246-f0d5f4a91929)

**Comment by NCC1701M** [comment]
@bpasero Well it's not "Close saved"! Modified and untracked files can also be saved! The request is about the repository state.

Reopen!

**Comment by NCC1701M** [comment]
@lszomoru 
This would work with git. But what's about other source control systems? I guess they have to implement this feature in their extensions as well. Somehow re-inventing the wheel. But because there is the source control API wouldn't it be better, when this functionality would be a default feature in VSCode which uses information from the SCM extension? And in my opinion, closing editors should be something the main application should handle.

**Comment by gjsjohnmurray** [comment]
> I guess they have to implement this feature in their extensions as well.

Yes, because not all SCM systems have the same concept of "unmodified" / "uncontrolled" as git has.

**Comment by gjsjohnmurray** [comment]
@NCC1701M wouldn't that require something adding to the API?

**Comment by NCC1701M** [comment]
@gjsjohnmurray 
I don't know. I'm only suggesting this feature. I would expect that an API developed for source control would have an interface to return all modified files. But this has to answered by the VSCode team

**Comment by lszomoru** [comment]
I agree with @gjsjohnmurray. Each extension that is implementing a source control provider has the best knowledge about the meaning of each resource group/resource. I do not see the value of extending the Source Control extension API to include the additional information to implement this in VS Code core.
