### ISSUE TITLE
my vs code is partially responding 

### ISSUE THREAD

**Issue by gautam-viswanathan** [microsoft/vscode#224123]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. open it and it partially responds.
I have added the screenrecord of it
[Screencast from 2024-07-28 19-09-10.webm](https://github.com/user-attachments/assets/9dac4fc1-2758-488f-b3cf-e92637179de8)

**Comment by aiday-mar** [comment]
Hi. I am not sure I understand. Do you mean that VS Code is slow? Could you describe with words the issue in more detail?
