### ISSUE TITLE
[markdown-language-features / markdownEngine.ts / getMarkdownOptions] Expose (export) the highlight.js object used for preview highlighting to allow adding new languages ​​easily (registerLanguage)

### ISSUE THREAD

**Issue by FALLAI-Denis** [microsoft/vscode#224173]
Hi,

The internal [markdown-language-features](https://github.com/microsoft/vscode/tree/main/extensions/markdown-language-features) extension provides highlighting of fenced blocks associated with a language when previewing a Markdown file.
To do this, it imports the `highlight.js` component and uses its `highlight` function, but this import is local to the [getMarkdownOptions](https://github.com/microsoft/vscode/blob/9473445f7d3dcb5c579f42ece8b6c18c43c63ed3/extensions/markdown-language-features/src/markdownEngine.ts#L415) function of the [ markdownEngine.ts](https://github.com/microsoft/vscode/blob/main/extensions/markdown-language-features/src/markdownEngine.ts) file. 
This does not allow the `highlight.js` component to be enriched with new languages ​​(or even removed).

By declaring the import of the `highlight.js` component at the global level, and exposing it (export) outside the [markdown-language-features](https://github.com/microsoft/vscode/tree/main/extensions/markdown-language-features) extension, possibly through a function or an interface, this would allow it to be enriched or its behavior adapted from another extension.

It is still necessary to have a` highlight.js` plugin supporting the language to implement, and possibly a textmate grammar for highlighting when editing the Markdown file itself, but the work would be simplified if the `highlight.js` object used for the Markdown preview was public and modifiable.

FYI, solution found for implementing additional language highlighting both when editing a Markdown file and previewing it:
* https://github.com/IBM/zopeneditor-about/issues/428#issuecomment-2250038933

Thanks.

**Comment by mjbvz** [comment]
#91279 is a better solution for this

**Comment by FALLAI-Denis** [comment]
Open since 24, Feb 2020… 
Solution I suggest seem to be more easy to implement and can be temporary.

**Comment by mjbvz** [comment]
Exposing an entire 3rd party library as api is not going to be good long term (or short term)
