### ISSUE TITLE
search.exclude not applied instantly

### ISSUE THREAD

**Issue by icegood** [microsoft/vscode#224101]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:08:12.169Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.8.0-38-generic

Steps to Reproduce:
see picture:
![SearchExcludeNotApplied](https://github.com/user-attachments/assets/5bfabb79-105e-404a-895c-7500e9d743cb)

1. Once added some folder to exclude list, it doesn't influence to subsequent searches. Still, result in **docs** folder found
2.  

Workaround: only restart vscode

**Comment by andreamah** [comment]
if you expand (using the three dots) to see 'files to exclude', is the circled icon disabled?



![Image](https://github.com/user-attachments/assets/28776de3-c458-4130-a76e-78e93cf0f27f)
