### ISSUE TITLE
Show language sevrice that caused the error

### ISSUE THREAD

**Issue by Tallyb** [microsoft/vscode#224293]
If an error was caused by a language service, add to error the language service that triggered it.

I recently opened this issue on TS repo https://github.com/microsoft/TypeScript/issues/59295. @RyanCavanaugh identified that this is caused by the nx language service. As we are not all Ryan, it would be great if the service that caused the issue would be added to the error message. It's a small step for the team, a great step for the users

**Comment by sandy081** [comment]
@mjbvz How can I assist on this issue? Is not this related to the typescript extension?

**Comment by mjbvz** [comment]
If the exception is from a separate extension, then the diagnostic should have a clear `source` for this. However I think nx  may actually be a TS Server plugin, which means that the errors actually get reported by TypeScript. There's no way for us as VS Code to know that these errors are not actually TypeScript errors

In these cases, the language plugin should make sure to set `source` property on the diagnostic. This is part of the TS Server protocol

@Tallyb I think everything is in place on the VS Code side so can you please follow up with the nx extension about this. Feel free to cc me on the issue too if they need more info
