### ISSUE TITLE
screen error

### ISSUE THREAD

**Issue by Max-2125** [microsoft/vscode#224258]
Type: <b>Bug</b>

coming frozen screen while i didnt writing or when i switch app

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12500H (16 x 3110)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (6.55GB free)|
|Process Argv|--crash-reporter-id a694a567-84d0-4184-aa31-6b73c735b69f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.2
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
live-server|ms-|0.4.14
LiveServer|rit|5.7.9
vscode-icons|vsc|12.8.0
material-theme|zhu|3.17.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactorc:31101458
ccplti:31103428
pythonrstrctxt:31103193
1iic9185:31097392

```

</details>

**Comment by Max-2125** [comment]
i did and it work but how to solve permanent

**Comment by Max-2125** [comment]
how to disable permanent gpu for vs code

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/issues/224298#issuecomment-2259617508

**Comment by deepak1556** [comment]
Closing as issue is not actionable and might get resolved with runtime updates.
