### ISSUE TITLE
Provide "terminal.integrated.enableBold" setting

### ISSUE THREAD

**Issue by yustnip** [Microsoft/vscode#22422]
It will be great to have a possibility to change a font weight for the integrated terminal. Now a text inside it looks bolder than a text in the editor:

![screenshot from 2017-03-11 00-19-24](https://cloud.githubusercontent.com/assets/9950871/23813610/b5151582-05f0-11e7-9584-4b4846f349b4.png)

- VSCode Version: 1.10.2
- OS Version: Ubuntu 16.04

**Comment by Tyriar** [comment]
Do you mean you want to set all text in the terminal to be bold? Because that would conflict with the shell's ability to bold text itself:

![image](https://cloud.githubusercontent.com/assets/2193314/23814297/d0994962-0597-11e7-8793-4f00e3c212ae.png)

Do you have any editor specific settings that deal with font weight?

**Comment by yustnip** [comment]
*Do you mean you want to set all text in the terminal to be bold?*
Yes, for example, to set all text in the terminal as "normal", "bold", etc.

VS Code terminal (different font weight):
![screenshot from 2017-03-11 00-51-45](https://cloud.githubusercontent.com/assets/9950871/23814555/040bfc92-05f5-11e7-87bd-6cc5a459e62d.png)

Ubuntu terminal (same font weight):
![screenshot from 2017-03-11 00-52-15](https://cloud.githubusercontent.com/assets/9950871/23814580/19879f72-05f5-11e7-8a61-68a7bfd473b8.png)

*Do you have any editor specific settings that deal with font weight?*
No, for the editor in VS Code I have default font weight settings.

**Comment by Tyriar** [comment]
Do you have this set in gnome-terminal?

![image](https://cloud.githubusercontent.com/assets/2193314/23814881/32df8080-059a-11e7-8ac1-6ab737e14bce.png)

**Comment by yustnip** [comment]
No, I have it is disabled now. With "Allow bold text" checkmark a font weight behavior is the same as in VS Code terminal.

**Comment by Tyriar** [comment]
Ok, makes sense :smile:

**Comment by Tyriar** [comment]
Accepting PRs on this, you will need to:

- Add the setting to terminal.contribution.ts
- Add the setting to the terminal.ts config interface
- Set some class on `.integrated-terminal.panel` based on the setting
- Add CSS for the class in xterm.css

**Comment by lifez** [comment]
I would take this PR. Can I ?

**Comment by Tyriar** [comment]
@lifez that would be awesome 😃

**Comment by lifez** [comment]
Great I will do this PR :)

**Comment by lifez** [comment]
I've implemented the terminal setting on the PR #22465 , it'd be nice to get some comments on it :)

**Comment by michelkaporin** [comment]
Cannot verify, as I don't see a difference between "terminal.integrated.enableBold": true and false on Windows cmd and powershell integrated terminals in VS Code v1.11.0.

**Comment by isidorn** [comment]
I also do not see the difference on my osx zsh shell,
Reopening this issue. I propose to either make it work on all platforms or to remove this seeting or at the very least document that it only works on linux.

**Comment by Tyriar** [comment]
@michaelchiche I don't think bold is used on cmd or PS unless you use a custom prompt?

@isidorn I expect it to work fine on all platforms, it depends on whether your shell outputs bold. Could you try again by running the following and comparing the styles?

```bash
echo -e '\x1b[1mFOO\x1b[0mFOO'
```

![image](https://cloud.githubusercontent.com/assets/2193314/24470725/c9a6b446-1474-11e7-968e-7857e36bf9bc.png)

They should look the same when the setting it true:

![image](https://cloud.githubusercontent.com/assets/2193314/24470769/e89cabda-1474-11e7-95a1-edc65511bfdc.png)

**Comment by michelkaporin** [comment]
@Tyriar If this setting exists I would expect it to work on all terminals as @isidorn mentioned. A workaround would be to make description to point out which terminals are supported.
E.g. default Windows cmd supports bolding, although this setting is not working for it.

P.S. you've pinged a different person (it happens most people confuse my nickname with michaelchiche, poor guy gets many notifications that are addressed to me 😃).

**Comment by isidorn** [comment]
@Tyriar for me they are the same in both cases (setting false and setting true). However if I run the command in my iTerm i nicely get the output bolded

![screen shot 2017-03-30 at 10 36 43](https://cloud.githubusercontent.com/assets/1926584/24495214/cabe21e6-1534-11e7-9f27-78720034e6f3.png)


![screen shot 2017-03-30 at 10 36 32](https://cloud.githubusercontent.com/assets/1926584/24495199/c1d53a7e-1534-11e7-853b-cc1154cb52b5.png)

**Comment by Tyriar** [comment]
@michaelchiche oppsy :wink: 

@isidorn does the font you use in the terminal not have a bold variant maybe? It doesn't look like the top screenshot has any bold text.

@michelkaporin all terminals that can output bold text are supported. If `enableBold` is `true` and bold text is showing up, flipping it to `false` should make the text non-bold. Maybe `allowBold` would be more fitting for what it is doing?

**Comment by isidorn** [comment]
@Tyriar I am not using any special font in the terminal, not sure if it supports bold. Inspecint it in chrome dev it is the usual     font-family: Menlo, Monaco, 'Courier New', monospace;

P.S aren't you sleeping 😁

**Comment by michelkaporin** [comment]
@Tyriar I would stick to `enableBold` but changing the description of the setting. 

> all terminals that can output bold text are supported

As I've said bolding in cmd.exe terminal does not work for me.

**Comment by Tyriar** [comment]
@isidorn my sleep was a bit funky yesterday :stuck_out_tongue:. One way to test whether the font supports bold is to manually add `font-weight:bold` to the element in devtools.

**Comment by Tyriar** [comment]
@michaelchiche :+1: deferred to April as it's the end of endgame https://github.com/Microsoft/vscode/issues/23694
