### ISSUE TITLE
Git: Support cherry-pick

### ISSUE THREAD

**Issue by sudogooglex** [microsoft/vscode#22426]
Ability to use the cherry pick command directly in vscode.
Actually, vscode users still have to cherry pick with the command lines :
```
git checkout master
git cherry-pick <commit-hash>
```

**Comment by mtpultz** [comment]
The visual cherry picker included with IntelliJ IDEA is great and seems to be one of the only things other then the PHP support that I consistently miss in VSCode, otherwise I'm a complete convert.

**Comment by zymotik** [comment]
In the meantime, I'm using `gitk --all`, right clicking the commit and selecting `cherry-pick` to pick into the current branch.

https://stackoverflow.com/questions/9000918/how-to-cherry-pick-interactively

A few of our teams are using IntelliJ and this is the only feature holding them back from switching to VS Code.

**Comment by inwardmovement** [comment]
Any news on this?

**Comment by benallfree** [comment]
[Git History](https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory) extension can do it. Recommend closing this issue or looking at pulling that extension into the core.

**Comment by enkia** [comment]
Git history doesn't seem to allow for the -x option. Currently, Git Graph's beta does, just FYI.
