### ISSUE TITLE
Add "Copy URL" to settings

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#224200]
Now that we can handle settings URLs, we could have a "Copy URL" command in the settings editor:

![Image](https://github.com/user-attachments/assets/d01b97ad-c034-4469-bb93-40d7f6de1a45)

From @TylerLeonhardt

**Comment by alexr00** [comment]
@rzhao271 FYI.

**Comment by rzhao271** [comment]
Thanks for the ping!
"Copy URL" sounds vague. I'd prefer "Copy URL to Setting".
Also, is it just the URL that's copied over, or the entire anchor element?

**Comment by alexr00** [comment]
To verify:
- Open the settings editor
- In an individual setting's menu, choose the "Copy Setting as URL" action
- Verify that a URL to the setting is copied
- Verify that if you close VS Code and open the URL that VS Code is opened to the setting

**Comment by TylerLeonhardt** [comment]
Verified. I've used this a ton recently!
