### ISSUE TITLE
Run button is not showing

### ISSUE THREAD

**Issue by Ishan-debug** [microsoft/vscode#224264]
Type: <b>Bug</b>

what the hell? this code editor is dumb run button is not showing sometimes code is not running please fix this fast as f...

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.35GB (1.32GB free)|
|Process Argv|--crash-reporter-id da679db6-99cb-4ec1-aaa2-362fd5450021|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme-icons|equ|3.6.1
code-runner|for|0.12.2
copilot|Git|1.219.0
copilot-chat|Git|0.17.1
debugpy|ms-|2024.8.0
pylint|ms-|2023.10.1
python|ms-|2024.11.2024072502
vscode-pylance|ms-|2024.7.1
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
indent-rainbow|ode|8.3.1
java|red|1.32.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.27.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0
vscode-icons|vsc|12.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
refactort:31101459
ccplt:31103426
pythonrstrctxtcf:31103194
1iic9185:31097392
wkspc-onlycs-t:31106322

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe the Run button is contributed by one of your extensions. The Start Extension Bisect command can help you check. And if it is, please report your issue to the extension authors.
