### ISSUE TITLE
hygiene.js Development use/options (eg commit without hygiene)

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#22427]
Development Environment:

OS: Windows 7 Professional SP1 (VM under OSX)
Python: ActiveState 2.7.5

Visual Studio 15 Community \ C++ Tools \ SDK 8.1
VS Code: 1.10.1 (Code OSS Build environment)
VS Code Insiders 1.10.0 2-27 build: (Test environment)
VS Code: master clone 2-28 and 3-1  development tests (including sidebar resize implementation)

Node: 6.9.1
NPM:  3.10.8

Issue/Feature request:

During development it's easy to violate one or more hygiene rules. Even simple debug output strings
or test functions.

a) Without resorting to complete disable of the precommit hygiene script. What is the best practice
for doing commits with hygiene violations.

b) would a commit without hygiene command or a meta comment File symbol (bypassed hygiene rules)
make sense?

if I missed the existence of a method - still on the learning curve...

Thanks 
Christopher

**Comment by joaomoreno** [comment]
You simply should not do commits with hygiene violations.
