### ISSUE TITLE
debugging: switch to console/terminal after preLaunchTask

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#22425]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.7.0|
|cpptools|ms-vscode|0.10.2|
|csharp|ms-vscode|1.7.0|;

---

please add an option to switch to the debug console after the preLaunchTask(if any) is completed and the debuggee is about to be launched.

**Comment by isidorn** [comment]
Please add `"internalConsoleOptions": "openOnSessionStart"` to your launch.json configuration
