### ISSUE TITLE
my default key bindings aren't working are not after i have installed VIM so how to fix that, recently i have deleleted the VIM but still that issues continues

### ISSUE THREAD

**Issue by AbdulRaffayQureshi** [microsoft/vscode#224257]
Type: <b>Bug</b>

my default key bindings aren't working are not after i have installed VIM so how to fix that, recently i have deleleted the VIM but still that issues continues

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (3.75GB free)|
|Process Argv|--crash-reporter-id 052428d2-3b4d-4a2e-be5e-20339f7e129e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
codegeex|AMi|2.13.1
blackbox|Bla|1.3.68
gitlens|eam|15.2.3
vscode-great-icons|emm|2.1.105
code-runner|for|0.12.2
c-cpp-runner|fra|9.4.8
ctrl-semicolon|Gfo|0.1.0
cmake-tools|ms-|1.18.43
cpptools|ms-|1.21.4
cpptools-extension-pack|ms-|1.3.0
notepadplusplus-keybindings|ms-|1.0.7
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
vim-colemakdh|zak|1.24.3

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31101459
ccplti:31103428
pythonrstrctxtcf:31103194
wkspc-onlycs-c:31106320
wkspc-ranged-c:31106315

```

</details>

**Comment by gjsjohnmurray** [comment]
I suggest you check what you have in your keybindings.json file. There is a Command Palette command to open this file easily.

**Comment by gjsjohnmurray** [comment]
Also worth using the Start Extension Bisect command.
