### ISSUE TITLE
Report a problem, doesnt work..

### ISSUE THREAD

**Issue by bcheung4589** [microsoft/vscode#224288]
![image](https://github.com/user-attachments/assets/5b132f9c-32a0-4806-b466-d234e6e3895c)

Do you guys test products?

https://developercommunity.visualstudio.com/report?port=1025&fsid=23a90b32-ea12-43ef-a4d6-52b566220211&entry=problem

**Comment by gjsjohnmurray** [comment]
Is that VS Code, or another tool?

**Comment by bcheung4589** [comment]
Because I cant find the VS one. Even when reporting from inside VS. And Im nog wasting more time googling searching where to report bugs.
