### ISSUE TITLE
Constant Screen Flickering

### ISSUE THREAD

**Issue by benaplus1** [microsoft/vscode#224298]
Type: <b>Bug</b>

Our computer system was recently upgraded from Ubuntu to AlmaLinux 9.4 using KDE Plasma 5.27.11. I am currently using VSCode 1.91.1 together with the C/C++, Modern Fortran, and vscode-pdf extensions (but this bug occurs even using code --disable-extension).

The bug is simply that the screen flickers more or less constantly between frames. When scrolling, the screen will flick back up or down. When typing, the most recently entered/deleted characters will rapidly appear and disappear. This occurs even when using the "find and replace" feature; entering characters in the search field will still result in characters appearing and disappearing randomly. 

Steps to reproduce:
1. Launch VSCode
2. Navigate to any text/.py/.f90/.sh file (the bug occurs with all of these; I haven't tested other file types, but I have no reason to think it wouldn't occur there as well)
3. Scroll up and down, click a few times, begin typing. The bug sometimes starts immediately, sometimes after a few seconds. It will invariably occur within 30 seconds of starting to work on a file.

Attempts to resolve
1. Disabling hardware acceleration: I have seen many other users who have found this to be a solution to their screen flickering problems. Unfortunately, it has not worked for me.
2. Disabling extensions: No effect

I was unable to include a video here due to the file size. Here's a link: https://drive.google.com/file/d/1MkucKbT0teEirPom3XE13s_dZv6UtDoP/view?usp=sharing

The bug begins approximately 13 seconds into the video. I apologize for the poor video quality and low framerate. The flickering actually happens much more rapidly than is shown in the video, I suspect because the built-in screen capture software I was using (Spectacle) records at a much lower framerate than my monitor refresh rate. Please let me know if you are unable to access the video, or if it is necessary to embed it in GitHub (in which case I will try to find a way to truncate it to reduce the file size).

Example code repository for reproduction: https://github.com/benaplus1/rams_postprocess/releases/tag/post-processing
Opening any file from the repository leads to the bug (this even occurs with the .gitignore and LICENSE files).

I apologize if this issue has been reported elsewhere. I have seen other screen flickering issues being raised, but all of those appeared to be solved by disabling hardware acceleration, while my issue has not.

Thanks so much for your help! Please let me know if you need any more information!

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:08:12.169Z)
OS version: Linux x64 5.14.0-427.26.1.el9_4.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz (20 x 800)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|46.05GB (30.59GB free)|
|Process Argv|--new-window --crash-reporter-id b603a65a-f42a-437e-a199-998d329772a5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|plasma|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
linter-gfortran|for|3.4.2024061901
cpptools|ms-|1.21.4
pdf|tom|1.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31104044
refactorc:31101458
ccplt:31103426
pythonrstrctxtcf:31103194
wkspc-ranged-t:31106316

```

</details>

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by benaplus1** [comment]
That was the first thing I tried, unfortunately. All the other people who have had this problem have found this to resolve their screen flickering; however, this didn't help for me.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by benaplus1** [comment]
This computer is part of a cluster, and I don't have permission to install new programs myself.

However, I contacted tech support at our institute and they found a solution to the screen flickering:

*The issue was the use of the KDE Plasma desktop environment with a _Weyland_ driver. Switching the driver from Weyland to X11 solved the problem.*
