### ISSUE TITLE
Keep and restore scroll position for readonly documents

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#22420]
- Start legacy protocol debug session
- Open something via "Open loaded scripts"
- scroll down
- ctrl+tab to switch to another doc
- ctrl+tab back to the newly opened script

It's scrolled up to the top. Is it being closed/opened each time we switch away?

**Comment by weinand** [comment]
This problem is independent from the "Open Loaded Scripts" feature.

To reproduce:

- debug a simple node hello world program and stop on entry
- in the CALL STACK select an internal module
- press Control-Tab twice (to switch between two editors)

Observe: you loose the scroll position in the internal module

**Comment by isidorn** [comment]
March to investigate

**Comment by isidorn** [comment]
Workbench is not preserving scroll location of in memory resources.
Same is true for diff view.

Forwarding to @bpasero since he probably already has an issue for this

**Comment by isidorn** [comment]
@bpasero give me some code pointers for the PR and I can do it in debt week

**Comment by bpasero** [comment]
@isidorn we do it for `files` and `untitled` via the `saveTextEditorViewState` and `restoreTextEditorViewState` methods that are actually defined in `src/vs/workbench/browser/parts/editor/textEditor` and we could probably push this down from `resourceTextEditor` and `textFileEditor` and just use it from textEditor for any input that has a resource 👍

**Comment by isidorn** [comment]
Ok, makes sense. Assigning to me and April to look into it

**Comment by soncodi** [comment]
Possibly related: https://github.com/Microsoft/vscode/issues/26251

**Comment by bpasero** [comment]
With https://github.com/Microsoft/vscode/issues/26317 landed, we keep the UI state when you switch editors, though we clear it when you close a tab. The rationale is that the lifecycle of these editors that have virtual resources is not known, as such we assume the view state can be ditched once the editor closes.

**Comment by eamodio** [comment]
That sounds perfect!
