### ISSUE TITLE
VS cant open Terminal.

### ISSUE THREAD

**Issue by bcheung4589** [microsoft/vscode#224287]
VS
![image](https://github.com/user-attachments/assets/bbff09c0-ab6a-416e-95ba-864f4943e969)

Open in terminal.
![image](https://github.com/user-attachments/assets/6b6e111b-a00d-4fbf-aafc-133816185149)

Doesnt do shit except shows a blank screen. Doesnt open WHERE I SELECTED.
![image](https://github.com/user-attachments/assets/8ecef326-b811-4779-9772-4334aadea06d)

This is really great... such a simple thing..

**Comment by gjsjohnmurray** [comment]
But why are you reporting this to the VS Code developers?

**Comment by bcheung4589** [comment]
Because I cant find the VS one. Even when reporting from inside VS. And Im nog wasting more time googling searching where to report bugs.

**Comment by meganrogge** [comment]
Please create an issue for VS - this is VS Code, which has no control over VS.
