### ISSUE TITLE
Integrate Existing Snippet Extensions with Surround With Snippets Feature

### ISSUE THREAD

**Issue by amsyarzero** [microsoft/vscode#224251]
Type: <b>Feature Request</b>

Hello! First off, a huge thank you to every dev and contributor for making this great app. I have a suggestion that will make this app better.

## What I'm trying to achieve
I want to easily wrap an existing block of code with various snippets such as functions or classes without having to manually indent and type them.

## Current behavior
The `Surround With Snippets` feature in VS Code only has the basic snippets of each language. For example, JavaScript in VS Code only has the JavaScript Language Basics.
![The Surround With Snippets panel for Javascript](https://github.com/user-attachments/assets/8aadd2d3-fc5a-4bdc-9b32-62ca9b65866c)

Defining custom snippets is possible, but it is manual and takes time to, say, include 10 custom snippets.

## Improvement
It would be helpful if the `Surround With Snippets` feature can recognize and integrate custom snippets from existing extensions. For example, [JavaScript (ES6) code snippets](https://marketplace.visualstudio.com/items?itemName=xabikos.JavaScriptSnippets) by xabikos provides many boilerplate code snippets, but it is only available for `Insert Snippet`, which is useful when making a new one, not so much for existing code.

I am also willing to contribute in any manner, shape, or form too. It could become coding practice for me 😁 

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by jrieken** [comment]
This is possible. The surrount-with feature picks up all snippets that use the $SELECTION variable
