### ISSUE TITLE
Component Name while using react.js

### ISSUE THREAD

**Issue by MayankJindal74** [microsoft/vscode#224274]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. When the user creates a component in react 
2. now user want to rename the component name 
3. user updates the component name and now it shows error and we cannot use that name of component in the particular project
4. our projects works well  but the symbol of error show on the vs code which irritates alots while coding.

I Hope You will resolve that issue as soon as possible.

thank you!

**Comment by mjbvz** [comment]
Please share some example code which demonstrates the issue
