### ISSUE TITLE
Show more info for unbound breakpoints

### ISSUE THREAD

**Issue by velara3** [microsoft/vscode#224201]
In my nodejs project I have moved my source files into the /src directory. I updated tsconfig.json sourceRoot property to reflect the changes but now all the break points are unbound. They don't work. 

From what I've read, the reason they don't work is the file paths are not found. Everyone in the discussions ask to post the log that shows where the file paths are. 

This feature request is to show more information if breakpoints are unbound. In the tooltip show more data! Where is vscode looking for the file, what option do I need to change to update that? Where can I get more info!?!

Please add more details and solutions to fix unbound breakpoint.

**Comment by roblourens** [comment]
Do you see this message when you hover the breakpoint?

![Image](https://github.com/user-attachments/assets/217cd554-9e71-426b-bf04-63d3362aa701)

If not you can also run the command "Diagnose breakpoint problems" manually
