### ISSUE TITLE
use  .code-workspace file config debug .NET project failed,but config in launch.json work well

### ISSUE THREAD

**Issue by mypursuit** [microsoft/vscode#224249]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 
版本: 1.90.0
提交: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
日期: 2024-06-04T19:43:07.605Z
浏览器: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.90.0 Chrome/122.0.6261.156 Electron/29.4.0 Safari/537.36

Steps to Reproduce:
1.open .codespace file use vscode,config the launch setting,but throw error when I use it to debug
     ErrorMessage:Can not find an opened workspace folder. Please open a folder before starting to debug with a 'dotnet' configuration'.
     Notice:it is work well on windows
2.config the same setting to launch.json file,work well

![image](https://github.com/user-attachments/assets/9422cb37-1b68-4e4f-91d2-5e72db790844)

**Comment by roblourens** [comment]
Please file this on the C# debug extension, thanks
