### ISSUE TITLE
Delete key in editor wants to delete file

### ISSUE THREAD

**Issue by JustinMinnaar** [microsoft/vscode#224364]
Type: <b>Bug</b>

Often whilst working on the Mac edition of VS Code, when I am editing text and press the delete key, it prompts to delete the file instead of deleting the character in the editor.

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|36.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id 81f98b00-4459-4335-a643-e8ae8d8094ec|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.9.0
composer-php-vscode|DEV|1.49.15728
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.49.15728
profiler-php-vscode|DEV|1.49.15728
copilot|Git|1.219.0
copilot-chat|Git|0.17.1
go|gol|0.42.0
vs-code-runner|Har|2.0.1
Ionide-fsharp|Ion|7.20.3
vscode-docker|ms-|1.29.1
csdevkit|ms-|1.8.14
csharp|ms-|2.39.29
dotnet-interactive-vscode|ms-|1.0.5229040
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.1.1
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
datawrangler|ms-|1.4.2
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.375.1
prettyxml|Pra|5.0.2
csharpen|spe|0.0.8
unfoldai|Tal|0.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactorc:31101458
ccplti:31103428
pythonrstrctxtcf:31103194

```

</details>

**Comment by bpasero** [comment]
Sounds like a keybindings / context key issue to me.
