### ISSUE TITLE
Enforce a minimum for editor.lineHeight

### ISSUE THREAD

**Issue by udaykiranp** [Microsoft/vscode#22433]
![capture](https://cloud.githubusercontent.com/assets/7515560/23818806/82e07538-05c4-11e7-8ef8-cd87e85ce4fc.PNG)
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by MikeVelazcoMtz** [comment]
Isn't this related to your font settings?

**Comment by udaykiranp** [comment]
i just installed code on my machine, i haven't changed any font. I tried to look into settings by clicking File --> Preferences --> Settings and i even see text overlapping like this
![capture2](https://cloud.githubusercontent.com/assets/7515560/23818968/1fee81b6-05c6-11e7-9c18-8210b19e0c2a.PNG)

**Comment by alexandrudima** [comment]
@udaykiranp This looks like a bad value for the setting `editor.lineHeight`. You can go to File > Preferences > Settings and in the right hand side select all (ctrl+a) and comment all (ctrl+/). This should reset all settings to the defaults.

**Comment by alexandrudima** [comment]
I can look into enforcing a minimum for `editor.lineHeight`.

**Comment by ajitid** [comment]
Same here. Happening in VS Code 1.12.1 on Windows 10 too

**Comment by ajitid** [comment]
What are permissible values for it?

**Comment by alexandrudima** [comment]
@ajitid At this time, even a value of `1` is accepted, hence the screenshots above of the font rendered with `1px` line height.
