### ISSUE TITLE
Lack of indicators to track progress when installing extensions

### ISSUE THREAD

**Issue by rasikabaskaran** [microsoft/vscode#224365]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.1 (Universal)
- OS Version: Darwin arm64 22.5.0

Steps to Reproduce:

1. Choose a new extension that has not been installed under Extensions.
2. Observe the lack of a progress tracker or loading bar that does not show how far the extensions has loaded.

**Comment by gjsjohnmurray** [comment]
Previously discussed in #76189
