### ISSUE TITLE
Allow interception of Completion list and its transformation

### ISSUE THREAD

**Issue by jkavalec** [microsoft/vscode#224374]
Ability to modify a Completion list right before it is rendered seems like missed opportunity, that would allow Plugin dev to change way completions are displayed to the user, this can be done in IntelliJ IDEs rather easily, and would be great if it was possible for VS-Code

I searched the whether it is possible similarly to IntelliJ IDEs to intercept the list of completions, inspect them and then modify the final list the way you like before it gets rendered.

There could be two approaches
- same as IntelliJ - have CompletionItemProvider receive 'Completion list so far' and allow it to be inspected/manipulated right there
- have a dedicated CompletionInterceptor that gets the list before it is rendered, so transformation is possible before rendering

**Comment by jrieken** [comment]
> same as IntelliJ - have CompletionItemProvider receive 'Completion list so far' and allow it to be inspected/manipulated right there

We run them (mostly) in parallel and therefore a "list so far" approach doesn't work

> have a dedicated CompletionInterceptor that gets the list before it is rendered, so transformation is possible before rendering

Unsure about that because it enables an extension to "break" another extension (by bugs) and that's something we aren't aiming for.

**Comment by jkavalec** [comment]
First is understandable.

Second - I don't thin processing/filtering result is breaking something, this would affect the output the way user wishes, and add some flexibility, autocompletion is the part you see all the time, and it would certainly open options to make it more convenient.

Another option would be to have 'interceptable completion action' standing separately that would allow such modification, and you could use it if you like.
