### ISSUE TITLE
window offset vertically after unplugging then plugging external monitor

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode#22430]
![screen shot 2017-03-10 at 3 48 43 pm](https://cloud.githubusercontent.com/assets/63830/23817593/1c6ed846-05a9-11e7-9f87-fa800690a7e3.png)

- VSCode Version: 1.10.2
- OS Version: 10.12.3 (16D32)

Using on a MacBook Pro in fullscreen on an external monitor. Unplugged the external monitor and closed the laptop. Opened the laptop again and used for a while as just a laptop. Closed the laptop again. Reattached the external monitor and opened the laptop. Switched to VS Code. Saw the attached screen shot.

**Comment by bpasero** [comment]
I would argue this is something the OS is doing wrong because there was no restart involved. Closing.

**Comment by willfaught** [comment]
Then why does it only happen for Slack and VS Code? Don’t they both use electron?
