### ISSUE TITLE
Request for Supporting RemoteForward Configuration in .ssh/config within VSCode Terminal

### ISSUE THREAD

**Issue by xicilion** [microsoft/vscode#224363]
Reasoning:

• Allows seamless interaction and debugging with remote servers.
• Enables direct local access to remote server tools without additional VPNs or tunnels.
• Enhances security via SSH encrypted traffic.

Example Use-case:Developers working on web apps remotely can map a remote web service from 192.168.2.100:8000 to their local port 4000, making it accessible through their local browser with this config:
```
Host my-remote-server
    HostName example.com
    User myuser
    RemoteForward 4000 192.168.2.100:8000
```
Currently, this setup doesn’t affect SSH sessions launched from VSCode terminals, requiring external terminal use which disrupts workflow.

**Comment by roblourens** [comment]
Please give some more details, why doesn't this work?

Are you talking about just running an 'ssh' command from the terminal, or using the Remote-SSH extension?

**Comment by xicilion** [comment]
Sorry, my mistake. I tested it now and it works. It was not working yestoday.
