### ISSUE TITLE
Display parent folder name in terminal tab 

### ISSUE THREAD

**Issue by qbuache** [microsoft/vscode#224373]
It would be useful to be able to display the parent directory name of the  CWD  in the terminal tab, to be able to differentiate between folders with the same name

Exemple:
Tabs opened in folders such as :

- .../Composables/Common
- .../Components/Common
- .../Directives/Common

all display : "bash Common"

We could change this by using "terminal.integrated.tabs.description" and a new ${cwdParentFolder} variable and use it like so :
"${cwdParentFolder}/${cwdFolder}"

to display : "bash Components/Common"

${cwd} overflows most of the time and is not really usable in that case

Thank you for your help

**Comment by meganrogge** [comment]
I think this is actually a bug and we should be showing more of the path if the full paths differ, but the abbreviated one doesn't.

**Comment by meganrogge** [comment]
I haven't seen more users requesting this, thus closing.
