### ISSUE TITLE
Toggle Skipping This File does not work

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#22432]
node2/chrome will change the presentationHint as a source is dynamically skipped/unskipped, but it seems like this is now cached during a debug session and can't be changed.

- Start a node2/chrome debug session
- Use "Toggle skip status" from context menu
- See that the presentationHint is now changed on returned frames, but the UI doesn't reflect the change.

**Comment by isidorn** [comment]
For now I did a not super nice fix to make it possible for the `presentaionHint` to be updated during a session. In the future if needed I will allow for the whoel source object to be rewritten by the adapter

**Comment by roblourens** [comment]
Now when I run "Toggle skip status", nothing happens and it appears to not be running the command. My breakpoint isn't hit at least. Do you see that? It activates the extension but doesn't run the command.

**Comment by isidorn** [comment]
Yes I see the same, from my point your command does not even call into my [customDebugRequest](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugCommands.ts#L45)

@roblourens can you please debug into if your command gets called at all.
If not please check with Joh if something changed in extension contributing commands to menus

**Comment by roblourens** [comment]
#23162
