### ISSUE TITLE
Sidebar search no longer a feature?

### ISSUE THREAD

**Issue by IDrumsey** [microsoft/vscode#224318]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91.1
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Open the "Open Editors" in the sidebar of vscode.
2. Click on a folder.
3. Press `ctrl+f`
4. The search bar for the sidebar doesn't popup. It used too.

I used to be able to really quickly search for a file in the sidebar, but now I can't. Maybe that is a setting that got marked as off as default in a recent update or something. Idk.

**Comment by gjsjohnmurray** [comment]
A couple of releases back its shortcut became Ctrl+Alt+F

**Comment by IDrumsey** [comment]
> A couple of releases back its shortcut became Ctrl+Alt+F

Awesome, thanks!
