### ISSUE TITLE
missing terminal

### ISSUE THREAD

**Issue by monikagupta13** [microsoft/vscode#224383]
Type: <b>Feature Request</b>

The terminal process failed to launch: Path to shell executable "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" does not exist.

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
