### ISSUE TITLE
version 1.10.1  plugin vetur 0.5.1 *.vue不能格式化

### ISSUE THREAD

**Issue by XieYuanCode** [Microsoft/vscode#22434]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.7|
|vetur|octref|0.5.1|;

---

Steps to Reproduce:

1.
2.

**Comment by yefang** [comment]
I can use it before update.

**Comment by ramya-rao-a** [comment]
Can you share a sample code, so that we can try and repro?

**Comment by ramya-rao-a** [comment]
Just looked at the changeling for the vetoer extension. Looks like the formatter was intentionally disabled

https://marketplace.visualstudio.com/items/octref.vetur/changelog
