### ISSUE TITLE
Import Profile configuration picker does not work

### ISSUE THREAD

**Issue by olguzzar** [microsoft/vscode#224392]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- Version: 1.92.0-insider (user setup)
Commit: 52b2f67e96b4e757e8ff8e1e009dfffd70da91f5
Date: 2024-07-30T12:51:05.208Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Make sure the New Profiles UI setting is disabled
2. Import profile
3. Select your profile to import - this happens both when using a pre-configured profile, or importing from a file
4. Un-check one of the configuration options. Note that all of the configurations become unchecked. You then cannot check any of the boxes at that point.
5. Expected behavior would be that only the box you select becomes unchecked, and you're able to import the profile without that configuration set.

https://github.com/user-attachments/assets/40415df7-7e0c-4264-8336-5c028120b9ba

**Comment by mateeni-dev** [comment]
Similar issue. I'm using "Copy from", when creating a new profile.
As soon as I pick an existing profile in the "Copy from" options drop-down, the config check-boxes are cleared below. I cannot check them manually.

I can create a new black profile. But then if I edit profile and uncheck any config checkbox, I am stuck with same issue.

![Screenshot 2024-08-02 071205](https://github.com/user-attachments/assets/6fa9286a-e02d-43ca-808a-fee3ee4a1a91)

**Comment by LaurentOngaro** [comment]
Same issue for me. This issue was not present with the previous version (probably the 1.91)

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/224788

Please use [New Profiles UI](https://github.com/microsoft/vscode/issues/224788#issuecomment-2274305778) as a workaround
