### ISSUE TITLE
Cannot sign in if launching an URL with "msedge" type

### ISSUE THREAD

**Issue by yuqizhou77** [microsoft/vscode#224370]
Type: <b>Bug</b>

Create a project with ".vscode/launch.json" file to launch an URL in edge.
The content of the file is
"{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Preview in Edge",
            "type": "msedge",
            "request": "launch",
            "url": "https://teams.microsoft.com",
            "presentation": {
                "group": "remote",
                "order": 1
            },
            "internalConsoleOptions": "neverOpen",
            "trace": true
        }
    ]
}"

When F5, it prompts me to sign in but the "sign in" button is not clickable so that I cannot continue.
![image](https://github.com/user-attachments/assets/ab0365f1-a11b-491a-8f18-523efc75cd89)

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (16 x 2793)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|63.95GB (50.61GB free)|
|Process Argv|--crash-reporter-id b24f6b88-5694-44a6-bcbe-9d6bdffbeba7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-yaml|red|1.15.0
ms-teams-vscode-extension|Tea|5.8.2-alpha.e185efa53.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31101459
ccplt:31103426
pythonrstrctxt:31103193
wkspc-onlycs-t:31106322

```

</details>

**Comment by yuqizhou77** [comment]
not sure if it will help. here is the trace from debugger
[vscode-debugadapter-3d5b311a.json](https://github.com/user-attachments/files/16437988/vscode-debugadapter-3d5b311a.json)

**Comment by roblourens** [comment]
This sounds like an issue with your code, does it work in Edge when not debugging?

**Comment by yuqizhou77** [comment]
I don't have any source code but just launch.json. 
If opening edge directly, it works which I guess it somehow gets my profile and does not require me to sign in.

**Comment by roblourens** [comment]
Oh, that's a login screen from Edge itself?

**Comment by yuqizhou77** [comment]
Yeah, I think so. But I was only able to repro if running the debugger.
