### ISSUE TITLE
terminal tabs are not restored

### ISSUE THREAD

**Issue by tiancihe** [microsoft/vscode#224372]
Environment:
Version: 1.91.1 (Universal)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:54.982Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.3.0

Issue:
multiple terminal tabs are not restored when workspace is reopened, only the first tab is restored
tried to set
"terminal.integrated.persistentSessionReviveProcess": "onExitAndWindowClose",
and restart vscode, issue still exists

related issue: https://github.com/microsoft/vscode/issues/214183

**Comment by meganrogge** [comment]
if you haven't typed anything in the terminals, they won't be reconnected to. could you pls provide a gif and all of your terminal settings?

**Comment by tiancihe** [comment]
> if you haven't typed anything in the terminals, they won't be reconnected to. could you pls provide a gif and all of your terminal settings?

oh, that's the issue then. tried to typed somethings, the terminals are preserved after reopen.
