### ISSUE TITLE
Opening a folder using vscode.workspace.updateWorkspaceFolders does not allow to execute rest of the code

### ISSUE THREAD

**Issue by rakaboy-s** [microsoft/vscode#224367]
- OS Version: Windows 10

I am trying to render a UI on vscode after the user selects a workspace. The selected workspace is opened using vscode.workspace.updateWorkspaceFolders in my code.

vscode.workspace.updateWorkspaceFolders(
                vscode.workspace.workspaceFolders ? vscode.workspace.workspaceFolders.length : 0,
                0,
                { uri: vscode.Uri.file(usrDefaultPath) }
            );
Once the above code is executed it shutdown the current extension host process. Even code can't stop at the breakpoint.

**Comment by rakaboy-s** [comment]
https://code.visualstudio.com/api/references/commands provides a detail on the behavior
![image](https://github.com/user-attachments/assets/382075b3-937b-4217-9caa-8a80bc4c5a62)

Is there any workaround so that it doesn't terminate current host.

I also tried using vscode.openFolder but the behavior is same.

**Comment by sandy081** [comment]
This is a known limitation and there is no workaround.
