### ISSUE TITLE
Tab key gets processed by Code when I use Alt+Tab to switch windows

### ISSUE THREAD

**Issue by phord** [microsoft/vscode#224344]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:08:12.169Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0

- OS Version: 
Operating System: KDE neon 6.0
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.0
Kernel Version: 6.5.0-41-generic (64-bit)

Steps to Reproduce:

1. Press Alt+Tab to switch to another window. 
2. While still holding Alt, press Tab again to switch to the next window in the chain.
3. Switch back to VSCode
4. See that tabs were inserted in the editor whereever the cursor is.  

If some code was highlighted, the lines get indented.  If my cursor is in the terminal, the terminal gets Tabs inserted.

This happens somewhat reliably.  If I press Alt+Tab four times (while holding the Alt the entire time), I usually (always?) see three Tabs inserted in my code.

I tried changing my "Window Switcher" hotkey to another combo, like Alt+P.  I saw the same behavior.  When I pressed Alt+P four times to switch to the 4th window in my stack, I later found that 3 `p`'s were inserted into my editor.

This only started happening in the last week or two.

**Comment by vladaburian** [comment]
Have found related [reddit thread](https://www.reddit.com/r/kde/comments/1dr3mye/anyone_else_getting_tabs_in_apps_when_alttabbing/) with solution.

You can disable legacy x11 apps from reading keystrokes from other apps in KDE settings by setting this option to `Never`:
```
> System Settings > Application Permissions > Legacy X11 App Support > Allow legacy X11 apps to read keystrokes typed in all apps
```

**Comment by phord** [comment]
This is fixed now in KDE.

https://bugs.kde.org/show_bug.cgi?id=484992
