### ISSUE TITLE
Have #pragma region create collapsible groups in the outline tab

### ISSUE THREAD

**Issue by Leafmun-certii** [microsoft/vscode#224390]
The #pragma region/endregion directive should add groups to the outline tab on the activity bar so that you can collapse groups of like functions/variables in the outline view 

For example, having the defines at the top of the outline collapsible to a "define" group similar to how the struct is collapsible
![image](https://github.com/user-attachments/assets/bf2c54fe-f8c6-4bc4-b7c4-3fe4d6a7f581)

**Comment by gjsjohnmurray** [comment]
Previously requested in #203703, #107084, #51364
