### ISSUE TITLE
Add Julia as a shell type in core

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/vscode#224325]
Part of: https://github.com/microsoft/vscode/issues/155530 
This should allow clear separation when users attempt to "Terminal: Run Recent Command", as in Julia users will only see Julia commands from VS Code and not those from other shells.

**Comment by anthonykim1** [comment]
Verification Steps:
1. Install and Julia and 
<img width="757" alt="Screenshot 2024-08-26 at 3 18 32 PM" src="https://github.com/user-attachments/assets/81978201-5849-4ef4-bca4-88f6aca3c36d">
2. Head over to command palette (launch via ctrl/cmd + shift + p) and press on Julia: Start REPL or Julia: Restart REPL
<img width="360" alt="Screenshot 2024-08-26 at 3 19 11 PM" src="https://github.com/user-attachments/assets/b4ee4881-cb63-439f-810b-2d32695712b6">
3. Type in some Julia command in Terminal
4. Open command palette again and click on "Terminal: Run Recent Command"
5. Observe you only see command from Julia shell and no commands from other shell.

**Comment by amunger** [comment]
the `Terminal: Run recent command` command just no-ops for me if I have a Julia REPL running, even after running commands in there. I don't see any errors in the dev tools.

![Recording 2024-08-28 at 10 03 03](https://github.com/user-attachments/assets/c5929d58-4c49-48bb-a8ab-3d52096e1bad)

**Comment by anthonykim1** [comment]
@amunger What is exact name of the julia executable in your windows machine? Is it something that deviates from "julia.exe"?

**Comment by amunger** [comment]
from julia logs, it looks like it is using "julia.exe"

**Comment by anthonykim1** [comment]
Verification steps should be same as above: https://github.com/microsoft/vscode/issues/224325#issuecomment-2310906132
