### ISSUE TITLE
Tasks UX doesn't load in workspaces

### ISSUE THREAD

**Issue by Gliptal** [microsoft/vscode#224305]
Type: <b>Bug</b>

I'm having a weird issue I can't reliably reproduce, and don't know how to properly debug. All my existing local workspaces seem to have a broken Tasks UX (new workspaces don't exhibit this behaviour). All `Tasks:` commands related to workspaces either silently fail, or hang: for example, `Tasks: Configure Task` opens the input box but it never stops loading and nothing is listed.

![tasks](https://github.com/user-attachments/assets/6270557a-1596-493c-bcdd-9bf6d9e6b51f)

This does not happen if I try on a non-workspace window or create a new workspace, and commands not related to workspaces (like `Tasks: Open User Tasks`) are unaffected (they work).

I realize this isn't enough for a bug report, and something must be amiss on my end, but how can I troubleshoot or debug this? I tried looking at the various output logs and found nothing; where should I look?

The issue also occurs with all the extension disabled (using the bisect tool). 

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700K (24 x 3418)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.75GB (44.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meganrogge** [comment]
are there any errors in the dev tools console? 

can you reproduce in [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed
