### ISSUE TITLE
Terminal suggest: Files are sorted strangely with executables with no prefix

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#224300]
Repro:

- Pwsh/Windows
- Suggest enabled
- Open terminal
- Press ctrl+space

![image](https://github.com/user-attachments/assets/f4ff6d23-9dc2-4766-898a-db5861e4f91b)

**Comment by Tyriar** [comment]
@meganrogge case we should verify/test regardless of provider

**Comment by meganrogge** [comment]
This is looking good for me now, hbu on Windows @tyriar?

<img width="478" alt="Image" src="https://github.com/user-attachments/assets/3154e655-1f0b-44ab-a4a9-7a7e0881ff4e" />
<img width="713" alt="Image" src="https://github.com/user-attachments/assets/35cd0d17-43e9-4a5b-bddb-12b5a3020b7a" />
