### ISSUE TITLE
 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#2243]
Issue Id: <b>b362e838-bb6f-52cc-f764-62479011f442</b><br /><br />*Versions* <br />- 0.10.6-release<br />-  dfc08dc9edf6607483b193bf934d3badc3fa2e11<br />*Stack* <br />TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.<br />    at TypeError (native)<br />[/vs/base/browser/htmlContentRenderer.ts#L187:10 (renderFormattedText)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/base/browser/htmlContentRenderer.ts#L187:10 (renderFormattedText))<br />[/vs/base/browser/htmlContentRenderer.ts#L192:3 (renderFormattedText)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/base/browser/htmlContentRenderer.ts#L192:3 (renderFormattedText))<br />    at Array.forEach (native)<br />[/vs/base/browser/htmlContentRenderer.ts#L191:20 (renderFormattedText)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/base/browser/htmlContentRenderer.ts#L191:20 (renderFormattedText))<br />[/vs/base/browser/htmlContentRenderer.ts#L67:2 (renderHtml)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/base/browser/htmlContentRenderer.ts#L67:2 (renderHtml))<br />[/vs/editor/contrib/hover/browser/modesContentHover.ts#L239:27 (ModesContentHoverWidget._renderMessages)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/editor/contrib/hover/browser/modesContentHover.ts#L239:27 (ModesContentHoverWidget._renderMessages))<br />    at Array.forEach (native)<br />[/vs/editor/contrib/hover/browser/modesContentHover.ts#L238:20 (ModesContentHoverWidget._renderMessages)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/editor/contrib/hover/browser/modesContentHover.ts#L238:20 (ModesContentHoverWidget._renderMessages))<br />    at Array.forEach (native)<br />

**Comment by jrieken** [comment]
not seen anymore, we now use markdown for things
