### ISSUE TITLE
Extensions from pack are not disabled properly

### ISSUE THREAD

**Issue by Imvivi** [microsoft/vscode#224468]
- VS Code Version: 
Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.91.1 Chrome/122.0.6261.156 Electron/29.4.0 Safari/537.36
- OS Version: Windows 10

Steps to Reproduce:

1. Install 'vscjava.vscode-java-pack' and 'dgileadi.java-decompiler'
2. Disable 'vscjava.vscode-java-pack' and click disable all
![image](https://github.com/user-attachments/assets/2300d0a0-6555-4a0d-991d-5f0b543da789)
3. All extensions from pack should be disabled, however they are not.
![image](https://github.com/user-attachments/assets/cb931df7-ccb8-42ce-a36a-2a47882de168)

**Comment by sandy081** [comment]
This seems to work for me. Can you please try our latest [insiders](https://code.visualstudio.com/insiders) and let us know if it works for you?
