### ISSUE TITLE
How extension authors can open Code multiple instance to debug their extension

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#22441]
Hi, 

Is there any way that extension authors can open multiple code instances as currently while debugging it opens only one instance for extension debugging.

Thanks

**Comment by ramya-rao-a** [comment]
What is your scenario?

**Comment by shanalikhan** [comment]
Im using chokidar npm package to view the file change.
When file changes the function runs every time no matter how many code instances are opened, that extension function in all instances run at once.
I want to debug this to stop this thing, off course locking etc can do in order to stop such behavior but it would be nice to debug this for multiple instances.
