### ISSUE TITLE
`code --update-extensions` does not work on arm Mac in Version 1.92.0 (July 2024 Update)

### ISSUE THREAD

**Issue by VicBoss1984** [microsoft/vscode#224495]
Issue description:
- The `code --update-extensions` shell command gets hung whenever it is run. The CLI for VS Code seems like it is getting stuck with the `--update-extensions` flag.
- If the command does not hang, like it usually does in this issue, I get this error message: `Server returned 503`.

System information:
- VS Code Version: 1.92.0
- OS Version: macOS 14.6 (23G80)
- Kernel Version: Darwin 23.6.0
- Architecture: Apple M3-chip or 'ARM'

Expected behaviour:
- The VS Code CLI should be able to finish updating all the extensions and report each extension being installed in real-time via the user's terminal.
- The `code --update-extensions` command should finish within a reasonable amount of time–for instance, within < 10 seconds from when the command is executed.

Steps to Reproduce:

1. Launch any terminal on macOS.
2. Ensure that you have the `code` command in your PATH environment variable by following the instructions and documentation of VS Code online.
3. Run the following command from anywhere: `code --update-extensions`.
4. The command will run in an infiite loop or crash and return the following error code: `Server returned 503`

Here is a sample of the issue as it appears on my terminal:

```sh
ajawad@Macintosh msrp-calculator > code --update-extensions
Server returned 503
ajawad@Macintosh msrp-calculator > code --update-extensions
Updating extensions: ms-python.python, ms-vscode.cpptools, ms-python.debugpy, redhat.java, vscjava.vscode-java-test, vscjava.vscode-java-pack, vscjava.vscode-gradle
Server returned 503
```

Please let me know if there are any debug output files or any logs that I can share to help out the community solve this issue. I use the VS Code CLI quite a bit–and I imagine that many other users use it as well.

Many thanks,
Ali

**Comment by skissane-medallia** [comment]
@VicBoss1984 Check your `$HOME/Library/Application\ Support/Code/logs` directory. when you run `code --update-extensions`, it will should create a new subdirectory of that (with the current timestamp) containing a `network.log` file. Hopefully that will tell you the URL you are getting the 503 error on.

I just upgraded to 1.9.2 (on Mac–albeit M1 Pro not M3, and 14.5 not 14.6) and I don't have the same issue. It might be something specific to your environment or the specific extensions you are updating. Or maybe Microsoft has already fixed it on their end–given it is a 503, it might have been a (temporary?) problem with Microsoft's servers that host the extensions, rather than anything necessarily to do with installing the new VS Code version.

**Comment by VicBoss1984** [comment]
@skissane-medallia Weirdly enough, I am having a hard time reproducing this error now. I think you are most likely right, since I have not tinkered with VS Code that much since the July 2024 update.

I was even able to get the command working with the extension update flag, albeit the command is bottlenecked by how quick the servers that host the extensions are.

For extra context, I tried the Insiders edition of VS Code and was able to get the extensions updating command working. I thought that this behavior was exclusive to the Insiders build, but now I am becoming more certain that it was caused by the servers being able to respond within a reasonable time frame–something that they were surprisingly unable to do yesterday. 

I will share the log files in a few hours when I am on my computer again.

Thanks for the helpful and clear insights,
Ali

**Comment by VicBoss1984** [comment]
@skissane-medallia I believe my `network.log` file is empty, even for all of the `network.log` files for August 2 and 3. I have ten of them and none of them have any contents within them.

The `cli.log` files are not empty, however. Based on what I can see inside them, they contain configuration flags.

Good news is: the `503 error` is not reproducible anymore, so I believe whatever issue Microsoft had with the servers holding their extensions has been resolved at this point.

I guess I will close the issue for now, unless the error/issue is reproducible in the near future.
