### ISSUE TITLE
terminal is lagging

### ISSUE THREAD

**Issue by harshit390-ux** [microsoft/vscode#224427]
Type: <b>Performance Issue</b>

whenever I open new terminal it takes to much time to run. so it makes trouble in running code in terminal.

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800HS with Radeon Graphics         (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (8.68GB free)|
|Process Argv|--crash-reporter-id 539f8ba5-79dd-454b-94df-f3f4c4b12f0d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   126	  7100	code main
    0	    99	 11600	window [2] (Issue Reporter)
    0	    28	 15828	   crashpad-handler
    0	   148	 15976	   gpu-process
    0	    51	 16132	   utility-network-service
    0	   217	 16228	window [1] (Settings - Visual Studio Code)
    0	   163	 16584	extensionHost [1]
    0	    26	  7900	     c:\Users\harsh\.vscode\extensions\ms-vscode.cpptools-1.21.4-win32-x64\bin\cpptools.exe
    0	     3	  6580	       "c:\Users\harsh\.vscode\extensions\ms-vscode.cpptools-1.21.4-win32-x64\bin\cpptools.exe"
    0	    15	  5096	         c:\Users\harsh\.vscode\extensions\ms-vscode.cpptools-1.21.4-win32-x64/bin/cpptools-srv.exe 7900 {96488712-32DF-43EA-91AE-0FC7A2DD29B6}
    0	    10	  4308	           C:\Windows\system32\conhost.exe 0x4
    0	    10	  7784	       C:\Windows\system32\conhost.exe 0x4
    0	    90	 13524	     "C:\Users\harsh\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\harsh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=16584
    0	   109	 16904	shared-process
    0	    82	 17068	fileWatcher [1]
    0	   104	 17304	ptyHost
    0	    70	  7564	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    64	  9748	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     7	 10912	     conpty-agent
    0	     6	 16696	     conpty-agent
    0	    64	 16892	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     7	 21136	     conpty-agent
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.4
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31101459
ccplti:31103428
pythonrstrctxtcf:31103194
wkspc-onlycs-t:31106322
wkspc-ranged-t:31107835

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
