### ISSUE TITLE
php Selected variable problem

### ISSUE THREAD

**Issue by hulang** [Microsoft/vscode#22445]
- VSCode Version:1.10.2
- OS Version:win7 x64

Steps to Reproduce:

1.Selected variable $data,Only select data，$ You cannot select.

**Comment by Tzook** [comment]
You can edit the list of characters that separate words.
Go to settings and change value of the key "editor.wordSeparators". 
It defaults to "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?" so all you have to do is to remove the $.

**Comment by ramya-rao-a** [comment]
@Tzook is correct
