### ISSUE TITLE
Silent crash on startup

### ISSUE THREAD

**Issue by lowski** [Microsoft/vscode#22449]
- VSCode Version: 1.10.2
- OS Version: OS X 10.12.3

Steps to Reproduce:

1. I open Visual Studio Code (either from terminal or App icon)
2. It closes itself but the window is still visible (icon on the dock disappears)
3. When I try to type I'm not able to, but I am able to click trough the interface
4. I don't see any error message

I tried to remove `~/.vscode` directory, clear settings but it didn't help. I tried to reinstall the app but after a few restarts problems come back. I don't see anything on Console log.

Any idea what can be the issue or how I can debug it further?

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by lowski** [comment]
Thanks for reply.

1. Here is the output from `code --verbose`:

```
$ code . --verbose
[main 09:16:06] Sending env to running instance...
[main 09:16:06] Sent env to running instance. Terminating...
```

2. in Code select Help | Toggle Developer Tools and select the Console - I'm not able to check it because when I start the code it immediately terminates. The main window frame stays but I don't see its menu on the toolbar so no way to turn it on.

3. attach any output you see in the Console you can find - Unfortunately I don't see anything from code on the Console.

**Comment by bpasero** [comment]
@lowski does it reproduce after rebooting the machine?

**Comment by lowski** [comment]
@bpasero weird, after restart it works. I didn't think about it since I don't restart my mac ;).

**Comment by bpasero** [comment]
@lowski this indicates that a leftover process from a previous session was still alive and hanging around. The restart cleaned up this hanging process (alternative you could try to kill the hanging process from the activity manager).

**Comment by lowski** [comment]
@bpasero thank you very much for your assistance.
