### ISSUE TITLE
mssql extension - Installing SQL tools service behind a proxy - Error: Request error: EPROTO

### ISSUE THREAD

**Issue by doctavian** [Microsoft/vscode#22440]
- VSCode Version: 1.10.2
- OS Version: Windows 10.0.14393 N/A Build 14393

Steps to Reproduce:

1. computer behind a proxy 
2. install mssql extension
3. run code
4. create t1.sql file
5. start typing a statement
6. code starts to install sql tools service and after a while it shows 

Initializing SQL tools service for the mssql extension.
Note: mssql commands will be available after installing the service.

Platform: win32, x86_64 (Windows)

Installing SQL tools service to C:\Users\user\.vscode\extensions\ms-mssql.mssql-0.3.0\sqltoolsservice\0.3.0.5\Windows.
Downloading https://download.microsoft.com/download/A/A/2/AA22B2D6-94D8-4C82-A388-D0246F567BBF/microsoft.sqltools.servicelayer-win-x64-netcoreapp1.0.zip
[ERROR] Error: Request error: EPROTO

**Comment by joaomoreno** [comment]
Closing until we nail a solution in #22214, and then propagate that for extensions.
