### ISSUE TITLE
Disable weird lines (hover? focus?) in the integrated terminal 

### ISSUE THREAD

**Issue by sapegin** [microsoft/vscode#224469]
There are two lines in the terminal left margin. One, very bright white, line appears on hover on each command, and the other, gray, line appears I don't know when, sometimes. I don't know what they do, I don't need them, and they are very very distracting. Is there a way to disable them? Or at least change the color to transparent.

![CleanShot 2024-08-01 at 12  22 48](https://github.com/user-attachments/assets/2ea24980-083a-4ef9-8e4b-cc1b9d1f76be)

**Comment by meganrogge** [comment]
does disabling `terminal.integrated.shellIntegration.enabled` fix this for you? I am not reproducing, but we have command line decorations when one navigates using `ctrlCmd+up/downArrow` with shell integration, so wondering if that's what you're seeing?

**Comment by Tyriar** [comment]
This is called the "command guide" and doesn't seem to have a documentation entry yet. It uses the same theme key as the similar feature in notebooks right now: `notebook.inactiveFocusedCellBorder`. It looks like your theme is an atypical one where it's light everywhere except for the terminal, so when in notebooks it might be the same as the background color. 

You can make it invisible with this setting:

```
"workbench.colorCustomizations": {
  "notebook.inactiveFocusedCellBorder": "#0000"
}
```

We should add a setting to disable this and a separate theme key.

**Comment by Tyriar** [comment]
The smaller line is command navigation. Those lines just stick around currently until they're moved again, you could clear the terminal, use command nav again or create a new terminal to move that one.

**Comment by Tyriar** [comment]
To verify make sure the `terminal.integrated.shellIntegration.showCommandGuide` setting and `terminalCommandGuide.foreground` theme keys work as expected.

The command guide should show when hovering a command or its output in a shell integration-enabled terminal (provided the command isn't very long):

![image](https://github.com/user-attachments/assets/989305b2-12ec-4207-9c12-c3e6dc1dc1e9)

**Comment by joyceerhl** [comment]
`terminal.integrated.shellIntegration.showCommandGuide` seems to have no effect on already-open terminals, only new ones

**Comment by Tyriar** [comment]
@joyceerhl could you create an issue for that? It should

**Comment by joyceerhl** [comment]
https://github.com/microsoft/vscode/issues/226868
