### ISSUE TITLE
Mac Right-click Focus

### ISSUE THREAD

**Issue by andrewgtibbetts** [microsoft/vscode#224421]
Type: <b>Bug</b>

- in macOS, split-full-screen VSCode with any other app
- focus on the other app
- right-click on VSCode while focused in the other app
- now left-click to focus into VSCode

right-click is disabled in VSCode until I focus back into any other app and then left-click back into VSCode.

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin x64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.69GB free)|
|Process Argv|--crash-reporter-id b7e08ed5-dec2-400a-8b6d-88eff5e24920 --crash-reporter-id b7e08ed5-dec2-400a-8b6d-88eff5e24920|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.1.2
atlascode|atl|3.0.10
color-info|bie|0.7.2
css-biscuits|Cod|0.0.7
html-biscuits|Cod|0.0.15
codeium|Cod|1.10.6
language-postcss|cpy|1.1.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
figma-vscode-extension|fig|0.3.5
copilot|Git|1.219.0
copilot-chat|Git|0.17.1
live-sass|gle|6.1.2
angular-essentials|joh|18.0.0
Angular2|joh|18.0.2
vscode-duplicate|mrm|1.2.1
vsliveshare|ms-|1.0.5936
gremlins|nho|0.26.0
indent-rainbow|ode|8.3.1
vscode-yaml|red|1.15.0
lit-plugin|run|1.4.3
markdown-preview-enhanced|shd|0.8.13
vscode-scss-formatter|sib|3.0.0
tree-exporter|Tin|1.0.2
vscode-mdx|uni|1.8.9
errorlens|use|3.20.0
vscode-css-variables|vun|2.7.1
five-server|yan|0.3.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactorc:31101458
ccpltc:31103427
pythonrstrctxt:31103193
wkspc-onlycs-c:31102393

```

</details>

**Comment by bpasero** [comment]
I cannot reproduce, do you maybe have some kind of window manager installed?

Btw the setting `window.clickThroughInactive` might have an impact.

**Comment by andrewgtibbetts** [comment]
Nope, no third-party window manager.
Couple things though:
1) I use a Logitech MX Master 3 mouse that uses the Logi Options+ configuration software. So, I thought it might be the mouse+software, but I tested with a wired mouse and had the same issue.
2) as added info, ctrl + left-click also does not engage the contextual menu once you have right-clicked into VSCode from another app in split-full-screen, but, you can ctrl + left-click from the other app and get the contextual menu in VSCode.

**Comment by andrewgtibbetts** [comment]
Another bit of info: The issue happens when not in fullscreen, too. Fullscreen or windowed, no difference. Updated the title of this issue.

**Comment by andrewgtibbetts** [comment]
Well, this might be a macOS issue...
I have found that if I right-click into Edge while focused in another app, and then focus into Edge, I can still right-click but all cmd + action keystrokes don't work. The plot thickens...so, I will close this issue since this has grown bigger than just VSCode.
