### ISSUE TITLE
Task that fail with `close: true` no longer notify user of errors

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#224412]
1. Have a task that will fail and close, such as this one (or the prelaunch task in vscode)

```js
    {
      "label": "My Task",
      "type": "shell",
      "command": "exit 1",
      "problemMatcher": [],
      "presentation": {
            "close": true
      }
    },
```

2. run it
3. Expect to see the usual error notification, but instead observe an "InstatiationService has been disposed" console error from 

https://github.com/microsoft/vscode/blob/6f2764acf84f4eb2c751f0ee635c057965a8147f/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1614

In debug land this then prevents the user being able to debug things with prelaunch tasks that fail with `close: true` because this is thrown before `onExit` fires

**Comment by meganrogge** [comment]
Should see this (in v 1.91)

![Image](https://github.com/user-attachments/assets/a05d6adc-0136-409c-9602-26fecc042ab0)

**Comment by meganrogge** [comment]
@connor4312 believes this is caused by https://github.com/microsoft/vscode/commit/478a5c2bb7434e3b16c6a67e2c1c89c10cff54c6 @Tyriar
