### ISSUE TITLE
Marketplace doesnt publish extension when previous version of extension file is uploaded

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#22444]
Is there any way to unpublish the LAST VERSION OF PUBLISHED EXTENSION. 

I want to insert the vsix file of v2.5.1 as i have published the v2.6.0 recently and want to revert that so every one can download the older v2.5.1

I have tried uploading v2.5.1 multiple times but version doenst seem to be change in the marketplace.

I see unpublish button but users wont be able to download the extension at all even v2.5.1

**Comment by joaomoreno** [comment]
The rule is: *always move forward*.

Why don't you release a 2.6.1 reverting the behaviour to 2.5.1?
