### ISSUE TITLE
I can't see my recent project list on right-click context menu on dock

### ISSUE THREAD

**Issue by xtzero** [microsoft/vscode#224474]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.1 (Universal)
- OS Version: macOS Sonoma 14.2.1 (23C71)

Steps to Reproduce:

1. Open VS Code app
2. Open 2 projects
3. Close these windows
4. Right click VS Code's icon on dock
5. Don't see recent projects list

I have a macbook pro in my house, and have another mac mini in company, I installed VS Code on both them. Company's VS Code can see the list but house's can't.

Following screenshot is the wrong one.

<img width="351" alt="image" src="https://github.com/user-attachments/assets/4613ca26-639e-49e8-9894-d16fd21edef3">

**Comment by xtzero** [comment]
The screenshot below was taken using the company's Mac Mini.

![image](https://github.com/user-attachments/assets/7c81c24e-604c-4b30-87c1-1a52bc2d1fb2)

**Comment by aiday-mar** [comment]
Hi Joh, I saw you are working on menus in VS Code. I am not sure if this is the correct assignment, let me know if it isn't.
