### ISSUE TITLE
Blur after scroll in Extensions

### ISSUE THREAD

**Issue by vandijkstef** [Microsoft/vscode#22442]
- VSCode Version: 1.9.1
- OS Version: W10

Steps to Reproduce:

1. Open the extensions tab, make sure you can scroll down in it
2. Scroll all the way down, as soon as I hit bottom, the whole list gets blurry
3. Scroll a bit up, the list remains blurry
4. As soon as I hit top of the list, everything is fixed again

This is reproducible over and over again. This does not occur in folder view.

It feels like when hitting the bottom of the list, it offsets everything in that list by a half pixel. Thus all text is rendered blurry

**Comment by ramya-rao-a** [comment]
Can you share a screenshot?

**Comment by sandy081** [comment]
@vandijkstef I see scrolling in Extensions viewlet works perfectly fine for me. Any additional info would be helpful.

**Comment by sandy081** [comment]
Closing this issue, please reopen with requested information
