### ISSUE TITLE
File tree search for documents

### ISSUE THREAD

**Issue by zheng1224** [microsoft/vscode#224455]
Type: <b>Bug</b>

It is not possible to fill in the file name and then search for the file in the file tree using Ctrl+F

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (4.59GB free)|
|Process Argv|--crash-reporter-id 511113a2-e84f-43e7-a933-686d5c345c0f|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
icons-carbon|ant|0.2.6
prettier-vscode|esb|10.4.0
code-runner|for|0.12.2
vscode-language-pack-zh-hans|MS-|1.91.2024071009
vetur|oct|0.37.3
material-icon-theme|PKi|5.8.0
LiveServer|rit|5.7.9
open-in-browser|tec|2.0.0
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31101459
ccplc:31103425
pythonrstrctxtcf:31103194
wkspc-onlycs-c:31106320

```

</details>

**Comment by IllusionMH** [comment]
This change was announced couple of updates ago https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding

But you can rebind command to your preference

**Comment by zheng1224** [comment]
> This change was announced couple of updates ago https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding
> 
> But you can rebind command to your preference

This was very helpful, thanks
