### ISSUE TITLE
Moving cell using toolbar moves in-focus cell instead of cell whose toolbar is used

### ISSUE THREAD

**Issue by MarinMlinarevic** [microsoft/vscode#224437]
Type: <b>Bug</b>

Steps to reproduce:
1. Click inside a cell in a Jupyter notebook.
2. Click on the overflow button (...) in another cell's toolbar, the select "Move Cell Down" or "Move Cell Up".

Result: The cell containing the cursor, clicked in Step 1, is moved.
Expected result: The cell whose toolbar was used should be moved.

![Moving cells using toolbar](https://github.com/user-attachments/assets/b939b790-0c50-4684-a2d2-59c98573786a)

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31101459
ccplc:31103425
pythonrstrctxtcf:31103194
1iic9185:31097392
wkspc-onlycs-c:31106320

```

</details>

**Comment by rebornix** [comment]
To enable the Move* commands in the menu, you would need to set `notebook.dragAndDropEnabled` to `false`.

**Comment by rzhao271** [comment]
Also had to change `notebook.cellToolbarVisibility` to `hover`. Verified.
