### ISSUE TITLE
Perhaps not an issue regarding minmap hover-appear request

### ISSUE THREAD

**Issue by jdc-cunningham** [microsoft/vscode#22446]
I like the minmap but I was wondering if it was possible to have it appear only when you hover over the scrollbar and then mouse over to the minmap to use it. Otherwise it takes up a lot of space.

If this can already be done how do I enable the hover-appear instead of just constantly displayed?

I like using it, overview of the code/seeing code groups/fast scrolling.

**Comment by michaeljota** [comment]
I would like to see this as well, if I understand right, it would act more like a preview of the whole file in an overfloating way while scrolling, but it would hide otherwise, right? If that's what you mean, take my +1

**Comment by jdc-cunningham** [comment]
Sorry to add another feature to this:

Another idea is when you hover over a group of code, to have an overlay say what that code is like if it's a function, say the function's name.

Right now when you hover over the min-map you get the transparent-block appear next to the scrollbar. Instead or along with that, if you're hovering over a big function, the name of that function appears where you're hovering. Or perhaps, magnify the text to readable in that area even if it's a couple words out of 2-3 lines for "quick-zooming".

**Comment by hediet** [comment]
Related: 107116

**Comment by alexdima** [comment]
This is now possible using `"editor.minimap.autohide": true` (via https://github.com/microsoft/vscode/pull/153093)
