### ISSUE TITLE
Move the "Tasks" items out of the menu "Terminal"

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#224473]
The [Tasks](https://code.visualstudio.com/docs/editor/tasks) commands reside under the "Terminal" menu. It does not make a lot of sense (only slightly).

![image](https://github.com/user-attachments/assets/ae9f4713-2992-4192-9e29-a3fe41c101e4)

Would it make sense to move these under its own "Tasks" menu item? Or possibly under the "Run" menu if it was restructured a bit.

**Comment by gjsjohnmurray** [comment]
Previously requested in #107683 which also links to an earlier issue under which a previously separate Build menu got relocated into Terminal.

**Comment by Tyriar** [comment]
It's also here:

![image](https://github.com/user-attachments/assets/8ea069b2-96ff-41fe-8af0-3fde2199cd93)

If we removed tasks from the Terminal menu, it would only have 4 entries which by itself doesn't justify its own menu imo. Personally I think that they are related enough to both live under Terminal.

Moving to Run would make the situation worse as there is already plenty of stuff in that menu. Plus tasks most often build, not run.

**Comment by meganrogge** [comment]
After discussing this more, we decided that there aren't enough `Task` or `Terminal` menu items to justify adding another `Menu`, so closing this.

**Comment by thernstig** [comment]
I understand it is not ideal adding a new menu, but maybe there is a compromise somewhere no one has thought about that you can brainstorm? I am sure you agree that having "Tasks", that are often used to build compiled languages such as C/C++, isn't great to have under "Terminal"?

> If we removed tasks from the Terminal menu, it would only have 4 entries which by itself doesn't justify its own menu imo. Personally I think that they are related enough to both live under Terminal.

I don't think that is a problem. I find it more discoverable that way keeping it short and sweet, but I have not done an UX on that if that pertains to everyone else or not.

I wish at least the thread here could find a much better place than "Terminal", it just is not logical to find all task-related commands under there.

**Comment by Tyriar** [comment]
@thernstig it's already at compromise, I think the history on #56836 was to reduce the amount of items in the menu bar. This just isn't a priority and any change we make to this area will annoy users so it should be significantly better if we do change it. I said to @meganrogge in DMs that we should only do this if UX were to do a consistency pass of the menu bar such that there's good justification to make the change. It's just not that important relative to everything else, the fact that there are so few issues mentioning this proves that it's not that important to the user base either.

**Comment by thernstig** [comment]
Thanks for chiming in Tyriar. Maybe an overall UX pass of the menu bar in the future finds a better place, if ever.
