### ISSUE TITLE
Split color themes into UI and Syntax themes

### ISSUE THREAD

**Issue by astamataris** [Microsoft/vscode#22443]
I come from Sublime and Atom where you have the option to have a separate theme for the UI (File explorer, tabs etc.) and a different theme for the editor. This allows me to have a light(white) UI and material syntaxt for example. I believe it adds a lot to the customisability of the editor and at least brings it on par with Atom and Sublime.

Good work with what you've done so far!

**Comment by ramya-rao-a** [comment]
@bpasero @aeschli Do you want to track this separately or cover this in #3112?

**Comment by bpasero** [comment]
I would close this as duplicate of #3112 but I let Martin decide.

**Comment by aeschli** [comment]
closing as duplicate of #3112
