### ISSUE TITLE
Terminal suggest: Completions differ for args depending on when they are requested

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#224419]
Repro:

- pwsh
- suggest enabled
- type `git cl`, suggestions show including `clean`, `clone` and `citool`
    <img width="164" alt="Screenshot 2024-07-31 at 10 56 43 AM" src="https://github.com/user-attachments/assets/97890e89-0101-42b4-8233-cf9dc1e3eb2d">
- press escape
- press ctrl+space, 🐛 suggestions should be the same but now don't include `citool`
    <img width="118" alt="Screenshot 2024-07-31 at 10 56 51 AM" src="https://github.com/user-attachments/assets/43202209-f9e8-4124-968f-f4439b177cd2">

**Comment by rzhao271** [comment]
Verified, though I noticed while typing `git cl` that there was a noticeable delay after typing `git c`.
