### ISSUE TITLE
git一直显示扫描中

### ISSUE THREAD

**Issue by GuoWeiChi** [microsoft/vscode#224467]
Type: <b>Feature Request</b>

git一直显示扫描中

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by Ekreke** [comment]
same problem , when use ssh connected a remote server...
