### ISSUE TITLE
Cannot debug main process

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#224466]
Steps to Reproduce:

1. add breakpoint to https://github.com/microsoft/vscode/blob/6b46ba06dd9de6720fb49601609f347b4e4cf198/src/vs/platform/windows/electron-main/windowImpl.ts#L1039
2. F5
3. => not hit

**Comment by connor4312** [comment]
This works for me -- can you

1. Confirm which launch config you're using 
2. Add `trace: true` to whichever launch config is attaching to the main process, and share the resulting log file whose location is written to the Debug Console?

**Comment by bpasero** [comment]
Sorry, my bad. In our ESM branch we work from a `src2` folder and not `src` and I had set the breakpoint in `src`.
