### ISSUE TITLE
Update 1.92.0 broke php-cs-fixer code formatting for php.

### ISSUE THREAD

**Issue by MircoBabin** [microsoft/vscode#224550]
Type: <b>Bug</b>

Up until version 1.92.0 code formatting using php-cs-fixer extension worked flawlessly. But after the update today, the statusbar shows "php-cs-fixer: formatting" forever, it does not end, nor does it execute anything it seems. It does not matter if code formatting is triggered manually via "format document" or via the save mechanism.

Clicking on "php-cs-fixer: formatting" shows an output panel containing:
[
  "fix",
  "--using-cache=no",
  "--format=json",
  "--config=d:\\Projects\\Webpage\\tripportals\\.php-cs-fixer.dist.php",
  "--path-mode=override",
  "C:\\Users\\Mirco\\AppData\\Local\\Temp\\pcf-tmp0.8835020385733021\\ApiOrderRequest_WriteTouOpdr.php"
]

![image](https://github.com/user-attachments/assets/a7282aa6-5a4b-408e-bc5f-69c8cf115162)

I have read the release notes and there is a mention of "**Notice of breaking API change when spawning .bat or .cmd files**". I am on Windows and php-cs-fixer in settings has as executable "php-cs-fixer.bat". So I'm wondering if this "breaking api change" broke php-cs-fixer?

![image](https://github.com/user-attachments/assets/025a36dc-945c-41ac-959f-a5012963a105)

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (8.72GB free)|
|Process Argv|C:\\Users\\Mirco\\Documents\\workspace.tripportals.code-workspace --crash-reporter-id a732a60b-9787-4676-b932-62966bfdd436|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|10.4.0
php-cs-fixer|jun|0.3.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
f8hc8238:30694864
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
ccplt:31103426
pythonrstrctxtcf:31103194
wkspc-onlycs-c:31106320

```

</details>

**Comment by MircoBabin** [comment]
Maybe related: https://github.com/junstyle/vscode-php-cs-fixer/issues/212#issue-2402024749

**Comment by MircoBabin** [comment]
I downgraded/rolled back to vs code 1.91.1 using the following steps:

- download june 2024 version from https://code.visualstudio.com/updates/
- close any running instance of vs code.
- execute VSCodeUserSetup-x64-1.91.1.exe
- Choose "Yes" on this strange message. **Do not uninstall vs code, because you will loose all settings/extension etc.!**
![image](https://github.com/user-attachments/assets/892d6005-a095-46d7-a4a7-14ecf7376b39)

**After this, php-cs-fixer code formatting works again.**

**Comment by MircoBabin** [comment]
I don't entirely agree with the assesment "caused by extension". It is caused by a breaking change in VS Code. And yes the extension should probably fix this.

**BUT:**
* filing https://github.com/junstyle/vscode-php-cs-fixer/issues/212 is a startpoint.
* But the assumption that a breaking change is always the problem of an extension is invalid. (see the /causedByExtension close reason of this issue)
* But the assumption an extension author can use an insider build is invalid. (see the filed extension issue)
* But the assumption an extension author has time within 1 month to fix/test a breaking change is invalid. (see the filed extension issue)
* But the assumption that VS Code can be used without extensions is invalid. (see my/this issue) I'm used to writing unpretty code, using php-cs-fixer to prettify my code. This saves me a lot of time, and a lot of not entering the spacebar/enter key.
* But the assumption that filed issues at extensions are a one-way channel, a directive that must be acted upon by the extension author is invalid. (see the release of 1.92.0) In general, because it is open source (and not paid), one can not expect any extension author to act upon anything!

I'm sorry to say, but the VS Code team knew https://github.com/junstyle/vscode-php-cs-fixer/issues/212 was still an open issue. There was no feedback from the extension author, the issue was not closed. So in this case, either the Release Notes should have mentioned that php-cs-fixer extension is affected by the "breaking api change" or v1.92.0 should have not been released at all until feedback from all extension authors was received.

None the less: I do really like VS Code!

**Comment by gjsjohnmurray** [comment]
AFAIK the breaking change was required in order to address a security vulnerability.
