### ISSUE TITLE
So hard to see what Tab is active

### ISSUE THREAD

**Issue by htruongVCC** [microsoft/vscode#224579]
Type: <b>Feature Request</b>

It's so hard to see what Tab is being active.
I understand that I has a blue strip line on the tab.
But the tab is right under a bright color Menu Bar, it makes difficult to see the blue strip line.
Please highlight the active better.

Look at this screenshot, I can hardly say which tab is my active tab:
![image](https://github.com/user-attachments/assets/283cf604-a848-4a5c-a9f6-c78faba80bca)

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:08:12.169Z)
OS version: Linux x64 6.5.0-45-generic snap
Modes:
Remote OS version: Linux x64 5.4.0-150-generic
Remote OS version: Linux x64 6.2.0-34-generic

**Comment by htruongVCC** [comment]
Updated to 1.92.0. My issue remains.

**Comment by gjsjohnmurray** [comment]
There are some customizable colors relevant to this:

https://code.visualstudio.com/api/references/theme-color#editor-groups-tabs

The top of that page explains how you can tweak them individually.

**Comment by htruongVCC** [comment]
Thank you, @gjsjohnmurray & @albertosantini so so much. You made my day :)
