### ISSUE TITLE
jsdoc auto-insert parameter names and render HTML

### ISSUE THREAD

**Issue by steveluc** [Microsoft/vscode#22456]
Great feature auto-jsdoc!!!

Is there a reason not to put in the parameter types, if present?  Including {parameter-type} before the parameter name leads to clearer highlighting of the parameter name.

Also, HTML within the jsdoc comments is reproduced plain text.  Is there a plan to render the HTML?

Thanks!

Steve

**Comment by mjbvz** [comment]
If you are working in TypeScript, we don't use the parameter type information from the JSDocs. The types in the code are the source of truth here. At best, the jsdocs types are just duplicated info and they can easily get out of sync with what the actual types in code. If you are in JavaScript, we auto generate parameter types, although in most cases these end up being `*` initially

---

HTML in comments is currently a VSCode limitation being tracked by #11877

**Comment by steveluc** [comment]
Thanks!

**Comment by steveluc** [comment]
But if we are not going to put in the parameter type, can we set up the highlighting to make the parameter name a different color?  Would be useful to be able to quickly scan the list of parameter descriptions for the parameter you want to know about.
