### ISSUE TITLE
Pop-up boxes

### ISSUE THREAD

**Issue by yuri-dev** [microsoft/vscode#224599]
Type: <b>Feature Request</b>

Please do something about all these annoying pop-up boxes (completions and hints).
They are ALWAYS appear under the mouse pointer and gone only after I hit the  ESC key.I haven't seen anything like that in JetBrains IDE.
For now, I have two options for VS Code behaviour: first, be patient; second, return to the Stone Age without enough information in the IDE editor.

VS Code version: Code 1.91.0 (Universal) (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:54:18.541Z)
OS version: Darwin arm64 23.5.0
Modes:

**Comment by jrieken** [comment]
Please be more concrete, include steps and actual vs desired behaviour. Also file one issue per topic

**Comment by yuri-dev** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.92.0. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

Thanks! In new version the problem seems to have been solved.
