### ISSUE TITLE
Integrated terminal sticky header font has broken anti-aliasing

### ISSUE THREAD

**Issue by kliput** [microsoft/vscode#224548]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.0
- OS Version: Ubuntu 22.04.4 (with latest updates)

Steps to Reproduce:

1. Enable sticky scroll in terminal `"terminal.integrated.stickyScroll.enabled": true`
2. Launch some command in the integrated terminal, which has output long enough to see the sticky scroll (eg. `ls /bin`)

The font in the sticky header has poor anti-aliasing that is significantly different from the standard font in terminal (marked using the red box on the screenshot):

![image](https://github.com/user-attachments/assets/81fbbcef-93d5-447f-bd7f-208a21327ff9)

**Comment by jmg-duarte** [comment]
This only happens in light themes though! See the difference
<img width="235" alt="Screenshot 2024-08-09 at 16 18 15" src="https://github.com/user-attachments/assets/d8aebe42-a92f-4609-b0dc-6883ac170ae7">
<img width="219" alt="Screenshot 2024-08-09 at 16 18 26" src="https://github.com/user-attachments/assets/b11f93bb-47b0-4bbe-9397-dd9c6d73cb0b">

**Comment by kliput** [comment]
Yes, it is fixed in version: 1.93.0-insider (Commit: 4693ac3d4dce852b747d08d4bc54db5e35afe268).
Thank you!

![Zrzut ekranu z 2024-08-09 20-27-05](https://github.com/user-attachments/assets/ca84af1a-5f87-48f1-8b73-7beae5ade958)
