### ISSUE TITLE
Create New Terminal in Editor Area not working on non-main windows

### ISSUE THREAD

**Issue by tamnguyenswe** [microsoft/vscode#224555]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.0, commit b1c0a14de1414fcdaa400695b4db1c0799bc3124
- OS Version: Windows 10 Enterprise, 22H2 build 19045.4651

Error message:
`The editor could not be opened due to an unexpected error: Not allowed to create elements in child window JavaScript context. Always use the main window so that "xyz instanceof HTMLElement" continues to work.`

Steps to Reproduce:

1. Open a new VS code window
![image](https://github.com/user-attachments/assets/a3c1841e-2429-4194-a628-5a2082dfcb34)
2. Create a new file and drag out to make another window
![image](https://github.com/user-attachments/assets/b06f15a0-d12d-4024-a6f2-dc6b71a87ca6)
3. Run "Create New Terminal in Editor Area" on that new window
![image](https://github.com/user-attachments/assets/40be833f-3917-4c26-9685-767c254df348)
4. The error will show up
![image](https://github.com/user-attachments/assets/dfe2cd84-7c95-4120-9373-62336ec6ee24)
5. Clicking "Try Again" will reload the terminal, but it doesn't accept inputs, cannot type anything there
![image](https://github.com/user-attachments/assets/67ca6341-d8e4-407e-9a62-9c5c0b5c3290)

Creating terminal in main window and drag it to side windows does work, but I have to do that with every window reload.
Yesterday I could still use terminals in side windows like normal, this only occured after updating to 1.92 July update
Thanks for reading :)

**Comment by meganrogge** [comment]
coming from xterm here I think

![Image](https://github.com/user-attachments/assets/7f156d4a-e55c-40d3-a3cd-a8e3e06d9904)

**Comment by Qinka** [comment]
I have the same problem on Fedora 40 Sway.

After I click `Try Again`, it will create a non-interoperable terminal.

**Comment by wsnjie** [comment]
I'm also having this issue, I thought it might be a problem with WSL but it started for me after updating to VSCode 1.92.0
![image_2024-08-05_104041191](https://github.com/user-attachments/assets/0c199b37-78c6-4277-80a6-dd01d47a90cd)

**Comment by subhadeepchowdhury41** [comment]
QUICK FIX!!!

Just create a new In-window terminal and drag it to the new terminal window. 👍

**Comment by michaelschufi** [comment]
Will this be hotfixed or should we downgrade?

**Comment by Tyriar** [comment]
@michaelschufi sorry this won't get a patch release as there's a few workarounds

**Comment by GillesTabary** [comment]
Hi.

> QUICK FIX!!!
> Just create a new In-window terminal and drag it to the new terminal window. 👍

Didn't do the trick for me. Other hack: Ctrl+J (new term in main window) > Ctrl + Shift + P > Terminal: Move Into New Window > Drag & Drop into wanted window. Cumbersom many many times a day.
