### ISSUE TITLE
Extension Development (Insiders): exits unexpectedly when executing command: vscode.openFolder

### ISSUE THREAD

**Issue by Jason3S** [microsoft/vscode#224593]
Note: Currently works on 1.92.0 stable.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.93.0-insider
Commit: 3b27f1f74bc09fe2e2068997fcd42768be44a4e3
Date: 2024-08-02T05:03:53.254Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 23.5.0
```
- OS Version: Linux and MacOS (not sure about Windows).

Steps to Reproduce:

1. Follow the directions at: https://code.visualstudio.com/api/working-with-extensions/testing-extension and/or https://github.com/microsoft/vscode-test/tree/main/sample

2. In a test, try to open a different folder than the one used to launch the tests:
    ```
    await vscode.commands.executeCommand('vscode.openFolder', folderUri);
    ```

The process will just exit without throwing an exception that can be caught.

Example Output:

[Log](https://github.com/streetsidesoftware/vscode-spell-checker/actions/runs/10215478110/job/28264977295)

```
Extension host test runner error { name: 'Canceled' }
Asking native host service to exit with code 1.
[main 2024-08-02T12:23:13.915Z] Extension host with pid 2930 exited with code: 0, signal: unknown.
Exit code:   1
TestRunFailedError: Test run failed with code 1
    at ChildProcess.onProcessClosed (/home/runner/work/vscode-spell-checker/vscode-spell-checker/node_modules/@vscode/test-electron/out/runTest.js:110:24)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  code: 1,
  signal: undefined
}
Failed to run tests
```

**Comment by bpasero** [comment]
Changing a folder restarts the extension host, is that what you are seeing? An extension host does not survive a change of folders.

**Comment by Jason3S** [comment]
@bpasero,

Hmmm, that could be what is happening. In previous versions, the restart some how stayed linked to the test runner, (that explains some duplicate test output I had seen).  It seems like the way the Extension Host is restarted has changed with 1.93.0.

**Comment by Jason3S** [comment]
@bpasero,

Thank you for the quick response.
