### ISSUE TITLE
Cannot hide incoming/outgoing in the Source Control view container

### ISSUE THREAD

**Issue by cathalmccosker** [microsoft/vscode#224576]
This issue is related to the previous issue here

https://github.com/microsoft/vscode/issues/192290

Prior to a recent update you could disable the incoming/outgoing via setting the following:

```
  "scm.showIncomingChanges": "never",
  "scm.showOutgoingChanges": "never",
```

However it no longer seems to work.

**Comment by rtaque** [comment]
Same problem here since 1.92.0 on debian. The settings `scm.showIncomingChanges` and `scm.showOutgoingChanges` have no effect anymore.

**Comment by mgabeler-lee-6rs** [comment]
Also they show changes that are neither incoming nor outgoing. In my case it seems that they are showing the last commit on the repo's default branch plus all commits on my current (dev) branch -- e.g. the commits listed by `git log main..HEAD`

**Comment by mateosss** [comment]
You can disable it with the setting `showHistoryGraph`.

This incoming/outgoing clutters the view quite a bit and it is not straightforward to disable. I see its usefulness and how some workflows might benefit from having it at hand as an alternative to the common `git lola` alias, but I am not sure what's the reasoning behind making it always-visible by default for everyone.

**Comment by darshanhurix** [comment]
![image](https://github.com/user-attachments/assets/73df9c30-fd3f-446e-8f4f-c1d44570efe0)
This helped me get rid of it in VS Code

**Comment by yashnarkhedkar** [comment]
Go to your vs code settings and search for `show history graph` and uncheck that option.
![image](https://github.com/user-attachments/assets/5f88d089-0f08-466a-aa48-7e20d8c585cd)


> ![image](https://private-user-images.githubusercontent.com/91274943/355174583-73df9c30-fd3f-446e-8f4f-c1d44570efe0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTk1NzUsIm5iZiI6MTcyMjkxOTI3NSwicGF0aCI6Ii85MTI3NDk0My8zNTUxNzQ1ODMtNzNkZjljMzAtZmQzZi00NDZlLThmNGYtYzFkNDQ1NzBlZmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA0NDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MmJhMmFlYzg3OTFmNzJiZmVlZWIyMzUzZTZlMDAzNGZmNTUwY2YxNTA1MzI1YjJmYjE1YjYyODE1OThkZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YOH0CDnfdPZioYseV4-v8oRjdRT2YQGrr0tl5pMzigo) This helped me get rid of it in VS Code

**Comment by raceybe** [comment]
> Yeah, I used `"scm.showHistoryGraph": false` in User Preferences JSON

this... previous instructions point to .vscode/settings.json, but CTRL+SHIFT+P then User (or workspace) settings is where it needs to go. Thank you!

**Comment by MikeRich88** [comment]
Why was this turned on??? (I hate auto updates)

This really freaked me out, I thought everything had screwed up and that I had 100s of uncommitted changes for some reason.

(I am a git noob more or less)

**Comment by philBrown** [comment]
@MikeRich88 

> I am a git noob more or less

Git veteran here and I thought the same

**Comment by KuryKat** [comment]
For anyone that didn't see in the prior comments...

## How to hide incoming/outgoing in the Source Control view:

Add this to your ``settings.json`` file:
```json
"scm.showHistoryGraph": false
```
<details>
  <summary>Why are you commenting this again?</summary>
  </br>
  Some people have a tendency of skipping over comments that don't have code blocks or giant titles...
</details>

**Comment by lszomoru** [comment]
The history graph has been moved into its own view - Source Control Graph. The change is available in the latest VS Code Insiders release and will be included in the upcoming VS Code Stable release. Please give it a try and let us know what you think. Thank you!

**Comment by brunoparga** [comment]
@lszomoru I personally don't like this change, it's a bit obtrusive and distracts me from what I use the source control panel for: my changed files. I mean, the change itself is okay if people use it, I just turn it off and all is fine :)
