### ISSUE TITLE
"Go To Definiton" doesn't work.  Instead it runs "Find All References"

### ISSUE THREAD

**Issue by nuncio-bitis** [microsoft/vscode#224587]
I've been using VSCode for C++ projects for a few years. Over the past year the "Go To Definition" (F12 on Windows and Linux) literally ends up running "Find All References". Why does this happen? This is literally not the same thing. There's no way to jump to symbol definitions anymore. Everything always ends up showing the "Find All References" results window.
I've tried deleting the .vscode directory in the projects, but that doesn't help.
I've also tried uninstalling VS Code and reinstalling (Windows and Linux), but that doesn't work either.
It seems a year or so ago the functionality got broken.

Steps to reproduce:
- Open a folder that contains a C/C++ project.
- Open a source file that contains references to another source file
- Click on a symbol and either type F12 or open the context menu (right-click) and select "Go to Definition"

Expected behavior: the editor opens the file and positions the cursor on the definition of the symbol
Observed behavior: A references subwindow opens up showing all references in the directory tree.

**Comment by nuncio-bitis** [comment]
Update: The same happens when using the "Go to Declaration", "Go to Type Definition",  and "References"  menu items.

**Comment by jrieken** [comment]
Likely caused by extension and should be handled by them first. Tho, when already on a definition, go-to-def runs find references. This can be configured via `editor.gotoLocation.alternativeDefinitionCommand` et al
