### ISSUE TITLE
Requires multiple tries to log into GitHub in VS Code instance with fresh user directory

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#224502]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.92.0-insider (user setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T20:34:16.103Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.25987
- OS Version: Windows 11 Insiders

Steps to Reproduce:

1. Launch VS Code Insiders with fresh user data and extensions directories: `code-insiders --user-data-dir SOME_PATH --extensions-dir SOME_PATH`
2. Attempt to sign into GitHub (in my case, I'm trying to sign into the GitHub Copilot pre-release extension)
3. Complete sign in process in the browser 
4. Prompted to return to VS Code:
![Image](https://github.com/user-attachments/assets/a185d493-35e8-4c39-8df5-c294c510f9cf)
5. ❔ When I select `Open`, a new VS Code Insiders window is opened (rather than my current active session with fresh directories)
6. ❔ If I refocus on the fresh directory Insiders window, it doesn't register I've signed in:
![Image](https://github.com/user-attachments/assets/19f36c00-9458-465d-b854-3c91f4b4b0c2)
7. I can sign in successfully if I `Cancel` the above toast and instead use the alternative local server method:
![Image](https://github.com/user-attachments/assets/0cb14c6e-cee1-417a-8d54-b6a3cb98d6d5)

This is probably a unique enough scenario that not many folks would run into, but figured I'd file it in case there's anything different we'd want to do / can detect if a user is in a fresh directory instance of VS Code.

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/172340#issuecomment-1438769349

@joaomoreno says this isn't supported.
