### ISSUE TITLE
Port forwarding not working anymore since update (remote dev)

### ISSUE THREAD

**Issue by JulienLrx** [microsoft/vscode#224577]
Type: <b>Bug</b>

1. Launch a bokeh server or any other process that open a local port
2. port isn't automatically fowarded anymore.
3. Browser window/tab isn't launched either.

I've tried changing the port forwarding setting to hybrid, output and process mode with no luck.
Fowarding the port manually then going to localhost:port still work.
Downgrading to previous version resolve the issue.

Please advise.

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.0-113-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Ultra 7 165U (14 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.46GB (4.30GB free)|
|Process Argv|--crash-reporter-id 249cd9b6-0040-4578-8b86-ddef15c09be1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container|
|OS|Linux x64 5.15.0-113-generic|
|CPUs|Intel(R) Xeon(R) Gold 5315Y CPU @ 3.20GHz (8 x 0)|
|Memory (System)|125.79GB (67.43GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
debugpy|ms-|2024.10.0
python|ms-|2024.12.1
vscode-pylance|ms-|2024.7.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
ccplt:31103426
pythonrstrctxt:31103193
wkspc-onlycs-t:31106322
wkspc-ranged-c:31107834

```

</details>

**Comment by alexr00** [comment]
Which remote extension are you using? SSH? Dev containers?

**Comment by JulienLrx** [comment]
Sorry for the late reply.
I'm using dev containers. In fact I have about 40 users using remote container dev and we are all experiencing this issue with v1.92.0

**Comment by JulienLrx** [comment]
Issue is still happening with latest version.
Switching to process mode, and deactivating the auto forward ports fallback resolve the issue. Openpreview/browser doesn't work automatically anymore though.

Problem seems to be with the ouput mode from what i see.
Thanks

**Comment by alexr00** [comment]
@JulienLrx can you share an example of the output that is printed when you execute the program that starts your server?

**Comment by JulienLrx** [comment]
sure here it is :
`Launching server at http://localhost:38181`

But your question made me try something :
Problem seems to be related to notebook output, if i export the script as a python script output is correctly detected and portfowarding is working correctly.

Hope that helps.

**Comment by alexr00** [comment]
> But your question mades me try something as we mainly use jupyter notebooks : if i export the notebook as a python script and execute it, output is correctly detected and portforwarding is then working correctly.

Thanks @JulienLrx that does explain it. Detecting ports in the output of notebooks isn't something we support.

**Comment by JulienLrx** [comment]
Ok noted thanks for the answers.

But something has changed with hybrid mode at least. Before (and going back to june release does the same things) It uses to work (auto forward the port + open the browser windows automatically) and now we have to force process mode and set to 0 auto forward ports fallback and even then we have to open browser manually.

**Comment by alexr00** [comment]
I don't think anything relevant in the [url finder](https://github.com/microsoft/vscode/blob/alexr00/future-barracuda/src/vs/workbench/contrib/remote/browser/urlFinder.ts) has changed in years. Launching the browser isn't default behavior when a port is discovered. Maybe the configuration of your project changed:
- you could have had a devcontainer.json file that caused the port to be forwarded, rather than waiting for auto port detection to find it
- the devcontainer.json could also set the port attributes such that the browser is launched when the port is detected
- you could have had `remote.portsAttributes` or `remote.otherPortsAttributes` in your settings to cause the browser to be launched
