### ISSUE TITLE
Source control panel not respecting setting

### ISSUE THREAD

**Issue by ToyWalrus** [microsoft/vscode#224506]
Type: <b>Bug</b>

1. Be in a git-enabled folder so that source control is available
2. Set the setting SCM: Show Incoming Changes and SCM: Show Outgoing Changes both to "never"
3. Open the source control panel
4. The incoming and outgoing changes are still visible in the panel

This only happened after the latest VS code update (July '24), before that the settings were working as expected and I wasn't seeing the incoming/outgoing changes list.

VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.97GB free)|
|Process Argv|--crash-reporter-id ac9cccfe-7cdc-4b09-9173-80e03b67eb11|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
cognitive-complexity-show|amp|0.0.5
gitstash|art|5.2.0
vscode-tailwindcss|bra|0.12.5
npm-intellisense|chr|1.4.5
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.3
prettier-vscode|esb|10.4.0
copilot|Git|1.219.0
copilot-chat|Git|0.18.1
todo-tree|Gru|0.0.226
vscode-drawio|hed|1.6.6
svg|joc|1.5.4
rainbow-csv|mec|3.12.0
material-icon-theme|PKi|5.8.0
vscode-thunder-client|ran|2.24.13
vscode-yaml|red|1.15.0
synthwave-vscode|Rob|0.1.15
everforest|sai|0.3.0
sonarlint-vscode|Son|4.7.0
material-theme|zhu|3.17.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
ccpltc:31103427
pythonrstrctxtcf:31103194
wkspc-onlycs-t:31106322

```

</details>

**Comment by ToyWalrus** [comment]
Seems to be a duplicate of https://github.com/microsoft/vscode/issues/223832

**Comment by gjsjohnmurray** [comment]
Assuming it's the new history graph you're seeing, then yes it's a duplicate.

You can turn off the new graph by setting `"scm.showHistoryGraph": false`, after which the other settings will take effect.

/duplicate
