### ISSUE TITLE
Do we send unnecessary requests to Marketplace on VS Code update

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#224559]
Marketplace team has noticed a high load on some Wednesdays and Thursdays. I am speculating that this is due to our VS Code Stable release. Might you send some queries on VS Code version update to the Marketplace? Maybe we need to check for each extension if there is a newer version that satisfies the `engines` property? Can you double check is there something we can do to optimize these calls?

Or is these simply that these updates trigger a VS Code Restart - and on startup we send queries to the MP. 

Assigning to August since this is potentially affecting the scalability of the Marketplace.

**Comment by joelverhagen** [comment]
I was able to correlate the past 6 releases (June 5 - August 1, 1.90.0 - 1.92.0) with high load in VS Marketplace. There are particular ~1 hour periods where it appears that hitting the query extensions endpoint in a higher volume -- roughly 2x to 3x high than before and after the spike.

The times match with the release dates visible on https://github.com/microsoft/vscode/releases.

**Comment by sandy081** [comment]
Acknowledged through our telemetry that VS Code is sending 2-3 times more number of requests during 2 hours after a new version of VS Code is released.

**Comment by sandy081** [comment]
Here is what's happening:

When VS Code releases an update, all those users with VS Code open and being online receives the update. This triggers extensions update check which internally sends a request or two per window to the Marketplace. Since all online users are checking for extension updates at the same time, this is adding load on the Marketplace.

**Comment by sandy081** [comment]
I believe there are no changes we can do here as the requests we are sending are required for checking updates on the client. From my analysis on the data I collected, we are sending 50% of additional queries (which include all versions) for getting the stable version of an extension. Right solution here is to get the stable version of an extension without additional query.
