### ISSUE TITLE
Option to disable or customize status bar color when folder is not opened

### ISSUE THREAD

**Issue by wojcraft** [microsoft/vscode#224546]
Dear VSCode Contributors,

I found out this purple status bar color is distracting me a lot and I want a settings option, maybe in `workspace.colorCustomizations`, where I can change this color to my theme's default or just disable it to be the same as in situation when folder is opened. I didn't found a duplicate of this (probably), so here I am. Let me know what you think!

All the best,
Wojcraft

![image](https://github.com/user-attachments/assets/40d1210c-9d43-4e8c-964b-ec7792e3d05b)

**Comment by bpasero** [comment]
You can use `statusBar.noFolderBackground`.
