### ISSUE TITLE
Trying to unselect an option or change the profile to be copied will unselect all "what to configure" boxes

### ISSUE THREAD

**Issue by carloscardoso05** [microsoft/vscode#224592]
Type: <b>Bug</b>

Go to "create new profile" and try to unselect any box of "what to configure" or choose another profile to copy from and all the boxes will be unselected and you cannot selecte them anymore.

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600G with Radeon Graphics (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.37GB (9.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
refactort:31108082
ccpltc:31103427
pythonrstrctxt:31103193
wkspc-onlycs-c:31106320

```

</details>

![image](https://github.com/user-attachments/assets/c0d306b7-b042-43f8-9cdb-d5f0a462d907)

![image](https://github.com/user-attachments/assets/d2128bd0-94a7-499d-b88b-d8a2c662669b)

**Comment by carloscardoso05** [comment]
Just installed the previous version (1.91) and the bug was gone.

![image](https://github.com/user-attachments/assets/d37c4083-6086-4075-ba74-8d40e4fdda2d)

**Comment by gjsjohnmurray** [comment]
If you are willing to upgrade to 1.92 again you might like to try the upcoming new profile management experience by setting this:

```
"workbench.experimental.enableNewProfilesUI": true
```

**Comment by carloscardoso05** [comment]
Just installed the previous version (1.19.1) and the bug was gone.

![image](https://github.com/user-attachments/assets/c1a263be-7bf5-4ed6-a2e4-757058419085)

**Comment by LaurentOngaro** [comment]
duplicate of https://github.com/microsoft/vscode/issues/224392
