### ISSUE TITLE
Feature Request: Language support for Objective-C, Objective-C++ and Swift

### ISSUE THREAD

**Issue by AVRamachandran** [Microsoft/vscode#22452]
- VSCode Version: 1.10.2
- OS Version: macOS 10.11.6

Steps to Reproduce:

1. Go to a Swift file, Objective-C file or Objective-C++ file.
2. Go Menu -> Go to Symbol in File

Result:
No symbols in the file

Expect:
The languages that everyone builds Apps in for iOS and macOS to be supported.

This is a really cool editor, but the lack of native language support is a deal breaker.

**Comment by ramya-rao-a** [comment]
By design,

![image](https://cloud.githubusercontent.com/assets/16890566/23827712/7f03677c-066e-11e7-9c97-5adddbb836e7.png)

Please checkout the marketplace: https://marketplace.visualstudio.com/vscode for the right extension that can help you.
