### ISSUE TITLE
Source Control menu is not displaying correctly, and not showing the file changes.

### ISSUE THREAD

**Issue by zzxslp** [microsoft/vscode#224514]
Hi, I ran into a really strange bug when using vscode (possible due to the latest update?).
I use remote ssh to log into a linux server with Ubuntu 18.04.6 LTS. When I open the source control for repo X (which only has a single branch main), it shows "fine-tune" branch, which is a branch from sub-folder Y inside X. And I cannot see the file changes in the bar. 

I checked git branch and git log, everything is displayed correctly in the terminal. There is no issue for all other local repositories. 

<img width="730" alt="image" src="https://github.com/user-attachments/assets/2eddd95f-ba19-4de1-a788-dc94df8895e9">

VScode version information: 

> Version: 1.92.0 (Universal)
> Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
> Date: 2024-07-31T23:26:45.634Z
> Electron: 30.1.2
> ElectronBuildId: 9870757
> Chromium: 124.0.6367.243
> Node.js: 20.14.0
> V8: 12.4.254.20-electron.0
> OS: Darwin arm64 23.5.0

I am using vscode for a few months on the same type of server and this is the first time to encounter this issue.

**Comment by zzxslp** [comment]
There is no issue when using another server with Ubuntu 22.04.3 LTS. Below is the correct screen I am expecting:

<img width="477" alt="image" src="https://github.com/user-attachments/assets/73c48ad4-75ce-4cb0-9966-d8713946709b">

**Comment by lszomoru** [comment]
@zzxslp please note the banner that is being shown in VS Code when connected to the server. Please click on the "Learn More" link and  install a version of the VS Code client that is compatible with the server that you are connecting to.

**Comment by zzxslp** [comment]
Hi @lszomoru , thanks for the reply! Are you suggesting downgrade my local VScode to an older version? 

A follow-up observation, I find if I rename the main folder on the server to a different name, the source control is displaying correctly, and changing it back will again cause the error in the first screen shot. Is there some cached vscode files in the server that lead to this problem?

**Comment by deepak1556** [comment]
Should be unrelated to the banner, it is shown when user has accepted connection to a legacy server. Couple of things to try,

* Share the remote logs and git extension logs
* Confirm if the issue is present when using `1.91.1` client
