### ISSUE TITLE
out/nls.keys.json is not built deterministically

### ISSUE THREAD

**Issue by brjsp** [microsoft/vscode#224551]
Does this issue occur when all extensions are disabled?: n/a

There are at least two reasons why reproducible builds are important which are important to Code repackagers such as GNU/Linux distros.
The _ideological_ reason is that the users can verify that the binaries we ship correspond to the source.
The _technical_ reason is that some buildsystems do automatic rebuilds on build-dependency change, and indeterministic builds result in the annoyance of frequent spurious updates pushed to end users.

You can read more at https://reproducible-builds.org/

This issue seems to have been introduced with commit f6f90e016301f288ac5b36936d15ff8af9d70923.
Previous versions (1.91.x and below) instead had a `nls.metadata.json` file which was also non-reproducible, but at least could be fixed after build with `jq -cjS .`

- VS Code Version: 1.92.0
- OS Version: openSUSE Tumbleweed

Steps to Reproduce:

1. Build Code OSS (`yarn gulp vscode-linux-x64-min && yarn gulp vscode-linux-x64-prepare-rpm`)
2. Clean up the artifacts
3. Build Code OSS again
4. Compare the file `out/nls.keys.json`

**Comment by bpasero** [comment]
We noticed and ran into issues ourselves, a fix has been pushed to `main` and thus our insiders release.

/duplicate https://github.com/microsoft/vscode/issues/224385

**Comment by brjsp** [comment]
I confirm that backporting a0a41c07fb8f0921eb262f2e030b3206b83943a4 (and associated changes to vendored node_modules) fixes this problem.
