### ISSUE TITLE
cant select a database

### ISSUE THREAD

**Issue by TiMya03** [microsoft/vscode#224533]
ADD ISSUE DESCRIPTION HERE

Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Or if you are using VS Code in a browser as part of an online course please contact your course support channel.
