### ISSUE TITLE
Running `nodemon` with express and Supabase code terminal process not stopped at restart/close

### ISSUE THREAD

**Issue by JorensM** [microsoft/vscode#224594]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.0
- OS Version: Windows 10

Following up on this issue: https://github.com/microsoft/vscode/issues/87321

Steps to Reproduce:

1. Create a node project and install `express` and `@supabase/supabase-js`
2. Create a `.ts`/`.js` file that creates a server and instantiates a Supabase client. Example code:
   ```
     import express from "express";
     import { createClient } from "@supabase/supabase-js";

     const app = express();
     const supabase = createClient(supabaseUrl, supabaseKey); // You'll need a Supabase project for this

    const port = 4000;
    app.listen(port, () => {
	console.log(`Server running on port ${port}`);
    });
   ```
3. Run the file using `nodemon` in a VSCode terminal
4. Close and reopen VSCode
5. Run the file again
6. See 'Address already in use' error because the process was not stopped when VSCode was closed.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is problem still reproducible if you disable terminal session persistence?
You can try different values of `terminal.integrated.persistentSessionReviveProcess`
