### ISSUE TITLE
MIGRATE TO RUST

### ISSUE THREAD

**Issue by anshumalivfx** [microsoft/vscode#224508]
I propose we consider migrating our beloved VSCode to Rust. The current VSCode is not as optimized as the new code editor built with Rust. Could we migrate the existing codebase to a framework like Tauri? We could start a new branch for this project and work on it until it reaches a better state.

![png-transparent-rust-programming-language-logo-machine-learning-haskell-crab-animals-cartoon-crab](https://github.com/user-attachments/assets/96164cee-0838-4b90-9ec6-64d70ae7955c)

**Comment by thecaralice** [comment]
please stop making rust community look bad
