### ISSUE TITLE
Unable to Open Unicode File Containing XML

### ISSUE THREAD

**Issue by bullines** [Microsoft/vscode#22455]
[hmmm.txt](https://github.com/Microsoft/vscode/files/836049/hmmm.txt)

I'm unable to open files like the attached Unicode file and get the following error:

"The file will not be displayed in the editor because it is either binary, very large or uses an unsupported text encoding."

If the file is saved as UTF-8 in a different editor, it is then able to be opened by VSCode.

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.7|
|xml|DotJoshJohnson|1.7.0|
|csharp|ms-vscode|1.7.0|
|vscode-docker|PeterJausovec|0.0.12|
|theme-obsidian|rprouse|0.2.0|;

---

Steps to Reproduce:

1. Open the attached hmmm.txt file in VSCode.
2. Observe error message.

**Comment by bpasero** [comment]
If the file is using UTF-16 LE or BE you are required to add a BOM to it, otherwise we think the file is binary because it contains 0-bytes.
