### ISSUE TITLE
Can't create new profile copying from a template

### ISSUE THREAD

**Issue by ansaganie** [microsoft/vscode#224566]
Type: <b>Bug</b>

Create new Profile -> Copy form -> Choose any template
after this it is not posssible to configuration from default profile and any further actions are not possible
![image](https://github.com/user-attachments/assets/8a9cda63-3a2e-49a2-96e6-6115fd3cbaa2)

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (8.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.5
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.3
prettier-vscode|esb|10.4.0
copilot|Git|1.219.0
copilot-chat|Git|0.18.1
material-icon-theme|PKi|5.8.0
win-ca|uko|3.5.1
volar|Vue|2.0.28

</details>

**Comment by gjsjohnmurray** [comment]
If you don't check at least one of the checkboxes, what is your profile going to store?

**Comment by mod3x** [comment]
> If you don't check at least one of the checkboxes, what is your profile going to store?

Hello, I've encountered the same problem. It is not possible to check a single checkbox when a profile to copy from is selected. Even after switching from some profile to copy and then back to none, the checkboxes remain unselectable. Thank you.

**Comment by ansaganie** [comment]
> If you don't check at least one of the checkboxes, what is your profile going to store?

sorry, forgot to mention it, yaa it is not possible to chosoe any of confirmation below

it is still possible create from scratch, but not as a copy from an existing profile

**Comment by ansaganie** [comment]
>

**Comment by RiseT** [comment]
Problem occurs on Linux (Mint) as well (and of course on my Windos machine).  This used to work with the previous VS Code version.

**Comment by aol-nnov** [comment]
Just stumbled upon this bug on MacOS!

```
Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 23.3.0
```

**Comment by andy1li** [comment]
I encountered the same issue. When copying profiles, nothing cannot be checked.

**Comment by Dromantor** [comment]
The title really should be "Can't create a new profile at all." Creating from scratch doesn't work either. Just the export-import workaround works.

![profileerr](https://github.com/user-attachments/assets/72862e94-7bb0-4460-9a01-3d4799ae815c)

**Comment by gjsjohnmurray** [comment]
Pinging @sandy081

**Comment by aol-nnov** [comment]
Just a friendly ping, that recent update

```
Version: 1.92.1
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 23.3.0
```

... does not fix this annoying issue... :(

**Comment by gjsjohnmurray** [comment]
You can avoid the issue by setting `"workbench.experimental.enableNewProfilesUI": true`

@sandy081 with that setting `false` this issue reproduces in the latest Insiders too.

**Comment by aol-nnov** [comment]
Thank you for the hint, @gjsjohnmurray !

**Comment by ansaganie** [comment]
> You can avoid the issue by setting `"workbench.experimental.enableNewProfilesUI": true`
> 
> @sandy081 with that setting `false` this issue reproduces in the latest Insiders too.

works for me, too. Thank you!

**Comment by mwheatfill** [comment]
@gjsjohnmurray thanks for the tip. I like the new Profiles UI as well.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/224788

Please use the [New Profiles UI](https://github.com/microsoft/vscode/issues/224788#issuecomment-2274305778) as the workaround.
