### ISSUE TITLE
Security Policy to enable Insecure Content for entire Workspace in Markdown Preview

### ISSUE THREAD

**Issue by indiaalphanovember** [microsoft/vscode#224588]
Hi, would it be possible to include a setting in settings.json to allow insecure content in the entire workspace? I am currently working with a lot of markdown files with screenshots as attachments. In Markdown Preview, these screenshots are disabled by default and I need to click the "allow insecure content for each markdown file" that is being edited. I need to repeat this process for every new markdown file that's being created. Since these files are all in the same workspace, if there is a blanket security policy that disables the prompt, it would be very helpful.

**Comment by mjbvz** [comment]
How are you opening the files? Do you have a workspace folder open?

The security settings should already be per-workspace folder but you'll have to do it per resource for loose files
