### ISSUE TITLE
Searching all and refactoring variables finding everything

### ISSUE THREAD

**Issue by nistre** [microsoft/vscode#224580]
Type: <b>Bug</b>

When trying to Search (Ctrl+Shift+F) I am only getting limited results that exist with my Explorer view, perhaps only the files currently open or recently opened are found.  A similar issue occurs when  refactoring where only a limited number of variable references in other files get refactored.  I should note I am using VS Code in a monolithic repo, so if it is a matter of the size, it would be nice for the Search/Refactoring to give an inidication it is loading to find/rename all the instances.

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12850HX (24 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.69GB (13.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
project-manager|ale|12.8.0
swagger-viewer|Arj|3.1.2
npm-intellisense|chr|1.4.5
gitignore|cod|0.9.0
vscode-eslint|dba|3.0.10
dendron|den|0.124.0
dendron-markdown-shortcuts|den|0.12.1
dendron-paste-image|den|1.1.1
githistory|don|0.6.20
gitlens|eam|15.2.3
EditorConfig|Edi|0.16.4
vscode-jest-runner|fir|0.4.73
todo-tree|Gru|0.0.226
vscode-drawio|hed|1.6.6
vscode-peacock|joh|4.2.2
openapi-lint|mer|1.2.0
git-graph|mhu|1.30.0
tabscolor|mon|0.2.4
vscode-docker|ms-|1.29.1
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.1
vscode-edge-devtools|ms-|2.1.5
remote-containers|ms-|0.380.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vsliveshare|ms-|1.0.5936
angular-console|nrw|18.25.0
material-icon-theme|PKi|5.8.0
vscode-yaml|red|1.15.0
code-spell-checker|str|3.0.1
vscode-conventional-commits|viv|1.25.0
vscode-icons|vsc|12.8.0

</details>

**Comment by andreamah** [comment]
Also, is it finished loading when it only shows limited files? Is it still showing the loading animation?

**Comment by nistre** [comment]
The button is not toggled on.  I do see (guessing I just didn't see it before) a loading icon on the Status Bar.  Is that the loading animation you are referring to?

**Comment by andreamah** [comment]
Yes. It seems that the search is taking a long time on your project.  Have you considered adding some paths to the `search.excludes` setting to make the search more optimized? I would assume that, since you're in a mono-repo, it's searching through many files, which may take a long time.

**Comment by nistre** [comment]
Gotcha, I'll refine the excludes the next time I need to refactor/search.  I guess I didn't see the loading icon in the Status Bar to know it was still loading.  v/r
