### ISSUE TITLE
Feature Request: Easily view installed extension dependencies

### ISSUE THREAD

**Issue by pmeyerson** [microsoft/vscode#224595]
I would like to understand what code dependencies installed by the extensions I use.  I need this information to understand if I am running an extension that has a known vulnerability or performing actions I consider risky, so I can make the decision if I need to disable the extension or not.  Right now  it is very cumbersome to compile this information myself.  

As a starting point, it would be very helpful for me to see a listing of:

extension-name, version xxx date xxx
  npm
      package version
      package version
  pypi 
      package version
      package version

or something similar.

It would also be useful to separate out the list between run time and dev dependencies, where the extension makes this information known.

Thanks for considering.

**Comment by pmeyerson** [comment]
The most helpful output would be text file(s) that I could then open to examine if need be.
If they are formatted like package manager lock files that would allow them to be easily scanned by existing security tools, cicd, etc.

Does that answer your question completely or do you need more detail from me?

**Comment by isidorn** [comment]
Yes, that helps. Thank you
