### ISSUE TITLE
terminal problem

### ISSUE THREAD

**Issue by MukeshRajput2005** [microsoft/vscode#224578]
Type: <b>Feature Request</b>

my problem is when i run the terminal its shows exception every time after the vscode update

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal
