### ISSUE TITLE
TestMessage display incorrectly when it's a markdown string in 1.92.0

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#224575]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.92.0 (Universal)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

Steps to Reproduce:

1. Using this snippet in the test-provider-sample project
```
const markdownString = new vscode.MarkdownString();
markdownString.isTrusted = true;
markdownString.supportHtml = true;
markdownString.appendText("foo");
markdownString.appendMarkdown("<br/>");
markdownString.appendText("bar");
const message = new vscode.TestMessage(markdownString);
message.location = new vscode.Location(item.uri!, item.range!);
options.failed(item, message, duration);
```
2. After running the test, both the editor peek view and test result view do not render correctly.

![image](https://github.com/user-attachments/assets/adf17432-96cd-4763-80e2-902ea2f00f28)

**Comment by connor4312** [comment]
Sorry, this got lost in the shuffle of the call stack UI :(

**Comment by connor4312** [comment]
Verification steps:

1. Check out the `connor4312/verify-224575` of vscode-extension-samples https://github.com/microsoft/vscode-extension-samples
2. Go into `test-provider-sample` and F5
3. Run the "easy math" test. Open the error messages for all the tests that fail and verify they're all visible

**Comment by Mati882023** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No
> 
> Version: 1.92.0 (Universal) Commit: [b1c0a14](https://github.com/microsoft/vscode/commit/b1c0a14de1414fcdaa400695b4db1c0799bc3124) Date: 2024-07-31T23:26:45.634Z Electron: 30.1.2 ElectronBuildId: 9870757 Chromium: 124.0.6367.243 Node.js: 20.14.0 V8: 12.4.254.20-electron.0 OS: Darwin arm64 23.5.0
> 
> Steps to Reproduce:
> 
> 1. Using this snippet in the test-provider-sample project
> 
> ```
> const markdownString = new vscode.MarkdownString();
> markdownString.isTrusted = true;
> markdownString.supportHtml = true;
> markdownString.appendText("foo");
> markdownString.appendMarkdown("<br/>");
> markdownString.appendText("bar");
> const message = new vscode.TestMessage(markdownString);
> message.location = new vscode.Location(item.uri!, item.range!);
> options.failed(item, message, duration);
> ```
> 
> 2. After running the test, both the editor peek view and test result view do not render correctly.
> 
> ![image](https://private-user-images.githubusercontent.com/6193897/354582553-adf17432-96cd-4763-80e2-902ea2f00f28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NTg5NjgsIm5iZiI6MTcyMzY1ODY2OCwicGF0aCI6Ii82MTkzODk3LzM1NDU4MjU1My1hZGYxNzQzMi05NmNkLTQ3NjMtODBlMi05MDJlYTJmMDBmMjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTRUMTgwNDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWEzZWQzOTk1ZTkxMmZjN2Q4OTE0MjNkZjZmZTRmOWNiNTNmMTQ0NTE2Yzc2YjQ1NTA2MzA1Zjg2MjNmODgwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aseeTaj4ihlfeHKx6TJtOk_NV4OyfSTI3ug_F-TMbGY)
