### ISSUE TITLE
Discrepancy between Markdown rendering of auto-links (GitHub, Marketplace, VS Code)

### ISSUE THREAD

**Issue by igorskyflyer** [microsoft/vscode#224644]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.0
- OS Version: Windows 11, 10.0.22621.3958

Both VS Code and GitHub use a GitHub-flavored Markdown engine and auto-create jumpable/anchor links in both VS Code and GitHub (using the HTML `id` attribute) when using headings. If there are non-supported characters they are replaced with a hyphen `-` (and lower-cased but not relevant here), e.g.:

`🤖 Features` -> `#-features`

which works fine, in both GitHub and VS Code ([example repository](https://github.com/igorskyflyer/vscode-git-home)) but fails on the Marketplace, which as mentioned in the [official documentation](https://code.visualstudio.com/api/references/extension-manifest#fields) [see `markdown` field] uses the same GitHub-flavored Markdown but the links stop working ([example extension](https://marketplace.visualstudio.com/items?itemName=igordvlpr.git-home)) because it does **NOT** replace the non-supported characters with a hyphen `-`, it strips them completely, rendering jumpable links broken on the Marketplace.  

<br>

Upon inspection of the extension's page, we can clearly see that the `id` does not comply with the GitHub-flavored anchor links rendering.

<div align="center">
	<img src="https://github.com/user-attachments/assets/d5491812-5de5-48cb-b041-1f9e97574400" alt="Marketplace source code">
	<p>Marketplace HTML source code</p>
</div>

<br>

Steps to Reproduce:

1. Go to this [GitHub repository](https://github.com/igorskyflyer/vscode-git-home)
2. Click on any link in the Table of Contents
3. The browser will jump to the correct section
4. Go to this [VS Code extension page](https://marketplace.visualstudio.com/items?itemName=igordvlpr.git-home)
5. Click on any link in the Table of Contents
6. The browser will **NOT** jump to the correct section

<br>

> Note: posted here because I am not sure which one of the mentioned does not comply with the auto-links format and because it affects VS Code extensions, i.e. links don't work in README of an extension page in VS Code, they only work in edit mode.

**Comment by mjbvz** [comment]
@isidorn I believe this is a marketplace issue. I've tried to align our markdown link support with GitHub but it seems like the marketplace may be doing something different. Here's a code pointer on what we do:

https://github.com/microsoft/vscode/blob/99d597285badc1c4086bbe55a9c615058dc9664e/extensions/markdown-language-features/src/slugify.ts#L21

I am looking to adopt this code instead this iteration:

https://github.com/microsoft/vscode-markdown-languageservice/blob/3b59c4c81ef1c92a5cb41074216a822b10b1e02c/src/slugify.ts#L51

**Comment by igorskyflyer** [comment]
Thanks for both of your responses.

Since the issue is not going to be fixed anytime soon, can somebody point the differences between the two values of the `markdown` field in the extension manifest (= `package.json`).

<br>

The value of `github` is the default one and I am currently using that one (which renders the non-functional links), would setting it to the other value, `standard`, fix the issue or the other Markdown-flavor just changes the rendering of certain elements?

<br>

The differences are not documented on the [official documentation](https://code.visualstudio.com/api/references/extension-manifest).
