### ISSUE TITLE
38 issues found from just loadin git

### ISSUE THREAD

**Issue by rismay** [microsoft/vscode#224656]
Type: <b>Bug</b>

Open VSCode. Git version 2.46

VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|10, 4, 4|
|Memory (System)|24.00GB (2.21GB free)|
|Process Argv|--crash-reporter-id e61c4447-ca73-4c51-9191-32e920d36e9f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
graphicaldebugging-vscode|Ada|0.8.0
codesnap|adp|1.3.4
terminal-commands|adr|1.0.5
vscode-sqlite|ale|0.14.1
vscode-openapi-viewer|And|1.1.2
jsoncrack-vscode|Ayk|2.0.3
markdown-checkbox|bie|0.4.0
vscode-markdownlint|Dav|0.55.0
filetree|dee|0.0.1
gpt-commit|Dmy|1.0.5
char-count-per-line|Dog|0.0.6
indent-rainbow-blocks|Gab|0.0.3
raythis|Goo|1.1.1
todo-tree|Gru|0.0.226
mayukaithemevsc|Gul|3.2.4
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-power-mode|hoo|3.0.2
snipped|jef|1.3.0
vscode-todo-highlight|jgc|2.0.8
vscode-rufo|jnb|0.0.5
commit-lint|kol|0.0.9
call-graph|Luo|1.2.1
syntax-project-pbxproj|mar|0.1.3
rainbow-csv|mec|3.12.0
highlight-on-copy|mgu|1.1.4
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
azure-repos|ms-|0.38.0
cpptools|ms-|1.21.5
cpptools-extension-pack|ms-|1.3.0
remote-repositories|ms-|0.40.0
vscode-paste-image|mus|1.0.4
resourcemonitor|mut|1.0.7
deepdark-material|Nim|3.3.1
vscode-ios-common-files|Ort|1.0.5
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|5.8.0
quicktype|qui|23.0.170
sqlite-viewer|qwt|0.5.11
geo-data-viewer|Ran|2.6.0
vscode-sort-json|ric|1.20.0
clangformat|sea|2.0.2
trailing-spaces|sha|0.4.1
markdown-preview-enhanced|shd|0.8.13
swift-lang|ssw|1.10.6
xcode-keybindings|ste|1.9.0
code-spell-checker|str|3.0.1
markdown-links|tch|0.8.0
file-size-explorer|tri|0.0.2
vscode-counter|uct|3.4.0
vscode-lldb|vad|1.10.0
code-viz-stat|viz|0.1.4
vscode-apple-swift-format|vkn|1.4.3
vscode-jumpy|wma|0.3.1
size|yur|0.3.1
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.6.2

(11 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
ccplti:31103428
pythonrstrctxtcf:31103194
wkspc-onlycs-t:31106322

```

</details>

**Comment by gjsjohnmurray** [comment]
Please explain what you mean by "38 issues found".
