### ISSUE TITLE
VSCode Code Tunnel Won't Load Due to CORS Policy

### ISSUE THREAD

**Issue by dave9123** [microsoft/vscode#224665]
- VS Code Version: code 1.92.0 (commit b1c0a14de1414fcdaa400695b4db1c0799bc3124)
- OS Version: Debian GNU/Linux 12 (bookworm)

Steps to Reproduce:

1. Run <code>code tunnel</code>
2. Open the tunnel on your browser
3. Fatal error shows up due to CORS Policy

![image](https://github.com/user-attachments/assets/f1c43741-25d1-4f6e-bd26-4e5943207b12)
![image](https://github.com/user-attachments/assets/96066435-3b44-4551-a843-1c430cb788e5)

**Comment by connor4312** [comment]
I don't reproduce this. Are you running any proxies on your system?

**Comment by dave9123** [comment]
I don't, also I don't have port forwarding enabled if that helps
________________________________
