### ISSUE TITLE
format html disorder

### ISSUE THREAD

**Issue by wgx1116** [Microsoft/vscode#22468]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: none
---

html mixed with php

Steps to Reproduce:

1. select multi line
2. format selection and result is disorder.

**Comment by ramya-rao-a** [comment]
Can you share a screenshot?

**Comment by aeschli** [comment]
Also please attach the HTML code example that show the problem.

**Comment by aeschli** [comment]
Closing as information is missing.
