### ISSUE TITLE
"Unable to validate." form GitHub

### ISSUE THREAD

**Issue by MetaBlue2000** [microsoft/vscode#224630]
- VS Code Version: 1.92.0
- OS Version:  Windows11 23H2

Hi,
When I want to validate and to push my modifications on my private project, I receive the error "Unable to validate". I reloaded VSCode, but no change.

https://github.com/user-attachments/assets/5fa2ed26-b3a2-4f85-83db-5e982bf1df53

Thx

**Comment by lszomoru** [comment]
Are you able to reproduce this with multiple repositories? 
If it is specific to one repository, do you have a git commit hook configured?

**Comment by MetaBlue2000** [comment]
It's only with this repo, and I don't have a hook configued. And I can't init a hook, because it's a remote workspace (without CMD).
