### ISSUE TITLE
Apply enable-proposed-api Changes in argv.json with Window Reload

### ISSUE THREAD

**Issue by mohankumarelec** [microsoft/vscode#224695]
**Description**:
Enable changes to the `enable-proposed-api` field in `argv.json` to take effect by reloading the VS Code window instead of requiring a full restart.

**Proposed Solution**:
Implement a mechanism to apply the `enable-proposed-api` changes with a window reload.

**Benefits**:
1. **Improved Workflow**: Enhances productivity by reducing downtime.
2. **Ease of Use**: Simplifies toggling the proposed API for developers.
3. **Consistency**: Aligns with other dynamic configuration changes in VS Code.

**Use Case**:
Facilitates efficient testing and development for those relying on the proposed API.

**Comment by jrieken** [comment]
> Facilitates efficient testing and development for those relying on the proposed API.

I don't understand the motivation because when running out of development this isn't needed at all, proposed API are just enabled.
