### ISSUE TITLE
vscode.dev outage for non-USA traffic?

### ISSUE THREAD

**Issue by venkatamutyala** [microsoft/vscode#224620]
looks like tunnels through vscode.dev are not working for my team in Ukraine or India. It works fine from the USA though

**Comment by venkatamutyala** [comment]
USA appears to be having issues as well.

**Comment by venkatamutyala** [comment]
Screenshot with possible error on code cli server: 
<img width="1182" alt="image" src="https://github.com/user-attachments/assets/9f9dfbcc-94f3-4783-bd10-6918ba1e9038">

**Comment by venkatamutyala** [comment]
I opened a bug report here for what I believe is the underlying cause: https://github.com/microsoft/vscode/issues/224650

**Comment by connor4312** [comment]
Please update to VS Code 1.92 for the fix
