### ISSUE TITLE
[UX] Install extension for workspace only

### ISSUE THREAD

**Issue by flash-me** [microsoft/vscode#224634]
_(Looked for existing issues and could not find anything, which surprises me. I can't be the only one annoyed by this)_

As of today, Extensions are always installed "globally", there is no other option:
<img width="443" alt="image" src="https://github.com/user-attachments/assets/6e14aaad-7fd1-4100-b2ab-608efbad53b7">

If I want to install an Extension only for the workspace I am currently working on, I have to 
- install it "globally"
- disable it "globally"
- enable it for the workspace 

I am pretty sure there are ways to improve the UX for this :)

cheers
flash ⚡

**Comment by gjsjohnmurray** [comment]
#85735  was a previous well-supported but unsuccessful attempt to get this.

**Comment by flash-me** [comment]
So the argument was/is to cover this use case with profiles.

Which then also means, that there is an expectation for workspaces that fit to a profile also have always the same extensions?

In my mental model, profiles were on a more abstract position above the workspace specific settings and hence more generic.

I'd need to give it some thought. Maybe I just had different assumptions.
