### ISSUE TITLE
Disaplay error

### ISSUE THREAD

**Issue by PeterRock** [microsoft/vscode#224664]
Type: <b>Bug</b>

Cannot disaplay english character after update the latest version

VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin x64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 7, 4|
|Memory (System)|16.00GB (3.03GB free)|
|Process Argv|--crash-reporter-id a192af4b-d356-4fa8-b121-b3474374be76|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
icons-carbon|ant|0.2.6
npm-intellisense|chr|1.4.5
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.2.3
prettier-vscode|esb|10.4.0
circom|ide|0.0.2
npm|ide|1.7.4
vscode-pnpm|Jac|0.0.3
react-taro-snippets|liu|0.0.4
i18n-ally|lok|2.12.0
xml-format|mik|1.1.3
autotrim|Nat|1.0.6
nutui-vscode-extension|nut|1.0.2
vscode-yaml|red|1.15.0
xml-toolkit|SAP|1.1.0
autoimport|ste|1.5.4
code-spell-checker|str|3.0.1
sass-indented|syl|1.8.30
ayu|tea|1.0.5
catppuccin-perfect-icons|tha|0.21.32
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-icons|vsc|12.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
ccpltc:31103427
pythonrstrctxtcf:31103194

```

</details>

**Comment by PeterRock** [comment]
<img width="907" alt="截屏2024-08-03 10 20 18" src="https://github.com/user-attachments/assets/148ca68a-223b-4182-9f19-e52a28d6aaba">

**Comment by PeterRock** [comment]
<img width="649" alt="截屏2024-08-03 10 35 41" src="https://github.com/user-attachments/assets/1f2ff0bc-a7f4-41ae-9629-8d07ad733870">
1.91 is ok！

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you using custom fonts? Does problem go away if you reset font family setting?

**Comment by PeterRock** [comment]
> /needsMoreInfo
> 
> Are you using custom fonts? Does problem go away if you reset font family setting?
> 
> May be duplicate of #224115

I don't think so.

You can see the screenshot, some is ok some is weird. such as "SideBar", "Menu", "Terminal", "Code line number"

**Comment by IllusionMH** [comment]
Workbench doesn't use custom font, so it won't be affected.

From screenshot it looks like only bold in terminal is not affected but other are.
Have you tried to run with `--disable-blink-features="FontMatchingCTMigration"` as mentioned in linked issue?

**Comment by PeterRock** [comment]
No, terminal is crashed too. It not work even  after reset all configurations.Rollback to last version of vscode is work right.I give up the new version!发自我的手机-------- 原始邮件 --------发件人： Andrii Dieiev ***@***.***>日期： 2024年8月5日周一 00:21收件人： microsoft/vscode ***@***.***>抄送： Peter ***@***.***>, Author ***@***.***>主    题： Re: [microsoft/vscode] Disaplay error (Issue #224664)
Workbench doesn't use custom font, so it won't be affected.
From screenshot it looks like only bold in terminal is not affected but other are.
Have you tried to run with --disable-blink-features="FontMatchingCTMigration" as mentioned in linked issue?

**Comment by PeterRock** [comment]
1.92.1 bug fixed!
