### ISSUE TITLE
Source Control - repo Incoming/Outgoing changes SLOW

### ISSUE THREAD

**Issue by classicrocker883** [microsoft/vscode#224675]
Does this issue occur when all extensions are disabled?: Yes/No
YES

- VS Code Version: 1.92.0
- OS Version: Windows_NT x64 10.0.22631
- Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
- Date: 2024-07-31T23:26:45.634Z

Steps to Reproduce:

1. Open VS Code, start a workspace - Clone/Open any Github repo (preferably with long list of commits)
2. Nav to Source Control
3. Observe how SLOW it is at loading all the Incoming/Outgoing commits
  basically any changes you make for staging is also slow, because it is loading literally every single commit from years back, this may take a while before it updates and is usable to stage and commit.

This is because up the resent update which implements this change.

It would be nice for a way to disable or limit any/all Incoming/Outgoing to prevent this from becoming so slow it hangs up.

edit: I found it is called SCM: Show History Graph in settings.  
however, sometimes this is helpful, but it would be nice if we can set a limit to prevent it loading every single one.

**Comment by gjsjohnmurray** [comment]
/duplicate

Another open issue (maybe more than one) is asking for a limit.
