### ISSUE TITLE
backspace not working in vs code 

### ISSUE THREAD

**Issue by Sandip-dhebe** [microsoft/vscode#224678]
Type: <b>Feature Request</b>

Backspace is not working in code 

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by gjsjohnmurray** [comment]
/confirmPlease

As well as the advice the next comment from the bot will give, maybe also look at https://github.com/microsoft/vscode/wiki/Keybinding-Issues
