### ISSUE TITLE
Build failed: extension host with pid 5416 exited with code: 0, signal: unknown.

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#224653]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=286401
Changes: https://github.com/Microsoft/vscode/compare/fcca275...79ab35e

**Comment by deepak1556** [comment]
Not actionable due to lack of crash dumps in the attached run, haven't seen similar reports since this issue. Closing for now.
