### ISSUE TITLE
SpEL syntax

### ISSUE THREAD

**Issue by manuelhz** [microsoft/vscode#224684]
Type: <b>Bug</b>

According to the Spring official documentation #https://spring.io/blog/2014/07/15/spel-support-in-spring-data-jpa-query-definitions
the following data jpa query is correct, and I know it is because I have deployed the application:
```
@Query("select p from Post p where p.postId > ?#{[0]} order by p.postId asc limit 1")
    Optional<Post> findPreviousById(Long postId);
```
the red warning is :
_SPEL: extraneous input '[' expecting {'++', '+', '--', '-', '(', '#', '@', '^[', '![', '!', '&', '?[', '$[', LCURLY, 'true', 'false', 'new', 'null', 'T', IDENTIFIER, NUMERIC_LITERAL, STRING_LITERAL}vscode-spring-boot(JAVA_SPEL_EXPRESSION_SYNTAX)_

basically it doesn't like this sintax: ?#{[0]}, however it wasn't giving eny problems maybe a month or two ago. It might have been a vscode update.

I am running Java 21 and Spring boot 3 on XUbuntu 22.04 LTS 

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Linux x64 6.5.0-44-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|4, 3, 1|
|Memory (System)|15.53GB (11.59GB free)|
|Process Argv|--no-sandbox .|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-select|chu|2.0.2
vscode-docker|ms-|1.29.1
vscode-kubernetes-tools|ms-|1.3.16
remote-containers|ms-|0.380.0
fabric8-analytics|red|0.9.5
java|red|1.33.0
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.56.0
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.28.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-spring-boot-dashboard|vsc|0.14.0
vscode-spring-initializr|vsc|0.11.2

</details>

**Comment by IllusionMH** [comment]
/causedByExtension

In error message you should see which extension provided that error.
