### ISSUE TITLE
Don't update disabled extensions

### ISSUE THREAD

**Issue by xavdid** [Microsoft/vscode#22461]
There seems to be a functional difference installed extensions disabled on a workspace level (they show up in settings). In the case of an extension disabled through the UI, I don't need it kept up-to-date until it's re-enableld through the UI. 

As of now, when an extension is disabled it still gets counted in the sidebar number for "extensions waiting to update". If I've disabled an extension, it would be nice if it's out of sight, out of mind.

- VSCode Version: `Version 1.10.2 (1.10.2)`
- OS Version: macOS `10.12.2`

Steps to Reproduce:

1. Install any extension
2. Hit `Disable` in the extensions panel
3. Wait for extension to update
4. Extension is shown as both disabled, and needing an update. There's a blue number shown in the sidebar for a disabled extension.

**Comment by ParkourKarthik** [comment]
I'd like to make a PR for this :)

**Comment by ParkourKarthik** [comment]
From my understanding, the below are to be done:

- The disabled extensions should be hidden by default in the extension sidebar.
- Any extension search except '@disabled' (such as '@outdated') should not show the disabled extensions.
- `Check for Updates` and `Update all Extensions` should not consider the disabled extensions.

@ramya-rao-a Let me know your view.

**Comment by ramya-rao-a** [comment]
> The disabled extensions should be hidden by default in the extension sidebar.

No. The default view of the extensions viewlet already has a "disabled" section, and that will continue to show the disabled extensions. Same goes for when user types @disabled

> Any extension search except '@disabled' (such as '@outdated') should not show the disabled extensions

No. Only '@outdated' should not show disabled extensions

> Check for Updates and Update all Extensions should not consider the disabled extensions.

Yes.

Additionally, the label `Update to ...` on the extension should not appear if the extension is disabled.

> Currently, the debugger instance (Launch VS Code) doesn't show any extensions from the marketplace

Did it work before when you were working on the other PR on outdated extensions?

**Comment by ParkourKarthik** [comment]
>Did it work before when you were working on the other PR on outdated extensions?

No it was not working. I managed to test it alernatively but not very much related to realtime!

**Comment by ramya-rao-a** [comment]
Ah! In that case, never mind. To display extensions when running VS Code from source, we need the gallery service url which is considered proprietary and legally we cannot share that. It can only be shipped as part of the product. 

Sorry for misleading you into taking this up.
