### ISSUE TITLE
Problem with class tag in vs code 

### ISSUE THREAD

**Issue by hacker539** [microsoft/vscode#224677]
Does this issue occur when all extensions are disabled?: Yes/No
yes

- VS Code Version: 1.92.0
- OS Version: 

Steps to Reproduce:

1. Have problem in the class tag of Html in vscode 
2. when i try to add class tag through emment it will not show as in the video below and when put using dot shortcut it will not work without div tag and it can't be used manually
[test.html - My docs - Visual Studio Code 2024-08-03 15-12-12.zip](https://github.com/user-attachments/files/16478991/test.html.-.My.docs.-.Visual.Studio.Code.2024-08-03.15-12-12.zip)

**Comment by hacker539** [comment]
![Recording 2024-08-03 at 15 37 42](https://github.com/user-attachments/assets/9ea43570-93a3-42d1-a46f-08cd59a01a20)
This is the problem video for it
This shows the class tag is not shown int emmet and when try using dot shortcut it will not work without div tag and can't be used manually

**Comment by IllusionMH** [comment]
What is expected behavior?

In the video I don't see any issues.
You need to use `.cls` to get tag with a class on it. `div` is default unless you put other tag name before dot.

Syntax highlight shows text white if you remove tag name.
