### ISSUE TITLE
Can't control click terminal links with brackets or parentheses 

### ISSUE THREAD

**Issue by quick007** [microsoft/vscode#224667]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: 1.92.0
- OS Version: Windows 11

Steps to Reproduce:

1. Have something like `app/(main)/dashboard/[id]/layout.tsx` in your terminal
2. `ctrl` + click the file path and see issue.

**Comment by lionel-rowe** [comment]
Partial workaround: remove `()[]` from `terminal.integrated.wordSeparators` setting (but make sure to keep the space at the beginning).

That gives you ctrl-click, but you still don't get automatic underline/click-on-hover.
