### ISSUE TITLE
Opening a project folder

### ISSUE THREAD

**Issue by deppenkaiser** [microsoft/vscode#224672]
Type: <b>Bug</b>

I have a folder, where three sub projects are included. This three apps works together as Client and Server. I must debug both at the same time. So i try to open my super project folder in two different VS Code sessions, in order to start and debug a client and a server.

This well known and often used technic is now not possible. The VS Code IDE does not open the same folder a second time. Why this?

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Linux x64 6.8.0-39-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz (20 x 4700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|31.26GB (28.64GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 59d43caf-ddc4-4775-afbc-6b71f590015d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.17.2
vscode-pull-request-github|Git|0.92.0
git-graph|mhu|1.30.0
vscode-language-pack-de|MS-|1.92.2024073109
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.9.10
pdf|tom|1.2.2
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
ccpltc:31103427
pythonrstrctxt:31103193
hdi1a554:31097393

```

</details>

**Comment by IllusionMH** [comment]
AFAIK you can run 2 debug sessions in one window.

Also there should be separate command to duplicate workspace in other window

**Comment by deppenkaiser** [comment]
Yes, this is possible. But it is not a good solution, because you have two debug-instances and only one debug-tool. There are many reasons why this is sub optimal. In the past (good old times) where always two tools for two debug-instances. Debugging can cause problems in the debugger, and you have two (or more) different datasets with only one viewer (debugger). There are also problems with timeouts. A breakpoint can disturb timeout Situations.

**Comment by deppenkaiser** [comment]
I use Linux streaming (GStreamer with Cameras), the data stream will broke if u set a breakpoint.

**Comment by deppenkaiser** [comment]
break (brake, broke, broken) :-)

**Comment by deppenkaiser** [comment]
I think both should be possible, this would be the best way.

**Comment by roblourens** [comment]
You can 

- Run multiple debug sessions in one window. I do this often, it works well for me. But if you don't like that you can:
- Open subfolders for your sub projects
- Use a workspace to open the same folder in multiple windows: https://code.visualstudio.com/docs/editor/multi-root-workspaces
