### ISSUE TITLE
a11y help menu for debug view shows when focused in terminal/notebook

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#224638]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 
noticed while fixing https://github.com/microsoft/vscode/issues/223331

Steps to Reproduce:

1. open the debug sidebar
2. focus the terminal and press alt+f1 to open a11y help for the terminal

:bug: debug a11y view is shown

**Comment by meganrogge** [comment]
Also occurs when in the editor
