### ISSUE TITLE
SCM: Keyboard activated context menu (shift-f10) action disappeared

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#22467]
The new source control module SCM has lost the Keypord context menu currently present
with the GIT part.

steps to reproduce:

- show SCM 
- select any file (with mouse or keyboard)
- press shift-f10
- no pop-up context menu

- right mouse click - pop-up context menu appears

Tested in Insiders 3-11-17

**Comment by cleidigh** [comment]
@joaomoreno 
I can see that the new SCM uses the list widget as opposed to tree - but you know that
since you did a bunch of the code ;-)

I have been trying to determine how to at the context menu keyboard listener all morning
but I don't understand enough of the code structure yet.

if I follow the tree example I would add a key down handler in the list widget
and make the context handler in SCMviewlet handle key and mouse events

I'm still hoping to fix it myself but I also think you guys may have changed
some architecture approaches with the new list widget and I may not
as an equivalent current design pattern.

**Comment by joaomoreno** [comment]
Fix was a bit trickier than expected. 👍  Thanks for the pointer.

**Comment by cleidigh** [comment]
cool
keyboard context works now
question- I was surprised you added the support in the mousecontroller, was that just expedient
since all other keyboard was handled as default handlers?

in testing found another issue - focused file does not reveal clean and stage icons
as when selected with mouse.  I can try and take a crack at the focus issue
assuming I get my debugger back working...
