### ISSUE TITLE
Debugger not showing breakpoint highlight

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#22466]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.6.1|
|Go|lukehoban|0.6.55|
|debugger-for-chrome|msjsdiag|2.6.0|
|vetur|octref|0.5.1|
|java|redhat|0.0.11|
|vscode-icons|robertohuertasm|7.3.0|
|language-stylus|sysoev|1.6.0|
|vim|vscodevim|0.6.3|;

---

Steps to Reproduce:

1. For this project: https://github.com/octref/vscode-electron-debug/tree/master/electron-quick-start

2. Add two lines here to debug:

![image](https://cloud.githubusercontent.com/assets/4033249/23828665/2a1d21f6-06a7-11e7-8ff9-36d5fb63a22c.png)

Debugger is stopping on the breakpoints, but nothing is being shown.
I'm positive this is a regression. Previously it worked fine.

@weinand

**Comment by weinand** [comment]
dup of https://github.com/Microsoft/vscode/issues/22466

**Comment by octref** [comment]
Dup of itself?

**Comment by weinand** [comment]
@octref sorry, I've fixed the link.
