### ISSUE TITLE
Hide Incoming/Outgoing graph

### ISSUE THREAD

**Issue by smk291** [microsoft/vscode#224606]
I'd like to be able to hide the Incoming/Outgoing graph. It's an awful lot of visual noise, which I'd prefer to minimize. If there's an option to hide the graph, I haven't found it:
<img width="373" alt="image" src="https://github.com/user-attachments/assets/b5d0f2d1-07d8-4f0e-9814-d7f1c42a91fa">

**Comment by gjsjohnmurray** [comment]
`"scm.showHistoryGraph": false`

It's mentioned in the release notes.

**Comment by Julian88Tex** [comment]
Did this default on for everyone? I'm wondering so I can tell our team how to turn it off.

**Comment by Julian88Tex** [comment]
Looks like quite a few people are annoyed by it: https://github.com/microsoft/vscode/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+incoming

**Comment by gjsjohnmurray** [comment]
> Did this default on for everyone? I'm wondering so I can plan to tell our team how to turn it off.

Yes.

**Comment by RyanKadri** [comment]
I think the main issue is just in the UX. The graph itself is nice -- It should probably just be in a collapsible section and potentially closed by default. It's a bit awkward with Workspaces especially since it kind of takes over the whole source control sidebar. Maybe it should just be default collapsed there if nothing else?

**Comment by Julian88Tex** [comment]
@RyanKadri Ah yeah I like that idea.

**Comment by dushmanta05** [comment]
I just came to see if someone has posted this. In big projects, this looks so cluttered; an option for hiding these would be nice.

**Comment by gjsjohnmurray** [comment]
@harsh-wal there is. Please see https://github.com/microsoft/vscode/issues/224606#issuecomment-2265880245

**Comment by derb95** [comment]
This is an interesting addition, and I can see value in it, but I agree it needs to be collapsible.

**Comment by ntap-bmegan** [comment]
Agree with others. I like the feature but wish that it was collapsible or that the on/off was an option inside the panel rather than having to go into settings and find `scm.showHistoryGraph`. My first help ticket this morning was from a user wanting to disable it because it's "cluttered".

**Comment by larrylai1993** [comment]
My colleague experienced frequent vscode crashes when dealing with a large volume of incoming and outgoing data. After disabling this feature, the vscode works fine. Has anyone else encountered this issue?

**Comment by skupjoe** [comment]
I was just about to submit a feature request to **make the Incoming/Outgoing changes graph collapsable**.

It's a nice feature, I just wish you could collapse/expand it.

👍

**Comment by smk291** [comment]
Thank you, @gjsjohnmurray. Greater UI clarity and consistency would eliminate the issue for most users, I think. The screenshot below shows that the 'Explorer' view's menu is quite simple and straightforward. Users are able to check and uncheck UI features that they want or don't want to see. There are far more options when I open the options for the git view. There are also fewer view options; they're nested in a 'views' submenu; and there appears to be no option to hide the graph. Intuitively, I expected the two menus to look and work similarly, and I expected to be able to 'untick' the graph to hide it.

<img width="552" alt="image" src="https://github.com/user-attachments/assets/bbfd9d66-20dd-46e2-9ccd-e5c4beda2eeb">

**Comment by lszomoru** [comment]
This information has been moved into a dedicated view called Source Control Graph.
