### ISSUE TITLE
Issue no #221788

### ISSUE THREAD

**Issue by MandarSant** [microsoft/vscode#224666]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

please check issue no #221788  
no comment any yet

Steps to Reproduce:

1. 
2.

**Comment by gjsjohnmurray** [comment]
/duplicate

Please continue to communicate on the original issue, and only open a new one if the original gets locked.

**Comment by MandarSant** [comment]
> /duplicate
> 
> Please continue to communicate on the original issue, and only open a new one if the original gets locked.

No body was replying for to attract attention i created this duplicate
