### ISSUE TITLE
Integrated Terminal Blank

### ISSUE THREAD

**Issue by johnphan96** [microsoft/vscode#224625]
Type: <b>Bug</b>

1. On a Windows PC, use Remote Explorer to SSH into a Ubuntu 20.04.6 LTS running in Oracle VM VirtualBox
2. Open an Integrated Terminal in VSCode (CTRL + Shift + `)
3. The opened Terminal is blank

![image](https://github.com/user-attachments/assets/1eed6299-ab3e-47fc-b132-29aafdf7f6fb)

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.0-117-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (6.00GB free)|
|Process Argv|--crash-reporter-id 18bcfaea-679a-4d84-9443-1d0360925a5f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: localhost|
|OS|Linux x64 5.15.0-117-generic|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (6 x 0)|
|Memory (System)|22.47GB (18.24GB free)|
|VM|100%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|4.4.3
better-cpp-syntax|jef|1.27.1
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
ReactSnippets|xab|2.4.0
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|15.2.3
prettier-vscode|esb|10.4.0
vscode-jest-runner|fir|0.4.73
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.1
vscode-typescript-tslint-plugin|ms-|1.3.4
fabric8-analytics|red|0.9.5
java|red|1.33.0
vscode-xml|red|0.27.1
vs-code-prettier-eslint|rve|6.0.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.28.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
ccplt:31103426
pythonrstrctxtcf:31103194
wkspc-onlycs-c:31106320

```

</details>

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal
