### ISSUE TITLE
i don't want to use data wrangler

### ISSUE THREAD

**Issue by yangtian6781** [microsoft/vscode#224707]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:
**I don't want to use  data wrangler, when i click view data in data viewer, vscode requires me to install data wrangeler(a data viewer extension is required to view data frames. click yes to see recommended extensions), i only want to use data viewer of jupyter extensions because data wrangler extension don't support torch data, how can i solve it? **

**Comment by yangtian6781** [comment]
Version: 1.92.0 (user setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by rebornix** [comment]
@yangtian6781 thanks for providing your feedback. We deprecated the builtin data viewer due to its lack of functionalities and accessibility support.

> because data wrangler extension don't support torch data, how can i solve it

We can file a feature request to the Data Wrangler extension.
