### ISSUE TITLE
Selecting database is not working

### ISSUE THREAD

**Issue by tvhancock** [microsoft/vscode#224740]
I am trying to select a database before running my codes but none of the databases are coming up. The only message I am getting is "Loading..." and nothing loads. How can I resolve this issue so I can complete my school work?

Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
