### ISSUE TITLE
vscode preview the markdown format file 

### ISSUE THREAD

**Issue by iqianxing** [Microsoft/vscode#22479]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.15048
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.0|;

---

Steps to Reproduce:

1.run mocha test
> mocha > reporter/report.md

2.vscode open file"reporter/report.md"

3.vscode preview the markdown file , please see the fellowing pictrue

![markdown preview](https://cloud.githubusercontent.com/assets/2938263/23832809/a251cd72-0777-11e7-926d-08e0946f46d3.png)

`  #add()
    √ correctly adds 2 args
    √ correctly adds 3 args
    √ correctly adds 4 args

  #ajax
    √ http://www.qq.com (279ms)
    √ http://react.apptravel.cn/ (173ms)
    √ http://react.apptravel.cn/article/20 (125ms)
    √ https://www.baidu.com/ (70ms)
    √ http://www.126.com/ (43ms)
    √ https://segmentfault.com/a/1190000002748032 (433ms)

  #Array
    ##indexOf()
      √ should return -1 when the value is not present`

**Comment by ramya-rao-a** [comment]
Am sorry, but what is the issue here?
Are you expecting `√` to be treated as a bullet point?

**Comment by mjbvz** [comment]
Mocha output is not valid markdown. You need to use the markdown reporter for your tests
