### ISSUE TITLE
Graphic error

### ISSUE THREAD

**Issue by dgsimone15** [Microsoft/vscode#22474]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:
![cattura](https://cloud.githubusercontent.com/assets/25420667/23830625/8d18db2a-070f-11e7-9273-84bc85b9877a.PNG)

**Comment by isidorn** [comment]
Please provide reproducable steps so we can investigate into this on our side.
Do you see this all the time?
Do you see the rendering issue also if you restart vscode?

**Comment by dgsimone15** [comment]
I do not remember exactly how it happened :(. I remember that I had just closed the window settings and I quickly pressed on dubug, but I'm not sure. If it happens again I hope I can give you more information. I Take this opportunity to suggest the integration Visual Studio Team Foundation Server etc ... in "Version Control" (insider)

**Comment by isidorn** [comment]
Ok, if it happens again please try to find reproducable steps and post them here so we can investigate.
I am closing this issue until more details are provided.

As for the TFS version control there is already a feature request for this and I believe this is actually coming soon as in the next milestone we will open SCM to be a contributable viewlet.
