### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by madara-uchihaaa** [microsoft/vscode#224781]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.6.0-dev.20240803

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|8.00GB (0.47GB free)|
|Process Argv|--crash-reporter-id 2a8f4492-d16f-48b7-8c52-507af84b24d1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.1.2
vscode-django|bat|1.15.0
c-cpp-compile-run|dan|1.0.58
competitive-programming-helper|Div|2024.7.1722430096
githistory|don|0.6.20
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.2.3
prettier-vscode|esb|10.4.0
code-runner|for|0.12.2
vscode-mysql|for|0.5.0
copilot|Git|1.219.0
copilot-chat|Git|0.18.1
go|gol|0.42.0
ionic|Ion|1.90.0
better-cpp-syntax|jef|1.27.1
angular-essentials|joh|18.0.0
vsc-python-indent|Kev|1.18.0
git-graph|mhu|1.30.0
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
python|ms-|2024.12.1
vscode-pylance|ms-|2024.7.1
cpptools|ms-|1.21.5
cpptools-extension-pack|ms-|1.3.0
vscode-typescript-next|ms-|5.6.20240803
sqltools|mtx|0.28.3
sqltools-driver-mysql|mtx|0.6.3
material-icon-theme|PKi|5.8.0
vscode-thunder-client|ran|2.24.13
java|red|1.33.0
vscode-xml|red|0.27.1
vscode-angular-support|vis|0.1.4
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.56.0
vscode-java-debug|vsc|0.58.0
vscode-java-pack|vsc|0.28.0
vscode-lombok|vsc|1.1.1
vscode-spring-boot-dashboard|vsc|0.14.0
vscode-spring-initializr|vsc|0.11.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
ccpltc:31103427
pythonrstrctxtcf:31103194
1iic9185:31097392

```

</details>

**Comment by mjbvz** [comment]
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
