### ISSUE TITLE
Changes in my font

### ISSUE THREAD

**Issue by jayad23** [microsoft/vscode#224736]
Type: <b>Bug</b>

I use VS Code in a Mac Pro, and have installed and configured it to use Cascadia Code as my default font. However, in the last couple of times, every time VS Code updates, the user configuration breaks and I end up working with a font that is neither my selection nor comfortable to work with. The last time it fixed itself, don't know how, or why... but I am not ok knowing this will happen concurrently everytime VS Code updates.

VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|. --crash-reporter-id 2448c06d-6887-4962-98a7-62f2542b2534|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
iconify|ant|0.9.2
jsoncrack-vscode|Ayk|2.0.3
vscode-django|bat|1.15.0
vscode-tailwindcss|bra|0.12.5
simple-react-snippets|bur|1.2.8
emmet-jss|car|1.0.0
turbo-console-log|Cha|2.10.4
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
vitest-snippets|dei|1.8.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.2.3
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|10.4.0
font-switcher|eva|4.1.0
comment-anchors|Exo|1.10.4
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
copilot|Git|1.219.0
copilot-chat|Git|0.19.2024073102
vscode-github-actions|git|0.26.3
gobystrok|GoB|0.0.1
vscode-env|Iro|0.1.0
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
better-folding|Moh|0.5.1
vscode-docker|ms-|1.29.1
vscode-language-pack-es|MS-|1.92.2024073109
autopep8|ms-|2024.0.0
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.1
vscode-pylance|ms-|2024.7.1
powershell|ms-|2024.2.2
vsliveshare|ms-|1.0.5936
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|5.8.0
tsimporter|pmn|2.0.1
prisma|Pri|5.17.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
vs-code-prettier-eslint|rve|6.0.0
vscode-javascript-booster|sbu|14.0.1
js-jsx-snippets|sky|11.1.3
vscode-standard|sta|2.1.3
code-spell-checker|str|3.0.1
code-spell-checker-spanish|str|2.3.4
iconfont-preview|stx|0.0.5
vscode-styled-components|sty|1.7.8
vscode-stylelint|sty|1.4.0
sass-indented|syl|1.8.30
vscode-pets|ton|1.27.0
errorlens|use|3.20.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
pretty-ts-errors|Yoa|0.6.0
material-theme|zhu|3.17.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
ccplti:31103428
pythonrstrctxt:31103193

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/issues/224496
