### ISSUE TITLE
UNGITHUB VSCODE!!!!!

### ISSUE THREAD

**Issue by tripolskypetr** [microsoft/vscode#224735]
Code stucks when trying to open any cloned github repo on Ubuntu 22.04. The logs shows me what It trying to open modal window for GitHub auth and fails

![Screenshot from 2024-08-04 19-06-25](https://github.com/user-attachments/assets/fcf390ce-d413-4441-a013-1984f5e9f7ca)

**Comment by tripolskypetr** [comment]
No one can send you this feedback cause the log tab is unavailable in the ui. Also disabling GitHub in settings does nothing: this is hard coded shit feature which nobody need but has been merged to force telemetry

**Comment by tripolskypetr** [comment]
To reproduce, make clean installation of any ubuntu and try install vscode from snap. Downgrade vscode for previous release works, but right now I am going to switch to Zed cause I am tired of microsoft upgrades

**Comment by lszomoru** [comment]
Thank you very much for filing this issue. Based on the screenshot it looks like you are running VSCodium and not VS Code. If you are still able to reproduce this issue please file an issue in the VSCodium repository: https://github.com/VSCodium/vscodium/issues.

**Comment by tripolskypetr** [comment]
@lszomoru It's the same for VSCode and VSCodium both. I have checked It
