### ISSUE TITLE
feature request: XML support

### ISSUE THREAD

**Issue by Rysher** [Microsoft/vscode#22475]
I could not find any extension that formats xml with indentations or one that color-codes xml tags the same way vsCode color-codes javaScript for example....would be extremely useful if at least this rudimentary support for xml will be available.

**Comment by ramya-rao-a** [comment]
By default, there is color coding for xml files without any extensions

<img width="685" alt="screen shot 2017-03-12 at 11 38 38 am" src="https://cloud.githubusercontent.com/assets/16890566/23834739/a4c18840-0718-11e7-8323-701d77a9cbb4.png">

@aeschli Any reason we don't support xml formatting just like we do html?

**Comment by Rysher** [comment]
in the attached screen capture theres an xml file, raw and unformatted that is not being color-coded.
maybe the color coding failed because it is unformatted?

anyway, the file is indeed being identified as an xml file (notice my red marker at the bottom of the capture).
![capture](https://cloud.githubusercontent.com/assets/16275140/23835313/c26aa7aa-076d-11e7-8d04-d76335287726.PNG)

**Comment by aeschli** [comment]
@Rysher @ramya-rao-a 
We don't have an XML formatter implementation ready to use and we have limited resources to implement and maintain one. We'd like the community to jump in. I see that there are some extensions out there. It would be great if you can try these and also give feed back an enhancement suggestions to the extension writers.

On the second issue. For performance reasons there is a maximum line length (10k) where we decide to no colorize the line.

**Comment by Rysher** [comment]
The 10K character limit for color-coding is reasonable and understandable.

But I've tried 4 extensions that claim they have formatting abilities, none worked. and their maintainers don't seem to respond very quickly or coherently to submitted issues. (if they even respond at all and still maintain their extensions).
Since XML is not an esoteric markup language, is there a chance you'd reconsider redirecting some resources to provide a built-in formatting ability?

**Comment by softineer** [comment]
Could you reconsider the line length?  I work with large XML files (250k or more line length) and what's odd is that when I open the file, the color-coding is not there, but when I re-save the file, the color-coding appears.

**Comment by aeschli** [comment]
@softineer Please file separate, new issues for the line length suggestion as well as the re-save strangeness you see. Thanks a lot!
