### ISSUE TITLE
Instruction breakpoint cannot be canceled by clicking on the sidebar

### ISSUE THREAD

**Issue by yuan92111246** [microsoft/vscode#224779]
Does this issue occur when all extensions are disabled?: Yes/No(Debugging cannot cancel all extensions)

- VS Code Version: 1.92.0
- OS Version: win10

Steps to Reproduce:

1. Click Debug C/C++ File to start debugging
![image](https://github.com/user-attachments/assets/7e55d1e2-ecd9-449c-9f1d-813c811e2b9d)
2. Open disassembly view after stopping
3. Set a breakpoint, execute continue
4. Click the sidebar to cancel the breakpoint. Breakpoints cannot be canceled.
![image](https://github.com/user-attachments/assets/c79daca6-805b-4dab-8382-87d7bc3254f9)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/129571
