### ISSUE TITLE
Terminal suggest: `git checkout .` doesn't show `.` as a completion

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#224745]
Repro:

1. macOS/pwsh
2. Suggest enabled
3. Type `git checkout .`, 🐛 suggestions show, but `.` is not one of them

<img width="870" alt="Screenshot 2024-08-04 at 9 37 12 AM" src="https://github.com/user-attachments/assets/cdaeab80-debe-4f95-bacc-34f037c0e3be">

**Comment by meganrogge** [comment]
https://github.com/user-attachments/assets/73e53840-22d3-461a-8526-7a668e3cd5bf

**Comment by Tyriar** [comment]
@meganrogge that's https://github.com/microsoft/vscode/issues/226186, for this issue type the `.` and wait a bit for the response. It's a shame that this can happen right now, but you could speed things up a lot by clearing out stale branches and/or re-cloning the vscode repo.
