### ISSUE TITLE
Custom title: right-click menu no longer works in the empty space

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#224784]
Bisecting points to https://github.com/microsoft/vscode/compare/b23e791eb5afbd95f05aa24da7693ce89344a079...8703a11164db333db471576d38ddc143d6ad7ead which would indicate it could be the Electron 30 update.

**Steps:**
- right click left or right of the command center
- notice how the context menu does not appear

Here is what you should be seeing:

![Image](https://github.com/user-attachments/assets/54b46aee-bfb3-446c-809c-9609d4b13500)

**Comment by benibenj** [comment]
Has this been fixed? I'm not reproducing on windows

**Comment by bpasero** [comment]
I can still reproduce with latest insiders.

**Comment by benibenj** [comment]
Can be reproduced on Linux

**Comment by bpasero** [comment]
I think this is https://github.com/electron/electron/issues/37789
