### ISSUE TITLE
Go to File with current text selection as search query

### ISSUE THREAD

**Issue by snoobvn** [Microsoft/vscode#22473]
- VSCode Version: 1.10
- OS Version: Windows 10

Expect Feature:
`import Hello from '/components/Hello'`
select **`Hello`**
Press Ctrl + P ( Go to File )
Have Hello as default search query

**Comment by mjbvz** [comment]
This is not TS/JS specific. Adding @bpasero since this relates to quick open

@snoobvn As a side note, you can use `go to definition` on the import file path in JS and TS files to quickly open the target file

**Comment by snoobvn** [comment]
Thanks for the reply, but for some file without js/ts extension (vue), go to definition won't work

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
