### ISSUE TITLE
Here is no way to hide the git tree in SCM panel

### ISSUE THREAD

**Issue by guoyunhe** [microsoft/vscode#224768]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.0
- OS Version: 

Steps to Reproduce:

1. Switch to a new branch and do a lot of commits
2. Open SCM panel in VS Code

The UI is messed with git history tree. And it is not clearly separated with staged files.

![image](https://github.com/user-attachments/assets/87e295bf-7828-48fe-a312-e9958e4416d4)

**Comment by susanne99** [comment]
This function drives me crazy - completely unnecessary. Who needs this view all the time?! no one !

**Comment by gjsjohnmurray** [comment]
Please use the release notes information at https://code.visualstudio.com/updates/v1_92#_incomingoutgoing-changes-graph to turn off this new feature.

/duplicate

**Comment by Dooks123** [comment]
1. File > Preferences > Settings
2. Search `SCM Show History Graph`
3. Untick

**Comment by susanne99** [comment]
thank you very much !!!  

 
 

Gesendet: Montag, 05. August 2024 um 14:34 Uhr
Von: "Pierre Duvenage" ***@***.***>
An: "microsoft/vscode" ***@***.***>
Cc: "susanne99" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [microsoft/vscode] Here is no way to hide the git tree in SCM panel (Issue #224768)


 


	File > Preferences > Settings
	Search SCM Show History Graph
	Untick

**Comment by fzs1994** [comment]
> 1. File > Preferences > Settings
> 2. Search `SCM Show History Graph`
> 3. Untick

Thanks a lot! It was slowing down my whole system!!
