### ISSUE TITLE
update explorer inline treeview when moving selection on current editor

### ISSUE THREAD

**Issue by cognominal** [microsoft/vscode#224705]
The RFE is relevant only when the current editor contains a file content which format is supported by the language
service: markdown, typescript... So that an inline treeview is displayed in the explorer sidebar.

When selecting an item in the explorer sidebar treeview, the corresponding code in the current editor is selected, and,
possibly, scrolling happens to make that selection visible.
The current RFE asks for things to go in the opposite direction. When the editor selection changes, the selection in the
inline treeview should change to reflect it.

This feature is missing from vscode-insider as of early august 2024.

I found this shortcoming when trying to solve a similar one on my (yet unpublished) [ts-AST-explorer](https://github.com/cognominal/ts-ast-explorer)  extension and filed a 
[bug](https://github.com/cognominal/ts-ast-explorer/issues/1) about it.

**Comment by gjsjohnmurray** [comment]
Are you able to fork vscode-extension-samples, then create a branch on your fork in which you modify the tree-view-sample to demonstrate your issue as simply as possible?

**Comment by alexr00** [comment]
This is a feature request to have the outline view follow the current selection in the editor?

**Comment by cognominal** [comment]
> This is a feature request to have the outline view follow the current selection in the editor?

Yes. I wish my english was good enough to express it in so few words. 
The json outline is very close to what I want to do with my AST-explorer, especially with that requested feature.

As suggested by [gjsjohnmurray](https://github.com/gjsjohnmurray) 
I will try to fork the treeview sample, not so much to reproduce my issue, but to start from a sane codebase. It will be even better if someone implement the requested feature

Thx for your feedback.

**Comment by alexr00** [comment]
I think showing us what you wanted with the tree view sample was to make sure we understood your request. Now that we understand it's not as important to do.

**Comment by jrieken** [comment]
You can do this

![Image](https://github.com/user-attachments/assets/8c6e5b6e-c203-4dd0-946e-423c51e8f471)
