### ISSUE TITLE
This wallpaper is Stuck

### ISSUE THREAD

**Issue by HaiderImtiaz-Github** [microsoft/vscode#224752]
Type: <b>Bug</b>

I install this extension: narutinho-wallpaper, right after installing, I uninstalled it, but the sticker is still there

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.84GB (6.34GB free)|
|Process Argv|C:\\Users\\HaiderImtiaz\\.vscode\\extensions\\thomaz.preparing-1.7.0\\themes\\Narutovisk-color-theme.json --crash-reporter-id 24c3cd51-5593-440d-b1cf-781f648bb508|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
generate-wt-scheme|bla|0.0.7
onlythemes|bui|1.1.0
gitignore|cod|0.9.0
vscode-terminal-themes|ctf|0.1.2
githistory|don|0.6.20
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
gitlens|eam|15.2.3
google-fonts-instant-import|Edw|0.0.5
font-switcher|eva|4.1.0
remotehub|Git|0.62.0
icon-fonts|idl|2.5.4
realtime-themes|Jux|0.0.8
google-search|kam|0.0.1
code-background|Kat|2.10.4
vsc-python-indent|Kev|1.18.0
vscode-pdf|mat|0.0.6
emoji-icons|mig|1.6.1
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.10.0
python|ms-|2024.12.1
vscode-pylance|ms-|2024.7.1
azure-repos|ms-|0.38.0
live-server|ms-|0.4.14
remote-repositories|ms-|0.40.0
autodocstring|njp|0.6.1
nrf-terminal|nor|2024.3.15
material-icon-theme|PKi|5.8.0
vscode-solidity-language|tin|0.0.7
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-icons|vsc|12.8.0
jinja|who|0.0.8
fontforge-vscode|xia|0.0.2

(24 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
ccplt:31103426
pythonrstrctxtcf:31103194
wkspc-ranged-t:31107835

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe that extension modified some VS Code files.
I suggest you download VS Code again from code.visualstudio.com and reinstall it.

**Comment by meganrogge** [comment]
Pls create an issue for the extension, closing as not actionable.
