### ISSUE TITLE
DDoS attack 

### ISSUE THREAD

**Issue by Flaconel** [microsoft/vscode#224755]
my serrverull leaves ddos ​​statck and I don't know how to stop it stop the server

**Comment by Flaconel** [comment]
I'm really sorry, I didn't mean for this to happen, so it closes after all?
Or you have nothing to help me with?

lun., 5 aug. 2024, 02:02 vs-code-engineering[bot] ***@***.***>
a scris:

**Comment by IllusionMH** [comment]
This is issue tracker for VS Code editor itself, not sure how your issue relates to it.

If you have problem with some servers - other media would be better place to ask specific questions (also you should provide more details about problem there, as currently it's not clear what happens)

**Comment by Flaconel** [comment]
I'm a beginner you know, by mistake I did that attack on a random site, to
see what I learned by myself and I didn't stop it with alt+c but I only
pressed once the attack didn't stop

lun., 5 aug. 2024, 02:14 Andrii Dieiev ***@***.***> a scris:

**Comment by Flaconel** [comment]
And after I got out of there I just forgot it there that the attack was
still running but it seemed to me that it had stopped

lun., 5 aug. 2024, 02:21 Sveduneac Flavius ***@***.***> a
scris:

**Comment by Flaconel** [comment]
Please shut down my server please

lun., 5 aug. 2024, 02:23 Sveduneac Flavius ***@***.***> a
scris:
