### ISSUE TITLE
[html] SCRIPT closing tag does not get aligned correctly

### ISSUE THREAD

**Issue by johnyradio** [Microsoft/vscode#2247]
if i manually enter both `<html>` and `</html>` the closing html tag gets correctly indent-aligned with the opening tag automatically. But if i do the same with `<script>` and `</script>`, the closing tag does NOT get correctly auto-aligned. 

in html file-type
vscode version 0.10.6

thx

**Comment by aeschli** [comment]
The behavior for <script> is different as for content inside we switch to JavaScipt. The JavaScript engine doesn't (yet) know it I embedded.

**Comment by aeschli** [comment]
The indentation is corrected because </html> is a completion proposals that you select.
For </script> we don't have such a proposal. This is #12787
