### ISSUE TITLE
Typo on landing page https://code.visualstudio.com/

### ISSUE THREAD

**Issue by ankugargdev619** [microsoft/vscode#224729]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Navigate to landing page https://code.visualstudio.com/
2. Navigate to extensions section
3. Note that there is typo with GitLens section (it should be "Supercharge" instead)
![image](https://github.com/user-attachments/assets/ff13cfb4-424d-4ad1-af13-bc32c4cd4c6e)

**Comment by albertosantini** [comment]
@ntrogh Just to understand better how to fix this kind of issues: where is the fix (repo), because the page didn't change?

Thanks for your effort.

**Comment by ntrogh** [comment]
@albertosantini The website infrastructure is in a private repo and the website home page is part of that. Other docs content is hosted in the public [vscode-docs](https://github.com/microsoft/vscode-docs) repo.

**Comment by ankugargdev619** [comment]
@ntrogh <https://github.com/ntrogh>

It seems that the changes are not yet deployed, would you be able to tell
how often those changes are deployed.

**Comment by ntrogh** [comment]
@ankugargdev619  We should have the changes deployed later today.
