### ISSUE TITLE
Space and tabs being displayed as "f"s 

### ISSUE THREAD

**Issue by anonymousDog12** [microsoft/vscode#224723]
Does this issue occur when all extensions are disabled?: Yes

    VS Code Version: 1.92.0 (Universal)
    OS Version: macOS 11.4

Steps to Reproduce:

    Open a file in VSCode.
    Type any text including spaces.
    Notice that typing space results in an "f" character instead of a space.

Expected Result:
Typed characters should appear as expected, with spaces being inserted when the spacebar is pressed.

Actual Result:
Typing the spacebar inserts an "f" character instead of a space.

Additional Information:
I have tried disabling all extensions and the issue persists. Here is a screenshot of the issue:

![Screenshot 2024-08-04 at 1 07 42 AM](https://github.com/user-attachments/assets/fd1f34c8-3205-4e84-83a5-49a1cfbdfb8f)

If I open a new document and type space, it gives me a bunch of "f"s instead as well; tabs are shown as 4 "f"s:

![Screenshot 2024-08-04 at 1 07 58 AM](https://github.com/user-attachments/assets/1ae3a510-bee6-4fe2-a4db-ae94ea16b41c)

**Comment by IllusionMH** [comment]
Are you using custom font for editor? Is this problem reproducible if you reserve font family setting?

**Comment by RedCMD** [comment]
related? https://www.reddit.com/r/vscode/comments/1ehwtih/can_anybody_tell_me_what_has_happened_to_my/

if you copy paste the 'space' into https://apps.timwhitlock.info/unicode/inspect does it say its a 'normal' space character?

**Comment by anonymousDog12** [comment]
@IllusionMH @RedCMD 

I checked again last week, the issue is still there. However, I just checked again today (without doing anything else), seems like the issue is gone now. 

Closing this for now. Thank you for checking!
