### ISSUE TITLE
Opening Large Folder

### ISSUE THREAD

**Issue by alihejazi97** [microsoft/vscode#224753]
Type: <b>Bug</b>

I accidentally opened a folder in vscode explorer section with 3 million audio files in it. the vscode cpu usage was 100% and it was  unresponsive .

I think vscode should only load small amount of files. the issue is also repeated in version control. vs code tries to load 3 million files changes in its ui. I have to close vscode before moving folder with huge amount of files to git repos.

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 6.5.0-41-generic

**Comment by lramos15** [comment]
Are you able to reproduce this issue locally? I think this has to do with the remote connection
