### ISSUE TITLE
Override git global username & email in both User Settings & Workspace Settings

### ISSUE THREAD

**Issue by RohithKumbharkar** [Microsoft/vscode#22471]
> It's a feature request to override the username / email in commits made from VS Code. This could help people with more than one account (personal & work) to well manage the author in the commits.

## Problem:
People using work laptops are likely to have their global email configured to work email. They might use full blown Visual Studio IDE for work but VS Code for personal projects. But, when using VS Code for personal projects on the same machine commits always take the work email. There's currently no way to customize the username / email used in commits made from VS Code.

## Proposed Solution:
We can configure the username / email for a specific repository (Workspace Settings) or for entire VS Code (User Settings).

The configuration could be something like

```json
"git.username": "Rohith Kumbharkar",
"git.email": "rohithkumbharkar@users.noreply.github.com"
```

The order of preference would be

1. Workspace settings
2. User settings
3. git globals

Before making a commit, VS Code will look for **git.username** & **git.email** in Workspace then User settings.

If the values are not found in both Workspace & User settings then it reverts back to default behavior of fetching from git global config.

**Comment by CoenraadS** [comment]
Why don't you just override it using git?

`git config user.name "Rohith Kumbharkar"`  
`git config user.email "rohithkumbharkar@users.noreply.github.com"`

**Comment by joaomoreno** [comment]
[Git has local settings](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration). In every repository you can have settings in `.git/config`.

**Comment by RohithKumbharkar** [comment]
Hi @joaomoreno, yes I'm aware of the local settings but that'll be confined to a repository & this needs to be done for every repo individually but I'm talking about a setting at the editor (VS Code) level so that no matter what repository I work on if I work in VS Code I can configure it in user settings.

**Comment by joaomoreno** [comment]
Unfortunately, this doesn't sound like a common scenario. Maybe you could attempt creating an extension for this?

**Comment by RohithKumbharkar** [comment]
Yep, I thought this might go the extension way so I'm looking into making one

**Comment by RohithKumbharkar** [comment]
@joaomoreno I'm trying to build an extension but after looking at the VS Code documentation I didn't see an API for git in VS Code. Is there a possibility for an extension to integrate seamlessly with git in VS Code in such a way that it can override the command being executed by git ?

If there exists any API / Event that I should be looking into, could you point me in the right direction ?

**Comment by joaomoreno** [comment]
No, there isn't any. Your extension should call `git config user.name` when you open a workspace that has a git repository. That'll achieve the same behaviour that you want.

**Comment by ShyykoSerhiy** [comment]
@RohithKumbharkar, I've made an extension for this https://marketplace.visualstudio.com/items?itemName=shyykoserhiy.git-autoconfig , have a look.

**Comment by RohithKumbharkar** [comment]
@ShyykoSerhiy, yup thanks for the extension
