### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by Yagneshdxt** [Microsoft/vscode#22476]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.3|
|csharp|ms-vscode|1.7.0|
|mono-debug|ms-vscode|0.15.3|
|laravel-blade|onecentlin|1.8.1|;

---

Steps to Reproduce:

1. click on start debugging button on debugging tab. (I am debugging php file wiht felixfbecker.php-debug extension)
2. Debugger shows error Debug adapter process has terminated unexpectedly 
on my developer tool it shows error in workbench.main.js:103

My debugging was working fine before vscode update after vscode update it started showing this error.

**Comment by ramya-rao-a** [comment]
@Yagneshdxt Is this happening consistently? Can you share the error you see in the debug console and developer console if any?

cc @felixfbecker

**Comment by felixfbecker** [comment]
Feel free to move the issue, I need to see some stack trace from eg dev tools

**Comment by ramya-rao-a** [comment]
This issue was moved to felixfbecker/vscode-php-debug#149
