### ISSUE TITLE
Elixir.tmLanguage works in Sublime but fails in VSCode

### ISSUE THREAD

**Issue by net** [Microsoft/vscode#22477]
When using the official Elixir.tmLanguage file found [here](https://github.com/elixir-lang/elixir-tmbundle/blob/master/Syntaxes/Elixir.tmLanguage), lines that begin with a whitespace character or an arbitrary unhighlighted token (e.g. `foo`) are not highlighted (see screenshot below).

<img width="319" alt="screen shot 2017-03-12 at 8 57 24 am" src="https://cloud.githubusercontent.com/assets/6983821/23831966/f4057248-0701-11e7-9d36-0325e782a4ba.png">

The Elixir.tmLanguage file does—of course—work perfectly fine in TextMate and Sublime.

https://github.com/elixir-lang/elixir-tmbundle/blob/master/Syntaxes/Elixir.tmLanguage

- VSCode Version: 1.10.2
- OS Version: macOS 10.12.3 (Sierra)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-textmate#37
