### ISSUE TITLE
Open Editors in Explorer is not updating list of editors

### ISSUE THREAD

**Issue by ElleonorK** [microsoft/vscode#224732]
Type: <b>Bug</b>

Open a few files in editor.
Expand open editors section in explorer.
Use the close-all button.
The editors are closed, but the section still shows all of them as open. Clicking on them does not re-open the editor and the X (close) near each item does nothing.

VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 4, 3|
|Memory (System)|32.00GB (0.58GB free)|
|Process Argv|--crash-reporter-id 300b06af-09b2-466c-82ce-2fe644b842d4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (80)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
better-comments|aar|3.0.2
Handlebars|and|0.4.1
shell|bbe|0.3.0
htmlplay|bia|0.0.10
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.23.1
markdown-preview-github-styles|bie|2.0.4
markdown-yaml-preamble|bie|0.1.0
mermaid-markdown-syntax-highlighting|bpr|1.6.6
path-intellisense|chr|2.9.0
gitignore|cod|0.9.0
vscode-tree-extension|CTC|0.0.12
vscode-markdownlint|Dav|0.55.0
diff-arrows|dev|1.0.1
githistory|don|0.6.20
gitlens|eam|15.2.3
vscode-hide-comments|eli|1.9.0
fold-unfold-all-icone|Fer|0.0.3
copilot|Git|1.219.0
copilot-chat|Git|0.18.1
vscode-pull-request-github|Git|0.92.0
airflow-templates|Gra|0.0.6
hcl|has|0.5.0
terraform|has|2.32.2
vscode-drawio|hed|1.6.6
path-autocomplete|ion|1.25.0
vscode-go-template|jin|0.2.1
vscode-ts-whitespace-converter|joh|1.2.1
auto-comment-blocks|kev|1.0.1
l13-diff|L13|1.3.8
kubernetes-templates|lun|1.3.1
code-groovy|mar|0.1.2
TFS|mat|0.0.4
mirrord|Met|3.60.1
git-graph|mhu|1.30.0
vscode-azureappservice|ms-|0.25.2
vscode-azurecontainerapps|ms-|0.7.0
vscode-azurefunctions|ms-|1.15.1
vscode-azureresourcegroups|ms-|0.9.1
vscode-azurestorage|ms-|0.16.0
vscode-azureterraform|ms-|0.3.2
vscode-azurevirtualmachines|ms-|0.6.5
vscode-cosmosdb|ms-|0.22.0
vscode-docker|ms-|1.29.1
vscode-aks-tools|ms-|1.4.8
vscode-kubernetes-tools|ms-|1.3.16
vscode-postgresql|ms-|0.3.0
debugpy|ms-|2024.10.0
python|ms-|2024.12.1
vscode-pylance|ms-|2024.7.1
remote-containers|ms-|0.380.0
azure-account|ms-|0.12.0
azurecli|ms-|0.6.0
vscode-node-azure-pack|ms-|1.2.0
sqltools|mtx|0.28.3
airflow-vscode-extension|Nec|1.5.0
vscode-groovy-lint|Nic|3.3.1
autodocstring|njp|0.6.1
vscode-yaml-sort|Pas|6.5.17
pdf-cos-syntax|pdf|0.1.5
vscode-gitignore-generator|pio|1.0.3
terraform-advanced-syntax-highlighting|pjm|1.4.3
java|red|1.33.0
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
sqltools-singlestore-driver|sin|0.1.3
comment-divider|sta|0.4.0
autopoetry|Ste|0.0.2
sort-json|Thi|19.1.1
helm-intellisense|Tim|0.14.3
pdf|tom|1.2.2
vscode-java-debug|vsc|0.58.0
vscode-java-pack|vsc|0.28.0
snippet|vsc|1.2.0
markdown-all-in-one|yzh|3.6.2
vscode-python-poetry|zes|0.17.25

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
ccpltc:31103427
pythonrstrctxtcf:31103194
wkspc-ranged-c:31107834

```

</details>

**Comment by aaronadamsCA** [comment]
I'm seeing similar behaviour tied to `scm.workingSets.enabled`.

In a freshly reloaded Codespaces window with no extensions, everything works fine. After switching branches, the list of open editors stops updating when opening/closing editors. Interestingly it still updates when switching branches.

https://github.com/user-attachments/assets/894bfed2-4a48-45f1-8fec-28adfa444d59

```
Version: 1.92.0 (Universal)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```
