### ISSUE TITLE
File open dialog does not appear and can't open files from external source.

### ISSUE THREAD

**Issue by Wielding** [microsoft/vscode#224767]
Type: <b>Bug</b>

I am no longer able to open the file dialog or open a file from nautilus.  The file dialog does not open via the menu or keyboard shortcut and if I try to "open with" from the nautilus context menu it just opens code to the last workspace without opening the file specified.

I had the same result when running vscode without any extensions enabled.

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Linux x64 6.9.3-76060903-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900KF (32 x 5341)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|3, 2, 1|
|Memory (System)|62.63GB (56.85GB free)|
|Process Argv|/home/redacted/.dotfiles|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|gnome|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
vscode-httpyac|anw|6.15.0
vscode-eslint|dba|3.0.10
i3|dca|1.0.0
gitlens|eam|15.2.3
dependi|fil|0.7.6
vscode-firefox-debug|fir|2.9.10
shell-format|fox|7.2.5
copilot|Git|1.219.0
copilot-chat|Git|0.18.1
go|gol|0.42.0
pfeifer-hurl|Jac|1.3.3
vscode-home-assistant|kee|1.40.0
mesonbuild|mes|1.25.1
vscode-scss|mrm|0.10.0
meson-build|Mrm|0.2.1
csdevkit|ms-|1.8.14
csharp|ms-|2.41.26
vscode-dotnet-runtime|ms-|2.1.1
vscodeintellicode-csharp|ms-|2.1.11
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.1
vscode-pylance|ms-|2024.7.1
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.5
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.14
makefile-tools|ms-|0.9.10
powershell|ms-|2024.2.2
vscode-speech|ms-|0.10.0
color-highlight|nau|2.8.0
vala|pri|1.1.0
vscode-redhat-account|red|0.2.0
vscode-yaml|red|1.15.0
bash-debug|rog|0.3.9
rust-analyzer|rus|0.3.2053
markdown-preview-enhanced|shd|0.8.13
even-better-toml|tam|0.19.2
tauri-vscode|tau|0.2.6
cmake|twx|0.0.17
vscode-terminal-here|Tyr|0.2.4
errorlens|use|3.20.0
vscode-lldb|vad|1.10.0
clang-format|xav|1.9.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Sounds similar to https://github.com/microsoft/vscode/issues/221836

Pinging @deepak1556

**Comment by deepak1556** [comment]
Yeah they are the same, merging to https://github.com/microsoft/vscode/issues/221836
