### ISSUE TITLE
Possible feature request: Edit parts of a file as if they are separate files accessible by tabs.

### ISSUE THREAD

**Issue by jdc-cunningham** [Microsoft/vscode#22470]
edit: if this already exists, could you please tell me what the setting is called.

I'm not sure if there is a reason this is not in practice/common place.

Say it was a JavaScript file and you had three functions, function one(), function two(), function three()...

If you had three separate files open, you'd have three tabs that you can click on and switch between the files.

If you had a pretty complex JavaScript file and wanted to 'chunk it' and modify it as if it was made of multiple individual files, while keeping it as one... I achieved this effect by using the small-scripts approach where you then had to include each one sequentially on an html page to work in order.

Yeah this might be a pointless question, how would you even activate that/specify where the splits happen? Highligh/select a section/code block?

**Comment by jdc-cunningham** [comment]
I was listening to a Change Log podcast and realized you guys are probably swamped with requests. Also I was listening to a podcast about web pack and I think that is what I'm after. Dang I am behind.

**Comment by weinand** [comment]
This feature is not supported.
WebPack is a module bundler for efficient loading of resources at runtime. I don't see that this could help with your feature.

**Comment by eamodio** [comment]
While this isn't exactly what you are getting at (I don't think), but you can kind of do this in code today -- any file can be opened once in each (of the 3) editor group. So you can open file A scrolled to `function one()` in group 1 (left), open file A again (or use the split command) in group 2 (center) scrolled to `function two()`, open file A again (or use the split command) in group 3 (right) scrolled to `function three()`.

So while each editor group will be visible (and you can only have 3) it provides some (imo important) ability to do what you are asking.

**Comment by weinand** [comment]
@jdc-cunningham how does @eamodio's suggestion sound to you?

**Comment by jdc-cunningham** [comment]
I am doing what @eamodio has suggested for long files where one editor pane is scrolled to a specific position say CSS group, and the other is scrolled to the HTML elements.

I mentioned the webpack as what they were describing of being able to join different components. It sounds handy as opposed to adding another <script></script> to the HTML file. Webpack also mentioned code splitting but this was talking about asynchronous something or other.

Anyway not a big deal. The minmap helps with code overview as well.

Building smaller code blocks help so you don't get lost in the process with a huge file.

Thanks for the suggestions/comments.

**Comment by hasan-abdul-rahman** [comment]
I think the feature you want is to open the same file in multiple tabs with each one scrolled to a different position.

Another way you can sort of do this is with bookmarks. There's an extension for that.

**Comment by jdc-cunningham** [comment]
@hasan-abdul-rahman 

Yeah I suppose that is ultimately what I'm after though I was hoping it would be separate code blocks, although why? If you'll end up combining it into one file anyway? So yeah, I will take a look at that, thanks.

**Comment by danPadric** [comment]
@jdc-cunningham: Would what you ask be the same as https://github.com/Microsoft/vscode/issues/22619?

I would like to be able to isolate a piece of code (and only that part) and have it show up as-if an isolated piece in a new editor / tab. With ZEN feature active that would be real nice to focus my concentration on the changes being done at that moment.

Having several code pieces open & available like this would be more efficient than bookmarks too. The mind can focus on functionality according to the tab position.

Seeing this request is so long in the tooth - wonder if it will happen.

Regards.

**Comment by jdc-cunningham** [comment]
@danPadric

I'm still behind in "proper" web dev or coding in general. Like using classes but what I mean relevant to this is, I think you can from what I hear combine separate functions into one using a compiler. I haven't used one yet myself. Maybe compiler is the  wrong word webpack?

So if you had a global thing, namespace? I'd on know.

function submitOrder(orderID) {

  // this function checks if the order exists
  function checkOrderID() {
    return true/false;
  }

  function() {
    // another function
  }

}

Say that the checkOrderID function is like 300 lines long for some reason and has multiple subfunctions inside.

If I could have this entire function open in another tab but still be part of the main submitOrder function. 

I don't know it's probably pointless/not done like this for a reason. I'm starting to learn Angular maybe I will see. I think you still can't include JS like in PHP. Unless you use <scripts> but I think that's on HTML.

Yeah what the other issue/request sounds similar except it's hiding code/still in the same tab maybe that still accomplished the problem. Also you can collapse blocks of code with the +/- signs on the left.

I am curious about this:

>i know the search can be done only on the selected text

I was looking for that myself, highlight a block and do search and replace in that highlighted section only.

Anyway hope you find an answer for your interest.

**Comment by bpasero** [comment]
Opening the same file in multiple editor groups is the right way of doing this. You can use folding to collapse other parts of the file you want to not see.
