### ISSUE TITLE
can't save/edit profile

### ISSUE THREAD

**Issue by pot-code** [microsoft/vscode#224766]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.92.0 (user setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

https://github.com/user-attachments/assets/c5eb71f6-3020-47d9-985e-83339cbcfe87

**Comment by pot-code** [comment]
> /duplicate of #224718 

how could it be the duplication of a spam?

**Comment by gjsjohnmurray** [comment]
Sorry, paste error

https://github.com/microsoft/vscode/issues/224566
