### ISSUE TITLE
VSCode SourceControl - Disable Incoming/Outgoing Items

### ISSUE THREAD

**Issue by susanne99** [microsoft/vscode#224773]
Version: 1.92.0 (system setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

sorry, but how can I block this unnecessary feature. I tried both of these settings, but they don't work. I ask you to leave the programs alone, don't keep changing something - it doesn't make any sense in most cases - I'm going crazy

"scm.showIncomingChanges": "never",
  "scm.showOutgoingChanges": "never",

**Comment by gjsjohnmurray** [comment]
/duplicate

Please see https://code.visualstudio.com/updates/v1_92#_incomingoutgoing-changes-graph for the relevant change.

> leave the programs alone

Maybe consider turning updating off?
