### ISSUE TITLE
new tab position depends on active tab

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#22480]
v1.11.0-insider

If I have two files 'pinned' open (keep open), when I open a third:
- new file opens on **end** if I got second file active
- new file opens **in between** two pinned files if first is active

I am not sure if working as intended?
but would anyone else appreciate an option to make new tab position independent of active tab?
Thanks.

`  "workbench.editor.newTabs": right|left|active,`

https://github.com/Microsoft/vscode/issues/12622

**Comment by bpasero** [comment]
This works as designed, we open the tab close to the location of the currently active tab. You can control this via the `"workbench.editor.openPositioning"` setting.
