### ISSUE TITLE
Support for Splitting Input String into Multiple Arguments in launch.json

### ISSUE THREAD

**Issue by sammasak** [microsoft/vscode#224859]
#### Description

Currently, VS Code's `launch.json` configuration does not natively support splitting a single input string into multiple arguments for the `args` array when launching a Python script. This limitation makes it difficult to pass multiple arguments to a script from a single input prompt. 

#### Steps to Reproduce

0. example app

```python
import typer

app = typer.Typer()

@app.command()
def command1(arg1: str):
    typer.echo(f"Argument 1: {arg1}")

@app.command()
def command1(arg1: str, arg2: str, arg3: str):
    typer.echo(f"Argument 1: {arg1}")
    typer.echo(f"Argument 2: {arg2}")
    typer.echo(f"Argument 3: {arg3}")

if __name__ == "__main__":
    app()

```

1. Create a `.vscode/launch.json` file with the following configuration:
    ```json
    {
      "version": "0.2.0",
      "configurations": [
        {
          "name": "Run CLI Script",
          "type": "debugpy",
          "request": "launch",
          "program": "cli.main",
          "args": [
            "${input:args}"
          ],
          "console": "integratedTerminal"
        }
      ],
      "inputs": [
        {
          "id": "args",
          "type": "promptString",
          "description": "Enter the args for the task",
          "default": "previous_args"
        }
      ]
    }
    ```

2. When running the above configuration, enter multiple arguments as a single string (e.g., `command1 arg1`).

3. Observe that the entire string is passed as a single argument rather than being split into individual arguments.

#### Expected Behavior

It would be beneficial if `launch.json` could natively support splitting a single input string into multiple arguments for the `args` array. For example, when entering `arg1 arg2 "arg with spaces" arg4`, the arguments should be passed as `arg1`, `arg2`, `arg with spaces`, and `arg4` to the script.

Additionally it would be nice to have the default value be dynamic such that you could reuse the latest used args as the default value.

 
```[tasklist]
### Tasks
```

**Comment by roblourens** [comment]
This would basically be an input that would return multiple values, which is a different type of thing than the existing `promptString`.

**Comment by sammasak** [comment]
> This would basically be an input that would return multiple values, which is a different type of thing than the existing `promptString`.

Yes, Would be nice to have one input field that takes in any amount of args, (and then uses the previously ran args as default for the next run).

**Comment by BuyMyBeard** [comment]
Is there any possibility this could be reopened for community review?

**Comment by TDuffinNTU** [comment]
> I'm surprised this doesn't have more interest, it would be very useful for debugging complex CLIs. I've resorted to pasting args into `launch.json` directly

It occurs _just enough_ to be a major PITA to work around, but not enough that there's enough people willing to do the social media campaign to upvote the issue. Rather silly way to assign things to a backlog but I digress.
