### ISSUE TITLE
Addition of files sorted by file type rather than by file name in the file explorer

### ISSUE THREAD

**Issue by 5txvn** [microsoft/vscode#224868]
In VSCode I have known that the file explorer separates files and folders by putting the folders on top and the files on the bottom. However, for the files on the bottom, they are sorted in alphabetical order, and as far as I'm aware, there is no option for them to be sorted by file type. I would like it to be such that there is an option for the files to be sorted firstly by file type and within the file types to then be sorted alphabetically, I hate it when I'm working on a project in Node.js and I have the package.json file and README in between all the other Javascript files, so if it is possible to create an option where you can choose to have the files sorted by type, that would be great, thanks.

**Comment by PedroASB** [comment]
There is an option to sort files by type. Go to settings and search for "Explorer: Sort Order", then change it to "type".

![image](https://github.com/user-attachments/assets/befee640-d8be-4ba3-9483-22b4d2e6c489)
