### ISSUE TITLE
The JS/TS language service crashed 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by ctbwx** [microsoft/vscode#224864]
Type: <b>Bug</b>

Open VSCode, open .ts file, do literally nothing, error will occur constantly on repeat.

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.91GB (10.79GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/ctbw/vastly/prod-wave-apps/the-home-mag --remote=wsl+Ubuntu --crash-reporter-id 1b8ca2e9-b418-4dba-8c29-af129d006981|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 0)|
|Memory (System)|15.58GB (9.34GB free)|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|3.18.0
turbo-console-log|Cha|2.10.4
npm-intellisense|chr|1.4.5
vscode-eslint|dba|3.0.11
gitlens|eam|15.2.3
prettier-vscode|esb|10.4.0
vscode-github-actions|git|0.26.3
debugpy|ms-|2024.10.0
python|ms-|2024.12.1
vscode-pylance|ms-|2024.7.1
prisma|Pri|5.17.0
vs-code-prettier-eslint|rve|6.0.0
trailing-spaces|sha|0.4.1
code-spell-checker|str|3.0.1
better-comments|aar|3.0.2
file-icons|fil|1.1.0
vscode-graphql-syntax|Gra|1.3.6
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.380.0
remote-wsl|ms-|0.88.2
material-icon-theme|PKi|5.8.0
vscode-icons|vsc|12.8.0
vim|vsc|1.27.3
jinja|who|0.0.8
material-theme|zhu|3.17.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
ccpltc:31103427
pythonrstrctxt:31103193
wkspc-onlycs-c:31106320

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
