### ISSUE TITLE
Still can't launch external programs

### ISSUE THREAD

**Issue by SapiensAnatis** [Microsoft/vscode#22484]
- VSCode Version: 1.11.0 (compiled from source just now)
- OS Version: Arch Linux (kernel 4.10.1-1-ARCH)

Steps to Reproduce:

1. Use zsh or another non-bash shell, I've heard it's tied to this but cannot confirm as changing shell doesn't fix it for me
2. Attempt to launch an external program in your build command.

Even after the recent issue #21655 and #22152 which was supposed to be fixed by [this](https://github.com/Microsoft/vscode/commit/78bc68a1d06403ffc02f61e0043af682e8f3d681) commit (for which I have verified the changes in the relevant file), I get the same issue as I did before. That is, when trying to launch cargo I get this error:
```
Failed to launch external program cargo run.
spawn cargo ENOENT
```

My tasks.json is about as simple as it gets, so I do not think the issue lies there - it is however enclosed just in case:

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "cargo",
    "isShellCommand": true,
    "args": ["run"],
    "showOutput": "always",
    "isBuildCommand": true
}
```
I have additionally verified that this is the tasks.json file being used by making changes and seeing those reflected in the error message.

The cargo command is attempted in a valid cargo directory which cargo shows no objection to when ran manually via terminal, displaying the correct output for the compiled program.

I do not experience this issue in the Windows version of VSCode. 

I've tried to be as inclusive of all necessary details as possible, hopefully it's something simple which I've done wrong. Thanks in advance!

**Comment by dbaeumer** [comment]
The current task runner takes the standard shell to execute shell commands. This is why this fails for you. We are working on executing tasks in the integrated terminal which will allow you to customize the shell which should make this work.

Preliminary support for terminal executing is available since 1.9 however needs to be enabled. To enable this for your setup simply change the version number of the tasks.json to `2.0.0`.

I am closing this issue since no work will be done to support this in the old output runner.

**Comment by SapiensAnatis** [comment]
Thanks for the clarification!

**Comment by JasonKleban** [comment]
Is there a similar trick for launch.json?  I tried upping the version number of that file to 2.0.0 as well but it still fails:

`
npm-run-all --inspect=18307 --debug-brk --parallel watch:* 
Node process error: Error: spawn npm-run-all ENOENT
`
