### ISSUE TITLE
Spread operator can break JS highlighting.

### ISSUE THREAD

**Issue by jeffmcmahan** [Microsoft/vscode#22483]
- VSCode Version: 1.10.2
- OS Version: 10.11.6

Steps to Reproduce:

1. Place this code in a JS file:

    ```js
    myFunc
    (...argName)
    
    function otherFunc() {} // <-- Not highlighted.
    ```
Remove the spread operator or the line break and the highlighting works again.

## Why fix this?
The parser used by VSCode is plainly in error. And FWIW, stuff like this is useful when working with higher-order functions:

```js

funcName
  (...someArgs)
  (someMore)
  (someMoreAgain)

```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#431
