### ISSUE TITLE
Clicking on the App Icon Doesn't Show the System Menu

### ISSUE THREAD

**Issue by NickAllmakerOpsCompass** [microsoft/vscode#224857]
Type: <b>Bug</b>

In Windows, when you click on the app icon in the top left corner of a top-level window, it drops down the system menu (Restore/Move/Size/Minimize/Maximize/Close). Double-clicking on the app icon closes the window.

Visual Studio Code's app icon does not mimic these behaviors, instead having the app icon be part of the "neutral" title bar.

## Single-Clicking

Steps to Reproduce:

1. Left-click on the app icon.

Expected Results:

- The system menu appears.

Actual Results:

- Nothing happens.

## Double Clicking

Steps to Reproduce:

1. Double-left-click on the app icon.

Expected Results:

- The window closes.

Actual Results:

- The window maximizes (or restores).

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.75GB (15.04GB free)|
|Process Argv|--crash-reporter-id 58ca3c29-86d0-4dfd-9ea8-73c135e93ebc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 0)|
|Memory (System)|15.50GB (14.19GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.24.1
copilot|Git|1.219.0
copilot-chat|Git|0.18.1
haml|kar|1.4.1
vscode-azurefunctions|ms-|1.15.1
vscode-azureresourcegroups|ms-|0.9.1
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.1
vscode-pylance|ms-|2024.7.1
jupyter|ms-|2024.7.0
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.2
azure-account|ms-|0.12.0
hexeditor|ms-|1.10.0
powershell|ms-|2024.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
ccplti:31103428
pythonrstrctxt:31103193

```

</details>

**Comment by bpasero** [comment]
I am quite sure this used to work and is maybe broken since a while.

**Comment by benibenj** [comment]
There is a setting for the double click close behaviour `window.doubleClickIconToClose`.

**Comment by bpasero** [comment]
Sorry I think I confused myself, the menu shows up on right-click, I am not sure it ever showed up on left-click.

**Comment by benibenj** [comment]
Closing as it does not seem to be a well established pattern
