### ISSUE TITLE
[WelcomeUX] Request: Option to remove directory from "Recent" section if it doesn't exist

### ISSUE THREAD

**Issue by NuroDev** [microsoft/vscode#22489]
- VSCode Version: 1.10.2
- OS Version: MacOS 10.12.3

# Suggestion: 
> Welcome page has list of recent items. If a item has been removed from the file system. When clicking on the item in welcome page, the dialog box pops up as it does currently warning you that the path does not exist.  
However I'm suggesting that a second button be added to that dialog box called "Remove" to remove that single item from recent list.

Would be a nice and simplified way to remove remove directories from the welcome page 😄

**Comment by chrmarti** [comment]
It is removed after you click on it, the Welcome page doesn't refresh, you have to close and reopen it to get the updated list.
