### ISSUE TITLE
Every new window causes workspace trust dialog to pop up

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#224866]
1. Set `security.workspace.trust.emptyWindow` to false
2. Open a new window
3. :bug: Workspace trust dialog pops up wanting to run tasks

My thoughts are the dialog is annoying and I'm unable to tell which tasks are trying to run.

![Workspace trust dialog for empty window](https://github.com/user-attachments/assets/07532224-571f-428c-9d48-8c3ea5331796)

**Comment by meganrogge** [comment]
Do you know if this only started recently? 🤔

The task changes of late have only been less eager to activate, so it would surprise me if this is new
