### ISSUE TITLE
Tasks trigger workspace trust dialog in insiders.vscode.dev repo

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#224881]
1. Open a repo in insiders.vscode.dev
2. :bug: see this 

![Image](https://github.com/user-attachments/assets/0a0350df-27e9-49ce-a241-753bb6686fff)

**Comment by meganrogge** [comment]
This is expected if the repo that you open has tasks that run on `folderOpen`. Could you pls provide me with a repo for which this happens that doesn't have those?

**Comment by meganrogge** [comment]
seeing this dialog when I just open a folder, so wondering if something with workspace trust has changed recently. No changes with tasks recently could explain this.

![Image](https://github.com/user-attachments/assets/a2293901-cd68-44b5-b2e8-23cc41e745f7)

**Comment by joyceerhl** [comment]
Doesn't repro in 3c490dadc81e29db441cb1cbe93b8c0249585569, repros in 5410988877ae11e0cb53097aed20fef4cbf3f07f:
* Bad: https://insiders.vscode.dev/github/microsoft/vscode-docs?vscode-version=5410988877ae11e0cb53097aed20fef4cbf3f07f
* Good: https://insiders.vscode.dev/github/microsoft/vscode-docs?vscode-version=3c490dadc81e29db441cb1cbe93b8c0249585569

**Comment by meganrogge** [comment]
@joyceerhl found these task PRs in that time frame: https://github.com/microsoft/vscode/pull/224329, https://github.com/microsoft/vscode/pull/224333

@connor4312 https://github.com/microsoft/vscode/pull/224333 could be causing this.

**Comment by meganrogge** [comment]
Since it's not reproducing for desktop, maybe we should check if `isWeb` and not add completions for that case

**Comment by meganrogge** [comment]
@rzhao271 found it also happens in an empty window on desktop #224866

**Comment by joyceerhl** [comment]
Still seeing this in insiders.vscode.dev (and also RemoteHub on desktop) with the changes in https://github.com/microsoft/vscode/commit/ff8504ae52f8e0d0e9a33e6cb326efc21e42db3e

![Image](https://github.com/user-attachments/assets/ed268d0a-467f-422a-86fb-8431e8fc9a04)

**Comment by meganrogge** [comment]
This is coming from `getKnownTasks` -> `getWorkspaceTasks` here

![Image](https://github.com/user-attachments/assets/e65b2d73-00fc-4beb-9208-d9af1d175af1)
