### ISSUE TITLE
Search - Inconsistent results

### ISSUE THREAD

**Issue by RambousekTomas** [microsoft/vscode#224843]
Hi, I am having issue with search of files within project folder.
I am searching for string within file in node_modules and VS Code stopped to display the results from that folder.
Even including node_modules in files to include does not helps.
![image](https://github.com/user-attachments/assets/a473298a-a6d3-46ce-8947-8938fcf2bfc8)
<img width="1032" alt="image" src="https://github.com/user-attachments/assets/c56e8365-8752-47a2-a01c-b6810b89eada">

Few minutes later:
It works again without the issue.
![image](https://github.com/user-attachments/assets/8dbcdc38-063a-4bf1-baa1-2c962ee0b709)

As a user I am not sure what to expect from the search. I have to always double check the results with another search tool.

**Comment by RambousekTomas** [comment]
I have disabled all extensions, restarted the mac and it did not matter. I do not have index.js file open.

![image](https://github.com/user-attachments/assets/035bdce5-9366-417d-a541-8ad622702860)

**Comment by andreamah** [comment]
Are you opening vscode in different folders between the two screenshots? The search feature is meant to search the current folder plus any open files. In the first screenshot with `index.js`, based on the path that it shows, it looks like it wasn't in the current directory. Was this true? Or are there some symlinks that are causing search to look in other directories?
