### ISSUE TITLE
Hotkey for displaying a hidden menu is accepted even when combined with other modifier keys

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#22488]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:

1. Set the menu to hidden by default
2. Leave the hotkey for showing the menu as the default (`ALT` in my case)
3. Press `ALT` + `CTRL` or `ALT` + `SHIFT`
4. The menu is displayed on key release

It is pretty common for me to start to use a hotkey combination and then change my mind and let go of the modifier keys before pressing the main hotkey. If those modifiers included the `ALT` key, the menu is displayed even if other modifier keys were also being pressed at the same time.

**Comment by bpasero** [comment]
The only workaround for now is `window.menuBarVisibility: hidden` but that also means that the menu never shows up, not even on `Alt` press.

**Comment by bpasero** [comment]
We will change to custom menus on Windows. For now you can set `"window.titleBarStyle": "custom"`.
