### ISSUE TITLE
Rebalance terminal sizes proportionally when creating a new terminal, rather than equally

### ISSUE THREAD

**Issue by bduffany** [microsoft/vscode#224875]
In the terminal pane, when adding a new terminal, the relative sizing that I've set for existing terminal windows is not preserved - instead, vscode resizes all terminal heights to be equal.

Let's say I have 2 terminals `important-terminal` that I've resized to take up 75% of the height of the terminal panel, and another terminal `unimportant-terminal` that only takes up 25% of the height.

Now I add a third terminal, `debug-terminal`, to run some one-off commands against the running servers.

Today what happens is that vscode will resize all 3 terminals to 33.3% height each.

However, I would prefer if vscode would only allocate 33.3% of the height to the new `debug-terminal` that I'm adding, and instead proportionally rebalance the remaining 66% of the height to the existing terminals: `25% * 66%` to `unimportant-terminal`, and `75% * 66%` to `important-terminal`.

The current behavior is very disruptive to my workflow because whenever I add a new terminal, my `important-terminal` shrinks to a size that is much smaller than I would like. This is a frequent problem for me (several times per day) because my workflow requires running 2 different development servers that I want to be running in separate terminals, and I very frequently need to open 1 or 2 other terminals for one-off commands (git commands, long-running tests, debugging running tests, etc.). So I find that I spend a lot of time having to manually resize these windows so that the less important terminal takes up a very small amount of the window height.

**Comment by meganrogge** [comment]
I think by height, you mean width ?

**Comment by meganrogge** [comment]
on reload, the proportional width is maintained. pls create a gif to demonstrate what you mean

https://github.com/user-attachments/assets/dbbc7ee2-0437-4f8e-9ac8-59385d071a57

**Comment by meganrogge** [comment]
Thanks for the gif. We also split horizontally equally vs proportionately
