### ISSUE TITLE
When the menu is hidden by default, toggling should be temporary, and dismissed by non-menu actions

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#22487]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:

1. Set the menu to be hidden by default
2. Press `ALT` to display the menu
3. Change your mind about needing the menu and continue typing in the editor instead

Issues:

- The menu doesn't go away unless `ALT` is pressed a second time
- Hotkey mnemonics continue to be displayed

If the menu is hidden by default, displaying it should be treated as a transient interaction. If the next interaction does not involve the menu, the menu should be re-hidden automatically.

**Comment by bpasero** [comment]
We will change to custom menus on Windows. For now you can set `"window.titleBarStyle": "custom"`.
