### ISSUE TITLE
:{{locate........esss_id}}}

### ISSUE THREAD

**Issue by Hemil09** [microsoft/vscode#224865]
![Annotation 2024-08-05 222844](https://github.com/user-attachments/assets/bbee2918-f98c-4a58-b8d2-524d91db09c2)
Type: <b>Bug</b>

In The Right SIde bar Code panel some line in showint this message
:{{locate........esss_id}}}

:{{locate........esss_id}}}

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|9.88GB (1.44GB free)|
|Process Argv|--crash-reporter-id 41734d3e-4be2-490d-818e-25b76d958efe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vue-peek|dar|1.0.2
vscode-eslint|dba|3.0.10
env-switcher|Eck|0.5.2
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
vetur|oct|0.37.3
material-icon-theme|PKi|5.8.0
nuxt-snippets|pra|1.7.0
autoimport|ste|1.5.4
volar|Vue|2.0.28
vuetify-vscode|vue|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
ccplt:31103426
pythonrstrctxtcf:31103194
hdi1a554:31097393

```

</details>

![image](https://github.com/user-attachments/assets/6cfe593c-859e-47e8-a086-092d9ae7e13e)

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
