### ISSUE TITLE
Terminal suggest: Don't show branch completions after `git checkout -b`

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#224853]
Repro:

1. Pwsh
2. Suggest enabled
3. Type `git checkout -b t`, 🐛 completions show up

Since this needs a new branch, these completions aren't valid

![image](https://github.com/user-attachments/assets/659a758b-0f1f-4d34-b6f6-5a31f6f4f2d2)

**Comment by meganrogge** [comment]
on macOS, in testing this, I do not see suggestions after that ✅ , but the terminal gets unresponsive for several seconds @Tyriar 

https://github.com/user-attachments/assets/dbf2cf99-7e5b-4960-8223-be99bc75e6d0
