### ISSUE TITLE
vsmarketplacebadges.dev badge urls triggering warning in package.json

### ISSUE THREAD

**Issue by song-dog** [microsoft/vscode#224860]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.0
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Create a new extension with the yeoman generator:
  `npx --package yo --package generator-code -- yo code`
2. Open the newly created `package.json`
3. Add a `"badges"` key and add a badge object with a url containing a `vsmarketplacebadges.dev` badge.
4. `vscode.extension-editing` extension warning appears in reference to that url.

Solution:

Replace `"vsmarketplacebadge.apphb.com"` with `"vsmarketplacebadges.dev"` in the `"extensionAllowedBadgeProviders"` array in `product.json`.

**Comment by sandy081** [comment]
@isidorn / @seaniyer Can you please confirm if `vsmarketplacebadges.dev` is a valid badge?

**Comment by isidorn** [comment]
I do not know. Maybe Sean knows.
