### ISSUE TITLE
Content lost on failed save

### ISSUE THREAD

**Issue by crimsonvspurple** [microsoft/vscode#224820]
Type: <b>Bug</b>

# STEPS
- I opened a new tab by double clicking on empty space
- Copy pasted a markdown document from teams
- Made some small edits
- Pressed CTRL+S to save

# Expected
Save dialog somes up for me to choose name/locatione etc

# Actual
A message on bottom right that said something like:
"Can not save document due to xyz (could not read fast enough)...."
It contained C:\untitled01 type of string (why?!)

Right when the message showed up, the tab closed automatically and I could not get my content back in any way.

I tried to reproduce it and I could not. **But loss of data is concerning**.

For reference:
- I did not press ENTER after CTRL+S
- i didn't see any dialog box
- after I pressed CTRL+S, I got the message and tab was gone with the content
- Pressing CTRL+S shows "documents" folder (right now), not `C:\`

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.22GB (7.84GB free)|
|Process Argv|--crash-reporter-id 5aceeabc-a644-4083-a04e-80ed32291469|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-checkbox|bie|0.4.0
markdown-preview-github-styles|bie|2.0.4
bruno|bru|3.1.0
copilot|Git|1.219.0
copilot-chat|Git|0.17.1
ldif|jta|0.2.0
caddyfile-support|mat|0.4.0
vscode-docker|ms-|1.29.1
remote-containers|ms-|0.380.0
remote-wsl|ms-|0.88.2
code-spell-checker|str|3.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31101459
ccpltc:31103427
pythonrstrctxt:31103193
wkspc-onlycs-c:31102393

```

</details>

**Comment by crimsonvspurple** [comment]
Error from VS Code Dev tools:
![image](https://github.com/user-attachments/assets/53fe3c3d-c517-4a6e-901b-5e1eaf092e51)

**Comment by bpasero** [comment]
Sorry to hear that, this kind of data loss should not happen because an editor that failed to save should not just close.

If you can distill steps for me to reproduce that would be great.

**Comment by crimsonvspurple** [comment]
As mentioned, I have tried to reproduce but didn't happen again. So I'm not sure what is the precondition for this issue.

I'm sure typing something in an empty tab and pressing CTRL+S is a very common use case and working as intended for millions of people.

But notice that for some reason, it tried to save `C:\Untitled-1` without even asking me where to save. On top of that, my user account has write permissions to C:\. Apart from defender, there's no other security applications in the computer. This is the only clue that I can provide.

**Comment by bpasero** [comment]
Yeah, that should normally not happen, unless you maybe started `code` from the command line with an explicit path such as `code C:\Untitled-1` where we then open an untitled file and associate that path without asking you to save.

But even then, it should not just close the editor.

Can you maybe try to reproduce with that command line?

**Comment by crimsonvspurple** [comment]
Looks like permissions are set up in a way that I can not create a file _directly in_ c:\ but I can create folders or files inside other folders. So this is the source of unable to write error.

- The command line does indeed popup this error
- But I don't lose the tab
- Also trying to close the tab or window gives me "save/don't save/cancel" dialog as expected

So you are correct in how the behavior should be and I am getting exactly as you said.

I tried with just `code` in run but that doesn't cause this issue because it tries to save in Documents folder then. I never typed code C:\Untitled-1 before though.

Now that I could pop that error up, I noticed something. It has two buttons, retry/discard. If you press discard, it nukes the entire tab.

So there is one bug and one UX issue.
Bug: Without opening `code C:\Untitled-1`, somehow it wanted to save the file there. Can't reproduce anymore.
UX: Clicking discard on an error message nukes the tab with contents. This button gives the feeling that pressing it will _dismiss_ the error, not nuke the tab.

So I'd request for that button to be changed into _dismiss_ and not nuke the tab. Let user do it manually if they want.

**Comment by bpasero** [comment]
I see. Now we are getting a clearer picture of what was going on.

I think that is debatable: "Discard" means, your changes will be discarded. We have had this wording for pretty much the entire lifespan of VS Code so I think it is well understood.

**Comment by bpasero** [comment]
Thinking more about it, maybe we can do changes:
* "Discard" is correct in the context, but what it actually triggers is "Revert", so maybe the button should say "Revert"
* when we show the notification for untitled files, we should not offer this button because clicking it will make the contents unrecoverable. this is different from a normal file that you can just "Undo" to get your changes back or even use the "Timeline" view to see previous contents.

**Comment by bpasero** [comment]
Pushing above suggestion for August, thanks for pointing this out.

**Comment by lizyChy0329** [comment]
I have the same issue

SystemOS: windows 10
VScode: 1.92.2
Extension: [Copy Image Size](https://marketplace.visualstudio.com/items?itemName=lizyChy0329.copy-image-size)

![save lose context](https://files.catbox.moe/uxac57.gif)
