### ISSUE TITLE
Launch.json fails to run using program from environment variable

### ISSUE THREAD

**Issue by ianflett** [microsoft/vscode#224879]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.92.0
- OS Version: Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Use Windows (?).
2. Create an environment variable for a program path (specifically in this example, Godot).
3. Create a project with a `launch.json`.
4. Set `program` to the environment variable (example: `"${env:GODOT}"`).
5. Run the program; it fails with "launch: program '' does not exist".

I've tried altering the path in the environment variable (`\\` and `/`), but no luck. Using an environment variable in this instance just doesn't seem to work. Yet this method is [suggested by Godot](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html#visual-studio-code), hinting it either did work, or just doesn't work under Windows.

I'm not entirely sure this is the right place for this issue, as it requires [coreclr](https://github.com/dotnet/runtime) to run.

**Comment by roblourens** [comment]
Please file this on the repo for the debug extension you're using, and I guess double-check that this variable is set in vscode's environment.
