### ISSUE TITLE
Add "isFolder" capability to explorer/context when clauses

### ISSUE THREAD

**Issue by mdickin** [Microsoft/vscode#22482]
- VSCode Version: 1.10.1
- OS Version: Windows

In my extension, I would like to provide context menu actions that only display when a folder is selected. The "explorer/context" commands use the `when` clauses to allow filtering based on the file language, but it appears there's currently no way to reliably distinguish between a file and a folder. The closest way is to check "!resourceLangId", but that will evaluate to true if the file is not associated with a language (e.g. "my_file.abc123")

Is it possible to add something like "isFolder" to the context?

**Comment by mdickin** [comment]
Yeesh, I don't know how many times I looked past it. This already exists as "explorerResourceIsFolder". Is it possible to add this to the documentation?

Thanks!

**Comment by bpasero** [comment]
This issue was moved to Microsoft/vscode-docs#885
