### ISSUE TITLE
[Suggestion] Git Blame info in gutter

### ISSUE THREAD

**Issue by berwyn** [Microsoft/vscode#2248]
Several other editors, either natively or through extensions, can quickly display information returned from `git blame`, which is a great tool to have while tracking down bugs or conflicts. It would be excellent if VS Code could imitate Atom or the IntelliJ Platform IDEs and have an option to toggle `git blame` info on in the gutter of a version-controlled file (Atom version shown below).

![Atom](https://dl.dropboxusercontent.com/u/1732435/atom-blame-gutter.gif)

**Comment by waderyan** [comment]
This is a good extensions solution. I started on a basic extension called Git Blame. You can find it [here](https://marketplace.visualstudio.com/items/waderyan.gitblame). PRs or recommendations are much appreciated.
On Jan 25 2016, at 10:26 am, berwyn <notifications@github.com> wrote:

Several other editors, either natively or through extensions, can quickly display information returned from git blame, which is a great tool to have while tracking down bugs or conflicts. It would be excellent if VS Code could imitate Atom or the IntelliJ Platform IDEs and have an option to toggle git blame info on in the gutter of a version-controlled file (Atom version shown below).

[Atom]<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fcamo.githubusercontent.com%2faa4e56c7ad143d8d72fc9e1542464d334e50fff3%2f68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f313733323433352f61746f6d2d626c616d652d6775747465722e676966&data=01%7c01%7cwaander%40microsoft.com%7c929d3bc9f5ae4fb9dc9c08d325b4fefb%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=uyI0drC3LTBJ0V1WAdDzULKA2%2blVXe4bfgg5b8MxX2c%3d>

**Comment by berwyn** [comment]
I had actually missed that one, that's certainly useful! That said, it'd be nice if more than one line could be viewed and if it could be in the gutter. I would recommend this for the extension, but it's my understanding that the only UI an extension is allowed to modify is the status bar -- hence the feature suggestion on the editor itself.

**Comment by tbroyer** [comment]
:+1:

**Comment by obrejla** [comment]
:+1:

**Comment by VladimirSemenyuk** [comment]
:+1:

**Comment by fatbrain** [comment]
:+1:

**Comment by carlkenne** [comment]
@waderyan is this extension still working? nothing shows up in my gutter even though it's installed

**Comment by nesukun** [comment]
@carlkenne that extension sadly does not show the blame status in the gutter, but in the status bar like this
![http://i.imgur.com/5cVA7y3.png](http://i.imgur.com/5cVA7y3.png)

**Comment by kavehv** [comment]
👍

**Comment by Tyriar** [comment]
Does anyone know if it is possible to add text to the gutter? If not we should create a separate feature request for that. This should then probably be moved to https://github.com/waderyan/vscode-gitblame and reference the extension API request.

**Comment by carlkenne** [comment]
I can't see anything in my status bar? Only information about line number and branch name and so on...  Are there any way to debug this?

**Comment by ryu1kn** [comment]
I also wanted to see git blame info inside the editor; so developed an extension called [Annotator](https://marketplace.visualstudio.com/items?itemName=ryu1kn.annotator).

As it doesn't open a gutter in a current editor to show blame info and open a new html view instead, it's got its own limitations like no syntax highlighting or no text search on the blame view, but I still find it very useful. Happy to hear suggestions or feedback :)

https://github.com/ryu1kn/vscode-annotator

![Annotator](https://raw.githubusercontent.com/ryu1kn/vscode-annotator/master/images/animations/annotate-code.gif)

**Comment by razvanphp** [comment]
👍 I currently miss this from NetBeans very much, can the API be adapted at least so extensions can improve this? Very useful feature.

**Comment by jez9999** [comment]
Yep this is one of the few things I regularly find myself missing in VS Code.  With Git support built-in, a natural evolution would be a right-click "Git blame" option that opens blame in the gutter.  Probably ought to be on the roadmap.

**Comment by nesukun** [comment]
I'd love to recommend to anyone missing this functionality, the extension GitLens is pretty much what I wanted and I've been using it for a while now.

**Comment by ehartford** [comment]
GitLens does everything I could ever want and more.

**Comment by sandervalstar** [comment]
Adding this configuration for GitLens will give you the desired behavior.

```json
    "gitlens.blame.compact": false,
    "gitlens.blame.format": "${date|10} ${author|8}",
    "gitlens.blame.dateFormat": "YYYY-MM-DD",
    "gitlens.blame.highlight.locations": [
        "gutter",
        "overview"
    ]
```

**Comment by joaomoreno** [comment]
We suggest to use GitLens! :+1:
