### ISSUE TITLE
Not Rendering

### ISSUE THREAD

**Issue by AnasAloor** [microsoft/vscode#224861]
Type: <b>Bug</b>

Auto-generated text from notebook cell performance. The duration for the renderer, VS Code Builtin Notebook Output Renderer, is slower than expected.
Execution Time: 1m 27.5s
Renderer Duration: 3ms

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.79GB (4.42GB free)|
|Process Argv|--crash-reporter-id 156bcc58-3747-4fb9-8621-6f246103d4bc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
python-image-preview|076|0.1.2
vscode-django|bat|1.15.0
blackbox|Bla|1.3.70
dscodegpt|Dan|3.4.47
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
nbpreviewer|jit|1.2.2
vsc-python-indent|Kev|1.18.0
rainbow-csv|mec|3.12.0
debugpy|ms-|2024.10.0
pylint|ms-|2023.10.1
python|ms-|2024.12.1
vscode-pylance|ms-|2024.7.1
datawrangler|ms-|1.6.0
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.2
autodocstring|njp|0.6.1
tabnine-vscode|Tab|3.132.0
pdf|tom|1.2.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
jinja|who|0.0.8
chat-gpt|zha|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
ccplc:31103425
pythonrstrctxt:31103193
wkspc-onlycs-c:31106320

```

</details>

**Comment by rebornix** [comment]
@AnasAloor can you please provide more details of what issue you are running into?
