### ISSUE TITLE
Allow HTTP links for localhost in documents and extension development

### ISSUE THREAD

**Issue by Prunoideae** [microsoft/vscode#224970]
Currently, I'm developing an extension that can decorate strings with images rendered from a local server on demand. This requires the extension to provide HTTP links to the `contentIconPath`, but unfortunately, resources from HTTP links are not allowed in VSCode:

![image](https://github.com/user-attachments/assets/a3fdeb20-cf4a-4827-a593-84d0854dc192)

Setting up HTTPS for each local server is unnecessary in my opinion, as the `localhost` should only be accessed by the user, and only `GET` request is used. It would be helpful if HTTP can be allowed in just localhost or a configurable set of hosts.

**Comment by mjbvz** [comment]
@bpasero Adding you because I believe this is blocked by our workbench content security policy

Marking as a feature request to gauge interest
