### ISSUE TITLE
No tooltip on hover on package.json

### ISSUE THREAD

**Issue by alexvrv** [microsoft/vscode#224918]
Type: <b>Bug</b>

Hi, there is no tooltip anymore on hovering over dependencies in package.json file. 

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.87GB (19.03GB free)|
|Process Argv|--crash-reporter-id e64f8c30-d565-44cf-afee-717e16fda1c6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-javascript-snippet-pack|aka|0.1.6
pug|ama|1.0.1
ng-template|Ang|18.1.2
turbo-console-log|Cha|2.10.4
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
package-json-upgrade|cod|3.0.1
codeium|Cod|1.10.11
angular-schematics|cyr|6.12.0
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
gitlens|eam|15.2.3
vscode-html-css|ecm|2.0.10
Angular-BeastCode|Mik|17.0.4
material-icon-theme|PKi|5.8.0
vscode-xml|red|0.27.1
trailing-spaces|sha|0.4.1
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
f8hc8238:30694864
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
ccpltc:31103427
pythonrstrctxtcf:31103194
1iic9185:31097392
wkspc-onlycs-c:31106320

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate and likely to be fixed in upcoming recovery release.

**Comment by gjsjohnmurray** [comment]
#224510
