### ISSUE TITLE
Edit + undo removes all BPs in file

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#22492]
- Start debug session with a few breakpoints
- Accidentally add or remove a newline
- Undo
- All BPs in file are gone

If you delete the newline and save, then this doesn't happen.

**Comment by isidorn** [comment]
Can not reproduce.
Do you see this all the time.
Do you aslo see other editor decorations being gone - for instance the lightbulb or some errors in the editor?

![bpsdisapear](https://cloud.githubusercontent.com/assets/1926584/23899501/a58d9586-08b5-11e7-83f5-e3b612abba20.gif)

**Comment by roblourens** [comment]
I just noticed that this only happens with `inspector`, but I don't see what the debug adapter could have to do with it.

**Comment by isidorn** [comment]
I also can not reproduce with `inspector`

**Comment by roblourens** [comment]
I'll debug a little more

**Comment by isidorn** [comment]
Assigning to you so you get more data, assign back to me once you have somethign 😊

**Comment by roblourens** [comment]
Turns out to be a node2 bug triggered by updating a bunch of BPs at once. When doing this, vscode deletes all BPs one by one, then resets them.

**Comment by roblourens** [comment]
Should be easy for someone to verify, if you want to repro it, it should be easier with anything that will slow the process down, like 

- many breakpoints
- in a larger file
- when sourcemaps are present
