### ISSUE TITLE
Invalid JS highlight

### ISSUE THREAD

**Issue by indapublic** [Microsoft/vscode#22498]
- VSCode Version: Version 1.10.2 (1.10.2)
- OS Version: OSX 10.12.3 (16D32)

Code example:
```
render() {
    return this.props.data.weekDays.filter((weekDay, index) => (this.state.showAll || index < 3)).map((weekDay, key) => (
      <p key={key}>
        {weekDay.label} {this.props.data[weekDay.id].start} - {this.props.data[weekDay.id].finish}
      </p>
    ))
  }
```

Highlight example:
<img width="906" alt="screen shot 2017-03-13 at 10 35 28" src="https://cloud.githubusercontent.com/assets/856260/23837747/d68f7de4-07d8-11e7-8a50-e6a95fc88f17.png">

If I will change `index < 3` to `3 > index`, all is fine

<img width="924" alt="screen shot 2017-03-13 at 10 37 08" src="https://cloud.githubusercontent.com/assets/856260/23837759/084e9144-07d9-11e7-9cb9-b963852259cf.png">

**Comment by kjnsn** [comment]
Confirmed. I'll have a look into it!

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#430
