### ISSUE TITLE
Code loses keypresses when busy

### ISSUE THREAD

**Issue by rogierschouten** [Microsoft/vscode#2249]
While writing TypeScript in Code, sometimes my keypresses get lost if Code is busy e.g. updating its language services. I end up with the start and end of the word I'm typing, with the middle bit missing. Collegues of mine have the same issue, especially on slower computers.  I would expect code to hang for a while maybe, but then type the word in its entirety.

OS: Windows 7 Professional
Code: 0.10.6

**Comment by bpasero** [comment]
Interestingly I have seen this too but only since a few days, I wonder if something changed here that could have an impact.

For example: I do see it very bad when running Win10 in parallels with NVDA enabled, but I am not sure if NVDA maybe just eats some keys. Also my system is very slow then.

On Mac however I also experience this and there my machine does not seem to be under heavy load.

@alexandrudima fyi

**Comment by alexandrudima** [comment]
@bpasero I have made a change last week that caused some inputs to be missed, but this was only on master until a1bd50f63fd8185a13495ff3d4c67396109e4e71 which now fixes it. So nothing I can think of regarding 0.10.6

**Comment by bpasero** [comment]
@alexandrudima ok good, I will report back if I still get it.

**Comment by alexandrudima** [comment]
I want to try the following to validate that the changes in a1bd50f63fd8185a13495ff3d4c67396109e4e71 also address this issue:
- write a program that computes Fibonacci numbers over and over again, keeping a core busy :)
- launch it many times
- try to type in VSCode
- if I don't lose characters, I'll consider this fixed.

**Comment by alexandrudima** [comment]
I have just tried running the following script 6 times until I got 100% CPU in task manager:

```javascript
var n = 0;
for (var i = 0; i < Math.pow(2,32); i++) {
    if (i % 10000000 === 0) {
        console.log(i, n);
    }
    n = (n + i) % 133337;
}
```

Then I changed the source code of the editor to render all the lines all the time (to slow things down further). Typing was lagging a bit, but it did not lose keypresses. I thin a1bd50f fixed the problem.

**Comment by isidorn** [comment]
Verified by Alex (by reading the comments)
