### ISSUE TITLE
Switch to pre-release version not offered for extensions that failed to load

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#224928]
1. Install Copilot and Copilot Chat release extension in VS Code Insiders
2. Notice error that Copilot Chat fails to load because of API incompatibility
3. There is no way for me to switch to pre-release version of Copilot Chat, and now I am stuck in this state 🐛 

We should render the "Switch to Pre-release" button even if extension fails to load.

Also bonus feature request - switching an extension to Pre-release, should switch all it's extension dependencies to pre-release.

fyi @roblourens 

![Image](https://github.com/user-attachments/assets/2de74b22-6163-43d4-b993-c651da23c7ba)

**Comment by rpmkp** [comment]
I was able to work around this issue with the following:
1. Switch to the pre-release version of GitHub Copilot
2. Navigate to the "Extensions: GitHub Copilot" page
3. Select the "EXTENSION PACK" tab, and then uninstall/reinstall the GitHub Copilot Chat extension, and it appears to switch the errored Chat extension to pre-release

**Comment by sandy081** [comment]
I see the Switch to Pre-release version action.

![Image](https://github.com/user-attachments/assets/af28b835-a0cc-401e-9fe9-9be89a01ef46)

 Probably this got fixed meanwhile.
