### ISSUE TITLE
[themes] Add a light/dark theme context variable

### ISSUE THREAD

**Issue by soyrubio** [microsoft/vscode#224927]
It would be beneficial to have a context variable available showing if the current theme is light or dark, i.e. `usesLightTheme` and `usesDarkTheme`.

**Comment by aeschli** [comment]
The vscode API already allows you to get that information:

`window.activeColorTheme.kind`

Is that good enough? 
If not can you elaborate on your use case?

Note if your extension has code you could use that API to create a context variable (that encapsulates even more state)

**Comment by soyrubio** [comment]
Thanks, didn't know about `window.activeColorTheme.kind`, this helps for now.
Nevertheless it would be beneficial to support themed SVGs in markdowns. I see that the theme css variables are passed to the processed markdown DOM element, so its probably the markdown engine which removes the themed colors.
