### ISSUE TITLE
Unstable Code Folding Function in VSCode

### ISSUE THREAD

**Issue by RMSHE-MSH** [microsoft/vscode#224911]
Type: <b>Bug</b>

The code folding feature in Visual Studio Code is experiencing issues. Sometimes, code blocks cannot be folded or unfolded, requiring a restart of VSCode to resolve the issue. Additionally, display issues occasionally occur.

   - When editing code, attempts to fold code blocks are unresponsive.
   - Already folded code blocks cannot be unfolded.
   - The issue temporarily resolves after restarting VSCode but reoccurs after a while.
   - Display issues sometimes occur, such as misaligned code lines or partial code disappearance.

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.87GB (51.28GB free)|
|Process Argv|--crash-reporter-id 68a349fe-b321-482f-be34-532f249e36ba|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
ZwLisp|Zws|1.0.8
codesnap|adp|1.3.4
vscode-subtitles|ast|0.4.0
GBK2UTF8|buu|0.6.2
path-intellisense|chr|2.9.0
keil-assistant|cl|1.7.0
doxdocgen|csc|1.4.0
prettier-vscode|esb|10.4.0
figma-vscode-extension|fig|0.3.5
gc-excelviewer|Gra|4.2.59
codetime|Jan|0.8.0
plantuml|jeb|2.18.1
keil-vscode|jiy|0.0.2
vscode-gutter-preview|kis|0.31.2
vscode-view-in-browser|kop|1.0.5
rainbow-csv|mec|3.12.0
vscode-language-pack-zh-hans|MS-|1.92.2024073109
vscode-edge-devtools|ms-|2.1.5
autopep8|ms-|2024.0.0
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.2
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
remote-explorer|ms-|0.4.3
vscode-serial-monitor|ms-|0.12.0
vsliveshare|ms-|1.0.5936
autodocstring|njp|0.6.1
material-icon-theme|PKi|5.8.0
platformio-ide|pla|3.3.3
polacode|pnp|0.3.4
cucumber|ste|0.14.0
graphviz-interactive-preview|tin|0.3.5
cmake|twx|0.0.17
errorlens|use|3.20.0
JavaScriptSnippets|xab|1.8.0
masm-tasm|xsr|1.1.1
vscode-dosbox|xsr|0.1.8
markdown-all-in-one|yzh|3.6.2
material-theme|zhu|3.17.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
ccplti:31103428
pythonrstrctxt:31103193

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
