### ISSUE TITLE
Preferences search can't search backwards

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#22497]
I was building from source and noticed that the new preferences search can only search forward and doesn't respond to shift+enter to search backwards.

I can see that it is because it uses the IIterator<T> interface, but the actual datastructure it uses implements INavigator<T> which supports going backwards.

I have a PR ready if this is something that you're interested in changing.

**Comment by sandy081** [comment]
@hoovercj Sure. Please submit the PR. 

Thanks
