### ISSUE TITLE
Unexpected brackets are not colored in Light High Contrast theme

### ISSUE THREAD

**Issue by MichaelMakesGames** [microsoft/vscode#224904]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.0
- Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
- Date: 2024-07-31T23:26:45.634Z
- Electron: 30.1.2
- ElectronBuildId: 9870757
- Chromium: 124.0.6367.243
- Node.js: 20.14.0
- V8: 12.4.254.20-electron.0
- OS: Linux x64 6.9.3-76060903-generic

Steps to Reproduce:

1. Switch theme to Light High Contrast
2. Open a Javascript file
3. Type `[]]`
4. The final bracket `]` is black, not red as in other themes

**Comment by MichaelMakesGames** [comment]
I believe this may be the core cause:
https://github.com/microsoft/vscode/blob/7c2a097c6a482d70dfb8756ff9f8015357b8a2ed/src/vs/editor/common/core/editorColorRegistry.ts#L83
The value for hcLight here is just an empty string

**Comment by aeschli** [comment]
@MichaelMakesGames Thanks for investigating, looks like this color got forgotten when creating the Light HC theme.
@daviddossett I took the same color as used in the overview ruler
