### ISSUE TITLE
Automatic zen mode option?

### ISSUE THREAD

**Issue by Izacht13** [Microsoft/vscode#22493]
After a configurable timeout of text editing, zen mode may automatically fade in.

(*This is a feature request, how do I tag it? Or can I even?*)

**Comment by isidorn** [comment]
Only team members can add tags.
Thanks for the suggestions however we try to keep automatic UI changes to a minimum.
Will keep this feature request open though.

**Comment by yfdyh000** [comment]
label: extension-candidate if we have the relevant APIs.

**Comment by isidorn** [comment]
I agree this should be done within an extension. The extension can simply call this command on the vscode side when it wants
  "command": "workbench.action.toggleZenMode"
