### ISSUE TITLE
No entry point for @vscode/tree-sitter-wasm assuming dist/@vscode/tree-sitter-wasm.min.js

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#224964]
```
C:\Development\vscode>yarn watch-client
yarn run v1.22.19
$ node --max-old-space-size=4095 ./node_modules/gulp/bin/gulp.js watch-client
[18:36:52] Using gulpfile C:\Development\vscode\gulpfile.js
[18:36:52] Starting 'watch-client'...
[18:36:52] Starting clean-out ...
[18:36:57] Finished clean-out after 4727 ms
[18:36:57] Starting build-web-node-paths ...
No entry point for @vscode/tree-sitter-wasm assuming dist/@vscode/tree-sitter-wasm.min.js
```

**Comment by alexr00** [comment]
@lramos15, does every node module need to have an entry point? I didn't add one when I created this module because I didn't think it needed one. What is this `acquireWebNodePaths` for? 

https://github.com/microsoft/vscode/blob/559107b7a92be2cfda116e3a0667f1b1ac9bf78b/build/lib/util.ts#L394-L395

**Comment by lramos15** [comment]
I believe it is recommended that all modules have an entry point because it tells the bundler where to look. Specifically acquireWebNodePaths is building our module list for the vscode.dev module loader. So this is required for our web experience to work properly.

**Comment by bpasero** [comment]
Just fyi (and this will only become an issue when we move to ESM soon), having trouble to load this module in ESM, I think because it is not self contained. We have a utility method to load AMD modules called `importAMDNodeModule` and that one fails with an error:

```
Error: Cannot resolve dependencies for script vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-esm/node_modules/@vscode/tree-sitter-wasm/wasm/tree-sitter.js. The dependencies are: exports
      at AMDModuleImporter.load (file:///Users/bpasero/Development/Microsoft/vscode-esm/out/vs/amdX.js:79:19)
      at async Context.<anonymous> (file:///Users/bpasero/Development/Microsoft/vscode-esm/out/vs/platform/environment/test/browser/amdX.test.js:23:24)
```

//cc @jrieken

**Comment by jrieken** [comment]
> `The dependencies are: exports`

That might be a fluke and something I can fix in amdX. The exports import is synthetic and something I would be able to support.

**Comment by alexr00** [comment]
Will be fixed by https://github.com/microsoft/vscode/pull/225252.

**Comment by jrieken** [comment]
also fixed by https://github.com/microsoft/vscode/pull/226171
