### ISSUE TITLE
Don't want to see typing errors for plain JavaScript files.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#22491]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.4.0-66-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.7.0|
|EditorConfig|EditorConfig|0.6.1|
|sort-lines|Tyriar|1.2.0|
|vscode-eslint|dbaeumer|1.2.7|
|tslint|eg2|0.8.1|
|cpptools|ms-vscode|0.10.3|
|Spell|seanmcbreen|0.9.1|;

VSCode should be smart enough to know about core JavaScript methods as well as NodeJS methods. The developer should not have to add typings for such things, or create some config settings file.

---

Steps to Reproduce:

1. Edit JavaScript code.
2. See ugly typing errors.

![js-typing-error](https://cloud.githubusercontent.com/assets/439226/23836349/1b5fb722-074d-11e7-92d1-e04f492b2e79.png)

**Comment by mjbvz** [comment]
I can't reproduce thisCan you please share the error message along with the complete file? If you have a `jsconfig.json`, please share that as well.

Also, please make sure this is not extension by running code with `--disable-extensions`

**Comment by rajinder-yadav** [comment]
Closing, with your extension tip, was able to determine it's coming from eslint!
