### ISSUE TITLE
TS+ESLint Slow in latest release, suspect scm history graph

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#224963]
From this thread: https://x.com/naoehtu/status/1820840108624425446

"Not sure what has happened to VSCode + TS + ESLint, but it is become incredibly slow."

1. Go to preferences -> settings
2. on the search settings put ->  scm:show history graph
3. disable the checkbox "Controls whether to render incoming/outgoing ..."

**Comment by lszomoru** [comment]
The "Incoming/Outgoing" section has been removed from the main "Source Control" view.
