### ISSUE TITLE
Hover in package.json does not show package version anymore

### ISSUE THREAD

**Issue by csicky** [microsoft/vscode#224936]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.0
- OS Version: Windows 10 Pro 22H2

Steps to Reproduce:

1. Open package.json
2. Hold mouse over an installed package
3. A tooltip should appear showing the latest version on NPM
4. Nothing happens

**Comment by gjsjohnmurray** [comment]
/duplicate and will be fixed in upcoming recovery release.
