### ISSUE TITLE
Publiish Branch not Publishing to GitHub and loads indefinitely

### ISSUE THREAD

**Issue by Motlakz** [microsoft/vscode#224993]
Type: <b>Bug</b>

When I try to initiate the git commit, it goes through successfully but will not allow me to publish the branch.
even though the repo was initialized, I cannot see it on GitHub or push changes to private or public version of the repo

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (4.53GB free)|
|Process Argv|--crash-reporter-id f8dfee77-d154-4a80-895a-8156c99a60a5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
commit-message-editor|ada|0.25.0
project-manager|ale|12.8.0
vscode-erb-beautify|ali|0.4.3
ng-template|Ang|18.1.2
astro-vscode|ast|2.13.2
tailwind-docs|aus|2.1.0
markdown-preview-github-styles|bie|2.0.4
blackbox|Bla|1.3.71
vscode-tailwindcss|bra|0.12.5
node-snippets|chr|1.3.3
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
vscode-postgres|cko|1.4.3
gitignore|cod|0.9.0
erb|Cra|0.0.1
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|3.0.10
git-extension-pack|don|0.1.3
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.2.3
vscode-html-css|ecm|2.0.10
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|10.4.0
figma-vscode-extension|fig|0.3.5
vscode-firefox-debug|fir|2.9.10
copilot|Git|1.220.0
copilot-chat|Git|0.18.1
vscode-github-actions|git|0.26.3
live-sass|gle|6.1.2
bun-lockb|jaa|0.0.7
search-node-modules|jas|1.3.0
Angular2|joh|18.0.2
vscode-peacock|joh|4.2.2
scss-refactoring|luk|0.1.4
aider|Mat|0.0.9
git-graph|mhu|1.30.0
theme-monokai-pro-vscode|mon|1.3.2
vscode-docker|ms-|1.29.1
vscode-postgresql|ms-|0.3.0
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
live-server|ms-|0.4.14
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
gpt-runner|nic|1.2.9
bun-vscode|ove|0.0.12
prisma|Pri|5.18.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
vs-code-prettier-eslint|rve|6.0.0
nextjs-js-ts-code-snippets|Shi|0.0.1
code-spell-checker|str|3.0.1
iconfont-preview|stx|0.0.5
vscode-stylelint|sty|1.4.0
ts-quickfixes-extension|tam|1.15.0
vscode-css-custom-properties|Toc|0.0.5
vscode-icons|vsc|12.8.0
volar|Vue|2.0.10
wasp|was|0.5.3
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
vscode-react|zha|0.0.5
material-theme|zhu|3.17.2
vscode-open-in-github|ziy|1.3.6
vue|znc|0.12.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
ccplti:31103428
pythonrstrctxt:31103193
wkspc-onlycs-t:31111718
wkspc-ranged-t:31111713

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the suggestion at https://github.com/microsoft/vscode/issues/224916#issuecomment-2270539060 hp?

**Comment by albertosantini** [comment]
@Motlakz Any hint in `output / Git` panel?

**Comment by Motlakz** [comment]
> @Motlakz Any hint in `output / Git` panel?

@albertosantini this is all I see indefinitely. And disabling that graph made no diff
![image](https://github.com/user-attachments/assets/a410dd49-7486-4c75-a7d2-eac899fa1d61)

**Comment by albertosantini** [comment]
I meant here as `output / Git`:
![image](https://github.com/user-attachments/assets/7c122eef-8ff9-4672-aa56-6daf64c297a7)

Just to find an hint (an error) about pushing the branch.

Another approach is trying to push the branch form the command line (not the terminal inside VSCode), just to rule out VSCode from the equation and to verify if git setup is ok.

```
$ git checkout -b <your branch>
...
$ git push -u origin <your branch>
```

Hope this helps.

**Comment by Motlakz** [comment]
Looks like it works now that I manually setup the git repo.

**Comment by lszomoru** [comment]
@Motlakz, are you able to reproduce the issue with a new repository? Could we close this issue? Thanks!

**Comment by Motlakz** [comment]
I haven't encountered this issue since last time. You can close it 😊

**Comment by lszomoru** [comment]
Thanks for the update! Please feel free to reopen the issue if you run into it again.
