### ISSUE TITLE
Automatically delete +1 comments

### ISSUE THREAD

**Issue by devnoname120** [Microsoft/vscode#22495]
Feature requests are riddled with "+1" comments that spam everyone's emails unless notifications are disabled.

I suggest you to use [something like this](https://github.com/keith/vote-knope) to automatically delete them.

**Comment by ZombieProtectionAgency** [comment]
+1

But seriously, I was actually going to recommend that. It seems that no matter how many times people are told they continue to do it. Some issues end up with dozens of them in a row.

I have also seen people justify the +1's saying the developers arent guarenteed to address highly upvoted issues and the extra nagging of email alerts makes them more aware of it. IMO that probably just annoys the developers and distracts them.

**Comment by kieferrm** [comment]
Commenters are pretty good in the meantime to use reactions.  There is no pressing need for us to do this anymore. So, I'll close this as out-of-scope.
