### ISSUE TITLE
Profiles not working on new os(new version?)

### ISSUE THREAD

**Issue by tommasoclini** [microsoft/vscode#224948]
Type: <b>Bug</b>

I've been using vscode profiles since they've been released and I hadn't had any problems.
I had enabled sync settings with my github account and checked the box "Profiles" in the settings sync configuration, yesterday version 1.92 of vscode got released, and I updated, I didn't notice anything wrong in my "old" os, as I didn't use the profiles feature in that particular time.
Today I reinstalled my os, reinstalled vscode, logged in with github, only to discover all of my profiles were empty, the default profile had all of the extensions combined together.
Now the profiles menu doesn't even work anymore, if I try to create a new profile, or edit a profile, I can't select what to customize.

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Linux x64 6.1.0-23-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 2646)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 1, 0|
|Memory (System)|15.41GB (11.60GB free)|
|Process Argv|--crash-reporter-id edbdd506-93f8-4321-a1e3-2f7f74f21314|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by tommasoclini** [comment]
Should I add footage of the bug?

**Comment by naolarega** [comment]
facing similar issue with profile after `vscode 1.92` release, opening new profile menu and try to change a profile to copy from renders the radio buttons under `"chose what to configure in your profile"` useless.

**Comment by tommasoclini** [comment]
That's exactly what happened when trying to do something, every checkbox gets unselected and I can't do anything other than closing the menu.

**Comment by naolarega** [comment]
> That's exactly what happened when trying to do something, every checkbox gets unselected and I can't do anything other than closing the menu.

Still not resolved in `version 1.92.2`

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/224788

Use [New Profiles UI](https://github.com/microsoft/vscode/issues/224788#issuecomment-2274305778) as a workaround.
