### ISSUE TITLE
Method Folding doesn't work correctly

### ISSUE THREAD

**Issue by thewickedaxe** [Microsoft/vscode#22496]
Version 1.10.2
Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
Date 2017-03-08T14:00:46.854Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

Description: Instead of folding methods by mtaching glower brackets , VS code is folding methods by matching indentation in cpp.

Steps to Reproduce:

1. Write a function that is poorly indented. Have a line appear at 0 indentation. 
2. Now try to fold the method, it folds up to that line but not beyond it

Eg method:
```
`std::vector< CurvatureInfo > GetCurvatures( const std::vector< PlyOrientedVertex< float > >& plyVertices , const std::vector< TriangleIndex >& triangles )
{
	std::vector< CurvatureInfo > curvatures( triangles.size() );

	// Compute the principal curvature directions and values
	// (The first principal curvature value/direction should be the one with the largest value)
#pragma message ( "[WARNING] Missing code here" )

	return curvatures;
}`
```

Folding this would fold up to #pragma but not beyond it

**Comment by aeschli** [comment]
Our folding strategy is based on whitespace, not on language constructs. #3422 is the issue for having language based folding regions.
