### ISSUE TITLE
Source code management is always loading

### ISSUE THREAD

**Issue by i4cup** [microsoft/vscode#224916]
Type: <b>Bug</b>

When accessing a git repository remotely via SSH, the source code management has been continuously loading and is unable to display the list of different files.

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 6.5.0-41-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.39GB (15.53GB free)|
|Process Argv|--crash-reporter-id 401892e2-0b53-4a6d-9b5c-4e80fcf96ac9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Linux-NXP-XX|
|OS|Linux x64 6.5.0-41-generic|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 488)|
|Memory (System)|30.98GB (26.90GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|15.2.3
copilot|Git|1.220.0
copilot-chat|Git|0.18.1
linuxkerneldev|mic|0.6.1
vscode-language-pack-zh-hans|MS-|1.92.2024073109
cpptools|ms-|1.21.6
resourcemonitor|mut|1.0.7
remotehub|Git|0.62.0
remote-ssh|ms-|0.112.0
vscode-remote-extensionpack|ms-|0.25.0
azure-repos|ms-|0.38.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
ccplti:31103428
pythonrstrctxtcf:31103194
wkspc-onlycs-c:31106320

```

</details>

**Comment by gjsjohnmurray** [comment]
I suggest you use the Release Notes information to turn  off the new source control graph feature, then let us know if the problem remains.

**Comment by i4cup** [comment]
Thank you very much. The diff file list comes back after disabled "scm.showHistoryGraph".
Sorry, I didn't pay attention to the release note this time. Is it possible that the slow loading issue is due to the large size of my git repository(it's a linux kernel repo with a lot of local changes/branches)?

**Comment by stefnto** [comment]
I'm facing the same issue. I disabled the SCM: Show History Graph checkbox, but source control keeps infinetly loading, breaking both source control and intelisense of VS Code.

**Comment by zhaoYun-Long** [comment]
俺也一样

**Comment by i4cup** [comment]
关了SCM: Show History Graph之后重新载入也不行么

**Comment by aoaim** [comment]
> I suggest you use the Release Notes information to turn off the new source control graph feature, then let us know if the problem remains.

I met the same problem, everything is normal after closing `scm.showHistoryGraph`. Is this a bug in the new version?

**Comment by mazer1310** [comment]
See also #224646

**Comment by lszomoru** [comment]
Closing as duplicate of https://github.com/microsoft/vscode/issues/224646.
