### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by anand-m-s** [microsoft/vscode#224910]
Type: <b>Bug</b>

When using Visual Studio Code, parts of the interface disappear when I hover over them. This happens randomly and affects my ability to interact with the editor.
![Screenshot_20240806_102235](https://github.com/user-attachments/assets/25b38b53-ca3f-4c36-9d28-2428c98415ae)

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.71GB (2.27GB free)|
|Process Argv|--crash-reporter-id d9bf071c-b621-43cb-aca1-651e33b0d506|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
save-typing|akh|0.1.0
vscode-tailwindcss|bra|0.12.5
javascript-ejs-support|Dig|1.3.3
es7-react-js-snippets|dsz|4.4.3
code-runner|for|0.12.2
mongodb-vscode|mon|1.7.0
live-server|ms-|0.4.14
java|red|1.33.0
LiveServer|rit|5.7.9
learn-vim|vin|0.0.28
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.28.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
ccplc:31103425
pythonrstrctxt:31103193
wkspc-onlycs-c:31106320

```

</details>

**Comment by gjsjohnmurray** [comment]
Please launch VS Code from a command prompt using `code --disable-gpu`

**Comment by anand-m-s** [comment]
Thank you for your help! I was able to launch VS Code from a command prompt using code --disable-gpu. Everything works fine now. :)

**Comment by aiday-mar** [comment]
Hi @anand-m-s thank you for the response. I will close the issue.
