### ISSUE TITLE
Cannot use CTRL+Space in package.json file to display npm latest versions in 1.92.0

### ISSUE THREAD

**Issue by Antelope-IT** [microsoft/vscode#224952]
Type: <b>Bug</b>

Prior to VS Code 1.92.0
1) Open package.json file
2) Position cursor at start of npm dependency version number
3) Click CTRL+Space 
As expected a list of latest versions are displayed in a context menu.

Update to VSCode 1.92.0
Repeat steps 1-3 above.
To display a list of random text entries in alphabetical order. No use at all, appears to be a regression

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.28GB free)|
|Process Argv|--crash-reporter-id 077c2d99-c8e9-4910-b914-bac3fbd634f4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|3.0.5
ng-template|Ang|18.1.2
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.3
haskell-nsis|idl|1.1.0
nsis|idl|4.4.0
vscode-docker|ms-|1.29.1
vscode-dotnet-runtime|ms-|2.1.1
vscode-kubernetes-tools|ms-|1.3.16
remote-containers|ms-|0.380.0
remote-wsl|ms-|0.88.2
powershell|ms-|2024.2.2
vscode-js-profile-flame|ms-|1.0.9
vscode-yaml|red|1.15.0
vscode-icons|vsc|12.8.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
ccplti:31103428
pythonrstrctxtcf:31103194
1iic9185:31097392
wkspc-onlycs-c:31106320

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate and will be fixed in upcoming recovery release.
