### ISSUE TITLE
Code Helper Processes eating massive memory, multiplied by workspaces open, causes massive crashes

### ISSUE THREAD

**Issue by VanessaKeeton** [microsoft/vscode#225088]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.0
- OS Version: Mac OS 14.5 and 14.6

Steps to Reproduce:

1. Open VS Code
2. Create several workspaces (include a few multi-root workspaces)
3. Open Activity monitor and note the massive amount of processes with "Code Helper" in the Memory tab
4. If you leave them, your memory will eventually go max and crash everything
5. If you start closing workspaces, you can see it freeing large blocks of memory

This issue started the day of the Update to 1.92.0 and has persisted since. It's crashed my work computer several times a day since, as I do require many workspaces to be open due to lots of micro service repos that I have to edit at once.

![image](https://github.com/user-attachments/assets/ae092f36-21d9-43dd-9aa1-c0d529fc5c8d)

**Comment by gjsjohnmurray** [comment]
Does disabling the `scm.showHistoryGraph` setting help?

**Comment by kjusupov** [comment]
I had similar issue even when `showHistoryGraph` is disabled, with a single (sometimes with 2) Code windows (working on different repositories OR branches):
- VS Code Version: 1.92.0
- OS Version: MacOS Sonoma (v 14.6)
- MacBook Pro (M3 Pro) with 36GB RAM

**Comment by VanessaKeeton** [comment]
@gjsjohnmurray - Disabling `scm.showHistoryGraph` has no discernible effect on this issue.

**Comment by lszomoru** [comment]
@VanessaKeeton, @kjusupov, could you please use [extension bisect tool](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to try to narrow down the extension that is causing the issue.

**Comment by VanessaKeeton** [comment]
> @VanessaKeeton, @kjusupov, could you please use [extension bisect tool](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to try to narrow down the extension that is causing the issue.   

This issue occurs with all extensions disabled.

**Comment by lszomoru** [comment]
@VanessaKeeton, @kjusupov, and to be clear this reproduces with the `scm.showHistoryGraph` setting disabled. 
@deepak1556, could you please advice on collecting a memory dump to investigate the memory consumption? Thanks!

**Comment by VanessaKeeton** [comment]
Yes, that's correct.

**Comment by VanessaKeeton** [comment]
@deepak1556  and @lszomoru - Any word on this as of yet? Still having issues with my computer crashing mid-work nearly every day. It helps to keep activity monitor up to help see when I need to restart vscode but, hard to be looking at it every moment. If I miss it going red, everything just starts shutting down. I had to use two workspaces today and it only took a few mins for it to run up the memory. I've worked for years with many Workspaces open for days at a time and never an issue until recently. 

Also, as far as I know, I'v answered all the question asked on this thread, so not sure why it's still in `info-needed`. Let me know what you might need from me. Thanks!

**Comment by lszomoru** [comment]
@VanessaKeeton, I was wondering if you are able to reproduce this with the latest VS Code Insiders and all extensions disabled?

**Comment by deepak1556** [comment]
Sorry for the delay here, `Code Helper (Plugin)` executable is used for all our different utility processes that serve varying purposes like file watching, extension host etc. It would be helpful to first narrow down the type of process that is causing the issue,

@VanessaKeeton please open the process explorer from VSCode `Help > Open Process Explorer` and right click on the process that is showing increased memory usage, copy the details to this issue.

**Comment by VanessaKeeton** [comment]
@deepak1556 It seems like the Process Explorer doesn't show the whole picture because it doesn't match the memory consumption shown by activity monitor. Here is a screen shot of the difference. 

<img width="1759" alt="image" src="https://github.com/user-attachments/assets/fbe5c19d-7c6e-4833-9605-1bd6aa2369c0">

@lszomoru - I will get back to you. I am just downloading Insiders and will try using it for a few hours and let you know how it goes.

**Comment by VanessaKeeton** [comment]
@lszomoru and @deepak1556 - I've been going between the latest release and Insiders this past week and, tho memory consumption is still high on both, the crashing has seemed to stop with both. This is both without any extensions (felt like I was coding in a time machine for a couple of days, lol) and with my normal batch of extensions enabled. So perhaps whatever caused this has been fixed. Thank you.
