### ISSUE TITLE
I can't see the git "Stash Staged" option

### ISSUE THREAD

**Issue by BraveNewWord** [microsoft/vscode#225019]
Type: <b>Bug</b>

I can't see the git "Stash Staged" option

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:

```[tasklist]
### Tasks
```

**Comment by BraveNewWord** [comment]
![image](https://github.com/user-attachments/assets/f4b6cc5b-dfa6-444f-8fdb-04c93f990a59)

**Comment by albertosantini** [comment]
Here I have git `2.46` and VSCode `1.92` (Windows)

![image](https://github.com/user-attachments/assets/b68fe699-e7b3-45fd-942d-948fbb3ac205)

**Comment by BraveNewWord** [comment]
OK @albertosantini I updated git and I can see it now thanks 👍

**Comment by albertosantini** [comment]
The feature `git stash push --staged` is only supported since `2.35` release.
