### ISSUE TITLE
Allow to select multiple items in the EXPLORER window to copy/paste

### ISSUE THREAD

**Issue by cateyes99** [Microsoft/vscode#22503]
- VSCode Version: 1.10.2
- OS Version:
 OS Name:     Mac OS X
 OS Version:  10.11.3
 OS Platform: Darwin
 RID:         osx.10.11-x64

Steps to Reproduce:

1. In the EXPLORER window, currently it allows to select only one item for copy/paste
2. It'd more convenient if it allows us to select multiple items for copy/paste :)

**Comment by kaiwood** [comment]
https://github.com/Microsoft/vscode/issues/1023

**Comment by weinand** [comment]
dup of #1023
