### ISSUE TITLE
Feature request: compare with clipboard

### ISSUE THREAD

**Issue by javahaxxor** [Microsoft/vscode#22508]
As in IntelliJ IDEA I'd like to compare a section of a file with what's in the clipboard. 

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 3.16.0-4-amd64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|indenticator|SirTori|0.2.1|
|html-css-class-completion|Zignd|1.0.3|
|vscode-eslint|dbaeumer|1.2.7|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.0.33|
|backbone-js-snippets|ioanaapetrei|0.0.1|
|debugger-for-chrome|msjsdiag|2.6.0|
|better-merge|pprice|0.5.1|
|diff|rafaelmaiolla|0.0.1|
|stylelint|shinnn|0.23.0|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by javahaxxor** [comment]
I saw that other issue it was about comparing a file. I was thinking about a section
