### ISSUE TITLE
Blank lines inserted when formatting html files

### ISSUE THREAD

**Issue by DavidBetteridge** [Microsoft/vscode#22507]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-refresh-html|bajdzis|0.0.2|
|vscode-instant-markdown|dbankier|0.2.0|
|python|donjayamanne|0.5.5|
|vscode-npm-script|eg2|0.1.8|
|mssql|ms-mssql|0.1.5|
|csharp|ms-vscode|1.7.0|;

---

Steps to Reproduce:

1. Edit an html file which includes css within a <style> element
2. Press Left Alt + Shift + F to format the document
3. A blank line is inserted between each of the sections in the style element
4. Repeating step 2 inserts an additional line and so on

**Comment by weinand** [comment]
I think this has been fixed in VS Code 1.10.2.
See https://github.com/Microsoft/vscode/issues/21717
Please verify!

**Comment by DavidBetteridge** [comment]
You are correct.  Just upgraded  from 1.10.1 to 1.10.2 and it now works
correctly.

Thanks

**Comment by weinand** [comment]
@DavidBetteridge Thanks for verifying.
