### ISSUE TITLE
JS/TS language features doesn't works

### ISSUE THREAD

**Issue by Gustavo-maia-gst** [microsoft/vscode#225094]
Type: <b>Bug</b>

Just open vscode, the extension starts loading and never finishs

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.94GB (5.92GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Arch/home/gustavo/SplitC/backend --remote=wsl+Arch --crash-reporter-id 24d2b984-2098-435a-9df5-fb4eb1b2ea07|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Arch|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (5 x 0)|
|Memory (System)|9.72GB (7.77GB free)|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.27.1
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vim|vsc|1.27.3
JavaScriptSnippets|xab|1.8.0
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
clang-format-indent-4|dem|1.10.13
competitive-programming-helper|Div|2024.7.1722430096
c-cpp-runner|fra|9.4.8
go|gol|0.42.0
vscode-edit-csv|jan|0.9.2
search-node-modules|jas|1.3.0
rainbow-csv|mec|3.12.0
vscode-docker|ms-|1.29.1
playwright|ms-|1.1.7
debugpy|ms-|2024.10.0
python|ms-|2024.12.2
vscode-pylance|ms-|2024.8.1
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
vscode-typescript-next|ms-|5.6.20240806
vsliveshare|ms-|1.0.5936
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
ccplt:31103426
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31111713

```

</details>

**Comment by HananINouman** [comment]
any updates?
