### ISSUE TITLE
Better reasoning in error messages thrown by the chat copilot model

### ISSUE THREAD

**Issue by alenakhineika** [microsoft/vscode#225057]
When sending a message to Copilot that exceeds models' context window, the error doesn't not include the real reason of the failure.

```ts
const userMessage = vscode.LanguageModelChatMessage.User('Text bigger than the context window');
// userMessage.content.length eql 137489
try {
  const [model] = await vscode.lm.selectChatModels({
  vendor: 'copilot',
  family: 'gpt-4o',
});
if (model) {
  const chatResponse = await model.sendRequest([userMessage], {}, token);
} catch (err) {}
```

The expected message would be about the prompt being too long.

The actual error message:
```
Error: Prompt failed validation with the reason: No messages provided. Please file an issue.
    at nk._provideLanguageModelResponse (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.19.2024080701/dist/extension.js:736:4851)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Another error that would be useful to differentiate is "too many requests" in case a user hits rate limits.

**Comment by lramos15** [comment]
Not shown because the fix is in a private repo but the error message should be better here now 👍

**Comment by alenakhineika** [comment]
In which Insiders version should be the fix?

I am on  `1.93.0-insider` and found a vise versa case, when you send a message to the model and it contains only the Assistant prompt without  the User prompt, the error from the model says:

```
Error: Sorry, this message is too long. Please try a shorter question.
    at Ge.render (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.20.2024081201/dist/extension.js:141:7037)
    at nk._provideLanguageModelResponse (/Users/alena.khineika/.vscode-insiders/extensions/github.copilot-chat-0.20.2024081201/dist/extension.js:737:3828)
```

Note, that the Assistant prompt is actually short, e.g. 500 characters.

**Comment by lramos15** [comment]
Is just an assistant message considered a valid prompt by Open AI? I don't think it is. But yeah that's not a great error message either

**Comment by alenakhineika** [comment]
Hmm it looks like it can be possible to send just an assistant message https://platform.openai.com/docs/api-reference/messages. I can't find the user message marked required anywhere.
