### ISSUE TITLE
Editor input

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2250]
- [x] mac @weinand 
- [x] linux @aeschli 
- [x] windows @chrisdias 

Please test the following input methods:

- Japanese. Add the Japanese keyboard layout and switch it to get Hiragana. Then type for example "sennsei" or "konnichiha" or "mikann". Check that you can see the composition being built and also try to choose other suggestions

- UniKey Vietnamese. Please see #1168

- Mac: Please try the "hold" input method where you long press "e" and get all other variants

- Mac: Please try the emoji inserter

- Chinese. Please try typing `.` or `,` in full width form

**Comment by weinand** [comment]
@alexandrudima I couldn't test "UniKey" on OS X because it doesn't exist but all the Vietnamese input methods (including drawing shapes on the trackpad ;-) seem to work fine.

**Comment by alexandrudima** [comment]
@weinand Awesome! Thank you :heart:

**Comment by aeschli** [comment]
On Linux I tested the Japanese input methods with [mozc](https://wiki.archlinux.org/index.php/Mozc). It seems to work, but I lack knowledge of Japanese.

**Comment by aeschli** [comment]
I wasn't able to verify UniKey Vietnamese and Chinese on Linux. I tried
http://elementaryos.stackexchange.com/questions/1431/install-ibus-on-freya
but switching never had an impact (also not on other applications).

**Comment by chrisdias** [comment]
#### Windows
###### Japanese

![image](https://cloud.githubusercontent.com/assets/1487073/12599036/6fd31de2-c443-11e5-9fc4-d6fb75920595.png)

###### Vietnamese

I could not get UniKey to do anything when it was on.  I followed the instructions above and make sure my settings looked identical.  I did however change the keyboard to Vietnamese QWERTY and i was able to see additional characters in the editor.

###### Chinese

I think it worked for simplified Chinese?

![image](https://cloud.githubusercontent.com/assets/1487073/12599438/b89de1c6-c446-11e5-8d23-b36b3ebaada9.png)

(picture also includes the Vietnamese text i was trying to type)

**Comment by alexandrudima** [comment]
@aeschli @chrisdias Thank you!

**Comment by alexandrudima** [comment]
For posterity:
* switch to Korean input
* Press g k s r m f (it should be "한글")
* Press space
* You should get "한글"
