### ISSUE TITLE
Debug incorrect on version 1.91.1 and 1.92

### ISSUE THREAD

**Issue by leonkong** [microsoft/vscode#225008]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.91.1 and 1.92
- OS Version:  macOS 12.7.5

Steps to Reproduce:

1. Open my project, set breakpoint, and move mouse cursor on one variable.
2. Always display 'undefined'.
3. But in WATCH area, it displays correct value.

Downupgrade to version 1.90, move mouse cursor on one variable and display a value same to WATCH area.

<img width="522" alt="image" src="https://github.com/user-attachments/assets/b1c91894-d081-4159-b400-2a4cfda3ffd9">
<img width="333" alt="image" src="https://github.com/user-attachments/assets/898e545c-98be-4a69-aca0-55f61e9bfd85">
<img width="300" alt="image" src="https://github.com/user-attachments/assets/f27222ef-d959-4155-99fb-3385548a9ce3">

**Comment by leandro-pineapple-lab** [comment]
Please solve this issue !

**Comment by connor4312** [comment]
Should be fixed on nightly already: https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension
