### ISSUE TITLE
Cannot open remote ssh terminal with VSCode 1.92

### ISSUE THREAD

**Issue by lyyyuna** [microsoft/vscode#225004]
- VS Code Version: 1.92
- OS Version: macOS 14.3.1 
- Remote OS Version: Ubuntu 22.04.4

After I upgrade to 1.92, I cannot open terminial on my remote machine. Steps to Reproduce:

1. I use remote ssh to connect to my working machine. 
2. I can edit and save my remote file normally, however, the default terminal shows nothing.
3. I click 'New terminal', still shows nothing.

![image](https://github.com/user-attachments/assets/3bcf8b1a-1498-4cb9-8383-01abd07d078b)

No error pops, and I can reproduce this issue on my another mac with vscode 1.92.

**Comment by deepak1556** [comment]
Can you share the remote logs

**Comment by lyyyuna** [comment]
When i click 'New terminal', the remote ubuntu ssh log shows nothing, but the local dev tool shows

![image](https://github.com/user-attachments/assets/de593776-9bb3-4a63-bede-ebd5c8823f37)

**Comment by deepak1556** [comment]
@Tyriar can you point to how additional terminal logs can be obtained

**Comment by lyyyuna** [comment]
after upgrade to 1.92.1, the bug fixed.
