### ISSUE TITLE
Double or Triple click an inactive pane too quickly cause it to not select accordingly

### ISSUE THREAD

**Issue by hyouuu** [microsoft/vscode#225015]
Type: <b>Bug</b>

I use 2 panes side by side, and say if the left pane is in focus and I try to double click on a word to select it on the right pane, then if I manually double click it works, but if I use Logitech Mouse's double click action then it would appear to be selected first then quickly get deselected (same for triple click action). 

It seems to be that the selection worked initially then there's a delayed focus event which causes selection to be lost, as using the action to select stuff in an already focused pane works fine.

VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|64.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id a82f9e15-b4dd-4142-9761-a3d9487fba5d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-neovim|asv|1.18.7
dart-import-sorter|azi|0.3.3
ccs-flutter-color|cir|1.2.5
dart-code|Dar|3.94.0
flutter|Dar|3.94.0
flutter-auto-import|dav|0.0.1
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
gdscript-formatter-linter|Edd|1.3.1
prettier-vscode|esb|10.4.0
vscode-expo-tools|exp|1.5.0
vscode-yarn|gam|2.1.0
godot-tools|gee|2.1.0
vscode-react-typescript|inf|1.3.1
dart-import|lua|0.3.1
import-sorter|mik|3.3.1
vscode-react-native|msj|1.13.0
auto-semicolon-vscode|mya|1.5.2
tsimporter|pmn|2.0.1
autoimport|ste|1.5.4
vscode-gradle|vsc|3.16.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
f8hc8238:30694864
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
ccpltc:31103427
pythonrstrctxtcf:31103194
wkspc-onlycs-c:31106320

```

</details>

**Comment by bpasero** [comment]
I do not think that a change in VS Code would be possible here to make your custom mouse logic work. We implement mouse events over standard DOM APIs and so maybe this custom mouse logic does not result in the right set of events.

Does it reproduce on https://microsoft.github.io/monaco-editor/playground.html?source=v0.50.0#example-creating-the-editor-hello-world in a browser?

**Comment by bpasero** [comment]
I do not know what kind of delay we need to remove.

**Comment by bpasero** [comment]
I am closing this as unplanned given it involves a special mouse, which maybe makes it then worse for other people.
