### ISSUE TITLE
Viewing flame graph without flame graph extension installed searches marketplace for id:null

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#225059]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:
0. Ensure you don't have the flame graph extension installed
1.  Open a CPU profile
2. Click the flame icon
3. 🐛 Extension view opens with a search for `@id:null`

**Comment by jeanp413** [comment]
Upstream PR https://github.com/microsoft/vscode-js-profile-visualizer/pull/186
