### ISSUE TITLE
Cannot create another instance when there's already one instance ran as administrator

### ISSUE THREAD

**Issue by whizkidwwe1217** [Microsoft/vscode#22502]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.0|
|vscode-icontheme-nomo-dark|be5invis|1.0.11|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.0.3|
|githistory|donjayamanne|0.1.0|
|vscode-todo-parser|minhthai|1.8.6|
|mssql|ms-mssql|0.2.1|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.8.0|
|debugger-for-chrome|msjsdiag|2.5.1|
|material-icon-theme|PKief|1.0.3|
|vscode-icons|robertohuertasm|3.0.0|
|Spell|seanmcbreen|0.8.6|;

---

Steps to Reproduce:

Option 1:
1. Run VS Code as Administrator.
2. Run another instance.

Option 2:
1.Run a normal instance.
2. Run another instance as Administrator.

Issue: Not creating another instance.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
