### ISSUE TITLE
The JS/TS language service immediately crashed 5 times.

### ISSUE THREAD

**Issue by vhenri** [microsoft/vscode#225078]
Type: <b>Bug</b>

1. Connect to codespaces 
2. Open a ts or tsx file
3. Explorer takes min 5 minutes to load. 
4. See "The JS/TS language service immediately crashed 5 times." error

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin arm64 23.1.0
Modes:
Remote OS version: Linux x64 6.5.0-1022-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 8064a14d-b4c1-4fba-ab61-8b069e9a3b5e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: sturdy halibut|
|OS|Linux x64 6.5.0-1022-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (8 x 0)|
|Memory (System)|31.33GB (14.93GB free)|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
vsc-material-theme|Equ|34.4.0
vsc-material-theme-icons|equ|3.7.0
codespaces|Git|1.17.2
remote-containers|ms-|0.380.0
vscode-todo-highlight|way|1.0.5
cucumberautocomplete|ale|3.0.5
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.3
prettier-vscode|esb|10.4.0
vscode-jest-runner|fir|0.4.73
auto-rename-tag|for|0.1.10
codespaces|Git|1.17.2
copilot|Git|1.220.0
copilot-chat|Git|0.18.1
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.94.0
go|gol|0.42.0
rest-client|hum|0.25.1
vscode-docker|ms-|1.29.1
playwright|ms-|1.1.7
debugpy|ms-|2024.10.0
python|ms-|2024.12.2
vscode-pylance|ms-|2024.8.1
cpptools|ms-|1.21.6
makefile-tools|ms-|0.9.10
trailing-spaces|sha|0.4.1
vscode-import-cost|wix|3.3.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
ccpltc:31103427
pythonrstrctxtcf:31103194
wkspc-onlycs-t:31111718
wkspc-ranged-c:31111712

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
