### ISSUE TITLE
Contents of closed editor window leaks into Task Manager

### ISSUE THREAD

**Issue by OlafCorp** [microsoft/vscode#225022]
![Screenshot 2024-08-07 091430](https://github.com/user-attachments/assets/54d508fb-1fed-4c5f-8a98-a999d1d9f783)
Type: <b>Bug</b>

1) Create and edit a new file
2) Close file without saving
3) [Did other work, unsure of actual steps]
4) Reopen VSCode
5) Content of previously closed window is shown as part of the process information

The content that was in the editor window was this:
"4.4.11", "4.4.7", "5.1.10", "5.3.0", "5.4.300"

It could have been something confidential, thus I think this issue should be handled as if sensitive content leaked.

I will add screenshot afterwards if allowed

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes: Restricted

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.83GB (14.99GB free)|
|Process Argv|--crash-reporter-id e24f9795-11dc-43c0-9ca4-64214636ba6f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bpasero** [comment]
This is configurable via the `workbench.editor.untitled.labelFormat` setting. You can set it to `name` to prevent this.

By default we put the first line contents of untitled editors as the name of the editor and the name of the editor is reflected in the window title. Alternatively you can also change the window title via the `window.title` setting.

**Comment by OlafCorp** [comment]
The content was still showing in Task Manager **after** the editor window was closed (see screenshot). I would expect that to go away then. It also looks like the content got into the top level process node, which I guess is also not expected.

**Comment by OlafCorp** [comment]
Should I rather open a Windows bug then? I'm running 22631.3958, which has the revised app.

**Comment by bpasero** [comment]
That would be great!

**Comment by OlafCorp** [comment]
Done
