### ISSUE TITLE
Add more styles to the matching bracket

### ISSUE THREAD

**Issue by cesaraaron** [microsoft/vscode#22504]
Like an underline:

![1](https://cloud.githubusercontent.com/assets/20180899/23841487/5c12e5b6-0773-11e7-8c26-9fbb3f534d08.PNG)
![captura](https://cloud.githubusercontent.com/assets/20180899/23841537/a96e9d1e-0773-11e7-9b3f-80eb9346e94e.PNG)

...or at least give an option to desactive it please.

**Comment by kanlukasz** [comment]
It could be merge with this -> #46804

**Comment by alexandrudima** [comment]
:+1: Let's track in #46804
