### ISSUE TITLE
New 1.92 Git Terminal shell integration not working

### ISSUE THREAD

**Issue by dkarkar92** [microsoft/vscode#225068]
Type: <b>Bug</b>

If I run `git status` and it resolves to two changed files, my VS Code "Source Control" tab / panel does not get updated. It continues to show the old / outdated files. 

I don't know if `git status` is working with the new terminal shell integration feature or not. But in my uses the past few days it has never worked. 

VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 6, 6|
|Memory (System)|32.00GB (0.91GB free)|
|Process Argv|--crash-reporter-id 26939c27-51ad-40b3-9738-8fd505806d6d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
turbo-console-log|Cha|2.10.4
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.3
vscode-jest-runner|fir|0.4.73
vscode-monorepo-workspace|fol|1.3.1
copilot|Git|1.220.0
copilot-chat|Git|0.18.1
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.94.0
vscode-peacock|joh|4.2.2
vscode-colorize|kam|0.11.1
template-string-converter|meg|0.6.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vsliveshare|ms-|1.0.5936
angular-console|nrw|18.25.0
material-icon-theme|PKi|5.8.0
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
partial-diff|ryu|1.4.3
es6-string-html|Tob|2.16.0
vscode-sort-package-json|uni|1.5.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-icons|vsc|12.8.0
vscode-todo-highlight|way|1.0.5
pretty-ts-errors|Yoa|0.6.0
material-theme|zhu|3.17.2

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
ccplc:31103425
pythonrstrctxt:31103193
wkspc-onlycs-c:31106320

```

</details>

**Comment by Tyriar** [comment]
It's likely unrelated to the new feature

**Comment by tberghuis** [comment]
I noticed that with 1.92 if I manually run git commands in the terminal, I need to manually refresh source control panel, it used to refresh automatically.

EndeavourOS
