### ISSUE TITLE
Integration tests are crashing intermittently

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#225074]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=287025
Changes: https://github.com/Microsoft/vscode/compare/3fc6de2...b5300cb

We've seen an uptick of integration test failures with the same symptom. Both on Linux and on Windows.

Linux:
```
Extension host test runner exit code: 0
Asking native host service to exit with code 0.
[main 2024-08-07T16:57:45.208Z] Extension host with pid 22955 exited with code: 0, signal: unknown.
Exit code:   SIGSEGV
SIGSEGV
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

##[error]Bash exited with code '1'.
Finishing: Run integration tests (Electron)
```

Windows:
```
Extension host test runner exit code: 0
Asking native host service to exit with code 0.
[main 2024-08-07T11:26:35.732Z] Extension host with pid 932 exited with code: 0, signal: unknown.
Exit code:   3221225477
Failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exec: 
At D:\a\_work\1\s\build\azure-pipelines\win32\exec.ps1:22 char:3
+         throw ("Exec: " + $errorMessage)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Exec: :String) [], RuntimeException
    + FullyQualifiedErrorId : Exec: 
```

Other builds:
* https://dev.azure.com/monacotools/Monaco/_build/results?buildId=286975&view=logs&j=0304f796-6596-5b42-8573-3d5da85bc4a5&s=27eddb93-7805-576c-c80f-37b2176e40f7&t=1a53f334-c977-530c-cec1-ac39ef9d774a&l=1798
* https://dev.azure.com/monacotools/Monaco/_build/results?buildId=286975&view=logs&j=0304f796-6596-5b42-8573-3d5da85bc4a5&s=27eddb93-7805-576c-c80f-37b2176e40f7&t=1a53f334-c977-530c-cec1-ac39ef9d774a&l=1798

**Comment by bpasero** [comment]
We do automated crash detection in integration and smoke tests and attach crash dumps to the build:



![Image](https://github.com/user-attachments/assets/a90d1aa1-9845-45d7-a8e8-343a6ba974ff)

Crashes we have here:
* Crash dump A: [link](https://artprodeus21.artifacts.visualstudio.com/A341001b6-62a6-4d7e-aa61-779aea3de100/a6d41577-0fa3-498e-af22-257312ff0545/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21vbmFjb3Rvb2xzL3Byb2plY3RJZC9hNmQ0MTU3Ny0wZmEzLTQ5OGUtYWYyMi0yNTczMTJmZjA1NDUvYnVpbGRJZC8yODcwMjUvYXJ0aWZhY3ROYW1lL2NyYXNoLWR1bXAtbGludXgteDY0LWludGVncmF0aW9uLTE1/content?format=zip&subPath=%2Fpending)
* Crash dump B: [link](https://artprodeus21.artifacts.visualstudio.com/A341001b6-62a6-4d7e-aa61-779aea3de100/a6d41577-0fa3-498e-af22-257312ff0545/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21vbmFjb3Rvb2xzL3Byb2plY3RJZC9hNmQ0MTU3Ny0wZmEzLTQ5OGUtYWYyMi0yNTczMTJmZjA1NDUvYnVpbGRJZC8yODY5NzUvYXJ0aWZhY3ROYW1lL2NyYXNoLWR1bXAtd2luZG93cy14NjQtaW50ZWdyYXRpb24tMQ2/content?format=zip&subPath=%2Freports)
* Crash dump C: [link](https://artprodeus21.artifacts.visualstudio.com/A341001b6-62a6-4d7e-aa61-779aea3de100/a6d41577-0fa3-498e-af22-257312ff0545/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21vbmFjb3Rvb2xzL3Byb2plY3RJZC9hNmQ0MTU3Ny0wZmEzLTQ5OGUtYWYyMi0yNTczMTJmZjA1NDUvYnVpbGRJZC8yODY5NzUvYXJ0aWZhY3ROYW1lL2NyYXNoLWR1bXAtd2luZG93cy14NjQtaW50ZWdyYXRpb24tMQ2/content?format=zip&subPath=%2Freports)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/192119
