### ISSUE TITLE
Terminal lateral margins too big + option to disable scrollbar in terminal

### ISSUE THREAD

**Issue by pasquale95** [microsoft/vscode#225052]
Hi, after the latest update the terminal has a very big margin which eats useful space within the terminal itself. In addition, also the scrollbar is now wider and eats more space, especially when I start splitting the terminal with 2 or more instances. 
It would be great if:
- the lateral margins of the terminal could be decreased; 
- an option to disable the scrollbar in the terminal could be added or, alternatively, an option to handle the scrollbar width in the same way it exists already for the scrollbar in the editor (`editor.scrollbar.verticalScrollbarSize`). 

The reason of such request is that the space in the terminal is limited, especially when working on a laptop without external monitor. Therefore I believe the terminal space should be carefully used:

<img width="1684" alt="Screenshot 2024-08-07 at 14 12 12" src="https://github.com/user-attachments/assets/08a5391f-b4a1-4533-8104-72fbc35945ff">

Moreover, I see that as soon as I split the terminal (where also the margins are too big) and I close one of the two terminals, the margin on the right gets reduced if compared to the same margin before performing the split:

<img width="1686" alt="Screenshot 2024-08-07 at 14 13 06" src="https://github.com/user-attachments/assets/e4a36695-5708-4853-a79c-c1e13178e7a9">

This sounds as a bug.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92
- OS Version: macOS Sonoma 14.5

Steps to Reproduce:

1. Open the terminal in VSCode:
<img width="1684" alt="Screenshot 2024-08-07 at 14 12 12" src="https://github.com/user-attachments/assets/4aebb56e-6cce-47c8-8a9e-f6e794661ae4">
2. Split the terminal in 2 parts:
<img width="1680" alt="Screenshot 2024-08-07 at 14 12 47" src="https://github.com/user-attachments/assets/a470e1c0-a704-44ad-a13c-4ab2cdbcd4ad">
3: Close one of the 2 terminals and look at the margin on the right:
<img width="1686" alt="Screenshot 2024-08-07 at 14 13 06" src="https://github.com/user-attachments/assets/935806a8-c767-4e3c-a3de-7f64f7edbbbb">

**Comment by legomushroom** [comment]
Hi @pasquale95, wasn't able to repro this today on stable 1.96.0 with zsh shell, do you still see the issue on your side? Also, what theme you are using? It could be related to the theme or other settings you are using 🤔

**Comment by Tyriar** [comment]
We've fixed bugs around the right margin being wrong so terminals get more space. We don't have plans to add a setting around terminal padding.
