### ISSUE TITLE
My vs interface is stuck

### ISSUE THREAD

**Issue by isadelarranaga** [microsoft/vscode#225007]
ADD ISSUE DESCRIPTION HERE
I ran the update50 prompt and it hasn't stopped loading since. 
Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
