### ISSUE TITLE
Name of temporary table (SQL Server) show up like commentary

### ISSUE THREAD

**Issue by helisoncruz** [microsoft/vscode#225047]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.0
- OS Version:  Windows 10 Pro 22H2

Steps to Reproduce:

1.  I'm using Sql Server with PHP in VS Code, when I need to create temporary tables as in the example below, part of the SQL looks like it was commented out.  `$sql = "SELECT * INTO #g2 FROM my_table";`

2.  This part here `#g2 FROM my_table` is all grayed out, as if it were a normal comment, is there any way to disable this just for the SQL context?

**Comment by RedCMD** [comment]
when using language `MS SQL` or installing the `sql server` extension
I'm not seeing anything commented out
![Image](https://github.com/user-attachments/assets/51d3ed45-7cc2-43d8-b923-643b6a60b48b)
