### ISSUE TITLE
Incorrect Incoming/outgoing history graph

### ISSUE THREAD

**Issue by chunlampang** [microsoft/vscode#225099]
![image](https://github.com/user-attachments/assets/72bacdeb-b578-4e3c-9993-496d4885d178)

**Comment by lszomoru** [comment]
@chunlampang, thank you very much for filing this issue. Could you please share more on your development flow:
- what is the default branch of your repository? 
- are you pushing your changes to the default branch of your repository?

**Comment by chunlampang** [comment]
The default branch is `main`. The branch in the cap screen is `develop`
The graph in bitbucket is just a straight line
![image](https://github.com/user-attachments/assets/864398cf-678a-47e3-b818-5d337792b5ea)

**Comment by chunlampang** [comment]
When I click on the item inside the history graph, it just show "No Changed Files" in 1 second and then become blank.

**Comment by chunlampang** [comment]
The graph still showing even the branch synchronized.
