### ISSUE TITLE
I'm facing trouble in reformatting source code lines.

### ISSUE THREAD

**Issue by sundarkid** [Microsoft/vscode#22505]
Having trouble in reformatting source python code using the the shortcut.

getting the prompt to even though the terminal tells already installed.
<img width="673" alt="errot-in-vsc" src="https://cloud.githubusercontent.com/assets/10157957/23842982/95e384e2-07de-11e7-94bd-1b366473a929.PNG">

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|Python-autopep8|himanoa|1.0.2|
|ftp-simple|humy2833|0.4.15|
|intellij-idea-keybindings|k--kato|0.2.10|
|MagicPython|magicstack|1.0.7|
|vscode-docker|PeterJausovec|0.0.12|
|partial-diff|ryu1kn|0.2.0|
|python|tht13|0.2.3|
|python-extended-snippets|tushortz|0.0.1|;

**Comment by weinand** [comment]
@sundarkid please create this issue against the Python-autopep8 extension project.
