### ISSUE TITLE
`yarn watch` does not compile changes

### ISSUE THREAD

**Issue by rjra2611** [microsoft/vscode#225077]
When working with Development container. `yarn watch` does not seem to be working. 

```
node -v
v20.15.0

yarn -v
1.22.22
```

![animation](https://github.com/user-attachments/assets/b0547e1f-decb-4a82-8c9f-d0c1650ce099)

**Comment by roblourens** [comment]
I guess this would be a problem with the watcher in your build script?

**Comment by IllusionMH** [comment]
Of you mount sources to container as mount/volume then you might need watcher that doesn't rely on system events
