### ISSUE TITLE
Unable to drag and drop files from Explorer to VSCode

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#225030]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
- OS Version: W11

Steps to Reproduce:
https://github.com/microsoft/vscode/issues/38999
https://github.com/microsoft/vscode/issues/219047
https://github.com/microsoft/vscode/issues/182300
1.  I not resolved problem
2. I have also shortcut with config as "as administrator"

**Comment by lramos15** [comment]
Can you try 1.92. And does this only happen when you have as an administrator configured?

**Comment by ManPython** [comment]
This same on:
`
Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
`

**Comment by lramos15** [comment]
This is not fixable by VS Code as described in https://github.com/microsoft/vscode/issues/38999#issuecomment-790146428

**Comment by ManPython** [comment]
Why? Early version worked normaly for me.. this is crazy explanation.

**Comment by lramos15** [comment]
Previous versions allowed you to drag and drop from the windows explorer to a VS Code instance running as administrator?

Does drag and drop still work in current versions when not running as an admin?

**Comment by ManPython** [comment]
As administrator and as not administrator.. allowed time ago but new version not.. 
So before my last reports around it works normally.. how to explain as not possible if other electron apps have this feature..

**Comment by lramos15** [comment]
Drag and drop should definitely work if not an administrator. Can you attach a screen recording?

**Comment by ManPython** [comment]
Are you joking.. stupid case.. to show well know stop icon on VSC gui and tabs. I installed new VSC and this problem is from long time..

**Comment by lramos15** [comment]
My coworkers and I cannot reproduce this issue using the information you've provided in the top of the issue. I am merely requesting a recording to see if I can glean any additional information from the recording about what is going on

**Comment by ManPython** [comment]
Dont want waste time for this records and care about sensitive data etc.

**Comment by ManPython** [comment]
Prepare some steps to return right logs maybe..

**Comment by ManPython** [comment]
Strange.. on other computer and OS this same portable version not doing problems when not administrator. But when not administrator the problems with python debug.. or cmd terminal operations, eg. pip install etc.. crazy..

**Comment by ManPython** [comment]
This is crazy.. if not administrator then Git is limited around functionality to commit etc..
