### ISSUE TITLE
Input Chiness with Microsoft input method

### ISSUE THREAD

**Issue by jmtian** [Microsoft/vscode#22501]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-css-formatter|aeschli|0.0.2|
|python|donjayamanne|0.5.9|
|vscode-emacs|hiro-sun|0.1.1|
|prettify-json|mohsen1|0.0.3|
|cpptools|ms-vscode|0.10.2|
|csharp|ms-vscode|1.5.1|
|RustyCode|saviorisdead|0.19.1|
|switch-corresponding|tomhultonharrop|0.1.2|
|cmake|twxs|0.0.17|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

When I use Microsoft input method to enter Chinese, an extra letter will appear before the word.

![vscode-bug](https://cloud.githubusercontent.com/assets/1918754/23838938/5887d9d0-07d5-11e7-8877-0028667fa330.png)
![vscode-bug2](https://cloud.githubusercontent.com/assets/1918754/23838968/8eb61bd4-07d5-11e7-9cc5-1e73c4d435ec.png)

**Comment by alexandrudima** [comment]
@rebornix Can you please take a look

**Comment by rebornix** [comment]
@jmtian can you tell me what version of Windows you are using and can you reproduce this issue by disabling all extensions?

**Comment by rebornix** [comment]
Can not reproduce with latest Insider version on Windows 10. Close it first and let me know if you still run into it.
