### ISSUE TITLE
FR: Disable Syntax Highlighting Permanently or On-Demand

### ISSUE THREAD

**Issue by matttproud** [microsoft/vscode#225138]
I would like Visual Studio Code to have the capability to disable syntax highlighting permanently or on demand, and I would like this capability to be decoupled from the user's theme, meaning it shows the file content in whatever form plain text takes for the given theme.

I've seen several workarounds described, but they are all subpar:

* [use a custom theme that effectively has no stylization](https://stackoverflow.com/a/43713187): I might like the theme I am using and don't want to duplicate it (or know how to) to override the myriad color palette settings.
* [reassign the `files.associations` to `plaintext`](https://stackoverflow.com/a/57160455): When this is done, various features that are specific to Visual Studio Code recognizing the file type break down (e.g., [document formatting](https://stackoverflow.com/a/78846743)).

I very much value being able to work on source code in a low noise context and don't need for it to light up in an editor like a Christmas tree.  I respect that other people may like that, but I don't.

**Comment by RedCMD** [comment]
you could set `"editor.maxTokenizationLineLength"` to `0`

or disable all the `@builtin` Basics extensions
![image](https://github.com/user-attachments/assets/c926f741-d538-448c-b452-64be2f78a791)
