### ISSUE TITLE
GitHub Copilot high CPU usage

### ISSUE THREAD

**Issue by stown100** [microsoft/vscode#225122]
Type: <b>Bug</b>

The process is experiencing high CPU usage, specifically running at over 100% on an Apple M1 MacBook Air. GitHub Copilot v1.221.0

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (1.87GB free)|
|Process Argv|--crash-reporter-id a2e30118-680e-4422-bd7c-7332146d11c8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-css-formatter|aes|1.0.2
atlascode|atl|3.0.10
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
gitlab-workflow|Git|5.4.0
vscode-gutter-preview|kis|0.31.2
auto-save|mcr|1.0.3
rainbow-csv|mec|3.12.0
vscode-docker|ms-|1.29.1
material-icon-theme|PKi|5.8.0
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
9b8hh234:30694863
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
ccpltc:31103427
pythonrstrctxt:31103193
wkspc-onlycs-c:31111717
wkspc-ranged-c:31111712

```

</details>

**Comment by stown100** [comment]
<img width="611" alt="Снимок экрана 2024-08-08 в 10 10 46" src="https://github.com/user-attachments/assets/fcfc7318-d9dc-4efc-a85a-9d0abf4b0941">

**Comment by connor4312** [comment]
Please collect a performance profile, thanks https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

**Comment by stown100** [comment]
[Uploading CPU-20240808T162943.870Z.cpuprofile.txt…]()

**Comment by stown100** [comment]
I started the new chat and the problem has disappeared. Now is ok. Maybe it was problem with old chat.

**Comment by connor4312** [comment]
It looks like you submitted your comment before the upload finished -- could you try attaching it again and wait until the "Uploading" text turns into a link?

**Comment by stown100** [comment]
[CPU-20240808T162943.870Z.cpuprofile.txt](https://github.com/user-attachments/files/16558335/CPU-20240808T162943.870Z.cpuprofile.txt)

**Comment by connor4312** [comment]
It looks like the TypeScript server is the one consuming CPU, rather than copilot

**Comment by stown100** [comment]
This happened when I enabled the Copilot chat and switched to it. After disabling the GitHub Copilot chat and restarting VSCode, the issue would go away until I enabled the GitHub Copilot chat again. However, the problem no longer exists. It disappeared completely after I started a new session with GitHub Copilot chat and restarted VSCode once more.
