### ISSUE TITLE
Screen blurs

### ISSUE THREAD

**Issue by AJAY732579** [microsoft/vscode#225130]
Type: <b>Bug</b>

my screen is blurred when i write something

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1240P (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.71GB (0.51GB free)|
|Process Argv|--crash-reporter-id 58a20651-fc40-4f4c-bbbb-9074eb28bfe3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
node-essentials|afr|1.1.0
vscode-icontheme-nomo-dark|be5|1.3.6
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.3
EditorConfig|Edi|0.16.4
classroom|git|0.0.4
vscode-pull-request-github|Git|0.94.0
dotenv|mik|1.0.1
vscode-kubernetes-tools|ms-|1.3.16
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5936
debugger-for-chrome|msj|4.13.0
vscode-jest|Ort|6.2.5
fabric8-analytics|red|0.9.5
java|red|1.33.0
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.28.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
quokka-vscode|Wal|1.0.649
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
ccpltc:31103427
pythonrstrctxt:31103193
wkspc-onlycs-t:31111718
wkspc-ranged-t:31111713

```

</details>

**Comment by gjsjohnmurray** [comment]
Please try launching VS Code from a Windows command prompt like this:

`code --disable-gpu`
