### ISSUE TITLE
Debugger prompt handles the arguments wrongly

### ISSUE THREAD

**Issue by AcademicChamberlain** [microsoft/vscode#225113]
Type: <b>Bug</b>

Spaces in the input string for arguments, such as `--batch_size=8 --device_id=0`, would be handled in the form of their escape characters, like `--batch_size=8\ --device_id=0`.

This result in `Exception has occurred: SystemExit`, `error: argument --batch_size: invalid int value: '8 --device_id=0'`, thus the characters that should be parsed into the second argument is wrongly parsed into the first one. 

The bug of debugger occurs when debugging with the input prompt for arguments, but when using the launch.json to set the arguments, the debugger works well.

This problem has been exsisted in the last version of vscode insider, but still exists in the new version as I tried to update to see if the essential functional problem solved.

VS Code version: Code - Insiders 1.93.0-insider (d4c4e690b9f1e70291da9a46c5c8ac5ebfbda81a, 2024-08-07T05:03:47.999Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Remote OS version: Linux x64 5.13.0-30-generic

<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-python-indent|Kev|1.18.0
remote-ssh|ms-|0.114.2024080515
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.5.2024070409
jinja|who|0.0.8
vscode-django|bat|1.15.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
vsc-python-indent|Kev|1.18.0
debugpy|ms-|2024.10.0
python|ms-|2024.12.2
vscode-pylance|ms-|2024.8.1
autodocstring|njp|0.6.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialogc:30812479
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
945dj816:31013170
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
2f103344:31071589
nb_pri_only:31057983
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31105043
wkspc-onlycs-t:31111718
nativeloc2:31111756
3ad50483:31111987
93e6f237:31111927

```

</details>

**Comment by roblourens** [comment]
What language? Can you give an example of the launch.json?

**Comment by AcademicChamberlain** [comment]
> What language? Can you give an example of the launch.json?

Python. Here's the python code and launch.json that works:
```Python
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--repeat_time', type=int, default=0)
parser.add_argument('--your_word', type=str, default='Hello World!', help='the content to repeat')

args = parser.parse_args()

for i in range (args.repeat_time):
    print(args.your_word)

```
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python Debugger: Current File with Arguments",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "args": [
                "--repeat_time=3", "--your_word=Poincare"
            ]
        }
    ]
}
```
But when I use `"--repeat_time=3 --your_word=Poincare"` in stead of `"--repeat_time=3", "--your_word=Poincare"` in the launch.json, the same bug occurs.

**Comment by roblourens** [comment]
Splitting the args into two is correct, `"--repeat_time=3 --your_word=Poincare"` seems incorrect. If you think there's an issue you can open an issue on the repo for the python debug extension

**Comment by AcademicChamberlain** [comment]
Okay, thanks for your reminding me~
