### ISSUE TITLE
���

### ISSUE THREAD

**Issue by duicym** [Microsoft/vscode#22516]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 
**[Running] fsi "d:\code\ham\hamorspam.fs"
'fsi' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

[Done] exited with code=1 in 0.085 seconds**

|Extension|Author|Version|
|---|---|---|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.7|
|vscode-npm-script|eg2|0.1.8|
|code-runner|formulahendry|0.6.14|
|Ionide-fsharp|Ionide|2.23.9|
|search-node-modules|jasonnutter|1.0.2|
|csharp|ms-vscode|1.7.0|
|nodejs-extension-pack|waderyan|0.1.9|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.mk a file .fs (F#)
2.right click ->"run code" , then output is ���

**Comment by weinand** [comment]
@duicym Please file this issues against the F# extension you are using.
