### ISSUE TITLE
Too slow on july release update 1.92

### ISSUE THREAD

**Issue by svigneshUIUX** [microsoft/vscode#225108]
Type: <b>Performance Issue</b>

Too slow on july relese update 1.92. After down grade to 1.91 works fine

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz (4 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (4.19GB free)|
|Process Argv|--crash-reporter-id bbcc5243-6543-4707-9bfc-d5282724cd21|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   107	 15672	code main
    0	   109	  4036	shared-process
    0	    29	  4360	   crashpad-handler
    0	   181	  5200	extensionHost [1]
    0	   121	  4004	     electron-nodejs (tsserver.js )
    0	   128	  6448	     electron-nodejs (tailwindServer.js )
    0	   152	 17656	     electron-nodejs (eslintServer.js )
    0	   149	 19956	     electron-nodejs (server.js )
    0	   218	 20904	     electron-nodejs (tsserver.js )
    0	    97	  1256	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	   280	  6772	window [1] (page.tsx - ca-website-V2 - Visual Studio Code)
    0	   171	 11580	   gpu-process
    0	    42	 12256	   utility-network-service
    1	    96	 14724	window [2] (Issue Reporter)
    0	   108	 20952	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (page.tsx - ca-website-V2 - Visual Studio Code)
|    Folder (ca-website-V2): 854 files
|      File types: webp(246) js(123) gz(43) tsx(42) json(39) ts(9) pack(6)
|                  css(5) old(3) svg(3)
|      Conf files: package.json(3) settings.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.1.2
vscode-tailwindcss|bra|0.12.5
dart-code|Dar|3.94.0
flutter|Dar|3.94.0
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
vscode-liquid-snippets|kil|2.0.3
azure-dev|ms-|0.8.3
vscode-azureappservice|ms-|0.25.2
vscode-azurecontainerapps|ms-|0.7.0
vscode-azurefunctions|ms-|1.15.1
vscode-azureresourcegroups|ms-|0.9.1
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.16.0
vscode-azurevirtualmachines|ms-|0.6.5
vscode-cosmosdb|ms-|0.22.0
csdevkit|ms-|1.9.55
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.1
vscode-edge-devtools|ms-|2.1.5
debugpy|ms-|2024.8.0
isort|ms-|2023.10.1
python|ms-|2024.12.2
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
azure-account|ms-|0.12.0
powershell|ms-|2024.2.2
vscode-node-azure-pack|ms-|1.2.0
material-icon-theme|PKi|5.8.0
theme-check-vscode|Sho|2.4.3
vscode-icons|vsc|12.8.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.17.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
ccplt:31103426
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-t:31111713

```

</details>

**Comment by albertosantini** [comment]
You may follow this steps to collect some info:
https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by meganrogge** [comment]
please provide more info
