### ISSUE TITLE
Quick pick API does not dispose any listeners

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#225158]
See all the `onDidXY` not being registered as disposable to clear when the session is over:

https://github.com/microsoft/vscode/blob/c7cf0f18ef2fd1960564cdf9d93151c4709bbf1a/src/vs/workbench/api/browser/mainThreadQuickOpen.ts#L125-L151

**Comment by bpasero** [comment]
Hm, why is this so wide spread, I see many more 🤔 

https://github.com/microsoft/vscode/blob/c7cf0f18ef2fd1960564cdf9d93151c4709bbf1a/src/vs/workbench/contrib/debug/browser/breakpointsView.ts#L1504-L1520

**Comment by TylerLeonhardt** [comment]
They're events. The user of the quick pick is responsible for disposing them afterwards.
