### ISSUE TITLE
Performance tests inside unit tests?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#22512]
I see that we run a textsearch performance test and quickopen performance test as part of our unit tests. Do we really need to run those everytime? I think we should extract them towards code-performance-test.sh or similar to keep our unit tests execute fast.

**Comment by roblourens** [comment]
They don't actually run (they can't, they don't have the test workspace to run on). We could run them via a separate script though.

**Comment by chrmarti** [comment]
They are run in a way they doesn't use much time. Running them makes sure they don't break.
