### ISSUE TITLE
Cannot create a new configuration normally

### ISSUE THREAD

**Issue by wowqhb** [microsoft/vscode#225114]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.0
- OS Version: Ubuntu 20.04.6 LTS

Steps to Reproduce:

Please watch the video
[2024年08月08日 屏幕视频 15时11分41秒.webm](https://github.com/user-attachments/assets/a8e6055d-67f0-4683-9473-f983a46d274a)

**Comment by CwkDark** [comment]
I'm the same way.
As soon as you change the options in this panel other than the name, it does this.

**Comment by CwkDark** [comment]
Did a simple test and only 1.92.0 has this issue

**Comment by wowqhb** [comment]
This problem can be tested in a virtual machine, in addition, this problem is in 1.91.x It's on.

**Comment by wowqhb** [comment]
[2024年08月27日 屏幕视频 09时44分53秒.webm](https://github.com/user-attachments/assets/77c89761-55a4-41e0-901a-bf8b3a9f4082)

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.92.2 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36 

Operating System: 
![image](https://github.com/user-attachments/assets/2eb99186-843a-4c4c-b242-a464e4a99516)

The problem remains, and I'm very disappointed with vsode.
