### ISSUE TITLE
Language mode not set for editor on reload

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#225134]
Markdown file on Plain Text on startup:

![image](https://github.com/user-attachments/assets/0298107a-f751-472b-83b4-6abffa4e117a)

Same with TS in another window:

![image](https://github.com/user-attachments/assets/f0df87a8-896a-4159-ba9c-8316307ff6c6)

Reproduces by reloading the window.

Not sure who the right person is for this

Version: 1.93.0-insider (user setup)
Commit: 8245d426e009ec7864018ed05ae2a282af42f03b
Date: 2024-08-08T05:03:51.428Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by hediet** [comment]
On it
