### ISSUE TITLE
Remote SSH bypasses normal login & shell initialisation and doesn't honor utmp, wtmp login records

### ISSUE THREAD

**Issue by johan-boule** [microsoft/vscode#225199]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.92.0 (user setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: MSDOS / Windows_NT x64 10.0.19045

Steps to Reproduce:
1. Connect to a remote host through SSH
2. Check login records with e.g. `w`, `who` or `utmpdump /var/run/utmp`

No login record found.

**Comment by roblourens** [comment]
This is probably because we use `ssh -T` since we are running a script to install a server that we connect to, and not starting a typical interactive ssh session, does that sound right?
