### ISSUE TITLE
git commit Author identity unknown

### ISSUE THREAD

**Issue by Jinying-Tang** [microsoft/vscode#225147]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.92.1
- OS Version: Windows11 23H2

Steps to Reproduce:
When I change the code in vscode and click the submit button on the git source code management page, it prompts to ensure that a username and email are configured in git. The log shows:
 2024-08-09 00:53:36.781 [info] > git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file - [129ms]
2024-08-09 00:53:36.781 [info] Author identity unknown
*** Please tell me who you are. 

However, I can see that I have already set up a username and email using git config user.name and git config user.email in the terminal, and changes can be committed through git commit prompt in the terminal.

**Comment by Jinying-Tang** [comment]
When I disable all extensions, the commit in the git source code manager works correctly. I tried enabling each extension one by one and found that when the .NET Install Tool extension is enabled, the error mentioned above occurs during submission. Then I disabled all extensions again and only enabled the .NET Install Tool extension, but the error still occurred.

**Comment by lszomoru** [comment]
Based on the information that you have shared it looks like the issue is related to the .NET Install Tool extension. 
Please file an issue in the extension's repository here: https://github.com/dotnet/vscode-dotnet-runtime/issues. Thanks!
