### ISSUE TITLE
TypeScript Decorators: IDE doesn't suggest to Add import decloration

### ISSUE THREAD

**Issue by microshine** [Microsoft/vscode#22518]
- VSCode Version: 1.10.2
- OS Version: macOS 10.12.3
- TS version: 2.2.1

it works for objects:
![image](https://cloud.githubusercontent.com/assets/7333669/23851768/b33cf00c-07f5-11e7-8cfe-b721f448ab26.png)

but not for decorators
![image](https://cloud.githubusercontent.com/assets/7333669/23851816/e0b35486-07f5-11e7-9e19-f6b920863c8a.png)

**Comment by mjbvz** [comment]
@microshine From the error message on `Storage`, it looks like there is already a definition of `Storage` somewhere. In that case, we would not so the add missing import quick fix.

If you run `go to definition` on `Storage`, where does it go?

**Comment by microshine** [comment]
Yes, you are right. This is my mistake. There is Storage in `lib.d.ts`. If I use another name it works. Thank you for help
