### ISSUE TITLE
SSH, SSH key passphrases, if cancel can't even exit VSCode

### ISSUE THREAD

**Issue by CaptainPalapa** [microsoft/vscode#225197]
Type: <b>Bug</b>

I have an SSH key with a passphrase for security.
I create saved (local Windows machine) workspaces for various SSH remote Linux instances as well as non-remote development projects that don't require SSH.

Open workspace (my-remote-1.workspaces), connection begins, SSH passphrase is asked for in the dialog popup at the top.

At this point, I MUST enter the passphrase.  (This can also happen if the connection is dropped and VSCode tries to reestablish it.)
If I hit cancel (maybe I meant to open a different remote or local workspace) I can no longer open a different workspace.  I can't ALT_F4, File..Exit... CTRL+P "Open Workspace"... nothing.  I have to go to Windows Task Manager and kill Visual Studio Code.

My current error showing behind this reporting window is, essentially:
"File system provider for vscode-remote://ssh-remote%[some id]/[remote path] is not available.  (Because I didn't correctly enter the passphrase or I hit ESC, ESC, ESC, ESC trying to get out of it.)  There is no getting out of it."

Sorry for the ramble, I'm not a professional bug submitter.

I'll add this while I'm here:  The UI for handling remote vs. local workspaces is poorly designed.  If I CTRL+P, Open Workspace... while I'm in a remote workspace, it tries to have me find something in the remote location.  I have to hit "Local Files" and it does not always work.    Now, I can say that I don't know how others do the remote SSH workspaces, but for me... with ALL locally saved workspaces that may point to remote computers or local folders... it is a mess.  VSCode is great.  I love it.  But this part... meh.

File...About:
Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Connection to 'SSH: Hetzner-Parcel' could not be established  Connecting was canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.85GB (11.17GB free)|
|Process Argv|C:\\Development\\VSR-project-workspace.code-workspace --crash-reporter-id 28d3a867-52e2-4251-a9eb-e8dd0c5a44d6|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: Hetzner-Parcel' could not be established  Connecting was canceled
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-c:31111712

```

</details>

**Comment by CaptainPalapa** [comment]
Yes, still the same kind of issues after upgrading.  I didn't have to KILL vscode this time.  But I did have to shut it down.  Then go double-click on a saved LOCAL workspace to open it in vscode so I'd be in not-ssh / local-files mode.

**Comment by joshspicer** [comment]
In the command palette there is a command `> Close Remote Connection` that you can use to exit.  In this case it sounds like you've initiated the connection, so that window is now tied to the remote, even if the connection ultimately was unsuccessful.  

Please feel free to re-open if you think there's something i'm missing here.  If so, it would be helpful to see a gif of the experience, so I can determine if you're hitting a bug or if our UX is confusing
