### ISSUE TITLE
[Fast run] Don't run ALL extensions that just only open a .txt file

### ISSUE THREAD

**Issue by LaksVister** [microsoft/vscode#225111]
Very often I want to open VScode in a separate window .txt file for quick viewing and not activate unnecessary extensions in the background that slow down my weak computer.

Although VScode is not about fast view, but in my opinion there is a fairly simple solution which I have depicted in the image.

The idea is simple, only run the extension when opening a file if that file needs it
![feature](https://github.com/user-attachments/assets/42505d17-ec72-493e-bdfb-028e1951105d)

**Comment by gjsjohnmurray** [comment]
Extension authors are given a lot of control over when they want their extension to be activated by VS Code.

https://code.visualstudio.com/api/references/activation-events

If you feel some of your extensions activate too early please raise the matter with the extension authors.

You can also use Profiles to get greater control of which extensions to enable in different contexts.

**Comment by roblourens** [comment]
Thanks @gjsjohnmurray, I would give the same answer. It's up to the extension, and Profiles are how you can customize this.
