### ISSUE TITLE
Type hint for TypedArray is not available for JS

### ISSUE THREAD

**Issue by gudvinr** [microsoft/vscode#225124]
Does this issue occur when all extensions are disabled?: Yes (you won't get any suggestions)

- VS Code Version: 1.92.0
- OS Version: Arch Linux 

Steps to Reproduce:

1. Create annotation that includes TypedArray hint
2. Hover over argument that has TypedArray hint

```js
/**
 * @param {TypedArray} data
 */
function shuffle(data) {}
```

In this example, when you hover over data, you should see reference to [TypedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray).

Instead, you're getting `type TypedArray = /*unresolved*/ any`.

**Comment by albertosantini** [comment]
Hovering on `TypedArray`
![image](https://github.com/user-attachments/assets/a83c1e7c-c813-4b0e-9cc7-4fd305f9e299)
Hovering on `data` in jsdoc
![image](https://github.com/user-attachments/assets/a388d38e-7422-485f-b614-6cbebf671a44)
Hovering on param `data`
![image](https://github.com/user-attachments/assets/706c0c26-904f-4cd5-801b-6f0088beb236)

It seems ok. Am I wrong?

**Comment by mjbvz** [comment]
`TypedArray` isn't an actual type you can use. It's the category that all the actual typed arrays — `Uint8Array`, `Float32Array`, ... — belong to, however there is no actual `TypedArray` global or type
