### ISSUE TITLE
Terminal rendering glitched on latest Insiders

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#225140]
I have windowsUseConptyDll set to true, but I believe I saw this yesterday with that setting off as well.

:bug: When I start typing, the cursor moves vertically to the middle of the terminal, around where the git checkout line is.

![Image](https://github.com/user-attachments/assets/9a81a13c-dd40-44f6-8414-5561db7265df)

**Comment by Tyriar** [comment]
Looks like this is what the `conptyInheritCursor` flag is meant to fix:

https://github.com/microsoft/vscode/blob/559107b7a92be2cfda116e3a0667f1b1ac9bf78b/src/vs/platform/terminal/node/terminalProcess.ts#L167

Perhaps the API for that is different in conpty.dll

**Comment by rzhao271** [comment]
Unable to repro now
