### ISSUE TITLE
Strange tslint + quick fix behaviour

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#22517]
Not sure if lightbulb or tslint issue.

![kapture 2017-03-13 at 11 53 54](https://cloud.githubusercontent.com/assets/22350/23851436/ce438c38-07e3-11e7-9b8f-a466befeaa8c.gif)

**Comment by joaomoreno** [comment]
Seems like a lightbulb issue, I get it with every quick fix.

**Comment by jrieken** [comment]
should be fixed by 3eb1c588ec05bff71d2aeb805c3b907a6c2d8fbc

**Comment by jrieken** [comment]
and if not, @joaomoreno should at least enjoy the use of object spread

**Comment by joaomoreno** [comment]
omg our perf numbers are gonna go thru the roof!
