### ISSUE TITLE
call stack

### ISSUE THREAD

**Issue by ErtasBurak** [microsoft/vscode#225123]
Type: <b>Bug</b>

sometimes when i debug one emulator it will not show in call stack but when i start the second emulator both show up in call stack

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.23GB free)|
|Process Argv|--crash-reporter-id 62ac25ee-7cea-46ce-a3df-20bc76845687|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
flutter-snippets|ale|3.0.0
vscode-django|bat|1.15.0
path-intellisense|chr|2.9.0
dart-code|Dar|3.94.0
flutter|Dar|3.94.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
gitlens|eam|15.2.3
prettier-vscode|esb|10.4.0
bloc|Fel|6.6.6
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
go|gol|0.42.0
vscode-flutter-files|gor|4.9.1
todo-tree|Gru|0.0.226
vscode-drawio|hed|1.6.6
json-to-dart|hir|3.5.8
dart-data-class-generator|hzg|0.5.4
vsc-python-indent|Kev|1.18.0
blockman|leo|1.7.7
flutter-intl|loc|1.19.3
dart-import|lua|0.3.1
git-graph|mhu|1.30.0
debugpy|ms-|2024.10.0
python|ms-|2024.12.2
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
vscode-groovy-lint|Nic|3.3.1
autodocstring|njp|0.6.1
material-icon-theme|PKi|5.8.0
postman-for-vscode|Pos|1.2.1
vscode-thunder-client|ran|2.24.13
vscode-xml|red|0.27.1
flutter-dart-utils|Rod|1.8.7
code-spell-checker|str|3.0.1
cmake|twx|0.0.17
errorlens|use|3.20.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.17.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
ccplti:31103428
pythonrstrctxt:31103193
wkspc-onlycs-c:31111717
wkspc-ranged-t:31111713

```

</details>

**Comment by roblourens** [comment]
It's by design that the name of the debuggee won't show in the call stack unless there are multiple processes and you may need to switch which one is active. Is that what you see? Or something else? A screenshot might help.

**Comment by ErtasBurak** [comment]
I found the issue. Its because of the Hitbox size and poisiton in onLoad(). 
![Screenshot_1723272383](https://github.com/user-attachments/assets/acc64200-4890-49a2-b5b6-8c0695454cfc)
![Screenshot_1723272400](https://github.com/user-attachments/assets/e970c74d-b759-477f-928d-b16ebb31be77)

**Comment by ErtasBurak** [comment]
If I just start one emulator:

![Ekran görüntüsü 2024-08-10 095022](https://github.com/user-attachments/assets/a8fe6bcb-1c19-406c-99b6-d3515dc5ad84)

When I start the second emulator:

![Ekran görüntüsü 2024-08-10 095141](https://github.com/user-attachments/assets/d5fe97aa-dbde-49e3-8f06-700ba765904f)

If the design is so, ok. But it would cool if I can see when I started just one emulator.
