### ISSUE TITLE
Command `workbench.action.togglePanel` should not resize the terminal

### ISSUE THREAD

**Issue by johan-boule** [microsoft/vscode#225196]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.92.0 (user setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z (1 wk ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: MSDOS / Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Launch tmux in the terminal
2. Maximise the terminal
3. Use the command workbench.action.togglePanel a few times

Issue: nearly half the time, the terminal gets resized to a non-maximised height. I suspect the terminal gets resized multiple times rapidly and the tmux application doesn't cope with this.

**Comment by meganrogge** [comment]
a gif would help
