### ISSUE TITLE
Could launch browser in container

### ISSUE THREAD

**Issue by taoqf** [microsoft/vscode#225193]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.0
- OS Version: win/linux

Steps to Reproduce:

1. open in a container
2. create file index.html
3. type following codes in
```html
<html>
<body>
<a href='https://code.visualstudio.com/'>vscode</a>
</body>
</html>
```
4. install extension `ritwickdey.LiveServer` in container
5. right click index.html and click `Open with Live Server`
6. Browser is not opened with no error.

**Comment by taoqf** [comment]
1.92.1 remain the same. 
I believe the behave opening default browser is changed since 1.92.0, or last publish of ext liveserver.

**Comment by andreamah** [comment]
Please file this with the extension's issue tracker: https://github.com/ritwickdey/vscode-live-server/issues
