### ISSUE TITLE
commit history list collapsible

### ISSUE THREAD

**Issue by levalencia** [microsoft/vscode#225115]
the commit history we shold be able to collapse it, or it should come collapsed by default.

we have 8 projects in the workspace and this is very annoying.

- VS Code Version: 1.92.0
- OS Version: windows 11

![image](https://github.com/user-attachments/assets/3964260d-aa0c-462b-ab56-ab73c26c0fb3)

**Comment by lszomoru** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/224517.
