### ISSUE TITLE
Change the size of the folding symbol together with the font size

### ISSUE THREAD

**Issue by miniAtom** [microsoft/vscode#225128]
The size of the folding symbol next to the code seems to be constant. When the font is large, the folding symbol looks very small and incongruous. Can we change the size of the folding symbol together with the font size?
![image](https://github.com/user-attachments/assets/6e12e54e-0686-4d68-8743-6cbdbde21b1c)

There is another problem. When the font is large, the sticky scrolling folding symbol overlaps with the code line number. I hope it can be fixed.
![image](https://github.com/user-attachments/assets/2990f764-27e4-448d-9006-0b94a091e818)

**Comment by aeschli** [comment]
I believe the size is managed by the editor gutter
