### ISSUE TITLE
BUG : jsconfig.json file in $HOME crash computer

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#22515]
- VSCode Version: 1.10.2
- OS Version:

Steps to Reproduce:
_linked to #22372_

1. Close vscode
2. create `jsconfig.json` file in your $HOME directory with content : 
```
{
    "compilerOptions": {
        "lib": [
            "es2015"
        ]
    }
}
```
3. launch any project of vscode and check your processor activity : 
![image](https://cloud.githubusercontent.com/assets/5599375/23849423/db71b45a-07db-11e7-82da-6dee271379d2.png)

You will got huge performances problems identified, intellisense will completely crash in "loading ..." state, and the whole computer will slow down.

Processes stay as ghost even if vscode is closed.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14636
