### ISSUE TITLE
Latest Insiders: Initial document not providing colors

### ISSUE THREAD

**Issue by RobertOstermann** [microsoft/vscode#225146]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.0-insider
- OS Version: 

Steps to Reproduce:

1. Open or reload a VSCode window
2. Notice the initial file that is opened does not provider colors, even when switching to a different file and switching back.

**Comment by antonblock** [comment]
Also seeing this across different languages. I found that closing the tab, then reopening (CMD+Shift+t or CTRL+Shift+t) restores the syntax highlighting and navigation to references/definitions

- Running: Version: 1.93.0-insider (Universal)

**Comment by RobertOstermann** [comment]
@hediet What issue is this a duplicate of?

**Comment by antonblock** [comment]
> @hediet What issue is this a duplicate of?

https://github.com/microsoft/vscode/issues/225134
