### ISSUE TITLE
localhost freezes when i change code , I'm using chrome

### ISSUE THREAD

**Issue by shivakumarnagineni** [microsoft/vscode#225148]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: July 2024 (version 1.92)
- OS Version: MacOs 14.6.1 

Steps to Reproduce:

1. When i do any kind of changes in my code it is reflecting but it isn't disabing clicking in chrome
2. I' m having this issue from latest update.

**Comment by IllusionMH** [comment]
/needsMoreInfo
How it's related to VS Code editor itself? Looks like an issue with an extension you might be using.

Please provide detailed steps to reproduce this problem

**Comment by shivakumarnagineni** [comment]
I've tried disabling all the extensions in vs code that i was using even before. I'm getting this issue after the latest update of both vs code and chrome. I'm not sure what is the exact reason. I tried clearing cache from the browser, disabling extensions in both chrome and vs code too. 


The issue I'm facing is, whenever I do the changes in code it does reflect in chrome but that localhost tab content itself is freezing. 


Please help me

Thank you
Shiva Kumar Nagineni



---- On Fri, 09 Aug 2024 05:08:02 +0530 ***@***.*** wrote ----



/needsMoreInfo
How it's related to VS Code editor itself? Looks like an issue with an extension you might be using.

Please provide detailed steps to reproduce this problem

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.
This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. Tek Yantra is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company

**Comment by joshspicer** [comment]
Unfortunately your issue is not clear from your description.  How is Chrome related here?  Are you building a web application and have Chrome open to view the app?  If so, how are you running this application.  What makes you think this is related to the VS Code editor, and not some other factor?

Please take a look at the linked issue reporting guidelines, as that will help us best understand your issue :)
