### ISSUE TITLE
wrong editor/context format of command shortcut text

### ISSUE THREAD

**Issue by fr43nk** [Microsoft/vscode#22511]
When there is a keybinding defined like: 
```ctrl+c ctrl+c```
the format of the editor context is somehow wrong (see screenshot).
![shortcut format](https://cloud.githubusercontent.com/assets/3279247/23847635/ab490db2-07d3-11e7-9188-662e439ff7d0.png)
The text format of the keybinding is the same as the command title. If I change this back to a single
```ctrl+c```
everything looks as usual.
![shortcut format correct](https://cloud.githubusercontent.com/assets/3279247/23847678/de159bb6-07d3-11e7-9df7-392994e9a99e.png)

- VSCode Version: 1.10.2
- OS Version: Windows 7

**Comment by weinand** [comment]
This is a limitation of Electron's native menu support.

**Comment by bpasero** [comment]
Yes, nothing we can do about currently.
