### ISSUE TITLE
Hope to increase debugging visibility

### ISSUE THREAD

**Issue by yupor5** [microsoft/vscode#225200]
Type: <b>Feature Request</b>

Hope to increase debugging visibility

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 6.1.0-10-amd64

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Please explain in more detail what you want.
