### ISSUE TITLE
Distinguish generic color and type name colors

### ISSUE THREAD

**Issue by videni** [microsoft/vscode#225209]
I searchd the issues, but didn't find existed request. 

 Rust is a strong type language. The type definition would look very complicated when there are lots of generics. 

 Generics are less important than trait name and type name (struct name, enum name), so I'd like to see their colors be different.
It might not be the best place to report this inconvenience here. 

![image](https://github.com/user-attachments/assets/27eceb07-6d14-4ccc-9615-a2adc429832b)

**Comment by aeschli** [comment]
Right now, the Rust grammar that we use (https://github.com/dustypomerleau/rust-syntax/blob/master/syntaxes/rust.tmLanguage.json) emits the scope for both `TraversePartialTree` and  `TaffyView`. 

You can file a feature request again the Rust grammar (https://github.com/dustypomerleau/rust-syntax) that it creates a different token for the trait. Then themes can give it a different color (or you can customize the color in the settings).

**Comment by videni** [comment]
@aeschli  I see, thanks
