### ISSUE TITLE
The first code file after vscode is opened cannot display language intelligent prompts correctly

### ISSUE THREAD

**Issue by samecos** [microsoft/vscode#225206]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.26120

提交: 8245d426e009ec7864018ed05ae2a282af42f03b
日期: 2024-08-08T05:03:51.428Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0

Steps to Reproduce:

1. open vscode
2. The first file cannot display the language's intelligent prompt correctly
3. Other files are  normal
4. 
![image](https://github.com/user-attachments/assets/b94a7187-7883-455b-bc50-f556968c5110)

**Comment by gjsjohnmurray** [comment]
Maybe a duplicate of #225183
