### ISSUE TITLE
not able to select a quick-pick checkbox in the `commit: add co author` action

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#225285]
1. commit -> add co-author
2. type to filter
3. use the mouse or the keyboard to try to select a user
4. 🐛 it won't work

https://github.com/user-attachments/assets/e06c96d4-9c13-42ad-949a-79fbd8868b2e

**Comment by TylerLeonhardt** [comment]
@eamodio I believe this is provided by GitLens? `gitlens.addAuthors` from what I can tell.

This quick pick does something interesting where it listens on selection change and maybe refreshes the data? I can't seem to repro this outside of this quick pick... Can you take a look?

**Comment by TylerLeonhardt** [comment]
@meganrogge can you open this over at https://github.com/gitkraken/vscode-gitlens/issues ? I'll close this since it's not VS Code... but @eamodio please lmk if you think it's a quick pick bug!

**Comment by eamodio** [comment]
@TylerLeonhardt yeah we try to refresh to keep the selected items at the top of the list (which the quickpick does not make easy). So yeah, please open this on the GitLens repo -- though FWIW, I can't replicate this.
