### ISSUE TITLE
Cloud Run Service Deployment Breaking

### ISSUE THREAD

**Issue by lalkumarrai** [microsoft/vscode#225205]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92
- OS Version:  window 10

Steps to Reproduce:

1. Install Gemini Code Assist + Google Cloud Code extension
2. Create an dummy project from cloud run and try to deploy in google cloud run
3. The service deployment failed suddenly with the issue (Failed to build the app. Error: Failed to create skaffold configuration. Error: processing cli artifacts: malformed artifact provided: {image:gcr.io/flaskgcp-424601/scoro-optimo,builder:Docker,payload:{path:Dockerfile}}
4. From the logs, we can see (Running skaffold command: "C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\skaffold.exe" init --artifact {"image":"gcr.io/flaskgcp-424601/scoro-optimo","builder":"Docker","payload":{"path":"Dockerfile"}} --skip-deploy --filename C:\Users\user\AppData\Local\Temp\cloud-code-cloud-run-PTBBBp\skaffold.yaml --force
processing cli artifacts: malformed artifact provided: {image:gcr.io/flaskgcp-424601/scoro-optimo,builder:Docker,payload:{path:Dockerfile}}
Failed to build the app. Error: Failed to create skaffold configuration. Error: processing cli artifacts: malformed artifact provided: {image:gcr.io/flaskgcp-424601/scoro-optimo,builder:Docker,payload:{path:Dockerfile}}
)

**Comment by lalkumarrai** [comment]
I have updated to 1.92.1 but the problem still exists.

**Comment by AnNguyenPTN** [comment]
I have the same issue with you. But when I try to run my project in Mac OS it works well.
I see in the window the Gemini Code Assits extension shows an error like the one below:
![image](https://github.com/user-attachments/assets/17751534-aba4-4c2c-9fbd-1e94092d02a1)
However, with the same account in the Mac OS it now shows any error
I want to uninstall it, just to keep Cloud Code but can not. It combines together.
I think this information can help you investigate this issue.

**Comment by gjsjohnmurray** [comment]
@AnNguyenPTN investigation is the job of the extension authors. Please raise the issue with them,
