### ISSUE TITLE
editor.action.formatDocument for HTML span not indenting properly?

### ISSUE THREAD

**Issue by StaticNoiseLog** [Microsoft/vscode#22524]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.7|
|vscode-firefox-debug|hbenl|0.9.1|
|csharp|ms-vscode|1.7.0|
|html5-boilerplate|sidthesloth|1.0.1|;

---

Steps to Reproduce:

1. Create a file with the following HTML snippet (from the Aurelia Quick Start):
```
<template>
    <h1>${heading}</h1>

    <form submit.trigger="addTodo()">
        <input type="text" value.bind="todoDescription">
        <button type="submit">Add Todo</button>
    </form>

    <ul>
        <li repeat.for="todo of todos">
            <input type="checkbox" checked.bind="todo.done">
                   <span css="text-decoration: ${todo.done ? 'line-through' : 'none'}">
              ${todo.description}              
     </span>
            <button click.trigger="removeTodo(todo)">Remove</button>
        </li>
    </ul>
</template>
```

2. Use **editor.action.formatDocument**

3. Why does the closing tag `</span>` element not get indented, i.e. not aligned with the starting tag `<span>`? Is this a special case because it is a span? Or is it a bug?

**Comment by aeschli** [comment]
This is because `span` is inside the input tag which is the list of tags not to be formatted.
See setting
```
  "html.format.unformatted": "a, abbr, acronym, b, bdo, big, br, button, cite, code, dfn, em, i, img, input, kbd, label, map, object, q, samp, select, small, span, strong, sub, sup, textarea, tt, var",
```
