### ISSUE TITLE
rename of unsaved new file erases all so far edited contents.

### ISSUE THREAD

**Issue by nanobug** [Microsoft/vscode#22527]
'rename' of unsaved new file erases its content in open editor.

- VSCode Version: 1.10.2
- OS Version: Win7 SP1

Steps to Reproduce:

1. Create new File ( .h)
2. edit file contents but do not save
3. on project window select in context-menu 'rename file'
4. All edits are gone !!!!

**Comment by bpasero** [comment]
I cannot reproduce, what are you doing differently?

![panel-red](https://cloud.githubusercontent.com/assets/900690/23856665/b28aa4ec-07fa-11e7-9ec3-6fdebcd85a82.gif)

**Comment by nanobug** [comment]
Had this situation that all contents was erased, will monitor ( happens not so often).
Hmm, not reproducable also on my site.

**Comment by nanobug** [comment]
Ahh, OK, now I got it reproduced:
The magic happens with the character Case of the file:
1. new file e.g. 'sto_gattSrv.h'
2. edit file without save
3. rename file 'sto_gattsrv.h'
4. contents erased.

**Comment by bpasero** [comment]
@nanobug thanks I see the issue.

**To verify:** we still show a confirmation prompt before doing the rename operation if you rename a file (or one of its parent folders) to the same path but different casing.

![image](https://cloud.githubusercontent.com/assets/900690/23862077/580f89e4-080c-11e7-8152-03c3c0f237d3.png)

**Comment by michelkaporin** [comment]
Followed @nanobug steps to verify, contents of the dirty file are not removed anymore on save. However, I do not see this prompt upon saving when renaming the same file to different casing.

**Comment by bpasero** [comment]
@michelkaporin actually what is happening is that I had a bug in that code so that my initial solution was never triggered (showing a dialog). On the other hand I just realized that hot-exit is now case sensitive so I no longer need to show the dialog.

Please verify (I just pushed something, so tomorrow) that you can rename a dirty file by changing its case (or parent casing) and the file stays dirty.

**Comment by michelkaporin** [comment]
@bpasero the file stays dirty, however it is marked as `deleted from disk`, which is wrong 😯, please see the gif below.
![dirty-file](https://cloud.githubusercontent.com/assets/2239563/24540210/6ffd836e-15f2-11e7-96a1-7b18d4973bbe.gif)

**Comment by bpasero** [comment]
@michelkaporin I cannot reproduce, on what OS?

**Comment by bpasero** [comment]
I can reproduce only on Windows, seems like a timing issue.

**Comment by michelkaporin** [comment]
@bpasero yes, Windows 👍
