### ISSUE TITLE
The hand pointer blocks EVERY XXXXX hovertip. Fix this ISHT!

### ISSUE THREAD

**Issue by ObiW4nKenobi** [microsoft/vscode#225284]
Type: <b>Bug</b>

How do you reproduce? Simply hover the damn hand mouse icon over anything that pops up a hover tip. The text is always blocked by the damn mouse hand icon. Fix this ISHT! This is stupid!!!

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics     (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|14.93GB (2.56GB free)|
|Process Argv|--crash-reporter-id 3bf867c5-675a-48a0-beb5-558ba403c712|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
csdevkit|ms-|1.9.55
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.1
vscodeintellicode-csharp|ms-|2.1.11
cpptools|ms-|1.21.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
ccpltc:31103427
pythonrstrctxtcf:31103194
wkspc-onlycs-t:31111718
wkspc-ranged-t:31111713

```

</details>

**Comment by aiday-mar** [comment]
Hi thanks for opening this issue. I am not sure I quite understand what you mean by 'The text is always blocked by the damn mouse hand icon'. Could you please add a screen recording showing the issue?

**Comment by xbb** [comment]
Maybe duplicate/related https://github.com/microsoft/vscode/issues/157430#issuecomment-1645778209

It might be subjective but in Windows it helps a lot if you customize the cursor (Link Select in the mouse pointer settings) to a smaller one.

The default one in Windows is definitely larger than the one macOS.

**Comment by aiday-mar** [comment]
Since the OP has not responded. This issue will be closed
