### ISSUE TITLE
Mouse cursor changing rapidly when placed between lines of source control?

### ISSUE THREAD

**Issue by MikeRich88** [microsoft/vscode#225283]
Type: <b>Bug</b>

1. Needs to be a retina Mac OS screen.
2. Place cursor between 2 lines of source control in the icons area. The area the issue occurs is only 1 (actual) pixel tall.

See video

VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin x64 22.6.0
Modes:
Remote OS version: Linux x64 5.14.0-284.30.1.el9_2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (4.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: orwell.revenueuniverse.com|
|OS|Linux x64 5.14.0-284.30.1.el9_2.x86_64|
|CPUs|DO-Regular (1 x 0)|
|Memory (System)|1.72GB (0.62GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
composer-php-vscode|DEV|1.49.15728
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.49.15728
profiler-php-vscode|DEV|1.49.15728
php-debug|xde|1.35.0

</details>

https://github.com/user-attachments/assets/1bf2cdfc-1264-44c6-9457-80de5eb58cd3

**Comment by MikeRich88** [comment]
It keeps saying I need to enter my password to install a helper tool and I have been pressing cancel.

Is pressing cancel preventing an update from installing?

Why does it need to ask this every time it seems?

**Comment by MikeRich88** [comment]
<img width="290" alt="image" src="https://github.com/user-attachments/assets/11060a44-7c39-4697-aece-c18b7ebc52f7">
That's what it shows. I have 500 mbit fiber here. Nothing is really downloading.

**Comment by lszomoru** [comment]
@deepak1556, have you seen this behaviour before? Thanks!

**Comment by lszomoru** [comment]
@MikeRich88, are you still able to reproduce this with the latest VS Code release? Thanks!
