### ISSUE TITLE
CTRL+Scroll doesn't zoom in / zoom out

### ISSUE THREAD

**Issue by Smile4ever** [Microsoft/vscode#22521]
- VSCode Version: 1.10.2
- OS Version: Windows 10

*  CTRL+Plus / CTRL+Min works
*  CTRL+Scroll (mouse wheel) doesn't work to zoom in / zoom out

**Comment by linkdesu** [comment]
Have you ever switch the config on? You can find it in the `settings.json`:

```
// Zoom the font of the editor when using mouse wheel and holding Ctrl
  "editor.mouseWheelZoom": false,
```

**Comment by Smile4ever** [comment]
I wasn't aware of this. Is there a similar setting for CTRL+0?

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@Smile4ever By default you can use Ctrl + 0 on the numeric keypad to reset the zoom.

Ctrl +0 on the non-nemeric keyboard has another function by default.

`{ "key": "ctrl+0",                "command": "workbench.action.focusSideBar" }`

But you can change that.

Go to File> Preferences> keyboard Shorcuts. In the keybindings.json file put:

`{"Key": "ctrl+0", "command": "workbench.action.zoomReset"}`
