### ISSUE TITLE
Shell syntax broken on code embedded in string

### ISSUE THREAD

**Issue by zgoda** [Microsoft/vscode#22525]
- VSCode Version:
```
Version 1.10.2
Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
Date 2017-03-08T14:00:46.854Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```
- OS Version:
```
$ lsb_release -idrc
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
Embedding shell code in string breaks syntax scheme on word "function" below:

![zrzut ekranu z 2017-03-13 13-21-34](https://cloud.githubusercontent.com/assets/141999/23854080/07654c0c-07f0-11e7-8a88-002a81bfbb9f.png)

This is consistent across all colour themes.

Test case:

```
    if ! fnExists "platform_${__platform}"; then
        fatalError "Set the __platform variable: $(compgen -A function platform_ | cut -b10- | paste -s -d' ')"
    fi
```

**Comment by aeschli** [comment]
This issue was moved to textmate/shellscript.tmbundle#36
