### ISSUE TITLE
Not able to git pull

### ISSUE THREAD

**Issue by priyankak-metacube** [microsoft/vscode#225243]
Type: <b>Bug</b>

priyanka@priyanka-kumbhar:/var/www/html/BrandSites-WhiteLabel$ git pull
remote: The  organization has enabled or enforced SAML SSO.
remote: To access this repository, you must re-authorize the OAuth Application 'GitHub for VS Code'.
fatal: unable to access '': The requested URL returned error: 403

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 5.15.0-117-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.38GB (1.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
drupal-smart-snippets|and|2.1.0
vscode-intelephense-client|bme|1.12.2
vscode-eslint|dba|3.0.8
empty-indent|Dmi|0.2.0
drupal-8-snippets|dss|0.0.2
gitlens|eam|15.2.3
prettier-vscode|esb|10.4.0
composer|ika|0.8.0
twig-language-2|mbl|0.9.4
vscode-docker|ms-|1.29.1
remote-containers|ms-|0.380.0
php-docblocker|nei|2.7.0
vscode-phpcbf|per|0.0.8
phpcs|she|1.0.8
drupal-8-javascript-snippets|tse|0.0.2
drupal-8-twig-snippets|tse|1.0.2
indent-one-space|use|1.0.0
vscode-phpsab|val|0.0.18
twig|wha|1.0.2
php-debug|xde|1.35.0
php-intellisense|zob|1.3.3

</details>

**Comment by lszomoru** [comment]
@priyankak-metacube, are you running git pull from the integrated terminal in VS Code? 
What happens if you are trying to run git pull from an external terminal? Thank you!

**Comment by priyankak-metacube** [comment]
When i try git pull from external terminal : it is working fine

**---------------------------------------------------------------------------------------------------------------------**
When i try git pull from integrated terminal in VS Code : it is showing below error

****priyanka@priyanka-kumbhar:/var/www/html/BrandSites-WhiteLabel$** git pull
remote: The organization has enabled or enforced SAML SSO.
remote: To access this repository, you must re-authorize the OAuth Application 'GitHub for VS Code'.
fatal: unable to access '': The requested URL returned error: 403**

**Comment by lszomoru** [comment]
@priyankak-metacube, are you signed in to VS Code with your GitHub account? 
Could you try signing out, signing back in with your GitHub account? Thanks!
