### ISSUE TITLE
Wrong current directory in terminal when path contain special characters like square brackets

### ISSUE THREAD

**Issue by Maher-AnasIQ** [microsoft/vscode#225280]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.0 (system setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
- OS Version: Windows 11 Pro 23H2 Build 22631.3880

### Steps to Reproduce:

1. Create or rename a folder with a name that contains square brackets "[" or "]"
2. open said folder with VSCode
3. open a new terminal and notice current directory is "C:\WINDOWS\System32\WindowsPowerShell\v1.0> " instead of the actual folder opened

### More Info:

- I noticed the issue when I tried running an NPM Script that failed with the error "Could not read package.json: Error: ENOENT: no such file or directory"
- package.json exist
- vscode lists scripts on the side panel
- scripts work as expected when I remove square brackets from folder name
- in powershell square brackets need to be escaped with backtick (`) in paths AFAIK so this might be a hint to the cause of the issue?

**Comment by meganrogge** [comment]
see https://github.com/microsoft/vscode/issues/145441#issuecomment-1347481575

**Comment by Maher-AnasIQ** [comment]
thank you for taking the time.
as stated in my issue, I'm aware that the issue is caused by PowerShell on WIndows and suggested that a possible solution is to escape the square brackets with a backtick.
eg ``cd 'd:\`[dir`]'``

I am able to change directory in terminal using the method above, however NPM scripts (in the side bar) does not work

the comment you linked does not provide a solution. so I think the issue still stands.
please reconsider.
