### ISSUE TITLE
Terminal input glitching

### ISSUE THREAD

**Issue by nicolanapa** [microsoft/vscode#225232]
Type: <b>Bug</b>

Since a few days when I type in the terminal it starts to glitch out the text
It doubles sometimes the text and then goes on a new line (can't explain it well)
And other times it doesn't show the right text position

Here's an example:
```
git add src/tests/fetchProduct.test.js && git commit -m "Added initial test to test if it fetches correctly a Product"   ectly a Product"

[development 509faf1] Added initial test to test if it fetches correctly a Product
 1 file changed, 5 insertions(+)
```

VS Code version: Code - Insiders 1.93.0-insider (4693ac3d4dce852b747d08d4bc54db5e35afe268, 2024-08-09T06:29:39.564Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7800X3D 8-Core Processor            (16 x 4192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.65GB (23.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
prettier-vscode|esb|10.4.0
vscode-language-pack-it|MS-|1.92.2024080709
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
material-icon-theme|PKi|5.8.0
open-in-browser|tec|2.0.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1

</details>

**Comment by meganrogge** [comment]
pls provide a gif

**Comment by nicolanapa** [comment]
![Recording 2024-08-10 at 10 17 17](https://github.com/user-attachments/assets/9204e96b-c91d-4fe6-bbe3-3db5de174ad6)

Here's the first glitch I mentioned

**Comment by Tyriar** [comment]
Should be fixed by https://github.com/microsoft/node-pty/pull/703 / https://github.com/microsoft/vscode/pull/225266
