### ISSUE TITLE
inline chat opens above editor lines

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#225288]
1. create a new markdown document
2. on line 1 of the editor, open inline chat and issue a request to generate content in the file
3. see the inline chat widget open above the editor lines
4. I expected it to not be above the editor lines, but maybe this is by design?

![Image](https://github.com/user-attachments/assets/82252499-0309-44f6-b87f-83d20e259d02)

**Comment by jrieken** [comment]
It be design because we stream in newly generated contents/lines and that should continuously push down the widget
