### ISSUE TITLE
Ability to have multiple selections added to the context

### ISSUE THREAD

**Issue by cloudbow** [microsoft/vscode#225245]
I would like to have more like a partial integration test where I look at the stack trace of a failed python application and find certain sections of code to be added to the context from different python files. When I tried doing this using cmd+/ , it was able to append the selection to the context, but when I navigated the stack and identified another section of code in another file I see that I can't no longer do the selection because it seems the context can have only 1 selection possible.

It will be extremely useful if vscode provides the ability to create a test case by referring fragments of sections of code from files in stack trace. I could fix errors, especially errors from server console to reproduce it locally very easily with the generated test case. Also remember that if I add test case for the whole file I might go over the context limit . This can help keep the context length within limit but create test cases.

**Comment by roblourens** [comment]
I'm able to add multiple selections to the chat. Can you explain some more? I'm not sure I follow.

**Comment by roblourens** [comment]
Maybe you are looking at the `#selection` variable, that is the one current selection, but in this case you maybe want to do right click > copilot> add selection to chat
