### ISSUE TITLE
I cannot switch tabs by touch gestures in Surface Pro 3.

### ISSUE THREAD

**Issue by scientist2009** [Microsoft/vscode#22523]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|cpptools|ms-vscode|0.10.2|
|vs-keybindings|ms-vscode|0.1.3|

---

Steps to Reproduce:

1.Use the vscode in a Surface Pro 3.
2.Open two source file with vscode.
3.Select a tab between the two source file, and touch it. I cannot switch tab by touch gestures. Please fix it.

**Comment by bpasero** [comment]
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment]
Verification:
* tabs can be opened via touch
* tab context menu can be triggered via touch long press
* tabs can be scrolled (if there is a scrollbar) using touch gesture

**Comment by roblourens** [comment]
Trying on a surface book, all of it works much better than 1.17.

But when showTabs disabled, it's almost impossible to switch tabs by touch. I can do it if I touch just right.

**Comment by bpasero** [comment]
@roblourens extracted that into https://github.com/Microsoft/vscode/issues/37671
