### ISSUE TITLE
Missing window border with `window.titleBarStyle` setting set to `custom`

### ISSUE THREAD

**Issue by uRohan** [microsoft/vscode#225257]
Type: <b>Bug</b>

Steps to Reproduce:

1. Open Visual Studio Code.
2. Open the Settings editor by navigating to `File` > `Preferences` > `Settings` or using the keyboard shortcut (`Ctrl`+`,`).
3. Change the `window.titleBarStyle` setting from `native` to `custom`.
5. Split the screen between Visual Studio Code and another application.

Observed Behavior:

The window border is missing when the `"window.titleBarStyle": "custom"` setting is enabled.

Expected Behavior:

Visual Studio Code should display a window border regardless of whether the `window.titleBarStyle` setting is set to `native` or `custom`.

Here's what it looks like:

| `"window.titleBarStyle": "native"` | `"window.titleBarStyle": "custom"` |
| ---------------------------------- | ---------------------------------- |
| [Screencast from 08-09-2024 06:23:49 PM.webm](https://github.com/user-attachments/assets/d9cbe054-507c-4273-84fa-385de5ea402b) | [Screencast from 08-09-2024 06:22:20 PM.webm](https://github.com/user-attachments/assets/d07ea62c-df06-48cf-a535-fa253e4d3be0) |
| ![Screenshot from 2024-08-09 00-29-44](https://github.com/user-attachments/assets/39ea4514-04c4-47e1-ab20-dcbd13801ad1) | ![Screenshot from 2024-08-09 00-32-51](https://github.com/user-attachments/assets/245a15d9-bf7b-4ed2-895d-ce02248fddf5) |
| ![Screenshot from 2024-08-09 00-29-49](https://github.com/user-attachments/assets/b72559cb-7ec7-467a-8e30-78fd95c68809) | ![Screenshot from 2024-08-09 00-32-42](https://github.com/user-attachments/assets/e3eb5dcc-f46e-4951-9c77-a8ac92e802b8) |

Additional Information:

This issue appears to have started with the Visual Studio Code version 1.92.1 update. I attempted to revert to version 1.92.0 using `sudo snap revert code --revision 165` and also tried reinstalling the previous version with `sudo snap install code --classic --revision 165` to take a screenshot of how it looked before. However, the bug persists in both cases, whether I reverted the existing version or reinstalled the previous one.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z), Code - Insiders 1.93.0-insider (4693ac3d4dce852b747d08d4bc54db5e35afe268, 2024-08-09T06:29:39.564Z)
OS version: Linux x64 6.5.0-45-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (8 x 3078)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|3, 1, 1|
|Memory (System)|7.63GB (4.53GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 5253c5c3-f097-4349-a530-63f20f5445f1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
da93g388:31013173
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
nb_pkg_only:31057982
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31105043
wkspc-onlycs-t:31111718
nativeloc1:31111755
wkspc-ranged-c:31111712
3ad50483:31111987
fcdif617:31111928

```

</details>

**Comment by benibenj** [comment]
I don't believe this is new, if I remember correctly the application did no use to have a border.  @bpasero do you know of any change here?

**Comment by bpasero** [comment]
When custom title is enabled, all window frame decoration is gone, but you can set a color for the window border via settings then, at least on macOS and Linux:

```json
"workbench.colorCustomizations": {
    "window.activeBorder": "#ff0000"
  }
```

**Comment by uRohan** [comment]
Thanks, I found out about this setting while filling out the issue, but I'm fairly certain it was enabled by default before (though I could be wrong). However, without the active border enabled, it looks strange to me. The Visual Studio Code window blends in with other applications in split-screen mode.

Additional screenshot:

![Screenshot from 2024-08-09 00-00-05](https://github.com/user-attachments/assets/d81611f7-0728-49de-873b-69f55664953a)

I'm okay with that if it's by design.

**Comment by benibenj** [comment]
This depends on the theme you are using so this is by design. Some themes set a color for the border and others do not (such as the theme you are using).
