### ISSUE TITLE
Clarify an option on overflow menu of Incoming/Outgoing in Source Control view

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#225230]
Type: <b>Feature Request</b>

I like it that the `...` menu now has a way of toggling between graph view and list view, but I think the wording of the option could be improved:

![image](https://github.com/user-attachments/assets/c6343bea-2dc4-4e3c-ae21-83a47c598388)

Instead of "Show Incoming/Outgoing Changes" I suggest "Show as Graph". Or break up the "Show" repetition by using "Display as Graph".

VS Code version: Code - Insiders 1.93.0-insider (4693ac3d4dce852b747d08d4bc54db5e35afe268, 2024-08-09T06:29:39.564Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by lszomoru** [comment]
Closing this issue as Incoming/Outgoing section has been removed from the main "Source Control" view.
