### ISSUE TITLE
TS crashes all the time

### ISSUE THREAD

**Issue by ReptoxX** [microsoft/vscode#225228]
Type: <b>Bug</b>

Having a NX Workspace running a NestJS Application with Mikro-ORM constantly crashes the ts server.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Darwin arm64 23.5.0
Modes:
Remote OS version: Linux x64 5.15.0-112-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 2, 3|
|Memory (System)|32.00GB (0.56GB free)|
|Process Argv|--crash-reporter-id 88480f18-46d6-42ca-821e-adb9b362d97b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Coder: terzibaschian∕eLoyalty∕main|
|OS|Linux x64 5.15.0-112-generic|
|CPUs|AMD EPYC 7502P 32-Core Processor (20 x 0)|
|Memory (System)|58.85GB (46.58GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-neovim|asv|1.18.7
catppuccin-vsc|Cat|3.15.1
coder-remote|cod|1.3.1
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.5.2024070409
remote-server|ms-|1.6.2024070809
material-icon-theme|PKi|5.8.0
catppuccin-perfect-icons|tha|0.21.32
jinja|who|0.0.8
vscode-tailwindcss|bra|0.12.5
prettier-vscode|esb|10.4.0
export-typescript|msc|0.4.2
supermaven|Sup|1.0.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
