### ISSUE TITLE
Relative paths sometimes not included as links in integrated terminal 

### ISSUE THREAD

**Issue by markwpearce** [Microsoft/vscode#22528]
- VSCode Version:  1.10.2
- OS Version: Mac OSX (10.11.6)

Steps to Reproduce:

1. Open VS Code integrated terminal
2. Echo a relative path (eg. ```echo "src/app.js"```)

Description:

Let's say you have a build system that outputs a stack trace on a build error or failed test. If this was run from the integrated terminal, the file paths in the output should be included as clickable links which can be clicked to open the file in VSCode.

However, this only works if the path is either an absolute path (e.g. ```~/work/project/src/app.js```) or a relative path that begins with "./". 

Many build systems and tools output file paths relative to the directory the command was run, without the leading "./", Karma for example. So the output would be something like: ```src/app.js```, not ```./src/app.js```. The first is not matched by VSCode as an openable path, but the second is.

I believe that what is determined to be a path comes from the Regex in "terminalLinkHandler.ts"

Is there a reason why relative paths of this form (e.g. no leading "./") are not included?

**Comment by Tyriar** [comment]
The reason was because until 1.11 links aren't validated so there would be heaps of false positives. Performance was also a factor but it shouldn't impact that much really now that I think about it.

Now that links are validated maybe we should be more lenient when linkifying.

**Comment by Tyriar** [comment]
I'll assign this to April but if someone wants to do a PR before then you're welcome. You will need to:

- Modify the regex to allow paths that are not qualified with `~/`, `./`, etc.
- Make sure that the new path matcher does not conflict with previously matched links and does not create links with adjacent characters. Eg. we want to avoid this: `~/<a>link</a>`

**Comment by markwpearce** [comment]
Nice. I'll write a PR...

**Comment by Tyriar** [comment]
That would be awesome @markwpearce :+1:

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/22602
