### ISSUE TITLE
Give an option to show files before directories in file explorer

### ISSUE THREAD

**Issue by claudioc** [Microsoft/vscode#22529]
There are project structures which would greatly benefit from being able to show the files of a directory before other subdirectories inside them. This is what I see for example in a project of mine (an Ember application using the POD structure)

![screen shot 2017-03-13 at 14 32 44](https://cloud.githubusercontent.com/assets/166692/23856551/5962d524-07fa-11e7-88ac-5363d98ba875.png)

As you can see there's a lot of repetions, names wise, which gives quite a bad overview of the whole components structure. If the `component.js` and `template.hbs` would appear before any other "sub-components" directory, it would increase the readability of the structure.

**Comment by claudioc** [comment]
Alternatively, highlight the files the current selected directory are part of (in the example, just the component.js and template.hbs right below "user-details-tab")

**Comment by bpasero** [comment]
Landed via https://github.com/Microsoft/vscode/pull/29509

Setting to use: `"explorer.sortOrder": "filesFirst"`
