### ISSUE TITLE
No notification on newer Version availability.

### ISSUE THREAD

**Issue by foo-baar** [Microsoft/vscode#22520]
Recently while troubleshooting task.json file I learned about the newer version of code from @dbaeumer, vscode never notified me on the availability of newer version.

(At that time I was using 1.8.1, on Mac Sierra)

Vscode should notify user when a new version has been pushed live.

(yes, even after changing `update.channel: "none"`).

**Comment by joaomoreno** [comment]
But that's exactly what that setting is for: no updates.

**Comment by joaomoreno** [comment]
There are update notifications on our blog, twitter, github, etc.

**Comment by foo-baar** [comment]
@joaomoreno I guess I misunderstood the `update.channel: "none"`, However by default vscode ships with settings to `"update.channel":"default"`, but it never showed me the update notification, hence I changed it to none later, but still never got update.

On learning that there is a newer version available I tried to find an option within vscode to update it or check, but there is no such feature available.

If we are expecting people of only stay updated via blogs. twitter..... for updates then we lack this feature (atleast that's I feel about it). Your call.

Danke

**Comment by joaomoreno** [comment]
> However by default vscode ships with settings to "update.channel":"default", but it never showed me the update notification

Then, that's the bug.

Are you behind a proxy?

**Comment by foo-baar** [comment]
Hello @joaomoreno: No I am not.

**Comment by joaomoreno** [comment]
Then something is odd. You definitely should get update notifications.

Try downloading an older version: https://az764295.vo.msecnd.net/stable/653f8733dd5a5c43d66d7168b4701f94d72b62e5/VSCode-darwin-stable.zip

Then, wait a minute and check whether you get an update notification.

**Comment by foo-baar** [comment]
Below is the fix for this issue:
https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150


@joaomoreno  Adding the resolution below, just in case someone like me come here looking for it:
