### ISSUE TITLE
vscode automatically add .i extension after I save as ipynb file

### ISSUE THREAD

**Issue by guocity** [microsoft/vscode#225270]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.92.1
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.1.0

I have try to use new profile without any extension and settings, the issue still there

Steps to Reproduce:

1. command + N create new file
2. command + S save to a ipynb file, 
3. the file will add a new .i extension to the end

**Comment by ClassicMMT** [comment]
I have the same issue

**Comment by bpasero** [comment]
This is a macOS bug fixed in `15.2`.
