### ISSUE TITLE
hiding the file explorer is not working

### ISSUE THREAD

**Issue by iliran11** [Microsoft/vscode#22522]
- VSCode Version: 1.10.2
- OS Version: windows 10 - version 1607

Steps to Reproduce:

1. open View toolbar
2. click on explorer
3. nothing happen.  expected the file explorer to become minimized.

![image](https://cloud.githubusercontent.com/assets/24987188/23853286/8bf0680e-07f4-11e7-9e8d-9d7c2685e472.png)

**Comment by bpasero** [comment]
This command will focus the explorer. What you are looking for is "Toggle Side Bar".
