### ISSUE TITLE
Terminal letters are scattered

### ISSUE THREAD

**Issue by sijocherian23** [microsoft/vscode#225234]
Type: <b>Bug</b>

There is some issue withh my vs  code terminal that i can t read letters becuse all of the letters were scattered

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Linux x64 6.5.0-45-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 3199)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|31.13GB (18.66GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 6437ede4-6afe-4dd5-b197-6cc484f56862|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|15.2.3
copilot|Git|1.221.0
copilot-chat|Git|0.18.1
vscode-graphql-syntax|Gra|1.3.6
graphql|mqu|0.1.2
vscode-docker|ms-|1.29.1
material-icon-theme|PKi|5.8.0
vscode-thunder-client|ran|2.24.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
ccpltc:31103427
pythonrstrctxt:31103193
wkspc-onlycs-t:31111718
wkspc-ranged-t:31111713

```

</details>

**Comment by huycozy** [comment]
This seems to appear to me as well. I can't finish my command from Terminal tab, for eg:

```console
flutter run -t lib/main_tf.dart -d web-server^M ^?
```

When I entered `Backspace` key, it turned to `^?`, and `Enter` turned to `^M`.
