### ISSUE TITLE
Source Control crashes the App

### ISSUE THREAD

**Issue by kodcuserkan** [microsoft/vscode#225227]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.92.1 (Universal)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z (1 day ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

- OS Version: MacOS Sonoma Version 14.5 (23F79)

Steps to Reproduce:

VsCode does not loading Source Control or loading very very slow and crashing

![Screenshot 2024-08-09 at 10 38 50](https://github.com/user-attachments/assets/b5694981-ba83-4624-b1f8-e67817c203f4)

**Comment by kodcuserkan** [comment]
https://github.com/user-attachments/assets/3604d163-1756-4e14-b5fb-1662e8ec8d17

After approx. 2 minutes:

**Comment by gjsjohnmurray** [comment]
@kodcuserkan does the setting `"scm.showHistoryGraph": false` fix it for you?

**Comment by kodcuserkan** [comment]
@gjsjohnmurray Yes it fixed, thank you, but as I see graph is disabled right? (Not important for me though)

**Comment by gjsjohnmurray** [comment]
Right. The new graph feature is known to have performance and resource consumption issues in some situations. @lszomoru is working on resolving these.

**Comment by JoonaV556** [comment]
I can confirm source control is working extremely slow on my end too after the June update.

**Comment by kodcuserkan** [comment]
> @kodcuserkan does the setting `"scm.showHistoryGraph": false` fix it for you?

This can be thought a fix until graph work done.
