### ISSUE TITLE
[loc][Query][VSCode] Please clarify all three placeholders

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#22538]
Hi, we have a question from our translator. Can you help please? Thanks!

**Source:**
Install the keyboard shortcuts of {0}, {1}, {2} and {3}

**File Name:**
src\vs\workbench\parts\welcome\page\electron-browser\vs_code_welcome_page.nls.resx

**Resource ID:**
".resx", 0; "welcomePage.installKeymap"

**Query:**
Please advise what the placeholders stand for. Thanks!

**Comment by chrmarti** [comment]
Currently that is Vim, Sublime, Atom and others. These four are shown as links on the welcome page, hence the placeholder.
