### ISSUE TITLE
Breakpoints creation and triggering not workling properly.

### ISSUE THREAD

**Issue by srikiran97** [microsoft/vscode#225397]
Type: <b>Bug</b>

- Add a break point in any one file.
- Add another break point in another file.
-  The breakpoint added in first file changes to the line no of the breakpoint added in second file.
- This happens irregularly.

VS Code version: Code 1.92.1 (Universal) (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (1.28GB free)|
|Process Argv|--crash-reporter-id 8279c7ad-6a8a-40e0-9425-e6ccdf762cf4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
dart-code|Dar|3.94.0
flutter|Dar|3.94.0
gitlens|eam|15.2.3
bloc|Fel|6.6.6
dart-data-class-generator|hzg|0.5.4
git-graph|mhu|1.30.0
cpptools|ms-|1.21.6
color-highlight|nau|2.8.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|5.9.0
iconfont-preview|stx|0.0.5
togglebracketguides|TGO|0.1.6
errorlens|use|3.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-t:31111713

```

</details>

**Comment by srikiran97** [comment]
Any updates on this issue? Will it be fixed??... Its quite annoying to use the IDE for debugging.

**Comment by roblourens** [comment]
What language? Can you give more details?

**Comment by srikiran97** [comment]
Am using dart language for flutter framework. The issue occurs when the app is running and while debugging, if i try to add a new breakpoint on the file where the breakpoint has already hit, the new breakpoint's line no is replaced for all the breakpoint that is already there in the file in a random manner.

**Comment by srikiran97** [comment]
Kindly reopen the issue.
