### ISSUE TITLE
Slow Renderer for Text pull

### ISSUE THREAD

**Issue by rswiney86** [microsoft/vscode#225339]
Type: <b>Bug</b>

Auto-generated text from notebook cell performance. The duration for the renderer, VS Code Builtin Notebook Output Renderer, is slower than expected.
Execution Time: 3ms
Renderer Duration: 2ms

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7840HS w/ Radeon 780M Graphics      (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|28.79GB (11.98GB free)|
|Process Argv|--crash-reporter-id 9274227c-1527-4806-b082-dbc3ef2d2e12|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
arepl|alm|2.0.5
appmap|app|0.125.0
vscode-django|bat|1.15.0
codeium|Cod|1.10.11
gitignore|cod|0.9.0
python-snippets|cst|0.1.2
vscode-markdownlint|Dav|0.55.0
vscode-dash|dee|2.4.0
python-extensions-pack|dem|1.0.3
composer-php-vscode|DEV|1.49.15728
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.49.15728
profiler-php-vscode|DEV|1.49.15728
python-preview|don|0.0.4
git-extension-pack|don|0.1.3
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.2.3
prettier-vscode|esb|10.4.0
copilot|Git|1.221.0
copilot-chat|Git|0.18.1
vscode-test-explorer|hbe|2.21.1
python-resource-monitor|kai|0.2.3
vsc-python-indent|Kev|1.18.0
vscode-python-test-adapter|lit|0.8.2
nmap-peek|mar|2.0.3
vsc-webshark|mbe|2.1.0
document|min|2.2.2
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.10.0
python|ms-|2024.12.2
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
test-adapter-converter|ms-|0.1.9
windows-ai-studio|ms-|0.4.0
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
indent-rainbow|ode|8.3.1
vscode-xml|red|0.27.1
LiveServer|rit|5.7.9
xml-toolkit|SAP|1.1.0
sourcery|sou|1.21.0
code-spell-checker|str|3.0.1
vscode-djaneiro|the|1.4.2
wolf|tra|0.4.3
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
livecode|xir|1.3.10
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-c:31111712

```

</details>

**Comment by rebornix** [comment]
@rswiney86 may I ask what performance issue in particular you are running into? It would be great if you can share more details to help us troubleshoot.
