### ISSUE TITLE
Source code control does not upload changes.

### ISSUE THREAD

**Issue by romuloroc** [microsoft/vscode#225340]
Type: <b>Bug</b>

Source code control does not load changes after upgrading from 1.91 to 1.92. The loading process does not stop and does not display the changes in the sidebar.
Source code control does not load changes.
After a few minutes, when loading, I can't remove forceignore.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.87GB (6.84GB free)|
|Process Argv|--crash-reporter-id 518189b7-011b-4b18-b50c-7c1244fd8e96|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (95)</summary>

Extension|Author (truncated)|Version
---|---|---
amphtml-validator|amp|1.2.0
atlascode|atl|3.0.10
npm-intellisense|chr|1.4.5
apex-pmd|chu|0.7.0
salesforce-diff|chu|0.0.7
dbclient-jdbc|cwe|1.3.5
vscode-database-client2|cwe|7.5.7
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.3
delphilsp|Emb|1.0.1
prettier-vscode|esb|10.4.0
figma-vscode-extension|fig|0.3.5
lana|Fin|1.16.0
vscode-firefox-debug|fir|2.9.10
codespaces|Git|1.17.2
copilot|Git|1.221.0
copilot-chat|Git|0.18.1
remotehub|Git|0.62.0
vscode-pull-request-github|Git|0.94.0
gitlab-workflow|Git|5.4.0
Ionide-fsharp|Ion|7.20.3
materialdesignicons-intellisense|luk|4.1.0
git-graph|mhu|1.30.0
vscode-exec-node|mir|0.5.6
azure-pipelines|ms-|1.228.0
azure-dev|ms-|0.8.3
vscode-azureappservice|ms-|0.25.2
vscode-azurecontainerapps|ms-|0.7.0
vscode-azurefunctions|ms-|1.15.2
vscode-azureresourcegroups|ms-|0.9.1
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.16.0
vscode-azurevirtualmachines|ms-|0.6.5
vscode-cosmosdb|ms-|0.22.0
vscode-docker|ms-|1.29.1
vscode-language-pack-pt-BR|MS-|1.92.2024080709
csharp|ms-|2.39.29
dotnet-interactive-vscode|ms-|1.0.5229040
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.1.1
vscode-dotnet-sdk|ms-|0.8.0
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.2
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
azure-account|ms-|0.12.0
azure-repos|ms-|0.38.0
js-debug-nightly|ms-|2024.8.817
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.2
vscode-node-azure-pack|ms-|1.2.0
material-icon-theme|PKi|5.9.0
vscode-thunder-client|ran|2.24.13
java|red|1.33.0
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
analyticsdx-vscode|sal|1.2.1
salesforcedx-vscode|sal|61.8.1
salesforcedx-vscode-apex|sal|61.8.1
salesforcedx-vscode-apex-debugger|sal|61.8.1
salesforcedx-vscode-apex-replay-debugger|sal|61.8.1
salesforcedx-vscode-core|sal|61.8.1
salesforcedx-vscode-expanded|sal|61.8.1
salesforcedx-vscode-lightning|sal|61.8.1
salesforcedx-vscode-lwc|sal|61.8.1
salesforcedx-vscode-soql|sal|61.8.1
salesforcedx-vscode-visualforce|sal|61.8.1
sfdx-code-analyzer-vscode|sal|1.0.0
vscode-simple-icons-rev|Sha|1.16.2
vscode-stylelint|sty|1.4.0
tw-dev-server|tre|1.0.1
sort-lines|Tyr|1.11.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.28.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-spring-initializr|vsc|0.11.2
vscode-icons|vsc|12.8.0
console-ninja|Wal|1.0.339

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717

```

</details>

**Comment by gjsjohnmurray** [comment]
I suggest you try the setting `"scm.showHistoryGraph": false`

The release notes explain the feature this setting relates to.
