### ISSUE TITLE
[loc][Query][VSCode] Localizability of "legacy"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#22531]
Hi, we have a question from our translator. Can you help please? Thanks!

**Source:**
Cannot connect to runtime via 'legacy' protocol; consider using 'inspector' protocol (timeout after {0} ms).

**File Name:**
out\node\nodeDebug.nls.resx

**Resource ID:**
".resx", 0; "VSND2009"

**Query:**
Should "legacy" be translated? Thanks!

**Comment by cacothi** [comment]
+1

**Comment by weinand** [comment]
'legacy' and 'inspector' should not be translated because both are options the user has to use literally in a configuration file.
For the next translation drop I will extract both from the string and add them as a '{n}' parameter.
Is this correct?
