### ISSUE TITLE
Scrollbar handle moves by itself when scrolling pass certain function

### ISSUE THREAD

**Issue by AuroraLantean** [microsoft/vscode#225348]
- VS Code Version: 1.92.1
- OS Version:  Linux Mint 22

Steps to Reproduce:

1. clone my repo: https://github.com/AuroraLantean/subtensor
2. Open `pallets/subtensor/src/epoch.rs`
3. Scroll down pass `epoch()`
4. See the scroll bar starts to move down by itself

**Comment by roblourens** [comment]
I can't repro and I don't understand what the issue would be, can you explain more or include a screen recording?
