### ISSUE TITLE
> reload window

### ISSUE THREAD

**Issue by amp127** [microsoft/vscode#225309]
Type: <b>Bug</b>

if i > reload window my terminals dont come back and show any output, i  have to terminate the windows. Its only with the latest version. 

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.91GB (22.78GB free)|
|Process Argv|--crash-reporter-id 457eb537-3567-4d69-9d3f-01c9d5182bc8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (22 x 0)|
|Memory (System)|31.30GB (22.16GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
simple-react-hooks-snippets|bry|1.0.0
postcss|css|1.0.9
auto-close-tag|for|0.5.15
dotenv|mik|1.0.1
remote-wsl|ms-|0.88.2
errorlens|use|3.20.0
JavaScriptSnippets|xab|1.8.0
vscode-openai|And|1.6.7
tailwind-docs|aus|2.1.0
vscode-tailwindcss|bra|0.12.6
simple-react-snippets|bur|1.2.8
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
gitlens|eam|15.2.3
prettier-vscode|esb|10.4.0
copilot|Git|1.221.0
copilot-chat|Git|0.18.1
todo-tree|Gru|0.0.226
prettier-eslint-typescript|hb4|1.0.5
tailwind-config-viewer|Kal|0.0.86
vscode-language-babel|mgm|0.0.40
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.1
vsliveshare|ms-|1.0.5936
color-highlight|nau|2.8.0
indent-rainbow|ode|8.3.1
vs-code-prettier-eslint|rve|6.0.0
firacode|Sey|2.2.1
code-spell-checker|str|3.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31111713

```

</details>

**Comment by meganrogge** [comment]
a gif would help
