### ISSUE TITLE
[loc][Query][VSCode] Please clarify localizability for words in quotes

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#22534]
Hi, we have a question from our translator. Can you help please? Thanks!

**Source:**
Controls the wrapping column of the editor when `editor.wordWrap` is 'wordWrapColumn' or 'bounded'.

**File Name:**
src\vs\editor\common\config\commonEditorConfig.nls.resx

**Resource ID:**
".resx", 0; "wordWrapColumn"

**Query:**
Please confirm if the parts in quotes should be localized or not. We assume that `editor.wordWrap` and 'wordWrapColumn should not be localized, but what about 'bounded'? Thanks!

**Comment by alexandrudima** [comment]
Also 'bounded' should not be localized. I have pushed a commit that adds comments to clarify these strings. Thank you!
