### ISSUE TITLE
Terminal console text reappears after clearing

### ISSUE THREAD

**Issue by Vidhan31** [microsoft/vscode#225328]
Type: <b>Bug</b>

After we clear terminal console text and resize terminal height by dragging panel up and down, the cleared console text reappears one by one as we continue to drag panel up and down.

Expected result: Cleared console texts must not reappear
Actual result: Cleared console texts reappears

GIF:

![Recording 2024-08-10 234216](https://github.com/user-attachments/assets/393fd85d-7aea-46ec-8d7d-f47ec0c4893c)

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitstash|art|5.2.0
githistory|don|0.6.20
vscode-html-css|ecm|2.0.10
help-me-add|eve|1.0.1
copilot|Git|1.221.0
copilot-chat|Git|0.18.1
live-server|ms-|0.4.14
powershell|ms-|2024.2.2
material-icon-theme|PKi|5.9.0

</details>

**Comment by meganrogge** [comment]
/duplicate https://github.com/microsoft/vscode/issues/75141#issuecomment-1845733788
