### ISSUE TITLE
[loc][Query][VSCode] Please clarify localizability

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#22536]
Hi, we have a question from our translator. Can you help please? Thanks!

**Source:**
e.g. /Users/Development/myProject/myFolder/myFile.txt
e.g. myFolder/myFile.txt

**File Name:**
extensions\configuration-editing\out\settingsDocumentHelper.nls.resx

**Resource ID:**
".resx", 0; "activeEditorLong"
".resx", 0; "activeEditorMedium"

**Query:**
Is the path in source text localizable? Thanks!

**Comment by bpasero** [comment]
@josefhosek no, the path can stay like that 👍
