### ISSUE TITLE
terminal tab is not working

### ISSUE THREAD

**Issue by virskor** [microsoft/vscode#225372]
Type: <b>Bug</b>

terminal tab is not working well, 

VS Code version: Code 1.92.1 (Universal) (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id e0c1c53d-cd1d-42a9-9b27-19d8484cb1ae|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
go-snippets|ban|0.1.2
vscode-intelephense-client|bme|1.12.2
dart-code|Dar|3.95.20240801
flutter|Dar|3.95.20240801
prettier-vscode|esb|10.4.0
go|gol|0.42.0
vue-snippets|hol|1.0.4
code-beautifier|mic|2.3.3
zd-tmpl|mn-|0.0.1
vscode-typescript-next|ms-|5.6.20240811
material-icon-theme|PKi|5.9.0
vue-vscode-snippets|sdr|3.1.1
markdown-preview-enhanced|shd|0.8.13
sass-indented|syl|1.8.31
volar|Vue|2.0.28

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717

```

</details>

**Comment by virskor** [comment]
enter bash run-ios and click tab shoule complete to bash run-ios-release but it changed to bash run-ios     -

**Comment by meganrogge** [comment]
not sure what you mean, a gif would help showing what happens in an external terminal vs what happens in vscode
