### ISSUE TITLE
Command palette closes when Active Terminal killed

### ISSUE THREAD

**Issue by PraneshBalasubramaniam** [microsoft/vscode#225361]
Command palette closes when Active Terminal is killed using command palette terminal list options.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.1
- OS Version: Windows 11 23H2

Steps to Reproduce:
1. Create multiple terminals and open the terminal panel.
2. Open terminal listing in command palette by typing `term `.
3. Kill the active terminal using command palette terminal option.
4. Command Palette closes on killing the terminal.

https://github.com/user-attachments/assets/29042aae-a718-4afb-b056-aeb5cbab2319

Expected Behaviour:
Command palette to be open even after any terminal killed.

Actual Behaviour:
Command palette closes when Active terminal is killed.

**Comment by NriotHrreion** [comment]
The command palette closes only when the last active terminal in the list is killed.

**Comment by nkumawat34** [comment]
can i work on this issue

**Comment by NriotHrreion** [comment]
> can i work on this issue

I have solved this #225500
