### ISSUE TITLE
Creating new profile

### ISSUE THREAD

**Issue by Harold-K** [microsoft/vscode#225316]
Type: <b>Bug</b>

Profile->new profile

Type name and select copy from:  an existing profile

Then want to select checkboxes under "Choose what to configure in your Profile", but that doesn't work I can't check any of checkboxes.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 885cf5eb-b012-4376-a835-906aff3db878|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-dash|dee|2.4.0
erlang-ls|erl|0.0.43
fontsize-shortcuts|fos|1.5.0
todo-tree|Gru|0.0.226
elixir-ls|Jak|0.23.0
rainbow-csv|mec|3.12.0
vscode-edge-devtools|ms-|2.1.5
azure-repos|ms-|0.38.0
live-server|ms-|0.4.14
remote-repositories|ms-|0.40.0
material-icon-theme|PKi|5.8.0
even-better-toml|tam|0.19.2
gistfs|vsl|0.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-c:31111712

```

</details>

**Comment by Harold-K** [comment]
Workaround for me is now export and then import profile

**Comment by gjsjohnmurray** [comment]
/duplicate

Another workaround is at https://github.com/microsoft/vscode/issues/224566#issuecomment-2277462990
