### ISSUE TITLE
Your terminal is messed up since 1.92

### ISSUE THREAD

**Issue by liufeimath** [microsoft/vscode#225301]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92
- OS Version: windows, with remote ssh to a linux server

Steps to Reproduce:

Your terminal is messed up since 1.92. The max-panel-size is not working properly. In the new version, any `less` output (e.g. by `git log`) does not take over the full screen as it used to. The scroll bar on the right is also very fishy: it shows the scroll bar even if I clear the terminal console by `clear`. If I minimize and maximize the terminal window again, the unnecessary scroll bar disappears.

Someone messed something up in the terminal console since 1.92 (or earlier). 

To reproduce:
1. try `git log` or `git show` in a maximized terminal window.
2. Try `for i in {1..10000}; do echo $i; done` and then `clear`, and then observe the weirdness on the right scroll bar.

**Comment by liufeimath** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.92.1. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

bot: 1.92.1 has the same issue. I'm pissed off that it didn't get fixed by your 1.92.1 which motivated me to report this issue.

**Comment by Tyriar** [comment]
Think this is the same as https://github.com/microsoft/vscode/issues/224750

/duplicate

**Comment by fenchu** [comment]
I'm using 1.93.0-insider same error there.
