### ISSUE TITLE
Themes: missing picker disposables

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#225386]
Quick pickers are itself disposables, as well as the events they provide.

Noticed a few leaks around picker instances and/or events:

https://github.com/microsoft/vscode/blob/3909bef4e4b26f7b08b187a6332a88ead318678e/src/vs/workbench/contrib/themes/browser/themes.contribution.ts#L172-L226

https://github.com/microsoft/vscode/blob/3909bef4e4b26f7b08b187a6332a88ead318678e/src/vs/workbench/contrib/themes/browser/themes.contribution.ts#L346-L388

//cc @TylerLeonhardt

**Comment by aeschli** [comment]
@bpasero There's already a `quickpick.dispose` that is called when the picker hides. Isn't that good enough?

https://github.com/microsoft/vscode/blob/2811728ba106c9c2c47728fc862c00bf2d2fde84/src/vs/workbench/contrib/themes/browser/themes.contribution.ts#L217
https://github.com/microsoft/vscode/blob/2811728ba106c9c2c47728fc862c00bf2d2fde84/src/vs/workbench/contrib/themes/browser/themes.contribution.ts#L385

**Comment by bpasero** [comment]
@aeschli see the various events (those beginning with `.onXY`) and how they are not getting disposed.

**Comment by aeschli** [comment]
But are going to a listener list managed by the quickpick, which is then disposed.

**Comment by bpasero** [comment]
@aeschli my understanding is that an `Emitter` does not dispose the `Event`-functions it had returned, i.e. this code is not running:

https://github.com/microsoft/vscode/blob/13b138216d720493a22d1e0fff74afad6737d55d/src/vs/base/common/event.ts#L1153-L1157

But maybe @jrieken or @alexdima can also chime in.

**Comment by jrieken** [comment]
Yes - an emitter doesn't dispose its listeners. @aeschli you basically rely on GC'ing here and I am uncertain if that actually works (e.g some disposables are tracked centrally for later blaming). I understand your motives but we generally dispose all the things
