### ISSUE TITLE
[loc][Query][VSCode] Please clarify context for comma

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#22530]
Hi, we have a question from our translator. Can you help please? Thanks!

**Source:**
{0}, debug

**File Name:**
src\vs\workbench\parts\debug\browser\debugQuickOpen.nls.resx

**Resource ID:**
".resx", 0; "entryAriaLabel"

**Query:**
Could you clarify the "comma" here? Thanks!

**Comment by isidorn** [comment]
@michaelchiche the translators have a question about how we use `nls` in `debugQuickOpen`. What we usually do in cases like this is to add a comment in the nls call to clarify the meaning and also comment here in the issue such that the translators are aware.

**Comment by michelkaporin** [comment]
@josefhosek I have followed the same convention as what we have in other places (e.g. taskQuickOpen resource), where we put comma after the task name label (see https://github.com/Microsoft/vscode/blob/470820229b4c23ea7ac78d6f80b8f7a4c2fc40eb/src/vs/workbench/parts/tasks/browser/taskQuickOpen.ts#L32). 

Here are some other resources that put a comma after the actual label, see:
https://github.com/Microsoft/vscode/blob/6450a172c0bdc5422a24b8228cd03a6595312372/src/vs/editor/contrib/quickOpen/browser/quickCommand.ts#L39, https://github.com/Microsoft/vscode/blob/422ffefee2fd852eb071a305598d9953f4c59992/src/vs/workbench/parts/quickopen/browser/helpHandler.ts#L41

So, the context is the same as for other files. This is a label of the entry to use when a screen reader wants to read about the entry. However, I cannot clarify why the comma is there as I am not aware how screen readers show these labels, maybe @isidorn knows more?

@isidorn I can check VS Code on screen reader to help to clarify the comma in this context if you could provide me with more information on screen reader we use to test our tool, etc.

**Comment by isidorn** [comment]
I think you explained it well enough, if the translator has more precise questions we can answer them. Closing for now
