### ISSUE TITLE
[loc][Query][VSCode] Please clarify placeholder

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#22539]
Hi, we have a question from our translator. Can you help please? Thanks!

**Source:**
Installing the {0} keyboard shortcuts...

**File Name:**
src\vs\workbench\parts\welcome\page\electron-browser\welcomePage.nls.resx

**Resource ID:**
".resx", 0; "welcomePage.installingKeymap"

**Query:**
What does the placeholder mean? Thanks!

**Comment by chrmarti** [comment]
It stands for another editor, currently either Vim, Atom or Sublime.
