### ISSUE TITLE
Simple file dialog: undisposed quick pick listeners and instances

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#225379]
Quick pick instances and listeners are not disposed here:

https://github.com/microsoft/vscode/blob/3909bef4e4b26f7b08b187a6332a88ead318678e/src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts#L109

Specifically:
* `createQuickPick` is a `IDisposable`
* listeners are `IDisposable`: `onDidCustom`, `onDidAccept`, `onDidChangeActive`, `onDidChangeValue`, `onDidHide`, 

Around:

https://github.com/microsoft/vscode/blob/3909bef4e4b26f7b08b187a6332a88ead318678e/src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts#L283-L406

and

https://github.com/microsoft/vscode/blob/3909bef4e4b26f7b08b187a6332a88ead318678e/src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts#L766-L796

//cc @TylerLeonhardt

**Comment by alexr00** [comment]
@bpasero are you seeing that the quick pick isn't getting disposed? It should be disposed here:

https://github.com/microsoft/vscode/blob/1370bd34a11408dbc2373047524bdc4146a78bd0/src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts#L326-L327

**Comment by bpasero** [comment]
Yeah possible I did not see that. In short, anything that is `IDisposable` should get disposed, including Events.
