### ISSUE TITLE
Users of zombie Vue extension cannot get migrated to the new version

### ISSUE THREAD

**Issue by johnsoncodehk** [microsoft/vscode#225398]
Type: <b>Bug</b>

This issue was supposed to be fixed in https://github.com/microsoft/vscode/issues/211702, but we have recently received complaints from some users regarding this.

I counted the first 50 issues with Vue extension installed in https://github.com/microsoft/vscode/issues, and 25 users are using 1.8.27 ~ 2.0.10 (2.0.10 was released 4 months ago ), only 19 users are using the latest version (2.0.22 ~ 2.0.28).

Numbers:
- **2.0.10**: 13 (Issue 225210, Issue 224993, Issue 223464, Issue 222157, Issue 221691, Issue 221503, Issue 221463, Issue 221461, Issue 221229, Issue 220972, Issue 220630, Issue 220106, Issue 220062)
- **2.0.8**: 6 (Issue 224271, Issue 224171, Issue 223290, Issue 221794, Issue 219837, Issue 219707)
- **2.0.7**: 2 (Issue 224527, Issue 224131)
- **2.0.6**: 2 (Issue 224896, Issue 223596)
- **1.8.27**: 2 (Issue 222893, Issue 221266)
- **2.0.22~2.0.28**: 19

Since some versions in 2.0.0~2.0.10 may have serious problems, this is probably the reason why the Vue extension has continued to receive negative reviews on the Marketplace and VSCode has continued to receive bug reports about the Vue extension for several months.

I found a Windows computer with `Vue.volar` 2.0.7 installed and was able to reproduce the issue of not being able to update the version. The following is the content of `.vscode/extensions/extensions.json`. (Formatted for easier reading)

```json
[
	{
		"identifier": {
			"id": "vue.volar",
			"uuid": "a5223b43-8621-4351-a14e-3d560f85f277"
		},
		"version": "2.0.7",
		"location": {
			"$mid": 1,
			"fsPath": "c:\\Users\\87156\\.vscode\\extensions\\vue.volar-2.0.7",
			"_sep": 1,
			"external": "file:///c%3A/Users/87156/.vscode/extensions/vue.volar-2.0.7",
			"path": "/c:/Users/87156/.vscode/extensions/vue.volar-2.0.7",
			"scheme": "file"
		},
		"relativeLocation": "vue.volar-2.0.7",
		"metadata": {
			"id": "a5223b43-8621-4351-a14e-3d560f85f277",
			"publisherId": "49983e2f-38ad-4441-beea-d678b53d0549",
			"publisherDisplayName": "Vue",
			"targetPlatform": "undefined",
			"isApplicationScoped": false,
			"updated": true,
			"isPreReleaseVersion": false,
			"installedTimestamp": 1711131971789,
			"preRelease": false
		}
	}
]
```

And I can reproduce the problem of not being able to update by overwriting the above metadata to the `.vscode/extensions/extensions.json` file of another macbook.

## Steps to Reproduce

1. If `Vue.volar` is installed, uninstall it and then close VSCode and reopen it.
2. Download `Vue.volar` 2.0.7 from https://open-vsx.org/extension/Vue/volar/2.0.7 and install it to VSCode, VSCode can normally prompt that Vue extension needs to be updated.
3. Open `~/.vscode/extensions/extensions.json` and modify the metadata of the last `Vue.volar` extension to:
```json
{
	"identifier": {
		"id": "vue.volar",
		"uuid": "a5223b43-8621-4351-a14e-3d560f85f277"
	},
	"version": "2.0.7",
	"location": {
		"$mid": 1,
		"fsPath": "c:\\Users\\87156\\.vscode\\extensions\\vue.volar-2.0.7",
		"_sep": 1,
		"external": "file:///c%3A/Users/87156/.vscode/extensions/vue.volar-2.0.7",
		"path": "/c:/Users/87156/.vscode/extensions/vue.volar-2.0.7",
		"scheme": "file"
	},
	"relativeLocation": "vue.volar-2.0.7",
	"metadata": {
		"id": "a5223b43-8621-4351-a14e-3d560f85f277",
		"publisherId": "49983e2f-38ad-4441-beea-d678b53d0549",
		"publisherDisplayName": "Vue",
		"targetPlatform": "undefined",
		"isApplicationScoped": false,
		"updated": true,
		"isPreReleaseVersion": false,
		"installedTimestamp": 1711131971789,
		"preRelease": false
	}
}
```
4. Reload VSCode will find that the Vue extension cannot detect newer versions.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Darwin arm64 23.1.0
Modes:

**Comment by sandy081** [comment]
Update is not detected automatically. It is detected only when user is searching for the extension.

**Comment by sandy081** [comment]
Sorry about this inconvenience caused. Fixed it - We will now detect the update automatically.

**Comment by johnsoncodehk** [comment]
I just tested it and confirmed it's fixed in the latest insiders version, thanks a lot!

**Comment by sandy081** [comment]
Adding `verified` label based on above comment
