### ISSUE TITLE
THE CODE IS RUNNING SLOW,TAKING TOO MUCH TIME FOR EXECUTION.

### ISSUE THREAD

**Issue by Prathmesh9999** [microsoft/vscode#225318]
[Trace-20240810T183115.json](https://github.com/user-attachments/files/16569647/Trace-20240810T183115.json)
Type: <b>Performance Issue</b>

the is from the date i have installed vs code...it took a lot of time to execute big code.even a small 1 letter word ouput took my 5 seconds.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13500H (16 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.70GB (5.76GB free)|
|Process Argv|--crash-reporter-id 73deadc3-7bc9-41de-a546-8a70cf68548d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   145	 11056	code main
    0	   109	   400	window [2] (Issue Reporter)
    0	    91	  2628	   utility-process
    0	    93	  3464	ptyHost
    0	    67	 13360	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"a:\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     7	 19000	     conpty-agent
    0	    39	  5512	   utility-network-service
    0	   306	  5624	window [1] (Settings - CODES - Visual Studio Code)
    0	    43	  6832	   utility-process
    0	   325	  8656	   window
    0	  2007	 11000	   gpu-process
    0	   192	 17556	extensionHost [1]
    0	    91	  9412	     c:\Users\gaura\.vscode\extensions\ms-vscode.cpptools-1.21.6-win32-x64\bin\cpptools.exe
    0	    10	 10124	       C:\Windows\system32\conhost.exe 0x4
    0	     8	 18964	       "c:\Users\gaura\.vscode\extensions\ms-vscode.cpptools-1.21.6-win32-x64\bin\cpptools.exe"
    0	    60	 16936	         c:\Users\gaura\.vscode\extensions\ms-vscode.cpptools-1.21.6-win32-x64/bin/cpptools-srv.exe 9412 {64CFB042-718D-41CE-BC4D-36946EF902D6}
    0	    10	   960	           C:\Windows\system32\conhost.exe 0x4
    0	    63	 18984	         c:\Users\gaura\.vscode\extensions\ms-vscode.cpptools-1.21.6-win32-x64/bin/cpptools-srv.exe 9412 {B5329EE9-F24E-4B3F-AC35-F4CCD36EBD08}
    0	    10	  1440	           C:\Windows\system32\conhost.exe 0x4
    0	    27	 18276	   crashpad-handler
    0	    83	 18508	fileWatcher [1]
    0	   109	 19220	shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings - CODES - Visual Studio Code)
|    Folder (CODES): 9 files
|      File types: cpp(5) exe(3) PY(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
blackbox|Bla|1.3.72
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
code-runner|for|0.12.2
vsc-python-indent|Kev|1.18.0
debugpy|ms-|2024.10.0
python|ms-|2024.12.2
vscode-pylance|ms-|2024.8.1
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
autodocstring|njp|0.6.1
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31111713

```

</details>

**Comment by aeschli** [comment]
What is running slow? Your code? VS Code?
Can you give reproducible steps and example code so I can see this on my machine?

**Comment by aeschli** [comment]
I looked at the trace, but it doesn't contain any clues on what this is about.
