### ISSUE TITLE
Update Seti icon theme for ESLint flat config files

### ISSUE THREAD

**Issue by reduckted** [microsoft/vscode#225370]
The Seti Icon theme has icons for the old ESLint config style, but not for the new flat config style.

The source repository has been updated to include a file mapping:
https://github.com/jesseweed/seti-ui/blob/88bcd4a8fca14aa33dd9d50781ad8af3b03c6b90/styles/components/icons/mapping.less#L604

The Seti Icon theme has not been updated yet:
https://github.com/microsoft/vscode/blob/8245d426e009ec7864018ed05ae2a282af42f03b/extensions/theme-seti/icons/vs-seti-icon-theme.json#L1753-L1761

Related to #195473

**Comment by aeschli** [comment]
Verify that with the built-in Seti theme, files named `eslint.config.js`  get the same icon as files named `eslintrc.json`

**Comment by bpasero** [comment]
I see different icons:

![image](https://github.com/user-attachments/assets/8463542b-b2dd-40b9-a961-9d063e0a12bf)

**Comment by aeschli** [comment]
Ok sorry, should have said: `eslint.config.js` get the same icon as files named `.eslintrc.json` (leading dot was missing)

![Image](https://github.com/user-attachments/assets/5abc1f25-8e36-461e-ab18-34c27c4fa4d4)
