### ISSUE TITLE
xz

### ISSUE THREAD

**Issue by Evgeny-Ramm** [microsoft/vscode#225329]
Type: <b>Bug</b>

вы работаете в среде gnome,  но набор ключей  ОС не доступен для шифрования.
Убедитесь, что установлено решение gnome-keyring

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Linux x64 5.15.0-118-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 1200 Quad-Core Processor (4 x 3448)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|7.67GB (5.92GB free)|
|Process Argv|--ms-enable-electron-run-as-node --extensions-dir=/home/evgeny/.var/app/com.visualstudio.code/data/vscode/extensions --reuse-window --crash-reporter-id 68b87c08-b1bb-405c-852a-89d3136a4d60|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
gitignore|cod|0.9.0
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|15.2.3
git-project-manager|fel|1.8.2
code-runner|for|0.12.2
copilot|Git|1.221.0
copilot-chat|Git|0.18.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.1
vscode-language-pack-ru|MS-|1.92.2024080709
debugpy|ms-|2024.10.0
pylint|ms-|2023.10.1
python|ms-|2024.13.2024080901
vscode-pylance|ms-|2024.8.1
material-icon-theme|PKi|5.9.0
learn-vim|vin|0.0.28
vim|vsc|1.27.3
gitblame|wad|11.0.1
txt-syntax|xsh|0.2.4
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31111713

```

</details>

**Comment by TylerLeonhardt** [comment]
Please follow https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues for keyring issues.
