### ISSUE TITLE
Holding ctrl+c in the terminal kills the interactive shell

### ISSUE THREAD

**Issue by johan-boule** [microsoft/vscode#225322]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.92.1 (user setup)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: MSDOS / Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Open a terminal to remote SSH shell
2. Hold ctrl+c

The shell gets killed. The terminal closes.

**Comment by meganrogge** [comment]
a gif would help

**Comment by johan-boule** [comment]
![image](https://github.com/user-attachments/assets/1850aef6-67b1-4655-96dc-7c3fd8572b71)

**Comment by meganrogge** [comment]
I cannot reproduce

**Comment by johan-boule** [comment]
The bug exists and I reproduce it 100%, quite easily, with the ultra simple steps as I described.
Marking an obvious bug ticket as "not planned" looks like a private joke inside the VSCode team, which I cannot comprehend.
