### ISSUE TITLE
[loc][Query][VSCode] Please clarify context for "staged"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#22533]
Hi, we have a question from our translator. Can you help please? Thanks!

**Source:**
Commit Staged (Amend)

**File Name:**
src\vs\workbench\parts\git\browser\gitActions.nls.resx

**Resource ID:**
".resx", 0; "commitStagedAmend"

**Query:**
What does staged make reference to? Thanks!

**Comment by joaomoreno** [comment]
Changes can either be staged or unstaged. Usually, only the staged changes are committed.
