### ISSUE TITLE
Pasting sftp path from Nautilus to editor, just pastes `/` character

### ISSUE THREAD

**Issue by yousofenv** [microsoft/vscode#225337]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.1
- OS Version: Ubuntu 22.04.4 LTS

Steps to Reproduce:

1. Open Files (Nautilus) and connect to a remote machine using sftp (Other locations -> Connect to Server -> Some sftp address)
2. Copy a file path by clicking on a directory or file and `ctlr + c`
3. Open VS code and Maybe a markdown file. 
4. Paste the path with `ctrl + v` or right click and paste.
5. It will paste as the image below, regardless of the original path.

![image](https://github.com/user-attachments/assets/2913d27c-cf9f-499b-865b-ed1326d002ed)

Pasting into integrated terminal works as expected.
It works fine when copying from host (not sftp address).

**Comment by mjbvz** [comment]
Relevant code if someone is interested in contributing:

https://github.com/iisaduan/vscode/blob/ddbe321368c13b02dc011fa243a61afcb6e48284/extensions/markdown-language-features/src/languageFeatures/copyFiles/shared.ts#L168

**Comment by pawar-ashish** [comment]
@yousofenv / @mjbvz what does Nautilus _actually_ copy to clipboard? I'm not on ubuntu but want to replicate this.

**Comment by yousofenv** [comment]
the image is here: ![Image](https://github.com/user-attachments/assets/7fa4dbdd-dbd4-497a-8779-cee3dd4c445a)

**Comment by mjbvz** [comment]
I've tested this on other systems and it seems to work fine. Given the low number of reports of the problem and complexity of testing this, I'm going to close this issue but we'd still take a community fix if someone wants to investigate further
