### ISSUE TITLE
Terminal No Longer Closes Automatically on Process Kill

### ISSUE THREAD

**Issue by bzm10** [microsoft/vscode#225346]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.1
- OS Version: MacOS 14.6

The integrated terminal in VSCode no longer closes automatically when a process is killed, despite no changes to settings or configurations. I have tried resetting VSCode and disabling all extensions, but the issue persists. This behavior is not present on a different machine with the same setup.

**Comment by meganrogge** [comment]
Is the terminal you're talking about a task terminal? A gif would help

**Comment by meganrogge** [comment]
> this is suspicious 

This behavior is not present on a different machine with the same setup.
