### ISSUE TITLE
how to turn off code overlay ?

### ISSUE THREAD

**Issue by craigcosmo** [microsoft/vscode#225349]
![CleanShot 2024-08-11 at 12 57 36](https://github.com/user-attachments/assets/fb7fcc60-23b3-4e65-b3c9-aa3144515969)
I see this in the new version of vs code. how to turn this off ?

**Comment by christhofer** [comment]
Right click on it, uncheck `Sticky Scroll`

![image](https://github.com/user-attachments/assets/8fd9ff06-197b-44f1-a6af-3a284705e965)
