### ISSUE TITLE
[loc][Query][VSCode] Please clarify context and placeholder for "Focus Terminal {0}"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#22537]
Hi, we have a question from our translator. Can you help please? Thanks!

**Source:**
Focus Terminal {0}

**File Name:**
src\vs\workbench\parts\terminal\electron-browser\terminalActions.nls.resx

**Resource ID:**
".resx", 0; "workbench.action.terminal.focusAtIndex"

**Query:**
Please provide context and the meaning of the placeholder. Thanks!

**Comment by Tyriar** [comment]
The user can create terminals that appear down the bottom of the editor, they are named terminal 1, 2, 3, 4, etc.

This text refers to sending the application focus to a terminal, showing it if necessary. Eg. "Focus terminal 1" will focus and show the first terminal.
