### ISSUE TITLE
Change terminal rename codicon

### ISSUE THREAD

**Issue by PraneshBalasubramaniam** [microsoft/vscode#225359]
The **terminal rename** option in command palette has `settings-gear` codicon which is little confusing as it appears as a setting. So can we use `edit` codicon which is more understandable.
![image](https://github.com/user-attachments/assets/bbe729c4-26da-4951-bafe-08f9830b1739)

**Comment by jeanp413** [comment]
PR fixing it https://github.com/microsoft/vscode/pull/225444
