### ISSUE TITLE
launch.json/task.json changes not always used when launching

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#22535]
- VSCode Version: 1.11 insiders
- OS Version: Ubuntu-14, Windows 10, and OSX

Steps to Reproduce:
1. Make a change to launch.json or a task that launch.json references through `preLaunchTask`.
2. Immediately hit F5 to start debugging

Expected:
Current version of the file should be used

Actual:
Most of the time on my box the old version is used and I need to launch again.

This seems to be related to https://github.com/Microsoft/vscode/issues/3132, but I am not sure if maybe that fix was insufficient or if it just regressed again.

**Comment by isidorn** [comment]
@gregg-miskelly good catch, happened due to some refactoring on my side. Should behave fine now, you can check it out in tomorrow's insiders

**Comment by gregg-miskelly** [comment]
@isidorn Thanks!
