### ISSUE TITLE
Push-Location and relative referencing not working correct

### ISSUE THREAD

**Issue by OlafDrechsler** [microsoft/vscode#225376]
Type: <b>Bug</b>

The situation:
We're building something in Powershell 7. 
All the script files are in C:\TomsTool\PS with icons in subfolder C:\TomsTool\PS\Icons

The problem:
I run the file C:\TomsTool\PS\Show-Menu.ps1 in debug mode in VS Code.
In that script we use Push-Location to set the path to C:\TomsTool\PS
Retrieving the value with Get-Location prooves that Push-Location worked correct.
Nevertheless relative referencing to a file 
```         Icon = '.\Icons\somepic.ico'; ```
refers to my home path and results in an error:
``` InvalidArgument: C:\TomsTool\PS\Show-Menu.ps1:241:5
Line |
 241 |      $formMenu = [Form]@{Text='Verarbeitung';
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot create object of type "System.Windows.Forms.Form". Cannot convert value ".\Icons\somepic.ico" to type
     | "System.Drawing.Icon". Error: "Could not find a part of the path 'C:\Users\OlafDrechsler\Icons\somepic.ico'."
```

The reason:
I did open the script file by double clicking in Microsoft Explorer and straight away started run in debug mode in VS Code.
The error does _not_ happen when I open VS code, open the folder C:\TomsTool\PS from within VS Code and open the script file from within VS Code.

My humble opinion:
I think Push-Location should work the same way in both situations.

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (5.90GB free)|
|Process Argv|C:\\TomsTool\\PS\\Show-Menu.ps1 --crash-reporter-id a8ea1613-c3b4-4026-a435-3572160607d0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2024.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-t:31111713

```

</details>

**Comment by OlafDrechsler** [comment]
still the same behavior

**Comment by roblourens** [comment]
Not totally following but I think this is an issue either with your script, with powershell, or with the powershell debugger? You can try opening an issue on the powershell extension for vscode, ideally with more context like a script to repro the issue.
