### ISSUE TITLE
Terminal Window Error Code Link resolver does not work anymore (Strg+Click / Ctrl+Click) to show source of error)

### ISSUE THREAD

**Issue by ABuch19** [microsoft/vscode#225371]
Type: <b>Bug</b>

I am developing C/C++ projects.
I am using `Make` to compile in the terminal.
The VSC terminal shows compiler errors like this:
````
../../src/modules/my-module.cpp: In destructror:
../../src/modules/my-module.cpp:71:3 error: 'what' was not declared in this scope
````

In previous versions of VSC I could simply use Strg+Mouse-Click / Ctrl+Mouse-Click to jump to the source at line 71, position 3.
This does not work anymore.
It fails with error message:
````
../../src/modules/my-module.cpp:71:3
No matching results
````

When I Strg+click / Ctrl+Click on the previous line with `../../src/modules/my-module.cpp`, this works:
The file is opened in the editor.

So in general the "link resolver" seems to work. But it struggles with line number and position after the latests updates.

I am not sure, if this is caused by VSC itself or by an Extension.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 6.2.0-37-generic
Remote OS version: Linux x64 4.9.0-19-rt-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.85GB (16.72GB free)|
|Process Argv|--crash-reporter-id f67d31ed-d43a-4da0-b8af-403c61bee558|
|Screen Reader|no|
|VM|29%|

|Item|Value|
|---|---|
|Remote|SSH: Ubuntu-Dev-ESXi|
|OS|Linux x64 6.2.0-37-generic|
|CPUs|Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz (8 x 0)|
|Memory (System)|11.67GB (8.84GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: 427e-debian|
|OS|Linux x64 4.9.0-19-rt-amd64|
|CPUs|Intel(R) Core(TM) i5-6442EQ CPU @ 1.90GHz (4 x 856)|
|Memory (System)|3.76GB (1.75GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.27.1
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
gitlens|eam|15.2.3
copilot|Git|1.221.0
copilot-chat|Git|0.18.1
vscode-language-pack-de|MS-|1.92.2024080709
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.9.10
cmake|twx|0.0.17
vscode-proto3|zxh|0.5.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718

```

</details>

**Comment by meganrogge** [comment]
what does this mean ? 

`Strg+click`?

**Comment by ABuch19** [comment]
Hi @meganrogge,
sorry for my bad explanation.
To follow a "link" in the terminal window, I have to left-click on the "link" while holding the "Strg" key on the keyboard.
In my case the "link" is the output of the compiler like `../../src/modules/my-module.cpp:71:3`.
In former versions of VSC (and Extensions) I could easily jump to this file and position by "Strg + Click".
Now it just prints the error `No matching result` 
The strange thing is, that a "Strg + Click" on `../../src/modules/my-module.cpp` is still working.

This really slows down my development workflow :-(
I always have to manually open the source file and go to the given line number with the error.

**Comment by ABuch19** [comment]
I have done more investigations. I always click with left mouse button while holding the Ctrl key on the keyboard:

| link in terminal wnidow | result when Ctrl+Click |
| ------------------------ | ----------------------  |
|  `../../src/modules/my-module.cpp` | file is opened |
| `../../src/modules/my-module.cpp:71:3` | error: No matching results |
| `src/modules/my-module.cpp:71:3` | file is opend at the correct position |

**Comment by Tyriar** [comment]
Both these links work for me on Windows:

![Image](https://github.com/user-attachments/assets/668cb688-f89c-4f7a-9c63-d25843dcad17)

**Comment by Tyriar** [comment]
They also work fine for me in a Remote - WSL window. So either this is fixed already or we'll need some more information to investigate. If you do still see this you can get some information about link resolving by getting a trace log of the `Terminal` channel:

https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
