### ISSUE TITLE
Run with Coverage doesn't work anymore

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#225395]
* open `src/vs/editor/test/common/core/range.test.ts`
* right click on the suite and choose Run with Coverage
* last week the coverage information used to be rendered in the editor, now it doesn't show anymore

https://github.com/user-attachments/assets/231d76ad-4e43-42c5-8f8e-b9d020aaec45

**Comment by connor4312** [comment]
I don't see this on macOS or Windows -- do you have any console errors?

**Comment by alexdima** [comment]
I can't explain it, I think I had somehow ended up being switched over from the workplace extension to the marketplace extension `ms-vscode.vscode-selfhost-test-provider`. Is this possible @sandy081 ? 

I uninstalled the selfhost test provider, reloaded vs code and then installed it again and now I get coverage info again

**Comment by connor4312** [comment]
I'll also see if we can unpublish the marketplace version as there's no longer any reason for that to exist
