### ISSUE TITLE
Source Control tab became very slow!

### ISSUE THREAD

**Issue by AmmarMohamadIsmaeel** [microsoft/vscode#225382]
Seeing the changes is taking more than 30 seconds
Staging files is taking more than 10 seconds for each file
Committing is taking more than 1 minute
This just happened when incoming/outcoming tree was added under the changes, please fix it asap

**Comment by TheDanielApril** [comment]
This works for me (`settings -> "scm.showHistoryGraph": false`)
https://github.com/microsoft/vscode/issues/225340#issuecomment-2282500011

**Comment by gjsjohnmurray** [comment]
The advice from @TheDanielApril is good.

/duplicate
