### ISSUE TITLE
Syntax Highlighting/Tokenization breaks in C++ if template parameter contains a less-than (`<`) comparison 

### ISSUE THREAD

**Issue by lethalbit** [microsoft/vscode#225314]
Type: <b>Bug</b>

Take this example:
```cpp
template<bool V>
struct foo { bool value = V; };
template<typename T>
struct bar : foo<(T(-1) < T(0))> {};
template<typename T>
struct bar<T> : false_type {};
```

The `<` within the template parameter of `bar` causes the tokenizer to get confused an go out of sync, causing all downstream highlighting to break.

|   |   |
|---|---|
|![image](https://github.com/user-attachments/assets/9f41eb87-83dc-4826-8132-df6d99462116)|![image](https://github.com/user-attachments/assets/54011880-844c-4332-ae97-c6e42f0461b7)|

Might be related to #211369

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Linux x64 6.10.2-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 1950X 16-Core Processor (32 x 3692)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|125.67GB (64.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasmax11|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by alexr00** [comment]
Copied to upstream repo: https://github.com/jeff-hykin/better-cpp-syntax/issues/660
