### ISSUE TITLE
Lightbulb and sparkle icons always showing below selected line

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#225459]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
```
Version: 1.93.0-insider (user setup)
Commit: b60fe002f59dbc364ba3af905cefd6575bfe717b
Date: 2024-08-12T07:52:06.295Z
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
```
- OS Version: 
```
OS: Windows_NT x64 10.0.26120
```

Whenever the lightbulb and/or sparkle icons appear, they are always on the line below the selected line

![Image](https://github.com/user-attachments/assets/ebd16040-25d7-4cec-a169-7762b7d09e67)

Steps to Reproduce:

1. 
2.

**Comment by justschen** [comment]
@chrisdias this should be intended - there isn't space above (it'll block code), so we spawn it below.

in a case where there is space above, it'll spawn above. if it's blocked above and below, it'll spawn in the gutter

![Screenshot 2024-08-13 at 12 05 34 AM](https://github.com/user-attachments/assets/07834979-b1c5-4aba-8c64-97e31f468c75)

vs.

![Screenshot 2024-08-13 at 12 05 42 AM](https://github.com/user-attachments/assets/ea1b4f81-5ba0-4a48-921f-057c4702cbce)

vs. 

![Screenshot 2024-08-13 at 12 06 21 AM](https://github.com/user-attachments/assets/11003fa8-48fc-4d48-b10f-61804b01ea21)

**Comment by justschen** [comment]
closing as it's intended
