### ISSUE TITLE
so much ram, like 2gigas

### ISSUE THREAD

**Issue by guillerg01** [microsoft/vscode#225421]
Type: <b>Performance Issue</b>

i dont know.... sorry, but, how i can see extencios ram, to unistall it

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7840HS w/ Radeon 780M Graphics      (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.31GB (2.99GB free)|
|Process Argv|--crash-reporter-id 1cefb61b-7d4d-42cd-8d78-ffbb0f2cea55|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   165	 24248	code main
    0	   101	  1496	shared-process
    0	    26	  1548	   crashpad-handler
    0	    71	  3880	ptyHost
    0	     6	 13808	     conpty-agent
    0	    71	 22612	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\K1LL3r\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    1	   142	 10280	   gpu-process
    1	   504	 13788	window [2] (LoaderBoard.tsx - showcase-md-backoffice - Visual Studio Code)
    0	   106	 13848	window [3] (Notificador de problemas)
    0	   722	 18264	extensionHost [2]
    0	    66	  1868	     electron-nodejs (eslintServer.js )
    0	    89	  7132	     electron-nodejs (tsserver.js )
    0	    62	  7680	     electron-nodejs (server.js )
    0	    68	 20432	     "C:\Users\K1LL3r\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\K1LL3r\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=18264
    0	   314	 20812	     electron-nodejs (tsserver.js )
    0	    55	 24808	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    57	 22472	     c:\Users\K1LL3r\.vscode\extensions\codeium.codeium-1.10.11\dist\4afed79fc3218d4ed6a74b3082a291b8e866ba19\language_server_windows_x64.exe --api_server_url https://server.codeium.com --manager_dir C:\Users\K1LL3r\AppData\Local\Temp\fdbbddde-9d33-4840-970b-09f6b0c8ac67\codeium\manager --enable_chat_web_server --enable_lsp --inference_api_server_url https://inference.codeium.com --database_dir C:\Users\K1LL3r\.codeium\database\9c0694567290725d9dcba14ade58e297 --enable_index_service --enable_local_search --search_max_workspace_file_count 5000 --indexed_files_retention_period_days 30 --workspace_id file_c_3A_Users_K1LL3r_Documents_GitHub_showcase_md_backoffice --sentry_telemetry
    0	   180	 14108	       c:\Users\K1LL3r\.vscode\extensions\codeium.codeium-1.10.11\dist\4afed79fc3218d4ed6a74b3082a291b8e866ba19\language_server_windows_x64.exe --api_server_url https://server.codeium.com --manager_dir C:\Users\K1LL3r\AppData\Local\Temp\fdbbddde-9d33-4840-970b-09f6b0c8ac67\codeium\manager --enable_chat_web_server --enable_lsp --inference_api_server_url https://inference.codeium.com --database_dir C:\Users\K1LL3r\.codeium\database\9c0694567290725d9dcba14ade58e297 --enable_index_service --enable_local_search --search_max_workspace_file_count 5000 --indexed_files_retention_period_days 30 --workspace_id file_c_3A_Users_K1LL3r_Documents_GitHub_showcase_md_backoffice --sentry_telemetry --run_child --limit_go_max_procs 4 --random_port --random_port_dir=C:\Users\K1LL3r\AppData\Local\Temp\fdbbddde-9d33-4840-970b-09f6b0c8ac67\codeium\manager/child_random_port_1723478097160036500_3205651642094753940 --manager_lock_file=C:\Users\K1LL3r\AppData\Local\Temp\fdbbddde-9d33-4840-970b-09f6b0c8ac67\codeium\manager/locks/manager.lock --child_lock_file C:\Users\K1LL3r\AppData\Local\Temp\fdbbddde-9d33-4840-970b-09f6b0c8ac67\codeium\manager/locks/child_lock_1723478097160557400_307535803253285269
    0	    11	 21988	       C:\Windows\system32\conhost.exe 0x4
    0	   118	 24204	     electron-nodejs (tailwindServer.js )
    0	   128	 24340	     "C:\Users\K1LL3r\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\K1LL3r\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\markdown-language-features\dist\serverWorkerMain" --node-ipc --clientProcessId=18264
    0	    95	 25044	     electron-nodejs (index.js )
    0	    43	 19620	   utility-network-service
    0	    95	 24940	fileWatcher [2]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (LoaderBoard.tsx - showcase-md-backoffice - Visual Studio Code)
|    Folder (showcase-md-backoffice): 1407 files
|      File types: js(228) tsx(194) jpg(121) ts(109) gz(97) json(64) pack(59)
|                  webp(46) html(30) meta(29)
|      Conf files: package.json(3) tsconfig.json(1);
```

</details>
<details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-tailwindcss|bra|0.12.5
path-intellisense|chr|2.9.0
codeium|Cod|1.10.11
vscode-eslint|dba|3.0.10
vscode-generate-getter-setter|DSK|0.5.0
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|10.4.0
copilot|Git|1.221.0
copilot-chat|Git|0.18.1
json2ts|Gre|0.0.6
vscode-react-typescript|inf|1.3.1
vscode-gutter-preview|kis|0.31.2
ts-extension-pack|loi|0.3.0
json-to-ts|Mar|1.8.0
prettify-json|moh|0.0.3
vscode-language-pack-es|MS-|1.91.2024071009
remote-containers|ms-|0.380.0
powershell|ms-|2024.2.2
test-adapter-converter|ms-|0.1.9
phind|phi|0.25.3
material-icon-theme|PKi|5.9.0
quicktype|qui|23.0.170
vscode-thunder-client|ran|2.24.13
es7-react-js-snippets|rod|1.9.3
vs-code-prettier-eslint|rve|6.0.0
vscode-icons|vsc|12.8.0
vscode-wakatime|Wak|24.6.0
console-ninja|Wal|1.0.339
vscode-import-cost|wix|3.3.0
pretty-ts-errors|Yoa|0.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31111713

```

</details>

**Comment by gjsjohnmurray** [comment]
Extensions run in a shared process so AFAIK it's hard to get memory usage figures for each of them. But the `Start Extension Bisect` command may be useful when trying to identify the hungry one(s).

**Comment by DonJayamanne** [comment]
More information on using Extension Bisect can be found here https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

**Comment by guillerg01** [comment]
![image](https://github.com/user-attachments/assets/bfa021fe-4811-4107-b62e-bb70f1811f1f)

**Comment by lakshyagithub** [comment]
Try uninstalling some extensions. Maybe that will help?

**Comment by DonJayamanne** [comment]
@guillerg01 Please can you u extension bisect to identify the extension that might be causing this issue.
Details provided here https://github.com/microsoft/vscode/issues/225421#issuecomment-2284844020
