### ISSUE TITLE
Syntax highlighting for inlay hints

### ISSUE THREAD

**Issue by LPeter1997** [microsoft/vscode#225479]
We have been doing a language integration primarily targeting VS Code and noticed, that there's no way to have the inlay hints colored. It would be nice, if inlay hints could be treated as regular code and could get the same syntax highlighting as the rest of the text, just maybe be a bit darker/transparent. In their current form, they are a bit harder to read.

I understand that treating inlay hints as code is not universally applicable, so we might need to propose something like a flag to LSP too to signal that the given inlay hint fragment can be treated as part of the code or something, this is partly a feature request and partly trying to start a discussion to see what people think of this.

**Comment by RedCMD** [comment]
https://github.com/microsoft/vscode/issues/225400

**Comment by LPeter1997** [comment]
@RedCMD No, inlay hints are labels within source code that are not actually part of the source code, they merely provide extra info for readability - like parameter names, inferred variable types,  etc. For example: https://code.visualstudio.com/docs/typescript/typescript-editing#_inlay-hints
