### ISSUE TITLE
Autosave "onFocusChange" stopped working

### ISSUE THREAD

**Issue by juanmirod** [Microsoft/vscode#22547]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.7.4-040704-generic
---

Hi, it seems that after updating the autosave feature stopped working, it was working until today. I enabled the minimap feature but disabling it didn't make autoSave work again, so it doesn't look to be related. If I set autoSave to "afterDelay" it works ok.

Steps to Reproduce:

1. Setting "files.autoSave": "onFocusChange" on and working with version 1.10.1
1. Updated to Code 1.10.2
2. autoSave doesn't work anymore on focus change.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by randywick** [comment]
Same issue experienced from `1.10.2` on `Linux 4.8.0-39-generic`, but after opening Settings to verify the option was set properly, autoSave began working properly on focus change.

**Comment by chrisdothtml** [comment]
Getting the same issue intermittently. Happening on both my work and personal Macs

**Comment by bpasero** [comment]
@randywick @chrisdothtml can you see if insiders fixes it for you? Get it from http://code.visualstudio.com/Download#insiders

**Comment by juanmirod** [comment]
Hi @bpasero I just tried the insiders build and it works, thanks a lot for the quick reply!

**Comment by randywick** [comment]
@bpasero it seems you've already confirmed this, but yes it was fixed in the insiders build - thanks!  For clarification, I mainly experienced the issue when switching between open files using ctrl+page up/down.  All fixed now.
