### ISSUE TITLE
Wiki missing pictures. IDE missing documented features. No reset to defaults available.

### ISSUE THREAD

**Issue by Gimpeh** [microsoft/vscode#225491]
Type: <b>Feature Request</b>

First, someone wrote this big giant document detailing quite a bit about the IDE. Clearly a fairly large effort has been made... but referencing it is hard.
For example, im trying to reset all settings. I pressed the wrong button because my hand slipped... and now i cant even nagivate the IDE with the arrow keys. So anyways, I found documentation for how to reset all settings (after searching myself for 30 minutes). The documenation mentions a menu bar, and selecting tools. But has no pictures or links to what these things are. 
Theres bars all over the place, none of them appear to be named menu bar... is it just a bar with menus? Because thats basically all of them...
I literally can't proceed until I get this fixed, and the documentation just plainly isn't helpful... Now if there were a few pictures... THEN we'd be in business.

After about 20 minutes of searching for either of those, in every possible location on this IDE that I can find.. Im confident that they don't exist on my IDE. Which is where the missing documented features comes in. The reset to defaults is kind of massively important when something goes wrong... like... am I supposed to guess which of the 40000 keybinds It is? Because a lot of the 'names' of the keybinds just aren't very informative for me. I realize thats because Im dumb.

Which is my biggest issue. Im dumb and I broke it. Can we get some kind of reset to defaults button contained with the settings they would reset? Or under file or edit even....

And this last part is just a request (i suppose so is the above), but its kind of a big thing you guys are lacking imo.
outline should allow me to keep info from files that aren't in the selected  editor in outline. Where they should still be displayed... It would be very useful to be able to see other parts of my project besides the single file I clicked on last.

Thanks! Im giving this escapade 5 more minutes and then migrating to notepad++. Not because I don't like Visual Studio... But because it literally is broken for me and I need to be able to navigate the file im working on with more than just mouse clicks..
Because this is just painful.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by Gimpeh** [comment]
Reset isnt even searchable in the search bar..

**Comment by ArturoDent** [comment]
See 

[Reset all settings](https://code.visualstudio.com/docs/getstarted/settings#_reset-all-settings)

While you can reset settings individually via the Settings editor Reset Setting command, you can reset all changed settings by opening settings.json and deleting the entries between the braces {}. Be careful since there is no way to recover your previous setting values.
