### ISSUE TITLE
Add `Save As...` to context menu for new, unsaved files

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#225451]
I would like for there to be a `Save As...` context menu when I right click on a new, unsaved file.

![Image](https://github.com/user-attachments/assets/7616b575-f112-4ca7-a7ef-26884553d04c)

Today I have to go to the `File...` menu

**Comment by bpasero** [comment]
We typically want to keep the tab menu from growing more, you will not see "Save" or "Revert" entries in there.

**Comment by chrisdias** [comment]
Can I write an extension that contributes a context menu to the tab?

**Comment by chrisdias** [comment]
Turns out you can pretty easily, extension coming soon!

**Comment by chrisdias** [comment]
https://marketplace.visualstudio.com/items?itemName=chrisdias.vscode-savecontextmenu
