### ISSUE TITLE
source control tab

### ISSUE THREAD

**Issue by Chethandev12** [microsoft/vscode#225405]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by Chethandev12** [comment]
<img width="960" alt="source control" src="https://github.com/user-attachments/assets/07c7253d-b930-46e5-898b-8063c6139f31">
changed files are not showing under source controll

**Comment by gjsjohnmurray** [comment]
Does the problem still happen if you add the setting `"scm.showHistoryGraph": false` ?

**Comment by Chethandev12** [comment]
how to add that commend ??

**Comment by gjsjohnmurray** [comment]
Easiest is to open Settings Editor, e.g. from File menu choose Preferences then Settings. The type 'showhistorygraph' (no quotes) and when the checkbox setting titled "SCM: Show History Graph" appears, clear it.

More info available at https://code.visualstudio.com/docs/getstarted/settings

**Comment by umagon** [comment]
@gjsjohnmurray after turning of `scm.showHistoryGraph` the changes show again. I like incoming/outgoing tree however, maybe it should be in its own tab? Or instead of "Commits".

**Comment by gjsjohnmurray** [comment]
/duplicate

Other open issues cover proposed improvements to this feature
