### ISSUE TITLE
EH crash reported when reloading window

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#225485]
* Start code-exploration on any folder
* Reload window
* See the following in main process logs

```
2024-08-13 19:41:55.046 [info] Extension host with pid 31907 exited with code: 0, signal: unknown.
2024-08-13 19:41:55.063 [error] [UtilityProcessWorker]: terminated unexpectedly with code 1806961072, signal: unknown
```

**Comment by bpasero** [comment]
@deepak1556 are you sure this is caused by ESM?

**Comment by deepak1556** [comment]
I don't see it in insiders, actually issue only repros when reloading windows, updated title. Also I don't see any dumps in the crash directory so may not be an actual crash but some incorrect lifecycle logging.

**Comment by deepak1556** [comment]
I filed it too fast, can repro with insiders as well with the updated steps.

**Comment by bpasero** [comment]
I would not be surprised if this is the issue where utility process reports a bad exit code of `15` and us assuming it is a crash even though it is going down normally.

**Comment by bpasero** [comment]
Bisecting points to this range: https://github.com/microsoft/vscode/compare/97d1b933ada0ca69bea107f7a89e029991277ccc...6c199b09f8764e6746a31eb1a860be68cb553165

Specifically https://github.com/microsoft/vscode/commit/6c199b09f8764e6746a31eb1a860be68cb553165 which includes https://github.com/electron/electron/pull/42395 as I had initially thought would cause this.

**Comment by deepak1556** [comment]
Upstream https://github.com/electron/electron/issues/44012
