### ISSUE TITLE
visualization of changes using a graph in "Source Control" tab with more than one Sources

### ISSUE THREAD

**Issue by aviad198** [microsoft/vscode#225493]
Hi,

In my use-case I got two sources. the new graph feature (1.92.1) is nice but causes my second source folder to "disappear" down on the window making these feature inconvenient and non-relevant.

 Before:
![Before](https://github.com/user-attachments/assets/3fd8b85f-f485-4c01-a56b-2918c8f6e884)
After:
![Untitled](https://github.com/user-attachments/assets/313742bb-5b02-485d-9f7d-4bd56791cef9)

**Comment by lszomoru** [comment]
Thanks for the feedback. For the time being you can disable the history graph by toggling the `scm.showHistoryGraph` setting.
