### ISSUE TITLE
Linux: font size issues in v1.92.x

### ISSUE THREAD

**Issue by jgarber623** [microsoft/vscode#225434]
Pull comments from #224496 per @deepak1556's [suggestion](https://github.com/microsoft/vscode/issues/224496#issuecomment-2283651474):

> this issue is specific to macOS, can you open a separate issue for your case. Thanks!

Relevant comments regarding font issues in various flavors of Linux:

- https://github.com/microsoft/vscode/issues/224496#issuecomment-2265166136
- https://github.com/microsoft/vscode/issues/224496#issuecomment-2266184744
- https://github.com/microsoft/vscode/issues/224496#issuecomment-2267595270
- https://github.com/microsoft/vscode/issues/224496#issuecomment-2282641562
- https://github.com/microsoft/vscode/issues/224496#issuecomment-2284604782

Filing this mostly to stem the tide of comments on the macOS issue and to give folks a space to discuss the Linux issues. I'll be immediately unsubscribing so… have at it. 😄

**Comment by kowsar89** [comment]
### Relevant screenshots (where menu items looks bigger):
Top menu items: https://prnt.sc/Twi3ckgzi0YA
Context menu items: https://prnt.sc/-qD51jp8JpMK

Could be font issue or zooming, I don't know

**Comment by guymarshall** [comment]
![Screenshot from 2024-08-12 22-31-23](https://github.com/user-attachments/assets/4f63beeb-8a6a-4d54-8325-ad69a73b3284)

I am not on my main laptop (*which is 1366x768*) I am on my *1920x1080* laptop, but I have changed the desktop scaling to show what the menus look like. I used to be able to close the editor from the menu without having to scroll. This happens for the right-click menu also. My specs are in the screenshot below:

![Screenshot from 2024-08-12 22-36-48](https://github.com/user-attachments/assets/5f19cb5e-509d-41bc-97d4-bf746b56e834)

**Comment by deepak1556** [comment]
Thanks @jgarber623 for taking the time to create the issue.

Based on the screenshots this is different from the macOS editor font issue and is specific to menu fonts which is a known upstream issue, tracked in https://github.com/microsoft/vscode/issues/224515. Please follow the issue for updates.
