### ISSUE TITLE
There's no apparent way to make files open in a new tab by default.

### ISSUE THREAD

**Issue by Stokestack** [microsoft/vscode#225453]
Type: <b>Bug</b>

I've searched the settings for "tab" and found no way to address this: VS Code consistently but inexplicably stops opening new tabs after the second one, as you click on files in the treeview.

The context menu on files in the treeview doesn't even offer an "open in new tab" option, so there's no discoverable hotkey to do so either. I looked in the File and Edit menus too.

One might suspect that double-clicking will do it, but nope. Option-clicking will in fact do it... but in the wrong pane (screen grab attached).

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (0.33GB free)|
|Process Argv|--crash-reporter-id 078df501-2baa-4a67-99eb-d56e79af23af|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
mustache-syntax-vscode|att|0.1.0
doxdocgen|csc|1.4.0
vscode-deno|den|3.38.0
cmake-integration-vscode|go2|0.7.1
codewind-openapi-tools|IBM|0.14.1
better-cpp-syntax|jef|1.27.1
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.2
vscode-pylance|ms-|2024.8.1
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.10.25
vscode-thunder-client|ran|2.24.13
java|red|1.33.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.3
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.28.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31111713

```

</details>

https://github.com/user-attachments/assets/9be3d887-4628-47d0-abbf-82a45640e255

**Comment by gjsjohnmurray** [comment]
Please learn about Preview Mode at https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

**Comment by Stokestack** [comment]
Thanks for that info. Unfortunately, the fundamental problem remains. Since this concerns **tab** behavior, the user will search the settings for "tab." This turns up nothing relevant in them, as far as I can tell.

Even if the user finds the Tabs section in the document that you linked to, he won't find the necessary information. It simply says,
[Tabs](https://code.visualstudio.com/docs/getstarted/userinterface#_tabs)

> VS Code shows open items with tabs (tabbed headings) in the title area above the editor. When you open a file, a new tab is added for that file. Tabs let you quickly navigate between items.

In fact, _nowhere in the Tabs section does it mention tabs being re-used or how to prevent it_. The user will not know that, for some reason, Microsoft calls this behavior "preview mode." This name is arguably wrong, since a _preview_ is almost universally expected to be a separate pane that shows the result of what the user is working on. For example, an HTML/CSS preview pane alongside a code-editing pane. Or the UI preview pane alongside the SwiftUI code editor in Xcode.

Thus, with no reason to search for the word "preview," the user is highly unlikely to discover the cause or solution to this behavior.

And there's still the problem of the undocumented new-tab hotkey opening the tab in the wrong (non-focused) pane.

**Comment by bpasero** [comment]
We have a prominent action to change this ad-hoc:



![Image](https://github.com/user-attachments/assets/001474c0-2119-4bde-b587-e4061a21dba6)

Tabs are not really mentioned in the setting because this setting applies when tabs are disabled as well. 

But I am open to expand the settings description to make it easier to find if someone is willing to step in (keeping it time boxed to 7 days).

**Comment by gjsjohnmurray** [comment]
I will submit a PR.

**Comment by Stokestack** [comment]
Thanks guys!
