### ISSUE TITLE
`clear` command doesn't work in the terminal.

### ISSUE THREAD

**Issue by xcfio** [microsoft/vscode#225406]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open terminal
2. Run `node --help`
3. Run `clear`
4. Scroll up

https://github.com/user-attachments/assets/0504e77b-138a-4c26-8520-65f11257ca62

**Comment by meganrogge** [comment]
/duplicate https://github.com/microsoft/vscode/issues/75141#issuecomment-1845733788
