### ISSUE TITLE
After workbench.externalBrowser is set, the zodiac cannot be

### ISSUE THREAD

**Issue by ChinaGodMan** [microsoft/vscode#225432]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: VSCode-win32-x64-1.92.1
- OS Version: windows 11

Steps to Reproduce:

1. I set "workbench.externalBrowser": "chrome" in the user's settings.json, but the browser I set cannot be called to open the link in the code.
2. This doesn't seem to be opening the web page through the command line? For example chrome "www.123.com"

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line
* reproduce the issue
* attach the log files you find from running the command "Open Logs Folder"

Thanks!

**Comment by bpasero** [comment]
Hm?

**Comment by ChinaGodMan** [comment]
> Hm? Did you find something in the logs?

[main.log](https://github.com/user-attachments/files/16661740/main.log)

**Comment by bpasero** [comment]
Got it, I did change a bit how error handling works recently in our insiders, can you try that and attach the log?

You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ChinaGodMan** [comment]
> Got it, I did change a bit how error handling works recently in our insiders, can you try that and attach the log?
> 
> You can give our preview releases a try from: https://code.visualstudio.com/insiders/

>VSCode-win32-x64-1.93.0-insider

 **Not work **
I use the extension `Live Server` and set `liveServer.settings.AdvanceCustomBrowserCmdLine": "chrome"` to wake up the browser.

**Comment by bpasero** [comment]
@ChinaGodMan thanks, I am curious how the log looks like again for insiders.

**Comment by ChinaGodMan** [comment]
> @ChinaGodMan thanks, I am curious how the log looks like again for insiders.

It doesn't matter

**Comment by bpasero** [comment]
For me it does.

**Comment by ChinaGodMan** [comment]
> For me it does.

thanks
