### ISSUE TITLE
[loc][Query][VSCode] Please clarify localizability of "main"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#22542]
Hi, we have a question from our translator. Can you help please? Thanks!

**Source:**
Node.js: Electron Main

**File Name:**
package.nls.resx

**Resource ID:**
".resx", 0; "node.snippet.electron.label"

**Query:**
Please confirm "main" is translatable on this context? Thanks!

**Comment by weinand** [comment]
"Node.js: Electron Main" is the name of a snippet that has the longer description: "Debug the Electron main process".
"Electron" is the software program "Electron" and needs no translation.
And "Main" is short for "main process" and needs translation.
