### ISSUE TITLE
error message close button not working or hangs

### ISSUE THREAD

**Issue by shashkanchan** [microsoft/vscode#225468]

**Comment by roblourens** [comment]
Not sure what you're referring to, a screen recording or screenshot might help

**Comment by shashkanchan** [comment]
> Not sure what you're referring to, a screen recording or screenshot might help


https://github.com/user-attachments/assets/2e2af036-10fb-493e-8381-31401a790aad

see here the close button on warning/ error message not working and the warnings/errors are changing automatically and frequently. in addition to this I can't edit the code. thank you!
