### ISSUE TITLE
[loc][Query][VSCode] Please clarify context for "node.protocol.auto.description"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#22544]
Hi, we have a question from our translator. Can you help please? Thanks!

**Source:**
try to detect the best protocol automatically

**File Name:**
package.nls.resx

**Resource ID:**
".resx", 0; "node.protocol.auto.description"

**Query:**
Context required. Does "try" refer to a program/process/etc. or to the user? Thanks!

**Comment by weinand** [comment]
"Try" refers to the VS Code program, not the user.

This description refers to an configuration option that the user can use to
"make VS Code try to detect the best protocol automatically"

**Comment by josefhosek** [comment]
Thanks!
