### ISSUE TITLE
${workspaceFolder} contains a leading slash on windows systems. It must not.

### ISSUE THREAD

**Issue by SeidChr** [microsoft/vscode#225498]
Does this issue occur when all extensions are disabled?: Yes/No

VSCODE-About:
Version: 1.92.0 (user setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

0. use a windows system with vscode
1. use ${workspaceFolder} in a .vscode\settings.json value
2. print the calculated value (I am using asciidocjs and print the attribute into a .adoc document, then look at the preview)

the value will be something like "/c:/abc"
it should be "c:\abc"

The direction of the slash actually doesn't matter so much, but the leading slash breaks certain tools, which are unfortunately unable to execute logic which could remove the slash.

The settings.json (inside of a project-local .vscode folder):
```json
{
  "asciidoc.extensions.enableKroki": true,
  "asciidoc.preview.asciidoctorAttributes": {
      "kroki-server-url": "https://kroki.###############",
      "documentroot": "${workspaceFolder}/asciidoc/root/src",
      "imagesdir": "${workspaceFolder}/asciidoc/root/src/images",
  },
}
```

**Comment by alexr00** [comment]
Which setting are you setting are you using?

**Comment by SeidChr** [comment]
> Which setting are you setting are you using?

i added it to the original post :)

**Comment by alexr00** [comment]
Thanks! VS Code doesn't do variable resolving for all settings. Since that's an extension provided setting, it's the extension that provides the setting that's including that slash.

**Comment by SeidChr** [comment]
Created a ticket here:
https://github.com/asciidoctor/asciidoctor-vscode/issues/897
