### ISSUE TITLE
Highlighting breaks with svg in HTML

### ISSUE THREAD

**Issue by hexadecimal233** [microsoft/vscode#225414]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.1
- OS Version: Windows 11

I was writing in vue and the highlighting seems to be glitched

Steps to Reproduce:

```
<template>
	<svg></svg
		>
</template>

<script lang="ts" setup>
//That doesn't work
</script>
```
```
<template>
	<svg></svg>
</template>

<script lang="ts" setup>
//That works
</script>
```
![image](https://github.com/user-attachments/assets/f9ab1b2f-1330-4f2a-81fd-ec910d346efc)
![image](https://github.com/user-attachments/assets/073ae0ab-6e25-4f9e-b903-58734a563e1b)

**Comment by alexr00** [comment]
I can repro. Linking to https://github.com/microsoft/vscode/issues/202915, which is tracking all the issues that could be fixed by trying a new grammar
