### ISSUE TITLE
Debug evals `require` for debug command

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#225464]
In ESM, there is no `require` anymore:

https://github.com/microsoft/vscode/blob/8be09bfd3828af8ee104ab48b50c2b4a33bf9f29/src/vs/workbench/contrib/debug/node/debugAdapter.ts#L210

I would suggest to use this piece of code here provided it works with eval:

```js
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
```

Alternatively, use `import(...)`, but this requires the target to be either ESM or a subset of CJS.

**Comment by connor4312** [comment]
Does that actually break with that line? That line is forking a child process with the require in the node `-e <eval>` argument which should be unaffected by the current process' loader.

**Comment by bpasero** [comment]
@connor4312 is there a way for me to test this from our ESM build somehow?

**Comment by connor4312** [comment]
1. Clone https://github.com/microsoft/vscode-mock-debug
2. Change [this](https://github.com/microsoft/vscode-mock-debug/blob/f9f23d69eb834c04347aa32e0ca3506100e7366c/src/extension.ts#L32) to `server`
3. Debug the extension and verify you can then 'debug' a markdown file

**Comment by bpasero** [comment]
Seems to work!
