### ISSUE TITLE
Multiple quick fix bulbs appearing on selection

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#22546]
- VSCode Version: 1.11.0
- OS Version: Win 10

Steps to Reproduce:

1. Create an unused function/variable.
2. Select multiple lines with unused function/variable declaration within the editor.
![bulbs](https://cloud.githubusercontent.com/assets/2239563/23860748/1d40fb94-0808-11e7-9a5c-66678272036b.gif)

**Comment by jrieken** [comment]
dupe #22517
