### ISSUE TITLE
Using VSCODE default settings, extra space added in SCSS file if there are comma separated child selectors

### ISSUE THREAD

**Issue by threeFatCat** [microsoft/vscode#225465]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.1 (user setup)
- OS Version: Windows_NT x64 10.0.22635 (Windows 11 Pro)

Steps to Reproduce:

1. Started Extension Bisect
2. On initial run I can reproduce the issue. 

Input:

```
.container {
    .h1,
    .h2 {
        color: green;
    }
}
```

Output:

```
.container {

    .h1,
    .h2 {
        color: green;
    }
}
```

lint throws the error:

`Unexpected empty line before rule       rule-empty-line-before`

I tested it either using a regular selector `p, h1, select` or `#id, #id-1` as long as there is a comma it adds a space ahead.

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?
