### ISSUE TITLE
Source control  panel turned extremly slow

### ISSUE THREAD

**Issue by 5starcoders** [microsoft/vscode#225469]
Type: <b>Bug</b>

When click on Source control, panel take too long to load. Specially Commit button. 

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13500H (16 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.64GB (6.17GB free)|
|Process Argv|--crash-reporter-id 2cdc005b-caee-46ac-8124-59ff8b9d8278|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.17.2
copilot|Git|1.221.0
copilot-chat|Git|0.18.1
vscode-pull-request-github|Git|0.94.0
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-c:31111712

```

</details>

**Comment by gjsjohnmurray** [comment]
Did you try the setting `"scm.showHistoryGraph": false` that the release notes mention?

**Comment by gkovats** [comment]
> Did you try the setting `"scm.showHistoryGraph": false` that the release notes mention?

You just saved me at least 90 seconds of wait this week, and the hassle of reading documentation!

**Comment by 5starcoders** [comment]
> > Did you try the setting `"scm.showHistoryGraph": false` that the release notes mention?
> 
> You just saved me at least 90 seconds of wait this week, and the hassle of reading documentation!

Where do i find this setting?

**Comment by gjsjohnmurray** [comment]
@5starcoders it was removed in 1.93 when the graph got its own view, which you can collapse by clicking its `>` icon or hide completely from its titlebar context menu.
