### ISSUE TITLE
[loc][Query][VSCode] Please clarify meaning of "at minimum of viewport"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#22541]
Hi, we have a question from our translator. Can you help please? Thanks!

**Source:**
Lines will wrap at the minimum of viewport and `editor.wordWrapColumn`.

**File Name:**
src\vs\editor\common\config\commonEditorConfig.nls.resx

**Resource ID:**
".resx", 0; "wordWrap.bounded"

**Query:**
Could you clarify "at the minimum"? Thanks!

**Comment by hasan-abdul-rahman** [comment]
Means whichever is smaller, the viewport (the edge of the window) or the number in the setting.

For example, if the setting says to wrap at the 80th char, but the window is small so as to only show 50 chars per line, it will wrap at the 50th char.
