### ISSUE TITLE
Support debug location references

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#225425]
Ref: https://github.com/microsoft/debug-adapter-protocol/pull/494

Should allow ctrl+cmd click and "go to" context menu actions in places where we display variables, including:

- Variables view
- Watch view
- Debug hovers(?)
- REPL

In js-debug these will only be (initially) available for function types, including class constructors.

**Comment by vogelsgesang** [comment]
>Should allow ctrl+cmd click [...] Variables view

Would there be two separate clickable areas?

E.g., for the screenshot,
<img width="1792" alt="Screenshot 2023-02-10 at 15 42 24" src="https://user-images.githubusercontent.com/6820896/218119539-308b7c90-d21c-4284-960e-6db9d6d7b274.png">

Cmd+clicking on `f` would take me to line 13, where the variable `f` was declared. Clicking on the gray text "a.out\`greet() at [...]" would take me to line 3.

Is this also what you are having in mind?

**Comment by connor4312** [comment]
> Cmd+clicking on f would take me to line 13, where the variable f was declared. Clicking on the gray text "a.out`greet() at [...]" would take me to line 3.

Yes
