### ISSUE TITLE
JS/TS Language Service Crashing

### ISSUE THREAD

**Issue by CameronDunning** [microsoft/vscode#225409]
Type: <b>Bug</b>

The JS/TS language service keeps crashing. I can reproduce after I ask a question in github copilot, but I'm not sure if that is the main cause.

VS Code version: Code 1.92.1 (Universal) (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (4.93GB free)|
|Process Argv|--crash-reporter-id 338c9a74-8d43-48c2-ac4f-ad08ac724678|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.12.6
npm-intellisense|chr|1.4.5
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.2.3
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
copilot|Git|1.221.0
copilot-chat|Git|0.18.1
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.94.0
go|gol|0.42.0
terraform|has|2.32.2
vscode-react-typescript|inf|1.3.1
find-unused-exports|iul|2.1.4
svg|joc|1.5.4
vscode-colorize|kam|0.11.1
vscode-versionlens|pfl|1.14.2
material-icon-theme|PKi|5.9.0
quicktype|qui|23.0.170
tailwind-fold|sti|0.2.0
console-ninja|Wal|1.0.340

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-c:31111712

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled) (except copilot)?

**Comment by CameronDunning** [comment]
It does not reproduce. I am able to see errors underlined even after using github copilot

**Comment by mjbvz** [comment]
Thanks for checking. It sounds like this issue has already been fixed then or was caused by one of your installed extensions
