### ISSUE TITLE
The file encoding is not being detected correctly

### ISSUE THREAD

**Issue by rodrigoestevao** [Microsoft/vscode#22549]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.13.4|
|plsql|casian|0.0.2|
|jshint|dbaeumer|0.10.15|
|githistory|donjayamanne|0.2.0|
|EditorConfig|EditorConfig|0.6.0|
|code-runner|formulahendry|0.6.13|
|beautify|HookyQR|0.8.9|
|Angular1|johnpapa|0.1.16|
|Angular2|johnpapa|2.0.3|
|PowerShell|ms-vscode|0.9.0|
|debugger-for-chrome|msjsdiag|2.6.0|
|vscode-icons|robertohuertasm|7.3.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1) I exported an SQL file as Windows 1252 and opened the file. The file was opened as  UTF-8. 
2) I reopened the file as 1252 and saved than using the same encoding although when I opened the file again, it still as UTF-8.

**Comment by bpasero** [comment]
@rodrigoestevao currently we only allow you to configure the encoding for the entire workspace, not a single file. However as long as you keep the file open inside a tab, the encoding should be preserved.

There are other issues to be able to configure the encoding per file, even when you close the file. And then there is another issue that asks for automatic detection of the encoding, so I am closing this one as duplicate.
