### ISSUE TITLE
Slow, laggy and zittery notebooks while scrolling.

### ISSUE THREAD

**Issue by AparneshShukla** [microsoft/vscode#225597]
Type: <b>Performance Issue</b>

Hello, I am Aparnesh from India. I am using VS Code from almost 7 years and I really loved it for its smoothness and flexibility towards any kind of development or programming.

However, nowadays from a year ago I am using VS Code as my primary editor for notebooks ( I mean ipynb files). And all the projects I am doing on it, as I shifted from Jupyter Lab and Jupyter Notebook.

But, Really I want to tell you guys, I have a laptop with 16GB of RAM AMD Ryzen 5500U processor which is a really good capable processor works fine with Android development, and a NVMe storage of 512GB.

I don't know what is the issue, Is it because of there is no Dedicated big GPU card available in my laptop, however I have a AMD Radeon Graphics with Dedicated 512MB memory and a shared GPU memory of 7GB with RAM.

Or whatever it is, I don't know why My VS Code is laggy with the Jupyter Notebooks while I scrolls down or scrolls up. Perhaps it loads or whatever, when I say laggy it means that while scrolling the cells zitters very fast but there is something which is not looking good and making me feel like I have no processing power.

It is really a humble request to you guys if you can fix it, please consider my problem it is seriously very problematic. Does'nt feel  good. 

While in other areas everything good, recently I gone through the may relesase note and found the new feature for remote pc or devices, the terminal scrollbar got new look, the keyboard keybinding setting update everything look good.

I appreciate your hard work, and oviously smart work and your dedication to acheive new updates with the consistancy you guys maintain and always do changes or add features with keeping in mind that a user will get greater experience.

Thanks for all of these guys. Stay Blessed and Do always what you are doing.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.35GB (7.97GB free)|
|Process Argv|C:\\Users\\Acer\\OneDrive\\Documents\\Aparnesh_Shukla\\Personal\\Machine_Learning\\NumPy.code-workspace --crash-reporter-id db02070a-6dee-43c6-8a7d-f76e6148499c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   137	 11780	code main
    0	   146	  3704	   gpu-process
    0	   260	  7676	window [1] (session_16_pandas_series.ipynb - NumPy (Workspace) - Jupyter - Visual Studio Code)
    0	   129	  8404	   window
    0	    28	 10560	   crashpad-handler
    0	    42	 11316	   utility-network-service
    0	   583	 11564	extensionHost [1]
    0	     4	   908	     c:\Users\Acer\OneDrive\Documents\Aparnesh_Shukla\Personal\Machine_Learning\NumPy\venv\Scripts\python.exe c:\Users\Acer\.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\lsp_server.py
    0	    11	  7176	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    48	  7348	       "C:\Users\Acer\AppData\Local\Programs\Python\Python311\python.exe" c:\Users\Acer\.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\lsp_server.py
    0	   102	  2956	     electron-nodejs (server.js )
    0	   103	  4900	     "C:\Users\Acer\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Acer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\markdown-language-features\dist\serverWorkerMain" --node-ipc --clientProcessId=11564
    0	    89	  8284	     electron-nodejs (server.js )
    0	   126	  8820	     electron-nodejs (languageServer.js )
    0	   208	 10196	     electron-nodejs (bundle.js )
    0	     4	 10540	     c:\Users\Acer\OneDrive\Documents\Aparnesh_Shukla\Personal\Machine_Learning\NumPy\venv\Scripts\python.exe c:\Users\Acer\.vscode\extensions\ms-python.black-formatter-2024.2.0\bundled\tool\lsp_server.py --stdio
    0	    11	 14660	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    49	 16600	       "C:\Users\Acer\AppData\Local\Programs\Python\Python311\python.exe" c:\Users\Acer\.vscode\extensions\ms-python.black-formatter-2024.2.0\bundled\tool\lsp_server.py --stdio
    0	     4	 13952	     electron-nodejs (Dx.js )
    0	    65	  2776	       electron-nodejs (Dx.js )
    0	    11	 10980	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    17	 14104	     c:\Users\Acer\AppData\Local\Programs\Python\Python311\python.exe c:\Users\Acer\.vscode\extensions\ms-toolsai.jupyter-2024.4.0-win32-x64\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 11564
    0	    11	  9944	       C:\WINDOWS\system32\conhost.exe 0x4
    0	     4	 16372	     electron-nodejs (wAVSKc.js )
    0	    65	  7164	       electron-nodejs (wAVSKc.js )
    0	    11	 15108	       C:\WINDOWS\system32\conhost.exe 0x4
    1	   106	 11816	window [2] (Issue Reporter)
    0	   116	 15752	ptyHost
    0	     7	  4252	     conpty-agent
    0	    75	  7560	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\Acer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     7	  8320	     conpty-agent
    0	    80	  8380	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\Acer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	    81	 11472	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\Acer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     7	 12472	     conpty-agent
    0	    87	 16424	fileWatcher [1]
    0	   100	 17292	   window
    0	   123	 17328	shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (session_16_pandas_series.ipynb - NumPy (Workspace) - Jupyter - Visual Studio Code)
|    Folder (NumPy): 16684 files
|      File types: py(5299) pyc(5299) pyi(2098) pyd(150) txt(86) lib(69)
|                  afm(60) c(57) f90(49) h(45)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-django|bat|1.15.0
vscode-tailwindcss|bra|0.12.6
flask-snippets|cst|0.1.3
dart-code|Dar|3.94.0
flutter|Dar|3.94.0
competitive-programming-helper|Div|2024.7.1722430096
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.2.3
vsc-material-theme|Equ|34.5.2
vsc-material-theme-icons|equ|3.8.7
prettier-vscode|esb|10.4.0
vscode-firefox-debug|fir|2.9.10
code-runner|for|0.12.2
kotlin|fwc|0.2.35
copilot|Git|1.222.0
copilot-chat|Git|0.18.1
copilot-labs|Git|0.17.1121
heygithub|Git|0.21.1441
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-ansi|ili|1.1.7
better-cpp-syntax|jef|1.27.1
polacode-2019|jef|0.6.1
MagicPython|mag|1.1.0
Kotlin|mat|1.7.1
vscode-language-babel|mgm|0.0.40
mongodb-vscode|mon|1.7.0
vscode-docker|ms-|1.29.2
vscode-edge-devtools|ms-|2.1.5
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
vscode-speech|ms-|0.10.0
vsliveshare|ms-|1.0.5936
vsliveshare-pack|ms-|0.4.0
material-icon-theme|PKi|5.9.0
java|red|1.33.0
LiveServer|rit|5.7.9
vscode-fileutils|sle|3.10.3
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
jinja|who|0.0.8
open-in-external-app|YuT|0.10.0

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718

```

</details>

**Comment by rebornix** [comment]
@AparneshShukla can you please help provide a screen recording of what you were seeing to help us troubleshoot? I have a few ideas why it happens but want to gather enough info, thanks in advance!
