### ISSUE TITLE
automaticaly open debug file and show launch program popup.

### ISSUE THREAD

**Issue by Md-sajeeb001** [microsoft/vscode#225583]
![Screenshot_88](https://github.com/user-attachments/assets/70a140fb-3d7f-4e20-af49-d65c664eb7a8)

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce: 

1. #104372 when I open my vscode he send a launch program popup . it's look like new error, and when I click the cancel button it not cancel this popup also same work yes button how could I solved this problem ?

**Comment by roblourens** [comment]
This is coming up automatically? Or when you try to start debugging? If it comes up automatically it would likely be because of an extension, you can check your installed extensions or run F1 > Troubleshoot Issue to check

**Comment by Md-sajeeb001** [comment]
> This is coming up automatically? Or when you try to start debugging? If it comes up automatically it would likely be because of an extension, you can check your installed extensions or run F1 > Troubleshoot Issue to check



> This is coming up automatically? Or when you try to start debugging? If it comes up automatically it would likely be because of an extension, you can check your installed extensions or run F1 > Troubleshoot Issue to check

I already download run extensions .

**Comment by roblourens** [comment]
I don't understand, please explain more
