### ISSUE TITLE
Markdown highlight misunderstands plantuml string inside sh snippet

### ISSUE THREAD

**Issue by awvalenti** [microsoft/vscode#225533]
Type: <b>Bug</b>

Markdown highlighting understands a='
plantuml
' as language switching from shell script to plantuml. Then it highlights stuff incorrectly. See example below and attached GIF. Note that `#wrong` goes from gray to white when it should'nt.

```sh
# right
r1='
  anything
'

# right
r2='
  plantum
'

# right
r3='
  Plantuml
'

# right
r4='plantuml'

w1='
  plantuml
'
# wrong

w2=plantuml
# wrong

w3='plantuml '
# wrong

w4="plantuml "
# wrong

```

![Peek 13-08-2024 18-25](https://github.com/user-attachments/assets/1d15ef32-3f6b-4fd5-8d2c-29a817098d4d)

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Linux x64 5.15.0-118-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz (16 x 3784)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|15.10GB (8.00GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id e478582e-a30a-45d5-8978-2ed55806744f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
plantuml|jeb|2.18.1
color-highlight|nau|2.8.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|5.9.0
vim|vsc|1.27.3
gitblame|wad|11.0.1

(3 theme extensions excluded)

</details>

**Comment by RedCMD** [comment]
works for me?
![image](https://github.com/user-attachments/assets/3588a7d9-ba2f-424d-8a26-a136a2792543)

**Comment by awvalenti** [comment]
Oops, you're right... It's an extension issue, opened it here: https://github.com/qjebbs/vscode-plantuml/issues/592. My bad, forgot to run `code --disable-extensions`. Thanks!
