### ISSUE TITLE
lightbulb in the gutter bug

### ISSUE THREAD

**Issue by EHMilon** [microsoft/vscode#225501]
In VS Code newer version lightbulb conflict with other gutter icons. Editor position is jumping.
Here is a video:
https://github.com/user-attachments/assets/2541a223-78a3-4d42-b6b5-ee237f800b6e

Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.92.1
- OS Version: Windows 11

Steps to Reproduce:

1. lightbulb should overlap over other getters icon
2. Alternatively, an option could be included in the settings to control the displayed position of the lightbulb.

**Comment by justschen** [comment]
duplicate https://github.com/microsoft/vscode/issues/225681
