### ISSUE TITLE
add an absolute folder in "workbench.editor.customLabels.patterns"

### ISSUE THREAD

**Issue by LeninZapata** [microsoft/vscode#225553]
I want to add a custom label in the VScode tabs with its new feature "workbench.editor.customLabels.patterns", when I use relative paths it works fine
![image](https://github.com/user-attachments/assets/0959d00d-f8ac-4900-876b-df6ec509536d)

but I want to refer to an absolute path that the other folder is in another directory outside the Workspace but I can't make this work, someone who can help me
![image](https://github.com/user-attachments/assets/06b80249-d6e1-4e96-a34a-b616ac17986d)

my `setting.code-workspace`

```
"workbench.editor.customLabels.patterns": {
  "minibot/*": "${filename}.${extname} / lenin",
  "C:/laragon/www/botnew/my-orignal-bot/*": "${filename}.${extname} / wale"
},
```

**Comment by benibenj** [comment]
Currently you have to have a `/` at the start of your absolute path for it to work. Try using `"/C:/laragon/www/botnew/my-orignal-bot/*": "${filename}.${extname} / wale"`

**Comment by benibenj** [comment]
@LeninZapata actually I think the C at the start has to be a small c. So it would be `"/c:/laragon/www/botnew/my-orignal-bot/*": "${filename}.${extname} / wale"`. When we fetch the file path it seems to always return the disk as lower case letter. I'll have a look if there is something we can do about it

**Comment by LeninZapata** [comment]
I also did that but it doesn't work. I would like you to give support to this topic since I need to put labels in the tabs in different directories outside the work area.
![image](https://github.com/user-attachments/assets/5e170f1a-4810-4301-beba-6e218233340c)

**Comment by benibenj** [comment]
@LeninZapata I believe you have a spelling mistake in your pattern. You specified `.../my-orignal-bot/...` but the folder is called `.../my-original-bot/...`

**Comment by LeninZapata** [comment]
You're right, this was my mistake, it worked! Thank you very much.
