### ISSUE TITLE
Entering a path to a valid file in the "Go To File" (cmd-P) popup should immediately resolve to a file

### ISSUE THREAD

**Issue by frewsxcv** [Microsoft/vscode#22555]
- VSCode Version: Version 1.10.2 (1.10.2)
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. Open a large project
2. Open the "Go To File" popup (cmd-P on Mac)
3. Enter a relative path to a file in the project

vscode seems to do some sort of query at this point and takes a while to resolve something, even though it could just immediately check to see if that file exists.

**Comment by roblourens** [comment]
We had something like this and removed it in https://github.com/Microsoft/vscode/issues/53510
