### ISSUE TITLE
Typescript and javascript language features not working 

### ISSUE THREAD

**Issue by NiRaJsHa91** [microsoft/vscode#225510]
Type: <b>Bug</b>

even if it running. Like when importing modules no suggestion list for autocompletion of import statements is shown for installed npm modules

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.28GB free)|
|Process Argv|--crash-reporter-id 9e1429b4-615f-4088-ab21-dabf91f2e5c2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
agile-css-suggestion|Agi|1.0.8
react-hooks-snippets|AlD|1.2.0
tailwind-documentation|alf|0.1.15
html-end-tag-labels|ant|1.0.0
emojisense|bie|0.10.0
blackbox|Bla|1.3.73
bracket-pair-color-dlw|Bra|0.0.6
vscode-tailwindcss|bra|0.12.6
npm-intellisense|chr|1.4.5
codeium|Cod|1.10.11
svg-gallery|dev|2.1.0
javascript-ejs-support|Dig|1.3.3
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.94.0
tailwind-config-viewer|Kal|0.0.86
vscode-language-babel|mgm|0.0.40
parse-to-css-vscode-plugin|mrg|0.0.8
debugpy|ms-|2024.10.0
python|ms-|2024.12.2
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vs-html-to-css|nep|1.0.0
prisma|Pri|5.18.0
view-in-browser|qin|0.0.5
java|red|1.33.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
html-to-css-autocompletion|sol|1.1.2
tailwind-fold|sti|0.2.0
open-in-browser|tec|2.0.0
highlight-matching-tag|vin|0.11.0
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-icons|vsc|12.8.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.17.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
