### ISSUE TITLE
InstantiationService has been disposed

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#225575]
```javascript
Error: InstantiationService has been disposed
at g.m in src/vs/platform/instantiation/common/instantiationService.ts:69:10
at g.createInstance in src/vs/platform/instantiation/common/instantiationService.ts:119:8
at L.m in src/vs/editor/browser/widget/codeEditor/codeEditorContributions.ts:156:48
at L.get in src/vs/editor/browser/widget/codeEditor/codeEditorContributions.ts:98:8
at p.getContribution in src/vs/editor/browser/widget/codeEditor/codeEditorWidget.ts:1026:30
at ue.get in src/vs/workbench/contrib/testing/browser/testingOutputPeek.ts:414:17
at pe.closeAllPeeks in src/vs/workbench/contrib/testing/browser/testingOutputPeek.ts:198:32
at handler in src/vs/workbench/contrib/testing/browser/testing.contribution.ts:201:36
at fn in src/vs/platform/instantiation/common/instantiationService.ts:109:11
at v.n in src/vs/workbench/services/commands/common/commandService.ts:95:46
at v.executeCommand in src/vs/workbench/services/commands/common/commandService.ts:60:17
at u.value in src/vs/workbench/contrib/testing/browser/testingExplorerView.ts:758:20
at o.B in src/vs/base/common/event.ts:1230:13
at o.fire in src/vs/base/common/event.ts:1261:9
at re.j in src/vs/platform/list/browser/listService.ts:778:19
at re.h in src/vs/platform/list/browser/listService.ts:770:8
at u.value in src/vs/platform/list/browser/listService.ts:706:112
at o.B in src/vs/base/common/event.ts:1230:13
at o.fire in src/vs/base/common/event.ts:1261:9
at u.value in src/vs/base/common/event.ts:161:97
at o.B in src/vs/base/common/event.ts:1230:13
at o.fire in src/vs/base/common/event.ts:1261:9
at u.value in src/vs/base/common/event.ts:127:84
at o.B in src/vs/base/common/event.ts:1230:13
at o.C in src/vs/base/common/event.ts:1241:9
at o.fire in src/vs/base/common/event.ts:1265:9
at u.value in src/vs/base/common/event.ts:127:84
at o.B in src/vs/base/common/event.ts:1230:13
at o.fire in src/vs/base/common/event.ts:1261:9
at HTMLDivElement.E in src/vs/base/browser/event.ts:40:41
```
[Go to Errors Site](https://errors.code.visualstudio.com/card?ch=eaa41d57266683296de7d118f574d0c2652e1fc4&bH=bffd65a3-34e2-378b-879e-7ca57dc55f18)

**Comment by connor4312** [comment]
@hediet this smells like some kind of bug in code editor land. This error is encountered trying to close all peeks:

https://github.com/microsoft/vscode/blob/413e6ede4bb7fc8676d021a7bcd81c3035492369/src/vs/workbench/contrib/testing/browser/testingOutputPeek.ts#L191-L195

and `.get` is simply:

https://github.com/microsoft/vscode/blob/413e6ede4bb7fc8676d021a7bcd81c3035492369/src/vs/workbench/contrib/testing/browser/testingOutputPeek.ts#L408-L410

It seems like we might have a stale code editor(?) in that list that's hanging on to a disposed instantiation service, and is then trying to create the contribution in this call. Or is there something I'm doing wrong here?


This was error triggered from a user click action in the tree, so I don't think it's some synchronous/racey condition:

https://github.com/microsoft/vscode/blob/8bf04271f7101185545718133abbea153c95c7ca/src/vs/workbench/contrib/testing/browser/testingExplorerView.ts#L779

**Comment by hediet** [comment]
> It seems like we might have a stale code editor(?) 

Could be. It's odd to create the contribution just to close it though, I think the editor is missing some `getIfInstantiated`.

Unfortunately, without repro steps this is unactionable on my side.
Also, I struggle to make use of the stack-trace, as the line numbers are off (relative to main) and the method names are cryptic.
I wished the stacktraces would contain the sha of the commit they are from and there would be an easy way to inspect the stacktrace in VS Code.

**Comment by connor4312** [comment]
I'm not able to repro
