### ISSUE TITLE
no selection highlight in completion list

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#22551]
- VSCode Version: insiders 1.11.0 dd197f1
- OS Version:Mac OS

Steps to Reproduce:

bring up completion list, here is what i see:

![image](https://cloud.githubusercontent.com/assets/1487073/23865412/dbc19ba4-07d2-11e7-85a2-7d82df585c67.png)

there is no highlight of the currently active item in the list and in the above example it would be "arguments"

**Comment by weinand** [comment]
@joaomoreno announced that the widget is broken today...

**Comment by joaomoreno** [comment]
#22509
