### ISSUE TITLE
Open File/Folder Dialog Disappears when Selecting More View Options

### ISSUE THREAD

**Issue by METACEO** [Microsoft/vscode#22550]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. Open `Visual Studio Code`
2. Open the File Dialog with `File > Open File...` or `File > Open Folder...`
3. Go to the `Change your view.` option and click the down arrow for `More options`

Maybe a Windows 7 Classic Theme issue?.. please see attached:

![1-before](https://cloud.githubusercontent.com/assets/13586713/23865288/35ee9bbc-07e3-11e7-99e0-8fe6f2da66f7.png)
![2-after](https://cloud.githubusercontent.com/assets/13586713/23865292/39c96dac-07e3-11e7-8564-68279f2465c6.png)

**Comment by bpasero** [comment]
Since this issue is rather old, I am closing this and ask anyone to open a new issue if this is still happening.
