### ISSUE TITLE
trimTrailingWhitespace conflicts with insertFinalNewline

### ISSUE THREAD

**Issue by ir-ma3x** [Microsoft/vscode#22558]
`trimTrailingWhitespace` deletes the line created by `insertFinalNewline`.

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.7.0|
|html-css-class-completion|Zignd|1.0.3|
|html-snippets|abusaidm|0.1.0|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|githistory|donjayamanne|0.2.0|
|vscode-html-css|ecmel|0.0.33|
|tslint|eg2|0.8.1|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.3|
|Angular2|johnpapa|2.0.3|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|Go|lukehoban|0.6.55|
|debugger-for-chrome|msjsdiag|2.6.0|
|vscode-icons|robertohuertasm|7.3.0|
|sass-indented|robinbentley|1.3.0|
|stylelint|shinnn|0.23.0|
|cordova-tools|vsmobile|1.2.7|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. add `"files.trimTrailingWhitespace": true` to `settings.json`.
2. add `"files.insertFinalNewline": true` to `settings.json`.
3. reload.

**Comment by alexandrudima** [comment]
@ir-ma3x i cannot reproduce this. i.e. this appears to be working correctly for me:

can you perhaps try with disabling all extensions (`code --disable-extensions`):

![22558](https://cloud.githubusercontent.com/assets/5047891/24407532/796f9550-13cb-11e7-8fa6-c9828d88763d.gif)

**Comment by c4milo** [comment]
I'm seeing this as well. @alexandrudima, after saving go and cat the file involved, you will see it has no new line.

**Comment by alexandrudima** [comment]
@c4milo 

Does this issue occur in any file or only on `.go` files?

Can you reproduce when running `code --disable-extensions` ?

**Comment by c4milo** [comment]
I was testing with a Vagrantfile and it was happening. I think `files.insertFinalNewline` is just not doing its thing because it happens even having `files.trimTrailingWhitespace` in `false`

**Comment by c4milo** [comment]
@alexandrudima I just tested with `--disable-extensions` and it seems to work well.

**Comment by alexandrudima** [comment]
@c4milo Have you found any steps / pattern for when this doesn't work ?

This works consistently as expected for me:
* when running with `code --disable-extensions`.
* when editing files in a fresh folder (i.e. no workspace settings), only `files.insertFinalNewline`

Looping in @bpasero , he knows all that is involved in the file save path.

**Comment by c4milo** [comment]
@alexandrudima, yes, I basically go and edit the file in vscode and double check it with `vim` and `hexdump`. I never see the newline that vscode was supposed to append at the bottom. To work around it, I'm inserting two newlines in vscode to really get the result I want.

**Comment by bpasero** [comment]
I can also not reproduce, sorry. @c4milo can you share your full settings file? Do you have workspace settings configured?

**Comment by c4milo** [comment]
I was under the wrong assumption regarding POSIX's new lines. This works as expected. Thank you!

**Comment by bpasero** [comment]
I can also not reproduce, sorry. @ir-ma3x can you share your full settings file? Do you have workspace settings configured?
