### ISSUE TITLE
File source code management can cause other extensions to hang

### ISSUE THREAD

**Issue by liuhuo23** [microsoft/vscode#225588]
Type: <b>Bug</b>

File source code management can cause other extensions to hang。
When there are too many commit modifications in the project, it can make the entire application extremely 

VS Code version: Code 1.92.1 (Universal) (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Darwin arm64 24.0.0
Modes:
Remote OS version: Linux x64 6.9.8-orbstack-00170-g7b4100b7ced4

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|18.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 6182a0e0-09ed-40a6-b2bb-4afca10b0246|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|开发容器: Docker Compose @ orbstack|
|OS|Linux x64 6.9.8-orbstack-00170-g7b4100b7ced4|
|CPUs|unknown (11 x 2000)|
|Memory (System)|5.78GB (0.38GB free)|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
macos-modern-theme|dav|2.3.19
file-icons|fil|1.1.0
pythonsnippets|frh|1.0.2
vsc-python-indent|Kev|1.18.0
debug-tracker-vscode|mcu|0.0.15
peripheral-viewer|mcu|1.4.6
theme-monokai-pro-vscode|mon|1.3.2
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
errorlens|use|3.20.0
vim|vsc|1.27.3
jetbrains-product-icons|yat|0.0.8
linkerscript|Zix|1.0.4
codegeex|AMi|2.14.2
ruff|cha|2024.40.0
gitlens|eam|15.2.3
comment-translate|int|2.3.3
vscode-go-template|jin|0.2.1
add-to-gitignore|mac|1.0.0
git-graph|mhu|1.30.0
document|min|2.2.2
vscode-language-pack-zh-hans|MS-|1.92.2024080709
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
errorlens|use|3.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717

```

</details>

**Comment by gjsjohnmurray** [comment]
The new History Graph feature in 1.92 is adversely affecting performance for some users. Please you to Settings Editor, search for scm.showHistoryGraph and clear the checkbox. Does this resolve your issue?
