### ISSUE TITLE
Improper syntax highlighting with line changes for `.sh` files

### ISSUE THREAD

**Issue by liufeimath** [microsoft/vscode#225561]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.1
- OS Version: Mac OS x, Windows (this is an universal issue, I see it everywhere)

Steps to Reproduce:

1. open a new file in editor, change syntax highlighting to "Shell Script" 
2. type the following the the editor:
```console
# good
ls -alh

# good
ls \
    -alh \

# not good, `-alh` should be "blue" as well
ls \
-alh \
```
and check the syntax highlighting:
<img width="485" alt="Screenshot 2024-08-14 at 12 56 21 AM" src="https://github.com/user-attachments/assets/c7e4854b-14d8-4307-98b3-936fd72c3247">

Also look at the markdown rendering above in step 2. It shows that Github web page can handle the rendering properly even in a markdown snippet.

**Comment by alexr00** [comment]
Copied to the upstream repo: https://github.com/jeff-hykin/better-shell-syntax/issues/99
