### ISSUE TITLE
[Feature Request] Multiple Active Search

### ISSUE THREAD

**Issue by robpaveza** [Microsoft/vscode#22554]
- VSCode Version: 1.10.2
- OS Version: Windows 10 14393

When I go into a code base, particularly one that is new to me, I might have good luck finding a symbol by doing a global project search (Ctrl+Shift+F to start).  Then I'll find what I'm looking for, but a comment or another symbol will prompt me to look further. 

The language services do pretty well sometimes when handling this situation, but other languages don't necessarily have the same level of support.  So I'm prompted (practically speaking) to open another search.  The trouble here is that it makes my first search go away -- specifically, I lose the state.  I lose which item I last opened, I lose the files that I've collapsed or expanded, etc.

Can we stash Search Results into the pane so we can pull them back up and continue navigating?

**Comment by sandy081** [comment]
Duplicates #16488
