### ISSUE TITLE
AutoSave pastes file(s) with changes into the pane with the focus, on top of the code already there.

### ISSUE THREAD

**Issue by 1nsomniac** [Microsoft/vscode#22552]
- VSCode Version: Code - Insiders 1.11.0-insider (84e56fc527047223a6ad22c31a906d4a579680d0, 2017-03-03T07:10:29.111Z)
- OS Version: Windows_NT ia32 10.0.15055
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-toothpaste|aalaap|0.0.1|
|html-snippets|abusaidm|0.1.0|
|theme-material|bcmarinacci|1.3.0|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.7|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.8.1|
|vscode-npm|fknop|3.3.0|
|Theme-CloudsMidnight|gerane|0.0.2|
|Theme-Colonoscopy|gerane|0.0.2|
|Theme-feelgood|gerane|0.0.2|
|Theme-PastelsonDark|gerane|0.0.2|
|Theme-peel|gerane|0.0.2|
|Theme-Sourlick|gerane|0.0.2|
|Theme-TomorrowNight|gerane|0.0.2|
|Theme-TomorrowNightEighties|gerane|0.0.2|
|Theme-tonic|gerane|0.0.2|
|Theme-zacks|gerane|0.0.2|
|beautify|HookyQR|0.8.9|
|crayon-vscode|jansenfuller|0.1.3|
|theme-charcoal-oceanicnext|joshpeng|1.1.5|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|mssql|ms-mssql|0.3.0|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|vs-keybindings|ms-vscode|0.1.3|
|debugger-for-chrome|msjsdiag|2.6.0|
|theme-oceanicnext|naumovs|0.0.4|
|theme-darktooth|Poorchop|0.0.2|
|theme-cyanicpastels|SamuelLampa|0.0.9|
|Spell|seanmcbreen|0.9.1|
|code-spell-checker|streetsidesoftware|0.17.2|
|theme-glacier|Tyriar|0.0.10|
|dark-plus-material|vangware|0.2.4|
|vscode-wakatime|WakaTime|1.1.3|
|theme-1-southwark-bridge-dark|xaver|0.0.2|;

---

Steps to Reproduce:

1. Turn on autoSave (any option works)
2. Edit file. Wait for, or trigger autoSave. (I have reinstalled vscode, restarted, and tried all the autosave options multiple ways. Issue started after I updated my computer. I'm on the Windows Insiders fast ring. Issue has persisted for more than two weeks.) These screenshots show original saved files, edited text, focus change/save, and then another focus change/save.

![screenshot 17](https://cloud.githubusercontent.com/assets/22018743/23866084/572b6842-07dd-11e7-8e03-0a8cb44000e6.png)
![screenshot 18](https://cloud.githubusercontent.com/assets/22018743/23866083/572344d2-07dd-11e7-830b-497e0b18ff5f.png)
![screenshot 19](https://cloud.githubusercontent.com/assets/22018743/23866081/5721ed6c-07dd-11e7-9347-ecea8ac32539.png)
![screenshot 20](https://cloud.githubusercontent.com/assets/22018743/23866082/57224ea6-07dd-11e7-9ecc-118fc05cf8e9.png)

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by 1nsomniac** [comment]
Ummm, so I resolved this issue. JS-CSS-HTML Formatter (sic) by lonefy instigates the issue. When it's off it doesn't happen.

**Comment by 1nsomniac** [comment]
How do I address that? Is there a way to send this to the extension author?

**Comment by weinand** [comment]
I will move this issue to the https://marketplace.visualstudio.com/items?itemName=lonefy.vscode-JS-CSS-HTML-formatter

**Comment by 1nsomniac** [comment]
Thanks :)

**Comment by weinand** [comment]
This issue was moved to Lonefy/vscode-JS-CSS-HTML-formatter#56
