### ISSUE TITLE
Improper syntax highlighting for f-string and format-string mixes in `.py` files

### ISSUE THREAD

**Issue by liufeimath** [microsoft/vscode#225563]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.1
- OS Version: Mac OS X, windows (this is a universal issue, I checked)

Steps to Reproduce:

1. open a new file in editor, change syntax highlighting to "Python"
2. type the following
```python
# good
a = "{THIS_FORMAT_STRING} is highlighted well"

# not good, expecting `{{THIS_FORMAT_STRING}}` to show in "blue" as well
f_string_format_now = "bla bla bla"
b = f"{{THIS_FORMAT_STRING}} is not highlighted well if I have a {f_string_format_now}"
```
check output (where the syntax highlighting issue is self-explained):
<img width="728" alt="Screenshot 2024-08-14 at 1 12 03 AM" src="https://github.com/user-attachments/assets/129eb17a-3547-40d8-a108-21e144d40b8e">

**Comment by alexr00** [comment]
I am not a python expert, but from my reading it looks like this is highlighted correctly as `{{` escapes the curly brace.

**Comment by liufeimath** [comment]
> I am not a python expert, but from my reading it looks like this is highlighted correctly as `{{` escapes the curly brace.

Ah no no. `{{` in an f-string means `{` in a raw string. So
```python
f"{{THIS_FORMAT_STRING}} is not highlighted well if I have a {f_string_format_now}"
```
evaluates to
```
"{THIS_FORMAT_STRING} is not highlighted well if I have a bla bla bla"
```
(where the `f_string_format_now` is f-string substituted)

That's why I'm saying it should have the consistent syntax highlighting as line-2 in the screenshot. Essentially, the syntax-highlighter failed to consider the f-string context.

Let me give another self-documenting example to illustrate further.
```
# good
a = "{THIS_FORMAT_STRING} is highlighted well"

# not good, expecting `{{THIS_FORMAT_STRING}}` to show in "blue" as well
f_string_format_now = "bla bla bla"
b = f"{{THIS_FORMAT_STRING}} is not highlighted well if I have a {f_string_format_now}"

print(repr(b))
# prints: {THIS_FORMAT_STRING} is not highlighted well if I have a bla bla bla

# see, now it highlights well, which should have been done in the b above
this_is_also_b = "{THIS_FORMAT_STRING} is not highlighted well if I have a bla bla bla"

# this is expected without f-string (but not the above for b)
c = "{{THIS_FORMAT_STRING}} really has two brackets, so the `THIS_FORMAT_STRING` is not highlighted"
```
<img width="811" alt="Screenshot 2024-08-14 at 3 26 21 PM" src="https://github.com/user-attachments/assets/ba57426e-91b0-46f8-a65f-e4b3f82bb804">

**Comment by RedCMD** [comment]
so `{}` is used in format strings and `{{}}` in `f` format strings?

the grammar that VSCode uses comes from https://github.com/MagicStack/MagicPython
sadly it hasn't been updated in the past 2 years

**Comment by liufeimath** [comment]
> so `{}` is used in format strings and `{{}}` in `f` format strings?

`{{` in f-string translates to `{` in a regular string. The point is that, if we are highlighting `{...}` in a regular string due to possible `str.format` calls (which is format string), then we'd better handle the same situation properly in an f-string.

> the grammar that VSCode uses comes from https://github.com/MagicStack/MagicPython sadly it hasn't been updated in the past 2 years

Does it mean that the way to address this is to contact the author of `MagicPython` and propose issues/PRs and get it fixed there? And since it's a "dormant" repo this is a bit hard?

**Comment by RedCMD** [comment]
> Does it mean that the way to address this is to contact the author of `MagicPython` and propose issues/PRs and get it fixed there?

yup and yup

I see there is a similar issue report already
https://github.com/MagicStack/MagicPython/issues/239
