### ISSUE TITLE
Intellisense highlight is gone

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#22560]
- VSCode Version: Code - Insiders 1.11.0-insider (dd197f19ddad6f8fa960c5f330fb7182c2321de3, 2017-03-13T07:19:17.514Z)
- OS Version: Linux x64 4.8.0-41-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-svgviewer|cssho|1.4.0|
|EditorConfig|EditorConfig|0.6.2|
|tslint|eg2|0.8.1|
|git-project-manager|felipecaputo|1.0.1|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|
|lorem-ipsum|Tyriar|1.0.0|
|theme-sapphire|Tyriar|0.0.5|;

---

I don't know what I'm selecting unless there is a description (where it's still hard to determine):

![image](https://cloud.githubusercontent.com/assets/2193314/23873696/1ef02c98-07f0-11e7-8f39-dfd8defee1e6.png)

![image](https://cloud.githubusercontent.com/assets/2193314/23873708/296bc6dc-07f0-11e7-861d-7d218ac1d317.png)

**Comment by joaomoreno** [comment]
#22509
