### ISSUE TITLE
Firefox unable to load extensions or join LiveShare session

### ISSUE THREAD

**Issue by recharging** [microsoft/vscode#225679]
Vscode.dev on Chromium browser runs fine on my system.
Does not load extensions on Firefox.

Version: 1.92.1
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0
Embedder: vscode.dev

![Screenshot_20240815_181016-1](https://github.com/user-attachments/assets/35a1aeb3-5f67-4b1e-a671-a45b033ac14e)

**Comment by sandy081** [comment]
Can you please share the exact error you are seeing. You can get that by opening console in Developer Tools (F1 > Developer: Toggle Developer Tools)
