### ISSUE TITLE
C++: Searching include paths takes forever if there are large sub-directories

### ISSUE THREAD

**Issue by navsan** [Microsoft/vscode#22569]
I tried using VS Code with a C++ project containing a large non-source directory with thousands of files (profile outputs, logs, etc.). The editor was unable to search the include path even after about an hour. Copying just the source files into a new directory and opening it in VS Code resolved the issue.

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jsx|TwentyChung|0.0.1|
|vscode-eslint|dbaeumer|1.2.7|
|vscode-instant-markdown|dbankier|1.1.0|
|python|donjayamanne|0.6.0|
|cpptools|ms-vscode|0.10.3|
|latex|ms-vscode|0.1.3|
|cmake|twxs|0.0.17|
|vim|vscodevim|0.6.5|
|debug|webfreak|0.17.0|;

---

Steps to Reproduce:

1. Create a large non-source directory (with thousands of profile results, logs, etc.) called "output" under the root directory for the project.
2. Create a main.cpp file which includes header files under a directory called "include" in the root directory for the project.
3. Observe that VS Code gives the green squiggly lines underneath the #include directives, but hovering over it does not produce the light bulb. Instead, there's a pop-up saying "searching include path" and "loading". 
4. Removing the large non-source directory resolves the issue in (3) above.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#560

**Comment by weinand** [comment]
@navsan please file extension specific issues with the corresponding repository.

**Comment by bobbrow** [comment]
@navsan, we provided some information to help you deal with this issue over in our GitHub issues page.  Please let us know if that helps resolve your issue.

see: Microsoft/vscode-cpptools#560
