### ISSUE TITLE
VSC crash on search something in markdown view

### ISSUE THREAD

**Issue by Coloryr** [microsoft/vscode#225652]
Type: <b>Bug</b>

VSC crash on search something in markdown view

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700K (24 x 3418)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.75GB (21.67GB free)|
|Process Argv|--crash-reporter-id e61403ef-cf54-46ce-aef4-01633b47178a|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nginx-conf|ahm|0.3.5
doxdocgen|csc|1.4.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
svg|joc|1.5.4
cmake-language-support-vscode|jos|0.0.9
docomment|k--|1.0.0
vsc-python-indent|Kev|1.18.0
debug-tracker-vscode|mcu|0.0.15
vscode-language-pack-zh-hans|MS-|1.92.2024081409
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.1
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
remote-explorer|ms-|0.4.3
nginx-formatter|ray|0.0.13
LiveServer|rit|5.7.9
even-better-toml|tam|0.19.2
cmake|twx|0.0.17
vscode-nginx|wil|0.7.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717

```

</details>

https://github.com/user-attachments/assets/2292c7f5-ebdf-4bd8-9033-283bee08d182

**Comment by gjsjohnmurray** [comment]
Probably a duplicate of #177046

**Comment by Coloryr** [comment]
yep
