### ISSUE TITLE
Editor loses focus after save, while cargo watch or rust analyzer is running

### ISSUE THREAD

**Issue by yannick818** [microsoft/vscode#225690]
Type: <b>Bug</b>

1. Have a rust project
2. run cargo watch (executes cargo check on save)
3. Edit your code and save
4. After cargo watch finishes the editor loses focus.

This happens also while all extensions are diabled.
I have this issues for a few days now.

See also: (there are some videos)
https://github.com/rust-lang/rust-analyzer/issues/15156
https://github.com/microsoft/vscode/issues/186125

Rust Toolchain:
rustup 1.27.1 (54dd3d00f 2024-04-24)
cargo 1.80.1 (376290515 2024-07-16)
rustc 1.80.1 (3f5fd8dd4 2024-08-06)

happened also with 1.80.0

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.64GB (42.11GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 7f0473cf-ef74-4a64-aa09-14a7dedcc192|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718

```

</details>

**Comment by yannick818** [comment]
I updated VSCode und it still happens

**Comment by toxfu** [comment]
I also have the same problem and it doesn't only happen in rust, I have autosave enabled and it happens randomly with jupyter.

**Comment by roblourens** [comment]
Sorry for the slow response. Since the whole window is losing focus, I would think that some other window is stealing focus. It seems like all the videos are on windows, and it seems linked to saving the file when there are errors. My best guess would be that rust-analyzer or something else is spawning a cmd.exe process which steals focus then immediately completes.

The best thing to do would be to look at what cargo watch is doing, try to simplify or eliminate pieces to narrow it down, or maybe there's a windows log or another tool you can use to figure out which window focus went to when vscode lost it.
