### ISSUE TITLE
typescript.tsserver.nodePath launches duplicate processes

### ISSUE THREAD

**Issue by oriooctopus** [microsoft/vscode#225608]
![Screenshot 2024-08-14 at 10 51 08 AM](https://github.com/user-attachments/assets/93eafce1-a11a-4c6c-a68d-0c6821f282dc)
This happens with all extensions disabled. The duplicate processes is acceptable for a small project, but in our huge one it means two processes that are 9gb each!!

Type: <b>Bug</b>

1. Download https://github.com/bitjson/typescript-starter and run `npm install`
2. Add a file called ts-binary.sh with the following contents (change the binary path to your own)
```
#!/bin/bash

# Specify your Node.js binary path if using nvm or a custom installation
NODE_BINARY="/Users/Oliver.Ullman/.nvm/versions/node/v16.14.2/bin/node"

# Run the ts server with specified memory limit
# Execute the TypeScript server with increased memory
exec $NODE_BINARY --title="custom-tsserver"

```
3. Make the file runnable with `chmod +x <path-to-ts-binary.sh>`
4. Modify the vscode `typescript.tsserver.nodePath` setting to be the absolute path of the ts-binary.sh file
5. Restart vscode and open up a typescript file
6. Open activity monitor, type in "custom-tsserver" and you should see two processes

VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 7, 8|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id b95d53ac-1b0f-4c5e-9093-5f213b352008|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.3
prettier-vscode|esb|10.4.0
vscode-jest-runner|fir|0.4.73
copilot|Git|1.222.0
copilot-chat|Git|0.18.1
toggle|reb|0.0.2
multi-command|ryu|1.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-t:31111713

```

</details>

**Comment by mjbvz** [comment]
This sounds expected. Since TS is synchronous, we run two different servers: a fast one for basic syntax operations and a full one that handles full IntelliSense

**Comment by mjbvz** [comment]
Also if you're using a shell script instead of the path to node directly, make sure to forward all of the arguments to node. That's likely why you see both processes using the full 9gb

**Comment by oriooctopus** [comment]
> This sounds expected. Since TS is synchronous, we run two different servers: a fast one for basic syntax operations and a full one that handles full IntelliSense

@mjbvz is it expected that they take up the same amount of memory?

> Also if you're using a shell script instead of the path to node directly, make sure to forward all of the arguments to node. That's likely why you see both processes using the full 9gb

Got it, thanks for the tip
