### ISSUE TITLE
ESM: impact on monaco standalone editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#225688]
It seems that merging the worker related stuff we did in `alex/esm` to `main` in https://github.com/microsoft/vscode/pull/225672 has an impact on Monaco standalone editor because we ship a monaco ESM build and the worker stuff has changed for ESM. We seem to be building monaco as ESM respecting our ESM related comment/uncomment trick.

I had to push a few tweaks to get the monaco GH action to run green but feel its maybe something to revisit when we create a new release because I am uncertain if these are breaking changes.

**Summary of changes:**
* `tsconfig.json` sets `module: es2022` (was `module: es6`) to prevent this error [1]: [link](https://github.com/microsoft/vscode/pull/225672/files#diff-f80d60d0cf7f4b36ec858ec4c32bacc179a8a3b073dd3cc894427f137f6d8806R160)
* `core.html` that is used for running tests, now requires to have a `globalThis._VSCODE_FILE_ROOT` defined because we need it in ESM: [link](https://github.com/microsoft/vscode/pull/225672/files?file-filters%5B%5D=.html&file-filters%5B%5D=.js&show-viewed-files=true#diff-46534cfc3e1d1ca85284912a9527d0adbfdb46fc0e8cf069b1fe6b7d747b7dbcR8-R10)

[1] 
```
vs/base/common/worker/simpleWorker.ts(539,11): error TS1323: Dynamic imports are only supported when the '--module' flag is set to 'es2020', 'es2022', 'esnext', 'commonjs', 'amd', 'system', 'umd', 'node16', or 'nodenext'.
vs/editor/common/services/editorSimpleWorker.ts(695,5): error TS1323: Dynamic imports are only supported when the '--module' flag is set to 'es2020', 'es2022', 'esnext', 'commonjs', 'amd', 'system', 'umd', 'node16', or 'nodenext'.
```

//cc @hediet @aiday-mar

**Comment by alexdima** [comment]
I think this is complete via https://github.com/microsoft/vscode/pull/225796
