### ISSUE TITLE
Backticks inserted at cursor location when opening new terminal

### ISSUE THREAD

**Issue by wbj** [microsoft/vscode#225616]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.1
- OS Version: macOS Sanoma 14.6.1 (23G93)
- Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

Steps to Reproduce:

1. open new text file
2. type some text: "this is a test"
3. leave cursor at end of sample text
4. open terminal using key chord "control - option - backtick"
5. observe backtick has been inserted at cursor location: "this is a test`"

**Comment by meganrogge** [comment]
seems like your keybinding is not working as expected. i'd suggest using `workbench.action.toggleKeybindingsLog` to figure out what's happening when you use that keybinding
