### ISSUE TITLE
window terminated unexpectedly

### ISSUE THREAD

**Issue by TinaY14** [microsoft/vscode#225641]
Type: <b>Performance Issue</b>

This happens everytime when i try to plot a model, after 10 mins it will show the same error and shut down. error: the wondow terminated unexpectedly, reason clean exit,code0)

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Linux x64 6.8.0-40-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900H (20 x 3397)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|93.92GB (87.73GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id a03c8a08-aa6a-47e8-ad16-d90fd00d98b8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    96	 35028	code main
    0	     0	 35030	   zygote
    0	     0	 35031	   zygote
    0	   192	 35097	window [1] (squid_deepstarr_additive_example.ipynb - koolab - Visual Studio Code)
    0	    96	 35210	     window
    0	    96	 37161	window [2] (Issue Reporter)
    0	     0	 35078	   utility-network-service
    0	    96	 35138	   gpu-process
    0	   192	 35194	extensionHost [1]
    0	     0	 35220	     /home/koolab/.vscode/extensions/ms-python.python-2024.12.3-linux-x64/python-env-tools/bin/pet server
    0	   385	 35625	     electron-nodejs (bundle.js )
    0	     0	 35879	     electron-nodejs (MFqVMFJVTXPQ.js )
    0	     0	 35894	     electron-nodejs (ILYArti.js )
    0	    96	 35365	shared-process
    0	     0	 37175	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 35366	fileWatcher [1]
    0	     0	 35388	ptyHost
    0	     0	 35424	     /usr/bin/bash --init-file /snap/code/166/usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 35825	     /usr/bin/bash --init-file /snap/code/166/usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (squid_deepstarr_additive_example.ipynb - koolab - Visual Studio Code)
|    Folder (koolab): more than 20715 files
|      File types: pyi(5232) png(1243) code(792) py(773) body(602) json(578)
|                  log(299) ipynb(246) sh(203) yaml(194)
|      Conf files: package.json(4) settings.json(2) makefile(2) dockerfile(1);
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31111713

```

</details>

**Comment by aiday-mar** [comment]
Hi when you say you are plotting a model, what exactly are you doing? Could you describe in more detail, and maybe include a screen recording?
