### ISSUE TITLE
ERR InstantiationService has been disposed

### ISSUE THREAD

**Issue by jacob-lineberry-cms** [microsoft/vscode#225607]
Type: <b>Bug</b>

Updated to the latest version of VSCode in windows
Used Ctrl+` to open the terminal and it disappears
Looking at the console logs from the developer tools I see:
  ERR InstantiationService has been disposed: Error: InstantiationService has been disposed
    at g.m (vscode-file://vscode-app/c:/Users/JacobLineberry-C/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:655:386)
    at g.createInstance (vscode-file://vscode-app/c:/Users/JacobLineberry-C/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:655:944)
    at Ue.Wc (vscode-file://vscode-app/c:/Users/JacobLineberry-C/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2633:57059) 

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.72GB (5.40GB free)|
|Process Argv|--crash-reporter-id 8917568d-a9bf-4a38-b21e-8734a0978a45|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
turbo-console-log|Cha|2.10.4
gitignore|cod|0.9.0
githistory|don|0.6.20
gitlens|eam|15.2.3
prettier-vscode|esb|10.4.0
openssl-configuration-file|gee|0.0.1
vscode-git-tags|how|1.4.4
har-analyzer|Mat|0.0.11
git-graph|mhu|1.30.0
vscode-rapidapi-client|Rap|1.10.2
vscode-services|rap|1.0.2
git-merger|sha|0.4.1
git-autoconfig|shy|0.0.2
git-essentials|Tec|0.3.0
branch-warnings|tel|1.0.10
gitblame|wad|11.0.1
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718

```

</details>

**Comment by jacob-lineberry-cms** [comment]
Looks related to: https://github.com/microsoft/vscode/issues/224803 and https://github.com/microsoft/vscode/pull/224869

**Comment by jacob-lineberry-cms** [comment]
Same problem after disabling all extensions and reloading.

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? Let us know if not.
