### ISSUE TITLE
Log snippet

### ISSUE THREAD

**Issue by mustafa-celiktas** [microsoft/vscode#225669]
Type: <b>Feature Request</b>

Why did you put \n after console.log(); when we use log snippet? It's going to a new line for literally no puspose and messing up my code. Please remove it. Thank you.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by gjsjohnmurray** [comment]
Changing a built-in snippet is likely to be unpopular. I suggest you create your own to meet your exact needs.

https://code.visualstudio.com/docs/editor/userdefinedsnippets
