### ISSUE TITLE
Python PIP doesn't install matplotlib

### ISSUE THREAD

**Issue by samskg** [microsoft/vscode#225668]
Type: <b>Bug</b>

This is really frustrating. Trying to install matplotlib with pip and not working. I need to look for some other option as CScode is crap.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.69GB (10.21GB free)|
|Process Argv|--crash-reporter-id cdbe2fb6-c3c9-4ad0-84e0-c8a363d3627b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
arepl|alm|2.0.5
vscode-django|bat|1.15.0
gitignore|cod|0.9.0
python-snippets|cst|0.1.2
vscode-dash|dee|2.4.0
python-extensions-pack|dem|1.0.3
python-preview|don|0.0.4
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|15.2.3
vscode-test-explorer|hbe|2.21.1
python-resource-monitor|kai|0.2.3
vsc-python-indent|Kev|1.18.0
vscode-python-test-adapter|lit|0.8.2
rainbow-csv|mec|3.12.0
document|min|2.2.2
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.380.0
notepadplusplus-keybindings|ms-|1.0.7
powershell|ms-|2024.2.2
test-adapter-converter|ms-|0.1.9
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
indent-rainbow|ode|8.3.1
r-debugger|RDe|0.5.4
r|REd|2.8.4
sourcery|sou|1.22.0
code-spell-checker|str|3.0.1
vscode-djaneiro|the|1.4.2
wolf|tra|0.4.3
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
JavaScriptSnippets|xab|1.8.0
livecode|xir|1.3.10
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718

```

</details>

**Comment by gjsjohnmurray** [comment]
> not working

/needsMoreInfo
