### ISSUE TITLE
Extensions: Expose version of VS Code

### ISSUE THREAD

**Issue by jeffyoung** [Microsoft/vscode#22562]
My extension sends telemetry via Application Insights and it'd be great to have access to the version of VS Code used with the extension.  I found how VS Code [gets that version ](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/menus.ts#L1109)for the Help | About dialog, but it doesn’t appear to be exposed to extensions (e.g., via env or ExtensionContext

- VSCode Version: 1.10.1
- OS Version: Win10

**Comment by jrieken** [comment]
tata: [`vscode.version`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L11)
