### ISSUE TITLE
YAML language syntax highlighting: YAML 1.2 support

### ISSUE THREAD

**Issue by Ned-Stevenson** [microsoft/vscode#225642]
YAML syntax highlighting does not conform to YAML 1.2, e.g., by highlighting fields with value "ON" as Boolean, not string. 
An additional language setting to allow for configuration of YAML version used for syntax highlighting should be introduced.

![image](https://github.com/user-attachments/assets/e7b0d6b8-12d8-457f-ad61-5e4e3d0e9917)
https://yaml.org/spec/1.2.2/

**Comment by RedCMD** [comment]
you can install my [extension](https://marketplace.visualstudio.com/items?itemName=RedCMD.yaml-syntax) if you like

it will become VSCode's new [grammar](https://github.com/microsoft/vscode/issues/180523) once we fix all the integration [issues](https://github.com/microsoft/vscode/issues/224978)

**Comment by Ned-Stevenson** [comment]
Appreciate the fast response. I had a look for other issues about this but somehow missed the one you linked. Very happy with your extension for as long as it's needed.
