### ISSUE TITLE
Testing: Clearing all results should still remember last test

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#225697]
Repro:

1. Run a failing unit test
2. Click clear all results
    ![image](https://github.com/user-attachments/assets/82d602ae-4d5d-45a1-8c3e-869d3a07a571)
3. Press ctrl+;, ctrl+l, 🐛 nothing happens as the last unit test is no longer tracked. I expected this to work despite clearing the results. I was only clearing to remove the 20+ old runs that I no longer wanted cluttering things

**Comment by connor4312** [comment]
Clearing all results is designed to reset the state of all tests.

Were the historical runs causing issues aside from the "older runs" item in history view? We're considering just hiding that in the future, depending on telemetry on how many users actually interact with tht.

**Comment by Tyriar** [comment]
Nope it was just clutter.

**Comment by connor4312** [comment]
I'm not a big fan of this, I think clearing results _should_ clear everything and I'm not sure a "clear all N-1 older results" is a very popular command worth adding
