### ISSUE TITLE
Allow MarkdownString.isTrusted for chat participants

### ISSUE THREAD

**Issue by alenakhineika** [microsoft/vscode#225609]
Currently, there is no way to return a markdown with the chat participant response that calls extension commands on click.

The `ChatResponseStream.markdown(value: string | MarkdownString): void` accepts the MarkdownString as an argument, but doesn't allow to set `isTrusted` to enable links that execute commands, e.g. `[Run it](command:myCommandId)`:

`Err: The boolean form of MarkdownString.isTrusted is NOT supported for chat participants.`

<img width="477" alt="list" src="https://github.com/user-attachments/assets/0596657e-cf79-4485-8ad6-28884c450754">

**Comment by alenakhineika** [comment]
cc @isidorn

**Comment by isidorn** [comment]
Good issue - thanks Alena.

@roblourens I thought you mentioned we supported trusted Markdown for chat participants. I might have misunderstood you.

**Comment by roblourens** [comment]
The boolean form is not supported. The non-boolean type (`enabledCommands`) works :)
