### ISSUE TITLE
Hover shows undefined while debugging

### ISSUE THREAD

**Issue by Alexios11** [microsoft/vscode#225618]
Type: <b>Bug</b>

Debug an angular project and place a breakpoint within an async function. Once execution stops at the breakpoint hover over any local variable within that async function. The tooltip shows undefined. This happens in version 1.91. I downgraded back to 1.90 and it works fine again.

If I place that variable in the watch window, its value shows properly. If I console.log() that variable I also see the proper value. This seems to only be an issue in async functions.

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (6.46GB free)|
|Process Argv|--crash-reporter-id 47d6066f-9eba-44c4-aaac-4a576619c640|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
Lua|key|0.0.9
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-t:31111713

```

</details>

**Comment by connor4312** [comment]
Please update your VS Code version to get the fix.

**Comment by Alexios11** [comment]
> Please update your VS Code version to get the fix.

The latest version (1.92.1) is the one having this issue. As I mentioned in my original post I had to downgrade to a version that does not have this issue and that's why the version in my report says "1.90.2", it was added automatically by the reporter. The downgraded version is just the one I used when I clicked on the Report Issue item in the Help Menu. In 1.90.2 it works fine.

PS: You marked this as duplicate, can I have a link to the duplicate report ?

Thanks!

**Comment by connor4312** [comment]
Could you grab a log file?

/jsDebugLogs

**Comment by Alexios11** [comment]
I don't know how to do that or where to put this "/jsDebugLogs" you mentioned.
I added "trace": true as the bot suggested but didn't get any report in the Debug Console.
I see some log files under AppData\Roaming\Code\logs but they don't contain much, plus there are older folders in there as well which suggests that adding "trace": true just now is not what caused them to be created.

The way I am debugging is by using "request": "attach", "type": "chrome" in my launch.json, then I place a breakpoint and hit "Start Debugging". The application is being run in CEF. When the breakpoint is reached I just hover over any local variable and see "undefined" in the tooltip. To stop the process I just ctrl+c in the terminal. Not sure at which point during this process and how I can get a log of that.

PS: Some additional info: I tested 1.91 as well and looks like that this is where the issue started. In the release notes I see that there were some changes to the Javascript debugger and the functionality when hovering over a variable which seems very suspicious in causing this.

**Comment by connor4312** [comment]
@andyfisher100 please collect a log file using the above instructions, thanks!

**Comment by ennovative-pl** [comment]
I also have this issue. Extremely annoying while debugging some errors in tight deadlines... 1.91 here

**Comment by connor4312** [comment]
@ennovative-pl please collect a log file using the above instructions, thanks!

**Comment by Alexios11** [comment]
@connor4312 Can you provide some help on how to create a log file for such an issue ?

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/225618#issuecomment-2289771246

**Comment by Alexios11** [comment]
@connor4312 
Well, I don't. All I see in the debug log is the message that comes from the angular project which is "Angular is running in the development mode. Call enableProdMode() to enable the production mode."

- I launch using "npm run start"
- I start debugging by hitting F5
- I set a breakpoint in the code where I can see the issue
- Execution stops at the breakpoint and I see the issue
- I hit F5 again to resume execution
- I press Ctrl+C in the terminal to shutdown

At no point during this process I get any other message in the Debug Console. 
There must some other pre-requisite for this to work. What is this "preview" debug extension I see in you log ? Maybe I need that extension for this to work ?

**Comment by satheesh-anecure** [comment]
same with me in the recent build, variables are showing undefined while hovering, but shows up the correct value in variables panel

**Comment by connor4312** [comment]
@satheesh-anecure please collect a log file using the above instructions, thanks!

---

> All I see in the debug log is the message that comes from the angular project which is "Angular is running in the development mode. 

What does your launch.json look like?

**Comment by ayortanli** [comment]
Hey @connor4312 
Having the same issue with 1.92.2. I've sent log file to [connor@xbox.com](mailto:connor@xbox.com)

**Comment by connor4312** [comment]
Much appreciated! Your issue should be solved on the nightly extension: https://github.com/microsoft/vscode-js-debug?tab=readme-ov-file#nightly-extension

Please let me know if not
