### ISSUE TITLE
switching automatically to rebase issue

### ISSUE THREAD

**Issue by LYROS-MUSTINISURENDRA** [microsoft/vscode#225689]
Type: <b>Bug</b>

switching automatically to rebase issue

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.26120
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz (4 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.65GB (3.03GB free)|
|Process Argv|--crash-reporter-id 896b45b1-1dc3-4ab5-9692-31cd849bc772|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
python-environment-manager|don|1.2.4
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|11.0.0
remotehub|Git|0.62.0
vsc-python-indent|Kev|1.18.0
vscode-docker|ms-|1.29.2
debugpy|ms-|2024.11.2024081401
python|ms-|2024.13.2024081501
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.2
azure-repos|ms-|0.38.0
remote-repositories|ms-|0.40.0
autodocstring|njp|0.6.1
material-icon-theme|PKi|5.9.0
vscode-rapidapi-client|Rap|1.10.2
vscode-services|rap|1.0.2
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
open-in-browser|tec|2.0.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
jinja|who|0.0.8
classnametocss|zit|0.0.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-c:31111712

```

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo Please provide a more detailed description of the bug you are seeing.
