### ISSUE TITLE
Formatting is not triggered when using auto save `afterDelay`

### ISSUE THREAD

**Issue by cc20041218** [microsoft/vscode#225661]
Diagnostic data

- Python version (& distribution (if applicable), such as Anaconda): 3.12.3

- The type of virtual environment used (such as conda, venv, virtualenv, etc.): venv

- Operating system (and version): macOS Ventura 13.6.7

- Expanded version of the tool you are using: v2024.3.12071014 (pre-release)

When "File: Auto Save" is set to "afterDelay" in VSC, it cannot be formatted. If it is set to another option or saves manually, there is no problem. After checking the log of the black formatter, there are only some prompts. I want to know how to make it work when it is set to delay saving.

This is my configuration.
```json
"[python]": {
"editor.defaultFormatter": "ms-python.black-formatter",
"editor.formatOnSave"：true
}，
```

**Comment by cc20041218** [comment]
> 此扩展仅注册格式化程序。格式化触发器由VS代码处理。这里的`afterDelay`行为来自vscode。

Thank you

**Comment by gjsjohnmurray** [comment]
Maybe related to https://github.com/microsoft/vscode/issues/213691#issuecomment-2135592457
