### ISSUE TITLE
Make VS Code Icon more attractive by adding transparent center

### ISSUE THREAD

**Issue by dustinwinski** [Microsoft/vscode#22566]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:

1. Center of VS Icon on the taskbar and live tile has white center
Make the icon more like the one I submitted.
![vso](https://cloud.githubusercontent.com/assets/17513036/23878893/58f17192-0820-11e7-9a0f-b7f89d435a6f.png)

**Comment by hoovercj** [comment]
Duplicate of #11274

**Comment by chrisdias** [comment]
Closing all icon issues against https://github.com/Microsoft/vscode/issues/6607
