### ISSUE TITLE
Terminal inline chat has big padding on bottom that sticks around

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#225612]
![image](https://github.com/user-attachments/assets/b8a8daf3-9622-4a7e-9ddb-8781f2d04d2e)

![image](https://github.com/user-attachments/assets/4db50853-55b3-42a7-af58-0634696e6fca)

**Comment by Tyriar** [comment]
I think they always show buttons now? Unless I have some setting

![image](https://github.com/user-attachments/assets/92436191-5c82-4fc4-9caf-e4a9132cc5df)

**Comment by meganrogge** [comment]
Cannot reproduce, think @Tyriar fixed this
