### ISSUE TITLE
Complete screen is fuzzy and only able to view the part that has my cursor over

### ISSUE THREAD

**Issue by akshatbansal218** [microsoft/vscode#225698]
Type: <b>Bug</b>

After recent update it has made vscode unable to be used as the complete screen has gone fuzzy and now it is unable to code only part my cursor is over is being highlighted rest is unreadable. 
Current Version: 1.92.1 (user setup)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.67GB (1.70GB free)|
|Process Argv|--crash-reporter-id 7b0b32cd-4d7a-449d-a7a2-ccc436e0188e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
nodejs-bundle|1Yi|1.0.0
svelte-bundle|1Yi|1.0.0
svelte-intellisense|ard|0.7.1
rc-beautify|Ato|1.2.0
blackbox|Bla|1.3.73
npm-intellisense|chr|1.4.5
apex-pmd|chu|0.7.0
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
lana|Fin|1.16.0
vscode-svelte-snippets|fiv|0.5.0
auto-rename-tag|for|0.1.10
svg|joc|1.5.4
start-git-bash|McC|1.2.1
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
vscode-react-native|msj|1.13.0
vscode-xml|red|0.27.1
vs-code-prettier-eslint|rve|6.0.0
salesforce-vscode-slds|sal|1.4.10
salesforcedx-einstein-gpt|sal|0.56.0
salesforcedx-vscode|sal|61.8.1
salesforcedx-vscode-apex|sal|61.8.1
salesforcedx-vscode-apex-debugger|sal|61.8.1
salesforcedx-vscode-apex-replay-debugger|sal|61.8.1
salesforcedx-vscode-core|sal|61.8.1
salesforcedx-vscode-expanded|sal|61.8.1
salesforcedx-vscode-lightning|sal|61.8.1
salesforcedx-vscode-lwc|sal|61.8.1
salesforcedx-vscode-soql|sal|61.8.1
salesforcedx-vscode-visualforce|sal|61.8.1
sfdx-code-analyzer-vscode|sal|1.0.0
vscode-standard|sta|2.1.3
svelte-vscode|sve|108.6.0
vscode-import-cost|wix|3.3.0
vscode-surround|yat|1.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717

```

</details>

**Comment by gjsjohnmurray** [comment]
Please see the suggestion at https://github.com/microsoft/vscode/issues/225564#issuecomment-2287957973

If it works you can use information later in that issue to apply the setting persistently.
