### ISSUE TITLE
Code Swing not working properly on new version on VSCode

### ISSUE THREAD

**Issue by modulardata** [microsoft/vscode#225677]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Latest version
2. Code Swing not showing preview

**Comment by gjsjohnmurray** [comment]
/causedByExtension

The extension author needs to investigate this. If they think it is caused by a VS Code regression they are best placed to raise it here.
