### ISSUE TITLE
Source Control goes slow.

### ISSUE THREAD

**Issue by MarinBelmont29** [microsoft/vscode#225644]
The resource control, when the incoming/outgoing feature was added, is now loading more than 200,000 commits in terms of commit and branch visualization. This makes Visual Studio unusable for me. To avoid this, I have to keep cloning my project frequently and adding my branches to Git. It's extremely inconvenient, and even restarting my PC doesn't help. This all started when that feature was added... errors never load, source control just stays loading with a little clock, and the extensions function gets stuck...

Please do something about that branch visualization in incoming/outgoing...

**Comment by gjsjohnmurray** [comment]
/duplicate re poor performance when a large number of commits are found.

Workaround is to toggle the `scm.showHistoryGraph` setting.
