### ISSUE TITLE
Terminal shell integration scripts should be in `common`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#225665]
Because they are added to the server build:

https://github.com/microsoft/vscode/blob/27f650ea2366a6b99b4727b2bec9731904d52ac5/build/gulpfile.reh.js#L67-L75

**Comment by Tyriar** [comment]
FYI @andyleejordan the shell integration script path will be changing in 1.94

**Comment by Tyriar** [comment]
This failed the build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=290812&view=logs&j=6a0bd816-257e-5ecc-41db-d193a9989793&t=43195df5-dc26-59c2-2561-baa382a3ffe0
