### ISSUE TITLE
Terminal suggest: `git co -` should be a completion

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#225784]
Top entry here should be `-` which means the last checked out branch:

![image](https://github.com/user-attachments/assets/564c520a-eb2f-4fc5-b0de-459a8a5ff2b9)

**Comment by joyceerhl** [comment]
There was a ~1-2 second delay between typing the space after `-` and the suggest widget actually showing up. Is that a known issue?

**Comment by Tyriar** [comment]
Yes that's tracked in another issue.
