### ISSUE TITLE
Turn on `editor.experimental.asyncTokenization` by default

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#225794]

**Comment by hediet** [comment]
[The experiment](https://exp.microsoft.com/a/feature/229db5b0-4e1e-4aea-9bd7-eba106e4c1b7?workspaceId=dbd12384-5001-4e90-a863-526321eaf233&group=/vscodeexpws) still needs to be deleted after the setting default value got deployed.

**Comment by hediet** [comment]
Reopening, as the experiment still needs to be deleted.
