### ISSUE TITLE
autoSave can't run on macOS

### ISSUE THREAD

**Issue by lei40251** [Microsoft/vscode#22578]
- VSCode Version:1.10.2 (1.10.2)
- OS Version:macOS Sierra 10.12 (16A323)

Steps to Reproduce:

1.file>autoSave
2.edit any file
3.
![35](https://cloud.githubusercontent.com/assets/648155/23885197/9b5a10d4-08ac-11e7-998e-87efcfff38d9.png)

**Comment by weinand** [comment]
@lei40251 do you know why you don't have access to the file shown in the error message?

**Comment by lei40251** [comment]
开启自动保存后，编辑文件然后自动保存就提示这个了。

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by Pyrolistical** [comment]
ya its fixed on insider build, but would love insider build to use my config by default

**Comment by bpasero** [comment]
@Pyrolistical you can copy the settings over, it should just work?
