### ISSUE TITLE
Crashes and UI Glitches When Deleting a File Added to Git Repository

### ISSUE THREAD

**Issue by CNenfan** [microsoft/vscode#225787]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.20
- OS Version: Windows 10

## Summary:
When I create a file in Visual Studio Code (VSCode), add it to the Git repository, and then manually delete it from the file system, VSCode crashes while trying to access the deleted file. Additionally, the code identifier (which shows how many times a function is referenced) exhibits UI flickering.

## Steps to Reproduce:
1. Create a new C# file (e.g., `MessageSystemSetting.cs`) in VSCode.
2. Commit the changes to the Git repository.
3. Manually delete the file from the file system.
4. Attempt to view or open the deleted file in the Git panel of VSCode.

## Expected Behavior:
VSCode should gracefully handle the situation where a file has been deleted from the file system and not crash or display error messages.

## Actual Behavior:
- Error messages appear stating "Server was requested to shut down." with error code `-32000`.
- The `Microsoft.CodeAnalysis.LanguageServer` server crashes multiple times (five times within three minutes) and does not restart.
- The code identifier displays UI flickering issues.

## Screenshots / Logs:

![image](https://github.com/user-attachments/assets/b6955de0-071a-44d6-bb6a-bcaa8a7061b8)
```log
[Error - 20:52:20] Document pull failed for text document file:///d%3A/Users/%E6%81%A9%E5%87%A1/Unity/Unity%20Program/RF-Memories%20from%20FurCafe/Assets/Main/UI/StorylineInterface/MessageSystem/MessageBox/Keycode/MessageSystemSetting.cs
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 20:52:20] Request textDocument/diagnostic failed.
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 20:52:20] Document pull failed for text document file:///d%3A/Users/%E6%81%A9%E5%87%A1/Unity/Unity%20Program/RF-Memories%20from%20FurCafe/Assets/Main/UI/StorylineInterface/MessageSystem/MessageBox/Keycode/MessageSystemSetting.cs
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 20:52:20] The Microsoft.CodeAnalysis.LanguageServer server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

Thanks!
If my question is a repeat, I'm very sorry. ：}

**Comment by codebyanas** [comment]
Bro can you please the name of this theme?

**Comment by CNenfan** [comment]
> Bro can you please tell me the name of this theme?

Default Dark Moderm
I use the font "荆南麦圆体"

**Comment by CNenfan** [comment]
> Bro can you please tell me the name of this theme?

if you like i can provide you the font asset

**Comment by codebyanas** [comment]
There is no theme with this name "Default Dark Moderm"
![Screenshot (291)](https://github.com/user-attachments/assets/2dd23241-7779-4383-aadb-b0bc12fae1e5)

**Comment by CNenfan** [comment]
> There is no theme with this name "Default Dark Moderm" ![Screenshot (291)](https://private-user-images.githubusercontent.com/155805881/358624883-2dd23241-7779-4383-aadb-b0bc12fae1e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MjA3NDMsIm5iZiI6MTcyMzgyMDQ0MywicGF0aCI6Ii8xNTU4MDU4ODEvMzU4NjI0ODgzLTJkZDIzMjQxLTc3NzktNDM4My1hYWRiLWIwYmMxMmZhZTFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQxNTAwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzE0NmJjMzE4NjQ4OTUwMTVhN2MzZGNhNzlmY2Q0OTM5NmY3NjQyOGNjNjdmOTJjNmZlODNhYmUzZTI5ODY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xtt8NZOT4avfAyoEyH07m_kZccD5fqDzwuoOPRhJ3Ss)

![image](https://github.com/user-attachments/assets/48b1eea3-08c7-4fd3-8c82-7a884e8bd753)
![image](https://github.com/user-attachments/assets/6f37fa99-7a96-4bc4-ad75-4a9e0cb8eb70)

**Comment by CNenfan** [comment]
> There is no theme with this name "Default Dark Moderm" ![Screenshot (291)](https://private-user-images.githubusercontent.com/155805881/358624883-2dd23241-7779-4383-aadb-b0bc12fae1e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MjExMzAsIm5iZiI6MTcyMzgyMDgzMCwicGF0aCI6Ii8xNTU4MDU4ODEvMzU4NjI0ODgzLTJkZDIzMjQxLTc3NzktNDM4My1hYWRiLWIwYmMxMmZhZTFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQxNTA3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2RkZjBlZTM3MWU3MjFiMmM2Njk5ZGFiNWIwYmE1MTdlZWEyMWUxODAzYzIwOTUyN2RjNjFhYzczMmYyODIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BNfv5TjXE276cWVheKD-acxOw1yPfnT72ZybRdipOzo)

Here is not the place to talk about the "theme" of vscode.
If you like, you can email me instead of here.
enfan@furcafe.top
