### ISSUE TITLE
Error and suggestion highlighting/underlining disappeared after last update

### ISSUE THREAD

**Issue by schugh** [Microsoft/vscode#22570]
- VSCode Version: 1.10.2
- OS Version: OSX Sierra 10.12.3

Steps to Reproduce:

1. Open any file with installed linter extensions: go + golint/gometalinter, javascript + jshint/eslint 
2. Not consistently showing error (red) or suggestion (green) underlining in source code.  Sometimes the session's work just as normal sometimes it stops highlighting. Intelli-sense works consistently.

Started happening yesterday after an update. I deleted VSCode and all extensions and reinstalled. Confident that no settings changed in my workspace/project.

**Comment by weinand** [comment]
@schugh what type of file shows this problem? I don't believe you that the problem occurs with "any file".

**Comment by ramya-rao-a** [comment]
@schugh In case of Go files, the Go extension shows the error/suggestions only on saving the file. Therefore, if you are just typing, they will not be updated. Is that the case?

**Comment by schugh** [comment]
I've been working with go source this week so yes, I've noticed this
'mostly' with go. Yesterday when I ran into it, i launched a javascript
project and saw that the highlighting wasn't working there either.

I did notice that the validating/linting is happening upon save; each time
I run into this, saving doesn't make a difference.  My assumption initially
was that it was the go extension that might be faulty but the the fact I
ran into it with that the behavior was replicated for a javascript project
is what led me to report the issue.

**Comment by schugh** [comment]
** the fact I ran into it with the behavior for a javascript project is
what led me to report the issue.

**Comment by dlong500** [comment]
Not sure if it has any relation to this (as I'm using Windows and the insiders build), but I've noticed over the past week or so in the insiders builds that eslint will stop working randomly (whatever suggestions/errors it was showing will get "stuck" no matter what you change in the code).

Invariably when this happens I can close the editor and there will be several "Code - Insiders.exe" zombie processes that won't close on their own.  If I kill them and restart vscode then everything is back to normal until the next incident (which could be minutes or hours later).

Not sure if this is a vscode issue or a plugin issue or both.  It is still happening today on the latest insiders build.

**Comment by schugh** [comment]
@dlong500 Your experience pretty accurately describes what I'm seeing for my go projects. I haven't looked to see if there's equivalent process (to Insiders.exe) that's getting spawned and abandoned. I'll look out for it

**Comment by ericfr** [comment]
I am seeing something similar when using Typescript. I can run a "Task" which will give a list of errors (mostly unused variables). when I click on the error in the 'Problems' tab, the file comes up in the editor view, but the error is not highlighted in the source code, and it disappears from the 'Problem' tab, even though I do not change anything.

**Comment by mjbvz** [comment]
Hey sorry I missed that this was assigned to me. If you are still seeing this issue in VSCode 1.16 while working with JavaScript or TypeScript code please let me know
