### ISSUE TITLE
ı cant log in my workspace

### ISSUE THREAD

**Issue by omhuner** [microsoft/vscode#225716]
Workbench sunucuya bağlanamadı (Hata: exception was thrown by handler. exception: failed to start vs code remote server.)
Version: 1.92.1
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by joshspicer** [comment]
I'm afraid we need a bit more information here in order to help troubleshoot.

It appears you're using codespaces, is that the case?  Is this issue continuing to reproduce? Does it re-produce across different repos? Are you using a custom `devcontainer.json` configuration on the repo(s) where the issue repros?

This may be a question better suited for GitHub support, although with the info above I may be able to provide some guidance - thanks!

**Comment by omhuner** [comment]
First of all, thank you for reaching out to me.
I have temporarily resolved my issue, but it reappears from time to time. Let me explain to inform you: I use the Codespace platform for coding online, and sometimes when I don't check it for a long time, it stops, and I receive a 'Codespace restart' warning. I then restart it, but sometimes when I don't check it for a long time or after restarting it multiple times, it doesn't load at all, and I receive a warning that I cannot view my files. As a solution, I either restart my computer or try accessing it again after a long break, and it usually gets fixed. The container I'm using is the CS50 library
________________________________
Gönderen: Josh Spicer ***@***.***>
Gönderildi: 16 Ağustos 2024 Cuma 22:04
Kime: microsoft/vscode ***@***.***>
Bilgi: Ömer Hüner ***@***.***>; Author ***@***.***>
Konu: Re: [microsoft/vscode] ı cant log in my workspace (Issue #225716)


I'm afraid we need a bit more information here in order to help troubleshoot.

It appears you're using codespaces, is that the case? Is this issue continuing to reproduce? Does it re-produce across different repos? Are you using a custom devcontainer.json configuration on the repo(s) where the issue repros?

This may be a question better suited for GitHub support, although with the info above I may be able to provide some guidance - thanks!

**Comment by joshspicer** [comment]
For codespace connection issues, i'd suggest reaching out via GitHub support, or if you're enrolled in the CS 50 course to your instructor.
