### ISSUE TITLE
Failed to resolve a save conflict for random files in a workspace

### ISSUE THREAD

**Issue by kirilllzaitsev** [microsoft/vscode#225723]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.92.1
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.5.0-21-generic

When exiting one file I'm working with at the moment and automatically triggering autosave, I receive an error on failing to resolve a conflict when saving, asking to compare the conflicting changes or force an overwrite for 2-3 files that haven't been changed lately at all. For example, two of them:

- one of the files from the error messages

![image](https://github.com/user-attachments/assets/3fa829a9-2263-41d7-b71b-cd509dbe35cc)

- `demo.py`:

![image](https://github.com/user-attachments/assets/288e42cd-674a-4848-b3cc-ce216cdf70d8)

Not sure if that may interfere with VScode operation, but recently I replaced the RAM modules of my laptop. Since I haven't observed this problem before (although the replacement coincided with the VScode update), can it be a consequence of some RAM/hardware problem?

Steps to Reproduce: no particular recipe, just working with some other files.

**Comment by bpasero** [comment]
This indicates that some other process has written to the file while it was changed and unsaved in VS Code. Hard to tell what the cause is.

**Comment by kirilllzaitsev** [comment]
I wasn't able to reproduce this behavior the next day. Reopening on more evidence of the problem
