### ISSUE TITLE
Some LogOutputChannel methods do not work

### ISSUE THREAD

**Issue by v-champion** [microsoft/vscode#225714]
Type: <b>Bug</b>

Using JavaScript, I have done the following:

1. `let channel = vscode.window.createOutputChannel('testChannel', {log: true});`
2. `channel.show();`
3. `channel.info("test message");`
4. `channel.clear();` // does not clear the channel

The expected result should be the output channel clearing. This issue does not happen at all for regular output channels, only for those with "log" set to true. 

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.94GB (11.96GB free)|
|Process Argv|P:\\Development (Roblox)\\Rojo Test\\Rojo SBR test.code-workspace --log nexus interactive.nexus-toolset=trace --log nexus-interactive.nexus-toolset=trace --log v-champion.nexus-sync=trace --crash-reporter-id a2325c1d-201b-4e19-b2e6-7bdd9642a654|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-as3mxml|bow|1.21.1
json-pretty-printer|eus|1.1.0
vscode-rojo|eva|2.1.2
roblox-ui|fil|0.3.2
copilot|Git|1.222.0
copilot-chat|Git|0.18.2
luau-lsp|Joh|1.32.3
nexus-toolset|nex|0.0.5
partial-diff|ryu|1.4.3
vanilla3-icons|v-c|1.4.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe #214048 is related.

**Comment by v-champion** [comment]
missed a step, edited appropriately

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/224516
