### ISSUE TITLE
Invocation of the function let add a b = a + b does not work on debug console

### ISSUE THREAD

**Issue by geraldodev** [Microsoft/vscode#22573]
- VSCode Version: 1.10.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1.create new F# project
2. On the main file paste
let sub (a, b) = a - b
let add a b =
    a + b
3. place a breakpoint debug on the first line of the main and hit start debugging
4. enter (add 2 3) on debug console to be executed on the context which returns
 error CS1026: ) expected

Interestingly when the parameter is constrained by a tuple like on sub it works:
sub (3, 2)
1

Also tested the add function on fsharpi from mono and it worked there.

Thanks for opening such a great language with a very respectable inheritance for non windows users.

Geraldo Lopes de Souza

**Comment by weinand** [comment]
VS Code does not support F# out of the box.
Please file this against the F# specific extension you are using.
