### ISSUE TITLE
升级后，vue文件 无CSS And JS提示

### ISSUE THREAD

**Issue by zhoupeihuang** [Microsoft/vscode#22574]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|compulim-vscode-closetag|Compulim|0.1.2|
|insert-file|crest|0.0.1|
|vscode-eslint|dbaeumer|1.2.7|
|vscode-babel-coloring|dzannotti|0.0.4|
|mithril-emmet|FallenMax|0.6.1|
|auto-rename-tag|formulahendry|0.0.11|
|beautify|HookyQR|1.0.1|
|hopscotch|idleberg|0.1.4|
|autofilename|JerryHong|0.1.3|
|vue|liuji-jim|0.1.5|
|HTMLHint|mkaufman|0.3.3|
|easy-less|mrcrowl|1.3.4|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.3.0|
|code-settings-sync|Shan|2.5.1|
|vscode-typings|typings|0.0.5|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.
2.

**Comment by weinand** [comment]
@zhoupeihuang Please provide an English translation for your issue

**Comment by weinand** [comment]
no response -> closing
