### ISSUE TITLE
VSCode terminal typesetting

### ISSUE THREAD

**Issue by yeaicc** [Microsoft/vscode#22572]
- VSCode Version: Code - Insiders 1.11.0-insider (a3b1076f079c150d921a7b91d91c6783fa04450a, 2017-03-06T07:10:28.191Z)
- OS Version: Windows_NT ia32 10.0.15055
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.7|
|beautify|HookyQR|1.0.1|
|vscode-icons|robertohuertasm|7.3.0|;

---

Steps to Reproduce:

1.Ctrl+`
2.
![image](https://cloud.githubusercontent.com/assets/4646789/23882494/f1399170-089b-11e7-91cb-88cbece9fdd9.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
