### ISSUE TITLE
The find text box in Golang Test Result tab is soooo long

### ISSUE THREAD

**Issue by qiansen1386** [microsoft/vscode#225773]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.92.0 (Universal)
- OS Version: OS: Darwin arm64 23.1.0

Steps to Reproduce:

1. Run a golang test
2. Press cmd/ctrl-F when test result is focus
![image](https://github.com/user-attachments/assets/58a85e74-08ce-408f-995a-0052de62674c)

**Comment by qiansen1386** [comment]
@connor4312  I also speculate it might be caused by an extension. However, how to identify which sub panel is registered by which extension.

**Comment by connor4312** [comment]
https://code.visualstudio.com/blogs/2021/02/16/extension-bisect#_welcome-extension-bisect

**Comment by connor4312** [comment]
Oh, that's in the test results view, hard to see in the first screenshot.

I think this duplicates https://github.com/microsoft/vscode/issues/225460, will tackle it at the same time
