### ISSUE TITLE
VSC not seeing symbols in outline for c language - strange case

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#225789]
Does this issue occur when all extensions are disabled?: Yes/No

VS Code version: Code 1.88.0 (https://github.com/microsoft/vscode/commit/5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.22631

Steps to Reproduce:

There is stupid case with outline that can't be resolved. Can VSC team check what is wrong around?
https://github.com/microsoft/vscode/issues/209982
https://github.com/microsoft/vscode-cpptools/issues/12181

**Comment by jrieken** [comment]
>  Can VSC team check what is wrong around?

We can't because the outline is entirely computed by extensions, not VSC
