### ISSUE TITLE
Add settings with GUI

### ISSUE THREAD

**Issue by Azhe403** [Microsoft/vscode#22576]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Add settings with GUI for VS Code

**Comment by indiejames** [comment]
It seems like it would be fairly easy to develop a dynamic GUI for this given that all the settings have a declared type. This is how Atom settings work.

**Comment by wangweixuan** [comment]
Duplicate of #3355.

**Comment by mjbvz** [comment]
Closing as duplicate of  #3355
