### ISSUE TITLE
debug.autoExpandLazyVariables removed from settings.json everytime vscode is started

### ISSUE THREAD

**Issue by danieltodor** [microsoft/vscode#225756]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version: Archlinux

When i open vscode, or just open a new window, the `debug.autoExpandLazyVariables` line is removed from settings.json.
Currently for me it's `off` (not the default), but even if it was on default, it should not be removed anyway.

Steps to Reproduce:

1. Place this into settings.json: `"debug.autoExpandLazyVariables": "off",`
2. Open a new window with the `New Window` command.

**Comment by ZhouLuquan** [comment]
I have the same problem.
I need to keep `debug.autoExpandLazyVariables` on. However, when I reopen vscode, I lost my configuration.
By the way, I'm not in screen reader mode. I have to set `"editor.accessibilitySupport": "on"` to make variables remain expanded.

Version: 1.93.0-insider (system setup)
Commit: 336db9ece67f682159078ea1b54212de7636d88a
Date: 2024-08-30T18:47:32.318Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by roblourens** [comment]
FYI @meganrogge

**Comment by meganrogge** [comment]
🤦‍♀ thanks for fixing @roblourens

**Comment by koutheir** [comment]
@roblourens, what is the new behavior after the setting is removed?
