### ISSUE TITLE
编辑器上下布局的时候，两组编辑器的代码莫名其妙的交换，请见详情。

### ISSUE THREAD

**Issue by dongrizhixue** [Microsoft/vscode#22571]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|calculate|acarreiro|1.1.0|
|project-manager|alefragnani|0.13.4|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|vscode-markdownlint|DavidAnson|0.7.0|
|javadebugger|donjayamanne|0.0.2|
|java-debug|DSnake|0.0.2|
|javac-linter|faustinoaq|1.2.2|
|url-encode|flesler|1.1.0|
|rest-client|humao|0.12.3|
|guid|kosunix|0.0.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|markdown-shortcuts|mdickin|0.7.1|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.8.0|
|java|redhat|0.0.11|
|vscode-icons|robertohuertasm|7.3.0|
|iis-express|warren-buckley|0.0.6|
|markdown-pdf|yzane|0.1.6|;

---

Steps to Reproduce:

1.编辑器上下布局，在上面双击某个单词。
2.在下面单击某处，上面和下面代码会莫名其妙的互换，毫无规律。

**Comment by rebornix** [comment]
He is saying

1. The editor groups are horizontally split. Double click a word on the editor up most
2. Single click on some random position in the editor group below, the content in the up most editor and the below one are somehow switched.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
