### ISSUE TITLE
The layout in the template will be changed when I saved the Jinja or Django template file

### ISSUE THREAD

**Issue by DennisXie** [Microsoft/vscode#22575]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.16|
|vscode-theme-onedark|akamud|0.2.14|
|theme-atom-one-dark|andischerer|0.0.1|
|python|donjayamanne|0.5.5|
|theme-dracula|dracula-theme|1.2.5|
|theme-atom-one-dark|freebroccolo|0.0.1|
|Theme-Dracula|gerane|0.0.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.1|
|theme-darktooth|Poorchop|0.0.2|
|vscode-icons|robertohuertasm|3.0.1|
|code-settings-sync|Shan|2.3.1|
|vim|vscodevim|0.5.3|
|bootstrap-3-snippets|wcwhitehead|0.0.7|
|JavaScriptSnippets|xabikos|1.2.0|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1.edit a Jinja or django template file
2.ctrl - S to save a file

**Comment by weinand** [comment]
@DennisXie could it be that a formatter kicks in when you are editing a Jinja or Django template file?
Does this problem occur if you run VS Code without any extensions?
From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by DennisXie** [comment]
@weinand Thanks a lot, after I disabled all extensions, this problem didn't occur any more.
