### ISSUE TITLE
Unable to scroll the editor while inline chat is generating code

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#225746]
The code generation was taking a bit long and I attempted to scroll in the editor to view other code, however it kept revealing the new changes.

https://github.com/user-attachments/assets/b4f7726b-e6fa-4bc1-a663-ebc9f0ef37e4

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode-copilot/issues/7338
