### ISSUE TITLE
FR: API to Enumerate Current Color Theme for Extensions

### ISSUE THREAD

**Issue by matttproud** [microsoft/vscode#225753]
I am interested in authoring an extension that would manage aspects of the current color theme in Visual Studio Code (particularly turn off/piecemeal minimize syntax highlighting #225138).  I would like Visual Studio Code to expose an API that allows extensions to enumerate the current color theme's settings similar to what @aeschli mentions in #168190 as `getThemeColors()`.

**Comment by aeschli** [comment]
duplicate of https://github.com/microsoft/vscode/issues/32813
