### ISSUE TITLE
keyboard shortcut to the csdevkit.addProjectReference command.

### ISSUE THREAD

**Issue by Tallyclone** [microsoft/vscode#225764]
Type: <b>Feature Request</b>

When I set the keyboard shortcut to the ' csdevkit. AddProjectReference 'command  , VSCode report always read the properties of undefined 'contextValue (reading); 
I set the json code to  {
"key": "ctrl+shift+f1",
"command": "csdevkit.addProjectReference",
"when": "focusedView == 'solutionExplorer' && selectedSolutionExplorerNodeType == 'Project'"
},
For what reason? 
Whether can   set the keyboard shortcuts  to 'csdevkit. AddProjectReference 'and 'csdevkit. AddNewFile 'commands, etc.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19044
Modes:

**Comment by aeschli** [comment]
Can you get information about the exception?
Can you open the Dev Tools (Command: `Developer: Toggle Developer Tools`) and go to the Console tab?

**Comment by Tallyclone** [comment]
> Can you get information about the exception? Can you open the Dev Tools (Command: `Developer: Toggle Developer Tools`) and go to the Console tab?

yes! 
![Snipaste_2024-08-19_10-47-54](https://github.com/user-attachments/assets/86abe96c-af0c-4b15-b747-fcc025d0c680)
