### ISSUE TITLE
VS Code, spawn EINVAL when debugging.

### ISSUE THREAD

**Issue by Atlantidee2024** [microsoft/vscode#225783]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: any
- OS Version: any

Steps to Reproduce:

1. Open project
2. Choose "Run and Debug"
3. Select any choice on the combo and click "Start Debugging"

Hi, 
we are currently updating an APP developed in Cordova. 
We use VS Code to write the code, to debug it and to preview the app on the browser, 
Everything worked fine until a couple of days ago. When we start the debug, VS Code shows a pop up with a "spawn EINVAL" message. Even if we click on "Open launch.json" the error persist and the debug won't run.
We tried everything; updating extensions and plugin, editing our files and even creating a new "basic" project. Nothing seems to work. We alway get that error. 

Can someone please help us undertand what's happening here? 

Thank you in advance. 

![image](https://github.com/user-attachments/assets/6c283738-96f6-4b79-859a-8a1b5a896abf)

**Comment by roblourens** [comment]
Please check that you're on the latest version of VS Code, and if so, file an issue on the Cordova debug extension. Probably related to https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2. You could downgrade vscode as a short-term workaround
