### ISSUE TITLE
`extensions.autoRestart` setting breaks extension debugging if extension VSIX is installed and disabled

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#225710]
Type: <b>Bug</b>

To reproduce:

1. Be using Insiders with `"extensions.autoRestart": true`
2. Clone vscode-extension-samples
3. Open helloworld-sample
4. npm install
5. Edit package.json to change publisher to something other than "vscode-samples" (e.g. "foobar") so the next step is possible.
6. vsce package
7. Install the VSIX
8. Set a breakpoint in activate method of extension.ts
9. Debug the extension.
10. Use Command Palette in EH window to run `Hello World` command.
11. Verify that the breakpoint is hit  and execution pauses indefinitely until you resume it.
12. Stop debug.
13. In Extensions view find the extension whose VSIX you installed earlier.
14. Disable this extension.
15. Launch debugging again and run the command in the EH window.
16. Observe that the breakpoint is hit but almost immediately debugging ceases 🐛  because `extensions.autoRestart` has erroneously restarted the EH.

VS Code version: Code - Insiders 1.93.0-insider (27f650ea2366a6b99b4727b2bec9731904d52ac5, 2024-08-15T05:03:41.839Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by roblourens** [comment]
Can we avoid autorestarting while in debug mode @sandy081?

**Comment by sandy081** [comment]
@roblourens We do not auto restart if there is an active debug session

https://github.com/microsoft/vscode/blob/9b2e9634aa7cca984acd9d408bb4342cb1613aca/src/vs/workbench/contrib/debug/browser/debugService.ts#L205-L210

@connor4312 Is this not enough to check for an active debug session?

**Comment by connor4312** [comment]
> Is this not enough to check for an active debug session?

Yes, that is enough, but that is run in the window doing the debugging, not the window being debugged, which is where it sounds like this bug happen.

I suggest not auto restarting if `IExtensionService.isExtensionDevelopment` is true.

Also, that's impressive bug hunting, John 🤠
