### ISSUE TITLE
Menu bar is missing

### ISSUE THREAD

**Issue by devcloudtech** [microsoft/vscode#225730]
Type: <b>Feature Request</b>

Hi, My VS code in Mac is not showing menu bar. Appreciate if you can support to restore.

VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.6.0
Modes:

**Comment by devcloudtech** [comment]
Hi, Any update on this?

**Comment by devcloudtech** [comment]
How long do you guys take to fix issues?

**Comment by devcloudtech** [comment]
Hi,

Kindly find attached screenshot of current view of VS Code.
As can be seen, there is no way to display the menu bar where important options are required e.g. save as…etc.
Appreciate if you can support to allow menu bar to be displayed.
Let me know if you require any further information.

Kind regards,

Hossam Salem

From: vs-code-engineering[bot] ***@***.***>
Date: Friday, 23 August 2024 at 05:35
To: microsoft/vscode ***@***.***>
Cc: devcloudtech ***@***.***>, Author ***@***.***>
Subject: Re: [microsoft/vscode] Menu bar is missing (Issue #225730)

Thanks for reporting this issue! Unfortunately, it's hard for us to understand what issue you're seeing. Please help us out by providing a screen recording showing exactly what isn't working as expected. While we can work with most standard formats, .gif files are preferred as they are displayed inline on GitHub. You may find https://gifcap.dev helpful as a browser-based gif recording tool.

If the issue depends on keyboard input, you can help us by enabling screencast mode for the recording (Developer: Toggle Screencast Mode in the command palette). Lastly, please attach this file via the GitHub web interface as emailed responses will strip files out from the issue.

Happy coding!

**Comment by bpasero** [comment]
@hmos2354 where would you expect the menu to appear here?

**Comment by hmos2354** [comment]
![image](https://github.com/user-attachments/assets/0a533972-28f9-4c89-94c9-c1f775933e80)

Hopefully similar to attached.

**Comment by bpasero** [comment]
@hmos2354 you are on macOS where that kind of UI is not supported, the menu will always be shown native to the top of the screen.
