### ISSUE TITLE
`vscode.authentication.getSession` resulting quickpick lists the same account multiple times 

### ISSUE THREAD

**Issue by motm32** [microsoft/vscode#225734]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.90.0-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Sign into an account using `vscode.authentication.getSession` with the `createIfNone` option set to true and the `clearSessionPreference` set to true. In this case I am using the `microsoft` providerId and passing ['https://management.azure.com/.default'] for the scope.
2. A quickpick with a list of accounts will pop up. Select `sign in to another account`. (If you are not signed into any accounts a model will pop up instead of the quickpick)
3. After successfully signing into an account run the same command and select `Sign in to another account` again and when prompted in the browser select the same account you selected in step 2.
4. Run the `vscode.authentication.getSession` command one more time to view the quickpick.

Expect: 
The previously signed in account to only show up once in the quickpick list.

Actual: 
This account shows up twice in the quickpick list. 

Note: 
This does not affect the account list under the Accounts menu in VSCode. As expected only one account shows up there. 

If you need any further information please let me know!

**Comment by TylerLeonhardt** [comment]
Hi @motm32 👋 I've made quite a few changes this past month, could you try the latest Insiders and tell me if you still see this?

**Comment by motm32** [comment]
Hi @TylerLeonhardt just tried it out on the latest insiders and the issue seems to be resolved!
