### ISSUE TITLE
Prioritize Directories in Quick Open (⌘P)

### ISSUE THREAD

**Issue by donaldpipowitch** [microsoft/vscode#225771]
# Description
It would be beneficial to have a feature in Visual Studio Code that allows users to prioritize certain directories in the Quick Open (⌘P) results. This would help users who frequently access files in specific directories, such as `src/`, to have those directories appear higher in the search results without fully excluding other directories like `tests/`.

# Proposed Solution
Add a setting in settings.json that allows users to specify directory priorities for Quick Open. For example:

```
{
    "quickOpen.priorities": {
        "src/**": 1,
        "tests/**": 0.5
    }
}
```

This setting would make files in the `src/` directory appear higher in the Quick Open results compared to files in the `tests/` directory.

# Benefits
- Improves productivity by reducing the time spent searching for frequently accessed files.
- Provides more control over search behavior in Quick Open.
- Enhances the overall user experience in Visual Studio Code.

# Additional Context
Currently, users can exclude directories from search results, but there is no way to prioritize certain directories without fully excluding others. This feature would provide a more flexible and user-friendly solution.

**Comment by paulinemartel** [comment]
no one to upvote for this ?! I've been looking for this feature for so looong, please we need it 😅
