### ISSUE TITLE
Accessibility › Signal Options: Volume Reset Error

### ISSUE THREAD

**Issue by colroom** [microsoft/vscode#225708]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.1 (Universal)
- Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
- Date: 2024-08-07T20:16:39.455Z
- Electron: 30.1.2
- ElectronBuildId: 9870757
- Chromium: 124.0.6367.243
- Node.js: 20.14.0
- V8: 12.4.254.20-electron.0
- OS: Darwin arm64 23.6.0

- OS Version:  MacOS 14.6.1(23G93)

Steps to Reproduce:

 1. search for Volume in the settings as I don't want to hear the error sound when coding

 2. change the sound from 70 to 0 in Accessibility ‘ Signal Options: Volume

 3. exit and restart vscode and the volume is back to 70 again

 4. if you check $HOME/Library/Application Support/Code/User/settings.json, you can see the problem.
When it is 70, there is no json change, but when I set it to 0, it generates the code ‘accessibility.signalOptions.volume’: 0 code is generated.

 5. when I exit vscode and run it again, the ‘accessibility.signalOptions.volume’: 0 code in settings.json is deleted: 0 code in settings.json is deleted and the signal Options: Volume in vscode changes to 70.

 6. please fix the bug where the volume is changed to 70 when restarting vscode. It is too hard to change the volume every time I restart vscode.

Is there something I'm missing? Thanks for your answers 🙇🏻
 
- Volume 0 Setting
<img width="787" alt="VScode_Volume_0_Setting" src="https://github.com/user-attachments/assets/aef95127-7eeb-4b53-a4f5-8db816ba51e0">

- VScode Restart (Volume 70)
<img width="777" alt="Vscode_Restart_Volume_Reset" src="https://github.com/user-attachments/assets/d626aaf6-1f69-4b6c-8301-d5d27c6d1a40">

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by colroom** [comment]
> I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? /label info-needed

Oh I downloaded insiders and ran it, and it's fixed at 0 in insiders!

This is the first time I realised that insiders existed.

I did a Google and GitHub search and didn't think I had the same question, but someone else must have asked it. 🫠

When will this be fixed in vscode? 😢

Thank you so much for your answer :)

**Comment by meganrogge** [comment]
It'll be fixed in stable in a few weeks
