### ISSUE TITLE
"Report Issue" has disappeared from "Help" menu

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#225718]
Type: <b>Bug</b>

I suppose it's one way of reducing the number of issue reports!

![image](https://github.com/user-attachments/assets/5ed1c897-bef0-46ea-aef2-bd78e6822462)

VS Code version: Code - Insiders 1.93.0-insider (27f650ea2366a6b99b4727b2bec9731904d52ac5, 2024-08-15T05:03:41.839Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by gjsjohnmurray** [comment]
The feature is still available via Command Palette.

**Comment by jrieken** [comment]
@justschen Thanks for investigation!
