### ISSUE TITLE
1.92 MergeEditor does NOT load at all

### ISSUE THREAD

**Issue by BAAAASS** [microsoft/vscode#225770]
Does this issue occur when all extensions are disabled?: Dunno, N/A.

- VS Code Version: 1.92
- OS Version: Win 11

Steps to Reproduce:

1.  Upgrade to 1.92
2. Have a file (merge) conflict
3. Try to solve merge conflict

My VSCode automatically updated to the latest version (1.92).  After which I was no longer able to solve merge conflicts.  Downgraded back to 1.91 and everything works as per normal.

**Comment by BAAAASS** [comment]
Nope, was using the latest.

**Comment by hediet** [comment]
Can you share a screenshot? Thanks!

**Comment by rzhao271** [comment]
Hi @BAAAASS, does the issue still occur for you on VS Code 1.96 or later?

**Comment by BAAAASS** [comment]
Don't know.  I rolled back to an older version and then everything worked as it should.
