### ISSUE TITLE
Shift + Delete supposedly delete the line

### ISSUE THREAD

**Issue by hansyulian** [Microsoft/vscode#22579]
- VSCode Version: 1.10.1
- OS Version: Windows 7

Steps to Reproduce:

1. Just pick any line
2. press ctrl + x without any selection
3. line will gone
4. press ctrl + v
5. the "cut" line will be pasted
(this is correct)

1. Just pick any line
2. press shift + delete without any selection
3. line will gone
4. press ctrl + v
5. the "cut" line will be pasted
(this is wrong!)

Shift + Delete supposedly delete the whole line, but not replacing the current clipboard with the deleted line.

**Comment by alexandrudima** [comment]
@hansyulian We are consistent with e.g. Visual Studio out of the box.

If you would like for Shift+Delete to delete the whole line but not place it in the clipboard you can use the following mapping in your keybindings.json

```
{
  "key": "shift+delete",
  "command": "editor.action.deleteLines",
  "when": "editorTextFocus && !editorReadonly"
}
```
