### ISSUE TITLE
LanguageModelTool uses a remote schema for parametersSchema, but default is wrong

### ISSUE THREAD

**Issue by benmcmorran** [microsoft/vscode#225727]
Does this issue occur when all extensions are disabled?: No, depends on Copilot Chat and another extension to use the [lmTools API proposal](https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.lmTools.d.ts)

- VS Code Version: 1.93.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.22631
- GitHub Copilot Chat Version: v0.20.2024081501 (pre-release)

Steps to Reproduce:

1. Run `npx --package yo --package generator-code -- yo code` and accept all prompts to create a new TypeScript extension.
2. Open the new extension folder in VS Code.
3. Edit package.json to add these blocks:

```json
  "enabledApiProposals": [
    "lmTools"
  ],
```

```json
  "contributes": {
    <existing contribution points>,
    "languageModelTools": [
      {
        "id": "usernametool",
        "name": "username",
        "displayName": "Username",
        "canBeInvokedManually": true,
        "icon": "$(account)",
        "modelDescription": "This tool provides the name of the current user.",
        "userDescription": "Provides the name of the current user.",
        "parametersSchema": true
      }
    ]
  },
```

4. Run `npx vscode-dts dev`.
5. Edit src/extension.ts to add the following:

```ts
	context.subscriptions.push(vscode.lm.registerTool('usernametool', {
		async invoke(parameters, token) {
			return {
				toString() {
					return "The user's name is Bob.";
				},
			}
		},
	}));
```

6. Start debugging the extension.
7. In Copilot Chat, type "Who am I? #username"
8. GitHub Copilot responses with "unhandled status from server: 400 Bad Request".

![Image](https://github.com/user-attachments/assets/4a688a2a-b1e8-428a-8c82-69505e923506)

If product.json is changed to `"parametersSchema": {}` instead, the request succeeds. However, `true` is a valid JSON Schema according to [the meta-schema](https://json-schema.org/draft/2020-12/schema) and [online validators](https://www.jsonschemavalidator.net/).

cc @isidorn

**Comment by roblourens** [comment]
I agree that it's valid, but looks like OpenAI requires that it be an object, and I don't think I can configure our schema to point at the json schema ref but disallow a boolean: https://github.com/microsoft/vscode/blob/583328de48cf0e478c99806b6aab311fcbfdad2f/src/vs/workbench/contrib/chat/common/tools/languageModelToolsContribution.ts#L71

So I could do some runtime validation on parametersSchema when it's registered. But it's pretty annoying that `true` is the default value for the meta-schema, and I don't think I can override that. Do you have any other idea what would be helpful?

**Comment by benmcmorran** [comment]
In this case my tool didn't need any parameters, so I was just accepting the default. I didn't explicitly need it to be `true`, and `{}` works just fine for my purposes.

Ideally the default can be changed, but regardless it'd probably be good to have runtime validation just so that extension developers get a more understandable error message than an HTTP 400 in chat, which makes it look like it's the Copilot Chat extension's fault instead of the extender.

**Comment by roblourens** [comment]
Sure. You don't need to set `parametersSchema` at all in that case either.
