### ISSUE TITLE
Temporary Git session support

### ISSUE THREAD

**Issue by pedromchd** [microsoft/vscode#225780]
As a student who uses VSCode weekly in the labs' computers along with several students, it's necessary a feature where I can manage commits and repositories in a closed, temporary session, without worrying with git credentials exposed in the local git config or in browser.

**Comment by lszomoru** [comment]
Are you hosting your repositories on GitHub? If so, the `vscode.git` extension is using the GitHub credentials that you have signed in to VS Code. So rather than creating a "temporary git session", what we would want to have is a temporary auth session in VS Code so that you are automatically signed out of VS Code (maybe on closing VS Code?).

**Comment by lszomoru** [comment]
> I think something more integrated with the already existing features of both VS Code and Git would be beneficial. To me, there is an unnecessary separation between the VS Code "login" and Git credentials. You can log in to VS Code to sync settings, but to sync VS Code with Git properly, you first have to set up Git and then push through the VS Code GUI (Git doesn't allow login through CLI anymore). So, if you can't have one without the other, there is no need to set them up separately (at least inside VS Code).

I would like to better understand this. Currently if you sign-in to VS Code with your GitHub account, and you do not have any credential provider configured, VS Code should be able to leverage your GitHub credentials for git operations from both the GUI and the integrated terminal (assuming that you are using HTTPS). Isn't that what you are seeing?

**Comment by pedromchd** [comment]
Sorry if I'm explaining something wrong, but for me who uses git through CLI, the common procedure when trying to, for example, pushing changes is, in the first time, prompting for git username and git email, and after trying to trigger VS Code to pop up the dialog for properly authentication with GitHub (usually this step requires to close the CLI to push through the GUI) and after those steps I can freely make git operations both from CLI and GUI, but still remains a separate experience. I have a proper authentication throught VS Code and credentials set by CLI separately, at least in my way to get through this, but my overall propose is to make this as an unique setp, a "login/logout", by GUI or by CLI that allows me to have a unified control about my credentials inside a machine, locally or globally trough them. If this kind of feature already exists, I'm deeply sorry for not using it the proper way.

**Comment by lszomoru** [comment]
Thank you! When you are using the CLI, are you using the VS Code integrated terminal or an external terminal?
Would you be able to provide a complete recording of this (https://gifcap.dev) as that would make things even more clear. Thanks!

**Comment by pedromchd** [comment]
I'm sorry, the operation has not performed as I expected, glad for you attention.
