### ISSUE TITLE
release notes - switch between tabs

### ISSUE THREAD

**Issue by ddyrcz** [Microsoft/vscode#22588]
- VSCode Version: 1.10.2
- OS Version: Win 10

Steps to Reproduce:

1. Open the release notes (help -> release notes)
2. Scroll to the middle of the notes
3. Test some new feature in the different tab e.g. TypeScript add missing import feature
4. Return to the release notes tab
5. The scroll is at the top of the file, not at middle

This cause that I have to look for the section I have just read every time I switch between tabs

**Comment by joaomoreno** [comment]
#13256
