### ISSUE TITLE
compiler error, incorrect generated code.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#22586]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.4.0-66-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.7.0|
|EditorConfig|EditorConfig|0.6.2|
|sort-lines|Tyriar|1.2.0|
|vscode-eslint|dbaeumer|1.2.7|
|tslint|eg2|0.8.1|
|cpptools|ms-vscode|0.10.3|
|Spell|seanmcbreen|0.9.1|;

---
Steps to Reproduce:

Sample project here: https://github.com/rajinder-yadav/gazeall

The problem, at top of file I declare `child_procs`.

```js
let child_procs: ChildProcess[];
```
The following function is getting compiled incorrectly (utils.ts):

```js
function runCommand( command: string, err_halt: boolean ): void {
  const args: string[] = command.split( /\s+/ );
  const cmd: string = args.shift();
  const proc: ChildProcess = spawn( cmd, args, { detached: true } );
  child_procs.push( proc );

  proc.stdout.on( "data", ( data: Buffer ) => {
    console.log( data.toString() );
  } );

  proc.stderr.on( "data", ( data: Buffer ) => {
    console.log( data.toString() );
    if ( err_halt ) {
      console.log( "Error! Forked Child process terminating." );
      process.exit( 1 );
    }
  } );
```

Compiled incorrect code is (see line 48 in generated code utils.js)

```js
function runCommand(command, err_halt) {
    var args = command.split(/\s+/);
    var cmd = args.shift();
    var proc = child_process_1.spawn(cmd, args, { detached: true });
    child_procs.push(proc);                                          // <--- child_procs is undefined, crashes.
    proc.stdout.on("data", function (data) {
        console.log(data.toString());
    });
    proc.stderr.on("data", function (data) {
        console.log(data.toString());
        if (err_halt) {
            console.log("Error! Forked Child process terminating.");
            process.exit(1);
        }
    });
}
```

**Comment by rajinder-yadav** [comment]
I really think code like this:

```js
let child_procs: ChildProcess[];
```

should be compiled as 

```js
var child_procs = []
```

I fixed the problem by assign the variable an empty array.

**Comment by weinand** [comment]
I cannot see an error here.
The declaration  `let child_procs: ChildProcess[];` does not assign anything to `child_procs`, so `child_procs` is undefined. 
Why should this be compiled to `var child_procs = []`?

**Comment by rajinder-yadav** [comment]
I understand what's happened. However, since the variable is defined as an array, it should default to its type which is `[]` and not `undefined`. This will avoid code crashing at runtime.

Otherwise what's the point of anyone having to type more boiler-plate typed code.

**Comment by weinand** [comment]
If you want this strict behaviour (and avoid the "crashes at runtime") I suggest to enable the TS option `"strictNullChecks": true` in your tsconfig.json. This would have caught the undefined array.

If you don't like the way TypeScript works, please create issues against TypeScript.

**Comment by rajinder-yadav** [comment]
I must be tired, didn't realise this was vscode. Thanks for the details.
