### ISSUE TITLE
internal error: BuildFrameworkTcImports: no resolution of 'FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a''

### ISSUE THREAD

**Issue by duicym** [Microsoft/vscode#22582]
- VSCode Version:
![image](https://cloud.githubusercontent.com/assets/16585097/23886705/f0f94b08-08b7-11e7-9cee-46bb2eacd05e.png)

- OS Version:
windows 10
Steps to Reproduce:

1.F# fs file 
2.issues is file: 'file:///startup'
severity: '错误'
message: 'internal error: BuildFrameworkTcImports: no resolution of 'FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a''
at: '1,1'
source: ''
![image](https://cloud.githubusercontent.com/assets/16585097/23886717/0fe0b9e8-08b8-11e7-866d-e0da416c8268.png)
how can i fix it?

**Comment by weinand** [comment]
Please file this issue against the F# extension you are using.
