### ISSUE TITLE
Open editors are showing blank files

### ISSUE THREAD

**Issue by angelicav1** [microsoft/vscode#225888]
![Screenshot 2024-08-17 at 10 03 10 AM](https://github.com/user-attachments/assets/8d110a29-a86f-4323-8736-81b9a0364816)
Type: <b>Bug</b>

Open editors are showing blank pages. I am uncertain if this issue is a result of updating MacOS System to Sonoma. I have granted VS Code full Disk access and the issue persists. I am also unable to view images I was previously able to see. 

I have been working with VS Code for the past year without issues until this past week. 

VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin x64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|18, 17, 27|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id ef9898c2-afe4-4908-9f30-2f29d891390d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
codesandbox-projects|Cod|0.2.137
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
prettier-vscode|esb|11.0.0
vscode-yarn|gam|2.1.0
gc-excelviewer|Gra|4.2.60
vsc-python-indent|Kev|1.18.0
vscode-edge-devtools|ms-|2.1.5
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
pylint|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
autodocstring|njp|0.6.1
LiveServer|rit|5.7.9
pdf|tom|1.2.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-c:31118571

```

</details>

**Comment by lramos15** [comment]
Are these files not blank on disk? I'm not sure I understand the issue.

**Comment by angelicav1** [comment]
I was able to resolve the issue. It was the MacOS software update that interfered with the VS Code files I had worked on previously. Thank you for your assistance anyway.
