### ISSUE TITLE
Add syntax highlighting for Holy C (.HC)

### ISSUE THREAD

**Issue by Prince527GitHub** [microsoft/vscode#225897]
My friend wanted to learn [Holy C](https://holyc-lang.com/) but vscode does not have syntax highlighting for it so he stopped :( 
```hc
U0 Main()
{
  "Hello world\n";
}
Main;
```
*(Github has support for Holy C)*

**Comment by louwers** [comment]
VS Code supports syntax highlighting through plugins https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide

**Comment by RedCMD** [comment]
@louwers there currently doesn't seem to be any HolyC extension available
https://marketplace.visualstudio.com/search?term=holyc&target=VSCode

there is a TextMate grammar that someone can turn into an extension https://github.com/codingdandy/holyc.tmbundle
