### ISSUE TITLE
Make `"args": "${command:pickArgs}"` as default debug configuration

### ISSUE THREAD

**Issue by PRO-2684** [microsoft/vscode#225834]
> With the new feature from July participating debug extensions can now support an `args` property that takes a **single string** that is passed **unmodified** to the underlying shell (this solves your problem "... a single string that appears as multiple space-separated arguments on the command line"). 
>
> This makes it possible to use a command line like the following in a launch.json: 
> ```json
> "args": "`echo hello world` > outfile",
> ```
> Instead of having this command line literal in the launch.json you can use an `${input:commandline}`variable that lets the user type the command line in an input box:
> ```json
> "args": "${input:commandline}",
> ```

_Originally posted by @weinand in https://github.com/microsoft/vscode/issues/83678#issuecomment-1236381454_

I was really frustrated when I "debug Python files with arguments", input my space-separated argument list, and see my script treating it like a single argument. So I think it is more sensible to make `"args": "${command:pickArgs}"` as default, instead of `"args": ["${command:pickArgs}"]`. More specifically, taking Python for example, I suggest changing the default debug configuration:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python 调试程序: 包含参数的当前文件",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "args": [
                "${command:pickArgs}"
            ]
        }
    ]
}
```

to:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python Debugger: Python File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "args": "${command:pickArgs}"
        }
    ]
}
```

**Comment by miaopas** [comment]
OMG you saved my life, I was wondering why things suddenly not working

**Comment by roblourens** [comment]
Please file this on the repo for the Python debug extension- thanks!
