### ISSUE TITLE
Question: Can you search all instances of console.log and then comment them all out at once?

### ISSUE THREAD

**Issue by jdc-cunningham** [Microsoft/vscode#22581]
If this already exists sorry. I will promptly delete this.

From what I searched they were about highlighting (knowing where) the particular lines and then commenting out. So say for JavaScript I want to comment out all the console.logs at once to clean up console log. Is there a feature where I can pull up ctrl+f 'find' and search for 'console.log' then hit a button 'comment out' or something? Where it would comment out all lines of 'console.log' wherever they may be in a file?

**Comment by andrejristevski** [comment]
Why don't you use the search and replace "console.log" with "// console.log "?

**Comment by jdc-cunningham** [comment]
That works thanks.
