### ISSUE TITLE
When I open VS code, the prompt window terminates unexpectedly

### ISSUE THREAD

**Issue by minc-nice-100** [microsoft/vscode#225889]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2
- OS Version: Windows 10 Pro for Workstations 22H2 (OS build:19045.4780)

Steps to Reproduce:

1. Launch VS Code
2. ![image](https://oss.ited.top/file/3b7c5e0075127eb34323f.png)

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
