### ISSUE TITLE
tasks.json task should quote the command string

### ISSUE THREAD

**Issue by kostrse** [Microsoft/vscode#22589]
- VSCode Version: 1.10.2
- OS Version: Windows 10 Anniversary

**This doesn't work:**

```json
{
    "version": "0.1.0",
    "command": "%ProgramFiles%/nodejs/node.exe",
    "isShellCommand": true,
    "args": [ "--version" ],
    "showOutput": "always"
}
```

Output:
```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

**But this works:**

```json
{
    "version": "0.1.0",
    "command": "C:/Program Files/nodejs/node.exe",
    "isShellCommand": true,
    "args": [ "--version" ],
    "showOutput": "always"
}
```
Output:
```
v7.7.0
```

To my understanding VS Code wraps the command string into quotes only if there're spaces.
But it misses the situation when an environment variable may evaluate to a string with spaces.

This related to *cmd.exe*, didn't test with *bash*.

**Comment by dbaeumer** [comment]
We will move away from the output runner to use the terminal runner. In the terminal runner there will be no quoting magic (since the terminal allows to run in all kinds of shells which come with different quoting rules). We will then require the writer of the tasks.json file to add proper quoting.

**Comment by ggirard07** [comment]
Just hitting the same issue in 1.14.2.

If I don't properly quote the `command` parameter, then I got a warning when saving:
> Warning: the task 'Package' is a shell command and either the command name or one of its arguments has unescaped spaces. To ensure correct command line quoting please merge args into the command.

If I quote the string properly, then the task fails to execute:
```json
{
    "taskName": "Package",
    "command": "${env:ProgramFiles(x86)}\\Path\\To\\Executable.exe",
    "args": [
        "-arg1:value",
        "-arg2:v=\"${workspaceRoot}\\path\"",
        "-arg3:v=\"${workspaceRoot}\\path2\""
    ],
    "type": "shell",
    "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "shared"
    }
}
```

> \> Executing task: "C:\Program Files (x86)\Path\To\Executable.exe" -arg1:value -arg2:v="c:\my\project\path" -arg3:v="c:\my\project\path2" <
> 
> 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dbaeumer** [comment]
@ggirard07 just to check. cmd.exe is your default terminal.

**Comment by ggirard07** [comment]
@dbaeumer I think it is cmd.exe.
I found this in my user settings `"terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\cmd.exe",`
Don't really remember adding it...

**Comment by dbaeumer** [comment]
Got fixed. Marking as dup of https://github.com/Microsoft/vscode/issues/45576 which contains the change set.
