### ISSUE TITLE
Node launched when connected to a remote service uses all available ram and does not end when VSCode disconnects

### ISSUE THREAD

**Issue by tyson-nw** [microsoft/vscode#225816]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version:  Ubuntu 24.04
- the server is hosted on digital ocean with a Regular Intel 1 vCPU 1 GB Ram 
Steps to Reproduce:

1. Open terminal to server and run `top`
2. Open VS Code on a windows machine
3. Use remote explorer to connect to server.
4. `node` will begin showing in the server running `top` running as the user.
6. Close VS Code
7. `node` will remain running in `top`
8. Leaving the vscode connected for an hour or two it spins up more instances of node. 
9. Once you disconnect from vscode more node processes will appear in `top` eventually using all the available ram and cpu.

The server does not have node installed, it seems to be running the node that comes packaged in ~/.vscode/cli/servers/...

**Comment by connor4312** [comment]
should be fixed on VS Code Insiders
