### ISSUE TITLE
Custom Problem matcher does not get recognized when passed into new Task()

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/vscode#225826]
For part of https://github.com/microsoft/vscode-python/pull/23953/files, where we are trying to define a default problem matcher and a task, I have noticed an issue:

- The problem matcher, when defined in its separate user's tasks.json with same shell execution command (such as python my_file.py), gets attached properly and shows problem in the problems panel.
- However, when the exact same problem panel is defined in extension's package.json (as opposed to user's tasks.json) and passed as an argument to the API
``` 
new Task(...., $customProblemMatcher)
```
 the problem matcher fails to get attached and does not show the problem in problems panel.

I've read through task-sample repository, https://github.com/Microsoft/vscode/issues/67285, https://code.visualstudio.com/api/references/contribution-points#contributes.problemMatchers, but could not tell the reason why contributing problem matcher fails when trying to attach to a custom task.

**Comment by meganrogge** [comment]
In your PR, I see you're defining the custom matcher as `pythonCustomMatcher` and referencing it as `$pythonCustomMatcher`.

**Comment by meganrogge** [comment]
Anthony clarified he tried with and without `$` to no avail.

**Comment by meganrogge** [comment]
Figured out a workaround: wrapping the `problemMatcher` in an array.

I believe the bug is caused by our expectation that `problemMatchers` is a `string []` here when in `vscode.d.ts` we allow `string | string[]`.

https://github.com/microsoft/vscode/blob/95608e3202582e8db36fead3307500cf1f7854e9/src/vs/workbench/api/common/extHostTask.ts#L282

**Comment by anthonykim1** [comment]
Verified as wrapping around custom problem matcher in an array did seem to allow registering of the problem matcher when calling Task API

Example:
```
const taskProvider = tasks.registerTaskProvider('pythonTask', { provideTasks: () => {
            return Promise.resolve([
                new Task(
                    { type: 'pythonTask', task: 'defaultTask' },
                    TaskScope.Workspace,
                    'Default Task',
                    'pythonTask',
                    new ShellExecution('python hello.py'), // Hard coded for now should be appropriate user's Python file.
                    ['$pythonCustomMatcher'], // Use the custom problem matcher defined in package.json
                ),
            ]);
        },
```

**Comment by anthonykim1** [comment]
Verified sending custom problem matcher by itself without including in array works with the latest insiders.
