### ISSUE TITLE
Running powershell script from vsc - OpenFileDialog pops under vscode

### ISSUE THREAD

**Issue by jtaseff-gfms** [microsoft/vscode#225815]
Type: <b>Bug</b>

Running a simple powershell script with an OpenFileDialog. Running it within VS Code with F5, the dialog pops under the main window, and the only way to choose the file is to minimize VS Code manually. If there are multiple windows open, it is very easy to lose the dialog completely, and since it doesn't spawn a taskbar item for the dialog the only way is to ctrl+C the script and start over.

```
# Create an OpenFileDialog object
$openFileDialog = New-Object System.Windows.Forms.OpenFileDialog
$openFileDialog.Title = "Select Log File"
$openFileDialog.Multiselect = $false
$result = $openFileDialog.ShowDialog()
```

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
Edit: same behavior on 1.92.2
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13950HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.61GB (32.13GB free)|
|Process Argv|--crash-reporter-id 11b68068-3be7-49ab-b36e-89aa189e4ec5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
gc-excelviewer|Gra|4.2.60
vscode-edit-csv|jan|0.9.2
csdevkit|ms-|1.9.55
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.1
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.380.0
remote-wsl|ms-|0.88.2
extension-test-runner|ms-|0.0.11
powershell|ms-|2024.2.2
vs-sequential-number|nep|1.1.0
microlution-language|und|0.1.1
spot-language|und|0.3.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718

```

</details>

**Comment by jtaseff-gfms** [comment]
Same on 1.92.2

**Comment by Tyriar** [comment]
/duplicate https://github.com/Microsoft/vscode/issues/42356

If you're in VS Code Insiders you can try the new `"terminal.integrated.experimental.windowsUseConptyDll": true` setting to use the same version of conpty as Windows Terminal stable
