### ISSUE TITLE
Emmet doesn't work in Vue <template> tag.

### ISSUE THREAD

**Issue by Garfield550** [Microsoft/vscode#22585]
- VSCode Version: 1.10.2
- OS Version: Windows 10 build 15055

Steps to Reproduce:

1.  I use `Vue 2 Snippets`, `vetur` extensions, and I edit my settings.json file, add `"emmet.syntaxProfiles"` options.

``` json
// Vue emmet support
    "emmet.syntaxProfiles": {
        "vue": "html"
    },
```

2. `.vue` files language is Vue not plain text.

![tim 20170314145402](https://cloud.githubusercontent.com/assets/3471836/23889060/19b75950-08c6-11e7-88ac-e659e2cbba41.png)

3. Emmet work in empty vue file, but not work in `<template>` tag.

``` emmet
template>div>ul>li*3
```

![tim 20170314145638](https://cloud.githubusercontent.com/assets/3471836/23889136/75fdd7b6-08c6-11e7-9246-f1253af3d70b.png)

![tim 20170314145816](https://cloud.githubusercontent.com/assets/3471836/23889185/b1fad926-08c6-11e7-8b71-ae2a76159b10.png)

I lost some settings?

**Comment by octref** [comment]
This is the first thing in vetur's README...https://github.com/octref/vetur#setup

![image](https://cloud.githubusercontent.com/assets/4033249/23932885/17ad8d5a-0911-11e7-9081-6c6322ca7067.png)

@ramya-rao-a @aeschli feel free to cc me for anything related to vetur/vue, or open issue there if it's vue specific problems.

**Comment by ramya-rao-a** [comment]
Thanks @octref :)

**Comment by Garfield550** [comment]
@octref @ramya-rao-a 
I solved the problem!

It is not settings problem, `Vue 2 Snippets` and `vetur` conflicts, disable one can fix.

**Comment by ysneo** [comment]
```json
"emmet.showAbbreviationSuggestions": true,
"emmet.showExpandedAbbreviation": "always",
"emmet.includeLanguages": {
        "vue-html": "html",
        "vue": "html"
},
```
my setting, i add these

**Comment by timurmelnikov** [comment]
Yes, it works. But not always correctly ...

**Comment by ramya-rao-a** [comment]
@timurmelnikov Can you share an example?

The one case where you will not get emmet suggestions is when you want to expand a simple `word` to `<word></word>`

This was done because otherwise emmet suggestions will show up for every word you ever type which can be noisy.

`word.noise` or `word>child` etc i.e actual abbreviations or commonly used tags like `div`, `span`, `body` should show up in emmet suggestions

**Comment by timurmelnikov** [comment]
`
<a href=""></a> 
<a href=""></a> 
div             
<span></span>   
`


Full source:
`<template>
  <div v-theme:column="'narrow'" id="show-blogs">
    <h1>List Blog Titles</h1>
    <input v-model="search" v-focus type="text" placeholder="search blogs"></input>
    <div v-for="blog in filtredBlogs" class="single-blog">
      <h2 v-rainbow>{{ blog.title | to-uppercase }}</h2>
    </div>


<a href=""></a> 
<a href=""></a> 
div             
<span></span>   


</template>

<script>
import searchMixin from '../mixins/searchMixin'

export default {
  data () {
    return {
      blogs: [],
      search: ''
    }
  },
  methods: {
  },
  computed: {
  },
  created () {
    this.$http.get('http://jsonplaceholder.typicode.com/posts').then(function (data) {
      this.blogs = data.body.slice(0, 10)
    })
  },

  mixins: [searchMixin],

  filters: {
    toUppercase (value) {
      return value.toUpperCase()
    }
  },

  directives: {
    'focus': {
      bind (el) {
        // Переключаем фокус на элемент (работает через таймер)
        setTimeout(() => { el.focus() }, 0)
      }
    },

    'rainbow': {
      bind (el, binding, vnode) {
        el.style.color = '#' + Math.random().toString(16).slice(2, 8)
      }
    }
  }
}
</script>

<style>
#show-blogs {
  max-width: 800px;
  margin: 0px auto;
}

.single-blog {
  padding: 20px;
  margin: 20px 0;
  box-sizing: border-box;
  background: #eee;
}
</style>
`

**Comment by timurmelnikov** [comment]
Here is an example - https://gist.github.com/timurmelnikov/f42bfb42f60681536618d2abcb8278b0

**Comment by ramya-rao-a** [comment]
@timurmelnikov I am not able to reproduce the issue. Can you try the latest Insiders and see if you see your issue there? https://code.visualstudio.com/insiders

**Comment by timurmelnikov** [comment]
After updating to version 1.15.1, the error has disappeared. Everything works perfectly! Thank you!

**Comment by ramya-rao-a** [comment]
@timurmelnikov Great, Happy Coding!

**Comment by DanielWLam** [comment]
@ramya-rao-a  Hi, does it still not support those customize tag, like ```word```, ```dialog```?

**Comment by ramya-rao-a** [comment]
@DanielWLam The `Emmet: Expand Abbreviation` should still work for them. And if you have set `emmet.triggerExpansionOnTab` to `true`, then tab should work as well
