### ISSUE TITLE
Losing highlight inside the auto-completion popup with keyboard event.

### ISSUE THREAD

**Issue by bjmin** [Microsoft/vscode#22584]
- VSCode Version: 1.11.0-insider (2017-03-13T07:02:34.221Z)
- OS Version: 10.12.3

Steps to Reproduce:

1. Try to type something that triggered the auto-completion popup.
2. Select the target one with pressing down keyboard (up, down, etc.)
3. No highlight within popup, but shows up when cursor move by. And the selected item was actually moving when pressing down.

I assumed that's the problem with keyboard event of highlighting selected item.

![screen shot 2017-03-14 at 13 54 15](https://cloud.githubusercontent.com/assets/5073227/23887590/d879c214-08bd-11e7-84c3-fca32a83b530.png)
![screen shot 2017-03-14 at 13 54 07](https://cloud.githubusercontent.com/assets/5073227/23887591/d87ba908-08bd-11e7-9a19-ad498bd509e3.png)

**Comment by weinand** [comment]
This is a temporary glitch of yesterday's Insiders build. Should be fixed in the next...

**Comment by joaomoreno** [comment]
#22509

**Comment by bjmin** [comment]
Ok.. thx
