### ISSUE TITLE
How i can deisable banner: Files you store within the installation folder ('{0}') may be OVERWRITTEN or DELETED IRREVERSIBLY without warning at update time.

### ISSUE THREAD

**Issue by truefriend-cz** [microsoft/vscode#225801]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2
- OS Version: Windows 11

Steps to Reproduce:

1. I am running VBCode.exe from my external drive
2. I will get banner with this text:
"Files you store within the installation folder ('{0}') may be OVERWRITTEN or DELETED IRREVERSIBLY without warning at update time.",

I want disable this for ever.
![image](https://github.com/user-attachments/assets/a6ee94c9-ab48-4c82-ae29-d9ea7034c7a1)

**Comment by gjsjohnmurray** [comment]
I don't think there's an option to disable this. Why are you placing your workspaces inside the VS Code application folder?

**Comment by truefriend-cz** [comment]
> I don't think there's an option to disable this. Why are you placing your workspaces inside the VS Code application folder?

for portable solution
It is easier to back up the application, including settings, and in case of problems it can be easily restored.
