### ISSUE TITLE
Git Bash terminal in VS code adding Git breaking environment variables and we can't permanently remove them.

### ISSUE THREAD

**Issue by NickRok** [microsoft/vscode#225840]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest
- OS Version: Windows 10

Steps to Reproduce:

The issue is that VS Code bash sessions will automatically add a HOME env variable even if we try to unset and prevent it all together. This HOME variable leads to git issues, and others have experienced this too but no permanent solution has been identified. 
This issue breaks git functionality and randomly started occurring. I have a .bash_profile file that I have added unset HOME to the contents to try to solve it, however it didn't work. I tried specifying HOME: null in the vscode settings.json, and that didn't work. 

1. Open a git bash terminal, type "set | less" find the HOME env variable
2. Unset it in the current bash terminal and then open another one and you'll see that it's back
3. Add unset HOME to .bash_profile but VS code will still overwrite that and bring it back

**Comment by lszomoru** [comment]
> The issue is that VS Code bash sessions will automatically add a HOME env variable even if we try to unset and prevent it all together.

@NickRok, I do not believe that is the case as the `vscode.git` extension does set some environment variables but it does not set the `HOME` environment variable. VS Code, and the `vscode.git` extension inherits the environment variables from the environment from which VS Code is being launched. 

Do you by any chance have [this extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscode-dotnet-runtime) installed? If so, could you disable it, close all instances of VS Code, start VS Code and see if you can repro the issue? Thanks!
