### ISSUE TITLE
Two red break points showing in debugging mmode

### ISSUE THREAD

**Issue by uyhung** [Microsoft/vscode#22587]
I use the latest VS Code version. I use Chrome debugger extension to support debugging React JS app.
After I set some break points and press F5 to start debugging, each break point is showing as two red circle on the IDE, please see my attached file.

![screenshot at 2017-03-14 15 20 05](https://cloud.githubusercontent.com/assets/1470309/23891683/1749c488-08ca-11e7-83ce-04334f28da5e.png)

**Comment by kumarharsh** [comment]
I think those are the new 'column' breakpoints, if I'm not wrong.

**Comment by isidorn** [comment]
@uyhung do you see this with latest vscode insiders? Since there was an issue which we fixed a couple of days ago
Do you see this if you delete all your breakpoints and add them again?

**Comment by uyhung** [comment]
hi @isidorn ,
I'm using the latest VS Code version downloaded from the official download page.

When I delete all the breakpoints and add them again, there're showing correctly with one red point per each break point. But then I press F5 to start debugging again the second red points get shown again the the corresponding line of code are pushed to the right.

**Comment by isidorn** [comment]
@uyhung please try the latest vscode insiders - you can download it here https://code.visualstudio.com/insiders

This issue is fixed in that version. If you still see it let me know and I can reopen this.
The fix will be available in the next stable release in a couple of weeks, in the meantime you can use vscode insiders

**Comment by uyhung** [comment]
Just downloaded, updated and tried again. I still got the same error.
I'm running VS Code on Ubuntu Mate 16 and using Chrome Debugger Extension.

![screenshot at 2017-03-16 10 16 36](https://cloud.githubusercontent.com/assets/1470309/23980375/d5ab72ec-0a31-11e7-80a1-6d087845e3bc.png)

**Comment by uyhung** [comment]
Hi @isidorn 
Do I need to re-open this issue?

**Comment by isidorn** [comment]
Hi @uyhung do not reopen the issue yet as you are still using the VSCode stable version.
Please try on the vscode insiders (a special version of vscode that has the latest source). It should say 1.11 in the dialog

You can download it here https://code.visualstudio.com/insiders

![screen shot 2017-03-16 at 09 57 51](https://cloud.githubusercontent.com/assets/1926584/23988579/2056c218-0a2f-11e7-902a-c358d48320a4.png)

**Comment by uyhung** [comment]
Don't understand why I've tried re-downloaded the insider package (1.11) then re-installed several time but it's still the stable version 1.10.

**Comment by kumarharsh** [comment]
Insider has blue icon. Type `code-insiders` in terminal.

**Comment by isidorn** [comment]
Insider has the green icon and the installation should live side by side with your vscode stable installation.

**Comment by kumarharsh** [comment]
Whoops, my bad - even after using it for past year i manage to get confused XD

**Comment by uyhung** [comment]
Great, it's fixed in the Insider build, thanks.

**Comment by isidorn** [comment]
Great - adding verified label then
