### ISSUE TITLE
Dropdown to select Output is missing 

### ISSUE THREAD

**Issue by cwebster-99** [microsoft/vscode#225806]
Type: <b>Bug</b>

In the latest insiders, I am unable to select where I want to view output from in the Output panel 
![image](https://github.com/user-attachments/assets/008eeef9-d9d5-4c49-afd5-dd823fde63a2)
VS Code version: Code - Insiders 1.93.0-insider (d751e4324d12370e950f8cd031aa8829637ce300, 2024-08-16T05:03:54.591Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 Microsoft Surface (R) Edition (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.45GB (0.44GB free)|
|Process Argv|--crash-reporter-id d43c6cb7-1956-4b45-bd15-ac990a27180d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
ruff|cha|2024.40.0
esbuild-problem-matchers|con|0.0.3
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
codespaces|Git|1.17.2
copilot|Git|1.223.1055
copilot-chat|Git|0.20.2024081601
azure-dev|ms-|0.8.3
vscode-azure-github-copilot|ms-|0.1.12
vscode-azureappservice|ms-|0.25.2
vscode-azurecontainerapps|ms-|0.7.0
vscode-azurefunctions|ms-|1.15.2
vscode-azureresourcegroups|ms-|0.9.2
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.16.0
vscode-azurevirtualmachines|ms-|0.6.5
vscode-cosmosdb|ms-|0.22.0
vscode-docker|ms-|1.29.2
vscode-dotnet-runtime|ms-|2.1.1
black-formatter|ms-|2024.3.12071014
debugpy|ms-|2024.10.0
pylint|ms-|2023.11.13481007
python|ms-|2024.13.2024081501
vscode-pylance|ms-|2024.8.101
datawrangler|ms-|1.7.1
jupyter|ms-|2024.8.2024081201
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.381.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
azure-account|ms-|0.12.0
debug-value-editor|ms-|0.1.0
extension-test-runner|ms-|0.0.11
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
ts-file-path-support|ms-|0.9.1
vscode-node-azure-pack|ms-|1.2.0
vscode-speech|ms-|0.10.0
web-editors|ms-|0.1.0
py-cage|Pra|0.0.4
quarto|qua|1.114.0
kuskus-kusto-language-server|ros|3.3.1
kuskus-kusto-syntax-highlighting|ros|2.0.4
explorer|vit|1.0.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
vscaat:30438846
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
945dj816:31013170
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
impr_priority:31057980
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-c:31111717
nativeloc1:31118317
wkspc-ranged-t:31118572
3ad50483:31111987
fcdif617:31111928

```

</details>

**Comment by luabud** [comment]
I can also repro this on the latest Insiders build

**Comment by gjsjohnmurray** [comment]
I think this just got fixed by https://github.com/microsoft/vscode/pull/225959

Please get the newest Insiders and retest.

**Comment by IllusionMH** [comment]
Works on my machine™ after update
