### ISSUE TITLE
Search and Replace by "copilot"

### ISSUE THREAD

**Issue by ron2015schmitt** [microsoft/vscode#225818]
Type: <b>Bug</b>

Over the past two days, I am experiencing code replacement that I did not make.   Please fix / desist.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700K (20 x 3610)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.75GB (12.82GB free)|
|Process Argv|--folder-uri file:///f%3A/development-environments/rs2015/project-b --crash-reporter-id 0fbedbfa-139c-43e8-8fe1-23613ac1a9a6|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.2.0
tailwind-docs|aus|2.1.0
markdown-preview-github-styles|bie|2.0.4
vscode-tailwindcss|bra|0.12.6
npm-intellisense|chr|1.4.5
vscode-css-modules|cli|0.5.1
vscode-eslint|dba|3.0.10
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
gitlens|eam|15.3.0
vscode-html-css|ecm|2.0.10
auto-rename-tag|for|0.1.10
html-preview-vscode|geo|0.2.5
vscode-pull-request-github|Git|0.94.0
latex-workshop|Jam|10.1.0
vsc-python-indent|Kev|1.18.0
eml|lei|0.4.0
node-module-intellisense|lei|1.5.0
excel-live-server|loc|4.0.30
rainbow-csv|mec|3.12.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.29.2
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
cpptools|ms-|1.21.6
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
autodocstring|njp|0.6.1
vscode-extension-auto-import|Nuc|1.4.3
material-icon-theme|PKi|5.9.0
vscode-css-peek|pra|4.4.1
Encryptor|Rus|0.3.1
bash-beautify|sha|0.1.1
vscode-scss-formatter|sib|3.0.0
autoimport|ste|1.5.4
vscode-styled-components|sty|1.7.8
email-viewer|Tom|5.0.0
clang-format|xav|1.9.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-c:31111717
wkspc-ranged-t:31118572

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to try and pinpoint what's causing this.
