### ISSUE TITLE
Problems exporting Jupiter Notebook to HTML

### ISSUE THREAD

**Issue by CanaryBrianArmas** [microsoft/vscode#225882]
Type: <b>Bug</b>

I am trying to export a Jupiter Notebook to HTML and it has been giving me an error for a while.
It was working until one month, one month and something ago but now it's not and I can't find the reason

This is the error that shows up on the terminal:

**Export failed [Error: Unable to export notebook as the built-in vscode.ipynb extension is currently unavailable.**

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.79GB (1.51GB free)|
|Process Argv|--crash-reporter-id 8b33b6f3-a602-4b1f-8cac-ec906c9af703|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.8.2024080201
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
material-icon-theme|PKi|5.9.0
ayu|tea|1.0.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-t:31111713

```

</details>

**Comment by Canary98** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.92.2. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

I already updated VSCode to the latest but it's pursuing

**Comment by rebornix** [comment]
@Canary98 can you please share your settings to help troubleshoot? I wonder if the Jupyter extension is running in an extension host that's not the same as ipynb.

**Comment by Canary98** [comment]
Hi Peng, thank you so much for your answer. I'll look over the guidelines
and will try to find the solution, and I'll try also to find where those
settings you told me are.

Happy codding!

**Comment by CanaryBrianArmas** [comment]
Hello, i just tried it and it seems to be working again! Thanks a lot
