### ISSUE TITLE
Terminal: Pressing Ctrl+<Letter> key invokes VSCode hotkey, which renders terminal useless.

### ISSUE THREAD

**Issue by shardator** [microsoft/vscode#225868]
Does this issue occur when all extensions are disabled?: Both

- VS Code Version: All
- OS Version: All

Steps to Reproduce:

1. Open terminal
2. Press for example Ctrl+W, closes window instead of deleting a word in bash.

This is not a feature request, the terminal is completely useless in this state unfortunately. The solution to manually add every single possible key combination to a json config is not a solution, it is part of the bug.

# Possible solution

Add a setting to completely disable all hotkeys while the terminal is in focus, and potentially, the option to OPT IN the hotkeys in the config, instead of opting out.

**Comment by andmm** [comment]
@shardator  What are your bindings?  This is not normal behavior. There are conditions like terminalFocus that should prevent this.

**Comment by meganrogge** [comment]
I'd suggest using the command:`Developer: Toggle Keyboard Shortcuts Troubleshooting` to see what's happening with your keybindings. 

there's also this setting `terminal.integrated.sendKeybindingsToShell`

closing as I cannot repro
