### ISSUE TITLE
debug50 error

### ISSUE THREAD

**Issue by MikeyOrtz17** [microsoft/vscode#225804]
My debug50 mechanic isnt working the way I want to Whenever I use it it brings me off to another page with errors and that I can't use the mechanics of skipping a line or into code. what can I do to troubleshoot?

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
Please contact your course support channel.
