### ISSUE TITLE
launch.json  

### ISSUE THREAD

**Issue by SAJALCHOURSIYA** [microsoft/vscode#225885]
Type: <b>Bug</b>

as per my concern i think there is a problem in launch.json code 
iam not able to run my program 
it says that (launch: program 'c:\users\sajal\Document\.vscode\clue.exe' does not exist )

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i3-1125G4 @ 2.00GHz (8 x 1997)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.75GB (1.53GB free)|
|Process Argv|--crash-reporter-id 60a39d88-f360-4af8-9cc3-50eac19d6bee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-runner|fra|9.4.8
cpptask|kay|0.0.1
json|Mee|0.1.2
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-maven|vsc|0.44.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
nativeloc2:31118319
wkspc-ranged-t:31118572

```

</details>

![Uploading 1723911591690.jpg…]()

**Comment by 818Nawaf** [comment]
https://github.com/microsoft/vscode/issues/225885#issue-2471584298
