### ISSUE TITLE
ENOPRO error

### ISSUE THREAD

**Issue by sphilpott** [microsoft/vscode#225800]
ADD ISSUE DESCRIPTION HERE
 
I have been designing a Power Pages site and altering some of the code in Visual Studio for at least 6+ months now. When I click "Edit Code" it is supposed to take me to VS so I can make my adjustments. Now I receive this error:

The editor could not be opened due to an unexpected error: ENOPRO: No file system provider found for resource 'powerplatform-vfs:/[MySiteName]/web-pages/Home/Home.en-US.customcss.css'

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by mjbvz** [comment]
Please file this against the power pages extension

**Comment by zaunere** [comment]
I've had the same issue with remote-ssh for quite a while .  Sometimes my remote host goes away (public wireless) and if I haven't saved things, it gets scary.  I believe there are other tickets, similar to this.

The below is the upshot of the error:
![ssh fails](https://github.com/user-attachments/assets/9413e6df-8ea3-49f9-9755-3eef24724f0a)

I have a longer animated .gif I can send directly. The initial pop-up only has a Save button, which fails, then opens a pop-up in the lower-right which has Save-As, but doesn't seem to work either.
