### ISSUE TITLE
VSCode crashes when closing a file without saving

### ISSUE THREAD

**Issue by Xanco78** [Microsoft/vscode#22580]
- VSCode Version: 1.10 (1.10.2)
- OS Version: Windows 8.1

Steps to Reproduce:

1. Open a new file or modify an existing one.
2. Close it without saving it.

**Comment by bpasero** [comment]
@Xanco78 can you share a video how this behaves?

**Comment by Xanco78** [comment]
I found out that vscode crashes when trying to unistall an extension too. 
I tried uninstalling and installing it again, deleting all the extensions from the folder, and the problem is still there.
I uploaded the video to youtube so you don't have to download it. However, if you need the file just tell me and I'll upload it. 
When the cursor freezes is when vscode crashes, I can move it but in the video freezes. Please tell me if this is enough :)
Here's the video: https://www.youtube.com/watch?v=cMFlFZqKiXY&feature=youtu.be

**Comment by bpasero** [comment]
@Xanco78 how do you close the editor in the video? you press Ctrl+W?

**Comment by Xanco78** [comment]
No, I click with the middle scroll button, but whatever way I use to close the editor it crashes and exits vscode.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by Xanco78** [comment]
Sorry for not being able to answer before, I was not at home. 
Nothing appeared in the console, but I don't know why or how since I opened vscode with the command line it's fixed! It works even if I don't open it with the command line, so I guess it's fixed :)
Thank you very much, you're awesome!

**Comment by bpasero** [comment]
Weird, ok closing.
