### ISSUE TITLE
'az' not found on PATH, please make sure it is installed

### ISSUE THREAD

**Issue by wshamroukh** [microsoft/vscode#225851]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2
- OS Version: Windows 11

Steps to Reproduce:

1. Open a new .azcli file 
2. You will receive the error mentioned in this link https://github.com/microsoft/vscode-azurecli/issues/102

Workaround:
- Uninstall latest vscode 1.92.2 and install a previous version, In my case I installed 1.90.0 and the issue is resolved

**Comment by connor4312** [comment]
https://code.visualstudio.com/updates/v1_92#_electron-30-update
