### ISSUE TITLE
Introduce a window.title relative path variable for the folder of a file

### ISSUE THREAD

**Issue by coreyfarrell** [Microsoft/vscode#22599]
I'd like to request two new variables to output `myProject/myFolder` or `myFolder`.  The goal is for `window.title` to produce the string: `myFile.txt - myProject/myFolder - Visual Studio Code`.  I'd like to be able to see `myFolder` in the window title, but not before `myFile.txt`.  This is because sometimes `${activeEditorMedium}` is long enough to obscure the actual filename.

The default example is doesn't really show why this would be useful, a better example is if you are editing `vscode/src/vs/platform/actions/browser/menuItemActionItem.ts`.  I want to see the relative path of the active file in the window title, but `menuItemActionItem.ts` should be visible from the taskbar.

**Comment by bpasero** [comment]
@coreyfarrell as far as I know the window title never shows something else than the taskbar.

**Comment by coreyfarrell** [comment]
@bpasero that is half true.  The window title is often 1000 pixels wide, the taskbar buttons are much smaller.  On my system the taskbar buttons only show the first ~23 characters of the window title.

**Comment by bpasero** [comment]
@coreyfarrell but I understood you that you want to show something else in the taskbar compared to the window title? That is not possible.

**Comment by coreyfarrell** [comment]
@bpasero No.. I want to show the same thing in taskbar and window title.  I want the project path after the filename.  Going back to the first example I gave, if I open vscode/src/vs/platform/actions/browser/menuItemActionItem.ts, I want window.title to produce the text:
`menuItemActionItem.ts - vscode/src/vs/platform/actions/browser - Visual Studio Code`

The filename `${activeEditorShort}` is first to ensure it can be seen in the taskbar.  The relative path of the file goes next and can be seen in the window title.  vscode can be produced by `${rootName}`, but no variable can produce the text 'src/vs/platform/actions/browser' (activeEditorMedium without the filename).
