### ISSUE TITLE
Hide problems for files that don't exist in current branch

### ISSUE THREAD

**Issue by jonatanschroeder** [microsoft/vscode#225973]
I often work with multiple branches in parallel, switching between them from time to time. Say in branch A I create a set of new files that make references to each other. When I switch to another branch (say branch B) that does not include those files, the "Problems" tab will start showing errors in those files that exist in branch A but not branch B, because they make references (e.g., import) to other files in branch A that also don't exist in branch B. This is for Typescript development, if it matters, but I've seen a similar behaviour in other languages too.

Is there a way to avoid showing problems for these files, since they are not actually a problem in the current branch? Closing the tabs with the new files removes the listed problems in the problems tab, but I don't want to have to close all tabs every time I switch branches.

I tried searching for related issues and didn't find anything relevant, but I may not be searching for the correct terms, so apologies if this issue already exists.

**Comment by gjsjohnmurray** [comment]
Do you know about these SCM working sets options?

![image](https://github.com/user-attachments/assets/9b9a94dc-abfd-4ab0-945f-1568841e02e3)

**Comment by jonatanschroeder** [comment]
I'm sorry, but I don't understand how using these options would resolve my problem, could you please elaborate?

**Comment by gjsjohnmurray** [comment]
One of the options for the first setting would allow you to begin with no files open when you switch from A to B for the first time. Then after you work on B, opening the files you need, a subsequent switch to A would reinstate the set of open files you had when previously on A.

**Comment by jonatanschroeder** [comment]
Thank you for the workaround, but this doesn't actually resolve my problem. Note that this implies having a separate working set for every branch, which is not what I want. Also, from what I understand there are some requirements for this to work (e.g., only changing the branch inside VSCode), which I'm not able to stick to due to other requirements. Besides, while closing the file often dismisses the problem list, this does not always happen.

**Comment by sandy081** [comment]
Problems are generated by the extensions and they manage the life cycle of these problems. VS Code just acts as UI for these problems. Therefore, I would request to create the issue against the extension to provide options to not to create problems for non existing files or something like that. Thanks.
