### ISSUE TITLE
Suggestion shouldn't take two lines just because of the info-icon

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#22590]
See attached screen shot. The UI become very nervous when going up/down and that just because the info-icon is rendered on a separate line

![screen shot 2017-03-14 at 10 17 42](https://cloud.githubusercontent.com/assets/1794099/23893635/8a026bb8-089f-11e7-802e-86b67add2767.png)

**Comment by joaomoreno** [comment]
Here's why the row is tall:

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L48

So... probably there is a documentation string which isn't empty (just whitespace). Can you prevent that on the extension host side, @jrieken? No need to transfer an empty string if it won't ever be used.

**Comment by jrieken** [comment]
actually not true @joaomoreno. `detail` contains newlines which we fail to render <img width="540" alt="screen shot 2017-03-14 at 17 48 04" src="https://cloud.githubusercontent.com/assets/1794099/23911882/6e9ef87a-08de-11e7-80c0-52c119b6c2e6.png">

**Comment by joaomoreno** [comment]
We don't fail to render. We just render the first line, when the item is _collapsed_ and then render everything when it is expanded. So, the action is there as designed. Not the best design, sure, but as designed. 😕

**Comment by joaomoreno** [comment]
We could put the info icon on the same line though.

**Comment by jrieken** [comment]
Yes - looks like 💩 with the extra line

**Comment by ramya-rao-a** [comment]
@joaomoreno  This can also be closed in favor of #18582

**Comment by joaomoreno** [comment]
Let's do it.
