### ISSUE TITLE
VS Code Downgrade 

### ISSUE THREAD

**Issue by Muneeb00alii** [microsoft/vscode#225911]
Issue: VS Code Bug

- VS Code Version: 1.92.0
- OS Version: Windows 11 Home

I've been a user of Visual Studio Code on Windows for about 2 years, and recently I've discovered a serious issue.

Ever since the new update, whenever I close my Visual Studio Code tab and then reopen it, it shows me the me the 1.72.9 version of vs code and say that vscode will stop working on windows 8 try to upgrade your window but I have windows 11 Home installed. It seems to revert as well.

I completely delete Vs code and then reinstall it but same thing happens again.

I have looked at the Visual Studio Code website and found nothing about this problem, and I've already reinstalled Visual Studio Code once. I have no antiviruses currently.

How can I prevent this from happening?

**Comment by Muneeb00alii** [comment]
Yes I have tried that but it didn't worked.

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/197444#issuecomment-1793555342 apply to you?

**Comment by maodi-hub** [comment]
I have encountered the same problem. I have tried to download multiple different versions from the VSCode website, but I still cannot solve the problem. Have you got a solution to the problem?

**Comment by maodi-hub** [comment]
I tried to right click on the VSCode icon, enter Settings, and cancel compatibility mode, which solved this problem。You can tried it, too.

**Comment by Muneeb00alii** [comment]
> I tried to right click on the VSCode icon, enter Settings, and cancel compatibility mode, which solved this problem。You can tried it, too.

Yes it solved my problem too thank you very much!

**Comment by Muneeb00alii** [comment]
Problem Solved
