### ISSUE TITLE
file saving very slow (takes minutes)

### ISSUE THREAD

**Issue by ezekiel747** [microsoft/vscode#225944]
Type: <b>Bug</b>

Not sure about the root cause, but file saving is veery slow, takes minutes.
I tried disabled unnecessary extensions but without success.
Yesterday i noticed this behavior for the first time.

VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 8a7cbe3d-27c5-4a62-9d14-a0b49f26ade3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
amazon-q-vscode|ama|1.21.0
svg-extract|ami|1.3.0
vscode-tailwindcss|bra|0.12.6
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
os-theme|hof|1.2.0
minifyall|jos|2.10.0
remote-ssh|ms-|0.113.1
sonarlint-vscode|Son|4.8.0
vscode-stylelint|sty|1.4.0
intellicode-api-usage-examples|Vis|0.2.8
glean|wix|5.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-c:31111717
wkspc-ranged-c:31118571

```

</details>

**Comment by Number-3434** [comment]
How big is your file?

Also what formatters are you using?

Are you trying to save the file whilst it a build task is running (e.g. whilst running a Flutter project)?

Also, if you have `editor.formatOnSaveMode` set to `modifications` or `modificationsIfAvailible`, it may also cause lag.
