### ISSUE TITLE
There is no way to close a folder without deleting it

### ISSUE THREAD

**Issue by ksrp1984** [microsoft/vscode#225929]
There is no way to close a folder without deleting it, with the ability to quickly open it later. The "inactive" parameter must be added to settings.json

In my workspace the cmake project is opened, also subdirectories of this project are added. All opened folders are in the cmake-tools outline. But I mostly need to work only with the main project, subdirectories just clutter the workspace (cmake outlines). They should be opened only when needed. But every time, searching for them in the file system is inconvenient, they should remain closed in the workspace.

This is what it looks like in Eclipse:
![image](https://github.com/user-attachments/assets/41477354-c117-490b-8b1f-567c4c9e534a)

**Comment by lramos15** [comment]
I believe https://github.com/microsoft/vscode/issues/41860 covers the case you want. Please let me know if it does not and I will reopen this issue.

**Comment by ksrp1984** [comment]
> I believe #41860 covers the case you want. Please let me know if it does not and I will reopen this issue.

Unfortunately, this discussion does not contain what I asked for.
