### ISSUE TITLE
File search ignores "include" folders in Fedora 40

### ISSUE THREAD

**Issue by irm-codebase** [microsoft/vscode#225919]
Type: <b>Bug</b>

File search does not seem to work for multi-folder exclusion.

See the example below: `./modules/heat/` has been set as the only folder to search (with the correct syntax as far as I can tell...) and yet the search hits files in `./modules/_example_module/`.

I've also tried without the `./` at the start, same behavior.

![image](https://github.com/user-attachments/assets/19fa4ebf-d492-4e59-84d0-f6b7d30926c7)

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Linux x64 6.10.4-200.fc40.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 3479)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.25GB (9.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.23.1
catppuccin-vsc|Cat|3.15.1
catppuccin-vsc-icons|Cat|1.15.0
ruff|cha|2024.42.0
vscode-markdownlint|Dav|0.55.0
EditorConfig|Edi|0.16.4
remotehub|Git|0.62.0
vscode-drawio|hed|1.6.6
mypy|mat|0.3.1
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
debugpy|ms-|2024.10.0
python|ms-|2024.13.2024081501
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
azure-repos|ms-|0.38.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
autodocstring|njp|0.6.1
vscode-yaml|red|1.15.0
snakemake-lang|sna|0.1.8
even-better-toml|tam|0.19.2

</details>

**Comment by IllusionMH** [comment]
You have comma after `./modules/heat/` so you effectively included any files in that folder, all files with `.py` & `.smk` extensions, and `Snakefile`

If you want to search only in that folder and limit files you should construct single glob AFAIK.
See https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options

Probably you are looking for something like `./modules/heat/**/{*.py,*.smk,Snakefile}`

**Comment by irm-codebase** [comment]
Ahhhh, that makes sense.
I assumed that searches would be "additive" from left to right. Issue closed!
