### ISSUE TITLE
Debugger's `node-options` overwritten by `node-options` in .npmrc

### ISSUE THREAD

**Issue by shaun-funke** [microsoft/vscode#225961]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.92.2 (Universal)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

Steps to Reproduce:

- Open 'JavaScript Debug Terminal'
- Create a ts file 'test.ts' and add a breakpoint at the first line
- Create a '.npmrc' and write `node-options=--max-old-space-size=16384`
- Add script to package.json
    
```json
{
    ...
     "scripts": {
        "test": "node test.ts",
        ....
  },
}
```

Run script such as `npm run test`

Expected: It should stop on the first line of 'test.ts' when a breakpoint is set.
Current: It does **not** stop on any breakpoints.

@connor4312 mentioned [here](https://github.com/microsoft/vscode/issues/218270#issuecomment-2197224861) that its possible to append `node-options` instead of overwrite them. A reference or example of this would be extremely helpful and appreciated! 🙏

**Comment by connor4312** [comment]
https://docs.npmjs.com/cli/v10/configuring-npm/npmrc#files

**Comment by shaun-funke** [comment]
@connor4312 Thanks for the quick reply, could you please be more specific?

If you are referring to the below code snippet, this would still overewrite the debugger's node options.
```bash
key[] = "first value"
key[] = "second value"
```

**Comment by connor4312** [comment]
You would do something like `node-options = "${NODE_OPTIONS} --other-option`

**Comment by shaun-funke** [comment]
Thank you very much @connor4312
