### ISSUE TITLE
Use "OUTPUT" for the "Compile Active File" task

### ISSUE THREAD

**Issue by ujos** [microsoft/vscode#225974]
Could you change the "Compile Active File" task (the button at the top-right of the opened C++ file) to report to the OUTPUT tab rather than to TERMINAL?

The reason is because it is inconvenient to navigate upon the errors and warnings inside the TERMINAL tab. Home and End buttons actually move the cursor to the begin/end of the command at the bottom of the tab rather than scroll the compilation output top/down. And PgUp/PgDown also do not scroll up/down

**Comment by alexr00** [comment]
It sounds like this task comes from the C++ extension, so the feedback should go to them. However, in general, the errors and warnings output by tasks should end up the problems view. If that isn't happening then that's another thing you could report to the C++ extension.

**Comment by bobbrow** [comment]
@alexr00 The button added by the C++ extension plugs in to the VS Code Tasks system and all output for tasks goes to the Terminal, right?  I don't think we can change that unless we run the tasks ourselves, but that does not seem like the right approach.

If there is an issue with the problem matchers, then we can take a look at that on the extension side.

**Comment by alexr00** [comment]
@bobbrow all that is correct! I also don't think that running the task yourself is the right approach. I agree improving the problem matching is the way to go.
