### ISSUE TITLE
Customize vscode

### ISSUE THREAD

**Issue by Oscurlo** [microsoft/vscode#225995]
I want to customize my vscode a bit with a neon effect, but I can't find the style for the brackets and curly brackets 😓. My idea is to change symbols and comments with the effect. Please help me 🙏
My style: 
![image](https://github.com/user-attachments/assets/fa4da5fc-3496-4e72-a5b1-8fbfcee335a9)
Random example of what it looks like:
![image](https://github.com/user-attachments/assets/85e93f8e-93b0-4751-9e00-9d10f3481a9e)

**Comment by aeschli** [comment]
Sorry, I don't know how you can get a neon effect. I assume you use an extension for that?

**Comment by aeschli** [comment]
Please file the issue against that extension.
