### ISSUE TITLE
`<link rel="stylesheet">` doesn't work in `.MD`-file preview pane (but `<style>` does).

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/vscode#225927]
<table><tr>
	<th>Does this issue occur when all extensions are disabled?</th>
	<td>Yes</td>
</tr></table>

<table><tr>
	<th>VS Code Version</th>
	<td><code>code-insiders-1.93.0-1723788816.el8.src.rpm</code></td>
</tr><tr>
	<th>OS Version</th>
	<td><a href="https://download.fedoraproject.org/pub/fedora/linux/releases/40/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40-1.14.iso"><code>cpe:/o:fedoraproject:fedora:40</code></a> from <a href="https://koji.fedoraproject.org/koji/rpminfo?rpmID=38347230">https://koji.fedoraproject.org/koji/rpminfo?rpmID=38347230</a></td>
</tr></table>

#### **Steps to Reproduce**

<blockQuote>

```MD
<head>
	<meta charSet = "UTF-8">
	<link rel="stylesheet" href="file:///home/RokeJulianLockhart/test.CSS">
</head>
```

</blockQuote>

...doesn't function, whereas `<style></style>` does.

**Comment by mjbvz** [comment]
These aren't full html files so you can't write a `<head>` element. `<link>` stylesheets work fine but only using relative paths

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/vscode/issues/225927#issuecomment-2296941767

@mjbvz, so they won't work with any kind of URI, even an external one (`HTTPS`, etc)?
