### ISSUE TITLE
Syntax Highlight & Intellisense Stopped Working

### ISSUE THREAD

**Issue by chaseCormint** [microsoft/vscode#225934]
Type: <b>Bug</b>

Syntax highlight and intellisense stopped working. I was editing some .cs files and after closing them then reopening them syntax highlight and intellisense stopped working. I don't know if closing/reopening them was the cause but it worked fine before doing that. I have to close then reopen VSCode to fix the issue.

This has been happening for a month or so, before that I went months without seeing this issue.

Thanks.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Connection to 'wsl+Ubuntu' could not be established
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.68GB (11.58GB free)|
|Process Argv|--crash-reporter-id c255f240-c629-495b-b22a-47fe78e2bd0f|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+Ubuntu' could not be established

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 0)|
|Memory (System)|15.46GB (9.34GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.4.3
user-secrets|adr|2.0.1
copilot|Git|1.222.0
copilot-chat|Git|0.18.2
vscode-docker|ms-|1.29.2
csdevkit|ms-|1.9.55
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.1
vscodeintellicode-csharp|ms-|2.1.11
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
vscode-thunder-client|ran|2.24.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-c:31118571

```

</details>

**Comment by aeschli** [comment]
When you say syntax highlighting stopped working, does this mean the text was rendered without colors, just white and black? Or just some colors where missing?
Can you add a screenshot?

IntelliSense not working probably means the CSharp extension stopped working. I that happens you also would not see semantic colors, which are colors that are going on top of syntax highlighting, e.g to distinguish differen types of variables.

**Comment by chaseCormint** [comment]
Some colors are used, but mostly just the default blue color.

Something interesting I noticed is that when I switch to a file I'll very briefly (less than 0.5s) see semantic colors as expected then everything just goes to blue as seen in the screenshot. However that only happens if I click the file from the file pane, it does not happen if I click a tab to change to a different file.

![image](https://github.com/user-attachments/assets/a3d3769e-7d5f-4069-a4b7-86293c1d2ffd)

**Comment by aeschli** [comment]
Ok, this shows that the CSharp extension stops working or computing for a long time.
You need to file the issue at https://github.com/dotnet/vscode-csharp
