### ISSUE TITLE
Rename terminal windows

### ISSUE THREAD

**Issue by jmbrito01** [Microsoft/vscode#22597]
Hi, i use a lot vscode with a bunch of ssh terminals opened in it, the problem is that because i use "sudo ssh [...]", all of them are renamed as sudo and the node apps are renamed node, this makes things really confusing
![image](https://cloud.githubusercontent.com/assets/11761278/23898284/4f82fb84-088f-11e7-8327-0901a1f8e285.png)

I think a great feature would be to rename this terminal tabs to some text i want.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10023

We're also looking into ways of improving the name of the terminal in https://github.com/Microsoft/vscode/pull/22454 and https://github.com/Microsoft/vscode/issues/20676
