### ISSUE TITLE
Search exclude broken once again

### ISSUE THREAD

**Issue by stoplion** [microsoft/vscode#225992]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  Version: 1.93.0-insider
Commit: d751e4324d12370e950f8cd031aa8829637ce300
Date: 2024-08-16T05:03:54.591Z (3 days ago)
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
- OS Version: Mac 14.6 (23G80)

Steps to Reproduce:

```
"search.exclude": {
    "**/*/build": true,
    "**/*/build/**/*": true,
    "**/build": true,
    "**/dist": true,
    "**/dist/**/*": true,
    "**/node_modules/**": true,
    "**/node_modules/**/*": true,
    "/node_modules": true,
    "build": true,
    "build/**": true
  }
```

https://github.com/user-attachments/assets/2aeaa14d-fd06-4058-a57b-54dcfbf891bc

When the exclude glob is added to the UI, it works
<img width="665" alt="CleanShot 2024-08-19 at 10 30 47@2x" src="https://github.com/user-attachments/assets/f3dfdab6-7b4a-48af-afdd-5a7fb763cb8e">

But when added in settings it is does _not_ work.

**Comment by andreamah** [comment]
Can you try toggling this button? Seems that exclude files are not enabled in your screencap.

![Image](https://github.com/user-attachments/assets/bb65534f-e3f8-4b50-b23d-0ee8f9100e31)
