### ISSUE TITLE
Option for Search to filter comments

### ISSUE THREAD

**Issue by hilloinen** [microsoft/vscode#225928]
Visual Studio Code is well aware when some text is inside a comment since it displays such text with a different color - at least with common programming languages.

It would be great if the the search had an option button similar to _"Match Case"_ and _"Match Whole Word"_ buttons that could be used to filter out matches found in comments. I suggest three modes for such button: 1) inactive/include all (it would function like search now), 2) exclude comments, and 3) include only comments.

**Comment by IllusionMH** [comment]
Looks like duplicate of #11688
