### ISSUE TITLE
Include stack trace for "Measuring item that is not in DOM!" warning ?

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#225953]
I see multiple of these [warnings](https://github.com/microsoft/vscode/blob/5a0335dcf3ffe79466b90d7c24923f3158fac81a/src/vs/base/browser/ui/list/listView.ts#L1522) in dev console but that's not helpful since it's hard to trace the buggy caller. Should we include `new Error().stack` in the warning? 👀 

![Image](https://github.com/user-attachments/assets/e08d1617-a02c-418d-9bd3-a5c76e9f73c7)

**Comment by benibenj** [comment]
Sure, I'll add the stack trace, however, it's possible that it won't be very helpful as it's likely to stem from a list event. If that is the case we can consider logging more detailed information on the list/node.

**Comment by benibenj** [comment]
verification by code review https://github.com/microsoft/vscode/pull/226037
