### ISSUE TITLE
Suggestion highlighting is broken

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#22592]
- VSCode Version: 1.11.0-insider (dd197f)
- OS Version: Win10

Steps to Reproduce:

1. There is no highlight for the selected item in the autocomplete suggestion box.

![image](https://cloud.githubusercontent.com/assets/760112/23894721/38cb0d34-08c9-11e7-92c5-519c495f2d2d.png)

**Comment by weinand** [comment]
dup of #22509
