### ISSUE TITLE
Change the icon of quick suggestions

### ISSUE THREAD

**Issue by Tiny1233** [microsoft/vscode#225952]
I don't really like the icon styles of the quick suggestions and I can't find a folder which stored them. _So where exactly are they stored?_ If it's not an image file, I'd recommend adding **an extension that makes it easy to modify icons**, or **adding a new theme that contains new icon styles of quick suggestions**. The nature of each word determines its icon, e.g. the function is a **purple cube**, and the code snippet is a **white square (the lower edge is a dotted line, and the others are solid lines)**,etc. The **left** side of the image below is the icon style I am currently using:      

![image](https://github.com/user-attachments/assets/fafcd6be-a039-41a3-a649-a6abdc79d782)

**Comment by gjsjohnmurray** [comment]
I think you can override these using a [Product Icon Theme](https://code.visualstudio.com/api/extension-guides/product-icon-theme).
