### ISSUE TITLE
The integrated terminal font display is abnormal

### ISSUE THREAD

**Issue by zyxjeek** [microsoft/vscode#225924]
Type: <b>Bug</b>

The font on my terminal is very strange. And when I choose them, they go back to the way they were. I tried changing the font, but it didn't work. Some fonts that have been tried are Cascadia Code and Fira Code.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13500H (16 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (18.96GB free)|
|Process Argv|--crash-reporter-id f8413348-53f4-4451-a2de-9fd30a96da18|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
zip-viewer|ada|3.17.2
TabOut|alb|0.2.2
oi-runner|Cmd|0.1.2
competitive-programming-helper|Div|2024.7.1722430096
vsc-material-theme|Equ|34.5.2
vsc-material-theme-icons|equ|3.8.7
code-runner|for|0.12.2
codespaces|Git|1.17.2
vscode-power-mode|hoo|3.0.2
vscode-vibrancy-continued|ill|1.1.36
better-cpp-syntax|jef|1.27.1
vscode-fix-checksums|leh|1.1.0
theme-monokai-pro-vscode|mon|1.3.2
vscode-language-pack-zh-hans|MS-|1.92.2024081409
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
vscode-zhihu|niu|0.5.1
java|red|1.33.0
ayu|tea|1.0.5
pdf|tom|1.2.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-luogu|ylt|4.8.5
material-theme|zhu|3.17.2

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
nativeloc1:31118318
wkspc-ranged-t:31118572

```

</details>

**Comment by zyxjeek** [comment]
![image](https://github.com/user-attachments/assets/687d4218-350e-4d83-aeef-44fc3c963880)
Like that.

**Comment by meganrogge** [comment]
strange how?
