### ISSUE TITLE
Location references for variable values don't work in SSH-remote sessions

### ISSUE THREAD

**Issue by vogelsgesang** [microsoft/vscode#225967]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: Version: 1.93.0-insider (Universal), Commit: 27f650ea2366a6b99b4727b2bec9731904d52ac5
- OS Version: macOS Sonoma 14.6.1

The recently introduced support for location references for variable values (#225546) seems to be only working for local debugging sessions. For remote debugging sessions using the [Remote SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) extension, the links from the debug adapter are not resolved correctly.

This was previously reported in https://github.com/microsoft/vscode/pull/225546#issuecomment-2292428591. By now, I confirmed that this works as expected in a local, non-remote debugging session. Hence, my suspicion that this is a bug in VS-Code / the SSH extension.

**Observed Behavior: Remote Debugging through SSH**

In the screen recording, we can see:

* The function pointers are shown in the variables view and the corresponding values are linked, as indicated by the underline when hovering the value
* When Cmd+Clicking on the value, the link is followed
* The link leads to an error message.

https://github.com/user-attachments/assets/6d7ff263-16e9-4194-b732-a79952ebed89

Towards the bottom of the screen, you can see the messages sent to/from `lldb-dap`. Note how it refers to the file as `/home/avogelsgesang/Documents/corotest/test-ptr.cpp`. This is the exact same path which is also used by the debug adapter in responses to stackTrace commands, and for stack traces this path is correctly linked.

In a couple of other requests, I am seeing VS-Code to refer to this path as `vscode-remote://ssh-remote%2Bavogelsges-wsl2/home/avogelsgesang/Documents/corotest/test-ptr.cpp`. I suspect that some path mapping for remote files is still missing here?

**Observed Behavior: Local debugging**

Debugging locally, in a non-remote session, works as expected:

https://github.com/user-attachments/assets/64b36078-a57b-440a-85f8-0e73f88c5a56

### Steps to Reproduce

1. Install a VS-Code Insiders version
2. Setup a SSH remote editing session
3. Setup lldb-dap
   * Build lldb-dap, including the commit https://github.com/llvm/llvm-project/pull/104589
   * Install the [LLDB DAP extension](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.lldb-dap)
   * Set the `lldb-dap.executable-path` to point to the lldb-dap executable
4. Debug a program which contains function pointers. Pause the program such that the function pointers are in the "Variables View"
5. Cmd+Click on any of the function pointer values

**Comment by connor4312** [comment]
Verification steps:

1. Connect to a remote machine
2. Use js-debug to debug something
3. Pause with a function in your Variables view, and verify you can ctrl+click to go to its definition location

**Comment by rzhao271** [comment]
Verified with Remote WSL if that counts
