### ISSUE TITLE
C++ Code Highlighting Not Displaying

### ISSUE THREAD

**Issue by cmsanacc** [microsoft/vscode#225923]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.89.1 - 1.92.1 arm64 (other versions not tested)
- OS Version: Kylin Galaxy (Based on Ubuntu or Debian Linux)

Steps to Reproduce:

    Open VS Code and edit any C++ code file.
    Observe the syntax highlighting behavior.

Issue Description:

In VS Code versions 1.89.1 - 1.92.1, C++ code does not display proper syntax highlighting, although the small code preview box in the top right corner shows correct highlighting. When I roll back to version 1.70.1, the issue disappears. This problem only occurs with C++ code; syntax highlighting for other languages has not been tested.

**Comment by alexr00** [comment]
Can you please share some screen shots that illustrate the behavior you're seeing?

**Comment by cmsanacc** [comment]
1.70.1
![2024-08-20_08-58-29](https://github.com/user-attachments/assets/f0f278cb-d8f1-4678-978c-d190284eb6ac)
1.92.2
![2024-08-20_09-01-51](https://github.com/user-attachments/assets/b2f3a961-cafc-4e24-a0c9-873930a280c2)

**Comment by alexr00** [comment]
Can you please check/try the following:
- Disable all extensions you have installed.
- Make sure that you haven't disabled the built in C++ extension.

**Comment by cmsanacc** [comment]
Already tried, problem still exists

**Comment by alexr00** [comment]
Hmm. I can't repro this issue. I'll need some additional steps on how to reproduce it.
