### ISSUE TITLE
VS Code Server for WSL closed unexpectedly 

### ISSUE THREAD

**Issue by immois** [microsoft/vscode#225912]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92
- OS Version: Windows 11

Steps to Reproduce:

1. After the last update, I can't connect vscode to WSL and I can't open any wsl files in vscode. This is what I get in the terminal:
![Captura de pantalla 2024-08-17 232230-edit](https://github.com/user-attachments/assets/e995f4c4-28da-41c2-80a1-28ad23e2d99e)

**Comment by immois** [comment]
I have already updated to v1.92.2 but it is still the same. Do you have a solution to the problem?

**Comment by aeschli** [comment]
Hm, there's no information why the server fails.
Can you run the command line in a WSL terminal your self?


![Image](https://github.com/user-attachments/assets/e92700ce-696f-47aa-8a20-1279e2508011)

- copy/paste the content after `Starting Server: ` to `-telemetry-level=all` 

Hopefully we get more error output.

**Comment by aeschli** [comment]
What version does the Ubuntu distro have? Run `lsb_release -a` to find out.

**Comment by immois** [comment]
> What version does the Ubuntu distro have? Run `lsb_release -a` to find out.

Ubuntu 22.04.4 LTS

**Comment by immois** [comment]
> Hm, there's no information why the server fails. Can you run the command line in a WSL terminal your self?
> 
> ![Image](https://private-user-images.githubusercontent.com/6461412/359203522-e92700ce-696f-47aa-8a20-1279e2508011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyODU3NzMsIm5iZiI6MTcyNDI4NTQ3MywicGF0aCI6Ii82NDYxNDEyLzM1OTIwMzUyMi1lOTI3MDBjZS02OTZmLTQ3YWEtOGEyMC0xMjc5ZTI1MDgwMTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMDAxMTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTNiODIxOGM5NzA3NGZhMjg5ZWMxMThhOWFhOWE0NTIwMmM4NDIwMTExZjY0MzRmNWViNjU1ZjRjYjZlMDViMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SJhrlqtg1mdXSJmTmjdVtWMpB6N64rRJcvwc8c_OPmM)
> 
> * copy/paste the content after `Starting Server: ` to `-telemetry-level=all`
> 
> Hopefully we get more error output.

I ran `/home/jobs/.vscode-server/bin/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/bin/code-server --telemetry-level=all` but the cursor keeps blinking without any response

**Comment by aeschli** [comment]
Can you 
- close all VS Code windows
- in a WSL terminal. run `rm -r /home/jobs/.vscode-server/bin` 
- open VS Code again on a WSL window

What's interesting is that the start script thinks that you are on a old version of ubuntu ('legacy'), while you are on a new one.

**Comment by immois** [comment]
If it now works normally since VS Code Server was reinstalled, although the problem that caused the error could not be identified. Thanks for the help.
