### ISSUE TITLE
Breadcrumb displays wrong path on pinned files

### ISSUE THREAD

**Issue by melikepeaches** [microsoft/vscode#225998]
Type: <b>Bug</b>

1. Open file A from EXPLORER
2. Pin tab with file A
3. Open file B from EXPLORER -> breadcrumb shows file B path (correct)
4. Click on the pinned tab with file A -> breadcrumb shows file B path but should file A

This is the minimal case. When I have multiple pinned tabs and open other files, the breadcrump gets more random. 

**UPDATE:**
Looks like the bug only comes out if this setting is set to true:
`"workbench.editor.pinnedTabsOnSeparateRow": true,`

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 4000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.89GB (42.38GB free)|
|Process Argv|--crash-reporter-id 8ec5ca70-4150-4ee5-8b4a-b08461f8bc56|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container docker.wilq.devroom:5000/novum_dev:latest (novum-DEV-1)|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 0)|
|Memory (System)|41.14GB (32.43GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
macos-modern-theme|dav|2.3.19
better-cpp-syntax|jef|1.27.1
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vscode-clangd|llv|0.1.29
regionfolder|map|1.0.22
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.6
workspace-include-what-you-use|sol|0.0.3
cmake|twx|0.0.17

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-c:31111717
wkspc-ranged-c:31118571
pme_test_t:31118333

```

</details>

**Comment by melikepeaches** [comment]
I turned off extensions and custom settings.
I nailed it down to this setting in settings.json

```
{
        "workbench.editor.pinnedTabsOnSeparateRow": true,
}
```

It appears that the bug is reproducible only if workbench.editor.pinnedTabsOnSeparateRow is true.

**Comment by jrieken** [comment]
@bpasero @benibenj can you help here? It seems that pinned, extra-row items don't make the call to `update` the breadcrumbs controls, like how it is done for instance for the [single tab case](https://github.com/microsoft/vscode/blob/9330962d6b9298c4b6ba27a50a40257f22a7120c/src/vs/workbench/browser/parts/editor/singleEditorTabsControl.ts#L273)

**Comment by bpasero** [comment]
Thanks for steps.

@benibenj could you take a look?

**Comment by benibenj** [comment]
Thanks for reporting. When switching to the last previous active tab of the other tab bar it wasn't updating the breadcrumbs. Made a fix

**Comment by melikepeaches** [comment]
Still doesn't work correctly on current insiders version.

Version: 1.93.0-insider (user setup)
Commit: 36e4ddb4dbdf5d41bbeedfce2db4834085de2b87
Date: 2024-08-23T06:45:56.108Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045


https://github.com/user-attachments/assets/a52217ed-94d7-45cf-ae61-6341b75ac678
