### ISSUE TITLE
TypeScript server is continuously crashing

### ISSUE THREAD

**Issue by luisnquin** [microsoft/vscode#225996]
Type: <b>Bug</b>

 - Execute "encore app create"
 - Select TypeScript
 - Select blank project

That's it

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Linux x64 6.10.4
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12650H (16 x 4100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|30.98GB (13.78GB free)|
|Process Argv|. --crash-reporter-id 9fef4e29-b025-42a4-913c-3ec9919b5a6b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|hyprland|
|XDG_CURRENT_DESKTOP|Hyprland|
|XDG_SESSION_DESKTOP|hyprland|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (122)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.1.4
vscode-openapi|42C|4.28.1
terraform|4op|0.2.5
templ|a-h|0.0.26
better-comments|aar|3.0.2
nix-env-selector|arr|1.0.11
nestjs|ash|1.4.2
Nix|bbe|1.0.1
vagrant|bbe|0.5.0
biome|bio|2.3.0
vscode-tailwindcss|bra|0.12.6
nixfmt-vscode|bre|0.0.1
path-intellisense|chr|2.9.0
systemd-unit-file|coo|1.0.6
htmx-attributes|Cra|0.8.0
doxdocgen|csc|1.4.0
vscode-robots-dot-txt-support|dar|1.5.1
vscode-markdownlint|Dav|0.55.0
debian-vscode|daw|0.1.2
vscode-eslint|dba|3.0.10
rasi|dla|1.0.0
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.3.0
env-switcher|Eck|0.5.2
EditorConfig|Edi|0.16.4
vsc-material-theme-icons|equ|3.8.7
json-tools|eri|1.0.2
prettier-vscode|esb|11.0.0
yuck|eww|0.0.3
docker-explorer|for|0.1.7
shell-format|fox|7.2.5
vscode-github-actions|git|0.26.3
go|gol|0.42.0
gc-excelviewer|Gra|4.2.61
todo-tree|Gru|0.0.226
terraform|has|2.32.2
rest-client|hum|0.25.1
iceworks-style-helper|ice|1.1.2
npm|ide|1.7.4
vscode-nestjs-snippets-extension|img|1.4.0
vscode-nestjs-typeorm-snippets|img|1.3.0
vscode-env|Iro|0.1.0
better-cpp-syntax|jef|1.27.1
nix-ide|jno|0.3.3
svg|joc|1.5.4
Angular2|joh|18.0.2
concise-sql-formatter|kaa|0.0.3
alejandra|kam|1.0.0
vsc-python-indent|Kev|1.18.0
vscord|Leo|5.2.12
bash-extension-pack|liz|0.0.4
bash-ide-vscode|mad|1.42.0
rainbow-csv|mec|3.12.0
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
document|min|2.2.2
shfmt|mkh|1.3.1
vscode-aql|mon|1.9.2
vscode-docker|ms-|1.29.2
vscode-edge-devtools|ms-|2.1.5
autopep8|ms-|2024.0.0
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
pylint|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.10.26
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
vsliveshare|ms-|1.0.5936
vscode-react-native|msj|1.13.0
uuid-generator|net|0.0.5
ocaml-platform|oca|1.20.0
vetur|oct|0.37.3
go-inline-pgformatter|pas|1.0.3
csv-to-table|php|1.4.0
material-icon-theme|PKi|5.9.0
vscode-go-inline-html|pyr|0.0.4
inline-sql-syntax|quf|2.16.0
vscode-thunder-client|ran|2.24.13
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
openapi-vs-code|Red|0.4.7
shellman|Rem|5.7.0
LiveServer|rit|5.7.9
bash-debug|rog|0.3.9
shebang-snippets|rpi|0.1.4
terraform-doc-snippets|run|0.6.0
rust-analyzer|rus|0.3.2078
vs-code-prettier-eslint|rve|6.0.0
vue-vscode-snippets|sdr|3.1.1
bash-beautify|sha|0.1.1
indenticator|Sir|0.7.0
just|ske|2.0.0
code-spell-checker|str|3.0.1
lua|sum|3.10.5
supermaven|Sup|1.0.8
even-better-toml|tam|0.19.2
vscode-nginx-format|tec|0.0.6
shellcheck|tim|0.37.1
pdf|tom|1.2.2
vscode-pets|ton|1.27.0
cmake|twx|0.0.17
errorlens|use|3.20.0
vscode-nginx|wil|0.7.2
vscode-import-cost|wix|3.3.0
change-case|wma|1.0.0
arrange-selection|Wup|1.3.1
JavaScriptSnippets|xab|1.8.0
pretty-ts-errors|Yoa|0.6.0
markdown-all-in-one|yzh|3.6.2
vscode-python-poetry|zes|0.17.27
material-theme|zhu|3.17.2
vscode-zig|zig|0.5.8

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31118572

```

</details>

**Comment by luisnquin** [comment]
Apparently this happens to me in any project.

![image](https://github.com/user-attachments/assets/a1d04e56-6c8f-4235-97c2-16ce29e27cf9)

**Server logs**:

![image](https://github.com/user-attachments/assets/5827fd0f-5540-47aa-a0bf-eab2ffd71319)

I already have verbose output enabled

![image](https://github.com/user-attachments/assets/2784123d-9c1e-4670-b83a-fabd8a734e3e)

**Comment by luisnquin** [comment]
What a surprise, after restarting my computer it's working again. There's a routine process that deletes files from `/tmp`.

Maybe the error handling can be improved here?

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
