### ISSUE TITLE
error in intelicode

### ISSUE THREAD

**Issue by staviasz** [microsoft/vscode#225925]
Type: <b>Bug</b>

open file tsx 

The JS/TS language service immediately crashed 5 times. The service will not be restarted. This may be caused by a plugin contributed by one of these extensions: styled-components.vscode-styled-components, VisualStudioExptTeam.vscodeintellicode, VisualStudioExptTeam.vscodeintellicode. Please try disabling these extensions before filing an issue against VS Code.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Linux x64 6.2.0-39-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3691)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|5, 4, 4|
|Memory (System)|15.50GB (9.99GB free)|
|Process Argv|/home/staviasz/Desktop/routinely/routnely --crash-reporter-id 96d54a29-b8ce-4972-948c-199843ef0333|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (77)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
vscode-sql-formatter|adp|1.4.4
vscode-angular2-files|ale|1.6.4
ng-template|Ang|18.2.0
vscode-django|bat|1.15.0
vscode-tailwindcss|bra|0.12.6
prettier-vscode-standard|bys|0.22.1
path-intellisense|chr|2.9.0
codeium|Cod|1.10.11
gitignore|cod|0.9.0
indent4to2|Com|0.1.2
vscode-test-explorer-status-bar|con|1.2.0
sql-formatter|cym|1.0.2
angular-schematics|cyr|6.13.1
vscode-pytest-intellisence|dat|0.0.1
vscode-eslint|dba|3.0.10
javascript-ejs-support|Dig|1.3.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
vscode-javac|geo|0.2.46
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.25.1
prettier-sql-vscode|inf|1.6.0
angular2-switcher|inf|0.4.0
angular-file-changer|joh|0.0.4
Angular2|joh|18.0.2
styled-components-snippets|jon|0.10.0
vscode-colorize|kam|0.11.1
graphql-for-vscode|kum|1.15.3
vscode-python-test-adapter|lit|0.8.2
angular-extension-pack|loi|1.1.2
vscode-language-babel|mgm|0.0.40
black-py|mik|1.0.3
vscode-docker|ms-|1.29.2
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
flake8|ms-|2023.10.0
mypy-type-checker|ms-|2023.6.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
test-adapter-converter|ms-|0.1.9
vscode-typescript-next|ms-|5.6.20240817
vsliveshare|ms-|1.0.5936
jetbrainsmono|Nar|1.0.2
reload|nat|0.0.7
arrr|obe|0.1.3
material-icon-theme|PKi|5.9.0
prisma|Pri|5.18.0
quicktype|qui|23.0.170
karma-problem-matcher|rct|1.0.1
java|red|1.33.0
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|6.0.0
angular-cli|seg|0.0.19
vscode-sql-beautify|sen|0.0.4
firacode|Sey|2.2.1
simontest|Sim|1.9.10
indenticator|Sir|0.7.0
bunker|sld|1.1.6
autoimport|ste|1.5.4
move-ts|str|1.12.0
code-autocomplete|svi|1.2.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
gitblame|wad|11.0.1
console-ninja|Wal|1.0.350
JavaScriptSnippets|xab|1.8.0
plsql-language|xyz|1.8.2
vscode-colorize-plus|YuT|0.12.13

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-t:31118572
pme_test_c:31118331

```

</details>

**Comment by gjsjohnmurray** [comment]
> This may be caused by a plugin contributed by one of these extensions: styled-components.vscode-styled-components, VisualStudioExptTeam.vscodeintellicode, VisualStudioExptTeam.vscodeintellicode. Please try disabling these extensions before filing an issue against VS Code.

Did you try this?

/needsMoreInfo
