### ISSUE TITLE
Support "Report Issue" for individual extensions

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#22591]
Today the inbox tracker has to move many issues to different repositories even if it was clear for the creator of the issue that it was an issue with a specific extension.

One reason for this is that the "Report Issue" action makes it very easy to create an issue against VS Code but not against any other repository.

It would be extremely helpful if we could support extension specific "Report Issue" (may be as sub menus under "Report Issue").

**Comment by joaomoreno** [comment]
#21376
