### ISSUE TITLE
Python documentation view issue

### ISSUE THREAD

**Issue by azzammuhyala** [microsoft/vscode#225966]
Does this issue occur when all extensions are disabled?: (Yes)/~No~

I would like to ask why the last letter character is missing in this documentation view in the parameter group section?

![Cuplikan layar (SCREENSHOOT) 2024-08-19 181528 GMT+7](https://github.com/user-attachments/assets/3f0c3b1c-dfb6-4e70-8d51-7cae9a20700f)

Even though in the raw text display form there is no problem.

literally for example in the parameter name `id`: ... in its appearance it points to `i` not `id`. also others, for example `rect` is pointed to `rec`.. why?

- VS Code Version: 1.92.2
- OS Version: Windows 11

**Comment by aeschli** [comment]
Can you paste some Python code so I can easily reproduce?
