### ISSUE TITLE
Second window to open does not open folder when first's cwd is deleted

### ISSUE THREAD

**Issue by martypdx** [microsoft/vscode#2259]
`Version 0.10.6 (0.10.6)` on OSX.

``` sh
> mkdir test1 && cd test1
> code .
> cd ..
> rm -rf test1
> mkdir test2 && cd test2
> code .
```

Second instance hangs until you completely quit vs code and relaunch.

Why would anyone do this? I'm grading student assignments, so I git clone and then delete directory after reviewing each student's assignment.

**Comment by bpasero** [comment]
@martypdx this seems to be https://github.com/nodejs/node/issues/1184

as a workaround, do not cd into the folder but instead open the folder from its parent directory.

**Comment by martypdx** [comment]
> as a workaround, do not cd into the folder but instead open the folder from its parent director

good idea, thx!

**Comment by martypdx** [comment]
Poking around some more on this, it seems that it only happens if the initial cwd that causes `code` to launch is deleted. It crashes even if the initial window is closed before deleting. (And inversely, subsequent opens don't bring down code if they are deleted). 

So while there is an underlying node issue, it would seem `code` could be made more tolerant. I haven't dug into the src at all, but wouldn't it make more sense to have the root process `process.chdir` to someplace other than the initial code directory, and launch the initial window in the same manner as any other subsequent open request?

**Comment by bpasero** [comment]
Where should Code chdir to? I am feeling uneasy doing such a change without understanding the impact for all spawned processes.

**Comment by martypdx** [comment]
> Where should Code chdir to? I am feeling uneasy doing such a change without understanding the impact for all spawned processes.

Well there's already an impact between the first opened directory and all subsequent spawned instances. I'm guessing the root process that spawns additional instances gets tied to the first directory from which `code` is launched. So perhaps it could `chdir` to the app dir or somewhere "safe" and then the first code editor instance would be spawned like any other instance it the original directory from which it was opened.

**Comment by bpasero** [comment]
@martypdx I think you could already do this with the current release. If you look at the script on Mac to launch code you see that we define a CWD variable called `VSCODE_CWD`:

```
function code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*; }
```

If you hardcode that one to be some other directory, it should work.

**Comment by sguillia** [comment]
It seems I just had this problem. Unable to open a folder until I completely quit vscode and relaunch.

Version:
```
Version: 1.42.0-insider
Commit: be9c72410acc677070685a616773b122f4c5e141
Date: 2020-01-29T05:36:49.901Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-74-generic
```

I only deleted the `.vscode` folder that was created in the workspace.
After that, built-in extensions started crashing with this error message:
```
The TypeScript language service died 5 times right after it got started. The service will not be restarted
```
But the extension was restarted anyway, so it kept crashing every few seconds.




![Capture du 2020-01-30 14-43-36](https://user-images.githubusercontent.com/15984272/73454940-64375480-436f-11ea-85d7-f81be1bb51d8.png)

**Comment by bpasero** [comment]
Since this issue has a linked upstream issue referenced, I am going ahead to close this issue as part of our issue grooming effort: https://github.com/microsoft/vscode/wiki/Issue-Grooming
