### ISSUE TITLE
Show Sidebar in new Window when Activity Bar not default

### ISSUE THREAD

**Issue by RayszShen** [microsoft/vscode#226027]
I found that once the [Activity Bar Position] is set to [Top], i can't find the activity bar at the top anymore, when i click [File->New Window] to open a new window.
Therefore, i suggest  display the activity bar by default when opening a new window.

**Comment by RayszShen** [comment]
<img width="1068" alt="20240820103700" src="https://github.com/user-attachments/assets/48cd7ec7-95d0-4290-b869-036597d6d372">

As shown in the picture, the new window displays nothing.

**Comment by benibenj** [comment]
I like this idea, I will look into it.
