### ISSUE TITLE
Add "Ctrl + K" AI-Powered Code Editing feature to VS Code

### ISSUE THREAD

**Issue by flowstate247** [microsoft/vscode#226004]
I'd like to request the addition of a "Ctrl + K" feature in VS Code, similar to what's available in the Cursor editor.
The description of the feature is here: https://www.cursor.com/features

See this comment by @levelsio for the motivation: https://twitter.com/levelsio/status/1825321031231213586

_Ok now 2 weeks on Cursor_

_It's great_

_I only use CMD+K now which is inline prompt box_

_You tell it to do something and it writes the code for you and you can Accept or Reject_

**Comment by mjbvz** [comment]
See https://code.visualstudio.com/docs/copilot/getting-started#_refactor-your-code-through-ai-chat
