### ISSUE TITLE
`window.restoreWindows` `preserve` should respect `window.openFilesInNewWindow`

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [microsoft/vscode#226097]
`window.openFilesInNewWindow` option is ignored on session restore when `window.restoreWindows` is set to `preserve`: file is always opened in some specific restored window. `--new-window` command-line option is also ignored. I expect that a file should always be opened in a new window on session restore when `window.openFilesInNewWindow` is either `default` or `on`.

**Comment by bpasero** [comment]
What are the steps to get it to not open a file?

**Comment by WPMGPRoSToTeMa** [comment]
@bpasero, sorry, looks like it was a bug in some previous version. I was not able to open an untrusted file when a trusted folder was restored. But in the latest version it works fine (asking if you want to trust it).

Still, there are two unexpected things with `"window.restoreWindows": "preserve"`:
1. `--new-window` command-line option is ignored.
2. `window.openFilesInNewWindow` setting is also ignored.

I think (1) should be treated as a bug and (2) may be treated as a feature request since it is a breaking change and a new setting value would be needed to not break the existing behavior. Should I leave this issue for (1) and open another one for (2)? And also should I change the template of this issue to the bug template?

**Comment by bpasero** [comment]
Yes, agree on the bug: https://github.com/microsoft/vscode/issues/226392

Leaving the rest here as feature request.
