### ISSUE TITLE
VSCode keeps crashing after update on OSX

### ISSUE THREAD

**Issue by Kagu-chan** [Microsoft/vscode#22600]
- VSCode Version: darwin stable
- OS Version: OSX Sierra 10.12.3

After restart for update VSCode keeps crashing. "Window is crashed, you can reopen it..."
I deleted VSCode from applications directory and redownloaded it, issue still there

**Comment by weinand** [comment]
Please try the following:
- shutdown VS Code
- rename the folder `Code` (or `Code - Insiders`) in your `~/Library/Application\ Support` folder to a different name, e.g. `Code2`
- start VS Code

Does it still crash?

**Comment by Kagu-chan** [comment]
Seems to work, thanks.
Closing...

**Comment by weinand** [comment]
@Kagu-chan great, thanks for trying my suggestion.
Please consider to remove the no longer used `Code2` folder.
