### ISSUE TITLE
sprit.ts.reloadprojects already registered by TypeScript and JavaScript Language Features

### ISSUE THREAD

**Issue by sameemqiitm** [microsoft/vscode#226033]
<img width="1350" alt="sprit ts reloadprojects already registered " src="https://github.com/user-attachments/assets/24169b2b-676c-445f-96de-2c2d9644dd16">
Type: <b>Bug</b>

1.Disable/Uninstall TypeScript an Javascript language features extension(Id: sprit.typescript-language-features-loose).
2.This error would be encountered: VS Code's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VS Code.
3.Enable TypeScript an Javascript language features extension.
4.Check the Running Extensions.
5.sprit.ts.reloadprojects already registered by TypeScript and JavaScript Language Features would occur.

Extension version: 1.0.2
VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.6.0
Modes:

**Comment by mjbvz** [comment]
That's not the normal version of our built-in JS/TS extension. Where are you running VS Code?

**Comment by sameemqiitm** [comment]
Actually the built in JS/TS extension i.e. [ https://marketplace.visualstudio.com/items?itemName=sprit.typescript-language-features-loose](Marketplace), got disabled on my machine, and I got the error `VS Code's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VS Code.` Then I had to manually enable the extension as mentioned in [issue](https://github.com/microsoft/vscode/issues/72721]). and the extension I enabled is this [](https://marketplace.visualstudio.com/items?itemName=sprit.typescript-language-features-loose), isn't this inbuilt for vs code?

**Comment by mjbvz** [comment]
That's not official extension. Instead try re-installing VS Code as suggested so that the actually built-in extension works. You shouldn't need to install anything extra

**Comment by sameemqiitm** [comment]
Is this not the official extension? Then how is it listed on the marketplace as the official extension?
Please refer: https://marketplace.visualstudio.com/items?itemName=sprit.typescript-language-features-loose 
Also , is reinstalling the only solution?
