### ISSUE TITLE
Source Control View Always shows incoming/outgoing

### ISSUE THREAD

**Issue by JimR-FAN** [microsoft/vscode#226055]
Type: <b>Bug</b>

As a developer, I want to be able to hide the Incoming/Outgoing list of changes, when my source control is local and has NO remote.

I viewed the Source Control feature settings, and saw there is a setting for a) Show Incoming  and b) Show Outgoing.     I updated both values to "Never". 

Expected:   The Incoming/Outgoing list in the Source Control view would be hidden.

Actual:  the Incoming/Outgoing list was still visible. 

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.05GB free)|
|Process Argv|--crash-reporter-id 1123cfa1-467e-43ae-acd9-b0369914aa3c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
apex-pmd|chu|0.7.0
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
filter-line|eve|2.0.1
vscode-xml|red|0.27.1
salesforce-vscode-slds|sal|1.4.10
salesforcedx-einstein-gpt|sal|0.57.0
salesforcedx-vscode|sal|61.7.0
salesforcedx-vscode-apex|sal|61.7.0
salesforcedx-vscode-core|sal|61.7.0
salesforcedx-vscode-expanded|sal|61.8.1
salesforcedx-vscode-lightning|sal|61.8.1
salesforcedx-vscode-lwc|sal|61.8.1
salesforcedx-vscode-soql|sal|61.8.1
salesforcedx-vscode-visualforce|sal|61.8.1
sfdx-code-analyzer-vscode|sal|1.0.0
sfdx-package-xml-generator|Vig|2.0.11

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31118572

```

</details>

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/issues/224517#issuecomment-2289097576

**Comment by JimR-FAN** [comment]
Thank you !

**Comment by JimR-FAN** [comment]
It would be great if this was collapsable.    I loaded  GitLens extention and now I have a collapsible list of commits, so I'm good, but it would be helpful if the built-in function was collapsable w/o the need for an extension. 

Anyway, **thanks for the quick response.**   I can't believe I missed the option!
