### ISSUE TITLE
The JS/TS language service crashed 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by emreerdener** [microsoft/vscode#226019]
Type: <b>Bug</b>

The JS/TS language service crashed 5 times in the last 5 Minutes.

VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 6, 10|
|Memory (System)|32.00GB (2.51GB free)|
|Process Argv|--crash-reporter-id f3077b3b-d38f-45f1-bc12-5e323c327b46|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.8
postcss|css|1.0.9
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
copilot|Git|1.223.0
copilot-chat|Git|0.18.2
vscode-pull-request-github|Git|0.94.0
vscode-speech|ms-|0.10.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
autoimport|ste|1.5.4
vscode-css-variables|vun|2.7.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-t:31111718
wkspc-ranged-t:31118572

```

</details>

**Comment by emreerdener** [comment]
Continue to have this issue for some reason...

**Comment by Number-3434** [comment]
What did you do to make this happen?

Sometimes it ooccurs because there are too complex types in the file.
