### ISSUE TITLE
Wayland Linux question

### ISSUE THREAD

**Issue by gianfelicevincenzo** [microsoft/vscode#226026]
Where is FULL wayland support on linux?
It's strange to see a very updated editor in terms of functionality without Wayland support (the future on Linux, probably...)

OS: **Fedora 40**

**Comment by legomushroom** [comment]
@gianfelicevincenzo please provide more details on what functionality is missing for you. There are indeed some quirks with wayland support, but it would be great to scope down the issues for your case. Having a concise and clear repro steps will also help a lot 👍

**Comment by Tyriar** [comment]
Yes please provide more targeted feedback in a new issue with repro steps if applicable.
