### ISSUE TITLE
allow html-language-features to be used as defaultFormatter for xml documents

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#226083]
Type: <b>Feature Request</b>

if I load an `xml` document and then change the language mode to `html`, then I am able to format that document as html, and it works great..

however, I'd like to configure vscode to use the html formatter as the *default* formatter for xml (xsd, xhtml, aspx, etc...) documents. so tried adding this to my settings:

```
"[xml]": {
    "editor.defaultFormatter": "vscode.html-language-features"
}
```

but it doesn't work for some reason - the 'Format Document' menu option doesn't appear, and running it from the palette brings up the "THere is no formatter..." dialog. it seems like it _should_ work, right?

please make it work.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

**Comment by RedCMD** [comment]
seems xml might need to follow https://github.com/microsoft/vscode/pull/146731
using the `htmlLanguageParticipants` field

**Comment by aeschli** [comment]
There are various extensions out there that provide XML formatters. Aren't they any good?
Maybe some of them are even using jsbeautify under the hood, which is the formatter that we use for HTML.

Using the HTML formatter for XML might work well for you but as soon as we add something like that to the product, we end up with bug reports for the things that don't work. That's frustrating for the users but also for us when we can't fix it.

What you can also do is to redefine that *.xml file are of language HTML. This might cause some highlighting and other issues, but at least you get the formatter you want ;-)

Closing the issue as the right solution is for an XML extension to provide a formatter. The built-in XML support is only minimal.

**Comment by Spongman** [comment]
I don’t want to set the language to .html as that beaks functionality that requires them to be .xml. I don’t want to use a 3rd-party formatter.  I want to just configure it to use the .html formatter, which works just fine (for me) if I do temporarily change the language mode.
