### ISSUE TITLE
 Cannot read property 'configuration' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#22609]
Issue Id: <b>4ac6ef28-ee3d-c455-47d4-9c9ca999b271</b><br /><br />*Versions* <br />- 1.10.2<br />-  0b51a92e512cc57e115b6b115cac5c4c65e3b7d8<br />*Stack* <br />TypeError: Cannot read property 'configuration' of undefined<br />[/vs/workbench/parts/debug/electron-browser/debugService.ts#L874:17 (configuration)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L874:17 (configuration))<br />[/vs/workbench/parts/debug/electron-browser/debugService.ts#L160:8 (onSessionEnd)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L160:8 (onSessionEnd))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L118:26 (call)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/base/common/event.ts#L118:26 (call))<br />[/vs/workbench/services/window/electron-browser/windowService.ts#L61:21 (fire)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/workbench/services/window/electron-browser/windowService.ts#L61:21 (fire))<br />    at emitTwo (events.js:106:13)<br />    at EventEmitter.emit (events.js:191:7)<br />

**Comment by OmarBizreh** [comment]
Could this cause extensions to not load on Ubuntu? on Windows and macOS extensions are working without issues and I don't see that error message in console 

VS Code: 1.10.2
Ubuntu 16.10

**Comment by isidorn** [comment]
@OmarBizreh this is unrelated to how we load extensions

**Comment by OmarBizreh** [comment]
@isidorn Thank you for clarifying it to me and, sorry for posting in the wrong section

**Comment by fforjan** [comment]
I can still reproduce it while running my extension under tests with latest vscode insider :
'C:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe' --debugBrkPluginHost=13948 --extensionDevelopmentPath=my-ext --extensionTestsPath=my-ext

my-ext uses PROPOSED API which is subject to change and removal without notice
TypeError: Cannot read property 'configure' of undefined

**Comment by isidorn** [comment]
@fforjan this is unrelated. your error is `'configure'` null exception this issue is about `'configuration'`

**Comment by fforjan** [comment]
@isidorn  oups ! sorry... will create a different one !
