### ISSUE TITLE
Authority is missing for Windows UNC paths when using a `FileSystemProvider`

### ISSUE THREAD

**Issue by dnicolson** [microsoft/vscode#226096]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version: Windows 11 Enterprise

Steps to Reproduce:

1. Create an extension with `yo code`
2. Create a file system provider:
```typescript
class UncTestProvider implements vscode.FileSystemProvider {
  readFile(uri: vscode.Uri): Uint8Array {
		return fs.readFileSync(uri.fsPath);
  }

  writeFile(uri: vscode.Uri, content: Uint8Array, options: { create: boolean; overwrite: boolean; }): Promise<void> {
		fs.writeFileSync(uri.fsPath, Buffer.from(content));
  }

  stat(uri: vscode.Uri): vscode.FileStat | Thenable<vscode.FileStat> {
    return ({ type: vscode.FileType.File }) as vscode.FileStat;
  }

  onDidChangeFile: vscode.Event<vscode.FileChangeEvent[]> = new vscode.EventEmitter<vscode.FileChangeEvent[]>().event;
  createDirectory(uri: vscode.Uri) { }
  delete(uri: vscode.Uri, options: { recursive: boolean; }) { }
  readDirectory(uri: vscode.Uri) { return []; }
  rename(oldUri: vscode.Uri, newUri: vscode.Uri, options: { overwrite: boolean; }) { }
  watch(uri: vscode.Uri, options: { recursive: boolean; excludes: string[]; }) { return new vscode.Disposable(() => { }); }
}
```
3. Add this code to the `activate` method:
```typescript
  vscode.workspace.registerFileSystemProvider('unc_test', new UncTestProvider());

  vscode.workspace.onDidOpenTextDocument(async document => {
		const uri = vscode.Uri.file(document.fileName).with({scheme: 'unc_test'});
		const doc = await vscode.workspace.openTextDocument(uri);
		await vscode.window.showTextDocument(doc, { preview: false });
  });
```
4. Add `*` to the `activationEvents` key in `package.json`

After opening a file, the extension opens the contents of the file in a new tab based on the `uri.fsPath` value. This works on all platforms, except for UNC paths on Windows. In these cases, the authority needs to be added manually:

```typescript
const fixUncPath = (uri: vscode.Uri): string => {
  if (uri.fsPath.startsWith('\\') && !uri.fsPath.startsWith(`\\${uri.authority}`)) {
    return `//${uri.authority}${uri.path}`;
  }
  return uri.fsPath;
};
```

The issue can be fixed by removing ` && uri.scheme === 'file'` here:
https://github.com/microsoft/vscode/blob/fd2dd6d375c87271f3910c9139f058a0eef120fd/src/vs/base/common/uri.ts#L624

This may have unintended consequences though.

**Comment by jrieken** [comment]
> After opening a file, the extension opens the contents of the file in a new tab based on the uri.fsPath value.

You should never use `fsPath` (which stands for "file system path") with a scheme that is different from the `file` scheme. The implementation of fsPath does this check but in hindsight it might have been better to throw (and have the fsPath logic in a util function like nodejs)

In short, try to avoid `fsPath` whenever possible, all APIs work with URI. Using fsPath should only be the rare exception when interacting with OS level methods, like when reading a file via an API that doesn't understand uris
