### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'heightInLines' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#22607]
Issue Id: <b>c910cd0e-ab04-ad8b-82df-8f5e12542fad</b><br /><br />*Versions* <br />- 1.10.2<br />*Stack* <br />TypeError: Cannot read property 'heightInLines' of null<br />[/vs/editor/contrib/zoneWidget/browser/zoneWidget.ts#L330:21 (heightInLines)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/editor/contrib/zoneWidget/browser/zoneWidget.ts#L330:21 (heightInLines))<br />[/vs/workbench/parts/debug/browser/exceptionWidget.ts#L53:7 (_relayout)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/workbench/parts/debug/browser/exceptionWidget.ts#L53:7 (_relayout))<br />[/vs/workbench/parts/debug/browser/exceptionWidget.ts#L25:69 (_doLayout)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/workbench/parts/debug/browser/exceptionWidget.ts#L25:69 (_doLayout))<br />[/vs/base/common/async.ts#L635:8 (runner)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/base/common/async.ts#L635:8 (runner))<br />

**Comment by isidorn** [comment]
Giving this to @michelkaporin looks like there is a null exception which we should fix

**Comment by michelkaporin** [comment]
The issue started happening again, when navigating between the exception-thrown file and file with no exception on the call stack (maybe due to #22078 refactoring), thus reopening the issue.
