### ISSUE TITLE
Improve discoverability of chat participants

### ISSUE THREAD

**Issue by charris-msft** [microsoft/vscode#226080]
@roblourens & @joyceerhl 
In the "VS Code UX Sync" meeting on 2024.08.20, we discussed ways to improve the discoverability of chat participants. This is important so we can help users become aware of participants that could be very helpful for them.

Here are the top suggestions from the meeting:
- Recommend *strategic* participants that are not installed
  - Copilot Chat has metadata for a select set of participants, even when those participants are not installed.
- Include *strategic* participants in the @ menu, even if they are not installed
  - when the user types @, they would see participants that are not yet installed.
  - when a participant that is not installed is used, the extension will be installed

Examples of *strategic* participants:
- @azure
- ...

**Comment by joyceerhl** [comment]
> Include strategic participants in the @ menu, even if they are not installed

This makes sense to me, we do something similar in the remote indicator picker (bottom left corner) for remote extensions that are not yet installed.

**Comment by kvenkatrajan** [comment]
@isidorn any thoughts on when this can be prioritized?

**Comment by isidorn** [comment]
@kvenkatrajan I would not tackle the issue of participant discoverability through recommendation of chat participants in chat. But instead with one of the following two:
1) bundle participant with existing extensions where it makes sense
2) recommend those extensions using existing extension mechanisms (passive recommendations and notification recommendation)

In addition to that we can mention participants in the Chat welcome view that @daviddossett is working with.

After we do those, if we see that discoverability is still an issue then we look into adding additional things as proposed in this issue.

**Comment by kvenkatrajan** [comment]
Thanks for your recommendation @isidorn. We will weigh what it would mean to bundle the participant with Azure tools extension.

> Chat Welcome view

This is interesting. Can you provide additional details here. thanks!

**Comment by isidorn** [comment]
Closing this one in favour of this issue https://github.com/microsoft/vscode-copilot/issues/8726
@kvenkatrajan that issue should have more details about our proposals on how to help with discovery of @azure
