### ISSUE TITLE
My vscode back to old version after using customization setting

### ISSUE THREAD

**Issue by 9Taurus** [microsoft/vscode#226007]
i installed version 1.92 and after using this customization setting my vscode backed to version 1.79.2
i got this problem twice
i have windows 11

![image](https://github.com/user-attachments/assets/702ec496-754a-4065-85ec-545be92f5c1f)
![Screenshot 2024-08-19 235858](https://github.com/user-attachments/assets/b5818c49-74c2-49b1-9587-38cee6652c66)
[vscode custom setting.txt](https://github.com/user-attachments/files/16665040/vscode.custom.setting.txt)

**Comment by 9Taurus** [comment]
check for update :
![Screenshot 2024-08-20 000646](https://github.com/user-attachments/assets/a7fc3778-91d6-4265-aa17-2e89b407d497)

**Comment by IllusionMH** [comment]
Are you running VS Code in compatibility mode? Check Properties on executable and/or shortcut.
