### ISSUE TITLE
Turning off word-based suggestions isn't enough for comments

### ISSUE THREAD

**Issue by emackey** [Microsoft/vscode#22601]
I set `editor.wordBasedSuggestions: false` in my user-level settings, and even restarted vscode, but if I open a `*.js` JavaScript file and type the following:

        // If

Still, vscode pops up some kind of suggestions about the JavaScript keyword `if`, even though I'm trying to write simple English in my comment.  Is there any way to really, fully disable all suggestions for comments?

(Originally posted in an unrelated issue, #17426)

**Comment by emackey** [comment]
The problem is coming from code snippet suggestions being used inside comments.  For example, type the following and press ENTER:

```
// Fred's
```

When ENTER is pressed, VSCode inserts the following text:

```
// Fred'setTimeout(function() {
    
}, timeout);
```

**Comment by jrieken** [comment]
Yes - we will have to revisit this. We have now an action that controls word-base suggestions but that's not so useful... The new idea is to control is quick suggestion should kick off when inside comments or strings. So, when explicitly requested suggestion (including words, snippets) will still come but not as you type (24x7-IntelliSense)

**Comment by jrieken** [comment]
We have fixed that in the original issue. Quick suggestion aka 24x7 suggestions are not disabled by default when typing in comments or strings and must be enabled explicitly
