### ISSUE TITLE
VSCode Terminal Disappearing

### ISSUE THREAD

**Issue by SisyphusRex** [microsoft/vscode#226098]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
- OS Version: Windows 10 & Windows 11

Steps to Reproduce:

1. The bottom panel where the terminal resides disappears whenever I open a Github codespace.  I took CS50 Python and the cloud VSCode worked fine.  Now I am taking CS50 SQL and the terminal disappears.  VSCode works fine on my desktop, but the terminal disappears if I try to make a remote connection to the cs50.dev codespace.
2. Here are youtube videos of my screen and the problem:
3. https://youtu.be/sO70nZTpatc
4. https://youtu.be/bQ1an4EHG8E
5. https://youtu.be/Q3_F6fYRyoU
6. https://youtu.be/v2JJ0YXHhyE
7. https://youtu.be/EjHWkKcOqQA
8. https://youtu.be/WgMUDAVnE-w

**Comment by meganrogge** [comment]
what happens if you create a new codespace vs reconnecting to an old one?

**Comment by SisyphusRex** [comment]
The terminal still disappears with a new code space.Sent from my iPhoneOn Aug 21, 2024, at 9:46 AM, Megan Rogge ***@***.***> wrote:﻿
what happens if you create a new codespace vs reconnecting to an old one?

**Comment by meganrogge** [comment]
I cannot reproduce - have you tried disabling all extensions?

**Comment by SisyphusRex** [comment]
I disabled all extensions and the terminal still flashes and disappears.

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal

**Comment by SisyphusRex** [comment]
I've attached the trace log and the settings.json for my cs50 codespace.
The terminal log is referencing C:\Projects not being found .  That is the
main folder and starting directory for my desktop version of VSCode.  Could
my desktop settings have migrated to the cloud instance of VSCode through
my profile?

**Comment by meganrogge** [comment]
yes, i'd try with a new profile.
