### ISSUE TITLE
Mac TorchBar dosen't work

### ISSUE THREAD

**Issue by congshan22104** [microsoft/vscode#226024]
I click the "Run" key in the TorchBar on my Mac and it's showing the debug instead of running your code normally,
- VS Code Version:  1.92.2
- OS Version: 14.5

**Comment by roblourens** [comment]
I believe that button is the same as the "run" button in vscode which does start the debugger. You might want to use "Run without debugging" under the "Run" menu in the normal menubar. Or run your code using an extension or a different way.
