### ISSUE TITLE
Some of Git repo files shows modified without any changes

### ISSUE THREAD

**Issue by VijayMadhyanapu** [microsoft/vscode#226150]
Type: <b>Bug</b>

I connect to one of our organization repo and cloned it from VSCode and without me doing any changes to any files, it shows some files as modified but when compared there are no differences. Earlier, I committed these changes but this is becoming recurring issue to all our team members.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (1.96GB free)|
|Process Argv|--crash-reporter-id eebb9654-58ec-4f06-8825-d64ecc4aab3c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
remotehub|Git|0.62.0
vscode-pull-request-github|Git|0.94.0
gc-excelviewer|Gra|4.2.61
git-graph|mhu|1.30.0
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.23.0
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.3
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
azure-repos|ms-|0.38.0
powershell|ms-|2024.2.2
remote-repositories|ms-|0.40.0
vscode-speech|ms-|0.10.0
batch-runner|Nil|1.3.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-c:31111717
wkspc-ranged-c:31118571
ei213698:31121563

```

</details>

**Comment by IllusionMH** [comment]
Usually it's line ending changes between repo and Windows setup.
Do you have same git setup as other devs on Windows?

**Comment by VijayMadhyanapu** [comment]
> Usually it's line ending changes between repo and Windows setup. Do you have same git setup as other devs on Windows?

Yes, its one and the same git setup. As I mentioned in my main reported details, most of our team members getting this issue in their machine as well.

**Comment by VijayMadhyanapu** [comment]
![Recording 2024-08-29 at 15 24 50](https://github.com/user-attachments/assets/c68cb9a9-6a4c-4ca7-b66f-dd75a6cfb952)

As soon as I open our repo, some files shows as modified but really there are no differences.

**Comment by lszomoru** [comment]
@VijayMadhyanapu, could you please open the integrated terminal and run `git status -z -uall` and share the output? Thanks!

**Comment by VijayMadhyanapu** [comment]
Here it is...
PS D:\FFI\Vijay\github\HA-CIMS> git status -z -uall
 M RF/SQL/Procedures/sp_AMF_Picking/pr_AMF_Picking_DP_DropPallet.sql M SQL/Procedures/sp_Picking/pr_Picking_DP_PauseOrFinishPick.sql M SQL/Procedures/sp_RFC_Picking/pr_RFC_Picking_ValidatePallet.sql

**Comment by VijayMadhyanapu** [comment]
Just to let you know to the original issue reported, its not allowing me to discard these changes as well.

**Comment by lszomoru** [comment]
VS Code renders the contents of the "Source Control" view based on the output of the `git status` command. Given that `git status` returns these files as modified indicates to me that this question is more about git (ex: why does git believe that these files are modified) then VS Code. I would suggest that you post this question on StackOverflow as that is a more appropriate channel for such a question.
