### ISSUE TITLE
Lines of Code and Line Numbers Getting Hidden While Scrolling in VS Code

### ISSUE THREAD

**Issue by ZainHayder** [microsoft/vscode#226145]
![Uploading Capture45518.PNG…]()
Type: <b>Bug</b>

Hello,

I'm experiencing an issue in Visual Studio Code where lines of code and line numbers get hidden when I scroll. This behavior is very frustrating and disrupts my coding workflow. It seems like the lines are somehow getting hidden or pushed behind other elements, possibly behind parent tags or due to some other rendering issue.

I've tried several troubleshooting steps, including:

Resetting VS Code.
Uninstalling and reinstalling VS Code.
Deleting the entire Code folder.
Resetting all settings and removing extensions.
Enabling/disabling word wrap (Alt+Z).
Despite these efforts, the problem persists. I'm unsure if this is a feature or a bug, but it's significantly affecting my ability to code efficiently. I would appreciate your guidance on how to resolve this issue. i dont know its a feature or its an extension or it is a setting issue.

Thank you for your assistance.

Best regards,
Zain Hayder

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.55GB free)|
|Process Argv|E:\\Zain Hayder\\Web Development\\Code-With-Harry-Sigma-Course\\Coding\\CSS --crash-reporter-id f5c09f99-18c9-4668-b11a-2e6f32d5fa10|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.2
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31118572

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe [Sticky Scroll](https://code.visualstudio.com/docs/getstarted/userinterface#_sticky-scroll) but I can't be sure because it seems you posted your issue before the screenshot upload had completed.
