### ISSUE TITLE
GPU-Process in use while idle

### ISSUE THREAD

**Issue by aaramians** [microsoft/vscode#226109]
Type: <b>Performance Issue</b>

while idle or regualr use, gpu-process is putting so much strain on the machine, that the gpu+cpu enters into thermal throttling.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.72GB (35.26GB free)|
|Process Argv|--crash-reporter-id 160decb0-3a7a-465a-b6ed-d51ed022fde9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   134	 20872	code main
    0	    29	  3108	   crashpad-handler
    0	   119	  6416	shared-process
    0	    88	  9668	fileWatcher [1]
    0	   107	 10536	window [5] (Issue Reporter)
    0	    41	 18852	   utility-network-service
    0	   335	 22520	extensionHost [1]
    0	   100	 26780	     electron-nodejs (tsserver.js )
    0	   436	 27180	     electron-nodejs (tsserver.js )
    0	    78	 27276	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    81	 27412	     "C:\Users\amegherdichiaramians\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\amegherdichiaramians\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=22520
    0	    84	 35312	     "C:\Users\amegherdichiaramians\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\amegherdichiaramians\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=22520
    0	    60	  3588	       
    0	    60	 18664	         
    0	    60	 24012	         
    0	    60	 29104	         
    0	    60	 33468	         
    0	    80	 24716	ptyHost
    1	   221	 24740	   gpu-process
    0	   333	 25684	window [1] (dataSlice.ts - ClientApp - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (dataSlice.ts - ClientApp - Visual Studio Code)
|    Folder (ClientApp): 1650 files
|      File types: bcmap(336) properties(224) tsx(223) ts(184) svg(131) js(55)
|                  map(23) pfb(20) json(14) css(14)
|      Conf files: package.json(2) launch.json(1) settings.json(1)
|                  tsconfig.json(1)
|      Launch Configs: pwa-node;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.223.0
copilot-chat|Git|0.18.2
git-graph|mhu|1.30.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-c:31118571

```

</details>

**Comment by deepak1556** [comment]
If you are still experiencing the issue with latest stable, can you share the process usage details from the os task manager.
