### ISSUE TITLE
Extension walkthrough doesn't always dynamically update

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#226184]
> Part of https://github.com/microsoft/vscode-copilot/issues/5665

Testing on Windows 11 Insiders and latest VS Code Insiders:
```
Version: 1.93.0-insider (user setup)
Commit: e1db90f81da28c0994b5d50dc2b51e964359e62d
Date: 2024-08-21T05:04:11.586Z
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.25987
```

- Install GitHub Copilot
- Extension walkthrough opens, first step is to sign in
- I sign into Copilot
- Extension walkthrough dynamically updates and sign in step disappears
- I log out of Copilot
- ❓ Sign in step doesn't reappear in walkthrough

**Comment by joyceerhl** [comment]
When I sign into GitHub, the walkthrough step to sign in does not update and disappear

**Comment by sandy081** [comment]
Sign in step reappears but it is not selected, instead the second step is.

![Image](https://github.com/user-attachments/assets/382d6622-d900-44c7-9097-8f34ab180919)

**Comment by bhavyaus** [comment]
This walkthrough step completion is controlled by a completion event. Hence the walkthrough step is not completed when it re-appears on sign-out in this case.

**Comment by bamurtaugh** [comment]
The step reappeared for me:

- Install GitHub Copilot
- Extension walkthrough opens, first step is to sign in
- I sign into Copilot
- Extension walkthrough dynamically updates and sign in step disappears
- I log out of Copilot
- ✅ Now sign in step reappears in walkthrough:
![Image](https://github.com/user-attachments/assets/7ba6c702-020d-4a49-9a4f-8358170561fd)

❔ One question: Should the step be marked as completed? I did previously complete it, and based on what @bhavyaus describes above:

> This walkthrough step completion is controlled by a completion event. Hence the walkthrough step is not completed when it re-appears on sign-out in this case.

I did meet that completion event already, so perhaps this is expected?

**Comment by bhavyaus** [comment]
>Should the step be marked as completed? 

No the step should NOT be marked. 🤔 
Just tried it my self and I see that the step is not marked as complete when it reappears.
