### ISSUE TITLE
Extension `package.json` not updated when switched to pre-release version 

### ISSUE THREAD

**Issue by soyrubio** [microsoft/vscode#226135]
I encountered a problem when a user switches to a pre-release version where `package.json` file is updated with new sidebar views (containing webviews), the views are not registered and an error `No view is registered with id...` occurs even after `Restart Extensions` is triggered. The issue is resolved after VS Code is restarted completely (quit and reopened) - only then the new sidebar views appear. Similarly, after switching back to release version and restarting extensions, the pre-release views stay visible (but empty) until VS Code is restarted again.

The tested extension is [Tools for Solidity](https://marketplace.visualstudio.com/items?itemName=AckeeBlockchain.tools-for-solidity#:~:text=Tools%20for%20Solidity%20is%20an,the%20relations%20in%20the%20code.). Tested on latest MacOS, latest VS Code 1.92.

To me it seems as if the `package.json`, where the new views are registered, is not updated on `Restart Extensions`, and thus when the code tries to access the new views they were not created in the first place.

**Comment by sandy081** [comment]
This extension does not have pre-release support. Can you please provide the extension with which I can reproduce?
