### ISSUE TITLE
terminal in new window issue

### ISSUE THREAD

**Issue by amitair** [microsoft/vscode#226162]
Type: <b>Bug</b>

I tried the terminal in new window which worked great, however when I tried to open a new terminal window in the newly opened window I receive an error:
The editor could not be opened due to an unexpected error: Not allowed to create elements in child window JavaScript context. Always use the main window so that "xyz instanceof HTMLElement" continues to work.
after i approve the error the terminal opens to the bash prompt but does not allow me to type in anything

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11980HK @ 2.60GHz (16 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (14.99GB free)|
|Process Argv|--crash-reporter-id cd96e05a-1b2e-4a0f-8965-431eca64ea22|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.28.1
better-comments|aar|3.0.2
npm-intellisense|chr|1.4.5
vscode-eslint|dba|3.0.10
gitlens|eam|15.3.0
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|11.0.0
vscode-jest-runner|fir|0.4.73
copilot|Git|1.223.1060
copilot-chat|Git|0.18.2
gitlab-workflow|Git|5.8.0
rest-client|hum|0.25.1
gitlab-pipelines|jam|1.0.12
batch-rename-extension|Jan|0.0.6
gitlab-mr|jas|1.4.3
copy-to-clipboard|joe|1.0.1
vscode-peacock|joh|4.2.2
rainbow-csv|mec|3.12.0
vscode-language-babel|mgm|0.0.40
dotenv|mik|1.0.1
vscode-docker|ms-|1.29.2
playwright|ms-|1.1.7
remote-containers|ms-|0.381.0
remote-wsl|ms-|0.88.2
vscode-jest|Ort|6.2.5
postman-for-vscode|Pos|1.2.1
vscode-yaml|red|1.15.0
vsc-ava-test-runner|scu|0.0.9
code-spell-checker|str|3.0.1
errorlens|use|3.20.0
vscode-js-console-utils|wht|0.7.0
local-history|xyz|1.8.1
pretty-ts-errors|Yoa|0.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
wkspc-ranged-t:31118572
ei213698:31121563

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by Arnaud-IFEA** [comment]
Hello, it seems to be working in VSCode Insiders

Version: 1.93.0-insider (user setup)
Commit: 336db9ece67f682159078ea1b54212de7636d88a
Date: 2024-08-30T18:47:32.318Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
