### ISSUE TITLE
cursor surrounding lines setting is not respected in a new build

### ISSUE THREAD

**Issue by alex1yaremchuk** [microsoft/vscode#226168]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version: Windows_NT x64 10.0.22631

Version: 1.92.2 (system setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Make sure your settings for cursor surrounding lines is 0 (or 1) 
2. Open any long document
3.  Try to put cursor on the topmost line
4. you cannot - it is auto scrolled to leave 5 lines above the cursor
5. it's pretty pesky

**Comment by alexdima** [comment]
This is due to sticky scrolling being enabled by default. The editor reserves 5 lines to the top for sticky scrolling.

**Comment by aiday-mar** [comment]
Duplicate. Closed in favor of https://github.com/microsoft/vscode/issues/227750
