### ISSUE TITLE
Terminal suggest: Pasting should never trigger completions

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#226187]
Steps to Reproduce:

1. Paste text into PowerShell (with Terminal suggest enabled)
2. 🐛 see batched pasting behavior

https://github.com/user-attachments/assets/c8904bb7-17e4-4840-8123-6001140afb00

**Comment by TylerLeonhardt** [comment]
maybe related to https://github.com/microsoft/vscode/issues/226186

**Comment by TylerLeonhardt** [comment]
https://github.com/user-attachments/assets/d2a2f9ec-080c-4910-84f0-6307839d810e

Another instance of this where I typed `cls` really fast, but it only types `c` and then stalls.

**Comment by Tyriar** [comment]
Haha, I think this is it triggering completions while the pasted text is being send then https://github.com/microsoft/vscode/issues/226186 kicking in. Pastes should never trigger completions so let's track that here.

**Comment by Tyriar** [comment]
When verifying make sure you're on macOS.
