### ISSUE TITLE
Right-Click XML File -> Open With -> Code (Not Working)

### ISSUE THREAD

**Issue by jtrombley24** [Microsoft/vscode#22615]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.7.0|
|mssql|ms-mssql|0.2.1|
|qub-xml|qub|1.0.3|;

---
As the title suggests, right-clicking a file and selecting 'Open With' -> Visual Studio Code doesn't seem to work.  It will open VS Code but not open the file.  It only opens an 'Untitled-1' file.  

While I was using this in BETA, 'Open With' worked fine.  After updating to the current version, it no longer opens my files using this method.

Love the program though!  

Thanks,
Jim Trombley
james.l.trombley@zoetis.com

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Can you try reinstalling? Does the problem persist?

**Comment by thech40s** [comment]
I got the same problem (same version). It only seems to affect opening .xml files.
Reinstalling and clean uninstall + reinstall didn't work. I also checked the file association in the windows registry, and xml is (correctly?) linked to "VSCode.xml"

**Comment by joaomoreno** [comment]
Can't reproduce. Please reinstall Code.
