### ISSUE TITLE
Support for JSDoc parameter properties

### ISSUE THREAD

**Issue by collinsauve** [Microsoft/vscode#22617]
VSCode does not appear to show intellisense when documenting a parameter's properties.

See http://usejsdoc.org/tags-param.html

> If a parameter is expected to have a specific property, you can document that property by providing an additional @param tag. For example, if an employee parameter is expected to have name and department properties, you can document it as follows:

> Documenting a parameter's properties

```
/**
 * Assign the project to an employee.
 * @param {Object} employee - The employee who is responsible for the project.
 * @param {string} employee.name - The name of the employee.
 * @param {string} employee.department - The employee's department.
 */
function Project(employee) {
    // ...
};
```

(note that I changed the above example to not use a prototype as that just confuses things)

- VSCode Version: 1.9.1
- OS Version: Windows 10 v1607

Steps to Reproduce:

1.  Create the above code
2.  Type `Project({ na`
3.  Intellisense should understand that you are typing the `name` property of the `employee` object, but it does not.

**Comment by mjbvz** [comment]
Thanks for the suggestion. This is currently being tracked upstream on the TypeScript side by: https://github.com/Microsoft/TypeScript/issues/11597
