### ISSUE TITLE
Extension walkthrough doesn't pop up in new profile

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#226183]
> Part of https://github.com/microsoft/vscode-copilot/issues/5665

Using Windows 11 Insiders and latest VS Code Insiders:
```
Version: 1.93.0-insider (user setup)
Commit: e1db90f81da28c0994b5d50dc2b51e964359e62d
Date: 2024-08-21T05:04:11.586Z
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.25987
```

- Create a fresh, blank Profile with no settings imported
- Install GitHub Copilot
- ❓ The Copilot extension walkthrough doesn't pop automatically

If I try with fresh user and extensions directory, the Copilot walkthrough pops up without issue, and I would've expected a Profile to also be a fresh start.

**Comment by bhavyaus** [comment]
Makes sense. I'll work on updating this scenario.

**Comment by bamurtaugh** [comment]
> Is this is walkthrough page that is mentioned in the golden scenario TPI?

@aiday-mar this is great feedback. What you see in the screenshot you shared is the README, which is different from the walkthrough the scenario refers to (supposed to be the getting started experience the completions extension contributes):

![Image](https://github.com/user-attachments/assets/c046a317-641c-4274-b4b6-3da7ef4f6dd0)

I'll make sure this distinction is clearer in the scenario doc since your question totally makes sense. And your experience (only getting README and not getting started walkthrough experience) is in-line with what I experienced in this issue.

**Comment by bhavyaus** [comment]
Thinking on this a bit more, this could be disruptive to users who have previously installed the extension, seen the walkthrough and dismissed it.
We should only show the walkthrough on first install of the extension. Closing this issue as wont-fix. Please let me know if we should reconsider.
