### ISSUE TITLE
Problems in formatting of lines (support of comments)

### ISSUE THREAD

**Issue by IvanMakarenko** [Microsoft/vscode#22610]
- VSCode Version: 1.10.2
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

1. Begin write the comment (in [phpDocumentor](https://phpdoc.org) style).
```
	/**
	 * @var string[] of supported intervals
	 */
```

2. Press enter and line will be begin from tab + space.
```
	/**
	 * @var string[] of supported intervals
	 */
	 private $whySpaceBefore;
```

I am expected to see something like this:
```
	/**
	 * @var string[] of supported intervals
	 */
	private $whySpaceBefore; // with out space before
```

**Comment by weinand** [comment]
@IvanMakarenko Are you using a php-extension for formatting php code?

**Comment by IvanMakarenko** [comment]
Even if I am turn off extensions, this problem stay. I use: PHP IntelliSence (1.1.3), PHP-Autocomplite (0.4.2), Trailing Spaces (0.2.11), other extensions don`t relate to PHP.

**Comment by AvatarWeb1** [comment]
merci

**Comment by roblourens** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/17530
