### ISSUE TITLE
File Recover

### ISSUE THREAD

**Issue by sreedeviej** [microsoft/vscode#226120]
Type: <b>Performance Issue</b>

I added a file to source control section and i accidentally deleted it. it also dissappeared from my pc ..please help me to restore it

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.86GB (0.50GB free)|
|Process Argv|--crash-reporter-id a8213740-ab69-4ba7-b834-15d1e32c7ee7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   108	  7732	code main
    0	    54	  1156	fileWatcher [1]
    0	    97	  1832	shared-process
    0	   132	  3276	window [1] (Welcome - d: - Visual Studio Code)
    3	    98	  3864	window [2] (Issue Reporter)
    0	    88	  4028	extensionHost [1]
    0	    27	  6236	   crashpad-handler
    0	    54	  9148	   window
    0	    42	 10816	   utility-network-service
    0	   137	 11384	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - d: - Visual Studio Code)
|    Folder (): 45 files
|      File types: ini(3) log(1) tmp(1) sys(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.94.0
flutter|Dar|3.94.0
debugpy|ms-|2024.10.0
python|ms-|2024.13.2024082001
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cpptools|ms-|1.21.6
java|red|1.33.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-c:31111717
wkspc-ranged-c:31118571
pme_test_c:31118331
fje88620:31121564

```

</details>

**Comment by sreedeviej** [comment]
is there any way???

**Comment by lszomoru** [comment]
@sreedeviej, here is something that you could try:
1. Create a new file with the same name, in the same location
2. Open the "Timeline" view and make sure that you have "Local History" selected
    ![Image](https://github.com/user-attachments/assets/ed962f1b-0daf-4550-9047-819a812e4ac6)
3. Do you see any "File Saved" entries? If so, clicking on them you can see the contents of the file
