### ISSUE TITLE
Terminal Suggest widget gets in the way of navigating history

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#226188]
Steps to Reproduce:

1. Have a good amount of history in PowerShell
2. hit up arrow
3. eventually one of them will cause Terminal Suggest to show which takes over the up arrow keybinding
4. 🐛 Up arrow no longer goes through history

https://github.com/user-attachments/assets/5fe90b9a-f990-4c12-85ac-3f747f4e437d

**Comment by neehhaa06** [comment]
Hello @TylerLeonhardt :)

```
Run in PowerShell:

    Set-PSReadLineOption -PredictionSource None
```

```
    Open your PowerShell profile:

notepad $PROFILE
```

```
Add the line:

        Set-PSReadLineOption -PredictionSource None
```
> Restart PowerShell and test.

> Now, the up arrow should navigate history without the suggested widget interfering.

**Comment by Tyriar** [comment]
@neehhaa06 that's pwsh's "predictive intellisense", not vscode's intellisense that @TylerLeonhardt is talking about. See https://code.visualstudio.com/updates/v1_92#_vs-codenative-intellisense-for-powershell

**Comment by Tyriar** [comment]
This shouldn't happen with the ext host API approach
