### ISSUE TITLE
TS/JS crashed 5 times

### ISSUE THREAD

**Issue by adipati27ma** [microsoft/vscode#226127]
Type: <b>Bug</b>

And not running

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Linux x64 6.8.0-40-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 4650G with Radeon Graphics (12 x 4292)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 0, 1|
|Memory (System)|13.53GB (4.91GB free)|
|Process Argv|. --crash-reporter-id cf045725-d2ad-420d-826c-ce730fd5032e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
blazor-snippet-pack|adr|2.6.1
remix-run-snippets|ami|1.2.1
laravel-extra-intellisense|ami|0.6.6
tailwindcss-extension-pack|and|1.1.4
jest-snippets|and|1.9.1
vscode-apollo|apo|2.0.1
laravel-blade-spacer|aus|2.3.0
tailwind-docs|aus|2.1.0
vscode-tailwindcss|bra|0.12.6
path-intellisense|chr|2.9.0
laravel-goto-view|cod|1.3.11
dart-code|Dar|3.94.0
flutter|Dar|3.94.0
vscode-eslint|dba|3.0.10
javascript-ejs-support|Dig|1.3.3
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.3.0
vsc-material-theme|Equ|34.5.2
vsc-material-theme-icons|equ|3.8.7
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
copilot|Git|1.223.0
copilot-chat|Git|0.18.2
live-sass|gle|6.1.2
jsx-beautify|gog|0.0.5
vscode-graphql|Gra|0.12.0
vscode-graphql-syntax|Gra|1.3.6
headwind|hey|1.7.0
vscode-es6-string-html|hjb|1.1.1
rest-client|hum|0.25.1
vscode-react-typescript|inf|1.3.1
theme-by-language|jsa|1.3.0
tailwind-sass-syntax|mac|1.3.0
vscode-discord|max|1.0.2
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
csdevkit|ms-|1.9.55
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.5
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
jupyter-renderers|ms-|1.0.19
indent-rainbow|ode|8.3.1
laravel-blade|one|1.36.1
laravel5-snippets|one|1.18.0
material-icon-theme|PKi|5.9.0
tsimporter|pmn|2.0.1
vscode-css-peek|pra|4.4.1
prisma|Pri|5.18.0
vscode-thunder-client|ran|2.24.13
LiveServer|rit|5.7.9
svg-preview|Sim|2.8.3
swdc-vscode|sof|2.7.14
html-to-jsx|sub|0.0.1
open-in-browser|tec|2.0.0
pdf|tom|1.2.2
errorlens|use|3.20.0
vscode-jss-snippets|vis|0.2.2
vscode-icons|vsc|12.8.0
vscode-wakatime|Wak|24.6.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
material-theme|zhu|3.17.2
html-css-class-completion|Zig|1.20.0
php-intellisense|zob|1.3.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-t:31118572
fje88620:31121564

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by adipati27ma** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.92.2. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

It seems that in the latest version it is safe and there are no problems, thank you for your response.

and for your information i am not using VS Code insiders build
