### ISSUE TITLE
Vscode v1.92 should use GPT-4O model

### ISSUE THREAD

**Issue by edgar1506** [microsoft/vscode#226154]
Type: <b>Bug</b>

I've just updated VSCode to v1.92. In the release notes it explicitly says:

"We've upgraded the Copilot Chat view from GPT-4-Turbo to GPT-4o, OpenAI's most powerful model to date."

However, I just asked via copilot chat and it says it's still using GPT-4-Turbo:

ME:
which AI model are you?

GitHub Copilot
I am GitHub Copilot, powered by OpenAI's GPT-4 Turbo model.

I meet all the requirements stated in the changelog:

"To use the new GPT-4o model in your IDE, ensure you are using at least the minimum version of Copilot Chat specified here:

VS Code: GitHub Copilot Chat 0.17+"

Am I missing something?

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 7730U with Radeon Graphics      (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|62.80GB (31.89GB free)|
|Process Argv|--crash-reporter-id cf75ac76-0613-4e5a-bb81-34f66cdcd2cd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Dockerfile|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 PRO 7730U with Radeon Graphics (16 x 0)|
|Memory (System)|30.75GB (26.59GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
copilot|Git|1.223.0
copilot-chat|Git|0.18.2
vscode-docker|ms-|1.29.2
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
app-studio-remote-access|SAP|1.16.0
app-studio-toolkit|SAP|1.16.2
supermaven|Sup|1.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-t:31118572

```

</details>

**Comment by lramos15** [comment]
You're not missing anything you're using 4o the model just likes to lie to you.



![Image](https://github.com/user-attachments/assets/b2c7c625-8093-499c-8799-a6a43ad40158)


Here we can see in a simple model playground it doesn't say 4o. I can assure you that you're getting 4o :)

**Comment by edgar1506** [comment]
Ok, thanks, it should deposit 1$ in a jar every time it lies ;)
