### ISSUE TITLE
Change outline default model

### ISSUE THREAD

**Issue by Evileoo** [microsoft/vscode#226129]
It could be awesome if we were able to change the outline default model like the sticky scroll (with the sticky scroll settings as shown below).

![image](https://github.com/user-attachments/assets/b6f2f31f-46d8-439a-82fa-e6e2b39ec9a8)
![image](https://github.com/user-attachments/assets/4c5001ca-0dc7-4da3-900d-47ace2ef0a85)

It would allow more control on what we want to see in the outline

**Comment by jrieken** [comment]
Can you install different extensions that could compute outline differently but there is no "default" outline (like one that's based on folding ranges)

**Comment by Evileoo** [comment]
Yeah languages extensions change the outline
But sometimes, not as you want

And I didn't find an extension that changes the outline in the way I need
