### ISSUE TITLE
Adopt File System Observer API

### ISSUE THREAD

**Issue by tomayac** [microsoft/vscode#226131]
Hey Visual Studio Code team,

This is Tom from Chrome's DevRel team. I wanted to point you at an exciting new origin trial that we run in Chrome, namely for the [File System Observer API](https://developer.chrome.com/blog/file-system-observer?hl=en). The core idea is to help IDEs like yours with their file system operations. I think currently this happens in [`workspaceWatcher.ts`](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/browser/workspaceWatcher.ts) and is based on polling. The new API could help you optimize this task:

```js
if ('FileSystemObserver' in self) {
  // The File System Observer API is supported.

  // The callback function that gets called whenever
  // a change is detected.
  const callback = (records) => {
    for (const record of records) {
      console.log('Change detected', record);
    }
  };

  const observer = new FileSystemObserver(callback); 
  // Observe a directory recursively.
  await observer.observe(directoryHandle, {recursive: true});
}
```

If this is of interest, happy to help you get started. Feel free to [reach out](mailto:tomac@google.com).

Cheers,
Tom

**Comment by bpasero** [comment]
@tomayac thanks for reaching out, we do indeed have interest in this! 

However, maybe not for our desktop experience where we need file watching support also in node.js and leverage https://github.com/parcel-bundler/watcher which is quite efficient, non-polling, leveraging OS watch mechanisms (`fsevents`, `ReadDirectoryChangesW`, `inotify`).

But VS Code for Web leverages the file system access API where we currently miss a way of implementing the `watch` method for notifying about file changes:

https://github.com/microsoft/vscode/blob/d78aaa9bed432b4407daba634816fdf67b510da5/src/vs/platform/files/browser/htmlFileSystemProvider.ts#L287-L293

Happy to integrate it there. Is there a way to sign up to the origin trial?

**Comment by tomayac** [comment]
> @tomayac thanks for reaching out, we do indeed have interest in this!

Amazing `:-)`

> However, maybe not for our desktop experience where we need file watching support also in node.js and leverage https://github.com/parcel-bundler/watcher which is quite efficient, non-polling, leveraging OS watch mechanisms (`fsevents`, `ReadDirectoryChangesW`, `inotify`).

Yes, makes sense. Node.js already can do this for you. 

> But VS Code for Web leverages the file system access API where we currently miss a way of implementing the `watch` method for notifying about file changes:
> 
> https://github.com/microsoft/vscode/blob/d78aaa9bed432b4407daba634816fdf67b510da5/src/vs/platform/files/browser/htmlFileSystemProvider.ts#L287-L293
> 
> Steps to try it out:
> 
> * open https://vscode.dev/
> * click on "Open Folder"
> * pick a local folder
> * notice how changes done outside the browser are not reflected inside the browser directly

This is the exact use case this new API proposal aims to address.

> Happy to integrate it there. Is there a way to sign up to the origin trial?

Yes, just go to the [sign up page](https://developer.chrome.com/origintrials/#/view_trial/59109745109237761) and sign up for your origin `https://vscode.dev/`. This gives you a token. Next, follow the instructions in this [article](https://developer.chrome.com/docs/web-platform/origin-trials) to integrate it in the app.

**Comment by bpasero** [comment]
@tomayac this seems to be working really great so far, in my testing 🙏 . Is there any downside from having a new `FileSystemObserver` per path to watch? This would make it easier for me to convert a change event back into an absolute path.

Work happens in https://github.com/microsoft/vscode/tree/ben/filesystem-observer.

I signed up for a origin trial but will have to integrate that into https://insiders.vscode.dev.

**Comment by tomayac** [comment]
Very excited about this new feature! Congratulations on landing it! For your question: there is some overhead if you watch each file separately compared to watching files jointly at a directory level, but the overhead should not matter in practice, or when it starts to matter, the app would probably already not be usable independent from this feature. 

Could you ping this Issue when the feature goes live on https://insiders.vscode.dev/ for testing? Thanks so much again!

**Comment by bpasero** [comment]
@tomayac got it. yeah it is live now on https://insiders.vscode.dev/ today and it seems to work pretty good, let me know otherwise!

**Comment by tomayac** [comment]
Wow, fantastic! Super cool to watch it watch the file system. I saw new file additions and file deletions and content updates right after saving in an external editor work almost in realtime, and file renames when refocusing the VS Code window. Brilliant job!

**Comment by bpasero** [comment]
Well, thanks to you and the team for providing this, having spent years and years of integrating file watching into VS Code, I know its a very hard thing to get right across all platforms 👏

**Comment by bpasero** [comment]
**Verification:**
- use Chrome or Edge latest version
- open insiders.vscode.dev and open a local folder
- make sure that changes you do to the files in the folder are reflected in the explorer view or opened editors immediately

**Comment by bpasero** [comment]
@tomayac is there a way to use the same origin trial key for insiders.vscode.dev and vscode.dev?

**Comment by tomayac** [comment]
@bpasero This should work with the checkbox checked:

![Image](https://github.com/user-attachments/assets/76598d05-9268-4445-a784-8d50cfb793b6)

**Comment by bpasero** [comment]
Ah ok, will do a new registration then with that option checked.
