### ISSUE TITLE
Editor's view should follow cursor in these cases

### ISSUE THREAD

**Issue by csalv5** [Microsoft/vscode#22611]
- VSCode Version: 1.10.2
- OS Version: Ubuntu 16.04

Jump to Bracket:
![jump](https://cloud.githubusercontent.com/assets/6254054/23906315/e04ab0d8-08cd-11e7-9037-5bcf2c548b69.gif)

Choose a completion:
![completion](https://cloud.githubusercontent.com/assets/6254054/23906418/34468a68-08ce-11e7-800e-c1881db985a2.gif)

This does not happen in Atom and Sublime.

**Comment by alexandrudima** [comment]
In the first case this appears to be fixed, but I can still reproduce for the accepting completion case:

![kapture 2018-04-17 at 15 52 35](https://user-images.githubusercontent.com/5047891/38874020-68bb4536-4257-11e8-907f-f7f6a7b9f03f.gif)
