### ISSUE TITLE
Cannot remove default prompt on inputBox

### ISSUE THREAD

**Issue by FloppyDisco** [microsoft/vscode#226100]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. createInputBox
2. inputBox.prompt = "new prompt"

no matter what you set the prompt to, or how long the prompt gets the default message "press 'enter' to confirm, or 'escape' to cancel" still appears in parentheses.

i would like to be able to remove this so that i can display a custom message with my own keybindings.

link to discussion: 
https://github.com/microsoft/vscode-discussions/discussions/1435#discussion-7074932

**Comment by TylerLeonhardt** [comment]
How would you want your users interact with your input box?

**Comment by FloppyDisco** [comment]
> How would you want your users interact with your input box?

it would be better to have the ability to put a completely custom message. For this particular case. I just want to change the description of what the enter button does. In my case, it selects the previous action instead of the current action.

**Comment by TylerLeonhardt** [comment]
We'd need API for this, the text is there so that users always know what their options are so we don't get issues saying: "how do I dismiss/accept this input?"

**Comment by FloppyDisco** [comment]
> We'd need API for this, the text is there so that users always know what their options are so we don't get issues saying: "how do I dismiss/accept this input?"

that is perfectly acceptable for showQuickInput, but i feel like the purpose of createQuickInput is to give the developer more autonomy.
