### ISSUE TITLE
Open recent project to new window in the background

### ISSUE THREAD

**Issue by njayman** [microsoft/vscode#226124]
In the welcome page, It would be beneficial if we could middle click to open recent projects in a new seperate window. Or right click will show a context menu for other actions like, "Add to workspace", "Open in new window".

Also I am new to open source development. Can i get assigned to do it?

**Comment by Sarvadnyaawaghad150503** [comment]
Assign me please, I will do it

**Comment by gjsjohnmurray** [comment]
Are you aware that the quickpick which displays when you click the "More..." link on the Welcome page gives you more options about what you can do with its entries? Though you have to use keyboard modifiers to use most of them, not mouse gestures.

**Comment by njayman** [comment]
I didn't know that. Good to know.

Well, unlike me, some people are not comfortable with keyboard shortcuts. It is not a nice experience to open File, Click "Open new window" and then select projects over and over again.

**Comment by chrmarti** [comment]
You can also left-click with `Ctrl` (`Cmd` on macOS) the recent entries on the Welcome page to open them in a new window.

**Comment by njayman** [comment]
> You can also left-click with `Ctrl` (`Cmd` on macOS) the recent entries on the Welcome page to open them in a new window.

I think this serves the purpose of this issue. but can we stop focusing to the new window opened in the settings?

**Comment by chrmarti** [comment]
@njayman Would you want this for all new windows or just those opened from the recent list? This would have to be a setting or another modifier when clicking since other users might prefer the existing behavior.

**Comment by njayman** [comment]
> @njayman Would you want this for all new windows or just those opened from the recent list? This would have to be a setting or another modifier when clicking since other users might prefer the existing behavior.

it could be a toggle flag in the setting. it will be like existing behavior by default, if user want, they can change it in the settings. or add some other shortcut like if `ctrl` + `left click` opens in new window focused, `ctrl` + `shift` + `left click` or any other combination  will open a new window without not focused.
