### ISSUE TITLE
Flaws with Git Diff of Jupyter Notebook in VSCode

### ISSUE THREAD

**Issue by wsrfad** [microsoft/vscode#226138]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Open a Jupyter notebook in a git reprository
2. Make some changes & then Run All cells
3. Now see the git diff in vscode
4. Issue : It does not allow Stage selected ranges
5. Issue : When we deselect Show Output Differences , Show Next Change moves across output differences also...

**Comment by DonJayamanne** [comment]
> When we deselect Show Output Differences , Show Next Change moves across output differences also...

this has been fixed in the latest version.
