### ISSUE TITLE
Create new tsconfig.json creates invalid tsconfig.json

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/vscode#226108]
```json
{
    "compilerOptions": {
        "module": "ESNext",
        "moduleResolution": "Bundler",
        "target": "ES2020",
        "jsx": "react",
        "allowImportingTsExtensions": true,
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "sourceMap": true
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

This `tsconfig.json` enables `allowImportingTsExtensions`, but this triggers the following error on TypeScript:

```
Option 'allowImportingTsExtensions' can only be used when either 'noEmit' or 'emitDeclarationOnly' is set.
```

Not sure what the intent was here.

**Comment by mjbvz** [comment]
Good find. We likely want to have this option on for implicit projects but not write it into a tsconfig

**Comment by rzhao271** [comment]
@mjbvz what are some verification steps for this issue?

**Comment by mjbvz** [comment]
- In the project with a single ts file and no `tsconfig`
- Click the language status indicator and select `create tsconfig`

Make sure there are no errors reported inside the config
