### ISSUE TITLE
Source Control have slowed down

### ISSUE THREAD

**Issue by shashankrunthala** [microsoft/vscode#226126]
Any save of file takes upto 20 seconds to reflect in source control. this wasn't happening two days back. Commit, pull, fetch, save everything seems to take long enough

**Comment by gjsjohnmurray** [comment]
Does adding the setting `"scm.showHistoryGraph": false` improve things?

**Comment by shashankrunthala** [comment]
Yes that worked and that map was new for me and was able to see from two three days but wasn't able to hide it. Hiding it have brought processing back to normal.
Thanks for your help.

**Comment by LucasOe** [comment]
I can also confirm that the history graph slows down SCM immensely for me. I suggest keeping this issue open until the problem is resolved.
