### ISSUE TITLE
CTRL+C Does Not Terminate Console

### ISSUE THREAD

**Issue by terryaney** [microsoft/vscode#226115]
Type: <b>Bug</b>

I upgraded from 1.92.1 -> 1.92.2

After upgrade CTRL+C no longer stopped my `BackgroundService` when it was running as a console application.

I simply created an app via `dotnet new worker --name <Project.Name>`.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.94GB (13.27GB free)|
|Process Argv|--crash-reporter-id 324c4641-8e15-4efb-9bdc-b30d565fb957|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
network-proxy-test|chr|0.0.12
vs-code-intellisense-katapp|con|1.0.5
xml|Dot|2.5.1
gitlens|eam|15.3.0
dotnet-test-explorer|for|0.7.8
copilot|Git|1.223.0
copilot-chat|Git|0.18.2
rest-client|hum|0.25.1
theme-monokai-pro-vscode|mon|1.3.2
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.5
live-server|ms-|0.4.14
vscode-speech|ms-|0.10.0
vsliveshare-pack|ms-|0.4.0
vscode-nuget-gallery|pat|1.2.1
postman-for-vscode|Pos|1.2.1
vscode-xml|red|0.27.1
command-variable|rio|1.65.0
LiveServer|rit|5.7.9
vscode-coverage-gutters|rya|2.11.1
vscode-autohotkey2-lsp|thq|2.4.9
vscode-gradle|vsc|3.16.4
vscode-icons|vsc|12.8.0
volar|Vue|2.0.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-c:31118571
pme_test_c:31118331

```

</details>

**Comment by terryaney** [comment]
Also, I have following:

Windows Terminal
Version: 1.20.11781.0

**Comment by terryaney** [comment]
One other note as well, may or may not be needed, but in addition to wanting `ConsoleLifetime` to handle the `CTRL-C`, I put my own event on `Console.CancelKeyPress` and it was never fired.  `CTRL-/` and `CTRL-Q` didn't do anything either.

**Comment by felipedrumond** [comment]
Same problem here - really annoying.

Version: 1.92.2 (system setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by legomushroom** [comment]
Wasn't able to repro this on stable 1.96.0 on Windows 11 today with cmd, powershell, and bash shells, so I assume the issue is fixed already. @terryaney please reopen if this bug still bothers you.
