### ISSUE TITLE
class Node highlighted with red line

### ISSUE THREAD

**Issue by greybax** [Microsoft/vscode#2261]
I'd like to create class Node in ES6 syntax. But IntelliSense underlined class Node with red and wrote a message **Duplicate identifier 'Node'.**

![image](https://cloud.githubusercontent.com/assets/3235047/12568893/a57547e2-c37e-11e5-8d59-f07a04213e36.png)

**Comment by jrieken** [comment]
@greybax Does the other file also contain a `Node` type? Or you are including all of `lib.d.ts` such that this collides with the DOM Node

**Comment by greybax** [comment]
@jrieken I'm not using typescript, so I haven't *.d.ts files. Also I haven't any files where I've already declared class Node. 
So it can be reproduced just create new .js file and declare class Node.

**Comment by jrieken** [comment]
We now use Salsa for this
