### ISSUE TITLE
No special highlighting for regex flags with tree sitter

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#226165]
Expected (current highlighting with text mate) : 

![Image](https://github.com/user-attachments/assets/6ed6a0d9-108f-4363-8608-7d3032fb51e2)

Actual (with tree sitter) : 

![Image](https://github.com/user-attachments/assets/2cb08f3b-6704-4014-92aa-093732bd9b1c)

Theme : light+

Version: 1.93.0-insider
Commit: e1db90f81da28c0994b5d50dc2b51e964359e62d
Date: 2024-08-21T05:04:11.586Z
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

**Comment by alexr00** [comment]
I noticed the same, thanks for filing an issue!

https://github.com/microsoft/vscode/blob/2bf25ee2fdabcbf36caf71ffe1b4d0d360ea4505/src/vs/editor/common/languages/highlights/typescript.scm#L89-L90

**Comment by ulugbekna** [comment]
> works in the playground but not here 

maybe because of different TS grammar versions used in vscode and in playground

**Comment by alexr00** [comment]
That's my suspicion as well. I'd prefer to wait for the next Tree-Sitter release to update, but since we build out of source we can always jump ahead to a specific commit if we want.

**Comment by bpasero** [comment]
It still looks like this to me in default dark theme:

![Image](https://github.com/user-attachments/assets/7b8a1914-4347-40d3-bde0-cbeea50acb63)

With

```
"editor.experimental.preferTreeSitter": [
    "typescript"
  ],
```

**Comment by alexr00** [comment]
@bpasero, it's just the flag that I fixed. Highlighting of the actual regex is not available right now.

**Comment by alexr00** [comment]
Based on your screenshot, the flag is highlighted properly. Marking as verified.
