### ISSUE TITLE
Clarification needed on license terms for VSCode server

### ISSUE THREAD

**Issue by iSuslov** [microsoft/vscode#226222]
Hi team,
I'm seeking clarification on the license terms for the VSCode server component and its usage in derivative products. The [FAQ](https://code.visualstudio.com/docs/remote/faq#_can-i-repackage-or-reuse-vs-code-server-in-my-own-public-service-offering) mentions restrictions on repackaging or reusing VS Code Server, but it's unclear if this applies to server functionality built from the open-source VSCode repository.

As I can see we have basic client server functionality open-sourced under MIT license here in this repository, however there are horrifying FAQ here: https://code.visualstudio.com/docs/remote/faq#_license-and-privacy 

Specific questions:

1. Does the restriction on building "public products or services on top of the VS Code Server" apply only to a specific product built by Microsoft, or to any server functionality derived from the VSCode repository?

2. If I build VSCode from source with basic client-server functionality, am I permitted to use this as a foundation for a commercial product?

3. Can I create a product that connects to a VSCode server, or am I required to build my own server distribution?

4. Is it permissible to build a client-server variant from the VSCode repository and offer it as a product?

5. Could you clarify the distinction, if any, between "VS Code Server" as mentioned in the [FAQ](https://code.visualstudio.com/docs/remote/faq#_can-i-repackage-or-reuse-vs-code-server-in-my-own-public-service-offering) and server functionality that can be built from the open-source VSCode repository?

Thank you!

**Comment by bamurtaugh** [comment]
Hi there, thanks for reaching out. It'd be a big help to get some more info on what type of product you're looking to build. It might be easier to discuss this in a live call - if you'd be willing to chat further, can you please send me an email brigit.murtaugh@microsoft.com?

**Comment by iSuslov** [comment]
Hey @bamurtaugh, thanks for the quick response! I'm interested in discussing this further. I'd like to gather my thoughts on the project specifics before we chat. I'll reach out via email soon with key points about what we're working on. Appreciate your help on this!
