### ISSUE TITLE
Cursor width not respected when using multiple cursors.

### ISSUE THREAD

**Issue by vtimbuc** [Microsoft/vscode#22621]
- VSCode Version: 1.10.2
- OS Version: OSX 10.11.6

![](https://vtimbuc.s3-eu-west-1.amazonaws.com/ezgif-2-1d40312820.gif)

**Comment by MikeVelazcoMtz** [comment]
Not so critical but a bug after all

**Comment by vtimbuc** [comment]
@MikeVelazcoMtz never said it was :)

**Comment by alexandrudima** [comment]
It is our intent to paint the primary cursor with a 2px width and secondary cursors with 1px. The idea is that when using multicursor, one usually wishes to do the same kind of operation on multiple locations (i.e. type the same thing in N places, etc.). The primary cursor is the one that existed when multiselection started and which will survive pressing Escape.

**Comment by MikeVelazcoMtz** [comment]
I think that if I had to see the difference between primary and secondary cursors I'd change the color of them.

Making the cursors narrower just could make them harder to see.

**Comment by vtimbuc** [comment]
@alexandrudima Yes I would expect all of them to be 2px wide, they already have a different color from the primary one and the ones with 1px are hard to see.
