### ISSUE TITLE
the color of code in my JS script is not visiblle

### ISSUE THREAD

**Issue by New-learner202** [microsoft/vscode#226204]
Type: <b>Feature Request</b>

hello , I havw written my code of JS in a separate source file but the color of code words have gone and is not visible right now except white

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by mjbvz** [comment]
Please share the code so we can investigate. An image would also be helpful

/gifPlease

**Comment by IllusionMH** [comment]
Are you using custom font? Try to reset font family setting to default
