### ISSUE TITLE
Explorer: file in `node_modules` not automatically revealed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#226226]
When I open a file from `node_modules`, it gets not revealed in explorer.

![Image](https://github.com/user-attachments/assets/0e663778-e7f3-4290-a790-8e3b1743800f)

**Comment by lramos15** [comment]
This is as designed. You will want to configure `explorer.autoRevealExclude`

People found that when navigating to imports and having the large node module structure automatically reveal itself was frustrating.

**Comment by bpasero** [comment]
Thanks, the settings work.
