### ISSUE TITLE
decreaseIndentPattern doesn't always take effect

### ISSUE THREAD

**Issue by MemoryPenguin** [Microsoft/vscode#2262]
While writing a language extension (not a server) I ran into an apparent issue with how `decreaseIndentPattern` in `IndentationRules` is applied: **it only outdents if you press enter before the matched characters**, not after (say, at the end of that line). I was expecting it to act on the entire line's text regardless of where on the line the cursor was.

Using version 0.10.6, commit a80232bbcfe8a5cdad1ebc98638673d9dcb02458. There are no errors in the developer console and I have no extensions (besides the test extension and what VS Code comes with) installed or running.

Reproduction steps:
1) Create a basic TypeScript extension. I made mine using the Yeoman generator.
2) Set it up so it adds a new language and activates when that language is selected.
3) Set that language's configuration on activation, using these indentation rules:

``` typescript
indentationRules: {
    decreaseIndentPattern: /^\s*outdent\s*$/,
    increaseIndentPattern: /^\s*indent\s*/,
}
```

4) Run the extension and select the language.
5) Type `indent` into the file (or otherwise indent)
6) Type `outdent` on a new line and press enter with the text cursor at the end of the text. Observe that it does _not_ outdent.
7) Type `outdent` on another indented line and press enter with the cursor _before_ the text. Observe that it does outdent as expected.

I threw together an [example extension](https://onedrive.live.com/redir?resid=8F34C5E85B8C95C!25522&authkey=!AI-4rLegxUxVEFA&ithint=file%2czip) that shows this issue. Here's a GIF from that:
![Example](http://i.imgur.com/OQ5JBxv.gif)

**Comment by alexandrudima** [comment]
I need to read again https://manual.macromates.com/en/appendix and confirm

**Comment by nixel2007** [comment]
+1. have this bug also (on 0.10.6)
Any chances to include it in JAN-2016 release?

**Comment by alexandrudima** [comment]
I'm sorry, we're wrapping up January today and I still have other critical issues to look at.

**Comment by alexandrudima** [comment]
I've looked again at https://manual.macromates.com/en/appendix and I think there is indeed something missing on our side - specifically our assumption that deciding what to do is localized to the current line being edited.

Considering the following rules (from their example):
```javascript
increaseIndentPattern = "^.*\{[^}\"']*$";           // intends to target lines ending in {
decreaseIndentPattern = '^(.*\*/)?\s*\}[;\s]*$';    // intends to target lines ending in }
```

Here are some examples I can think of (`|` indicates cursor when <kbd>Enter</kbd> is pressed):

```c
// A) ------------------------------
// BEFORE
int main (int argc, char const* argv[])|{
// AFTER (do nothing)
int main (int argc, char const* argv[])
|{

// B) ------------------------------
// BEFORE
int main (int argc, char const* argv[]) {|
// AFTER (indent new line)
int main (int argc, char const* argv[]) {
    |

// C) ------------------------------
// BEFORE
    if (true)|{}
// AFTER (do nothing)
    if (true)
    |{}

// D) ------------------------------
// BEFORE
    if (true) {}|
// AFTER (do nothing)
    if (true) {}
    |

// E) ------------------------------
// BEFORE
    if (true) {|x-=5;}
// AFTER (indent new line)
    if (true) {
        |x-=5;}

// F) ------------------------------
// BEFORE
        x-=5;|}
// AFTER (outdent new line)
        x-=5;
    |}

// G) ------------------------------
// BEFORE
        x-=5;
    }|
// AFTER (do nothing)
        x-=5;
    }
    |

// H) ------------------------------
// BEFORE
        if (true) {
        }|
// AFTER (do nothing)
        if (true) {
        }
        |

// I) ------------------------------
// BEFORE
        x-=5;
        }|
// AFTER (outdent current line + new line)
        x-=5;
    }
    |

// J) ------------------------------
// BEFORE
        if (true) {
            }|
// AFTER (outdent current line + new line)
        if (true) {
        }
        |
```

As far as I can tell, all would work today in VS Code except I) and J). Of interest the difference between H) and J) where the lines would match the same regexes, but differ in terms of indentation, thus producing different results.

**Comment by Allardvm** [comment]
I ran into the same issue while writing an indent-enabled extension for the Julia language. It's quite common to write:
```julia
function foo()
end
```
with a manual `[enter]` after `foo()`, followed by `end[enter]`. But because of the way this issue works out, I instead end up with:
```julia
function foo()
    end
```
With the current API it seems somewhat difficult to get the intended behavior, while, for example, Atom automatically unindents the `end` with the same `RegExp` (even before pressing `[enter]`).

**Comment by rebornix** [comment]
https://github.com/Microsoft/vscode/pull/16568 aims to mitigate this issue.

**Comment by rebornix** [comment]
@Allardvm you can now set `editor.autoIndent` to `true` in today's Insider to embrace auto indent on type. The end will decrease if you put that in your decreaseIndentPattern rule.
