### ISSUE TITLE
Have option to allow a Conditional Breakpoint to not stop execution (and/or a Logpoint to be conditional), like a conditional/action breakpoint in Visual Studio

### ISSUE THREAD

**Issue by IsaacBandVBS** [microsoft/vscode#226209]
I want to log a variable's value at a breakpoint, conditionally, and have the execution automatically continue rather than stop at the breakpoint.
As far as I know in VSCode, Logpoints do not stop execution, but can't be conditional. Conditional Breakpoints don't allow you to not stop code execution at the breakpoint.

**Comment by roblourens** [comment]
According to the debug adapter protocol, logpoints should respect the condition. What language are you debugging where you don't see this work?
