### ISSUE TITLE
Allow hiding extensions installed with an extension pack

### ISSUE THREAD

**Issue by Tedpac** [microsoft/vscode#226227]
When installing an extension pack, the list of installed extensions displays both the pack and its individual extensions. Hiding the extensions within a pack from the installed extensions list, leaving only the pack visible, would provide a more simplified user experience and a much shorter list.

One reason for this is that Visual Studio Code allows users to uninstall extensions even if they are part of an installed pack. This could lead to a user unintentionally uninstalling an extension without realizing that it belongs to a previously installed pack. Additionally, the main utility of an extension pack lies in summarizing multiple functionalities into one, but this summary is lost when all the pack's extensions are shown in the installed list. As a result, there is little difference between installing an extension pack and installing its extensions individually.

I suggest adding a boolean setting to show or hide extensions from installed packs, which would be a simple solution that offers user preference flexibility.

There was a similar issue (#141611), closed years ago.

**Comment by sandy081** [comment]
/duplicate

Please do a +1 to the original issue.

**Comment by Tedpac** [comment]
I don't agree that this is a duplicate because, as I mentioned earlier, the issue I referenced has been closed for years. Moreover, the "similar existing issues" link above is limited to **open issues**.

If this issue is going to remain closed, it would only be fair to reopen the other one (but this one has more information). Please consider this. 🙏

**Comment by sandy081** [comment]
I updated the original issue with the reasoning behind getting closed - https://github.com/microsoft/vscode/issues/141611#issuecomment-2340298151 

In brief, original issue was closed because we don't plan to address it in the foreseeable future and hence marked as out of scope.

**Comment by Tedpac** [comment]
@sandy081, thank you very much for the information.
