### ISSUE TITLE
Freeze latest version

### ISSUE THREAD

**Issue by sushant-ntt** [microsoft/vscode#226242]
Type: <b>Performance Issue</b>

I updated VS code to latest version and it si quite slow . it freezes frequently .

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1345U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.66GB (6.00GB free)|
|Process Argv|--crash-reporter-id 663fc3b4-9b67-4597-ac0d-1a35d2aa1f4c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   150	 16832	code main
    0	    89	  2200	   crashpad-handler
    0	    91	  2272	fileWatcher [1]
    0	   131	  5148	shared-process
    0	    92	  6200	   utility-process
    0	    93	  6996	ptyHost
    0	    51	  2008	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\EKUMARS29\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     6	 15556	     conpty-agent
    0	    90	  8788	   utility-network-service
    0	   108	 13316	window [2] (Issue Reporter)
    3	   260	 16896	window [1] (wdio.config.ts - afc-wdio-automation - Visual Studio Code)
    5	   185	 17928	   gpu-process
    0	   245	 18508	extensionHost [1]
    0	     1	 10992	     C:\Users\EKUMARS29\AppData\Local\Programs\Git\cmd\git.exe merge-base --octopus refs/remotes/origin/feature/DI-103 refs/heads/feature/DI-110 refs/remotes/origin/feature/DI-110
    0	    90	 11140	     electron-nodejs (tsserver.js )
    1	    99	 19200	     electron-nodejs (tsserver.js )
    0	    84	 18828	       electron-nodejs (typingsInstaller.js typesMap.js )
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (wdio.config.ts - afc-wdio-automation - Visual Studio Code)
|    Folder (afc-wdio-automation): 146 files
|      File types: json(35) ts(30) feature(7) js(5) html(4) txt(3) csv(3)
|                  css(2) yaml(1) gitignore(1)
|      Conf files: launch.json(2) github-actions(1) package.json(1)
|                  tsconfig.json(1)
|      Launch Configs: chrome(2) node;
```

</details>
<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|3.0.5
compile-ts|ani|0.1.5
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
githistory|don|0.6.20
vscode-surround-with|drc|1.2.0
prettier-vscode|esb|11.0.0
code-runner|for|0.12.2
copilot|Git|1.223.0
copilot-chat|Git|0.18.2
vscode-pull-request-github|Git|0.94.0
ts-debug|kak|0.0.6
npm-scripts|luk|1.0.0
vscode-typescript-next|ms-|5.7.20240821
tree-exporter|Tin|1.0.2
vscode-icons|vsc|12.8.0
JavaScriptSnippets|xab|1.8.0
pretty-ts-errors|Yoa|0.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-t:31111718
wkspc-ranged-c:31122780
ei213698:31121563

```

</details>

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
