### ISSUE TITLE
[Feature Request] Preview for SVG files

### ISSUE THREAD

**Issue by bastienmoulia** [Microsoft/vscode#22629]
It would be nice to be able to open an SVG as an image from its code as the preview of the markdown files.

![image](https://cloud.githubusercontent.com/assets/686196/23923928/00a5e4fc-0909-11e7-9f05-820b37f51e7f.png)

And see changes in real times when the editor is splitted.

**Comment by mjbvz** [comment]
Give this extension a try: https://marketplace.visualstudio.com/items?itemName=cssho.vscode-svgviewer
