### ISSUE TITLE
live server not showed

### ISSUE THREAD

**Issue by supriya73968** [microsoft/vscode#226245]
Type: <b>Feature Request</b>

output is not showed and live option is not showing on the screen

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by andreamah** [comment]
Is this related to an extension? Live Server or Live Preview? Please take this to the respective issue trackers:
Live Preview: https://github.com/microsoft/vscode-livepreview/issues
Live Server: https://github.com/ritwickdey/vscode-live-server/issues
