### ISSUE TITLE
Test: ESM exploration builds

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#226399]
Refs: https://github.com/microsoft/vscode/issues/160416

- [x] macOS @bhavyaus
- [x] linux @roblourens
- [x] windows @andreamah
- [x] wsl @karthiknadig
- [x] ssh @meganrogge
- [x] dev container @sandy081
- [x] web @ulugbekna

Complexity: 5

Authors: @jrieken @bpasero
Roles: Developer

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23226399%0A%0A&assignees=bpasero,jrieken)

---

**Setup: Desktop / Remote**
- install the latest exploration build from https://builds.code.visualstudio.com/builds/exploration: [`ff7a154d5e5e9034914f0466420f0f1407f0c95e`](https://builds.code.visualstudio.com/builds/exploration?commit=ff7a154d5e5e9034914f0466420f0f1407f0c95e)
- run it for testing, it should show up as orange icon
- ❤ ideally you keep using it during endgame week for selfhosting, we will keep it updated daily!

![Image](https://github.com/user-attachments/assets/1bb558d1-dc2b-489e-b90f-beffa5f799a0)

**Setup: Web**
- for testing on insiders.vscode.dev, two URL query parameters are needed:
  - `vscode-version=<commit>`: to point to the ESM enabled web bits
  - `vscode-esm=true`: to enable the server to serve ESM web bits
- use this for testing: https://insiders.vscode.dev/?vscode-version=d903f161caa4a4aa9cc965d95d24cf6704940020&vscode-esm=true
  - you will see a modal dialog confirming that version that you then press "OK"
- **Note:** if you see the workbench not opening, make sure you did not get redirected, with the 2 query params lost, just open the URL again with devtools opened and caches cleared

**Testing**
This is about exploratory testing all aspects of the build and checking for:
* things that do not work anymore, regressions
* suspicious error output in logs or dev tools that you do not see in insiders
* extensions not working anymore

**Areas to cover:**
* Editor colorization and workbench themes work
* Text Editing works fine, including text diffing and multi-diff editors
* Notebooks are functioning
* Explorer operations on files and folders work
* Fulltext search and quick open work
* Git SCM operations work from the changes view
* Extension development and debugging works (F5 on a sample extension, breakpoints are hit and tests can run)
* Command line works (passing folders/files to open, extension management)
* Telemetry is properly sent and received (please reach out for advice)
* Extension installation and management works from the UI
* Terminal works
* Settings sync works
* Profiles can be created, managed and switched to
* GH Copilot Chat is functional
* Selfhosting: keep using the exploration build for the endgame and see if you are limited in any way

**Comment by tats-u** [comment]
https://builds.code.visualstudio.com/builds/exploration looks like staff only.
Is it newer than https://github.com/microsoft/vscode/issues/160416#issuecomment-2292791157?
Which issue should we non-staffs report issues on these builds if we found a bug in them, https://github.com/microsoft/vscode/issues/160416 or here?

**Comment by bpasero** [comment]
Thanks for willing to test! Here are direct links:

```
VS Code Build: 79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b

cli-alpine-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/vscode_cli_alpine_arm64_cli.tar.gz
cli-alpine-x64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/vscode_cli_alpine_x64_cli.tar.gz
cli-darwin-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/vscode_cli_darwin_arm64_cli.zip
cli-darwin-x64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/vscode_cli_darwin_x64_cli.zip
cli-linux-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/vscode_cli_linux_arm64_cli.tar.gz
cli-linux-armhf: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/vscode_cli_linux_armhf_cli.tar.gz
cli-linux-x64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/vscode_cli_linux_x64_cli.tar.gz
cli-win32-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/vscode_cli_win32_arm64_cli.zip
cli-win32-x64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/vscode_cli_win32_x64_cli.zip
darwin: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/VSCode-darwin.zip
darwin-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/VSCode-darwin-arm64.zip
linux-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/code-exploration-arm64-1724413495.tar.gz
linux-armhf: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/code-exploration-armhf-1724413482.tar.gz
linux-deb-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/code-exploration_1.93.0-1724413576_arm64.deb
linux-deb-armhf: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/code-exploration_1.93.0-1724413558_armhf.deb
linux-deb-x64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/code-exploration_1.93.0-1724414801_amd64.deb
linux-rpm-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/code-exploration-1.93.0-1724413669.el8.aarch64.rpm
linux-rpm-armhf: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/code-exploration-1.93.0-1724413637.el8.armv7hl.rpm
linux-rpm-x64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/code-exploration-1.93.0-1724414884.el8.x86_64.rpm
linux-snap-x64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/code-exploration-x64-1724416998.snap
linux-x64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/code-exploration-x64-1724413480.tar.gz
win32-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/VSCodeSetup-arm64-1.93.0-exploration.exe
win32-arm64-archive: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/VSCode-win32-arm64-1.93.0-exploration.zip
win32-arm64-user: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/VSCodeUserSetup-arm64-1.93.0-exploration.exe
win32-x64: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/VSCodeSetup-x64-1.93.0-exploration.exe
win32-x64-archive: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/VSCode-win32-x64-1.93.0-exploration.zip
win32-x64-user: https://vscode.download.prss.microsoft.com/dbazure/download/exploration/79f3a3ad60190a7f0cc5e222f7cc1a366b6c8d3b/VSCodeUserSetup-x64-1.93.0-exploration.exe
```

**Comment by tats-u** [comment]
Thank you for providing a newer build.
I hope it make it easier for extension developers using ESM-only packages to prepare this change in VS Code.

**Comment by bpasero** [comment]
To clarify: we did not change anything for extensions, this is core only!

**Comment by tats-u** [comment]
I know the impact on extensions is just a side effect.
If the core is changed to ESM, it would be (theoretically) possible for extensions to run ESM code, right?

**Comment by bpasero** [comment]
Technically probably yes, but entirely out of the scope of this issue and not in the near future I think.

**Comment by tats-u** [comment]
> not in the near future

That's disappointing, but I hope the fix of this issue make it easier (or possible directly possible) to allow extensions consume ESM code.

**Comment by tats-u** [comment]
The following error occurs sometimes when trying to install extensions:

```
2024-08-25 18:13:46.029 [error] TypeError: Failed to fetch
    at dDs (vscode-file://vscode-app/c:/Users/tatsu/AppData/Local/Programs/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2923:39991)
    at vscode-file://vscode-app/c:/Users/tatsu/AppData/Local/Programs/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2923:41171
    at vut.c (vscode-file://vscode-app/c:/Users/tatsu/AppData/Local/Programs/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:371:52668)
    at vut.request (vscode-file://vscode-app/c:/Users/tatsu/AppData/Local/Programs/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2923:41153)
    at Aze.F (vscode-file://vscode-app/c:/Users/tatsu/AppData/Local/Programs/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:1118:167)
    at async Aze.getManifest (vscode-file://vscode-app/c:/Users/tatsu/AppData/Local/Programs/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:1116:40360)
    at async Wut.S (vscode-file://vscode-app/c:/Users/tatsu/AppData/Local/Programs/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2928:9085)
    at async Wut.installFromGallery (vscode-file://vscode-app/c:/Users/tatsu/AppData/Local/Programs/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2928:5935)
    at async vscode-file://vscode-app/c:/Users/tatsu/AppData/Local/Programs/Microsoft%20VS%20Code%20Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js:2251:33378
```

However, I was able to install them at the second trial.

**Comment by bpasero** [comment]
Please see if you can reproduce with insiders as well or not.

**Comment by tats-u** [comment]
I installed the latest Insiders and tried installing some extensions, but no "fetch failed" has occurred.
The fetch failure occurred once when I visited the detail page of an extension.

**Comment by bpasero** [comment]
If someone has trouble getting remote to work with exploration builds, https://builds.code.visualstudio.com/builds/insider?commit=4edd1ad59d7e15a3c08e7111f00a2cf3785bbe87&dev=true is an insiders build that is ESM enabled, but you need to disable auto update if you plan on using that.

**Comment by andreamah** [comment]
Everything looks good from my side- just need to check if telemetry is ingested correctly. Since there is an ingestion delay, I'll wait a few hours and then check back.

**Comment by bhavyaus** [comment]
> Telemetry is properly sent and received (please reach out for advice)

I verified by setting the log level to trace and that I saw telemetry events emitted in the output channel. How do I confirm that events were received on our end (besides looking for my events in our telemetry pipeline once they are ingested). 

Otherwise, everything looks good on `macOS` on first pass. I'll continue to selfhost through the week as my primary ID.

**Comment by meganrogge** [comment]
@bhavyaus you check for a specific event using kusto

**Comment by meganrogge** [comment]
Example: create a file with your name as the extension. Then: 

```
RawEventsVSCode
| where EventName == "monacoworkbench/fileput"
| where Properties['ext'] == ".meganrogge"
```

I still get a network error when I try this, so will wait a little longer.

**Comment by roblourens** [comment]
@meganrogge if you are getting a network error in the kusto window, you now are supposed to be on the azure vpn to access that data. I haven't set that up, I just use a devbox.

**Comment by roblourens** [comment]
I will keep selfhosting
