### ISSUE TITLE
Custom preferred inline chat position for empty notebook cell

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#226386]
The new position of the inline chat widget looks great in a normal text editor IMHO, the only catch is in an empty code cell it looks strange. Previously it renders at the top which looks much nicer, I wonder if we can have a special mode for this particular scenario.

<img width="1312" alt="image" src="https://github.com/user-attachments/assets/67f73674-8714-4b92-a793-9a3ef88d96bc">

**Comment by jrieken** [comment]
just fyi that since yesterday the zone is default (`inlineChat.startWithOverlayWidget` defaults to false) and that we might remove the content widget alltogether

**Comment by jrieken** [comment]
obsolete because the content widget is gone
