### ISSUE TITLE
Following link from Jasmine testing framework breaks search

### ISSUE THREAD

**Issue by offenwanger** [microsoft/vscode#226344]
Type: <b>Bug</b>

I am trying to debug my code using jasmine tests. The tests run fine, I click the link to go to the place of the error, but then when I try to do a search the search hangs and never completes. 

These are the links I click: 

 TypeError: mModel.getById is not a function
  Stack:
        at Object.setAttribute (file:///C:/Users/annao/OneDrive/Desktop/Moments/moments/js/pages/controllers/model_controller.js?__quibble=224:42:27)
        at file:///C:/Users/annao/OneDrive/Desktop/Moments/moments/js/pages/editor_page.js?__quibble=224:184:32

etc.

I am getting this error in the console when I try to do a search: 

  ERR file:///c%3A/Users/annao/OneDrive/Desktop/Moments/moments/js/pages/controllers/model_controller.js?__quibble%3D224 is not a descendant of file:///c%3A/Users/annao/OneDrive/Desktop/Moments/moments: Error: file:///c%3A/Users/annao/OneDrive/Desktop/Moments/moments/js/pages/controllers/model_controller.js?__quibble%3D224 is not a descendant of file:///c%3A/Users/annao/OneDrive/Desktop/Moments/moments
    at Q.createAndConfigureFileMatch (vscode-file://vscode-app/c:/Users/annao/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3161:16961)
    at vscode-file://vscode-app/c:/Users/annao/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3161:13989
    at Array.forEach (<anonymous>)
    at Q.addFileMatch (vscode-file://vscode-app/c:/Users/annao/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3161:13490)
    at vscode-file://vscode-app/c:/Users/annao/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3161:22855
    at v.forEach (vscode-file://vscode-app/c:/Users/annao/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:23:27916)
    at ne.add (vscode-file://vscode-app/c:/Users/annao/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3161:22769)
    at vscode-file://vscode-app/c:/Users/annao/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3161:29390

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.20GB (7.51GB free)|
|Process Argv|--crash-reporter-id 9bd3a49b-5f7a-403b-95d0-89ff121cdf2b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.2.0
xml|Dot|2.5.1
observable-js|Gor|0.4.37
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.5
autopep8|ms-|2024.0.0
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
pme_test_t:31118333
ei213698:31121563

```

</details>

**Comment by connor4312** [comment]
Where are you clicking the link from? A screenshot/gif might help

/gifPlease
