### ISSUE TITLE
Include explicitly committed files

### ISSUE THREAD

**Issue by that70schris** [microsoft/vscode#226321]
`search.useIgnoreFiles` is a great setting, but it would be great if it didn't also exclude files that were explicitly committed in spite of .gitignore

**Comment by andreamah** [comment]
Hmm, we rely on [ripgrep upstream](https://github.com/BurntSushi/ripgrep) for `useIgnoreFiles` functionality. I would file upstream to see if they can do that, although I'm not sure if they actually key into the git state of things. Rather, I *think* that they just read the ignore files and act accordingly.

**Comment by andreamah** [comment]
Will close this as 'not planned', since we are planning to continue following what ripgrep does.
