### ISSUE TITLE
Indentation feature request for "Space" key

### ISSUE THREAD

**Issue by vscpp** [Microsoft/vscode#22637]
- VSCode Version: 1.10.2
- OS Version: Win7/Win10

Steps to Reproduce:

1. Select multiple lines c code
2. Press "Space" key. The code are deleted. -> I just want to code indents a line, not delete code.

Will you support this feature? It's helpful for coding. Thanks.

Microsoft/vscode-cpptools extension doesn't support this feature, so file the request here.
https://github.com/Microsoft/vscode-cpptools/issues/552

**Comment by sean-mcmanus** [comment]
@vscpp said Source Insight supports this feature. I was thinking an extension could implement this via workspace/applyEdit in the didChange, but I don't think it belongs in the C++ extension.

**Comment by alexandrudima** [comment]
workaround:
* make a multiline selection
* split it into multiple cursors (shift+alt+i)
* press Home to go to the line starts
* press Space to insert a space on each line

**Comment by sean-mcmanus** [comment]
Cool. Thanks, that workaround works.

**Comment by pettomartino** [comment]
👍  vote for this feature

**Comment by usernamehw** [comment]
IDK [Indent one space](https://marketplace.visualstudio.com/items?itemName=usernamehw.indent-one-space)

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
