### ISSUE TITLE
C# / Unity code using LINQ breaks the debugger

### ISSUE THREAD

**Issue by chetan51** [Microsoft/vscode#22635]
- VSCode Version: 1.10.2
- OS Version: macOS 10.12.3

When using the Unity3D / C# debugging feature in VSCode, if you place a breakpoint inside code that is triggered by LINQ queries, Unity will pause and the debugger will hit the breakpoint, but the breakpointed line isn't highlighted and no debug information is shown in the debug panel. The only action you can take is to press continue, after which everything goes back to normal.

Outside of LINQ code, the debugger works fine.

Steps to Reproduce:

1. Write a function that is called inside of a LINQ query (such as `lead.Serialize()` in `this._leads.Select(lead => lead.Serialize()).ToList()`).
2. Inside the function, place a breakpoint.
3. Attach VSCode debugger to Unity3D and hit the breakpoint.

**Comment by weinand** [comment]
Unity3D / C# debugging is not a builtin feature of VS Code but relies on separate extensions.
Please file this issue against the extension you are using.

**Comment by chetan51** [comment]
Moved to https://github.com/Unity-Technologies/vscode-unity-debug/issues/29.
