### ISSUE TITLE
No Scrollbar Buttons in Editor.

### ISSUE THREAD

**Issue by Steviey** [Microsoft/vscode#22636]
I have no scrollbar buttons (up/down, left/right arrows, vertical and horizontal) in my editor.
Am I the only one, trapped in black magic, or is it a 'stylish' feature? 

...VS Code latest version.
...Win 7

**Comment by weinand** [comment]
@Steviey do you think that this has changed since the previous releases?

**Comment by Steviey** [comment]
I don't know. I ask to see what's the standard.

**Comment by weinand** [comment]
I've never seen scrollbar buttons in VS Code. But I'm on macOS.
But I've verified with those in the know that this is by design.

**Comment by Steviey** [comment]
Thank you, this is a big design misconception- since it simply cuts down essential IDE standard features.
May move this to feature request.

**Comment by weinand** [comment]
On macOS, no scrollbar has buttons, so at least there the point is moot.

**Comment by Steviey** [comment]
I knew Jobs forgot something. :-) 

It's impressive how many things are build with a Mac in mind, while its market share is under 3% worldwide.

 I would guess there has to have extra efforts to remove the buttons from Atom/Electron.
And this is a Microsoft product. Congratulations to the responsible designer. What's next? 
Windows Software for mice with only one button?

**Comment by weinand** [comment]
There is a general trend to have no scrollbar buttons: I just verified on Linux (Elementary OS) and Windows 10. Modern dev tools don't have scrollbar buttons, e.g. Sublime.

And who needs scrollbar buttons if we have scroll wheels and mice with 2D touch surfaces. 
I always found it painful to hit the tiny scrollbar buttons with the mouse.

(BTW, among developers the macOS market share is a bit higher than 3%:
http://stackoverflow.com/insights/survey/2016#technology-desktop-operating-system)

**Comment by Steviey** [comment]
The beauty of scrollbar buttons is, that they provide additionally to the mouse wheel option another scroll range (instantly, without an special hardware or configuration) . Vertically they scroll exactly per one line. For me this is an essential feature.

Since I only use Unix-shells without any desktops, I can't verify your Linux statement.
But everything including Visual Studio, MS Office, Notepad, Browser etc. on my Windows 10 partition which scrolls, has scrollbar buttons. The same goes for my Win 7. 

So I can't really believe that this could become a trend. 
I would say its' simply an important feature less, if not implemented.
I see no real substitution.

Don't know which numbers are right, but your developer exception seems to make sense:
https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0

Anyway, If there would be a way to write a plugin for that, I would do so if some initial related informations are provided (how this is removed/disabled etc.).

**Comment by Steviey** [comment]
For the interested researcher:
Preferences > Settings:
  "editor.scrollbar": {
      "verticalHasArrows": true,
      "horizontalHasArrows": true
     }
...will does the trick, even when it says: 'Unknown configuration setting'

**Comment by geri777** [comment]
I also miss this feature. Steviey's configuration shows scrollbar buttons, but they don't work - there's no reaction on click on the buttons. Btw. I tried with version 1.12.2

**Comment by jvincent-siplay** [comment]
I would really love arrows in the integrated terminal pane.  The mouse wheel scrolls an entire page (even though my environment settings are set to 3 lines) and the thumbnail scroller gets so tiny it becomes hard to click and precise scrolling becomes impossible.
