### ISSUE TITLE
Force Close after open 5 second

### ISSUE THREAD

**Issue by tottyunair** [microsoft/vscode#226361]
Type: <b>Bug</b>

After i open my VSCODE its force close after 5 second

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12650H (16 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.70GB (5.73GB free)|
|Process Argv|--crash-reporter-id 624c01cd-e97d-4f79-b5cf-be15c450b930|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-flutter-helper|aks|0.2.5
flutter-snippets|ale|3.0.0
flutter-widget-wrap|ami|0.0.3
ccs-flutter-color|cir|1.2.5
dart-code|Dar|3.94.0
flutter|Dar|3.94.0
vscode-flutter-i18n-json|ess|0.28.0
flutter-stylizer|gml|0.1.16
vscode-flutter-files|gor|4.9.1
flutter-intl|loc|1.19.3
flutter-tree|mar|1.0.0
flutter-snippets|Mar|1.0.5
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
awesome-flutter-snippets|Nas|4.0.1
file-and-folder-icons|nex|1.0.4
material-icon-theme|PKi|5.9.0
flutter-dart-utils|Rod|1.8.7
vscode-gradle|vsc|3.16.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-t:31111718
fje88620:31121564

```

</details>

**Comment by deepak1556** [comment]
Please share crash dumps following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report
