### ISSUE TITLE
executeDefinitionProvider action doesn't get the definition for specifier of type ImportNamespaceSpecifier

### ISSUE THREAD

**Issue by girdhariag** [microsoft/vscode#226342]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.0 (Universal)
- OS Version: macOS 13.6 (22G120)

Steps to Reproduce:
1. Try using an import statement using the `ImportNamespaceSpecifier` type. For e.g. `import * as Utils from "@/utils";`
2. Pass this function to the `vscode.commands.executeCommand('vscode.executeDefinitionProvider')` with the other necessary information.

What did we observe:
1. We do not get target definitions for the ImportNamespaceSpecifier.

What is expected?
1. To get the target uri, loc etc for the specified resource.

**Comment by mjbvz** [comment]
Can you please share a minimal, self-contained extension sample which demonstrates this. Thanks

**Comment by mjbvz** [comment]
Closing as not actionable without more info from op
