### ISSUE TITLE
Bug - Save All Files button

### ISSUE THREAD

**Issue by feidianbo** [Microsoft/vscode#22639]
When I open multiple files, such as demo.scss and demo.html, I click the 
'Save All Files' button, it will be occurring a strange thing. The content of dem.scss will be overide by content of demo.html.

- VSCode Version:1.10.2
- OS Version:10.12.3

Steps to Reproduce:

1. Open a file. (such as demo.scss)
2. Open another file. (such as demo.html)
3. Click 'Save All Files' button.

By the way, it will not be occurred every time.

**Comment by weinand** [comment]
@feidianbo VS Code does not have a 'Save All Files' button. I assume you mean the 'Save All Files' action (e.g. in the 'File' menu), correct?

**Comment by bpasero** [comment]
@feidianbo are you using the js-css-formatter extension? or what extensions are you using?

**Comment by feidianbo** [comment]
@weinand 
I means as the following:
<img width="1054" alt="jietu20170323-161500 2x" src="https://cloud.githubusercontent.com/assets/1548731/24238123/1597454a-0fe4-11e7-8601-96fca29c0232.png">

**Comment by feidianbo** [comment]
@bpasero Yes, I install some extenstions for formatting code.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
