### ISSUE TITLE
Unsupported 16-bit application. 

### ISSUE THREAD

**Issue by vikaparh** [Microsoft/vscode#22632]
Just received strange message about incompatibility.

![16bit](https://cloud.githubusercontent.com/assets/7015208/23926348/1bc0b920-08ea-11e7-836a-b8ee59c4013e.png)

- VSCode Version: 1.10.2 and 1.9.1
- OS Version: Windows 10 Enterprise 1511, OS Build: 10586.0

Steps to Reproduce:

1. Download installer.
2. Install
3. Launch

Can someone suggest a workaround?

Many thanks!

**Comment by joaomoreno** [comment]
That is odd. Is that a special Windows build?
