### ISSUE TITLE
Allow window title color to distinguish between multiple windows

### ISSUE THREAD

**Issue by osdiab** [Microsoft/vscode#22634]
I often have multiple directories open in separate VSCode windows, and wish I could at a glance distinguish between them (like with a random color present in the UI)—although the directory name is already in the title of the window, it often takes me a bit to reorient myself because there is so much text on screen already. Any suggestions on how to more easily distinguish between multiple open files/a possibility to include a feature like this?

**Comment by bpasero** [comment]
Assuming we want a cross platform solution, this requires native API to decorate the window frame color.

**Comment by electriccode** [comment]
If there are too many projects open, colouring the editor window will not work well. I think its best to have project management utility built in which can help you switch between multiple projects. Like an autocomplete for recent and active projects.

![image](https://cloud.githubusercontent.com/assets/1471581/23987075/9739c8f8-0a4d-11e7-9b8f-d1ffa26b072f.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16363
