### ISSUE TITLE
Incoming/Outgoing Not Remembering Which Branches are Hidden

### ISSUE THREAD

**Issue by MitchTalmadge** [microsoft/vscode#226376]
Type: <b>Bug</b>

1. Use the hamburger menu to hide a branch in the "Incoming/Outgoing" section of the "Source Control" panel
2. Exit and re-open VSCode, or Reload Window.

Actual: The hidden branch is visible again.

Expected: The hidden branch remains hidden.

Here's the part I am talking about:
![image](https://github.com/user-attachments/assets/2719886e-3f94-4add-b3c0-57019f4510c3)

VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|96.00GB (16.55GB free)|
|Process Argv|--crash-reporter-id 7ff71ef7-97c4-4978-8914-f65e7e9e538e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (72)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
laravel-extra-intellisense|ami|0.6.6
icons-carbon|ant|0.2.6
atlascode|atl|3.0.10
vscode-intelephense-client|bme|1.12.4
catppuccin-vsc-icons|Cat|1.15.0
npm-intellisense|chr|1.4.5
gitignore|cod|0.9.0
vscode-eslint|dba|3.0.10
composer-php-vscode|DEV|1.50.15906
javascript-ejs-support|Dig|1.3.3
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.3.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
shell-format|fox|7.2.5
codespaces|Git|1.17.2
copilot|Git|1.223.0
copilot-chat|Git|0.18.2
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.94.0
gc-excelviewer|Gra|4.2.61
todo-tree|Gru|0.0.226
jbockle-format-files|jbo|3.4.0
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
vscode-docker|ms-|1.29.2
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
azure-repos|ms-|0.38.0
hexeditor|ms-|1.10.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.2
vsliveshare|ms-|1.0.5936
sqltools|mtx|0.28.3
sqltools-driver-mysql|mtx|0.6.3
autodocstring|njp|0.6.1
laravel5-snippets|one|1.18.0
fabric8-analytics|red|0.9.5
vscode-commons|red|0.0.6
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
vscode-sort-json|ric|1.20.0
laravel-artisan|rya|0.0.31
scala|sca|0.5.7
metals|sca|1.39.0
markdown-preview-enhanced|shd|0.8.13
vscode-scss-formatter|sib|3.0.0
git-prefix|srm|1.3.2
code-spell-checker|str|3.0.1
vscode-stylelint|sty|1.4.0
even-better-toml|tam|0.19.2
vscode-status-bar-format-toggle|tom|3.2.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-icons|vsc|12.8.0
windows-nt-vscode-theme|was|0.0.12
php-debug|xde|1.35.0
php-pack|xde|1.0.3
markdown-all-in-one|yzh|3.6.2
material-theme|zhu|3.17.2

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-c:31111717
wkspc-ranged-t:31118572
ei213698:31121563

```

</details>

**Comment by lszomoru** [comment]
@MitchTalmadge, thanks for filing this issue. This milestone we have moved the history graph into a separate view called "Source Control Graph". Next milestone we will be adding back the capability to filter this new view and we will also be persisting the filter selection.
