### ISSUE TITLE
Cannot type Space in Terminal, not any character in Editor

### ISSUE THREAD

**Issue by dacengie** [microsoft/vscode#226393]
# Bug description

- Typing alphanumeric characters in Editor produces nothing: no modification to active file
- Typing Space in Terminal produces nothing
- Keyboard shortcuts work
- Typing in other local apps (Terminal, Chrome...) produces usual effect.

# How to produce

The bug happens randomly but surely some moments after starting and using VS Code.

# Expected behaviour

- Typing in Editor and Terminal produces all characters

# Log (obtained using `code --verbose --log=debug`): 

[Code.txt](https://github.com/user-attachments/files/16724663/Code.txt) (See particularly the last lines)

# System info:

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

**Comment by meganrogge** [comment]
does it happen if you reload with all extensions disabled?

**Comment by dacengie** [comment]
> does it happen if you reload with all extensions disabled?

Yes it _did_.
For un unknown reason, I do not have this problem any more now. The log message "KeyBindings dispatch" does not comeback. Maybe a problem with my Mac.
