### ISSUE TITLE
Logged out of all Microsoft accounts (MSAL)

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/vscode#226347]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.93.0-insider (user setup)
Commit: c2aa3c4625ed4b46448fa546ac5f2e93b0757718
Date: 2024-08-22T05:03:56.076Z
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.27691

After the MSAL experiment is turned on, I'm signed out of all my Microsoft accounts and need to log back in to each one.

Steps to Reproduce:

1. Turn on MSAL for the first time, whether that's through an experiment update or updating the config manually
2. Notice you're signed out of all your Microsoft accounts

(Also I'll note that while most accounts will persist after toggling this value, Sync Settings will always reset and I need to sign in again)

**Comment by TylerLeonhardt** [comment]
Sadly, MSAL-node does not provide a straightforward way to seed an auth session... so we have no choice but to take the user through fresh flows.

... at least this is a one time cost once they've moved on to MSAL...
