### ISSUE TITLE
Avoid/Undo Broken Extensions

### ISSUE THREAD

**Issue by ajackson-cpi** [Microsoft/vscode#22633]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.53|

---

Steps to Reproduce:

1. When an extension author's pushes a build that is failing, you can see it in Extensions
2. Update & it will be broken.

I would like avoidance & undo:
Avoid:  Detect the "build failing" logo on github & stop offering it as an upgrade
Undo:  Let me return to a previous extension version if the present one isn't working.

**Comment by joaomoreno** [comment]
It's the publisher's responsibility not to publish something that is broken. You should report the issue back to the extension developer so he fixes it asap.
