### ISSUE TITLE
New Windows Security dialog when authenticating (MSAL)

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/vscode#226349]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.93.0-insider (user setup)
Commit: c2aa3c4625ed4b46448fa546ac5f2e93b0757718
Date: 2024-08-22T05:03:56.076Z
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.27691

Steps to Reproduce:

When MSAL is enabled, the first time you try to log into an account, a Windows Security dialog pops up asking if you want to allow network access.
![windows-security](https://github.com/user-attachments/assets/c28e5639-be1e-4248-acb7-2d4a16250e70)

1. Enable MSAL for the first time
2. Try logging into an account
3. Observe modal dialog

**Comment by TylerLeonhardt** [comment]
Fixed upstream here: https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/7268

**Comment by TylerLeonhardt** [comment]
Steps to verify (only if you've never done MSAL-based Microsoft auth before):
* [Enable MSAL](https://vscode.dev/redirect?url=vscode-insiders://settings/microsoft.useMsal)
* Reload VS Code
* Log in with Microsoft into an extension or feature (Settings Sync, Remote Tunnels, Azure Repos, Azure Resources... etc)

You should not see the dialog shown above.
