### ISSUE TITLE
Unable to open repository

### ISSUE THREAD

**Issue by SimardeepSingh-zsh** [microsoft/vscode#226377]
Type: <b>Bug</b>

Screenshot -> ![Screenshot 2024-08-22 193427](https://github.com/user-attachments/assets/106f8790-d6c2-474d-9469-e533137b46ca)

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 6800HS with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.26GB (21.72GB free)|
|Process Argv|--crash-reporter-id d1be1930-8f10-41b7-ba45-4bb1c4d8d739|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
amazon-q-vscode|ama|1.22.0
aws-toolkit-vscode|ama|3.21.0
codium|Cod|0.9.13
codespaces|Git|1.17.2
copilot|Git|1.223.0
copilot-chat|Git|0.18.2
remotehub|Git|0.62.0
vscode-pull-request-github|Git|0.94.0
terraform|has|2.32.2
vscode-azureresourcegroups|ms-|0.9.2
vscode-azureterraform|ms-|0.3.2
vscode-docker|ms-|1.29.2
vscode-kubernetes-tools|ms-|1.3.16
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
azure-account|ms-|0.12.0
azure-repos|ms-|0.38.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.2
vscode-yaml|red|1.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31123313
ei213698:31121563

```

</details>

**Comment by lszomoru** [comment]
@SimardeepSingh-zsh, could you please describe how you are opening the repository?

**Comment by SimardeepSingh-zsh** [comment]
It was a bug. I was not able to move further, I was just using a remote repository but after restarting the system and even reinstalling vscode. Now, I'm able to work. Thanks :)

**Comment by lszomoru** [comment]
Thanks for the update! I will go ahead and close this issue.
