### ISSUE TITLE
[Feature Request] - Programmatic Access and Switching of User Profiles via Extension API

### ISSUE THREAD

**Issue by ondrovic** [microsoft/vscode#226355]
Objective:

Develop a programmatic interface that allows for the retrieval and management of user profiles within the application. The desired functionality includes:

 * Get Current Profile: A function to retrieve the currently active user profile.  - something like: `vscode.user.profiles.getActiveProfile()`
 * Set Current Profile: A function to set or change the active user profile.  - something like: `vscode.user.profiles.setActiveProfile(profileName string)`
 * Get All Profiles: A function to retrieve a list of all available user profiles.  - something like:
 `vscode.user.profiles.getProfiles(): string[]`

Context:

This functionality is part of an extension I am developing to automatically switch user profiles based on specific criteria or triggers. The goal is to make it easier for developers working in multi-stack workspaces to efficiently switch profiles based on the current tech stack or language. While the core logic for detecting and switching profiles automatically is in place, I need to implement the ability to programmatically change profiles. This will enable seamless profile management, allowing developers to transition smoothly between different environments and toolsets based on the active language or framework.

[Auto Profile Switcher Extension](https://github.com/ondrovic/auto-profile-switcher)

If this is something that cannot be exposed via the extension api, would it be possible to bake in the ability to do so?

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/211890
