### ISSUE TITLE
Better rendering of inline chat anchors

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#226375]
Two feature request/issues with inline chat anchors:

- Support rendering the workspace relative path instead of just the file name. Showing just the file name can make it difficult to understand what file is being talked about 

- Support rendering the file path as inline code instead of as normal text as this makes it more clear it's not just text. Maybe we can just do this by default

Both could be supported if the chat anchor let you specific the text value of the anchor. In markdown syntax, that would be: `[text](dest "title")`. Right now the text is always computer by VS Code

**Comment by roblourens** [comment]
I think #1 should just be done automatically as a resource label. VS Code is best at computing that, not the extension, IMO. I worry about it being very long when you don't need that context, though? For the second, you just mean as a codespan with backticks?

**Comment by mjbvz** [comment]
Thanks, will take a look at adopting `ChatResponseAnchorPart` in copilot chat and tweaking our rendering in core. We can try these changes out and see what we think in the UI
