### ISSUE TITLE
commanding ejs commands

### ISSUE THREAD

**Issue by FarisShamsudeen** [microsoft/vscode#226388]
Type: <b>Feature Request</b>

there is an issue occuring while commanding ejs files. it commands everything except ejs commands. it would be a great improvement for us developers to if you include this . thank you

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Linux x64 6.10.3-200.fc40.x86_64
Modes:

**Comment by lramos15** [comment]
What do you by EJS commands and commands not working there? Can you elaborate a little please
