### ISSUE TITLE
Can't complete school assignments

### ISSUE THREAD

**Issue by ashgainesLTC** [microsoft/vscode#226496]
Please help, I can't figure out why this is happening I have reached out to my professors and we are at a loss. 

Issue 1. The "Run test for task" is not working it spins and then says nothing and when I check it says I have tried zero attempts. 
Issue 2. It will not run the code, it goes to a page that says "This content can't be displayed, please contact site manager" or something like that. 
Issue 3. When I have put in all the code and KNOW that is correct by saving it to an HTML file and opening in Chrome and it works perfectly. I try to calculate grade and it returns with a zero. 

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by RedCMD** [comment]
you'll need to contact the only of your extension.
what extensions does your school install?

**Comment by ashgainesLTC** [comment]
I don't believe I have had to install any extensions, I am in another class that uses this same process and those assignments go through without a hitch. Below is what I have tried to correct this. 
Things I have tried: 

Ran system compatibility - Good

Ran browser compatibility - Chrome - Good

Cleared browser cache 

Restarted browser

Rebooted computer 

Added suggested sites from Cengage and Github support to allow pop ups, cookies and JavaScripting. Here is the link to the support site I followed. https://help.cengage.com/mindtap/mt-student/common/change-chrome-settings.html

Rebuilt the Container - Link here: https://help.cengage.com/mindtap/mt-student/mindtap/tbs-coding-labs-rebuild.html

Tried a different assignment to make sure it wasn't just the one. 


Any suggestions or help would be greatly appreciated!

**Comment by roblourens** [comment]
I don't know what `Run test for task` is, are you sure you aren't using an extension?

> It will not run the code, it goes to a page that says

It sounds like this is an issue with your browser or network configuration, vscode doesn't run your webpage

**Comment by ashgainesLTC** [comment]
No Extentions, I will try to be very detailed here so you can see the process, maybe that will help. I have attached a document and a video showing what is happening. There is a video as well to show that the "run test for task" just spins and doesn't complete. 
[Can't complete task.docx](https://github.com/user-attachments/files/16763742/Can.t.complete.task.docx)

https://github.com/user-attachments/assets/f511d284-17e1-4df7-9c66-429661eefacf

**Comment by roblourens** [comment]
I don't know what this "Companion" is, this must be something from your school
