### ISSUE TITLE
Support disabling python linters via configuration setting

### ISSUE THREAD

**Issue by Spitfire1900** [microsoft/vscode#226437]
As a contributor to multiple python projects I need to be aware of which linters a project uses. Contributions to a project to resolve linting errors for a linter the project does not use are generally not accepted unless they can be associated with a known bug.

The [current Python linter docs](https://github.com/microsoft/vscode-docs/blob/91a0d17ea355b826ac1c97c694ba76d0b3fa399c/docs/python/linting.md?plain=1#L52) note:
> Linters, if installed, are enabled by default. You can disable them by [disabling the extension](/docs/editor/extension-marketplace.md#disable-an-extension) per workspace.

Remembering to enable/disable linter extensions for a specific workspace This is a much less friendly DX experience than the obsolete
```json
"python.linting.pycodestyleEnabled": false,
"python.linting.pylintEnabled": true,
"python.linting.enabled": true,
```
configuration that existed previously.

Please provide a way to remark which linters should be enabled in a workspace as a configuration setting if multiple linters are installed simultaneously, i.e. as a `disabled` section in `.vscode/extensions.json` or as block in `.vscode/settings.json` like:

```json
 "[python]": {
        "editor.enabledLinters": [
            "charliermarsh.ruff",
            "ms-python.pylint"
        ]
}
```

**Comment by Spitfire1900** [comment]
This is a similar feature request to https://github.com/microsoft/vscode/issues/40239

**Comment by sandy081** [comment]
Please file the issue against the python extension.

**Comment by Spitfire1900** [comment]
https://github.com/microsoft/vscode-python/issues/22607 is the associated vscode-python issue.
