### ISSUE TITLE
HTML
Meu VSCode não abre pra digitar em HTML, mas em outras linguagens pra colar ele abre, preciso de ajuda.

### ISSUE THREAD

**Issue by LeandraFernanda** [microsoft/vscode#226432]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by tcodes0** [comment]
translates to: vscode does not open to type in HTML, but in other languages when pasting it opens, need help

**Comment by aeschli** [comment]
Sorry, I don't know what you mean/ Please provide more information. The best is to provide detailed steps and sample code.
Explain what you see and what you expect. Screenshots are also very helpfull.
