### ISSUE TITLE
Hover variable value disappears on key down

### ISSUE THREAD

**Issue by capegreg** [microsoft/vscode#226474]
Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Hover variable.
2. Click inside hovered value.
3. Select any amount of the value.
4. Press Ctrl-C to copy value - key down event is triggered.
5. Hovered value closes before it can be copied to clipboard.
6. Repeat as many times as you want!
7. Copying hovered values worked perfectly in previous versions of VSCode
8. Other bugs have been reported on the exact same issue.
9. https://github.com/microsoft/vscode/issues/224230
10. https://github.com/microsoft/vscode/issues/211917

![hover-copy-value](https://github.com/user-attachments/assets/03722519-aeca-4b29-8115-ff1490a170c6)

**Comment by aiday-mar** [comment]
Hi are you debugging the code when doing this?

**Comment by connor4312** [comment]
I'm not able to reproduce this, please take a recording with "Toggle Screencast Mode" so we can see the keybindings VS Code is receiving

**Comment by connor4312** [comment]
Ah, the key is to move the mouse while the key is held.
