### ISSUE TITLE
Can't install 'GitHub Copilot Chat' extension in VS Code Insiders

### ISSUE THREAD

**Issue by sergei3000** [microsoft/vscode#226468]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.0-insider (Universal)
- OS Version: MacOS Sonoma 14.5 (23F79)

Steps to Reproduce:

1. Try to install GitHub Copilot chat extension in VS Code Insiders
2. See the message "Can't install 'GitHub Copilot Chat' extension. Extension is using an API proposal 'lmTools' that is not compatible with the current version of VS Code."

<img width="283" alt="image" src="https://github.com/user-attachments/assets/12374698-71bb-4d8a-aa96-cd26fd28679e">

**Comment by roblourens** [comment]
Is this still happening? Maybe there was a short window where the vscode and extension versions were out of date. Should be in sync now.

**Comment by tachun** [comment]
I have the same issue as well
```
Version: 1.93.0-insider (Universal)
Commit: c2aa3c4625ed4b46448fa546ac5f2e93b0757718
Date: 2024-08-22T05:03:56.076Z (2 days ago)
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0
```

**Comment by sergei3000** [comment]
@roblourens yes, it is still happening for me. I have the latest VS Code Insiders version available to me.
<img width="267" alt="image" src="https://github.com/user-attachments/assets/6eb51787-f26f-4b36-b2b7-1ebffc0d4eb8">

**Comment by roblourens** [comment]
And you're trying to install the pre-release version of the extension? Can you confirm the version info of vscode and the version number of the extension that you see?

**Comment by roblourens** [comment]
Actually we can merge this issue into https://github.com/microsoft/vscode-copilot-release/issues/1452

**Comment by LoganRupe** [comment]
Same issue also:
```
Version: 1.93.0-insider (Universal)
Commit: c2aa3c4625ed4b46448fa546ac5f2e93b0757718
Date: 2024-08-22T05:03:56.076Z
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

GitHub Copilot Chat `v0.20.2024082301 (pre-release)`
