### ISSUE TITLE
Source Control Graph: right-hand badges collide with actions location

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#226429]
Already discussed in standups, the indicators for current commit and remote commit are nice but I think conflict with typical actions location in trees/lists there:

![Image](https://github.com/user-attachments/assets/2534f98d-8793-4b80-8429-1a037f77591c)

Maybe we can find some other way to distinguish this.

//cc @daviddossett

**Comment by lszomoru** [comment]
Absolutely. Would love to get @daviddossett thoughts on this...

**Comment by bpasero** [comment]
An idea would be to adopt what search view does: show a pill-shaped badge with the name of the branch:



![Image](https://github.com/user-attachments/assets/cd350578-9bb0-4050-97a9-4f2fc4b644d9)

**Comment by lszomoru** [comment]
Here is a screenshot (still right aligned but you can imagine how this would look like):

![Image](https://github.com/user-attachments/assets/f6a7d8ca-da26-47eb-820d-bd41637141e1)

**Comment by daviddossett** [comment]
These still look like clickable buttons to me. Especially when they are more rectangular in shape, which is what I currently see in insiders. Is the color really needed? The muted grey examples that I see rendered in the hover feel less clickable and more badge like, which feels more appropriate.

**Comment by gjsjohnmurray** [comment]
@daviddossett I like that the colors reinforce the significance of the line colors.

**Comment by lszomoru** [comment]
The color indicates that it is a reference that was used as a starting point to render the source control graph. The grey references point to history items that are part of the graph but they were not used as starting points. By default these are hidden (they are present in the hover) and their visibility can be controlled using the `scm.graph.badges` setting.

> These still look like clickable buttons to me.

Thanks for bringing this up as this is something that I really need your guidance on. Imagine that we have an action to "Fetch origin/main" that is specific to one of the references shown in the graph. Where would you expect such an action to show up? My idea was to make these clickable and then show these "reference actions" in the context menu. We have precedence for this:
1. In the Settings editor the "gear" action opens a context menu with actions
2. In the Problems view the "filter" actions opens a context menu with actions
3. In the Extensions viewlet the "filter" actions opens a context menu with actions

@daviddossett, would this be acceptable? Any other suggestions? Thank you!

**Comment by daviddossett** [comment]
Wouldn't we render the actions as icon buttons a specific list item? 

A random example but just to illustrate the point. I think in this case the badge hides on hover and is replaced by the action. Not sure if that would apply here but was one pattern that came to mind. 

![Image](https://github.com/user-attachments/assets/48bd5c19-ea23-4dc7-a01e-72b6343a6cd1)

**Comment by lszomoru** [comment]
I think that the problem that we are facing is that the action in question is specific to a particular reference. There can be multiple references on the same row so we need a way to "anchor" the action to a particular reference. Yes I full understand that this might be "outside the box" as we do not have colored actions anywhere in the workbench...

**Comment by lszomoru** [comment]
Closing as we have adopted badges for the branches/remote branches/tags.
