### ISSUE TITLE
something wrong when using terminal

### ISSUE THREAD

**Issue by 306414383** [Microsoft/vscode#22644]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.15055
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|togglehs|bbenoist|0.1.2|
|head-file-guard|bjr|0.0.2|
|vscode-astyle|chiehyu|0.6.2|
|vscode-markdownlint|DavidAnson|0.7.0|
|python|donjayamanne|0.5.9|
|code-runner|formulahendry|0.6.13|
|CppSnippets|hars|0.0.7|
|code-guid|jammerware|1.0.1|
|Go|lukehoban|0.6.55|
|MagicPython|magicstack|1.0.7|
|cpp-symbols|mirkoh|0.0.1|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.10.3|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|ntc-docker-workshop-support|ntc|0.1.0|
|java|redhat|0.0.11|
|python|tht13|0.2.3|
|go|TwentyChung|0.0.1|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.3|;

---
![image](https://cloud.githubusercontent.com/assets/18328768/23933862/6c3e1d56-097c-11e7-96b5-f7f872ef8779.png)
![image](https://cloud.githubusercontent.com/assets/18328768/23933876/8898d6a8-097c-11e7-9a76-a0396df34273.png)

Steps to Reproduce:
I am using windows insider 15055. 
1.When I using terminal , it shows like 
![image](https://cloud.githubusercontent.com/assets/18328768/23933876/8898d6a8-097c-11e7-9a76-a0396df34273.png)
2.But when I using bash or python shell with this terminal it comes to normal.
![image](https://cloud.githubusercontent.com/assets/18328768/23934004/3391986a-097d-11e7-95e3-8d18bfa593e1.png)
![image](https://cloud.githubusercontent.com/assets/18328768/23934050/7b78239c-097d-11e7-9453-5c3e6b644a87.png)
![image](https://cloud.githubusercontent.com/assets/18328768/23934058/84cf66d0-097d-11e7-94d3-cf924703cc82.png)
![image](https://cloud.githubusercontent.com/assets/18328768/23934061/8b15398e-097d-11e7-8b64-b1a2da086c14.png)
![image](https://cloud.githubusercontent.com/assets/18328768/23934064/94737a22-097d-11e7-8091-b0332561a351.png)

3. If I exit it goes wrong again.
![image](https://cloud.githubusercontent.com/assets/18328768/23934013/4477f1ce-097d-11e7-8140-b42945cbde05.png)
4.From the pictures from 2,I think it may be caused by screen cache?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
