### ISSUE TITLE
Debugging OSS builds fail after 3-7-17 master branch code, silent failure, cannot breakpoint

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#22642]
Development Environment:

OS: Windows 7 Professional SP1 (VM under OSX)
Python: ActiveState 2.7.5

Visual Studio 15 Community \ C++ Tools \ SDK 8.1
VS Code: 1.10.2 (Code OSS Build environment)
VS Code Insiders 1.11.0 3-13 build: (Test environment)
Chrome Debugger Extension 2.6.0

Node: 6.9.1
NPM:  3.10.8

Debug Issue:

I have multiple local repositories for VSC code source trees.
I have done this to keep things separate while experimenting and learning.
the problem I am having is that only one local repository of VSC
can be debuged. I have three repositories all that can Build
and successfully execute. all have changes and some debug output
the launch files are all the same an original from the VSC clone.

if I launch the debugger with breakpoints in my main repository
the code launches and debugging will successfully work including breakpoints.

if I launch any other code from another repository, the OSS Dev
version launches but the debugger shows no output in the debug output
window and breakpoints are never hit. No debug errors our ever displayed
the debugger buttons appear as normal.

I'm thinking that there is something non- volatile saved by the one
working repository that interferes with the others. I have tried
full cleans changing names in product.jason without success.

I do think the one working repository was the first I did a win32-package
operation. One of the last tests was to do a clean of the Win32 package.
That still did not work.

I don't know how to get anymore log info as the debug output
is totally blank. And the builder works just fine.

Update:

- did exact folder copy of working repository - this works and dbg works correctly
- did fresh clone of master vsc in fresh repository/folder - build and execute okay
cannot debug - no errors F6 to pause process takes a long time but finally stops in
net.js - no source debugging/or error log output

- found I had another repository where debugging works , was cloned from 2-24-17
- repository clone from 3-1 works, each repository 3-10 and my later forks
all will not work with dbg but build and execute

Thanks
Christopher

**Comment by cleidigh** [comment]
just for clarification , problem occurs with both release and insiders
VS Code: 1.10.2 (Code OSS Build environment)
VS Code Insiders 1.11.0 3-13 build: (Test environment)
Chrome Debugger Extension 2.6.0

issue started with master branch sometime between 3-1 and 3-10

**Comment by bpasero** [comment]
@cleidigh to be clear, things work fine as soon as you stop debugging the one workspace and start from the other? this only happens when you debug multiple at the same time?

**Comment by weinand** [comment]
@cleidigh what exactly are you debugging? There are multiple launch configuration in VS Code's launch.json. Which one are you using?

**Comment by cleidigh** [comment]
@bpasero 
@weinand 
@joaomoreno 

sorry if my initial post was a bit of a red herring
also my updates may not have been clear I was working
until six a.m. on this...

I think I have a better understanding and narrowing down
of the issue/introduction point.

First I do not think this has anything to do with multiple
repositories (though I do up a question of overlapped registries)

Current Summary:

After having issues debugging my later repositories
I did a binary search/build/debug test on commits
and tags from 3-2 up to and including the insiders
commitment from last night.

Each test was the following:

Clean repository, check out new commit, build, test, debug

git clean -xfd
(check out next test commit eg)
git checkout -b 3-14-Insiders 6a002910356c6e087dd93e819e4ad54c68b9857a

.\scripts\npm install
.\scripts\code install

After successful compilation:

- launch Code OSS Dev normally with .\scripts\code
- verify normal execution
- close development Code
- set breakpoint in toggleSidebarVisibility.ts
(easy visible location/operation)

(line 33)

	public run(): TPromise<any> {
		const hideSidebar = this.partService.isVisible(Parts.SIDEBAR_PART);
*		return this.partService.setSideBarHidden(hideSidebar);
	}

- Using the current unmodified branch/commitment
	start the debugger using Launch VS Code (unmodified from launch.json)
- In all scenarios the development VSC gets launched
	and is usable. if I add a single console output line
	before the breakpoint I can see this in the debug console
	of the test code.
- in successful commits the breakpoint is hit when In
	toggleSidebarVisibility also the debug console output
	in the development/debugging VSC shows output

- the failure mode still launches the correct executable,
	the debug progress bar is normal, and no errors are displayed
	but the debug console output shows absolutely nothing
	and breakpoints are never hit

The list of branches/commits I tested following

  1.10.1        653f8733d Bump version
  1.10.2        8076a19fd debug: save all untitled non dirty files before debug start
  3-14-Insiders 6a0029103 bump node-debug2
  3-2           5790f031d Move LayoutProvider to /common/
  3-5           3b16023c4 Clean up webview click handler
  3-6           0106ab2e3 Merged in translations
  3-7           0529b5c6b Merge remote-tracking branch 'origin/master' into tyriar/21934
* 3-7-3338bf    3338bf2fc :zap: spawn shared process after first workbench window
  3-7-3ae62a    3ae62a8d8 debug: introduce map for sources, remove reference from source uri in workbench
  3-7-a39a0f    a39a0f2e1 :zap: shell should wait for shared process to be up and running
  3-7-c2cb72    c2cb72d86 debug: fix type when executing add configurations command
  master        6a0029103 [remotes/origin/master: behind 26] bump node-debug2
  origin/master 49129d126 Fix Webview scroll position preserve broken (#21531)

As per the testing above the problem appears at commit

3-7-3338bf fails
3-7-a39a0f success

The same problem persists in the current insiders build from last night
I have not looked at the files yet, but I'm sure it's beyond my pay grade

Hopefully this is detailed enough (or perhaps too detailed)
but I wanted to do my best especially as I'm new to git.

Christopher

**Comment by cleidigh** [comment]
okay, I think I found the problem

the spawn of a shared process addressing issue #22091 somehow causes the debugger
to not communicate or show errors.

if I commented out this spawn request , #263 main.ts then the debugger works


		// Install Menu
		instantiationService2.createInstance(VSCodeMenu);

		// Start shared process here
		sharedProcess.spawn();
	});
}

I assume the non- shared process prior to this edit allowed the debugger process
normal communication (I don't pretend to know how...)

but this single line will create/remove the problem...

Christopher

**Comment by bpasero** [comment]
@roblourens isn't this the same issue or related to https://github.com/Microsoft/vscode-chrome-debug/issues/382 ?

**Comment by roblourens** [comment]
Yeah, it's the same as that. Sorry you had to go through that long analysis @cleidigh. 

Workaround:
Run the "Launch VS Code" debug config
Then, run the "Attach to VS Code" debug config which will attach to the renderer process.

Working on a better solution in the chrome-debug issue.

**Comment by weinand** [comment]
@cleidigh thanks a lot for spending so much time on this.

It would have helped immensely to clearly state what exactly you are debugging and what debugger is involved (this is the 'type' attribute in the launch config).

The 'type' determines how we investigate and what developers are dragged into the investigation.

**Comment by cleidigh** [comment]
@weinand

Not a problem, as always chasing bugs makes you learn the most - favorite pastime of mine ;-)
I'm hoping to be able to contribute to both accessibility(need of mine)
and communication code (my main software and firmware focus)...

I realize the first post did not specify the launch config - sorry about that. I did think
I was clear about debugging a VSC OSS build , hopefully my follow-up was clear.

Anyway:

- read the @isidorn  issue thread #382 for chrome debug - never searched that project
- does appear related/same - discussion on shared process clearly of issue
  as I can solve my problem as described before without the shared process spawn @joaomoreno 
  I don't mean to imply that is a solution without potential other problems
  but it does enable debugging and breakpoints.


- Doing @roblourens  suggested workaround still does not work:

	Launch VSC then Attach VSC
	(have to stop the debugger after launch to be able to attach)
	Tried .\scripts\code then Attach
	still does not work, again silent failure

- Tried @bpasero  ToggleShareProcess comment , still could not hit breakpoints
	but maybe I don't know the sequence for this
	I did Launch VSC, toggle share ToggleShareProcess in OSS
	stopped debugger,  then Attach VSC
	still no breakpoints hit


- am I missing something? how can I help?

 Christopher

**Comment by weinand** [comment]
@cleidigh please fix the link to the 382 chrome issue above, because it ends up in the wrong repo which is confusing.

**Comment by roblourens** [comment]
> (have to stop the debugger after launch to be able to attach)

Don't stop the debugger. Otherwise you'll attach to the shared process again. You can run two debug configs at once.

**Comment by cleidigh** [comment]
@weinand 
sorry, could not figure how to reference other project issue - copy of URL seems to work ;-)

**Comment by cleidigh** [comment]
@roblourens 
Thanks - tried that - had figure out to use the icon F5 does not seem to work when a session is already
started...

Attach VSC after Launch throws the following error:

[C:/Users/Christopher Leidigh/.vscode-insiders/extensions/eamodio.gitlens-2.12.0]: Sorry, but currently only the 'navigation' group of the 'editor/title' menu supports alt-commands
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2601  for  bookmarks.toggle
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2602  for  bookmarks.jumpToNext
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2600  for  bookmarks.jumpToPrevious
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2597  for  typescriptHero.showCmdGui
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2599  for  typescriptHero.resolve.addImport
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2605  for  typescriptHero.resolve.organizeImports
[Extension Host] [C:/Users/Christopher Leidigh/.vscode-insiders/extensions/eamodio.gitlens-2.12.0]: Sorry, but currently only the 'navigation' group of the 'editor/title' menu supports alt-commands
[Extension Host] vscode-icons is active!
[debugger-for-chrome] Error processing "attach": TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:87:11)
    at Object.urlParse [as parse] (url.js:81:5)
    at LoggingSocket.initAsClient (C:\Users\Christopher Leidigh\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-2.6.0\node_modules\ws\lib\WebSocket.js:597:23)
    at LoggingSocket.WebSocket (C:\Users\Christopher Leidigh\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-2.6.0\node_modules\ws\lib\WebSocket.js:79:18)
    at LoggingSocket (C:\Users\Christopher Leidigh\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-2.6.0\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeConnection.js:16:9)
    at utils.retryAsync.catch.then.wsUrl (C:\Users\Christopher Leidigh\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-2.6.0\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeConnection.js:69:28)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by roblourens** [comment]
Yeah, there is an issue in the chrome debugger when you try to launch without setting the url field. I pushed a fix for it yesterday, so it should work if you sync again.

**Comment by cleidigh** [comment]
Perfect! works like a charm thanks !!

As a voice programmer only the double launch changes add up. 

can I do a prelaunch task for the first part?
or maybe make a task with the two dbg commands in task.json ?

**Comment by weinand** [comment]
@cleidigh try multi target debugging: https://code.visualstudio.com/updates/v1_8#_multitarget-debugging

**Comment by cleidigh** [comment]
compounds...awesome!

added

"compounds": [
        {
            "name": "L/A VSC",
            "configurations": ["Launch VS Code", "Attach to VS Code"]
        }

almost works, I think there's a timing issue. Debug Launch VSC works
but the attach never occurs like when I do the two operations separately.
However , if I do a manual attach after the compound L/A VSC the attached completes

**Comment by cleidigh** [comment]
@weinand 
@bpasero 
@roblourens 

very cool, got it to work:

- compound debug launch task as above
- added prelaunch task to Attach to VS Code (tasks.json task for a 2.5s delay batch file)
- seems to sequence okay this way 
- tried timeout, did not work but was not getting timeout errors anyway

How about adding a prelaunchDelay option?

**Comment by roblourens** [comment]
Cool, glad that works. 

Ideally, I will come up with a good fix for this so we don't need a hack like prelaunchDelay :)

**Comment by cleidigh** [comment]
would that really be a hack?
for the compound launch actions one could imagine a certain task needing a lot of startup time
and thus a delay capability anywhere in the chain might be useful, no?

**Comment by isidorn** [comment]
@cleidigh we already have some feature requests for the delay, though if I am mistaken feel free to open a new one.

**Comment by cleidigh** [comment]
@isidorn 
@roblourens 

Once I finish my current keyboard window expansion feature, I could look into this if all agree...

In the meantime question - any reason the following compound launch should not work?
no errors, but attach does not complete

"compounds": [
{
"name": "L/A VSC",
"configurations": ["Launch VS Code", "Attach to VS Code"]
}

The slight hack I did with the prelaunch task implementing a delay did work but...

I found out you cannot have a prelaunch task when using the watcher task
for incremental building and debugging.

Actually it's clear you cannot have two tasks at the same time.  That means 
no debug set up with the prelaunch task will work with any set up
using something like the watch task (or any other task) I tried an example
of just the echo hello task while using the incremental build task and debugging
fails in that case. standard large tasks, standard code watch task.
 
Limitation/intended or worthy of an issue post?

**Comment by isidorn** [comment]
@cleidigh yes this is a current limitation of the task framework and basically a duplicate of https://github.com/Microsoft/vscode/issues/981 or some other similar task feature request that would like to be able to run more than 1 task at a time
