### ISSUE TITLE
Not able to see changes in the git tree/ sometimes shows wierd styling

### ISSUE THREAD

**Issue by AbhiramKrishnaM** [microsoft/vscode#226476]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

![Screenshot 2024-08-24 at 12 10 36 AM](https://github.com/user-attachments/assets/49147fa8-9590-45ab-8693-b5b13a46a3af)

**Comment by lszomoru** [comment]
@AbhiramKrishnaM, are you able to reproduce this with all extensions disabled? If so can you please provide a screenshot? Thanks!

**Comment by AbhiramKrishnaM** [comment]
> @AbhiramKrishnaM, are you able to reproduce this with all extensions disabled? If so can you please provide a screenshot? Thanks!

I was not able to reproduce with all the extensions disabled.

**Comment by lszomoru** [comment]
Thanks for update! Please use the [bisect tool](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to track down the culprit extension causing the rendering issue.
