### ISSUE TITLE
OmniSharp doesn't run right away when vscode open a dnx project

### ISSUE THREAD

**Issue by rspaulino** [Microsoft/vscode#2264]
Mac 10.11.3
vscode 0.10.6
.net 1.0.0-rc1-final mono 

When I open vscode, let the project load and run ">dnx run" from the Command Palette I get the "OmniSharp server is not running." then I can see in the log that Omnisharp start initializing but only I after I try to run the project after that if I run ">dnx run" everything work fine.

<img width="1280" alt="screen shot 2016-01-25 at 10 51 53 pm" src="https://cloud.githubusercontent.com/assets/378671/12572219/29e90300-c3b7-11e5-98bd-6dce1302459a.png">
<img width="591" alt="screen shot 2016-01-25 at 10 57 44 pm" src="https://cloud.githubusercontent.com/assets/378671/12572220/2a0c8136-c3b7-11e5-8270-5145852360b1.png">

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#17
