### ISSUE TITLE
Typescript - add missing import

### ISSUE THREAD

**Issue by ddyrcz** [Microsoft/vscode#22648]
- VSCode Version: 1.10.2
- OS Version: Win 10

Steps to Reproduce:

1. Fetch some package from the npm (in my case it was angular2-moment)
2. Go to the app.module file
3. Add to the imports array the new module to import (in my case it was MomentModule)
4. Try to add missing import - CTRL + .
5. No missing import is added

**Comment by mjbvz** [comment]
@ddyrcz Can you please provide some example code? Also, is the file you are working with named `app.module` with no `.js` or `.ts` extension? The TypeScript server we use to power our JS and TS intellisense only supports imports/modules for files that have one the these extensions: `.js`, `.jsx`, `.ts`, `.tsx`. You may want to try adding the supported file extensions if this is the case

**Comment by ddyrcz** [comment]
Sory I forgot the extension. Of course I meant app.module.ts

I've create an sample git repository (it's just a new project generated with angular-cli 1.0.0-rc.1):
https://github.com/ddyrcz/vscode-typescript-issue


You can clone this and try to reproduce.

Steps:
1) clone repository from the https://github.com/ddyrcz/vscode-typescript-issue.git
2) install dependencies
3) install angular2-moment (npm i angular2-moment)
4) go to app.module.ts
5) add MomentModule in the imports array

![image](https://cloud.githubusercontent.com/assets/20314986/23989209/f0b89a60-0a31-11e7-8636-109f2d41b8c5.png)

6) try to add missing import

In my case no missing import is adding

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15309
