### ISSUE TITLE
Quick fixes are all "title cased"

### ISSUE THREAD

**Issue by jakebailey** [microsoft/vscode#226487]
Type: <b>Bug</b>

With the latest insiders, I hit Ctrl+. to open the quick fix menu on a diagnostic. As of this release, all of the options are now getting title cased, so I end up with fixes like:

```
Update Import From "./_namespaces/Ts.Js"
```

Even though that's not what tsserver has provided and that's not the code that's going to be added.

![image](https://github.com/user-attachments/assets/b5ef953d-7dfd-416f-8d4a-ebfcde2d0f80)

VS Code version: Code - Insiders 1.93.0-insider (36e4ddb4dbdf5d41bbeedfce2db4834085de2b87, 2024-08-23T06:45:56.108Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.78GB (40.60GB free)|
|Process Argv|--crash-reporter-id d7a309d7-31af-4c18-a079-63f8bc94a2fb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 0)|
|Memory (System)|47.05GB (42.83GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
kdl|kdl|1.3.1
remote-ssh|ms-|0.114.2024082315
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
atom-keybindings|ms-|3.3.0
remote-explorer|ms-|0.5.2024081309
material-theme|zhu|3.17.2
vscode-tsserver-debug|and|1.3.0
markdown-mermaid|bie|1.23.1
monocart-coverage-vscode|Cen|1.0.1
dprint|dpr|0.16.3
copilot|Git|1.223.1065
copilot-chat|Git|0.20.2024082301
vscode-github-actions|git|0.26.3
todo-tree|Gru|0.0.226
vscode-duplicate|mrm|1.2.1
vscode-azureresourcegroups|ms-|0.9.2
azure-account|ms-|0.12.0
hexeditor|ms-|1.10.0
live-server|ms-|0.4.14
vscode-js-profile-flame|ms-|1.0.9
vscode-typescript-next|ms-|5.7.20240822
vscode-twoslash-queries|Ort|1.2.2
deoptexplorer-vscode|rbu|1.1.2
vscode-coverage-gutters|rya|2.11.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
da93g388:31013173
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nb_pkg_only:31057982
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-c:31111717
nativeloc1:31118317
wkspc-ranged-t:31123313
3ad50483:31111987
93e6f237:31111927
e80f6927:31120813
fje88620:31121564
i21gd607:31121876

```

</details>

**Comment by justschen** [comment]
looks like it's a result of https://github.com/microsoft/vscode/pull/226365/files. I'll see if I can come up with a better fix

**Comment by jakebailey** [comment]
I don't really get the original reason to change this; I don't think it's desirable at all to modify the casing of what a language provider is asking the UI to display.

**Comment by justschen** [comment]
ope yes just responded with the PR before I saw this, but I'll defer to you and @daviddossett on this. PR above reverts capitalization for now

**Comment by daviddossett** [comment]
> I don't really understand the original reason to change this

It's to be consistent with all other menus and command palette entries in VS Code. I didn't think about the possibility of affecting paths, so reverting makes sense for now.
