### ISSUE TITLE
Source Control Graph: align the UI for branch info and syncing from repo view?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#226428]
I think these actions confuse me a bit as I am not so used to them (yet):

![Image](https://github.com/user-attachments/assets/c7a9be7d-5170-43b1-b5d5-c8d9174b1c38)

Maybe we could simply copy the UI we already have for the repos view down to the graph view title?

![Image](https://github.com/user-attachments/assets/7911550f-bb60-4aa7-a81f-957cec9ae353)

**Comment by lszomoru** [comment]
Many users value the fact that they have actions to explicitly fetch/pull/push in favour of the sync changes actions. 
Users that do not want to use these actions can hide them as well.
