### ISSUE TITLE
Virtual Box - Ubuntu LTS - Virtual Machine

### ISSUE THREAD

**Issue by vinsevinalon** [Microsoft/vscode#22647]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.8.0-41-generic
- Extensions: none
---

Steps to Reproduce:

1. Install Virtual Box
2. Install Ubuntu LTS Unity
3. Install Visual Code
4. Visual Code is not opening. UI crashes.

**Comment by Tyriar** [comment]
Try `code --disable-gpu`
