### ISSUE TITLE
VSCode OSX crashes immediately on opening after latest release 1.10

### ISSUE THREAD

**Issue by andycmaj** [Microsoft/vscode#22643]
- VSCode Version: 1.10
- OS Version: OSX 10.11 (Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64)

Steps to Reproduce:

1. Update VS Code to latest release
2. Open VSCode

Observe:

<img width="1920" alt="screencapture at tue mar 14 20 49 20 pdt 2017" src="https://cloud.githubusercontent.com/assets/97470/23932858/b7a7a6d4-08f7-11e7-979d-2fa88c0140f4.png">

Happens every time i open...

Insiders build does not crash.

**Comment by andycmaj** [comment]
Rolling back to https://vscode-update.azurewebsites.net/1.9.1/darwin/stable fixes the issue.

here's my extension list:
<img width="470" alt="screencapture at tue mar 14 20 54 41 pdt 2017" src="https://cloud.githubusercontent.com/assets/97470/23932959/7ccbd8ae-08f8-11e7-8148-0bfc46d26398.png">

**Comment by andycmaj** [comment]
uhp... nevermind. i tried to open a project and it started happening again. not sure how i can get log files for this.

```
ELECTRON_ENABLE_LOGGING=1 ELECTRON_ENABLE_STACK_DUMPING=1 code .
```

doesn't seem to show any log output on the console

**Comment by roblourens** [comment]
Can you try the `--verbose` flag?

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by andycmaj** [comment]
i actually cleared my Library directories related to Code and it works again.
i'll re-open and use the --verbose flag if it happens again. 

Thanks!
