### ISSUE TITLE
SCM graph view placement issue

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#226447]
If user would have played around with the order of the SCM views say moving views around and back, then there is a possibility that the new scm graph view can be located on top of the scm view because of its default order value `-998`. Even though the default order of other SCM views is higher (in terms of priority) than graph view, if user moved around the views, the order in the state is set relative to `0`.

**Comment by benibenj** [comment]
I think @sandy081 has fixed this?

**Comment by sandy081** [comment]
Yes
