### ISSUE TITLE
Ability to set "after another breakpoint" expression on breakpoint expressions

### ISSUE THREAD

**Issue by FMorschel** [microsoft/vscode#226420]
Sometimes when debugging I'd like the ability to "stop here if it`s hit after this second breakpoint".

This would be really useful in asynchronous languages.

**Comment by roblourens** [comment]
Is this what you're asking for? https://code.visualstudio.com/updates/v1_86#_triggered-breakpoints

**Comment by FMorschel** [comment]
Yes that was it! Sorry I missed it!
