### ISSUE TITLE
.NET task detection has unclear security level

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#226475]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: Win10

`dotnet.autoDetect` can't be set per workspace/folder, so its either safe for untrusted workspaces, or needs that that functionality would be added.

Steps to Reproduce:

1. Set `dotnet.autoDetect` to `off`.
2. `Terminal\Run Task\dotnet\<<..>> Enable dotnet task detection...`
    
    The shown message tells that the option causes execution of some content, unlike the description for `dotnet.autoDetect`.
    ![image](https://github.com/user-attachments/assets/76a90b26-3d5c-471f-96d7-455337a56e5d)

Description for `typescript.tsc.autoDetect` is also unclear.

**Comment by meganrogge** [comment]
Pls create an issue for the dotnet extension
