### ISSUE TITLE
Comment text cut off in Comments view

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#226415]
Type: <b>Bug</b>

![Image](https://github.com/user-attachments/assets/b613cd72-fe74-4ac8-bfe8-a45221905a19)

VS Code version: Code - Insiders 1.93.0-insider (c2aa3c4625ed4b46448fa546ac5f2e93b0757718, 2024-08-22T05:03:56.076Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (2.00GB free)|
|Process Argv|--crash-reporter-id 7aad610c-0e6b-48aa-ba87-b704b1b543cf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
openmatchingfiles|bca|0.5.4
unique-lines|bib|1.0.0
devcontainer-image-convert|Bri|0.0.1
network-proxy-test|chr|0.0.12
regex|chr|0.4.0
esbuild-problem-matchers|con|0.0.3
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
codespaces|Git|1.17.2
copilot|Git|1.223.1064
copilot-chat|Git|0.20.2024082201
remotehub|Git|0.62.0
vscode-pull-request-github|Git|0.95.2024082204
gitlab-workflow|Git|5.8.0
vscode-drawio|hed|1.6.6
rest-client|hum|0.25.1
template-string-converter|meg|0.6.1
regexsnippets|Mon|1.0.2
vscode-azurefunctions|ms-|1.15.2
vscode-azureresourcegroups|ms-|0.9.2
vscode-docker|ms-|1.29.2
vscode-language-pack-de|MS-|1.93.2024082109
vscode-language-pack-qps-ploc|MS-|1.93.2024082109
vscode-kubernetes-tools|ms-|1.3.16
debugpy|ms-|2024.11.2024081401
python|ms-|2024.13.2024082201
vscode-pylance|ms-|2024.8.101
jupyter|ms-|2024.8.2024081201
jupyter-hub|ms-|2024.5.1002140811
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-ai|ms-|1.0.0
vscode-ai-remote|ms-|1.0.0
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.382.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
azure-account|ms-|0.12.0
azure-repos|ms-|0.38.0
azurecli|ms-|0.6.0
extension-test-runner|ms-|0.0.11
hexeditor|ms-|1.10.0
live-server|ms-|0.5.2024062701
remote-explorer|ms-|0.5.2024081309
remote-repositories|ms-|0.40.0
remote-server|ms-|1.6.2024081909
test-adapter-converter|ms-|0.1.9
vscode-github-issue-notebooks|ms-|0.0.130
vscode-selfhost-test-provider|ms-|0.3.25
vscode-speech|ms-|0.10.0
vscode-speech-language-pack-de-de|ms-|0.4.0
chat-sample|my-|0.1.0
vscode-yaml|red|1.15.0
vscode-dall-toys|rob|0.0.9
rust-analyzer|rus|0.4.2082
eval|Sto|0.0.6
vscode-open-in-github|sys|1.18.0
even-better-toml|tam|0.19.2
shellcheck|tim|0.37.1
non-github-remote-source-provider|und|0.0.1
vscode-lldb|vad|1.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
9c06g630:31013171
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31057980
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31111718
nativeloc1:31118317
3ad50483:31111987
93e6f237:31111927
e80f6927:31120813
ei213698:31121563
12bdf347:31121875

```

</details>

**Comment by alexr00** [comment]
I expanded the max width earlier this year and I can expand it to fully fit the view, but I thought it looks weird that way. @daviddossett, what do you think?

**Comment by daviddossett** [comment]
I guess it could be hard to read on really large screens. But at the same time there's no logical reason to overflow if it isn't wrapping to multiple lines. 

Maybe a screenshot to compare would be helpful.

**Comment by alexr00** [comment]
Example: 
![Image](https://github.com/user-attachments/assets/c099639a-42e4-42c9-87a6-641039e9b819)

I originally got feedback when doing the comments view refresh that having the comment fill the whole width didn't look good, but it seems fine to me now.

**Comment by chrmarti** [comment]
The line number is moved too far to the right. I'll open a new issue for that.
