### ISSUE TITLE
remove old issue reporter flow

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#226481]
- [x] enable aux window issue reporter by default everywhere (https://github.com/microsoft/vscode/pull/226370)
- [ ] continue to monitor issues in stable and insiders. when we are at a good spot, we can continue with the step below.
- [ ] remove all components of the old issue reporter (https://github.com/microsoft/vscode/issues/213332)

**Comment by bpasero** [comment]
Would be great to remove the old `BrowserWindow` based flow 🙏
