### ISSUE TITLE
Cannot close miniterm 

### ISSUE THREAD

**Issue by neilyoung** [Microsoft/vscode#22646]
- VSCode Version: Version 1.11.0-insider (1.11.0-insider)
- OS Version: Mac OSX Sierra

Steps to Reproduce:

1. I've got pyserial and miniterm installed together with ESP32-IDF (https://github.com/espressif/esp-idf)
2. If I want to compile and flash and run a console I need to issue 

`make flash monitor`

on a terminal prompt. This works both, on native terminal and integrated terminal. But I can't finish the terminal after debugging. The key combination is CTRL-[, which is CTRL+ALT+6 on a Mac. This closes the miniterm window in native terminal, but not in integrated terminal in VSCode

**Comment by Tyriar** [comment]
@neilyoung do you know what ctrl+[ is meant to do in your case exactly? xterm.js appears to act the same as gnome-terminal in a regular bash prompt.

You could try ctrl+c (SIGINT) or ctrl+\ (string terminator).

**Comment by neilyoung** [comment]
I'm sorry, my fault. It is actually CTRL+]
Description here: http://esp-idf.readthedocs.io/en/latest/idf-monitor.html?highlight=miniterm

**Comment by Tyriar** [comment]
Please provide additional repro steps if you're still having this issue.
