### ISSUE TITLE
Remember Language Mode for re-opened hot-exit code

### ISSUE THREAD

**Issue by seewee44** [Microsoft/vscode#22658]
Would it be possible to restore the Language mode that was set on an unsaved file when restoring ?

- VSCode Version: 1.11.0
- OS Version: Windows 10 1607

Steps to Reproduce:

1. Create a new file, don't save
2. Set language mode to anything but "Plain Text"
3. Exit without saving
4. Re-open VS Code
5. Code is restored in Untitled-1, language mode is back to "Plain Text"

**Comment by bpasero** [comment]
This works as soon as you open a folder, but not without. This is https://github.com/Microsoft/vscode/issues?page=156&q=is%3Aissue+is%3Aopen
