### ISSUE TITLE
Indentations getting lost while copy pasting

### ISSUE THREAD

**Issue by harikrishkk** [Microsoft/vscode#22659]
- VSCode Version: Code - Insiders 1.11.0-insider (6a002910356c6e087dd93e819e4ad54c68b9857a, 2017-03-15T07:11:58.965Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|Theme-azure|gerane|0.0.2|
|easy-icons|jamesmaj|0.3.1|
|jostheme|jestersimpps|0.1.0|
|theme-onedark-sublime|joshpeng|0.3.6|;

---

Steps to Reproduce:

1.The copy as HTML with syntax highlighting was working awesome. But after a couple of updates, now the same when copy pasting, looses all the indentations. 
![image](https://cloud.githubusercontent.com/assets/5024456/23945233/cadd63b6-099b-11e7-852e-bccc9bd6d5b1.png)

2. I was able to copy paste well before, but now, after pasting, i need to again re-align the braces and spacings.

**Comment by rebornix** [comment]
It's an obsolete/dup one. Now already fixed in master.
