### ISSUE TITLE
VSCode Developer Tools freeze when click mobile view (permanently)

### ISSUE THREAD

**Issue by tom-pollak** [microsoft/vscode#226551]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 
```
$ code --version
1.92.2
fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
arm64
```
- OS Version: MacOS 14.6.1

Steps to Reproduce:

1. Click the mobile view button in developer tools
2. All developer tools freeze (elements, console, sources), not possible to toggle back to normal mode, and this toggle seems to be saved across restarting, no extensions etc.

https://github.com/user-attachments/assets/10893a2d-5e9f-492f-a551-cafe234b3d70

**Comment by deepak1556** [comment]
Can you check if the issue repros with our insiders https://code.visualstudio.com/insiders/

**Comment by tom-pollak** [comment]
It does

- toggle developer tools
- click the mobile web view button (be careful bricks the dev tools)

**Comment by deepak1556** [comment]
I am unable to repro the issue with insiders while stable does repro the issue. Can you share your `settings.json`, wonder if they have an effect.
