### ISSUE TITLE
Try out MSAL-node based Microsoft auth

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#226539]
Refs: https://github.com/microsoft/vscode/issues/178740

- [ ] macOS @aiday-mar
- [x] linux @rzhao271
- [x] windows @andreamah

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23226539%0A%0A&assignees=TylerLeonhardt)

---

This iteration, we've essentially completely rewritten the Microsoft auth extension using https://github.com/AzureAD/microsoft-authentication-library-for-js which is the recommended way to interact with Microsoft identity APIs and allows us one day to use WAM to get auth state from the OS.

I'd love for you to give this new auth provider a spin.

### Prereqs

* YOU MUST APPLY [THE MSAL SETTING](https://vscode.dev/redirect?url=vscode-insiders://settings/microsoft.useMsal).

* You can certainly write [your own little extension](https://code.visualstudio.com/api/get-started/your-first-extension) and interact with [our auth APIs](https://code.visualstudio.com/api/references/vscode-api#authentication) like:
  ```ts
  vscode.authentication.getSession('microsoft', scopes, options);
  ```
  
  Or you can use my [Fugio extension](https://marketplace.visualstudio.com/items?itemName=TylerLeonhardt.fugio) to do more or less the same thing but via a quick pick form.

### Definitions

* **AuthenticationSessionAccountInformation:** An account. An account can be associated with many sessions
* **AuthenticationSession:** A session that contains an access token that has certain scopes
* **Scopes:** these are the permissions that you want to have
* **JWT:** The Access Token in the session is a **J**SON **W**eb **T**oken. You can paste the access token into http://jwt.io to see the information contained by it

### Testing

* Different values of scopes:
  * `profile` - returns a basic session with just some profile info
  * `Mail.ReadWrite` - returns a session that could be used to read or write your email ([API](https://learn.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http))
  * `VSCODE_CLIENT_ID:a4fd7674-4ebd-4dbc-831c-338314dd459e`, `VSCODE_TENANT:common`, `profile` - Put all of these. These `VSCODE_` scopes are "special" scopes that we don't pass along with the scopes themselves but rather use these to override the app that is used. VS Code ships with a default client id and tenant, which extension authors can use, but if that doesn't meet their needs, they can [create their own Entra App](https://ms.portal.azure.com/#view/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/~/Overview) and override it this way. I've created a backup Entra App for you. Keep in mind, it may not work with Corp accounts, Personal Microsoft accounts work better.
  
  Feel free to play with other values of scopes. Keep in mind, not every set of scopes will work because our app is only suppose to have the minimum scopes authorized to function... but if you hit this case (it complaining about pre-authorization) the error message should be surfaced to you nicely.
* General flow stuff
  * Sign in - did it work?
  * Sign out - did it work?
  * Sign in again - did it work?
  * Wait a long time - are you still logged in?
  * reload the window - are you still logged in?
* Real world examples
  * Use Settings Sync with Microsoft
  * Use the Azure Resources extension

It's... a weird topic so feel free to message me if you have any questions. I'll be in Germany during testing, but will try to respond to questions.

**Comment by aiday-mar** [comment]
Hi I am currently trying to test this TPI and am a bit confused as to what to do. I installed the Fugio extension. I noticed from the command palette, there are the commands `Fugio : Inspect Accounts` and `Fugio : Mint Token`. From your description I suppose that clicking on `Fugio : Inspect Accounts` or `Fugio : Mint Token` should open a form view. This does not happen on my VS Code insiders instance. I was wondering if I am missing something to test correctly?

https://github.com/user-attachments/assets/ce388d97-2be0-4c6c-81f3-bcdf0964833a

**Comment by aiday-mar** [comment]
I did the same as Andrea with settings sync and the azure resources extension. I read the filed issues to understand better the steps. Generally signed in and signed out, tried reloading and changing the scopes of the tokens. It seems to work.
