### ISSUE TITLE
Feature Request: Allow Customization of Tooltip Content in VSCode

### ISSUE THREAD

**Issue by joonheeu** [microsoft/vscode#226561]
**Description:**

Hello, I would like to suggest an enhancement for Visual Studio Code that could further improve the user experience. Currently, tooltips in VSCode automatically generate useful information based on the code context. However, I believe the product could benefit from a feature that allows users to customize and extend the content of these tooltips according to their specific workflows and needs.

**Problem:**

At present, tooltips are generated in a fixed manner with no built-in functionality for users to edit, add to, or modify the content. This limitation may restrict developers who wish to incorporate custom information or adjust tooltip formatting to enhance readability and improve their development experience.

**Proposed Solution:**

I propose the introduction of a feature or API that enables users to:

Customize tooltip content: Modify the content based on specific conditions or code contexts.
Insert additional information: Add custom documentation, notes, or links directly into tooltips.
Adjust tooltip formatting: Modify the formatting or styling of tooltips to align with user preferences.

**Use Cases:**

1. **Enhanced Documentation**: Developers could embed specific notes or documentation snippets directly into tooltips, providing immediate access to relevant information.
2. **Custom Formatting**: Users might format tooltips to highlight important sections or add links, making tooltips more aligned with their development style.
3. **Project-Specific Information**: In certain projects, the ability to include project-specific information directly in tooltips could greatly enhance productivity for the entire team.

**Conclusion:**

Introducing this feature would make VSCode more flexible and powerful, catering to a broader range of developer needs. It would allow all users to better control their development environment and enhance their productivity with personalized tooltip content.

I submit this feature request with respect for the community and contributors, and I appreciate your consideration. Thank you.

**Comment by jrieken** [comment]
> Currently, tooltips in VSCode automatically generate useful information based on the code context.

There are a couple of things in VSCode that can be described as tooltips, which one do you mean? Those inside the editor, e.g when hovering over words or what "targets" do you have in mind?
