### ISSUE TITLE
Add a Restart Command

### ISSUE THREAD

**Issue by DashBing** [microsoft/vscode#226511]
Add a new command that can restart VSCode just like the "restart" when when updated the VSCode or selected a new 
display language.

> before edited:
> when you update an extension.

There's a very similar command `Reload Window`, but it won't reload all the windows.
I think the new command should be like `Reload VSCode` or `Restart VSCode`.

**Comment by demetrebadzaradze** [comment]
is reload window not good enough for your work??

**Comment by RedCMD** [comment]
it works too much
clears undo history etc

**Comment by bpasero** [comment]
A command to restart the extension host exists, that is what happens when restarting for an extension:



![Image](https://github.com/user-attachments/assets/494cb8c4-972e-4774-a549-92a6e10b2c91)

**Comment by RedCMD** [comment]
`workbench.action.restartExtensionHost` doesn't clear the `Restart Extensions` notification

![image](https://github.com/user-attachments/assets/19911384-4323-4f24-93f3-4453183d5866)

![image](https://github.com/user-attachments/assets/f7a67957-1f79-42ae-b9a3-e5d28ccd084f)

**Comment by bpasero** [comment]
In that case I think "Reload Window" should suffice:



![Image](https://github.com/user-attachments/assets/386323cf-4b2a-49a8-b6c5-6150099a9809)

**Comment by RedCMD** [comment]
`workbench.action.reloadWindow` clears undo history etc
which is undesirable

we would like to be able to run the command that the `Restart Extensions` button does
`workbench.action.restartExtensionHost` does not restart extensions in the way that `Restart Extensions` does

**Comment by bpasero** [comment]
That is unfortunately not possible, some extensions that are running cannot restart, but @sandy081 would know the rules.

**Comment by DashBing** [comment]
But `Reload Window` won't reload all of the windows.

**Comment by DashBing** [comment]
It would be nice to be able to refresh the environment variables at the same time, refer to #226510 .

**Comment by DashBing** [comment]
Another suggestion is add `Restart` to here:
![image](https://github.com/user-attachments/assets/d238e706-04bc-4541-828b-6c4bcd96d326)

**Comment by sandy081** [comment]
> we would like to be able to run the command that the Restart Extensions button does
workbench.action.restartExtensionHost does not restart extensions in the way that Restart Extensions does

What's the difference?

**Comment by RedCMD** [comment]
`workbench.action.restartExtensionHost` doesn't reload TextMate grammars

if I disable an extension and **don't** click `Restart Extensions`
but instead run `workbench.action.restartExtensionHost`
the extension still remains enabled
and no TextMate grammars get refreshed

**Comment by sandy081** [comment]
CC @alexdima

**Comment by axefrog** [comment]
@alexdima This is a niche feature. It feels like the "20 community upvotes" requirement to not have the bot automatically close it should be reconsidered in this case. This should especially be the case for features involving an intersection of multiple niches (in this case; _people using local workspace extensions_ and _people developing extensions_). You'd get the upvotes, it might just take longer than 60 days, especially considering the fact that local workspace extensions are still a relatively new feature. We have 6 upvotes so far. This seems valid, I think?

**Comment by axefrog** [comment]
@alexdima @deepak1556 @bpasero This is a niche feature - important, but niche nonetheless. I'd imagine niche features would be more likely to grow in usage with increased focus on reduction of friction in their use. It feels like the "20 community upvotes" requirement to not have the bot automatically close it should be reconsidered in cases like this, as the expectation of N upvotes in T time period shouldn't be applied equally to all categories of features. This should especially be the case for features involving an intersection of multiple niches (in this case; _people using local workspace extensions_ and _people developing extensions_). You'd get the upvotes, it might just take longer than 60 days, especially considering the fact that local workspace extensions are still a relatively new feature. We have 6 upvotes so far. This seems valid, I think?
