### ISSUE TITLE
Block cursor is able to reach inline hints and causes wrong visual feedback for calculated cursor position

### ISSUE THREAD

**Issue by andreasvh-conceto** [microsoft/vscode#226557]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version: macOS Sonoma 14.6.1 (23G93)

Steps to Reproduce:
1. open a new typescript file `code --disable-extensions foo.ts` 
2. Go to Command Palette (F1) and go to user settings (JSON), enable the inline hints and a block cursor:
```json
    "editor.cursorStyle": "block",
    "typescript.inlayHints.parameterNames.enabled": "all",
    "typescript.inlayHints.functionLikeReturnTypes.enabled": true,
    "typescript.inlayHints.enumMemberValues.enabled": true,
    "typescript.inlayHints.variableTypes.enabled": true,
    "typescript.inlayHints.propertyDeclarationTypes.enabled": true
```
3. Type in the following code in the `foo.ts`:
```typescript
Object.values(123);
```
4. Make sure inline hints are shown, if not (F1 -> Reload Window). It should look like this:
```typescript
Object.values(o: 123);
```
5. Begin with the block cursor _at the beginning_ of the line and move with the right arrow to the right until you reach the _**invalid!!**_ position. The `[x]` represents the cursor:
```typescript
// Start here
[O]bject.values(o: 123);
// move to the right until you reach this invalid position from the inline hint
Object.values([o]: 123);
// this represents the following position: Ln1, Col15
```
6. Move just one step more to the right and you will see, that you will skip the `1` and directly be here:
```typescript
// 1 was skipped when moving from left to right
Object.values(o: 1[2]3);
```
7. Now start _from the right side_ and move the cursor to the left until you reach the following position:
```typescript
// Start here
Object.values(o: 123)[;]
// move <= here with arrows
Object.values(o: [1]23);
// this represents also the following position: Ln1, Col15
```
8. Move one step more to the left and you will see, that the inlineHint is correctly skipped:
```typescript
Object.values[(]o: 123);
```

In both cases for 5 and 7 the cursor position is the same and in step 5 we reached an invalid inline hint position. Since 2 visual positions are mapped to one cursor position behind the scenes `Ln1, Col15` this leads to wrong visual feedback for the calculated cursor position.

Note:
While this issue sounds absolutely minor it has major and annoying effect for extensions like `vim` and `neovim`. These (block-cursor-based) extensions are used by many developers and in **both** extensions the developers are unable to visually reach the resulting position from step 7. Nevertheless if you come from the right or left - you can not reach this position:
```typescript
// unreachable position for vim or neovim extension
Object.values(o: [1]23);
```

It is always shown as:
```typescript
Object.values([o]: 123);
```
Luckily on this position vim commands like `r` for replace are still working and the 1 will still be replaced. 

But the visual feedback is not in synch. The cause of this issue should be exactly the steps from 1 to 8, which is reproducable without any extension in vscode.

I would be very grateful for a solution.

Thanks a lot and best regards
Andreas

**Comment by hediet** [comment]
Thanks! @ulugbekna filed this already somewhere though.
