### ISSUE TITLE
installiation issue

### ISSUE THREAD

**Issue by Goku2415** [microsoft/vscode#226524]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2
- OS Version: 

Steps to Reproduce:

1. I am unable to install vs code as an administrator
2. 

```[tasklist]
### Tasks
```
```[tasklist]
### Tasks
```

**Comment by rzhao271** [comment]
@Goku2415 could you try using the User installer from the [Downloads](https://code.visualstudio.com/Download) page? It should not require admin permissions. In the worst case, there is also a zip file to use VS Code in portable mode.
