### ISSUE TITLE
the terminal doesn´t work

### ISSUE THREAD

**Issue by AlRe221** [microsoft/vscode#226527]
My terminal got stuck in one point, and im trying tu rum my tests, but it doesn´t work. Like, this freezed. 

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed
