### ISSUE TITLE
i do not have a tool bar or backspace funtion

### ISSUE THREAD

**Issue by zues1bh** [Microsoft/vscode#22657]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|statusbar-commands|anweber|0.1.0|
|scanner-js-twain-wia-javascript-browser-scan|asprise-scan-ocr|2.0.2|
|python|donjayamanne|0.6.0|
|vscode-nupkg|eridem|0.0.4|
|scriptcsRunner|filipw|0.1.0|
|code-runner|formulahendry|0.6.14|
|nuget-reverse-package-search|jesschadwick|0.1.61|
|vscodeilviewer|josephwoodward|0.0.1|
|docomment|k--kato|0.0.14|
|csharpfixformat|Leopotam|0.0.16|
|quicksnippet|mousetraps|0.0.1|
|csharp|ms-vscode|1.8.0|
|PowerShell|ms-vscode|0.10.0|
|sublime-keybindings|ms-vscode|2.0.1|
|vs-keybindings|ms-vscode|0.1.3|
|material-icon-theme|PKief|2.0.0|
|ClassyNaming|reflectiondm|1.0.0|
|vscode-icons|robertohuertasm|7.3.0|
|vim|vscodevim|0.6.5|
|wandbox-vscode|wraith13|2.1.1|;

---

Steps to Reproduce:

1.
2.

**Comment by weinand** [comment]
@zues1bh VS Code does not have a "toolbar" by design. Please watch the following introduction to learn how VS Code works: https://code.visualstudio.com/docs/introvideos/quicktour

What do you mean by "backspace function"?

**Comment by zues1bh** [comment]
I cannot back space when I am writing code. I have to highlight and cut all
unwanted text.

**Comment by weinand** [comment]
So you don't have a Backspace ('←') key?

**Comment by weinand** [comment]
no response -> closing
