### ISSUE TITLE
Test: Git - support reftable storage

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#226598]
Refs: https://github.com/microsoft/vscode/issues/221642

- [x] anyOS @anthonykim1
- [x] anyOS @ntrogh

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23226598%0A%0A&assignees=lszomoru)

---

Git 2.45 introduces support for the new reftable storage. This milestone we have made changes to the `vscode.git` extension to support it.

### Prerequisites
1. Install Git 2.45 or later
2. Install the latest VS Code Insiders release

### Testplan
1. Clone a git repository using the terminal
    ```
    git clone --ref-format=reftable https://github.com/microsoft/vscode.git
    ```
2. Open a newly cloned repository in VS Code
    * Confirm that the repository is correctly detected 
3. Perform basic source control operations (ex: checkout, stage/unstage, commit, create new branch)
    * Confirm that these operations are working as expected

**Comment by ntrogh** [comment]
Tested ok with git 2.46 on Windows.

**Comment by anthonykim1** [comment]
Tested with 2.46.0 - tried making branch, staging and committing - worked fine. Also seeing expected main with check mark instead of invalid from the screenshot in the referenced issue. Nice work!
