### ISSUE TITLE
Cengage MindTap unable to find line in program

### ISSUE THREAD

**Issue by mifraser1** [microsoft/vscode#226526]
Cengage MindTap is unable to find String testScoreString; or find a line. I am not experienced in java or github, but I'm sure that the code is identical to what is being asked. I tried refreshing the extensions, browser, project.

Test Feedback:
Status: FAILED!
Check: 1
Test: Declare the `String` variable `testScoreString`.
Reason: Unable to find 'String testScoreString;' in the program.
Error : str - AssertionError
Timestamp: 2024-08-24 16:02:52.065382

Status: FAILED!
Check: 1
Test: A student ranked 45 is rejected for an 85 test score.
Reason: No line found
Error : str - AssertionError
Timestamp: 2024-08-24 16:02:56.011484

Code:
import java.util.Scanner;
public class CollegeAdmission
{
	public static void main(String args[])
   { 
  		// Declare variables   
      String testScoreString;
      String classRankString;
      int testScore;
      int classRank;
      Scanner scanner = new Scanner(System.in);
    
     	// Get input and convert to correct data type    
      System.out.println("Enter student's test score:");
      testScoreString = scanner.nextLine();
      System.out.println("Enter student's class rank:");
      classRankString = scanner.nextLine();
      testScore = Integer.parseInt(testScoreString);
      classRank = Integer.parseInt(classRankString);

     	// Test using admission requirements and print Accept or Reject 
		if( testScore >= 90 )
		{
			if( classRank >= 25)
			{
			   System.out.println("Accept");
			}
			else
	   		System.out.println("Reject"); 
		}
     	else 
        {
           if (testScore >= 80) {
              if (classRank >= 50)
                 System.out.println("Accept");
              else
                 System.out.println("Reject");
           } else {
              if (testScore >= 70) {
                 if (classRank >= 75)
                    System.out.println("Accept");
                 else
                    System.out.println("Reject");
              } else
                 System.out.println("Reject");
           }
        }
        scanner.close();
   } // End of main() method
} // End of CollegeAdmission class

![image](https://github.com/user-attachments/assets/1d0b668f-a77c-4a54-ae7d-834505535374)

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by Abisael313952** [comment]
I have the same problem.
