### ISSUE TITLE
High CPU and Ram Usage when using Flutter SDK and when using Android Emulator

### ISSUE THREAD

**Issue by faheemstepsharp** [microsoft/vscode#226517]
Here’s your updated GitHub issue with the additional information:

---

**Title**: High CPU and RAM Usage in VS Code with Flutter SDK and Android Emulator

**Description**:
While using VS Code with the Flutter SDK, I encounter high CPU and RAM usage, particularly when running the Android Emulator. Additionally, hovering over any class, function, or image within VS Code takes an unusually long time to display information, further slowing down the development environment.

**Steps to Reproduce**:
1. Open VS Code with the Flutter extension installed.
2. Create a new Flutter project or open an existing one.
3. Launch the Android Emulator and run the Flutter project.
4. Hover over any class, function, or image within the code.
5. Monitor CPU and RAM usage using system monitoring tools.

**Expected Behavior**:
VS Code should run smoothly with reasonable CPU and RAM usage during Flutter development, and hover actions should display information promptly.

**Actual Behavior**:
High CPU and RAM consumption in VS Code, causing the system to slow down. Hover actions are slow to respond, making the IDE sluggish and difficult to work with.

**Environment**:
- Flutter version: 3.24
- Operating System: [Windows 11]
- CPU: i3
- RAM: 16GB

**Additional Information**:
- Disabling unnecessary VS Code extensions did not help.
- The issue persists with both new and existing Flutter projects.
- Hovering over classes or functions significantly delays performance.

**Comment by mjbvz** [comment]
Please file this against the flutter extension

**Comment by faheemstepsharp** [comment]
> Please file this against the flutter extension

Cant, even VSCODE is doing same with NEXTJS
