### ISSUE TITLE
vs code is slow, both text editor and terminal

### ISSUE THREAD

**Issue by omril1** [microsoft/vscode#226538]
Type: <b>Performance Issue</b>

It behaves like shell intergration is enabled but it is not enabled

VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|6, 5, 4|
|Memory (System)|64.00GB (5.03GB free)|
|Process Argv|--crash-reporter-id f907a8d5-38cd-4a67-9a1c-a3263bd5949a|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   24	   328	  3194	code main
    7	   131	  3197	   gpu-process
    0	    66	  3198	   utility-network-service
    1	   131	  3504	shared-process
    0	     0	 51268	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	  3514	ptyHost
    0	    66	 72407	     zsh (figterm)
    0	     0	 72425	       /bin/zsh --login
   18	   131	 51233	window [4] (Issue Reporter)
   64	  1180	 86669	window [3] (.eslintrc — testimio)
  101	  1769	 86686	extensionHost [3]
    0	   197	 86690	     electron-nodejs (tsserver.js )
    0	  1901	 86691	     electron-nodejs (tsserver.js )
    0	   197	 86692	     electron-nodejs (server-node.js )
    0	   131	 86693	     electron-nodejs (server.js )
    0	  1376	 86715	     electron-nodejs (eslintServer.js )
    2	   197	 86716	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/omriluzon/.vscode/extensions/streetsidesoftware.code-spell-checker-3.0.1/packages/_server/dist/main.cjs --node-ipc --clientProcessId=86686
    0	   131	 86717	     electron-nodejs (start-server.js )
    0	    66	 86727	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=86686
    0	   131	 86992	     electron-nodejs (languageserver.js )
    0	    66	 87042	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=86686
    3	   131	 86687	fileWatcher [3]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (.eslintrc — testimio)
|    Folder (testimio): 9019 files
|      File types: ts(2773) tsx(1119) html(909) svg(782) scss(760) js(212)
|                  gz(144) png(124) woff2(88) woff(77)
|      Conf files: github-actions(24) dockerfile(13) package.json(13)
|                  tsconfig.json(10) launch.json(1) settings.json(1)
|      Launch Configs: node(8);
```

</details>
<details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
tsco|alj|1.0.29
unique-lines|bib|1.0.0
vscode-css-modules|cli|0.5.1
vscode-svgviewer|css|2.0.0
vscode-redis-client|cwe|7.5.7
vscode-eslint|dba|3.0.10
highlight|deb|0.1.0
xml|Dot|2.5.1
gitlens|eam|15.3.1
prettier-vscode|esb|11.0.0
copilot|Git|1.223.0
copilot-chat|Git|0.18.2
copilot-labs|Git|0.17.1121
vscode-pull-request-github|Git|0.94.0
vscode-drawio|hed|1.6.6
banner-comments|hey|0.4.3
vscode-ansi|ili|1.1.7
vscode-postfix-ts|ipa|1.13.2
vscode-smart-column-indenter|lmc|0.0.13
yarn-lock-syntax|mar|0.2.0
vscode-docker|ms-|1.29.2
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
hexeditor|ms-|1.10.0
test-adapter-converter|ms-|0.1.9
vscode-js-profile-flame|ms-|1.0.9
vscode-twoslash-queries|Ort|1.2.2
refactor|p42|3.0.1
vscode-versionlens|pfl|1.14.2
vscode-yaml|red|1.15.0
vscode-sort-json|ric|1.20.0
vs-code-prettier-eslint|rve|6.0.0
vscode-javascript-booster|sbu|14.0.1
code-spell-checker|str|3.0.1
vscode-stylelint|sty|1.4.0
teamhub|Tea|17.1.4
jest-snapshot-language-support|tle|1.1.1
vscode-icons|vsc|12.8.0
highlight-bad-chars|wen|0.0.6
fig|wit|0.0.7
change-case|wma|1.0.0
pretty-ts-errors|Yoa|0.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-t:31111718
wkspc-ranged-t:31123313
pme_test_t:31118333
fje88620:31121564

```

</details>

```[tasklist]
### Tasks
```

**Comment by meganrogge** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
/label info-needed terminal

**Comment by omril1** [comment]
I don't have time to investigate it at the moment, I will open a better issue with more details if I do have the time.
