### ISSUE TITLE
Lock empty groups

### ISSUE THREAD

**Issue by Vallek** [microsoft/vscode#226553]
Please make it possible to lock empty groups so you can't close them. For example by accidentally clicking middle mouse on empty group.

And/or make it possible to lock whole editor/groups layout. So opening files will never create more groups.

To be clear lock groups currently as far as I know does not allow to do it. You can lock group with editors but it does not prevent empty group from being closed or opening new ones.

**Comment by bpasero** [comment]
Empty groups can be locked:

![Image](https://github.com/user-attachments/assets/efecafe9-14c5-4e89-87ab-24c05018292c)
