### ISSUE TITLE
Javascript support broken? jsconfig.json's file directive is ignored, and intellisense doesn't work

### ISSUE THREAD

**Issue by manad777** [Microsoft/vscode#2265]
I used the first jsconfig.json example from https://code.visualstudio.com/Docs/languages/javascript in my project. According to the doc this config should only let app.js be visible in the left pane, but as you can see in the screenshot below it's not the case. I tried restarting Code, of course.

![screenshot - 01252016 - 11 29 24 pm](https://cloud.githubusercontent.com/assets/3642217/12572708/a6bb7286-c3bd-11e5-8ff0-c9169543b652.png)

Similarly, Intellisense doesn't work at all. I installed typings using the tsd commands mentioned at https://code.visualstudio.com/Docs/runtimes/nodejs (they're visible in the screenshot), but autocomplete for commonjs modules is not working. A google search had people mentioning a tsd.d.ts file in the typings/ directory, but tsd didn't create one for me. I tried creating one by hand and populating it using the content with the entries below pointing at existing files, but autocomplete is still unavailable.
`/// <reference path="node/node.d.ts" />
/// <reference path="lodash/lodash.d.ts" />`

Does VS Code actually support Javascript, or did I completely misunderstand the doc?

**Comment by justsml** [comment]
Oh, it works brilliantly on all platforms.
Check here: http://webstackoflove.com/use-typescript-definition-manager-for-adding-type-definitions-to-your-project/
And read the whole README here: https://github.com/DefinitelyTyped/tsd

**Comment by justsml** [comment]
![vscode-lodash-autocomplete](https://cloud.githubusercontent.com/assets/397632/12574752/f436be48-c3c3-11e5-9de0-59c32948dd31.png)

Here's my `tsd.d.ts`
```
/// <reference path="angularjs/angular.d.ts" />
/// <reference path="express/express.d.ts" />
/// <reference path="jquery/jquery.d.ts" />
/// <reference path="lodash/lodash.d.ts" />
/// <reference path="superagent/superagent.d.ts" />
/// <reference path="supertest/supertest.d.ts" />
```

**Comment by manad777** [comment]
My problems remain.

I've set up a repo showing the issue: https://github.com/manad777/vscodetest . 
If you clone that repo, do you get lodash's autocomplete in app.js?

I feel there is fundamental broken here, because I don't see what I'm doing anything different from you. What version of VSCode are you using? Here's a complete list of my issues on 0.10.5:

##FILE EXCLUSION
1. https://code.visualstudio.com/Docs/languages/javascript states that the "files" entry in jsconfig.json's will only show those files, 
implicitly excluding all others. Yet all files remain visible, not just app.js.

2. https://code.visualstudio.com/Docs/languages/javascript states that the "exclude" entry in jsconfig.json will excluse directories
matching that name. However, folder-to-be-ignored remains visible.

3. https://code.visualstudio.com/Docs/languages/javascript states "By default, VS Code excludes .git, node_modules, bower_components, 
jspm_packages, tmp, and temp folders." 
However, node_modules remains visible (I didn't bother trying the others).

##AUTOCOMPLETE/INTELLISENSE
I ran the following commands:
npm install lodash --save
tsd init
tsd install lodash --save

Yet, in app.js, I don't get autocomplete after _. If I press Ctrl+Space after the dot, I get "No suggestions".

**Comment by justsml** [comment]
Strange on the autocomplete issue. I've seen something similar related to the default open-file limits in Mac & Linux. Can you post the results of this cmd: `ulimit -a`

**Comment by justsml** [comment]
Here are some related issues:
#1081 and #703

**Comment by manad777** [comment]
user1@ubuntu-webdev:~$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7922
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7922
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

This is on Ubuntu 14.04.

The issues you linked seem related to large amount of projects, or the name of directories. I can reproduce it with nothing but a single app.js file in the root directory.

**Comment by unional** [comment]
I can confirm that `files` in `jsconfig.json` is not working. `exclude` does work.
https://github.com/coolcodeexamples/timely-wealth-game
https://github.com/coolcodeexamples/timely-wealth-game/tree/files-not-working

**Comment by unional** [comment]
@manad777  I don't see the doc says it will "hide the files in the left pane".  My understanding is that it only govern intelliSense. Am I wrong?

**Comment by ginolon** [comment]
+1 the same problem of lodash and _.

**Comment by egamma** [comment]
>https://code.visualstudio.com/Docs/languages/javascript states that the "files" entry in jsconfig.json's will only show those files, implicitly excluding all others. Yet all files remain visible, not just app.js.

The misunderstanding is the sentence ` The file itself lists the files belonging to the project as well as compiler options.` The explorer shows all files not only the files belonging to the project defined in the jsconfig.json.

>Similarly, Intellisense doesn't work at all. I installed typings using the tsd commands mentioned at https://code.visualstudio.com/Docs/runtimes/nodejs (they're visible in the screenshot), 

In your jsconfig.json you define that only `app.js` belongs to the project, therefore the typings folder is not considered. You either need to remove the `files` section or add the `.d.ts` folders to the `files` list.

**Comment by manad777** [comment]
@egamma , thanks for clarifying that the explorer will always show everything regardless of configuration. It's not a bug, then.

However, this issue shouldn't be closed yet. Neither of your suggestions to fix intellisense worked for me. I tried removing the files entry altogether, and I tried adding every single typings path I could think of. In both cases I restarted VSCode. And in both cases, I still had no intellisense in app.js.

My example project has 2 new commits that you can peruse: https://github.com/manad777/vscodetest/commits/master

**Comment by egamma** [comment]
I've changed the `jsconfig.json` as follows:

```json
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs"
    },
    "exclude": [
        "node_modules"
    ]
}
```

Now it works for me
![image](https://cloud.githubusercontent.com/assets/172399/13553359/168ee62c-e387-11e5-8df8-937d1581b70d.png)

**Comment by unional** [comment]
https://github.com/Microsoft/vscode/issues/2265#issuecomment-176601823

I think `exclude` does work. But not for `files`.

**Comment by egamma** [comment]
@unioal thanks and agreed, the `exclude` setting has no impact on the behaviour. I can remove it from the jsconfig.json and I still get Intellisense.

**Comment by egamma** [comment]
The following jsconfig.json works for me in VS Code 0.10.10 available on the insider channel.

`jsconfig.json`

```json
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs"
    },
    "files": [
        "app.js",
        "typings/lodash/lodash.d.ts"
    ]
}
```

![image](https://cloud.githubusercontent.com/assets/172399/13553414/d92d2d28-e388-11e5-80bc-f95382c3e50a.png)

**Comment by unional** [comment]
Thanks.  @egamma . I just reconfirming that it is working too. :beer:

**Comment by gvolkan** [comment]
Thanks @egamma, 
may the force be with you :)

**Comment by manad777** [comment]
Even after @egamma 's suggested jsconfig.json Intellisense wouldn't work. Then I deleted ~/.config/Code and tried again, and it worked. I've been using VS Code for a few months now, so it could have been caused by an artifact from an old version.

**Comment by blopez2010** [comment]
The solution works with small projects but if it is a large project it doesn't work on VSCode version 1.3.1
