### ISSUE TITLE
dzwięki podczas pisania kodu 

### ISSUE THREAD

**Issue by ManczakAdrian** [microsoft/vscode#226523]
Type: <b>Feature Request</b>

Good day, when writing code, when pressing a key, as long as there is an error in the code, I hear a sound in VSC. How do I turn off this sound notification about an error in the code. I don't want this sound when writing code, and I don't see an option in the settings to turn it off

Dzień Dobry , podczas pisania kodu przy naciśnięciu klawisza tak długo jak jest błąd w kodzie słyszę dzwięk w VSC. Jak mam wyłączyć to powiadomienie dzwiękowe o błędzie w kodzie. Nie chcę tego dzwięku podczas pisania kodu , a nie widzę opcji w ustawieniach o możliwosci wyłączenia 

pozdrawiam 

Adrian Mańczak
manczakadrian@gmail.com

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

```[tasklist]
### Tasks
```

**Comment by ManczakAdrian** [comment]
Good day, when writing code, when pressing a key, as long as there is an error in the code, I hear a sound in VSC. How do I turn off this sound notification about an error in the code. I don't want this sound when writing code, and I don't see an option in the settings to turn it off

**Comment by lszomoru** [comment]
@ManczakAdrian, can you please use [extension bisect utility](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to track down the possible extension causing this? Thanks!

**Comment by ManczakAdrian** [comment]
I've stopped my extension, but I still have this irritating sound always when I move the cursor from one letter to another. how do I switch all sounds which coming from VSC?

**Comment by lszomoru** [comment]
Adding @meganrogge to see if this sounds are related to any accessibility features.

**Comment by meganrogge** [comment]
You can check your `accessibility.signals.*` settings, sounds like you've modified one or more of those. Alternatively, you can set `accessibility.signalOptions.volume` to zero. If it's coming from VS Code, that'll fix it. Otherwise, maybe check your extensions.

**Comment by ManczakAdrian** [comment]
It helps. I fixed. Thank you for your help

 

Regards

 

Adrian
