### ISSUE TITLE
Freeze when dealing with long (unbreakable) strings

### ISSUE THREAD

**Issue by kwazel** [Microsoft/vscode#22651]
- VSCode Version: 1.10.2
- OS Version: Windows 6.1 (Build 7601), Windows 10 Version 1607 (OS Build 14393.0)

Steps to Reproduce:

1. Open a C# file with a long string (e.g. the attached file with extension .cs)
2. Syntax coloring may start but not progress past the long string
3. Visual Studio Code will become unresponsive

[crasher2.cs.txt](https://github.com/Microsoft/vscode/files/843674/crasher2.cs.txt)

**Comment by aeschli** [comment]
This issue was moved to dotnet/csharp-tmLanguage#48
