### ISSUE TITLE
Incorrect syntax highlighting when a varible name ends with 'var' in Go mode

### ISSUE THREAD

**Issue by louyihua** [Microsoft/vscode#22654]
- VSCode Version: 1.11.0-insider & 1.10.2
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Create/Open a code file written in Go
2. Choose `Go` as the current syntax highlighting mode
3. Write a function definition as follows:
```go
func fnName(avar string, bval bool, cvar int, dval rune) { }
``` 
Or, a varible definition as follows:
```go
var aval, bvar string
``` 
On either case above, the syntax highlighting goes wrong after the varible whose name ends with `var`. Snapshots are listed below:
![1 10 2](https://cloud.githubusercontent.com/assets/1275238/23941086/77056e12-09a2-11e7-9962-341257bd4dab.png)
![1 11 0](https://cloud.githubusercontent.com/assets/1275238/23940988/f9cb3396-09a1-11e7-8794-8884d64311de.png)

The reason should be caused by misinterpretting the trailing part of a varible name (`var`) as the keyword `var`.

**Comment by ramya-rao-a** [comment]
@50Wliu Could this in any way be related to the various `var` related issues you were looking at in the atom grammar for Go?

cc @joefitzgerald

**Comment by 50Wliu** [comment]
Yes.  It's high-up on my todo list and I should be finishing up that PR soon.

**Comment by ramya-rao-a** [comment]
Cool, is there any particular issue in the atom grammar repo you'd prefer to link this to?

**Comment by ramya-rao-a** [comment]
Thanks!

**Comment by louyihua** [comment]
@50Wliu
I've added some change suggestions to your PR at https://github.com/atom/language-go/pull/111
It should be able to fix the bugs related to `type` and `var`, including this one.

**Comment by 50Wliu** [comment]
@ramya-rao-a This has been fixed in language-go.  A new version should be published within the next week.

**Comment by ramya-rao-a** [comment]
Thanks @50Wliu
