### ISSUE TITLE
Environment Variables Problems in Terminal

### ISSUE THREAD

**Issue by DashBing** [microsoft/vscode#226510]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version: Windows_NT x64 10.0.22631
- PowerShell Version: 7.4.4

Steps to Reproduce:

1. Start a VSCode session
2. Add some path which have executable program under it to the Path of Enviroment Variables
3. Then start the terminal and try to run these files

If you try to restart the terminal session to fix this, it won't work. Even when you use the command "Reload Window" it doesn't work. However, this can be fixed when you close all running VSCode sessions and then open them, or when you update an extension and require a restart. But when I open a lot of VSCode sessions I need to close them all, which is very cumbersome.

You can also add a new command that can restart VSCode just like the "restart" when updating an extension.
For this, I just opened a new issue there: #226511

**Comment by meganrogge** [comment]
Thank you for reporting this issue. We understand that it can be cumbersome to restart all VS Code sessions to apply changes to environment variables.

The reason why restarting the terminal session or using the "Reload Window" command does not work is that environment variables are inherited from the parent process. When you start a new terminal session or reload the window, the environment variables are not reloaded from the system but are inherited from the VS Code process that was initially started. This means that any changes to the environment variables made after VS Code was started will not be reflected in the terminal sessions.

To apply changes to environment variables, the entire VS Code process needs to be restarted.
