### ISSUE TITLE
Console in Developer Tools no longer shows font Consolas after update to VSCode 1.92

### ISSUE THREAD

**Issue by md-base-t** [microsoft/vscode#226555]
Type: <b>Bug</b>

The **console** in the VSCode-intern **Developer Tools** window (CTRL+SHIFT+I) shows now font `Courier New` (probably Courier New).
Compared with the prior font `Consolas` I find Courier New harder to read.
Or is there a configuration option to change the font for the Developer Tools console?

Developer Tools console font 

- till VSCode 1.92:  `Consolas`
- in VSCode 1.92:   `Courier New` (probably)

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.11GB free)|
|Process Argv|--log info|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
json-viewer|Dut|0.1.0
vscode-commands|fab|2.0.2
thefoldingstuff|geo|0.2.1
vscode-menu-builder|kyl|1.0.2
vscode-plugin-keyboard-shortcut-eval-custom-javascript-codes|Lia|1.0.13
vscode-language-pack-de|MS-|1.92.2024081409
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.1
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
powershell|ms-|2024.2.2
multi-command|ryu|1.6.0
vbsvscode|Ser|1.2.1
memento-inputs|spa|1.0.0
vscode-autohotkey2-lsp|thq|2.4.9
vscode-inline-values-powershell|Tyl|0.0.7
vscode-autohotkey-debug|zer|1.11.0

</details>

**Comment by deepak1556** [comment]
Nope we don't have an option to configure developer tools font settings, but you can customize via a devtools extension.

**Comment by md-base-t** [comment]
Thank you deepak1556 for the reply!

But was the change to the (old serif) font `Courier New` intended or is it a bug and will be fixed in the future back to font `Consolas`?

**Comment by deepak1556** [comment]
It would be a change in https://chromium.googlesource.com/devtools/devtools-frontend which is bundled as part of the runtime and not something we manage directly.
