### ISSUE TITLE
Can't create a partial profile

### ISSUE THREAD

**Issue by laszukdawid** [microsoft/vscode#226563]
I can create a new profile from scratch but I cannot create a partial profile.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9)
- OS Version: Ubuntu 24.04 (OS: Linux x64 6.8.0-41-generic)

Steps to Reproduce:

1. Click bottom right "Manage" -> navigate through "Profile (Default) to "New Profile"
2. Click on any checkbox from "Choose what to configure in your Profile"
3. All checkboxes are now unchecks and validation warning shows up under Profile name "The profile should have at least one configuration."

Clicking directly within the checkbox only seem to highlight area directly around the checkbox. Clicking anywhere else in the settings checkboxes area highlights the whole settings area. (Hovering over options highlights specific lines.)

Inputting profile name or selecting "Copy from" work but I cannot profile. If I didn't click on any checkbox then all is fine.

**Comment by sandy081** [comment]
/duplicate 

https://github.com/microsoft/vscode/issues/224788

Sorry for breaking this experience. Please use the [New Profiles UI](https://github.com/microsoft/vscode/issues/224788#issuecomment-2274305778) as the workaround.
