### ISSUE TITLE
Can you support phpdoc comment

### ISSUE THREAD

**Issue by WayneLone** [Microsoft/vscode#22650]
Can you support phpdoc comment, like jdoc, see also: https://www.phpdoc.org/, when I  type `/**`

**Comment by bmewburn** [comment]
Is this something that would be done in an extension or in vscode?

**Comment by roblourens** [comment]
if you mean something like autopopulating a phpdoc section from info in a function, this would have to be done by an extension.

**Comment by WayneLone** [comment]
Yeah, I found a vs code extension `PHP DocBlocker`, Thanks for your answer
