### ISSUE TITLE
Allow snippets to control the scope to which they are applicable

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#22661]
We know have solid information about the current position/cursor being in a *string*, in a *comment*, in a *regex*, and elsewhere. We should expose this to snippet authors such that their snippets can express where they want to show

**Comment by jrieken** [comment]
Streck for march...

**Comment by CoenraadS** [comment]
Could exposing this information about an arbitrary position being a string/comment etc also be available as an extension API?

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/22661#issuecomment-286776398 that's actually a lot, lot more complex because token can change a lot while you type and we would need to eagerly synchronize that to the extension host process which is quite expensive. There are idea about tokenising in the ext host but nothing real yet

**Comment by jrieken** [comment]
Idea is to have `.code-snippet`-files which contain a `scope` attribute (similar to how others do it). Unsure yet if such files should be just one snippet or multiple...

**Comment by jrieken** [comment]
closing this as dupe of #13182
