### ISSUE TITLE
"Expand selection" on a call expression doesn't correct expand to multiline arguments

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#226604]
Given 

```typescript
/* foo */

des/*CURSOR*/cribe([
	1, 2, 3
])
```

# Expected

Invoking "expand selection" eventually expands the selection to the whole call expression, ie 

```typescript
/* foo */

<SELECTION>describe([
	1, 2, 3
])</SELECTION>
```

# Actual

Selection after the current line selection (ie `describe([` ) jumps to select whole file.

# Versions

Version: 1.93.0-insider
Commit: e81aceaa07bab1ccdc94deae04168c8bd062f0de
Date: 2024-08-26T05:04:02.640Z
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

Typescript nightly v5.7.20240825

**Comment by mjbvz** [comment]
Hm I'm not seeing this:


https://github.com/user-attachments/assets/d1e7e765-f349-42d5-91ca-97a08d61fb3b


What's the language mode of the file?

**Comment by ulugbekna** [comment]
This's weird. I can't repro today either. Sorry for the noise
