### ISSUE TITLE
Test: call stacks in the testing view

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#226684]
Refs #214488

- [x] anyOS @deepak1556 
- [x] anyOS @andreamah

Complexity: 4
Roles: Developer, Engineering Manager

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23226684%0A%0A&assignees=connor4312)

---

We now have API to support display call stacks associated with test failure messages. Please:

1. Read through the API for `TestMessageStackFrame` and `TestMessage.stackTrace` and see that it makes sense
2. Try out the UI. I've adopted it for unit tests in the VS Code repo. Create a failure in a test, or code that a test calls, and see the stack trace view.
    - Note that if the top stack frame is the same location where the failure happened (e.g. an assert) this is automatically hidden since that case just duplicates the code you're already looking at. For best testing of the UI, create a failure that happens a few frames deep.
3. Verify that its display inside the peek view is correct, as well as the Test Results view when you click on the individual failure.
4. Verify the various UI works as you would expect it to.
5. If you would like to play around with the API yourself, you can do so in the [selfhost extension](https://github.com/microsoft/vscode/blob/17de21ac6ee117c005426ef9beb5ee48e4ed7871/.vscode/extensions/vscode-selfhost-test-provider/src/testOutputScanner.ts#L315) or the [sample test provider](https://github.com/microsoft/vscode-extension-samples/blob/a11599ca990d239073f4b9978723800d8565d9fb/test-provider-sample/src/testTree.ts#L112).

**Comment by andreamah** [comment]
Nice! 🎉
