### ISSUE TITLE
Problems with Russian localization on Debian server

### ISSUE THREAD

**Issue by akellavk** [microsoft/vscode#226650]
After the latest update 1.92.2 I noticed that if you work in VS Code via Remote SSH, the Russian language is partially applied. For example, if I work remotely - in Problems it is written in English.
![Problem_VSCode_ru](https://github.com/user-attachments/assets/0f54469c-0243-4055-a445-0d370ffb14d8)

 At the same time, if I work locally, the Problems are written in Russian. 
![Problem_VSCode_ru_2](https://github.com/user-attachments/assets/94e59668-5634-4953-bcb4-7b05c81b4566)

P.S. I tried deleting the vscode-server folder on the server and reinstalling all Exstension.

**Comment by TylerLeonhardt** [comment]
This looks related to https://github.com/microsoft/vscode/issues/151000 the locale doesn't seem to get applied on the remote side and so English is used. Marking as a duplicate since they have the same symptoms.
