### ISSUE TITLE
Add accessible view for getting started walkthroughs

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#226642]
In order to make the walkthroughs screen reader friendly, we should add accessible view support.

**Comment by bhavyaus** [comment]
@meganrogge for walkthroughs steps which include markdown, should we consider exposing the markdown content in the accessible view also?

**Comment by meganrogge** [comment]
Yes @bhavyaus

**Comment by bhavyaus** [comment]
> [@meganrogge](https://github.com/meganrogge) for walkthroughs steps which include markdown, should we consider exposing the markdown content in the accessible view also?

Tracking https://github.com/microsoft/vscode/issues/228007
