### ISSUE TITLE
Use Settings Editor Viewer for Editing Keybindings

### ISSUE THREAD

**Issue by sgtoj** [Microsoft/vscode#22660]
While editing my keybinding today, I noticed the editing experience is inconsistent when compared to editing settings. Is it possible make the settings and keybinding editing view and experience the same.

**Comment by sandy081** [comment]
Duplicates #18095. 

@sgtoj I am currently working on this. Current insiders has already first cut implementation of new keybindings customisation editor. Please try it and provide the feedback. You can get the latest insiders here - http://code.visualstudio.com/insiders
