### ISSUE TITLE
Seti Icons seem badly rendered

### ISSUE THREAD

**Issue by gmckeown** [Microsoft/vscode#22667]
- VSCode Version: 1.10.2 and 1.11.0 Insider build (b9857a)
- OS Version: Windows 10 Build 14393.693

Steps to Reproduce:

1. Enable vs-seti icon set
2. Create a file with .sh extension (for example)

Icon is simply a grey square; the [Seti icon set for Atom](https://atom.io/packages/seti-icons) suggests there should be some detail displayed.

Here's an enlarged comparison with VSCode on top and the version from the Seti summary below:

![comparison](https://cloud.githubusercontent.com/assets/22765233/23946498/83e0a050-0972-11e7-99ab-03fcf0e93ee7.png)

And here's a rendering of the original [Seti shell.svg](https://github.com/jesseweed/seti-ui/blob/master/icons/shell.svg) using Inkscape:

![2017-03-15 12_44_45-shell svg - inkscape](https://cloud.githubusercontent.com/assets/22765233/23949020/698678c8-097d-11e7-9bab-a0a64557d7a1.png)

Loading the seti.woff file (in eval version of FontCreator) shows the icons to be poorly rendered at larger sizes as well, which I assume is due to a problem converting from the SVGs to WOFF?

A selection of the icons as viewed in FontCreator:
![2017-03-15 13_09_54-fontcreator 10 1 unregistered - seti woff - seti](https://cloud.githubusercontent.com/assets/22765233/23949950/36aed0c2-0981-11e7-820c-d75fcccb47a4.png)

Here's the C# Icon from the WOFF:
![2017-03-15 13_11_04-fontcreator 10 1 unregistered - seti woff - seti](https://cloud.githubusercontent.com/assets/22765233/23949958/3da1ac38-0981-11e7-958d-c020ffcba5da.png)

And here's the same icon from the original SVG (viewed in Inkscape):
![2017-03-15 13_12_39-c-sharp svg - inkscape](https://cloud.githubusercontent.com/assets/22765233/23949967/431fcd3e-0981-11e7-9309-0e24f987830f.png)

**Comment by gmckeown** [comment]
Digging a bit further, I assume you've used the [seti.woff](https://github.com/wyze/atom-seti-icons/blob/master/styles/_fonts/seti/seti.woff) file from the [atom-seti-icons](https://github.com/wyze/atom-seti-icons) project, which in turn takes them from the [seti-ui](https://github.com/jesseweed/seti-ui) project.

Seti UI uses a [script ](https://github.com/jesseweed/seti-ui/blob/master/gulpfile.js)that converts the good-looking SVG icons into font files, and it appears to be there that the problem occurs. This combines the icons and outputs them into five font files (seti.eot, seti.svg, seti.ttf, seti.woff, and seti.woff2).

Both the TTF and WOFF files have the disfigured glyphs. I don't have tools to open the WOFF2 and EOT formats directly. The seti.svg font file opens in FontForge and shows most of the icons correctly -- CSV and Shell are still missing their detail.

So, ultimately, this seems to be an issue with the conversion of the source SVG icons into a font-file.

**Comment by aeschli** [comment]
@gmckeown Thanks for the analysis. We're take the font directly from the [seti-ui](https://github.com/jesseweed/seti-ui/blob/master/styles/_fonts/seti/seti.woff) project. 
I move the issue there in the hope they can improve the SVG to font conversion.

**Comment by aeschli** [comment]
This issue was moved to jesseweed/seti-ui#401

**Comment by gmckeown** [comment]
I've got a pull request in with Seti UI to resolve this issue -- fix for VS Code I expect will be an updated seti.woff and changes to vs-seti-icon-theme.json to account for some additional icons. With Atom, I was able to just drop the new fonts into the theme's package folder and everything seems to work, but with VSCode, I get this strangeness:
<img width="210" alt="vscode_updated_font" src="https://cloud.githubusercontent.com/assets/22765233/24274818/c6b7a188-1022-11e7-8559-0b14904de220.png">
Any idea how I might correct this?

Updated font can be found in the pull request if you wish to test for yourself: https://github.com/jesseweed/seti-ui/pull/406

**Comment by gmckeown** [comment]
Ignore the above. The mis-alignment was due to an error in one of the source icons that was throwing off the font size normalisation. Seems to all be working in Atom now, and initial tests with VSCode look promising. My assumption is that you'll pull the updated WOFF from the Seti UI project once it's merged. A small preview below :)

<img width="290" alt="vs code updated seti font" src="https://cloud.githubusercontent.com/assets/22765233/24317068/ef372ad8-10eb-11e7-85bc-2d80d9ef5708.png">

**Comment by aeschli** [comment]
@gmckeown Looks great, thanks for your work! I hope your changes get adopted soon so I can pick them up.

**Comment by aeschli** [comment]
@gmckeown I updated the Seti font containing your fixes. Thanks a lot!

**Comment by TheFluffyOne** [comment]
Good stuff! If you do see any vertical alignment issues with the updated font -- per https://github.com/Microsoft/vscode/issues/22667#issuecomment-288894359 above -- there's a separate pull request to address this: https://github.com/jesseweed/seti-ui/pull/409. When the Insiders build updates to include your commit I'll test on the machine that had the issue before.

**Comment by aeschli** [comment]
Yes, I had to manually patch seti-ui to get the vertical alignment correct on windows. Thanks for creating a pull request for that!

**Comment by TheFluffyOne** [comment]
@aeschli Today's Insider build is looking great on the Win10 notebook on which I previously saw the alignment issues :). I'll add a comment here if/when my fix is pulled into Seti-UI.

**Comment by gmckeown** [comment]
Sorry, just realised I left myself logged in to an old account I was in the process of retiring! Previous comments were from me :)

**Comment by gmckeown** [comment]
@aeschli, I don't see mention of the updated icons in current Insiders release notes -- will this make it into 1.12.0?

**Comment by aeschli** [comment]
It's in there, sorry. I'll add a note.

**Comment by aeschli** [comment]
I added a thank you note to the release notes! Thanks again @gmckeown !

**Comment by gmckeown** [comment]
Awesome, cheers!
