### ISSUE TITLE
Dependent extension is not activated if the depending extension gets activated after getting updated

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#226660]
Steps to Reproduce:

1. Have extension A depending on extension B
2. Have extension B current version is incompatible with VS Code and newer version is compatible
3. Opening VS Code with such version does not activate B therefore extension A throws an error that extension B is not activated
4. In the same session, extension B gets auto updated and newer version of extension B gets activated, but the extension A still does not get activated.

**Comment by rzhao271** [comment]
What are some extensions I could verify this issue with?
I can get GitHub Copilot Chat to emit the error in step 2, but GitHub Copilot doesn't depend on it afaik, and I don't know any other extensions depending on it.

**Comment by sandy081** [comment]
To verify:

- Install `hbenl.vscode-mocha-test-adapter` extension. It has a dependency on `hbenl.vscode-test-explorer` which gets installed too
- From `hbenl.vscode-test-explorer` extension - Install one version older using `Install Specific Version...` action in the context menu. This is to show **Update** action on this extension.
- Open Extension Folder (F1 > Open Extensions Folder), open the package.json of the `hbenl.vscode-test-explorer` extension that you just installed (Make sure this is the same version as you installed from Install Specific Version... action. Remove the `engines` property and save it. 
- Reload the window. You should see both  `hbenl.vscode-test-explorer` and `hbenl.vscode-mocha-test-adapter` extensions disabled in the view
- Click Update action on  `hbenl.vscode-test-explorer`
- Verify that both extensions are enabled after update is finished.
