### ISSUE TITLE
Element already has context attribute: title

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#226622]
The element is:

```
<div class="title tabs show-file-icons"
```

Seems to be related to having `workbench.editor.pinnedTabsOnSeparateRow` enabled.

**Comment by benibenj** [comment]
This happens because we create 2 scoped context key services on the same html element when running with 2 tab bars.

**Comment by Tyriar** [comment]
Please look at this during October, I've been seeing it for quite a while now and creates noise in the console.
