### ISSUE TITLE
Convert indentation on save

### ISSUE THREAD

**Issue by kirillku** [Microsoft/vscode#22666]
- VSCode Version: 1.10.2
- OS Version: Win 10

It would be nice to add option to automatically change indentation on save.
Something like `"editor.convertIndentationOnSave": true`.

Like this sublime extension : [ExpandTabsOnSave](https://github.com/bubenkoff/ExpandTabsOnSave-SublimeText).

**Comment by jrieken** [comment]
This should be done as extension. The APIs are all in place

**Comment by VitorLuizC** [comment]
[EditorConfig](https://github.com/editorconfig/editorconfig-vscode) does it well.
