### ISSUE TITLE
TextEditor::edit, returns a Promise that shows edits could be applied, but how to determine when they are applied

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#226656]
[`TextEditor::edit`](https://code.visualstudio.com/api/references/vscode-api#TextEditor.edit) returns

> `Thenable<boolean>` A promise that resolves with a value indicating if the edits **could** be applied.

How do we determine when the edits **are** applied?

If I `await` the `Thenable` does it mean:

* the edits will sometime in the future be applied, when extension command returns

or

* the edits are applied

**Comment by jrieken** [comment]
When the promise/thenable resolved and returns `true` than the edits have been applied
