### ISSUE TITLE
Test sorting comments in Comments view

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#226657]
Refs: #149449

- [ ] macOS @kieferrm
- [x] linux @chrmarti
- [x] windows @Tyriar

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23226657%0A%0A&assignees=alexr00)

---

The easiest way to test this is with the GitHub Pull Request extension, but you can test it with any extension that provides comments with a date.

1. Install GitHub Pull Requests
2. Open a GitHub repository in VS Code
3. Check out a PR with comments, or leave some comments on a PR
4. Open the Comments view
5. You can find the sorting actions in the filter icon of the view title area. Try out the sorting options and verify they do what you'd expect.

**Comment by alexr00** [comment]
It is by design, but it's a good idea: https://github.com/microsoft/vscode-pull-request-github/issues/6167

**Comment by kieferrm** [comment]
No new findings compared to @Tyriar's https://github.com/microsoft/vscode/issues/226764.
