### ISSUE TITLE
Recognize altKey correctly on macOS

### ISSUE THREAD

**Issue by AriaMinaei** [Microsoft/vscode#22664]
- VSCode Version: 1.11.0-insider (6a002910356c6e087dd93e819e4ad54c68b9857a)
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. Define this keybinding and try it: `{"key": "alt+u", "command": "cursorHome"}`

What's expected: For `cursorHome` command to be invoked.
What actually happens: This character gets written: ¨

Atom used to have this problem too, which was solved by this PR: https://github.com/atom/atom-keymap/pull/163

More context: https://github.com/atom/atom/issues/13043

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in today's Insiders build) appear to behave correctly for this key combination. I have tested under the US layout.
