### ISSUE TITLE
VS Code Crashes Randomly with Error Code 132

### ISSUE THREAD

**Issue by rejahn** [microsoft/vscode#226658]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2 and also on insiders 
- OS Version: Fedora 40

![image](https://github.com/user-attachments/assets/50f71985-bee7-4c1c-a255-e4a7bdbd0727)

"The window terminated unexpectedly (reason: 'crashed', code: '132')"

I'm experiencing random crashes in Visual Studio Code, most commonly when opening the application. The error consistently shows code 132. When the crash occurs and I click 'Reopen', VS Code crashes again immediately. However, if I select 'Close' and manually launch VS Code again, it works as expected, at least until it crashes once more.

The crashes don't happen every time I open VS Code but occur frequently enough to impact workflow. I have observed that the crashes are more frequent, if  the screen was locked. I cant remember this happening when launching from command line, but when opening using the desktop entry provided within the installation.

This issue might be related to another running process on my system, though I haven't been able to pinpoint the exact cause. I wonder if it has happen to someone before.

**Comment by tamuratak** [comment]
It might be duplicate of  #221886. See https://github.com/microsoft/vscode/issues/221886#issuecomment-2271739803

**Comment by rejahn** [comment]
I am now using kernel `6.10.6`. If it happens again, I will reopen the issue. Thank you!
