### ISSUE TITLE
Restrict Intellisense

### ISSUE THREAD

**Issue by DarrylD** [Microsoft/vscode#22665]
While using javascript, ~90% of the suggestions I feel are useless. I seem to only use suggestions based on the project (ex: variables, methods, etc...) and snippets. 

Is it anyway to restrict Intellisense to remove the generic suggestions?

I turned off `quickSuggestions` to prevent seeing the tons of suggestions but, I realized I still would like to see the suggestions specific to the open project.

**Comment by weinand** [comment]
Have you tried to configure the "editor.wordBasedSuggestions"?

**Comment by DarrylD** [comment]
@weinand I'm not exactly sure what that's for. The description just says `// Enable word based suggestions`

I just set it to false and I'm not sure if anything changed.

**Comment by weinand** [comment]
What version of VS Code are you using?
For me the setting looks like this:
![2017-03-15_15-27-47](https://cloud.githubusercontent.com/assets/1898161/23953180/1c357ec2-0994-11e7-9d86-f6966cca8b4c.png)

**Comment by DarrylD** [comment]
I'm using ` 1.10.2 (1.10.2)` on Mac

is `other` the all of the extra suggestions i mentioned?

**Comment by DarrylD** [comment]
This is what I have... 

![screen shot 2017-03-15 at 10 52 28 am](https://cloud.githubusercontent.com/assets/1310383/23954384/86e6e44e-096d-11e7-8b03-6bdc190bdef3.png)

**Comment by weinand** [comment]
Yes, we'll expand this option in 1.11.0 (current Insiders).
Setting editor.wordBasedSuggestions to false eliminates all generic (text based) suggestions. These are the ones with the 'abc' icon.

**Comment by DarrylD** [comment]
I'm not seeing any 'abc' icons. Something new in 1.11.0 also?

This is what I see when I type `a`. In this case, I only care about the first instance of `api` since I have an `import` for it.

![screen shot 2017-03-15 at 11 08 52 am](https://cloud.githubusercontent.com/assets/1310383/23955317/f1a232dc-096f-11e7-90fb-2fe50797cf18.png)

**Comment by weinand** [comment]
No, 'abc' suggestions exist since the beginning of time. They are what the "editor.wordBasedSuggestions" setting controls. But it seems that they are disabled for JS/TS automatically.
You can seem them in plain text files:

![2017-03-15_16-16-20](https://cloud.githubusercontent.com/assets/1898161/23955655/d36b732a-099a-11e7-998d-9a1df41d63eb.png)

I've assigned the issue to someone from the VS Code JS/TS team.

**Comment by mjbvz** [comment]
The word based suggestion issue sounds related to #21611

As for the original question, I suspect that the suggestions that you are seeing are coming from the DOM or from the standard library. Try creating a `jsconfig.json` in the root of your project with the content:

```json
{
  "compilerOptions": {
      "lib": ["es2015"]
   }
}
```

This instructs our language support to only include typings from the es2015 standard library in your suggestions. To disable all builtin suggestions, use `"lib": []`
