### ISSUE TITLE
Test: Notebook `cmd+d` multi-select typing and deleteLeft editing

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#226681]
Refs: #141673, #226545

- [x] anyOS @bpasero  
- [x] anyOS @rebornix 

Complexity: 1

author: @Yoyokrazy 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23226681%0A%0A&assignees=Yoyokrazy)

--- 

## Summary
Notebooks have multi-select that can be triggered via cmd+d

## Steps to Test:
- Go wild
- Try to break things like:
  - decoration states
  - being in editing state without decorations
  - undo-redo stacks (if the latter ref PR merges)

--- 
Thanks for testing!

**Comment by bpasero** [comment]
@Tyriar fyi somehow author got assigned to test 🤔

**Comment by Tyriar** [comment]
> @Tyriar fyi somehow author got assigned to test 🤔

@sandy081 FYI

**Comment by Yoyokrazy** [comment]
Sorry about this, assigned this tpi to the two of us manually. This was primarily to selfhost and track issues before pushing it to the entire team, so no bug with assignment actually happened. Sorry about having to interpret my half-written thoughts @bpasero 😅

**Comment by sandy081** [comment]
I have thought so that you assigned it to yourself for a reason. Hence, I also believe that it makes sense to allow assigning the author self explicitly to the test plan item.

**Comment by Tyriar** [comment]
:+1: I've also done this once or twice in the past to give myself some dedicated time to test a feature on a different OS to my main. It makes sense in special circumstances.

We could possibly avoid this confusion if the test plan tool added ` (assigned self explicitly)` to the user?

**Comment by sandy081** [comment]
Actually, it makes sense to add such a label for all assignments, author has added explicitly

**Comment by bpasero** [comment]
@Yoyokrazy oh ok, that explains a lot. sorry for acting up, now it makes sense :D
