### ISSUE TITLE
Test type acquisition and full project intellisense for JS/TS

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#226653]
Test for #182791

- [x] anyOS @alexdima
- [x] anyOS @Yoyokrazy

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23226653%0A%0A&assignees=mjbvz)

---

This iteration we enabled type acquisition on `vscode.dev` for JS/TS. This means:

- We can provide intellisense for packages listed in the `package.json`

- For JS files, we can provide intellisense for imported files even if they aren't in the `package.json`, i.e. you can type `import $ from 'jquery';` and start getting jQuery IntelliSense

With these two features on, we've also enabled semantic error reporting again

## Testing
For this test plan item, try out this new support on https://insiders.vscode.dev and make sure it works as expected. Test in Chrome/edge.

Some basic areas to test

- Open a small/medium sized TS project from github
    - You get IntelliSense for the module imports
    - Confirm auto imports work
    - You should get semantic/typings errors
    - You can use `go to definition` and `find all references` on types from modules

- Try doing the same but this time opening a folder from your local machine

- Create a loose js file. Try adding an import for a third party library and confirm you get IntelliSense for it after the typings are installed

## Known limitations
- Safari currently doesn't support this. The nightly safari should but for 

- Currently only tested for small/medium projects. Larger project, such as `vscode`, will likely work but may take a while to load. We're working on implementing caching to support them better

**Comment by alexdima** [comment]
Very cool!
