### ISSUE TITLE
New Profiles creation work removes the flyout to easily switch between profiles

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#226629]
With the new work done to change profile creation, it seems like the flyout to quicky change profiles has disappeared. Referring to the settings/profile icon in the bottom left of a standard vscode layout

It feels fairly cumbersome to have to open the dedicated profiles editor to just change between profiles.

**Comment by sandy081** [comment]
I understand that switching profile from the gear menu is handy and has got into the muscle memory for profiles users. The new Profiles editor has brought completeness to the Profiles feature and we would want this as the single main entry in the Global Activity menu like other main features entries there.

I would recommend to use following commands as replacements for quick access:

> Profiles: Switch Profile...
> Profiles: New Window with Profile...
> Profiles: Open {Name} Profile

Last two commands are useful if you want to open a window with a specific profile
