### ISSUE TITLE
vscode terminal difficult to use!

### ISSUE THREAD

**Issue by iqianxing** [Microsoft/vscode#22674]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.15048
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.0|;

---

Steps to Reproduce:

1.open the vscode teminal, and type some cmd

2.you can found terminal current input key like bellow:

![difficult to use](https://cloud.githubusercontent.com/assets/2938263/23958048/df58d088-09db-11e7-85c7-4f9539413e19.jpg)

**Comment by sgtoj** [comment]
Closing the terminal (exit Trash icon) and opening a new one will resolve this issue.

This has happen to many times. In fact, it is reproducible. After installing Python modules using `pip`, will cause the terminal to behave similarly or cause carriage-return without line break after some unknown line character number. 

```powershell
# execute from PowerShell
python -m pip install ptvsd
# now try using terminal normally
```

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665

**Comment by iqianxing** [comment]
thank u
