### ISSUE TITLE
Profile Editor List Actions Feedback

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#226732]
I personally think the wrong actions are being shown on the profile list items. 
- The delete action doesn't need to be so prominent and cold be moved to the context menu and there could be a `Delete` button at the bottom of the profile page.
- I think switching the profile of the active window should be the primary action and the open in new window action should be an alternative action (press Alt) of the primary and also be visible in the context menu.

<img width="1159" alt="image" src="https://github.com/user-attachments/assets/4fd14bce-9ebf-4aaf-a2fd-57117f3fbf66">

**Comment by sandy081** [comment]
More feedback from @benibenj 

I find the `Use for ...` actions very confusing in the context menu. 

- I think the `Use for Current Window` should not be a toggle and should be renamed to `activate` or something similar and be disabled when it's the current active one. I would also not add the checkbox in the profile editor on the right but move it to the top as a prominent action. 
- Regarding the `Use for New Windows`, I don't really think it has to be in the context menu and could be replaced by the action `Open in new Window`.

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/81e85b55-ee1a-4cc9-8b9d-deeef9971aa3">

**Comment by sandy081** [comment]
- Moved Delete Action to Secondary Actions
- Moved Use profile for current window action to Primary Actions
- Removed Use profile for current window entry from the Profile Content

![Image](https://github.com/user-attachments/assets/1721c443-0c57-4deb-b07b-41db6b896003)


Adding Delete and Export buttons in the bottom is an interesting idea, but I would hold on it because there are plans to add a workspaces table in the content.

**Comment by benibenj** [comment]
This is already a great improvement! 

I still don't like the `Use profile for current window` wording. I think it could be simplified to just `use profile`, `activate profile` or `switch profile`. 

Also, `Use for New Windows` doesn't seem like a common action and is not that easy to understand without the description of the action. Also, from the left list it is not possible to see which profile current is being used for new windows. Due to these reasons I think it should be removed from the context menu. Users can still configure it in the profile editor to the right.
You could also consider removing it from the profile editor on the right side and add a dropdown somewhere with which the user could switch the `Default Profile` (Use for New Windows)

**Comment by sandy081** [comment]
> I still don't like the Use profile for current window wording. I think it could be simplified to just use profile, activate profile or switch profile.

It is now a primary action (icon), so it would be helpful to be verbose on the title - **Use this profile for current window**.

> Also, Use for New Windows doesn't seem like a common action and is not that easy to understand without the description of the action. Also, from the left list it is not possible to see which profile current is being used for new windows. Due to these reasons I think it should be removed from the context menu. Users can still configure it in the profile editor to the right.

I had similar thought but somehow I did not go for it. I am convinced to remove it now.

> You could also consider removing it from the profile editor on the right side and add a dropdown somewhere with which the user could switch the Default Profile (Use for New Windows)

I would prefer to have it as it is - this is helpful to configure a profile. What is missing here is the information about the current default profile used for new windows - I have an issue for that where I will tackle.

**Comment by ericzhao007** [comment]
I want to customize management extensions, which cannot be solved
