### ISSUE TITLE
Not being able to use GitHub Copilot chat

### ISSUE THREAD

**Issue by adam-vukovic** [microsoft/vscode#226724]
Type: <b>Bug</b>

I am signed in with my GitHub account that has Copilot, but I am unable to use my chat for some reason. It just asks me to sign in over and over again. Then I sign in and authenticate my account and I still see the sign in button. I tried restarting everything but it doesn't work.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1245U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.64GB (8.11GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Student/OneDrive/Desktop/gitlab/speac --crash-reporter-id 4c83be8f-f676-4934-a20b-b3888b0ea9c5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.223.0
copilot-chat|Git|0.18.1
vscode-edit-csv|jan|0.9.2
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by rockpyer** [comment]
same issue. tried switching to last version, latest version and pre-release versions.   This just cropped up with in the last week or so

**Comment by rockpyer** [comment]
same issue. tried switching to last version, latest version and pre-release versions.   This just cropped up with in the last week or so
<img width="786" alt="Screenshot 2024-09-02 at 6 15 18 PM" src="https://github.com/user-attachments/assets/8327ff06-17af-4963-b695-f1762a8c44df">

**Comment by TylerLeonhardt** [comment]
duplicated of https://github.com/microsoft/vscode-copilot-release/issues/1444#issuecomment-2299464817
