### ISSUE TITLE
Profiles: use this profile for current window

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#226710]
This UI:

![Image](https://github.com/user-attachments/assets/1ea405f4-9aeb-4d18-965e-c33cbb71e6fb)

Comes a bit to my surprise, should it be a button rather than a setting like thing? My feeling was its a setting but it actually performs an action only for the current window.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/226732
