### ISSUE TITLE
Feature request: Select closing bracket, show function/array/etc... opening tag with indent-guide hover-highlight.

### ISSUE THREAD

**Issue by jdc-cunningham** [Microsoft/vscode#22675]
![example](https://cloud.githubusercontent.com/assets/11015467/23958188/41a0a3c8-096f-11e7-8bd7-f9bd720a5712.png)

It's probably a bad thing I found the support request for VS code haha.

So I have this problem where when working with very long functions, I click on the closing bracket and I don't know what function that is. So I will hover over the indent guide and scroll up, until I run into the opening bracket to figure out what it is. It might be an object for example. Also applies to `<div>` tags. Anything "out of view" of the coding pane.

Regarding the hover-highlight on the indent guide, that would be a cool feature if you could hover on the indent guides and highlight them (along side with the feature above).

The highlighting part might be redundant/unnecessary if you can show the opening tag name so you don't have to trace by scrolling upwards.

If this has already been addressed, my apologies.

Attached is an image to show the rough functionality.

**Comment by alexandrudima** [comment]
Let's track in #14017.
