### ISSUE TITLE
Buttons in chat are visually quite noisy

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#226722]
![Image](https://github.com/user-attachments/assets/c64a39fc-8f46-4eb9-a215-70ddd4796717)

Why not show this as a command when I hover over the section? Similar to this UI:

![Image](https://github.com/user-attachments/assets/34aa7358-5b67-4ccd-9b17-ffe2fff70330)

**Comment by daviddossett** [comment]
I agree. We could try the command name as a link. Lots of prior art there..

![Image](https://github.com/user-attachments/assets/146f18bf-1563-427d-833e-e82fd4bd3c87)

**Comment by rzhao271** [comment]
Moving off of milestone
