### ISSUE TITLE
Polish UI of inline-edits toolbar

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#226750]
We have this to work with inline edits now:

![Image](https://github.com/user-attachments/assets/da709ab3-6d74-4cbf-858c-a0e3101fd5a8)

Maybe the actions could be made more explicit to be a kind of toolbar, like we do in the chat over source code:

![Image](https://github.com/user-attachments/assets/38a6712f-a068-43c2-b3da-16e3845e6291)

**Comment by jrieken** [comment]
related https://github.com/microsoft/vscode-copilot/issues/7547
