### ISSUE TITLE
Provide a `reason` when `applyEdit` returns `false` (plus, clarify the docs)

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#226746]
Firstly, I think the docs here are a little confusing. `applyEdit` resolves with a `boolean` that indicates whether the edit was applied, but the docs suggest it just doesn't resolve until they _could_ be applied.

![image](https://github.com/user-attachments/assets/965fd0e7-4965-4180-b061-dd8df7de8cc4)

Secondly, I think there should be a way to obtain a _useful reason_ for why an edit could not be applied. I was trying to debug an issue with edits not being applied that turns out to be that the server was providing a `null` version number for a document where it should have had a `2`. I _believe_ that's why the edit failed to apply, but I can't be sure (and I've not yet been able to reproduce this issue).

It would be nice if VS Code could provide a reason for returning `false`, such as "Edit was for `foo.txt` version `null` but current version is `2`". Using `Thenable<boolean>` for the return type unfortunately makes this difficult (if it was an object a new field could be added in a non-breaking way), but I think as a debugging tool that this is useful enough that it should be considered another way (such as `tryApplyEdit()` that returns an object, and `applyEdit can just call it and read the `applied` boolean from it?).

**Comment by FMorschel** [comment]
> I believe that's why the edit failed to apply

I was following the works on https://github.com/Dart-Code/Dart-Code/issues/5218 and just to clarify, this was the problem. It was having some problems with the Windows Drive letter case to find the file.

But in any case, this would be a great addition so we can have more clear explanations as to why it is not working.
