### ISSUE TITLE
No drag and drop text support in editor?

### ISSUE THREAD

**Issue by wmjordan** [Microsoft/vscode#2267]
Ordinary editors nowadays allow us to drag and drop text inside/outside it. But in VS Code, there's no such a feature. I tried to find out settings in the user settings configuration file, but did not find any setting to activate it.

**Comment by diryboy** [comment]
+1, I also miss this feature. Commenting to get notification.

**Comment by senjacob** [comment]
https://github.com/Microsoft/vscode/issues/1046

**Comment by alexandrudima** [comment]
Let's track in #1046

**Comment by nblx2k4** [comment]
I miss this feature as well especially that I use it a lot!!

**Comment by agatlin** [comment]
I miss this feature much too. Lack of drag and drop in a modern editor is pretty insane. It is a real time killer.
