### ISSUE TITLE
PowerShell PSEdit support in Integrated Terminal

### ISSUE THREAD

**Issue by kberridge** [Microsoft/vscode#22673]
PowerShell ISE has this useful "psedit" command that allows you to open a file to edit through a remote session (http://www.powershellmagazine.com/2014/12/08/pstip-editing-remote-file-in-powershell-ise/).  I prefer working in VSCode, so it would be great if VSCode could support the psedit command in it's Integrated PowerShell Terminal.

**Comment by kberridge** [comment]
After opening this I learned that _today_ (how's that for timing) the vscode powershell extension released support for the psedit command in their integrated console: https://github.com/PowerShell/vscode-powershell/releases.

It still seems to me that it would be great if this was supported by the default powershell console too, but I don't really understand where the line between the powershell extension and the main editor is in regards to the integrated terminal.

**Comment by Tyriar** [comment]
@kberridge yes I believe the PowerShell extension is just getting into this. We don't ship the best support for many languages by default and defer to extensions as that gives us a few benefits such as:

- It can be owned entirely by another team (in this case the PowerShell team)
- Releases don't need to be aligned with VS Code's release schedule
- It doesn't increase the VS Code's download size
- Loading of the code definitely won't happen unless the use installs it.

/cc @daviwil

**Comment by daviwil** [comment]
@kberridge supporting psedit generally in VS Code is non-trivial and would be a little hacky so I think it's best left to the PowerShell extension.  The PowerShell team has internally discussed providing a more standard psedit function built in to PowerShell but no plans to do it yet.
