### ISSUE TITLE
`TerminalShellIntegrationChangeEvent` has a `terminal` and a `shellIntegration` property

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#226745]
Testing #226655

Reading through the documentation I am under the impression that when the `TerminalShellIntegrationChangeEvent` event fires that terminal has a shell integration (e.g. its property `shellIntegration` is !== undefined). 

Why does the event carry the additional `shellIntegration` property. Aren't they the same?

**Comment by dbaeumer** [comment]
Same for `TerminalShellExecutionStartEvent` and `TerminalShellExecutionEndEvent` event

**Comment by Tyriar** [comment]
It does that to avoid the need for a `shellIntegration?` check or `!` assertion. We could also do some TS magic like `Required<Pick<Terminal, 'shellIntegration'>> & Terminal` but we tend to avoid composing complex types like that to simplify the API.

Closing as designed as this did come up in the API syncs. cc @jrieken
