### ISSUE TITLE
Source Control Graph view: Make the current HEAD more prominent

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#226751]
Testing #226648

Version: 1.93.0-insider
Commit: ff7a154d5e5e9034914f0466420f0f1407f0c95e
Date: 2024-08-27T05:04:20.235Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 5.15.0-119-generic

When looking at the graph view, I'm orienting myself on the commit that represents HEAD. I want to see what's incoming and what the history is.

When there are a lot of incoming commits, I find it sometimes difficult to find that commit.
The bigger blue dot and the crosshair icon visualizes this, but I find it very subtle.

Here I'm on main, but there's an incoming change:

![Image](https://github.com/user-attachments/assets/1876ed9f-1c6e-4a44-8b42-57b02d963e42)

Here I am on a branch, but main and origin/main are much farther

![Image](https://github.com/user-attachments/assets/09e99a28-5820-4f5e-8c32-e92fbc0dc6d2)

For older release I even need to scroll down to find it:

![Image](https://github.com/user-attachments/assets/a2d43e5b-5aa6-42f6-9d3f-a730ac7c8afb)

Steps:
   - switch to an older branch
   - find the curretn commit by manually scroll down

Some ideas:

- Switching a branch should reveal the commit that is HEAD.
- offer an actions in the toolbar that reveal the current head. The icon could use the crosshair icon that is already used to mark head.
- make the item that has head more prominent: Maybe a different background color

**Comment by lszomoru** [comment]
Made the following change to address the feedback:
1. More prominent rendering of the commit circle in the graph
2. HEAD commit subject/author is using bold text
3. Added action to reveal HEAD to the view title

**Comment by aeschli** [comment]
Look great!
