### ISSUE TITLE
Continue with a codespace button does nothing

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#226729]
repro 

1. open insiders.vscode.dev
2. checkout PR https://github.com/jrieken/vscode-tree-sitter-query/pull/16
3. click on Terminal pane
4. click on continue with a codespace -- nothing happens :bug:

https://github.com/user-attachments/assets/4845d787-c21e-4633-bb4a-4dd55179c5a9

**Comment by joyceerhl** [comment]
In your recording it looks like you clicked the Continue in Codespaces button but somehow the Continue in Local Clone option got invoked instead. Does that happen for you every time?

**Comment by ulugbekna** [comment]
> In your recording it looks like you clicked the Continue in Codespaces button but somehow the Continue in Local Clone option got invoked instead. Does that happen for you every time?

I clicked "continue in codespaces" which didn't work, then I clicked on "continue locally" which did. 

Seeing this error in console: 

```
Activating extension 'GitHub.codespaces' failed: document.createElement is not a function.
```

**Comment by joyceerhl** [comment]
I don't see a `document.createElement` in the extension codebase, but I also do not observe any issues using Continue on Codespace in Google Chrome Version 128.0.6613.85 (Official Build) (64-bit). 

1. What version are you on?
2. If you disable all your Chrome browser extensions, do you still see this behavior?

**Comment by ulugbekna** [comment]
> What version are you on?

Version 128.0.6613.84 (Official Build) (arm64)

> If you disable all your Chrome browser extensions, do you still see this behavior?

I can't seem to repro in incognito mode, so maybe that's an extension issue indeed 🤷
