### ISSUE TITLE
Quick Info missing descriptions for own imported functions, objects and primitives

### ISSUE THREAD

**Issue by marbakjs** [Microsoft/vscode#22677]
![quickinfo](https://cloud.githubusercontent.com/assets/26436450/23957939/ed37505c-09a0-11e7-8262-88b2b0bd321e.gif)

**test3.js**
```javascript
/**
 * description of a
 */
function a() {}
export { a };
```
**test4.js**
```javascript
import { a } from './test3';

```

VSCode started with **--disable-extensions**

- VSCode Version: 1.10.2
- OS Version: Microsoft Windows [Version 10.0.14393]

**Comment by mjbvz** [comment]
Thanks. This is being tracked upstream by: https://github.com/Microsoft/TypeScript/issues/11099
