### ISSUE TITLE
can't go to file / file in 'Problems' tab with TSC build task

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#22671]
- VSCode Version: Insiders 6a002910
- OS Version: Windows 

Steps to Reproduce:

Have a tsx file with some errors and a TSC watch task running:

![image](https://cloud.githubusercontent.com/assets/461084/23955212/08942cc2-0978-11e7-95d7-3b02de57e440.png)

after clicking

![image](https://cloud.githubusercontent.com/assets/461084/23955232/165362ce-0978-11e7-950d-96bfa1d9c51d.png)

**Comment by fearthecowboy** [comment]
I get this too.

My `tsconfig.json` isn't in the root of the workspace (I have multiple ts projects in the workspace and build them with `gulp` ) -- I had to filter the output in gulp to expand out the file names to their full path. 

And in c# too now that I think about it, I had to enable full paths output in msbuild.

**Comment by MikeBeaton** [comment]
I get this too. I think this is a general, genuine problem, which would affect anyone who is building a multi-project solution. (I just mean 2 or more projects - a very normal use-case - not  necessarily many many projects.).

E.g. I have a very simple setup of two C# projects. One is a dll, the other is a console project which references the dll.

It all compiles and builds absolutely fine, with default VS Code settings. But if I get any build errors, and then try to double click in the Problems tab to navigate to errors in files within the dll project (i.e. not in the starting project, but any project referenced by it) then VS Code tries to open the file in the wrong location, and gives the error above (offering to create the file for me, in the wrong location!).

Note, this is ONLY a navigation bug (for double-click navigation to errors listed in the Problems tab, that aren't in the starting project). The actual build, the actual errors listed, etc., are all absolutely fine.

**Comment by MikeBeaton** [comment]
@fearthecowboy gives the correct workaround - thank you!

To save others hunting for how to actually do this: in your root directory open the file `.vscode/tasks.json` and add `"/p:GenerateFullPaths=true"` as an additional string in the array `"args"`, for the task with `"taskName": "build"`. That fixes it for all projects which VS Code builds under that directory, and you can now just click through to errors correctly.

**Comment by sandy081** [comment]
@mjbvz Not sure if it is related to Problems view as it is just showing the diagnostics it receives from the problem matchers.

**Comment by MikeBeaton** [comment]
Hi @sandy081 . I am thinking that two different fixes would be possible? One would be to add the above line to the auto-generated `.vscode\tasks.json` file. Everything would then work (but we use slightly non-standard, slightly less nice looking MSBuild output). The other would (I think?) be to update the Problems view pane, so that it realises which project each error comes from, and makes the file path which it tries to navigate to be relative to the project which the problem came from, and not always to the root project.

**Comment by sandy081** [comment]
@dbaeumer Any suggestions? I think, problems view assuming and computing the paths is not a good approach, if not, where does this should go?

**Comment by MikeBeaton** [comment]
Just a thought, but couldn't the problem view know about relative paths, and not have to guess? (I am working under the assumption - I hope correct? - that the problems views view is parsing the MS Build text output anyway.)

For each problem, this msbuild output includes the 'context' (basically, the full path name to the .csproj which is being built), for example:

````
Parameters/Cursor.cs(9,4): error CS0103: The name 'xValue' does not exist in the current context [/Users/mjsbeaton/Projects/Mighty/net.core.shared/src/Mighty.csproj]
````

When built with `/p:GenerateFullPaths=true` the output is detectably different (e.g. starting with a /  on macOS):

````
/Users/mjsbeaton/Projects/Mighty/net.core.shared/src/Parameters/Cursor.cs(9,4): error CS0103: The name 'xValue' does not exist in the current context [/Users/mjsbeaton/Projects/Mighty/net.core.shared/src/Mighty.csproj]
````

So it looks like there is enough there for the problems view to see whether a full path is present or not, *and* to know which directory to make it relative to (i.e. the directory containing the .xxproj file) if not?

**Comment by MikeBeaton** [comment]
More relevant info (I think!):

If I create a new project with `dotnet new console` and open it with VS Code, then VS Code offers to add required assets, and when I accept it creates a tasks.json which does not add `"/p:GenerateFullPaths=true"` to the args:

````
{
    "version": "0.1.0",
    "command": "dotnet",
    "isShellCommand": true,
    "args": [],
    "tasks": [
        {
            "taskName": "build",
            "args": [
                "${workspaceRoot}/testcore.csproj",
                **** [we need this line added] **** "/p:GenerateFullPaths=true"
            ],
            "isBuildCommand": true,
            "problemMatcher": "$msCompile"
        }
    ]
}
````

However, if I create a new project with `dotnet new classlib` then VS Code behaves differently. Firstly, on initially loading the project it does *not* offer to add required assets. But secondly, when I actually try to build my classlib, then I do get an option to configure build task. If I choose 'MS Build' from the subsidiary options, then I get a task.json which *does* include `"/p:GenerateFullPaths=true"`, as follows:

````
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "msbuild",
	"args": [
		// Ask msbuild to generate full paths for file names.
		"/property:GenerateFullPaths=true"
	],
	"taskSelector": "/t:",
	"showOutput": "silent",
	"tasks": [
		{
			"taskName": "build",
			// Show the output window only if unrecognized errors occur.
			"showOutput": "silent",
			// Use the standard MS compiler pattern to detect errors, warnings and infos
			"problemMatcher": "$msCompile"
		}
	]
}
````

(Although this file does not seem to actually work as a build file for the project, unlike the previous one, which does.)

So it seems as if there may already be some partially implemented support to work around this problem?

**Comment by pocesar** [comment]
it seems to have been fixed on the latest insiders

**Comment by sandy081** [comment]
Closing this as per previous comment
