### ISSUE TITLE
Interacting with vagrant from the integrated terminal doesn't work. 

### ISSUE THREAD

**Issue by erikseulean** [Microsoft/vscode#22670]
- VSCode Version:1.10.1
- OS Version: Windows 7
Steps to Reproduce:
Using bash on Windows and running this command in the Integrated Terminal
1.vagrant ssh 
Error: VM must be running to open SSH connection. Run 'vagrant up' to start the virtual machine. 

I've noticed that interacting with Vagrant doesn't work from the integrated terminal
Same thing from a bash window, external from vscode works fine.

**Comment by Tyriar** [comment]
Does vagrant allow you to ssh into local VMs? Some things that could affect this:

- What user are the terminals running under
- What environment are they running under
