### ISSUE TITLE
Profiles Editor: `Use for current Window` toggle state confusing

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#226726]
I find the `Use for ...` actions very confusing in the context menu. 

- I think the `Use for Current Window` should not be a toggle and should be renamed to `activate` or something similar and be disabled when it's the current active one. I would also not add the checkbox in the profile editor on the right but move it to the top as a prominent action. 
- Regarding the `Use for New Windows`, I don't really think it has to be in the context menu and could be replaced by the action `Open in new Window`.

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/81e85b55-ee1a-4cc9-8b9d-deeef9971aa3">

**Comment by sandy081** [comment]
/duplicate

Thanks for the feedback.

I am combining this with https://github.com/microsoft/vscode/issues/226732
