### ISSUE TITLE
`Create: New Jupyter Notebook` doesn't start with path selection

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#226784]
Testing #226665

Version: 1.93.0-insider (user setup)
Commit: ff7a154d5e5e9034914f0466420f0f1407f0c95e
Date: 2024-08-27T05:04:20.235Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.25987

- Open a GH repo in latest VS Code Insiders on Windows 11 Insiders
- Use command `Create: New Jupyter Notebook` to create a new notebook for the TPI
- I go to diff view and realize my new notebook isn't there - it isn't actually part of the project
- I go the Extensions view to make sure I have the latest version of all extensions and find I need to update the Python extension
- When I go to `Restart Extensions`, I'm prompted with a file explorer to save my notebook, which is helpful, but I wondered why I wasn't prompted to pick a path at the start

❔ I expected my notebook to automatically be part of my current project, or to at least have gotten the option to pick a path / directory for it before it was created.

**Comment by DonJayamanne** [comment]
Files created using `Create: New Jupyter Notebook` are not saved anywhere, 
they are the same as untitled files which do not show up in SCM view.

**Comment by T-256** [comment]
> I'm prompted with a file explorer to save my notebook, which is helpful, but I wondered why I wasn't prompted to pick a path at the start

I'm found it unhelpful. currently I'm still rely on `Reload Window` command because each time I click on `Restart Extension` button, it will prompt to save untitled files which I don't want to.
