### ISSUE TITLE
after i finish 'npm run watch',how can i start vscode.i need help.

### ISSUE THREAD

**Issue by dandingol03** [Microsoft/vscode#22676]
1.i use node ./out/main.js ,but there is some error as below:
app.setPath('userData', userData);
   ^
TypeError: Cannot read property 'setPath' of undefined

//i have install electron global
thanks for your time!!!

**Comment by weinand** [comment]
I suggest that you first try to walk through this tutorial:
https://code.visualstudio.com/docs/runtimes/nodejs#_express
