### ISSUE TITLE
Edited cell is not uncollapsed

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#226766]
Testing #226663

![Image](https://github.com/user-attachments/assets/646c2fac-998d-4174-8283-008641e9e90e)

**Comment by alexr00** [comment]
I was one update behind. Appears to be fixed in the latest!

**Comment by alexr00** [comment]
Oh wait, it was only fixed because of the restart from updating. The issue still occurs in the latest insiders.

**Comment by DonJayamanne** [comment]
Ooh, interesting issue, surprised we've never caught this before.

**Comment by DonJayamanne** [comment]
Root cause is here 
```
		// note that the cell content change is not applied to the MirrorCell
		// but it's fine as if a cell content is modified after the first diff, its position will not change any more
		// but it might lead to interesting bugs in the future.
```

**Comment by DonJayamanne** [comment]
Fix will be reverted, see here https://github.com/microsoft/vscode/issues/227143

**Comment by DonJayamanne** [comment]
Current workaround is to compare each cells  (effectively this is the same as ignoring the diffing in worker and comparing everything in main thread).

Some comments here 
```
		// note that the cell content change is not applied to the MirrorCell
		// but it's fine as if a cell content is modified after the first diff, its position will not change any more
		// but it might lead to interesting bugs in the future.
```

Will be reverting the changes due to perf issues

**Comment by DonJayamanne** [comment]
Should now be fixed.
