### ISSUE TITLE
Database not showing up

### ISSUE THREAD

**Issue by tracybirky** [microsoft/vscode#226703]
I am trying to complete my assignment and selected the database: Ch13_SaleCo but when I run my query it is showing that the database is not there. I cannot complete my assignment if the database is not in your system.
<img width="452" alt="image" src="https://github.com/user-attachments/assets/e73179f9-8a6c-499a-a0f0-84f46ccd10cc">
<img width="343" alt="image" src="https://github.com/user-attachments/assets/b8b9c061-7761-419e-9b3c-e9ab53771578">

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0
Embedder: codespaces

**Comment by aiday-mar** [comment]
Hi this looks like it is an issue that you should file to the extension authors. I am not able to access the following look, but you may be able to file this issue directly to https://github.com/internal-CSP-HES-engineering/cengage-companion/issues. I will close this issue in the meantime.
