### ISSUE TITLE
Extract separate interface for `FileSearchProviderOptions#folderOptions` and consider to move `pattern` into it

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#226738]
Testing #226668

The complete description what to search for is spread out across `options#folderOptions` and the `pattern`-argument. During a session, the latter is changing while the former isn't. I wonder if that's an implementation detail shadowing into the API and if `pattern` should be merged into a "search pattern object"

**Comment by andreamah** [comment]
a "search pattern object" containing info about the `pattern`, `folder`, `includes`, and `excludes`? I still stand by keeping `pattern` by itself. In both the Text and File search provider APIs, the first argument is "how to know that something is a match" vs the options contain the details on where to find it and other limitations.

**Comment by andreamah** [comment]
I feel like this issue has the same vibe as this issue, although it's not the same: https://github.com/microsoft/vscode/issues/226814
I believe that, on both sides, it feels motivated by the ambiguity between `query/pattern` and `options`. Not sure if this warrants an extra argument or just a different way of organizing info.

**Comment by jrieken** [comment]
> the first argument is "how to know that something is a match" vs the options contain the details on where to find it and other limitations.

But aren't those patterns, that are in the options bag, also for "how to know that something is a match". Like, it doesn't help that pattern matches if exclude-pattern don't match. Or did I misunderstand those patterns?

**Comment by andreamah** [comment]
I guess `query` is mostly the 'within-file' matching parameters, whereas the `options` control which files we end up looking in. Not sure if that's a valid way of separating them.
