### ISSUE TITLE
auth.vscode.dev returns 500 when trying to login in vscode.dev

### ISSUE THREAD

**Issue by realDuang** [microsoft/vscode#226700]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: vscode.dev
- OS Version: vscode.dev

Steps to Reproduce:

1.  Sign in vscode.dev (eg: via backup and setting sync)
2. Select account in the pop-up window to sign in.
3. display Error occurred
4. Open devtools, it is caused by auth.vscode.dev request 500

![WX20240827-125146@2x](https://github.com/user-attachments/assets/789598e2-2a36-436a-902d-20608414cd97)

BTW, I also tried this insiders.vscode.dev, and the current login flow is healthy in this insider version.

**Comment by joaomoreno** [comment]
We did have a small hiccup in maintaining the service in the last 24h, but things should be back to normal by now. Can you still reproduce?

**Comment by joaomoreno** [comment]
Closing for now. Let me know if you still see this.
