### ISSUE TITLE
"Open Editors" view does not hide in new empty profile

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#226709]
I created a new empty profile and the "Open Editors" view was visible:

![Image](https://github.com/user-attachments/assets/97c75a7b-b702-4c41-9432-d6a520e1f2c0)

My understanding is that this view is hidden by default.

**Comment by sandy081** [comment]
I am not able to reproduce. Can you please provide steps?

By any chance do you have this view visible before switching the profile?
