### ISSUE TITLE
Add possibility to reload file from disk

### ISSUE THREAD

**Issue by kjo-sdds** [microsoft/vscode#226707]
Add a command to reload the active open file from disk.

It sometimes happen (especially when working in VCS, but also when working with other external files ... ) that the content on disk is newer than the "dirty" currently opened file. We then get a popup with 2 options : some "merging" option and some "overwrite" option.

It often happen that I actually just want to go to the newer version on disk ... so it'd be nice either to have a 3rd option "load from disk" or even just simply a command to reload from disk ! (currently either you have to close the file without saving then open it again ... or go through the merge and reject all your modifications and accept the ones on disk ... ).

Since it is not an everyday use-case ... I wouldn't even have written a request if it were something seemingly complex ... but as it seems pretty basic ... [kind of an alias of "close without saving" then "open file" again] ... I'm thinking that could be usefull for others than just me ...

**Comment by bpasero** [comment]
Did you try "Revert File"?

**Comment by kjo-sdds** [comment]
Damn !!! 
I swear I searched on google but never did this command pop up !

Nope, I did not try ! I'll try it on next occurence (I'll try to artificially create the situation before the next pull) and keep you up to date !

In any case thanks already for the direction!
