### ISSUE TITLE
Sorting should have the default state checked

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#226764]
Testing #226657

Before attempting to sort anything, nothing is checked:

![image](https://github.com/user-attachments/assets/a2064e30-517c-42bb-9698-4ca79c65039b)

I'm actually not sure what it's sorted by as I see folders interleaved, it's not sorted by file name and updated times are also not sorted:

![image](https://github.com/user-attachments/assets/21f0868c-a106-4900-996e-d6736c917186)

**Comment by Tyriar** [comment]
FWIW I am also unable to uncheck or reset the sort state:

![image](https://github.com/user-attachments/assets/9bc4e1ff-d7cd-4c35-8f35-a6d46c712b8d)

I don't think we should have this, but it doesn't seem possible to get back to the mysterious default sort state

**Comment by alexr00** [comment]
The mysterious default sort order is a bug and shouldn't happen.

**Comment by aiday-mar** [comment]
I see two sorting methods now 'position in file' and 'updated time'. 'position in file' is the default sorting order.
