### ISSUE TITLE
Configure Task action does nothing

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#226838]
I think this is supposed to open the tasks.json file, but nothing happens when I click on the Configure Task button (tasks shown are from this repo):

![image](https://github.com/user-attachments/assets/a8d6c822-646d-43fb-8ed1-21aea832be05)

**Comment by meganrogge** [comment]
This is working for me - a gif would help and also, does this happen for every entry or just some?

**Comment by joyceerhl** [comment]
This works on `VS Code - Build` and `Ensure Prelaunch Dependencies` but no-ops on `Ext - Build` and `Core - Build`

**Comment by meganrogge** [comment]
Thanks for the info. Reproduces in stable and likely has never worked. Closing as I haven't had other reports and it's unlikely i'll get to this.

**Comment by joyceerhl** [comment]
Can we make this a `good-first-issue` at least?

**Comment by meganrogge** [comment]
Do you encounter this often? I am not sure how involved the fix would be.
