### ISSUE TITLE
telemetry not showing up

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#226881]
Testing #226399

> Example: create a file with your name as the extension. Then: 
> 
> ```
> RawEventsVSCode
> | where EventName == "monacoworkbench/fileput"
> | where Properties['ext'] == ".meganrogge"
> ```
> 
> I still get a network error when I try this, so will wait a little longer. 

 _Originally posted by @meganrogge in [#226399](https://github.com/microsoft/vscode/issues/226399#issuecomment-2313330704)_

It's been 90 mins and still not showing in kusto

**Comment by bpasero** [comment]
@meganrogge can you enable trace in logs, open telemetry channel and find a session ID to search for, that might be easier to see if any events come up.

**Comment by meganrogge** [comment]
I tried searching for session id too and did not see it

**Comment by bpasero** [comment]
@meganrogge could you try again with latest insiders `1.94.x` which now is ESM enabled?

**Comment by meganrogge** [comment]
Yes, will check telemetry later to see if an event I just did shows up there.

**Comment by meganrogge** [comment]
nice, it's there.
![Image](https://github.com/user-attachments/assets/acb80f55-693b-4905-bb7b-668c79488a39)
