### ISSUE TITLE
Git - better handle conflict caused by deleted file

### ISSUE THREAD

**Issue by krizerator** [microsoft/vscode#226880]
Type: <b>Bug</b>

GitHub repositories with large changes get stuck when loading and sometimes don't display the files where they should.
- Pulled from remote.
- More than 10k files were updated.
- Some files had merge changes (unmerged conflicts).
- Terminal output when attempting to commit: 
```
error: Committing is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
```
- Merge changes don't show up in Source Control, so deleted files cannot be fixed with the Merge Editor.
- Changes do show up after `git commit`, but when opening the files, these don't show the button to Resolve in Merge Editor.
- Git: Merge Editor - Open the merge editor for files that are currently under conflict. Is deactivated by default.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Linux x64 5.15.0-113-generic
Modes:
Remote OS version: Linux x64 5.15.0-113-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 1284)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|31.02GB (12.19GB free)|
|Process Argv|--crash-reporter-id aace5d7a-f861-4043-a5de-79e4971f24b0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: Python Developer Environment|
|OS|Linux x64 5.15.0-113-generic|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 1284)|
|Memory (System)|31.02GB (12.20GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-drawio|hed|1.6.6
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.380.0
gitlens|eam|15.3.1
vscode-drawio|hed|1.6.6
cucumberautocomplete|Job|3.0.4
vsc-python-indent|Kev|1.18.0
iis|lex|1.0.14
restructuredtext|lex|190.4.2
restructuredtext-pack|lex|1.0.3
vscode-docker|ms-|1.29.2
debugpy|ms-|2024.10.0
flake8|ms-|2023.10.0
isort|ms-|2023.10.1
pylint|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
esbonio|swy|0.11.0
even-better-toml|tam|0.19.2
python-tox|the|1.0.0
simple-rst|tro|1.5.4
bdd|vte|0.3.18

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
wkspc-ranged-t:31118572
fje88620:31121564

```

</details>

**Comment by krizerator** [comment]
Setting `git.statusLimit` to a higher value than the amount of changes will allow the changes to show up in Source Control. Unfortunately, even when doing that, Resolve in Merge Editor button still does not show up and if there is a file that has been deleted causing a conflict, then it will show the option to delete it or keep the version without showing a preview of the file.

**Comment by lszomoru** [comment]
> Unfortunately, even when doing that, Resolve in Merge Editor button still does not show up and if there is a file that has been deleted causing a conflict, then it will show the option to delete it or keep the version without showing a preview of the file.

@krizerator, sorry for not getting back to you on this until now. 
Could you please provide me with a set of steps that I could follow in order to try to reproduce this? Thanks!
