### ISSUE TITLE
Panne d'enregistrement pour mes pages Web de vulnérabilités

### ISSUE THREAD

**Issue by Shygeek64** [microsoft/vscode#226823]
Type: <b>Bug</b>

1 - Enregistrer la page Web et cela ne marque rien, 
2 - Stopper le débogage, mais rien ne fait, 
3 - Lancer j.son mais ils ont refusé de me l'envoyer sur ma page, et enfin...
4 - Les nombreuses mises à jour qui n'ont rient changé dans mon ordi...

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Connection to 'Codespaces: fluffy tribble' could not be established  GH_SPENDING_LIMIT
Connection to 'Codespaces: fluffy tribble' could not be established  GH_SPENDING_LIMIT

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|30.93GB (23.68GB free)|
|Process Argv|--crash-reporter-id 71ad2fd2-3cdd-456a-b1a0-2d7b22c97da9|
|Screen Reader|no|
|VM|0%|

Connection to 'Codespaces: fluffy tribble' could not be established  GH_SPENDING_LIMIT

Connection to 'Codespaces: fluffy tribble' could not be established  GH_SPENDING_LIMIT
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
fje88620:31121564
aajjf12562:31125793

```

</details>

**Comment by Shygeek64** [comment]
Comment me débarrasser de fluffy tribble sur Codespaces 1.92.2 ?

**Comment by Shygeek64** [comment]
SVP Merci ?

**Comment by joyceerhl** [comment]
You can delete codespaces at this page https://github.com/codespaces
