### ISSUE TITLE
`Go to Source` appears twice in the context menu for list of tests

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#226852]
Testing #226684
1. run a test suite with failing tests
2. `Test Results` bottom pane.
3. `Go to Source` appears twice :bug:

![Image](https://github.com/user-attachments/assets/740b4eb1-c740-48e9-80a3-a8ecd702c267)

**Comment by joyceerhl** [comment]
Now I see Go to Test and Go to Error
![image](https://github.com/user-attachments/assets/3234e447-cc44-4e85-9817-ea35df254cef)
