### ISSUE TITLE
The setting `editor.wrappingColumn` has been deprecated in favor of `editor.wordWrap`.

### ISSUE THREAD

**Issue by BassamHabash** [Microsoft/vscode#22686]
The setting `editor.wrappingColumn` has been deprecated in favor of `editor.wordWrap`.

"editor.wrappingColumn": 80 // or "editor.wrappingColumn": 110 

"editor.wordWrap": "off",

**Comment by weinand** [comment]
This has been documented in the 1.10 release notes:
https://code.visualstudio.com/updates/v1_10#_word-wrap-settings-redesign

@BassamHabash Why did you create this issue?

**Comment by BassamHabash** [comment]
![screen shot 2017-03-16 at 9 34 42 am](https://cloud.githubusercontent.com/assets/21196246/23986302/1e1f3a1e-0a2c-11e7-8c77-8be5c7a7a5b9.png)

**Comment by weinand** [comment]
@BassamHabash what is the problem with that helpful error message? It explains nicely that 'editor.wrappingColumn' should no longer be used and that you should use 'editor.wordWrap' instead.

**Comment by BassamHabash** [comment]
Thanks for replay , problem occur  open visual code , i solved it by delete ( editor.wrappingColumn )
and put 'editor.wordWrap = "on" , but the other problem .

when i hover on function by example and click ( cmd ) mac os . not appears function details .
