### ISSUE TITLE
Titlebar overlay is not enabled

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#226860]
Type: <b>Bug</b>

  ERR [uncaught exception in main]: Titlebar overlay is not enabled: Error: Titlebar overlay is not enabled
    at $.updateWindowControls (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:117:119996)
    at $.n (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:117:117632)
    at $.Q (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:118:3434)
    at $.tryClaimWindow (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:118:3152)
    at App.<anonymous> (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:118:4453)
    at App.emit (node:events:519:28)
    at n._init (node:electron/js2c/browser_init:2:12346)
    at openGuestWindow (node:electron/js2c/browser_init:2:98561)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:85743)
    at WebContents.emit (node:events:519:28)

VS Code version: Code - Insiders 1.93.0-insider (ff7a154d5e5e9034914f0466420f0f1407f0c95e, 2024-08-27T05:04:20.235Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.60GB (15.79GB free)|
|Process Argv|--log info --log ms-python.python=info --crash-reporter-id 4fb1ebc1-cf4c-4880-a88a-47738ec3768d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
ruff|cha|2024.42.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.3.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
copilot|Git|1.223.1070
copilot-chat|Git|0.20.2024082705
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.95.2024082704
copilot-for-security|Mic|0.3.1
vscode-language-pack-de|MS-|1.93.2024082109
debugpy|ms-|2024.10.0
python|ms-|2024.13.2024082701
vscode-pylance|ms-|2024.8.2
jupyter|ms-|2024.8.2024081201
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.2
code-spell-checker|str|3.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aacf:30263846
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
vscrpc:30624061
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
0ee40948:31013168
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31057980
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-c:31111717
nativeloc1:31118317
wkspc-ranged-c:31125598
cf971741:31111988
jh802675:31111929
notreesitter:31116712
e80f6927:31120813
ei213698:31121563
i21gd607:31121876
aajjf12562:31125793

```

</details>

**Comment by bpasero** [comment]
@karthiknadig any steps, is this reproducible?

**Comment by karthiknadig** [comment]
I got this on Windows. I opened an existing project for an extension. After the vscode window came up I opened the developer view and I see this.

**Comment by bpasero** [comment]
I cannot reproduce, what are your settings?

**Comment by karthiknadig** [comment]
I had just this one in user settings:
![image](https://github.com/user-attachments/assets/cd97b25f-5783-4d4a-a455-7137358c93b4)


This does not seem to be happening with the build from today:
Version: 1.93.0-exploration (system setup)
Commit: 96475999252541f346cc68976cc3e15ac6701b7f
Date: 2024-08-28T04:04:01.271Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by bpasero** [comment]
Ok, if you see this again and can distill steps, that would be great. Maybe some setting got synced that caused this.

**Comment by vikthorvergara** [comment]
It's happening to me on Windows as well. I've disabled all my extensions, but I can't figure out which settings are causing this. I think it might have something to do with these Arc settings:
```json
  "apc.activityBar": {
    "hideSettings": true,
    "itemMargin": 8,
    "itemSize": 32,
    "position": "bottom",
    "size": 48
  },
  "apc.electron": {
    "titleBarStyle": "hiddenInset",
    "trafficLightPosition": {
      "x": 11,
      "y": 10
    },
    "opacity": 1,
    "vibrancy": "dark",
    "frame": false
  },
  "apc.font.family": "Inter",
  "apc.header": {
    "height": 36
  },
  "apc.listRow": {
    "height": 24
  },
  "apc.stylesheet": {
    ".editor-actions": "display: none",
    ".monaco-list-row": "border-radius: 4px;",
    ".monaco-workbench .monaco-list:not(.element-focused):focus:before": "display: none;",
    ".nosidebar .inline-tabs-placeholder": "width: 75px",
    ".pane-body": "padding: 0 8px",
    ".pane-header": "padding: 0 8px",
    ".split-view-view:first-child .pane-header": "display: none !important;",
    ".title-label > h2": "display: none"
  },
```

**Comment by ChristoferMendes** [comment]
> It's happening to me on Windows as well. I'm not sure but I think it might have something to do with this Apc setting:
> 
> ```json
>   "apc.electron": {
>     "titleBarStyle": "hiddenInset"
>   }
> ```

My vscode was not opening, If I remove this apc setting it opens now

**Comment by luispazcode** [comment]
> It's happening to me on Windows as well. I'm not sure but I think it might have something to do with this Apc setting:
> 
> ```json
>   "apc.electron": {
>     "titleBarStyle": "hiddenInset"
>   }
> ```

It happened to me too, but I commented it and it works.
