### ISSUE TITLE
Timed out getting tasks from "typescript" / "npm"

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#226854]
Type: <b>Bug</b>

Getting the following error:
![image](https://github.com/user-attachments/assets/9b81e0b4-3428-432f-bde3-784e9bdf38f1)

VS Code version: Code - Insiders 1.93.0-insider (ff7a154d5e5e9034914f0466420f0f1407f0c95e, 2024-08-27T05:04:20.235Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.60GB (15.96GB free)|
|Process Argv|--log info --log ms-python.python=info --crash-reporter-id 4fb1ebc1-cf4c-4880-a88a-47738ec3768d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
ruff|cha|2024.42.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.3.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
copilot|Git|1.223.1070
copilot-chat|Git|0.20.2024082705
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.95.2024082704
copilot-for-security|Mic|0.3.1
vscode-language-pack-de|MS-|1.93.2024082109
debugpy|ms-|2024.10.0
python|ms-|2024.13.2024082701
vscode-pylance|ms-|2024.8.2
jupyter|ms-|2024.8.2024081201
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.2
code-spell-checker|str|3.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aacf:30263846
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
vscrpc:30624061
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
0ee40948:31013168
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31057980
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-c:31111717
nativeloc1:31118317
wkspc-ranged-c:31125598
cf971741:31111988
jh802675:31111929
notreesitter:31116712
e80f6927:31120813
ei213698:31121563
i21gd607:31121876
aajjf12562:31125793

```

</details>

**Comment by meganrogge** [comment]
Are you seeing this in oss? This is often caused by a slow/bad extension

**Comment by karthiknadig** [comment]
This seems to occur with running "Extensions Disabled":
![image](https://github.com/user-attachments/assets/ddf4eb02-6989-4b36-b1b7-628c9e6abb38)

repeated re-launch cause both to show up eventually.

**Comment by meganrogge** [comment]
Anything else you're doing? I cannot repro

**Comment by karthiknadig** [comment]
Actually nothing. Just loading a TS project and opening the developer tools.

**Comment by meganrogge** [comment]
Opening the vscode repo does this for you? Can you disable the python extension specifically?

Can you provide your settings file?

**Comment by meganrogge** [comment]
Also, do tasks work?

**Comment by karthiknadig** [comment]
Opening the vscode repo does this for you?
> Yes. Actually any TS project I hit this.

Can you disable the python extension specifically?
> I have tried it without python extension uninstalled.

Can you provide your settings file?

> workspace settings:
```
{
    "files.exclude": {
        "out": false, // set this to true to hide the "out" folder with the compiled JS files
        "dist": false // set this to true to hide the "dist" folder with the compiled JS files
    },
    "search.exclude": {
        "out": true, // set this to false to include "out" folder in search results
        "dist": true // set this to false to include "dist" folder in search results
    },
    // Turn off tsc task auto detection since we have the necessary tasks as npm scripts
    "typescript.tsc.autoDetect": "off",
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.formatOnSave": true
    },
    "prettier.tabWidth": 4
}
```
User settings:
```
{
  "workbench.sideBar.location": "right",
  "terminal.integrated.defaultProfile.windows": "Command Prompt",
   "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "python.analysis.typeCheckingMode": "off",
  "git.inputValidationSubjectLength": 200,
  "git.inputValidationLength": 200,
  "editor.inlineSuggest.enabled": true,
  "gulp.autoDetect": "on",
  "workbench.colorTheme": "Visual Studio Dark",
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "python.experiments.optInto": ["All"],
  "editor.renderWhitespace": "all",
  "diffEditor.ignoreTrimWhitespace": false,
  "githubPullRequests.fileListLayout": "tree",
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "python.trace.server": "verbose",
  //"black-formatter.trace.server": "verbose",
  "editor.accessibilitySupport": "off",
  "python.createEnvironment.trigger": "prompt",
  "testing.automaticallyOpenPeekView": "never",
  "pygls-demo.trace.server": "verbose",
  "githubPullRequests.pullBranch": "never",
  "editor.stickyScroll.scrollWithEditor": false,
  "workbench.tree.enableStickyScroll": false,
  "editor.stickyScroll.enabled": false,
  "terminal.integrated.stickyScroll.enabled": false,
  "diffEditor.maxComputationTime": 0,
  "files.autoSave": "off",
  "scm.workingSets.enabled": true,
  "scm.workingSets.default": "empty",
  "remote.autoForwardPortsSource": "hybrid",
  "github.copilot.editor.enableAutoCompletions": true,
  "python.languageServer": "Pylance",
  "ruff.nativeServer": true,
  "python.locator": "native",
  "git.replaceTagsWhenPull": true,
  "accessibility.verbosity.debug": true,
  "notebook.experimental.enableNewDiffEditor": true,
  "python-envs.defaultEnvManager": "ms-python.vscode-python-envs:system"
}

```

> do tasks work?

Yes.

**Comment by TechMaz** [comment]
I'm having the same issue but on Mac

**Comment by meganrogge** [comment]
@karthiknadig does this still reproduce for you? I am not seeing it

**Comment by karthiknadig** [comment]
I am not seeing it either. We can close this and see if this repros consistently.

**Comment by yanite** [comment]
me too
