### ISSUE TITLE
trailing whitespace change is shown with whitespace changes disabled

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#226806]
Testing #226664

1. open a notebook and add a few newlines to the end of a cell
2. open the diff view and deselect show whitespace changes

:bug:
![image](https://github.com/user-attachments/assets/c3334843-189a-4a04-8c72-24f5b81f4cdc)

**Comment by DonJayamanne** [comment]
Not an issue, new lines are not ignored when toggling the white space setting (as that only applies to trailing whitespaces in a line, thats how it works in regular plain text diff editor as well).
Hence closing as designed.
