### ISSUE TITLE
double-click in text content of stack frame should take you to source

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#226855]
Testing #226684

When double-clicking on the source code in the stack frame, I feel like that should take you to the source code in the editor (like how it does when you do in the `Go to Definition` peek view.

**Comment by connor4312** [comment]
Double click is not really an action we have in code editors since that can also create selections, but I'll make it so that ctrl+clicking on any word in the editor brings you to the full file instead of its definition
