### ISSUE TITLE
editor.selectionHighlight set to false not respected in .scss files

### ISSUE THREAD

**Issue by tomliv** [Microsoft/vscode#22687]
- VSCode Version: Version 1.10.2 (1.10.2)
- OS Version: Mac OS 10.12.3

Steps to Reproduce:

1. Set editor.selectionHighlight to false
2. Confirm setting in HTML document
3. Create and .scss document
4. With multiple lines containing same word/selector etc., place cursor inside one iteration. Others highlight.

I have editor.selectionHighlight set to false, and in a PHP file it seems to be off. However, in a .scss document, putting my cursor in a selector will highlight all other similar selectors. See attached.
<img width="330" alt="screen shot 2017-03-15 at 2 33 24 pm" src="https://cloud.githubusercontent.com/assets/1153953/23968482/4690323e-0999-11e7-8ae4-d1d0db39d8e9.png">

**Comment by aeschli** [comment]
What you see is the highlight from the document symbols that scss provides. It is not configurable at this time. The request for this is #5351.
