### ISSUE TITLE
launching in a locale from command line fails

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#226822]
1. install the French language pack.
2. Try re-opening in French from command line: `code-insiders . --locale=fr`. I am following what it says [here](https://code.visualstudio.com/docs/getstarted/locales#_setting-the-language).
3. Still in English :bug:

Changing language from the command palette works, so I'm not sure where the failure is.

**Comment by andreamah** [comment]
Weird- I have this new output log:


![Image](https://github.com/user-attachments/assets/27744f84-697f-438a-a0f0-6f1a0cf409a0)

**Comment by andreamah** [comment]
Oh, I was able to get it in english?


![Image](https://github.com/user-attachments/assets/d109ca72-7d98-4bfd-b80c-78606332ae95)

**Comment by TylerLeonhardt** [comment]
@andreamah can you try this again? There was a bug fix last week around the `--locale` parameter.

Also, that `Expected......` output channel doesn't seem localization related... what does it come from?

**Comment by andreamah** [comment]
I don't see this anymore... I'll just close for now.
