### ISSUE TITLE
shell integration `onDidStart` never stops

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#226871]
Testing #226655

tried testing `onDidStartTerminalShellExecution` with something simple like writing `git status` and running it (since it runs by default), but it never stops sending the text via `sendText`.

maybe this is intended since there is anexplicit `onDidEndTerminalShellExecution`, but can maybe specify in docs that these two go hand in hand (unless this is already something well known 🫨 )

**Comment by Tyriar** [comment]
@justschen not sure what you mean by `but it never stops sending the text via sendText.`?

**Comment by justschen** [comment]
hmm I actually cannot repro anymore...

for context, I was trying something along the lines of:

```typescript
	vscode.window.onDidStartTerminalShellExecution(e => {
			if (e.execution.commandLine.value === 'git add .') {
				e.terminal.sendText('git commit -m "audot commit"');
			}
		}),
```
perhaps `e.shellIntegration.executeCommand` is the more correct one in this case anyways, but i'll continue playing around with it

**Comment by Tyriar** [comment]
@justschen my only guess is that `commandLine.value` may have been different in start and stop? Also something like this is how I would go about doing your example:

```ts
// end not start, destructuring
vscode.window.onDidEndTerminalShellExecution({ execution, shellIntegration } => {
    if (execution.commandLine.value === 'git add .') {
        // executeCommand instead of sendText
        shellIntegration.executeCommand('git commit -m "auto commit"');
    }
})
```
