### ISSUE TITLE
Should we remove the pull, push and fetch buttons from the scm graph?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#226839]
Testing #226648

In the default setup where this shows up in the SCM view these feel like bloat to me as you can already do them elsewhere:

<img width="118" alt="Screenshot 2024-08-27 at 10 46 07 AM" src="https://github.com/user-attachments/assets/cba8ae16-cb2b-48a8-ac91-f329dbb57437">

Should these live in the overflow menu or not at all in that view to reduce clutter?

**Comment by lszomoru** [comment]
These buttons have been removed. At the moment there is only a "Fetch All Remotes" action which fetches new information for the graph.
