### ISSUE TITLE
language specific editor.wordBasedSuggestions setting doesn't override the global setting

### ISSUE THREAD

**Issue by StanislawStempin** [Microsoft/vscode#22680]
- VSCode Version: 1.10.2
- OS Version: Windows 10 1607 14393.693

Steps to Reproduce:

1. Create a new empty folder and open it in VSCode
2. In that folder - create a new xml file 
3. Open workspace settings and set the following settings:
'''{
    "editor.wordBasedSuggestions": true,
    "[xml]": {
        "editor.wordBasedSuggestions": false
    }    
}
'''
4. Open the XML file, type a few words and press Ctrl+Space

Actual result:
Word based suggestions show up
Expected result:
No suggestions showing up

![wordbasedsuggestions](https://cloud.githubusercontent.com/assets/23653165/23961603/b7799866-09ab-11e7-98d0-81878fc72ef9.png)

**Comment by sandy081** [comment]
@jrieken Looks like wordBasedSuggestions config is being read without lang id.

**Comment by jrieken** [comment]
Please advise how @sandy081. There is nothing obvious on the service: [`const { wordBasedSuggestions } = this._configurationService.getConfiguration<IEditorOptions>('editor');
`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/editorWorkerServiceImpl.ts#L92)

**Comment by sandy081** [comment]
@jrieken Agreed, service api is not explicit. You can get language options as follows

```js
this._configurationService.getConfiguration<IEditorOptions>({section: 'editor', overrideIdentifier: <langId>})
```

**Comment by sandy081** [comment]
@jrieken Not sure why are we not getting editor settings from the editor instead of asking the service again?

**Comment by jrieken** [comment]
Because this is done as service which isn't aware of an editor, just knowing models.
