### ISSUE TITLE
`onDidStartTerminalShellExecution` not fired when expected

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#226875]
Testing #226655

I expected to see the start event fire when I press enter, but I do not.

https://github.com/user-attachments/assets/739e01c8-cd68-45f4-8a08-8d4344b82b07

**Comment by Tyriar** [comment]
I think what's happening here is the zsh correction thing happens before the preexec hook goes off. Since started does eventually fire, I don't think we could do anything here if we wanted to.
