### ISSUE TITLE
Should merging into a branch not indent the text?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#226821]
Testing #226648

Current:

![image](https://github.com/user-attachments/assets/3d7a0945-8a8b-426b-b0ca-b0cc9f9dabc6)

Proposal:

![image](https://github.com/user-attachments/assets/fd893a3b-c316-4214-9e82-4638952124b9)

or

![image](https://github.com/user-attachments/assets/9d026da8-1f46-4aac-ae01-0ec3be0d98d8)

While the looping around line does look cool, it ends up indenting the commits which makes it look like something special may have happened on all the indented lines which it did not:

![image](https://github.com/user-attachments/assets/c085cc93-bf95-4474-a453-3702d1f3a0b9)

**Comment by petvaizAkhtar** [comment]
Good
