### ISSUE TITLE
Outlook account doesn't show up in Accounts menu after reloading the window

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#226853]
Testing #226539

With VS Code Insiders on Ubuntu and with Fugio, I minted a token for my Outlook account with `profile` scope.
Afterwards, I noticed my Outlook account showed up as a new entry in the Accounts menu.
After reloading the window, I didn't see that entry anymore and had to re-mint the token.

**Comment by TylerLeonhardt** [comment]
Hmmm this seems more like a SecretStorage issue... did you get any sort of notification about Secret Storage not being available?

**Comment by rzhao271** [comment]
Cannot repro now
