### ISSUE TITLE
pane title click behavior

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#226863]
Testing #226684

I see that clicking the title of the pane will take you to source. I guess I'm used to seeing things getting toggled to collapse/expand the node, so that was unexpected for me.

**Comment by joyceerhl** [comment]
Not sure which pane title this refers to 😅

**Comment by connor4312** [comment]
This is referring to the headers of the stack frames in the stack trace view when looking at a failed test. The call stack is shown when tests fail using the selfhost test provider
