### ISSUE TITLE
Not comparing against the staged changes

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#226807]
Testing #226665

Repro steps:
1. Make some changes to a cell, in my case I added a cell with some content
2. stage the changes
3. Remove some lines from the cell that was added in step 1, and save.
4. The diff view launched from "changes" SCM view should diff between staged and working.

**Comment by DonJayamanne** [comment]
This is an existing issue, view model isn't updated after opening the diff editor

**Comment by joyceerhl** [comment]
Now the diff view for the changes in the 'Staged Changes' group is the same as the diff view for the unstaged changes

**Comment by karthiknadig** [comment]
I am seeing it as I would expect. This is diff launched from staged (where the cell was added)
![image](https://github.com/user-attachments/assets/73383fa6-4ecd-4071-9d02-3fd17c995bf7)

This is diff launched on unstaged:
![image](https://github.com/user-attachments/assets/38d6e22d-5a88-438a-9c93-2052e10769ac)

**Comment by DonJayamanne** [comment]
Works for me too,
@joyce can you share the text file contents in the 3 cases
* Commited ipynb
* Staged ipynb 
* & finally changed ipynb

**Comment by rzhao271** [comment]
Original steps LGTM

**Comment by joyceerhl** [comment]
Original file:
![image](https://github.com/user-attachments/assets/836c7959-ed31-43f6-aa37-9c49b960c594)

Modification 1:
![image](https://github.com/user-attachments/assets/0493e641-100a-4c1e-88af-8311027121d6)

Modification 2: 
![image](https://github.com/user-attachments/assets/09a8d0e8-d409-4491-91e4-1d8469900020)

Observe that the diffs for the Staged and Working Changes regions below are identical
![Recording 2024-08-30 at 10 41 33](https://github.com/user-attachments/assets/0c9978d3-d8be-46d9-9f59-a98aae239da9)
