### ISSUE TITLE
Bug: Format Document

### ISSUE THREAD

**Issue by buzinas** [Microsoft/vscode#22682]
- VSCode Version: 1.10.2
- OS Version: Mac OS X Sierra

Steps to Reproduce:

1. Create a new JavaScript file with two-spaces indentation settings:
2. Add the following code (intentionally with four-spaces indentation):
```javascript
f({
    x: 1
}, {
    y: 2
});

```
3. Right click, select the option `Format Document`. Code is formatted as:
```javascript
f({
  x: 1
}, {
    y: 2
  });
```

Expected:
```javascript
f({
  x: 1
}, {
  y: 2
});
```

**Comment by mjbvz** [comment]
Thanks. This issue is being tracked upstream here: https://github.com/Microsoft/TypeScript/issues/6252
