### ISSUE TITLE
Hide hover popups while dragging text

### ISSUE THREAD

**Issue by JoshKreitz** [microsoft/vscode#226874]
With hover fields enabled, select some code including a variable and attempt to drag it to another location. While dragging, the hover popup showing variable information appears, preventing the selection from being dropped anywhere within the area covered by the popup. Observed in JavaScript/TypeScript and C# editors, I haven’t tested elsewhere. 

Either hover events should be interrupted by drag events to prevent popups from appearing when a drag is initiated, or a setting should be provided to disable hover popups when dragging selected text. 

System Info: 
- MacOS 14.6.1 on an Apple M3 Pro
- VS Code 1.92.2
- Extensions: Pylance, .NET Install Tool, C/C++, C#, Docker, Eslint, npm, Path Intellisense, Prettier, misc others unrelated

**Comment by mordechaim** [comment]
This annoying behavior is no longer present in the latest version of VS Code. As soon as you start a drag gesture the popup closes.

**Comment by youlinaa** [comment]
Same problem, after restarting the window, it returns to normal. This problem will occur after using it for a period of time.

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. I believe this should be fixed in the latest version of VS Code.
