### ISSUE TITLE
Unable to start Settings Sync

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#226888]
Testing #226539

VS Code Insiders on Ubuntu with Fugio.

1. Mint a Microsoft account token with `profile` scope.
2. Run "Settings Sync: Backup and Sync Settings..."
3. Use the Microsoft account.
4. :bug: Error message in Settings Sync output: GET request to Settings Sync endpoint (trafficmanager.net) fails because the requested endpoint is not found (405). Cannot use collections before a manifest exists. That error message is followed by "Did reset the local sync state."

**Comment by sandy081** [comment]
Can you please share the logs from Settings Sync output view?
