### ISSUE TITLE
Unable to log in with VSCODE_CLIENT_ID VSCODE_TENANT scope

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#226851]
Testing #226539

Using the latest VS Code Insiders on Ubuntu with the Fugio extension and my personal Microsoft account.

I tried putting in the scope `VSCODE_CLIENT_ID:a4fd7674-4ebd-4dbc-831c-338314dd459e VSCODE_TENANT:common profile` and got the error "invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application."

I then tried putting in the scope `VSCODE_CLIENT_ID:a4fd7674-4ebd-4dbc-831c-338314dd459e, VSCODE_TENANT:common, profile` and got the error "Specified tenant identifier 'common,' is neither a valid DNS name, nor a valid external domain." which seems to imply that the values should not be comma-separated, either.

**Comment by aiday-mar** [comment]
Got the same error 

![Screenshot 2024-08-28 at 10 11 51](https://github.com/user-attachments/assets/4469ef4c-e8d9-4c27-86bc-e40677b6a90e)

**Comment by TylerLeonhardt** [comment]
This should be working now. I forgot to add a redirect uri to the client id configuration

**Comment by TylerLeonhardt** [comment]
Steps:

* Install [Fugio](https://marketplace.visualstudio.com/items?itemName=TylerLeonhardt.fugio)
* Run `Fugio: Mint Token`
* `microsoft`
* `VSCODE_CLIENT_ID:a4fd7674-4ebd-4dbc-831c-338314dd459e VSCODE_TENANT:common profile`

It should take you through the flow to mint a token
