### ISSUE TITLE
Repl file paths highlighting is broken if path contains space

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#226882]
Testing https://github.com/microsoft/vscode-python/issues/23994

1. In a workspace that has a space in the path
1. In native repl run:
```python
import os
print(os.getcwd())
```

## Bug
A broken link is created. Here my workspace folder is called `sub space`

![Image](https://github.com/user-attachments/assets/96f811e1-2aca-464a-8a8b-0149e8c1671a)

**Comment by rebornix** [comment]
We will track this in https://github.com/microsoft/vscode/issues/236113
