### ISSUE TITLE
`onDidOpenTerminal` fires twice for send text

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#226893]
Testing #226655

```typescript
vscode.window.onDidOpenTerminal(e => {
			e.sendText('echo hi');
		}),
```
this ends up firing twice or an extra "echo hi" shows up

![Screenshot 2024-08-27 at 2 26 06 PM](https://github.com/user-attachments/assets/c3f2b35f-e7df-4bad-ad36-d5c89c18eb7d)

**Comment by justschen** [comment]
also it seems like `e.shellIntegration?.executeCommand('echo hi');` does not work in `onDidOpenTerminal`

**Comment by meganrogge** [comment]
@justschen, it's not firing twice. The input is received before the prompt starts, so it gets written to the terminal. You can repro this if you create a terminal and type quickly like the below. 

![Image](https://github.com/user-attachments/assets/83a23fe4-068c-40aa-afe4-e222548aa895)

**Comment by legomushroom** [comment]
@justschen I think that is exactly what @meganrogge said happens here 🤗

> also it seems like `e.shellIntegration?.executeCommand('echo hi');` does not work in `onDidOpenTerminal`

The `shellIntegration` is always `undefined` when terminal starts, you need to wait on the `window.onDidChangeTerminalShellIntegration` to be notified when shell integration is a fully activated for the terminal, e.g.:

```typescript
vscode.window.onDidOpenTerminal((_event) => {
    vscode.window.onDidChangeTerminalShellIntegration((event) => {
        event.shellIntegration?.executeCommand('echo hi');
    });
});
```

Note that this even can fire multiple times. 

Please reopen if you still think that the issues exist 🤗
