### ISSUE TITLE
Copy-paste doesn't work properly with Unix-style line endings under Windows

### ISSUE THREAD

**Issue by corford** [Microsoft/vscode#22688]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new file in vscode, set line endings to LF and type some lines of text (pressing enter a few times between each line)
2. CTRL-A, CTRL-C
3. Open putty and ssh into a remote linux box (e.g. ubuntu)
4. Open a text editor on the remote box (e.g. nano) and paste the text - all empty lines are gone

This is because vscode (unlike most other editors on Windows e.g. Sublime) does not convert line endings to the platform's native line ending format when placing text in to the clipboard. As a result other Windows programs (like putty) have problems working with it.

The only workaround (I have found) is to temporarily change the line-endings to CRLF, copy the text and then change them back to LF.  It's cumbersome and error prone.
 
Unsure if this is a vscode issue or an electron one as a similar issue exists with Atom (see: https://github.com/atom/atom/issues/8365)

**Comment by cecilemuller** [comment]
Was this closed because it's fixed in the next release or closed because it's been in the backlog for a while ?

**Comment by alexandrudima** [comment]
@cecilemuller The change pushed via c935020 will make it that when copying or cutting in the editor on Windows, the text written to the clipboard will always contain CRLF line endings, even if the file uses LF line endings.

**Comment by cecilemuller** [comment]
That's wonderful, thank you 😃
