### ISSUE TITLE
`folderOptions` on query, vs options

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#226814]
Testing #226669

It sort of feels like `folderOptions` should be on the "query", not on the options, since it just feels like a fundamental part of the query. I am searching this folder for this pattern, that's the most important thing. Then you have `surroundingContext`, `previewOptions`, etc which are additional "meta" flags that relate to how results are presented, etc.

**Comment by andreamah** [comment]
I think of `query` as more of how the text itself is looked up (how you know that it's a 'match' when you see it in text), whereas the options are more like how to filter files and any extra limitations. I guess that this also simplifies some of the arguments for `findTextInFiles`, as it also uses the same query type as `TextSearchProvider`.

**Comment by andreamah** [comment]
I guess that you could argue that the provider implementer will look at it as more like "given these files, I need to search using this criteria", so then thing like the `include` are really important. But I also could argue that the way that we have it right now with clear parallels also just makes the relationship between the APIs cleaner and easier to understand.

**Comment by roblourens** [comment]
Yeah, I can see it either way.

**Comment by andreamah** [comment]
I'm going to continue discussion about this what's in `query` vs `options` in https://github.com/microsoft/vscode/issues/226738. Although it's not an identical convo, I should probably just collect feedback on how to re-shape on that thread.
