### ISSUE TITLE
JS/TS Crashed Multiple Times

### ISSUE THREAD

**Issue by AngeloAnolin** [microsoft/vscode#226890]
Type: <b>Bug</b>

Just got notice from VS Code that the TS/JS crashed multiple times.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (3.26GB free)|
|Process Argv|--crash-reporter-id b2236b50-6d13-4959-bcd1-8af930038477|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
aws-toolkit-vscode|ama|3.21.0
jsoncrack-vscode|Ayk|2.0.3
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
rust-syntax|dus|0.6.1
gitlens|eam|15.3.1
prettier-vscode|esb|11.0.0
vscode-jest-runner|fir|0.4.73
copilot|Git|1.223.0
copilot-chat|Git|0.18.2
gitlab-workflow|Git|5.8.0
terraform|has|2.32.2
vscode-edit-csv|jan|0.9.2
vscode-peacock|joh|4.2.2
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.5
remote-containers|ms-|0.380.0
material-icon-theme|PKi|5.9.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.2089
sonarlint-vscode|Son|4.9.1
vscode-icons|vsc|12.8.0
pretty-ts-errors|Yoa|0.6.0
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
fje88620:31121564
aajjf12562cf:31125794

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
