### ISSUE TITLE
While clicking on Source control icon VSCODE is crashing

### ISSUE THREAD

**Issue by nishant-sunstone** [microsoft/vscode#226867]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2 (Universal)
- OS Version: macOS Sonomo 14.6.1

Steps to Reproduce:

1. When I'm clicking on source control in vscode, it hangs for some time and then finally crashed.
2. Its happening every time now from few days(after update to latest version I think)
<img width="669" alt="Screenshot 2024-08-28 at 12 25 26 AM" src="https://github.com/user-attachments/assets/ba84a0ef-94b0-4894-9b23-7c35eb1984ca">

**Comment by gjsjohnmurray** [comment]
Please add the setting `"scm.showHistoryGraph": false` and see if this resolves your issue.

**Comment by nishant-sunstone** [comment]
Yes its worked

**Comment by tomasvn** [comment]
IMO, It is not fixed, I see it as a temporary solution

**Comment by gjsjohnmurray** [comment]
@tomasvn this whole area has been reworked in the upcoming 1.93, which you can already try if you install Insiders.
