### ISSUE TITLE
Support linking to GH issues from scm graph

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#226833]
Testing #226648

There are so many potential useful links in the list, could we somehow allow GHPR to make the #numbers links?

<img width="540" alt="Screenshot 2024-08-27 at 10 40 52 AM" src="https://github.com/user-attachments/assets/cf698051-3b7c-4740-84a1-82ebd0dfb7b9">

**Comment by lszomoru** [comment]
Absolutely. Something that we are looking at already.

**Comment by gjsjohnmurray** [comment]
See #223043
