### ISSUE TITLE
Azure Resources not logging into personal acct

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#226892]
Testing #226539

1. Enable MSAL
2. `Azure: Sign In`
3. `Sign into other account` since I want to use my other account.
4. Will pop up a window to say I'm logged in (without asking what the other account is).
5. Try doing `Azure: Sign In` again- nothing is changed

**Comment by andreamah** [comment]
Seems that this also happens with generating a token using msft- it just defaults to the account that is already logged in.

**Comment by TylerLeonhardt** [comment]
This worked for me now, maybe try it again now that we've polished MSAL a bunch?

**Comment by andreamah** [comment]
I can't remember which `Azure: Sign In` I used

![Image](https://github.com/user-attachments/assets/204c2e29-8672-417b-ae4e-3a6c95a34cea)

For the resource group one, I can verify that the bug still exists. When I select 'Sign in to another account', it just sends me to a window that says "You are signed in now and can close the page".

![Image](https://github.com/user-attachments/assets/a011e784-6e57-4850-b136-9841630d7e1c)

**Comment by TylerLeonhardt** [comment]
Nice find, I need to tell MSAL to actually show you the picker in the browser. PR out now for that.
