### ISSUE TITLE
why is there a `cwd` on both `shellIntegration` and `execution` ?

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#226876]
Testing #226655

![Image](https://github.com/user-attachments/assets/98eac4db-b43d-4eeb-87f7-1c50c2a099b8)

**Comment by Tyriar** [comment]
`execution.cwd` is the working directory as the time the execution happened. `shellIntegration.cwd` is the current cwd, ie. the cwd of the upcoming execution.

```
// ~/vscode
console.log(shellIntegration.cwd);

const execution = shellIntegation.executeCommand('cd src');

// ~/vscode
console.log(execution.cwd);
// ~/vscode
console.log(shellIntegration.cwd);

await executionEndEvent;

// ~/vscode/src
console.log(shellIntegration.cwd);
```
