### ISSUE TITLE
Focus current symbol when opening symbols list

### ISSUE THREAD

**Issue by ilyabirman** [microsoft/vscode#22689]
- VSCode Version: 1.10.2
- OS Version: 10.12.1

Steps to Reproduce:
1. Put caret inside a function in a PHP file with many functions.
2. Open symbols list.

Current behavior: Symbols list opens without any symbol selected. Pressing ↓ selects the first symbol in a list.

Wanted behavior: The current symbol is selected. Pressing ↑ or ↓ selected the previous or next symbol in the file. This is how Sublime Text works. Quick way to figure out what function you are in!

**Comment by roblourens** [comment]
Would need vscode support

**Comment by ford04** [comment]
Is there any update on this request?

Copy from my created FR:
It would be awesome, if the "Go to Symbol in File..." (ctrl+shift+o default shortcut) view would start at the focused symbol at cursor position.

Currently, nothing is selected and you have to navigate through the list entries or type part of the symbol. When you narrow the entries through typing, you loose the "big picture" with all symbols of the file and awareness of current position in the file.

I would like to use this view as quick navigation through the open file relative to the current cursor position.
This behaviour could be copied somehow from the outline view, which has the ability to follow the cursor.
Outline view also allows navigation through the file, but I would prefer not loosing the focus, if sidebar is hidden.

**Comment by jrieken** [comment]
This is actually quick outline. @bpasero any change this is supported there?

**Comment by bpasero** [comment]
@jrieken no we currently have no support for selecting the symbol in the quick outline when it opens, but a fair feature request.

**Comment by jasonwilliams** [comment]
Hey @bpasero what do you mean by "no support"? It's something vscode can't do natively?

**Comment by haotangextreme** [comment]
it surprises me, this has been sitting for years,  still "not support".  can not wait to have this.

**Comment by everyonesdesign** [comment]
That actually would also allow to very conveniently navigate found files in search results editor even when starting from the middle of the list

**Comment by zingdle** [comment]
When you highlight symbol (or some text) and press `Ctrl + Shift + F`, it will search in workspace instantly.

It's good to have something silimar in `Go to Symbol` when pressing `Ctrl + Shift + O`.

**Comment by TylerLeonhardt** [comment]
This works now. https://github.com/microsoft/vscode/pull/154247
