### ISSUE TITLE
origin/main label background color?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#226827]
Testing #226648

I couldn't find this color when searching the generated theme:

![image](https://github.com/user-attachments/assets/73f84ddb-1ffd-403c-a598-ca7ede5216cd)

Is it hardcoded or derived from another?

**Comment by lszomoru** [comment]
The theme color for `origin/main` is `scm.historyGraph.historyItemGroupRemote`. 

At the moment we have the following theme colors to control the graph colors: 
* scm.historyGraph.historyItemGroupLocal
* scm.historyGraph.historyItemGroupRemote
* scm.historyGraph.historyItemGroupBase
* scm.historyGraph.green
* scm.historyGraph.red
* scm.historyGraph.yellow

**Comment by Tyriar** [comment]
Ah I see the color match up with the generated theme command now, might have pasted the wrong color into the find widget when searching for it.
