### ISSUE TITLE
quick pick padding in the search bar

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#226908]
looks like the quick pick has some extra padding or missing some padding since the search bar and the selection don't line up, so it looks off centered

![Screenshot 2024-08-27 at 4 48 45 PM](https://github.com/user-attachments/assets/4b8c909c-b480-4907-b7ea-5eba6e03d8ab)

**Comment by TylerLeonhardt** [comment]
Dupe https://github.com/microsoft/vscode/issues/233699
