### ISSUE TITLE
Weird gray rectangles in file picker and git view

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#22695]
Is this a rendering bug of chrome? I tried looking in chrome devtools to see if there was something wrong in css but I couldn't see anything popping out.

Seen this happen on both mac and windows. Using VScode 1.10

![image](https://cloud.githubusercontent.com/assets/1018196/23972195/18987a72-098e-11e7-99a4-7236b2666f5b.png)

**Comment by weinand** [comment]
probably duplicate of https://github.com/Microsoft/vscode/issues/22678

**Comment by nojvek** [comment]
Okay closing.
