### ISSUE TITLE
Microsoft authentication: non-stop handleSecretStorageChange/getSessions events (MSAL)

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/vscode#226907]
Does this issue occur when all extensions are disabled?: N/A

Version: 1.93.0-insider (user setup)
Commit: ff7a154d5e5e9034914f0466420f0f1407f0c95e
Date: 2024-08-27T05:04:20.235Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.27693

I'm getting an absolute deluge of Microsoft auth events which look like they're _constantly_ re-acquiring sessions. CPU usage as measured by Task Manager is hovering around ~10-15%.

Steps to Reproduce:

1. Not sure. At some point, VS Code will go into a fit until I reload the window.

Here's a snippet of the logs if they help... https://gist.github.com/50Wliu/52112d8e03c058887e53ea973c7111d2

https://github.com/user-attachments/assets/db1329fb-b4a8-4206-ac1d-e59a164b0bbb

**Comment by TylerLeonhardt** [comment]
Fixed in https://github.com/microsoft/vscode/pull/227854 I'm pretty sure.

**Comment by TylerLeonhardt** [comment]
Verified via telemetry with Identity team. This spam is no longer happening. Also, when I looked at @50Wliu's logs I didn't see the bad behavior anymore.
