### ISSUE TITLE
Hover - Instant hover is not shown instantly

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#226948]
Steps to Reproduce:

1. Open a folder/workspace that contains a git repository 
2. Open the Source Control viewlet and expand the Source Control Graph view
3. Hover over one commit and wait for the hover to appear
4. Move the mouse quickly across multiple items and notice that at one point the hover disappears a it waits for the delay to appear

**Comment by benibenj** [comment]
Should be fixed
