### ISSUE TITLE
vscode debug values should take into account source map names

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#22690]
The ES5 transpilers such as Typescript and babel translate nested `this` into `_this1`, `this2` e.t.c

the source map generated by transpiler contains what names should be used as the values but this isn't taken into account via inline values or hover in the editor. To get the actual values, a user has to do guess via console on what the generated property is actually called. 

I believe the experience can be improved. Happy to send a PR if you guide me on how to get source map names from the debug adapter.

@roblourens @isidorn

**Comment by roblourens** [comment]
We have this issue: https://github.com/Microsoft/vscode/issues/12066 and I think it would be implemented entirely in the debug adapter. A PR would be awesome but I'm not sure exactly what would go into it.

**Comment by nojvek** [comment]
Okay closing this issue then.
