### ISSUE TITLE
Terminal Font Size Occasionally Changes to Negative Value When Pasting in VSCode Terminal

### ISSUE THREAD

**Issue by jobinkavalam** [microsoft/vscode#226925]
Type: <b>Bug</b>

Intermittently, when pasting certain text into the VSCode terminal, the terminal font size changes to a negative value (e.g., -1232). This unexpected behavior causes the font size to become quite small, though the terminal remains functional. The font size must be manually corrected in the settings to restore readability.

## Steps to Reproduce:

1. Open Visual Studio Code.
1. Navigate to the terminal section.
1. Copy some text from an unknown source.
1. Occasionally, paste the copied text into the terminal.
1. Observe the terminal font size setting.

## Actual Result:
The terminal font size occasionally changes to a negative value (e.g., -1232) when specific text is pasted.

## Expected Result:
The terminal font size should remain unaffected by pasted text and maintain its default or previously set value.

VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-t:31111718
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562cf:31125794

```

</details>

Attachment: ![vscode-bug](https://github.com/user-attachments/assets/ddfc06d3-47e8-4447-bb46-3c54863994c4)

**Comment by meganrogge** [comment]
I cannot reproduce. A gif would help
