### ISSUE TITLE
preview for collapsed cells in diff view

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#226984]
Testing #226663

Could we show the first line of the cell as we do for collapsed cells in the notebook editor? With a large amount of collapsed cells, it is pretty hard to know where I am in the notebook. Doing this for markdown cells could be especially effective.

![image](https://github.com/user-attachments/assets/23c05ba9-7d70-459b-b4ba-4c4bc0177973)

**Comment by DonJayamanne** [comment]
As we haven't had enough upvotes on this feature request I'm closing this as not planned.
