### ISSUE TITLE
scrollbar consumes mouse clicks even when scrollbar is not present

### ISSUE THREAD

**Issue by ad8e** [Microsoft/vscode#22699]
- VSCode Version: 1.10.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. Move your mouse to the bottom of the VSCode window, where a horizontal scrollbar would normally be.
2. Notice that the mouse cursor changes from a text cursor to a pointer when mousing over the scrollbar position, whether the scrollbar is present or not. Also, clicks there are captured by the invisible scrollbar.

**Comment by alexandrudima** [comment]
Fixed via #42801
