### ISSUE TITLE
Output in terminal ignores line/column numbers 

### ISSUE THREAD

**Issue by mmkal** [Microsoft/vscode#22692]
- VSCode Version: 1.10.2 (Commit 8076a19f)
- OS Version: Windows 10 Enterprise v1607

Steps to Reproduce:

1. Run a js/ts file from terminal (press `ctrl-'`) (in my case I ran using `ts-node myfile.ts`)
2. Throw an error
3. Click on one of the call stack lines

Expected
* Editor window jumps to correct line number within file.

Actual
* Editor window jumps to the top of the file.

When I hover over the line of the call stack, you can see that only the file is highlighted, not the line or column number (see underlined file):
![image](https://cloud.githubusercontent.com/assets/15040698/23971972/6b8c85f8-09a6-11e7-9663-91b3272742fe.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/21472
