### ISSUE TITLE
`findFiles2New` Should cancel return an `[]` array

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#226914]
Testing #226670

Should it return CancellationError instead?

**Comment by andreamah** [comment]
Taking a quick look at finalized API, we don't seem to throw `CancellationToken` upon cancellation too much (especially considering that there are lots of APIs that have this token-to-cancel style of calling). 

@jrieken You're probably the expert on whether we should be throwing `CancellationToken`- I'm willing to make the change if it's consistent with others.

**Comment by jrieken** [comment]
Let's stick with what the current API does.
