### ISSUE TITLE
Terminal copilot initial hint should not show up for extension terminals

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#226992]
See this frame from https://github.com/microsoft/vscode/issues/226988 report:

![image](https://github.com/user-attachments/assets/f1145ed0-68ca-4642-bb77-9cfc2d56ee9f)

**Comment by rzhao271** [comment]
The hint isn't showing up for me at all right now.
I'm on the latest Insiders on Windows 11 with pwsh.

**Comment by andreamah** [comment]
Same here- the initial hint should appear in the regular terminal, right? I don't even see that.

**Comment by rzhao271** [comment]
Verified on macOS by clearing out my Insiders profile
