### ISSUE TITLE
"It continues loading after the last update, and I can't see the latest updated files due to the loading issue."

### ISSUE THREAD

**Issue by Drashti1510-cpu** [microsoft/vscode#226955]
Type: <b>Bug</b>

"It continues loading after the last update, and I can't see the latest updated files due to the loading issue."
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.66GB free)|
|Process Argv|--crash-reporter-id 00abbefd-af7c-4a05-b31c-19a172017460|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
project-manager|ale|12.8.0
cmake-format|che|0.6.11
gitignore|cod|0.9.0
react-redux-react-router-snippets|dis|0.4.29
git-extension-pack|don|0.1.3
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.3.1
prettier-vscode|esb|11.0.0
duplicate|gee|1.0.2
chatgpt-vscode|gen|0.0.11
error-gutters|Igo|1.0.1
vscode-chat-gpt|ika|1.2.0
remove-break-lines|jal|1.0.0
statusbarerror|Joe|0.4.0
remove-unused-imports|kus|1.2.4
git-graph|mhu|1.30.0
betty-extension|mou|3.0.2
vscode-docker|ms-|1.29.2
vscode-versionlens|pfl|1.14.2
vscode-react-refactor|pla|1.1.3
postman-for-vscode|Pos|1.2.1
vs-code-prettier-eslint|rve|6.0.0
skillhub-react-redux-toolkit-snippets|ski|0.0.2
vscode-stylelint|sty|1.4.0
prettier-plus|svi|4.2.2
node-pack|Swe|0.1.16
tabnine-vscode|Tab|3.146.0
errorlens|use|3.20.0
remove-empty-lines|use|1.0.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-c:31125598
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by gjsjohnmurray** [comment]
If it is the Source Control history graph that is causing this I suggest you add this setting:

`"scm.showHistoryGraph": false`

Performance issued have been addressed in the upcoming 1.93

**Comment by chenzhuoyu** [comment]
@gjsjohnmurray Works for me!

**Comment by lszomoru** [comment]
Please upgrade to the latest VS Code version (1.93) as there have been many improvements in this area.
