### ISSUE TITLE
unpredictable grouping of collapsed cells

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#226979]
Testing #226663

It's hard to guess which cells are going to be grouped into a collapsed set - it might have something to do with markdown vs code cells, but not completely consistent. Also, whether or not the content in the cell input is shown or collapsed.

![image](https://github.com/user-attachments/assets/2dbbfcd8-5a19-4cf2-86f1-924d621ddd90)

![image](https://github.com/user-attachments/assets/636b1214-3f96-4f56-acbd-28209e2b4163)

**Comment by DonJayamanne** [comment]
@amunger Please can you share the steps to repro this issue.

**Comment by DonJayamanne** [comment]
> Also, whether or not the content in the cell input is shown or collapsed.

Unchanged cells will be collapsed.
Once you have this issue, just open the text file diff view and compare the text changes (in json), then paste the two/three JSON files, that way I too can replicate this at my end (all I need are the same diffs, either the diffs or the instructions to replicate)

**Comment by DonJayamanne** [comment]
Also, please ensure you test with the latest insiders, as an issue was resolved that prevented changes from being detected once you had opened the diff view.

**Comment by amunger** [comment]
making a change in the CITestResults.ipynb in the jupyter repo seems to happen pretty often

1. open the file and make a change to one of the cells
2. open the diff view from the source control sidebar

result: some unchanged cells are expanded, and the hidden groups are split around those cells
![image](https://github.com/user-attachments/assets/b92ae331-3b94-4dc1-9c45-e296f794de85)

**Comment by DonJayamanne** [comment]
Cannot repro, 
![Screenshot 2024-08-30 at 05 59 13](https://github.com/user-attachments/assets/90043510-4b94-4b1c-850d-e1d580153c01)

Please can you share the text file diffs

**Comment by DonJayamanne** [comment]
Perhaps there are some white space changes or the like,

**Comment by amunger** [comment]
the text file diff only has the one change that is shown in the notebook diff.

might have a better repro:
1. make a change in cell 3
2. scroll down and focus in a cell further down
3. open the diff view

:bug: the focused cell is shown in the diff view (no changes), and the cell with changes is hidden.

![Recording 2024-08-29 at 13 28 32](https://github.com/user-attachments/assets/8e5508c9-c8be-46e9-9b19-da3de0033cd8)

**Comment by DonJayamanne** [comment]
Please can you 
* Close all files
* Reload VS Code
* Try again
* This time make change to just 1 cell
* If you change other cells after you load the diff view, then things will not work as expected, (known issue)

Sorry, but I'm not able to repro this

**Comment by amunger** [comment]
same thing after reloading, the diff view is just showing cells that are in active in the notebook editor list view

**Comment by amunger** [comment]
no longer repro's
