### ISSUE TITLE
Terminal instantly closing on open

### ISSUE THREAD

**Issue by n-hennigh** [microsoft/vscode#226915]
Type: <b>Bug</b>

I am using version 1.92.2 and whenever I open the terminal or the bottom panel view that includes the terminal it immediately closes. Changing the default terminal opened did not change anything

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 4900HS with Radeon Graphics          (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.42GB (8.54GB free)|
|Process Argv|--crash-reporter-id 627b955b-f56f-4cb3-b6a6-b5c7b0d93a28|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.12.4
beyond-debug|coo|0.9.15
flask-snippets|cst|0.1.3
gdb-debug|Dam|1.0.7
composer-php-vscode|DEV|1.50.15906
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.50.15906
profiler-php-vscode|DEV|1.50.15906
peachpie-vscode|iol|1.0.8
azure-dev|ms-|0.8.3
vscode-azureappservice|ms-|0.25.3
vscode-azurecontainerapps|ms-|0.7.0
vscode-azurefunctions|ms-|1.15.3
vscode-azureresourcegroups|ms-|0.9.2
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.16.1
vscode-azurevirtualmachines|ms-|0.6.5
vscode-cosmosdb|ms-|0.22.0
vscode-docker|ms-|1.29.2
csdevkit|ms-|1.9.55
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.5
vscodeintellicode-csharp|ms-|2.1.11
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.380.0
remote-wsl|ms-|0.88.2
azure-account|ms-|0.12.0
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.10.26
vscode-node-azure-pack|ms-|1.2.0
vscode-nuget-gallery|pat|1.2.1
java|red|1.33.0
vscode-xml|red|0.27.1
vscode-xml-complete|rog|0.3.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-c:31111717
wkspc-ranged-c:31125598
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal
