### ISSUE TITLE
Action shortcut conflicts

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2269]
On linux

@alexandrudima we are conflicting for output / repl toggling and replace shortcuts. Did you change these shortcuts in the last couple of days since I did not see this warning before and I tried on linux once I introduced mine.

![screen shot 2016-01-26 at 09 46 49](https://cloud.githubusercontent.com/assets/1926584/12576123/c9d29912-c411-11e5-9f77-3e02f91d4468.png)

**Comment by alexandrudima** [comment]
I merged a PR that introduced `replaceOne`.

I did not touch format whatsoever -- did you ever try your new keybinding in linux before?

> Pro tip: [Here you can see how the default keybindings have changed](https://github.com/Microsoft/vscode-docs/blob/master/scripts/keybindings/doc.keybindings.linux.json)

**Comment by isidorn** [comment]
I have changed the replace one to be cltr+shift+1 - which i think is intuitive
Replace toggle consoly to ctrl+shift+Y so it is next to ctrl+shift+U for toggling output
