### ISSUE TITLE
Cmd-A doesn't select all text in the save dialog save-as field

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode#22696]
- VSCode Version: Version 1.10.2 (1.10.2), 8076a19fdcab7e1fc1707952d652f0bb6c6db331
- OS Version: MacOS 10.12.3 (16D32)

Steps to Reproduce:

1. Create a new document.
2. Save it.
3. Move the cursor to the end of the default Save As text.
4. Press Cmd-A. Nothing is selected.

**Comment by bpasero** [comment]
This is the same as https://github.com/Microsoft/vscode/issues/19003, though in a different location.
