### ISSUE TITLE
Set default save location to that of most recent file

### ISSUE THREAD

**Issue by xavdid** [Microsoft/vscode#22697]
- VSCode Version: `Version 1.10.2`
- OS Version: `macOS 10.12.2`

This is a feature request from Sublime Text. I have a fairly well nested project and anytime I go to save a new file, it always defaults to project root (which makes sense). However, if I'm trying to save `project/assets/templates/category/file.html` and `project/assets/static/styles/category/file.scss` it can get really tedious to get those save locations. 

In ST, when you're saving a new file, the mac saver dialog defaults to the location of the most recently open file. This is great because you can open an existing file in the directory you want, hit the new tab, and `save` puts it right where you want it to be. 

Right now, my workaround is to use "copy path" in the side bar and `touch` in the integrated terminal to create the file I need, then paste in. 

This would be a super useful feature for very complex file structures in projects!

**Comment by andrewkincaid** [comment]
I'd like to see options for "default save location" behavior like most recently opened file, last saved location, hard-coded location, etc.
