### ISSUE TITLE
Source Control Not Picking changes as and when files are updated

### ISSUE THREAD

**Issue by Honey20** [microsoft/vscode#226958]
Type: <b>Bug</b>

Make some changes in files, click on view -> source control

1. File changes are not picked up in source control unless we disable and enable Git extension
2. Once extension is enabled again, latest changes are picked up but if we make more changes, or revert any changes, the source control does not update the files.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (10.35GB free)|
|Process Argv|--crash-reporter-id 89574c38-aa5d-4c6c-bb88-f557cc5cfefe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.2.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.3.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|11.0.0
code-runner|for|0.12.2
copilot-chat|Git|0.18.2
vscode-jetbrains-keybindings|isu|0.1.9
angular-essentials|joh|18.0.0
Angular2|joh|18.0.2
vscode-peacock|joh|4.2.2
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.2
material-icon-theme|PKi|5.9.0
vscode-yaml|red|1.15.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-c:31125598
pme_test_c:31118331
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by lszomoru** [comment]
@Honey20, could you try setting the `typescript.tsserver.experimental.useVsCodeWatcher` setting to `false` to see if that helps?

**Comment by Honey20** [comment]
Hi, I tried setting it to false but the issue still persists. Source
control is not picking changes as and when files are updated. This issue is
witnessed after I had updated the VS code with the latest update.


Will be grateful if you can help me with this.

Regards
Honey Srivastav
Software Engineer
ZS Associates

**Comment by lszomoru** [comment]
Can you please follow the steps from [this wiki](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues#logging-local) and share the logs so that we can see that the file system events are working.

**Comment by ianldgs** [comment]
> @Honey20, could you try setting the `typescript.tsserver.experimental.useVsCodeWatcher` setting to `false` to see if that helps?

That worked for me, @lszomoru!

**Comment by Honey20** [comment]
The issue was resolved after updated the application.

Thanks.

**Comment by lszomoru** [comment]
@Honey20, thanks for the update! I will go ahead and close this issue.
