### ISSUE TITLE
[sideloading] needs to happen in main thread

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#227]
Side loading of extensions should move out of the renderer and into the shared process where we do the install of plugins.

@joaomoreno just moved this bug over from tfs, we should look into it together

**Comment by joaomoreno** [comment]
Excellent.

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
@isidorn @joaomoreno ping, lets D0 this 👍

**Comment by joaomoreno** [comment]
Fixed!
