### ISSUE TITLE
Using find, negated set with right parenthesis in regular expression does not seem to work

### ISSUE THREAD

**Issue by simon-glitch** [microsoft/vscode#227021]
Type: <b>Bug</b>

I am using the "find and replace" tool, and I have this regular expression:
,\(0,([^\)]+)\)

It's supposed to find 2 matches in the following text:
                Rd['bvM']['bIo'] = rP['W']['Fvm'],
                Rd['bNl'] = Fd['blB'](new r8(r7['A']['bxs']['bSE'],(0,
                rp['LX'])(rC['A']['bwI'], rC['A']['bwI']),(0,
                rp['LX'])(1, 7),0,true)),
                Rd;

It seems is cannot find them. I believe this might be an issue with regex.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz (4 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.65GB (0.17GB free)|
|Process Argv|--crash-reporter-id 68353614-77e4-4900-b651-942496736b9d|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-c:31125598
ei213698:31121563
aajjf12562cf:31125794

```

</details>

**Comment by RedCMD** [comment]
`,0,true` is the only possible match
![image](https://github.com/user-attachments/assets/721c6a82-33f4-4ef2-955d-de3c6d54e6fb)


there are no other commas `,` followed by a zero `0` present `,0`
![image](https://github.com/user-attachments/assets/deb5dcdd-6a13-4055-bd9f-c0e3fedcd90a)

are you wanting to match the brackets `()` and across newlines? `,\(0,([^\)]+|\n)\)`
![image](https://github.com/user-attachments/assets/ceb9bede-bdb8-4a50-88b2-69ed86c745d8)
