### ISSUE TITLE
notebook output is wrong

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#227018]
- See that I'm logged in
- run the endgame github issues notebook release notes query
- see issues that don't belong to me 

![Image](https://github.com/user-attachments/assets/bbc92c0e-52a6-4d19-a3d9-2f904bb88ab3)

**Comment by amunger** [comment]
that would rely on $MINE being set correctly, did you run the top cell first?
if you replace $MINE with `assignee:@me` does it work correctly?

**Comment by meganrogge** [comment]
I tried that and it did not work. reloading fixed it 🤔

**Comment by amunger** [comment]
My guess is that the macro wasn't set properly somehow. I'll close for now but if it comes up again, I can try to look into how that all works.
