### ISSUE TITLE
Option to create fresh Profile with no sign in

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#227000]
Came up during [testing](https://github.com/microsoft/vscode-copilot/issues/5665)

@aiday-mar found that even in new Profiles, she was still signed in to her GitHub and Microsoft accounts. 

I'd love the option to create a truly blank Profile with no authentication preserved.

**Comment by sandy081** [comment]
I believe auth sessions are application specific, hence they are available across profiles.

**Comment by TylerLeonhardt** [comment]
Auth accounts are the higher level item compared to Profiles so creating a new profile without sign in doesn't really make sense for us.

For example, your profiles are synced to the account you have signed in to for Settings Sync.

Additionally, for this to work, we'd need completely separate secret storages (that the GitHub & Microsoft auth extensions could leverage) which would be theoretically possible but currently is not the behavior.

So unless someone has a really compelling reason why we should do this, I don't think we should go in this direction.

**Comment by bamurtaugh** [comment]
Ah, okay then I see why it'd be odd and introduce a new state here. In my mental model, a Profile wasn't tied to anything, but I see now that it can be tied to an account, so this would almost introduce a whole new flow for / type of Profile (there'd continue to be Profiles tied to your auth account, and we'd need this new concept of ones not tied to any account), and it'd be odd to consider a Profile tied to an account that then wasn't signed in when a user entered it.

I'll close this issue for now, and I'll report back if I think of anything else or hear any other user feedback.
