### ISSUE TITLE
Show dirty indicator close to file when tabs are disabled

### ISSUE THREAD

**Issue by metasong** [Microsoft/vscode#22709]
show file modified circle on the title of the file when in Zen mode.
currently vscode will show the file modified circle icon in normal model.
![image](https://cloud.githubusercontent.com/assets/5009757/23978370/abd3e07e-0a2e-11e7-90a6-8fb08fd2f1dc.png)

**Comment by bpasero** [comment]
@metasong the file dirty indicator is all the way to the right when tabs are disabled.

**Comment by bpasero** [comment]
Suggest to close this as dupe of https://github.com/Microsoft/vscode/issues/19531
