### ISSUE TITLE
Color Picker works only once

### ISSUE THREAD

**Issue by jano23** [microsoft/vscode#227080]
Type: <b>Bug</b>

When I open a CSS file and click on a color declaration's color decorator square, the color picker window shows up and allows me to select a new color.
This happens only once. If I need to change another color, I have to restart VSCode and again, it will work only once

- VS Code Version: 1.92.2
- OS Version: Windows 11

Steps to Reproduce:

1. Open VSCode
2. Open a CSS file
3. Click on a color decorator
4. Select a color from the color picker interface
5. Click on the same decorator or any other decorator 
6. Nothing happens
7. I have to restart VSCode for it to work again - once

I have tried restarting VSCode with Extensions disabled. Same results
In Text Editor settings I have  Color Decorators checked, Color Decorators Activated on Click (tried clickAndHover as well).
Color Decorators Limit is set to the default 500.
I don't have any other color picker extensions installed.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700K (20 x 3610)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.73GB (105.79GB free)|
|Process Argv|--crash-reporter-id 1983002f-2bca-4aa5-808c-fff939489454|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (98)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.4.0
vscode-sqlite|ale|0.14.1
icons-carbon-tweaked|aly|0.2.1
better-find-and-replace|ami|0.0.2
sublime-cmd-shift-d|and|1.2.2
icons-carbon|ant|0.2.6
houston|ast|0.1.2
surround-with-tag|Bal|1.0.0
vscode-icontheme-nomo-dark|be5|1.3.6
beardedicons|Bea|1.18.0
catppuccin-vsc|Cat|3.15.2
path-intellisense|chr|2.9.0
regex|chr|0.4.0
gitignore|cod|0.9.0
font-preview|ctc|2.2.1
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|3.0.10
composer-php-vscode|DEV|1.50.15906
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.50.15906
profiler-php-vscode|DEV|1.50.15906
githistory|don|0.6.20
xml|Dot|2.5.1
sync-scroll|dqi|1.3.1
gitlens|eam|15.3.1
permute-lines|ear|1.1.0
el-vsc-product-icon-theme|ElA|0.1.8
vscode-great-icons|emm|2.1.106
fira-code-nerd-font|ent|0.0.3
vsc-material-theme|Equ|34.5.2
vsc-material-theme-icons|equ|3.8.8
prettier-vscode|esb|11.0.0
font-switcher|eva|4.1.0
file-icons|fil|1.1.0
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
vscode-flatland-icon-theme|geb|0.0.6
codespaces|Git|1.17.2
vscode-pull-request-github|Git|0.94.0
live-sass|gle|6.1.2
helium-icon-theme|hel|1.0.0
pro-deployer|hem|2.4.1
workspacesort|ici|1.6.2
git-buttons-vscode|idm|1.1.0
classic-asp|ili|0.0.4
path-autocomplete|ion|1.25.0
html-links-checker|j-c|1.1.13
copy-filename|jac|2.3.2
easy-icons|jam|0.3.1
polacode-2019|jef|0.6.1
color-picker-universal|Jer|2.6.0
vscode-peacock|joh|4.2.2
classic-asp-html|jtj|0.1.3
vscode-position|jtr|1.1.2
break-from-comma|jza|1.1.6
theme-dark-plus-contrast|k3a|1.76.0
vscode-gist|ken|3.0.3
vscode-pdf|mat|0.0.6
rainbow-csv|mec|3.12.0
fluent-icons|mig|0.0.18
vscode-filesize|mkx|3.1.0
better-folding|Moh|0.5.1
theme-monokai-pro-vscode|mon|1.3.2
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.3
live-server|ms-|0.5.2024062701
test-adapter-converter|ms-|0.1.9
resourcemonitor|mut|1.0.7
sftp|Nat|1.16.3
syncing|non|3.3.7
material-icon-theme|PKi|5.10.0
material-product-icons|PKi|1.7.1
seti-icons|qin|0.1.3
developer-theme-dark|Raj|5.0.0
php-debug|rob|1.14.0
synthwave-vscode|Rob|0.1.15
gruvbox-material|sai|6.5.2
docxreader|Sha|1.1.3
bunker|sld|1.1.6
icons|tal|3.8.0
actual-font-changer|tal|0.0.10
ayu|tea|1.0.5
luna-paint|Tyr|0.16.0
theme-generator|use|0.0.8
highlight-matching-tag|vin|0.11.0
vscode-icons|vsc|12.8.0
gitblame|wad|11.0.1
vscode-icons-mac|way|7.25.3
snippet-generator|wen|0.3.8
vs-asp-classic|wfe|0.0.4
php-debug|xde|1.35.0
php-pack|xde|1.0.3
city-lights-icon-vsc|Yum|1.1.3
tabler-icons|zgu|0.3.4
material-theme|zhu|3.17.2
php-intellisense|zob|1.3.3

(33 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562cf:31125794

```

</details>

**Comment by jcmill** [comment]
I was running into the exact same issue yesterday. Same steps taken, same version of VS Code. The only difference on my end is I am using a Mac (OS 12.7.4).

**Comment by yueduz** [comment]
Same situation, I am using Linux+Gnome

**Comment by yueduz** [comment]
When I `code --disable-extensions` it didn't work, when I `rm -Rf ~.config/Code` it worked fine.

**Comment by yueduz** [comment]
Have you set this option?
```
"editor.hover.enabled": false,
```

**Comment by EskelCz** [comment]
I'm seeing the same behavior, haven't changed the hover option.

**Comment by Matt544** [comment]
I have `"editor.hover.enabled": false,` in *settings.json* (which I generally want, because I don't like tooltips popping up constantly when I move my mouse). When I comment that out, the color picker works again. 

The bug arises whether I have the "Editor: Color Decorators Activated On" setting as "clickAndHover" or just "click".

It would be nice to be able to use the color picker without enabling hover, which I find very annoying.

I'm on Windows 10, working in WSL. VS Code version 1.94.2.

**Comment by aiday-mar** [comment]
Hi everyone, apologies for taking long to get to it. This iteration has been AI work intensive. I have the following PR which will fix the issue: https://github.com/microsoft/vscode/pull/232586
