### ISSUE TITLE
Improve performances

### ISSUE THREAD

**Issue by foxypiratecove37350** [microsoft/vscode#227085]
I know that Visual Studio Code is built on ElectronJS, litteraly a Chrome process to render web pages in desktop apps, but that's very bad for performances. It could be great if I could use it for my everyday projects *but* because it consume too munch RAM & CPU I need to use Neovim...

So I propose you to try to find a way to improve performances because I don't have 10 Gio of free RAM.

Thanks.

**Comment by joshspicer** [comment]
Thank you for the feedback.  We strive to create a product that is performant for any platform, although architecturally I believe it is unlikely the product will move away from Electron.

**Comment by foxypiratecove37350** [comment]
@joshspicer I understand. I didn't mean to move from Electron and I know that the problem is more from the fact that Electron uses Chromium. Thanks.
