### ISSUE TITLE
Compare Selected feature shows wrong file at top

### ISSUE THREAD

**Issue by ballgitte** [microsoft/vscode#227090]
![Screenshot 2024-08-29 111623](https://github.com/user-attachments/assets/9b8521d7-c041-44cc-815a-915e509082da)
Notice how one.txt shows two.txt's contents "two".

Also, there's no other indicator on the other side which file you're looking at.

**Comment by bpasero** [comment]
Breadcrumbs currently only shows for the right-hand "primary" editor. We would need to support breadcrumbs on both sides.
