### ISSUE TITLE
Navegation Laggy

### ISSUE THREAD

**Issue by LuchitoAlberto** [microsoft/vscode#227038]
Type: <b>Performance Issue</b>

One week ago i start up VS Code and the navegation, typping and all of it became very laggy... I tried everything but it doesnt get solve

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|13.86GB (7.23GB free)|
|Process Argv|--crash-reporter-id 78cfaea4-ef88-44e8-a745-b77a1bef640c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   158	 16788	code main
    0	   111	  1512	window [4] (Notificador de problemas)
    0	   988	  6484	   window
    0	   193	  8172	   window
    0	   122	  9400	shared-process
    0	   129	 10288	extensionHost [1]
    0	    93	  1976	     "C:\Users\veget\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\veget\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\markdown-language-features\dist\serverWorkerMain" --node-ipc --clientProcessId=10288
    0	   107	 13904	   utility-process
    0	   291	 16148	window [1] (S2_Proyecto_Mortalidad_2024.pdf - Aves - Visual Studio Code)
    0	    28	 16172	   crashpad-handler
    0	    86	 16492	fileWatcher [1]
    0	    42	 17072	   utility-network-service
    0	   320	 17120	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (S2_Proyecto_Mortalidad_2024.pdf - Aves - Visual Studio Code)
|    Folder (Aves): 4 files
|      File types: txt(2) py(1) pdf(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-es|MS-|1.92.2024081409

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
fje88620:31121564
aajjf12562:31125793

```

</details>

**Comment by LuchitoAlberto** [comment]
https://www.mediafire.com/file/lx7jmob3n5c8y7o/Trace-20240829T023714.json/file 

link to perfromance profile in developer tools

**Comment by justschen** [comment]
/needsMoreInfo

I do not believe we can receive files via mediafire. could you attach the trace another way?
