### ISSUE TITLE
Feature Request: Configure VSC to stop auto-restore and build of .NET Core projects

### ISSUE THREAD

**Issue by GuardRex** [Microsoft/vscode#22702]
- VSCode Version: 1.10.2
- OS Version: Win10 Pro

I use VSC to work on documentation projects that include .NET Core samples. When I open folders to work on sample files, these sample projects should **not** be restored/built. VSC keeps creating `obj` and `bin` folders automatically against my wishes, and I need to then manually delete them from the samples.

I'm aware of ...
```json
"csharp.suppressDotnetInstallWarning": true,
"csharp.suppressDotnetRestoreNotification": true,
```
... but those don't actually prevent the auto-restore/build behavior. Looking at the [workspace settings doc](https://code.visualstudio.com/docs/customization/userandworkspace), I don't see a way to disable auto-restore/auto-build for .NET Core projects, so I'm asking if you would consider adding such a workspace setting if such a setting doesn't already exist (undocumented).

**Comment by weinand** [comment]
Please file this issues against the .NET extension.
VS Code does not include any builtin .NET functionality.
