### ISSUE TITLE
Evaluating something collapses expanded items in variables pane

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#22700]
- Start a debug session, hit a breakpoint
- Expand something in the variables pane
- Eval something in the console

The expanded item collapses. I think we re-request variables after evaluating something, but it would be great to match up the expanded items from before, to keep them expanded. Then, could even keep them expanded while stepping. Chrome devtools seems to do this.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/16031
