### ISSUE TITLE
Unfriendly error experience when adding a new setting

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2270]
Red + squiggly a bit too strong?
All that I am trying here is to trigger intelisense to add a new setting, and I get the feedback like it is the end of the world (red letters + squiggly)

![screen shot 2016-01-26 at 09 52 38](https://cloud.githubusercontent.com/assets/1926584/12576257/b30ac80c-c412-11e5-8b25-69142a1c7f18.png)

**Comment by aeschli** [comment]
That's normal syntax highlighting. What's in your document is not a valid JSON content.
As designed
