### ISSUE TITLE
Can't open html file in WSL 

### ISSUE THREAD

**Issue by jaroslaw-kaczor-111** [microsoft/vscode#227072]
Type: <b>Bug</b>

Try to open html file in WSL2 environment by clicking on "Show in Browser" has no effect. 
Opening via "Reveal in File Explorer" works fine. 
The problem is not visible when not in WSL.
Windows OS

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.68GB (6.68GB free)|
|Process Argv|--crash-reporter-id 3c47670c-463b-456a-81c6-63a475e4b31b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900H (12 x 0)|
|Memory (System)|19.54GB (16.20GB free)|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.4.3
to-typescript|ale|0.3.0
vscode-markdownlint|Dav|0.55.0
filter-lines|ear|1.1.0
html-preview-vscode|geo|0.2.5
vscode-ansi|ili|1.1.7
batch-rename-extension|Jan|0.0.6
vscode-wsl-workspacefolder|lfu|1.1.2
vscode-docker|ms-|1.29.2
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
powershell|ms-|2024.2.2
robotframework-lsp|rob|1.12.0
prettify-selected-json|vth|1.0.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-c:31111717
ei213698:31121563

```

</details>

**Comment by aeschli** [comment]
The `Show in Preview` is implemented by an extension. which doesn't properly support WSL.

I recommend to use the `Live Preview` extension instead to look at HTML. I just tried and it also works in WSL.
Any issues please file against the extension.

**Comment by jaroslaw-kaczor-111** [comment]
For **Live Preview** I can see:
![Uploading image.png…]()
Is there anything I can do to open Robot files?

**Comment by aeschli** [comment]
Please file this against the `Live Preview` extension: https://github.com/microsoft/vscode-livepreview/issues

When doing so, please provide the HTML file where it doesn't work.
