### ISSUE TITLE
ftp graphical

### ISSUE THREAD

**Issue by pinakid3** [Microsoft/vscode#22705]
- VSCode Version: 1.10.2
- OS Version: win7

Can we have graphical solution, for ftp & sftp.
Just wanted to avoid command line.

**Comment by pwwang** [comment]
+1 Just like Komodo Edit, edit a remote file directly. Without syncing, like some ftp extensions did.

**Comment by mjbvz** [comment]
Please see https://github.com/Microsoft/vscode/pull/34229
