### ISSUE TITLE
feature request: continue press ctrl+shift+i to select line up

### ISSUE THREAD

**Issue by metasong** [Microsoft/vscode#22708]
currently when press ctrl+i several times vscode will select line below. 
what about press ctrl+shift+i to select line up

analysis: ctrl+i bind to expandLineSelection, this command will select current line and move cursor to the first column of next line, 
we can implement a comand expandLineSelectionUp that select current line and move cursor to the **previous** line.

**Comment by Bill-Stewart** [comment]
Already requested: https://github.com/Microsoft/vscode/issues/1262

**Comment by alexandrudima** [comment]
Thank you @Bill-Stewart, let's track in #1262
