### ISSUE TITLE
Inheritance for Profiles

### ISSUE THREAD

**Issue by OskarHM** [microsoft/vscode#227051]
**Summary:** I propose adding inheritance support to Visual Studio Code's profiles. This feature would allow a base profile to be created, from which other profiles can inherit. The key benefit is that any changes made to the base profile would automatically propagate to all derived profiles, ensuring consistency and reducing maintenance effort.

**Key Points:**
Base Profile: Create a base profile with common settings, code blocks, plugins etc.
Inheritance: Other profiles can inherit from the base profile, automatically including its contents.
Automatic Updates: Changes to the base profile are reflected in all derived profiles, maintaining consistency and simplifying updates.

**Benefits:**
Consistency: Centralized changes ensure all derived profiles are up-to-date.
Efficiency: Reduces redundancy and manual updates across multiple profiles.
Flexibility: Allows easy customization while retaining a shared structure.
This feature would significantly enhance productivity and consistency in managing multiple configurations or projects within Visual Studio Code.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/191516
