### ISSUE TITLE
Find in Files partially broken

### ISSUE THREAD

**Issue by yoDon** [Microsoft/vscode#22704]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

I'm suddenly unable to "Find in Files" inside `*.ts` and `*.tsx` files. Searching in other file types works fine.

This behavior survives reboots and survives restarting the Windows search service.

Steps to Reproduce:

1. Ctrl+Shift+F to open Find in Files dialog
2. Search options: unselect all three options (match case, whole word, use regexp)
3. Files to include: one of
      a) `*.ts,*.tsx`
      b) `*.js,*.md`
      c) `*.*`
4. Files to exclude: blank
5. Files excluded through settings: for me this shows
        `**/.git, **/.svn, **/.hg, **/.DS_Store, **/node_modules, **/bower_components`
6. Search text: some bit of text present in many files (I've used just the letter e)

Expected behavior:

1. See list of all files and lines of text containing the indicated search term

Actual behavior:

1. When searching `*.ts,*.tsx` the results are empty even though there are many `*.ts` and `*.tsx` files matching the search condition
2. When searching `*.js,*.md` the results are as expected, all `*.js` and `*.md` files matching the search conditions
3. When searching `*.*` the results include `*.js,*.md`, and `*.json` files but no `*.ts` or `*.tsx` files

Additional behavior notes:

1. The explorer and text editor views show the `*.ts` and `*.tsx` files in the project. 

2. The typescript project builds correctly when using Ctrl-Shift-B to build.

3. Immediately before this condition started, Outlook reported a toast message something like "Windows search did not correctly close the message file" (It disappeared from the screen before I could write it down precisely). I don't know if that message is related or if it is whether it is a root cause or a symptom of some other root cause impacting both Outlook and Code. Rebooting the machine and restarting the Windows search service resolved the outlook issue but did not resolve the code issue.

4. This search condition started today. For the past month I have been receiving error messages every time I launch Code that there is a "Version Mismatch global tsc 2.1.5 != VS Code's language service 2.2.1" I have repeatedly read the link embedded in that message and have NO IDEA how to resolve that issue because the link doesn't tell me what to change or where (though I believe the current text may well be helpful to someone who already knows how to fix the issue and merely needs a reminder of what files are involved). I doubt this search issue is related to the version issue, but I mention it, and I sincerely hope that you will please also fix the page that is linked to by that error message to have a bulleted list of "step 1 do this step 2 do this step 3 do this" instructions on how to make that error message go away because it's incredibly frustrating to be completely powerless to fix the error even after repeatedly reading your "help text." But again, based on that error being present for a month prior to the search issue I doubt it's a root cause of this search issue.

[edited to fix markup that was hiding `*` characters in text]

**Comment by roblourens** [comment]
That's a weird issue. Does it happen in another workspace (folder)? If you just make a new folder that contains a .ts file and a .md file, can you search both? If 'files to include' is blank, does it search the *.ts files? 

Also, search is driven by a totally different backend in 1.11. Could you try downloading the Insiders build (or waiting until wednesday or thursday for the update) and check whether it reproes there?

The message from Outlook probably isn't related, unless it's a sign of something weird happening on your file system.

@mattbierner comments on the last part?

**Comment by yoDon** [comment]
@roblourens yes a weird issue and keeps getting weirder (these results are using Code 1.10.2, I haven't had a chance to check 1.11 yet)

If I open a different folder of javascript/typescript/tsx etc., search works normally, including searching for import with no file types specified, *.ts specified, *.* specified.

If I go back to my original folder (which I've since converted to a VS2015 typescript project because of this issue), searching for the word import in *.ts files or in *.* files returns nothing BUT searching for import with no file qualifier specified returns many hits in .ts files (so search is still broken, but I didn't think to try searching with no file qualifier previously so I don't know if the success searching inside typescript files with no file qualifier is new or not).

**Comment by mjbvz** [comment]
I believe that part about the tsc warning was discussed in #23054. It should be unrelated to the find in files issue, since that does not use the TSServer

**Comment by roblourens** [comment]
@yoDon Have you checked out 1.11? It went out this week.

**Comment by yoDon** [comment]
@roblourens running 1.11 seems to fix my issue, should be ok to close
