### ISSUE TITLE
dotnet watch run --project <PATH> Can't Work

### ISSUE THREAD

**Issue by Bruce-TC** [microsoft/vscode#227053]
![Snipaste_2024-08-29_16-58-41](https://github.com/user-attachments/assets/ecd71298-536b-40ae-b84e-38d34779ae64)
Type: <b>Bug</b>

當我的資料夾裡有兩個(或以上?) .sln 檔，即使使用 --project <PATH> 指定檔案 dotnet watch run 也無法啟動。
同時有 .proj 檔與 .sln 檔即使我使用' dotnet watch run --project "D:\Project\新增資料夾\EywaLink.BlazorServer\EywaLink.BlazorServer\EywaLink.BlazorServer.csproj" '也一樣不能啟動。
當我刪除 .sln 檔之後，兩個指令就都可以使用，我懷疑是 --project <PATH> 沒有作用。

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.69GB (8.41GB free)|
|Process Argv|D:\\Project\\新增資料夾 --crash-reporter-id f92bb99a-043b-4666-8f7c-f322cd01abaf --crash-reporter-id f92bb99a-043b-4666-8f7c-f322cd01abaf --crash-reporter-id f92bb99a-043b-4666-8f7c-f322cd01abaf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hant|MS-|1.92.2024081409
csdevkit|ms-|1.9.55
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.5
vscodeintellicode-csharp|ms-|2.1.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-t:31125599
autoexpandse:31127268
ei213698:31121563
aajjf12562cf:31125794

```

</details>

**Comment by roblourens** [comment]
You can file an issue on dotnet for this
