### ISSUE TITLE
Use a stable sort when sorting Edits

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/vscode#22703]
There was a conversation on how to insert multiple text changes that all have the same starting position over in https://github.com/Microsoft/TypeScript/pull/14441. To specify the order explicitly, we thought the ordering of edits in a change should work as a tiebreakers (ie: use a stable sort when ordering the edits).

Can the vscode side respect this property when applying changes? After a bit of debugging, it looks like the necessary change would be to replace https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/bulkEdit.ts#L98 with a stable sort.

I would put up a PR except that I was unable to find an existing stable sort and I'm unsure if there's some pattern you'd prefer to use for an implementation.

If it helps, I'll later edit this with an explicit repro (the case I'm running into is currently dependent on a change I've yet to merge into https://github.com/Microsoft/TypeScript).

**Comment by vladima** [comment]
Alternatively we can collapse such edits into one textchange on our side - this way editors won't have to add any special handling to this pretty ambiguous case

**Comment by aozgaa** [comment]
We will be merging edits starting at the same position for codefixes as a result of work in https://github.com/Microsoft/TypeScript/pull/14709, so this issue is non-essential for us now.

**Comment by alexandrudima** [comment]
Edits are already sorted before being applied. Ambiguous edits (i.e. inserting at the same exact position) will be executed in the order that they come in.

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/model/editableTextModel.ts#L258

```
	private static _sortOpsAscending(a: IValidatedEditOperation, b: IValidatedEditOperation): number {
		let r = Range.compareRangesUsingEnds(a.range, b.range);
		if (r === 0) {
			return a.sortIndex - b.sortIndex;
		}
		return r;
	}
```

**Comment by aozgaa** [comment]
We observed that if we have a number of ambiguous insertions in an edit, the ordering get's mixed up by the unstable sort at https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/bulkEdit.ts#L98

That said, we solved the issue by collapsing multiple `TextChange`'s down to one `TextChange`, per https://github.com/Microsoft/TypeScript/blob/master/src/services/codefixes/helpers.ts#L19.

So, we don't depend on the aforementioned sort being stable.

**Comment by alexandrudima** [comment]
Thanks for the explanation, wasn't aware of that sort or I forgot about it :) Will look together with @jrieken into it...

**Comment by chrmarti** [comment]
Fix looks good, could not reproduce the original issue in 1.11.2, still marking verified.
