### ISSUE TITLE
Type to Search Across Lists

### ISSUE THREAD

**Issue by trevrobwhite** [microsoft/vscode#227067]
Coming from the Jetbrains platform one feature I really miss is the ability to be able to type in lists for example workspace, database etc and the system will automatically jump you to the first matching item in that list, then use the up/down arrows to move through the selections, filtering would also be acceptable (maybe that's an option).

I realise there is the global search, but this is much faster when you are looking for a table, view or a file.

Many thanks

**Comment by gjsjohnmurray** [comment]
Many lists support this but you first have to type Ctrl+Alt+F to activate the widget.

**Comment by trevrobwhite** [comment]
![image](https://github.com/user-attachments/assets/9f53849c-e48c-459e-abed-38ca77d6531e)

Anywhere there is a list, click an item and start typing a magnifying glass appears and the list filters as you type, if nothing is found it turns red, backspace works and escape clears the filter.  It's a global action so works with every list, it means you can find things really quickly without opening another editor

**Comment by andreamah** [comment]
Oh. Then yes, the comment above is correct: 

> Many lists support this but you first have to type Ctrl+Alt+F to activate the widget.

**Comment by trevrobwhite** [comment]
CTRL+ALT+F yes that's the one thanks, much better than CTRL+SHIFT+F, thanks :-)
