### ISSUE TITLE
Editor Hover: Hiding Delay without effect

### ISSUE THREAD

**Issue by zzador** [microsoft/vscode#227064]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.1
- OS Version: Windows 10

Steps to Reproduce:

1. Set the Editor Hover: Delay to 2000ms
1. Set the Editor Hover: Hiding Delay to 1 ms
2. Hover with mouse over a function or variable and wait for popup hints to show
3. Move mouse away from function or variable -> popup hint stays visible for 2000ms as specified in "Editor Hover: Delay" and not like in "Editor Hover: Hiding delay".

**Comment by gjsjohnmurray** [comment]
/duplicate

Fixed by #225687 in upcoming 1.93
