### ISSUE TITLE
Dialog with command line hist0ry

### ISSUE THREAD

**Issue by steveareeno** [microsoft/vscode#227074]
I would like a keyboard shortcut for the terminal that would allow you to pull up a dialog with a history of command lines you have entered. Kind of like using the arrow key pulls up you last commands, only in a window where you can scroll and select a command.

**Comment by roblourens** [comment]
You're gonna love the command "Terminal: Run Recent Command"

**Comment by legomushroom** [comment]
@steveareeno the `Terminal: Run Recent Command` seems to be what you want (it also has a shortcut, e.g. `ctrl+option+R` on mac). Please reopen if you meant something different.
