### ISSUE TITLE
Unable to scroll on vscode.dev terminal

### ISSUE THREAD

**Issue by jiwonz** [microsoft/vscode#227033]
Terminal is not scrollable in chrome vscode

Repro: Open remote tunnel and open terminal then try to swipe terminal

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by meganrogge** [comment]
a gif would help, also, could you try the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by jiwonz** [comment]
> a gif would help, also, could you try the [Insiders build](https://code.visualstudio.com/insiders)? /label info-needed

Hello, thanks for replying! Here is the video (vscode.dev)
https://github.com/user-attachments/assets/dfa0a43f-c087-4bee-8825-6553e50dd3ae

I'm not in an environment to use vscode insiders so I will try it later.

**Comment by meganrogge** [comment]
Thanks for the gif. Looks very odd. Can you pls let me know if it reproduces in insiders?
