### ISSUE TITLE
[bug] Fold code is the wrong implementation

### ISSUE THREAD

**Issue by ZSkycat** [Microsoft/vscode#22714]
- VSCode Version: 1.10.2
- OS Version: Windows10

Steps to Reproduce:
1.write code in js file
``` javescript
function abc() {
    var see;
    var bug2;
    var bug = `testtest
I can Cross line`;
}
```
2. folded “function abc()”
result:
![qq 20170316110829](https://cloud.githubusercontent.com/assets/20368649/23980129/e48e2172-0a38-11e7-8f81-f31f813729da.png)
expected (visual studio 2015):
![qq 20170316111142](https://cloud.githubusercontent.com/assets/20368649/23980218/5a7650bc-0a39-11e7-8795-1d30260ea9b8.png)

- then I find ...
please notice the first space

``` javescript
function abc() {
    var see;
    var bug2;
    var bug = `testtest
 I can Cross line`;
}
```
result:
![qq 20170316112152](https://cloud.githubusercontent.com/assets/20368649/23980501/e08b1a92-0a3a-11e7-9ef6-53b56c85b45b.png)

``` javescript
function abc() {
    var see;
var bug2;
    var bug = `testtest
I can Cross line`;
}
```
result:
![qq 20170316112527](https://cloud.githubusercontent.com/assets/20368649/23980549/439c748c-0a3b-11e7-81cd-4e7c64fe04bb.png)
![qq 20170316112551](https://cloud.githubusercontent.com/assets/20368649/23980566/524ed54c-0a3b-11e7-9e55-35a21b4e9cce.png)

``` javescript
function abc() {
    var see;
    var bug2;
    var bug = `testtest
    I can Cross line`;
 }

 var config = {
    see: 0,
};
```
result:
![qq 20170316112822](https://cloud.githubusercontent.com/assets/20368649/23980615/abcbd70a-0a3b-11e7-819c-0063debccb33.png)

- other file also
``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
 </head>
 <body>
    
 </body>
</html>
```
result:
![qq 20170316113149](https://cloud.githubusercontent.com/assets/20368649/23980679/2bf49cb4-0a3c-11e7-9b8c-220791fdcd73.png)
![20170316113216](https://cloud.githubusercontent.com/assets/20368649/23980871/860f65e8-0a3d-11e7-9b44-3abaa9b5a615.png)
expected (visual studio 2015):
![qq 20170316113659](https://cloud.githubusercontent.com/assets/20368649/23980870/81e6faee-0a3d-11e7-8861-fae3a22e7436.png)

- it seems only to determine whether the first character is a space

**Comment by kumarharsh** [comment]
+1. I don't use this feature, but I've observed similar bugs with code-folding. The scope of the code block doesn't seem to be respected, instead the feature seems to rely on the indentation of code.

**Comment by weinand** [comment]
Correct, code folding is based on indentation.

**Comment by aeschli** [comment]
#3422 is the request to enable language based folding.
