### ISSUE TITLE
Notebooks do not offer conflict resolution on save, whereas regular files do, despite notebooks also supporting diffs.

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#227198]
If you have a file conflict on save, with a regular file you get the message:
> Failed to save '{0}': The content of the file is newer. Please compare your version with the file contents or overwrite the content of the file with your changes.
> `Compare` `Overwrite`

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/browser/editors/textFileSaveErrorHandler.ts#L127

Whereas with a Notebook you get the similar message, but without the option to view the diff:
> Failed to save '{0}': The content of the file is newer. Do you want to overwrite the file with your changes?
> `Overwrite` `Discard`

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts#L1143

Given that Notebooks do support side by side diffs, should this prompt now be updated to show the same message for Notebooks as it does for text files and offer resolution via a diff editor?

**Comment by rebornix** [comment]
This makes good sense to me, thanks for the suggestion!

**Comment by bpasero** [comment]
This needs to be implemented per working copy owner I would think, i.e. the `storedFileWorkingCopy` delegates to a handler that implements this flow. I don't think this can be implemented in a generic way because it needs to open working copy specific editors.

Happy to review a PR in this area 👍

**Comment by DonJayamanne** [comment]
This issue hasn't had enough upvotes hence closing this issue.
