### ISSUE TITLE
Apply in Editor should get its own distinct icon

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#227151]
The sparkle icon is not suggestive of what it does:

![Image](https://github.com/user-attachments/assets/9b63acec-2aea-4f4d-98dd-c6dd5d6db1ac)

**Comment by daviddossett** [comment]
Replaced

![Image](https://github.com/user-attachments/assets/e1bc5eaf-8194-4b13-bcd4-7f70fa14b7c3)
