### ISSUE TITLE
Allow toggling `editor.experimental.preferTreeSitter` at runtime

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#227141]
Currently:

- If it's disabled and I enable it, nothing changes. I must reload the window.
- If it's enabled and I disable it, all colors are gone. Enabling it back again does nothing. I must reload the window.

Let's make this setting work dynamically at runtime, so ease experimentation.

---

Bonus: remove the `experimental` from the setting name. Related: https://github.com/microsoft/vscode/issues/227140

**Comment by alexr00** [comment]
> If it's disabled and I enable it, nothing changes. I must reload the window.

This should already be working, and I do see it working.

> If it's enabled and I disable it, all colors are gone. Enabling it back again does nothing. I must reload the window.

The colors being gone is not related to disabling it, it's actually still running but you've hit the bug where the tree is getting messed up. I removed disabling without reload as part of some structural changes. I'll see if it can be re-added.

**Comment by bpasero** [comment]
I am not sure this works, is it `editor.experimental.treeSitterTelemetry` setting?

**Comment by bpasero** [comment]
Looks like I need this:

```
"editor.experimental.preferTreeSitter": [
    "typescript"
  ],
```

**Comment by alexr00** [comment]
Was just adding steps, yes that's it. Thanks for verifying!

**Comment by heartacker** [comment]
@alexr00 Can I ask what languages treesister supports now? Or can only support typescript

**Comment by alexr00** [comment]
Just typescript, and it's a work in progress: it is not yet performant, we don't support injected languages, and its missing a lot of the tricks we do to make syntax highlighting for the viewport fast. We're starting with typescript for selfhosting purposes.
