### ISSUE TITLE
Allow to Format Only Changed Lines

### ISSUE THREAD

**Issue by abhijit-chikane** [microsoft/vscode#227128]
Problem:

Currently, when I make changes to a document and save it, VSCode formats the entire document. This behavior alters the line blame in Git, attributing more changes to my name than I actually made, which is concerning.

Request:

It would be highly beneficial if VSCode could provide an option to format only the lines that have been changed, rather than the entire document. This would help maintain accurate Git blame history and avoid unnecessary formatting changes across the document.

**Comment by lszomoru** [comment]
You can already do that using the `"editor.formatOnSaveMode": "modifications"` setting.

**Comment by abhijit-chikane** [comment]
I didn’t know that
Thanks👍
