### ISSUE TITLE
Moving text cursor cause an incorrect position in Chinese

### ISSUE THREAD

**Issue by ikatyang** [Microsoft/vscode#22717]
- VSCode Version: 1.10.2
- OS Version: win7 & win10

Steps to Reproduce:

1. Press up arrow key :arrow_up:
2. Press down arrow key :arrow_down:

![vscode-text-cursor](https://cloud.githubusercontent.com/assets/8341033/23981715/ad047714-0a43-11e7-896f-99b8ff096c64.gif)

Chinese characters are actually 2-char width in monospace-font.

Test font:  文泉驛等寬正黑 ( download: [wqy-zenhei.zip](https://github.com/Microsoft/vscode/files/846682/wqy-zenhei.zip), this is an open-source font )

Test config `settings.json`
```json
{
  "editor.fontFamily": "文泉驛等寬正黑"
}
```

Test case
```
一二三四五六七八九十
12345678901234567890
一二三四五六七八九十
12345678901234567890
一二三四五六七八九十
12345678901234567890
一二三四五六七八九十
12345678901234567890
一二三四五六七八九十
12345678901234567890
一二三四五六七八九十
12345678901234567890
一二三四五六七八九十
12345678901234567890
一二三四五六七八九十
12345678901234567890
一二三四五六七八九十
12345678901234567890
```

**Comment by alexandrudima** [comment]
Related - #22832

**Comment by wangweixuan** [comment]
Related #9989.

**Comment by alexandrudima** [comment]
To the verifier:
* make sure you have a font where a wide CJK character is painted with the widht of 2 latin characters. e.g. `Inconsolata`
* please also check the steps in https://github.com/Microsoft/vscode/issues/9989#issue-168500904

**Comment by alexandrudima** [comment]
Fixed by PR #44259

**Comment by octref** [comment]
@alexandrudima https://github.com/Microsoft/vscode/issues/44878

**Comment by alexandrudima** [comment]
@octref Thank you for verifying, but I believe you have attempted to verify in a build that did not contain the fix (i.e. the behaviour you describe sounds a lot like what is on stable):

![kapture 2018-03-02 at 9 32 29](https://user-images.githubusercontent.com/5047891/36890024-b1a55c2a-1dfc-11e8-9512-22db1ec556c8.gif)
