### ISSUE TITLE
> @js-writer, are you able to reproduce the same behaviour using [VS Code Insiders](https://code.visualstudio.com/insiders/)?

### ISSUE THREAD

**Issue by atarng-magicleap** [microsoft/vscode#227148]
> @js-writer, are you able to reproduce the same behaviour using [VS Code Insiders](https://code.visualstudio.com/insiders/)?

VS code insiders seems to work for me and it is my new default version.

_Originally posted by @VedAustin in https://github.com/microsoft/vscode/issues/171923#issuecomment-1407012299_
            
            
Just encountered the same issue with vscode unable to load a specific repository, where code-insiders was able to resolve the issue.

**Comment by mjbvz** [comment]
Please file a proper issue report if this is an actual problem because this looks like spam right now
