### ISSUE TITLE
Native crash on Fedora 40

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#227113]
When reloading the window, I experienced a crash: [crash-report.zip](https://github.com/user-attachments/files/16802525/crash-report.zip)

(Happened fairly consistently, maybe 1/10 times)

```
1.93.0-insider
ae45c9d4b0f71d53151edc6d18be09107903c229
x64
```

```
     Static hostname: (unset)
  Transient hostname: fedora
           Icon name: computer-vm
             Chassis: vm 🖴
          Machine ID: b70c67d428e34cf7b4249fb6a7037265
             Boot ID: 1c78151e925c4625a09c3833e9c07af9
      Virtualization: microsoft
    Operating System: Fedora Linux 40 (Workstation Edition)
         CPE OS Name: cpe:/o:fedoraproject:fedora:40
      OS Support End: Tue 2025-05-13
OS Support Remaining: 8month 1w 5d
              Kernel: Linux 6.9.5-200.fc40.x86_64
        Architecture: x86-64
     Hardware Vendor: Microsoft Corporation
      Hardware Model: Virtual Machine
    Firmware Version: Hyper-V UEFI Release v4.1
       Firmware Date: Wed 2022-04-06
        Firmware Age: 2y 4month 3w 3d
```

**Comment by rzhao271** [comment]
@connor4312 do you still see the issue on the latest VS Code Insiders? I have symbolicated the crash dumps in the meantime and they all seem to have the same stacktrace.

[symbolicated-27.log](https://github.com/user-attachments/files/17579275/symbolicated-27.log)
[symbolicated-8e.log](https://github.com/user-attachments/files/17579273/symbolicated-8e.log)
[symbolicated-90.log](https://github.com/user-attachments/files/17579274/symbolicated-90.log)

**Comment by connor4312** [comment]
I don't repro this on the latest Insiders

**Comment by rzhao271** [comment]
Closing the issue. CC @deepak1556 for the potentially outdated symbolicated stack traces above.
