### ISSUE TITLE
[SCM] Ability to edit while commit is in process is misleading

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#22718]
*This issue is very noticeable if you have git hooks which take a little time to execute*

- VSCode Version: 1.11-insider
- OS Version: Win10

Steps to Reproduce:

1. Stage some files, make a commit
2. While the commit is in progress, the commit message text box is enabled, which allows me to change the message - but this message doesn't get committed.
3. While the commit is in progress, I can change the staged files (add/remove more files), which do get committed.

Now, I'm not sure exactly what the *intended* behaviour is, but as I see it:
1. The message should not be editable, or if it is editable, the final message should be applied to the commit.
2. The staged file list should not be editable, because if it is, then there is a problem since the list of files passed to the pre-commit hook, and the list of files committed can be different. This can cause potential bugs in projects if they rely on commit-hook to be a source of truth.

For a reference, Git-GUI disables any action while a commit is in progress.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
