### ISSUE TITLE
Debugging the extension host does not load source maps for the core code

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#227165]
* open `Developer: Show Running Extensions`
* press the play button to begin debugging the extension host
* observe that the source map does not work
* I can't see any hints, also tried it with chrome's inspect but that also shows an error

![Image](https://github.com/user-attachments/assets/54b6915d-6f16-433f-a798-7892f2972475)

**Comment by joshspicer** [comment]
Source map from the main.vscode-cdn.net is now present.  

Note: Source maps for extensions outside of core code (see `Debug Console`) are not present, but I don't believe that is relevant to this issue or necessarily expected

![Image](https://github.com/user-attachments/assets/71b5ee39-5edd-4443-b59b-b87487df3456)
