### ISSUE TITLE
"Language-specific workspace settings" does not override "Language-specific user settings"

### ISSUE THREAD

**Issue by nabe1653** [microsoft/vscode#227180]
Type: <b>Bug</b>

I'd like to use defaultFormatter with biome extention for some TypeScript workspace that has biome. But workspace setting does not override user setting.

I have user setting like below:

```jsonc
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.tabSize": 2,
    },
```

I set workspace setting like below:

```jsonc
  "[javascript][typescript][svelte]": {
    "editor.tabSize": 2,
    "editor.insertSpaces": true,
    "editor.defaultFormatter": "biomejs.biome"
  },
```

If I remove the defaultFormatter line in user setting, vscode uses workspace's setting so those have correct values.

Document said "Language-specific workspace settings" is stronger than "Language-specific user settings": https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence

Thank you.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (13.83GB free)|
|Process Argv|--crash-reporter-id ca2a1b94-1896-42fa-87dc-e58738a43fa3|
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by nabe1653** [comment]
And... now I tried to set workspace like below, then it works.

```jsonc
  "[typescript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[javascript][svelte]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
```

So it may have some problem about language listing.

**Comment by rzhao271** [comment]
The behaviour is documented in the section below your link https://code.visualstudio.com/docs/getstarted/settings#_note-about-multiple-language-specific-settings.

**Comment by nabe1653** [comment]
Oh, So sorry about I've not read the document completely.
I will use only single language format, Thank you for replying.
