### ISSUE TITLE
Window stops responding after switching to Remote Explorer

### ISSUE THREAD

**Issue by arka003** [microsoft/vscode#227182]
![Screenshot from 2024-08-30 12-51-21](https://github.com/user-attachments/assets/ea280c6f-7f64-4c82-89c8-7b4d705d24b5)

Does this issue occur when all extensions are disabled?: No (Since it disables the remote explorer option)

- VS Code Version: 1.92.2 (.deb)
- OS Version: Ubuntu 24.04 (kernel 6.8.0-41-generic)

- Extensions Installed: C/C++, Code Runner, Debugger for Java, Dev Containers, Extension Pack for Java, Gradle for Java, IntelliCode, IntelliCode API Usage Examples, Language Support for Java(TM) by Red Hat, Maven for Java, Project Manager for Java, Remote - SSH, Remote - SSH: Editing Configuration Files, Remote - Tunnels, Remote Development, Remote Explorer, Test Runner for Java, Vim, WSL

Steps to Reproduce:

1. Open VS Code, install Remote Development Extension pack
2.  Switch to Remote Explorer in the Activity Bar

I've tried running  `code --crash-reporter-directory <absolute-path>` but no *.dmp file gets created in the absolute path I provided.
The same crash happens with code-insiders too.

**Comment by alexr00** [comment]
Can you use extension bisect per https://github.com/microsoft/vscode/issues/227182#issuecomment-2322135436 to see which one is the problem?
