### ISSUE TITLE
make terminal selection automatically focus on selected terminal after selection

### ISSUE THREAD

**Issue by yifan** [microsoft/vscode#227183]
There are certain panes in workspace layout does not keep to retrain focus, one of them is terminal selection. When I do things in a hurry, I may click on a terminal, to expect the focus is on associated terminal window, not the selection pane.
![Screenshot 2024-08-30 at 11 10 15 AM](https://github.com/user-attachments/assets/6489f468-228a-41f8-a3c2-9acf95aa46e9)

What actually happens is that when I click on a terminal name, the focus is on the selection pane, I have to click on terminal window itself to start use keyboard to write command.

**Comment by gjsjohnmurray** [comment]
Did you experiment with the `terminal.integrated.tabs.focusMode` setting?

**Comment by legomushroom** [comment]
Hi @yifan, you can set the `terminal.integrated.tabs.focusMode` to `singleClick` to achieve the desired behaviour (it is set to `doubleClick` by default). Hope that helps 🤗
