### ISSUE TITLE
When editing PHP files, it is no longer possible to expand abbreviations using emmet.

### ISSUE THREAD

**Issue by mu60** [microsoft/vscode#227194]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version: Linux x64 6.6.46-1-MANJARO

Steps to Reproduce:

~~~
<p></p>

p

<?php echo str_replace('<a href=', '<', $prev_link); ?>
~~~

If you place the cursor after the p on line 3 of the above code and press the tab key, it should normally be converted to \<p\>\<\/p\>, but nothing happens now.
If you delete the equal sign from the first argument of str_replace on line 5, or the inequality sign from the second argument, emmet is now able to run.
I don't understand why the code on line 5 is causing an emmet error.
Also, although I entered the p tag as an example this time, it does not run with other tags either.

**Comment by rzhao271** [comment]
The inline HTML-like fragments are likely confusing the current HTML parser that we use with Emmet. This is one of those issues that I suspect a polyglot parser would fix.

Closing as a duplicate or another example of https://github.com/microsoft/vscode/issues/129529.
