### ISSUE TITLE
Sticky Code Cells

### ISSUE THREAD

**Issue by Ayman250** [microsoft/vscode#227125]
After a bit of searching I can't seem to find a way to do this. Similar to sticky scroll for headers in MD cells, I'd like a way to sticky code cells so that they can be easily viewed/run. Is there already a way to achieve this or something similar?

**Comment by rebornix** [comment]
@Ayman250 can you elaborate this a bit more? I'm not sure what "sticky code cell" means. In markdown we make headers sticky so you can quickly navigate to the beginning of the section, but code cells are usually "leaf" nodes in a notebook document.
