### ISSUE TITLE
Integrated terminal in separate window

### ISSUE THREAD

**Issue by ProbabilisticS** [microsoft/vscode#227188]
I'd like to have the integrated terminal in fullscreen mode on my laptop screen next to my desktop monitors.

* It is possible to use an external terminal, but all features of the intergrated terminal would be lost (notably file links).
* It is possible to manually resize the vscode window to extend beyond the bounds of one monitor, but it would require a lot of tinkering with tab/window placement, and the end result would still not compare to a fullscreen terminal.
* It is possible to duplicate the vscode window, but file links would open in the same window as the terminal.

A dock/undock feature or similar would be greatly appreciated.

**Comment by gjsjohnmurray** [comment]
There's a tip in https://github.com/microsoft/vscode/issues/193267#issuecomment-2148129764

**Comment by bpasero** [comment]
You can open a terminal as editor in the editor area and then drag that editor out into a separate window, can you try?

**Comment by ProbabilisticS** [comment]
@bpasero @gjsjohnmurray Thank you for input. I've tested it and it works as advertised 👍 I would still prefer a cleaner solution where nothing but the terminal area is shown on screen, but I like it overall.
