### ISSUE TITLE
SQL format Not Highlighting "qualify" Statement

### ISSUE THREAD

**Issue by miiguelkf** [microsoft/vscode#227172]
VSCode is not highlighting the "qualify" statement as shown in the screenshot below.

I have been using this statement for a while. At first I tought it would get implemented, as it is an slightly new command.
But it has been almost an year and nothing changed.

![image](https://github.com/user-attachments/assets/25bcb38f-f469-4991-933d-e45e390e1e14)

```[tasklist]
### Tasks
```

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/132944#issuecomment-924015144 may be relevant.

**Comment by alexr00** [comment]
As far as I can tell, `qualify` isn't part of T-SQL/MS SQL. You could find another SQL extension that supports something other than T-SQL/MS SQL.
