### ISSUE TITLE
Unable to rename folders

### ISSUE THREAD

**Issue by nagarajkyatari** [microsoft/vscode#227298]
Type: <b>Performance Issue</b>

I have copied a folder in VS code and tried to rename it but it was stuck at renaming, operation was not completing, as checked that folder was not opened anywhere else, i needed to close and open vs code to make it complete. Kindly let me know if im doing any wrong here

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i3-1125G4 @ 2.00GHz (8 x 1997)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.75GB (1.00GB free)|
|Process Argv|--crash-reporter-id b9ee5d60-483d-46e4-85fe-ebe21844852e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    98	 17448	code main
    0	   185	  1352	extensionHost [1]
    0	   105	  1648	     "C:\Users\nagar\AppData\Local\Programs\Microsoft VS Code\Code.exe" c:\Users\nagar\.vscode\extensions\streetsidesoftware.code-spell-checker-3.0.1\packages\_server\dist\main.cjs --node-ipc --clientProcessId=1352
    0	    87	 11604	     electron-nodejs (serverMain.js )
    0	    96	  3120	fileWatcher [1]
    2	    99	 10512	window [2] (Issue Reporter)
    0	    38	 17432	ptyHost
    0	    24	 17556	   crashpad-handler
    0	   152	 17644	   gpu-process
    0	    30	 17672	   utility-network-service
    0	   159	 17840	window [1] (Welcome - JavaScript - Visual Studio Code)
    0	    69	 18096	shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - JavaScript - Visual Studio Code)
|    Folder (JavaScript): 735 files
|      File types: js(191) html(181) png(41) css(25) svg(5) pdf(2) json(1)
|                  zip(1) txt(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
blackbox|Bla|1.3.92
doxdocgen|csc|1.4.0
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
c-cpp-runner|fra|9.4.9
blender-development|Jac|0.0.21
better-cpp-syntax|jef|1.27.1
git-graph|mhu|1.30.0
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
jupyter|ms-|2024.7.0
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.2
cmake-tools|ms-|1.19.49
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.14
java|red|1.34.0
LiveServer|rit|5.7.9
code-spell-checker|str|3.0.1
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-icons|vsc|12.8.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562cf:31125794

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
