### ISSUE TITLE
Initializing TS/JS features crashing and Code Helper (Plugin) consuming >4GB memory with no extensions

### ISSUE THREAD

**Issue by glemin5011** [microsoft/vscode#227228]
Type: <b>Performance Issue</b>

Recently, I have been having major performance issues with VS Code running a small-size Typescript project. This is probably also related to issue #225421. 

I noticed that the Code - Helper (Plugin) process was consuming a lot of memory and I assumed this was due to extensions. I did the following:

- I tried to run my current VS Code installation with no extensions on - no change
- I did a clean reinstall of my VS Code installation, did not install any extensions - no change
- I installed the latest Code Insiders build with no extensions turned on - no change

Is this an expected level of performance? I did not have these issues a couple of ~~months~~ weeks ago (I am unable to pinpoint when exactly this became a noticable issue). 

Maybe this is unrelated, but in about the same time, I started having major issues with running TS on my other machine running WSL2 - i get the `Initalizing JS/TS language features` crashes as referenced in #225651, #225596, #225409, which also leads to a spike in memory consumption.

Screenshot below is from when I opened one TS file from my project after booting my device (running a fresh Code Insiders install with no extensions)

VS Code version: Code - Insiders 1.93.0-insider (Universal) (5b066ec2e30cf46bc636d6d27af5404713f6b0f8, 2024-08-29T17:06:24.451Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|. --crash-reporter-id eec284df-f61a-4fc0-8036-0496e4bfc7ec|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	   115	 70663	code-insiders main
    8	    49	 70666	   gpu-process
    0	    25	 70667	   utility-network-service
   18	    57	 70669	shared-process
    0	     0	 72551	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    33	 70712	ptyHost
    0	     0	 71478	     /bin/zsh -il
   44	   287	 71444	window [2] (ibm-create-service-id-worker.ts — backend)
    1	    33	 71445	extensionHost [2]
    0	    25	 71871	     /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=71445
    0	    33	 72378	     electron-nodejs (tsserver.js )
   97	   385	 72379	     electron-nodejs (tsserver.js )
    0	    25	 72381	       electron-nodejs (typingsInstaller.js typesMap.js )
  240	  1163	 72380	     electron-nodejs (tsserver.js )
    0	    33	 71477	fileWatcher [2]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ibm-create-service-id-worker.ts — backend)
|    Folder (backend): 374 files
|      File types: js(81) zip(80) ts(72) json(17) env(1) example(1) cjs(1)
|                  gitignore(1) npmignore(1) md(1)
|      Conf files: settings.json(1) package.json(1) tsconfig.json(1);
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aa:30263845
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
9c06g630:31013171
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nb_pri_only:31057983
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31111718
nativeloc1:31118317
wkspc-ranged-c:31125598
3ad50483:31111987
jh802675:31111929
e80f6927:31120813
fje88620:31121564
aajjf12562cf:31125794

```

</details>

![VS Code Insiders](https://github.com/user-attachments/assets/7614cbc9-7fc3-4138-afe5-408f98b02343)

**Comment by coluccini** [comment]
I'm experiencing the same thing for the last few days. 
Here are my system info:

VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 3, 3|
|Memory (System)|32.00GB (2.81GB free)|
|Process Argv|--crash-reporter-id f271f496-c531-4402-a1a3-80ebdcdb1e3d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
htmltagwrap|bra|1.0.0
vscode-eslint|dba|3.0.10
vscode-styled-jsx-languageserver|Div|1.3.1
vscode-styled-jsx-syntax|Div|1.3.1
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
code-runner|for|0.12.2
vscode-xml|red|0.27.1
vs-code-prettier-eslint|rve|6.0.0
vscode-input-sequence|tom|0.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-c:31111717
wkspc-ranged-c:31125598
ei213698:31121563
aajjf12562cf:31125794

```

</details>

**Comment by glemin5011** [comment]
Also, it might be worth noting that the same problem occurs in other IDEs - I have the exact same problem with Zed, which also consumes around 4GB memory - I know issues with Zed are not your concern, but I am mentioning it because it made me wonder whether the underlying problem is in the LSP itself, rather than in the IDE  - afaik Zed uses [vtsls](https://github.com/yioneko/vtsls), which if I understand correctly is a wrapper around VSCode's implementation of the LSP

they discuss the issue [here](https://github.com/zed-industries/zed/issues/16430) if interested

**Comment by coluccini** [comment]
I'm still having this issue. I've tried to move to Cursor and I seeing the exact same behaviour.
The only way to keep working is to disabled TS/JS features.

@glemin5011 did you find a solution? maybe is something related to a broken cache or something like that, but anything I've tried has worked :(

**Comment by coluccini** [comment]
For extra info: this is still happening even with all the extensions disabled:

<img width="1090" alt="Screenshot 2024-09-03 at 10 15 20" src="https://github.com/user-attachments/assets/22707656-363a-4267-86cc-e434b9b3f410">

**Comment by mjbvz** [comment]
> Recently, I have been having major performance issues with VS Code running a small-size Typescript project.

Please share an example project which causes this so we can take a look

**Comment by glemin5011** [comment]
I was struggling to find a repo that i could share with you which causes the same behavior, but I took this screenshot when i cloned freeCodeCamp's [repo](https://github.com/freeCodeCamp/freeCodeCamp) just now, which is roughly the same size as my project in terms of Typescript LOC (~60,000 in Typescript and roughly 2GB size repo incl. dependencies installed)

 ![freeCodeCamp](https://github.com/user-attachments/assets/f4d19255-cc48-485f-947f-dd6da7161836)


This is the same version of code insiders with no plugins running - fwiw I don't really experience CPU problems like @coluccini , for me the issue is memory

**Comment by coluccini** [comment]
I have changed the "Tsserver: Max TS Server Memory" setting to 4GB (from 3) and I'm now not seeing the CPU issue, even when the plugin is still using +3GB of RAM. So I guess the issue might be triggered when the plugin reaches the setting limit


<img width="480" alt="Screenshot 2024-09-04 at 18 08 37" src="https://github.com/user-attachments/assets/cbb19481-fe09-4faf-9a58-a9084163c4a0">

**Comment by coluccini** [comment]
A little bit of more context: my projects has "only" 18K files. So, using 3.5GB of RAM seems way too excessive

**Comment by coluccini** [comment]
Update: I just installed the last update and everything seems to be working fine now. The max RAM use by code helper plugin is 700MB, CPU is low and most features that was not working smoothly are now working just fine.

**Comment by glemin5011** [comment]
unfortunately, the update did not change anything for me, which I think is consistent with the fact that I saw this behavior with a fresh Code Insiders installation - anyways, it's possible that my project is just too big for the LSP to work under this level of RAM consumption, i was just surprised by it, because I did not consider it to be a large project

**Comment by coluccini** [comment]
The issue is back 😔 And today a colleague started having the same issue... 
And I'm totally sure that our project is not too big (we are just 4 people and we just have an API and a React App).

It's getting really frustrating as most of the time "go to definition" does not work and finding where everything is is too time consuming. 

<img width="482" alt="Screenshot 2024-09-10 at 17 35 08" src="https://github.com/user-attachments/assets/e9c10475-fb95-4f03-aee4-1526728f05b9">
<img width="451" alt="Screenshot 2024-09-10 at 17 34 55" src="https://github.com/user-attachments/assets/a48e94e0-b970-4c1a-a6ca-47fd9aa4d0c8">

**Comment by glemin5011** [comment]
hey, yeah I am not sure what additional information would be helpful - this is a general performance issue I experienced across devices, platforms (Mac OS / Windows with WSL2) and repositories. FWIW I haven't really had a major problem when working with Swift and its LSP, so that's one of the reasons why I think it might be related to the TS LSP.

**Comment by coluccini** [comment]
The issue is gone for me :)

**Comment by mjbvz** [comment]
Please start by following [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. Thanks!
