### ISSUE TITLE
Mac OS: Cannot select non-contiguous lines of text 

### ISSUE THREAD

**Issue by iAmWillShepherd** [Microsoft/vscode#22726]
Holding down *⌘* while making text selections does not behave as expected. The correct behavior on Mac OS is to select non-contiguous blocks of text.

![vscode](https://cloud.githubusercontent.com/assets/1715082/23985199/b85835b8-09eb-11e7-8475-33a42e0fa9e4.gif)

#### Text Edit (Mac OS default editor)

![textedit](https://cloud.githubusercontent.com/assets/1715082/23985211/c8ca2dc0-09eb-11e7-922a-29af1382fe20.gif)

#### Sublime

![sublime](https://cloud.githubusercontent.com/assets/1715082/23985223/e32bd10a-09eb-11e7-8580-5be9e05b2c85.gif)

#### Atom

![atom](https://cloud.githubusercontent.com/assets/1715082/23985242/eb629458-09eb-11e7-9271-d7fc656421cb.gif)

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|empty-indent|DmitryDorofeev|0.2.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|tslint|eg2|0.8.1|
|vscode-npm|fknop|3.3.0|
|csharp|ms-vscode|1.8.0|
|mono-debug|ms-vscode|0.15.3|
|debugger-for-chrome|msjsdiag|2.6.0|
|indent-rainbow|oderwat|0.4.1|
|vscode-icons|robertohuertasm|7.3.0|
|final-newline|samverschueren|0.3.2|;

---

Steps to Reproduce:

1. Open any file
2. Hold down Command while selecting text with a mouse

**Comment by alexandrudima** [comment]
Please use Alt until #3130 is implemented. Please also feel free to upvote #3130
