### ISSUE TITLE
`Search: Find in files`: order of tab targeting

### ISSUE THREAD

**Issue by mcrampon** [microsoft/vscode#227209]
When using the `Search: Find in files` feature, the order in which elements are targeted by pressing `TAB` is counter-intuitive. It should go through the most useful items first, then go to more and more "advanced" tools.

### Current behavior
![Screenshot 2024-08-30 144846](https://github.com/user-attachments/assets/a5165990-a650-4f2a-9a3f-b831353e1ce5)
![Screenshot 2024-08-30 144852](https://github.com/user-attachments/assets/8de8da33-ad18-4637-9d5a-fc36afb6eb98)
![Screenshot 2024-08-30 144858](https://github.com/user-attachments/assets/55a8d056-3444-44d9-9df2-f01184395376)
![Screenshot 2024-08-30 144904](https://github.com/user-attachments/assets/ab6db345-e427-41a5-9087-4a11c69e34dd)
![Screenshot 2024-08-30 144909](https://github.com/user-attachments/assets/5be7a7b5-4f5f-458d-9ec5-606c64e1144c)

Etc. For reference, before I can access the `files to include` text box, I have to press `TAB` 7 times.

### Desired behavior
![Screenshot 2024-08-30 144846](https://github.com/user-attachments/assets/a5165990-a650-4f2a-9a3f-b831353e1ce5)
![Screenshot 2024-08-30 145100](https://github.com/user-attachments/assets/3d677f8d-5beb-4be7-bae3-3d6a3e84afb7)
![Screenshot 2024-08-30 145242](https://github.com/user-attachments/assets/f430b1a6-036e-488f-a50f-76769406ee27)
![Screenshot 2024-08-30 144852](https://github.com/user-attachments/assets/8de8da33-ad18-4637-9d5a-fc36afb6eb98)

Etc.

**Comment by andreamah** [comment]
Please see the comment here: https://github.com/microsoft/vscode/issues/159880#issuecomment-1247538835

/duplicate https://github.com/microsoft/vscode/issues/159880

**Comment by mcrampon** [comment]
> Please see the comment here: [#159880 (comment)](https://github.com/microsoft/vscode/issues/159880#issuecomment-1247538835)
> 
> /duplicate #159880

You completely misunderstood. I 100% agree with that comment:

> users want to tab to the replace box much more often than they want to tab to those buttons 

However, that is NOT the current behaviour.

**Comment by andreamah** [comment]
For you, is the bug that it is inconsistent?

**Comment by andreamah** [comment]
Taking another look at this, the reason why it's like this is because those are not the replace fields- those are are the 'files to include' and 'files to exclude' fields, which also exist in the search view if you click the `...`. The search editor's behavior would be the same as the search view's behavior if the search view had no replace field.

**Comment by mcrampon** [comment]
> Taking another look at this, the reason why it's like this is because those are not the replace fields- those are are the 'files to include' and 'files to exclude' fields, which also exist in the search view if you click the `...`. The search editor's behavior would be the same as the search view's behavior if the search view had no replace field.

Ah, never knew you could have the include/exclude fields in the replace view. Good to know.

Indeed, there's an inconsistency on a field basis then:


https://github.com/user-attachments/assets/cc7d4747-dcb3-4cd2-82e6-a37d20623b78

**Comment by andreamah** [comment]
There currently is no support for replacing in the search editor, unfortunately. See here: https://github.com/microsoft/vscode/issues/93031

**Comment by mcrampon** [comment]
> There currently is no support for replacing in the search editor, unfortunately. See here: #93031

That is not what I was talking about. I was simply confirming that the order of traversal is inconsistent.
My original point still stands and should also apply to the replace view.

Search view order should be:
- Search
- Include (if displayed)
- Exclude (if displayed)
- Secondary buttons

Replace view order should be:
- Search
- Replace
- Include (if displayed)
- Exclude (if displayed)
- Secondary buttons

**Comment by andreamah** [comment]
We would still want the order to be:
- search
- replace
- secondary buttons
- include
- exclude

Referencing https://github.com/microsoft/vscode/issues/159880#issuecomment-1247538835, the reason why we have the replace as the second tab element is because it's more commonly used than the secondary buttons. Indeed, it's confusing, but seems to work for majority of our users.
