### ISSUE TITLE
[Accessibility] Aria label for Pane header not dynamically updated.

### ISSUE THREAD

**Issue by Krituhar** [microsoft/vscode#227266]
**Desc**: We have contributed our own extensions to VScode's Explorer view container (side bar panel) and the extensions are having their own view containers. In one of the view container, we update the pane header title of the webview in runtime. But the aria-labels are not being dynamically updated to be in accordance with the visual label present. The Pane header is being contributed mainly from extensions's `package.json` but the updated string is being handled in our src code. Also since it's a webview for the particular "Deploy" extension, we don't see `Accessibility Information` property being supported either.

**[Issue]**
The "Deploy Section" accordion control with accessible name that do not include the text of their visual labels.

[**User Impact]**
Speech input users will have difficulty navigating to these controls.

**[Code Reference]**
```
<div class="pane-header" tabindex="0" role="button" aria-label="Deploy Section" aria-expanded="false" draggable="true" (...)>
(...)
</div>
```

**[Recommendation]**
Ensure the visible text label for a control is included in the control's accessible name.

In this case, provide accessible name as "Deploy [Undeployed changes] Section" or similar.

**[Compliant Code Example]**
```
<div class="pane-header" tabindex="0" role="button" aria-label="Deploy [Undeployed changes] Section" aria-expanded="false" draggable="true" (...)>
(...)
</div>
```

**Comment by meganrogge** [comment]
Thanks for the issue - this is so niche that I am closing as I don't think we'll get to it any time soon. I also think the number of users impacted by this will be miniscule.
