### ISSUE TITLE
feature request: when focus in the file explorer, press a-z to navagate to the file like in windows file explorer

### ISSUE THREAD

**Issue by metasong** [Microsoft/vscode#22721]
![ds](https://cloud.githubusercontent.com/assets/5009757/23983556/bb895708-0a4f-11e7-9783-994b403f156b.gif)

if press r it will select runOrSwitch.ahk, then press t, the test.ahk will be selected again, and press t again, the test.ahk.back will be selected.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
