### ISSUE TITLE
Testing via editor doesn't run tests inside terminalEnvironment.test

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#227222]
Guessing this is because of the conditionals? It detects them fine, but doesn't run. They run fine if I add `.only` to the suite and `./scripts/test`

https://github.com/microsoft/vscode/blob/fb8d82e29ba0b8663287389a8ebbd5ad796d3daf/src/vs/platform/terminal/test/node/terminalEnvironment.test.ts#L52

![image](https://github.com/user-attachments/assets/712110af-42e5-4b0b-8f21-ec8d625c24dd)

**Comment by connor4312** [comment]
Yes, we use an [AST parser](https://github.com/microsoft/vscode/blob/7806baa56d84e413dccb83d9fc0efbbd66d2c766/.vscode/extensions/vscode-selfhost-test-provider/src/sourceUtils.ts#L17) to extract tests from files. It doesn't doing any evaluation. Not sure that I want to open that can of worms 😛

**Comment by Tyriar** [comment]
@connor4312 but it detects the tests as seen on the left side, so why isn't it able to run it if it knows the test name?

**Comment by connor4312** [comment]
The identity of a test is formed by joining the containing file name and its name with the path of containing suites' names. It detects the suite `should override args` but it does not recognize that it's a child of `pwsh`. When tests are run it's expecting updates to a test named `platform - terminalEnvironment getShellIntergation should override args`, but it doesn't get that so it's marked as skipped.

**Comment by Tyriar** [comment]
I clicked run on `platform - terminalEnvironment` though, so can't we run everything matching `platform - terminalEnvironment.*` in that case?

**Comment by connor4312** [comment]
It does run everything, and you should see that in the output, but it doesn't associate the results with the tests.

It expects to get results for `platform - terminalEnvironment getShellIntergation should override args` but it actually gets `platform - terminalEnvironment getShellIntergation **pwsh** should override args`, which is not a path to any test the extension knows about.

**Comment by Tyriar** [comment]
Could we be a little smarter in matching these up if there's a simple 1:1 match up? Like checking that expected items have matching prefixes and suffixes and there's no ambiguity? I don't expect this to work if we're generating tests with a loop (though that would be nice), if we can exactly match up the amount of tests to that expected then it should be safe?

**Comment by connor4312** [comment]
Eh, I'll just add some logic to identify simple ternary expressions like these
