### ISSUE TITLE
VS Code Shows an Error Where There Is None

### ISSUE THREAD

**Issue by chirva-sf** [microsoft/vscode#227277]
Type: <b>Bug</b>

I have a simple code snippet saved in a file:
```
<?php
class User {
  public int $id;
}
```
In this code, VS Code highlights the line "public int $id;" in red and, when hovering, shows the error "syntax error, unexpected 'int' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)."
But in fact, there is no mistake!

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19043
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2130 @ 3.20GHz (2 x 3203)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.96GB (3.10GB free)|
|Process Argv|--crash-reporter-id 68b14b8e-5c88-4d7f-a3c3-16c050125fcb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|8.5.0
smarty-template-support|asw|2.1.1
vscode-intelephense-client|bme|1.12.5
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
macros|ged|1.2.1
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
twig-code-snippets|nad|2.0.0
subtle-brackets|raf|3.0.0
autoclose-find|tyg|1.0.0
vscode-icons|vsc|12.8.0
php-debug|xde|1.35.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562cf:31125794

```

</details>

**Comment by roblourens** [comment]
It looks like you have the php intelephense extension installed, is this from that?

**Comment by chirva-sf** [comment]
Yes, the PHP Intelephense extension is installed, but it's not the cause, as I tried disabling it and even uninstalling it. I also disabled all other extensions, but the issue with the error highlighting persists.

Take a look at the screenshot below: I removed the PHP Intelephense extension and disabled the others, but VS Code still highlights the line

![image](https://github.com/user-attachments/assets/c95a8881-bc9a-4585-8831-d151d32ed242)

**Comment by roblourens** [comment]
Ok, then it's probably from our builtin PHP validation, which is pretty basic. If you are using a PHP extension, I recommend disabling it by disabling `php.validate.enable`. 

If you want to use the builtin validation, maybe it's picking up an old version of `php` on your PATH, or you have `php.validate.executablePath` set to the wrong thing?

**Comment by chirva-sf** [comment]
Yes, you were absolutely right. My php.validate.executablePath was indeed pointing to a rather old version of PHP. I changed it to the path for the latest PHP version, and now everything works perfectly. Thank you so much for your help!
