### ISSUE TITLE
Does not open after updating MacOS

### ISSUE THREAD

**Issue by tylerlaprade** [microsoft/vscode#227227]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: Latest
- OS Version: Sonoma 14.6.1

Steps to Reproduce:

1. Restart MacBook Pro to update to Sonoma 14.6.1 while VSCode has a workspace open
2. Try to open VSCode
3. Infinite loop of one of these, regardless of which option I pick:
<img width="401" alt="image" src="https://github.com/user-attachments/assets/d2c9c746-8071-4b85-8d9f-ba01c12842d8">
<img width="399" alt="image" src="https://github.com/user-attachments/assets/c622ca75-2535-4c3f-b03c-583815c1fc57">

**Comment by tylerlaprade** [comment]
I deleted everything in `/Users/tyler/Library/Application Support/Code`, still the same error

**Comment by tylerlaprade** [comment]
I ended up uninstalling and reinstalling because nothing else was working

**Comment by deepak1556** [comment]
If the issue still persists, can you share the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

**Comment by tylerlaprade** [comment]
Thanks @deepak1556. The issue persisted, but I uninstalled and reinstalled to fix it because I was blocked from doing my job, so I can no longer repro.

**Comment by deepak1556** [comment]
Closing based on previous response, can reopen if the issue persists.
