### ISSUE TITLE
Why can't I use the wsl extension after the source code is packaged?

### ISSUE THREAD

**Issue by AlaricWeb** [microsoft/vscode#227294]
![image](https://github.com/user-attachments/assets/6cfa313e-d781-474f-a908-271a71c34fd0)

![image](https://github.com/user-attachments/assets/4be57865-860e-4743-b7e1-9b9ba900b296)

**Comment by AlaricWeb** [comment]
Guys, please help me. The font size of the version released by vscode is too small. I changed the font size and packaged it, but I can't use the wsl extension.

**Comment by aeschli** [comment]
Did you see the last line in the dev tools console?

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/issues/227293#issuecomment-2324870021
