### ISSUE TITLE
SCM Graph View - Polish hover and context menu action

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#227214]
- [x] Create Tag...
- [x] Create Branch...
- [x] Cherry Pick
- [x] Checkout (Detached)

**Comment by sanket-bhalerao** [comment]
@lszomoru , is there a roadmap for the git graph feature to see what might be coming in the future?

* is there a plan to show tags on the commits?
* is there a plan to soft/hard deletes?
