### ISSUE TITLE
The Display Language to receive the wrong values

### ISSUE THREAD

**Issue by roll100** [Microsoft/vscode#22729]
- VSCode Version: 
- OS Version: macOS 10.12.3

Steps to Reproduce:

I write the wrong Display Language ，Caused the vscode cannot be started。So I can't modify it correctly

**Comment by weinand** [comment]
I do not understand what you mean. Please clarify.

**Comment by roll100** [comment]
I write the wrong “locale.json”
The save after unable to open vscode
Delete the code folder to solve the。 thanks

**Comment by dbaeumer** [comment]
You can always pass --locale=xx to override the locale.json. An a broken locale.json will not prevent VS Code to start. Do you still have the broken locale.json so that I can have a look why this is happening?
