### ISSUE TITLE
style features are not working

### ISSUE THREAD

**Issue by sheelamppal** [microsoft/vscode#227286]
Type: <b>Feature Request</b>

<style> and html  color attribute are not working 

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide exact steps to reproduce, expected behaviors and code samples
