### ISSUE TITLE
No Smooth Scrolling via Touchpad

### ISSUE THREAD

**Issue by mst-marcernst** [Microsoft/vscode#22727]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|c|vscode|0.1.0|
|csharp|ms-vscode|1.6.2|;

---

Steps to Reproduce:

1. Install VS Code
2. Scroll via TouchPad :-D

I'm using a Surface Pro 4 with the Touch Cover. Scrolling via mouse works fine, but when I use the touch pad, scrolling gets near impossible and I must revert to PageUp/Down instead.

System Language: German

Thank you for looking into this!

**Comment by NeoLegends** [comment]
Try resizing the window, this issue might be related to #17747.

**Comment by alexandrudima** [comment]
Indeed, let's track in those issues. These were introduced when we adopted the current version of Electron. Hopefully they will go away once we update again next milestone. Known workarounds: resize (restore) and then maximize VS Code back. Let's track in the other issues.
