### ISSUE TITLE
Debugging tsx via NPM does not work if console is set to integratedTerminal or externalConsole, only internalConsole works

### ISSUE THREAD

**Issue by GoldenretriverYT** [microsoft/vscode#227285]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2
- OS Version:  Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Create a new folder
2. `npm init`, install tsx as dev dependency. Create a npm task that runs `npx tsx file.ts`, and a launch.json profile that runs that task.
3. Set the launch tasks "console" property to "integratedTerminal", the debugger will attach at first but dettach before the code is actual ever ran.
4. If you, on the other hand, set it to "internalConsole" it works fine.

![Recording 2024-08-31 at 20 07 47](https://github.com/user-attachments/assets/7133196a-124c-4884-8da6-6d2686d2db0b)

Also tested in Insiders with default extensions, same issue. Also happens with ts-node in place of tsx.

**Comment by connor4312** [comment]
I cannot reproduce this. Please check your terminal configuration and dotfiles (e.g. npmrc) to see if you have anything that would overwrite the `NODE_OPTIONS` environment variable, as this will break debugging.

**Comment by GoldenretriverYT** [comment]
I recently reset my computer and haven't done a lot since, so I doubt its that. And printing NODE_OPTIONS in Node shows that they dont seem to be changed from what vscode passes:

vvvv passed by vscode
![image](https://github.com/user-attachments/assets/ce1d42dc-d961-4731-ac67-a2711d1bc072)

vvvv both variables in node
![image](https://github.com/user-attachments/assets/eb968bdc-b817-4dfa-9617-daca5ff000d5)

**Comment by connor4312** [comment]
Strange can you run the **Developer: Toggle Developer Tools** command and check for any errors that might have been logged there?

**Comment by GoldenretriverYT** [comment]
![image](https://github.com/user-attachments/assets/2187a668-96c9-448a-827a-bab618fdd3ca)
no errors :/

**Comment by GoldenretriverYT** [comment]
Modifying the launch.json to directly use tsx or ts-node without a npm task works, so I assume it somehow breaks because of npm being inbetween?

**Comment by connor4312** [comment]
Got it. Last question, can you share the contents of `C:\Program Files\nodejs\npm.cmd`?

**Comment by GoldenretriverYT** [comment]
Sure
```
:: Created by npm, please don't edit manually.
@ECHO OFF

SETLOCAL

SET "NODE_EXE=%~dp0\node.exe"
IF NOT EXIST "%NODE_EXE%" (
  SET "NODE_EXE=node"
)

SET "NPM_PREFIX_JS=%~dp0\node_modules\npm\bin\npm-prefix.js"
SET "NPM_CLI_JS=%~dp0\node_modules\npm\bin\npm-cli.js"
FOR /F "delims=" %%F IN ('CALL "%NODE_EXE%" "%NPM_PREFIX_JS%"') DO (
  SET "NPM_PREFIX_NPM_CLI_JS=%%F\node_modules\npm\bin\npm-cli.js"
)
IF EXIST "%NPM_PREFIX_NPM_CLI_JS%" (
  SET "NPM_CLI_JS=%NPM_PREFIX_NPM_CLI_JS%"
)

"%NODE_EXE%" "%NPM_CLI_JS%" %*
```

**Comment by connor4312** [comment]
```
FOR /F "delims=" %%F IN ('CALL "%NODE_EXE%" "%NPM_PREFIX_JS%"') DO (
```

that would do it
