### ISSUE TITLE
Cannot use asExternalUri with remote-tunnel in companion extension

### ISSUE THREAD

**Issue by nisargjhaveri** [microsoft/vscode#227253]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version: macOS 14.6 (23G80)

Steps to Reproduce:

1. Connect using remote-tunnel for remote development
2. Have a server running on the remote machine and forward the port and have the local URI using `vscode.env.asExternalUri`.
3. Have an extension running on UI host programmatically connect to this URI. The UI-side extension is designed to work with a remote-side extension as companion which starts the server on the remote.
4. Notice that this works well in remote-ssh, but with remote-tunnel, the companion extension cannot connect to the forwarded URI with authentication failure.

How can the companion extension authenticate to this URL forwarded inside the same VS Code session?

**Comment by nisargjhaveri** [comment]
@connor4312 Any suggestions on how to go about this?

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-remote-release/issues/9195
