### ISSUE TITLE
Customized npm tasks are not found if the script used by the task is the same as a script used by a different custom task

### ISSUE THREAD

**Issue by angolding** [microsoft/vscode#227237]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.4.0
- OS Version: 14.4.1 (23E224)

Steps to Reproduce:

1. Create an npm task in tasks.json that uses a different label and environment but runs the same npm script as a different command
2. Create launch configuration that depends on the npm task configured in step 1
3. launch using the launch configuration in step 2

Expected result: launch configuration is able to find the task by task label
Actual result: launch configuration is unable to find the task

**Comment by meganrogge** [comment]
/duplicate [#93001](https://github.com/microsoft/vscode/issues/93001)
