### ISSUE TITLE
Format using the only available formatter if the default formatter is unavailable

### ISSUE THREAD

**Issue by argvchs** [microsoft/vscode#227232]
Type: **Feature Request**

I want to set Prettier as the default formatter, and there are two ways.

1. Add **a lot of** language specific settings.

    ```jsonc
    {
        "[css]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[html]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[javascript]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[typescriptreact]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[json]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[jsonc]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[markdown]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[typescript]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[typescriptreact]": { "editor.defaultFormatter": "esbenp.prettier-vscode" }
    }
    ```

2. Set Prettier as the global default formatter.

    Since I use some languages ​​that Prettier cannot format, I also need to set **a lot of** language specific default formatters.

    ```jsonc
    {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "[c]": { "editor.defaultFormatter": "llvm-vs-code-extensions.vscode-clangd" },
        "[cpp]": { "editor.defaultFormatter": "llvm-vs-code-extensions.vscode-clangd" },
        "[hosts]": { "editor.defaultFormatter": "foxundermoon.shell-format" },
        "[ignore]": { "editor.defaultFormatter": "foxundermoon.shell-format" },
        "[properties]": { "editor.defaultFormatter": "foxundermoon.shell-format" },
        "[python]": { "editor.defaultFormatter": "ms-python.black-formatter" },
        "[shellscript]": { "editor.defaultFormatter": "foxundermoon.shell-format" }
    }
    ```

I always need to add a lot of settings as you can see.

But if VS Code uses the **only available** formatter when the **default** formatter is **unavailable**, then the settings will be **very simple**:

```jsonc
"editor.defaultFormatter": "esbenp.prettier-vscode" // only need to add one line
```

**Comment by otabekoff** [comment]
Hi @argvchs,

Thank you for bringing this up!

Currently, VS Code does not have an option to automatically use the only available formatter when the default formatter is unavailable. This behavior isn't supported for several reasons:

- **Explicit Formatter Control**: VS Code’s design emphasizes explicit control over formatting for each language. Allowing the editor to automatically switch formatters when one is unavailable could lead to unpredictable results, especially if different formatters apply different styles or rules. This could cause confusion or formatting inconsistencies across various file types.

- **Language-Specific Formatters**: Some languages require highly specialized formatters (e.g., Python's Black or C++'s Clangd), and VS Code needs to ensure that users configure the correct formatter for their specific use case. Automatically selecting the available formatter could lead to unintended behavior, as not all formatters support the same features or standards.

- **Customization Flexibility**: Allowing users to explicitly set formatters per language enables them to tailor their environment based on the unique needs of each language they work with. This provides greater flexibility and ensures that users are in control of the formatting tools applied to their code.

For now, setting language-specific formatters in your settings, as you have outlined, is the best approach to ensure the correct formatter is used where needed. While this does involve adding more configuration, it gives you the reliability of knowing that each language will be formatted according to your preferences.

If you think this feature would improve the overall user experience, you might consider submitting a feature request to the VS Code team for future consideration.

Thanks again for your feedback!

Best regards,  
[Your Name]

**Comment by argvchs** [comment]
The formatting behavior will be always defined, because it will only format if one formatter is available, and if there are two ones, it should prompt me to choose.

You can still explicitly set language specific formatters. This should be the formatter priority:

1. Language specific default formatter.
2. Global default formatter.
3. Available formatters. (prompt if there are >1)

And the current formatting behavior is weird. When I have the following settings:

```json
{
    "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

When I try to format a file that no formatter is available, VS Code shows `There is no formatter for '...' files installed`.

When I try to format a file that has one available formatter, VS Code shows `Extension 'Prettier - Code formatter' is configured as formatter but it cannot format '...'-files`.

**Comment by argvchs** [comment]
The formatting behavior will be always defined, because it will only format if one formatter is available, and if there are two ones, it should prompt me to choose.

You can still explicitly set language specific formatters. This should be the formatter priority:

Language specific default formatter.
Global default formatter.
Available formatters. (prompt if there are >1)

**Comment by argvchs** [comment]
> Hi @argvchs,
> 
> Thank you for bringing this up!
> 
> At first glance, it seems like a really cool idea, and I completely agree—it would be great if we could have such a feature. However, currently, VS Code does not have an option to automatically use the only available formatter when the default one is unavailable. This behavior isn’t supported for a few key reasons:
> 
> * **No Single Universal Formatter**: Even though Prettier is an amazing tool and supports a vast range of languages and technologies, no formatter can cover all languages. If there were a formatter that could handle every language, it would likely become the default. But for now, different formatters specialize in different areas, which is why explicit configuration is necessary. Allowing the editor to switch automatically could lead to unintended formatting results, especially when the available formatter doesn’t fully support the language.
> * **Explicit Formatter Control**: VS Code emphasizes giving users control over which formatter is applied to each language. Automatically switching to an available formatter might lead to unpredictable behavior, causing confusion or inconsistencies in formatting standards across various languages.
> * **Language-Specific Formatters**: Some languages require very specific formatters (e.g., Black for Python or Clangd for C++), and relying on the wrong formatter could lead to incorrect or suboptimal results. It's important that users explicitly set the correct formatter to ensure the right behavior.
> * **Customization Flexibility**: While it involves more configuration, setting language-specific formatters ensures that users can tailor their setup for each language. This avoids situations where formatters are applied incorrectly due to automatic switching.
> 
> For now, the best approach is still to explicitly configure the formatters as you've outlined. While it adds more settings, it ensures that each language is formatted correctly and according to your preferences.
> 
> If you believe this feature would significantly improve the user experience, I recommend submitting a feature request to the VS Code team for future consideration.
> 
> EDIT: Setting up default formatters for your specific languages is actually a better approach. Once you configure the default formatter for each language, it remains consistent and reliable, ensuring that each language is formatted according to your preferences. This setup, while involving some initial configuration, avoids the potential issues that could arise from automatically switching formatters. It gives you control over which formatter is applied and helps maintain predictable and accurate formatting results.
> 
> Thanks again for your input and for understanding!
> 
> Best regards, Otabekoff

AI generated content?

**Comment by thernstig** [comment]
I would not like the implicitness of this. I am an explicit-over-implicit guy especially when it comes to important things like formatting.

In addition, I have found that using the language identifier specific way to set the default formatter should always be used. There is a risk otherwise that if you have a repo where only configure `"editor.defaultFormatter": "esbenp.prettier-vscode"` and expect that to be used for that repo, it will not work if a user in their user settings have done a language specific override.

My recommendation is to always configure all formatters used for a project in the .vscode/settings.json to  be on the safe and explicit side. It also makes it more apparent as the proejct grows and new users join what formatters are used.
