### ISSUE TITLE
source control 

### ISSUE THREAD

**Issue by annsmustafa191** [microsoft/vscode#227276]
Type: <b>Bug</b>

source control not working as intended it keeps on loading doesnot show changes and if changes are present on syncing it keeps showing the files , even if the files are added manually and commited they are still visible in the source control window , its kind of annoying to do everything manually when you have got a feature for that previously , hope you rectify it soon . thankyou .

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1355U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.65GB (13.61GB free)|
|Process Argv|--crash-reporter-id 8312c386-0ae7-44ed-9e58-fbdb18b6b6c7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.2.0
atlascode|atl|3.0.10
gitlens|eam|15.3.1
angular-essentials|joh|18.0.0
Angular2|joh|18.0.2
vscode-peacock|joh|4.2.2
vscode-docker|ms-|1.29.2
remote-containers|ms-|0.380.0
remote-wsl|ms-|0.88.2
material-icon-theme|PKi|5.10.0
vscode-yaml|red|1.15.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/226955#issuecomment-2315207526 might help you.
