### ISSUE TITLE
Linux native context menu scrolls

### ISSUE THREAD

**Issue by alihassancods** [microsoft/vscode#227296]
Type: <b>Feature Request</b>

Since the last update, you guys introduced Chrome's Native Menu. Seriously we want the complete VSCode UI design(the same design which is used in windows such as search bar on in Linux based systems. You guys introduced Google Chrome native menu everywhere even in ur menu bar. And the menu which appears on right click(context menu). The UI on windows is way better than linux. As it has search bar on top. Doesn't have any scrolling context menu. 
I request that you guys should keep the same ui design everywhere instead of using GTK/QT on linux.
# I hate the little down arrow showing at the bottom of the menu.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Linux x64 6.8.0-40-generic
Modes:

**Comment by MasterIO02** [comment]
Seconded, the 1.92.x update brought an ugly and very spaced context menu (the same than on Chrome/Chromium) that is barely usable when you have more than 10 options since you need to scroll.
Downgraded to 1.91 for the meantime.

**Comment by benibenj** [comment]
You can configure the `window.titleBarStyle` setting to custom in VSCode to enable the custom title bar and context menu. This is the default title bar / context menu we use on windows.

**Comment by benibenj** [comment]
@deepak1556 Has there been a change to context menus in the latest electron update? The font size seems much larger than usual, leading the context menu to scroll.

Ubuntu 22.04.4 LTS, Gnome 42.9:
![peek_2024-09-03_10-29_360](https://github.com/user-attachments/assets/9cb33105-aea8-4312-9438-9a91da2e1a60)

// cc: @bpasero

**Comment by deepak1556** [comment]
@benibenj yes there seems to be an upstream regression and is tracked in https://github.com/microsoft/vscode/issues/224515. Relevant upstream issue https://github.com/electron/electron/issues/42262

Please follow https://github.com/microsoft/vscode/issues/224515 for updates.
