### ISSUE TITLE
VSCode run very slow inside virtualbox VM + windows 10 guest os

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#22728]
VSCode run very slow inside virtualbox VM + windows 10 guest os
The cpu usage very high, the UI slow . very slow.
But notepad++ run very fast.

**Comment by weinand** [comment]
On what platform? are you running Virtualbox?

I'm running VS Code inside Parallels VM (on macOS) and I do not see any slowness.

**Comment by weinand** [comment]
I suggest not to run VS code in a virtual box if this is too slow.
There are no plans to optimise VS Code for this use case.

**Comment by Artox** [comment]
I experience the same ridiculous slowness. Windows 10 Host, Windows 7 guest: working liek a charm on the host, and takes 2 minutes only to start up on the guest.
Sad that this is a won't fix, because even sophisticated applications like Firefox work well in the guest.
