### ISSUE TITLE
consuming 100% cpu on windows server

### ISSUE THREAD

**Issue by surajds** [Microsoft/vscode#22724]
Hi,

 I've installed vscode on a AWS windows server. Whenever opening vscode, it starts consuming 100% cpu by default. I've not installed any plugins yet and version is up to date.

**Comment by bpasero** [comment]
@surajds ist that a single core CPU VM?

**Comment by surajds** [comment]
yes it is

**Comment by bpasero** [comment]
ok, this is https://github.com/Microsoft/vscode/issues/17097
