### ISSUE TITLE
Distorted Graphic

### ISSUE THREAD

**Issue by DennDenn0** [microsoft/vscode#227217]
![image](https://github.com/user-attachments/assets/47633cf2-7997-4d25-bee1-939ad8583443)
vsc suddenly become distorted like that and every time I move my cursor, the distortion keeps flickering like crazy

**Comment by rzhao271** [comment]
Does [disabling hardware acceleration](https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration) help?
