### ISSUE TITLE
JS/TS language services keeps crashing

### ISSUE THREAD

**Issue by AjelmarMedina** [microsoft/vscode#227398]
JS/TS language services keeps crashing. I'm using codespaces, and it keeps crashing. I'm using a 2-core 16GB RAM 32GB storage machine. It used to run smoothly with no problem just yesterday. Unfortunately, just today, it has kept crashing and is barely workable. I've also tried disabling extensions, and even restarting my computer. I suspect that codespaces is too heavy for my physical device-- 2GB RAM, Intel Celeron N3050, 32GB Storage, outdated Windows 10 x64

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by mjbvz** [comment]
> 2GB RAM

Is this the machine where the code space is running, or the machine you are connecting from?
