### ISSUE TITLE
where is the tasks?

### ISSUE THREAD

**Issue by lyhopq** [Microsoft/vscode#22736]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.6.2|
|project-manager|alefragnani|0.13.4|
|code-gnu-global|austin|0.2.1|
|vscode-eslint|dbaeumer|1.2.7|
|vscode-dash|deerawan|1.4.0|
|python|donjayamanne|0.6.0|
|tslint|eg2|0.8.1|
|code-runner|formulahendry|0.6.14|
|mdmath|goessner|1.2.6|
|CppSnippets|hars|0.0.7|
|vscode-elixir|mjmcloug|0.2.0|
|cpptools|ms-vscode|0.10.4|
|csharp|ms-vscode|1.8.0|
|debugger-for-chrome|msjsdiag|2.6.0|
|vscode-icons|robertohuertasm|7.3.0|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.3|
|vim|vscodevim|0.6.5|
|Material-theme|zhuangtongfa|2.2.7|;

---

Steps to Reproduce:

1. press F1
2. input tasks

[![tasks](http://storage1.imgchr.com/PP9jx.png)](https://imgchr.com/i/PP9jx)

**Comment by dbaeumer** [comment]
This got already fixed for the next release. They are still there but you need to type the Chinese command name. In the next release you can type the English one again.

**Comment by lyhopq** [comment]
ok, thanks!

**Comment by RootMale** [comment]
+1, cant search and run tasks. Cant use them, only create. vscode 1.10.2, but was already broken in 1.10.1
