### ISSUE TITLE
breadcrumbs for files with the same name opened at the same time won't update 

### ISSUE THREAD

**Issue by gitgud5000** [microsoft/vscode#227343]
Type: <b>Bug</b>

breadcrumbs for files with the same name opened at the same time won't update when switching between one file and the other. Causing great confusion and sometimes leading to editing the wrong file.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.0-1064-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.82GB (8.54GB free)|
|Process Argv|--log github.copilot=trace --crash-reporter-id 5180629b-4855-4e73-a799-6c45fd0ba14d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 0)|
|Memory (System)|15.53GB (10.93GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: nz-med|
|OS|Linux x64 5.15.0-1064-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (16 x 0)|
|Memory (System)|62.79GB (52.68GB free)|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
vscode-toggle-quotes|Bri|0.3.6
LogFileHighlighter|emi|3.3.2
vsc-material-theme|Equ|34.5.2
vsc-material-theme-icons|equ|3.8.8
vscode-peacock|joh|4.2.2
theme-monokai-pro-vscode|mon|1.3.2
jupyter-keymap|ms-|1.1.2
vscode-ai-remote|ms-|1.0.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
remote-explorer|ms-|0.4.3
vscode-speech|ms-|0.10.0
pdf|tom|1.2.2
vscode-todo-highlight|way|1.0.5
vscode-sql-formatter|adp|1.4.4
ruff|cha|2024.42.0
gitlens|eam|15.3.1
copilot|Git|1.224.0
copilot-chat|Git|0.18.2
vscode-ansi|ili|1.1.7
path-autocomplete|ion|1.25.0
batch-rename-extension|Jan|0.0.6
git-graph|mhu|1.30.0
vscode-azureresourcegroups|ms-|0.9.4
vscode-docker|ms-|1.29.2
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
datawrangler|ms-|1.6.0
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-ai|ms-|1.0.0
vscode-ai-remote|ms-|1.0.0
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-powertoys|ms-|0.1.1
vscode-jupyter-slideshow|ms-|0.1.6
azure-account|ms-|0.12.0
vsliveshare|ms-|1.0.5936
indent-rainbow|ode|8.3.1
explorer-exclude|Pet|1.3.2
vscode-yaml|red|1.15.0
scope-to-this|rha|0.2.1
even-better-toml|tam|0.19.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
wkspc-ranged-t:31125599
fje88620:31121564
aajjf12562:31125793

```

</details>

**Comment by RedCMD** [comment]
I cannot confirm

is there a large delay when before it updates?

**Comment by jrieken** [comment]
Please provide the file names and your settings
