### ISSUE TITLE
how to set user snippet so that no matter when sami can be appeared at end of line?

### ISSUE THREAD

**Issue by charmer1989** [Microsoft/vscode#22733]
example: my setting is:
"fg": {"prefix": "fg ","body": [
"function*($1) {",
"  $2",
"};"],"description": "fg"}

when the cursor in "()", input "fg", enter, result is "(function*(){};)", but i hope "(function*(){});"
英语太挫了, 希望有中文大神指点一下, 在Emacs下可以实现的一个功能, 比如光标在括号里, 输入fg回车, 得到"(function*(){});" 在vscode里只能是"(function*(){};)", 有办法实现么?

**Comment by jrieken** [comment]
Static snippets cannot do that but `CompletionItemProviders`. Have a look at this extension sample https://github.com/Microsoft/vscode-extension-samples/tree/master/completions-sample which implements a basic completion item provider.

**Comment by charmer1989** [comment]
@jrieken thank you for answer, I have success run those samples, learn something about extension, but have not realize the purpose, I will have time to try again !
