### ISSUE TITLE
Unknown Border in Terminal View

### ISSUE THREAD

**Issue by Barzi-Ahmed** [microsoft/vscode#227318]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version: Windows 11 Pro 22631.4112

Hello,

VSCode has a black border surrounding scrollbar in terminal view and window. This wasn't in here before, but it appeared after updating vscode version long time. Please remove it as it is an unpleasant UI thing... Remove this border surronding scrollbar. This issue occurs even when all extensions are disabled.

![img](https://github.com/user-attachments/assets/27d2f790-6e70-4295-939f-001193a6c498)

**Comment by Tyriar** [comment]
This is by design, it's there to align with the scroll bar in the editor. Note that themes control this color so you could report it there if you're not a fan. You can also override it with this setting:

```json
"workbench.colorCustomizations": {
    "terminalOverviewRuler.border": "#0000"
}
```
