### ISSUE TITLE
Improve UX for terminal switcher control. Change the dropdown for a switcher control

### ISSUE THREAD

**Issue by omniscient** [Microsoft/vscode#22737]
In the spirit of the following issues:

https://github.com/Microsoft/vscode/issues/10546
https://github.com/Microsoft/vscode/issues/11889
https://github.com/Microsoft/vscode/issues/8073

It would be great to replace the dropdown control in the terminal pane that indicates what terminal window has the focus to a more user friendly control. Having to click twice is annoying and unnecessary. 

Instead of a dropdown control, a switcher control that displays an icon for each terminal window could be used.

Here's how it might look like:

![image](https://cloud.githubusercontent.com/assets/89523/24001183/d4878cfa-0a33-11e7-847c-853c1ff4386b.png)

The first character in the box is the order at which you opened the terminal and the second char is the type of terminal in that window.

That way, you have one click to focus on the terminal you need and it works with split view, tabs, etc.

**Comment by Tyriar** [comment]
This would be solved when we look at https://github.com/Microsoft/vscode/issues/10546, https://github.com/Microsoft/vscode/issues/7504 might also be worth subscribing to.

In the meantime I recommend setting up some keybindings so you can switch between the terminals more easily, here's mine:

```js
{ "key": "ctrl+shift+j",    "command": "workbench.action.terminal.focusNext" },
{ "key": "ctrl+shift+k",    "command": "workbench.action.terminal.focusPrevious" }
```
