### ISSUE TITLE
VSCode hangs indefinitely after adding new remote to git repo

### ISSUE THREAD

**Issue by draghiallestero** [microsoft/vscode#227317]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version: Ubuntu 24.04.1 LTS

Steps to Reproduce:

This appears to happen with any folder, although I have not tested if it happens with only particular remote names (I'd wager not).

1. Open any folder in VSCode using Open Folder, let's call it `crash-test`. The folder should be empty, although it doesn't have to be
2. Run `git init`
3. Run `git remote add anyname git@github.com:draghiallestero/anyname.git`
4. Reload window using the command palette

VSCode will hang forever upon the window being opened. In fact this also happens if you open the folder containing `crash-test`.

**Comment by gjsjohnmurray** [comment]
Does the problem also happen after you disable the scm.showHistoryGraph setting?

**Comment by draghiallestero** [comment]
It does. I disabled the setting, closed and reopened VSCode, then repeated the steps. Still hangs.

I should add some context I forgot in the issue description itself. I first noticed this happening to a real repository of mine. The moment git got to some point in the cloning step, VSCode hung. After a bunch of testing I narrowed it down to those few repeatable steps, but originally I was not adding any remotes (since I never got past cloning).

**Comment by lszomoru** [comment]
Are you running those steps from the integrated terminal? 
What happens if you try to add the remote using an external terminal?

**Comment by draghiallestero** [comment]
This is perhaps embarrassing to admit, but the problem just... went away. Nothing changed on my end, didn't upgrade any packages. All that could have affected this is me booting into Windows and back to Ubuntu since I have them both on my laptop (I did test the obvious before writing the issue and restarted my laptop several times).

Apologies for the time spent reading this. I'll keep it open for a few days in case the issue returns, otherwise I'll close it.

**Comment by lszomoru** [comment]
Nothing embarrassing. Please feel free to reopen the issue in case it reoccurs. Thank you!
