### ISSUE TITLE
Diff tool ignores indentation in these files

### ISSUE THREAD

**Issue by ldeluigi** [microsoft/vscode#227360]
Type: <b>Bug</b>

Create a file named "a.txt" with the following content:
```
{
  2023-12-31: [
    {
      A: {
        B: main,
        C: {
          D: B1,

```

Then create a file named "b.txt" with the following content:
```
{
  2023-12-31: [
          {
            A: {
              B: main,
              C: {
                D: B1,

```

Then go into the folder containing both files with a terminal and launch `code --diff a.txt b.txt`

The diff editor pops up but no red/green markings are shown, because vs code doesn't recognize the different indentation levels as different blocks!

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes: Restricted

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.2.0
vscode-lark|dir|0.1.0
vscode-drawio|hed|1.6.6
plantuml|jeb|2.18.1
vscode-docker|ms-|1.29.2
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
vsliveshare|ms-|1.0.5936
vscode-yaml|red|1.15.0
vscode-icons|vsc|12.8.0

</details>

**Comment by RedCMD** [comment]
do you have `diffEditor.ignoreTrimWhitespace` enabled?
![image](https://github.com/user-attachments/assets/46af4350-83be-4774-8eb5-622274eb3fd7)

**Comment by ldeluigi** [comment]
Whops! I submitted a false positive. This was the option I had to enable:
![image](https://github.com/user-attachments/assets/b66bfffb-c0a3-4983-8f0b-4cef6823a8a0)

I didn't notice until now, and I've been using vs code for years! Thanks.

Side note: maybe if due to that option there are no visible differences, a suggestiion info box to enable it would be great?
