### ISSUE TITLE
Workbench Layout Tabs and Fav Tabs

### ISSUE THREAD

**Issue by Ordensbruderbogdan** [microsoft/vscode#227319]
Type: <b>Feature Request</b>

Hello,

Workflow in VScode would be much better if there would be no min-size limit for Tabs and Tab groups. If you've opened more than 3 Tab Groups its nearly impossible to work with vscode because the Tabs 'have to' be at least about 20% of the screen, even if they're not needed. It would be much better if the user could fold that Tab Grous and Tabs as much as he want. Even totally closed but 2cm. The Tabs he will need later would not be closed, but just moved out of the view to be able to unfold them again when the user needs another tab.

Also it would be a possible good addition to add some 'Favorite Files' button, to be able to quickly open frequent used project files in larger projects.

Thank you and Have a nice day.
Great Software!

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by gjsjohnmurray** [comment]
For favorites there are extensions such as https://marketplace.visualstudio.com/items?itemName=howardzuo.vscode-favorites
