### ISSUE TITLE
Temporary search file exclusions fail when expression includes comma (Insiders only)

### ISSUE THREAD

**Issue by aliblong** [microsoft/vscode#227384]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Search within files and use a temporary files-to-exclude pattern that includes a comma

## Examples
Example on VSCode 1.93.0-insider (bugged):
![image](https://github.com/user-attachments/assets/29b6aef7-504a-4ec3-8fbe-eedad56636be)
Example on VSCode 1.92.2 (working):
![image](https://github.com/user-attachments/assets/294283f4-5c18-4f84-8719-fd5c8a5c153d)
Example on VSCode 1.93.0-insider where _no_ comma is used (working)
![image](https://github.com/user-attachments/assets/e3a1a03f-43bd-45cb-89dd-e69b596f4409)

**Comment by IllusionMH** [comment]
Are you on latest Insiders build? I had this problem ~ 1.5 week ago, but it started working as expected last week.

Version: 1.93.0-insider
Commit: 336db9ece67f682159078ea1b54212de7636d88a
Date: 2024-08-30T18:47:32.318Z (3 days ago)

**Comment by aliblong** [comment]
Seems like updating did the trick. I applied the update before checking what commit I was on.

**Comment by aliblong** [comment]
My b. I must have done a bad job looking for similar issues.
