### ISSUE TITLE
VsCode Welcome Page not going away even if I set the workbench.startupEditor to none. 

### ISSUE THREAD

**Issue by mike-rambil** [microsoft/vscode#227327]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2
- OS Version: Windows 11

Steps to Reproduce:

1. Open Vscode and disable start up welcome page to become none by either unchecking the "Show welcome page on start up" or by manually doing to settings page and changing the json to none.
2. On next vscode launch, I still get the welcome page and the box is still unchecked and the json is still set to none instead of welcome page.

![image](https://github.com/user-attachments/assets/1cdba61b-fe87-447c-bbdb-a8e528666fc6)
> Here note that the box is unchecked, however the welcome page is still here on startup of vscode.

**Comment by gjsjohnmurray** [comment]
If you close the Welcome tab before you exit VS Code does it appear again when you relaunch?

**Comment by mike-rambil** [comment]
Doesn't help. I have created a screen recording - [Link](https://jam.dev/c/e1c81489-69cb-4f75-8923-67df9502ce61)

**Comment by chrmarti** [comment]
What do you have the startup editor setting set to?
![Image](https://github.com/user-attachments/assets/508a1f5a-cd8a-4f0c-add9-6e6526035185)

**Comment by mike-rambil** [comment]
It's always been "none". I should tell you I have been using VsCode for about 3-4 years and this problem arise only a couple of weeks ago. Not sure why...Could it be my plugins? 

![image](https://github.com/user-attachments/assets/61bee6d7-ff35-4cef-9859-0c26f1a20d27)

@gjsjohnmurray @chrmarti @bhavyaus

**Comment by bhavyaus** [comment]
Unable to reproduce this. Could you please try this scenario out on a newer newer release (1.93) of VSCode?
