### ISSUE TITLE
not abel to toggel screen size

### ISSUE THREAD

**Issue by Karang15** [microsoft/vscode#227371]
Type: <b>Performance Issue</b>

after applying some extension

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|5.86GB (0.87GB free)|
|Process Argv|--crash-reporter-id 37e59e7f-f3f9-41fe-bdac-6e17bb608bf6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   100	 18244	code main
    0	    13	  1432	   crashpad-handler
    0	   104	  4472	window [3] (Issue Reporter)
    0	   237	  5520	window [2] (script.js - zero-cross - Visual Studio Code)
    0	    23	 13796	   utility-network-service
    0	   117	 19168	   gpu-process
    0	    53	 19208	shared-process
    0	   146	 19508	extensionHost [2]
    0	    77	  1508	     electron-nodejs (tsserver.js )
    0	    50	  9672	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    37	  4136	     "C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=19508
    0	    33	  7360	     electron-nodejs (server.js )
    0	    44	  7640	     electron-nodejs (tailwindServer.js )
    0	    28	 11848	     c:\Users\Lenovo\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.187.0\x86_64-pc-windows-msvc\TabNine.exe --tls_config insecure=false --no-lsp=true --client=vscode --client-metadata clientVersion=1.92.2 pluginVersion=3.147.0 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-extension-kind=1 "vscode-theme-name=Material Theme Palenight" vscode-theme-kind=Dark vscode-machine-id=5269f09fbd42f340d4ff4d4c59b2daa62083332eae12e233ea48b333f7bbf48c vscode-is-new-app-install=false vscode-session-id=d1fefaca-c538-49fb-9769-7150cd65f96a1725272630635 vscode-language=en "vscode-app-name=Visual Studio Code" vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true vscode-code-lens-enabled=true vscode-found-intellicode=false ide-restart-counter=0
    0	     5	 20124	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    57	 20308	       "c:\Users\Lenovo\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.187.0\x86_64-pc-windows-msvc\TabNine.exe" --tls_config insecure=false --no-lsp=true --client=vscode --client-metadata clientVersion=1.92.2 pluginVersion=3.147.0 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-extension-kind=1 "vscode-theme-name=Material Theme Palenight" vscode-theme-kind=Dark vscode-machine-id=5269f09fbd42f340d4ff4d4c59b2daa62083332eae12e233ea48b333f7bbf48c vscode-is-new-app-install=false vscode-session-id=d1fefaca-c538-49fb-9769-7150cd65f96a1725272630635 vscode-language=en "vscode-app-name=Visual Studio Code" vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true vscode-code-lens-enabled=true vscode-found-intellicode=false ide-restart-counter=0 --no_bootstrap
    0	    38	 14160	     electron-nodejs (eslintServer.js )
    0	    35	 19544	     "C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=19508
    0	    56	 19596	     "C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=19508
    0	    84	 19620	     electron-nodejs (tsserver.js )
    0	    34	 19636	fileWatcher [2]
    0	    20	 20296	ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (script.js - zero-cross - Visual Studio Code)
|    Folder (zero-cross): 3 files
|      File types: html(1) js(1) css(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
nodejs-bundle|1Yi|1.0.0
tailwind-documentation|alf|0.1.15
aws-toolkit-vscode|ama|3.22.0
bracket-pair-color-dlw|Bra|0.0.6
vscode-tailwindcss|bra|0.12.8
npm-intellisense|chr|1.4.5
doxdocgen|csc|1.4.0
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.3.1
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|34.5.2
vsc-material-theme-icons|equ|3.8.8
prettier-vscode|esb|11.0.0
change-case|Fin|0.0.7
vscode-firefox-debug|fir|2.9.10
code-runner|for|0.12.2
gc-excelviewer|Gra|4.2.62
vscode-drawio|hed|1.6.6
vscode-vibrancy-continued|ill|1.1.37
better-cpp-syntax|jef|1.27.1
polacode-2019|jef|0.6.1
init-node-script|Jer|0.0.2
svg|joc|1.5.4
tailwind-config-viewer|Kal|0.0.86
auto-save|mcr|1.0.3
vscode-docker|ms-|1.29.2
vscode-edge-devtools|ms-|2.1.5
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
cmake-tools|ms-|1.19.49
cpptools|ms-|1.22.2
cpptools-extension-pack|ms-|1.3.0
js-debug-nightly|ms-|2024.8.2817
live-server|ms-|0.4.14
awesome-flutter-snippets|Nas|4.0.1
vscode-thunder-client|ran|2.25.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
vscode-standard|sta|2.1.3
tabnine-vscode|Tab|3.147.0
cmake|twx|0.0.17
vscode-icons|vsc|12.8.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-c:31125598
fje88620:31121564
aajjf12562cf:31125794

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate which extension is causing the problem.
