### ISSUE TITLE
Avoid automatic unfolding when passing thru folding code

### ISSUE THREAD

**Issue by charlires** [Microsoft/vscode#22738]
- VSCode Version: 1.10.2
- OS Version: 10.12.3

Steps to Reproduce: Fold a function and pass the caret thru that function using the navigation arrows, function will automatically unfold

1. Is there a way to avoid this to happen
2.If avoiding this is not possible, it will be a nice feature.

**Comment by sean-mcmanus** [comment]
This doesn't repro for me. I don't get any auto unfolding via the keyboard arrows. Maybe an extension is causing it?

**Comment by charlires** [comment]
You are absolutely right it was the VIM emulator extension.
