### ISSUE TITLE
Support for Multiple GitHub Account Logins in VSCode

### ISSUE THREAD

**Issue by inam95** [microsoft/vscode#227315]
Type: <b>Feature Request</b>

I am currently using GitHub Copilot with my personal GitHub account and have a separate GitHub account for work. When working in my "work" profile in VSCode, I need to use my personal GitHub account to access GitHub Copilot features. Simultaneously, I need to log in with my work GitHub account to view pull requests and manage other work-related activities. Logging in with two different GitHub accounts is causing conflicts, making it difficult to use both GitHub Copilot and work-related GitHub features effectively.

Feature Request: I would like to request a feature in VSCode that allows users to easily manage and switch between multiple GitHub accounts. This would enable a smoother experience when using GitHub Copilot with a personal account while also accessing work-related GitHub activities under a separate account. Ideally, the feature would include:

The ability to stay logged in to multiple GitHub accounts simultaneously.
A simple account switcher within VSCode that can toggle between accounts for different features (e.g., Copilot, pull requests).
Clear indicators showing which account is active for which feature, to prevent any accidental actions under the wrong account.
This feature would greatly enhance the productivity and user experience for developers who maintain separate GitHub accounts for personal and professional use.

Thank you for considering this request!

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/127967#issuecomment-2253124828
