### ISSUE TITLE
Tab grouping based on Git branch

### ISSUE THREAD

**Issue by Cadjenovic** [microsoft/vscode#227362]
Introduce a setting which would allow users to have distinct tab groups based on their current git branch.

Example:
Working on branch "A", user has "file1.ts" and "file2.ts" tabs opened. User switches to branch "B" in order to work on a new feature and opens "file3.ts" and "file4.ts". After switching back to branch "A", window would automatically re-open files "file1.ts" and "file2.ts" and close files "file3.ts" and "file4.ts", which would allow user to have distinct workspaces without tab clutter, resulting in much more productive environment.

**Comment by gjsjohnmurray** [comment]
Please take a look at the `scm.workingSets.enabled` setting.
