### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by Rajputlalit** [microsoft/vscode#227309]
![Termiinal](https://github.com/user-attachments/assets/3c2c17ad-1ba2-401e-9293-fba6d58618ff)
Type: <b>Feature Request</b>

I am having issues in the vs code terminal.
The terminal opens but i can not write anything in the terminal
it stays blank and empty, nothing runs..
all i have to do is open a seperate terminal by the window+r shortkey, over and over again to work.
I have tried everythig that needs to be done to fix the issue but the problem with the terminal is still the same.
kindly look into the matter ASAP!
I wish this will be done.
Thanks!

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 6.2.9200
Modes:

**Comment by gjsjohnmurray** [comment]
What Windows version are you using? VS Code is reporting an old one. If that is not the case please check whether the shortcut you launch VS Code from has been configured to use Windows 8 compatibility mode.

**Comment by Rajputlalit** [comment]
I am using Windows 10 Pro
and i feel like that should not be issue...

**Comment by Rajputlalit** [comment]
> What Windows version are you using? VS Code is reporting an old one. If that is not the case please check whether the shortcut you launch VS Code from has been configured to use Windows 8 compatibility mode.

I will try to install windows again..
hope that works...

**Comment by Rajputlalit** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.92.2. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

I have tried done that!
i installed the latetst version again and tried the insider too!
but its not done.

**Comment by meganrogge** [comment]
Would suggest disabling all installed extensions. Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal

**Comment by meganrogge** [comment]
Also, any errors in the dev tools console?

**Comment by Rajputlalit** [comment]
> Also, any errors in the dev tools console?

nope..

**Comment by gjsjohnmurray** [comment]
> VS Code version: Code 1.79.2 ([695af09](https://github.com/microsoft/vscode/commit/695af097c7bd098fbf017ce3ac85e09bbc5dda06), 2023-06-14T08:57:04.379Z)
> OS version: Windows_NT x64 6.2.9200

VS Code thinks it is running on an older Windows version, so won't update itself to the current release (1.93).

Are you launching VS Code from a Windows Start menu entry or desktop shortcut that has been set to use a Compatibility Mode?

If you open a Windows command window what version of Windows does that report? Then when you launch VS Code by typing `code` what Windows version does VS Code's Help/About menu option report?
