### ISSUE TITLE
`Press To ask GitHub Copilot` prompt being displayed in Diff editors

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#227336]
Steps to Reproduce:

1.  Create a new typescript file in vscode repo
2.  Go into SCM and view the differences
3. The file on the right will end up being displayed with the text `Press to ask GitHub Copilot to do Something`

This same message appears in the mult-file diff view
This same message appears for new cells added and viewed in SCM, See here https://github.com/microsoft/vscode/issues/226819

![Screenshot 2024-09-02 at 10 40 23](https://github.com/user-attachments/assets/87957bb2-1013-4a7a-9cbc-1336e9057ffa)

**Comment by joyceerhl** [comment]
This is as designed because the right hand side of the diff is not readonly. Note that there is separate code for the notebooks version so you can pursue a different fix for https://github.com/microsoft/vscode/issues/226819
