### ISSUE TITLE
Allow finding in files selected in SCM

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#227363]
* Have a symbol, say `a` which is used in 200 files
* Have a symbol, say `b` which is used in a subset of those 200 files, like in 50 files
* Suppose all usages of `a` where `b` is used need to be migrated: `a` -> `a2` and `b` -> `b2`
* Do a replace in files to replace `b` with `b2`
* At this time, the SCM viewlet contains exactly the 50 files where `a` needs to be migrated to `a2`
* It is not possible to operate on those 50 files because all instances of `a` will be found (200 files)
* It would be nice if I could right click on the changed files in the SCM viewlet and use that to define the search context.

**Comment by andreamah** [comment]
I've been tracking ideas for "search in specific files/ranges` in this issue https://github.com/microsoft/vscode/issues/20530. Please leave a comment there for this. Once we have better infrastructure for this type of search, I can start implementing these types of ideas (potentially as part of an API).

/duplicate https://github.com/microsoft/vscode/issues/20530
