### ISSUE TITLE
TypeScript "Add missing import" root path and quotes configuration

### ISSUE THREAD

**Issue by seishin4real** [Microsoft/vscode#22731]
- VSCode Version: 1.20.2
- OS Version: Windows Server 2008 R2 Enterprise

Steps to Reproduce:

1. write some code with type not yet imported to the file ex. `x: SomeType;`
2. place cursor on the type - yelow lightbulb shows up in the gutter
3. click it and select "Import SomeType from "app/common/some-type"

problems which could be fixed with config options:
1. the inserted "from" path starts with "app" which is kind of absolute but not really - my dir structure is `<project>/src/app/...`, where <project> is the folder opened in vscode. in my team we prefer paths relative to the edited file.
2. the "from" path is surrounded with double-quotes - some projects use single-quotes and tslint shows warnings.

**Comment by mjbvz** [comment]
Configuring quotes for missing imports is being tracked upstream: https://github.com/Microsoft/TypeScript/issues/13270

As for using absolute imports, try adding a `jsconfig.json` file to the root of your project with a `baseUrl` set:

```json
{
  "compilerOptions": {
    "baseUrl": "./src"
  }
}
```

This will create imports of the form:

```ts
import { abc } from "app/otherFile";

abc()
```
