### ISSUE TITLE
Selected Python Interpreter changes automatically

### ISSUE THREAD

**Issue by Tuhin-thinks** [microsoft/vscode#227300]
Type: <b>Bug</b>

Selected Python Interpreter changes automatically, when a different Python interpreter is selected from any external terminal.

In my case, you'll see the `requests_env` is continuously getting activated even when I have manually selected `auto_env` from the F1 menu.

I will attach the video file demostrating the same.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Linux x64 6.8.0-060800-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx (8 x 3667)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|7, 4, 2|
|Memory (System)|15.43GB (3.98GB free)|
|Process Argv|. --crash-reporter-id 2de9ee3f-1b65-45f4-8b80-cc7f3fda0086|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
vscode-sql-formatter|adp|1.4.4
vscode-django|bat|1.15.0
modulestf|bet|0.0.10
markdown-mermaid|bie|1.23.1
npm-intellisense|chr|1.4.5
vscode-eslint|dba|3.0.10
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
vscode-babel-coloring|dza|0.0.4
gitlens|eam|15.3.1
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
copilot|Git|1.224.0
copilot-chat|Git|0.18.2
vscode-pull-request-github|Git|0.94.0
google-translate|han|1.2.9
vsc-python-indent|Kev|1.18.0
mypy|mat|0.4.0
vscode-language-babel|mgm|0.0.40
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
flake8|ms-|2023.13.12291011
isort|ms-|2023.10.1
pylint|ms-|2023.11.13481007
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
datawrangler|ms-|1.6.0
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
sqltools|mtx|0.28.3
autodocstring|njp|0.6.1
material-icon-theme|PKi|5.10.0
bootstrap-product-icons|rub|1.0.2
code-spell-checker|str|3.0.1
even-better-toml|tam|0.19.2
win-ca|uko|3.5.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
wkspc-ranged-c:31125598
fje88620:31121564
aajjf12562cf:31125794

```

</details>

**Comment by Tuhin-thinks** [comment]
Here's the screen recording for the same.

https://github.com/user-attachments/assets/77c2385c-7f0d-4ed2-90d6-75c77338598e

**Comment by roblourens** [comment]
Please file this on the repo for the Python extension, thanks!
