### ISSUE TITLE
Syntax errors when reexporting default in index.js file

### ISSUE THREAD

**Issue by ardentum** [Microsoft/vscode#22732]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.3.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ejs-language-support|QassimFarid|0.0.1|
|jsx|TwentyChung|0.0.1|
|python|donjayamanne|0.5.5|
|autoimport|steoates|1.2.2|
|ReactSnippets|xabikos|1.2.0|
|Material-theme|zhuangtongfa|2.2.7|;

---

Hi! I have a very unpleasant bug with reexporting default submodule export in index files. It is a very common case for me and it works with current bundler (Webpack), but looks broken in the editor.

Steps to Reproduce:

1. Create `submodule.js` file with following content: 

```
export default function DefaultExport () {}
export function TestExport () {}
```
2. Create `index.js` with reexports:
```
export default from './submodule1.js';
export TestExport from './submodule1.js';
```

VS Code highlights reexports as syntax errors and breaks "Go To Definition" logic, which is very useful.

![](https://cloud.githubusercontent.com/assets/654461/23992643/b930af3e-0a4e-11e7-96fc-47f87e55b3ee.png)

Here is my jsconfig.json file:
```
{
    "compilerOptions": {
        "target": "ES6",
        "jsx": "react"
    },
    "exclude": [
        "node_modules",
        "build",
        "tools",
        ".idea"
    ]
}
```

Thanks!

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14697

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14698
