### ISSUE TITLE
A  history table or  chatbot to remember my commands

### ISSUE THREAD

**Issue by alien-cyber** [microsoft/vscode#227375]
I try out so many new languages,framworks(js).I browse everytime to search the correct commands or go to chatgpt.
sometimes for some application like EAS in reactnative ,new tread in chatgpt dont give the correct answer.
In command promth by pressing pgUp we can find the commands used in previous project but that is unordered and consumes so much time .
Would love to have an chatbot to ask it directly which commands I used in which project or an history table which refreshes when switching folders showing it. 

I am not an contributor yet to VScode.If you dont find enough time solving this can you guide me on solving this one.

**Comment by roblourens** [comment]
You're looking for the terminal commands that you ran? The command "Terminal: Run Recent Command" might help you

**Comment by alien-cyber** [comment]
Thanks.  is there a  command which shows commands  runned in specific project(folder)
