### ISSUE TITLE
Calculate grade

### ISSUE THREAD

**Issue by 17lantti** [microsoft/vscode#227388]
I can not calculate my grade for some reason?? or submit this assignment

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/causedByExtension please use your course support channel
