### ISSUE TITLE
Named capturing groups are only available when targeting 'ES2018'

### ISSUE THREAD

**Issue by nbouvrette** [microsoft/vscode#227409]
Does this issue occur when all extensions are disabled?: Yes/No

N/A

- VS Code Version: 1.92.2
- OS Version: macOS 14.6.1 

Steps to Reproduce:

1. Clone this branch of this repo: https://github.com/next-multilingual/next-multilingual/tree/eslint-flat-config
2. Run `npm install --legacy-peer-deps`
3. From the root of the project run: `npx eslint cypress/e2e/dynamic-routes/dynamic-routes-identifier.cy.ts --debug` you will see no issues with the file
4. Now open the file in VSCode and you will see errors with the regular expressions

You can check there are 2 `tsconfig.json` files (a main one, and one for Cypress) both have ES2018 or later.

**Comment by dbaeumer** [comment]
This problem is not reported by ESLint. It is reported by the TypeScript compiler. See

<img width="576" alt="image" src="https://github.com/user-attachments/assets/c30cbb95-c794-493e-aca8-0b3df9ecb267">

`ts(1503)` at the end of the message.

**Comment by alexgladd** [comment]
Why did this close? What is the resolution?

I'm also having this issue in 1.93.1 even though my project's `tsconfig.json` specifies a `lib` of `ES2023`.

**Comment by dbaeumer** [comment]
@mattbierner didn't anything change in terms of the TS language server that gets shipped in VS Code.

**Comment by nbouvrette** [comment]
@dbaeumer good find - looks like this is tied with how VSCode use the TypeScript compiler. I suspect that you are not using the correct `tsconfig` files - I was able to trigger another similar issue here:

https://github.com/properties-file/properties-file/blob/90a2f929ce6049273c25833800a3a8cb7352a5ba/src/build-scripts/build.ts#L106

```sh
Property 'replaceAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.ts(2550)
```

In this case I have 2 `tsconfig`, the main one which ignores the directory `src/build-scripts` which targets `es5` and the second one `tsconfig.build-scripts` which includes `src/build-scripts` and targets `ESNext`

How to reproduce:

1) clone https://github.com/properties-file/properties-file.git
2) Run `npm install --legacy-peer-deps`
3) open `/src/build-scripts/build.ts` to see the error in VSCode
4) npx `eslint src/build-scripts/build.ts --debug` you will see no issues with the file

**Comment by nbouvrette** [comment]
Good catch @mjbvz - I should have caught this 🤦

I also found another way to resolve this specific problem by adding:

```json
{
  "references": [{ "path": "./tsconfig.build-scripts.json" }]
}
```

 in my main `tsconfig.json` file and then adding:
 
 ```json
{
  "compilerOptions": {
    "composite": true
  },
}
```

in my `tsconfig.build-scripts.json` file - VSCode seems to be able to automatically use the right configuration.

**Comment by nbouvrette** [comment]
Also another workaround, simply create `tsconfig.json` files in directories that use other configuration and making sure that `rootDir": "."` is set.

This seems to make VSCode happy without having to deal with the `composite` implications, such as `"incremental": true`
