### ISSUE TITLE
SignatureHelp UI is still open when completionlist ui open

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#2274]
Repro steps:

   1. type c# code as following to trigger the SignatureHelp UI:
    Console.Beep(
   2. backspace four characters ,signaturehelp ui still exists when completionlist ui display   
   
![33](https://cloud.githubusercontent.com/assets/15098626/12577242/1de2b748-c454-11e5-87fa-75d9a43e69fe.png)

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#18
