### ISSUE TITLE
Go to symbol in workspace leads to nonexisting files

### ISSUE THREAD

**Issue by oleynikandrey** [Microsoft/vscode#22746]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|swagger-viewer|Arjun|1.3.0|
|gitignore|codezombiech|0.5.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|xml|DotJoshJohnson|1.7.0|
|pgsql|doublefint|0.0.7|
|code-runner|formulahendry|0.6.14|
|gc-excelviewer|GrapeCity|1.1.13|
|beautify|HookyQR|1.0.1|
|plantuml|jebbs|1.3.0|
|MagicPython|magicstack|1.0.7|
|PowerShell|ms-vscode|0.10.0|
|vscode-json-transform|octref|0.1.2|
|vscode-docker|PeterJausovec|0.0.13|
|better-merge|pprice|0.5.1|
|language-plantuml|qhoekman|0.0.3|
|todotasks|sandy081|0.4.0|
|searchdocsets-vscode|silverlakesoftware|0.5.2|
|python-extended-snippets|tushortz|0.0.1|
|vim|vscodevim|0.6.5|
|erlang-otp|yuce|0.2.1|;

---

Steps to Reproduce:

1. Open a directory with files
2. Click Ctrl + T and look at list of found symbols - paths to files in witch these symbols are found are incorrect.
<img width="489" alt="code_2017-03-16_19-46-08" src="https://cloud.githubusercontent.com/assets/1157958/24008290/475e0f62-0a82-11e7-8db8-0e1aaaf20996.png">

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by oleynikandrey** [comment]
Without extensions it doesn't work at all.
<img width="459" alt="code_2017-03-17_11-07-41" src="https://cloud.githubusercontent.com/assets/1157958/24034335/fa77b362-0b01-11e7-8d11-efcebfe204ef.png">

**Comment by weinand** [comment]
Then please file the issue against the extension that produces the broken paths.

**Comment by oleynikandrey** [comment]
Why do you think so? 
I have turned off all extensions and described functionality doesn't work.

**Comment by weinand** [comment]
Because the "Goto to symbol" functionality is provided by the Python extension.

**Comment by oleynikandrey** [comment]
I thought that this is the core feature. 
Thank you then.
